### ISSUE TITLE
discussion: hardcoding of paths vs. globals.inc variables

### ISSUE THREAD

**Issue by fichtner** [opnsense/core#1]
Softcoding is generally a good idea, except when system paths must be static as in the case of most of the ports (/usr/local). Sometimes the path is parsed by shell scripts using crude hacks. Sometimes the softcoding is not consistent. Most of the time it's harder to find softcoded paths. Discuss!

**Comment by fichtner** [comment]
@AdSchellevis @jschellevis here is an example commit I promised two weeks ago ;)

**Comment by AdSchellevis** [comment]
Thanks! In my opinion the new code is better readable, although there are some situations where soft coding has some benefits. (for example the config.xml location in the new config parser, it makes the unit easier testable).

**Comment by fichtner** [comment]
Maybe as a rule of thumb soft-code the path once in a function? That reduces diffs further... :)

**Comment by AdSchellevis** [comment]
Well, if the file is only used in one class (with minimal occurrences), the separate function might not be necessary I guess... if a file is abstracted by a class that might be ok too? (config.xml is the best example I think, because this file should eventually only be accessed by one class/object)

**Comment by fichtner** [comment]
If we have wrapper classes file names should never be leaked. That's what models are for. :)

**Comment by AdSchellevis** [comment]
yes :-)

**Comment by fichtner** [comment]
alright, thanks for the feedback. will do some more work then.

**Comment by fichtner** [comment]
Patches ongoing in bit by bit, but question has been answered. Thanks. :)
