### ISSUE TITLE
netflow: restrict selection to capable interfaces

### ISSUE THREAD

**Issue by oparoz** [opnsense/core#1001]
After a reboot, after the 16.1.16 update, I see lots of Netflow related error messages on screen related to the OpenVPN interfaces, but can't find where they're logged.

```
setup ovpnc2 [egress only]
ngctl: send msg: No such file or directory
ngctl: line1: error in file
ngctl: send msg: No such file or directory
ngctl: line2: error in file
ngctl: send msg: No such file or directory
ngctl: line3: error in file
ngctl: send msg: No such file or directory
ngctl: line4: error in file
ngctl: send msg: No such file or directory
ngctl: line5: error in file
ngctl: send msg: No such file or directory
ngctl: line6: error in file
```

Maybe the collector is trying to capture data before those interfaces are ready

**Comment by fichtner** [comment]
I am guessing this will be fixed via #1002, please close if that's the case :)

**Comment by oparoz** [comment]
After I applie the patch, I get the same thing when doing a `service netflow restart`

**Comment by L1ghtn1ng** [comment]
Try doing a system reboot

**Comment by oparoz** [comment]
Just did, nothing has changed

**Comment by oparoz** [comment]
I've just added to the OP that this is a new bug which appeared on 16.1.16.

**Comment by fichtner** [comment]
Not sure this is really new. This is a client running tun or tap?

**Comment by oparoz** [comment]
I had no issue restarting netflow on 16.1.15. The clients are all running tun.

**Comment by fichtner** [comment]
On OPNsense 16.7 this changes to the following because of a ngctl custom patch revert, but mostly the same:

    setup em0
    setup ovpnc1
    ngctl: send msg: No such file or directory
    ngctl: line 1: error in file
    setup em2

It also doesn't work for enc or gif types so far. It means that ng_netflow doesn't work on a lot of interface types and we should restrict this. FWIW, it's definitely not new. :)

**Comment by oparoz** [comment]
>FWIW, it's definitely not new. :)

After having checked the services, I think you're right.
netflow, flowd and flowd_aggregate are up, so despite the error message, things should be working (but Insight is not), so I'll open a separate issue for what's broken.

**Comment by fichtner** [comment]
this hasn't come up for months, it's better to focus on pressing issues
