### ISSUE TITLE
Widget trying to get information about not enabled interface

### ISSUE THREAD

**Issue by oparoz** [opnsense/core#1002]
The system.log is being spammed with messages like this:

```
Jun  8 12:34:01 Empyrion opnsense: /widgets/api/get.php: The command `/sbin/ifconfig 'ovpnc4'' failed to execute
Jun  8 12:34:01 Empyrion opnsense: /widgets/api/get.php: The command `/usr/local/sbin/ifinfo 'ovpnc4'' failed to execute
```

But that ovpnc4 interface does not show up in the list when executing those commands without any argument since it is not active, only defined.

**Comment by fichtner** [comment]
This takes a longer route to fix properly, so what I've done is always creating these interfaces unconditionally, which is kind of similar to what #980 was about, missing interfaces.

You can patch your 16.1.16 using:

     # opnsense-patch 44cd7ae d4d27c1

**Comment by oparoz** [comment]
I applied the patch, but see no change. I suspect something needs to be restarted, but what?

**Comment by oparoz** [comment]
That fixed the problem, thank you.

**Comment by fichtner** [comment]
Yes, this needs a reboot as you can't reconfigure disabled devices at runtime, thanks for confirming. One down, two to go :)
