### ISSUE TITLE
Improve /  test 4g modem support

### ISSUE THREAD

**Issue by AdSchellevis** [opnsense/core#1004]
Test and improve support for 4g modems.
Sponsored by OSNet.eu (https://www.osnet.eu/).

**Comment by fraenki** [comment]
Maybe as a result of this a list of supported or "known to work" 4g devices can be added to the wiki.

**Comment by AdSchellevis** [comment]
yes, we should add something in the docs at some point, let me collect what I've tested here, so we don't forget:

Huawei ME909u-521
Huawei E220

**Comment by fichtner** [comment]
whoopsie, closed the wrong issue

**Comment by fichtner** [comment]
@AdSchellevis merged to stable just now

**Comment by AdSchellevis** [comment]
@fichtner thanks
