### ISSUE TITLE
apinger fails after a while

### ISSUE THREAD

**Issue by oparoz** [opnsense/core#1007]
After a while apinger silently fails and needs to be restarted. This has ben going on for a while and is still a problem on 16.1.6

```
Jun 10 15:27:00	apinger: command (al/opnsense/service/configd_ctl.py -m 'dyndns reload VPN_TCP_VPNV4' 'ipsecdns reload' 'openvpn reload VPN_TCP_VPNV4' 'filter reload' ) exited with status: 127
Jun 10 15:27:00	apinger: Error while starting command form alarm(down) on target(8.8.8.8-VPN_TCP2_VPNV4)
```

**Comment by fichtner** [comment]
the command string is mangled during execution, likely related to earlier changes that were done in order to change apinger's original code a years ago. apinger repo is open, please report it over there instead...  https://github.com/opnsense/apinger

**Comment by oparoz** [comment]
OK, thanks.
