### ISSUE TITLE
Interface Statistics Widget - No Auto Scroll

### ISSUE THREAD

**Issue by vectr0n** [opnsense/core#1008]
Not sure if this is already a known issue or not, but it seems the interface statistics widget does not auto scroll as seen below:

[http://i.imgur.com/d3l7znB.png](url)

It also does not auto scroll when you shrink the browser window, the whole dashboard page scrolls instead of just the widget.

**Comment by fichtner** [comment]
This is part of a larger issue described and discussed in #1003, embedding screenshot for future reference and deferring in favour of the other ticked. Thanks so far!

![d3l7znb](https://cloud.githubusercontent.com/assets/1915288/16141783/649f2600-345f-11e6-90ea-0744f1f883f7.png)

**Comment by knxuf** [comment]
can this not be solved if rows and colums are exchanged?
if the width is a fixed size then the number of interfaces will not produce an overflow.
The width can also be smaller if there are two header rows. The first with the category Packets/Bytes/Errors and the second with in/out

**Comment by fichtner** [comment]
well, you can set your dashboard to less columns to make the widget wider to fit the stats.
