### ISSUE TITLE
firmware: probe mirror status

### ISSUE THREAD

**Issue by fichtner** [opnsense/core#1009]
Now that we have a fancy settings page we should run a quick test to see that the mirror is available, either on save or preferably with an extra button... This stems from the current backend behaviour which does not offer a sensible feedback regarding this.

**Comment by mschilt** [comment]
+1 would also be great to get the latest version available from the server.. 
run into that issue: selected my closest mirror and was unable to update.. because the latest version never reachted that mirror.
