### ISSUE TITLE
Absent combobox for auth backend in openvpn

### ISSUE THREAD

**Issue by FChapeau** [opnsense/core#1012]
I have been trying to setup an openvpn server using OPNSense. I setup LinOTP with FreeRadius to provide two-factor authentication for my server. I setup LinOTP through RADIUS in OPNSense and I am able to authenticate using the authentication tester.

But when I try to login through the VPN using my LinOTP token, I get access denied.

I read that I need to select my RADIUS backend, which makes sense, but I do not see the "Backend for Authentication" combobox in the server configuration panel. I can see the label for it when I resize my browser window so it gets mobile sized (or browse it on mobile), but no combo box.

**Regular sized**
![openvpn opnsense](https://cloud.githubusercontent.com/assets/3579649/16028777/a528b242-31b0-11e6-89a1-d76ec3546ced.PNG)

**Mobile sized**
![openvpn opnsense 2](https://cloud.githubusercontent.com/assets/3579649/16028781/a8fa38be-31b0-11e6-8d18-e32f37a93efb.PNG)

**Comment by fichtner** [comment]
Hi there,

A bug in 16.1.16 prevents the field from showing up. You can patch your installation by running this in the console / root shell:

    # opnsense-patch 6ffc213

Also see: https://forum.opnsense.org/index.php?topic=3191.0


Cheers,
Franco

**Comment by FChapeau** [comment]
I must be losing my Google magic touch. Thank you very much, it works.

**Comment by fichtner** [comment]
no worries :)
