### ISSUE TITLE
The script in core/src/opnsense/www/js/d3.min.js has stopped working (Firefox 47.0)

### ISSUE THREAD

**Issue by Swoy** [opnsense/core#1013]
Leaving a tab with Opnsense on dashboard with the following widgets:

System information
Gateways
Traffic Graphs
Service Status
Interfacelist
Thermal Sensors
Interface Statistics
System Log
Firewall Logs

causes script hang on d3.min.js after a random amount of time. If the user allows the script to continue, the memory is leaking up to several GB for that tab.

Please let me know what additional information you require to locate the issue.

**Comment by AdSchellevis** [comment]
timeout
