### ISSUE TITLE
Support VLANs in new Traffic Graphs (Dashboard)

### ISSUE THREAD

**Issue by elohmeier** [opnsense/core#1014]
The new Traffic Graphs Widget lacks VLAN support. Currently VLANs are displayed (in sum) in the name of the according physical interface. 
It would be great to see each VLAN seperately.

**Comment by fichtner** [comment]
Is this a regression or a feature request? :)

**Comment by elohmeier** [comment]
I guess it's a feature request, as I'm not that sure about the old version.
The new UI is definitely great! Much faster load time.. :)

**Comment by AdSchellevis** [comment]
tested https://github.com/opnsense/core/commit/8405ee77aa736cb850e2ec0a4f8fe41ee967634a on another box with VLANs, all looks good now.
