### ISSUE TITLE
GUI "Firewall: Aliases" fail to add host with "_"

### ISSUE THREAD

**Issue by kalos** [opnsense/core#1015]
An error occur if I add an alias like:

Name: test
Type: Host(s)

Host(s):
- myhost1 (this is OK)
- my_host2 (error: doesn't appear to be a valid hostname or ip address)

If I change the myhost1 later that I create the alias "test", it's ok.

**Comment by fichtner** [comment]
Hi there,

Tested, then found this:

RFCs mandate that a hostname's labels may contain only the ASCII letters 'a' through 'z' (case-insensitive), the digits '0' through '9', and the hyphen. Hostname labels cannot begin or end with a hyphen. No other symbols, punctuation characters, or blank spaces are permitted.

Not sure what to do here as that would mean the validation is correct.


Cheers,
Franco

**Comment by fichtner** [comment]
Yup, hyphens work as expected.

**Comment by kalos** [comment]
![screenshot from 2016-06-16 18-06-21](https://cloud.githubusercontent.com/assets/3465/16124038/9113186c-33ed-11e6-9c89-09abd31fbb43.png)

**Comment by fichtner** [comment]
Now this is a pf.conf restriction of how aliases are inserted into the rule set:

Macros can be defined that will later be expanded in context. Macro names must start with a letter, and may contain letters, digits and underscores.
