### ISSUE TITLE
Syslog Logging for Suricata/IDS

### ISSUE THREAD

**Issue by mschilt** [opnsense/core#1018]
The ability to forward IDS logs via syslog would be great.

Doc:
http://jasonish-suricata.readthedocs.io/en/latest/configuration/suricata-yaml.html?highlight=syslog#syslog

**Comment by fichtner** [comment]
@AdSchellevis since you did this for the proxy, I'm reassigning for 17.1, no strings attached :)

**Comment by AdSchellevis** [comment]
@fichtner sure, no problem
