### ISSUE TITLE
Boot boot good slow

### ISSUE THREAD

**Issue by cvsyun013** [opnsense/core#1022]
Intel(R) Celeron(R) CPU J1900 @ 1.99GHz (4 cores )  2GBMemory  

Boot the upper left corner of a white line beat and start system needs 3 minutes, I would like to ask is my hardware and system startup ability

**Comment by fichtner** [comment]
We'll need:

* Last know version where this worked as expected
* Current version where this doesn't work as expected
* Installed image type
* A screenshot to know which boot loader stage you are referring to

**Comment by fichtner** [comment]
Timeout.
