### ISSUE TITLE
IPS not sending notifiacations

### ISSUE THREAD

**Issue by L1ghtn1ng** [opnsense/core#1024]
I have setup email notifications, but when I enable the eicar test rule to generate a block alert I do not get an email. I have clicked the test smtp check to make sure I receive an email from the firewall and I do but not when an alert is generated.

**Comment by fichtner** [comment]
I don't think it works that way... Notifications are an old subsystem from having forked that needs to undergo a rework as it does not plug into a lot of facilities (only a handful of messages to be honest).

On IDS specifically, it would also cause a lot of spamming. The format of a daily report would be better here coupled with a system that does real time log processing (SIEM).

Can we close this?

**Comment by L1ghtn1ng** [comment]
You can close it and a daily report would be nice

**Comment by fichtner** [comment]
Thanks, I'm consolidating ideas in ticket #1025
