### ISSUE TITLE
Renaming firewall alias doesn't rename it where it is used

### ISSUE THREAD

**Issue by module0x90** [opnsense/core#1028]
Hi,

I am using quite heavily firewall aliases for hosts and als groups. I have the proxy enabled and then a group which devices have to go through the proxy. This "enforce_proxy" group consists of other groups.

So I have enforce_proxy -> group1, group2
group1 -> 1.1.1.1, 2.2.2.2
group2 -> 3.3.3.3, 4.4.4.4

for example.

When configuring the alias enforce_proxy and I key in just a "g", then it displays group1 and group2 in the completion dropdown. I choose group1 then.
Then I edit the alias group1 -> group_user.

The "parent" group "enforce_proxy" is still referring "group1" and not "group_user".

Is this a bug or a feature?
Should it work this way actually?

Cheers

Thomas

OPNsense 16.1.17-amd64

**Comment by fichtner** [comment]
Hi Thomas,

Recursive aliases may very well have this bug, it should rename it where it is used or lock its name if it's being used. Will double check how firewall rules using aliases handle this and likely adapt accordingly.


Cheers,
Franco

**Comment by fichtner** [comment]
Yes, renaming an alias used in a rule renames that alias over there too, so the same must be done for recursive aliases and their usage in rules :)

**Comment by AdSchellevis** [comment]
Just checked at my end, the rename isn't working because the alias "address" field contains a list of aliases which won't match. the following commit will fix and close this.
