### ISSUE TITLE
rc.filter_configure_sync causes empty config flush while plugging "enc0" internally

### ISSUE THREAD

**Issue by fichtner** [opnsense/core#1029]
Hi Ad,

I'm leaving this for you to look at. "enc0" is plugged, but not written to the config. However, $changed_interfaces is still set so the config is flushed creating a spurious revision.

Cheers,
Franco

**Comment by AdSchellevis** [comment]
Hi Franco,

No problem, I found the bug, will fix and close in the next commit.

Cheers,

Ad

**Comment by fichtner** [comment]
super, thanks a lot :)
