### ISSUE TITLE
Two form authentication using LDAP and google authenticator

### ISSUE THREAD

**Issue by moikonom** [opnsense/core#1030]
Hello Ad,

Following our recent conversation on forums, I'm making a request using GitHub. Could you please provide 2FA, using an external LDAP and google authenticator? 

Thanks again for your time and effort.

Kind regards,
Michalis

**Comment by AdSchellevis** [comment]
This https://github.com/opnsense/core/blob/master/src/www/system_authservers.php#L475-L612 including read/write config data needs to be wrapped into getConfigurationOptions() first to be able to inherit from the LDAP connector. I'll keep it on the list, but don't have the time to fix this now. The actual connect should be easy.

**Comment by itn3rd77** [comment]
Hi,

as some time had passed I wanted to ask if this feature is still on the ToDo list. Any updates planned for 18.7?

Thx
Ingo

**Comment by AdSchellevis** [comment]
Hi Ingo,

It’s still on the todo list, but no promises for 18.7, it’s just very busy.

Best,
Ad

**Comment by wilson65o** [comment]
Hello, this would be a fantistic feature to add. Please consider this as a +1 from me. Thanks.

**Comment by gitterdoneplease** [comment]
Yes please on this as well. Google 2FA + LDAP/AD would be fantastic.

**Comment by brainrecursion** [comment]
Any update on if this is being worked on? Would love this.

**Comment by AdSchellevis** [comment]
done, originally I wanted to refactor the settings page (system_authservers.php) as well, but maybe it's better to make it functional first, since the authentication code itself won't really change.
