### ISSUE TITLE
Translation of the permission page is not working

### ISSUE THREAD

**Issue by fabianfrz** [opnsense/core#1037]
In the line https://github.com/opnsense/core/blob/master/src/www/system_usermanager_addprivs.php#L212, is the translation not working

As the ACL codes seems to work correctly (https://github.com/opnsense/core/blob/master/src/opnsense/mvc/app/models/OPNsense/Core/ACL.php#L267) - I assume that the extraction of the strings does not work as they are not available on the translation server. It is only the name, which is displayed on this page (the description works).

**Comment by fichtner** [comment]
I will change the whole thing for 17.1 to remove most static strings for each ACL and auto-generate a description as most of it is duplicated over 100 times... ACLs should be per feature block, not per static page, this is something that has been discussed with @AdSchellevis internally every now and then.

**Comment by fichtner** [comment]
Mostly done(tm)
