### ISSUE TITLE
Issue on Boot

### ISSUE THREAD

**Issue by fabianfrz** [opnsense/core#1038]
It looks like an openssl command fails on boot:

![Error while Booting](https://cloud.githubusercontent.com/assets/3713914/16361528/872d9180-3b93-11e6-9097-f5bde5720ab6.png)

running:
OPNsense 16.7.b_394-amd64
FreeBSD 10.2-RELEASE-p18
LibreSSL 2.3.5

**Comment by fichtner** [comment]
This is about OpenVPN. Haven't looked closer as we don't have actual problem reports in this area. Feel free to investigate.

**Comment by L1ghtn1ng** [comment]
I know you don't have reports of this but as I use openvpn I want to know, that when I upgrade to 16.7 that my VPN will work and the system will be stable. I also use libressl and I thought that a beta is for people to test and find and fix issues before the stable release comes out?

**Comment by fichtner** [comment]
Let's narrow this down to which openssl command invoke fails and if its specific to LibreSSL or not and it'll be fixed in no time that's all I'm saying. :)
