### ISSUE TITLE
IPS not setting new rules to drop

### ISSUE THREAD

**Issue by L1ghtn1ng** [opnsense/core#1039]
I enabled 2 new rule sets and changed them to drop. Upon reviewing the rules after in the rule section tab and doing a search for them. Instead of them saying drop it still said alert. The expected behaviour should of been to change them to drop.

**Comment by AdSchellevis** [comment]
@L1ghtn1ng did you "Download & Update Rules" again after changing the set to drop? If so, please inspect the timestamps of the files to check if your download was actually completed (/usr/local/etc/suricata/rules/).

If possible, can you first use the forum (https://forum.opnsense.org/) before opening new issues? This gives others the opportunity to discuss and help, which increases the chance that issues which are logged contain enough information to solve them.

**Comment by L1ghtn1ng** [comment]
@AdSchellevis No I did not

**Comment by L1ghtn1ng** [comment]
Closing due to user error. Thanks @AdSchellevis for pointing out what I did wrong
