### ISSUE TITLE
IPv6 Enhancement - replace rtsold

### ISSUE THREAD

**Issue by jschellevis** [opnsense/core#104]
In issue #47 @pdf suggested the following for replacing the rtsold functionality by kernel feature:
"..... reading of how configuration would normally be done (outside of OPNsense) for FreeBSD 9+ is that the functionality that rtsol used to provide would now be handled directly by the kernel.

I've got other issues with OPNsense's IPv6 support, for example I'm meant to receive a dynamic /64 for the wan interface - and the appropriate routes to go with it - via RA, and also receive a prefix via DHCPv6-PD for the LAN side. This is currently impossible with OPNsense, and while it's still possible to route traffic over the WAN via link-local, this should be a supported configuration.

First, I'd propose dropping rtsol altogether and spawning dhcp6c explicitly for DHCPv6 interfaces (it's already spawned explicitly for SLAAC interfaces, though that should probably also be tunable, because DNS might be expected via RDNSS, handled by openresolv/resolvconf).
    If either SLAAC or DHCPv6 is selected on the WAN, set sysctl tunables net.inet6.ip6.rfc6204w3 and net.inet6.ip6.no_radr to 1 - this will allow accepting RA messages even when forwarding is enabled, and disable accepting route advertisements on all interfaces by default (necessary to avoid upstream routes landing on the wrong interface). With the default for no_radr set to 1, the WAN interface will need to have the flag inverted (inet6 -no_radr) so that routes will be accepted on that interface.
    With rtsol gone, let the kernel handle handle RA messages by setting the appropriate interface flags. For SLAAC interfaces, or for DHCPv6 interfaces with dhcp6prefixonly enabled, add the inet6 accept_rtadv flag. The default for all interfaces should probably be to disable autoconf by setting net.inet6.ip6.accept_rtadv to 0, so that only interfaces specifically set to accept autoconf actually do so.

I think that should get things into better shape, but I'm just going by the documentation - the only box I have to test on right now is pushing real data."

See #47 for original context for this enhancement. Thanks @pdf!

**Comment by fichtner** [comment]
timeout
