### ISSUE TITLE
[Feature Request] Possible to hide used aliases?

### ISSUE THREAD

**Issue by tsumaru720** [opnsense/core#1042]
I've an alias I use to drop traffic from "naughty" IPs. It'd be nice if I could re-order IPs in that alias so i can sort of keep them grouped together. 

For example if I add some IPs from a particular AS number to my "BLOCKED" alias, then add some other IPs from a different provider, If i want to add more from the first AS, They are at the bottom of the list and I am not able to keep them all near eachother if that makes sense?

I'd rather have a single firewall rule to drop based on alias rather than having lots of aliases/firewall rules

**Comment by fichtner** [comment]
Hi there,

Did you know you can use nested aliases? So there could be one alias per provider and one alias that picks up all providers.


Cheers,
Franco

**Comment by tsumaru720** [comment]
Hi Franco

I did not - That would probably work better for me :)

**Comment by fichtner** [comment]
Hi Simon,

Ok, try it out and if you need more info let me know.

As far as I know the alias has auto-suggest so it'll be trivial to add once you start typing, but it's a lot less obvious before.


Cheers,
Franco

**Comment by tsumaru720** [comment]
Hi Franco

Yeah I've already moved to an alias per AS number and changed my blocked alias to point at those. 

Can I instead suggest that if you're nesting aliases, if it already exists in your list to not show it as an auto-complete option?

**Comment by fichtner** [comment]
Makes sense, I'll adjust the topic, thanks!
