### ISSUE TITLE
[FR] Add password Field to Base/FieldTypes

### ISSUE THREAD

**Issue by gitdevmod** [opnsense/core#1045]
TextField expose password with http://opnsense/api/foo/get, it's not useful. Could you create a PasswordField for this case ?

Thanks

**Comment by AdSchellevis** [comment]
@gitdevmod what do you want to achieve with this? if you want the field presentation for the password type, you can use the password type  (https://github.com/opnsense/core/blob/master/src/opnsense/mvc/app/views/layout_partials/form_input_tr.volt#L64)

**Comment by gitdevmod** [comment]
@AdSchellevis indeed I use password in gui, if I use the web page https://opnsense/api/foo/get the password is displayed in clear but it's maybe needed for action to retrieve all fields.

**Comment by AdSchellevis** [comment]
@gitdevmod you very likely need the content, but can change the presentation (by choosing the password type in the form)

**Comment by AdSchellevis** [comment]
@gitdevmod I've added an "update-only" field for you, you need these two commits to test https://github.com/opnsense/core/commit/5c09fbdf4371582716ae603996775bef1200a97d https://github.com/opnsense/core/commit/c6fdfee89a4fd3512fc20d477bca73993690f6e0
