### ISSUE TITLE
Impossible to grant user permission to import new users from LDAP without grant permission to all pages

### ISSUE THREAD

**Issue by lombizani** [opnsense/core#1046]
* Version used: 16.1.17-i386
* WebGUI URL: /system_usermanager_import_ldap.php
* How to replicate: 
  * Make sure you're linked to an LDAP server and can import users using the user manager as root.
  * Create a new local test user.
  * Edit the new user, go to the Edit Privileges page and click Select All to tick all permissions, but unselect "WebCfg - All pages" after that.
  * Log out and log in as the new user.
  * Go to System -> Access -> Users and click the import button.
  * A window will pop-up, but instead of getting the user import page, you'll be redirected to the index page.

**Comment by fichtner** [comment]
Thanks for this report. There's no ACL entry for system_usermanager_import_ldap.php, that should be easy enough to fix. :)

**Comment by fichtner** [comment]
Patch will be in 16.1.18 today, so no need for manual apply.


Cheers,
Franci
