### ISSUE TITLE
Internal server error when upgrading to 16.1.18

### ISSUE THREAD

**Issue by davidolrik** [opnsense/core#1047]
I'v just updated to 16.1.18, and during the update I got a 500 on `/api/core/firmware/upgradestatus`.

The upgrade completed anyway, so I'm guessing it's only a cosmetic issue due to the API being temporarily unavailable.

I suggest you ignore the 500 error, and just keep trying to update the status window.

**Comment by fichtner** [comment]
Hi David,

Depends from which version you were coming. This was fixed in 16.1.15, any update prior to that will do that because it uses the old code, e.g. 16.1.8 -> 16.1.18.

16.1.18 also enables full detach / reattach, so you can always hit reload to get the progress back as long as it's running.

https://github.com/opnsense/changelog/commit/5ff0b300b8e7ca5165fb4177fb80baf39d98cfdf#diff-e8c90a1cedeae26be96c7d714c2eee19R21


Cheers,
Franco

**Comment by davidolrik** [comment]
Hmm...

Searching the log for `pkg-static: opnsense` gives me this:

```
Jun 30 12:12:26	pkg-static: opnsense upgraded: 16.1.17 -> 16.1.18
Jun 30 12:12:22	pkg-static: opnsense-update upgraded: 16.1.16 -> 16.1.18
Jun 15 20:53:05	pkg-static: opnsense upgraded: 16.1.16 -> 16.1.17
Jun 15 20:52:59	pkg-static: opnsense-lang upgraded: 16.1.14 -> 16.1.17
```

Which would suggest that I was upgrading from `16.1.17` and therefore should not see the bug.
Or am I reading the log wrong?

**Comment by fichtner** [comment]
Hmm, ok, did the progress window stop or did you get the reboot notification?

This is the commit from 2 months ago, should also include 500. https://github.com/opnsense/core/commit/9526856634d491e249c0231f76211839988737b6

**Comment by davidolrik** [comment]
It stopped. - I only saw one 500 on the browser console.

But looking at 9526856, it doesn't look like it includes `/api/core/firmware/upgradestatus`, just `/api/core/firmware/upgrade` and `'/api/core/firmware/'+pkg_act+'/'+pkg_name`

**Comment by davidolrik** [comment]
There is no fail block here:

https://github.com/opnsense/core/blob/9526856634d491e249c0231f76211839988737b6/src/opnsense/mvc/app/views/OPNsense/Core/firmware.volt#L159

**Comment by fichtner** [comment]
Nice catch, thanks!

**Comment by fichtner** [comment]
My bad with this, thanks again @davidolrik !
