### ISSUE TITLE
intrusion detection: multi-pattern matcher option

### ISSUE THREAD

**Issue by fichtner** [opnsense/core#1050]
Hi Ad,

Hyperscan support is coming to our Suricata 3.1, for that we need to set something in suricata.yaml:

    mpm-algo: hs

The current default is: "ac" (Aho-Corasick)
The new option is: "hs" (Hyperscan)

For this we need a select box in the GUI.

Cheers,
Franco

**Comment by L1ghtn1ng** [comment]
Will hyperscan be able to run on an a10? Also with 16.7 is it going to be the default now?

**Comment by L1ghtn1ng** [comment]
Well the a10 is 64 bit so that is fine for me as I will not have to worry about that

**Comment by L1ghtn1ng** [comment]
But would be awesome if this can become the default though

**Comment by fichtner** [comment]
I know, but there are others and this is free software for many platforms. According to the website below, 32 bit is fine.

http://www.intel.com/content/www/us/en/communications/hyperscan.html

It doesn't need to be a default. We start shipping the support, the setting will be permanent. Done. :)

**Comment by L1ghtn1ng** [comment]
Awesome and performance for the win while maintaining security I like it
