### ISSUE TITLE
interfaces: strange dhcp settings behaviour in advanced/override modes

### ISSUE THREAD

**Issue by devste** [opnsense/core#1052]
OPNsense 16.1.18-amd64
FreeBSD 10.2-RELEASE-p19
OpenSSL 1.0.2h 3 May 2016

Page: https://opnsense-host/interfaces.php?if=wan

I had problems getting dhcpv6 up and running on wan. My instinct was to play around on the advanced tab, try some settings, restart the interface and always run /var/etc/rtsold_re1_script.sh (wan is on re1) - as is mentioned in bug https://github.com/opnsense/core/issues/637. I got it working in one specific combination. However then I went looking for the difference:

If I'm on the "basic" tab it works: wan gets two IPv6 addresses and lan gets a public ipv6 assigned.

ifconfig shortened and some values masked

```
re0: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500
	options=82098<VLAN_MTU,VLAN_HWTAGGING,VLAN_HWCSUM,WOL_MAGIC,LINKSTATE>
	inet6 2a02:xxxx:a2dc prefixlen 64 
	inet6 fe80::1:1%re0 prefixlen 64 scopeid 0x1 
	nd6 options=21<PERFORMNUD,AUTO_LINKLOCAL>

re1: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500
options=182098<VLAN_MTU,VLAN_HWTAGGING,VLAN_HWCSUM,WOL_MAGIC,LINKSTATE,NETMAP>
	inet6 fe80::xxxx:a2dd%re1 prefixlen 64 scopeid 0x2 
	inet6 2a02:xxxx:a2dd prefixlen 64 autoconf 
	inet6 2a02:xxxx:28cd prefixlen 128 
	nd6 options=23<PERFORMNUD,ACCEPT_RTADV,AUTO_LINKLOCAL>
```

If I switch to the "advanced" tab, but without filling anything else, then there is only one IPv6 address assigned to re1 (wan) and nothing assigned to LAN. WAN looks like this then:

```
re1: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500
options=182098<VLAN_MTU,VLAN_HWTAGGING,VLAN_HWCSUM,WOL_MAGIC,LINKSTATE,NETMAP>
	inet6 fe80::xxxx:a2dd%re1 prefixlen 64 scopeid 0x2 
	inet6 2a02:xxxx:a2dd prefixlen 64 autoconf 
	nd6 options=23<PERFORMNUD,ACCEPT_RTADV,AUTO_LINKLOCAL>
```

The only difference in configuration is this here (in /conf)

```
--- backup/config-1467826445.4156.xml	2016-07-06 19:34:05.418779000 +0200
+++ config.xml	2016-07-06 19:34:05.427740000 +0200
@@ -301,7 +301,7 @@
       <adv_dhcp6_key_info_statement_keyid/>
       <adv_dhcp6_key_info_statement_secret/>
       <adv_dhcp6_key_info_statement_expire/>
-      <adv_dhcp6_config_advanced/>
+      <adv_dhcp6_config_advanced>advanced</adv_dhcp6_config_advanced>
       <adv_dhcp6_config_file_override/>
       <adv_dhcp6_config_file_override_path/>
     </wan>
@@ -547,7 +547,7 @@
   </widgets>
   <revision>
     <username>root@192.168.1.144</username>
-    <time>1467825559.8815</time>
+    <time>1467826445.4189</time>
     <description>/interfaces.php made changes</description>
   </revision>
   <cert>
```

Expected behaviour: switching over the tab should not really make any difference in behaviour. In other words: if a field is empty I would expect opnsense to use the default values, as if I were on the "basic" tab.

**Comment by devste** [comment]
Config snippet. The only options I changed are "debug" mode in advanced and the prefix delegation size to 48. https://gist.github.com/devste/0d24dd347780313c1af4281c5130c3fc

**Comment by fichtner** [comment]
Nice, thanks for the analysis! Will take a look in the morning and get a fix in. :)

**Comment by devste** [comment]
I had time to look at the [source](https://github.com/opnsense/core/blob/master/src/etc/inc/interfaces.inc#L3372) today, and I think my notion of "default values" in the dhcp6c configuration is a misconception. Maybe giving the user a warning underneath the "advanced" tab would be an easier option for now. A warning or descriptive text that says something like: "The advanced method does not provide any default values, you will need to fill out any values you would like dhcp6 to use."

**Comment by fichtner** [comment]
More trouble with adv_dhcp_config_file_override set but dhcp_config_file_override_path not set. Need to reproduce.
