### ISSUE TITLE
Multiple OpenVPN Servers and Firewall Rules

### ISSUE THREAD

**Issue by fenderle** [opnsense/core#1053]
If I define multiple OpenVPN servers, I still only see **one** OpenVPN Tab in the firewall ruleset. Is this supposed as it should be? How do I setup different rules for the OpenVPN interface? To which interface of the two OpenVPN interfaces do the rules apply?

Or is it maybe a *combined* view on all OpenVPN interfaces? If so, what is the `OPENVPN_NET` alias when? which of the two interface networks? Or is this also combined? 

It would be great if I could get a bit insight in how this is supposed to be used with multiple servers (I need to configure three of them: one roadwarrior and two tunnel endpoints...)

**Comment by AdSchellevis** [comment]
@fenderle yes, you're supposed to see one tab for openvpn. you can use different networks to keep them apart. 
In case you want to use specific rules for roadwarrior clients, you can enforce policies using     client specific overrides.

We have an excellent forum available at https://forum.opnsense.org/ can you please use that for discussions?

**Comment by fenderle** [comment]
Alright - thanks for answering anyway.
