### ISSUE TITLE
2fa usage unclear in documentation

### ISSUE THREAD

**Issue by xor-gate** [opnsense/core#1059]
I needed to google/search around in the forums and tried to understand how the 2fa works in OPNSense.  It is unclear in the documentation that you need to concatenate "<totp token><password>"  into the password field. I completely understand this is needed because vpn and other authentication only have a password field and not a extra OTP token field as most people expect (as seen in issue #944). This should be clearified in the documentation that this is different from most web-apps and applications request users to enter username + password and afterwards the OTP token.

I also found something related at the forums: https://forum.opnsense.org/index.php?topic=3107.msg9718

**Comment by AdSchellevis** [comment]
see https://docs.opnsense.org/manual/how-tos/two_factor.html?highlight=2fa step 5:

To use the token in any application/service that you have configured, just open the Google Authenticator and add the created token/key **before** your regular password.

**Comment by xor-gate** [comment]
Probably I have read over this, maybe it would be wise to place a notice in a warning box that the behaviour is different to all other TOTP implementations which show a second step dialog.

**Comment by fichtner** [comment]
Or a figure in the doc visualising the concatenation. I agree that reading over it is a thing we cannot avoid and need to address differently.

**Comment by xor-gate** [comment]
Yeah I understand, but because it is none-standard 2FA behaviour the user should be noticed in the documentation.

**Comment by jschellevis** [comment]
I agree it need clarifiction, I'll add it to the docs before 17.1. However this kind of token+password construction is very common too a standard solution, although the order is sometimes reversed.. password (or pin) + token.

**Comment by xor-gate** [comment]
Yeah I understand this is the "only-way" and therefor commonly used. But as a regular user you should be aware of this (as some implementations, mostly web based use user, pass -> redirect -> 2fa token).

Thanks @jschellevis !

**Comment by jschellevis** [comment]
Improved documentation and added warning.
