### ISSUE TITLE
(ipsec) add any interface option for phase1 (left = %any)

### ISSUE THREAD

**Issue by AdSchellevis** [opnsense/core#1067]

**Comment by AdSchellevis** [comment]
https://github.com/opnsense/core/commit/41157c8901b9f4da0b16cc626fbd049794114993

**Comment by fichtner** [comment]
Just FYI: I've added a stable/16.7, this commit is currently *not* on there

**Comment by AdSchellevis** [comment]
@fichtner thanks

**Comment by AdSchellevis** [comment]
tested on my end, needs this https://github.com/opnsense/core/commit/2cc1c4a990821b66721df802656f1ba64c239f45 but then its ok.
