### ISSUE TITLE
Diagnostics: Crash Reporter with disabled "yes" button

### ISSUE THREAD

**Issue by ortylp** [opnsense/core#107]
The "yes" button in crash reporter is disabled in 15.1.8.1-564571c81 (amd64)

**Comment by fichtner** [comment]
This is a feature request. The crash reporter still needs some work to know when it doesn't have a crash report so it doesn't bug you along with some other things and the backend server isn't running yet. Will be fixed in the upcoming weeks.

**Comment by fichtner** [comment]
Duplicates #80
