### ISSUE TITLE
Design glitch in web-gui drop-down menus (low priority)

### ISSUE THREAD

**Issue by MrM40** [opnsense/core#1071]
The last menu-item in the drop-menus in web-gui is not showing full-size:

![dropdown](https://cloud.githubusercontent.com/assets/16258063/17122010/273ac318-52d8-11e6-9ccf-a8d7a1770311.jpg)
It seems to be all menus....or at least those with with many menu-items

OPNsense 16.7.r2-amd64
Chrome Version 52.0.2743.82, 64-bit
Windows 7, x64

**Comment by AdSchellevis** [comment]
I think its the default behaviour of https://silviomoreto.github.io/bootstrap-select/ this issue 
https://github.com/opnsense/core/issues/773 is related, but without changing the internals of bootstrap-select.js I can't find a way to fix this styling.
