### ISSUE TITLE
It tries to load lots of modules on boot which are already loaded.

### ISSUE THREAD

**Issue by fabianfrz** [opnsense/core#1073]
Results in a lot of text output.
Solution may be suppressed or only loaded if they are not loaded yet.

Version 10.7 Release Candidate 2

**Comment by fichtner** [comment]
I'm guessing the netflow modules... make sure you are on FreeBSD 10.3 underneath...

**Comment by fabianfrz** [comment]
Maybe some screenshots may help:

![vlcsnap-2016-07-26-13h17m15s406](https://cloud.githubusercontent.com/assets/3713914/17136069/8cdc8ce6-5333-11e6-820c-e882ff82070a.png)
![vlcsnap-2016-07-26-13h17m53s708](https://cloud.githubusercontent.com/assets/3713914/17136071/8fc8521e-5333-11e6-96d9-1821f8f4a867.png)

**Comment by fichtner** [comment]
Yes, you're running on FreeBSD 10.2.

# opnsense-update -bkr 16.7 && /usr/local/etc/rc.reboot

**Comment by fabianfrz** [comment]
This did work, thanks :+1:
