### ISSUE TITLE
strongswan status actions sometimes hang

### ISSUE THREAD

**Issue by andreasvel** [opnsense/core#1075]
Hi,
on Version
OPNsense 16.1.20-amd64
FreeBSD 10.2-RELEASE-p19
OpenSSL 1.0.2h 3 May 2016

several Times the Dasboard and the Ipsec Status Page doenst show any active or inactive Tunnels.
The Tunnels are active and Working... 
Restarting the Service doenst work, Just Stopping and Starting the Service makes the Overview correct

**Comment by fichtner** [comment]
@andreasvel I have Strongswan 5.5.0 queued up for 16.7.1. Do you want to preview a snapshot sooner?

**Comment by andreasvel** [comment]
Hi,
ive updated to 16.7 this morning
from 6 Tunnels 5 are working well - if i try to start the inactive tunnel the loading is very slow and no really success...
the tunnel is enabled but in the status view there are no subnetworks to displayed

**Comment by fichtner** [comment]
Even swanctl utility hangs from time to time on my setups, I think this is still part of an upstream issue.

**Comment by fichtner** [comment]
16.7.4 has been out for a while. I have several IPsec connections myself and no issues reported by other users.

16.7.5 will have a few more additions to IPsec, but all in all it's working well.

Anonymised screenshots say more than thousand words if the problem persists.
