### ISSUE TITLE
GUI improvement on the Tester form

### ISSUE THREAD

**Issue by MrM40** [opnsense/core#1076]
Perhaps you could add a help-text on the Tester in regards to TOTP.
I wasted some time on this not knowing :-(
Searching for Tester in documentation and forum didn't gave any hits.

![totp](https://cloud.githubusercontent.com/assets/16258063/17168324/1e0fd048-53e2-11e6-94ae-13964a9f03e7.jpg)

OPNsense 16.7.r2-amd64
FreeBSD 10.3-RELEASE-p5
OpenSSL 1.0.2h 3 May 2016

**Comment by AdSchellevis** [comment]
It would be good to add the tester to the documentation, https://docs.opnsense.org/manual/how-tos/two_factor.html

**Comment by jschellevis** [comment]
Added tester to howto manual page.
