### ISSUE TITLE
Change IP LAN from console menu not working

### ISSUE THREAD

**Issue by lgcosta** [opnsense/core#1082]
When trying to change the IP configuration of the LAN interface via the console menu, it has no effect, checking config.xml configuration is saved, however, is not applied.

**Comment by fichtner** [comment]
Hi Luiz,

What setting was this and which version? I use it all the time, suspecting it's something with the input values.


Cheers,
Franco

**Comment by lgcosta** [comment]
Hi,
last version 16.7 (AMD64) with virtualbox
It was necessary for me to redo the assignment interface configuration for the application of the settings work.
I'll reinstall it again to see if the error repeats.

**Comment by fichtner** [comment]
Closing to be reopened when reproducible :)
