### ISSUE TITLE
Add IPv6 carp support to opnsense

### ISSUE THREAD

**Issue by elbuit** [opnsense/core#1084]
Add IPv6 carp support to opnsense because IPv6 is supported by opnsense but not in carp settings.

Thanks.

**Comment by AdSchellevis** [comment]
@elbuit have you tried adding an ipv6 address as carp VIP? maybe I'm missing something, but when I add an ipv6 carp VIP on my test vm it looks normal in the status page and on the box itself.

**Comment by AdSchellevis** [comment]
timeout
