### ISSUE TITLE
pf rules use variables such as $WAN inconsistently

### ISSUE THREAD

**Issue by djGrrr** [opnsense/core#1088]
There is a lot of inconsistency in the use of variables in the generated pf rules such as:

rdr on igb0  proto tcp from any to x.x.x.252 port $Plex_TCP_Ports -> 10.x.x.x 
pass out  route-to ( igb0 x.x.x.1 ) from x.x.x.what 252 to !x.x.x.0/22 keep state allow-opts label "let out anything from firewall host itself"
scrub on igb1 from any to any random-id  set-tos 0xc0

in order to use variables in all of these places, the interface aliases would have to change, currently they look like this:
loopback = "{ lo0 }"
WAN = "{ igb0 }"
LAN = "{ igb1 }"

if they were without the brackets, the variables could be use everywhere to make the rules much more consistent:
loopback = "lo0"
WAN = "igb0"
LAN = "igb1"

There is a similar story with the Gateway reply-to variables, except they do not seem to actually be used at all.

**Comment by AdSchellevis** [comment]
@djGrrr our current plan is to first add a pluggable mechanism in place (https://github.com/opnsense/core/issues/993) and then split the current script into smaller better to read pieces. For 16.7 we already did some cleanups, but filter.inc is one of the largest piles of unstructured code. 

In case you have time to replace some of the inconsistencies, that would be great, but try to keep the commits small for traceability.

**Comment by AdSchellevis** [comment]
17.1 will replace the variables for the automatic rules, eventually they will be removed completely. For reference, the new mapping code https://github.com/opnsense/core/blob/7f2e31e6d78d48be6167232fbd10bd6d0dca9f0f/src/opnsense/mvc/app/library/OPNsense/Firewall/FilterRule.php#L132-L141
