### ISSUE TITLE
Prevent robots from indexing GUI

### ISSUE THREAD

**Issue by jpawlowski** [opnsense/core#1089]
I can see that the current GUI explicitly invites search engine robots to index a firewall:

    <meta name="robots" content="index, follow, noodp, noydir">

I don't think anybody wants to have his firewall admin interface listed in any search engine, e.g. one only needs to search for "opnsense" in Google and get all the installations out there having WAN administration enabled.

Even though WAN administration might not be a good idea w/o X509 client-auth or VPN, I think it's a good idea to replace that header with

    <meta name="robots" content="noindex, nofollow, noodp, noydir">

**Comment by fichtner** [comment]
Agreed, thanks!
