### ISSUE TITLE
More aliases config mishaps

### ISSUE THREAD

**Issue by fichtner** [opnsense/core#109]
https://twitter.com/mannkind/status/580914528038227968
https://twitter.com/ToeiRei/status/580838332483141632

**Comment by AdSchellevis** [comment]
should be fixed with  https://github.com/opnsense/core/commit/812d1aa4f5b9b4b3445447457648dfffb34eb437

**Comment by fichtner** [comment]
Reported fixed from numerous sources. Thanks! :)
