### ISSUE TITLE
SSL certificate restore fails

### ISSUE THREAD

**Issue by andreas-p** [opnsense/core#1093]
With 16.7, it's not possible to re-import exported certificates, it will claim "could not locate xml tag". Actually, the format of the backup file differs from the complete config backup.
I massaged the file to match the normal config file, but no success: the list of certificates will be empty afterwards.

**Comment by fichtner** [comment]
This is a partial restore, right?

**Comment by andreas-p** [comment]
Yes, certificate export and import only.

**Comment by fichtner** [comment]
This doesn't work on 16.1.8 too. A full export and section import can work, but may fail for other reasons that can only be fixed through #471.

I'm closing this, making the other one a priority. Thanks for the report.
