### ISSUE TITLE
proxy: no interface selector

### ISSUE THREAD

**Issue by FlorianHeigl** [opnsense/core#1094]
Hi,

no idea why this happens, the "Proxy interfaces" field doesn't have a dropdown.
Typing into it shows no autocomplete, but I can see I only have 2-3 chars of space, there seems to be some invisible space for the dropdown or something.

Only odd thing I have in this test install so far is the LAN IP is also DHCP'ed.

I could not find any issue opened for this, let me know if I should attach a config backup or anything else.
Version info:
OPNsense 16.7-amd64
FreeBSD 10.3-RELEASE-p5
OpenSSL 1.0.2h 3 May 2016

Running on KVM, single core, 1GB, 10GB GPT disk.

**Comment by fichtner** [comment]
Proxy interfaces need to be static, so no DHCP allowed. Maybe that's why this happens?

**Comment by FlorianHeigl** [comment]
makes sense then :-)
I'll adjust my lab.
