### ISSUE TITLE
allow config model to load and arbitrary config file

### ISSUE THREAD

**Issue by fichtner** [opnsense/core#1097]
This is for: https://github.com/opnsense/core/issues/471

To do section import properly, we need to parse the config file given through our model, but not as the new standard config in a standard location as we only want this or that config tag to be carried over. This is useful for "inspecting" config files.

**Comment by AdSchellevis** [comment]
@fichtner we could add some glue to "switch" the config file that is used for the model system, but we can't have two open at the same time for comparison (the model uses a singleton). 

So this kind of sequence could work in theory:
1. switch to temp config.xml
2. read model from temp (model reads singleton)
3. switch back to normal config.xml
4. save in memory model to disk (which is now the normal config.xml again)

Is that enough for your use case?

**Comment by fichtner** [comment]
1-3 under a critical section would be enough, returning the arbitrary file's "$config" for further inspection (or reassign to $config itself), never switching away from the actual running config. It's only about using the config loader code that's there in the first place without changing the running config. Does that make sense?

**Comment by AdSchellevis** [comment]
discussed on irc, only wrap fromArray() to an arbitrary config.xml file

**Comment by AdSchellevis** [comment]
@fichtner to load xml config into a new array(), using the same structure as $config, use:
```
$conf_bck = load_config_from_file('/conf/config.xml.1');
```

**Comment by fichtner** [comment]
Works like a charm, many thanks!
