### ISSUE TITLE
Selective ACL and MVC routing

### ISSUE THREAD

**Issue by fichtner** [opnsense/core#1098]
Hi Ad,

We've identified a ACL problem with e.g. trying to access only the Captive Portal voucher page:

https://forum.opnsense.org/index.php?topic=3431.msg11479#msg11479

With only privileges for "ui/captiveportal/voucher/\*" and "api/captiveportal/voucher/\*" the page doesn't load at all (redirect loop). Adding "ui/index.php\*" helps with that. Then, the page doesn't properly invoke the API, so it also needs "api/api.php\*" to fix that.

The latter two should probably be auto-generated and enforced automatically?

Cheers,
Franco

**Comment by AdSchellevis** [comment]
@fichtner this doesn't look very logical, the two pages (ui/index.php, api/api.php) aren't accessed directly.

If I create this acl (same as the forum):
```
<acl>
    <!-- unique acl key, must be globally unique for all acl's  -->
    <page-services-VoucherAdmin>
        <name>WebCfg - Services: Captive Portal Vouchers page</name>
        <description>Allow access to the 'Services: CaptivePortal: Vouchers' page.</description>
        <patterns>
            <pattern>ui/captiveportal/voucher/*</pattern>
            <pattern>api/captiveportal/voucher/*</pattern>
        </patterns>
    </page-services-VoucherAdmin>
</acl>
```

And only assign this acl to a user, then on my end the user can login to the voucher page without issues.

Are you sure the user isn't assigned to any other groups or acls (which may be incomplete)? 

For reference (shouldn't be important), my acl lives here:
_/usr/local/opnsense/mvc/app/models/OPNsense/HelloWorld/ACL/ACL.xml_

**Comment by fichtner** [comment]
Yes, new empty user, no privs except for this, ended up in a redirect loop without ui/index.php*.

API operation didn't work until ui/api.php* was added.

The former wasn't reported by the user as it seemed to work for him, but the latter was definitely a problem with him too.

**Comment by AdSchellevis** [comment]
@fichtner it seems like I'm unable to reproduce this, can you test the same acl in the same location as I posted and assign it to an empty user?

**Comment by fichtner** [comment]
I get this:

    Aug 3 07:45:58	api[26388]: uri /ui/index.php?_url=/captiveportal/voucher/& not accessible for user foobar
    Aug 3 07:45:58	opnsense: /index.php: foobar@10.0.100.1 attempted to access / but does not have access to that page. Redirecting to ui/captiveportal/voucher/.
    Aug 3 07:45:57	api[37250]: uri /ui/index.php?_url=/captiveportal/voucher/& not accessible for user foobar
    Aug 3 07:45:57	opnsense: /index.php: foobar@10.0.100.1 attempted to access / but does not have access to that page. Redirecting to ui/captiveportal/voucher/.
    Aug 3 07:45:57	api[26388]: uri /ui/index.php?_url=/captiveportal/voucher/& not accessible for user foobar
    Aug 3 07:45:57	opnsense: /index.php: foobar@10.0.100.1 attempted to access / but does not have access to that page. Redirecting to ui/captiveportal/voucher/.
    Aug 3 07:45:57	api[68761]: uri /ui/index.php?_url=/captiveportal/voucher/& not accessible for user foobar
    Aug 3 07:45:57	opnsense: /index.php: foobar@10.0.100.1 attempted to access / but does not have access to that page. Redirecting to ui/captiveportal/voucher/.

<img width="1355" alt="screen shot 2016-08-03 at 7 46 02 am" src="https://cloud.githubusercontent.com/assets/1915288/17355110/85391fba-594e-11e6-91f3-61f60580ea99.png">

**Comment by AdSchellevis** [comment]
@fichtner I have to try this on another box tomorrow, my setup redirects to this:

`Aug  3 20:33:53 OPNsense opnsense: /index.php: test@10.211.55.2 attempted to access / but does not have access to that page. Redirecting to ui/captiveportal/voucher/.
`

Which is exactly what it should do. There's something odd in your redirect....

**Comment by L1ghtn1ng** [comment]
Maybe a browser bug depending if you are using a different browser?

**Comment by fichtner** [comment]
Firefox was used in my tests, I think Ad uses it too.

**Comment by L1ghtn1ng** [comment]
Do you have any plugins enabled that could mess with it?

**Comment by fichtner** [comment]
We're suspecting lighttpd now, I've been running a 1.4.40 for testing purposes, but 1.4.39 is still the default in 16.7. :)

**Comment by L1ghtn1ng** [comment]
Ah okay

**Comment by fichtner** [comment]
Seems to have been a bug on lighttpd 1.4.40. Cannot even reproduce API problems. ACL works as intended.
