### ISSUE TITLE
'Cancel' button breaks when editing FW rule after 'Save' is aborted due to user error

### ISSUE THREAD

**Issue by syserr0r** [opnsense/core#1099]
Steps to reproduce:
- Edit firewall rule
- Attempt to 'Save' the rule, causing an error (such as attempting to modify an IPv4+6 rule gateway, causing "You can not assign a gateway to a rule that applies to IPv4 and IPv6")
- Click 'Cancel'

Expected: 'Cancel' returns you to the firewall overview page
Actual: 'Cancel' reloads the page with the firewall rule you are editing

**Comment by syserr0r** [comment]
Screen capture showing the problem is available [here](http://i.imgur.com/GZqA1hN.gifv)

**Comment by fabianfrz** [comment]
@syserr0r The cancel button redirects you to the page you visited before which is the rule edit page because of the error.

**Comment by syserr0r** [comment]
@fabianfrz Yes, this is what I suspected. It is not very intuitive, however, hence the bug-report.

If this is as intended it should at the very least return to the FW rules overview page after the second click. As it stands it is a worse implementation than using the browser 'back' button or `onclick="history.back();"`.

**Comment by syserr0r** [comment]
I'm unsure how the page stores the 'back' url, but a simple solution would be to prevent the 'back' url being set to the same URL as the page it is to be used on (in which case it should keep it's previous value, which would be the Overview page).

**Comment by AdSchellevis** [comment]
For reference,  it uses the HTTP_REFERER. We should probably replace these:

`git grep 'onclick="window.location.href' | grep Cancel
`

With the most logical return page, back doesn't really work using HTTP_REFERER and in 95% of the pages back should always return to the same page.
