### ISSUE TITLE
IPsec cleanup

### ISSUE THREAD

**Issue by jschellevis** [opnsense/core#11]
For IPsec some option are listed that are not valid in current setup.
Remove: AES-GCM until tested and functional
Change: IKE, charon supports setting to ike or ikev2 IKE supports both IKEv2 and IKEv1 according to documentation. Option needs to be auto or ikev2 not ikev1.

**Comment by fichtner** [comment]
@jschellevis how relevant is this ticket in 2016?

**Comment by jschellevis** [comment]
Lots have changed.. i'd say close. Ad has done a lot of cleanups and enhacements.

**Comment by fichtner** [comment]
ok
