### ISSUE TITLE
carp over lagg interfaces has demotion handling problems

### ISSUE THREAD

**Issue by andreas-p** [opnsense/core#1100]
opn 16.7: When starting up a lagg interface or disconnecting or reconnecting a LACP member interface, the kernel will recognize "send error 50 on lagg0_vlan..." and increase the carp demotion for each interface and VLAN that's defined for it. Since it will never recover from that, lacp demotion starts with 240 * (interface on LAGG) and makes master and slave indistinguishable.

I stumbled upon this when I found my master firewall to be carp backup, although advskew was 0 and 100 on backup as expected. But the high demotion from LAGG events maxed out advskew on the wire, with every CARP packet containing advskew=240 and thus corrumping master/slave selection.

To hot-fix this, I tuned net.inet.carp.senderr_demotion_factor=0 to ignore carp send errors (and net.pfsync.carp_demotion_factor=0 as well; why should a master demote itself if the backup can't receive pfsync?) I observed pfsync demotion to decrease after a minute or so, but never carp.senderr demotion.

**Comment by andreas-p** [comment]
Just checked on a pf 2.2.4:  
Both net.inet.carp.senderr_demotion_factor and net.pfsync.carp_demotion_factor are set to 0 by default there; probably as a consequence of https://forum.pfsense.org/index.php?topic=89085

**Comment by fichtner** [comment]
Thanks, I'll look into this soon.

**Comment by fichtner** [comment]
Hi Andreas,

Looks sane, if you have a spare minute try to help verify:

    # opnsense-update 79a2008b


Cheers,
Franco

**Comment by andreas-p** [comment]
What is this update supposed to do? I don't see any change, a testsystem still has net.pfsync.carp_demotion_factor=240 and net.inet.carp.senderr_demotion_factor=240.

**Comment by fichtner** [comment]
The update applies the commit with the hash 79a2008b

It will set the correct values on bootup (it should).

**Comment by andreas-p** [comment]
It doesn't... 
# sysctl -a |grep carp
net.inet.carp.ifdown_demotion_factor: 240
net.inet.carp.senderr_demotion_factor: 240
net.inet.carp.demotion: 0
net.inet.carp.log: 1
net.inet.carp.preempt: 0
net.inet.carp.allow: 1
net.pfsync.carp_demotion_factor: 240

This is even a degradation. net.inet.carp.preempt should be 1, as it is on the firewalls I'm preparing for production (where I noticed the problems); this is tested on a dedicated test machine.

**Comment by fichtner** [comment]
Let me refine this as I've just tested this successfully: the patch will set both "net.inet.carp.senderr_demotion_factor" and "net.pfsync.carp_demotion_factor" to 0 on boot, unless you've specified otherwise in the tunables GUI.

The value of "net.inet.carp.preempt" is set during carp setup, it's been untouched since 2015. https://github.com/opnsense/core/blame/master/src/etc/inc/interfaces.inc#L1788

**Comment by andreas-p** [comment]
# opnsense-update 79a2008b
Updating OPNsense repository catalogue...
OPNsense repository is up-to-date.
...
Your system is up to date.

# tail -n +117 /usr/local/etc/inc/system.inc | head -n7
    $sysctls = array(
        "net.enc.in.ipsec_bpf_mask" => "0x0002",
        "net.enc.in.ipsec_filter_mask" => "0x0002",
        "net.enc.out.ipsec_bpf_mask" => "0x0001",
        "net.enc.out.ipsec_filter_mask" => "0x0001",
    );

Apparently https://github.com/opnsense/core/commit/79a2008b66ed754073360754d6d936bceee7c0a5 isn't present.

**Comment by fichtner** [comment]
Sorry, I'm an idiot :) I meant "opnsense-patch", I fixed it in the comment.

**Comment by andreas-p** [comment]
Ack, patch works.
I don't see it in system/settings/tunables though. I guess nobody should touch this anyway.

**Comment by fichtner** [comment]
Ok, thanks. I've added this to the upcoming 16.7.1 as well.

The sysctl can be added manually and thus overridden. I'm not very fond of the whole sysctls section in config.xml as that is not going to be visible to an existing installation on upgrade anyway.

**Comment by syserr0r** [comment]
After re-visiting CARP/HA again and stumbling upon the related pfsense article (and this) I suspect this may be a factor in my problems.

Both my systems have both `net.inet.carp.ifdown_demotion_factor` and `net.inet.carp.senderr_demotion_factor` as 240 (and not 0) -- was this patch reverted or is there something odd about my set-up?

**Comment by AdSchellevis** [comment]
they should be, you can set them manually to another value if needed, but in most cases that's not advisable. 

https://www.freebsd.org/cgi/man.cgi?query=carp&sektion=4

**Comment by 53c70r** [comment]
I would like to mention that
https://github.com/opnsense/core/commit/79a2008b66ed754073360754d6d936bceee7c0a5
Is not included in the current release?

**Comment by 53c70r** [comment]
> @53c70r removed for good reasons years ago ([1c37911](https://github.com/opnsense/core/commit/1c37911d82f4f4749126d59322eb27eaa26ca7c1))

That's really interesting I just had the exact problem, the master demoted with 2880 after I rebooted the master.
The backup took over the Master and never gave it back, the master stood at 2880 while backup was 0 even after everything was back online and stable.

gw-00 before reboot:

```
root@opnsense-00:~ # ifconfig | grep carp
    carp: MASTER vhid 1 advbase 1 advskew 0
    carp: MASTER vhid 8 advbase 1 advskew 0
    carp: MASTER vhid 3 advbase 1 advskew 0
    carp: MASTER vhid 4 advbase 1 advskew 0
    carp: MASTER vhid 10 advbase 1 advskew 0
    carp: MASTER vhid 6 advbase 1 advskew 0
    carp: MASTER vhid 7 advbase 1 advskew 0
    carp: MASTER vhid 9 advbase 1 advskew 0
    carp: MASTER vhid 11 advbase 1 advskew 0
    carp: MASTER vhid 12 advbase 1 advskew 0
    carp: MASTER vhid 13 advbase 1 advskew 0
    carp: MASTER vhid 14 advbase 1 advskew 0
    carp: MASTER vhid 15 advbase 1 advskew 0
root@opnsense-00:~ # sysctl -a | grep net.inet.carp
net.inet.carp.ifdown_demotion_factor: 240
net.inet.carp.senderr_demotion_factor: 240
net.inet.carp.demotion: 0
net.inet.carp.log: 1
net.inet.carp.preempt: 1
net.inet.carp.dscp: 56
net.inet.carp.allow: 1
```

gw-01
```
root@opnsense-01:~ # ifconfig | grep carp
    carp: BACKUP vhid 1 advbase 1 advskew 100
    carp: INIT vhid 2 advbase 1 advskew 100
    carp: BACKUP vhid 8 advbase 1 advskew 100
    carp: BACKUP vhid 3 advbase 1 advskew 100
    carp: BACKUP vhid 4 advbase 1 advskew 100
    carp: BACKUP vhid 10 advbase 1 advskew 100
    carp: INIT vhid 5 advbase 1 advskew 100
    carp: BACKUP vhid 6 advbase 1 advskew 100
    carp: BACKUP vhid 7 advbase 1 advskew 100
    carp: BACKUP vhid 9 advbase 1 advskew 100
    carp: BACKUP vhid 11 advbase 1 advskew 100
    carp: BACKUP vhid 12 advbase 1 advskew 100
    carp: BACKUP vhid 13 advbase 1 advskew 100
    carp: BACKUP vhid 14 advbase 1 advskew 100
    carp: BACKUP vhid 15 advbase 1 advskew 100
root@opnsense-01:~ # sysctl -a | grep net.inet.carp
net.inet.carp.ifdown_demotion_factor: 240
net.inet.carp.senderr_demotion_factor: 240
net.inet.carp.demotion: 480
net.inet.carp.log: 1
net.inet.carp.preempt: 1
net.inet.carp.dscp: 56
net.inet.carp.allow: 1
```

after the reboot of gw-00

```
root@opnsense-00:~ # ifconfig | grep carp
    carp: BACKUP vhid 1 advbase 1 advskew 0
    carp: BACKUP vhid 8 advbase 1 advskew 0
    carp: BACKUP vhid 3 advbase 1 advskew 0
    carp: BACKUP vhid 4 advbase 1 advskew 0
    carp: BACKUP vhid 10 advbase 1 advskew 0
    carp: BACKUP vhid 6 advbase 1 advskew 0
    carp: BACKUP vhid 7 advbase 1 advskew 0
    carp: BACKUP vhid 9 advbase 1 advskew 0
    carp: BACKUP vhid 11 advbase 1 advskew 0
    carp: BACKUP vhid 12 advbase 1 advskew 0
    carp: MASTER vhid 13 advbase 1 advskew 0
    carp: BACKUP vhid 14 advbase 1 advskew 0
    carp: BACKUP vhid 15 advbase 1 advskew 0
root@opnsense-00:~ # sysctl -a | grep net.inet.carp
net.inet.carp.ifdown_demotion_factor: 240
net.inet.carp.senderr_demotion_factor: 240
net.inet.carp.demotion: 2880
net.inet.carp.log: 1
net.inet.carp.preempt: 1
net.inet.carp.dscp: 56
net.inet.carp.allow: 1
```

gw-01
```
root@opnsense-01:~ # ifconfig | grep carp
    carp: MASTER vhid 1 advbase 1 advskew 100
    carp: INIT vhid 2 advbase 1 advskew 100
    carp: MASTER vhid 8 advbase 1 advskew 100
    carp: MASTER vhid 3 advbase 1 advskew 100
    carp: MASTER vhid 4 advbase 1 advskew 100
    carp: MASTER vhid 10 advbase 1 advskew 100
    carp: INIT vhid 5 advbase 1 advskew 100
    carp: MASTER vhid 6 advbase 1 advskew 100
    carp: MASTER vhid 7 advbase 1 advskew 100
    carp: MASTER vhid 9 advbase 1 advskew 100
    carp: MASTER vhid 11 advbase 1 advskew 100
    carp: MASTER vhid 12 advbase 1 advskew 100
    carp: BACKUP vhid 13 advbase 1 advskew 100
    carp: MASTER vhid 14 advbase 1 advskew 100
    carp: MASTER vhid 15 advbase 1 advskew 100
root@opnsense-01:~ # sysctl -a | grep net.inet.carp
net.inet.carp.ifdown_demotion_factor: 240
net.inet.carp.senderr_demotion_factor: 240
net.inet.carp.demotion: 480
net.inet.carp.log: 1
net.inet.carp.preempt: 1
net.inet.carp.dscp: 56
net.inet.carp.allow: 1
```

The gw-00 never went to master or intended to because of the demotion so the skew could do its job.

after the tunables everything was fine after the reboot of gw-00:

gw-00
```
root@opnsense-00:~ # ifconfig | grep carp && sysctl -a | grep net.inet.carp
	carp: MASTER vhid 1 advbase 1 advskew 0
	carp: MASTER vhid 8 advbase 1 advskew 0
	carp: MASTER vhid 3 advbase 1 advskew 0
	carp: MASTER vhid 4 advbase 1 advskew 0
	carp: MASTER vhid 10 advbase 1 advskew 0
	carp: MASTER vhid 6 advbase 1 advskew 0
	carp: MASTER vhid 7 advbase 1 advskew 0
	carp: MASTER vhid 9 advbase 1 advskew 0
	carp: MASTER vhid 11 advbase 1 advskew 0
	carp: MASTER vhid 12 advbase 1 advskew 0
	carp: MASTER vhid 13 advbase 1 advskew 0
	carp: MASTER vhid 14 advbase 1 advskew 0
	carp: MASTER vhid 15 advbase 1 advskew 0
net.inet.carp.ifdown_demotion_factor: 240
net.inet.carp.senderr_demotion_factor: 0
net.inet.carp.demotion: 0
net.inet.carp.log: 1
net.inet.carp.preempt: 1
net.inet.carp.dscp: 56
net.inet.carp.allow: 1
```

gw-01
```
root@opnsense-01:~ # ifconfig | grep carp && sysctl -a | grep net.inet.carp
	carp: BACKUP vhid 1 advbase 1 advskew 100
	carp: INIT vhid 2 advbase 1 advskew 100
	carp: BACKUP vhid 8 advbase 1 advskew 100
	carp: BACKUP vhid 3 advbase 1 advskew 100
	carp: BACKUP vhid 4 advbase 1 advskew 100
	carp: BACKUP vhid 10 advbase 1 advskew 100
	carp: INIT vhid 5 advbase 1 advskew 100
	carp: BACKUP vhid 6 advbase 1 advskew 100
	carp: BACKUP vhid 7 advbase 1 advskew 100
	carp: BACKUP vhid 9 advbase 1 advskew 100
	carp: BACKUP vhid 11 advbase 1 advskew 100
	carp: BACKUP vhid 12 advbase 1 advskew 100
	carp: BACKUP vhid 13 advbase 1 advskew 100
	carp: BACKUP vhid 14 advbase 1 advskew 100
	carp: BACKUP vhid 15 advbase 1 advskew 100
net.inet.carp.ifdown_demotion_factor: 240
net.inet.carp.senderr_demotion_factor: 0
net.inet.carp.demotion: 0
net.inet.carp.log: 1
net.inet.carp.preempt: 1
net.inet.carp.dscp: 56
net.inet.carp.allow: 1
```

**Comment by 53c70r** [comment]
> @53c70r removed for good reasons years ago ([1c37911](https://github.com/opnsense/core/commit/1c37911d82f4f4749126d59322eb27eaa26ca7c1))

Could you clarify what led to the removal of the tunables in src/etc/inc/system.inc? I'm struggling to understand the reasoning behind it from the comments and commit messages.

**Comment by AdSchellevis** [comment]
@53c70r stick to the standards, people can configure differently when needed, ignoring interface and pfsync errors by default is usually not the best idea.

**Comment by 53c70r** [comment]
> @53c70r stick to the standards, people can configure differently when needed, ignoring interface and pfsync errors by default is usually not the best idea.

Thank you for the clarification. In our real-world scenarios, we found that switching the master to the backup due to issues like wire overload didn't provide any advantage, as the new master would face the same load. Because of this, and the flaky connectivity we've experienced, we've opted to use the 0 tunables to better suit our environment.
