### ISSUE TITLE
Serial install of 16.7 fails on APU2 board

### ISSUE THREAD

**Issue by Woi** [opnsense/core#1101]
Hey, 

I'm trying to install OPNsense 16.7 from an USB stick on an APU2c4 [1] via serial console, which fails with this error message:
```
Trying to mount root from ufs:/dev/ufs/OPNsense_Install [ro,noatime]...
mountroot: waiting for device /dev/ufs/OPNsense_Install ...
Mounting from ufs:/dev/ufs/OPNsense_Install failed with error 19.

Loader variables:
  vfs.root.mountfrom=ufs:/dev/ufs/OPNsense_Install
  vfs.root.mountfrom.options=ro,noatime

Manual root filesystem specification:
  <fstype>:<device> [options]
      Mount <device> using filesystem <fstype>
      and with the specified (optional) option list.

    eg. ufs:/dev/da0s1a
        zfs:tank
        cd9660:/dev/acd0 ro
          (which is equivalent to: mount -t cd9660 -o ro /dev/acd0 /)

  ?               List valid disk boot devices
  .               Yield 1 second (for background tasks)
  <empty line>    Abort manual input

mountroot> reboot
Invalid file system specification.

mountroot> ufs:/dev/ufs/OPNsense_Install
Trying to mount root from ufs:/dev/ufs/OPNsense_Install []...
Mounting from ufs:/dev/ufs/OPNsense_Install failed with error 2: unknown file system.

mountroot> 
```
Some more details:
I'm using `OPNsense-16.7-OpenSSL-serial-amd64.img.bz2` and sha256 sum matches.
`Screen version 4.03.01 (GNU)`  is invoked with `/dev/ttyS0 115200`
APU2s Bios versions is 20160307

It doesn't seem related, but to give you an overall picture:
there is an other issue with disordered output, which can be fixed with `set console=comconsole`. 

Cheers
Woi

[1] http://pcengines.ch/apu2c2.htm

**Comment by fichtner** [comment]
Hi Woi,

From the boot loader prompt (3) try:

    set kern.cam.boot_delay="10000"
    boot

I've seen the disordered output on a APU2C2 this week, didn't know that setting it to single console fixes this. I want to revise images and serial mode soon, this will probably be the new default, thanks!


Cheers,
Franco

**Comment by Woi** [comment]
Hey fitcherner,

thanks for the quick reply :-). I just managed to boot in to the installer the very same moment you answered  by following this blog post: https://randomproblem.wordpress.com/2016/03/31/installing-opnsense-16-1-on-pc-engines-apu2/
The same guy also blogged about the disordered output: https://randomproblem.wordpress.com/2016/05/15/installing-freebsd-via-a-serial-port/

**Comment by Woi** [comment]
Regarding the disordered output, I stumbled over this thread:
https://www.coreboot.org/pipermail/coreboot/2016-June/081542.html which  leads to this commit:
https://github.com/pcengines/seabios/commit/d161aaf84d4f71d93599f2ab72508095da7d30d2
So this behaviour might be a BIOS issue.

Since you marked this bug for milestone 17.1, I like to suggest to document both issues along with there workarounds for the current release. This is to improve user experience and save APU2 owners some time finding a solution on there own.

Thanks for OPNsense and your support :)
