### ISSUE TITLE
Support mobile IKEv2

### ISSUE THREAD

**Issue by mikejuni** [opnsense/core#1102]
Current OPNSense (16.07) does not support IKEv2 for mobiles, which is actually the best VPN supported by different vendors (iOS, Windows, Linux, Android (through strongswan).

Can we add support for IKEv2 soon? Both EAP-TLS and EAP-MSCHAPv2 would be extremely useful for roadwarrior setup.

**Comment by fichtner** [comment]
Hi there,

I understand the request for EAP-TLS and EAP-MSCHAPv2. There were attempts to bring it it, but it needs testing and feedback to be released which it didn't receive last time. We try to make this a stronger policy for going forward.

Secondly, before I triage this issue I'm curious as to why the following is not suitable for your use case of "mobile IKEv2" in general?

https://docs.opnsense.org/manual/how-tos/ipsec-road.html


Cheers,
Franco

**Comment by mikejuni** [comment]
IKEv1 works on iOS, however there are authentication issues from Xauth disallowing saving of passwords. On the other hand mobike support in IKEv2 really allows the remote machine to switch network on the fly without disconnecting VPN which is a key advantage.

**Comment by fichtner** [comment]
Ok, get it. I don't maintain IPSec so not sure how much work is needed... reassigning to the proper authority now, thanks!

**Comment by AdSchellevis** [comment]
@mikejuni the option is back in the code again, if you have time to test you can easily run the following command from the console:

`opnsense-patch 10c6828e
`

I've checked https://wiki.strongswan.org/projects/strongswan/wiki/Win7EapMultipleConfig for the missing settings (actually did that some time ago https://forum.opnsense.org/index.php?topic=3338)

There are some other cleanups in the ipsec code pending as well (https://github.com/opnsense/core/commit/3a44d7328369c13e672e2de77db33d2ddd97aed2 https://github.com/opnsense/core/commit/2cc1c4a990821b66721df802656f1ba64c239f45 https://github.com/opnsense/core/commit/0dd120ff1aac446f0df9a3f82051b95b64eecf27), but they won't result in a different ipsec.conf, so you don't have to apply those patches.

**Comment by AdSchellevis** [comment]
@mikejuni do you have any feedback on your testing?

**Comment by fichtner** [comment]
It'll be in 16.7.5 tomorrow. Feel free to reopen. For now consider this done/timeout.
