### ISSUE TITLE
the old switcheroo for fonts (or: better cyrillic fonts)

### ISSUE THREAD

**Issue by fichtner** [opnsense/core#1104]
via: https://forum.opnsense.org/index.php?topic=3464.0

**Comment by AdSchellevis** [comment]
note to self : try https://fonts.google.com/specimen/PT+Sans;

**Comment by AdSchellevis** [comment]
https://github.com/adobe-fonts/source-sans-pro/releases/tag/2.020R-ro/1.075R-it should improve cyrillic support without changing our defaults. I tried the suggested PT Sans font, but rather keep our defaults like they are now for non cyrillic users.

**Comment by fichtner** [comment]
Looks good as far as I can tell, thanks!
