### ISSUE TITLE
Support lacp_fast_timeout

### ISSUE THREAD

**Issue by andreas-p** [opnsense/core#1105]
The default timeout for LACP timeout in freebsd is very long (observed about 3 seconds), this is really long (too long for CARP). 
ifconfig lagg0 lacp_fast_timeout will reduce this significantly and is probably what most installations need.

**Comment by AdSchellevis** [comment]
@andreas-p https://github.com/opnsense/core/commit/c68ca487689e7a77c9358737f742839f7c881d35 should do the trick, if you have time to test, you can install the patch using:

`opnsense-patch c68ca48`

**Comment by andreas-p** [comment]
Yes, works as expected, thanks!

**Comment by fichtner** [comment]
Jolly good, thanks! :)
