### ISSUE TITLE
Incorrect form validation in aliases edit form

### ISSUE THREAD

**Issue by pv2b** [opnsense/core#1109]
# Summary

There is an error in the form validation logic in the Aliases edit form.

# Steps to reproduce:

1. Go to Firewall -> Aliases -> View
2. Click on Add a new alias
3. Enter a valid name for the alias, e.g. "test"
4. Leave the description blank (probably does not matter)
5. Choose Host(s) as type (probably does not matter)
6. In the hosts field, enter 192.0.2.10 192.0.2.11 with a space between them.
7. Enter "Ten" in the host description field.
8. Click the + button to add a second host row.
9. In the hosts field, enter 192.0.2.20 192.0.2.21 with a space between them.
10. Enter "Twenty" in the host description field.
11.. Press save.

# Expected result

An error message pops up complaining of the invalid format, and the form is re-populated as it was left without any changes.

# Actual result

An error message pops up complaining about the input format. The form does not return as submitted, instead the following unwanted changes occur:

- The hosts are actually split up into four fields rows, however, the descriptions do not line up properly. The descriptions "Ten" and "Twenty" line up with the first two rows, which as 192.0.2.10 and 192.0.2.11, in contrast to what was desired.

# Discussion

At this point, the alias is (correctly) not saved, clicking the save button a second time will however save it, since now the form is valid.

It would appear that the form seems a bit schitzofrenic about whether to fix the user's mistakes and be flexible, or just point them out. It can be argued that the ability to enter a space-separated list is a desired behavior that may have become ingrained in user's workflows. However, the Aliases->Import feature would seem to negate the neccessity of this unintentional feature.

If you intend to keep this feature, care should be taken that the descriptions line up properly after the space-seperated lists are expanded.

Without looking at the code, I think the root to this problem may have something to do with how aliases are represented in config.xml. As an example, this is how an alias might be represented.

```
<opnsense>
  <!-- Snip... -->
  <aliases>
    <alias>
      <name>test</name>
      <address>192.0.2.1 192.0.2.2 192.0.2.3 192.0.2.4</address>
      <descr>Test entry</descr>
      <type>host</type>
      <detail>First entry||Second entry||Third entry||Fourth entry</detail>
    </alias>
    <!-- Snip... -->
  </aliases>
  <!-- Snip... -->
</opnsense>

```
Note how the list of aliases is listed as a space-separated list. Granted, this file format is brain damaged, but that is the topic of [another issue](https://github.com/opnsense/core/issues/1110).

**Comment by AdSchellevis** [comment]
@pv2b the format is indeed horrific ;) we should fix the validation to return the same data after save, let me look into that.

**Comment by AdSchellevis** [comment]
@pv2b https://github.com/opnsense/core/commit/214d92c39f76a6eadafbef6f7d8ce18f2762c3d2 should improve the current situation. Do you have time to do some additional testing.

**Comment by AdSchellevis** [comment]
@pv2b have you tested the fix and can you close this issue?

**Comment by pv2b** [comment]
Hi!

I just tested this now, and I cannot provoke any "wrong" behavior through either the original test case nor with some more fuzzing.

**Comment by AdSchellevis** [comment]
@pv2b thanks for testing!
