### ISSUE TITLE
DHCP client of OPNsense doesn't request a address if Ethernet cable plugged in after startup

### ISSUE THREAD

**Issue by jstrebel** [opnsense/core#111]
If I start the Box (pcengines APU) without connected Ethernet Cable and insert the Ethernet Cable after the Box is up, then the Box does not get a address on the WAN Interface.
SW 15.1.8.1 (AMD 64)
HW: APU 
WAN Interface configured as DHCP client.

(ifconfig of WAN interface)
re1: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500
        options=8209b<RXCSUM,TXCSUM,VLAN_MTU,VLAN_HWTAGGING,VLAN_HWCSUM,WOL_MAGIC,LINKSTATE>
        ether 00:0d:b9:33:16:01
        inet6 fe80::20d:b9ff:fe33:1601%re1 prefixlen 64 scopeid 0x2 
        nd6 options=23<PERFORMNUD,ACCEPT_RTADV,AUTO_LINKLOCAL>
        media: Ethernet autoselect (100baseTX <full-duplex>)
        status: active

(end of system.log) 
Mar 26 13:03:18 OPNsense sshd[6224]: Server listening on 0.0.0.0 port 22.
Mar 26 13:03:18 OPNsense sshlockout[6753]: sshlockout/webConfigurator v3.0 starting up
Mar 26 13:03:18 OPNsense kernel: done.
Mar 26 13:03:18 OPNsense opnsense: /usr/local/etc/rc.bootup: Cloning new wireless interface ath0_wlan1
Mar 26 13:03:18 OPNsense opnsense: /usr/local/etc/rc.bootup: Failed to clone interface ath0 with error code 1, output ifconfig: SIOCIFCREATE2: Device not configured
Mar 26 13:03:18 OPNsense kernel: done.
Mar 26 13:03:29 OPNsense opnsense: /usr/local/etc/rc.bootup: The command '/sbin/dhclient -c /var/etc/dhclient_wan.conf re1 > /tmp/re1_output 2> /tmp/re1_error_output' returned exit code '1', the output was ''
Mar 26 13:03:29 OPNsense opnsense: /usr/local/etc/rc.bootup: Accept router advertisements on interface re1
Mar 26 13:03:30 OPNsense opnsense: /usr/local/etc/rc.bootup: Resyncing OpenVPN instances.
Mar 26 13:03:30 OPNsense kernel: done.
Mar 26 13:03:30 OPNsense opnsense: /usr/local/etc/rc.bootup: Could not find IPv4 gateway for interface (wan).
Mar 26 13:03:30 OPNsense kernel: pflog0: promiscuous mode enabled
Mar 26 13:03:30 OPNsense kernel: ..
Mar 26 13:03:30 OPNsense kernel: .done.
Mar 26 13:03:32 OPNsense kernel: done.
Mar 26 13:03:32 OPNsense rtsold[8444]: <sendpacket> sendmsg on re1: Operation not permitted
Mar 26 13:03:32 OPNsense opnsense: /usr/local/etc/rc.bootup: The command '/usr/sbin/pw groupadd test1 -g  -M 2000 2>&1' returned exit code '65', the output was 'pw: gid `0' has already been allocated'
Mar 26 13:03:33 OPNsense kernel: done.
Mar 26 13:03:34 OPNsense lighttpd[42654]: (log.c.164) server started
Mar 26 13:03:34 OPNsense kernel: done.
Mar 26 13:03:34 OPNsense kernel: done.
Mar 26 13:03:34 OPNsense kernel: done.
Mar 26 13:03:34 OPNsense configd.py: Updating all dyndns
Mar 26 13:03:35 OPNsense opnsense: /usr/local/etc/rc.bootup: Could not find IPv4 gateway for interface (wan).
Mar 26 13:03:35 OPNsense kernel: ..
Mar 26 13:03:35 OPNsense kernel: .done.
Mar 26 13:03:35 OPNsense kernel: ipfw2 (+ipv6) initialized, divert loadable, nat loadable, default to accept, logging disabled
Mar 26 13:03:35 OPNsense lighttpd[56734]: (log.c.164) server started
Mar 26 13:03:35 OPNsense kernel: done
Mar 26 13:03:36 OPNsense rtsold[8444]: <sendpacket> sendmsg on re1: Operation not permitted
Mar 26 13:03:40 OPNsense rtsold[8444]: <sendpacket> sendmsg on re1: Operation not permitted
Mar 26 13:03:45 OPNsense opnsense: /usr/local/etc/rc.bootup: Creating rrd update script
Mar 26 13:03:45 OPNsense opnsense: /usr/local/etc/rc.bootup: miniupnpd: Starting service on interface: lan
Mar 26 13:03:45 OPNsense kernel: done.
Mar 26 13:03:45 OPNsense kernel: done.
Mar 26 13:03:46 OPNsense getty[93927]: open /dev/ttyv1: No such file or directory
Mar 26 13:03:46 OPNsense getty[93927]: open /dev/ttyv1: No such file or directory
Mar 26 13:03:46 OPNsense getty[93987]: open /dev/ttyv3: No such file or directory
Mar 26 13:03:46 OPNsense getty[93987]: open /dev/ttyv3: No such file or directory
Mar 26 13:03:47 OPNsense sshlockout[94834]: sshlockout/webConfigurator v3.0 starting up
Mar 26 13:03:46 OPNsense getty[94176]: open /dev/ttyv4: No such file or directory
Mar 26 13:03:46 OPNsense getty[94176]: open /dev/ttyv4: No such file or directory
Mar 26 13:03:47 OPNsense getty[93965]: open /dev/ttyv2: No such file or directory
Mar 26 13:03:47 OPNsense getty[93965]: open /dev/ttyv2: No such file or directory
Mar 26 13:03:47 OPNsense getty[93704]: open /dev/ttyv0: No such file or directory
Mar 26 13:03:47 OPNsense getty[93704]: open /dev/ttyv0: No such file or directory
Mar 26 13:03:47 OPNsense getty[94319]: open /dev/ttyv5: No such file or directory
Mar 26 13:03:47 OPNsense getty[94319]: open /dev/ttyv5: No such file or directory
Mar 26 13:03:47 OPNsense getty[94571]: open /dev/ttyv6: No such file or directory
Mar 26 13:03:47 OPNsense getty[94571]: open /dev/ttyv6: No such file or directory
Mar 26 13:03:47 OPNsense getty[94713]: open /dev/ttyv7: No such file or directory
Mar 26 13:03:47 OPNsense getty[94713]: open /dev/ttyv7: No such file or directory
Mar 26 13:03:52 OPNsense kernel: re1: link state changed to UP
Mar 26 13:03:52 OPNsense devd: Executing '/usr/local/opnsense/service/configd_ctl.py 'interface linkup start re1''
Mar 26 13:03:52 OPNsense configd.py: Linkup starting re1
Mar 26 14:54:08 OPNsense login: login on ttyu0 as root
Mar 26 14:54:08 OPNsense login: ROOT LOGIN (root) ON ttyu0

**Comment by AdSchellevis** [comment]
Thanks for calling it in, it should be fixed with commit https://github.com/opnsense/core/commit/adacd4b6ed4eb51f85806cb77b296571fae28328 which will be in the next release today or tomorrow.
