### ISSUE TITLE
config.xml format for aliases brain damaged

### ISSUE THREAD

**Issue by pv2b** [opnsense/core#1110]
# Current situation

Currently, aliases are stored in config.xml like this:

```
<opnsense>
  <!-- Snip... -->
  <aliases>
    <alias>
      <name>test</name>
      <address>192.0.2.1 192.0.2.2 192.0.2.3 192.0.2.4</address>
      <descr>Test entry</descr>
      <type>host</type>
      <detail>First entry||Second entry||Third entry||Fourth entry</detail>
    </alias>
    <!-- Snip... -->
  </aliases>
  <!-- Snip... -->
</opnsense>
```

This corresponds to an alias that looks like this:

**Name:** test
**Description:** Test Entry
**Type:** Host(s)

| Host(s) | Description |
| --- | --- |
| 192.0.2.1 | First entry |
| 192.0.2.2 | Second entry |
| 192.0.2.3 | Third entry |
| 192.0.2.4 | Fourth entry |
# Discussion

This is a brain damaged format. Basically, instead of using multiple XML elements to represent multiple items, making it trivial to handle using the functionality of the XML parser, instead any code has to handle parsing and splitting up values, and then matching a description to an address by indexing into two arrays or similar. This is an error-prone method of coding.
# Proposal for change

Instead, I would like to propose that the config.xml file format instead represents the above data as such:

```
<opnsense>
  <!-- Snip... -->
  <aliases>
    <alias>
      <name>test</name>
      <descr>Test entry</descr>
      <type>host</type>
      <entry>
        <value>192.0.2.1</value>
        <descr>First entry</descr>
      </entry>
      <entry>
        <value>192.0.2.2</value>
        <descr>Second entry</descr>
      </entry>
      <entry>
        <value>192.0.2.3</value>
        <descr>Third entry</descr>
      </entry>
      <entry>
        <value>192.0.2.4</value>
        <descr>Fourth entry</descr>
      </entry>
    </alias>
    <!-- Snip... -->
  </aliases>
  <!-- Snip... -->
</opnsense>
```

Any existing address or detail fields could be converted into the new format upon parsing of the configuration file, in order to upgrade these data structures to the new format upon upgrade.

There is an alternative more compact way of doing this in XML. However, this involves using XML attributes which seems to be something that the configuration file format does not use anywhere for any purpose.

```
<opnsense>
  <!-- Snip... -->
  <aliases>
    <alias>
      <name>test</name>
      <descr>Test entry</descr>
      <type>host</type>
      <entry value="192.0.2.1" descr="First entry" />
      <entry value="192.0.2.2" descr="Second entry" />
      <entry value="192.0.2.3" descr="Third entry" />
      <entry value="192.0.2.4" descr="Fourth entry" />
    </alias>
    <!-- Snip... -->
  </aliases>
  <!-- Snip... -->
</opnsense>
```

Using this format may be better, but it would represent the first time to my knowledge XML attributes were used in config.xml. As such it may not be the best way in the big picture. Currently, transitioning from an XML-based file format to JSON or similar is simple, because of the subset of XML in use. Adding attributes may complicate these matters. I don't know if this is something you want to do or care about.

**Comment by AdSchellevis** [comment]
@pv2b eventually the aliases should move over to our mvc framework, which has a sane format and contains validations. The missing part however is a new style migration strategy for old style data to the new style format. (there is still some work in the queue for the model, before we are going to look at migrations)

In case you want to start working on this issue, please take a look at https://docs.opnsense.org/develop.html

**Comment by fichtner** [comment]
timeout
