### ISSUE TITLE
16.7 Webgui: Layout broken on some config items.

### ISSUE THREAD

**Issue by Woi** [opnsense/core#1111]
Hey, 

The configuration items `Services -> Intrusion Detection` and `Services -> Proxy Server -> Administration` have a broken layout in the webgui. Looks like CSS are missing. 

Kind regards,
Woi

**Comment by fichtner** [comment]
Please attach a screenshot. GitHub supports "drag and drop" :)

**Comment by Woi** [comment]
Here you are:
![broken_layout_ids_pre](https://cloud.githubusercontent.com/assets/5870628/17402709/dace4930-5a54-11e6-9718-4d3b67453292.png)
![broken_layout_ids_post](https://cloud.githubusercontent.com/assets/5870628/17402708/daca9632-5a54-11e6-9265-4f311a3753a4.png)
![broken_layout_proxy_pre](https://cloud.githubusercontent.com/assets/5870628/17402707/dac7592c-5a54-11e6-932d-3b825dab5d49.png)
![broken_layout_proxy_post](https://cloud.githubusercontent.com/assets/5870628/17402706/dac47266-5a54-11e6-936d-a17906842b9a.png)

**Comment by fichtner** [comment]
Can you try a different browser to confirm? It could be overzealous caching.

**Comment by Woi** [comment]
I used SeaMonkey and Firefox before opening this bug. The later with an fresh profile.

**Comment by fichtner** [comment]
Ok, just checking :)

Let's try to see from the console if all files are ok:

    # pkg check -s opnsense

Can you check from the developer tools (network) what kind of error is returned on load of these items?

**Comment by Woi** [comment]
Files seem to be ok:
```
root@OPNsense:~ # pkg check -s opnsense
Checking opnsense: 100%
root@OPNsense:~ # 
```

But SeaMonkeys error console comes up with this:
```
Error: ReferenceError: $ is not defined
Source file: https://192.168.1.1/ui/ids/
Line: 5
```
and
```
Error: ReferenceError: $ is not defined
Source file: https://192.168.1.1/ui/proxy/
Line: 5
```
Line 5 is:
` $( document ).ready(function() {`

In context with empty lines removed:
```
<script type="text/javascript">
    $( document ).ready(function() {
        //
        var data_get_map = {'frm_GeneralSettings':"/api/ids/settings/get"};
```
```
<script type="text/javascript">
    $( document ).ready(function() {
        var data_get_map = {'frm_proxy':"/api/proxy/settings/get"};
```

**Comment by fichtner** [comment]
Let's try to reapply the package nonetheless, it will also restart the web server:

    # pkg install -f opnsense

**Comment by fichtner** [comment]
Sorry, doesn't restart the full web server, you'll need:

    # /usr/local/etc/rc.restart_webgui

**Comment by Woi** [comment]
The box doesn't have internet access yet. It might take a few days before I'm able to test it.

**Comment by fichtner** [comment]
It's difficult to say what's wrong here remotely. The JS files "$" is for jQuery are in the same location for both the MVC and the static php pages. You can also reinstall, use the "Import Configuration" before running the "Guided Installation", this can restore all your settings.

**Comment by Woi** [comment]
I did a fresh install on a second APU2 and retested using SeaMonkey and Chromium. Layout is still broken.
Also checked the behaviour on an OPNsense 16.1.20, without any issues.

**Comment by fichtner** [comment]
Which image? serial amd64?

**Comment by Woi** [comment]
Exactly

**Comment by fichtner** [comment]
There is a file /var/log/installer/mtree.log -- can you share it with us? It might give an indication on whether or not files were copied / broken.

**Comment by Woi** [comment]
This is the `mtree.log` from the second installation. I had to append `.txt` because GitHub wouldn't accept the file otherwise
[mtree.log.txt](https://github.com/opnsense/core/files/403547/mtree.log.txt)

**Comment by fichtner** [comment]
All the GUI files were installed correctly, it only lists the files that changed for one reason or another and these few look ok :(

**Comment by Woi** [comment]
I made a surprising and weird observation:
After connecting one of the boxes to my local network (with internet access) to run `pkg install -f opnsense`, everything looked fine, even without invoking `pkg`. I then took the second box and checked the layout again, which was broken as expected. After connecting the second box to the LAN and reloading the items in question, the layout was ok again.
I then did try to break the layout by removing the LAN connection and rebooting and even resetting the configuration back to factory defaults, but without success.

**Comment by fichtner** [comment]
What VM and network type were you using? VirtuaBox and Host-Only network?

**Comment by Woi** [comment]
Bare metal on APU2. Direct wire to a notebook for configuration. Connection to LAN was made using a wifi client.

**Comment by fichtner** [comment]
I can't reproduce this at all. Serial amd64 install, had a laptop with no firefox installed... installed it, unplugged internet, plugged LAN for APU2 which has stock 16.7 and no WAN. All pages are working as expected. This was on FreeBSD 10.3 / Firefox 47.0.1.

Is this 16.7 or maybe RC1/RC2?

**Comment by Woi** [comment]
I'm using 16.7 release, of course.
I did three reinstalls to reproduce the bug, but without success. Since I used a freshly created thumb drive for testing, I'm suspecting something went wrong while writing the installation media the first time. But it remains weird.
However, enough time has been wasted, thus I'm closing this bug. Thanks for your support and sorry for wasting your time.
