### ISSUE TITLE
GUI "Firewall: Aliases" fail to add host alias with underscore in Alias

### ISSUE THREAD

**Issue by nemesix29** [opnsense/core#1113]
Can't add Alias within alias with underscore in name of them.

It's work fine without underscore

![2016-08-04 19_51_50-view _ aliases _ firewall _ nh-fw01 nexxx us](https://cloud.githubusercontent.com/assets/15220591/17412772/bd4709e0-5a7e-11e6-9d50-7bbe27b65201.png)

**Comment by fichtner** [comment]
Hi there,

Underscores are forbidden in the host name specification:

https://en.wikipedia.org/wiki/Hostname#Restrictions_on_valid_host_names

Or is there something I'm not seeing?


Cheers,
Franco

**Comment by AdSchellevis** [comment]
@fichtner alias nesting should work, is_domain() is valid for most alias names :)

**Comment by fichtner** [comment]
ah ok sorry, nice catch!
