### ISSUE TITLE
NanoBSD Upgrade - pkg: write(): No space left on device

### ISSUE THREAD

**Issue by juliocbc** [opnsense/core#1114]
While attempting to upgrade from **16.7.RC1** to **16.7.1** the following error is appearing: 

pkg: write(): No space left on device

I've corrected this issue creating a symbolic link from `/var/cache/pkg`  to `/root/var/cache/pkg`

**Comment by fichtner** [comment]
This was actually fixed in RC2 :)

https://github.com/opnsense/changelog/blob/master/doc/16.7.r2#L27

Code here:

https://github.com/opnsense/core/commit/51b04e9b0aa98850ce90df84d3f4a523da7c2ae8

Cheers,
Franco

**Comment by juliocbc** [comment]
Thanks Fichtner! 

I've posted in forum (hope that helps someone)
[](https://forum.opnsense.org/index.php?topic=3489.0)
