### ISSUE TITLE
openVPN bug

### ISSUE THREAD

**Issue by L1ghtn1ng** [opnsense/core#1115]
```
Thu Aug  4 23:44:15 2016 Control Channel Authentication: tls-auth using INLINE static key file
Thu Aug  4 23:44:15 2016 UDPv4 link local (bound): [undef]
Thu Aug  4 23:44:15 2016 UDPv4 link remote: [AF_INET]REDACTED:1194
Thu Aug  4 23:44:15 2016 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
Thu Aug  4 23:44:16 2016 [Home VPN Server] Peer Connection Initiated with [AF_INET]REDACTED:1194
Thu Aug  4 23:44:18 2016 TUN/TAP device tun0 opened
Thu Aug  4 23:44:18 2016 do_ifconfig, tt->ipv6=0, tt->did_ifconfig_ipv6_setup=0
Thu Aug  4 23:44:18 2016 /sbin/ip link set dev tun0 up mtu 1500
Thu Aug  4 23:44:18 2016 /sbin/ip addr add dev tun0 local 10.0.8.6 peer 10.0.8.5
RTNETLINK answers: Invalid argument
Thu Aug  4 23:44:18 2016 ERROR: Linux route add command failed: external program exited with error status: 2
Thu Aug  4 23:44:18 2016 Initialization Sequence Completed
```

on 16.7.1
cc @fichtner

**Comment by fichtner** [comment]
Hi Jay,

"/sbin/ip" is a Linux binary that we don't execute, so this is OpenVPN itself. It fails to set something on the other side, I don't know if it's a syntax thing or misconfigured...


Cheers,
Franco

**Comment by fabianfrz** [comment]
@L1ghtn1ng It may help if you post the "push" commands from the configuration file - maybe there is something wrong with them.

**Comment by L1ghtn1ng** [comment]
https://www.kirkg.us/posts/building-an-openvpn-server-with-opnsense/ this is what I used and it worked fine on 16.1 series but I did ever so slightly change what it said and yeah I can do that just not sure where to look on freebsd, still new to BSD

**Comment by fichtner** [comment]
An upgrade to the Linux host on the other side could easily cause that. It's definitely on the Linux remote side, not the BSD side

**Comment by fichtner** [comment]
Unless of course OpenVPN tries to run /sbin/ip on BSD, which is obviously not so useful :D

**Comment by L1ghtn1ng** [comment]
Where is the file to show the config of it?

**Comment by L1ghtn1ng** [comment]
Okay so I think we should rename this ticket to "OpenVPN wizard does not provide a working VPN"

As the wizard should provide a working VPN in my opinion, thoughts?

**Comment by fichtner** [comment]
I can't say that the wizard works under all conditions because it's hard to verify. We should focus on a setup that doesn't work starting by gathering the steps to reproduce through the wizard. Ok?

**Comment by L1ghtn1ng** [comment]
Yeah will try setting it up again tonight and will make notes

**Comment by reetp** [comment]
First thing is where does the log come from ? The 'linux' box or the 'Opnsense' box ?
Here's a pointer to the issue: https://forums.openvpn.net/viewtopic.php?t=17440
Which end is client and which is server ?
Unfortunately I have no idea where opnsense stores its openvpn configs - usually in linux it would be something like /etc/openvpn/somplace - but it would be useful to find out and view them
