### ISSUE TITLE
intrusion detection: missing argument

### ISSUE THREAD

**Issue by fichtner** [opnsense/core#1117]
Hi Ad,

I'm recording this in multiple crash reports since at least 16.1.19. You probably know what to do. :)

    PHP Warning:  Missing argument 1 for OPNsense\IDS\Api\SettingsController::getRuleInfoAction() in /usr/local/opnsense/mvc/app/controllers/OPNsense/IDS/Api/SettingsController.php on line 153
    PHP Notice:  Undefined variable: sid in /usr/local/opnsense/mvc/app/controllers/OPNsense/IDS/Api/SettingsController.php on line 157

I also found this:

    PHP Warning:  array_key_exists(): The first argument should be either a string or an integer in /usr/local/opnsense/mvc/app/models/OPNsense/IDS/IDS.php on line 134
    PHP Warning:  array_key_exists(): The first argument should be either a string or an integer in /usr/local/opnsense/mvc/app/models/OPNsense/IDS/IDS.php on line 151

Cheers,
Franco

**Comment by AdSchellevis** [comment]
@fichtner I will try to look at it this weekend.

**Comment by L1ghtn1ng** [comment]
Is this going to be cherry picked for 16.7.2?

**Comment by fichtner** [comment]
@L1ghtn1ng It's only from rare cases and does not seem to effect overall operation, yet since the patches are small they will likely be picked up for 16.7.2

**Comment by L1ghtn1ng** [comment]
Okay thanks
