### ISSUE TITLE
feature request: collectd plugin

### ISSUE THREAD

**Issue by willjones** [opnsense/core#1120]
As we now have collectd available from the default repo would someone like to make this pluggable.

We use it for remote monitoring of opnsense boxes that I do not have direct access to, imagine they are behind someone else network that permits outbound connections but not inbound, we use the graphite plugin to send stats back to a remote server without needing to worry about a VPN tunnel.

Collectd can do a whole lot more beyond this, maybe it could be a good replacement for some of the RRD backend stuff? - There are plugins that  could monitor other processes such as unbound, ntp, openvpn and so on.

https://collectd.org/features.shtml

GUI Ideas:

Enable / disable various plugins.
Set targets for sending data to remote collectors via graphite etc.
Some basic options to configure plugin variables.

**Comment by fichtner** [comment]
Will, thanks for the details. Can we please take this to https://github.com/opnsense/plugins instead before we get into further discussion? :)

**Comment by willjones** [comment]
Moved to  :  https://github.com/opnsense/plugins/issues/33
