### ISSUE TITLE
Missing OrganizationalUnit (CSR)

### ISSUE THREAD

**Issue by blogmotion** [opnsense/core#1121]
Hello, I use wildcard certificate *.domain.com and I need to generate my CSR to send to the CA and they give me signed certificate.

In System > Certificate Manager > Certificates > Add > Create A Certificate Signing Request, but the "OU=" (Organizational Unit) is not present, and it's a mandotory field with my athority.

Is it possible to add the "OU" field ?
thank you for the fix!

regards

**Comment by AdSchellevis** [comment]
@blogmotion just added the field and logic, if you want to try this on 16.7.1, you can easily patch your version using:

`opnsense-patch  3973a6c`

(from the command line)

**Comment by blogmotion** [comment]
Thank you, it works !
