### ISSUE TITLE
base_layout missing template for tables of objects

### ISSUE THREAD

**Issue by pv2b** [opnsense/core#1122]
Hi!

I've been working on a new plugin, and it would seem that base_layout it missing a template for a list of objects. I've been looking through how the existing plugins do it, and they all seem to be re-inventing the same wheel, of setting up a HTML table (this ought to be possible to generate from a template given a field in the model or a layout parameter selecting appropriate headers for the summary) and hooking up UIBootgrid etc.

This probably needs to improve to reduce code duplication?

**Comment by AdSchellevis** [comment]
There's certainly room for improvement in the grid system, although defining the table doesn't have to be a bad idea in general. Bootgrid offers quite some layout features.

Defining a new meta model + template might be a good idea, although there are some challenges to make this work for all current implementations (endpoint definitions, glue to edit form content, etc).
UIBootgrid is a bit of a workaround to avoid a lot of code duplication and keep the grid definition simpler, its not my favourite piece, but functional enough at the time.

Is there a specific pattern your trying to solve? or a similar case like the other forms (ids, traffic shaper, etc)?

**Comment by pv2b** [comment]
As an example, let's say that I want to re-implement the VLAN code in the new style.

I need to be able to manage a list of VLANs, add new ones, remove old ones, etc. There should be some way for me to just get some basic scaffolding in to create a grid of these, given the columns I want to see.

The IDS does this for example in several places, such as the rules and user defined and tab, and I guess the alerts tab too.

The traffic shaper's entire UI is about managing lists.

**Comment by AdSchellevis** [comment]
Actually both IDS and the shaper use the same pattern, where the shaper is more or less what your add/remove/edit vlan probably should do.
The most basic pattern should probably be easy to wrap in a template.

We could add a grid definition, like we have for the input forms with the necessary endpoints and fields (/formats) in them. That would simplify the frontend template.
If we store the endpoint in the template generated table, we could then hook in the jquery code to handle the endpoint actions.
Its probably best to re-engineer the current jquery code in a new module and replace the current implementations one by one if we have an easier option available.

**Comment by fichtner** [comment]
I also think the easier pattern should be implemented first, later extended / adapted to replace the other tables (if needed or indeed possible). A lot of list that we have are simple rows with labels and action buttons so this will go a long way.

**Comment by AdSchellevis** [comment]
timeout
