### ISSUE TITLE
ipsec default negotiation

### ISSUE THREAD

**Issue by reetp** [opnsense/core#1128]
Opnsense16.7

I was setting up a ipsec tunnel. In the documentation you correctly note that 'aggressive' mode for the Negotiation Mode is insecure, but 'Aggressive' seems the default choice. It would be better to set it to Main Mode

Seems that a change is required in 

/usr/local/www/vpn_ipsec_phase1.php

At 126 change to:

$pconfig['mode'] = "main"

**Comment by AdSchellevis** [comment]
@reetp your right, thanks!
