### ISSUE TITLE
Intrusion Detection description ambiguities

### ISSUE THREAD

**Issue by reetp** [opnsense/core#1129]
This follows:
https://github.com/opnsense/core/issues/239
https://github.com/opnsense/core/issues/991

I was messing with IDS and it took me a while to figure out how to get it to work.

I was trying to select All, Download & Install.

The problem is that you have to select the box next to Description and then scroll down and click the lower righthand 'checked' box which looks like a check box but is actually an icon !

Having two check boxes with no real description of what either does, one being an actual check box and the other two being icons of check boxes and no explanation as to how to use the system correctly is very confusing (i.e. if I can't figure it out from what I see and read then there is something missing !)

I was trying to think of the best way of doing this but am not really sure at the minute.

'Select All' should BOTH go at either the top or bottom in both columns to be consistent. There should be some more explanatory text and differentiation between Apply and Download & Update - e.g If I click a box in the Description column and click apply, it thinks about it but does not show 'Enabled' which is not logical (in the absence of any descriptive text)

Exactly what do the Description column checkboxes do ? If I check Enabled, do I need to click Apply or Download & Install ? How do I schedule automatic updating which is not explained?

Happy to look at any suggestions on modifications ! It's a bit beyond my coding skills to actually do anything on this one.

Obviously this is the file but it is beyond my primitive hacking skills !

/usr/local/opnsense/mvc/app/views/OPNsense/IDS/index.volt

**Comment by AdSchellevis** [comment]
@reetp Putting the multiselect on top and left sounds like a good idea (https://github.com/opnsense/core/commit/4b3a556b795876cc8acf5d2f19dd53d276541b4e). 

How and when to update is described in the docs https://docs.opnsense.org/manual/how-tos/ips-feodo.html .

**Comment by reetp** [comment]
Still not sure this is the right fix.

I just want to:

Select a number of rules, or all of them and then enable them

Select a number of rules, or all of them and then disable them

It should be much simpler with just one set of select boxes and an indicator of enabled/disabled. Click the box, download and install/enable. Uncheck box and apply. Disable.

The Select/Deselect box lower right should go where it says 'Enabled' just confuses.

Also, note that if you select a check box at left, then select the same at right, the left box unchecks. If I then go back and check the left box, the right remains checked......

**Comment by fichtner** [comment]
@reetp As it is it's difficult to figure out what it does and why some checkboxes behave differently. The on/off checkbox items that trigger the actual on/off (right side checkboxes for each rule and the bottom/top ones) shouldn't look like checkboxes. Maybe that will help?

**Comment by reetp** [comment]
Yup - confuses me :-) Not trying to be awkward, and I understand that sometimes you get so used to it that it seems obvious.

I think there has to be some clear distinction for sure.

Multi select and multi disable/enable should either ALL go at the top or ALL at the bottom... currently you have a multi select top left, then Disbable/Enable selected which are not really clear lower right (and are easy to miss and hence top is probably better) and then Apply and Download/Enable lower left.

Personally I'd go for one check box + Multiselect and something like

if checked && disabled {
  if downloaded == no {
    download
    enable
  else {
    enable
  }
}

if checked && enabled {
  disable
}

KISS ;-)

**Comment by fichtner** [comment]
A good start, but still a bit of a POLA violation with the downloaded twist and logic inversion.

I just saw that the info button also lets you activate and deactivate the entry, so how about:

1. Remove each entry's toggle checkbox in favour of a simple visual queue that the rule is disabled, e.g. greyed out and a text label in the last updated column: "not in use".

2. Leave the multi-select as is with the on/off buttons on top, but mark them as "primary" in orange colour and change their icons to something that shows it will disable/enable, not check/uncheck itself.

What do you think?

**Comment by reetp** [comment]
LOL. I gave it a shot at being simple just as idea. I am no coder...... certainly sounds worth a try for sure. Now I have a box running again I can give it a whirl (love the opnsense-patch tool)

Also need to check Ads gateway monitoring fix but out of time now as I have to go wine tasting ....... 

If I can try over the weekend I will, if not back at work Tuesday

**Comment by fichtner** [comment]
Hey John,

Bottoms up! or whatever they say during a fancy wine tasting. I'll get this done till Tuesday.


Cheers,
Franco

**Comment by fichtner** [comment]
I've started on this... the idea is to get rid of the single row toggle buttons while retaining the visual queue of enabled/disabled which I am not capable off. Giving this back to @AdSchellevis.

**Comment by reetp** [comment]
Yes, I tried fiddling with it and made a very big mess :-)

**Comment by fichtner** [comment]
As good as the GUI is, it needs more tweaks, I'll do it.

**Comment by AdSchellevis** [comment]
@fichtner I'm not sure here, I guess its functional enough at the moment, but there is always room for improvement.... :) I'm not sure what to change here without adding too much logic. 

I just rather reopen an issue if someone feels the urge to work on it if its only cosmetic....

**Comment by fichtner** [comment]
There was some talk here about how all the checkboxes behave differently and that it can be confusing: https://forum.opnsense.org/index.php?topic=3708.0

It's not hard to learn, but it may be better to clean this up eventually to not get new users stuck on what to expect vs. what they get. :)

The idea was the real checkboxes on the left stay there for multi-select, the right column should be replaced by a text label or a visual queue like greyed-out row (that already exists, but only for not installed, not yet for deactivated). One can still toggle individual rulesets using the edit button and the modal so we don't need the extra right toggle in the row. The left colum multi-action buttons are already rebranded as primary with a text label to make sure they do what they are expected to do.

This leaves the user with one column of real checkboxes and a simplified visual representation. The rules tabs have similar UX issues. I haven't finished this because I got stuck in the java script for the tables.

This isn't overly important but should be left open as a reminder, ok? :)

**Comment by AdSchellevis** [comment]
Maybe we could hide the checkboxes and move the events to "onClick" the row, I can do the JS code for you if you like.

**Comment by AdSchellevis** [comment]
No problem, let me take a look at this.

**Comment by AdSchellevis** [comment]
https://github.com/opnsense/core/commit/25d8428cb6b6d8d0f22e49d70ef6f7ce49b14a3c should do the trick, hook in after ajax calls finish and hide toggle buttons. Maybe not the nicest hook in the world, but easy and effective :)

**Comment by fichtner** [comment]
@AdSchellevis ah, thanks, that looks good! I will fix up the others, then close this :)
