### ISSUE TITLE
Remote logging source interface option ineffective

### ISSUE THREAD

**Issue by kevemueller** [opnsense/core#1130]
The UI allows to set the source address to bind syslogd against. This is very useful if e.g. you log via IPSEC and need to use the right tunnel endpoint source.
The configuration item is properly built into the invocation command line of syslogd in system.inc/system_syslogd_start, but is not effective.
system_syslogd_start checks at the end if syslogd is running (isvalidpid), if yes, it merely sends a SIGHUP to the running syslogd, which was started with a different command line.
In order to effectively start syslogd with the -b option one has to manually kill the running syslogd.
This malbehaviour is also consistent across reboot, as syslogd seems to be started before the interfaces are fully configured, hence the bind address is not (yet) available.

SIGHUP should only be used if the command line of the running syslogd is equal to the newly to be spawned syslogd.
syslogd should be restarted when a dependent interface comes up.

**Comment by fichtner** [comment]
agreed, I'll see what we can do :)

**Comment by ra1nb0w** [comment]
Any step further? or How can I help?
