### ISSUE TITLE
Group Status Missing Tier items

### ISSUE THREAD

**Issue by reetp** [opnsense/core#1132]
I have a gateway Group as follows

WAN1 = Tier 1
WAN2 = Tier 1
WAN3 = Tier 2

When I go to Group Status it shows : 
Tier 1 	  WAN2_DHCP, Online
Tier 2 	  WAN3_DHCP, Online 

Tier 1 should have an extra line to show WAN1

I have had a look in the code and can see where it is displayed from here:

/usr/local/www/status_gateway_groups.php

But despite multiple print & echo statements I cannot see where to grab a variable to get it to print an extra line. I think it goes wrong somewhere about this line:

$priorities[$itemsplit[1]] = $a_gateways[$itemsplit[0]];

At the next line you can see that WAN1 has been lost

ksort($priorities);

Unfortunately I can't quote 'see' how to fix it - don't have my normal debug setup to step through and look at the vars.

**Comment by reetp** [comment]
[Status_gateways.txt](https://github.com/opnsense/core/files/413634/Status_gateways.txt)

I have starred where it gets to Priorities but there is no WAN1 present. Hope that helps.

**Comment by reetp** [comment]
As an addendum to this, if I disable a gateway the status shows as 'gathering data' when it should show 'disabled' or similar.

**Comment by AdSchellevis** [comment]
@reetp can you try https://github.com/opnsense/core/commit/342337f35af733fa9aa089daf647f0a868beac72?

`
opnsense-patch 342337f35
`

**Comment by reetp** [comment]
Hi, yes I can but I binned my last test install. I'll try and spin one up again in the morning.

Do you want me to test on 16.7 or 17.x ?

**Comment by AdSchellevis** [comment]
it should work on both, I don't think there are a lot of other changes in that area which aren't in 16.7 yet

**Comment by reetp** [comment]
OK. Leave me with it.

**Comment by reetp** [comment]
That looks better.

Only issue is if I pull a connection physically status_gateways.php correctly reports 'Offline' but status_gateway_groups.php show the same Gateway 'gathering data'

Screen shots attached I hope

![gatewaystatus](https://cloud.githubusercontent.com/assets/3800384/18036973/14c17fac-6d71-11e6-946b-393f409f2f80.png)
![groupstatus](https://cloud.githubusercontent.com/assets/3800384/18036975/1867b108-6d71-11e6-8b03-5e962e4230dc.png)

**Comment by AdSchellevis** [comment]
Hi John, 

Looks like another bug on the same page ;( can you try this commit https://github.com/opnsense/core/commit/f8b187990805594e2562cd5bb5636930a633a173 ?

` opnsense-patch f8b187990 
`

Thanks,

Ad

**Comment by reetp** [comment]
They all seem to have 'Gathering Data' now despite all being connected !

If I disconnect one, they stay as Gathering Data'

Not fixed !

**Comment by AdSchellevis** [comment]
It seems like I missed a spot there, return_gateways_status() uses two different return types... confusing.

Can you try?

`opnsense-patch f3f36924b8
`

**Comment by reetp** [comment]
That seems to fix it ! 

One comment is that it doesn't show 'Gathering Data' whilst it tries to ping before it works out that the Gateway is offline. If I pull a connection you wait for 30-40 secs with it showing Online, and then it goes straight to Offline.

Don't know whether this is worth looking at but just so you are aware.

**Comment by reetp** [comment]
![gatewaystatus](https://cloud.githubusercontent.com/assets/3800384/18046864/cc6d7452-6dd1-11e6-859c-d9e24865dd4f.png)

![groupstatus](https://cloud.githubusercontent.com/assets/3800384/18046865/cfdda6f2-6dd1-11e6-9078-079515042a3b.png)

**Comment by AdSchellevis** [comment]
Hi John, 

Thanks for testing, we'll leave the little glitch in the status transition in there for now.

Best regards,

Ad

**Comment by reetp** [comment]
Nope problems and thanks for fixing it.

Agree the transition issue is not a biggy.

B. Rgds
John

**Comment by fichtner** [comment]
FTR: The transition is caused by the monitoring tool using "packet loss" as the transition state and the page is ignoring it. I think the widget does handle it more transparently. Generally, that is correct, it just looks odd and could be expanded in the future. :)

**Comment by reetp** [comment]
Indeed. Should be a low status bug or NFR. But it isn't that important to worry about fixing right now.
