### ISSUE TITLE
PHP errors in API calls end up breaking the output

### ISSUE THREAD

**Issue by pv2b** [opnsense/core#1136]
Hi.

If you have a PHP error when you call an API call, it goes straight out and intermingles with the JSON output. This ends up breaking JSON parsing and is generally annoying, especially when it comes out *before* the JSON output.

**Comment by fichtner** [comment]
Sounds reasonable. display_errors should be turned off for the API, as long as the messages still make it to the log file (either the one we have or a different one, whatever makes more sense?).

**Comment by AdSchellevis** [comment]
it should throw the errors (most of the time they point to actual issues), report back in json and log the traceback. 
https://github.com/opnsense/core/commit/9ed6406bdc8786e7d280a101ac652dc4b76c3b77 should fix this to the proper behaviour.
