### ISSUE TITLE
VLAN Hardware offload settings implemented in the wrong place

### ISSUE THREAD

**Issue by pv2b** [opnsense/core#1137]
Right now, VLAN hardware offload is implemented in interface_vlan_configure here: https://github.com/opnsense/core/blob/master/src/etc/inc/interfaces.inc#L260

It sounds like the right place, but it's not. If you inspect what the code is actually doing, it's looking at the _physical_ interface under the VLAN interface, and settings the settings on the physical interface. In case of a VLAN on top of a LAGG, it will find the physical interfaces under the LAGG and disable the settings there.

This means that these settings will be applied once for every VLAN on a physical interface, which is wrong. It also means that these settings will be left in an indeterminate state on interfaces with no VLANs on top, which also is subtly wrong.

The correct implementation would be to move this setting out somewhere else, to apply it on all physical interfaces, regardless of whether they have VLANs on top of them or not.

The reason I care about this right now is that this is blocking a re-implementation of the VLAN code in the new MVC model.

**Comment by pv2b** [comment]
Here's a fairly innocent refactoring that should make this easier to move:

https://github.com/pv2b/core/commit/0c94271ffcdcfb359b20d952596c8a2313e5cb74

I'm not exactly sure where this should go. I'd need to iterate over all physical interfaces. Is that even possible, or do I have to factor out the old code of iterating over the physical interfaces by looking at the vlan config?

**Comment by pv2b** [comment]
After sleeping on it overnight, perhaps the correct solution might be to create another module that deals with "interface tweaks" to be merged in before any new VLAN code. The module would permit the user to tweak settings such as VLAN hardware offload, but also settings like hardware TCP checksum offload, TSO, etc. I'd have to inventory any places settings like this are exposed (if any).

**Comment by pv2b** [comment]
I have started work on extracting out system_advanced_network.php. It looks fairly straight-forward to do all of this in the same place. I'll need this in place before I can integrate VLAN code. This will happen on the (slightly mislabeled) https://github.com/pv2b/core/tree/vlan-hardware-offload-refactor branch.

**Comment by fichtner** [comment]
timeout
