### ISSUE TITLE
Dropdown not populated with options

### ISSUE THREAD

**Issue by pv2b** [opnsense/core#1138]
I'm attempting to add a dropdown to one of my forms, and it appears that I'm either missing something, or the functionality is broken.

In order to illustrate what I'm trying to do without lots of irrelevant code, I've attempted to add a field to a fork of the helloworld module, as per this commit: https://github.com/pv2b/plugins/commit/f10d4e26a66588e4864a0b1700d93fdcbcfe45c6

Expected result: A form dropdown field appears labelled "color" with three options being red, green, and blue.

Actual result: A form dropdown field appears, but it's just listed as "Nothing selected" with no other selectable options as per the screenshot below:

![image](https://cloud.githubusercontent.com/assets/7115238/17649057/70d62538-622a-11e6-9ff5-3c7e73d3ce1b.png)

**Comment by AdSchellevis** [comment]
@pv2b see https://github.com/opnsense/core/blob/16.7.1/src/opnsense/mvc/app/views/OPNsense/Proxy/index.volt#L38

Your frontend component (selectpicker) requires a refresh after load.

Maybe its better to move this kind of questions to the forum / irc, they pollute our actual workload too much.
