### ISSUE TITLE
Single-interface OPNsense box defaults to single LAN interface rather than a single WAN interface

### ISSUE THREAD

**Issue by pv2b** [opnsense/core#1139]
When installing OPNsense to a new VM with a single NIC, that single NIC is assigned to the LAN interface.

This is not a configuration that is possible to set up using the interface assignment on the console, since it mandates a WAN to be set before a LAN. A single-interface OPNsense box therefore properly should have only a LAN.

Issue https://github.com/opnsense/core/issues/1082 may have this as a root cause.

Steps to reproduce:

- Install a new OPNsense install on a VM with 1 interface only.
- Note how the single interface is a LAN interface.
- Try to use the console interface assignment, notice how it insists on configuring a WAN interface first.

**Comment by fichtner** [comment]
I don't follow. You can skip WAN setup by hitting enter. You can also skip LAN setup although it's not very useful. :)

**Comment by pv2b** [comment]
Seems like I'm mistaken, sorry for the spam.

**Comment by fichtner** [comment]
No worries 👍
