### ISSUE TITLE
Captive Portal does not restart correctly

### ISSUE THREAD

**Issue by jstrebel** [opnsense/core#114]
Clicking on the resort button in the Status:Captive Portal page does not force a correct restart. 
- by clicking on the Restart button the service stops. -> Icon with green Arrow turns red.
- I need to click at the grey arrow to bring the service up
![screenshot 2015-03-27 00 02 28](https://cloud.githubusercontent.com/assets/2244311/6859013/b41e25d4-d414-11e4-8600-67f0630f6d37.jpg)

**Comment by fichtner** [comment]
Fixed. :)
