### ISSUE TITLE
dashboard: some widgets do not refresh

### ISSUE THREAD

**Issue by fichtner** [opnsense/core#1141]
E.g.: services status, ipsec status, ...

**Comment by reetp** [comment]
What do you want help with ??

**Comment by fichtner** [comment]
@reetp it should be fairly simple to get these plugins to poll their status. assembling a full list of non-updating widgets would help too :)

**Comment by reetp** [comment]
Still working ? :-)

I'll take a look if I get 5 minutes without the world nagging me.... and a mates Proxmox disaster area to sort out.....

**Comment by fichtner** [comment]
never working :)

good luck, this here isn't all that important. we went years without it.

**Comment by AdSchellevis** [comment]
timeout
