### ISSUE TITLE
WoL widget link does not prefill interface

### ISSUE THREAD

**Issue by m4rcu5** [opnsense/core#1148]
Hi,

On the dashboard, there is an WoL widget. In this widget, there is an "wake up" button, which seems to link to the Wake on Lan page, including the MAC and interface for the device you'd like to wake up.
The link seems correct, '/services_wol.php?mac=00:11:22:33:44:55&if=lan', however if you end up on the page, the dropdown still has the WAN interface pre-selected instead on LAN.

Same is valid for the mac addresses in the Wake on Lan page itself.

**Comment by fabianfrz** [comment]
@AdSchellevis https://github.com/opnsense/core/blob/224b5d82477759731e79f2e5123525ce6683177c/src/www/services_wol.php#L40 seems to be POST only

**Comment by m4rcu5** [comment]
@fabianfrz The magic for the autofill seems to be at line 173, the magic for the mac address at line 188 does seem to work as expected.

**Comment by AdSchellevis** [comment]
@m4rcu5 can you try this https://github.com/opnsense/core/commit/0441cf4cb8c00846c9315413010122801d8b3a79 ? on my end it already worked, but the additional call to link_interface_to_bridge() seems very odd here.

**Comment by m4rcu5** [comment]
Works like a charm @AdSchellevis !

**Comment by AdSchellevis** [comment]
@m4rcu5 thanks for testing!
