### ISSUE TITLE
DHCPv6 server "Apply changes" deletes all settings

### ISSUE THREAD

**Issue by pdf** [opnsense/core#115]
Modifying static mappings for DHCPv6 hosts results in a dialogue at the top of the screen that prompts the user to `Apply changes`, before the updated mappings will take effect.  Clicking the button destroys all configuration for the DHCPv6 server and saves the result, meaning that all the user's settings are lost and must be configured from scratch.  This is pretty severe.  I imagine this is because the form for the apply button submits to the same action URL, but doesn't include any parameters.

I suspect this problem effects any other screens that include an `Apply changes` prompt, though I have no great desire to test this by destroying my DHCPv4 settings (one other screen I know uses this workflow).

EDIT: A workaround for users in the mean time is to use the `Save` button, and never click the `Apply changes` button.

**Comment by AdSchellevis** [comment]
The issue should be fixed with https://github.com/opnsense/core/commit/64d21efdbe4306f6bbd9617c032b958dacf44e6d apparently a apply also saved the empty post data....

**Comment by AdSchellevis** [comment]
Forgot to mention, the ipv4 screen doesn't seem to have this issue on my machine.

**Comment by pdf** [comment]
Good stuff @AdSchellevis.  It'd probably be prudent to check other screens that use the `Apply changes` workflow - I feel like this isn't the only screen I've seen this happen on, but I could be wrong.

**Comment by AdSchellevis** [comment]
Thanks, I have checked quite some pages, but with the very different approaches used in all the pages it's quite hard to figure out if this is really all. At least we know why we really need to move away from the untestable legacy code... 
In case you stumble into other weirdness, just let us know.

**Comment by pdf** [comment]
Ouch, thanks for the efforts @AdSchellevis, will do.
