### ISSUE TITLE
openldap-sasl-client conflicts with FreeBSD openldap-client

### ISSUE THREAD

**Issue by andreas-p** [opnsense/core#1152]
On 16.7.2, I've been trying to install openldap-server from FreeBSD, which will install openldap-client as well. Unfortunately, the latter will conflict with openldap-sasl-client, proposing to remove php56-ldap and opnsense; we don't want that...
I guess it's php56-ldap that should depend on openldap-sasl-client OR openldap-client.

**Comment by fichtner** [comment]
This won't fix. The FreeBSD default is to exclude cyrus-sasl, but we'll need it for SSO.

I can add the openldap server to our package build list instead?

**Comment by andreas-p** [comment]
That would probably help (could be openldap-sasl-server, I've seen this package name when googling the openldap-.*client problem).

**Comment by fichtner** [comment]
openldap-sasl-server package will be available when 16.7.3 is out :)
