### ISSUE TITLE
openvpn: make "username-as-common-name" opt-out

### ISSUE THREAD

**Issue by fichtner** [opnsense/core#1154]
Hi Ad,

I'm assigning this for discussion, you'd know best how to integrate this. What do you think?

https://forum.opnsense.org/index.php?topic=3562.0

Cheers,
Franco

**Comment by AdSchellevis** [comment]
@fichtner I have to read into it, but you may assign it to me. As soon as I can find a spare moment I will look into it.

**Comment by fichtner** [comment]
@AdSchellevis ok, we already did the use case and verification in the forum, all the info is there
