### ISSUE TITLE
plugins: ipsec and openvpn need to be brushed up still

### ISSUE THREAD

**Issue by fichtner** [opnsense/core#1157]
As discussed with @AdSchellevis the OpenVPN interface plugin code should check wether there is a non-disabled OpenVPN in the network.

For IPsec it's worse as we have to traverse phase 1 for enabled entries, then traverse through phase 2 to find enabled entries....

Unfortunately, this also requires to wrap change all callers of "write_config();" to "plugins_interfaces(false); write_config();" as a lot of things can change/be changed to handle configuration or disable/enable spots.

PS: In the long run, it may be wise to add a function plugins_write_config() to take care of this "plugins_interfaces(false); write_config();" oddity in the future. There may be more things that require plugging.

**Comment by fichtner** [comment]
Improved write_config() to align with other plugin functions https://github.com/opnsense/core/commit/1d73b3b59de355b3f34e102fabe5c5aea865abc6

**Comment by AdSchellevis** [comment]
@fichtner looks good, probably the easiest way to fix this.
