### ISSUE TITLE
Adding new user breaks access to WebUI

### ISSUE THREAD

**Issue by ortylp** [opnsense/core#116]
Attempt to add first new user (with WebUI) ends with the following message:
" An HTTP_REFERER was detected other than what is defined in System -> Advanced (https://192.168.1.1/system_usermanager.php). You can disable this check if needed in System -> Advanced -> Admin. "

After opening https://192.168.1.1 again you get login screen with the following text:
"You are accessing this router by an IP address not configured locally, which may be forwarded by NAT or other means.

If you did not setup this forwarding, you may be the target of a man-in-the-middle attack."

The only fields filled were user name and password (twice).

This happened to me for the second time today.  I made fresh reinstall after the first lock-out.

This time restoring old configuration on the serial console and rebooting helped.

After third reproduction of the bug I have found the following lines in /var/log/system.log
Mar 27 18:39:35 OPNsense opnsense: /system_usermanager.php: Tried to remove user  but got user pw instead. Bailing.
Mar 27 18:39:35 OPNsense opnsense: /system_usermanager.php: The command '/usr/sbin/pw groupadd  -g  -M 2000 2>&1' returned exit code '65', the output was 'pw: group name required' 

/var/log/userlog:
2015-03-27 18:39:35 [unknown:useradd] ortyl(2000):nobody(65534)::/home/ortyl:/sbin/nologin
2015-03-27 18:39:35 [unknown:useradd] ortyl(2000) home /home/ortyl made
2015-03-27 18:39:35 [unknown:user(null)] ortyl(2000):nobody(65534)::/home/ortyl:/sbin/nologin

**Comment by AdSchellevis** [comment]
I looked at the code, but it's a little bit weird this happens. Did you perform an update after installation? The install media contains some bugs in the configuration handling which might trigger this.

**Comment by ortylp** [comment]
I am running 15.1.8.2-32aeeab6b (amd64), so 15.1.8 plus update triggered through WebUI

**Comment by AdSchellevis** [comment]
Thanks, I was able to reproduce, and will look into it further..

**Comment by AdSchellevis** [comment]
Found the issue, fixed in https://github.com/opnsense/core/commit/49c891985fc733ec647094bec7c315e2af265fdf will be in the next release. Thanks for reporting!

**Comment by inquam** [comment]
I edited an added group and got this exact error. Now I can't get into the web interface... any way to fix this?
