### ISSUE TITLE
openvpn: csc is missing tunnel_networkv6

### ISSUE THREAD

**Issue by fichtner** [opnsense/core#1161]
Hi Ad,

I found this while cleaning up some strings for the translation. Looks like it should be added?

Cheers,
Franco

**Comment by AdSchellevis** [comment]
@fichtner I don't have the time to test, but according to the man page it should work like this https://github.com/opnsense/core/commit/9dfee192dd28946f724d88f5c772fb54cb2d5fd5

**Comment by fichtner** [comment]
Let's ship this with the larger updates of IPsec and OpenVPN (plugin capabilities) in 16.7.5, it doesn't break anything. Thanks! :)
