### ISSUE TITLE
Check package dependencies when upgrading

### ISSUE THREAD

**Issue by andreas-p** [opnsense/core#1162]
Recently, opnsense had a new dependency added; requiring the package openldap-sasl-client in 16.7.2. This package will replace openldap-client (from FreeBSD repository), but unfortunately will not satisfy openldap-server's dependency on openldap-client. Ultimately, this was fixed quickly (as usual :-) by introducing openldap-sasl-server to the opnsense repository (16.7.3), which made things work as expected again.
Actually, when I performed that 16.7.2 upgrade, I didn't notice immediately that my openldap-server package was removed. Yes, there was a line indicating that auto-removal, (I noticed when doing that on a second router), but it can easily slip unnoticed until all upgrades are done and no machine is working any more...

Thanks to opnsense package system, it's quite easy to enhance the firewall with some plain FreeBSD tools (always need nano first), but the conflict handling should be enhanced. When an opnsense upgrade removes a package that is not replaced by a functional equivalent, there should be an eye-catching warning/abort msg box before removal.

**Comment by fichtner** [comment]
This happens atomically during "pkg upgrade" and in such cases pkg will not let us know up front what it'll do. It did sometimes remove the GUI package during testing, that's the least bit of fun. ;)

If you want your custom packages to persist please lock then from the packages tab, but it will likely break your firmware upgrades in such cases and/or cause undefined behaviour in general. We try to make it a rule that returning to a known configuration is better than handling all possible configurations.

Generally, the ports/packages of FreeBSD are clean, but the openldap-* mess forced this behaviour. I'm grateful that pkg handles these cases so well in general.

Another way out of this would have been an os-openldap-server plugin that would have caught the problem during build time and handled the transition gracefully.

**Comment by fichtner** [comment]
To reiterate: please lock the packages from the firmware GUI you want to keep, that's why we have these buttons. :)
