### ISSUE TITLE
Move Routing under Interfaces

### ISSUE THREAD

**Issue by reetp** [opnsense/core#1164]
NFR - only cosmetic but I find that after messing with Interfaces I keep going back to Routes, and then Interfaces again.

To me it would be more logical to have a 'Networking' tab, with Interfaces and Routing grouped together as they are inextricably interlinked.

Not sure it is the perfect solution but just a thought.....

**Comment by fichtner** [comment]
Gateways and Routes needs to be merged into something else, I agree. "Networking" is nice, but some interface aspects don't feel completely right just yet as they'd have to move there too.

**Comment by fichtner** [comment]
(tagged this feature as it will require more shuffling and page tweaks to get there)

**Comment by reetp** [comment]
:-)

**Comment by AdSchellevis** [comment]
timeout
