### ISSUE TITLE
Illegal option -B on boot opnsense-devel

### ISSUE THREAD

**Issue by gitdevmod** [opnsense/core#1165]
Hi,

I updated opnsense-devel to 17.1.a_277 (amd64/OpenSSL) And I'm seeing this on boot:
![capture d ecran 2016-08-31 a 23 25 06](https://cloud.githubusercontent.com/assets/2040775/18146929/9dbf5a50-6fd2-11e6-8b44-4d06bff818e5.png)

**Comment by fichtner** [comment]
Work in progress. This area of opnsense-update is still under development. For now the error is intended and only on -devel. :)

**Comment by gitdevmod** [comment]
ok, thanks!

**Comment by fichtner** [comment]
These stubs will prevent the message from appearing in 16.7.4 even when the work isn't finished:

https://github.com/opnsense/update/commit/275cc86ab05a8d361782efda98535544bfc7f85e
