### ISSUE TITLE
Bridge device not fully up after reboot

### ISSUE THREAD

**Issue by labor4** [opnsense/core#1167]
Hi
I'm not sure if this is a bug, cause I'm no 100% expert, so please be easy on me.

I experience the bridge device not being fully up after each reboot.

i did:
- enable PORT 1, dont configure.
- enable PORT 2, dont configure
- create Bridge with PORT 1+2, and configure it with an IP.

have I understood something very wrong here?
I didn't look at the Bridge advanced settings, though.

when I go into "Interfaces > Bridge", just save it again, and so being able to apply the "changes" again, the bridge's IP starts to work as a gateway, but otherwhise no.

thanks
best
manu

**Comment by fichtner** [comment]
Hi manu,

Bugs like that have popped up now and then, this could be one so don't worry.

I did, however, assume a log of things:

1. OPNsense updasted to 16.7.3.
2. PORT 1 enabled meaning assigned a physical port as an interface OPT1, enabling it but not putting any IP configuration in there.
3. Same as above for PORT 2 as OPT2.
4. Added a bridge based on PORT 1 and PORT 2.
5. Assigned the bridge as an interface OPT 3, enabled it and put a static IPv4 configuration.
6. After reboot, the IP configuration is there and the bridge has the UP flag from ifconfig output.

<img width="704" alt="screen shot 2016-09-02 at 7 19 56 am" src="https://cloud.githubusercontent.com/assets/1915288/18193422/baaa7c56-70dd-11e6-8559-717bc3d93d50.png">

So my question is: does your setup steps differ or do you have the same behaviour and we're looking into a connectivity issue beyond the mere setup steps and interface configuration during boot itself?


Cheers,
Franco

**Comment by labor4** [comment]
Hi Franco

Yes exactly, I wasnt aware of the assign step anymore. but yes.
I cannot reboot right now, though, so i cannot check the fresh ifconfig command.


m

**Comment by fichtner** [comment]
( may be related to: https://github.com/opnsense/core/issues/1180 )

**Comment by fichtner** [comment]
Try this from the root shell when you have a moment to reboot:

# opnsense-patch 17b3374 && /usr/local/etc/rc.reboot

**Comment by fichtner** [comment]
Fixes in 16.7.5. Hopefully done, if not please reopen. :)


Cheers,
Franco

**Comment by labor4** [comment]
I think it got fixed soon, now it's there again in:

OPNsense 16.7.13-amd64
FreeBSD 10.3-RELEASE-p14
OpenSSL 1.0.2j 26 Sep 2016

still, resaving the bridge-intf makes it work.
