### ISSUE TITLE
System: Access: Tester does not return group from user

### ISSUE THREAD

**Issue by ccesario** [opnsense/core#1169]
Hi,

Tester form does not return Group name of user when using Active Directory as Server

![ad_tester](https://cloud.githubusercontent.com/assets/1812609/18205704/cb057a58-70f9-11e6-838b-d0d0c71d18b0.png)

Versions	OPNsense 16.7.3-amd64
FreeBSD 10.3-RELEASE-p7
OpenSSL 1.0.2h 3 May 2016

**Comment by AdSchellevis** [comment]
@ccesario did you import the user first and assign groups to it?

**Comment by ccesario** [comment]
@AdSchellevis not. I really did not see it. Where can I do it!?

**Comment by AdSchellevis** [comment]
@ccesario no problem, you should see a cloud symbol in the system -> access -> user screen on the right bottom of the screen. You can import users into the OPNsense configuration, which you can then assign groups and rights.

**Comment by ccesario** [comment]
@AdSchellevis well, I think that the cloud synbol does not appear in my system.

look this

![image](https://cloud.githubusercontent.com/assets/1812609/18220909/232b7540-714d-11e6-8fd8-ba5bc6169046.png)

**Comment by AdSchellevis** [comment]
ah, I see. it only appears if ldap (/AD) is used as authentication option for the UI. This is handled in the settings (2 menu items below).

**Comment by Pimmal** [comment]
The same problem is here on my side: Tester form does not return Group name of user when using Active Directory as Server

**Comment by AdSchellevis** [comment]
Groups are only supported if LDAP (/AD) is used as authentication for the webgui, System -> Access -> Settings, then choose your server. Next import users into the configuration.
There currently are no other services which make use of groups.

**Comment by Pimmal** [comment]
> Import users into the configuration.

The Users are created in AD, were i have to import the users?
If i have to import the users then AD auth makes no sense.

**Comment by AdSchellevis** [comment]
If you want to assign rights within OPNsense, you need to import users,  if you just want to use the connector (e.g. openvpn, ipsec), you don't need to assign privileges and therefore don't need to import the users into the firewall (and hence don't need the assigned groups either). 
LDAP (/AD) is used for authentication only, authorisation is handled within the product itself. 

For reference, the original issue was solved in this issue https://github.com/opnsense/core/issues/266 
The reason for handling authorisation locally is simple, keep the acl structure clean and simple without interaction to other services. Like in a lot of other products the "linking pin"  needs to be stored in the product to use it.

We do need some documentation about this subject.

**Comment by Pimmal** [comment]
But it makes no sense to create the users in opnsense localy, i use the AD auth to administrate the opnsense admins in AD, like in pfsense. There all users with the AD Groups pfsense-admin have access to the admin features. I would prefere to do the same in opnsense, if this is not possible then i have to use the non stable pfsenseproduct.

**Comment by AdSchellevis** [comment]
You could write your own scripting to synchronize users between the two (or sponsor the feature). We don't supply scripting for this at the moment. 
The hook pfSense has to query the groups from within the authentication request won't make it to OPNsense (architectural choice). Synchronisation could reach a similar behaviour.

**Comment by AdSchellevis** [comment]
@jschellevis added documentation https://docs.opnsense.org/manual/how-tos/user-ldap.html
