### ISSUE TITLE
HA sync does not work

### ISSUE THREAD

**Issue by fichtner** [opnsense/core#117]
via https://forum.opnsense.org/index.php?topic=266.0

---

Master

Mar 28 19:26:43	opnsense: /system_hasync.php: Configuring CARP settings finalize...
Mar 28 19:26:43	opnsense: /system_hasync.php: pfsync done in 0 seconds.
Mar 28 19:26:43	opnsense: /system_hasync.php: waiting for pfsync...
Mar 28 19:26:42	kernel: pid 49446 (ifconfig), uid 0: exited on signal 10 (core dumped)
Mar 28 19:26:42	kernel: carp: demoted by 240 to 240 (pfsync bulk start)
Mar 28 19:26:42	opnsense: /usr/local/etc/rc.filter_synchronize: New alert found: A communications error occurred while attempting XMLRPC sync with username root https://10.50.110.4:443.

Mar 28 19:26:42	opnsense: /usr/local/etc/rc.filter_synchronize: A communications error occurred while attempting XMLRPC sync with username root https://10.50.110.4:443.

Mar 28 19:26:42	opnsense: /usr/local/etc/rc.filter_synchronize: XML_RPC_Client: Connection to RPC server 10.50.110.4:443 failed. 103
Mar 28 19:26:41	opnsense: /usr/local/etc/rc.filter_synchronize: New alert found: A communications error occurred while attempting XMLRPC sync with username root https://10.50.110.4:443.

Mar 28 19:26:41	opnsense: /usr/local/etc/rc.filter_synchronize: A communications error occurred while attempting XMLRPC sync with username root https://10.50.110.4:443.

Mar 28 19:26:41	opnsense: /usr/local/etc/rc.filter_synchronize: XML_RPC_Client: Connection to RPC server 10.50.110.4:443 failed. 103

Slave

Mar 28 19:23:58	opnsense: /usr/local/etc/rc.filter_configure_sync: Could not find IPv6 gateway for interface(lan).
Mar 28 18:23:58	configd.py: Reloading filter
Mar 28 19:23:58	opnsense: /usr/local/etc/rc.filter_synchronize: Config sync not being done because of missing sync IP (this is normal on secondary systems).
Mar 28 18:23:58	configd.py: Syncing firewall
Mar 28 19:22:35	opnsense: /usr/local/etc/rc.filter_synchronize: Config sync not being done because of missing sync IP (this is normal on secondary systems).
Mar 28 18:22:35	configd.py: Syncing firewall
Mar 28 19:19:11	opnsense: /diag_logs_filter.php: There was a error parsing rule: . Please report to mailing list or forum.
Mar 28 19:19:11	opnsense: /diag_logs_filter.php: There was a error parsing rule: . Please report to mailing list or forum.
Mar 28 19:19:11	opnsense: /diag_logs_filter.php: There was a error parsing rule: . Please report to mailing list or forum.
Mar 28 19:19:11	opnsense: /diag_logs_filter.php: There was a error parsing rule: . Please report to mailing list or forum.

**Comment by AdSchellevis** [comment]
The xmlrpc server part looks broken and very old/unsupported, I'm working on a replacement.

**Comment by fichtner** [comment]
@AdSchellevis thanks for picking this up! :+1:

**Comment by AdSchellevis** [comment]
fixed, last bits and pieces in https://github.com/opnsense/core/commit/20118288e243a058cdb9ca94ca33a2bd97576e76
