### ISSUE TITLE
Inconsistent use of rule + button

### ISSUE THREAD

**Issue by reetp** [opnsense/core#1173]
Just noticed something.

I was looking to add a rule. I kept looking for the + button in the middle of the screen which is where it is when there are no rules.

Once you have created a rule the button switches to lower right and loses the help tag.

It's cosmetic as I know it works - just frustrating when you are learning your way round and things do not appear where you expect them. You start thinking you have missed something !

Keeping things like a + button in the same place where possibly just helps consistency (I accept I could just be getting old !)

![norules](https://cloud.githubusercontent.com/assets/3800384/18245952/8a02bf36-7368-11e6-8ea8-e2e8de4e8448.png)

![withrules](https://cloud.githubusercontent.com/assets/3800384/18245960/917e555e-7368-11e6-8f50-44133777b845.png)

**Comment by AdSchellevis** [comment]
Hi John,

Can you please use our forum for discussions (https://forum.opnsense.org/ )? Too many questions in our issue tracker make it quite difficult to prioritize the actual work.
Through the rest of our interface all actions are at the bottom right of the grid, the note is only an extra (which some people find quite useful).

Cheers,

Ad

**Comment by reetp** [comment]
I'm not really asking a question but pointing out a flaw in the UI....
I can talk about it all you want in the forums but would it get changed (which personally I think it should be) ? I agree the note is useful, but the button position is inconsistent.

**Comment by AdSchellevis** [comment]
ok, what is your proposal here then?

**Comment by reetp** [comment]
Something like this for every rule on every page so you have the consistent + button to the right.

Don't make the + in the centre message a link - you always have to click the button at right to add a rule.

![message](https://cloud.githubusercontent.com/assets/3800384/18247383/82219602-7372-11e6-8f4a-35d2e2eb6b88.png)

This is a very rough stab at hacking the code - I can't quite get the columns right but you will get the idea

root@OPNsense:/usr/local/www # diff -ruN firewall_rules.php.orig firewall_rules.php
```
--- firewall_rules.php.orig	2016-09-05 14:19:43.236704000 +0200
+++ firewall_rules.php	2016-09-05 14:35:31.777647000 +0200
@@ -625,17 +625,23 @@
                   if (!$interface_has_rules):
 ?>
                   <tr>
-                    <td colspan="11" align="center" valign="middle">
+                    <td colspan="6" align="center" valign="middle">
                     <span class="text-muted">
                 <?php if ($selected_if == "FloatingRules"): ?>
                       <?=gettext("No floating rules are currently defined."); ?><br /><br />
+		       <td colspan="3" class="hidden-xs hidden-sm" align="right"><?=gettext("Click the + button to add a new rule");?></td>
+		       <td> <a href="firewall_rules_edit.php?if=<?=$selected_if;?>" class="btn btn-default btn-xs" data-toggle="tooltip" title="<?=gettext("add new rule");?>">
+                        <span class="glyphicon glyphicon-plus"></span>
+                      </a></td>
                 <?php else: ?>
                       <?=gettext("No rules are currently defined for this interface"); ?><br />
                       <?=gettext("All incoming connections on this interface will be blocked until you add pass rules."); ?><br /><br />
+		       <td colspan="3" class="hidden-xs hidden-sm" align="right"><?=gettext("Click the + button to add a new rule");?></td>
+		       <td> <a href="firewall_rules_edit.php?if=<?=$selected_if;?>" class="btn btn-default btn-xs" data-toggle="tooltip" title="<?=gettext("add new rule");?>">
+                        <span class="glyphicon glyphicon-plus"></span>
+                      </a></td>
                 <?php endif; ?>
-                      <?= sprintf(gettext("Click the %s button to add a new rule."),
-                                  '<a href="firewall_rules_edit.php?if='.$selected_if.'" class="btn btn-default btn-xs"><span class="glyphicon glyphicon-plus"></span></a>')
-                      ?></span>
+                      </span>
                     </td>
                   </tr>
               <?php else: ?>
@@ -656,7 +662,7 @@
                         endforeach;?>
                       </select>
                     </td>
-                    <td colspan="5" class="hidden-xs hidden-sm"></td>
+                    <td colspan="5" class="hidden-xs hidden-sm" align="right"><?=gettext("Click the + button to add a new rule");?></td>
                     <td>
                       <a type="submit" id="move_<?=$i;?>" name="move_<?=$i;?>_x" data-toggle="tooltip" title="<?=gettext("move selected rules to end");?>" class="act_move btn btn-default btn-xs">
                         <span class="glyphicon glyphicon-arrow-left"></span>

```

**Comment by reetp** [comment]
More like this

![newrule](https://cloud.githubusercontent.com/assets/3800384/18248124/cf5798e6-7376-11e6-862c-89b95bfdb88a.png)

**Comment by AdSchellevis** [comment]
To be honest, we might as well ditch the "Click the +..." completely if we move it over to the same area.... We're not trying to explain other grids in the system either. 
How about leaving it like it was and un-hide the bottom row?

**Comment by reetp** [comment]
Yup - does it for me if it is easier. Let me know if you have a patch to want me to try.

**Comment by AdSchellevis** [comment]
ok, here it is https://github.com/opnsense/core/commit/9503d722d95f6c697e43779d6a980b6bb737b008

**Comment by reetp** [comment]
Looks good :-) Personally I'd keep the nice little + icon as an indicator but lose the clickable URL.  You are trying to push people to use one button in the same place and be consistent.

But it looks more sensible now.

**Comment by AdSchellevis** [comment]
ok, I don't have a preference here, so let's stick to your plan and change it for " Click the [+] button to add a new rule. ". I will close the issue on commit.
