### ISSUE TITLE
Feature: RADIUS support for IPsec authentication, authorization and accounting

### ISSUE THREAD

**Issue by Strykar** [opnsense/core#1174]
strongSwan supports RADIUS for authentication, authorization and CoA.
OPNsense supports external RADIUS servers, letting strongSwan use this for authentication and accounting would be great.

strongSwan also supports DAE -
The Dynamic Authorization Extension allows a RADIUS backend to actively terminate a session using a Disconnect-Request, or change the timeout of a session using a Session-Timeout attribute in a CoA-Request. 
See https://wiki.strongswan.org/projects/strongswan/wiki/EAPRAdius

Building RADIUS support for things outside the captive portal would be useful, OpenVPN can use RADIUS for AAA too.

**Comment by AdSchellevis** [comment]
closed with https://github.com/opnsense/core/pull/1345
