### ISSUE TITLE
All traffic on WAN network blocked

### ISSUE THREAD

**Issue by andreas-p** [opnsense/core#1175]
I'm having trouble pinging my new firewalls on the WAN side. Pinging the other (carp backup) firewall doesn't respond, neigher does any service on the firewall if the client is located directly in the WAN network.

If I edit rules.debug and remove the reply-to clause from
_pass  in  quick  on $WAN reply-to ( <WLAN-GW>) inet proto icmp  from any to any keep state_, traffic starts to go through. Apparently, I can't create a rule that doesn't include reply-to using the gui.

Strange enough, on some ancient 2.1 pfs firewalls there's the same reply-to, but ping works nevertheless.

**Comment by AdSchellevis** [comment]
@andreas-p you can set "disable reply-to" in the advanced section of the firewall rules.

**Comment by andreas-p** [comment]
Right, there's the option (did expect a "none" gateway option). Now I'm able to add another rule _Allow ICMP for WAN net to WAN net without reply-to_, and this actually works (with some restrictions).
BUT:
I still think there's something wrong. When allowing _ICMP any to any_, I'd expect this to work, reply-to defined or not. Since it's the same subnet, there's no gateway affected (actually, since it's a preparation installation the gateway isn't present), and the reply-to shouldn't have any effect. As mentioned, on pfs 2.1.5 and 2.2.4 this works as expected.

Another flaw:
I had that WAN net to WAN net rule defined already. When I changed it on the carp master to drop reply-to, I could see this with pfctl, but on the backup only the gui would show the change, but it wouldn't get applied to pf until I triggered a rule apply on the backup by re-saving a rule.

**Comment by AdSchellevis** [comment]
its not a bug, it will send the packet to the next router, if that one reflects it back into the same net (which most won't do) it will work. pfs has a lot of kernel patches which breaks standard functionality, this might as well be another one. 
You can either disable this functionality, or add an additional rule for the network on your wan.

Can you please move discussions on how functionality works to the forum in the future?

**Comment by andreas-p** [comment]
Ok if this is by design... Still think it's odd to redirect traffic in the very same network which obviously doesn't need routing hops.
