### ISSUE TITLE
Unable to add sites via console to "/usr/local/etc/squid/nobumpsites.acl"

### ISSUE THREAD

**Issue by Strykar** [opnsense/core#1176]
White-listing a long list of sites and entering it directly in to `/usr/local/etc/squid/nobumpsites.acl` is ignored. Could this be allowed instead of entering 1 site at a time via the web interface in to the `SSL no bump sites` list at `/ui/proxy/#subtab_proxy-forward-general` which takes an inordinately long time for a long list.

**Comment by AdSchellevis** [comment]
You can paste a comma separated list in the input box, like :

`wwww.sitea.com,wwww.siteb.com,wwww.sitec.com`

You cannot edit the the nobump file manually (won't be supported either), if you would like to manually hack into squid, you can however use custom hooks https://github.com/opnsense/core/issues/802

**Comment by Strykar** [comment]
Thanks for clearing that up. Perhaps that could be made clear in the tool tip. https://github.com/opnsense/core/pull/1179
