### ISSUE TITLE
Keeping 2 dashboards open in Microsoft Edge overnight consumes 12GB RAM

### ISSUE THREAD

**Issue by Strykar** [opnsense/core#1177]
Keeping just 2 tabs with 2 OPNSense dashboards over night had MS Edge consume 12 GB of RAM and would've climbed had the machine not started to swap and killed other applications.

They each had 12 dashboard widgets running. I'm unsure how to help troubleshoot this issue.

**Comment by Strykar** [comment]
This seems to be a bigger issue with Edge than IE (11.545.10586)
Leaving a single tab in IE open for 14 hours increased RAM consumption for IE from 162MB to 235MB.

I will test some more with Firefox & Chrome and all addons disabled.

**Comment by fichtner** [comment]
This is a problem in the JavaScript of the dashboard. It duplicates https://github.com/opnsense/core/issues/1013 so I'm closing this one.
