### ISSUE TITLE
Translation issues in interfaces.php 

### ISSUE THREAD

**Issue by fabianfrz** [opnsense/core#1178]
This range is unclear (configuration directives instead of normal language) - it should be changed to be understandable by users:
https://github.com/opnsense/core/blob/master/src/www/interfaces.php#L2564-L2630

This should be kept together in the gettext call:
https://github.com/opnsense/core/blob/master/src/www/interfaces.php#L2683

**Comment by fichtner** [comment]
*runs for cover*

**Comment by fabianfrz** [comment]
I cannot fix this as I have no idea what pltime, vltime etc. is.

**Comment by fichtner** [comment]
close then?

**Comment by fabianfrz** [comment]
No, the issue does still exist.

**Comment by fichtner** [comment]
If nobody fixes it we may as well close it.

**Comment by fabianfrz** [comment]
You may understand it better than I do:
https://www.freebsd.org/cgi/man.cgi?query=dhcp6c.conf&apropos=0&sektion=0&manpath=FreeBSD+Ports+8.4-RELEASE&arch=default&format=html

I think it may be something like lifetime but then what are p and v?
