### ISSUE TITLE
Deleting one firewall rule deletes them all

### ISSUE THREAD

**Issue by mannkind** [opnsense/core#118]
I'm encountering an issue where trying to delete a single firewall rule via the **[ x ]** button within the row deletes *all* of my firewall rules (except RFC 1918/Reserved IANA). I can also reproduce it on a brand new install in a test VM.

OPNSense Version: 15.1.8.2 

**Steps to reproduce**
* Create a number of rules, it doesn't seem to matter what the rules contain. For my test, I created `3` rules and only changed two fields – Destination and Description. 
  * Rule (id = 0): Destination = 192.168.0.1; Description = Test 1
  * Rule (id = 1): Destination = 192.168.0.2; Description = Test 2
  * Rule (id = 2): Destination = 192.168.0.3; Description = Test 3
* Click *Apply Changes*
* Click the **[ x ]** button on the row for rule w/Description Test 2
 * **Side Note** While writing this bug report I noticed when I hover over the [ <- ] button there is a javascript error `fr_insline is not defined`

**Expected result**
Firewall rule w/Description *Test 2* is deleted

**Actual result**
All firewall rules except RFC 1918/Reserved IANA are deleted

**Comment by AdSchellevis** [comment]
Found the issue, thanks for bringing it in. 
Fixed in https://github.com/opnsense/core/commit/0fa6332a7b5e264d5c414da0672bf74d7f1170b1 
The javascript issue apparently was a leftover from some old code, removed the events in the following commit.
