### ISSUE TITLE
Sysctl not set when module not loaded yet (bridging)

### ISSUE THREAD

**Issue by AdSchellevis** [opnsense/core#1180]
collected from crash report:
______
I set The system Tunable:
net.link.bridge.pfil_member to 0 for Bridging.
After reboot, Bridging is not working.
Tunable is still 0 but I have to edit and save it again to enable bridging.
______

Which is a result from using bridging as a module, which isn't loaded at the time sysctl is set.
Two options come to my mind, up for debate what the proper fix is/should be here:

1)   move system_setup_sysctl() to the bottom of rc.bootup
2)  add if_bridge to load_kernel_module() in system.inc

**Comment by fichtner** [comment]
Option 2 was the better one. if_bridge would have landed there if ifconfig didn't load it when it needed it, but obviously this stuff needs more. Eventually, the kernel modules should move to rc.loader.d where we can load them before going into multi-user mode. :)
