### ISSUE TITLE
Unable to delete user if french is selected

### ISSUE THREAD

**Issue by gitdevmod** [opnsense/core#1181]
If language french is selected, the delete user button does not display pop up for yes or no.
OPNsense 17.1.a_277-amd64
FreeBSD 10.3-RELEASE-p7
OpenSSL 1.0.2h 3 May 2016

**Comment by fichtner** [comment]
JavaScript breaks with French translation likely. Following string needs a html_safe() wrapped around:

gettext("Do you really want to delete this user?")

Not at home so can't fix but should be easy :)

**Comment by fabianfrz** [comment]
@fichtner it is possible to do changes via the GitHub website.

Is it this line? https://github.com/opnsense/core/blob/master/src/www/system_usermanager.php#L411
