### ISSUE TITLE
DNS Forwarder (DNSMASQ) does not listen to CARP IPv6 address unless 'ALL' is ticked

### ISSUE THREAD

**Issue by syserr0r** [opnsense/core#1182]
When selecting specific interfaces for the DNS Forwarder to listen on, if one of them is a CARP/Virtual IPv6 address then this CARP/Virtual IPv6 interface does not respond to DNS requests.

Selecting 'ALL' interfaces to listen on allows the the DNS forwarder to respond on the CARP/Virtual IPv6 address.

**Comment by AdSchellevis** [comment]
@syserr0r can you check the contents of /var/unbound/unbound.conf  ? I don't have a similar setup available, but my generated config seems to contain the correct data in it, something like : 

# Interface IP(s) to bind to
interface: x.x.x.x
interface: y:y:y:y:y


Next thing to do is check the generated ACL, if your interface only has a vip in the same subnet, that might be your issue. Check the contents of  /var/unbound/access_lists.conf to be sure.

**Comment by syserr0r** [comment]
It's the DNS forwarder (dnsmasq) not the DNS resolver (unbound) that I am having this issue with.

**Comment by AdSchellevis** [comment]
@syserr0r my mistake, can you try this patch https://github.com/opnsense/core/commit/52c78955b8156519ec79717472f3ae3560f012ff ?

`opnsense-patch 52c78955
`

**Comment by syserr0r** [comment]
No change, in fact selecting the CARP/IPv6 virtual address causes it not to respond at all, even on the IPv4 addresses. Selecting 'ALL' causes it to work again.

**Comment by AdSchellevis** [comment]
@syserr0r can you check if your vip addresses where appended to dnsmasq?

`ps auxww | grep dnsmasq`

**Comment by syserr0r** [comment]
Update: This is related to https://github.com/opnsense/core/issues/1184#issuecomment-248700859 I am going to re-test now the IPv6 CARP/VIP is now working

**Comment by syserr0r** [comment]
Re-tested with working IPv6 CARP/VIP and this seems to be working properly now.

**Comment by AdSchellevis** [comment]
@syserr0r thanks for testing, I will close this one then.
