### ISSUE TITLE
IPv6 CARP/Virtual IP does not support abbreviated notation

### ISSUE THREAD

**Issue by syserr0r** [opnsense/core#1184]
Adding an IPv6 CARP Virtual IP such as `1:2:3::feed` appears to work but the interface does not appear to accept or respond to any packets.

Entering the IP as `1:2:3:0:0:0:0:feed` allows the virtual IP/interface to work as normal

**Comment by AdSchellevis** [comment]
@syserr0r I don't have a test setup available at the moment, can you post some screenshots of ifconfig for both situations?

**Comment by syserr0r** [comment]
I don't have access to the production set-up right now and as it's a remote site I don't want to break it if I can avoid it.

I might try and replicate at our offices if you still need?

**Comment by AdSchellevis** [comment]
sure, it might help tracking it down.

**Comment by syserr0r** [comment]
I have just tried this again and it appears to be working with shortened notation although I haven't tried a restart yet (`ifconfig` produced identical results in both cases).

**Comment by AdSchellevis** [comment]
@syserr0r ok, lets close this for now then and reopen if you have more info.

**Comment by syserr0r** [comment]
More info (reproduced)
Short notation:
```
em1: flags=8943<UP,BROADCAST,RUNNING,PROMISC,SIMPLEX,MULTICAST> metric 0 mtu 1500
options=9b<RXCSUM,TXCSUM,VLAN_MTU,VLAN_HWTAGGING,VLAN_HWCSUM>
        ether 00:0c:29:e6:77:b1
        inet 10.10.10.201 netmask 0xff000000 broadcast 10.255.255.255
        inet6 fe80::20c:29ff:fee6:77b1%em1 prefixlen 64 scopeid 0x2
        inet6 2a02:390:7392::1 prefixlen 64
        inet 10.10.10.254 netmask 0xff000000 broadcast 10.255.255.255 vhid 2
        inet6 2a02:390:7392::feed prefixlen 64 duplicated vhid 6
        nd6 options=21<PERFORMNUD,AUTO_LINKLOCAL>
        media: Ethernet autoselect (1000baseT <full-duplex>)
        status: active
        carp: MASTER vhid 2 advbase 1 advskew 0
        carp: MASTER vhid 6 advbase 1 advskew 0 
```

Long notation:
```
em1: flags=8943<UP,BROADCAST,RUNNING,PROMISC,SIMPLEX,MULTICAST> metric 0 mtu 1500
options=9b<RXCSUM,TXCSUM,VLAN_MTU,VLAN_HWTAGGING,VLAN_HWCSUM>
        ether 00:0c:29:e6:77:b1
        inet 10.10.10.201 netmask 0xff000000 broadcast 10.255.255.255
        inet6 fe80::20c:29ff:fee6:77b1%em1 prefixlen 64 scopeid 0x2
        inet6 2a02:390:7392::1 prefixlen 64
        inet 10.10.10.254 netmask 0xff000000 broadcast 10.255.255.255 vhid 2
        inet6 2a02:390:7392::feed prefixlen 64 vhid 6
        nd6 options=21<PERFORMNUD,AUTO_LINKLOCAL>
        media: Ethernet autoselect (1000baseT <full-duplex>)
        status: active
        carp: MASTER vhid 2 advbase 1 advskew 0
        carp: MASTER vhid 6 advbase 1 advskew 0 
```

The differences being:
`inet6 2a02:390:7392::feed prefixlen 64 duplicated vhid 6` (short) vs
`inet6 2a02:390:7392::feed prefixlen 64 vhid 6` (long)
