### ISSUE TITLE
PPPoE option dial-on-demand can not be enabled with a timeout of 0 (disabled)

### ISSUE THREAD

**Issue by syserr0r** [opnsense/core#1185]
I'm not sure if intentional but the 'dial on demand' PPPoE option does not allow a timeout of 0 (GUI produces an error and doesn't allow saving).

Looking at the help text for the timeout option would suggest this should be acceptable.

Additionally entering a value of '00' bypasses the restriction (although I am unsure of the implications)

**Comment by syserr0r** [comment]
Note: The reason I was looking to do this was a PPPoE connection HA/CARP where the backup/idle connection would be 'disconnected' as no traffic would be going to it. When it becomes the master it would receive traffic and dial -- if there is a better way of doing this then please let me know.

**Comment by AdSchellevis** [comment]
@syserr0r the feature isn't intended for this scenario, but if it works for your case I have no big objection in removing the timeout validation here.

The mpd options are described here http://mpd.sourceforge.net/doc5/mpd28.html on-demand should interact with timeout, which is the trigger to disconnect to provide a "virtual full time" connection. 

Another option could be to allow plugins on the carp master/backup events to bring the interface up/down when the trigger occurs. You would need a script to make it work, but I expect it would provide a more predictable solution.

**Comment by syserr0r** [comment]
Incidentally my CARP VIPs for the PPPoE interface don't show a status in the web UI but seem to function OK.

**Comment by AdSchellevis** [comment]
ok, lets remove the check here, it's not an invalid config according to mpd.

**Comment by syserr0r** [comment]
@AdSchellevis I would prefer to keep things in-UI and not have to script modifications (that might change between releases) as I don't have much time to commit to maintaining firewall modifications -- I was looking for OPNsense as a powerful firewall replacement, not really an alternative to running a *nix box with iptables etc.

**Comment by AdSchellevis** [comment]
@syserr0r I know, but sometimes you can't add an option for general use and simple scripts help in that case. If this option works for you, I'm certainly fine with it.
I've removed the check https://github.com/opnsense/core/commit/1ccf6b4527441d9a974978610bc1e98edb414c9f can you check and close the issue?

**Comment by syserr0r** [comment]
@AdSchellevis  I don't have a dev env (I should probably set one up) but that looks like it should resolve the issue. On the production system the timeout is set for 24hrs until this comes through.

**Comment by AdSchellevis** [comment]
@syserr0r ok, I'll close the issue then.
