### ISSUE TITLE
netgraph, remove hooks

### ISSUE THREAD

**Issue by AdSchellevis** [opnsense/core#1188]
I think we should remove the attach/detach hooks in the code, there doesn't seem to be a valid reason for detaching netgraph (other then a probably very minor performance gain).

When we do, we could trash the following functions, which moves us further to standards:
- interface_netgraph_needed
- legacy_netgraph_detach
- legacy_netgraph_attach

up for debate.

**Comment by fichtner** [comment]
We can gladly strip them. I would wish that we could have a speed measurement though to verify the netgraph impact.

We could also try to improve the situation by making netgraph an on-demand load. I know that the netflow module already does that, MPD5 should be clever enough to do the rest for all multi-point connections. 😊

**Comment by AdSchellevis** [comment]
as soon as I can find some time, I will a simple test with and without, if the impact is low... strip all :)

**Comment by fichtner** [comment]
I will strip everything from the code tomorrow. This will also remove the infamous ngattach utility and the inherited kernel patch... In theory the same is possible with kldunload as the subsequent kldload will reattach all devices. But if the impact is small this doesn't matter and we end up with the longed-for standard netgraph setup after all. 😊

**Comment by AdSchellevis** [comment]
@fichtner great! thanks

**Comment by fichtner** [comment]
@jschellevis @AdSchellevis -devel has had ngattach completely  removed a while back. I really don't want to bring it back in 17.1 -- do we have numbers to back up the removal?

**Comment by AdSchellevis** [comment]
@fichtner sorry, it has been too busy lately, but I really don't expect we're going to move the hooks back in. I will try to do some measurements before release.

**Comment by AdSchellevis** [comment]
checked today, no noticeable difference.
