### ISSUE TITLE
Captive portal + transparant proxy can't be combined

### ISSUE THREAD

**Issue by AdSchellevis** [opnsense/core#1189]
from https://forum.opnsense.org/index.php?topic=3670.msg12576#msg12576

It would be practical if we could tag the packets in ipfw, so we could skip mangling in pf. That would also solve https://github.com/opnsense/core/issues/1166

**Comment by fichtner** [comment]
patch available, test builds soon

**Comment by fichtner** [comment]
Call for testing instructions here: https://forum.opnsense.org/index.php?topic=3704.0
