### ISSUE TITLE
Unbound listen issues

### ISSUE THREAD

**Issue by andreas-p** [opnsense/core#1190]
In order to have unbound listen on virtual IPs, it's not sufficient to select "ALL". Instead, each vip has to be selected individually. 
The interfaces list misses localhost, so to have unbound listen on localhost again, I had to add interface: 127.0.0.0 in the custom section

**Comment by fichtner** [comment]
7127524124a79246175eb7b887731d7539e28ab4 should fix your issue:

    # opnsense-patch 712752412

**Comment by fichtner** [comment]
closing unless something came up. included in 16.7.9 tomorrow
