### ISSUE TITLE
GRE Tunnel: Alias Address

### ISSUE THREAD

**Issue by ip6li** [opnsense/core#1191]
It seems there is no GUI supported way to add an alias address to a GRE interface.

Example from a Debian installation to explain problem:

```
auto mygre
iface mygre inet static
    address 192.168.78.6
    netmask 255.255.255.252
    pre-up ip tunnel add mygre mode gre remote 192.168.0.1 local 192.168.1.1 ttl 255
    up ip route add default via 192.168.78.5
    post-down ip tunnel del mygre

iface mygre inet6 static
    address fd00:7a0:1::16
    netmask 126
    up ip -6 route add default via fd00:7a0:1::15
```

This config builds a gre tunnel on Linux from 192.168.0.1 to 192.168.1.1 and assigns following IP addresses to GRE interface: 192.168.78.6 and fd00:7a0:1::16 so that GRE interface becomes usable for dual stack operation.

OPNsense GUI does not support multiple IP addresses bound on one GRE tunnel.

**Comment by fichtner** [comment]
Hi there,

Interesting, it seems that GRE wants an IPv4 in the Device setup, and doesn't allow an IPv4/IPv6 assignment from the interfaces. Judging by the use case this is not entirely about arbitrary aliases but the ability to assign an IPv6 address as well.

Firewall: Virtual IP may work in your case, too, but the GUI should not impose the restrictions as it does right now. I will queue this up for 17.1.


Cheers,
Franco

**Comment by fichtner** [comment]
Not sure what's required here anymore. No requests since. Timeout.

**Comment by proap** [comment]
I still can't configure a dual-stack configuration through a GRE tunnel. Setting up a virtual IP doesn't do the job because when one needs to configure the interfaces there is no gateway properly configured. Is there a way of doing this?

**Comment by Phiwatec** [comment]
Same here. Would love to use GRE as a way to tunnel IPv6 over an IPv4 only network. Currently OPNsense doesn't allow an IPv6 address to be assigned to a GRE Tunnel Interface.

**Comment by AdSchellevis** [comment]
@Phiwatec and you did try to assign the interface and stack an alias on top? I don't think there are any validations on our end preventing this from happening as long as the interface is assigned and active.  If you're looking for something else, best try to implement it command line first (using FreeBSD's documentation) and post a small sample of how your use-case can work.
