### ISSUE TITLE
Unbound writes an empty / line in access list and is not able to start

### ISSUE THREAD

**Issue by wokienl** [opnsense/core#1192]
Unbound writes an empty / line in access list and is not able to start

This happens when All is selected (default) in Services - DNS Resolver - General - Network Interfaces
![opnsense dns resolver slash](https://cloud.githubusercontent.com/assets/22257644/18608648/74f0f898-7cef-11e6-9876-d8db9cdb649e.png)

Release: OPNsense 16.7.3-amd64 with the latest updates. 
Configuration:
- WAN interface ipv4 and ipv6 
- LAN interface ipv4 static and ipv6 track interface 
- OPT1, OPT2, OPT3, VLAN interfaces with static ipv4 

Workaround:
- Select only the some specific network interfaces instead of All interfaces.

**Comment by AdSchellevis** [comment]
@wokienl can you try this commit? https://github.com/opnsense/core/commit/86996d7bf74d7eadcd0879d8edb5aa3d7f807b32

easy to try from you machine, using:

`opnsense-patch 86996d7b
`

**Comment by wokienl** [comment]
Great, it works now!

No '/' in the access list anymore and unbound is able to startup with the default setting of All network interfaces. 

The patch is indeed very simple to apply.
