### ISSUE TITLE
Two items are selected in webconfigurator reporting

### ISSUE THREAD

**Issue by wokienl** [opnsense/core#1193]
In the webconfigurator two items are selected, but just one is shown. I guess only one can be showed in the reporting screen, so it seems the orange selection color is not taken away from items which are selected before.  This seems to happen only once, after clicking around a few times the problem disappears. 

OS: Windows 10 
Chrome: Version 53.0.2785.116 m (64-bit)
Edge: 38.14393.0.0

![2016-09-19 13_14_14-system health](https://cloud.githubusercontent.com/assets/22257644/18630213/3f230206-7e6b-11e6-9a81-cfa6ca742ea1.png)

**Comment by AdSchellevis** [comment]
timeout
