### ISSUE TITLE
DHCP - Undefined Functions (system_dhcpleases_configure and services_dhcpleases_configure)

### ISSUE THREAD

**Issue by rafaelcrocce** [opnsense/core#1194]
Sometimes, there's an error showing of two undefined functions **system_dhcpleases_configure()** and **services_dhcpleases_configure()**.

The files which calls this functions are:
/usr/local/www/services_dhcp.php (services_dhcpleases_configure())
/usr/local/etc/inc/interfaces.inc (services_dhcpleases_configure())
/usr/local/etc/inc/services.inc (system_dhcpleases_configure())
/usr/local/etc/inc/xmlrpc/legacy.inc (services_dhcpleases_configure())
/usr/local/etc/rc.bootup (services_dhcpleases_configure())
/usr/local/etc/rc.newwanip (services_dhcpleases_configure())
/usr/local/etc/rc.reload_all (services_dhcpleases_configure())
/usr/local/www/services_dnsmasq.php (services_dhcpleases_configure())
/usr/local/www/system_advanced_admin.php (services_dhcpleases_configure())
/usr/local/www/system_general.php (services_dhcpleases_configure())

We've commented all these references and there wasn't any other errors or problems with the DHCP process and the leases registration.

![captura de tela de 2016-09-16 08-37-34](https://cloud.githubusercontent.com/assets/5739310/18631763/44d5ff8a-7e4a-11e6-9ed8-281a91aa0e25.png)

![captura de tela de 2016-09-16 08-51-10](https://cloud.githubusercontent.com/assets/5739310/18631764/44d6118c-7e4a-11e6-9a24-dd4c7a88996e.png)

**Comment by fichtner** [comment]
I'll check and add this to 16.7.4, thanks!

**Comment by fichtner** [comment]
No files in 16.7.3 have system_dhcpleases_configure() anymore, what version are you running? Direct paste from the dashboard version info would help the most. :)

**Comment by fichtner** [comment]
I haven't seen any crash reports since two stable versions, are you sure you're not running the development version 17.1.a? It had a few spots that weren't perfect for a while, but the whole DNS rework was merged to 16.7.2 without issues: https://github.com/opnsense/changelog/blob/master/doc/16.7.3#L36

**Comment by fichtner** [comment]
No crash reports in 16.7.4 either. Please upgrade to the latest version to fix this :)
