### ISSUE TITLE
Nano Image a little to large for certain SD cards

### ISSUE THREAD

**Issue by neffs** [opnsense/core#1195]
I ordered a 4 GB pSLC SD Card from PC Engines for my APU2: http://www.pcengines.ch/sd4b.htm

Although its sold as 4GB its only almost 4GB. It is only 3.980.394.496 bytes, while the nano image is 3.999.997.952 bytes. (~20 MB difference)
Could the image be built a little bit smaller? It would help a lot!

Thanks!

**Comment by fichtner** [comment]
FreeBSD's NanoBSD code is already trying to be conservative with the size of "4 GB", but apparently not enough :)

We're planning to revamp the Nano bits to use as little space as possible (under 1 GB) and use growfs to adjust to the physically available size after the first boot. That's how FreeBSD's RPI images work at the moment.

I don't have an ETA on this, but it's in the roadmap for 17.1. If you're looking for a custom nano fit to install on these cards at the moment let me know.

**Comment by fichtner** [comment]
Fixed for 17.1. Semi-official backports for 16.7 here:

https://pkg.opnsense.org/snapshots/OPNsense-16.7-OpenSSL-nano-amd64.img.bz2
https://pkg.opnsense.org/snapshots/OPNsense-16.7-OpenSSL-nano-i386.img.bz2
