### ISSUE TITLE
RADVD will not start when the RA interface is a VIP

### ISSUE THREAD

**Issue by syserr0r** [opnsense/core#1196]
Works as normal when the RA interface is set to 'LAN'

**Comment by syserr0r** [comment]
Using the VIP /var/etc/radvd.conf looks like this:
```
# Automatically Generated, do not edit
# Generated for DHCPv6 Server lan_vip6
interface  {
        AdvSendAdvert on;
        MinRtrAdvInterval 200;
        MaxRtrAdvInterval 600;
        AdvLinkMTU 1280;
        AdvDefaultPreference high;
        AdvManagedFlag on;
        AdvOtherConfigFlag on;
        ...
```

Using LAN it looks like this:
```
# Automatically Generated, do not edit
# Generated for DHCPv6 Server lan
interface em1 {
        AdvSendAdvert on;
        MinRtrAdvInterval 200;
        MaxRtrAdvInterval 600;
        AdvLinkMTU 1500;
        AdvDefaultPreference high;
        AdvManagedFlag on;
        AdvOtherConfigFlag on;
        ...
```

Running radvd produces a syntax error for line 3 (lack of interface) when using the VIP config

**Comment by AdSchellevis** [comment]
hi Anthony, can you try https://github.com/opnsense/core/commit/607d8eccd0c0d05b6a60f5a67edc8af89dba9abb ?

`opnsense-patch 607d8ec
`

There where quite some inconsistencies in the code, I've restructured the function to make it more logical and generated some configs on my test vm, which look good.

**Comment by syserr0r** [comment]
Appears to work (in that the `radvd` service does not show as dead) but I can't do much more checking than this at the moment.

**Comment by syserr0r** [comment]
Config looks correct `/var/etc/radvd.conf`:
```
# Automatically Generated, do not edit
#Generated for DHCPv6 Server lan_vip6
interface em1 {
	AdvSendAdvert on;
	MinRtrAdvInterval 200;
	MaxRtrAdvInterval 600;
	AdvLinkMTU 1500;
	AdvDefaultPreference high;
	AdvManagedFlag on;
	AdvOtherConfigFlag on;
	...
```

**Comment by AdSchellevis** [comment]
@syserr0r can we close this one for now? you can always reopen if needed.

**Comment by syserr0r** [comment]
Yes, I am happy this patch fixes the issue.

**Comment by syserr0r** [comment]
Following IPv6 problems, setting this back to the 'LAN' interface (instead of the VIP on the interface) causes an invalid config to be generated (the file contains only: `# Automatically Generated, do not edit`)

**Comment by AdSchellevis** [comment]
@syserr0r can you test https://github.com/opnsense/core/commit/089a3f07d6bf6f1ed6a8f9c2e8505ad445d5f93a ? I missed the text 'interface' when none/default is selected....

**Comment by fichtner** [comment]
@syserr0r what's the status here? have had this on -devel for a while and would feel better about an "ok" to get this into the next release. thanks!

**Comment by syserr0r** [comment]
I have had to disable IPv6 on the site that was affected by this due to packet loss over IPv6 (and being unable to identify the source of the problem).

After applying 089a3f0 it did write a valid config so I think this is fixed.

**Comment by fichtner** [comment]
Thanks, everything ported to 16.7.9. :)
