### ISSUE TITLE
Multiple Captive Portal(s) with VLAN support

### ISSUE THREAD

**Issue by jstrebel** [opnsense/core#120]
Hi, I am not sure if already in OPNsense.
It would be very useful to add VLAN support with multiple Captive Portal instances.
I see the following scenarios in a hotels quite often.
One physical interface:
- VLAN x serve Mobile Credit Card readers and Ordering devices. They usually connect to a WPA2 SSID an mapped to the VLAN X
- VLAN xy for Guest Goup 1 (reason this guest group has certain i.e application restrictions filters)
- VLAN xyz for Guest Goup 2 (this guest group has another filter set or privileges)

**Comment by fichtner** [comment]
The setup is a little tricky, but it is supported by default:

o add VLAN(s)
o add Interface that uses VLAN
o Enable and setup Interface
o Create a captive portal instance
o Enable captive portal instance on Interface
