### ISSUE TITLE
rc.sshd DSA host key

### ISSUE THREAD

**Issue by kevemueller** [opnsense/core#1200]
rc.sshd does no longer generate a dsa host key, but OpenSSH still defaults to 4 different HostKeys when not specified otherwise. rc.sshd does not specify HostKeys, hence sshd still looks for ssh_host_dsa_key.
To reproduce:
Factory reset (which deletes an existing ssh_host_dsa_key)
sshd -T | grep hostkey 
=> 4 default host keys are listed and an error message is displayed, that ssh_host_dsa_key cannot be loaded.

Either put back generation of ssh_host_dsa_key or explicitely set the 3 supported HostKeys when generating sshd_config in rc.sshd.

**Comment by AdSchellevis** [comment]
@kevemueller Thanks, your right, we missed a spot there. I will include the supported hostkeys in the config generation.

**Comment by fichtner** [comment]
Hi all,

@kevemueller I don't agree with this, as I really don't know what the issue here is. SSH works, even after reset, I see no errors for sshd -T on a 16.7.4 system. Can you please elaborate?

Setting host keys explicitly does not deprecate them, it disables them completely which is not what we want. :(


Cheers,
Franco

**Comment by fichtner** [comment]
(stupid github closed this issue via a git revert)

**Comment by L1ghtn1ng** [comment]
I say we remove DSA support as in the not to distant future SSH will be dropping DSA support

**Comment by fichtner** [comment]
it *is* removed, but the old DSA key keeps working for as long as it's not reset ;)

**Comment by L1ghtn1ng** [comment]
Oh okay

**Comment by kevemueller** [comment]
The problem is reproduceable. Install OpnSense from CD, upgrade via UI, reboot, perform a factory reset (reboots).
You will end up with no /usr/local/etc/ssh/ssh_host_dsa_key and sshd -T still looking for it.
The error line is not only produced by sshd -T, but also in /var/log/system.log at every new ssh connection.

I am agnostic about DSA, but if you want to remove it you should also remove it from /usr/local/etc/ssh/sshd_config. The patch above does  exactly that, by specifically enlisting valid HostKeys, so sshd does not revert to the default list, which still includes dsa host key.

I agree that sshd continues operating, but getting rid of   
`sshd[...]: error: Could not load host key: /usr/local/etc/ssh/ssh_host_dsa_key`
in system.log is IMO more than a cosmetic change.

**Comment by fichtner** [comment]
Alright, fine, I just needed to know where the error was :)

I've added a new commit that generates the keys before writing the config, so we can pick up the available files from the file system including the deprecated ones.


Cheers,
Franco

**Comment by fichtner** [comment]
I found another bug with factory reset: the keys are not properly deleted and pulled back into the new system. I expect this to go into 16.7.x after one round in opnsense-devel, so 16.7.7.

The whole file has practically been rewritten... better safe than sorry.

**Comment by fichtner** [comment]
Merging all changes in 16.7.8. Extra caution taken. :)
