### ISSUE TITLE
IPSec Status is not shown directly

### ISSUE THREAD

**Issue by andreasvel** [opnsense/core#1201]
After a while the IPSec Status is not shown correctly. Neither on the dashboard then on the status page
The Tunnel itself seems to work normally.

after restarting the whole ipsec service the Status is shown correctly

**Comment by AdSchellevis** [comment]
@andreasvel if you have new information, append new findings to the existing issue https://github.com/opnsense/core/issues/634 instead of opening a new issue again, like https://github.com/opnsense/core/issues/777
