### ISSUE TITLE
Notification chooser?

### ISSUE THREAD

**Issue by GrayGhost93** [opnsense/core#1203]
E-Mail-Notification is possible and works for example for a new IP-assignment, but it would be nice to have a possibility to configure also other notifications to get the as a direct mail or a mail once a day with some information like logwatch. Is there something like that which I havn't discovered so far?

Thanks allready

**Comment by AdSchellevis** [comment]
@GrayGhost93 its certainly a good idea to have a solid notification system in place at some point, unfortunately the current code is quite old and unmaintained. If we can find the time, we might look into something which integrates better for a future release. A plugin for syslog using patterns to match messages is something that comes to mind, but will certainly not make before our 17.7 release.

**Comment by GrayGhost93** [comment]
Okay, thanks for the quick reply. I'm happy to hear that and many thanks to you for developing such a nice project!

**Comment by sjorge** [comment]
Was looking for a list of things generate notification to see if it can disable/enable stuff. I ended up here.

Would indeed be nice to have. e.g. on boot, shutdown, vpn connections,...

**Comment by Woi** [comment]
OPNsense 17.1.5 comes with the monit plugin. I just started to test it, but maybe we can add additional checks to get the desired behaviour?
