### ISSUE TITLE
%any Identifier for Pre-Shared Key incorrectly generated for ipsec.secrets file

### ISSUE THREAD

**Issue by abel408** [opnsense/core#1205]
When I try to input "%any" into the OPNsense GUI (VPN -> IPsec -> Pre-Shared Secret), it gives an error about an invalid character. 

There is currently a message that says "PSK for any user can be set by using an identifier of any/ANY" which, to me, is unclear. Are we supposed to use the identifier any, ANY, or any/ANY? None of these choices work anyway.

To get around this, I used the identifier "0.0.0.0"

**Comment by AdSchellevis** [comment]
@abel408 0.0.0.0 will do the same according to the docs, it looks like the any tag isn't parsed at all. I will fix the code to comply with the documentation here.
