### ISSUE TITLE
Add run_rc_script to the rc file

### ISSUE THREAD

**Issue by ali-reza-zareian** [opnsense/core#1207]
Hi
I want to run a simple script at boot time.it's not a service.what should i do ?(I dont want to edit rc file.)
I think it's good to add **run_rc_script** method to the **rc** file.

**Comment by fichtner** [comment]
I'm not exactly sure what you're trying to run (package script or a user-written script), but I think rc.syshook is what you're looking for. A brief description is here:

https://forum.opnsense.org/index.php?topic=3312.msg11175#msg11175

Will this work for you?

**Comment by AdSchellevis** [comment]
The docs also contain our options on this subject https://docs.opnsense.org/development/backend/autorun.html

**Comment by ali-reza-zareian** [comment]
Thats great!
