### ISSUE TITLE
IPSEC Mobile Client Option "Save Xauth Password" not working

### ISSUE THREAD

**Issue by abel408** [opnsense/core#1209]
The "Save Xauth Password" to allow clients the ability to save passwords is not working. I believe the 28673 option in /usr/local/etc/strongswan.conf needs to be set to 1 instead of yes.

**Comment by AdSchellevis** [comment]
@abel408 there isn't a lot of documentation about this property, but I think your right. can you test https://github.com/opnsense/core/commit/8459b38f1119e3a97aafaf75692ed2f044b6cc32 ?

Easiest option to patch (from a console):
`opnsense-patch 8459b38`

**Comment by abel408** [comment]
Sorry for the late response. The patch seems to work great! Thanks

**Comment by AdSchellevis** [comment]
@abel408 thanks for reporting back!
