### ISSUE TITLE
Feature: Add primary6 support to dhcp ddns updates

### ISSUE THREAD

**Issue by kevemueller** [opnsense/core#1210]
The DHCP DDNS form (services_dhcp.php as well as services_dhcpv6.php) allow specifying a IPv4 as the address of the primary domain name server to which the name update is sent.
This field does not accept IPv6 addresses.

Request: Add another field that allows specifying a IPv6 address which is then templated out using the primary6 option into dhcp.conf.

At least one of IPv4 / IPv6 must be set. It is allowed to have both set at the same time.
Specifying an IPv6 address can make sense for DHCPv4 as well, e.g. when the PDNS can be easier reached over IPv6 than over IPv4 (tunnel scenarios).

**Comment by AdSchellevis** [comment]
timeout due to inactivity
