### ISSUE TITLE
Feature: Add IPv6 dynamic reverse DNS update

### ISSUE THREAD

**Issue by kevemueller** [opnsense/core#1211]
A DHCPv4 DDNS option templates out the forward zone as well as the reverse zone (in-addr.arpa) for updating.
The DHCPv6 DDNS option only templates the forward zone, which means that PTR records are not added to DNS.

Feature request: Add the corresponding ip6.arpa reverse zones to the dhcpv6.conf, so IPv6 PTRs are also updated.

**Comment by AdSchellevis** [comment]
timeout due to inactivity
