### ISSUE TITLE
Feature: Allow unbound to listen on port 53 when dnsmasq is enabled

### ISSUE THREAD

**Issue by mbrgm** [opnsense/core#1213]
Currently, it is not possible to have unbound listen on port 53, while dnsmasq is enabled -- even, if dnsmasq is configured to listen on a different port.

However, some users might want to use unbound as the primary DNS resolver but forward queries in a specific zone to an authorative DNS server for that zone. In my pre-opnsense setup, I used unbound+nsd, but I would like to completely migrate this to unbound+dnsmasq under opnsense. 

With the current implementation, this is not possible. So I propose to remove the [check for port 53](https://github.com/opnsense/core/blob/86996d7bf74d7eadcd0879d8edb5aa3d7f807b32/src/www/services_dnsmasq.php#L70) and only check if unbound and dnsmasq are not set to listen on the same port instead. If people agree about that, I'd create a PR implementing the change.

**Comment by fichtner** [comment]
Hi Marius,

I agree, though more code needs to be adapted as it's assumed that dnsmasq always takes precedence over unbound when it's enabled.

I can offer code review for eventual inclusion in 17.1... how does that sound?


Cheers,
Franco

**Comment by mbrgm** [comment]
I'm not as familiar with the architecture of OPNSense, so I don't know yet which parts of the code would have to be adapted. But I'll try to get an overview, send a PR and then you can comment on the diff and point me to the missing parts.

**Comment by fichtner** [comment]
@mbrgm sounds good :)

**Comment by fabianfrz** [comment]
@fichtner because plug ins use ports as well I think the best way to do that is having a function is_port_in_use($number, $application = null), which can find all used ports because plugins can register them self.

The function should return 
false if not found 
false if $application == the calling configuration page
true i we have a match

**Comment by AdSchellevis** [comment]
https://github.com/opnsense/core/commit/d938708963b7cfdba958b244627f46149d1ee45b not a perfect solution, but in my opinion doesn't make the current situation any worse then it was.

I don't expect all services will register used ports any time soon (we should probably check netstat in that case to know for sure which services are running), and this dns option seems to popup from time to time.

Feel free to revert or close the issue :)

**Comment by mbrgm** [comment]
I have to admit that I may have to move DNS away from OPNsense anyway (due to additional requirements). So I don't think that I will put a serious amount of time into this anymore. Until then I'll give @AdSchellevis implementation a try, once it's available. Closing this, but feel free to reopen if you want to.
