### ISSUE TITLE
Feature Request from the forum: IPSec roadwarrior with Windows >= 7

### ISSUE THREAD

**Issue by fabianfrz** [opnsense/core#1214]
See https://forum.opnsense.org/index.php?topic=3338.0;topicseen

Forum: **16.7** Production Series

Note: As far as I can remember there was a commit from @AdSchellevis but it has been reverted because it was not tested.

**Comment by AdSchellevis** [comment]
@fabianfrz the forum request is something different, that's the reason why I ask people to add issues in here themselves, this gives us an owner of the issue and one clear description of what the user expects. To be honest, it doesn't take the time of the world to create a GitHub account and log an issue..... (probably way less then it takes to solve the issue)
