### ISSUE TITLE
openldap-sasl-server missing overlays

### ISSUE THREAD

**Issue by andreas-p** [opnsense/core#1215]
Apparently, all overlays are missing, with the exception of syncprov which is statically linked.
Interestingly, all slapo-* manual pages are present.

**Comment by AdSchellevis** [comment]
@andreas-p openldap isn't a core dependency, please report your issue in the proper repository including the steps performed and whether your issue is new with or was introduced in a specific release. 
Incomplete issues will be closed without further notice.

**Comment by fichtner** [comment]
Well, we have the defaults: https://github.com/freebsd/freebsd-ports/blob/master/net/openldap24-server/Makefile#L79

Which overlays are we talking about then?

**Comment by andreas-p** [comment]
I'm specifically missing the memberof and refint overlays right now. But why not have all overlays present as module?

**Comment by fichtner** [comment]
I'll add both of them.

Reasons are simple:
* keep to standards as much as possible, even though they tend get in the way
* make sure compile time and repository sizes do not increase drastically
* adding something must be reviewed and maintained afterwards, which may cause hogging ressources
* people should ask for what they want so everyone can help steer the project

**Comment by andreas-p** [comment]
Thanks. I wonder why overlay modules aren't included in FreeBSD at all, checked 10.0-11.0. Will report there as well.

**Comment by fichtner** [comment]
Will be in 16.7.7's packages.

https://github.com/opnsense/tools/commit/7fafe0a7fff22dad000358f3ad04007c3dc61d0c
