### ISSUE TITLE
Traffic shaper sync broken

### ISSUE THREAD

**Issue by tkald** [opnsense/core#1217]
When I add/change pipes on primary firewall, pipes/rules are eventually (at least 15+min) synced to secondary. However those changes on secondary are not enforced.
Under "Firewall: Traffic Shaper: Status" are still pipes missing or old values are shown.

No problems with other sync items - firewall rules, aliases, carp ip-s ...

OPNsense 16.7.6-amd64

**Comment by AdSchellevis** [comment]
@tkald you should be able to restart that service using the "System-> High Availability -> Status" page, but it looks like this one isn't registered. We should fix that.

The sync process restarts some services, which is kind of a leftover from the old code, restarting all services on the backup on every "Apply" isn't a very good idea and quite time consuming (there's no way of knowing which services to restart).

**Comment by tkald** [comment]
Should be enough on secondary just to set new pipes to ipfw, no reload needed.
Since there is separate chekbox on ha sync  settings page for traffic shaper, I imagine there must be separate code to sync traffic shaper shanges. I'm not coder though :)

And it kinda defies point of having setting syned if I need to reload/restart things manually...

**Comment by tkald** [comment]
Applied those 2 patches, no change in traffic shaper sync behaviour.
Seems like shaping rules are syned to the secondary node when I change some firewall (pf) rules. 
Which at this point is irrelevant to shaper.

When finally shapring rules make it to the secondary, still no shaping enforcement.
So when carp failover should happen, those rules are not loaded.

**Comment by AdSchellevis** [comment]
you did reload the shaper using the status page? ("System-> High Availability -> Status") 
The apply won't happen automatically.

**Comment by tkald** [comment]
Yes, I did push that reload - did not work.

I still think, if it's possible to reload fw rules on secondary node without touching anything there, should be possible with shaping rules too :)

**Comment by AdSchellevis** [comment]
It probably didn't sync the changes (only legacy code does that), I've changed the action to force a sync first in https://github.com/opnsense/core/commit/7c82fe62023ae572951fda2747d10d22507da529 .

**Comment by tkald** [comment]
Yap, now it works.
Still, why can't this all happen with one "apply" press under Firewall - Traffic Shaper ? :)

BTW, is there a way to reload whole "clean" php code from latest version? Reinstalling opnsense package doesn't seem to revert code.

**Comment by fichtner** [comment]
@tkald reapplying the patch reverts it, terrible UX, but it's a feature ;)

Not sure why it wouldn't revert to the correct behaviour. Which patches did you apply?

**Comment by AdSchellevis** [comment]
@tkald we're not going to trigger a sync there, because you don't know for sure what to restart (and you don't want to restart all services on every apply).... it's not only a traffic shaper thing, the same behaviour should count for all services. 
This method is easy to embed in local administration procedures.

**Comment by tkald** [comment]
@fichtner I think I applied one or two patches here twice which broke my UI. Replaced corresponding files and all ok now.

**Comment by tkald** [comment]
@AdSchellevis ok I see. 
I know there's no easy fix but in the future we could know, what to restart exactly :)
