### ISSUE TITLE
system: allow users to select their own languages

### ISSUE THREAD

**Issue by fichtner** [opnsense/core#1218]
- ~~The password changer page needs to be adopted as a sort of profile settings page where languages can be set as well (another issue is pending to show QR codes there, also user-related as well as potentially OpenVPN information/configs)~~
- ~~at least show user settings on user edit page~~
- ~~The language for new users should be the admin language.~~
- ~~The MVC must be able to change the language according to the user as well~~
- ~~Ideally we do not want to change language settings twice, but the legacy page probably does that now because of its structure~~

**Comment by fichtner** [comment]
@kekek2 maybe can help with this as well? language selection for users currently under lobby: password, it is not patched into MVC yet :)

**Comment by kekek2** [comment]
I'll do it.

**Comment by fichtner** [comment]
All done, thanks for your help @kekek2 !
