### ISSUE TITLE
Feature: Custom IDS/IPS Rules

### ISSUE THREAD

**Issue by tpcr** [opnsense/core#1219]
I would like to see the ability to use rules that I wrote for specific alerts

**Comment by AdSchellevis** [comment]
@tpcr you can just put your rule file in /usr/local/etc/suricata/rules/ and "download & update rules" should do the rest.
I tested it on my end by adding a rule in a newly created file "/usr/local/etc/suricata/rules/mytest.rules", works like a charm.

**Comment by tpcr** [comment]
I do not see a file manager in OPNsense and I do not know my way around Linux

**Comment by AdSchellevis** [comment]
For security reasons, there is no file manager in OPNsense. You have to use ssh or a physical console to manually edit files.

**Comment by fabianfrz** [comment]
Hi @tpcr, wou will see the rules in its tab after you do what @AdSchellevis described.

**Comment by tpcr** [comment]
I guess OPNsense is for Linux users only.

**Comment by fabianfrz** [comment]
@tpcr no, it is not. If you are using Windows, you can use WinSCP to copy the files, but you will have to enable SSH on your OPNsense machine.
