### ISSUE TITLE
OPNsense plugin config should be covered by XMLRPC Sync

### ISSUE THREAD

**Issue by fraenki** [opnsense/core#1224]
Currently plugin configurations will not be synced to a second node in HA configuration. As a result these services will not be available when the primary node goes down. (*Or the service will be running but without the desired configuration.)

Sidenote: A potential workaround is to maintain the configuration on each OPNsense node manually. Unfortunately this is not a good idea for more complex configurations, because this is error prone.

**Comment by AdSchellevis** [comment]
for reference, at the moment the xmlrpc sync config is static code... I have done some work on restructuring the backend code https://github.com/opnsense/core/blob/master/src/etc/rc.filter_synchronize#L278-L296, but we should fix the hasync page first and make the options pluggable.
https://github.com/opnsense/core/blob/master/src/www/system_hasync.php

One side note, partial xmlrpc sync won't always be safe (when entries are referenced by uuid).

**Comment by pcmediapear** [comment]
+1, that would be great

**Comment by AdSchellevis** [comment]
@fraenki This should do the trick, example in https://github.com/opnsense/plugins/commit/542dd642d3395e55295e4caa339e6bf492a3f389

**Comment by pcmediapear** [comment]
hi @AdSchellevis, should this work also for haproxy plugin?

**Comment by fichtner** [comment]
@pcmediapear haproxy still needs a fix for this, likely not this year anymore

cc @fraenki
