### ISSUE TITLE
Filter reload failures on "secondary"

### ISSUE THREAD

**Issue by tkald** [opnsense/core#1225]
In HA setup, changing firewall rules on primary router will cause errors on secondary router. So rules on secondary will not be applied right away.

Here's log:

`Oct 18 15:05:06    kernel: pid 8887 (php), uid 0: exited on signal 11 (core dumped)
Oct 18 15:05:06     configd.py: [3882b70b-bab0-4e9f-a8ec-1272d6408855] returned exit status -11
Oct 18 15:04:37     opnsense: /usr/local/etc/rc.filter_configure_sync: Could not find IPv6 gateway for interface(wan).
Oct 18 15:04:11     configd[38328]: /xmlrpc.php: ROUTING: setting IPv4 default route to x.x.x.x
Oct 18 15:04:11     configd[38328]: Timeout (120) executing : filter reload
Oct 18 15:03:15     configd.py: [3b54afcb-2447-4ed4-a7e5-386dfd2bb980] request osfp
Oct 18 15:03:05     configd.py: unable to sendback response [Error (-11) ] for [filter][reload][None] {f2ab9af3-be96-4ab4-8184-88a6bfa1413d}, message was Traceback (most recent call last): File "/usr/local/opnsense/service/modules/processhandler.py", line 202, in run self.connection.sendall('%s\n' % result) File "/usr/local/lib/python2.7/socket.py", line 228, in meth return getattr(self._sock,name)(*args) error: [Errno 32] Broken pipe
Oct 18 15:03:05     kernel: pid 76196 (php), uid 0: exited on signal 11 (core dumped)
Oct 18 15:03:05     configd.py: [f2ab9af3-be96-4ab4-8184-88a6bfa1413d] returned exit status -11`

---

OPNsense 16.7.6-amd64

**Comment by AdSchellevis** [comment]
doesn't look familiar, might be hardware/driver related. can you try to run the following in a console on the backup?

`/usr/local/etc/rc.filter_configure_sync
`

**Comment by tkald** [comment]
No errors for that command.
Firewall rules sync seems to work fine again. Strange...

**Comment by fichtner** [comment]
closing unless new things happened?
