### ISSUE TITLE
Feature request: GUI WPAD configuration

### ISSUE THREAD

**Issue by EquisTango** [opnsense/core#1229]
It would be great to have an option to enable opnsense Squid proxy to be automatically discovered via PAC/WPAD.

This is: a) adding a "wpad" entry to the DNS server / forwarder; b) hosting a "wpad.dat" file accessible via HTTP; and c) adding the correct MIME type for the wpad.dat file (application/x-ns-proxy-autoconfig).

Useful PAC information site: http://findproxyforurl.com

**Comment by sachaw** [comment]
+1, would be very useful, hope to see it soon.

**Comment by AdSchellevis** [comment]
timeout due to inactivity
