### ISSUE TITLE
nat: IPv6 selection is not honoured leading to a broken ruleset

### ISSUE THREAD

**Issue by fabianfrz** [opnsense/core#1232]
rule in GUI and configuration:
![bildschirmfoto am 2016-10-21 um 10 42 54](https://cloud.githubusercontent.com/assets/3713914/19592360/9bab8290-977b-11e6-83b0-d80d399f2210.png)

generated rule:
nat on vmx6 proto tcp from *IPv4-Net* to ::1 port 443 -> (vmx6)

**Comment by fichtner** [comment]
Something is wrong when the interface is not WAN, but on WAN it works as expected.

**Comment by fichtner** [comment]
NAT reflection wasn't able to generate IPv6 entries.... it wasn't the actual NAT rule ;)

**Comment by fichtner** [comment]
@fabianfrz if you can please try it...

     # opnsense-patch 661445d

**Comment by fabianfrz** [comment]
Works :+1:

**Comment by fabianfrz** [comment]
having this in rules.debug but no errors in the GUI
```
# source not found :             on $LAN  inet6 pass   in   quick  label "USER_RULE: Default allow LAN IPv6 to any rule"
# destination not found :           proto { tcp udp }    on $LAN  inet6 pass   in   quick   from any  label "USER_RULE"
# source not found :           proto tcp    on $LAN  inet6 pass   in   quick  label "USER_RULE: NAT test"
```

**Comment by fabianfrz** [comment]
when using an ip address, the 3rd rule works

**Comment by fabianfrz** [comment]
any: same as ip address used

**Comment by fichtner** [comment]
@fabianfrz you're confusing me, I just added the IPv6 branch...
