### ISSUE TITLE
api error appears twice in a row

### ISSUE THREAD

**Issue by fichtner** [opnsense/core#1234]
I guess the first one should be removed...

<img width="656" alt="screen shot 2016-10-22 at 11 34 09 am" src="https://cloud.githubusercontent.com/assets/1915288/19618481/be7ddc20-984b-11e6-8c19-f293c70e4321.png">

<img width="621" alt="screen shot 2016-10-22 at 11 34 15 am" src="https://cloud.githubusercontent.com/assets/1915288/19618482/c040a6be-984b-11e6-95e1-491d0d9db357.png">

**Comment by AdSchellevis** [comment]
yes, I forgot to remove that one it seems.....

**Comment by fichtner** [comment]
I really like the new error reporting :)
