### ISSUE TITLE
Feature request: Change Ports for Captive Portal

### ISSUE THREAD

**Issue by PitchBendStretch** [opnsense/core#1237]
Hello guys :)

i made the experience that the port the user is going to be redirected to depends on the zone number the captive portal uses. For example if i would create a "test" Captive Portal using the zone number 0, the user would get redirected to the landing page using port 8000.
Since i got alot of co-workers asking me to change the port to something completely different, for example "8079" i now have the wish to do so but did not found a way to do it.

I think it would be a good idea to provide the possibility to change the port the captive portal is using after enabling the little "advanced" slider. Don't you think? :-)

Have a nice day and keep it safe :)

Best regards

**Comment by AdSchellevis** [comment]
the port numbers are calculated in the ruleset and used in the templates as well, I honestly don't see the big gain in changing them.... more prune to errors (users will at some point overlap zones leading to all sorts of strange behaviour).

If there's a very good business reason why we should add the feature, I'm happy to keep the issue open for a while..... but it really has to be a good reason.

**Comment by PitchBendStretch** [comment]
Thats why i thought it should be hidden behind the "advanced" slider. 
In this case i think there will be no way for you to add the feature just because my supervisor wants it to be different, because of company internal errors regarding the blocking rules of some ports above 8000.
It's okay. You can close the issue then.
