### ISSUE TITLE
templates: need pattern to revoke file on delete and associated command

### ISSUE THREAD

**Issue by fichtner** [opnsense/core#1238]
## Problem

Currently, +TARGETS only specifies local file and target name.
## Motivation

We also need to add a revoke pattern which can be called via configd like "reload".

The idea is to have this facility called on +PRE_DEINSTALL to safely remove the files as they could leave partial configuration in the system (web-proxy-sso injects a squid_ option via a separate file).

Then we can also weave an unconditional +POST_INSTALL into the files to inject the new templates.
## Syntax

```
test.file:/usr/local/test
```

Backwards-compatible, expands to:

```
test.file:/usr/local/test:/usr/local/test
```

Which means the actual file is removed. We also need glob pattern support:

```
test.file:/usr/local/test:/usr/local/test*
```

If the behaviour is undesired, the behaviour could be disabled using an empty pattern:

```
test.file:/usr/local/test:
```

Note delete should only work on files and ignore directories and only files with a leading "/" should be removed.

**Comment by AdSchellevis** [comment]
@fichtner sounds like a good idea, only issue is backwards compatibility with calculated filenames https://github.com/opnsense/core/blob/master/src/opnsense/service/templates/OPNsense/Sample/%2BTARGETS#L1 we should skip those for removal.

**Comment by fichtner** [comment]
I'm expecting to fix up these with the glob replacements in the code itself, no need to be that backwards-compatible, or?

**Comment by AdSchellevis** [comment]
my idea too, skip them when found and no handling was specified...

**Comment by fichtner** [comment]
ok, sounds good :)

**Comment by fichtner** [comment]
BTW, I reviewed the template code and it has an operational weakness with missing recursive behaviour, intermixed with wildcard matching:
* Wildcards are prefix matches, it doesn't work to do "template reload 'OPNsense\*Auth'" and get the correct result
* Regenerating a container layout like OPNsense/Sample/s1 and OPNsense/Sample/s2 does not invoke the subcontainers when doing "template reload OPNsense.Sample"

Long story short, a full per component is probably better and should recurse on available submatches. This way, invoking "template reload OPNsense" (*) or "template reload" (empty) would do the same thing as "template reload '*'" now

(*) except this only regenerates our changes, strictly not other vendor templates so "template reload" (empty) is probably the best thing.

If you are ok with this I can do the coding.

**Comment by AdSchellevis** [comment]
I'm not sure I follow your story completely, but I can review your changes for you.

**Comment by fichtner** [comment]
As per our discussion: Template patterns "*" expands to all, "" does nothing. Full matching directories trigger als subdirs as well. Otherwise we don't need the wildcard character anymore.
