### ISSUE TITLE
Factory reset via serial Interface does not reset

### ISSUE THREAD

**Issue by jstrebel** [opnsense/core#124]
Executing a factory reset trough the Serial Interface does not reset the Box to the default Values.
The interface addresses remain to the previously configured values. The captive portal is still shown as active and the Voucher support as well active. 
I have also tried to do a reset trough the GUI. Same result.

**Comment by fichtner** [comment]
I did not see this behaviour, but I made sure the config cannot possibly linger in the file system by rebooting directly. It would try to back up vouchers probably refreshing the whole config in the process. Now also kills dhcpleases and rrd data. Cheers for the report.

**Comment by jstrebel** [comment]
Franco, I go to Diagnostics:Factory defaults and click "Yes" and wait until the box comes up again.
Below is the end of the Startup log.


Starting configd.
Launching the init system... done.
Initializing.................. done.
Starting device manager (devd)...done.
Loading configuration...done.
Updating configuration...done.
Setting up extended sysctls...done.
amdtemp0: <AMD CPU On-Die Thermal Sensors> on hostb4
Setting timezone...done.
Configuring loopback interface...done.
Starting syslog...done.
Starting Secure Shell Services...done.
Setting up polling defaults...done.
Setting up interfaces microcode...done.
Configuring loopback interface...done.
Creating wireless clone interfaces...done.
Configuring LAGG interfaces...done.
Configuring VLAN interfaces...done.
Configuring QinQ interfaces...done.
Configuring WAN interface...done.
Configuring LAN interface...done.
Configuring GAST interface...done.
Syncing OpenVPN settings...done.
Configuring firewall......done.
Starting PFLOG...done.
Setting up gateway monitors...done.
Synchronizing user settings...done.
Starting webConfigurator...done.
Configuring CRON...done.
Starting DNS forwarder...done.
Starting NTP time client...done.
Starting DHCP service...done.
Starting DHCPv6 service...done.
Configuring firewall......done.
Starting captive portal(buero)... done
Enabling voucher support... done
Generating RRD graphs...^[[B^[[Bdone.
Starting UPnP service... done.
Starting syslog...done.
Starting CRON... done.

*** Welcome to OPNsense 15.1.8.3-c6240d38f (amd64) on OPNsense ***

 WAN (re1)       -> v4/DHCP4: 192.168.10.237/24
 LAN (re0)       -> v4: 192.168.233.1/24
 GAST (re2)      -> v4: 192.168.11.1/24

FreeBSD/amd64 (OPNsense.teamstrebel.ch) (ttyu0)

HERE is the LOG:
Apr 3 00:22:34 	opnsense: /diag_defaults.php: Successful login for user 'admin' from: 192.168.10.200
Apr 3 00:20:54 	getty[99167]: open /dev/ttyv3: No such file or directory
Apr 3 00:20:54 	getty[99167]: open /dev/ttyv3: No such file or directory
Apr 3 00:20:54 	getty[98652]: open /dev/ttyv0: No such file or directory
Apr 3 00:20:54 	getty[98652]: open /dev/ttyv0: No such file or directory
Apr 3 00:20:54 	getty[99538]: open /dev/ttyv6: No such file or directory
Apr 3 00:20:54 	getty[99538]: open /dev/ttyv6: No such file or directory
Apr 3 00:20:54 	getty[98992]: open /dev/ttyv2: No such file or directory
Apr 3 00:20:54 	getty[98992]: open /dev/ttyv2: No such file or directory
Apr 3 00:20:54 	getty[99198]: open /dev/ttyv4: No such file or directory
Apr 3 00:20:54 	getty[99198]: open /dev/ttyv4: No such file or directory
Apr 3 00:20:54 	getty[99358]: open /dev/ttyv5: No such file or directory
Apr 3 00:20:54 	getty[99358]: open /dev/ttyv5: No such file or directory
Apr 3 00:20:54 	getty[98707]: open /dev/ttyv1: No such file or directory
Apr 3 00:20:54 	getty[98707]: open /dev/ttyv1: No such file or directory
Apr 3 00:20:54 	sshlockout[99980]: sshlockout/webConfigurator v3.0 starting up
Apr 3 00:20:54 	getty[99557]: open /dev/ttyv7: No such file or directory
Apr 3 00:20:54 	getty[99557]: open /dev/ttyv7: No such file or directory
Apr 3 00:20:53 	kernel: done.
Apr 3 00:20:53 	kernel: done.
Apr 3 00:20:53 	opnsense: /usr/local/etc/rc.bootup: miniupnpd: Starting service on interface: lan
Apr 3 00:20:53 	opnsense: /usr/local/etc/rc.bootup: Creating rrd update script
Apr 3 00:20:47 	rtsold[15659]: <sendpacket> sendmsg on re1: Operation not permitted
Apr 3 00:20:43 	rtsold[15659]: <sendpacket> sendmsg on re1: Operation not permitted
Apr 3 00:20:42 	kernel: done
Apr 3 00:20:42 	lighttpd[63300]: (log.c.164) server started
Apr 3 00:20:41 	kernel: ipfw2 (+ipv6) initialized, divert loadable, nat loadable, default to accept, logging disabled
Apr 3 00:20:41 	kernel: .....done.
Apr 3 00:20:41 	configd.py: Updating all dyndns
Apr 3 00:20:41 	kernel: done.
Apr 3 00:20:40 	opnsense: /usr/local/etc/rc.bootup: ROUTING: setting default route to 192.168.10.1
Apr 3 00:20:40 	kernel: done.
Apr 3 00:20:40 	opnsense: /usr/local/etc/rc.bootup: ROUTING: remove current default route to 192.168.10.1
Apr 3 00:20:40 	kernel: done.
Apr 3 00:20:40 	lighttpd[49851]: (log.c.164) server started
Apr 3 00:20:39 	rtsold[15659]: <sendpacket> sendmsg on re1: Operation not permitted
Apr 3 00:20:39 	kernel: done.
Apr 3 00:20:39 	opnsense: /usr/local/etc/rc.bootup: The command '/usr/sbin/pw groupadd test1 -g -M 2000 2>&1' returned exit code '65', the output was 'pw: gid `0' has already been allocated'
Apr 3 00:20:39 	kernel: done.
Apr 3 00:20:36 	kernel: pflog0: promiscuous mode enabled
Apr 3 00:20:36 	opnsense: /usr/local/etc/rc.bootup: Resyncing OpenVPN instances.
Apr 3 00:20:36 	opnsense: /usr/local/etc/rc.bootup: Accept router advertisements on interface re1
Apr 3 00:20:35 	configd.py: Linkup starting re1
Apr 3 00:20:35 	devd: Executing '/usr/local/opnsense/service/configd_ctl.py 'interface linkup start re1''
Apr 3 00:20:35 	kernel: re1: link state changed to UP
Apr 3 00:20:33 	configd.py: Linkup stopping re1
Apr 3 00:20:33 	devd: Executing '/usr/local/opnsense/service/configd_ctl.py 'interface linkup stop re1''
Apr 3 00:20:33 	kernel: re1: link state changed to DOWN
Apr 3 00:20:33 	kernel: done.
Apr 3 00:20:33 	opnsense: /usr/local/etc/rc.bootup: Failed to clone interface ath0 with error code 1, output ifconfig: SIOCIFCREATE2: Device not configured
Apr 3 00:20:33 	kernel: done.
Apr 3 00:20:33 	opnsense: /usr/local/etc/rc.bootup: Cloning new wireless interface ath0_wlan1
Apr 3 00:20:33 	kernel: done.
Apr 3 00:20:33 	sshlockout[5932]: sshlockout/webConfigurator v3.0 starting up
Apr 3 00:20:33 	sshd[5738]: Server listening on 0.0.0.0 port 22.
Apr 3 00:20:33 	sshd[5738]: Server listening on :: port 22.
Apr 3 00:20:33 	kernel: amdtemp0: <AMD CPU On-Die Thermal Sensors> on hostb4
Apr 3 00:20:33 	kernel: Trying to mount root from ufs:/dev/ada0s1a [rw]...
Apr 3 00:20:33 	kernel: Timecounter "TSC" frequency 1000021981 Hz quality 800
Apr 3 00:20:33 	kernel: SMP: AP CPU #1 Launched!
Apr 3 00:20:33 	kernel: da0: quirks=0x2<NO_6_BYTE>
Apr 3 00:20:33 	kernel: da0: Attempt to query device size failed: NOT READY, Medium not present
Apr 3 00:20:33 	kernel: da0: 40.000MB/s transfers
Apr 3 00:20:33 	kernel: da0: Serial Number 058F63666485
Apr 3 00:20:33 	kernel: da0: <Multiple Card Reader 1.00> Removable Direct Access SCSI-4 device
Apr 3 00:20:33 	kernel: da0 at umass-sim0 bus 0 scbus6 target 0 lun 0
Apr 3 00:20:33 	kernel: ada0: Previously was known as ad4
Apr 3 00:20:33 	kernel: ada0: 15258MB (31248704 512 byte sectors: 16H 63S/T 16383C)
Apr 3 00:20:33 	kernel: ada0: Command Queueing enabled
Apr 3 00:20:33 	kernel: ada0: 300.000MB/s transfers (SATA 2.x, UDMA6, PIO 8192bytes)
Apr 3 00:20:33 	kernel: ada0: Serial Number YTAK140600316
Apr 3 00:20:33 	kernel: ada0: <SuperSSpeed S238 16G V4629N> ATA-7 SATA 2.x device
Apr 3 00:20:33 	kernel: ada0 at ahcich0 bus 0 scbus0 target 0 lun 0
Apr 3 00:20:33 	kernel: umass0:6:0:-1: Attached to scbus6
Apr 3 00:20:33 	kernel: umass0: SCSI over Bulk-Only; quirks = 0x4001
Apr 3 00:20:33 	kernel: umass0: <Generic Flash Card ReaderWriter, class 0/0, rev 2.01/1.00, addr 2> on usbus6
Apr 3 00:20:33 	kernel: ugen6.2: <Generic> at usbus6
Apr 3 00:20:33 	kernel: uhub3: 5 ports with 5 removable, self powered
Apr 3 00:20:33 	kernel: uhub1: 5 ports with 5 removable, self powered
Apr 3 00:20:33 	kernel: uhub6: 4 ports with 4 removable, self powered
Apr 3 00:20:33 	kernel: uhub5: 4 ports with 4 removable, self powered
Apr 3 00:20:33 	kernel: uhub2: 5 ports with 5 removable, self powered
Apr 3 00:20:33 	kernel: uhub0: 5 ports with 5 removable, self powered
Apr 3 00:20:33 	kernel: uhub4: 2 ports with 2 removable, self powered
Apr 3 00:20:33 	kernel: uhub6: <ATI EHCI root HUB, class 9/0, rev 2.00/1.00, addr 1> on usbus6
Apr 3 00:20:33 	kernel: ugen6.1: <ATI> at usbus6
Apr 3 00:20:33 	kernel: uhub5: <ATI OHCI root HUB, class 9/0, rev 1.00/1.00, addr 1> on usbus5
Apr 3 00:20:33 	kernel: ugen5.1: <ATI> at usbus5
Apr 3 00:20:33 	kernel: uhub4: <ATI OHCI root HUB, class 9/0, rev 1.00/1.00, addr 1> on usbus4
Apr 3 00:20:33 	kernel: ugen4.1: <ATI> at usbus4
Apr 3 00:20:33 	kernel: usbus6: 480Mbps High Speed USB v2.0
Apr 3 00:20:33 	kernel: usbus5: 12Mbps Full Speed USB v1.0
Apr 3 00:20:33 	kernel: usbus4: 12Mbps Full Speed USB v1.0
Apr 3 00:20:33 	kernel: uhub3: <ATI EHCI root HUB, class 9/0, rev 2.00/1.00, addr 1> on usbus3
Apr 3 00:20:33 	kernel: ugen3.1: <ATI> at usbus3
Apr 3 00:20:33 	kernel: uhub2: <ATI OHCI root HUB, class 9/0, rev 1.00/1.00, addr 1> on usbus2
Apr 3 00:20:33 	kernel: ugen2.1: <ATI> at usbus2
Apr 3 00:20:33 	kernel: uhub1: <ATI EHCI root HUB, class 9/0, rev 2.00/1.00, addr 1> on usbus1
Apr 3 00:20:33 	kernel: ugen1.1: <ATI> at usbus1
Apr 3 00:20:33 	kernel: uhub0: <ATI OHCI root HUB, class 9/0, rev 1.00/1.00, addr 1> on usbus0
Apr 3 00:20:33 	kernel: ugen0.1: <ATI> at usbus0
Apr 3 00:20:33 	kernel: usbus3: 480Mbps High Speed USB v2.0
Apr 3 00:20:33 	kernel: usbus2: 12Mbps Full Speed USB v1.0
Apr 3 00:20:33 	kernel: usbus1: 480Mbps High Speed USB v2.0
Apr 3 00:20:33 	kernel: IPsec: Initialized Security Association Processing.
Apr 3 00:20:33 	kernel: Timecounters tick every 1.000 msec
Apr 3 00:20:33 	kernel: usbus0: 12Mbps Full Speed USB v1.0
Apr 3 00:20:33 	kernel: random: unblocking device.
Apr 3 00:20:33 	kernel: acpi_throttle0: <ACPI CPU Throttling> on cpu0
Apr 3 00:20:33 	kernel: uart1: <16550 or compatible> at port 0x2f8-0x2ff irq 3 on isa0
Apr 3 00:20:33 	kernel: uart0: console (115200,n,8,1)
Apr 3 00:20:33 	kernel: uart0: <16550 or compatible> at port 0x3f8-0x3ff irq 4 flags 0x10 on isa0
Apr 3 00:20:33 	kernel: ppc0: cannot reserve I/O port range
Apr 3 00:20:33 	kernel: orm0: <ISA Option ROM> at iomem 0xee000-0xeffff on isa0
Apr 3 00:20:33 	kernel: acpi_button0: <Power Button> on acpi0
Apr 3 00:20:33 	kernel: usbus6 on ehci2
Apr 3 00:20:33 	kernel: usbus6: EHCI version 1.0
Apr 3 00:20:33 	kernel: ehci2: <AMD SB7x0/SB8x0/SB9x0 USB 2.0 controller> mem 0xfeb04600-0xfeb046ff at device 22.2 on pci0
Apr 3 00:20:33 	kernel: usbus5 on ohci3
Apr 3 00:20:33 	kernel: ohci3: <AMD SB7x0/SB8x0/SB9x0 USB controller> mem 0xfeb03000-0xfeb03fff at device 22.0 on pci0
Apr 3 00:20:33 	kernel: pci4: <ACPI PCI bus> on pcib4
Apr 3 00:20:33 	kernel: pcib4: <ACPI PCI-PCI bridge> at device 21.0 on pci0
Apr 3 00:20:33 	kernel: usbus4 on ohci2
Apr 3 00:20:33 	kernel: ohci2: <AMD SB7x0/SB8x0/SB9x0 USB controller> mem 0xfeb02000-0xfeb02fff at device 20.5 on pci0
Apr 3 00:20:33 	kernel: device_attach: pcib4 attach returned 6
Apr 3 00:20:33 	kernel: pci0: couldn't attach pci bus
Apr 3 00:20:33 	kernel: pcib4: failed to allocate initial prefetch window: 0-0xfffff
Apr 3 00:20:33 	kernel: pcib4: failed to allocate initial memory window: 0-0xfffff
Apr 3 00:20:33 	kernel: pcib4: <ACPI PCI-PCI bridge> at device 20.4 on pci0
Apr 3 00:20:33 	kernel: isa0: <ISA bus> on isab0
Apr 3 00:20:33 	kernel: isab0: <PCI-ISA bridge> at device 20.3 on pci0
Apr 3 00:20:33 	kernel: ata1: <ATA channel> at channel 1 on atapci0
Apr 3 00:20:33 	kernel: ata0: <ATA channel> at channel 0 on atapci0
Apr 3 00:20:33 	kernel: atapci0: <ATI IXP700/800 UDMA133 controller> port 0x1f0-0x1f7,0x3f6,0x170-0x177,0x376,0x4010-0x401f at device 20.1 on pci0
Apr 3 00:20:33 	kernel: usbus3 on ehci1
Apr 3 00:20:33 	kernel: usbus3: EHCI version 1.0
Apr 3 00:20:33 	kernel: ehci1: <AMD SB7x0/SB8x0/SB9x0 USB 2.0 controller> mem 0xfeb04500-0xfeb045ff at device 19.2 on pci0
Apr 3 00:20:33 	kernel: usbus2 on ohci1
Apr 3 00:20:33 	kernel: ohci1: <AMD SB7x0/SB8x0/SB9x0 USB controller> mem 0xfeb01000-0xfeb01fff at device 19.0 on pci0
Apr 3 00:20:33 	kernel: usbus1 on ehci0
Apr 3 00:20:33 	kernel: usbus1: EHCI version 1.0
Apr 3 00:20:33 	kernel: ehci0: <AMD SB7x0/SB8x0/SB9x0 USB 2.0 controller> mem 0xfeb04400-0xfeb044ff at device 18.2 on pci0
Apr 3 00:20:33 	kernel: usbus0 on ohci0
Apr 3 00:20:33 	kernel: ohci0: <AMD SB7x0/SB8x0/SB9x0 USB controller> mem 0xfeb00000-0xfeb00fff at device 18.0 on pci0
Apr 3 00:20:33 	kernel: ahcich3: <AHCI channel> at channel 3 on ahci0
Apr 3 00:20:33 	kernel: ahcich2: <AHCI channel> at channel 2 on ahci0
Apr 3 00:20:33 	kernel: ahcich1: <AHCI channel> at channel 1 on ahci0
Apr 3 00:20:33 	kernel: ahcich0: <AHCI channel> at channel 0 on ahci0
Apr 3 00:20:33 	kernel: ahci0: AHCI v1.20 with 4 6Gbps ports, Port Multiplier supported
Apr 3 00:20:33 	kernel: ahci0: <AMD SB7x0/SB8x0/SB9x0 AHCI SATA controller> port 0x4020-0x4027,0x4040-0x4043,0x4028-0x402f,0x4044-0x4047,0x4000-0x400f mem 0xfeb04000-0xfeb043ff at device 17.0 on pci0
Apr 3 00:20:33 	kernel: re2: Ethernet address: 00:0d:b9:33:16:02
Apr 3 00:20:33 	kernel: rgephy2: none, 10baseT, 10baseT-FDX, 10baseT-FDX-flow, 100baseTX, 100baseTX-FDX, 100baseTX-FDX-flow, 1000baseT, 1000baseT-master, 1000baseT-FDX, 1000baseT-FDX-master, 1000baseT-FDX-flow, 1000baseT-FDX-flow-master, auto, auto-flow
Apr 3 00:20:33 	kernel: rgephy2: <RTL8169S/8110S/8211 1000BASE-T media interface> PHY 1 on miibus2
Apr 3 00:20:33 	kernel: miibus2: <MII bus> on re2
Apr 3 00:20:33 	kernel: re2: MAC rev. 0x00200000
Apr 3 00:20:33 	kernel: re2: Chip rev. 0x2c000000
Apr 3 00:20:33 	kernel: re2: ASPM disabled
Apr 3 00:20:33 	kernel: re2: Using 1 MSI-X message
Apr 3 00:20:33 	kernel: re2: <RealTek 8168/8111 B/C/CP/D/DP/E/F/G PCIe Gigabit Ethernet> port 0x3000-0x30ff mem 0xfea00000-0xfea00fff,0xfe900000-0xfe903fff at device 0.0 on pci3
Apr 3 00:20:33 	kernel: pci3: <ACPI PCI bus> on pcib3
Apr 3 00:20:33 	kernel: pcib3: <ACPI PCI-PCI bridge> at device 6.0 on pci0
Apr 3 00:20:33 	kernel: re1: Ethernet address: 00:0d:b9:33:16:01
Apr 3 00:20:33 	kernel: rgephy1: none, 10baseT, 10baseT-FDX, 10baseT-FDX-flow, 100baseTX, 100baseTX-FDX, 100baseTX-FDX-flow, 1000baseT, 1000baseT-master, 1000baseT-FDX, 1000baseT-FDX-master, 1000baseT-FDX-flow, 1000baseT-FDX-flow-master, auto, auto-flow
Apr 3 00:20:33 	kernel: rgephy1: <RTL8169S/8110S/8211 1000BASE-T media interface> PHY 1 on miibus1
Apr 3 00:20:33 	kernel: miibus1: <MII bus> on re1
Apr 3 00:20:33 	kernel: re1: MAC rev. 0x00200000
Apr 3 00:20:33 	kernel: re1: Chip rev. 0x2c000000
Apr 3 00:20:33 	kernel: re1: ASPM disabled
Apr 3 00:20:33 	kernel: re1: Using 1 MSI-X message
Apr 3 00:20:33 	kernel: re1: <RealTek 8168/8111 B/C/CP/D/DP/E/F/G PCIe Gigabit Ethernet> port 0x2000-0x20ff mem 0xfe800000-0xfe800fff,0xfe700000-0xfe703fff at device 0.0 on pci2
Apr 3 00:20:33 	kernel: pci2: <ACPI PCI bus> on pcib2
Apr 3 00:20:33 	kernel: pcib2: <ACPI PCI-PCI bridge> at device 5.0 on pci0
Apr 3 00:20:33 	kernel: re0: Ethernet address: 00:0d:b9:33:16:00
Apr 3 00:20:33 	kernel: rgephy0: none, 10baseT, 10baseT-FDX, 10baseT-FDX-flow, 100baseTX, 100baseTX-FDX, 100baseTX-FDX-flow, 1000baseT, 1000baseT-master, 1000baseT-FDX, 1000baseT-FDX-master, 1000baseT-FDX-flow, 1000baseT-FDX-flow-master, auto, auto-flow
Apr 3 00:20:33 	kernel: rgephy0: <RTL8169S/8110S/8211 1000BASE-T media interface> PHY 1 on miibus0
Apr 3 00:20:33 	kernel: miibus0: <MII bus> on re0
Apr 3 00:20:33 	kernel: re0: MAC rev. 0x00200000
Apr 3 00:20:33 	kernel: re0: Chip rev. 0x2c000000
Apr 3 00:20:33 	kernel: re0: ASPM disabled
Apr 3 00:20:33 	kernel: re0: Using 1 MSI-X message
Apr 3 00:20:33 	kernel: re0: <RealTek 8168/8111 B/C/CP/D/DP/E/F/G PCIe Gigabit Ethernet> port 0x1000-0x10ff mem 0xfe600000-0xfe600fff,0xfe500000-0xfe503fff at device 0.0 on pci1
Apr 3 00:20:33 	kernel: pci1: <ACPI PCI bus> on pcib1
Apr 3 00:20:33 	kernel: pcib1: <ACPI PCI-PCI bridge> at device 4.0 on pci0
Apr 3 00:20:33 	kernel: pci0: <ACPI PCI bus> on pcib0
Apr 3 00:20:33 	kernel: pcib0: <ACPI Host-PCI bridge> port 0xcf8-0xcff on acpi0
Apr 3 00:20:33 	kernel: Event timer "HPET1" frequency 14318180 Hz quality 450
Apr 3 00:20:33 	kernel: Event timer "HPET" frequency 14318180 Hz quality 550
Apr 3 00:20:33 	kernel: Timecounter "HPET" frequency 14318180 Hz quality 950
Apr 3 00:20:33 	kernel: hpet0: <High Precision Event Timer> iomem 0xfed00000-0xfed003ff on acpi0
Apr 3 00:20:33 	kernel: acpi_timer0: <32-bit timer at 3.579545MHz> port 0x808-0x80b on acpi0
Apr 3 00:20:33 	kernel: Timecounter "ACPI-fast" frequency 3579545 Hz quality 900
Apr 3 00:20:33 	kernel: Event timer "i8254" frequency 1193182 Hz quality 100
Apr 3 00:20:33 	kernel: Timecounter "i8254" frequency 1193182 Hz quality 0
Apr 3 00:20:33 	kernel: attimer0: <AT timer> port 0x40-0x43 irq 0 on acpi0
Apr 3 00:20:33 	kernel: Event timer "RTC" frequency 32768 Hz quality 0
Apr 3 00:20:33 	kernel: atrtc0: <AT realtime clock> port 0x70-0x71 irq 8 on acpi0
Apr 3 00:20:33 	kernel: cpu1: <ACPI CPU> on acpi0
Apr 3 00:20:33 	kernel: cpu0: <ACPI CPU> on acpi0
Apr 3 00:20:33 	kernel: acpi0: Power Button (fixed)
Apr 3 00:20:33 	kernel: acpi0: <CORE COREBOOT> on motherboard
Apr 3 00:20:33 	kernel: padlock0: No ACE support.
Apr 3 00:20:33 	kernel: cryptosoft0: <software crypto> on motherboard
Apr 3 00:20:33 	kernel: module_register_init: MOD_LOAD (vesa, 0xffffffff80f618f0, 0) error 19
Apr 3 00:20:33 	kernel: kbd0 at kbdmux0
Apr 3 00:20:33 	kernel: random: <Software, Yarrow> initialized
Apr 3 00:20:33 	kernel: wlan: mac acl policy registered
Apr 3 00:20:33 	kernel: module_register_init: MOD_LOAD (ipw_monitor_fw, 0xffffffff805dcc70, 0) error 1
Apr 3 00:20:33 	kernel: ipw_monitor: If you agree with the license, set legal.intel_ipw.license_ack=1 in /boot/loader.conf.
Apr 3 00:20:33 	kernel: ipw_monitor: You need to read the LICENSE file in /usr/share/doc/legal/intel_ipw/.
Apr 3 00:20:33 	kernel: module_register_init: MOD_LOAD (ipw_ibss_fw, 0xffffffff805dcbc0, 0) error 1
Apr 3 00:20:33 	kernel: ipw_ibss: If you agree with the license, set legal.intel_ipw.license_ack=1 in /boot/loader.conf.
Apr 3 00:20:33 	kernel: ipw_ibss: You need to read the LICENSE file in /usr/share/doc/legal/intel_ipw/.
Apr 3 00:20:33 	kernel: module_register_init: MOD_LOAD (ipw_bss_fw, 0xffffffff805dcb10, 0) error 1
Apr 3 00:20:33 	kernel: ipw_bss: If you agree with the license, set legal.intel_ipw.license_ack=1 in /boot/loader.conf.
Apr 3 00:20:33 	kernel: ipw_bss: You need to read the LICENSE file in /usr/share/doc/legal/intel_ipw/.
Apr 3 00:20:33 	kernel: ioapic0 <Version 2.1> irqs 0-23 on motherboard
Apr 3 00:20:33 	kernel: cpu1 (AP): APIC ID: 1
Apr 3 00:20:33 	kernel: cpu0 (BSP): APIC ID: 0
Apr 3 00:20:33 	kernel: FreeBSD/SMP: 1 package(s) x 2 core(s)
Apr 3 00:20:33 	kernel: FreeBSD/SMP: Multiprocessor System Detected: 2 CPUs
Apr 3 00:20:33 	kernel: ACPI APIC Table: <CORE COREBOOT>
Apr 3 00:20:33 	kernel: Event timer "LAPIC" quality 400
Apr 3 00:20:33 	kernel: avail memory = 2010673152 (1917 MB)
Apr 3 00:20:33 	kernel: real memory = 2115428352 (2017 MB)
Apr 3 00:20:33 	kernel: TSC: P-state invariant, performance statistics
Apr 3 00:20:33 	kernel: AMD Features2=0x35ff<LAHF,CMP,SVM,ExtAPIC,CR8,ABM,SSE4A,MAS,Prefetch,IBS,SKINIT,WDT>
Apr 3 00:20:33 	kernel: AMD Features=0x2e500800<SYSCALL,NX,MMX+,FFXSR,Page1GB,RDTSCP,LM>
Apr 3 00:20:33 	kernel: Features2=0x802209<SSE3,MON,SSSE3,CX16,POPCNT>
Apr 3 00:20:33 	kernel: Features=0x178bfbff<FPU,VME,DE,PSE,TSC,MSR,PAE,MCE,CX8,APIC,SEP,MTRR,PGE,MCA,CMOV,PAT,PSE36,CLFLUSH,MMX,FXSR,SSE,SSE2,HTT>
Apr 3 00:20:33 	kernel: Origin = "AuthenticAMD" Id = 0x500f20 Family = 0x14 Model = 0x2 Stepping = 0
Apr 3 00:20:33 	kernel: CPU: AMD G-T40E Processor (1000.02-MHz K8-class CPU)
Apr 3 00:20:33 	kernel: FreeBSD clang version 3.4.1 (tags/RELEASE_34/dot1-final 208032) 20140512
Apr 3 00:20:33 	kernel: root@sensey64:/usr/obj/usr/src/sys/SMP amd64
Apr 3 00:20:33 	kernel: FreeBSD 10.1-RELEASE-p8 #0 2822f85(master): Sat Mar 21 03:09:56 CET 2015
Apr 3 00:20:33 	kernel: FreeBSD is a registered trademark of The FreeBSD Foundation.
Apr 3 00:20:33 	kernel: The Regents of the University of California. All rights reserved.
Apr 3 00:20:33 	kernel: Copyright (c) 1979, 1980, 1983, 1986, 1988, 1989, 1991, 1992, 1993, 1994
Apr 3 00:20:33 	kernel: Copyright (c) 1992-2014 The FreeBSD Project.
Apr 3 00:20:33 	syslogd: kernel boot file is /boot/kernel/kernel
Apr 3 00:19:39 	syslogd: exiting on signal 15
Apr 3 00:19:39 	shutdown: reboot by root:
Apr 3 00:19:39 	shutdown: reboot by root:
Apr 3 00:19:33 	configd.py: Syncing firewall
Apr 3 00:18:54 	opnsense: /index.php: Successful login for user 'admin' from: 192.168.10.200

**Comment by fichtner** [comment]
@jstrebel the code used by the GUI is the same as previously fixed for the console; just tested and it looks good too. Small follow ups have been committed to polish the code some more.
