### ISSUE TITLE
proxy: allow to use proxy transparent and not transparent at the same time

### ISSUE THREAD

**Issue by fabianfrz** [opnsense/core#1243]
normal mode: to allow authentication (makes rules for users possible)
transparent: for all clients which have no proxy configured

required for different networks with different security settings

**Comment by fichtner** [comment]
I don't get this... even the transparent proxy must be able to run in non-proxy mode to serve some content to clients...

**Comment by fabianfrz** [comment]
It is about having one port running in transparent mode for all hosts (ad blocking, virus filtering, block some file downloads) and one for special clients which can authenticate so other ACLs can be applied (depending on users, so they can download this stuff or access social media etc.).

**Comment by fichtner** [comment]
well, I got that part, but what's special about it, e.g. what doesn't work already in our GUI?

**Comment by fabianfrz** [comment]
Isn't there only a checkbox to run in transparent mode?

**Comment by fichtner** [comment]
the checkbox is for enabling the loopback listening. you can still select each required interface along with it. in fact, it is even required by transparent mode to have a real listening address on the interface. ;)

https://forum.opnsense.org/index.php?topic=2425

Close?

**Comment by fabianfrz** [comment]
Yes, close it ;)
