### ISSUE TITLE
mvc: Macro 'base_dialog_header' is already defined on PHP 7.0

### ISSUE THREAD

**Issue by fichtner** [opnsense/core#1245]
Suboptimal workaround introduced for a problem exclusive to PHP 7.0 is https://github.com/opnsense/core/commit/8f194f4bb5b5af4e634d1ce3082894d20da801bd .

Maybe there is some underlying bug that doesn't visibly trigger on PHP 5.6 or we just need to find a better way to keep the former readability intact.

Thanks!

**Comment by fichtner** [comment]
This resurfaced now, we should just avoid the macro here...

https://forum.opnsense.org/index.php?topic=4860.0
https://github.com/opnsense/core/commit/6d7d2dc

**Comment by fichtner** [comment]
or alternatively make it a full template to be included

**Comment by AdSchellevis** [comment]
new phalcon version?

**Comment by fichtner** [comment]
could be, although we should really go with the flow here, php 7.0 scoping and phalcon will likely not get better when nobody cares as it would seem ;(

**Comment by fichtner** [comment]
I saw this just once while testing a few minutes ago, after that the thing works as normal. I've prodded the 3.0.4 phalcon release for over two weeks....

**Comment by fichtner** [comment]
Sorry for pinging this all the time, small valuable addition: the reporter said this happened for him on a fresh 17.1 install as well today, so it may be circumstantial race condition we could not possibly fix or report upstream

**Comment by AdSchellevis** [comment]
really a bummer, the volt templates seem to get more broken on every release.... scope issues, macro issues, .... 
Let's revert and hope it won't get worse...

**Comment by fichtner** [comment]
Agree. I'll get confirmation from the reporter, then try to fix this a bit more pretty

**Comment by fichtner** [comment]
created a ticket just for reference... https://github.com/phalcon/cphalcon/issues/12744

**Comment by AdSchellevis** [comment]
thanks!

**Comment by fichtner** [comment]
Ok, that's the one https://github.com/phalcon/cphalcon/issues/12648

**Comment by sergeyklay** [comment]
Fixed https://github.com/phalcon/cphalcon/issues/12782

**Comment by fichtner** [comment]
@sergeyklay  many thanks! 👍
