### ISSUE TITLE
Remove deleted vlan from Interfaces: Assignments

### ISSUE THREAD

**Issue by ali-reza-zareian** [opnsense/core#1247]
hi
If vlan on page Interfaces: Other Types: VLAN is erased ,it should be erase from Interfaces: Assignments automatically.
Now i delete valn from Interfaces: Other Types: VLAN and the connected interfaces remain empty in Interfaces: Assignments page..

**Comment by AdSchellevis** [comment]
Ideally it should be the other way around, when used refuse to delete.
Unfortunately there are more areas in the system suffering from the same issue.... there are no referential constraints which can easily be enforced.

**Comment by ali-reza-zareian** [comment]
yes.but i think interfaces_vlan.php should be modified.
Line 57 :vlan_inuse($a_vlans[$id]**['vlanif']**)

**Comment by AdSchellevis** [comment]
yes, when in use, refuse to drop.

**Comment by AdSchellevis** [comment]
@ali-reza-zareian I'm not sure why you closed the issue, adding the validation is certainly a valid question. feel free to reopen

**Comment by ali-reza-zareian** [comment]
hi
this is my last suggestion for interfaces_vlan.php.
`function vlan_inuse_descr($vlan_intf,&$descr) {
    global $config;
    foreach ($config['interfaces'] as $if => $intf) {
        if ($intf['if'] == $vlan_intf) {
            $descr=$intf['descr'];
            return true;
        }
    }
    return false;
}`

this function return the name of interface that should be deleted as $descr argument.Now we can use it in error message.So end user can understand which interface should be deleted first.

**Comment by AdSchellevis** [comment]
@ali-reza-zareian thank you for your feedback, I've implemented things a bit differently leading to the same result (fix check and communicate interface name to the user)
