### ISSUE TITLE
dns forwarder/resolver: provide regdhcp domain name overrides

### ISSUE THREAD

**Issue by pcmediapear** [opnsense/core#1250]
by configuring multiple dhcp ranges on multiple network interfaces all clients getting domain configured in system/settings/general and not domain specified in services/dhcp/server/domain name

version 16.7.7-amd64

**Comment by fichtner** [comment]
Can you provide /var/dhcpd/etc/dhcpd.conf, and a specific subnet range with the expected outcome + observed outcome via email to project AT opnsense DOT org ? Thanks!

**Comment by fichtner** [comment]
Received info, thanks. It looks like this is related: #624

**Comment by fichtner** [comment]
@pcmediapear Can you try this patch?

# opnsense-patch ce6a55655

**Comment by pcmediapear** [comment]
yesterday i tried the patch but after restarting opnsense devices not getting dhcp leases, maybe i have wrong applied patch
in these days i does not have enough time for testing so i will let you know next week

**Comment by fichtner** [comment]
@pcmediapear I'm keeping these changes on the development branch, and appear to work from here. just let me know when you can confirm/deny and we go forward from there. thanks so far!

**Comment by pcmediapear** [comment]
have tried patch again but without sucess so i have examined it more deeply in more networks and with more devices
domain name option is send by dhcp and it was also without patch
it looks like issue is by writing fqdn to /etc/hosts from where it is through dns forwarder resolved in network
fqdn is writen with domain configured by hostname in system/settings/general and not with domain configured in services/dhcp/server/domain name as it should

side note:
sometimes i saw duplicate entry of "# dhcpleases automatically entered" part in /etc/hosts
it is possible that it was because i had for testing configured 60s dhcp lease

**Comment by fichtner** [comment]
@pcmediapear Is this solely about dhcp-registered static mapping showing the wrong domain name?

I've reverted the patch. If the above question is answered with yes I know what to do. Thanks in advance.

**Comment by pcmediapear** [comment]
it affects normal leases and also static leases
everything with comment "# dynamic entry from dhcpd.leases" in /etc/hosts

**Comment by fichtner** [comment]
Ok, for dynamic leases I have to unfortunately draw the line: something that has never worked with other than the standard domain in both forwarder and resolver. It's also documented that way looking at the help text of the settings in the respective dns service settings.

Static mapping can be created with a click on the lease page, overriding the domain from there is also possible or the interface's DHCP domain is automatically picked up if set.

I have fixed this for the upcoming 16.7.10, but can't provide a backport as this includes multiple cleanups over various files that requires more testing. Tomorrows opnsense-devel package in 16.7.9 will have the fixes, though if you want to try them run:

    # opnsense-update -t opnsense-devel

Or go back to the release with

    # opnsense-update -t opnsense


Cheers,
Franco

**Comment by fichtner** [comment]
I'm keeping this open as a feature request: after studying the code the only thing we will provide is a special override in the DNS Forwarder/Resolver to use a specific domain name instead of the default name. For multiple dynamic domains the system will fail to operate properly.

**Comment by pcmediapear** [comment]
many thanks, you are providing great support here...

**Comment by fichtner** [comment]
@pcmediapear ok, all done. optimistic for a swift merge towards 16.7.10 one or two weeks away. cheers! :)

**Comment by pcmediapear** [comment]
hello @fichtner, just for sure, should now dns domain name override work also for dynamic entrys or just for static mappings?

**Comment by fichtner** [comment]
the domain name override is only for dhcp lease mappings, not the static mapping as they will choose the proper domain name. the help text should be clear on this.

**Comment by pcmediapear** [comment]
ok, then "domain name" dhcp server option with using dns forwarder is still not working correctly (16.7.11) :-(
in /var/etc/dnsmasq-hosts are all "# dynamic entry from dhcpd.leases" entrys written with domain name from system
if "domain name" option is defined with dhcp static mapping it is written as it should
additional note: dns forwarder host overrides are working without any issues

**Comment by fichtner** [comment]
did you specify the domain name on the dns forwarder config page?

**Comment by pcmediapear** [comment]
i have multiple separate networks and each should have own dns name so i can not configure domain override on dns forwarder config page

**Comment by fichtner** [comment]
the way dynamic leases work is they read the dhcp leases file, which does *not* contain the domain name. we can provide a best effort and an override, but only the dhcp knows this information and a lot more work must be put into this to work reliably for forwarder/resolver.

static mappings help with this, but I when your network is large and segmented I can see that this will be difficult to manage as well.

everything is documented and tested now thanks to your help. I don't see any leaps forward here anymore without dedicated help as project resources are needed/moved elsewhere.

**Comment by pcmediapear** [comment]
ok now i understand how it works
until now i always used dnsmasq for dhcp and also dns so hostnames was resolvable with right domain
but you are using dhcpd with dnsmasq or unbound so you need detect and create hostnames because it is not done automaticaly from service
what about to match dhcp lease with dhcp range for detecting right domain?
dhcp range should not overlap and should be unique so meybe it can be good source
by searching a solution i saw that by dhcp server can be configured dynamic dns so i will install server with bind and test it this will work for me
thank you for your patience

**Comment by fichtner** [comment]
@pcmediapear generally yes, though the journey is something like:

1. extract the config.xml info into a "config file" for the dhcp lease listener, particularly designing a format that can cope with the complexity of the host name/ domain overrides of the static leases: unbound fixed
2. replace the dhcp lease listener for dnsmasq with the one used by unbound, or at least a new listener which isn't C (the unbound one is python for better flexibility)
3. add the same dhcp lease magic to the dnsmasq listener

Essentially, I want to avoid a feature split for such a similar feature that is currently "torn apart" by different daemons who are supposed to do the same, but cannot be easily maintained. As soon as we add fixes, new users will pressure into a fix for dnsmasq or ask "why is it not the same, this is stupid."

The sane order of execution is therefore something like... (2), (1), (3) ... or (3), (1), whatever e.g. you would offer to test.

I know @AdSchellevis hinted at replacing the lease daemon of dnsmasq, but this could take a few months to materialise, not before 17.1 in any case. Afterwards I could take over to write the remaining things.

What do you think? :)


Cheers,
Franco

**Comment by pcmediapear** [comment]
@fichtner now i have working envirnonment with bind on separate servers which is working (with small issue which i will report)
from my point of view any solution which help me to full administration of dns and dhcp through opnsense GUI from you will help me
so if you prepare some improvments let me know and i can test it

additional info of my environment:
- dhcp is using (before also dns) HA synchronization
- dhcp use failover peer
