### ISSUE TITLE
Concurrent access to config not serialized

### ISSUE THREAD

**Issue by fbrendel** [opnsense/core#1251]
Accessing the config concurrent is not an atomic operation.
The problem occurs in ftp-proxy plugin because jQuerys ajax requests are async by default.
https://github.com/opnsense/plugins/pull/38#discussion_r81970066

**Comment by fichtner** [comment]
Thinking a bit about this: it is serialised, but not locked in a global context.... Each API-Call gets a copy of the full state, then the threads race back and overwrite the state of other states within the model.

A quick fix would be to selectively do synchronous calls, or do a single API command for all of them?

Long-term, I'm a bit unsure: if sub-models are edited, maybe only sub-models should be saved, but it would still be prone to races.

**Comment by fbrendel** [comment]
Yes synchronous calls doesn't solve the problem because they all are in the scope of a single API call.
I'd say locks are the safest method to do it consistently. Maybe for the whole config or selectively for the plugin/sub-model. The tricky part is to handle stale locks because API calls are quite fleeting.

**Comment by AdSchellevis** [comment]
You can only lock the full config at the moment (single file different processes), at the moment only the write itself is locked. For mvc style actions we could consider a lock/release method which you can use in mutable calls, for legacy code this isn't a good idea (will lead to a very sloppy interface). 

So locking would be up to the developer in this case, who should call something like this:

```
set(){
     lock();
     read_model();
     do_calculations(); // may not run long...
     write_model();
     release();
     optional_long_running_additional_actions(); // not in the lock scope
}
```

As far as I see there isn't an option to implement better locking without changing the whole config handling (and getting rid of all the legacy code first).

**Comment by fichtner** [comment]
I'm closing this at is not overly relevant for plugin use.
