### ISSUE TITLE
Cannot Traceroute on 17.1

### ISSUE THREAD

**Issue by KyleSanderson** [opnsense/core#1252]
Any tips as to why I can't traceroute from a client on 17.1? Stock rules, everything permitted. Can't seem to source out any reason for why this would be the case beyond an old bug that was forcefully backed out in 16.x.

**Comment by fichtner** [comment]
sounds like the same fix that was included in 12-CURRENT wasn't applied to 11.0? I'll check...

**Comment by fichtner** [comment]
at least the known commits are all on stock 11.0. how does your output look like?

**Comment by KyleSanderson** [comment]
Microsoft Windows [Version 10.0.14393]
(c) 2016 Microsoft Corporation. All rights reserved.

C:\Users\Kal>ipconfig

Windows IP Configuration


Ethernet adapter Ethernet:

   Media State . . . . . . . . . . . : Media disconnected
   Connection-specific DNS Suffix  . : OPNsense.localdomain

Ethernet adapter vEthernet (External):

   Connection-specific DNS Suffix  . : OPNsense.localdomain
   Link-local IPv6 Address . . . . . : fe80::4c69:3d82:d4a3:2ea1%20
   IPv4 Address. . . . . . . . . . . : 10.24.96.45
   Subnet Mask . . . . . . . . . . . : 255.255.255.0
   Default Gateway . . . . . . . . . : 10.24.96.1

Tunnel adapter isatap.OPNsense.localdomain:

   Media State . . . . . . . . . . . : Media disconnected
   Connection-specific DNS Suffix  . : OPNsense.localdomain

C:\Users\Kal>ping 10.24.96.1

Pinging 10.24.96.1 with 32 bytes of data:
Reply from 10.24.96.1: bytes=32 time<1ms TTL=64
Reply from 10.24.96.1: bytes=32 time<1ms TTL=64

Ping statistics for 10.24.96.1:
    Packets: Sent = 2, Received = 2, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 0ms, Maximum = 0ms, Average = 0ms
Control-C
^C
C:\Users\Kal>tracert -d 8.8.8.8

Tracing route to 8.8.8.8 over a maximum of 30 hops

  1     *        *        *     Request timed out.
  2     *        *     ^C
C:\Users\Kal>

**Comment by fichtner** [comment]
Strange, on 17.1.a, it looks ok from here:

```
$ traceroute 8.8.8.8
traceroute to 8.8.8.8 (8.8.8.8), 64 hops max, 52 byte packets
 1  sensey (10.0.0.1)  5.236 ms  5.741 ms  4.180 ms
 2  easy.box.local (192.168.2.1)  5.229 ms  4.807 ms  5.641 ms
[...]
```

Did 16.7.x behave better in this scenario?

**Comment by KyleSanderson** [comment]
I haven't tried downgrading to 16.7.x yet. Working better then my R7000 with my FQ_Codel backport. Had a couple issues with trunking (like all the ifaces died, until I rebooted the box), and NAT reflection doesn't take effect until Automatic outbound NAT is triggered. Beyond that it seems to largely work.

Linux traceroute works for me, perhaps it's the packet type being dropped?
traceroute to 8.8.8.8 (8.8.8.8), 30 hops max, 60 byte packets
 1  OPNsense.OPNsense.localdomain (10.24.96.1)  0.441 ms  0.384 ms  0.537 ms
 2  10.27.162.1 (10.27.162.1)  2.503 ms  1.760 ms  2.138 ms

**Comment by fichtner** [comment]
Very likely, something like a IP option or so... Can you record a pcap from the windows host and send it to franco AT opnsense DOT org ? thanks!

**Comment by KyleSanderson** [comment]
Can't seem to pcap... plain-text sent.

Looks like the last packet (with the correct ttl) isn't dropped by the gateway. mtr with udp and tcp packets all work; I'm assuming it's because Windows still uses ICMP option 8 (instead of option 0 like everyone else).

**Comment by KyleSanderson** [comment]
16.7.10-amd64 has the same issue.

Steps to reproduce: Run Windows.

**Comment by AdSchellevis** [comment]
timout
