### ISSUE TITLE
GUI Text formatting past border issue on dashboard

### ISSUE THREAD

**Issue by avvidme** [opnsense/core#1254]
Text will be displayed outside of the border on a few windows.   Tried on Safari, Chrome and Firefox.  Both 2 and 3 column modes.

![screen shot 2016-11-12 at 4 00 39 pm](https://cloud.githubusercontent.com/assets/10760278/20240861/7d679c24-a8f1-11e6-99fc-d4a90d7aa7b5.jpg)

**Comment by fichtner** [comment]
duplicates  #1003
