### ISSUE TITLE
GUI Dashboard: Cannot save graph state

### ISSUE THREAD

**Issue by avvidme** [opnsense/core#1255]
When deselecting interfaces (ie: see OPT interfaces on attachment).  No option to save state.  Will always revert when you browse back to page.

![screen shot 2016-11-12 at 4 01 07 pm](https://cloud.githubusercontent.com/assets/10760278/20240880/da6f441c-a8f1-11e6-8607-a2e1a746df3e.jpg)

**Comment by fichtner** [comment]
This is indeed missing since all graphs were merged into one. It's nice to have, but not mission critical as the largest benefit with the formerly available was to save space on the dashboard, which is no longer the case.

**Comment by AdSchellevis** [comment]
timeout due to inactivity
