### ISSUE TITLE
[plugins] need a copy/duplicate function for config items

### ISSUE THREAD

**Issue by fraenki** [opnsense/core#1260]
In (legacy) Firewall->Rules each rule has a "copy rule" button. The button will open an edit dialog and insert the data from the rule that is being copied.

I couldn't figure out how to do something similar for plugins. Especially our HAProxy plugin badly needs this feature, it saves a lot of time when creating complex configurations (or when doing migrations). :)

**Comment by AdSchellevis** [comment]
@fraenki this https://github.com/opnsense/core/commit/cb0d18424971aae6e417801e297d449a11480819 should do the trick, opnsense_bootgrid_plugin.js still needs improvement but there's no rush there (a bit too much code for my taste).

**Comment by fraenki** [comment]
Thanks, @AdSchellevis! I'll try it out.

**Comment by fraenki** [comment]
Tested with HAProxy (frontends, backends, servers and ACLs), seems to work as expected. Thanks again!

**Comment by tapsystem** [comment]
perfect, thanks for rooting my request at the good place
