### ISSUE TITLE
[plugins] sorting of GUI items unpredictable

### ISSUE THREAD

**Issue by fraenki** [opnsense/core#1261]
I've just noticed that the sorting of items in plugins is somewhat unpredictable.

For example, the default sort order of "Backends" in HAProxy looks like this:

![sort_default](https://cloud.githubusercontent.com/assets/909706/20348688/038b71e6-ac07-11e6-9cde-c7851f658c48.png)

You can clearly see that the default sort order is not alphanumeric. I assume that it's sorted by date or internal ID.

When clicking on the "Backend Name" header I'd assume that it would switch to alphanumeric sorting, but it doesn't work:

![sort_by_name](https://cloud.githubusercontent.com/assets/909706/20348727/44656e2e-ac07-11e6-81af-a001c2e49ec2.png)

You can clearly see that there's no change.

Maybe the plugin developer needs to do some adjustements that I'm not aware of? Please advice or point me to an example so I'll be able to fix it for the HAProxy plugin.

**Comment by AdSchellevis** [comment]
@fraenki it looks alphabetically sorted to me, if you click the header again, it should sort reverse (it does so on other usages of the same component).
Just to be sure _ (underscore) has a higher character value then 5 (chr(95) vs chr(53) )

**Comment by fraenki** [comment]
Hi @AdSchellevis, I know it's easy to overlook, but this isn't sorted alphanumerical: b, b, b, b, n, *t*, p. The letter "t" is in the wrong position ;)

**Comment by AdSchellevis** [comment]
Hi @fraenki you're right, I overlooked that one. what happens when you order descending?

**Comment by fraenki** [comment]
I've added some more obvious test data :)

**Ascending:**
![sort_ooops](https://cloud.githubusercontent.com/assets/909706/20385063/35ed721a-acb6-11e6-8f57-1ba38d135c08.png)

**Descending:**
![sort_desc](https://cloud.githubusercontent.com/assets/909706/20385087/4932c7a8-acb6-11e6-9fca-ad58f8902d75.png)

It's actually reversed, but still not alphanumerical.

**Comment by fraenki** [comment]
Here are the entries from config.xml...

```
root@opnsense-test:~ # grep -A3 'backend uuid' /conf/config.xml
        <backend uuid="497f5d29-b1fe-4224-b176-1c0a79a2a1c4">
          <id>57051e93ea8753.59975846</id>
          <enabled>0</enabled>
          <name>backend_1</name>
--
        <backend uuid="c4f81225-382c-45c1-b483-77c977d29da2">
          <id>57051ea77ba751.56655280</id>
          <enabled>0</enabled>
          <name>backend2</name>
--
        <backend uuid="d79c5987-cebd-4a56-9a07-5ed5dab44b62">
          <id>5706481537ae91.88736051</id>
          <enabled>0</enabled>
          <name>backend4</name>
--
        <backend uuid="45ad9963-323b-465b-8e64-30e3c1b20ccf">
          <id>57064df74bcff3.15122874</id>
          <enabled>0</enabled>
          <name>backend5</name>
--
        <backend uuid="3eb12297-02d5-4333-9f09-424c37267b58">
          <id>5713c94e5cc150.43519011</id>
          <enabled>1</enabled>
          <name>testing_backend</name>
--
        <backend uuid="4bb8894e-613e-40ac-a0a3-516e5a731a7e">
          <id>5713f9bc946ee7.70127142</id>
          <enabled>0</enabled>
          <name>prod_www_backend</name>
--
        <backend uuid="a1b1d058-67aa-4b39-9f82-fa791e95fb05">
          <id>582b225092f596.56903199</id>
          <enabled>1</enabled>
          <name>non_sni_backend</name>
--
        <backend uuid="525e0259-7018-4759-afcf-5beeb1d57300">
          <id>582d7c1613b873.43593669</id>
          <enabled>1</enabled>
          <name>zbackend</name>
--
        <backend uuid="593c3d5e-a7ca-4832-8d4c-0f690ed059ad">
          <id>582d7c2893fc31.35392162</id>
          <enabled>1</enabled>
          <name>xbackend</name>
--
        <backend uuid="468f9922-39f5-431f-a816-597b60d6363c">
          <id>582d7c5ad41d18.38165493</id>
          <enabled>1</enabled>
          <name>ybackend</name>

```

**Comment by AdSchellevis** [comment]
@fraenki ok found it, ArrayField->SortedBy aligns text before sorting https://github.com/opnsense/core/commit/1a37f39f687a02c74eb9c714548c24ee5a03d77c . Eventually we probably better add a sortableValue() to the baseFieldType and use that for sorting, this method always delivers a best guess.

**Comment by fraenki** [comment]
Thanks, @AdSchellevis! Tested and works as advertised. :+1:
