### ISSUE TITLE
IDS Download & Update Rules Not Working

### ISSUE THREAD

**Issue by chaserit123** [opnsense/core#1262]
I'm unable to download the rules using the download & update rules button.  It runs for about 1 min and just stops no rules get downloaded.  Any help would be appreciated!

**Comment by L1ghtn1ng** [comment]
What version are you running and have you made sure you have enabled the rules, screenshots and output of the logs would be helpful to see what is happening



On Wed, Nov 16, 2016 at 5:51 PM +0000, "chaserit123" <notifications@github.com<mailto:notifications@github.com>> wrote:


I'm unable to download the rules using the download & update rules button. It runs for about 1 min and just stops no rules get downloaded. Any help would be appreciated!

-

**Comment by chaserit123** [comment]
It almost seems like a DNS issue but Im not 100% sure at this point.
Here is the version info:

OPNsense 16.7.5-amd64
FreeBSD 10.3-RELEASE-p9
OpenSSL 1.0.2j 26 Sep 2016

Screenshots:
![idt_pane](https://cloud.githubusercontent.com/assets/72666/20359749/ca42bec2-abf6-11e6-8ff6-4723a5c70ae6.png)

![logscreenshot](https://cloud.githubusercontent.com/assets/72666/20359757/d189d47c-abf6-11e6-8730-bf1902d4c2ab.png)

**Comment by chaserit123** [comment]
I have confirmed it's a DNS issue I can't ping google at all.  Why would the DNS resolve on every connected client VM but not the firewall?

**Comment by chaserit123** [comment]
![image](https://cloud.githubusercontent.com/assets/72666/20361280/a015b978-abfc-11e6-8946-7274e6ccb5ea.png)

**Comment by L1ghtn1ng** [comment]
Are you using DNS forwarder or resolver?



On Wed, Nov 16, 2016 at 7:00 PM +0000, "chaserit123" <notifications@github.com<mailto:notifications@github.com>> wrote:


[image]<https://cloud.githubusercontent.com/assets/72666/20361280/a015b978-abfc-11e6-8946-7274e6ccb5ea.png>

-

**Comment by chaserit123** [comment]
This doesn't make sense at all. The DNS is setup properly and working everywhere but on the firewall.  I have tried just about everything I can think of no dice.  Here is the DNS logs.

![image](https://cloud.githubusercontent.com/assets/72666/20363321/6aee5d60-ac04-11e6-8ffc-1d2be4263264.png)

**Comment by chaserit123** [comment]
I'm using the DNS forwarder!

**Comment by chaserit123** [comment]
![image](https://cloud.githubusercontent.com/assets/72666/20363345/80e45520-ac04-11e6-85f0-406eddbf133d.png)

**Comment by L1ghtn1ng** [comment]
Try setting up the resolver, if that works then update to the latest release of OPNsense 16.7.8 and see if the forwarder works on the firewall itself then.



On Wed, Nov 16, 2016 at 7:56 PM +0000, "chaserit123" <notifications@github.com<mailto:notifications@github.com>> wrote:


[image]<https://cloud.githubusercontent.com/assets/72666/20363345/80e45520-ac04-11e6-85f0-406eddbf133d.png>

-

**Comment by fichtner** [comment]
timeout / support issue
