### ISSUE TITLE
firmware: let user know that DNS resolution failed

### ISSUE THREAD

**Issue by fabianfrz** [opnsense/core#1264]
Output of /usr/local/opnsense/scripts/firmware/check.sh
```
{"connection":"error","repository":"error","product_version":"16.7.8-b1e53ce1b","os_version":"FreeBSD 10.3-RELEASE-p11","last_check":"Thu Nov 17 11:21:26 UTC 2016","updates":"","download_size":"none","extra_space_required":"none","new_packages":[],"reinstall_packages":[],"upgrade_packages":[],"upgrade_needs_reboot":"0"}
```

from the ssh menu it works flawlessly

pkg version: 1.9.3

**Comment by fichtner** [comment]
Can't say I can reproduce this. Please run the following and paste the output.

    # sh -x /usr/local/opnsense/scripts/firmware/check.sh

**Comment by fabianfrz** [comment]
Was able to reproduce the error - DNS service broke (restart helped) - maybe add a test if DNS is working so there will be a better error message.

**Comment by fichtner** [comment]
The messages were tweaked. Upon further reflection, we don't want to probe DNS from the updater and also not from anywhere else without the user knowing. :) Some people don't get DNS set up properly, but that's a rare outlier judging by the issues reported in the forum.

**Comment by fichtner** [comment]
This was introduced lately so I thought I'd move the milestone. :)
