### ISSUE TITLE
Static interface with DHCP server enabled is being re-assigned the lowest address range for DHCP

### ISSUE THREAD

**Issue by adessemond** [opnsense/core#127]
When configuring the network interfaces, I set:

em0 -> WAN - static
em1 -> LAN - static (192.168.1.1) with DHCP server enabled (range: 192.168.1.50 to 192.168.1.60)
em2  -> OPT1 - static

I configure the WAN then the LAN then OPT1 interface. The issue triggers at the end of configuring OPT1: OPNsense reloads the DHCP server, then my LAN interface changes from 192.168.1.1 to 192.168.1.50 which basically corresponds to the lowest available address in the range reserved for automatic address assignments. The same happens through a reconfiguration via the Web interface.

Everything comes back in order after rebooting....

EDIT: Unable to reproduce with latest updates, please close this issue as it is "invalid".

**Comment by fichtner** [comment]
Thanks for following up on this. :)
