### ISSUE TITLE
RADIUS MAC authentication on Captive Portal

### ISSUE THREAD

**Issue by greenvespa** [opnsense/core#1270]
Actually (version 16.7.9)  the mac address of the user isn't send with the authentication to the radius server.
Could you please add this feature for the next releases?
Thanks!

**Comment by x-ian** [comment]
Just to verify: I assume this Issue was closed as it won't be added (and not because it was already implemented), right?

So no MAC-based Auth of the Captive Portal for opnsense?

**Comment by AdSchellevis** [comment]
timed out, nobody working on it.
