### ISSUE TITLE
radvd does not start

### ISSUE THREAD

**Issue by Shadesh** [opnsense/core#1273]
On OPNsense 16.7.9-amd64 the radvd service dies and never comes up again. My setup is simple, i get new IPv6 subnets via DHCP from my ISP. My WAN interface has one /128 address and the LAN interface gets a /64 assigned.

The radvd service dies everytime this happens:

Nov 24 18:31:47 gw opnsense: /usr/local/etc/rc.newwanipv6: rc.newwanipv6: Informational is starting re0.
Nov 24 18:31:47 gw opnsense: /usr/local/etc/rc.newwanipv6: rc.newwanipv6: on (IP address: 2001:*:*:*:a585:fe6d:*:1230) (interface: wan) (real interface: re0).
Nov 24 18:31:48 gw opnsense: /usr/local/etc/rc.newwanipv6: ROUTING: setting IPv4 default route to 111.122.133.1

There is no error or something when i try to start it via the webinterface. It just does not start. When is start it via Shell, it's up, working and the "green" symbol is also shown at the dashboard, but everytime the script  rc.newwanipv6 runs, it stops again... This didn't happen on a previous release.

Anyone with the same problem?

**Comment by netrixtardis** [comment]
I just encountered this bug (or I did not notice it until after I rebooted).  It was working even after the upgrade to OPNsense 16.7.9-i386 earlier in the week, but I had not performed a reboot.  After a reboot a couple of hours ago, I noticed it did not come back.  I've re-configured my device to remove IPv6 configuration, and re-did them to no change.  not even sure where to troubleshoot the issue....

**Comment by netrixtardis** [comment]
Looks like a lot of work done under commit: ab1cf69f06ab0bcadc11d98ecd7876e6eee35ddf tagged for 16.7.9.  May be the commit that broke radvd.

**Comment by fichtner** [comment]
Hi guys,

Right, I needed to make sure that the following works... On 16.7.9 run this command to undo the commit (rerun to reapply, etc.):

    # opnsense-patch ab1cf69

If it works afterwards, I'm going to need both /var/etc/radvd.conf files from when this works and when it doesn't.

Please send to franco AT opnsense DOT org


Thanks,
Franco

**Comment by netrixtardis** [comment]
Performed as requested, undoing the commit has made radvd work normally.  I compared radvd.conf between each time - they are identical.  The commit changed something else breaking radvd.

**Comment by fichtner** [comment]
ok, will take a closer look at the commit, thanks for testing so far

**Comment by fichtner** [comment]
@netrixtardis what's your setting for ra mode? and is dhcpv6 enabled in your setup or not?

**Comment by Shadesh** [comment]
Same here. No DHCPv6 enabled, only radvd to distribute the /64.

**Comment by fichtner** [comment]
@Shadesh what's your selected router advertisement mode (first setting on the page)?

**Comment by netrixtardis** [comment]
I am not using DHCPv6 internally to handle IPv6 address assignment.

WAN - IPv6 Configuration Type:  DHCPv6
LAN - IPv6 Configuration Type:  Track Interface

ISP assigns a /128 for WAN, then provides a /64 to LAN.

**Comment by fichtner** [comment]
still need to know which router advertisement mode is set in the respective GUI page... could it be it's set to something other than "unmanaged"?

**Comment by Shadesh** [comment]
There is nothing you can set afaik. It just picks the /64 and distributes it to the LAN. Don't know the exact words (I'm at work at the moment) but when i go to the services pages for DHCPv6 and then to "Advertisements" it only says "No Interfaces with static IPv6 adresses found". but it worked like a charm before that commit. Please correct me @netrixtardis if i'm wrong here, because it looks like we're using the same setup ;)

**Comment by fichtner** [comment]
this is an interesting clue. so your LAN is set to track and radvd was automatic... more code review ensues...

**Comment by fichtner** [comment]
This should do the trick:

    # opnsense-patch 0ec8569

**Comment by Shadesh** [comment]
Looks good here. Let's see if it survives the next rc.newwanipv6 run ;)
Thanks!

**Comment by fichtner** [comment]
fingers crossed, and thanks for the quick testing :D

**Comment by netrixtardis** [comment]
Shadesh is correct.  I'm going to apply the fix myself real quick and I'll report back in a little while.

**Comment by fichtner** [comment]
You may have the the reverted patch installed. Try again after:

    # pkg install -f opnsense

**Comment by netrixtardis** [comment]
Yes - that worked this time, it applied cleanly.  Fix applied, and after reboot, radvd is running.

**Comment by fichtner** [comment]
@netrixtardis @Shadesh thanks, closing this now. if anything else pops up let me know.
