### ISSUE TITLE
OpenVPN client export tool does not supports multiple "local networks"

### ISSUE THREAD

**Issue by C-Duv** [opnsense/core#1275]
On OPNsense v16.7.9, if I configure an OpenVPN server with 
"IPv4 Local Network" field set to "192.168.0.0/24,192.168.1.0/24" (a comma-separated list of two networks) and generate the client configuration using the export tool.

### Expected result

The generated .ovpn file should contain the following `route` directives:
```
route 192.168.0.0 255.255.255.0
route 192.168.1.0 255.255.255.0
```

### Actual result

The generated .ovpn file only have the following `route` directive:
```
route 192.168.0.0 255.255.255.0
```

### Problem analysis

Problem seems to be there is no process of possible "comma" that delimits the list nor any loop:
```PHP
    if ($settings['local_network']) {
        list($ip, $mask) = explode('/', $settings['local_network']);
        $mask = gen_subnet_mask($mask);
        $conf .= "route $ip $mask\n";
    }
```
([file `/src/www/vpn_openvpn_export.php`, line 635](https://github.com/opnsense/core/blob/804d915b8b2f8551a49cbc2fffe3531a4d1425ea/src/www/vpn_openvpn_export.php#L635))

**Comment by fichtner** [comment]
@C-Duv thanks, please try this patch:

    # opnsense-patch 621d703

**Comment by C-Duv** [comment]
This patch fixes the issue, I get a .ovpn file with:
```
route 192.168.0.0 255.255.255.0
route 192.168.1.0 255.255.255.0
```
:+1:
