### ISSUE TITLE
OpenVPN client export tool does not export latest server settings

### ISSUE THREAD

**Issue by C-Duv** [opnsense/core#1276]
On OPNsense v16.7.9, generating the OpenVPN client configuration using the export tools does not seems to use the actual/latest server settings.

### Steps to reproduce

1. Create an OpenVPN server.
2. Export client configuration using the export tool
3. Change a setting of the OpenVPN server.
4. Re-export the client configuration using the export tool.

### Expected result

The second generated .ovpn file obtained from step 4 should reflect any changes you have performed on step 3.

### Actual result

The second generated .ovpn file obtained from step 4 is the same as the one obtained from step 2.

### Note

The following scenario where no export is done prior to change server settings works:

1. Create an OpenVPN server.
2. Change a setting of the OpenVPN server.
3. Export the client configuration using the export tool.

**Comment by fichtner** [comment]
Oh boy, the code hands out file names that are always the same, probably not wiping a file somewhere. Which *exact* export type are you using?

**Comment by C-Duv** [comment]
Both (config only and config+secret archive) have the issue.

**Comment by C-Duv** [comment]
According to my knowledge of this kind of problem I know why the following is "normal" (considering the issue) but I'll also report the following (in case anyone get the same issue):
After deleting an OpenVPN server and creating a new one: the exported file is the one for the _deleted_ server.

**Comment by AdSchellevis** [comment]
Have you tried another browser? When I change the cipher in a server and export the same user again, all looks good on my end.
To be sure I inspected the code for the "file only" export and it doesn't look like these type of files are synced to disk, so a caching issue on the server end seems very unlikely in this case.

**Comment by AdSchellevis** [comment]
timeout
