### ISSUE TITLE
Lobby: Dashboard: Services parsing issue

### ISSUE THREAD

**Issue by whoot** [opnsense/core#1277]
![fail](https://cloud.githubusercontent.com/assets/8066322/20628958/5f6d7936-b329-11e6-9589-b8a9fa7e93c6.png)
![server](https://cloud.githubusercontent.com/assets/8066322/20628959/5f712676-b329-11e6-8bf8-d96b115f0e26.png)

Hey,

there is a parsing issue in the "Service" tab on the Dashboard in the Lobby.
If the OpenVPN Server has a dot in its name, everything from it will not be displayed.

Example:
OpenVPN Server is named: 

- "test.me OpenVPN Server"

Then it will be displayed as:

Service 	Description 	                                              Status
openvpn 	OpenVPN server: test

**Comment by fichtner** [comment]
Ouch, nice catch... Historic commit...

https://github.com/pfsense/pfsense/commit/41af581edd49bb

We would encourage everyone *not* do write long descriptions or deal with the consequences. "." is not a good metric to start with.

I'm going to back this out.


Cheers,
Franco

**Comment by fichtner** [comment]
Fixed, thanks! Applies with a single command or wait till shipped with 16.7.10... :)

    # opnsense-patch df469d3
