### ISSUE TITLE
OSPF Support (Quagga integration)

### ISSUE THREAD

**Issue by SteloNLD** [opnsense/core#1280]
Dear Developers,

As stated in the [OPNsense Quagga How To](https://docs.opnsense.org/manual/how-tos/quagga.html?highlight=ospf) OPNsense does support OSPF but there is no integration.

I would really like to see some form of integration for this kind of routing protocol.

**Comment by AdSchellevis** [comment]
moved to https://github.com/opnsense/plugins/issues/63
