### ISSUE TITLE
Selectable OpenVPN version.

### ISSUE THREAD

**Issue by SteloNLD** [opnsense/core#1281]
Dear Developers,

I would like to have the ability to select a OpenVPN version in the same way you can select a SSL version (OpenSSL/LibreSSL) 

- [OpenVPN](https://openvpn.net/)
- [OpenVPN-NL](https://openvpn.fox-it.com/)

It makes sense to also support OpenVPN-NL being an NL Company and it makes your solution more attractive to the NL Medical, Government and Education sectors.

**Comment by AdSchellevis** [comment]
I don't know which additional security features Fox IT incorporated in their version of openvpn, the website isn't very explicit about them, but the website does state the following:

> For all OpenVPN-NL releases which are available for download, the source code of that version is made available. The positive evaluation of the NBV applies only to the binaries which are distributed via the OpenVPN-NL website. One may choose to compile OpenVPN-NL oneself, but the assessment of the NBV is not warranted for any self-compiled version. The source code of OpenVPN-NL is distributed in this manner as a courtesy to the professional who really knows what he is doing, and also to comply with the copyright licence which applies to the source code (GPLv2)

The positive evaluation is only valid for pre-build versions from Fox IT, which can't be installed on OPNsense.
If you have enough time, you could investigate the changes brought into their version and inspect if it makes sense to add them to the standard version, it very likely doesn't make a lot sense to add two versions of the same software.

**Comment by fabianfrz** [comment]
This page seems to have a comparison: https://openvpn.fox-it.com/about.html
It also states that they contributed the patches upstream, so they may already be in the standard OpenVPN daemon. See heading "Open Source".

**Comment by SteloNLD** [comment]
I see what you mean, it was suggested to me several times that this version would be a requirement for certain data streams, compiling it from source without having the official 'positive evaluation' stamp means it is not 100% covered, i guess that my dedicated OpenVPN-NL host will be running for a while ;)

**Comment by fabianfrz** [comment]
@SteloNLD as the web site says only the compiled version from them are certified and as long as there is no FreeBSD version available it cannot be included.

There are two options:
* close this issue as it cannot be solved
* send it upstream to the developers of this version of OpenVPN and include it in the repository when available
