### ISSUE TITLE
Routes to OpenVPN remote network are not created: cannot contact remote network

### ISSUE THREAD

**Issue by C-Duv** [opnsense/core#1283]
On OPNsense v16.7.9, if I configure an OpenVPN server (for site-to-site link) with:
* Server Mode: Peer to Peer (Shared Key)
* Protocol: UDP
* Device Mode: tun
* IPv4 Local Network: 10.1.0.0/16
* IPv4 Tunnel Network: 192.168.9.0/30
* IPv4 Remote Network: 10.2.0.0/16
* Client Settings>Dynamic IP: checked
* Client Settings>Address Pool: checked
* Client Settings>Topology: checked

No route to the remote network (_10.2.0.0/16_) is added (the command `netstat -r -n` makes no mention of it), so I can't contact any machine of this network.

(Note: In my case, on the other -client- side I am not using OPNsense and, for this example, let's pretend routing on client side is fine).

### Expected result

`netstat -r -n | grep -F "10.2.0.0/16"` should return:
```
10.2.0.0/16      192.168.9.2         UGS      ovpns1
```

### Actual result

`netstat -r -n | grep -F "10.2.0.0/16"` returns no line.

### Problem analysis

From what I found in OPNsense code, remote network is indeed added to OpenVPN's configuration file in */var/etc/openvpn/server1.conf* as a `route` directive:
```
[...]
route 10.2.0.0 255.255.255.0
[...]
```

Relevant PHP code:
```PHP
    // Add a remote network route if set, and only for p2p modes.
    if ((substr($settings['mode'], 0, 3) == "p2p") && (openvpn_validate_cidr($settings['remote_network'], "", true, "ipv4") === false)) {
        $conf .= openvpn_gen_routes($settings['remote_network'], "ipv4", false);
    }
```
([file `/src/etc/inc/openvpn.inc`, line 723](https://github.com/opnsense/core/blob/7c65a076d68aa744ae76fc226a2d1a4038d90e25/src/etc/inc/openvpn.inc#L723))

So it seems that OPNsense relies on OpenVPN to add the route(s) to the system: either this assumption is false and routes should be added by OPNsense or OpenVPN is not doing it's job.

### Workaround

Manually adding the route is possible and make access to remote network from OPNsense (and any machine belonging to it's LAN network) working:
```Shell
route add -net 10.2.0.0/16 192.168.9.2
```

**Comment by fichtner** [comment]
I am under the impression this works now? If not please reopen.

**Comment by dzikus** [comment]
It doesnt work till today. I have set client specific overrides with "IPv4 Remote Network" and set also "IPv4 Remote Network" in server.

It gives configs that should works but ovpn does't set route.
