### ISSUE TITLE
Update 16.7 to Unbound to 1.5.10

### ISSUE THREAD

**Issue by brad0** [opnsense/core#1284]
I noticed the Unbound version OPNsense is shipping is fairly old at 1.5.7. The latest release is 1.5.10. The .10 release contains a fairly important bug fix "Fix #804: unbound stops responding after outage. Fixes queries that attempt to wait for an empty list of subqueries."

**Comment by fichtner** [comment]
Unbound was added in 16.7.6 and we are currently at 16.7.9. Please update from System: Firmware: Updates. 😊

https://github.com/opnsense/changelog/blob/master/doc/16.7.6

Cheers,
Franco
