### ISSUE TITLE
Loss of IPv6 when radvd starts, then total WAN connectivity loss

### ISSUE THREAD

**Issue by kgleason** [opnsense/core#1286]
I think my issue is related in part to #1273. It's been difficult to test without completely irritating my family. I am currently running OPNSense 16.7.9 on some old hardware that I had laying around. The hardware is old (AMD Athlon from around 2006), and it is starting to get noisy, so I grabbed some stuff to replace it. The new rig is an Atom based device, it is small and blissfully quiet. I made a backup of my OPNSense config, installed OPNSense on the new machine, and restored from the backup. I powered off the old firewall, and rebooted everything. Things seemed good.

I noticed that Suricata and radvd weren't running. I know that suricata wasn't running on the old device (something with upstream suricata and older AMD processors), but I didn't know if radvd was previously broken or not. Weird.

I came searching here for known issues with radvd, and found issue #1273. I applied the recommended patch, and radvd did in fact start up. However, as soon as radvd started, OPNSense lost all of it's IPv6 addresses, and about 30 second later, my entire connection was dead. Weird again. 

I rebooted everything, and it seemed to come back. Connection was working, and I was getting IPv6 addresses from my provider. Then about 30 seconds after the OPNSense chimes went off, the IPv6 addresses went away. About 30 seconds later, total loss of WAN connectivity.

I tried the same thing once more with the same results. You can find my IPv6 config documented [here](https://www.kirkg.us/posts/setting-up-ipv6-with-opnsense-and-comcast/).

By this point my kids were getting fired up about no internet, so I put the old OPNSense box back in place. Voila connectivity was restored and solid. I had IPv6 addresses both in OPNSense and on all of my clients. However, radvd wasn't starting. So while I had an IPv6 address (a proper address, not a link-local address) on my laptop, I wasn't able to ping6 anything, or browse to ipv6.google.com.

As I was typing all of this, I found out that 16.7.10 is dropping tomorrow. Hopefully I'll just be able to close this issue once I get everything upgraded (new and old). If not, what kind of information will I need to collect to get to the bottom of this?

**Comment by fichtner** [comment]
Hi Kirk,

We'd need the /var/etc/radvd.conf from the working and the non-working box.

Logs for radvd are under "System: Routing: Log files". Looking for anything that pops out.

Your setup is still recent?

https://www.kirkg.us/posts/setting-up-ipv6-with-opnsense-and-comcast/

We can also revert to 16.7.8 to see if that makes a difference.


Cheers,
Franco

**Comment by kgleason** [comment]
Franco,
  My IPv6 setup does still reflect what is in the blog article.
  To be clear, I'm not sure that either radvd is working. Currently on the old machine (what I am running right now), radvd is stopped, and won't start. On the new box, I applied the patch you suggested in #1273, and radvd started, but that was when everything got really weird.
  That said, I'll do what I can to grab them both when I get home.

**Comment by kgleason** [comment]
Sorry about the long delay. Had to take off for the weekend. Came back and my OPNSense was all up to date to 16.7.10 and IPv6 is working from all of my internal machines now. I'm still running on the old firewall, and I'm going to trade it out again today. I'm going to close this ticket, since my old firewall is all updated, I've lost the opportunity to collect the logs.
