### ISSUE TITLE
Unbound has incorrect list of private networks

### ISSUE THREAD

**Issue by C1int** [opnsense/core#1287]
The unbound configuration file contains the incorrect private-address entry:

private-address: 192.254.0.0/16

The network 192.254.0.0/16 is not private address space, and should not be listed.

**Comment by fichtner** [comment]
Hi @C1int,

This was fixed in 16.7.9 last week. :)

 https://github.com/opnsense/changelog/blob/master/doc/16.7.9#L19


Cheers,
Franco
