### ISSUE TITLE
Multi-WAN with >4 Connections

### ISSUE THREAD

**Issue by willjones** [opnsense/core#1291]
It would be good to be able to add extra DNS servers for multi-wan setups with more than four external connections as at present the GUI only allows for four to be configured limiting how many we can configure.

**Comment by fichtner** [comment]
I agree. The current 4 servers are hardcoded, which makes this all the more difficult to extend, let me see if I can wrap this reliably and extend afterwards. :)

**Comment by fichtner** [comment]
should be good with b47c65bc013e6fd840eea479347b2691fc13e9e9
