### ISSUE TITLE
Feature request : DHCP lease add/paste multiple entry in a text field

### ISSUE THREAD

**Issue by tapsystem** [opnsense/core#1296]
Hi,
It can be useful to past several lease at the same time in DHCP static maping entries, it's not easy to enter mac address one by one, maybe the possibility to make a large copy/paste like this :

18:68:da:09:6a:be	192.168.200.3	#station1
bc:30:5b:b0:aa:86	192.168.200.4	#station2
18:a6:da:05:fc:8a	192.168.200.5	#station3
98:90:9d:e4:9f:a7	192.168.200.6	#station4
.....
		
Tks a lot

**Comment by AdSchellevis** [comment]
timeout due to inactivity
