### ISSUE TITLE
Deleting traffic shaper rules/pipes/queues does not delete from ipfw until reboot

### ISSUE THREAD

**Issue by RickNY** [opnsense/core#1297]
Up until and including 16.7.10, if you attempt to delete rules, pipes, or queues from the traffic shaper screen in the GUI, they only delete from the GUI - but still remain in ipfw.. Likewise, the GUI does not seem to show ipfw transactions that may have been manually added from a shell session.  Even when the items are deleted from the GUI, ipfw still processes the rules as if they were still there.  My experience so far has been to either drop to a shell and perform an ipfw flush on the objects in question, or to just reboot.

It would also be helpful if the GUI accurately reflected objects that were created in a shell manually.

**Comment by AdSchellevis** [comment]
@RickNY Manual additions won't be supported, just too complex and really not the way it should work. cleaning up unused pipes and queues might be something worth to look into at some point, but has some disadvantages too (like traffic still using those objects and possible stability issues when flushing all on once), usually the unused pipes and queues don't bother that much.

An apply should should reload the rules and delete the ones added manually in the shell too, only unused pipes and queues remain in the list.... but shouldn't be used after the same apply (maybe for a split second, for the sessions currently active).

Is there a specific scenario where it really is worth the trouble of removing the unused pipes and queues?

**Comment by RickNY** [comment]
I understand the complexity of what you are saying. What about a relatively easy compromise -- a reset button in the traffic shaper GUI that will flush everything?

**Comment by AdSchellevis** [comment]
sounds like a plan
