### ISSUE TITLE
Disable automatic OpenVPN interface group

### ISSUE THREAD

**Issue by m4rcu5** [opnsense/core#1299]
As discussed on IRC with @fichtner and @djGrrr, it would be a nice feature to have a way to disable the automatic OpenVPN interface group.

At the moment, all OpenVPN interfaces (servers and clients) are grouped together into a single tab on the firewall page called "OpenVPN". In case of multiple OpenVPN instances this gets confusing as rules apply to all instances instead of a single one. More advanced users would assign an interface to the vpn instance and manage rules that way. However the "OpenVPN" tab (interface group) would exist in the interface. Naming your own assigned interface the same would override the tab, but the dropdown will now show duplicates.

Another nice to have would be to show the interface group more transparently when enabled, but listing it in the interface groups menu, including its members.

**Comment by AdSchellevis** [comment]
timeout due to inactivity
