### ISSUE TITLE
Unused gateways keep appearing

### ISSUE THREAD

**Issue by m4rcu5** [opnsense/core#1300]
If one adds a new interface of a tunnel type. There are 2 gateways created by default. A TUNNELV4 and TUNNELV6, even is the interface does not have a v6 or v4 address.

You can disable the extra gateway, but as soon as you delete it, it will re-appear as active.

**Comment by fichtner** [comment]
This is exactly how the system copes with missing gateways. It does this to recover into a known state. Only disable will prevent this. Gateway code will require more work (along with apinger), but I'd like to wait for after 17.1.

**Comment by raoulwegat** [comment]
@fichtner: Similar situation: I have one default WAN gateway, then clone it, set clone to default and active. Set the old to disabled and deselect default. Then I delete the old gateway, as it reappears as active and default. Also the description text appears as: "Interface {GW_name} Interface" 

1. Single default WAN gateway
![1](https://cloud.githubusercontent.com/assets/2627210/22178925/54065cce-e098-11e6-960a-746b3c334afa.png)

2. After cloning and disabling the original.
![2](https://cloud.githubusercontent.com/assets/2627210/22178931/62c267c6-e098-11e6-9507-9d99f7277c45.png)

3. After deleting the original. Applying changes doesn't change anything.
![3](https://cloud.githubusercontent.com/assets/2627210/22178939/7a28c8e2-e098-11e6-98ad-ee5030c4ae37.png)

**Comment by fichtner** [comment]
Is this still happening on 17.1? There was a fix that went in..

**Comment by raoulwegat** [comment]
All fixed in 17.1 👍

**Comment by fichtner** [comment]
@raoulwegat thanks for confirming :)
