### ISSUE TITLE
Intrusion detection alerts tab pagination is wrong

### ISSUE THREAD

**Issue by wernerreuser** [opnsense/core#1302]
I have 32 alerts in my alert view from IDS, I select 'All' in the dropdown (or any higher number than 7), the page shows all alerts but still shows pagination in the footer and the message 'Showing 1 to 7 of 32 entries'. Clicking on one of the page numbers shows the same page.

**Comment by AdSchellevis** [comment]
see https://github.com/opnsense/core/issues/756 , long story short, not really fixable.

**Comment by wernerreuser** [comment]
Not sure about the explanation, shoudn't be too hard to get the amount of logfile line, like with wc -l <filename> in the cli and base the amount of pages on that and the amount of items to list per page...

**Comment by AdSchellevis** [comment]
@wernerreuser those files can get really large, so you really don't want to count lines on every request.....

**Comment by wernerreuser** [comment]
I understand... conclusion is file based this won't work properly... Not an issue in my case as we plan to ship logs to our external logstash/elasticsearch/kibana for viewing and filtering.

**Comment by AdSchellevis** [comment]
yes, file based is fine to get some results and see the last alerts, not for processing results ;) most people use ELK or something similar on another machine to process/analyse the logs.
