### ISSUE TITLE
webConfigurator anti-lockout help text not describing observed behaviour in WAN-only setup

### ISSUE THREAD

**Issue by chrwick** [opnsense/core#1304]
Version: OPNsense 16.7.11_1-amd64

In WAN-only setup where no LAN interface is present the text mentions the WAN interface and not the LAN interface:
"When this is unchecked, access to the webConfigurator on the WAN interface is always permitted, regardless of the user-defined firewall rule set. "

However, an anti-lockout rule is not automatically added in WAN-only setup. 
I am not sure if this is intended. 

Possible solutions:
1) Disable the anti-lockout option in WAN-only setup, if it is intended to not add such a rule for the WAN interface for security reasons.
2) Add anti-lockout rule accordingly in WAN-only setup to WAN interface, if it can be assumed that the user knows what he is doing when only using a WAN interface and no LAN interface. (e.g.: OpenVPN access server)

**Comment by fichtner** [comment]
3. option would be to fix the help text. :)

For 1. maybe disabling the button would be enough?

Not sure which, but I agree this is something to fix.

**Comment by chrwick** [comment]
My suggestion would be: 1) + 3)
Fix the help text stating that this is only valid for Non-WAN interfaces and disable the button if only a WAN interface is present. Disabling makes sense, because otherwise I would expect that something happens when using the button.

**Comment by fichtner** [comment]
```
However, an anti-lockout rule is not automatically added in WAN-only setup.
I am not sure if this is intended.
```

Upon further investigation, this isn't entirely true: the anti-lockout rules are added to WAN, in my case port 80 and 443, but only if there is no OPT network. Need to read up some more...

**Comment by fichtner** [comment]
We now only switch to WAN if it's the only interface, otherwise the text sticks to "LAN", which is not there so that's fine. :)
