### ISSUE TITLE
IPSec: autogenerated rule missing

### ISSUE THREAD

**Issue by sachaz** [opnsense/core#1308]
The autogenerated rules are perfect, just missing one rule:
pass in quick on enc0 inet from REMOTELAN to LOCALLAN flags S/SA keep state label "USER_RULE: blahblah"

**Comment by AdSchellevis** [comment]
Not everybody would like to see the same policy, some networks should be filtered. 
see my comments in your other two issues https://github.com/opnsense/core/issues/1306 and https://github.com/opnsense/core/issues/1307 as well.
