### ISSUE TITLE
Web Proxy Interface Subnets are not computed correctly

### ISSUE THREAD

**Issue by prokrastinix** [opnsense/core#1309]
I configured two interfaces with IPv4 `10.10.10.64/26` and `10.10.10.128/26`. If I set up the Web Proxy for those two interfaces and tick _Allow interface subnets_, the resulting entries in `/usr/local/etc/squi/squid.conf` are:

```
# Rules allowing access from your local networks.
# Generated list of (internal) IP networks from where browsing
# should be allowed. (Allow interface subnets).
acl localnet src 10.10.10.0/26 # Possible internal network
acl localnet src 10.10.10.0/26 # Possible internal network
```

**Comment by fabianfrz** [comment]
The issue may be caused by the template:
https://github.com/opnsense/core/blob/master/src/opnsense/service/templates/OPNsense/Proxy/squid.conf#L104
