### ISSUE TITLE
Wireless Speed & duplex in Host AP mode

### ISSUE THREAD

**Issue by kgleason** [opnsense/core#1313]
Let me start out with some system info:

    OPNsense 17.1.b-amd64
    FreeBSD 11.0-RELEASE-p5
    OpenSSL 1.0.2j 26 Sep 2016

    ath0: <Qualcomm Atheros AR9565>
    em0: <Intel(R) PRO/1000 Network Connection 7.6.1-k> 

I have ath0_wlan1 up and running in HostAP mode. I am able to connect to the wireless network, and browse botht he local network and the internets.

I wasn't able to test any of this in 16.7, since hostap didn't seem to work properly with ATH0. It could be that this is an existing issue, it could be that it is not an issue at all.

In the WIFI interface (what I named ath0_wlan1), I have the standard set to 802.11ng. However, based on what I am seeing from wavemon (on the client), it looks as if it is connecting using 802.11b.

When I investigate further, I see the following on the dashboard:

    WIFI		autoselect mode 11b <hostap>	172.19.22.1 

So it looks as if the interface is automatically determining that the wireless should be using 802.11b. I went into the interface settings for WIFI, and I attempted to adjust the Speed and Duplex value to anything other than default. After clicking save and apply, the setting always reverts back to default, and the AP always comes back up with 802.11b.

The hint in the Speed and Duplex setting makes perfect sense to me for a wired interface; but it seems as if the same logic might be being applied to the wireless interface as well. Since there is no switchport on the other side, there is nothing for me to negotiate with.

Or I am misunderstanding something.

Is there a way that I can force the AP to only use 802.11n or 802.11ng?

For the sake of thoroughness, here is the output from `ifconfig ath0_wlan1`

    ath0_wlan1: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500
	ether ac:b5:7d:72:bb:57
	inet6 fe80::aeb5:7dff:fe72:bb57%ath0_wlan1 prefixlen 64 scopeid 0x6 
	inet 172.19.22.1 netmask 0xffffff00 broadcast 172.19.22.255 
	nd6 options=21<PERFORMNUD,AUTO_LINKLOCAL>
	media: IEEE 802.11 Wireless Ethernet autoselect mode 11b <hostap>
	status: running
	ssid BloomTestWifi channel 1 (2412 MHz 11b) bssid ac:b5:7d:72:bb:57
	regdomain 106 indoor ecm authmode WPA1+WPA2/802.11i privacy MIXED
	deftxkey 3 TKIP 2:128-bit TKIP 3:128-bit txpower 20 scanvalid 60 burst
	-apbridge dtimperiod 1 -dfs
	groups: wlan 

Also, here is `/var/etc/hostapd.conf`

    # cat /var/etc/hostapd_ath0_wlan1.conf 
    interface=ath0_wlan1
    driver=bsd
    logger_syslog=-1
    logger_syslog_level=0
    logger_stdout=-1
    logger_stdout_level=0
    dump_file=/tmp/hostapd_ath0_wlan1.dump
    ctrl_interface=/var/run/hostapd
    ctrl_interface_group=wheel
    #accept_mac_file=/tmp/hostapd_ath0_wlan1.accept
    #deny_mac_file=/tmp/hostapd_ath0_wlan1.deny
    #macaddr_acl=
    ssid=TestWifi
    debug=
    auth_algs=1
    wpa=3
    wpa_key_mgmt=WPA-PSK
    wpa_pairwise=CCMP TKIP
    wpa_group_rekey=60
    wpa_gmk_rekey=3600
    wpa_strict_rekey=
    wpa_passphrase=supersecret

Please let me know if you require any additional information.

**Comment by AdSchellevis** [comment]
timeout due to inactivity
