### ISSUE TITLE
Captive Portal: users should be configured and enabled in the CP Screen

### ISSUE THREAD

**Issue by jstrebel** [opnsense/core#132]
Currently we need to configure the user and their password in the System:User Manager. I suggest to configure the CP users in the CP screen. Those users have in my view nothing in common with the Users in the "User Manger. 
In M0n0wall this type of user are configured in the CP pave
Regards Jakob

**Comment by fichtner** [comment]
Hi Jakob, I agree with this. We have the same issue in the VPN functionality. I'll pick this up, but it'll take a bit of time to materialise.

**Comment by fichtner** [comment]
Reassigned to the portal master. ;)

**Comment by AdSchellevis** [comment]
For voucher type users I agree and the new version does implement voucher users in a separate screen. Within the normal access control, it does make sense to handle them shared. captive portal is a service in this case, just like ipsec is for example.

Can we close this one?
