### ISSUE TITLE
Not forwarding DHCP leases to DNS resolver

### ISSUE THREAD

**Issue by BastiG** [opnsense/core#1320]
I've run into an issue where Unbound would not resolve hostnames for devices that obtained their IP addresses through DHCP. After some debugging it turned out that the dhcpd watcher python script ([/usr/local/opnsense/site-python/watchers/dhcpd.py](https://github.com/opnsense/core/blob/master/src/opnsense/site-python/watchers/dhcpd.py)) throws an uncaught exception when the DHCP server is running with failover peer configured.

The script searches the leases file for the occurence of a "lease" block, stores all the content in _section_data and tries to parse the information once it finds an empty line with just the "}" character.

Having a failover peer configured there is an additional block in the leases file and the script will identify the curly bracket from the failover peer block (see the first few lines of my [dhcpd.leases](https://github.com/opnsense/core/files/679687/dhcpd.leases.txt) file attached). It fails to parse the _section_data which, in that case, only contains the "}".

A simple one-line patch like the attached [dhcpd.patch](https://github.com/opnsense/core/files/679688/dhcpd.patch.txt) should do the trick.

**CONDITIONS**:
* DHCP Server is configured and running in HA mode
* DNS Resolver (Unbound) is enabled and running

**STEPS TO REPRODUCE**:
* have a client obtain a lease through DHCP
* then run /usr/local/opnsense/scripts/dns/unbound_dhcpd.py in foreground (i.e. don't Daemonize)

**Comment by AdSchellevis** [comment]
@BastiG thanks, it looks like I missed that one :)
