### ISSUE TITLE
 [plugins] inject new NAT rules

### ISSUE THREAD

**Issue by fraenki** [opnsense/core#1326]
Similar to #993 it should be possible (for plugins) to inject NAT rules as required.

**Comment by fichtner** [comment]
Doesn't this cover all yet? If not, I know @fbrendel and @fabianfrz are waiting for this already.

Don't think this will be before 17.1.x though.

**Comment by AdSchellevis** [comment]
it's on my list..... all firewall logic should follow the same rules, but given the impact of changing the standard parsing, we (@fichtner and I) decided to hold development off for some time.
Using anchors you should be able to inject rules already (like some services do).

**Comment by fraenki** [comment]
>  Using anchors you should be able to inject rules already (like some services do).

I've seen the examples to inject regular FW rules. Am I missing something... does this work for NAT rules too?

**Comment by AdSchellevis** [comment]
if I'm not mistaken both relayd and ftpproxy use an anchor to forward traffic, but a registration option will be added later....

**Comment by fbrendel** [comment]
The ftpproxy plugin only adds the anchor and the ftp-proxy(8) daemon injects the rules.
And I believe the same does relayd.

Furthermore the plugin depends on regular FW rules to allow access to the ftp-proxy daemon.
This rules could be made automatically by the plugin. But this requires cluster aware services.

**Comment by AdSchellevis** [comment]
@fichtner I'm refactoring the code behind "enablenatreflectionhelper", to me this looks like a lot of magic which could be simplified a lot.

Do you know if there's a good reason why we shouldn't replace the two lines below

https://github.com/opnsense/core/blob/ad1744ce240fc721a473c6f434269b55c6fee135/src/etc/inc/filter.inc#L847-L848

with something which looks more like:

`nat on [emX] proto tcp from [emX]:network to [redirect ip] port [redirect port] -> [emX] port 1024:65535
`

Where emX is the interface configured to forward the session. At my end this seems todo exactly the same, but maybe I'm missing something.

**Comment by fichtner** [comment]
@AdSchellevis Judging by the commit history this was introduced by Scott in 2005 and kept that way. The [emX]:network network trick is what seems to make your suggestion work in one line. I'm all for it. We still have RC1 and RC2 to gather feedback so please go ahead. :)

**Comment by AdSchellevis** [comment]
ok, will do :)

**Comment by fichtner** [comment]
Im closing this since substantial work was done and we should discuss individual things in dedicated tickets.

**Comment by fichtner** [comment]
PS: thanks to @AdSchellevis for doing this huge rework!

**Comment by fabianfrz** [comment]
@fichtner I think all usual use cases are plugins doing DNAT (transparent proxy servers and dynamic port forwards) and IP based SNAT (VPN plugins).

If you think about the proxy (squid) it should be possible to create the rules you have to create manually now automatically.

**Comment by fichtner** [comment]
@fabianfrz it's a good idea to have tickets for each of these replacements, with them we could verify if the NAT plugging works as expected and / or needs further tweaks while working on the next goals.

**Comment by fabianfrz** [comment]
ok
