### ISSUE TITLE
[Bug] Menu option 12 (update) offers non-functional upgrade

### ISSUE THREAD

**Issue by fabianfrz** [opnsense/core#1329]
![virtualbox_opnsense_07_01_2017_15_55_47](https://cloud.githubusercontent.com/assets/3713914/21742585/38958098-d4f2-11e6-8c83-2b98378030bf.png)

Expected Result: Should only offer upgrade to beta if available
Current: Error

Version: current beta series

**Comment by fichtner** [comment]
Sorry, -devel is -devel. It's a construction site and staging area for the releases. We don't have LibreSSL yet. :)
