### ISSUE TITLE
Turn off all hardware offload when enabling IPS automatically

### ISSUE THREAD

**Issue by L1ghtn1ng** [opnsense/core#1333]
When enabling IPS, hardware offload is not automatically disabled. It should be as forgetting causes the system to not be available, this is an easy thing to forget and people will just expect it to work when they enable IPS mode.

Opnsense 16.7.13 amd64 LibreSSL on A10

**Comment by fichtner** [comment]
The default config.xml has been changed to switch off all hardware features. This wasn't in the images, so you will only be seeing this after a factory reset or when installing a new 17.1.

See #1092
