### ISSUE TITLE
NAT reflection does not work with alias containing DNS hostname

### ISSUE THREAD

**Issue by pv2b** [opnsense/core#1338]
I ran into an issue creating a port-forward to an internal server. It seems that the "helper rule" for NAT reflection (the rule that re-writes the soource address of traffic being "hairpinned" on the same subnet as the opnsense box's ip address) is not properly generated in case the destination of the port forward is created through an alias with a DNS name. Changing the alias to a hardcoded IP address worked around the issue.

The following two lines were added to /tmp/rules.debug with the alias "srv1" set to an IP address instead of "srv1.customer.com": (ip addresses obviously changed for anonymity)

no nat on em0 proto tcp from em0 to $srv1 port 8080
nat on em0 proto tcp from 10.532.289.999/24 to $srv1 port 8080 -> 300.999.874.842 port 1024:65535

My guess is that the problem "smells like" it occurs because the filter_generate_reflection_nat function in filter.inc tries to check the IP addresses of the target by reading directly from the config, instead of after the aliases have been populated through dns resolution. There may in fact not be an easy way to "fix" this behavior, but it should at least be documented. A warning on filter reload might also be helpful.

**Comment by AdSchellevis** [comment]
timeout due to inactivity

**Comment by biGdada** [comment]
was it ever solved? i'm experiencing the same.
