### ISSUE TITLE
system: select sc/vt in general settings

### ISSUE THREAD

**Issue by stormy1777** [opnsense/core#1343]
See forum post: https://forum.opnsense.org/index.php?topic=4319.0

boot stuck on Video initialization, see image: https://goo.gl/photos/W26wr6ETpmjrC8hr6

Trying 16.7 on same USB stick, boots fine.  Tried on boot prompt:

set kern.vt.fb.default_mode="800x480"
boot

but it still tries 800x600 and fails to initiate video.

Comparing /boot/loader.conf in 16.7 only 4 lines, in 17.1 many more, maybe that is it.

**Comment by stormy1777** [comment]
this page may be helpful: https://www.freebsd.org/cgi/man.cgi?query=vt&sektion=4

**Comment by fichtner** [comment]
We're not using vt, it has a few issues, so we stick to sc. Instructions in the forum. Please let me know if that was the issue.
