### ISSUE TITLE
ldap starttls support

### ISSUE THREAD

**Issue by EugenMayer** [opnsense/core#1346]
Seems like pfsense does already have this, but this is hugely important to be supported.

Especially considered that openldap deprecated ldaps since 2.0 should be reason enough to start working on this http://www.openldap.org/faq/data/cache/605.html

fitch pointed me on https://github.com/opnsense/core/blob/master/src/opnsense/mvc/app/library/OPNsense/Auth/LDAP.php#L353 so thats the starting point.
I guess we want http://php.net/manual/de/function.ldap-start-tls.php there, including an option the the form of the server configuration ( or rather say an option in the select ). Port should stay 389 as usual for startTLS.

In the end we need to run https://github.com/opnsense/core/blob/master/src/opnsense/mvc/app/library/OPNsense/Auth/LDAP.php#L251 those 3 things after the ldap_connect

    if($this->useStartTLS) {
      ldap_set_option($con, LDAP_OPT_PROTOCOL_VERSION, 3);
      ldap_set_option($con, LDAP_OPT_REFERRALS, 0);
      $encrypted = (ldap_start_tls($this->ldapHandle));
    }

And of course we need to patch https://github.com/opnsense/core/blob/master/src/opnsense/mvc/app/library/OPNsense/Auth/LDAP.php#L193 to include the property beside introducing those in the fields https://github.com/opnsense/core/blob/master/src/opnsense/mvc/app/library/OPNsense/Auth/LDAP.php#L97

For me at least thats more or less the show-stopper for opnsense and that would be horrible ;/

**Comment by EugenMayer** [comment]
I could provide a PR for the connection part, but i am not able to find out how to introduce the option / were the FAPI is.

Looks like the factory is generating the options: https://github.com/opnsense/core/blob/master/src/opnsense/mvc/app/library/OPNsense/Auth/AuthenticationFactory.php#L147 .. but ldap does not implement getConfigurationOptions

Cannot really find the configuration tempaltes in the views either https://github.com/opnsense/core/tree/master/src/opnsense/mvc/app/views/OPNsense

**Comment by EugenMayer** [comment]
That one gets in our way https://github.com/opnsense/core/issues/1348 .. but not really since it gets ignore anyway in the end, never used

**Comment by fichtner** [comment]
This commit should include all relevant files: https://github.com/opnsense/core/commit/0fb3fd78cbfe059001016a30b14fbe481f169282

The MVC code is a rewrite. The etc/inc code is gradually (re)moved. We try not to unhook existing functionality. At one point the authentication backend was rewritten, but still needs to provided to non-MVC pages.

**Comment by EugenMayer** [comment]
Yet not entirely finished, we need to care about https://github.com/opnsense/core/issues/1348 and also the one used when "select" is used to select the containers on the ldap form

**Comment by AdSchellevis** [comment]
@EugenMayer are you still working on this one?

**Comment by EugenMayer** [comment]
@AdSchellevis nope, i finished it, it was working, but nowdays using ldap+tls ( due to obvious reasons )

**Comment by AdSchellevis** [comment]
ok, I'll close this one then
