### ISSUE TITLE
Why does auth_get_authserver replicate the connection string configuration?

### ISSUE THREAD

**Issue by EugenMayer** [opnsense/core#1348]
Eventhough the Auth-Backend Implementations do their own thing in parsing the config and creating the configuration strings, auth_get_authserver replicates that, introducing possible erros and confusion, while later, passed to the OPNsense\Auth\AuthenticationFactory anyway in authenticate_user .. beside that little stunt here https://github.com/opnsense/core/blob/master/src/etc/inc/auth.inc#L754 which should go into LDAP https://github.com/opnsense/core/blob/master/src/opnsense/mvc/app/library/OPNsense/Auth/LDAP.php as a precondition into the constructor.

Nevertheless, the point is here, $authCFG is not even used, its created and passed here https://github.com/opnsense/core/blob/master/src/etc/inc/authgui.inc#L207 and then gets thrown away since the factory ignore is, out of good reasons since it implements config parsing itself while https://github.com/opnsense/core/blob/master/src/etc/inc/auth.inc#L701 is a plain duplication which is error prone

**Comment by AdSchellevis** [comment]
timeout due to inactivity
