### ISSUE TITLE
Order of "play" and "stop" button is not the same when a service is stopped/started

### ISSUE THREAD

**Issue by GurliGebis** [opnsense/core#1361]
Small issue, I know, but it makes it look inconsistent when it isn't the same.

Would it be possible to align it, so it is the same order (etc. play, refresh, stop) no matter if the service is running or not?

**Comment by AdSchellevis** [comment]
The first icon represents the status, it's not an actual action (in status_services.php). I don't think we should change the order, it would look wobbly if the colours (green/red) jump between columns.

**Comment by GurliGebis** [comment]
I see your point :)
