### ISSUE TITLE
broken link in console interface

### ISSUE THREAD

**Issue by mircsicz** [opnsense/core#1363]
Hi hi, just upgraded three of my installation's two of them went smooth a third has firewall rule issue's... But that's another story taking place in the forum!

In the console interface there's that link's and the "forums" link is broken. It leads to https://forums.opnsense.org when it should point to https://forum.opnsense.org... ;-)

[Screenshot](https://snag.gy/isoTJ0.jpg)

Greetz

BTW: not sure if core is the right place but didn't know any better place...

**Comment by fichtner** [comment]
Fair point. You've come to the right place. Fixed, thank you. :)
