### ISSUE TITLE
Unable to change keymap in installer

### ISSUE THREAD

**Issue by hoalex** [opnsense/core#1365]
When starting the installer, it gives you the option to change the keymap before starting the installation process. Unfortunately, this does not seem to work.

For example, selecting `german.iso.kbd` yields the following error: ![Error 1](https://i.imgur.com/yqHcwTW.png)

The ``View Log`` option shows the following output:
``,-<<< Executing `/usr/sbin/kbdcontrol -l``
``//usr/share/syscons/keympas/german.is.kbd < /dev/ttyv0´``
``| /bin/sh: cannot open /dev/ttyv0: No such file or directory``
`` `->>> Exit status: 2``

I tried this with some other keymaps and they all seem to lead to the same error.

Image: ``OPNsense-17.1-OpenSSL-serial-amd64.img`` running on APU2C4 (connected via RS-232 cable).

**Comment by fichtner** [comment]
Ah, ttyv0 is wrong, this is a serial-only image now

**Comment by fichtner** [comment]
"tty" command output seems do be the thing that we want here. There will be new images for 17.1.x, but not sure if this will make it as soon as 17.1.3 or later.

**Comment by fichtner** [comment]
Selection is now hidden if /dev/ttyv0 is not there. it is unclear if this ever worked for console, vid modes don't work in any case here.
