### ISSUE TITLE
AES-GCM ciphers not shown for IPsec tunnels

### ISSUE THREAD

**Issue by hoalex** [opnsense/core#1366]
I do not see a way to select an AES-GCM cipher for IPsec phase 1/2 tunnels: ![Screenshot](https://i.imgur.com/eOK4HQV.png)

There seems to be some logic checks in place to display an error message, when a non-AES-GCM cipher is selected without also selecting a hash function: [vpn_ipsec_phase2.php
](https://github.com/opnsense/core/blob/0e03967cf536052de38ab9624242765dde837b76/src/www/vpn_ipsec_phase2.php#L390)

Unfortunately, I do not see a way to actually select a AES-GCM cipher. I first thought thas selecting `Auto` would probably activate AES-GCM, but when trying to apply the changes without selecting a hash function, the error as shown in ``vpn_ipsec_phase2.php`` above is being shown (``At least one hashing algorithm needs to be selected.``). 

I found an old issue talking about adding AES-GCM to the UI: #12 Has this ever been implemented?

OPNsense 17.1 amd64 on APU2C4

**Comment by AdSchellevis** [comment]
The option is not in the gui yet, the feature is new in FreeBSD 11, we only need to add it to our interface.

**Comment by AdSchellevis** [comment]
@hoalex the patch is in, if you want to try, just use (on the command line):

`opnsense-patch 26c99a97
`

**Comment by hoalex** [comment]
Thanks @AdSchellevis!

I tested the patch on my OPNsense 17.1 box and tried to connect to a pfSense box on the remote side using AES-GCM for Phase 2:
```
root@OPNsense:~ # ipsec statusall
[...]
Security Associations (1 up, 0 connecting):
        con1[50]: ESTABLISHED 6 minutes ago, x.x.x.x[x.x.x.x]...y.y.y.y[y.y.y.y]
        con1[50]: IKEv2 SPIs: 83db69fec46ed6c3_i* 83ad346e8a04c23d_r, pre-shared key reauthentication in 7 hours
        con1[50]: IKE proposal: AES_CBC_128/HMAC_SHA2_256_128/PRF_HMAC_SHA2_256/MODP_4096
        con1{242}:  INSTALLED, TUNNEL, reqid 10, ESP SPIs: c437c5a4_i cc432e16_o
        con1{242}:  AES_GCM_16_128, 4445493 bytes_i (3288 pkts, 2s ago), 365252 bytes_o (2524 pkts, 2s ago), rekeying in 32 minutes
        con1{242}:   192.168.1.0/24 === 192.168.2.0/24
```
Everything works fine 👍 
I did not try using AES-GCM for Phase 1 yet, but I simply guess that this would work just as well ;-)

**Comment by AdSchellevis** [comment]
@hoalex thanks for testing!
