### ISSUE TITLE
import users icon not shown

### ISSUE THREAD

**Issue by neubian** [opnsense/core#1368]
OPNsense 16.7 & 17.1

/system_usermanager.php

per
https://forum.opnsense.org/index.php?topic=4069.0#msg14747

even with a working LDAP server configured and testing properly, there is no "import users" button or icon as indicated in the wiki here:  https://docs.opnsense.org/manual/how-tos/user-ldap.html

**Comment by AdSchellevis** [comment]
Are you sure you've changed the default authentication server to your ldap server in here system_usermanager_settings.php ?

**Comment by neubian** [comment]
Yes, the LDAP server was the primary, and local was fallback.

I switched the fall back to "--No Fallback--", then saved, and the icon appeared.  I added the Local Database back as the fallback, saved, and the icon remained.  I rebooted, the icon remained.  

Not sure why this came to be, but I'm not the only one who has experienced it:
   https://forum.opnsense.org/index.php?topic=4069.0

**Comment by AdSchellevis** [comment]
ok, that's odd, I can't seem to reproduce this behaviour.
The check in the code seems pretty straightforward.
https://github.com/opnsense/core/blob/master/src/www/system_usermanager.php#L950 

How was the original value set? was this an imported config from pfSense perhaps.

**Comment by neubian** [comment]
It was a fresh install of 16.x -- whatever was new about a week ago.

**Comment by sonicfx92** [comment]
I have same problem, but i resolved it.
I was installed last version OPNSense 17.1.6, succesfully configure LDAP, and didn't see Import icon.
I check primary auth. server and it was already LDAP. Then i manualy reselect default auth server and Import icon appear. Have a nice day!

**Comment by AdSchellevis** [comment]
timeout due to inactivity

**Comment by evbevz** [comment]
Have the same issue on 18.1.13

**Comment by mimugmail** [comment]
see screenshot:

![image](https://user-images.githubusercontent.com/20438689/48415853-e463a100-e74e-11e8-8f2e-c5a3c655dfa4.png)

**Comment by fichtner** [comment]
18.1.13 is no longer actively developed and 1b4eb8e went into 18.7 so we should be ok.
