### ISSUE TITLE
[framework] validation mask crashes the server

### ISSUE THREAD

**Issue by fraenki** [opnsense/core#1369]
@AdSchellevis, I guess your're the one to ask. :) I'm not sure if this is a bug or a feature. Should only a limited set of characters be used in the `<mask>` field in our model XML? Or should the code be improved to better handle special characters?

The following `<mask>`...

```
                 <description type="TextField">
                     <Required>N</Required>
                     <mask>/^[^\x{003c}\x{003e}\x{005b}\x{005d}\x{0024}]*{1,255}$/u</mask>
                     <ValidationMessage>Should be a string between 1 and 255 characters.</ValidationMessage>
                 </description>
```

...will lead to this error...

```
Feb  2 13:44:50 opnsense-test lighttpd[5754]: (mod_fastcgi.c.2424) unexpected end-of-file (perhaps the fastcgi process died): pid: 6283 socket: unix:/tmp/php-fastcgi.socket-1 
Feb  2 13:44:50 opnsense-test kernel: pid 30341 (php-cgi), uid 0: exited on signal 11 (core dumped)
Feb  2 13:44:50 opnsense-test lighttpd[5754]: (mod_fastcgi.c.3175) response not received, request sent: 2627 on socket: unix:/tmp/php-fastcgi.socket-1 for /api/api.php?_url=/haproxy/settings/setFrontend/14dc8751-cbb4-451c-8d0c-8f2f7e1cfe28&, closing connection 
```

...when trying to save the input field from the WebGUI.

**Comment by AdSchellevis** [comment]
Hi Frank,

I'm not sure why it crashes on your end, it looks like a faulty regex, my machine returns:

> Error at /usr/local/opnsense/mvc/app/models/OPNsense/Base/BaseModel.php:368 - preg_match(): Compilation failed: nothing to repeat at offset 51 (errno=2)

Which looks reasonable, given the regex:

```
<mask>/^[^\x{003c}\x{003e}\x{005b}\x{005d}\x{0024}]*{1,255}$/u</mask> (your code)
<mask>/^[^\x{003c}\x{003e}\x{005b}\x{005d}\x{0024}]{1,255}$/u</mask> (I think you mean this)
```

Best regards,

Ad

**Comment by fraenki** [comment]
Looks like an issue on my side, closing this for now.
