### ISSUE TITLE
firmware: finish the base/kernel upgrades through the firmware

### ISSUE THREAD

**Issue by fichtner** [opnsense/core#137]
Open points; CC @jschellevis @AdSchellevis 

o Do we automatically reboot afterwards?
o Do we need more visual feedback when unpacking the base set? (takes a while,  I know)
o How do we embed a change log that can be viewed prior to upgrading?
o Do we still need the settings page? If so, can we hide it temporarily as it does nothing?
o Something I forgot here.

**Comment by AdSchellevis** [comment]
I think the current upgrade procedure needs some re factoring, but maybe it's best to first make sure we have some anchors in place to minimize the chances of breaking things in the future.
Maybe it's better to wait until our mvc code is in place and activated in the default system, then we could implement clean services for the upgrade stuff.

The way I see it we should have some (simple) service calls to integrate updates, like (for example):
* getAvailableUpdates
* performUpdate
* getStatus
* getChangelog

* getAvailableUpdates should tell the user if there's a reboot required, how to determine maybe a bit tricky at the moment, but it's safe to assume a baseupdate needs a reboot I guess.
* more visual feedback, if we can it's nice. but if it turns into magic, I would leave it as on big step in the process. (but that's my opinion)
* One Idea could be to create a dummy package to implement the systems changelogs which has no dependencies and just copies all changelogs we have in a standard directory. I don't know what other options pkgng has for this.
* The settings page, we may eventually add support for mirrors there, what do you think?

**Comment by fichtner** [comment]
Good stuff, will digest later. Quick question though, does that mean we ought to roll back on the base/kernel update in the GUI upgrade? Just making sure we don't forget to disable it again. :)

**Comment by AdSchellevis** [comment]
I'm not sure I understand what you mean. I think the base/kernel update for the gui part is just an update like any other, although the technique used to perform the action is different.  
So the frontend (or service client) requests what could be done, it tells something like:
squid from version x -> y
joe from version a-> b
base from version d -> e  ( reboot required )
 (in a nicely formed structure :-) )

**Comment by fichtner** [comment]
If you have stability concerns we need to comment out these lines:

https://github.com/opnsense/core/blob/master/src/opnsense/scripts/pkg_upgrade.sh#L48-52

So far testing has been promising, but upgrade dying while upgrading base/kernel might be nasty. Nastier than just a package glitch.

BTW, pkgng is not stable enough to cherry-pick updates of individual packages. The thing that Jos did is correct: update pkg only or all packages at once. Anything else is unstable and leads to inconsistencies. I’m not sure this can be solved.

Other than that you are right. Now the only question is do we fix the GUI like above or do we wait. We can wait, but reading patches notes is hard, and people seem to rely on the GUI far too much. To some degree that’s how it should be, but it creates this tricky situation that may keep base/kernel installations vulnerable or stale.

**Comment by AdSchellevis** [comment]
Sorry, I kind of missed that one. I would leave it in for now, without that reboot it very likely produces issues as well.
Upgrading all at once is probably the safest thing to do anyway, it's quite hard to track dependencies for components I guess. (It wasn't my intention to install parts of the updates)

Maybe it's best to drop in a fix in the current code now, but my only point is that given the current changing environment it's almost impossible not to break things now and then. My response on your question was more of an end solution to the issue, but fixing the current into a better state is always a good idea.

**Comment by fichtner** [comment]
See referenced commit, thanks for the help. :)

**Comment by fichtner** [comment]
I agree with what you said earlier. I don't think we should make a package for changeblogs as that depends on updating the firmware, even if minimally so. It probably needs to be an RSS feed or something similar.... We already have the blog for that, maybe we can reuse it.

On mirrors: yes, that is a tricky one which requires rewrite of the OPNsense.conf file. I can see that OPNsense.conf should rather be OPNsense.conf.sample and is then rewritten via the GUI. It's not only about mirrors but also fingerprint verification for third party repositories or changing between OpenSSL/LibreSSL flavours or for testing. Good idea. I'll ponder a bit about it. :)

**Comment by fichtner** [comment]
Bravely tackled by @AdSchellevis ;)
