### ISSUE TITLE
external config.xml import on boot

### ISSUE THREAD

**Issue by fichtner** [opnsense/core#1372]
FAT32 / one partition (standard Windows layout), always automatically import from install media in this case (and on factory reset).

via: https://forum.opnsense.org/index.php?topic=4394.0

**Comment by EugenMayer** [comment]
That would be actually pretty neat, also during the installer

**Comment by fichtner** [comment]
First step done. Extracted importer code from the installer as a shell script: https://github.com/opnsense/core/blob/974ff9420d99e641f419021f6aa61a4426537d3d/src/etc/rc.importer

**Comment by EugenMayer** [comment]
@fichtner those are cool news, very handy for the cloud appliances GCE/AWS whatsoever, or provisioning with packer

**Comment by mircsicz** [comment]
@fichtner THX for adding it to the Milestone

And as a cross reference: [Forum-Thread](https://forum.opnsense.org/index.php?topic=8987.0;topicseen)

**Comment by EugenMayer** [comment]
its seems like this is not working for me at least. Are there any docs?

Using a MBR or GPT absed MSDOS usb drive with either `config-hostname...xml` or `config.xml` right under root but i get "no prevision configuration was found on device"

**Comment by fichtner** [comment]
it's /conf/config.xml -- opnsense-importer expects a "real system" layout

**Comment by fichtner** [comment]
https://github.com/opnsense/core/commit/245401492 added it to the manual page and the import error message for clarity

**Comment by EugenMayer** [comment]
@fichtner great, thank you! Shouldn't we also add it to https://docs.opnsense.org/manual/install.html since that is what i was actually using to find out (since opnsense-importer --help did not work) .. out of any reason i did not pick man.

Maybe its reasonable to you

**Comment by fichtner** [comment]
Is this a 18.7 image import? I'm getting:

    opnsense-importer --help
    opnsense-importer: illegal option -- -
    Usage: man opnsense-importer

Eventually it should be added to the docs page as well, but may require a bit of effort to split the page... pretty big already so easy to miss this even if on the page.

**Comment by fichtner** [comment]
Fair point. Alias transition was planned for 18.7.0 so that would have aligned with image... I'll try to release 18.7.8 images after that's out... planned for tomorrow so images could follow next week. Will check internally if that makes sense, but it should. :)
