### ISSUE TITLE
let out anything from firewall host itself rules generated incorrectly

### ISSUE THREAD

**Issue by djGrrr** [opnsense/core#1375]
The "to !" networks on the openvpn rules have no basis in reality

It is worth noting that the OpenVPN interfaces that this affects are each assigned to interfaces with ipv4 and ipv6 configuration both set to None, to let openvpn handle all that itself.

> 
> pass out  route-to ( ovpnc5 192.168.16.1 ) from 192.168.16.2 to !192.160.0.0/12 keep state allow-opts label "let out anything from firewall host itself" # this is a /24 not a /12
> pass out  route-to ( ovpnc6 192.168.99.13 ) from 192.168.99.14 to !192.168.0.0/15 keep state allow-opts label "let out anything from firewall host itself" # this is a /32, not /15
> pass out  route-to ( ovpns3 255.255.255.0 ) from 192.168.18.1 to !192.160.0.0/11 keep state allow-opts label "let out anything from firewall host itself" # this is another /24, not /11
> pass out  route-to ( igb0 24.224.x.x ) from 24.224.x.x to !24.224.x.x/24 keep state allow-opts label "let out anything from firewall host itself" # the /24 here is correct

**Comment by fichtner** [comment]
@djGrrr is it working now, or still a bit of trouble reading the ifconfig output?

**Comment by djGrrr** [comment]
@fichtner with #1395, this is now fixed :)
