### ISSUE TITLE
captive portal: group-based login selector

### ISSUE THREAD

**Issue by fichtner** [opnsense/core#1377]
Hi Ad,

This was reported / asked about a few times. Our web proxy has this privilege, but the captive portal one got lost during the transition. It's not so easy to migrate it back, though it should definitely be back eventually.

Maybe we can have a optional setting in each zone to honour the new privilege (off by default to prevent lockout of current installations).

What do you think?

Cheers,
Franco

**Comment by AdSchellevis** [comment]
@fichtner you mean the lighttpd-api-dispatcher.conf ? the cp zones use www

**Comment by fichtner** [comment]
no, system: access: users: privileges

**Comment by AdSchellevis** [comment]
ah, you mean use local groups / user privs as additional auth criteria. The proxy (and ipsec if I'm not mistaken) indeed uses that, but implementation isn't really neat. 

I think it would be better to be able to specify a group which the user should belong to, so we don't need additional acl's with no real meaning.

**Comment by fichtner** [comment]
wrapping the ACL into a group is trivial. we still need the ACL though, group or not. :)
