### ISSUE TITLE
Feature: WebFilter / Squid - Transparent / Non-Transparent per Interface 

### ISSUE THREAD

**Issue by spec1re** [opnsense/core#1379]
Make an option to chose, different transparent mode for each interface.

![grafik](https://cloud.githubusercontent.com/assets/11883076/22683750/63e19b38-ed11-11e6-84cd-b0125720ead8.png)

**Comment by fichtner** [comment]
@spec1re We don't need this selection for the transparent proxy. When you enable the help text, you will see that you can create redirect rules for each interface. It's even more flexible because you can decide how these rules match, not just per interface.

**Comment by spec1re** [comment]
Okay now I see, thank you fitchner.

**Comment by fichtner** [comment]
you're welcome :)
