### ISSUE TITLE
Feature: Captive Portal - MAC, IP address and allowed Hostname.

### ISSUE THREAD

**Issue by spec1re** [opnsense/core#1380]
It would be nice to have those three options additionally for the Captive Portal:

![grafik](https://cloud.githubusercontent.com/assets/11883076/22684189/37efd65a-ed13-11e6-8ce0-2daa4eb88676.png)

with extra bandwidth limits for each client, this is very handy and easier to manage as vouchers and traffic shaping.

**Comment by AdSchellevis** [comment]
timeout due to inactivity
