### ISSUE TITLE
GUI: Entering an IPv6 address in an 'IPv4 TCP/UDP' firewall rule stops FW/Routing

### ISSUE THREAD

**Issue by syserr0r** [opnsense/core#1381]
Tested on OPNsense 16.7.14_2-amd64

Entered in the 'Destination' field of a rule.

I am not proud to have made this mistake :(

**Comment by AdSchellevis** [comment]
@syserr0r nice catch, https://github.com/opnsense/core/commit/f44a60f9b06773a8f649e233f91e3367e61a029d should fix this.
