### ISSUE TITLE
DynDNS: Custom setting not working as expected

### ISSUE THREAD

**Issue by Woi** [opnsense/core#1383]
Bugreport:
Using the DynDNS Custom setting is not working. This might or might not be limited to german hoster Strato. However a workaround exists [2,3]

OPNsense version where bug was found: OPNsense 17.1-i386
OPNsense version where the bug first appeared: unknown
Last OPNsense version where the bug did not exist: unknown
The exact URL of the GUI page involved: https://192.168.1.1/services_dyndns_edit.php

Steps to reproduce:
1. Get a Strato hosting package supporting DynDNS
2. Set up Stratos DynDNS as explained in step 1 on [1] 
3. Set up DynDNS in OPNsense as explained in step 2 on [1] and click on "Save & Force Update"
4. Observe that OPNsense is reporting the DynDNS update as successful
5. Check with the host command of your operation system that the update failed

Actual result:
Hostname is not updated

Expected result:
Hostname is updated

Possible solutions:
* Fix DynDNS Custom settings and/or
* Add Strato to the known DynDNS providers.

Further information information:
[1] https://www.strato.de/faq/article/671/So-einfach-richten-Sie-DynDNS-f%C3%BCr-Ihre-Domains-ein.html
[2] https://forum.pfsense.org/index.php?topic=124141.0
[3] https://forum.pfsense.org/index.php?PHPSESSID=5ljiou06rd5qd4vt60itik29o0&action=search2;params=eJwtj8GOwjAMRP-FC5cRauzYKTf-pCpJJBaVBiVhV0j9-HURt5k3tjWe0--8xpy24-a2w3atH-VBAzy8h0BGMIjACnIghRshBGcigEAMFpDACTiAz_A2a7sCr2BLbRYKsYMjvMUOwhAjATpALSQoQz1UoAo1PkLPCAPCXqrdyt8Uy-O55J6_Rdvres-xT2Vd3oZ2Umqf0k81l3KLX2Ku5iV_ntxRnmu8Gbyk95rWdmq9zr2c7Po_IUdMzQ..

**Comment by Woi** [comment]
The situation improved as of release 17.1.5:
Custom settings are now working with `https://dyndns.strato.com/nic/update?hostname=example.com`, but username and password are taken from the related fields.
However the DynDNS plugin still reports a successful update in log files and on the dashboard when the update actually failed.

**Comment by Woi** [comment]
There is also no AAAA record for the hostname. (Just a FYI. I don't have a glue if this is a problem of Strato or OPNsense.)

**Comment by fichtner** [comment]
Would you mind sharing strato test credentials with me to get this tested internally? Not sure how AAAA is handled here, maybe it only updates A. Only one way to find out. :)

**Comment by Woi** [comment]
@fichtner Sure. I just sent you my contact details via OPNsense forum private message.

**Comment by Woi** [comment]
Strato seems to be able to do IPv6. This is how a freshly created dyndns subdomain looks, before the fist update:

```
host sub.example.com
sub.example.com has address 81.169.145.163
sub.example.com has IPv6 address 2a01:238:20a:202:1163::
sub.example.com mail is handled by 5 smtpin.rzone.de.
```

**Comment by Woi** [comment]
> STRATO Service schrieb:
> [...]
> vielen Dank für Ihr Schreiben. Gerne werde ich Sie in Ihrem Anliegen unterstützen.
> 
> STRATO DynDNS unterstützt bedauerlicherweise keine IPv6-Adressen sondern ausschließlich IPv4-Adressen.
>  [...]
(English: Strato doesn't support IPv6/AAAA-Records for there DynDNS service)

**Comment by fichtner** [comment]
thanks for confirming with them. shall we close this?

**Comment by Woi** [comment]
@fichtner I would close this ticket now. Custom settings improved in 17.15 and patch https://github.com/opnsense/core/commit/a84f3c0 finally makes me happy :)

**Comment by Woi** [comment]
Just saw your comment, while typing :)

**Comment by Woi** [comment]
I missed to say thank you for your wonderful support :)

**Comment by fichtner** [comment]
no, thank you for prodding and testing! :)
