### ISSUE TITLE
17.1 IPsec mobile client: critical docs update needed

### ISSUE THREAD

**Issue by EugenMayer** [opnsense/core#1385]
These docs need updating https://docs.opnsense.org/manual/how-tos/ipsec-road.html

Mandatory changes to be done are:

a) tunnel phase 1, DH must be lvl 14 ( 2048 ) or higher, 1024 is blacklisted under OSX ( at least )

b) phase 2: ensure to mention, that sha256 will not work, while sha256 will work for phase 1 +AES256 - so phase1/phase2 encryptions do differ. For Phase 2 AES only sha1 is possible

c) discussion item: Negotiation mode needs to be "main" otherwise no authentication is possible. @fichtner is smelling something else with this settings - this fix is independent of a) / b) though, a)/b) do still apply, no matter what negotiation mode

d) there is no longer the possibility and according to @fichtner also technically no need to select a user-identifier during tunne/phase 1, while this is still in the description in the docs. This is only needed for site-2-site - just remove that section

Glitches / less critical:
 - One can not set priviledges during the creation of a user ( UI element is missing ) - only during "editing" an user. Not sure this is an UI bug, but should be mentioned in the docs or people probably fail / get confused

**Comment by EugenMayer** [comment]
References:
 - DH2 not working: https://support.apple.com/en-us/HT206154 ( thanks @fichtner )
  -> that meanst, DH5 will also work, not only DH14. But, with SHA256 in phase 2, only DH14 works. We probably should link that topic in the docs

**Comment by EugenMayer** [comment]
b) Sha256 in Phase2 does neither work for El Capitan nor for Sierra

**Comment by abraxxa** [comment]
Are you referring to IKEv2 VPN?
I still haven't gotten my iPhone to connect successfully even after cipher negotiation was successful.
The last few log lines are:

>Feb 10 21:28:04	charon: 07[JOB] deleting half open IKE_SA after timeout
Feb 10 21:27:35	charon: 07[NET] sending packet: from 1.2.3.4[4500] to 5.6.7.8[4500] (368 bytes)
Feb 10 21:27:35	charon: 07[ENC] generating IKE_AUTH response 1 [ IDr AUTH EAP/REQ/ID ]
Feb 10 21:27:35	charon: 07[IKE] authentication of 'fqdn' (myself) with RSA signature successful
Feb 10 21:27:35	charon: 07[IKE] peer supports MOBIKE
Feb 10 21:27:35	charon: 07[IKE] received ESP_TFC_PADDING_NOT_SUPPORTED, not using ESPv3 TFC padding
Feb 10 21:27:35	charon: 07[IKE] initiating EAP_IDENTITY method (id 0x00)
Feb 10 21:27:35	charon: 07[CFG] selected peer config 'con1'
Feb 10 21:27:35	charon: 07[CFG] looking for peer configs matching 1.2.3.4[fqdn]...5.6.7.8[5.6.7.8]
Feb 10 21:27:35	charon: 07[ENC] parsed IKE_AUTH request 1 [ IDi N(INIT_CONTACT) N(MOBIKE_SUP) IDr CPRQ(ADDR DHCP DNS MASK ADDR6 DHCP6 DNS6) N(ESP_TFC_PAD_N) N(NON_FIRST_FRAG) SA TSi TSr ]

**Comment by mimugmail** [comment]
I'm planning a major rewrite, perhaps with a compatibility matrix ...

**Comment by fichtner** [comment]
code is in to support multiple phase 1 proposals at once, @mimugmail will update docs. closing!
