### ISSUE TITLE
Captive Portal IPFW-PF chaining issue on 17.1

### ISSUE THREAD

**Issue by fabianfrz** [opnsense/core#1391]
It seems like PF rules for NAT are applied before IPFW so having rules to send traffic to the proxy will break the captive portal (IPFW). No NAT on PF and using the CP while checking the proxy rules works or using PF rules without the CP works too.

On 16.7 There was no issue with such rules.

**Comment by AdSchellevis** [comment]
tested on my end, and it looks like the new kernel handles these cases differently (http[s] got blocked from the firewall itself).

I was able to get it working again by adding an additional rule for my local address

`ipfw add 60005 skipto 65533 ip from {address} to any`

As soon as I can find some more time I will try to provide a proper fix.
