### ISSUE TITLE
IPSEC IKEv2+EAP-MSCHAPv2 not working with Windows 10(native) and Android strongswan

### ISSUE THREAD

**Issue by cvbkf** [opnsense/core#1393]
Hello, 

this is the continuation of the following thread at the forums: [https://forum.opnsense.org/index.php?topic=4481.0](url)

currently i am using three different pfsense-installations with IKEv2+EAP-MSCHAPv2, which are working perfectly fine with android and windows clients. now i migrated the firewall at my home to opnsense and tried to rebuild the vpn with the same functionality. i used the same settings from my pfsense installation, as long it was possible. e.g. the possibility to configure the peer identifier is missing in opnsense's gui, but opnsense uses %any per default. 
short: it **almost** works. 

it looks like the client is dropped at one of the last steps due to a certificate problem, maybe because of a missing client certificate. the firewall log itself does not show any signs of vpn-related blocked packets, the ipsec tab has an any:any rule.  Windows 10 reports a gateway error 13801: IKE authentication credentials are unacceptable, which is related to some sort of certifcate problems regarding to microsoft. detailed explanation from microsoft can be found here: [https://technet.microsoft.com/de-de/library/dd941612%28v=ws.10%29.aspx?f=255&MSPPError=-2147217396](url)
so i tried with strongswan on android, which provides a more detailed logfile, which is attached. 

the vpn log of opnsense
[opnvpn.txt](https://github.com/opnsense/core/files/766672/opnvpn.txt)

charon.log android strongswan
[charon.log-client.txt](https://github.com/opnsense/core/files/766680/charon.log-client.txt)

comparison of ipsec.conf between pfsense (left) and opnsense (right)
![pf-opn](https://cloud.githubusercontent.com/assets/16870924/22827334/8c32d1c8-ef97-11e6-89bf-a9a1ea72e613.gif)

i can provide more details, if needed. 
opnSense 17.1.1 on Intel Atom D510MO with 3x GbE

**Comment by AdSchellevis** [comment]
@cvbkf I don't have a similar setup available, so lets try to fix some differences which might lead to your issue.

- aggressive = no is the default 
- our leftsendcert is set to standard, I think it's safe to change that to always
- mobike couldn't be disabled, I added the marker to our phase 1 as well
- leftid, I expect the prefix fqdn wouldn't be necessary, automatic conversion should work here.
- rightca, as far as I could see, the ca shouldn't be selected for mschapv2, I have removed it for this scenario, if for some reason this should optional, we can re-add it.

rightsubnet is the result of "virtual address pool" in /vpn_ipsec_mobile.php


I you want to try both patches, you can install them using:

`opnsense-patch 212fd9a 71bc4cb
`
 
Best regards,

Ad

**Comment by cvbkf** [comment]
@AdSchellevis 
thank you for your patches, i applied them to my device successfully. 

bit offtopic: after creating a new phase1 and phase2 configuration a crash report was generated, which happened on plain 17.1.0, too, and is not related to your patches. the report was already submitted by me on friday. 

back on topic: 
the vpn connection from android and windows are now working, your patches fixed the problem. thank you a lot. 
the log file looks good, only this line here is a bit strange
`Feb 12 22:56:38 08[CFG] handling INTERNAL_IP4_SUBNET attribute failed
Feb 12 22:56:38 08[IKE] installing new virtual IP 192.168.199.1`

**Comment by abraxxa** [comment]
That patch made IKEv2 VPN work on iPhone running IOS 10.2.1 as well, thanks!

I received the log message
> charon: 07[IKE] no EAP key found for hosts 'fqdn' - 'username'

first in the log without seeing any EAP authentication on the RADIUS server.
After adding a Pre-shared key of type EAP with my username and password it worked.

Why isn't it forwarding the EAP authentication to the RADIUS server configured in Mobile Clients?

**Comment by abraxxa** [comment]
I just noticed that the 'Split DNS' checkbox value in Mobile Clients isn't saved when the field is left blank although the help text suggests that this is possible and valid.

**Comment by abraxxa** [comment]
I guess I have to set the IKEv2 Authentication method to 'EAP-RADIUS' instead of 'EAP-MSCHAPv2' but this results in

> charon: 06[IKE] loading EAP_RADIUS method failed

**Comment by GurliGebis** [comment]
@abraxxa You need to stop and start the strongswan service for the error message to go away and for it to work.
My guess is that this is related to reloading strongswan does not load the EAP-RADIUS module, so it fails.
That explains why a restart fixes the problem.

**Comment by AdSchellevis** [comment]
@cvbkf thanks for conforming, I also solved your crashreport, I will close this issue now.

**Comment by abraxxa** [comment]
@GurliGebis: thanks, that solved it!
@AdSchellevis: can you either always load the radius module or restart strongswan if required?

**Comment by AdSchellevis** [comment]
@abraxxa no, ipsec.conf handles loading the module and we can't know for sure if a restart is required (we don't know the current running state).
If there are multiple tunnels active, you might want to plan the restart.

**Comment by GurliGebis** [comment]
Just an idea - maybe generating an empty eap-radius section in the config file will make it load the plugin. Could that be the solution?

**Comment by AdSchellevis** [comment]
maybe, but I don't know what the downside is there. I just have limited time available at the moment to change the internals and test it. If anyone could test if this really works, we could consider changing it. 
Another (less time consuming option) could be to display a note when radius is enabled.

**Comment by GurliGebis** [comment]
When I get time, I'll try and see if some of the things mentioned here makes any difference: https://wiki.strongswan.org/projects/1/wiki/PluginLoad

**Comment by cvbkf** [comment]
@AdSchellevis thank you very much for fixing the issue. 

as mentioned by @abraxxa i noticed too that for the (windows) client no dns settings will be applied, dns request will be forwarded to the current networks dns, which isn't reachable after connecting to vpn.

**Comment by AdSchellevis** [comment]
@GurliGebis thanks in advance, if you have a better solution, please open a new issue or pull request so we can keep this one closed.

**Comment by GurliGebis** [comment]
@cvbkf have you configured the DNS servers to use in the phase 2? (I forgot that when I set mine up, and that caused it to be not working).

@AdSchellevis I will :)

**Comment by GurliGebis** [comment]
@cvbkf You have to configure them in the Mobile tab, not the Phase 2 tab - my bad :)

**Comment by cvbkf** [comment]
@GurliGebis 

currently i have dns configured like this: 

`Network List: yes 	
Save Xauth Password: no 	
DNS Default Domain: no 	
Split DNS: no 	
DNS Servers
Server #1: firewall itself Server #2: google Server #3: google
WINS Servers: no	
Phase2 PFS Group: no`

at the moment, the windows client can't access the internet because of dns failure (request goes to unreachable dns of the current network). i'll try something different and report back

**Comment by GurliGebis** [comment]
Good question, I have it working on my end with just the DNS servers defined like that.
I'm not using the firewall as a DNS server - could you try and define an internal IP as the DNS server and see if that works? (external might not work, if traffic from the tunnel is not allowed through to the outside).

**Comment by abraxxa** [comment]
I have defined the internal IP of the firewall as only DNS server and it doesn't work for me.

**Comment by GurliGebis** [comment]
What if you define an internal DNS server running on another machine than the firewall? (Since the issue might be that going from the IPSEC tunnel to the firewall internal IP is blocked)
