### ISSUE TITLE
Feature Request: TCP Syslog

### ISSUE THREAD

**Issue by shezzski** [opnsense/core#1398]
Dear all,
It appears that the Syslog client within OPNsense only supports sending via UDP.  Is it possible to add TCP support with the current Syslog client?  I see this as a benefit for all as its not a corner case feature.

Thanks for your time.

**Comment by AdSchellevis** [comment]
@shezzski I don't think the integrated syslog supports tcp, I couldn't find a reference in the documentation https://www.freebsd.org/doc/handbook/configtuning-syslog.html 
Unfortunately no quick fix in that case ;(

**Comment by fichtner** [comment]
The long run is this... https://github.com/opnsense/core/pull/1206

**Comment by AdSchellevis** [comment]
@fichtner are you sure newsyslog supports forwarding in tcp mode? I couldn't find a reference in the manual nor did I see the implementation for remoteserver in the pull from @evbevz (I probably overlooked it there.)

**Comment by fichtner** [comment]
It would seem so :) https://www.balabit.com/documents/syslog-ng-ose-latest-guides/en/syslog-ng-ose-guide-admin/html/configuring-destinations-network.html

**Comment by shezzski** [comment]
Thanks @AdSchellevis and @fichtner reading through #1206 I was not able to see what syslog software was being used.  Syslog-ng is a good option, but did you compare with rsyslog? I am just interested as I had a bit of exposure to both.

**Comment by AdSchellevis** [comment]
@shezzski I haven't, pulling in 1206 in smaller pieces will take quite some time.

**Comment by shezzski** [comment]
Thanks for the feedback @AdSchellevis.  I am happy to to have this feature request closed.

Regards

**Comment by AdSchellevis** [comment]
timeout due to inactivity
