### ISSUE TITLE
[BUG ]os-vmware pam related problem

### ISSUE THREAD

**Issue by maseron** [opnsense/core#1399]
I installed plugin os-vmware and wanted to execute command using vmWare tools, but I got back the error:
Failed to authenticate with the guest operating system using the supplied credentials.
I know that the credentials are correct.

In system.log I get this error:
vmsvc[86627]: in openpam_sidpatch(): all modules were unsuccessful for pam_sm_authenticate()
vmsvc[86627]: [critical] [vmsvc] Auth_AuthenticateUser:316:PAM failure - system error (4)

What I can do to solve this problem?

**Comment by maseron** [comment]
There is no such problem with plain FreeBSD 11, just now tested it.

OpnSense is the latest version - 17.1.1.

**Comment by fichtner** [comment]
@maseron does it work if you enable "Disable integrated authentication" under System: Settings: Administration?

**Comment by maseron** [comment]
Thank You! That fixed the problem and saved my day :-)

**Comment by fichtner** [comment]
Not so fast :D

We've switched 17.1 to integrated authentication. Do you have any idea which credentials VMware is using here? Do you use 2FA for the GUI authentication?

**Comment by maseron** [comment]
In my case VMware uses root user and password what I provide. 
I do not use 2FA for GUI.

**Comment by fichtner** [comment]
Thanks. It should still work if the passwords match for the GUI login. The system disables the root password, but PAM would still work.

Unless... https://github.com/opnsense/ports/blob/master/emulators/open-vm-tools/files/patch-scripts_linux_pam.d_vmtoolsd

VMware tries to authenticate against pam_unix, not system. oO

**Comment by fichtner** [comment]
Hi @maseron,

I have a test package here that may work with and without integrated authentication. Would you mind trying it?

    # pkg add -fA https://pkg.opnsense.org/snapshots/open-vm-tools-nox11-1280544_17,1.txz

You can change back to the old package by doing this:

    # pkg install -Af open-vm-tools-nox11


Thanks,
Franco

**Comment by fichtner** [comment]
@maseron on 17.1.2 we have a fix for enabled integrated authentication. would you mind trying it so this can be closed? thanks! :)

**Comment by maseron** [comment]
Hi, sorry for not replying. Upgraded to 17.1.2 and now customization works
also when the "Disable integrated authentication" checkbox is unchecked..
Thanks.

**Comment by fichtner** [comment]
no worries. cool, I'll try to get this also into FreeBSD ports. Closing. :)
