### ISSUE TITLE
[BUG] Firewall does not respect flag to use local resolver for its own resolution

### ISSUE THREAD

**Issue by phpb-com** [opnsense/core#1401]
When DNS Resolver is configured, and flag "Do not use the DNS Forwarder/Resolver as a DNS server for the firewall" is unchecked, firewall still populates its own /etc/resolve.conf with the IPs of forwarders.

**Comment by phpb-com** [comment]
Forgot to mention that I am on the latest version, 17.1.1

**Comment by djGrrr** [comment]
I think you may be misunderstanding what this setting is for, it simply removes:
nameserver 127.0.0.1
from resolv.conf when checked, ie, don't use the local DNS Forwarder or DNS Resolver services to resolve dns on the firewall, use only upstream servers.

**Comment by phpb-com** [comment]
I do understand this part, and observed that resolve.conf is not affected by this setting in any way.

**Comment by djGrrr** [comment]
OK, that is strange, I tested this setting when I saw this issue, and it works perfectly fine for me.
Do you happen to have 127.0.0.1 in the dns server list just above this setting?

**Comment by phpb-com** [comment]
I do not have localhost in there, the reason I noticed is when I played with OpenDNS filter, local network hosts stopped being resolved by the firewall. Even later after disabling that, I still could not get the resolve.conf to populate with localhost settings. Do I need to maybe restart the resolver service or to trigger reconfiguration of it? I am not sure which setting is responsible for making this modification. Also, note that I use DNS resolver (unbound)

**Comment by djGrrr** [comment]
I am not sure what would cause this, you only need to apply the settings under system>settings>general with the option "Do not use the DNS Forwarder/Resolver as a DNS server for the firewall " un-ticked for it to show back up in /etc/resolv.conf

**Comment by phpb-com** [comment]
I just tried that again, and still see that it is not updated with the local host information. In DNS server settings I have configured 2 servers and that is all that I see in resolve.conf. Also tried to reconfigure DNS Resolver, still no luck.

**Comment by fichtner** [comment]
Did you set manual interfaces for unbound/dns resolver? If yes, do you have loopback in your selection?

**Comment by phpb-com** [comment]
I do have interface manually selected, that is right. But I also do not see loopback in the menu for selection. Selecting "All" does fix the issue and I see localhost in resolve.conf.

**Comment by fichtner** [comment]
This should do the trick:

    # opnsense-patch b3ed2232

**Comment by phpb-com** [comment]
Thanks, that will definitely help.

**Comment by phpb-com** [comment]
Just tested the patch, and it did do the trick. Thanks again fro a quick fix.

**Comment by phpb-com** [comment]
This fix introduced one problem that I mentioned in #1400 , it registers loopback interface (::1, 127.0.0.1) in as a valid RR for firewall hostname. This will happen if you choose specific interfaces to listen on and if Loopback interface is selected to allow for firewall to use the resolver.

**Comment by fichtner** [comment]
Maybe we simply prevent the loopback from being written here at all?

**Comment by phpb-com** [comment]
I would say so, I do not think that registering "lo0" addresses in DNS Resolver needed or desired.

**Comment by fichtner** [comment]
I think that's all: 03170898cafd5cb5f

**Comment by phpb-com** [comment]
Clean and simple, thanks. Checked the change and it works as expected.

**Comment by fichtner** [comment]
Brilliant, thanks for testing! Since builds for 17.1.2 start about now, these fixes won't make it in time, giving them another round on the -devel package for final inclusion in 17.1.3.
