### ISSUE TITLE
Bug: Syslog Source Interface not working as intended

### ISSUE THREAD

**Issue by shezzski** [opnsense/core#1402]
Hi devs,

I have been trying to configure syslog on OPNsense 17.1.1 to point to a central syslog server and I have been having great difficulties with the syslog "Source Address" setting under "Remote Logging Options".

I have a number of interfaces on my firewall:
1. WAN
2. LAN
3. DMZ
4. OpenVPN <- not strictly an interface listed under "Interfaces" in the web GUI.

I have the "Source Address" configured to be the LAN address, but for some reason the OpenVPN interface is seen on syslog entries on my syslog server coming from the firewall.

What I do find strange is that sometimes the firewall decides to use the LAN address so it has me baffled. 

My first thoughts is that there is some race condition when the service starts and the OpenVPN is the first interface that is ready.

I understand that the syslog service is getting an overhaul with #1206 and I am merely wanting to report this bug for the benefit of others with the same problem.

Regards,

**Comment by AdSchellevis** [comment]
timeout due to inactivity
