### ISSUE TITLE
Enhancement Request: Unbound 1.6 - Serve Expired

### ISSUE THREAD

**Issue by willjones** [opnsense/core#1405]
As we move up to unbound 1.6 it would be pretty nice to have a GUI option for the following feature:

       serve-expired: <yes or no>
              If  enabled,  unbound attempts to serve old responses from cache
              with a TTL of 0 in the response without waiting for  the  actual
              resolution  to  finish.  The actual resolution answer ends up in
              the cache later on.  Default is "no".

http://unbound.net/documentation/unbound.conf.html

This, when used with pre-fetching on a busy recursor can be quite nice in case the upstream authoritative server for a domain is not reachable- if we cast our minds back to a few months ago when Dyn was the subject of a massive DDoS attack having this available and enabled might have cushioned the impact for some people without resorting to forwarding all your queries to someone like OpenDNS who are doing something similar on their caches.

**Comment by fichtner** [comment]
Done, want to test this? :)

**Comment by fichtner** [comment]
Landing in 17.1.3.

**Comment by chrcoluk** [comment]
brilliant feature thanks for it, as prefetch is only reliable when the resolver is extremely high traffic.
