### ISSUE TITLE
Results paging broken

### ISSUE THREAD

**Issue by tkald** [opnsense/core#1407]
On page Intrusion Detection - alerts tab, result pages links and page size selector do not cooperate.
If I select to show 1000 records, paging links are still calculated with default (7) sets.
Also link to last page does not lead to the last page.

v17.1

**Comment by AdSchellevis** [comment]
@tkald the result count is always a guestimate, can't fix this without actually parsing the whole file on every request. more info https://github.com/opnsense/core/issues/756
