### ISSUE TITLE
Loading 16.7 config in 17.1 leads to broken system. Broken after upgrade

### ISSUE THREAD

**Issue by pgassmann** [opnsense/core#1409]
First after the update (from ssh) the system did not come up. Debugging with serial console did not get far.
Then I installed 17.1 from image and restored the configuration file from before (16.7) and got the same state (config loaded > reboot > broken).

Unexpected behaviour:
- No Networking on any interface
- On Serial console: no OPNsense menu. Direct access to FreeBSD shell, login: root, no password required.
- opnsense-bootstrap command returns "Requires FreeBSD 10.x"

Hardware: Deciso OPNsense Dual A10 DC Rack https://www.deciso.com/product-catalog/OPN20321R/

**Comment by pgassmann** [comment]
How can I see what goes wrong to provide more detailed information? Are there any logfiles that could be helpful?

**Comment by AdSchellevis** [comment]
@pgassmann what installer did you use? opnsense-bootstrap isn't the normal install procedure.
In case you would like to reinstall the device, it's probably best to use the normal serial installer (https://pkg.opnsense.org/releases/17.1/OPNsense-17.1-OpenSSL-serial-amd64.img.bz2) and import the config after the first successful boot. 

Installation instructions can be found here https://docs.opnsense.org/manual/install.html?highlight=install

**Comment by pgassmann** [comment]
@AdSchellevis Yes, i used this installer. After successful installation of 17.1, i loaded the configuration saved from 16.7 and then it rebooted and did not come back up.

This I did after i tried to upgrade the system. After the upgrade, opnsense did not come back up.

In both cases I could access the shell via serial console. There I found the opnsense-* commands of which i tried opnsense-bootstrap to see if i perhaps i can get the system to start again properly. opnsense-bootstrap returned "FreeBSD 10.x required".

**Comment by AdSchellevis** [comment]
@pgassmann ok, that's weird, doesn't sound familiar to me. If you can send me the configuration I can check if there's anything unusual in it. I haven't seen a similar issue before.

My email adres is ad at project domain.

**Comment by pgassmann** [comment]
will check what I can send. Would need to clean some sensitive information and secrets. Probably I cannot send the configuration.

Can you tell me which log files etc I could look at to debug what went wrong? I am familiar with Linux, but not FreeBSD.

**Comment by AdSchellevis** [comment]
It's best to connect a serial cable, startup your terminal program an watch the boot sequence first, not all is easily found in the logs.
Then the bootup dmesg can be found here : /var/log/dmesg.boot 

Next inspect if syslog is actually running, (ps fax | grep syslog), if that's the case you can inspect system.log using:

`clog /var/log/system.log
`

**Comment by fichtner** [comment]
If the system successfully updated to 17.1 opnsense-bootstrap cannot return "FreeBSD 10.x required" anymore so I am guessing the update went south.

We know of a bug with locked packages where this can lead to partial upgrades. Or people running upgrade sequences manually, which does not work on release versions prior to 16.7.14_2.

How should we proceed? From my POV the update wasn't completed properly and we either need to inspect the system or the system has already been redone and there is nothing to inspect?

**Comment by fichtner** [comment]
Feel free to reopen with more info. For now there is nothing we can do here.

**Comment by pgassmann** [comment]
Thank you. I tried again and was successful with the upgrade. I cannot say what I did differently. Sorry for the trouble and thanks for your work.

**Comment by fichtner** [comment]
@pgassmann thanks for checking back + glad to hear :)
