### ISSUE TITLE
Support for custom LDAP layouts

### ISSUE THREAD

**Issue by tbe** [opnsense/core#1412]
At the moment, it is not possible to sync users from LDAP if the User-DN is not "cn=Users".

In our LDAP tree, all users are under "ou=people". This works well for VPN and LDAP, but not for local login on the OpnSense appliance. 

It should be possible for the user to define the users and groups DN. Currently "cn=Users" is hardcoded.

https://github.com/opnsense/core/blob/0d104a9d790e31e5c18b0ff08e36ef151c26d48a/src/opnsense/mvc/app/library/OPNsense/Auth/LDAP.php#L340

**Comment by fichtner** [comment]
The code spot does an OR type search for either ou=* or cn=Users. Have you tried changing the line to verify that this is the underlying problem?
