### ISSUE TITLE
Missing var in make.conf produces warnings

### ISSUE THREAD

**Issue by speed47** [opnsense/core#1414]
When building any program from the ports tree, A warning appears at the beggining of the build process (I'm running OPNsense 17.1.1):

```
root@fw:/usr/ports/net/mosh # make install
/!\ WARNING /!\
You have security/openssl installed but do not have DEFAULT_VERSIONS+=ssl=openssl set in your make.conf
```

The build still proceeds correctly, but it seems the build system is expecting to be told which SSL flavor we're running. I'm running the OpenSSL build of OPNsense as detected, and adding the aforementioned line in my `/etc/make.conf` does fix the issue.

Maybe the install of OPNsense should ensure the proper line is there? Especially as we also do have a LibreSSL flavor?

**Comment by fichtner** [comment]
# opnsense-code tools

That should fix it on 17.1.1?

**Comment by speed47** [comment]
It sure does! Sorry for the noise :)

**Comment by fichtner** [comment]
No problem. The symlink is relatively new. I will document it in the to be updated development workflow. 😊

**Comment by speed47** [comment]
That would be great :) Thanks!
