### ISSUE TITLE
[CLEANUP] Split dyndns update class into one class per service

### ISSUE THREAD

**Issue by fabianfrz** [opnsense/core#1420]
File: /src/etc/inc/dyndns.class

one abstract base class with the logic and service classes, which hold the data for a specific service (for example update URL, post data template)

**Comment by fichtner** [comment]
I like this, especially for pluggable dyndns... but let's please start by making dyndns a full plugin?

**Comment by fabianfrz** [comment]
@fichtner for now, keep it as it is - maybe an idea for 17.7 - otherwise it may break installations. The code is not very beautiful at the moment (there are a lot of case statements and the file is quite long).

**Comment by fichtner** [comment]
Still some work to do, but this is a good start without all the complexity of the core system: https://github.com/opnsense/core/commit/e8b996802920f0f369c2ddb70dc40c4e29a609d9

**Comment by fichtner** [comment]
We could even make /usr/local/etc/inc/plugins.inc.d/dyndns/ a pluggable directory in the long run given that we create an interface and deduplicate as much as possible.

**Comment by Woi** [comment]
This is related to DynDNS: Custom setting not working as expected #1383

**Comment by fichtner** [comment]
@Woi There are a bunch of fixes coming to 17.1.5. Can you let me know if the problem persists after 17.1.5? See the larger stable backport... https://github.com/opnsense/core/commit/0077ff23a65bfeb9fb81b347f9b9159ad51b0c4c

**Comment by Woi** [comment]
@fichtner I'll do.

**Comment by Woi** [comment]
@fichtner See: https://github.com/opnsense/core/issues/1383#issuecomment-297843259

**Comment by fichtner** [comment]
some work here https://github.com/opnsense/core/commit/12810d94 https://github.com/opnsense/core/commit/bb80ad02961b9a43844bf26aa1ef989db60cbab6

Ideally, we'd not need a lot of custom glue for most things, a parsable URL like here would be golden:

https://github.com/openwrt/packages/blob/master/net/ddns-scripts/files/services

**Comment by Woi** [comment]
@fichtner I assume your last comment is more a FYI then a request to test. Just give a shout if you need some testing.

**Comment by fichtner** [comment]
@Woi yes, just a FYI... I think we'll pick up Dynamic DNS after 17.7 is out and migrated to packages

**Comment by fichtner** [comment]
If anybody wants to work on this, feel free to let me know. From core perspective we have bigger issues to work on, dnydns works pretty well.
