### ISSUE TITLE
Serial console freezes on APU2

### ISSUE THREAD

**Issue by net147** [opnsense/core#1424]
After writing OPNsense-17.1-OpenSSL-serial-amd64.img to a USB flash drive and installing to mSATA SSD on APU2, booting OPNsense results in a hang before it can display the "login:" prompt.

It starts to print the line "FreeBSD/amd64 (OPNsense.localdomain) (ttyu0)" very slowly but fails and then repeats the process of printing the line again. It never gets the "login:" prompt. You can login using the web interface though.

I am using 115200 8N1 for the serial console.

**Comment by net147** [comment]
Installing all updates to upgrade to 17.1.2 changes the Primary Console in System > Settings > Administration to "VGA Console". After changing to "Serial Console" it starts trying to display the login  prompt but fails as mentioned above.

**Comment by fichtner** [comment]
This doesn't sound normal. Is your BIOS up to date, have you double-checked with an older image?

**Comment by net147** [comment]
BIOS is 3/7/2016. Newer BIOS version adds iPXE which I don't need. Console login is working with latest pfSense and LEDE distributions.

**Comment by fichtner** [comment]
Ok, knowing about other distros is nice, but doesn't help us diagnose. I need to know of 16.7 serial images are different. :)

**Comment by net147** [comment]
Works fine on 16.7 if I Ctrl-C after it boots to installer on USB. Shows login prompt and can login as root.

17.1 USB boots straight to login prompt and freezes.

**Comment by fichtner** [comment]
without a password? what kind of serial are you using? built-in or usb?

**Comment by net147** [comment]
Yes, I enter root user and press enter so logs in on 16.7 booted from USB without password. Physical RS-232 port on apu2c4 board exposed through chassis connected using serial cable to FTDI USB-serial adapter on Windows running PuTTY at 115200 8n1.

**Comment by fichtner** [comment]
Alright, the password-less login is the FreeBSD standard, not the one we use, which brings us a bit closer, but still not quite.

There's a full walk through (in German) for the APU.2C4 here also using Putty: https://forum.opnsense.org/index.php?topic=3528.0

Would you mind going through it to see where things don't work as expected for you?

**Comment by net147** [comment]
Any interaction before the login prompt works fine. I can press keys for manual interface assignment or go through installer process. It is just as soon as it gets to login prompt it freezes.

**Comment by fichtner** [comment]
This should have be tested on released images for 17.1.4 and 17.7-RC1 (this week). Feel free to reopen. Thanks!
