### ISSUE TITLE
mail-aware system spamming from cron

### ISSUE THREAD

**Issue by speed47** [opnsense/core#1426]
On a default OPNsense install, the system is unable to send e-mails, which is perfectly okay. I however needed it to be able to send e-mails because that's how `arpwatch` sends notices of new MAC addresses detected, using the standard UNIX `/usr/lib/sendmail` mechanism.

So I installed `opensmtpd`, `mailx` and `mailwrapper`, and the system is now able to transmit locally-generated e-mails to the outside world. I also aliased root's e-mail to my own.

That's when I started to get flooded by e-mails originating from root's cron, several dozens per hour. On a default install the system is muted in the sense that cron doesn't find any way to send e-mails so it silently discards them all. Some examples follow.

```
From: Cron Daemon <root@fw.home>
To: root@fw.home
Subject: Cron <root@fw> /usr/local/sbin/ping_hosts.sh

CARP interface is MASTER or non CARP (pinging ipsec hosts)
```

```
From: Cron Daemon <root@fw.home>
To: root@fw.home
Subject: Cron <root@fw> /usr/local/etc/rc.expireaccounts

1
User speed expires 
1
User test expires 
```

This is clearly just the stdout of the cron'ed scripts, some of them even sounding like debug output, and nothing really worth receiving by e-mail. I would however expect cron to send out an e-mail about a failure or a problem in a script (thru its stderr). To mitigate this, I have been merging a one-line patch after each OPNsense update since the past 6 months so that it does exactly that in `system.inc`:

```
-        $cron_item['command'] = $command;
+        $cron_item['command'] = "$command >/dev/null";
```

With this patch, the generated cron lines discard the scripts stdout, and only keep their stderr to be sent by e-mail if not empty (I've never received any in 6 months, by the way).
I'm not sending a PR as of now, because as this behavior is hidden on default mail-less installs, it might not be considered as a bug. However I would expect most other sysadmins to consider this an oddity after making their system mail-aware.

I'm leaving the close-bug or ask-for-PR decision to the project maintainers :)

**Comment by fabianfrz** [comment]
I have not worked on cron on OPNsense yet but it would make sense to put the command into brackets like this:
```php
$cron_item['command'] = "($command) >/dev/null"
```

The reason to do this is that it is possible to chain commands in cron like in a shell script and this way the output redirection would apply to all commands and not only the last one.

**Comment by AdSchellevis** [comment]
I moved the redirect to the template generation, other then that it should do wat @fabianfrz suggested now.
