### ISSUE TITLE
Two Factor Authentication :  Disable Fallback

### ISSUE THREAD

**Issue by bigops** [opnsense/core#1433]
The two factor authentication in OPNSense even though works fine is somewhat broken for most scenarios.  The TFA requires a fallback option which is Global and not set at per user / group level.  So while fallback for a root account is is a desirable option, the fallback feature to the local database defeats the purpose of TFA for regular users.  Disabling the fallback affects the root user also making the WebGUI inaccessible unless reset from the console.  

Request to enable per user / group configurable fallback where fallback is enabled for root but disabled  for all other users

**Comment by AdSchellevis** [comment]
You can always choose to enable ssh with a pub/priv key combination as fallback for emergencies if a general fallback is not desired. 
A per user override is not a feature we're considering at the moment.
