### ISSUE TITLE
Allow alias for alias ports

### ISSUE THREAD

**Issue by Tragen** [opnsense/core#1436]
I can create an alias Test with different alias hosts inside.
But I cannot create an alias Test with all alias ports inside. When I start typing, I get the name of all alias ports I have created. But I cannot save this alias.
Is this is by design, you shouldn't show alias ports drop down.
If not, please allow to save it. It would make firewall rules much easier.

**Comment by AdSchellevis** [comment]
@Tragenit it's a bug, https://github.com/opnsense/core/commit/8d00e4885797c28aff8c1b55bdc0cc5161623860 should solve it

**Comment by Tragen** [comment]
Very nice for the fast fixes. Thanks.
