### ISSUE TITLE
Captive Portal: save database on /root/var when /var is in memory to keep sessions on reboot

### ISSUE THREAD

**Issue by QuentinC** [opnsense/core#1437]
Hello,

I've experienced some unexpected behavior with Captive Portal when using /var in memory.
On restart, all sessions are lost.

It's not a huge problem for the moment, because I don't use vouchers yet. But I plan to use them and I would like to have persistent sessions upon reboot.

I need to have /var in memory as I'm using an SSD that I don't want to ruin...

I thing that it will just require to add the /var/captiveportal/captiveportal.sqlite here:
https://github.com/opnsense/core/blob/ce32fb747b124b0efaa96187db39ac47728efe5c/src/etc/rc#L168 

If you want me to test some commit just contact me !

Thanks,

Quentin Canel

**Comment by fichtner** [comment]
Hi Quentin,

/var MFS is a trade-off between backup frequency and still writing the SD card for the backups... Nowadays you can set /tmp MFS and skip /var MFS. /tmp is where the most writes are, if you're not running an IPS at the same time. ;)

We could also add backup helpers for the captive portal session database, though we've also seen database corruptions stemming from backing up partial sqlite databases during write operations.

What do you think?


Cheers,
Franco

**Comment by QuentinC** [comment]
Hi @fichtner , 

First of all, thanks for your quick reply !
To be quite honest, I'm not sure that my opinion is really relevant. I'm not an expert of FreeBSD, and no more of storage weakness.

Of course, right now I've just selected /tmp MFS, and it works perfectly !
But I'm thinking about writes likes log files that can write a huge amount of data to /var, and I'm gone to the conclusion that it would be preferable to use /var MFS too.

Anyway, aside from my case, I thing that Captive Portal sessions should be saved in some persistent storage. One solution is to link the sqlite database to /root/var (as for other part of /var that are persistent when using MFS), or another solution is to change the Captive Portal script to let it look elsewhere for its database.

Thanks,

Quentin

**Comment by fichtner** [comment]
So let's try it. I'll add the scripts soon and let you know to give it a test run, ok?

**Comment by QuentinC** [comment]
Thanks ! I'd be glad to do that !

**Comment by djGrrr** [comment]
@fichtner to avoid sqlite db corruptions, you could use the sqlite3 command with .backup in order to do a proper backup.

> sqlite3 /file/path/database.file ".backup /backup/path/database.file"

**Comment by fichtner** [comment]
@djGrrr nice, does this lock the db and copy it without meddling with the applications that use the database normally?

**Comment by djGrrr** [comment]
Other applications will be able to read from the db as normal while the backup operation is in progress, I am not totally sure about writing, but I do know that it won't lock out writing, at worst it will delay the writes until the backup is finished.

**Comment by djGrrr** [comment]
I could be wrong about the writes:
http://www.sqlite.org/backup.html

Either way, reading is allowed during the backup, and I doubt that a write-lock would be much of an issue, I would expect the size of the Captive Portal db to be relatively small?

**Comment by fichtner** [comment]
@QuentinC @djGrrr how about this? applies on top of 17.1.2:

    # opnsense-patch 156f8d4

**Comment by QuentinC** [comment]
I've just applied the patch.

I currently have one device connected. I've set the configuration option on "1 hour".

I will wait and come back to you after some system reboots !

Thanks,

Quentin

**Comment by QuentinC** [comment]
Hello Franco,

The first cron was missed. The error is that the file "/usr/local/etc/rc.backup_captiveportal" wasn't set to be executable.

I've changed the chmod and launched it by hand. 
After the reboot, sessions were lost. But the backup were correct.

After restoring by hand (`cp /conf/captiveportal.sqlite /var/captiveportal/captiveportal.sqlite`), sessions were back.

I will try to investigate on it if I can find some time !

Thanks, 

Quentin

**Comment by fichtner** [comment]
Hi Quentin,

Oh, I didn't know opnsense-patch doesn't take care of the executable flag but that's obviously problematic. Sorry and nice catch!

The backup also triggers on a GUI-triggered reboot or shutdown. The cron job is only additional to guard against unexpected power loss.


Cheers,
Franco

**Comment by QuentinC** [comment]
Hi Franco !

You are missing `mkdir /var/captiveportal/` before doing the cp of the backup file when restoring !

Here is my file:
```
#!/bin/sh

BACKUPFILE="/conf/captiveportal.sqlite"
BACKUPDB="/var/captiveportal/captiveportal.sqlite"

if [ "${1}" = "restore" ]; then
        if [ -f "${BACKUPFILE}" ]; then
                mkdir /var/captiveportal/
                cp "${BACKUPFILE}" "${BACKUPDB}"
        fi
else
        if [ -f "${BACKUPDB}" ]; then
                sqlite3 "${BACKUPDB}" ".backup ${BACKUPFILE}"
        fi
fi
```

**Comment by fichtner** [comment]
Right thanks. Slightly different approach for later reuse went in as 052745d3b67f,

**Comment by fichtner** [comment]
@QuentinC do you think we can close this and merge into 17.1.3?

**Comment by QuentinC** [comment]
Yes absolutely. It has been working perfectly for me since your patch ! 
My sessions survived several restart without any issue !

Thanks !

**Comment by fichtner** [comment]
Thank you for idea + testing! I'm closing this and merge to 17.1.3.
