### ISSUE TITLE
Creating host alias instead of port alias gives load error

### ISSUE THREAD

**Issue by Tragen** [opnsense/core#1440]
I've tried to create a port alias with port 16663 but I clicked on host and entered 16663.
I could save it, but I get errors that I cannot load "table { 16663 }".
Afterwards I wasn't able to change from host to port. Had to delete the alias and recreate it as a port.
Perhaps don't allow numeric values only in host or ask if you want to save it.

**Comment by fichtner** [comment]
could this be an issue with pf wanting to parse a number expecting a host string? quotes could help here... 16663 should be a valid host name

**Comment by fichtner** [comment]
Feedback timeout.
