### ISSUE TITLE
mvc: strict types in POST cause save error?

### ISSUE THREAD

**Issue by fichtner** [opnsense/core#1442]
Working on the IPS rules and toggling a ruleset seems to cause empty values to be posted from a hidden dialog, which breaks boolean type:

<img width="854" alt="screen shot 2017-03-01 at 9 30 38 am" src="https://cloud.githubusercontent.com/assets/1915288/23451812/d84be044-fe61-11e6-9da7-0552d7b922a5.png">

Also, proxy seems to have issues I can't pin down:

<img width="809" alt="screen shot 2017-03-01 at 9 32 38 am" src="https://cloud.githubusercontent.com/assets/1915288/23451850/123b537a-fe62-11e6-8c03-91871e7c3a2c.png">

Any ideas?

**Comment by fabianfrz** [comment]
Hey Franco, @rails has a solution for that: You need to create a hidden input with the value when unchecked. After that, a normal checkbox exists, which has the same name. If it is checked, it will overwrite the previous value in the hidden field. A checkbox is usually not sent when it is not checked.

I hope that this info can help you.

**Comment by fichtner** [comment]
Hi Fabian, well the type checking behaviour was added yesterday so I'm just recording this info here. Not sure which way to go, I think Ad will know best. :)

**Comment by AdSchellevis** [comment]
@fichtner thanks for testing, I will look at it asap.

**Comment by AdSchellevis** [comment]
@fichtner it seems like I can;t reproduce it easily, can you capture the response data from the web form?

**Comment by fichtner** [comment]
<img width="831" alt="screen shot 2017-03-01 at 11 32 07 am" src="https://cloud.githubusercontent.com/assets/1915288/23456218/ce8ec6aa-fe72-11e6-86f7-12926f5b62c2.png">

Response is:

{"errorMessage":"[OPNsense.IDS.IDS.general.enabled] value should be a boolean (0,1)\n[OPNsense.IDS.IDS.general.ips] value should be a boolean (0,1)\n[OPNsense.IDS.IDS.general.promisc] value should be a boolean (0,1)\n[OPNsense.IDS.IDS.general.syslog] value should be a boolean (0,1)\n"}

Does this help?

**Comment by AdSchellevis** [comment]
maybe, does your config contain anything for OPNsense.IDS.IDS.general ?

**Comment by fichtner** [comment]
No, it should have been OPNsense.IDS.general et al, these values are available. I tested against stable/17.1, it's not problematic there.

**Comment by AdSchellevis** [comment]
ok, that's strange. Even without a general section, I can't seem to reproduce this. my changes shouldn't impact this one, because it has no payload.
Can you dump the general section of your IDS config here? normally it shouldn't revalidate, because there are no changes there.... but maybe somethings off.

**Comment by fichtner** [comment]
Triggering rule sets doesn't generate this error for you? (enable selected)

Section looks normal:

```
1945       <general>                                                                 
1946         <enabled/>                                                              
1947         <ips/>                                                                  
1948         <promisc/>                                                              
1949         <interfaces>wan</interfaces>                                            
1950         <UpdateCron>ee9888a6-5a5f-4d71-b4d5-c9e206cc33cf</UpdateCron>           
1951         <AlertLogrotate>W0D23</AlertLogrotate>                                  
1952         <AlertSaveLogs>4</AlertSaveLogs>                                        
1953         <MPMAlgo>hs</MPMAlgo>                                                   
1954         <syslog/>                                                               
1955       </general>                                                                
1956     </IDS>                                                                      
1957   </OPNsense> 
```

Saving the general dialog is ok too...

**Comment by AdSchellevis** [comment]
@fichtner nope, it doesn't look normal...

<general>
        <enabled>0</enabled>
        <ips>0</ips>
        <promisc>0</promisc>
        <interfaces>wan</interfaces>
        <UpdateCron/>
        <AlertLogrotate>W0D23</AlertLogrotate>
        <AlertSaveLogs>4</AlertSaveLogs>
        <MPMAlgo>ac</MPMAlgo>
        <syslog>0</syslog>
      </general>

**Comment by fichtner** [comment]
Funky, did this jut now...

Setting enabled: <enabled>1</enabled>
Unsetting enabled: <enabled/>

**Comment by AdSchellevis** [comment]
Ok, found it.... it fails at saving the general section ;)

**Comment by AdSchellevis** [comment]
@fichtner can you try https://github.com/opnsense/core/commit/f54260277af5fdb9a31c8932db8b0107e7a0dd44 ?
(save general form again)

**Comment by fichtner** [comment]
Looks better, thanks!

Will post web proxy debug info later, no more time at the moment.

**Comment by fichtner** [comment]
(quick save in web proxy didn't solve this as with IPS)

**Comment by AdSchellevis** [comment]
As soon as you have some time, can you post the request/response for this one too? Maybe a parameter got damaged before and isn't rewritten.

**Comment by fichtner** [comment]
```
{"result":"failed","validations":{"proxy.forward.acl.remoteACLs.blacklists.blacklist.909195a7-01a4-41d8-bd74-82e698b5daf8.sslNoVerify":"value should be a boolean (0,1)"}}
```

This is a bit of a pickle. Easily fixed by resaving the blacklist entry, but impossible to find for a normal user.

**Comment by AdSchellevis** [comment]
@fichtner sorry about that, this was already the case, my latest patch only saved the wrong value resulting in this ;(
Maybe we should add a "debug" option in the dialog to show the actual response message.... if the setting isn't on screen, it's indeed difficult to spot.

**Comment by fichtner** [comment]
Like the API error, yes, that would already help.

I'd rather keep this new POST stuff on -devel for a while, maybe we can thing of a smoother migration strategy before it hits 17.1.x.

In any case, I do like this new strictness, just looking out for problematic user experience.

**Comment by AdSchellevis** [comment]
yes, your right, we should keep this for a couple of weeks on -devel. I will add a debug option in the dialog asap.

**Comment by AdSchellevis** [comment]
ok, this should help https://github.com/opnsense/core/commit/39628cd7f3cb25c3b7dad5e3108f513cee783877
![image](https://cloud.githubusercontent.com/assets/9783985/23474052/b61659a4-feb2-11e6-87d4-30f8ad9f5652.png)

![image](https://cloud.githubusercontent.com/assets/9783985/23474038/ab1cf59e-feb2-11e6-9f59-fba6ef5116b1.png)

**Comment by fichtner** [comment]
LGTM, thank you very much :)
