### ISSUE TITLE
Cannot create alias called "printer"

### ISSUE THREAD

**Issue by Signum** [opnsense/core#1443]
OPNense version: OPNsense 17.7.a_86-amd64 / FreeBSD 11.0-RELEASE-p8
The exact URL of the GUI page involved: /firewall_aliases_edit.php

Creating a host alias with name "printer" leads to this error message:

    The following input errors were detected:
    The alias name must be less than 32 characters long and may only consist of the characters a-z, A-Z, 0-9, _.

Naming the host "printerr" (with two "r") works though.

![547_auswahl](https://cloud.githubusercontent.com/assets/36562/23458943/7ffef026-fe7e-11e6-99c0-de5b4f49d082.png)

**Comment by fichtner** [comment]
Internal aliases do not permit the use of reserved keywords words. the list is not displayed. E.g. "printer" is a system alias for 515/tcp defined in /etc/services.

I am not sure if displaying hundreds of reserved words is helpful. Open for ideas.

**Comment by Signum** [comment]
How do host or network names possibly conflict with system service names internally?

**Comment by fichtner** [comment]
the "use case" is likely a weak modelling between aliases and real ports to forcefully avoid clashing definitions of a "printer" alias with the actual port "printer"... relevant code comment:

https://github.com/opnsense/core/blob/master/src/etc/inc/util.inc#L544-L550

**Comment by fichtner** [comment]
First things first, we should improve the validation message...
