### ISSUE TITLE
Cannot reboot via GUI or Command line option

### ISSUE THREAD

**Issue by QuentinC** [opnsense/core#1447]
This issue seems to be the same as #812.
I'm not able to reboot my router from the web GUI (and not also from the command line option).

Only the "reboot" command works, but loses data with /var in memory.

When trying to reboot, I can see in system.log that lighttpd stops, but nothing more. The system never restarts... I have to force the reboot from the shell.

Thanks,

Quentin

**Comment by fichtner** [comment]
A service hangs during reboot which causes it not to reboot. Need to isolate which service it is. A good start would be the output of:

    # sh -x /usr/local/etc/rc.reboot

**Comment by QuentinC** [comment]
Hello,

You are alright !
The command hang at "Waiting for pid xxx" which was haproxy. I killed it manually and the router restarted then.

So something is not working with haproxy service.

Thanks,

Quentin

**Comment by fichtner** [comment]
If this is important to you please open a bug in the plugins. I know we switch to HAProxy 1.7.3 soon, maybe this will already help. Closing as not a core bug.
