### ISSUE TITLE
No serial console after 'reset to factory defaults' in Console Menu

### ISSUE THREAD

**Issue by MNMtm** [opnsense/core#145]
Under System: Settings: Admin Access: Serial Communications, Serial Terminal is not enabled by default.

**Comment by fichtner** [comment]
Which install version/flavour did you use?

**Comment by MNMtm** [comment]
Installed appliance with OPNsense 15.1.9, updated to 15.1.9.1.

**Comment by fichtner** [comment]
Indeed, the standard config from the install media is replaced by the update. I'll take care of this for 15.1.9.2.
