### ISSUE TITLE
Allowed MAC addresses in Captive Portal

### ISSUE THREAD

**Issue by gertfriend** [opnsense/core#1451]
If i enter a allowed MAC address in Captive Portal i don't see it so the list is empty. What i'm doing wrong or is this a bug in the gui?

**Comment by AdSchellevis** [comment]
forgot to press enter after inserting the value? it turns blue, like this:
![image](https://cloud.githubusercontent.com/assets/9783985/23644962/0b8949e0-030a-11e7-9692-97a4b7d4a1e0.png)

**Comment by gertfriend** [comment]
Hello. I'm sorry, you are right i didn't press enter but i didn't also found in any documentation to press enter. I thought alway i'm wrong in the format of MAC because some devices need 00:00:00:00:00:00, some 000000000000 and others 00-00-00-00-00-00. Maybe it will be useful to show the exptected format in the help.
Thank you very much for the fast response.
