### ISSUE TITLE
[Feature Request] Add IPsec to interfaces group

### ISSUE THREAD

**Issue by nicovell3** [opnsense/core#1455]
Hello,

I'm trying to set up a network through IPsec with the same rules as other networks I've already configured.

I have an interfaces group to assign the same rules to these networks I've configured, but now I can't add the IPsec interface to the interfaces group. If this can't be done, I'll need to replicate each rule of the interface group on the IPsec interface, which is not desirable.

How can I solve this problem?

**Comment by nicovell3** [comment]
What I'd like to see is the interface "IPsec" in this list:

![image](https://cloud.githubusercontent.com/assets/9163055/23748291/41a69e14-04c3-11e7-8639-be421d9b9c18.png)

**Comment by AdSchellevis** [comment]
@nicovell3 As far as I can see, this https://github.com/opnsense/core/commit/f6d83a94e5521f2673fa90d505a5e2c53b259953 should work. Can you test and confirm?


You can use the following to patch your installation:

`opnsense-patch f6d83a9
`

**Comment by nicovell3** [comment]
@AdSchellevis That worked perfectly, thank you very much. Will it be available in the next version?

**Comment by AdSchellevis** [comment]
I think so, but let's ask @fichtner

**Comment by fichtner** [comment]
This is a fun one :)

I can create a group called "OPENVPN" now with the OpenVPN interface "OPENVPN", which is already a group in the underlying code. It creates a second "OPENVPN" tab in the firewall rules.

Special groups are: "l2tp", "pptp", "pppoe", "enc0" (visibly named IPsec or IPSEC), "openvpn". The FreeBSD system has more but we should not be concerned with those.

We should make sure that: validation for groups are case insensitive and do not overlap with existing groups or know groups, maybe also interface names?

**Comment by AdSchellevis** [comment]
@fichtner we should probably change the type here, to something more useful (currently openvpn, ipsec uses "none" here). What if we add type "ifgroup" as type to the groups, replace openvpn and other types with ifgroup as well? then filter on appropriate types.

**Comment by fichtner** [comment]
'type' => 'group' sounds reasonable, but not for known internal groups. it's going to be confusing.

groups are essentially tags on existing interfaces, not interfaces itself

**Comment by fichtner** [comment]
in the case of ipsec it's not a group but treated as one (we have enc0 as a real interface)

**Comment by AdSchellevis** [comment]
@fichtner those internal groups are actually groups too, enc0 is an actual interface....

**Comment by fichtner** [comment]
hmm, do we have a flag for "internal" (automatically created) already?

**Comment by AdSchellevis** [comment]
nope, ipsec is internally created as well (internal_dynamic).... it's just missing a descriptive type in my opinion.

**Comment by fichtner** [comment]
ok, you know best there. go ahead :)

**Comment by AdSchellevis** [comment]
other plugins will need the same treatment still, but when selecting an interface group into another group, it will just skip internally.

**Comment by phpb-com** [comment]
1dabd53d fixed the issue with interface group inception, not sure if this works for IPSec interfaces (since I have none). Thanks.

**Comment by fichtner** [comment]
plugis need to be fixed still, though...

I'm going to get rid of "if_ipsec.inc" et al. by merging them into "ipsec.inc", that also affects groups. Can we simplify from "ifgroup" to "group" already?

**Comment by AdSchellevis** [comment]
@phpb-com thanks for confirming!

**Comment by AdSchellevis** [comment]
@fichtner I would leave the ipsec definition where it is (not sure what we solve by moving it), I don't have a strong meaning about using ifgroup or group, both work for me.

**Comment by fichtner** [comment]
if_ipsec.inc was a workaround for not being able to name the plugin file ipsec.inc because that already existed and caused prefix clashes, but essentially the files need to be merged into the plugin dir under the ipsec.inc file. the plugin isn't "interface" specific anymore, it's the whole contained subsystem then. for the user nothing changes here.

**Comment by AdSchellevis** [comment]
ah, I see, I thought you meant something else. as long as <name>_interfaces() is called, I'm fine with it :)

**Comment by fichtner** [comment]
Plugins also fixed. Likely for 17.1.3, but keeping it open for now

**Comment by fichtner** [comment]
Backported for 17.1.3.
