### ISSUE TITLE
System: Trust: Revocation - wrong certificate count

### ISSUE THREAD

**Issue by tkald** [opnsense/core#1458]
Revoked a certificate, now certificates column on System: Trust: Revocation page shows wrong revoked certificate count.
Previously I had 1 cert revoked, added one cert but certificates column still shows 1.

If I open revocation list, there's 2 certs.  
Also on certificates page, those certs are correctly marked as revoked.

v17.1.2

**Comment by fichtner** [comment]
Nice catch, thank you!
