### ISSUE TITLE
menu: hide empty main menu items

### ISSUE THREAD

**Issue by fichtner** [opnsense/core#146]
ACL might not grant access to any page there so the whole container item can be removed. Postponed due to MVC consolidation which is coming up soon.

**Comment by AdSchellevis** [comment]
should be fixed with https://github.com/opnsense/core/commit/31df024e7fea8114ca448bf9769ae7b062a7d254

**Comment by fichtner** [comment]
wheeeew, it's christmas! :)

**Comment by AdSchellevis** [comment]
almost :-)
