### ISSUE TITLE
Restore from Google Drive

### ISSUE THREAD

**Issue by kingfisher77** [opnsense/core#1461]
Hi, we had a sudden OPNSense crash resulting in not booting because of a corrupted configuration file. Via serial we copied a backup from /conf/backup and the system was back working again. What a luck!

The reason for the crash is unknown. In the frontend we fiddled around with VLAN but if this was the reason? Cannot say...

Afterwards we checked our generell backup strategy. What if we had to restore the configuration from Google Drive? We did not find a way do do this. The files in Drive are encrypted. How can we decrypt then? Could not find any answer for that one.

Must be something obvious :) Anyone?

**Comment by AdSchellevis** [comment]
easy, download the file from google drive, input the password you choose to use for encrypting..

![image](https://cloud.githubusercontent.com/assets/9783985/23795885/28a6f7e4-0598-11e7-8953-3ed5a20b9b0e.png)

**Comment by kingfisher77** [comment]
Ah, okay - this works :) Thank you.

What is if we would like to copy the configuration file from Google Drive directly into /conf. This was our scenario: the system were not booting anymore into the web frontend.

How can the backuped config from Google Drive decrypted directly on a cli?

**Comment by AdSchellevis** [comment]
either choose to not encrypt your data or install a new box, download config and reboot.. simple as that.

**Comment by kingfisher77** [comment]
Hoped there is a less time consuming option. Anyway, thank you very much!

**Comment by AdSchellevis** [comment]
your welcome.
