### ISSUE TITLE
Feature: Traffic Graph IP table improvements

### ISSUE THREAD

**Issue by jeffg2k** [opnsense/core#1462]
The IP table that lists the current traffic is too fleeting with IPs popping in and out, trying to spot who is consuming what is difficult.

Instead of dropping off the IPs as they flow in and out of traffic, let them persist for the duration of the overall traffic graph (showing maybe the top xx), dynamically updating the traffic for each.  You could add small graphs to each row for the individual usage (like the size of CPU usage in the dashboard).  It would also be great to have a column that displays the hostname.  Would make a great dashboard widget too.

This would be so much more effective when trying to look at the traffic graph.  It's great to see the overall traffic, but usually I'm looking at it to see who is consuming what in real time.

**Comment by fichtner** [comment]
This was merged recently, thanks again!
