### ISSUE TITLE
Verbose description for Plugins

### ISSUE THREAD

**Issue by jeffg2k** [opnsense/core#1464]
It's probably correct to assume that if you don't know what it is, you shouldn't be installing it.  But it would be nice if there was an option (like your "full help") that offered a verbose description of the plugin, what it does in OpnSense, and where you may find more info.   For example, I believe "SMART tools" is for monitoring hard drives but maybe it's an acronym for something totally different.

**Comment by fabianfrz** [comment]
This is already possible:
https://github.com/opnsense/plugins/blob/master/net/ftp-proxy/Makefile#L3

This Comment is what is shown in the GUI and it is up to plugin authors and contributors to set it to something useful. It is just that in case of open source development, people prefer to write awesome code and usually spend not much time for documentation purposes. In my opinion, people know what they install.

**Comment by jeffg2k** [comment]
The plugin authors seem to use the comment more like a "Full Name" and not really a description. Even with knowing what SMART and FTP proxy are, I don't know what they bring to OpnSense and why I should install them.  Guess I could just try it and see.. lol  Wish they were more descriptive.

**Comment by fichtner** [comment]
We do have a comment and a description available, but currently only use one. I want to add a "information dialog" for each package/plugin, which could then show more relevant package info along with a verbose description (packages already have this in FreeBSD).

**Comment by fichtner** [comment]
This is the plugin glue... contributors can now add "pkg-descr" files like it's being done in ports: https://github.com/opnsense/plugins/commit/aa69b4fde7a40ff67fe04e15807e0ea9ecae69f7
