### ISSUE TITLE
DHCP static mapping not listing IP

### ISSUE THREAD

**Issue by jeffg2k** [opnsense/core#1465]
I find the viewing of static mapped DHCP addresses (IP reservations) confusing.

Feedback - Suggestions
1) On the Server page it lists the "DHCP Static Mappings for this interface."  However, it doesn't list the IP addresses assigned to those reservations.  I haven't turned on Static ARP, so maybe it would display it there, but it just seems weird that the IP reservation doesn't show the IP reserved.  As a interface placement, I also wonder at the point of having it at the bottom of the server tab.  To me it might make more sense to just have it all on the Leases page - add a LAN / WAN tab there if needed.

2) On the Leases page we have the same issue as above where the static entries don't contain their static reservations.  The entries also do not have edit or delete buttons, where the Server page does.  In addition, it doesn't include the lease period.  As far as I know, an IP reservation (static mapping) is still a lease - it's just the system will not give that IP out to anyone else.  And it does show this information, above in the table.  It has two entries in the table, a static one and an active one.  I find this confusing.  Just have it once, note it as reserved along with the IP assigned and the lease period, along with the static description.

    - The static hostname lists what the admin defines and the active hostname lists what the computer reports.  If you give the option to edit the hostname, then it should probably reflect that, unless you want to give an option to add an alias that doesn't effect the name reported.  Sometimes I'll add a prefix to the hostname so I can identify who it belongs to, where I use the description to define where it is located.

**Comment by djGrrr** [comment]
Have you actually configured IP addresses on these leases? IP addresses show up in both places for me, and there are no duplicate leases for an IP with static reservation, only the static ones get listed. Can you please include some screenshots so we can see what you are seeing?

What version of OPNsense are you running?

**Comment by jeffg2k** [comment]
I'll have to wait until Monday to provide a screenshot, but no, I have not configured IP addresses on the leases.  If I recall, it states that if you specify an ip, the ip must be outside the DHCP scope, which seemed odd.  If you leave it blank, it will use an IP from the DHCP pool, which is usually the one currently assigned to it.  I want to reserve its current IP, which is in the pool.  I'm running the latest version of OPNsense, 17.1.

**Comment by djGrrr** [comment]
The IP is not static unless you put it in the reservation, it just allows you to do dynamic addresses with "allow only known clients" enabled.

I would suggest making the dynamic range a subset of the entire range, then assigning static ips in the rest of the range.

**Comment by jeffg2k** [comment]
I'll give that a try.  Some of the other points should still be considered, such as the lease page not having the edit / delete buttons.  As an addition, I wouldn't mind being able to edit the hostname and add a description for the active leases as well, which is the primary reason I made them static, that and to give historical consistency for the logs.

**Comment by jeffg2k** [comment]
Couple things - setting the IP as static does display it in the table, but it still doesn't show the lease period, which I don't see any reason why it shouldn't.  If you have a column for it, why not populate it.

Second, when you change the scope of DHCP - it wipes out all the current active leases.  Why?  I was using the active lease list - click the little [+] to reserve my first static lease and a refresh later, I have 0 leases to work from.. so now I have little idea what they were.  And I can't switch it back without removing the static leases.  I'm not sure why there is this restriction on the pool anyway.

Then you don't have the add button on the leases page to add more static and you can't edit or delete them from the lease page.

**Comment by jeffg2k** [comment]
This would be more of a feature request - but the main reason I'm making static reservations is to document 1) where they are located, 2) who they are assigned to.  It would be nice to be able to do that and leave them dynamic.  Currently, I'm using the Hostname and Description to do those things via a static reservation.

**Comment by AdSchellevis** [comment]
timeout due to inactivity
