### ISSUE TITLE
OpenVPN server creation wizard creates invalid certificate when pointed at an external CA

### ISSUE THREAD

**Issue by kevemueller** [opnsense/core#1467]
Using OPNsense 17.1.2 the (very convenient) OpenVPN server creation wizard offers to create a server certificate.
On a system with an externally configured CA (without private key), this CA is offered in the dropdown box and certificate creation seems to work (wizard does not throw an error). The created "certificate" is  zero bytes.
Certificates cannot be created against a CA like this.
* The wizard should try to create a certificate against an external CA and believe to have succeeded.
* Ideally in such a case the wizard should present the CSR to the user, asking for the externally signed certificate and proceed with installing that certificate.

**Comment by fichtner** [comment]
Presenting a CSR inside the wizard is out of scope, I'm going to hide selection of external CAs.

**Comment by fichtner** [comment]
Thanks for this report! :)
