### ISSUE TITLE
Cannot create user with scrambled password

### ISSUE THREAD

**Issue by kevemueller** [opnsense/core#1468]
Using OPNsense 17.1.2 the "Generate a scrambled password to prevent local database logins for this user." checkbox under System/Access/Users/Add does not grey out the password entry fields and the form does not validate with the error "The field Password is required.".
Setting a dummy password and checking the scrambled box also does not validate: "Cannot set random password due to explicit input."

* The checkbox should grey out the password fields and the form validation logic should accept this as a valid means to specify the password.

Update: The behavior of the checkbox is correct when editing the user after creation. The above error refers to the form that is presented when adding a new user (same form).

**Comment by fichtner** [comment]
Nice catch. The option was added for editing imported LDAP users so the behaviour while adding was inconsistent. I haven't disabled fields, it just checks correctly if the checkbox was set and the password is empty now to proceed as intended. Thanks!
