### ISSUE TITLE
Feature request: Reset (partial config) to Defaults

### ISSUE THREAD

**Issue by alphastar868** [opnsense/core#1471]
I'd like to be able to reset a config section, for e.g. _Services > DNS Resolver_ to Defaults.

Ideally this would be under _Advanced_ in the section options, just to avoid accidents.

Also, I think it would be nice to be able to Reset everything to Defaults (maybe from _General > Settings > Advanced_ option) except Interfaces (and _Interfaces > Other_ ( to keep Bridging)).

Thanks in advance!

**Comment by Woi** [comment]
I like to suggest to provide the default settings in the description of all options. This would allow to quickly spot changes that have been made and for easy manually resetting them. The documentation could be auto generated, to reduce documentation maintenance and ensure it's always up to date.

**Comment by AdSchellevis** [comment]
timeout due to inactivity
