### ISSUE TITLE
Certificate manager: allow to secure exports with a password

### ISSUE THREAD

**Issue by fraenki** [opnsense/core#1475]
Via a [forum post](https://forum.opnsense.org/index.php?topic=4792.msg18673#msg18673):

> Is there a way to export the full certificate and also include a password? I'm actually wanting to use the module to generate certificates for another device and for some inexplicable reason it won't let me enter a blank password when importing - I'm thinking that they assume no-one stores full certificates without a password.

**Comment by Taomyn** [comment]
Really could have done with this last night, right pain to import a renewed certificate from opnSense onto my server/access-point.

**Comment by AdSchellevis** [comment]
timeout due to inactivity

**Comment by Taomyn** [comment]
Please re-open, I would still like this added as a feature

**Comment by AdSchellevis** [comment]
@Taomyn are you planning to work on it? We can't keep issues open if nobody has the intention of working on it. We can always reopen if there's someone committed to do the work for it.

**Comment by Taomyn** [comment]
No as I'm not a developer, but it's not an issue but a feature request.

**Comment by AdSchellevis** [comment]
I know it's a feature request, we keep them open for several months (as stated https://github.com/opnsense/core/blob/master/CONTRIBUTING.md). 
If there is someone interested  in working on it we assign an owner and the issue remains open. 

Maintaining issues/feature requests takes time during every release cycle, which we try to keep manageable.
