### ISSUE TITLE
fixed IP for opneVPN client (CSC)

### ISSUE THREAD

**Issue by Ivan-Smagleson** [opnsense/core#1476]
Hi there
I use openVPN in Topology subnet in 17.1.3
How can I specify fixed IP for opneVPN client via csc and Tunnel Network field?
I use ifconfig-push 10.10.10.43 255.255.255.0 in Advanced, but when I try to specify 
10.10.10.43/24 in Tunnel Network, I'm get an error The field 'Tunnel Network' must contain only valid ipv4 CIDR range(s) separated by commas.
What I do wrong?

**Comment by fichtner** [comment]
Should be easy... use 10.10.10.0/24


Cheers,
Franco

**Comment by Ivan-Smagleson** [comment]
And which IP address will be fixed?
I want to get ClientA - 10.10.10.41
 ClientB - 10.10.10.42
 ClientC - 10.10.10.43
how I will reach this with 10.10.10.0/24?

**Comment by fichtner** [comment]
Working on a patch, hold on.

**Comment by fichtner** [comment]
I've allowed host address specifications for tunnel networks in CSCs. Run this from the console to apply the patch for 17.1.3:

    # opnsense-patch 4446556


Cheers,
Franco
