### ISSUE TITLE
Not all available diskspace used

### ISSUE THREAD

**Issue by mschilt** [opnsense/core#148]
I installed Opnsense 15.1 with a livecd and somehow the automatic partitioning did not use the full disk. I have a 16GB SSD but only 6GB seem to be used.

HW Platform: PCengines APU with msata16d

    root@opnsense:~ # df -h
    Filesystem      Size    Used   Avail Capacity  Mounted on
    /dev/ada0s1a    5.8G    912M    4.4G    17%    /
    devfs           1.0K    1.0K      0B   100%    /dev
    /dev/md0        3.4M    108K    3.0M     3%    /var/run
    devfs           1.0K    1.0K      0B   100%    /var/dhcpd/dev
    root@opnsense:~ # fdisk 
    ******* Working on device /dev/ada0 *******
    parameters extracted from in-core disklabel are:
    cylinders=29091 heads=16 sectors/track=63 (1008 blks/cyl)

    Figures below won't work with BIOS for partitions not in cyl 1
    parameters to be used for BIOS calculations are:
    cylinders=29091 heads=16 sectors/track=63 (1008 blks/cyl)

    Media sector size is 512
    Warning: BIOS sector numbering starts with sector 1
    Information from DOS bootblock is:
    The data for partition 1 is:
    sysid 165 (0xa5),(FreeBSD/NetBSD/386BSD)
        start 63, size 29323665 (14318 Meg), flag 80 (active)
    	beg: cyl 0/ head 1/ sector 1;
    	end: cyl 418/ head 15/ sector 63
    The data for partition 2 is:
    <UNUSED>
    The data for partition 3 is:
    <UNUSED>
    The data for partition 4 is:
    <UNUSED>

**Comment by fichtner** [comment]
I'd say the swap partition is the culprit here. I'm still trying to wrap up a sane approach to swap usage (especially for small solid state drives or SD cards), but so far swap files as opposed to partitions are not helping since core dumps won't work with swap files. Beyond that there really is no point in having a swap partition at all (swapping would be slow as hell anyway).

**Comment by mschilt** [comment]
Ack. Its the swap partition. Have 4Gb RAM and a 8Gb swap partition on that SSD. Not sure If I really need/want swap at all. Speed is not that bad according to diskinfo/dd but vmstat lists that I have still plenty of free mem. I believe having more disk space instead of available/unused swap space would be better.

**Comment by fichtner** [comment]
Will fix this via https://github.com/opnsense/ports/issues/2 -- most likely skip swap for installations smaller than 30GB. Cheers. :)
