### ISSUE TITLE
OpenVPN 2.4 dhcp-option DNS6

### ISSUE THREAD

**Issue by tsumaru720** [opnsense/core#1486]
Hi All

When providing DNS servers in OpenVPN configuration, if you give IPv6 addresses, it seems that some clients will fail as dhcp-option DNS xx seems to be for IPv4 addresses

Ultimately this means no ipv6 when connected to VPN as all DNS lookups are done via the v4 servers thus primarily v4 addresses are returned and used.

It seems that OpenVPN 2.4 has addressed this and added a DNS6 option - https://community.openvpn.net/openvpn/ticket/243

Would it be possible to bundle OpenVPN 2.4 (looks to be stable)? To fully support this particular change then the settings page would either need separate DNS server boxes for v4 or v6, or do some kind of check to see if the IP provided is v4 or v6 and generate the correct dhcp-option accordingly

**Comment by fichtner** [comment]
OpenVPN 2.4 is in the pipe, but currently stalled because we want to provide new images based on 17.1.4 as there have been multiple fixes that should be in the installer. I would say we're looking at 2.4 adoption to be completed in a month.

I am guessing we already have an IPv4 setting, but the GUI for IPv6 is missing?

**Comment by tsumaru720** [comment]
The GUI (VPN -> OpenVPN -> Servers -> <edit your server>) has an option for DNS - It'll allow entry of 4 addresses and seems to accept IPv4 and IPv6 just fine.
![dns1](https://cloud.githubusercontent.com/assets/239857/24084142/9ecaa7f4-0cdc-11e7-84cf-ee9045b4fadf.png)
This results in the following config snippet

```
root@vpn1:/var/etc/openvpn # grep -i dns server1.conf 
push "dhcp-option DNS 10.0.2.11"
push "dhcp-option DNS 10.0.2.13"
push "dhcp-option DNS 2a03:b2XX"
push "dhcp-option DNS 2001:1bXX"
```
This happily gets pushed out to clients so for now it looks like the onus is on the connecting client to deal with it.... Take KNetworkManager for KDE which seems to deal with it correctly:
```
Mar 19 19:46:31 MyPC NetworkManager[917]: <info> VPN Gateway: XXXXX
Mar 19 19:46:31 MyPC NetworkManager[917]: <info> Tunnel Device: tun0
Mar 19 19:46:31 MyPC NetworkManager[917]: <info> IPv4 configuration:
Mar 19 19:46:31 MyPC NetworkManager[917]: <info>   Internal Gateway: 10.0.3.1
Mar 19 19:46:31 MyPC NetworkManager[917]: <info>   Internal Address: 10.0.3.2
Mar 19 19:46:31 MyPC NetworkManager[917]: <info>   Internal Prefix: 25
Mar 19 19:46:31 MyPC NetworkManager[917]: <info>   Internal Point-to-Point Address: 0.0.0.0
Mar 19 19:46:31 MyPC NetworkManager[917]: <info>   Maximum Segment Size (MSS): 0
Mar 19 19:46:31 MyPC NetworkManager[917]: <info>   Forbid Default Route: yes
Mar 19 19:46:31 MyPC NetworkManager[917]: <info>   Internal DNS: 10.0.2.11
Mar 19 19:46:31 MyPC NetworkManager[917]: <info>   Internal DNS: 10.0.2.13
Mar 19 19:46:31 MyPC NetworkManager[917]: <info>   DNS Domain: 'xxx'
Mar 19 19:46:31 MyPC NetworkManager[917]: <info> IPv6 configuration:
Mar 19 19:46:31 MyPC NetworkManager[917]: <info>   Internal Address: 2a03:b2XX::1000
Mar 19 19:46:31 MyPC NetworkManager[917]: <info>   Internal Prefix: 64
Mar 19 19:46:31 MyPC NetworkManager[917]: <info>   Internal Point-to-Point Address: 2a03:b2XX::1
Mar 19 19:46:31 MyPC NetworkManager[917]: <info>   Maximum Segment Size (MSS): 0
Mar 19 19:46:31 MyPC NetworkManager[917]: <info>   Forbid Default Route: no
Mar 19 19:46:31 MyPC NetworkManager[917]: <info>   Internal DNS: 2a03:b2XX
Mar 19 19:46:31 MyPC NetworkManager[917]: <info>   Internal DNS: 2001:1bXX
Mar 19 19:46:31 MyPC NetworkManager[917]: <info>   DNS Domain: 'XXX'
Mar 19 19:46:33 MyPC NetworkManager[917]: <info> VPN connection 'xxx' (IP Config Get) complete.
```
However using an android VPN client does the following... It gets this pushed from the server
```
dhcp-option DNS 2a03:b2XX
dhcp-option DNS 2001:1bXX
```
But it seems this particular client doesn't check IPs properly
```
2017-03-19 13:22:25 Options error: dhcp-option parameter DNS '2a03:b2XX' must be an IP address
2017-03-19 13:22:25 Options error: dhcp-option parameter DNS '2001:1bXX' must be an IP address
```

The link I provided in my original post suggests OpenVPN have added support for dhcp-option DNS6 to specify specific DNS servers for IPv6. Granted my issue is currently with my Android VPN client, I thought I'd ask about server support too :)

I think maybe having options for IPv4 and IPv6 DNS servers separately would be clearer and it'd save some logic when you POST to check if its v4 of v6 when generating openvpn's config

**Comment by sjorge** [comment]
Just to add to this, we probably also want NTP6.

Also the redirect-gateway bug were it does not do IPv6 'should' be fixed in 2.4.

**Comment by fichtner** [comment]
17.1.6's -devel will feature OpenVPN 2.4, then we can hopefully deal with additions in-tree for a final merge in 17.1.7 or 17.1.8 :)

**Comment by fichtner** [comment]
Merging this into #1721.
