### ISSUE TITLE
OpenVPN: ca certificate shall include ancestors if not self-singed

### ISSUE THREAD

**Issue by 8191** [opnsense/core#1487]
It seems that OpenVPN refuses to verify user certificates if it does not know **all** its ancestors. I.e. if the CA configured as "Peer Certificate Authority" in the OpenVPN Server UI is not self-signed, OpenVPN refuses to verify user certificates (even if signed directly by the _Peer Certificate Authority_) with the error `VERIFY ERROR: depth=1, error=unable to get issuer certificate: Peer Certificate Authority`.

A solution to this would be to add all ancestors of _Peer Certificate Authority_ to the ca file (`/var/etc/openvpn/serverx.ca`) if the CA is a sub-ca (i.e. not self-signed).

_See also: https://forum.opnsense.org/index.php?topic=4830.0_

**Comment by AdSchellevis** [comment]
timeout due to inactivity

**Comment by 8191** [comment]
Actually still an issue. Did anyone ever try to use OpenVPN with TLS-Auth using a non-self-sigened root CA?

**Comment by wschlich** [comment]
Yes, it's still an issue.

**Comment by wschlich** [comment]
@AdSchellevis can you please reopen the issue?

**Comment by AdSchellevis** [comment]
@wschlich are you planning to work on it?

**Comment by wschlich** [comment]
@AdSchellevis At least from a user perspective, yes :-)

**Comment by AdSchellevis** [comment]
Not a lot of people seem to be using this construction, hence the time out last time. I'll reopen this for now, but without people digging into the use  case and related code, it's likely this will be closed again.

**Comment by wschlich** [comment]
From what I've seen, @8191 was absolutely right regarding his findings. I've written mine down at https://forum.opnsense.org/index.php?topic=11601.0 -- basically OPNsense does not add the full CA certificate chain to `/var/etc/openvpn/serverX.ca` when the `Peer Certificate Authority` is not a self-signed, but an intermediate CA.

**Comment by wschlich** [comment]
The bug is in `/usr/local/etc/inc/plugins.inc.d/openvpn.inc` in lines 895+896 (on 19.1.1):
`$ca = lookup_ca($settings['caref']);`
`openvpn_add_keyfile($ca['crt'], $conf, $mode_id, "ca");`
Simply no full CA chain resolution code there.

**Comment by AdSchellevis** [comment]
but that would suggest it doesn't work for self-signed certificates either, let me take a quick peek.

**Comment by wschlich** [comment]
@AdSchellevis nope, works fine for self-signed Root CA certificates because the CA chain is completed already by adding just the Root CA certificate.

**Comment by AdSchellevis** [comment]
does OPNsense know the path for your intermediate CA?

**Comment by wschlich** [comment]
@AdSchellevis yes, it does, as it consists solely of CA certificates that are managed by the OPNsense CA manager :-)

**Comment by AdSchellevis** [comment]
ok, one moment.

**Comment by AdSchellevis** [comment]
@wschlich can you try https://github.com/opnsense/core/commit/67f49486708770633ca615ee41f53439e0a962ce ?

From your console, you should be able to install using:
```
opnsense-patch 67f4948
```

**Comment by wschlich** [comment]
> @wschlich can you try [67f4948](https://github.com/opnsense/core/commit/67f49486708770633ca615ee41f53439e0a962ce) ?

works flawlessly now (removed the workaround before having the openvpn instance config regenerated using the web UI), awesome! thank you :-) :+1:

**Comment by AdSchellevis** [comment]
Thank you!

**Comment by fichtner** [comment]
@AdSchellevis for 19.1.2?

**Comment by AdSchellevis** [comment]
@fichtner yes please :)

**Comment by wschlich** [comment]
@AdSchellevis , @fichtner you guys rock! :1st_place_medal:

**Comment by wschlich** [comment]
@AdSchellevis My OPNsense firewall reported an issue in /usr/local/opnsense/mvc/app/controllers/OPNsense/OpenVPN/Api/ExportController.php, line 205 (function accountsActivation). Is it maybe related to your patch? That function is working with 'caref' as well...

**Comment by AdSchellevis** [comment]
@wschlich it can't be related, new style mvc code has no relation with the legacy code base.

Can you open a new issue with the the full error?

**Comment by wschlich** [comment]
> @wschlich it can't be related, new style mvc code has no relation with the legacy code base.

I see :-)

> Can you open a new issue with the the full error?

Hmm, I submitted the issue via the web GUI crash reporting function. Did that already open up an issue somewhere?

**Comment by AdSchellevis** [comment]
sorry, we don't read those on a very regular bases, better to open a ticket describing steps to reproduce and data here.

**Comment by wschlich** [comment]
I see... :/ actually I have no idea how this error occurred. If it happens again, I'll open a github issue then.

**Comment by AdSchellevis** [comment]
ok, thanks
