### ISSUE TITLE
UEFI booting stops

### ISSUE THREAD

**Issue by thomasnilsen** [opnsense/core#1489]
Hi,

I have tried installing with UEFI boot option. This works pretty well (goes 4 times slower when reading files from disk. As expected probably due to UEFI services calling), but when switching to new console the the image freezes and it does not seem like its working. Not sure if the machine actually boots or just hangs.

I have tried on two machines and with same result. It might be related to the GUI/frambuffer driver that this motherboard exports (GOP or the other UEFI type.. as i remember there are two main protocols/services that UEFI exports for this depending on implementation). I have not tried to install FreeBSD on machine, but I can test this to see if its acutally related to Opnsense or just the kernel not supporting this motherboards EFI implementation. (Linux/Windows UEFI boot works perfect on this machine).

regards
Thomas

**Comment by fichtner** [comment]
Hi Thomas,

It is kind of a know issue. Which image are you using?


Cheers,
Franco

**Comment by thomasnilsen** [comment]
Hi,

I'm using OPNsense-17.1-OpenSSL-vga-amd64.img.bz2 image..

I have seen same issues before in other cases with linux etc. So my guess is that its something with the framebuffer protocoll service in the UEFI implementation in the kernel.

I can test doing a Freebsd uefi boot to see if i get same result. Can also check with linux to see what linux says about the UEFI graphics service exported from the bios.

regards
Thomas

**Comment by fichtner** [comment]
Good, can please see if this image makes a difference? 

https://pkg.opnsense.org/snapshots/OPNsense-201703120533-OpenSSL-vga-amd64.img.bz2

It uses UEFI/VT console driver by default.


thanks,
Franco

**Comment by thomasnilsen** [comment]
Yes! I'll check tonight and post back.

regards
Thomas

**Comment by fichtner** [comment]
17.1.4 images are now live and should fix this, closing. Feel free to report back if there is still a problem.
