### ISSUE TITLE
Add Route same gateway different interface

### ISSUE THREAD

**Issue by sachaz** [opnsense/core#1490]
Hello,

I cannot add a route to the right interface in a special case:

I have 2 DSL links {pppoe1 & pppoe2} on 2 interfaces {wan1 & wan2}  with the same gateway {GW_IP} (yes it's the same provider).
If I try to add an IP (for exemple: 131.252.210.176) to be routed on pppoe2 "wan2_PPPOE GW_IP" when I had the route it's on the wrong pppoe1.
If I do manualy route add 131.252.210.176/32 -iface pppoe2 it's works.

 Also if I had 2 lan interfaces (lan1 and lan2), if I had a rule for lan2 like:
pass in quick on lan2 route-to (pppoe2 GW_IP) inet from lan2:network to any it doesn't route my lan2 interface traffic to my pppoe2

Thanks for reading and maybe helping.
Sacha.

**Comment by sachaz** [comment]
before reboot I had:
131.252.210.176/32   GW_IP      UGS      pppoe0

after a reboot:
131.252.210.176/32   pppoe1             US       pppoe1

It works after the reboot ?!

**Comment by AdSchellevis** [comment]
timeout due to inactivity
