### ISSUE TITLE
Issuing CA not found if CSR was signed

### ISSUE THREAD

**Issue by 8191** [opnsense/core#1492]
After filling in the certificate data of a signed CSR the "Issuer" field is always shown as _External_ even if the CA is installed as Authority.

**How to reproduce**
1. Install a CA in System > Trust > Authorities
1. Create a CSR in System > Trust > Certificates (_Add or Import Certificate_ > Method: Create Certificate Signing Request > Fill in all data)
1. Click the _Edit_ icon to show the CSR data, sign the CSR with the CA added in first step
1. Paste the signed certificate to the "Certificate" field in the Edit Certificate dialog
1. In the overview the "Issuer" is shown as _External_ even the CA was installed in step 1

**Comment by AdSchellevis** [comment]
timeout due to inactivity

**Comment by dl8dtl** [comment]
Don't know why this has been closed.  This is still an issue as of today (OPNsense 19.1.9).

As soon as I create a second CA using the same CA certificate, all existing certificates signed by that one will be assigned to that new entry. However, the existing VPN server then gets confused, and does not show its users anymore (not recognizing that both CAs are actually the same).

**Comment by fichtner** [comment]
For more details see our contribution guidelines https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

**Comment by dl8dtl** [comment]
Workaround: download the key and certificate data, delete the entire certificate, and then recreate from the downloaded data - voila, now it's correctly assigned to the issuer.
