### ISSUE TITLE
firewall: logging for NAT rules

### ISSUE THREAD

**Issue by cryptochrome** [opnsense/core#1494]
Currently, when you add a new port forwarding rule and let it automatically create a corresponding firewall rule, that firewall rule has logging disabled and the rule can't be edited. So if I want logging, I would have to add the firewall rule manually and disable automatic rule creation.

Why not give us an option to enable logging on these auto-created rules?

**Comment by AdSchellevis** [comment]
There's a good reason why automatic rules can't be edited, the automatic generated rules lack validations which causes more issues if we let users edit them, for reference see https://github.com/opnsense/core/issues/858 and the associated forum posts.

**Comment by cryptochrome** [comment]
I didn't necessarily imply that the auto-generated rules should be changeable. You could just add an additional option to the Port Forwarder setup page next to the field that asks if and which firewall should be created. Just add a checkbox, "enabled logging".

**Comment by fichtner** [comment]
I'm taking this as discussed in the forum :)

**Comment by AdSchellevis** [comment]
@fichtner no problem, just referencing the cause here and not entirely sure it's a good idea to extend the forwarder page with more firewall settings.

**Comment by fichtner** [comment]
I agree, it will go to system: settings: logging

**Comment by AdSchellevis** [comment]
@fichtner thanks!

**Comment by cryptochrome** [comment]
thanks guys :) 👍

**Comment by fichtner** [comment]
Also for port forward, via https://forum.opnsense.org/index.php?topic=7266.0

**Comment by ccesario** [comment]
Hi Folks,  is there any ETA for this feature!?

Regards
Carlos

**Comment by fichtner** [comment]
Like this? :) Although it's not what @AdSchellevis wanted as you can enable it per port forward rule ;)

<img width="700" alt="screenshot 2018-11-11 at 8 48 15 am" src="https://user-images.githubusercontent.com/1915288/48310375-93a54a00-e58e-11e8-9266-51038cb2786f.png">

**Comment by drinn** [comment]
Thank you, @fichtner for your work on this! I'm assuming I'd need to change my release type to "development" if I want to see these changes reflected on my running opnsense instance (assuming I want to try it out before the next release)?

**Comment by ccesario** [comment]
Hey @fichtner , only to configr .... is this in 18.7.8 ? 
I'm not able to see log option in Firewall: NAT: Port Forward rule.

Carlos

**Comment by fichtner** [comment]
it's on the development version now (18.7.8 -> Release type Development, Check for updates again) . there is one issue left with the feature: the live log shows the wrong rule label. needs @AdSchellevis's help but not super urgent. I'm hoping it's done in 18.7.9 or 18.7.10.
