### ISSUE TITLE
[REQ] LAGG configurable from command line

### ISSUE THREAD

**Issue by joegsn** [opnsense/core#1495]
I would like for it to be possible to configure LAGG interfaces from the command line, sort of similar to (or maybe part of) the wizard that configures VLANs.  From what I can tell, you need to configure the system far enough to login via a web-browser before you can configure a LAGG.  If I'm configuring a 2-port LAGG, this means my easiest configuration is to have at least 3 network ports:  One used as a LAN port to login to the WebUI, and the other two for the LAGG until you can reassign the LAN to the LAGG (or a VLAN on the LAGG).

If the LAGG were able to be created before VLAN configuration (and used by VLANS) in the console, then it would simplify my initial configuration, or rebuilding my system (such as in the case of a failed HDD) if the switches I'm already plugged into are also configured to support the LAGG.

**Comment by fichtner** [comment]
While this would be useful, I don't think anybody is going to work on it. The interface assignment on the console is for a simple first-time setup. VLAN from there is already the "cherry on top".
