### ISSUE TITLE
IPsec unable to set Certificate Authority

### ISSUE THREAD

**Issue by smindorf** [opnsense/core#1497]
Hi,

```
Versions OPNsense 17.1.3-amd64
FreeBSD 11.0-RELEASE-p8
OpenSSL 1.0.2k 26 Jan 2017
```

I tried to set up a IPsec RSA site-to-site tunnel but I'm unable to select the Certificate Authority. The field is missing but required.

![ipsec-opn](https://cloud.githubusercontent.com/assets/8710032/24191695/d0c037da-0eec-11e7-9975-43e5c1e1f5f2.png)
![ipsec-opn-2](https://cloud.githubusercontent.com/assets/8710032/24191694/d0b635fa-0eec-11e7-8e8b-4605d7139c14.png)

Regards,
Soeren

**Comment by AdSchellevis** [comment]
Hi Soeren,

Can you try https://github.com/opnsense/core/commit/b6c6eec21e0bd6376c6e039c4a08139e8376974d , apply on your OPNsense using:

`opnsense-patch b6c6eec2
`
Best regards,

Ad

**Comment by smindorf** [comment]
Hi Ad,

I've applied the patch and now I can save the IPSec RSA Tunnel.

Thanks for the patch.

Kind regards,
Soeren

**Comment by AdSchellevis** [comment]
Hi Soeren,

Thanks for confirming!

Best regards,

Ad
