### ISSUE TITLE
IPSec Server has no knowledge of VPN subnet

### ISSUE THREAD

**Issue by abel408** [opnsense/core#1499]
I've set up a raod warrior IPSec VPN set up according to this guide: https://docs.opnsense.org/manual/how-tos/ipsec-road.html

Everything is the same except that Negotiation mode is set to Main. Aggressive did not work.

My virtual address pool is 10.140.0.0/24
My OPNSense IP is 192.168.0.101
My LAN address is 10.128.0.0/16
Local Address in phase 2 is set to 10.128.0.0/16, but I've also tried setting this to 0.0.0.0/0 with no luck.

My client can successfully connect and is given the ip address 10.140.0.1 from the OPNSense server. When I try to ping that address from the client, it times out. I also cannot ping or connect to anything... not even google's public DNS servers. It's like it's trying to send all traffic through the VPN even though I have my LAN subnet set in the local address field of the phase 2 settings.

My internal hosts can ping the IPSec client. For example, a machine at 10.128.0.50 can ping 10.140.0.1, but 10.140.0.1 cannot ping 10.128.0.50. 

If I start a packet capture on the IPSec interface, I can see the ICMP request and replies... even the ones that do not go through. I can even see the icmp request and reply to itself (ping 10.140.0.1 from 10.140.0.1).

**Comment by AdSchellevis** [comment]
timeout due to inactivity
