### ISSUE TITLE
[framework] field attribute "advanced" broken

### ISSUE THREAD

**Issue by fraenki** [opnsense/core#1500]
On 17.1.3 (and earlier?) a field with the `<advanced>true</advanced>` parameter will cause all subsequent fields to (accidentially) inherit this attribute too. As a result, these fields will only be visible in "advanced mode", even though they don't have this attribute set in their form definition.

As a result, the sub-tab "Global Parameters" in `Service -> HAProxy -> Settings -> General Settings` is empty:

![advanced_foo](https://cloud.githubusercontent.com/assets/909706/24261000/d1b82fc6-0ff5-11e7-9296-ae8bd9d9a2b8.png)

This also affects other plugins and possibly some core pages. I was unable to find the change that is causing this issue.

(Tested on recent Firefox and Chromium.)

**Comment by fichtner** [comment]
https://github.com/opnsense/core/commit/38cbce1be4cf1f509f8b2bb2547a6477e204a3db maybe?

**Comment by fichtner** [comment]
fwiw, it doesn't look wrong on the web proxy, but maybe I misunderstood

in any case, are you sure it's not a bug surfacing in the plugin now?

but I don't have 17.1.3 here at the moment to double check, maybe also a backport glitch?

**Comment by AdSchellevis** [comment]
@fraenki I could reproduce it, seems like another issue with scope in volt templates, looks buggy to me. https://github.com/opnsense/core/commit/7504bd00a2309cbac5b28539f169e3b3f0f49f7d fixes it for me, just let me know if it doesn't in your case.
