### ISSUE TITLE
Feature update REq - Squid Logging Scheme 

### ISSUE THREAD

**Issue by gaurovsoni** [opnsense/core#1507]
Access.logs are Essential for finding user / ip / mac based reports . 

Why Feature update is Needed for default squid access log : 
  1> logs generated are in UNIX time stamp format, Which are difficult for humans (normal user) to understand while creating a report. 
  2>  IP based  - ip can b changed , user & macc address are not basically (until not spoofed).

Bellow is a image better then default log format... user detail on 1 side. & other details on the right

![screenshot from 2017-03-26 23-34-51](https://cloud.githubusercontent.com/assets/9216097/24334047/acde3178-1252-11e7-98cd-03ae2b5e0b40.png)

in order to achieve this i did a bit manipulation in : 
/usr/local/opnsense/service/templates/OPNsense/Proxy/squid.conf
added line 329
modified line 330

![screenshot from 2017-03-26 23-50-10](https://cloud.githubusercontent.com/assets/9216097/24333960/2f0dbed6-1251-11e7-87ba-be6edc0bf231.png)

these changes remain persistent even after reboot, but not after update/upgrade i believe, therefore i jst made a request

future Suggestion : 
1> One more thing i would like to suggest but since i dont know the working of php & falcon i cannot do it now, the Access.logs of one day in only shown, after 12:00am a new access.log file is generated completely empty. the old access.log of previous day containing logs get converted to .gz format. and in order to view old logs other than today i have to unzip the .gz files & find logs in them. and then search manually. 
2> If we can export logs in PDF , html, .csv it will b much better.

**Comment by AdSchellevis** [comment]
I've added an option to enable "Extended" file logging.
https://github.com/opnsense/core/commit/abad6f9952589d390348927a78ab06dee77b52df contains the "combined" squid logging format, extended with the mac address.

**Comment by gaurovsoni** [comment]
Thanks, 
  Currently i am creating a Reporting module(Plugin) for squid (proxy) which add up the following feature --
1> check logs according to date. 
2> Export in PDF , CSV & TXT 

I hope that u will live my work.

**Comment by fichtner** [comment]
@gaurovsoni that sounds great. if you can create a PR in the plugins.git we can review and give input if you want :)
