### ISSUE TITLE
firewall logging problem

### ISSUE THREAD

**Issue by liszhu** [opnsense/core#1508]
The Opnsense does not log firewall actions although firewall logging has been enabled. The firmware version is  OPNsense 17.1.3-i386.
![configuration](https://cloud.githubusercontent.com/assets/15182584/24342830/d95813d8-12f5-11e7-8eff-af989847aafb.png)
![issue](https://cloud.githubusercontent.com/assets/15182584/24342836/e18b17da-12f5-11e7-8493-b36d735fb621.png)

**Comment by fichtner** [comment]
Which specific option gives you trouble? Not that this is not a log-all for rules found in the firewall rules section, logging needs to be enabled per rule there.

**Comment by liszhu** [comment]
![Uploading rule.png…]()

**Comment by liszhu** [comment]
![rule](https://cloud.githubusercontent.com/assets/15182584/24347264/4812e5b4-130a-11e7-8038-47ece107d409.png)
please check attached, actually i have enable the logging of each rule about out traffic.
And the truth is that the logging of firewall had been working fine since upgrade to 17.1.3

**Comment by fichtner** [comment]
Are you using Multi-WAN?

**Comment by liszhu** [comment]
No, just one wan interface, OpenVPN service is enable on this firewall for
remote dialed in.

2017-03-27 16:44 GMT+08:00 Franco Fichtner <notifications@github.com>:

**Comment by criiser** [comment]
For reference - OPNsense 17.1.3-amd64 - logs perfectly into it's files.

**Comment by AdSchellevis** [comment]
timeout due to inactivity
