### ISSUE TITLE
configd: per action detach / async support

### ISSUE THREAD

**Issue by fichtner** [opnsense/core#1509]
Hi Ad,

What do you think about adding an action parameter to make (mostly certain long-running) actions optionally asynchronous, but blocking per action? Internally this would be a fork, we wait for the child to exit before we let another of those actions run (if it runs already we simply consider it started and exit ok).

Cheers,
Franco

**Comment by AdSchellevis** [comment]
Hi Franco,

I'm not sure why we need a fork, our processes are already threaded and there is the possibility to detach (https://github.com/opnsense/core/blob/master/src/opnsense/service/modules/processhandler.py#L174).

What issue would we solve by changing this?

Cheers,

Ad

**Comment by fichtner** [comment]
Alright, problem description: the remote ACL can take a long time, failing the 2 minute timeout. In the background, the process keeps running, blocking other maybe more important configd work.

Current solution: fork the script via configd. In this case we have no way of knowing the user won't trigger the script again, so we would have to add a lock to it... actually for every configd script, but sometimes not full written scripts but shell commands (or worse sequences).

Wantend solution: configd would "track" the state of the background job by action. in this case it would pose as the lock itself, preventing a second background job of the same running job if it was triggered twice, cutting out the need for locks underneath the code. Here we could even add a "poll" script to probe for the running status of a particular action. It would also give configd the chance to parallelise the work it is doing in smaller doses.

Interface changes:
* The actions would receive a new "runmode:" parameter (or whatever it is called) adding the option "background". This is required, but it automatically compatible with the client side, except that GUI needs to be aware that the "OK" is not for successful run, it is for starting the action.
* A facility of probing for action status (running, not running, last known return status). This is optional to improve user feedback.

What do you think?

**Comment by AdSchellevis** [comment]
I'm not sure, it's not supposed to block in the current setup, if forking is the only solution, we should certainly consider it, but I think threading should also fix our issue here. 
Let's first see why this blocks now and if there's an easy fix, before overcomplicating things here. We might end up adding a lot of logic for process control, which might be nice in terms of features but not so much in terms of complexity.

Let's keep this issue open, until we know why something blocks now.

**Comment by AdSchellevis** [comment]
@fichtner I can't reproduce this, I've just tested the following:

create a configd service config (actions_test.conf), using the following:

```
[sleep]
command:/bin/sleep
parameters:%s
type:script_output
message:sleep for %s


[echo]
command:/bin/echo
parameters:%s
type:script_output
message:echo %s
```

Then restart configd and open two consoles, first start:

`configctl test sleep 10000
`

Then during the time the sleep is running, start the following in the other console:
`configctl test echo test
`

Which returns instantly at my end, are we looking for something else? or is this what you where looking for? (the processes theirselves are already forked)
