### ISSUE TITLE
Add more packages to pkg.opnsense.org

### ISSUE THREAD

**Issue by rmx-it** [opnsense/core#151]
Hi,
since opnsense uses a few non-standard options to compile its packages this makes it difficult to
use the FreeBSD pkg repo additionally.

For example the opnsense pkg requires bind-tools.
When trying to installing bind910 from the FreeBSD repo pkg would reinstall bind-tools from the
FreeBSD repo and deinstall the opnsense pkg beforehand...

Ideally opnsense would provide all packages (or all packages with special options incl. their dependent 
packages)...

But currently at least a few additional ports would be sufficient for me:
benchmarks/netpipe
comms/gnokii
comms/kermit
dns/bind910
dns/ddclient
ftp/curl
mail/smtp-cli
net/rsync
sysutils/ipmitool
sysutils/tmux
www/tinyproxy

Or is there a different way to get missing packages without conflicting with the official opnsense ones?

**Comment by fichtner** [comment]
The simplest way is setting up a custom mirror. The ports tree used to be heavily out of sync up till Monday, but I have improved the sync script to pull in all currently unused ports as well.

The list of packages provided is: https://pkg.opnsense.org/FreeBSD:10:amd64/latest/All/

curl and tmux we do have; ipmitool, rsync I can put up; bind910 is probably going to cause a lot of trouble, it does indeed conflict with bind-tools; the others I'll have to look at one by one

Depending on how lightweight they are we may include them, but we neither have a large build server that would enable all potentially useful ports to be build nor do we have the support to maintain such a large ecosystem at this point in time. It costs quite a bit of time to rebuild the ports for updates and the more ports we have the longer the release process is going to take (we have at least 4 passes through all ports: OpenSSL+amd64, OpenSSL+i386, LibreSSL+amd64, LibreSSL+i386).

I'll report back on which ones we can include tomorrow after checking their dependencies and build times.

**Comment by fichtner** [comment]
netpipe is marked broken, gnokii did not build, bin910 I won't merge right now due to suspecting it'll flush opnsense package out of the system as well when it comes from our mirror (pkg install -f might or might not work). help to progress on this front is needed.

everything else has been merged: https://github.com/opnsense/tools/commit/da78fa2d293ccba3f9527cbeaf80fd29c21efebe

**Comment by rmx-it** [comment]
Hi,
thanks a lot for your efforts so far!
For gnokii, do you have a build log by chance?
In my FreeBSD 10 poudriere env it does build.

And yes, as it seems, bind-tools and bind910 are mutially exclusive. (See the conflicts entry)
One of the big shortcoming I had with all *sense appliances was the absence of a full dns server.
From a space point of view it shouldn't make that much difference to use bind910 instead of bind-tools, even if there is currently no configuration dialog for the dns settings.
This would - on the other hand - give the possibility to use a manual config...

Thanks again!

BTW: Since I'm a FreeBSD src/ports committer too please ask if you want tomething changed in the base src/ports - if its appropriate for the base...

Greetings
---
Michael

**Comment by fichtner** [comment]
Gnokii fails with: no rule to make targer /usr/lib/libsdp.so -- bluetooth support is turned off in the base but it can certainly be enabled. Will take a bit of time to sync in, but hopefully in time for 15.1.10.

If you could drop me a line at franco@ project website that would be great for a direct contact. thanks :)

**Comment by fichtner** [comment]
gnokii is in now but needed this fix for when building without X11: https://github.com/opnsense/ports/commit/d89e974f2e1aff14dc8da11fa9e6c5d8f436d4a7

**Comment by fichtner** [comment]
FYI: kermit doesn't build with LibreSSL
