### ISSUE TITLE
Upgrade to 17.1.4, cannot login with 2FA enabled account

### ISSUE THREAD

**Issue by jonakarl** [opnsense/core#1511]
Hi, 

I have enabled 2FA  for webgui access and after a upgrade to 17.1.4 (from 17.1.3) I cannot logon.
I also use 2FA for (open) vpn access and that also stopped working after the update. 
Luckily I had configured ssh keys and was able to reset the admin password that way. 

Disclaimer: 
I must admit I have had problems with the vpn 2FA access before (requiring sometimes multiple tries). However, after the 17.1.4 update it was impossible to logon and also if I try to test the 2FA via the GUI testing tool it fails.

**Comment by AdSchellevis** [comment]
@jonakarl are you sure your time was properly set? 2FA requires a accurate clock.

**Comment by jonakarl** [comment]
Hmm, after some further checking I notified that the ntp client is in Unreach/Pending state. 

Closing this as I think it is related to ntp problems
