### ISSUE TITLE
Default install of opnsense ntp is not working 

### ISSUE THREAD

**Issue by jonakarl** [opnsense/core#1513]
To be able to use 2FA the time on my opnsense machine needs to be correct. 

I have enabled ntp in the gui but whatever server I add in the server field the state is always "Unreach/Pending".

From the shell of the opnsense machine (17.1.4) I can do as root : 
```
root@gw:~ # ntpdate -u pool.ntp.org
30 Mar 16:41:46 ntpdate[30820]: adjust time server 192.36.143.153 offset 0.024567 sec
root@gw:~ # ntpdate pool.ntp.org
30 Mar 16:41:58 ntpdate[30914]: no server suitable for synchronization found
```
As I understood it ntpdate -u uses unprivileged ports while ntpdate (without -u uses privileged ports) 

Most likely this is a a firewall rule that blocks this but if that is the case the firewall should be updated to allow this traffic when enabling the ntp settings in the GUI or this should be documented somewhere.

Note: My purpose is not to let the opnsense machine be a ntp server for my internal LAN but to act as a client and recive clock updates form a external server

**Comment by fichtner** [comment]
NTP should work out of the box, are you sure it's not another firewall blocking the sync?

**Comment by jonakarl** [comment]
Pretty sure, the same commands works perfectly fine from a machine outside the firewall (although on a different subnet). 

I will will double check on monday with a machine on the same subnet as my fw to be 100% sure.

**Comment by jonakarl** [comment]
Closing this as it was a external firewall causing the port block. Sorry for the confusion.
