### ISSUE TITLE
[Bug] Suricata rule lookup crash

### ISSUE THREAD

**Issue by L1ghtn1ng** [opnsense/core#1516]
While trying to look at the rules on 17.1.4 64-bit I get the follwoing crash and this is even after a reboot

configd.py: [765dd116-17aa-4f24-87ea-61c7dcb83e14] Script action failed with Command '/usr/local/opnsense/scripts/suricata/queryInstalledRules.py /limit "10" /offset "0" /filter "" /sort_by "sid"' returned non-zero exit status 1 at Traceback (most recent call last): File "/usr/local/opnsense/service/modules/processhandler.py", line 477, in execute stdout=output_stream, stderr=error_stream) File "/usr/local/lib/python2.7/subprocess.py", line 541, in check_call raise CalledProcessError(retcode, cmd) CalledProcessError: Command '/usr/local/opnsense/scripts/suricata/queryInstalledRules.py /limit "10" /offset "0" /filter "" /sort_by "sid"' returned non-zero exit status 1

**Comment by AdSchellevis** [comment]
@L1ghtn1ng can you execute the following on a console and post the output?

`/usr/local/opnsense/scripts/suricata/queryInstalledRules.py /limit "10" /offset "0" /filter "" /sort_by "sid"`

**Comment by L1ghtn1ng** [comment]
I get the following

Traceback (most recent call last):
  File "/usr/local/opnsense/scripts/suricata/queryInstalledRules.py",
line 46, in <module>
    rc.create()
  File "/usr/local/opnsense/scripts/suricata/lib/rulecache.py", line
193, in create
    'fieldvalues': ':' + (',:'.join(self._rule_fields))}, rules)
sqlite3.ProgrammingError: You must not use 8-bit bytestrings unless you
use a text_factory that can interpret 8-bit bytestrings (like
text_factory = str). It is highly recommended that you instead just
switch your application to Unicode strings.

**Comment by AdSchellevis** [comment]
@L1ghtn1ng can you try https://github.com/opnsense/core/commit/5f17abb3fa294da78edffc375c7e3a873597cdf4 ?

it looks there's some unicode text in your rules, which result in parsing issues in sqlite, because I don't have the same files, I can't properly test it here.

**Comment by L1ghtn1ng** [comment]
@AdSchellevis That did the trick, they now load. I am just using the rules that come in OPNsense

**Comment by L1ghtn1ng** [comment]
Can we get this pulled in for 17.1.5?

**Comment by AdSchellevis** [comment]
@L1ghtn1ng ok, thanks for confirming. Let's ask @fichtner if he can pull this one in.

**Comment by fichtner** [comment]
I think I have another case, if this is confirmed there too it's going into 17.1.5 for sure.

As for the trigger of this issue, I don't see anything in particular, maybe a Framework change in the ports? Or did ET Open rules maybe start embedding UTF-8? The timing for 17.1.4 is off: it was released on Wednesday, but reports for this problem are not older than 24 hours...

**Comment by L1ghtn1ng** [comment]
Probably the latter. As that would be the only variable here that would make sense, as you have said you cannot see anything in ports.

Sent from phone


________________________________

**Comment by fichtner** [comment]
Confirmed. Backport+Close.
