### ISSUE TITLE
Openvpn CSO problems

### ISSUE THREAD

**Issue by jonakarl** [opnsense/core#1520]
I have multiple VLAN/subnets (one subnet per vlan) where only certified personel should have access to the mgmt subnets. 
I have a problem with cso where I get no traffic through the firewall to my internal lan when using a different tunnel network from the one I specify on the openvpn server page. I had this working in pfsense but I cannot get it working in opnsense. 

Current setup: 
I have two openvpn servers, one for admins and one for clients, "user" tunnel network is 10.0.8.0/24 and admin uses 10.0.10.0/24. 
I block all outgoing traffic to the admin lans from 10.0.8.0/24 on the openvpn interface.
This works but is cumbersome.

What I would like to have: 
1 openvpn server and use cso to put the admin personal on a different tunnel network (ie 10.0.10.0/24) so I can filter this in the firewall later. 

The cso works to the extent that when I connect with a user that matches the cso, I get 10.0.10.1 as gateway  (strangely also a route to 10.0.8.5). However I cannot ping any ip on the other side of the tunnel (10.0.10.2, my side of the tunnel works). 

Any clues on where to start debugging would be helpful since I cannot see anything in the logs. 

(I have asked the same question in the forum but I am unsure where the best place are to ask, please close this issue if belongs more to the forum section and you do not believe it to be a bug)
Forum thread is here: https://forum.opnsense.org/index.php?topic=4865.msg19102#msg19102

**Comment by AdSchellevis** [comment]
timeout due to inactivity
