### ISSUE TITLE
Unbound in 17.4 doesn't handle timezone any good

### ISSUE THREAD

**Issue by sennerholm** [opnsense/core#1521]
Hi!
When I have the settings on my opnsense to Europe/Stockholm the /usr/local/opnsense/scripts/dns/unbound_dhcpd.py generates empty /var/dhcpd/var/db/dhcpd.leases files (wish should contain the leases). It works if I changed my local timezone to UTC.

Probably because the times in /var/dhcpd/var/db/dhcpd.leases is in UTC and the loading in /usr/local/opnsense/site-python/watchers/dhcpd.py is in localtime. I think that, 

if field_name in ('starts', 'ends', 'tstp', 'tsfp', 'atsfp', 'cltt') and len(parts) >= 3:
               dt = '%s %s'%(parts[2], parts[3])
               try:
                   field_value = time.mktime(datetime.datetime.strptime(dt, "%Y/%m/%d %H:%M:%S;").timetuple())
is the responsible part and that mktime should be changed to calendar.timegm() if my understanding of the code is correct, but I'm not a python hacker. 

Sincerely
Mikael

**Comment by AdSchellevis** [comment]
Hi Mikael, you're right, I've totally misinterpreted the lease timestamps. 
The fix seems to be as easy as you suggested, tested it on my end with the following timestamp:

`2017/03/18 20:12:28;
`
Which converts to `1489867948` when using calendar.timegm() {was 1489864348 in timezone Europe/Amsterdam}

I will push a fix and close the issue, feel free to reopen if this doesn't fix your issue.

Best regards,

Ad
