### ISSUE TITLE
locales directories in /usr/share/locale/ are empty

### ISSUE THREAD

**Issue by sachaz** [opnsense/core#1522]
I had an issue launching tmux:
tmux: need UTF-8 locale (LC_CTYPE) but have US-ASCII
ok the utf8 locale wasn't declared, fixed.

and then:
tmux: invalid LC_ALL, LC_CTYPE or LANG
ls /usr/share/locale/en_US.UTF-8/ => empty !

I had to get the base.txz uncompress the locale in the right path and it's works !

So my issue is all the directories in /usr/share/locale are EMPTY !

----------------
Kind regards

**Comment by fichtner** [comment]
Thanks for the report, I guess because if this: https://github.com/opnsense/tools/blob/master/config/17.1/src.conf#L19

**Comment by sachaz** [comment]
Nice: that's the point.
Thanks !

**Comment by fichtner** [comment]
The next kernel/base update will fix this, not sure if 17.1.5 will do this already, but it's committed already: https://github.com/opnsense/tools/commit/e9882554428519b38fd95ddb92604ee63737cd32


Cheers,
Franco
