### ISSUE TITLE
IPv6 NAT/Port forwarding does not work as expected: no TCP connection to LAN IPv6 link local address possible

### ISSUE THREAD

**Issue by chrwick** [opnsense/core#1523]
OPNsense 17.1.4-amd64

I need to forward a TCP port from WAN to LAN for IPv6.
For this purpose I setup the port forwarding as I would do it with IPv4, but instead I use the IPv6 link local address together with the zone id to specifiy the redirect target ip.
LAN is igb0 and WAN is igb1 in my setup.
So I specify fe80::ba27:ebff:fee8:320e%igb0 as the redirect target ip.
As there is no complain, I assume that the specified IPv6 link local address with zone id is valid.

The entry is accepted, but leads to some alerts:
`opnsense: /usr/local/etc/rc.filter_configure: New alert found: There were error(s) loading the rules: /tmp/rules.debug:101: rule expands to no valid combination - The line in question reads [101]: pass in quick on $WAN inet6 proto tcp from any to fe80::ba27:ebff:fee8:320e%igb0 port 17574 flags S/SA keep state label "USER_RULE: NAT "
`

**Comment by chrwick** [comment]
Just a small additional info:

Using the infterface diagnostic ping, I can successfully ping the IPv6 link local address with zone id.

**Comment by AdSchellevis** [comment]
timeout due to inactivity
