### ISSUE TITLE
Issues with WAN IP renewal after provider outage

### ISSUE THREAD

**Issue by cvbkf** [opnsense/core#1525]
I have a OPNSense running on an intel atom D510MO, directly connected to a cisco EPC3212 cable modem running as transparent bridge (WAN IP provided to OPNSense).  WAN interface is configured to DHCPv4 and DHCPv6.

yesterday night my provider had some issues leading to a network outage, which i noticed in the morning because i couldn't access the internet due to timeouts.  first, i suspected the cable modem and did a warm and a cold reboot, which did not help.  the modem's ip (192.168.100.1) wasn't accessible as usual, too. 

the wan interface had no ip, so i did a manuel renew under interfaces -> overview. after that, internet was fine again. 

i did some log file digging, and it looks like in case of failure the wan interface gets an internal ip adress from the cable modem (192.168.100.10) and does not recognize if the "real" wan ip comes back online. 

relevant logs are attached
[opnlog.txt](https://github.com/opnsense/core/files/902468/opnlog.txt)

the "Could not find IPv4 gateway for interface" entry is repeated a few hundred times till the first cable modem reboot at 10 o'clock. 
"can't allocate llinfo" is repeated a few dozen times, too

**Comment by AdSchellevis** [comment]
timeout due to inactivity
