### ISSUE TITLE
Questions and proposals about Captive Portal

### ISSUE THREAD

**Issue by gertfriend** [opnsense/core#1526]
Where can i set a static redirect URL in the Captive Portal so that the client, after logging in, will be redirected always to for example info.client.com? Is ist possible to introduce a field in Captive Portal to set this?
Thank you for your great work

**Comment by AdSchellevis** [comment]
@gertfriend please use our forum for discussions and questions, it's quite impractical for us to handle multiple questions per issue.

To redirect to a standard page in CP, just download the template and change the redirect here: https://github.com/opnsense/core/blob/master/src/opnsense/scripts/OPNsense/CaptivePortal/htdocs_default/index.html#L89

**Comment by gertfriend** [comment]
Thank you for the answer and sorry for the multpost, i will use the forum for the other questions and leave this.
