### ISSUE TITLE
OpenVPN config not fully synced

### ISSUE THREAD

**Issue by nkfilis** [opnsense/core#1528]
We copy the OpenVPN config among other things thru HA from box A to B. When we try to connect to the OpenVPN server on B, we don't get any DNS servers assigned, even though they show on "DNS Servers" in the OpenVPN Server edit form on B. Submitting the (unchanged) form and restarting the OpenVPN service on B fixes the issue. Just restarting the service didn't help.

**Comment by AdSchellevis** [comment]
timeout due to inactivity
