### ISSUE TITLE
Not able to input numbers in "Destination port range" fields.

### ISSUE THREAD

**Issue by ruffy91** [opnsense/core#1529]
I am not able to input port numbers in the NAT and Firewall Rule "Destination port range" fields.
I created port aliases for the start and end port of the range (RTP, about 1000 Ports).
But I am not able to use the aliases in the firewall rules, as start and end port have to be the same alias.
I cannot believe that i really have to create 1000 port aliases and NAT rules one by one.

What am I doing wrong?

I am using 17.1.4 and tried Firefox and Chromium

**Comment by fichtner** [comment]
Hi Fabian,

You should be able to create either a single alias port with all addresses or a nested alias with other port aliases embedded. With this, simply select the single port alias referencing all ports and you should be done. :)


Cheers,
Franco

**Comment by ruffy91** [comment]
When trying to create a port alias for a range I get the following error:
"The following input errors were detected:
16384-32768 doesn't appear to be a valid port number"

**Comment by fichtner** [comment]
16384:32768 should work? We can fix this up on the input side I think

**Comment by ruffy91** [comment]
Yes this works. Thanks Franco.
Also when defining a range in NAT or Firewall I have to select (other) as port and can then input a number in the new fields that appear. The finished rule then shows 16384-32768 as port range. (- instead of :)
I think the best would be:
- Do not allow 1 to 65000 as a port alias name but take them directly as a port number instead of (other) or show (other) as a suggestion when entering numbers in this field.
- Use - and : consistently. Changing to : in rules should not give problems, while changing to - would mess with existing port aliases

**Comment by fichtner** [comment]
Consistency is a problem here, I agree. The reason is that internally pf(4) uses ":" while for all user-facing logic it should rather be presented as "-".
