### ISSUE TITLE
Intrusion detection interferes with port forwarding

### ISSUE THREAD

**Issue by tkald** [opnsense/core#1530]
While port forwarning and intrusion detection both active on my Opnsense, port forwarding misbehaves.
Packet retransmission loops, hanging connections.

See issues described in #1410 

As soon as I disable Intrusion detection, port forwarding works as expected.
I do have v17.1.4 multiwan HA setup with CARP and LAGG interfaces...

![image](https://cloud.githubusercontent.com/assets/8062491/24828807/8a193928-1c6e-11e7-8c58-449e7b8e7157.png)

So WAN1 and WAN2 are not real physical interfaces but LAG interfaces in failover mode.
Could those LAG interfaces be the issue?

**Comment by fichtner** [comment]
@tkald does this still happen on 17.7?

**Comment by tkald** [comment]
I haven't upgraded to 17.7 yet. 
I'll report back when I'm on the latest release...

**Comment by tkald** [comment]
@fichtner Yes, this issue still present in version 17.7.1

**Comment by fichtner** [comment]
Thanks for testing. If it's really aborts in the IDS can you try turning off IPS mode just for confirmation?

**Comment by tkald** [comment]
When IDS is ON and IPS mode is turned OFF, it seems to work fine.

**Comment by fichtner** [comment]
@tkald I have heard no other case like this until now. There also was a port forward fix for shared forwarding in 17.7.8 that was happening with multi-wan only. is this still relevant or fixed?

https://github.com/opnsense/changelog/blob/0ac8a37092bf5436323136fa02051e6298f7799a/doc/17.7/17.7.8#L55

**Comment by tkald** [comment]
Just checked, it's still an issue with version  17.7.10.
Shared forwarding is disabled on my setup.

**Comment by fichtner** [comment]
Hmm, I'm totally unsure how we can inspect this further. ;(

**Comment by tkald** [comment]
Seems to me that IPS mode breaks things, as when it's off (and IDS is on), port forwarding works as expected.
I do have VLAN Hardware Filtering enabled though under interfaces: settings. I'll test it with disabled state in a minute...

**Comment by fichtner** [comment]
Can you check /var/log/suricata.log for its statistics? If all we're seeing is dropped packages or reordering I'm simply not sure how "IPS" can be fixed from our perspective. It looks like an issue in the FreeBSD stack if Suricata does not misplace packets itself. Statistics counters from your interfaces where IPS runs helps too. How many interfaces do you use Suricata on anyway? Is it internal or external?

**Comment by tkald** [comment]
There's not a single dropped packet in suricata.log

No In/out errors or collissions on WAN1 and WAN2 interfaces. 
There are blocked packets on Interfaces: Overview page but I assume those come from firewall?

I'll try testing LAN interface after christmas...

**Comment by tkald** [comment]
Discovered another issue that might be related to this topic - when I enable "Shared forwarding" all nat port forwarding will stop over primary wan.
My own vpn connection also dropped and switched to router's secondary wan, where it stayed up.

**Comment by fichtner** [comment]
Second wan is set up as default gateway? If yes that is a known bug, but I don’t have the ticket number right now.

**Comment by tkald** [comment]
Nope, secondary wan is not default gw, primary wan is default gw.
I do have same port forwardings over both wan-s.

**Comment by fichtner** [comment]
Ah ok, the other one was about shaping, found it but unfortunately not related... https://github.com/opnsense/core/issues/1900

**Comment by tkald** [comment]
Tried also Intrusion detection on DMZ lan interface, from outside, over wan, port forwaring worked ok, but bunch of other servers in alternative lan became inaccessible as a result from our monitoring system located in DMZ lan.

**Comment by fichtner** [comment]
Closing this in the hope it’s not relevant anymore. If not please ping.
