### ISSUE TITLE
[Question] Language selection in the login form

### ISSUE THREAD

**Issue by fabianfrz** [opnsense/core#1532]
What do you think about selecting the language at login?

The preselected language is the system default which is also used as a fall back if no session information from a login is available.

This may make the system more user friendly if the admins are from multiple countries.

BTW: I don't need this feature but had the idea and wanted to document it here

**Comment by fichtner** [comment]
first step: #1218

**Comment by fabianfrz** [comment]
that may make the older one obsolete...

**Comment by fabianfrz** [comment]
@fichtner feel free to close this if you like. However it could be a problem if a german admin would log in into an asian (chinese, japanese) appliance. The language for that admin would have to be set up first.

**Comment by fichtner** [comment]
I don't like the language selection on login because it

(a) overrides the user's preference
(b) we don't know the user preference before login ;)

**Comment by fichtner** [comment]
per user language + language selection in the top corner would probably be best, but then again saving the config.xml from switching the language via the main navigation seems overkill also

**Comment by fabianfrz** [comment]
Maybe a globe icon right of the search bar linking to the correct settings may solve that problem.

**Comment by fichtner** [comment]
it should link to a profile page where such settings could be changed? the password change page is best for that in general, but has no other settings yet.

what I want to avoid is selecting languages without saving them for the next time and and also prevent saving them all the time through switching them from a location on all pages like the globe suggestion

difficulty is letting users know where they can change the language without being able to change the language everywhere... know what I mean?

**Comment by fabianfrz** [comment]
yes, but it can be stored in the local storage (last selection). Anyway we need a solution for the issue.

**Comment by fichtner** [comment]
should really add per user selector...
