### ISSUE TITLE
Host alias cannot be "ftp"

### ISSUE THREAD

**Issue by pawal** [opnsense/core#1536]
Perhaps "ftp" is a reserved word, but it is not obvious from the error message:

> The following input errors were detected:
> The alias name must be less than 32 characters long and may only consist of the characters a-z, A-Z, 0-9, _.

Other three letter names can be added.

Using:

OPNsense 17.1.4-amd64
FreeBSD 11.0-RELEASE-p8
OpenSSL 1.0.2k 26 Jan 2017

https://192.168.0.1/firewall_aliases_edit.php

**Comment by fichtner** [comment]
This happens every now and then, there's an open ticket, I'll take care of it tomorrow. Closing this in favour of #1443

**Comment by fichtner** [comment]
fixed via https://github.com/opnsense/core/commit/68faafd185c01b594a292af0c6ec66d93136c70b, likely part of 17.1.5

thanks again for the report :)
