### ISSUE TITLE
max-src-conn-rate

### ISSUE THREAD

**Issue by sachaz** [opnsense/core#1537]
Hi,

On the BSD's Packet Filter, I'm doing a macros like:
NOFLOOD ="synproxy state (source-track rule, max-src-nodes 8, max-src-conn 8, max-src-conn-rate 10/300, overload <BLACKLIST> flush global)"

On a OPNSense firewall rule in the Advanced Options,  I don't know how to do the same with the following options:
Max states
Max source nodes
Max established 
Max source states
Max new connections
State timeout

Is it relevant to have the availability to do macros on OPNSense firewall, feature request ? 

Thanks,
Sacha

**Comment by fichtner** [comment]
Can you please rephrase your question? I don't know what to answer at the moment.

**Comment by sachaz** [comment]
done

**Comment by AdSchellevis** [comment]
timeout due to inactivity
