### ISSUE TITLE
More context when creating new firewall rule

### ISSUE THREAD

**Issue by sachaz** [opnsense/core#1539]
Hi,

when I'm creating a new rule for the firewall, I have no context of the rule, like in the Firewall: Rules page. Could we keep a view on this page when create a new rule or have on the left menu Firewall / Rules a submenu with the interfaces name  ?

how to copy rule to a different interface, is it a feature request ?

Thanks

**Comment by fichtner** [comment]
Hi @sachaz,

The latter would work, although for long interface lists that would be annoying for those users as well. Ideally, the rules pages should be moved to the MVC where we can do "modal" edit forms for what you suggest here. I don't see this happening for our static pages.


Cheers,
Franco

**Comment by sachaz** [comment]
+ how to copy rule to a different interface ?

**Comment by fichtner** [comment]
You can't unless it's a floating rule which gives the opportunity to change the interface. It's a feature request that belongs to #1538.

There is no easy way around this: how should we know where to copy? One could make the interface configurable per rule even for the fixed interfaces, effectively moving the rule, but the order will be wrong and the cloning will be non-obvious.

**Comment by AdSchellevis** [comment]
timeout due to inactivity

**Comment by duese22** [comment]
> You can't unless it's a floating rule which gives the opportunity to change the interface. It's a feature request that belongs to #1538.
> 

Full circle.
