### ISSUE TITLE
IPsec desktop widget active counters display wrong status

### ISSUE THREAD

**Issue by AdSchellevis** [opnsense/core#154]
Copied from https://github.com/opnsense/core/issues/64#issuecomment-96393444

The connection state in Status --> IPsec is now indeed correct, however I noticed that the IPsec widget doesn't display them correctly. Currently I have 7 working tunnels and the widget shows 7 inactive. Sometimes it shows 3/7 or other combinations. I have tested this on two different machines.
ipsec widget

**Comment by fichtner** [comment]
I heard differently from another user. Maybe it depends on the type of connection or only shows a certain amount?

**Comment by reetp** [comment]
This is possibly related to an error I was getting 

PHP Warning:  Invalid argument supplied for foreach() in /usr/local/www/widgets/widgets/ipsec.widget.php on line 56
Invalid argument supplied for foreach() in /usr/local/etc/inc/vpn.inc on line 39
Invalid argument supplied for foreach() in /usr/local/etc/inc/vpn.inc on line 39

That seems to stem from this 

56	    foreach ($config['ipsec']['phase2'] as $ph2ent) {

No check is made to see if the variable is set/exists although funnily enough at line 90 before it draws the page it IS checked !

    90	if (isset($config['ipsec']['phase2'])) {
    91	?>

Again, not sure what is really intended here so not sure of the best way to sort it out.

The issues in vpn.inc again relate to no check on variables here - clearly there is nothing set for $log_levels - possibly this sort itself out once it has some information

34  function vpn_ipsec_configure_loglevels($forconfig = false)
    35  {
    36          global $config, $ipsec_loglevels;
    37  
    38          $cfgtext = array();
    39          foreach ($ipsec_loglevels as $lkey => $ldescr) {
    40                  if (!isset($config['ipsec']["ipsec_{$lkey}"]) && !$forconfig)

Again, not sure of the best way to deal with this
