### ISSUE TITLE
Traffic Shaper ignored outgoing traffic from WAN, when using route to / gateway firewall rules

### ISSUE THREAD

**Issue by SeTk** [opnsense/core#1541]
Configuring a traffic shaper with standard gateways works using shaper rules for wan all outgoing an all incoming traffic (two rules for two pipes for upload and download).

But traffic shaper ignores outgoing traffic from wan-interface, when routed by an route to / gateway firewall rule. So all connections, routed to an specific gateway by a firewall rule, bypasses the limiter / traffice shaper.

**Comment by fichtner** [comment]
Yup, it's a very old bug between pf route-to and the network stack. You can try to use the Firewall: Settings: Advanced [ x ] use shared forwarding option, but it doesn't work in all cases yet.

More work is needed here, which we will pick up as time permits. For now, the option should address the problem for the most part.


Cheers,
Franco

**Comment by SeTk** [comment]
Thank You for your explaination, but it is not working.
- Firewall rule with sepcific gateway
- Traffic shaper for download, assigend all incoming traffic from specific wan connection: Working.
- Traffic shaper for upload, assigend all outgoing traffic from specific wan connection: **Not working.**

**Comment by fichtner** [comment]
With the shared forwarding setting on or off?

**Comment by fichtner** [comment]
Also, please provide a version info, it's a crucial piece of the puzzle. :)

**Comment by SeTk** [comment]
Shared forwarding is on.

OPNsense 17.1.4-amd64
FreeBSD 11.0-RELEASE-p8
OpenSSL 1.0.2k 26 Jan 2017

Here some screenshots:
<img width="686" alt="pipe" src="https://cloud.githubusercontent.com/assets/27353744/24960917/86ad5fae-1f97-11e7-9129-f69db83e8ec4.PNG">
<img width="687" alt="shaper-rule" src="https://cloud.githubusercontent.com/assets/27353744/24960925/8a828c3a-1f97-11e7-8db3-6fce9e69ce6e.PNG">
<img width="652" alt="status" src="https://cloud.githubusercontent.com/assets/27353744/24960928/8c7f4da2-1f97-11e7-97a9-82f38ee13c0a.PNG">

**Comment by fichtner** [comment]
This is true for IPv6 but not IPv4?

**Comment by SeTk** [comment]
We are using IPv4 only (for now) - so alle rules are true for IPv4 and IPv6 or IPv4 only.
I have added a second traffic shaper with default gateway...
I found all uploading IPs (against firewall-rule-gateway-setting) there.

Our Setup:
Default local nets - some firewall rules without gateway settings - default gateway
Specific local net - firewall rule with gateway setting - specific gateway

Now, with traffic shaper configured like posted - with download and upload pipe for default nets/gateway and download and upload pipe for specific net/gateway.

Alle incoming/download packages are assigned to the correct pipe: download to specific nets to specific-net-download-pipe; download to default nets to default-net-download-pipe.
But all outgoing/upload packages are assigned to the default-net-upload-pipe, no matter whether from specific net (with specific-gateway-rule) or from default nets (without specific-gateway-rule).

Maybe that helps to solve our issue.

**Comment by fichtner** [comment]
Ok, I'll have to forward this to @jschellevis for a peek

**Comment by SeTk** [comment]
To check behaviour I disabled shared forwarding.
Nothing changed - same behaviour like described above.
Same after reboot.

There is an other buggy(?) behaviour in both cases traffic shaping on or off.
We have only one interface for our specific net an a single firewall rule, which routes to the specific gateway. But traffic shaper shows some few connections from that specific interface on default-wan/gateway-pipes (upload and download also).

Here our rule (GW3 is our specific gateway):
<img width="762" alt="089rule" src="https://cloud.githubusercontent.com/assets/27353744/24963467/f87c68da-1f9e-11e7-92d4-902363b98f29.PNG">

Seems like traffic shaper detectes packages wrong or firewall-gateway-setting does not match all packages but passes packages to default gateway...

Tell me, which information do you need or how I can help you.

**Comment by docteurmicro50** [comment]
Any new on that issue?
I was using limiter into pfsense with gateway groups but right now it's an issue issue for me into opnsense...

Thanks and good luck!

**Comment by fichtner** [comment]
Should work since 17.1 with the "shared forwarding" option enabled in normal setups. Closing this.

**Comment by docteurmicro50** [comment]
Thanks!
