### ISSUE TITLE
Traffic Shaper documentation seems to be wrong

### ISSUE THREAD

**Issue by SeTk** [opnsense/core#1542]
There seems to be an issue in yours traffic shaper documentation.

Mapping all >destinations-masks< to >share bandwidth<
and all >source-masks< to >limit all connection by whole pipe bandwidt< sounds wrong.

Detailed explained here:
https://forum.opnsense.org/index.php?topic=4949.0

**Comment by mimugmail** [comment]
This is fixed now, can also be closed @fichtner ...
