### ISSUE TITLE
Unbound config error

### ISSUE THREAD

**Issue by sachaz** [opnsense/core#1543]
root@rosebud:~ # unbound-control reload
/var/unbound/unbound.conf:28: error: unknown keyword 'serve-expired'
/var/unbound/unbound.conf:28: error: stray ':'
/var/unbound/unbound.conf:28: error: unknown keyword 'no'
read /var/unbound/unbound.conf failed: 3 errors in configuration file
[1492083311] unbound-control[56375:0] fatal error: could not read config file

**Comment by fichtner** [comment]
Needs unbound 1.6, what version are you on?

**Comment by sachaz** [comment]
I have a default opnsense-17.1.4:
root@rosebud:~ # pkg info opnsense
opnsense-17.1.4
...
root@rosebud:~ # pkg info unbound
unbound-1.6.1
...

**Comment by fichtner** [comment]
# which unbound-control

I think you are invoking the FreeBSD Unbound from the base system by accident?

**Comment by fabianfrz** [comment]
Have you also tried to call it this way?
https://github.com/opnsense/core/blob/master/src/opnsense/scripts/unbound/unboundctlwrapper#L72

**Comment by fichtner** [comment]
Same issue as described and explained here:

https://forum.opnsense.org/index.php?topic=5039.0


Cheers,
Franco
