### ISSUE TITLE
[17.1.4] EFI boot fails 

### ISSUE THREAD

**Issue by enoch85** [opnsense/core#1544]
I just installed a new OPNsense box that will replace my old one. The new box is a Supermicro X10SDV-4C+-TP4F with IPMI. I installed the OS from IPMI with the cdrom ISO and chose to install in UEFI mode. Everything went fine and I imported my old config. So far so good. 

Then I rebooted the machine and this pops up on my screen and just sits there:
![efi](https://cloud.githubusercontent.com/assets/4511254/25010595/e6e12b5c-206a-11e7-8c47-05319c3b3ee1.jpg)

I've waited for 15 minutes now and nothing happens. If I press "reset" on the new box it works again. 

That lead me to think there was something wrong with the EFI boot, so I chose to set non UEFI as fisrt boot option, now it hangs here instead:
![nonefi](https://cloud.githubusercontent.com/assets/4511254/25010693/28101188-206b-11e7-97ec-59afc07a408d.jpg)

This is kind of disturbing as everytime I reboot I must hit reset. Will there be a fix implemented for this soon or should I simply re-install with non UEFI?

Thanks!

cc @fichtner

**Comment by enoch85** [comment]
Ok, not even a reboot helps now... :(

**Comment by fichtner** [comment]
Completely new box, right?

**Comment by enoch85** [comment]
@fichtner Yes

**Comment by fichtner** [comment]
hmm, does this thing still have a legacy boot mode in bios you could try?

**Comment by enoch85** [comment]
Hmm... I disabled all the other boot options and now it boots again. Let's see what happens if I reboot from GUI.

**Comment by enoch85** [comment]
> hmm, does this thing still have a legacy boot mode in bios you could try?

It has DUAL which means it boots both Legacy and UEFI.

Rebooted from GUI and same thing happens. :(

**Comment by fichtner** [comment]
Problem with DUAL is that GPT/UEFI install will always fire up UEFI.

Can you try to set the EFI-Console before reboot under System: Settings: Administration as the primary console?

**Comment by enoch85** [comment]
@fichtner Should I also change to UEFI only in BIOS?

**Comment by fichtner** [comment]
@enoch85 whatever works best. These first-time encounters are always tricky to guess.

**Comment by enoch85** [comment]
Changing to EFI-Console worked 1 time, will try several times...

**Comment by enoch85** [comment]
**EDIT** I was a bit too fast here... Now it stops here instead:

![efi2](https://cloud.githubusercontent.com/assets/4511254/25011939/415e5f1a-206f-11e7-946b-4a608e8b7a3c.jpg)

**Comment by enoch85** [comment]
@fichtner How can I bypass this? Nomatter what I do in BIOS I get stuck here.

**Comment by enoch85** [comment]
Here is a video:
https://cloud.techandme.se/s/6hhTCa845YGdDl0

**BIOS Settings**
- UEFI Only
- Disabled APCI (according to Pfsense troubleshooting guide)

**OPNsense settings**
- EFI Console

**Comment by enoch85** [comment]
*/me* re-installing with Legacy instead... Can't come around this issue.

**Comment by enoch85** [comment]
OK it works now. Yay. Thanks @fichtner for your guidance.

**Comment by enoch85** [comment]
Fdisk settings if they are to any use:
![fdisk](https://cloud.githubusercontent.com/assets/4511254/25013780/3b173e14-2075-11e7-829a-8ff7cb5af3eb.jpg)
