### ISSUE TITLE
ftp-proxy feature

### ISSUE THREAD

**Issue by fichtner** [opnsense/core#155]
For clients that's easy. For servers behind nat it's a little more difficult to present. Any takers?

https://doc.pfsense.org/index.php/FTP_without_a_Proxy
http://www.openbsd.org/faq/pf/ftp.html
https://www.freebsd.org/cgi/man.cgi?query=ftp-proxy&apropos=0&sektion=8&manpath=FreeBSD+10.1-RELEASE&arch=default&format=html

**Comment by langerma** [comment]
maybe this is interesting: http://wiki.squid-cache.org/Features/FtpRelay

**Comment by jschellevis** [comment]
just tested with ftp_port in squid as suggested by langerma
works fine with standard ACL lists in squid. Will add this feature to the squid proxy implementation.

**Comment by fichtner** [comment]
Thanks! The server-behind-firewall support is especially interesting if we could pull that off with squid. The client works for now. :)

**Comment by jschellevis** [comment]
![schermafbeelding 2015-04-29 om 15 29 54](https://cloud.githubusercontent.com/assets/9606698/7391939/ac788cd6-ee84-11e4-9adf-e87a37162bee.png) Something like this?

**Comment by jschellevis** [comment]
Done... squid sample log for ftp:
![schermafbeelding 2015-04-29 om 15 40 14](https://cloud.githubusercontent.com/assets/9606698/7392149/25462546-ee86-11e4-914f-edbf939da521.png)
and... sample configuration of FileZilla:
![schermafbeelding 2015-04-29 om 15 35 10](https://cloud.githubusercontent.com/assets/9606698/7392161/37b7dc4c-ee86-11e4-9af6-0d92f1f8366b.png)

**Comment by fichtner** [comment]
Like it! Not sure if it's enough for a ftp server behind the firewall as suggested in "FTP Server Protected by an External PF Firewall Running NAT" at http://www.openbsd.org/faq/pf/ftp.html but maybe it is? :)

**Comment by jschellevis** [comment]
Think that is intended the other way around... do we really need that?
What I just implemented with Squid is a ftp-proxy from inside to outside.. you can use it to block domains or file types... for instance add .+TXT$ to the blacklist and it will block all TXT files on http and ftp proxy.

**Comment by fichtner** [comment]
We were talking about this server-behind-NAT use case on IRC. But we definitely don't need it *now*.

**Comment by jschellevis** [comment]
I see... I misiunderstood the question... but now we got a really neat ftp proxy ;-)
I'll first implement the reverse http proxy and test, when that works I'll take another look at this to see if the ftp proxy from squid can be configured for that pupose as well..

**Comment by langerma** [comment]
i think squid works reverse as well

**Comment by jschellevis** [comment]
hope so, cause then it should be an easy fix after the http reverse is done and tested.

**Comment by fichtner** [comment]
CC @m4rcu5
