### ISSUE TITLE
[Feature] Add option to specify latency in pipe configuration

### ISSUE THREAD

**Issue by djflux** [opnsense/core#1550]
First, thank you for this incredible networking tool.

What I would like to do is specify a latency and possibly jitter in the pipe configuration so that a link with a high latency can be simulated.

If someone can point me in the right direction in the code I'd be happy to add this functionality and generate a pull request.

Thanks again,
Andy aka Flux

**Comment by AdSchellevis** [comment]
Hi Andy,

No problem, I can point you in the right direction for this.

First, extend the model to support your settings:
https://github.com/opnsense/core/blob/master/src/opnsense/mvc/app/models/OPNsense/TrafficShaper/TrafficShaper.xml

Next, add the field to the appropriate form:
https://github.com/opnsense/core/tree/master/src/opnsense/mvc/app/controllers/OPNsense/TrafficShaper/forms

Finally, add the logic to the ipfw template (please make sure the defaults don't change, so your addition can be activated without impact):
https://github.com/opnsense/core/blob/master/src/opnsense/service/templates/OPNsense/IPFW/ipfw.conf

It's probably best to mark these settings as advanced, like https://github.com/opnsense/core/blob/master/src/opnsense/mvc/app/controllers/OPNsense/TrafficShaper/forms/dialogPipe.xml#L59

If you have questions. just let me know,

Best regards,

Ad

**Comment by djflux** [comment]
Excellent.  I should have something for a pull request in the next few weeks.  Thanks again for taking the time to explain the places I should be looking.

Cheers,
Andy

**Comment by AdSchellevis** [comment]
timeout due to inactivity
