### ISSUE TITLE
Adding valid hostname as firewall alias returns as invalid

### ISSUE THREAD

**Issue by darkfires** [opnsense/core#1553]
Adding a firewall alias with the hostname "venus" returns The alias name must be less than 32 etc.

I tracked the problem down to etc/inc/util.inc is_validaliasname(), it calls getprotobyname($name), and because "venus" is in /etc/services it fails, but "Venus" works.  I feel this should be handled differently for names unless it could actually conflict with a protocol/service name (which hostnames cannot).

**Comment by fichtner** [comment]
We've updated the validation message to be more clear with #1443 which will be part of 17.1.5 next week. There is probably more potential for improvement, but it's a low value target for us as it's been this way for many years (not an excuse, just an observation).

If you want to help lift some of those restrictions I'm happy to review and discuss. :)


Cheers,
Franco
