### ISSUE TITLE
Aliases: Cannot allocate memory error for large URL Table (IPs)

### ISSUE THREAD

**Issue by ndejong** [opnsense/core#1555]
When defining a URL Table (IPs) that has a large number of ip + netblock entries we get the following console error message:-
```
04-24-17 02:35:59 [ There were error(s) loading the rules: /tmp/rules.debug:20: cannot define table blocklist_filtered: Cannot allocate memory - The line in question reads [20]: table  persist file /var/db/aliastables/blocklist_filtered.txt]
```

Several points:-
 - the URL table alias in question is successfully loaded by pfSense.
 - the URL source in question has 139079 entries and the source data at the URL is updated 4x a day
 - would it be possible to have a configurable item somewhere that allows for more memory to be allowed/provided to the underlaying function?
 - seemed that maybe this failing table alias also caused other firewall-rules to be ineffective, could not cause firewall-rules to become effective until the offending alias was deleted, difficult to confirm sorry.
 - Also, a feature request for an update frequency measured in something less than days

**Comment by fichtner** [comment]
Hi @ndejong,

Well, first things first: just how big is the file and what is your system spec in terms of RAM, hard disk space and installed OPNsense (e.g. Nano install?).

    the URL table alias in question is successfully loaded by pfSense.

That's a relative term: no version numbers to match, no extended settings mentioned. :)

    would it be possible to have a configurable item somewhere that allows for more memory to be allowed/provided to the underlaying function?    

Certainly, but without looking at the manual and testing / confirming it's difficult to say. https://www.freebsd.org/cgi/man.cgi?query=pf.conf&sektion=5

    seemed that maybe this failing table alias also caused other firewall-rules to be ineffective, could not cause firewall-rules to become effective until the offending alias was deleted, difficult to confirm sorry.

Could be. Memory depletion normally causes undefined state and should be avoided.

    Also, a feature request for an update frequency measured in something less than days

You can update aliases more frequently using System: Settings: Cron, selecting a time frame you like using the command "Update and reload firewall aliases".

**Comment by ndejong** [comment]
Thanks for the prompt response and pardon my late reply - Looks like I need to dig further, but certainly "something" not right - the pfSense instances have considerably less cpu/memory/hdd resources and happily load this URL Table of 139079 entries while the OPNSense instances seem to blow up  :(

In reviewing the pf docs (https://www.freebsd.org/cgi/man.cgi?query=pf.conf&sektion=5) if feels like the resolution is going to be around this:-

```
set limit table-entries 100000
```

Will respond when I have more to share

**Comment by AdSchellevis** [comment]
@ndejong you can already set that parameter https://github.com/opnsense/core/blob/212f51a6e85f11c34a6c30ea899d108226b157aa/src/etc/inc/filter.inc#L447

just go to system_advanced_firewall.php

**Comment by Woi** [comment]
Just a FYI: I saw a similar error a few times on my ALIX2D13:
```There were error(s) loading the rules: /tmp/rules.debug:20: cannot define table bogonsv6: Cannot allocate memory - The line in question reads [20]: table <bogonsv6> persist file "/usr/local/etc/bogonsv6"```

table-entries is blank, means I have a value of 200000:
> Firewall Maximum Table Entries:
> Maximum number of table entries for systems such as aliases, sshlockout, snort, etc, combined.
> Note: Leave this blank for the default. On your system the default size is: 200000

**Comment by Woi** [comment]
https://redmine.pfsense.org/issues/4876#note-7
> "it uses memory from the uma allocator, the uma tries to be smart and start to deny some bigger allocations under low memory conditions but before it actually exhaust the memory"
> 
> It's easily replicable with a big enough config and 256 or 384 MB RAM. But with 512 MB or more, it's not an issue.
> 
> In short, you can fail to allocate memory in this situation even if there is some memory or swap available, so huge tables aren't doable with small amounts of RAM.

**Comment by fichtner** [comment]
Adding a swap file option for SSDs, which could help here, but will still be slow. Original isssue is solved by configuration.
