### ISSUE TITLE
Captive Portal Widget in the Dashboard and Statistic

### ISSUE THREAD

**Issue by gertfriend** [opnsense/core#1556]
Would it be possible also to integrate a statistic for the connected users, for example to see how much clients were connected yesterday at 09.00?

For now i solved it with the following script, witch will write date and time and the number off logged in users in the cplogins.txt and this script is scheduled every 5 minutes:

z=$(date +"%d.%m.%Y %H:%M")
l=$(configctl captiveportal list_clients 0 | grep -w "anonymous" | wc -l)
echo $z $l >> /root/cplogins.txt

And finaly import the txt in Excel.

**Comment by gertfriend** [comment]
Any news about this?
Also discussed in Forum 16.7.

**Comment by AdSchellevis** [comment]
timeout due to inactivity
