### ISSUE TITLE
CARP Primary to Master bevore services started 

### ISSUE THREAD

**Issue by lihaso** [opnsense/core#1557]
I have the problem after the restart of the Primary Firewall who's failed, they catch the CARP to this before all services are up and running. For example Relayd, openvpn and co. Is there a way to prohibit the catch until all services are up and running ?

**Comment by AdSchellevis** [comment]
Hi René,

Not really, the services should already be running on the backup machine, but the other end may not notice that directly and in some cases may be forced to reconnect.

You can register events using devd (/usr/local/etc/devd/), like the ones already in OPNsense to reconnect openvpn clients, but they will most likely be triggered after the switch.

When your using hasync (xmlrpc), make sure you restart the backups services after changes, so your sure both running configs are equal.

Best regards,

Ad

**Comment by lihaso** [comment]
Hi Ad

The case is a automatic fail over. And i restart the Firewall who is offline, when it starts, he catch the Carp (>10 VLAN's and 20 External IP Addresses Total 30 VHID's) to early, before the relayd and openvpn has successfully started. On failover event openvpn and relayd tunnels still works and when the primary starts up all https & VPN connections are lost, the other way on fail over event from Primary to Slave everything works fine. 

Greeting

René

**Comment by AdSchellevis** [comment]
Hi René,

I'll have to look into this as soon as I can find some additional time, I expect the network comes up first, propagating its status and may enter master state before all services are actually awake (depending on the time it takes for startup).
Maybe we could keep carp disabled until te last stages of the boot process, but I'll have to inspect some code there.

Best regards,

Ad

**Comment by AdSchellevis** [comment]
I don't have a quick fix for this available at the moment, due to impact on existing installs.

Ideally it should work like the following in may opinion:

-> bootup with net.inet.carp.allow=0
-> configure network
-> configure services
-> set net.inet.carp.allow=1 when not configured in sysctl parameters.

Although I'm unsure you can setup all when allow=0, triggered by this bit in the code https://github.com/opnsense/core/blob/4ca71c3234f054cea4109590715baa982a6bbda2/src/etc/inc/interfaces.inc#L1826

It would be good to see of there are more ideas available for the best solution here, since I couldn't find solid reference implementations not suffering from a similar issue.

**Comment by lihaso** [comment]
I think as i read in the carp(4) net.inet.carp.preempt set to 0 should prohibit it from auto switch over.
And in GUI should be a possibility to manually switch over.
I try to test this case with a HA Setup.

**Comment by AdSchellevis** [comment]
ok, thanks, if this works as expected we could remove https://github.com/opnsense/core/blob/4ca71c3234f054cea4109590715baa982a6bbda2/src/etc/inc/interfaces.inc#L1679 then add net.inet.carp.preempt=0 to the top of the boot procedure and revert back to normal when the bootup is complete.

An other option could be to let the user decide what he wants and stop assuming net.inet.carp.preempt should be 1 when carp is used (and move the setting to the bottom of the boot sequence).

**Comment by lihaso** [comment]
If it is disabled the active slave is still active as long preempt is set to 0 on master. If it is set to 1 the master takes asap everything, and that is bad in my opinion. It should be not enabled during boot process. I think it is best to let the user decide when it should be enabled after boot process, default should be disabled as in https://www.freebsd.org/cgi/man.cgi?query=carp&sektion=4 described.

**Comment by AdSchellevis** [comment]
I think we can change this without a lot of risks by moving it to a later state of the boot proces, make it configureable and leave our default on 1.
As soon as I have a patch for this I'll let you know.

**Comment by fichtner** [comment]
The boot process is difficult. CARP should indeed not be joined before it has finished booting, which is around here https://github.com/opnsense/core/blob/master/src/etc/rc#L263

Looking at this rc.opnsense invoke should probably be pushed to rc.syshook and the carp hook should be executed from there as well with a low priority (90-carp.start) to ensure even user plugins and scripts are up and running.

**Comment by AdSchellevis** [comment]
@fichtner I think you're right, let me change this in a single commit so you can test it on your end.

**Comment by AdSchellevis** [comment]
this https://github.com/opnsense/core/commit/7596738104cd30e8c4e3df83e0db860d1c7b3176 should do the trick, add an option to disable resetting preempt completely and a move to syshook.
