### ISSUE TITLE
OpenVPN Server confuration: reneg-sec option suffixed with semicolon

### ISSUE THREAD

**Issue by theq86** [opnsense/core#1558]
Version: 17.1.5 and before

When saving the OpenVPN server config file and using a non default value for the _reneg-sec_ option, there is a semicolon appended.

Example:
reneg-sec 0;
reneg-sec 11;

There are no other options suffixed with a semicolon and as I know it is not neccessary.

However, since everything works as expected this seems to be just cosmetic.

**Comment by theq86** [comment]
#1559

**Comment by fichtner** [comment]
via /2a2222a7a4b
