### ISSUE TITLE
getty error log entries

### ISSUE THREAD

**Issue by jstrebel** [opnsense/core#156]
I get at the end of the restart about 10 of the following entries:
getty[92605]: open /dev/ttyv0: No such file or directory 

OPNsense 15.1.9.2_1-amd64	
FreeBSD 10.1-RELEASE-p9	
LibreSSL 2.1.6

**Comment by fichtner** [comment]
Is this a box that doesn't have VGA?

**Comment by jstrebel** [comment]
yes I run the Serial Interface version.

**Comment by fichtner** [comment]
That's part of the dual serial/vga. The error stems from the fact that vga is being opened as well but there are no devices. Not sure if we can suppress that but I will take a look.

**Comment by fichtner** [comment]
Moving this to https://github.com/opnsense/tools/issues/6 -- thanks!
