### ISSUE TITLE
reporter: collect info about installed plugins

### ISSUE THREAD

**Issue by fichtner** [opnsense/core#1563]
sometimes plugin versions are ahead of the actual core release. this helps to diagnose problems.

**Comment by fabianfrz** [comment]
```bash
pkg info | grep os- | cut -d " " -f1
```
will give this list - may become a configd call.

**Comment by fichtner** [comment]
# pkg info -g 'os-*'

;)

We don't need a configd call here, it's just for diagnostics when the crash report is generated

**Comment by fabianfrz** [comment]
I am just not sure if the command runs as a user too.

**Comment by fichtner** [comment]
I don't want to create a call for a command. instead this would need to create a command for a crash report generation instead, with all possible info collection. No time to do this and the system already works.

**Comment by fabianfrz** [comment]
running it from the quagga user says it is ok. So privilege separation will not break it ;)
