### ISSUE TITLE
[wifi] add support for Intel cards iwn(4)

### ISSUE THREAD

**Issue by fraenki** [opnsense/core#1564]
Please add the [iwn(4)](https://www.freebsd.org/cgi/man.cgi?iwn(4)#DESCRIPTION) module to the kernel to provide support for Intel Wifi cards. (Reported via #opnsense on Freenode.)

**Comment by fichtner** [comment]
This works according to the man page:

```
 if_iwn_load="YES"
iwn1000fw_load="YES"
iwn100fw_load="YES"
iwn105fw_load="YES"
iwn135fw_load="YES"
iwn2000fw_load="YES"
iwn2030fw_load="YES"
iwn4965fw_load="YES"
iwn5000fw_load="YES"
iwn5150fw_load="YES"
iwn6000fw_load="YES"
iwn6000g2afw_load="YES"
iwn6000g2bfw_load="YES"
iwn6050fw_load="YES"
```

I don't want to deviate from the FreeBSD GENERIC if we can avoid it. How about adding those loader.conf vars to a plugin?

**Comment by fichtner** [comment]
support ticket, seems fixed :)
