### ISSUE TITLE
[Feature] Add feature to build rules based on users, groups on Proxy/Squid

### ISSUE THREAD

**Issue by leandroscardua** [opnsense/core#1566]
Hello,

Is possible create a feature or plugin that allow you to build rules based on users and/or groups on Proxy/Squid, with local base and/or remote base (LDAP, AD, etc..)

**Comment by AdSchellevis** [comment]
timeout due to inactivity

**Comment by kekek2** [comment]
I wrote such a plugin. But it depends on proxy-sso. When it is in stable version, I'll do pull-request.

**Comment by leandroscardua** [comment]
Ok, Thank  you.

**Comment by fichtner** [comment]
we are targeting 17.7.6 for the web-proxy-sso release :)

**Comment by kekek2** [comment]
Well
