### ISSUE TITLE
Settings a NTP server for a static dhcp lease does not stick

### ISSUE THREAD

**Issue by sjorge** [opnsense/core#1568]
Using the latest in the 17.1 series,

When adding a mapping using 'DHCP Static Mappings for this interface.' and setting a NTP server for that host.

The entry does not seem to be set, you can check this by editing the mapping and looking at the ntp servers.

(Doing a 3rd attempt to migrate all my stuff to OPNsense, so expect more bug reports if I find anything fishy)

**Comment by AdSchellevis** [comment]
No problem, this one was easy to fix, although not limited to ntp (wins and dns had the same issue)

**Comment by sjorge** [comment]
Also applied the commit as a patch, looking good.

**Comment by fichtner** [comment]
also backported to 17.1.6
