### ISSUE TITLE
Minor incosistancies in how mutli value fields work

### ISSUE THREAD

**Issue by sjorge** [opnsense/core#1569]
Using 17.7.5

For example for search domains (DHCP, DHCPv6, ...) the seperator is a simi-colon.
For Alternate Hostnames for the WebGUI is it space seperated.

Ideally those should be aligned, if something on the backend/config wants it in a particular way. This can always be formatted properly after.

(Super cool fix would be like how some of the fancy fields work in confluence wiki, where you type the entry hit return and it becomes a small label with an X to remove it)

**Comment by fichtner** [comment]
The MVC fields do what you propose, the static PHP pages follow CSV or Multi-Select Drop Down Style. The MVC fields even support Drag+Drop of CSV data. Long story short, everything should be migrated. Close this in favour of topic-based MVC migration? It could take a while though.
