### ISSUE TITLE
system log spacing between entries is too wide

### ISSUE THREAD

**Issue by fichtner** [opnsense/core#157]

**Comment by reetp** [comment]
Was having a look at this (I must be bored !) and whilst looking at the CSS I noticed an error

GET http://192.168.10.251/javascript/bootstrap-select.js.map 404 (Not Found)

That is being called by 

javascript/bootstrap-select.min.js:8://# sourceMappingURL=bootstrap-select.js.map

The file exists in 
./themes/opnsense/build/js/bootstrap-select.js.map
./themes/sample/build/js/bootstrap-select.js.map

Not sure if it is relevant but thought I would point it out.

**Comment by reetp** [comment]
OK, the CSS that affects this is "class=listlr nowrap" or "class=listlr" which is used in the function dump_clog in guiconfig.inc

If you change the CSS then it will affect various diag_logs files

root@OPNsense:/usr/local/www # grep -rn dump_clog *

I noticed there was no css entry for the listlr class mentioned so added this to main.css to test

.listlr {
padding: 5px 0px 5px 20px !important;
}

You need !important to override the default td style I think - doesn't work without.

This then tightens up the rows for all the diagnostic logs. Probably could do with refinement, but it is somewhere close. HTH.
