### ISSUE TITLE
17.1.5 sudo not working in 'ask password' mode

### ISSUE THREAD

**Issue by sjorge** [opnsense/core#1570]
I'm using 17.1.5, when setting sudo to 'ask password' under System -> Settings -> Administrator sudo does not work.

Dissallow -> does not work (to be expected)
No password -> works fine
Ask password -> asks for password but the password of the user logged in via ssh is not working.

I tried with both ```Disable integrated authentication``` on and off. I also tried with ```Permit password login``` on and off, as expected this only toggled the sshd setting.

The user I am using is member of the admin group.

**Comment by fichtner** [comment]
You have to be more specific about your setup. Generally, if "no password" works, "ask password" rejecting the password means its wrong :)

**Comment by sjorge** [comment]
Ha you just beet me too it.

I managed to fat finger the password (its a very long one) on both account creation, webgui login (4x) and account testing (2x).

But had the correct one for sudo 9x in a row. I figured it out by temporarily setting it to a simple password for further testing.

Good news I guess, I am not a donkey ;)

**Comment by fichtner** [comment]
We spent a lot of time getting this just right with PAM integration, you can even use 2FA from SSH or login or sudo. Whatever works with GUI login now works reliably everywhere else :)

**Comment by sjorge** [comment]
Yeah I noticed the 2FA, I will probably play with that once I got all things sorted :)
Got pretty far this time, aside from losing a day on HA clustering due to SmartOS issues I had to abandon that.

Now poking at DDNS with double-nat (I hate my ISP)

**Comment by fichtner** [comment]
Cool, glad to hear that. And thanks for all the pointers through issues, really appreciated. Makes a better OPNsense!
