### ISSUE TITLE
custom dyndns option that does not use curl but dns

### ISSUE THREAD

**Issue by sjorge** [opnsense/core#1571]
I'm playing with a custom dyndns stuff now because of double-nat (boo ISP boo!)

I usually use this trick over curl'ing one of the many URLs.

```bash
dig +short myip.opendns.com @resolver1.opendns.com
```

This would make a nice alternative for the curl methode of detecting an ip change.

**Comment by fichtner** [comment]
This is indeed nice, dyndns.org can be flaky sometimes.

**Comment by fichtner** [comment]
There doesn't seem to be a way for IPv6?

# dig -6 +short myip.opendns.com @resolver1.opendns.com

**Comment by sjorge** [comment]
Hmmm I never noticed as I always passed -4 in my scripts.
But it does indeed looks like myip.opendns.com only returns IPv4 :(

**Comment by fichtner** [comment]
it's not strictly necessary, but I'd rather have this in case that NAT becomes ever prevalent and we have to go back and fix it.

**Comment by alesnav** [comment]
This would be a nice feature! I am in the same situation, my ISP doesn't allow to use the router as a bridge :(

**Comment by fichtner** [comment]
Note to self: nice stuff, simplify IPv6 again and make sure we don't trust opendns...

**Comment by fichtner** [comment]
I don't think we need this. We've been through a few hoops in this regard and it works ok as is.

**Comment by alesnav** [comment]
Hmmm and how can we set a dyndns linked to one external IP address not directly associated with an interface? Sorry, maybe I just don't know how to get it done.

**Comment by fichtner** [comment]
I'm not sure about the question or how the proposed solution in this ticket helps with that?
