### ISSUE TITLE
dyndns: cloudflare not working with some tlds

### ISSUE THREAD

**Issue by nwpr** [opnsense/core#1572]
CloudFlare dyndns is broken with subdomains or international TLDs with many parts (like .co.uk). The bug exists since commit 55586d3c8ba890d65cc1a2d62839650cfa6aa275. As the current code was taken from pfsense, they already have a fix for that which can be referred to. (https://redmine.pfsense.org/projects/pfsense/repository/revisions/2446fffa5932e8debcaf165bfaf5492cea429c60)

**Comment by fichtner** [comment]
Ideally, we'd need test credentials and a test case to fix this. No contributor uses cloudflare, so we cannot fix easily.

**Comment by Nornode** [comment]
Hey, this still seems valid... 
I'm happy to help to troubleshoot this issue.
