### ISSUE TITLE
[17.1.5] outbound nat and rule generation

### ISSUE THREAD

**Issue by sjorge** [opnsense/core#1577]
If you switch to manual outbound nat, then switch to something else and back to outbound nat.
The default rules get added again. It's probably better to only add them if there are no existing rules, if there are maybe show a prompt.

It's a lot of work cleaning those up if you have a few WAN's

**Comment by sjorge** [comment]
Probably also a good idea to only generate outbound nat rules IF the interface has IPv4 address configured.

IF_WAN6 (HE tunnel) also gets outbound NAT rules generated but there is no IPv4 address on that interface, nor is there an IPv4 gateway for it.

**Comment by fichtner** [comment]
@AdSchellevis is working on this at the moment it seems

**Comment by fichtner** [comment]
Outbound page was cleaned recently.
