### ISSUE TITLE
[17.1.5] firewall alias of type host accepts IPv6 subnet

### ISSUE THREAD

**Issue by sjorge** [opnsense/core#1579]
![screenshot](http://i.imgur.com/sqdHbVb.png)

If you add a IPv4 subnet e.g. 172.16.10.0/24 it will complain.
I would expect the same to happen for IPv6.

**Comment by AdSchellevis** [comment]
it looks like the behaviour of is_ipaddrv6() is different then is_ipaddrv4(), easy to fix, although I do think we should leave this on devel for some time (other validations might accidentally rely on this).

**Comment by sjorge** [comment]
Agreed, this breaking a lot at the moment.

Aside from the expectation that a hosts alias has host not networks :)

**Comment by fichtner** [comment]
Maybe this will surface some spots elsewhere that incorrectly use is_ipaddrv6, so the fix here is right but the callers may be wrong. we'll see, will keep this on -devel for 1-2 versions
