### ISSUE TITLE
wiki: new naming scheme for installation media

### ISSUE THREAD

**Issue by fraenki** [opnsense/core#158]
I'm aware that this is not the best place to report this, but I couldn't find a better one.

The [Installation documentation](https://wiki.opnsense.org/index.php/Manual:Installation_and_Initial_Configuration) still mentions the old naming scheme for installation media (memstick, LiveCD, serial), but [starting with 15.1.6](https://opnsense.org/opnsense-version-15-1-6-1-released/) a new scheme was introduced (vga, cdrom, serial).

I would've changed it, but I don't have write access to the Wiki. :-)

As a sidenote, I think the name 'vga' for the USB installer image is slightly misleading. On the other hand, it's hard to please everybody. ;-)

**Comment by AdSchellevis** [comment]
No problem and thanks for mentioning it, I personally really like the issue tracker of GitHub :-)  
I have replaced the media types with the new ones.
If you want an update account on the wiki, just create an account and let me know your account name.

**Comment by fraenki** [comment]
@AdSchellevis Thanks, and nice that you've changed the version and platform too :+1: 
My wiki account name is Fraenki ;)

**Comment by fichtner** [comment]
@fraenki what would be a better name for "vga"? I've tried to keep the names as small as possible, avoiding stuffing of "memstick-usb-serial-with-vga-on-the-side", "memstick-vga-but-no-serial", etc. I'm overstating for emphasis, but I'm not against tweaking the names further given there are better ideas. Discuss! :)

**Comment by AdSchellevis** [comment]
@fraenki Your welcome! I've changed your wiki account, you should be able to edit now.

**Comment by fraenki** [comment]
@fichtner Hm, I'd rather vote for a more expressive naming scheme, but I can't think of anything without going back to long filenames. I think I can get used to the new scheme, too. Don't worry.
@AdSchellevis Edit works, thanks!

**Comment by fichtner** [comment]
@fraenki expressive vs. explicit -- I do think the names are expressive, but not explicit and you probably mean explicit? I like one word names, even though they don't reflect the full scope, they are easier to remember and communicate. If we can find better words for the images we should! :)
