### ISSUE TITLE
[17.1.5] Label incorrect when importing a CA

### ISSUE THREAD

**Issue by sjorge** [opnsense/core#1581]
```Serial for next certificate```

This value actually gets incremented by 1 it seems.
So if you enter 42... the next certificate is not 42 but 43.

**Comment by fichtner** [comment]
We run the risk of issuing the same serial twice if we fix the code, should be limit the serial to > 0 and then do -1 before store?

**Comment by sjorge** [comment]
Or change the label to 'Serial of last certificate' ?

**Comment by fichtner** [comment]
changing labels means updating manuals and translations :)
