### ISSUE TITLE
[17.1.5] system_certmanager.php's issuer field is linked on name, not serial!

### ISSUE THREAD

**Issue by sjorge** [opnsense/core#1582]
The issuer field is wrong on system_certmanager.php if you have renamed a CA.

To reproduce.
1. Create a new CA, description/cn = CA-Active
2. Create a certificate using CA-Active
3. Rename CA-Active to CA-Spare
4. Create a new CA, description/cn = CA-Active

You now have 2 CA's: CA-Active, CA-Spare
You now have 1 cert: signed with CA-Spare, but it shows CA-Active because it seems to be linked on description field?

Probably best to look up the issuer signature, then check each CA for a match.

**Comment by sjorge** [comment]
You want to match on this field ```X509v3 Authority Key Identifier```

**Comment by AdSchellevis** [comment]
timeout due to inactivity
