### ISSUE TITLE
[17.1.5] Port Forwarding does not take hostname as redirection ip

### ISSUE THREAD

**Issue by sjorge** [opnsense/core#1583]
On OpenBSD I could just have it redirect to a hostname, this saves in creating aliases for ever host.
Creating a host alias that just links one FQDN is rather annoying.

Same holds true for normal rules too.

Not sure if this was intentionally designed like this, but it seems likely. So feel free to just close if that is the case. (I assume this is done to avoid DNS needing to be up when loading the firewall rules. Tables can be populated afterwards... if that is the reason, perhaps for every hostname a hidden table could be autogenerated in the rules files so to the user it just works TM)

**Comment by fichtner** [comment]
Not using an alias has the trouble of pf only resolving the host entry once on rule loaf. I'm not opposed to adding support, but the limitations must be clear to the user and it may break reloading when dns is misconfigured.

**Comment by sjorge** [comment]
Wouldn't that be solved by 'automagically' turning that into a implicit table?

The first time hostX is used it because auto_table_hostX (or whatever), if hostX is encountered again later it reuses the table. If at some point auto_table_hostX has no references we remove it?

Although that would probably be a lot more work. It is probably the most proper solution.

**Comment by AdSchellevis** [comment]
please don't accept hostnames in rules, when anything fails, the filter breaks. We already have some of this issues in the alias support, which are fixable. if we add support here, it very likely will get beyond repair.
(current static alias entries should eventually be dynamically loaded to prevent the current issue)

**Comment by fichtner** [comment]
Ok, reason enough to close :)

How about instead we could have a "quick alias" feature? One that would turn a hostname into an alias?

**Comment by sjorge** [comment]
@fichtner that one has my preference actually, it should avoid the issues @AdSchellevis was talking about. As I also raised those concerns in the original comment.

**Comment by AdSchellevis** [comment]
timeout due to inactivity
