### ISSUE TITLE
No way to see more rule detail without editing?

### ISSUE THREAD

**Issue by sjorge** [opnsense/core#1584]
So far I have not found a way to see detailed rule information without going to the edit page.

A little (i) icon like we see in other places that open a popup (on click or hover or whatever) would be very welcome. This gets especially annoying if you use a few float are nearly identical except you target different interfaces for example.

**Comment by sjorge** [comment]
Speaking of other improvements, a little extra help icon that shows you the processing order as a quick reminder could be handy too. I usually have to dig up my notes.

**Comment by fichtner** [comment]
Ideally, the rules edit should be a modal edit view, which doesn't lose context with the list page. The captive portal and traffic shaper are doing this, but I'm not sure when the firewall pages are going to be converted.

**Comment by sjorge** [comment]
Just checked, something like that would work fine too :)

**Comment by fabianfrz** [comment]
A temporary workaround would be loading the rules in an `iframe` but I would not recommend it.

The problem here is that the firewall part has lot of dependencies like aliases or interfaces which are needed to be converted first.

**Comment by fabianfrz** [comment]
First part was easy: #1607 but I won't work in the frontend

**Comment by AdSchellevis** [comment]
timeout due to inactivity
