### ISSUE TITLE
[17.1.5] creating a port forward with "No RDR" always creates a linked rule

### ISSUE THREAD

**Issue by sjorge** [opnsense/core#1585]
Basically the subject, you need to create it without 'No RDR' first and set linked rule to none, then edit it and check 'No RDR' to one without a linked rule.

**Comment by fichtner** [comment]
I'm not sure if no-rdr is supposed to do this linking at all. The JS hides the field which could indicate that but then it does the opposite?

**Comment by sjorge** [comment]
I just did some more testing.

Default the field is set to add a associated rule, clicking no-rdr hides the fields.
But it still adds it on save.

However if you set the field to 'none', **before** clicking no-rdr, on save it does not add it.

So it me it looks like the fields gets hidden but not ignored on save.

**Comment by fichtner** [comment]
Added 6eda8ae as a base for discussion, maybe @AdSchellevis can weigh in on this.

**Comment by sjorge** [comment]
Like yo said, I'm not sure a associated rule makes sense for no-rdr.
But now I can at least disable it manually, my current 17.1.5 is starting to looked like a patched quilt

**Comment by AdSchellevis** [comment]
probably better to disable the field using the same class, it's not very logical to show a filter option when no-rdr is selected. @fichtner You can assign the issue to me if that's the way to go.

**Comment by fichtner** [comment]
It makes at least some sense to keep this, in this case it's configurable at least. No-rdr might mean we want to pass traffic so associated pass isn't the worst thing... But I'm handing this over :)

**Comment by fichtner** [comment]
going into a no-rdr rule and unchecking no-rdr yields a disabled input box? it needs a save + edit to become selectable

**Comment by AdSchellevis** [comment]
not sure what you mean, on my end it hides and disables (saving no value when selected).

**Comment by fichtner** [comment]
I saved no-rdr, it redirects to the listing, then edit again, disable no-rdr. the filter field is shown, but disabled (cannot change the value).

**Comment by AdSchellevis** [comment]
ah, it failed on initial open, missing refresh on the selectpicker type.

**Comment by fichtner** [comment]
works, thanks! I'm adding this to stable/17.1 now :)

**Comment by sjorge** [comment]
I'm going to need a lot of time figuring out what patches still to apply on the next 17.1.x release :+1: 
Which is kind of awesome because a lot of stuff I found already got fixed and some will be in 17.7!
