### ISSUE TITLE
[FEATURE] I want to be able to do outbound nat based on a tag

### ISSUE THREAD

**Issue by sjorge** [opnsense/core#1586]
As a network admin I want to be able to NAT traffic based on a tag set.

For example I could tag certain traffic flowing into the LAN and OPTx interfaces.
I could then NAT with different settings based on those tags.

I don't think ordering is preventing this from being added, as the traffic gets tagged on it's way in and NAT'ed on the way out.

**Comment by fichtner** [comment]
I added this for Port Forwards recently, not a problem to add this here too.

**Comment by sjorge** [comment]
Done testing this fix on top of 17.1.5, works fine now! 👍

**Comment by fichtner** [comment]
Nice, thanks!
