### ISSUE TITLE
[FEATURE] Disable or enable rules/nat/pf/... using checkboxes

### ISSUE THREAD

**Issue by sjorge** [opnsense/core#1587]
The NAT, Port Forward, Rules pages ... have checkboxes. These can be used to move and delete rules. 

It would be great to have a enable and disable icon too.

**Comment by fichtner** [comment]
This works by clicking the action icon... Which rules do not offer this?

**Comment by sjorge** [comment]
But that only toggles it for Rule I clicked the icon on. Not for all the ones I selected.
