### ISSUE TITLE
apinger log messages even all gateways are disabled

### ISSUE THREAD

**Issue by mschilt** [opnsense/core#159]
This log message is flooded all the time:
   opnsense: /getstats.php: The command '/bin/pkill -'USR1' -F '/var/run/apinger.pid'' returned exit code '1', the output was ''

I only have one gateway defined and disabled monitoring on that one. So there should not be any apinger monitoring a gateway. 

Looks like I hay have found the issue. Here is what is called.
  www/getstats.php -> www/includes/functions.inc.php:get_stats() -> get_gatewaystats()  ->   etc/inc/gwlb.inc:return_gateways_status()

  return_gateways_status():
  ..
  /* Always get the latest status from apinger */
          killbypid("{$g['varrun_path']}/apinger.pid", 'USR1');
  ..

So it always tries to send a SIGUSR1 to a process with the pid listed in the old pid file of apinger even when there is no such process running. The pid file is not cleaned up when disabling apinger. I believe this could be an issue when that pid is reused by a process that maybe does something different when receiving a SIGUSR1.

**Comment by fichtner** [comment]
Stale pid files are okay as long as the caller checks if the pid is valid. Will fix that, thanks!
