### ISSUE TITLE
[FEATURE] Firewall rule should allow for selecting mutilple ICMP types in one rule.

### ISSUE THREAD

**Issue by sjorge** [opnsense/core#1590]
This applies for both ICMP and IPv6-ICMP

**Comment by sachaz** [comment]
+1

**Comment by AdSchellevis** [comment]
timeout due to inactivity

**Comment by sachaz** [comment]
This feature should still be useful, why close it ?

**Comment by fichtner** [comment]
To be able to open it when somebody works on it. If we keep all tickets open all the time where no progress is made we will not have any overview of the progress that we actually make and possibly miss more urgent tickets in the process.

**Comment by sachaz** [comment]
thanks for your explanation.
