### ISSUE TITLE
[17.1.5] as a user I expect the category filter to stick even when changing tabs

### ISSUE THREAD

**Issue by sjorge** [opnsense/core#1592]
As a user I expect the category filter to stick even when changing tabs.

I open the Floating tab and limit my view to rules in the NTP category, I then click on the LAN interface tab. I now see all rules for the interface instead of only those of the NTP category as I would expect.

**Comment by sjorge** [comment]
Hey Add, can this be applied on top of 17.1.8?
I ran ```opnsense-patch d5ceec2``` but the selected categories are still not remembered when changing between the interface tabs.

**Comment by fichtner** [comment]
also need 	e660269

**Comment by sjorge** [comment]
Yep, that was it, I was missing  e660269. Working fine with both applied 👍
