### ISSUE TITLE
[17.1.5] Configuration restore lists sections that no longer exist

### ISSUE THREAD

**Issue by sjorge** [opnsense/core#1593]
E.g. Proxy Arp, Wake On Lan,...

I think some of these are now plugins.

There should probably be some sort of way for a plugin to say which sections it adds. And only list them if the plugin is installed.

**Comment by fichtner** [comment]
Sure, this spot needs a similar addition like the XMLRPC sync plugin code that advertises possible config sections for the backup/restore.

**Comment by AdSchellevis** [comment]
timeout due to inactivity
