### ISSUE TITLE
Gateway status shows loss value inconsistently

### ISSUE THREAD

**Issue by sjorge** [opnsense/core#1594]
![screenshot](http://i.imgur.com/l0fkiqI.png)

One has 0% another one 0.0%.

IPv4 vs IPv6?

**Comment by fichtner** [comment]
@sjorge not sure, looks like round() may do weird things but now precision should be pinned to one decimal for both RTT and Loss.

**Comment by sjorge** [comment]
Looks fine now!

**Comment by sjorge** [comment]
Actually this now shows the number fine but it somehow turns 0.0% loss into 100.0% loss for the IPv4 gateway.

**Comment by fichtner** [comment]
Sorry, will correct :D

**Comment by sjorge** [comment]
Sorry I did not notice, it was green and everything had the proper formatting :D I was looking at the actual numbers.

**Comment by fichtner** [comment]
brings it back to where it was... if there isn't something else wrong entirely

    # opnsense-patch dd0d8ed

**Comment by sjorge** [comment]
Looks good now :)

**Comment by fichtner** [comment]
I apologise for this blunt attempt to subvert your efforts to polish the GUI :)
