### ISSUE TITLE
[17.1.5] Can't create alias with name well known service

### ISSUE THREAD

**Issue by sjorge** [opnsense/core#1595]
```The name cannot be the internally reserved keyword "irc".```
But it is not in the list of known services (although I assume it is in /etc/services

**Comment by sjorge** [comment]
Same for nntps

**Comment by sjorge** [comment]
Same for sieve...

It looks like the drop down does not list all wellknown servers but doesn't allow aliases for them to be create... which is really annoying!

**Comment by sjorge** [comment]
Since we know the list from /etc/services...
It would be nice to option under Firewall -> Settings to toggle showing of all known services vs well known services.

Showing all of them is probably overwhelming for some users, but others might want to see them all.

**Comment by AdSchellevis** [comment]
timeout due to inactivity
