### ISSUE TITLE
[17.1.5] Firewall Logs (Normal View) does not resolve IPv6 addresses

### ISSUE THREAD

**Issue by sjorge** [opnsense/core#1596]
In the log viewer when clicking the (i) next to an IPv6 address nothing happens. 
e.g. [2a00:1450:400e:806::200e]:443

I can do a reverse lookup from the command line just fine:

```
$ nslookup 2a00:1450:400e:806::200e
Server:		2001:xxx:xxx:10::1
Address:	2001:470:7ee7:10::1#53

Non-authoritative answer:
e.0.0.2.0.0.0.0.0.0.0.0.0.0.0.0.6.0.8.0.e.0.0.4.0.5.4.1.0.0.a.2.ip6.arpa	name = ams15s29-in-x0e.1e100.net.

Authoritative answers can be found from:
```

**Comment by TrentHunger** [comment]
I've been able to confirm the same on 17.7

**Comment by fichtner** [comment]
@AdSchellevis does this work in your new life view?

**Comment by AdSchellevis** [comment]
@fichtner it should, /api/diagnostics/dns/reverse_lookup?address=2a00:1450:400e:806::200e 

outputs 

`["ams15s29-in-x0e.1e100.net"]`

which is the output of gethostbyaddr()

**Comment by fichtner** [comment]
Ok so closing this for #1917

**Comment by fichtner** [comment]
And thanks for this work, it will also be useful for insight dns resolving. 😊

**Comment by AdSchellevis** [comment]
I know, it's on my list
