### ISSUE TITLE
LDAP Confgiuration is not enought flexible

### ISSUE THREAD

**Issue by koma85** [opnsense/core#1599]
The interface wizard on the LDAP server creation asks for what kind of server ldap is going to connect answering this question should populate some variables but there is no way to change those values after hitting ok.
Like the membership attribute and so on.

In pfSense interface you can see what attributes I'm talking about.

**Comment by AdSchellevis** [comment]
Please define what your missing, where it's missing and to what result it should lead. We're all way too busy to investigate incomplete issues.

**Comment by fichtner** [comment]
What @AdSchellevis means is that if you make it clear by providing screenshots and/or exact labels from the GUI, give a reference to the used OPNsense version and ideally which page you are referring to (address bar, full page title) it's way easier to pinpoint and fix. :)


Cheers,
Franco

**Comment by koma85** [comment]
I mean that you are missing this part of configuration in the interface (section :    SystemUser ManagerAuthentication ServersEdit) :

![schermata 2017-05-03 alle 11 46 42](https://cloud.githubusercontent.com/assets/247170/25655740/4d069a94-2ff6-11e7-8c00-3cd40bc0927b.png)
The droplist in OPNSense's wizard let you choose against what kind of LDAP server you are authenticating to. This actually fills those values that in pfsense are openly customizable.

**Comment by AdSchellevis** [comment]
It's already configurable. only user naming is actually used. 
![image](https://cloud.githubusercontent.com/assets/9783985/25718989/5369e874-3108-11e7-912e-240e2cc94dde.png) 
you can use extended queries to customise even further (https://docs.opnsense.org/manual/how-tos/user-ldap.html?highlight=extended).

**Comment by koma85** [comment]
In my case I've mixed group naming  and group member attribute.
an extended query will not solve the problem because of the key searched.

**Comment by AdSchellevis** [comment]
timeout due to inactivity
