### ISSUE TITLE
[FEATURE] obfproxy support for OpenVPN

### ISSUE THREAD

**Issue by sjorge** [opnsense/core#1600]
This has peaked my interest for a time and more and more clients seem to have picked up support.
e.g. Viscosity is one of them.

https://community.openvpn.net/openvpn/wiki/TrafficObfuscation

**Comment by fabianfrz** [comment]
this is more a request for adding a plugin `obfproxy`. OpenVPN does support it already (by adding custom configuration directives).

**Comment by sjorge** [comment]
True, obfproxy could be added as plugin and used by OpenVPN.

With all the proxy plugins maybe we need a generic framework for adding specifically proxy plugins so both a obfproxy, ftp-proxy, sslh,... could all plug into a simpler unified UI.

**Comment by fichtner** [comment]
Note that while openvpn says this is better than the XOR patch which they reject because they have obfsproxy, multiple people have reported that obfsproxy does not cut it in cases like the big wall. We have XOR integrated since 2015 and ported it to openvpn 2.4 in FreeBSD already.

**Comment by sjorge** [comment]
Also interesting, shall close this issue and open one in the plugin repo for obfproxy plugin?

**Comment by fabianfrz** [comment]
@sjorge if you want it and somebody is interested into implementing it, I would suggest adding a ticket in core for socks proxy configuration and a ticket in plugins for this proxy software.

**Comment by sjorge** [comment]
Would the ovpn advance configure field (already exists) + just a obfproxy plugin be sufficient?

**Comment by fabianfrz** [comment]
It would do it but the GUI should allow to input a socks server via a standard form element like a textbox for this value so it can be validated.

A plugin can operate completely independent from the service so it is not relevant if it is OpenVPN or something else.
