### ISSUE TITLE
[17.1.5] Deleting for a port alias triggers rule update

### ISSUE THREAD

**Issue by sjorge** [opnsense/core#1601]
Deleting a port alias seems to trigger a rule update. I noticed this twice now.

**Comment by sjorge** [comment]
Just confirmed it.
I made some rule edits.

Then before I wanted to apply them I wanted to clean up the now unused alias.

````
--- /tmp/rules.debug.old	2017-05-02 21:37:52.432929000 +0200
+++ /tmp/rules.debug	2017-05-02 21:37:52.433091000 +0200
@@ -78,7 +78,6 @@
 table <smtp_relay> {} persist
 smtp_relay = "<smtp_relay>"
 sshbackup = "{ 22987 }"
-vnc_common = "{ 5900:5999 }"
 table <zeus_vlan30> { 2001:470:7ee7:30::2 172.16.30.2 }
 zeus_vlan30 = "<zeus_vlan30>"
 znc = "{ 7666 }"
@@ -304,14 +303,14 @@
 pass  in  quick  on $IF_MGMT inet6 proto tcp  from (vtnet4:network) to any port 587 flags S/SA keep state  label "USER_RULE: Allow submission"
 pass  in  quick  on $IF_MGMT inet proto tcp  from $eros_vlan40 to $localnets port 22 flags S/SA keep state  label "USER_RULE: Allow SSH from Emergency Mgmt"
 pass  in  quick  on $IF_MGMT inet6 proto tcp  from $eros_vlan40 to $localnets port 22 flags S/SA keep state  label "USER_RULE: Allow SSH from Emergency Mgmt"
-pass  in  quick  on $IF_MGMT inet proto tcp  from $eros_vlan40 to $localnets port $vnc_common flags S/SA keep state  label "USER_RULE: Allow VNC from Emergency Mgmt"
-pass  in  quick  on $IF_MGMT inet6 proto tcp  from $eros_vlan40 to $localnets port $vnc_common flags S/SA keep state  label "USER_RULE: Allow VNC from Emergency Mgmt"
+pass  in  quick  on $IF_MGMT inet proto tcp  from $eros_vlan40 to $localnets port 5900:5999 flags S/SA keep state  label "USER_RULE: Allow VNC from Emergency Mgmt"
+pass  in  quick  on $IF_MGMT inet6 proto tcp  from $eros_vlan40 to $localnets port 5900:5999 flags S/SA keep state  label "USER_RULE: Allow VNC from Emergency Mgmt"
 pass  in  quick  on $IF_MGMT inet proto tcp  from $eros_vlan40 to $localnets port 3389 flags S/SA keep state  label "USER_RULE: Allow RDP from Emergency Mgmt"
 pass  in  quick  on $IF_MGMT inet6 proto tcp  from $eros_vlan40 to $localnets port 3389 flags S/SA keep state  label "USER_RULE: Allow RDP from Emergency Mgmt"
 pass  in  quick  on $IF_MGMT inet proto tcp  from $eris_vlan40 to $localnets port 22 flags S/SA keep state  label "USER_RULE: Allow SSH from Emergency Mgmt"
 pass  in  quick  on $IF_MGMT inet6 proto tcp  from $eris_vlan40 to $localnets port 22 flags S/SA keep state  label "USER_RULE: Allow SSH from Emergency Mgmt"
-pass  in  quick  on $IF_MGMT inet proto tcp  from $eris_vlan40 to $localnets port $vnc_common flags S/SA keep state  label "USER_RULE: Allow VNC from Emergency Mgmt"
-pass  in  quick  on $IF_MGMT inet6 proto tcp  from $eris_vlan40 to $localnets port $vnc_common flags S/SA keep state  label "USER_RULE: Allow VNC from Emergency Mgmt"
+pass  in  quick  on $IF_MGMT inet proto tcp  from $eris_vlan40 to $localnets port 5900:5999 flags S/SA keep state  label "USER_RULE: Allow VNC from Emergency Mgmt"
+pass  in  quick  on $IF_MGMT inet6 proto tcp  from $eris_vlan40 to $localnets port 5900:5999 flags S/SA keep state  label "USER_RULE: Allow VNC from Emergency Mgmt"
 pass  in  quick  on $IF_MGMT inet proto tcp  from $eris_vlan40 to $localnets port 3389 flags S/SA keep state  label "USER_RULE: Allow RDP from Emergency Mgmt"
 pass  in  quick  on $IF_MGMT inet6 proto tcp  from $eris_vlan40 to $localnets port 3389 flags S/SA keep state  label "USER_RULE: Allow RDP from Emergency Mgmt"
 pass  in  quick  on $IF_CLNT inet proto { tcp udp }  from (vtnet1:network) to (vtnet1) port 53 keep state  label "USER_RULE: Allow DNS"
````

After confirming the delete a took a few seconds for it to refresh and presto my rule edits were also applied!

This is not wanted behavior. Say you ware building a new rule set. Delete and alias, and your set was not finished you could block traffic or worse, allow traffic that you did not intend to yet!

**Comment by AdSchellevis** [comment]
ok, that's odd, it should trigger an error as far as I know https://github.com/opnsense/core/blob/master/src/www/firewall_aliases.php#L168

**Comment by sjorge** [comment]
It's no longer in use.

1. create a alias called common_http { 80, 8080, 443, 8443 }
2. create a rule to allow common_http
3. apply

4. decide you don't want 8080 and 8443
5. update rule create in 2 to to port 80
6. create a rule to allow port 443
7. remove the common_http alias
<update of the rules is triggered once clicking yes>

The apply button is now visible on the aliases page... but the changes have already been applied. I would expect the new rules set not to be applied yet.

Say I was doing a few edits and shuffling rules around, there is a chance to apply an incomplete ruleset.

**Comment by AdSchellevis** [comment]
I don't understand, are you editing the content of the rule in another tab?

**Comment by sjorge** [comment]
1. No, you edit the rules and save then.
**no update triggered**, apply button becomes available.
1. Go to the aliases page.
2. Delete the now unused alias
**update triggered when clicking yes to delete**, apply button now also becomes available on the aliases page.

**Comment by sjorge** [comment]
Yes, sorry if it wasn't clear.

The apply rules on delete is unwanted, it should only happen when apply is clicked.

**Comment by sjorge** [comment]
Oh that was a simple fix! :) (sorry I check all of them so I can get to know my way around the code a tiny bit)

**Comment by AdSchellevis** [comment]
I agree here, although the fix won't be perfect. When an alias is deleted, it will be flushed immediately, otherwise the system doesn't know of its existence given the current setup https://github.com/opnsense/core/blob/master/src/www/firewall_aliases.php#L170
