### ISSUE TITLE
Alias Update frequency URL Table

### ISSUE THREAD

**Issue by gertfriend** [opnsense/core#1603]
Would it be possible to change the field "Update Freq. (days)" from days to minutes?

I ask this because i have some lists with IPs, with can be updated once a day but i have some URL Aliases with DynDNS names and this should be updateded every 5 Minutes.

I know that this can be done with Cron but it would be more comfortable by setting it properly for each entry

**Comment by AdSchellevis** [comment]
duplicate https://github.com/opnsense/core/issues/1703
