### ISSUE TITLE
[17.1.5] Can't enter a IPv6 host or network when adding rules.

### ISSUE THREAD

**Issue by sjorge** [opnsense/core#1608]
![screenshot](http://i.imgur.com/mRjoYhD.png)

As you can see in the screenshot the smallest subnet is 32 when the selecting IPv6 or IPv4+IPv6.

**Comment by AdSchellevis** [comment]
it should flip when a IPv6 address is provided....

**Comment by sjorge** [comment]
Aha! Never noticed as I usually start by selecting the correct mask first.
