### ISSUE TITLE
Routes status page ipv6 default route missing

### ISSUE THREAD

**Issue by QN-Darrell** [opnsense/core#1609]
There is a bug on the System > Routes > Status page, where if you have an IPv4 and IPv6 default route, only the IPv4 one shows. I believe this is due to both of the route destination's being "default". The ajax json object contains both routes, but the display on the page does not, i suspect due to the destination column being the "identifier".

```
root@opnsense:/ # netstat -rWn | grep default
default            76.x.x.1         UGS    488167936   1500       igb0
default            2001:470:x:x::1          UGS         156   1280     gif0
```

![system routing table](https://cloud.githubusercontent.com/assets/26904677/25713918/e5ed67ee-30d0-11e7-9521-528b8a3a0157.png)

**Comment by AdSchellevis** [comment]
@QN-Darrell can you try https://github.com/opnsense/core/commit/320cc256aa8361cebc8806f1bd1dd0e6bfe612a7?

easy to install, using:

`opnsense-patch 320cc25`

**Comment by fichtner** [comment]
(works for me 👍 )

**Comment by QN-Darrell** [comment]
Works great, thanks :smile:

**Comment by AdSchellevis** [comment]
@QN-Darrell your welcome, thanks for confirming.
