### ISSUE TITLE
Implement traffic shaper feature using ipfw/dummynet

### ISSUE THREAD

**Issue by AdSchellevis** [opnsense/core#161]
The old non functional traffic shaper feature using pf/dummynet hooks is removed in 15.1.10, a new version will be implemented before 15.7.

**Comment by dsbaars** [comment]
As mentioned in the discussion at #97 and not directly clear from this issue, this is needed to set up traffic shaping when using VLANs.

**Comment by AdSchellevis** [comment]
Sorry, my description was a little short :-) 

We have removed the limiter (from version 15.1.10), because it wasn't functional and will reimplement it back using a more standard solution somewhere before release 15.7. 

Using ipfw/dummynet we should be able to shape all sorts of traffic, including vlan's (expected). In pfSense there were a lot of custom patches which we want to avoid, because of stability and security reasons.

There's still a lot of work to do glueing all the bits and pieces together and we try to keep things as standard as possible.

As soon as we have something worth testing, I will put a comment in this thread.

**Comment by AdSchellevis** [comment]
Just a quick update before closing the issue, the initial release of the new traffic shaper will be in 15.1.11.2 (later today).

**Comment by fichtner** [comment]
Does this mean we can slowly start to phase out ALTQ?

**Comment by AdSchellevis** [comment]
maybe.... I still have some more research to do if there's any missing function which we should move over to our new system.

**Comment by fichtner** [comment]
DELETE DELETE DELETE :D

**Comment by fichtner** [comment]
or should I rather say.... EXTERMINATE

**Comment by AdSchellevis** [comment]
;-)

**Comment by fichtner** [comment]
Closing this.
