### ISSUE TITLE
DHCPv6 not working

### ISSUE THREAD

**Issue by fraenki** [opnsense/core#1610]
This came in via IRC:

> I just switched to OPNsense and I have a problem. I am trying to enable IPV6, but it does not work. I have enabled DHCPV6 from interfaces, but it seems that the dhcp6client does not run at all. ps | aux does not show the client process or there is no mention on the logs.

Contents of `/var/etc/dhcp6c_wan.conf`:

```
interface re0 {
  send ia-na 0;   # request stateful address
  send ia-pd 0;  # request prefix delegation
        request domain-name-servers;
        request domain-name;
        script "/var/etc/dhcp6c_wan_script.sh"; # we'd like some nameservers please
};
id-assoc na 0 { };
id-assoc pd 0 {
  prefix-interface re1 {
    sla-id 0;
    sla-len 8;
  };
};
```

System log when restarting the WAN interface:

```
May 4 18:17:50 	opnsense: /interfaces.php: ROUTING: setting IPv4 default route to xx.xxx.xxx.xx
May 4 18:17:49 	opnsense: /interfaces.php: Accept router advertisements on interface re0
May 4 18:17:47 	opnsense: /usr/local/etc/rc.newwanip: ROUTING: setting IPv4 default route to xx.xxx.xxx.xx
May 4 18:17:47 	opnsense: /usr/local/etc/rc.newwanip: rc.newwanip: on (IP address: xx.xxx.xxx.xx) (interface: WAN[wan]) (real interface: re0).
May 4 18:17:47 	opnsense: /usr/local/etc/rc.newwanip: rc.newwanip: Informational is starting re0.
May 4 18:17:46 	opnsense: /interfaces.php: Clearing states to old gateway xx.xxx.xxx.xx.
```

While searching the forums I had the feeling that this is a [common](https://forum.opnsense.org/index.php?topic=4774.msg18598) [issue](https://forum.opnsense.org/index.php?topic=4774.msg18598). So I thought I should report it here, although I'm not using DHCP6.

**Comment by fichtner** [comment]
dhcp6 only rungs when a router advertisement is received. if radvd is running, that can mean:

* The ISP doesn't like it ;)
* try the "Directly send SOLICIT" option
* Please please name the ISP, it may need other tweaks

**Comment by fichtner** [comment]
trying something new.... support case, answer given, lots of progress since :)
