### ISSUE TITLE
[17.1.6] cannot do static outbound nat for port range

### ISSUE THREAD

**Issue by sjorge** [opnsense/core#1615]
So I'm trying to allow static outbound nat for the Apple Facetime port range (UDP 16384 to 16472)
But looks like I have to have a rule per port.

It should be possible to do this in one rule.

**Comment by JohnD87** [comment]
I was possible some versions before. 
I am actually facing the same issue now. I have to set static outbount for around ~1000 ports and i do not want to set 1000 rules.
Any ideas?

**Comment by fichtner** [comment]
@AdSchellevis close or assign to a milestone?

**Comment by AdSchellevis** [comment]
let's close it, there's an easy work around with aliases.
