### ISSUE TITLE
[17.1.6] unbound-checkconf returns errors

### ISSUE THREAD

**Issue by sjorge** [opnsense/core#1616]
I ran unbound-checkconfig when messing around to get cname support.

But even with my changes not applied I get a warning.

```
root@exosphere:~ # unbound-checkconf
/var/unbound/unbound.conf:28: error: unknown keyword 'serve-expired'
/var/unbound/unbound.conf:28: error: stray ':'
/var/unbound/unbound.conf:28: error: unknown keyword 'no'
```

**Comment by fichtner** [comment]
don't do it ;)

https://forum.opnsense.org/index.php?topic=5039.msg20101#msg20101

**Comment by sjorge** [comment]
Is there an unbound-checkconf that gets shipped with the opnsense one?

**Comment by sjorge** [comment]
Found it!

**Comment by fichtner** [comment]
For reference:

    # /usr/local/sbin/unbound-checkconf

**Comment by fichtner** [comment]
maybe we can remove unbound from the base system, but I'm not sure

**Comment by sjorge** [comment]
+1 on removing the system one
