### ISSUE TITLE
unbound issues and feature requests

### ISSUE THREAD

**Issue by sjorge** [opnsense/core#1618]
I'm trying to consolidate some tickets to make there be less of them.

Missing feaures:
- [x] CNAME host override PR #1617
- [ ] Option to disable interface record generation PR #1620 
- [ ] DNSCrypt support (see @L1ghtn1ng's comment)

Bugs:
- [ ] domain name overrides for dhcp servers are ignored when registering

**CNAME host overrides**
It would be nice to be able to add CNAME to the host override section.
Maybe other types too eventually.

**Option to disable interface record generation**
When the firewall is in a multi-homed lan where every interface has it's own subdomain the automatic generation of hostname records is not wanted.

e.g.
LAN_CLIENTS -> vlan10.example.org
LAN_STORAGE -> vlan20.example.org
LAN_SERVERS -> vlan40.example.org

In this case you do not want fwname.example.org to have 3 A and AAAA records.
Something like this is probably more desirable:
fwname.vlan10.example.org
fwname.vlan20.example.org
fwname.vlan30.example.org
fwname.example.org CNAME fwname.vlan10.example.org

When using dnsmasq host override seems to work for this, not with unbound. The initial entries added seem to take precedence over ones added later.

It would be useful to have a advanced option to not generate them. Then the responsibility will fall unto the administrator. I'll try and look into adding this myself as it does not seem overly hard to do. This has been done in PR #1620 pending a merge.

**domain name overrides for dhcp servers are ignored when registering**
In a multi-lan setup each lan can have it's own subdomain. You can have dhcpd and dhcpv6 push out the correct domain to each client just fine by overriding the default that comes from general -> settings.

Static leases can even have a different one from that too!

However if you let unbound register the static entries from the lease file they all end up with the default domain. Static mappings do have the proper domain name attached.

Current plan of attack is to extend watcher.dhcp to also parse dhcpd.conf and match up the address to the subnet entry in the config. We can then populate a 'domain' key with the domain from the config, or if it is missing the default one.

Implementation details still fuzzy as I am not yet sure how to query the default domain correctly from python.

**Comment by sjorge** [comment]
Alright, think I know how to get the correct domain name if one is set.
Static mappings are already correct so that is a big help.

I just need to find a way to match the IP to the correct pool and presto I can check for the hostname.
I'll look into it after the other 2 PR get merged, to avoid issues were I'm editing the same file.

**Comment by sjorge** [comment]
Hey @AdSchellevis for the last item on the list I am trying to understand the DHCPLease watcher.

I'm not sure why we reset the seek position here?
https://github.com/opnsense/core/blob/master/src/opnsense/site-python/watchers/dhcpd.py#L91

My initial guess is we do this so if we lose the handle and repopen the leases file we continue where we left of. This could lead to problems.

For example if the leases had 10 lines and we were at line 9, and after the re-open there are only 8 lines.

.watch() is called in every loop in the unbound-dhcp script anyway so it's probably safer to start at the beginning again?

Or am I missing something?

**Comment by L1ghtn1ng** [comment]
@sjorge As you are working on unbound I would like to request this get added 
```#1217. DNSCrypt support, with --enable-dnscrypt, libsodium and then enabled in the config file from Manu Bretelle.```

**Comment by AdSchellevis** [comment]
Hi @sjorge,

On reopen self._last_pos is reset to None, telling the watcher that it's not the same file we're watching (https://github.com/opnsense/core/blob/master/src/opnsense/site-python/watchers/dhcpd.py#L48).

When the current file is unlinked, it will trigger a reopen https://github.com/opnsense/core/blob/master/src/opnsense/site-python/watchers/dhcpd.py#L87.

We need the tell() seek() construction just to keep reading at our last position within the same file, if you skip those it won't continue reading the data pushed by the other (dhcp) process.

Regards,

Ad

**Comment by sjorge** [comment]
@AdSchellevis ah yes! this makes sense. Thanks.

@L1ghtn1ng that looks a bit above my skill set.
DNSCrypt would probably also work better as a plugging. Then both unbound and dnsmasq could use it if desired.

**Comment by fichtner** [comment]
@sjorge shall we close this?

**Comment by sjorge** [comment]
Sure I guess, CNAME do not seems feasable.

Although #1620 is ready and would still be nice to have.

**Comment by fichtner** [comment]
sure, ok, will take care of it.
