### ISSUE TITLE
[17.1.6] unbound does not honer domain overrides configured for dhcp servers

### ISSUE THREAD

**Issue by sjorge** [opnsense/core#1619]
Unbound will always use the domain from general -> settings ignoring the domain set in the dhcp server's domain field.

**Comment by fichtner** [comment]
@sjorge we need to slow down on the tickets or collect them per topic, it's getting very hard to keep track :/

**Comment by sjorge** [comment]
Yeah, I just open one when I run into a problem.
Lets see if I can groep them somewhat.

**Comment by sjorge** [comment]
Closed in favor of #1618
