### ISSUE TITLE
Captive Portal: Radius Accounting improvements

### ISSUE THREAD

**Issue by AdSchellevis** [opnsense/core#162]
Current support is probably broken and code base is still quite messy. 
Needs rewrite using a cleaner and better understandable code.

**Comment by miken32** [comment]
FYI getVolume was perfectly functional (we're using it now in pfSense) but I do support a rewrite of captive portal entirely. It's quite the mess.

We are planning to expand our use of custom-built routers (currently most of our hospitality sites use HP or Nomadix, with 10-15 pfSense) and are looking at giving opnSense 15.7 a try. Captive portal/RADIUS is a big part of our networks, so I'll be keeping an eye on this for sure!

**Comment by AdSchellevis** [comment]
Thanks for the tip.

We had to rewrite a lot of the captive portal code to get rid of all the non standard kernel hooks, unfortunately we had to drop some functionality in the first release (like limiting traffic).  At the moment we're working on the traffic shaper component which also has a relation to the captive portal part due to the technology it's using (ipfw/dummynet). 
Eventually we want to bring captive portal back to a more functional state, by also rewriting this part using our new framework. 

I hope you like OPNsense, although you might miss some features in captive portal due to our cleanups.

**Comment by fichtner** [comment]
We've been discussing this recently and it seems that authentication is working fine in general:

https://forum.opnsense.org/index.php?topic=686.0

We focus on getting authentication into shape, then take a look at accounting which may or may not have some issues. One step at a time. :)

**Comment by fichtner** [comment]
Radius is being rewritten for the new captive portal, closing.
