### ISSUE TITLE
illegal TOS value

### ISSUE THREAD

**Issue by porjo** [opnsense/core#1623]
Attempting to create a normalization rule (Firewall -> Settings -> Normalization), the list of available priorities includes `0x0` however selecting and applying that value results in an error:

```
05-06-17 07:21:06 [ There were error(s) loading the rules: /tmp/rules.debug:33: illegal tos value 0x0 - The line in question reads [33]: scrub out on igb1 from any to any set-tos 0x0 ]
```

My intention is to reset the TOS field on all outbound traffic to zero

OPNSense 17.1.6
/firewall_scrub.php

**Comment by AdSchellevis** [comment]
@porjo 0x0 is not a valid value for the tos bit, it shouldn't have been in the interface (the error message is from our used package filter, pf).
I've removed the option and will close this issue.

**Comment by fichtner** [comment]
There is some pfctl stuff to import that we did for FreeBSD. Let's keep this open. 😊

**Comment by fichtner** [comment]
btw, the check in the kernel is wrong, zero is an accepted value... I've added this commit, it takes better values for TOS and does not clobber ECN parts of the byte: https://github.com/opnsense/src/commit/fa04428122

**Comment by porjo** [comment]
Thanks for the quick response. The fix will be in 17.1.7 or 17.7?

**Comment by fichtner** [comment]
17.1.7 or 17.1.8, not sure yet. It needs an OS update.

**Comment by fichtner** [comment]
@porjo if you run amd64 you could try the latest base/kernel with your 17.1.6 to see if zero works as expected:

    # opnsense-update -bkr 17.1.4-next
    # /usr/local/etc/rc.reboot


Cheers,
Franco

**Comment by porjo** [comment]
@fichtner thankyou, that resolved the problem for me

**Comment by fichtner** [comment]
@porjo thanks, so in 17.1.7 we will have this fix and be able to also select predefined DCSP values from the GUI :)
