### ISSUE TITLE
IPSec auth stopped working

### ISSUE THREAD

**Issue by thomasnilsen** [opnsense/core#1625]
I cannot connect with VPN anymore after I got it working for some time now..

I use IPSec IKEv1 and Xauth.. + mobile client.

Found this in logfile;

May  7 14:30:39 OPNsense charon: 09[IKE] XAUTH-SCRIPT failed to execute script '/usr/local/etc/inc/ipsec.auth-user.php'.
May  7 14:30:39 OPNsense charon: 09[IKE] XAuth-SCRIPT failed for user 'test' with return status: -1.
May  7 14:30:39 OPNsense charon: 09[IKE] Could not authenticate with XAuth secrets for 'xx.xx.xx.xx' - 'test'
May  7 14:30:39 OPNsense charon: 09[IKE] XAuth authentication of 'test' failed

I can also confirm the file is not there..

I'm running OPNsense 17.1.6-amd64

best regards
Thomas

**Comment by fichtner** [comment]
Hi Thomas,

A reboot should fix that. The file was moved but IPSec not restarted.

Cheers, Franco

**Comment by thomasnilsen** [comment]
Well thanks alot! Should have given that a try first. I enabled and disable ipsec, but I guess that did not restart it!

Thanks! It works now 👍

**Comment by fichtner** [comment]
Cool, glad to help 😊
