### ISSUE TITLE
OpenVpn Client -  Multiwan

### ISSUE THREAD

**Issue by scimitar4444** [opnsense/core#1630]
In the settings of the OpenVPN Client under interface, you can not select any gateway groups, but only physical interfaces. Version 17.1.X

![gatway_group](https://cloud.githubusercontent.com/assets/28559754/25843055/62ada360-34a6-11e7-8897-d23a60a20dae.png)
![openvpn_gateway](https://cloud.githubusercontent.com/assets/28559754/25843068/6b108680-34a6-11e7-93d9-f8d7ba604936.png)

**Comment by AdSchellevis** [comment]
a gateway isn't an interface.... you can listen on any interface or if I'm not mistaken listen on an interface group (different type of interface)

**Comment by fichtner** [comment]
interface groups are only an abstraction for the firewall rules

**Comment by scimitar4444** [comment]
Good. If so, why is there then at IPSEC? Or alternative with PFSense?

![gateway_ipsec](https://cloud.githubusercontent.com/assets/28559754/25845029/a7f81594-34ac-11e7-837d-83932f1f1dc2.png)
![pfsense_gateway](https://cloud.githubusercontent.com/assets/28559754/25845207/6601eca4-34ad-11e7-8559-a6d7ac90004a.png)

**Comment by AdSchellevis** [comment]
just choose any if it may use any outbound gateway (no bind). if local may contain more addresses (in openvpn), we may consider changing the current option to a multiselect.
It could help if you dropped a config how you think it should look.

**Comment by scimitar4444** [comment]
Basically, you are right. Just how do I control the priority? In my example  above, Tier 1 is a SDSL line and Tier 2 is a VDSL line at Gateway_Tunnel. The OpenVPN tunnel run  always over the SDSL line. Only in the case of backup run the OpenVPN tunnel over  the VDSL line. The  "Normal" Internet traffic should be exactly the opposite. That always over VDSL and only in the event of failure via SDSL. This is the Gateway_Internet.

**Comment by AdSchellevis** [comment]
From openvpn's perspective you don't, the interface only drives the bind address, sending traffic is a gateway decision. 
You might define a firewall rule for outbound traffic, steering it the right way using policy routing via the gateway group, shouldn't be that hard to try.
(It might be an idea to bind to an internal address and policy route from there).
