### ISSUE TITLE
[FEATURE] Need FieldType which allows special chars for regexp

### ISSUE THREAD

**Issue by mimugmail** [opnsense/core#1631]
Hi,

within the Quagga plugin I want to build AS-Path lists for BGP.

In the configuration file they look like this:

```
ip as-path access-list 1 permit ^$
ip as-path access-list 2 permit _12340$
ip as-path access-list 3 permit _8767$
```

EDIT: They could also look like 

`ip as-path access-list  1 ^6[4-5][4-6][0-9][0-9]$`

When I use FieldType Text I can insert the value, but when creating a ModelRelation field pointing to it, it wont get recognized. If I don't use the special characters it works.

Perhaps there's a way how to avoid creating a new FieldType? 

Thanks!

**Comment by AdSchellevis** [comment]
Hi Michael,

Can you explain with a short example what your model looks like for this piece?
The relation field is meant to model a normal foreign key type of relation, a fuzzy match might not be the best solution here, but I need some more context to help you out.
I don't have a lot of time available, so please excuse me for not reading the current codebase.

Best regards,

Ad

**Comment by mimugmail** [comment]
Hi,

thanks for taking the time! 

I have also an issue open at the plugins Project:
https://github.com/opnsense/plugins/issues/150

There you can see what I want to do. Please don't take care about the other problem within this issue because I'll restructure the whole process, but AS Path lists are regexp in config.

Here is a sample config from a Quagga BGP daemon:

```
router bgp 65550
 network 192.168.0.0/24
 neighbor 1.1.1.1 remote-as 8767
 neighbor 1.1.1.1 update-source eth0
 neighbor 1.1.1.1 route-map SET_IN_FILTER in
!
ip as-path access-list 3 permit _8767$
!
route-map SET_MNET_IN_FILTER permit 10
 match as-path 3
 set local-preference 300
!
```

This is the config in text file.

So, I created a tab AS-Path (like in screenshot in plugins/ #150), then I create a tab Route-Map and there is the ModelRelation field to the AS-Path list. In the end I have to add the Route-Map with the referenced AS-Path list to a specific neighbor. 

Hope this helps :)

**Comment by mimugmail** [comment]
@AdSchellevis Sorry, forgot the model:

This is the field for the AS Path input:

https://github.com/mimugmail/plugins/blob/bgp/net/quagga/src/opnsense/mvc/app/models/OPNsense/Quagga/BGP.xml#L105

And the reference in the route-map tab is:

https://github.com/mimugmail/plugins/blob/bgp/net/quagga/src/opnsense/mvc/app/models/OPNsense/Quagga/BGP.xml#L135

When only using number like:

`ip as-path access-list 3 permit 8767`

I can select the list, but with:

`ip as-path access-list 3 permit _8767$`

there's only "none"

**Comment by AdSchellevis** [comment]
@mimugmail just to be sure, when your text field contains a regex and you show the name field, it can't find the uuid anymore (no display in the gui)? if that's the case, it sounds like a bug somewhere.
The relation fields use the uuid of the array item, so the actual content shouldn't really matter.

**Comment by mimugmail** [comment]
@AdSchellevis Hm, I'm a bit embarressed now. After you said it sounds like a bug I started browser debugging to find some errors but now it works. I don't really know why, but it's getting saved now correctly. Perhaps I had a wrong relation set but I did so many changes since then ... can't say why. 

Sorry for wasting your time :(

**Comment by AdSchellevis** [comment]
@mimugmail no problem, things happen, enjoy the rest of your coding journey and feel free to open an issue when you run into trouble.
