### ISSUE TITLE
DNS Resolver: Overrides --> Domain Overrides --> add RFC1918 PTR not works

### ISSUE THREAD

**Issue by ra1nb0w** [opnsense/core#1637]
hello,
I notice this problem: if I add a network reverse zone like 168.192.in-addr.arpa, unbound.inc doesn't add
`local-zone: "168.192.in-addr.arpa" typetransparent` to /var/unbound/unbound.conf and if I use the "Custom options" is too late, will be after `private-domain` and unbound doesn't start.
I see that pfsense/../unbound.inc [link](https://github.com/pfsense/pfsense/blob/ac446eac051c4514666f9904bbdd0609468f2fc5/src/etc/inc/unbound.inc#L518) add this line and works correctly. If I add the line to opnsense unbound.inc it works but $pvt is only true or false. Is it a design decision that I don't realize or it is only a bug?

thanks for your great work!

OPNsense 17.1.6-amd64
FreeBSD 11.0-RELEASE-p8
OpenSSL 1.0.2k 26 Jan 2017

**Comment by fichtner** [comment]
fixed by @ra1nb0w via 51b6f4dfc02d6
