### ISSUE TITLE
[17.1.6] CPU 100% when enabling SNMP Host Resources module

### ISSUE THREAD

**Issue by alexchiolo** [opnsense/core#1638]
hi, I have been monitoring interfaces on our firewalls with SNMP for a while; today I tried enabling the Host Resources module to start collecting CPU and memory usage and noticed that doing this makes the host use most of the available CPU:

with only MibII enabled:
		11	root	155	ki31	0K	16K	RUN	 	373.8H	100.00%	[idle]
	62918	root	20	0	1062M	5744K	select	 	0:00	0.00%	/usr/sbin/bsnmpd -c /var/etc/snmpd.conf -p /var/run/snmpd.pid

with MibII and Host Resources:
25392	root	98	0	1118M	44032K	RUN	 	1:07	83.69%	/usr/sbin/bsnmpd -c /var/etc/snmpd.conf -p /var/run/snmpd.pid
	14	root	-8	-	0K	48K	-	 	0:41	11.47%	[geom{g_event}]
	11	root	155	ki31	0K	16K	RUN	 	373.8H	0.00%	[idle]

not sure if this is relevant but the firewall is a VM on ESXi 6.0 with a dedicated xeon core and vmware tools installed. the Host Resources mib works with no CPU impact on other VMs running linux/net-snmp hosted on the same server. Rebooting the firewall made no difference.

**Comment by fichtner** [comment]
Hi @alexchiolo,

It's a known bug in FreeBSD 11.0: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=215471

You can mount a CD to fix this temporarily. It seems nobody is working on this in FreeBSD. It has to do with the kernel device subsystem. We know this was ok in OPNsense 16.7 with FreeBSD 10.3


Cheers,
Franco

**Comment by alexchiolo** [comment]
Thanks Franco for the quick response; removing the CD altogether form the VM configuration did the trick as well.
