### ISSUE TITLE
users: unhide QR code by default or add a hint?

### ISSUE THREAD

**Issue by fichtner** [opnsense/core#1639]
Hi Ad,

Quick questions since users seem to miss that they have easy access to QR codes for 2FA:

Should we unhide it or at least add a visible note? I'm partially for unhiding it, but I can understand if there are concerns with the secrecy of it and that it could be captured by photo/film in an instant.

Also see: https://forum.opnsense.org/index.php?topic=5155.0

Thanks,
Franco

**Comment by AdSchellevis** [comment]
let's add a visible note then, maybe as simple as chaning the caption in :
OTP seed (click to unhide)

**Comment by fichtner** [comment]
Sounds good, do you want to do it or should I?

**Comment by fichtner** [comment]
Thanks! :)

**Comment by AdSchellevis** [comment]
you're welcome
