### ISSUE TITLE
[FR] Need stable sorting in Jinja2 template

### ISSUE THREAD

**Issue by mimugmail** [opnsense/core#1641]
Hi,

I have to sort a list in template generation for name and within this for an id.
My template looke like:

https://github.com/mimugmail/plugins/blob/bgp/net/quagga/src/opnsense/service/templates/OPNsense/Quagga/bgpd.conf#L58-L75

With this I get an output of:

```
route-map RR permit 20
 match as-path 2
 set community 4444:33
route-map RR permit 10
 match as-path 1
 set local-preference 300
route-map TESTMAP permit 10
 set local-preference 320
```

As you can see the names of the Route-maps "RR" and "TESTMAP" gets correctly sorted, but I also have the filed id which should be sorted also. 

Here's a link how to do that:
http://stackoverflow.com/questions/16143053/stable-sorting-in-jinja2

I talked to @fichtner and he told me that configd needs some attention for this, so here's my feature request :)

**Comment by AdSchellevis** [comment]
https://github.com/opnsense/core/commit/e4082599441f054f5df4b017219a69bb4c1d0d15 should do the trick

```
{%  for item in helpers.sortDictList(OPNsense.ConfigObject, 'description') %}
    {{item.description}}
{%  endfor %}

```

**Comment by mimugmail** [comment]
Hi, 

this only sorts for the name. So:

`{%     for routemap in helpers.sortDictList(OPNsense.quagga.bgp.routemaps.routemap, 'name') %}`

Does:

```
route-map RR permit 20
 match as-path 2
 set community 4444:33
route-map RR permit 10
 match as-path 1
 set local-preference 300
route-map TESTMAP permit 10
 set local-preference 320
```

The name gets correctly sorted, but what I need is:

```
route-map RR permit 10
 match as-path 1
 set local-preference 300
route-map RR permit 20
 match as-path 2
 set community 4444:33
route-map TESTMAP permit 10
 set local-preference 320
```

Any idea?

**Comment by AdSchellevis** [comment]
you should be able to add the other sort criteria as well, like sortDictList(item, 'key1', 'key2')

**Comment by mimugmail** [comment]
True that, my fault! Works like a charm ... I love it/you/OPN 👍

**Comment by AdSchellevis** [comment]
great! :)

**Comment by mimugmail** [comment]
@AdSchellevis @fichtner  Sorry, I have to reopen this.

The config gerneration is here:
https://github.com/opnsense/plugins/blob/master/net/quagga/src/opnsense/service/templates/OPNsense/Quagga/bgpd.conf

The problem is, when there's only one entry, so nothing to sort, this one entry won't be written to the configuration. Is there a design error within my template or does sortDictList need some tweaking?

**Comment by AdSchellevis** [comment]
@mimugmail doesn't sound good, I will try to look into this as soon as possible.

**Comment by AdSchellevis** [comment]
@mimugmail can you check https://github.com/opnsense/core/commit/2e096b3e72fccf215a39a6aa6352ccde50a64137 ? it looks like it's missing a type

**Comment by mimugmail** [comment]
You did it, thanks! 👍
