### ISSUE TITLE
Feature request: pppoe reconnect and dhcp renew

### ISSUE THREAD

**Issue by sachaz** [opnsense/core#1642]
Hi,

some context: I want to disconnect & reconnect a pppoe connexion on a remote site.
with the interface I have the availability in the interface overview to disconnect a pppoe not to reconnect (disconnect & connect), should be useful for remote admin.

Best regards,
Sacha

**Comment by zitlo** [comment]
yeah same problem here. Im using a cron for an reboot after 1min for this. :(

**Comment by fichtner** [comment]
Sorry, no time at the moment to spare for this.
