### ISSUE TITLE
Unable to delete IDS auto update rules cron entry

### ISSUE THREAD

**Issue by thomasnilsen** [opnsense/core#1643]
Cannot remove rule after added. Tried to clone rule and delete, works but the original rule cannot be deleted.

**Comment by fichtner** [comment]
@thomasnilsen which page are you referring to? (see contribution guide on bug reports)

Because if you reference System: Settings: Cron that's intended, because the cron job is owned by the IDS subsystem as an "anchor" to prevent accidental removal. As such, it can only be disabled.

Maybe having a trash button that doesn't delete or it not producing an error would be better here for UX?

**Comment by thomasnilsen** [comment]
Hi @fichtner

I added the rule from IDS and schedule. I noticed I was redirected to and from the cron page in the process.

The only place I could try to delete was under cron and it was impossible. Still after disable IDS etc I could not delete. No error message either.

So I guess creating the rule makes it impossible to delete. Waste of time to run rule update when IDS is disabled for example.

Regards
Thomas

**Comment by fichtner** [comment]
It easily disables. I'll look into whether it's doing any work if the whole subsystem is disabled.

**Comment by adamcarter81** [comment]
I see the same behaviour - the suracati service keeps stopping, so to troubleshoot I thought I would stop/delete the update rule, but when clicking on Services -> Intrusion Detection -> Schedule tab it goes straight to edit the rule.  If I Save or Close then it jumps back to the settings tab. It does seem to save any changes here though, but can't delete the rule.

Under cron I can enable/disable/edit the rule but again can't delete

This happened with version 17.1.6 & 17.1.7

**Comment by giovino** [comment]
Version: OPNsense 17.1.8-amd64

I am reporting the same problem adamcarter81 reported above. 

Steps to repeat:

1. Click  Services > Intrusion Detection > Schedule
2. Create a rule to "update and reload intrusion detection rules" once a day > save changes
3. Click  Services > Intrusion Detection > Schedule
4. The "Edit Job" screen appears
    * url: ```https://opnsense.localdomain/ui/cron/item/open/d7bf407e-c3c1-447c-8a44-eea0b281400d```

5. Click "Close"
6. For one second you can see a listing of the existing scheduled job then you are redirected to the Intrusion Detection settings tab
    * url: ```https://opnsense.localdomain/ui/ids/```

My expectation is, once a scheduled job has been created, clicking the "Schedule" tab with Intrusion Detection would take me to a list of scheduled jobs, if I wanted to edit one I would need to click an edit button.

**Comment by fichtner** [comment]
The page is under System: Settings: Cron.

I get that the "guided" handling of the IDS cron job is confusing, but it is not designed as a defect, but as a safeguard to prevent accidental tampering with the job from a non-IDS portion of the GUI.

What does everyone expect? Wouldn't it be just as annoying to have a deleted job reappear the next time the IDS is saved? What is the rationale for not using the "disable" for these sort of scenarios when the job is unwanted?

**Comment by giovino** [comment]
@fichtner I think I would find the following more intuitive:

## Minor change

  1. Click Services > Intrusion Detection > Schedule
  1. Click Schedule
  1. Create the IDS job > Save Changes
  1. Redirect the user to System > Settings > Cron
      * ```https://opnsense.localdomain/ui/cron/```

## Larger change

  1. Click Services > Intrusion Detection > Schedule
  1. Click Schedule
  1. *new window*: two buttons - create new & edit existing

Create new:
  1. Create the IDS job > Save Changes
  1. Redirect the user to System > Settings > Cron
      * ```https://opnsense.localdomain/ui/cron/```

Edit existing:
  1. Redirect the user to System > Settings > Cron
      * ```https://opnsense.localdomain/ui/cron/```

-----

or some other better solution, I find current behavior confusing although now that I understand it, I can certainly live with it.

**Comment by fichtner** [comment]
thanks for the clarification 👍 

I don't know if either proposed change fits the way the pages do work, because we don't want to duplicate code in controllers that are not native to cron.

The simplest solution seems to simply add a cron link and stop "faking" a native tab in the IDS, but it needs to retain the simple work flow and hopefully route back to the IDS page.

I'll think about it. :)

**Comment by fichtner** [comment]
This hasn't come up in months of forum activity, I'm closing this as we want to spend quality time in other areas that require improvements.

**Comment by dimme** [comment]
The cron job created by suricata can still not be deleted.

**Comment by AdSchellevis** [comment]
that's intentional, you can disable it.

**Comment by dimme** [comment]
The intentional behavior does not match the intention of the owner. Editing the crontab doesn't help either. Any idea which file can be edited to get rid of this job?
