### ISSUE TITLE
failover peer invalid argument in dhcpd.log

### ISSUE THREAD

**Issue by rszilvi** [opnsense/core#1645]
OPNSense version: 17.1.6 (installed)

https://127.0.0.1/services_dhcp.php

CARP VIP resides on OPT2 interface
OPT2 Interface name renamed from original
XMLRPC Sync - all set
DHCP only enabled on this opt interface

When Failover Peer is configured, DHCP peers always remain in unknown state.
(Workaround: static ARP enabled and leases are visible on both)

I think the ports on both machines need to be different, however they are mixed up.
Primary never choosen, although carp skew seems to be ok.
192.168.x.254/24 (vhid 4 , freq. 1 / 0 )  - primary
192.168.x.254/24 (vhid 4 , freq. 1 / 100 )  - backup

failover peer "dhcp_opt2" {
  secondary;
  address 192.168.x.252;
  port 520;
  peer address 192.168.x.253;
  peer port 519;
  max-response-delay 10;
  max-unacked-updates 10;
  
  load balance max seconds 3;
}
failover peer "dhcp_opt2" {
  secondary;
  address 192.168.x.253;
  port 520;
  peer address 192.168.x.252;
  peer port 519;
  max-response-delay 10;
  max-unacked-updates 10;
  
  load balance max seconds 3;
}

**Comment by rszilvi** [comment]
Apologies CARP Netmask was wrong.

**Comment by fichtner** [comment]
no worries, thanks for reporting back :)
