### ISSUE TITLE
[17.1] adding pasting a ssh-pubkey doest not strip comments

### ISSUE THREAD

**Issue by sjorge** [opnsense/core#1648]
When adding a ssh pubkey for a user, the comment is not stripped.
When it is written to the .ssh/authorized_keys file a comment of the user's login gets appended.

Commends should probably be stripped first.

```
keytype hash commentOPNSENSECOMMENT
```

Is how it shows up

**Comment by fichtner** [comment]
I would have thought it just writes the line as is, comment or no

**Comment by sjorge** [comment]
I ran a few new tests, looks like it indeed just dumps the line. But it does not add a new line at the end, which made my terminal dump the username behind it and then again the PS1 string on the next line.

**Comment by fichtner** [comment]
Hmm, I'll take a look, trailing new lines are cool...
