### ISSUE TITLE
upgrade to 15.1.10 trough console failed

### ISSUE THREAD

**Issue by jstrebel** [opnsense/core#165]
Hi, I tried to upgrade as advised trough the serial console (ssh). I get the message system is up to date. 
I did first a restart of the web interface. Then I did a reboot and again a upgrade trough the console.
Running on a APU booting from the SD Card.

Enter an option: 12

This will automatically fetch all available updates, apply them,
and reboot if necessary.  Proceed with this action? [y/N]: y

Updating OPNsense repository catalogue...
OPNsense repository is up-to-date.
All repositories are up-to-date.
Checking for upgrades (81 candidates): 100%
Processing candidates (81 candidates): 100%
Checking integrity... done (0 conflicting)
Your packages are up to date.
Checking integrity... done (0 conflicting)
Nothing to do.

Restarting webConfigurator...done.

Your system is up to date.

*** Welcome to OPNsense 15.1.9.2_1-7cced4096 (amd64) on OPNsense ***

**Comment by fichtner** [comment]
Jakob, can you do a `df -h' as well as `pkg info' for me? I'm thinking /var/db/pkg/* was overwritten or has been wiped. We've had similar problems in the past.

**Comment by jstrebel** [comment]
df -h
Filesystem            Size    Used   Avail Capacity  Mounted on
/dev/ufs/OPNsense0    912M    593M    246M    71%    /
devfs                 1.0K    1.0K      0B   100%    /dev
/dev/md0              3.4M     96K    3.0M     3%    /var/run
devfs                 1.0K    1.0K      0B   100%    /var/dhcpd/dev

pkg info
3gstat-20091215_1              3G status
apinger-0.6.1_3                IP device monitoring tool
ataidle-2.7.2                  Utility to spin down ATA drives
b43-fwcutter-015               Extracts firmware for Broadcom Wireless adapters
beep-1.0_1                     Beeps a certain duration and pitch out of the PC Speaker
bind-tools-9.10.2              Command line tools from BIND: delv, dig, host, nslookup...
bsdinstaller-2.1.1_16          BSD Installer mega-package
bsnmp-regex-0.6_1              bsnmpd module allowing creation of counters from log files
bsnmp-ucd-0.4.1                bsnmpd module that implements parts of UCD-SNMP-MIB
bwi-firmware-kmod-3.130.20     Broadcom AirForce IEEE 802.11 Firmware Kernel Module
ca_root_nss-3.18               Root certificate bundle from the Mozilla Project
choparp-20021107_4             Simple proxy arp daemon
clog-1.0.1_3                   Circular log support for FreeBSD syslogd
cpdup-1.17_2                   Comprehensive filesystem mirroring and backup program
cpustats-0.1                   cpustats
curl-7.41.0                    Non-interactive tool to get files from FTP, GOPHER, HTTP(S) servers
czmq-2.2.0_1                   High-level C Binding for ZeroMQ
dhcp6-20080615_2               KAME DHCP6 client, server, and relay
dhcpleases-0.1_1               read dhpcd.lease file and add it to hosts file
dhcpleases6-0.1_1              read dhpcd6.leases file and trigger command on modification
dmidecode-2.12                 Tool for dumping DMI (SMBIOS) contents in human-readable format
dnsmasq-2.72,1                 Lightweight DNS forwarder, DHCP, and TFTP server
easy-rsa-2.2.0.m               Small RSA key management package based on openssl
expat-2.1.0_2                  XML 1.0 parser written in C
expiretable-0.6_1              Utility to remove entries from the pf(4) table based on their age
filterdns-0.1                  filterdns
filterlog-0.1                  filterlog
fping-3.10                     Quickly ping multiple hosts without flooding the network
freetype2-2.5.5                Free and portable TrueType font rendering engine
gettext-runtime-0.19.4         GNU gettext runtime libraries and programs
gmp-5.1.3_2                    Free library for arbitrary precision arithmetic
idnkit-1.0_5                   Library to handle internationalized domain names
ifstated-5.1,3                 Interface state daemon
igmpproxy-0.1_2,1              Multicast forwarding IGMP proxy
indexinfo-0.2.3                Utility to regenerate the GNU info page index
ipfw-classifyd-0.1_1           application classifier
isc-dhcp42-client-4.2.8        The ISC Dynamic Host Configuration Protocol client
isc-dhcp42-relay-4.2.8         The ISC Dynamic Host Configuration Protocol relay
isc-dhcp42-server-4.2.8        ISC Dynamic Host Configuration Protocol server
libart_lgpl-2.3.21_2,1         Library for high-performance 2D graphics
libdaemon-0.14_1               Lightweight C library that eases the writing of UNIX daemons
libevent2-2.0.22_1             API for executing callback functions on events or timeouts
libffi-3.2.1                   Foreign Function Interface
libltdl-2.4.6                  System independent dlopen wrapper
libmcrypt-2.5.8_2              Multi-cipher cryptographic library (used in PHP)
libpdel-0.5.3_6                Packet Design multi-purpose C library for embedded applications
libressl-2.1.6                 Free version of the SSL/TLS protocol forked from OpenSSL
libsodium-1.0.2                Library to build higher-level cryptographic tools
libssh2-1.4.3_5,2              Library implementing the SSH2 protocol
libxml2-2.9.2_2                XML parser library for GNOME
libzmq4-4.0.5                  ZeroMQ core library (Version 4)
lighttpd-1.4.35_5              Secure, fast, compliant, and flexible Web Server
lzo2-2.09                      Portable speedy, lossless data compression library
minicron-0.0.2                 very small cron
miniupnpd-1.9_1,1              UPnP IGD implementation which uses pf/ipf
mpd4-4.4.1_2                   Multi-link PPP daemon based on netgraph(4)
mpd5-5.7_2                     Multi-link PPP daemon based on netgraph(4)
nettle-2.7.1                   Low-level cryptographic library
ntp-4.2.8p2                    The Network Time Protocol Distribution
oniguruma4-4.7.1_1             BSDL Regular Expressions library compatible with POSIX/GNU/Perl
openldap-client-2.4.40_1       Open source LDAP client implementation
openssh-portable-6.8.p1_5,1    The portable version of OpenBSD's OpenSSH
openvpn-2.3.6_3                Secure IP/Ethernet tunnel daemon
opnsense-15.1.9.2_1            7cced4096
os-update-15.1.9               OPNsense system update utility
pcre-8.35_2                    Perl Compatible Regular Expressions library
pear-1.9.4_3                   PEAR framework for PHP
pear-PHP_CodeSniffer-2.2.0     PHP Script Tokenises and Sniffs PHP and JavaScript code
pecl-radius-1.2.7              Radius client library for PHP
pecl-ssh2-0.12                 PECL extension to the libssh2 library
pftop-0.7_4                    Utility for real-time display of statistics for pf
phalcon-1.3.4                  Phalcon PHP Framework written in C-language
php-pfSense-0.1_9              Library for getting useful info
php-suhosin-0.9.37.1_1         PHP extension that implements high-level protections
php-xdebug-2.2.5               Xdebug extension for PHP
php56-5.6.8                    PHP Scripting Language
php56-bcmath-5.6.8             The bcmath shared extension for php
php56-bz2-5.6.8                The bz2 shared extension for php
php56-ctype-5.6.8              The ctype shared extension for php
php56-curl-5.6.8               The curl shared extension for php
php56-dom-5.6.8                The dom shared extension for php
php56-filter-5.6.8             The filter shared extension for php
php56-gettext-5.6.8            The gettext shared extension for php
php56-hash-5.6.8               The hash shared extension for php
php56-json-5.6.8               The json shared extension for php
php56-ldap-5.6.8               The ldap shared extension for php
php56-mbstring-5.6.8           The mbstring shared extension for php
php56-mcrypt-5.6.8_1           The mcrypt shared extension for php
php56-mysql-5.6.8              The mysql shared extension for php
php56-openssl-5.6.8            The openssl shared extension for php
php56-pcntl-5.6.8              The pcntl shared extension for php
php56-pdo-5.6.8                The pdo shared extension for php
php56-pdo_sqlite-5.6.8_1       The pdo_sqlite shared extension for php
php56-session-5.6.8            The session shared extension for php
php56-simplexml-5.6.8          The simplexml shared extension for php
php56-sockets-5.6.8            The sockets shared extension for php
php56-sqlite3-5.6.8_1          The sqlite3 shared extension for php
php56-tokenizer-5.6.8          The tokenizer shared extension for php
php56-xml-5.6.8                The xml shared extension for php
php56-zlib-5.6.8               The zlib shared extension for php
pkg-1.5.1                      Package manager
png-1.6.16                     Library for manipulating PNG images
python27-2.7.9_1               Interpreted object-oriented programming language
qstats-0.1_1                   read dhpcd.lease file and add it to hosts file
radvd-1.9.7                    Linux/BSD IPv6 router advertisement daemon
rate-0.9                       Traffic analysis command-line utility
relayd-5.5.20140810_1          OpenBSD relay daemon
rrdtool12-1.2.30_7             Round Robin Database Tools v1.2
smartmontools-6.3              S.M.A.R.T. disk monitoring tools
sqlite3-3.8.9_1                SQL database engine in a C library
ssh_tunnel_shell-0.1_3         SSH Tunneling Shell
sshlockout_pf-0.0.2_2          Automatically block IPs with failed SSH logins using pf(4)
strongswan-5.3.0_2             Open Source IKEv2 IPsec-based VPN solution
syslogd-10.1                   FreeBSD syslogd with clog and zmq additions
voucher-0.1_4                  voucher support
wol-0.7.1_2                    Tool to wake up Wake-On-LAN compliant computers
zip-3.0_1                      Create/update ZIP files compatible with PKZIP
root@OPNsense:~ #

**Comment by fichtner** [comment]
Hi Jakob, this version is a LibreSSL version and the mirrors haven't been updated yet. So this is expected... Mirrors will go up in half an hour.
