### ISSUE TITLE
Feature: Bulk / Mass - Import of Firewall rules

### ISSUE THREAD

**Issue by derWeihnachtsmann** [opnsense/core#1656]
Hey, maybe there is already a possibility to mass-import IP-Adresses in firewall rules. 
And maybe also assign rules to groups, and enable or disable the whole group with all the IP-rules in.  

Many thanks guys! <3

**Comment by fichtner** [comment]
Hi there,

Yes, you want to look under Firewall: Aliases: Import. The "Host(s)" can input a list of IP addresses or FQDNs. Later, you can edit this new alias under Firewall: Aliases: View to add/remove entries.

In the firewall rules simply use the alias for source or destination, it will show up in the selection.

Please close if that is what you were looking for. :)


Cheers,
Franco

**Comment by derWeihnachtsmann** [comment]
Hey, thanks for your response!
That is what I was looking for! Awesome!

Thank you so much Franco!

**Comment by fichtner** [comment]
great, enjoy :)

**Comment by tuxthemadpenguin** [comment]
I can't seem to find the import option.  Was it removed or is it missing from the current version?

**Comment by AdSchellevis** [comment]
@tuxthemadpenguin we removed the import page, since you can copy-paste into the content part of the alias now.
