### ISSUE TITLE
Feature: Reverse DNS/whois in "insight" - pie chart

### ISSUE THREAD

**Issue by derWeihnachtsmann** [opnsense/core#1658]
Hey, it's me again,
maybe I should read the f*** manual one more time, but I don't see the switch to enable that feature.. 
I'm asking myself if it's possible to do a reverse DNS-search (or Whois) on the Pie-chart in the  Reporting | Insight  view.? That would be a pretty nice feature.

Thanks again to all who make this project possible!

**Comment by juj** [comment]
This seems to be a duplicate of #1034.

**Comment by AdSchellevis** [comment]
it's indeed a duplicate, if I can find some time I might add the functionality, it would indeed be practical to have it.
Let me close this issue, we keep the original one open.
