### ISSUE TITLE
Suricata IPS mode issue

### ISSUE THREAD

**Issue by L1ghtn1ng** [opnsense/core#1659]
When playing around with the default packet size advanced option even when I set it to the MTU of my network I still get downloads sometimes stalling or when trying to fetch or push from github it always times out.

When I disable suricata I do not have this issue.

On OPNsense 17.1.7 64 bit A10 with the default-packet-size patch applied that is coming in 17.1.8

I also run a proxy as well. I have been having this issue for a very long time and would love to have this issue resolved.

cc @fichtner

**Comment by AdSchellevis** [comment]
there's not a lot of info in the issue, but have you tried enabling IPS on the other interface to narrow it down a bit (if you're using wan now, switch to lan and repeat the same test)?

**Comment by L1ghtn1ng** [comment]
I have tried it with wan and I have no issue as it does not seem to inspect the traffic as it does not block the eicar test file. I have it now set to wan & lan it does inspect traffic and block the eicar file but only on the lan side. I did send earlier reports to franco via email.

**Comment by AdSchellevis** [comment]
you're using pppoe, aren't you? That might explain why suricata doesn't see the traffic on the wan side. It's probably best not to enable both, if one of them wasn't functional before.

**Comment by L1ghtn1ng** [comment]
Yes, will disable it on the WAN then and just leave it on the LAN but would also love to have it work on the WAN as well though.

Sent from phone

________________________________

**Comment by AdSchellevis** [comment]
I'm not sure if suricata/netmap supports pppoe decapsulation, although I don't think they do. netmap on pppoe interfaces is not supported as far as I know. 

I don't mind leaving the issue open, but if it's related to pppoe and/or missing support in either netmap or suricata I don't expect it's something we can solve.

**Comment by L1ghtn1ng** [comment]
I have let Victor know and he is traveling at the moment so hopefully we will get his input soon

Sent from phone

________________________________

**Comment by L1ghtn1ng** [comment]
@AdSchellevis Just out of curiosity how hard would it be to get PPPoE decapsulation support in netmap if it does not support it? As the amount of users that have issues due to this is high. In my opinion this is a bug, but I think other people will think otherwise.

**Comment by AdSchellevis** [comment]
@L1ghtn1ng if I'm not mistaken you need netmap support on the pppoe device to make it work (or decapsulation support in suricata to capture the traffic on the real interface), not really my area of expertise, but I figure it's quite some work.

**Comment by L1ghtn1ng** [comment]
I use a A10 so that does not have support for it?

Sent from phone

________________________________

**Comment by AdSchellevis** [comment]
Intel network cards (like the A10 uses) have the best known netmap support, but you either need support in FreeBSD for the virtual driver (pppoe/mpd5) or suricata should be capable of decoding the pppoe stream.

**Comment by L1ghtn1ng** [comment]
So to try and make it clear and provide more information for victor when downloading in firefox it will start the download and get to a certain point in the download and just stop. It never recovers, when restarting the download it sometimes manages to complete the download.

Since OPNsense 17.1.8 in the advanced tab you can now change the default packet size parameter in suricata.yaml with me putting it to 1500 as that is the MTU on the LAN it has helped. I still get the behaviour mentioned above but on the second go it now manages to download the file I am downloading at that moment in time.

If I disable Suricata everything works correctly i.e can download things first time and also am able to push,fetch,pull from github. If I enable Suricata in IPS mode I get the issues I have mentioned in this post. 

I have also tried Suricata in IDS mode and everything also works correctly in that configuration as well.

So from this post I hope it is clear to everyone the issues I am having and would like if possible fixed.

**Comment by L1ghtn1ng** [comment]
@AdSchellevis with speaking to @inliniac via email I need the following in a patch that will allow me to enable the following taken from the email  "if you enable drop log do you see drops? If so please share.

Additionally, if you enable stream events, do you get alerts? If so,
please share those too.
"

So I can provide victor with the information to track down the issues I am having.

**Comment by AdSchellevis** [comment]
@L1ghtn1ng you can easily change settings in suricata.yaml for testing and restart suricata afterwards.
Use the following statement to restart suricata without loosing changes made manually:
```
service suricata restart
```

**Comment by L1ghtn1ng** [comment]
@inliniac I have enabled more of the decoder-events.rules and made the alerts that I am getting so far changed them to block so I am getting the following in the drop.log
```
07/02/2017-20:46:12.940210: IN= OUT= SRC=0.0.0.0 DST=224.0.0.1 LEN=32 TOS=0x192 TTL=1 ID=0 PROTO=IGMP Unknown protocol
07/02/2017-20:48:18.381601: IN= OUT= SRC=0.0.0.0 DST=224.0.0.1 LEN=32 TOS=0x192 TTL=1 ID=0 PROTO=IGMP Unknown protocol
07/02/2017-20:50:23.823193: IN= OUT= SRC=0.0.0.0 DST=224.0.0.1 LEN=32 TOS=0x192 TTL=1 ID=0 PROTO=IGMP Unknown protocol
```

And this in the Web ui 

```
2017-07-02T20:50:23.823193+0100	blocked	0.0.0.0	224.0.0.1	SURICATA IPv4 padding required 	
2017-07-02T20:48:18.381601+0100	blocked	0.0.0.0	224.0.0.1	SURICATA IPv4 padding required 	
2017-07-02T20:46:12.940210+0100	blocked	0.0.0.0	224.0.0.1	SURICATA IPv4 padding required 
```

**Comment by L1ghtn1ng** [comment]
I have also gotten this alert as well SURICATA STREAM CLOSEWAIT FIN out of window in the alerts tab

**Comment by L1ghtn1ng** [comment]
This one also SURICATA STREAM 3way handshake wrong seq wrong ack

**Comment by L1ghtn1ng** [comment]
SURICATA STREAM Packet with invalid timestamp

**Comment by L1ghtn1ng** [comment]
@AdSchellevis Do you think you would be able to get help with this issue from @inliniac?

**Comment by AdSchellevis** [comment]
@L1ghtn1ng sorry, too busy, I honestly don't think this works like you would like it to work.

**Comment by abraxxa** [comment]
I have enabled Suricata again just to find out that my guest network isn't working because it's on the internal lan interface with vlan tagging.
VLAN Hardware Filtering is set to 'Leave default', all offloadings are disabled as per OPNsense IPS docs. The physical LAN interface is the only one I've selected in the IPS settings, the Guest VLAN interface is listed but according to what I've read it only works in promiscuous mode on physical interfaces.
The NIC is a Realtek RTL8111F on a Gigabyte GA-J1900N-D3V mainboard.

**Comment by abraxxa** [comment]
After updating to 17.7.1_2 which includes Suricata 4.0.0 I've tried again, this time also enabling the IPS on the Guest VLAN in addition to the untagged, which is my internal network, and it works!
Have there been any changes besides the Suricata update which might have affected this? How should it be configured when you have one interface with one untagged network and one tagged connected? An earlier issue states that you should only enable the IPS on physical (untagged) interfaces and a GUI patch was applied back then to only list such interfaces. Is this still the fact of is it possible to run the IPS on VLAN interfaces too these days?

**Comment by fichtner** [comment]
@abraxxa there were two patches in 17.7.1 that affected VLAN (re)configuration workflow away from Suricata itself, @adschellevis said this helped with stability of Suricata on VLANs and it seems he was right about it.

Other issues mainly address interfaces types like PPPoE (mpd5-based connections) that are not fully physical on the upper layer as the interface would present itself and this fails for IPS (Netmap mode) although IDS mode works all the time (PCAP/BPF mode).

**Comment by abraxxa** [comment]
I've read about the PPPoE issue and therefore haven't enabled Suricata on the outside interface(s) (native IPv4 via PPPoE and 6in4 via Tunnelbroker over that PPPoE connection).
Should this work now as well? If so I'd deactivate the IPs on the internal interfaces and enable it only on the two outside ones.

**Comment by fichtner** [comment]
Most likely still problematic. This is FreeBSD kernel territory, which didn't change since January 2017 when we moved to FreeBSD 11.0.

**Comment by L1ghtn1ng** [comment]
Just tested on the WAN interface and still does not work with pppoe


________________________________

**Comment by L1ghtn1ng** [comment]
@fichtner @AdSchellevis I have 2 suggestions that I would like to put forward that will help track down issues and help work around them.

- Add gui support for http://suricata.readthedocs.io/en/latest/performance/ignoring-traffic.html which should I hope to allow me to workaround my github/git issues with IPS mode enabled and should help other people that have issues as well

- Add gui logs tab and enable extra logs that are not enabled that will allow people to debug suricata issues far easier with log rotate on these logs as well to save disk space

**Comment by AdSchellevis** [comment]
timeout / solved or moved to  https://github.com/opnsense/core/issues/2110
