### ISSUE TITLE
OPNsense 15.1.10-267d589a8 (i386) - miniupnp fails to start

### ISSUE THREAD

**Issue by netrixtardis** [opnsense/core#166]
service fails to start, only relevant information found under 
Status: System logs: Routing

May 4 22:03:43 	miniupnpd[20959]: Failed to init redirection engine. EXITING
May 4 22:03:43 	miniupnpd[20959]: DIOCGETSTATUS: Operation not supported by device

Attempted the following to fix:  clear settings and save, reconfigure settings, to start services - did not resolve issue.

**Comment by AdSchellevis** [comment]
You probably need a reinstall of the miniupnp package, because of kernel dependencies.
Can you try to reinstall upnp by running the following in a shell (via ssh or console)?

pkg install -f miniupnpd

And then try to start it again.

**Comment by netrixtardis** [comment]
performing the steps did fix the issue.  Guess it would get a good idea to add this kind of steps in the upgrade process when a kernel update is occurred.

once kernel update is complete, to re-install certain packages that depend on it.

**Comment by fichtner** [comment]
Except that it's impossible to track this as most programs depend on the kernel. Ideally, we'd need to make sure we reinstall all packages, but that would create a lot of load on the user side. We'll have to think more about this. Thank you for helping to track this down. :)
