### ISSUE TITLE
Difference between user created from GUI and Console

### ISSUE THREAD

**Issue by gitdevmod** [opnsense/core#1660]
There is a difference in user created from GUI and Console:
Add a class in login.conf with with passwd_prompt, times.allow or times.deny 

- If I create a user from GUI and assign a class => it does not work
- If I create a user from Console (pw useradd or useradd) and assign a class => it works

**Comment by fichtner** [comment]
Users from the gui are held in a consistent state in order to avoid self-induced lockouts. Login.conf can be edited, but will be overwritten on firmware upgrades.

What is the use case here? What is the user used for?

**Comment by gitdevmod** [comment]
Hi @fichtner,
I created a FR #1661, It's for creating logon hours, ie: user can only login (shell, proxy) Friday between 8am and 17 p.m, maybe it's not the better way ?

**Comment by fichtner** [comment]
FWIW, I think the user is tripping over a feature: 
Try to disable integrated authentication under system:settings: administration ;)

**Comment by gitdevmod** [comment]
Yes, it works with disableintegratedauth
