### ISSUE TITLE
Gui slow / not responding with 150 vlan interfaces

### ISSUE THREAD

**Issue by pthag** [opnsense/core#1662]
When adding 150 vlan interfaces, the gui becomes unresponsive. If the interfaces widget is disabled it's possible to login, but still everything is slow.

**Comment by pthag** [comment]
Applied as discussed on the forum patch 9bba2092 by AdSchellevis, which makes the gui it more response again.

It's still having problem with the interface overview. And saw at boot one block of 5 interfaces IPv4 address not showing up.

**Comment by AdSchellevis** [comment]
The interfaces overview and widget seems to be one of the most annoying culprits... it's quite a call nightmare in get_interface_info() when owning multiple interfaces.
![image](https://cloud.githubusercontent.com/assets/9783985/26522806/eb648384-4308-11e7-97d5-b11fc6d444d7.png)

https://github.com/opnsense/core/commit/6401d20ec8de75f3435847e7b3097b21d3f32af9 already solves some of it, but there's more to do there.

**Comment by pthag** [comment]
Is get_interface_info() also used at the wireless status page? 

Cause also at boot it's hanging a long time at wifi (with no wifi setup). So some massive processing getting done there as well.

**Comment by AdSchellevis** [comment]
@pthag no, that should be this one if I'm not mistaken https://github.com/opnsense/core/commit/b6e4e56e0c60a513434a69c42a27497b9418b537

**Comment by AdSchellevis** [comment]
@pthag ok, here we go, I've refactored quite some code to speed things up, in case you want to test, the easiest thing to do is first reinstall the current package to make sure none of my patches are already in:

`pkg install -f opnsense`

Then apply all patches in this issue:
`opnsense-patch c14db1a 24c62ed b6e4e56 6401d20 6d2fa2b de5ff59 17a9a26 3b3ebbb`

Make sure the new configd commands are executeable:
```
chmod 700 /usr/local/opnsense/scripts/system/list_interrupts.py
chmod 700 /usr/local/opnsense/scripts/filter/list_counters.py
```
And restart configd:
`service configd restart`

After inspection, I rebooted my machine to see if all started normally, which seems to be doing it, on my end the gaps in configured interfaces are also gone.

**Comment by pthag** [comment]
Page processing goes well now! 

There is only one aesthetic detail left, all interfaces are now always listed as up. Even if they are not physically connected.

**Comment by AdSchellevis** [comment]
@pthag thanks for reporting back, missed a spot there. 

https://github.com/opnsense/core/commit/f15eb3b203997ae36fd14887b92c882a336f982d should fix the status code (it was overwritten, although it would be better to always report the actual status from the interface I guess it's better to leave this as it was now).

**Comment by fichtner** [comment]
@pthag, this seems to have been confused in the past code if it was so... "up" denotes interface status in software, and "status", however, would e.g. mean "active" or "no carrier", but the two got mixed as "no carrier" really is "up" as long as the interface is active. I don't know which other code parts rely on "up" and "down", but we should really pass all values through as is, so status would show "active" or "no carrier", etc.

**Comment by fichtner** [comment]
This one seems to be empty now: Interrupts per Second	total rate

**Comment by AdSchellevis** [comment]
@fichtner have you restarted configd?

**Comment by fichtner** [comment]
"make upgrade" always does, yes

**Comment by AdSchellevis** [comment]
on my end for status_interfaces.php
![image](https://cloud.githubusercontent.com/assets/9783985/26539873/e1285156-444e-11e7-9216-3166ed001206.png)

**Comment by AdSchellevis** [comment]
what does  `configctl system list interrupts json` report?

**Comment by fichtner** [comment]
```
{"interrupts":{"irq260":{"rate":null,"total":null,"devices":["em1"]},"irq261":{"rate":null,"total":null,"devices":["em1"]},"irq257":{"rate":null,"total":null,"devices":["em0"]},"irq256":{"rate":null,"total":null,"devices":["em0"]},"cpu3":{"rate":34,"total":1686466,"devices":["timer"]},"cpu2":{"rate":49,"total":2412281,"devices":["timer"]},"irq259":{"rate":null,"total":null,"devices":["em1"]},"irq258":{"rate":null,"total":null,"devices":["em0"]},"cpu0":{"rate":1000,"total":49181676,"devices":["timer"]},"cpu1":{"rate":44,"total":2159142,"devices":["timer"]},"irq19":{"rate":2,"total":83332,"devices":["ahci0"]},"irq4":{"rate":0,"total":325,"devices":["uart0"]}},"interrupt_map":{"ahci0":"irq19","uart0":"irq4","em1":"irq261","em0":"irq258","timer":"cpu3"}}
```

**Comment by fichtner** [comment]
interface statistics widget + GIF tunnel status are also problematic. I can take a look at the GIF tunnel thing because I have the setup here and checking against stable/17.1 confirms

**Comment by AdSchellevis** [comment]
ok, that's odd, what does `vmstat -i `say?

**Comment by fichtner** [comment]
```
# vmstat -i
interrupt                          total       rate
irq4: uart0                          325          0
irq19: ahci0                       83937          2
cpu0:timer                      49342671       1000
irq256: em0:rx0                   692685         14
irq257: em0:tx0                  3247547         66
irq258: em0:link                       2          0
irq259: em1:rx0                  3164533         64
irq260: em1:tx0                   519908         11
irq261: em1:link                       4          0
cpu1:timer                       2225259         45
cpu2:timer                       2484403         50
cpu3:timer                       1740889         35
Total                           63502163       1286
```

**Comment by AdSchellevis** [comment]
ah, I see the issue, your driver is using two interrupts. what did the old code report? rx0, tx0, rx0+tx0?

**Comment by fichtner** [comment]
oh, the old code does not show interrupt row, not kidding...

**Comment by AdSchellevis** [comment]
ah, that's logical then :) let me fix this on the page, one moment

**Comment by AdSchellevis** [comment]
@fichtner how about?
![image](https://cloud.githubusercontent.com/assets/9783985/26540752/2710f28c-4453-11e7-8642-296c6d0235de.png)

I've renamed "interrupts per second" to "interrupts" and filled out all the data accordingly.

**Comment by AdSchellevis** [comment]
@fichtner the GIF tunnel, did that work before? and if so, can you post an example before/after?

**Comment by fichtner** [comment]
irq listing looks nice, thanks!

gif tunnel issue fixed in https://github.com/opnsense/core/commit/9bb3dd61a65b556220f434cf0ba74911c0a248d5

that only leaves the interface statistics widget :)

**Comment by fichtner** [comment]
Maybe this is easier than explaining...

Interface list widget 17.1.7:

<img width="567" alt="screen shot 2017-05-29 at 10 07 32 am" src="https://cloud.githubusercontent.com/assets/1915288/26541785/7b5ecf90-4457-11e7-84a4-54daa6806f1d.png">

Interface list widget 17.7.a:

<img width="563" alt="screen shot 2017-05-29 at 10 08 45 am" src="https://cloud.githubusercontent.com/assets/1915288/26541793/85d59936-4457-11e7-9a3b-54797eaa218e.png">

Interface statistics widget 17.1.7:

<img width="566" alt="screen shot 2017-05-29 at 10 07 44 am" src="https://cloud.githubusercontent.com/assets/1915288/26541798/8fc14198-4457-11e7-8d3d-5994976d95cc.png">

Interface statistics widget 17.7.a:

<img width="560" alt="screen shot 2017-05-29 at 10 08 52 am" src="https://cloud.githubusercontent.com/assets/1915288/26541813/99d270ee-4457-11e7-8768-e9a4567e49e9.png">

**Comment by AdSchellevis** [comment]
@fichtner https://github.com/opnsense/core/commit/89a81f3ea6fa07abf1346c9f0cecfdb669507833 brings the ipv4 address back, one more to go.

**Comment by AdSchellevis** [comment]
@fichtner I missed the pfctl counters in there https://github.com/opnsense/core/commit/a206e8f6de8f08c08154f546be2776e308f249e6 

It's far from optimal, but at least way better then it was.

**Comment by fichtner** [comment]
all good, thanks for doing this work. even with low interface count this feels faster now!

**Comment by pthag** [comment]
I think it will speed up the whole thing in many ways, there was constantly this huge call list being made. Great work! Would it be an idea to list all the patches to make it work?

**Comment by AdSchellevis** [comment]
yes, it should already be faster with only a few interfaces, the more interfaces there are the sloppier it gets ;) ... not exactly linear.

**Comment by AdSchellevis** [comment]
@pthag sure, the same instruction as above applies,  the patch should look like this:
`
opnsense-patch 9bba209 c14db1a 24c62ed b6e4e56 6401d20 6d2fa2b de5ff59 17a9a26 3b3ebbb f15eb3b 932a086 9bb3dd6 89a81f3 a206e8f
`

**Comment by pthag** [comment]
My config with 150 interfaces uses a little more time than usual, but perfectly acceptable now.

**Comment by AdSchellevis** [comment]
what do you mean by usual? the same config with only a few interfaces?

**Comment by pthag** [comment]
Sorry, for the open interpretation. Yes, I meant the sort of 'classic' setup with 2 interfaces.

**Comment by AdSchellevis** [comment]
no problem at all, good to hear it's way faster now :)

**Comment by pthag** [comment]
I don't want to clutter this feed here, but one last question I don't know where to ask elsewhere. Should I now use the patches after every update until it's included in a future update?

**Comment by fichtner** [comment]
@pthag yes. I don't see this patch set in 17.1.8, maybe 17.1.9 or 17.1.10 after enough day-to-day testing, but you can also switch to opnsense-devel with 17.1.8 onward as it will have these patches included (development track).

    # opnsense-update -t opnsense-devel

(but ony for 17.1.8 and up, if you run this now it will remove the patches again)

**Comment by pthag** [comment]
The issue can be closed then I would say?

**Comment by fichtner** [comment]
It's your issue! :)

**Comment by fichtner** [comment]
@pthag thank you for the help and testing
