### ISSUE TITLE
firmware: remember installed plugins, hint at user to install them

### ISSUE THREAD

**Issue by fichtner** [opnsense/core#1663]
(when a config.xml was exported  / imported)

**Comment by fichtner** [comment]
Very cool. Even cooler if more people had the time to work on this... :)

**Comment by beren12** [comment]
As a stopgap, can we just list the installed plugins in the config so they are easy to see & reinstall?

**Comment by fichtner** [comment]
Not without creating a mapping of config sections and plugins that needs to be in core and synced almost every release. Big process. :)

**Comment by fichtner** [comment]
It's probably simpler to register installed plugins in the config.xml by name. If there are testers, I can try to fix it for 18.7 ?

**Comment by beren12** [comment]
No, more simple than that. just a list of non-core plugins that are installed in an xml field. the web UI seems to know already...

**Comment by fichtner** [comment]
It asks the package database, yes. But it would be better to fix the real problem first instead of trying to create a "sync" mechanism that writes all currently known plugins to the config. If we have a install/deinstall trigger that is much easier to implement and avoids "over-syncing" and a separate code spot for it.

**Comment by fichtner** [comment]
Code is in there, but GUI parts need more work.

**Comment by nekoprog** [comment]
> It's probably simpler to register installed plugins in the config.xml by name. If there are testers, I can try to fix it for 18.7 ?

Something like plist can be done? Just a standard flat file with current/previously successful installed plugin name. Then just call the `processPlugin($pkg_name, 'reinstall');` I guess. Not having a creative idea right now. lol

**Comment by fichtner** [comment]
The store is already there, the question is how to use it in the GUI, present reinstall buttons, clear, discard orphaned packages but only when the mirror is up to date because otherwise all plugins look "orphaned".

I'm happy for all help but I am going to be picky here to ensure the feature is as good as it can be when we have it. I don't like to go back and rewrite this again. Sorry in advance. :)

**Comment by nekoprog** [comment]
you got a rough design for that? can show me where it should be done? i would like to help with this under your guidance.

**Comment by AdSchellevis** [comment]
@fichtner how about this?
![image](https://user-images.githubusercontent.com/9783985/74751607-c64bf100-526d-11ea-8aa7-861d07dfe3f1.png)

**Comment by fichtner** [comment]
this is certainly the right direction, but we also need a dismiss button that syncs the current plugin names into the config and we can only install the ones that are really there (do we silently dismiss them or dismiss explicitly?)

also when you change the mirror url and open packages again the missing ones should also be listed if people do offline installs :)

**Comment by AdSchellevis** [comment]
There you go, accept captures currently installed plugins, which looks like the most obvious choice here.
![image](https://user-images.githubusercontent.com/9783985/74814515-bb3da300-52f7-11ea-8b54-f508e1941342.png)


In time we might need to think about a larger overhaul, the volt template file is growing a bit too much for my taste, but certainly not this year :)

**Comment by fichtner** [comment]
some more changes done to streamline it a bit and also display missing plugins that are no longer available (while not making them marked as orphaned)

<img width="1041" alt="Screenshot 2020-02-20 at 8 35 55 PM" src="https://user-images.githubusercontent.com/1915288/74971665-c2140500-5420-11ea-887e-1896f69db7a8.png">

The last bit is moving the action buttons to the dedicated blue upper section and make the page show the actual progress of the reinstall. :)

**Comment by AdSchellevis** [comment]
@fichtner looks good, thanks!
