### ISSUE TITLE
FireHol pfTable list cannot be reloaded

### ISSUE THREAD

**Issue by mimugmail** [opnsense/core#1666]
Hi,

I added FileHol Level1 list to pfTable URL list.
The initial download works but reloading the rules fails with:

06-01-17 10:41:18 [ There were error(s) loading the rules: /tmp/rules.debug:21: cannot define table FireHol: Cannot allocate memory - The line in question reads [21]: table persist file /var/db/aliastables/FireHol.txt]

Where line 21 is the pfTable itself. The FileHol.txt is 
-rw-r-----   1 root  wheel  259319 May 31 15:39 FireHol.txt

Is this too big for a blacklist?

Edit: There's another user around with the same issue: https://forum.opnsense.org/index.php?topic=5275.0

**Comment by AdSchellevis** [comment]
@mimugmail see "Firewall Maximum Table Entries" in system_advanced_firewall.php

**Comment by mimugmail** [comment]
@AdSchellevis Thanks, I'll do some performance tests with and without the list and then close this one.

**Comment by mimugmail** [comment]
Ok, no impact on throughput, nor the CPU (for a 300Mbit test)
