### ISSUE TITLE
DNS port binding killed 

### ISSUE THREAD

**Issue by gregober** [opnsense/core#1669]
We have configured bind and shutdown all instances of unbound and all other internal DNS programs @opnsense. 

BIND is configured to act as  resolver for a local zone and as an authoritative server for our internal networks. BIND is deployed and configured to listen on 2 different local network interfaces. 

It is working "ok" without any problem rndc gives the right feedback and everything is "up and running". But after a while one of the interfaces where BIND is listening is somehow deleted. 

So we end-up with an interface that's not listening on one of the two configured network. 

This is really annoying since we have our phone network configured on this network and that we can no longer use our phone because of this "vanishing interface". 

If we restart bind everything goes back to normal.

**Comment by fichtner** [comment]
Hi Greg,

This is normal if you select specific interfaces / IP addresses to listen to... a better approach is to listen on 0.0.0.0, or is there anything against this approach in your setup?

Otherwise we need to build a small plugin for Bind in order to restart it correctly...


Cheers,
Franco

**Comment by fichtner** [comment]
Just as a follow up we're having the same issue with unbound. You really need a plugin to handle this case, the plugin_configure() facility can deal with this via the 'newwanip' tag.
