### ISSUE TITLE
[Feature] [NTP] Multicast / Broadcast

### ISSUE THREAD

**Issue by MyLive** [opnsense/core#1672]
Hello @ all,

@ the moment, NTP allows only unicast, can this please extend to transmit the Network Time over Multicast / Broadcast ?

This make's the Client config very easy :-), it's only listening on the Multicast Address and do not known the real NTP Server, so i have to change notthing, if the NTP Server is moved to any other :-).

Thanks a lot,
René

**Comment by AdSchellevis** [comment]
timeout
