### ISSUE TITLE
Transparent proxy blocking Google

### ISSUE THREAD

**Issue by kojo1984** [opnsense/core#1675]
Hi,

I have configured OPNSense several times, using official docs.

I have configured Transparent PROXY with SSL inspection, deployed certificate to all PCs.

I have problem that sometimes, for some users, Google pages are blocked (translate.google.com, www.google.ba).

In Proxy log, I found:

2017/06/08 09:55:55 kid1| 	Error negotiating SSL connection on FD 176: (54) Connection reset by peer
2017/06/08 09:55:55 kid1| 	Error negotiating SSL connection on FD 176: error:14076102:SSL routines:SSL23_GET_CLIENT_HELLO:unsupported protocol (1/-1)
2017/06/08 09:55:55 kid1| 	SECURITY ALERT: on URL: translate.google.com:443
2017/06/08 09:55:55 kid1| 	SECURITY ALERT: Host header forgery detected on local=172.217.18.78:443 remote=192.168.1.93:56166 FD 176 flags=33 (local IP does not match any domain IP)
2017/06/08 09:55:55 kid1| 	SECURITY ALERT: on URL: translate.google.com:443
2017/06/08 09:55:55 kid1| 	SECURITY ALERT: Host header forgery detected on local=172.217.18.78:443 remote=192.168.1.93:56165 FD 176 flags=33 (local IP does not match any domain IP)
2017/06/08 09:55:55 kid1| 	SECURITY ALERT: on URL: translate.google.com:443
2017/06/08 09:55:55 kid1| 	SECURITY ALERT: Host header forgery detected on local=172.217.18.78:443 remote=192.168.1.93:56164 FD 176 flags=33 (local IP does not match any domain IP)
2017/06/08 09:55:51 kid1| 	SECURITY ALERT: on URL: translate.google.com:443
2017/06/08 09:55:51 kid1| 	SECURITY ALERT: Host header forgery detected on local=172.217.18.78:443 remote=192.168.1.93:56162 FD 55 flags=33 (local IP does not match any domain IP)
2017/06/08 09:55:51 kid1| 	SECURITY ALERT: on URL: translate.google.com:443
2017/06/08 09:55:51 kid1| 	SECURITY ALERT: Host header forgery detected on local=172.217.18.78:443 remote=192.168.1.93:56161 FD 55 flags=33 (local IP does not match any domain IP)
2017/06/08 09:55:50 kid1| 	Error negotiating SSL connection on FD 55: error:1408A0C1:SSL routines:ssl3_get_client_hello:no shared cipher (1/-1)
2017/06/08 09:55:50 kid1| 	Error negotiating SSL connection on FD 177: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown (1/0)

Maybe not all lines are important, but this happens from time to time and users are killing me...

After few minutes, it starts working normally.

Any help on this one?

**Comment by fabianfrz** [comment]
this are four different issues

* no shared cipher
this probably means that the TLS implementation of your client or the server you are trying to reach is crap. We cannot help you if we don't have more info.

* alert certificate unknown
an untrusted certificate is used. The only thing is to bypass the certificate check - usually a bad idea
If it is your company CA, you will have to add it to the trust store (this is afaik not available in the GUI)

* SECURITY ALERT: Host header forgery detected on local=172.217.18.78:443
A DNS issue that your host and your proxy resolve a domain name to different IPs
http://wiki.squid-cache.org/KnowledgeBase/HostHeaderForgery

* Error negotiating SSL connection on FD 176: error:14076102:SSL routines:SSL23_GET_CLIENT_HELLO:unsupported protocol 
Was that HTTPS or did someone try to abuse the HTTPS port? I would suggest you to check for malware.

* Connection reset by peer
you tried to access a host where no HTTPS port is open or a connection may have timed out.

**Comment by kojo1984** [comment]
Hi,

tnx for fast response.

1. I'm using latest version of GoogleChrome and EDGE when trying this and I'm accessing Google web pages. Only those pages have a problem.
2. I'm using self-signed certificate for MITM (because I use TransparentProxy. I added that certificate to all clients on network.
3. I looked at that article previously, it suggests WPAD config and using GPOs to configure settings, but I must use Transparent Proxy.
My clients are using local AD DNS servers that are using ISPs public DNS as forwarders. OPNSense is using ISP public DNS servers on WAN interface.
Tried using internal domain DNS servers, same error appears.

4. PC fresh installed
5. OK.

I only have problem with Google services and for some reason, problem disappears after few minutes.
Other HTTPS sites are working perfectly.
Also, I added Google domains in SSL Bump and White Lists

**Comment by fabianfrz** [comment]
vivaldi connects to google using
```
The connection to this site is encrypted and authenticated using a strong protocol (TLS 1.2), a strong key exchange (ECDHE_RSA with X25519), and a strong cipher (AES_128_GCM).
```
Firefox uses `TLS_ECDHE_RSA_AES_128_GCM_SHA256`.

The firefox cipher should work just fine but I an not sure if X25519 is supported by OpenSSL.

**Comment by kojo1984** [comment]
Will try with Vivaldi, also...

But, it keeps throwing an error, randomly ... or I just haven't figured the pattern.

**Comment by kojo1984** [comment]
Error still remains, only Google pages are getting blocked, randomly.

After some time, they get working.

**Comment by fabianfrz** [comment]
Can you provide the error message on the client and/or a packet capture?

**Comment by kojo1984** [comment]
I will, as soon as error happens.

**Comment by kojo1984** [comment]
Error from GoogleChrome:

This site can’t provide a secure connection

translate.google.com sent an invalid response.
Try running Windows Network Diagnostics.
ERR_SSL_PROTOCOL_ERROR

**Comment by kojo1984** [comment]
From Firefox:

Secure Connection Failed

An error occurred during a connection to translate.google.com. SSL received a record that exceeded the maximum permissible length. Error code: SSL_ERROR_RX_RECORD_TOO_LONG

    The page you are trying to view cannot be shown because the authenticity of the received data could not be verified.
    Please contact the website owners to inform them of this problem.

**Comment by fabianfrz** [comment]
this sounds like a bug in the proxy - the best thing you can do is filing a bug report to http://bugs.squid-cache.org/index.cgi

@fichtner Please add the upstream tag

**Comment by fichtner** [comment]
@kojo1984 are you using LibreSSL or OpenSSL? please provide your versions from the system widget as a reference. :)

**Comment by kojo1984** [comment]
@fichtner It was a default install of OpnSense no packages added/removed. Is this what you were asking?

![openssl](https://user-images.githubusercontent.com/25300598/27026688-eb92e1b8-4f5e-11e7-9c8c-6923c050b061.PNG)

If yes, OpenSSL :) .

**Comment by fichtner** [comment]
yes, ok, I was just asking to make sure we're not looking at a LibreSSL oddity

**Comment by kojo1984** [comment]
OPNsense1:~ % openssl
OpenSSL> version
OpenSSL 1.0.2k-freebsd  26 Jan 2017
OpenSSL>

**Comment by fichtner** [comment]
no, that's the unused base version ;)

    # /usr/local/bin/openssl version # OpenSSL or LibreSSL from ports
    # /usr/bin/openssl version # FreeBSD bundled OpenSSL base version

**Comment by kojo1984** [comment]
My bad, didn't know that :( ...

But, here's an updated stuff:

OPNsense1:~ % /usr/local/bin/openssl version
OpenSSL 1.0.2l  25 May 2017
OPNsense1:~ %

**Comment by fichtner** [comment]
ok, good. squid released 3.5.26, it'll be in the next update... maybe it's a known issue:

```
	Changes to squid-3.5.26 (01 Jun 2017):
 	
 	       - Bug 4711: SubjectAlternativeNames is missing in some generated certific
 	ates
 	       - Bug 4695: squidpurge: GCC 7 build errors
 	       - Bug 4682: ignoring http_access deny when client-first bumping mode is u
 	sed
 	       - Bug 4682: Fix ssl_bump "bump" action documentation
 	       - Bug 4653: %st lies about tunneled traffic volumes
 	       - Bug 4589: ssl_crtd: returning zero on failure
 	       - Bug 3772: message from FTP server gets mangled
 	       - Bug 3102: FTP directory listing drops fist character of file names
 	       - Add OpenSSL library details to -v output
 	       - ... and some documentatino updates
```

**Comment by kojo1984** [comment]
OK, I'll wait for that. My Squid is 3.5.25.

I'll leave this thread open until then.

**Comment by L1ghtn1ng** [comment]
It will be down to the subject alternative bug as Google recently pushed that out as people are having issues with self signed and had to change them to get them to work in chrome so I would not be surprised if it's that which is fixed in the new release of squid

Sent from phone

________________________________

**Comment by kojo1984** [comment]
OK, I've resolved my issue.

The last thing I've done is that I removed ".google.com" domain from SSL Bump sites.

Now, for the past 6 days, it's working, no users are reporting an issue.

P.S. Should not the SSL Bump enabled sites avoid proxy?

**Comment by fichtner** [comment]
Google may still detect tampering in their server or client Infrastructure. They are very progressive / aggressive so indeed whitelisting google is a good approach. Thanks for checking back.
