### ISSUE TITLE
configuration restore

### ISSUE THREAD

**Issue by pah96** [opnsense/core#1676]
Hello,

I'm using OPNsense since the early days, should be about version 15.1.9.
After a power interrupt i'm not able to restore my config, OPNsense alwas starts up with the default installation. Already changed internal storage (8GB SD-card) and also tried to set up new in manual way (this is what I did not expected having backed up the config) but no config will be saved and device always comes up in default.

Can you please gave me a hint how to get it up with my backed up configuration anyway?

Best regards,
Herbert P.

**Comment by fichtner** [comment]
Hi Herbert,

There's not a lot to go on here. Do you mean default as in factory reset or a "configuration that you configured but which is fixed in time"?

The latter could happen when the disk is permanently in read-only mode, where the system goes into a live mode and wipes the configuration afterwards.

Can you send your output of the following commands?

    # df -h
    # mount

Are there any related error messages we should know about? How does your System: Configuration: History cope with your restore? Does it reset the configuration on top of the restore or does it "forget" the configuration after reboot?


Cheers,
Franco

**Comment by pah96** [comment]
Hi!
Thanks for relpy!

Yesterday I was busy because I had to find a workaround getting internet connectivity anyhow at home so I'll answer your technical questions tomorrow.

So far: yes the system "forgets" any configuration after every reboot. Anyway if configured manually or restored via WebGUI. And it does not depend on size or date. Also tried to recover the manual configuration but didn't work too.

Is there a way to put the configuration directly on it via console or just ssh? I've seen something like /usr/local/etc/config.xml 

Best regards,
Herbert
p.s.: koennen dann auch gerne in deutsch weiter machen :)

**Comment by fichtner** [comment]
Hallo Herbert,

Ist unter /conf/config.xml, aber erstmal schauen was auf der Box los ist. Bräuchte den Output von den beiden Kommandos:

    # df -h
    # mount


Grüsse
Franco

**Comment by pah96** [comment]
Hi Franco,

Alles klar. Liefere ich gerne morgen!

Lg,
herbert

**Comment by pah96** [comment]
Hallo Franco,

Hier nun der neueste Stand der Dinge:

Zum einen ist mir erst jetzt gedaemmert: das Image auf der SD ist ja vielleicht ganz nett aber so ganz ohne dem Install wird es kann es eben nicht funktionieren :-/

Zum anderen bleibt jetzt aber die Frage: warum funktioniert der Install nicht? Weil die Karte nicht gemountet werden kann. Nur weshalb nicht?

[...]
da0 at umass-sim0 bus 0 scbus6 target 0 lun 0
da0: <Multiple Card  Reader 1.00> Removable Direct Access SCSI-4 device
da0: Serial Number 058F63666485
da0: 40.000MB/s transfers
da0: 7519MB (15398912 512 byte sectors: 255H 63S/T 958C)
da0: quirks=0x2<NO_6_BYTE>
Mounting filesystems...
Updating motd:.
No suitable dump device was found.
Bootstrapping config.xml...done.
Bootstrapping openssl.cnf...done.
realpath: /dev/dumpdev: No such file or directory
Dump device does not exist.  Savecore not run.
[...]

Geht auch mit einer anderen Karte nicht. Den kompletten Output siehe Attachement.

[apu_install2.txt](https://github.com/opnsense/core/files/1065808/apu_install2.txt)

Hier auch noch was waehrend eines Install passiert:

[apu_install.txt](https://github.com/opnsense/core/files/1065813/apu_install.txt)

Beim Kopieren des Images hatte ich Probleme bei beiden Karten. Ging nicht auf Anhieb. Musste mehrmals formatieren bis das Kopieren endlich geklappt hatte. Das Ergebnis hat jedenfalls gut ausgesehen, sprich gelesene und geschriebene Byte.

Wird es daran liegen oder koennte doch auch ein HW-Problem bestehen?

Vielen Dank fuer die Unterstuetzung und lg,
herbert

**Comment by pah96** [comment]
Hallo Franco!

Wie schon vermutet kein Problem im Bereich L1-L7 (OSI) sondern schlicht und ergreifend am Layer8 (ICH)! :)

Installation laeuft nun und ich denke der restore wir dann auch wie erwartet funktionieren.

Sorry fuer die Umstaende!

Frage trotzdem: Upgrade von 15.1.9 auf die aktuellste Version ist ratsam oder nur mit Zwischenschritten? Im ersten Schritt will ich einfach nur den Status-Quo wieder herstellen.

Lg,
herbert

**Comment by fichtner** [comment]
Hallo Herbert,

Die notwendigen Zwischenschritte sind automatisch drin. Wenn es aber eine SD-Karte ist würde ich empfehlen direkt von 17.1 anzufangen. Das Image ist verbessert und es sind weniger Schreibzyklen für das Medium. :)

Sollen wir das Ticket schließen?


Grüsse
Franco

**Comment by pah96** [comment]
Hallo Franco,
Ja, gerne! Nur noch eine letzte Frage: funktioniert die Konfig von 15.1.9 eh auch noch mit 17.1?

Danke und lg,
herbert

**Comment by fichtner** [comment]
Hallo Herbert,

Ja, ggf. braucht es etwas Fine-Tuning (Console Neuerungen z.b.), aber booten wird es allemal mit den korrekten Netzwerkeinstellungen.


Grüsse
Franco

**Comment by fabianfrz** [comment]
@fichtner von der 15er Serie wird es noch andere Probleme geben:

Z.B.: Captive Portal wurde ausgetauscht - das heißt hier wird die Konfiguration nicht mehr gehen

**Comment by fichtner** [comment]
stimmt, würde beim sequentiellen update aber auch passieren. die release notes sollten ggf. durchstöbert werden :)

**Comment by pah96** [comment]
Alles klar! Portal hatte ich nicht in Verwendung, aber vielleicht ja jetzt dann.

Danke euch!

Lg,
herbert

**Comment by fichtner** [comment]
kein problem :)
