### ISSUE TITLE
Multi WAN + Captive Portal not working on 17.1.8

### ISSUE THREAD

**Issue by tee4cute** [opnsense/core#1678]
Hi,

**I'm facing the same issue with this thread:**

https://forum.opnsense.org/index.php?topic=3600.0

**This is my system env:**

OPNsense 17.1.8-amd64
FreeBSD 11.0-RELEASE-p10
OpenSSL 1.0.2l 25 May 2017

I upgraded the system firmware to this version 2 days ago and this problem suddenly presented without changing any my old configurations. From the thread I gave the link above, it seems that this bug should has been fixed since OPNSense version 16.7.x?

Could you please test this issue on the same system version given above and confirm/deny that this is a bug on this version or not?

PS. I'm really sorry that I could not remember that what is my system version prior the upgrade. I downloaded the latest OPNSense version provided on the website and set it up about 2 months ago. And, this is my first firmware upgrade.

**Comment by fichtner** [comment]
Please try the "shared forwarding" setting under firewall: settings: advanced.

**Comment by tee4cute** [comment]
Hi fichtner,


Thanks for your quick reply. Enabling **"shared forwarding"** works like a charm!

Sorry for reporting this issue since I didn't know about "shared forwarding" setting.


Cheers.

**Comment by fichtner** [comment]
No worries! :)
