### ISSUE TITLE
X (delete) button in NAT and Rule screens not working properly

### ISSUE THREAD

**Issue by weust1979** [opnsense/core#168]
On both the NAT and Rule screen, the X button at the bottom of the overview is not working.
The X button behind a rule is working as expected.

When selecting one or more rules on the left side, and clicking the X button shows the message if you really want to delete the rules, but when pressing Yes is simply reloads the page without having done anything.

As an extra, there is no big orange Delete button on the Rule page.
The NAT page does show it.

**Comment by AdSchellevis** [comment]
Thanks for posting. It should be fixed with https://github.com/opnsense/core/commit/7bf001c403d98d37f5b13857e786676bdc5afb9b
The large delete button is kind of duplicate, I would rather remove it from the nat page as well (in stead of placing it on the firewall rules page).
