### ISSUE TITLE
Import FreeBSD fixes for Intel Atom Cherry Trail SOCs

### ISSUE THREAD

**Issue by fraenki** [opnsense/core#1680]
I've tried running OPNsense (amd64) on an Intel Atom x5 Z8350 SOC ([UP board](http://up-shop.org/4-up-boards)), but it won't boot.

A workaround is to set the following boot options:

```
set hint.uart.0.flags=0x10
set hint.uart.1.flags=0x10
```

There's already a patch available from FreeBSD:
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=207910

It would be nice to get the fixes ready for OPNsense 17.7.

(The internal eMMC drive is still not being recognized, but I was able to install OPNsense on an USB flash drive instead.)

**Comment by fichtner** [comment]
https://github.com/opnsense/src/commit/0357654fe95

I'll add this with the next kernel update for 17.1.x, likely *not* 17.1.9

**Comment by Halino** [comment]
Whas this fix imported into the 17.7 RC1 ?

**Comment by fichtner** [comment]
17.1.9 :)

**Comment by FlorianHeigl** [comment]
@fraenki did you also set ```hint.uart.1.disabled=1```?
I couldn't ever get it to boot without that.

**Comment by fraenki** [comment]
> did you additionally set hint.uart.1.disabled=1

Yes, I have this setting in my `/boot/loader.conf.local`.

**Comment by jo3rg** [comment]
Seems this issue is still persistent in the latest release: 18.1.9
Breaks after each and every upgrade...

**Comment by fichtner** [comment]
Sure, makes sense since the ticket is still open. ;)

**Comment by fichtner** [comment]
Oh wait it isn’t. I mixed up this with the Apollo Lake ticket. Nevermind.

**Comment by jo3rg** [comment]
I'm confused now. :) 
What can we do to fix this issue sustainable?

**Comment by fichtner** [comment]
@jo3rg hmm, @fraenki asked for a commit to be included that would fix this and it was imported so it was closed. It seems there may be another commit in the wild or a new PCI type not yet recognised by FreeBSD because you have "the same issue" on a different hardware base?

**Comment by jo3rg** [comment]
@fichtner what do you need to identify the exact hardware?

**Comment by fichtner** [comment]
Not sure yet. I’ll be back on Monday to check where this info can be found in your system.

**Comment by fichtner** [comment]
@jo3rg this should help identify it:

    # pciconf -l

**Comment by fichtner** [comment]
PS: I could not find any new UART devices in FreeBSD that would fit your description.

It would be interesting to know what hardware you are using and how "it breaks after each update", because if you use /boot/loader.conf.local it shouldn't. Since 18.1.6 we also have support in system: setting: tunables for this.

**Comment by fraenki** [comment]
(FWIW, this works for me, at least on the hardware listed in first post.)

**Comment by jo3rg** [comment]
@fichtner any feedback on that?
