### ISSUE TITLE
regression firewall refactor

### ISSUE THREAD

**Issue by AdSchellevis** [opnsense/core#1681]
In some situations the new code seems to trigger on the auto-generated "route-to" rules on my vm:

`There were error(s) loading the rules: /tmp/rules.debug:137: no routing address with matching address family found. - The line in question reads [137]: pass out log  route-to ( em1 XXXX ) from {emX} to {!(emX:network)} keep state allow-opts label "let out anything from firewall host itself
`

The needs some more investigation, pulling the virtual plug doesn't seem enough to trigger it.

**Comment by AdSchellevis** [comment]
it's caused by https://github.com/opnsense/core/blob/17.1.8/src/etc/inc/filter.inc#L2446 maybe it's better to ditch the outbound rules completely (https://github.com/opnsense/core/blob/master/src/etc/inc/filter.lib.inc#L367-L382). If the gateway switches, it makes no sense locking it to the previous one.

**Comment by fichtner** [comment]
Exactly one of our talking points, it pins a gateway in the worst possible way where it won't even work with multi-wan for the box's own outgoing traffic

**Comment by AdSchellevis** [comment]
@fichtner I vote for removing the route-to here and trust the routing table or user defined rules to do it's work, what do you think?

**Comment by fichtner** [comment]
yes please
