### ISSUE TITLE
[regression] field "style" / jinja "in" operator not working

### ISSUE THREAD

**Issue by fraenki** [opnsense/core#1682]
The "style" attribute is no longer working, it's not added to the HTML output for unknown reason. I found out that [this piece of code](https://github.com/opnsense/core/blob/8527911968d117de7f610a94951b5126ea5106e9/src/opnsense/mvc/app/views/layout_partials/base_dialog.volt#L100) no longer works:

`{% if style in field %}{{field['style']}}{% endif %}`

The issue is the jinja `in` operator, apparently it stopped working. If I remove the `if style in field` clause the "style" is added properly. (Note that the `in` operator was once working and was [added to avoid crash reports](https://github.com/opnsense/core/commit/88787945d133a821978a5986ccdbc88f1c6a9020#diff-f4be382c8ae4beca50fe657f08bd3c80).)

This breaks [custom styles](https://github.com/opnsense/plugins/blob/7a7df459d54719c617aaf5bffa11688d9daa82db/security/acme-client/src/opnsense/mvc/app/controllers/OPNsense/AcmeClient/forms/dialogValidation.xml#L29) in our plugins, for example the Acme "Validation Methods" form is somewhat broken because the style in "header" fields is ignored:

```
<field>
  <label>HTTP-01</label>
  <type>header</type>
  <style>method_table method_table_http01</style>
</field>
```

**Comment by AdSchellevis** [comment]
@fraenki as far as I could find, we're only using this construction in one Volt template, so it seems easier to replace it with a default here. Although I'm not sure why it stopped working, it doesn't seem important enough to investigate further.

**Comment by fichtner** [comment]
maybe a php stable bump. hard to catch..

**Comment by fraenki** [comment]
Nice solution, thank you :)
