### ISSUE TITLE
Supported cellular modem device fails to connect

### ISSUE THREAD

**Issue by PitchBendStretch** [opnsense/core#1684]
Hello Guys,

this issue is based on the following german thread i posted earlier this week:
https://forum.opnsense.org/index.php?PHPSESSID=vh47q6fo3r910vgnutrd1cm464&topic=5247.0

I bought the **Huawei ME909u-521** LTE cellular modem mPCIe card for my **APU2C4** to use it as my main WAN connection to the internet in combination with my **Telekom SIM** card. 
In https://docs.opnsense.org/manual/mobile_wan.html 
this card got marked as "_supported and tested device_" so i wanted to maked sure and bought one.

As described in the thread i am not able to make it work even after restarting and/or changing the link interfaces for my PPP connection. No matter what combination i try i always get these following error messages:

using **/dev/cuau0** i get: 
MODEM: Fail to open serial port /dev/cuau0 on speed 115200
device is busy

using **/dev/cuau1** i get:
CHAT: The modem is not responding to "AT" at ModemCmd: label

This issue was first discovered on version 17.1 
and there were no solution working even after updating to 17.1.8
Is this a known issue? :-/

Best regards,
Oxy/PitchBendStretch

**Comment by AdSchellevis** [comment]
If I'm reading the docs correctly, the device should be /dev/cuaU0.0 ... but it has been quite some time ago I did setup something similar with a Huawei.

Can you post your settings and the output of the following command?

`ls -asl /dev/cuau*
`

**Comment by PitchBendStretch** [comment]
Hey ad,
thank you very very much for your quick reply. I am confused aswell, since i expected "cuaU0.0" but got "cuau0" and "cuau1"

ls -asl /dev/cuau* gave me the following:
> root@test:~ # ls -asl /dev/cuau*
> 0 crw-rw----  1 uucp  dialer  0x31 Jun 16 17:49 /dev/cuau0
> 0 crw-rw----  1 uucp  dialer  0x32 Jun 16 17:49 /dev/cuau0.init
> 0 crw-rw----  1 uucp  dialer  0x33 Jun 16 17:49 /dev/cuau0.lock
> 0 crw-rw----  1 uucp  dialer  0x37 Jun 16 17:49 /dev/cuau1
> 0 crw-rw----  1 uucp  dialer  0x38 Jun 16 17:49 /dev/cuau1.init
> 0 crw-rw----  1 uucp  dialer  0x39 Jun 16 17:49 /dev/cuau1.lock

i tried again but got the same error:

> Jun 16 18:01:16	ppp: [opt2_link0] MODEM: Fail to open serial port /dev/cuau0 on speed 115200
> Jun 16 18:01:16	ppp: [opt2_link0] can't open /dev/cuau0: Device busy
> Jun 16 18:01:15	ppp: [opt2_link0] Link: reconnection attempt 9
> Jun 16 18:01:13	ppp: [opt2_link0] Link: reconnection attempt 9 in 2 seconds
> Jun 16 18:01:13	ppp: [opt2_link0] LCP: Down event
> Jun 16 18:01:13	ppp: [opt2_link0] Link: DOWN event

Thanks for your help. :)

**Comment by AdSchellevis** [comment]
ok, I just checked a card at our end, it looks like yours has either a wrong firmware or is of the wrong type:

To compare against our card, list usbconfig:
```
root@OPNsense:~ # usbconfig 
ugen0.1: <OHCI root HUB AMD> at usbus0, cfg=0 md=HOST spd=FULL (12Mbps) pwr=SAVE (0mA)
ugen1.1: <EHCI root HUB AMD> at usbus1, cfg=0 md=HOST spd=HIGH (480Mbps) pwr=SAVE (0mA)
ugen2.1: <OHCI root HUB AMD> at usbus2, cfg=0 md=HOST spd=FULL (12Mbps) pwr=SAVE (0mA)
ugen3.1: <EHCI root HUB AMD> at usbus3, cfg=0 md=HOST spd=HIGH (480Mbps) pwr=SAVE (0mA)
ugen4.1: <OHCI root HUB AMD> at usbus4, cfg=0 md=HOST spd=FULL (12Mbps) pwr=SAVE (0mA)
ugen5.1: <EHCI root HUB AMD> at usbus5, cfg=0 md=HOST spd=HIGH (480Mbps) pwr=SAVE (0mA)
ugen3.2: <HUAWEI Mobile HUAWEI Technology> at usbus3, cfg=0 md=HOST spd=HIGH (480Mbps) pwr=ON (500mA)
 
```
 
Then usbconfig the Huawei card:
```
root@OPNsense:~ # usbconfig -d ugen3.2 dump_device_desc
ugen3.2: <HUAWEI Mobile HUAWEI Technology> at usbus3, cfg=0 md=HOST spd=HIGH (480Mbps) pwr=ON (500mA)
 
  bLength = 0x0012 
  bDescriptorType = 0x0001 
  bcdUSB = 0x0200 
  bDeviceClass = 0x0000  <Probed by interface class>
  bDeviceSubClass = 0x0000 
  bDeviceProtocol = 0x0000 
  bMaxPacketSize0 = 0x0040 
  idVendor = 0x12d1 
  idProduct = 0x1573 
  bcdDevice = 0x0228 
  iManufacturer = 0x0001  <HUAWEI Technology>
  iProduct = 0x0002  <HUAWEI Mobile>
  iSerialNumber = 0x0003  <0123456712ABCA17>
  bNumConfigurations = 0x0003 
```

**Comment by PitchBendStretch** [comment]
Hey,

i just did but there is no Huwei card listed.... ?? That is weird.
I get the following:

> root@test:~ # usbconfig
> ugen0.1: <XHCI root HUB 0x1022> at usbus0, cfg=0 md=HOST spd=SUPER (5.0Gbps) pwr=SAVE (0mA)
> ugen1.1: < EHCI root HUB AMD > at usbus1, cfg=0 md=HOST spd=HIGH (480Mbps) pwr=SAVE (0mA)
> ugen1.2: <product 0x7900 vendor 0x0438> at usbus1, cfg=0 md=HOST spd=HIGH (480Mbps) pwr=SAVE (100mA)

is "product 0x7900" my Huawei card?

**Comment by AdSchellevis** [comment]
nope, there doesn't seem to be a card in the list, ugen1.2 is probably something available by default on your system, probably an onboard serial device.
Did you insert the card into the right socket? If I'm not mistaken, there's only one socket connected to the sim.

**Comment by fichtner** [comment]
usb_modeswitch usage necessary here perhaps?

**Comment by PitchBendStretch** [comment]
Sorry for the delay i will write back in about 3-4 hours.

i inserted my SIM card into the only SIM slot available on the APU2C4. 
I then have 2 slots for mPCIe and one for mSata. I will try again to use the mPCIe2 slot instead of mPCIe1, maybe the first one is broken.

i will try out the usb_modeswitch later today.

**Comment by PitchBendStretch** [comment]
Hey,

so i switched the mPCIe cellular Modem card to the second slot but the error continues.
i read about the usb_modeswitch utility. How do i install it on OPNsense?

Best regards

**Comment by TecumsehSamp** [comment]
@PitchBendStretch  What was your solution, we bumped into the same.

**Comment by PitchBendStretch** [comment]
Hi @TecumsehSamp Sadly i wasn't able to fix my problem back then. I had my deadlines and my goal was to present/showcase my Captive Portal solution on OPNsense. I did that by using an old router, flashed the image and made it a wlan Access Point. I was then able to get rid of my cellular modem idea and did not further tried to solve the issue. This problem is one year old. OPNsense and FreeBSD upgraded aswell. Is it still not working with this specific mPCIe modem? It's really a gamble to get the right modem to work with FreeBSD. I had no luck though..... i am sorry that i can't help here.

**Comment by TecumsehSamp** [comment]
Hey, @PitchBendStretch 

Yup, though during the course of trying to figure out I think I may have bricked my modem 😞.

No worries though, really appreciate the response.
