### ISSUE TITLE
Multi-WAN with LTE Modem causes full WAN failure after reboot

### ISSUE THREAD

**Issue by cvbkf** [opnsense/core#1686]
Hi, 

i have the following issue with the current release of opnsense while creating a multi-wan. I configured the Multi-WAN as failover following this guide: [https://docs.opnsense.org/manual/how-tos/ggmultiwan.html](url)

After the setup everything was fine, both WAN interfaces were able to ping internet addresses. then, i remotely rebooted the opnsense, after that it was gone and not reachable from the internet. so i went to the local site and found the internal networks fully operational, but internet access was gone. so i checked the console (vga) and found both wan interfaces without valid IPs. then, i tried rebooting the device, the bootup got stuck at "Configuring WAN" for ~ 2 minutes, and it failed to acquire IPs for both WAN interfaces again. Then, i removed the USB LTE modem and rebooted once again, but to no effort, the WAN still got no IP. Finally i had to restore the configuration prior to the changes for MultiWAN to get the OPNSense online again. 

I couldn't pull logs yet, because it was important to get everything online again (as soon as possible) and now everything is overwritten. But i will try reproducing it when there is no availability needed (second try failed, too, so i am sure that the issue is reproducible). I want to provide you as much details as possible - so what can i do ? Are there any logs beside the logs in /var/log which i should look at ? 

system details: 
SuperMicro A1SRM-2558F with Intel Atom C2558
2x 4GB ECC RAM
2x Samsung 850 Evo SSD
4x Intel GbE LAN 

Interface Assignments
LAN0: igb0->pppoe0 (400/100 VDSL2 via Draytek Vigor 130)
LAN1: igb1, internal LAN, Static IP
LAN2: igb2, unconfigured, but providing four VLANs (static IP)
LAN3: igb3, unused
USB: ue0, LTE Modem ZTE MF-831 running in ethernet mode (DHCP)

**Comment by cvbkf** [comment]
The issue is still present in 17.1.10, so i want to give a small update. 

I tried it with a fresh install, but with the same result. After configuring the LTE modem and the failover groups, everything is fine until reboot, which causes some interface weirdness (WAN interface without IP, some VLANs missing, LTE missing...)

This time, i pulled some logs, which are attached. I configured the LTE Modem around 00:15h, and did the reboot leading to the lockup at 00.39h

any help would be very appreciated. 

[system.txt](https://github.com/opnsense/core/files/1165564/system.txt)
[userlog.txt](https://github.com/opnsense/core/files/1165562/userlog.txt)
[dmesg.today.txt](https://github.com/opnsense/core/files/1165565/dmesg.today.txt)
[gateways.txt](https://github.com/opnsense/core/files/1165561/gateways.txt)
[ppps.txt](https://github.com/opnsense/core/files/1165560/ppps.txt)
[routing.txt](https://github.com/opnsense/core/files/1165563/routing.txt)

**Comment by fraenki** [comment]
@cvbkf I'm unable to download your logfiles due to a "SignatureDoesNotMatch" error; not sure if it's a GitHub issue....

**Comment by AdSchellevis** [comment]
@cvbkf It's probably best to test step by step (with a clean config) and see when it fails, there are some errors in your setup which might not be related but should better be resolved:

`Jul 21 00:40:18 charon configd.py: error generating template OPNsense/Captiveportal : Traceback (most recent call last):   File "/usr/local/opnsense/service/modules/template.py", line 301, in generate     for filename in self._generate(template_name, create_directory):   File "/usr/local/opnsense/service/modules/template.py", line 236, in _generate     raise Exception("%s %s %s" % (module_name, template_filename, render_exception)) Exception: OPNsense/Captiveportal OPNsense/Captiveportal/lighttpd-zone.conf 'collections.OrderedDict object' has no attribute 'interface_hostaddr'
`
Some issue with captive portal, probably an interface without an ip configured.

`Jul 21 00:39:06 charon opnsense: /usr/local/etc/rc.bootup: The command '/usr/sbin/ngctl name 'vlan0': 'igb2_vlan10'' returned exit code '71', the output was 'ngctl: send msg: No such file or directory'
`
Interface rename seems to be failing, the current dev version (which will be in 17.7) changed the assignment.


`Jul 21 00:40:14 charon opnsense: /usr/local/etc/rc.bootup: Static Routes: Gateway IP could not be found for 2.0.0.0/24
`
Strange route.

According to ppps log it was last active Jul 20 23:52:07, so it doesn't look like it tried to setup a new connection today.

In case you want to try the current development version, you could switch using:
`opnsense-update -t opnsense-devel`
But I would really recommend setting up the basic network first, then add the lte modem and if all is functional start adding policy routing / gateway groups.

**Comment by cvbkf** [comment]
@AdSchellevis 

I think the errors you mentioned are caused by the underlying issue, because the interfaces and vlans are not fully up. the firewall gets stuck at "configuring wan" for around a minute at boot, and on the logon screen there are a missing interfaces/vlans. on logon i can't see my guest vlan, so that's why captive portal fails. the rename-error could be the same, a missing interface/vlan. the missing gateway ip is on a missing interface, too.

after boot there are the following entries: 
i noticed, that somehow LAN and WAN are on the wrong interfaces (igb0 instead of igb1), they are switched ?

buggy state:
LAN (igb0) -> v4: 10.0.0.1/22
VLAN1 (igb2_vlan10) -> v4: 10.0.10.1/24
VLAN3 (igb2_vlan30) -> v4: 10.0.36.1/23
WAN (igb1) ->

usual state (after config restore)
 LAN (igb1)      -> v4: 10.0.0.1/22
 MODEM (igb0)    -> v4: 10.0.200.100/24
 VLAN2 (igb2_vlan20) -> v4: 10.0.24.1/21
 VLAN4 (igb2_vlan40) -> v4: 10.0.40.1/24
 VLAN1 (igb2_vlan10) -> v4: 10.0.10.1/24
 VLAN3 (igb2_vlan30) -> v4: 10.0.36.1/23
 WAN (pppoe0)    -> v4/PPPoE: 79.249.145.206/32

side note: the 2.0.0.0/24 is correct, it's an Art-Net (https://en.wikipedia.org/wiki/Art-Net). I hate it, but the lighting technicians are insisting on that ip range, which has to be reachable from LAN. to minimize impact, i used a /24 instead of the full /8 subnet ....

**Comment by fichtner** [comment]
since 17.7.1 interfaces can be locked (right under enable in the settings)... this can be required for usb, lte and zerotier to not force the box to try to recover...
