### ISSUE TITLE
unbound: offer the ability to define forward-zone

### ISSUE THREAD

**Issue by EugenMayer** [opnsense/core#1687]
Having domain-overrides is very nice (stubs) but it also would be practical to be able to define forward-zones to be able to actually resolve internal domains which might also need to recurse to public domain servers for this ( domain overrides ).

Since they are defined more or less identicaly we could just copy/past the inteface + tempalte 

https://www.unbound.net/documentation/unbound.conf.html -> Forward Zone Options

**Comment by ndobbs** [comment]
This feature would be great.

**Comment by landonix** [comment]
I would love this feature.

**Comment by mscott312** [comment]
Good idea, I would love this as well.

**Comment by LilRoro** [comment]
This would prove itself very useful in my world!!

**Comment by curtbraz** [comment]
Yes please!

**Comment by landonix** [comment]
Happy to help with this one. Is this planned for 19.x, currently?

**Comment by fichtner** [comment]
18.7 hopefully, although I've been tied up with release engineering and route handling rework lately

**Comment by mimugmail** [comment]
I can help or take over when nut is finished.

**Comment by fichtner** [comment]
I'll gladly find the time to review. Static code will be a new challenge for you. :)

**Comment by fichtner** [comment]
If we have https://github.com/opnsense/core/issues/2550 can we actually close this?

**Comment by fichtner** [comment]
It's in 18.7.3. I'm closing this...
