### ISSUE TITLE
IPSec tunnels should be disconnected by disabling

### ISSUE THREAD

**Issue by mafn** [opnsense/core#1688]
Version: tested with 17.1.8
If I disable an active IPSec tunnel (and reload the config) the connection is still active and cannot be disconnected in the Status Overview as it does not appear there anymore.

Steps to reproduce:

- create and activate IPSec tunnel
- disable said tunnel

Expected Result:
- Tunnel is not available anymore

What happens:
- Tunnel still active
- Tunnel does not appear in Status Overview

**Comment by AdSchellevis** [comment]
It's a downside on how strongswan handles a reload (https://lists.strongswan.org/pipermail/users/2015-March/007718.html), it keeps all connections active (which is good), but won't kill connections not in the configuration.

In case the user interface doesn't show the connection either after a reload it might be a bug in vici (the strongswan configuration interface) or how the information is processed on our side.

We should try to fix the status page, disconnecting automatically isn't very trivial in the way connections are administered. (you can always force a reload on the service page, which drops all active connections)

**Comment by AdSchellevis** [comment]
https://github.com/opnsense/core/commit/d5c6ce35768c84db35090b86749e74b3570577f3  lists the non routed connections as well. Just for the record, the "non routed" connections won't handle any traffic.
https://github.com/opnsense/core/commit/efd256585a8ce366f436dc9483e499363118f0b0 adds the "routed" keyword to the status when the connection is active/routed.
