### ISSUE TITLE
No indicator in front of NAT when it's disabled

### ISSUE THREAD

**Issue by weust1979** [opnsense/core#169]
When a NAT is disabled, there is no indicator that it is disabled, apart from looking it up in the NAT by editing it.

A Rule at least has a grey icon instead of a coloured one indicating Pass/Block/Reject.

Perhaps a red coloured circle in front of a disables NAT would help indicate it being disabled?

**Comment by AdSchellevis** [comment]
It should have been greyed out. commit https://github.com/opnsense/core/commit/b668fdeb13631826a1721245d3a4a04220289a0b  makes it more visible.
