### ISSUE TITLE
[FR] Implement select_multiple for OptionField

### ISSUE THREAD

**Issue by mimugmail** [opnsense/core#1693]
I discussed with @AdSchellevis the problem in #187 (https://github.com/opnsense/plugins/issues/187) in IRC, seems select_multiple isn't available for the OptionField.

Is it possible to enable it? 

Thanks!

**Comment by AdSchellevis** [comment]
https://github.com/opnsense/core/commit/ac75ef6f10665b495f4d7503dc05dc804d63a061 adds the multi select option

**Comment by mimugmail** [comment]
Thanks @AdSchellevis ! But does this one interfere with #1641 ?
After applying this one I get:

Jun 26 22:07:25 OPNsense configd.py: [bf916b54-8fc0-4921-86e1-d45c0e0ab3b1] Inline action failed with OPNsense/Quagga OPNsense/Quagga/bgpd.conf 'modules.addons.template_helpers.Helpers object' has no attribute 'sortDictList' at Traceback (most recent call last):   File "/usr/local/opnsense/service/modules/processhandler.py", line 505, in execute     return ph_inline_actions.execute(self, inline_act_parameters)   File "/usr/local/opnsense/service/modules/ph_inline_actions.py", line 50, in execute     filenames = tmpl.generate(parameters)   File "/usr/local/opnsense/service/modules/template.py", line 309, in generate     raise render_exception Exception: OPNsense/Quagga OPNsense/Quagga/bgpd.conf 'modules.addons.template_helpers.Helpers object' has no attribute 'sortDictList'

**Comment by AdSchellevis** [comment]
@mimugmail you probably have another issue there, the model/volt templates have no relation with the Jinja templates. Perhaps you forgot to split the entries in the list (multiple items are stored as comma separated values).

**Comment by mimugmail** [comment]
@AdSchellevis Hm, it seems that with changing the models or patching around the system something brokes up. I cloned a fresh image from my master and now it's working as expected, thanks! 👍 

Do you know if this one will go to 17.1.9 or 17.7 since it also affects current stable plugin of quagga?

Put @fichtner in copy :)
