### ISSUE TITLE
Why does everything run as root?

### ISSUE THREAD

**Issue by sachaz** [opnsense/core#1695]
as the subject:
Why does everything run as root? 
Is it scheduled to change ?

**Comment by AdSchellevis** [comment]
Legacy (old pfSense code, although heavily restructured), still needs the webui to run as root, eventually we plan to change that, but given the amount of legacy code still available that will take time.
Our new code detaches operations using our configd daemon.

More info:
https://opnsense.org/about/road-map/
https://docs.opnsense.org/development/architecture.html

**Comment by fichtner** [comment]
The most important point being that until *every single* privileged operation is removed, we cannot disable root in the frontend. All help to separate the calls is thus very welcome. :)

**Comment by sachaz** [comment]
Thanks guys for your answears.
From my point of view it's a very important secury exposure surface.
All users who loves OPNSense should help on this ! (& I promise to try too).

**Comment by ffries** [comment]
i might give a try too, when digging in OPNsense.
This is a real security issue ... considering the many security issues of PHP over time.

**Comment by fichtner** [comment]
It's better to not have this question open, would rather see tickets for subsystem conversion where we can measure progress. :)
