### ISSUE TITLE
Let's Encrypt and Web Proxy (Transparent)

### ISSUE THREAD

**Issue by kojo1984** [opnsense/core#1697]
Hi,

I've configured WebProxy in transparent mode, with SSL Inspection, it's up and running.

In "CA to use:", I've used INTERNAL CA to issue certificates for intercepted HTTPS traffic.

Today, I've installed Let'sEncrypt plugin, issued myself a certificate and when I tried to use  Let's Encrypt Authority X3 (Let's Encrypt) certificate instead of INTERNAL CA, Squid won't start.

I get an errors:
Jun 29 22:17:31 	configd.py: [6af81bc9-8919-4c62-8d85-753717ed14c0] returned exit status 1
Jun 29 22:17:31 	root: /usr/local/etc/rc.d/squid: WARNING: failed to start squid
Jun 29 22:17:31 	squid: No valid signing SSL certificate configured for HTTP_port 127.0.0.1:3128

Is it, maybe, impossible to use Let'sEncrypt in this combination (transparent proxy with SSL inspection)?

**Comment by AdSchellevis** [comment]
Let's encrypt won't supply CA's (public+private), only certificates and public keys for it's own CA's, this can't work.
You can create your own CA using the webgui and trust that certificate in your clients.

**Comment by kojo1984** [comment]
OK, it figures ... I'll keep using my internal CA..


Tnx
