### ISSUE TITLE
no default route when changing to static IPv4 WAN interface and default gateway applied

### ISSUE THREAD

**Issue by RobertVanPapeveld** [opnsense/core#17]
When changing WAN interface to a static IPv4 WAN and apply a default gateway then no default route is created.

**Comment by jschellevis** [comment]
confirmed, the issue appears when there is not default route. In that case a route change -inet cannot work. solution seems to be add a default route when none exists.

**Comment by jschellevis** [comment]
fixed in d2fa9a5
