### ISSUE TITLE
add package for shadowsocks-libev

### ISSUE THREAD

**Issue by picelec** [opnsense/core#1701]
hi,

do you add package for shadowsocks-libev on opnsense ?

it's ported to freebsd
http://pkg.freebsd.org/freebsd:11:x86:64/latest/All/shadowsocks-libev-1.6.4.txz

thanks

**Comment by fichtner** [comment]
sure, will be available in 17.1.10 as a binary package via 6c82189

do you need a package now? freebsd package should work in theory :)

**Comment by picelec** [comment]
Thanks
i don't have tested the freebsd package.
i plan it tomorrow.

**Comment by fichtner** [comment]
@picelec ok, if you have questions just let me know

**Comment by picelec** [comment]
@fichtner 
hi, 
i'm a debian man, i can't find howto install package in freebsd :-(
thanks

**Comment by fichtner** [comment]
Sorry I am too slow today :) for reference:

# pkg add -f http://pkg.freebsd.org/freebsd:11:x86:64/latest/All/shadowsocks-libev-1.6.4.txz
