### ISSUE TITLE
Nummeric Description for Interface causes syntax error and missconfig for firewall rules

### ISSUE THREAD

**Issue by thepill** [opnsense/core#1702]
### Description
Setting the description of an arbitary interface to a nummeric value, causes the firewall rules to be not applied any more.

### Error:

`opnsense: /usr/local/etc/rc.filter_configure: New alert found: There were error(s) loading the rules: /tmp/rules.debug:9: syntax error - The line in question reads [9]: 1234 = "{ em1 }"`

### Steps to reproduce:

1. Go to `your-opnsense-ip/interfaces.php?if=interface` (replace interface with your interface)
2. Change the description of a arbitary interface to `1234`
3. Save the changes
4. Look at the error message

### Versions:

OPNsense 17.1.8-amd64
FreeBSD 11.0-RELEASE-p10
OpenSSL 1.0.2l 25 May 2017

**Comment by fichtner** [comment]
thanks for your report... unfortunately, we will have to prevent numbers from being accepted as this is a problem inside pf where macro names have such restrictions

**Comment by AdSchellevis** [comment]
Eventually the macro's will go away, for the filter rules in dev their already unused, unfortunately we still have to refactor the nat rules.

**Comment by fichtner** [comment]
@AdSchellevis reassign to you?

**Comment by thepill** [comment]
IMHO for the mean time it should be mentioned at the input field or checked when saving

**Comment by fichtner** [comment]
True, the "rules" are defined here: https://www.freebsd.org/cgi/man.cgi?query=pf.conf&sektion=5#MACROS

> Macros can	be defined that	will later be expanded in context.  Macro
> names must	start with a letter, and may contain letters, digits and
>  underscores.  Macro names may not be reserved words (for example pass,
>  in, out).

**Comment by AdSchellevis** [comment]
@fichtner I don't know if the Macro's are easy to identify in the old code, if so we could also opt for using the technical name in the meantime (opt1,lan,wan,..)... but adding a validation is also fine by me.

**Comment by fichtner** [comment]
technical name and/or global prefix is ok even "_" as prefix would work

**Comment by AdSchellevis** [comment]
@fichtner this https://github.com/opnsense/core/commit/e5711dfb25f0b909d3663ee5834168bbbfb3ca40 should do the trick on dev.

**Comment by fichtner** [comment]
interface names were used as aliases but are not validated. unfortunately, they are not full aliases, things like IPv6 could be valid names but are prohibited by the validation. The former fix by @AdSchellevis solves this issue by allowing more arbitrary description names in 17.7, so I am closing this.
