### ISSUE TITLE
Freeradius

### ISSUE THREAD

**Issue by thomasnilsen** [opnsense/core#1704]
Hi,

I have found some forum posts from 2015 talking about success with freeradius3, but it does not seem to be in the repo. Any update on this?

If someone could guide me along how to get this installed I'm interrested in doing some work on a new plugin for a web-interface and some extras to build a lightweight tool for administrating it. My goal is to get dot1x working on my switches and using this for securing access to ports. A lightweight "packetfence" for opnsense.

regards
Thomas

**Comment by fichtner** [comment]
Hi Thomas,

The package has been there a long time, no?

    # pkg install freeradius3

There is a test plugin coming in 17.1.10 with support for a limited scope for GUI setup:

https://github.com/opnsense/plugins/commit/1391330b671e5b283d6984a03acb2a3c5de0b4b4


Cheers,
Franco

**Comment by thomasnilsen** [comment]
Ahh. Great!

Just confirmed it's there.. 👍 

I'll take a look at that plugin to get me going!

Thanks @fichtner 🥇
