### ISSUE TITLE
firmware: GUI upgrades to 17.7

### ISSUE THREAD

**Issue by fichtner** [opnsense/core#1707]
* ~~The #message dialog should be a modal~~
* ~~Add a second button to be able to upgrade to a new major version if available, prompting the reboot dialog~~
* ~~Add major upgrade glue to firmware backend script~~
* ~~Tweak the buttons of the EoL and reboot modals indicating a primary (critical actions)~~
* ~~Make the EoL message trigger through an extra dialog, clicking through it is too easy.~~
* Improve the reboot message if we are in the major upgrade case.

I think that's all :)

**Comment by fichtner** [comment]
@AdSchellevis @jschellevis please take a look, this is my proposal for 17.1 -> 17.7 -- feedback welcome :)

**Comment by fabianfrz** [comment]
@fichtner this requires a template refresh in translation. It will be probably too late.

**Comment by fichtner** [comment]
Not a big worry. We aim for stability in 18.1 here. New features are new. Also, some strings were never translated before.

**Comment by AdSchellevis** [comment]
@fichtner text looks good to me, thanks!

**Comment by fichtner** [comment]
There will be more tweaks, but this a full working state. Maybe I can bring in the changelog here too. Thanks for checking guys 👍
