### ISSUE TITLE
Long delay in boot when FQDN in alias and WAN down

### ISSUE THREAD

**Issue by tskarman** [opnsense/core#1708]
Just an observation that makes me hesitant to use FQDNs in firewall aliases:

When a FQDN is specified in any firewall alias and no DNS can be reached to resolve those FQDNs at the time of booting, the system will hang for a considerable time before giving up resolving the FQDNs and continue booting.

For me that happened when all  WAN connections were down.

I suggest adding an aggressive time-out for boot-time resolving in the context of firewall aliases.

Side note: This happens even for aliases that are not in use (which I think is normal, but I want to mention it).

**Comment by AdSchellevis** [comment]
The alias handling should be detached, we can't solve this at the moment with the way things work now. For some more explanation see https://github.com/opnsense/core/issues/1703

**Comment by fichtner** [comment]
Work being done in #1971 as we speak.
