### ISSUE TITLE
Deleting of alias is possible if still in use by an outbound nat rule

### ISSUE THREAD

**Issue by sjorge** [opnsense/core#1711]
While cleaning up some rules and aliases I discovered I can delete an alias if it is only used for outbound nat.

If the alias is used in a rule for example it will not let me delete it.
After deleting the alias that was only used for outbound nat the ruleset complain it could not use dns to resolve 'myaliasname'.

**Comment by fichtner** [comment]
@AdSchellevis would you take a look, you know both subsystems better...

**Comment by AdSchellevis** [comment]
@fichtner the ui part of the outbound rules probably has more issues too, as soon as I have some time available after the cleanup of the rule engine, I will take a look at this one.

**Comment by fichtner** [comment]
thanks, feel free to move to 18.7 if need be, I'm just trying to clear out undoable items for 18.1
