### ISSUE TITLE
 GPS Initialization seems not to work for ublox usb serial GPS

### ISSUE THREAD

**Issue by sjorge** [opnsense/core#1712]
Looks like the field does nothing, I tested my commands and they work fine when sending them manually.

```
$PUBX,40,GGA,1,1,1,1,0,0*5A
$PUBX,40,GLL,0,0,0,0,0,0*5C
$PUBX,40,GSA,0,0,0,0,0,0*4E
$PUBX,40,GSV,0,0,0,0,0,0*59
$PUBX,40,RMC,1,1,1,1,0,0*47
$PUBX,40,VTG,0,0,0,0,0,0*5E
$PUBX,40,GRS,0,0,0,0,0,0*5D
$PUBX,40,GST,0,0,0,0,0,0*5B
$PUBX,40,ZDA,1,1,1,1,0,0*44
$PUBX,40,GBS,0,0,0,0,0,0*4D
$PUBX,40,DTM,0,0,0,0,0,0*46
$PUBX,41,1,0007,0003,9600,0*10
```
Tweaked defaults as some of them are not supported by my unit but all of the above gets set if done manually.

```
cat gpsinit | cu -s 9600 -l /dev/cuaU0
```

Sending junk actually gets an error that the unit does not nderstand it but the above stuff all worked as I was left with just GGA ZDA and RMC as expected!

**Comment by sjorge** [comment]
Also 9600 is the speed for my unit, so I set the speed accordingly and also updated the speed mode change to reflect 9600 instead of 4800.

**Comment by fichtner** [comment]
@sjorge I'm not following here, what do we need to do?

**Comment by sjorge** [comment]
Under the NTPd configuration is a field to entered some data that needs to be send to the gps to initialize it.

Those commands do not get sent. Sending them manually works fine.

So some code may be broken.

(On my phone now, but I can send a screenshot later)

~ sjorge

**Comment by fichtner** [comment]
Thanks, I'll take a look :)

**Comment by sjorge** [comment]
![screenshot](http://i.imgur.com/WezV6Zl.png)

As promised, here is the screenshot. I'm talking about the field you see at the very bottom.
The default value for those is different for each type of GPS. I slightly edited the default for U-Blox.

Like mentioned above the command set works fine if I manually send them (cat a file to cu), however this must be done on every system boot/reboot so it would be great if it just works via the field in the WebUI.

**Comment by sjorge** [comment]
Speaking of which, PPS support seems busted unless I set

```hw.usb.ucom.pps_mode``` to either 1 or 2, depends on the GPS, mine is 2.

This took a very long time to figure out, reference: http://gsp.com/cgi-bin/man.cgi?section=4&topic=ucom#3

**Comment by fichtner** [comment]
Timing this out.
