### ISSUE TITLE
[FR] IPSEC: Allow multiple P1's when remote gateway is 0.0.0.0

### ISSUE THREAD

**Issue by mimugmail** [opnsense/core#1714]
Hi,

I'm trying to replace a huge hub and spoke network based on Cisco, IKEv2, endpoints with dynamic IPs.
With Cisco I create a dynamic crypto map and then multiple connections differentiated by FQDN.

Within OPN I can do this when remote gateway is set to 0.0.0.0 and the via the FQDN the correct config is chosen. The problem I have is, that when I duplicate P1, edit the FQDN to a different type I'm getting an error that the remote IP is already in used:

https://github.com/opnsense/core/blob/master/src/www/vpn_ipsec_phase1.php#L235

Is there a way to extend this check with some !isset remoteip 0.0.0.0?

I duplicated the conn  /usr/local/etc/ipsec.conf and restarted ipsec by hand. It works great so far:

```
conn viaUI
  aggressive = no
  fragmentation = yes
  keyexchange = ikev2
  mobike = yes
  reauth = yes
  rekey = yes
  forceencaps = no
  installpolicy = yes
  type = tunnel
  dpdaction = none
  left = IP
  right = 0.0.0.0
  leftid = IP
  ikelifetime = 28800s
  lifetime = 28800s
  ike = aes256-sha256-modp2048!
  leftauth = psk
  rightauth = psk
  rightid = Location1
  rightsubnet = 172.21.29.0/24
  leftsubnet = 0.0.0.0/0
  esp = aes256-sha1,aes256-sha256,aes192-sha1,aes192-sha256,aes128-sha1,aes128-sha256!
  auto = add

conn COPIED
  aggressive = no
  fragmentation = yes
  keyexchange = ikev2
  mobike = yes
  reauth = yes
  rekey = yes
  forceencaps = no
  installpolicy = yes
  type = tunnel
  dpdaction = none
  left = IP
  right = 0.0.0.0
  leftid = IP
  ikelifetime = 28800s
  lifetime = 28800s
  ike = aes256-sha256-modp2048!
  leftauth = psk
  rightauth = psk
  rightid = Location2
  rightsubnet = 172.21.30.0/24
  leftsubnet = 0.0.0.0/0
  esp = aes256-sha1,aes256-sha256,aes192-sha1,aes192-sha256,aes128-sha1,aes128-sha256!
  auto = add
```

**Comment by fichtner** [comment]
I think this check dates back to IKEv1, it should not apply to IKEv2?

**Comment by fichtner** [comment]
hrm, can you try this as multi-phase 2, but on phase 1 set: Tunnelisolation

**Comment by mimugmail** [comment]
Tunnelisolation would work, but you need to separate the conf in P1 with a unique identifier. Otherwise every spoke must have the same PSK (like it was with IKEv1)

With this approach you can set a different PSK for every connection

**Comment by fichtner** [comment]
I was just trying to get out of the work... ;)

I think we should only reject if this is IKEv1.

**Comment by mimugmail** [comment]
The trick here is when you have 0.0.0.0 as remote gateway you can have multiple backup lines with a tracking setup. In my lab here I have a leased line with static IP, a ADSL with dynamic IP and a LTE fallback. So no matter when leased and ADSL fails it switches to LTE and you have around 10 pings lost (already tested here with cheap cisco spokes)

**Comment by mimugmail** [comment]
@fichtner Thanks! Really, this would enable OPN to do real enterprise VPN. I already run setups like this with Cisco ASA, 100 site-2-sites and automatic failovers.

**Comment by fichtner** [comment]
# opnsense-patch 738f998

**Comment by mimugmail** [comment]
Wonderful!

![image](https://user-images.githubusercontent.com/20438689/28123403-26c50ff2-6721-11e7-849a-640bc8bb5236.png)


That's why I love this project so much 👍

**Comment by fichtner** [comment]
splendid, thanks for pushing forward! :)

**Comment by QuadPiece** [comment]
Thank you for implementing this feature. I just had a need for the same thing when moving from a Watchguard firewall.

However, I could only find this info by Googling my way to this GitHub issue. Could this perhaps be documented somewhere in the user interface?

![vcxsrv_2019-03-04_14-44-54](https://user-images.githubusercontent.com/6379091/53737353-96ed7a00-3e8c-11e9-8962-d374ba4e8034.png)

For reference, here's a screenshot of the IKEv2 remote gateway setting from a Watchguard firewall:

![pm_fb_2019-03-04_14-43-58](https://user-images.githubusercontent.com/6379091/53737390-b08ec180-3e8c-11e9-8fc8-2cae04a66874.png)

**Comment by brandlit** [comment]
Is it possible that the feature will be implemented for IKEv1 as well?
