### ISSUE TITLE
BUG: System crashes when editing LAGG in Interfaces - Other types

### ISSUE THREAD

**Issue by mimugmail** [opnsense/core#1715]
I currently hunting this bug/phenomenon: https://forum.opnsense.org/index.php?topic=5412.15

Now I've found a reproduceable bug:

When adding a LAGG with Interfaces - Other types - LAGG, chosing interfaces and method and Save, everything is OK. But when you go back, add a description and Save again the system crashes.

I seems it doesn't recognize this as a edit and try to add it again. 

Heres the picture of the dump:

![image](https://user-images.githubusercontent.com/20438689/28122009-3ddee04a-671d-11e7-9f17-9607149b4a0e.png)

**Comment by fichtner** [comment]
can you "bt" this for me?

**Comment by fichtner** [comment]
I think it's this one, there is a fix available.

https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=218886

**Comment by mimugmail** [comment]
What means "bt"?

**Comment by fichtner** [comment]
type "bt" to generate the stack trace

**Comment by mimugmail** [comment]
Ah ok, so you don't need it anymore since it's a known issue ..

**Comment by fichtner** [comment]
I would like to see the stack trace to be sure. But we can try a kernel as soon as 17.7-RC1 is out the door (Friday)

**Comment by fichtner** [comment]
I couldn't wait. :)

    # opnsense-update -kr 17.1.9-lagg
    # /usr/local/etc/rc.reboot

**Comment by fichtner** [comment]
This kernel patch. https://github.com/opnsense/src/commit/391965bde38f83bb6f25c9f8fe18f2caccf712b0

**Comment by mimugmail** [comment]
Thanks! Ok, I'll dig further regarding the VLAN in LAGG in CARP issue :)

**Comment by fichtner** [comment]
I think this was confirmed by @mimugmail if not please reopen
