### ISSUE TITLE
opnsense 17.1.9 dnsmasq crash 

### ISSUE THREAD

**Issue by zjzxj** [opnsense/core#1716]
I have upgraded to 17.1.9, after the upgrade dnsmasq repeatedly automatically stop, every few hours or day, will automatically stop

**Comment by fichtner** [comment]
We need your full version now as printed in the dashbaord, as well as a dnsmasq log snippet and which version you upgraded from...

In 17.1.9 dnsmasq was bumped to version 2.77, let's start with using 2.76 instead:

    # opnsense-revert -r 17.1.8 dnsmasq

**Comment by zjzxj** [comment]
Thank you for reply

**Comment by zjzxj** [comment]
system logs show:

**Comment by zjzxj** [comment]
Upgrade to 17.7，dnsmasq crash again，
I cannot use dnsmasq 2.76
opnsense-revert -r 17.1.8 dnsmasq
Fetching dnsmasq.txz failed

**Comment by fichtner** [comment]
when you upgrade to 17.7, you can't install older packages for 17.1 anymore. And since we only keep 3 versions,that is 17.7, 17.1.11 and 1.7.10 now.

there is virtually no info about the crash other than the segfault itself, which, by your tiniest indication seems to be fixed by using 2.76?

If so, it would be nice to know. ;)

**Comment by fichtner** [comment]
PS: you will have to find out why your traffic / your setup crashes 2.77, compile a useful report we can give to dnsmasq or sidestep the issue by using unbound DNS resolver.

**Comment by zjzxj** [comment]
Yes, I fixed it by using 2.76,but now ,can`t downgrade 2.76

**Comment by fichtner** [comment]
you should have said that fixes it, you can always lock the package to prevent the package from updating :)

**Comment by fichtner** [comment]
what architecture/crypto combo are you using? e.g. amd64/OpenSSL

**Comment by zjzxj** [comment]
amd64/OpenSSL

**Comment by fichtner** [comment]
thanks, here's the package...

# pkg add -f https://pkg.opnsense.org/snapshots/dnsmasq-2.76,1.txz

**Comment by zjzxj** [comment]
I have locked the package in 17.1,but upgrade to 17.7 ,it upgrade Automatically

**Comment by fichtner** [comment]
right, sorry, a cautionary tale from a bad 17.1 upgrade made us unlock all packages to be able to upgrade cleanly.

**Comment by zjzxj** [comment]
Thanks a lot ,returned to 2.76
pkg add -f https://pkg.opnsense.org/snapshots/dnsmasq-2.76,1.txz

**Comment by fichtner** [comment]
so there is some problem in 2.77: http://www.thekelleys.org.uk/dnsmasq/CHANGELOG

do you have any idea which it could be? does it crash instantly or after a while?

**Comment by zjzxj** [comment]
I have looked at changelog and may be related to the following changes:
Fix logic error in Linux netlink code. 

Handle binding upstream servers to an interface (--server=1.2.3.4@eth0) when the named interface is destroyed and recreated in the kernel.

Make --localise-queries apply to names from --interface-name.

Improve logging of upstream servers when there are a lot of "local addresses only" entries.

Make --rev-server for an RFC1918 subnet work even in the  presence of the --bogus-priv flag

Because in the production environment, so can not do more testing

**Comment by fichtner** [comment]
Timeout.
