### ISSUE TITLE
[FR] Integrate nDPI with IPFW (probably as a plugin)?

### ISSUE THREAD

**Issue by mimugmail** [opnsense/core#1717]
Hi,

I stumbled upon this one ...

https://github.com/ntop/nDPI/issues/300

... where a BSD user was able to filter with nDPI applications like facebook. 
After a quick research there was a similiar issue open: #1397 

I'm not really a BSD pro, nor really into OPN where it does PF or IPFW, or mix it up, but I could imagine to to build something which works besides the basic firewall rules. And if it's implemented as a plugin there should not be much impact with main development, perhaps we could build a base for further development?

I saw a npdi package in the ports on github, but nothing related to ipfw-classifyd. Is this outdated or a replacement for it around? 

What do you think?

**Comment by fichtner** [comment]
Sadly, this is not about ipfw, it is about ipfw-classifyd, a very ancient application filtering daemon with poor performance and no maintenance for years. It was removed from OPNsense in 2015, removed from pfSense in 2016.

**Comment by mimugmail** [comment]
So there's no hook around for integrating it to ipfw?

**Comment by fichtner** [comment]
there is, it can be done like relayd or squid, but essentially you need to write a daemon with ndpi, add rules configuration, etc. And then the tricky part is to be able to do something useful with the application classification, namely blocking *and* shaping.

**Comment by mimugmail** [comment]
Seems there's a guy around with a similar idea:

https://redmine.openinfosecfoundation.org/issues/511

I'll close this one for now but keep tracking :)

Thanks!

**Comment by fichtner** [comment]
Suricata is nice, but it can't shape. Ideally, writing this isn't the issue. But nobody is doing it OpenSource because everybody wants to make money off of it.

See Slide 4 of this grumpy guy from 2014 http://operatingsystems.io/slides/userland_networking.pdf

**Comment by mimugmail** [comment]
@fichtner Snort with OpenAppID? I know, also not working with the shaper, but a good choice for blocking access to specific sites or micro apps. 

I read the #1649 but are you all against snort?

**Comment by fichtner** [comment]
With snort on FreeBSD we have the problem of not having a real inline mode, only lazy IP blocking destinations. AppID in Snort has the same problem, shaping is not applicable here. :/

**Comment by mimugmail** [comment]
https://github.com/pmacct/pmacct/blob/master/QUICKSTART#L776

It's only classification, but a quite good start to visualize. 
Do you streamline this version to the ports or will we have to wait for FreeBSD? 

P.S. very low prio :)
