### ISSUE TITLE
IPv6 support for OpenVPN (now that we are on 2.4)

### ISSUE THREAD

**Issue by sjorge** [opnsense/core#1721]
There are a few basic things needed for IPv6 support.

If 'Redirect Gateway' and not 'Disable IPv6'
add 'push "redirect-gateway def1 ipv6'
elif 'Redirect Gateway'
add 'push "redirect-gateway def1'
end

DNS and NTP servers should be address type aware, if addr is IPv6
use DNS6 instead of DNS as dhcp-iption, same for NTP use NTP6 instead of NTP

Also the compression field needs updating, the new parameter is called compress and it takes off, lzo and lz4. I'm getting a small compression ratio increase with lz4.

- [ ] drop tun-ipv6 and 'push "tun-ipv6"' as they are now implied
- [ ] redirect gateway
- [ ] DNS
- [ ] NTP
- [ ] lz4 compression

**Comment by shonjir** [comment]
While adding options, the following would be even more awesome.

lz4-v2 compression support
push compression option to client checkbox
ncp-ciphers config support (encryption cipher negotiation)

**Comment by fichtner** [comment]
A couple of basic tweaks went into OpenVPN setup that ensure "any" interface selection by default since interface binding would automatically prevent IPv6. Now we only add more usefulness to IPv6 with the remaining required options.

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/core/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
