### ISSUE TITLE
lighttpd / harden ciphers

### ISSUE THREAD

**Issue by AdSchellevis** [opnsense/core#1722]
Maybe we should harden the default ciphers for lighttpd further in the road to 18.1, as discussed here https://github.com/opnsense/core/commit/d2ab500ac649497eaf004d3d2fb44b82be14f825 

To sum things up, lighttpd refers to https://cipherli.st/ for an advised list, @fabianfrz suggested to look at https://mozilla.github.io/server-side-tls/ssl-config-generator/?server=lighttpd-1.4.37&openssl=1.0.1e&hsts=yes&profile=modern 

Before we're actually going to radically change our defaults it might be a good idea to open an issue and discuss.

**Comment by fichtner** [comment]
@AdSchellevis for 18.7 ?

**Comment by AdSchellevis** [comment]
@fichtner I kind of opened the issue for a discussion, but hardening our standards in 18.7 sounds good to me. Shall I fix this? or are you planning to do so?

**Comment by fichtner** [comment]
Please do it, I just wanted to prod here. :)
