### ISSUE TITLE
default gw not set after wan ip change

### ISSUE THREAD

**Issue by dhia-eddine** [opnsense/core#1723]
- from command line, changed ip and upstream_gw_ip on wan interface, but default route to upstream_gw_ip is not set even after reboot
- in system-->gateways there was both the old (marked as default) and new upstream_gw

- new upstream_gw_ip is pingable from gw
- further more, it seems that default gw is not set at all ( not set to old upstream_gw ) because 
route show 8.8.8.8 gives: no route to host
- when the old upstream_gw is deleted the default route is set correctly
- first noticed on opnsense version 17.1.4, after upgrade to 17.1.9 didn't tested ip reassignment from cmdline but default gw is not set at boot

**Comment by AdSchellevis** [comment]
timeout
