### ISSUE TITLE
17.1.9 unbound forware reverse lookup (bug?)

### ISSUE THREAD

**Issue by chrisMa68** [opnsense/core#1725]
Hello,
i used unbound for a internal DNS. The internal Domain for my Network is .nodomain . All queries for this Domain will be forwarded to an other internal DNS-Server.  So far everything works.

But i need to forward Reverse Lookups for the internal Domain to an other Server. In the GUI isn't such option.

So i put under:
Services: Unbound DNS: General Custom options this:
Quote

    server:
            local-zone: "168.192.in-addr.arpa."  nodefault
    stub-zone:
            name: "168.192.in-addr.arpa."
            stub-addr: 192.168.2.50

Now the reserve lookups work. Later i try it again an i got:
 
Quote

    dig -x 192.168.2.198             

    ; <<>> DiG 9.9.5-9+deb8u11-Debian <<>> -x 192.168.2.198
    ;; global options: +cmd
    ;; Got answer:
    ;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 41408
    ;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

    ;; OPT PSEUDOSECTION:
    ; EDNS: version: 0, flags:; udp: 4096
    ;; QUESTION SECTION:
    ;198.2.168.192.in-addr.arpa.   IN   PTR

    ;; AUTHORITY SECTION:
    168.192.in-addr.arpa.   3580   IN   SOA   prisoner.iana.org. hostmaster.root-servers.org. 1 604800 60 604800 604800

    ;; Query time: 0 msec
    ;; SERVER: 192.168.2.188#53(192.168.2.188)
    ;; WHEN: Thu Jul 13 12:32:00 CEST 2017
    ;; MSG SIZE  rcvd: 132

Than i restart the unbound service, and it works for a short time.

Has anyone on Idea what is wrong?  

I had copy the unbound Configuration to a local Debian System and it Works fine. So I think it is maybe a bug.

**Comment by AdSchellevis** [comment]
timeout
