### ISSUE TITLE
Problem with line endings when entering OpenVPN TLS authentication key

### ISSUE THREAD

**Issue by ldldr** [opnsense/core#1727]
When entering the key for OpenVPN TLS authentication I get issues when the browser sends strings with CRLF, e. g. Chromium on Windows. The additional '\r' end up in /var/etc/openvpn/server1.tls-auth. This caused problems with openvpn. Here is a possible fix that resolves the problem for me:
```
--- /usr/local/www/vpn_openvpn_server.php.orig  2017-07-03 01:53:25.000000000 +0200
+++ /usr/local/www/vpn_openvpn_server.php       2017-07-14 10:04:17.803586000 +0200
@@ -375,7 +375,7 @@
                     if (!empty($pconfig['autotls_enable'])) {
                         $pconfig['tls'] = openvpn_create_key();
                     }
-                    $server['tls'] = base64_encode($pconfig['tls']);
+                    $server['tls'] = base64_encode(str_replace("\r\n", "\n", $pconfig['tls']));
                 }
                 foreach (array("caref","crlref",
                       "certref","dh_length","cert_depth") as $cpKey) {
```

**Comment by fichtner** [comment]
This looks familiar. We should, however, fix that on the backend, not frontend.

**Comment by fichtner** [comment]
I think it's openvpn_add_keyfile() in /usr/local/etc/inc/plugins.inc.d/openvpn.inc -- can you confirm?

**Comment by ldldr** [comment]
Yes, looks like this works:
```
--- /usr/local/etc/inc/plugins.inc.d/openvpn.inc.orig   2017-07-19 11:58:36.999939000 +0200
+++ /usr/local/etc/inc/plugins.inc.d/openvpn.inc        2017-07-19 11:55:45.759185000 +0200
@@ -470,7 +470,7 @@
 {
     $fpath = "/var/etc/openvpn/{$mode_id}.{$directive}";
     openvpn_create_dirs();
-    file_put_contents($fpath, base64_decode($data));
+    file_put_contents($fpath, str_replace("\r\n", "\n", base64_decode($data)));
     //chown($fpath, 'nobody');
     //chgrp($fpath, 'nobody');
     @chmod($fpath, 0600);
```
But this means that the CRLFs are stored in /conf/config.xml. Not sure if this can cause other problems. For example editing again from a non-CRLF system.

**Comment by fichtner** [comment]
Nice, thanks! I don't think there will be problems that weren't already there. CC'ing @AdSchellevis to be sure.


Cheers,
Franco

**Comment by AdSchellevis** [comment]
@fichtner It's certainly better then it was, but  maybe it would be better to remove \r, so that a <CR> only won't run into similar issues (although I think only classic Mac systems use that).

**Comment by fichtner** [comment]
@AdSchellevis Alright, proposed patch removes "\r", then "\n\n" -> "\n" like web GUI code.

@ldldr following command sequence removes all local changes from the webgui and applies the patch directly from github:

    # opnsense-revert opnsense
    # opnsense-patch 36f0ff5

Cheers,
Franco

**Comment by ldldr** [comment]
@fichtner Thanks!

**Comment by fichtner** [comment]
@ldldr sure, please close if ok. I will do the backports then :)
