### ISSUE TITLE
Feature Request: Support VXLAN VTEP Interfaces in GUI

### ISSUE THREAD

**Issue by cultcom** [opnsense/core#1729]
This would be a great improvement for future use to have a way to tunnel L2 segments to a central firewall instance.

**Comment by mimugmail** [comment]
I was able to create a vxlan interface and build a tunnel via CLI.

The problem is when you assign the new vxlan interface and the device reboots your WAN if is gone, or probably mixed up. 

But in theory it's already supported (not via gui)

**Comment by obrienmd** [comment]
+1 on having this in the GUI, would be extremely useful!

**Comment by 3XTron** [comment]
Please add in next release a GUI support for VXLAN.

**Comment by fichtner** [comment]
Please help with the integration. :)

**Comment by mimugmail** [comment]
I started a first approach some weeks ago, just check my repo, but it's far from working :)

**Comment by AdSchellevis** [comment]
Timeout, nobody seems to be working on it, vxlan support in FreeBSD doesn't seem to be feature complete either (https://wiki.freebsd.org/vxlan), no IPv6 for example.
