### ISSUE TITLE
[Feature Request] User annotations

### ISSUE THREAD

**Issue by lattera** [opnsense/core#1731]
It would be great if I could record at a minimum a given user's email address. Or even attach notes to their account. Notes would allow me to record an audit trail for that user.

**Comment by fichtner** [comment]
we can do both email and comment field?

**Comment by lattera** [comment]
Perfect! Thanks!

**Comment by fichtner** [comment]
the email doesn't validate, I don't think that causes a problem. we can always add it if it does.
