### ISSUE TITLE
PHP 7.1 vs. auto-vivification fail in static PHP

### ISSUE THREAD

**Issue by fichtner** [opnsense/core#1733]
Adding a client works fine, deleting the last client ends up with...

```
Warning: Illegal string offset 'openvpn-client' in /usr/local/www/vpn_openvpn_client.php on line 36
Warning: Illegal string offset 'openvpn-client' in /usr/local/www/vpn_openvpn_client.php on line 39
Fatal error: Uncaught Error: Cannot create references to/from string offsets in /usr/local/www/vpn_openvpn_client.php:39 Stack trace: #0 {main} thrown in /usr/local/www/vpn_openvpn_client.php on line 39
```

I consider the inherited config handling a bug that finally exploded. This needs much QA before we can go to PHP 7.1 some time in mid-17.7.

**Comment by fichtner** [comment]
# git grep '= *& *$config'

All entries in src/www must be converted, the src/etc entries are backend calls and need to protect their access properly.

**Comment by AdSchellevis** [comment]
@fichtner https://github.com/opnsense/core/commit/69510a5fade1f55ca3dc11223d33d3aa76fb08c0 should be the last batch, shall I close the issue? or do you want to keep it open until 17.7.x?

**Comment by fichtner** [comment]
Thank you very much. Need to keep this open, the plugins need the same fix.

**Comment by AdSchellevis** [comment]
sorry forgot about that, will fix that soon.

**Comment by AdSchellevis** [comment]
https://github.com/opnsense/plugins/commit/b3ac2871e242f57e66312cc1357c38f633868133 should fix the plugins

**Comment by fichtner** [comment]
@AdSchellevis thanks again for the help, added more cleanups, ditching over 200 additional lines. all modified plugins received a revision bump and this is closed. :)
