### ISSUE TITLE
OpenVPN CRL broken after upgrading to 17.1.10

### ISSUE THREAD

**Issue by abplfab** [opnsense/core#1734]
Hi

Just upgraded to 17.1.10. After a reboot the OpenVPN Plugin crashes with error [1] and stops loading other services.
Workaround: Login locally, choose restart all services (after you will have WebGUI & SSH again) -> Set "Peer Certificate Revocation List" to "None" on all OpenVPN Servers and reboot.

[1]
Fatal error: Uncaught Error: Call to undefined function openssl_crl_new() in /usr/local/etc/inc/certs.inc:559 Stack trace:
#0 /usr/local/etc/inc/plugins.inc.d/openvpn.inc(846): crl_update(Array)
#1 /usr/local/etc/inc/plugins.inc.d/openvpn.inc(1163): openvpn_reconfigure('server', Array)
#2 /usr/local/www/vpn_openvpn_server.php(406): openvpn_configure_single('1')
#3 {main} thrown in /usr/local/etc/inc/certs.inc on line 559

Fabian

**Comment by fichtner** [comment]
@abplfab php70-openssl-7.0.21_1 went out shortly after 17.1.10 was released. check your packages, use a different mirror if necessary.

**Comment by abplfab** [comment]
Thanks, that fixed it!

**Comment by fichtner** [comment]
:)
