### ISSUE TITLE
OpenVPN "Connected Since" time format

### ISSUE THREAD

**Issue by abplfab** [opnsense/core#1737]
Would be great to have the "Connected Since" in a more readable format on OpenVPN -> Status and on the Widget

**Comment by abplfab** [comment]
Seems to be epoch time

**Comment by fichtner** [comment]
@abplfab I don't have time this week due to finishing up 17.7, can you ping this again next week? :)

Thanks,
Franco

**Comment by abplfab** [comment]
Sure! No problem, good luck with 17.7 :)

**Comment by fichtner** [comment]
One instance was missing. But the date looks off with the year at the end.

Can you try this and screenshot for me? (just drag and drop in github, it uploads the image)

    # opnsense-patch 35e57c0fe

**Comment by abplfab** [comment]
![2017-08-01 14_45_09-connection status _ openvpn _ vpn _ asterix1 neratec local](https://user-images.githubusercontent.com/28706980/28825870-361c1f16-76c8-11e7-9447-0dae73f8c849.png)

**Comment by abplfab** [comment]
![2017-08-01 14_46_57-dashboard _ lobby _ asterix1 neratec local](https://user-images.githubusercontent.com/28706980/28825948-7af2da26-76c8-11e7-9bf5-123687560e6d.png)

**Comment by fichtner** [comment]
Thanks, now try:

    # opnsense-patch f43f02d


Cheers,
Franco

**Comment by abplfab** [comment]
![2017-08-01 15_03_14-connection status _ openvpn _ vpn _ asterix1 neratec local](https://user-images.githubusercontent.com/28706980/28826509-ad379b3c-76ca-11e7-9e3c-4d20156d2a44.png)
![2017-08-01 15_02_31-dashboard _ lobby _ asterix1 neratec local](https://user-images.githubusercontent.com/28706980/28826508-ad3645de-76ca-11e7-828d-ae96d17f4a33.png)

**Comment by fichtner** [comment]
If you haven't rebooted your box for this amount of time the values should be correct?

**Comment by abplfab** [comment]
Hmm, no. 

> Uptime of the Box: 01:09:47

> OpenVPN Client: Tue Aug 01 14:27:40 2017 Initialization Sequence Completed

(All local time)

**Comment by fichtner** [comment]
Maybe it's milliseconds, but either way that handling has been totally broken for a long time... brb

**Comment by abplfab** [comment]
Just killed the VPN Session on the Firewall to be sure. After a reconnect: 
Widget says 2017-07-31 00:14:18
OpenVPN -> Connection Status: Connected Since 2017-07-26 03:40:44

**Comment by fichtner** [comment]
doesn't make any sense other than that we are reading the wrong value. I will need a setup to reproduce.

**Comment by fichtner** [comment]
So this? :)

    # opnsense-patch a5e5661

**Comment by abplfab** [comment]
Great! Fixed. On both; 2017-08-01 15:08:53 which is the same time as the client says (Tue Aug 01 15:08:59 2017 Initialization Sequence Completed)

**Comment by abplfab** [comment]
Now over and out, happy Swiss National Day :)

**Comment by fichtner** [comment]
Bytes should also be fixed, one was empty, the other one showing the wrong field. It was misaligned as well. Thanks for the report and the help! :)

Gleichfalls ;)

Grüsse
Franco
