### ISSUE TITLE
Hosts Alias IP Range

### ISSUE THREAD

**Issue by abplfab** [opnsense/core#1738]
Adding multiple hosts for i.e. 192.168.36.100-192.168.36.200 is accepted by the GUI.
If I afterwards create a Firewall rule with this alias, it doesn't work.
Type: Host(s)
Name: i.e. "LAN_DHCP_RANGE"
Descrition: <empty>
Aliases: 192.168.36.100-192.168.36.200

**Comment by AdSchellevis** [comment]
this looks like an issue with the validation, ranges should only work for network types. 
This should work
![image](https://user-images.githubusercontent.com/9783985/28619010-d4a30260-7206-11e7-85d0-a069acb7dcf4.png)

We should inspect the validation here.

**Comment by abplfab** [comment]
Yes, with Network(s) it works correctly. Thanks. If I remember right on pfSense it was "hosts". Would be great to have a Help comment on how to use "-" or ":" for Ports/IPs.
