### ISSUE TITLE
Publish image hash for verification on download page

### ISSUE THREAD

**Issue by intekhabrizvi** [opnsense/core#1746]
Hello everyone,
I just downloaded opnSense but i can't verify the code integrity because there is no information regards to verification hash. 
Its bit difficult to for me to trust mirror websites hosting images without verification hash.
I suggest you guys to publish SHA256 or any other hash to verify the image integrity as soon as user select all 3 "Fast Download selector" option on your download page. So that user can verify the image as soon as download complete.
This way we can easily track the illegal changes / code injection.
Thanks

**Comment by fichtner** [comment]
hashes in mails:

https://lists.opnsense.org/pipermail/announce/2017-July/000081.html
http://marc.info/?l=opnsense-announce&m=150003353632019&w=2

hashes on website:

https://opnsense.org/opnsense-17-7-rc1/
https://forum.opnsense.org/index.php?topic=5494.0

We also added SHA256 digests for the upcoming 17.7 images, which can be verified with a public RSA key we'll publish via the same channels.

Lastly, we will update the download page to also show this sort of info.


Cheers,
Franco
