### ISSUE TITLE
Assign interface Lan to a bridge

### ISSUE THREAD

**Issue by sachaz** [opnsense/core#1754]
Hi,

I cannot " 2) Set interface(s) IP address" to a bridge as LAN interface:

 LAN (igb2)      -> 
 LANWIFI (bridge0) -> v4: 10.34.2.254/24
 OPT1 (igb1)     -> 
 WAN (igb0)      -> v4/DHCP4: 10.11.12.100/24
 WIFI (ath0_wlan1) -> 

  0) Logout                              7) Ping host
  1) Assign Interfaces                   8) Shell
  2) Set interface(s) IP address         9) pfTop
  3) Reset the root password            10) Filter Logs
  4) Reset to factory defaults          11) Reload all services
  5) Power off system                   12) Upgrade from console
  6) Reboot system                      13) Restore a configuration

Enter an option: 1

Valid interfaces are:
igb0             00:0d:b9:47:2c:4c Intel(R) PRO/1000 Network Connection, Version - 2.5.3-k
igb1             00:0d:b9:47:2c:4d Intel(R) PRO/1000 Network Connection, Version - 2.5.3-k
igb2             00:0d:b9:47:2c:4e Intel(R) PRO/1000 Network Connection, Version - 2.5.3-k
ath0_wlan1       04:f0:21:2e:55:42 
ath0              Atheros 9280

You now have the opportunity to configure VLANs.  If you don't require VLANs
for initial connectivity, say no here and use the GUI to configure VLANs later.

Do you want to set up VLANs now [y|n]? n

If you do not know the names of your interfaces, you may choose to use
auto-detection. In that case, disconnect all interfaces now before
hitting 'a' to initiate auto detection.

Enter the WAN interface name or 'a' for auto-detection: igb0

Enter the LAN interface name or 'a' for auto-detection
NOTE: this enables full Firewalling/NAT mode.
(or nothing if finished): bridge0

Invalid interface name 'bridge0'

Enter the LAN interface name or 'a' for auto-detection
NOTE: this enables full Firewalling/NAT mode.

**Comment by fichtner** [comment]
Which version are you on? Which version did this stop working? Was it ever working? Option "1" is for first time setup: physical and VLAN, Option"2" is for light reassignment. You said option "2" but pasted option "1".

**Comment by sachaz** [comment]
opnsense-17.1.4
I think it never worked.
I cannot assign lan to bridge on option 1 too.

**Comment by fichtner** [comment]
We won't change interface assignment. Extended configuration (beyond ethernet and VLANs) is created via the GUI or a config import from a previous system.

IP assignment works for assigned interfaces including a bridge, I just tested this...

**Comment by AdSchellevis** [comment]
Timeout
