### ISSUE TITLE
17.7 service configuration buttons not inline

### ISSUE THREAD

**Issue by fabianfrz** [opnsense/core#1755]
![spectacle pe2602](https://user-images.githubusercontent.com/3713914/28840499-764157ee-76f7-11e7-9d87-e147edcf1fb1.png)

**Comment by AdSchellevis** [comment]
@fabianfrz I don't think there is a very nice solution, but this should work https://github.com/opnsense/core/commit/1e87fd4a6a9eef34e835c97c50acb3e2f377a588

**Comment by fichtner** [comment]
in the smallest possible screen size this still wraps

this stuff can be fixed in general, but we really need to get rid of tables in favour of divs

**Comment by AdSchellevis** [comment]
It will always wrap at some level, even with divs... hiding columns on xs size is also still an option. I don't expect the widgets will be converted any time soon (to less to gain, too much effort to restructure all).

**Comment by fichtner** [comment]
that's true, wrap or overflow. the problem with tables at the moment is that every other row will overflow, while the other doesn't. I tried to fix this, but it's impossible. Maybe that is a better context. :)

**Comment by AdSchellevis** [comment]
true, the question for this issue is..... is the fix good enough (within the boundaries we can fix), or do we wait for something better. 
I vote for close :)

**Comment by fabianfrz** [comment]
@AdSchellevis me too. If the display is small enough this should be possible but not on a screen wide enough.
