### ISSUE TITLE
17.7 d3 graph in widget broken

### ISSUE THREAD

**Issue by fabianfrz** [opnsense/core#1756]
Error from JS console:
```
TypeError: i is null
```

Data seems to exist:
![spectacle bh2602](https://user-images.githubusercontent.com/3713914/28840729-2e89a374-76f8-11e7-826b-ff01092e0871.png)

![spectacle ad2602](https://user-images.githubusercontent.com/3713914/28840761-4e9e06aa-76f8-11e7-863f-e698d144167b.png)

**Comment by fichtner** [comment]
I know. I'll take a look.

**Comment by fichtner** [comment]
@fabianfrz which browser are you using? chrome?

**Comment by fichtner** [comment]
works in safari, chrome, firefox. not sure what this was about...

**Comment by fabianfrz** [comment]
![bildschirmfoto am 2017-08-02 um 19 32 41](https://user-images.githubusercontent.com/3713914/28886343-6c80af8a-77b9-11e7-9298-590d8240a6b1.png)

The chart is still empty.

**Comment by fabianfrz** [comment]
![bildschirmfoto am 2017-08-02 um 19 32 41](https://user-images.githubusercontent.com/3713914/28886343-6c80af8a-77b9-11e7-9298-590d8240a6b1.png)

The chart is still empty.

This may be an issue with a memory leak as opening the page will result in more and more GB of memory used in seconds.
