### ISSUE TITLE
Bug? No gateway assigned by DHCP after upgrade to 17.7

### ISSUE THREAD

**Issue by violuke** [opnsense/core#1757]
Firstly thanks for the great work generally, OPNSense is so much better than the Sonicwall we used before.

We upgraded last night to 17.7 and everything went smoothly apart from the DHCP server (v4) stopped allocating a Gateway so as each device renewed their lease they lost internet connection.

Once I realised the problem, I checked the `Services > DHCP > Server` settings for the LAN and the `Gateway` box was empty (as it always has been). To clarify, it did not contain `none`.

![gateway](https://user-images.githubusercontent.com/6420347/28860194-6739fe84-7753-11e7-9147-04d9168965e6.jpeg)

I could fix the issue by manually setting the Gateway value to the OPNSense box's IP address on the LAN (`10.0.0.1` in my case) and then getting all devices to renew their DHCP lease.

In `System > Gateways > All` we have just the one and it is marked as the default. Prior to making the above change to the DHCP settings, I tried toggling the `Disable Gateway Monitoring` checkbox, but that made no difference. Our gateway settings were as follows:

![gateway](https://user-images.githubusercontent.com/6420347/28860342-250bc6ea-7754-11e7-905c-0cd5455d6f64.jpeg)

Obviously, I've managed to get around the issue now, but it does seem to me to be a bug that no gateway was specified. I hope this all makes sense and please let me know if you need any more info to help track down what's happened. Thank you

**Comment by AdSchellevis** [comment]
Could you remove the gateway again and check what is written in the config? 

`grep 'routers' /var/dhcpd/etc/dhcpd.conf
`

It's not the prettiest code in the world, but it should propagate your interfaces address when no gateway is provided  https://github.com/opnsense/core/blob/17.7/src/etc/inc/services.inc#L723-L733 assuming your lan interface has no gateway set by itself.

**Comment by violuke** [comment]
Thanks for the quick reply.

I've removed the gateway from both LAN and OPT1 networks, restarted the DHCP service and now I get allocated a gateway by DHCP when renewing a lease. So basically, it is not doing the same thing as it did immediately following the upgrade. (Once I found the issue earlier, I never tried removing the gateways again.)

The output of your command is as you'd expect:
```
  option routers 10.0.0.1;
  option routers 192.168.100.1;
```

I suspect that this file got modified during the upgrade which is when they got removed. Now that I've re-saved, they have gone back in?

**Comment by fichtner** [comment]
It would seem when your DHCP server was started there was no address on the WAN link, so the gateway detection failed. A restart of the DHCP server should fix this condition, at least to be able to workaround and trouble shoot. If that's the case, it needs to be examined why your link reacts so slowly.

I reckon you are using DHCP to get your address on WAN?


Cheers,
Franco

**Comment by violuke** [comment]
Thanks Franco, that could explain why it was missing from the DHCP server, but WAN is a static IP.

I can't see why is would be slow to get the IP when static, but I'm no expert at these things. The physical setup is very simple on the WAN side:

```
OPNSense WAN ------> Gigabit Switch ------> Primary Gateway (Share a Floating IP Address)
                                   `-----> Backup Gateway (Share a Floating IP Address)
```

![opn1](https://user-images.githubusercontent.com/6420347/28874305-39259324-7789-11e7-991f-74534ea76aad.jpeg)

**Comment by fichtner** [comment]
I wasn't implying it was so, just trying the most likely scenario. In that case the static gateway setup will help pinning down the code that is responsible, something inside extracting the gateway ip from the static interface. It does sound like there is a bug/race in there somewhere.

**Comment by violuke** [comment]
Ok, great, I appreciate your help. Yeah, being DHCP would seem like the most likely reason for it being slow.

I'm not sure if it is relevant but I did notice after the upgrade that the `apinger` service wouldn't start. I tried a few times. Eventually it would start after, I disabled monitoring of the gateway and re-enabled it again.

**Comment by fichtner** [comment]
sounds like the same issue: can't extract any gateway IP, but was probably always a latent bug, nothing particularly new as one or two other users reported this over the last months sporadicly after updates that didn't change any code that was responsible :)

**Comment by violuke** [comment]
Ah ok, that makes sense. Feel free to close this if it's not important. I'm really impressed with the project and now know more about how it works for the future. I'm a PHP dev myself so hopefully can help out with the code one day too.

**Comment by fichtner** [comment]
we'll leave this open for a closer inspection.

if you want to contribute, please do. we'll help with questions, too. :)

**Comment by fichtner** [comment]
Timeout.
