### ISSUE TITLE
[17.1/17.7] feature request: possibility to add persistent changes to /boot/devices.hints

### ISSUE THREAD

**Issue by cvbkf** [opnsense/core#1758]
hello, 

i am using opnsense on many boxes with different hardware, so far with nearly zero issues. now, i upgraded my own opnsense hardware from an intel D510MO to a fairly new GA-N3160 mini-itx motherboard with an intel celeron N3160. 
At boot time, i get 10-12 messages regarding a controller timeout on the (non-existent) sdhc-reader, which seems to be the same bug like [described here (freebsd)](https://lists.freebsd.org/pipermail/freebsd-bugs/2016-August/069271.html). The timeouts stall the boot for around three minutes, which is quite annoying. 
Adding "hw.sdhci.enable_msi=0" to /boot/loader.conf.local and "hint.sdhci_pci.0.disabled=1" to /boot/device.hints solves the problem, but the changes to device.hints are not persistent in case of upgrading opnsense. 
Maybe a feature like adding own hints via GUI (e.g. at the tunables) could make it easier to fix such kinds of hardware hiccups without recompiling the kernel.

**Comment by fichtner** [comment]
Hi @cvbkf,

As far as I know, the boot loader configuration files are simply registered as:

loader_conf_files="/boot/device.hints /boot/loader.conf /boot/loader.conf.local"

Have you tried to add both settings to /boot/loader.conf.local?

Cheers,
Franco

**Comment by cvbkf** [comment]
Hello @fichtner,

i tried your suggestion and it worked. didn't know that, so thank you very much. i'll close the issue now as it is resolved.

**Comment by fichtner** [comment]
yay, awesome 👍
