### ISSUE TITLE
Issues with secondary D-link card on OPNsense 17.x series

### ISSUE THREAD

**Issue by epicavic** [opnsense/core#1759]
Hello

i've upgraded recently from opnsense 16.7 to 17.7 (tried different 17.x versions and tried upgrade and clean install) and started to face weird issue with DGE-528T Gigabit Ethernet Adapter

hardware config description:
3 LAN interfaces: 
 - bult-in AR8131 Gigabit Ethernet
 - 2x PCI DGE-528T Gigabit Ethernet Adapters
 - Dlink interfaces for dual-home internet from different ISP's
 - Dlink interfaces configured into failover gateway group (ISP's gateways are monitored)

issue description:
 - one of the Dlink interfaces start loosing connection with ISP gateway every 10-15 minutes. connection get lost for random period of time up to 10 min. traffic gets blackholed
 - no errors, no collisions
 - interface keeps ip settings (received via dhcp)
 - if i do dhcp release/renew - ISP's gateway can be contacted once again ... but in 10-15 min starting experience same issue
 - on opnsense 16.7 everything works without issues

**Comment by fichtner** [comment]
Hi there,

Do you have gateway switching enabled under firewall: settings: advanced?


Cheers,
Franco

**Comment by fichtner** [comment]
PS: it would be good to know when this started happening. 16.7 to 17.7 is a long way... I'm guessing you were on 16.7.14_2? How does 17.1.4 behave? How does 17.1.11_1 behave?

**Comment by epicavic** [comment]
Hi,
everything was fine on OPNsense 16.7.14_2-amd64
- i've upgraded to 17.1 about 30-35 days ago and performed update to the latest version at that moment.
that's the moment when this started happening
- on 1st of aug updated to 17.7.(latest) - same behaviour
- exported config, performed fresh install of 17.7, imported config - same behavior
- installed 16.7 - imported config - everything works fine

i haven't touched any settings under firewall: settings: advanced,   so everything should have been configured with default settings there

**Comment by fichtner** [comment]
So 17.1.11_1 is not working for you, but 17.1.4 is?

**Comment by epicavic** [comment]
none of 17.x line were working (at least the ones i've tried)
because of that i had to revert to 16.7

**Comment by fichtner** [comment]
You can try FreeBSD 11.1, we will likely adapt 18.1 to it. It looks like 11.0 changed something, but can't be sure unless someone looks at the driver who knows them. Unfortunately that's not us.
