### ISSUE TITLE
17.7 issues with DHCPv6

### ISSUE THREAD

**Issue by mhercek** [opnsense/core#1761]
Server: OPNsense: 17.7, clean installation
Client: Windows 10 Enterprise latest updates, client connected directly into LAN interface of OPNsense.
**Problem: Client does not get an IPv6 address from DHCPv6 server running on OPNsense.**

DHCPv4 on LAN works as expected.
Client gets IPv6 gateway via RA but not IP addresses from DHCPv6. There is no lease in Services -> DHCPv6 -> Leases. DHCPv6 has configured these options: range, DNS servers, domain name, domain search list, default lease time (one day), maximum lease time (two days) and time format change.

Router Advertisements are configured as managed and RA sending is enabled.
System logs show nothing related to DHCPv6.

Firewall only has one rule attached to the LAN interface:
- direction: any - any
- protocol: any
- action: pass.

Client has working IPv6 networking stack.

**Comment by mhercek** [comment]
According to the process list, DHCPv6 is running, but config file does not exist!
I've made some changes in DHCPv6 server settings and config file has not been created.

` ps -fx | grep dhcp`
`13557  -  Ss       0:12.82 /usr/local/sbin/syslogd -s -c -c -P /var/run/syslog.pid -l /var/dhcpd/var/run/log -f /var/etc/syslog.conf`
`14317  -  Ss       0:00.19 /usr/local/sbin/dhcp6c -d -c /var/etc/dhcp6c_lan.conf -p /var/run/dhcp6c_vmx1.pid vmx1`
`15082  -  Is       0:00.00 /usr/local/sbin/dhcpleases6 -c /usr/local/bin/php -f /usr/local/sbin/prefixes.php|/bin/sh -l /var/dhcpd/var/db/dhcpd6.leases`

**Comment by fichtner** [comment]
dhcpd is not running, you seem to have hit a a configuration that will not render a config, but it's totally unclear why from the currently provided info
