### ISSUE TITLE
NTPd add Custom Field

### ISSUE THREAD

**Issue by abplfab** [opnsense/core#1764]
We have to ignore the KoD for our monitoring. Currently we can only disable/enable KoD globally. It would be nice to have a text field or something to add custom data to ntp.conf
ie. we need to add:
`restrict 62.2.85.xy nomodify`
`restrict -6 2001:8a8:a:b::c nomodify`

**Comment by fichtner** [comment]
@abplfab ping me if I don't follow up. I'll take a look soon. :)

**Comment by abplfab** [comment]
Here is your ping :)

**Comment by fichtner** [comment]
better late than never...

**Comment by fichtner** [comment]
@abplfab small follow up since the output breaks on very long IPv6 output...

    # opnsense-patch 4e1c7d4

Cheers,
Franco
