### ISSUE TITLE
Multiple subnets on one Interface

### ISSUE THREAD

**Issue by elsobrino** [opnsense/core#1767]
Versions: OPNsense 17.1.4-amd64FreeBSD 11.0-RELEASE-p8OpenSSL 1.0.2k 26 Jan 2017

We have a customer who wants to migrate from Watchguard to OPNsense and he has multiple subnets assigned to one interface. Is there any way to configure something alike with OPNsense? I wasn't able to find a corresponding option.

**Comment by fichtner** [comment]
under Firewall: Virtual IPs, IP Alias.

Upgrade to 17.7 if you can, 17.1 is no longer receiving stable updates.

**Comment by elsobrino** [comment]
Franco, thank you.

**Comment by fichtner** [comment]
:)
