### ISSUE TITLE
Unbound adds forward-addr: 8.8.8.8 but it's unrechable today...

### ISSUE THREAD

**Issue by mircsicz** [opnsense/core#1768]
Hi hi,

I've just upgraded one of our APU2 based OPNsense boxes to 17.7 and immediatly after the upgrade lost internet connection! At least the colleages thought it's a lost internet connection, but it was just DNS...

On closer inspection I realized that I can't ping 8.8.8.8 but can 8.8.4.4... In System > Settings > General there was no DNS listed. But /var/unbound/unbound.conf contains the following lines:

`# Forwarding
forward-zone:
    name: "."
        forward-addr: 8.8.8.8
        forward-addr: 5.10.0.122`

So I'm wondering where unbound get's that IP from? The IP 5.10.0.122 is from our ISP...

I manully changed it to 8.8.4.4, but on restart of the unbound service it reappears.

**Comment by fichtner** [comment]
The servers there come from /etc/resolv.conf or /var/etc/nameservers.conf or /var/etc/nameserver_*

We don't hardcode "8.8.8.8" anywhere so it must either have come from the upstream DHCP or was set somewhere else.

In fact, I can't find what /var/etc/nameservers.conf was for so I'm ditching this...

**Comment by mircsicz** [comment]
Hi Franco and THX for the hint...

I don't have /var/etc/nameservers.conf, but I do have a /var/etc/nameserver_igb1

`
cat /var/etc/nameserver_igb1
8.8.8.8
5.10.0.122
`

So now I know for sure that it came from WAN...

**Comment by fichtner** [comment]
Ok, close? :)
