### ISSUE TITLE
CPU goes 100% while SNMP is enabled

### ISSUE THREAD

**Issue by str1k3r** [opnsense/core#1770]
I have 5 instances with the latest OpnSense (17.7 for now) and every instance is affected with that. 
As I noticed that happened after upgrade from 16.7.14.

**Comment by fichtner** [comment]
a cd drive assigned in the VM will do that, it's a know issue

either: remove cd driver from vm or insert cd into drive

you can also disable the hostres module in snmp

**Comment by str1k3r** [comment]
@fichtner can't disable hostres module due to enabled SNMP monitoring, but the workaround with mounted cd image helped. thanks!

**Comment by fichtner** [comment]
we're hoping for a fix upstream, maybe FreeBSD 11.1 is already better. we'll have to see. :)

Cheers,
Franco
