### ISSUE TITLE
[17.7] ignores /boot/loader.conf.local

### ISSUE THREAD

**Issue by sjorge** [opnsense/core#1772]
I was trying to figure out why my serial console stopped working after the upgrade to 17.7.

It looks like /boot/loader.conf.local is no longer appended to /boot/loader.conf!

```
root@hydrogen:/boot # cat loader.conf.local
ipmi_load="YES"
hint.uart.0.flags="0x10"
hint.uart.1.flags="0x10"
root@hydrogen:/boot # grep ipmi_load loader.conf
root@hydrogen:/boot # ls -l loader.conf*
-rw-r--r--  1 root  wheel  1727 Aug 10 20:22 loader.conf
-rw-r--r--  1 root  wheel    66 Aug 10 20:21 loader.conf.local
```

**Comment by fichtner** [comment]
Very unlikely, ipmi module is loaded after boot or not?

**Comment by fichtner** [comment]
btw... maybe this changed ?

    # grep hint.uart...flags /boot/device.hints

**Comment by sjorge** [comment]
kldstat shows it yes, its the uart stuff that stopped working.

But I just grepped on the first line of loader.conf.local in loader.conf, I know on 17.1 the content of loader.conf.local got appended to loader.conf, I even did a reboot earlier to day to make sure it got update. But doesn't matter what I add ti loader.conf.local it never shows up in loader.conf anymore as the header states it should.

```
root@hydrogen:~ # head -5 /boot/loader.conf
##############################################################
# This file was auto-generated using the rc.loader facility. #
# In order to deploy a custom change to this installation,   #
# please use /boot/loader.conf.local as it is not rewritten. #
##############################################################
```

**Comment by fichtner** [comment]
no:

    # grep loader_conf_files /boot/defaults/loader.conf
    # loader_conf_files instead and you will be able to update these
    loader_conf_files="/boot/device.hints /boot/loader.conf /boot/loader.conf.local"

all files are loaded from here

**Comment by sjorge** [comment]
You seem to be right, I just rebooted it with the ipmi_load line commented and the driver is missing after boot.

Maybe I should move the hint.* lines to /boot/device.hints ? or does this one get regenerated by OPNsense?

**Comment by fichtner** [comment]
it is included in a base set update via FreeBSD, but you can try to see if that makes a difference

**Comment by sjorge** [comment]
Alright, I'll give this a go and close this issue as it seems ipmi does get loaded when added to loader.conf.local so it is getting loaded properly.

**Comment by fichtner** [comment]
you could also create a rc.loader.d plugin file, but I would think it doesn't help:

https://github.com/opnsense/core/blob/master/src/etc/rc.loader.d/20-misc

Also, maybe this affects you:

https://github.com/opnsense/src/commit/0357654fe95b5738bccc889520683b3190b4f495

**Comment by sjorge** [comment]
Could very well be as it is also a older atom system. Seems I can only get either COM0(Physical) or COM1 (SoL) not COM0 and COM1, which worked before.

Anyway, enough messing with this for today I will poke it some more this weekend.

**Comment by sjorge** [comment]
Device hints did work, both ports are now marked as 0x10 so they can hold a system console
```
sjorge@hydrogen:~ % dmesg | grep uart
uart0: <16550 or compatible> port 0x3f8-0x3ff irq 4 flags 0x10 on acpi0
uart0: console (115200,n,8,1)
uart1: <16550 or compatible> port 0x2f8-0x2ff irq 3 flags 0x10 on acpi0
```

However the console is still only available on uart0 after the loader screen.

**Comment by fichtner** [comment]
You could try the older kernel to verify that commit broke it, but from the looks of it this seems to be "working as intended" since the patch came from upstream unless we miss some crucial piece. maybe the driver now only ever cares about one of those now that it knows both?!
