### ISSUE TITLE
MVC: rewrite static routes

### ISSUE THREAD

**Issue by AdSchellevis** [opnsense/core#1774]
The new static routes code is work in progress, with the help of @fabianfrz we have a mostly working setup (https://github.com/opnsense/core/pull/1749), now we need to smoothen the edges..

I've found the following issues so far:

- [x] gateway changes are immediately applied on save, which could lead to an inaccessible machine
- [x] changing a network removes the old route, but doesn't add the new one, same for changing the gateway.
- [x] disabled/enabled colors are switched in the grid.
- [x] address family for the route is missing a validation.

**Comment by fabianfrz** [comment]
2) it should do it (it deletes the old one and adds the new one)
3) configd or model?
4)  the reason for the inverted display is here:
     https://github.com/opnsense/core/blob/master/src/opnsense/www/js/opnsense_bootgrid_plugin.js#L75

    The problem here is, that the function does not know if this is a enable or disable checkbox. Maybe a hint as a data property is required. for example data-display-inverted=yes.

**Comment by AdSchellevis** [comment]
2. it didn't on my end, needs further inspection

3. model / controller, I understand the issue there, we need to add some additional validations (maybe use the same kind of glue as the gateway list). Let me think about this some more.

4. we should either revert the mark in the controller (make it enabled again, which is more logical) or fix the javascript glue. I'm not a very big fan of presenting something other then what is stored, but from a user perspective enabled could be more logical.

**Comment by fabianfrz** [comment]
@AdSchellevis the disabled stuff comes from the legacy data model. the first step should not change the behaviour in the GUI as this may confuse users. I am also not a big fan of inverting boolean values before storing as it is just dangerous to break something.

**Comment by fichtner** [comment]
The config model version keeps switching every now and then on the same installation: Migrated OPNsense\Routes\Route from 0.0.0 to 0.0.1

**Comment by AdSchellevis** [comment]
While working on https://github.com/opnsense/core/issues/1971 I noticed that the old route pages used filter_expand_alias_array to support aliases, I don't mind ditching this support as it has some flaws (content may changed unnoticed) but some people may use it. 

So maybe this is a good time to discuss these new pages again, the extra validations and explicit apply I can fix,  but it will mean we stop support for aliases in this place when hitting 18.1. 

@fabianfrz @fichtner what do you think?

**Comment by fabianfrz** [comment]
@AdSchellevis I have not known that this feature has existed but it may be ported to the MVC version if needed. In this case it will be hard to validate this settings as there is currently no alias functionality.

**Comment by AdSchellevis** [comment]
@fabianfrz I'm not sure if I have enough spare time to fix that, fixing what's already there (either this or the legacy system_routes*.php code) costs time.... Which likely results in a choice of dropping some support or reverting back to what we had. 

It was a bit too enthusiastic of me pulling the new code in before all concerns where solved.

**Comment by fichtner** [comment]
My biggest concern is that "routes_wrapper" does not really work as a replacement as it is too coarse in creating routes and they may not look like when being configured by the "normal" routing configure call. Let me help a bit by adding a rc script / configd call for routing...

**Comment by fichtner** [comment]
Now we should kill routes_wrapper usage and add an apply button instead... 7e4bcda61

**Comment by AdSchellevis** [comment]
@fichtner but what do you think about the aliases in there? I'm not sure if they cover all scenarios as it is now (recursion, hosts, aliases fetched from remote locations, etc,).

**Comment by fichtner** [comment]
I don't think aliases are very useful here, it's just for 1:1 mapping.. an alias for a single network?!

**Comment by AdSchellevis** [comment]
It adds all addresses (?) in the alias at once, but to be honest, to me this looks like fuzzy logic. If we are going to ditch support, we should in my opinion do that in 18.1 (I can do the rest of the work for this issue)

**Comment by fichtner** [comment]
@AdSchellevis I've cleaned up the add/delete, now it only reconfigures, but can you take care of the two remaining things?

I'm fine with dropping it.

**Comment by AdSchellevis** [comment]
@fichtner sure, thanks for fixing the other things. Let's do this for 18.1, together with a nicely restructured alias handling.

**Comment by fichtner** [comment]
👍

**Comment by fichtner** [comment]
I found the cause of this:

    -  <staticroutes version="0.0.1"/>
    +  <staticroutes/>

It's when I save the config from the legacy pages. Maybe this only happens on empty nodes, idk.

**Comment by AdSchellevis** [comment]
this https://github.com/opnsense/core/commit/873f1c394a76e8c4fad0804c673474fb95f82ff3 should do the trick to validate gateway vs network address family

**Comment by AdSchellevis** [comment]
@fichtner I think the "staticroutes version="0.0.1" issue only appears when saving empty nodes, due to https://github.com/opnsense/core/blob/master/src/www/system_routes_edit.php#L35 . I think it's safe to ignore this and ditch the legacy pages, what do you think?

**Comment by fichtner** [comment]
ok, please also run "make plist-fix" after delete to regenerate the plist (make sure there are no offending files in your repo that change the plist to have files that are not in the repo normally, could happen with "make mount")

**Comment by AdSchellevis** [comment]
ok, will try todo so. small question, did the apply stuff function correctly on your end?  my config doesn't seem to reflect the reality after apply...

**Comment by fichtner** [comment]
I made sure it ran ok as it didn't require new fancy code, but I can double-check the model changes after apply.

**Comment by fichtner** [comment]
(model + routing table)

**Comment by AdSchellevis** [comment]
ok, found the first one. a typical case of `isset($rtent['disabled'])` <>` !empty($rtent['disabled']) ` the model saves a 0 when false

**Comment by fichtner** [comment]
argh, worst case of "doesn't seem to reflect the reality" there is. I assumed @fabianfrz tested at least *this*...

**Comment by AdSchellevis** [comment]
there's more weirdness in here.... also in the old code, you can't enter hostnames.... but the code is full with stuff to resolve them.

**Comment by fichtner** [comment]
alias remnants?

**Comment by AdSchellevis** [comment]
nope, doesn't seem to unpack an alias there... expect a cleanup coming in very soon

**Comment by AdSchellevis** [comment]
I think we have one real issue left now, if you remove a static route and apply, it doesn't leave...

**Comment by fichtner** [comment]
Ah, this was executed during Delete POST?

**Comment by AdSchellevis** [comment]
yep, but it shouldn't due to obvious reasons...

**Comment by fabianfrz** [comment]
@fichtner I have tested it on my machine and it did delete the route. The delete code was triggered before the model got updated or the entry deleted.

Deletion of Routes in the original PR:
* https://github.com/opnsense/core/pull/1749/files#diff-3bb7bad3aceb98f0a332f2c2a560c6c1R63
* https://github.com/opnsense/core/pull/1749/files#diff-3bb7bad3aceb98f0a332f2c2a560c6c1R135
* https://github.com/opnsense/core/pull/1749/files#diff-3bb7bad3aceb98f0a332f2c2a560c6c1R158

However this did update the route immediately and this is what @AdSchellevis tries to avoid.

**Comment by fabianfrz** [comment]
@AdSchellevis You did an awesome job on this to improve it.

**Comment by fichtner** [comment]
Sorry I meant that disable flag is not evaluated correctly...

**Comment by AdSchellevis** [comment]
@fichtner https://github.com/opnsense/core/commit/33d98ca951c4eb8384ac2b56f55de4dc8151e3fe should complete the work here, maybe not the most elegant solution of the planet, but small and effective.

**Comment by fichtner** [comment]
That's a good workaround, files are unique, not much potential for race conditions. Thanks for the wrap-up! ❤️
