### ISSUE TITLE
OpenVPN Server Connection Status columns off by one

### ISSUE THREAD

**Issue by ChristianHackAMS** [opnsense/core#1777]
On https://opnsense/status_openvpn.php

Connected Since data is missing.
Connected Since column appears to display Bytes Sent data (in raw bytes always)
Bytes Sent column appears to display Bytes Received data (in bytes, kB, MB as appropriate)
Bytes Received column is alway "0 bytes"

Sent / received numbers look good (compared with other end), but is just in the wrong columns. 

![image](https://user-images.githubusercontent.com/30165295/29395765-a1e1e70e-8356-11e7-95b1-c060ff4d2510.png)

Other end confirming data looks good:

![image](https://user-images.githubusercontent.com/30165295/29395798-ea72a062-8356-11e7-93b0-0d0e9142db30.png)

Latest 17.7 version of OPNsense although previous version did it as well. I've only recently converted over from pf..... but it shows correctly there.

**Comment by ChristianHackAMS** [comment]
Looks like this also affects the dashboard widget where the time contains bytes sent:

![image](https://user-images.githubusercontent.com/30165295/29397472-c438caec-8361-11e7-9c0e-e2214433b490.png)

**Comment by fichtner** [comment]
Already fixed via https://github.com/opnsense/core/issues/1737

Will be in 17.7.1 :)

Thanks for the report,
Franco

**Comment by fichtner** [comment]
Btw, you can try the patch by running the following from the root shell:

    # opnsense-patch 805a9bf

It simply loads 805a9bf from GitHub and applies it in the system.

**Comment by ChristianHackAMS** [comment]
Yes. That fixes it. Sorry I only searched open issues...

**Comment by fichtner** [comment]
No worries, thanks again! :)
