### ISSUE TITLE
Feature Request: Documentation of complex, many-IP CARP configurations

### ISSUE THREAD

**Issue by wytcld** [opnsense/core#1778]
See https://forum.opnsense.org/index.php?topic=5765.0. Currently the doc at https://docs.opnsense.org/manual/how-tos/carp.html describes only the simplest of setups. What's not described is what to do in a Multi WAN configuration combined with failover where multiple IPs are assigned to each WAN. In pfSense in this situation one IP is assigned as CARP, the rest as IP Alias IPs with the CARP IP specified as the interface. OPNsense does not offer the CARP IP as the interface. What is the right way to configure this then? All the IPs as CARP? One as CARP and the rest as Alias IPs assigned to the base WAN interface? The doc does not say.

**Comment by AdSchellevis** [comment]
timeout
