### ISSUE TITLE
Going to Status > Queues with default Traffic Shaping config causes error.

### ISSUE THREAD

**Issue by skarekrow** [opnsense/core#178]
The output is 
```XML error: QUEUE at line 19 cannot occur more than once```

To reproduce:

* Clean VM install
* Select Multi Lan/Wan
* 1 for each
* HFSC for the Scheduler, bandwidth didn't make a difference. But did 1000/10000 respectively.
* Enabled P2P and did not select anything or enter anything.
* Enabled games and did not select anything.
* Enabled raise other/lower and did not change anything.

Afterwards it sits on reloading filter and requires manually going back to the page. It does not refresh. Going to Status > Queues will present you with this message.

Thanks again for this! Loving the stuff the fork has been doing.

**Comment by skarekrow** [comment]
I should mention this is on the i386 platform.

**Comment by fichtner** [comment]
Queue (ALTQ) support has been removed for 15.7, so this doesn't apply anymore.

The new traffic shaping uses IPFW, we are hoping the same functionality can be achieved with it. Let us know if that works for you or if these is a feature missing.

**Comment by skarekrow** [comment]
Sweet! Thanks @fichtner will do.
