### ISSUE TITLE
Captive Portal Issues

### ISSUE THREAD

**Issue by lifewcody** [opnsense/core#1786]
Hello,

I am currently running OPNSense 17.7 and have discovered a couple issues with the captive portal.

1) When first making a template, Captive portal service is added, but not started
2) If you don't enter a hostname you get the error:

`configd.py: [cf623d2e-9b9b-443e-8592-b6adc6d94088] Inline action failed with OPNsense/Captiveportal OPNsense/Captiveportal/lighttpd-zone.conf 'collections.OrderedDict object' has no attribute 'ipaddr' at Traceback (most recent call last): File "/usr/local/opnsense/service/modules/processhandler.py", line 505, in execute return ph_inline_actions.execute(self, inline_act_parameters) File "/usr/local/opnsense/service/modules/ph_inline_actions.py", line 50, in execute filenames = tmpl.generate(parameters) File "/usr/local/opnsense/service/modules/template.py", line 309, in generate raise render_exception Exception: OPNsense/Captiveportal OPNsense/Captiveportal/lighttpd-zone.conf 'collections.OrderedDict object' has no attribute 'ipaddr'`

Once setting an IP for the hostname, it goes away. I think 'ipaddr' isn't being set to the default IP?

**Comment by AdSchellevis** [comment]
You need to apply the settings before services are started, it's intended.

The second message can't be related to the hostname, it seems to crash here https://github.com/opnsense/core/blob/master/src/opnsense/service/templates/OPNsense/Captiveportal/lighttpd-zone.conf#L8. if you can reproduce it, can you check which interface is selected and which configuration is set?
