### ISSUE TITLE
[Feature] New port forward rule: copy destination port to redirect target port

### ISSUE THREAD

**Issue by StrikerTwo** [opnsense/core#1787]
99.9% of the time I create a port forward rule to forward one port from a public IP to the same port on an internal IP.
It would be nice usability-wise if the selection in the "destination port" was automatically copied to the "redirect target port" input, at least for new rules.
As it is now, it defaults to "HTTP" in both inputs.
A simple Javascript onchange-Handler would do it and save the user a couple of clicks every time.

**Comment by AdSchellevis** [comment]
@StrikerTwo fine idea, https://github.com/opnsense/core/commit/328bfe7d29a0dfc900bf5fb4aad463336ba1bfcb should fix this on a new entry.

`opnsense-patch 328bfe7` to test

**Comment by StrikerTwo** [comment]
Looking good! Thanks for the quick response and solution.

**Comment by fichtner** [comment]
Will be in 17.7.1. Thanks!
