### ISSUE TITLE
One-to-One NAT: Host alias can be selected, but does not work

### ISSUE THREAD

**Issue by StrikerTwo** [opnsense/core#1789]
I can select a host alias under Firewall: NAT: One-to-One --> Internal IP, but if I apply the rules I get a notification saying the rules could not be loaded:

opnsense: /usr/local/etc/rc.filter_configure: New alert found: There were error(s) loading the rules: /tmp/rules.debug:72: invalid use of table <H_DAN> as the source address of a binat rule - The line in question reads [72]: binat on hn5 from $H_DAN to any -> 77.11.22.33

If it's not supported, don't let me select it.
If it should work, I found a bug :)

**Comment by AdSchellevis** [comment]
There where already some changes stashed for this area, but I kind of forgot about this one. Using an alias is only valid when using nat mode (which can be selected in the next version). I will add a validation here and close the issue when done.

**Comment by fichtner** [comment]
hrm, some of it is partially for #440 so I guess that is a yes...

**Comment by AdSchellevis** [comment]
@fichtner yes :)
