### ISSUE TITLE
CARP with IPv6

### ISSUE THREAD

**Issue by abplfab** [opnsense/core#1790]
Hi

I'm trying to setup native IPv6 with CARP. The setup is as follow:
Our Net: 2a02:aa08:xy:900::/56
Provider Router is 2a02:aa08:xy:900::1
WAN Net: 2a02:aa08:xy:900::/64
LAN Net: 2a02:aa08:xy:902::/64
OPNsense1 WAN IPv6: 2a02:aa08:xy:900::14/64
OPNsense2 WAN IPv6: 2a02:aa08:xy:900::13/64
OPNsense WAN CARP vIP: 2a02:aa08:xy:900::2/64
According to our provider he routes the 2a02:aa08:xy:902::/64 LAN net to IP 2a02:aa08:xy:900:2 (WAN CARP vIP)
What I see now: If I try to ping the CARP vIP (2a02:aa08:xy:900::2) it doesn't respond. If I change something on the vIP  Page in the GUI and click "Apply" the vIP responds for about 10s and afterwards stops to respond.
Did I miss anything in my setup?
ICMPv6 Rule is allowed on WAN from any to any, in Advanced setup IPv6 is enabled

**Comment by AdSchellevis** [comment]
timeout

**Comment by abplfab** [comment]
More Investigations done and found a workaround.
Comment from our provider:

> Unser ipv6 neighbor table zeigt den Eintrag erst wenn wir die Addresse  2A02:AA08:xy:900::2 pingen, kurz danach lauft der Eintrag ab.
> 
> ch-mceBUB010#sh ipv6  nei vrf INTERNET1                                              
> Load for five secs: 1%/0%; one minute: 1%; five minutes: 1% Time source is NTP, 12:42:02.924 CEST Fri May 10 2019
> 
> IPv6 Address                              Age Link-layer Addr State Interface
> 2A02:AA08:xy:900::6                       0 000d.b94f.619a  REACH Gi9
> 2A02:AA08:xy:900::13                      0 0cc4.7a97.e943  REACH Gi9
> 2A02:AA08:xy:900::14                      0 0cc4.7a97.e5e3  REACH Gi9
> 2A02:AA08:F000:5::1                         0 70e4.2268.1074  REACH Gi8.1188
> FE80::72E4:22FF:FE68:1074                   0 70e4.2268.1074  REACH Gi8.1188
> 
> 
> 
> Wir stellen fest dass kurz nach einem Ping aus dem connected Interface , die CARP ( 2A02:AA08:xy:900::2 ) gibt Antwort zu unserem NS mit eineme NA und ARP Addresse.
> 
> May 10 12:38:30.791 CEST: ICMPv6-ND: (GigabitEthernet9,2A02:AA08:xy:900::2) DELETE -> INCMP
> May 10 12:38:30.791 CEST: ICMPv6-ND: (GigabitEthernet9,2A02:AA08:xy:900::2) Sending NS               ---------------------------> neighbor Sollicitation
> May 10 12:38:30.791 CEST: ICMPv6-ND: (GigabitEthernet9,2A02:AA08:xy:900::2) Queued data for resolution
> May 10 12:38:30.795 CEST: ICMPv6-ND: (GigabitEthernet9,2A02:AA08:xy:900::2) Received NA from 2A02:AA08:xy:900::14        -------------> neighbor Advertissement
> May 10 12:38:30.795 CEST: ICMPv6-ND: (GigabitEthernet9,2A02:AA08:xy:900::2) LLA 0000.5e00.0114 May 10 12:38:30.795 CEST: ICMPv6-ND: (GigabitEthernet9,2A02:AA08:xy:900::2) INCMP -> REACH
> 
> 
> aus einem anderen Interface , gibt die CARP ( 2A02:AA08:xy:900::2 ) kein antwort zu unserem NS und deswegen kennt unser Router die entsprechende ARP nicht. 
> 
> 
> May 10 12:31:44.852 CEST: ICMPv6-ND: (GigabitEthernet9,2A02:AA08:xy:900::2) Resolution request 
> May 10 12:31:44.852 CEST: ICMPv6-ND: (GigabitEthernet9,2A02:AA08:xy:900::2) DELETE -> INCMP 
> May 10 12:31:44.852 CEST: ICMPv6-ND: (GigabitEthernet9,2A02:AA08:xy:900::2) Sending NS 
> May 10 12:31:44.852 CEST: ICMPv6-ND: (GigabitEthernet9,2A02:AA08:xy:900::2) Queued data for resolution 
> May 10 12:31:45.880 CEST: ICMPv6-ND: (GigabitEthernet9,2A02:AA08:xy:900::2) Sending NS 
> May 10 12:31:46.852 CEST: ICMPv6-ND: (GigabitEthernet9,2A02:AA08:xy:900::2) Replaced data for resolution 
> May 10 12:31:46.904 CEST: ICMPv6-ND: (GigabitEthernet9,2A02:AA08:xy:900::2) Sending NS 
> May 10 12:31:47.928 CEST: ICMPv6-ND: (GigabitEthernet9,2A02:AA08:xy:900::2) INCMP -> DELETE 
> May 10 12:31:48.852 CEST: ICMPv6-ND: (GigabitEthernet9,2A02:AA08:xy:900::2) Resolution request 
> May 10 12:31:48.852 CEST: ICMPv6-ND: (GigabitEthernet9,2A02:AA08:xy:900::2) DELETE -> INCMP 
> May 10 12:31:48.852 CEST: ICMPv6-ND: (GigabitEthernet9,2A02:AA08:xy:900::2) Sending NS 
> May 10 12:31:48.852 CEST: ICMPv6-ND: (GigabitEthernet9,2A02:AA08:xy:900::2) Queued data for resolution 
> May 10 12:31:49.944 CEST: ICMPv6-ND: (GigabitEthernet9,2A02:AA08:xy:900::2) Sending NS 
> May 10 12:31:50.852 CEST: ICMPv6-ND: (GigabitEthernet9,2A02:AA08:xy:900::2) Replaced data for resolution 
> May 10 12:31:51.032 CEST: ICMPv6-ND: (GigabitEthernet9,2A02:AA08:xy:900::2) Sending NS 
> May 10 12:31:52.112 CEST: ICMPv6-ND: (GigabitEthernet9,2A02:AA08:xy:900::2) INCMP -> DELETE

Workaround:
> statische Binding Lösung: 
> ch-mceBUB010(config)#ipv6 neighbor 2A02:AA08:xy:900::2 gigabitEthernet 9 0000.5e00.0114

But I guess there should be a smarter & nicer solution...
