### ISSUE TITLE
CARP with traffic shapers / fq-codel

### ISSUE THREAD

**Issue by obrienmd** [opnsense/core#1792]
My experience thus far with FairQueue-Codel via a set of pipe/queue/rules to battle bufferbloat in OPNSense has been phenomenal - A+ all around in DSLReports, good numbers against Berkeley's ICSI Netalyzer, and generally peppy performance under load.

Last week, I attempted my usual config for this against a pair of OPNSense boxes in a redundant config in CARP. Initial results were bad (lots of bloat under load), so I dug a bit further and found packet counts were not increasing in "ipfw sched show" under heavy load. 

Thinking it may be CARP (as it was the only substantive difference), I pointed a client's default gateway at one of the redundant OPNSense boxes individual IPs on the LAN, and it worked perfectly. Packets were flowing into the pipes per "ipfw sched show", and bufferbloat was way down.

I dug through pipe/queue/rules config to see where I may be going wrong, but am coming up empty. Any ideas?

**Comment by AdSchellevis** [comment]
First thing I should look at is if the packets are actually flowing to your pipe, using `ipfw show`, maybe there's an issue in the configured ruleset.

**Comment by fichtner** [comment]
You can sync the traffic shaping as well with XMLRPC, that would rule out differences in configuration unless it is somehow related to the network setup and the rulesets need to be different (hard to tell).

**Comment by obrienmd** [comment]
@fichtner traffic shaping is synchronized and same on both boxes.

**Comment by obrienmd** [comment]
@AdSchellevis `ipfw show` shows that packets are not flowing to the pipe when a client is pointed at the CARP virtual IP, but are when pointed to an individual firewall's non-shared LAN IP. Sorry if I did a crap job explaining this in my initial post :)

**Comment by obrienmd** [comment]
@AdSchellevis In my rules, I only have two rules, with:

interface: wan
proto: ip
source: any
src-port: any
dst: any
dst port: any
direction: in or out (depending on upload/download queue)
target: (appropriate queue per direction)

**Comment by AdSchellevis** [comment]
@obrienmd can you try to create a rule with direction "both" and selecting your traffic with source/destination network? 

(e.g. 192.168.0.0/24 -> any , any -> 192.168.0.0)

**Comment by obrienmd** [comment]
Well this is embarrassing... It's working now without that change. I flushed states on the firewall after my initial change set, but perhaps something else was "stuck" somewhere.

Sorry folks, not trying to spin you up constantly without cause!

**Comment by fichtner** [comment]
No worries, happy it works as intended. 😊
