### ISSUE TITLE
[Feature] Editable Suricata Network Configuration

### ISSUE THREAD

**Issue by realaquaman** [opnsense/core#1793]
When using the OPNsense between two different private networks the IDS won't work.

Reason is that the ruleset placeholder $HOME_NET gets replaced with the networks configured inside:
/usr/local/opnsense/service/templates/OPNsense/IDS/suricata.yaml

This setting is lost after an upgrade. It would be nice to specify these networks using the web GUI.

**Comment by AdSchellevis** [comment]
@realaquaman I thought about this some time ago, but kind of forgot about it.  https://github.com/opnsense/core/commit/5d457fed104e5859d4bb44bab223ceb591c9ee13 and 
https://github.com/opnsense/core/commit/c4bbef09530d2e3d5745e770025f308ee7dc83b1 should add the option (in advanced mode).

**Comment by L1ghtn1ng** [comment]
Can this go in to 17.7.1?

________________________________

**Comment by fichtner** [comment]
No, 17.7.1 is currently being finalised.

**Comment by L1ghtn1ng** [comment]
Ah okay fair enough
________________________________

**Comment by mimugmail** [comment]
Really nice feature for public only/private only networks, thanks! 👍

**Comment by mimugmail** [comment]
Close this one since it was released with 17.7.2?

**Comment by fichtner** [comment]
yep, thanks!

**Comment by realaquaman** [comment]
Thank you very much!
