### ISSUE TITLE
"Bypass firewall rules for traffic on the same interface" stopped working

### ISSUE THREAD

**Issue by StrikerTwo** [opnsense/core#1794]
**Background:**
I have a somewhat complex setup (two dedicated Hyper-V servers, each running several VMs and a OPNsense VM as router/firewall). Both servers share an internal subnet (LAN NICs and dedicated switch). Every VM is on that internal subnet and has "their" OPNsense as the default gateway. Both OPNsense VMs are setup exactly the same way (same interfaces, same everything) and I sync the firewall and NAT rules from OPNsense 1 to OPNsense 2.
On one server I have a VM that serves as a SoftEther VPN gateway to other locations with their own servers and subnets. This leads to asymetric routing if somebody from the VPN side wants to use a VM running on the second server:

```
Client -> VPN -> OPNsense 1 -> VM
VM -> OPNsense 2 -> OPNsense 1-> VPN -> Client
```

I cannot give every VM OPNsense 1 as default gateway, because that would be a SPOF if server 1 is down and server 2 keeps running (also, every server has its own dedicated public IPs and I have to use them all). 
And I don't want to give every VM a static route to the VPN subnet with OPNsense 1 as gateway because that's a lot of manual work ;)

**Problem:**
So I enabled the firewall option "Bypass firewall rules for traffic on the same interface" and everything worked fine. Until today, when my WSUS (running on server 2) told me that the PCs on the VPN hadn't contacted it for over a week. And sure enough, the firewall log on OPNsense 2 was full of blocked TCP:SA packets from the WSUS VM to the VPN clients. Reloading the rules did not help.

I finally rebooted OPNsense 2 and everything started working again.

Any ideas?

**Comment by StrikerTwo** [comment]
Huh. Worked for a few minutes after the reboot (some clients now show up in the WSUS console with a current timestamp) and now it's gone again.

**Comment by StrikerTwo** [comment]
Okay, I "solved" this by pushing out a static route to the VMs concerned via GPO. I'd still like to know why I get packets blocked by firewall rules even if OPNsense should not apply them.

**Comment by AdSchellevis** [comment]
@StrikerTwo please note that the this option is likely to vanish somewhere in the upcoming major releases see https://github.com/opnsense/core/blob/master/src/etc/inc/plugins.inc.d/pf.inc#L91

**Comment by StrikerTwo** [comment]
So what are people (cursed) with asymmetric routing supposed to do?
I can always try to create those rules manually as shown in https://doc.pfsense.org/index.php/Asymmetric_Routing_and_Firewall_Rules 
Should I try that and see if it works better?

**Comment by fichtner** [comment]
Disable state tracking for these routes (under advanced settings per firewall rule), the state tracking is meant for ensuring symmetric traffic consistency. :)

**Comment by StrikerTwo** [comment]
Problem is I do want to block connections initiated from the VMs going to the VPN. I only want to allow connections from the VPN to the VMs. Can I do this without state tracking?

**Comment by fichtner** [comment]
Each firewall rule interface tab filters incoming directions, so yes you can filter both sides. The problem is if there is no state association (or lack of symmetric), it could start dropping packets from the other side because it doesn't know the affiliation of return pack.

Did I understand this right: there is both symmetric and asymmetric traffic from/to the VM?

**Comment by StrikerTwo** [comment]
Correct. Asymmetric traffic from/to the VPN (via OPNsense 1) and symmetric traffic from other VMs (directly) or the internet (NATed via OPNsense 2).

**Comment by fichtner** [comment]
@StrikerTwo sorry, lost track of this... still relevant?

**Comment by StrikerTwo** [comment]
Not to me anyway - I switched to Zerotier as my VPN solution. With the ZT plugin running directly on the OPNsense box this problem has not occurred anymore.
Feel free to close the issue if nobody else has that problem.

**Comment by fichtner** [comment]
ok, thanks, will do. can always reopen if necessary. :)
