### ISSUE TITLE
bogons filter is too aggressive for OSPF

### ISSUE THREAD

**Issue by cultcom** [opnsense/core#1795]
The bogons table includes the range 224.0.0.0/4 which is the valid reserved multicast address space.

When I enable the bogons filter on WAN OSPF is not completely working.
As long as the peer router is DR everything is fine but if opnsense becomes DR after a reelection all routers send their updates to it utilizing 224.0.0.6 which is filtered and so the routing is broken until quagga is restarted and the peer is DR again.

I think the multicast address space must not be filtered by the bogons table as it contains valid traffic.

Same for the 169.254.0.0/16 range which transports valid linklocal zeroconf/apipa traffic. Though this range does not harm OSPF.

**Comment by fichtner** [comment]
Are you running OSPF on a public WAN address?

Historically, the bogons vs. private switch done internally is a bit weird. We could make both ranges "private" as well, but that would have strange consequences considering they were formerly blocked and now open *and* valid traffic sources of some sort.

**Comment by cultcom** [comment]
Well yes, all our addresses are public. WAN means for me the link to the backbone.

When I look at the pf rules only the source address is filtered by the bogons table am I right? In that case the problem lies somewhere else I guess.

What I can tell for sure is that not all routes are distributed when the DR changes to a OPNsense box.

**Comment by fichtner** [comment]
Thanks for the clarification :)

Yes, only incoming traffic with bogons from is filtered.

@fabianfrz and @mimugmail should be able to help. hopefully vacation time is over soon

**Comment by fabianfrz** [comment]
@fichtner What should we do? Installing firewall rules may help but I always tried to avoid to do that in the plugin.

What I can think of is injecting a pass rule for `OSPF` before the Bogon filter as this is a problem in the bogon filter.

**Comment by mimugmail** [comment]
I never thought about Bogon, hm, what is the advantage of enabling thins when you have a default drop at the end of the firewall ruleset?

Nonetheless I don't see any other chance then injecting like @fabianfrz writes ...

**Comment by cultcom** [comment]
Maybe I was wrong about the bogons. When I understand OSPF correctly the routers send packets to the multicast addresses 224.0.0.5 and 224.0.0.6 as destination but use their interface IP as source address. Thus the bogons might not be the problem here.

What I actually did notice is the following behaviour in  a setup like this:
  - R1 : a typical router (Brocade in my case)
  - O1: OPNsense VM
  - O2: OPNsense VM

R1, O1 and O2 are connected to the same L2 network and speak OSPF with each other. (O* on the WAN interface)

R1 is configured with OSPF priority 100 to be DR in the election. Everything comes up, all routes are available.

Now for whatever reason R1 becomes unavailable so O1 and O2 elect one of themselves as DR.
Say O1 is DR now.

When R1 comes back, which announces the default route, only O1 exchanges the full information with R1 and runs normally.
O2 stays in "ExStart" state for OSPF to R1 and only sees O1 as "Full (DR)" neighbour.
R1 on the other hand sees both as "Full" DR and BDR.

Since OSPF does not implement preempt for DR election I can only fix this situation by restarting quagga on O1. Then R1 is DR again and both O1 and O2 get all the routes they need.

Unfortunately I do not see any blocked packages in the firewall logs to track down the reason for this. Maybe any of you do have an idea what is going wrong here.

**Comment by fabianfrz** [comment]
@cultcom can you try out this patch:
https://github.com/opnsense/plugins/pull/237

**Comment by fabianfrz** [comment]
The plugin injects the pass rules before the bogon rule. Every rule you create in the GUI will be after the Bogon filter rules. That makes a huge difference.

**Comment by fichtner** [comment]
ping ;)

**Comment by fabianfrz** [comment]
ICMP: No route to host ;)

**Comment by fichtner** [comment]
it would seem so :D

**Comment by fichtner** [comment]
Was addressed by @fabianfrz via plugins.
