### ISSUE TITLE
Firewall: Diagnostics: pfInfo: Rules: Output should be HTML encoded

### ISSUE THREAD

**Issue by StrikerTwo** [opnsense/core#1796]
I was trying to copy my current rules from the GUI for #1794 and noticed they looked strange.

The GUI shows
`@132 block return in log quick on hn0 inet from any to  label "USER_RULE: H to SITE"
` 
but the actual JSON returned is
`@132 block return in log quick on hn0 inet from any to <Site:4> label \"USER_RULE: H to SITE\"`

Should encode those nasty brackets. Because this also works:
`@135 pass in quick on hn5 reply-to (hn5 w.x.y.z) inet all flags S\/SA keep state label \"USER_RULE: <script>alert('woah')</script>\"`

**Comment by AdSchellevis** [comment]
@StrikerTwo thanks, html() should have been text() in the jQuery code. I will commit a fix and close this one asap.

**Comment by fichtner** [comment]
A hotfix "17.7.1_2" was just issued to address this. :)
