### ISSUE TITLE
MTU ignored for incomming UDP traffic over OpenVPN to local vlan interface

### ISSUE THREAD

**Issue by 4nn0** [opnsense/core#1797]
Hi,
if we send bigger UDP packets which need to be fragmented, the target system does't receive them.
We have the default MTU 1500 on our devices and OpenVPN tunnel.

em3: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500
	options=5209b<RXCSUM,TXCSUM,VLAN_MTU,VLAN_HWTAGGING,VLAN_HWCSUM,WOL_MAGIC,VLAN_HWFILTER,VLAN_HWTSO>
	ether f4:90:ea:10:11:b3
	inet6 fe80::f690:eaff:fe10:11b3%em3 prefixlen 64 scopeid 0x4 
	nd6 options=21<PERFORMNUD,AUTO_LINKLOCAL>
	media: Ethernet autoselect (1000baseT <full-duplex>)
	status: active
ovpnc2: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> metric 0 mtu 1500
	options=80000<LINKSTATE>
	inet6 fe80::f690:eaff:fe10:11b0%ovpnc2 prefixlen 64 scopeid 0xc 
	inet 10.0.23.2 --> 10.0.23.1 netmask 0xffffffff 
	nd6 options=21<PERFORMNUD,AUTO_LINKLOCAL>
	Opened by PID 86547
em3_vlan3: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500
	options=3<RXCSUM,TXCSUM>
	ether f4:90:ea:10:11:b3
	inet6 fe80::f690:eaff:fe10:11b3%em3_vlan3 prefixlen 64 scopeid 0x12 
	inet 10.66.0.1 netmask 0xffffff00 broadcast 10.66.0.255 
	nd6 options=21<PERFORMNUD,AUTO_LINKLOCAL>
	media: Ethernet autoselect (1000baseT <full-duplex>)
	status: active
	vlan: 3 parent interface: em3

According to the MTU the packets are correctly fragmented on the ovpnc2 device 

root@firewall01p:~# tcpdump -nei ovpnc2 udp and not port 123 and not port 53
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on ovpnc2, link-type NULL (BSD loopback), capture size 65535 bytes
11:00:56.743981 AF IPv4 (2), length 163: 10.2.111.8.703 > 10.66.0.3.10080: UDP, length 131
11:00:56.774191 AF IPv4 (2), length 82: 10.66.0.3.10080 > 10.2.111.8.703: UDP, length 50
11:00:57.780584 AF IPv4 (2), length 127: 10.66.0.3.10080 > 10.2.111.8.703: UDP, length 95
11:00:57.786114 AF IPv4 (2), length 82: 10.2.111.8.703 > 10.66.0.3.10080: UDP, length 50
11:00:57.787555 AF IPv4 (2), length 1504: 10.2.111.8.703 > 10.66.0.3.10080: UDP, length 4586
11:00:57.787656 AF IPv4 (2), length 1504: 10.2.111.8 > 10.66.0.3: ip-proto-17
11:00:57.787705 AF IPv4 (2), length 1504: 10.2.111.8 > 10.66.0.3: ip-proto-17
11:00:57.787805 AF IPv4 (2), length 178: 10.2.111.8 > 10.66.0.3: ip-proto-17
11:00:57.799277 AF IPv4 (2), length 82: 10.66.0.3.10080 > 10.2.111.8.703: UDP, length 50
11:00:57.820950 AF IPv4 (2), length 728: 10.66.0.3.10080 > 10.2.111.8.703: UDP, length 696
11:00:57.826480 AF IPv4 (2), length 82: 10.2.111.8.703 > 10.66.0.3.10080: UDP, length 50

When the firewall forwarding the packets to the target system, the packets are not fragmented any more and the the target system doesn't receive them:

root@firewall01p:~ # tcpdump -nei em3_vlan3 udp and not port 123 and not port 53
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on em3_vlan3, link-type EN10MB (Ethernet), capture size 65535 bytes
11:01:17.557775 f4:90:ea:10:11:b3 > 0c:c4:7a:da:be:46, ethertype IPv4 (0x0800), length 173: 10.2.111.8.735 > 10.66.0.3.10080: UDP, length 131
11:01:17.569975 0c:c4:7a:da:be:46 > f4:90:ea:10:11:b3, ethertype IPv4 (0x0800), length 92: 10.66.0.3.10080 > 10.2.111.8.735: UDP, length 50
11:01:18.577223 0c:c4:7a:da:be:46 > f4:90:ea:10:11:b3, ethertype IPv4 (0x0800), length 137: 10.66.0.3.10080 > 10.2.111.8.735: UDP, length 95
11:01:18.582466 f4:90:ea:10:11:b3 > 0c:c4:7a:da:be:46, ethertype IPv4 (0x0800), length 92: 10.2.111.8.735 > 10.66.0.3.10080: UDP, length 50
11:01:18.584768 f4:90:ea:10:11:b3 > 0c:c4:7a:da:be:46, ethertype IPv4 (0x0800), length 4628: 10.2.111.8.735 > 10.66.0.3.10080: UDP, length 4586
11:01:18.596907 0c:c4:7a:da:be:46 > f4:90:ea:10:11:b3, ethertype IPv4 (0x0800), length 92: 10.66.0.3.10080 > 10.2.111.8.735: UDP, length 50
11:01:18.618899 0c:c4:7a:da:be:46 > f4:90:ea:10:11:b3, ethertype IPv4 (0x0800), length 738: 10.66.0.3.10080 > 10.2.111.8.735: UDP, length 696
11:01:18.624359 f4:90:ea:10:11:b3 > 0c:c4:7a:da:be:46, ethertype IPv4 (0x0800), length 92: 10.2.111.8.735 > 10.66.0.3.10080: UDP, length 50

I can see a 4628 byte big packet which should be fragmented to 4 packets (MTU 1500).
Found already similar bugs in pfsense: https://redmine.pfsense.org/issues/7801 and https://redmine.pfsense.org/issues/4723

**Comment by AdSchellevis** [comment]
just to be sure, can you dump your scrub rules?

`grep scrub /tmp/rules.debug`

**Comment by 4nn0** [comment]
root@firewall01p:~ # grep scrub /tmp/rules.debug
scrub on $Port2 all   
scrub on $VPNmgmt all   
scrub on $WAN all   
scrub on $mgmt all   
scrub on $prodcustinterface all   
scrub on $prodintinterface all   
scrub on $testint all   
scrub on $testmgmt all   
scrub on $testpub all

**Comment by AdSchellevis** [comment]
can you try what happens when scrubbing is disabled? Go to Firewall -> Settings -> Normalisation and "Disable interface scrub" .

If that works and you need to setup custom scrubbing, you can do that in the rules below.

**Comment by 4nn0** [comment]
After disabling scrubbing everything works as expected.
Thanks a lot for the hint.

**Comment by AdSchellevis** [comment]
sure, I will close this one.
