### ISSUE TITLE
dashboard widget modal: wrong z-index, needs to be in foreground

### ISSUE THREAD

**Issue by fichtner** [opnsense/core#180]
via https://twitter.com/dam09fr/status/598969238498451458

**Comment by reetp** [comment]
Hi - sorry. stupid question but I saw this bug and wondered if there was an easy way to find the patch here at github ?

I can't seem to see it as there doesn't appear to be a link to it and I would like to apply it. (I haven't downloaded the code to see a diff)

**Comment by fichtner** [comment]
@reetp no fix in the repo yet, I confirmed this locally in the developer console of the browser, but @jschellevis is the better person to fix this, or @AdSchellevis can help?

**Comment by reetp** [comment]
Thanks ! Was going to try and patch and see if worked - I have the same issue myself.
OPNsense 15.1.10.2-amd64	
Installed yesterday and updated immediately.

**Comment by fichtner** [comment]
@reetp there's a tutorial here on how to plug the latest core.git changes into your live system http://lastsummer.de/development-workflow-in-opnsense/

**Comment by reetp** [comment]
Col - thanks. I'll give it a go. Not sure how much use I'll be as I am new to BSD and howlingly bad at CSS :-)

**Comment by fichtner** [comment]
@reetp no worries. it would also help if users us this to verify fixes are working before they are shipped with a release. keep it up :)

**Comment by reetp** [comment]
LOL - I get that - I work on SME Server (www.contribs.org) and know the bug / verification process pretty well :-) Happy to help where I can...... Still testing to see if it works for me - critical bits are to do with VPNs to my SME boxes. Currently just feeling my way round.

If you push a fix for this one I'll try and verify.

**Comment by reetp** [comment]
Had a quick look at this....

.modal has a z-index of 1050 so guess it has to be higher than this.

1040 kind of works (needs to be higher than 1039 minimum as far as I can see) so I put it at 10000 and that seems fine :-)

Something like this (beware - I told you my CSS sucks !) :

root@OPNsense:~ # diff -ruN main.css.old main.css
--- main.css.old	2015-05-18 14:50:21.000000000 +0200
+++ main.css	2015-05-18 14:51:40.000000000 +0200
@@ -4810,7 +4810,8 @@
 .modal-dialog {
   position: relative;
   width: auto;
-  margin: 62px 10px 10px 10px;
+  margin: 62px 10px 10px 10px; 
+  z-index:10000;
   }
 
 .modal-content {


FYI :  cat -n main.css | grep z-index
  2597	  z-index: 2;
  3019	  z-index: 1000;
  3100	  z-index: 990; }
  3138	      z-index: 2; }
  3284	  z-index: -1;
  3298	    z-index: 2;
  3379	      z-index: 2; }
  3584	  z-index: 1000;
  3595	  z-index: 1030;
  3911	    z-index: 2;
  4223	  z-index: 2;
  4350	  z-index: 2; }
  4791	  z-index: 1050;
  4814	  z-index:10000;
  4834	  z-index: 1040;
  4899	  z-index: 1070;
  4987	  z-index: 1060;
  5171	    z-index: 5;
  5196	  z-index: 15;
  5224	  z-index: 10;
  5482	  z-index: 2; }
  5488	  z-index: 1; }
  5518	  z-index: 3; }
  5532	  z-index: 2; }
  5644	  z-index: 1; }

**Comment by AdSchellevis** [comment]
Thanks! It's fixed in https://github.com/opnsense/core/commit/8c43a733bfd124936254f2a9b39a3590aa075b00
