### ISSUE TITLE
Filter reload page

### ISSUE THREAD

**Issue by fabianfrz** [opnsense/core#1800]
Filter reload page sends lots of requests to the backend.

It may be limited to 1 request per second.

**Comment by fichtner** [comment]
Can bump this to 500 ms like firmware page, currently it's 200 ms so 5 requests per second for "real time view".

**Comment by fabianfrz** [comment]
could be better as it currently makes issues in firefox (memory issues)

**Comment by fabianfrz** [comment]
The other idea would be stopping updates after completion.

**Comment by AdSchellevis** [comment]
I vote for kill, the number of update_filter_reload_status() calls is being degraded anyway and service restart is more logical anyway.

Shall I kill it?

**Comment by fichtner** [comment]
With fire!!!

**Comment by AdSchellevis** [comment]
a bit smokey here :)
