### ISSUE TITLE
Auto-update:  parameter ALLOW_RISKY_MAJOR_UPGRADE breaks patch level updates

### ISSUE THREAD

**Issue by Woi** [opnsense/core#1804]
I just found a bug in patch 93072dd80:
Setting parameter ALLOW_RISKY_MAJOR_UPGRADE for the auto-update cron job breaks patch level updates. 

Steps to reproduce:
1. Get a box with OPNsense 17.7.1 while 17.7.1_2 is available
2. Set up an auto update cronjob with parameter ALLOW_RISKY_MAJOR_UPGRADE
3. Observer a update to 17.7.1_2 won't happen (e.g. via `/diag_logs.php`)
4. Remove ALLOW_RISKY_MAJOR_UPGRADE
5. Check the successful update.

Expected result:
Auto update with ALLOW_RISKY_MAJOR_UPGRADE installs each and every (stable) update available. 

I can confirm mayor updates are working as of 17.1.11 to 17.7.1. However I don't know about minor updates so far.

**Comment by fichtner** [comment]
Hi @Woi ,

Doesn't look wrong from the code perspective. I'll try to reproduce tomorrow.


Cheers,
Franco

**Comment by Woi** [comment]
Yeah, please enjoy your weekend :)

**Comment by fichtner** [comment]
you too :)

**Comment by fichtner** [comment]
It's quite odd.. The backend call lets "flock" decide it can't run, otherwise it's ok...

<img width="720" alt="screen shot 2017-09-04 at 7 55 59 am" src="https://user-images.githubusercontent.com/1915288/30013412-b2f82e2e-9146-11e7-89e6-ae7354d82d65.png">

It's probably an environment thing, but unsure where that came from / since when.

**Comment by fichtner** [comment]
Can you spot the problem? :)

![Uploading Screen Shot 2017-09-04 at 8.02.14 AM.png…]()

We can probably fix this in flock, the parameter buffer is way too small for this argument.

**Comment by fichtner** [comment]
Ok, my bad... thanks for the report! :)

    # opnsense-patch bc1ff72

**Comment by Woi** [comment]
Thanks :)

Applied the patch, but testing is currently kind of difficult. If it's okay for you I'll just wait for the next minor or patch level update.

**Comment by fichtner** [comment]
Testing is easy (not that it changes the core package, if you had bugs on 17.7, don't do it)

    # opnsense-revert -r 17.7 opnsense


Cheers,
Franco

**Comment by fichtner** [comment]
But you will need to apply the patch again after that command. Sorry.

**Comment by Woi** [comment]
Do you need some one to confirm the patch? Because otherwise I'd like to not test it.

But out of curiosity:
`opnsense-revert -r 17.7 opnsense` would bring me to 17.1.11, right?
While `-r 17.7.1 opnsense` won't work because I updated from 17.1.11 directly to 17.7.1?

**Comment by fichtner** [comment]
@Woi no, it's ok, was a just stupid mistake

opnsense-revert reverts given packages to the OPNsense version specified by -r. In this case it would have downgraded the GUI package to 17.7, it's a bit of a dull one. But ideally, if something like Unbound changes for the worse, you can do:

    # opnsense-revert -r 17.7.x unbound

and go back to the particular unbound version shipped with the specified OPNsense release (not the Unbound version). This only works for 2 previous versions usually, we don't keep the releases on the mirror too long.

And this would bring you back to the current version:

    # opnsense-revert unbound


Cheers,
Franco

**Comment by Woi** [comment]
Thanks for clarification
