### ISSUE TITLE
[Feature] Sync config to more than one node

### ISSUE THREAD

**Issue by StrikerTwo** [opnsense/core#1805]
Syncing the config to a second OPNsense box works quite well. I use this to globally define aliases and general firewall rules, and to sync certificates for manual failover.

It would be nice if I could sync the config to more than one node / IP address. Then I could have one box as central admin node where all the configuration is done, and several "front-end" boxes that just do the work.

I have not tried this, but I guess daisy-chaining one box to the next would not work, because as soon as I enter an IP address it stops receiving configuration syncs - correct?

**Comment by AdSchellevis** [comment]
The xmlrpc service will likely work, but I don't think you receive a trigger when updates arrive (and thus they won't be pushed to other nodes). 

For safety it's probably better to keep it a master slave, but it may need quite some work to implement properly (e.g. the status page uses the same information too and how about the accounts used on the various machines).

**Comment by StrikerTwo** [comment]
Okay, it's just a nice-to-have for me. If it's too much work then forget about it ;)

**Comment by StrikerTwo** [comment]
@AdSchellevis Can I ask to move this up again?

We have expanded quite a bit and it would be really really nice to have more than one slave for XMLRPC sync. Either by daisy chaining (as I understand it all that would be needed is to trigger the sync when updates arrive) or by entering more than one IP address as backup machine.

Aliases and FW rules are bad enough, but the real pain is the LetsEncrypt certificates which need to be distributed to the other nodes regularly.

**Comment by AdSchellevis** [comment]
@StrikerTwo I'm not sure xmlrpc will be the standard option to do this in the long run, we refactored it to keep it functional, but expanding it is certainly not high on my list of things todo. 

At the moment there's nobody working on this, things may change in time if one of our customers need something similar, but opening the issue again without an owner doesn't seem to be a good idea at the time.

**Comment by StrikerTwo** [comment]
Fair enough. Just wanted to tell you that it's not just a nice-to-have for me anymore ;)

**Comment by StrikerTwo** [comment]
Or is there any other way to get the LetsEncrypt certs from one OPNsense installation to another automatically?
Can I do a backup and selective restore via API?
