### ISSUE TITLE
Captive Portal sessions after reboot

### ISSUE THREAD

**Issue by greenvespa** [opnsense/core#1807]
As discussed here https://forum.opnsense.org/index.php?topic=5907.0 I open this ticket for a problem that I have everytime I reboot Opnsense firewall: users connected to wifi network through Captive Portal (with Radius Authentication) needs to logout from Captive Portal and login again because network connection doesn't work.
I checked my actual RAM disk configuration here https://my-opnsense-host/system_advanced_misc.php and I can confirm that /var/RAM disk and /tmp RAM disk are both UNCHECKED (so I think disabled)
It's very annoying for my users. If I need to reboot they lose wifi connection, I try to give more informations: they keep connected to our wifi network, but there's no traffic. The only solution is Logout from Captive Portal and login again.

**Comment by fichtner** [comment]
@AdSchellevis when you have a bit of time, can you give an assessment? thanks!

**Comment by AdSchellevis** [comment]
@fichtner As long as the database isn't corrupted, it should list the users in /ui/captiveportal/session/ after a reboot and automatically unlock those users too.

Things to check on the box:
1)  is the database populated with the actual users after a reboot
2) if so, does the ip address still match

I don't expect this to be a structural problem, tested it on my machine and all looks normal from here.
