### ISSUE TITLE
Feature request OpenVPN client profile import

### ISSUE THREAD

**Issue by squadramunter** [opnsense/core#1808]
It should be awesome if there is a simple way to import a client configuration file so the right settings are set on the right place. For customers who do not have much knowledge about VPN. Maybe something like this? Import Button near client export > profile settings imported by the right scheme and placed like you do it on the manual way > save the client profile with a name and add description for it > your router has now a tunneled VPN connection. I don't know if a VPN disturb the way IDS and IPS services works. So the IP can be listed on the router for incoming connections. But it would be nice if it works.

**Comment by AdSchellevis** [comment]
Personally I don't think it's very useful opening issues in different repositories for the exact same question, but let me repeat my last comment and close your other one https://github.com/opnsense/plugins/issues/255:

> Unfortunately you have to import your settings manually, creating an automatic import which maps the ovpn format back to the fields we use will likely be very prune to errors.... (and most of the time the settings needed are quite basic).

Next time, please be so kind to cleanup your duplicates.....

**Comment by squadramunter** [comment]
is there not another option to do this like i did on my raspberry pi? `sudo openvpn --config "/etc/openvpn/vyprvpn/USA - San Francisco.ovpn" --auth-user-pass /etc/openvpn/auth.txt`

**Comment by fichtner** [comment]
in theory something like this could be done by adding a client config file option and disabling all generation of the file just using the stored one as is, but on the other hand not sure how much debug and support effort that will cost on the long run. it looks simple now, but people may expect more features, better debugging and post-import editing.

**Comment by AdSchellevis** [comment]
You can always do it manually, create a script for it and use our available plugin hooks for startup. (just remember to add the openvpn interface to the openvpn interface group so the rules apply).

For some inspiration for a custom script, see https://github.com/opnsense/core/blob/17.7.1/src/etc/inc/plugins.inc.d/openvpn.inc#L522 

and syshook, for startup
https://github.com/opnsense/core/blob/17.7.1/src/etc/rc.syshook.d/95-beep.start

**Comment by kersvanbinsbergen** [comment]
Great feature request.

To bad it still isn't implemented
