### ISSUE TITLE
Remote Access Control Lists Bug?

### ISSUE THREAD

**Issue by Stephanowicz** [opnsense/core#1812]
Hi,

I wanted to add a new ACL (from UT as in the example) but it does not work at all.
Before I had successfully configured the ACL from shallalist.
But now, the new settings won't get applied - even if I delete **ALL** lists it still loads the shallalist!
So the tab for the remote acl is not consistent with the settings behind - I found out that the settings won't get updated in the _/usr/local/etc/squid/externalACLs.conf_ 

How can I fix this behaviour?

Cheers,

Stephan

**Comment by AdSchellevis** [comment]
did you hit apply? 
if so, please check logs first (system->Log file) for anything unusual.

**Comment by Stephanowicz** [comment]
this shows up:

> configd.py: [cb87ff1c-3444-4afa-9e37-94fffdd451bf] Inline action failed with OPNsense/Proxy OPNsense/Proxy/squid.conf 'collections.OrderedDict object' has no attribute 'ipaddr' at Traceback (most recent call last): File "/usr/local/opnsense/service/modules/processhandler.py", line 505, in execute return ph_inline_actions.execute(self, inline_act_parameters) File "/usr/local/opnsense/service/modules/ph_inline_actions.py", line 50, in execute filenames = tmpl.generate(parameters) File "/usr/local/opnsense/service/modules/template.py", line 309, in generate raise render_exception Exception: OPNsense/Proxy OPNsense/Proxy/squid.conf 'collections.OrderedDict object' has no attribute 'ipaddr'

**Comment by Stephanowicz** [comment]
Meanwhile I can see the categories in the acl settings...dunno restarted squid sometimes.
Nevertheless I discovered that the **squid.conf** doesn't get updated, too.
It still has the old entry:
_# ACL - Remote fetched Blacklist (remoteblacklist)
acl remoteblacklist_shallalist dstdomain "/usr/local/etc/squid/acl/shallalist"_

Is it because of the configd.py error from above?

Thanks

**Comment by fabianfrz** [comment]
@Stephanowicz the error in `configd` is a syntax error in the template of squid (proxy) which causes it not being rendered.

**Comment by Stephanowicz** [comment]
O.k. - I found it!
[https://forum.opnsense.org/index.php?topic=4446.0](https://forum.opnsense.org/index.php?topic=4446.0)
If a proxy interface has no ip-address this configd.py error shows up
I've created a bridge and so the network dev no longer has an ip-address...

Thanx & cheers,

Stephan
