### ISSUE TITLE
UTF8 characters shown as web codes.

### ISSUE THREAD

**Issue by ikke-t** [opnsense/core#1813]
At least on /firewall_schedule.php page the text within time range description shows like this:

"edelt&amp;auml;v&amp;auml; ilta"

where as it should be like:

"edeltävä ilta"

[image at paste service](https://pasteboard.co/GJshehp.png)

You can paste the above sample into description field where one can set time ranges, e.g. Fri + Sat 22:00-23:59, description: "edeltävä ilta"

This is the latest version at the moment: OPNsense 17.7.1_2-amd64

**Comment by fichtner** [comment]
Hi @ikke-t,

Thanks for the report. A fix will be available in 17.7.2. You can try it now if you want, run this from the shell:

    # opnsense-patch 283fd7a

The input needs to be redone as it was incorrectly written on save, but now it will not double-encode anymore. :)


Cheers,
Franco

**Comment by ikke-t** [comment]
I verified, it works. Thanks!

**Comment by fichtner** [comment]
Thank you for confirming. 😊
