### ISSUE TITLE
Feature Request: XMPP as a notification option.

### ISSUE THREAD

**Issue by MalakymR** [opnsense/core#1814]
:)

https://xmpp.org/software/libraries.html

**Comment by knxuf** [comment]
maybe even a modular reuseable notification section.

The notification could be outsourced to a script or something like this and be selectable in other modules.

Like email/xmpp/pushover/prowl

The notification options could then be implemented as a plugin and be reused systemwide

**Comment by fichtner** [comment]
We were thinking of making Monit the core notification service. I don't know which methods it supports, but it would be better than coding special notification services around protocol libraries. 😊

**Comment by knxuf** [comment]
Monit do it exact the same way https://mmonit.com/wiki/MMonit/PushoverNotification

Most of the notifications can be made with a simple script (curl)
If we can just make the library of available notification scripts available to the different applications that supports them. They could be easily selected from a dropdown list and used in whatever package that supports notification per script.

**Comment by AdSchellevis** [comment]
timeout
