### ISSUE TITLE
Squid: log name now starts with a module name

### ISSUE THREAD

**Issue by Stephanowicz** [opnsense/core#1815]
Hi,

this warning still shows up:

> WARNING: log name now starts with a module name. Use 'stdio:/var/log/squid/store.log'

To fix it, following additions have to be made in _/usr/local/opnsense/service/templates/OPNsense/Proxy/squid.conf_

in line 338, 340 insert **stdio:** before the path
_access_log stdio:/var/log/squid/access.log squid_ 

also in line 350 for cache_store_log:
_cache_store_log stdio:/var/log/squid/store.log_

Cheers,

Stephan

**Comment by AdSchellevis** [comment]
@Stephanowicz thanks for the report, I will fix and close the issue right away.
