### ISSUE TITLE
Menu: Service section is growing too large

### ISSUE THREAD

**Issue by fabianfrz** [opnsense/core#1817]
Screenshot of my Service Section:

![spectacle vk8761](https://user-images.githubusercontent.com/3713914/30251692-64e72d38-9665-11e7-9091-6c4d7c033cfa.png)

My Notebook has a screen height of 900px.

The Solution could be grouping services by type. Feel free to close if this is inappropriate.

**Comment by StrikerTwo** [comment]
+1.
Could we have an option to disable unneed services, or at least hide them in the menu?
I only need about 50% of the entries there.

**Comment by fichtner** [comment]
Luxury problem... let me see what we can do on our way to 18.1.

The search fields / quick nav works very well with minimal key strokes btw :)

**Comment by StrikerTwo** [comment]
Both true, but still ;)
And/or maybe a "favourite" menu where I could put the top 5 items I need most?

@fabianfrz in a pinch you could also zoom the browser out until you see the entry you want to click.

**Comment by fichtner** [comment]
Favourite menu sounds vaguely familiar. On any install the menu can be changed / transformed using the XML format, but presenting it in a user-friendly way is the challenge here.

**Comment by AdSchellevis** [comment]
You can easily create custom overwrites using our xml menu system, including hiding items which are there... plugins which can be deinstalled solve most "issues"

**Comment by fraenki** [comment]
> The Solution could be grouping services by type.

Grouping has the disadvantage that it adds yet another level to the menu. I don't want a deeply nested menu.

> And/or maybe a "favourite" menu re I could put the top 5 items I need most?

+1 for Favorites menu if it's easy to implement.

> plugins which can be deinstalled solve most "issues"

+1, moving more and more non-core functionality to plugins solves this for basic installs.

**Comment by fichtner** [comment]
@AdSchellevis worked on this in https://github.com/opnsense/core/commit/2b94b6691a and it is a very cool solution.

The only thing that is missing is a style fix:

The active items are shown in grey:

<img width="223" alt="screen shot 2017-11-28 at 8 51 58 am" src="https://user-images.githubusercontent.com/1915288/33308142-9079f448-d419-11e7-966e-50a05a52400f.png">

But in the new overlay they are white, indicating "inactive":

<img width="220" alt="screen shot 2017-11-28 at 8 52 13 am" src="https://user-images.githubusercontent.com/1915288/33308159-9d675b0a-d419-11e7-9473-b408eaf6b9a6.png">

**Comment by AdSchellevis** [comment]
@fichtner that was intentional, grey isn't very obvious in this view. Another solution could be to border or underline the sticky part.

**Comment by fichtner** [comment]
True, maybe less grey markup in general would be better, but not sure what's best yet.

I've also been able to stack "Firewall" or "Interfaces" on top of the menu by doing a few scroll and navigation movements.

<img width="224" alt="screen shot 2017-11-28 at 8 57 00 am" src="https://user-images.githubusercontent.com/1915288/33308422-a0fb5298-d41a-11e7-9ae6-5328f9535c7a.png">

Nothing serious, I like the solution and I'm sure the last few bits can be arranged.


Thank you,
Franco

**Comment by fichtner** [comment]
Good enough, we should retrace if necessary.
