### ISSUE TITLE
configd.py: timeout while updating large squid acls

### ISSUE THREAD

**Issue by Stephanowicz** [opnsense/core#1818]
Hi,

@moment we use some very large acls for squid (e.g from [Université Toulouse ](http://dsi.ut-capitole.fr/blacklists/index_en.php))

now we always get this error from the update process - though the files get downloaded and installed correctly...

> Sep 11 00:45:00 lifesense configd.py: [55550bc2-c9f6-4be8-9bf2-2629be9089b3] download and reload proxy ACLs from remote locations
> Sep 11 00:47:00 lifesense configd_ctl.py: error in configd communication  Traceback (most recent call last):   File "/usr/local/opnsense/service/configd_ctl.py", line 65, in exec_config_cmd     line = sock.recv(65536) timeout: timed out
> Sep 11 00:47:06 lifesense configd.py: unable to sendback response [OK ] for [proxy][fetchacls][None] {55550bc2-c9f6-4be8-9bf2-2629be9089b3}, message was Traceback (most recent call last):   File "/usr/local/opnsense/service/modules/processhandler.py", line 202, in run     self.connection.sendall('%s\n' % result)   File "/usr/local/lib/python2.7/socket.py", line 228, in meth     return getattr(self._sock,name)(*args) error: [Errno 32] Broken pipe
> 

Is there a way to increase the timeout?

(I know it's probably too much effort- though I think it will be helpful also for other tasks, if there's a progress status, like bytes downloaded. The code could check then if there's still a download in progress or the download is stalled... - just an idea ;) )

Cheers,

Stephan

**Comment by AdSchellevis** [comment]
Hi Stephan,

The download usually doesn't consume most of the time, the sorting does and is difficult to measure.

An option is to detach the process and add a call to see if it's still active, but it's not very high on my priority list... it doesn't stop downloading when it timeouts, it only informs you that it won't wait now.

Best regards,

Ad

**Comment by Stephanowicz** [comment]
Hi Ad,

ok, agreed. ;) 
Nevertheless it would feel better, to know that the update progress is monitored and certain actions would be taken if it fails somehow.

Cheers, 
Stephan

**Comment by fichtner** [comment]
@Stephanowicz is this still happening?

**Comment by Stephanowicz** [comment]
@fichtner 
Yep...
```
Jan 19 00:05:00 lifesense configd.py: [f954dbaa-e0cc-414e-aaf4-6996df4e4e7f] Updating squidanalyzer data
Jan 19 00:45:00 lifesense configd.py: [eacd87f8-9af2-4c88-bc7d-757f8ed41d17] download and reload proxy ACLs from remote locations
Jan 19 00:47:00 lifesense configd_ctl.py: error in configd communication  Traceback (most recent call last):   File "/usr/local/opnsense/service/configd_ctl.py", line 65, in exec_config_cmd     line = sock.recv(65536) timeout: timed out
Jan 19 00:47:11 lifesense configd.py: unable to sendback response [OK ] for [proxy][fetchacls][None] {eacd87f8-9af2-4c88-bc7d-757f8ed41d17}, message was Traceback (most recent call last):   File "/usr/local/opnsense/service/modules/processhandler.py", line 202, in run     self.connection.sendall('%s\n' % result)   File "/usr/local/lib/python2.7/socket.py", line 228, in meth     return getattr(self._sock,name)(*args) error: [Errno 32] Broken pipe
Jan 19 01:05:00 lifesense configd.py: [a9c70b3d-f15c-4129-9e23-715f27857597] Updating squidanalyzer data
```

**Comment by fichtner** [comment]
not great, but thanks for the quick response. I've tagged it accordingly. We have made some changes to the general service handling workflow of plugins (and the web proxy as a core component plugin) so it is time to look a bit further to other edge cases like this.

**Comment by AdSchellevis** [comment]
There's not an awful lot we can do here, either we loose feedback in normal operations if we background the task:

https://github.com/opnsense/core/blob/0672cd0483febdda7171e303ad73e6989d56150e/src/opnsense/mvc/app/views/OPNsense/Proxy/index.volt#L205-L216

Or if the machine can't keep up, we might signal the user that we cannot send the message back (which in other scenarios is quite practical to know):

https://github.com/opnsense/core/blob/0672cd0483febdda7171e303ad73e6989d56150e/src/opnsense/service/modules/processhandler.py#L219-L228
