### ISSUE TITLE
System error Reporter

### ISSUE THREAD

**Issue by squadramunter** [opnsense/core#1819]
System Information:

User-Agent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36
FreeBSD 11.0-RELEASE-p12 #0 02581be96(stable/17.7): Sat Aug 26 11:00:39 CEST 2017     root@sensey64:/usr/obj/usr/src/sys/SMP
OPNsense 17.7.1_2-ad244dbba [17.7-7c9539338] LibreSSL 2.5.5 (amd64)
Time Mon, 11 Sep 2017 21:17:55 +0200

dmesg.boot:

Copyright (c) 1992-2016 The FreeBSD Project.
Copyright (c) 1979, 1980, 1983, 1986, 1988, 1989, 1991, 1992, 1993, 1994
	The Regents of the University of California. All rights reserved.
FreeBSD is a registered trademark of The FreeBSD Foundation.
FreeBSD 11.0-RELEASE-p12 #0 02581be96(stable/17.7): Sat Aug 26 11:00:39 CEST 2017
    root@sensey64:/usr/obj/usr/src/sys/SMP amd64
FreeBSD clang version 3.8.0 (tags/RELEASE_380/final 262564) (based on LLVM 3.8.0)
VT(vga): resolution 640x480
[HBSD ASLR] status: opt-out
[HBSD ASLR] mmap: 30 bit
[HBSD ASLR] exec base: 30 bit
[HBSD ASLR] stack: 42 bit
[HBSD ASLR] vdso: 28 bit
[HBSD ASLR] map32bit: 18 bit
[HBSD ASLR] disallow MAP_32BIT mode mmap: opt-out
[HBSD ASLR (compat)] status: opt-out
[HBSD ASLR (compat)] mmap: 14 bit
[HBSD ASLR (compat)] exec base: 14 bit
[HBSD ASLR (compat)] stack: 14 bit
[HBSD ASLR (compat)] vdso: 8 bit
[HBSD HARDENING] procfs hardening: enabled
[HBSD LOG] logging to system: enabled
[HBSD LOG] logging to user: disabled
[HBSD SEGVGUARD] status: opt-out
[HBSD SEGVGUARD] expiry: 120 sec
[HBSD SEGVGUARD] suspension: 600 sec
[HBSD SEGVGUARD] maxcrashes: 5
CPU: Pentium(R) Dual-Core  CPU      E5300  @ 2.60GHz (2593.84-MHz K8-class CPU)
  Origin="GenuineIntel"  Id=0x1067a  Family=0x6  Model=0x17  Stepping=10
  Features=0xbfebfbff
  Features2=0xc00e3bd
  AMD Features=0x20100800
  AMD Features2=0x1
  VT-x: HLT,PAUSE
  TSC: P-state invariant, performance statistics
real memory  = 4294967296 (4096 MB)
avail memory = 4050706432 (3863 MB)
Event timer "LAPIC" quality 400
ACPI APIC Table: <093009 APIC2248>
FreeBSD/SMP: Multiprocessor System Detected: 2 CPUs
FreeBSD/SMP: 1 package(s) x 2 core(s)
random: unblocking device.
ACPI BIOS Warning (bug): 32/64X length mismatch in FADT/Gpe0Block: 128/64 (20160527/tbfadt-650)
ioapic0  irqs 0-23 on motherboard
random: entropy device external interface
wlan: mac acl policy registered
netmap: loaded module
module_register_init: MOD_LOAD (vesa, 0xffffffff81149b90, 0) error 19
kbd1 at kbdmux0
vtvga0:  on motherboard
cryptosoft0:  on motherboard
acpi0:  on motherboard
acpi0: Power Button (fixed)
cpu0:  on acpi0
cpu1:  on acpi0
attimer0:  port 0x40-0x43 irq 0 on acpi0
Timecounter "i8254" frequency 1193182 Hz quality 0
Event timer "i8254" frequency 1193182 Hz quality 100
atrtc0:  port 0x70-0x71 irq 8 on acpi0
Event timer "RTC" frequency 32768 Hz quality 0
hpet0:  iomem 0xfed00000-0xfed003ff on acpi0
Timecounter "HPET" frequency 14318180 Hz quality 950
Event timer "HPET" frequency 14318180 Hz quality 450
Event timer "HPET1" frequency 14318180 Hz quality 440
Event timer "HPET2" frequency 14318180 Hz quality 440
Event timer "HPET3" frequency 14318180 Hz quality 440
Timecounter "ACPI-fast" frequency 3579545 Hz quality 900
acpi_timer0: <24-bit timer at 3.579545MHz> port 0x808-0x80b on acpi0
pcib0:  port 0xcf8-0xcff on acpi0
pci0:  on pcib0
vgapci0:  port 0xcc00-0xcc07 mem 0xfe400000-0xfe7fffff,0xd0000000-0xdfffffff irq 16 at device 2.0 on pci0
agp0:  on vgapci0
agp0: aperture size is 256M, detected 32764k stolen memory
vgapci0: Boot video device
vgapci1:  mem 0xfe800000-0xfe8fffff at device 2.1 on pci0
em0:  port 0xc880-0xc89f mem 0xfe9c0000-0xfe9dffff,0xfe9fa000-0xfe9fafff irq 20 at device 25.0 on pci0
em0: Using an MSI interrupt
em0: Ethernet address: 00:26:2d:11:8c:ad
em0: netmap queues/slots: TX 1/1024, RX 1/1024
uhci0:  port 0xc800-0xc81f irq 16 at device 26.0 on pci0
uhci0: LegSup = 0x2f00
usbus0 on uhci0
uhci1:  port 0xc480-0xc49f irq 21 at device 26.1 on pci0
uhci1: LegSup = 0x2f00
usbus1 on uhci1
uhci2:  port 0xc400-0xc41f irq 19 at device 26.2 on pci0
uhci2: LegSup = 0x2f00
usbus2 on uhci2
ehci0:  mem 0xfe9f8000-0xfe9f83ff irq 18 at device 26.7 on pci0
usbus3: EHCI version 1.0
usbus3 on ehci0
hdac0:  mem 0xfe9f0000-0xfe9f3fff irq 22 at device 27.0 on pci0
pcib1:  irq 17 at device 28.0 on pci0
pcib1: [GIANT-LOCKED]
pci1:  on pcib1
pci1:  at device 0.0 (no driver attached)
pcib2:  irq 16 at device 28.1 on pci0
pcib2: [GIANT-LOCKED]
pci2:  on pcib2
re0:  port 0xe800-0xe8ff mem 0xfebff000-0xfebfffff,0xfdffc000-0xfdffffff irq 17 at device 0.0 on pci2
re0: Using Memory Mapping!
re0: Using 1 MSI-X message
re0: version:1.93
re0: Ethernet address: 18:d6:c7:03:e5:72

This product is covered by one or more of the following patents:            
US6,570,884, US6,115,776, and US6,327,625.
re0: Ethernet address: 18:d6:c7:03:e5:72
uhci3:  port 0xc080-0xc09f irq 23 at device 29.0 on pci0
uhci3: LegSup = 0x2f00
usbus4 on uhci3
uhci4:  port 0xc000-0xc01f irq 19 at device 29.1 on pci0
uhci4: LegSup = 0x2f00
usbus5 on uhci4
uhci5:  port 0xbc00-0xbc1f irq 18 at device 29.2 on pci0
uhci5: LegSup = 0x2f00
usbus6 on uhci5
ehci1:  mem 0xfe9ee000-0xfe9ee3ff irq 23 at device 29.7 on pci0
usbus7: EHCI version 1.0
usbus7 on ehci1
pcib3:  at device 30.0 on pci0
pci3:  on pcib3
isab0:  at device 31.0 on pci0
isa0:  on isab0
ahci0:  port 0xb880-0xb887,0xb800-0xb803,0xb480-0xb487,0xb400-0xb403,0xb080-0xb09f mem 0xfe9ec000-0xfe9ec7ff irq 19 at device 31.2 on pci0
ahci0: AHCI v1.20 with 6 3Gbps ports, Port Multiplier not supported
ahcich0:  at channel 0 on ahci0
ahcich1:  at channel 1 on ahci0
ahcich2:  at channel 2 on ahci0
ahcich3:  at channel 3 on ahci0
ahcich4:  at channel 4 on ahci0
ahcich5:  at channel 5 on ahci0
ahciem0:  on ahci0
acpi_button0:  on acpi0
orm0:  at iomem 0xcc800-0xcd7ff on isa0
atkbdc0:  at port 0x60,0x64 on isa0
atkbd0:  irq 1 on atkbdc0
kbd0 at atkbd0
atkbd0: [GIANT-LOCKED]
ppc0: cannot reserve I/O port range
est0:  on cpu0
est1:  on cpu1
Timecounters tick every 1.000 msec
nvme cam probe device init
hdacc0:  at cad 2 on hdac0
hdaa0:  at nid 1 on hdacc0
pcm0:  at nid 20,22,21,27 and 24,25,26 on hdaa0
pcm1:  at nid 30 on hdaa0
hdacc1:  at cad 3 on hdac0
hdaa1:  at nid 1 on hdacc1
pcm2:  at nid 3 on hdaa1
usbus0: 12Mbps Full Speed USB v1.0
usbus1: 12Mbps Full Speed USB v1.0
usbus2: 12Mbps Full Speed USB v1.0
ugen0.1:  at usbus0
uhub0:  on usbus0
ugen1.1:  at usbus1
uhub1:  on usbus1
ugen2.1:  at usbus2
uhub2:  on usbus2
usbus3: 480Mbps High Speed USB v2.0
usbus4: 12Mbps Full Speed USB v1.0
usbus5: 12Mbps Full Speed USB v1.0
ugen3.1:  at usbus3
uhub3:  on usbus3
ugen4.1:  at usbus4
uhub4:  on usbus4
ugen5.1:  at usbus5
uhub5:  on usbus5
usbus6: 12Mbps Full Speed USB v1.0
usbus7: 480Mbps High Speed USB v2.0
ugen6.1:  at usbus6
uhub6:  on usbus6
ugen7.1:  at usbus7
uhub7:  on usbus7
ses0 at ahciem0 bus 0 scbus6 target 0 lun 0
ses0:  SEMB S-E-S 2.00 device
ses0: SEMB SES Device
ada0 at ahcich3 bus 0 scbus3 target 0 lun 0
ada0:  ACS-2 ATA SATA 3.x device
ada0: Serial Number WD-WCC4J2LTAJS4
ada0: 300.000MB/s transfers (SATA 2.x, UDMA6, PIO 8192bytes)
ada0: Command Queueing enabled
ada0: 953869MB (1953525168 512 byte sectors)
ada0: quirks=0x1<4K>
SMP: AP CPU #1 Launched!
cd0 at ahcich0 bus 0 scbus0 target 0 lun 0
cd0:  Removable CD-ROM SCSI device
cd0: 150.000MB/s transfers (SATA 1.x, UDMA5, ATAPI 12bytes, PIO 8192bytes)
cd0: Attempt to query device size failed: NOT READY, Medium not present - tray closed
Timecounter "TSC-low" frequency 1296920735 Hz quality 1000
Trying to mount root from ufs:/dev/ada0s1a [rw]...
uhub0: 2 ports with 2 removable, self powered
uhub1: 2 ports with 2 removable, self powered
uhub2: 2 ports with 2 removable, self powered
uhub4: 2 ports with 2 removable, self powered
uhub5: 2 ports with 2 removable, self powered
uhub6: 2 ports with 2 removable, self powered
uhub3: 6 ports with 6 removable, self powered
uhub7: 6 ports with 6 removable, self powered
ugen7.2:  at usbus7
umass0:  on usbus7
umass0:  SCSI over Bulk-Only; quirks = 0x4001
umass0:7:0: Attached to scbus7
da0 at umass-sim0 bus 0 scbus7 target 0 lun 0
da0:  Removable Direct Access SCSI device
da0: Serial Number 058F63636476
da0: 40.000MB/s transfers
da0: Attempt to query device size failed: NOT READY, Medium not present
da0: quirks=0x2
da1 at umass-sim0 bus 0 scbus7 target 0 lun 1
da1:  Removable Direct Access SCSI device
da1: Serial Number 058F63636476
da1: 40.000MB/s transfers
da1: Attempt to query device size failed: NOT READY, Medium not present
da1: quirks=0x2

/var/crash/info.0:

Dump header from device: /dev/ada0s1b
  Architecture: amd64
  Architecture Version: 2
  Dump Length: 706195456
  Blocksize: 512
  Dumptime: Sun Sep 10 11:19:11 2017
  Hostname: OPNsense.localdomain
  Magic: FreeBSD Kernel Dump
  Version String: FreeBSD 11.0-RELEASE-p12 #0 02581be96(stable/17.7): Sat Aug 26 11:00:39 CEST 2017
    root@sensey64:/usr/obj/usr/src/sys/SMP
  Panic String: sleeping thread
  Dump Parity: 2902257935
  Bounds: 0
  Dump Status: good

**Comment by fichtner** [comment]
The only thing I see here is "sleeping thread". Everything else is boilerplate.

No idea how to narrow this down.

**Comment by squadramunter** [comment]
I don't know how but sometimes when I start my router there is internet connection for like 30 minutes but when I come back after 30 minutes and want to surf the web the connection is broken. Does it appears to be a suspended mode? it's really annoying and I need to restart my router to solve this issue over and over. I have latest updates installed. Anybody a clue how this gonna happen? I have one build in ethernet port and a PCI-e TP-LINK TG-3468. How to solve this issue?

**Comment by fichtner** [comment]
What hardware is this? Do you have access to a monitor or serial console when this happens so we can see the actual error?

**Comment by squadramunter** [comment]
Eh I use currently a HDMI connection but it is installed fine. when I have installed the router I just use SSH and putty to remotely controll my router.

**Comment by fichtner** [comment]
The error would be on the HDMI display I think.

**Comment by squadramunter** [comment]
Don't know It's not connected and I used it only when I had to install the router.
Further on I used putty to setup the configuration part off the router.

**Comment by fichtner** [comment]
The error won't be reachable via ssh if ssh locks down, that's all I am trying to say. So if we want to see the error which is the only thing that can help we need to see it on the hdmi output.

**Comment by squadramunter** [comment]
Ah okay. is there a way to copy the system log to a text file and send that to you? When I am connected to HDMI my screen is overlapping the text.

**Comment by fichtner** [comment]
a picture is enough, you can drag+drop to github. if you get a ddb prompt also type "bt" and hit enter to get a picture of the backtrace. Thanks in advance.

**Comment by squadramunter** [comment]
What command do I need to use for that? Is it on SSH or on the main router page?

**Comment by fichtner** [comment]
just the console and a keyboard... it'll be the error prompt on the screen, nothing you can login to.

**Comment by squadramunter** [comment]
I have not COM port on my PC. so I can't connect to the console. VGA is not working because I have only HDMI and HDMI is getting some text overlapping I use my LCD Philips TV for that.

**Comment by fichtner** [comment]
I want to say that will not help us track down the issue any further. Can you share the hardware specs / device model with us for reference?

**Comment by squadramunter** [comment]
Acer Aspire AX3811

**Comment by squadramunter** [comment]
Sep 12 18:26:25 | dhclient[68778]: bound to 192.168.2.30 -- renewal in 2147483647 seconds.
-- | --
Sep 12 18:26:25 | dhclient: Creating resolv.conf
Sep 12 18:26:25 | dhclient: /sbin/route add default 192.168.2.254
Sep 12 18:26:25 | dhclient: Adding new routes to interface: em0
Sep 12 18:26:25 | dhclient: New Routers (em0): 192.168.2.254
Sep 12 18:26:25 | dhclient: New Broadcast Address (em0): 192.168.2.255
Sep 12 18:26:25 | dhclient: New Subnet Mask (em0): 255.255.255.0
Sep 12 18:26:25 | dhclient: New IP Address (em0): 192.168.2.30
Sep 12 18:26:25 | dhclient: ifconfig em0 inet 192.168.2.30 netmask 255.255.255.0 broadcast 192.168.2.255
Sep 12 18:26:25 | dhclient: Starting add_new_address()
Sep 12 18:26:25 | dhclient: Comparing IPs: Old: 192.168.2.30 New: 192.168.2.30
Sep 12 18:26:25 | dhclient: Starting delete_old_states()
Sep 12 18:26:25 | dhclient: REBOOT
Sep 12 18:26:25 | dhclient[68778]: unknown dhcp option value 0x7d
Sep 12 18:26:25 | dhclient[68778]: DHCPACK from 192.168.2.254
Sep 12 18:26:25 | dhclient[68778]: DHCPREQUEST on em0 to 255.255.255.255 port 67
Sep 12 18:26:24 | dhclient[68778]: DHCPREQUEST on em0 to 255.255.255.255 port 67
Sep 12 18:26:24 | dhclient: Removing states from old IP '192.168.2.30' (new IP '')
Sep 12 18:26:24 | dhclient: Comparing IPs: Old: 192.168.2.30 New:

I saw this error unknown dhcp option value 0x7d

**Comment by squadramunter** [comment]
I think this is a problem with the NIC card on my PCI-e slot. but somewhere Opnsense is not able to configure it on the right way.

**Comment by squadramunter** [comment]
Tried PfSense and that worked for me. But like OpnSense more than PfSense

**Comment by fichtner** [comment]
Pfsense 2.3 or 2.4?

**Comment by fichtner** [comment]
If re0 is the problematic one, you could switch it out. I don't think they will be any better in the future and lots of people have said their issues disappeared after getting rid of Realtek NICs.

**Comment by squadramunter** [comment]
Ah okay but that's strange that there is no fix for it.

**Comment by squadramunter** [comment]
I added a tunable with name if_re_load and value YES and hope that it will fixed now. I will see if the connection did not drop. I even did this trick ifconfig re0 -tso

**Comment by squadramunter** [comment]
Update:

root@OPNsense:~ # dmesg | grep re0
re0: <Realtek PCIe GBE Family Controller> port 0xe800-0xe8ff mem 0xfebff000-0xfe                                                                                                             bfffff,0xfdffc000-0xfdffffff irq 17 at device 0.0 on pci2
re0: Using Memory Mapping!
re0: Using 1 MSI-X message
re0: version:1.93
re0: Ethernet address: 18:d6:c7:03:e5:72
re0: Ethernet address: 18:d6:c7:03:e5:72
re0: link state changed to UP
re0: link state changed to DOWN
re0: link state changed to UP
re0: link state changed to DOWN
re0: link state changed to UP
ifa_maintain_loopback_route: deletion failed for interface re0: 3
ifa_maintain_loopback_route: deletion failed for interface re0: 3
re0: link state changed to DOWN
re0: link state changed to UP
re0: <Realtek PCIe GBE Family Controller> port 0xe800-0xe8ff mem 0xfebff000-0xfe                                                                                                             bfffff,0xfdffc000-0xfdffffff irq 17 at device 0.0 on pci2
re0: Using Memory Mapping!
re0: Using 1 MSI-X message
re0: version:1.93
re0: Ethernet address: 18:d6:c7:03:e5:72
re0: Ethernet address: 18:d6:c7:03:e5:72
re0: link state changed to UP
re0: <Realtek PCIe GBE Family Controller> port 0xe800-0xe8ff mem 0xfebff000-0xfe                                                                                                             bfffff,0xfdffc000-0xfdffffff irq 17 at device 0.0 on pci2
re0: Using Memory Mapping!
re0: Using 1 MSI-X message
re0: version:1.93
re0: Ethernet address: 18:d6:c7:03:e5:72
re0: Ethernet address: 18:d6:c7:03:e5:72
re0: link state changed to UP
ifa_maintain_loopback_route: deletion failed for interface re0: 3

**Comment by squadramunter** [comment]
Do you guys have this file? kernel-17.1.1-re-amd64.txz so I can update it? 

opnsense-update -kr 17.1.1-re

**Comment by squadramunter** [comment]
Okay I fixed this problem using a tunable also As written in another thread dont tick "Disable preempt" on both FWs and set a tunable of net.inet.carp.senderr_demotion_factor=0 on both firewalls. Reboot and you're good

**Comment by squadramunter** [comment]
Now this stupid error is gone. ifa_maintain_loopback_route: deletion failed for interface re0: 3

**Comment by harrypnyce** [comment]
I've continued to receive same/similar errors as above.  Almost certainly related to our shoddy eMachines hardware.  Acer has gotten better in recent memory, but this is kind of painful.  Going to attempt this [workaround](https://github.com/opnsense/tools/issues/28#issue-151053710).

`umass0: SCSI over Bulk-Only; quirks = 0x4001`
