### ISSUE TITLE
Login issue Input Field.

### ISSUE THREAD

**Issue by squadramunter** [opnsense/core#1824]
Got few times when I selecting the username and password box that the input field is not responding correctly. After a few times refreshing my browser it works.

Sounds like a Bug in the Web UI.

**Comment by L1ghtn1ng** [comment]
I have had this issue as well in chrome on android and I think it's a chrome problem.


________________________________

**Comment by mimugmail** [comment]
Same here for Chrome, but only a few OPN, not all

**Comment by fichtner** [comment]
What does it mean, "not responding correctly" ? I never had issues with Chrome, Firefox and Safari on the login page in the last couple of years.

**Comment by L1ghtn1ng** [comment]
Its the most up to date version of chrome on android and is version 7.1.2 nexus 6


________________________________

**Comment by mimugmail** [comment]
@fichtner It means that there's no flashing cursor when you tick in login or pw field.
Since it was only on a dev system I didn't dig further into it. Perhaps some cache issue with Chrome.

**Comment by fichtner** [comment]
Ok, I think I've seen this too once or twice, but we don't have any javascript so everything that happens is browser/OS related. I vote for close ;)

**Comment by fichtner** [comment]
What I meant to say was I've seen this too, but that wasn't limited to OPNsense. Maybe that is clearer now.

**Comment by mimugmail** [comment]
I cleared the cache in Chrome and the cursor is there again.
@squadramunter Can you check this and close if it fixes?

**Comment by fichtner** [comment]
Yesterday I saw this in a non-bootstrap perl-backed web frontend. I really don't think there is anything we can do.
