### ISSUE TITLE
SURICATA: bug when converting commented out alerts to "drop"

### ISSUE THREAD

**Issue by Stephanowicz** [opnsense/core#1825]
Hi,

the lists of emergingthreats often contain rules that are commented out 

> #alert http $HOME_NET any -> $EXTERNAL_NET

when changing 'all alerts to drop actions' these will get converted to

> drop **t** http ...

resulting in errormessages

> <Error> - [ERRCODE: SC_ERR_UNKNOWN_PROTOCOL(124)] - protocol "t" cannot be used in a signature.

I don't know why these rules are commented out - but this case has to be taken care of when changing from alert to drop.

Thank You & cheers,

Stephan

**Comment by fichtner** [comment]
Hi Stephan,

Looks like it tries to remove "alert" as seven characters from the beginning of the stream. Not sure where this is, somewhere in src/opnsense/scripts/suricata I think, but handing over to Ad for assessment.


Cheers,
Franco

**Comment by AdSchellevis** [comment]
I can't check it right now, but the logic is here https://github.com/opnsense/core/blob/master/src/opnsense/scripts/suricata/lib/downloader.py#L62-L66

**Comment by fichtner** [comment]
https://github.com/opnsense/core/blob/master/src/opnsense/scripts/suricata/lib/downloader.py#L66

copy+paste issue, should probably be [6:]

**Comment by fichtner** [comment]
@Stephanowicz please try this:

    # opnsense-patch 105fb5b

**Comment by Stephanowicz** [comment]
Perfect!

Thanks again ;)

**Comment by fichtner** [comment]
yay, thanks for confirming
