### ISSUE TITLE
NTP: remove obsolete RRD setting 

### ISSUE THREAD

**Issue by Woi** [opnsense/core#1826]
Hey, 

I found this "NTP graphs" option on `/services_ntpd.php` to do nothing if enabled. Explanation is 
> Enable rrd graphs of NTP statistics (default: disabled)

It seems RRD was removed a long time ago [1,2]. So I guess this option and the code behind it should be removed as well.

[1] https://forum.opnsense.org/index.php?topic=1795
[2] https://forum.opnsense.org/index.php?topic=1852.0

**Comment by fichtner** [comment]
It's still there under Reporting: Health, it got a fresh frontend.


Cheers,
Franco

**Comment by Woi** [comment]
Thanks for clarification. It just takes some time for the data to show up. Closing since this is not a bug

**Comment by Woi** [comment]
Have a nice weekend :)

**Comment by fichtner** [comment]
you too :)
