### ISSUE TITLE
CRL- revoke: Failed to set compromise time

### ISSUE THREAD

**Issue by knxuf** [opnsense/core#1827]
FW: 17.7.2

Error revoking certificate.

Steps to reproduce:
create CRL (if not already):
edit crl: revoke cert.

PS: the already revoked certificates also shouldn't be in the dropdown list

`
Warning: openssl_crl_revoke_cert(): Failed to set compromise time in /usr/local/etc/inc/certs.inc on line 562

Warning: openssl_crl_revoke_cert(): Failed to revoke certificate in /usr/local/etc/inc/certs.inc on line 562
-----BEGIN X509 CRL-----
MIIBzzCBuAIBATANBgkqhkiG9w0BAQUFADB1MQswCQYDVQQGEwJERTEMMAoGA1UE
CAwDTmRzMRIwEAYDVQQHDAlJbnRlcndlYnoxETAPBgNVBAoMCE92ZXJzZWFzMR4w
HAYJKoZIhvcNAQkBFg9wcm94eUBpbnRlcndlYnoxETAPBgNVBAMMCFByb3h5IENB
Fw0xNzA5MTQxMzIzNThaFw00NTAxMjkxMzIzNThaoA8wDTALBgNVHRQEBAICJxEw
DQYJKoZIhvcNAQEFBQADggEBACjZriEAiZehTkUyL3d5BUOETkuXbbVGf12Dd2Xj
AVok0xZnenMixZYFMGO1OysOeuqIoIh4gP6Kg1zuKVyprrZmjaaBMRccom9urZj3
S4YwVQL4pjxK10BAsQOjVcrfuYaUAQuNilR92LVGba7ZJ2`

**Comment by knxuf** [comment]
Could we also have an unauthorized http(s) url for the crl to import on other devices?

Also it would be nice to import crls from url and update per cron.

CAs / CA CSR generated on opnSense could also embed the crl distribution point (hostname field needed)

**Comment by fichtner** [comment]
I can't reproduce the revoke failures for compromise time. But what is possible is fixing the "PS" note.

**Comment by fichtner** [comment]
This patch should help to clean up the certs-to-revoke selection:

    # opnsense-patch 020010f

Failed compromise time sounds like a problem with the clock, probably crl date before issue date or something... use NTP if possible, this shouldn't happen.


Cheers,
Franco

**Comment by fichtner** [comment]
Done
