### ISSUE TITLE
Connectivity bug related to "Enable Static ARP entries" Option in the DHCP section

### ISSUE THREAD

**Issue by fionnb** [opnsense/core#1828]
I struggled with a problem for some time where one of my vLans constantly lost WAN connectivity after varying periods of time. A reboot fixed the problem but it always came back, sometimes after two hours, sometimes after two days. After trying around a lot I finally found out that disabling the static ARP entries option for DHCP made the problem go away. Since all clients on that vLAN _do have_ static leases with static arp enabled and sometimes it works and sometimes not I suspect there is a bug there to be fixed.

Problem occurred on 17.1 as well as 17.7 and 17.7.1

Steps to reproduce my use case:

- Create a trunked interface with at least 2 tagged vLans on it (maybe a regular interfaces are sufficient but I do not have a spare one to test with)
- at least one vLAN interface (A) gets a default WAN route so devices on it have WAN access
- at least one vLAN interface (B)
  - does not get a default WAN route
  - has at least one client with static DHCP lease, static ARP and its own WAN route
  - has "Enable Static ARP entries" Option enabled globally for that interface

You may find a more detailed description of the proceedings in [this opnsense forum thread](https://forum.opnsense.org/index.php?topic=5888.0).
Now sit and wait and (hopefully) watch the client on B lose all connectivity after some time. It can not even be reached from the router then (see forum thread).

**Comment by AdSchellevis** [comment]
Timeout

**Comment by JOduMonT** [comment]
![image](https://user-images.githubusercontent.com/5204724/73128932-7f6e3100-400a-11ea-852e-cfcd7f301b58.png)

My comment is just to be sure nobody open an issue about this because he/she also assume or expect a different result:

*as @AdSchellevis mentioned [there](https://github.com/opnsense/core/issues/3894#issuecomment-578389520)*

> Warning: This option persists even if DHCP server is disabled. Only the machines listed below will be able to communicate with the firewall on this NIC.
