### ISSUE TITLE
adding group with existing name overwrites system group

### ISSUE THREAD

**Issue by corin33** [opnsense/core#183]
When adding a new group via the webconfigurator, it is possible to create groups which already exist on the system, like `wheel`. This leads to the following behaviour:
* The new group gets added to `/etc/group` with a GID of 2000+x, so we have two groups with the same name.
* If the group gets deleted via the webconfigurator, the 'original' system group gets deleted from `/etc/group`, the entry with GID 2000+x stays there. The same happens after a reboot.
So the system group is effectively overwritten. In the case of `wheel`, root is no longer member of wheel, and all the file with GID 0 no longer belong to anyone.

This may be related to #71.

**Possible workaround/fix:**
Prohibit creation of groups with names already present in `/etc/group`.

I stumbled upon this while trying to configure sudo. I'll just use the group `sudoers` instead of `wheel` :smiley:.

**Comment by AdSchellevis** [comment]
It seemed that the user manager checked for that, but the groups didn't. It should be fixed in https://github.com/opnsense/core/commit/69fe3b29314f15782ce2ed9ef6c999f8817d8fa4 
Thanks for reporting.
