### ISSUE TITLE
Feature request: ARP flush cache table

### ISSUE THREAD

**Issue by peppelinux** [opnsense/core#1833]
It would be great to have in
Interfaces/Diagnostics/ARP Table

a button to flush ARP table.
This could be usefull in case of:

 - ARP poison
 - just-changed-ip as AP or others critical nodes
 - diagnosys on ARP loop and unwanted ARP proxy (after flush something will be more visible if happens)

**Comment by peppelinux** [comment]
It should not cost too much, just an API call to confid 

  arp -ad (this should work on BSD too)

and a page refresh :)
Thank you for your attention, I never seen in my life a support and a Team work like yours.

**Comment by peppelinux** [comment]
Just pulled in #1844, 
very simple approach just to get it to work, we could extent it is needed

**Comment by fichtner** [comment]
Was merged a while back. :)
