### ISSUE TITLE
[Suricata][Feature Request] Emerging Threats Pro Support

### ISSUE THREAD

**Issue by glugy** [opnsense/core#1834]
Hello, for users who subscribe to the Emerging Threats Pro ruleset for Suricata, I've created an et-pro.xml file that replaces the et-open.xml file at core/src/opnsense/scripts/suricata/metadata/rules/.  The subscriber's oink code goes inside the URL in the et-pro.xml file.  The et-pro.xml file is attached.
[et-pro.xml.txt](https://github.com/opnsense/core/files/1312393/et-pro.xml.txt)

In order for the rules to download properly, I had to make some changes to core/src/opnsense/scripts/suricata/lib/downloader.py.  

```
132d131
<                     req.raw.decode_content = True
134,139c133,135
<                     while True:
<                         data = req.raw.read(10240)
<                         if not data:
<                             break
<                         else:
<                              src.write(data)
---
>                     for chunk in req.iter_content(chunk_size=10240): 
>                         if chunk:
>                             src.write(chunk)
```

The headers for the ET Pro rule download looks like:

{'Content-Length': '7255', 'X-Content-Type-Options': 'nosniff', 'X-Powered-By': 'PHP/5.5.9-1ubuntu4.22', 'Strict-Transport-Security': 'max-age=63072000; includeSubDomains', 'Vary': 'Accept-Encoding', 'Keep-Alive': 'timeout=5, max=100', 'Server': 'Apache/2.4.7 (Ubuntu)', 'Connection': 'Keep-Alive', 'Date': 'Mon, 18 Sep 2017 22:11:48 GMT', 'X-Frame-Options': 'DENY', 'Content-Type': 'text/plain', 'Content-Encoding': 'gzip'}

I admit that I don't fully understand everything that is happening in downloader.py nor the consequences of my change.  That's why this is a feature request rather than a contribution.  It seems to be working for me, however, and it would be great if this could be done through the GUI.

**Comment by AdSchellevis** [comment]
@glugy I don't have an oink code available at the moment, but we do support a method to supply parameters for the oink code. 
The code change is probably a bug you hit, this one https://github.com/opnsense/core/commit/30fde1ef05bebba9c37e0b5c85176bd3c663d79b

 can you try the following changes to the file for me?

```
<location url="https://rules.emergingthreatspro.com/%%etpro.oinkcode%%/suricata-1.3-enhanced/rules/" prefix="ET Pro"/>
<files>
... your content..
</files>
<properties>
        <property name="etpro.oinkcode" default=""/>
</properties>
```

This should add the oink code at the bottom of the list, which the will be used on downloading the rules.
![image](https://user-images.githubusercontent.com/9783985/30579039-27c23c6e-9d17-11e7-8065-899e48822c32.png)

We can easily add a plugin containing this list, which people can install via the normal plugins then.

**Comment by glugy** [comment]
@AdSchellevis, 
I applied the patch in [30fde1e ](https://github.com/opnsense/core/commit/30fde1ef05bebba9c37e0b5c85176bd3c663d79b), and that corrected the problem with the ET Pro rules downloading.  Thanks for that.

Next, I updated my et-pro.xml file with your suggested changes to support entering the oink code in the web interface.  That all worked as expected.  I've attached the final et-pro.xml file with oink code support. (I had to add a .txt extension to add it to this message)  
[et-pro.xml.txt](https://github.com/opnsense/core/files/1316077/et-pro.xml.txt)

One item of note, there are 7 rules across the et-open and et-pro rulesets that have the same names.  I noticed some odd behavior for some of those 7 rules when both rulesets were loaded in the metadata/rules folder.  If this is made into a plugin, is it possible to remove the et-open.xml when the et-pro.xml is installed, and replace the et-open.xml when the plugin is uninstalled?

If/when this can be made into a plugin, I'd be happy to help with testing.

Thanks!

**Comment by AdSchellevis** [comment]
@glugy thanks for confirming, I will try to wrap this in a package when I have some time.

**Comment by AdSchellevis** [comment]
@glugy can you check this https://github.com/opnsense/plugins/blob/master/security/intrusion-detection-content-et-pro/src/opnsense/scripts/suricata/metadata/rules/et-pro.xml file for me too? 

This package will be included in one of the following releases and should also work in conjunction with the et-open rules  (uses different output filenames).

**Comment by glugy** [comment]
The location url in https://github.com/opnsense/plugins/blob/master/security/intrusion-detection-content-et-pro/src/opnsense/scripts/suricata/metadata/rules/et-pro.xml needs to be changed to: `https://rules.emergingthreatspro.com/%%etpro.oinkcode%%/suricata-1.3-enhanced/etpro.rules.tar.gz`.  Otherwise, it seemed to work well.  I was able to use rules from both et-open and et-pro at the same time.  

Thanks!

**Comment by AdSchellevis** [comment]
@glugy thanks for testing, I've changed the url in the package it should be good now
