### ISSUE TITLE
php warning dmesg.boot does not exist

### ISSUE THREAD

**Issue by reetp** [opnsense/core#184]
PHP Warning:  fopen(/var/log/dmesg.boot): failed to open stream: No such file or directory in /usr/local/www/index.php on line 113

   111	## Find out whether there's hardware encryption or not
   112	unset($hwcrypto);
   113	$fd = fopen('/var/log/dmesg.boot', 'r');
   114	if ($fd) {

Probably should have something like 

if (file_exists('/var/log/dmesg.boot'));
 $fd = fopen('/var/log/dmesg.boot', 'r');
else bail out
blah

Question is should there always be a dmesg.boot file ? I can see that the logs get rotated out every day - be much nice for debugging if you kept at least a weeks worth.

This seems to work but my PHP is as bad as my CSS :-) You may want to do something else if either the file doesn't exist.

root@OPNsense:/ # diff -ruN /usr/local/www/index.php.orig /usr/local/www/index.php
--- /usr/local/www/index.php.orig	2015-05-18 19:28:31.000000000 +0200
+++ /usr/local/www/index.php	2015-05-19 10:49:11.000000000 +0200
@@ -110,6 +110,7 @@
 
 ## Find out whether there's hardware encryption or not
 unset($hwcrypto);
+if (file_exists('/var/log/dmesg.boot')){
 $fd = fopen('/var/log/dmesg.boot', 'r');
 if ($fd) {
     while (!feof($fd)) {
@@ -127,6 +128,7 @@
     }
     fclose($fd);
 }
+}
 
 ##build widget saved list information
 if ($config['widgets'] && $config['widgets']['sequence'] != "") {

**Comment by fichtner** [comment]
Heh, I pushed this a few minutes ago: https://github.com/opnsense/core/commit/252a9a13842255c7e0eda731ff913d147983d741 :)

/var/log/dmesg.boot doesn't really exist, but was written from the GUI in some instances previously removed. The correct location is /var/run/dmesg.boot

**Comment by reetp** [comment]
:-) Another one coming for you in a minute !
