### ISSUE TITLE
Feature Request: Libreswan or equivalent IPSEC/IKEv1 implementation

### ISSUE THREAD

**Issue by sempervictus** [opnsense/core#1840]
At present, documentation states that the two methods for setting up client access VPN utilize strongswan for the IPSEC portion (IKEv1 included, a very prominent part of the UI), or OpenVPN for TLS encapsulation (L2TP in itself offers no secrecy, just encap).
As discussed in IRC, strongswan sends incompatible options to the vpnc and Cisco VPN clients resulting in connection failures when available routes for split tunneling are advertised (option 13 IIRC). OpenVPN is a third party application and driver stack which many companies and individuals will not want or cannot install.
We've seen this problem before running VPNaaS in Neutron - under the K and M releases on Ubuntu, default client implementation was strongswan. We were able to replace it with libreswan and inter-site connectivity with ASAs began to work like a charm. It was pretty "drop-in" with Neutron being more of a PITA than building and deploying the binaries/packages on Ubuntu.
I'm aware this isn't Linux, and that initial attempts at adding the libreswan client to ports were met with frustration. However, i would suggest that this is a major feature in any edge control implementation, and already takes up a decent chunk of realestate in the UI. Breakage of this nature is often impossible for users to trace and understand, so they get frustrated and move on to something else without ever filing a bug. Either a vpnc/cisco compatible implementation needs to be devised, or at least the docs updated to state that client VPN implementations will require installation of software on client systems.

**Comment by AdSchellevis** [comment]
@sempervictus it's better to open your request in plugins, our standard ipsec implementation won't switch to libreswan, strongswan has much better support for most situations.

**Comment by sempervictus** [comment]
Libreswan does not reduce compatibility with peers as far as we've seen, its a superset in terms of peer compatibility. If I can get it to build sanely, would that not constitute a worthwhile improvement? At present, there are "broken features" in the implementation far as compatibility goes. Strongswan breaks with site to site against an asa on rekey and doesn't work with Cisco compatible clients when it uses split tunneling. This creates all sorts of security concerns as a working implementation may leak traffic to the VPN provider which was not supposed to be xlated/routed through them.

**Comment by AdSchellevis** [comment]
wouldn't it be better if you worked with strongswan to fix the issue you have? libreswan certainly isn't a drop drop in replacement for strongswan.

**Comment by fabianfrz** [comment]
@sempervictus: this is probably the best place for your bug report: https://wiki.strongswan.org/projects/strongswan/issues

**Comment by fichtner** [comment]
Since libreswan is out of the question I'm closing this.
