### ISSUE TITLE
anti spam

### ISSUE THREAD

**Issue by rout3rx** [opnsense/core#1843]
hello,
which anti-spam package is good and compatible with opnsense?

**Comment by fabianfrz** [comment]
@rout3rx you can install any software that runs on freebsd.
You need a mail server as a proxy (for example postfix) and a tool like spamassassin.

**Comment by mimugmail** [comment]
I was planning to start on building a plugin in November, but I'm still unsure about the software to use. I'm a old fashioned user of postfix / amavis / SA, but there's already opensmtpd which is really easy to use, or other anti spam alternatives like rspamd.

**Comment by fabianfrz** [comment]
@mimugmail if you use amavisd, you can make it dependent on os-clamav so it will also scan for malware.

**Comment by mimugmail** [comment]
@fabianfrz This was the intention to build clamav as a separate plugin to let other services like MTA to use it.

**Comment by fabianfrz** [comment]
@mimugmail amavisd-new easily allows to add a new scanner - It is just adding two new entries in a template - for clamav you only have to uncomment it in the default config (and maybe adjust the path).

The other idea would be making it optional but in that case, core must be updated to allow a check if a plugin is installed in the template.

**Comment by fichtner** [comment]
In any case this is not core functionality. ;)

https://github.com/opnsense/plugins

**Comment by rout3rx** [comment]
is it true?
security/clamav -- Antivirus engine for detecting malicious threats
antivirus added in opnsense?

**Comment by fichtner** [comment]
yes, currently for ICAP usage through c-icap plugin to web proxy (squid)

**Comment by ffries** [comment]
AFAIK, the best way to kill spam nearly completely is to run your own mail server, for example Postfix. 

It will allow you to validate mail on several criterias: HELO verification,address veridication, SPF (identity of sender), clamav (virus) and various tweaks. In my case, I was able to drop spam to a minimal of 1 or 2 per day. Whereas with professionnal services like OVH, i still receive 100 spams a day.

Fighting against spam requires that your mailserver is able to reject or postpone delivery on the fly. i.e. you really need your own mail server.

**Comment by mimugmail** [comment]
@rout3rx can you close this one here? We can start a discussion issue in plugins.
My proposal would be `postfix` for smtp and `amavisd-new/spamssassin` or `rspamd` for Antispam.

**Comment by fabianfrz** [comment]
@mimugmail from the [forum](https://forum.opnsense.org/index.php?topic=6069.0;topicseen): this one exists too: https://sourceforge.net/projects/assp/

its (also) written in perl so it should work.

**Comment by mimugmail** [comment]
assp for BSD is only v1 and there's no maintainer for v2. If I remember correctly there was a discussion to discontinue the BSD port.

@fabianfrz There's a nice thread (german only) regarding rspamd. It's really promising in contrast to amavisd, but it's a pain to compile the port (luckily that's @fichtner 's job) ;)
https://listi.jpberlin.de/pipermail/postfixbuch-users/2017-September/065340.html

**Comment by fabianfrz** [comment]
@mimugmail does not look bad in comparison:
https://rspamd.com/comparison.html

 It has also native AV support:
https://rspamd.com/doc/modules/antivirus.html

**Comment by mimugmail** [comment]
Yep, configuration is also pretty easy

https://forums.freebsd.org/threads/60690/

**Comment by fichtner** [comment]
Just add a reminder ticket for rspamd 😊

**Comment by fabianfrz** [comment]
@fichtner done

**Comment by rout3rx** [comment]
i think 
http://www.caronteantispam.com/quick_install.php
not bad. it have a rich interface and MTA installed built in.

**Comment by mimugmail** [comment]
It's not free?!

http://www.caronteantispam.com/acquista.php

**Comment by rout3rx** [comment]
yeah, sorry.

**Comment by rout3rx** [comment]
i installed rspamd via pkg and run it in a privileged user, some ports such as 11333 and 11334 is already listend but no one have webui and give me a error:
{"error":"invalid command: ","error_domain":"protocol-error"}

**Comment by fabianfrz** [comment]
@rout3rx Maybe you are talking to it using the wrong protocol (for example accessing the milter port using HTTP). Please check the configuration for enabling the GUI.

**Comment by fabianfrz** [comment]
@mimugmail I compiled `rspamd` on my arch linux machine without any problems (just had to install an AUR package as a dependency).

So building should not be an issue for making it working on OPNsense as well.

**Comment by mimugmail** [comment]
@fabianfrz Great! :) I tested it couple of weeks ago but not very deeply.
@rout3rx 11334 is the admin port, but it's localhost only. On a Debian install it works good :)

I loke the proposal to put all own stuff in subfolder local.d, this would make it very easy to adapt to OPN. 

Also really nice to train ham&spam via Admin UI

@fichtner This would mean we need postfix, rspamd and redis-server as pkg's
