### ISSUE TITLE
[Feature request] Make interface groups working in IPS/ Suricata, as they are already listed in the int selection dropdown

### ISSUE THREAD

**Issue by hutiucip** [opnsense/core#1845]
Hello!

Please, write the necessary code for interface groups to work in IPS, especially since a grup is available/ listed in the web interface, in interface selection drop-down list.

Thank you!

**Comment by AdSchellevis** [comment]
can't work for IPS, only for IDS, due to the technology used (netmap),

**Comment by AdSchellevis** [comment]
my mistake, isn't supported for IDS either. will strip them from the list of options

**Comment by fichtner** [comment]
@AdSchellevis I know I'm generating work, but wouldn't it be possible to render the grouped interfaces instead of the group interface name? I'd be ok with looking into this at a later point.

In any case I do agree with the current fix to provide consistency, I will also add it to 17.7.4.

**Comment by AdSchellevis** [comment]
@fichtner better not, interface groups can also include types which aren't supported for ips and the contents of the group can be dynamic (openvpn, tinc for example) .

**Comment by fichtner** [comment]
ok, understood
