### ISSUE TITLE
firewall: pressing "enter" in virtual IP edit changes vhid to 1

### ISSUE THREAD

**Issue by fichtner** [opnsense/core#1849]
Also, how is "unused" supposed to work?

**Comment by syserr0r** [comment]
Clicking 'unused' also changes the VHID to 1 -- I suspect pressing <Enter> is causing the 'Unused' button to be triggered

**Comment by AdSchellevis** [comment]
unused selects the first unused vid, I can't reproduce the "select 1 on enter" when opening the page, disabling tabstop on the button could be a fix...

**Comment by fichtner** [comment]
Using chrome it selects “1” on enter as described previously. You’re using Firefox?

**Comment by syserr0r** [comment]
@AdSchellevis try pressing `Enter` when focus is in an `<input ... >` box
