### ISSUE TITLE
Feature Request: Internal CA can sign CSRs in UI

### ISSUE THREAD

**Issue by pwhack** [opnsense/core#1850]
Hi,

Please consider adding to the existing Certificate Authority UI functionality to sign an existing CSR. Presently the UI only permits generating a CSR from scratch or importing existing private key and public cert.

I use OPNsense as my in-house CA and not all devices accept uploads of pre-generated keys/certs.

Thanks!

**Comment by fichtner** [comment]
Hi @pwhack,

This is a nice feature. I'm tagging it "help wanted" to see if anybody will help to get this in. :)


Cheers,
Franco

**Comment by tokred** [comment]
This feature would be great as it would complete the whole Trust functionality.

What would be required to implement this? Can opnsense already handle certificates without available private key at all?

Regards

**Comment by pwhack** [comment]
I'm guessing [system_certmanager.php](https://github.com/opnsense/core/blob/master/src/www/system_certmanager.php) just needs a function to wrap around PHP's [openssl_csr_sign()](http://php.net/manual/en/function.openssl-csr-sign.php). Much of system_certmanager.php is already doing similar wrapping with logic so someone familiar with that that file's logic likely knows the right spot to add such a logic branch.

**Comment by soleilblanc99** [comment]
Any chance this will happen? i can't code but willing to test.

thank you

**Comment by wschlich** [comment]
I'd also love seeing this feature implemented. How can I help?

**Comment by AdSchellevis** [comment]
@wschlich It's probably not very difficult to add, but I haven't looked at it. It's probably best to start with describing some steps how to do this end to end (openssl commands), so we have an easy test scenario. Then check where this would fit the ui. 

If I'm understanding the request correctly, then this would only use a ca to generate a cert, which the user can copy-paste into his application. It wouldn't be necessary to store the result, right?

**Comment by AdSchellevis** [comment]
@wschlich it seems @nhirokinet made an initial proposal https://github.com/opnsense/core/pull/3234 If your would like to do some testing, that would be very nice.

**Comment by AdSchellevis** [comment]
```
opnsense-patch 07b41fc4
```

**Comment by wschlich** [comment]
> @wschlich It's probably not very difficult to add, but I haven't looked at it. It's probably best to start with describing some steps how to do this end to end (openssl commands), so we have an easy test scenario. Then check where this would fit the ui.

I see. Shouldn't be a big deal.

> If I'm understanding the request correctly, then this would only use a ca to generate a cert, which the user can copy-paste into his application. It wouldn't be necessary to store the result, right?

It would be about generating a certificate by signing a request (CSR) uploaded/pasted by the user.

I would vote for storing the result/certificate for reference purposes, because it would also need to be revokable via the CRL etc. -- it would just not have a private key part, compared to other certificates issues by OPNsense.

**Comment by wschlich** [comment]
> @wschlich it seems @nhirokinet made an initial proposal #3234 If your would like to do some testing, that would be very nice.

Okay, will do :)

**Comment by wschlich** [comment]
> @wschlich it seems @nhirokinet made an initial proposal #3234 If your would like to do some testing, that would be very nice.

Worked well so far -- got a certificate signed successfully :)
Also, the certificate is stored just like others.

Had some comments placed in the pull request (https://github.com/opnsense/core/pull/3234/commits/07b41fc43a275e3aa4d8676fbb9749cedd0cdfa5) -- mainly cosmetic issues.

**Comment by wschlich** [comment]
Ok, so I did find an issue :)
My CSR contained a 'X509v3 Subject Alternative Name' but the certificated generated from signing that CSR doesn't have a SAN.

**Comment by AdSchellevis** [comment]
https://github.com/opnsense/core/pull/3234

**Comment by ybizeul** [comment]
I'm very confused by this issue. It seems like a lot of work has been done and the feature merged, but as @wschlich mentions, SANs are dropped from the signed certificate, even though they are listed in the UI while signing the request (it reads them from the CSR just fine)

**Comment by koelle25** [comment]
> I'm very confused by this issue. It seems like a lot of work has been done and the feature merged, but as @wschlich mentions, SANs are dropped from the signed certificate, even though they are listed in the UI while signing the request (it reads them from the CSR just fine)

The same happens when trying to sign a CSR with `basicConstraints=CA:TRUE`. In the UI it is display, and the checkbox is set, but after creating the certificate it does NOT have CA:TRUE.
