### ISSUE TITLE
Add support for copying out IP addresses from Network Insight view

### ISSUE THREAD

**Issue by juj** [opnsense/core#1853]
In web UI, under `Reporting` -> `Insight`, there is a set of pie charts showing IP addresses of network transfers.

I'm trying to understand what some of these IP addresses are, and hence, I wanted to do Reverse DNS lookups on them. In the absence of that feature (#1034), I was attempting to copy-paste the IP addresses out to manually Reverse DNS (e.g. via https://remote.12dt.com/), but it looks like it is not possible to copy these IP addresses to be pasted elsewhere. This would be a great feature to have.

**Comment by AdSchellevis** [comment]
you know you can export the data? the last tab will delivers the same content as the graphs.
I'm not sure we can change the behaviour easily in the graphs.

**Comment by juj** [comment]
Thanks for the reply! I now notice I am able to copy the data out from the other tab.
