### ISSUE TITLE
Show lan hostnames instead/in addition to local IP addresses in Insight view

### ISSUE THREAD

**Issue by juj** [opnsense/core#1854]
Similar to #1034, it would be good to see the `lan` section of the `Reporting` -> `Insight` view show local hostnames instead/in addition to IP addresses. That is, instead of a `192.168.1.121`, it would show `MikesPC` or whatever the hostname was.

Something that might be a bit delicate there is that it would be great to have that feature show the hostname that the system had during the time of the transfer, instead of at present time, since it might have changed between that time. (e.g. due to DHCP lease)

**Comment by AdSchellevis** [comment]
If we have support for reverse lookups, you should be able to register your dhcp leases in your dns to make this happen.

**Comment by fichtner** [comment]
This already works in 18.1 when:

* Dnsmasq or Unbound are set to register static/dynamic DHCP hostnames.
* The firewall is allowed to resolve against either Dnsmasq or Unbound. (disable "Do not use the DNS Forwarder/Resolver as a DNS server for the firewall" under System: Settings: General)

One user has noted that he did not want the firewall to resolve against Unbound/Dnsmasq, but we consider this an user choice that breaks internal resolution for said user(s). Adding more glue for a solution that works if set correctly (you can also use the forward mode in Unbound with your ISP servers) is not a core mission.
