### ISSUE TITLE
Feature Request: Shibboleth/SAML Authentication support

### ISSUE THREAD

**Issue by peppelinux** [opnsense/core#1855]
It would be awesome if OPNsense could be federated to a SAML IDP service, such shibboleth.

In a modern management of enterprises, academies or campus, Shibboleth IDP is now a ineludible standard. Is there any already development plugins for integrate OPN as a SP of Shibboleth or could we start thinking about this opportunity?

In other words it is not so much important that the below webserver is patched for shibboleth sessions, neither nginx or apache should replace lighthttpd, because we could introduce this important feature with a good PHP SAML library (or python if needed).

I'm going to develop a Django Service provider, for other projects, without apache or nginx additional patches/modules, just using python-SAML.

Shibboleth demistyfied :)

**Comment by AdSchellevis** [comment]
I'm not sure core is the correct place for this, forcing SAML for webgui authentication really has disadvantages, like not being able to login to your firewall administration when your SAML provider is unreachable.

From my earlier experiences with SAML/IDP there are some challenges in getting it to work, but the service itself is certainly helpful for a lot of web applications.
If your using python-SAML, the challenge will be to make sure you can route the requests correctly through our framework, so you don't need another webserver listening for SAML responses. 
A php library integrating into Phalcon probably is easier.

If you have a concept of how it will/can integrate, just let us know, we can always discuss if it's better to place it in a plugin and changes needed to core for getting it functional.

**Comment by peppelinux** [comment]
You're right, Shibboleth is simply out of scope, introducing a PHP SAML2 library will be the goal.

A stupid question: Does OPN have a authentication stack or just one auth could be used at time.
I mean, If my user@IDP doesn't work could I use a local /etc/passwd OPN user?
In Django we use multiple autentication backends configured in a stack, from top to bottom the first that matches will give the login to the user.

**Comment by AdSchellevis** [comment]
you can configure a fallback, just take a look at our authentication framework and settings (in System->Access)

**Comment by peppelinux** [comment]
Could a php-saml auth be introduced as a plugin or we have to commit in the core repo?

**Comment by AdSchellevis** [comment]
a plugin, but you might need additions in core, the procesflow using saml is quite different.

**Comment by peppelinux** [comment]
Could we develop in core directly?
This thing will take more time but, if in my work environment we will decide to introduce OPNsense in production it will be because of SAML2 support. This mean that if it will be introduced, well, it will supports SAML2 :)

I do not have any alternative way to face this, just develop it!

**Comment by fabianfrz** [comment]
@peppelinux you can write it and it can be moved later. We cannot enforce anything what you do in your repositories or local machines. Just create a new feature branch and you may get help how to extract the changes for a plugin.

**Comment by peppelinux** [comment]
thank you @fabianfrz, if something will happen I'll post updates here

**Comment by AdSchellevis** [comment]
timeout
