### ISSUE TITLE
[USER MANAGEMENT] Limitation of GUI

### ISSUE THREAD

**Issue by kavi0208** [opnsense/core#1856]
Hello,

The user management interface has some limitations and problems:
1. A normal user assigned to group x which has access only to user management is able to create,delete,modify users but is also able to modify the admin account
2. As a normal user can modify the admin account, he can eventually assign privileges to himself to get full access. Well i can disable assign privileges for this particular account but he may modify admin password, gain access to it and add privileges for his user.

Actually i have a situation where if i want to give access to a user privilege just to create/delete/modify vpn local users, i automatically give him rights to modify overall config.

It would have been interesting that a user is added to a specific group where his privileges permits him only to modify users in some groups like:
```
group1:
add/modify/delete users in group1
add users in group1 or group2

group2:
permits only vpn login for ipsec "ipsec xauth dialin"
```

And the admin group has access to everything. This would have permit to give a user access just to add/modify/delete vpn user account without being able to modify his privileges or gaining access to admin. This would permit to give specific access to some people without being able to modify the whole system.

The only way that can permit me to achieve this actually is to go for external authentification.

Thanks.

Regards,
Kaviraj

**Comment by youhackme** [comment]
I am having the same issue. Is this a bug or an intended feature? 🤔 

 Thanks.

**Comment by fichtner** [comment]
This is how the privileges system was designed and maintained in earlier iterations of the software.

Even in theoretical / more complex solutions to the system giving rights to the user management will yield full power over user management so I am not sure how to solve this without adding more code that is tailored for specific use cases that could maybe solved differently.

In the case of xauth dail in, the privilege was already dropped from the system in the development version for 18.1. You can assign a group that allows IPsec mobile authentication, but then the group assignment is probably the tricky part to model correctly again.

So I have to ask... who is assigning groups / users at the moment and why are you not using a more flexible approach with an "external" authentication method, e.g. LDAP?  RADIUS may also work *and* maybe even with the plugin that we have that does not require user manager access...


Cheers,
Franco

**Comment by kavi0208** [comment]
Hello,

Going through external authentification creates another problem with openvpn as actually user management permits the creation of ssl certificates for users directly when adding a user. In case of using external authentification means user creation will be done via lets say radius but certificates creation will be via opnsense more precisely in trust menu.

Regards,
Kaviraj

**Comment by AdSchellevis** [comment]
Timeout

**Comment by openPablo** [comment]
Has this been resolved yet?

**Comment by fichtner** [comment]
Nobody proposed code for this. Note this is a feature request, not a bug.

**Comment by openPablo** [comment]
Isn't this a security issue? I'm trying to setup a system where an admin can add/remove his own users on his own so I don't have to micromanage all my clients. Otherwise I would need to create all users and give them the QR code for their OTP manually.

Thanks in advance.

**Comment by openPablo** [comment]
Okay thank you. I understand it was made that way and it's not easy to change the whole structure of the code.
What other options do I have to delegate user creation?

**Comment by fichtner** [comment]
I assume you want OTP for OpenVPN login?

**Comment by openPablo** [comment]
Yes I want OTP, are you saying it's doable if I drop OTP?

**Comment by fichtner** [comment]
There are several things you can do:

* Use an external RADIUS / LDAP server for OpenVPN authentication. This can include remote OTP if supported by the backend.
* Use the os-radius plugin to do the OpenVPN user management. It currently does not support OTP. The Radius can be operated by non-admins if you want that and user creation is done there. Then simply use that internal Radius like an external one in OpenVPN (binding created over system: access: servers too).

**Comment by openPablo** [comment]
Thank you for the tips, I'm going to try os-radius plugin! Would've been much easier though if AC was a bit more fine grained.
