### ISSUE TITLE
[feature request] SYSLOGD config

### ISSUE THREAD

**Issue by Stephanowicz** [opnsense/core#1857]
Hello again^^,

Basically I'd like to have more control over what is logged and where.
At moment this is partially avaiable for remote logging only

As it is quite a bit of work to add individual options it would be great if one could add an additional line to the settings at least...
e.g I'd like to have smth like 
`*.err;kern.warning;*.notice;authpriv.none;kern.debug;lpr.info;mail.crit;news.err	/var/log/messages
`

At moment I'm thinking of an addtional .conf file that get's parsed at startup as a simple solution...
Probably this is already somewhere implemented?

Cheers, Stephan

**Comment by fichtner** [comment]
Syslog-ng should eventually replace syslogd and we want to make that more configurable. But at the moment we don’t know if this is landing in 18.1 or not. It’s not likely that the old system will receive substantial updates in the meantime.

**Comment by AdSchellevis** [comment]
with https://github.com/opnsense/core/issues/3505 (in master) you can already add custom configuration files 

https://github.com/opnsense/core/blob/41fcaf2436dfee412ddb03e4ac715cb162d85cf3/src/opnsense/service/templates/OPNsense/Syslog/syslog-ng.conf#L26

I'm planning to do some more specifically for remote logging, this ticket looks like it can be closed.
