### ISSUE TITLE
API access to firewall rules and aliases

### ISSUE THREAD

**Issue by noahmehl** [opnsense/core#1858]
# Definition

As a user, I need API access to update firewall aliases and rules.  The specific use case is to run an agent on my servers (fail2ban for instance), that can update a firewall alias list with banned IP addresses for the firewall rule/s.

## Next Steps
Not sure how to get started on such a thing...  Also, please let me know if this is a duplicate of an existing issue.

**Comment by AdSchellevis** [comment]
It's on the roadmap, but long time, since we need the legacy code to move into manageable direction, this https://github.com/opnsense/core/issues/1326 for example is a prerequisite and then we should move all validations into a model/controller construction. 

A possible short-term win could be to add an api to the aliases and start from there, for most scenarios access to the aliases is enough (like fail2ban), less validations there and less attributes to worry about. Still quite some work, but fits the roadmap.

**Comment by noahmehl** [comment]
Well, I'm for anything that allows me to update aliases from an API :). Is this something that has to be sponsored?  I don't know if I have the skillset to help programmatically...

**Comment by AdSchellevis** [comment]
I’m working in that area, but very busy. I’ll put it on my list of things todo, maybe 18.1, I can’t promise

**Comment by AdSchellevis** [comment]
Ok, the large chunks of work seem to be done, but still quite some small things todo:

- [ ] Validate usage of alias before removal
- [ ] Rename aliases in the system on rename (replacement for find_alias_reference())
- [ ] change is_alias() to use the new structure (during transition it should likely support both)
- [ ] change get_alias_description() to use the new structure
- [ ] change legacy_list_aliases() to use the new structure
- [ ] hook new alias system into menu
- [ ] remove old alias pages
- [ ] ditch alias import feature, using the tokenizer copy-paste should work by default.
- [ ] check pages for direct config access, there might still be some spots trying to load data from aliases

**Comment by noahmehl** [comment]
Wow, this is really amazing!  Thank you so much for your hard work on this!

**Comment by mimugmail** [comment]
Tested new aliases in current master. Why don't you display "content" in the overview? It's quite unusual when you have a huge list but no IP addresses in overview volt listed.

**Comment by mimugmail** [comment]
![image](https://user-images.githubusercontent.com/20438689/45216968-b66f6580-b2a2-11e8-8150-e10119aa9192.png)

**Comment by AdSchellevis** [comment]
@mimugmail content can be quite large (and usually is), but we probably can add the first x items there

**Comment by mimugmail** [comment]
Indeed, but as you can see from the screenshot it looks a bit odd compared to legacy code

**Comment by AdSchellevis** [comment]
@mimugmail https://github.com/opnsense/core/commit/e42c3d2565f2ed71281a9a6a1e1b47ddba45dea7 should do the trick

**Comment by mimugmail** [comment]
Looks good, thanks 👍

**Comment by fichtner** [comment]
Except for final merge date we are all done here with a bonus MVC rework on top for table diagnostics page. :)

Great work by @AdSchellevis

**Comment by mimugmail** [comment]
First upgrades in a couple of systems went smoothly. Very nice work @AdSchellevis ..very appreciated :)

**Comment by AdSchellevis** [comment]
@mimugmail thanks!

**Comment by fichtner** [comment]
yes, thanks @AdSchellevis  ❤️

**Comment by vlabmichl** [comment]
hey @AdSchellevis is there a documentation of your API?

...I stummbled around in the user / development manual and only came up to this
but it's missing sth. liken an "Firewall Alias" part:
* https://wiki.opnsense.org/manual/aliases.html
* https://wiki.opnsense.org/development/api.html

thanks for any hint!

**Comment by AdSchellevis** [comment]
@vlabmichl the general concept is found here https://docs.opnsense.org/development/how-tos/api.html best use the inspector in your browser to find the exact payload for an endpoint (all endpoints are used in the alias page and diagnostics -> pfTables).
