### ISSUE TITLE
Clarify what does "Insert my local MAC address" do?

### ISSUE THREAD

**Issue by juj** [opnsense/core#1859]
In the Interface setup view, there is a button `Insert my local MAC address`, like so:

![opnsense_lan_setup](https://user-images.githubusercontent.com/225351/31071167-b4e49264-a76b-11e7-9164-09ed4a710118.png)

I think it would be worth clarifying on the GUI page, what does that button exactly do, and what happens when one leaves the box blank?

In particular, does "my local" in that sentence mean the address of the connected user's MAC address who is configuring the web UI? Or does `Insert my local MAC address` mean `Insert this adapter's default MAC address`? If so, I feel that the second sentence would be more appropriate to use, since the reference `"my local"` is vague to me. I understand this is probably crystal clear to you, but I was really confused.

Also, I think it would make sense to add a small text paragraph there saying what will happen if the box is left blank, and show what the adapter's default MAC address actually is: e.g. `"If this field is left empty, the adapter's default MAC address 03:1F:53:01:33:36 will be used"`.

Are these assumptions correct?

**Comment by fichtner** [comment]
Hi @juj,

It wasn't / isn't clear, I agree... After a review, the code "means" the following: the visible remote MAC address that is being used to connect to the OPNsense box via your current GUI session, noting that it will be the nearest router hop by the way how the link layer works.

That is what is normally necessary if you put the OPNsense in front of your home router to be able to talk to the modem in front of it, telling the modem that the "correct" device is connecting.

Your assumption is correct and the text could be changed slightly, we don't know if the adapter is hard or software so its MAC may be spoofed / generated and should not be displayed.

As to how "my local address" should be reworded: what do you think now?


Cheers,
Franco

**Comment by juj** [comment]
Thanks for the clarification. Reading through your explanation, I admit I might be at a slightly too beginner level on networking concepts to grab the explained use case to be able to recommend a good wording.

What happened in my scenario is that I had a Realtek network interface on my OPNsense router box connecting to my WAN side DSL box, and I had connected my local PC directly to the OPNsense box LAN port to configure the box. Initially I was having problems with the OPNsense box's NIC to obtain a DHCP address for the WAN side. At the time I was not aware of the trouble with the Realtek NIC card drivers not working well with FreeBSD, and I was browsing around the OPNsense settings pages to find what might be the problem, testing various settings. At some point I thought to try clicking the `"Insert my local MAC address"` button thinking that it would "autofill" the hardware MAC address of the adapter into the MAC address field, with a `"well, does not harm to explicitly add this in so the field will not be left looking empty"` thought on it. Some time after that, I think the Realtek NIC card intermittently was able to get a DHCP lease, so I thought I was all in green and did not think much about it.

Until a bit later, when I revised my network setup topology to my intended configuration, where instead of connecting my PC directly to the OPNsense box, I would add a 24-port network switch in between the PC and the OPNsense box, to connect more devices to my LAN. After that, everything got really crazy, as it turns out that the OPNsense box and my PC were all of a sudden operating with colliding MAC addresses, and the router in between the PC and OPNsense was throwing packets all over, causing huge latencies and about 90% of packet loss, with random 10% of packets reaching their intended destination eventually. This led to a couple of days of hair scratching and debugging, and thinking that this brand new 24-port switch might be even physically broken, since connecting the PC directly to the OPNsense box had worked.

Only by a random chance I was able to figure out that there was a MAC collision, when I was looking at the switch's configuration page, which was fluctuating the same registered MAC address between two different ports, which was a "hold on, what's going on there" moment. After that, clearing the MAC address fields of the OPNsense box resolved the problem.

I am not sure what a good wording would be, but whatever it ends up being, it would be good to be clear to ensure it's something very explicit to not have a chance to be confused to being a sorts of a "autofill the defaults" action, like my mistake was.

**Comment by fichtner** [comment]
Thanks for the explanations. I've reworded / reordered the help text a bit, although there isn't much obvious to change. I've subtly added "leave empty if unsure", "(use with care)" and a hint that this is normally not required, and if only for "WAN interfaces".

<img width="615" alt="screen shot 2017-10-25 at 7 08 08 am" src="https://user-images.githubusercontent.com/1915288/31981424-7eeebad2-b953-11e7-9e13-521aa75dae5a.png">


Cheers,
Franco
