### ISSUE TITLE
php warning file(/var/log/squid/cache.log): failed to open stream

### ISSUE THREAD

**Issue by reetp** [opnsense/core#186]
Got the following 

PHP Warning:  file(/var/log/squid/cache.log): failed to open stream: No such file or directory in /usr/local/www/diag_logs_proxy.php on line 60

/var/log/squid is empty

There should be a check on if the file exists similar too

if (file_exists($logfile) {

Not exactly sure how to finish this one off but I guess you will figure it out :-)

I can see that in dia_logs_relayd.php it is OK as there is an empty logfile created - may the solution is to create /var/log/squid/cache.log (though there should still really be if_exists in case of problems)

**Comment by fichtner** [comment]
squid was plugged in recently. All the warnings you are seeing are a result of the "debug" mode you went into using the live-mount for core.git. If they are non-fatal, prepending "@" to the function call is the best approach, if it is fatal, then some other code needs restructuring. Will look into this later.

**Comment by reetp** [comment]
:-)

**Comment by AdSchellevis** [comment]
The solution to check for existence sounds like a good plan, fixed in https://github.com/opnsense/core/commit/485225f46b6f0229589f5a4c4264639ea8ed9609

**Comment by reetp** [comment]
Never a bad thing. And checking if vars are set etc. Saves a lot of bugs ;-)
