### ISSUE TITLE
GeoIP selection of countries

### ISSUE THREAD

**Issue by gertfriend** [opnsense/core#1860]
Maybe it will be possible to change the GeoIP country selection from Dropdown to multiple-selection list box sorted by continent and then by country which would be more comfortable.

**Comment by mimugmail** [comment]
This really need some attention. 

The sort order in Aliases is by Country Codes. Normally this should make sense, but the CC of Germany is DE. Now this is how it looks like:

![image](https://user-images.githubusercontent.com/20438689/31575952-858ca760-b0f1-11e7-88ec-706f66ebfa43.png)

CC of Algeria id DZ, that's why it's there. 

First of all there should be a new sort order by country_name. 

Also the CSV from the script `/usr/local/opnsense/scripts/filter/download_geoip.py` includes `continent_code` and `continent_name`

I havent digged to much in this script yet, but there could be an optimized sort order for `continent_name` and inside this by `country_name`

What do you think @AdSchellevis and @fichtner ?

**Comment by AdSchellevis** [comment]
@mimugmail I agree about the sorting, but not the continent data. we use /usr/local/opnsense/contrib/tzdata/iso3166.tab for country codes, which is always available on the machine and doesn't require a download first. Unfortunately there is no continent in there.

I will prepare a fix for the sorting, and add some JS magic to replace the select for a searchable one, but that's as far as I will take this.

**Comment by fichtner** [comment]
I agree that it's difficult to conjure a nice UX here for selecting whole Continents, managing exceptions within, etc...

The zone.tab file has all the info. I'll try to look at implementing it after Ad's changes.

https://github.com/Distrotech/tzdata/blob/master/zone.tab

**Comment by mimugmail** [comment]
Yep, really tricky with a dropdown list. Sophos does this besides the rules, just to give you an idea:

![image](https://user-images.githubusercontent.com/20438689/31584407-400436b4-b1ae-11e7-9e18-433883563f78.png)

**Comment by AdSchellevis** [comment]
with the continent info available, optgroups (https://silviomoreto.github.io/bootstrap-select/examples/#select-boxes-with-optgroups) could be used. but selecting more items in the same row also requires changes to the filter.

**Comment by fichtner** [comment]
Option groups with individual select/deselect all might work if they can be combined, so people can select whole regions and also make exceptions....

**Comment by fichtner** [comment]
I think the Sophos example is good, the boxes should be multi-select and we have a fixed data so adding more fields doesn't help...

I would:

1. Add javascript section headers checkbox to toggle whole region.
2. Add checkboxes in each region for each country.

That way "search" can be done via browser.

Ok?

**Comment by mimugmail** [comment]
And probably a checkbox of the country rules should be before or after the user ruleset

**Comment by fichtner** [comment]
I don't understand that last part?

**Comment by fichtner** [comment]
Like this, only pretty...
 
<img width="668" alt="screen shot 2017-10-15 at 5 14 44 pm" src="https://user-images.githubusercontent.com/1915288/31586078-6be67f1c-b1cc-11e7-937d-038df1c9e3f6.png">

**Comment by AdSchellevis** [comment]
I would advise to keep it simple, within the features selectpicker kan handle by default..... The amount of work needed could grow rapidly.
This
![image](https://user-images.githubusercontent.com/9783985/31586085-9ad9a38a-b1cc-11e7-813e-baf7aa37419f.png)

can easily be combined with 
![image](https://user-images.githubusercontent.com/9783985/31586107-b3ec5494-b1cc-11e7-9f2e-1ca4d94503fd.png)

Only challenge is to map the codes back to something comma separated and push it back to the input.

**Comment by mimugmail** [comment]
With Sophos this is an own tab besides fw rules. Country rules are processed before normal rules. So if you plan to so it the same way it would be cool to decide

**Comment by fichtner** [comment]
@AdSchellevis but still the dataset is fixed and a bit too big to handle from a single select picker. if we unfold to checkboxes and create CSV from there that's easy. we also don't need the multi-row approach... it's like apples and oranges. If we can render by region, we don't have to change it again. can't get more UX than what Sophos already has in terms of edit speed and field of view.

@mimugmail aliases can be used as destination or source in filter rules. they are not blocked by default and should not, so we don't need any "ordering".

**Comment by mimugmail** [comment]
This would be winner against Sophos, always good to beat the commercials 👍

**Comment by AdSchellevis** [comment]
@fichtner you're certainly right about the usability aspect, fitting it in just takes more time then improving what we have now.

**Comment by fichtner** [comment]
Works for me, saves ok, added new validation... please test

<img width="1029" alt="screen shot 2017-10-15 at 8 31 03 pm" src="https://user-images.githubusercontent.com/1915288/31587781-d9435510-b1e7-11e7-9a23-7a88c0a663b1.png">

**Comment by mimugmail** [comment]
987afe8 is enough or also the first one?

**Comment by fichtner** [comment]
# opnsense-code core
    # cd /usr/core
    # make upgrade

if upgrade refuses:

    # opnsense-update -t opnsense-devel

**Comment by mimugmail** [comment]
I love it :) 
Is this so memory hungry? I created a "europe" alias with toggle all and get:

`Oct 16 10:46:10 OPNsense opnsense: /usr/local/etc/rc.filter_configure: New alert found: There were error(s) loading the rules: /tmp/rules.debug:21: cannot define table europe: Cannot allocate memory - The line in question reads [21]: table <europe> persist file "/var/db/aliastables/europe.txt"
`

**Comment by fichtner** [comment]
how big is the file? I would say yes... /var/db/aliastables/europe.txt

**Comment by AdSchellevis** [comment]
@mimugmail how is "Firewall Maximum Table Entries" set in firewall -> settings -> advanced?

**Comment by mimugmail** [comment]
Since I cloned a fresh installation it was default. Bumped to 2000000 and now it's good.
I like this new approach, thank you guys 👍

**Comment by fichtner** [comment]
Maybe it's time we increase the default of that value somewhere?

**Comment by AdSchellevis** [comment]
could be a good idea, but chances are people still need to extend when having larger rulesets (which isn't an issue when there's enough memory available)

**Comment by L1ghtn1ng** [comment]
Can't we query how much ram the system has and set appropriately to what the system would be able to handle with that amount of ram? Just an idea I had

________________________________

**Comment by AdSchellevis** [comment]
no

**Comment by gertfriend** [comment]
Great work and also very fast implementation. With this view GeoIP would be very much more usable. Thank you very much.

**Comment by mimugmail** [comment]
Perhaps some kind of div alert when changing alias type to Geo?

**Comment by fichtner** [comment]
I was thinking help text as well, or added to the docs... FAE ... frequently asked errors :D

**Comment by mimugmail** [comment]
Yep, but the latest experiences showed that most people do a trial and error before posting to gh, before looking at the docs :( Perhaps a blue colored div ..

**Comment by fichtner** [comment]
in 17.7.7 :)

**Comment by algato** [comment]
Hello,
I would like to ask for your help:
1. "Firewall Maximum Table Entries"  how can i check how many entries my table allready has (does my table allready reached the limit)

2. which settings the WAN firewall rule should have to use the alias with the selected (blocked) countries.
interface WAN
Protocol any
Source (prepared alias) blocked_countries
Destination any

Is that correct, are that all parameters for that rule? 

Kind regard
Alex

**Comment by warnerbryce** [comment]
@algato i have the same question as you, do you have news about this ?

**Comment by mimugmail** [comment]
Just reread the official docs, should all be clear
