### ISSUE TITLE
Drag and Drop for sorting in Firewall- and Nat-Rules

### ISSUE THREAD

**Issue by gertfriend** [opnsense/core#1861]
Would it be possible to implement Drag and Drop in Firewall and Nat Rules to sort them?

**Comment by dohlin** [comment]
I understand this is very much on the "nice to have" side of the fence, but count my vote in on this request!  It's one of the few things I found myself missing after a recent migration from pfSense to see what OPNsense was all about.  For the most part I'm really loving it so far!  Thanks for all your guys' stellar work!!

**Comment by AdSchellevis** [comment]
timeout
