### ISSUE TITLE
Fast change of Aliases

### ISSUE THREAD

**Issue by gertfriend** [opnsense/core#1862]
Can you please implement that i can change an alias for more rules at the same time, for example i select 20 rules and change for them at once the Source Alias.
Or would it be possible that i can change an assigned aliastype, for example i have an Alias of the type GeoIP for 50 rules, now i must change the aliastype to Host(s) but that isn't allowed and if i would like to change like this i must change all the 50 rules individually

**Comment by AdSchellevis** [comment]
Timeout
