### ISSUE TITLE
dhcp leases: hostnames with spaces cannot be registered

### ISSUE THREAD

**Issue by goor4** [opnsense/core#1866]
Host get a ip adress via dhcp and should register their hostname in dns (e.g. via unbound).

That can be configured as follows:
Menu: Services -> Unbound DNS -> General
  DHCP Registration: [x] Register DHCP leases in DNS Resolver
  DHCP Static Mappings: [x] Register static mappings in the DNS Resolver

But after some weeks uptime this work for some hosts but for some hosts not anymore.

Is it possible, that this is the inherited longstanding bug with ISC dhcpd and missing hostnames in dhcpd.lease in some cases?
Bug: https://redmine.pfsense.org/issues/6589
Fix: https://redmine.pfsense.org/projects/pfsense/repository/revisions/9dacff7f1b2b89ebebc1e9456d642e0657bb89cc/diff/src/etc/inc/services.inc

Thank you

**Comment by fichtner** [comment]
It seems this was fixed in isc-dhcp 4.3.5, we're now at 4.5.6. Also see https://github.com/pfsense/pfsense/commit/1bd7d5e5753c

**Comment by fichtner** [comment]
What version are you running?

**Comment by goor4** [comment]
OPNsense 17.7.4-amd64  (latest version)

with:
isc-dhcp43-server	4.3.6_1
dhcpleases	0.2
unbound	1.6.6

**Comment by fichtner** [comment]
Can you find an entry without a hostname in your leases file?

**Comment by goor4** [comment]
I just startet the system and:

The lease shows the correct hostname:
Services: DHCP: Leases
Interface IP address MAC address Hostname Description  
LAN 	192.168.33.193 	58:9c:fc:12:23:56 fbsd110 

Services: DHCP: Log File
Oct 6 17:22:02 	dhcpd: DHCPACK on 192.168.33.193 to 58:9c:fc:12:23:56 (fbsd110) via igb0
Oct 6 17:22:02 	dhcpd: DHCPREQUEST for 192.168.33.193 (192.168.33.1) from 58:9c:fc:12:23:56 (fbsd110) via igb0
Oct 6 17:22:00 	dhcpd: DHCPOFFER on 192.168.33.193 to 58:9c:fc:12:23:56 (fbsd110) via igb0
Oct 6 17:21:59 	dhcpd: DHCPDISCOVER from 58:9c:fc:12:23:56 via igb0

But the host is not resolvable via dns.

How can i download the raw leases file without ssh?

**Comment by goor4** [comment]
I managed to get ssh access:
cat /var/dhcpd/var/db/dhcpd.leases

lease 192.168.33.193 {
  starts 5 2017/10/06 18:22:01;
  ends 5 2017/10/06 20:22:01;
  tstp 5 2017/10/06 20:22:01;
  cltt 5 2017/10/06 18:22:01;
  binding state active;
  next binding state free;
  rewind binding state free;
  hardware ethernet 58:9c:fc:12:23:56;
  uid "\001X\234\374\013\3468";
  client-hostname "fbsd110";
}

DNS-Lookup to hostname fbsd110 is still NOT possible.

Another host is resolvable with that entry:
lease 192.168.33.190 {
  starts 5 2017/10/06 17:43:53;
  ends 5 2017/10/06 19:43:53;
  tstp 5 2017/10/06 19:43:53;
  cltt 5 2017/10/06 17:43:53;
  binding state active;
  next binding state free;
  rewind binding state free;
  hardware ethernet 00:0d:b9:12:34:56;
  uid "\001\000\015\2713|(";
  client-hostname "otherhost";
}

It seems, that there is another problem - probably with the dhcpleases  (Version 0.2)?

**Comment by goor4** [comment]
After some Day without reboot of openSense and the host with failing dhcp-dns-registration now the registration works without intervention.

**Comment by fichtner** [comment]
@goor4 that still the case? :)

**Comment by goor4** [comment]
Yes, it is still the case.
Now it happens on another host.

(I had a dhcp registering system with spaces in name ("Bose Waveradio ..."), could that cause a problem in the parser dhcpleses?`)

**Comment by fichtner** [comment]
It could be, ideally, we just need the leases file dump (or partial dump) and an indication of which hosts fail to resolve to reproduce

**Comment by goor4** [comment]
[dhcp.leases.txt](https://github.com/opnsense/core/files/1406076/dhcp.leases.txt)

I renamed the problematic "Bose"-Host a week ago, but I hope i could reconstruct it in dhcp.leases file to the old Value.

**Comment by fichtner** [comment]
Timeout, did not come up again.
