### ISSUE TITLE
Captive Portal Allowed Addresses not saving

### ISSUE THREAD

**Issue by patcsy88** [opnsense/core#1867]
Hi,

After configuring CP, i wanted to allow some hosts in the Guest zone to bypass CP and thus added 192.168.1.100/32 in Allowed Addresses, saved and Apply. However the host is still being redirected to the CP login page. Checking the configuration, the Allowed Address is black. I tried various permutations including excluding the entire subnet. I am on 17.7.5

**Comment by mimugmail** [comment]
You mean empty with "black"? Enter "," after the IP address and then save.

**Comment by patcsy88** [comment]
Got it! Thanks!
