### ISSUE TITLE
[FR]: data-type=password in mvc formulars

### ISSUE THREAD

**Issue by mimugmail** [opnsense/core#1868]
Hi,

in a dialog forms there's the option data-type="string" which will be translated as type=text in `<input>`
Is there a change to add a data-type="password" to translate it as type=password?

Example:
```
            <tr>
                <th data-column-id="enabled" data-type="string" data-formatter="rowtoggle">{{ lang._('Enabled') }}</th>
                <th data-column-id="username" data-type="string" data-visible="true">{{ lang._('Username') }}</th>
                <th data-column-id="password" type="password" data-visible="true">{{ lang._('Password') }}</th>

```

Perhaps there's already an option I'm not aware of :)

Thanks!

**Comment by fichtner** [comment]
Hi there,

This? :)

https://github.com/opnsense/core/blob/master/src/opnsense/mvc/app/views/layout_partials/form_input_tr.volt#L65


Cheers,
Franco

**Comment by mimugmail** [comment]
Forget it ... form `<type>password<type>` ... should have investigated some more minutes :(
