### ISSUE TITLE
[Suricata][Feature Request] Snort VRT Rules Support

### ISSUE THREAD

**Issue by shonjir** [opnsense/core#1869]
Building on issue https://github.com/opnsense/core/issues/1834, I've created a version for Snort VRT subscription rules.  

[snort-vrt.xml.txt](https://github.com/opnsense/core/files/1367391/snort-vrt.xml.txt)

Edit: It seems to be working fine.

**Comment by shonjir** [comment]
Opened PR https://github.com/opnsense/plugins/pull/316

**Comment by fichtner** [comment]
This was done, thanks for the submission :)
