### ISSUE TITLE
missing icons icon_in.gif icon_out.gif

### ISSUE THREAD

**Issue by reetp** [opnsense/core#187]
In ipsec status I get not found for these images
/themes/opnsense/images/icons/icon_in.gif
/themes/opnsense/images/icons/icon_out.gif

**Comment by reetp** [comment]
Also missing 
/themes/opnsense/images/icons/icon_success.gif

**Comment by AdSchellevis** [comment]
replaced them with some glyphicons, not perfect but at least better than missing icons :-)
