### ISSUE TITLE
[Suricata][Feature Request] Additional rule UI widgets for editing/sorting/filtering

### ISSUE THREAD

**Issue by shonjir** [opnsense/core#1871]
There are a number of UI enhancements that would make the rule editor easier to use for more complex policies.

- [ ]  A way to apply rules or filters to mark rules for dropping, sort of like oinkmaster rule files.  

- [ ]  A widget to respect the IPS policy mode metadata for Snort VRT rules (https://github.com/opnsense/core/issues/1869) to enable preselected rules for dropping (e.g., via "policy mode" and "policy selection" dropdowns as in pfSense's Suricata package).

- [ ]  Filtering dropdowns for policy set and/or file

- [ ]  Ability to filter based on enable status (e.g, show only disabled or enabled rules)

**Comment by AdSchellevis** [comment]
@shonjir 

> A way to apply rules or filters to mark rules for dropping, sort of like oinkmaster rule files.

you know you can change all rules in a file at once using "filter" in the download tab? or are you looking for something more fine-grained?

**Comment by shonjir** [comment]
Definitely more fine-grained.  The per-ruleset method works well for the ET-open rules where most of the rules you'd want to set to drop are well grouped into distinct rulesets.

Snort rules aren't quite as accommodating, with rules of varying severities and desired actions mixed throughout.  More selection options would definitely help with these. 

From a flexibility standpoint being able to set a baseline drop policy that's keyed to rule severity, classification, and/or policy metadata would be a great feature that would allow more flexibility in managing rulesets while retaining the "easy to use" aspect of OPNsense for the majority of users.

I was originally thinking in terms of oinkmaster configs (what I used with pfsense), but honestly a drop policy screen with a severity radio button, an IPS policy radio button, and a category checklist would allow a really simple way to customize rule actions without incurring the complexity of the oinkmaster method.

The screen could even include a rule action summary matrix showing counts of rules that are active/inactive, set to alert/drop, etc. as a way to provide immediate feedback when buttons are changed.

**Comment by AdSchellevis** [comment]
Timeout
