### ISSUE TITLE
what is the usefulness of logging in firewall rules ?

### ISSUE THREAD

**Issue by Diegonarducci88** [opnsense/core#1876]
Hello, I'm looking for a firewall, but I'm not sure if this is the case. I'm not sure if this is the case. every firewall rule has the option to log this rule, but when I go to settings and log files / normal view, all the log of all rules appears, what is the usefulness of the log option per rule if I can not see individually or only the What I put to log?

**Comment by mimugmail** [comment]
Go to 
System - Settings - Logging

There you can disable to log accepted packets.

@fichtner @AdSchellevis why isn't this under Firewall - Settings. I searched 3 times the page and had to google for this :/

**Comment by fichtner** [comment]
at the time when this was created there were no firewall: settings, still, don't want to spit log settings from log page at this point.
