### ISSUE TITLE
[BUG] openvpn rule

### ISSUE THREAD

**Issue by Diegonarducci88** [opnsense/core#1877]
openvpn only connects when I create a floating rule releasing everything, the rule created by openvpn wizard does not work, even releasing all traffic on all interfaces opnsense continues giving timeout, only when I apply the rule in floating.

openvpn 2.4.4. en last version opnsense.

**Comment by mimugmail** [comment]
Can you post a Screenshot of your wan firewall rules? Do you try to connect from outside?

**Comment by fichtner** [comment]
handled via https://forum.opnsense.org/index.php?topic=6172.0
