### ISSUE TITLE
KRACK_ATTACK Vulnerable HostApd

### ISSUE THREAD

**Issue by squadramunter** [opnsense/core#1878]
Found today a security patch for the well known KRACK_ATTACK readed by thehackernews.com

https://thehackernews.com/2017/10/wpa2-krack-wifi-hacking.html 

Also I found some patches for hostapd to solve this problem.

https://w1.fi/security/2017-1/ 

I don't know if OpnSense uses HostApd but in case here is the patch for this vulnerable.

Hope this can be fixed as soon as possible.

**Comment by squadramunter** [comment]
I checked what version off HostApd is installed on OpnSense, but there is version 2.5 installed. Should this be upgraded to version 2.6 with the security patches init?

**Comment by fichtner** [comment]
I would rather take the official freebsd variant for 11.x, but I'm trying my luck with 2.6 rebased patches on 2.5 now because the former will take longer

**Comment by fichtner** [comment]
nope, no easy backport. can't verify these findings. don't want to leave things vulnerable by shipping flawed patches...

**Comment by squadramunter** [comment]
You mean these patches are not working properly?

**Comment by fichtner** [comment]
rebased-v2.6-0001-hostapd-Avoid-key-reinstallation-in-FT-handshake.patch does not apply, functions were refactored

**Comment by squadramunter** [comment]
Ah okay. What does this mean?

**Comment by fichtner** [comment]
we wait for freebsd

https://lists.freebsd.org/pipermail/freebsd-current/2017-October/067198.html

**Comment by squadramunter** [comment]
I hope they will fix this soon.

**Comment by fichtner** [comment]
So FreeBSD at least updates wpa_supplicant in ports, I’ve added both this and hostapd to the package build and a test for using installed ports instead of the vulnerable base files. If we male this fix manual for users or migrate to the ports directly I something we cannot say today, for today that is a small win over doing nothing.

**Comment by fichtner** [comment]
@squadramunter  if you have time, the CFT for our fix is here https://forum.opnsense.org/index.php?topic=6183.0

**Comment by fichtner** [comment]
shipped :)
