### ISSUE TITLE
Radius IP Management

### ISSUE THREAD

**Issue by kamcio2603** [opnsense/core#1879]
Hello, 

what do you think about adding to file ipsec.inc  [https://github.com/opnsense/core/blob/master/src/etc/inc/plugins.inc.d/ipsec.inc#L1216](link to exact line)

$authentication .= "\n\trightsourceip = %radius";

Im using it for assigning IP directly from radius, static IP bounded to user account.
I think some of us use this solution by hardcoding source code which is bad and ugly hack.

**Comment by AdSchellevis** [comment]
@kamcio2603 good idea, shouldn't be too hard to add. As soon as I find some time I will add it.

**Comment by AdSchellevis** [comment]
@kamcio2603 if I read the documentation correctly, you could either accept %radius or an address range (which can be configured in the mobile clients tab). https://github.com/opnsense/core/commit/312a42614e4418e66ace47b7e4b879492c326a4e should keep both options valid.
