### ISSUE TITLE
Reshuffle pages / shortcut links for consistency

### ISSUE THREAD

**Issue by reetp** [opnsense/core#188]
Found it a bit confusing when in Status/Ipsec I clicked the 'Logs' tab which jumped me to /diag_logs_ipsec.php

First I had to work out where I was, and then had to work out how to go back to a previous tab in Ipsec status - perhaps it would be better to remove the logs tab ?

**Comment by reetp** [comment]
Alternative thought - make sure there are links on each page to jump you back easily.

**Comment by fichtner** [comment]
Ture, something that I have planned for 16.1 is reshuffling all the pages so that the need for "status" and "diagnostics" mostly disappears and all associated pages can be found in the actual feature, e.g. ipsec log would be a tab of ipsec.

**Comment by fichtner** [comment]
This is mostly done in the develoment version although more fine-tuning is needed. logs can be found in their respective sections now, as well as other pages. Closing.
