### ISSUE TITLE
"Not Found Error" API Exception from BaseModel via Tor Plugin

### ISSUE THREAD

**Issue by fichtner** [opnsense/core#1885]
I'm trying to track this down from the following line that raises the exception:

https://github.com/opnsense/core/blob/master/src/opnsense/mvc/app/models/OPNsense/Base/BaseModel.php#L475

Do you have any idea what could be wrong?

**Comment by fichtner** [comment]
So I thought this was something I did, but it's already in the os-tor 1.0:

Go to Onion Services, Add an onion service, go to Onion Services ACL, add an ACL for the service, go back to the Onion Services, edit the name once. Edit name twice and kaboom:

<img width="945" alt="screen shot 2017-10-20 at 10 25 54 pm" src="https://user-images.githubusercontent.com/1915288/31840471-ceff28f2-b5e5-11e7-95da-469576ec5cb0.png">

**Comment by fichtner** [comment]
Ok, the set action seems to be completely off:

https://github.com/opnsense/plugins/blob/master/security/tor/src/opnsense/mvc/app/controllers/OPNsense/Tor/Api/HiddenserviceController.php#L111-L139

vs.

https://github.com/opnsense/core/blob/master/src/opnsense/mvc/app/controllers/OPNsense/TrafficShaper/Api/SettingsController.php#L105-L118

at least from https://github.com/opnsense/core/blob/master/src/opnsense/mvc/app/controllers/OPNsense/TrafficShaper/Api/SettingsController.php#L149 serializeToConfig should not be called from above, which is where things go south. I'll try to replace that code tomorrow...

**Comment by fichtner** [comment]
@AdSchellevis No, unluckily serializeToConfig() is still in the safe() code and so this keeps failing ;(

**Comment by AdSchellevis** [comment]
@fichtner I'm not sure when your issue occurs, I don't think I have the same options after installation...
![image](https://user-images.githubusercontent.com/9783985/31853744-2a697b86-b68e-11e7-8873-496c646964e3.png)

**Comment by fichtner** [comment]
Oh sorry dev version differs in naming. It’s hidden service and hidden service acl

**Comment by AdSchellevis** [comment]
@fichtner I can't reproduce this (or don't know how to), easiest thing to do usually is to check what endpoint it calls by looking in the network traffic of your browser. I expect a "Not found" when the action isn't in the controller, maybe someone created some JS code that doesn't always call the correct endpoint... If there's a simple test scenario using the version in ports that always fail, I wouldn't mind testing it on my end.

**Comment by fabianfrz** [comment]
@AdSchellevis the problem is on the next tab ("Hidden Services").
If an entry is opened and save clicked, the exception occurs and there is nothing in the servers answer than the error message which is already shown in the screenshot of @fichtner. The Exception is only visible from the crash reporter.

This is quite strange behaviour as all the other controllers are having the same code for set actions and are working.

**Comment by fichtner** [comment]
```
[21-Oct-2017 10:08:32 Etc/UTC] DOMException: Not Found Error in /usr/local/opnsense/mvc/app/models/OPNsense/Base/BaseModel.php:475
Stack trace:
#0 /usr/local/opnsense/mvc/app/models/OPNsense/Base/BaseModel.php(475): DOMNode->removeChild(Object(DOMElement))
#1 /usr/local/opnsense/mvc/app/models/OPNsense/Base/BaseModel.php(512): OPNsense\Base\BaseModel->internalSerializeToConfig()
#2 /usr/local/opnsense/mvc/app/controllers/OPNsense/Base/ApiMutableModelControllerBase.php(160): OPNsense\Base\BaseModel->serializeToConfig()
#3 /usr/local/opnsense/mvc/app/controllers/OPNsense/Tor/Api/HiddenserviceController.php(119): OPNsense\Base\ApiMutableModelControllerBase->save(Object(OPNsense\Tor\HiddenService), Object(OPNsense\Base\FieldTypes\ContainerField), 'hiddenservice')
#4 [internal function]: OPNsense\Tor\Api\HiddenserviceController->setserviceAction('bd58da92-755f-4...')
#5 [internal function]: Phalcon\Dispatcher->callActionMethod(Object(OPNsense\Tor\Api\HiddenserviceController), 'setserviceActio...', Array)
#6 [internal function]: Phalcon\Dispatcher->dispatch()
#7 /usr/local/opnsense/www/api.php(26): Phalcon\Mvc\Application->handle()
#8 {main}
```

**Comment by AdSchellevis** [comment]
ok, I can reproduce this now, a bit strange since I'm almost certain I tried the exact same action yesterday. I'll get back to you later.

**Comment by fichtner** [comment]
thank you 👍

**Comment by fichtner** [comment]
maybe as a side-note,this *does not* happen when you remove the reference to the service from the acl by e.g. deleting it. after that, the edit works as expected again.

**Comment by AdSchellevis** [comment]
ok, think I found the culprit, now the fix.... getElementsByTagName() returns the first "hiddenservice" tag which lies in "hiddenserviceacl", tries to remove it at the root which obviously fails.

**Comment by AdSchellevis** [comment]
@fichtner @fabianfrz https://github.com/opnsense/core/commit/704ba99631339393dd446d166dd51a7530417f68 should fix the culprit, can you test and confirm?

**Comment by fichtner** [comment]
looks good, unit tests pass as well :)

**Comment by fabianfrz** [comment]
looks also good at my end.
