### ISSUE TITLE
HostApd not working after KRACK patch - 20-10-2017

### ISSUE THREAD

**Issue by squadramunter** [opnsense/core#1886]
Hello today I have tested the update that was delivered.

I got some problems with my HostApd config now when I configure a wifi network the client can't see my SSID in the area. Even when I setup WPA2 using AES and TKIP Android fails to find the network. I tried to look at Windows but there I can see my Wireless network but that network seems to be an open network while it has to be locked by a WPA2 passphrase. When I click on my network it refuses to connect to it. Even I like to see a feature update where you can edit the hostapd.conf file in advanced configuration mode. I don't know if that has to be an type error or something but my wireless network does not work as it supposed to be. https://github.com/opnsense/core/commit/f0ad55d

PS. Can I use my TP-LINK TL-WN823N WIFI ADAPTER using OpnSense without problems?

**Comment by fichtner** [comment]
See https://forum.opnsense.org/index.php?topic=6183.msg26150#msg26150

We did not touch / alter config file generation. We only switched the used binaries.
