### ISSUE TITLE
squid: visible_hostname {{OPNsense.proxy.general.VisibleHostname}}

### ISSUE THREAD

**Issue by shacal** [opnsense/core#1888]
Gives in clean install "localhost" as an result.
And exposes header: Via: 1.1 localhost (squid/3.5.27)

**Comment by fichtner** [comment]
@shacal thanks for the report! I removed the default value of "localhost" making this feature opt-in, but only when we release new images, which is OPNsense 18.1. Is this fix ok for you?

**Comment by shacal** [comment]
Sure, in fine with this.
Would like an field on web UI 🙈

**Comment by fichtner** [comment]
@shacal not sure what you mean, it's on the UI :)

General Proxy Settings: enable "advanced mode"

**Comment by shacal** [comment]
I mean that even empty "" hostname or toggle to have that in config or not. 
As that info should not be exported.

**Comment by fichtner** [comment]
@shacal try again with the patch, run from the root shell:

    # opnsense-patch e99275d
