### ISSUE TITLE
PHP warning foreach in vpn_ipsec_phase1.php

### ISSUE THREAD

**Issue by reetp** [opnsense/core#189]
Another one

PHP Warning:  Invalid argument supplied for foreach() in /usr/local/www/vpn_ipsec_phase1.php on line 775

No check for a set variable - this warning was logged even though I only used PSK

I presume this is because I have no certificates setup.

755			<?php
756				foreach ($config['cert'] as $cert):
757					$selected = "";
758					if ($pconfig['certref'] == $cert['refid'])
759						$selected = "selected=\"selected\"";
760			?>

Again a quick "isset" should be used somewhere

**Comment by AdSchellevis** [comment]
should be fixed with https://github.com/opnsense/core/commit/9fe1b635537fe623233b01e6dba6b0da24ec7e48
