### ISSUE TITLE
IPsec - Routing all traffic over a tunnel results in inaccessible firewall

### ISSUE THREAD

**Issue by jschellevis** [opnsense/core#1890]
When forcing all traffic over an IPSec tunnel via remote network 0.0.0.0/0 one can not access the firewall itself anymore as it directs the traffic in the wrong way.

It seems this issue can be resolved by adding an option using passthrough instead of tunnel to leave certain packages untouched. See also https://wiki.strongswan.org/issues/1283

**Comment by AdSchellevis** [comment]
apply https://github.com/opnsense/core/commit/5049d2c84f76419b30977ecd71fbf98de7f3168a  and https://github.com/opnsense/core/commit/76d18ef4664e5a036bf64fd394f505dc2a6183b4 to add the passthrough option to vpn -> ipsec -> advanced settings.
