### ISSUE TITLE
Add net.link.bridge.pfil_local_phys to System Tunables

### ISSUE THREAD

**Issue by knxuf** [opnsense/core#1894]
To use OPNsense as a Firewall which only bridge LAN traffic and still NAT to a WAN

net.link.bridge.pfil_local_phys (default 0)
Set to 1 to additionally filter on the physical interface for locally destined packets. Set to 0 to disable this feature.

**Comment by fichtner** [comment]
It has been added, but please keep in mind this only shows up in new installs with 18.1 onward as we do not manipulate configurations retrospectively.
