### ISSUE TITLE
[MVC] ModelRelationField should prevent deletion of referenced item

### ISSUE THREAD

**Issue by fraenki** [opnsense/core#1897]
The `ModelRelationField` type is a great way to add a reference to another object. I really like it and use it a lot for my plugins.

Unfortunately, it is currently possible to delete the referenced object _without any notice or warning_. This will leave the configuration in an **invalid state**, the validation fails from now on and - most importantly - **model migrations** during an upgrade **will fail**:

```
Oct 26 23:11:31 opnsense config[56018]: [OPNsense\HAProxy\HAProxy:actions.action.0981fe29-5ca1-43de-b356-d351c13d8f67.use_backend] Related backend item not found
Oct 26 23:11:31 opnsense config[56018]: Model OPNsense\HAProxy\HAProxy can't be saved, skip ( Phalcon\Validation\Exception: [OPNsense\HAProxy\HAProxy:actions.action.0981fe29-5ca1-43de-b356-d351c13d8f67.use_backend] Related backend item not found  in /usr/local/opnsense/mvc/app/models/OPNsense/Base/BaseModel.php:509 Stack trace: #0 /usr/local/opnsense/mvc/app/models/OPNsense/Base/BaseModel.php(613): OPNsense\Base\BaseModel->serializeToConfig() #1 /usr/local/opnsense/mvc/script/run_migrations.php(56): OPNsense\Base\BaseModel->runMigrations() #2 {main} )
```

I suggest to disallow the deletion of an object if it's still referenced by a `ModelRelationField` type.
Would this be possible?

**Comment by AdSchellevis** [comment]
It's a bit tricky to validate, the related field doesn't really know it's related. We should be able to add some glue to validate this state, but I don't think we should change the default behaviour.

**Comment by mimugmail** [comment]
Please CC me when there is a change, I also use it heavily in Quagga and it's quite sensible

**Comment by AdSchellevis** [comment]
Ok, we can solve this in our standard controller, but let's keep it "opt-in" to start with.
The idea is actually quite simple, if the (exact)uuid is found in an xml tag (content), which parent has a `uuid` attribute itself and a `version` attribute is found further up in the tree. We can safely assume this item has been referenced.

Add the following in your controller to use:
```
protected static $internalModelUseSafeDelete = true;
```

Which will then produce errors like this:

![image](https://user-images.githubusercontent.com/9783985/68497272-7748f580-0254-11ea-9d69-c583013bb532.png)

For reference I'll leave the path in the exception, so it should be easy to validate.

**Comment by AdSchellevis** [comment]
@mimugmail you wanted to stay posted ^^

**Comment by mimugmail** [comment]
Thx, I will test it next week. Have a nice weekend
