### ISSUE TITLE
Make changes to the view layer (Volt) without overwriting changes when update

### ISSUE THREAD

**Issue by youhackme** [opnsense/core#1898]
Hello,

We had like to modify the view layer e.g in `/usr/local/opnsense/mvc/app/views/OPNsense`.

 However, the issue is if we make modifications in the view layer, all changes will be lost if we upgrade. Is there a way to make views extensible in OPNSense?

Thanks for your help.

Hyder

**Comment by AdSchellevis** [comment]
Hi Hyder,

You can extend the controller (normal inheritance), overwrite the menu (and acl) to use your other endpoint and create a custom view based on the original one. 
In some cases you could probably extend the volt template as well, depending on your changes.


Best regards,

Ad
