### ISSUE TITLE
Legacy 2 MVC

### ISSUE THREAD

**Issue by kekek2** [opnsense/core#1899]
What are the plans in the translation of legacy code to MVC ? Do you need help ?

**Comment by AdSchellevis** [comment]
We are still working in some core areas (mainly firewall), but we can't manage too many changes at once. 
Help is certainly welcome, preferable for features which aren't too big and can easily be migrated, such as diagnostics pages (dns lookup, ping, ...).

Every pull request costs us time to manage and test, which is fine, but we need to spend the limited time we have wisely. 
https://github.com/opnsense/core/issues/1774 for example also needs work, we did pull in the code, but can't spend enough time at the moment to finish it.

Thanks for your support!

**Comment by mimugmail** [comment]
@kekek2 how about certificate Code .. would close #1905

**Comment by AdSchellevis** [comment]
@mimugmail @kekek2  I would suggest starting with smaller things, the trust/certificate section is quite a blob of work, which might result in quite some work for the core team to review as well (which we might not have available at the moment).

**Comment by kekek2** [comment]
The trust/certificates are almost ready, tested. Will soon make pull-request.
