### ISSUE TITLE
RedWood as an alternative to Squid-Cache, possible?

### ISSUE THREAD

**Issue by elico** [opnsense/core#1901]
I am not sure it's the right place to start but.. I am packaging both Squid-Cache and couple others.
One of these is RedWood which is a very good proxy written in GoLang:
https://github.com/andybalholm/redwood/

I have tested it on big systems and it seems that it works much better then Squid-Cache for filtering.
It has lower memory foot print and since it has garbage collection internally unlike Squid-Cache it actually frees memory when there is no need for it.
I have it running on couple systems which have more then 2k users\clients and I am looking for help integrating it into opensense.
@* ??

**Comment by fabianfrz** [comment]
@elico you can add a plugin if you want. For a replacement it lacks many features like for example
* TLS Intercept - needed in some environments
* Transparent Proxy (with PF support)
* ICAP - for av scanning, content manipulation and replacement

However you can build your own plugin to configure it if there is a FreeBSD port. You can look at the plugins HAProxy and Tor for examples (similar plugins).

Here are some docs: https://docs.opnsense.org/development/examples/helloworld.html

**Comment by elico** [comment]
@fabianfrz It doesn'k lack TLS Intercept...
It might not have Transparent Proxy support fir PF but it's not an issue to add this...
ICAP, this software leaves ICAP much behind. If someone needs an  Antivirus he will need more then squid+icap inside OpnSense despite to the fact that many likes this kind of a setup.
I have binaries for FreeBSD and will try to see the other pluglins.

Also take into account that many places uses a proxy in a non-transparent mode and RedWood does so much compared to squid in the Content Filtering field as a stand alone proxy that it's not a question on many environments...

**Comment by fabianfrz** [comment]
@elico so if this software is in the FreeBSD ports, it needs to be added to OPNsense and you can pull it in as a dependency (Go is compiled so different packages are required for amd64, i386 and arm).

The package needs to be made available via the tools repository (`ports.conf`) and then you can install it via pkg on a development VM. The best way is to ask @fichtner for that.

In the next step you will have to fork OPNsense/plugins and create a new feature branch with your plugin code. If needed/desired you can add additional pages like a log viewer, diagnostics pages etc. to your configuration GUI. Those diagnostics pages usually need some scripting language for data processing (you may have to add additional dependencies). Available are Python 2.7, Ruby 2.4, Perl 5 and PHP.

**Comment by fichtner** [comment]
Redwood is not in FreeBSD ports https://www.freshports.org/search.php

I'm all for help in integrating and reviewing plugin work, but we can't spend time on porting software to freebsd where we have a well-working solution.
