### ISSUE TITLE
strange $ sign in  /tmp/rules.debug since 17.7.7, Rules do not get loadet

### ISSUE THREAD

**Issue by peysche** [opnsense/core#1903]
Hi all,

I am facing The following error during applying Rules since 17.7.7, error is not existing in 17.7.6

afacted php Site is ~/firewall_rules.php?if=wan

i simply applied the rule in the shown config at the bottom per GUI to repro this topic

opnsense: /usr/local/etc/rc.filter_configure: New alert found: There were error(s) loading the rules: /tmp/rules.debug:196: macro '' not defined - The line in question reads [196]: pass in  quick on pppoe1 reply-to ( pppoe1 123.123.123.123 )  inet proto {tcp udp}  from {321.321.321.321}  port $ to {(pppoe1)}  port {4500} keep state label "USER_RULE: S2S IPSec" 

for me it lookkls like an bug similar to 

"Nummeric Description for Interface causes syntax error and missconfig for firewall rules #1702"

existing link to bug on Github: https://github.com/opnsense/core/issues/1702

Here are two rule Examples in /tmp/rules.debug one from 17.7.6 and the other one from 17.7.7

17.7.7
pass in  quick on pppoe1 reply-to ( pppoe1 123.123.123.123 )  inet proto {tcp udp}  from {321.321.321.321}  **port $** to {(pppoe1)}  port {4500} keep state label "USER_RULE: S2S IPSec" 

17.7.6
pass in  quick on pppoe1 reply-to ( pppoe1 123.123.123.123 )  inet proto {tcp udp}  from {321.321.321.321} to {((pppoe1)}  port {4500} keep state label "USER_RULE: S2S-IPSec" 

In 17.7.7 you can see a Strange **"port $"** string, with should not be there...

in config file the rule looks like this

`<rule>
	<type>pass</type>
	<interface>wan</interface>
	<ipprotocol>inet</ipprotocol>
	<statetype>keep state</statetype>
	<descr>S2S IPSec</descr>
	<protocol>tcp/udp</protocol>
	<source>
		<address>89.16.200.98</address>
	</source>
	<destination>
		<network>wanip</network>
		<port>4500</port>
	</destination>
</rule>`

config file on 17.7.7 and 17.7.6 looks like the same

If you need more information please let me know.

Thx
Paul

**Comment by fichtner** [comment]
Can you check your port aliases for missing names? Should be easy to spot, even from the /conf/config.xml if the GUI doesn't bring results.

**Comment by fichtner** [comment]
or possibly the rule references an alias that is no longer found :)

**Comment by peysche** [comment]
I am not working with aliases.. so i have no alias in the alias section, it looks for me if i use a target port like 4500 and have no source port defined, then this thing happens, I have only problems with rules where target ports are defined. and port $ in this possitions looks like no sourceport is defined and the logic in the code is doing something wrong and write instad of nothing, or maybe when defined a port the strange port $ thing so i think an NULL variable for an sourceport is not handelt correctly.

**Comment by fichtner** [comment]
Can you try to revert this commit? https://github.com/opnsense/core/commit/bbbb363

    # opnsense-patch bbbb363


Cheers,
Franco

**Comment by peysche** [comment]
Hi, sorry for delay, hat todo a walk with the Dog, reverting this was no success.

i can see that you are focusing on ipsec.. so pleas get not confused by my sample rule, a can repro this with every other rule.

**Comment by fichtner** [comment]
Hi Paul,

No worries and thanks for your help.

I've tried to extrapolate from 17.7.6 vs. 17.7.7 which only the IPsec change was something of interest. We haven't had a lot of changes lately so this is rather odd.

We can apply more force by reverting to 17.7.6:

    # opnsense-revert -r 17.7.6 opnsense

And see if that changes things. My guess now is it won't.


Cheers,
Franco

**Comment by peysche** [comment]
ok i was going back step by step to 1.7.4 nothing was changing error stays the same :-(

i have still 2 systems ongoing on 1.7.6 where everything is working, i will do an snapshot on one of this systems and will upgrade to 1.7.7, lets see if the failure comes up.

all systems was upgradet from 16 to 17 on console.

on the Error System i was going directly from 16 to 17.7.6 and then to 17.7.7. On the working Systems i did a step by step update from 16 to 17.6 i covert every version.

I will test this upgrade now on the other system, as soon is i know more i will respond.

Thx
Paul

**Comment by fichtner** [comment]
Hi Paul,

Thanks so far. I'm assigning @AdSchellevis as I am not available in the next weeks. He wrote the code and can help fix this for sure.


Cheers,
Franco

**Comment by peysche** [comment]
Hi, 

I updated now my other System to 17.7.7, everything is ok, the Port $ is not in the rules.debug.

diff between the 2 systems is mainly the Wan interface, on the Error System it is an pppoe adapter.
The other Systems have an normal Routet NIC to providers Router.

Maybe this info Helps

Regards
Paul

**Comment by AdSchellevis** [comment]
@peysche can you try https://github.com/opnsense/core/commit/bd984071b4faa2ed6d7ad7ccded12fb50d1ba358 on your machine with the issue?

easy to install, using:
`opnsense-patch bd98407`

My assumption is that somehow there's an empty record in your aliases section, resulting in a positive check if "empty" is an alias and adding the $ sign.

**Comment by peysche** [comment]
hi,
i checked the config file as backup and has found out that something is realy not fitting...

```
  <aliases>
    <aliases/>
  </aliases>
```

do not ask me why, i have never ever modified the config manualy...

after removing aliases/ the problem is solved, so i did not tested the patch

as fichtner was thinking the same way, i was only looking into the GUI, and i was knowing that i do not use Aliases...

THX for realy fast response and help !

should i try the patch with the malforemed config file ?

Regards
Paul

**Comment by fichtner** [comment]
Hi Paul,

Yes please, it looks exactly like it solves the issue. Confirmation helps to pick up this patch into the release. It seems worthwhile to avoid such a problem for others. :)

Thank you,
Franco

**Comment by peysche** [comment]
Hi,
Sure i will try it in the afternoon and let you know !

Paul

**Comment by peysche** [comment]
Hi all,

I can confirm that the Error is gone after applying this Patch to the System..

So the root cause is the malformed Aliases XML Tag 

My other 2 systems have aliases, so i assume that there was no error because of existing aliases.

So the question is why the config file was malformed... i have no idear..

Let me know if i can/should test something else...

THX&regards
Paul

**Comment by AdSchellevis** [comment]
Hi Paul, 

I don't know where the xml error came from, but it's good to know we can cope with it using this patch. I suggest we close this issue and we will add this patch to one of the following releases.

Best regards,

Ad

**Comment by peysche** [comment]
Hi Ad,

Patch will fix it.
so its nice when you Implement it to avoid issues like this.
maybe some one will find this and fix his error as well..

i like to say big THX to this Team !!!
You are grate !

Have a nice day off tomorrow !

Regards
Paul
