### ISSUE TITLE
Alias

### ISSUE THREAD

**Issue by abplfab** [opnsense/core#1904]
I dont know since which update... I see the Aliases in the overview, but if I edit an entry, there is no data.
<img width="582" alt="2017-10-29 17_02_33-view _ aliases _ firewall _ durian bug ch" src="https://user-images.githubusercontent.com/28706980/32145563-25e8468a-bccb-11e7-854c-666a9fe82c4f.png">
<img width="589" alt="2017-10-29 17_03_19-view _ aliases _ firewall _ durian bug ch" src="https://user-images.githubusercontent.com/28706980/32145566-2af6fe1e-bccb-11e7-85f8-cec6a0f829ef.png">

**Comment by fichtner** [comment]
Please update to 17.7.7_1 😊

**Comment by abplfab** [comment]
Thanks :)
