### ISSUE TITLE
Feature Request: Search for Trust->Certificates store

### ISSUE THREAD

**Issue by EugenMayer** [opnsense/core#1905]
When you have a number of certificates in the system, the current display of certificates become a bit to bulky. Since we have a multi-line display per certificate with meta informations, you get quiet some verbose output for looking up e.g. "how is the cert validity for certificate X".

It would be great to have a CN / alternative name base search ( combined ) so one could look those up. In this terms, it would be useful to have a search where one could do 'foo.*.domain.tld' to work on a group of domains. Also e.g. having exact matches, e.g. when you have a lot of subdomains and you would need to look to check the validity of domain.tld and you look for "domain.tld" in the search, you get all the 30 domains due to the partial match.

So  a custom asteriks syntax would make sense here, no automated wildcard "contains".

Thanks!

**Comment by AdSchellevis** [comment]
timeout (https://github.com/opnsense/core/commit/7338549ba5f295f5420e45ba74112af10d20c713)
