### ISSUE TITLE
OpenVPN: Status empty after client reboot

### ISSUE THREAD

**Issue by chrisch1974** [opnsense/core#191]
Setup is a Peer to Peer OpenVPN server with one client.

When the client connects the status of OpenVPN is correct.
![status1](https://cloud.githubusercontent.com/assets/1726822/7706214/4717841c-fe49-11e4-9b69-b359fb3d2f07.png)

After a client reconnect (reboot) the status shows only blank entries.
![status2](https://cloud.githubusercontent.com/assets/1726822/7706244/81e723d6-fe49-11e4-84de-8aad1ca193f7.png)

After a restart of the OpenVPN server the status is correctly again.

**Comment by fichtner** [comment]
This is somehow related to OpenVPN and the status socket being unresponsive. Not sure how to work around this?

**Comment by fichtner** [comment]
Can't think of anything other than an upstream OpenVPN bug report, sorry.

**Comment by chrisch1974** [comment]
Output of the management interface of the OpenVPN server confirms a problem of OpenVPN itself:
( echo "state all" ; sleep 1 ; echo "quit" ) | nc -U /var/etc/openvpn/server1.sock

>INFO:OpenVPN Management Interface Version 1 -- type 'help' for more info
1435591619,CONNECTING,,,
1435591619,ASSIGN_IP,,10.8.222.1,
1435591624,ADD_ROUTES,,,
1435591676,AUTH,,,
1435591676,WAIT,,,
1435591683,CONNECTED,SUCCESS,10.8.222.1,x.x.x.x
1435629641,WAIT,,,
1435716041,WAIT,,,
1435802441,WAIT,,,
END
