### ISSUE TITLE
Possible 2FA Fallback Bug

### ISSUE THREAD

**Issue by bigops** [opnsense/core#1910]
While configuring 2FA with authenticator it works only when the fallback is set to None.  If Local database is the fallback when 2FA is entered the login fails, but the login is possible with the password alone without the OTP

**Comment by AdSchellevis** [comment]
that's logical (not a bug), if you fallback to a method without 2FA it doesn't need your token for the second authenticator attempt.

**Comment by bigops** [comment]
The issue is not of fallback.  If the 2FA is configured with the Fallback as the Local database, 2FA does not work.  It gives an error wrong username and password. 

But if only the username and the local password is provided it will logon without 2FA.  

The possible bug is when the fallback is configured and 2FA does not work.  If fallback is disabled then 2FA works.

**Comment by fichtner** [comment]
Some unsers reported 2FA being useless with local fallback and this after over a year is the first that said it doesn’t work at all in that case. From a code perspective this is very unlikely. Do you have the steps to reproduce?

**Comment by AdSchellevis** [comment]
Just to be sure, I've just tested 2FA in combination with fallback which authorises both (user/2fa+pass and user+pass).
It's a useless combination, but works like expected on my end.

**Comment by fichtner** [comment]
PS: to respond to your forum question... any primary auth server is reset to local auth via the console password reset (option 4). Make sure to set your console to auto login and physically secure access for an uncomplicated reset procedure.

**Comment by bigops** [comment]
Looks like this happens only when the server is configured for such a combination initially without a reboot.  I tested in another newly minted machine and the behaviour is the same as not allowing me to login, but after a reboot it works as expected.  

Thanks for all the help.
