### ISSUE TITLE
[Bug] VLAN Routing drops after WAN Interface reload

### ISSUE THREAD

**Issue by PitchBendStretch** [opnsense/core#1912]
Hi guys,

My setup is based on inter-VLAN-routing, while using LACP.
My OPNsense version is: 
`OPNsense 17.7.7_1-amd64
FreeBSD 11.0-RELEASE-p12
OpenSSL 1.0.2l 25 May 2017`

Since a few days my ISP is having problems which are leading to Interface reloadings from configd.py from time to time, which then end up in inter-VLAN routing problems. I get little drop outs to my NAS in another VLAN, while streaming music for example. This error came up:
![wan error](https://user-images.githubusercontent.com/23058346/32407168-4d3eb9da-c185-11e7-82ee-63ba6898072e.PNG)

When this happens, the connection to the file gets lost and thats really annoying.
Why is my WAN default Gateway intercepting inter-VLAN-routing which is directly connected?
When the WAN Interface reloads, my NAS is not able to answer, but it is a stateful packet inspection Firewall so there should be no need to add additional rules:
![nas error tcp_pa](https://user-images.githubusercontent.com/23058346/32407175-537b9890-c185-11e7-98fa-a098728a751d.PNG)

I changed one setting here, which maybe solved the problem but i am not sure:
![gateway monitoring error](https://user-images.githubusercontent.com/23058346/32407182-6b30701e-c185-11e7-9613-c6b347cc5d65.PNG)

I deleted every VPN setting but still this is showing up in the system logs:
`configd.py: [9bfef01c-16c1-4b6f-b303-c7341b49c1ba] Reloading filter` 
![openvpn wan reload](https://user-images.githubusercontent.com/23058346/32407184-7cf0f1ac-c185-11e7-810a-07e0469d45da.PNG)

I checked my offloading settings, but it didn't change after enabling or disabling Hardware Filtering, so that can't be the issue. Just for your interest, all my NICs are Intel NICs:
`VLAN Hardware Filtering: Enable VLAN Hardware Filtering`

Best regards,
Pitch

P.s.: While writing this i again had a Disconnect from the Internet "WAN_DHCP" Down, but the apinger state didn't got flushed so the connection to my NAS stayed up. Is that normal behaviour?

**Comment by AdSchellevis** [comment]
just a quick note on "Restarting OpenVPN tunnels", it's only the event, it doesn't do anything if there are no tunnels configured, details in:

https://github.com/opnsense/core/blob/9386226bdc3d1fbb28f9f49cf5ed4930cf3571d0/src/etc/inc/gwlb.inc#L96

**Comment by PitchBendStretch** [comment]
Thank you very much for clarifying, since this was a big question on my mind. So i searched for something, which wasn't there anymore. Good to know. :)
