### ISSUE TITLE
Traffic Graph not showing correctly

### ISSUE THREAD

**Issue by jeffg2k** [opnsense/core#1913]
Not sure at what version this started to occur, but I have no traffic listed in large "Out" graph.  And on the little mini-graphs (per ip), no "In" traffic is listed.  "status_graph.php"

Running version 17.7.7, but I know the issue was present in 17.7.5 as well.

**Comment by fabianfrz** [comment]
@jeffg2k please check if you have IPS enabled. IPS blocks that.

**Comment by jeffg2k** [comment]
Yes, IPS mode is enabled.  But it's always been enabled.  Any way to exclude the traffic reporting from the IPS?

**Comment by mimugmail** [comment]
Would you first try disabling it and check of it works?

**Comment by jeffg2k** [comment]
Yes, turning off IPS mode corrects the issue.  I don't see that as a good solution, but it does fix it.

**Comment by mimugmail** [comment]
This is not a solution, only better to track down the problem. This one is already known that with IPS enabled packets in one direction are not seen ...

**Comment by AdSchellevis** [comment]
it could be a driver issue, what network chip are you using?

**Comment by mimugmail** [comment]
Virtualbox:
```
em0@pci0:0:3:0: class=0x020000 card=0x001e8086 chip=0x100e8086 rev=0x02 hdr=0x00
    vendor     = 'Intel Corporation'
    device     = '82540EM Gigabit Ethernet Controller'
    class      = network
    subclass   = ethernet

```

Physical:
```
igb0@pci0:1:0:0:        class=0x020000 card=0x00018086 chip=0x15218086 rev=0x01 hdr=0x00
    vendor     = 'Intel Corporation'
    device     = 'I350 Gigabit Network Connection'
    class      = network
    subclass   = ethernet
```

**Comment by AdSchellevis** [comment]
you have the same issue with both drivers?

**Comment by mimugmail** [comment]
Yep, two different systems.

https://forum.opnsense.org/index.php?topic=5911.0

**Comment by jeffg2k** [comment]
How to I list the drivers in opnsense / bsd?  Seems dmsg doesn't go back very far, I don't see a /etc/modules.conf, no lspci.

**Comment by mimugmail** [comment]
`pciconf -lv`

**Comment by jeffg2k** [comment]
dmesg.boot has this:
> em0: <Intel(R) PRO/1000 Network Connection 7.6.1-k>
> em1: <Intel(R) PRO/1000 Network Connection 7.6.1-k>

pciconf -lv:
> em0@pci0:0:25:0:	class=0x020000 card=0x00008086 chip=0x10bd8086 rev=0x02 hdr=0x00
>     vendor     = 'Intel Corporation'
>     device     = '82566DM-2 Gigabit Network Connection'
>     class      = network
>     subclass   = ethernet


> em1@pci0:6:0:0:	class=0x020000 card=0x00008086 chip=0x108b8086 rev=0x03 hdr=0x00
>     vendor     = 'Intel Corporation'
>     device     = '82573V Gigabit Ethernet Controller (Copper)'
>     class      = network
>     subclass   = ethernet

**Comment by AdSchellevis** [comment]
What are your "sort by" and "filter" settings?

**Comment by jeffg2k** [comment]
I have the defaults, which are Bw In and Local.  Changing the "sort by" didn't fix anything, but changing the "filter" to All does fix the "Bandwidth In" on the mini-graphs.  The large Out (bps) graph is still 0.

**Comment by AdSchellevis** [comment]
It's highly likely a kernel issue with netmap, the graphs use two different command's (ifinfo, rate) to gather statistics which both seem to stall.

**Comment by mimugmail** [comment]
Yep .. there's a bit weirdness in kernel, netmap and suricata ... also like this:
https://forum.opnsense.org/index.php?topic=6190.0

KVM or ESX .. some guys need to set to e1000 but for some only vmxnet3 helps.

**Comment by AdSchellevis** [comment]
should be same as https://github.com/opnsense/core/issues/1632, likely fixed when we disable netmap libpcap support

**Comment by fichtner** [comment]
Same as https://github.com/opnsense/core/issues/1632 - IPS makes "out" direction disappear in PCAP capture mode.

**Comment by ghost235** [comment]
Sorry for warming this up, but the issue seems to be back on 20.7.4 on vmware 6.5.0 with e1000.  IPS is on

**Comment by AdSchellevis** [comment]
@ghost235 https://github.com/opnsense/core/issues/4272

**Comment by ghost235** [comment]
thanks i found just after post ;)
