### ISSUE TITLE
IKEv2 Port issue in Firewall rules

### ISSUE THREAD

**Issue by bigops** [opnsense/core#1914]
I have an **OpnSense OPNsense 17.7.7_1-amd64** configured for IKEv2 VPN, but i am noticing that the VPN can be successfully established even though I have not opened any ports on the firewall.  If there are automatic rules being configured they are not being displayed in the GUI.  I am concerned that this could be a potential issue.  The documentation for IKEV2 says that the ports need to be opened (https://docs.opnsense.org/manual/how-tos/ipsec-road.html?highlight=ikev2) 

![firewall rules](https://user-images.githubusercontent.com/26052053/32468117-9f1598b2-c312-11e7-8330-84c2c530b967.PNG)
![ipsec3](https://user-images.githubusercontent.com/26052053/32468118-9f26b9d0-c312-11e7-9b2a-196ce8cb81d9.png)
![ipsec2](https://user-images.githubusercontent.com/26052053/32468119-9f3b4e2c-c312-11e7-8d25-a5caf902b3c1.png)
![ipsec1](https://user-images.githubusercontent.com/26052053/32468120-9f4b847c-c312-11e7-9e9d-453f81ff21b3.png)

**Comment by AdSchellevis** [comment]
yes, these rules are generated automatically, see https://github.com/opnsense/core/blob/17.7.7/src/etc/inc/plugins.inc.d/ipsec.inc#L193 

They can be disabled using "Disable all auto-added VPN rules." in vpn -> ipsec -> advanced settings.

**Comment by bigops** [comment]
Thanks.  That explains.  Maybe this could be a feature request to have these auto added rules show up in the Interface rules similar to the anti-lockout rules.

**Comment by AdSchellevis** [comment]
I think there already is one for it, but it's not very trivial... We still have quite some work to do cleaning up / refactoring the nat/portforward code (https://github.com/opnsense/core/issues/1326).

The way rules are generated now would eventually make it possible to rebuild the user interface, but the amount of work needed todo so is quite immense.

Can you close this issue now?

**Comment by bigops** [comment]
Thanks.
