### ISSUE TITLE
Feature request: make the "full help" setting "sticky"

### ISSUE THREAD

**Issue by ljm42** [opnsense/core#1915]
As a new user, I find that I am clicking the "full help" button in the upper right corner on nearly every page load.

Can we make that a "sticky" setting? So click "full help" once to have the help text load by default on every page until you click the "full help" button again to turn it off?

This would be an enormous benefit to new users. Experienced users probably never turn help on, but if they do it would only be a single additional click to turn it back off.

**Comment by ljm42** [comment]
Yes, I think a cookie would be fine. The setting doesn't need to be stored in your user profile, if you move between browsers you can deal with turning help on as needed.

**Comment by fabianfrz** [comment]
@AdSchellevis You can use the local storage like for the scroll lock.

**Comment by AdSchellevis** [comment]
@fabianfrz I know, I added that one too ;) Time is the only thing keeping this from happening at the moment.  I can assign myself, eventually this will be there.... The question has been there more often and it's quite practical to have.

**Comment by AdSchellevis** [comment]
In case anyone likes to test, the command below installs the feature (on a recent version of OPNsense)

`opnsense-patch 7e3906a09`

**Comment by ljm42** [comment]
Thanks for this @AdSchellevis it works great! This should be extremely helpful.

**Comment by fichtner** [comment]
Nice, thank you!

**Comment by fichtner** [comment]
@AdSchellevis can we do the same for advanced?

**Comment by AdSchellevis** [comment]
sure, will fix in a minute

**Comment by AdSchellevis** [comment]
@fichtner https://github.com/opnsense/core/commit/2826d6206e0e5bf9d4ebecc323426c2ce80b10aa

**Comment by fichtner** [comment]
perfect, thank you <3

**Comment by fichtner** [comment]
I have to reopen this briefly for a fix (I'll do it after investigation):

https://forum.opnsense.org/index.php?topic=6444.0

Sometimes the stores are deactivated and should therefore not stop all the pages from working. Maybe we can add an if check or something....

**Comment by fabianfrz** [comment]
This is quite strange but the setting `dom.storage.enabled` to false, will cause that `window.localStorage`  will be undefined. A possible fix would be disabling the feature be wrapping it into an if statement looking like this:
```js
if ('localStorage' in window) {
//code
}
```

**Comment by fichtner** [comment]
@fabianfrz if you want to propose a fix please do, that looks promising. Till can help text over at the forum.

**Comment by fabianfrz** [comment]
@fichtner will create a PR which should fix this.

**Comment by fabianfrz** [comment]
@fichtner #1972

**Comment by fichtner** [comment]
thank you!
