### ISSUE TITLE
Feature request: search for specific settings

### ISSUE THREAD

**Issue by ljm42** [opnsense/core#1916]
I really like the OPNsense menu system with integrated search box. However, it is sometimes frustrating that the search box can only access page titles and not configuration settings themselves.

For instance, it would be great if searching for "hostname" pulled up the "Systems: Settings: General" page. 

Of if "syslog" pulled up "System: Settings: Logging"

Or if "radius" pulled up "System: Access: Settings" and "System: Access: Servers" in addition to the various "Services: FreeRadius" pages.

As it is now, I often do a Google search for "opnsense <keyword>" to figure out where something is.

Perhaps the menu search function can be extended to include keywords from the pages themselves?

**Comment by AdSchellevis** [comment]
I think the menu system can already do that, but generating all the correct tags is quite some work. In case you would like to work on gathering keywords, I can check the possibilities (with an example) for you.

**Comment by fichtner** [comment]
To be fair, only the mvc pages can do this easily. But it takes a bit of time to work on a proper index format for lookups and how the search is presented. Ideally, an index should be generated after installing a new plugin or updating the core package.

**Comment by fichtner** [comment]
PS: suggested cross-reference of e.g. Radius is subject to proper field names, we can’t arbitrarily glue parts together that happens to have model relationships. At least I expect this to be too much work and explaining why these relationships exist is something that cannot be explained in a search window nor derived from the relationships easily. That’s what documentation and how-to are for. :)

**Comment by ljm42** [comment]
I was originally thinking the search terms would be maintained manually, perhaps as a "keyword" attribute in the Menu.xml files.  I took a shot at coming up with keywords for the System: Settings pages

```
<General order="100" url="/system_general.php" keyword="hostname,domain,time zone,language,theme,dns">
<Administration order="200" url="/system_advanced_admin.php" keyword="ssl,webgui,anti-lockout,dns rebind,compression,http_referer,ssh,root,console,serial,sudo" />
<Logging order="300" url="/diag_logs_settings.php" keyword="syslog,local,remote,reset,filter" />
<Notifications order="400" url="/system_advanced_notifications.php" keyword="growl,smtp,email,sounds,beep" />
<Miscellaneous order="500" url="/system_advanced_misc.php" keyword="cryptographic,hardware,thermal sensors,backup,power,battery,swap,ram" />
<Tunables VisibleName="Tunables" order="600" url="/system_advanced_sysctl.php" keyword="debug,vfs,net.inet,kern.ipc,hw" >
```

But extrapolating from your comments... perhaps the search index could be generated automatically from the forms/*.xml files? That would be awesome. Always up to date, zero manual effort.

And I see your point on the Radius example, particularly if the Radius plugin isn't installed. But if the search index is updated automatically when the plugin in (un)installed... maybe?

**Comment by AdSchellevis** [comment]
I don't think we should automatically index the form xml files, most need more context and legacy code won't work.
We should be able to add an extra level in the menu xml to handle keywords/references, bit it all boils down to quite some work to build all the indexes.

**Comment by fichtner** [comment]
The main question is where is setting xxx, xxx being a specific setting like a checkbox on any given page at any point in time. If we can cross-reference menu entires with their forms that’s enough info. We can’t maintain a list of (marginally) useful keywords, keep track of restructuring, plugins, etc. Plus the translation automatically works here and we could try to anchor / navigate to the correct tab in a future edition.

**Comment by fichtner** [comment]
Ps: we could also ship each index precompiled with the package during build time, that afterwards only requires merging plugins and core index files for lookups.

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository, 
please read https://github.com/opnsense/core/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue, 
just let us know, so we can reopen the issue and assign an owner to it.
