### ISSUE TITLE
Drop diag_logs_filter.php in 18.1

### ISSUE THREAD

**Issue by AdSchellevis** [opnsense/core#1917]
With https://github.com/opnsense/core/issues/1788 stacked for 18.1 I would like to suggest the removal of the old "Normal" view (diag_logs_filter.php).

The codebase is pretty old and messy, doesn't really bring more functionality to the table then the new live view and the feature to quickly add firewall rules based on log output isn't very solid anyway.

**Comment by fichtner** [comment]
Sounds good. Maybe we can merge both by slapping the current normal log filter behaviour on top. It’s really time to rework this plumbing internally as well, i was thinking syslog-ng usage for exported streams to finally support TCP and proper host name write but keep clog/syslogd combo a bit longer for internal use. 😊
