### ISSUE TITLE
[BUG] Traffic Shaper: Queue/Pipe statistics viewable in Status after deletion

### ISSUE THREAD

**Issue by mimugmail** [opnsense/core#1918]
Hi,

not sure if this is known/normal behavior. I did some testing with Traffic Shaper and wanted to start from scratch. Deleted all Rules, Save. Deleted all Q's, Save. Deleted all Pipes, Save. But this after some time it's still there in Status:

```
Limiters:
10000:  10.000 Mbit/s    0 ms burst 0 
q75536  50 sl. 0 flows (1 buckets) sched 10000 weight 0 lmax 0 pri 0 droptail
 sched 75536 type FIFO flags 0x1 256 buckets 0 active
    mask:  0x00 0x00000000/0x0000 -> 0xffffffff/0x0000


Queues:
q10000  50 sl. 0 flows (1 buckets) sched 10000 weight 100 lmax 0 pri 0 
q10001  50 sl. 0 flows (1 buckets) sched 10000 weight 1 lmax 0 pri 0 
```

Is there a way to reset without rebooting? And is this fixable? :)

**Comment by fichtner** [comment]
There is a flush button on the shaper page somewhere for this reason. This is the normal behaviour of ipfw. Operationally it doesn’t matter.

**Comment by mimugmail** [comment]
Ah great, I thought this is something for the specific tab, thanks! :)
