### ISSUE TITLE
squid configuration produced bungled localnet entry when an ipv6 ip alias is used

### ISSUE THREAD

**Issue by wytchmaster** [opnsense/core#1919]
When using a network virtual IP alias with an ipv6 unique local unicast address fdxx::/64 the config backend produces an acl entry with a wrong prefix length:

`acl localnet src fd42:1313:815:1::254/fd42:1313:815:1::254 # Possible internal network`

this should be

`acl localnet src fd42:1313:815:1::254/64`

The malformed entry prevents squid to start.

**Comment by AdSchellevis** [comment]
@wytchmaster can you try https://github.com/opnsense/core/commit/20cf2eb64d70c06824316cfcb8c9ac2a73e59fcc ?

`opnsense-patch 20cf2eb64d`

**Comment by wytchmaster** [comment]
I willbtry it tomorrow. Sorry for the delay, I was very busy on the job.

**Comment by AdSchellevis** [comment]
no problem, thanks in advance

**Comment by wytchmaster** [comment]
looks good. The acl entry is well-formed now. Thanks.
