### ISSUE TITLE
Theme / improve tab presentation

### ISSUE THREAD

**Issue by AdSchellevis** [opnsense/core#1922]
The current tabs used in our new codebase float a bit too much in my opnion,

![image](https://user-images.githubusercontent.com/9783985/32690042-0a1d64d8-c6f0-11e7-81bc-0a2440dd4df5.png)

I would like to suggest to make the tabs a bit more "tab-like", such as
![image](https://user-images.githubusercontent.com/9783985/32690066-6a57c83e-c6f0-11e7-8171-ec1108ade491.png)

**Comment by fichtner** [comment]
Sure, as long as the stacked tabs (web proxy) also get a clearer representation as well. There was a ticket somewhere recently.

**Comment by AdSchellevis** [comment]
I see what I can fix for that one as well, it needs some work.

**Comment by fabianfrz** [comment]
I like the style of the tabs in Firefox (but that may not work with the dropdown menu):
![screenshot_20171111_192234](https://user-images.githubusercontent.com/3713914/32692294-acbebb54-c715-11e7-9fc1-c764bcc2a901.png)

**Comment by AdSchellevis** [comment]
@fabianfrz They certainly look nice, but I don't think I can integrate that smoothly with the rest of the layout. Maybe for a next step.

**Comment by AdSchellevis** [comment]
![image](https://user-images.githubusercontent.com/9783985/32702427-67ba313c-c7e7-11e7-97d9-e0ce3515b0e4.png)

**Comment by fraenki** [comment]
Great, @AdSchellevis! This was just recently suggested by someone using the HAProxy plugin! Good timing! :+1:

**Comment by fichtner** [comment]
The dashed line is a visual flow stopper, I can’t help but this maybe it should be removed? The intention is clear, but even the normal bootstrap examples avoid this and there is no lack in functionality.

I think the people who miss these selectors will always miss them as they are hard to extrapolate in any case.

**Comment by AdSchellevis** [comment]
It would look like this without it 
![image](https://user-images.githubusercontent.com/9783985/32768217-3701b39a-c917-11e7-9853-9dc6febe3969.png)

To be honest, I don't think I fancy it more without the dashed line. What do you think?

**Comment by fichtner** [comment]
It looks cleaner that way, only the arbitrary padding is making this look off (the padding between word and icon is bigger than the padding between the word/icon and the edges.

**Comment by AdSchellevis** [comment]
Sorry, I'm not completely sure what you mean. If you can find some time, can you add an example?

**Comment by fichtner** [comment]
The space between the tab text and the dropdown icon is too wide, probably double the size of the normal padding, where that dashed line used to be.

**Comment by AdSchellevis** [comment]
this?
![image](https://user-images.githubusercontent.com/9783985/32836882-9af32448-ca0b-11e7-9d05-6c6b7315397d.png)

**Comment by fichtner** [comment]
Yes, I like this very much. Other opinions? @mimugmail @fabianfrz @fraenkie

**Comment by AdSchellevis** [comment]
ok, I'm fine with this too. Will check it in now.

**Comment by fabianfrz** [comment]
looks good

**Comment by mimugmail** [comment]
Go for it 👍

**Comment by fichtner** [comment]
With the new cool layout I noticed to this:

* The new dark line for all inactive tabs / table head is too dark and think with the pretty rework done to outline inactive tabs we don't really need it:
<img width="652" alt="screen shot 2017-11-19 at 8 10 17 am" src="https://user-images.githubusercontent.com/1915288/32988292-5aa59a08-cd01-11e7-8bf9-ec2c43f716ff.png">
* Legacy tabs don't follow this layout. Should we change it or really simply to to get rid of them? see #1928 
<img width="1186" alt="screen shot 2017-11-19 at 8 13 26 am" src="https://user-images.githubusercontent.com/1915288/32988303-8fd0169a-cd01-11e7-8a1a-7e95072939de.png">

**Comment by AdSchellevis** [comment]
Personally I liked the dark line to accent the tab more, I've experimented with different styles, but this one was the clearest in my opinion. 
For core packages I can look into migrating the tabs, old legacy plugins I don't want to spend time on (unless it's the exact same implementation and can work without extra effort).

**Comment by AdSchellevis** [comment]
It's intentional that it only underlines the tab section.... Personally I really don't think it looks off, but if removing is what it takes to end this subject, feel free to remove.

**Comment by fichtner** [comment]
I'm sorry to nag you with this. I'm trying to raise a question that is likely going to come up with our users when we ship this, so we have a good answer for why this was designed the way it is. I'm just not convinced we have the best answer yet.

**Comment by AdSchellevis** [comment]
I'm not sure we can ever find a good answer for either layouts, it's about preferences... some people may like this, others won't. I just want to avoid starting a beauty contest for something this small, I can live with both versions. In terms of visibility both aren't that different (the line might even be a bit better, but I'm really not an expert on that subject).

In the end, people are free to propose different options, but I only ask to do the work for it too then... (fixing the css can cost quite some time)

**Comment by fichtner** [comment]
I don't want to keep anyone from doing other work or ask for other people's time, but I do need to ask whether I'm having stupid ideas or not and if you are ok with them in the end. Nothing worse than people working on the same thing pulling in different directions.

I'll fiddle with the CSS. I really like this work, so please don't let me that that away from you in any way. :)

**Comment by AdSchellevis** [comment]
ok, thanks. I really think these are the last tiny details.... We'll get there :)

**Comment by fichtner** [comment]
Maybe like this?

<img width="1127" alt="screen shot 2017-11-19 at 5 18 33 pm" src="https://user-images.githubusercontent.com/1915288/32992674-caadf6c8-cd4d-11e7-9cce-2e56ab11b5b3.png">

**Comment by AdSchellevis** [comment]
ok, that is indeed very nice! Do I need to add it to the sass file for you? Just post the css attributes if needed.

**Comment by fichtner** [comment]
I can fix this in the sass I think, currently fighting with the primary colouring of the stacked tabs in web proxy. That may take a bit more time. :)

**Comment by AdSchellevis** [comment]
if you need help, just let me know

**Comment by fichtner** [comment]
@AdSchellevis try 65e18d2, the bordering was done around li but li &gt; a was used for stacked tabs. not entirely sure about the scss.

**Comment by AdSchellevis** [comment]
it looks good, did you compile the scss?

**Comment by fichtner** [comment]
no, just fixed it up accordingly

**Comment by AdSchellevis** [comment]
ok, let me compile/test and commit it then.

**Comment by fichtner** [comment]
thanks for bearing with me ❤️

**Comment by AdSchellevis** [comment]
The result looks great! thanks, https://github.com/opnsense/core/commit/53765207761932e0a501c969d022e66541cdd854  contains the compiled version.

**Comment by fichtner** [comment]
ok, got a bit sloppy with the build css style at the end it seems :) thanks again!
