### ISSUE TITLE
[Feature] Add burst value to Traffic Shaper

### ISSUE THREAD

**Issue by mimugmail** [opnsense/core#1923]
@AdSchellevis Is there a reason why there's no field for configuring a burst value in the pipe?
In the template there's no value (so 0), but technically it shouldn't be a problem to add 
`{{ burst|default('0') }}` 
to the pipe command?

Opinions? :)

**Comment by AdSchellevis** [comment]
@mimugmail yes, last time we checked/tested, burst didn't work. see https://github.com/opnsense/core/commit/31175631197e3cd15b70a2cd89865b5c11ddbc2a

**Comment by fichtner** [comment]
Context and old code via https://github.com/opnsense/core/issues/226

**Comment by mimugmail** [comment]
Thanks for the hints, I'll have a look :)
