### ISSUE TITLE
Crash report after every reboot.

### ISSUE THREAD

**Issue by borisneubert** [opnsense/core#1924]
Right after every reboot I am informed about a crash. System: Firmware: Reporter | Submit this report runs forever. Attached files are copied from the System: Firmware: Reporter page.

OPNsense 17.7.7_1-amd64
FreeBSD 11.0-RELEASE-p12
OpenSSL 1.0.2l 25 May 2017

[logs.zip](https://github.com/opnsense/core/files/1464792/logs.zip)

**Comment by AdSchellevis** [comment]
```
All buffers synced.
swap_pager: I/O error - pagein failed; blkno 4204018,size 4096, error 5
panic: swap_pager_force_pagein: read from swap failed
cpuid = 0
KDB: stack backtrace:
db_trace_self_wrapper() at db_trace_self_wrapper+0x2b/frame 0xfffffe02317d9830
vpanic() at vpanic+0x182/frame 0xfffffe02317d98b0
panic() at panic+0x43/frame 0xfffffe02317d9910
swapoff_one() at swapoff_one+0xa24/frame 0xfffffe02317d9990
swapoff_all() at swapoff_all+0x197/frame 0xfffffe02317d99d0
bufshutdown() at bufshutdown+0x45c/frame 0xfffffe02317d9a20
kern_reboot() at kern_reboot+0x244/frame 0xfffffe02317d9a80
sys_reboot() at sys_reboot+0x58c/frame 0xfffffe02317d9ad0
amd64_syscall() at amd64_syscall+0x4ce/frame 0xfffffe02317d9bf0
Xfast_syscall() at Xfast_syscall+0xfb/frame 0xfffffe02317d9bf0
```

Looks like an issue with your swap configuration or the disk itself, depending on how the machines is installed you could try disabling swap in /etc/fstab if it's enabled there or disable the swap file in the UI (system_advanced_misc.php).

**Comment by borisneubert** [comment]
Thank you @AdSchellevis, I turned off the swap file  leaving the swap partition.  Issue resolved.

Since I did not dismiss the crash report, still some garbled content gets displayed in the System: Firmware: Reporter. This is because the files in /var/crash are gzipped (now):

```
root@opnsense:/var/crash # ll
total 123284
-rw-r--r--  1 root  wheel         29 Nov 12 16:02 bounds.gz
-rw-r--r--  1 root  wheel        385 Nov 12 16:04 crashreport_header.txt.gz
-rw-r--r--  1 root  wheel       7481 Nov 12 16:04 dmesg.boot.gz
-rw-------  1 root  wheel        371 Nov 12 16:02 info.0.gz
lrwxr-xr-x  1 root  wheel          6 Nov 12 16:02 info.last@ -> info.0
-rw-------  1 root  wheel  126162010 Nov 12 16:02 vmcore.0.gz
lrwxr-xr-x  1 root  wheel          8 Nov 12 16:02 vmcore.last@ -> vmcore.0
```

I suppose the submission of the crash reports takes forever due to the size of the core dump (126MB gzipped). This is probably not intended.

**Comment by AdSchellevis** [comment]
it looks like we forgot to limit the filesize for submission, I will add a 2MB max per file and close the issue.

**Comment by borisneubert** [comment]
That's fine for me.
