### ISSUE TITLE
IGMP Proxy is too old

### ISSUE THREAD

**Issue by timur-davletshin** [opnsense/core#1925]
Current version of igmpproxy does not support v.3. Looks like sourceforge is abandoned and moved to https://github.com/pali/igmpproxy which provides support for v.3.

Report:

RECV V2 member report   from 192.168.0.121   to 225.77.225.2
Updated route entry for 225.77.225.2 on VIF #2
RECV unk: 0x22/0x00     from 80.82.58.46     to 224.0.0.22
ignoring unknown IGMP message type 22 from 80.82.58.46 to 224.0.0.22
RECV Leave message      from 192.168.0.121   to 224.0.0.2
leaveMcGroup: 225.77.225.2 on pppoe0

**Comment by AdSchellevis** [comment]
can you please open this issue in https://github.com/opnsense/plugins ? igmp is not part of our core system (https://github.com/opnsense/plugins/tree/master/net/igmp-proxy).

**Comment by timur-davletshin** [comment]
Done. Sorry for posting it in the wrong place.

**Comment by AdSchellevis** [comment]
no problem, thanks for moving.
