### ISSUE TITLE
tap0 interface not joining bridge0 at boot.

### ISSUE THREAD

**Issue by lallhands** [opnsense/core#1926]
OPNSense version 17.7.5-amd64
FreeBSD 11.0-RELEASE-p12

Intel platform

So I have created at tap0 interface and added it to bridge0 along with em1. Whenever I boot up and run ifconfig I see only em1 as a member of the bridge.

bridge0: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500
        ether 02:ac:8a:46:e4:00
        nd6 options=1<PERFORMNUD>
        groups: bridge
        id 00:00:00:00:00:00 priority 32768 hellotime 2 fwddelay 15
        maxage 20 holdcnt 6 proto rstp maxaddr 2000 timeout 1200
        root id 00:00:00:00:00:00 priority 32768 ifcost 0 port 0
        member: igb1 flags=143<LEARNING,DISCOVER,AUTOEDGE,AUTOPTP>
                ifmaxaddr 0 port 2 priority 128 path cost 55

If I run "ifconfig bridge0 addm tap0 up" from the CLI or open and save the bridge config in the GUI then tap0 joins bridge0. 

bridge0: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500
        ether 02:ac:8a:46:e4:00
        nd6 options=1<PERFORMNUD>
        groups: bridge
        id 00:00:00:00:00:00 priority 32768 hellotime 2 fwddelay 15
        maxage 20 holdcnt 6 proto rstp maxaddr 2000 timeout 1200
        root id 00:00:00:00:00:00 priority 32768 ifcost 0 port 0
        member: tap0 flags=143<LEARNING,DISCOVER,AUTOEDGE,AUTOPTP>
                ifmaxaddr 0 port 19 priority 128 path cost 2000000
        member: igb1 flags=143<LEARNING,DISCOVER,AUTOEDGE,AUTOPTP>
                ifmaxaddr 0 port 2 priority 128 path cost 55

**Comment by AdSchellevis** [comment]
where did the tap0 interface come from the first time?

**Comment by lallhands** [comment]
I believe I added it from the GUI. It is there now and I do not believe I have it configured anywhere else. I can check though.

**Comment by AdSchellevis** [comment]
to be able to reproduce an issue, we need to know what you did and how you did it.

**Comment by lallhands** [comment]
Right, thanks for the help too! 

So I just checked and I created tap0 at boot from a script that I run in  /usr/local/etc/rc.syshook.d/ with an 85-domotz.start. I'm creating a virutal machine running Ubuntu Server to perform some advanced services.

##############################
####
#!/bin/sh

bhyvectl --destroy --vm=linuxguest

grub-bhyve -m /root/device.map -r hd0,msdos1 -M 1024M linuxguest

sleep 1

bhyve -A -H -P -s 0:0,hostbridge -s 1:0,lpc -s 2:0,virtio-net,tap0 -s 3:0,virtio
-blk,/root/linux.img -l com1,stdio -c 4 -m 1024M linuxguest

Is that throwing the timing off for adding tap0 to the bridge?

**Comment by AdSchellevis** [comment]
You probably need to register an interface into the plugin system, which you can then add to the bridge. For some pointers on how to do this for your own code, you could look at other plugins (for example https://github.com/opnsense/plugins/blob/master/security/tinc/src/etc/inc/plugins.inc.d/tinc.inc#L82)

**Comment by lallhands** [comment]
Thank you - very helpful!

**Comment by fichtner** [comment]
Change the name of your syshook script from „start“ to „early“. You are creating the tap0 device after network setup currently, I guess that is the only issue...
