### ISSUE TITLE
web-proxy: Feature request: restrict Remote Black Lists to subnets

### ISSUE THREAD

**Issue by borisneubert** [opnsense/core#1927]
This is potentially related to https://github.com/opnsense/plugins/issues/356

It should be possible to restrict Remote Black Lists to subnets. For example, to have different black lists for the office and the guest net, or for the parents' and the children's net.

Would require to add a subnet box to the "Edit Blacklist" dialog. Assume we have a blacklist "Shalla_Office" assigned to the "office" net 192.168.35.0/24, the corresponding entries in squid.conf would be

```
acl remoteblacklist_Shalla_Office dstdomain "/usr/local/etc/squid/acl/Shalla_Office"
acl subnets subnets_Shalla_Office 192.168.35.0/24
adaptation_access response_mod deny remoteblacklist_Shalla_Office subnets_Shalla_Office
adaptation_access request_mod deny remoteblacklist_Shalla_Office subnets_Shalla_Office
http_access deny remoteblacklist_Shalla_Office subnets_Shalla_Office
```

**Comment by fichtner** [comment]
@evbevz @kekek2 if you are interested in this let us know :)

**Comment by kekek2** [comment]
We are interested, but not now.

**Comment by AdSchellevis** [comment]
timeout (https://github.com/opnsense/core/commit/7338549ba5f295f5420e45ba74112af10d20c713)

**Comment by borisneubert** [comment]
This means no one has picked the feature request and implemented it within a reasonable time? Would it make sense to request that wonderful feature again in a few months?
