### ISSUE TITLE
System: remove authentication fallback in favour of a list of servers like in vpn

### ISSUE THREAD

**Issue by fichtner** [opnsense/core#1929]
This also requires #1689 to be able to reorder authentication, it seems useful to do auth against multiple servers in an arbitrary order.

- [x] kill autmode_fallback
- [x] allow multiple autmode
- [x] help text in authmode
- [x] kill/merge settings page
- [x] kill legacy LDAP connection tester
- [x] opnsense-auth-test
- [x] GUI login test
- [x] password policy settings to server edit (Local Database)
- [x] add back hide/unhide password policy settings
- [x] password policy compat test

**Comment by AdSchellevis** [comment]
it's not very high on my list of priorities, it doesn't happen very much that people need a large list of servers. The tokenizer doesn't seem to come with sorting, so that would be another challenge.
Feel free to fix, I just miss the big gain here. 

(p.s. auto adding the new entries on a tokenizer is likely a small fix, some focus event I guess)

**Comment by fichtner** [comment]
b78654eb should do it, only need to add a "fallback" help text note and repair whatever the LDAP tester did in the settings page... :)

**Comment by fichtner** [comment]
@AdSchellevis would you be ok with merging System: Access: Settings into System: Settings: Administration? it looks like the same place and we also have admin GUI, SSH and integrated auth knobs there.

**Comment by AdSchellevis** [comment]
@fichtner yes, that looks more logical indeed.

**Comment by fichtner** [comment]
@AdSchellevis another question:

There is a largely unmaintained LDAP connection tester embedded into the old settings page... I don't think it works anymore, mostly because it assumes that the first server is an LDAP server:

https://github.com/opnsense/core/blob/master/src/www/system_usermanager_settings_test.php#L35

The code is triggered via:

https://github.com/opnsense/core/blob/master/src/www/system_usermanager_settings.php#L37

Since we have another tester which will also do user / pass testing should we just remove it?

**Comment by AdSchellevis** [comment]
@fichtner ok, that doesn't make sense indeed. let's kill it

**Comment by fichtner** [comment]
@AdSchellevis not sure you like it, but the policy settings made even more sense in the local database server edit... I've added an edit button there and will add back the hide/unhide with a few final tests tomorrow to see if I haven't broken these policy enforcements.

**Comment by fichtner** [comment]
Err, see d13da15cb

**Comment by AdSchellevis** [comment]
@fichtner I was doubting about this in the first place, but choose the other spot because eventually the authenticator should supply his needs with listConfigOptions(), which would suggest there's a hook and a config section for the local authenticator.... but functional I have no objections with moving the settings (so feel free to proceed).
Fixing all the settings just cost a bit too much time at the moment, which is also what's holding LDAP+TOTP at the moment, the plugin itself I build a long time a go, just missing the settings.

**Comment by fichtner** [comment]
I agree, it's a bit of a hack now more than before, authservers page is full of do-this-or-that and the worst thing is "Local Database" is a bit of an empty shell for doing all sorts of things for the web GUI mostly, but session timeout is not one of those things... At least from here the policy settings make the most logical sense to not let users trip over "why does it not work?".

I think all these changes are for 18.7 now anyway so we don't have to worry about 18.1 performance. It also gave a bit of attention for dirty authentication spots, but so far everything looks, feels and works as expected. So yay for this at least. :)

**Comment by AdSchellevis** [comment]
yay :)

**Comment by fichtner** [comment]
@AdSchellevis all done here, but more questions regarding the password policy duration and possibly others:

* during login we have the password, but length check is not enforced (my test password was 5 characters while it had 8 characters set), same likely goes for complexity
* add more possible character lengths (minimum is nice, but smaller minimum might be required as it can't be enabled selectively, or we add a "0" length option for any length

What do you think?

**Comment by AdSchellevis** [comment]
@fichtner we  could check constraints on login too, maybe that would indeed be better to force the user into a "change password" trap after changing policies. Adding more lengths is probably a good idea too, although I don't think 0 would be necessary (not much use of having a policy when none is needed I guess).
