### ISSUE TITLE
php warning file_put_contents(/var/etc/ipsec/dump_test): failed to open stream

### ISSUE THREAD

**Issue by reetp** [opnsense/core#193]
Sorry - another one.... feel like a bug hunter ;-)

When using the VPN settings I get this warning in the logs

PHP Warning:  file_put_contents(/var/etc/ipsec/dump_test): failed to open stream: No such file or directory in /usr/local/etc/inc/vpn.inc on line 795

The offending lines are here

794	if (!empty($ealgoESPsp2arr)) {
795		file_put_contents("/var/etc/ipsec/dump_test", print_r($ealgoESPsp2arr, true));
796		$ipsecconf .= "\tesp = " . join(',', $ealgoESPsp2arr) . "!\n";
797	}

ls /var/etc/ shows no ipsec directory

As I am not sure about the intentions I can't suggest a fix. Should it get dumped to /tmp or another place, or should a directory /var/etc/ipsec be created somewhere ?

There is also a reference here that doesn't seem to exist

local/www/status.php:161:defCmdT("ipsec.conf","cat /var/etc/ipsec/ipsec.conf");

Should that be /usr/local/etc/ipsec.conf ?

**Comment by fichtner** [comment]
Meh, misspelled the name. Sorry!

First one was debug output never being used, second one fixed according to your suggestion. "/var/etc/ipsec" is no longer found in the code base. :)

**Comment by reetp** [comment]
:-) 

Will try and test / verify some fixes. Had to dump the machine I was using for testing so will rebuild again.
