### ISSUE TITLE
syslogd: restart when a new plugin is registered?

### ISSUE THREAD

**Issue by fraenki** [opnsense/core#1930]
[Some plugins](https://github.com/opnsense/plugins/blob/223e92eedb084ddfe6cfd055248b5f15e9a6d6ac/net/haproxy/src/etc/inc/plugins.inc.d/haproxy.inc#L35-L46) register additional syslog configuration.

Usually this requires to restart syslogd, otherwise the log does not work or is empty (the latter is the case for HAProxy). But I couldn't find a way to do it right. Currently, the only way for a user to restart syslogd is to reboot OPNsense, right?

I thought of adding a (legacy) `system_syslogd_stop()` function, similar to the [start function in system.inc](https://github.com/opnsense/core/blob/807b526443c40331c0e8599a33f37c292e3a7ccb/src/etc/inc/system.inc#L731). But this would require that each plugin restarts syslogd if it adds a syslogd configuration, which doesn't sound right.

A better approach would be to have the syslogd component automatically detect changes (plugin added or removed) and restart accordingly.

How should this be solved – what do you think?

**Comment by fichtner** [comment]
We have some leeway here, it's not possible to do this without a syslog restart, but we can do it by chaining it through our new configd/pluginctl subsystem.

**Comment by fichtner** [comment]
Since we have moved to caching ACL and menu files, we can fix this without plugin interaction. Commit follows in a second. :)
