### ISSUE TITLE
OpenVPN: Wrong routing of iroute when using Server Mode Remote Access

### ISSUE THREAD

**Issue by mimugmail** [opnsense/core#1932]
Hi,

I setup an OpenVPN server in Server Mode "Remote Access" with Client certificates. 
My goal is to have 50 branches to connect their LAN to the server LAN. 

Since I don't want to create 50 servce instances I'm using "Remote Access" as Server Mode. The problem here is that the local network at the client wont get pushed to the server. So now I created a Client Specific Override and set the remote network at the server. 

This works fine and I can see the echo requests and replies at the LAN side of the server, but the replies go out through WAN and not the opvpns1 interface. Don't know why this happens .. when I check "Show Routing Table" in Connection Status I can see the client network there, but wont get routed.

Also tried enabling/disabling topology mode .. no success.

Any ideas?

**Comment by mimugmail** [comment]
Seems to be the same as #1283

When I set a route via CLI it works .. strange thing :(

**Comment by mimugmail** [comment]
Workaround: In server config in Advanced: `route clientnet subnet`

Would be cool to have a field for this so no advanced fields are needed :)

**Comment by AdSchellevis** [comment]
@mimugmail Is the change your proposing just overriding this to enable the route push on other modes then p2p? https://github.com/opnsense/core/blob/7ced5ac1b909ff44e29c8bbcff358e3223ad65ce/src/etc/inc/plugins.inc.d/openvpn.inc#L820-L823

**Comment by AdSchellevis** [comment]
I looks to me that we can just remove the check for p2p, the local networks (remote_network, remote_networkv6) are normally empty and only used in this spot for as far as I can see. It doesn't really make sense to ask for a value and then forget about it..

@fichtner what do you think?

**Comment by fichtner** [comment]
I have no strong opinion on this particular issue. 😊

**Comment by AdSchellevis** [comment]
@mimugmail can you try https://github.com/opnsense/core/commit/35dd2ea09cc5e133192281cb341e042bec6e0fc7 ?

**Comment by fichtner** [comment]
Context: https://github.com/pfsense/pfsense/commit/17c98ba9 and https://redmine.pfsense.org/issues/1707

**Comment by mimugmail** [comment]
@AdSchellevis Sorry, no route in routing table ...

**Comment by AdSchellevis** [comment]
@mimugmail can you inspect the openvpn config in /var/etc/openvpn/? it should have added the exact same route tag (after save/reload of the config)

**Comment by mimugmail** [comment]
@AdSchellevis No, I also rebooted the machine, no `route 10.0.90.0 255.255.255.0` in conf and no route in routing table

**Comment by AdSchellevis** [comment]
@mimugmail my mistake, I forgot to actually show the remote_network/remote_networkv6 options for the other server modes. can you try https://github.com/opnsense/core/commit/91c849306841a7a7886de6a1b3a828250919d569 ?

**Comment by mimugmail** [comment]
Works, thanks! 👍

**Comment by kandev** [comment]
I am using OPNsense 20.7.3-amd64 and this issue is still present.
Subnet routes configured as "Client specific" > "IPv4 Remote Network" are not pushed to system routing table when the client connects.

**Comment by mimugmail** [comment]
Can you please open a thread in the forums with more details?

**Comment by kandev** [comment]
> Can you please open a thread in the forums with more details?
Of course:
https://forum.opnsense.org/index.php?topic=19637.msg90416#msg90416
