### ISSUE TITLE
Unable to create internal certificate authority

### ISSUE THREAD

**Issue by itheiss** [opnsense/core#1933]
Hi,

I just installed OPNsense 17.7.7_1 on my brand new hardware and wanted to create an internal certificate authority. After filling all fields and clicking 'Save' I am presented  with the following error messages. 

![16-11-_2017_10-21-14](https://user-images.githubusercontent.com/2655169/32883931-0633066c-cab9-11e7-8a60-6d2ace4c2d87.jpg)

No matter what I tried, I am unable to create an internal certificate authority. Is this a know bug or I am just to stupid?

Best Regards
Ingo

**Comment by AdSchellevis** [comment]
Hi Ingo,

I've never seen this before, can't reproduce it either on my end (using openssl) using the same input.
Are you using OpenSSL (the default) or LibreSSL) ?

What does the following output?

`/usr/local/bin/openssl version
`

Best regards,

Ad

**Comment by fichtner** [comment]
It looks like a flakey install, please provide the output of these two commands:

    # pkg check -da
    # pkg check -sa

**Comment by itheiss** [comment]
Hi Ad, hi Franco,

I am using the default (OpenSSL). Here is the requested output:

```
root@OPNsense:~ # /usr/local/bin/openssl version
OpenSSL 1.0.2l  25 May 2017
```

and

```
root@OPNsense:~ # pkg check -da
Checking all packages: 100%
```
```
root@OPNsense:~ # pkg check -sa
Checking all packages: 100%
```

Best regards,
Ingo

**Comment by itheiss** [comment]
Whoop!
Got it working after rebooting and reinstalling OpenSSL from Firmware -> Packages.
Really strange ...

Thank you both for your quick replies. I am closing the issue. If you want me to collect some more info leave me a note.

Best regards,
Ingo

**Comment by fichtner** [comment]
Hi Ingo,

We need a consistent error state, but that is no longer the case. Can’t be sure what happened. In any case happy it works now. 😊

From the two commands it seemed that OpenSSL was properly installed and all files passed the checksum test.


Cheers,
Franco
