### ISSUE TITLE
configd / custom template overwrites / overlay

### ISSUE THREAD

**Issue by AdSchellevis** [opnsense/core#1934]
From time to time people ask for functionality that doesn't really fit our core system, but uses parts of the system already in place (which makes it hard/impossible to use our plugin system to extend).

A nice example of such a feature is https://github.com/opnsense/core/pull/1882 , which most likely will not make it into our system because there's no use case for it in scenarios we support.
Other examples are complex suricata scenario's which can't be configured from the gui.

One way of dealing with this is to support overwrites on our templating system to use your own modifications, although there are downsides in doing this it could offer vendors the possibility to maintain their own version of our plugins and users the option to overwrite our defaults.

The addition I would like to propose here is an extension to the `+TARGETS` file, named `+TARGETS.overlay`, which can register new targets or overwrite the ones which are already in the normal targets. So, an example:

For squid we would like to create our custom configuration, which overwrites our defaults which are statically configured.
_src/opnsense/service/templates/OPNsense/Proxy/+TARGETS.overlay_ 
`squid.conf.custom:/usr/local/etc/squid/squid.conf
` 

And the original installed by default.
_src/opnsense/service/templates/OPNsense/Proxy/+TARGETS_
```
rc.conf.d:/etc/rc.conf.d/squid/squid
squid.conf:/usr/local/etc/squid/squid.conf
newsyslog.conf:/etc/newsyslog.conf.d/squid
```

The downsides are:

- You can only have one overwrite per module, so two packages trying to install an overwrite will fail on install (we won't accept plugins using overwrites, for obvious reasons)
- Changes on default templates won't propagate to the custom templates, so vendors do need to maintain their own templates.

I will add a commit referencing this issue later on, up for discussion.

**Comment by fichtner** [comment]
What if we glob and order +TARGETS.*, it would create an arbitrary number of possible overwrites.

Normal target file first of course.

**Comment by AdSchellevis** [comment]
I don't mind adding a glob, as long as we suffix them with something that makes it obvious that it is an overwrite (to prevent accidental files from being processed, such as +TARGET.old). 

It might increase the possibilities a bit, but there can only be one template per described target (it can't/won't merge)

**Comment by fichtner** [comment]
It doesn‘t have to merge, we just need to make sure our normal templates in +TARGETS are first, and then we can iterate through any number of overrides. But making a safe glob pattern is hard. What if we create a +TARGETS.D directory instead? But what to ignore and what not is still a problem unless we say no file on there is ignored?

**Comment by AdSchellevis** [comment]
a +TARGETS.D directory sounds good to me, what if we scan for files there that end on .TARGET?

so one can create an overwrite for squid.conf like this:

`src/opnsense/service/templates/OPNsense/Proxy/+TARGETS.D\squid.conf.TARGET
`

**Comment by fichtner** [comment]
Lots of semantics for newcomers, but sounds good to me as long as prefix of the file is only cosmetic, not functional (content stays the same)

**Comment by AdSchellevis** [comment]
Well, the upside is this should only be used by people who know what their doing ;) 
I will add a probe for +TARGETS.D directory, contents won't change, with this we have something to point integrators to (without having to discuss pulls that won't make it).

Thanks for your feedback

**Comment by chelming** [comment]
> so one can create an overwrite for squid.conf like this:
> 
> `src/opnsense/service/templates/OPNsense/Proxy/+TARGETS.D\squid.conf.TARGET`

is this working as intended? it appears that squid.conf.TARGET will be read as a target and look for paths specified in it but won't actually override squid.conf located a directory above?

the actual practice appears to be: inside of +TARGETS.D create a file like `override.TARGET` containing
```
example_simple_page.txt:/tmp/template_sample/simple_page.txt:/tmp/template_sample/simple_page.*
```
and creating example_simple_page.txt in the `src/opnsense/service/templates/OPNsense/Proxy` directory.

Based on the conversation in here and on the [target overwrites page](https://docs.opnsense.org/development/backend/templates.html#target-overwrites) I was assuming that any matching file + '.TARGET' in the +TARGETS.D directory would override the file one directory higher but that appears to not be the case.

**Comment by AdSchellevis** [comment]
@chelming 
> the actual practice appears to be:
> Inside of +TARGETS.D create a file like override.TARGET containing
> ...

That is indeed the intended purpose, overwrite definitions with custom ones. 

https://github.com/opnsense/core/blob/88ab77fc85ec0d06dbb9fda72da7daae88a45704/src/opnsense/service/modules/template.py#L90-L93


> ... I'm not sure what the benefits of the +TARGETS.D directory would be otherwise vs just using a file like +TARGETS.overrides that contained target overrides.

Overwrite system defined or plugin defined configuration files with those of your own. As mentioned in the docs, handle with care as the original configuration file is likely subjected to change. If one would like to ship a custom `squid.conf` for example, you can divert the configuration output with one of your own.

**Comment by chelming** [comment]
I think my confusion is based around overriding the target vs overriding
the config file itself. Based on the documentation it makes it seem like
you can override the conf file by putting a new one in +TARGETS.D as
opposed to a generic .TARGET file with the definition for the file to be
overridden.

>Overwrite system defined or plugin defined configuration files with those
of your own.

Right, I get the purpose, but what's the difference between having separate
+TARGETS.D/users.conf.TARGET and +TARGETS.D/base.conf.TARGET files vs one
single +TARGETS.D/overrides.TARGET file with definitions for base.conf and
users.conf like the +TARGETS file?

**Comment by AdSchellevis** [comment]
> Right, I get the purpose, but what's the difference between having separate
> +TARGETS.D/users.conf.TARGET and +TARGETS.D/base.conf.TARGET files vs one
> single +TARGETS.D/overrides.TARGET file with definitions for base.conf and
> users.conf like the +TARGETS file?

There isn't, all files are processed in order so different "vendors" can plug different files from the base target definition file.

**Comment by chelming** [comment]
Got it, thanks. I want to try and update the documentation for people like
me who are unfamiliar with targets to add some clarity and an example of
how to override a specific file and wanted to make sure I understood what
was happening.
