### ISSUE TITLE
Feature Request: IDS Alert list additions

### ISSUE THREAD

**Issue by tpcr** [opnsense/core#1935]
I would like to see the IDS alerts page also show source and destination ports and which interface it was generated on in the main IDS alert listing. A choice of which categories to display would also be helpful.

I am requesting an addition to the list of displayed alerts in IDS in the WebGUI. This dropdown list should show the ports and the interface. I know the ports are shown in the detail, but they should also be shown in the list. The Interface that triggered the alert is not shown anywhere which is useful when IDS is attached to multiple interfaces

**Comment by AdSchellevis** [comment]
I was working on https://github.com/opnsense/core/issues/1911 and thought it was a good idea to add the port and interface fields in the grid too.

![image](https://user-images.githubusercontent.com/9783985/32969551-d91268e8-cbe5-11e7-914a-d757be5933ad.png)
![image](https://user-images.githubusercontent.com/9783985/32969563-e3312a8a-cbe5-11e7-8afa-7dbfd733b87f.png)


To test, first install https://github.com/opnsense/core/issues/1911

`opnsense-patch 14d0ce9`

Then the work done for this issue
`opnsense-patch 18515f15`

**Comment by tpcr** [comment]
Works great. A must have for the next release. Thanks loads!

**Comment by fichtner** [comment]
I’ll pull these in for 17.7.8 as long as they have no compatibility issues with the jquery bump.

**Comment by tpcr** [comment]
There is a problem with the patch. If you delete the alert log it crashes OPNsense.
A reboot is needed to get the WebGUI back, but the console is still working.

**Comment by AdSchellevis** [comment]
@tpcr doesn't seem to be related, the patches only really extend javascript in the browser.

**Comment by tpcr** [comment]
Must have something to do with it because whenever I install the patches, as soon as I start messing with IDS settings the OPNsense network crashes, but the shell is still accessible in the console. Is there any log that may shed some light on this.

**Comment by AdSchellevis** [comment]
a good place to start is always /var/log/system.log

**Comment by tpcr** [comment]
The previous tests were with IPS enabled. Doesn't seem to do it with IPS disabled, but I may have some other issues with IPS. Still working on it.

**Comment by tpcr** [comment]
Seems to be working now with IPS enabled after a reinstall and patches reapplied,

**Comment by fichtner** [comment]
I've added this to 17.7.8, small hiccup with the pre block as usual...

<img width="719" alt="screen shot 2017-11-20 at 6 37 55 am" src="https://user-images.githubusercontent.com/1915288/33003974-5b666c3e-cdbe-11e7-806a-458b84547b4f.png">

**Comment by fichtner** [comment]
This also, we need to zap the "+" prior to interface lookup:

<img width="518" alt="screen shot 2017-11-20 at 6 49 26 am" src="https://user-images.githubusercontent.com/1915288/33004075-0ae3a078-cdbf-11e7-91d8-82200817c643.png">

**Comment by fichtner** [comment]
@AdSchellevis I'll take care of both :)

**Comment by AdSchellevis** [comment]
@fichtner thanks!

**Comment by tpcr** [comment]
Good work!
