### ISSUE TITLE
Internal IP address can't match policy route rules

### ISSUE THREAD

**Issue by apsnowolf** [opnsense/core#1936]
I have a MutilWAN environment use opnsense 17.7.7, pureNAT is enabled.
WAN1==IP1 WAN2==IP2   default gateway is WAN2 GW。

I want setup pptpvpn, but pptp server only can listening on an lan IP address.
I creating a forwarding rule in NAT section, that sends incoming IP1 pptp traffic (gre and tcp1723) to the lan ip.
but it's not work well.
I capture package in wan port,  gre out package NAT to the wrong IP address: IP2.

I creating policy route rule(SIP=IanIP protocol=GRE  forword to WAN1 GW), but  it can't match internal IP address .

This looks like a bug？

**Comment by AdSchellevis** [comment]
timeout (https://github.com/opnsense/core/commit/7338549ba5f295f5420e45ba74112af10d20c713)
