### ISSUE TITLE
radvd does not advertise addresses for virtual IPs

### ISSUE THREAD

**Issue by wytchmaster** [opnsense/core#1937]
The radvd configuration does not provide a section for virtual ips. If you use any virtual ip from the fc00::/7 range for Unique Local Unicast, no advertisements are configured. The radvd.conf only has the configuration for the "real" interfaces.

**Comment by fichtner** [comment]
The whole config for radvd is based on static IPv6 addresses from the interface setting itself. To support this, what would be necessary to change in the radvd.conf file? I am not sure we can easily add new configuration blocks for virtual IPs here...

**Comment by wytchmaster** [comment]
There should be a  prefix stanza for every IPv6 address in the interface definition. This is, what I use on my Linux-Router:

```
interface enp1s0 {
        AdvSendAdvert on;
        AdvLinkMTU 1280;
        MaxRtrAdvInterval 120;
        prefix 200x:x:x:x::/64 {   
                AdvOnLink on;
                AdvAutonomous on;
                AdvRouterAddr on;
        };
        prefix fd42:1313:815:1::/64 {
                AdvOnLink on;
                AdvAutonomous on;
                AdvRouterAddr on;
        };
        
};

```
One prefix stanza for the public IP-Range and one for the IP-alias with the unique local unicast address.

**Comment by fichtner** [comment]
@wytchmaster that looks doable, give me some time to integrate this :)

**Comment by fichtner** [comment]
You can try the proposed patch 9471303 with the following command... needs another commit, some other radvd improvement via 38c1daa

# opnsense-patch 38c1daa 9471303

If anything goes wrong:

# opnsense-revert opnsense

Cheers,
Franco

**Comment by wytchmaster** [comment]
I will try to check that this evening.

**Comment by wytchmaster** [comment]
works like a charm :-) Thank you.

**Comment by fichtner** [comment]
purrfect, thanks! expecting this to land in 17.7.10. if not, please prod again :)

**Comment by fichtner** [comment]
Will be in 17.7.9 :)
