### ISSUE TITLE
syslog exits on signal 11

### ISSUE THREAD

**Issue by wytchmaster** [opnsense/core#1938]
Syslog exits with signal 11. I have already reset the logfiles multiple times. If I start syslog with the "original" config file /etc/syslog.conf it does not die. But that is of course not what I want ...

**Comment by fichtner** [comment]
Is this still the case? Is there anything in dmesg? I have a newer syslogd package we could try.

**Comment by wytchmaster** [comment]
I moved the installation from a KVM based VM to to physical hardware. After restoring the config from backup, it seems to be fine.

**Comment by fichtner** [comment]
Ok, closing until able to reproduce. Thanks!
