### ISSUE TITLE
squid should have a "expert configuration" option

### ISSUE THREAD

**Issue by wytchmaster** [opnsense/core#1939]
In pfsense it's possible the insert native squid configuration fragments. This would be nice to have in opnsense, as the GUI does not offer options to fine tune the configuration. In my case I want to have multiple delay pools for traffic management.

**Comment by fabianfrz** [comment]
We don't want that and will probably refuse that whenever it is possible because this cannot be validated and may break the service. In your case, you can add it via the CLI via the plugin hook (a directory which is automatically included) or request a feature to configure those delay pools via the web interface.

**Comment by wytchmaster** [comment]
Ok. But in other services it's possible (unbound for example). And that's really helpful if one has some uncommon settings ....

**Comment by fabianfrz** [comment]
@wytchmaster also uncommon settings can be made available via the GUI. This settings can be marked as advanced and will not be shown to the user by default (those forms have a button in the top left corner of the form - for example like the proxy pages).

OpenVPN, Unbound etc. however are legacy pages (no MVC) which does not have the new form system and will probably be replaced in the future (might not be very soon).

If the pages are converted, it will be very simple to add new options as it will require changes only at three places (form, model and template).

**Comment by wytchmaster** [comment]
OK. I got it :-) So I will try the plugin hook first ... Thanks for your explanations.
