### ISSUE TITLE
IPSEC change WAN does not change route

### ISSUE THREAD

**Issue by reetp** [opnsense/core#194]
I setup an IPSEC 192.168.97.0 connection on WAN1. If I edit it and change to WAN2 the interface changes, but not the gateway. I deleted the whole entry and set it up again just using WAN2 but it still picks the wrong gateway.

WAN1
IPv4 address 	192.168.201.11
Subnet mask IPv4 	255.255.255.0
Gateway IPv4 	192.168.201.1

Internet:
Destination        Gateway            Flags       Use    Mtu      Netif Expire
default            192.168.201.1      UGS       11269   1500        em1
localhost          link#6             UH            0  16384        lo0
192.168.10.0       link#1             U         12166   1500        em0
OPNsense           link#1             UHS           0  16384        lo0
192.168.88.0       link#7             U          5167   1500        ue0
192.168.88.3       link#7             UHS           0  16384        lo0
192.168.97.0       192.168.201.1      US            0   1500        em1  ** Here
192.168.201.0      link#2             U          2424   1500        em1
192.168.201.11     link#2             UHS           0  16384        lo0
resolver2.opendns. 192.168.201.1      UGHS          0   1500        em1
resolver1.opendns. 192.168.201.1      UGHS         45   1500        em1

WAN2 
IPv4 address 	192.168.88.3
Subnet mask IPv4 	255.255.255.0
Gateway IPv4 	192.168.88.1

Internet:
Destination        Gateway            Flags       Use    Mtu      Netif Expire
default            192.168.201.1      UGS       11265   1500        em1
localhost          link#6             UH            0  16384        lo0
192.168.10.0       link#1             U         11825   1500        em0
OPNsense           link#1             UHS           0  16384        lo0
192.168.88.0       link#7             U          4902   1500        ue0
192.168.88.3       link#7             UHS           0  16384        lo0
192.168.97.0       192.168.201.1      US            0   1500        ue0  **Here
192.168.201.0      link#2             U          2173   1500        em1
192.168.201.11     link#2             UHS           0  16384        lo0
resolver2.opendns. 192.168.201.1      UGHS          0   1500        em1
resolver1.opendns. 192.168.201.1      UGHS         27   1500        em1

**Comment by fichtner** [comment]
Is this still the case?

**Comment by reetp** [comment]
Sorry Franco - been up to my ears in a pile of other stuff so had no time to test. I'll see if I can check for you ASAP.

**Comment by fichtner** [comment]
No worries mate, wait for 15.7 tomorrow before testing. Lots of goodness coming. :)

**Comment by reetp** [comment]
KK - thanks :-)

**Comment by reetp** [comment]
Was going to go have another play but not sure which version to use. Open/Libre SSL or Hardened BSD?

**Comment by AdSchellevis** [comment]
I'm not sure what version you used the last time when you had an issue, I'm using the OpenSSL version most of the time.

**Comment by reetp** [comment]
Was using OpenSSL 15.1 before but as I can see some new choices I wondered which might be the best

**Comment by AdSchellevis** [comment]
It's a question of preference I guess, some like Libre more, others like Hardened or OpenSSL more. :)

**Comment by fichtner** [comment]
Timeout
