### ISSUE TITLE
Unbound: Generated zone file does not honour assigned dhcp domain names for opnsense host

### ISSUE THREAD

**Issue by Slugger** [opnsense/core#1940]
**Version: 17.7.7_1**

I have a setup with 3 VLANs and the management network:

re1 (opt3): 192.168.13.1/24
re1_vlan44 (lan): 192.168.44.1/24
re1_vlan55 (opt1): 192.168.55.1/24
re1_vlan66 (op2): 192.168.66.1/24

On the dhcp config, the domains for these are setup as follows:

opt3: home.mgmt
lan: home.main (note: home.main is also the configured system domain for opnsense)
opt1: home.guest
opt2: home.iot

Unbound is configured to register all dhcp addresses and it does, except it creates 4 records for the 4 interfaces above, but uses the home.main domain for all of them.

This generates 4 A records for router.home.main, one for each IP above (router is the hostname assigned to opnsense) and responses appear to be round robined between all 4.  The problem with this is that each vlan above is isolated and cannot talk to each other.  So if I'm connected to anything other than vlan44 and try to resolve "router" it does not resolve (as each vlan is told to search it's own domain by default, not home.main).  If I'm connected to vlan44 and try to connect to router it will be fine as long as unbound happens to return the vlan44 address, but if it returns any of the other 3 then I can't connect as I'm trying to cross vlans.

Unbound should register the ip with the associated domain name from the dhcp configuration (and default to the system assigned domain when not set) instead of just always using the system configured domain.

**Comment by fichtner** [comment]
Hi @Slugger,

Does not work, a known limitation in the service that looks for DHCP leases and dynamically registers them. The service only uses the DHCP leases file which has no info about the interface / domain of the lease. You can override the used domain name, but that's it.


Cheers,
Franco

**Comment by Slugger** [comment]
I've been experimenting this morning and it appears the `global $config` object referenced in `plugins.inc.d/unbound.inc` has all of the dhcp config info available at the time it's building the zone file.  Could it not lookup the assigned dhcp domain for each interface when building the zone file?  Or is there a reason this shouldn't be done?

**Comment by fichtner** [comment]
are we talking about static or dynamic dhcp hosts?

**Comment by Slugger** [comment]
Static, I guess.  I'm looking at the `unbound_add_host_entries()` function and the first thing it does is create the host entries for itself, but it's hardcoded to use `$config['system']['domain']` for all the entries is creates instead of looking for the interface in the dhcp config and using the assigned domain name from there, when available.

**Comment by fichtner** [comment]
ok, that looks fixable. hold on...

**Comment by fichtner** [comment]
We are talking about this blob? https://github.com/opnsense/core/blob/master/src/etc/inc/plugins.inc.d/unbound.inc#L539-L565

**Comment by Slugger** [comment]
Yup

**Comment by fichtner** [comment]
Try this:

    # opnsense-patch 84bd7d8
    # pluginctl dns

**Comment by Slugger** [comment]
Works well.  Only _possible_ issue I'm seeing in the generated zone file are the entries for the naked host names:

```
local-data-ptr: "192.168.55.1 router.home.guest"
local-data: "router.home.guest A 192.168.55.1"
local-data: "router A 192.168.55.1"
local-data-ptr: "192.168.66.1 router.home.iot"
local-data: "router.home.iot A 192.168.66.1"
local-data: "router A 192.168.66.1"
local-data-ptr: "192.168.44.1 router.home.main"
local-data: "router.home.main A 192.168.44.1"
local-data: "router A 192.168.44.1"
local-data-ptr: "192.168.13.1 router.home.mgmt"
local-data: "router.home.mgmt A 192.168.13.1"
local-data: "router A 192.168.13.1"
```
Not sure if those might conflict with each other still?  I didn't see any issues in my testing, but all my clients have a default search domain assigned via dhcp so I doubt they're ever querying for the naked hostname.

Other than that, all good!  Note: didn't test the IPv6 part of it as I don't use IPv6.

Really wasn't expecting a patch so quickly. :)  Was actually expecting to have to dig in there and write my own so this is much appreciated.

**Comment by fichtner** [comment]
Maybe they are returned in batch, does not matter I think. We'll give this patch a bit of testing to be sure. Tested IPv6 from here, seemed ok. :)

Sorry for taking a bit of fun out of this. If you want to work on issues let me know, so we do more review / discussion instead of patching.


Cheers,
Franco

**Comment by fichtner** [comment]
@Slugger looks good from here still, did you encounter any issues? We're pondering inclusion in 17.7.x or if waiting for 18.1-RC1 is better. What do you think?

**Comment by Slugger** [comment]
I've had no issues with it.

**Comment by fichtner** [comment]
@Slugger thanks, will see about backporting :)

**Comment by fichtner** [comment]
Landing in 17.7.11 this week.
