### ISSUE TITLE
IPSec Support for Elliptical Curve DH Groups

### ISSUE THREAD

**Issue by bigops** [opnsense/core#1942]
While configuring IPSec VPN the EC DH Groups (19,20,21) are missing from the options.  StrongSWAN has been supporting these for some time now.  Since Groups 1, 2 & 5 are now considered as insecure and the ECC groups along with Group 24 (Already supported) are recommended to be used in VPNs, raising this ticket to get these enabled.  As per Franco in the  forums this should only needs a configuration change. 

https://supportforums.cisco.com/t5/security-documents/diffie-hellman-groups/ta-p/3147010

**Comment by AdSchellevis** [comment]
this https://github.com/opnsense/core/commit/581b8b17bcd26ee3d97774efb6c8e65b6ee2ed85 should do the trick, changed the default for new entries to 24 in the process and there seemed to be some missing implementation for some of the types.
