### ISSUE TITLE
Firewall: Remove rule separation by interface

### ISSUE THREAD

**Issue by StrikerTwo** [opnsense/core#1943]
As suggested in #1928 it might be worth reworking the firewall rule layout. The separation of rules per interface makes it hard to see all rules belonging to a certain flow at one glance. 
Tab- or menu-based navigation also has limits for installations with lots of interfaces.

Sophos UTM for example just has a big list of rules that can be grouped by using rule categories and hiding auto-created rules (NAT, bogons etc.):
![image](https://user-images.githubusercontent.com/6770084/33009281-a84818be-cdd6-11e7-981d-84c1c5d30c07.png)

Floating rules need special consideration sorting-wise so the display order corresponds with the actual rule execution order.

**Comment by fichtner** [comment]
We have been discussing a bit today, but want to let the tab removal sink in the development version for 18.1 to see what is the best way forward. 😊

**Comment by mimugmail** [comment]
Imho, best way is adding auto rules for every service step by step without a hurry, then the change will be quite silent, no matter if it's 18.7 or 19.1 :)

**Comment by AdSchellevis** [comment]
I don't think we should automagically add a lot of firewall rules, they tend to let to confusion as well with people not expecting ports to be open on certain interfaces. Better to make things explicit imho.

**Comment by StrikerTwo** [comment]
This issue wasn't meant to be about auto-created rules, just about the rule presentation.

I don't even want automatic rules for every service. I have services running on the OPNsense box that are only to be used internally, or only from specific IPs.
For the services that should be available on WAN I just have an alias list of the relevant ports and one single rule to grant access to them. IMHO somebody running a firewall product should know at least that much without relying on automatisms.

**Comment by fichtner** [comment]
We'll move this to 18.7. Too much other rough edges to fix up for 18.1 at the moment.

**Comment by AdSchellevis** [comment]
This has been open for quite some time now. I'm going to close it as at the moment as i don't expect this will happen any time soon.

We do have quite some changes stashed for 19.7 to increase readability and traceability, but one large list of all rules isn't one of them and probably will only make sense in combination with some sort of filter option as well.
