### ISSUE TITLE
Access point still working at 2.4GHz when Standard = 802.11na

### ISSUE THREAD

**Issue by paride** [opnsense/core#1944]
I set up an access point and I want it to work in the 5GHz band, so I configured it to use the 802.11na standard from the web interface. Even when configured like this, it auto-selects a channel in the 2.4GHz band. The `hw_mode` variable is not set in the `hostap_*.conf` configuration files, so this may be what is missing. (The hardware I'm using is 5GHz capable.)

(Edit) It should probably not be possible to select a 2.4GHz channel when the 802.11na standard is selected, and a 5GHz channel when the 802.11na standard is selected.

**Comment by AdSchellevis** [comment]
timeout (https://github.com/opnsense/core/commit/7338549ba5f295f5420e45ba74112af10d20c713)
