### ISSUE TITLE
DNS:implement remote DNS-blacklists (like pi-hole)

### ISSUE THREAD

**Issue by wytchmaster** [opnsense/core#1945]
It would be a great feature, if one can use remote DNS-blacklists in unbound and/or dnsmasq. Maybe it is possible to implement something like pi-hole https://pi-hole.net/). This makes a lot of sense, when blacklisting a lot of domains, especially when in a corporate environment.

**Comment by fabianfrz** [comment]
this might be a duplicate of opnsense/plugins#229

**Comment by jumbi77** [comment]
+1
Is that on the roadmap for 18.7 or planned for later releases?

**Comment by AdSchellevis** [comment]
tracked in https://github.com/opnsense/plugins/issues/229
