### ISSUE TITLE
LAGG in "loadbalance" mode not available as parent for VLAN interface

### ISSUE THREAD

**Issue by fraenki** [opnsense/core#1946]
I've noticed that the "capabilities" are quite different for my LAGG interface, depending if it's configured for "loadbalance" or "failover" mode.

In "loadbalance" mode, the `capabilities` line is quite sparse: 

```
 lagg0: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500
 	options=c400b8<VLAN_MTU,VLAN_HWTAGGING,JUMBO_MTU,VLAN_HWCSUM,VLAN_HWTSO,TXCSUM_IPV6>
-	capabilities=10000<VLAN_HWFILTER>
+	capabilities=f507bb<RXCSUM,TXCSUM,VLAN_MTU,VLAN_HWTAGGING,JUMBO_MTU,VLAN_HWCSUM,TSO4,TSO6,LRO,VLAN_HWFILTER,VLAN_HWTSO,NETMAP,RXCSUM_IPV6,TXCSUM_IPV6>
 	ether b4:96:91:07:b4:a8
-	inet6 fe80::d294:66ff:fe0a:d141%lagg0 prefixlen 64 scopeid 0xb 
+	inet6 fe80::b696:91ff:fe07:b4a8%lagg0 prefixlen 64 scopeid 0xb 
 	nd6 options=23<PERFORMNUD,ACCEPT_RTADV,AUTO_LINKLOCAL>
 	media: Ethernet autoselect
-	status: no carrier
+	status: active
 	supported media:
 		media autoselect
 	groups: lagg 
-	laggproto loadbalance lagghash l2,l3,l4
-	laggport: ix0 flags=0<>
+	laggproto failover lagghash l2,l3,l4
+	laggport: ix0 flags=5<MASTER,ACTIVE>
 	laggport: ix1 flags=0<>
```

As you can see, `capabilities=10000<VLAN_HWFILTER>` is all I get in "loadbalance" mode.
This leads to the situation that this interface fails the `is_jumbo_capable()` check in `interfaces_vlan_edit.php` and thus is not available as a parent interface for VLANs.

It smells like a driver issue, but it might be interesting to see if it's the same result on other hardware if LAGG is set to "loadbalance" mode. If that would be the case, maybe the logic needs to change so that such interfaces could be used as parent for VLANs.

This was tested on an Intel X540 card:
```
ix0: <Intel(R) PRO/10GbE PCI-Express Network Driver, Version - 3.1.13-k>
```

**Comment by fraenki** [comment]
Nope, not a driver issue. I was able to reproduce this on a test VM:

```
lagg0: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500
        options=6c00b8<VLAN_MTU,VLAN_HWTAGGING,JUMBO_MTU,VLAN_HWCSUM,VLAN_HWTSO,LINKSTATE,RXCSUM_IPV6,TXCSUM_IPV6>
        capabilities=7d07bb<RXCSUM,TXCSUM,VLAN_MTU,VLAN_HWTAGGING,JUMBO_MTU,VLAN_HWCSUM,TSO4,TSO6,LRO,VLAN_HWFILTER,VLAN_HWTSO,LINKSTATE,NETMAP,RXCSUM_IPV6,TXCSUM_IPV6>
        laggproto failover lagghash l2,l3,l4

lagg1: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500
        options=6c00b8<VLAN_MTU,VLAN_HWTAGGING,JUMBO_MTU,VLAN_HWCSUM,VLAN_HWTSO,LINKSTATE,RXCSUM_IPV6,TXCSUM_IPV6>
        capabilities=10000<VLAN_HWFILTER>
        laggproto loadbalance lagghash l2,l3,l4
```

Looks like it's an old issue that should already be fixed in 11-STABLE?
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=179733

**Comment by fichtner** [comment]
src.git/sys/net/if_lagg.c *is* the LAGG driver ;)

Have you tried against 18.1-BETA kernel?

**Comment by fraenki** [comment]
> Have you tried against 18.1-BETA kernel?

Good idea. I've upgraded my test VM and now the issue is solved.
Looks like FreeBSD 11.1 fixed this issue. Any chance to get the fix backported to 17.7, or would this be too much work?

**Comment by fichtner** [comment]
There seem to be multiple fixes on top of the lagg driver that loosely build on top of each other, I don't think this is a one-off fix so I'd rather not take the risk.

But OTOH, lagg is a module, you could use the /boot/kernel/if_lagg.ko from 11.1 with 11.0 to minimise impact...

**Comment by fraenki** [comment]
Thanks for considering it. I'll stick with "failover" mode on 17.7 and will switch to "loadbalance" mode on 18.1.
