### ISSUE TITLE
Feature Request: Scan for wireless networks

### ISSUE THREAD

**Issue by lattera** [opnsense/core#1947]
If I want to have OPNsense connect to an existing wireless AP, I may need it to scan for APs, first.

**Comment by fichtner** [comment]
Interfaces -> Wireless -> Status

The only trouble is that it requires you to assign an interface already.

**Comment by lattera** [comment]
Ah, nice! I'll close this ticket, then. Sorry for the noise.

**Comment by fichtner** [comment]
Not a problem :)
