### ISSUE TITLE
mvc: generate page titles from menu breadcrumbs like legacy code

### ISSUE THREAD

**Issue by fichtner** [opnsense/core#1948]
Currently, all titles in the index controllers are fixed. The legacy pages, however, more gracefully generate their titles from the menu structure like breadcrumbs. This gives better context and makes changes possible from the Menu.xml only without having to touch the view titles at all.

https://github.com/opnsense/core/blob/aaf2178f5a4070b9f2fe0fc673f4d0c14510be95/src/opnsense/mvc/app/controllers/OPNsense/Proxy/IndexController.php#L45

As a reference the legacy code:

https://github.com/opnsense/core/blob/aaf2178f5a4070b9f2fe0fc673f4d0c14510be95/src/www/head.inc#L20

@AdSchellevis as you have a better grasp of this index controller magic, how would an effective implementation look like without having to duplicate menu reading?

**Comment by fichtner** [comment]
@AdSchellevis I probably found an answer, no need to help out at this point. sorry for the noise!

**Comment by AdSchellevis** [comment]
@fichtner nice catch!
