### ISSUE TITLE
system: selective restore in OPNsense vendor space

### ISSUE THREAD

**Issue by fichtner** [opnsense/core#1951]
via: https://forum.opnsense.org/index.php?topic=6441.0

**Comment by AdSchellevis** [comment]
@fichtner I don't know if that's a good idea, to be honest, I think we could even better drop support for partial restores. There's no way to validate correctness and with relations between objects changes are even bigger for issues when selectively restoring new model data.

**Comment by fabianfrz** [comment]
@AdSchellevis there are also cross references in the config like:
haproxy <=> acme
redis <=> rspamd

**Comment by AdSchellevis** [comment]
I totally understand, which kind of is the reason why I don't think we should extend partial backups/restores.... to really support this would add quite some complexity, which isn't really worth the effort. (and doing it partially will always lead to more support cases, which are hard to track)

**Comment by fichtner** [comment]
ok, less work then... :)
