### ISSUE TITLE
Feature Requests :  Readable usernames in Voucher Server or access code only

### ISSUE THREAD

**Issue by bigops** [opnsense/core#1953]
Presently the user name and password in the voucher server consists of a series of standard and special characters.  This makes it difficult to convey.  My suggestion is to either have the usernames in a standard format like User3434 or even doing away with the username in the Voucher server and have only the access code

**Comment by AdSchellevis** [comment]
timeout (https://github.com/opnsense/core/commit/7338549ba5f295f5420e45ba74112af10d20c713)
