### ISSUE TITLE
Reboot: Pf / Packet Filter blocks traffic after reboot.

### ISSUE THREAD

**Issue by PitchBendStretch** [opnsense/core#1955]
**Hi OPNsense Admins, :)**

i have another problem, which i tried to ignore for a few months, but it's getting outer hand now, 
since OPNsense is not able to "self-recover" without an Admin to login to the Firewall. 

After every reboot, the Packet Filter is not working correctly anymore until i restart the "Pf service". 
What i mean by that is that the Packet Filter starts to block ICMP / TCP:S Traffic for Port 80 and 443 as soon as the Firewall rebooted successfully.
The Firewall Log is filled with these blocked ports.
I use policy based routing because i use VPN Gateways to route my traffic to !RFC1918
As soon as i manually restart the packet filter service everything works as intended again.

As far as i know the problem did start to appear with Version 17.7.5 but i am not 100% sure about that, but pretty certain. To that time i additionally started to configure my VPN gateways - just saying.
___________________________

**My idea:**

I have a VPN Failover Gateway configured with 3 VPN Gateways, which need some time to get an IP and establish a correct connection. Could the problem be caused by the time it takes to fully activate all VPN gateways, so that the packet filter fails to load the rules because the Policy Based routes are using a VPN Gateway which is not fully active to that specific moment? Just to be clear, even after all VPNs are online and working, the Packet Filter remains blocking legit traffic, which i allowed through Firewall rules (no floating Rules used) 

**// Just brainstorming here** 

I remember back then (Version 15.1+) there was the possibility to delay the reboot so that it has more time to load services correctly. Is this setting still available somewhere?
___________________________

**My current Version:**

> Versions | OPNsense 17.7.8-amd64
FreeBSD 11.0-RELEASE-p15
OpenSSL 1.0.2m 2 Nov 2017
___________________________

**System Log after reboot:**

> Nov 23 20:01:39 | kernel:
Nov 23 20:01:39 | kernel:
Nov 23 20:01:39 | kernel:
Nov 23 20:01:37 | kernel: OK
Nov 23 20:01:37 | configd.py: [405c1bc5-ca6e-4044-b1f5-fc7ef8c1fdd4] restarting cron
Nov 23 20:01:35 | sshlockout[43123]: sshlockout/webConfigurator v3.0 starting up
Nov 23 20:01:35 | configd.py: [a22e707e-522a-45ff-b4d4-f51858f5a396] request pfctl byte/packet counters
Nov 23 20:01:34 | kernel: done.
Nov 23 20:01:32 | root: /etc/rc.d/hostid: WARNING: hostid: unable to figure out a UUID from DMI data, generating a new one
Nov 23 20:01:32 | configd.py: generate template container OPNsense/Syslog
Nov 23 20:01:31 | kernel: done.
___________________________

Best regards,
Oxy / PitchBendStretch

**Comment by PitchBendStretch** [comment]
Hi Admins,

It's getting worse with the packet filter error. From time to time the OPNsense restarts itself, when every failover Gateway is gone. (Atleast that i my guess). Whenever this happens the Packet Filter blocks EVERY outgoing traffic, no matter if it's HTTP/HTTPs, ICMP or any mail protocol.

I once again checked the System Log and searched for "**error**" and found this at the time the Firewall restarted:
> Nov 29 19:43:23 | kernel: WARNING: /mnt: reload pending error: blocks 8 files 0
Nov 29 19:43:23 | kernel: WARNING: /mnt: reload pending error: blocks 8 files 0
Nov 29 19:43:23 | kernel: WARNING: /mnt: mount pending error: blocks 8 files 0
Nov 29 19:43:23 | kernel: pcib0: _OSC returned error 0x10
Nov 29 19:43:23 | kernel: module_register_init: MOD_LOAD (vesa, 0xffffffff81149b90, 0) error 19

When i search for "**warning**" i additionally get these errors:
> Nov 29 19:43:23 | kernel: WARNING: /mnt was not properly dismounted
Nov 29 19:43:23 | kernel: WARNING: L1 data cache covers less APIC IDs than a core

This really doesn't look good to me...
Any idea by any chance?

Best regards,
Oxy / PitchBendStretch

**Comment by PitchBendStretch** [comment]
Hi it's me again.
I found the "delay Plugin", which is the following:

os-boot-delay (installed) | 1.0 | 32.0B | Apply a persistent 10 second boot delay
-- | -- | -- | --

After i did that **i can now reboot the Firewall without any packet filter issues.** The problem i always had with my NTP service/daemon not being able to load properly after a reboot is now gone aswell.

I have no idea why this is happening but the issue seems to be the following:

> The system is rebooting to fast ??

Really odd behaviour but it is now working again somehow. I read in the forum that i am not the only one. Franco wrote the following in one of the threads:
> Also der Fehler kann auftreten wenn das Device sobald der Kernel das Dateisystem mounten möchte noch nicht bereit ist. Das Dateisystem ist in diesem Fall in Ordnung, weil ja der Bootloader und der Kernel schon durch sind.
> Gerade auf dem APU gibt es manchmal dieses Problem, manchmal nicht. "os-boot-delay" fügt einen 10 Sekunden-Timeout als Workaround (für das ungeduldige Betriebssystem) hinzu.

**Source:** https://forum.opnsense.org/index.php?topic=3989.0

I wish you guys all the luck to fix this issue! :)

Best regards,
Oxy / PitchBendStretch

**Comment by fichtner** [comment]
Hi Oxy,

Sorry I have been traveling abroad for most of last week. Interesting, can you dump your ifconfig device info real quick? Questions follow for specific drivers...

    # ifconfig -l


Cheers,
Franco

**Comment by PitchBendStretch** [comment]
Hi Franco :)
Sure thing. Here we go:

**root@OPNsense:/ # ifconfig -l**
> igb0 igb1 igb2 igb3 igb4 igb5 enc0 lo0 pflog0 pfsync0 ovpnc1 ovpnc2 ovpnc3 ovpnc4 ovpnc5 ovpnc6 lagg0 lagg0_vlan5 lagg0_vlan10 lagg0_vlan20 lagg0_vlan30 lagg0_vlan40 lagg0_vlan60

ovpnc1 ovpnc2 ovpnc3 are not in use by now. ovpnc4 ovpnc5 ovpnc6 are OpenVPN Client interfaces.
The rest are VLANs (more will follow next year), which are "trunked (HP terminology)" using 4 INTEL Interfaces.
1 Interface is for WAN and 1 is for DMZ/WLAN purposes. 

This is my Hardware: 
http://www.lannerinc.com/products/x86-network-appliances/x86-desktop-appliances/fw-7525
Every interface is an INTEL interface. I did not mess with the BIOS, so i don't think i misconfigured something of the hardware specific settings. :P

**Comment by fichtner** [comment]
Hi Oxy,

This looks perfectly innocent, no USB devices that would make the boot unstable, which is where os-boot-delay came in... However, we are currently trying to find out if igb is misbehaving and I would think that if your igb is doing some up/down during boot that would cause this, but still not tightly tied to 17.7.5 or any 17.7 for that matter. What the os-boot-delay may do is give your adapters some time to go up/down before they stabilise and then the system boots ok.

Long thread with some workarounds to try:

https://forum.opnsense.org/index.php?topic=5511.0

Werner noticed that FreeBSD 11.1 works mostly better, it may be worth a try as well:

https://forum.opnsense.org/index.php?topic=6257.0


Cheers,
Franco

**Comment by PitchBendStretch** [comment]
Hi Franco,

Thanks but december is frozen zone for me. I can't risk loosing a working system even if it's just for the weekends. The boot delay plugin kinda "fixed" the issue enough for me so that it will work until january.
I will then further try out to disable the EEE settings and update to 18.1, if it's not released until then anyway.

Thank you very much for your help Franco. You can close the ticket, as i found a workaround for now. :)

**Comment by fichtner** [comment]
@PitchBendStretch ok, I'm keeping my eyes open for this nevertheless... :)
