### ISSUE TITLE
Feature Request: Use Aliases within Aliases

### ISSUE THREAD

**Issue by DukeSniper** [opnsense/core#1957]
To further simplify ruleset and alias definitions, it would be useful to be able to use Aliases within an Alias definition.

Consider the following simplified example. There's 2 Servers (Host_A and Host_B), that offer 3 Services. Host A offers Service_A, Host B offers Service_B, and they both offer Service_C. Right now, I would need to define 3 Aliases:

Host_A -> 10.10.10.10
Host_B -> 10.10.10.20
Hosts_AB -> 10.10.10.10, 10.10.10.20

Also, there's 3 rules for the  services

Rule Service_A uses the alias Host_A
Rule Service_B uses the alias Host_B
Rule Service_C uses the alias Hosts_AB

So far, so good. But what happens, if Host_A's IP address changes? With the current design, I'd have to check every alias and see if it contains Host_A's old IP address and change that, that would be 2 definitions to be changed in this overly simplified example (probably a few more in a production environment).

If I were able to use aliases within an alias definition, it would require only one change - the definition of Host_A. The Group definition would automatically be right again because it references the (now changed) definition of Host_A:

h_Host_A -> 10.10.10.10
h_Host_B -> 10.10.10.20
g_Group_AB -> h_Host_A, h_Host_B

**Comment by fichtner** [comment]
You can do this already ;)

**Comment by DukeSniper** [comment]
I'm gonna have to try. The current UI help texts kinda suggest otherwise.

**Comment by fichtner** [comment]
If you let us know which, we can change it accordingly. The alias names can be used as inputs, there should even be type-ahead support.

**Comment by DukeSniper** [comment]
Tested, actually does work with hosts, networks, and ports (which is kinda awesome!)

Basically, all the texts in the screenshot fail to mention that aliases can be used to. The red one is the one I was focussing on, since I was trying to define host groups. Oh, and there's a typo as well: The word "mehrere" (green arrow, right before the "IP-Adressen zurückgegeben" is missing an R
![image](https://user-images.githubusercontent.com/6539018/33209833-0cb1f4fc-d118-11e7-9a90-418bbbd24277.png)

**Comment by fichtner** [comment]
Thanks, I'll take care of it unless you want to propose a PR? :)

**Comment by DukeSniper** [comment]
You go ahead, I currently have neither the time nor the motivation to read up on git ;)

**Comment by fichtner** [comment]
Typo in German fixed, will add a note for alias nesting in the GUI and close.
