### ISSUE TITLE
select different wan ip ?

### ISSUE THREAD

**Issue by akbulut** [opnsense/core#1958]
Hello,
can i do that ?
for exp;

local ip 192.168.1.10 > 2a02:16b0:2000:2b::10
local ip 192.168.1.11 > 2a02:16b0:2000:2b::11

can i select wan ip ?

**Comment by StrikerTwo** [comment]
Sorry, what?

**Comment by akbulut** [comment]
I want to redirect or forward ip4 ip to ipv6 
if client call 192.168.1.10:3129 forward 2a02:16b0:2000:2b::10 
if client call 192.168.1.11:3129 forward 2a02:16b0:2000:2b::11

**Comment by StrikerTwo** [comment]
If we are talking about TCP then you could try setting up HAProxy in TCP mode for that, i.e. use 192.168.1.10 as the frontend address and 2a02:16b0:2000:2b::10 as the server address.

**Comment by akbulut** [comment]
yes we are talking about tcp but i want to choose out ip one by one.
i try wan add ipv6 to wan ip. then client all any ipv4 ip , my proxy server only 1 wan ip using for out ip. 
i have to select ipv6 ip for outing.

**Comment by StrikerTwo** [comment]
So you want an outgoing 1:1 NAT from a specific IPv4 to a specific IPv6 address? I don't think that will work.
Why can't your clients have IPv6 addresses?

**Comment by AdSchellevis** [comment]
timeout (https://github.com/opnsense/core/commit/7338549ba5f295f5420e45ba74112af10d20c713)
