### ISSUE TITLE
No autocompletion for aliases in Firewall Rules

### ISSUE THREAD

**Issue by fraenki** [opnsense/core#196]
Server: OPNsense 15.1.11.1-amd64
Client: Firefox 38.0

Steps to reproduce:
- Firewall -> Rules -> Add (or Edit)
- Source -> Type: Single Host or Alias
- enter an existing alias

Expected result:
- while typing the first letter(s) of the alias, autocompletion should be activated and complete the alias name (similar to pfSense)

Actual result:
- no autocompletion

As a sidenote, alias autocompletion is working for NAT Port Forward rules. So I guess this is a bug.

**Comment by AdSchellevis** [comment]
Yes it looks like a bug, there was a javascript error on the page preventing the auto complete code to load. 
I've not tested all different alias types, but commit https://github.com/opnsense/core/commit/38a6a82560ed26fe9f0ea85d5cf10e377e488204 seems to solve it.

**Comment by fraenki** [comment]
Great! Tested and worksforme. :+1:

**Comment by AdSchellevis** [comment]
Thanks for testing!
