### ISSUE TITLE
Feature Request: More options for the Traffic Graph

### ISSUE THREAD

**Issue by Alpha-Bravo** [opnsense/core#1960]
The traffic graph (dashboard and dedicated page) is a quite important element to most users of a router/firewall. The following points could be improved:

- The time line (scale) is missing (x-axis) - one has to hover the (moving) data points in order to check the point in time of a throughput measurement. A time scale with some timestamps should be present all the time.

- The curve permanently compresses the range of the x-axis where it should only be shifted linear over time. Shifting, like a sliding window, allows easier interpretation of the current and past traffic throughput.

- The frequency of new data points is a bit low. A new point every one or two seconds would allow finer resolution.

- The curve itself looks quite edged (linear interpolation of data points). There should be an option to smooth the edges a tiny bit.

I know: These requirements are met by the current traffic graph of the sister project... I switched a few days ago to OPNsense because of political reasons... OPN is great an clean. But the one thing I am really missing is the kind of traffic graph. Would be very nice to add some options to the traffic graph (especially dashboard widget).

**Comment by fichtner** [comment]
Hi @Alpha-Bravo,

Thanks for this. I am not sure we can fix them all, but these are certainly things to work on as time permits. Marking these as "help wanted", because the wish list for 18.1 is already pretty full.


Cheers,
Franco

**Comment by JesseWV** [comment]
I agree. Even in 18.7.1 it looks horrible. To me, the features mentioned by the OP are a must. It would also be nice to remove/add interfaces from each graph. It's a bit redundant to see WAN/IN and LAN/OUT since they are virtually the same. Honestly, and I hate to say this, it needs to be at least as good as the traffic graph in PFSense.

**Comment by fichtner** [comment]
Happy to see this progress indeed.

**Comment by AdSchellevis** [comment]
timeout
