### ISSUE TITLE
Aliases in Outbound NAT Rules broken

### ISSUE THREAD

**Issue by fraenki** [opnsense/core#197]
Server: OPNsense 15.1.11.1-amd64
Client: Firefox 38.0

Steps to reproduce:
- Firewall -> NAT -> Outbound -> Add (or Edit)
- Destination -> Type: Network
- enter an existing alias
- Save

Expected result:
- the alias should be viewed in column "Destination"

Actual result:
- the column "Destination" reads: `Array<name of alias>` (see screenshot)

![alias](https://cloud.githubusercontent.com/assets/909706/7799551/bd7dda4e-0307-11e5-9c55-11149ce9944c.png)

As a sidenote, alias autocompletion is *not* working for Outbound NAT Rules, while it *actually is* working in Port Forward NAT Rules.

**Comment by AdSchellevis** [comment]
Thanks for the detailed description. 
Our interface does not include a tooltip for the aliases, but had some left over code which results in the "Array" tag. 
Commit  https://github.com/opnsense/core/commit/399e4f84d836ea337ad4e2ea74d7ad3af74ab157 removes this glitch.

The Alias auto completion code was not in this page as it seems, maybe we should add another issue for this in GitHub. If possible I would like to prevent adding another copy of the same code which we will have to replace sometime later.
