### ISSUE TITLE
Configurable listen interface for web GUI

### ISSUE THREAD

**Issue by tokred** [opnsense/core#1970]
I would like to suggest the feature to set the web server's listen interface. 

This would allow setups where e.g. OpenVPN listens on WAN 443/tcp (to cope with restrictive firewalls) while web GUI still runs on LAN 443/tcp. 

What do you think? 

Best regards

**Comment by fichtner** [comment]
See https://github.com/opnsense/core/issues/1347 — will be in 18.1 :)
