### ISSUE TITLE
Firewall / aliases, refactor and detach alias logic

### ISSUE THREAD

**Issue by AdSchellevis** [opnsense/core#1971]
As part of the cleanup and restructure operation we're going to refactor and detach the alias logic, the start for this was https://github.com/opnsense/core/commit/70b74c29dc5246ad14f836987b706a2886a2f149 . This issue is a placeholder to hook related work for easier tracking.

**Comment by AdSchellevis** [comment]
https://github.com/opnsense/core/commit/e51197e54b85da22602a35aa5cf9098b8ad8cbd2

**Comment by fichtner** [comment]
Reminder for myself: ping https://forum.opnsense.org/index.php?topic=6506.0 when this is ready for wider testing

**Comment by SReign** [comment]
Is there a way to disable Aliases from automatically adding descriptions to individual table records or turning off individual record descriptions completely?

**Comment by fichtner** [comment]
@mimugmail reported this template exception: OPNsense/Filter OPNsense/Filter/filter_tables.conf 'None' has no attribute 'type'

**Comment by AdSchellevis** [comment]
@fichtner empty alias section, will fix this later on.

**Comment by fichtner** [comment]
@AdSchellevis no worries, just wanted to record it for later :)

**Comment by AdSchellevis** [comment]
@fichtner fixed in https://github.com/opnsense/core/commit/6ab11f0636e853bdd39970ac5c221c6e9085cc4f

**Comment by mimugmail** [comment]
Is this already in RC2? Im getting:

`Jan 16 19:55:22 OPNsense configd.py: error generating template OPNsense/Filter : Traceback (most recent call last):   File "/usr/local/opnsense/service/modules/template.py", line 313, in generate     for filename in self._generate(template_name, create_directory):   File "/usr/local/opnsense/service/modules/template.py", line 248, in _generate     raise Exception("%s %s %s" % (module_name, template_filename, render_exception)) Exception: OPNsense/Filter OPNsense/Filter/filter_tables.conf 'aliases' is undefined
`

But not really sure if there's a relation to this issue ...

**Comment by fichtner** [comment]
Was fixed incorrectly, see bba40c9789ba7f3 which will be in 18.1.
