### ISSUE TITLE
In current development build, time zone setting always shows UTC

### ISSUE THREAD

**Issue by JeffMelton** [opnsense/core#1973]
Current OPNSense version: OPNsense 18.1.a_364-amd64 (LibreSSL)

How to replicate: Set time zone in System->Settings->General to local (America/Chicago, in my case), click Save, watch it revert to ETC/UTC. System dashboard shows expected localtime, however, so this appears to be a UI bug.

[I'm tracking the dev build because I'm slowly rebuilding my APU after the last major pfSense upgrade left me in the lurch and v18+ has the AHCI hints I need built in.]

**Comment by AdSchellevis** [comment]
oops, I was a bit too quick here. one moment

**Comment by fichtner** [comment]
whoopsie, I messed up a refactor. thanks for running -devel!! ❤️

**Comment by JeffMelton** [comment]
@fichtner It does seem to have been the solution to the problem I was seeing, yes.

**Comment by fichtner** [comment]
@JeffMelton thanks, superb!
