### ISSUE TITLE
Feature Request: User Definded IDS Alerts

### ISSUE THREAD

**Issue by tpcr** [opnsense/core#1974]
It would be nice to have the ability to suppress alerts for the GeoIP IDS alerts. My alerts fill up quickly with GeoIP alerts and I would like to suppress them or any other User Defined rules in the IDS category

**Comment by AdSchellevis** [comment]
you better switch to using geoip from aliases in your firewall, I don't think there's an option not to log the alerts..

**Comment by tpcr** [comment]
I know about using GeoIP in Alerts, and I may go back to that, but I wanted to block these countries before they gained firewall access. Isn't that a better approach?

**Comment by AdSchellevis** [comment]
I would stick to the firewall, the alias option was added later and likely better fits your needs.
