### ISSUE TITLE
intrusion detection: enable/disable toggle in alert info

### ISSUE THREAD

**Issue by tpcr** [opnsense/core#1976]
When info is selected and the Rule details are displayed, this should also show the actual rule and allow a 'pass' Action in the drop down list. This is also useful with any custom rules that have been added. Some of my custom rules are needed to allow an IP to pass regardless of content and to avoid unnecessary IPS overhead on trusted servers that use a lot of bandwidth.

**Comment by fichtner** [comment]
Which version are you using?

**Comment by tpcr** [comment]
17.7.8

**Comment by fichtner** [comment]
ok, do you mean a "conditional pass" ?

**Comment by tpcr** [comment]
The only Action options in the Rule Details is alert or drop. I think pass should also be there. Some of my custom rules are pass rules and the Rule Details is useless for these rules because it doesn't have pass as an option.

**Comment by fichtner** [comment]
Ah, now I understand, enable/disable, thanks

**Comment by tpcr** [comment]
Thanks

**Comment by fichtner** [comment]
@AdSchellevis since a few other improvements went into IDS could this be implemented easily as well?

**Comment by AdSchellevis** [comment]
https://github.com/opnsense/core/commit/4e1112edc9207fcbc307cd55a02372222e3b7444 fixes an issue there, related to the action not always being visible. 
![image](https://user-images.githubusercontent.com/9783985/59446780-6d84a880-8e02-11e9-8785-ad0ec3f46ec2.png)

I kind of expect the same already works with custom rules, when properly installed.

**Comment by fichtner** [comment]
@AdSchellevis keep or close?

**Comment by AdSchellevis** [comment]
@fichtner as far as I know it's fixed.
