### ISSUE TITLE
ipsec crash report when using ping host in P2

### ISSUE THREAD

**Issue by mimugmail** [opnsense/core#1977]
I sent you a crash report after update to 17.7.9.
Seems it's related when a P2 has an automatically ping host entry.

If I remove it and restart the crash report is gone.

**Comment by fichtner** [comment]
I guess that's a bumped log message by PHP 7.1. I'll try to find the report.

**Comment by fichtner** [comment]
```
PHP Fatal error:  Uncaught Error: [] operator not supported for strings in /usr/local/etc/inc/plugins.inc.d/ipsec.inc:884
Stack trace:
#0 /usr/local/etc/rc.bootup(126): ipsec_configure_do(true)
#1 {main}
  thrown in /usr/local/etc/inc/plugins.inc.d/ipsec.inc on line 884
```

**Comment by mimugmail** [comment]
exactly ... sadly this happens only on the machine where I had the going live today :(

**Comment by fichtner** [comment]
# opnsense-patch 0c6d34e

We shall hotfix this tomorrow. Please confirm, make sure to check the contents of /var/db/ipsecpinghosts shows one entry per line (or just one).

**Comment by mimugmail** [comment]
I can't test right now, have my engineers doing a migration from some virtual machines now. 
I'll try to reproduce on some test systems ..

**Comment by mimugmail** [comment]
ok, it's reproduceable:

![image](https://user-images.githubusercontent.com/20438689/33733917-8db00ad0-db8b-11e7-9d05-e4600a8d19ef.png)

**Comment by mimugmail** [comment]
The patch fixed it .. 

```
root@OPNsense:~ # less /var/db/ipsecpinghosts
10.10.10.1|10.26.1.10|3|||||inet|
10.10.10.1|10.26.2.10|3|||||inet|

```

**Comment by fichtner** [comment]
thanks... it's a latent problem that PHP put off for a long time but changed it finally for 7.0 -> 7.1 --- I'll issue a hotfix tomorrow morning as promised. :)
