### ISSUE TITLE
[bug]: multiple IDS blocks on the same packets

### ISSUE THREAD

**Issue by tpcr** [opnsense/core#1978]
Using IDS with IPS, whenever a User defined GeoIP block triggers and another rule matches, they are both displayed in alerts. Shouldn't the first trigger end the rule search? Seems to happen only with the GeoIP rule and any other match. looks like a GeoIP rule match does not conclude the search
See 2 examples in these pics

![ips1](https://user-images.githubusercontent.com/22845650/33735870-daa4463c-db4d-11e7-85b6-4ed7ce7dfcb3.jpg)
![ips2](https://user-images.githubusercontent.com/22845650/33735871-dac1bb54-db4d-11e7-805d-27e8ae02abed.jpg)

**Comment by tpcr** [comment]
Apparently this happens with all rules. I have multiple hits from different ET rules on the same packet.
Here is an example. I have seen this multiple times.
![ips3](https://user-images.githubusercontent.com/22845650/33742329-1e7214f4-db65-11e7-94b7-14f7840c56d2.jpg)

**Comment by AdSchellevis** [comment]
ok, no need to search for this then, looks like intended behaviour (I don't have a lot of overlapping rules, but if I duplicate a rule it functions the same). please check the suricata documentation for more information and backgrounds.

**Comment by tpcr** [comment]
Ok, I figured it was a Suricata thing. I would think it shouldn't work this way. Never seen it before when I was using Snort.

**Comment by tpcr** [comment]
This is from the Suricata manual. http://suricata.readthedocs.io/en/latest/configuration/suricata-yaml.html

Drop-
This only concerns the IPS/inline mode. If the program finds a signature that matches, containing drop, it stops immediately. The packet will not be sent any further. Drawback: The receiver does not receive a message of what is going on, resulting in a time-out (certainly with TCP). Suricata generates an alert for this packet.

This is not happening. I have submitted a bug report with Suricata.

**Comment by tpcr** [comment]
Seems the Suricata devs are scratching their heads on this one. So am I.
I am reopening this issue so I can maybe get some answers.

**Comment by AdSchellevis** [comment]
timeout (https://github.com/opnsense/core/commit/7338549ba5f295f5420e45ba74112af10d20c713)
