### ISSUE TITLE
[Bug]: Resetting all local log file clears all logging settings on the page

### ISSUE THREAD

**Issue by tpcr** [opnsense/core#1979]
Using 17.7.9
When resetting log files under System>Settings>Logging
All the settings on page also clear after hitting the Reset Log Files button, so if you hit save, you lose your settings. If you leave the page and come back without saving, the settings are still there.
Minor cosmetic bug.

**Comment by fichtner** [comment]
I was going for a redirect, but this looks good too :)

**Comment by tpcr** [comment]
Thanks
