### ISSUE TITLE
Enable Alias Autocompletion for Outbound NAT Rules

### ISSUE THREAD

**Issue by fraenki** [opnsense/core#198]
Follow-up to #197 to handle the second issue:
Alias Autocompletion is *not* working for Outbound NAT Rules, while it *actually is* working in Port Forward NAT Rules.

**Comment by fichtner** [comment]
@AdSchellevis is this already done? :)

**Comment by AdSchellevis** [comment]
@fichtner Alias handling is different in the new pages, also for the outbound NAT rule, I think we should close this. Functionally it's doing the right thing now.

**Comment by fichtner** [comment]
Great thanks. :)
