### ISSUE TITLE
ssh login key file being removed

### ISSUE THREAD

**Issue by backstube** [opnsense/core#1980]
Hi,
we used to use key auth to ssh into our OPNsense box for quite a while. Only recently we noticed that the file <code>/root/.ssh/authorized_keys</code>, which is holding said keys, is being removed automatically shortly after creation.

Why is that? And by which job/tool/whatever?

Thanks!

**Comment by AdSchellevis** [comment]
@backstube you need to add the keys in the usermanager, they will automatically be flushed to disk (overwriting the ones already there)

**Comment by backstube** [comment]
Ah, I see. We previously put them 'by hand' into that file, yes.

Alright. Thanks for your very speedy response. And of course for your excellent work!

**Comment by fichtner** [comment]
❤️
