### ISSUE TITLE
change gateway = no internet

### ISSUE THREAD

**Issue by Diegonarducci88** [opnsense/core#1989]
if in rule lan to ALL, if change default gatreway to unique gateway, is lost connection and dont wor

last version opnsense 17.7.9

**Comment by fichtner** [comment]
There is not much info go go on. What is your network setup, what are you trying to achieve?

**Comment by AdSchellevis** [comment]
timeout (https://github.com/opnsense/core/commit/7338549ba5f295f5420e45ba74112af10d20c713)
