### ISSUE TITLE
GUI Enhancement - reorder Interfaces Alphabetically and other stuff

### ISSUE THREAD

**Issue by reetp** [opnsense/core#199]
I notice that the system assigns the interface with LAN, WAN, OPT1 OPT2 etc.

So I wanted to rename the interfaces so I know what is what, but frustratingly they stay in the same position e.g.

WANBackup
LAN
WANMain
WANVoip

I'd prefer them as 

LAN
WANBackup
WANMain
WANVoip

(or at least ordered alphabetically so I can rename them and get them in the order I want)

I can see that the pages are then hardlinked e.g.

http://192.168.1.1/opt1.php

These should be variables or something else.

I also note that if you click 'Interfaces' you get this URL : 

http://192.168.1.1/interfaces_assign.php#Interfaces

That might be better to link to : 

http://192.168.1.1/interfaces_assign.php

Or alternatively when you click each of the main menu Links - e.g. System, Interfaces, etc perhaps it would be better going to a default page for each section - either a description page or the first tab ? Sometimes you feel you click expecting something to happen, and nothing does, beyond a menu expanding !

Sorry - sounds picky, but making the UI intuitive makes so much difference to the user experience IMHO :-) The system may work perfectly, but if you feel you are floundering around for things, it detracts from the quality underneath !

One last bit - It is easy to miss the fact that you might need updates after install. Perhaps once you have done with configuring et al you should be dumped straight in to the updates page with a 'checking for updates' as the system auto checks for the user ?

**Comment by fichtner** [comment]
We'll try a ordering by key for now, but this might clash with a description set. I don't really like using descriptions as descriptive names, but that's for another time.

For firmware updates: we don't want to enable auto-polling by default, so there has to be a manual effort involved. Some deployments also live in a Internet-less environment, where said prodding would cause more annoyance then do good. :)
