### ISSUE TITLE
Allow DHCPv6 with Prefix delegation 

### ISSUE THREAD

**Issue by poggenpower** [opnsense/core#1993]
If you have a internet uplink with prefix delegation, you typically want to assign these delegated ipv6 addresses to your clients in your network, but Opnsense doesn't support this, because almost all DHCPv6 functions are disabled. Especially Router Advertisements and DHCP Server. 

Feature Request:
Support DHCPv6 and RA, if the interface is a Track IPv6 Interface. 
subrequest: 
Instead of assigning an Interface ID by EUI-64 it would be great to make it configurable like "::1" as this interface is the default route in this network and need to be configured in some places.

**Comment by fichtner** [comment]
Hi @poggenpower,

Thanks for this ticket... let's break this down and work our way up.

> Instead of assigning an Interface ID by EUI-64 it would be great to make it configurable like "::1" as this interface is the default route in this network and need to be configured in some places.

Can you explain this a bit more, preferably in the respective config syntax so we can write and test precise changes.

I'm tagging this "future", I'm not sure we'll get all of this into 18.1 still.


Cheers,
Franco

**Comment by poggenpower** [comment]
Thanks Franco,

for your response. Here what I could think of how it should look like. 
![screen shot 2017-12-15 at 00 49 16](https://user-images.githubusercontent.com/6035034/34020007-de67c0c0-e131-11e7-8f2c-793378086015.png)

Here a mockup of how it could look like. 
In the additional field you can specify the Interface ID in typical colon separated format. How long this input could be depends on the length of the prefix delegated. This could be inherited the parent interface. The formula is: 128 - "DHCPv6 Prefix Delegation size" - "Site-Level Aggregation Length" = Interface ID Length. As the example in the mock up shows, if a shorter ID is given, than it should be the most right hand side part of the address. 

The configuration of the interface ID is not an requirement for the main request to have DHCP working on a tracked interface.

Bye 
  Thomas

**Comment by fichtner** [comment]
Hi Thomas,

Okay, so that is effectively setting the IPv6 address obtained for the tracking interface to a static value (inside the prefix)? Do you expect the compressed format to work here? Like 1::ff expanding to 1:0000:0000:00ff or would that be expanded and cut to 0000:0000:0000:00ff? Probably the latter, just double-checking. :)


Thanks,
Franco

**Comment by poggenpower** [comment]
Hi Franco,
it is up to you, if you want to support this and do the expansion in the code. Don't know the rest of the code, but as :: is only valid one time in a address, you could not assume that it could work here. In real life I think this is a very rare case where such a interface ID is given. If needed the user should type it full qualified, this should be OK  and keeps the code simpler.
Bye
  Thomas

**Comment by iamperson347** [comment]
Implemeting this would bring opnsense in line with pfsense with regards to some of the ipv6 functionality. (My LAN interface on pfsense as an example.)

![image](https://user-images.githubusercontent.com/1909402/42484470-28c24eec-83c1-11e8-90e6-a9e4fa2b023a.png)

And an example of the interface automatically grabbing an IP within the prefix.

![image](https://user-images.githubusercontent.com/1909402/42484564-881a976e-83c1-11e8-9146-da5db5f800fb.png)

Note: in pfsense, this still allows DHCPv6 to be used.

**Comment by fichtner** [comment]
@iamperson347 unsure what you are asking. The feature you show in the screenshot has been in OPNsense since the fork? And yes, in OPNsense 18.7 you will be able to use manual DHCPv6 / RA if you want.

**Comment by iamperson347** [comment]
Excellent. When I tried opnsense previously, I was not able to use DHCPv6
unless a static address was assigned to the interface.

**Comment by fichtner** [comment]
I don't know if we can accommodate for an ID to assign a real address. dhcp6c seems to assign it, more or less related to what it gets from radvd/dhcpv6. I am unable to find overrides in the deamons for proper configuration.

**Comment by poggenpower** [comment]
If I understand the comments correct, it is not possible to set the interface address to a specific address because of technical restrictions. Right?

**Comment by fichtner** [comment]
Yes, dhcp6c leaves no room for manual IDs/Suffixes that it assigns for the interfaces it handles. That could be mitigated by using ULAs via VIPs.
