### ISSUE TITLE
Captive Portal not redirecting

### ISSUE THREAD

**Issue by abplfab** [opnsense/core#1994]
Since 17.7.9 captive portal doesn't redirect to the portal anymore. Also there seems no server running on 8000-10000/tcp on LAN (did a portscan against the LAN IP).
Rules on LAN (where CP should run):
* Pass IPv4+6 TCP from LAN Net to LAN Address Ports 8000-10000
* Pass IPv4 * any to any
* Pass IPv6 * any to any
As soon as CP is enabled all traffic is blocked and no Portal comes up. Disabling CP traffic is ok.
Captive Portal Settings:
Interface: LAN
Auth using: Local Database
Enforce local group: "Captive Users" (created group with 1 user)
Idle Timeout: 0
Hard Timeout: 0
Concurrent user logins: yes
SSL Cert: none
Hostname: <empty>

**Comment by fichtner** [comment]
Hi @abplfab,

See https://github.com/opnsense/core/issues/1990 -- 17.7.10 is issued today, but there is a workaround included in the ticket.


Cheers,
Franco
