### ISSUE TITLE
Transparent Proxy Port Forward Rule Failing

### ISSUE THREAD

**Issue by sempervictus** [opnsense/core#1995]
Creating a transparent proxy for Tor port 9040 using the interface's network addresses (10.0.3.0/24) as the permissible source, any source and dst port, and all of it being forwarded to 127.0.0.1:9040. Same setup as the transparent HTTP proxy writeup in the docs, just the dst port is "any" in the original packet.
Enabling this DNAT along with its FW rule generates:
```
opnsense: /usr/local/etc/rc.filter_configure: New alert found: There were error(s) loading the rules: /tmp/rules.debug:58: syntax error - The line in question reads [58]: nat on em0_vlan3 inet proto tcp from 10.0.3.0/24 to 127.0.0.1 port -> (em0_vlan3)
```
That seems to be missing the dst_port on localhost (9040), and complaining about that fact. Am i doing something wrong or is the UI passing the wrong data to the firewall? This is all on a current version (updated this morning).

**Comment by fichtner** [comment]
As per web proxy template dst port should be "(other)" with 9040 set, also for the target redirect port. "any" seems weird here, it'll fail, maybe just because "port" is in there when it should match all or explicitly state the full range ("any").

Maybe @AdSchellevis knows this better.

**Comment by sempervictus** [comment]
So the matcher for the rule is TCP/IP (10.0.3.0/24:any) -> TCP/IP(any:any), the redirect target is TCP/IP(localhost:9040), at least in the firewall GUI. What it produces doesnt seem to be that. :)

Thanks for looking into this

**Comment by fichtner** [comment]
It would probably work if you did "(other)" from 1 to 65535. We'll fix the "any" to do the same one way or another, but I don't want to decide.

**Comment by AdSchellevis** [comment]
lots of things have changed in the rule generation, this might be fixed in the process
