### ISSUE TITLE
NTPd IPv6

### ISSUE THREAD

**Issue by abplfab** [opnsense/core#1997]
Would be nice to see the whole IPv6 in the Status Page (2a02:...):
![grafik](https://user-images.githubusercontent.com/28706980/34068954-53e94f48-e246-11e7-8acc-878ad984bdc9.png)

**Comment by fichtner** [comment]
Ciao Fabian,

Indeed... :)


Cheers,
Franco

PS: Please prod on other issues you would like to see fixed, we're circling back to smaller fixes for final 18.1 inclusion now.

**Comment by fichtner** [comment]
This should do the trick:

    # opnsense-patch b98c3c7
