### ISSUE TITLE
System: Access: Users -> Save & Close

### ISSUE THREAD

**Issue by abplfab** [opnsense/core#2000]
When adding multiple users it would be nice if the save button closes the window and returns to the user list. Or maybe make an additional button "Save & Close".

**Comment by AdSchellevis** [comment]
@abplfab that is practical indeed, https://github.com/opnsense/core/commit/2d76299e68f197288e299f5c0d1231f37e5b8819 adds the button

**Comment by fichtner** [comment]
ebb191d was pretty bad, it dropped my admin's group memberships... no more page access after save :)

**Comment by AdSchellevis** [comment]
@fichtner oops, sorry about that.
