### ISSUE TITLE
ipsec, kill filterdns

### ISSUE THREAD

**Issue by AdSchellevis** [opnsense/core#2003]
Probably up for discussion, ipsec.inc uses filterdns to reload ipsec when a fqdn times out. The question is if this is still a valid requirement. 
The code originally came from m0n0wall and was pulled in a long time ago https://github.com/pfsense/pfsense/commit/979cd6db9c6a81493498660f7205faabf25ed6ec when racoon was still used.

Reading the help text of strongSwan https://wiki.strongswan.org/projects/strongswan/wiki/ConnSection, kind of suggest that dns changes should be detected automatically.

```
left|right = <ip address> | <fqdn> | %any | range | subnet
......
If an FQDN is assigned it is resolved every time a configuration lookup is done. If DNS resolution times out,
the lookup is delayed for that time.
......

```

The release log for version 4.1.4 (our version 5.6.x) seems to suggest dyndns support too https://wiki.strongswan.org/projects/strongswan/wiki/414

**Comment by AdSchellevis** [comment]
the name resolving magic doesn't even seem to be used... https://github.com/opnsense/core/blob/f2ffe3f8ee58be428b3cbc8b4999c6294c5dc878/src/etc/inc/plugins.inc.d/ipsec.inc#L822-L837

both `$rg` and `$rgmap` doesn't seem to appear anywhere...

**Comment by AdSchellevis** [comment]
@fichtner feel free to revert https://github.com/opnsense/core/commit/e8a4fc1b46d83024d5b703333552866bfc97b12f if it's a bad idea.

**Comment by fichtner** [comment]
@mimugmail should look at this, but AFAIK, he only used ping hosts which is something else. I'm all for letting filterdns die a graceful death and retrace if necessary.

**Comment by AdSchellevis** [comment]
let's wait for @mimugmail then and if he can't think of a reason it should stay, we should just trash it and see what happens :)

**Comment by mimugmail** [comment]
No I dont use it .. this should be handled by the daemon itself :) 
Throw this piece of code away ...

**Comment by fichtner** [comment]
Ok, poof... gone. :)
