### ISSUE TITLE
Show ! on traffic shaper rules table on invert selection

### ISSUE THREAD

**Issue by tkald** [opnsense/core#2004]
For now rules with invert source / dest selected are indistinguishable in traffic shaper rules table.
Please add exclamation mark infront of source / dest row if either invert rule is selected (as implemented with firewall rules).

**Comment by fabianfrz** [comment]
I made a patch in #2006. You may want to try it.

**Comment by AdSchellevis** [comment]
@fabianfrz sure, thanks again.
