### ISSUE TITLE
Firewall: Diagnostics: States Dump - formatting issue

### ISSUE THREAD

**Issue by adam2104** [opnsense/core#2005]
Hello, I'm running Opnsense 17.7.10. In the "Firewall: Diagnostics: States Dump" screen, there appears to be a formatting issue on states that are NAT'ed from inside to outside. For example:

207.153.29.239:26936 -> 192.168.1.30:6338117.248.143.57:443

Note, the space missing between in the inside address:port and the destination address and port. It should read:

207.153.29.239:26936 -> 192.168.1.30:63381 17.248.143.57:443

That's still kind of hard to read though. Better yet, maybe, would be to format it like the output of "pfctl -ss"

207.153.29.239:26936 (192.168.1.30:63381) -> 17.248.143.57:443

**Comment by AdSchellevis** [comment]
@adam2104 this https://github.com/opnsense/core/commit/f58c2ece056a6d9c4655db3aa6efdc7baa460575 should do the trick

**Comment by adam2104** [comment]
Yep, it sure does! Thanks!

**Comment by AdSchellevis** [comment]
your welcome, thanks for reporting!
