### ISSUE TITLE
FR: Ability to define additional custom dhcp server section

### ISSUE THREAD

**Issue by tkald** [opnsense/core#2009]
So we could run scripts on dhcp leases and so on...

> on commit {
>         set clip = binary-to-ascii(10, 8, ".", leased-address);
>         set clhw = binary-to-ascii(16, 8, ":", substring(hardware, 1, 6));
>         execute("/usr/local/sbin/dhcpevent", "commit", clip, clhw, host-decl-name);
>     }

**Comment by AdSchellevis** [comment]
timeout (https://github.com/opnsense/core/commit/7338549ba5f295f5420e45ba74112af10d20c713)
