### ISSUE TITLE
GUI : Transparent proxies (both http/https) make GIU unreachable 

### ISSUE THREAD

**Issue by lezidev1** [opnsense/core#2011]
Hello everyone

In my training project, I need to set up a captive portal connected to a wireless access point. The last one distributes DHCP on the LAN interface. I have two network cards not three as suggested in documentation tutorial ; it's not possible so I tried on two cards configuration.

I have an issue on the captive portal, more precisely on the web GUI. Actually I tried to add http and https transparent proxies on it which is on the LAN network card.
However when I did this, it was on the LAN interface (web GUI and guestnetwork are on this interface) and now I can't get access on the GUI. It makes sense, this is what the transparent proxies should do. 

Of course I'm stuck now.. I tried to undo the LAN interface on my server but it appears the configuration is still the same. 
N.B. The captive portal still work on the LAN interface 

LAN is : 10.100.70.0 
WAN is : 10.100.71.0
and the Web GUI is on 10.100.70.254

EDIT: I tried this on account of HTTPS certificate issue when clients need to log on but the browser shows certificate error.

**Comment by AdSchellevis** [comment]
@lezidev1 would you be so kind to keep discussions on our forum? (I noticed the same question on our forum too)

easiest steps to reconfigure your box, with a factory reset is to flush all firewall related configurations, go to the gui and then reapply settings when done.

```
ipfw flush 
pfctl -d
```

Then configure your firewall, next your captive portal....

**Comment by lezidev1** [comment]
Thanks for reply :) Yes it doesn't matter, I keep going in the forum.

So your proposition works perfecty. I go check if anyone solved the https issue. Thanks a lot.
