### ISSUE TITLE
SMTP notification not working with german web UI

### ISSUE THREAD

**Issue by 90er** [opnsense/core#2015]
Hi,

i came accross with an bug using OPNsense with the web UI set to german language (https://<IP-Address>/system_general.php).

When i try to validate the SMTP notification configuration with web UI language set to english, everything is workin fine. If i change the language to german, nothing happens (click on "Test SMTP" @ https://<IP-Address>/system_advanced_notifications.php). I do not receive an E-Mail with web UI language set to german.

I tested it with versions: 17.7.10, 17.7.11

Currently running:
OPNsense 17.7.11-amd64, FreeBSD 11.0-RELEASE-p17

Best regards
Wolfgang Hofbauer

**Comment by fichtner** [comment]
Hi Wolfgang,

Thanks, I'll take a look.


Cheers,
Franco

**Comment by 90er** [comment]
Hi Franco,

i received the missing test e-mails in my spam folder. All with english web UI in my Inbox, all with german web UI in spam folder. 

Hope this helps. 

Wolfgang

**Comment by fichtner** [comment]
Sounds like a spam filter issue on the receiving end then, not a bug. What are you testing against? Maybe a German free mail provider?

**Comment by 90er** [comment]
I'm hosting an email server with postfix, dovecot and rspamd.

As you can see in the attached screenshot, the email with german language has an much higher score rating (second score result):

<img width="379" alt="spam" src="https://user-images.githubusercontent.com/17730136/34326368-f4bb628e-e8aa-11e7-8fb4-4cbc0233d44a.png">
