### ISSUE TITLE
Firewall: Settings: Advanced ---> Allow IPv6 logging enabled?

### ISSUE THREAD

**Issue by adam2104** [opnsense/core#2016]
I'm running OPNsense 17.7.11. I have "Allowed IPv6" UNchecked on Firewall: Settings: Advanced. If the "Log packets matched from the default block rules put in the ruleset" option is enabled the IPv6 blocking rule also logs, see from pfctl -sr output:

block drop in log quick inet6 all label "Block all IPv6"

This seems counter intuitive to me. I've actively disabled IPv6, I don't need/want to see the packets in the firewall log. This isn't a default block rule.

Alternatively, if this was intentionally logged, the rule icon in the Floating firewall rules list doesn't show the log icon.

**Comment by AdSchellevis** [comment]
The log description from the log settings could be a bit better probably, what it means is that all automatically generated rules contain a log target (same setting for block as accept).
I don't think we should change anything here, from historical perspective people seem to expect this and putting more logic in the firewall interface will make it even harder to rebuild them in the future. 
(next person will complain about the anti-lockout rules for example)

A better description for the log page should be enough probably, suggestions for both checkmarks are certainly welcome.

**Comment by AdSchellevis** [comment]
timeout (https://github.com/opnsense/core/commit/7338549ba5f295f5420e45ba74112af10d20c713)
