### ISSUE TITLE
Configuration backup file date issues (diag_confbak.php)

### ISSUE THREAD

**Issue by jschellevis** [opnsense/core#202]
From Forum by Gpac (https://forum.opnsense.org/index.php?topic=526.msg1740#msg1740)

My platform : Alix SD3 (time is lost when power-off).
OPNsense release : 15.1.11.1 nano

System made automatically some backups before syncing time with NTP server => these backups appears dated 1/1/2000 from CLI with file names config-946685???.xml

From web GUI they appear "Unknown" date.

From GUI trying to remove those with "Unknown" do not work (I think because malformation of URL which didn't get proper backup file no : https://192.168.2.1/diag_confbak.php?rmver=)

From GUI trying to remove those with a date works bizarrely :
+ clicking on the "x" seems to work (we go to confirmation screen)
+ file is actually removed from the disk & GUI says "Deleted Backup...", but stays with the confirmation screen.
If you click on "Config History" to reload the list of backups, the deleted backup is still present in the list.

**Comment by AdSchellevis** [comment]
code tried to remove filename by revision id in the file it self, if for some reason they are not 100% in sync this fails. 
Changed to search by revision id and put some quick fixes in the gui part.
For details, see https://github.com/opnsense/core/commit/949542defa7bb9a24c63fb41f9a2222c060f96ff
