### ISSUE TITLE
Does start/stop arguments in actions file support Jinja templating?

### ISSUE THREAD

**Issue by mimugmail** [opnsense/core#2022]
Sorry if this is a stupid question :) I have a daemon (lldpd) with arguments which wont be read by a conf.

If I start it with -c it supports also CDP. I have no idea how to put this model (enable/disable checkbox) to the actions config. 

Perhaps there's already a smart option I'm not aware of :)

Only thing I could imagine is a script called instead of the one in /usr/local/etc/rc.d with some custom parameters.

**Comment by AdSchellevis** [comment]
Usually the rc config file supports the extra options, like the one we use for suricata https://github.com/opnsense/core/blob/master/src/opnsense/service/templates/OPNsense/IDS/rc.conf.d if it doesn't you might need changes to the rc script in place or write a custom wrapper around it.

**Comment by mimugmail** [comment]
Nice, I'll give it a try, thanks!

**Comment by fichtner** [comment]
Normally SERVICENAME_flags="" is supported by the rc vars... see the rc file for details :)

https://github.com/opnsense/ports/blob/master/net-mgmt/lldpd/files/lldpd.in#L25

**Comment by mimugmail** [comment]
Works, thanks! 👍
