### ISSUE TITLE
system: serial via USB support

### ISSUE THREAD

**Issue by fichtner** [opnsense/core#2026]
via: https://forum.opnsense.org/index.php?topic=6702.0

**Comment by sjorge** [comment]
Just an FYI, the tty naming seems to be consistant for usb serial ports!
```
[iris :: sjorge][~]
[.]$ ls /dev | grep ttyU
ttyU0
ttyU0.init
ttyU0.lock
ttyU1
ttyU1.init
ttyU1.lock
ttyU2
ttyU2.init
ttyU2.lock
ttyU3
ttyU3.init
ttyU3.lock
```
This is from a FreeBSD box (not OPNsense) with a usb to 4x serial adaptor.

So you can probably target ttyU0 as the first detected serial interface over USB rather reliably.

**Comment by fichtner** [comment]
Yes, but the real question is for /etc/ttys rewrite. Replace serial ttyu* with ttyU* or add both side by side without issues? I'll look into it when I have a bit more time.

**Comment by sjorge** [comment]
I think it is replace, I never to serial + serial over lan to work. I always just one of the too. But I am no expert on this.

**Comment by fichtner** [comment]
I've implemented a checkbox to enable USB-based serial ports.
