### ISSUE TITLE
Allow dot (.) in pkgname or rename acme.sh package

### ISSUE THREAD

**Issue by fvanroie** [opnsense/core#2031]
The pkgname sanitizer filters dot (.) characters from the packagesnames passed to the FirmwareController.php API in core/src/opnsense/mvc/app/controllers/OPNsense/Core/Api/FirmwareController.php

The "acme.sh" package contains a dot (.) in the pkgname and this character gets sanitized by the filter, leading to the package not being found. Affected commands: install, remove, reinstall, lock, unlock, license 

Example output: (notice the missing dot in the package name)

```
***GOT REQUEST TO REINSTALL: acmesh***
pkg: No packages available to install matching 'acmesh' have been found in the repositories
```
```
***GOT REQUEST TO LOCK: acmesh***
***DONE***
```

**Comment by fichtner** [comment]
Nice catch, I've added the dot to the allowed characters. :)
