### ISSUE TITLE
use rule label not just number

### ISSUE THREAD

**Issue by lamixer** [opnsense/core#2034]
Hello. I suggest when the user has requested to show (as a new line) which rule caused a firewall action in the firewall log gui, you show not only the rule number, which is pretty useless by itself, to show the rule number PLUS the LABEL which describes the rule.

I posted a longer explanation here: https://forum.opnsense.org/index.php?topic=6735.msg29086#msg29086

**Comment by AdSchellevis** [comment]
The new live firewall log for 18.1 already includes labels 
![image](https://user-images.githubusercontent.com/9783985/34456264-a8796af0-ed92-11e7-9cc7-277876a0f924.png)

Only small detail is that when rules change, the label might be wrong (due to the fact that the label is from the active rule).

**Comment by lamixer** [comment]
That is a nice improvement for the live view... I will certainly enjoy that!

Still, if you are keeping the 'show rule number on a second line' option for the the standard log view, and if it's not too much work, I think you should still consider my suggestion. Thanks.

**Comment by AdSchellevis** [comment]
The old log view goes away in 18.1, so there's no real need to change anything there.

**Comment by lamixer** [comment]
Indeed! Makes sense. Thanks.
