### ISSUE TITLE
FR use kea instead of isc dhcp

### ISSUE THREAD

**Issue by L1ghtn1ng** [opnsense/core#2035]
This link has more information on the differences between the 2
https://www.isc.org/kea/ but as a quick overview please see the following picture
![screenshot-2017-12-30 kea dhcp server internet systems consortium](https://user-images.githubusercontent.com/3628354/34457137-f8bd89f8-ed9f-11e7-8448-7abda2dec82c.png)

**Comment by fabianfrz** [comment]
kea looks cool but there are two major issues:
* we do not have postgresql on OPNsense (and it is hard to integrate)
* we are currently having a new major release and such changes will not be done in a minor release
* lots of code have to be rewritten but the hooking sounds interesting but it seems to be C++ only (https://jenkins.isc.org/job/Kea_doc/doxygen/dd/dfa/hooksComponentDeveloperGuide.html).

**Comment by L1ghtn1ng** [comment]
@fabianfrz I did not expect this to be for 18.1 well aware of the current state of 18.1 and you do not need to use postgres you can use a memfile. Also the hooks will be supported for all languages but as you have pointed out currently only C++ but if someone can find the information as to when support for other languages are coming then it everything should be good ?

**Comment by L1ghtn1ng** [comment]
@fabianfrz Also found this
![screenshot-2017-12-30 kea administrator reference manual](https://user-images.githubusercontent.com/3628354/34457618-f23e4938-edad-11e7-843a-159a558b6992.png)

**Comment by fabianfrz** [comment]
as you can see from that screenshot, memfile does not support per host configuration and sharing of lease information which is mandatory for HA setups.

**Comment by L1ghtn1ng** [comment]
IIRC from what I read it gets put into a config file but for HA and memfile please see this 
```High Availability

We want to address the need for high availability for DHCP services. ISC DHCP supports DHCPv4 failover, but this is a complicated and fragile protocol, and we are hoping to avoid implementing it in Kea. A number of Kea users have reported on the Kea-users mailing list that they have managed to build HA Kea systems using a shared database backend but there is no way, currently, to have a HA system with the higher-performance memfile system.

We have written up a design plan for HA support for Kea that includes load balancing between systems using the memfile option. It is posted on the Kea wiki for review.
```
Taken from https://www.isc.org/blogs/planning-for-kea-1-4/

**Comment by fabianfrz** [comment]
just downloaded 1.3 and it seems to be not compiling:

```
checking whether Boost tries to use threads... yes
checking Boost offset_ptr compiles... yes
checking Boost numeric_cast compiles with -Werror... yes
checking BOOST_STATIC_ASSERT compiles... yes
checking for Boost system library... no
configure: error: Linking with  -lboost_system is not enough: please make sure libboost_system is installed; Check config.log for details, you may be missing other libraries.
```

The FreeBSD package offers 1.0 which might be outdated.
I installed boost from the FreeBSD repository and `boost_system` exists.

**Comment by L1ghtn1ng** [comment]
Have you read this? kea build<https://ftp.isc.org/isc/kea/1.3.0/doc/kea-guide.html#configure>
________________________________

**Comment by AdSchellevis** [comment]
timeout (https://github.com/opnsense/core/commit/7338549ba5f295f5420e45ba74112af10d20c713)

**Comment by dBitech** [comment]
It would be worthy to revisit this.  KEA since Version 1.4 supports HA using any of the backends

**Comment by o1crimson1o** [comment]
> It would be worthy to revisit this. KEA since Version 1.4 supports HA using any of the backends

I agree, would love a switch to this.

**Comment by thefiredragon** [comment]
This would be a great point, could this ticket someone reopen?

**Comment by fichtner** [comment]
Unless isc-dhcpd is EoL I don't see an open source route for kea integration. If someone wants to start a plugin that would maybe help an eventual migration. But mind you the DHCP implementation is quite complex...


Cheers,
Franco

**Comment by fhloston** [comment]
isc-dhcpd is actually EoL now. 

https://www.isc.org/blogs/isc-dhcp-eol/

**Comment by L1ghtn1ng** [comment]
@AdSchellevis @fichtner Can this be re-opened now please due to isc-dhcpd actually being EoL now?

**Comment by AdSchellevis** [comment]
@L1ghtn1ng no, it's not on our roadmap.. If you wish to build a plugin, just open a PR in the plugins repo. more context on our forum https://forum.opnsense.org/index.php?topic=30642.msg147818#msg147818

**Comment by MaZe3D** [comment]
I mean EOL means End of Life. It should not be outdated software within a network device, let alone if the device is a firewall and routing solution. The bug should jump up in the priority list.

To quote ISC at https://www.isc.org/dhcp/
> ISC has announced the end of life for ISC DHCP as of the end of 2022. ISC will continue providing professional support services for existing subscribers, **_but does not intend to issue any further maintenance releases_**.

**Comment by L1ghtn1ng** [comment]
There is a port in FreeBSD for kea

If people are not aware https://cgit.freebsd.org/ports/tree/net/kea

On 8 Mar 2023, at 21:58, MaZe ***@***.***> wrote:

﻿

May I ask, what alternatives to consider? I am not that big in the "knowing all dhcp-server-application"-game ;D
A first move would be discussing a viable service. Maybe it will be kea, maybe not.
And yes, I know complaining is not the solution and if I can, I will contribute. My current problem about this is the lack of knowledge about freebsd and development with opnsense itself.

**Comment by L1ghtn1ng** [comment]
There is also this to help with said migration to kea https://cgit.freebsd.org/ports/tree/net/keama I am also not aware of any alternatives other than kea myself as well so would be interested in knowing how things are going to done in OPNsense

On 9 Mar 2023, at 00:13, Jay Townsend ***@***.***> wrote:

﻿ There is a port in FreeBSD for kea

If people are not aware https://cgit.freebsd.org/ports/tree/net/kea

On 8 Mar 2023, at 21:58, MaZe ***@***.***> wrote:

﻿

May I ask, what alternatives to consider? I am not that big in the "knowing all dhcp-server-application"-game ;D
A first move would be discussing a viable service. Maybe it will be kea, maybe not.
And yes, I know complaining is not the solution and if I can, I will contribute. My current problem about this is the lack of knowledge about freebsd and development with opnsense itself.

**Comment by L1ghtn1ng** [comment]
Well other than dnsmasq which there is also a port for as well but not sure if that would fit the bill as it were, could be wrong

On 9 Mar 2023, at 00:13, Jay Townsend ***@***.***> wrote:

﻿ There is a port in FreeBSD for kea

If people are not aware https://cgit.freebsd.org/ports/tree/net/kea

On 8 Mar 2023, at 21:58, MaZe ***@***.***> wrote:

﻿

May I ask, what alternatives to consider? I am not that big in the "knowing all dhcp-server-application"-game ;D
A first move would be discussing a viable service. Maybe it will be kea, maybe not.
And yes, I know complaining is not the solution and if I can, I will contribute. My current problem about this is the lack of knowledge about freebsd and development with opnsense itself.

**Comment by mimugmail** [comment]
FreeRADIUS plugin already has DHCP support, we (the community) can work on it extending it's features and it's already MVC.
In the long run it would not replace the existing implementation, but for concerned people it could be an alternative.
