### ISSUE TITLE
firewall/nat: add functionality for adding persistent DNAT

### ISSUE THREAD

**Issue by fabianfrz** [opnsense/core#2037]
Follow up for #1326

For example:
Select all interfaces you like to run a transparent proxy on. The code will then add the rules like that to the pf.conf
```bash
rdr on $interface  proto $proto from any to ($interface) port $protocol_port -> $host:$protocol_port
```

maybe some prototype like
```php
<?php
function add_dnat_rule($interface, $original_port, $destination_port, $protocol = 'tcp', $host = '127.0.0.1')
```

so a rule for squid would be (pseudocode):
```php
<?php
foreach ($interfaces as $key => $value) {
  $fw->add_dnat_rule($value, 80, 3128);
  $fw->add_dnat_rule($value, 443, 3129);
}
```

**Comment by fichtner** [comment]
@AdSchellevis do we still need this?

**Comment by AdSchellevis** [comment]
to be honest, the current rule insertion works as a charm, it only lacks validation and a bit of documentation about the fields which are available. lets close this for now, I wasn't planning on providing another programming interface here at the moment.
