### ISSUE TITLE
Intrusion Detection: possibility to choose eve log as log output with several types (alert, http, dns, tls, files, ssh)

### ISSUE THREAD

**Issue by ifzenc** [opnsense/core#2038]
Hi,
It could be nice to be able to select the log output as eve.json instead of fast.log and be able to select syslog instead of file. Additionally, the types should be selectable.
A potential output in suricata.yaml would be: 

```
 - eve-log:
      enabled: yes
      type: syslog #file|syslog|unix_dgram|unix_stream
      filename: eve.json
      # the following are valid when type: syslog above
      identity: "suricata"
      facility: local5
      level: Info ## possible levels: Emergency, Alert, Critical,
                   ## Error, Warning, Notice, Info, Debug
      types:
        - alert:
             payload: yes
             payload-buffer-size: 100kb
             payload-printable: yes
             http: yes
             tls: yes
        - http:
            extended: yes     # enable this for extended logging information
            # custom allows additional http fields to be included in eve-log
            # the example below adds three additional fields when uncommented
            #custom: [Accept-Encoding, Accept-Language, Authorization]
        - dns
        - tls:
            extended: yes     # enable this for extended logging information
        - files:
            force-magic: no   # force logging magic on all logged files
            force-md5: no     # force logging of md5 checksums
        #- drop
        - ssh
```

This is very useful if sending logs to a SIEM like Splunk as json is automatically parsed.

Thank you.

Additional info:
Version OPNSense 17.7.11
URL: ui/ids/

**Comment by AdSchellevis** [comment]
Files are already in eve format (/var/log/suricata/eve.json), which is used by our log viewer. syslog currently uses fast.log (as mentioned in the help text). 

I'm not sure you can select the syslog output and still keep the file output we have now, which is needed for our product. Another option is to ship the log files using filebeat or similar from disk to the SIEM product.

**Comment by ifzenc** [comment]
Thanks for your reply.
You're probably right it doesn't seem to be possible to have simultaneously syslog and file for eve format. I understand that you use the file for the log viewer, but it could be great to have the choice in the UI as well as the type of events to log.

In my configuration, I don't want to write logs on disk as it uses flash disk, that's why I chose syslog for eve.

**Comment by AdSchellevis** [comment]
timeout
