### ISSUE TITLE
APU1D4 won't start automatically

### ISSUE THREAD

**Issue by groveld** [opnsense/core#204]
After an successful installation, my platform idles on this screen.
i can press <ENTER> and all works fine, but why doesn't it skip this menu after the normal 3 seconds?

i'm using an PC Engines APU1D4 board with a 60GB mSATA drive.
install completes without any problems or any error messages whatsoever.
tried to install from USB and SD.

![schermafbeelding 2015-06-03 om 10 56 43](https://cloud.githubusercontent.com/assets/3328493/7956307/5f61cd1a-09df-11e5-8d4e-90618cc784a1.png)

**Comment by AdSchellevis** [comment]
Just checked it using a pcengines 16Gb mSATA drive on a APU1D and this functions correctly. 
It looks like either a compatibility issue with your drive or with your installed config.

**Comment by fichtner** [comment]
Maybe there is a garbage character on the serial console. Do you see the countdown at all?

**Comment by groveld** [comment]
No, it looks like a kernel crash, because the indicator (-/|\) stops at - or / but responds perfectly to user input.
on a vpc or old pc i indeed see a countdown, but not on my APU.

**Comment by groveld** [comment]
Found the problem! My Prolific usb-serial cable was throwing some trash-bits at the router, whitch in turn stopped the automagic boot sequence. Problem was solved using a usb-serial adapter with an FTDI chip.

**Comment by fichtner** [comment]
Glad to hear that. Thanks for checking back. :)
