### ISSUE TITLE
URL Aliases not being updated by script

### ISSUE THREAD

**Issue by brandonmreeves** [opnsense/core#2042]
It appears the URL Alias table update script is not updating the file properly for changes to the tables or associated rules. We have tried using the interface setting the cron to run more regularly and running the scripts manually.

Running /usr/local/etc/rc.d/rc.update_urltables does not appear to update the local file /var/db/aliastables/(tablename) even if the source has changed.

Version: OPNsense 17.7.11-amd64

**Comment by AdSchellevis** [comment]
18.1 will come with a total rewrite of the alias functionality, probably best to test the beta when it's available.

**Comment by fichtner** [comment]
what Ad means: release candidate. beta is already out (see below).

    # opnsense-update -t opnsense-devel
    # /usr/local/etc/rc.reboot


Cheers,
Franco

**Comment by brandonmreeves** [comment]
Great. Thank you. You can close this issue then. Also, we are one of the orgs that just purchased business support to implement Opnsense in AWS.

Thanks for the great product and support. Any support we can give you let us know. We want to make sure to keep the project going.

**Comment by fichtner** [comment]
@brandonmreeves thank you. if you can briefly check out the new alias framework and let us know via this ticket ... it can help polish the result for the 18.1 release further. :)

**Comment by brandonmreeves** [comment]
I performed the update and the form looks great. However the URL table does not appear to be updating at all. No initial data is populated in the pftables view

Also in log file the log continuously repeats:

Jan 3 01:59:42 | configd.py: [2b807da4-475c-4d70-8775-ac4d3bd3e98c] request content of pf iplist table

But never adds an IP address. Additionally, if the scripts are supposed to use the same directory structure (etc /var/db/aliastables) that no longer exists and is not created

**Comment by brandonmreeves** [comment]
Ok figured it out. I manually had to run mkdir /var/db/aliastables/ to make the directory. Then I ran the command to update the tables from the config script. After I did that the table updated properly.

Here is the command I ran via cli 
"/usr/local/bin/flock -n -E 0 -o /tmp/filter_update_tables.lock /usr/local/opnsense/scripts/filter/update_tables.py"

Which results in the appropriate file being created

**Comment by brandonmreeves** [comment]
That command does not however re-write the file if the source changes. So if we change the source file and re-run the command, let the cron job run as expected or just wait, none of the associated files change. 
There are 3 files included and none appear to get changed.

aliasname.md5.txt
aliasname.txt
aliasname.self.txt

All remain consistent after initial sync and never update.

**Comment by brandonmreeves** [comment]
Never mind last statement. It is a timing issue. Apparently based on the interface it is a timeout issue and regardless of the job running the alias does not get updated. Maybe the wording should be changed from update frequency in the interface to alias expiration or something else which is more clear.

Working now as I modified timing

**Comment by fichtner** [comment]
@AdSchellevis what do you think about the wording change? I kind of agree with @brandonmreeves 

@brandonmreeves sounds like you didn't reboot at first, could that have been your initial struggle with the new system?

**Comment by AdSchellevis** [comment]
@fichtner sure, I kept the caption like it was before (the function didn't change), but alias expiration sounds good to me. I will rename it in the next commit.

**Comment by brandonmreeves** [comment]
@fichtner Regarding your question. I am using a test box so basically, I ran the upgrade and rebooted immediately afterwards. There was not aliastables directory created for some reason. I can spin up another test box and try again today to see if results are the same.

**Comment by fichtner** [comment]
@brandonmreeves we're tracking the same issue via #2051 now, looks like it will receive a small fix before 18.1 is out :)
