### ISSUE TITLE
firmware: if the user root is disabled, firmware updates do not go through

### ISSUE THREAD

**Issue by fichtner** [opnsense/core#2045]
At this point it's not sure whether this is a bug or feature. ;)

Reported via forum PM.

**Comment by AdSchellevis** [comment]
likely more fails if you don't have a root user.... sounds like a feature ;)

**Comment by fichtner** [comment]
other things keep working as far as I know, maybe some oddity in "pkg" itself. still, worth finding out what causes this :)

**Comment by fichtner** [comment]
Disabling root works fine from my end. I don't know what happens when "admin" group is stripped, but frankly if it fails it should.
