### ISSUE TITLE
Traffic shaper rules tab does not show address invert in grid

### ISSUE THREAD

**Issue by tomfanning** [opnsense/core#2047]
Version: OPNsense 17.7.11-amd64

URL: https://opnsense/ui/trafficshaper/#rules

In the Traffic Shaper feature, on the Rules tab, if Invert Source or Invert Destination is ticked for a rule, I expect the Source or Destination cell in the grid to reflect this by showing something like "not" before the IP address. 

Currently the grid is the same regardless of whether Invert Source or Invert Destination is ticket.

**Comment by fichtner** [comment]
that should be fixed on -devel / upcoming 18.1, see https://github.com/opnsense/core/issues/2004

**Comment by tomfanning** [comment]
Impressively quick, thanks for the link.

**Comment by fichtner** [comment]
nevertheless, thank you for the report. it keeps us on our toes :)
