### ISSUE TITLE
Enhancement: Advanced OpenVPN configuration via GUI options

### ISSUE THREAD

**Issue by ashceryth** [opnsense/core#2048]
Hi,

It would be great if it would be possible to configure some more advanced settings for OpenVPN directly via options in the GUI rather than using the "Advanced configuration" field. I am thinking of GUI options reflecting the following OpenVPN config options:

- tls-version-min (e.g. allowing only TLS 1.2)
- tls-cipher
- tls-crypt (as an alternative to tls-auth)
- ncp-ciphers
- ecdh-curve
- compress (selection of the desired compression algorithm, e.g. lz4-v2)
- explicit-exit-notify 1 (when using UDP)

Is there anything planned? Also OpenVPN running as unpriviledged user would be superb :)

**Comment by fichtner** [comment]
I’ll work on this as time permits.

**Comment by imidoriya** [comment]
The client export also includes "--comp-lzo" which has been depreciated.  The new method is "--compress [algorithm]".

**Comment by ky41083** [comment]
+1 for this. Please ;-)

Security wise, these are very good controls to have. Some do not have a good way of implementing using the free form advanced settings box. Good as in, fully included in config backups / restores.

**Comment by trendchiller** [comment]
Should the TLA-AUTH feature be replaced by TLS-CRYPT or be choosable as an alternative ?
i need this feature also very desperately, so i perhaps community could help on this (if desired) ?

**Comment by ky41083** [comment]
tls-auth and tls-crypt should coexist as selectable options. One does not deprecate the other. You can only use one of them at a time. If nothing else, they should both remain as options for backwards compatibility with pre-existing setups.

**Comment by fichtner** [comment]
@AdSchellevis maybe you have incentive to work on this earlier, for now I'll have to push to 19.7

**Comment by AdSchellevis** [comment]
@fichtner I have no plans for this at the moment, move further is certainly fine.

**Comment by Bytechanger** [comment]
Hello,
I also need   tls-crypt   option for more security.
At this time I run my openvpn-server on my raspberry!

**Comment by Keltere** [comment]
+1 on tls-crypt, without it it's really a pain

**Comment by galvanopus** [comment]
It would be nice to have this feature implemented.

Btw, there is a workaround:
1. Disable TLS authentication.
2. Paste the following into Advanced section:
```
<tls-crypt>
#
# 2048 bit OpenVPN static key
#
-----BEGIN OpenVPN Static key V1-----
key data here
-----END OpenVPN Static key V1-----
</tls-crypt>
```

**Comment by hugosxm** [comment]
Hi, we are planning to migrate all our pfsense boxes ( 30 boxes aprox. ) to opnsense because we found opnsense better but this "missing" ui feature for openvpn is quite annoying we have to say, would be really appreciated if this is done in the next release

sorry for my english !

**Comment by FingerlessGlov3s** [comment]
Hi Guys,

If we could implement Negotiable Crypto Parameters (NCP) in the WebUI of OPNsense would be great, this feature was added back in OpenVPN 2.4

This would aid with OpenVPN deployments, when trying to move to new cyphers as and when ones are depreciated or considered not as secure, EG CBC to GCM.

https://community.openvpn.net/openvpn/wiki/CipherNegotiation

**Comment by khicks** [comment]
This is a big requirement for folks looking for a drop-in replacement for pfSense. Administrators of multi-user environments have already distributed OpenVPN configs, and having no option for tls-crypt means they're going to have to shoehorn it in or redistribute configs.

No GUI option for tls-crypt would be acceptable if the Advanced config field wasn't being deprecated. Without it, administrators wanting _improved_ security will have to dig into the file system, which is far from ideal. I really hope that the OpenVPN GUI configuration tool will have all of the common options before the Advanced field gets taken away.

**Comment by trendchiller** [comment]
I approached this problem with this workaround so far:
https://github.com/trendchiller/OPNsense/commit/5f044ce6bc8d31f557e47f9189475409628a3849
The goal was backward compatibility and improved security.
I wanted to commit, when the exporters were ready, but so I'll stop work until we have a status ;-)

**Comment by beren12** [comment]
> This is a big requirement for folks looking for a drop-in replacement for pfSense. Administrators of multi-user environments have already distributed OpenVPN configs, and having no option for tls-crypt means they're going to have to shoehorn it in or redistribute configs.
> 
> No GUI option for tls-crypt would be acceptable if the Advanced config field wasn't being deprecated. Without it, administrators wanting _improved_ security will have to dig into the file system, which is far from ideal. I really hope that the OpenVPN GUI configuration tool will have all of the common options before the Advanced field gets taken away.

The problem is *advanced* options will never be 100% covered from the GUI, and it's far far better security to see the advanced config then to have it hidden in a file nobody ever knows to check.

**Comment by trendchiller** [comment]
perhaps it could be an idea to habe a checkbox in system-settings to "enable. advances settings" which "unhides" the advanced config boxes ?
so they could be hidden by default and enabled by users which are experienced ?

**Comment by ITJamie** [comment]
I would also like the export file type option contain a .ovpn export option. right now it comes down as filename.ovpn.txt. this means its not easy to import into openvpn apps on ios/android

**Comment by AdSchellevis** [comment]
better open new issues after 23.7 is released aiming the new `Instances` option
