### ISSUE TITLE
Enhancement: Set RADIUS NAS-Identifier dynamically

### ISSUE THREAD

**Issue by ashceryth** [opnsense/core#2049]
Hi,

As far as I am aware the NAS ID for RADIUS requests is always set to the RefID from config. To better distinguish between the reguests on the RADIUS server side it would be great if the NAS ID would be set dynamically based on the source of the request. By now to achieve an distinction it is possible to create an own auth profile for each service. Better: For example if a RADIUS authentication profile is used for OpenVPN server 1 the NAS ID should be set to something like "openvpn-server1". This way it would be possible to create different AAA policies based on the OpenVPN server instance. The same would be great for any other place where RADIUS is used. Maybe also a GUI option for setting the NAS ID would be helpful.

**Comment by AdSchellevis** [comment]
timeout

**Comment by schreiberstein** [comment]
Is there a solution to this?
Right now, it seems I need to start my target radius server in debug mode to be able to find out the NAS identifier, which is some completely random string.
Is there some way to set it to the FQDN of the opnsense appliance?

**Comment by mimugmail** [comment]
If you know the config syntax I can add it
