### ISSUE TITLE
Wireless Association Breaks Networking

### ISSUE THREAD

**Issue by lattera** [opnsense/core#205]
So I'm totally willing to admit this might be a case of PEBCAK. I just set up wireless on a recent build of OPNSense + HardenedBSD (built 02 Jun 2015). Before any wireless clients associate, networking works fully and `ping google.com` works. But once a client successfully associates, all networking dies. I can't even ping my upstream gateway. If you need a build, here's the memstick image of the same build: https://hardenedbsd.org/~shawn/opnsense/OPNsense-201506021216_OpenSSL-serial-generic-amd64.img.xz

**Comment by fichtner** [comment]
I this still the case, Shawn?

**Comment by lattera** [comment]
I fixed this in the interim through doing a `sleep 10` before rc.bootup is called. This might be specific to the Netgate RCC-VE 4860. When I get home from bsdcan, I'll test on my Deciso appliance as well.

**Comment by fichtner** [comment]
Will continue this in #218, not only related to wifi stuff.
