### ISSUE TITLE
security/tinc: mtu calculation

### ISSUE THREAD

**Issue by mockare** [opnsense/core#2057]
tinc does not always calculate MTU correctly, with the default settings it causes VPN to go very slow, I had to force it by changing on the local node and in the remote node to get full speeds, the following lines:
PMTU=1514
PMTUDiscovery=no
could you add these to the web gui as configurable parameters

Another suggestion would be being able to add extra lines to the tinc-up via the web-gui as well (so to add static routes for instance)

I'm running the latest non-dev version

**Comment by AdSchellevis** [comment]
We're usually not adding text inputs for validation reasons, adding the mtu settings probably won't be a problem. 

Should a manual PMTU automatically disable PMTUDiscovery? (one setting in stead of 2)

**Comment by mockare** [comment]
Actually not, but PMTU=1514 is the default so a simple combo box for PMTUDiscovery (yes or no) should be enough

**Comment by AdSchellevis** [comment]
@mockare this https://github.com/opnsense/plugins/commit/e338624afb2274db4efa5f91cb40758cb6498c57 should do the trick. I just noticed you opened the issue in core, but as it's a plugin it should be in our plugins repository, but that's for the next time.

**Comment by fichtner** [comment]
Shipped in 18.1 already.
