### ISSUE TITLE
Menu display error with 18.1.r_2

### ISSUE THREAD

**Issue by mimugmail** [opnsense/core#2065]
Hi,

when I have menu Services and click HAProxy it stays some kind of up when scrolling the bar. If I then click on HAProxy it opens the menu of FreeRadius but with the submenu's of HAProxy. 
Hard to explain, I made a screen capture for you. When logging out and in again it's reproduceable (latest Chrome)
[vokoscreen-2018-01-07_14-11-32.mkv.zip](https://github.com/opnsense/core/files/1610659/vokoscreen-2018-01-07_14-11-32.mkv.zip)

**Comment by fichtner** [comment]
It's likely due to https://github.com/opnsense/core/commit/2b94b6691a I had a glitch with it too when testing, see https://github.com/opnsense/core/issues/1928

**Comment by mimugmail** [comment]
Any news to this? While looking at telegraf plugin: 
![image](https://user-images.githubusercontent.com/20438689/34920928-124e1680-f97b-11e7-88d1-b826e380bb2b.png)

**Comment by fichtner** [comment]
Ad is on vacation now, you'll have to ping me again via IRC to work on this a bit more.
