### ISSUE TITLE
configd: turn off non-error execution output

### ISSUE THREAD

**Issue by fichtner** [opnsense/core#2067]
Hi @AdSchellevis,

Since more and more commands are using configd the system log is becoming less and less informative.. can we somehow toggle the syslog output rate for configd, preferably making non-error messages opt-in or moving them to a different log?

Cheers,
Franco

**Comment by AdSchellevis** [comment]
@fichtner I have to look at that, another log target is certainly a good idea. not sure if I can find the time to fix this before 18.1
