### ISSUE TITLE
Parent Proxy feature

### ISSUE THREAD

**Issue by ackv** [opnsense/core#2068]
Asking for a ParentProxy feature.
At this time there is only one way to configure that in the opnsense filesystem. See: https://forum.opnsense.org/index.php?topic=6763.msg29327#msg29327

**Comment by MyLive** [comment]
it the same request as https://github.com/opnsense/core/issues/1671

**Comment by fichtner** [comment]
@MyLive indeed, thanks

**Comment by opnsenseuser12123** [comment]
Yes. Would be great to have this feature! thx

**Comment by mimugmail** [comment]
If there are no general concerns by @AdSchellevis or @fichtner I'd try to take over, need this too ..

**Comment by fichtner** [comment]
No concerns, please do.
