### ISSUE TITLE
Secure Shell option PermitRootLogin does not work as expected

### ISSUE THREAD

**Issue by theq86** [opnsense/core#2069]
Hello!

I'm using OPNsense 17.7.11. I have given the root user an authorized key to log in via ssh.
SSH login with the root user is working regardless of wether I turn on or off the option in the GUI.

If it is turned on, the sshd_config is added the line "PermitRootLogin yes".
If it is turned off, the line will be removed.

According to the sshd_config manpage this should work, since 'no' is the default option, if not mentioned in the config.

However, this can not be true. For experimenting, I added the line 'PermitRootLogin no' and guess what? Right, root login did not succeed even with key authentication. If you just omit the line, I guess the default option is 'without-password' even though the manpage states otherwise.

**Comment by fichtner** [comment]
Hi @theq86,

Better to lock this down indeed. You can try:

    # opnsense-patch 930fb80


Cheers,
Franco

**Comment by theq86** [comment]
@fichtner Thanks. Patch applied and confirmed working.

**Comment by fichtner** [comment]
Splendid, adding this to 18.1-RC2. Not going to backport to 17.7.x. :)
