### ISSUE TITLE
devd fails to start

### ISSUE THREAD

**Issue by lattera** [opnsense/core#207]
My core is at HardenedBSD/opnsense-core@99031ac6b019647543c6a9e6068d4103f4806cbc
My ports is at HardenedBSD/hardenedbsd-ports@10458df0c34dec31190c4e517d57bb5551bf628a
My tools is at HardenedBSD/opnsense-tools@bf29010fb8b6a5298ed9a2e27fa54699dd10b41d
My src is at HardenedBSD/hardenedBSD@57518daddcd121ad0a905e05ea35c35636bb9225

This causes more problems when wireless is set up. I'm unsure if this is from work I've done on the HardenedBSD side. I can provide a build for you if you want.

	Starting device manager (devd)...Traceback (most recent call last):
	  File "/usr/local/opnsense/service/configd_ctl.py", line 53, in <module>
	    sock.connect(configd_socket_name)
	  File "/usr/local/lib/python2.7/socket.py", line 231, in meth
	    return getattr(self._sock,name)(*args)
	socket.error: [Errno 2] No such file or directory

**Comment by lattera** [comment]
I've nailed it down to commit 435492adcfdf41a286b1d65a8a5dc4128b4d8cd9 (issue #201). Reverting that commit results in the removal of that error.

**Comment by fichtner** [comment]
Are you sure devd fails to start? devd seems to launch and immediately invokes configd_ctl.py, which isn't up yet (the socket anyway). The suspicious commit may only uncover something else like a faulty read in devd, because the new rules don't have actions and thus the behaviour shouldn't change at all.

Instead of revert, can you try adding actions for these rules a la "/usr/bin/true" just to make sure devd isn't doing something weird...

Can you also describe what "more problems when wireless is set up" means?

**Comment by lattera** [comment]
I'm unsure what is failing as I'm unfamiliar with configd. All I know is the error I pasted above. I'd be happy to try out /usr/bin/true if you could instruct me how to do so.

I'll add a log for what happens when this bug exists and wireless is configured. I get more python errors from configd and not a single interface is configured/brought up.

**Comment by fichtner** [comment]
Sounds like a more fundamental issue... configd is launched before devd, so there's probably something wrong with the daemon itself. Can you please provide output for:

# service configd status
# ls -lah /var/run/configd.socket

And if it is not running:

# service configd start

**Comment by lattera** [comment]
Can do. Will reply soon-ish with further details. I gotta spin and flash a new build.

**Comment by fichtner** [comment]
@AdSchellevis Hey Ad, do you think we could have a better error message in case the socket isn't up? :)

**Comment by lattera** [comment]
Output for the two commands you wanted:

    root@OPNsense:~ # service configd status
    configd is running as pid 12930.
    root@OPNsense:~ # ls -lah /var/run/configd.socket
    srw-rw-rw-  1 root  wheel     0B Jun  8 05:46 /var/run/configd.socket

I'll have the output of what happens when wifi is set up in a bit. Gotta find some extra networking cables lying around.

**Comment by fichtner** [comment]
Thanks, so far so good. Also interested in knowing whether devd is running ok in the background.

**Comment by lattera** [comment]
root@OPNsense:~ # ps wwaux | grep devd
    root   86151   0.0  0.1 490036  5156  -  Ss    5:46AM  0:00.04 /sbin/devd
    root   64242   0.0  0.0  65968  3396 u1  RV+   5:53AM  0:00.00 grep devd (csh)
    root@OPNsense:~ # service devd status
    devd is running as pid 86151.

**Comment by lattera** [comment]
Alright, so it's not specific with wireless. But this is what happens on the first reboot, no matter the network setup:

    Starting configd.
    Launching the init system... done.
    Initializing.................. done.
    Starting device manager (devd)...Traceback (most recent call last):
    File "/usr/local/opnsense/service/configd_ctl.py", line 53, in <module>
        sock.connect(configd_socket_name)
    File "/usr/local/lib/python2.7/socket.py", line 231, in meth
        return getattr(self._sock,name)(*args)
    socket.error: [Errno 2] No such file or directory
    Traceback (most recent call last):
    File "/usr/local/opnsense/service/configd_ctl.py", line 53, in <module>
        sock.connect(configd_socket_name)
    File "/usr/local/lib/python2.7/socket.py", line 231, in meth
        return getattr(self._sock,name)(*args)
    socket.error: [Errno 2] No such file or directory
    done.
    Loading configuration...done.
    Updating configuration...done.
    Setting up extended sysctls...sysctl: oid 'kern.randompid' is read only
    sysctl: oid 'kern.randompid' is read only
    done.
    Setting timezone...done.
    Configuring loopback interface...done.
    Starting syslog...done.
    Starting Secure Shell Services...
    Fatal error: Uncaught exception 'Exception' with message 'Failed to connect: No such file or directory' in /usr/local/opnsense/mvc/app/library/OPNsense/Core/Backend.php:67
    Stack trace:
    #0 /usr/local/etc/inc/util.inc(148): OPNsense\Core\Backend->configdRun('sshd restart', false)
    #1 /usr/local/etc/rc.bootup(194): configd_run('sshd restart')
    #2 {main}
    thrown in /usr/local/opnsense/mvc/app/library/OPNsense/Core/Backend.php on line 67
    Starting CRON... done.

    *** Welcome to OPNsense 15.1.11.3_9-b47419cc7 (amd64) on opnsense-dev-01 ***

    WAN (igb1)      -> 
    LAN (igb2)      -> 

    FreeBSD/amd64 (opnsense-dev-01.hardenedbsd.dev) (ttyu1)

    login:

**Comment by AdSchellevis** [comment]
@franco configd_ctl was kind of a quick fix to remove old code, I've just improved it to return more user friendly output on failures in https://github.com/opnsense/core/commit/e4cd84cb651175ebafa0b96e9fc9649b10412dbd

I've also added a symlink for command line usage, try : 
configdctl configd actions  

to receive a full list of registered actions for example.

**Comment by fichtner** [comment]
Closing this, feeling lucky.
