### ISSUE TITLE
ipsec: what to do with the mobile peer id

### ISSUE THREAD

**Issue by fichtner** [opnsense/core#2070]
https://github.com/opnsense/core/commit/0dd120

via: https://forum.opnsense.org/index.php?topic=6194.0

**Comment by mimugmail** [comment]
Is this only a ike v1 issue? One of the apprentices told me to be bored so I'll set up a test environment.

I also had struggles months ago troubleshooting Mac integrated client .. so this might bei the issue I had too

**Comment by fichtner** [comment]
could be. although for macOS I do not recommend v1 at all.

**Comment by fichtner** [comment]
I'm closing this, again, due to lack of feedback.

**Comment by wh0else** [comment]
Any update on this? IPsec/IKEv2 road warrior VPN with EAP-TLS/Mutual RSA seems to need mobile peer id, at least on clients such as macOS and iOS.
Working in pfSense, as the setting is there
