### ISSUE TITLE
How do you propose to specify NAT rules on bridges?

### ISSUE THREAD

**Issue by poige** [opnsense/core#2071]
Yeah, you know — those bridges that can be configured there: interfaces_bridge.php

What's worse — you don't allow to specify voluntary interface names in NAT rule editor.

That's again (another) proof that with the approach you've chosen it's way _wiser_ to install BSD and do needed config manually.

**Comment by fichtner** [comment]
It's true. We're not fond of the approach of how bridges are integrated. For that reason we do recommend hardware switches which do the job just nicely for very little money of need be.

However, in the scope of this ticket, what can we do to help make the system in place a bit less cumbersome?

**Comment by poige** [comment]
Nope, you can't replace bridges with anything external; such virtual bridges can be used as glue for VPNs and LAN interfaces and so on.

> what can we do to help make the system in place a bit less cumbersome?

What does original OS allow? It allows entering any interface name in PF rule set. And, BTW, that really does make sense cause not all interfaces exist all the time. Some of them can be sprung/ceased during uptime. So, at least this approach "don't narrow allowed choice scope" would help to mitigate  this and similar problems.

**Comment by fichtner** [comment]
What is your use case? I'm terribly sorry for not being able to follow.

**Comment by poige** [comment]
> I'm terribly sorry for not being able to follow.

That's exactly the thing! — Having hard coded values for option (interfaces choice in PF is an example) w/o giving users an ability to override them makes opnsense unable to follow.

**Comment by fichtner** [comment]
Wait, are you questioning the GUI + config.xml approach now? I thought we were talking about bridges?

**Comment by poige** [comment]
![image](https://user-images.githubusercontent.com/600779/34779256-3f4a1eee-f652-11e7-9e83-65790e5b5162.png)

**Comment by fichtner** [comment]
Ah, ok, we can't, because if we do that it won't be reproducible after config export + import.

**Comment by poige** [comment]
> I thought we were talking about bridges?

We _also_ did. As to my very case — it's combining 2 network Ethernet LAN segments into a single one: with VPN and bridging. But in fact I also mentioned it earlier:

![image](https://user-images.githubusercontent.com/600779/34779323-7052d08a-f652-11e7-96fb-1b2b7b8003c9.png)

**Comment by poige** [comment]
> Ah, ok, we can't, because if we do that it won't be reproducible after config export + import.

well, PF allows you to specify anything as NIC name. The rules with it just won't have any effect if it's non present at run time. But, well, ok, you can't. That's the thing why it's not wise to install opnsense instead of BSD. ;)

**Comment by fichtner** [comment]
The design goal is to not let the user edit raw files to provide verification and validation of the setup. It's not a console-based BSD, that's true.

It's also uncommon to "glue" VPNs as normally network segregation is a wanted security aspect.

**Comment by poige** [comment]
You're typical "we know better what users need". But in fact you're too lame to realize it

**Comment by poige** [comment]
> you're too lame to realize it

proof: https://www.softether.org/4-docs/1-manual/A._Examples_of_Building_VPN_Networks/10.5_Build_a_LAN-to-LAN_VPN_(Using_L2_Bridge)

**Comment by AdSchellevis** [comment]
@poige be polite please, if OPNsense doesn't fit your needs, feel free to use any other product available..

**Comment by fichtner** [comment]
Ok, can I help you with something else?

**Comment by poige** [comment]
I never meant to be polite to stupidity

**Comment by fichtner** [comment]
I guess that is a no then. :)


Cheers,
Franco

**Comment by poige** [comment]
>  if OPNsense doesn't fit your needs, feel free to use any other product available..

Sure. I made up my mind; I'm also letting others know what they would face if they would try using pfsense^W opnsense. — Its lame developers won't allow you to achieve full potential of original opensource software they've combined into this very ergh project.
