### ISSUE TITLE
dhcp failover not working

### ISSUE THREAD

**Issue by hudecof** [opnsense/core#2074]
Hi,

there is a BUG in DHCP fialower when using th HA.

# generated configuration
## primary
```
failover peer "dhcp_lan" {
  secondary;
  address 192.168.1.11;
  port 520;
  peer address 192.168.1.12;
  peer port 519;
  max-response-delay 10;
  max-unacked-updates 10;

  load balance max seconds 3;
}
```

## secondary
```
failover peer "dhcp_lan" {
  secondary;
  address 192.168.1.12;
  port 520;
  peer address 192.168.1.11;
  peer port 519;
  max-response-delay 10;
  max-unacked-updates 10;

  load balance max seconds 3;
}
```
## problem

there are wrong **port** and **peer port** values. On the slave it should be switched or ithe values should be the same.

**Comment by hudecof** [comment]
see https://kb.isc.org/article/AA-00502/0/A-Basic-Guide-to-Configuring-DHCP-Failover.html

**Comment by hudecof** [comment]
I miss, that both are 88secondaries88, so problem could be in code `./src/etc/inc/services.inc` calculatin `skew` or in my configuration.

**Comment by hudecof** [comment]
as readin the coide I found bug in my configuration. The **CRAP** interfaces had `/32` netmask. After chnage to `/24` it works as expected.

**Comment by hudecof** [comment]
so closing bug, it's not a bug

**Comment by fichtner** [comment]
@hudecof thanks for checking back so quickly! we're rolling out 18.1-RC1 in 2 hours, it's been busy so sorry for not responding earlier.

**Comment by hudecof** [comment]
@fichtner don't worry, but you should thing about code optimalization for such a use case. The dhcp service was not working, did not provide leases. ;(
