### ISSUE TITLE
qinq interface always down

### ISSUE THREAD

**Issue by tomarch** [opnsense/core#2078]
When setting a qinq member interface, this interface still show as down and no traffic pass.
QinQ parent (the first vlan) is show as up.

Pfsense has the same issue: https://redmine.pfsense.org/issues/7942

**Comment by AdSchellevis** [comment]
I probably need some documentation to fix this, the current code doesn't really seem to work and the documentation for QinQ with FreeBSD / ngctl is quite minimal.

If someone has a step by step guide how it should work, that would be very welcome.

**Comment by AdSchellevis** [comment]
we have chosen to remove the feature since it's unclear how to fix, https://github.com/opnsense/core/issues/2274
