### ISSUE TITLE
MVC: Common validator for model (IPv4/IPv6/FQDN)

### ISSUE THREAD

**Issue by mimugmail** [opnsense/core#2081]
Hi,

is it possible to write a validator to check for v4/v6/FQDN? 
I think this turns out very often, perhaps there's an easy way to realise this.

Thanks!

**Comment by AdSchellevis** [comment]
Hi Michael, 

You mean a combination of either ip address or fqdn? maybe we can extend one of the available validators (otherwise we can add a new one).

**Comment by fichtner** [comment]
I think this is more about validation options and/or text field templates trying to reduce and consolidate the custom regex usage

**Comment by mimugmail** [comment]
When I need a field type where I can set a v4, v6 or FQDN I have to use TextField and XY masks. Ether a new field type of a combined mask would be cool.

**Comment by AdSchellevis** [comment]
no problem, I'll try to add a combined one at the end of the week based on https://github.com/opnsense/core/blob/master/src/opnsense/mvc/app/models/OPNsense/Base/FieldTypes/NetworkField.php

**Comment by AdSchellevis** [comment]
It looks like we can validate hostnames using `filter_var(..., FILTER_VALIDATE_DOMAIN)`, so we should be able to add the combined validator with https://github.com/opnsense/core/commit/ec17d4cadb09ed638ac63c54f394c0bdd1b91ab4

For reference, the php doc for FILTER_VALIDATE_DOMAIN seems to missing, the implementation is here.
https://github.com/php/php-src/blob/a7fe2570d3ce6915d4ea85c62c0f880ddc225ba7/ext/filter/logical_filters.c#L461-L511

**Comment by mimugmail** [comment]
In production yet ..
