### ISSUE TITLE
ntpd crashes frequently

### ISSUE THREAD

**Issue by sauff** [opnsense/core#2086]
OPNsense 17.7.11, running on ESXi 6.0.
I have a little load on my ntpd (IPv4+6), between 0.5MBit/s and 2MBit/s.
The ntpd is crashing more or less frequently. The last crashes were:
- nov. 4th
- nov. 19th
- dec. 30th
- jan. 3rd
- jan. 9th
- jan. 11th
- jan. 12th
- jan. 13th

The log file always says:
Jan 13 15:36:10 | kernel: pid 36097 (ntpd), uid 0: exited on signal 11 (core dumped)

Can I somehow make it restart automatically? Or find out why it crashes?

**Comment by sauff** [comment]
The frequency of the ntpd crashes seems to increase, it crashed again on:
- jan. 16th
- jan. 19th
- jan. 20th

**Comment by fichtner** [comment]
It heavily depends on your setup. There is another ticket here: https://github.com/opnsense/core/issues/1785

You can also disable NTP and use the host sync option. For this you simply need to delete all name servers from its configuration.

**Comment by sauff** [comment]
The referenced ticket is about mlockall(), so some kind of memory allocation error. Here the error message ist different (see above, it doesn't say anything about mlockall()).

I don't see how disabling the NTP server could help here. The host sync option would only help to sync the time of OPNsense to the time of the ESXI host, but my OPNsense is providing the time to dozens of other machine on my network. If I disable the NTP server it doesn't serve the time anymore. This seems a little counterproductive. ;)

**Comment by sauff** [comment]
I had crashes every few days, from OPNsense 17.7 up until the last version of 18.1. Now after the upgrade to 18.7 it is suddenly stable. For 11 days I didn't have any ntpd crash - so probably the problem is fixed now.
