### ISSUE TITLE
menu or dhcp config page broken

### ISSUE THREAD

**Issue by fabianfrz** [opnsense/core#2087]
menu links to dhcp server config page without ?if=INTERFACE which then does an redirect to index.php.
It can be fixed by adding the parameter or maybe in the page by using the first interface.

**Comment by AdSchellevis** [comment]
is this when there are no dhcp servers available?

**Comment by fabianfrz** [comment]
It is on my dev VM where the DHCP server is running on two interfaces.

Release: OPNsense 17.7.11-amd64 FreeBSD 11.0-RELEASE-p17 LibreSSL 2.5.5

**Comment by AdSchellevis** [comment]
can you post a screenshot of the menu section? I don't appear to have the same on my end.

**Comment by fabianfrz** [comment]
![screenshot_20180113_221742](https://user-images.githubusercontent.com/3713914/34910164-93a1d374-f8af-11e7-8cd9-98133e36c5d4.png)

**Comment by fabianfrz** [comment]
looks like some things change between 18.1 and 17.7 which was the reason for this issue.

**Comment by fichtner** [comment]
Where do you get a plain "Server" link? They were removed consistently with what you describe. No interface = no more access. The page was never built for access without interfaces. It simply said "no static interfaces available" before.

**Comment by fichtner** [comment]
PS: The former is true for all branches, except stable/17.7 and therefore shouldn't be on 17.7.11

**Comment by fichtner** [comment]
Closing this, works on 17.7.11...

<img width="963" alt="screen shot 2018-01-14 at 9 30 32 am" src="https://user-images.githubusercontent.com/1915288/34914191-af505d4e-f90d-11e7-961c-d33f7e26135a.png">
