### ISSUE TITLE
openvpn - /usr/local/etc/rc.openvpn clients break after multiple reconfigurations

### ISSUE THREAD

**Issue by rootwyrm** [opnsense/core#2089]
Symptom:

Jan 13 17:16:11 | openvpn[45891]: Use --help for more information.
-- | --
Jan 13 17:16:11 | openvpn[45891]: Options error: You must define certificate file (--cert) or PKCS#12 file (--pkcs12)
Jan 13 17:16:11 | openvpn[45891]: disabling NCP mode (--ncp-disable) because not in P2MP client or server mode

This occurs even with a working configuration which has a peer certificate selected. Client is using username/password authentication, SSL/TLS. (ProtonVPN.) I was not able to reproduce on 17.7.11; only 18.1.r1. The configuration was previously working and did not produce this error message.

**Comment by fichtner** [comment]
It's 0ec330d you're missing. You can apply the patch with:

    # opnsense-patch 0ec330d

Thank you for testing 18.1!  :)


Cheers,
Franco
