### ISSUE TITLE
IPSec: NAT-T does not forward all traffic

### ISSUE THREAD

**Issue by fichtner** [opnsense/core#209]
IPSec over UDP works well, but NAT-T has problems with HTTP(s) even though other services like ICMP, RDP, SMB over TCP work fine. Problem exists in pfSense as well.

via https://forum.opnsense.org/index.php?topic=565.0

**Comment by fichtner** [comment]
@AdSchellevis maybe fixed recently?

**Comment by AdSchellevis** [comment]
@fichtner I don't know this issue, haven't looked into it. But if there's no real owner on our side, lets close it.

**Comment by fichtner** [comment]
keep it as help wanted :)
