### ISSUE TITLE
Link request docs in the beginners or API hello world

### ISSUE THREAD

**Issue by EugenMayer** [opnsense/core#2091]
Its intransparent where request comes from and it cannot be resolved by symbols if you do not already know the answer.

At least link https://olddocs.phalconphp.com/en/3.0.0/reference/request.html for that purpose, so one could lookup how getPost works

**Comment by fabianfrz** [comment]
@EugenMayer The current docs are here: https://docs.phalconphp.com/en/3.2/request and I do not know where I should link it. We cannot help you if you don't provide enough information.

**Comment by EugenMayer** [comment]
I do not need any help - its for anybody else running into the same issues. For me, i added phalconphp stubs into Intellij and resolved the symbols. If you consider that the default, close this issue. But i expect that not to be the case.

Understand the actions api will require to understand what request is. And that is never explained neither seems phalconphp to be ever linked as "the framework" used.

**Comment by fichtner** [comment]
docs are online if anyone wants to submit. not a core issue.

https://github.com/opnsense/docs
