### ISSUE TITLE
Widget controls not working correctly with touch screen input

### ISSUE THREAD

**Issue by NOYB** [opnsense/core#2092]
Chrome:
The title link and buttons work with touch input.  Though vertical position offset a little bit.  Have to touch slightly below them.
Drag and drop sorting doesn't work with touch input.
None of them work at all with active stylus input.

IE:
None of them work at all with touch.
Only drag and drop sorting works with stylus input.

Adding delay: 50, and distance: 2 options to the jquery sortable function gets the link and buttons to work with both touch and active stylus input.
Kind of a cursor grabbing action.

Adding "touch-action: none" css to the sort handle header element gets the drag and drop sorting working with touch input.

I'll make a commit for these changes which fixes this for IE.  But Chrome is still not working.

A bit surprised that if this is not working in Chrome it hasn't been reported.  So maybe it's just my Chrome environment that is not working properly.  Can someone confirm that the widget title link, settings, minimize, and remove buttons all work as well as drag and drop sorting works with touch screen input?

**Comment by NOYB** [comment]
Added a modification that works with both Android and Desktop Chrome.
https://github.com/opnsense/core/pull/2137

So nice to have touch access to the widget settings.

**Comment by fichtner** [comment]
Submitted and subsequently released into 18.1.x
