### ISSUE TITLE
"VLAN Hardware Filtering" is drop-down but description says it can be checked

### ISSUE THREAD

**Issue by C-Duv** [opnsense/core#2094]
The description for setting *VLAN Hardware Filtering* (in *Interfaces: Settings*) says "*Checking this option ...*" while the *VLAN Hardware Filtering* is using a drop-down menu with the following possible values:
* *Enable VLAN Hardware Filtering*
* *Disable VLAN Hardware Filtering*
* *Leave default*

I guess the setting was a checkbox once and was later converted into a drop-down when the *Leave default* arrived but the description was not updated.

Steps:
* Open GUI
* Go to: *Interfaces: Settings* (`/system_advanced_network.php`)
* Display setting description for the "*VLAN Hardware Filtering*" (by clicking on the *(i)* icon or the "*full help*" toggle button).

Actual description is:
*Checking this option will disable VLAN hardware filtering. This offloading is broken in some hardware drivers, and may impact performance with some specific NICs.*

Expected description (something like):
*Enabling this option will disable VLAN hardware filtering. This offloading is broken in some hardware drivers, and may impact performance with some specific NICs.*

OPNsense version: 18.1.r2
GUI URL: `/system_advanced_network.php`

**Comment by fichtner** [comment]
Slightly different version committed. Thank you. ❤️

**Comment by C-Duv** [comment]
You're welcome.
