### ISSUE TITLE
Make it obvious that a new cronjob needs to be applied

### ISSUE THREAD

**Issue by Kimmax** [opnsense/core#2101]
Adding a new cronjob via System -> Settings -> Cron does not automagically write it to crontab. This behavior could be miss-leading, since the button on the "Add pane" says "Save Changes".
We should either apply the changed cronjob immediately or make it really obvious that changed / new cronjobs need to be applied using the "Apply" button. Right now it looks like the button serves a reload or should be used when changing  the "Enabled" checkbox

**Comment by Kimmax** [comment]
> 12:29 <TotallyNotKim> how about we pull in the "Configuration changed" notification from the fw?
> 12:30 <TotallyNotKim> The cronjob configuration has been changed.
> 12:30 <TotallyNotKim> You must apply the changes in order for them to take effect.
> 12:30 <TotallyNotKim> with the apply button right next to it
> 12:30 <fitch> there is no unified implementation of that, which means we need to clutter every MVC page
> 12:31 <fitch> we could show in JS maybe, but the state then is not persistent if you reload the page
> 12:32 <TotallyNotKim> adding that the apply button is necessary on the page as description or something should do the job for starters

**Comment by monreal** [comment]
Thanks... I ran into this myself today and never noticed the apply button :(
