### ISSUE TITLE
After upgrade from 17.7.11 to 18.1.rc2 alias tables are not applied correctly

### ISSUE THREAD

**Issue by jschellevis** [opnsense/core#2102]
After upgrade from 17.7.11 to 18.1.rc2 alias tables are not applied correctly

To reproduce:

1) Start with clean install of 17.7.11 
2) and create an alias table (IP's or Networks).
3) Add a rule using the alias (just for reference) and check under Firewall->Diagnostics->pfTables if the new IP or Network table is listed (port aliases work differently, this issue does not apply to those).

4) Upgrade to 18.1.rc2
5) After upgrade you will find the alias table listed under /var/db/aliastables/
     The rules under /tmp/rules.debug are correct and include the file reference for the alias table.
     However the pfTables are not filled (check under Firewall->Diagnostics->pfTables).

6) Now run `configctl filter refresh_aliases` and the pfTables are filled with correct data.

**Comment by fichtner** [comment]
@jschellevis please test with these two patches:

    # opnsense-patch bba40c97 947718b

**Comment by jschellevis** [comment]
@franco thanks! that resolves the issue completely.
