### ISSUE TITLE
Minor: do not open openvpn client in same window

### ISSUE THREAD

**Issue by EugenMayer** [opnsense/core#2103]
When clicking on any of those clients, it loads in the same window. Should be _blank rather

![image](https://user-images.githubusercontent.com/136934/35049702-31edbe78-fba1-11e7-8560-ee237de1f301.png)

**Comment by fabianfrz** [comment]
Created a fix for your issue.

**Comment by fichtner** [comment]
Fixed in 18.1.1. Thanks!
