### ISSUE TITLE
Firewall logs widget double updating

### ISSUE THREAD

**Issue by NOYB** [opnsense/core#2104]
Document ready is fired twice when dashboard loads.  Because of this the firewall logs widget double schedules updating (doubles up the setTimeout calls).  Consuming double the resources.

**Comment by fichtner** [comment]
If you want this ticket assigned please let me know.

**Comment by NOYB** [comment]
Yes it needs to be assigned to someone.

I have a dirty work around (global var flag to prevent fetch log from being called again, and also for extra precaution clear timeout before setting another one) but thought Ad or someone might have a better/cleaner solution.

**Comment by AdSchellevis** [comment]
This seems to impact the other widgets as well.  Likely some javascript/jQuery is manipulating the dom resulting in this behaviour, although I can't find the exact cause very easily. 

The most simple solution for now seems to be replacing the ready events with `$(window).load()` for the widgets. I will commit a fix and close this issue and the corresponding PR. 

@NOYB thanks for reporting.
