### ISSUE TITLE
PC Engines APU* LED support

### ISSUE THREAD

**Issue by ktk** [opnsense/core#2114]
Unless I missed something it looks like OPNsense does not include default support for onboard LEDs on [PC Engines APU*](http://pcengines.ch/apu2.htm) boards.

It looks like there is a kernel module available for them called [apuled](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=189772). According to the FreeBSD issue it supports APU1, APU2 and APU3.

Would be great if this could be shipped/included in the default configuration for serial builds so one can enable it. On ALIX boards/pfsense a popular package was [BlinkLED](https://doc.pfsense.org/index.php/BlinkLED_Package), which would probably easy to re-implement once I have the LEDs available.

Thanks for the awesome work!

**Comment by fichtner** [comment]
Hi @ktk,

The led driver nodes should be there for your APU already...

    # ls /dev/led/led*

And it is easy to operate via shell script:

https://www.freebsd.org/cgi/man.cgi?query=led&sektion=4


Cheers,
Franco

**Comment by ktk** [comment]
@fichtner oh great didn't realize that thanks! Will update the posts in the forum accordingly. Also I will try to see if I can port BlinkLED! Will report here as well for reference.

**Comment by fichtner** [comment]
Best way of integrating would be to rewrite the management parts in the MVC framework. That would automatically provide an API for future use... :)

https://docs.opnsense.org/development/examples/helloworld.html

**Comment by ktk** [comment]
@fichtner tnx will check that out!

**Comment by ktk** [comment]
@fichtner just checked on 17.7, I only see:

```
ls /dev/led/*
/dev/led/igb0   /dev/led/igb1   /dev/led/igb2
```

**Comment by fichtner** [comment]
I don't think the drivers disappeared, but seeing igb* maybe the new APU leds are not found... I have to check on Monday on an old APU1 to see if they are available there, ok?

**Comment by ktk** [comment]
@fichtner sure thanks!

**Comment by fichtner** [comment]
please ping me when I'm slacking off :)

**Comment by fabianfrz** [comment]
Also having an APU1 board so I can check for /dev/led as well

**Comment by fabianfrz** [comment]
there is no led on APU1d4:

```
root@opn:~ # ls /dev/*
/dev/acpi       /dev/ctty       /dev/da0s1      /dev/geom.ctl   /dev/mem        /dev/random     /dev/ttyu0.init /dev/ufssuspend /dev/ugen6.2
/dev/apm        /dev/cuau0      /dev/da0s1a     /dev/hpet0      /dev/midistat   /dev/sndstat    /dev/ttyu0.lock /dev/ugen0.1    /dev/urandom
/dev/apmctl     /dev/cuau0.init /dev/da0s1b     /dev/io         /dev/netmap     /dev/speaker    /dev/ttyu1      /dev/ugen1.1    /dev/usbctl
/dev/audit      /dev/cuau0.lock /dev/devctl     /dev/kbd0       /dev/nfslock    /dev/stderr     /dev/ttyu1.init /dev/ugen2.1    /dev/xpt0
/dev/auditpipe  /dev/cuau1      /dev/devctl2    /dev/kbdmux0    /dev/null       /dev/stdin      /dev/ttyu1.lock /dev/ugen3.1    /dev/zero
/dev/bpf        /dev/cuau1.init /dev/devstat    /dev/klog       /dev/pass0      /dev/stdout     /dev/tun1       /dev/ugen4.1
/dev/bpf0       /dev/cuau1.lock /dev/fido       /dev/kmem       /dev/pci        /dev/sysmouse   /dev/tun2       /dev/ugen5.1
/dev/console    /dev/da0        /dev/full       /dev/mdctl      /dev/pf         /dev/ttyu0      /dev/tun3       /dev/ugen6.1

/dev/fd:
0       1       2

/dev/pts:
0

/dev/reroot:
reroot

/dev/usb:
0.1.0   0.1.1   1.1.0   1.1.1   2.1.0   2.1.1   3.1.0   3.1.1   4.1.0   4.1.1   5.1.0   5.1.1   6.1.0   6.1.1   6.2.0   6.2.1   6.2.2
```

**Comment by fichtner** [comment]
Same issue here... so that is really an issue with all APUs.... I'll take a look at the apuled integration.

**Comment by seamusdemora** [comment]
Here's what worked for me on the APU.2C2 via the serial port: 

After login, go to the shell (8), then: 
```
root@OPNsense:~ # ls /dev/led
igb0    igb1    igb2
root@OPNsense:~ # echo f3 > /dev/led/igb0 
```
blinks the LED for igb0. To turn it off:
`echo 0 > /dev/led/igb0`

**Comment by ktk** [comment]
@seamusdemora interesting, on what version are you?

**Comment by evbevz** [comment]
Hi all, we have support for PC Engine APU leds and hidden front button control.
One patch to src, one additional port and one patch into core.
Configurable blinking schemes and ability to bind shell script to button action (we use it for reset config to factory defaults).
Alex can describe in details.

**Comment by alexpro** [comment]
Patch to src:
It's a Larry's Baird driver for onboard LEDs and button, module name - apuled.ko
I got it [here](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=189772)
Upon loading the driver creates four devices.  Three led devices:    
    /dev/led/led1                                                               
    /dev/led/led2                                                 
    /dev/led/led3                                       
One for the mode switch:
    /dev/modesw

Additional port:
It's a very simple daemon which can light or quench LEDs. Also, it tracks onboard button state and can invoke action script when button pressed. LEDs can be light up by configurable schemes which can be switched.

Patch into core:
We created syshook for 'boot' runlevel which run above daemon when rc starts, before mounting filesystems rw. After rc runs, LEDs blinking according 'startup' scheme until rc finishes. Once OPNsense boot completed, blink scheme swithced to 'running'. When reboot initiated, scheme switches to 'running' again. When button pressed, blink scheme switched to scheme 'press'.

You can see how it really works on this [video](http://194.0.206.11/apu2/video_2018-09-07_21-17-28.mp4)

**Comment by alexpro** [comment]
And in addition about daemon:
If apuled.ko module doesn't loaded or if OPNsense running not on APU device, daemon exits immediately, so placing it in syshook doesn't make useless processes.

**Comment by seamusdemora** [comment]
@ktk: I was on 18.1 when I checked this; I've since upgraded to 18.7. Have not checked to see if it still works. I'm afraid I'm completely unclear what's going on with @alexpro's comment. I seem to recall I found this in an OpenBSD man page...

**Comment by seamusdemora** [comment]
Ah! So sorry... my APU faces me  connector-forward... I forget that there are actually other LEDs on the other side :P

**Comment by evbevz** [comment]
If our solution is suitable for opnsense mainstream, we can make pull-request.

**Comment by ktk** [comment]
@evbevz video looks great to me. Not sure about how to proceed to get this into mainstream. @fichtner you might comment on that?

**Comment by fichtner** [comment]
Errr... src.git support and publishing a plugin I guess. We've removed the original LED implementation in core because it wasn't essential, only tailored for APU/WRAP? and wasn't flexible either.

**Comment by ktk** [comment]
@alexpro & @evbevz would that be possible to create for you? Would be great, I think APU is pretty popular among OPNsense users.

**Comment by evbevz** [comment]
@ktk , no problem, if @fichtner  allows pull-request to kernel and core.

**Comment by soder10** [comment]
Is there a chance this LED support will arrive into 18.7, instead of 19.1?

**Comment by sachaz** [comment]
interested too ;)

**Comment by fichtner** [comment]
Imported kernel module via https://github.com/opnsense/src/commit/8ba72fd13491a6a0150c9a2235bb93da2d3bd1e6 for inclusion in OPNsense 19.1. Considering a backport to 18.7 when it works as expected...

**Comment by soder10** [comment]
Sorry for my dumb question: do I need to switch to "beta" release channel, to be able to try this feature?

**Comment by evbevz** [comment]
@soder10, no, those pull-requests doesn't merged yet.

**Comment by soder10** [comment]
Ok, I am waiting patiently for 19.1 then :)
Just please make sure APU2/3 model number is not hardcoded, as ALU4 and 5 is also available (at least APU4 is for sure using the exact same board as APU2/3 only added +1 more NIC, so the 3x LED and 1 SWITCH should be the same)

**Comment by ktk** [comment]
I'm still on 18.x, did the support for the LEDs make it into 19.1?

**Comment by fichtner** [comment]
The driver did, yes.

**Comment by ktk** [comment]
Excellent, thanks! Will check it out and see if I can contribute a plugin.

**Comment by wschlich** [comment]
On my APU4C4 I can see the following LED devices running OPNsense 19.1:
/dev/led/igb0
/dev/led/igb1
/dev/led/igb2
/dev/led/igb3
These LEDs are the green link/activity LEDs of the 4 onboard LAN interfaces at the rear.
The APU has 3 additional status LEDs at the front.
Using 'kldload apuled' yields in the following additional devices:
/dev/led/led1
/dev/led/led2
/dev/led/led3
Nice, thanks!

**Comment by soder10** [comment]
Important note: you need to load the kernel driver named "apuled" after every reboot, as its not automatically loaded. Hand editing /boot/loader.conf is not the way it should be done, as that file is overwritten every single time a GUI-driven config change is saved.
Is there a way to add this "Load APU LED" into the System \ Settings \ Misc section, or do we need to add this under Settings \ TUNABLE : apuled_load = "YES" ?

**Comment by fichtner** [comment]
why not create a ticket for the plugin? if you already use the plugin? it's in development mode...

**Comment by soder10** [comment]
@fichtner Oh well, I wasnt really aware that the plugin is in progress :)
Just wanted to give some warning to any random users, that the device driver load via manual is an ephemeral solution unless comitted via a permanent solution.

**Comment by kosli** [comment]
Is the (front) LED functionality still in the current version of OPNsense?
I have installed the latest OPNsense (20.1.3) on my apu2e4 and the apuled kernel module is loaded, but there are NO /dev/led/led* devices. Any idea what could be wrong?

**Comment by soder10** [comment]
@kosli There is a problem with this LED module driver since APU firmware 4.10.x -> check the description amd possible workaround here:

https://pcengines.github.io/
and
https://github.com/pcengines/coreboot/issues/329
apuled driver doesn't work in FreeBSD. Check the GPIOs document for workaround.

**Comment by kosli** [comment]
@soder10 thank you very much! I didn't expect that it was a bios upgrade (that I did only after installing OPNsense for the first time on that board) that made problems. I have added the loadef.conf.local setting and now the LEDs work fine. (Haven't tried downgrading the bios).

**Comment by tbussmann** [comment]
I'm using OPNSense 25.1.3 on a PC Engines APU6.

Despite having applied the [trick](https://github.com/pcengines/apu2-documentation/blob/master/docs/gpios.md#known-issues) of adding a tunable `debug.acpi.avoid` with value `\_SB_.PCI0.GPIO` to solve the conflict with ACPI, the LED devices at `/dev/led*` are not created, neither automatically nor after `kldload apuled`. The three LEDs are always on/off/off.

Further investigation of the `apuled` module reveals it is supporting LEDs on the PC-Engines [apu](https://pcengines.ch/apu.htm) and [apu2](https://pcengines.ch/apu2.htm) platform. On the apu2 platform there are variants apu2, apu3 and apu4 known and supported by the same code. Unfortunately, the last addition to that platform apu6 is not yet handled. APU6 is not well documented, but judging from a comparison of the schematics ([apu6](https://pcengines.ch/schema/apu6b.pdf), [apu4](https://pcengines.ch/schema/apu4d.pdf) Page 7) and documentation with [apu4](https://pcengines.ch/pdf/apu4.pdf) (Page 11), the LEDs are still at the same pins G57, G58, G59. I'm also able to directly address the LEDs using the same GPIO pins listed in the driver 68, 69, 70: `kldload amdgpio; gpioctl -t -p 69`.

For this reason, the I'd expect a minimal code change to identify apu6 would solve it. Unfortunately, I don't have a development system where I can build and test this.

Further details:
<details>
<summary> dmidecode </summary>

```
$ sudo dmidecode -t system
# dmidecode 3.6
Scanning /dev/mem for entry point.
SMBIOS 3.0.0 present.

Handle 0x0001, DMI type 1, 27 bytes
System Information
	Manufacturer: PC Engines
	Product Name: apu6
	Version: 1.0
	Serial Number: 1595115
	UUID: Not Settable
	Wake-up Type: Reserved
	SKU Number: 4 GB
	Family: Not Specified

Handle 0x0008, DMI type 32, 11 bytes
System Boot Information
	Status: No errors detected

$ sudo dmidecode -t bios 
# dmidecode 3.6
Scanning /dev/mem for entry point.
SMBIOS 3.0.0 present.

Handle 0x0000, DMI type 0, 26 bytes
BIOS Information
	Vendor: coreboot
	Version: v4.19.0.1
	Release Date: 01/31/2023
	ROM Size: 8 MB
	Characteristics:
		PCI is supported
		PC Card (PCMCIA) is supported
		BIOS is upgradeable
		Selectable boot is supported
		ACPI is supported
		Targeted content distribution is supported
	BIOS Revision: 0.0
	Firmware Revision: 0.0
```
</details>

<details>
<summary> acpidump (excerpt) </summary>
same with `debug.acpi.avoid` set or not

```
$ acpidump -dt
[...]
    Scope (_SB.PCI0)
    {
        Device (LEDS)
        {
            Name (_HID, "PRP0001")  // _HID: Hardware ID
            Name (_CRS, ResourceTemplate ()  // _CRS: Current Resource Settings
            {
                GpioIo (Exclusive, PullUp, 0x0000, 0x0000, IoRestrictionOutputOnly,
                    "\\_SB.PCI0.GPIO", 0x00, ResourceConsumer, ,
                    )
                    {   // Pin list
                        0x0044,
                        0x0045,
                        0x0046
                    }
            })
            Name (_DSD, Package (0x02)  // _DSD: Device-Specific Data
            {
                ToUUID ("daffd814-6eba-4d8c-8a91-bc9bbf4aa301") /* Device Properties for _DSD */, 
                Package (0x01)
                {
                    Package (0x02)
                    {
                        "compatible", 
                        "gpio-leds"
                    }
                }
            })
            Device (LED1)
            {
                Name (_HID, "PRP0001")  // _HID: Hardware ID
                Name (_DSD, Package (0x02)  // _DSD: Device-Specific Data
                {
                    ToUUID ("daffd814-6eba-4d8c-8a91-bc9bbf4aa301") /* Device Properties for _DSD */, 
                    Package (0x03)
                    {
                        Package (0x02)
                        {
                            "label", 
                            "apu6:green:led1"
                        }, 

                        Package (0x02)
                        {
                            "gpios", 
                            Package (0x04)
                            {
                                LEDS, 
                                Zero, 
                                Zero, 
                                One
                            }
                        }, 

                        Package (0x02)
                        {
                            "default-state", 
                            "on"
                        }
                    }
                })
            }

            Device (LED2)
            {
                Name (_HID, "PRP0001")  // _HID: Hardware ID
                Name (_DSD, Package (0x02)  // _DSD: Device-Specific Data
                {
                    ToUUID ("daffd814-6eba-4d8c-8a91-bc9bbf4aa301") /* Device Properties for _DSD */, 
                    Package (0x03)
                    {
                        Package (0x02)
                        {
                            "label", 
                            "apu6:green:led2"
                        }, 

                        Package (0x02)
                        {
                            "gpios", 
                            Package (0x04)
                            {
                                LEDS, 
                                Zero, 
                                One, 
                                One
                            }
                        }, 

                        Package (0x02)
                        {
                            "default-state", 
                            "off"
                        }
                    }
                })
            }

            Device (LED3)
            {
                Name (_HID, "PRP0001")  // _HID: Hardware ID
                Name (_DSD, Package (0x02)  // _DSD: Device-Specific Data
                {
                    ToUUID ("daffd814-6eba-4d8c-8a91-bc9bbf4aa301") /* Device Properties for _DSD */, 
                    Package (0x03)
                    {
                        Package (0x02)
                        {
                            "label", 
                            "apu6:green:led3"
                        }, 

                        Package (0x02)
                        {
                            "gpios", 
                            Package (0x04)
                            {
                                LEDS, 
                                Zero, 
                                0x02, 
                                One
                            }
                        }, 

                        Package (0x02)
                        {
                            "linux,default-trigger", 
                            "heartbeat"
                        }
                    }
                })
            }
        }
    }
[...]
```
</details>

<details>
<summary> gpioctl (shortended)</summary>
only possible if `debug.acpi.avoid` is not set

```
$ sudo gpioctl -l
pin 00:	1	AMDGPIO0_PIN_0<IN>
pin 01:	1	AMDGPIO0_PIN_1<IN>
pin 02:	1	AMDGPIO0_PIN_2<IN>
pin 03:	0	AMDGPIO0_PIN_3<IN>
pin 04:	0	AMDGPIO0_PIN_4<IN>
pin 05:	0	AMDGPIO0_PIN_5<IN>
pin 06:	1	AMDGPIO0_PIN_6<IN>
pin 07:	1	AMDGPIO0_PIN_7<IN>
pin 08:	1	AMDGPIO0_PIN_8<IN>
pin 09:	1	AMDGPIO0_PIN_9<IN>
pin 10:	0	AMDGPIO0_PIN_10<IN>
pin 11:	1	AMDGPIO0_PIN_11<IN>
pin 12:	0	AMDGPIO0_PIN_12<IN>
pin 13:	1	AMDGPIO0_PIN_13<IN>
pin 14:	1	AMDGPIO0_PIN_14<IN>
pin 15:	1	AMDGPIO0_PIN_15<IN>
pin 16:	1	AMDGPIO0_PIN_16<IN>
pin 17:	1	AMDGPIO0_PIN_17<IN>
pin 18:	1	AMDGPIO0_PIN_18<IN>
pin 19:	1	AMDGPIO0_PIN_19<IN>
pin 20:	1	AMDGPIO0_PIN_20<IN>
pin 21:	-1	<>
pin 22:	-1	<>
pin 23:	1	AMDGPIO0_PIN_23<IN>
pin 24:	1	AMDGPIO0_PIN_24<IN>
pin 25:	0	AMDGPIO0_PIN_25<IN>
pin 26:	0	AMDGPIO0_PIN_26<IN>
pin 27:	-1	<>
pin 28:	-1	<>
pin 29:	-1	<>
pin 30:	-1	<>
pin 31:	-1	<>
pin 32:	-1	<>
pin 33:	-1	<>
pin 34:	-1	<>
pin 35:	-1	<>
pin 36:	-1	<>
pin 37:	-1	<>
pin 38:	-1	<>
pin 39:	0	AMDGPIO0_PIN_39<IN>
pin 40:	0	AMDGPIO0_PIN_40<IN>
pin 41:	-1	<>
pin 42:	-1	<>
pin 43:	0	AMDGPIO0_PIN_43<IN>
pin 44:	-1	<>
pin 45:	-1	<>
pin 46:	1	AMDGPIO0_PIN_46<IN>
pin 47:	0	AMDGPIO0_PIN_47<IN>
pin 48:	0	AMDGPIO0_PIN_48<IN>
pin 49:	0	AMDGPIO0_PIN_49<IN>
pin 50:	0	AMDGPIO0_PIN_50<IN>
pin 51:	0	AMDGPIO0_PIN_51<IN>
pin 52:	0	AMDGPIO0_PIN_52<IN>
pin 53:	0	AMDGPIO0_PIN_53<IN>
pin 54:	0	AMDGPIO0_PIN_54<IN>
pin 55:	0	AMDGPIO0_PIN_55<IN>
pin 56:	0	AMDGPIO0_PIN_56<IN>
pin 57:	0	AMDGPIO0_PIN_57<IN>
pin 58:	0	AMDGPIO0_PIN_58<IN>
pin 59:	0	AMDGPIO0_PIN_59<IN>
pin 60:	1	AMDGPIO0_PIN_60<IN>
pin 61:	0	AMDGPIO0_PIN_61<IN>
pin 62:	0	AMDGPIO0_PIN_62<IN>
pin 63:	-1	<>
pin 64:	1	AMDGPIO1_PIN_64<IN>
pin 65:	0	AMDGPIO1_PIN_65<IN>
pin 66:	1	AMDGPIO1_PIN_66<OUT>
pin 67:	-1	<>
pin 68:	0	AMDGPIO1_PIN_68<OUT>
pin 69:	1	AMDGPIO1_PIN_69<OUT>
pin 70:	1	AMDGPIO1_PIN_70<OUT>
pin 71:	1	AMDGPIO1_PIN_71<OUT>
pin 72:	1	AMDGPIO1_PIN_72<OUT>
pin 73:	-1	<>
pin 74:	0	AMDGPIO1_PIN_74<IN>
pin 75:	0	AMDGPIO1_PIN_75<IN>
pin 76:	0	AMDGPIO1_PIN_76<IN>
pin 77:	-1	<>
pin 78:	-1	<>
pin 79:	-1	<>
pin 80:	-1	<>
pin 81:	-1	<>
pin 82:	-1	<>
pin 83:	-1	<>
pin 84:	1	AMDGPIO1_PIN_84<IN>
pin 85:	1	AMDGPIO1_PIN_85<IN>
pin 86:	0	AMDGPIO1_PIN_86<IN>
pin 87:	1	AMDGPIO1_PIN_87<IN>
pin 88:	0	AMDGPIO1_PIN_88<IN>
pin 89:	1	AMDGPIO1_PIN_89<IN>
pin 90:	0	AMDGPIO1_PIN_90<IN>
pin 91:	0	AMDGPIO1_PIN_91<IN>
pin 92:	0	AMDGPIO1_PIN_92<IN>
pin 93:	0	AMDGPIO1_PIN_93<IN>
pin 94:	-1	<>
pin 95:	1	AMDGPIO1_PIN_95<IN>
pin 96:	1	AMDGPIO1_PIN_96<IN>
pin 97:	1	AMDGPIO1_PIN_97<IN>
pin 98:	1	AMDGPIO1_PIN_98<IN>
pin 99:	1	AMDGPIO1_PIN_99<IN>
pin 100:	1	AMDGPIO1_PIN_100<IN>
pin 101:	0	AMDGPIO1_PIN_101<IN>
pin 102:	0	AMDGPIO1_PIN_102<IN>
pin 103:	-1	<>
pin 104:	-1	<>
pin 105:	-1	<>
pin 106:	-1	<>
pin 107:	-1	<>
pin 108:	-1	<>
pin 109:	-1	<>
pin 110:	-1	<>
pin 111:	-1	<>
pin 112:	-1	<>
pin 113:	1	AMDGPIO1_PIN_113<IN>
pin 114:	1	AMDGPIO1_PIN_114<IN>
pin 115:	0	AMDGPIO1_PIN_115<IN>
pin 116:	0	AMDGPIO1_PIN_116<IN>
pin 117:	0	AMDGPIO1_PIN_117<IN>
pin 118:	0	AMDGPIO1_PIN_118<IN>
pin 119:	0	AMDGPIO1_PIN_119<IN>
pin 120:	0	AMDGPIO1_PIN_120<IN>
pin 121:	0	AMDGPIO1_PIN_121<IN>
pin 122:	0	AMDGPIO1_PIN_122<IN>
pin 123:	-1	<>
pin 124:	-1	<>
pin 125:	-1	<>
pin 126:	1	AMDGPIO1_PIN_126<IN>
pin 127:	-1	<>
pin 128:	-1	<>
pin 129:	1	AMDGPIO2_PIN_129<IN>
pin 130:	1	AMDGPIO2_PIN_130<IN>
pin 131:	1	AMDGPIO2_PIN_131<IN>
pin 132:	0	AMDGPIO2_PIN_132<IN>
pin 133:	0	AMDGPIO2_PIN_133<IN>
pin 134:	-1	<>
pin 135:	0	AMDGPIO2_PIN_135<IN>
pin 136:	0	AMDGPIO2_PIN_136<IN>
pin 137:	0	AMDGPIO2_PIN_137<IN>
pin 138:	0	AMDGPIO2_PIN_138<IN>
pin 139:	0	AMDGPIO2_PIN_139<IN>
pin 140:	0	AMDGPIO2_PIN_140<IN>
pin 141:	0	AMDGPIO2_PIN_141<IN>
pin 142:	0	AMDGPIO2_PIN_142<IN>
pin 143:	0	AMDGPIO2_PIN_143<IN>
pin 144:	0	AMDGPIO2_PIN_144<IN>
pin 145:	0	AMDGPIO2_PIN_145<IN>
pin 146:	0	AMDGPIO2_PIN_146<IN>
pin 147:	0	AMDGPIO2_PIN_147<IN>
pin 148:	0	AMDGPIO2_PIN_148<IN>
pin 149:	-1	<>
pin 150:	-1	<>
pin 151:	-1	<>
pin 152:	-1	<>
pin 153:	-1	<>
pin 154:	-1	<>
pin 155:	-1	<>
pin 156:	-1	<>
pin 157:	-1	<>
pin 158:	-1	<>
pin 159:	-1	<>
pin 160:	-1	<>
pin 161:	-1	<>
pin 162:	-1	<>
pin 163:	-1	<>
pin 164:	-1	<>
pin 165:	-1	<>
pin 166:	0	AMDGPIO2_PIN_166<IN>
pin 167:	0	AMDGPIO2_PIN_167<IN>
pin 168:	0	AMDGPIO2_PIN_168<IN>
pin 169:	0	AMDGPIO2_PIN_169<IN>
pin 170:	0	AMDGPIO2_PIN_170<IN>
pin 171:	0	AMDGPIO2_PIN_171<IN>
pin 172:	0	AMDGPIO2_PIN_172<IN>
pin 173:	0	AMDGPIO2_PIN_173<IN>
pin 174:	0	AMDGPIO2_PIN_174<IN>
pin 175:	0	AMDGPIO2_PIN_175<IN>
pin 176:	0	AMDGPIO2_PIN_176<IN>
pin 177:	1	AMDGPIO2_PIN_177<IN>
pin 178:	-1	<>
pin 179:	-1	<>
pin 180:	-1	<>
[...]
pin 254:	-1	<>
pin 255:	-1	<>
```
</details>
