### ISSUE TITLE
.local domain doesn’t work

### ISSUE THREAD

**Issue by fbruetting** [opnsense/core#2117]
[18.1rc2]
If I specify OPNsense to use `local` as it’s domain name in the general system settings, that doesn’t work and I have to enter `http://opnsense` with the prefix in Firefox – instead of being able to use `opnsense.local` (what is more convenient). When I change the domain to `local1`, everything works fine and as expected.

I don’t know why there is the remark, that `local` shouldn’t be used as the domain name, as about every system defaults to that for years…? But still, that should be an advise and not be forced (if the bug is due to that setting).

**Comment by NOYB** [comment]
.local
https://en.wikipedia.org/wiki/.local

**Comment by fichtner** [comment]
I'm using this because living on the edge is cool... Also note the help text specifically saying "local" should not be used. ;)

<img width="1125" alt="screen shot 2018-01-21 at 9 28 52 am" src="https://user-images.githubusercontent.com/1915288/35192197-a264482c-fe8d-11e7-8dd3-14f4eca01809.png">
