### ISSUE TITLE
Startup beep runs too late

### ISSUE THREAD

**Issue by fbruetting** [opnsense/core#2118]
[18.1rc2]

When I restart my OPNsense machine, I recognize that it works again after some time, as my internet radio starts to play again. But it takes about half a minute afterwards for the startup beep to appear.

**Comment by fichtner** [comment]
Hi @fbruetting,

The beep is the last thing the boot sequence does to indicate it finished ok. It is not an indicator of connectivity and its timing heavily depends on the plugins that you use and how fast your hardware goes through the boot sequence.


Cheers,
Franco

**Comment by fbruetting** [comment]
Yeah ok, but half a minute seems like too much (at least to me). I have just acme and arp-scan plugins and not much configured – just Unbound and basic firewalling. So I’m concerned if something doesn’t work right.

**Comment by fichtner** [comment]
You could post the system log of your boot sequence for inspection, but I'm sure it's just the way it is.

**Comment by fichtner** [comment]
PS: The delays are often in the setup details, e.g. GeoIP alias takes a long time to fetch during boot. I can say for sure the beep = system started ok and if you use the factory reset that happens in a very short amount of time.

**Comment by fichtner** [comment]
@fbruetting 

During image testing I still feel this is how it should be: beeps when login on the console is possible / has not crashed during boot. On shutdown / reboot it's the first thing that happens to know that the box is responding to the request.

FWIW, I see potential for doing a partial early "beep" and "beep beep" for different stages in the boot process to indicate progress more clearly?

**Comment by fbruetting** [comment]
Whatever FWIW means…
It’s not that I need the beep for knowing that the box is ready – although that will be nice. It’s rather that I couldn’t (and can’t) understand that half minute delay, because my box really doesn’t do anything other than basic functionality. But I currently had no time for looking into that.

**Comment by fichtner** [comment]
Ok, take your time. We can leave this open for a couple of weeks. :)


Cheers,
Franco
