### ISSUE TITLE
Setting DHCP for LAN interface is not allowed from wizard.php

### ISSUE THREAD

**Issue by gitmod** [opnsense/core#212]
I'm trying to set dhcp for LAN interface with the keyword 'dhcp' but a window alert explain that only ip address is allowed

![dhcp](https://cloud.githubusercontent.com/assets/2040775/8144053/6e68f980-11ca-11e5-9591-aac750c315ac.png)

**Comment by fichtner** [comment]
The message dates back to 2004, but there is no code to handle this case (and even the verification doesn't understand 'dhcp'), so the message was simply removed to fix the behaviour.
