### ISSUE TITLE
DynDNS provider Route53 v6 not working

### ISSUE THREAD

**Issue by theq86** [opnsense/core#2122]
When trying to update the IPv6 address on Amazon Route53 I always get the following error:

opnsense: /services_dyndns_edit.php: Route53::listResourceRecordSets(): Sender - AccessDenied: User: arn:aws:iam::575452484744:user/dyndns is not authorized to perform: GetHostedZone on resource: arn:aws:route53:::hostedzone/rrset Request Id: 11250012-ffaa-11e7-9c69-1deaea571495

This is somehow impossible, since the user has the policies: AmazonRoute53DomainsFullAccess, AmazonRoute53AutoNamingFullAccess, AmazonRoute53FullAccess.

edit: PLUS, you cannot set a Hosted Zone ID in the config for Route53 v6. This option is missing in the GUI. Without it, how does it know which Hosted Zone to update? In the v4 settings this option is available. Maybe this has to be added to v6 as well to make it work.

On IPv4 it works well. I'm using the same account and aws credentials for both IPv4 and IPv6.

If you need some more log or debugging data let me know

**Comment by fabianfrz** [comment]
plugins was the correct repo. dyndns is a plugin.

**Comment by fichtner** [comment]
Yup. :)

**Comment by theq86** [comment]
Oh yes, since 17.7. thx
