### ISSUE TITLE
Opening port ranges only works with an alias

### ISSUE THREAD

**Issue by jkent** [opnsense/core#2126]
v18.1.r2
Tried to open a UDP port *range* using (other) from/to fields fails.  A single port works fine.  @fraenki gave me the idea to try with an port range alias and this worked.

**Comment by fichtner** [comment]
I think you need to scroll up in the dropdown, select (other) and then you get the port input boxes.

**Comment by jkent** [comment]
Yes, (other) was selected, the port range was entered into the two boxes below.

**Comment by fichtner** [comment]
And then what happened as opposed to what was expected? It worked when I just tried it?

**Comment by jkent** [comment]
mosh was unable to connect when using the from/to fields, but connects and talks fine when port range alias.  Also mosh works if I create a port forward for it after it tells me what port it is trying to talk on.

I tested again, the following does NOT work properly.  Creating an alias for the port range however does work
![screenshot at 2018-01-24 00-53-06](https://user-images.githubusercontent.com/556979/35318459-18918bda-00a1-11e8-9fa1-144d40b442ff.png)

**Comment by fichtner** [comment]
Thanks, that was what I needed. Can you try this patch?

    # opnsense-patch 69929ee


Cheers,
Franco

**Comment by jkent** [comment]
Thanks Franco, I tried it out, works here!

**Comment by fichtner** [comment]
Super, thank you @jkent for the report and quick test! :)
