### ISSUE TITLE
get_dyndns_ip function returns link-local v6 address instead of global unique

### ISSUE THREAD

**Issue by theq86** [opnsense/core#2128]
The context for this ticket can be read here: https://github.com/opnsense/plugins/issues/509

To determine, if the current public ip is in sync with the cached file in OPNsense the dyndns plugin calls the core function _get_dyndns_ip()_ in _src/etc/inc/services.inc_.

In my case, this function returns my link-local address (fe80::[interface-identfier]) instead the global unique address, which would be necessary to compare to the cached address.

Edit:

excerpt from my system log:

`opnsense: /services_dyndns.php: Aborted IP detection: bind failed with errno 49: Can't assign requested address`

It seems an error occurs during executing the curl-request in line 1595.

**Comment by theq86** [comment]
Looks like the curl option CURLOPT_INTERFACE makes problems with ipv6.

**Comment by fichtner** [comment]
I'll revert the IPv6 part to what it was before, which simply checks the IP addresses on the interface since they should be globally visible.

**Comment by theq86** [comment]
I had a similar aproach.

look:
_src/etc/inc/services.inc_
```
if ($ipver == 6 || is_private_ip($ip_address)) {
// curl stuff
}
```
I see why this is needed for private ipv4 addresses, But for IPv6 ? I think not.

There's something different that confuses me:
_src/etc/inc/interfaces.inc_ l. 4297
```
if (isset($config['interfaces'][$interface]['dhcp6prefixonly'])) {
            $curip = find_interface_ipv6_ll($realif, $flush);
            if ($curip && is_ipaddrv6($curip) && ($curip != "::")) {
                return $curip;
            }
        }
```
I have checked the option to only request a prefix on WAN. In that case, explicitly the link-local address is returned. That leads to the "wrong" IP returned. I need the WAN IP regardless of this setting.

**Comment by fichtner** [comment]
ipv6 through dyndns was an experiment. The thing fails for the same reason like always: there is only a link-local address. It's not capable of reaching out. But that is already the case while trying to resolve. Changed the code and a log message, but will have to see how this pans out in the office on Monday.

**Comment by fichtner** [comment]
In the custom settings there is a "Interface to send update from" extra input... it sounds like it's more useful in these cases?

**Comment by fichtner** [comment]
We fail hard on link local addresses now.
