### ISSUE TITLE
Proxy Local Cache Steam|Adobe|Java|Google

### ISSUE THREAD

**Issue by rudiservo** [opnsense/core#2129]
Add new types of cache sites
or
add if possible a custom configuration area so that Squid StoreId helpers may be configured.

If anyone can point me in the right direction on where the configuration is saved and executed I can add the proper code and form elements.

**Comment by fabianfrz** [comment]
You can look at the cache code for Linux and Windows packages.:
* https://github.com/opnsense/core/blob/master/src/opnsense/service/templates/OPNsense/Proxy/squid.conf#L320-L336
* https://github.com/opnsense/core/blob/master/src/opnsense/mvc/app/models/OPNsense/Proxy/Proxy.xml#L131-L138
* https://github.com/opnsense/core/blob/master/src/opnsense/mvc/app/controllers/OPNsense/Proxy/forms/main.xml#L163-L174

**Comment by fabianfrz** [comment]
BTW: Shouldn't java be already cached (matches .rpm on fedora, centos etc., .deb on debian, ubuntu, mint, and pkg.tar.xz on ArchLinux) or are you talking about JAR files, which should not be very common now as there is no applet support anymore -> the feature would then only act as a package cache for maven etc.

**Comment by rudiservo** [comment]
Is the markdown on the squid config script liquid?
Dont get me wrong but I see to much fragmentation on the scripting languages in use.

**Comment by rudiservo** [comment]
Ok got it you are using volt.
why are you using volt for configurations?
why you have models with zero stuff in it... couldnt they easily be used for configs.
Again dont get me wrong, it looks like very smart with a lot of magic, just very confusing... cant make heads or tails what is the workflow and how things are called and where and by what.

**Comment by fichtner** [comment]
https://docs.opnsense.org/development/backend/templates.html

**Comment by AdSchellevis** [comment]
timeout
