### ISSUE TITLE
Feature Request: cronjob to turn WLAN on/off

### ISSUE THREAD

**Issue by ivoruetsche** [opnsense/core#2135]
Hi

Maybe it's also helpful for other home users with an esoteric touch:

cron to stop/start the wifi in the night.

gruss ivo

**Comment by fichtner** [comment]
Hi ivo,

Some more changes coming up eventually for the cron job command selection. I'll take this, but it'll be a while...


Grüsse
Franco

**Comment by micressor** [comment]
Is there already a workaround, so that you can install it yourself?

**Comment by azdps** [comment]
> Is there already a workaround, so that you can install it yourself?

Yes you can create your own cron jobs that will show as one of the selections under webui --> cron. See the following forum post for specific instructions. I tested this and was able to create one rather quickly. The description that you provide in your actions_* file will show up in the webui --> cron as the description for the cron job. Obviously you will need to access the shell to accomplish this. What would be great is if someone started a thread on the forums that specifically for users to post their custom cron jobs.

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/core/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
