### ISSUE TITLE
Bootstap seems to be missing badge colors

### ISSUE THREAD

**Issue by fabianfrz** [opnsense/core#2138]
Bootstrap in OPNsense does not support colored badges:
https://getbootstrap.com/docs/4.0/components/badge/#contextual-variations

All badges result in the gray variant. Maybe bootstrap needs an update.
See: https://github.com/opnsense/core/compare/master...fabianfrz:badge?expand=1

This not yet made PR will probably make opnsense/plugins#508 work better.

**Comment by AdSchellevis** [comment]
@fabianfrz I'm not sure bootstrap 3.x support badge colours, see http://getbootstrap.com/docs/3.3/components/#badges for the correct documentation. Upgrading to 4 isn't an option at the time, they changed quite some styles and concepts if I'm not mistaken.

**Comment by fabianfrz** [comment]
so the difference to 4 is that  in 4 both are badges - in 3 the rectangular is label: https://getbootstrap.com/docs/3.3/components/#available-variations

**Comment by fabianfrz** [comment]
the problem is solved for now: #2139
