### ISSUE TITLE
Password Protect local console

### ISSUE THREAD

**Issue by brandonmreeves** [opnsense/core#2142]
Not sure if this is a support request or a feature request. 

It would be nice if we could protect the menu when someone plugs a keyboard, mouse, and monitor into the device.

For example rather than just plugging in and seeing the menu for managing opnsense, we would like there to be a username/password prompt before the menu is presented (maybe just for the root user).

The justification for this is that we are deploying a number of local and remote opnsense devices and we would like to protect the physical console from modification without our permission. As it stands, if someone gets access to the device physically, our concern is that they may reset the root password and/or reset the system to defaults which would create a support issue for us.

We see a few options.
1.) Password protect the local console menu
2.) disable the console menu altogether except through SSH
3.) Use a custom console which would be limited to reboot/shutdown etc.

Any advise or recommendations would be great.

**Comment by NOYB** [comment]
Think this is this what you're looking for.

System: Settings: Administration
Console menu - Password protect the console menu

**Comment by fabianfrz** [comment]
A mouse is also an useless device because its input will not be used anyway (OPNsense is CLI only).
Logging out is possible, but it will lead to unexpected behaviour(like terminating processes). If you don't want people attaching stuff, you should look for a lockable 19" rack.

**Comment by fichtner** [comment]
Hi @brandonmreeves,

We've introduced https://github.com/opnsense/core/commit/46251a023 in 2014 prior to our first release, so I think what you're looking for has always been the default.

And @NOYB is right, you can still trigger this from the settings if you wish to toggle the behaviour.

I think this can be closed? :)


Cheers,
Franco

**Comment by brandonmreeves** [comment]
Yes please close. I apologize I missed the setting.

Thanks

**Comment by fichtner** [comment]
No worries. :)
