### ISSUE TITLE
mtu not correctly set for vlan and parent for pppoe RFC4638

### ISSUE THREAD

**Issue by gizahNL** [opnsense/core#2146]
Setting the WAN PPPOE mtu to 1500 and setting link parameter of associated vlan to mtu1508 does not correctly set mtu for parent device to 1528 and thus doesnt allow raising of vlanmtu to 1508.

This results in non-working connection as the padi mtu negotiation is forced to 1500.

Solution would be to cascade mtu settings, and first apply them to vlan parents then to vlan before continuing with pppoe

**Comment by fichtner** [comment]
Sorry, I may be misunderstanding. WAN PPPoE needs to set 1520 if it sits on top of a VLAN, physical  parent needs 1528 ? resulting PPPoE MTU is 1500...
