### ISSUE TITLE
Update unbound root.hints file

### ISSUE THREAD

**Issue by itys** [opnsense/core#2147]
Update root DNS servers by downloading root.hints file from Internic, verify signature, and then update unbound.conf with the relevant config:

Step 1. curl ftp://ftp.internic.net/domain/named.cache -o /var/unbound/named.cache
Step 2. curl ftp://ftp.internic.net/domain/named.cache.sig -o /tmp/named.cache.sig
Step 3. gpg --verify /tmp/named.cache.sig /var/unbound/named.cache
Step 4. if return 0; mv /var/unbound/named.cache /var/unbound/root.hints
Step 5. append server: block to /var/unbound/unbound.conf <<
server:
   root-hints: /root.hints
Step 6: restart unbound
Step 7 (optional): add to unbound update process and/or cron job like updating the bogons 

Reference: Issue #2144 
cc: @fichtner

**Comment by fichtner** [comment]
I think we'll have to do something similar to what we do with changelogs and bogons... provide our own signature on our package mirrors and avoid the use of curl grabbing both sig and hints from same insecure ftp and doing the gpg check on a server that supports it (gpg is not installed in OPNsense).
