### ISSUE TITLE
Blocking bogons breaks DHCPv6

### ISSUE THREAD

**Issue by gizahNL** [opnsense/core#2148]
Blocking bogons on a wan interface that also needs to do DHCPv6 for PD breaks DHCPv6. 

The only way to solve this is to disable bogon blocking, as it is currently imposssible to prioritize explicit quick pass rules for DHCPv6 above bogon blocking (since bogon blocking cannot be moved around in the interface). 
This was quite the headbreaker, took quite some time to figure out why things where breaking, and then how they where breaking...

Bonus feature request:
when enabling dhcpv6 for interface create matching firewall rule for interface "pass in quick on $interface inet6 proto udp from any port 547 to any port 546"

**Comment by fichtner** [comment]
@gizahNL sorry for the delay. Which bogon network block is causing this, do you know?

**Comment by gizahNL** [comment]
I am unsure, I didn't wireshark or have any logs. 
Just the fact that, at least in my specific situation (XS4All FTTH, DHCP-PD over PPPOE link) if I have block bogons enabled on the wan link I am unable to get PD working, tested using command line. 

Even adding a floating top rule to allow DHCPv6 traffic did not resolve it so I assume interface specific bogon blocking precedes that.

**Comment by fichtner** [comment]
@marjohn56 did you see this pop up before?

**Comment by marjohn56** [comment]
Nope, I can test it though. My ISP is PPPoE and although I use static I can switch quickly to DHCP6C, give me five.

**Comment by marjohn56** [comment]
Negative... although I did see multiple dhcp6c clients on first run ( see my PR ! ) killing them and saving the wan interface corrected that and I have a prefix on LAN and my V6 address on the WAN as seen here.

![image](https://user-images.githubusercontent.com/17962918/35695302-f91529c4-077b-11e8-869c-238dc14fe250.png)

**Comment by marjohn56** [comment]
Oops.. left my v4... now blanked. :)

**Comment by fichtner** [comment]
Thanks @marjohn56!

Realistically, we need to know where the PD response comes from if it is blocked via the IPv6 bogons list so we can exclude it.

(18.1.1 goes out tomorrow, then I'm all dhcp for you).

**Comment by marjohn56** [comment]
Certainly need more info on that. I'd like to see the dhcpd logs and the firewall logs with all logging enabled.

**Comment by macktic** [comment]
Still happening
I’ve been scratching my head why the dhcpv6 on lan wasn’t giving out addresses 
Started working as soon as I unchecked the block bogon on the lan interface

**Comment by fichtner** [comment]
Do you know which is the offending network?

**Comment by macktic** [comment]
fe80::

**Comment by marjohn56** [comment]
Why are you enabling block bogons on the LAN?  

Bogons also include private address spaces as well.

See this is wiki:

https://en.wikipedia.org/wiki/Bogon_filtering

**Comment by macktic** [comment]
There’s a separate box for private addresses. 
Bogon should just be addresses that should never be used so should be save to enable. 

Not really necessary to enable on lan, but it shouldn’t break things if you do. 
Just in case some IoT device gets hacked, block anything that’s unexpected on the lan

**Comment by macktic** [comment]
fe80:: should really be in the private list, not the bogon one...

**Comment by fichtner** [comment]
Not really, because on the WAN side you reach the public scope even if link-local.

@AdSchellevis priorities for bogons and all other pluggable rules are at 5 so bogons seem to take precedence... should we up all pluggable rules to 4 and leave bogons at 5? the WAN side client rules for IPv6 are already at priority 1...

**Comment by AdSchellevis** [comment]
old version? fe80:: isn't in our bogons list (https://pkg.opnsense.org/FreeBSD:11:amd64/19.1/sets/bogons.txz)

```
grep "fe80:" fullbogons-ipv6.txt 
2001:df0:fe80::/41
2001:df1:fe80::/41
2001:df2:fe80::/41
2001:df3:fe80::/41
2001:df4:fe80::/41
2001:df5:fe80::/41
2001:df6:fe80::/41
2001:df7:fe80::/41
2a0e:fe80::/25
2c0f:fe80::/29
```

**Comment by fichtner** [comment]
it actually is: 8000::/1 -- find reference will find it indeed :)

**Comment by AdSchellevis** [comment]
I think we should indeed move the dhcp inbound in the same region as the outbound traffic, although I don't think we should move all plugins up at once. 

https://github.com/opnsense/core/blob/0ea621cab309d7445992cfe56cdf30d638108f92/src/etc/inc/filter.lib.inc#L326-L352

**Comment by fichtner** [comment]
which prio do you suggest? ideally dhcpd-related things can go into dhcpd.inc now

**Comment by AdSchellevis** [comment]
prio 1 if you ask me, moving it into dhcpd.inc in the process sounds good indeed

**Comment by fichtner** [comment]
@macktic can you try 316d8dd?

    # opnsense-patch 316d8dd

It'll need a rules reload.


Thanks,
Franco

**Comment by macktic** [comment]
That seems to have done it. 
Thanks

**Comment by fichtner** [comment]
Ok, we‘ll add this in 19.1.8. Thanks!
