### ISSUE TITLE
captive portal: bad database

### ISSUE THREAD

**Issue by fichtner** [opnsense/core#215]
Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[HY000]: General error: 1 no such table: captiveportal_ip' in /usr/local/opnsense/mvc/app/models/OPNsense/CaptivePortal/DB.php:342 Stack trace: #0 [internal function]: PDO->prepare('select ip,pipen...') #1 /usr/local/opnsense/mvc/app/models/OPNsense/CaptivePortal/DB.php(342): Phalcon\Db\Adapter\Pdo->query('select ip,pipen...') #2 /usr/local/opnsense/mvc/app/models/OPNsense/CaptivePortal/CPClient.php(162): OPNsense\CaptivePortal\DB->listFixedIPs() #3 /usr/local/opnsense/mvc/app/models/OPNsense/CaptivePortal/CPClient.php(147): OPNsense\CaptivePortal\CPClient->refreshAllowedIPs(NULL) #4 /usr/local/opnsense/mvc/app/models/OPNsense/CaptivePortal/CPClient.php(107): OPNsense\CaptivePortal\CPClient->update() #5 /usr/local/etc/inc/captiveportal.inc(229): OPNsense\CaptivePortal\CPClient->reconfigure() #6 /usr/local/etc/inc/captiveportal.inc(337): captiveportal_init_rules(true) #7 /usr/local/www/services_captiveportal.php(386): captiveportal_configure() #8 {main} in /usr/local/opnsense/mvc/app/models/OPNsense/CaptivePortal/DB.php on line 342

via https://forum.opnsense.org/index.php?topic=679.0

**Comment by fichtner** [comment]
@AdSchellevis you are going to like this one...

**Comment by AdSchellevis** [comment]
Nice!

**Comment by jschellevis** [comment]
Great work Franco!


Verzonden vanaf mijn Samsung-apparaat

-------- Oorspronkelijk bericht --------
Van: Franco Fichtner <notifications@github.com> 
Datum: 16-06-2015  19:08  (GMT+01:00) 
Aan: opnsense/core <core@noreply.github.com> 
Onderwerp: Re: [core] captive portal: bad database (#215) 

Closed #215 via eac7cdd.
