### ISSUE TITLE
Current firmware API does not report that 18.1 is available

### ISSUE THREAD

**Issue by astrandb** [opnsense/core#2153]
I am using API (/api/core/firmware/status) calls to remind me if my routers have firmware upgrades available.
It worked as expected when 17.7.12_1 became available. The json response contained updates=1, download_size=3MiB etc.

After I installed 17.7.12_1, the json response says that no updates are available even though the GUI shows a yellow panel with EOL message.

It would be useful if the API response included the same information.

**Comment by fichtner** [comment]
Thanks, will be done in time for the next iteration. :)

**Comment by fichtner** [comment]
Hi @astrandb,

API now exposes "upgrade_major_version" and "upgrade_major_message". You can also fetch the major version via changelog as the GUI does now. The message is optional, mainly used for a few last words to mention incompatible changes, upgrade methods, etc.

Not sure when this will hit the 18.1.x track, but certainly before the EoL release so it can be used. :)


Cheers,
Franco

**Comment by astrandb** [comment]
Thank you @fichtner 
I will update my check script for icinga2 well before the next major release and then just sit back and wait for the bell...
/Åke

**Comment by fichtner** [comment]
Sure, I'll try to ping when this is merged into 18.1.x to let you know it's incoming. :)
