### ISSUE TITLE
IPv6 connection not working on clients after 24h reconnect

### ISSUE THREAD

**Issue by theq86** [opnsense/core#2155]
Forum link for reference: https://forum.opnsense.org/index.php?topic=6946.msg31674#msg31674

After the 24 hours reconnect, IPv6 is no more working on the clients. As the forum user mentions it seems that the clients are assigned an old prefix although after reconnect the prefix changed.
I can also confirm that issue. v 18.1_1

**Comment by fichtner** [comment]
Could be #2164, although that was the case since 2016 if true.

**Comment by theq86** [comment]
I can try to apply opnsense-patch f09eaf7. Will report the next 2-3 days if it helps.

**Comment by fichtner** [comment]
@theq86 thanks! But this will very likely hit 18.1.2 tomorrow anyway.

**Comment by fichtner** [comment]
Ok, we'll keep looking. Thanks for the double-check.

**Comment by theq86** [comment]
What happens during periodic interface reset? I tried to find out something more about this issue.

First, what I stated earlier is wrong, all clients get the correct IPv6 address. But after periodic interface reset (every morning at 4 o' clock on my box) IPv6 internet stops working.

Some facts:
Client -> LAN address -> ping works
Client -> WAN address -> ping works
Client -> Internet -> does not work.

Then I tcpdump'ed the connections on the client, the opnsense' pppoe1 interface and on the server.

Client: obviously, ping request is shown, response not
OPNsense (pppoe1): same here, request is shown, response is not
internet server: receives ping, sends reply

So the way towards the server is working. but the way back does not, not even the pppoe interface receives the echo reply.

**Comment by fichtner** [comment]
Multiple tickets and patches landing on master at the moment. Can you reevaluate on the development version of 18.1.3 when that is out?

**Comment by theq86** [comment]
Yes. Tell me when I can test it and how to update/downgrade to/from the dev version.

**Comment by fichtner** [comment]
I've been unspecific regarding commits because there have been a couple that seem to improve things in tandem. You can switch to the dev version from System: Firmware: Settings and hit save and update. Then...

    # opnsense-code core
    # cd /usr/core && make upgrade


Cheers,
Franco

**Comment by theq86** [comment]
I can test it at the weekend. These changes will hit 18.1.4 then?

**Comment by fichtner** [comment]
At least all in dev version of 18.1.4. We don't necessarily put them into the release without testing. :)

**Comment by fichtner** [comment]
@theq86 how's 18.1.4 working for you?

**Comment by theq86** [comment]
I will test it tonight. Until now I still had the full reboots in my crontab.

**Comment by theq86** [comment]
Unfortunately not better in 18.1.4. :-(

**Comment by fichtner** [comment]
Step by step. How about this? https://github.com/opnsense/core/commit/64057c13

    # opnsense-patch 64057c13

**Comment by theq86** [comment]
64057c1 or 64057c13? Your linked commit does not match the commit in the command ;-)

**Comment by fichtner** [comment]
Same one, github truncates the hash after posting...

**Comment by fichtner** [comment]
Logs should be a lot better now on 18.1.4, too. Can you sanitised post newwanip logs of your next test?

**Comment by theq86** [comment]
yes. I'll post them here in the evening.

**Comment by fichtner** [comment]
Where does "62.214.63.93" come from? Can you verify in ifconfig where this is? It picks up the wrong IP, so that's why it fails quite simply oO

**Comment by fichtner** [comment]
If it's not in ifconfig, it's set in a gateway under system: gateways: single maybe...

**Comment by fichtner** [comment]
# grep 62.214.63.93 /conf/config.xml

**Comment by theq86** [comment]
This IP could not be found in the config.xml. It is in fact my Gateway IP. This is the one I get from my ISP.
Now where I rebooted my sense, everything is working. Still have the same IP as my gateway but it does not come from within my configuration.

**Comment by fichtner** [comment]
Ok, will need these to before and after daily reset:

    # netstat -nr | grep default

Maybe it lands on the wrong interface after reconnect. :/

**Comment by theq86** [comment]
Okay, I can provide this info when I'm back from work.

BTW after interface reset IPv4 internet works but I can't connect to openvpn. Maybe it is a firewall thing. But let's first check on the routing.

**Comment by theq86** [comment]
before:
`default            62.214.63.93       UGS      pppoe0
default                           fe80::5651:1bff:fe83:bbbd%pppoe0 UGS   pppoe0`

after:
`default            62.214.63.93       UGS      pppoe0
default                           fe80::5651:1bff:fe83:bbbd%pppoe0 UGS   pppoe0`

that's the same output.

**Comment by fichtner** [comment]
Thanks, I think this is deep inside netgraph that makes this fail as someone else reported lately. Was this test with the additional 64057c13 patch or without?

**Comment by theq86** [comment]
It was including https://github.com/opnsense/core/commit/64057c136f4d579eeeb2dfb565f72fc3f9004b75

**Comment by fichtner** [comment]
Ok, thanks for confirming. To me it seems something is completely broken and it's not our scripting... :(

**Comment by fichtner** [comment]
@theq86 18.1.7 replaced dhcp6c and a race condition in dhcp6c daemon creation. Does that make any difference here?

**Comment by theq86** [comment]
@fichtner 
I just upgraded to 18.1.7 and will have a look on that. I was busy so no pre-testing was possible. I will report back in a few days. :-)

**Comment by theq86** [comment]
I deactivated the reboot cron. for 2 days now everything is working fine including ipv6.
However, I forgot to reactivate the periodic interface reset at 4 o' clock. I did it now and will report back. but so far so good

**Comment by theq86** [comment]
okay, tested for four days now. the issue is resolved.

**Comment by fichtner** [comment]
Thanks, great to hear. So 18.1.6 did not work but 18.1.7 does? In that case it was likely the SUGHUP addition for dhcp6c that prevents spawning of new processes which lock each other out. 😊
