### ISSUE TITLE
GUI Schedule tab in Intrusion Detection disappears

### ISSUE THREAD

**Issue by nqnguyen2** [opnsense/core#2160]
Tried searching for this bug/issue but didn't find anything so I'm opening one. Issue occurs on both 18.1 and 18.1.1. Rebooted afer latest udpate and still able to replicate.

Current Version: 18.1.1
Browser: Chrome (latest) and Firefox (v56)

1. Action Path: Services -> Intrusion Detection -> Select another tab besides Settings (ie. Download, Rules, User Defined, Alerts)
1. Select Schedule and wait for "Edit job" pop-up
1. Click Close button
1. Schedule tab disappears (https://www.screencast.com/t/8sRyrlfZ2hQT) and doesn't appear until any of the following occurs:
    1. Refresh page
    1. Select Settings tab
    1. Select Intrusion Detection again 
    1. Select any item in left menu panel and select Intrusion Detection again

Video: https://www.screencast.com/t/zR5iG6RDl (requires Flash)

**Comment by fichtner** [comment]
Looks like this was done by design, although it is understandably confusing.

You can try this patch, simply invoke the command from the console:

    # opnsense-patch e6423e3


Cheers,
Franco

**Comment by nqnguyen2** [comment]
Thank you for the quick response!

**Comment by highwalker** [comment]
Hi, this still is open in 20.7.3, can you please update or share a patch? I am not sure if I can use the previous patch posted.

**Comment by mimugmail** [comment]
Screenshot please

**Comment by highwalker** [comment]
I have attached a gif file to show the animation, clicking schedule tab pops up the new job screen and doesn't let old jobs to be edited. Work around is to use the cron jobs to edit the existing jobs.

![IDS-SchedTab](https://user-images.githubusercontent.com/4450185/94380362-94dac280-0178-11eb-9546-6113ea7663d9.gif)

**Comment by mimugmail** [comment]
It links to System : Settings : Cron, opening a new schedule, looks good to me
