### ISSUE TITLE
NAT portforwarding use only the last entry from alias port list in 18.1_1

### ISSUE THREAD

**Issue by pazifi** [opnsense/core#2161]
Hi all,

i think there is an issue with portforwarding.

If i forward the ports 80 and 443 with an alias group from WAN address to a private address in lan (ex. 10.0.0.10)
all request ar forwarded to the last entry in alias list.

So, is port 80 the last entry, all requests (from port 80 and 443) are forwarded to 10.0.0.10:80.
Is port 443 the last entry, all requests (from port 80 and 443) are forwarded to 10.0.0.10:443.

In earlier versions (17.x) the ports were forwarded unchanged if I used an alias with the same configuration. 
(WAN-IP:80 -> 10.0.0.0.10:80 / WAN-IP:443 -> 10.0.0.0.10:443)

Version: 18.1_1

Greetins,
pazifi

**Comment by fichtner** [comment]
Hi, will you try 18.1.1 ? :)

**Comment by pazifi** [comment]
Problem solved in 18.1.1! Thank you very much :)

**Comment by fichtner** [comment]
Yay, thank you for confirming. :)
