### ISSUE TITLE
[feature request] Activate all rules for intrusion- detection

### ISSUE THREAD

**Issue by b2410** [opnsense/core#2163]
Hi,

It would make it much easier if there was a button with which you can activate all the rules.
There are just too many to activate individually.

**Comment by fichtner** [comment]
Thanks :)

While here, I want to address the ambiguity of the primary toggles on the ruleset page, too.

**Comment by fichtner** [comment]
@AdSchellevis I'm removing my assignment this this is not my topic in an effort to find time for other areas like IPv6 connectivity. maybe you want to take this?

**Comment by fichtner** [comment]
ok, marking support and closing then

**Comment by fichtner** [comment]
Some changes were made in 18.7.1...
