### ISSUE TITLE
IPv6 gateway monitoring not working when WAN is a link local.

### ISSUE THREAD

**Issue by marjohn56** [opnsense/core#2164]
One of my testers has an issue whereby he cannot get v6 gateway monitoring to work. On investigation I find that the *_defaultgw6 file is empty. This file is echoed out by rtsold and it took me a while to find the cause and it's in system.inc lines 460 to 463.

    /* XXX eventually this file-based workaround must be removed */
    foreach (glob('/tmp/*_defaultgw{,v6}', GLOB_BRACE) as $to_delete) {
        @unlink($to_delete);
    }

What is the purpose of this apart from deleting the files at this point?

**Comment by fichtner** [comment]
Funny, this. 4590b17dd2dea3

I refactored this, but now it looks like it was a silly piece of code in the first place.

Can you spot an issue with the refactor besides moving it out of the if block for when gateways are set?

**Comment by fichtner** [comment]
https://github.com/pfsense/pfsense/blob/3c44c845fe6dcbd160ee778bc918c024c447545b/src/etc/inc/system.inc#L677

This is today. And I also found this...

https://github.com/pfsense/pfsense/commit/924f202ee818c72b10855d3a1c06b34a9e7aa595

**Comment by marjohn56** [comment]
Was the original intention just to delete the files to clean up, or was it to do with some strange gateway issue?

Cannot see where you've moved it to as I'm now on my tablet and it won't play nicely with github. :)

**Comment by fichtner** [comment]
I've moved it out of the if loop below. I think the system tries to delete stale gateways and put them back. At some point it grew to do IPv6 as well. Organically grown, outlived its prime time...

**Comment by fichtner** [comment]
Try this....

    # opnsense-patch f09eaf7

I need to take this further though, not backwards.

**Comment by fichtner** [comment]
May still walk all over you, now simply when you less expect it.

**Comment by fichtner** [comment]
I have a better solution for this logic ready, it should hit master in the next two days.
