### ISSUE TITLE
OpenVPN Client error at boot

### ISSUE THREAD

**Issue by kingfisher77** [opnsense/core#2166]
Since update to 18.1 the formerly working OpenVPN Client throws an error after The boot process hangs for a few minutes:
opnsense: /usr/local/etc/rc.bootup: New alert found: There were error(s) loading the rules: no IP address found for ovpnc3:network - The line in question reads [0]:

Restarting the OpenVPN client after bootup helps. The connection works.

**Comment by fichtner** [comment]
Hi @kingfisher77,

Is this no longer the case or why the close?


Cheers,
Franco

**Comment by kingfisher77** [comment]
Thought it was not clear enough, just postet a new issue with more context.

**Comment by kingfisher77** [comment]
Would have been better to post more context in the original issue, or?

**Comment by fichtner** [comment]
indeed, thanks! fine by us either way. only thing that is not so good is having multiple tickets and going back and forth between them for help.... confusing :)
