### ISSUE TITLE
Unbound autoconfig sets bad value on large machines making system unusable.

### ISSUE THREAD

**Issue by rbonser** [opnsense/core#2172]
I am new to opnsense. I recently downloaded the installer for 17.7.5 amd64 and attempted to install on spare hardware to do some testing and could not get the system to stay running for more than a few minutes before it consumed all of the memory and swap then locked up. It would not even stay running long enough to run the installer.

The same happened with the new 18.1 installer as well so I tried the bsd install / boostrap route and was able to install freebsd 11.1 just fine but after bootstrapping opnsense and rebooting the same issue returned.

I was able to track down the cause to the line sited:
https://github.com/opnsense/core/blob/2d4ef851efbd18e148328a09c4f4fd7b6a15c2e1/src/etc/inc/plugins.inc.d/unbound.inc#L110

The hardware specs are:
2x8-core Xeon w/HT
64GB ram

Based on the size of the hardware I was using for testing, this calculation was setting a negative value ( -18 ) for outgoing-range in unbound.conf which in turn caused the unbound process to freak out and start consuming resources until the machine crashed.

This value should not be allowed to go negative.

When I tweaked the calculation to get a positive value on my hardware the system booted properly.

  --Roy

**Comment by fichtner** [comment]
Hi Roy,

Thanks for that report and analysis! One small question: what does this yield on your box?

    # sysctl kern.smp.cpus

Mine says:

    # sysctl kern.smp.cpus
    kern.smp.cpus: 4

It's the value that is used in the calculation leading up to the error.


Thanks,
Franco

**Comment by rbonser** [comment]
```
# sysctl kern.smp.cpus
kern.smp.cpus: 32
```

  --Roy

**Comment by fichtner** [comment]
ouch, ok, I'll propose a fix soon

**Comment by fichtner** [comment]
You can try the patch, but need to make sure your code is clean so the patch won't fail:

    # opnsense-revert opnsense
    # opnsense-patch b12f921


Cheers,
Franco
