### ISSUE TITLE
ApiMutableModelControllerBase getBase typo

### ISSUE THREAD

**Issue by fbrendel** [opnsense/core#2176]
Got an error:
>Fatal error: Uncaught Error: Call to undefined method OPNsense\Base\FieldTypes\ContainerField::add() in /usr/local/opnsense/mvc/app/controllers/OPNsense/Base/ApiMutableModelControllerBase.php:256

Seems that line 256 `$node = $mdl->add();` should be `$node = $mdl->Add();`

**Comment by fichtner** [comment]
Thanks!
