### ISSUE TITLE
session_timeout = 0 -> Help text incorrect

### ISSUE THREAD

**Issue by astrandb** [opnsense/core#2177]
Regarding System->Access->Settings: Session Timeout.
The help text states that 0 means Never Expire. I don't think this is true. A zero value is treated as no value = default i.e. 240 min.
I would not recommend to allow for being logged in indefinitely so the easy fix is to remove the last part of the help text.

**Comment by fichtner** [comment]
@adschellevis is it true that the MVC does not check session_timeout yet ?

**Comment by fichtner** [comment]
PS: It seems the help text was corrected while working on #1929 which is due to hit in 18.7. :)

**Comment by AdSchellevis** [comment]
@fichtner it seems so, it defaults to 4 hours at the moment, let me fix this.

**Comment by fichtner** [comment]
Super, thanks! ❤️
