### ISSUE TITLE
WAN DHCP update on power loss

### ISSUE THREAD

**Issue by mitjari** [opnsense/core#2178]
I have opnsense box connected to cable modem and is configured to get ip via DHCP. Opnsense box is connected to UPS so when power goes out only the modem powers off. When the power comes back the opnsense gets "temp" ip from modem: 192.168.100.10. But then when it should get "real" ip it chrashes returning the error atached below.

I found out that this is happening when I have "ounbound dns" service or "dynamicDNS" service enabled.

![dhcperror](https://user-images.githubusercontent.com/7448895/35931041-de102c2a-0c33-11e8-8f29-286a291b97d4.png)

**Comment by fichtner** [comment]
I don't know about the dhclient error, but you can set "Reject Leases From" on the WAN interface configuration for 192.168.100.1 and see if that helps.

**Comment by mitjari** [comment]
I tried to put modem ip in "Reject Leases From" but got same error. I still have to manually renew IP via GUI.

**Comment by fichtner** [comment]
Maybe same issue as #2372, has patches attached.

**Comment by fichtner** [comment]
Closing, will ship in 18.1.7. Feel free to reopen or discuss further on #2373.
