### ISSUE TITLE
configd: startup sometimes fails to bring up the socket in time

### ISSUE THREAD

**Issue by fichtner** [opnsense/core#218]
Workaround exists: wait a little longer for configd to come up. It seems we need a retry/delay for the socket on configctl invokes.

via: https://forum.opnsense.org/index.php?topic=731.0

**Comment by AdSchellevis** [comment]
fixed with :
https://github.com/opnsense/core/commit/b282f65db57ee4a0c16416077326d989e879ec53
https://github.com/opnsense/core/commit/f43baf4a6437d7e0ac23a27c89ebf19a7d971594
https://github.com/opnsense/core/commit/064de35257a1277670e4bd485b27e057548ee95a

**Comment by fichtner** [comment]
thank you! :)
