### ISSUE TITLE
firewall: put category filter selection on top of the list/screen

### ISSUE THREAD

**Issue by jodelkoenig** [opnsense/core#2182]
Hi,

would it be possible to move the field to set the filter for rule maintenance on top of the list/screen rather than at the bottom? It'll be great to just select the filter and maintain filter specific rules right away. Rather than scrolling all the way down, set filter, and scrolling all the way up again after a filter has been applied.

Thanx

**Comment by AdSchellevis** [comment]
@jodelkoenig you mean the category filter?

**Comment by jodelkoenig** [comment]
Indeed. The category filter :)

**Comment by jodelkoenig** [comment]
One more thing, related to category filer:

It'll be great if a selection would survive the switch between interfaces. With 18.1 this is no longer the case. With the latest 17.x the selection was still valid, even if I changed the - via tab - from LAN to OpenVPN or so. 

Thanks :)

**Comment by AdSchellevis** [comment]
ok, this is work in progress. https://github.com/opnsense/core/commit/ac4f5a1aec26d5ec1fc89680b9019ef37ce6db4c fixes the "sticky" categories like it was, but creates issues in the menu system (matching). 

To be continued...

**Comment by AdSchellevis** [comment]
Functional it would indeed be better to move the filter to the top of the page, optical it probably looks a bit better on the bottom.

I'm not sure this is the best version, but can you try the commits in this issue?

`
opnsense-patch  ac4f5a1 5bc9fdf  0752629
`

**Comment by fichtner** [comment]
What if you put the drop down where the "Add xxx" buttons would be?

**Comment by fichtner** [comment]
<img width="1172" alt="screen shot 2018-02-16 at 7 10 43 am" src="https://user-images.githubusercontent.com/1915288/36295551-8e2f4cde-12e8-11e8-9b63-717649aee592.png">

**Comment by jodelkoenig** [comment]
I like your idea, fichtner. This looks much cleaner.

Thanks AdSchellevis. For both items. Category Filter at the top of the page and persistency of filter cross interface pages.

**Comment by AdSchellevis** [comment]
@fichtner better indeed, shall I change it accordingly

**Comment by fichtner** [comment]
yes please, I only fiddled with the browser's DOM

**Comment by AdSchellevis** [comment]
it was a bit of fiddling, but this should be it 
![image](https://user-images.githubusercontent.com/9783985/36309800-4f0da8f0-1326-11e8-9641-823965d675d1.png)

**Comment by fichtner** [comment]
Very nice, thanks!

**Comment by jodelkoenig** [comment]
Indeed. Thanks a lot! Cool :)
