### ISSUE TITLE
Automatic NAT Rules (Outbound) in Hybrid NAT not working for non-attached networks (18.1.*)

### ISSUE THREAD

**Issue by s256** [opnsense/core#2183]
Hi all,
since we updated to version 18.1.1 (from 17.7.12) we have issues with the NAT (Outbount) rules.
We have two networks which are not connected to the opnsense-server but need NATing via the WAN interface. This was added as an automatic NAT Rule (Outbound) and working fine since 18.1.1. As the local (attached) networks are not affected, and NAT is working as it is supposed to be, the non-attached networks are not beeing NATed. As we also have two manual NAT rules we're using the hybrid mode. After adding an additional manual NAT rule for the non-attached networks, NAT is working again as expected. Attached is a screenshot of this. The last manual NAT rule fixes the issue for the non-attached networks in the last automatic-NAT rule.

Best
s256
![opnsense-nat](https://user-images.githubusercontent.com/1517486/36022925-0f559dd0-0d8b-11e8-8f65-df8e3d5b3d2e.jpg)

**Comment by fichtner** [comment]
hi @s256, was this solved in the meantime?

**Comment by s256** [comment]
hi @fichtner as I changed my employer who is not using opnsense, I can't tell you if this was fixed in the meantime. As I don't have the necessary infrastructure at home, I can't test it unfortunately.

**Comment by fichtner** [comment]
@s256 ok, thanks for the feedback. I'll close it then.
