### ISSUE TITLE
[Bug] Interface CIDR selection

### ISSUE THREAD

**Issue by tpcr** [opnsense/core#2185]
The CIDR selection on the Static IPv4 configuration in Interfaces is messed up.

**Comment by BeNeDeLuX** [comment]
Can confirm! -> Version 18.1.2

![cidr](https://user-images.githubusercontent.com/1895086/36066164-9ecbdf68-0ea5-11e8-8d35-379438ae6db1.JPG)

**Comment by fichtner** [comment]
People said this is firefox only?

**Comment by AdSchellevis** [comment]
@fichtner I'm looking into this at the moment, looks like a regression with white-space fix in the td https://github.com/opnsense/core/commit/d034df7b67eb3cc77253ac10eab70e6f2a2ddde9

**Comment by AdSchellevis** [comment]
found it, it's in https://github.com/opnsense/core/commit/a58dcf7cdfb40b377573917e38cdda72af37cea6 

https://github.com/opnsense/core/blob/master/src/opnsense/www/themes/opnsense/assets/stylesheets/main.scss#L369-L372

**Comment by AdSchellevis** [comment]
@fichtner I think this https://github.com/opnsense/core/commit/36022f8bdc4b40b99ecf7eab18a13b87c64ec031 is the intended behaviour. doesn't interfere with the rest of the dropdown widgets for as far as I can see and the alignment in the proxy page looks normal.

**Comment by fabianfrz** [comment]
Also looks OS specific as this is on ArchLinux:
![screenshot_20180211_210216](https://user-images.githubusercontent.com/3713914/36077746-d852c34a-0f6e-11e8-9867-621cba232c95.png)

As you can see it is at least readable but the scroll bar is still over the number.

**Comment by fichtner** [comment]
Looks good now, sorry for the breakage.
