### ISSUE TITLE
IPv6 Gateway monitoring when WAN is link local address only

### ISSUE THREAD

**Issue by marjohn56** [opnsense/core#2188]
A number of ISP's do not provide a global v6 address on the WAN, relying on a link-local between the user and the BNG, This appears to result in the gateway monitor not working. Generally I use an address out on the WAN as my target, googles IPv6 address or similar. This works perfectly fine on my own system as I have an ISP who provides me with a WAN global address. For two of my testers they get no v6 monitoring as they have no global WAN address.

So the question is this, is this the expected behaviour or is this a bug?

If this is the expected behaviour, because you cannot ping a WAN address from a link local then I have a work around which is to set the source address as the LAN IP in Apinger.conf.

I do not want to go down the path of creating this if it's a bug that needs fixing, but if it's not a bug then I will create a solution,

**Comment by marjohn56** [comment]
It appears we have a partial solution. By adding a new gateway and selecting LAN as the interface we can get a global monitor IP to work. Of course this leaves the existing gateway showing, disabling monitoring on that gateway then shows as green. It would be nice to hide that gateway but it's a cosmetic thing.

**Comment by fichtner** [comment]
I'm not sure I understand this completely. In the office I have a link local gateway and it works for monitoring automatically?

**Comment by nivek1612** [comment]
Is it a dynamic gateway created as a result of the dhcp6c request to the ISP or one you have created manually ?

**Comment by nivek1612** [comment]
Franco 
We get a ipv6 gateway allocated from the dhcp6 request to the ISP
But it remains pending. trying to add a monitor IP also has no effect the gateway still stays pending 
In apinger.conf there are no setting for the ipv6 gateway which explains the above 
If I manually add the setting to apinger.conf for target IP and source IP etc then it works after killing and restarting apinger
I can create a similar result (correct settings in apinger.conf) by adding a new gateway and specifing it as LAN gateway

**Comment by fichtner** [comment]
@nivek1612 it's a gateway that I get from rtsold... *sense has a custom patch for this which is in here:

https://github.com/opnsense/core/blob/master/src/etc/inc/interfaces.inc#L3232-L3235

It populates the files with a link-local gateway and that one is added to apinger correctly.

What's different in your case?

**Comment by marjohn56** [comment]
Those files are not created, that's what I've been trying to find. The issue I posted last week ans asked about the reason for the *v6 files being deleted, I though that was the reason, but I've bypassed the deletion and still the files do not get created, yet on my test system they do.

**Comment by fichtner** [comment]
did you replace rtsold ? maybe the second parameter is empty for the ISP, which would be.... very very nasty

**Comment by marjohn56** [comment]
Well the one ISP is Sky in the U.K. the other is Orange France, so it would not surprise me. I THINK I tried pf*** rtsold,  I know I had to re-compile it, but I don't remember sending it to Kev or Ned to test, I'll try that and see where it  takes us.

**Comment by fichtner** [comment]
we can add a log message to rtsold to diagnose this, or logging from the script using "${0} ${*}" that should show us all arguments...

**Comment by marjohn56** [comment]
I added a couple of extra echoes to the script, this is what finally told me that the *V6 outputs to /tmp  are not being created. The thing is when I had Sky as my ISP it was then that all the work on pf** was done as we found out from a Sky network engineer about needing dhcp6 before RS, if RS arrived first the BNG would reject any subsequent dhcp6c solicit, I am almost certain that we were seeing the *V6 echoed files.

**Comment by marjohn56** [comment]
There's something different about pf** rtsold,  I have compiled it, but when I run it it exits and this is in the log.

Feb 12 22:23:36 OPNsense rtsold[5081]: <interface_up> checking if igb1 is ready...
Feb 12 22:23:36 OPNsense rtsold[5081]: <interface_up> igb1 is ready
Feb 12 22:23:36 OPNsense rtsold[5081]: <rtsol_timer_update> set timer for igb1 to 0s
Feb 12 22:23:36 OPNsense rtsold[5081]: <probe_init> shutdown: Socket is not connected
Feb 12 22:23:36 OPNsense rtsold[5081]: <main> failed to setup for probing routers

**Comment by marjohn56** [comment]
Waiting for kev to get back to me on this, I have 'patched' the other sides version and we'll see if it makes any difference.

**Comment by marjohn56** [comment]
We have discusses this in another issue thread, we have a solution to rtsold if we need it. @fichtner Do you want to close this issue.

**Comment by abraxxa** [comment]
I just came across this issue when I was looking if one already exists.
My WAN interface is PPPoE, IPv6 via DHCPv6. The IPv6 gateway, which was added automatically, is displayed with only the link-local IPv6 under System/Gateways/Status missing the interface identifier.
On the dashboard in the interface widget it includes the interface identifier but the wrong one, re0 in my case which is the outside Ethernet interface on which the PPPoE is configured. pppoe0 would be the correct one.
Even if I edit the IPv6 gateway and enter the link-local IPv6 address followed by the interface identifier %pppoe0 the gateway becomes marked as offline although a ping6 on the cli is possible.

**Comment by marjohn56** [comment]
Have you ticked the 'Use v4 link' in the WAN interface dhcp6 section?

If not, tick it, save, apply. I then suggest a reboot -  then let us know if that makes any difference?

**Comment by abraxxa** [comment]
That did it, but a reboot was required, else the IPv6 connectivity including gateway monitoring worked, but IPv4 was broken.
What can we do to improve the help text of this option? I assume it''s always required when the IPv4 configuration type is some sort of tunneling.

**Comment by marjohn56** [comment]
No, it's not always the case, it's very dependant on the ISP.  

There's not enough room on the GUI to give a detailed description, but we could update the docs which don't have very much when it comes to ipv6.

**Comment by fichtner** [comment]
From what I know the original issue turned out to be a misconception so I'm closing this for clarity.

**Comment by abraxxa** [comment]
The docs and/or GUI info needs improvement.

**Comment by fichtner** [comment]
I agree, we do not have enough IPv6 setup info. This should probably be per provider, or at least with a table for provider-specific setup. Though for manual setups and small ISPs it will always be difficult...

**Comment by abraxxa** [comment]
What is the technical difference of this setting?

**Comment by marjohn56** [comment]
It routes the ipv6 traffic including dhcp6 solicits etc over the pppoe link. However, not all ISPs do it that way,   hence the option.

**Comment by marjohn56** [comment]
@fichtner Franco, I am happy to do a 'How to' IPv6 for Zen UK and Sky UK, what format should it take, a *.docx file or what?

**Comment by fichtner** [comment]
rst file for docs a la: https://docs.opnsense.org/manual/how-tos/ipv6_tunnelbroker.html

source: https://github.com/opnsense/docs/blob/9aa470246fff2bea8753c81a38279cb07f759e0b/source/manual/how-tos/ipv6_tunnelbroker.rst
