### ISSUE TITLE
Traffic Shaper: share bandwidth evenly is NOT working!

### ISSUE THREAD

**Issue by hutiucip** [opnsense/core#2191]
Hello!

Following the documentation/ how-to from https://docs.opnsense.org/manual/how-tos/shaper.html#share-bandwidth-evenly the only effect is that the limit set in pipe(s) is applied per client and not per total no. of clients, meaning each and every client is allowed to get up to that pipe limit, disregarding the total number of clients (eg. 1 Gb/s piped to 100 Mb/s will limit 1 client to 100 Mb/s, 2 clients to 100 Mb/s each, 5 to 100 each, 10 to 100 each - and above 10 clients there is no certainty that the bandwidth is evenly shared).

Further details from the forum:
https://forum.opnsense.org/index.php?topic=7235.0
https://forum.opnsense.org/index.php?topic=3966.0

Please investigate.
Thank you!

Ciprian

**Comment by mimugmail** [comment]
I'll have a look at this tomorrow.
Just one Q, your problem described is Not the same as in forum posts, right?

**Comment by hutiucip** [comment]
Hi Mimugmail!

Why would you ask that? :)
It is exactly as in the forum posts linked above, the rule(s) works partially, meaning the queues limit the bandwidth for each and every client to the value of the queue, but they are NOT limiting the **total** bandwidth allocated to all clients, neither share the bandwidth (any bandwidth) evenly. Neither the total available bandwidth, nor the bandwidth set in queue(s).

Thank you, and a nice day!

PS Also, the connection gets spiky when the shaper is on, despite the selected scheduler, or other settings. (Not related to this matter, but might have the same originating cause/ bug?!?! :-? )

**Comment by mimugmail** [comment]
@hutiucip 18.1.5 will have a fix for mask in queues .. if I remember this was also discussed in one of posts.
Not sure if this fixes your problem but I'm still on it :)

**Comment by hutiucip** [comment]
@mimugmail TY allot! :)

Everything above remaining as stated, I add some details, hope it helps:

Not changing anything except enabling/ disabling TS/ QoS, I have the follwing results:

1. TS disabled: http://www.dslreports.com/speedtest/31134518
2. TS enabled: http://www.dslreports.com/speedtest/31134551

The link is symmetrical 450/450. The load is very light: if I check the insider graph, for the last 2,5 hours there are spikes of 300 - 400 Mbps only when I test connection, otherwise the graph is below 50 Mbps. So, if a shape is to be expected with TS enabled, then my bandwidth should be of 50, up to 100 Mbps smaller - around 350 - 400, not 200 as in the above result. To be fair, BufferBloat is better with TS enabled (not by much, but it is), but the serios drop in BW makes TS unusable.

I really would like this function fixed, it's very very important for us to be able to shape the traffic and to give users a consistent quality of service, no matter the total load and/ or the individual allocated speed.

**Comment by mimugmail** [comment]
@hutiucip Ok, would you mind posting alle screenshots with advanced mode enabled regarding TS? Otherwise you can send them by mail :)

**Comment by hutiucip** [comment]
Exactly as in https://forum.opnsense.org/index.php?topic=7423.0 excepting I only use "Direction" = up/ down" in rules, not source/ destination IPs. I'll be right back with screenshots, it's OK to be posted here (it's one matter to know where something can be found, it's another matter to effectively have access to what you found ;) )

**Comment by hutiucip** [comment]
![rule-uld](https://user-images.githubusercontent.com/32258815/37645959-ffab7368-2c30-11e8-9f9f-aa9d5188823a.PNG)
![rule-dld](https://user-images.githubusercontent.com/32258815/37645960-ffcab76e-2c30-11e8-95e8-94c96e25cae4.PNG)
![pipe-uld](https://user-images.githubusercontent.com/32258815/37645977-0b39fd76-2c31-11e8-96df-42543668b01f.PNG)
![pipe-dld](https://user-images.githubusercontent.com/32258815/37645978-0b59d920-2c31-11e8-9d40-7bab3d33e450.PNG)

**Comment by hutiucip** [comment]
@mimugmail Hello, Michael!

I have read the patch notes for 18.1.5, and seen "firewall: respect mask in traffic shaper queue config (contributed by Michael Muenz)". I ask you, did you address the mask issue only for queues? Because I don't use queues - only used them for testing, I only want to share the bandwidth evenly (pipes), not further prioritize between services (queues) - and this ticket is about pipes, not queues. :)

I will repeat the tests later this day, but I want to be clear that the problem I have does NOT implies queues, only pipes and rules. And the evenly sharing of the bandwidth between connected clients is/ was malfunctioning in pipes. :)

**Comment by hutiucip** [comment]
OK, I have just tested with a coleague of mine, using only rules and pipes (as in https://docs.opnsense.org/manual/how-tos/shaper.html#share-bandwidth-evenly) and I can say for sure it's NOT working as intended:

- 450/ 450 symmetrical connection
- parallel DLD test: ~370 Mbps for me, ~80 Mbps for him
- parallel ULD test: ~218 Mbps for me, ~230 Mbps for him

Did the tests twice!
From these tests I can say that only destination mask (for download) is not working in pipes.

I will test again with queues also, and see if something changes.

**Comment by mimugmail** [comment]
Correct, the fix is only for queues. I'm was digging in TS and found this error, then I remembered your forum links where someone also was talking about disrespecting mask in queues. That's why I was writing here in the issue. 

I hope to find time next week since my lab is ready now with 2 computers and a firewall infront.

Thanks for your update and screens so I can easily reproduce then ...

**Comment by hutiucip** [comment]
@mimugmail I write again and cite you because I did add some LE and LLE to my previous comment, the conclusion being that there is no fix to that matter, nothing changed with this update. :)
I'm around here if you want further info or/ and help.

Thank you very much for your effort to fix this! :)

**Comment by mimugmail** [comment]
I'm currently reading this one .. quite good to understand the difference between mask ins pipe und mask in queues! 

https://www.hyperois.com/members/knowledgebase.php?action=displayarticle&id=1

```
Another very useful option is the mask option. It has the same syntax for both pipes and queues: add mask mask-specifier at the end of the config option. The effect is masking the packets and turning one flow into several flows, using the mask to establish which flow a packet belongs to. The default mask is empty, meaning all packets fall in the same flow. Using mask all would make all the fields be significant, meaning every TCP connection or UDP communication would be considered a flow.

For a pipe, each flow acts like it has a separate pipe, which is an exact clone of the original pipe: it has the same parameters. This means three active flows will use (for our example pipe) 360 kbits/s, meaning 120kbits/s each.

For a queue, the flows will act as several queues, with the same weight as the original one. This means you can use the mask to equally share a certain bandwidth. For our examples with three flows and the 120kbit/s pipe, each flow will get a a third of that bandwidth, namely 40 kilobits per second.
```

**Comment by mimugmail** [comment]
Ok, I've checked your screenshots and the new findings .. please set a pipe for each direction with max available bandwith. Scheduler MUST be WFQ2+, at first dont use CoDel. Then set a queue for each direction with weight of 100. For download mask destination, for upload source, then the rules like in your screenshot.

If there's no bug in FreeBSD or Shared forwarding this MUST work.

**Comment by mimugmail** [comment]
@hutiucip I was able to successfully test the evenly shared stuff in both directions. The problem is that the alg/scheduler needs some time to balance the connections. I did iperf tests and sometimes it needs 30 seconds until both streams are even. I thing this is related to internal timing but technically it's working.

**Comment by mimugmail** [comment]
The logic in pipe's works also like in the newly updated help texts or as in the posted link. So from my perspective this looks solved.

**Comment by hutiucip** [comment]
Hello again, @mimugmail :)

Thank you very much for your provided links and for your big effort! Really-really-really appreciating!... :)

Even if I didn't have the time to test it thoroughly, there are still issues, and I don't know now if it's an OPNsense bug, or FreeBSD bug, or TS implementation bug, but:

1. TS activated, WFQ Scheduler, no checkmarks for FQ-CoDel, no nothing, total/ effective speed/ bandwidth/ throughput is less then half of the total/ effective speed/ bandwidth/ throughput when TS is disabled - 450/450 TS disabled, 100 - 200 spikes, about 150 average throughput. If I reset/ disable -> enable TS then throughput rises to almost maximum, but only for a few (tens of) minutes. (I can't remember exactly, but I think there was another issue/ bug report about TS affecting effective throughput.)
2. No other scheduler type than WFQ works if queues are implied. If TS is configured with only pipes and rules (connected directly to pipes, doesn't matter if queues are created or not) any selected scheduler type produces effects on the _Firewall: Traffic Shaper: Status_. If queues are implied, created and linked to rules + referring to pipes, then the only scheduler type that produces live statistics on _Firewall: Traffic Shaper: Status_ is WFQ.

3. Still not sure (needs more tests) about the flows being equally shared for queues, and again for pipes (as described in the link you provided above), but so far I would say the evenly sharing of set maximum speed is still not working.

Sorry to be so negative :(, I really am sorry! :(
I will come back after I'll find the time for more in depth and thorough testing.

Have a nice day!

**Comment by mimugmail** [comment]
1. I'll reconfigure my lab for 10GB connection and test with higher speeds, no problem!
2. Yes, use Queues ONLY with WFQ, all other doesn't make any sense (to me), perhaps we need a validator (@AdSchellevis what do you think?)
3. Please test, for me it was fine, but me tests were with limited bandwidth because public speed test server vary from time to time.
4. Don't use masks in pipes and queues, this doesn't make any sense since you evenly share within a pipe but also copy the pipe to every flow ..

**Comment by AdSchellevis** [comment]
@mimugmail I guess you're right, the manual states `Pass packet to a dummynet ``queue'' (for bandwidth limitation using WF2Q+).`.

**Comment by fichtner** [comment]
What is the status here? Can this be closed?

**Comment by hutiucip** [comment]
Guys, sorry to inform, TS/ QoS for me is **not** working: all I could get, up to now, was a _total bandwidth limit_ and nothing more. No evenly shared bandwidth, no constant and max transfer speeds, no such thing.
More so, every once in a while, I see posts on forum claiming the same problems. A few days ago, a week or two at most, I received a private message from a forum user stating/ facing the same problems I have (maybe this is how he identified me as a possible helpful user).

So, no! For me for sure, and probably for several other users, this problem is not solved.

**Comment by fichtner** [comment]
So, what's the conclusion of this ticket? FreeBSD issue, OPNsense issue, documentation issue?
