### ISSUE TITLE
OpnSense 18.1.2 Host Aliases fail to load

### ISSUE THREAD

**Issue by JasonNaughton** [opnsense/core#2194]
Hi all,

Okay so I upgraded from 17.7.12 today to 18.1.2 and my host alias block will no longer be used as apart of the outbound NAT option.    I have a alias called ExternalIPs which consist of a pool of various IP addresses that my internal network will be translated to while going outbound.   In 17.7.12 this worked like a charm.   Now with the last update 18.1.2 I get the following logged error when attempting to use a Host Alias:

opnsense: /usr/local/etc/rc.filter_configure: New alert found: There were error(s) loading the rules: no IP address found for ExternalIPs

If I switch back to using only one translated IP address (from within the block that I had defined in the ExternalIPs) everything works fine but I'm now only translating to one IP address rather than the 63 that I had done with 17.7.12.

I've looked into /var/db/aliastables and the files ExternalIPs do show up:

/var/db/aliastables # ls -lh
-rw-r-----  1 root  wheel    32B Feb 12 12:31 ExternalIPs.md5.txt
-rw-r-----  1 root  wheel   854B Feb 12 12:31 ExternalIPs.self.txt
-rw-r-----  1 root  wheel   853B Feb 12 12:31 ExternalIPs.txt

The .txt and the .self.txt files essentially have a list of my external IP addresses one per line.

Any idea if there will be a 18.1.3 to fix this?

**Comment by AdSchellevis** [comment]
@JasonNaughton can you provide a bit more information so we can reproduce your issue? The exact type of alias used (and it's content), where is it used in the outbound rule.. some screenshots can also help.

**Comment by JasonNaughton** [comment]
The process to reproduce is very simple.

1) Create a host based alias

![5ebc214d-ff4b-49ba-baaf-f04b90ee0433](https://user-images.githubusercontent.com/11697795/36118159-12558eba-100a-11e8-8c02-2a84a035f439.jpeg)

2) Esseintally have one opnsense box with 2 interfaces which you wish to NAT from one to the other

3) Under the NAT Outbound specify the alias group as a translation target.  

Once you apply you will find that you will get the error that I produced above in your log files.  It seems that it doesn’t recognize the content of any alias group.

**Comment by JasonNaughton** [comment]
Here’s the outbound NAT rule.   I”m using manual.

![abffe864-8742-4eb1-a7b5-2be9b978f0f1](https://user-images.githubusercontent.com/11697795/36118362-c7003ee6-100a-11e8-9e40-e8cca7b8117d.jpeg)
![eb1ee634-d391-45e3-a5e2-bb306a6759f6](https://user-images.githubusercontent.com/11697795/36118363-c709e4e6-100a-11e8-87ef-b929fba20351.jpeg)

**Comment by AdSchellevis** [comment]
@JasonNaughton found it, can you test https://github.com/opnsense/core/commit/b5149928aa30288f91f12be556fd0992930d64b3 ?

`
opnsense-patch b5149928aa
`

**Comment by JasonNaughton** [comment]
Ok applied the patch this morning and we're now operational.  Thanks for the quick fix.

**Comment by fichtner** [comment]
@JasonNaughton thanks for confirming! adding this to 18.1.3 then :)
