### ISSUE TITLE
Reset WebGUI Certificate via shell

### ISSUE THREAD

**Issue by sedra-madina** [opnsense/core#2198]
i changed the Webgui certificate encryption to access the firewall thru web page and now i cant access any more as all browsers gives me that this ssl_error_no_cypher_overlap.

is there a way to change it to default via shell interface locally?

**Comment by fichtner** [comment]
Option 13 in the menu, revert to a good backup.

Cheers,
Franco

**Comment by sedra-madina** [comment]
Many thanks fichtner it worked

**Comment by fichtner** [comment]
great :)
