### ISSUE TITLE
firewall: alias nesting vs. geoip

### ISSUE THREAD

**Issue by fichtner** [opnsense/core#2199]
Adding a GeoIP alias "CH" and selecting "Switzerland" will make the alias fail to fetch any data.

This changed from 17.7 to 18.1 according to https://forum.opnsense.org/index.php?topic=7078.msg32856#msg32856

Do we add better validation or can we reenable this behaviour?

**Comment by AdSchellevis** [comment]
ok, this should work, https://github.com/opnsense/core/commit/cdae884ec970ab4d214ea8b28010c421c03ba018 makes sure we don't skip resolving when the content equals our alias name.

Only downside is that when someone defines an alias "CH" with static content and has an alias containing both "CH" and "NL" the static alias is preferred.

**Comment by fichtner** [comment]
Works, static preference sounds good. ❤️
