### ISSUE TITLE
Bug in Web GUI with interface named VPN

### ISSUE THREAD

**Issue by 0xFelix** [opnsense/core#2202]
This is only a small GUI bug, but when having an interface named "VPN" it is impossible to open its entry on the interface overview (status_interfaces.php). When clicking on the entry, instead of opening the entry the menu "VPN" in the sidebar is opened.

I found this bug in version 18.1.2.

**Comment by AdSchellevis** [comment]
@0xFelix thanks for reporting, fixed in https://github.com/opnsense/core/commit/8787a3200b98b33b28e2bd0565b9111c275adb3a

To try, use:
`opnsense-patch 8787a32
`

**Comment by 0xFelix** [comment]
Can confirm the patch works, thanks!
