### ISSUE TITLE
Issue: HTML Table <tr> background-color problem on some subpages

### ISSUE THREAD

**Issue by ghost** [opnsense/core#2205]
when creating a template I noticed that some subpages do have some problems with the background color representation of the tr-tags / table.
For example open a subpage of Interfaces like LAN or WAN or go to Firewall / Rules the background-color of the separated tr-tags of the html table are all shown in the same color (see my screenshot) and not in alternating color order.
only way to fix this is to resize the browser. then the background-colors of the tr-Tags are shown in their alternating order.
the problem exists in every browser (IE / FIREFOX / CHROME) and also still on the newest 18.7 dev version.
(see my screenshots) all tr-tags have the same background-color!
![interfaces](https://user-images.githubusercontent.com/35663978/36331877-05b2fd64-1370-11e8-9fe0-016df6fe97fe.JPG)
![rules](https://user-images.githubusercontent.com/35663978/36331878-05cba3fa-1370-11e8-92f2-facf9a2b29e4.JPG)

**Comment by opnsenseuser12123** [comment]
![temp1_problem](https://user-images.githubusercontent.com/35663978/36332402-60467ce0-1372-11e8-8e18-14fdbfaf1e2d.JPG)
![temp1_browser_resize_fix](https://user-images.githubusercontent.com/35663978/36332404-61dbbbec-1372-11e8-8693-37258f7bb1b9.JPG)

**Comment by AdSchellevis** [comment]
but then for v3 :)

**Comment by opnsenseuser12123** [comment]
No, its a Problem in every Template. Even on the one supplied with the product. Proof it yourself as described on my First Message.

**Comment by opnsenseuser12123** [comment]
I use the newest Firefox chrome and ie. Im Running this on Windows 10. i will Check that on Windows 7 again.

**Comment by opnsenseuser12123** [comment]
Ok, i testen this on a Windows 7 Machine using firefox / IE and on Apple iPad on Safari. The same Problem. Seems to be a presentation error. Perhaps there is a method to get rid of this Problem. I dont think this error only appears in opnsense. Has to do with the html table.

**Comment by fabianfrz** [comment]
@AdSchellevis I could reproduce and found the root cause:

There seems to be some kind of a hack to make a line break on mobile devices using two tr tags where one only contains the label and the label in the second will be hidden on a small screen.

For sure, the CSS class works but it styles hidden rows in that case and all visible rows gets the same background-color assigned.

**Comment by fichtner** [comment]
Static css zebra is not very clever. We can’t simplify our tables for it. Worst case we hide and show rows based on properties, it kills zebra layout order too.

This is futile to get right for all the static pages, but if the problem exists in MVC pages it’s worth improving. All help is welcome.

**Comment by AdSchellevis** [comment]
@fabianfrz flipping the columns to rows is handled using an additional JavaScript hook in https://github.com/opnsense/core/blob/master/src/www/javascript/opnsense_legacy.js#L82 and only applies to the legacy pages. I wasn’t able to reproduce the issue myself, but given how the tables in the legacy pages are constructed this is one of the few options available to render neatly on mobile.
The js code uses the striping that’s already there, maybe there is an event missing to force the hook, if the striping is back after resize (which triggers this hook).

**Comment by opnsenseuser12123** [comment]
If you add a new User (Access / users) there is no background tr Color too. even resizing doesnt help. The backround table Shows only one static color even on the latest dark theme....tested of course with the latest 18.7 dev version. There are a few more Pages that have the same Problem. Just Test this by yourself with any background-Color tr and you will see.

**Comment by fichtner** [comment]
I found the issue, but this is an ongoing effort.
