### ISSUE TITLE
Issue: HTML/CSS Template - Netmask pull down menu is cut off on the side

### ISSUE THREAD

**Issue by opnsenseuser12123** [opnsense/core#2208]
This Problem consists on every template on every page which has a netmask pull down menu and in every Browser (IE/Firefox/Chrome).
The pull down menu is to narrow. There is a scrollbar overlay. It gets cut off on the side!

![pull_down_menu](https://user-images.githubusercontent.com/35663978/36349701-acce564a-148b-11e8-8b0e-e641d38e9fb6.JPG)

**Comment by fichtner** [comment]
Already fixed in upcoming 18.1.3. please take the time to research tickets here before opening one.

**Comment by opnsenseuser12123** [comment]
ok.sorry
