### ISSUE TITLE
Unexpected behaviour with Traffic Shaping

### ISSUE THREAD

**Issue by kingfisher77** [opnsense/core#2210]
Following the how-to "Reserve dedicated bandwidth for VOIP":
https://docs.opnsense.org/manual/how-tos/shaper.html

Our bandwith is:
20 Mbit/s Upstream
200 Mbit/s Downstream

Our Traffic Shaping pipes are:
PipeUp-256Kbps (for VOIP-Device)
PipeUp-19744Kbps (for all internal networks)
PipeDown-256Kbps (for VOIP-Device)
PipeDown-199744Kbps (for all internal networks)

Rules set up accordingly.

Without Traffic Shaping we measure for downstream around 200Mbit/s and for Upstream around 20Mbit/s. Full bandwitdth.

With Traffic Shaping activated we measure for downstream around 110Mbit/s and for upstream around 18Mbit/s.

For Downstream its only around half of the bandwith.

Obviously the rules do something. If we reduce for example downstream for internal network to 1Mbit/s then this is what we measure.

What do we miss?

**Comment by hutiucip** [comment]
Me too! :)

**Comment by fichtner** [comment]
Docs have been updated... https://github.com/opnsense/docs/commit/64663c9fb26a7fb27b502c8f3f8ee9c5f6c0ee01
