### ISSUE TITLE
CLI Reference

### ISSUE THREAD

**Issue by brandonmreeves** [opnsense/core#2211]
We are planning on using the CLI to perform most administrative tasks on our Opnsense devices. Is there a CLI reference for the scripts that we could use to do this? We have been able to identify a few through detailed research like the new alias system, reloading interfaces etc.

Thanks
Brandon

**Comment by AdSchellevis** [comment]
Hi Brandon,

We don´t have a reference available, but the commands that are registered in configd can easily be found using 

`configctl configd actions [json]
`
Which basically lists all commands it can parse from /usr/local/opnsense/service/conf/ in plain or json format.
For most scenario's it's better to use the api endpoints (if available), since they offer both an update mechanism to the configuration as the possibility to trigger services.

Best regards,

Ad

**Comment by brandonmreeves** [comment]
Be glad to use the API. We initially thought of that. Is there a page of the API call references? We checked the docs and could not find the list of references with the exception of the firmware status and upgrade examples.

**Comment by brandonmreeves** [comment]
Let me clarify.
Using the interface, we were able to figure out some of the endpoints (ex. Firewall Log - see below). However, we would like to interact with the IDS(suricata) logs just like we do at the following endpoint:

/api/diagnostics/firewall/log

A couple things we would like to be able to do with the API
1.) Reset States
2.) Reboot / See Last Reboot date / status
3.) Modify Users
4.) Adjust Tunables
5.) Create Backup / Restore Backup
6.) Adjust DHCP (scope etc.)


There are a few more but those would be a good start.

We would be willing to start and maintain an API document if that would help.

The problem we are trying to solve:
We expect to deploy a number of Opnsense devices soon. We are developing scripts and interfaces to managed them in a way that is consistent and provides change control through a centralized user interface.

Note: If this undertaking (centralized mgmt etc.) is something the Opnsense team has interest in, we would be glad to work with the Opnsense team to provide the distributed management capabilities as part of the project. 

Thanks
Brandon

**Comment by AdSchellevis** [comment]
Hi Brandon,

Our endpoints are quite easy to figure out (using either your browser or fetching them from the controllers in GitHub), but are only available for modules which use our mvc framework (/ui/ and corresponding /api/ paths). 

API documentation for the features that are available, using something like slate (https://lord.github.io/slate/) could certainly be helpful, but is not at the top of our priority list at the moment.

Looking at your list of requirements, I don't think any of them are available using the api at the moment, which automatically means that once they are, calls will change. (Although some of the features are quite easy to move over)

For centralized management options we're looking at different technologies, when developing something yourself it's best to decouple as much as possible so you're able to cope with changes that will likely reach our product at a later stage. 
Step by step we're replacing components with ones that are (partial or fully) api capable, which in our opinion is a requirement for most managed scenarios.

Best regards,

Ad

**Comment by brandonmreeves** [comment]
Thanks. We are more than happy to test central mgmt etc. or support the project however possible.
