### ISSUE TITLE
Feature Request: Update maxbits 31 -> 32 in src/etc/rc.initial.setlanip

### ISSUE THREAD

**Issue by sazb** [opnsense/core#2213]
Hello

Could it be possible to update the maxbits of IPv4 from 31 to 32 in src/etc/rc.initial.setlanip (see below) ?

```
function console_configure_ip_address($version) {
...
$maxbits = ($version === 6) ? 127 : 31;
...
```
Hint Maybe to update for IPv6 but not tested so it's up to you :-)

I've already tried it on command line via sed (see below) and it works since (IPv4) far gateways are already coded and ready for use:

`sed -i.dist -e '/maxbits *=/ { s/31/32/; }' /usr/local/etc/rc.initial.setlanip`

Thanks in advance.

Kind Regards,

**Comment by fichtner** [comment]
@sazb thanks, looks reasonable. also fixes for IPv6. you can try the patch, but it's also likely in 18.1.5 soon:

    # opnsense-patch ef45114
