### ISSUE TITLE
Logrotate Suricata every 15m

### ISSUE THREAD

**Issue by brandonmreeves** [opnsense/core#2215]
We would like to logrotate suricata logs every 15 or 30 minutes and keep 4 copies due to sending it to another server via syslog. We only install a small cf card and we want to keep it from filling up. We tried performing the rotate every hour with 4 copies and the card was getting more full than we were comfortable with.

Can we get some advise on how to do this? Which file edits to make etc and we will create a plugin to make the necessary changes.

Thanks

**Comment by subfission** [comment]
Check out these, incase they might help:
```
/etc/newsyslog.conf.d/suricata
```
Additionally, the logrotator script includes a reference to this file, which does not exist by default.  You could drop your script into there as well:
```
/usr/local/etc/newsyslog.conf.d/*
```

Extras:
```
/usr/local/etc/suricata/suricata.yaml
/usr/local/etc/suricata/threshold.config
```

**Comment by fichtner** [comment]
Well, we do have a template for this and a few GUI settings... https://github.com/opnsense/core/blob/master/src/opnsense/service/templates/OPNsense/IDS/newsyslog.conf
