### ISSUE TITLE
radvd restarts cause windows clients to lose gateway

### ISSUE THREAD

**Issue by Korkman** [opnsense/core#2216]
# Problem

The generated "route" stanza in the radvd.conf with "RemoveRoute on;" causes Windows clients to lose their gateway and log "tcpip" event ID 4205 when radvd is restarted too often, which happens under real-life conditions configuring firewall settings. Affected Windows versions: Windows Server 2008 R2 and up to Windows 10.

What happens is that Windows counts route additions to a maximum limit of 100, but doesn't decrease said limit on route removal. When that limit is hit, all further route additions are ignored until the interface is reset or IPv6 is disabled and re-enabled in the interface options dialog.

The more routes configured the faster radvd restarts will kill off Windows clients.

# Suggested solution

Any of this would help, all should be done.

- Make "RemoveRoute" a checkbox in UI and set default to "RemoveRoute off;" until this Windows bug is properly fixed.

- Send SIGHUP instead of restarting radvd.

- Do not restart radvd when it is not necessary. I have observed radvd restarts when unbound DNS settings were changed, which seems totally unrelated to me.

# References

This limit has been introduced by Microsoft with this update:

https://support.microsoft.com/en-us/help/2750841/an-ipv6-readiness-update-is-available-for-windows-7-and-for-windows-se

For the curious, here is an radvd.conf (for Linux) triggering the bug on purpose:

[radvd-route-overload-demo.conf.txt](https://github.com/opnsense/core/files/1740668/radvd-route-overload-demo.conf.txt)

**Comment by fichtner** [comment]
This was the only report, we need more traction to be able to add permanent options to the GUI.
