### ISSUE TITLE
Automatically trim whitespace from input box fields

### ISSUE THREAD

**Issue by darkain** [opnsense/core#2217]
One of the most annoying issues I had with pfSense, and now having with OPNSense since migrating routers over is the lack of trimming text on input fields. For example, putting in any extra whitespace at the beginning or end of a MAC address or IP address field results in an error and having to go back to correct it, instead of just trimming the additional characters and processing like normal.

This is most commonly occurring when copy-pasting the addresses (or really, any field data) from other web based administration consoles that use tables. If the cursor selection for the address on the other administration page was too far to the left/right, it'll include an additional TAB character.

**Comment by fichtner** [comment]
Some fields in MVC have special validation to avoid this, but most of the static pages do not do this at all. Nothing we want to change in old code that is too hard to maintain and eventually removed.

**Comment by darkain** [comment]
I'm confused. What part of this is being removed? The page in question is the DHCP static IP address UI page. Why would any of that be removed? Also, what is complex about running trim() on GET/POST data, to help provide a better UX for end-users?

**Comment by fabianfrz** [comment]
The entire page will be removed and replaced by a MVC variant when the time is ready (static page is almost any page containing ".php" in the URL while the new pages contain "/ui" in the URL).

**Comment by doktornotor** [comment]
Can we please revisit this? MVC migration or not, this results in super-annoying validation errors, e.g. when pasting aliases.

**Comment by AdSchellevis** [comment]
@doktornotor yes and no, we're not going to cleanse the actual input as a space is a regular character and we would interfere with with the normal storage pattern. The pasting issue however can likely be fixed easily with https://github.com/opnsense/core/commit/547c97a93192a4b6ad8150a0d4c6e91c6da6bc5e , in my humble opinion this isn't a backend issue and should thus be fixed where it originates from.

**Comment by doktornotor** [comment]
Kinda confused how it is supposed to be fixed where it originates from. The problem is described pretty exactly in the original report, There are areas where it always makes sense to trim any whitespace from input (or treat it as a delimiter) - such as IPs, subnets etc. 

On a more generic note, the inability to edit anything in these types of input fields does not help. I need to find and remove the offending entries and re-add them again.

**Comment by AdSchellevis** [comment]
ok, then I'll patiently wait for a PR which fits the earlier described boundaries.

**Comment by doktornotor** [comment]
So with https://github.com/opnsense/core/commit/547c97a93192a4b6ad8150a0d4c6e91c6da6bc5e applied - am I supposed to  somehow edit `mvc/app/Views/OPNsense/alias/alias.volt` to get the whitespace trimmed on paste, or... ?

**Comment by AdSchellevis** [comment]
on input fields, yes, on tokenizers, no. likely also fixable, but not related to the (generic) question. I can point you in the direction, but already starting to regret spending time on the subject.

**Comment by doktornotor** [comment]
Well if that's something that could eventually get merged I'd be happy to spend some time to get this improved. If whitespace trimming is generally undesired, then I'd rather not maintain local patches.

**Comment by AdSchellevis** [comment]
cleansing the "paste" action is fine, to be honest, your specific use-case likely only needs a trim() here :

https://github.com/opnsense/core/blob/5280cb346bc40fe9dc221dcdae6c9eb4543de74e/src/opnsense/www/js/opnsense_ui.js#L366


90% of the other inputs just use an input field, which is what my commit cleanses when being pasted. I'm for good reasons not a fan of sending `A` to an endpoint and storing `B`, it's asking for future issues. data is either acceptable or it's not.
