### ISSUE TITLE
LDAP Configuration : Unsafe url characters are not encoded

### ISSUE THREAD

**Issue by diode** [opnsense/core#2218]
OPNsense version : 18.1

## Issue
There is a minor issue in LDAP Configuration UI.
Passwords that contain unsafe url characters ( @, # etc. ) will break query string, and as a result **system_usermanager_settings_ldapacpicker.php** shows "Could not connect to LDAP server".

## Steps to reproduce

1. Try to create an LDAP configuration > System: Access: Servers
2. Fill all required fields and set password as AB#CDEF@GH

### Result
This password breaks the query string, and unexpected results are shown
e.g: Instead of ldap:// it connects to ldaps://

### Workaround
Use url encoded password for listing **Authentication containers**
So AB%23CDEF%40GH instead of AB#CDEF@GH
After selecting **Authentication containers** in the UI revert password back to original (AB#CDEF@GH) and save.

![image](https://user-images.githubusercontent.com/1157204/36470873-65a70fbc-1712-11e8-8a00-a42fea659a44.png)

**Comment by AdSchellevis** [comment]
Passing the parameters in a get type request was stil something which we needed to  replace, so let's fix this now and keep the dialog on the same page while switching to a post type request. 
![image](https://user-images.githubusercontent.com/9783985/36693864-d5a82976-1b3c-11e8-94f1-097c8c9e8d3c.png)
