### ISSUE TITLE
OpenVPN's AES-NI Visibility

### ISSUE THREAD

**Issue by sjorge** [opnsense/core#222]
There doesn't seem to be a way to select aes-ni crypto-accelleration for OpenVPN.
Depending on the LibreSSL/OpenSSL used for OpenVPN it should work automatically if the compatible cyper suite is selected.

Having the option to select aes-ni as crypto-accellerator would be nice, selecting this should then just limit the cyphers that are selectable to the supported ones.

**Comment by fichtner** [comment]
"System: Settings: Miscellaneous: Cryptographic Hardware" doesn't work?

**Comment by sjorge** [comment]
Oh there are 2 locations, I saw one on the OpenVPN page too but it was missing there. Maybe consolidate those?

**Comment by fichtner** [comment]
One is the system setting underneath FreeBSD's cryptodev (AES-NI, Geode LX SB), the other is OpenVPN asking/saying please use it: OpenSSL only propagates "cryptodev", which is what OpenVPN cares about. Not sure what to do.

**Comment by sjorge** [comment]
Perhaps have the default entry for OpenVPN page be 'Use system cryptodev', so if that is set to none, none is used, if it is set to aes-ni, that is used,... you can then pick an alternative one on the page ?

**Comment by fichtner** [comment]
A bit more code but sounds reasonable. Not sure what happens since cryptodev is in the kernel by default and aesni is loaded when enabled. Will try that some time, thanks so far.

**Comment by sjorge** [comment]
Optionally maybe mark/restrict the aes-ni supported cypher suits everywhere when you can select them if it is being used. Since if you select a wrong one it will not be used and there won't be a indication of that.

**Comment by fichtner** [comment]
For OpenVPN, AES-NI is never directly advertised as it used the OpenSSL engine's crpytodev /dev/crypto but on LibreSSL the cryptodev is no longer available. I have to mark this wontfix for reasons of this indirection.

**Comment by h-2** [comment]
Sorry for digging this up. I just recently installed OpnSense. After upgrading from OpenSSL to LibreSSL flavor "Hardware Crypto" now reads "No Hardware crypto acceleration", but before the change it offered hardware crypto. Does this mean LibreSSL never supports hardware crypto or that it is always on by default.... and is there some way I can check?

**Comment by h-2** [comment]
Thanks for the quick reply!

> AES-NI is automatic if you select the respective AES ciphers. 

I have aesni, can I check on the command line if it works? e.g. Is there something I can pass to `/usr/local/bin/openssl speed` to explicitly (de)activate the hardware backend?

**Comment by fichtner** [comment]
See this thread: https://forum.opnsense.org/index.php?topic=2379.0

Test with AES-NI:

    # /usr/local/bin/openssl speed -evp aes-128-cbc

Test without AES-NI:

    # /usr/local/bin/openssl speed aes-128-cbc

**Comment by fichtner** [comment]
For LibreSSL it seems that AES-NI is even used without "-evp" envelope mode

**Comment by fichtner** [comment]
Values on an A10:

```
% /usr/local/bin/openssl speed -evp aes-128-cbc
Doing aes-128-cbc for 3s on 16 size blocks: 8338911 aes-128-cbc's in 3.00s
Doing aes-128-cbc for 3s on 64 size blocks: 2391469 aes-128-cbc's in 3.01s
Doing aes-128-cbc for 3s on 256 size blocks: 624482 aes-128-cbc's in 3.04s
Doing aes-128-cbc for 3s on 1024 size blocks: 157032 aes-128-cbc's in 2.99s
Doing aes-128-cbc for 3s on 8192 size blocks: 19953 aes-128-cbc's in 3.06s
LibreSSL 2.6.4
built on: date not available
options:bn(64,64) rc4(ptr,int) des(idx,cisc,16,int) aes(partial) idea(int) blowfish(idx) 
compiler: information not available
The 'numbers' are in 1000s of bytes per second processed.
type             16 bytes     64 bytes    256 bytes   1024 bytes   8192 bytes
aes-128-cbc      44474.19k    50885.49k    52604.18k    53740.20k    53373.05k
```

```
% /usr/local/bin/openssl speed aes-128-cbc
Doing aes-128 cbc for 3s on 16 size blocks: 8769293 aes-128 cbc's in 3.00s
Doing aes-128 cbc for 3s on 64 size blocks: 2437747 aes-128 cbc's in 3.05s
Doing aes-128 cbc for 3s on 256 size blocks: 623840 aes-128 cbc's in 3.06s
Doing aes-128 cbc for 3s on 1024 size blocks: 160645 aes-128 cbc's in 3.10s
Doing aes-128 cbc for 3s on 8192 size blocks: 19378 aes-128 cbc's in 3.01s
LibreSSL 2.6.4
built on: date not available
options:bn(64,64) rc4(ptr,int) des(idx,cisc,16,int) aes(partial) idea(int) blowfish(idx) 
compiler: information not available
The 'numbers' are in 1000s of bytes per second processed.
type             16 bytes     64 bytes    256 bytes   1024 bytes   8192 bytes
aes-128 cbc      46769.56k    51205.19k    52147.93k    53037.94k    52777.42k
```

**Comment by fichtner** [comment]
Grr, no, these values are without AES-NI... wtf...hopefully openssl works as expected :)

**Comment by h-2** [comment]
> Grr, no, these values are without AES-NI... wtf...hopefully openssl works as expected :)

Exactly, it seems *LibreSSL does not use hardware crypto*. I will open a new issue for this.

**Comment by fichtner** [comment]
Thanks for the pointer. It used to work on 2.5 and none of the code that we manage seemed to have caused this so it's probably in the portable version of LibreSSL... :/
