### ISSUE TITLE
CloudVPS keeps signing out ever since upgrading to 18.1.x

### ISSUE THREAD

**Issue by rene-demonsters** [opnsense/core#2220]
So here's an interesting one... We rent a couple of VPS servers over at CloudVPS. CloudVPS has their own management dashboard over at https://interface.cloudvps.com. This management dashboard used to work just fine up until we upgraded to 18.1. Ever since then we're having issues signing into their interface (works about 3 out of 5 times) and we keep being signed out between 2-5 clicks when navigating through pages.

I've been able to confirm the issue is related to the firewall somehow, since the the interface works fine when I switch on a VPN or tether my Macbook over my phone. I've tried this across multiple different browsers on multiple devices and I keep seeing the same issue when the firewall is in play.

I'm not sure what information would be useful to debug this issue or how to obtain it, so please let me know what you guys would like to see and I'll get the required information. I've already checked the Chrome logs and there's nothing in there that's relevant, I see the same warnings both with and without VPN. But for good measure I've included them.

```
[Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
```

```
Ractive.js: Missing "" transition plugin. You may need to download a transition via http://docs.ractivejs.org/latest/plugins#transitions
```

I've already contacted CloudVPS about this issue, they told me they didn't have any experience with OPNsense and couldn't help me any further.

**Comment by fraenki** [comment]
I'd assume that this is related to the new NAT behaviour in 18.1.
[This post](https://forum.opnsense.org/index.php?topic=7323.0) describes a workaround and 18.1.3 might fix it automatically be re-enabling sticky outbound NAT.

**Comment by rene-demonsters** [comment]
@fraenki Thanks, I've just enabled Sticky Outbound NAT and that solves the problem. However it has picked our IP starting with 178, rather than the 84 one to stick with. Where can I change that to the one starting with 84?

**Comment by fichtner** [comment]
Should work with manual or hybrid outbound rules where you can specify it.

**Comment by rene-demonsters** [comment]
I've switched to the hybrid outbound rule and set it to use that specific IP regardless of source or destination. That seems to do the trick. Thanks for the help, I'll close the ticket.
