### ISSUE TITLE
dhcp network boot uefi 64 bit broken

### ISSUE THREAD

**Issue by kevemueller** [opnsense/core#2223]
Using OPNSense 18.1.2, https://opn.sense/services_dhcp.php?if=xxx1

The UI allows providing different boot files for Legacy BIOS/EFI IA32/UEFI X86_64 bit which make it into the dhcpd configuration file.
```
  if option arch = 00:06 {
    filename "EFI32";
  } else if option arch = 00:07 {
    filename "EFI64";
  } else {
    filename "BIOS";
  }
```
This switch is unfortunately broken. https://tools.ietf.org/html/rfc4578#section-2.1 lists the architectures, 7 is EFI BC, the correct code for 64 bit is **9**.
A UEFI64 bit request is served the catch-all BIOS filename.

The switch should read: 
```
  if option arch = 00:06 {
    filename "EFI32";
  } else if option arch = 00:09 {
    filename "EFI64";
  } else {
    filename "BIOS";
  }
```
_Ideally_ the UI should present with a dynamic option list with architecture drop-down and filename, to support the exotic OS options as well, but for me the above fix is sufficient.

**Comment by AdSchellevis** [comment]
In case one of the exotic variants pop-up, we'll see, we can't really fix that quickly without breaking old logic. I'll replace the architecture like suggested and close the issue with my commit.
