### ISSUE TITLE
API PHP Exception: SystemhealthController.php:281

### ISSUE THREAD

**Issue by squadramunter** [opnsense/core#2228]
Hello I have some trouble with seeing health information on my OpnSense.

`Error at /usr/local/opnsense/mvc/app/controllers/OPNsense/Diagnostics/Api/SystemhealthController.php:281 - A non-numeric value encountered (errno=2)`

Anybody have an idear what is going on here?

This error occurs when I toggle the Inverse option on and off. If it is off then all is fine but when I toggle it on I got that error.

![health1](https://user-images.githubusercontent.com/26835124/36797975-aa2968fa-1ca9-11e8-984a-f715e3199a0c.PNG)

Do you know why I don't get any packet data? It did work before the new Gecko release.

![health2-problem](https://user-images.githubusercontent.com/26835124/36797976-aa470cc0-1ca9-11e8-9dc6-0ae7ad5ac6ff.PNG)

Detailed log:

`[28-Feb-2018 16:57:28 Europe/Amsterdam] Exception: Error at /usr/local/opnsense/mvc/app/controllers/OPNsense/Diagnostics/Api/SystemhealthController.php:281 - A non-numeric value encountered (errno=2) in /usr/local/opnsense/mvc/app/controllers/OPNsense/Base/ApiControllerBase.php:85
Stack trace:
#0 /usr/local/opnsense/mvc/app/controllers/OPNsense/Diagnostics/Api/SystemhealthController.php(281): OPNsense\Base\ApiControllerBase->APIErrorHandler(2, 'A non-numeric v...', '/usr/local/opns...', 281, Array)
#1 /usr/local/opnsense/mvc/app/controllers/OPNsense/Diagnostics/Api/SystemhealthController.php(576): OPNsense\Diagnostics\Api\SystemhealthController->translateD3(Array, true, Array)
#2 [internal function]: OPNsense\Diagnostics\Api\SystemhealthController->getSystemHealthAction('ipsec-packets', '0', '0', '120', true, '1')
#3 [internal function]: Phalcon\Dispatcher->callActionMethod(Object(OPNsense\Diagnostics\Api\SystemhealthController), 'getSystemHealth...', Array)
#4 [internal function]: Phalcon\Dispatcher->dispatch()
#5 /usr/local/opnsense/www/api.php(26): Phalcon\Mvc\Application->handle()
#6 {main}`

I hope this issue can be fixed ASAP.

Greetings,

SquadraMunter 👍

**Comment by AdSchellevis** [comment]
your rrd data is likely corrupt, you can flush it under reporting ->settings, although it shouldn't crash on invert when there's nothing to invert... I'll need to look at that

**Comment by squadramunter** [comment]
Do you know what causes this corruption?

**Comment by squadramunter** [comment]
Just flushed my rrd data hopefully it works again 👍

**Comment by AdSchellevis** [comment]
maybe a power failure on your machine, ufs isn't very solid when crashes happen

**Comment by AdSchellevis** [comment]
https://github.com/opnsense/core/commit/048f3d0b4faef0f9fde4e6f2b602015ab61be08b should fix the "non-numeric" error. I'll close the issue, feel free to reopen when the issue remains.

**Comment by squadramunter** [comment]
I waited one day and the issue remains. The solution you provided did not work.
