### ISSUE TITLE
Feature Request: Route Based VPN 

### ISSUE THREAD

**Issue by rhysxevans** [opnsense/core#2229]
Hi

Ths would be great - as per https://forum.opnsense.org/index.php?topic=6745.0 

Is there the possibility to support route based VPN's ? This is becoming more prevelant when connecting to specific cloud providers (ie Azure)

IE: (I haven't verified any of the links as working implementations)
https://genneko.github.io/playing-with-bsd/networking/freebsd-vti-ipsec
https://wiki.strongswan.org/projects/strongswan/wiki/RouteBasedVPN
https://vincent.bernat.im/en/blog/2017-route-based-vpn

Thoughts ?

**Comment by mimugmail** [comment]
If you have a running config this should be easy to implement

**Comment by ccesario** [comment]
Hello, is it working into 18.7.2 ?

**Comment by fichtner** [comment]
No, no work was contributed as of yet.

**Comment by fichtner** [comment]
Same as #2332
