### ISSUE TITLE
Add sslh as a service

### ISSUE THREAD

**Issue by sjorge** [opnsense/core#223]
It would be nice to have sslh (http://www.rutschle.net/tech/sslh.shtml) as a service, or even as an option for a port forward rule. It's great to forward for example wan:443 to a ssh server, https server, openvpn server and something else (RDP for example)

Ofcourse you can use it on many ports, so having the option to configure multiple instances would be a must. (Hench the suggestion to have it under port forward as an option, it could then just spawn copies for each rule like you would with a proxy program)

**Comment by fichtner** [comment]
Should be a plugin. No ETA.

**Comment by fichtner** [comment]
This never popped up again, I'm closing this in favour of other issues.

**Comment by sjorge** [comment]
Hey @fichtner can the package be added to the opnsense repository? It is in the upstream freebsd one, that should help getting this as a plugin.

**Comment by sjorge** [comment]
Alright so I got the package installed via 'pkg add' from the freebsd repo...
Going to try another migration to opnsense with manual configure sslh, if it works well I should be able to look at this again.

**Comment by fichtner** [comment]
@sjorge 17.1.6 has the native package https://github.com/opnsense/tools/commit/4008167d

**Comment by sjorge** [comment]
Nice that will make it a bit easier, once everything is running smoothly with a manual config I'll look into turning it in a plugin. Some other bugs to get sorted before that though.

**Comment by dkowis** [comment]
Did it ever make it to a plugin?

**Comment by sjorge** [comment]
No, I couldn’t figure out the plugin stuff. I just install the package manually now and use it that way.

**Comment by mimugmail** [comment]
When you add a feature request in plugins repo I can add it next year, doesn't seem to be very complicated.
