### ISSUE TITLE
wccp support

### ISSUE THREAD

**Issue by unicorn667** [opnsense/core#2230]
Hi @all,

it´s possible to add wccp support to the squid proxy? We want  continue to use our "interscan web security virtual appliance" from trendmicro.

Best

**Comment by fichtner** [comment]
Hi @unicorn667,

The port has WCCP support built-in, so I assume you mean adding the feature to the GUI?

```
% pkg info squid | grep WCCP
	WCCP           : on
	WCCPV2         : on
```

What would a configuration look like?


Cheers,
Franco

**Comment by mimugmail** [comment]
You would also need a GRE Tunnel to the system, but this is for plain wccp without the need for squid, like with Cisco Routers

**Comment by fabianfrz** [comment]
https://wiki.squid-cache.org/Features/Wccp2#Squid_configuration_for_WCCP_version_2

**Comment by mimugmail** [comment]
@unicorn667 Does the TM act like a wccp endpoint or is there also an option for upstream proxy usage?

**Comment by unicorn667** [comment]
Hi,

thanks for all replays on my thread.

Please look here for wccp and tm integration

https://supportforums.cisco.com/t5/security-documents/asa-wccp-step-by-step-configuration/ta-p/3126636

It runs very fast and stable and blocks content that violent company policy. I don´t want to change this setting when i move to opnsense.

A GUI entry where very nice for that. 

I think i will do a lab installation and will test it.

**Comment by fichtner** [comment]
Keep or close?
