### ISSUE TITLE
API PHP Exception: SystemhealthController.php:281

### ISSUE THREAD

**Issue by squadramunter** [opnsense/core#2231]
API PHP Exception: SystemhealthController.php:281

Hello I have some trouble with seeing health information on my OpnSense.

`Error at /usr/local/opnsense/mvc/app/controllers/OPNsense/Diagnostics/Api/SystemhealthController.php:281 - A non-numeric value encountered (errno=2)`

Anybody have an idear what is going on here?

This error occurs when I toggle the Inverse option on and off. If it is off then all is fine but when I toggle it on I got that error.

![health1](https://user-images.githubusercontent.com/26835124/36797975-aa2968fa-1ca9-11e8-984a-f715e3199a0c.PNG)

Do you know why I don't get any packet data? It did work before the new Gecko release.

![health2-problem](https://user-images.githubusercontent.com/26835124/36797976-aa470cc0-1ca9-11e8-9dc6-0ae7ad5ac6ff.PNG)

Detailed log:

`[28-Feb-2018 16:57:28 Europe/Amsterdam] Exception: Error at /usr/local/opnsense/mvc/app/controllers/OPNsense/Diagnostics/Api/SystemhealthController.php:281 - A non-numeric value encountered (errno=2) in /usr/local/opnsense/mvc/app/controllers/OPNsense/Base/ApiControllerBase.php:85
Stack trace:
#0 /usr/local/opnsense/mvc/app/controllers/OPNsense/Diagnostics/Api/SystemhealthController.php(281): OPNsense\Base\ApiControllerBase->APIErrorHandler(2, 'A non-numeric v...', '/usr/local/opns...', 281, Array)
#1 /usr/local/opnsense/mvc/app/controllers/OPNsense/Diagnostics/Api/SystemhealthController.php(576): OPNsense\Diagnostics\Api\SystemhealthController->translateD3(Array, true, Array)
#2 [internal function]: OPNsense\Diagnostics\Api\SystemhealthController->getSystemHealthAction('ipsec-packets', '0', '0', '120', true, '1')
#3 [internal function]: Phalcon\Dispatcher->callActionMethod(Object(OPNsense\Diagnostics\Api\SystemhealthController), 'getSystemHealth...', Array)
#4 [internal function]: Phalcon\Dispatcher->dispatch()
#5 /usr/local/opnsense/www/api.php(26): Phalcon\Mvc\Application->handle()
#6 {main}`

I hope this issue can be fixed ASAP.

Greetings,

SquadraMunter 👍

**Comment by fichtner** [comment]
Well, do you have IPsec traffic? Here's mine...

<img width="1104" alt="screen shot 2018-03-01 at 4 59 04 pm" src="https://user-images.githubusercontent.com/1915288/36854738-fb387312-1d71-11e8-9964-d06dd00c88fd.png">

**Comment by squadramunter** [comment]
Pls look at https://github.com/opnsense/core/issues/2228

**Comment by squadramunter** [comment]
No I have no IPsec traffic. I upgraded OpnSense to the latest version 18.2 but before that upgrade all things works just fine.

**Comment by fichtner** [comment]
if you open a new ticket, please provide the details or reopen your old one

**Comment by squadramunter** [comment]
How can I reopen the old one?

**Comment by fichtner** [comment]
why switch tickets again? ;)

I don't understand your report. I open the page, select ipsec, toggle invert a couple of times. data is always there. no error with fix on #2228.

**Comment by squadramunter** [comment]
I don't know? Maybe this problem is a power failure?

**Comment by squadramunter** [comment]
I only see dots nothing more can you help me to solve this problem?

**Comment by fichtner** [comment]
you need to help us reproduce, otherwise we can't do anything :(

**Comment by fichtner** [comment]
maybe to stress this point? why are you expecting data on ipsec when you don't have ipsec?

**Comment by squadramunter** [comment]
ipsec?

**Comment by squadramunter** [comment]
I don't see ipsec package or plugin that is installed on my opnsense

**Comment by squadramunter** [comment]
I can try to backup my OpnSense configuration and exclude the RRD data. After that I can do a factory reset and then import my configuration and fingers crossed that this solve the problem.

**Comment by fichtner** [comment]
right now, you are showing a screenshot for ipsec traffic, expecting ipsec traffic visualisation to be shown but have no ipsec so the graph will *always* be empty.

I really cannot help because that's how it works unless I am misunderstanding.

**Comment by squadramunter** [comment]
I have normal internet access. And monitor everything else does work tho

**Comment by fichtner** [comment]
I'm sorry, I still don't understand without context. Gaps can happen when you reboot or the firewall is offline. You've given no time base or context where you expect traffic to be show despite the graph being blank. In the last picture you crop the time axis.... it's impossible to help you under these conditions and I can't spend all my time on one person today.

**Comment by squadramunter** [comment]
Oh wait now I know what you mean about ipsec that is VPN based traffic. Sorry about that. But still this is strange when I have no data that it gives me a error even when I use that toggle option.

**Comment by fichtner** [comment]
Did you apply the patch @AdSchellevis provided?

**Comment by squadramunter** [comment]
no how can I apply that patch manually?

**Comment by fichtner** [comment]
# opnsense-patch 048f3d0

**Comment by squadramunter** [comment]
yes the patch does work. I tested it out and can say that the patch now does work as it should do. When I toggle that inverse button no API error happens.

**Comment by fichtner** [comment]
Ok, nice. can we clone then? :)

**Comment by squadramunter** [comment]
I think you can close this issue 🥇

**Comment by fichtner** [comment]
Thanks!
