### ISSUE TITLE
IPv6 tunable net.inet6.ip6.use_tempaddr has no effect

### ISSUE THREAD

**Issue by stackcoder** [opnsense/core#2236]
I've tried to setup OPNSense using [IPv6 privacy addresses](https://en.wikipedia.org/wiki/IPv6#Privacy). Since these are [not enabled by default](http://ipv6int.net/systems/freebsd-ipv6.html#privacy) in FreeBSD I set the specific tunable on the `System > Settings > Tunables` (/system_advanced_sysctl.php) page. After various attempts to renew the DHCP lease and rebooting the whole system it still uses the MAC address as Interface Identifier. Applying `net.inet6.ip6.prefer_tempaddr` had also no effect.

Not sure which dhcp client is used here, the WIDE DHCPv6 (KAME) does [not support temporary addresses](https://github.com/opnsense/ports/blob/6428bbb34fe02af567837c54e2b0219c017532f2/net/dhcp6/pkg-descr). 

Affected version: at least 18.1.2

Where does this setting apply?
Can I simply use the icd-dhcpv6-client here?

We have several options like IP Normalization per firewall rule to protect privacy, so I think this should be supported as well.

**Comment by fichtner** [comment]
It’s not a good idea to change this on the router as it causes its IPv6 to shift likely causing disruption for clients. Case studies with different findings are welcome though :)

**Comment by stackcoder** [comment]
Clients don't care about which address is used by opnsense to communicate with the world. Even in case of NAT the clients never notice any public IP address. That's why we can build _gateway groups_. Also IPv4 addresses of dial-up connections are changed periodically. So this should no issue.
