### ISSUE TITLE
Switching off core dump

### ISSUE THREAD

**Issue by kingfisher77** [opnsense/core#2237]
Recently we had the file system full on `/dev/ufs/OPNsense0`. We found out that there were some core dumps lay around in different locations. The biggest was from ntpd with a size about greater then 600MB. We deleted them and the side effects from a filled up file system disappeard.

The question is: can we configure the kernel to not write core dumps by adding `kern.coredump=0` in `/etc/sysctl.conf`? Is it save do do it in Opnsense?

**Comment by fichtner** [comment]
sysctl.conf is operated by System: Settings: Tunables. No issues with adding it there.
