### ISSUE TITLE
DHCP Serving multiple subnets to remote networks (vlans), not directly connected

### ISSUE THREAD

**Issue by githubatf2f10** [opnsense/core#2238]
Hi Wonder team here!!

I am in a project with an opportunity of replacing Windows AD/DHCP/DNS stuff with BSD/Linux. I have to do it piece by piece.

I plan to have one LAN only with CARP serving as default Gateway for all company's outgoing traffic. This only LAN will be something like, 10.16.229.0/29 with one IP for Primary OpnSense and another for Secondary and a VIP.  I prefer to not have DHCP on this VLAN, becase all these IP are only for OpnSense to use; however, if I have to enable it for the purpose of getting my following purpose served, it's ok for me to enable DCHP on this VLAN as well. The rest of LANs (VLANs) will be on the remote Cisco access switches. They are not directly connected to OpnSense. Otherwise, I can to extend those VLANs across mutiple switch/links to OpnSense, which will be a mess with STP. I'd like to use Layer 3 Routing on those switches to take care of routing to get those remote VLANs.

Instead of setting up another pair of DHCP/DNS server to serve remote VLAN network with centralized pool of multiple subnets, just like what Windows DHCP server does, I'd like to utilize OpnSense's DHCP/DNS function to do this. I don't like to get these remote VLANs directly connecting to OpnSense which complicates things with STP on all switches across the whole company.

For DNS part,  I assume by just pointing to remote DHCP client pc with a DNS IP option with DHCP server, it would work. Correct?

For DHCP server handling out multiple subnets based on remote VLANs interface IP as source of DHCP request, it seems hard to get it set up. All my switches with those VLANs will have Cisco "ip dhcp helper x.x.x.x" configured on Layer 3 VLAN (with one IP  and IP subnet configured on VLAN). When client do DHCP request, this helper will forward that to DHCP server x.x.x.x with source IP of this VLAN's IP.  Windows DHCP server can assign pool of ip subnets well based on IP Helper's source IP.

When I tried do this on OpnSense LAN, I find out no way of doing this. Even I enable DHCP server on this LAN, the additional pool range must be within this LANs Interface subnet. 

However, base on the bottom of this post, https://community.spiceworks.com/topic/1331562-isc-dhcp-server-for-multiple-vlans

Only thing we need to to get it isc-dhcp server working for this purpose, is to add this simple declaration within dhcpd.conf.

Quote
##This subnet is the one that the DHCP server is in, has to be here in order 
##the server to hand out addresses. It won't hand out IPs on that subnet since 
##there is nothing between the curly brackets.
subnet 10.20.20.0 netmask 255.255.255.0 { }  
##VLAN - 211
subnet 10.21.12.0 netmask 255.255.252.0 {
	range				10.21.12.3 10.21.15.254;
        option routers                  10.21.12.1;
        option subnet-mask              255.255.252.0;
        option broadcast-address        10.21.15.255;
        }

##VLAN - 212
subnet 10.21.20.0 netmask 255.255.252.0 {
	range				10.21.20.3 10.21.23.254;
        option routers                  10.21.22.1;
        option subnet-mask              255.255.252.0;
        option broadcast-address        10.21.23.255;
        }
        
BASH
interface Vlan211
 description VLAN 211
 ip address 10.21.12.1 255.255.252.0
 ip helper-address 10.20.20.41

interface Vlan212
 description VLAN 212
 ip address 10.21.22.1 255.255.252.0
 ip helper-address 10.20.20.41
Unquote.

Another effort is here,
https://happy-coder.com/2014/06/27/pfsense-custom-dhcpd-configuration/

another here,
https://blog.tinle.org/2013/01/09/single-dhcp-server-for-multiple-subnets-vlans-one-single-interface/

If this is the case, can you guys help to make this available in the OpnSense? So, ideally, we can choose a OpnSense LAN interface, enable DHCP service on this LAN, but not assigning DHCP address for this LAN (by making an empty declaration for this subnet).. It has option then for us to add addition SUBNET info. This will make OpnSense a replacement for Windows DHCP server.

Or, at least, we can still allow assign DHCP address for this specific LAN, at same time, allowing to server other SUBNETs, if "not serving dhcp address" on this LAN is difficult to acchieve.

My project actually goes live on Monday Mar 5 2018. I just didn't plan this and just realized this issue. Would this be a quick easy fix with a minor update from you guys?

My next option plan (least favorite) would be either using a standalone box for this purpose as standalone DHCP server, or extending all those VLANs across many switches to OpnSense.

Thanks
peng

**Comment by githubatf2f10** [comment]
some pfsense' attempt..

pfsense multiple subnets dhcp server

https://forum.pfsense.org/index.php?topic=65736.15
https://github.com/pfsense/pfsense/pull/816
https://github.com/pfsense/pfsense/pull/3836

**Comment by githubatf2f10** [comment]
https://happy-coder.com/2014/06/27/pfsense-custom-dhcpd-configuration/ (**for pfsense)

**Comment by githubatf2f10** [comment]
so, for the vlan that we want to have STATIC IP as a transit network of other networks, we can simply define this "EMPTY" subnet and list all other subnets here, while we "ENABLE" dhcp service on this interface.

https://community.spiceworks.com/topic/1331562-isc-dhcp-server-for-multiple-vlans
The last link that B-C posted was what I used to get it working. The key was dropping all the need for multiple virtual NICs and just use the one. Then spec the ranges and use the "IP Helper" command on my cisco switch for each VLAN definition. 

Works flawlessly. Only gotcha is you need to specify a DHCP subnet for the subnet that the DHCP Server is on, but it can be empty (mine is).

Here is my dhcpd.comf and VLAN description from my Cisco switch. I have many more than these two VLANs, but you should get the idea from them.

# This subnet is the one that the DHCP server is in, has to be here in order 
# the server to hand out addresses. It won't hand out IPs on that subnet since 
# there is nothing between the curly brackets.
 
subnet 10.20.20.0 netmask 255.255.255.0 { } 

#VLAN - 211
subnet 10.21.12.0 netmask 255.255.252.0 {
	range				10.21.12.3 10.21.15.254;
        option routers                  10.21.12.1;
        option subnet-mask              255.255.252.0;
        option broadcast-address        10.21.15.255;
        }

#VLAN - 212
subnet 10.21.20.0 netmask 255.255.252.0 {
	range				10.21.20.3 10.21.23.254;
        option routers                  10.21.22.1;
        option subnet-mask              255.255.252.0;
        option broadcast-address        10.21.23.255;
        }
        
BASH
interface Vlan211
 description VLAN 211
 ip address 10.21.12.1 255.255.252.0
 ip helper-address 10.20.20.41

interface Vlan212
 description VLAN 212
 ip address 10.21.22.1 255.255.252.0
 ip helper-address 10.20.20.41

**Comment by fichtner** [comment]
Closing in favour of open ticket #910.

**Comment by FlorianHeigl** [comment]
I had to read this like 10 times, but I think the last post is in fact a solution.
