### ISSUE TITLE
XMLRPC sync not triggered for plugin config changes

### ISSUE THREAD

**Issue by fraenki** [opnsense/core#2239]
I've noticed that plugin configuration changes are synced _only very unreliably_ to the secondary OPNsense node. Interestingly, it's always working for core components, for example when adding or changing an alias or configuring IPsec tunnels, the change is immediately synced to my secondary OPNsense node.

How to reproduce:
- `System: High Availability: Settings` – enable config sync for all components
- `Services: HAProxy: Settings` – add or change a setting on the primary OPNsense node

Expected result:
- the added HAProxy configuration should be available on the secondary OPNsense node

Actual result:
- the added HAProxy configuration is missing on the secondary node

**Observation:**
It looks like config changes in plugins _do not trigger_ a XMLRPC sync at all. A workaround is to change a core component, for example an alias; this will immediately trigger a XMLRPC sync and also transfer all previously made plugin config changes to the secondary node.

Verified on 18.1.3, 17.7.12 and 17.7.10.
It's the same behaviour on **three completely different setups**.

There's nothing in the `system.log` on both nodes, and of course no sync error reported in the GUI.
Besides that, `System: High Availability: Status` looks sane too.

**Comment by Addy90** [comment]
What helped me is to reload the service on the backup firewall via the Status page of "High Availability" site. This way, I could trigger the sync, too.

This is not only the problem for HAsync but also for IDS/Suricata, also for one of the "Unbound" General checkbox buttons, but I forgot which one it was...

**Comment by fichtner** [comment]
Nowadays that is more of a "what you put into it you get out of it" situation. Register a remote reload call... It's triggered here...

https://github.com/opnsense/core/blob/master/src/etc/inc/xmlrpc/legacy.inc#L137

... and defined here...

https://github.com/opnsense/core/blob/master/src/etc/inc/plugins.inc.d/openvpn.inc#L36

We can figure out the rest, but no by raising tickets that nobody will work on.

**Comment by fraenki** [comment]
@fichtner Huh, anything wrong in raising attention for an issue that is not documented elsewhere? Anyway, thanks for pointing to the right direction. I'll try to integrate it into one of the plugins for a starter.

**Comment by fichtner** [comment]
Nothing wrong, but it needs to be broken down into manageable parts that have a clear implementation path. This looks like a conglomerate of wishes and expectations. Need to forcefully break this down to go forward. Core tickets welcome for step by step progress, otherwise we’ll never get to the bottom and solve this reliably.
