### ISSUE TITLE
I have removed all aliases, but pFTables entries are still visible

### ISSUE THREAD

**Issue by gonzopl** [opnsense/core#2240]
I have removed all aliases, but pFTables entries are still visible

![firewall_aliases_view](https://user-images.githubusercontent.com/37049345/36949721-845b2f00-1fec-11e8-9740-a0e855625267.jpg)
![firewall_diagnostics_pftables](https://user-images.githubusercontent.com/37049345/36949722-84775fea-1fec-11e8-8e31-dba60508d07b.jpg)

**Comment by fichtner** [comment]
You can reboot. ;)

**Comment by fichtner** [comment]
See https://forum.opnsense.org/index.php?topic=7464.msg34118#msg34118
