### ISSUE TITLE
FR: Add Renew button to Interfaces - Overview

### ISSUE THREAD

**Issue by mimugmail** [opnsense/core#2241]
Hi,

while testing some stuff for #1821 I'm struggling with DHCP and the "Release" button for interfaces. 
When I push release the interface will be released from DHCP, this is quite OK, but when you administrate the device from remote a "Renew" would be better. 

Perhaps you can add a second button "Renew" which does "Release" and after it "Renew"?

Opinions?

**Comment by fichtner** [comment]
Should be https://github.com/opnsense/core/issues/1642

**Comment by fichtner** [comment]
@mimugmail you can try aa4da63f95 now :)
