### ISSUE TITLE
Imported ldap users: The username contains invalid characters with Active Directory UPN

### ISSUE THREAD

**Issue by nantoine555** [opnsense/core#2242]
I'm using an Active Directory LDAP with "userPrincipalName" as username.

So I have usernames like "pname@domain.com".

First import from ldap is ok, but further editing is raising an error "The username contains invalid characters"

Is there a reason not to accept '@' for username, and less than 32 characters  in system_usermanager.php?

        if (preg_match("/[^a-zA-Z0-9\.\-_]/", $pconfig['usernamefld'])) {
            $input_errors[] = gettext("The username contains invalid characters.");
        }
        if (strlen($pconfig['usernamefld']) > 32) {
            $input_errors[] = gettext("The username is longer than 32 characters.");
        }

**Comment by AdSchellevis** [comment]
yes, usernames are created locally and thus have the same constraints as local (FreeBSD) users.

**Comment by nantoine555** [comment]
Maybe I should not be able to add such usernames then?

**Comment by AdSchellevis** [comment]
you're definitely right, if the import accepted it, the local user should be cleansed before input (logically `pname@domain.com` should turn into `pname` as local user).
