### ISSUE TITLE
Suricata / IPS bug with Jumbo Frames or IPv6

### ISSUE THREAD

**Issue by addy90** [opnsense/core#2249]
I have two bugs with Suricata IDS since 17.7 and still not fixed in 18.1.3.
This happens in two different setups of OPNsense, both on 18.1.3.

First bug in setup 1: When I have Suricata with IPS enabled and enable IPv6 (for example via DHCP from an upstream router), the local "Check for updates" does not work anymore. I get a timeout from the command, no matter if GUI or Console. When I disable IDS, it works - even when Suricata still is running. When I disable IPv6, it works. So the combination of IPv6 and Suricata kills some (but not all) local connections, like the update command. I am running without IPv6 so that I can use IPS.

Second bug in setup 2: Jumbo Frames and Suricata with IPS don't work at all, without IPS it works. Everything is offline instantly except unprotected Ports. No idea how this is solved, default packet size does not matter at all.
I cannot use Suricata at all here. This is bad...

I tried to solve this for hours already and have not found anything that is clearly helpful - if I can provide something, please ask!

**Comment by fabianfrz** [comment]
For 1: You should check your signatures and logs. Maybe you have some kind of overblocking.
For 2: The bug tracker for the ids is here: https://redmine.openinfosecfoundation.org/

**Comment by Addy90** [comment]
For 1: Update is reporting `Firmware status check was aborted internally. Please try again.`
There are no Suricata alerts at all, nothing blocked.

When I call the fetch manually, I get the following:
```
# configctl firmware changelog fetch
Error (1)
```

This is the same as in system.log: `configd.py: [1fdf8458-e370-48f9-911c-a4f0a636c328] returned exit status 1`

A ping and ping6 to `pkg.opnsense.org` works, but not fetching the changelog...

When I dig deeper, I see that `pkg update` does not work...
I tried it with parameter -4 or -6 and with -4 in IPv4 it works, with -6 in IPv6 it hangs...

**I noticed that ping, curl, etc. work on IPv6 when no TLS is used, but SSH, curl on https do not work!**

Any more idea how to find out more about this? I cannot debug suricata, unfortunately...

Concerning 2, maybe this is another issue, I will dig deeper and ask again, so let's just continue 1 here first - sorry for mixing up, will learn for future reports.

**Comment by AdSchellevis** [comment]
timeout
