### ISSUE TITLE
add password policies for local users

### ISSUE THREAD

**Issue by AdSchellevis** [opnsense/core#2252]
Set an expiry date on local passwords and enforce password strength when selected.

**Comment by AdSchellevis** [comment]
for reference, setup password constraints 
![image](https://user-images.githubusercontent.com/9783985/37256398-6e54d21a-255a-11e8-849a-5baf3eb302b7.png)

**Comment by AdSchellevis** [comment]
By default the policies will stay disabled in https://github.com/opnsense/core/commit/dc74006c9ac7790cbcfdb02f5b9b420886ae2b62 so nothing should change for existing and new installs, other then some minor (non functional) cleanups in the authentication flow.

**Comment by linuxmail** [comment]
Hello,

is there a roadmap, when this feature would be available for the production release ?

cu denny

**Comment by fichtner** [comment]
Hi Denny,

It was shipped in 18.1.6.


Cheers,
Franco

**Comment by linuxmail** [comment]
hi @fichtner 

thanks :-) Is there a configuration file or a doc, what kind of complexity is used ? I mean, I can enable it but I can see (if the password is bad) the rule only on a password change :-)
