### ISSUE TITLE
Installer issues

### ISSUE THREAD

**Issue by petererdos** [opnsense/core#2254]
I can't really provide logs for this, so I'll try to explain what happens.

Sources for this reporting:
1. https://forum.opnsense.org/index.php?topic=7547
2. This is not exactly the same as p1, but similar hardware and exactly the same outcome: https://forum.opnsense.org/index.php?topic=7329

I read many times what Franco was advising in similar cases, especially for p1, so I tried exactly that: install FreeBSD first and see if that works. And it did, FreeBSD installed quite nicely.

As you can see from the forum report, OPNsense 18.1 installer (amd64, vga) fails to install. It hangs right after formatting, right before partitioning the HDD.

I'll define what hang means here:
1. Any visible progress stops after the HDD is formatted 
2. I think when trying to partition the HDD, the installer hangs
3. There is no visible progress on the screen after this point
4. CTRL+ALT+DELETE or the power button will display some logs, overlaying the blue screen of the installer with the installation progress
5. There is absolutely nothing wrong hardware wise (professionally tested)

I'll have this hardware (from p1) for another 2 or 3 days, as it is not mine. It will be the main gateway of a client's network, deployed far away from where I live, so access will be difficult, the issue impossible to reproduce and confirm a fix once it's put in place. If anybody has the time to investigate before relocating the box, I'll try to be available.

Thank you all.

**Comment by fichtner** [comment]
There should be a /tmp/installer.log in the system -- can it be salvaged?

**Comment by petererdos** [comment]
Don't know, let me try and I'll report back.

**Comment by petererdos** [comment]
No logs yet, but..
dcol mentioned that changing the font to vgarom-8x14.fnt worked for him a few times.
Just tried it. Worked for guided, did not for manual install (exactly the same symptoms with any other fonts for manual install).

/tmp/installer.log is kept in the memory or written on the hdd/usb flash drive? I guess, since the hdd is not yet partitioned (i think), in the memory.. can i set it's location somehow to the memstick?

**Comment by petererdos** [comment]
I think it has something to do with the display indeed. Just attached a mouse as well, the mouse works even when the installer hangs. Choosing the gallant font freezes the installer instantly. I cannot access the console from this point in any way. I can restart with CTRL+ALT+DEL, shutdown (and i have some line of logs overlaying the blue screen) and move the mouse. That's it, nothing else works, no function keys, trying blindly some commands in the background, nothing..

**Comment by petererdos** [comment]
![img_20180311_124203](https://user-images.githubusercontent.com/14872721/37252647-7d32acda-252d-11e8-95c8-aa088ccab283.jpg)
So i booted another memstick, the hdd looks like partially formatted (nothing seems to recognize the filesystem). But there are no other partitions. Also, when the installer hangs, the CPU cooler jumps to higher rpm (i can hear it), like there's some serious processing happening in the background or it gets into an infinite loop of something.. attached an image with how the hdd looks like after the installer hangs, but i no longer think it has something to do with anything else than the display. I replaced the Samsung 2.5 ssd with an m.2 WD Green ssd.

**Comment by fichtner** [comment]
@petererdos I can build a new VGA image based on the latest code and development version. would it make sense to try this as a data point?

**Comment by petererdos** [comment]
I can try as many images as you you want me too for two more days (this evening and the next one, as the whole thing got postponed because of a missing hardware which will arrive today or tomorrow).  I have to finish configuring the system after that and test some stuff a little , then travel with it to its destination.

**Comment by fichtner** [comment]
Here's one, but it's only for testing because I don't know which software state is on there. If it works I can build a reliable image on 18.1.4perhaps? 

REDACTED

**Comment by fichtner** [comment]
Sorry, second try: https://pkg.opnsense.org/FreeBSD:11:amd64/snapshots/OPNsense-201802100805-OpenSSL-vga-amd64.img.bz2

This image is ok, based on an updatable 18.1.x release. Particularly, it fixes the Unbound issue that causes the system to freeze up during install.

**Comment by petererdos** [comment]
Sure Franco, i'll try this evening. Unfortunately it's the last night the system is available for testing, as i'm running out of time with the setup/testing part...

**Comment by fichtner** [comment]
I understand and appreciate all your efforts. The installer is tricky and time consuming. The target to fix this is 18.7 anyway so we don't have to rush or be disappointed with unrealistic goals. I think that trouble with the installer may be a bit elevated with 18.1 on FreeBSD 11.1, but we don't know how many new people with new hardware run into this that have never previously given us data points / a proper baseline. :)

**Comment by petererdos** [comment]
Nope.. same thing. Only with the 8x14 font and guided install works.. On the positive side, the import of settings was successful 👍

**Comment by fichtner** [comment]
if you do select "3" during boot menu and use the following:

```
set kern.vty=sc
boot
```

Does it work more reliably or worse? Is this an UEFI system?

**Comment by petererdos** [comment]
UEFI. If i have some time tomorrow I'll check this out. Unfortunately I'm passed the time to test installs, unless i get everything up and running very quickly..

**Comment by douglasg14b** [comment]
@fichtner tried
```
set kern.vty=sc
boot
```
and it froze here: https://i.imgur.com/OGbuVYw.jpg

Changed the font to garom and the guided install worked, however the UI was shoved to the lower right. https://i.imgur.com/ckaNuCe.jpg

**Comment by comnam90** [comment]
Changing the font size also resolved the issue for me on Hyper-V Gen2 VM

**Comment by fichtner** [comment]
18.7 won't be better since we will keep FreeBSD 11.1, but we can try an installer based on FreeBSD 11.2 in a few weeks to see if this has gotten better or not.

**Comment by SergioRius** [comment]
The issue still reproduces with the latest vga image.

**Comment by fichtner** [comment]
Yes, that's why I said "18.7 won't be better" :)

**Comment by eugene-chow** [comment]
I used the same amd64/vga image on 2x Dell R440 servers and encountered a similar issue. In my case, the installer always became unresponsive at menu for creating the swap partition. The mouse could move but the keyboard was stuck. I discovered the solution by sheer luck:
1. Press `Ctrl+C` to exit the installer, which returns you to the login screen.
1. Relogin as the `installer` user and resume the installation.

I hope this helps someone who encountered the same issue!

**Comment by Alphaprot** [comment]
It helped to change the font in the GUI.. I'm really sorry that I don't know which one anymore, but you can really do some trial and error - at least it worked for me with the Guided Install Option.

EDIT: I took vgarom-thin 8x16... As far as I remember :)

**Comment by fredskis** [comment]
> I used the same amd64/vga image on 2x Dell R440 servers and encountered a similar issue. In my case, the installer always became unresponsive at menu for creating the swap partition. The mouse could move but the keyboard was stuck. I discovered the solution by sheer luck:
> 
> 1. Press `Ctrl+C` to exit the installer, which returns you to the login screen.
> 2. Relogin as the `installer` user and resume the installation.
> 
> I hope this helps someone who encountered the same issue!

This helped me! Thanks. I had also changed the font to 8x14 on this test (where it froze) but CTRL+C and re-logging in brought it back to life!

**Comment by celsolom** [comment]
That help me too in 19.7 and Hyper-V 2012 R2!

**Comment by dpieski** [comment]
Thanks! The CTRL+C and re-login worked for me too. Hyper-V on Win 10 pro, Gen2 VM, opnsense 19.7.
Locked up at the Guided - Manual Install menu, locked up again on the SWAP confirm dialog.

**Comment by MBiesma** [comment]
> Thanks! The CTRL+C and re-login worked for me too. Hyper-V on Win 10 pro, Gen2 VM, opnsense 19.7.
> Locked up at the Guided - Manual Install menu, locked up again on the SWAP confirm dialog.

I got exactly the same problem and configuration. The CTRL+C and re-login worked for me too.

**Comment by kevin-j-morse** [comment]
CTRL+C and re-login worked on Windows Server 2019 with a lock up right after choosing to continue with default keymap.

Also locked up at SWAP dialog... Again CTRL + C and re-login worked.

**Comment by Bilal-io** [comment]
Issues still happening with latest version 20.1 VGA.
CTRL+C and re-login resolves the issue for me as well.

**Comment by manualdidact** [comment]
Confirmed, 20.1 vga, freeze at the swap dialog.  Ctrl-C and re-login worked.

Really glad I found this page.

**Comment by bimmerdriver** [comment]
Bumping this issue to see if the problem has been fixed or if it fell off the radar...

**Comment by cameronkollwitz** [comment]
> Bumping this issue to see if the problem has been fixed or if it fell off the radar...

Still happening. It happened multiple times to me during the same install (the second time was at the swap partition prompt) but the Ctrl-C workaround still worked for the second one.
