### ISSUE TITLE
UI: Do not allow binding a second bridge on the same network interface

### ISSUE THREAD

**Issue by EugenMayer** [opnsense/core#2256]
OPNsense: `18.1.4`
uname -a : `11.1-RELEASE-p6 FreeBSD 11.1-RELEASE-p6  6621d681e(stable/18.1)  amd64`

created 2 bridges, default settings with member WAN.

in the config.xml they both look the same:

```
 <bridges>
    <bridged>
      <descr>demos1</descr>
      <maxaddr/>
      <timeout/>
      <bridgeif>bridge0</bridgeif>
      <maxage/>
      <fwdelay/>
      <hellotime/>
      <priority/>
      <proto>rstp</proto>
      <holdcnt/>
      <members>wan</members>
      <ifpriority/>
      <ifpathcost/>
    </bridged>
    <bridged>
      <descr>saas1</descr>
      <maxaddr/>
      <timeout/>
      <bridgeif>bridge1</bridgeif>
      <maxage/>
      <fwdelay/>
      <hellotime/>
      <priority/>
      <proto>rstp</proto>
      <holdcnt/>
      <members>wan</members>
      <ifpriority/>
      <ifpathcost/>
    </bridged>
  </bridges>
```

And demos1, the first bridge, works as expected, but bridge1 is completely offline. The reason seems to be that bridge1 does not get a member attached at all:
https://drive.google.com/file/d/1mhWnMQ3KI7R8MbzikW4RrKKvE3fSshC3/view?usp=drivesdk

Anything else i need to provide?

**Comment by AdSchellevis** [comment]
you probably shouldn't be able to configure that, an interface can't live in two bridges at the same time (both contain wan).

**Comment by EugenMayer** [comment]
@AdSchellevis thats possible in linux too? And why should it not possible, sounds like a pretty common case.

L2 based, you get packages for MAC1, MAC2, MAC3 on the WAN nic ( DC setup ) and you know want to split all those up onto bridges, keeping mac1 on the vtnet1, mac2 for br0 and mac3 for br1 ..

Thats farily common?

Is that a BSD limitation? 

I just verified what you said in terms, i used vtnet0 as a member interface ( so its WAN and LAN ) and it has been assigned properly - so you are def. nailing it - but in linux, i could have unlimitted bridges on an nic? like here

https://drive.google.com/file/d/1BiKCK1oYimoKbvL889qsW21C9l0fA9A8/view

**Comment by AdSchellevis** [comment]
I don't think linux is that different for bridging, your last screenshot doesn't contain an overlapping interface just some virtual interfaces in different bridges (which should also function in bsd). 

A correct comparison would be that eth0 would be in both vmbr0 and vmbr30, which I  expect would lead to the same kind of issues.

**Comment by EugenMayer** [comment]
is there something like this "virtual interface" in opnsense? The case here is, that creating something like the bridge lets me assign an interface - and for that interface i can then set a MAC ( 2-3) which then will capture all the packages i need.

If that is not supposed to be done with bridges ( i just follow you on that, its far away from my expertise ) what would be the alternative. Sure, if the DC would not use MAC1/2/3 but rather MAC1 for all IPs i could go with virtual IPs, but thats not the case here. 

Nevertheless, i guess this issue should then be downgraded to cosemtic and "avoid offering to binding 2 bridges to the same interface" right?

**Comment by AdSchellevis** [comment]
yes
