### ISSUE TITLE
CP: Voucher Code, confiusion between characters I and l 

### ISSUE THREAD

**Issue by DokuKaefer** [opnsense/core#2257]
The guests have problems to distinguish the letters I (i) and l (L).

Is it possible to exclude these characters from the voucher generation?

**Comment by fichtner** [comment]
In simple mode?

**Comment by DokuKaefer** [comment]
Yes with simple mode

**Comment by fichtner** [comment]
"l (L) is not included, so I'm simply removing "I (i)" ?

**Comment by fichtner** [comment]
Please try:

# opnsense-patch 86aa456

**Comment by DokuKaefer** [comment]
Perfect, works.

Thanks Franco!
