### ISSUE TITLE
UI/Convinience: Let Aliases be chosen for source in 1:1 NAT settings

### ISSUE THREAD

**Issue by EugenMayer** [opnsense/core#2261]
Yet one has to provide the ip which is most probably already an Alias manually - selecting the alias would be very helpful.

Any reason besides "its effort to implement" to not do that / not allow that?

**Comment by AdSchellevis** [comment]
switch to nat mode instead of binat if you want to use aliases.... binat rules won't accept aliases because they expect equal sized networks to map.

**Comment by EugenMayer** [comment]
Thanks @AdSchellevis - forgot to come back. That helped (also understanding that)
