### ISSUE TITLE
Feature Request - Include hostname-domain in Backup file name

### ISSUE THREAD

**Issue by brandonmreeves** [opnsense/core#2262]
Paid Support Customer Here. We would like to make a feature request.

We use the backup to google drive feature however because we use multiple opnsense devices we are unable to determine which backup goes with which device when looking in the google drive folder. 

We would like to request a feature to add the hostname-domain to the backup name when the file is copied to google drive. 

Current file name may be:
config-1520834402.xml

Preferred file name would be:
gw101-local-config-1520834402.xml which translates to

hostname-domain-currentbackup_filename.xml

If we can accomplish this another way to backup our config files in a central location via shell script, we are happy to do that as well in the meantime.

Please advise.

Thanks

**Comment by AdSchellevis** [comment]
just out of curiosity, is there a reason to not backup the different machine to their own folder on Google?  Normally you should also be able to organise rights between folders and prevent the different machines from accessing each others contents.

**Comment by brandonmreeves** [comment]
We could do that. We built a standard opnsense image and was trying to standardize as many settings as possible to minimize the likelihood of error on our part or miss anything.

**Comment by AdSchellevis** [comment]
@brandonmreeves it's probably practical to support this, here you are https://github.com/opnsense/core/commit/8c44049298253bfcd6ea23cefc8ff85f2edb9dfd 

To test on your machine, run from a console:
`opnsense-patch 8c44049
`

**Comment by brandonmreeves** [comment]
worked perfect. The Opnsense team is amazing.
