### ISSUE TITLE
IPv6 PPPOE Static IP  & Neighbor Advertisement over PPP ignored

### ISSUE THREAD

**Issue by msenebald** [opnsense/core#2263]
Hi, 

i am running  OPNsense 18.1.4 (amd64/OpenSSL)
While setting up IPv6 over PPP, I found the the Static IP(provided by ISP) and the NA from my provider are happily ignored. 

## Configuration: 
WAN Interface:
IPv4 PPPOE 
IPv6 Static

Static IPv6 configuration
IPv6 address 2xxx:xxxx:xxxx:: /48
Use IPv4 connectivity [ ]
IPv6 Upstream Gateway - none

## Current result
after pppoe is established, the link looks like:
```
pppoe0: flags=88d1<UP,POINTOPOINT,RUNNING,NOARP,SIMPLEX,MULTICAST> metric 0 mtu 1456
	inet6 fe80::axxx:xxxxx:xxxx:xxxx%pppoe0 prefixlen 64 scopeid 0xd
	inet 2xx.xxx.xxx.xxx --> xx.xxx.xxx.xx  netmask 0xffffffff
	nd6 options=23<PERFORMNUD,ACCEPT_RTADV,AUTO_LINKLOCAL>
```

while routes are like:
```
netstat -rn6 | grep pppoe
fe80::%pppoe0/64                  link#13                       U        pppoe0
fe80::axxx:xxxxx:xxxx:xxxx%pppoe0  link#13                       UHS         lo0
```

PPPOE got the Interface Identifier 

```
Frame 38: 36 bytes on wire (288 bits), 36 bytes captured (288 bits)
Ethernet II, Src: LOCAL, Dst: ISP
PPP-over-Ethernet Session
Point-to-Point Protocol
    Protocol: IPv6 Control Protocol (0x8057)
PPP IPv6 Control Protocol
    Code: Configuration Ack (2)
    Identifier: 1 (0x01)
    Length: 14
    Options: (10 bytes), Interface Identifier
        Interface Identifier
            Type: Interface Identifier (1)
            Length: 10
            Interface Identifier: 00:00:00:00:00:00:88:20
```
NA (fe80::8820)  was also send via ICMPv6 on the wire and marked as a router

```
Frame 39: 86 bytes on wire (688 bits), 86 bytes captured (688 bits)
Ethernet II, Src: JuniperN_b3:0e:ea (88:a2:5e:b3:0e:ea), Dst: SuperMic_45:e1:c8 (ac:1f:6b:45:e1:c8)
PPP-over-Ethernet Session
Point-to-Point Protocol
    Protocol: Internet Protocol version 6 (0x0057)
Internet Protocol Version 6, Src: fe80::8820, Dst: ff02::1
Internet Control Message Protocol v6
    Type: Neighbor Advertisement (136)
    Code: 0
    Checksum: 0xeb65 [correct]
    [Checksum Status: Good]
    Flags: 0x80000000, Router
    Target Address: fe80::8820
```

## Expected behaviour:
IP Address:
pppoe0 Link should have next to link local address the static IP assigned.

Route:
since this is point-to-point and no route was added, the Neighbor identified as as Router this should be considered as the router and a respective gatway should be created. 

## Comment
Once i add the IP Adress manually on the pppoe0 interface and have a gateway configured (with the discovered link-local adress from isp) it works as expected. 

```
netstat -rn6 | grep pppoe
default                           fe80::8820%pppoe0             UGS      pppoe0
fe80::%pppoe0/64                  link#13                       U        pppoe0
fe80::axxx:xxxxx:xxxx:xxxx%pppoe0  link#13                       UHS         lo0
```

```
ifconfig pppoe0 inet6 2xxx:xxxx:xxxx:: /48 add
pppoe0: flags=88d1<UP,POINTOPOINT,RUNNING,NOARP,SIMPLEX,MULTICAST> metric 0 mtu 1456
	inet6 fe80::ae1f:6bff:fe45:e1c8%pppoe0 prefixlen 64 scopeid 0xd
	inet6 2xxx:xxxx:xxxx:: prefixlen 48
	inet 2xx.xxx.xxx.xxx --> xx.xxx.xxx.xx  netmask 0xffffffff
	nd6 options=23<PERFORMNUD,ACCEPT_RTADV,AUTO_LINKLOCAL>
```

**Comment by marjohn56** [comment]
Not sure what your issue is here. If you set IPv6 static then you have to supply an address, otherwise you select dhcp6.

I also use static IP on IPv6 over PPPoE. I can use static, where I enter an IP address or I can use dhcp6, where the ISP will give me an address. I cannot use static and not enter an address.

**Comment by msenebald** [comment]
The problem is, even tho I set an IPv6 address, it is ignored when bringing up the PPPOE connection. 
It is not configured.

**Comment by umsp1** [comment]
Seems I have exactly same issue.  
My ISP providing static /56 or Dynamic /64  ipv6 and dynamic IPv4 through PPPoE.
Dynamic ipv6 never worked (with two ISP’s) so I assigned static IPv6, but still struggling to make it to work.
igb0 - LAN
igb1 – WAN pppoe configured

This is the ppoe0 interface
ppoe0: flags=88d1<UP,POINTOPOINT,RUNNING,NOARP,SIMPLEX,MULTICAST> metric 0 mtu 1492
        inet6 2400:xxxx:xxxx:xxxx::1 prefixlen 56 
        inet6 fe80::xxxx:xxxx:xxxx:8045%pppoe0 prefixlen 64 scopeid 0x9 
        inet 10x.xxx.xxx.223 --> 10x.xxx.xxx.x25  netmask 0xffffffff 
        nd6 options=21<PERFORMNUD,AUTO_LINKLOCAL>

I realized this is a routing issue, but still not sure how to fix

Internet6:
Destination        Gateway            Flags     Netif Expire
::1                link#5             UH          lo0
2400:xxxx:xxxx:7b0 link#1             U             igb0
2400:xxxx:xxxx:7b0 link#1             UHS         lo0
2400:xxxx:xxxx:7bf  link#9             UHS         lo0
fe80::%igb0/64          link#1             U            igb0
fe80::20e:xxxx:fed    link#1             UHS         lo0
fe80::%igb1/64          link#2             U            igb1
fe80::20e:xxxx:fed    link#2             UHS         lo0
fe80::%lo0/64            link#5             U             lo0
fe80::1%lo0               link#5             UHS         lo0
fe80::%pppoe0/64     link#9             U         pppoe0
fe80::xxx:xxxx:fed   link#9             UHS         lo0

If I change IPv6 default gateway to pppoe I can ping ISP’s DNS server, but that’s it. There is no connection to internet. 

Executing route add -inet6 default -interface pppoe0

add default route, now I can ping6 to ISP’s IP’s e.g.DNS servers

Now routing table look like this
Internet6:
Destination        Gateway            Flags     Netif Expire
default                  pppoe0             US       pppoe0
::1                            link#5             UH          lo0
2400:xxxx:xxxx:7b0 link#1             U          igb0
2400:xxxx:xxxx:7b0 link#1             UHS         lo0
2400:xxxx:xxxx:7bf  link#9             UHS         lo0
fe80::%igb0/64        link#1             U          igb0
fe80::xxx:xxxx:fed    link#1             UHS         lo0
fe80::%igb1/64         link#2             U          igb1
fe80::xxx:xxxx:fed     link#2             UHS         lo0
fe80::%lo0/64            link#5             U           lo0
fe80::1%lo0               link#5             UHS         lo0
fe80::%pppoe0/64    link#9             U        pppoe0
fe80::xxx:xxxx:fed     link#9             UHS         lo0

Hope someone send me right direction

**Comment by fichtner** [comment]
You probably need to set "Use IPv4 connectivity" for your Static IPv6 WAN configuration.

**Comment by umsp1** [comment]
configured "Use IPv4 connectivity" for static IPv6 WAN configuration, but still pppoe not get configured as default gateway.
I have ipv6 gateway provided by ISP, but struggling with correct command to use.
I can use "route add -inet6 default -interface pppoe" to make default gateway, then I can ping gateway and ISP's DNS server and I can see name resolution working. But still not connecting to INTERNET. . 

I assume I have to do something like "ip route add 172.16.5.0/24 via 10.0.0.101 dev eth0"
But not sure what command to use with BSD with ipv6.

**Comment by marjohn56** [comment]
This is bizarre... There are at least two of using static IPv6 addresses and both the WAN and LAN with zero issues.

OK, so does your ISP gives you a static WAN /64  address range and a separate PD prefix /48 for the LAN or what exactly do they give you?

**Comment by umsp1** [comment]
ISP give /64 DHCP and /56 static range. DHCP range never worked for me. 
I'm using static range /64 block assigned to WAN and another /64 for LAN. 
Many people claim commercial routers working fine.

**Comment by marjohn56** [comment]
Are you 100% sure you have that the right way around? a /64 WAN and a /56 PD for the LAN makes sense, the other way around is madness. Double check that first before I go further.

Also, the dhcp WAN address and the static WAN address are usually in the same /64 range. Check that too.

**Comment by umsp1** [comment]
Thank you marjohn56
I test with old TPlink  router seems still IPv6 not working. Now I'm suspecting something wrong with ISP end (smaller AU ISP). While trying these I upgraded opnsence, look like I reboot wrong time which cause Opnsence not starting any more. I will try again when 18.7 released.

**Comment by fichtner** [comment]
Sounds like https://github.com/opnsense/core/issues/2726 to me. A fix has been added to the development version. Please discuss in the other ticket.
