### ISSUE TITLE
net.inet.tcp.tso set to 1 by default

### ISSUE THREAD

**Issue by fichtner** [opnsense/core#2265]
@AdSchellevis what should we do with it? Could interfere with IPS or performance on VM.

**Comment by AdSchellevis** [comment]
We should probably leave it default, which is 0 if I'm correct. not sure why it was set originally. offloading usually isn't a very good idea.

**Comment by fichtner** [comment]
https://github.com/pfsense/pfsense/commit/e2bee3feb11 ;)

**Comment by fichtner** [comment]
But the default in FreeBSD is also "1". Dunno, I just wanted to mention it.

**Comment by AdSchellevis** [comment]
I don't think this does anything for out usual setups, we normally disable tso on the card, if I understand the setting correctly this is the system wide option to be able to support TSO. Let's leave it default.
