### ISSUE TITLE
Suricata - Add include to main config

### ISSUE THREAD

**Issue by brandonmreeves** [opnsense/core#2268]
We are using suricata for IDS/IPS. Rather than messing with core files, we would like to include our own custom yaml files as per suricata documentation in the suricata folder.

What would be the easiest way for us to have a custom include persist across opnsense / suricata upgrades?

For example, we may want to have the following line added at the bottom of the primary suricata.yaml config file that has additional settings.
ex. 
include: custom_config.yaml 

We were thinking the solution may be one the following
1.) adding a blank custom_config.yaml to suricata.yaml and then adding a text box to the gui so we could modify custom_config.yaml from within the gui.
2.) Adding an option in the gui to add the include line into the suricata.yaml and use our pkg install process to install custom_config.yaml.

Reason for request: The main suricata config works for most things, however we occasionally like to turn on flow/netflow to send the data to another source. We also may use custom rules which we could include references to in our custom_config.yaml.

Thoughts?

**Comment by fichtner** [comment]
We can add a pkg "custom.yaml.sample" file and include it by default... so you can override the actual custom.yaml and pkg won't touch it. Sounds good?

**Comment by brandonmreeves** [comment]
works for me.

**Comment by fichtner** [comment]
Don't close just yet :D

**Comment by fichtner** [comment]
d7720dc should work. if you use opnsense-patch then /usr/local/opnsense/service/templates/OPNsense/IDS/custom.yaml needs to be created manually as pkg is not involved in that process.

**Comment by fichtner** [comment]
Shipping in 18.1.6.
