### ISSUE TITLE
Intrusion detection schedules

### ISSUE THREAD

**Issue by dimitrijp** [opnsense/core#2273]
Under system - intrusion detection -administration - schedule, even if schedule already exists GUI is always opening ADD new schedule window, it is not possible to edit or delete already configured schedules under schedules tab. (version 18.1.4)

**Comment by fichtner** [comment]
The schedule tab is only intended for editing the IDS schedule. Go to System: Settings: Cron to edit the others.

Furthermore, it's not possible to delete the IDS schedule because it is linked to the subsystem, but it can be deactivated just fine.

**Comment by dimitrijp** [comment]
I have IDS rules update scheduled...i can access/edit this via system - cron but not via IDS - schedules...also I cant disable it..every time i click on Schedules add new widnow pops up. Maybe this it how it should work, but its a little confusing..I have no problem to edit it via cron..just want to check if the behavior is correct.

**Comment by fichtner** [comment]
It's disabled by unchecking "enabled" on top + save
