### ISSUE TITLE
add DNSSEC-Support to DNSMASQ

### ISSUE THREAD

**Issue by ruggerio** [opnsense/core#2275]
As dnsmasq provides more possibilities within the dns-server as unbound, please also add dnssec-support to it.

**Comment by fichtner** [comment]
@ruggerio thanks! do you have a reference to a setup document or the relevant config knobs in Dnsmasq?

**Comment by ruggerio** [comment]
Hi,

Man-Page From thekelleys.org:
http://www.thekelleys.org.uk/dnsmasq/docs/dnsmasq-man.html

The gentoo-site explains it easy (as i hope):
https://wiki.gentoo.org/wiki/Dnsmasq (see the DNSSEC-section)

**Comment by fichtner** [comment]
@ruggerio very helpful, thanks! :)

**Comment by ruggerio** [comment]
just ping if you need Support :)

**Comment by fichtner** [comment]
@ruggerio sorry for the delay, it will be in the upcoming development version of 18.7.9
