### ISSUE TITLE
Can't ugprade current master, missing php71-pecl-radius

### ISSUE THREAD

**Issue by mimugmail** [opnsense/core#2276]
```
root@X:/usr/core # make upgrade
pkg: No package(s) matching php71-pecl-radius
Updating OPNsense repository catalogue...
OPNsense repository is up to date.
All repositories are up to date.
pkg: No packages available to install matching 'php71-pecl-radius' have been found in the repositories
*** Error code 70

Stop.
make: stopped in /usr/core
```

Any ideas? :) I'm on 18.1.4, switched to devel, loaded current master ...

**Comment by fichtner** [comment]
FreeBSD is fiddling with PHP package names... Use "latest/snapshots" firmware flavour.

We'll make a clean transition with 18.1.5.

**Comment by mimugmail** [comment]
Thanks, I'm gonna wait 👍

**Comment by fichtner** [comment]
Alternatively, you can edit Makefile and remove "php71-" prefix for pecl ports and phalcon.

**Comment by mimugmail** [comment]
Just for the archive, it's "snapshots/latest" if anyone struggels :)

**Comment by fichtner** [comment]
whoopsie, right, sorry!
