### ISSUE TITLE
mvc: prevent usage of empty openvpn and ipsec interfaces in e.g. web proxy

### ISSUE THREAD

**Issue by poggenpower** [opnsense/core#2280]
No config changes take place if I change the squid.config via UI. 
There is not error message displayed.

In the system.log appears following error message:
`Mar 21 23:44:52 r04 configd.py: [4265d5be-d8a8-479b-b326-9ecb48999935] request proxy status
Mar 21 23:45:23 r04 configd.py: [13819390-28df-4e6d-a571-5745a0fc352f] generate template OPNsense/Proxy
Mar 21 23:45:26 r04 configd.py: generate template container OPNsense/Proxy
Mar 21 23:45:33 r04 configd.py: [13819390-28df-4e6d-a571-5745a0fc352f] Inline action failed with OPNsense/Proxy OPNsense/Proxy/squid.conf 'collections.OrderedDict object' has no attribute 'ipaddr' at Traceback (most recent call last):   File "/usr/local/opnsense/service/modules/processhandler.py", line 507, in execute     return ph_inline_actions.execute(self, inline_act_parameters)   File "/usr/local/opnsense/service/modules/ph_inline_actions.py", line 50, in execute     filenames = tmpl.generate(parameters)   File "/usr/local/opnsense/service/modules/template.py", line 321, in generate     raise render_exception Exception: OPNsense/Proxy OPNsense/Proxy/squid.conf 'collections.OrderedDict object' has no attribute 'ipaddr'
Mar 21 23:45:33 r04 configd.py: [87adfda5-cdb5-4cea-998b-372dcf98a5bc] request proxy status
Mar 21 23:45:33 r04 configd.py: [cead06f7-4006-42ae-b5e0-ac019b55f5d0] reload proxy
Mar 21 23:45:35 r04 configd.py: [5eb8019c-db0c-4680-8f0d-1e8871bdba27] request proxy status`

while applying a config change. 

My config is very basic, no idea where these "ipaddr" should come from. And no Idea how to troubleshoot in more details.

**Comment by fichtner** [comment]
Do you have an interface selected that does not use a static IP?

**Comment by poggenpower** [comment]
I am using prefix delegation for IPv6, will check if this is the issue. Ipv4 is static. In any case  error message in the UI if template processing is failing would be useful.

**Comment by fichtner** [comment]
It's not a standard error. You have an interface configured for which no IP address can be found. They don't show up unless the interface was stripped later. Try to delete all configured interfaces for "Proxy interfaces" and add them back, one of them is likely missing now?

**Comment by poggenpower** [comment]
OK removed all Interfaces with IPv6 prefix delegation, than the config gets generated. 
But can add them again, may be the check is not working for IPv6.
If there would be an generic error message, that something failed while generating the config, would help at the first point. Wastes a long time, in troubleshooting, because I thought I configured something wrong in the general Proxy config.
How ever thanks for your support, I have know a way to work around. Thank you for this great firewall.

**Comment by fichtner** [comment]
Are you 100% sure there is a static IPv4 on all those IPv6 PD interfaces?

**Comment by poggenpower** [comment]
If I add the OpenVPN interface, the error occurs. 
The IPv6 prefix was a red herring, sorry.
See under Interface>Assignments two network ports ovpnc1 and opvnc2. The first one with a zeroed mac address and the other with a real one. 
Should I create an Interface with this network ports? And add IP-Addresses.

**Comment by fichtner** [comment]
Thanks for the analysis, let me try to reproduce now :)

**Comment by fichtner** [comment]
This is related to a discussion in https://github.com/opnsense/plugins/issues/622
