### ISSUE TITLE
Routing menu

### ISSUE THREAD

**Issue by muchahagrande** [opnsense/core#2282]
"Gateways" and "Routes" menues could reside under their own "Routing" menu.
Now they are under "System" menu.
A "Routing" sleeve appears when you install FRRouting Protocol Suite plugin.
I think that "static routes" and "gateways" being related to routing, should reside on the same Routing menu as the routing protocols.

**Comment by fichtner** [comment]
Maybe time to finally pull in https://github.com/opnsense/core/pull/1647  --- I have no objections / reservations anymore.

**Comment by muchahagrande** [comment]
Question, when will this menu change be pulled in ?
