### ISSUE TITLE
Add Milter-functions to RSPAMD

### ISSUE THREAD

**Issue by ruggerio** [opnsense/core#2285]
Hi,

It would be great, if this could be implemented, so a admin can filter based on needs:

https://www.rspamd.com/doc/modules/milter_headers.html

Admin should then also decide to forward or to drop the mail.

**Comment by fabianfrz** [comment]
@ruggerio can you close this and open it in the plugins repository. This is core (wrong place)

**Comment by ruggerio** [comment]
@fabianfrz done.
https://github.com/opnsense/plugins/issues/624

**Comment by ruggerio** [comment]
New in Plugins.
