### ISSUE TITLE
Playstation: NAT 3 - Type

### ISSUE THREAD

**Issue by ruggerio** [opnsense/core#2286]
Opnsense sets NAT to type 3, even if all UPNP-Options are set. Shouldn't it be on 2 in this case?
Playstation in each case degrades all (even paid) services according to NAT type 3.

Should be fixed. As i read, in Pfsense it goes back on NAT Type 2, if upnp is enabled.

**Comment by ruggerio** [comment]
Get Type 2 if:
- Redirect traffic via Squid
- Use upnp

Think, it will not be fixed, if one will not use squid.

**Comment by DasTestament** [comment]
Actually, all you have to do is set "Static port" to "YES" like this: 
![image](https://user-images.githubusercontent.com/7909542/38670408-59b0ed8e-3e51-11e8-82b5-0149edfc0cb2.png)

Give it a try. It's good for you.
