### ISSUE TITLE
Firewall Live View: Show Hostnames instead of IP's

### ISSUE THREAD

**Issue by ruggerio** [opnsense/core#2287]
Hi,
Live View should give the possibility to show fqdn instead of ip adresses.

Thx,
Roger

**Comment by AdSchellevis** [comment]
you can resolve in the info dialog....

**Comment by ruggerio** [comment]
Thats great, did not know this. 
But, if you search for domains, it is much easier to see the domain instead of an ip. Even because of having tons of ip's for one "hostname" - see google-servers.

Now from the infodialogue, i just interpret, that i can look for the hostname, if i am interested.
