### ISSUE TITLE
Firmware Upgrade on EOL Releases

### ISSUE THREAD

**Issue by abplfab** [opnsense/core#2294]
If you check for upgrades on a 17.7.12_1 it will find and install the update to 17.7.12_2. If you then click again on "check for updates" it will display that all is current. To get the upgrade to 18.1 you have to go back to the Dashboard and check for updates to see the EOL Message and unlock the new release. 
In my opinion the EOL Message and Unlock should be displayed even if I check from the updater directly.

**Comment by fichtner** [comment]
Sure, but who will do the work for this cosmetic bug? :)

**Comment by fichtner** [comment]
The menu has a similar issue after firmware upgrade when new items have been added or were removed.

**Comment by fichtner** [comment]
Solving this via #2153.
