### ISSUE TITLE
Invalid ipv6 bogon list

### ISSUE THREAD

**Issue by bahnwaerter** [opnsense/core#2298]
The current ipv6 bogon list on the OPNSense package server contains invalid content.
The content represents a html page from the "Team Cymru" website and not valid ipv6 subnet entries.

Therefore, the reloading of the firewall rules causes the following error:
> There were error(s) loading the rules: no IP address found for <!DOCTYPE

It seems to be that the former ipv6 bogon list on that website has moved.
Please update the ipv6 bogon list in the bogons.txz archives.

**Comment by bahnwaerter** [comment]
The problem was discovered in the OPNSense forum, too.
Here is the link to the appropriate post: https://forum.opnsense.org/index.php?topic=7731.0

**Comment by fichtner** [comment]
Not sure why this happened. Should be back to normal now?

In any case, thanks for the report!

**Comment by bahnwaerter** [comment]
Thanks for updating the ipv6 bogon list in the bogons.txz archives.
Now, it works without any problems after updating the bogon lists with the following shell script: `/usr/local/etc/rc.update_bogons`

**Comment by fichtner** [comment]
@bahnwaerter thanks again for the report! ❤️
