### ISSUE TITLE
several issues with captive portal

### ISSUE THREAD

**Issue by borisneubert** [opnsense/core#2302]
OPNSense 1.8.5, captive portal setup as in [Wiki](https://wiki.opnsense.org/manual/how-tos/guestnet.html), but with IPv4+IPv6.

- Browsing to HTTP site does not redirect me to captive portal if I am not signed in, instead opens site even if I am not signed in ([example site](http://compgen.de)).
- Browsing to HTTPS site does not redirect me to captive portal if I am not signed in, instead times out ([example site](https://www.google.com)).

Browsing to http://guestaddress:8000 opens the captive portal sign-in page (and rewrites URL to http://guestaddress:8000/index.html?redirecturl=guestaddress).

After signing in, both the HTTP and HTTPS web sites can be reached.

After signing out, initial situation is back.

There are several recent reports in the forum about a non-working redirection to the captive portal sign-in page.

**Comment by borisneubert** [comment]
I set all firewall rules on guest net to IPv4 only. The behavior is the same.

**Comment by borisneubert** [comment]
I disabled IPv6 now. I also removed a NAT rule for the transparent proxy on the guest net - this rule seemingly caused most of the problem (actually I need to check the HTTP transparent proxy option in the captive portal zone settings).

The second issue remains, though: browsing to HTTPS site does not redirect me to captive portal if I am not signed in, instead times out.

**Comment by fichtner** [comment]
Can this be concluded?

**Comment by borisneubert** [comment]
Will test in the next days.

**Comment by borisneubert** [comment]
Tested with OPNsense 18.7.9-amd64: Browsing to HTTPS site does not redirect me to captive portal if I am not signed in, instead times out.

Is this expected because captive portal does not capture HTTPS?

**Comment by AdSchellevis** [comment]
yes, it can't do a man in the middle, so your browser won't trust the certificate it got served from the CP

**Comment by borisneubert** [comment]
Conclusions:
- Captive Portal does not support IPv6
- Captive Portal redirects HTTP requests to login page but not HTTPS requests
