### ISSUE TITLE
DHCPv6 is not configurable, if prefix delegation is used

### ISSUE THREAD

**Issue by poggenpower** [opnsense/core#2303]
Hello,
I am using PreFix delegation from my ISP to configure the internal interfaces. 
OPNSense launching a DHCPv6 Server to configure attached clients, but this DHCP Server is not configurable via UI. 
Would be great if this would be possible to set things like DNS Servers and Domain, but also DHCPv6 Static Mappings.

And leases provided by this "hidden" DHCPv6 server not are not shown in "Services: DHCPv6: Leases"

Thanks
  Thomas

**Comment by marjohn56** [comment]
See #2314

**Comment by efficiosoft** [comment]
Oh... why did I overlook this one? I wouldn't have opened another one in that case. Sorry.

**Comment by fichtner** [comment]
Closing this in favour of a longer discussion in #2314.
