### ISSUE TITLE
Proxy: support compressed blacklists

### ISSUE THREAD

**Issue by fichtner** [opnsense/core#231]
ie:http://dsi.ut-capitole.fr/blacklists/download/ via @gitmod

**Comment by fichtner** [comment]
@jschellevis just skimming through packets.. this was always a good addition being requested :)

**Comment by AdSchellevis** [comment]
@fichtner I will try to add the compressed downloads before 16.1, it's not forgotten :)

**Comment by gitdevmod** [comment]
Thanks!
