### ISSUE TITLE
VLAN DHCP not serving IP's from own subnet

### ISSUE THREAD

**Issue by ruggerio** [opnsense/core#2310]
If using DHCP on VLAN, i get the IP's from the master-interface, instead of the VLAN. 
VLAN-Tag is set correct. Was working before 18.1.5 (as i remember)

**Comment by Alphakilo** [comment]
Can't confirm. I rely heavily on DHCP and VLAN.
All is good in the DHCP land here.

**Comment by ruggerio** [comment]
so, you have your vlans getting the correct ip's from the vlan-dhcp-server?

**Comment by ruggerio** [comment]
ok, i said opnsense to install vlans while initial installation. I deleted them all and did all from scratch, now it works.
