### ISSUE TITLE
SSL-Inspection: no internet connection for Android Devices

### ISSUE THREAD

**Issue by ruggerio** [opnsense/core#2311]
If setting up ssl-inspection in squid, i get no internet connection on Android devices. Windows and Linux (WLAN and LAN) work flawlessy.

Perhaps an issue about connectivitycheck.gstatic.com/gen_204 (and others)?

Thx,
Roger

**Comment by Alphakilo** [comment]
This is most likely an certificate issue.

For clarification: What do you mean by "i get no internet connection"?
Is Android saying you don't have connectivity?
Is DNS not working (can you go to http://108.61.202.109)?

How did you configure the forward proxy exactly?

**Comment by Alphakilo** [comment]
Try this:
Check "Enable SSL inspection"
Check "Log SNI information only"

That should enable ["SSL Peek and Splice"](https://wiki.squid-cache.org/Features/SslPeekAndSplice).

This allows Squid to extract the domains from the traffic (and enforcing ACLs) without actually breaking the encryption.

"Bumping" ("Enable SSL inspection" without "Log SNI only", also known as MiTM) is something you don't want to do, except you really know what you're doing and know why you're doing it (regulatory compliance f.ex.). You're heavily degrading the security and privacy by doing so.

It also breaks sites that use certificate pinning, I'd expect that you'll find most "common" services unusable.

**Comment by ruggerio** [comment]
Hi all,

1) i will look for a tcpdump
2) No certificate of the CA is installed
3) I putted connectivitycheck.[android][google].com and play.googleapis.com in ssl bump host list, also .1e100.net...nothing helped.

meanwhile i leave it on sni.

**Comment by fabianfrz** [comment]
Maybe it is HTTPS so the connection fails if the certificate is not trusted.

**Comment by ruggerio** [comment]
Can be resolved, if entered the following in the no ssl bump sites of the forwarding tab:

.google.[your own country]
.google.com
.googleapis.com
.gstatic.com
.1e100.net

Do not forget to install CA as "VPN and Apps"

**Comment by fichtner** [comment]
Thank you for the follow up and solution. 😊

**Comment by fabianfrz** [comment]
@fichtner maybe that should be added to the docs.

**Comment by fabianfrz** [comment]
@ruggerio I made a short Note for the docs in that special case. Can you review opnsense/docs#21 please?

**Comment by ruggerio** [comment]
It's ok! Thats how i got it working (tested, i deleted everything und putted it in step by step in several mixtures).

**Comment by aneillans** [comment]
@fabianfrz it's probably worth noting that since Android Nougat this no longer works; Android by default tends to ignore User loaded CA certs and only honour the ones in System - making interception virtually impossible on Android.
