### ISSUE TITLE
Inappropriate automatic keymap configuration

### ISSUE THREAD

**Issue by Ricky-Tigg** [opnsense/core#2318]
**Description of problem**: Inappropriate automatic keymap configuration.

Version-Release number of selected component: **OPNsense-18.1-OpenSSL-dvd-amd64.iso**

**Actual results**: _OPNsense_ installer configures the settings related to keymap according to the application default keymap, which I reasonably suspect to be as usual the standard **USA ISO-8859-1**. 

**Expected results:** Supporting physical computing device's current keymap as Linux distributions do, which means for _OPNsense_, listing either the options for selecting the keyboard identification or the standards related to the keymap, if not then, the ability to set automatically the configuration according to the existent device's models, be they virtualised or not.

**Additional info:**

- Physical device : laptop – Keymap standard: **Finnish ISO-8859-1**.
- _OPNsense_ run on _Linux_, as virtual machine on the _QEMU/KVM_ virtualisation platform.
- Virtual disk's bus model: _VirtIO_.
- Recognised network interfaces' model types: _rtl8139_, _VirtIO_.
- Same results regardless selected keymap options:  _Auto_, _fi_, _'empty field'_.

**Comment by fichtner** [comment]
Hi @Ricky-Tigg,

You can select the keymap on the first installer menu. We wouldn't know how to detect the keyboard type and I'm unaware FreeBSD does this / has a working implementation. :/


Cheers,
Franco

**Comment by Ricky-Tigg** [comment]
Hi Franco. Assumed I know installation process  just enough to know what about I am talking in my original message. Therefore using the very first installer menu, –which is according to me nothing else but **Boot Multi User**– shows that those entries are currently the only possibilities of interaction:

`Press any key to start the`
- `configuration importer...`
- `manual interface assignment:`

That is indeed what can be done so far, so I _can_ as you said, since this is the only ways we have to interact with the software for now. If you can, what obviously we cannot, it indicates that I will need fo sure more than a trick to accomplish what you spoke about.

**Comment by Ricky-Tigg** [comment]
Unsure as well I might be just now. Though help is coming! The attached material seems suitable as common mean for dissipating that natural feeling. _Installer_, is the media –here as a virtual disk– involved in the installation process. 

![installer_opnsense-18 1-openssl-dvd-amd64](https://user-images.githubusercontent.com/26058215/38196764-15fb3d52-3685-11e8-9371-cedf13b4837c.png)

**Comment by fichtner** [comment]
Okay, so the first time you are able to modify the keymap is when you have completed boot with said media image and at the login prompt use user „installer“ with password „opnsense“.

**Comment by Ricky-Tigg** [comment]
Hi. _Oh no, not him again!_  Here I am anyway.  After two attempts of further installation failed at **2048 MB** (of virtual memory) of **3096 MB** (Total host memory) the _Installer_ at last succeed to complete its installation process (I was sorry to see the notice _No AESNI support_, but what can I do as mortal). 

Nevertheless, so proud I am, as you can imagine, to announce just for you today, what you would dully qualify as a decent bunch of issues to be fixed with talent, who knows by whom, So here are the beasts, mentioned in their natural order.

1. issue: Using the _installer_ (the one you meant), once the **fi.kbd** keymap entry has been selected and changes applied to the system, the field dedicated to the _root_ user's password does not display the entered keyboard's Scandinavian characters, for instance _ä_, _ö_, _å_. Therefore I had to renounce setting a new password, since I intended to include one of those characters as part of the password.

What the matter by the way with those fool Scandinavians and especially those Finns who just enjoy so much _makkara_, beer, _Salmiakki_, sauna and pure cow-milk and cannot dream any more (how fullish they are) not to be overpopulated by those who had since the beginning of times in their gene  the code to overpopulate each countries that used to be free and pure of their inhuman intrusions.

Then comes an issue in two variants: Issue is tied presently to the use of those very characters and is illustrated by the ability I have to interact in this context with the system-built _login:_ text. 

2. issue: Please (as we used to say), pay attention to the location of the **cursor**. 

![opnsense-18 1_2 issue](https://user-images.githubusercontent.com/26058215/38260781-c8b59a62-3768-11e8-8d9a-18700951eaf3.png)

3. issue:   _login_ text has partially been erased (by me I have to confess).

![opnsense-18 1_3 issue](https://user-images.githubusercontent.com/26058215/38260830-e729533a-3768-11e8-8356-c11929a0d720.png)

I know, that was a bit of exotic matter but it is all I had to offer for that day, and it is all **code**, I hope to do better if comes a next time. Bye Franco.
