### ISSUE TITLE
Performance: use opcache with file-read cache

### ISSUE THREAD

**Issue by EugenMayer** [opnsense/core#2320]
Considering the amount of files opsensen is build from and the amount of includes, this optimization will have an significant improvment in performance ( on second load after cold start ).

Especially on boxes like APU, rpi this will be a dramatic change:

```
zend_extension=opcache.so
opcache.enable=1
opcache.enable_cli=0
opcache.memory_consumption=128
opcache.interned_strings_buffer=4
opcache.max_accelerated_files=20000
opcache.fast_shutdown=1
opcache.enable_file_override=0
opcache.validate_timestamps=0
```

i think `opcache.memory_consumption=128` (we run it with 512) can be downtuned, anything else we run in production for a long time. The memory_consumption is basically dependent on the code size, after warming up the opcache, just check the stats to see what min size is required.

This will need though, the awareness, that running opsense-patch will require and php-fpm reload or just an opcache flush with `cachetool opcache:reset` (https://github.com/gordalina/cachetool)
This is optional, you can just reload fpm with the same effect. To make it more convinient there might be a patch in opnsense-patch to do that out of the box, instead of relying on documentation.

**Comment by fichtner** [comment]
initial thoughts:
* in general it would be nice to plug in a cache
* opnsense-patch shouldn't be the focus here
* in the past we removed hand-rolled caches as they would only introduce latent bugs. and I think APC went away a few years ago so we never had a built-in cache except what phalcon may be doing.

**Comment by AdSchellevis** [comment]
We could consider making it optional, like the compression settings we have in the administration section. There are some downsides in using caching, but maybe our situation changed over time too. 

It's probably a good idea to measure the affect in real life before doing anything structural.

**Comment by EugenMayer** [comment]
APC and OPCACHE is fairly different. Also for having a switch for this first, probably announce in the release notes and give people an issue link for feedback.

Right now, there is only one downside of using opcache this way, and thats hot-patching.

**Comment by fichtner** [comment]
I know, I just wanted to mention the history with APC for completeness. ;)

And, again, opnsense-patch is a non-issue here. It’s a secondary tool, it can’t even be used automatically anymore for security reasons.

**Comment by EugenMayer** [comment]
We are using those opcode caches for about 7 years no in heavy duty. APC was a little trickier to configure and understand, especially since it was not PHP code and was not too well maintained. Still the effort was more then worth it, it was very much underestimated due to the fact, that people did not use the read-cache.

Opcache is a different story, core maintained, even the defaults work out very well and there is little to care about. Fine-Tuning it, as with APC, has a huge effect on some systems with a specific signature - e.g. like Drupal. OPNsense has a very similar signature - a lot of files, framework based, no static autoloader, heavy include usages.

I expect a speed up about 2-5 times on average usage if right now no opcache is used. On systems like rpi it should be higher. 

Especially interesting is, that the CPU usage is a lot lesser, that means, actual routing is not affected by REST / GUI browsing.

i think @AdSchellevis got it pretty right, lets have this as a tuneable for now to gather data, if you feel scared by the idea - i think that is a reasonable conservative approach - considering the type of system i would second that very much.
