### ISSUE TITLE
Renaming a VLAN description breaks assigned interface

### ISSUE THREAD

**Issue by johnkeates** [opnsense/core#2321]
There seems to be a bug somewhere (either in the GUI or in configd), changing the description of a VLAN disables the interface.

Procedure:
1. Create VLAN
2. Assign interface to VLAN
3. Apply & Save everything
4. Go back to VLAN, edit description, save

Expected outcome:
User defined description string on the VLAN is saved, everything keeps running

Outcome due to bug:
Assigned interface stops working, loses its IP in the GUI and on the network, need to connect using a backup interface or via console to fix. From the GUI, this can be fixed by simply going the to broken interface, and without changing anything simply saving + applying it. This probably triggers configd to reconfigure the broken interface.

**Comment by AdSchellevis** [comment]
@johnkeates thanks for reporting, https://github.com/opnsense/core/commit/c9f22da31ee873127ba1d852d19aa19f6739af39 prevents the reconfigure when not needed.
