### ISSUE TITLE
cannot define table bogonsv6: Cannot allocate memory

### ISSUE THREAD

**Issue by funar** [opnsense/core#2322]
OPNSense Version: 18.1.5
Server: Dell R610 48gb RAM.

When "Block bogon networks" is enabled on the WAN interface, the following error can be observed in the system log and the firewall is unable to pass traffic.  Disabling "Block bogon networks" restores functionality.

/tmp/rules.debug:15: cannot define table bogonsv6: Cannot allocate memory

Clearing the bogonv6 file and forcing an update yields the same results.

**Comment by AdSchellevis** [comment]
Increase "Firewall Maximum Table Entries" in Firewall -> Settings -> Advanced and please search our forum (https://forum.opnsense.org/index.php?topic=4524.msg17290#msg17290) and Github (https://github.com/opnsense/core/issues/1555)  before posting new issues.

**Comment by fichtner** [comment]
The bogons seem to have changed recently, causing more memory to be used and exceeding our defaults. Would it be possible to raise our defaults?

**Comment by AdSchellevis** [comment]
@fichtner we trust the defaults of pf when not set explicitly, which should usually be enough (on my machine with 2GB memory, the number seems to be 200.000)

**Comment by tjaalton** [comment]
the default doesn't seem to scale with the amount of RAM, it's still 200k with 4GB and not enough for the current bogon list..

**Comment by fichtner** [comment]
the default is mandated by some arbitrary never-changing OS variable. we don't handle it, but this should help:

fc0c66e87b54903d770fbffcab783ca28fa08e8c
5dd172ed16c408e15163fa46cf1d70b2fc6e62db
