### ISSUE TITLE
Disabling root user doesn't show "Disabled User" icon.

### ISSUE THREAD

**Issue by syndgr** [opnsense/core#2323]
Version: 18.1.5

Minor cosmetic issue. Through web UI I disabled the root user but the icon does not show the user as disabled. This issue only affects the root user. Cannot reproduce with any other user and group membership does not have any influence.

![image](https://user-images.githubusercontent.com/20760738/38236961-b030f7b6-371d-11e8-9e9e-115de08d5807.png)

![image](https://user-images.githubusercontent.com/20760738/38236983-c13efdc8-371d-11e8-8110-0bf610a9ef48.png)

**Comment by fichtner** [comment]
Hi @syndgr,

Indeed, thanks for your report!

You can try the proposed change from the console:

    # opnsense-patch ae119d5


Cheers,
Franco

**Comment by syndgr** [comment]
Hey @fichtner,

Tested and confirmed this has fixed the cosmetic issue. Thank you!

**Comment by fichtner** [comment]
perfect, thanks! We'll add this to 18.1.6 :)
