### ISSUE TITLE
Changes to static dhcp leases in 18.1.5 or 18.1.4

### ISSUE THREAD

**Issue by EugenMayer** [opnsense/core#2330]
I am yet not entirely sure, but it seems like since either .5 or .4 dhcp leases are renewed way to often, especially considered they are actually all static leases:

https://www.pastiebin.com/5ac4fcfa97a53
https://drive.google.com/file/d/1jmqzaQCRiaKxq8cuvbAPxlukdkc6rREM/view

Did anything change regarding the leases, e.g. for static leases?

I am yet not sure, but is this actually "interruptive"? I was debugging an NFS / psql issue with the server above, getting random disconnects / connection issues - are those DHCP acks going to reset the interface and thus cause interruptions?

That aside, is this the desired behavior for static leases? Seems to be, it does not really make a lot of sense for those, does it?

**Comment by fichtner** [comment]
https://github.com/opnsense/changelog/blob/master/doc/18.1/18.1.5
https://github.com/opnsense/changelog/blob/master/doc/18.1/18.1.4

**Comment by EugenMayer** [comment]
since there is nothing in the changelogs, which i already reviewed before asking here, its common sense this means there cannot be any bug - since bugs would be in the changelog :)

Anyway, signal taken.

**Comment by fichtner** [comment]
Sorry, you misread my intention. No changes were mentioned by you, also no going through the changelog and coming up empty. So please don’t take my help for something that is less forthcoming.

ISC-DHCP port was bumped in 18.1.4, not sure if related, but something that sticks out:

    # opnsense-revert -r 18.1.3 isc-dhcp43-server

**Comment by EugenMayer** [comment]
@fichtner i was not sure how to take a comment without any comment i guess.

````
opnsense-revert -r 18.1.3 isc-dhcp43-server
```

are you suggesting running that revert and see if something is changing? 
Reading the changelogs is way harder for me then it might be for you i guess

My general question is, what is the expectation for "static leases" - should / is there a lease time communicated to the dhclient at all? is ( should ) it be the same as in cases where we use a dynamic lease?

My expectation would be, that static leases either have an infinit lease time or at least a far higher then dynamic leases - the latter can be configured in dhcp in opnsense ( i guess that value is the same for both then? )

---

If my expectation / assumption is wrong in the first place, the question if that actually "changed"
