### ISSUE TITLE
i211: CARP goes to INIT on after link down/link up

### ISSUE THREAD

**Issue by ruffy91** [opnsense/core#2339]
Hi.
Hardware: 2x APU2C4 with 3x i211 interfaces.
Software: OPNSense 18.1.5/18.1.6
Problem: carp goes to init after link down/link up event.
Steps to reproduce:
1. Make HA/CARP config on the firewalls
2. Pull out carp interface cable from Primary firewall => Secondary Firewall gets Master status
3. Plug in carp interface cable to master firewall => Primary interface gets Backup status => Primary interface gets Master status (Primary Firewall is promoted) => Primary Firewall goes to Init
The logs are as follows:

igb1: link state changed to DOWN # Step 1
carp: 3@igb1_vlan221: MASTER -> INIT (hardware interface down)
carp: demoted by 240 to 240 (interface down)
igb1_vlan221: link state changed to DOWN
igb1: link state changed to UP # Step 1
carp: 3@igb1_vlan221: INIT -> BACKUP (initialization complete)
igb1_vlan221: link state changed to UP
carp: demoted by -240 to 0 (interface up)
igb1_vlan221: promiscuous mode disabled
carp: demoted by 240 to 240 (pfsync bulk start)
ifa_maintain_loopback_route: deletion failed for interface igb1_vlan221: 3
ifa_maintain_loopback_route: deletion failed for interface igb1_vlan221: 3
carp: 3@igb1_vlan221: BACKUP -> INIT (hardware interface up)
igb1_vlan221: promiscuous mode disabled

And now nothing happens until I disable and enable CARP on the Primary Firewall which brings it up as Master again.

**Comment by fichtner** [comment]
Tunable might help: https://forum.opnsense.org/index.php?topic=5412.msg22460#msg22460

**Comment by fichtner** [comment]
i211 drivers get an update in OPNsense 18.7.
