### ISSUE TITLE
Crash after changing GUI from HTTPS to HTTP

### ISSUE THREAD

**Issue by crosscutrat** [opnsense/core#2340]
Default config is to use HTTPS for the GUI.  Got everything configured and was working fine.  Changed GUI to use HTTP instead of HTTPS and got an interesting warning that the page should auto load and if not click here "10.0.0.1://10.0.0.1/blah/blah".  Somehow the variable for "http" is getting replaced with the LAN IP.  Bricked the box and won't boot up.  Console hung on interfaces and would never continue.   This has happened twice now on a nano image and a different box using the installer.

**Comment by fichtner** [comment]
The bricking is unusual, it just switches the proto and reloads. I'll take a look...

**Comment by fichtner** [comment]
Hi Rob,

Worked fine from here:

<img width="636" alt="screen shot 2018-04-12 at 10 37 03 pm" src="https://user-images.githubusercontent.com/1915288/38702940-38b14948-3ea2-11e8-9f0d-4e67906d7cfd.png">

Had to click the link but that's a different story and why the link was added: Switching HTTP <-> HTTPS is a bit of a pickle as browsers don't like the downgrade or upgrade in the same window.

What browser are you using? What extra settings did you set?


Cheers,
Franco

**Comment by fichtner** [comment]
PS: If "http://" or "https://" is ending up being displayed as IP:// that would mean something goes completely wrong on POST. It's not verified what the radio button pushes as a value so if there is an IP in there I can understand the brick afterwards... let me add a validation at least...

**Comment by fichtner** [comment]
I just experienced the "brick": The browser refuses to open HTTP after having been warmed up to the idea of HTTPS. And it does a really bad job telling you it rather wants to open HTTPS while it shows HTTP not responding (Chrome). Opened Firefox, all good on HTTP....

**Comment by fichtner** [comment]
Firefox and Safari show similar issues after switching around more than once. I think we can close this as there is not much we can do?

**Comment by fichtner** [comment]
I'm assuming that's a yes. :)
