### ISSUE TITLE
Duplicate VLANs when using the console to setup interfaces

### ISSUE THREAD

**Issue by fvanroie** [opnsense/core#2342]
I think commit [566fe52](https://github.com/opnsense/core/commit/566fe52edcdde2e5d9dd6148d856891a20176afb#diff-9aa2355a793265d8d68f412dface2f38) introduced an issue while configuring VLANs using the "1) Assign interfaces" option in the console. (src/etc/inc/console.inc)

When you choose to setup VLANs via the console interface, it warns you that existing VLANs will be cleared:
WARNING: all existing VLANs will be cleared if you proceed!

However, this is not the case and when you enter the VLANs at the next prompts, you will end up with duplicate VLANs in the config. So the existing VLANs are not cleared like the warning message says and there is no check for duplicate VLAN IDs.

I tried removing these duplicates in the GUI, but it won't let me delete them because some are 'in use'.

**Comment by fvanroie** [comment]
No problem. Meanwhile, I have found a workaround by exporting the config and re-importing the VLANs with the duplicated removed from the config.xml file. Now all my VLANs are listed only once.

**Comment by fichtner** [comment]
@fvanroie thanks for your spot-on analysis. committed a fix just now. :)

**Comment by fvanroie** [comment]
That was quick, glad I could help. I'll try this out in the next release.

**Comment by fichtner** [comment]
Had to tweak the whole VLAN configuration process so this will not be in 18.1.7..... not sure when it'll be released. I try to ping when it's in. :)
