### ISSUE TITLE
LibreSSL flavor doesn't use aesni

### ISSUE THREAD

**Issue by h-2** [opnsense/core#2343]
Coming here from #222 

LibreSSL does not seem to be able to make use of AES-NI:

|                      |   speed |
|----------------------|--------------:|
| openssl -evp | 390 MB/s|
| openssl         |  86 MB/s|
|  libressl -evp |   55 MB/s|
|  libressl         |   55 MB/s|

(all of the above is 8KB, aes-128-cbc)

Long log:
```
root@fire:~ # openssl speed -evp aes-128-cbc
OpenSSL 1.0.2k-freebsd  26 Jan 2017
built on: date not available
options:bn(64,64) rc4(16x,int) des(idx,cisc,16,int) aes(partial) idea(int) blowfish(idx) 
compiler: clang
The 'numbers' are in 1000s of bytes per second processed.
type             16 bytes     64 bytes    256 bytes   1024 bytes   8192 bytes
aes-128-cbc     259552.04k   346362.11k   368229.12k   385205.63k   390116.57k

root@fire:~ # openssl speed  aes-128-cbc
OpenSSL 1.0.2k-freebsd  26 Jan 2017
built on: date not available
options:bn(64,64) rc4(16x,int) des(idx,cisc,16,int) aes(partial) idea(int) blowfish(idx) 
compiler: clang
The 'numbers' are in 1000s of bytes per second processed.
type             16 bytes     64 bytes    256 bytes   1024 bytes   8192 bytes
aes-128 cbc      32988.44k    36508.98k    37855.04k    85214.55k    86029.65k

root@fire:~ # /usr/local/bin/openssl speed -evp aes-128-cbc
LibreSSL 2.6.4
built on: date not available
options:bn(64,64) rc4(ptr,int) des(idx,cisc,16,int) aes(partial) idea(int) blowfish(idx) 
compiler: information not available
The 'numbers' are in 1000s of bytes per second processed.
type             16 bytes     64 bytes    256 bytes   1024 bytes   8192 bytes
aes-128-cbc      45461.70k    52489.94k    54501.63k    55128.06k    55235.93k

root@fire:~ # /usr/local/bin/openssl speed aes-128-cbc
LibreSSL 2.6.4
built on: date not available
options:bn(64,64) rc4(ptr,int) des(idx,cisc,16,int) aes(partial) idea(int) blowfish(idx) 
compiler: information not available
The 'numbers' are in 1000s of bytes per second processed.
type             16 bytes     64 bytes    256 bytes   1024 bytes   8192 bytes
aes-128 cbc      50298.05k    53927.98k    54856.77k    55211.87k    55160.47k
```

Also note how the performance differs between the (block?) sizes in OpenSSL, but not in LibreSSL :question: 

VERSIONS:
OPNsense 18.1.5-amd64
FreeBSD 11.1-RELEASE-p8
LibreSSL 2.6.4

**Comment by h-2** [comment]
Thanks for looking into this! 

> LibreSSL 2.6 seems to have broken their assembler inclusion switch in the portable version. First attempts to undo this ended in compiler errors...

Yeah, I heard that the "for other OS" - versions of OpenBSD tools receive a lot less love, but I would have hoped for something like LibreSSL to have upstream regression testing...

**Comment by fichtner** [comment]
Even OpenSSL was shipped without assembler bits in FreeBSD ports for a while... because it is a difficult regression to observe as it passes all checks... :)

Will try again tomorrow.

**Comment by fichtner** [comment]
Here's a report of the same issue, but with inconclusive outcome https://forums.freebsd.org/threads/openssl-almost-10x-faster-than-libressl.64497/
