### ISSUE TITLE
Apollo lake boot hang

### ISSUE THREAD

**Issue by h-2** [opnsense/core#2344]
I thought I'd reference https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=222908 here since it will probably affect more people with Apollo lakes now becoming more widely available and being good firewall CPUs. 

FreeBSD seems to be slow to act so maybe even OpnSense could add the workaround for the next round of install images (if an affected CPU is detected)?

If you feel that upstream needs to fix this, you can of course close it again :wink:

**Comment by fichtner** [comment]
It's hard to work around hardware-specific issues in a way that nobody not affected is not affected in some other way. But since 18.1.5 at least you can use system: settings: tunables to also hold and enforce your loader.conf settings. It's not much, but it eases config import / export a bit as the settings are kept (minus the initial boot fix).

**Comment by fichtner** [comment]
Fix was committed as https://svnweb.freebsd.org/base?view=revision&revision=333026 but we need to wait for the MFC to stable/11 before we can pull it as the code surrounding this changed and the backport isn't trivial.

**Comment by h-2** [comment]
Thanks a lot!

**Comment by fichtner** [comment]
hi @h-2,

Preliminary patch here, need to build and test tomorrow:

https://github.com/opnsense/src/commit/eb2d1233f30605387e3934bef6a658eadede9391

It's difficult to backport cleanly without pulling in a number of unrelated changes so I wrote a different version for 18.7.

More on this tomorrow. :)


Cheers,
Franco

**Comment by fichtner** [comment]
@h-2 Patch compiles and doesn't do bad things so that's a good start. Now we need your hardware to confirm. I can provide a test image to boot if you want.

**Comment by fichtner** [comment]
Can't ship this without testing. We'll try to fix this in 19.1 via HardenedBSD 11.2 anyway.

**Comment by h-2** [comment]
Sorry that I did not reply to this. Everything boots up fine with 19.1!
