### ISSUE TITLE
No login prompt / userspace output on serial console

### ISSUE THREAD

**Issue by h-2** [opnsense/core#2345]
I recently installed OPNSense on a Gigabyte J3455N-D3H. After some initial trouble the system is now running, but the serial port doesn't work as expected:

I get kernel messages up until:
```
Trying to mount root from ufs:/dev/ufs/OPNsense_Nano [rw]...
Mounting filesys
```

It then stops midword and shows no login prompt or output from rc. It will however print kernel messages if I shutdown or plug-in a removable disk.

Or is this expected behaviour and I need to change further settings?

PS: primary console is set to VGA, secondary to serial, but I also had these issues when booting the minimal img.

VERSIONS:

OPNsense 18.1.5-amd64
FreeBSD 11.1-RELEASE-p8
LibreSSL 2.6.4

**Comment by fichtner** [comment]
unfortunately, that is the expected behaviour. init messages are only printed on the primary console so if you use that primarily, switch vga and serial.

**Comment by fichtner** [comment]
or wait, maybe it should at least prompt for login afterwards. it could also mean the serial needs a loader hint as well. just guessing :)

**Comment by h-2** [comment]
> unfortunately, that is the expected behaviour. init messages are only printed on the primary console so if you use that primarily, switch vga and serial.

No, but its the other way around for me: I get kernel output on both, but I don't get a login on serial. 

> or wait, maybe it should at least prompt for login afterwards. it could also mean the serial needs a loader hint as well. just guessing :)

Also I had the same behaviour with the minimal-img which only boots to serial and no vga. I also didn't get a prompt or output from rc – which is why I thought it was broken, but it did boot up in the background.

**Comment by fichtner** [comment]
What does this output on the board?

    # ls -lah /dev/tty*

**Comment by h-2** [comment]
```
# ls -lah /dev/tty*
crw-------  1 root  wheel   0x30 Apr  3 21:19 /dev/ttyu0
crw-------  1 root  wheel   0x31 Apr  3 21:18 /dev/ttyu0.init
crw-------  1 root  wheel   0x32 Apr  3 21:18 /dev/ttyu0.lock
crw-------  1 root  wheel   0x36 Apr  3 21:18 /dev/ttyu1
crw-------  1 root  wheel   0x37 Apr  3 21:18 /dev/ttyu1.init
crw-------  1 root  wheel   0x38 Apr  3 21:18 /dev/ttyu1.lock
crw-------  1 root  wheel   0x48 Apr  3 21:19 /dev/ttyv0
crw-------  1 root  wheel   0x49 Apr  3 21:19 /dev/ttyv1
crw-------  1 root  wheel   0x4a Apr  3 21:19 /dev/ttyv2
crw-------  1 root  wheel   0x4b Apr  3 21:19 /dev/ttyv3
crw-------  1 root  wheel   0x4c Apr  3 21:19 /dev/ttyv4
crw-------  1 root  wheel   0x4d Apr  3 21:19 /dev/ttyv5
crw-------  1 root  wheel   0x4e Apr  3 21:19 /dev/ttyv6
crw-------  1 root  wheel   0x4f Apr  3 21:19 /dev/ttyv7
crw-------  1 root  wheel   0x50 Apr  3 21:18 /dev/ttyv8
crw-------  1 root  wheel   0x51 Apr  3 21:18 /dev/ttyv9
crw-------  1 root  wheel   0x52 Apr  3 21:18 /dev/ttyva
crw-------  1 root  wheel   0x53 Apr  3 21:18 /dev/ttyvb
```
I haven't checked, yet, whether the kernel might output to the first serial port and the userland to the second one :thinking:

**Comment by fichtner** [comment]
it looks normal, and both are being enabled. maybe this is a driver bug in combination with the hardware. can't spot any obvious problem, it works on countless devices as is.

**Comment by roger225** [comment]
I have the same problem,too.
This issue will happen on J3455B-itx but DN2800MT.
And look like the serial console can not get any input, it will not response for keyboard input.
It will also cause NTP can not get GPS PPS timestamp signal from serial port.

# ls -lah /dev/tty*
crw-------  1 root  tty     0x36 Jun 18 18:07 /dev/ttyu0
crw-------  1 root  wheel   0x37 Jun 18 18:07 /dev/ttyu0.init
crw-------  1 root  wheel   0x38 Jun 18 18:07 /dev/ttyu0.lock
crw-------  1 root  wheel   0x3c Jun 18 18:07 /dev/ttyu1
crw-------  1 root  wheel   0x3d Jun 18 18:07 /dev/ttyu1.init
crw-------  1 root  wheel   0x3e Jun 18 18:07 /dev/ttyu1.lock
crw-------  1 root  tty     0x4f Jun 18 18:07 /dev/ttyv0
crw-------  1 root  tty     0x50 Jun 18 18:07 /dev/ttyv1
crw-------  1 root  tty     0x51 Jun 18 18:07 /dev/ttyv2
crw-------  1 root  tty     0x52 Jun 18 18:07 /dev/ttyv3
crw-------  1 root  tty     0x53 Jun 18 18:07 /dev/ttyv4
crw-------  1 root  tty     0x54 Jun 18 18:07 /dev/ttyv5
crw-------  1 root  tty     0x55 Jun 18 18:07 /dev/ttyv6
crw-------  1 root  tty     0x56 Jun 18 18:07 /dev/ttyv7
crw-------  1 root  wheel   0x57 Jun 18 18:07 /dev/ttyv8
crw-------  1 root  wheel   0x58 Jun 18 18:07 /dev/ttyv9
crw-------  1 root  wheel   0x59 Jun 18 18:07 /dev/ttyva
crw-------  1 root  wheel   0x5a Jun 18 18:07 /dev/ttyvb
ls -lah /dev/cuau*
crw-rw----  1 uucp  dialer   0x39 Jun 18 18:07 /dev/cuau0
crw-rw----  1 uucp  dialer   0x3a Jun 18 18:07 /dev/cuau0.init
crw-rw----  1 uucp  dialer   0x3b Jun 18 18:07 /dev/cuau0.lock
crw-rw----  1 uucp  dialer   0x3f Jun 18 18:07 /dev/cuau1
crw-rw----  1 uucp  dialer   0x40 Jun 18 18:07 /dev/cuau1.init
crw-rw----  1 uucp  dialer   0x41 Jun 18 18:07 /dev/cuau1.lock

**Comment by fichtner** [comment]
Looks like the same class of hardware. Ideally, we'd need to figure out which settings a stock FreeBSD 11.1 needs on this hardware to work or if 11.2 works nowadays.

**Comment by fichtner** [comment]
11.2 is on the way ... beta for 19.1 almost out.
