### ISSUE TITLE
OpenDNS Test Login Fails if Password Contains Single Quote(s)

### ISSUE THREAD

**Issue by dlcasto** [opnsense/core#2346]
I am using a long, randomly generated password for OpenDNS. I experienced issues when I tried trouble testing the login and signing into OpenDNS in the Services section. So I regenerated my password and tried a smaller password length since I have had issues in other applications where the maximum password lengths are different in applications that log into other applications. When I changed it, I was able to sign in and use the OpenDNS service.

Looking at the code (core/services_opendns.php), I am thinking that the single quote in the password string is causing issues on line 65 since single quotes in the password string are not escaped:

``curl_setopt($ch, CURLOPT_USERPWD, sprintf('%s:%s', $pconfig['username'], $pconfig['password']));``

I could be mistaken and overlooked if the password string is being escaped prior to logging into OpenDNS, but I do know that there exists a condition in which certain passwords cause the test/login to OpenDNS to fail.

This issue exists on 17.7 and 18.1. I haven't tested any other versions (since I am new to OPNsense and haven't used any older versions).

**Comment by fichtner** [comment]
Hi @dlcasto,

The single quotes in the sprintf interpolated by %s does not escape the format string's single quotes, that's why this is the safe way to write the option. Not sure what goes wrong here, it pushes the user/pass to PHP/CURL and that's it unless the password is not correct in $pconfig['password'] -- maybe it's  HTML escaped?


Cheers,
Franco

**Comment by dlcasto** [comment]
@fichtner, thanks for the feedback. I realized that I was a bit confused when I looked up information about the difference between single and double quotes using sprintf in PHP. I know that sometimes you can use double quotes to treat single quotes as literals and vice-versa which is handy if you prefer not to escape single or double quotes.

I looked at my old password in my password manager and it also contains the special characters "?" and ":" which I think could be potentially problematic depending on how PHP CURL generates URLs and posts data. It's not a huge problem since changing to a different password resolves the issue. However, it would be nice if all valid OpenDNS passwords could be used in OPNsense without issue.

**Comment by fichtner** [comment]
Still not sure what's going on. Given the username does not allow ":" there is nothing wrong with the code:

https://stackoverflow.com/questions/26285094/proper-way-to-curl-authorization-basic-with-a-hash

Looking at the sprintf reveals no double-encoding issues. I'd say be wary of the ":" character in the password. In theory it shouldn't matter, but in a real world setting maybe the server handles it incorrectly. There's no indication the client-side makes a mistake at least.

**Comment by JasMan78** [comment]
I'd the same problem with $ and % in my password for OpenDNS and OPNsense 18.1.9. 
I've changed the password to one with only upper/lower case letters, numbers and some exclamation marks. That works.
