### ISSUE TITLE
Unstable behaviour since V6/DHCPv6

### ISSUE THREAD

**Issue by kingfisher77** [opnsense/core#2352]
Since we switched to Dual Stack v4/v6 Opnsense behaves unstable. From time to time no ip traffic is possible anymore. 

`There were error(s) loading the rules: /tmp/rules.debug:15: cannot define table bogonsv6: Cannot allocate memory - The line in question reads [15]: table <bogonsv6> persist file "/usr/local/etc/bogonsv6"`

Cannot allocate memory? We run this cute thing: https://www.applianceshop.eu/security-appliances/opnsense-small-ghz.html with 2G Memory. Is this to small?

Should we create a swap space?

What are these bogons and bogonsv6 files for?

**Comment by fichtner** [comment]
set firewall: settings: advanced: table entries to "500000"

**Comment by fichtner** [comment]
(ipv6 bogons are like its ipv4 cousing a long list of subnets that should not occur in the wild and are therefore blocked by default and updated regularly)

**Comment by fichtner** [comment]
(shipped a permanent fixup in 18.1.7)
