### ISSUE TITLE
CARP VIP should not require existing IP

### ISSUE THREAD

**Issue by lschweiss-wustl** [opnsense/core#2358]
It seems CARP no longer requires an existing IP on the interface it is assigned.   This requirement should be removed from OPNsense.   

Besides pfsense has done this since their version 2.2.

**Comment by mimugmail** [comment]
Why not choose some private unused IP in the main interface?

**Comment by lschweiss-wustl** [comment]
Because I do not use NAT, and there appears to be no other way to make outgoing connections use the CARP IP instead of an unneeded preconfigured IP.   This also causes split routes that break connections with some systems.


________________________________

**Comment by mimugmail** [comment]
Oh you mean like local squid binding to a specific IP for outgoing connections?

**Comment by fichtner** [comment]
As far as I know a rule of carp is to never use the carp ip for creating connections, only for answering, which would mean you need a regular IP as well. Do you have a reference when and where this restriction was lifted in FreeBSD?

**Comment by AdSchellevis** [comment]
I don't think it's a problem to remove the constraint, although I can't find a reference for the intended behaviour in FreeBSD on this topic (it seems to work, the doc's don't seem to suggest otherwise)

I do have the changes needed stashed on my machine, if we want this, I can commit them.

**Comment by AdSchellevis** [comment]
... on the plus side, this dumps two other pointless _file_notice()_ executions as well

**Comment by mimugmail** [comment]
It would also make HA setup possible where WAN is only /30

Ad Schellevis <notifications@github.com> schrieb am Sa., 14. Apr. 2018,
14:28:

**Comment by AdSchellevis** [comment]
@fichtner are you ok with ditching the validation too?

**Comment by fichtner** [comment]
fine by me, but will not look at kernel bugs related to this. it sounds like a protocol violation unless someone shares the details and related FreeBSD code changes.
