### ISSUE TITLE
Password duration: exclude for sync/HA account ?

### ISSUE THREAD

**Issue by linuxmail** [opnsense/core#2361]
hi,

we have enabled the password duration for 90 days. I assume, that it also is active for the sync/HA account. So it would break after -- for example 90 days -- the config / firewall sync to the secondary node. Correct ?

If so, it would be good to exclude the duration option for the username/account, which is used for sync the configuration.

**Comment by fichtner** [comment]
The password expires, but you are still able to log in and set a new one. It just forces you to change it.
