### ISSUE TITLE
Captive Portal: Voucher overview style issue

### ISSUE THREAD

**Issue by DokuKaefer** [opnsense/core#2362]
Hello everybody

with Firefox (59.0.2) i get the follwoing style issue in the voucher overview when i switch between vouchers. Chorme and IE do not have this effect.

![vouchers](https://user-images.githubusercontent.com/11537653/38827487-5e1e2994-41b3-11e8-926e-1a8af235e200.png)

OPNsense 18.1.6

@fichtner I hope the ticket is okay. :) 

Regards
Andreas

**Comment by fichtner** [comment]
Hi Andreas,

Thanks for this, I'll try to find it if @AdSchellevis doesn't beat me to it :)


Cheers,
Franco

**Comment by AdSchellevis** [comment]
@fichtner almost found it, will fix in a minute

**Comment by AdSchellevis** [comment]
@DokuKaefer can you test https://github.com/opnsense/core/commit/c716d2cf1b17f7b4e7d19f7a17f1af743c26dfd1 ?

**Comment by fichtner** [comment]
hehe, briljant!

**Comment by AdSchellevis** [comment]
:) seems like firefox didn't like the unused grid_clients assignment

**Comment by DokuKaefer** [comment]
That was fast. :) It works!
Thanks Ad.

**Comment by AdSchellevis** [comment]
your welcome

**Comment by fichtner** [comment]
Will go into 18.1.7, thanks all!
