### ISSUE TITLE
Add custom.inc include to Unbound

### ISSUE THREAD

**Issue by mimugmail** [opnsense/core#2365]
Like in #2268 we should add an empty custom config for unbound. 
This could be an easy way to integrate a plugin like pfBlocker without too much user interaction.

Just an idea, not sure how compatible this would be with legacy unbound code and mvc (with new plugin).

**Comment by fichtner** [comment]
We do have a custom block, it doesn't make any sense to add a file as well?

**Comment by fichtner** [comment]
(the advanced block is in config.xml, the extra file will not be)

**Comment by mimugmail** [comment]
Is it allowed for a plugin to add entries there?

**Comment by fichtner** [comment]
no, this changes the nature of the request and how it useful it is but also means quite a bit of work... why move unbound features to a separate plugin?

we need to talk about which settings you want and why... :)

**Comment by mimugmail** [comment]
I was just thinking about solution to make ad/malware blocking easier with a plugin.
But half of it depends on DNS / Unbound and an empty config file which is already loaded might make it easier for the UX. 

I'm not demanding it, was just an idea, but if it breaks I'm also happy to move this topic :)

**Comment by fichtner** [comment]
but what about the people who use dnsmasq?

it brings you back to discussions to use aliases for other things like shaper, routing (a recent request), and dns... I'd say the means are there, but it needs to be carried out. but I don't know if there are hostname-only aliases...

**Comment by AdSchellevis** [comment]
It's probably easier to just add imports (a bit like the remote blacklists in squid) for unbound to map zones to localhost, that's what most of these solutions seem todo. Please don't clutter this with the alias system, it will likely increase complexity there and for most scenario's you don't want all these entries in the filter table anyway.

**Comment by mimugmail** [comment]
My idea is to load managed hostsfile. For unbound convert it with a script and put it in the custom include.
For dnsmasq you could use the initial host file loaded via:

```
# If you don't want dnsmasq to read /etc/hosts, uncomment the
# following line.
#no-hosts
# or if you want it to read another file, as well as /etc/hosts, use
# this.
#addn-hosts=/etc/banner_add_hosts
```

I wouldn't manage it via aliases would be a mess when there are more than 1000 :)

**Comment by AdSchellevis** [comment]
unbound probably needs some work, but I would keep it in a clean spot there (In the override section?). 
Something like a definition which points to an url to include and with a configd call to refresh/reload it. 
I don't have the time to really look into the most logic spot for this at the moment.

**Comment by mimugmail** [comment]
You don't have to look at it intensively, just a discussion what's possible or not, or makes sense or not. 
We can close for now and reopen when there's more time.
