### ISSUE TITLE
Append version string to resources to enforce reload after updating

### ISSUE THREAD

**Issue by Kimmax** [opnsense/core#2367]
TL;DR:
Add `v=<Version>` to script and style resources to force reload them after updating opnsense, while keeping the caching functionality of browsers intact.

I ran into cache problems after a script was updated and my browser refused to load the new one. While this is not a big problem, it's a known one that can be easily mitigated by appending a `v=<Version>` string to the URL's of said resources. While browsers still cache them, changing the version number, e.g. after an update, forces the browser to treat the resource as a new one, which is guaranteed to be loaded from the server.

**Comment by fichtner** [comment]
It's funny, because this has potential for a CVE especially if done on the login page as well as it is a version disclosure. So we'll skip the login page and try to discuss this further internally before shipping it. :)

**Comment by fabianfrz** [comment]
@fichtner If you want to do that, the /ui pages need it as well.

**Comment by fichtner** [comment]
no, this is only for ressources

**Comment by fabianfrz** [comment]
have not seen it - it is already done: https://github.com/opnsense/core/blob/master/src/opnsense/mvc/app/views/layouts/default.volt

**Comment by AdSchellevis** [comment]
We could generate a token after an update to avoid version leakage, the `cache_safe` function itself would remain the same and is likely the best way to do this.

@fabianfrz this code seems to break ui_devtools at the moment, which looks like your other issue.

**Comment by fichtner** [comment]
I thought commit hash as its more practical than generating a version tag for a machine operations, but in any case that inclusion process is settled for both "make install" (and "make upgrade" and all the package building) and could push an arbitrary string into it while doing the operation. The git hash avoids collisions, but the fact remains that the build-time string is not random after shipping it in a release and doing some pseudo-random runtime thingy seems over the top for the problem at hand.

**Comment by fabianfrz** [comment]
@fichtner stat can be used: md5(file creation time)

**Comment by fichtner** [comment]
That's still static on build time and you can identify the version from it...

**Comment by fabianfrz** [comment]
@fichtner no, it is dynamic (depends on install time). A single nanosecond would give another hash

**Comment by fichtner** [comment]
But then we'd have to write firmware-upgrade or some other arbitrary file or possibly the config.xml which I wanted to avoid in the first place because firmware-upgrade already offers data without overhead.

**Comment by fabianfrz** [comment]
no, just call stat on the file which is linked.
```php
opnsense/plugins% echo '<?php $file = "LICENSE"; echo $file . "?" . md5(stat($file)["mtime"]) ?>' | php
LICENSE?eba2cb72eed8a4689ebc202bca9d5146
```

**Comment by fichtner** [comment]
Ok, this seems ready for general release https://github.com/opnsense/core/commit/4178038 from my side in 18.7.4 after a final testing round in 18.7.3. Some plugins need to be adjusted later though...
