### ISSUE TITLE
DynDNS trouble with public IP with Router

### ISSUE THREAD

**Issue by gertfriend** [opnsense/core#2368]
Sometimes the DynDNS Service pushes a private public IP to the DynDNS Service and does not update it if the public IP doesn't change. This happens if there is a router with NAT before the firewall. So if the Router has a LAN-IP of 192.168.0.1 and the OPNsense 192.168.0.10 as WAN-IP the DynDNS-Service will publish the 192.168.0.10 as the WAN-IP and not the public Internet WAN IP.

**Comment by fichtner** [comment]
Do you have the system logs for this? It should be impossible to push a private IP according to the code and use of an external IP probing service.

**Comment by gertfriend** [comment]
Here the log:

Apr 4 01:11:00 	opnsense: /usr/local/etc/rc.dyndns: Dynamic DNS (xxx.dyndns.provider): No change in my IP address and/or 25 days has not passed. Not updating dynamic DNS entry.
Apr 3 22:22:29 	opnsense: /usr/local/etc/rc.dyndns: Dynamic DNS: (Success) Update successful
Apr 3 22:22:29 	opnsense: /usr/local/etc/rc.dyndns: Dynamic DNS: updating cache file /var/cache/dyndns_wan_xxx.dyndns.provider_0.cache: 185.121.X.X
Apr 3 22:22:28 	configd.py: [3e808b97-adc8-4f00-a751-6ac535d28467] updating dyndns WANGW
Apr 3 22:22:26 	opnsense: /usr/local/etc/rc.dyndns: Dynamic DNS: (Success) Update successful
Apr 3 22:22:26 	opnsense: /usr/local/etc/rc.dyndns: Dynamic DNS: updating cache file /var/cache/dyndns_wan_xxx.dyndns.provider_0.cache: 192.168.1.10
Apr 3 22:22:26 	opnsense: /usr/local/etc/rc.dyndns: Aborted IP detection: Resolving timed out after 5797 milliseconds
Apr 3 22:22:09 	opnsense: /usr/local/etc/rc.dyndns: Aborted IP detection: Resolving timed out after 5710 milliseconds
Apr 3 22:22:03 	opnsense: /usr/local/etc/rc.dyndns: Aborted IP detection: Resolving timed out after 5691 milliseconds
Apr 3 22:21:57 	configd.py: [87112ac6-15fc-4797-9acc-609ab69381d7] updating dyndns WANGW

At line "Apr 3 22:22:29" states, that the update with the public IP was successful but it wasn't.

The DynDNS-Service is regfish.de

**Comment by fichtner** [comment]
Nice observation, thanks! I don't think this patches correctly on top of 18.1.6, but it's easy to add the line manually as seen in 1547ecc -- confirmation welcome

**Comment by gertfriend** [comment]
Thank you for the fast solution and the great work you do.
I'll try to confirm but it's difficult to observe the bug because it happen rarely.

**Comment by fichtner** [comment]
Sure thing! Then let's close and ship this in 18.1.7 and if this happens again just ping me, ok? :)

**Comment by gertfriend** [comment]
OK. Thanks.
