### ISSUE TITLE
ipsec: resolve_retry() is a pre-strongswan remnant?

### ISSUE THREAD

**Issue by fichtner** [opnsense/core#2369]
I spotted this wile browsing through util.inc ... should we just remove the function and its usage?

**Comment by AdSchellevis** [comment]
probably, strongswan should reverse lookup by itself in needs testing of dyndns (https://github.com/opnsense/core/blob/18.1.6/src/etc/inc/plugins.inc.d/ipsec.inc#L594) and hostnames as peer address (https://github.com/opnsense/core/blob/18.1.6/src/etc/inc/plugins.inc.d/ipsec.inc#L598)

**Comment by AdSchellevis** [comment]
ok, if I understand the docs correctly on this point, we should be able to ditch it and keep the same behaviour, a name without an @ prefix should resolve to an ipv4 address like it's doing now (https://wiki.strongswan.org/projects/strongswan/wiki/IdentityParsing)
