### ISSUE TITLE
Possiblity to use the firewall aliases in relevant input fields

### ISSUE THREAD

**Issue by bewue** [opnsense/core#2373]
e.g.:
- System: Settings: Logging: "Remote Syslog Servers"
- System: High Availability: Settings: "Synchronize Peer IP"
- VPN: IPsec: Mobile Clients: "Virtual Address Pool"
- VPN: OpenVPN: Servers: "IPv4 Tunnel Network"

...there are much more places.

This feature would be really helpful for a consistent configuration,
because you only have to change a IP a port or a hostname on one place (in the alias area).

edit:
I want to add more places which I consider important:
- Services: Unbound DNS: Overrides: hostname and IP
- Services: DHCPv4 | DHCPv6: [interface]: DNS servers, Gateway, Static Mappings (hostname and IP)

**Comment by C-Duv** [comment]
Also, in Unbound DNS's access lists (Services > Unbound DNS > Access Lists)?

**Comment by fixfinest** [comment]
Hi **fitcfitcfatc**,
These firewall aliases use cases are very handy and quit needed, i hope the great **Dev.** team consider these features it'll be great additions to our great firewall

Dev. Team take your time, u doing a great work we all appreciate it 
Thank u all

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository, 
please read https://github.com/opnsense/core/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue, 
just let us know, so we can reopen the issue and assign an owner to it.

**Comment by CrashNash** [comment]
After using pfSense for more than 18 months, i gave OPNSense a try.

I really liked everything about OPNSense more than pfSense but still some issues for me to make it my main firewall/router.

- using aliases in traffic shaping rules is a must for me.
- WireGuard is more complicated than pfSense which is not usable for simple user like me.

with better documentation and adding support for using aliases in traffic shaping i hope to make it.

**Comment by fichtner** [comment]
This is unlikely to change from a random post with multiple things that span core and plugins and third party repositories to a closed ticket from 2019. Just my two cents.

**Comment by CrashNash** [comment]
> This is unlikely to change from a random post with multiple things that span core and plugins and third party repositories to a closed ticket from 2019. Just my two cents.

is it that hard to make these changes, coz i really don't know.
just commented to give it a chance.
