### ISSUE TITLE
Web GUI not starting, due to duplicate IPv6 adresses.

### ISSUE THREAD

**Issue by gizahNL** [opnsense/core#2375]
This morning I noticed the webgui is no longer starting automatically. 

After some debugging I found out this is due to duplicate IPv6 adresses being inserted into /var/etc/lighty-webConfigurator.conf

My hunch is that this is possibly due to my configuration; where I have a bridge configured with a IPv6 ULA adress and a publicly routable IPv6 adress as alias (any other configuration will break dhcpv6 for the ULA net).
The last actions I have taken on this interface was taking out and reinserting into the bridge the openvpn interface, perhaps this triggered the reconfigure and insertion of duplicate IPv6 adresses. 
It should be noted that the ULA adress is /not/ automatically inserted into the webgui configuration.

[system.log](https://github.com/opnsense/core/files/1946106/system.log)
[dmesg.log](https://github.com/opnsense/core/files/1946107/dmesg.log)
[ifconfig.log](https://github.com/opnsense/core/files/1946110/ifconfig.log)

**Comment by fichtner** [comment]
Strict binding could cause this, which interfaces have you set for the GUI? In general the strict bindings works until it doesn't.

**Comment by gizahNL** [comment]
I've limited the binding to the LAN and WAN interfaces, so bridge0 and pppoe1 respectively. 

I would imagine it is doing something wrong in the binding foo and as a result tries to bind twice to the publicly routed ipv6 ip instead of binding to the public ipv6 and the ULA.

**Comment by fichtner** [comment]
A quick fix would be to deduplicate the entries to be written, but I'd like to know why this happens first.  Which one is the IP that is written twice?

**Comment by gizahNL** [comment]
The one getting duplicated is 2001:984:a1fc:1::1 

I've scanned the logfiles and have not seen anything interesting that could indicated as to a cause of duplicating entries. 

I could see if I can play around a bit somewhere this week, trying to find out the conditions to reproduce. 

For me it is not critical this moment; I can still ssh into the machine when needed and remove duplicate entries with vim and restart the webgui manually.

**Comment by fichtner** [comment]
It's not a duplicate in the ifconfig output you provided, which is odd. But, is that the virtual IP you spoke of which os manually configured?

**Comment by gizahNL** [comment]
Yes that one is configured as a virtual IP in the firewall tab. Due to the fact that I want to run a ULA prefix next to my global prefix, which I want to assign using dhcpv6. 
So the fdea address (ULA) is assigned on the interface as a static ipv6 like one normally would. 
Then the 2001 address (global) is assigned using the virtual IP interface.

**Comment by fichtner** [comment]
Thanks for explaining. Try this then:

    # opnsense-patch b2b926d

**Comment by fichtner** [comment]
Haven't heard back, but shipping in 18.1.7 due to low impact. :)

**Comment by gizahNL** [comment]
Yes the patch fixed the issue, though it seems it still is not correctly using the ULA address (it doesn't create a listening socket for the ULA address)

**Comment by fichtner** [comment]
lighttpd doesn't like link-local, probably the same for ULA (prefix fc00::/7)?

**Comment by fichtner** [comment]
Long story short, the only thing we can do for now is blacklist the ULA prefix as well.

**Comment by gizahNL** [comment]
No, it seems OPNSense foo is not detecting properly the ULA address ( fdea:8d1c:cac5:1::1), as it is not written into the config file for the WebGui

Not that it truly matters, it seems few are using ULA at this moment, and even fewer (*none*) care about GUI on ULA ;)

**Comment by fichtner** [comment]
It's not a VIP, is it? Where would that one come from if not a VIP? (sorry for maybe repeating a question)

**Comment by gizahNL** [comment]
No, it's configured as a static. The GUA address is configured as a VIP. 

That is due to the fact that the DHCPv6 server will only work with the configured IP on the interface; and I want stateless address assignment for the GUA range and statefull address assignment using DHCP for the ULA

**Comment by fichtner** [comment]
@gizahNL do you want to bind fdea:8d1c:cac5:1::1 or fdea:8d1c:cac5::1 ?

**Comment by fichtner** [comment]
I'm assuming 2001:984:a1fc:1::1 is properly written? It could be the issue where we only read one IP from the interface.

**Comment by gizahNL** [comment]
cat /var/etc/lighty-webConfigurator.conf

```
$SERVER["socket"] == "[fdea:8d1c:cac5:1::1]:80" {
    $HTTP["host"] =~ "(.*)" {
        url.redirect = ( "^/(.*)" => "https://%1/$1" )
    }
}
```


we have a winner ;)

**Comment by fichtner** [comment]
Okay, I'll ship this in 18.1.8. Sorry for being braindead on this occasionally. :)

**Comment by gizahNL** [comment]
Braindead was my mantra for the whole past week... ;)

BTW I also notice my dhcpv6 daemon breaking (it was working fine on previous versions before). 

I notice that it is complaining about the range being in the wrong subnet. Could it be that it is internally using the GUA address configured as a VIP address while calling back to the user in the interface as if it is using the ULA address?

**Comment by fichtner** [comment]
I think so, we can't support non-attached ranges yet, see #910

**Comment by gizahNL** [comment]
Though technically it only needs to serve one range, and ignore the other configured range on the interface ;) 

The normal stanza would be something like this:
range A { subnet declarations, start end etc. }
range B { (empty, DHCP server is made aware of range , but doesn't serve this range) }

While not full multi-subnet support it would prevent breakage in cases where multiple subnets are configured.

**Comment by fichtner** [comment]
the trouble so far is that it needs a subnet configuration prior to giving out a range and that is incompatible with how subnet configuration is read and written in the dhcpv6 implementation (it expects to use the one from the interface because you can't create arbitrary subnets in the dhcpv6 pages)

**Comment by gizahNL** [comment]
Yes I see. 

If I end up having some spare time I might be able to look into it, see if there is a simple fix possible.

**Comment by fichtner** [comment]
Thanks, that would be terrific. ❤️

**Comment by gizahNL** [comment]
Hmmm, now that we are on this topic, radvd.conf foo also seems to be off ;)

> root@gw-01:/var/etc # cat radvd.conf
> # Automatically Generated, do not edit
> # Generated for DHCPv6 Server lan
> interface bridge0 {
>         AdvSendAdvert on;
>         MinRtrAdvInterval 200;
>         MaxRtrAdvInterval 600;
>         AdvLinkMTU 1500;
>         AdvDefaultPreference high;
>         AdvManagedFlag on;
>         AdvOtherConfigFlag on;
>         prefix 2001:984:a1fc:1::/64 {
>                 DeprecatePrefix on;
>                 AdvOnLink on;
>                 AdvAutonomous on;
>                 AdvRouterAddr on;
>         };
>         prefix 2001:984:a1fc:1::/64 {
>                 DeprecatePrefix on;
>                 AdvOnLink on;
>                 AdvAutonomous on;
>                 AdvRouterAddr on;
>         };
>         route ::/0 {
>                 RemoveRoute on;
>         };
>         DNSSL lan { };
> };
> # Generated for DHCPv6 Server opt2
> interface em1_vlan14 {
>         AdvSendAdvert on;
>         MinRtrAdvInterval 200;
>         MaxRtrAdvInterval 600;
>         AdvLinkMTU 1500;
>         AdvDefaultPreference high;
>         AdvManagedFlag on;
>         AdvOtherConfigFlag on;
>         prefix fdea:8d1c:cac5:e::/64 {
>                 DeprecatePrefix on;
>                 AdvOnLink on;
>                 AdvAutonomous on;
>                 AdvRouterAddr on;
>         };
>         prefix 2001:984:a1fc:e::/64 {
>                 DeprecatePrefix on;
>                 AdvOnLink on;
>                 AdvAutonomous on;
>                 AdvRouterAddr on;
>         };
>         route ::/0 {
>                 RemoveRoute on;
>         };
>         RDNSS fdea:8d1c:cac5:e::1 { };
>         DNSSL heteigenwijsje.lan { };
> };
> # Generated for DHCPv6 Server opt3
> interface em1_vlan2 {
>         AdvSendAdvert on;
>         MinRtrAdvInterval 200;
>         MaxRtrAdvInterval 600;
>         AdvLinkMTU 1500;
>         AdvDefaultPreference high;
>         AdvManagedFlag on;
>         AdvOtherConfigFlag on;
>         prefix fdea:8d1c:cac5::/64 {
>                 DeprecatePrefix on;
>                 AdvOnLink on;
>                 AdvAutonomous on;
>                 AdvRouterAddr on;
>         };
>         prefix 2001:984:a1fc::/64 {
>                 DeprecatePrefix on;
>                 AdvOnLink on;
>                 AdvAutonomous on;
>                 AdvRouterAddr on;
>         };
>         route ::/0 {
>                 RemoveRoute on;
>         };
>         RDNSS fdea:8d1c:cac5::1 { };
>         DNSSL heteigenwijsje.lan { };
> };
> 

As you may see opt3 and opt2 get done correctly while bridge0 gets double GUA adresses assigned in the config...

**Comment by fichtner** [comment]
Ok, same issue :)

**Comment by fichtner** [comment]
This one is easy:

    # opnsense-patch 734e6f4 


Cheers,
Franco
