### ISSUE TITLE
bootstrap: rework theme to reduce overall padding and provide better wide screen adoption

### ISSUE THREAD

**Issue by fichtner** [opnsense/core#238]
Requested by many. We are aware. Any help here is welcome. :)

**Comment by fichtner** [comment]
e.g. https://forum.opnsense.org/index.php?topic=923.0

**Comment by sjorge** [comment]
not sure what options you are looking in but generally the 'Google's Material' design guide looks pretty good for stuff that needs to scale well on various screen sizes. There is even a bootstrap theme for that: https://github.com/FezVrasta/bootstrap-material-design (not official though)

**Comment by fichtner** [comment]
Some progress in opnsense-devel, more to come :)
