### ISSUE TITLE
NetFlow enable drop down list only shows 10 interfaces

### ISSUE THREAD

**Issue by ypid** [opnsense/core#2380]
List of steps to replicate the bug:

1. Create more than 10 interfaces
2. Open /ui/diagnostics/netflow/
3. Try to add new interfaces

Expected: Show all available interfaces
Actual: Only 10 interfaces where NetFlow is currently not enabled are shown

Workaround: Add/enable all interfaces and disable the once you don’t want again.

In all other places I have used before, OPNsense handles a long list of interfaces quite well.

OPNsense version: OPNsense 18.1.6-amd64
URL path of the GUI page involved: /ui/diagnostics/netflow/

Using OPNsense for many months now and love it! Thanks!

**Comment by fichtner** [comment]
Hi @ypid,

Looks like this is a feature, it only shows 10 interfaces in the drop-down, but the type-ahead should filter what you are looking for.


Cheers,
Franco

**Comment by ypid** [comment]
Thanks for your help @fichtner, you are right ;-) I missed that/did not test that because I was used to the drop down list provided in for example /interfaces_groups_edit.php where you have a search field and can select the different interfaces in the drop down list. Would it make sense to only have one drop down list UI style for interfaces?

**Comment by fichtner** [comment]
We have two, that's true. MVC seems to prefer the tokenizer over the selectpicker. Not sure if @AdSchellevis thinks alignment of use (for the interface selection) would be useful. I guess it could be beneficial to UX to set a guideline.

**Comment by AdSchellevis** [comment]
@fichtner Maybe we better change https://github.com/opnsense/core/blob/master/src/opnsense/mvc/app/views/layout_partials/form_input_tr.volt#L60-L62 to show a selectpicker when the list is static and a tokenizer when custom options are allowed, what do you think?
