### ISSUE TITLE
Multi-select broken

### ISSUE THREAD

**Issue by StrikerTwo** [opnsense/core#2381]
Example: HAProxy -> Public Service
I want to assign a certificate to the public service. The needed certificate is not shown in the dropdown at first (because there are too many), so I have to type some letters in order to filter the dropdown.
If I click on the certificate I want, the input field gets not the certificate name, but the text I searched.

This happens on 18.1.6 both with Chromium and Internet Explorer.
![image](https://user-images.githubusercontent.com/6770084/39422534-104b5154-4c6e-11e8-81b8-f6eb69458861.png)
![image](https://user-images.githubusercontent.com/6770084/39422544-25e8d6da-4c6e-11e8-8aa8-1daac784ab47.png)
![image](https://user-images.githubusercontent.com/6770084/39422555-325af3d0-4c6e-11e8-972d-5419063c825b.png)

**Comment by StrikerTwo** [comment]
Firefox doesn't work either. Help, I need to add that cert ;)

**Comment by StrikerTwo** [comment]
Workaround: Keep adding certificates until the one you need appears in the dropdown, click on it, then remove all others

**Comment by AdSchellevis** [comment]
found the culprit, https://github.com/opnsense/core/blame/5fafceada92b79b67bd72b06b9bef8fdc42b56c8/src/opnsense/www/js/jquery.tokenize.js#L156-L159 , although the fix doesn't seem to be complete yet (https://github.com/opnsense/core/commit/a4d77517d6d626e248156b1cc9d95e9f3e9ee307).

**Comment by fichtner** [comment]
Hmm, nice catch... it's unchartered what should happen here exactly when the typeahead matches a final element. The original fix was for free form input (IP/network lists), rendering it when users click "save" or "apply", see #1689.

The consistent fix would be to add the tag on blur when it matches the input. But the current version works as well, it forces people to click. Comma trick for adding also doesn't work so it's 2:1 for the current state as of a4d7751.

**Comment by fichtner** [comment]
no difference in chrome with or without 9a010a9, so either way is fine. thanks!

**Comment by StrikerTwo** [comment]
Sorry, still seems to be broken after applying the patch.

If I type the server name in the dropdown, it now shows the correct name - but it still does not accept it when clicking the save button.
![image](https://user-images.githubusercontent.com/6770084/40119115-0cf2060a-591c-11e8-916b-9ebcc4f115f6.png)

If I use my workaround of selecting servers until the one I want appears in the list and then click on it, it works.
The difference is that in the first case it has a `data-value="FTP_H_WEB"`, in the second case it has the correct GUID `data-value="3fd95d78-f9a9-467a-a039-1914178d93c4"`.

**Comment by StrikerTwo** [comment]
I used 59cb5cb and cleared the browser cache. The behaviour is different (better) than before in that it does not put the search text, but the text of the actual item into the input. But it should put the value, not the text.

**Comment by fichtner** [comment]
now that you mention it

**Comment by fichtner** [comment]
which plugin / page is this?

**Comment by StrikerTwo** [comment]
/ui/haproxy/#backends

**Comment by fichtner** [comment]
ok, can reproduce. mighty strange. we used this patch successfully in other areas of the interface.

**Comment by fichtner** [comment]
So dee48af on top should help:

    # opnsense-patch dee48af

**Comment by fichtner** [comment]
The field you spotted this error in also has an UI defect as it is marked as "allow-new" but that is untrue. Otherwise it works now, thanks for the report! CC @fraenki

**Comment by fichtner** [comment]
PS this won't be in 18.1.8 as that build is already done, but I'll pick it up in 18.1.9.

**Comment by AdSchellevis** [comment]
@fichtner ok, let's do that then. the lesser tokenizers we use, the easier it will be to replace later on :)

**Comment by StrikerTwo** [comment]
@fichtner thanks, looking good now.

**Comment by fichtner** [comment]
Great to hear! :)
