### ISSUE TITLE
Static routes are not added after router reboot

### ISSUE THREAD

**Issue by DasTestament** [opnsense/core#2388]
Hello,

I have a GIF tunnel and a few static routes on it. Sadly enough, they are not added after router reboot.

Steps to rep:
1. OPNsense 18.1.7 box
2. Create GIF tun
3. Add some static routes on GIF tun
4. Reboot

**Comment by fichtner** [comment]
@DasTestament do you have a system log for this, maybe the routes are added before the tunnels are up?

**Comment by DasTestament** [comment]
@fichtner Well, I can't answer your question because I've moved back to pfSense =/

**Comment by fichtner** [comment]
Ok, sure.
