### ISSUE TITLE
intrusion detection: toggle all button for rulesets and rules screens

### ISSUE THREAD

**Issue by fichtner** [opnsense/core#239]
Will also need to work in conjunction with the filter in the rules so that only selected rules are toggled.

**Comment by AdSchellevis** [comment]
commit https://github.com/opnsense/core/commit/790586b74f567b8ec2ff839dbbed08ce082baf0b adds support for selecting all items at once (standard select in upper corner followed by the select or deselect action at the right bottom of the grid).
