### ISSUE TITLE
system: dpinger post-merge work

### ISSUE THREAD

**Issue by fichtner** [opnsense/core#2396]
Was initially merged in #2326

- [x] gateway monitoring setting to firewall: settings: advanced
- [x] reload gateway monitor(s) immediately after preference save
- [x] proper start using dpinger binary ;)
- [x] investigate hang in service start
- [x] remove pidfile/socket name magic
- [x] testing apinger (RRD even when newly generated after a switch works fine)
- [x] testing dpinger (daemon works fine, switch ok)
- [x] rrd in dpinger mode not working
- [x] RTTd (stddev) in the web GUI
- [x] merge setup_dpinger_gateways_monitor() into setup__gateways_monitor()
- [x] exec_safe() usage to prevent shell command injection
- [x] test pid file before assuming a dpinger process running
- [x] fix hand-rolled $gwifip derivation (link-local issues)
- [x] merge dpinger service loop 1 and 2
- [x] "The probe interval needs to be less than the default down time setting (0)"
- [x] src/www/widgets/api/plugins/gateway.inc: "stdev" usage, but where is it set?
- [ ] src/etc/inc/gwlb.inc: "monitorip" and "srcip" are not in the pid file name (remains unsolved)

**Comment by mimugmail** [comment]
When you have a probe interval set on gateway like 1s you'll receive an error when editing the gateway: The probe interval needs to be less than the default down time setting (0)

**Comment by marjohn56** [comment]
Not sure why your RRD is not working,,, mine is.

**Comment by fichtner** [comment]
Also not sure. Tested apinger RRD overnight for double-checking, that works fine and both RRD graph switch ok. So hopefully tomorrow will see what might go wrong or if it works as is. :)

**Comment by marjohn56** [comment]
There was a bug in the RRD script creation, but I posted a fix for that before you pulled it. The zip file I posted for 18.1.7 is working fine on a couple of live systems. I am running it on 18.7.b_97 live. I had to do a couple of fixes to it as the STDev was not being displayed and monit needed adjusting due to the name changes of the *PID's etc. Other than that it appears to be working fine

**Comment by fichtner** [comment]
Found it... commit in a sec.

**Comment by marjohn56** [comment]
Cool.

Can you commit the config change in misc, that will allow me to quickly switch back and forth,

**Comment by fichtner** [comment]
It's now under Firewall: Settings: Advanced with the other gateway monitoring settings. It deleted the stale RRD quality database, restarts with the new monitoring service and restarts the RRD subsystem as you would expect. :)

**Comment by fichtner** [comment]
See https://github.com/opnsense/core/blob/master/src/www/system_advanced_firewall.php#L234-L238

**Comment by marjohn56** [comment]
Ahah!! There it is... OK, switching back to Apinger works, Now I need to wait around 20 minutes for the data to build to see if it's OK with dpinger.

**Comment by fichtner** [comment]
It's good for me now with the stddev in the graph and dpinger... previously it would not render anything :)

**Comment by marjohn56** [comment]
Another box to tick then. stddev in webgui?  That just needs the widget stuff imported, gateway.inc, gateways_widget.php. system, gateways.php and gateways_edit.php , Just imported into mine and looks good.

**Comment by fichtner** [comment]
Sure, shall we close #2326 and you create a new one for STDDEV additions? I am a bit split on when/where to show it and whether we should show it unconditionally or not. Also, the wording was inconsistent so I removed the bits from your latest proposal just so we don't forget to look at it in detail.

**Comment by marjohn56** [comment]
Can do. I guess we could make STDEV only display if dpinger was in use.

**Comment by marjohn56** [comment]
update to b_105 ... Looking good. :)

**Comment by fichtner** [comment]
Indeed, brilliant work you did there, thanks again!

Last bits are merging setup_dpinger_gateways_monitor() into setup_gateways_monitor() to get rid of the code duplication. And that bug that Michael found, but maybe it's not a dpinger issue.

Maybe we can even ship this in 18.1.9 or 18.1.10 .... if the diff is clean enough. :)

**Comment by fichtner** [comment]
@marjohn56 would you mind looking into the TODO "src/www/widgets/api/plugins/gateway.inc: "stdev" usage, but where is it set" ? I am not available in the next few days

**Comment by fichtner** [comment]
@mimugmail fixed your report via 726449b2ff8

**Comment by mimugmail** [comment]
yep, works 👍

**Comment by marjohn56** [comment]
@fichtner I'll take a look. Will be tomorrow as real work calls today. Looked at the gateway_edit last night, think we must expand this to give full settings for dpinger at some point.

**Comment by fichtner** [comment]
@marjohn56 sure, can clean this up when we ditch apinger post 18.7 ;)

**Comment by marjohn56** [comment]
stdev is returned from from the function return_gateways_status() in gwlib.inc.

Line 463,

**Comment by mimugmail** [comment]
@marjohn56 yep seems ok

Have you tested with multiwan? On my testbed I plugged out one modem resulting in no default gateway at all. Perhaps there's still some work to do :/

**Comment by marjohn56** [comment]
I am not able to test on Multiwan. 

I am not familiar with how the default gateway switching works, as I cannot test it I've never looked into it.

**Comment by mimugmail** [comment]
Ok, I'll test on Monday since the guy at the office removed the modem and is gone now :/

**Comment by fichtner** [comment]
Well, hold on:

```
$ git grep stdev
src/www/widgets/api/plugins/gateway.inc:                case "stdev": /* XXX this does not exist? */
```

I don't see where this is handled, gwlb.inc should probably set this but it does not unless it uses a side effect from the returned dpinger state?

**Comment by fichtner** [comment]
FWIW, monitoring is not affected... the trigger changes and may have issues that are not of apinger nature, but the multi-wan system scripting is the same.

**Comment by marjohn56** [comment]
Welcome back - 

Are you still unable to find where stddev is returned?

**Comment by fichtner** [comment]
yup :)

**Comment by fichtner** [comment]
It should be here but it's not:

https://github.com/opnsense/core/blob/master/src/etc/inc/gwlb.inc#L1277-L1285

**Comment by marjohn56** [comment]
On my source it's now line 560. A call to get_dpinger_status() returns an array by the look of it, along wuuth the RTT.

$status[$target]['stddev'] = sprintf('%0.1f ms', empty($dpinger_status['latency_stddev']) ? 0.0 : round($dpinger_status['latency_stddev'], 1));

**Comment by fichtner** [comment]
wrong stddev. this is the actual value, not the status value. note the missing d in "stdev"

**Comment by marjohn56** [comment]
line 1246 ?

**Comment by marjohn56** [comment]
Where is the missing 'd'?

**Comment by fichtner** [comment]
https://github.com/opnsense/core/blob/master/src/www/widgets/api/plugins/gateway.inc#L53

**Comment by marjohn56** [comment]
Ah, isn't that just a text translation though, if it cannot find it it will leave it as is?

**Comment by marjohn56** [comment]
Just fix it by adding the extra d. It's definitely outputting the value and the labelling is correct on my system.

**Comment by fichtner** [comment]
No, it translates a low level status "stdev" to a human readable string. But if ne never set "stdev" we don't have to look for it. There is either something missing from the original patch or we don't need that line.

**Comment by marjohn56** [comment]
I've searched, and I cannot find where gateway_api() is called anyway,

**Comment by fichtner** [comment]
dashboard widget only

**Comment by marjohn56** [comment]
what, in gateways_widget.php?

**Comment by marjohn56** [comment]
Well it would have been my addition that has the typo, strange it works though, I have just added the extra d to my live system and nothing breaks. But I'll keep an eye on it.

**Comment by marjohn56** [comment]
Still behaving.... Shall I push a PR or do you want to do it?

**Comment by marjohn56** [comment]
It has actually made a difference. I was concerned that my RTTd seemed high at times, sometimes many times the RTT, the addition of the 'd' has reduced it and it seems the value is now 'sensible. I think you can see where I added the 'd'.

![image](https://user-images.githubusercontent.com/17962918/40041559-52596f28-5816-11e8-9a3c-0fb2976f5c3a.png)

**Comment by fichtner** [comment]
it looks like you simply don't browse a lot at night... try to compare after 24 hours for a full baseline

**Comment by marjohn56** [comment]
I can saturate it now for a test...

**Comment by marjohn56** [comment]
I'll issue a patch shortly to correct it, perhaps @mimugmail could patch it too and see if he sees any difference.

**Comment by marjohn56** [comment]
@mimugmail  - Can you try this and see if it makes a difference. PR #2404

**Comment by mimugmail** [comment]
I'm building latest master now .. give me an hour to test everything ..

**Comment by marjohn56** [comment]
@mimugmail - That's good news. Waiting for my crew to come back with the info on the stddev issue too, Might take a few days, but t's a minor fix if it's needed.

**Comment by marjohn56** [comment]
OK - Makes no difference, I can see RTTd exceeding RTT again, so it';s a done job.
