### ISSUE TITLE
FR: Add dstAddress field to Details tab in Insight

### ISSUE THREAD

**Issue by mimugmail** [opnsense/core#2398]
Hi,

would it be a big problem to add a dstAddress field to the Details tab?
Would make it search to troubleshoot some malicious outbound traffic. 

Thanks!

**Comment by AdSchellevis** [comment]
@mimugmail probably not, I'll add it on my list

**Comment by AdSchellevis** [comment]
@mimugmail here you are https://github.com/opnsense/core/commit/fcda7cd9eee0f32d6a699384790bbb7e04793263
