### ISSUE TITLE
Telegraf plugin - graphite "insecure_skip_verify"

### ISSUE THREAD

**Issue by dtavb** [opnsense/core#2402]
Hi,

after configuration of telegram plugin and output to graphite, no output is sent because of unsecure traffic between opnsense and graphite node.
the value for this is automatically set in background by the opnsense webGUI.

/usr/local/etc/telegraf.conf:
insecure_skip_verify = true

after changing this to "insecure_skip_verify = false" the telegraf plugin is working.

my issue is: after reboot of opnsense the value is set to "true" again.

would it be possible to make this value accessable via webGUI or the value manually set in conf-file survives reboot?

Thanks and bye
dtavb

**Comment by mimugmail** [comment]
Can you open this issue in plugins repo please and close this one here? 
Telegraf is a plugin and I don't monitor core issues.

**Comment by dtavb** [comment]
thanks, I will do it.

**Comment by donixa** [comment]
i have this same issue, any news about this? what is the solution for this?

**Comment by fichtner** [comment]
@donixa Graphite SSL Verification checkbox.

**Comment by donixa** [comment]
thank you @fichtner it works now...

**Comment by fichtner** [comment]
great, no problem :)
