### ISSUE TITLE
system: remove legacy notifications with monit alternatives

### ISSUE THREAD

**Issue by lopsch** [opnsense/core#2408]
The actual integration for growl notifications is using the UDP:9887 protocol. This seems to be [superseded](https://redmine.pfsense.org/issues/2942) by the [GNTP](http://growl.info/documentation/developer/gntp.php) which uses TCP:23053. 

There is already a usable version in [pfSense](https://github.com/pfsense/pfsense/commit/e7cf30eb6fcd0cc2ec20dd267775b03db2b3667f#diff-72d56d9b02b90f32a1c7842315d545d4) which uses [Net_Growl](https://pear.php.net/package/Net_Growl). As far as I can see Net_Growl is available in [ports](https://github.com/opnsense/ports/tree/master/net/pear-Net_Growl).

As I'm not into PHP I just tried to apply the patch und download Net_Growl into the include directory for testing. I came as far as trying to send a message where it bails out not having mbstring available.

So I assume the packages Net_Growl depends on are not available at all:

- mbstring extension
- pcre extension
- SPL extension
- mcrypt extension (optional)

I would build a new image including the patches, Net_Growl and its dependencies for testing myself but to be honest I don't know where all the knobs are that I need to turn.

If someone could point me in the right direction and there is interest in an integration update I could try to contribute a PR.

Best regards and sorry if the issue is not correct/missing information.

**Comment by fichtner** [comment]
Hi @lopsch,

The current notification framework is scheduled for a full removal in 18.7. We already imported Monit into the core package for this reason. I don't see this code going anywhere because of it. Ok?


Cheers,
Franco

**Comment by fichtner** [comment]
Sorry for the delay! Monit is fully customizable, e.g. https://mmonit.com/wiki/MMonit/PushoverNotification

**Comment by fichtner** [comment]
Closing in favour of #2408
