### ISSUE TITLE
crash reporter: uuid plus optional email and description box, manual problem report

### ISSUE THREAD

**Issue by fichtner** [opnsense/core#241]
as discussed with @AdSchellevis

**Comment by AdSchellevis** [comment]
Will fix that, we only need to change "something" so we know server side if the uuid should come back.
(current code will signal failed when it receives data from remote host)

**Comment by fichtner** [comment]
Just for reference I'd still like that as some crash reports miss context so a description plus contact email would be neat. I also saw this so we can identify recurring issues:

    # sysctl kern.hostuuid
    kern.hostuuid: 06ed86b5-2649-11e5-9ea5-f490ea001992

**Comment by fichtner** [comment]
#325 notes that a custom crash report could be created if needed (very useful with description box)

**Comment by fichtner** [comment]
Mostly done, but need to figure out a way to "generate" a manual report.
