### ISSUE TITLE
Dropdown selector occasionally does not show the correct display value

### ISSUE THREAD

**Issue by MaxOrelus** [opnsense/core#2413]
On refresh of a setting pages, from time to time the dropdown display does not show the correct display value. There are times that it shows `Nothing selected` and there are times is actually shows the correct display value.

I investigated it a bit more and the settings as they come back from the API endpoint are correct, I just think there's something going on with the JS behind populating the display in the dropdown. Looking into the code, the correct value has the `selected` attribute next to it, but the display shows `Nothing selected`.

**Comment by AdSchellevis** [comment]
Hi Max, is there a specific page/test scenario where this fails? I've never seen it before on my end, maybe it fails at specific scenarios. The normal dropdown is a selectpicker, which should normally be reloaded when items change.

**Comment by MaxOrelus** [comment]
form.xml:
```
<log_level type="OptionField">
  <Required>Y</Required>
  <default>warning</default>
  <OptionValues>
    <debug>Debug</debug>
    <verbose>Verbose</verbose>
    <notice>Notice</notice>
    <warning>Warning</warning>
  </OptionValues>
</log_level>
```

model.xml:
```
<log_level type="OptionField">
  <Required>Y</Required>
  <default>warning</default>
  <OptionValues>
    <debug>Debug</debug>
    <verbose>Verbose</verbose>
    <notice>Notice</notice>
    <warning>Warning</warning>
  </OptionValues>
</log_level>
```

When I look at this in the ui_devtools locally, the options don't load and ends up display "Nothing selected"

**Comment by MaxOrelus** [comment]
I think I just figured it out, I was missing:

```
$('.selectpicker').selectpicker('refresh');
```
