### ISSUE TITLE
Feature request - Reset all states if WAN IP Address changes

### ISSUE THREAD

**Issue by JosQuelqu1** [opnsense/core#2414]
Hi,

Can't find this feature on OPNsense. I need this to pull the plug on pfSense...

On pfSense:

Reset All States
Reset all states if WAN IP Address changes
This option resets all states when a WAN IP Address changes instead of only states associated with the previous IP Address.

Thank you!

**Comment by fichtner** [comment]
The implementation is a bit optimistic and only works for DHCP IPv4, not particularly related to "WAN".

Although the functionality is clear, can you state your use case for reference? Maybe we can find a better spot for implementation.

**Comment by JosQuelqu1** [comment]
It's for the VoIP guy here at the office. When the WAN IP change it cause problem with the VoIP service.

He sent me this. It's the exact issue: https://redmine.pfsense.org/issues/1629

**Comment by topaDev** [comment]
Hi,
experiencing the same problem with VoIP, just came across this workaround (search for "resetstates.sh" script):
https://bauschp.wordpress.com/asterisk-projects/asterisk_provider_t_kom/

**Comment by fichtner** [comment]
Please try this patch c5b9f672 via:

    # opnsense-patch c5b9f672


Thanks,
Franco

**Comment by topaDev** [comment]
Thank you Franco, it works like a charm.

**Comment by fichtner** [comment]
Ok, great, will ship this in 18.1.9. Thanks for testing!
