### ISSUE TITLE
UI-Bug: Show all countries within GeoIP-Blocking

### ISSUE THREAD

**Issue by Farma12** [opnsense/core#2415]
I use the following:
OPNsense 18.1.8-amd64
FreeBSD 11.1-RELEASE-p10
OpenSSL 1.0.2o 27 Mar 2018
on a APU2c4Board.

If I follow this guide: https://wiki.opnsense.org/manual/how-tos/ips-geoip.html there is the part where I add the countries from the dropdown-list. But it only shows the first ten entries. The url is https://<ip-address>/ui/ids/#userrules

What I want to archive: Add all countries and remove only those which are thrustworthy.
What is my problem: I have to know all countrynames, to be able to add all countries.
What I would like as solution: Either be able to add all countries with one click, or show the whole list.

Thanks for your time and this cool firewall.

**Comment by fichtner** [comment]
The IDS GeoIP block has been superseded with the firewall alias GeoIP blocking which has a splendid interface nowadays and is more flexible to use. Try it under Firewall: Aliases, select GeoIP :)

I don't think the IDS GeoIP will be reworked anymore.


Cheers,
Franco

**Comment by Farma12** [comment]
Thanks, there is a much better UI and it works very good.

**Comment by fichtner** [comment]
Glad to hear 👍
