### ISSUE TITLE
IPsec mobile client: DNS problem with Apple IOS on IKEv1

### ISSUE THREAD

**Issue by mgollo** [opnsense/core#2418]
When setting up IPsec for mobile clients with IKEv1, Apple IOS devices are able to connect if the setup happens according to https://wiki.opnsense.org/manual/how-tos/ipsec-road.html but they cannot resolve any DNS names, even if DNS servers are configured. 
In strongswan.conf, something like this is generated:
>	plugins {
>		attr {
>			subnet = 10.10.2.0/24
>			dns = 172.18.55.1
>		}

but this is ignored by IOS devices according to https://serverfault.com/questions/521536/strongswan-cant-push-dns-resolver-to-osx-mountain-lion-split-tunnel if I understand this correctly. I manually edited ipsec.conf and added 
> rightdns = 172.18.55.1

to the connection entry and now the VPN is working fine. So it seems that this option should at least be used in addition to the first entry to make Apple devices work with IKEv1.

**Comment by pgaultier** [comment]
Well, I had the same problem and it was because I forgot to allow traffic from the IPSec network to Unbound.

I added an access list in unbound dns > access list and everything worked like a charm
