### ISSUE TITLE
timezonelist is truncating some timezone names in system_general.php

### ISSUE THREAD

**Issue by cbasolutions** [opnsense/core#242]
`$timezonelist = array_map(`
`	function ($path) { return str_replace('/usr/share/zoneinfo/', '', $path); },`
`	glob('/usr/share/zoneinfo/*/*')`
`);` 

This truncates several values and allows for erroneous selections in the drop down. Is there a reason to use this instead of the built-in PHP function: `DateTimeZone::listIdentifiers()`

The list: 

>America/Argentina/Buenos_Aires
>America/Argentina/Catamarca
>America/Argentina/Cordoba
>America/Argentina/Jujuy
>America/Argentina/La_Rioja
>America/Argentina/Mendoza
>America/Argentina/Rio_Gallegos
>America/Argentina/Salta
>America/Argentina/San_Juan
>America/Argentina/San_Luis
>America/Argentina/Tucuman
>America/Argentina/Ushuaia
>America/Indiana/Indianapolis
>America/Indiana/Knox
>America/Indiana/Marengo
>America/Indiana/Petersburg
>America/Indiana/Tell_City
>America/Indiana/Vevay
>America/Indiana/Vincennes
>America/Indiana/Winamac
>America/Kentucky/Louisville
>America/Kentucky/Monticello
>America/North_Dakota/Beulah
>America/North_Dakota/Center
>America/North_Dakota/New_Salem

**Comment by fichtner** [comment]
Nice catch. No particular reason I guess. It went through a refactor, but it can go through one more... Will push a small cleanup that will make this easier to fix in one place only.

**Comment by fichtner** [comment]
The Etc\UTC style time zones are gone, but since the dialog asks for locations I think this is ok?

**Comment by fichtner** [comment]
A bit more on the history. zoneinfo.tgz used to be in /usr/share instead of the proper layout. I refactored that, not having looked up if there was a portable function already available.

https://github.com/opnsense/core/commit/0d8ad1b487c44

**Comment by cbasolutions** [comment]
Is there a way for me to easily pull this onto my device for testing?

**Comment by fichtner** [comment]
http://lastsummer.de/development-workflow-in-opnsense/

These days I use "core_safe" instead of "core" so that auto-mount doesn't kick in automatically. Don't forget to "make umount" when you are done.

**Comment by fichtner** [comment]
Confident about these changes; will be in today's 15.7.1

**Comment by fichtner** [comment]
Any thoughts on this issue's resolution? :)

**Comment by cbasolutions** [comment]
Hi Franco, I can confirm on my firewall that the TZ selection I was looking for is now there and it is writing to /conf/config.xml. I also added a phpinfo() to the bottom of index.php and it is now showing the proper TZ!

This seems to be resolved.

**Comment by fichtner** [comment]
Yay, thanks for confirming.
