### ISSUE TITLE
OPNsense 18.1.8 Services: RFC 2136 Local IPv6 address use

### ISSUE THREAD

**Issue by datiscum** [opnsense/core#2421]
The RFC2316 client transmits the lovale IPv6 address to the name server.

Cached IP in the service overview:  IPv6: fe80::21b:21ff......
WAN address in Dashboard:
2003:c9:2fff:2c45:21b:21ff....

I checked/unchecked the "Use Public IP" Entry, but no change.

**Comment by fichtner** [comment]
Not sure if this is enough info to go on. Needs more configuration points from RFC2136 plugin for reference and how WAN is set up (IPv6 mode).

**Comment by datiscum** [comment]
Sorry here more details.

Interfaces: Overview

LAN interface lan,em1
SwitchLanInt opt1,em2
WAN wan.pppoe0
WAN_LAN opt2,em0

A special feature is the WAN_Lan interface.
Via ssh port forwarding i can reach the VDSL modem (Admin Panel) before the OPNSense Box.

Why can i not direcly select the "WAN pppoeXX" Inteface for the address ?


em0: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500
options=52098<VLAN_MTU,VLAN_HWTAGGING,VLAN_HWCSUM,WOL_MAGIC,VLAN_HWFILTER,VLAN_HWTSO>
        ether 00:1b:21...
        hwaddr 00:1b:21...
        inet6 fe80::21b:21...%em0 prefixlen 64 scopeid 0x1 
        inet 192.168.244.11 netmask 0xffffff00 broadcast 192.168.244.255 
        nd6 options=21<PERFORMNUD,AUTO_LINKLOCAL>
        media: Ethernet autoselect (1000baseT <full-duplex>)
        status: active
em1: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500
        options=40098<VLAN_MTU,VLAN_HWTAGGING,VLAN_HWCSUM,VLAN_HWTSO>
        ether 00:1b:21...
        hwaddr 00:1b:21...
        inet 192.168.11.1 netmask 0xffffff00 broadcast 192.168.11.255 
        inet6 2003:c9:2f2c:3302:21b:21... prefixlen 64 
        inet6 fe80::1:1%em1 prefixlen 64 duplicated scopeid 0x2 
        nd6 options=21<PERFORMNUD,AUTO_LINKLOCAL>
        media: Ethernet autoselect (1000baseT <full-duplex>)
        status: active
em2: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500
        options=2098<VLAN_MTU,VLAN_HWTAGGING,VLAN_HWCSUM,WOL_MAGIC>
        ether 52:54:00...
        hwaddr 52:54:00...
        inet 192.168.12.1 netmask 0xffffff00 broadcast 192.168.12.255 
        inet6 2003:c9:2f2c:3301:5054... prefixlen 64 
        inet6 fe80::1:1%em2 prefixlen 64 scopeid 0x3 
        nd6 options=21<PERFORMNUD,AUTO_LINKLOCAL>
        media: Ethernet autoselect (1000baseT <full-duplex>)
        status: active
enc0: flags=41<UP,RUNNING> metric 0 mtu 1536
        nd6 options=21<PERFORMNUD,AUTO_LINKLOCAL>
        groups: enc 
pflog0: flags=100<PROMISC> metric 0 mtu 33160
        groups: pflog 
pfsync0: flags=0<> metric 0 mtu 1500
        groups: pfsync 
        syncpeer: 0.0.0.0 maxupd: 128 defer: off
em0_vlan7: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1492
        ether 00:1b:21...
        inet6 fe80::21...%em0_vlan7 prefixlen 64 scopeid 0x8 
        nd6 options=21<PERFORMNUD,AUTO_LINKLOCAL>
        media: Ethernet autoselect (1000baseT <full-duplex>)
        status: active
        vlan: 7 vlanpcp: 0 parent interface: em0
        groups: vlan 
pppoe0: flags=88d1<UP,POINTOPOINT,RUNNING,NOARP,SIMPLEX,MULTICAST> metric 0 mtu 1484
        inet6 fe80::21b:21...%pppoe0 prefixlen 64 scopeid 0x9 
        inet6 2003:c9:2fff:2c45:21b:21... prefixlen 64 autoconf 
        inet 84.182.80.137
        nd6 options=23<PERFORMNUD,ACCEPT_RTADV,AUTO_LINKLOCAL>

I hope that's enough detail.

**Comment by fichtner** [comment]
Thanks, I think I know what's going on. In your WAN PPPoE config (IPv4), the box "Use IPv4 connectivity" is checked for your additional IPv6 configuration?


Cheers,
Franco

**Comment by marjohn56** [comment]
I think the problem here, and I could be reading this wrong is that the WAN address is link-local and not global. This could well be the way it's meant to be. Sky UK for example use a link local on the WAN, only the LAN side has a global.

I am not fully aware of what the OP is trying to get across, however if it is the for Dynamic DNS, then we need to send the LAN v6 address if the WAN is getting only a link-local. Maybe an option switch in the DDNS setup unless we can think if a way to be sure that link local is in use. This is similar to the gateway issue way back, where using the LAN address as the source fixes the issue,

**Comment by fichtner** [comment]
@marjohn56 but pppoe0 has 2003:c9:... according to ifconfig ?

**Comment by marjohn56** [comment]
Ah I see, but em0 has a link local, and it appears that is what's being sent, is it not?

**Comment by datiscum** [comment]
Interfaces: [WAN] -> DHCPv6 client configuration -> Use IPv4 connectivity - is checked
Request a IPv6 prefix/information through the IPv4 connectivity link.

**Comment by fichtner** [comment]
Okay, we're on the right track.... do you happen to have "Request only an IPv6 prefix" enabled as well?

**Comment by marjohn56** [comment]
@fichtner - Am I miss-reading this? Is the issue to do with DDDNS?

**Comment by datiscum** [comment]
Yes, these entries are enabled.
Request only a IPv6 prefix 
Send IPv6 prefix hint
Request a IPv6 prefix/information through the IPv4 connectivity link

**Comment by datiscum** [comment]
It is about the RFC2136 service and not about DynDNS Service

**Comment by fichtner** [comment]
It's almost the same, based on shared / copied code.

I think there's your issue, "Request only a IPv6 prefix" will ignore any non-local address that the ISP may give you.

This is more or less an expected result of a change in 18.1.7:

https://github.com/opnsense/changelog/blob/master/doc/18.1/18.1.7#L47

It worked by accident earlier and I'm not yet sure how to combine both worlds without avoiding the accident.
