### ISSUE TITLE
Allow more special values for `addr` in ipfw rules (Traffic Shaping)

### ISSUE THREAD

**Issue by ypid** [opnsense/core#2424]
According to `man 8 ipfw`, more special values are supported by the `addr` rule field then just `any`:

```
     addr: [not] {any | me | me6 | table(name[,value]) | addr-list | addr-set}

             any     matches any IP address.

             me      matches any IP address configured on an interface in the
                     system.

             me6     matches any IPv6 address configured on an interface in
                     the system.  The address list is evaluated at the time
                     the packet is analysed.

             table(name[,value])
                     Matches any IPv4 or IPv6 address for which an entry
                     exists in the lookup table number.  If an optional 32-bit
                     unsigned value is also specified, an entry will match
                     only if it has this value.  See the LOOKUP TABLES section
                     below for more information on lookup tables.
```

Especially `me6` and `me` can be useful. When it is currently specified as `source`, [the validator](https://github.com/opnsense/core/blob/15ec336b0fccd4516e0c0d774a71cacbad15a9d1/src/opnsense/mvc/app/models/OPNsense/Base/FieldTypes/NetworkField.php#L159-L179) complains with: "please specify a valid network segment or address (IPv4/IPv6)"

OPNsense version: OPNsense 18.1.8-amd64
URL path of the GUI page involved: /ui/trafficshaper/#rules

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository, 
please read https://github.com/opnsense/core/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue, 
just let us know, so we can reopen the issue and assign an owner to it.
