### ISSUE TITLE
Allow to disable traffic shaping rules

### ISSUE THREAD

**Issue by ypid** [opnsense/core#2426]
Pipes and queues can already be disabled. It would be helpful to also support this for traffic shaping rules.

OPNsense version: OPNsense 18.1.8-amd64
URL path of the GUI page involved: /ui/trafficshaper/#rules

**Comment by AdSchellevis** [comment]
https://github.com/opnsense/core/commit/26ee607a31f1e1ef4754e76ccc31df100019671d should do the trick, to test pull in the diff using opnsense-patch and run a model migration to upgrade your config.

```
opnsense-patch  26ee607
/usr/local/opnsense/mvc/script/run_migrations.php

```

**Comment by ypid** [comment]
@AdSchellevis Thanks so much, you rock! Works nicely :+1:
