### ISSUE TITLE
QR code image needs white border

### ISSUE THREAD

**Issue by marjohn56** [opnsense/core#2430]
The QR code does not work for dark themes as there is no border around the image, otherwise known as the quiet zone. See...

https://web.archive.org/web/20110812190511/http://raidenii.net/files/datasheets/misc/qr_code.pdf

As reported https://forum.opnsense.org/index.php?topic=6885.0

**Comment by AdSchellevis** [comment]
It seems like the qr-code module isn't really maintained anymore, same issue is in the pull requests https://github.com/jeromeetienne/jquery-qrcode/pull/43/files let me try to incorporate this and see how that pins out

**Comment by AdSchellevis** [comment]
@marjohn56 can you try https://github.com/opnsense/core/commit/2f247f2f854aa40a8ec67db736fa1d8b211382f7 ?

**Comment by marjohn56** [comment]
Looks the same, still no border.

**Comment by AdSchellevis** [comment]
cache?
![image](https://user-images.githubusercontent.com/9783985/40766937-5cc3e4dc-64b1-11e8-9303-fad4b185cff4.png)

**Comment by marjohn56** [comment]
Strangely enough I was looking through the same https://github.com/jeromeetienne/jquery-qrcode and found another method, that didn't work either.... then I cleared the cache. :)

Now your version and mine both work.... :)

Nice one Ad, another one bites the dust.

**Comment by AdSchellevis** [comment]
Thanks for confirming Martin
