### ISSUE TITLE
Feature Request: dh-parameters regeneration UI/schedule

### ISSUE THREAD

**Issue by beren12** [opnsense/core#2431]
Talking to Fitch in IRC we came up with a few ideas to keep dh-parameters fresh:

- have a warning in the webui if they are past a certain age based on modification date
- save a hash of the files on install, and on updates if the hash matches it's safe to overwrite with a newer system one; rehash
- regen new files each update
- Allow users to set a cronjob (nice -n 20) to refresh them, maybe with weekly or monthly options, also a button to regen on demand (like if they get the warning it's old) with time of day to make sure it's off-peak

**Comment by fichtner** [comment]
Thanks! So what we need first is a function that wraps getting the correct du parameters file: self-generated or standard file provided by core package. When we have this we can automatically select the file that is newer, other logic as we come up with later.

**Comment by beren12** [comment]
Looks like filemtime will tell you when the file was last modified http://php.net/manual/en/function.filemtime.php 

I would bundle the hash of the last few dh-parameter versions, maybe going back to whatever date you think is too stale, and have a notification when you login to the webui if it's stale.
Maybe even just forcing it's replacement even if it's custom but too old. Once the system overwrites the files with defaults from an update, the file with the hashes only needs to keep the hash of the currently installed file

Another thing to consider is if the admin installs other key lengths than the default… Does the system recognize those like pfsense does? If so they should be checked and the option given to admins to regen those as well, but they might want to do that remotely since they take so long to generate.

**Comment by beren12** [comment]
I was thinking every minor update provide new dh files, and those replace the installed unless a custom job is scheduled or the installed ones are older than 1-3 month default (configurable under advanced)

There should also be logic to allow admins to override generation esp if OpenVPN can use up to a 16k dh. Then they should be checked by mod date (not creation) and hashed, and yell at admins when they get stale. Would be nice to decide which files get generated on the machine as well, faster boxes may never want to use provided dh but only generate them on the box. 

Shared random numbers aren't random really :-)

**Comment by fichtner** [comment]
> Shared random numbers aren't random really :-)

Low entropy is not to be confused with higher but shared entropy.

Obviously we can't update DH parameters every release as it takes too much time and there is no randomness guarantee. And I don't see a lot of benefit from registering past entropy records or allowing more fine-grained local regeneration other than "use shared file or update weekly/monthly/custom" with a cron job to use as one sees fit.

This state will be in 18.1.10. Every additional submission and improvement is welcome of course.

**Comment by fichtner** [comment]
Last bits via 00429edb9 await testing and backport.
