### ISSUE TITLE
Feature Request: bulk certificate import and management

### ISSUE THREAD

**Issue by beren12** [opnsense/core#2432]
It would be nice to be able to pass a zip file or just multiple files to the webui to bulk import my certs and keys. It's not required that the client certs be in the UI but it's handy to see them, when they expire, etc. the description could be based on the filename, like ca.crt and ca.key are the CA, but client1.crt|key would be called client1, maybe even an option to add an arbitrary prefix, like "OpenVPN-" on importing.

Another useful feature could be options for highlighting expired/soon to expire certs, weak hashes (SHA1 anyone?) or small key sizes.

Also better links from OpenVPN to the trust/cert pages, took me a bit to find where to add client certs once i set it up. The "OpenVPN Client" page was not what it seemed at first :-)

I guess going along with this could be a config page that lists the certs/clients generated from the openvpn ca/server cert to allow custom config options, new certs issued, etc. Like how the DHCP static assignments work.

Hell, at that point it would likely be trivial to generate client config files with certs included based on a template/server settings.

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository, 
please read https://github.com/opnsense/core/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue, 
just let us know, so we can reopen the issue and assign an owner to it.
