### ISSUE TITLE
Feature Request: Firewall -> ! operator for SRC & DST PORT

### ISSUE THREAD

**Issue by v-i-r-u-s** [opnsense/core#2434]
Would it be possible to include IPFILTER operators for SRC_PORT & DST_PORT (similar to the ! operator for SRC_ADDR & DST_ADDR ) ?

**Comment by fichtner** [comment]
I'll take it but not sure it will be ready in 18.7. Lots of TODOs at the moment.

**Comment by fichtner** [comment]
@v-i-r-u-s I'm releasing this back into the pool: there is no "!" operator in pf.conf syntax for ports, only != and it doesn't easily work with aliases so this won't fix
