### ISSUE TITLE
Core Infrastructure Initiative (CII) Best Practices

### ISSUE THREAD

**Issue by ypid** [opnsense/core#2437]
I would like to point you to the [CII Best Practices Badge Program](https://bestpractices.coreinfrastructure.org). Could you go thought the [criteria](https://bestpractices.coreinfrastructure.org/criteria), [add the project](https://bestpractices.coreinfrastructure.org/projects/new) and keep it up-to-date there?

Refs:
- https://bestpractices.coreinfrastructure.org
- https://twit.tv/shows/floss-weekly/episodes/389

**Comment by AdSchellevis** [comment]
timeout
