### ISSUE TITLE
Firewall Scheduler not working consistently?

### ISSUE THREAD

**Issue by marjohn56** [opnsense/core#2439]
Raised because of this thread on the forum. https://forum.opnsense.org/index.php?topic=8808.0

Tried it and it worked once, blocking a specific host. However it failed to work again when I reset the schedule.

**Comment by marjohn56** [comment]
There is something not quite right. The rule applied by schedule as expected - at least for the first schedule, however, the log entries show the following:

![image](https://user-images.githubusercontent.com/17962918/40873527-83c567f0-6659-11e8-8d89-fc1ec970a2ac.png)

It appears to be putting the wrong label in the log.

**Comment by marjohn56** [comment]
Ah... I think I know why. Once the rule has ended then that rule is no longer in the table, so when it goes to look it up it picks the rule that is now in its place, does that make sense?

**Comment by fichtner** [comment]
The labels provided are mapped via the currently loaded ruleset, we don't have historic correlation. cc @AdSchellevis

**Comment by marjohn56** [comment]
Indeed, that makes it look a bit odd... Need to think on that one.

**Comment by AdSchellevis** [comment]
@fichtner @marjohn56 pf unfortunately misses a feature to identify the rules from the log, pfSense has a hack for that to push an identifier in the ruleset, which we removed in the early days (https://github.com/opnsense/src/commit/6eb42982ea94c7ac484630ddde9eb9ea92a54e3d) because it seemed unlikely that it would ever reach FreeBSD (which it didn't).

It's quite difficult to know for sure which entry belongs to what in the log given the current constraints, you would have to persist the ruleset on every change.

**Comment by marjohn56** [comment]
So that identifier is useful then, maybe time to restore it unless another way can be found.

**Comment by AdSchellevis** [comment]
nope, only if someone pushes similar functionality to FreeBSD. the reason for removing it is still valid.

**Comment by marjohn56** [comment]
I suppose instead of removing the rule it would work by just reversing the block/pass state. Then the rule would stay in the same place? 

However that also falls over when a new entry is created, but it may be better than nothing.

**Comment by fichtner** [comment]
We could add a hash identifier in the label? We already have one now.

**Comment by marjohn56** [comment]
That should work, good thinking.

**Comment by fichtner** [comment]
It probably breaks-label based state kills though :P

**Comment by marjohn56** [comment]
Tested this quite heavily this morning. Apart from the log issue it all worked flawlessly.
