### ISSUE TITLE
dyndns/cloudflare ignores IPv6 address on pppoe interface

### ISSUE THREAD

**Issue by ip6li** [opnsense/core#2442]
Interface pppoe0 has one IPv4 address and one IPv6 (global) address assigned by provider.
DynDNS service is configured for Cloudflare using username and api key.

Matching file  /var/cache/dyndns_... contains 0.0.0.0|<timestamp> initially. After editing with vi and [Save/force update] Cloudflare got IPv4 address. AAAA RR at Cloudflare was not updated.

Expected behaviour: AAAA RR should also be updated.

**Comment by fichtner** [comment]
Do you have only request prefix set for your WAN? It used to work, but now it does what is set up: ignore a global IPv6 on WAN so you need to move your Dynamic DNS to LAN.

**Comment by ip6li** [comment]
Changed DynDNS config to internal IPv6 interface which got IPv6 address by prefix delegation. This interface is IPv6 only, which is intended.

result:

Jun  5 19:53:45 fw opnsense: /services_dyndns_edit.php: Aborted IPv4 detection: no address for igb1_vlan2
Jun  5 19:53:45 fw opnsense: /services_dyndns_edit.php: Dynamic DNS (tk6.example.com) There was an error trying to determine the public IP for interface - opt3(igb1_vlan2). Probably interface is not a WAN interface.

[1] real domain replaced by example.com

**Comment by fichtner** [comment]
Sorry, I am confused now. Isn't Cloudflare is currently IPv4 only?

**Comment by fichtner** [comment]
But the dyndns plugin does not yet know about it :)

**Comment by fichtner** [comment]
If you want to request CloudFlare IPv6 support and / or work on it, please open a ticket here https://github.com/opnsense/plugins
