### ISSUE TITLE
Dpinger link local param issue.

### ISSUE THREAD

**Issue by marjohn56** [opnsense/core#2443]
I have found an issue with dpinger where in gwlib.inc if the source IP and/or target IP contains a '%' char then the call to daemonise fails... 

This is I suspect where something is fe80:xxxx:xxxx::1234%pppoe0 etc.

This fails...
`mwexecf_bg("/usr/local/bin/dpinger -f {$params} %s", array($gateway['monitor']));`

This works
`mwexec_bg("/usr/local/bin/dpinger -f {$params} {$gateway['monitor']}");`

What to do?

**Comment by fichtner** [comment]
Problem is probably in $params, % needs to be %% but exec_safe doesn't do that automatically.

**Comment by marjohn56** [comment]
Do we need to pass it through escapeshellarg()?

**Comment by fichtner** [comment]
Can you inspect $params ? It should simply replace % with %% to make it immune to sprintf usage in mwexecf_bg()

**Comment by marjohn56** [comment]
Already looking at it. :)

**Comment by marjohn56** [comment]
Done PR #2444

**Comment by fichtner** [comment]
Thanks for the analysis, can you try https://github.com/opnsense/core/commit/38a68670 instead? exec_safe and mwexecf ideally should be used exclusively to avoid this from happening (doubled use of sprintf is generally tricky with %)

**Comment by fichtner** [comment]
sorry, and also d8ba407978 it makes more sense to fix the bug correctly to avoid the doubled sprintf. Nice catch, thanks!

**Comment by marjohn56** [comment]
Tried it. Still the same. vsprintf gets upset.

**Comment by marjohn56** [comment]
Seems to work fine. :)

**Comment by fichtner** [comment]
ok, I will try to get dpinger into 18.1.0...

**Comment by marjohn56** [comment]
We may still have an issue. One of my testers says it's not fixed his Sky UK gateway, awaiting more info when he can give it to me.

**Comment by fichtner** [comment]
Make sure he’s not using os-cache plugin, it caches previous code almost forever so opnsense-patch doesn’t cut it.

**Comment by marjohn56** [comment]
I've got him onto the dev stream and upgrade. Fixes are in there I believe, well I can see them on mine.

**Comment by marjohn56** [comment]
Just spent a couple of hours looking at his system remotely, weird thing is it does not seem to be picking up the link-local addresses for dpinger to use. Also if I go to diagnistics->ping and use WAN-Link-local as the interface/address and ping the target link-local I get 'could not assign address'. If I ping link local from the shell it's fine.. I'll look again when I get some more time to play,

**Comment by marjohn56** [comment]
Think it might be a Sky UK thing... same issue with pf.

**Comment by fichtner** [comment]
What exactly, dpinger not starting because of interface config/address oddity? What is the ifconfig? To compare to working setups...

**Comment by marjohn56** [comment]
This is the confusing thing. Remember the message on the forum where bimmerdriver said that his gateway monitors work by default with link-local addresses. Well I have pppoe and route IPv6 through the v4 link. I can get it to work but the RTT time is a bit suspect:

![capture](https://user-images.githubusercontent.com/17962918/41023241-c2bab1f6-6963-11e8-838b-10243ac8fbe8.PNG)

On Ned's system which is IPv6 straight ipoe, not a chance. So he loaded up pf... it doesn't work on that either...

I think I'm chasing my tail.

**Comment by fichtner** [comment]
Any steps to reproduce locally? It's an internal gateway? Maybe it's a "no route to host" problem?

**Comment by marjohn56** [comment]
Once I have some definitive answers to your questions I'll give you the answers. He's not responding to my emails at the moment.

**Comment by marjohn56** [comment]
Working fine
