### ISSUE TITLE
Latest installer does NOT support intel 550EM chipset

### ISSUE THREAD

**Issue by seitzbg** [opnsense/core#2445]
Added to FreeBSD here:

https://svnweb.freebsd.org/base/head/sys/dev/ixgbe/ixgbe_type.h?revision=320688&view=markup&sortby=date

**Comment by fichtner** [comment]
Do we make a false indication that the latest installer does support it?

**Comment by seitzbg** [comment]
Indeed you did not.  I just want to be able to run Opnsense so if I can rebuild with my own driver until 19.1, that would be ideal.

**Comment by fichtner** [comment]
Branch with MFC for our 11.1 added here: https://github.com/opnsense/src/tree/ixgbe_next

Builds ok, good start...

**Comment by fichtner** [comment]
Here we go, this is a 18.1.9 installer image with the kernel replaced https://pkg.opnsense.org/FreeBSD:11:amd64/snapshots/OPNsense-201806061946-OpenSSL-vga-amd64.img.bz2

If it works, go to System: Firmware: Packages and lock the "kernel" package to avoid removing the driver on updates. Ask back here if 18.7 is safe to upgrade... at the moment it's not so we need to figure out a way to keep you hooked. :)

**Comment by seitzbg** [comment]
Nics are now detected  and functional with the IX driver, but disk is not :(

**Comment by seitzbg** [comment]
I added the following to loader.conf.local and AHCI errors have gone away with disks working as well.  Looks like a regression since 17.X seems to work.

hint.hpet.0.clock="0"
hint.ahci.0.msi = "2"
hint.ahci.6.msi = "2"

**Comment by fichtner** [comment]
You can add these values to System: Settings: Tunables since 18.1.6 and they are written to /boot/loader.conf directly. It's a bit better to have them in the settings for import / export.

**Comment by seitzbg** [comment]
Thanks!
