### ISSUE TITLE
web proxy: possibility to use ICAP reqmod without respmod

### ISSUE THREAD

**Issue by airetday** [opnsense/core#2449]
Often, the proxy may be used to do URL filtering but not content filtering, or virus scanning but no URL filtering.
The squid template allows that by checking if the URL exists before writing the  icap_service configuration directive.
However, validation of the proxy-icap subtab in the web GUI expects both URLs to be filled.
Allowing one of the URLs to be empty in the proxy-icap subtab validation should be enough.

**Comment by fichtner** [comment]
@airetday thanks for the request. can you open the ticket in the https://github.com/opnsense/plugins/issues section where it should be?

**Comment by airetday** [comment]
@fichtner I don't mind creating this issue somewhere else, but I think it really belongs to core, it is about Squid's ICAP feature, whose code is in core component, and not with c-icap plugin.
Maybe I could have been more clear, by using the word **squid** in my description.

**Comment by fichtner** [comment]
ahhh ok, no worries, I'll make it clear. thanks!

**Comment by fichtner** [comment]
maybe @fabianfrz is interested? :)

**Comment by fabianfrz** [comment]
@fichtner Why should we only scan HTTP requests - I don't see a reason for that.

**Comment by fichtner** [comment]
Advanced option?

**Comment by fabianfrz** [comment]
the two textboxes must be visible all the time because this is what you have to configure in most cases.
Every service has it's own rule - `RESPMOD` and `REQMOD` can have the same URL but should not.

In case of an AV engine, ICAP can prevent malicious uploads and downloads (most usual use case of ICAP). In case of a content filter, you need REQMOD for URL and header based filtering, while RESPMOD is needed for the response header and the data.

**Comment by airetday** [comment]
@fabianfrz the point is that there is a big impact in terms of performances when RESPMOD is activated, the web content has to be sent from the proxy to the adaptation server, and then back from the adaptation server to the proxy, which has a cost even when proxy and adaptation server are close to each other, and is sometimes unacceptable when the link between the two is not a good one.

In REQMOD on the other hand, only the URL travels, and the overhead is far more acceptable.

Simple URL filtering is a case where one will want REQMOD but no RESPMOD.

**Comment by fabianfrz** [comment]
@airetday  yes but in that case you don't need ICAP. Use squids features for that.

**Comment by airetday** [comment]
@fabianfrz it is not easy to use squid features to interact with an ICAP filtering solution, without using squid's ICAP feature. Maybe I don't totally understand your point.

**Comment by fabianfrz** [comment]
Probably yes - for that use case, ICAP is not needed since squid can do everything without ICAP. You can match on headers, urls, users, time etc. and build an access policy by joining different access lists.

**Comment by airetday** [comment]
@fabianfrz  My use case is that I have to interact with an **already existing** filtering service, available through ICAP. So yes, for this use case, ICAP is needed.

The filtering service is not on the same site than the OPNsense box, and I have no control on the link quality, so yes, for this use case RESPMOD may be harmful.

From your comment above, it seems that you see ICAP only as a link to an AV engine or a content filter.
It may also be used (and is effectively used) to connect a proxy to a third party URL filtering, offering features that squid does not provide by itself, like a high quality URL database.

I see a workaround I can use, setting up a no-op c-icap server on the OPNsense box, and using it for RESPMOD, but this is a hack, and not a clean one. I would prefer being able to use REQMOD without RESPMOD, and it may be enough for that to allow that the RESPMOD URL stays empty in the web UI.

There are other ways to achieve the same feature, like having two checkboxes, one for REQMOD and one for RESPMOD.

I can help to implement this, if there is a chance that the feature is accepted.

**Comment by fabianfrz** [comment]
I am not the one who has to accept it - you have to ask @fichtner  and @AdSchellevis for that - I am the person who wrote the current implementation which works quite well in almost all cases and I don't see any need for this so I will not implement it. For URL filtering, ICAP is in my opinion too much overhead since at least two headers have to be sent (HTTP Header and ICAP Header) and it may be a lot slower than normal URL filtering. From my point of view I would suggest you to import the lists into squid.

**Comment by airetday** [comment]
@fabianfrz 

> From my point of view I would suggest you to import the lists into squid
I have no list, I have access to an ICAP service. Is this understandable ?

**Comment by fichtner** [comment]
@airetday @fabianfrz I'm ok with splitting the REQMOD / RESPMOD into separate settings to be used as none, one or both. Shall I do this then?

**Comment by fabianfrz** [comment]
If you like to. It should not be hard to implement.

**Comment by airetday** [comment]
@fichtner The simplest patch is
```
diff --git a/src/opnsense/mvc/app/models/OPNsense/Proxy/Proxy.xml b/src/opnsense/mvc/app/models/OPNsense/Proxy/Proxy.xml
index 520ddea6d..7f1968ecd 100644
--- a/src/opnsense/mvc/app/models/OPNsense/Proxy/Proxy.xml
+++ b/src/opnsense/mvc/app/models/OPNsense/Proxy/Proxy.xml
@@ -385,12 +385,12 @@
                     <Required>Y</Required>
                 </enable>
                 <RequestURL type="TextField">
-                    <Required>Y</Required>
+                    <Required>N</Required>
                     <default>icap://[::1]:1344/avscan</default>
                 </RequestURL>
                 <ResponseURL type="TextField">
                     <default>icap://[::1]:1344/avscan</default>
-                    <Required>Y</Required>
+                    <Required>N</Required>
                 </ResponseURL>
                 <SendClientIP type="BooleanField">
                     <Required>Y</Required>
```

This will generate, when both text fields are empty, a useless but valid configuration, and allows to use only one of REQMOD or RESPMOD.
