### ISSUE TITLE
_VPNV6 gateways always created, even when V6 disabled for OpenVPN Clients

### ISSUE THREAD

**Issue by rootwyrm** [opnsense/core#2450]
The system always creates _VPNV6 gateways, even for OpenVPN clients with IPv6 explicitly disabled. These gateways also cannot be deleted and will be recreated every time the client connects.

![](https://i.imgur.com/MZntuUE.png)
![](https://i.imgur.com/4qnUpV0.png)

**Comment by rootwyrm** [comment]
Here is what the ifconfig and routing looks like for the running OpenVPN client. Note that the VPN Client is _not_ acting as the default gateway.

```
ovpnc3: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> metric 0 mtu 1500
        options=80000<LINKSTATE>
        inet6 fe80::250:56ff:fe83:11cb%ovpnc3 prefixlen 64 scopeid 0xb
        inet 10.7.7.2 --> 10.7.7.1  netmask 0xffffff00
        nd6 options=21<PERFORMNUD,AUTO_LINKLOCAL>
        groups: tun openvpn
        Opened by PID 46040

root@anshe:~ # netstat -rn | grep ovpn
10.7.7.0/24        10.7.7.1           UGS      ovpnc3
10.7.7.1           link#11            UH       ovpnc3
10.12.0.0/24       10.12.0.2          UGS      ovpns1
10.12.0.2          link#9             UH       ovpns1
fe80::250:56ff:fe83:11cb%ovpns1   link#9                        UHS         lo0
fe80::250:56ff:fe83:11cb%ovpnc3   link#11                       UHS         lo0
```

The odd numbering is due to a separate issue with `tun(4)` interfaces not being cleaned up when clients are deleted, unrelated to this issue.

**Comment by rootwyrm** [comment]
As requested on IRC... question is, how to infer the device node name of a tun/tap after renaming in ifconfig. This also exposed another bug related to gateways and groups - an interface is not removed from groups either.

Since we aren't working with cloned interfaces, these will have a link-local address. Of course, this link local address will be the same as the first non-loopback interface on the system. However, each interface must have a _unique_ scopeid. The scopeid will populate even if an ovpnc has IPv6 disabled (IPv6 is disabled in the OpenVPN process rather than the interface - this is a requirement for mixed-scheme environments.)

So for example:
```
        inet6 fe80::250:56ff:fe83:11cb%vmx0 prefixlen 64 scopeid 0x1
        inet6 fe80::250:56ff:fe83:3407%vmx1 prefixlen 64 scopeid 0x2
        inet6 fe80::250:56ff:fe83:7839%vmx2 prefixlen 64 scopeid 0x3
        inet6 fe80::250:56ff:fe83:bfee%vmx3 prefixlen 64 scopeid 0x4
        inet6 fe80::1%lo0 prefixlen 64 scopeid 0x5
        inet6 fe80::250:56ff:fe83:11cb%ovpns1 prefixlen 64 scopeid 0x9
        inet6 fe80::250:56ff:fe83:11cb%tun2 prefixlen 64 scopeid 0xa
        inet6 fe80::250:56ff:fe83:11cb%ovpnc3 prefixlen 64 scopeid 0xb

tun2: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> metric 0 mtu 1500
        options=80000<LINKSTATE>
        inet6 fe80::250:56ff:fe83:11cb%tun2 prefixlen 64 scopeid 0xa
        nd6 options=21<PERFORMNUD,AUTO_LINKLOCAL>
        groups: tun NordVPN
```

Now, I will manually rename tun2 to demo0:

```
demo0: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> metric 0 mtu 1500
        options=80000<LINKSTATE>
        inet6 fe80::250:56ff:fe83:11cb%demo0 prefixlen 64 scopeid 0xa
        nd6 options=21<PERFORMNUD,AUTO_LINKLOCAL>
        groups: tun NordVPN
```

However, the `scopeid` will only exist if the interface is actually brought up. However, if an ovpnc is failing to connect for any reason, the link-local and scopeid will not populate. So creating an 'invisible' group like `__tunnelN` on a per-interface basis may make more sense here.

**Comment by fichtner** [comment]
@rootwyrm thanks! it seems that "ifconfig tunX create" creates tunX already, so the only race that could happen is that someone uses e.g. tun2 but GUI wants to create an OpenVPN ID 2 because that is the next one to create after ID 0. In that case the GUI code will "steal" the existing tun2, thinking it is up for grabs.

On the bright side, the destroy on delete works for tun and tap.

**Comment by fichtner** [comment]
ac1c2ec will do the trick

**Comment by rootwyrm** [comment]
@fichtner this needs reopened as a **major** regression found in 19.7.4 that has been made MUCH worse.

This is even worse than before. Now it creates both `V4` and `V6` gateways, and selects the `V6` gateway as active, refuses to make the `V4` gateway active when a gateway is present. Attempt to delete the V6 gateway, and it gets brought back as active. Attempt to disable it, it just gets brought back as active. How did this get missed?? This makes non-IPv6 VPN clients basically broken!

**Comment by rootwyrm** [comment]
So did some further digging and analysis and this is part regression, part "upstream is smoking crack." As of 2.4, OpenVPN _defaults_ to IPv6 and _insists_ on it being available. (Which as you might guess, blows up everyone's Docker stuff, just as an opener. It's exceptionally braindead on their part.)

Now, it is also **not supposed to** do this if you have the following lines in your config:
```
pull-filter ignore "ifconfig-ipv6 "
pull-filter ignore "route-ipv6 "
```

So, the `Disable IPv6` tickbox in theory needs to apply those two lines to the configuration _in addition to_ what it already does. Also, you **must** specify as "TCP4" or "UDP4". However, you will probably be completely unsurprised to hear that having all of that still results in OpenVPN creating an IPv6 gateway no matter what.

And if you have any sort of IPv6, it cheerfully sets up a default route conflict at priority 255, sending your traffic down a non-existent VPN tunnel. So just disable IPv6, right? No. [If you disable IPv6, then OpenVPN 2.4.x will refuse to work _period_.](https://community.openvpn.net/openvpn/ticket/849)

What this ALSO means is because OpenVPN is now broken in such a way that it no longer respects user settings in the least, any client reconnect instantly causes nasty route conflicts and a complete disruption of all connections. Including IPv4. Even when it's not supposed to pull or insert the routes. <insert 'great job' GIF here> 

So basically, OpenVPN now insists on creating IPv6 AND an IPv6 gateway no matter what, at all costs, _especially_ if that means deliberately breaking or disrupting your entire network with a completely bogus default route to nowhere despite setting it to not pull or set default routes. And treats any desire to NOT have IPv6 on your OpenVPN configuration as a, quote the developers, "a pilot error." No small irony that this is exclusive to client; servers configured at `tcp4` or `udp4` do not inflict this utter stupidity on the user.

The only way I see working around the delusional-at-best attitude of OpenVPN here is to somehow instruct OPNsense to explicitly ignore and not create the IPv6 gateway for an OVPN client that does not explicitly request one. Otherwise, the user is going to get badly screwed from a POLA perspective as their VPN quits working or their traffic stops working because of an IPv6-to-nowhere.

**Comment by mannp** [comment]
I am getting this issue on 20.7 and wondered if there was a solution or workaround?

I have currently disable the IPv6 gateways and am not sure if that is sufficient.

Thanks

**Comment by twodrops** [comment]
I am getting this with 21.1.7_1 as well. For now, I disabled IPv6 gateways as deleting them simply makes them active again. Any fix/workaround possible to remove those IPv6 gateways?

**Comment by fichtner** [comment]
See here for our contribution guidelines https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

**Comment by sanxiago** [comment]
When configuring the OpenVPN Server just choose "UDP4" from dropdown on proto.

**Comment by mannp** [comment]
> When configuring the OpenVPN Server just choose "UDP4" from dropdown on proto.

Doesn't change anything for me, always had OV defined with UDP4, but IPv6 always appears and becomes enabled.

**Comment by coreybrett** [comment]
Seems like this is still an issue. Is disabling the v6 gateways the only fix ? I know pfSense has an option in the client configuration to control this behaviour.

**Comment by phpcitizen** [comment]
Is this really an issue for the last 5 years?

**Comment by fichtner** [comment]
I don't see a functional issue resulting from this behaviour? pfSense also made it this way in the first place ;)
