### ISSUE TITLE
Intel 8th Gen Core Platform (B360 and others)

### ISSUE THREAD

**Issue by jcberthon** [opnsense/core#2451]
I've built a small router based on PC parts, rather recent. I'm using the Gigabyte B360N WiFi motherboard which has a dual NIC:

* the Intel B360 chipset's integrated NIC, based on i219-V
* an extra NIC based on i211

Installation and boot of OPNsense 18.1.8 worked flawlessly! But the i219-V NIC is not recognised. Only the igb driver is loaded (for the i211 NIC) and I can configure this interface. But the em driver (which should recognise the i219-V NIC) does not see any other NIC.

It seems that the FreeBSD core is not yet compatible with Intel 8th Generation Core CPUs, at least with respect to the embedded NIC inside B360 chipset (and potentially other chipset that support this new Coffee Lake family).

_PS: I've tried FreeBSD 11.1 which also failed to recognised the other NIC. However, Ubuntu 18.04 (based on using Linux kernel 4.15) recognised both NIC._

_PS2: I still have installed OPNsense at the moment. But in the coming days I will wipe it and install Ubuntu and create a simple router from scratch while waiting for FreeBSD to support this newer generation. If you would like any logs or command output, I can still provide them in the coming days._

**Comment by fichtner** [comment]
If FreeBSD 11.2 is better we may be able to backport. Have done so for ixl and ixgbe.

**Comment by jcberthon** [comment]
I can try testing the rc.

**Comment by fichtner** [comment]
@jcberthon found hints to "Add support for Kaby Lake generation i219 (4) and i219 (5) devices." which would mean that's what you're looking for, but will wait for your confirmation.

**Comment by fichtner** [comment]
Done via https://github.com/opnsense/src/commit/6f9578aef0133856ff4cf57d88f18265e7b00532 -- will be in 18.7-RC and 18.7 if all goes well.

It's possible to test the kernel in 18.1.x via:

    # opnsense-update -kr 18.1.9-next -n "snapshots\/dummy"

Public CFT will be out in a few days, too.

**Comment by jo-erlend** [comment]
That motherboard comes with Intel CNVi wireless as well, which according to Intel should be capable of being used as access point in 802.11ac mode if their heuristics determine that it's legal. Have you tried this, or if not, would you care to?
