### ISSUE TITLE
3gstats detects wrong monitor device for Huawei ME909s-120

### ISSUE THREAD

**Issue by pv2b** [opnsense/core#2453]
Hi.

I have a Huawei ME909s-120 in one of my firewalls, that I was able to get to work (after changing an init string to `&F`, but that's a different issue that I'll post later).

I noticed however that the code that is in OPNsense right now (as of release 18.1.9) seems to assume that the last cua device that belongs to the modem is the one where the status output comes out on. That's not a correct assumption, at least not on my modem.

A workaround to make the statistics almost work is as below:

```
root@pvz-lab:~ # ps axuw|grep 3gstats
root    11193   0.0  0.5  112252 19832  -  Is   15:29    0:00.13 /usr/local/bin/php /usr/local/sbin/3gstats.php cuaU0.4 wan
root    29230   0.0  0.1 1080528  2864 u0  S+   15:32    0:00.01 grep 3gstats
root@pvz-lab:~ # kill 11193
root@pvz-lab:~ # /usr/local/bin/php /usr/local/sbin/3gstats.php cuaU0.2 wan
^Z
Suspended
root@pvz-lab:~ # bg
[1]    /usr/local/bin/php /usr/local/sbin/3gstats.php cuaU0.2 wan &
```

After applying this workaround, `/tmp/3gstats.wan` seems to be created correctly and is at least updated with a correct RSSI value, but still the statistics I can't see them in the WebUI. Not sure what process polls this tmp file.

```
root@pvz-lab:/tmp # cat /tmp/3gstats.wan
#seconds,rssi,mode,submode,upstream,downstream,sentbytes,receivedbyts,bwupstream,bwdownstream,simstate,service
0,21,0,0,0,0,0,0,0,0,0,0
root@pvz-lab:/tmp #
```

The code that seems to determine which monitor device to use is found here:

https://github.com/opnsense/core/blob/ecc15a7680c58a4bdea4bbf3876c8e6aeceab8ee/src/etc/inc/interfaces.inc#L1519

This might also be useful:

```
root@pvz-lab:/tmp # usbconfig | egrep -ie '(huawei)'
ugen2.3: <Huawei Technologies Co., Ltd. HUAWEI Mobile V7R11> at usbus2, cfg=0 md=HOST spd=FULL (12Mbps) pwr=ON (2mA)
```

**Comment by fichtner** [comment]
Timeout
