### ISSUE TITLE
Reporting -> Traffic not listing IPv6 streams

### ISSUE THREAD

**Issue by sjorge** [opnsense/core#2455]
![screenshot](https://imgur.com/FSXZDN6.png)

You can see around 10MB/s download coming in on IF_WAN6 and going to IF_CLNT (I checked both the IF_WAN6 and IF_CLNT for the streams).

(IF_WAN6 is a tunnel so that is why there is also the same traffic in on IF_WAN4)

**Comment by fichtner** [comment]
AFAIK, this is an issue with the used "rate" utility which doesn't know about IPv6.

**Comment by fichtner** [comment]
I took a small peek inside and this this IPv6 support for "rate" is not a project to be carried from our side.
