### ISSUE TITLE
Backup options request

### ISSUE THREAD

**Issue by PHoBwz** [opnsense/core#2456]
This is a feature request. 

Could the backup/restore options be opened up a bit. Great that there is a G-drive option but not ideal for anyone who doesnt trust Google (most people) or the enterprise. Could there be an option to create an archive and upload to SCP/SFTP/FTP and then have a schedule of that too?

Had a quick few searches in the issues but couldn't find anything relating to this.

**Comment by fichtner** [comment]
We made the backups fully pluggable in 18.1.9. Nextcloud is coming to 18.1.10. SCP is queued up for a later date, no later than 18.7. I'm closing this since the work is done and additional options can be added by users. :)
