### ISSUE TITLE
RRD graph of temperature

### ISSUE THREAD

**Issue by mschilt** [opnsense/core#246]
There is the current temperature displayed in the lobby. Would love to have it available as RRD graph.

**Comment by jschellevis** [comment]
I already created the requered files for that, will add it in august cause I have not got the time for it at the moment.

**Comment by jschellevis** [comment]
@mschilt I have not finished this work yet as I will completely replace the current RRD Graphs with a new "System Health" module... see blog: https://opnsense.org/system-health-whats-next/ 
When this is released I'll add the system temperature as well.
