### ISSUE TITLE
Consistent "Bus error (core dumped)" error when attempting to select boot type

### ISSUE THREAD

**Issue by DBReinitialized** [opnsense/core#2468]
Attempting to install OPNSense on Hyper-V running on Windows 10 Professional 1803.17134.112 is consistently failing with "Bus error (core dumped): The installation was aborted". It should be noted I was able to install OPNSense without failure previously on a Hyper-V Generation 2 VM and it worked fine. After attempting to reinstall it due to a need, I began to be plagued with the issue:
<br>
<br>complete lockup of installation at the Guided Selection/Manual Selection installation screen. 
<br>
<br>To solve the issue, I recreated the VM and deleted all previous data of the old VM. I was then able to proceed past the Guided Installation until I now run into the "Bus error (core dumped)" when attempting to select either UEFI or legacy. Strangely, after the error is thrown, I am given the option to log back in (either as root or installer). If I log back in, I will then be able to proceed to the "Swap Partition" menu (able to select either Yes or No), but will freeze when selecting either answers.

Images:

![image](https://user-images.githubusercontent.com/20674500/41624736-2554013c-73dc-11e8-9f7c-ba166077a8b4.png)
Bus error (core dumped) message

![image](https://user-images.githubusercontent.com/20674500/41624654-0b08431a-73dc-11e8-9b33-98f2adef4a52.png)
frozen screen

**Comment by fichtner** [comment]
This is a known issue. We have to reevaluate on HardenedBSD 11.2.
