### ISSUE TITLE
IDS / enable legacy:uricontent

### ISSUE THREAD

**Issue by mschilt** [opnsense/core#247]
Many rules from ET still use "uricontent" keyword. This is disabled by default which leads to a lot of not-working rules and various log messages.

Could be fixed by enabling it in 
/usr/local/opnsense/service/templates/OPNsense/IDS/suricata.yaml
```
legacy:
  uricontent: enabled
```

**Comment by AdSchellevis** [comment]
Thanks for reporting, it should be fixed with https://github.com/opnsense/core/commit/de8d93960df5985adebfc149c6548f290e86a9e4

**Comment by fichtner** [comment]
Neat. git-cherry-pick to stable/15.7 right away? :)

**Comment by AdSchellevis** [comment]
yes please! :-)

**Comment by fichtner** [comment]
Please do me the honour. I'm on the road. Good luck. :D

**Comment by mschilt** [comment]
woot! always a pleasure..

**Comment by fichtner** [comment]
your first stable cherry-pick, @AdSchellevis  :)

@mschilt keep them coming, thanks!!

**Comment by AdSchellevis** [comment]
yes! this works like a charm.
