### ISSUE TITLE
Reference to alias object in NAT rule is lost after rename

### ISSUE THREAD

**Issue by PhilippKendlbacher** [opnsense/core#2470]
If a NAT rule refers to an alias as source address and then the same alias is renamed, the reference in the NAT rule is not updated to the new alias name. As a result the NAT rule does not work anymore.

**Comment by fichtner** [comment]
@PhilippKendlbacher even with the fix from #1711 ?

**Comment by PhilippKendlbacher** [comment]
I am running version 18.1.9 which is the latest "production" version.

**Comment by fichtner** [comment]
Please try ef519606 which is part of tomorrow's 18.1.10:

    # opnsense-patch ef519606


Cheers,
Franco

**Comment by PhilippKendlbacher** [comment]
I am sorry but an upgrade to 18.1.10 did not solve the problem. 
When i rename the alias, the source address changes like this:
![after_rename](https://user-images.githubusercontent.com/40423029/41714566-fce09456-7550-11e8-99b0-5f917859ce84.png)
This was before renaming the alias:
![before_rename](https://user-images.githubusercontent.com/40423029/41714595-1b4fbfa2-7551-11e8-80f4-61cd1e374365.png)

Thanks,
Philipp

**Comment by fichtner** [comment]
No worries, let's see if we can find this :)

**Comment by AdSchellevis** [comment]
fixed with the new api enabled aliases. (checked source/destination/target on my install)

ref:
https://github.com/opnsense/core/blob/5d49c6afcda115fa563ca06e16bb165bc31f9d6e/src/opnsense/mvc/app/models/OPNsense/Firewall/Alias.php#L60-L64

**Comment by FrankWeis** [comment]
I have just had this again in 19.7.3.
Had an alias, used it in a NAT rule. Edited and renamed the alias for clarity, and after wondering why my NAT stopped working I came to find it dangling.
