### ISSUE TITLE
Wrong generated Unbound ACLs

### ISSUE THREAD

**Issue by bewue** [opnsense/core#2472]
OPNsense 18.1.9
If you use virtual IPs (Unbound: General: "Network Interfaces"), the generated ACLs (Unbound: Access Lists) are always /29 subnets.
I have multiple virtual IPs (public IPs) on one interface.

**Comment by fichtner** [comment]
I am inclined to kill the auto-ACL feature as it doesn't work very well with OpenVPN either. @AdSchellevis thoughts?

**Comment by go2sh** [comment]
We also had a problem with the feature and changing IPv6 prefixes.

**Comment by AdSchellevis** [comment]
@fichtner it doesn't win the beauty contest, I thought of removing it a long time ago too, but the defaults without it are a bit too strict which is confusing for new users. I'm not sure what we can do best here, I expect quite some complaints when we move to manual during a major upgrade.

**Comment by fichtner** [comment]
I'll take a closer look, but no big promises at the moment.

**Comment by fichtner** [comment]
So to be honest all it does is find one single global IP on the interface for IPv4 and IPv6 and that's it. SSH and web GUI have recently gained more code to improve the situation, but it's a rocky road forward...

**Comment by fichtner** [comment]
The feature was reworked to read all addresses. There are two caveats:

1. Adding new VIPs or other network configuration will not automatically restart Unbound. This issue always existed before but may be more prominent now.
2. OpenVPN will probably not work here anymore, but that makes it consistent with IPsec.

**Comment by AdSchellevis** [comment]
@fichtner thanks for fixing, it looks better in my opinion.  Personally I do prefer the new approach of using the configured data in stead of trying to reconstruct anything that might not be there. OpenVPN is indeed a small offer we should be willing to make.
