### ISSUE TITLE
Intel Denverton arch not supported in 11.1 but ok in 11.2

### ISSUE THREAD

**Issue by bobafrinet** [opnsense/core#2473]
After different set of tests, It looks like Intel Denverton architecture is supported in FBSD 11.2 but not yet in 11.1 

AHCI drivers seems to have been updated. 

https://forum.opnsense.org/index.php?topic=8954.0

This the boot on OPNSense on 18.1 where we have :

> […]
> umass0:4:0: Attached to scbus4                                                 
> ahcich8: Timeout on slot 5 port 0                                               
> ahcich8: is 00000002 cs 00000000 ss 00000000 rs 00000020 tfd 50 serr 00000000 c7
> (aprobe0:ahcich8:0:0:0): ATA_IDENTIFY. ACB: ec 00 00 00 00 40 00 00 00 00 00 00
> (aprobe0:ahcich8:0:0:0): CAM status: Command timeout                           
> (aprobe0:ahcich8:0:0:0): Retrying command                                       
> run_interrupt_driven_hooks: still waiting after 60 seconds for xpt_config       
> […]

Where on FBSD 11.2-RC3 we have: 

> […]
> ahcich8: <AHCI channel> at channel 7 on ahci1                                   
> ahciem1: <AHCI enclosure management bridge> on ahci1                           
> xhci0: <Intel Denverton USB 3.0 controller> mem 0xdff80000-0xdff8ffff irq 19 at
> device 21.0 on pci0                                                             
> xhci0: 32 bytes context size, 64-bit DMA
> […]

A backported version of the AHCI package will be very useful…

**Comment by fichtner** [comment]
we have a preliminary backport going on for 18.7, kernel to try soon...

https://github.com/opnsense/src/commit/4d136a0d914280f2183e8125f6b1ad6c0eb4eb59

**Comment by fichtner** [comment]
Loads up ok, will provide image soon.

**Comment by fichtner** [comment]
@Uica https://pkg.opnsense.org/FreeBSD:11:amd64/snapshots/OPNsense-18.7.r-ahci-OpenSSL-vga-amd64.img.bz2

**Comment by Uica** [comment]
@fichtner: No luck. I‘m seeing some Denverton AHCI related messsages in dmesg, but still getting this CAM command timeouts. No hard disk recognized.
I can provide the dmesg file from today‘s test, and a dmesg from pfSense for comparison, if that helps.

**Comment by fichtner** [comment]
Fun. Can't go on a wild goose chase at the moment any more than already done, but I will try to find a bit of time between RC1 and RC2 to find out more. Sorry. :(

**Comment by Uica** [comment]
Sure, thanks for trying! Let me know if I can help with more testing later.

**Comment by bobafrinet** [comment]
I can confirm the AHCI bug is still persistent. 

Attached is the boot sequence. 
[Boot_18-7-AHCI.txt](https://github.com/opnsense/core/files/2169414/Boot_18-7-AHCI.txt)

**Comment by fichtner** [comment]
Yup, all help in figuring out which code we are currently missing is welcome. The focus of our work now is to get 18.7-RC1 and 18.1.12 out the door so it's not within my immediate reach to look for more backports which won't make the cut for 18.7-RC1 in any case.

**Comment by bobafrinet** [comment]
This is the part of boot which starts to go wrong : 

> Timecounters tick every 1.000 msec                                              
> nvme cam probe device init                                                      
> ugen0.1: <0x8086 XHCI root HUB> at usbus0                                       
> uhub0: <0x8086 XHCI root HUB, class 9/0, rev 3.00/1.00, addr 1> on usbus0       
> uhub0: 8 ports with 8 removable, self powered                                   
> ugen0.2: <UFD 3.0 Silicon-Power16G> at usbus0                                   
> umass0 on uhub0                                                                 
> umass0: <UFD 3.0 Silicon-Power16G, class 0/0, rev 3.00/11.00, addr 1> on usbus0 
> umass0:  SCSI over Bulk-Only; quirks = 0x4000                                   
> umass0:4:0: Attached to scbus4                                                  
> ahcich0: Timeout on slot 5 port 0                                               
> ahcich0: is 00000002 cs 00000000 ss 00000000 rs 00000020 tfd 50 serr 00000000 c7
> (aprobe0:ahcich0:0:0:0): ATA_IDENTIFY. ACB: ec 00 00 00 00 40 00 00 00 00 00 00 
> (aprobe0:ahcich0:0:0:0): CAM status: Command timeout                            
> (aprobe0:ahcich0:0:0:0): Retrying command                                       
> run_interrupt_driven_hooks: still waiting after 60 seconds for xpt_config       
> ahcich0: Timeout on slot 6 port 0                 


And this is the same part found on a FreeBSD 11.2-Release where boot is ok : 

> Timecounters tick every 1.000 msec                                              
> ugen0.1: <0x8086 XHCI root HUB> at usbus0                                       
> uhub0: <0x8086 XHCI root HUB, class 9/0, rev 3.00/1.00, addr 1> on usbus0       
> ses0 at ahciem0 bus 0 scbus1 target 0 lun 0                                     
> ses0: <AHCI SGPIO Enclosure 1.00 0001> SEMB S-E-S 2.00 device                   
> ses0: SEMB SES Device                                                           
> ses1 at ahciem1 bus 0 scbus3 target 0 lun 0                                     
> ses1: <AHCI SGPIO Enclosure 1.00 0001> SEMB S-E-S 2.00 device                   
> ses1: SEMB SES Device                                                           
> ada0 at ahcich0 bus 0 scbus0 target 0 lun 0                                     
> ada0: <TS32GMTS400S P1225CH1> ACS-2 ATA SATA 3.x device                         
> ada0: Serial Number 0208834FE28807020153                                        
> ada0: 600.000MB/s transfers (SATA 3.x, UDMA6, PIO 1024bytes)                    
> ada0: Command Queueing enabled                                                  
> ada0: 30533MB (62533296 512 byte sectors)                                       
> Trying to mount root from ufs:/dev/ufs/FreeBSD_Install [ro,noatime]...          
> Root mount waiting for: usbus0                                                  
> uhub0: 8 ports with 8 removable, self powered                                   
> ugen0.2: <UFD 3.0 Silicon-Power16G> at usbus0                                   
> umass0 on uhub0                                                                 
> umass0: <UFD 3.0 Silicon-Power16G, class 0/0, rev 3.00/11.00, addr 1> on usbus0 
> umass0:  SCSI over Bulk-Only; quirks = 0x4000                      


So from my understanding It might come from the ses0 driver which doesn't seem to be detected. 
https://www.freebsd.org/cgi/man.cgi?query=sesutil&sektion=8&manpath=FreeBSD+11.2-RELEASE+and+Ports

Maybe a kernel compile time option related to ses is not detected…      

I'll try to have a helping hand having a look at this.

**Comment by opnsenseuser** [comment]
i get the same error.

Strangely, the first installation worked. After about 3 reboots came then this error.

Now i can´t even boot opnsense from harddisc too.

i´m using atom c3558

I was already looking forward to 18.7, because I thought that with it, the atom c3000 works. Pity!

**Comment by fichtner** [comment]
> I was already looking forward to 18.7, because I thought that with it, the atom c3000 works. Pity!

Did we mislead you in this in any way? Can you point to the material that is ambiguous?


Thanks,
Franco

**Comment by opnsenseuser** [comment]
I just thought that only the nic drivers are missing and then the atom c3000 works. but that was probably misinterpreted by me. I think there are more important things for opnsense and so I have to wait until the end of the year and as soon as opnsense on freebsd 11.2 converts it will work. I just wanted to write that I have the same problem but I do not blame or blame anyone. please do not be angry. best regards, rene

**Comment by fichtner** [comment]
I'll promise to work on an early 11.2 preview and fix the Denverton issue subsequently. For the initial 18.7 we can't make it so I apologise if that is inconvenient.

Thank you,
Franco

**Comment by opnsenseuser** [comment]
do not stress. it fits as it is. thanks for your commitment. KR René

**Comment by opnsenseuser** [comment]
I would really like to help find the problem, but unfortunately I know myself with the topic of kernel and drivers too little. I prefer to keep my fingers off that. best regards rené

**Comment by opnsenseuser** [comment]
by the way.
i´m using a m.2 disc

**Comment by opnsenseuser** [comment]
I found out the following. 

The latest dev version of pfsense 2.4.4 works without problems. I just want to say this, so maybe this can help save time.

**Comment by fichtner** [comment]
The 2.4.4 dev branch is using FreeBSD 11.2 indeed. Note that while 2.4.4 may still be a few months out 18.7 is due this month and 11.2 just came out so for us with our fixed schedule it's not the best spot so we would rather keep 11.1 for a little longer and give 11.2 the testing it deserves.

**Comment by opnsenseuser** [comment]
I agree with you.

**Comment by fichtner** [comment]
Need to move this to 19.1 as 18.7 is approaching.

**Comment by bobafrinet** [comment]
I am not sure to understand why you are using 11.1 as target for this release. 
11.1 is going to be outdated September 30, 2018. So it means that if any security breach is disclosed after this date, It might not necessarily be ported (will probably, but not necessarily)… 

https://www.freebsd.org/security/security.html

18.7 might have been pushed back in time a bit, but It might have been simpler to have "loose" release dates which will keep up with upcoming releases ?

Real shift will come with 19.1 from what I can read. 
Is there a chance to see a branch in 18.7 based on 11.2 ?

**Comment by fichtner** [comment]
This has been discussed before. We do not set EoL policies for FreeBSD or have influence on their release date. Long story short it's not enough time to test and deploy 11.2 before 18.7 comes out.

**Comment by vogelfreiheit** [comment]
Also having this issue, are the snapshots any good to make this work, out of curiosity? Did the AHCI drivers get backported and are part of the images right now?

**Comment by Uica** [comment]
@vogelfreiheit  I am currently using 18.7.1 on a Denverton system (Supermicro), but that’s only possible with BIOS tweaks (which only took effect after a full power cycle). The AHCI drivers have not been backported. The intel network drivers have been backported, though, and are working fine on my system, including the use of VLANs. I have seen other discussions that indicated that both the current 18.7/18.7.1 kernels and also FreeBSD 11.2 have generated some new problems with those network drivers on certain systems, so I doubt that the developers will rush into backporting even more parts from 11.2. 
That’s just my observation as a user, though.

**Comment by vogelfreiheit** [comment]
What is the status of the AHCI driver now?

**Comment by fichtner** [comment]
Same as it was when it was last discussed: it works on FreeBSD 11.2, not 11.1.

**Comment by fichtner** [comment]
About to land in src.git master branch...
