### ISSUE TITLE
CPU graph percentage always in the middle

### ISSUE THREAD

**Issue by weust1979** [opnsense/core#2478]
I've noticed this in 17.* too, and now in 18.1.r2 as well.
In several web browsers I noticed that when I hover the mouse cursor over the CPU graph it always shows the percentage in the middle, showing the CPU percentage it was when at the middle.

Example, the screenshot shows 3%, but that's from after the spike a bit to the left of the middle.

My OS is Windows 10, web browsers are Edge and Waterfox. Also saw this in Google Chrome and Vivaldi.

Forum topic reference: https://forum.opnsense.org/index.php?topic=6888.0

![image](https://user-images.githubusercontent.com/11320409/41810747-b8890176-7703-11e8-94e5-409bdf1316ad.png)

**Comment by fichtner** [comment]
happy to try a fix, maybe @AdSchellevis knows ?

**Comment by AdSchellevis** [comment]
@fichtner I will have to look into it, not sure what the issue is. I'll put it on my list, although it doesn't have a very high priority for me.

**Comment by weust1979** [comment]
@fbrendel Exactly. That way we can see the CPU utilization at a specific time point.
I forgot what the time range is, but say it's 10 minutes. Having small markers per minute in the bottom would be helpful then.

@fichtner @AdSchellevis Making this no high priority is fine. It's just something that feels should be different.

**Comment by fbrendel** [comment]
I can imagine why it is disabled.
If the dashboard refreshes the graph is redrawn.
Then you have only a few data points, whose number is growing over time.
That makes it very difficult to add a legend etc.

**Comment by AdSchellevis** [comment]
The issue is that the number is actually a title on the object, which represents the last known value https://github.com/opnsense/core/blob/18.1.10/src/www/widgets/widgets/system_information.widget.php#L49-L50 

nvd3 tooltips can only be shown within the canvas of the graph, which simply isn't large enough for that. 

I don't expect this is something we can fix, other then also removing the title if that avoids confusion.

**Comment by marjohn56** [comment]
Use the large CPU widget, that shows it correctly. As Ad says, the small display is too small to use... one of the reasons I created the large one.

**Comment by fichtner** [comment]
Should we simply deactivate the small tooltip with the average? The larget CPU widget has data for each point.

Speaking of these points, they are numbered "0,1,2,3,..." while the traffic graph widget shows dates.

**Comment by marjohn56** [comment]
Is it possible to insert the word 'Average' in the tooltip?

I'll take look at the large widget, see if we can improve it a bit.

**Comment by fichtner** [comment]
it's better to ditch the tooltip in the small one, it's only for showing "it's doing something" like a HDD LED... and in your widget we already have tooltips per data point :)

**Comment by marjohn56** [comment]
Well the data points are just time from the start of the widget, 100 points in total.

**Comment by marjohn56** [comment]
I can either insert the word 'Average' or remove the top tooltip, which is preferred? IRC?

**Comment by fichtner** [comment]
I opt for remove for simplicity

**Comment by weust1979** [comment]
Remove then.

**Comment by marjohn56** [comment]
And so it shall be...
