### ISSUE TITLE
Auto update OpenVPN widget on dashboard

### ISSUE THREAD

**Issue by laxmanpradhan** [opnsense/core#2479]
This is a very minor cosmetic thing but it does make life a lot easier when debugging openVPN issues. The openvpn dashboard widget does not autoupdate when a new connection is made or disconnected. You have to refresh the entire page to show the changes. If the widget could poll the openVPN status every 2 seconds or so (or perhaps some push method to show a changed states) and show an updated list of connections, that would make it a lot easier to debug openvpn issues and is simply nicer cosmetically as well. This fits with the overall look of the dashbaord as well since most of the other widgets have real time updates happening.

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository, 
please read https://github.com/opnsense/core/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue, 
just let us know, so we can reopen the issue and assign an owner to it.
