### ISSUE TITLE
IDS / process of enabling new rules looks incomplete

### ISSUE THREAD

**Issue by mschilt** [opnsense/core#248]
I enable new rules and press apply. This is what happens: 
* The UI shows the checkbox marked of the new enabled rules without a "rule update timestamp"
* Suricata is restarted.

What I would expect from that action: 
* The new enabled rules are being downloaded. 
* Timestamp of the rules in the UI is updated
* intalled_rules.yaml is updated with the new files
* suricata is restarted.

**Comment by AdSchellevis** [comment]
Well, downloading of the sets (first tab) is a separate action triggered by "Download & update rules" once that is done you have the option to plan the rule updates periodical using the cron server (this option is only visible after an apply is triggered and you visit the page again, sorry about that).

The yaml file is updated on apply (currently also on download, although there's no real need for it at that point) and the daemon is started/stopped or restarted depending on the configuration.

Every (configurable) ruleset that's on your system is displayed in the grid, so you have some feedback on the download status.

The reason we don't update rules on apply is that this may take some time and updating the rules on every apply really is an overkill (this would also mean that changing the set behaviour on the second tab would require a reload for every apply, which really isn't necessary). 
We probably should add some additional help documentation on screen to make the workflow better understandable.

**Comment by AdSchellevis** [comment]
some additional documentation has been added on screen and the initial (cron) schedule is shown after initial download. this will be in the coming release.
