### ISSUE TITLE
rc.newwanip kills CARP on every other call

### ISSUE THREAD

**Issue by clystron** [opnsense/core#2486]
I have been testing CARP for a firewall using 18.1.10 and I noticed that sometimes the status of a virtual IP is neiter MASTER/BACKUP/INIT but simply nothing. By checking ifconfig output on the console I noticed that the "carp" line is simply gone in these cases which effectively disables carp.

I traced the issue to rc.newwanip, this script is executed on link-up even though all my Interfaces are configured static and it performs two ifconfig calls for each VIP, here is an example:

/sbin/ifconfig igb3 vhid '2' advskew '10' advbase '1' pass 'password'
/sbin/ifconfig igb3 '10.0.1.132'/'16' alias vhid '2'

The second of those commands fails with error 'ioctl (SIOCAIFADDR): Protocol not available' on every other call of rc.newwanip. I have also tried to execute those commands on the console and I have the same problem there. If I execute the second command multiple times I get the error on every other call and CARP is gone on that interface. The error does not occur if I use a different vhid on every call so I guess it is some issue with updating an existing vhid.

This happens on the WAN interface all the time but rc.newwanip can also be called for other interfaces destroying there config as well.

Any thoughts?

**Comment by clystron** [comment]
Seems very simliar to this https://redmine.pfsense.org/issues/6892

**Comment by fichtner** [comment]
Looks like a FreeBSD bug then. Not sure if their patches ever landed upstream, but I can check.

**Comment by fichtner** [comment]
Looks like we want https://github.com/freebsd/freebsd/commit/5bd3158a -- it was never added to stable/11 despite the note "MFC after:	2 weeks"

**Comment by fichtner** [comment]
Backported via https://github.com/opnsense/src/commit/8d1a9170bd4d -- should automatically hit in 18.7-RC1 but I'll prepare a kernel for testing right now.

**Comment by clystron** [comment]
Great, I´d be happy to test if it helps

**Comment by fichtner** [comment]
Thanks! You can install the test kernel via:

    # opnsense-update -kr 18.1.9-next -n "snapshots\/dummy"
    # /usr/local/etc/rc.reboot

Version from uname -a should tell you something about 8d1a9170bd4(master).


Cheers,
Franco

**Comment by clystron** [comment]
The error is gone with this kernel, looks good

**Comment by fichtner** [comment]
Hooray \o/ close ticket? :)

**Comment by clystron** [comment]
I am a little confused about the "18.1.9-next" label, is this the kernel I had running on 18.1.10 with just this one patch applied?

**Comment by fichtner** [comment]
We have had an internal test kernel up previously for what we want to release as 18.7-RC. I simply replaced that kernel, because this CARP change requires the same testing workflow. In general, the name is arbitrary.

**Comment by fichtner** [comment]
(The kernel is based on the master branch of src.git)

**Comment by clystron** [comment]
Lets hope 18.7 gets released on time then.....

**Comment by fichtner** [comment]
Releases never shifted back so far. You can keep this kernel locked until 18.7 is out (system: firmware: packages), which will force a lock release and update anyway.

**Comment by clystron** [comment]
Thats good to know, thanks for your quick responses!

**Comment by fichtner** [comment]
Thank you for the report. ❤️
