### ISSUE TITLE
[18.7.b_344] OpenVPN fails to start after an update.

### ISSUE THREAD

**Issue by sjorge** [opnsense/core#2489]
After updating OpenVPN from TLS+User to simple TLS the server no longer started.
After switching back, the same result.

With some debugging it looks like the server(s) are complaining about this line in the config:
```
dh /usr/local/etc/dh-parameters..sample
```

```
root@hydrogen:/var/etc/openvpn # /usr/local/sbin/openvpn --config /var/etc/openvpn/server3.conf
Wed Jun 27 16:08:24 2018 Note: option tun-ipv6 is ignored because modern operating systems do not need special IPv6 tun handling anymore.
Options error: --dh fails with '/usr/local/etc/dh-parameters..sample': No such file or directory (errno=2)
Options error: Please correct these errors.
Use --help for more information.
```

(I comment the daemon line to debug)

**Comment by fichtner** [comment]
the DH bits are missing from the file name. are they set in config.xml ?

**Comment by fichtner** [comment]
Refs https://github.com/opnsense/core/commit/d840e9acade9dd7

**Comment by sjorge** [comment]
@fichtner nope, I just checked config.xml:

```
<dh_length/>
```

For all 4 my servers, selecting 1024, 2048, 4096 in the drop down and saving has no effect.

**Comment by fichtner** [comment]
brrrr, sorry about that...

**Comment by sjorge** [comment]
I'll apply the diff and try again ...

**Comment by fichtner** [comment]
Thanks for confirming. Stupid mistake. Only on -devel though.
