### ISSUE TITLE
Unable to clear whitlist or backlist  destination domains for Squid (ACL)

### ISSUE THREAD

**Issue by Gul-liver** [opnsense/core#2491]
Using OPNsense 18.1.10-amd64 - FreeBSD 11.1-RELEASE-p10, it seems not possible to clear some white and black lists in the ACL config of Squid when items contains special characters.
For instance: `^https?:\/\/([a-zA-Z]+)\.mydomain\.` given as example in the help section.
Grey cross near each element does'nt operate and the "clear all" button, no more.

**Comment by AdSchellevis** [comment]
this https://github.com/zellerda/Tokenize2/pull/51 should fix the issue, I will add the new library to core shortly.

**Comment by fichtner** [comment]
@AdSchellevis lovely, thanks for that!

**Comment by AdSchellevis** [comment]
@fichtner you're welcome :)  it's almost there ;)
