### ISSUE TITLE
MVC / routing url encoded paths

### ISSUE THREAD

**Issue by AdSchellevis** [opnsense/core#2494]
When routing encoded characters, the action parameters may be wrong (parameters are handled after decode). To solve this we should switch from the default `$_GET['_url'] ` to `$_SERVER['REQUEST_URI']` and let phalcon handle the path routing. 

for reference https://github.com/phalcon/cphalcon/issues/12421 and https://docs.phalconphp.com/en/latest/routing#uri-sources 

The impact of this change should be small, we don't seem to use encoded characters in paths (like `/api/app/module/xxx%201%201%2F2?xx=1`)

**Comment by AdSchellevis** [comment]
to test on 18.1.10:

```
opnsense-patch d1f2ca8 
rm /usr/local/opnsense/mvc/app/models/OPNsense/Base/Menu/Menu.xml.rej
opnsense-patch e62d1ef
```

The menu change in https://github.com/opnsense/core/commit/d1f2ca86490e31ded45e912480a6330629c0ee48 will fail, this can be ignored (hence the `rm`).

**Comment by fabianfrz** [comment]
@AdSchellevis does this change affect the nginx plugin?

**Comment by AdSchellevis** [comment]
@fabianfrz it should be backwards compatible, but removes the use of `_url` in the requests, here https://github.com/opnsense/plugins/pull/696/files#diff-06f3b5be0cabf46e05c08f99c6bdeda9R178 and https://github.com/opnsense/plugins/pull/696/files#diff-06f3b5be0cabf46e05c08f99c6bdeda9R189

**Comment by fabianfrz** [comment]
@AdSchellevis: looks good - can apply the patch to nginx as well.

**Comment by fichtner** [comment]
Close?

**Comment by AdSchellevis** [comment]
@fichtner sorry, forgot
