### ISSUE TITLE
Firewall, category dropdown list not visible via Chrome

### ISSUE THREAD

**Issue by mimugmail** [opnsense/core#2496]
No idea if it's a known bug, but with Chrome I can't see the dropdown list for selecting categories in rules tab. With Firefox it's perfectly displayed / useable.

**Comment by AdSchellevis** [comment]
it looks like it, I seem to be missing the selector as well on my in in chrome

**Comment by AdSchellevis** [comment]
@mimugmail my mistake, on my end it seems to be there (forgot to add some categories), which version do you use? I seem to have version 67.0.3396.87 on my end.

**Comment by mimugmail** [comment]
![compare](https://user-images.githubusercontent.com/20438689/42125182-fd36ea54-7c71-11e8-8fc4-f61b4f002f78.png)

67.0.3396.99

**Comment by fabianfrz** [comment]
@mimugmail does the JS console show an error on a page reload?

**Comment by mimugmail** [comment]
No error found, also cleared the cache and restarted Chrome, still not working.

**Comment by AdSchellevis** [comment]
@mimugmail I've just upgraded Chrome to match your version, but don't seem to have your issue. Is your issue consistent with stable and devel? (devel is slightly different, it seems we have the Add button there in the same corner)

**Comment by AdSchellevis** [comment]
it could also be a plugin in chrome altering the page in some way

**Comment by mimugmail** [comment]
I installed Chrome on a machine where there was only Firefox, with 18.7 beta it's working, 18.1.10 vanilla it's working, 18.1.10 with HAProxy no category. Really strange ..

**Comment by AdSchellevis** [comment]
really odd, my box has haproxy installed too it seems, but no issue. did you perhaps install `os-cache` ?

**Comment by mimugmail** [comment]
I'll close this now .. have to do some more testing with other machines.
