### ISSUE TITLE
[FR] www/nginx: assign certificates to users or in the other direction to allow TLS logins

### ISSUE THREAD

**Issue by fabianfrz** [opnsense/core#2497]
It would also work to get the username as the common name of the certificate but that may be a bit too dangerous as there is only this loose trust relationship.

**Comment by fichtner** [comment]
This is a core ticket to mimmic the behaviour of OpenVPN user certificates?

**Comment by fabianfrz** [comment]
yes, just for login on the web interface using client certificates.

**Comment by fichtner** [comment]
I’ll have a look. Not sure about the 19.1 target though. Just so it is looked at sooner than later.

**Comment by fabianfrz** [comment]
@fichtner just tell me what you need, I can pass almost everything that is supported to the PHP interpreter in the $_SERVER variable using a freely defined name.

Here is a list of the supported variables:
https://nginx.org/en/docs/http/ngx_http_ssl_module.html#variables

**Comment by AdSchellevis** [comment]
Is this supposed to support ui logins? in that case it looks a lot like https://github.com/opnsense/core/issues/1718 (which I've tested for lighttpd) 

The username is stored in the environment variable `REMOTE_USER` according to the docs https://redmine.lighttpd.net/projects/lighttpd/wiki/Docs_SSL 

Or is this something else?

**Comment by fabianfrz** [comment]
@AdSchellevis yes, it is probably the same but a different server as the frontend so I can mimic the behaviour of the lighttpd so both servers act the same way.

**Comment by fabianfrz** [comment]
both are easy to implement - it needs a CA to validate against and the common name can be passed in any case but can also be made configurable. The only thing is that the API has to look into the server array and if it finds a CN, it should check if a user is assigned and if yes, do a stateless login like the basic auth.

All the parts in the nginx plugin can be done by me, but the issue is about the backend supporting it in general (in case of #1718 also for lighttpd) so it is not specific for a server.

If there is no backend configuration, this may have side effects because some users may share the CA with OpenVPN (use different ones for both) and the main purpose is for API clients but browsers could be used as well.

In nginx this are two directives and one optional for more security:

* https://nginx.org/en/docs/http/ngx_http_ssl_module.html#ssl_verify_client
* https://nginx.org/en/docs/http/ngx_http_ssl_module.html#ssl_client_certificate
* https://nginx.org/en/docs/http/ngx_http_ssl_module.html#ssl_crl (optional, but recommended)

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/core/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
