### ISSUE TITLE
Backup file name contains colon, which is not allowed in Windows

### ISSUE THREAD

**Issue by astrandb** [opnsense/core#2498]
I am testing backup to Nextcloud. The file name of the backup is typically config-myrouter.mydomain-2018-06-30_18:55:00.xml . However, the colon used as time separator is not allowed in filenames in Windows. If you download a backup file via the web interface Nextcloud will translate the colon to an underscore. The Nextcloud sync client for Windows refuses to sync the backup files. 
If you want to manipulate or store backup files on Windows file system you will have to rename the file and remember to rename it back again when re-uploading to Nexcloud.
In order to make it possible to move the files between systems I suggest that the filenames are formatted without time separator e.g. config-xxx-2018-06-30_185500.xml or even more compact as config-xxx-20180630_185500.xml

**Comment by fabianfrz** [comment]
This is not a OPNsense bug nor a Nextcloud bug. Columns in filenames are legit characters.
Look for the different file systems in wikipedia. ":" is a legit character.

**Comment by astrandb** [comment]
No,  : is not allowed in filenames in Windows. It is used to distinguish the drive letter e.g. C:
One reference from Microsoft: https://docs.microsoft.com/en-us/windows/desktop/msi/filename

**Comment by fabianfrz** [comment]
So it is Windows issue because the underlying file system (NTFS) supports it (only `NUL` (0x00) and `/` (0x2f) are forbidden regarding to Wikipedia). For handling client OS specific issues, I see the client to be responsible to care, not a completely independent software which does not even have contact with it in that case.

**Comment by astrandb** [comment]
I respect your view, but the problem remains. backup files from OPNsense cannot be stored on Windows systems as long as they contain a colon in the name. This is not unique to OPNSense nor to Nextcloud. You will find tons of examples if you google around. The simplest way to avoid this interoperability issue is to avoid ":" in filenames.

c:myfile would ambiguous if allowed. There is no way  to decide if "c:myfile" is the filename or if it refers to "myfile" on drive c:

**Comment by fabianfrz** [comment]
`c:myfile` is also valid because it does not contain a '/' nor a '\' form the view of the FS but I guess It may be interpreted as a alternative data stream which is probably the root cause. It has no reference to a mount point which is visible as a drive letter.

you may open a ticket for the sync client if you think it should care about windows file name limitations:
https://github.com/nextcloud/desktop

**Comment by fabianfrz** [comment]
@fichtner I created a ticket in the nextcloud client repository.

**Comment by fichtner** [comment]
thanks 👍

**Comment by fabianfrz** [comment]
@astrandb 
If I remind that correctly, the syntax to install a patch from my repository is
opnsense-patch -a fabianfrz 6f2e192

This is a hotfix - it is not intended for a public release but you can use it for your instance. You will have to reapply it after an update.

**Comment by astrandb** [comment]
Thank you @fabianfrz !

**Comment by Alphakilo** [comment]
@fichtner @fabianfrz 
Why should this be a Nextcloud client issue? 

And is there a good reason to keep the colon other than "It's a valid character"?

**Comment by fabianfrz** [comment]
@Alphakilo For example if you would sync to DOS, you have a limitation of 8.3 file names (https://en.wikipedia.org/wiki/8.3_filename) but actually nobody cares. In that particular case, Windows creates the "short name" by itself so the application does not need to handle it but it is still the job of the OS or applications running on this OS to handle local file system limitations.

**Comment by astrandb** [comment]
@fabianfrz @fichtner
It is obvious that many Windows users have problems with current date string. One way to solve the situation without creating breaking changes could be to make the delimiter characters user selectable. Default should be current setup and an alternate setup with no delimiters (e.g. 201912240624 for 2019 dec 24 6:24 am).
Unfortunately I don't have the skills to develop and produce a PR.

**Comment by EagleWolfpack** [comment]
@fabianfrz : Would you please update your patch? Patching fails in Opnsense 19.7.5_5

Regards
Chris

**Comment by fabianfrz** [comment]
@EagleWolfpack can you try this commit id: 1ae454b7448288ea94347fc937eac6266519d88c

**Comment by EagleWolfpack** [comment]
@fabianfrz
Hi!
Thx, the patch works, but there is a litte mistake; You repaced "Y-m-d_H:i:s" to "Y-m-d_h-m-s" instead of "Y-m-d_H-i-s" (H to h - 12hour without AP/PM) (i to m - Month instead minutes) ;-) 

Regards
Chris

**Comment by fabianfrz** [comment]
Ok than this one: cdc9061fe9e549219ce1936676f9d54de8731cd1

**Comment by EagleWolfpack** [comment]
Sorry, but no Minutes? (missing "i" between "H--s" (should be "H-i-s")
Regards
Chris

**Comment by fabianfrz** [comment]
my mistake 4f8a361d2d45490b25302ddc966743e7f426137a - it is already late.

**Comment by EagleWolfpack** [comment]
@fabianfrz 
Perfect!
Now it's working!
Greez from Austria

Regards 
Chris

**Comment by muchahagrande** [comment]
Will this patch be permanent on following OPNSense updates?
I have to modify the PHP myself on every update

**Comment by EagleWolfpack** [comment]
Hi,

Is it possible to patch V20.1.1?

Regards
Chris

Von: Fabian Franz BSc [mailto:notifications@github.com]
Gesendet: Sonntag, 20. Oktober 2019 22:26
An: opnsense/core <core@noreply.github.com>
Cc: Eagle <office@eagle.at>; Mention <mention@noreply.github.com>
Betreff: Re: [opnsense/core] Backup file name contains colon, which is not allowed in Windows (#2498)


my mistake 4f8a361<https://github.com/opnsense/core/commit/4f8a361d2d45490b25302ddc966743e7f426137a> - it is already late.
