### ISSUE TITLE
NAT Portforwarding doesn't work

### ISSUE THREAD

**Issue by archenroot** [opnsense/core#2506]
I have fresh install of Opensense latest stable (my first try to replace pfSense) and tried to establish basic port forwarding rules:
inet client -> WAN port 31001 -> Forward to LAN IP port 22 (ssh)

I have already VPN server fully working, so I logged in via SSH over VPN and tested on server specific IP (there are 2 interfaces) if ssh is enable on that one IP I use for forward:
```
zeus /opt/nexus/nexus-oss-webapp/conf # telnet 172.29.29.105 22
Trying 172.29.29.105...
Connected to 172.29.29.105.
Escape character is '^]'.
SSH-2.0-OpenSSH_7.7
^]
telnet> quite
?Invalid command
telnet> quit
Connection closed.
```

Now here is the screenshot from forward rule settings:
![image](https://user-images.githubusercontent.com/553512/42175573-606e2fac-7e15-11e8-8d0f-7a493599b6de.png)

This created associated FW rule:
![image](https://user-images.githubusercontent.com/553512/42175588-754eb52c-7e15-11e8-872e-c9963c296dee.png)

Any idea what could be wrong with this configuration for dummies :-)))

**Comment by fichtner** [comment]
Hi there! :)

Try this: clear source port, set destination port to 31001, clear destination host


Cheers,
Franco

**Comment by archenroot** [comment]
Jesus I am stupid :dagger:

**Comment by fichtner** [comment]
no worries, you're doing fine. glad to be of help :)

**Comment by archenroot** [comment]
Of course it works, so far all works as expected except my head :-)))
