### ISSUE TITLE
No Admin-access after (failed?) update from 18.1.10 to 18.1.11

### ISSUE THREAD

**Issue by clystron** [opnsense/core#2511]
I have a pretty strange issue with a firewall that has been updated from 18.1.10 to 18.1.11. The update requires a reboot and the firewall "refused" to actually perfom it, even when trying to manually reboot it just does not react. I noticed errors in the log about groupmod for group "all" and groupadd in group "admins" failing because one of the admin-users appearantly does not exist. There are 4 admin users (uids 0,2000,2001,2002), one is local root and the other 3 are imported from LDAP, the "non existing" is the last one of those and it is also named "root". This was probably a mistake but it has been this way for years now.

The device worked as usuall but could not reboot and SSH-authentifcation for shell-access was not possible ("access denied"). After trying to modify a setting via Web-Interface the whole interface is now down (no answers to any HTTP requests) and I am no longer prompted for credentials over SSH. I have not looked at the physical console yet because I am not currently on site but I fear that I do not have access to anything there as well.

I am unsure what to do now, if the device does not perform the reboot and all admin-interfaces are inaccessible I can only reset/power-cycle it but I am not sure if it will work afterwards. If the "admins" group is actually empty now even if it boots up fine it is possible that no one has permissions to change anything.

Any suggestions on how to recover from this? Routing/Firewalling/Other services all work fine (for now).

**Comment by fichtner** [comment]
Have you tried the GUI reboot option under power?

**Comment by clystron** [comment]
Thats what I meant by "trying to manually reboot".
My main concern is that the "admins" group is probably empty now because of the "access denied" message when trying to access SSH-console....

**Comment by fichtner** [comment]
I have no good picture of what is wrong here. All user admin root access funkiness aside...

Are you able to open the GUI now?
Are you able to access the console, preferably the console menu?

**Comment by clystron** [comment]
GUI is not accessible now, as is SSH console. The TCP-Sockets are accepted but there is are no replies to HTTP GET requests or a login prompt over SSH. Before trying to change a setting the GUI was accessible but SSH console was denied. I can check the locally attached VGA monitor when I am o site in a little while.

**Comment by fichtner** [comment]
It sounds like a latent file system corruption, files missing / corrupted leading to incomplete system start. You can use a VGA image to recover with installer doing config import and reinstall to do a seamless replace.

**Comment by clystron** [comment]
So you think the failure on "groupadd" is a pure coincidence?

The failed groupadd command is '/usr/sbin/pw 'groupadd' 'admins' -g '1999' -M '0,2000,2001,2002''
it complains about user 2002 not existing.

Just to be clear, the device did not restart after the upgrade, the uptime did not change. The failed commands first appeared during the update.

**Comment by fichtner** [comment]
groupadd does not lock you out of GUI or SSH, let alone make GUI unresponsive.

2002 is your other "root" so it doesn't exist because it couldn't be created (the database is rebuilt from scratch on reboot). That's a minor issue.

I understand. A failed reboot indicates problems with the installation / download of the update. We'd need the update log to see why it didn't reboot, but I'm guessing that's not available so we have to find out some other way. :)

**Comment by clystron** [comment]
What I do have are syslog messages because the device logs to another machine. I see a whole lot of "upgraded" messages from pkg-static and then some errors about "Model OPNSense\Quagga\OSPF6 can´t be saved, skip" with "validation error". Quagga has been replaced by FRR on this machine a while ago so those could be remnants. Finally I see my two group-errors and then "upgraded: 18.1.10 -> 18.1.11".

**Comment by clystron** [comment]
BTW: Can the installer import a config from the existing installation filesystem or do I have to use a config-backup? So far I have not used that feature.

**Comment by fichtner** [comment]
Hmm, the base/kernel update doesn't log to syslog because it's not using the package manager. Ideally, these need to be rerun to catch the issue in the act:

    # opnsense-update

The installer importer takes the contents of /conf including DHCP leases, your backups, RRD files, captive portal database and Insight reporting data. It's the same system afterwards minus the logs. To be on the safe side make sure have a config.xml backup ready as well.

**Comment by clystron** [comment]
Ok, I will check the VGA console in the afternoon and if nothing works prepare for a reinstall of that machine. It has been performing its "normal" services for serveral hours now so I hope I can do it after office hours.

**Comment by clystron** [comment]
So here is what happened:
I checked the VGA console and the menu was present (the setting I changed in the GUI before it froze was to not require a password for the console) but I could not do anything. I tried Shell, Reboot, Power off and Firewall log but all the terminals just froze. So the only thing I could do was prepare for a reinstall and reset the machine. First test was to just let it boot and see what happens and after auto-correcting some issues in the filesystem (went by to fast to see) it was back up. All services are running normaly and the GUI is working and does not freeze when changing settings, I re-enabled the password protection for the console and removed the extra root user to get rid of the groupadd/mod errors and it all looks good now.

The machine is scheduled to be replaced soon so I am happy with the result and not having to reinstall.  It looks like the update completed, are there any logs I could check to maybe find out what went wrong in the first place?

**Comment by fichtner** [comment]
@clystron was there a crash report on the dashboard after the reboot that fixed it? it sounds like the kernel locked up without warning, which is rare, but not entirely unusual.

To be fully sure about the file system errors go to system: firmware: updates and do an audit for "health" and it will check all package's file checksums to be sure. it could also be indication of the disk slowly dying and may come back at any second, worst case on major upgrades because it uses more write cycles to complete.

**Comment by clystron** [comment]
There was no crash report on the dashboard.
Would a kernel lockup not affect firewalling/routing etc? The machine performed all its services without any degradation for several hours while the GUI was inaccessible and also continued to log to its syslog server.

The filesystem is on a RAID1 so I would expect it to be able to cope with some (not all of course) HDD errors. As far as I can tell both HDDs are healthy (checked SMART attributes, errors and ran selftests), thats no guarantee of course but its all I can check.

I will perform a health audit to see if anything comes up, thanks for your support!

**Comment by clystron** [comment]
Health audit reported no issues.

**Comment by fichtner** [comment]
You are right, I forgot about the part that networking kept working. Still odd that the GUI froze too, I could understand the console not responding and SSH with it, but not the GUI.

I suppose the system log could mention something related around the time of the incident... you can skim the full log form the console via:

# clog /var/log/system.log

**Comment by clystron** [comment]
There is nothing in there that I have not already seen on the syslog server, pkg-static logged updated packages and then "pkg-static: opnsense upgraded: 18.1.10 -> 18.1.11". In the same second there was also "sshlockout/webConfigurator v3.0 starting up" and "pkg-static: isc-dhcp43-client-4.3.6P1 deinstalled". 80sec later the Monit daemon was stopped (trying to reboot?). After that point the SSH console was reporting PAM auth errors but the GUI kept working until I changed the setting about password protecting the console menu. The setting was applied but I never got a result in the GUI and after that GUI was frozen, SSH was frozen and Console menu was not able to start anything.It looks like anything involving starting a new process was frozen.

Since there are no updates detected running opnsense-update as you mentioned above would probably not yield any new results either. I am pretty much out of ideas.....

**Comment by fichtner** [comment]
Maybe that is part of the key to solving this: the services tried to shut down and the system was in a state just prior to reboot with a particular daemon hanging (haproxy, squid?). I know that shutdown writes /var/run/nologin, which disables login and you won't get it back until it cleanly reboots.

**Comment by clystron** [comment]
It certainly looks that way, the only service mentioned in syslog is Monit, haproxy or squid are not enabled. The vital services IPSec/OpenVPN/FRR/DHCPD/Unbound were all still up.
I dont think it was just nologin because nologin is ignored for the user root and is not logged as PAM auth error when rejecting a login but it seems something was missing for PAM auth.

I also found that lighttpd was stopped and started at the time the update was logged as completed, then a lighttpd was stopped again 70sec later (different PID though), 10sec before monit was stopped.

Later when I changed the console-password setting causing GUI/SSH freezeup Unbound was successfully restarted.

I checked all the files in /var/log/ to get more information but there is not much there, it really looks like something went wrong in the very early stages of the reboot but it seems impossible to find out what.

**Comment by fichtner** [comment]
Alright, thanks for the additional info. Shall we close this issue then? I'm on the lookout for similar behaviour in my test environments always. Some things were fixed in 18.1.x lately regarding heightened visibility in that area, but catching all seems like a job for life but that's ok. :)

**Comment by clystron** [comment]
Fine with me, thanks again for your efforts!
