### ISSUE TITLE
CRON JOB to KILL STATES

### ISSUE THREAD

**Issue by muchahagrande** [opnsense/core#2512]
Hi,
   I need a cron job to kill some states.
   In the cron job command selection list, it would be usefull to have a "kill states" command, and in the parameter box you could enter an IP or an ALIAS to filter the list of states to kill.
   I need this to workaround a SIP problem that occurres when you have a trunk between two sites that have dynamic IP addresses.
   I do this states killing by hand but it could be automated with the very same result.
   May be this could be usefull for other cases too.

Thank you and regards...

**Comment by fichtner** [comment]
Hi @muchahagrande,

Would you try and see if the recent addition of "Dynamic state reset" works for you? (Firewall: Settings: Advanced)


Cheers,
Franco

**Comment by muchahagrande** [comment]
I forgot to mention that I have binat, so my router does not detect public IP changes.

**Comment by AdSchellevis** [comment]
timeout
