### ISSUE TITLE
[18.7.b_415] UUID when editing a monit service

### ISSUE THREAD

**Issue by sjorge** [opnsense/core#2515]
When I try and edit a monit service for it displays UUID in stead of check names. The check dropdown box also pears in the top left corner.

![monit screenshot](https://i.imgur.com/l4C3i7Z.png)

**Comment by fichtner** [comment]
CC @fbrendel

**Comment by fichtner** [comment]
was fixed by 20f41070bc1ab6aef6fe6f33dacea7e13c820398

**Comment by sjorge** [comment]
👍 yep that commit fixes it!
