### ISSUE TITLE
some IPv6 WAN issues after update to 18.1.11

### ISSUE THREAD

**Issue by mimugmail** [opnsense/core#2516]
Read here about some issues after 18.1.11, since there are already 3 different ppl I thought to put here an issue. One of them explained some more facts so perhaps you already see whats wrong.

https://www.reddit.com/r/OPNsenseFirewall/comments/8w1gx0/no_ipv6_access_to_internet_from_clients_after/

**Comment by fichtner** [comment]
18.1.6 to 18.1.11 is too broad. We need the exact version change. And I don't think kernel or base updates did this. The timing may be purely coincidental with the update, which tends to happen with these obscure problems for reasons outside of our control or just a simple setup quirk. Not trying to fend this off, but I trust the forum and twitter users to report issues like this as well in a very timely and angry mob fashion so this is merely managing expectations :)

**Comment by mimugmail** [comment]
FYI

https://www.reddit.com/r/OPNsenseFirewall/comments/8w1gx0/no_ipv6_access_to_internet_from_clients_after/e1tkxkm/
