### ISSUE TITLE
Knob for vlanhwfilter disable in system settings

### ISSUE THREAD

**Issue by fichtner** [opnsense/core#252]
via: https://forum.opnsense.org/index.php?topic=896.0

**Comment by AdSchellevis** [comment]
Is this what your looking for https://github.com/opnsense/core/commit/2a3a6a1de88110a11f070badd451fad5928a0750 ? 

An option to set all technical parameters for an interface is probably not the best thing to do in the legacy code, maybe more something for the wishlist for future releases? (to prevent too much changes in legacy code and possible transition problems between versions).

**Comment by fichtner** [comment]
This is exactly the amount of code needed for this to be solved short-term. So, yes, Long-term the interfaces in the new GUI need a better system. :)

As for the patch: yes, thank you, almost. There separate hardware code that sets vlanhwfilter unconditionally on a vlan though: https://github.com/opnsense/core/blob/2a3a6a1de88110a11f070badd451fad5928a0750/src/etc/inc/interfaces.inc#L266

**Comment by AdSchellevis** [comment]
No problem, will look at that in an hour or so.

**Comment by fichtner** [comment]
Awesome, thank you. :D

**Comment by AdSchellevis** [comment]
Your welcome. 
I guess it makes most sense to disable all hw options when hwfilter is disabled. 
Commit https://github.com/opnsense/core/commit/cd41d6b95cbfaf6f9b311fd9650a58662a98740f contains the fix.

**Comment by fichtner** [comment]
I tried to backport these changes, but for some reason it doesn't work. It seems to be a larger issue. I can't even unset the tags in ifconfig, at least for the e1000 driver I've tested so far.
