### ISSUE TITLE
MVC: create templated files?

### ISSUE THREAD

**Issue by mimugmail** [opnsense/core#2520]
Hi,

for plugins I know the process to template the content of a file and name via TARGETS.
For a BIND plugin I'd need to create a file for every zone created in a dialog. 
Is there already a way to do this? I not seen something similar within the new codebase.

**Comment by fichtner** [comment]
Something like this?

https://github.com/opnsense/core/blob/master/src/opnsense/service/templates/OPNsense/Sample/%2BTARGETS#L1

**Comment by mimugmail** [comment]
Hm, I dont get it, perhaps I have to test in with real data. Be sure that I'll ping you in IRC next week :D
