### ISSUE TITLE
[6rd][stf] not able to connect through swisscom

### ISSUE THREAD

**Issue by RyuunoAelia** [opnsense/core#2521]
As discussed in #1501 I open a new issue.

I get the wan_stf interface, everything seems configured correctly but I when I run packet capture on internet facing interface no packets goes to the 6rd border gateway and I get "Network is Down" errors when trying to ping any ipv6 adress including the border router.

Nothing wrong in dmesg.

```
# uname -a
FreeBSD XXXXXXXXX 11.1-RELEASE-p11 FreeBSD 11.1-RELEASE-p11  2bab086d417(stf)  amd64
```

```
# ifconfig wan_stf
wan_stf: flags=4041<UP,RUNNING,LINK2> metric 0 mtu 1280
	inet6 2a02:120X:XXXX:XXXX:: prefixlen 60 
	nd6 options=1<PERFORMNUD>
	v4net 0.0.0.0/32 -> tv4br 193.5.29.1
	groups: stf 
```

The prefix is 2a02::1200/28 and border gateway is the ip resolved by name 6rd.swisscom.com the complete ipv4 is embedded into the ipv6 address

I am pretty confident about the 6rd parameters I did find recent reports that show it works on pfsense with the settings I use: https://community.swisscom.ch/t5/Internet/IPv6-Webseiten-nicht-mehr-abrufbar/td-p/485992 (in german). Though the specific version of pfsense is not specified (still I hope they are not using pfsense 2.1 in March 2017...). So it should still work.

```
# netstat -r -n
Routing tables

Internet:
Destination        Gateway            Flags     Netif Expire
default            Y.Y.Y.1         UGS         re0
X.X.X.0/23      link#1             U           re0
X.X.X.X       link#1             UHS         lo0
[...]
193.5.29.1         Y.Y.Y.1         UGHS        re0

Internet6:
Destination                       Gateway                       Flags     Netif Expire
default                           2a02:120X:XXXX:XXXX::c105:1d01 UGS    wan_stf
::1                               link#5                        UH          lo0
2a02:120X:XXXX:XXXX::             link#11                       UHS         lo0
2a02:120X:XXXX:XXXX::/60          link#11                       U       wan_stf
[...]
```

```
# ping6 google.com
PING6(56=40+8+8 bytes) 2a02:120X:XXXX:XXXX:: --> 2a00:1450:400a:801::200e
ping6: sendmsg: Network is down
ping6: wrote google.com 16 chars, ret=-1
[...]
```

Thus I am curious about what stf debug will say. However the debug for stf is a compile-time setting enabled via C preprocessor. I could build the code myself if you give me some pointers. I am not familiar with FreeBSD/opnsense build/packaging system however I am a C/Linux guru.

**Comment by RyuunoAelia** [comment]
Ok, I managed to build a kernel and installing it. I don't have error message when ifconfig sets the ipv6 adress for my 6rd setup, but I forgot I need a patched ifconfig (I reverted to the Production line after my first test failed).
I will build base (since it doesn't seem possible to build only ifconfig) and continue testing things.

**Comment by RyuunoAelia** [comment]
well I finally used your update repo from #1501  with my kernel and I got everything configured correctly. however even after patching the if_stf.c file with #define STF_DEBUG 4 I still get no debug in dmesg... I even built a "debug" kernel. Don't know if I am doing something wrong or if my problem comes from somewhere else and doesn't even reach the kernel module code ...

**Comment by RyuunoAelia** [comment]
Ok there's an annoying sysctl thingy. I will remove this check and enable the debugging always...

**Comment by RyuunoAelia** [comment]
Wow... I guess this is not normal:

```
stf_getin4addr: enter.
stf_getin4addr: addr6 = 2a02:120X:XXXX:XXX0::
residue = 4 0xf
stf_getin4addr: in->in_addr = 0.0.0.0
```
From what I understood of my reading stf_getin4addr should extract the ipv4 address from the ipv6 one. In this case the addr6 is my local ipv6 (I already find that weird) and the ipv4 is 0.0.0.0 (even weirder). And I get that bunch of messages for every single ping request send to google.com

**Comment by RyuunoAelia** [comment]
Yep after adding more debug I was right.

```
stf_output: enter
stf_getsrcifa6: enter
stf_getin4addr: enter.
stf_getin4addr: addr6 = 2a02:1205:506e:b8b0::
residue = 4 0xf
stf_getin4addr: in->in_addr = 0.0.0.0
stf_output: ipv4 embedded in ipv6 packet is not local.
```

The module parses my local ipv6 address to get the src ipv4 for outgoing packet. When 0.0.0.0 is received it just stops there to avoid sending garbage it expects a local ipv4.
I expect my setup is special when compared to the others that tested it. Swisscom having a /28 prefix might be the cause I do not know the other setups.

**Comment by RyuunoAelia** [comment]
The more I dig into the patch to stf the less I understand its logic. Argument naming is an unhelpful mess, lack of comments makes it hard to understand what is expected of functions and the sheer number of variables makes it virtually untraceable.
The best example of that is "stf_getin4addr" which *should* be a function to extract the ipv4 address from an ipv6 address. (the exact one that returns 0.0.0.0 in my case).
Here is a list of all variables + parameters in context during the copy of the ipv4 from the ipv6:
* struct stf_softc *sc
* struct sockaddr_in *sin
* struct in6_addr addr6
* struct in6_addr mask6
* struct in_addr *in
* struct in6_addr buf
* u_char *p
* u_char *q
* u_int residue
* u_int v4residue
* u_char mask
* u_char v4mask
* int i
* int j
* u_int plen
* u_int loop

Not all are used in that part of the function, but most of them are and there is no comment about what they are used for you have to guess sometimes using how they are initialized, sometimes using how they are used... There is no indication of which parameter of a function is input or output, you have to guess, and the code miodifies some internal context all the time even in some "search" functions. I have no idea what side-effects this has.

**Comment by fichtner** [comment]
I'm beginning to see what you say, stf_getin4addr() has an actual issue. The good thing is ifconfig can be used to verify this as it prints 0.0.0.0/32 which is what happens internally too.

**Comment by RyuunoAelia** [comment]
If we follow what the linux patch does, it becomes much easier to extract the ipv4 from the ipv6 and much less error prone.
Actually use 2 consecutive 32bit chunks of the struct in6_addr pass them through ntohl() and do bit shift to get the 32bits of full ipv4 address. Then use a mask to keep only the ipv4 prefix and pass the result in hlton().
This solution would be faster in compute time, much less code, and easier to understand to boot.

**Comment by fichtner** [comment]
I found a small thing... 6df682c, apply using:

    # opnsense-patch 6df682c

pfSense does this too nowadays. But what I don't understand is that both /0 and /32 do the same thing as /32 but 32 bits is not allowed in the GUI?

Also you said "prefix 2a02::1200/28" but shouldn't that be "2a02:1200::/28" ?

**Comment by RyuunoAelia** [comment]
Yes you are correct. I messed up my message for the "2a02::1200/28", the ifconfig output is correct if you look at it.

Also I actually detected this confusion between 0 and 32 in the kernel patch and this is actually dangerous since the RFC does not limit the values of the ipv4 prefix, so 0 is actually a valid prefix acording to the RFC which means there is only a single customer per SP ipv6 prefix. weird but allowed by the spec.

I will test the patch as soon as I have a window to reboot on my custom patched kernel with extra debug.

**Comment by fichtner** [comment]
I'm fixing some more in the GUI / configuration code to support 0 - 32 bits, right now the only thing that worries me is that the kernel assumes /0 and /32 is the same.

**Comment by fichtner** [comment]
Second part via 83f8321b, to apply both patches:

    # opnsense-patch 6df682c 83f8321b

I'll look into the kernel now :)

**Comment by RyuunoAelia** [comment]
YEAH! with both patches applied I managed to make my configuration work. I can ping6 google.com now.

However, only if I set the prefix length to 0 with 32 ifconfig output is identitcal but I cannot ping6 google the icmp reply is never received.

**Comment by fichtner** [comment]
Ok, here comes the kernel...

# opnsense-update -kr 18.7.r-stf2 -n "snapshots\/dummy"

Don't forget to reboot. It won't show /0 because that is in ifconfig to fix too (via base update later on).


Cheers,
Franco

**Comment by RyuunoAelia** [comment]
I installed your kernel
# uname -a
FreeBSD pfsense.idm.aelia.ch 11.1-RELEASE-p11 FreeBSD 11.1-RELEASE-p11  bdf43282b19(master)  amd64

Same behaviour as with my extra debug-patched kernel. I can ping6 google.com only when I set the ipv4 prefix to 0. Even my full debug was not showing any reason when set to 32. So probably the encapsulation was wrong somewhere with 32bit of ipv4 prefix. With prefix of length 0 I had my debug identical than with 32 except it did show a call to stf_encapcheck with 0 and not with 32.

Though I cannot find where this function was called from...

**Comment by RyuunoAelia** [comment]
Oh the stf_encapcheck is a callback set when the virtual interface is created.

**Comment by fichtner** [comment]
encap4_input() calls this function via ep->func

**Comment by RyuunoAelia** [comment]
so I can probably tcpdump when I set the ipv4 prefix length to 32 ans see if something goes out. Will try.

**Comment by fichtner** [comment]
Sorry, there's also encap6_input(). I think the packet goes out but doesn't come back (into the network stack on the host). Could that be true?

**Comment by RyuunoAelia** [comment]
Ok after some tcpdump (and after that realizing that actually ifconfig shows pretty clearly what happens) I know what is happening. Actually the kernel is doing exactly what I tell it to do, but the web interface naming for the parameter is wrong.

The parameter should not be "ipv4 prefix length" but the "number of bits to drop at the end of the ipv4" address. So if I set 32 it drops the entire ipv4 from the ipv6 and my local ipv6 address becomes 2a02:1200:: while if I put 0, the full ipv4 is appended to the SP ipv6 prefix. I tried with 12 to check and it is as expected.

**Comment by fichtner** [comment]
What do you think, should the resulting prefix be parent prefix + ipv4 prefix bits?

**Comment by RyuunoAelia** [comment]
To be clear (since I am not sure if I understand what you ask).

If the SP prefix is 2a02:1200::/28 and my ipv4 ip address fully embedded into the ipv6 adress so 32 bit. You have to add 28+32 to get the subnet length which makes a /60 delegated.

The RFC5969 actually defined the 6rd parameters as they currently are taken by the kernel module. (sorry I made an error in my previous statement, the parameter is the number of HIGH order bits to drop from the IPv4 address and is exactly that and they call it IPv4MaskLen).

**Comment by RyuunoAelia** [comment]
For now it works for me so I will stop looking into it for today. Maybe you should check if it really works correctly for a bunch of different parameters (ifconfig shows the delegated prefix but not the size of the delegated subnet, only the length of the SP ipv6 subnet so 28 for me).

**Comment by fichtner** [comment]
@RyuunoAelia To answer the question myself maybe: so I made a small error in bc378402b5 but then realised that this previous code wasn't even correct and c6034f651cd27 makes the most sense to me. What do you think?

**Comment by RyuunoAelia** [comment]
Well, if you take into consideration what the help text in the interface says "The value in this field is the 6RD IPv4 prefix length. Normally specified by the ISP. A value of 0 means we embed the entire IPv4 address in the 6RD prefix." you might be right. But still it doesn't explain why the full IPv4 address is 0...

**Comment by fichtner** [comment]
> But still it doesn't explain why the full IPv4 address is 0...

Now or before?

**Comment by RyuunoAelia** [comment]
I admit I am a bit lost as to what patches I should apply. I am still with your two very first commits:
opnsense-patch 6df682c 83f8321b

And at that point passing 0 in the interface (which means passing directly 0 to ifconfig if I read it correctly) works for me, and matches the help text somehow. Passing 32 does not work at all. But If I set 12, the wan_stf interface still shows a prefixlen of 28. So I need to tcpdump the traffic to check things.

With your modification of 32 - interface number. I would have to set 32 in the interface to make it work (which seems more natural). Tough I am still not confident this will work as expected for every setup.

**Comment by fichtner** [comment]
Not so worried about changing the game here with regard to input values from tutorials if we can match the labels the code and the result to what is expected.

You can apply the other two as well:

opnsense-patch bc37840 c6034f6

**Comment by RyuunoAelia** [comment]
Ok with your two additionnal patches I now get a completely different result than before.
Setting 0 in the WebUI I get:
```
# ifconfig wan_stf
wan_stf: flags=4041<UP,RUNNING,LINK2> metric 0 mtu 1280
	inet6 2a02:120X:XXXX:XXX0:: prefixlen 60 
	nd6 options=1<PERFORMNUD>
	v4net X.X.X.X/32 -> tv4br 193.5.29.1
	groups: stf
# netstat -nr
Routing tables
[...]
Destination                       Gateway                       Flags     Netif Expire
default                           2a02:120X:XXXX:XXX0::c105:1d01 UGS    wan_stf
::1                               link#5                        UH          lo0
2a02:120X:XXXX:XXX0::             link#11                       UHS         lo0
2a02:120X:XXXX:XXX0::/60          link#11                       U       wan_stf

# ping6 google.com
PING6(56=40+8+8 bytes) 2a02:120X:XXXX:XXX0:: --> 2a00:1450:400a:801::200e
16 bytes from 2a00:1450:400a:801::200e, icmp_seq=0 hlim=56 time=5.337 ms
```
So exactly what I expected to be a completely correct setup... With correct prefixlen in ifconfig and correct routes for my delegated ipv6 prefix.

Setting 32 in the WebUI, I get:
```
# ifconfig wan_stf
wan_stf: flags=4041<UP,RUNNING,LINK2> metric 0 mtu 1280
	inet6 2a02:1200:: prefixlen 28 
	nd6 options=1<PERFORMNUD>
	v4net X.X.X.X/32 -> tv4br 193.5.29.1
	groups: stf
# netstat -nr
Routing tables
[...]
Internet6:
Destination                       Gateway                       Flags     Netif Expire
default                           2a02:1200::c105:1d01          UGS     wan_stf
::1                               link#5                        UH          lo0
2a02:1200::                       link#11                       UHS         lo0
2a02:1200::/28                    link#11                       U       wan_stf

# ping6 google.com
PING6(56=40+8+8 bytes) 2a02:1200:: --> 2a00:1450:400a:801::200e
```
And obviously this doesn't work since my ipv4 is not embedded into the delegated ipv6.

**Comment by fichtner** [comment]
Yep, that's what the code has always been doing. The only thing that changed is that the prefixlen calculation is now tied to the number of IP4 bits that are folded into the IPv6 prefix. If you set it to 8, 16, 24 you can see the prefixlen decrease and the prefix with it. This wasn't the case before.

I'm not sure if a prefix length of 32 makes sense now or if "0" was always used the wrong way. At least "0" does what the help text says and when you start increasing it you lose prefix bits on your ISP all the way up to the final 32 which means no bits are folded into the preifx which gets you your ISPs 2a02:1200::/28.

Shall we wrap this up then?

**Comment by fichtner** [comment]
Thanks. Down the line we may try to work up the kernel side, but for now let's set a base line and get 6RD users on board who will be able to test and confirm future kernel changes. Thank you for all your help and insight!
