### ISSUE TITLE
Unable to ping OPNsense as guest from host machine

### ISSUE THREAD

**Issue by reza-ebrahimi** [opnsense/core#2523]
I've a fresh install of OPNsense inside Virtualbox, so I cannot ping OPNsense guest machine from host, I've tested from both Windows and Ubuntu host and cannot work, I have tested both host only networking and bridged networking with no success, is there any config to change? I'm also trying to disable OPNsense firewall but cannot find any useful information about that, any help is appreciated.

**Comment by fabianfrz** [comment]
This are the settings of my dev machine (and I know that they are working):

Adapter 2 and 3:
![screenshot_20180708_081825](https://user-images.githubusercontent.com/3713914/42417320-7ea94738-8287-11e8-8743-75d8eef10921.png)
Adapter 1:
![screenshot_20180708_081923](https://user-images.githubusercontent.com/3713914/42417331-a110c9ae-8287-11e8-8f98-4a10c2c65af4.png)

**Comment by fabianfrz** [comment]
before i forget it - I have also configured a network manager connection matching the settings of OPNsense. Maybe your host is in a different network.

**Comment by reza-ebrahimi** [comment]
@fabianfrz Thanks a lot, The trick is disabling firewall with `pfctl -d`, with disabling firewall all ICMP packets are allowed to OPNsense machine.
