### ISSUE TITLE
some UI improvements (papercut)

### ISSUE THREAD

**Issue by labor4** [opnsense/core#2524]
some UI improvements

- I think its not informative that a non-enabled interface is shown in graphs.
- Menu "Interfaces": Idea to group VLAN intf under their respective parent interfaces, maybe like the "Services" Menu.
- Menu "Interfaces": Also work with padding/spaces for "the interfaces"->following->"Assignments" (and maybe others too). make groups.
- OpenVPN interfaces are sometimes displayed as Ovpn1-X even though the other interfaces in list inherit their "display-name"

don't wanna bug you with non-important stuff, but i had just the right temperature...
;-)
best wishes
m

**Comment by AdSchellevis** [comment]
timeout
