### ISSUE TITLE
Backup filename on Nextcloud is not optimal

### ISSUE THREAD

**Issue by astrandb** [opnsense/core#2527]
I think there is a slight mistake in the naming of backup files in Nextcloud.php.
Current date format string for the backup filename on Nextcloud is:

`date("Y-m-d_h-m-s")`. 

A better format would be: 
`date("Y-m-d_H-i-s")`.

**Comment by fabianfrz** [comment]
@astrandb you can test the fix if you like - it should work (thanks for reporting the bug).

**Comment by fabianfrz** [comment]
you may run "opnsense-patch 4b1dd40" to apply it
