### ISSUE TITLE
JS issues with Tokenizer and NetworkField with Fieldseparator

### ISSUE THREAD

**Issue by mimugmail** [opnsense/core#2528]
For the net-snmp plugin I use for IP listener the NetworkField and a Fieldseparator to allow multiple ones. It seems to work fine and values get in config. But when I go elsewhere and click again on the menu the fields are empty and thow a JS error. 

At first I thought it was related cause of jumping from stable to master and back. But I did a fresh install and tried a clean browser, doesn't help.

https://snag.gy/GaINZk.jpg

Normally the field should allow inputs .. perhaps I mixed something? This is form and model:

https://github.com/mimugmail/plugins/blob/bind/net-mgmt/net-snmp/src/opnsense/mvc/app/controllers/OPNsense/Netsnmp/forms/general.xml#L27-L32

https://github.com/mimugmail/plugins/blob/bind/net-mgmt/net-snmp/src/opnsense/mvc/app/models/OPNsense/Netsnmp/General.xml#L22-L25

Thanks!

**Comment by AdSchellevis** [comment]
@mimugmail you probably miss the "AsList" operator, like https://github.com/opnsense/core/blob/062ad3f82ce5b1146a3d9aae7fa8ca72858ea1e3/src/opnsense/mvc/app/models/OPNsense/IDS/IDS.xml#L126

**Comment by mimugmail** [comment]
This is probably the 15th plugin and there's always something new to learn :)
Thanks for this one! 👍
