### ISSUE TITLE
OpenVPN config generator is handling /31 tunnel networks incorrectly

### ISSUE THREAD

**Issue by dmbaturin** [opnsense/core#2529]
As [RFC3021](https://tools.ietf.org/html/rfc3021) says, "In a point-to-point link with a 31-bit subnet mask, the two addresses above MUST be interpreted as host addresses." 
Right now, if you use a /31 network for the tunnel subnet, it ignores this special case, and treats the first address as a network address, thus running over the intended range, and producing non-RFC compliant and counterintuitive results.

Since OpenVPN interfaces are inherently point to point, and it makes perfect sense to use point to point network for them rather than waste /30's on them, this is quite annoying.

Reproducing steps:

1. Create an OpenVPN client interface
2. Enter a /31 prefix in the "Tunnel network" option, e.g. 10.0.0.4/31
3. Expected ifconfig statement as per RFC3021 and the "first address is the server address" logic is "ifconfig 10.0.0.5 10.0.0.4".
4. Look into the /var/etc/openvpn/client$num.conf file: the actual result is "ifconfig 10.0.0.6 10.0.0.5"

A pull request will follow shortly.

**Comment by fichtner** [comment]
I'm removing this from the stable branches since this is just the smaller half of the actual change.

**Comment by fichtner** [comment]
@dmbaturin thanks for the fix. In general, doesn't this also mean a tunnel network of /32 should not be accepted on the server side since we can't fix two IPs ?

**Comment by dmbaturin** [comment]
@fichtner Indeed. I've created a separate issue (#2536) for that since it's, well, a separate issue. :)
