### ISSUE TITLE
kill service-utils.inc

### ISSUE THREAD

**Issue by fichtner** [opnsense/core#253]
Code can move to services.inc, only included in very few places.

**Comment by AdSchellevis** [comment]
fixed in https://github.com/opnsense/core/commit/eacbc8abac4c01be7d14d51bcd911d501113bf2e, shared into services.inc and the rest into origin of usage. same strategy as the rest of the current cleanups.

**Comment by fichtner** [comment]
Thanks. We should be careful not to remove copyright notices when code moves and the original file is killed. They must also move to the new home, unless authors are already stated in the new file.

**Comment by AdSchellevis** [comment]
You are right, I try to keep track of them, but I missed one. Fixed in the next commit.

**Comment by AdSchellevis** [comment]
You are right, I try to keep track of them, but I missed one. Fixed in the next commit.
