### ISSUE TITLE
Site to site OpenVPN (p2p/shared key) allow /32 tunnel networks

### ISSUE THREAD

**Issue by dmbaturin** [opnsense/core#2536]
Mentioned in #2529 

I thought this case is handled somewhere, but I've just tried and indeed it accepts it, then openvpn_get_interface_ip() blindly generates a pair of addresses from it.

I can take it up if you tell me where is the code where validation should occur.

**Comment by fichtner** [comment]
the code to fix here is the validation for tunnel networks in the vpn_openvpn_server.php page during saving a server instance. the code folds back to openvpn.inc but I would like to mention the flow of the data here. The goal is to prevent accepting a faulty tunnel network in the first place, not refusing to generate a config later on which would lead to dysfunctional OpenVPN service or user scratching their heads why their accepted instance isn't running as expected. :)

**Comment by fichtner** [comment]
399d719edebcdc7cbe582e73357dab2ea785c362 should do the trick

**Comment by dmbaturin** [comment]
Looks good, thanks!

**Comment by fichtner** [comment]
Okay, closing, thanks!
