### ISSUE TITLE
Can't get 6RD to work with Tweak NL

### ISSUE THREAD

**Issue by diekgait** [opnsense/core#2537]
I was following  #1501 and am trying to get 6RD working with TweakNL. A capture of the DHCPv4 ack gives me these details:
![image](https://user-images.githubusercontent.com/26073060/42570464-3fd5d262-8514-11e8-9597-ff2e9143514b.png)
Which I have configured:
![image](https://user-images.githubusercontent.com/26073060/42570499-61bcb36e-8514-11e8-8be5-8bfeea0c014e.png)

As you can see below no default route is installed.

```
root@firewall:/var/log # uname -a
FreeBSD firewall.diekgait.nl 11.1-RELEASE-p11 FreeBSD 11.1-RELEASE-p11  116e406d37f(stable/18.1)  amd64
```

```
root@firewall:/var/log # ifconfig wan_stf
wan_stf: flags=4000<LINK2> metric 0 mtu 1280
        nd6 options=21<PERFORMNUD,AUTO_LINKLOCAL>
        groups: stf
```

```
root@firewall:/var/log # netstat -6rn
Routing tables

Internet6:
Destination                       Gateway                       Flags     Netif Expire
::1                               link#4                        UH          lo0
fe80::%em0/64                     link#2                        U           em0
fe80::21b:21ff:fe90:3b22%em0      link#2                        UHS         lo0
fe80::%em1/64                     link#3                        U           em1
fe80::21b:21ff:fe90:3b23%em1      link#3                        UHS         lo0
fe80::%lo0/64                     link#4                        U           lo0
fe80::1%lo0                       link#4                        UHS         lo0
fe80::6ef0:49ff:fede:8ece%ovpns1  link#8                        UHS         lo0
fe80::%em0_vlan50/64              link#9                        U      em0_vlan
fe80::21b:21ff:fe90:3b22%em0_vlan50 link#9                      UHS         lo0
```
What else can I check?

**Comment by diekgait** [comment]
Thanks for the quick reply, I have installed the kernel and the patches:
```
root@firewall:~ # uname -a
FreeBSD firewall.diekgait.nl 11.1-RELEASE-p11 FreeBSD 11.1-RELEASE-p11  bdf43282b19(master)  amd64

```
And the interface is looking good:
```
wan_stf: flags=4041<UP,RUNNING,LINK2> metric 0 mtu 1280
        inet6 2a02:58:c9:8100:: prefixlen 56
        nd6 options=1<PERFORMNUD>
        groups: stf

```
Also when I send a ping from an IPV6 source to 2a02:58:c9:8100:: I can see the packets comming in from the 6RD Border Relay:
```
root@firewall:~ # tcpdump -i em1 host 217.19.16.16
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on em1, link-type EN10MB (Ethernet), capture size 262144 bytes
16:29:30.294579 IP 217.19.16.16 > 84-245-9-129.dsl.cambrium.nl: IP6 diekgait-1-pt.tunnel.tserv18.fra1.ipv6.he.net > 2a02:58:c9:8100::: ICMP6, echo request, seq 1, length 64

```
However it does not reply and when I try a ping from the firewall I get:

```
root@firewall:~ # ping6 google.com
PING6(56=40+8+8 bytes) 2a02:58:c9:8100:: --> 2a00:1450:400e:807::200e
ping6: sendmsg: Network is down
ping6: wrote google.com 16 chars, ret=-1

```

**Comment by fichtner** [comment]
I think you may have installed the kernel but skipped the base update that is required for ifconfig to send the 6RD options.

    # opnsense-update -vb

This says 18.1.11, or?

**Comment by diekgait** [comment]
```
root@firewall:~ # opnsense-update -vb
18.1.11-amd64

```

**Comment by fichtner** [comment]
Okay, right, you need this too...

    # opnsense-update -br 18.7-stftest -n "snapshots\/dummy"
    # /usr/local/etc/rc.reboot


Cheers,
Franco

**Comment by diekgait** [comment]
That gives me no prefix on the interface and no route:
```
root@firewall:~ # ifconfig wan_stf
wan_stf: flags=4000<LINK2> metric 0 mtu 1280
        nd6 options=21<PERFORMNUD,AUTO_LINKLOCAL>
        groups: stf
root@firewall:~ # netstat -rn6
Routing tables

Internet6:
Destination                       Gateway                       Flags     Netif Expire
::1                               link#4                        UH          lo0
fe80::%em0/64                     link#2                        U           em0
fe80::21b:21ff:fe90:3b22%em0      link#2                        UHS         lo0
fe80::%em1/64                     link#3                        U           em1
fe80::21b:21ff:fe90:3b23%em1      link#3                        UHS         lo0
fe80::%lo0/64                     link#4                        U           lo0
fe80::1%lo0                       link#4                        UHS         lo0
fe80::6ef0:49ff:fede:8ece%ovpns1  link#8                        UHS         lo0
fe80::%em0_vlan50/64              link#9                        U      em0_vlan
fe80::21b:21ff:fe90:3b22%em0_vlan50 link#9                      UHS         lo0
                 link#4                        UH          lo0
fe80::%em0/64                     link#2                        U           em0
fe80::21b:21ff:fe90:3b22%em0      link#2                        UHS         lo0
fe80::%em1/64                     link#3                        U           em1
fe80::21b:21ff:fe90:3b23%em1      link#3                        UHS         lo0
fe80::%lo0/64                     link#4                        U           lo0
fe80::1%lo0                       link#4                        UHS         lo0
fe80::6ef0:49ff:fede:8ece%ovpns1  link#8                        UHS         lo0
fe80::%em0_vlan50/64              link#9                        U      em0_vlan
fe80::21b:21ff:fe90:3b22%em0_vlan50 link#9                      UHS         lo0

```

I've disabled 6rd and reconfigured it but that makes no difference.

**Comment by fichtner** [comment]
The ifconfig output suggest you still have the wrong ifconfig binary. :( You could also try the 18.7-RC1 image. Things are a bit confusing at the moment. Lots of different states that will sync up in the final 18.7.... almost there though... end of July.

**Comment by diekgait** [comment]
Cheers again! Installing 18.7-RC1 does the trick, after that I'm able to reach google. There are still some issues though:
When I configure the lan interface as a tracker interface it picks the first /64 from my customer prefix. This /64 contains the default router and therefor all ipv6 connectivity breaks.

I've now configured it staticly with the 2nd /64 from my prefix. And this works if I staticly configure my client because for some reason radvd won't start so no router advertisements are being sent out.

**Comment by fichtner** [comment]
If you are tracking WAN from LAN, change its IPv6 Prefix ID from 0 to something else so the first prefix isn't used by LAN :)

**Comment by diekgait** [comment]
That makes sense :) RA's are working now when I set it to tracking. If with 6RD the first /64 can never be used it might be a good idea to default the prefix-id to 1? What also would be nice is to add an auto option to the 6rd configuration so it takes the configuration from v4 dhcp option 212. Is that already on the feature request list?

**Comment by fichtner** [comment]
Historically, Prefix 0 is ok, because sometimes the PD is /64 so you only have one in the first place. I wanted to improve this a bit because of you have two LANs the second one is set to 0 as well so that's a bit iffy.

Let's close this ticket and you can create a new one with the dhcp request and also mention the prefix id oddity there? I didn't know DHCP can advertise 6RD. It's certainly handy to get the values directly from the request but I'm unsure how much work it is to auto-configure using it so we'll have to discuss and see. Ok?
