### ISSUE TITLE
[NPTv6] Rules are generated for physical device when 6RD is configured (probably with ipv6 tunneling in general)

### ISSUE THREAD

**Issue by RyuunoAelia** [opnsense/core#2538]
I tried enabling NPTv6 so that my internal network does not change IPv6 subnet all the time when my 6RD prefix changes, and while debugging I nearly got it to work (at least ping goes to google and comes back up to the firewall).

What I diagnosed is that the binat rules are generated for the physical device instead of the wan_stf tunnel. So the rules cannot match the ipv4-encapsulated ipv6 address.

In /tmp/rules.debug I get:
```
binat on re0 from fdb9:86fc:f74d:1945::/64 to any -> 2a02:120X:XXXX:XXXX::/64
binat on re0 from 2a02:120X:XXXX:XXXX::/64 to any -> fdb9:86fc:f74d:1945::/64
```

Changing to:
```
binat on wan_stf from fdbY:YYYY:YYYY:YYYY::/64 to any -> 2a02:120X:XXXX:XXXX::/64
binat on wan_stf from 2a02:120X:XXXX:XXXX::/64 to any -> fdbY:YYYY:YYYY:YYYY::/64
```
For debugging I applied using `pfctl -f /tmp/rules.debug` after the above change.

After applying I can tcpdump the physical interface and actually get the ping request and ping reply send from my IPv6 ULA translated correctly to the public IPv6 going to google.com and coming back with the public IPv6.
There is probably another set of rules with a similar problem or I am missing something in my config to have the ping reply forwarded to my host in the private network.

**Comment by RyuunoAelia** [comment]
Ok after digging a bit, I found out how to make everything work. And in that case the management of the firewall and interface by opnsense gets in the way more than it helps.

I found out that the second rule generated that transform 2a02::120X:XXXX:XXX::/64 to my ULA is unneeded, since the name of the rule says it all "Bi-directional NAT".

Then I need to put an IPv6 in my public prefix (note that the public prefix must not be the "main" one used for the 6rd tunnel or else pfsense cannot use ipv6 connectivity anymore) on an interface on the router. Without this tweak the packets arriving on the wan_stf interface are dropped (before actually performing the NAT) because they would be forwarded on the same interface according to routing rules. I don't know if it is a generic case, or specific to 6rd but this makes the setup of NPTv6 completely manual since the interface does not seem to allow me to put 2 ipv6 addresses on the interface. Also  RADV is automagically configured for the public prefix if I ask opnsense to track the public interface, which makes it even more painful.

The steps to make NPTv6 work in the current state are, If my public prefix changes, I need to:
* change the configuration in the UI (at that point this is only informational since everything done by the webUI logic will be undone manually)
* change the PF rules: drop the rule "public -> ULA", rule and assign the rule "ULA -> public" to the wan_stf interface
* re-assign a public ipv6 (remove the old prefix, and set the new prefix) on the local network interface (one that matches the ULA assigned the interface to actually have NPTv6 do its job correctly)

At that point I have a perfectly working NPTv6 setup.

**Comment by RyuunoAelia** [comment]
I found a "workaround" the wrong interface for the NPTv4 rules, by creating a new interface in the WebUI for the wan_stf, I name it 00STFTUNNEL (so that it is alphabetically before the interface that sets up 6rd; though I am not sure it is mandatory), I enable it but set None to IP and IPv6 configurations.
Then I set the NTPv6 rules to that new interface. However after that, you must not touch the stf interface from the WebUI, that would make you lose ipv6 connectivity. If you really need to touch the interface, you must reload the internet connection that sets up 6rd, too.
I still cannot find how to get two IPv6 addresses on a single interface. That would be the ULA and the "tracking" of the public prefix, though I would prefer no automatic RADV (to manually select which hosts have access to ipv6 connectivity manually, without having my WiFi AP getting a publicly routable ip adress during my firewall-less testing...).

**Comment by RyuunoAelia** [comment]
Ah I found  #2314 just now, which will help with my RADV issue.
So I am missing 2 things now:
* automatic NPTv6 rule generation
* setting the ULA along with track6 on a single interface.

So maybe I will lbe opening 2 other issues if they do not exist already and keep this issue for the Interface mixup.

**Comment by RyuunoAelia** [comment]
Well that would be helpful, and kind of what I expect for a perfectly working NPTv6 setup. Note that I also opened #2544 for the NPTv6 prefix thing to avoid mixing the two issues that are not really directly linked.

**Comment by fichtner** [comment]
@RyuunoAelia looks good from here but please double-check anyway:

    # opnsense-patch 80b9a81


Thanks,
Franco

**Comment by RyuunoAelia** [comment]
Oh you closed this issue. Hmm this one was tracking the "latch on to wan_stf for you automatically" part of the issue.

**Comment by RyuunoAelia** [comment]
ah my refresh did not show your patch sorry.

**Comment by RyuunoAelia** [comment]
Yes it works without issue.
Thank you.
