### ISSUE TITLE
[FR] Better Cert Manager

### ISSUE THREAD

**Issue by QDaniel** [opnsense/core#2539]
I missing the Function to renew certificates and csr signing.

**Comment by mimugmail** [comment]
Can be closed when #3234 is in ...

**Comment by AdSchellevis** [comment]
@mimugmail I'll close it when finished

**Comment by nhirokinet** [comment]
In my plan, `renew certificate` is not included in #3234.

**Comment by AdSchellevis** [comment]
close due to timeout then, nobody is planning to work on it, no need to keep it open forever.
