### ISSUE TITLE
Synchronization of Static Routes 

### ISSUE THREAD

**Issue by tsumaru720** [opnsense/core#254]
System -> High Availability -> Synchronize Static Routes -> Config Sync

"Automatically sync the Static Route configuration to the other HA host when changes are made."

This does sync gateway changes, but doesnt seem to sync actual static routes. Even if I add one, it does not appear on the second host.

Versions	OPNsense 15.7-amd64	
FreeBSD 10.1-RELEASE-p14	
OpenSSL 1.0.2c 12 Jun 2015

**Comment by AdSchellevis** [comment]
When trying to reproduce I received some errors from the sync process when static routes should be synced. 
Commit https://github.com/opnsense/core/commit/98939e30386777a3fcfd17def183beda6079bb8a should fix the issue.
