### ISSUE TITLE
OPNsense web GUI not working with v18.7.r1

### ISSUE THREAD

**Issue by reza-ebrahimi** [opnsense/core#2541]
I've installed `OPNSense v18.7.r1` on Virtualbox and assigned a static ip address to LAN interface, so when I `curl` it from inside OPNsense shell, the response always is nothing on port `80` and `Empty reply from server` on port `443`,

I've tested various scenarios, I've remove WAN interface from Virtualbox network adapters and still not working, some notes on forums tell to add a firewall rule on WAN interface, so I've disabled firewall with `pfctl -d` to bypass the firewall and still not working (`WAN` interface attached to Wireless network adapter).

I'm sure that `lighttpd` web server is running and listening on port 80 but does not respond correctly, I think my problem is not related to connection issues between Virtualbox guest and host networks, I'd say if `lighttpd` works correctly it should respond to curl command inside OPNsense.

I'm also tested with OPNsense v18.1.6 and still not working.

**Comment by fichtner** [comment]
Can you run this?

```
% fetch -v http://127.0.0.1/
resolving server address: 127.0.0.1:80
requesting http://127.0.0.1/
301 redirect to https://127.0.0.1/
resolving server address: 127.0.0.1:443
SSL options: 83004bff
Peer verification enabled
Using CA cert file: /usr/local/etc/ssl/cert.pem
Certificate verification failed for /C=NL/ST=Zuid-Holland/L=Middelharnis/O=OPNsense
3537115702888:error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed:/usr/src/crypto/openssl/ssl/s3_clnt.c:1264:
fetch: http://127.0.0.1/: Authentication error
```

**Comment by reza-ebrahimi** [comment]
@fichtner Yes,

![virtualbox_opnsense-v18](https://user-images.githubusercontent.com/11276982/42633547-1321d698-85f6-11e8-8b4c-71fb0cd23315.png)

**Comment by fichtner** [comment]
Looks good to me. Maybe you swapped interfaces or try to access WAN, but since you have a LAN you cannot access from WAN...

**Comment by reza-ebrahimi** [comment]
Currently there is no WAN interface, just have LAN interface,

![virtualbox_opnsense-v18-1](https://user-images.githubusercontent.com/11276982/42633754-a728338c-85f6-11e8-9477-bc93e4fdd232.png)

**Comment by reza-ebrahimi** [comment]
@fichtner Same result with attaching WAN interface, how WAN interface relates to LAN?

**Comment by fichtner** [comment]
nmap scan looks normal too... just tested with 192.168.56.5/24 as host-only network. Works from here.

**Comment by reza-ebrahimi** [comment]
@fichtner From outside its totally not working, but from inside OPNsense `curl` still have no reply, why it happens? it show that `lighttpd` server up and running but doesn't function properly.

```
$ curl 127.0.0.1 # returns nothing
$
```

**Comment by fichtner** [comment]
Not sure what you are saying... Same for me, but that doesn't mean it doesn't work:

```
% curl 127.0.0.1
% curl -v 127.0.0.1
* Rebuilt URL to: 127.0.0.1/
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 80 (#0)
> GET / HTTP/1.1
> Host: 127.0.0.1
> User-Agent: curl/7.60.0
> Accept: */*
> 
< HTTP/1.1 301 Moved Permanently
< Location: https://127.0.0.1/
< Content-Length: 0
< Date: Thu, 12 Jul 2018 13:02:55 GMT
< Server: lighttpd/1.4.49
< 
* Connection #0 to host 127.0.0.1 left intact
```

**Comment by reza-ebrahimi** [comment]
@fichtner Ok, agreed, could you please post curl output here from your host? 

mine is:
```console
$ curl -v http://192.168.56.5
* Rebuilt URL to: http://192.168.56.5/
*   Trying 127.0.0.1...
* SOCKS4 communication to 192.168.56.5:80
* SOCKS4 connect to 192.168.56.5 (locally resolved)
* Can't complete SOCKS4 connection to 0.0.0.0:67. (91), request rejected or failed.
* Closing connection 0
curl: (7) Can't complete SOCKS4 connection to 0.0.0.0:67. (91), request rejected or failed.
```

**Comment by fichtner** [comment]
Sure, from the VirtualBox host:

```
$ curl -v http://192.168.56.5
* Rebuilt URL to: http://192.168.56.5/
*   Trying 192.168.56.5...
* TCP_NODELAY set
* Connected to 192.168.56.5 (192.168.56.5) port 80 (#0)
> GET / HTTP/1.1
> Host: 192.168.56.5
> User-Agent: curl/7.54.0
> Accept: */*
> 
< HTTP/1.1 301 Moved Permanently
< Location: https://192.168.56.5/
< Content-Length: 0
< Date: Thu, 12 Jul 2018 15:09:56 GMT
< Server: lighttpd/1.4.49
< 
* Connection #0 to host 192.168.56.5 left intact
```

Looks like you have a SOCKS proxy configured on your PC? oO

**Comment by fabianfrz** [comment]
@fichtner either this or misconfigured WPAD/PAC ;)
What happens if you try `--proxy ""`?

**Comment by reza-ebrahimi** [comment]
@fichtner  I've disabled an old running tor proxy on my host Ubuntu machine and everything works fine right now, I'm appreciate your help.
