### ISSUE TITLE
Adding a new interface removes the default route

### ISSUE THREAD

**Issue by darinpp** [opnsense/core#2542]
I have currently WAN interface that uses DHCP and a LAN with static ip. I tried adding a new interface set to obtain IP through DHCP as well. As soon as I added the new interface the default route disappeared. I verified the Gateways and I can see that WAN_DHCP shows as default. 
I can consistently replicate the dropping of the default route by going into Interfaces : Overview and then pressing release followed by renew (the route dissapears when I press the renew) for the new interface.

This is with 18.1.11

**Comment by mimugmail** [comment]
https://github.com/opnsense/core/issues/1821

**Comment by mimugmail** [comment]
Yep, was sent from mobile ...sorry

**Comment by mimugmail** [comment]
But you receive a second default gateway via DHCP and you only can have one .. this cant work.

You probably try to disable receiving gateway on the second one

**Comment by darinpp** [comment]
Yes, the newly added interface gets a gateway address with the rest of the DHCP information. 
But the new interface is not the default one. The default gw in the routing table is set to another interface. 
Isn't the logic to only override the default gw in the routing table if the previous default gw was on the same interface? This seems to be the logic in `dhclient-script`

**Comment by darinpp** [comment]
Not sure what you are saying. The problem here is that the gateway set as default in the routing table stops being default after adding a new interface (using DHCP). I would expect that this interface is always the default as you are saying. 

I'm looking at the stock freebsd, pfsense and opnsense's versions of `dhclient-script` and it seems that in the stock and pfsense's versions, all the changes to the routing table's default gw are within `if is_default_interface; then` blocks. This isn't the case for opnsense. 
For example this line 
```
	if is_default_interface; then
		add_new_resolv_conf
	fi
``` 
is replaced by
```
	add_new_resolv_conf
	if [ "$changes" = "yes" ] ; then
		notify_rc_newwanip
	fi
```
Is this an intentional departure of how FreeBSD handles adding a new interface using DHCP?

**Comment by fichtner** [comment]
The script is almost entirely unchanged since we forked in 2014 so I have to admit I don't know why or how it was changed and what now works better and what works worse. It could also be that the FreeBSd script received updates over the years that never went into this copy. It's not an excuse, just trying to explain why the drift exists. I'll take a look at the diff side by side.

**Comment by fichtner** [comment]
This change is quite telling:

    -# $FreeBSD: src/sbin/dhclient/dhclient-script,v 1.4 2005/06/10 03:41:18 brooks Exp $
    +# $FreeBSD$

The file is basically from 2005. :/

**Comment by mimugmail** [comment]
For me, the question is, when enabling Default Gateway switvhing fix it, why not set it as default enabled

**Comment by fichtner** [comment]
Preliminary consolidation in 882ce28 mostly missing the naughty bits that have been changed for specific use in pfSense. Not sure if this fixes anything but for now I'll also take a "works like before".

**Comment by darinpp** [comment]
I can't test the patch on the firewall that I have because I can't afford downtime. The patch seems fine although in same cases it has the possibility to modify the default routes for an interface that isn't default.  
```
+			if ! is_default_interface; then
+				/usr/local/etc/rc.newwanip $interface
+				exit_with_hooks 0
+			fi
```
As for @mimugmail's comment - I have the Default Gateway switching enabled but I'm afraid that it will send traffic to my new interface in case my WAN interface goes down for some reason. I'll remove the new interface for now and think of something else. 
Thanks for the help.

**Comment by fichtner** [comment]
@darinpp there will be a new mode in gateway switching that will allow to deselect "unwanted gateways" in an early 18.7.x.

rc.newwanip needs to be called to properly configure the services and related actions on the interface. It will invoke gateway switching, yes, but I gather that's not what you want to use so it's not problematic... Only chance then is to adapt dhclient-script and see that the routing doesn't clobber defaults anymore.

**Comment by lwimmer** [comment]
I experience the same problem as described here and in #2690.

The fix in 19b832f6c80c538f4575ab0b6c09243451f180ee seems to solve this problem for me!

**Comment by fichtner** [comment]
Thank you for the feedback. This commit is not in 18.7 yet. FWIW, had no issues with it so far so we’ll discuss internally if it’s 18.7 material and report back. :)

**Comment by Franck78** [comment]
Hello,
Using opnSense 18.7.6,

The screwing of the routing table is still there 'by default'. Add a vlan nic with dhcp4 that will no receive answer to the Request/Discover and you get a screwed routing table

'by default' I mean maybe there is an advanced option somewhere in opnSense that should be off.
Cannot affirm that with an answer to DHCP received it would be ok.


The general setup is the one replacing the french livebox, three vLan over the wan interface.
```
em0 : gpon optic fiber
em1 : LAN
em0_vlan832 (dhcpv4 v6, the only and true default gateway)
em0_vlan838 (dhcpv4, not a gateway)
em0_vlan840 (static ipv4)
em2, em3 specifics interfaces no routing via them
```

Before enabling em0_vlan838

```
enabled:
WAN_INTERNET_DHCP (default) 	WAN_internet 	86.195.88.1 		0.0 ms 	0.0 % 	Online
	Interface WAN_internet dhcp Gateway 	
disabled:
WAN_INTERNET_DHCP6 	WAN_internet 	dynamic 		Pending 	Pending 	Online
	Interface WAN_internet dhcp6 Gateway 

Route/Status
ipv4	default	86.195.88.1	    UGS	261 1500	em0_vlan832	WAN_internet	 
ipv4	10.0.0.0/16	     link#2	U	517	1500	em1	LAN_nic	 
ipv4	10.0.0.201	     link#2	UHS	0	16384	lo0	 	 
ipv4	86.195.88.0/21	link#9	U	261	1500	em0_vlan832	WAN_internet	 
ipv4	86.195.91.67	link#9	UHS	0	16384	lo0	 	 
ipv4	127.0.0.1      	link#6	UH	0	16384	lo0	 	 
ipv4	192.168.20.0/24	link#4	U	0	1500	em3	TV_Lan	 
ipv4	192.168.20.2	link#4	UHS	0	16384	lo0	 	 
ipv4	192.168.30.2	link#10	UHS	0	16384	lo0	 	 
ipv4	192.168.30.2/32	link#10	U	0	1500	em0_vlan840	TV_840Stream


```
After enabling DHCPv4 em0_vlan838
will NOT receive any lease for some reasons

```
enabled:
TV_838CONTROL_DHCP 	TV_838Control 			0.0 ms 	0.0 % 	Online
	Interface TV_838Control dhcp Gateway 	
enabled:
WAN_INTERNET_DHCP (default) 	WAN_internet 	86.195.88.1 		0.0 ms 	0.0 % 	Online
	Interface WAN_internet dhcp Gateway 	
disabled:
WAN_INTERNET_DHCP6 	WAN_internet 	dynamic 		Pending 	Pending 	
	Interface WAN_internet dhcp6 Gateway 


ipv4	default	         link#11    U	88	1500	    em0_vlan838	TV_838Control	 
ipv4	10.0.0.0/16	     link#2	    U	7002 1500	    em1	LAN_nic	 
ipv4	10.0.0.201	     link#2	    UHS	0	16384	    lo0	 	 
ipv4	86.195.88.0/21	 link#9   	U	297	1500	    em0_vlan832	WAN_internet	 
ipv4	86.195.91.67	 link#9	    UHS	0	16384	    lo0	 	 
ipv4	127.0.0.1	     link#6	    UH	0	16384	    lo0	 	 
ipv4	192.168.20.0/24	 link#4   	U	0	1500      	em3	TV_Lan	 
ipv4	192.168.20.2	 link#4	    UHS	0	16384	    lo0	 	 
ipv4	192.168.30.2	 link#10	UHS	0	16384	    lo0	 	 
ipv4	192.168.30.2/32	 link#10	U	0	1500	    em0_vlan840	TV_840Stream	 

```

Activating the vlan_838 interface stubbornly create a gateway.
This gateway CANNOT be erased/disabled/down in any way with the GUI.....

enabled:
TV_838CONTROL_DHCP 	TV_838Control 			0.0 ms 	0.0 % 	Online
	Interface TV_838Control dhcp Gateway 	

and becomes 'default'. 

Not working !!!

**Comment by AdSchellevis** [comment]
@Franck78 using capitals and exclamations is likely not encouraging others to help you with your issue....

**Comment by fichtner** [comment]
So did you try the patch or not?

**Comment by Franck78** [comment]
What patch ??

Can't see any filename and code modification here.
Sorry.

**Comment by fichtner** [comment]
See 882ce28, apply in your installation using this command:

    # opnsense-patch 882ce28

**Comment by Franck78** [comment]
```
ipv4 | 0.0.0.0/8 | link#11 | U | 0 | 1500 | em0_vlan838 | TV_838Control |  

ipv4 | default | 86.195.88.1 | UGS | 371 | 1500 | em0_vlan832 | WAN_internet |  
ipv4 | 10.0.0.0/16 | link#2 | U | 244737 | 1500 | em1 | LAN_nic |  
ipv4 | 10.0.0.201 | link#2 | UHS | 0 | 16384 | lo0 |   |  
ipv4 | 86.195.88.0/21 | link#9 | U | 1709 | 1500 | em0_vlan832 | WAN_internet |  
ipv4 | 86.195.91.67 | link#9 | UHS | 0 | 16384 | lo0 |   |  
ipv4 | 127.0.0.1 | link#6 | UH | 0 | 16384 | lo0 |   |  
ipv4 | 192.168.20.0/24 | link#4 | U | 0 | 1500 | em3 | TV_Lan |  
ipv4 | 192.168.20.2 | link#4 | UHS | 0 | 16384 | lo0 |  |  
.......
```

with the patch (more a rewrite ;)   ) the default gw stays ok after enabling the vlan838 interface

As I said, no response from dhcp server, thus what is that entry created ?
`ipv4 | 0.0.0.0/8 | link#11 | U | 0 | 1500 | em0_vlan838 | TV_838Control |  `

**Comment by fichtner** [comment]
Goes into 19.1 as is. Thanks all for testing!

Side effects or similar issues should be handled in separate issues.
