### ISSUE TITLE
[ipv6] Unable to set multiple addresses on a single interface

### ISSUE THREAD

**Issue by RyuunoAelia** [opnsense/core#2543]
As defined in IPv6 RFCs, you might want to keep local communications while:
* your uplink is unreachable (so you loose your prefix for track6 local network type)
* you have renumbering occurring (change in upstream ipv6 prefix)
* other cases
The way to do it is, to set ULA addresses and public prefix at the same time.
This is a normal setup for IPv6 to have multiple prefixes on the same interface for different purposes (Link Local, ULA, global prefix, etc), but I just cannot find how to do it with opnsense.

When setting up the Interface, you can only choose a single type of network address (Track, SLAAC, etc) and even in that type you cannot set multiple IPs. And using multiple interfaces on the same broadcast domain is not a solution since RADV would kick in and might break IPv6 altogether.

I have seen the Virtual IP settings, in Firewall, however this only allows you to set up to 32 bit subnet (clearly this was made with IPv4 in mind).

Is there a third way to do it I did not discover yet ?

The whole context of my issue is in #2538.

**Comment by RyuunoAelia** [comment]
OH! Ok if I start entering an IPv6 the drop-down with the prefix length changed to allow a maximum of 128.

Sorry for the noise I should have tested that.

**Comment by RyuunoAelia** [comment]
Hmm well I the UI changes, but I get an error when trying to set as IP Alias. If I set it as Other it is useless, I don't need want this IP as CARP either (it is the device's own IP not a HA IP; even though I do not have other routers for the CARP setup).
The other are useless since I could not use the IP to access the WebUI defeating the purpose of the ULA.

**Comment by fichtner** [comment]
maybe it's not hitting the wan_stf device for the same reason?

**Comment by fichtner** [comment]
hmm, no, that can't be it.. which error are you seeing?

**Comment by RyuunoAelia** [comment]
Ok I found out what is happening... I tried to set fdb9:86fc:f74d:1945::/64 and apparently it is refused by the UI. setting fdb9:86fc:f74d:1945::0/64 works. Parsing issue I guess.

**Comment by RyuunoAelia** [comment]
The error message was : 
```
The following input errors were detected:
 * You cannot use the network address for this VIP
```

**Comment by fichtner** [comment]
@RyuunoAelia strange, /128 will let you do this with both IPs. From what I can see for /64 it should work for neither.

**Comment by fichtner** [comment]
The ::0 vs. :: oddity comes from IPv6 class not compressing the IPv6 completely and the compare fails.

Does your setup work if you set /128 for the alias? If yes, I would fix the validation so that both /64 variants fail (there seems to be some merit to the imposed restriction)

**Comment by RyuunoAelia** [comment]
No it won't work with /128 since the purpose of that ULA is to communicate with my internal network. So ideally I would configure pfsense to stop binding on public IP and only bind on the ULA (for ssh, http, etc).

I tried with "Other" but it does nothing on the network side.

I don't see the merit of the restriction to /128 (especially for ipv6), if this should always be /128 why have the drop-box that allows to choose the subnet ?

**Comment by fichtner** [comment]
It tries to avoid using the first address of a subnet as a valid IP. That's true for most IPv4 networks. Not so much for IPv6? OTOH, this is easily avoided by using ::1 instead of ::(0). But if this works in either case it's better to remove the validation.

**Comment by RyuunoAelia** [comment]
For IPv4 that was a restriction in the spec to avoid confusion. There was no technical reason behind the restriction, and it has been lifted when the IPv4 pool was becoming too small. Still some older systems do not support an IPv4 that has no machine address bits set.

This restriction was never in place for ipv6 so systems that do not support this have a buggy implementation of the IPv6 stack.

**Comment by RyuunoAelia** [comment]
Ah I just remebered, actually at the begginning of IPv4 there was a technical restriction. Before the arrival of CIDR the IP subnet was the IP with 0 to the Machine part of the address. With the prefix length being determined by the Class of the Address. So even when CIDR arrived, there was still this restriction. It has been lifted later.

But still with IPv6 there is no issue here.

**Comment by fichtner** [comment]
Ok, patch via:

    # opnsense-patch 063a425

**Comment by RyuunoAelia** [comment]
Ok applied and tested, it works. Thank you.

**Comment by fichtner** [comment]
You're welcome!
