### ISSUE TITLE
Unbound refuses queries from OpenVPN clients until service restart

### ISSUE THREAD

**Issue by theq86** [opnsense/core#2549]
Hi,

After rebooting OPNsense all DNS queries from remote clients get refused.
After restarting unbound, everything is working. There is also no log about refuses queries that I can find.

**Comment by thomasjsn** [comment]
I had to add my OpenVPN IP range to the list of Unbound authorized clients.

**Comment by theq86** [comment]
Currently the problem is gone. I'm on 18.7 now. I had it on the previous version.

However, OpenVPN ranges are automatically added to the list of authorized clients.
