### ISSUE TITLE
Reboot after a config restore

### ISSUE THREAD

**Issue by tsumaru720** [opnsense/core#255]
I performed a config restore on my opnsense install and it imported fine and rebooted the box. Now however whenever I go to the backup/restore page I see:

> The firewall configuration has been changed.
> The firewall is now rebooting.

and then the box gracefully reboots. Every time.

Versions	 OPNsense 15.7.2-amd64	
FreeBSD 10.1-RELEASE-p14	
OpenSSL 1.0.2d 9 Jul 2015

**Comment by fichtner** [comment]
From the console, please delete the file /var/run/restore.dirty -- a more permanent fix will be in 15.7.3.
