### ISSUE TITLE
Unbound Domain Overrides support for forward-zones instead of stub-zone

### ISSUE THREAD

**Issue by johnkeates** [opnsense/core#2550]
There seems to be an issue that some uses run in to where domain overrides in Unbound might point to DNS servers that are forwarders themselves (i.e. another OPNSense box with its own overrides and zones). Unbound stub-zones don't allow this as they can only point to authoritative name servers.

The forward-zone option does the same thing but allows non-authoritative to be used instead of just returning a SERVFAIL to the client.

**Comment by johnkeates** [comment]
Ping?

Perhaps the easier quick fix is to swap forward-zone for stub-zone for now?

**Comment by fichtner** [comment]
This should be able to make 18.7.3 if testing goes well, thanks! :)

**Comment by fichtner** [comment]
Will pull into 18.7.3 as promised. Just to be clear: 18.7.2 is next up. The addition comes afterwards. :)
