### ISSUE TITLE
CARP Flapping with IP Alias

### ISSUE THREAD

**Issue by drkdragonarcher** [opnsense/core#2551]
When adding additional IPs as IP Aliases using the same VHID as my primary WAN vIP to use for NAT, it causes the CARP master to flap back and forth between the two firewalls.

**Comment by fichtner** [comment]
Could it be #2486 ?

**Comment by drkdragonarcher** [comment]
I don't think mine is that. I don't see thatioctl (SIOCAIFADDR) in the logs for this (although I have seen that randomly after rebooting or coming out of persistent mode). Here's some excerpt from my logs. I get these repeated multiple times within the same time so I tried to collapse it into just what was unique.

```Jul 10 03:28:36 fw1 opnsense: /usr/local/etc/rc.carpbackup: Carp cluster member "x.x.x.178 -  (2@em1)" has resumed the state "BACKUP" for vhid 2
Jul 10 03:28:36 fw1 opnsense: /usr/local/etc/rc.linkup: Hotplug event detected for WAN(wan) but ignoring since interface is configured with static IP (x.x.x.181 ::)
Jul 10 03:28:36 fw1 kernel: OK
Jul 10 03:28:36 fw1 opnsense: /usr/local/etc/rc.newwanip: IP renewal is starting on 'em1'
Jul 10 03:28:36 fw1 opnsense: /usr/local/etc/rc.newwanip: On (IP address: x.x.x.181) (interface: WAN[wan]) (real interface: em1).
Jul 10 03:28:36 fw1 kernel: ifa_maintain_loopback_route: deletion failed for interface em1: 3
Jul 10 03:28:36 fw1 kernel: carp: 2@em1: MASTER -> INIT (hardware interface up)
Jul 10 03:28:36 fw1 kernel: carp: 2@em1: INIT -> BACKUP (initialization complete)
Jul 10 03:29:11 fw1 kernel: carp: demoted by -240 to 0 (pfsync bulk done)
Jul 10 03:29:11 fw1 kernel: carp: demoted by 240 to 240 (pfsync bulk start)
Jul 10 03:29:11 fw1 kernel: carp: demoted by -240 to 0 (pfsync bulk done)
Jul 10 03:29:11 fw1 opnsense: /usr/local/etc/rc.carpbackup: Carp cluster member "x.x.x.178 -  (2@em1)" has resumed the state "BACKUP" for vhid 2
Jul 10 03:29:15 fw1 kernel: carp: 2@em1: BACKUP -> MASTER (master timed out)
Jul 10 03:29:15 fw1 opnsense: /usr/local/etc/rc.carpmaster: Carp cluster member "x.x.x.178 -  (2@em1)" has resumed the state "MASTER" for vhid 2
Jul 10 03:29:15 fw1 opnsense: /usr/local/etc/rc.carpmaster: Starting OpenVPN server instance on 207.99.80.178 -  because of transition to CARP master.
Jul 10 03:29:15 fw1 kernel: ovpns1: link state changed to DOWN
Jul 10 03:29:16 fw1 kernel: ovpns1: link state changed to UP
Jul 10 03:29:16 fw1 opnsense: /usr/local/etc/rc.newwanip: IP renewal is starting on 'ovpns1'
Jul 10 03:29:16 fw1 opnsense: /usr/local/etc/rc.newwanip: Interface '' is disabled or empty, nothing to do.
Jul 10 03:29:41 fw1 kernel: carp: 2@em1: MASTER -> BACKUP (more frequent advertisement received)
Jul 10 03:29:41 fw1 kernel: ifa_maintain_loopback_route: deletion failed for interface em1: 3```

**Comment by fichtner** [comment]
There are carp changes coming to address this. Don’t have ticket numbers to paste at the moment.

**Comment by mimugmail** [comment]
You need to create the alias on Backup machine manually

**Comment by clebig** [comment]
Similar BUG here. IP Alias (IPv6) created on both master and slave using the same vhid (inherited from the CARP interface).

`Jan  7 19:49:41 192.168.0.245 kernel: carp: 44@igb0_vlan242: MASTER -> BACKUP (more frequent advertisement received)
Jan  7 19:49:44 192.168.0.245 devd: Processing event '!system=CARP subsystem=44@igb0_vlan242 type=MASTER'
Jan  7 19:49:44 192.168.0.245 kernel: carp: 44@igb0_vlan242: BACKUP -> MASTER (master timed out)
Jan  7 19:49:45 192.168.0.245 devd: Processing event '!system=CARP subsystem=44@igb0_vlan242 type=BACKUP' `

If I remove the alias on the backup, it stops flapping. When I re add it, it starts again. 

Clément
