### ISSUE TITLE
XMLRPC sync for routes will only be called when touching firewall rules

### ISSUE THREAD

**Issue by mimugmail** [opnsense/core#2552]
When adding a route no Master it doesn't get replicated to Slave until I manually edit a rule and save.
Responsible for syncing seems to be: /usr/local/etc/rc.filter_synchronize

No idea if it's good to call this script also within routes code (no MVC glue) or try restructure all for 19.1 or 19.7.

**Comment by AdSchellevis** [comment]
We should at least make it explicit somewhere how to sync :)

**Comment by fichtner** [comment]
same as 
https://github.com/opnsense/core/issues/2796
