### ISSUE TITLE
Allow 6RD tunnel mtu to be configured.

### ISSUE THREAD

**Issue by diekgait** [opnsense/core#2553]
The current mtu of a 6RD tunnel(wan_stf) interface is 1280 and cannot be configured. For most setups this does not deliver the optimal performance.
In my opinion the mtu should be configurable and have a default and maximum value of the parent interface mtu-20.
So if the parent interface is configured with an MTU of 1500 the tunnel interface should have a default mtu of 1480 configured, and this should also be the maximum value that can be configured.

**Comment by fichtner** [comment]
@diekgait Thanks for the idea! To minimise impact the MTU will remain 1280 unless the user specifies an explicit interface MTU. The calculation logic then follows your suggestions.


Cheers,
Franco
