### ISSUE TITLE
Cancel install -> menu doesn't recover

### ISSUE THREAD

**Issue by stilez** [opnsense/core#2556]
If you run the installer from external media with a blank SSD/HDD, and take the install process to the point it starts to write to the new disk, then click "cancel", the installer can't recover, because it doesn't escape you back to the point where you specify the disk or layout. It only lets you escape to the point of retrying the write-out - which then fails.

**Comment by fichtner** [comment]
thanks for your report.. installer repository is here https://github.com/opnsense/bsdinstaller ... would you mind moving this ticket? :)


Thanks,
Franco

**Comment by stilez** [comment]
Reopened on other repo as asked.
