### ISSUE TITLE
Define alias - logic error

### ISSUE THREAD

**Issue by stilez** [opnsense/core#2559]
Step 1: Use the "Alias Import" page to create the following: host 1.1.1.1-1.1.1.5

Step 2: Use the "Alias View" page to modify it to 1.1.1.2-1.1.1.5. 

Fails because it expects a network type - but won't let you either enter the IP range or change the alias type.

**Comment by AdSchellevis** [comment]
@stilez this feature (the import) will be dropped in 18.7.1 or 18.7.2, we're working on a new version of the alias system.

**Comment by stilez** [comment]
Good :)  I've been aiming for an alias handling rewrite in pfSense for ages but never had a chance to do it. Good news to heat its hapeninf on OPNsense. May I contribute ideas/code  (if so where) or is it too far along?

**Comment by stilez** [comment]
bliss!
