### ISSUE TITLE
dashboard: clicking upgrade does not upgrade directly

### ISSUE THREAD

**Issue by sjorge** [opnsense/core#256]
On the dashboard when you do:
- check for upgrade
- do the upgrade -> takes you to the upgrade page, instead of upgrading

on that page I have to check again, then i am able to upgrade. Kind of a lot of extra clicks.

**Comment by fichtner** [comment]
I agree. However, that's working as intended as we had trouble "caching" the results for the upgrade previously. Keeping this here for picking it up later.

**Comment by sjorge** [comment]
Well an easy fix would be after checking the status on the dashboard adn clicking upgrade on the dashboard... to just start an upgrade and display the progress tab?

**Comment by fichtner** [comment]
The upgrade is triggered via Java Script using the API, that's hard to just "link" against without being on the firmware page. Also, I'd like the user to review the changes before clicking "update". We were talking about storing the update info in the user session to do that properly...

**Comment by sjorge** [comment]
OK, makes sense.

**Comment by fichtner** [comment]
I have some more firmware upgrade / review tickets, will try to mop this one up with #249 #250

**Comment by fichtner** [comment]
The link will now launch the "update check" step in the firmware page automatically. That's the best we can do for now. Another confirmation will be needed afterwards. :)
