### ISSUE TITLE
[18.7.r1] IPv4+IPv6 rules seem broken?

### ISSUE THREAD

**Issue by sjorge** [opnsense/core#2564]
After switching to the RC i noticed my DNS lookups were super slow.

![firewall_log](https://i.imgur.com/pGXi1Bs.png)

Odd that all IPv6 DNS tries are blocked, I checked if something was still listening (probably because lookups via the IPv4 of the box still worked)

```sjorge@hydrogen:~ % sudo netstat -na | grep 53
tcp6       0      0 *.53                   *.*                    LISTEN
tcp4       0      0 *.53                   *.*                    LISTEN
udp6       0      0 *.53                   *.*
udp4       0      0 *.53                   *.*```

![firewall_rules](https://i.imgur.com/vwxMT6x.png)

The rule looks good... but traffic is indeed dropped.

**Comment by fichtner** [comment]
can you see which rule blocks and dump the relevant entries from /tmp/rules.debug ?

**Comment by sjorge** [comment]
I'm still digging further into but more than just this seems wrong, most IPv6 traffic seems to be hitting my catch all reject rule at the bottom. So far 'Match all IPv6 on all protocol' does not even match anything... which is very very worrying and I might revert soon if I can;t figure out more what is broken.

**Comment by sjorge** [comment]
Looks like all IPv6 stuff is just hitting my default 'reject IPv4+6 from any to any rule' 👎

**Comment by sjorge** [comment]
So the rule original rule + logging (as I am excluding my tests which I have undone)
```
pass in log quick on vtnet4 inet proto {tcp udp} from {(vtnet4:network)} to {(vtnet4:0)} port {53} keep state label "USER_RULE: Allow DNS" # 40400b57569601ac494729021c93ab64
pass in log quick on vtnet4 inet6 proto {tcp udp} from {(vtnet4:network)} to {(vtnet4:0)} port {53} keep state label "USER_RULE: Allow DNS" # 40400b57569601ac494729021c93ab64
```

Never matches and the traffic hits

```
block return in log quick on vtnet4 inet from {any} to {any} label "USER_RULE: Reject catch all [MGMT]" # 70f0b03d9926a8b4293fd4ad225bbc3a
block return in log quick on vtnet4 inet6 from {any} to {any} label "USER_RULE: Reject catch all [MGMT]" # 70f0b03d9926a8b4293fd4ad225bbc3a
```

**Comment by sjorge** [comment]
OK I think I narrowed it down! The problem is the destination.

If I manually split the rule into 2 one for IPv6 and one for IPv4 and not use 'IF_MGMT Address' as destination but 10.23.40.1 for the IPv4 one and 2001:470:7ee7:40::1 for the IPv6 one it works!

It's rather annoying though.

**Comment by fichtner** [comment]
It could be 2408d6a12. Try this then:

    # opnsense-patch 2408d6a12

**Comment by sjorge** [comment]
For now I fixed it by swapping 'IF_MGMT Address' with a table that has both addresses, now the original rule works again. A lot of my rules use 'IF_XXX Address' so that is why most stuff seems broken. Going to swap those to the tables for now, but Ideally this should be fixed somehow.

**Comment by sjorge** [comment]
On that note I had similar issues on OpenBSD as :0 only grabs the first IP... even if of type inet4

**Comment by sjorge** [comment]
@fichtner After reversing that commit everything is working again! So it is certainly that commit.

**Comment by fichtner** [comment]
The only thing that :0 does is described here:

    :0            Do not include interface aliases.

So I guess it means you rely on an alias to be automatically included?

**Comment by sjorge** [comment]
I don't have aliases configure on them, just one static IPv4 and one static IPv6 address (well those are technically 2 as there is a local-link which you always get in addition).

But I think anything that is not the primary ip(v4) address counts an an alias right?

**Comment by fichtner** [comment]
I think it grabs the link local. This would be iffy.

**Comment by sjorge** [comment]
It grabbing inet6 local-link or the primary inet one would be wrong behavior for IPv6 or IPv5+IPv6 rules.

**Comment by fichtner** [comment]
yeah, in any case it's a pf(4) bug we'd need to look into

**Comment by fichtner** [comment]
@sjorge so can you patch pfctl on your own or do you want a binary to try?

https://github.com/opnsense/src/commit/c160c3cd2e

**Comment by sjorge** [comment]
A binary would be helpful.

**Comment by fichtner** [comment]
Late night bug included, will post one within 30 minutes.

**Comment by fichtner** [comment]
https://pkg.opnsense.org/FreeBSD:11:amd64/snapshots/ifconfig

**Comment by fichtner** [comment]
geez, sorry, I'm an idiot... pfctl coming right up :D

**Comment by fichtner** [comment]
https://pkg.opnsense.org/FreeBSD:11:amd64/snapshots/pfctl

**Comment by sjorge** [comment]
I replaced /sbin/pfctl with the one you linked, problem is still there when using 'IF_MGMT Address' for the rule. Generated rules look the same, but that is expected if I understand the diff.
```
pass in quick on vtnet4 inet proto {tcp udp} from {(vtnet4:network)} to {(vtnet4:0)} port {53} keep state label "USER_RULE: Allow DNS" # d33ab56e7d27ee832fb3f199365f0e8b
pass in quick on vtnet4 inet6 proto {tcp udp} from {(vtnet4:network)} to {(vtnet4:0)} port {53} keep state label "USER_RULE: Allow DNS" # d33ab56e7d27ee832fb3f199365f0e8b
```

**Comment by fichtner** [comment]
Can you post ifconfig one more time for vtnet4 ?

**Comment by sjorge** [comment]
```
isjorge@hydrogen:~ % ifconfig  vtnet4
vtnet4: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500
	options=80028<VLAN_MTU,JUMBO_MTU,LINKSTATE>
	ether e2:3c:1b:01:a8:33
	hwaddr e2:3c:1b:01:a8:33
	inet 10.23.40.1 netmask 0xffffff00 broadcast 10.23.40.255
	inet6 fe80::e03c:1bff:fe01:a833%vtnet4 prefixlen 64 scopeid 0x5
	inet6 2001:470:7ee7:40::1 prefixlen 64
	nd6 options=21<PERFORMNUD,AUTO_LINKLOCAL>
	media: Ethernet 10Gbase-T <full-duplex>
	status: active
```

**Comment by fichtner** [comment]
It needs both kernel and pfctl patch... brrrr, I'll post this in a few hours. Thanks for your help so far!

**Comment by fichtner** [comment]
PS: kernel patch, same same but different https://github.com/opnsense/src/commit/4cadbe

**Comment by fichtner** [comment]
Long story short, we're reverting 2408d6a12 for 18.7 and work around it in another way.
