### ISSUE TITLE
Switching domain name leads to “DNS rebind attack” warning

### ISSUE THREAD

**Issue by fbruetting** [opnsense/core#2565]
I switched my domain name and immediately received this page:
![bildschirmfoto von 2018-07-22 19-52-50](https://user-images.githubusercontent.com/10520767/43048517-38e50300-8de9-11e8-8f96-c1e78607b450.png)

Can this be better handeled? It may also be caused due to me not having set up a TLS certificate yet.

**Comment by AdSchellevis** [comment]
You need to configure the proper dns in the software or add alternate hostnames, see
![image](https://user-images.githubusercontent.com/9783985/43048554-bd1c5178-8de9-11e8-8d29-f30f9bf57d59.png)

**Comment by fbruetting** [comment]
Should I just put the hostname into that box? (I don’t really understand this option.)

When I change the domain name (not the hostname) in OPNsense, the router should be able to handle this appropriately (maybe redirect afterwards etc), or do I miss something here?

**Comment by AdSchellevis** [comment]
if you add the full hostname (including domain), it should work, same of you change the host and domain name of the machine itself.

If you want to known what this is about, please read https://en.wikipedia.org/wiki/DNS_rebinding

**Comment by fbruetting** [comment]
Well, that’s something OPNsense if completely aware of, when I change either the host name or the domain name. Can’t OPNsense do this automatically?
