### ISSUE TITLE
configd enters infinite loop and cause 100% CPU usage

### ISSUE THREAD

**Issue by hayatigonultas** [opnsense/core#2568]
Hi,

OPNsense version: 18.1.12

When configd is restarted while it is executing a relatively long running cron job(around 10secs), it starts to loop forever in "while True" loop and never exits (after two days for example):
Code is from /usr/local/opnsense/service/configd_ctl.py causing the loop:

    try:
        sock.send(exec_command)
        data = []
        while True:
            line = sock.recv(65536)
            if line:
                data.append(line)

            # end of stream marker found, exit
            if line.find("%c%c%c"%(chr(0), chr(0), chr(0))) > -1 or (
                len(line) < 3 and len(data) > 1 and (''.join(data[-2:])).find("%c%c%c"%(chr(0), chr(0), chr(0))) > -1
            ):
                break

        return ''.join(data)[:-3]

**Comment by AdSchellevis** [comment]
This part is the client (`configctl`), you need to know which command it was trying to execute and for which output it's still waiting. The configd log might give hand you some pointers, you can find it in System->Logfile->Config

**Comment by hayatigonultas** [comment]
Hi Ad, 
in fact I've pointed out the exact location of the infinite loop with adding debug outputs to configd_ctl.py. If it is the client side then termination of actual command should also have terminated configd_ctl.py process. But in my case it did not. 

It is quite easy to reproduce this though. When you add a new action (namely sleep : which basically sleeps for 60 seconds) to 

`/usr/local/opnsense/service/conf/actions.d/actions_sleep.conf`

with the below contents:

```
[sleep]
command: sleep 60
parameters:
type:script_output
message:sleep some
```

and running with this action with (you may need to restart configd to read sleep command):

`systemctl sleep sleep`

while it is running then just restart configd a few times to trigger case.
That's it you'll get 100% cpu usage.

**Comment by AdSchellevis** [comment]
it doesn't on my end, it just exits after 60 seconds. sock.recv() is blocking, if for some vague reason the endmarker isn't transmitted and the connection is lost, in theory this could happen, but I really expect something in the log then. Can you inspect `/var/log/configd.log` for details?

**Comment by hayatigonultas** [comment]
Hi Ad,
My guess is that recv() is returning 0 because peer closed connection. And this case does not seem to be handled there. I've done a dirty fix to handle this case, and it seems to be solving the issue.

```
    try:
        sock.send(exec_command)
        data = []
        while True:
            line = sock.recv(65536)
            if line:
                data.append(line)
            else: # This part handles recv returns 0 case ******
                break

            # end of stream marker found, exit
            if line.find("%c%c%c"%(chr(0), chr(0), chr(0))) > -1 or (
                len(line) < 3 and len(data) > 1 and (''.join(data[-2:])).find("%
c%c%c"%(chr(0), chr(0), chr(0))) > -1
            ):
                break
```

**Comment by AdSchellevis** [comment]
the restart of configd was the missing part, sounds reasonable, although I'm not 100% about the fix. let me get back on this after checking the rest of our code.

**Comment by hayatigonultas** [comment]
Sounds great.

**Comment by AdSchellevis** [comment]
@hayatigonultas just checked some different inputs and it seems we overreacted with the end of stream marker in this case. I've replaced it with the normal break when no data found. Thanks for reporting.
