### ISSUE TITLE
IPSec There is a Phase 2 using IPv6, you cannot use IPv4

### ISSUE THREAD

**Issue by sachaz** [opnsense/core#2570]
Hi
I'm trying to do something like this:

ServerZZTop ----- FirewallA [OPNSense] o===(IPSEC)===o FirewallB [OpenBSD] ----- Internet

ServerZZTop have a public IPv4/6

Phase 1 Type: IPv4 IKE v1
Phase 2 Type:  ESP IPv4 tunnel
Phase 2 Type:  ESP IPv6 tunnel

Yes I got I phase 2 for an IPv4 tunnel AND another one for an IPv6 tunnel, Strongswan is suposed to work like this(https://www.strongswan.org/testing/testresults/ipv6/net2net-ip6-in-ip4-ikev1/).
Yes it works on OPNSense too.

The bug for me is the following message when I try to modify my phase 1: "There is a Phase 2 using IPv6, you cannot use IPv4".

**Comment by AdSchellevis** [comment]
@sachaz if I read the scenario's correctly https://www.strongswan.org/testing/testresults/ipv6/ both should work ipv4 of a ipv6 tunnel and vise versa. correct? we can easily drop the validation if not needed anymore.

**Comment by sachaz** [comment]
due to this error message I cannot change anymore any parameter on my phase 1 IPv4 until I have phase 2 ipv6 :(

**Comment by AdSchellevis** [comment]
that I understand, my question was about strongswan itself.

**Comment by AdSchellevis** [comment]
https://github.com/opnsense/core/commit/a79b20c12759007f2079ffd6e0cad26d04b00808 removes the validation, to test use:
```
opnsense-patch  a79b20c 
```

**Comment by sachaz** [comment]
Thanks it works perfectly

**Comment by fichtner** [comment]
Yay, I'll push this into 18.7 then. Thanks for testing! ❤️

**Comment by sachaz** [comment]
Thanks guys to be so reactive ❤️
