### ISSUE TITLE
IPSec auto Passthrough networks

### ISSUE THREAD

**Issue by sachaz** [opnsense/core#2571]
When I configuring IPSec I have to set up manually passthrough networks from my Opnsense firewall's local interface.
I guess this passthrough should be always activated allways: local network should not be routed in the IPSec tunnel (for exemple it's a problem arp IPv4/IPv6 requests).

**Comment by AdSchellevis** [comment]
Strongswan has https://wiki.strongswan.org/projects/strongswan/wiki/Bypass-lan available for that purpose, but I don't think we are going to add it, never tried it myself. 

It's relatively easy to add your own networks to the configuration, auto generating the networks on our end will cause an unwanted dependency on configuration changes for IPsec.

**Comment by sachaz** [comment]
my wondering is about in which case we don't need a exclusion of the local network to be routed in the IPSec tunnel ?
a click to "disable auto exclusion of local network" ? or add this information in the OPNSense IPSec wiki ?

**Comment by AdSchellevis** [comment]
local networks change, which won't cause ipsec to restart. If you would be so kind to work on the docs page (or a fix which doesn't involve entanglement with the network configuration) that would be greatly appreciated.

**Comment by sachaz** [comment]
https://atelier.aquilenet.fr/projects/services/wiki/Librehosting

**Comment by AdSchellevis** [comment]
timeout
