### ISSUE TITLE
opnsense_bootgrid_plugins.js doesn't reload bootgrid via std_bootgrid_reload when adding items

### ISSUE THREAD

**Issue by fbrendel** [opnsense/core#2576]
The grid is always reloaded via _std_bootgrid_reload(gridId);_ except if you add an item.
Then _$("#"+gridId).bootgrid("reload");_ is used.
https://github.com/opnsense/core/blob/master/src/opnsense/www/js/opnsense_bootgrid_plugin.js#L295

The problem is that Relayd chains the std_bootgrid_reload to get the isSubsystemDirty state. So if you add a virtual server for example the message 'The Relayd configuration has been changed...' doesn't appear.

**Comment by AdSchellevis** [comment]
@fbrendel can you point me to your issue?  https://github.com/opnsense/core/blob/master/src/opnsense/www/js/opnsense_bootgrid_plugin.js#L108 only tries to reconstruct the current page and reloads the provided bootgrid.

**Comment by fbrendel** [comment]
The plugin chains std_bootgrid_reload and loads the isSubsystemDirty state from the SettingsController
https://github.com/opnsense/plugins/blob/d9863be946df47157a462addbec403347b6b76c1/net/relayd/src/opnsense/mvc/app/views/OPNsense/Relayd/index.volt#L51

But when adding an item the std_bootgrid_reload is not called.

E.g. when you edit and save an item std_bootgrid_reload is called
https://github.com/opnsense/core/blob/d4190f08d698c08c5e9aafdf2ae5d93490953a42/src/opnsense/www/js/opnsense_bootgrid_plugin.js#L190

But why not when adding an item?
https://github.com/opnsense/core/blob/d4190f08d698c08c5e9aafdf2ae5d93490953a42/src/opnsense/www/js/opnsense_bootgrid_plugin.js#L295

**Comment by fbrendel** [comment]
And works. :clap:
Thank you :smiley:
