### ISSUE TITLE
Backup - Entreprise

### ISSUE THREAD

**Issue by b4b857f6ee** [opnsense/core#2577]
Hi,

In the backup section we only can backup with google drive, witch is not really professional.
Any chance to get a configuration menu for http upload? NFS? FTP?
So we can be as the same level of the other firewall.

Thank you

**Comment by fichtner** [comment]
There is already Nextcloud and there will also be SCP. You can also plug in your own backup mechanisms that will plug into the GUI and keep working after firmware updates. Even plugins are possible.
