### ISSUE TITLE
Cannot add LDAP users together with local users

### ISSUE THREAD

**Issue by fbrendel** [opnsense/core#2578]
The cloud button for LDAP import at System -> Access -> Users is not visible with a LDAP server AND "Local Database" selected as authentication servers.
To add LDAP users I have to remove "Local Database" and add it afterwards again for local users.

**Comment by fichtner** [comment]
Multiple auth modes are new so the behaviour is expected but should be changed.

**Comment by fichtner** [comment]
@fbrendel can you try 8e28b78 ? It's not perfect but does what you expect:

    # opnsense-patch 8e28b78

**Comment by fbrendel** [comment]
Yes, works!
Thank you :+1:

**Comment by fichtner** [comment]
Thanks, I'll pull this into 18.7.
