### ISSUE TITLE
Suggest changing default mirror from HTTP to HTTPS

### ISSUE THREAD

**Issue by tonsilware** [opnsense/core#2582]
Hi,

When using the OPNSense gui (18.1.13) to "check for updates" with the "firmware mirror" set to "(default)" I noticed that OPNSense is pulling updates from pkg.opnsense.org via insecure HTTP (port 80). For me this is undesirable from a privacy point of view because anyone upstream (monitoring communications) can see exactly which packages are being updated etc. For privacy purposes I believe HTTPS would be a preferable default.

Another issue is that the "firmware mirror" dropdown list at "System: Firmware -> Settings" doesn't clearly show whether a mirror uses HTTP or HTTPS. So how is a user to know which mirrors are http and which are https? Also, how is a user to know the default is over insecure http?

Two suggestions (for whatever it's worth):
1) Suggest changing the default mirror URL from: http://pkg.opnsense.org to http**s**://pkg.opnsense.org
2) In the "Firmware mirror" dropdown list at "System: Firmware -> Settings" suggest putting the actual mirror URL after the name so users can see whether the mirror uses https or http. Perhaps also show the actual default url next to (default).

Thanks.

**Comment by fichtner** [comment]
Believe it or not, HTTPS with static content will not help your privacy concerns. There was a paper at least 6 years ago that showed this with encrypted HTTPS traffic analysis which could find the corresponding HTTP page associated (Wikipedia was used to conduct this reseach). I can't find the paper with a quick search, but I hope you can see that there is no privacy issue involved here.

If you really want to go private you can run you own internal mirror and simply use rsync from e.g. https://mirror.fra10.de.leaseweb.net/ -- that's as invisible as you can be.

**Comment by fichtner** [comment]
Half-expected fallout reported here https://forum.opnsense.org/index.php?topic=9435.msg42875#msg42875

Which means we won't add this before 19.1.
