### ISSUE TITLE
UI - Firewall/Rules representation/rendering 

### ISSUE THREAD

**Issue by commonism** [opnsense/core#2583]
I'd love to improve the representation of the rules in OPNSense to make a pfSense migration possible.

This is some screenshots of the rules view on a 2560x display using full/half/even less of the screen:

![opn_rules_2551](https://user-images.githubusercontent.com/164513/43380852-e680bdd0-93d2-11e8-9fd1-e2ecb5932de1.png)
![opn_rules_1914](https://user-images.githubusercontent.com/164513/43380838-df3f7f5c-93d2-11e8-83ed-76a96ddd7102.png)
At 1400x it starts to stack the icons:
![opn_rules_1400](https://user-images.githubusercontent.com/164513/43380845-e3335192-93d2-11e8-9531-41fcbafb2280.png)

To improve the usability of this very important view, there are things I'd like to change:
  * if the category changes, the category of a rule is shown above the rule
  * category filter box has the categories *sorted* by name and only the categories of the current interface
  * description is a row below the rule
  * remove Gateway column
  * remove Schedule column
  * add options column for things like interface(s), direction, Gateway, Schedule
  * rules with things not shown have an "advanced icon"
  * all clickable things for a rule are in the same spot
  * disabled rules font is grey/italic for the whole row

Similar to:
![example](https://user-images.githubusercontent.com/164513/43382777-2e6f18e8-93d9-11e8-8814-e404e1a1c11a.png)

If we could have the category to be coloured (attribute on the XML Element is an backwards compatible change) - even better.

As you may guess I really miss separators and as you propose to use category instead, lets make it a working replacement.

In case you have a large test config using aliases, floating rules, multiple interfaces, categories and all the other nice things, I could render it as an example. Small configs do not work, as there is very little gain cleaning up the rendering for them.

**Comment by AdSchellevis** [comment]
@commonism there's more work needed in the firewall area to eventually drop the legacy code and move to new api enabled mvc code.  I the meantime it's no problem to improve the visibility as long as the changes are manageable (small steps, easy to review). I'm not sure about the proposed layout, it should eventually fit with the rest of the system in look in feel for as far as possible.

**Comment by fabianfrz** [comment]
@AdSchellevis it would be also possible to provide an API via the legacy file which would make the new components working. When the backend is ready, only the API endpoints need to be moved.

**Comment by AdSchellevis** [comment]
@fabianfrz it's possible, but not advisable, you would have to create plumbing including validations which reacts the same as the model you're intending to build. When building components end-to-end it's easier validate you're assumptions, creating the model itself is usually not the hard labor.

**Comment by fabianfrz** [comment]
@AdSchellevis the only problem is the sorting order because accessing sub trees works differently.

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository, 
please read https://github.com/opnsense/core/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue, 
just let us know, so we can reopen the issue and assign an owner to it.
