### ISSUE TITLE
interfaces: build HE tunnel IPv6 mode

### ISSUE THREAD

**Issue by fichtner** [opnsense/core#2584]
HE tunnel setup has several drawbacks so it's time to integrate this properly. This will also pave the way for DS-Lite integration which is the other way around...

CC @noctarius

**Comment by noctarius** [comment]
👍 after the dhcpv6 stuff is merged it should be fairly easy to get the rest tested and integrated. Being a few weeks into the new company stress also seems to fall off a bit on learning all the new stuff :D

**Comment by fichtner** [comment]
with 18.7 it's all in. going to be released tomorrow. :)

**Comment by noctarius** [comment]
sounds like a win-win-win situation lol
