### ISSUE TITLE
Cannot override gateway to "none" in DHCPv4 static mapping

### ISSUE THREAD

**Issue by Addy90** [opnsense/core#2587]
When you want to override a DHCPv4 static mapping gateway with none (current 18.1.13), you cannot assign this value within the static mapping scope. Error is the following:

>The following input errors were detected:
>
>A valid IP address must be specified for the gateway.
>The gateway address none does not lie within the chosen interface's subnet.

But on the main settings page of the DHCPv4 server, the help text to the Gateway tells us:
> The default is to use the IP on this interface of the firewall as the gateway. Specify an alternate gateway here if this is not the correct gateway for your network. Type "none" for no gateway assignment.

I need this scenario because one client gets IPv4 addresses from two different OPNsense that do not communicate with each other and have different roles, but the outgoing network should only go through one of the firewalls. So setting the static mapping to "none" on one firewall would exactly do what I want, but this shall not be the default, only when overriding this single client.

I think this should be simple to fix...

**Comment by AdSchellevis** [comment]
@Addy90 I can't reproduce this, although I think the current `none` input is somewhat confusing, it seems to be working fine on my end, due to https://github.com/opnsense/core/blob/master/src/www/services_dhcp.php#L214

Maybe some spacing before or after the "none" string?

**Comment by Addy90** [comment]
Dear @AdSchellevis 
Please have a look here: https://github.com/opnsense/core/blob/master/src/www/services_dhcp_edit.php#L185
You sent me the main settings page which I wrote is working as expected, my problem is that the static leases do not work as expected! As you can see, there is no mentioning of "none" in the override section "edit" page.

**Comment by AdSchellevis** [comment]
@Addy90 The help text in the static assignment is correct, I'm unsure what you would like to fix here, but feel free to propose a pull request for us to validate.

The "none" implementation for the dhcp zone can be found here:

https://github.com/opnsense/core/blob/master/src/etc/inc/services.inc#L669-L673
(where "none" provides the option to ignore the default set on the interface)

and the static entry can set it's own (or drop back to default in the zone) using:
https://github.com/opnsense/core/blob/master/src/etc/inc/services.inc#L892-L894

**Comment by Addy90** [comment]
Well I have set in my DHCPv4 main settings page a gateway (to let's say 192.168.0.1) and I want to override this behavior for a static lease to "none". This is currently unsupported because on the edit page (which is called for static leases, I mean the plus at the bottom of the page), the "none" is no valid input but only on the main page it is a valid value (but there, I have a gateway set).

Perhaps I can try to make a pull request when I have some time left... do you understand what I mean, so far? Set a gateway on the main page (which is valid for all static leases that do not override it) and override the gateway to none for some / a single static lease.

**Comment by AdSchellevis** [comment]
I see you're point, it just doesn't appear to work that way. the "none" in the general page prevents the system from sending a gateway, not sending a gateway in the host overwrite automatically falls back to the pool. 
If it's possible to configure, you probably should digg into the dhcpd documentation.

**Comment by Addy90** [comment]
Thank you @AdSchellevis, now I understood why this is not working as I expected it to do.
While searching through the documentation, it is indeed not possible to overwrite already set options, but one is able to set an option to a value that is "invalid".
So what works is to set the gateway in the static lease to the network address. As this is an invalid address, the option is ignored and no gateway is sent. Now my client works as expected, it only gets one default route and has access to both networks with it's way out to only one node.

Nevertheless, this is a hack. It works great, there is no complaint of any software, but I think that this should have a safe way. Nevertheless, I understand now that this is no issue of OPNsense but if the isc-dhcp-server. Totally agree, thanks for your help!
