### ISSUE TITLE
Diagnostic page to check firewall aliases?

### ISSUE THREAD

**Issue by C-Duv** [opnsense/core#2588]
Hello,

Would a page that allows to check which aliases matches a given input be interesting?

A simple page with 2 fields such as:
* Input type: Dropdown with *IP address*, *port number*, *URL* possible values
* Input value: Text field

On submission, all defined aliases would be tested to see which matches the given input.

Example:

* Defined alias:
  * Network: PRIVATE_NET_FOO = *192.168.0.0/16*
  * Network: PRIVATE_NET_BAR = *192.168.5.0/24*
  * Host: MY_HOST_BAZ = *192.168.5.42*
  * URL: MY_HOST_LIST_BAX = (an URL pointing to a file containing *192.168.5.32/28* and other lines)
* Diagnostic page inputs:
  * Type: *IP address*
  * Value: *192.168.5.42*
* Diagnostic page results:
> The given IP address *192.168.5.42* matches the following aliases:
> * PRIVATE_NET_FOO (network: 192.168.0.0/16)
> * PRIVATE_NET_BAR (network: 192.168.5.0/24)
> * MY_HOST_BAZ (host: 192.168.5.42)
> * MY_HOST_LIST_BAX (url: the URL)

**Comment by AdSchellevis** [comment]
@C-Duv are you planning to work on it? if so, it might be a good idea to integrate the pfTables functionality with the search function.

**Comment by C-Duv** [comment]
I could give it a try and open a PR, I still need to understand how to run/check my OPNsense code.

What do you mean by "integrating the pfTables functionality"?

**Comment by AdSchellevis** [comment]
the `pfTables`  page [Firewall -> Diagnostics -> pFtables] shows the contents of an alias, using pf, which is where all valid firewall aliases live (including the parsed url ones)

**Comment by C-Duv** [comment]
Oh, right, the *pFtables* page is a close feature that I could start from, simply adding a search/filter function.
(I had forgotten this page)

**Comment by AdSchellevis** [comment]
closed with https://github.com/opnsense/core/pull/2977
