### ISSUE TITLE
Wrong user / password after upgrade to 18.7

### ISSUE THREAD

**Issue by abplfab** [opnsense/core#2593]
On one system (VM on proxmox), in transparent firewall mode: After upgrading to 18.7 root user can't login to the GUI nor by SSH. Restored 18.1.13 and created an "admin" user (and added to admin group) before upgrade gives the same error after upgrade to 18.7: unable to login to the GUI or by SSH.
Also tried upgrade by console: same problem. No errors shown during upgrade...

**Comment by fichtner** [comment]
https://forum.opnsense.org/index.php?topic=9284.0

**Comment by abplfab** [comment]
Thanks.
