### ISSUE TITLE
Support for WireGuard?

### ISSUE THREAD

**Issue by module0x90** [opnsense/core#2594]
Hi,

I just read that WireGuard is about this be added to the Linux Kernel. Checking their website https://www.wireguard.com/ shows that it already supports quite a number of operating systems, FreeBSD as well.
Their setup guide on https://www.wireguard.com/quickstart/ looks quite daunting - how easy it is to
setup a tunnel :-)
Your OpenVPN implementation works for me, but my gut feeling tells me this is a good new product on the horizon worth supporting and implementing maybe - hopefully?

Regards

Thomas

**Comment by fichtner** [comment]
Hi Thomas,

    # pkg install wireguard

;)

A plugin is being discussed, but will not happen as long as wireguard considers itself "alpha software".

Cheers,
Franco

**Comment by fichtner** [comment]
Yeah, updates in OPNsense for the package arrive in steadily via FreeBSD. I'll close this ticket. The time to discuss a plugin has not yet come. :)
