### ISSUE TITLE
Firewall log widget (6 columns view problem)

### ISSUE THREAD

**Issue by opnsenseuser** [opnsense/core#2595]
don´t know if im right here but this is what i get if i switch to 6 columns . the firewall log widget view is not perfect! Its the same problem on all themes. even the main theme of opnsense has this problem.

![grafik](https://user-images.githubusercontent.com/34602360/43529806-5a635ebc-95ac-11e8-9b9b-70596b0b2dbf.png)

**Comment by fichtner** [comment]
Yeah, this is a general CSS problem with the tables used that force the overflow. Diffs are less prone to this, but it's too much work to go through all static pages and fix it (the .php files also have this defect when screen space is rare). There used to be tickets for this, e.g. https://github.com/opnsense/core/issues/1003

**Comment by fichtner** [comment]
I agree. I have no time to work on this, unfortunately.

**Comment by opnsenseuser** [comment]
can you tell me which file is responsible for this widget. then at least I can see if I can improve it myself somehow.

**Comment by fichtner** [comment]
It's this file: https://github.com/opnsense/core/blob/master/src/www/widgets/widgets/system_log.widget.php

**Comment by opnsenseuser** [comment]
it was easier than I thought.

![grafik](https://user-images.githubusercontent.com/34602360/43534585-0589a25a-95b8-11e8-9533-4815ee6076f0.png)

6 columns now look like this

![grafik](https://user-images.githubusercontent.com/34602360/43534692-4a1064cc-95b8-11e8-9e67-a55706cc8da1.png)

**Comment by opnsenseuser** [comment]
It still wouldn´t be totally perfect, but much better adapted to 6 columns. it would at least have fewer presentation problems and would not be completely moved immediately. i tested all columns options. had no problems at all. 
@franco what do you think?

**Comment by fichtner** [comment]
That only works for 6 column layout :/

The problem is that tables overflow the div containers.

How about this?

    .dashboard_grid_column {
      table-layout: fixed;
    }

**Comment by fichtner** [comment]
If you squeeze it to tight it looks bad too, but where there's no space there's no grace.

<img width="211" alt="screen shot 2018-08-01 at 6 46 24 pm" src="https://user-images.githubusercontent.com/1915288/43535899-70c842f8-95bb-11e8-9aec-6cc0fdea8b05.png">

**Comment by fichtner** [comment]
sorry I tested with table { ...  } but that affects other pages so we need to fix tables within dashboard_grid_column, not just that class

**Comment by opnsenseuser** [comment]
yes, this solution is only for the 6 columns issue. 

in the 6 columns view it is also worst distorted. in the other views, one can still live with it, since most use a monitor with a resolution of 1920x1080. but on this resolution and beyond, the 6 columns view is really awful. unless you change this view to 20%. then it is in the 6 columns view is even better or at least as good as in 1,2,3 and 4 and that would be at least an improvement.

**Comment by opnsenseuser** [comment]
yes we have to test this. i need a test-team! Maybe the rebellion team can test this.
It's kind of bad for me to look at pfsense and see that everything looks perfect. it would be a pity if we could not do that too. shame about the whole perfect interior if the packaging does not have the same quality.

**Comment by fichtner** [comment]
It's boring to work on a perfect product, but that's just my view. ;)

**Comment by opnsenseuser** [comment]
:-)

**Comment by opnsenseuser** [comment]
deleted browser cache -> after I set .col-md-2 to 20%, I've gone through all the serives, reporting, free wall and so on and could not find a problem somewhere where it comes to presentation problems. but of course we have to test that much more effectively!

**Comment by fichtner** [comment]
Err, hold on now. I'm not sure how col-md-2 at 20% makes any sense whatsoever: if you say 6 column layout but set it to 20% which is 5 times to 100% which is 5 columns in your screenshot. Of course 5 columns has more space for the table contents than 6...

https://github.com/opnsense/core/blob/master/src/opnsense/www/themes/opnsense/build/css/main.css#L2200

**Comment by opnsenseuser** [comment]
I did a pr with your changes for tukan and cicada too.

**Comment by opnsenseuser** [comment]
Maybe we should tie the 6 columns option to the new sidebar. So the 6 columns are only selectable if you have activated the new sidebar. this is just an idea but would offer for presentation problems and monitor resolution.
