### ISSUE TITLE
18.7 release - sidebar problem

### ISSUE THREAD

**Issue by opnsenseuser** [opnsense/core#2596]
I think it was already mentioned but I would like to point out again that while the sidebar is included in the new themes, it does not work as it should.

3 problems:

1.	You can not set the sidebar as default. at least the firewall does not notice it.

2.	If you click on a link, the sidebar jumps back to the old sidebar and the toogle button points to the right. the toggle button pointing to the right would be correct, but then the sidebar may not switch to the old sidebar.
 
![grafik](https://user-images.githubusercontent.com/34602360/43539044-04275f54-95c4-11e8-84b0-34f61a20c828.png)

3.    sometimes the toggle button disappears completely. when exactly, I could not determine yet.

![grafik](https://user-images.githubusercontent.com/34602360/43539051-09a1efd0-95c4-11e8-9f68-18c11aa12537.png)

**Comment by opnsenseuser** [comment]
unfortunately I do not know myself with asp and mvc as already discussed. but I am available for help with solutions available.

**Comment by fichtner** [comment]
I've collected TODOs here https://github.com/opnsense/core/issues/2554

**Comment by opnsenseuser** [comment]
Thx for the Info 

Regards,
Rene

Mittwoch, 1. August 2018, 20:01 +0200 von notifications@github.com  <notifications@github.com>:

**Comment by opnsenseuser** [comment]
Maybe we should tie the 6 columns option to the new sidebar. So the 6 columns are only selectable if you have activated the new sidebar. this is just an idea but would offer for presentation problems and monitor resolution.

**Comment by opnsenseuser** [comment]
I've found that the problem with the disappearance of the toogle button only occurs in reporting (Health, Inside, Netflow).
Furthermore, I have found that the Graifk does not go all the way through the screen if you have enabled the sidebar. See my screenshot!

![grafik](https://user-images.githubusercontent.com/34602360/43676676-f08f597c-97f5-11e8-952d-88d93ba400e3.png)

**Comment by fichtner** [comment]
The collapse/expand button is reversed on the MVC pages by default. Not sure why. When you click it it thinks it collapses so the expand button disappears as per its javascript.

I'm also seeing this in Chrome:

<img width="326" alt="screen shot 2018-08-04 at 3 34 08 pm" src="https://user-images.githubusercontent.com/1915288/43677075-7d2b2f86-97fc-11e8-8fbf-9805b0b0d2df.png">

**Comment by fichtner** [comment]
Found the MVC thing: my mistake while converting glyphicon to fontawesome, see 
881ab33

**Comment by fichtner** [comment]
Closing in favour of keeping track in #2554
