### ISSUE TITLE
18.7 captive portal and vouchers doesn't work

### ISSUE THREAD

**Issue by rantwolf** [opnsense/core#2597]
Hi.
After upgrading to 18.7 my exisiting vouchers are gone...
OK. Now when I'm creating new vouchers I get the *.csv for download.
But the list is still empty.
After this checkup I deleted the voucher server and created a new one.
But still doesn't work.

Is there a log file int the cli for the voucher server?

**Comment by fichtner** [comment]
Sounds like the database was damaged. I'm not sure what is where, maybe @AdSchellevis has a bit of time to explain.

**Comment by frank499** [comment]
I have exactly the same problem. It started after upgrading from 18.1.11 to 18.1.13. I tried to track down the changes and apparently the problem is related to https://github.com/opnsense/core/commit/fbca4bf4cc36a9dff4d89d9564cb595de92d6be1
For 18.1.13 reverting the changes make the vouches visible again.

**Comment by fichtner** [comment]
@frank499 thanks for pinning this down, officially handing this over now

**Comment by AdSchellevis** [comment]
at my end the vouchers look normal 
![image](https://user-images.githubusercontent.com/9783985/43609471-638c99ec-96a4-11e8-8b2b-27510078f213.png)

@frank499 If this page is empty on your end, could you gather some network responses from the webbrowser? maybe one of the endpoints fails in some scenario.

**Comment by rantwolf** [comment]
Soo.
I played around with the voucher server.
Yesterday I told you that I deleted my old and created a new voucher server and nothing works.
Today I created a new server again but now with another name of the server.
Now I'm a surprised... it works fine.
![bildschirmfoto 2018-08-03 um 00 13 44](https://user-images.githubusercontent.com/39314130/43614183-acb68502-96b2-11e8-8075-8e22e8de0e0d.png)

**Comment by AdSchellevis** [comment]
@advcron same question, when inspecting the network traffic in your browser, are there failed requests, if so, what does the response look like.

**Comment by advcron** [comment]
Sorry but how can I " inspecting the network traffic in your browser" ?

**Comment by advcron** [comment]
When I enter to voucher menu:
![0](https://user-images.githubusercontent.com/38749228/43630218-eebeedd4-96ff-11e8-9cc6-1cbaedd18b06.PNG)
When I click generate voucher:
![1](https://user-images.githubusercontent.com/38749228/43630219-eede93dc-96ff-11e8-9464-7dfe34cae995.PNG)

**Comment by AdSchellevis** [comment]
@advcron ok, got it, can you try to add a voucher group without a space in it? I'm guessing that's the issue.

**Comment by advcron** [comment]
There isnn't any space in voucher gorup
![3](https://user-images.githubusercontent.com/38749228/43631795-80c41250-9704-11e8-8726-cb31e5fe960f.PNG)

**Comment by AdSchellevis** [comment]
"Capative Voucher"?

**Comment by AdSchellevis** [comment]
I can reproduce this here, no further actions needed.

**Comment by advcron** [comment]
This is it !!! 
It works on 18.1.13 and 18.7. 

**Thank you very much!**

**Comment by AdSchellevis** [comment]
@advcron I'm still going to fix the issue, it should work with the space in between

**Comment by peysche** [comment]
Hi, 

 Could it be that there is an similar issue when you use ä,ö,ü in the groupnames?

Since i addet a groupname with some umlauts, i see also no vouchers for this group, and the login page does not apere on the devices...

Thx
Paul

**Comment by peysche** [comment]
After up to 18.1 also umlauts ar working in groupnames

**Comment by AdSchellevis** [comment]
@peysche have you even tried the supplied patch?

**Comment by peysche** [comment]
hi, yes latest release fixes the problem!

thx 
paul
