### ISSUE TITLE
Netflow error after update to 18.7

### ISSUE THREAD

**Issue by pepper77** [opnsense/core#2598]
I just updated from 18.1.13 to 18.7, and everything seems to work OK except Netflow-gathering. After the update the netflow configuration show all interfaces on both "LAN interfaces" and "WAN interfaces", and I couldn't change this. I tried to press "Clear all" and "Apply", then I lost network communication with the firewall and had access the console directly on the computer to do a reboot. After the reboot the firewall seems to work again, but now I have no interfaces in "LAN interfaces" and "WAN interfaces", and when I try to choose interfaces, nothing shows up. Netflow gathering is also not working. See attached screenshot of web-UI.
<img width="1061" alt="screen shot 2018-08-02 at 11 10 33" src="https://user-images.githubusercontent.com/973298/43575046-122cea74-9646-11e8-8bbc-6744eef632b7.png">

**Comment by pepper77** [comment]
Thanks! That fixed the problem. :-)

**Comment by fichtner** [comment]
Yay, you're welcome :)
