### ISSUE TITLE
Implement proxy feature

### ISSUE THREAD

**Issue by AdSchellevis** [opnsense/core#26]
Implement proxy feature into OPNsense

**Comment by StopTrain** [comment]
Not sure I want to see a proxy added into core... maybe as some sort of plugin or addon module?  I specifically went to opensense because it didn't have the add on proxy that most others have.  Just my two cents :)

**Comment by AdSchellevis** [comment]
It will be a standard feature in 15.7, but disabled by default. For this release we're not planning user installable packages but aim to support the most common features in the product. Our development framework will probably support custom features in the future, for more information on (the progress) of our architecture visit: 

https://wiki.opnsense.org/index.php/Develop:Architecture

**Comment by StopTrain** [comment]
That sounds great actually.  I could possibly find a use for a proxy.  I guess i misunderstood :)

**Comment by AdSchellevis** [comment]
implemented in 15.1.10.2
