### ISSUE TITLE
dhcpd broken after update to OPNsense 15.7.2-amd64 

### ISSUE THREAD

**Issue by ortylp** [opnsense/core#260]
the error in /var/log/dhcpd/log is:
no such user: dhcpd

**Comment by fichtner** [comment]
Upgrading from 15.1.x? Using /var MFS? See https://forum.opnsense.org/index.php?topic=850.0

Please close if that thread helps, otherwise we'll need more info.

**Comment by ortylp** [comment]
This manual workaround fixed the issue.

**Comment by fichtner** [comment]
Sorry about the trouble!

**Comment by ortylp** [comment]
At least the support was fast ;)

**Comment by srvg** [comment]
Doing a ` /usr/local/etc/rc.recover ` re-added the dhcp user for me and solved this problem.
I am currently running `OPNsense 15.7.7_1-amd64 `

**Comment by srvg** [comment]
An hour later dhcpd crashed again with the same problem. Recover solved it again.
I think there is something deeper going on here.

**Comment by fichtner** [comment]
15.7.7_1 comes from 15.7 images, which had a defect, at least for nano images. Which image type are you running, why are you not on 15.7.11?

A guide on how to fix the early nano image was provided with 15.7.1: https://forum.opnsense.org/index.php?topic=915.0
