### ISSUE TITLE
18.7: Captive Portal sessions cannot be disconnected

### ISSUE THREAD

**Issue by patcsy88** [opnsense/core#2606]
Hi,

I just updated to 18.7 and my sessions in Captive Portal cannot be 'deleted'. I used the command line to try and do the same configctl captiveportal disconnect [session_id] and I get the error "terminateCause UNKNOWN".

**Comment by AdSchellevis** [comment]
It should be:
```
configctl captiveportal disconnect [zoneid] [session_id]
```

unknown means it can't find the session.

**Comment by patcsy88** [comment]
Hi,

I have managed to delete all the stale sessions using sqlite3 directly on the captiveportal.sqlite file. All is well now! Many thanks.

**Comment by patcsy88** [comment]
Login in today I now observe that the 'stale' sessions are again showing under Service/Captive Portal/Sessions. Deleting them from the WebUI does nothing (for a brief moment I can see the sessionid). configctl captiveportal disconnect [zoneid] [session_id] throws the same error as before

root@OPNsense:/var/captiveportal # configctl captiveportal disconnect 0 hznhd6esOsLPpqj+YLce0A==
terminateCause UNKNOWN

So a couple of questions:-
1. How it is that I had deleted it from sqlite3 that the stale sessions are back?
2. How do i disconnect it once and for all?

Best,
Patrick

**Comment by AdSchellevis** [comment]
Maybe a corrupted disk or database? hard to tell without additional logs available.

**Comment by patcsy88** [comment]
How should I go about making the logging more verbose and where would the relevant logs be kept?

**Comment by AdSchellevis** [comment]
![image](https://user-images.githubusercontent.com/9783985/43719788-f4727cd2-998e-11e8-83ea-c458de034605.png)
general and configd are usually the most interesting ones

**Comment by patcsy88** [comment]
configd seem to have a few entries from last evening after I deleted the stale sessions from captiveportal.sqlite in /var/captiveportal.


Aug 5 21:59:26 | configd.py: [0ba7faef-c26a-4982-af9e-d5140256aaf3] restarting captiveportal services
-- | --
Aug 5 21:59:26 | configd.py: OPNsense/Captiveportal generated //var/etc/lighttpd-cp-zone-0.conf
Aug 5 21:59:26 | configd.py: OPNsense/Captiveportal generated //etc/rc.conf.d/captiveportal
Aug 5 21:59:26 | configd.py: OPNsense/Captiveportal generated //usr/local/etc/captiveportal.conf
Aug 5 21:59:26 | configd.py: OPNsense/Captiveportal generated //var/etc/lighttpd-api-dispatcher.conf
Aug 5 21:59:24 | configd.py: generate template container OPNsense/Captiveportal
Aug 5 21:59:21 | configd.py: [ce3011fc-9b7e-460b-b85a-193d9667db1e] generate template OPNsense/Captiveportal
Aug 5 21:56:07 | configd.py: [4f0a6423-9163-4a26-8d41-41c1779c5ecf] stopping captiveportal services
Aug 5 21:56:07 | configd.py: OPNsense/Captiveportal generated //var/etc/lighttpd-cp-zone-0.conf
Aug 5 21:56:07 | configd.py: OPNsense/Captiveportal generated //etc/rc.conf.d/captiveportal
Aug 5 21:56:07 | configd.py: OPNsense/Captiveportal generated //usr/local/etc/captiveportal.conf
Aug 5 21:56:07 | configd.py: OPNsense/Captiveportal generated //var/etc/lighttpd-api-dispatcher.conf

Is it possible that a restore takes place from somewhere when I restarted the service along with a backup of the sessions?

**Comment by AdSchellevis** [comment]
as long as you're not using a ramdisk there shouldn't be a restore.

**Comment by patcsy88** [comment]
I do not believe so. I am running on an APU2 from PCEngines with an mSATA SSD. mount does not suggest I have a RAM disk. Forgive my ignorance but how do i check if I have a RAM disk? Also I have found an exact copy of captiveportal.sqlite in /conf which contains the same stale sessions.

**Comment by fichtner** [comment]
issuing a lone "reboot" will skip pre-shutdown backup and the subsequent bootup will restore the old database.

(modify database)

# rm /conf/captiveportal.sqlite

(reboot)

.....

or us a GUI reboot which will back up your changes so this doesn't happen.

**Comment by patcsy88** [comment]
Ok many thanks. I will try this over the next day and report back if the problem is addressed.
