### ISSUE TITLE
Nextcloud backup failed: config[55710]: cannot execute PUT

### ISSUE THREAD

**Issue by pmasterc3** [opnsense/core#2607]
I tried to use the new nextcloud backup feature of Opnsense on my Nextcloud server. I seems that the login on server side is successful (Nextcloud logs & lighttpd logs) however a 207 is returned by the server.
Looking at the php code I found 

    "$url/remote.php/dav/files/$username$directory",

in core/src/opnsense/mvc/app/library/OPNsense/Backup/Nextcloud.php .

However, on my Nextcloud installation (I did several upgrades starting from Owncloud 6), the webdav path is remote.php/**webdav**. 

I guess an option to configure that (dev vs. webdav) is needed.

**Comment by curana** [comment]
The documentation of Nextcloud says it's "/dav/".

**Comment by fabianfrz** [comment]
@curana no, webdav is correct:

https://docs.nextcloud.com/server/13/user_manual/files/access_webdav.html

**Comment by pmasterc3** [comment]
Well, in my case Nextcloud says _$DOMAIN/remote.php/webdav/_ as webdav path. As mentioned above, I did quite some updates since Owncloud ~6. So I guess that /dav/ is only valid for recent newly installed Nextcloud versions.

**Comment by fabianfrz** [comment]
@pmasterc3 you are wrong. Both endponts exist - the one I am using is *just not displayed* in the GUI.

The really likely solution for your issue is fix your webserver or permissions.

**Comment by anthony-wang** [comment]
@fabianfrz sorry to dig up such an old issue, but I am encountering the same issue reported by @pmasterc3.

More specifically, I wanted to set up the automated Nextcloud backup to TU Berlin's [tubCloud](https://www.campusmanagement.tu-berlin.de/menue/dienste/daten_server/tubcloud/tubcloud_webdav/).

If I access `https://tubcloud.tu-berlin.de/remote.php/webdav/$username` it shows me a message

> This is the WebDAV interface. It can only be accessed by WebDAV clients such as the Nextcloud desktop sync client.

but if I access `https://tubcloud.tu-berlin.de/remote.php/dav/$username` then I get a "Not found" error. 

It seems therefore that the `/dav` interface has been disabled? Is there therefore a way to set a custom URL for the request?

Thanks!

**Comment by fabianfrz** [comment]
$username has to be substituted by your nextcloud username if you want to try it and you need to use the PROPFIND method. Otherwise it will not work.

There is probably something wrong with your installation as I get an error that the authentication failed even when I try to login with an invalid username, which is asking for username and password using basic auth:

![grafik](https://user-images.githubusercontent.com/3713914/54852856-63b14480-4cee-11e9-9a7a-93c7c1382cf2.png)
