### ISSUE TITLE
Add a password selection when exporting user certificates.

### ISSUE THREAD

**Issue by FGTgb** [opnsense/core#2609]
Currently, exported .p12 file is not password protected.
This is not secure when you'd like to distribute a certificate to a user.

Discussed in the forum:
https://forum.opnsense.org/index.php?topic=8762.new;topicseen#new

**Comment by FGTgb** [comment]
Ok sorry, I didn't know there was already an entry for that request.
I just followed the suggestion from the forum.
You can close this duplicate request.

**Comment by fichtner** [comment]
Reopened #1475, closing this one.
