### ISSUE TITLE
Disabling/Removing a gateway that is member of a gateway group is preventing editing of the gateway group

### ISSUE THREAD

**Issue by simplerezo** [opnsense/core#2613]
Hi

If you have a gateway group and you are disabling a member, editing gateway group does not permitting you to change members (nothing is displayed in "Gateway Priority" section).

Regards

**Comment by fichtner** [comment]
I can't reproduce this on the latest development version. When I disable it will disappear from the Gateway Group. If I try to delete it says "Gateway 'ANOTHER_GW' cannot be deleted because it is in use on Gateway Group 'GWGNAME'".
