### ISSUE TITLE
Cannot give access to "Services: Unbound DNS: Overrides"

### ISSUE THREAD

**Issue by nikaro** [opnsense/core#2617]
Hello,

I created a user in the local database, and gave him the "Services: Unbound DNS: Edit Host" privilege.
Then i have 2 issues:

* First the Unbound item does not show up in the menu. And even if i check all Unbound related privileges for this user, "Unbound: Overrides" still does not show up.
* Second, if i go directly on https://router.ubicast.net:8443/services_unbound_overrides.php it redirects me on https://router.ubicast.net:8443/services_unbound_host_edit.php so thu user cannot see/edit the existing overrides.

Thank you for your help.

**Comment by fichtner** [comment]
Hi @nikaro,

Thanks for the report. Looks like there are multiple oddities in the ACL setup. This patch will help:

    # opnsense-patch  c313826


Cheers,
Franco

[1] https://github.com/opnsense/core/commit/c3138260e0465603a10af4b8d6cf00dde6bab039

**Comment by nikaro** [comment]
I confirm that it works. Thank you very much.

PS: very nice this `opnsense-patch` thing.

**Comment by fichtner** [comment]
Thanks for confirming. I'll have this shipped in 18.7.1 next week :)


Cheers,
Franco
