### ISSUE TITLE
problem in ipsec widget

### ISSUE THREAD

**Issue by fabianfrz** [opnsense/core#262]
Error message

Fatal error: Cannot redeclare display_widget_tabs() (previously declared in /usr/local/www/guiconfig.inc:668) in /usr/local/www/widgets/widgets/ipsec.widget.php on line 65 

Possible fix: Check if the function is already defined or prefix the function name

**Comment by fichtner** [comment]
Was fixed in 2480cd39206ce4b39eb but is not yet merged into stable

**Comment by fichtner** [comment]
Fix was part of 15.7.4.
