### ISSUE TITLE
Help wanted: routing of IPSec IKE packets with BGP

### ISSUE THREAD

**Issue by clystron** [opnsense/core#2623]
OPNsense 18.1.13 with BGP setup (2 peers) and several IPSec tunnels, the preferred peer failed and BGP switched the default gateway to the seconday one, so far so good. Most services were not interrupted but the IPSec tunnels all stayed down, I checked the log and found that the firewall received IKE packets and logged "sending packet..." but a quick tcpdump on the WAN interface reveiled that not a single IKE packet was actually sent out so the tunnels could not be established. Ping and traceroute worked just fine on the IPSec peers and showed that the secondary gateway was used as expected.

I played around with "Connection method" settings, disabled IPSec completely several times and even tried to configure a static default gateway because the preferred peer will be down for a while but nothing really helped. One of the tunnels would come up sometimes but no chance to get all of them up consistently.

Finally they are all up now but I have no real clue why, the last one came up right after I deleted its IKE state from the firewall state table. I know thats not much to go on but maybe someone can explain to me how IPSec decides where to send its Packets because to me it almost looks like it was trying to use the down gateway and since that ARP entry expired it could not send out anything.

Update: all the tunnels went down again once the tried to re-key and dropping their IKE/ESP states really seems to help bringing them back up again but I have no idea why.

any thoughts?

**Comment by clystron** [comment]
Update: I have now changed the IPSec settings to "Respond only" and "Disable rekeying" which basically means that all IKE communication is initiated by the IPSec peers and that helps a lot. Before that OPNsense would initiate a re-keying after 3000sec and that would kill the tunnel because it did not work. Now that the other side initiates the re-keying (~ every 3300sec) its OK.

**Comment by clystron** [comment]
Update: it would appear that the problem was/is that the automatic FW-rules created by IPSec contain a "route-to"/"reply-to" part that is not updated when the default gateway changes so every packet that matches those rules is effectively "lost". It works in "passive mode" because there is also a user-rule that allows incomming IKE-traffic and that does not have a gateway in it. I have now disabled the automatic rules and will re-test the failover when its convenient.

**Comment by AdSchellevis** [comment]
@clystron you can disable automatic ipsec rules in `VPN->IPsec->Advanced Settings->Disable all auto-added VPN rules.`

**Comment by clystron** [comment]
Thanks, thats what I did eventually, now just need to find a good time to re-test.
I also checked the rules-table for any more "sneaky" entries with gateways attached and there do not seem to be any more.
