### ISSUE TITLE
New Sidebar -> on viewport height resize (lower then 669px)  -> do not switch back!

### ISSUE THREAD

**Issue by opnsenseuser** [opnsense/core#2628]
When I programmed the new sidebar I wanted to make sure that the new sidebar is only displayed if the viewport has at least the height of the new sidebar. in this case 669px. so in javascript I did a query checking the height and in case the viewport height is less than 669px it automatically switches to the old sidebar and the toogle button in the header disappears. This guarantees that you can scroll again, since the new sidebar has no scroll function and you can´t switch back to the new sidebar as long as your viewport is lower then 669px. the toogle switch appears again if the viewport hight is higher then 669px.

Now I noticed that the switch works on resizing the viewport to less then 669px, but if you then click on a link, is switched back to the new sidebar, since the session was saved before. 
Here it would be useful to save the session storage on the old sidebar as long as the height is less than 669px.

Here is the source code to understand what I mean.

![grafik](https://user-images.githubusercontent.com/34602360/43999407-18057a74-9e0c-11e8-85f6-38ad79faa623.png)

**Comment by fichtner** [comment]
@opnsenseuser db50af0 works nicely for me.
