### ISSUE TITLE
State table problem afer reboot

### ISSUE THREAD

**Issue by MaartenJB** [opnsense/core#2631]
Hi,

I have 2 routers connected over openvpn. I use policy routing to route the subnets. If I run a ping from one host to a host on the other network and then reboot the router, at boot the router creates a wrong state and the ping will not come back.

This happens probably because the host is still pinging and the vpn is not yet online. It is not always the case, but, when I have 3 pings to separate hosts, usually 1 or 2 do not reply untill I do a State table reset.

Best regards,

Maarten

OPNsense 18.1.13-amd64
FreeBSD 11.1-RELEASE-p11
OpenSSL 1.0.2o 27 Mar 2018

**Comment by AdSchellevis** [comment]
timeout (probably a support case).
