### ISSUE TITLE
monit: Allow source address to be specified for Ping check

### ISSUE THREAD

**Issue by ruffy91** [opnsense/core#2632]
I want to ping the remote firewall on a IPsec tunnel.
I need to specify a source address as it is not possible to ping directly from one firewall to another over IPsec (opnsense/core#1624)

**Comment by fbrendel** [comment]
You can add the source address to the ping test as described in the [Monit Documentation](https://mmonit.com/monit/documentation/monit.html#NETWORK-PING-TEST).

Example with 10.0.1.1 as source address:

_Service Test Setting_
Name: **Ping**
Condition: **failed ping address 10.0.1.1**
Action: **Alert**

_Service Setting_
Name: **SophosUTM**
Type: **Remote Host**
Address: **10.0.2.1**
Tests: **Ping**

**Comment by ruffy91** [comment]
Thank you. I can now ping the remote gateway of the IPsec tunnel.
Got it to work so the IPsec tunnel automatically starts if the remote firewall restarts.
