### ISSUE TITLE
Feature Request: 1:1 NAT using a WAN with DHCP (Not Static)

### ISSUE THREAD

**Issue by marjohn56** [opnsense/core#2634]
Forum user requesting this, he as two dhcp WAN addresses and wants to use one of them for 1:1 NAT. He can only enter a static address.

Would it be possible to use an alias here so as to track the WAN address and adjust accordingly?

**Comment by AdSchellevis** [comment]
two addresses sounds a bit odd, but that maybe besides the point.

What's the use case for this? and how should it work?

**Comment by marjohn56** [comment]
Erm.. I believe it's two WAN interfaces, not two addresses on one interface. :)

**Comment by AdSchellevis** [comment]
ok, and want to forward all traffic to the current public ip to a single host in the local network?

**Comment by marjohn56** [comment]
Yup.. the same as a static address.

**Comment by marjohn56** [comment]
I never realised you couldn't do it till I tried.

**Comment by AdSchellevis** [comment]
you should be able to use a portforward, just select any and the wan address as destination

**Comment by marjohn56** [comment]
But wont you need the same on the outbound too?.

**Comment by marjohn56** [comment]
Sorry I meant inbound

**Comment by marjohn56** [comment]
Just be nice to do it with 1:1 was my thinking,

**Comment by AdSchellevis** [comment]
it doesn't do anything else then a port forward in this case, the 1:1 option is mainly useful if you need to map ranges.

**Comment by AdSchellevis** [comment]
fixed one minor glitch on the port forward page https://github.com/opnsense/core/commit/ee98ebb29e89686fea75ac689ba2f0e6c75ce89e while looking at this one.

**Comment by marjohn56** [comment]
True, but you only need to make one entry rather than two.

**Comment by AdSchellevis** [comment]
I'm not sure what you mean, as far as I know the user can already reach his goal with the functionality integrated.

**Comment by marjohn56** [comment]
Yes he can, It's just a case of making it stupidly simple. :)
