### ISSUE TITLE
captive-portal-lighttpd not starting after upgrade 18.7 -> 18.7.1

### ISSUE THREAD

**Issue by Mad-Onion** [opnsense/core#2638]
After upgrading OPNsense from 18.7 to 18.7.1 the captive portal's landingpage is not working anymore. When I try to connect to the internet via cp, I just receive a connection timeout instead of being redirected to the landingpage. If I add the mac to the whitelist, everything works as expected -> no network / firewall issue.
In the cp's logfile I found this entry, with the timestamp from around the upgrade:
```
config[1147]: failed migrating from version 0.0.0 to 1.0.0 in OPNsense\Firewall\Alias [skipping step]
```
In the sockets-overview in Firewall/Diagnostics/Sockets I don't see any lighttpd-process on port 8000, but System/Diagnostics/Activity states that the cp-background-job is running:
```
7149 | root | 52 | 0 | 99396K | 22144K | select | 3 | 0:07 | 0.68% | /usr/local/bin/python2.7 /usr/local/opnsense/scripts/OPNsense/CaptivePortal/cp-background-process.py start
```

**Comment by fichtner** [comment]
thanks for finding this. it seems this will have to be hotfixed today.
