### ISSUE TITLE
port-alias with two ports disables outbound-nat-rule - 18.7

### ISSUE THREAD

**Issue by Mad-Onion** [opnsense/core#2639]
After upgrading from 18.1 to 18.7 my outgoing NAT-rule didn't work anymore. In the gui everything was fine but looking into `/tmp/rules.debug` I saw a "#" at the beginning of the corresponding rule's line.
I changed the parameters of the rule and discovered that the # appeared when I used  a port-alias containing the two port 80 and 443 as the destination-port. When I removed the alias and used a single port (80 or 443), the # disappears.

Thread: https://forum.opnsense.org/index.php?topic=9417.0

**Comment by fichtner** [comment]
Is this based on 18.7 or 18.7.1 ?

**Comment by Mad-Onion** [comment]
Was based on 18.7 and seems to be gone with 18.7.1! :-)

**Comment by fichtner** [comment]
Good. I'm working on a hotfix for your CP report. Should be up in an hour. Thanks for your reports. ❤️

**Comment by Mad-Onion** [comment]
You're welcome :-)
Thanks for the fast hotfix!
