### ISSUE TITLE
proxy: template issue with multiple interfaces?

### ISSUE THREAD

**Issue by fichtner** [opnsense/core#264]
Expected behaviour:

    http_port 192.168.1.1:3128
    http_port 192.168.3.1:3128

Actual behaviour:

    http_port 192.168.1.1:3128 http_port 192.168.3.1:3128

Resulting in "Bungled /usr/local/etc/squid/squid.conf line 6: http_port 192.168.1.1:3128 http_port 192.168.3.1:3128".

via: https://forum.opnsense.org/index.php?topic=1096.0

**Comment by AdSchellevis** [comment]
Fixed in https://github.com/opnsense/core/commit/a6f879fcdff23b40ea1546b8e0242bb7e1e225fe

**Comment by fichtner** [comment]
Also merged to stable, thanks for the quick response. :)
