### ISSUE TITLE
multiple admin-UIs behind port-forwarding / each logging out other sessions

### ISSUE THREAD

**Issue by Mad-Onion** [opnsense/core#2640]
I'm using multiple OPNsense-appliances (OS) which I manage in-band through a vpn-tunnel. To access them I connect through a port-forwarding on the vpn-endpoint on different ports.
```
                            ___________
to OS 1> ---[WAN-IP:1337]---| OS VPN  |===<to VPN-IP:443>===[OS 1]
to OS 2> ---[WAN-IP:1338]---| NATTING |===<to VPN-IP:443>===[OS 2]
to OS 3> ---[WAN-IP:1339]---|_________|===<to VPN-IP:443>===[OS 3]
```
I can access every appliance from the outside separately, but when I sign into the web-ui of appliance 2, i get signed out of appliance 1 and so on. I think this has to do with the session-cookies and the cookie-domain (WAN-IP of OS VPN), which is the same for all appliances.
Is there a way to change this behavior? Maybe use the appliance-hostname in the cookie-name to differentiate them?

**Comment by nallar** [comment]
You could work around the issue by setting up three hostnames for that IP and using a different one for each opnsense. Cookies are shared on the same domain regardless of port, but they aren't shared between different domains which point to the same IP.

**Comment by Mad-Onion** [comment]
@fichtner what about a appliance-specific cookie-name to distinguish between those appliance without the mentioned workaround using different hostnames?

**Comment by fichtner** [comment]
I'm not sure and I can't take a look in the next couple of weeks. CC @AdSchellevis

**Comment by Mad-Onion** [comment]
It's not that important, more a nice-to-have feature ;-)

**Comment by mimugmail** [comment]
Maybe Nginx or HAProxy is worth a try?

**Comment by fichtner** [comment]
Timeout.
