### ISSUE TITLE
OpenVPN CSOs not created when using Common Name

### ISSUE THREAD

**Issue by ashceryth** [opnsense/core#2641]
Hi folks,

I am using the feature "Use common name" together with user auth in OpenVPN server config and have added some CSOs in the GUI which match the CN of the client certificates. However, it seems that the CSO files are not generated by the `auth-user.php` script. If I interpreted the code correctly, I think this may be caused by the script expecting the username as the name of the CSO:

```php
...
if (!empty($all_cso[$vpnid][$username])) {
   $cso = $all_cso[$vpnid][$username];
} else {
   $cso = array("common_name" => $username);
}
...
```
Thanks!

**Comment by ashceryth** [comment]
I edited the lines mentioned above and replaced `$username` with `$common_name` and the CSO files get created as expected.

**Comment by AdSchellevis** [comment]
@ashceryth it looks like you're right, it should have been the `$common_name`, which is often equal to the username but not always as it appears.

**Comment by AdSchellevis** [comment]
@ashceryth thanks for the report, https://github.com/opnsense/core/commit/81d70d630a748135a9163e0668ae38060c2f4a8e should fix the issue

**Comment by ashceryth** [comment]
@AdSchellevis Thanks for the quick fix.

**Comment by AdSchellevis** [comment]
@ashceryth you're welcome, thanks for reporting it didn't come up in my testbed

**Comment by ashceryth** [comment]
@AdSchellevis Well, I think using the username as CN in the certificates is the most common variant. I prefer to use certificates bound to the client hostname, so that I don't have to change the certificates on all devices used by the user in case one of them is lost and I need to revoke the certificate. Another benefit is that I can use CSOs that apply to the machine not the user (for example the client IP). This way the user can use serveral device at the same time and I can assign different CSOs to every single one of them :)
