### ISSUE TITLE
Feature request: IPSec IKE phase 1 - IKE, IKEv2 or auto

### ISSUE THREAD

**Issue by trendchiller** [opnsense/core#2642]
in pfSense there is the possibility in IPSec phase 1 to select auto, IKE or IKEv2.
Would it be possible to implement the "auto feature" in opnSense, too ?
(as we were speaking about in twitter message)

**Comment by fichtner** [comment]
Sure, I'll take a look in September. Out of office for the next two weeks.

**Comment by AdSchellevis** [comment]
@fichtner I can pick this one, it only sets `keyexchange` and leaves the `aggressive ` tag in when configured

**Comment by fichtner** [comment]
it's yours ❤️

**Comment by AdSchellevis** [comment]
@trendchiller here you go https://github.com/opnsense/core/commit/b693a3b99a87d146a91b307b11b644e3fd2abe3d, can you test and confirm?

**Comment by trendchiller** [comment]
Setting up a fresh machine for production ;)

Am 17.08.2018 um 11:56 schrieb Ad Schellevis <notifications@github.com<mailto:notifications@github.com>>:


@trendchiller<https://github.com/trendchiller> here you go b693a3b<https://github.com/opnsense/core/commit/b693a3b99a87d146a91b307b11b644e3fd2abe3d>, can you test and confirm?

**Comment by trendchiller** [comment]
Yes...
Tool a bit longer due to serious problems at work, but tested by now and confirmed to work - thanks.

Am 17.08.2018 um 11:56 schrieb Ad Schellevis <notifications@github.com<mailto:notifications@github.com>>:


@trendchiller<https://github.com/trendchiller> here you go b693a3b<https://github.com/opnsense/core/commit/b693a3b99a87d146a91b307b11b644e3fd2abe3d>, can you test and confirm?

**Comment by AdSchellevis** [comment]
@trendchiller @mimugmail thanks for confirming!
