### ISSUE TITLE
Feature Request: Let's Encrypt DynDNS TSIG nsupdate script add

### ISSUE THREAD

**Issue by nforceroh** [opnsense/core#2646]
Not sure where this goes but here's what needs to be added to use Let's Encrypt DynDNS TSIG nsupdates using nsupdate. I just don't know enough about the inner workings to do the PR myself.
You can make the "nsupdate (RFC2136)" option work but a zone field that is your domain name managed by Dyndns needs to be added in the GUI or inserted in the script /usr/local/share/examples/acme.sh/dnsapi/dns_nsupdate.sh

My work around is to capture the domain name from the passed fqdn and add a zone statement in the nsupdate options
```
root@fw:/usr/local/share/examples/acme.sh/dnsapi # diff /usr/local/share/examples/acme.sh/dnsapi/dns_nsupdate.sh /usr/local/share/examples/acme.sh/dnsapi/dns_nsupdate.sh.orig
9d8
<   zone=`echo $1|egrep -o '[a-z]+\.[a-z]+$'`
16d14
< 
19c17
< zone ${zone}
---
> zone 
34d31
<   zone=`echo $1|egrep -o '[a-z]+\.[a-z]+$'`
40d36
< zone ${zone}
```
If you wanted to add the "DynDns TSIG nsupdates" option in the  validation method under DNS-01
the ${NSUPDATE_SERVER}" option needs to be set to  update.dyndns.com

the dns_nsupdate_add() function would look like
```
  nsupdate -k "${NSUPDATE_KEY}" <<EOF
server update.dyndns.com
zone ${zone}
update add ${fulldomain}. 60 in txt "${txtvalue}"
send
EOF
```
and the dns_nsupdate_rm function looks like
```
  nsupdate -k "${NSUPDATE_KEY}" <<EOF
server update.dyndns.com
zone ${zone}
update delete ${fulldomain}. txt
send
EOF
```

**Comment by AdSchellevis** [comment]
@nforceroh please open requests for plugins in our plugin repository here  https://github.com/opnsense/plugins/issues
