### ISSUE TITLE
System > Configuration > Backups > Nextcloud URL

### ISSUE THREAD

**Issue by joestafford** [opnsense/core#2647]
Hello!

I'd previously had issues trying to get nextcloud backups configured but kept getting a generic "Communication Error" when testing.  I finally spotted in the logs that I had an extra trailing forward slash in my URL which prevented connectivity.  May I suggest adding "rtrim" where appropriate to find and trim any trailing slashes?  If I remember I'm happy to look at it and do a PR with proposed changes.

**Comment by fabianfrz** [comment]
Sure, should not be hard to do ;)
