### ISSUE TITLE
Adding new interface overwrites LAN entry (German interface)

### ISSUE THREAD

**Issue by tk-wfischer** [opnsense/core#2652]
When a user removes the default lan interface and the user sets the interface language to German, he/she is not able to add multiple additional interfaces. Adding a new interface after removing the default lan interface leads to a new interface "LAN". Trying to add additional interfaces simply overwrites this "LAN" interface (no OPT* interfaces can be created any more).

I have tested this with OPNsense 18.1.?, 18.7, 18.7.1

Steps to reproduce:
1) /system_general.php (System -> Settings -> General) set language to German
2) /interfaces_assign.php (Schnittstellen -> Zuweisungen) Remove the LAN interface 
3) /interfaces_assign.php Add a new interface (it will be named "LAN")
4) /interfaces_assign.php Try to add another new interface - it is not possible. The former interface will be overwritten.
5) /diag_backup.php (System -> Konfiguration -> Sicherungen -> Konfiguration herunterladen), look at xml under "interfaces" -> the tag for lan is in CAPITAL LETTERS

Fix: remove the gettext function in line number 138 of interfaces_assign.php. I'll submit a pull request for this.

**Comment by AdSchellevis** [comment]
https://github.com/opnsense/core/commit/bf0b3f1acc06b250232e93c5d95600ce0ada1837
