### ISSUE TITLE
ipv6 cause webui lan only isn't working

### ISSUE THREAD

**Issue by bitdegree67** [opnsense/core#2654]
OPNsense version : `OPNsense 18.7.1_3 (amd64/LibreSSL)`

Problem : webui isn't starting when i select in "System: Settings: Administration:  Listen Interfaces" : LAN Only

i think it's because LAN IPv6 is tracking WAN IPv6.
i have this error in system.log
`
Aug 17 13:03:18 OPNsense opnsense: /usr/local/etc/rc.bootup: The command '/usr/local/sbin/lighttpd -f /var/etc/lighty-webConfigurator.conf' returned exit code '255', the output was '2018-08-17 13:03:18: (network.c.313) can't bind to socket: [2a01:cb10:2fe:8a00:f690:eaff:fe00:1fee]:443 Can't assign requested address'`

at reboot, webui isn't accessible from LAN. but if i restart all service (in shell) then the webui is working from LAN

**Comment by bitdegree67** [comment]
someone ?

**Comment by fichtner** [comment]
Try the development version as we have changed the way the feature works. Manual interface binding is error-prone in general and can lock you out hence the warning dialog...

**Comment by bitdegree67** [comment]
@fichtner i'm in production case and i can't use a development version. next stable version with this fix will be released soon ?

**Comment by fichtner** [comment]
not without feedback I'm afraid. I can prepare a target patch for the issue on top of 18.7.2 if you want...

**Comment by bitdegree67** [comment]
I'm on 18.7.2 and it's fixed :)

**Comment by bitdegree67** [comment]
oh so the fix it isn't in this release. because i really don't have the problem anymore. this is another PR have fixed this so

**Comment by fichtner** [comment]
I'm not aware of another PR having addressed this so it may just be a problem that'll come back. That's why I mention it. But I'm glad it's better now.
