### ISSUE TITLE
Feature request: Disabling keepalive option for OpenVPN clients

### ISSUE THREAD

**Issue by Chrzi** [opnsense/core#2659]
OPNSense automatically adds the `--keepalive` option to the OpenVPN client, but there is no option in the GUI to disable it.

The ping and keepalive options are mutually exclusive and some VPN providers like NordVPN rely on the ping option instead of keepalive, which results in reconnects every other minute.

**Comment by fichtner** [comment]
Hi @Chrzi,

Sounds reasonable. I assume this is most relevant for OpenVPN clients so we only need the option there?


Cheers,
Franco

**Comment by Chrzi** [comment]
Sorry for the late answer.

I did read the man page of openvpn again and a bit closer this time. `--keepalive <interval> <timeout>` is for clients an alias for `--ping <interval>` bundled with `--ping-restart <timeout>`.  

By adding the keepliave into the advanced config you can set the values however you want (except 0) and there is no need for another option to disable it.

https://community.openvpn.net/openvpn/wiki/Openvpn24ManPage

**Comment by fichtner** [comment]
@Chrzi ok, thank you for posting the answer 👍
