### ISSUE TITLE
LDAP: authentication user is broken

### ISSUE THREAD

**Issue by chrisch1974** [opnsense/core#266]
Original approach of the LDAP implantation is that you first need to setup the LDAP server. For the authentication you need to create the same group in OPNsense and LDAP. The permissions in auth.inc are read correctly but they are broken in OPNsense\Core\ACL.php as there are only local users processed. This results in an empty system menu.

Better approach would be to create the user with linking to LDAP in OPNsense. And group permissions should be handled locally.

**Comment by AdSchellevis** [comment]
commit https://github.com/opnsense/core/commit/b4845e6270bf5e885b953800d6a3e9b8323f9316 contains the "final" part of the rewrite.
You can import ldap users now in system_usermanager.php and change the permissions afterwards.

**Comment by fichtner** [comment]
Note that this commit is not part of 15.7.5's *opnsense-devel* package, but will be available in 15.7.6's *opnsense-devel. Whether or not this code will go into the stable 15.7.6 needs to be decided...

**Comment by fichtner** [comment]
@AdSchellevis @chrisch1974 close this then?

**Comment by AdSchellevis** [comment]
yes, let's close it.
