### ISSUE TITLE
[6rd] allow to manually specify the local IPv4 address

### ISSUE THREAD

**Issue by paride** [opnsense/core#2662]
I am in the following situation:
 - My ISP assigns me a private (10.x.x.x) IPv4 address and gateway via DHCP
 - I also have a public, static IPv4 address assigned, which I configured as a Virtual IP for my WAN.

The local IPv4 address I have to use to configure a 6rd tunnel is the public one, but OPNsense uses the DHCP assigned private one instead. This could be solved by allowing to chose the Virtual IP as the IPv4 address to use when configuring the tunnel.

(This could also be solved by setting the public IP as the "primary" IP for the interface, but I think this is not possible.)

At the moment I am working around this by embedding the public IP in the `6RD prefix` field (in hex) and setting `6RD IPv4 Prefix length` to 32bit (I get just a /64 from my ISP). However this is inconvenient.

**Comment by paride** [comment]
It does, thank you!

**Comment by fichtner** [comment]
@paride it's in 18.7.3 ... let me know if it works as expected

**Comment by paride** [comment]
@fichtner It does work, but unfortunately it still does not fit my use case (and I think the option name is slightly misleading). Currently the ipv4address set using the "6RD IPv4 Prefix address" option is used for two different things. One thing is computing the IPv6 prefix:

https://github.com/opnsense/core/blob/772ea4ace1c76543d75eb93dfc5fc7ac68697cc2/src/etc/inc/interfaces.inc#L2717

and subsequent use of `hexwanv4`. The other thing is setting the `stfv4net` ifconfig option:

https://github.com/opnsense/core/blob/772ea4ace1c76543d75eb93dfc5fc7ac68697cc2/src/etc/inc/interfaces.inc#L2759

I only need to change the address used to compute the prefix, so I would like the "6RD IPv4 Prefix address" to only override the address used to compute the prefix (as the option name suggests). The address passed used to set `stfv4net` could be overridden by a different option (something like "6RD local IPv4 address"). It should default to the same auto-detect logic.

This is the issue I was referring to in https://github.com/opnsense/core/issues/2663#issuecomment-423985031.

(I know you probably had enough 6rd for today, at least this may save you some mental context-switch!)

**Comment by fichtner** [comment]
Understood, will fix it tomorrow. Thanks for the analysis. :)

**Comment by fichtner** [comment]
@paride can you try this then?

    # opnsense-patch f8178e9

**Comment by paride** [comment]
@fichtner I will try this evening. Should I be on 18.7.3 or on the development version to apply the patch?

**Comment by fichtner** [comment]
@paride 18.7.3 will suffice, tomorrow's 18.7.4 will work too with the patch. and the feature could be generally fixed up in 18.7.5 if testing goes ok

**Comment by paride** [comment]
@fichtner I did apply it over 19.1.a_227-i386 and it works fine! I still have to revert to the production release, let's see what turns out to be better for #2663. I guess this issue can be closed now.

**Comment by fichtner** [comment]
Ok thanks, closing this one. Still unsure about #2663 but we'll figure something out eventually.

**Comment by fichtner** [comment]
@paride good morning! just FYI: this went into 18.7.4 last minute since you gave your ok. When you go back to 18.7.x make sure to reinstall your aliases if you had any from that config backup mentioned earlier.

**Comment by paride** [comment]
@fichtner I did notice, thanks!
