### ISSUE TITLE
Accessing the UUID of a config item in templates

### ISSUE THREAD

**Issue by ndejong** [opnsense/core#2664]
I started a discussion in the forum [with the same subject](https://forum.opnsense.org/index.php?topic=9489.0) but I think I need to move this one here to discuss the code in more detail.

My goal is to implement a [template helper](https://github.com/opnsense/core/blob/master/src/opnsense/service/modules/addons/template_helpers.py) function called `getUUIDs()` to facilitate being able to write the following template style:-
```
{% for tunnel_uuid in helpers.getUUIDs('VerbNetworks.autossh.tunnels.tunnel') %}
{% set tunnel = helpers.getUUID(tunnel_uuid) %}
Host {{ tunnel_uuid }}
  User {{ tunnel.user }}
  HostName {{ tunnel.host }}
{% endfor %}
```
Following the code, I observe that the special `__uuid_tags__` attribute that is populated via [this code ](https://github.com/opnsense/core/blob/master/src/opnsense/service/modules/config.py#L76)
```
self.__uuid_tags[item.attrib['uuid']] = item.tag
```
... and this code provides data in the helper that looks like this
```
  "__uuid_tags__": {
    "8a777695-656c-497e-ba31-3e9301edb15f": "alert",
    "4a0bab44-cd2d-485a-8d07-75967c8e521f": "key",
    "c467f1c4-375b-4be1-987a-e52a07dd6de1": "tunnel",
...
```
The "thing" about this is that the tag-name value (ie, "alert", "key", "tunnel") only provide the last part of the item tag-path which means it is impossible to select all UUIDs that belong to a given full-tag without the risk of collecting tags from different plugins that happen to have the same name.

Is there actually any straight-forward way to resolve this?  I imagine that the flow on effects of expanding the tag value to include the full tag-path would create a whole set of new issues elsewhere.
```
  "__uuid_tags__": {
    "8a777695-656c-497e-ba31-3e9301edb15f": "OPNsense.monit.general.alert",
    "4a0bab44-cd2d-485a-8d07-75967c8e521f": "VerbNetworks.autossh.keys.key",
    "c467f1c4-375b-4be1-987a-e52a07dd6de1": "VerbNetworks.autossh.tunnels.tunnel",
...
```

@AdSchellevis - I'm figuring this question is for you.

**Comment by AdSchellevis** [comment]
@ndejong I think we should just add the attributes to the items, so you could point to something like `{{tunnel.__uuid__}}` I'll take a look at this when I can.

**Comment by AdSchellevis** [comment]
for reference, same content as in the pull request :

this https://github.com/opnsense/core/commit/3add6c7cc9adea860061a8849286047cb388e777 should do the trick. 

To use a uuid, just use something similar to:

```
  {{item['@uuid']}}
```

**Comment by ndejong** [comment]
Thanks @AdSchellevis
