### ISSUE TITLE
Description missing in Firewall Aliases

### ISSUE THREAD

**Issue by MaartenJB** [opnsense/core#2667]
When I open a Firewall Alias the description field is not showing anymore. 

FreeBSD 11.1-RELEASE-p12
OpenSSL 1.0.2o 27 Mar 2018
CPU Type AMD GX-415GA SOC with Radeon(tm) HD Graphics (4 cores)
Plugin: os-acme-client 1.17 (Let's Encrypt client)

**Comment by AdSchellevis** [comment]
per line description won't be available due to the planned new version and the way item lists function.
