### ISSUE TITLE
OpenVPN /32 "IPv4 Tunnel Network" not allowed anymore 

### ISSUE THREAD

**Issue by Timo-acc** [opnsense/core#2668]
In OPNsense 18.7.1 (OpenSSL) it is not possible anymore to add for an OpenVPN server a /32 as "IPv4 Local Network"

Steps to reproduce the problem:
* select a OpenVPN Server
* add /32 Network as "IPv4 Local Network"

You will get the error message:
>"The field 'IPv4 Local Network' must contain only valid ipv4 CIDR range(s) separated by commas."

There is a second OpenVPN Server on the same OPNsense which was created when the server was on 18.1.10. and there are /32 Networks in the "IPv4 Local Network" list.

So it was possible to add such networks, but it is not in the current version.
In 18.7.1 it is only possible to add /30 and larger networks.

Thanks in advance 
Timo

**Comment by AdSchellevis** [comment]
https://forum.opnsense.org/index.php?topic=9445.0 https://github.com/opnsense/core/commit/4d664bc39d0bcf4635d3a0f758e4171831ed5d3c

**Comment by Timo-acc** [comment]
Thank you very much.

**Comment by fichtner** [comment]
Will be in 18.7.2
