### ISSUE TITLE
Nextcloud Backup not using specified port?

### ISSUE THREAD

**Issue by chris42** [opnsense/core#2671]
I tried to setup the nextcloud backup feature, however my instance is running on a different port.
I used `subdomain.domain.tld:1234` in the domain field, however I am only getting a generic communication error.
Then checked the webserver logs and no request is shown.

It seems, that the port is ignored?

**Comment by chris42** [comment]
Oops, sorry. I missed that in the problem description.
using `https://` with a valid certificate of Let's encrypt.

**Comment by chris42** [comment]
Is there a way to get some increased logging?
In GUI I only get "communication failure"
In logs I only see the config message and "config[8230]: Error while fetching filelist from Nextcloud"

**Comment by chris42** [comment]
Ok, I am not a developer, but I guess it is this part from the log, which I called config message?

`config[3662]: {"url":"https:\/\/xxx.domain.de:12345\/remote.php\/dav\/files\/christian\/","content_type":null,"http_code":0,"header_size":0,"request_size":0,"filetime":-1,"ssl_verify_result":0,"redirect_count":0,"total_time":60.000706,"namelookup_time":0.023905,"connect_time":0,"pretransfer_time":0,"size_upload":0,"size_download":0,"speed_download":0,"speed_upload":0,"download_content_length":-1,"upload_content_length":-1,"starttransfer_time":0,"redirect_time":0,"redirect_url":"","primary_ip":"","certinfo":[],"primary_port":0,"local_ip":"","local_port":0}`

What does it tell / How to read it?

**Comment by fabianfrz** [comment]
@chris42 yes, this one. It is a json structure containing all status and error codes as well as the useful debug information. In your case I guess it is a timeout problem because I don't see an error code but it fails after around one minute. Does curl on the CLI work?

**Comment by chris42** [comment]
Ok, I tried curl. It works from any machine in my LAN, but not from OPNSense. I was able to catch the connection in the firewall, which is allowed.
However I noticed, that interface lo0 is stated. 

So this is beyond me. It seems some sort of routing problem?

The nextcloud instance is in my LAN with NAT and dyndns. Hence when resolving the URL, OPNSense gets back its own WAN IP. Is this why it uses lo0? Seems to try to connect to itself?

**Comment by fabianfrz** [comment]
Ok, this is something I cannot answer…

* may be broken DNS
* broken /etc/hosts file
* broken routing
* …

in any case: @AdSchellevis @fichtner this is to be closed. It has nothing to do with the nextcloud backup code.

**Comment by chris42** [comment]
I agree that this is not a problem with the backup itself. An option to accept certificate mismatches would be a workaround, as I could use the LAN hostnames.

However I need to look into the DNS and routing setups

**Comment by fabianfrz** [comment]
There is a way to disable TLS validation: use plain HTTP ;)
