### ISSUE TITLE
dhcpd6 not starting

### ISSUE THREAD

**Issue by marjohn56** [opnsense/core#2675]
This is on the dev path, I've not checked production as I think we would have heard by now if the problem existed on that path.

I switched back from using dhcpd6 override to auto to check out that everything still works OK, and found that dhcpd6 is not starting. Tracked this down to newwanipv6 now has a check in it for $manual_dhcpv6. If this is false then services_dhcpd_configure('inet6') does not get called, result = no dhcpdv6. What was the intended purpose of this, as whether it is auto or manual dhcpd_configure('inet6') still needs calling.... or am  I missing something?

Commit ID: dcc4ec0 is the beast.

**Comment by al-ec** [comment]
Experienced the same. This actually shuts down my DNS connectivity (I guess most my DNS traffic is ipv6?) and it makes me unable to reach any update repos for OPNsense/FBSD.

**Comment by marjohn56** [comment]
Until @fichtner rejoins us just replace that check and block with this.

`foreach (link_interface_to_track6($interface, true) as $lanif => $lancfg) {
    services_dhcpd_configure('inet6');
}
`

**Comment by fichtner** [comment]
What setting in dhcpv6 /ra mode do you use? I’m entirely sure what dhcpv6 does in tracking, but Martin‘s patch is probably what is needed.

It looks like an interface_bring_down() temporarily disables dhcpv6 with that „blacklist” but it doesn’t come up afterwards again.

I removed a side effect in 18.7 that would unconditionally reload dhcpv6 so that’s probably still what we’re chasing. At least it gives us the opportunity to reload it correctly now.

**Comment by marjohn56** [comment]
Just had another look, we're not passing any interface to the services_dhcpd_configure() function so I cannot at present ( I've only been awake for a short while! ) see the reason for the 'for' loop.

**Comment by fichtner** [comment]
The for loop was for figuring out the amount of manual dhcpv6 usage. If it was above zero we would start dhcpv6 once. 😉

But then we simply have to say: if (count(link_interface...)) {

**Comment by fichtner** [comment]
Blacklist skips down interfaces which ends up stopping dhcpv6 because it has no more interfaces

**Comment by marjohn56** [comment]
So really we need to check if the interface is up and act accordingly. So perhaps a check in the services_dhcpd_configure function itself is the way forward. Not sure, not wide awake. :)

**Comment by fichtner** [comment]
I think the conditional restart in rc.newwanipv6 is enough when there is at least one track interface. Formerly, it would restart dhcpv6 for each track interface which seemed excessive.

**Comment by marjohn56** [comment]
#2681

**Comment by fichtner** [comment]
We'll add this fix to 18.7.2 next week. Thanks! ❤️
