### ISSUE TITLE
Squid GUI: does not honor syslog target

### ISSUE THREAD

**Issue by wytchmaster** [opnsense/core#2678]
Squid does not log to syslog if "Log Target" is set to syslog. There is no corresponding entry in the squid configuration file. The entry is still:

> access_log stdio:/var/log/squid/access.log squid

but should be something like:

> access_log syslog:daemon.info squid all

If I place this entry in /usr/local/etc/squid/pre-auth/10-syslog.conf everything works like a charm.

**Comment by AdSchellevis** [comment]
which version? on my machine it nicely outputs `access_log syslog:local4.info` (OPNsense 18.7.1)

https://github.com/opnsense/core/blob/18.7.1/src/opnsense/service/templates/OPNsense/Proxy/squid.conf#L361

**Comment by wytchmaster** [comment]
I have 18.7.1. And there's no syslog entry generated:

```
access_log stdio:/var/log/squid/access.log squid 
cache_store_log stdio:/var/log/squid/store.log
```
The template file looks the same as yours. The line that should insert the syslog entry is present. But I suspect that it is not transferred into the configuration file for whatever reason.

**Comment by AdSchellevis** [comment]
the template looks reasonably simple, can you inspect your `config.xml `and see what's in `OPNsense->proxy->general->logging->target` ?

**Comment by wytchmaster** [comment]
<logging>
          <enable>
            <accessLog>1</accessLog>
            <storeLog>1</storeLog>
          </enable>
          <ignoreLogACL/>
          <target>syslog</target>
        </logging>

But the squid.conf shows no difference. After a deeper look, I saw that the squid.conf has a modification date of August, 8th, which is about 4 weeks ago. So I tried to change another setting to see if it's updating the the file, but it wasn't. So it looks like that there's something broken with the generation of the file. Is there any option to force recreation of config files, maybe with debugging output?

**Comment by AdSchellevis** [comment]
you can check the configd log (system -> log files -> configd)

**Comment by wytchmaster** [comment]
Squid config file generation has an error:

`
configd.py: [920acaf7-6ebe-4492-8496-fbe050760de0] Inline action failed with OPNsense/Proxy OPNsense/Proxy/squid.conf 'collections.OrderedDict object' has no attribute 'ipaddr' at Traceback (most recent call last): File "/usr/local/opnsense/service/modules/processhandler.py", line 509, in execute return ph_inline_actions.execute(self, inline_act_parameters) File "/usr/local/opnsense/service/modules/ph_inline_actions.py", line 51, in execute filenames = tmpl.generate(parameters) File "/usr/local/opnsense/service/modules/template.py", line 332, in generate raise render_exception Exception: OPNsense/Proxy OPNsense/Proxy/squid.conf 'collections.OrderedDict object' has no attribute 'ipaddr'
`

Any clue what is happening here?

**Comment by AdSchellevis** [comment]
Does the selected interface have a static ip address?

**Comment by wytchmaster** [comment]
I found the mistake. There was an interface activated, that was no longer active (from wireguard VPN). I just removed it from the Squid-GUI and voila -> the config file was written correctly. Thank you for your support. 

BTW: will the wireguard-VPN have an gui / autostart option in the near future?
