### ISSUE TITLE
Feature request: Aliases in Traffic shaper

### ISSUE THREAD

**Issue by fixfinest** [opnsense/core#2683]
Hi there,

Pls, can u consider to add "Aliases in Traffic Shaper Rules" this a handy feature, or even add multiple ips or ranges or in "firewall rules - queues" like **pfsense** 

This feature is quite handy and effective in traffic shaping **opnsense** is missing it

Pls consider it, and thanks for great works behind that master peace firewall

**Comment by fichtner** [comment]
Please mention it here if not already asked for: https://github.com/opnsense/core/issues/2373

**Comment by fixfinest** [comment]
Sorry **fichtner**, for not following
I had a bad month in my work, so the firewall aliases features u r requesting in [#2373](https://github.com/opnsense/core/issues/2373) is really handy and all is needed, Great thinking
Thanks for ur support

**Comment by fichtner** [comment]
@fixfinest no worries, thanks for the feedback and all the best for your work :)

**Comment by fixfinest** [comment]
Thanks **fichtner** for replay and your support, great team are supporting us
Wish the best for u
