### ISSUE TITLE
Trust: Creating a CSR doesn't allow to set Alternative names

### ISSUE THREAD

**Issue by mimugmail** [opnsense/core#2686]
When I create an internal certificate I can add alternative names etc. to the certificate. 
But when I just create a CSR e.g. for signing at a regular authority, I can't add alternative names. 
This breaks setups where multi san certificates are in use.

Any idea how to fix that?

**Comment by andrewheberle** [comment]
This causes Chrome to complain that the resulting certificate is invalid (NET::ERR_CERT_COMMON_NAME_INVALID) as the there is no "Subject Alternative Names" on the certificate.

Many CA's add the "CN" as an alternative name by default anyway for this exact reason, however it is best not to rely on this...

Ideally the UI should (in my opinion anyway) default to including the CN as a DNS based alternative name, and allow the user to remove this if required.

**Comment by mimugmail** [comment]
Adding multiple SANs is also requires since you can order Multi SAN certificates for e.g. 5 DNS names.

**Comment by AdSchellevis** [comment]
@mimugmail it should be as simple as https://github.com/opnsense/core/pull/2932, can you try and confirm this fixes your issue?

**Comment by fichtner** [comment]
@mimugmail please test, I want to ship in 18.7.8 ;)

**Comment by mimugmail** [comment]
I don't want to press order as it's 79 EUR, but the CSR looks wrong:

This is by OPN:
`Subject: C=DE, ST=Bayern, L=Muenchen, O=m.a.x. Informationstechnologie AG/emailAddress=michael.muenz@max-it.de, CN=www.spam-fetish.org/subjectAltName=DNS:mail.spam-fetish.org,DNS:vpn.spam-fetish.org,DNS:autodiscover.spam-fetish.org`

But it should be under x509 extensions:
```
        Attributes:
        Requested Extensions:
            X509v3 Subject Alternative Name:
                DNS:mail.spam-fetish.org, DNS:mobile.spam-fetish.org, DNS:autodiscover.spam-fetish.org, DNS:vpn.spam-fetish.org
```

**Comment by MichaelDeciso** [comment]
I have been able to reproduce your problem, and it should be fixed now: https://github.com/opnsense/core/pull/2967
Could you test if OPNsense now generates a correct CSR for you?

**Comment by MichaelDeciso** [comment]
@mimugmail ping

**Comment by mimugmail** [comment]
It looks good now :)
