### ISSUE TITLE
Captive Portal: Accounting to Radius only when there is a Daily Session Limit?

### ISSUE THREAD

**Issue by mimugmail** [opnsense/core#2689]
I'm playing with SQLite and FreeRADIUS. 

What I recently discovered is that accounting requests are only sent when there is a session limit for the user. 

I understand that it doesn't make much sense for every user to send accounting requests every 5 seconds, but it might be cool to see wasted bandwidth for every logged in user in CP. 

Would this be hard to implement?

**Comment by AdSchellevis** [comment]
@mimugmail the session_limit is how the system knows accounting is enabled, it shouldn't be very difficult to add an option there to send all out when an option is set. I'm probably going to work on some bandwidth options in CP in a couple of weeks, will look at this then.

**Comment by AdSchellevis** [comment]
@mimugmail If I'm not mistaken I should create some maximums per client (mac), but I don't remember exactly what it should do.  It's not for myself, it's for a client.

**Comment by mimugmail** [comment]
I like your client! 👍

**Comment by AdSchellevis** [comment]
@mimugmail this https://github.com/opnsense/core/pull/2996 adds an option to always send accounting messages, does that fix your issue?

**Comment by mimugmail** [comment]
Works great, thanks! 👍
