### ISSUE TITLE
Default Gateway Issue with DHCP

### ISSUE THREAD

**Issue by redcot** [opnsense/core#2690]
When a interface doesnt get a DHCP response thats the interface that is selected as the default gateway with mulitiple a WAN setup! Opnsense Version OPNsense 18.7.1_3-amd64

**Comment by fichtner** [comment]
Hi @redcot, would you mind explaining this in more detail?

**Comment by Adamizme** [comment]
I believe I experienced this same issue yesterday. I configured a second WAN port for DHCP (primary WAN uses static IP). When I plugged in the secondary WAN, internet went down completely until I disabled the secondary gateway and then re-enabled it.

Hope this helps.

**Comment by fichtner** [comment]
Sounds like #2542 ?

**Comment by fichtner** [comment]
Let's focus discussion in #2542 then. I've made a bit of progress with dhclient script, but it needs testing.
