### ISSUE TITLE
web proxy not respecting whitelist for SSL transprent proxy

### ISSUE THREAD

**Issue by gitterdoneplease** [opnsense/core#2692]
Steps to reproduce:

1. Web Proxy -> Administration; Forward Proxy -> Access Control List
2. In Whitelist paste without quotes "^https?:\/\/yahoo.com,^https?:\/\/www.yahoo.com,yahoo.com,www.yahoo.com"
3. Apply

Expected result:

www.yahoo.com and yahoo.com accessed via public CA

Actual result:

www.yahoo.com and yahoo.com accessed via private CA

**Comment by AdSchellevis** [comment]
whitelisting and do not bump (`SSL no bump sites`) are different things, if you would like to skip ssl bumping, but the domains in the  "SSL no bump sites" list.

**Comment by gitterdoneplease** [comment]
It appears do not bump also whitelists the site. Is that as intended?

**Comment by fichtner** [comment]
Can this be cosed?

**Comment by mimugmail** [comment]
I'd go for closing .. more related to the forums
