### ISSUE TITLE
18.7.2 udate hosed config

### ISSUE THREAD

**Issue by larseggert** [opnsense/core#2694]
My box auto-updated to 18.7.2 overnight, and that completely hosed the config. The WAN port was configured on igb3, but when I logged into 18.7.2, it showed as configured on igb1 (which was unused before). That change caused many other configurations to become invalid (port forwards, etc.)

I am manually cleaning it all up now, and I wish I could give any details, but /var/log is on tmpfs.

(I did get an email notification, with a less-than-helpful message of "There were error(s) loading the rules: no IP address found for enc0:network")

**Comment by larseggert** [comment]
I have no USB devices in use, and I don't use zerotier. Anyway, I will lock the NICs - I assume you mean "Prevent interface removal"? Wouldn't I also need to lock down the currently unused igb1 and igb2 interfaces?

Regarding System: Configuration: History, after fixing the config manually, I don't have the respective entries available anymore. I upped the limit in case something like this happens again.

Thanks for the quick response!

**Comment by fichtner** [comment]
Would you mind posting output of your network devices?

# ifconfig -l

**Comment by larseggert** [comment]
```
root@pf:~ # ifconfig -l
igb0 igb1 igb2 igb3 enc0 lo0 pflog0 pfsync0
```

**Comment by mimugmail** [comment]
Did you try to assign some other VPN Interfaces like OpenVPN, Tinc or Wireguard?

**Comment by fichtner** [comment]
At least from the ifconfig advertised devices there's nothing that would have caused this (all hard-wired). "Prevent interface removal" is the correct setting, should enable it on WAN and that'll take care of it in the future.

So I guess close ticket?

**Comment by larseggert** [comment]
@mimugmail I have an OpenConnect tunnel, but I don't think that establishes itself at boot time. Not sure though.

**Comment by larseggert** [comment]
Yeah, close it I guess

**Comment by fichtner** [comment]
If openconnect was involved and assigned as an interface that allows us to do something to prevent this in the future?
