### ISSUE TITLE
6rd WAN gateway does not get an address assigned in 18.7.2

### ISSUE THREAD

**Issue by Uica** [opnsense/core#2698]
I updated to 18.7.2 today, but IPv6 WAN access stopped working. Turned out that the WAN_6RD gateway no longer gets an address assigned; it just says "dynamic" where there used to be a (strange) combination of IPv6 address and 6RD Border Relay earlier (something like 2a00:xxxx:xxxx:xxxx::100.127.0.1).
6rd itself seems to be working; the WAN section on the console shows the correct /56 network.

I reverted to 18.7.1 for now after several attempts to get it working. Simple revert of opnsense to release 18.7.1 worked immediately, without reboot.

I'll be happy to help tracking down the reason, just let me know what information you need or what I should try.

**Comment by Uica** [comment]
Thanks, that worked! The cosmetic part (showing the gateway address) worked immediately, the policy based routing worked after a reboot. Now LAN clients can use IPv6 again to connect to the internet.
Regarding your comment on the real fix: Could it be that OpenVPN clients could benefit from the same fix? I had some issues with IPv6 routing through an OpenVPN tunnel, not critical now because I found a workaround.

**Comment by fichtner** [comment]
Sounds like a different issue, but I can't rule out the possibility that the current development efforts to align interface names and their helper files 100% for IPv4 and IPv6 connectivity would play a role in the grand scheme of things. Couldn't possibly say more without knowing the underlying cause of what you are seeing and / or direct feedback from the master branch in your setup.

**Comment by fichtner** [comment]
@Uica does this work on 18.7.3 ?

**Comment by Uica** [comment]
Yes, just updated a few hours ago, did not see that problem again.

**Comment by fichtner** [comment]
super, thanks! :)
