### ISSUE TITLE
How to enable MySQL as database backend for Freeradius?

### ISSUE THREAD

**Issue by reza-ebrahimi** [opnsense/core#2699]
I need to use MySQL database for accounting purposes on Freeradius, but cannot find any document about that.

**Comment by fabianfrz** [comment]
does not work with the plugin because it is not supported. If it works (don't know if it is compiled in), you have to configure freeradius by yourself on command line and use it without the plugin.

**Comment by fichtner** [comment]
The freeradius3 port also needs the MYSQL option, but we have SQLITE and no plans to pull in another database for it.

**Comment by mimugmail** [comment]
It will only be SQLite and basic functionality was added with 18.7.2.
If you insist we could try to add a feature to speak with an external MySQL DB via 3306

**Comment by reza-ebrahimi** [comment]
@fichtner Is freeradius port on opnsense supports SQLite by default?
