### ISSUE TITLE
pkg upgrade does not refresh update list

### ISSUE THREAD

**Issue by fraenki** [opnsense/core#27]
When running pkg upgrades from System->Firmware the packages will be updates without problems. Unfortunately the OPNsense appliance does not refresh the update list and keeps telling me that an update is available (actually the same update as before: pkg 1.4.3 -> 1.4.4).

Maybe OPNsense should clear the update list if the pkg upgrade completed successfully.

System: fresh install of OPNsense 15.1 amd64

**Comment by fichtner** [comment]
I've seen this... does this go away if you use the Dashboard to click and check for new updates?

**Comment by fraenki** [comment]
Yes, this is the only way to clear the outdated update message. (Also tried a logout/login cycle.)

**Comment by fichtner** [comment]
Thanks, that'll make it easy to track down. @jschellevis will you take this? :)
