### ISSUE TITLE
OpenVPN: Client Specific Overrides problem in 18.7.2 

### ISSUE THREAD

**Issue by fprina** [opnsense/core#2701]
After the 18.7.2 upgrade seems OpenVPN do not create anymore the CSO files.

Also the RADISU Framed-Route and ramed-IP-Address attributes are ignored

**Comment by AdSchellevis** [comment]
upgrade from where?

**Comment by AdSchellevis** [comment]
what does the openvpn log report?

**Comment by fprina** [comment]
This is an authentiation session
`
Sep  8 12:45:28 nme-fw1-prod openvpn[24686]: MULTI: multi_create_instance called
Sep  8 12:45:28 nme-fw1-prod openvpn[24686]: 1xx.xx.xx.xx:55114 Re-using SSL/TLS context
Sep  8 12:45:28 nme-fw1-prod openvpn[24686]: 1xx.xx.xx.xx:55114 LZO compression initializing
Sep  8 12:45:28 nme-fw1-prod openvpn[24686]: 1xx.xx.xx.xx:55114 Control Channel MTU parms [ L:1622 D:1140 EF:110 EB:0 ET:0 EL:3 ]
Sep  8 12:45:28 nme-fw1-prod openvpn[24686]: 1xx.xx.xx.xx:55114 Data Channel MTU parms [ L:1622 D:1450 EF:122 EB:406 ET:0 EL:3 ]
Sep  8 12:45:28 nme-fw1-prod openvpn[24686]: 1xx.xx.xx.xx:55114 Local Options String (VER=V4): 'V4,dev-type tun,link-mtu 1602,tun-mtu 1500,proto UDPv4,comp-lzo,keydir 0,cipher AES-128-CBC,auth SHA512,keysize 128,tls-auth,key-method 2,tls-server'
Sep  8 12:45:28 nme-fw1-prod openvpn[24686]: 1xx.xx.xx.xx:55114 Expected Remote Options String (VER=V4): 'V4,dev-type tun,link-mtu 1602,tun-mtu 1500,proto UDPv4,comp-lzo,keydir 1,cipher AES-128-CBC,auth SHA512,keysize 128,tls-auth,key-method 2,tls-client'
Sep  8 12:45:28 nme-fw1-prod openvpn[24686]: 1xx.xx.xx.xx:55114 UDPv4 READ [86] from [AF_INET]1xx.xx.xx.xx:55114: P_CONTROL_HARD_RESET_CLIENT_V2 kid=0 pid=[ #1 ] [ ] pid=0 DATA len=0
Sep  8 12:45:28 nme-fw1-prod openvpn[24686]: 1xx.xx.xx.xx:55114 TLS: Initial packet from [AF_INET]1xx.xx.xx.xx:55114, sid=2a61cb2a b28c81b5
Sep  8 12:45:28 nme-fw1-prod openvpn[24686]: 1xx.xx.xx.xx:55114 UDPv4 WRITE [98] to [AF_INET]1xx.xx.xx.xx:55114: P_CONTROL_HARD_RESET_SERVER_V2 kid=0 pid=[ #1 ] [ 0 ] pid=0 DATA len=0
Sep  8 12:45:28 nme-fw1-prod openvpn[24686]: 1xx.xx.xx.xx:55114 UDPv4 READ [94] from [AF_INET]1xx.xx.xx.xx:55114: P_ACK_V1 kid=0 pid=[ #2 ] [ 0 ]
Sep  8 12:45:28 nme-fw1-prod openvpn[24686]: 1xx.xx.xx.xx:55114 UDPv4 READ [246] from [AF_INET]1xx.xx.xx.xx:55114: P_CONTROL_V1 kid=0 pid=[ #3 ] [ ] pid=1 DATA len=160
Sep  8 12:45:28 nme-fw1-prod openvpn[24686]: 1xx.xx.xx.xx:55114 UDPv4 WRITE [1128] to [AF_INET]1xx.xx.xx.xx:55114: P_CONTROL_V1 kid=0 pid=[ #2 ] [ 1 ] pid=1 DATA len=1030
Sep  8 12:45:28 nme-fw1-prod openvpn[24686]: 1xx.xx.xx.xx:55114 UDPv4 WRITE [1116] to [AF_INET]1xx.xx.xx.xx:55114: P_CONTROL_V1 kid=0 pid=[ #3 ] [ ] pid=2 DATA len=1030
Sep  8 12:45:28 nme-fw1-prod openvpn[24686]: 1xx.xx.xx.xx:55114 UDPv4 WRITE [1116] to [AF_INET]1xx.xx.xx.xx:55114: P_CONTROL_V1 kid=0 pid=[ #4 ] [ ] pid=3 DATA len=1030
Sep  8 12:45:28 nme-fw1-prod openvpn[24686]: 1xx.xx.xx.xx:55114 UDPv4 WRITE [966] to [AF_INET]1xx.xx.xx.xx:55114: P_CONTROL_V1 kid=0 pid=[ #5 ] [ ] pid=4 DATA len=880
Sep  8 12:45:28 nme-fw1-prod openvpn[24686]: 1xx.xx.xx.xx:55114 UDPv4 READ [94] from [AF_INET]1xx.xx.xx.xx:55114: P_ACK_V1 kid=0 pid=[ #4 ] [ 1 ]
Sep  8 12:45:28 nme-fw1-prod openvpn[24686]: 1xx.xx.xx.xx:55114 UDPv4 READ [94] from [AF_INET]1xx.xx.xx.xx:55114: P_ACK_V1 kid=0 pid=[ #5 ] [ 2 ]
Sep  8 12:45:28 nme-fw1-prod openvpn[24686]: 1xx.xx.xx.xx:55114 UDPv4 READ [94] from [AF_INET]1xx.xx.xx.xx:55114: P_ACK_V1 kid=0 pid=[ #6 ] [ 3 ]
Sep  8 12:45:28 nme-fw1-prod openvpn[24686]: 1xx.xx.xx.xx:55114 UDPv4 READ [224] from [AF_INET]1xx.xx.xx.xx:55114: P_CONTROL_V1 kid=0 pid=[ #7 ] [ 4 ] pid=2 DATA len=126
Sep  8 12:45:28 nme-fw1-prod openvpn[24686]: 1xx.xx.xx.xx:55114 UDPv4 WRITE [149] to [AF_INET]1xx.xx.xx.xx:55114: P_CONTROL_V1 kid=0 pid=[ #6 ] [ 2 ] pid=5 DATA len=51
Sep  8 12:45:28 nme-fw1-prod openvpn[24686]: 1xx.xx.xx.xx:55114 UDPv4 READ [580] from [AF_INET]1xx.xx.xx.xx:55114: P_CONTROL_V1 kid=0 pid=[ #8 ] [ 5 ] pid=3 DATA len=482
Sep  8 12:45:28 nme-fw1-prod openvpn[24686]: 1xx.xx.xx.xx:55114 peer info: IV_VER=2.5_master
Sep  8 12:45:28 nme-fw1-prod openvpn[24686]: 1xx.xx.xx.xx:55114 peer info: IV_PLAT=android
Sep  8 12:45:28 nme-fw1-prod openvpn[24686]: 1xx.xx.xx.xx:55114 peer info: IV_PROTO=2
Sep  8 12:45:28 nme-fw1-prod openvpn[24686]: 1xx.xx.xx.xx:55114 peer info: IV_NCP=2
Sep  8 12:45:28 nme-fw1-prod openvpn[24686]: 1xx.xx.xx.xx:55114 peer info: IV_LZ4=1
Sep  8 12:45:28 nme-fw1-prod openvpn[24686]: 1xx.xx.xx.xx:55114 peer info: IV_LZ4v2=1
Sep  8 12:45:28 nme-fw1-prod openvpn[24686]: 1xx.xx.xx.xx:55114 peer info: IV_LZO=1
Sep  8 12:45:28 nme-fw1-prod openvpn[24686]: 1xx.xx.xx.xx:55114 peer info: IV_COMP_STUB=1
Sep  8 12:45:28 nme-fw1-prod openvpn[24686]: 1xx.xx.xx.xx:55114 peer info: IV_COMP_STUBv2=1
Sep  8 12:45:28 nme-fw1-prod openvpn[24686]: 1xx.xx.xx.xx:55114 peer info: IV_TCPNL=1
Sep  8 12:45:28 nme-fw1-prod openvpn[24686]: 1xx.xx.xx.xx:55114 peer info: IV_GUI_VER=de.blinkt.openvpn_0.7.5
Sep  8 12:45:28 nme-fw1-prod openvpn: user 'fprina' authenticated using 'Radius-auth1'
Sep  8 12:45:28 nme-fw1-prod openvpn[24686]: 1xx.xx.xx.xx:55114 TLS: Username/Password authentication succeeded for username 'fprina' [CN SET]
Sep  8 12:45:28 nme-fw1-prod openvpn[24686]: 1xx.xx.xx.xx:55114 UDPv4 WRITE [353] to [AF_INET]1xx.xx.xx.xx:55114: P_CONTROL_V1 kid=0 pid=[ #7 ] [ 3 ] pid=6 DATA len=255
Sep  8 12:45:28 nme-fw1-prod openvpn[24686]: 1xx.xx.xx.xx:55114 UDPv4 READ [94] from [AF_INET]1xx.xx.xx.xx:55114: P_ACK_V1 kid=0 pid=[ #9 ] [ 6 ]
Sep  8 12:45:28 nme-fw1-prod openvpn[24686]: 1xx.xx.xx.xx:55114 Control Channel: TLSv1.2, cipher TLSv1/SSLv3 ECDHE-RSA-AES256-GCM-SHA384
Sep  8 12:45:28 nme-fw1-prod openvpn[24686]: 1xx.xx.xx.xx:55114 [fprina] Peer Connection Initiated with [AF_INET]1xx.xx.xx.xx:55114
Sep  8 12:45:28 nme-fw1-prod openvpn[24686]: fprina/1xx.xx.xx.xx:55114 MULTI_sva: pool returned IPv4=10.44.144.2, IPv6=(Not enabled)
Sep  8 12:45:28 nme-fw1-prod openvpn[24686]: fprina/1xx.xx.xx.xx:55114 MULTI: Learn: 10.8.144.2 -> fprina/1xx.xx.xx.xx:55114
Sep  8 12:45:28 nme-fw1-prod openvpn[24686]: fprina/1xx.xx.xx.xx:55114 MULTI: primary virtual IP for fprina/1xx.xx.xx.xx:55114: 10.8.144.2
Sep  8 12:45:29 nme-fw1-prod openvpn[24686]: fprina/1xx.xx.xx.xx:55114 UDPv4 READ [128] from [AF_INET]1xx.xx.xx.xx:55114: P_CONTROL_V1 kid=0 pid=[ #10 ] [ ] pid=4 DATA len=42
Sep  8 12:45:29 nme-fw1-prod openvpn[24686]: fprina/1xx.xx.xx.xx:55114 PUSH: Received control message: 'PUSH_REQUEST'
Sep  8 12:45:29 nme-fw1-prod openvpn[24686]: fprina/1xx.xx.xx.xx:55114 SENT CONTROL [fprina]: 'PUSH_REPLY,dhcp-option DOMAIN ................ ,push-continua
Sep  8 12:45:29 nme-fw1-prod openvpn[24686]: fprina/1xx.xx.xx.xx:55114 SENT CONTROL [fprina]: 'PUSH_REPLY,route ................ (status=1)
Sep  8 12:45:29 nme-fw1-prod openvpn[24686]: fprina/1xx.xx.xx.xx:55114 Data Channel: using negotiated cipher 'AES-256-GCM'
Sep  8 12:45:29 nme-fw1-prod openvpn[24686]: fprina/1xx.xx.xx.xx:55114 Data Channel MTU parms [ L:1550 D:1450 EF:50 EB:406 ET:0 EL:3 ]
Sep  8 12:45:29 nme-fw1-prod openvpn[24686]: fprina/1xx.xx.xx.xx:55114 Outgoing Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key
Sep  8 12:45:29 nme-fw1-prod openvpn[24686]: fprina/1xx.xx.xx.xx:55114 Incoming Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key
Sep  8 12:45:29 nme-fw1-prod openvpn[24686]: fprina/1xx.xx.xx.xx:55114 UDPv4 WRITE [94] to [AF_INET]1xx.xx.xx.xx:55114: P_ACK_V1 kid=0 pid=[ #8 ] [ 4 ]
Sep  8 12:45:29 nme-fw1-prod openvpn[24686]: fprina/1xx.xx.xx.xx:55114 UDPv4 WRITE [1116] to [AF_INET]1xx.xx.xx.xx:55114: P_CONTROL_V1 kid=0 pid=[ #9 ] [ ] pid=7 DATA len=1030
Sep  8 12:45:29 nme-fw1-prod openvpn[24686]: fprina/1xx.xx.xx.xx:55114 UDPv4 WRITE [812] to [AF_INET]1xx.xx.xx.xx:55114: P_CONTROL_V1 kid=0 pid=[ #10 ] [ ] pid=8 DATA len=726
Sep  8 12:45:29 nme-fw1-prod openvpn[24686]: fprina/1xx.xx.xx.xx:55114 UDPv4 READ [94] from [AF_INET]1xx.xx.xx.xx:55114: P_ACK_V1 kid=0 pid=[ #11 ] [ 7 ]
Sep  8 12:45:30 nme-fw1-prod openvpn[24686]: fprina/1xx.xx.xx.xx:55114 UDPv4 WRITE [89] to [AF_INET]1xx.xx.xx.xx:55114: P_DATA_V2 kid=0 DATA len=88
Sep  8 12:45:30 nme-fw1-prod openvpn[24686]: fprina/1xx.xx.xx.xx:55114 UDPv4 READ [94] from [AF_INET]1xx.xx.xx.xx:55114: P_ACK_V1 kid=0 pid=[ #12 ] [ 8 ]
Sep  8 12:45:30 nme-fw1-prod openvpn[24686]: fprina/1xx.xx.xx.xx:55114 UDPv4 READ [85] from [AF_INET]1xx.xx.xx.xx:55114: P_DATA_V2 kid=0 DATA len=84
Sep  8 12:45:30 nme-fw1-prod openvpn[24686]: fprina/1xx.xx.xx.xx:55114 TUN WRITE [60]
Sep  8 12:45:30 nme-fw1-prod openvpn[24686]: fprina/1xx.xx.xx.xx:55114 UDPv4 READ [95] from [AF_INET]1xx.xx.xx.xx:55114: P_DATA_V2 kid=0 DATA len=94
Sep  8 12:45:30 nme-fw1-prod openvpn[24686]: fprina/1xx.xx.xx.xx:55114 TUN WRITE [70]
Sep  8 12:45:30 nme-fw1-prod openvpn[24686]: fprina/1xx.xx.xx.xx:55114 TUN READ [76]
Sep  8 12:45:30 nme-fw1-prod openvpn[24686]: fprina/1xx.xx.xx.xx:55114 UDPv4 WRITE [101] to [AF_INET]1xx.xx.xx.xx:55114: P_DATA_V2 kid=0 DATA len=100
Sep  8 12:45:30 nme-fw1-prod openvpn[24686]: fprina/1xx.xx.xx.xx:55114 TUN READ [216]
Sep  8 12:45:30 nme-fw1-prod openvpn[24686]: fprina/1xx.xx.xx.xx:55114 UDPv4 WRITE [185] to [AF_INET]1xx.xx.xx.xx:55114: P_DATA_V2 kid=0 DATA len=184
Sep  8 12:45:31 nme-fw1-prod openvpn[24686]: fprina/1xx.xx.xx.xx:55114 UDPv4 READ [90] from [AF_INET]1xx.xx.xx.xx:55114: P_DATA_V2 kid=0 DATA len=89
Sep  8 12:45:31 nme-fw1-prod openvpn[24686]: fprina/1xx.xx.xx.xx:55114 TUN WRITE [65]
`

I suppose that I should see something like 
`user '{$username}' authenticated using '{$authName}' cso :{$cso_filename}"`

Also editing a CSO from the web GUI the file is not created, at least i do not see it in the /var/etc/openvpn-csc/1 directory 

About the version I'm sure it worked with 18.7.1 but not the 100% on 18.7.1_3

**Comment by AdSchellevis** [comment]
only thing changed there is this https://github.com/opnsense/core/commit/bcb31809a51b9d089c3df2a98d999a6f95cd9166 can you try to revert this one?

```
opnsense-patch bcb31809
```

If that makes a difference, there might be a mismatch in your username and chosen certificate CN, in most situations `$username` and `$common_name` are equal, which is why we missed it in the first place.

**Comment by fprina** [comment]
After the bcb31809 patch the CSO started to work again; CSO file are create and also RADIUS attribute are fine. 

Currently I'm using  "Remote Access (User Auth)" as Server Mode with the certificate and the relative CN  shared across all the users.

So the username is the only user identifier and I'm sure they are different from the CN.

**Comment by AdSchellevis** [comment]
We probably have to add an option to prefer user as common name, I don’t think we can detect this automatically

**Comment by fichtner** [comment]
isn't here an option already?

**Comment by fichtner** [comment]
Strict User/CN Matching

**Comment by fichtner** [comment]
ah ok :/

FWIW, @fprina does not use TLS so there is no common name to default against

**Comment by fprina** [comment]
From the man page 
```    
   --username-as-common-name
              For --auth-user-pass-verify authentication, use the
              authenticated username as the common name, rather than the
              common name from the client cert.
```

But in current /var/etc/openvpn/server1.conf is already present 
```
username-as-common-name
auth-user-pass-verify "/usr/local/etc/inc/plugins.inc.d/openvpn/ovpn_auth_verify user 'Radius-auth1,Radius-auth2' 'false' 'server1'" via-env
```
So this directive seems do not work properly

**Comment by fprina** [comment]
> We probably have to add an option to prefer user as common name, I don’t think we can detect this automatically

I've added a pull reqeust with the option

**Comment by AdSchellevis** [comment]
closed with https://github.com/opnsense/core/pull/2748
