### ISSUE TITLE
Firewall's Aliases: more descrition fields

### ISSUE THREAD

**Issue by sachaz** [opnsense/core#2703]
Hi,

as we add some networks or hosts in the Firewall's Aliases, it could be usefull to have a description for each aliases.

**Comment by fichtner** [comment]
Hi @sachaz,

We decided to remove per-item descriptions for the upcoming alias API and have explained a few times. You can nest aliases if you need descriptions for specific aliases / groups. Therefore the feature was dropped in 18.7.


Cheers,
Franco

**Comment by sachaz** [comment]
Ok thanks
