### ISSUE TITLE
OPNsense does not add l2tp device via Webui if configured

### ISSUE THREAD

**Issue by jmboettger** [opnsense/core#2707]
If you try to add a l2tp device via Interfaces -> Point to Point -> Devices -> Add, you can insert all the details needed and save it, the web ui shows a interface l2tp0 which should be correct.
After assigning the newly created interface and activating it, the logfile shows

> opnsense: /interfaces.php: The command `/sbin/ifconfig -m 'l2tp0'' failed to execute ifconfig: interface l2tp0 does not exist

furthermore, if you open the advanced settings it opens an empty mask to create a new l2tp interface.

Versions | OPNsense 18.7.2-amd64FreeBSD 11.1-RELEASE-p13

**Comment by jmboettger** [comment]
![bildschirmfoto_2018-09-09_19-47-08](https://user-images.githubusercontent.com/877113/45267275-e157e600-b469-11e8-8a3d-62c660df41fd.png)

**Comment by fichtner** [comment]
There's an issue here indeed, but I'm unable to locate it at first glance.

**Comment by miminno** [comment]
Same issue with adding PPTP interface.

**Comment by fichtner** [comment]
reclassified as cleanup since there wasn't an issue with operation, for details see 7fda167
