### ISSUE TITLE
Add logging option to NAT rule

### ISSUE THREAD

**Issue by ccesario** [opnsense/core#2717]
Currently the NAT / Portforward rules does not have logging option.
Would be interesting add it to audit the external connections.

**Comment by fichtner** [comment]
There is a ticket for this I think.

**Comment by ccesario** [comment]
> There is a ticket for this I think.

Nice... This is very importand for audit process :)

**Comment by fichtner** [comment]
for reference, see #1494 :)

I'm closing this one
