### ISSUE TITLE
Issues with the GUI - DCHP V4 - Sends back to the dashboard 

### ISSUE THREAD

**Issue by nitrofx** [opnsense/core#2719]
Not sure if anyone is experiencing this issue with the new version of OPNsense 18.7.2-amd64 that when selecting to add a new static IP in DHCPv4 the GUI jumps back to the Dashboard. Please note that restarting the FW or the plug-in also does not fix the issue.
Not sure if this is a known bug and if there are any logs that I can submit to troubleshoot the issue. Please advise. Thanks.

system details:

Intel(R) Core(TM)2 Duo CPU E6550 @ 2.33GHz (2 cores)

State table size
0 % ( 107/391000 )
MBUF Usage
0 % ( 2030/242968 )
Memory usage
6 % ( 256/3917 MB )
SWAP usage
0 % ( 0/8192 MB )
Disk usage
OPNsense 18.7.2-amd64
FreeBSD 11.1-RELEASE-p13
OpenSSL 1.0.2p 14 Aug 2018

**Comment by fichtner** [comment]
Hi @nitrofx,

Thanks for the report!

There's not enough to go on just yet so please let us know:

1. last version this was working ok
2. which page you are on before you click add
3. the link you click (copy link)
4. does your user have all privileges to access said page?

My first guess would be your LAN/OPT does not have a static IPv4 so the redirect kicks in....


Cheers,
Franco

**Comment by nitrofx** [comment]
1. last version this was working ok
- this is the first version tested. 

2. which page you are on before you click add
- I start at the dashboard and navigate to the DHCP page leases

3. the link you click (copy link)
- https://192.168.1.1/status_dhcp_leases.php
-The issue happens when clicking on the plus sign in order to convert a dynamic IP to a static at the page listed above.

4. does your user have all privileges to access said page? am running the GUI with root access.

PS: There is a work around, you can manually add a static IP by using the link 

https://192.168.1.1/services_dhcp.php?if=lan

- clicking on the plus icon located on the right side of the DHCP Static Mappings for this interface section. however, you need to know the MAC address and hostname of the PC or device to add, or copy from the page - https://192.168.1.1/status_dhcp_leases.php and paste it there. this however, defeats the purpose of the + sign beside the dynamic setting. 

Thanks for your support.

**Comment by nitrofx** [comment]
Please also note that enabling these two settings on the DHCP v4 page: 

https://192.168.1.1/services_dhcp.php?if=lan

Static ARP | Enable Static ARP entries
Warning: This option persists even if DHCP server is disabled. Only the machines listed below will be able to communicate with the firewall on this NIC.
-- | --
Time format change | Change DHCP display lease time from UTC to local time.Warning: By default DHCP leases are displayed in UTC time. By checking this box DHCP lease time will be displayed in local time and set to time zone selected. This will be used for all DHCP interfaces lease time.

It causes the web-page to freeze stop responding and closed the communication. I have to restart the sytem twice in order to be able to log back in.

**Comment by fichtner** [comment]
Let's not get ahead of ourselves... I can't reproduce your issue with the leases page. What leases "add" link are you seeing? feel free to remove the hostname and mac from the url.

**Comment by nitrofx** [comment]
sorry, i lost you there... 
-The issue happens when clicking on the plus sign in order to convert a dynamic IP to a static IP at the page listed below.

https://192.168.1.1/status_dhcp_leases.php

**Comment by fichtner** [comment]
I know. I need the link from the plus sign, not the link of the page where the add button is to be found :)

**Comment by nitrofx** [comment]
I have reinstalled the FW. there were other underlining issues with it, Unbound stopped working etc. I will keep an eye on this new installation and see what happens.
