### ISSUE TITLE
Wierd IPv6 issue when using PPPoE

### ISSUE THREAD

**Issue by marjohn56** [opnsense/core#2726]
We noticed that if you save and apply the WAN interface, don't take it down - just save and apply then when the interface comes back up there is no IPv6 address on the PPPoE interface. I think this is because the PPPoE interface is not ready for it. Sort of proved this by putting a sleep(5) ( maybe a bit long ) in the case 'ppp': call where it's setup for V4.

Interfaces.inc Lines 211 on.

> switch ($wancfg['ipaddr']) {
        case 'dhcp':
            interface_dhcp_configure($interface);
            break;
        case 'pppoe':
        case 'l2tp':
        case 'pptp':
        case 'ppp':
            interface_ppps_configure($interface);
            sleep(5);
            break;
        default:
            /* XXX: Kludge for now related to #3280 */
            if (!in_array($tunnelif, array("gif", "gre", "ovp"))) {
                if (is_ipaddrv4($wancfg['ipaddr']) && $wancfg['subnet'] <> "") {
                    legacy_interface_setaddress($realif, "{$wancfg['ipaddr']}/{$wancfg['subnet']}");
                }
            }
            break;
    }

Very likely not the way to fix this, but I wonder if this is causing some of the odd v6 behaviour sometimes seen on the forum.

**Comment by marjohn56** [comment]
Have a little free time to take a look at this. It appears it only happens if you have a static v6 with PPPoE on v4. I think if you are using dhcp6c the natural sequence of things allows that to work, but with static v6 it appears it's trying to add the v6 address before the interface is ready. I know it fixes it using a generic sleep(5) before applying the static, I'll reduce that until it no longer works then increase it and also add a catch so that it only sleeps if dhcp4 is pppoe and v6 is static.

**Comment by marjohn56** [comment]
Use IPv4 connectivity is checked, as it's using the PPPoE link.

**Comment by fichtner** [comment]
@marjohn56 noted via https://github.com/opnsense/core/pull/2736

> That bits OK, but the dev version has something amiss in the firewall, it was not allowing any of my rules for my servers, everything was hitting the default deny.

Did you solve this or potentially still happening? There are a few minor firewalling changes, but nothing drastic that would force this.

**Comment by marjohn56** [comment]
No, I had to switch back to production due to complete lack of email coming through, SWMBO was muttering. I'll try and have another look when I can.

**Comment by fichtner** [comment]
Alias issue solved in -devel

**Comment by marjohn56** [comment]
Confirmed. Running live unit with 11.2 at 19.1b, all good.

**Comment by fichtner** [comment]
Not yet, 19.1.b is 18.7.5 which does not have new alias API yet. But -devel should work now when you switch over.
