### ISSUE TITLE
OpenVPN - No buffer space available

### ISSUE THREAD

**Issue by jo3rg** [opnsense/core#2729]
OPNsense 18.1.9-amd64
FreeBSD 11.1-RELEASE-p10
LibreSSL 2.6.4
---
Whenever I have my outgoing traffic tunneled via VPN and it's running at about 40MBit 
it crashes at some point triggering the following errormessages:
`openvpn[79299]: write UDP: Host is down (code=64)
openvpn[834]: write UDP: No buffer space available (code=55)
`
Anyone ever had the same issue? Can I add more infos to help you solve the matter?

**Comment by mimugmail** [comment]
I'd check the NIC driver and switch OpenSSL for testing

**Comment by fichtner** [comment]
It sounds like a system issue that can either be solved by tweaking system parameters or upgrading hardware... so the guess is no more buffers in the operating system for networking... small hardware with low RAM possibly?
