### ISSUE TITLE
practicality of read-only config.xml API endpoint

### ISSUE THREAD

**Issue by fichtner** [opnsense/core#2731]
To be discussed, see https://forum.opnsense.org/index.php?topic=9707.0

**Comment by ccesario** [comment]
+1

**Comment by AdSchellevis** [comment]
I'm not against an endpoint for config retrieval, although I believe it should be part of a rewrite for diag_backup.php, since it's overlapping functionality. It's not very high on my list of things to work on to be honest. 

Building a plugin that only serves a download config isn't much work, for consistency reasons probably won't be offered by us (certainly not in core, without replacing the old backup solution).

**Comment by fichtner** [comment]
I was thinking such a temporary spot could maybe reside in the firmware API?

**Comment by AdSchellevis** [comment]
It could, but eventually the backup api should probably have a different endpoint to better control access (people able to upgrade might not be granted access to everything that's stored in the box).

Another short term solution could be to add the download action to `diag_backup.php` which makes it the responsibility of whoever is going to replace this code in the future (which isn't a big issue given the functionality should be in the new api as well).

**Comment by fichtner** [comment]
The issue with diag_backup.php or any other static page is that it's not API-key enabled. Otherwise that'd be working already...

**Comment by AdSchellevis** [comment]
sorry, my mistake, moving the download to a new spot at a different namespace and using it in the legacy page could also be an option (kind of a hybrid approach), but the risk stays that eventually nobody is willing to invest into the real elephant in the room (moving the functionality), creating an indefinite hybrid component.... 

Adding a plugin with only a download action is easy to build and doesn't taint our support status (could stay at community support level) and can use it's own access control (lower risk of leaking sensitive data).

**Comment by fichtner** [comment]
Now that you mention it... great idea to go forward indeed. :) That satisfies requirements from all sides and does not create roadblocks. Shall I move this to plugins then with a concrete plan?

**Comment by AdSchellevis** [comment]
sure, if anyone is planning to work on it, I would even offer help if needed (just don't want to own the plugin).

**Comment by fabianfrz** [comment]
Without encryption support, it would be an API endpoint with around less than 10 lines of code to download the current configuration.

**Comment by fichtner** [comment]
@fabianfrz is that a "I'll take it"? :)

moving over to https://github.com/opnsense/plugins/issues/865
