### ISSUE TITLE
Captive Portal:  Connection Drop for "Allowed" MAC addresses

### ISSUE THREAD

**Issue by MagnaPilot** [opnsense/core#2732]
This issue has been present since at least the 16 series that I have experienced, and to this point I have not found a solution, but have found others with the same issue.

Specifically, when using Captive Portal, and allowing some devices access via the MAC access list, eventually, after a seemingly arbitrary amount of time, between minutes and weeks, the devices given access via the MAC list will start to drop connections at random, downloads are impossible and the perception to the user is a very slow network. This issue does not occur at the same time to users who are authenticated via username/password on the same captive portal zone. The issue is present regardless of the status of proxy, IDS, firewall or otherwise. I'm willing to contribute any logs needed to help diagnose, I've been trying to trace this issue for nearly two years without success.  I am going to test "Allowed by IP" and see if that performs any differently once the issue returns and will report back.

Thank you

**Comment by AdSchellevis** [comment]
timeout

**Comment by patovala** [comment]
I'm experiencing same behaviour. I'm using OPNsense 22.1-amd64, FreeBSD 13.0-STABLE, OpenSSL 1.1.1m 14 Dec 2021.  I've trying to debug this issue and basically when the captive portal is on and adding a mac into the allowed mac lists, any download from those machines is randomly dropped. Seems like the transparent proxy gets activated in the middle, also git drops with:

**Comment by tomacco81** [comment]
I have the same problem :(
OPNsense 22.1.8_1-amd64
