### ISSUE TITLE
Feature request: make beep.sh customization survive upgrades

### ISSUE THREAD

**Issue by soder10** [opnsense/core#2734]
Hello dear devs!

Is it possible to make the customized content of "beep.sh" part of the core config, so it is not overwritten by the next firmware update?

**Comment by fichtner** [comment]
Hi @soder10,

Since the script hasn't changed over the years and I don't see work happening there I'd suggest a simpler approach: exchanging the script at boot start / stop time via our https://docs.opnsense.org/development/backend/autorun.html rc.syshook facility so you can move your beep.sh copy back to be the actual script that's going to be executed.


Cheers,
Franco

**Comment by soder10** [comment]
Hi @fichtner,

you mean, if I create my own custom beep.sh (e.g. modified parameters inside the script) and  copy it to both to /usr/local/etc/rc.syshook.d/start/ and /usr/local/etc/rc.syshook.d/stop/  --> give it some custom name, then the original boot.sh will be bypassed and only my custom beep.sh will be executed only?

**Comment by fichtner** [comment]
almost, the start and stop script will have to overwrite the original beep.sh before it is used

**Comment by soder10** [comment]
Sorry for my ignorance, but closing this issue means your recommendation to copy beep.sh into the autorun rc.syshook is the solution for the future?

**Comment by fichtner** [comment]
I took the lack of further response as a sign that the proposed solution works? I really don’t want a ticket around for a feature request that will not be worked on by the core team. It would be nicer if the Pull Request would be opened, reviewed and merged for a more portable solution when it was prepared by a submitter.

**Comment by soder10** [comment]
You arw right, I did not provide feedback. Actually I got stuck reading the dev docs about this syshook architecture, and what needs to be done where. Maybe its too high for me :-) I am not a Linux/BSD dev at all.

**Comment by fichtner** [comment]
I'm more than happy to walk you through it. You have your modified beep.sh, right?

**Comment by soder10** [comment]
Thanks for the support! Yes, I have a custom "beep.sh" in /usr/local/sbin, with some custom values inside. I made a backup of the original and called it as beep.sh.original in the same dir, just in case.

I checked /usr/local/etc/rc.syshook.d/start, and it has the following file: "95-beep", its content is:

#!/bin/sh
/usr/local/sbin/beep.sh start

Similarly, /usr/local/etc/rc.syshook.d/stop, and it has "05-beep", its content is:

#!/bin/sh
/usr/local/sbin/beep.sh stop

So if /usr/local/sbin/beep.sh is edited, the change will be in effect until the beep.sh is restored to Opnsense default during a possible upgrade. 

To avoid such overwrite, I would need to create a new file "beep.sh.custom", and modify the startup rc.syshook.d/start to add a new sequence before 95:
"94-copy-beep" with such content:
cp /usr/local/sbin/beep.sh.custom /usr/local/sbin/beep.sh

Similarly for rc.syshook.d/stop
"04-copy-beep" with such content:
cp /usr/local/sbin/beep.sh.custom /usr/local/sbin/beep.sh

Would that be the future-proof solution? Or am I missing the whole point here?

**Comment by fichtner** [comment]
This is exactly right. But use the following content:

```
#!/bin/sh
cp /usr/local/sbin/beep.sh.custom /usr/local/sbin/beep.sh
```

And do this:

```
# chmod 755 /usr/local/etc/rc.syshook.d/start/94-copy-beep /usr/local/etc/rc.syshook.d/stop/04-copy-beep
```

You could even build a single file installable plugin for this in case you need to install it on different machines, but that's for later if needed.

**Comment by soder10** [comment]
Cool, thanks!
