### ISSUE TITLE
Config templates : optional use of sub modules and the option to recursively generate templates

### ISSUE THREAD

**Issue by AdSchellevis** [opnsense/core#274]
The current version creates templates per module, but sometimes it’s only necessary to generate some files of the module (for example a subcomponent from IDS to update rulesets may not need to regenerate the full configuration). Optional splitting things into parts may solve this.
When we implement this, we also need the option to generate all templates from the module including sub modules and perhaps also all templates used by the system (to use when the system starts)

**Comment by fichtner** [comment]
@AdSchellevis the sample data is still there, should it be removed?

**Comment by AdSchellevis** [comment]
@fichtner I would rather keep a sample because it uses more features then the helloworld sample, but I will move it out of the way so it won't generate automatically.

**Comment by fichtner** [comment]
@AdSchellevis as long as the error is fixed it can also stay there. no clue what condition triggers this, have been unable to reproduce and the backtrace was never complete

**Comment by AdSchellevis** [comment]
@fichtner A wrong assumption from my end :) I removed the offending code.
