### ISSUE TITLE
[Feature request] Use Unattended-Upgrades

### ISSUE THREAD

**Issue by zero77** [opnsense/core#2740]
Hi
Can you please use unattended-upgrades to automatically check for and install updates, it can also be configured to uninstall unused software and a rainge of other related things.

To my knowledge it now comes installed by default on a lot of modern Linux distros like ubuntu but, it needs configuring to take care of updates.
Thanks

https://github.com/mvo5/unattended-upgrades

**Comment by zero77** [comment]
@fichtner  Hi
Are all updates included in this cron job.

**Comment by fichtner** [comment]
yep, it'll also reboot if necessary in case of OS updates

**Comment by zero77** [comment]
ok, thanks.
