### ISSUE TITLE
VPN:OpenVPN: Client Export doesn`t see server in the list

### ISSUE THREAD

**Issue by jsn0w** [opnsense/core#2743]
I have created new server but I don`t see it in the list in VPN:OpenVPN:Client Export 

OPNsense 18.7.3-amd64
FreeBSD 11.1-RELEASE-p14
OpenSSL 1.0.2p 14 Aug 2018

**Comment by fichtner** [comment]
The process is described here: https://docs.opnsense.org/manual/how-tos/sslvpn_client.html

There is not enough information in your report to guess which step was omitted.

**Comment by jsn0w** [comment]
> The process is described here: https://docs.opnsense.org/manual/how-tos/sslvpn_client.html
> 
> There is not enough information in your report to guess which step was omitted.

sorry it`s my fault. I had mistake at server settings. Thank you.

**Comment by fichtner** [comment]
@jsn0w no, problem. Was it not set to user auth?

**Comment by jsn0w** [comment]
> @jsn0w no, problem. Was it not set to user auth?

yes, it is.
