### ISSUE TITLE
6 columns - with latest table fix - still problem in firewall log view on dashboard

### ISSUE THREAD

**Issue by opnsenseuser** [opnsense/core#2745]
![grafik](https://user-images.githubusercontent.com/34602360/45914113-a8901780-be40-11e8-82e2-9613cdbdc5f6.png)

![grafik](https://user-images.githubusercontent.com/34602360/45914136-ec831c80-be40-11e8-9e02-17c9248e4a5e.png)

![grafik](https://user-images.githubusercontent.com/34602360/45914146-2c4a0400-be41-11e8-9cdb-518be441b1c3.png)

![grafik](https://user-images.githubusercontent.com/34602360/45914169-67e4ce00-be41-11e8-9015-bfea46078112.png)

**Comment by fichtner** [comment]
There are only three possibilities when there is not enough space (this is the underlying issue, nothing else) so:

Overflow, cutoff, or text-wrap.

The first fix we did made the overflow bearable not breaking the tables / zebra at the same time. Progress. :)

Martin then added text wraps recently in one widget. I've added it to a few more, but it's a larger effort to fix all widgets.

**Comment by marjohn56** [comment]
And it's not going to be very easy with this widget, here's what happens when a v6 entry appears. So it will need wrapping for both source and destination.

![image](https://user-images.githubusercontent.com/17962918/46130143-727fd880-c230-11e8-8fa5-ecebbfd2547e.png)

**Comment by opnsenseuser** [comment]
@marjohn56 any news on this?
Regards rene

**Comment by marjohn56** [comment]
Not yet René, sadly I have very little spare time at present. I'll try and look at this as soon as I'm able.

**Comment by fichtner** [comment]
It's back to the old issue now. It wraps text but Firefox ignores it. I would like to move on to other issues as it's not very fixable because it all goes back to "you're not giving the widget enough space to display its values".
