### ISSUE TITLE
Firewall log widget edit - Show error

### ISSUE THREAD

**Issue by opnsenseuser** [opnsense/core#2747]
![grafik](https://user-images.githubusercontent.com/34602360/45919314-bc189e00-be93-11e8-9c3b-bd56b21fb8d9.png)

![grafik](https://user-images.githubusercontent.com/34602360/45919346-4234e480-be94-11e8-9aa3-4514a36a7e38.png)

**Comment by opnsenseuser** [comment]
using 6 columns!

**Comment by fichtner** [comment]
ouch. I'll fix this...
