### ISSUE TITLE
firewall host alias with dhcp/dnsmasq

### ISSUE THREAD

**Issue by thutex** [opnsense/core#2749]
using dnsmasq, i register dhcp leases into dns.
when i subsequently wish to use one of those hostnames in the alias table for the firewall,
i get an error saying its not a valid hostname.

using for example firewall.lan (fqdn for the firewall) works, but using pc_name.lan (ip assigned through dhcp and registered in dnsmasq, and pingable through that name) i get the error.

this means you cannot add an alias based on the hostname when the hostname includes a _.

**Comment by fichtner** [comment]
Hi @thutex, there are a number of open tickets regarding this and its technical difficulties. Let's gather all info in one request, ok?

https://github.com/opnsense/core/issues/2373


Cheers,
Franco

**Comment by thutex** [comment]
hi Franco,
i searched the bugs but didnt find anything about this.
its also not a feature request, but a bug in the gui/logic for validating fqdn hosts i think?

**Comment by fichtner** [comment]
Sorry, I misread. There is an issue with alias and "-", but "_" works...

https://github.com/opnsense/core/issues/1434

... however, "_" is not a valid host name character as far as I know, so I'm not 100% sure what's going on here.

**Comment by fichtner** [comment]
@thutex ok, I'll try to see if the system can easily return a clear "_" validation error message instead of complaining about the allowed chars. :)

**Comment by fichtner** [comment]
This is ok in 18.7.10:

The name must be less than 32 characters long and may only consist of the following characters: a-z, A-Z, 0-9, _
