### ISSUE TITLE
system: dnsallowoverride isset() vs !empty() and shell script XML parsing fails

### ISSUE THREAD

**Issue by fichtner** [opnsense/core#2751]
https://twitter.com/l33tname/status/1043783662410616832

**Comment by fliiiix** [comment]
Unfortunately I don't have steps how to reproduce it.

**Comment by fichtner** [comment]
@fliiiix no worries, I found two spots that don't seem to do the right thing. You can try the patch via:

    # opnsense-patch a07dca9

If you go to System: Settings: General and save once it should no longer happen :)

I just have to see if all readers of the setting do the right thing as well otherwise the write fix is pointless.

**Comment by fichtner** [comment]
Surprisingly, the wizard does the right thing also so the patch will be shipped in 18.7.4 and that's it. :)

**Comment by fliiiix** [comment]
Amazing :tada:

**Comment by fichtner** [comment]
You know how they say... just a normal day for bicycle repair man.

https://www.youtube.com/watch?v=5Lwjv_VRM7A

;)
