### ISSUE TITLE
add RADIX_MPATH option to kernel

### ISSUE THREAD

**Issue by flatterlight** [opnsense/core#2752]
to enable ecmp the kernel needs option "RADIX_MPATH"

**Comment by fichtner** [comment]
Hi @flatterlight,

I don't believe we will deviate from the precedent set by FreeBSD to not include this option. The build system allows to build different kernels and the core system can lock them so you don't run the risk of breakage on updates.

If you need help with these two points I'm happy to answer related questions.


Cheers,
Franco
