### ISSUE TITLE
Add validation to model that only one of two checkboxes are ticked

### ISSUE THREAD

**Issue by mimugmail** [opnsense/core#2757]
As discussed with @AdSchellevis in IRC I need a validator like 

https://github.com/opnsense/core/blob/b36a3906e47f3e5d85bd8a1dd0057d7f3c774d8d/src/opnsense/mvc/app/models/OPNsense/Proxy/Proxy.xml#L163-L171

but reversed, so only one checkbox is allowed to be ticked.

Concrete it's for adding PIE to Shaper in parallel to CoDel. Problem is that only one of them has to be ticked. Normally I'd change it to from checkbox to dropdown, but I'm unsure about a totally different UX.

**Comment by AdSchellevis** [comment]
@mimugmail https://github.com/opnsense/core/commit/89802d77b6cd1cc68c567086214b1f3d6080965b  should do the trick
