### ISSUE TITLE
The field 'IPv4 Local Network' must contain only valid ipv4 CIDR range(s) separated by commas.

### ISSUE THREAD

**Issue by dzikus** [opnsense/core#2758]
Since 18.7 in VPN->OpenVPN->Servers in field "IPv4 Local Network" I cannot set valid ipv4 CIDR with mask 32 for example: 10.0.0.1/32.

In previous versions it was working and set route with such mask. Now I cannot save such setting in GUI.

**Comment by fichtner** [comment]
https://github.com/opnsense/changelog/blob/master/doc/18.7/18.7.2#L38

**Comment by dzikus** [comment]
I tested in on 18.7.3 and it works 👍

**Comment by fichtner** [comment]
thanks :)
