### ISSUE TITLE
Request: Add uuid field to the result of addBase

### ISSUE THREAD

**Issue by fvanroie** [opnsense/core#2760]
**Issue**
One of the problems when creating a CRUD item via the API is figuring out what the uuid is of the newly created item. Current only `{"result":"saved"}` gets returned upon successful creation.

**Proposal**
I want to propose the addition of the uuid in the response, so programs consuming the API can easily and reliably find the new object uuid: e.g. `{"result":"saved","uuid":"3ffc6cce-233a-483e-95d8-dd9adacbba5a"}`

**Solution**
This can be achieved via the addBase() helper function:

https://github.com/opnsense/core/blob/f8178e98d3c38dfc210720dc27000e960a9f04be/src/opnsense/mvc/app/controllers/OPNsense/Base/ApiMutableModelControllerBase.php#L298

Add uuid to the result array:
```
                $result = array(
                        "result" => "saved",
                        "uuid" => str_replace($path . ".", "", $node->__reference)
                );
```
If this is OK I can create a Pull request.

**Comment by fichtner** [comment]
please do and ask @AdSchellevis to review

**Comment by fvanroie** [comment]
Thanks @fabianfrz. This is indeed a quick fix. I've considered the impact since it's a change in the Base controller. This feature would best be included in a major update, which should be properly tested by API clients for compatibility issues anyways.

Another possibility I've seen is to [include a Location header](https://www.restapitutorial.com/lessons/httpmethods.html) with the URI to the new item that would also include the uuid. However this is part of a REST methodology that uses verbs and http response codes to indicate the result of the operation. I can investigate this avenue, but it will take considerably more effort.

Short of it is that I believe this proposal will benefit API clients more than it _might_ do any harm.

**Comment by fabianfrz** [comment]
@fvanroie I know this behaviour from @rails which does it on browser requests in automatically generated controllers (rails scaffold), where it contains a link in the location header to the created element. The browser follows it and the API client can read the data.

**Comment by fichtner** [comment]
> Thanks @fabianfrz. This is indeed a quick fix. I've considered the impact since it's a change in the Base controller. This feature would best be included in a major update, which should be properly tested by API clients for compatibility issues anyways.

This will land in 18.7.5 without much noise. It's imperial that APIs are robust enough to deal with this so we would assume everything that breaks needs fixing anyway. Discussed with @AdSchellevis.

**Comment by fvanroie** [comment]
Great, thanks @fichtner. I'll make sure to test against 18.7.5 when released.
