### ISSUE TITLE
Create a kind of modal "Loading page ... please wait ..." ?

### ISSUE THREAD

**Issue by opnsenseuser** [opnsense/core#2775]
@fichtner 
I was just wondering if it would make sense for all sides to create a kind of "Loading page ... please wait ..." modal window when a new page is loaded or a page is saved. That would be very helpful, because sometimes you unintentionally clicks too early somewhere or it is not always clearly recognizable. Sometimes there are buttons that indicate it by a spinnig icon, but generally I would consider it useful to inform the user about it. This is just an idea and for me now counts the completion of the last sidebar problem. But I thought I could work on something like this when I finished the sidebar. Do you think the idea useful or meaningless? 

if you do not like this idea just delete this!

best regards rené

**Comment by fabianfrz** [comment]
It would make sense when we would have a single page application (backbone, vue or angular) where you would have the start and the end event but in our case it is quite hard because this is not the case.
If you switch, you can show the spinner theoretically two times:
* button / link clicked until the page is replaced
* the new page is being loaded until the JS gives a notification (everything is ready)

Inbetween you have some undefined behaviour.

**Comment by AdSchellevis** [comment]
quite some pages already show spinners in the action buttons, I don't think there's a need for much more then that.

**Comment by AdSchellevis** [comment]
@opnsenseuser Adding missing spinners if there's a lack of user response is certainly a good idea.

**Comment by opnsenseuser** [comment]
@AdSchellevis what would be the easiest way to provide all save buttons with a spinning wheel?

**Comment by opnsenseuser** [comment]
@fichtner What do you think about? spinning wheel for all Save Buttons or modal window? imagine the modal window via unload page with javascript.

best regards

**Comment by AdSchellevis** [comment]
@opnsenseuser you can't do all at once, it's depending on the page (only applicable for mvc pages by the way).

Usually they do something like:
https://github.com/opnsense/core/blob/7835b70c6bedad6e2851670637008f2ea86f10a6/src/opnsense/mvc/app/views/OPNsense/Proxy/index.volt#L274-L302

Where the action (if it consumes some time) triggers the `addClass` and removes the class using `removeClass` when finished.


Personally I haven't found obvious places with missing feedback, but if there are, we could consider adding them like above.
Add spinners to modal dialogs doesn't really bring anything, they close after save...

**Comment by fichtner** [comment]
modals are nice if you want to convey information for confirmation or why a system is doing something while you wait. for save and apply  buttons it's probably better to use spinners.

The nice thing about the static pages is you just have to start the spinner on click and the page reload will take care of the reset. The bad thing about static pages is that every button needs to be patched, at least with a class to inject the click handler selectively.

**Comment by fichtner** [comment]
timeout
