### ISSUE TITLE
Question: Should an api be able to call /api/core/menu/* actions?

### ISSUE THREAD

**Issue by fvanroie** [opnsense/core#2778]
**Issue**
I want to display the OPNsense menu hierarchy as a console application, so I decided to look into the `/api/core/menu/search` and `/api/core/menu/tree` actions. However I couldn't get these to work using the API authentication method. Whatever I tried, it only returns the `Lobby / Logout` item.

**Wanted result**
When logged on in the WebGUI as the api user, the endpoints return all the menu items. I want to achieve the same result using the API authentication.

**Cause**
After some digging, it appears that these endpoints are not supported when accessing them via the API authentication. They only work correctly from a PHP session that is logged on...

https://github.com/opnsense/core/blob/8fba640bc680c8d7a03453445baac5d6ce831048/src/opnsense/mvc/app/controllers/OPNsense/Core/Api/MenuController.php#L122-L125

No username is set when using the API authentication, hence only `Lobby / Logout` is returned.

**Question**
I wonder if there is a specific reason only the Web session is checked? Or would it be acceptable to expose the menu items via the api as well?

**Workaround**
I copy/pasted some code from the routing, and now I can get these endpoints to work via the api as well:

```
       // get username into context
        if ($this->session->has("Username")) {
            $this->username = $this->session->get("Username");
        } else {

            // authenticate api user
            $authHeader = explode(' ', $this->request->getHeader('Authorization'));
            if (count($authHeader) > 1) {
                $key_secret_hash = $authHeader[1];
                $key_secret = explode(':', base64_decode($key_secret_hash));
                if (count($key_secret) > 1) {
                    $apiKey = $key_secret[0];
                    $apiSecret = $key_secret[1];
                    $authFactory = new AuthenticationFactory();
                    $authenticator = $authFactory->get("Local API");
                    if ($authenticator->authenticate($apiKey, $apiSecret)) {
                        $authResult = $authenticator->getLastAuthProperties();
                        if (array_key_exists('username', $authResult)) {
                            $this->username = $authResult['username'];
                        }
                    }
                }
            }

        }
```
I will investigate this avenue further, if I can actually achieve my goal via this workaround. It will allow to browse the tree like a filesystem:

```
PS C:\> cd OPN:
PS OPN:\> ls

    Directory: OPN:

Mode  Name
----  ----
+     Lobby
+     Reporting
+     System
+     Interfaces
+     Firewall
+     Routing
+     VPN
+     Services
+     Power

PS OPN:\> cd Lobby
PS OPN:\Lobby> pwd

Path
----
OPN:\Lobby

PS OPN:\Lobby>
```

If there are no objections to also implement the API way, I can make a PR too.

**Comment by AdSchellevis** [comment]
@fvanroie we should probably add something similar one level higher, let me take a look at this. It would indeed be better if you can access the menu over the api too.

**Comment by fvanroie** [comment]
Thanks @AdSchellevis. I'm doing a proof-of-of-concept with the *workaround*. I will welcome a more robust and future-proof method. This feature opens up some interesting possibilities. I can gladly assist or test where needed.

**Comment by AdSchellevis** [comment]
@fvanroie can you try https://github.com/opnsense/core/commit/ce98b297fa8527abd5306e148b1f1d564c03051d ? I've refactored some stuff, removed the authentication hook from the controller and added the `getUsername()` call to our base controllers

**Comment by fvanroie** [comment]
Great! I have reverted my local changes and applied the path. Now it's working as expected.

**Comment by AdSchellevis** [comment]
@fvanroie I'll close the issue then, after some time on development it can go to 18.7.x probably
