### ISSUE TITLE
Virtual IPs in Port Forward: Network treated as single address

### ISSUE THREAD

**Issue by TheEvilCoder42** [opnsense/core#2783]
Hello

After configuring a virtual network in 'Virtual IPs' with type 'Other' and selecting this entry in the drop-down list in 'Port Forward > Destination' I get a single address.

![image](https://user-images.githubusercontent.com/35196983/46374234-82644600-c690-11e8-8f13-1194fc57205c.png)

![image](https://user-images.githubusercontent.com/35196983/46374279-a031ab00-c690-11e8-8e1e-a298cfc53192.png)

If I select 'Single host or Network' the entry is shown as single address with /32.

![image](https://user-images.githubusercontent.com/35196983/46374375-dc650b80-c690-11e8-8b0c-380b5736e10e.png)

I would expect the network gets entered correctly.

I didn't saw this mentioned anywhere, so I thought I would raise an issue.

**Comment by AdSchellevis** [comment]
@TheEvilCoder42 thanks for the report, proxyarp and other should have been treated equally, which is fixed in https://github.com/opnsense/core/commit/9ee4921d427b0068bb9a73172bd2750f7aabaf7d .
