### ISSUE TITLE
squid: modifying SSL options

### ISSUE THREAD

**Issue by falcon78921** [opnsense/core#2786]
In my environment, I have end users who require the use of legacy web applications. These web applications require TLSv1.0. 

I have OPNSense installed and acting as an edge device. Here's my setup:

```
OPNsense 18.7.4-amd64
FreeBSD 11.1-RELEASE-p14
OpenSSL 1.0.2p 14 Aug 2018
```

Looking at the template for ```squid.conf```, I found this:

```
{% if helpers.exists('OPNsense.proxy.forward.sslbump') and OPNsense.proxy.forward.sslbump == '1' %}
# setup ssl re-cert
sslcrtd_program /usr/local/libexec/squid/ssl_crtd -s /var/squid/ssl_crtd -M {{ OPNsense.proxy.forward.ssl_crtd_storage_max_size|default('4') }}MB
sslcrtd_children {{ OPNsense.proxy.forward.sslcrtd_children|default('5') }}

sslproxy_cipher HIGH:MEDIUM:!RC4:!aNULL:!eNULL:!LOW:!3DES:!MD5:!EXP:!PSK:!SRP:!DSS
sslproxy_options NO_TLSv1
```
I know TLSv1.0 is obsolete, I get that. Unfortunately, some people don't understand this. My hands are tied. I really like OPNSense. OPNSense has really improved our infrastructure and the Squid module helps with necessary content filtering. In order for my administration to not eliminate OPNSense, I need to get TLSv1.0 working for legacy web applications.

Is there a way, through the GUI or custom configuration, that I can replace ```sslproxy_options NO_TLSv1``` to ```sslproxy_options ALL```? Is there something I'm missing?

This issue and #2777 are paramount to keeping OPNSense in our environment. :)

**Comment by AdSchellevis** [comment]
You **really** don't want to do that, it would basically mean that all traffic can be downgraded to insecure protocols without the enduser having an idea about it. 

If you don't want security on specific old internal addresses, you probably better don't forward that traffic to the proxy (disable nat for specific targets and allow traffic directly).

Taking in consideration that people might accidentally enable this option, I don't think we should provide it.  

If you still want to do this, you could disable bumping and add a custom template with your options (see pre/post-auth plugins in https://github.com/opnsense/core/blob/master/src/opnsense/service/templates/OPNsense/Proxy/squid.conf )

**Comment by falcon78921** [comment]
@AdSchellevis I agree 100% with you on this. I also understand not having this as a feature.

**Comment by falcon78921** [comment]
Thanks! @AdSchellevis :)
