### ISSUE TITLE
alias: URL Table alias gets flushed when webserver is unavailable

### ISSUE THREAD

**Issue by mimugmail** [opnsense/core#2793]
As discussed @AdSchellevis in IRC, when you create a URL Table alias with an expiry of e.g. 1hour, the systems tries to flush and fetch the the definitions via URL. If the webserver is unavailable (down, unrouteable whatever) the pfTable get's flushed (empty) and stays empty.

This could be a security risk when using this alias in a blocklist since the rule would be skipped when the alias is emtpy (since no match). There should be some kind of caching when the host is unavailable.

**Comment by AdSchellevis** [comment]
@mimugmail can you try https://github.com/opnsense/core/commit/8d08b67d28c6d37ea26d2bd39f0f830c6a01be0a ?

**Comment by mimugmail** [comment]
It works, thank you for your fast fix 👍 🥇
