### ISSUE TITLE
WEB GUI: Usage of the same VHID Group for muliply CARP IP

### ISSUE THREAD

**Issue by apas-iut** [opnsense/core#2795]
It is impossible to use same the VHID more than twice on the same WAN/LAN/VLAN interface. If any interface already has two CARP IPs with the same VHID then it's impossible to make any other interface with two CARP IPs with any other unique VHID.
The problem was already solved [here](https://github.com/opnsense/core/issues/1779) but it still exists!

**Tested on version:**
  OPNsense 18.7.4-amd64
  FreeBSD 11.1-RELEASE-p14

**Steps to reproduce:**
1. Firewall > Virtual IPs > Settings. Add CARP IP for any interface.
2. Add second CARP IP to the same interface with the same VHID.
3. Add third CARP IP to the same interface with the same VHID.

**Expected:** 3 Different CARP IPs with the same VHID Group on interface.
**Bug:** An error message in web gui _"VHID XXX is already in use on interface YYY. Pick a unique number on this interface."_

Workaround. I just downloaded the xml-config, edited the < virtualip > section, applied it to the router and got what I need with single VHID for the whole firewall as described [here](https://lists.freebsd.org/pipermail/freebsd-stable/2014-September/080067.html)

ifconfig output is listed bellow
lagg0:
        inet 192.168.0.2 netmask 0xffffff00 broadcast 192.168.0.255
        inet 192.168.0.1 netmask 0xffffff00 broadcast 192.168.0.255 vhid 107
        inet 192.168.10.1 netmask 0xffffff00 broadcast 192.168.10.255 vhid 107

lagg1:
        inet 192.168.101.2 netmask 0xffffff00 broadcast 192.168.101.255
        inet 192.168.101.1 netmask 0xffffff00 broadcast 192.168.101.255 vhid 107
        inet 192.168.102.1 netmask 0xffffff00 broadcast 192.168.102.255 vhid 107
        inet 192.168.105.1 netmask 0xffffff00 broadcast 192.168.105.255 vhid 107

lagg1_vlan43:
        inet 192.168.104.1 netmask 0xffffff00 broadcast 192.168.104.255 vhid 107
        inet 192.168.109.1 netmask 0xffffff00 broadcast 192.168.109.255 vhid 107
        inet 192.168.124.1 netmask 0xffffff00 broadcast 192.168.124.255 vhid 107

**Comment by AdSchellevis** [comment]
You need to assign an IPalias using the same vhid if you would like to re-use the same on multiple addresses. Which is by the way also noted in https://github.com/opnsense/core/issues/1779#issuecomment-324400002

**Comment by apas-iut** [comment]
The problem with ipalias that it does not sync with backup node even with system_hasync.php force.

**Comment by AdSchellevis** [comment]
That's indeed unsupported

**Comment by apas-iut** [comment]
@AdSchellevis so is the proper solutions for this case?

If I want CARP + config sync then WEB GUI forces me to create a unique VHID group for every new interface and ip network. But the number of VHID is limited to 256. In addition every new VHID creates an extra unnecessary multicast group in network.

I don't see any real issue if opnsense will allow users to utilize the same VHID group for different interfaces and ip networks since it is allowed by FreeBSD and works in real environment.

**Comment by AdSchellevis** [comment]
use ip-aliases, setup manually on the backup node.

**Comment by apas-iut** [comment]
Manual setup is very inconvenient an unreliable solution in case if you have 50+ aliases.
I still don't understand the idea of prevention of usage the same vhid group in web gui.

**Comment by mimugmail** [comment]
@AdSchellevis while debugging my comment on https://github.com/opnsense/core/issues/2780#issuecomment-430726706 I stumbled upon this one. 

Indeed, I created an IP Alias on an existing vhid and then both units where master for this vhid. As soon as I manually added the IP Alias on the second node the master / backup setup was correct again. 

Is this a bigger issue adding IP Alias to xmlrpc?

**Comment by AdSchellevis** [comment]
@mimugmail not sure what you mean, but ip aliases need to be created on both machines, using the correct advskew for each one of them.

**Comment by mimugmail** [comment]
you mean setting the correct vhid since skew is greyed out. 
is this a historical reason why carp vip's are synchronized to slave and alias not? 

for me both is ok, but then I'd update the docs to make this clear :)

**Comment by AdSchellevis** [comment]
You just can't sync regular aliases, since it would lead to ip conflicts, it should be possible to add similar logic to ip aliases which have vhid's as carp, but ideally they would have a different type for better distinction (something like carp-alias, which should ideally validate if the actual carp vip is there).

**Comment by mimugmail** [comment]
Good idea! I'd leave this decision to you as you'd have most part of the work. In the meantime I'll add a note to the existing doc .. thx 👍

**Comment by clystron** [comment]
Note: after adding IP-Aliases on the same VHID the "orginal" CARP entry can no longer be edited because the VHID is detected as non-unique. Tested on 18.7.6

**Comment by AdSchellevis** [comment]
https://github.com/opnsense/core/commit/754d483b868f9a46c05051b1881da8b4974d2ec2

**Comment by AdSchellevis** [comment]
Closed the issue in favour of https://github.com/opnsense/core/issues/3034 for the remaining part
