### ISSUE TITLE
Static Routes synchronization does not work

### ISSUE THREAD

**Issue by apas-iut** [opnsense/core#2796]
Same problem as described in this [issue](https://github.com/opnsense/core/issues/254)

**Tested on version:**
OPNsense 18.7.4-amd64
FreeBSD 11.1-RELEASE-p14

**Steps to reproduce:**
1. Setup XMLRPC Sync between master and slave nodes. Activate synchronizestaticroutes=on parameter on master node.
2. Add a new gateway on master. Gateway successfully syncs with slave node
3. Add a new route using new gateway on master.

**Expected:** A new route syncs to slave node.
**Bug:** Route does not sync.

**Comment by AdSchellevis** [comment]
What happens if you restart a service from the master on the backup (status_habackup.php)? These config sections need a trigger to sync to the remote side, which isn't provided automatically.

**Comment by mimugmail** [comment]
Yes this is reproduceable, I remember I asked you the same in IRC some months ago. When opening a firewall rule, do nothing and apply again, then it was synced.

**Comment by AdSchellevis** [comment]
We should probably add a button to the status_habackup page, which only triggers a sync (to make it more explicit), since we're not going to add a sync on mvc config changes. 
9 times out of 10 you need to reconfigure services on the backup anyway.

**Comment by mimugmail** [comment]
A "Force Sync" button would be very cool <3

**Comment by apas-iut** [comment]
Forcing synchronization at system_hasync.php does help. Routes successfully migrate to the slave node.
Regarding the proposal of an additions sync button, System>Routes>Configuration already has an Apply button with nice animation. Is it possible to trigger the config sync with this button?
![default](https://user-images.githubusercontent.com/43873009/46595301-2155cb80-caf1-11e8-99ea-3b71517eaa90.png)

**Comment by AdSchellevis** [comment]
https://github.com/opnsense/core/commit/9c947a748edf96c5224c03b4124c040eb35e578e makes the sync more explicit, we're not going to hack a sync trigger in every page (9 times out of 10 you really want to reload services after changes on master).
