### ISSUE TITLE
js/zone.js missing

### ISSUE THREAD

**Issue by FathiBenNasr** [opnsense/core#2797]
I have reviewed a lot of captive portal templates including the default one which comes with opnsense. They refer to a js/zone.js file which is missing.
Where can i find it ?

**Comment by fabianfrz** [comment]
It is autogenerated [here](https://github.com/opnsense/core/blob/eb95e8f53e56e25ce8f0898ee6936d8201bd9a29/src/opnsense/scripts/OPNsense/CaptivePortal/overlay_template.py#L58) and contains the id of the captive portal which is required different backend calls.

**Comment by FathiBenNasr** [comment]
Thanks.
