### ISSUE TITLE
OpenVPN - Routing or Gateway Issue?

### ISSUE THREAD

**Issue by iamperson347** [opnsense/core#2799]
Hi all,

It appears opensense is not assigning gateway addresses correctly when using an openvpn client as a "WAN" interface. At the surface, it appears this may only be affecting the gateway monitoring. However, I'm also not able to route traffic through the VPN client.

Notice below: the openvpn client gets an IP of 10.11.2.7.

Oct 11 23:18:19	opnsense: /usr/local/etc/rc.openvpn: OpenVPN: One or more OpenVPN tunnel endpoints may have changed its IP. Reloading endpoints that may use VPN_WAN_DHCP.
Oct 11 23:18:16	opnsense: /usr/local/etc/rc.newwanip: Adding static route for monitor 2620:0:ccc::2 via fe80::868a:8dff:fef0:3419%vtnet1
Oct 11 23:18:16	opnsense: /usr/local/etc/rc.newwanip: Removing static route for monitor 2620:0:ccc::2 via fe80::868a:8dff:fef0:3419%vtnet1
Oct 11 23:18:16	opnsense: /usr/local/etc/rc.newwanip: Adding static route for monitor 208.67.222.222 via xxx.xxx.212.1
Oct 11 23:18:16	opnsense: /usr/local/etc/rc.newwanip: Removing static route for monitor 208.67.222.222 via xxx.xxx.212.1
Oct 11 23:18:16	opnsense: /usr/local/etc/rc.newwanip: The command '/sbin/route add -host -'inet' '8.8.4.4' '255.255.255.0'' returned exit code '1', the output was 'route: writing to routing socket: Network is unreachable add host 8.8.4.4: gateway 255.255.255.0 fib 0: Network is unreachable'
Oct 11 23:18:16	opnsense: /usr/local/etc/rc.newwanip: Adding static route for monitor 8.8.4.4 via 255.255.255.0
Oct 11 23:18:16	opnsense: /usr/local/etc/rc.newwanip: Removing static route for monitor 8.8.4.4 via 255.255.255.0
Oct 11 23:18:16	opnsense: /usr/local/etc/rc.newwanip: ROUTING: skipping IPv6 default route
Oct 11 23:18:16	opnsense: /usr/local/etc/rc.newwanip: ROUTING: skipping IPv4 default route
Oct 11 23:18:16	opnsense: /usr/local/etc/rc.newwanip: ROUTING: IPv4 default gateway set to wan
Oct 11 23:18:16	opnsense: /usr/local/etc/rc.newwanip: ROUTING: IPv6 default gateway set to wan
Oct 11 23:18:16	opnsense: /usr/local/etc/rc.newwanip: ROUTING: entering configure using 'opt3'
Oct 11 23:18:16	opnsense: /usr/local/etc/rc.newwanip: On (IP address: 10.11.2.7) (interface: VPN_WAN[opt3]) (real interface: ovpnc1).
Oct 11 23:18:16	opnsense: /usr/local/etc/rc.newwanip: IP renewal is starting on 'ovpnc1'
Oct 11 23:18:16	kernel: ovpnc1: link state changed to UP
Oct 11 23:18:14	kernel: ovpnc1: link state changed to DOWN

Routes:

ipv4 | 10.11.2.0/24 | 10.11.2.1 | UGS | 0 | 1500 | ovpnc1 | VPN_WAN |  
-- | -- | -- | -- | -- | -- | -- | -- | --
ipv4 | 10.11.2.1 | link#7 | UH | 0 | 1500 | ovpnc1 | VPN_WAN |  
ipv4 | 10.11.2.7 | link#7 | UHS | 0 | 16384 | lo0 |   |  

------------------Original Issue Text Below ---------------------------------------------

I'm having a hard time pinpointing the root of this issue. 
1) Sometimes, the gateway for the VPN does not get assigned (0.0.0.0) or is assigned the wrong address (like 255.255.255.0)
2) It seems I can't get traffic to route out of the gateway (trying to do a tracrt, navigate to a site, etc.)

The VPN appears to be connecting correctly/etc., I just seem to be having trouble getting the routing to get set properly.

I'm trying to set up the following: 

Openvpn -> assign to VPN_WAN interface (DHCP ipv4)
Creation another interface (VPN) to act as a gateway (192.168.10.1/24)
Setup NAT for VPN_WAN -> VPN interface
Setup firewall rule on VPN interface to forward all traffic out of of VPN_WAN gateway

(I'm also doing other optional stuff like tagging traffic, make sure it can't go out the regular WAN connection without going through VPN, etc.)

I know pfsense and opnsense are different. However, I can successfully get this working on pfsense with no issues. That is why I decided to open issue. I'm not sure what else to send along for debugging purposes, but am willing to provide logs/etc.

**Comment by iamperson347** [comment]
Also, here are the options I'm using on the VPN client

![image](https://user-images.githubusercontent.com/1909402/46640234-c051e600-cb38-11e8-8300-6a4f41a367d6.png)

**Comment by AdSchellevis** [comment]
If the routes are pushed from the server, you probably should disable "`Don't pull routes`"

**Comment by iamperson347** [comment]
Hi @AdSchellevis,

If I uncheck that, everything tries to go through the VPN. I'm trying to do policy based routing where one of my subnets get sent through the VPN while all other traffic goes through the normal WAN.

**Comment by AdSchellevis** [comment]
sounds like a more advanced config, can't help you with that using free support.

**Comment by iamperson347** [comment]
Ok. I'll get some more details when I get home. One of my main concerns is opnsense assigning an IP of 255.255.255.0 to the gateway instead of the openvpn client address (VPN). That's is more of a potential bug vs. support.

**Comment by iamperson347** [comment]
I've looked at this some more. I believe the root of the problem is gateway IP detection when the parent interface is assigned an openvpn client. When the gateway is set to "dynamic", the gateway is pulling "255.255.255.0" for the gateway IP which is the subnet mask instead of the openvpn assigned gateway. 

Subsequently, when 255.255.255.0 is pulled as the gateway IP, this incorrectly generates rules in the firewall (trying to route traffic to 255.255.255.0 instead of the proper gateway). 

![image](https://user-images.githubusercontent.com/1909402/46906872-49ba3d00-ced8-11e8-9c07-684e88ac4f95.png)

![image](https://user-images.githubusercontent.com/1909402/46906855-08c22880-ced8-11e8-993a-928d34d49924.png)

![image](https://user-images.githubusercontent.com/1909402/46906861-1a0b3500-ced8-11e8-8607-40991763b982.png)


![image](https://user-images.githubusercontent.com/1909402/46906831-8e91a400-ced7-11e8-9d20-a55be0ccf840.png)

This is what is causing the client machines on my local subnet for VPN clients to not be able to route traffic. If I set the gateway manually to the openvpn client gateway, clients can route traffic as expected.

What do you think? I'm not familiar with the opnsense codebase but I will try to look around and see if I can find where this is happening.

**Comment by AdSchellevis** [comment]
I expect the 255.255.255.0 comes from https://github.com/opnsense/core/blob/84f35e7088354070a997b1253a2cc886a662943f/src/etc/inc/gwlb.inc#L1077 which would suggest that the file `/tmp/{$realif}_router` contains `255.255.255.0`

Can you check / confirm that the file exists and contains the expected content.

Although I'm not sure the used configuration should actually be valid (the openvpn interface doesn't receive it's adres using dhcp), let see where this brings us.

**Comment by AdSchellevis** [comment]
@iamperson347 can you try https://github.com/opnsense/core/commit/58eaa625990da9b7a2daf258997f8667c0464c5f ? if this fixes your issue, we should add some glue for ipv6 as well.

**Comment by iamperson347** [comment]
With the patch, it looks like /tmp/ovpnc1_router is still getting set to 255.255.255.0.

I tried the following ("borrowed" from pfsense):

```
	if [ -n "${route_vpn_gateway}" ]; then
		/bin/echo ${route_vpn_gateway} > /tmp/${1}_router
	elif [ -n "${ifconfig_remote}" ]; then
		/bin/echo ${ifconfig_remote} > /tmp/${1}_router
	elif [ -n "${ifconfig_local}" ]; then
		/bin/echo ${ifconfig_local} > /tmp/${1}_router
	else
		/bin/echo ${5} > /tmp/${1}_router
	fi
```
That seemed to get /tmp/ovpnc1_router to be set correctly. The gateway also picked up the correct address (at least what matches my pfsense test vm). However, I was still having through getting traffic to route correctly out of the vpn (still trying to figure that one out).

**Comment by AdSchellevis** [comment]
your gateway is probably set to the local address, which wasn't in my patch.

**Comment by AdSchellevis** [comment]
@iamperson347 can you try https://github.com/opnsense/core/commit/54f4ec89bb50f80aada623c70fb4f018c3bbd3c8 for the gateway issue as well? 

It still looks a bit strange that the `/bin/echo ${5} > /tmp/${1}_router` does receive `255.255.255.0`, according to the openvpn docs it should contain the remote ip (which it doesn't seem to be able to find in your setup):

`cmd tun_dev tun_mtu link_mtu ifconfig_local_ip ifconfig_remote_ip [ init | restart ]
`

**Comment by fichtner** [comment]
Will be added in 18.7.8. please reopen if still relevant.
