### ISSUE TITLE
[RFE] Import pfSense Config

### ISSUE THREAD

**Issue by fraenki** [opnsense/core#28]
I think it would greatly ease migration to OPNsense if it would be possible to import a pfSense configuration. I don't care for the RRDs, but only the configuration.

This would make it easier for people to test OPNsense with their real-world configuration and possibly attract more people to try OPNsense.

Maybe this should be implemented alongside the OPNsense config backup/import feature (to allow OPNsense to diverge more from pfSense over time). Well, I guess it would be OK to support only the stable version of pfSense (not every old release).

**Comment by jschellevis** [comment]
In theory it should be possible to import the pfsense config from version 2.1.5 or earlier.. minus packages that is. However I think there is one small issue that prevents it to work now. I think the theme pfsense can't be found and there is no fallback.. I'll look into it, but we also need a more permanent solution at least for older pfsense branches.. don't think we like to keep supporting newer versions op pfSense as we would need to keep track of their changes..

**Comment by fichtner** [comment]
FWIW, I added a theme upgrade to the migration. This is just a work around. We need substantial reworks of the config file handling and migration. The handling of the root tag is weirdly hardcoded to <pfsense/>. More on this soon.

**Comment by AdSchellevis** [comment]
Nice! I'm working on the model / config in Phalcon to glue the new framework parts together. Maybe the most practical solution is to try to create a bridge like feature to the new config class as soon as this is kind of "feature complete".

**Comment by jschellevis** [comment]
Import works for pfsense configurations of 2.1.5 or earlier. Packages are not supported and Captive portal functionality differs.

**Comment by skarekrow** [comment]
Are there still plans to support migration from pfsense >=2.2? I'm sure others are like me, watching this project grow before they replace their setups. I have enough things that manually migrating would be frustrating. I understand if this isn't a priority, just checking if it's still on the roadmap or not.

**Comment by mircsicz** [comment]
+1 for me...

Just got an APU to replace my ALIX and I'ld like to switch, but with half a dozen IPSec's and some OpenVPN's it's nothing I could reconfigure in an hour!

**Comment by fichtner** [comment]
I'll reopen, but no promises or ETA. It's a lot of work and I don't want users to expect this works flawlessly...

**Comment by fichtner** [comment]
We've recently fixed a theme import issue, and I'll push a needed user cleanup as well. This is stuff for 2.1.5 but looks like it improves reliability a lot.

As for 2.2.x, I'd recommend changing version line to

    <version>11.1</version>

And try it out the config import in a VM to see if it boots and retains its settings. Unless I get some feedback/testing, I'm not able to continue as I don't have a 2.2.x config nor will have one so I am relying on user contributions. :)

**Comment by fichtner** [comment]
Any feedback regarding 2.2.x imports using the above workaround? 2.1.5 seems to work fine since the last fix, at least I haven't heard of any issues.

**Comment by skarekrow** [comment]
Sorry @fichtner I haven't tried it myself. Been quite busy. But I also have stuck to pfsense for the time being as I needed altq. I was unable to find a way to view any traffic shaping statistics in opnsense. So I haven't jumped ship yet :(

**Comment by fichtner** [comment]
that's alright @skarekrow maybe you can let me know what you are looking for in shaping statistics :)

**Comment by skarekrow** [comment]
@fichtner just basic statistics showing me the bits/kbits/mbits a second for each pipe/queue it is in. Nothing fancy is needed like pfsense's page, but something like m0n0wall had on it's `/status.php` page would be great.

I can open a separate issue as a enhancement request if you wish :)

**Comment by fichtner** [comment]
@skarekrow We do have a limiter status and a status.php -- might it already be there?! If m0n0wall had it it might be trivial to fix if not. :)

**Comment by skarekrow** [comment]
@fichtner I checked the status.php last with opnsense and I did not see it, it was quite a night, so I may have missed something! Limiter info doesn't seem to show me packets and what queue they are passing into. Maybe I am also missing something there?

**Comment by fichtner** [comment]
Don't think so, thanks for the feedback :) https://github.com/opnsense/core/issues/450

**Comment by skarekrow** [comment]
No problem, responded there :)

**Comment by fichtner** [comment]
I'm going to close this for good, very few people have asked for this since , workarounds seem to function, and the configs have drifted apart further. With new versions around the corner for both projects, it comes down to picking the one that works and sticking with it.
