### ISSUE TITLE
Feature Request: Create Certificates with Both Server & Client Extended Key Usage

### ISSUE THREAD

**Issue by addy90** [opnsense/core#2800]
When creating a certificate in Trust section of OPNsense, you have to select either Server, Client (or CA) as certificate extended key usage (Type row).

Now I am confronted with a software problem where I need both usage types within the same certificate.
See here: [Problem with solution](https://community.hortonworks.com/content/supportkb/151790/errorjavasecuritycertcertificateexception-javaxnet.html)

Unfortunately, it is not possible to generate such a certificate with OPNsense, which means that I have to generate the certificate outside of OPNsense.

It would be nice if it is possible to select multiple values in the Type of the certificate dropdown so that it is possible to generate certificates with server and client extended key usage for cluster servers and nodes that authenticate and serve with the same certificate.

Thanks!

**Comment by addy90** [comment]
Any idea or progress on this?

As far as I saw, the current code only permits to create either a server or a client certificate, but not both. So it does not look like it is only a UI problem.

I noticed that the Let's Encrypt certificates have both server and client extension, but there is no known export possibility for me that can be automated to fetch the certificates.

So I still have no possibility here, except maybe redirect letsencrypt challenges to the host that needs that special certificate... but I would prefer a certificate from the local CA.

**Comment by MichaelDeciso** [comment]
Hi Adrian,

I'm working on this feature. Could you check if the enclosed file (which should be a combined client and server certificate) is indeed what you need?
 
[bla.crt.zip](https://github.com/opnsense/core/files/2745276/bla.crt.zip)

**Comment by addy90** [comment]
Hi Michael,

yes this is indeed the right thing! I noticed that the order is also important, but you have it right with client first and then server. So this is the right thing!

Thank you!

Nevertheless, I was able to create such a certificate by myself via openssl and the exported CA, so I found a workaround, though it is a nasty one.
