### ISSUE TITLE
[feature request] live log improvements

### ISSUE THREAD

**Issue by thutex** [opnsense/core#2804]
To improve how efficient we can use the live log, i would like to suggest these options:\

1) add an icon for the traffic direction as seen from the interface
=> i.e. instead of having WAN or LAN like now, have => WAN / LAN and <= WAN / LAN to show if the traffic is coming into the interface or leaving it
(because now you have to: stop the live log, find the rule, click the info button, and look over the information to see the direction)

2) an option to resolve hostnames automatically (related: issue #2287), instead of having to click the info icon, then the resolve icon
=> this would be an option because not everyone needs it, and extra dns requests mean extra resources. 
maybe the resolving, if enabled, can be limited to occur only when on the live log page and not for the entire logging?

**Comment by thutex** [comment]
for suggestion 1 i have a quickfix in the file core/fw_log.volt : 

`                                    case 'interface':
                                        if (interface_descriptions[record[column_name]] != undefined) {

if (record['dir'] == 'in') {
log_td.html('<i class="fa fa-download fa-lg" aria-hidden="true"></i><span>' + interface_descriptions[record[column_name]] + '</span>');
}
else {
log_td.html('<i class="fa fa-upload fa-lg" aria-hidden="true"></i><span>' + interface_descriptions[record[column_name]] + '</span>');
}
`

**Comment by AdSchellevis** [comment]
I can add an extra field for inbound/outbound, which you can then also use in your filters (e.g. `lanout`)

**Comment by AdSchellevis** [comment]
@thutex https://github.com/opnsense/core/commit/e53953001489f8e7cce491787fdad60eafd87fad adds direction, I suggest we keep your other feature request in https://github.com/opnsense/core/issues/2287 and close this one

**Comment by thutex** [comment]
@AdSchellevis thank you, this is exactly what i was looking for.

i agree that we can close this one and continue the hostname resolution request in #2287
