### ISSUE TITLE
MVC: DialogForm in DialogForm

### ISSUE THREAD

**Issue by mimugmail** [opnsense/core#2808]
For BIND plugin offering a complete authoritative DNS I need to add zone mangement. So I would add a new tab with DialogForm to let the user add multiple domains, but within the popup of this dialog I need a second one for adding multiple resource records on demand. 

I only saw this functionality with legacy code like ntp servers or on openvpn client to add multiple servers. Is there also a solution for MVC?

**Comment by AdSchellevis** [comment]
Kind of a master detail form with grids?

**Comment by mimugmail** [comment]
Closing, it was just a design issue on my side :)
