### ISSUE TITLE
interfaces: DHCP client configuration options

### ISSUE THREAD

**Issue by fichtner** [opnsense/core#281]
DHCP client configuration - Are the two checkboxes intended to be mutually exclusive?  If so, then a radio button would be appropriate. 
* "Advanced" ticked alone causes "Protocol Timing", "Lease Requirements and Requests", and "Option Modifiers" sections to appear above the "Private networks" (or "6RD Rapid Deployment" or "Track IPv6 Interface" if either is enabled) section,
* ticking both "Advanced" and "Config File Override" causes the above "Advanced" sections and * "Hostname", "Alias IPv4 address", and "Reject Leases From" sections to vanish, and "Configuration File Override" to appear, and
* "Configuration File Override" ticked alone causes the "Configuration File Override" section to appear, and "Hostname", "Alias IPv4 address", and "Reject Leases From" sections to vanish.

Whether the appearance or vanishing of any section of configuration values here also causes them to be disabled or removed in an underlying config file is of some concern but I did not verify/check.

Submitted by: Curt Dox

**Comment by AdSchellevis** [comment]
Refactored some months ago, should be fixed now.
