### ISSUE TITLE
PAC: make default proxy configurable instead of direct

### ISSUE THREAD

**Issue by poggenpower** [opnsense/core#2812]
First thank you for integrating PAC management into Opnsense really usefull feature.
I have an improvement request:
At the moment it is hard coded, that per default not proxy will be returned. I think there are many environments, where using a proxy is default not a direct connection. 
It would be great if it could be possible to flag one of the proxies as default proxy and this one will be returned as default. 
This will will reduce the complexity of many configurations and avoid things like negations in the policy which make them harder to understand. 
Thanks
  Thomas

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository, 
please read https://github.com/opnsense/core/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue, 
just let us know, so we can reopen the issue and assign an owner to it.
