### ISSUE TITLE
menu: sorting in VPN

### ISSUE THREAD

**Issue by mimugmail** [opnsense/core#2814]
Hi,

Since the addition of ZeroTier and WireGuard the menu sorting is a bit mixed. 
Tinc has 100, WireGuard and ZeroTier are below. IPSec, OpenConnect and OpenVPN seems to be fine.

Shall I reorder WireGuard and ZeroTier to 150 and 200 or is there a better approach you like more?

**Comment by AdSchellevis** [comment]
@mimugmail reorder is fine, if we remove all ordering it should fallback to alphabetical (if I'm not mistaken), but then you can't register items in between. Best to fixate at the most logical spot.
