### ISSUE TITLE
LDAP Authentication Server - userPrincipalName strange behavior

### ISSUE THREAD

**Issue by Bluemchenpfluecker** [opnsense/core#2816]
Hello dear developers,

we discovered a strange behavior when creating a ldap authentication server with the user naming attribute "userPrincipalName". We weren't able to authenticate against MS AD, but when we changed the user naming attribute to "sAMAccountName" and switched back to "userPrincipalName" the authentication is now working.

OPNsense Version: 18.7.4

The exact URL of the GUI page involved:
/system_authservers.php
/diag_authentication.php

List of steps to replicate the bug:
1. Create LDAP Authentication Server with the user naming attribute "userPrincipalName"
2. Test with Authentication Tester -> Authentication will fail
3. Change the user naming attribute of the LDAP Auth Server to "sAMAccountName"
3. Test now with "sAMAccountName" -> Authentication will succeed
4. Change back to "userPrincipalName"
5. Now the Test with "userPrincipalName" will succeed, too.

**Comment by AdSchellevis** [comment]
Maybe a typo in the password or different users in the test?

For a connected user, te DN in https://github.com/opnsense/core/blob/eb95e8f53e56e25ce8f0898ee6936d8201bd9a29/src/opnsense/mvc/app/library/OPNsense/Auth/LDAP.php#L377 is used, but if it needs to search for the user, it needs the correct `ldapAttributeUser` in https://github.com/opnsense/core/blob/eb95e8f53e56e25ce8f0898ee6936d8201bd9a29/src/opnsense/mvc/app/library/OPNsense/Auth/LDAP.php#L383

**Comment by Bluemchenpfluecker** [comment]
Sorry for the inconveniance, tt was our fault. There was an "." in the user naming attribute.
Have a nice day :)

**Comment by fichtner** [comment]
@Bluemchenpfluecker no worries, thanks for the quick follow-up :)
