### ISSUE TITLE
Unbound memory leak when using TLS

### ISSUE THREAD

**Issue by iMiMx** [opnsense/core#2817]
https://github.com/openssl/openssl/issues/7128
https://github.com/openwrt/packages/pull/7112

Seen this a few times, restarting Unbound clears the RAM (from 95% used), prior to enabling swap it used to kill the box.

**Comment by iMiMx** [comment]
Seems I'm currently a few behind, am running 18.7.2 - will install 18.7.4 and see if it still reoccurs, I don't see anything in the .3 nor .4 notes, however.

**Comment by fichtner** [comment]
We're shipping the latest 1.8.1 tomorrow in 18.7.6.

https://nlnetlabs.nl/projects/unbound/download/

I'll close this due to lack of response in the hopes 1.8.1 has all the fixes. :)
