### ISSUE TITLE
LDAP extended query not fully working

### ISSUE THREAD

**Issue by ahaase-c4u** [opnsense/core#2818]
When configuring Active Directory as auth source, extended query can be used to restrict the number of user found. While doing so, extended query is applied to user list while importing users from Active Directory, but obviously not during login to web user interface. That leads to situations, where maybe some user gets removed from a group used in extended query. But because the query isn't applied to login form data, user has to be deactivated in opnsense additionally.

Please also apply the extended query to logins. Version of opnsense having the problem is 18.7.4. I didn't check this in any previous version.

**Comment by AdSchellevis** [comment]
It already is applied in authenticate (if the user isn't known)
https://github.com/opnsense/core/blob/7410822082f796ff4c828b8dee1fcc4f1a344a37/src/opnsense/mvc/app/library/OPNsense/Auth/LDAP.php#L383

bound using 
https://github.com/opnsense/core/blob/eb95e8f53e56e25ce8f0898ee6936d8201bd9a29/src/opnsense/mvc/app/library/OPNsense/Auth/LDAP.php#L204

coming from  https://github.com/opnsense/core/blob/eb95e8f53e56e25ce8f0898ee6936d8201bd9a29/src/opnsense/mvc/app/library/OPNsense/Auth/AuthenticationFactory.php#L135

Same in user import
https://github.com/opnsense/core/blob/bd8c938ba0692cefac91fbad1b3918fa63344486/src/www/system_usermanager_import_ldap.php#L94-L97

Not sure what you mean by groups here, we don't import anything else from ldap then the manual user import.

**Comment by ahaase-c4u** [comment]
Ok, let me explain, how to reproduce the issue:

1. configure AD server as auth server, containing extended query, i.e. "&(memberOf=CN=grp-infrastructure,CN=Users,DC=company,DC=com)"
2. import users from AD source, extended query is applied correctly
3. some time later: one user leaves the company, so in AD he is removed from group grp-infrastructure

Expected behaviour: the user is not able to log in to any device, that is checking the group membership.

Behaviour in opnsense: the user can login as before :-/

**Comment by ahaase-c4u** [comment]
Would be nice to get a link to the mentioned entry on your wish list. Maybe I can leave a +1 there ;-)

**Comment by AdSchellevis** [comment]
sorry it's not online :)

**Comment by fichtner** [comment]
Can we close this support issue?
