### ISSUE TITLE
HA config sync broken

### ISSUE THREAD

**Issue by tkald** [opnsense/core#2824]
I have issue with HA config sync with version 18.7.5.
On master node I get error notice after conif changes:

`10-18-18 23:41:23 [ An error occurred while attempting XMLRPC sync with username root and https://172.19.0.2:443/xmlrpc.php parse error. not well formed ]`

And on slave node error report:
`[19-Oct-2018 00:40:13 Europe/Tallinn] PHP Fatal error:  Uncaught OPNsense\Core\ConfigException: no valid config loaded in /usr/local/opnsense/mvc/app/library/OPNsense/Core/Config.php:240
Stack trace:
#0 /usr/local/opnsense/mvc/app/library/OPNsense/Core/Config.php(182): OPNsense\Core\Config->checkvalid()
#1 /usr/local/opnsense/mvc/app/library/OPNsense/Core/Config.php(221): OPNsense\Core\Config->fromArray(Array, Object(SimpleXMLElement), 'authserver')
#2 /usr/local/opnsense/mvc/app/library/OPNsense/Core/Config.php(221): OPNsense\Core\Config->fromArray(Array, Object(SimpleXMLElement), 'system')
#3 /usr/local/etc/inc/config.inc(156): OPNsense\Core\Config->fromArray(Array)
#4 /usr/local/etc/inc/xmlrpc/legacy.inc(195): write_config('Merged filter,a...')
#5 /usr/local/opnsense/contrib/IXR/IXR_Library.php(446): restore_config_section_xmlrpc(Array)
#6 /usr/local/opnsense/contrib/IXR/IXR_Library.php(384): IXR_Server->call('opnsense.restor...', Array)
#7 /usr/local/opnsense/contrib/IXR/IXR_Library.php(357): IXR_Server->serve('checkvalid()
#1 /usr/local/opnsense/mvc/app/library/OPNsense/Core/Config.php(221): OPNsense\Core\Config->fromArray(Array, Object(SimpleXMLElement), 'authserver')
#2 /usr/local/opnsense/mvc/app/library/OPNsense/Core/Config.php(221): OPNsense\Core\Config->fromArray(Array, Object(SimpleXMLElement), 'system')
#3 /usr/local/etc/inc/config.inc(156): OPNsense\Core\Config->fromArray(Array)
#4 /usr/local/etc/inc/xmlrpc/legacy.inc(195): write_config('Merged filter,a...')
#5 /usr/local/opnsense/contrib/IXR/IXR_Library.php(446): restore_config_section_xmlrpc(Array)
#6 /usr/local/opnsense/contrib/IXR/IXR_Library.php(384): IXR_Server->call('opnsense.restor...', Array)
#7 /usr/local/opnsense/contrib/IXR/IXR_Library.php(357): IXR_Server->serve('`

**Comment by mimugmail** [comment]
Update to the latest hotfix release which was released couple of hours after 18.7.5.

**Comment by tkald** [comment]
Yes, with the latest hotfix, config sync works again!
