### ISSUE TITLE
19.1 Geo IP blocking

### ISSUE THREAD

**Issue by marjohn56** [opnsense/core#2827]
Is this supposed to work yet or is it still WIP? Had to 11.2 to 18.7.5_1 to restore Geo Blocking.

**Comment by mimugmail** [comment]
IPS or Alias?

**Comment by marjohn56** [comment]
Alias.. Strange things happen. For example Germany was missing from Europe for a while - most worrying, I did check that it hadn't moved continent but it was no-where to be found. I exited the Geo Aliases and came back to it and it had magically re-appeared. If I select everything, then a 'timed-out' error occurs. If I reverse the logic and set only countries I wish to allow and then that error no longer occurs but in either case no geo-blocking happens. Difficult to test this as obviously I need my live system to work correctly. I'm running up my test unit with 19.1 and the same config as my live unit, then I'll see if there is anything obvious.

**Comment by fichtner** [comment]
I don't understand "11.2 to 18.7.5_1". 19.1 is 11.2 with 18.7.5_1. There should be no issue. Alias API is for 18.7.6 and I don't think the kernel on 11.2 has an issue either.

**Comment by fichtner** [comment]
PS: @marjohn56 I tested your config against soon to be 18.7.6 and it works fine now so that's not it.

**Comment by marjohn56** [comment]
No, as I said, really really weird, and I had NOT been drinking. Note I switched to Dev and and then did a code core and upgrade, it's working fine for me when using the installation media you provided. Only when I did the code core and upgrade did I hit issues.
