### ISSUE TITLE
OpenVPN Stopped working after last update (Juli 27)

### ISSUE THREAD

**Issue by groveld** [opnsense/core#283]
My OpenVPN Stopped working after the last system update of Juli 27th, when i try to start the service manually i'll get the following message:

Fatal error: Call to undefined function openvpn_get_settings() in /usr/local/www/status_services.php on line 35

I have disabled OpenVPN for now but would like to see it fixed :)

**Comment by fichtner** [comment]
We are aware, fix here: https://github.com/opnsense/core/commit/3a28b5a36342043e62c666ea9b068a5d6c474e8c

Will be part of 15.7.5 which is being released later today.
