### ISSUE TITLE
Static DHCPv4 mappings on VLANs are incorrectly listed against LAN interface

### ISSUE THREAD

**Issue by andrewgreenwood** [opnsense/core#2831]
Upgraded yesterday to OPNsense 18.1.13_1-amd64 (from a much older version)

(I've edited this issue since creating it as I realise now what the real problem is!)

Some background to my network setup:
I have a VLAN named MAIN_VLAN, with IP x.x.x.1 and a DHCPv4 range from x.x.3.200 to x.x.3.250
The LAN interface has no IP address. This interface also has DHCPv4 disabled, however it was previously assigned an DHCPv4 pool covering x.x.3.10 to x.x.3.245 in the same subnet as MAIN_VLAN now does. As DHCP is not enabled on the LAN interface and that interface has no IP address, it does not get shown for any services etc. (as expected)

So, there is a conflict in the DHCP pool ranges used by LAN and MAIN_VLAN, however the DHCP service is disabled on LAN therefore I'd expect there to be no issues.

DHCP leases are correctly being issued to hosts on MAIN_VLAN, however they are showing in the lease list against the LAN interface. If I attempt to create a static mapping from the lease list page for one of those leases, OPNsense attempts to create this against the LAN interface. In this instance I was trying to add an IP of x.x.3.127 which is outside of MAIN_VLAN's pool range, but inside LAN's (disabled) pool range so this displayed an error of "The IP address must not be within the DHCP range for this interface."

Obviously my setup needs correcting and this is something I will now do, but it seems as though when OPNsense is working out which interface a lease is for, it is not ignoring those interfaces for which DHCP is not enabled.

**Comment by fichtner** [comment]
Shipped in 18.7.x, no more feedback.
