### ISSUE TITLE
Feature request: GUI to query Unbound stats

### ISSUE THREAD

**Issue by soder10** [opnsense/core#2832]
Dear all,

I would like to find an easy way to query the standard stats of Unbound from the GUI, for example:

- get stats of how many requests received since service start / restart
- how many reqs were answered / failed to resolve
- average response time (for iterative queries?)
- current size of resource records cache (both in terms of item count and Kb)
- print out the entire cache content (e.g. for troubleshooting)

**Comment by fichtner** [comment]
The backend part as of 18.7.5:

    # configctl unbound stats

**Comment by MichaelDeciso** [comment]
@fichtner PR has been merged, so I guess this can be closed?

**Comment by fichtner** [comment]
@MichaelDeciso thanks for the PR ❤️
