### ISSUE TITLE
Allowing multiple IPSEC Mobile P1 configs

### ISSUE THREAD

**Issue by mimugmail** [opnsense/core#2833]
Reference: https://forum.opnsense.org/index.php?topic=9142.msg44734#msg44734

Today I tried this for a customer. Added a second Mobile P1 via link from forum and set a different authentication mechanism. Only caveat is that I can't user the same network in P2, but this is just a wrong preg validator since it doesn't matter what rightsubnet is when using mobile ipsec.

Last thing is that all users share the same pool, but in principle it's working. What I have setup and tested successfully was a setup mix of IPSEC v1 with PSK+XAuth and a second connection with IKEv2 and EAP-MSCHAPv2 and/or EAP-RADIUS. This is really cool since you can allow all kinds of devices like android with stock VPN since it doesn't support IKEv2 but also Windows7 or Mac (has to be tested yet by my colleague). 

@AdSchellevis Is there a technical reason why only one mobile ipsec is allowed?

**Comment by mimugmail** [comment]
Thanks @AdSchellevis  👍 Can we add a "help wanted" tag? I'll collect some test scenarios, documenting what works and whats not, also to have a reference if there come more FRs from other. Perhaps I can find a moment in post-19.1 where some of you has time to work on this. :)

**Comment by AdSchellevis** [comment]
Finding out what works and what doesn't is probably most of the needed work for options that don't need structural changes, I can probably do the work afterwards depending on the outcome of your testing.

**Comment by mimugmail** [comment]
Mutual PSK + XAuth with ldap as backend, combined with EAP-RADIUS does not work:

strongswan.conf:

```
starter {
    load_warning = no
}

charon {
    # number of worker threads in charon
    threads = 16
    ikesa_table_size = 32
    ikesa_table_segments = 4
    init_limit_half_open = 1000
    ignore_acquire_ts = yes
    syslog {
        daemon {
            ike_name = yes
        }
    }
        cisco_unity = yes

        plugins {
                attr {
                        subnet = 10.0.0.0/8,10.0.0.0/9,10.0.0.0/10
                        split-include = 10.0.0.0/8,10.0.0.0/9,10.0.0.0/10
                }
                xauth-generic {
                        script = /usr/local/etc/inc/plugins.inc.d/ipsec/auth-user.php
                        authcfg = unused
                }
        }
}
```

```
starter {
    load_warning = no
}

charon {
    # number of worker threads in charon
    threads = 16
    ikesa_table_size = 32
    ikesa_table_segments = 4
    init_limit_half_open = 1000
    ignore_acquire_ts = yes
    syslog {
        daemon {
            ike_name = yes
        }
    }
        cisco_unity = yes

        plugins {
                attr {
                        subnet = 10.0.0.0/8,10.0.0.0/9,10.0.0.0/10
                        split-include = 10.0.0.0/8,10.0.0.0/9,10.0.0.0/10
                }
                eap-radius {
                        accounting = yes
                        servers {
                                server1 {
                                        address = 127.0.0.1
                                        secret = "test"
                                        auth_port = 1812
                                        acct_port = 1813
                                }
                        }
                }
        }
}
```

Perhaps loading of multiple plugins here should be allowed .. I'll try to add this via CLI.

**Comment by fichtner** [comment]
Keep or close?

**Comment by mimugmail** [comment]
Close, not enough time, with this I have a good starting point when I find some more

**Comment by fichtner** [comment]
Ok ❤️

**Comment by max-weller** [comment]
I created a pull request (#3121) which should fix the problem noted in https://github.com/opnsense/core/issues/2833#issuecomment-432543007 by @mimugmail

**Comment by mimugmail** [comment]
Cool! :D Now we just ne a PR for routed ipsec 🥇
