### ISSUE TITLE
Python 2 is EOL soon (2020)

### ISSUE THREAD

**Issue by aphor** [opnsense/core#2834]
In 2020 upstream Python 2 updates (including security updates) will stop.

"The End Of Life date (EOL, sunset date) for Python 2.7 has been moved five years into the future, to 2020. This decision was made to clarify the status of Python 2.7 and relieve worries for those users who cannot yet migrate to Python 3. See also PEP 466."

https://www.python.org/dev/peps/pep-0373/
https://pythonclock.org/

This will require planning (timeline/goals), architecture (dual python versions or cutover migration), testing, and documentation.

**Comment by AdSchellevis** [comment]
We know. We're probably going to use a dual python version strategy as of 19.1, leaving the rest of the year to convert the different scripts. some are already compatible, some aren't yet.

**Comment by fichtner** [comment]
Please don't be surprised if you don't lead with a question or personal stake that makes your post not look like an automated notice.

**Comment by aphor** [comment]
Thanks for the guidance. Would you welcome PRs to help move the Python code migration along?

**Comment by AdSchellevis** [comment]
@aphor we certainly do, if compatible with both versions we might consider patches to be include in 19.1, otherwise we rather see them enter a bit later so they can be used with our dev version when both versions are shipped.

Thanks in advance!

**Comment by fichtner** [comment]
Python 3.6 packages will be in 18.7.7, except for ipaddr as it seems to be in the base installation under 3.3+.

https://github.com/opnsense/core/commit/66709dbbfa0
https://github.com/opnsense/tools/commit/c0a105a93eb
https://github.com/opnsense/tools/commit/62fa88cd5d1
https://github.com/opnsense/tools/commit/4f5a745c52f
https://github.com/opnsense/tools/commit/28d826cf0ed
https://github.com/opnsense/tools/commit/d322b6001bc
https://github.com/opnsense/tools/commit/a75e573ad2f8
https://github.com/opnsense/tools/commit/627d147d67c
https://github.com/opnsense/tools/commit/a836b4683e8

**Comment by AdSchellevis** [comment]
@fichtner nice! thanks!

**Comment by aphor** [comment]
I have to burn some vacation time this month. I spent some of my copious spare time in the last few weeks setting up a local test environment.

BTW: ipaddr in base python is a little problematic as it doesn't accept RFC compliant scoped local addresses. There is a bolt-on implementation which does though, in saltstack/salt.

**Comment by fichtner** [comment]
Keep ticket or split into workable chunks of actual tasks?
