### ISSUE TITLE
intrusion detection: remove GeoIP feature in 19.1

### ISSUE THREAD

**Issue by fichtner** [opnsense/core#2838]
via https://github.com/opnsense/plugins/issues/935

**Comment by jslay88** [comment]
Well, at least you guys are quick to respond. :) Thanks!

**Comment by AdSchellevis** [comment]
https://github.com/opnsense/core/pull/2890

**Comment by AdSchellevis** [comment]
https://github.com/opnsense/core/pull/2890 removes the functionality, but could cause migration issues if people are blocking access from a specific region. We should probably look into some migration code to disable the user rules which have geoip settings for safety.

**Comment by fichtner** [comment]
suricata in tools.git also has GEOIP set, which can be removed as well in 19.1.

**Comment by AdSchellevis** [comment]
good point, almost forgot about that one. I think we can already do that, shall I drop it now?

**Comment by fichtner** [comment]
in the 19.1 make.conf only -- but since suricata-devel goes away I'll have to touch those later anyway

**Comment by AdSchellevis** [comment]
ok, I'll leave it for you then :)

**Comment by fichtner** [comment]
btw, 4.1 im 18.7.8 ? :)

**Comment by AdSchellevis** [comment]
I think that's a good idea, let's do it :)

**Comment by fichtner** [comment]
yay, ok!

**Comment by AdSchellevis** [comment]
https://github.com/opnsense/core/pull/2965
