### ISSUE TITLE
Error when importing Aliases from pfsense config file

### ISSUE THREAD

**Issue by Flole998** [opnsense/core#2839]
I tried to import the aliases today from my pfsense installation. That did not fail with a "nice error message", but instead I was presented this:

> Fatal error: Uncaught OPNsense\Core\ConfigException: invalid config xml in /usr/local/opnsense/mvc/app/library/OPNsense/Core/Config.php:336 Stack trace: #0 /usr/local/opnsense/mvc/app/library/OPNsense/Core/Config.php(168): OPNsense\Core\Config->loadFromFile('/tmp/tmpxml') #1 /usr/local/etc/inc/config.inc(69): OPNsense\Core\Config->toArrayFromFile('/tmp/tmpxml', Array) #2 /usr/local/www/diag_backup.php(55): load_config_from_file('/tmp/tmpxml') #3 /usr/local/www/diag_backup.php(219): restore_config_section('aliases', '

**Comment by fichtner** [comment]
What version are you on? It's useful for helping.

I'm guessing it's 18.7.5. There was a hotfix 18.7.5_1 and 18.7.6 came out today as well. On 18.7.6 importing pfSense aliases will likely no longer work since we added our API.


Cheers,
Franco
