### ISSUE TITLE
flowd_aggregate.py consumes whole cpu core

### ISSUE THREAD

**Issue by tkald** [opnsense/core#2840]
Since update to verstion 18.7.6 flowd_aggregate.py consumes whole cpu core.
![image](https://user-images.githubusercontent.com/8062491/47524640-d46d4580-d8a3-11e8-8326-aa8f298e5e7d.png)

Wasn't like it with version 18.7.5. 

HW - Dell R330, Xeon E3-1240L v5 @ 2.10GHz (8 cores)

```
last pid:   509;  load averages:  0.66,  0.89,  0.97                                                                                 up 0+00:33:12  22:27:18
54 processes:  2 running, 52 sleeping
CPU: 12.2% user,  0.0% nice,  0.5% system,  0.7% interrupt, 86.6% idle
Mem: 193M Active, 6212M Inact, 2376K Laundry, 1181M Wired, 768M Buf, 150M Free
Swap: 16G Total, 16G Free

  PID USERNAME       THR PRI NICE   SIZE    RES STATE   C   TIME    WCPU COMMAND
49596 root             1  93    0 97180K 22148K CPU1    1   0:11  99.63% python2.7
68154 _flowd           1  20    0  8328K  1876K select  5   0:01   0.09% flowd
91870 root             1  20    0 20076K  2920K CPU5    5   0:00   0.05% top
63578 root             1  20    0  1061M  5356K select  2   0:01   0.05% openvpn
91723 nobody           1  20    0  1049M  1840K sbwait  2   0:01   0.05% samplicate
97983 root             1  20    0 21784K  2492K select  3   0:00   0.02% zabbix_agentd
43493 root             1  20    0  1049M  2148K select  6   0:00   0.01% apinger
97647 root             1   4    0 21784K  2488K select  1   0:00   0.01% zabbix_agentd
46632 root             1  20    0  1053M  2088K bpf     3   0:00   0.01% filterlog
29344 root             1  20    0  1051M  2332K select  3   0:00   0.01% syslogd
57072 root             1  20    0  1061M  5468K select  7   0:00   0.01% openvpn
38357 root             1  20    0  1061M  5336K select  5   0:01   0.01% openvpn
 6389 dhcpd            1  20    0 24732K  7944K select  4   0:00   0.00% dhcpd


```

Netflow configuration:
![image](https://user-images.githubusercontent.com/8062491/47525402-d6d09f00-d8a5-11e8-8ab3-2162a6f83448.png)

**Comment by tkald** [comment]
Looks like after resetting netflow data, cpu usage dropped to the same level as before ... 
Still 100% core usage by flowd_aggregate.py process for 5 seconds after every 15 seconds but I suppose it should work like that?

**Comment by kekek2** [comment]
I have same problem.

**Comment by mimugmail** [comment]
On my side update went fine (18.7.5->18.7.6), graphs still there, no CPU jumps .. 
Anything in the logs? Probably on console while starting?

**Comment by fichtner** [comment]
Judging from the release notes there were no relating changes whatsoever, probably in all of 18.7. Maybe this is normal on reboot now for your databases? It must be doing something, no? E.g. it's cleaning its database on restarts.

**Comment by AdSchellevis** [comment]
flowd is busy if there are a lot of flow packages handled, more traffic (or smaller bits) will result in more activity. `/var/log/flowd*` files are likely bigger then before.

**Comment by tkald** [comment]
I usually get around 400 flow entries per second.

**Comment by fichtner** [comment]
Timeout?

**Comment by Killerhaschen** [comment]
Disable Reporting->NetFlow->Capture local worked for me.

**Comment by becks0815** [comment]
Can confirm (opnsense 23.7.12) that disabling Capture local stops opnsense from consuming a lot of CPU power. In my case one core was 99.7% busy with flowd, and I have no idea why this was the case.

**Comment by putnam** [comment]
> Disable Reporting->NetFlow->Capture local worked for me.

This just disables insight entirely. Unless you're running a collector on some other machine I don't know why you'd want to do this. The name "capture local" is confusing because it sounds like it means capture insight data on the firewall itself, an issue that was raised at least as far back as 2018 when multiple users confused it on the forum: https://forum.opnsense.org/index.php?topic=9060.0

I've had a high traffic opnsense system running for a while and netflow/insight has had this issue the whole time with flowd.log not being properly rotated. I had a 135GB flowd.log when I checked tonight and flowd_aggregate.py was once again hitting 100% on a single core with no insight data for any interface. There is no useful logging info anywhere and trying to run flowd_aggregate.py in console mode just hangs indefinitely with no output to the console.
