### ISSUE TITLE
ipfw scheduler PRIO?

### ISSUE THREAD

**Issue by mimugmail** [opnsense/core#2842]
Today I saw in system.log:

`kernel: load_dn_sched dn_sched PRIO loaded`

Does anyone know what PRIO is? There is no documentation in man page and also in google you only find a report of a kernel panic. Since dummynet "only" supports queuing, this would be very interesting.

ipfw takes this command and looks like this:

```
root@OPNsense:~ # ipfw sched show
10002:   3.000 Mbit/s    0 ms burst 0
 sched 10002 type PRIO flags 0x0 0 buckets 0 active
10000:  25.000 Mbit/s    0 ms burst 0
 sched 10000 type WF2Q+ flags 0x0 0 buckets 0 active
   Children flowsets: 10002 10001 10000
10001:   2.000 Mbit/s    0 ms burst 0
q75537  50 sl. 0 flows (1 buckets) sched 10001 weight 0 lmax 0 pri 0 droptail
 sched 10001 type FQ_PIE flags 0x0 0 buckets 0 active
  FQ_PIE target 15ms tupdate 15ms alpha 0.125 beta 1.25 max_burst 150ms max_ecnth 0.1 quantum 1514 limit 10240 flows 1024 ECN CapDrop TS Derand

```

Normally, priority queuing means, always put this first, let others starve. I'd guess you create a rule (not queue) and add it to pipe PRIO to get this running. 

But I'm a bit concerned because there is really no documentation around .. 

Anyone?

**Comment by fichtner** [comment]
There seem to be defunct types, the comments are telling :D

sys/netpfil/ipfw/dn_sched_prio.c:#define DN_SCHED_PRIO	5 //XXX
sys/netpfil/ipfw/dn_sched_qfq.c:#define DN_SCHED_QFQ	4 // XXX Where?
sys/netpfil/ipfw/dn_sched_rr.c:#define DN_SCHED_RR	3 // XXX Where?

**Comment by fichtner** [comment]
oh no, qfq and rr seem to be documented

**Comment by mimugmail** [comment]
QFQ seems to be pretty good .. but I'm interested in PRIO .. just wanted to hear what you say before I send a foolish post on freebsd-net :)

**Comment by fichtner** [comment]
keywords are "pri" / "priority", do the same thing. only for flowsets. Used like "lmax" / "maxlen" or "weight"

**Comment by mimugmail** [comment]
These are value from FQ_PIE scheduler ;)

**Comment by fichtner** [comment]
I don't think so. It's a general queue modifier.

**Comment by mimugmail** [comment]
I'll try to gather more info via freebsd-net .. thx
