### ISSUE TITLE
usb boot broken after configuration

### ISSUE THREAD

**Issue by ciroiriarte** [opnsense/core#2843]
I'm trying to run 18.7 from a pendrive on a HP Thinclient t5745 booting from a pendrive (OPNsense-18.7-OpenSSL-nano-i386.img). First boot is flawless, I get to configure everything and after the first reboot I have two issues:

1- Super slow boot (\ - | - / - \  sequence slowly moving)
2- After several minutes, I just receive a "can't load kernel" message.

I remember being able to run previous versions of OPNsense (just had the slow boot thing and I cannot remember the workaround).

Can this be a regression?

**Comment by fichtner** [comment]
No, it looks like your hardware likes the install image's initial setup better than the actual install. The reasons can be plenty. Need to find out why. Nano does a growfs on first boot. Subsequent boots have been reported to break on SD cards with APU hardware. None of these reports have been substantial. From a technical standpoint 18.1 and 18.7 are not different.

**Comment by fichtner** [comment]
Documentation is sparse indeed even in FreeBSD. However, 17.x working seems to be a clue.

There was this commit going into 18.1: 8e85edd41 maybe you can remove the three lines from /usr/local/etc/rc.loader.d/20-misc and run this once prior to reboot:

    # /usr/local/etc/rc.loader

I'd offer the 19.1-BETA images with HardenedBSD 11.2 (we are on 11.1 now), but i386 is not ready just yet.

**Comment by ciroiriarte** [comment]
> It could also be System: Settings: Administration: Console driver, uncheck "vt". And 17.x was 11.0. Lots of changes...

First test, no joy. Boot is still super slow

**Comment by ciroiriarte** [comment]
> Documentation is sparse indeed even in FreeBSD. However, 17.x working seems to be a clue.
> 
> There was this commit going into 18.1: [8e85edd](https://github.com/opnsense/core/commit/8e85edd41643c7a36c845b0d53a38ed75f51f33a) maybe you can remove the three lines from /usr/local/etc/rc.loader.d/20-misc and run this once prior to reboot:
> 
> ```
> # /usr/local/etc/rc.loader
> ```
> I'd offer the 19.1-BETA images with HardenedBSD 11.2 (we are on 11.1 now), but i386 is not ready just yet.

Also tested, nothing changed. Wondering why an AHCI parameter would hinder USB boot though...

**Comment by fichtner** [comment]
Timeout. 19.1 is out now and require reassessment.
