### ISSUE TITLE
Flag "Multi-WAN gateway" really makes sense?

### ISSUE THREAD

**Issue by andrewhotlab** [opnsense/core#2846]
Hi to all, testing multi wan setup... when I used the "add" button to create a new gateway from the same web page of the new WAN interface settings, I noticed this flag (see attached screenshot), which seems no useful to me: in fact creating the new gateway with this flag does not seems to set anything different from creating without it.

![multiwangw](https://user-images.githubusercontent.com/26433166/47567688-8bfb6980-d92f-11e8-9c06-edd7452cf952.png)

**Comment by fichtner** [comment]
When you select this, after save you have set "ipv4 upstream gateway" to "WAN1_GWv4"

**Comment by andrewhotlab** [comment]
Sorry I didn't noticed it: I was looking only the resulting gateway configuration in the file `config.xml`.

Thanks for the clarification!
