### ISSUE TITLE
Unable to add Aliases after update to 18.7.6

### ISSUE THREAD

**Issue by aldopeirano** [opnsense/core#2847]
No longer have the option to Add an Alias after upgrading to 18.7.6 from 18.7.5.   The option is just not present on the screen.  I am able to edit the existing Aliases, but I can not add any new ones

![image](https://user-images.githubusercontent.com/43044143/47575369-f43a5300-d90f-11e8-81ff-631f77a9945c.png)

**Comment by mimugmail** [comment]
At the bottom right I can see a + sign ...

**Comment by aldopeirano** [comment]
OK.. so I am blind, I could have sworn it was at the top....   thank you for the second set of eyes.
