### ISSUE TITLE
[UI] bootstrap-select upgrade to v1.13.3

### ISSUE THREAD

**Issue by reza-ebrahimi** [opnsense/core#2848]
The last upgrade for bootstrap-select is for v1.9.3, the current stable version is v1.13.3 that some critical bugs has been resolved.

https://github.com/snapappointments/bootstrap-select/releases/tag/v1.13.3

**Comment by AdSchellevis** [comment]
This will likely have to wait for a major release, the style sheet changes don't seem to be compatible with the ones in our theme's now.

**Comment by reza-ebrahimi** [comment]
And when we can have a major release?

**Comment by AdSchellevis** [comment]
The next one is scheduled for Januari 2019, we'll try to add this.

**Comment by AdSchellevis** [comment]
https://github.com/opnsense/core/pull/2939
