### ISSUE TITLE
lighttpd request-size too long after 18.7.6 update

### ISSUE THREAD

**Issue by p33k** [opnsense/core#2850]
OPNSense running on a 64 bit Intel PC. Mainboard LAN as WAN and USB LAN as LAN.
After the update 18.7.6 the pcs behind Opnsense don't have internet connection and I can't reach the web frontend from behind opnsense and also not before it (pcs within the network that passes internet as WAN to opnsense.

on the machine directly I get the error "lighttpd request-size too long"

**Comment by p33k** [comment]
am I the only one with this problem? the setup worked without errors before the update. without changing anything the update killed it. 
Is there a way to fix it or do I need a complete reinstall?

**Comment by fichtner** [comment]
Hi,

The update doesn't cause this. It looks like something is mangling your requests to the firewall. Could be anything... new component in the network, software, bad switch or cable or broken NIC on the firewall.


Cheers,
Franco
