### ISSUE TITLE
Host Aliases Do Not Allow Domain Names

### ISSUE THREAD

**Issue by btwood** [opnsense/core#2857]
According to the docs, this is allowed:
https://wiki.opnsense.org/manual/aliases.html#hosts

However when trying it in the web GUI, form validation fails.
"The following input errors were detected:

The name must be less than 32 characters long and may only consist of the following characters: a-z, A-Z, 0-9, _"

OPNsense 18.7.5_1-amd64
FreeBSD 11.1-RELEASE-p14
LibreSSL 2.7.4

**Comment by fichtner** [comment]
Hmm, for host names, "_" shouldn't be allowed too, but "-" should. Handing over to @AdSchellevis

**Comment by AdSchellevis** [comment]
@btwood please upgrade to the latest version first, the comment relates to the alias name itself which may not contain minus (-) signs:

Same validation in 18.7.6:

![image](https://user-images.githubusercontent.com/9783985/47636165-b92a6080-db57-11e8-88d9-0d21b281a746.png)

**Comment by btwood** [comment]
Oh. That makes sense. I didn't realize "name" was reference to the alias at the time, though that seems painfully obvious now. Totally a human error on my end.

**Comment by AdSchellevis** [comment]
@btwood no problem, things happen :)
