### ISSUE TITLE
Star certificate generation error

### ISSUE THREAD

**Issue by pgaultier** [opnsense/core#2858]
If you want to create a "star" certificate which is valid in Chrome, you have to fill the alternative names.

For example, I would like to create a certificate `*.subdomain.domain.intra`. In that case, I have to fill :
 * CN : *.subdomain.domain.intra
 * Alternative Names
     * DNS : *.subdomain.domain.intra

If the Alternative name is omitted Chrome produce an error `NET::ERR_CERT_COMMON_NAME_INVALID`  with a `"Subject Alternative Names"` missing

After looking at the code, the problem seems to be here :

https://github.com/opnsense/core/blob/eb95e8f53e56e25ce8f0898ee6936d8201bd9a29/src/www/system_certmanager.php#L343

because the `is_hostname(...)` function does not handle the `*`. You can see it here

https://github.com/opnsense/core/blob/352428ba5c4b8a03151afe1089331bd452469542/src/etc/inc/util.inc#L565

It seems pfSense fixed it by adding a "wildcard" option. You can see it here

https://github.com/pfsense/pfsense/blob/8be7aff9d53954f4a952789c6bf79cc628ac5746/src/etc/inc/util.inc#L981

**Comment by AdSchellevis** [comment]
@pgaultier can you try https://github.com/opnsense/core/commit/d573662f5e3ecd0c533aecd5662c2150ac1d0b3e ?

**Comment by pgaultier** [comment]
@AdSchellevis Thank you !!, applied the patch and it works like a charm.

**Comment by AdSchellevis** [comment]
@pgaultier thanks for confirming!
