### ISSUE TITLE
Disabling an alias which a rule is using doesnt work

### ISSUE THREAD

**Issue by MAGICCC** [opnsense/core#2860]
Hello,

Since 18.7.6 allows you to disabling/enabling aliases via API and GUI I wanted to try this to 'disable'/'enable' a rule because directly toggling a rule doesn't not work via API yet.
But disabling an alias doesn't automatically render a rule useless, since the underlying alias is disabled, the rule still works and therefore my plan doesnt work

**Comment by fichtner** [comment]
The only way that you can do what you want is manipulate the alias contents itself.

**Comment by AdSchellevis** [comment]
Disable should leave you with an empty alias, but I think I missed a spot there.

**Comment by AdSchellevis** [comment]
@MAGICCC this https://github.com/opnsense/core/commit/1d9b7ef4801e25ce371317a6087b44468df2804d should do the trick.

**Comment by MAGICCC** [comment]
wew thanks @AdSchellevis 
When we disable the alias it will be cleared? Or did I missunderstand something now?
Anyway I'll will build OPNSense then to check it when I have time

**Comment by AdSchellevis** [comment]
disable then apply will leave you with an empty alias, which can be practical for some scenario's.

**Comment by MAGICCC** [comment]
And when we enable it will the alias content be restored or do we end up with an enabled empty alias?

**Comment by AdSchellevis** [comment]
after apply, it will be populated again.

**Comment by MAGICCC** [comment]
Am I right that using `toggleitem` via the API will perform an apply automatically?
`curl -XPOST -d "{}" -H "Content-Type: application/json" -k -u "$keys":"$secret" https://example.org/api/firewall/alias/toggleitem/f6b1b711-c8dc-45c8-a3b5-c95dcdbb4a01`

**Comment by AdSchellevis** [comment]
No

**Comment by MAGICCC** [comment]
How can we apply the changes by using the API then?

**Comment by fichtner** [comment]
@MAGICCC see https://forum.opnsense.org/index.php?topic=10099.msg46281#msg46281

Will ship the aforementioned fix in 18.7.7.
