### ISSUE TITLE
[FEATURE REQUEST} SSH algorithm toggle

### ISSUE THREAD

**Issue by bipton** [opnsense/core#2867]
Recently Trustwave scans have been failing on my SSH daemon for "weak SSH key exchange algorithms supported", it would be slick to have a toggle under the ssh options to limit the keys used, like legacy/modern. The report has three references they steered me to:

https://tools.ietf.org/html/rfc4253#page-13
https://wiki.mozilla.org/Security/Guidelines/OpenSSH#Configuration
https://www.freebsd.org/cgi/man.cgi?query=sshd_config&sektion=5

**Comment by fichtner** [comment]
If nobody will be working on this it's better to wait and reopen when somebody is.

**Comment by immanuelfodor** [comment]
Can somebody do this manually via editing some config files somewhere?
