### ISSUE TITLE
[UI-Model] How to set model variable programmatically from UI using javascript or PHP script?

### ISSUE THREAD

**Issue by reza-ebrahimi** [opnsense/core#2875]
I need to calculate some values and set model from UI with `javascript` or `PHP` script.

**Comment by AdSchellevis** [comment]
The docs at https://docs.opnsense.org contain examples, the plugins directory also contains quite some simple plugins which you can look at.

**Comment by fabianfrz** [comment]
with a patched core, a heavy weighted working version is here: https://github.com/opnsense/plugins/pull/930

**Comment by reza-ebrahimi** [comment]
Thanks, I've handled with `ajaxCall` and `ajaxGet` to controller action, but I need to provide `uuid` of current user from `modal` form, how can I do this?

**Comment by fabianfrz** [comment]
you probably cannot read it - it is in `opnsense_bootgrid_plugin.js` in a local variable.

**Comment by reza-ebrahimi** [comment]
Is there any hack to read it? I need `uuid` to manipulate `model` item from view, why `uuid` doesn't generated via controller? and why it doesn't have an appropriate field in the model?

**Comment by fabianfrz** [comment]
if you are using the standard bootgrid / modal dialog, the uuid is bound to the event on the save button, so there is no extra field needed. If you are talking about the backend, the uuid is an attribute of the ArrayField element. You should definitely explain, what you try to do. I use a hidden field which I do fill using a script and I talk to the API using Backbone.js to calculate values based on other fields.

**Comment by reza-ebrahimi** [comment]
I need to update model item from view (.volt), so for updating model, needs to know `uuid` for which item to be updating.
I have tested a hidden HTML element and bind it to model, but the problem is cannot update element value when it binds to model.

**Comment by reza-ebrahimi** [comment]
Any workaround?

**Comment by fabianfrz** [comment]
The devel version should supports hidden fields which do allow setting custom data via JS (plain and JSON)
