### ISSUE TITLE
netflow backup created damaged tar -> OPNsense does not start because of infinite loop

### ISSUE THREAD

**Issue by Alex9779** [opnsense/core#2876]
I am using netflow for a small overview of what's going on, but today I had an issue.
It seems I created it by myself because I was too impatient when I wanted to restart the firewall after some problems with my DSL line. I fired the reboot command multiple times from the WebIF and then again from the SSH shell. Seems this lead to that the backup file for netflow got damaged.
The problem then was that the firewall didn't boot up anymore:
```
***** FILE SYSTEM MARKED CLEAN *****
Setting hostuuid: b4998a3a-5868-11e8-b348-000db9463368.
Setting hostid: 0x1ef47c8b.
Configuring vt: blanktime.
Configuring crash dump device: /dev/gpt/swapfs
swapon: adding /dev/gpt/swapfs as swap device
.ELF ldconfig path: /lib /usr/lib /usr/lib/compat /usr/local/lib /usr/local/lib/ipsec /usr/local/lib/perl5/5.26/mach/CORE
32-bit compatibility ldconfig path:
done.
>>> Invoking early script 'update'
>>> Invoking early script 'configd'
Starting configd.
>>> Invoking early script 'php'
Configuring PHP: OK
>>> Invoking early script 'backup'
>>> Invoking backup script 'captiveportal'
>>> Invoking backup script 'dhcpleases'
>>> Invoking backup script 'duid'
>>> Invoking backup script 'netflow'
tar: Damaged tar archive
tar: Retrying...
tar: Damaged tar archive
tar: Retrying...
tar: Damaged tar archive
tar: Retrying...
tar: Damaged tar archive
tar: Retrying...
tar: Damaged tar archive
tar: Retrying...
````
The startup was caged in that infinite loop where tar tried to open that damaged archive.
I had to connect with serial to my box and Ctrl-C that, then did a clean shutdown, which takes about 15 minutes on my box where the main part is that backup script of netflow tar'ing and zip'ing the netflow data.

So I did some research and I found no option in tar to stop when and archive is damages and return with an error code.

I wanted to bring this up here because this is not very nice and I wanted to discuss several options to resolve my issues.

1. It is not good that tar goes in an infinite loop, maybe someone knows how to stop that, so that it just tries once, and then bad luck, restore failed, not data there,rather than preventing the whole box from booting into a managable state.
2. It would be nice if there was an option where I could select if I want that data to be backed up. Or is that inlcuded in the option to backup RDD data? I also have no idea what the benefit is backing that data when I do a shutdown. If I select to backup the data when doing a config backup then it is ok, but at shutdown I don't backup the config to somewhere else other than the storage of the firewall itself, so if that storage crashed the backup is lost too. That backup take a long long time on my machine for IMHO no benefit...

**Comment by mimugmail** [comment]
Use /usr/local/etc/rc.reboot instead .. it wont damage DB instead of plain reboot command

**Comment by mimugmail** [comment]
It think the reason is when using /var in RAM so you wont loose all data when rebooting.
Regarding tar loop probably @AdSchellevis has an idea.

**Comment by AdSchellevis** [comment]
To be honest, I'm also not convinced it should do the backup when not using a ram filesystem, here we're disabling the backup schedule:
https://github.com/opnsense/core/blob/cae5ec3f69dfdfcd4119c1c3f69c6a61c534e410/src/etc/inc/plugins.inc.d/core.inc#L195-L201

Which we then later kick of during shutdown anyway:

https://github.com/opnsense/core/blob/eb95e8f53e56e25ce8f0898ee6936d8201bd9a29/src/etc/rc.syshook#L73 

@fichtner What do you think? Maybe we can add a parameter in the cronjob then for the default start check if /var is ramfs mounted in these cases.

**Comment by fichtner** [comment]
UFS has never been truly stable. For that reason on reboot all backup-worthy facilities are automatically saved and restored. I'd say this helped more users *silently* retain their data even when it was corrupted on the file system since the archive is harder to be broken by FS corruptions.

The backup on reboot is also used for seamless config import during installations:

https://github.com/opnsense/core/blob/f16167442665a8b5625cf08e63bea75dd2dcd4bb/src/sbin/opnsense-importer#L281

This should be raised to https://github.com/libarchive/libarchive -- it is a sort of a DoS scenario.

**Comment by Alex9779** [comment]
@fichtner regarding the tar thing, I am going to raise this issue with the infinite loop on the mentioned repo, no matter what we do here, there should be a possibility to handle such cases with an option. I have never heard of a self-healing archive that gets healthy again just if you try often enough...

**Comment by fichtner** [comment]
we can add a backup option "never" for each backup type listed under system: settings: misc. we can't enable it by default as it will break expected behaviour but that would work for you from the looks of it?

**Comment by Alex9779** [comment]
Yeah, I see your point of doing a backup of vital system config if as you say UFS can have problems sometimes.
It must not be for every single config type but just for the postions that can get huge and are not so important if they get lost...

**Comment by fichtner** [comment]
Views of "importance" can differ. The next issue raised is going to be about why it's not backed up by default if we change it. :)

**Comment by Alex9779** [comment]
As you said, I wouldn't change that default behaviour of backing up everything. As I told earlier on a normal machine this is absolutely fine as you have no issue when packing 500mb of data, but the APU board has...
So if you think just to implement options to exlude every single type of setting, that's fine too :D...

**Comment by AdSchellevis** [comment]
@fichtner I agree, a "never" options should fix the issue, I expect in reality this only impacts netflow since the size can grow pretty rapidly.

**Comment by fichtner** [comment]
Defaults to "Power off" which used to be labelled "Disabled" while now "Disabled" is the new non-default mode which prevents *all* backups and deletes any remaining ones left on the system. Shell parsing XML is a bit iffy but it does the trick without rewriting these scripts.

**Comment by fichtner** [comment]
PS: this will land in 18.7.8 :)

**Comment by Alex9779** [comment]
Just wanted to add that the update to 18.7.9, where that change kicked in first, went smooth and fast because of the disabled backups...
Thanks for this!

**Comment by fichtner** [comment]
yay, glad to hear. thanks for the follow-up!
