### ISSUE TITLE
routing: standard menu item

### ISSUE THREAD

**Issue by opnsenseuser** [opnsense/core#2878]
@fichtner 
@AdSchellevis 

Only as food for thought! and no negative review!
Is it really useful to put almost every plugin in the "service" menu? if I install more than 20 plugins on my test environment, sometimes, it depends on the plugin, even the new "dropup" function of the sidebar is no long enough to display the full menu.
It would still have so much space in the main menu and could for the sake of clarity, some plugins in another or new category record. 
Opnsense gets more and more new plugins, but stuffing almost everything in the category "services" seems to me to be over-thinking.
19.1 will be another milestone and should, in my opinion, take another step in this regard.

thx,
best regards,
rené

**Comment by mimugmail** [comment]
Perhaps we could move:

Telegraf
Colldectd
Vnstat
Zabbix Agent
Zabbix Proxy
LLDPd
ntopng

to `Reporting`?

**Comment by fichtner** [comment]
There's little we can do to avoid long menus long term, 4th level is not great for overview. I like @mimugmail's suggestion about the reporting, and we should eventually go for a standard routing menu.

**Comment by opnsenseuser** [comment]
I fully agree with you and @mimugmail. Other plugins should really be assigned more specific. and the routing is extra (can not be wrong with a firewall anyway) -> This provides more overview!

@fichtner as soon as the routing is available as a separate main menu item, I would adapt all the themes( @media/css) and the opnsense_theme.js for the (.on (resize)).

**Comment by fichtner** [comment]
Also see https://github.com/opnsense/core/pull/1647

**Comment by fichtner** [comment]
<img width="543" alt="screenshot 2019-01-20 at 11 57 07 am" src="https://user-images.githubusercontent.com/1915288/51438275-9d43e000-1caa-11e9-9081-e95c6cb8312b.png">

@AdSchellevis 19.1 or 19.7 ... this is something that has been put off for too long. In any case with your OK I would like to add this to development branch now.

**Comment by AdSchellevis** [comment]
@fichtner development branch is fine, I’ll get back to you about production release

**Comment by AdSchellevis** [comment]
@fichtner I've pulled your change into master, let's do this for 19.1.

**Comment by fichtner** [comment]
I already reverted it... discussing other ways with @mimugmail currently... none of the ways forward are great so it's best to stick with what we always had

**Comment by AdSchellevis** [comment]
ok, I'll revert the cherry-pick and doc then, let's keep this issue closed if it doesn't reflect the actual state anymore then

**Comment by fichtner** [comment]
Yes, thanks and sorry for the trouble.

**Comment by AdSchellevis** [comment]
no problem, going to move the other discussions (pppoe, hyperv) to 19.7 as well, it's not very likely they will be sorted out in a day.

**Comment by fichtner** [comment]
hyperv might be fixed... reports are inconclusive or incomplete at this point

**Comment by AdSchellevis** [comment]
we'll see, can always close when it appears to be solved

**Comment by fichtner** [comment]
ok 👍
