### ISSUE TITLE
NAT not working on 18.7.6

### ISSUE THREAD

**Issue by antipiot** [opnsense/core#2879]
Hello! 
Facing some issues for creating and using NAT rules:

If i create a NAT rule to convert WAN:8093 to LAN:9987
My firewall will log blocked traffic to LAN:8093 wich should be authorized to LAN:9987.
All my other rules are working fine.

If i create a new NAT rule, this is reproductible.

![45412794_10156931379453395_4790271553164017664_o](https://user-images.githubusercontent.com/26579988/47989213-a4fcdb00-e0e4-11e8-9ee5-fef8e218cdbc.jpg)
![45347928_10156931379538395_8860105571269869568_o](https://user-images.githubusercontent.com/26579988/47989214-a5957180-e0e4-11e8-8783-5f34efa306cf.jpg)
![45522218_10156931379443395_1546963691495227392_o](https://user-images.githubusercontent.com/26579988/47989215-a5957180-e0e4-11e8-99b9-2fe35c8b4f10.jpg)
![45452593_10156931379508395_6466311501668941824_n](https://user-images.githubusercontent.com/26579988/47989216-a5957180-e0e4-11e8-9dd6-c5be464cce37.jpg)

**Comment by AdSchellevis** [comment]
can you share the following:

- The log messages blocking the traffic
- The generated rule in /tmp/rules.debug (grep for the description should probably work)
- Other rules affecting the same interface (Either floating or directly on the interface)

**Comment by antipiot** [comment]
Hello!
Plain view:

Nov 5 12:37:56 | filterlog: 9,,,0,igb0,match,block,in,4,0x0,,54,7751,0,DF,17,udp,211,194.230.158.56,10.0.0.5,44911,8093,191
-- | --

 Rules debug:

on igb0 inet proto udp from {any} to {any} port $Teamspeak_WAN -> $NAS # Teamspeak forwarding
nat on igb0 inet proto udp from (igb0:network) to $NAS -> igb0 port 1024:65535 # Teamspeak forwarding

Some of the working NAT are:
nat on igb0 inet proto tcp from (igb0:network) to $ipcam port {80} -> igb0 port 1024:65535
nat on igb0 inet proto tcp from (igb0:network) to $desktop port {3389} -> igb0 port 1024:65535

Hope it helps :-)

**Comment by AdSchellevis** [comment]
can you use the live view? it shows a bit more info

**Comment by antipiot** [comment]
yes:
![8093](https://user-images.githubusercontent.com/26579988/47996679-9e2c9300-e0f9-11e8-9a15-59c6d3c5fc9f.JPG)

**Comment by AdSchellevis** [comment]
could it be that the alias changed at some point in time? it looks like the rule is only created initially.

**Comment by antipiot** [comment]
I did some testing when i noticed this rule was not working and have changed / deleted / recreated aliases.

**Comment by AdSchellevis** [comment]
I would suspect something similar to this in your rules.debug (as has mine):

`
pass in quick on em1 inet proto tcp from {any} to  $NAS port $Teamspeak_WAN label "USER_RULE: NAT my_rule" # 34dae5d9adcb498c997c0c7666394999
`

Which in my case is the correct rule, remember the target filter should match the post-nat target.

I have some cleanups for this code, which I will commit later, but in my test cases there always seems to be a pass rule

**Comment by antipiot** [comment]
Anything i can do? as for now i cant even create new rules?

**Comment by AdSchellevis** [comment]
Maybe you have another config related issue, I can't really help you with that.

**Comment by RasmusKvanderLoo** [comment]
I have my NAT rule working using ip and port numbers only (no aliases)??!!

**Comment by AdSchellevis** [comment]
@RasmusKvanderLoo and your point is?

**Comment by antipiot** [comment]
> 
> 
> I have my NAT rule working using ip and port numbers only (no aliases)??!!

I tried this aswell:
Same result: for a nat rule WAN:8888 -> LAN:7777 ill see traffic hitting firewall with LAN:8888
If i create a rule with WAN:8888 -> LAN:8888 it's indeed working as there's no PAT

**Comment by antipiot** [comment]
If anybody there is on 18.7.6:

Could you try to create a NAT to so i'll know this is only related to my system?

**Comment by AdSchellevis** [comment]
@antipiot found it, the target port seems to be missing in the generated rule, I really overlooked something here.

**Comment by antipiot** [comment]
> 
> 
> @antipiot found it, the target port seems to be missing in the generated rule, I really overlooked something here.

Great! thanks for your help!

**Comment by AdSchellevis** [comment]
@antipiot can you try https://github.com/opnsense/core/commit/eb42fac60adf932f857dd69abad05a8914d3214e ?


```
opnsense-patch eb42fac
```

filter reload needed after patch (/usr/local/etc/rc.filter_configure)

**Comment by antipiot** [comment]
Patch fix the NAT problem.
Thanks you very much.
Tried to create a new rule and it's working aswell indeed

**Comment by fichtner** [comment]
I'll pull this into 18.7.7 for tomorrow then. Thanks for the quick fix and feedback! ❤️

**Comment by antipiot** [comment]
> 
> 
> I'll pull this into 18.7.7 for tomorrow then. Thanks for the quick fix and feedback! ❤️

Thanks to you! :-)
