### ISSUE TITLE
IPSEC site-to-site certificate input is mandotory, which breaks the tunnel if you don't need it.

### ISSUE THREAD

**Issue by r-jansen** [opnsense/core#2881]
Hi,

When I create a new IPSEC site-to-site tunnel (mutual PSK), phase1, there are 2 dropdown boxes:
My Certificate
My Certificate Authority.
These fields are mandotory and cannot be left empty.

If you check the status overview, the certificate is being used as the Local ID, which breaks the IPSEC tunnels.

Would it be possible to make these fields optional?

As a workaround (as suggested by user jmirakul), I have downloaded the config.xml file, removed the <certref> and <certrefca> line. Uploaded this section, and after re-applying IPSEC tunnels started working fine.

The status overview now no longer shows the certificate in Local ID, but in my case the IP-address.

Kind regards,
Ray

**Comment by AdSchellevis** [comment]
Hi Ray,

Can you try another browser? on my end a Mutual PSK looks like this:

![image](https://user-images.githubusercontent.com/9783985/48003981-3f264880-e110-11e8-8af4-411419eec893.png)


Best regards,

Ad

**Comment by r-jansen** [comment]
Hi Ad,

You're right. With a different browser, I don't get the fields at all! I've also checked the configuration xml file, the tags are not in there also.

If I used this browser, it would have saved me a lot of trouble!

Thanks for checking!

Ray

**Comment by fichtner** [comment]
Hi Ray,

We discussed this internally a bit... the static PHP pages (*.php in the URL) have this drawback in edge cases when the browser refuses to execute JS. The long term fix is proper MVC migration. These pages should be immune to these problems as the model will validate the input correctly (and you can't hit save if the browser refuses ;) ). Closing this issue therefore.

You you mind stating the browser that caused this issue for future reference?


Thanks,
Franco

**Comment by jmirakul** [comment]
Thanks everybody.
With FF everything is OK, but failed with macOS & Safari 

Jon

**Comment by r-jansen** [comment]
Hi Franco,

I've used Internet Explorer before, Firefox now.

Kind regards,
Ray
