### ISSUE TITLE
Strongswan failled to start

### ISSUE THREAD

**Issue by sachaz** [opnsense/core#2882]
Dear all

on a fresh opnsense install on 18.7.4:

root@z:~ # uname -a
FreeBSD c3rb3r3.brest.rosedor.fr 11.1-RELEASE-p14 FreeBSD 11.1-RELEASE-p14  93e30e927e5(stable/18.7)  amd64
root@z:~ # pkg info opnsense
opnsense-18.7.4
Name           : opnsense
Version        : 18.7.4

I cannot start Strongswan:

plugin 'openssl' failed to load: /usr/local/lib/ipsec/plugins/libstrongswan-openssl.so: Undefined symbol "RSA_set0_factors"

I cannot upgrade for the moment due to  #2835

is it related to https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=212149 ?

**Comment by fichtner** [comment]
It's pretty weird.

You can do:

    # opnsense-revert -r 18.7.2 strongswan

And it will probably start working again.

18.7.7 ships with strongswan 5.7.1 and it's fixed there, too:

    # pkg add -f https://pkg.opnsense.org/FreeBSD:11:amd64/snapshots/latest/All/strongswan-5.7.1.txz

And if all of this fails revert back to the current version:

    # opnsense-revert -r 18.7.4

There's also the possibility of switching to the LibreSSL repo of 18.7.4 if needed, but I'm confident solution 1 or 2 works for you.

**Comment by sachaz** [comment]
> It's pretty weird.
> 
> You can do:
> 
> ```
> # opnsense-revert -r 18.7.2 strongswan
> ```
> 
> And it will probably start working again.

I don't know how you can do so fast in your replies <3
Thanks as you said it works \o/

**Comment by fichtner** [comment]
Ok, great. Should be back to normal on Thursday with 18.7.7. The issue seemed to be my LibreSSL 2.7 compat patching which extended to OpenSSL and caused runtime issues for some ... https://github.com/opnsense/ports/commit/6b1e56ec07
