### ISSUE TITLE
Support manual Source Address at "Interfaces: Diagnostics: Ping"

### ISSUE THREAD

**Issue by Kofl** [opnsense/core#2886]
Hi,

it would be really great, if "Interfaces: Diagnostics: Ping" would allow to set the Source Address IP manually and not force to select a local IP address from a OPNsense interface.

Very useful for testing via forged source ips for e.g. vpn connections.

**Comment by fichtner** [comment]
I just reworked these pages for 18.7.7. I'm not sure there is any benefit compared to the console use of ping/ping6. A lot of time can be spent building the greatest ping GUI in the world that 2 people use once every other year. :/

**Comment by fichtner** [comment]
Sorry, I meant 18.7.6.

**Comment by Kofl** [comment]
I was not aware of the functionality at all. Cisco ASA did a nice GUI work for that functionality.
If you like, I try to organize a screenshot. If not, I am also fine :-)
