### ISSUE TITLE
Feature: Allow specifying port for DHCP Dynamic DNS update

### ISSUE THREAD

**Issue by kevemueller** [opnsense/core#2889]
Services/DHCPv4 allows configuring Dynamic DNS.
The DNS request is sent to port 53 of the provided DNS server (standard port). There are valid circumstances when one would have DDNS server bound to a differen port.
The form should allow specifying the port number as well.

**Comment by fichtner** [comment]
I'm happy to add this, but I'm unable to find how ISC DHCP's zone "primary", "primary6", "secondary" or "secondary6" can be coerced into using a specific port?
