### ISSUE TITLE
Firewall log shows incorrect rule?

### ISSUE THREAD

**Issue by sjorge** [opnsense/core#2891]
```
sjorge@hydrogen:/tmp % grep 'Drop NetBIOS' rules.debug
block in quick on vtnet1 inet proto {tcp udp} from {(vtnet1:network)} to {any} port {137:138} label "USER_RULE: Drop NetBIOS (without log)" # 09d650892b301ec9892dbe88389f993f
block in quick on vtnet1 inet6 proto {tcp udp} from {(vtnet1:network)} to {any} port {137:138} label "USER_RULE: Drop NetBIOS (without log)" # 09d650892b301ec9892dbe88389f993f
block in quick on vtnet2 inet proto {tcp udp} from {(vtnet2:network)} to {10.23.20.255} port {137:138} label "USER_RULE: Drop NetBIOS (without log)" # 021a1f811792d1a933793263a2d851c4
```

![screenshot](https://i.imgur.com/SHobGYQ.png)

I'm confused why this is dropped by the rule that is mentioned, looking at the rules the packet should not match?

**Comment by fichtner** [comment]
Association of rules is not retained between reloads that change rule numbering.

**Comment by sjorge** [comment]
I don't think I reloaded the firewall rules, but I did end up reverting to 18.7.7 as the Development release ended up wiping all my rules if I tried to edit one. (It was late at night and I did not fail like troubleshooting)

Looks OK on 18.7.
