### ISSUE TITLE
insight UI - subtle "no data available" UI need

### ISSUE THREAD

**Issue by dotike** [opnsense/core#2895]
I'm a HUGE fan of the OPNSense Insight tooling, extremely useful to me.

Have seen a great deal of work go into fixing the "No Data Available" issue, e.g.:
https://forum.opnsense.org/index.php?topic=6879.msg30037#msg30037
This is related to, but not the same as, those issues (which are now resolved).

Found a subtle and low-priority issue, more of a UI/user-expectation problem with Insight graphs:

**On bursty/quiet networks, the "No Data Available" screens show up when there has been no traffic on the interfaces specified for some hours.**

Not broken, just misleading, the UI here does not naturally lead a user to understand they can see older data, with the following workarounds:

- By selecting an older/larger date range (where there is network traffic recorded), the insight graphs show back up.
- By putting traffic across the monitored network interfaces, after some time, (hours?), the graphs show back up.

On quiet/bursty networks, the "No Data Available" message leads users to believe there is something broken with the data, (particularly after searching the net for that error).  On regularly busy networks, the insight data always shows the rich data in the UI.

--
Open suggestions for workarounds:

- EASY: Perhaps Change the words "No Data Available" to "No Data Available In This Time Range" (implying that the user should fiddle with a larger date range to maybe see some data).

- HARD: Change the graph to show empty graphs when there is empty data, and only show the message "No Data Available" when there is something wrong with the data, (corrupted or disabled, etc...).  Looks like this could become quite a rabbit hole into re-workng subtle interactions of the UI and the data.

**Comment by AdSchellevis** [comment]
Hi @dotike, The "No Data Available" can still happen, it has been a long time ago since I build this component, but if I remember correctly it was kind of a struggle to display empty graphs with nvd3 here. Changing the title may be a good solution to make it a bit more explicit that the message is related to the timeframe.

Let's see what we can do for 19.1.

**Comment by AdSchellevis** [comment]
@dotike in 19.1 missing data should be presented as zero's due to https://github.com/opnsense/core/commit/fad4b3c426a925107d5e50e7091c1a17be418adf, we might consider fixing the pie chart at some point in time too, but that's probably not really necessary.
