### ISSUE TITLE
Feature request: ocserv plugin

### ISSUE THREAD

**Issue by elfrom** [opnsense/core#2896]
SSL makes it possible to connect to the endpoint from almost any network attached to the internet.
OpenVPN is able to run over SSL, I know. But the client is bulky and ugly, in my opinion.
Ocserv is available in ports, I have it installed and working, but it would be really nice if the configuration was backed up along with the rest of OPNsense configuration when doing backup.

I for one would really like an alternative to OpenVPN and Strongswan for my "road warrior" users. At the moment we use the old Cisco IPSec vpn client connecting to an old Cisco ASA, but its at pain to maintain on Windows 10.

**Comment by mimugmail** [comment]
I already requested a pkg here: https://github.com/opnsense/tools/issues/94

When this is in I'll start with a plugin ...

**Comment by elfrom** [comment]
Oh great, thanks.
Sorry for kicking in, an already open door :-)

**Comment by fichtner** [comment]
Let's keep this open then. Package soon...
