### ISSUE TITLE
Can not change name of existing firewall aliases when the name contains an _

### ISSUE THREAD

**Issue by JasMan78** [opnsense/core#2897]
Version: OPNsense 18.7.7-amd64

When I try to change the name of an existing firewall alias which has an _ in its name (e.g. My_PC), and when this alias is also an member of at least one other alias, nothing happens when I press "Save changes".
If I remove the _ from the name or the membership in the other aliases I can save the change.

**Comment by AdSchellevis** [comment]
@JasMan78 thanks for the report, https://github.com/opnsense/core/commit/bf2473db79d26afd256abfca7efe2a37e4ff6075 should fix the issue.
