### ISSUE TITLE
Cookie security

### ISSUE THREAD

**Issue by jpawlowski** [opnsense/core#2900]
The securityheaders.com scanner showed up an issue on the web UI with duplicated cookies while one header line indicates the cookie shall _not_ be secure and _not_ only http:

`````
Set-Cookie PHPSESSID=c6c503116e427e287e2438f00d877ebc; path=/
Set-Cookie PHPSESSID=c6c503116e427e287e2438f00d877ebc; path=/; secure; HttpOnly
`````

I believe the duplicated cookie shall be avoided in order to ensure correct browser behavior.

**Comment by AdSchellevis** [comment]
@jpawlowski two questions, which page scanned and which version tested?

**Comment by jpawlowski** [comment]
I scanned the OPNsense web ui login page.
I am using the current version 18.7.7.

**Comment by fabianfrz** [comment]
@AdSchellevis probably the ini flag `session.use_cookies` must be set to 0 to prevent it from being sent. See this post:
https://stackoverflow.com/questions/8643956/prevent-php-session-start-to-send-a-cookie

The only thing is that I cannot tell you if this breaks session handling entirely. It is very likely safe to be set inside a script but not globally.

**Comment by AdSchellevis** [comment]
@fabianfrz no, you can't do that, without session cookies you have to parse the session id in your requests (which you better avoid).

Odd thing is, I do seem to get the headers twice too, but mine always seem to be correct, normally this should adjust the session headers:

https://github.com/opnsense/core/blob/866ff2ba9252e4c3e830c6ff66edf0d2128b4f5e/src/etc/inc/authgui.inc#L68-L75

**Comment by fabianfrz** [comment]
@AdSchellevis probably due to https://github.com/opnsense/core/blob/866ff2ba9252e4c3e830c6ff66edf0d2128b4f5e/src/etc/inc/authgui.inc#L174
