### ISSUE TITLE
unbound: Enable TLS server support

### ISSUE THREAD

**Issue by jpawlowski** [opnsense/core#2910]
It would be nice to be able to enable TLS support for the Unbound server itself so that clients can make use of it.

**Comment by jpawlowski** [comment]
I may also refer to the "small p" appliance and their updated implementation.

**Comment by mimugmail** [comment]
I'm building a dnscrypt-proxy plugin with Support for DOH or dnscrypt. :) Core integration might take some more time

**Comment by jpawlowski** [comment]
well okay, why yet another plugin for stuff that's already possible to do out of the box? I know something to have for BIND (and not to wait for years for their own implementation) might be nice, but enforcing somebody to install just another plugin if you are only using Unbound seems overkill to me.
Maybe the right answer is not to have either of those but each of those possible options.

**Comment by fichtner** [comment]
Unbound-plus merged into core.
