### ISSUE TITLE
config: delete vip "hides" other entries

### ISSUE THREAD

**Issue by fichtner** [opnsense/core#2911]
Not entirely sure if this can be reproduced so for now just record what happened: it fits the "entries disappeared" reports that happen sporadically... I was using "die;" for debuggin in a POST request. Removed "die;", hit reload and resubmit in the browser and that happened:

```
--- /conf/backup/config-1542039272.2488.xml	2018-11-12 17:14:32.249928000 +0100
+++ /conf/backup/config-1542039332.9464.xml	2018-11-12 17:15:32.947471000 +0100
@@ -1165,8 +1165,8 @@
     <filterlogentriesacts>Pass Block Reject</filterlogentriesacts>
   </widgets>
   <revision>
-    <time>1542039239.9586</time>
-    <description>/firewall_virtual_ip_edit.php made changes</description>
+    <time>1542039272.25</time>
+    <description>/firewall_virtual_ip.php made changes</description>
     <username>franco@10.0.0.11</username>
   </revision>
   <openvpn>
@@ -3128,27 +3128,21 @@
   </wol>
   <virtualip>
     <vip>
-      <type>single</type>
-      <subnet_bits>8</subnet_bits>
-      <mode>ipalias</mode>
-      <interface>lo0</interface>
-      <descr>testing</descr>
-      <subnet>127.0.0.2</subnet>
-    </vip>
-    <vip>
-      <type>single</type>
-      <subnet_bits>24</subnet_bits>
-      <mode>ipalias</mode>
-      <interface>wan</interface>
-      <descr>Mock</descr>
-      <subnet>192.168.2.42</subnet>
-    </vip>
-    <vip>
-      <type>single</type>
-      <subnet_bits>64</subnet_bits>
-      <mode>ipalias</mode>
-      <interface>lan</interface>
-      <subnet>::123</subnet>
+      <vip>
+        <type>single</type>
+        <subnet_bits>8</subnet_bits>
+        <mode>ipalias</mode>
+        <interface>lo0</interface>
+        <descr>testing</descr>
+        <subnet>127.0.0.2</subnet>
+      </vip>
+      <vip>
+        <type>single</type>
+        <subnet_bits>64</subnet_bits>
+        <mode>ipalias</mode>
+        <interface>lan</interface>
+        <subnet>::123</subnet>
+      </vip>
     </vip>
   </virtualip>
   <staticroutes/>
```

Maybe also reported via: https://forum.opnsense.org/index.php?topic=10276.0
Offending issue could be: bd148f1dd2b52

**Comment by fichtner** [comment]
@AdSchellevis maybe you could look at this, I'm suspecting bd148f1 again, I have it queued up for 18.7.8 but the forum thread makes me worry...

**Comment by mstrdraco** [comment]
I'm having similar issues when I delete rules it's wiping out my entire Rule list for all firewall rules.

**Comment by AdSchellevis** [comment]
@mstrdraco which version?

**Comment by fichtner** [comment]
@mstrdraco @AdSchellevis thanks ❤️

**Comment by AdSchellevis** [comment]
@fichtner found the culprit, `unset()` doesn't reindex, which kills https://github.com/opnsense/core/blob/master/src/opnsense/mvc/app/library/OPNsense/Core/Config.php#L80

It's just very stupid that you can't distinct associative and sequential arrays easily.

**Comment by AdSchellevis** [comment]
it's in the same corner, yes

**Comment by AdSchellevis** [comment]
https://github.com/opnsense/core/commit/0df243422bfc449a43f1e94360985458f3a72771 should fix the problem.

**Comment by fichtner** [comment]
@mstrdraco you can try the patch from the command line:

    # opnsense-patch 0df2434

**Comment by mstrdraco** [comment]
Worked great! Thank you

**Comment by fichtner** [comment]
perfect, thanks. will be in the next devel update 👍
