### ISSUE TITLE
CARP events notifications can be in separate file

### ISSUE THREAD

**Issue by evbevz** [opnsense/core#2912]
https://github.com/opnsense/core/blob/bc773aa2a8a5c919431269e196e16b7df2596b64/src/etc/rc.syshook.d/carp/20-openvpn#L55

This kind of notifications is not related to openvpn. Filename is misleading. Can in be better to move CARP notifications to separate file?

**Comment by fichtner** [comment]
you're right. let me think about it.

**Comment by AdSchellevis** [comment]
We might consider dropping these completely, since the notifications itself aren’t very useful and should probably be superseded by monit now. Drop for 19.1?

**Comment by fichtner** [comment]
If we drop them we have to re-add them correctly or we use them to implement monit underneath during transition. Only issue with dropping them now is we may forget to put them back.

**Comment by AdSchellevis** [comment]
Let me check later this week, I kind of expect these events can easily be catched by monit, but haven’t looked at it yet

**Comment by clystron** [comment]
Just a comment: During my latest CARP-tests I had 2 issues with that "notify_via_smtp"-line, one was that I got tons of emails (multiple CARP-IPs on my test-setup) and the other was that the script made CARP-switchovers extremely slow sometimes when the SMTP-server was not reachable. So from my point of view getting rid of that inline mail-sending would be quite a plus.

**Comment by AdSchellevis** [comment]
@clystron we're likely going to ditch the legacy notices in 19.1

**Comment by fichtner** [comment]
Done via https://github.com/opnsense/core/commit/862d6a86d6ff if I'm not mistaken.
