### ISSUE TITLE
Disable ipv6 in unbound if system-wide ipv6 has already been disabled

### ISSUE THREAD

**Issue by soder10** [opnsense/core#2913]
Hello devs,

just a suggestion: if the Interfaces\LAN\IPv6 configuration type is set to "none", it would be helpful to signal  unbound not to try to use ipv6 for name resolution. At the moment resolver.log is full of similar entries:

unbound: [58191:0] info: error sending query to auth server 2600:9000:5303:3700::1 port 53

**Comment by fichtner** [comment]
Hi @soder10,

I'm not sure Unbound is restricted by LAN settings as it tries to reach out via WAN and seems to be getting a bit of connectivity for it?

IPv6 is generally preferred, but that can be changed via System: Settings: General: Prefer IPv4...


Cheers,
Franco

**Comment by soder10** [comment]
I have already set up "prefer ipv4 over ipv6" and I have Firewall\Settings\Advanced: Allow ipv6 UNCHECKED.

Still, under these conditions I still get these entries in the resolver.log.
Name resolution DOES work though, just there are many such failed attempts in the log.

**Comment by fichtner** [comment]
So, how can unbound be taught to prefer ipv4 as well? We can use the same setting, maybe unbound requires more force.

**Comment by soder10** [comment]
Is this unbound-related option set/unset during service-start, while opnsense ipv6 is NOT preferred?

do-ip6: (yes or no)

Enable or disable whether ip6 queries are answered or issued. Default is yes. If disabled, queries are not answered on IPv6, and queries are not sent on IPv6 to the internet nameservers. With this option you can disable the ipv6 transport for sending DNS traffic, it does not impact the contents of the DNS traffic, which may have ip4 and ip6 addresses in it.

**Comment by fichtner** [comment]
Done. Only two lines changed... would have been a great first contribution. :)
