### ISSUE TITLE
system: get_interface_gateway unable to find existing but unassigned gateways

### ISSUE THREAD

**Issue by ccesario** [opnsense/core#2914]
Hi, 

It seems that versions **18.7.6** and **18.7.7** are not creating automatic outbound rules. 
I need create Manual Outbound  Rules from LAN to WAN traffic works.

I have a **18.7.3** version that is working very well as expected.

https://forum.opnsense.org/index.php?topic=10183.0

**Comment by fichtner** [comment]
Following our discussion in the forum I've been over code and change logs but could not see something sticking out. What I can say for sure is if it's not listed under auto it will not be created as it uses the same data source function in both places. Are you using something like the os-cache plugin? what is your wan setup like?

**Comment by fichtner** [comment]
Could you give temporary access to the box via SSH, this will be easy to spot from there. I'm out of ideas otherwise. :( let me know via franco@opnsense.org

**Comment by ccesario** [comment]
Hi Franco, thank you by your effort. I will deploy other appliance and restore the current appliance backup in this new and I send you the credentials by email.

**Comment by fichtner** [comment]
@ccesario thanks!

**Comment by ccesario** [comment]
Hi @fichtner , 
I sent you the email with data.

Thank you!

**Comment by fichtner** [comment]
Hi Carlos,

Under WAN I set "IPv4 Upstream Gateway" to the actual gateway and it works as expected. The auto-detect doesn't seem to work here. I'll try to investigate why. It may be due to static configuration of WAN.

At least you can use your setups manually with this setting. :)


Cheers,
Franco

**Comment by fichtner** [comment]
Found a better fix. Will not fit into 18.7.8 but should be in time for 18.7.9.

**Comment by ccesario** [comment]
Hi Franco! 
Thank you by excellent help!!!

Nice to know that found a fix!!!! 

Best regards,

Carlos

**Comment by fichtner** [comment]
should be good on the latest development release shipping with 18.7.8. Workaround possible so we'll try to pull smaller chunks into several 18.7.x until all is in 19.1 eventually. :)
