### ISSUE TITLE
Feature request: CPU temp sensor output filter

### ISSUE THREAD

**Issue by soder10** [opnsense/core#2915]
Hello devs,

a small/minor cosmetic request for the GUI Dashboard: I have a quad-core embedded CPU box, where all cores report their own temp value. By accident, or on purpose I really dont know, but all cores report the very exact same value all over the time.  So on the dashboard I always see the same 4 lines of temp report. This takes quite some space on the dashboard, and practically has very little value. I know on some other systems, where cores are spread across separate packages, it makes sense to monitor all of them.

Could the widget include a filter e.g. to show only the value associated to CPU0, and dont display the other remaining ones? I can imagine on a dual-quad-core or hex-core system, the widget could take even more screen space.

Thanks in advance.

**Comment by AdSchellevis** [comment]
https://github.com/opnsense/core/pull/3000
