### ISSUE TITLE
PortField validation is broken

### ISSUE THREAD

**Issue by fabianfrz** [opnsense/core#2916]
see opnsense/plugins#976

* The validation should by default allow only numeric values (services should be added by an extra flag as most plugins expect ports to be numeric)
* The validation must not pass garbage data after the port / service

**Comment by AdSchellevis** [comment]
@fabianfrz it's not broken, but it looks like this field has been misused in other plugins as well. The IntegerField using min/max is meant to be used for number ranges. Not sure what your other issue is, the setter trims and lowers the input on `setValue()`

I will look at changing the behaviour, since core only uses this in the traffic shaper.

**Comment by fabianfrz** [comment]
You have to look at the screenshot. The user stored "443 default_server" in the field which is definitly invalid

**Comment by AdSchellevis** [comment]
ok, that's odd, it looks like `InclusionIn()` isn't fired, but seems to be used correctly https://github.com/opnsense/core/blob/eb95e8f53e56e25ce8f0898ee6936d8201bd9a29/src/opnsense/mvc/app/models/OPNsense/Base/FieldTypes/PortField.php#L140

**Comment by AdSchellevis** [comment]
found it, although I'm pretty sure this used to work in some version of phalcon. https://github.com/opnsense/core/commit/9349cffb2433273bed8d58e073250c2f08a8bd82

**Comment by fabianfrz** [comment]
@AdSchellevis thanks for your quick fix. Now the validation should work how users and developers do expect it to.

**Comment by fichtner** [comment]
@AdSchellevis there's a cosmetic issue with the validation message now as it hardcodes the well known ports mention:

https://github.com/opnsense/core/blob/3407a991329a19cf26bffda54b69390d70ae36d3/src/opnsense/mvc/app/models/OPNsense/Base/FieldTypes/PortField.php#L152
