### ISSUE TITLE
Monit: service tests and relation to service type

### ISSUE THREAD

**Issue by AdSchellevis** [opnsense/core#2918]
The monit service tests configuration contains different test options, but can be selected on every service now, in reality this would lead to configuration errors.

For example, when adding a file service, it's possible to select a ping test now.

I would like to suggest to add a service type field to the "Service Tests Settings" section, which can then be used as validation or selection filter in the service definition.

**Comment by AdSchellevis** [comment]
@fbrendel what do you think?

**Comment by fbrendel** [comment]
Basically sounds good.
However, the challenge is to find out which test is valid for which service.
E.g. existence tests are valid for files, directories, processes etc.
So we need a mapping between service types and test types (Fault tolerance, existence, resource...).
Much work and we have to watch for new test types on every Monit release.

On the other side Monit has already syntax checks and knows better what works and what not.
Yes, usability is important but I'd rather rely on Monit.

Don't get me wrong. It's a really cool idea.
But is it worth the effort?

If so, I'd implement it only in the UI.
Instead of the Condition textfield I'd add a Test Type dropdown list and
guide the user through all the possible options.

**Comment by AdSchellevis** [comment]
The valid combinations should be in the monit docs, my problem is that the current solution isn't very user friendly, with error messages like : 
![image](https://user-images.githubusercontent.com/9783985/48637622-19583980-e983-11e8-8f42-182a6efac998.png)

Which should be rather easy to prevent using proper validations in my humble opinion.

The original plan for adding Monit to core instead of a plugin was to remove the legacy notifications, which is a good plan given the Monit feature set, but it's a bit tough to use at the moment.
If we're actively going to steer people in using this, I kind of expect some support challenges, @fichtner what do you think?

**Comment by fichtner** [comment]
with the marginal notification support still left any replacement is better than what we have now. I'm happy to work on this, but maybe 19.1 is not the greatest time frame for removing the old ones... maybe just adding a first viable replacement as an optional method and keep improving from there?

architecturally I don't think any way other than too complicated to get started is worth going for.  small steps.. .we can still make it more complicated later?

(please don't expect a technical answer until I know the system well enough)

**Comment by AdSchellevis** [comment]
@fichtner I guess dropping the old could still be viable for 19.1, I really want to prevent any patches like https://github.com/opnsense/core/pull/2907 being needed for stuff that should go away. I expect we can add some simple tests, disabled by default like `RootFS` thing now. 

I'll work on the needed tests, this validation issue can wait until after 19.1 in my opinion.

**Comment by fbrendel** [comment]
@AdSchellevis you're right. It's a bad idea to point the user to third party docs for a core function.

If I understand you right you'll add tests and services for the notification replacement?
So I'll add the suggested test types and everything necessary for that.

**Comment by AdSchellevis** [comment]
@fbrendel I'll try to add the things needed to replace the old (https://github.com/opnsense/core/issues/2919), improving the validations is work that still needed to be done then. But there's no rush in my opinion, so improving validations could also entre post 19.1.

It would be good to add some basic documentation for 19.1 in our docs, is that something you would be willing to work on?

**Comment by fbrendel** [comment]
Ok, 19.1.x is realistic.
The documentation comes with the new version then.

**Comment by AdSchellevis** [comment]
Hi @fbrendel,  @MichaelDeciso added some basic documentation (https://github.com/opnsense/docs/pull/91),  maybe you want to review it before we publish it do the docs.

**Comment by fbrendel** [comment]
Cool :smiley: 
Looks good.

**Comment by fichtner** [comment]
on my end migration and tests don't really work: (empty) migration fails, tests fail
