### ISSUE TITLE
Drop legacy notices [notify_via_smtp]

### ISSUE THREAD

**Issue by AdSchellevis** [opnsense/core#2919]
As a followup on https://github.com/opnsense/core/issues/2912 and https://github.com/opnsense/core/pull/2907, we should drop the legacy notices which are being send out and add glue for monit where needed.

Currently there are only two spots where the notifications are (kind of relevantly) used:

- carp changes https://github.com/opnsense/core/blob/702f9af71f9b2d2e6684a628a89a33daabb4db2f/src/etc/rc.syshook.d/carp/20-openvpn#L55
- gateway changes in https://github.com/opnsense/core/blob/6172beb8f4cbc764fa96727405b0c51ecf9144ef/src/etc/inc/gwlb.inc#L708 and https://github.com/opnsense/core/blob/6172beb8f4cbc764fa96727405b0c51ecf9144ef/src/etc/inc/gwlb.inc#L727

The notify() function itself for filter configuration issues should remain for now, since these messages have no other clear feedback to the user.

**Comment by fichtner** [comment]
I've closed #2408 :)

**Comment by MichaelDeciso** [comment]
I was wondering: are we talking about just notices via SMTP, or are we talking about all `notices.*.inc` files?

**Comment by AdSchellevis** [comment]
The ones aiming the user directly should stay (firewall load issues), they don't need to be broadcasted via mail.

**Comment by MichaelDeciso** [comment]
Ah. How about the SASL files, for example the one with NTLM authentication? Would those stay or be removed? (I can't find direct evidence of that one being used, for example, but it does use the mcrypt extension, which has been removed in PHP 7.2).

**Comment by AdSchellevis** [comment]
@MichaelDeciso  leave all for now, we need a replacement for the gateway switch detection, then we can start removing stuff. In case you would like to work on that part, just let me know.

**Comment by AdSchellevis** [comment]
https://github.com/opnsense/core/pull/3031
