### ISSUE TITLE
system/trust: Allow to set password for P12 export

### ISSUE THREAD

**Issue by jpawlowski** [opnsense/core#2922]
The current P12 export functionality is kind of useless when dealing with Windows machines. Those machines always expect the P12 trust store to be password protected and will not allow empty passwords.

It would be good to be able to protect the P12 export file with a password directly, avoiding somebody needs to take additional action using openssl commands afterwards.

**Comment by jpawlowski** [comment]
https://github.com/opnsense/core/issues/2923#issuecomment-439605381
https://github.com/opnsense/core/issues/2923#issuecomment-439606698

**Comment by mimugmail** [comment]
@jpawlowski 

https://github.com/opnsense/core/pull/2926

I need some time for Boostrap .. perhaps it'll be in 19.1 ..

**Comment by jpawlowski** [comment]
No worries, thanks for your efforts in this regard!
Bootstrap surely is a bitch...

**Comment by fabianfrz** [comment]
final version committed by @AdSchellevis

**Comment by AdSchellevis** [comment]
it should be safe to close this one now, (https://github.com/opnsense/core/pull/2926, https://github.com/opnsense/core/commit/8a4c4614420f332222d6fbf006c17bd6a35f7765)
