### ISSUE TITLE
system/trust: Distinguish certificates with same common name

### ISSUE THREAD

**Issue by jpawlowski** [opnsense/core#2923]
In case there are multiple certificates with the same common name but with different settings (e.g. different SAN or key length/type), it is impossible to distinguish between them in any of the GUI views as there are simply multiple certificates to choose from. This results in a lot of try-and-error to find the correct certificate.

Either a dedicated custom certificate name shall be possible (or even mandatory, see the "small p" fraction) or at least one should be able to see the description field content in every view somehow (tooltip?). Simply adding the description to the line might be bad, depending on its length.

**Comment by AdSchellevis** [comment]
Hi @jpawlowski, are you planning to work on some of your requests as well? 
They seem to stack-up rapidly....

**Comment by jpawlowski** [comment]
@AdSchellevis Not for the moment as I'm unfamiliar with model-view-controller concept as such. Tried to understand some of the code in OPNsense but never got it just easily. Lacking time for a deeper dive besides doing troubleshooting already (it s not my only opensource arrangement).

**Comment by mimugmail** [comment]
Trust Code is legacy code base like in pfsense. If it would be MVC I'd have already added this.
I don't know all the dependencies, but I could imagine a new text box when adding certs for password. 
This would be noneditable an stored in config.xml. When downloading password is passed along the command.

**Comment by mimugmail** [comment]
https://github.com/pfsense/pfsense/blob/master/src/usr/local/www/system_certmanager.php#L185

Password is static to `null` .. perhaps just add a if `isset` to a new field and use password, else set `null`

I'm quite sure your php skills are better than mine :) You want to try?

**Comment by jpawlowski** [comment]
Don’t mix up this report with another one about the password thing ;)

**Comment by AdSchellevis** [comment]
@jpawlowski 
> it s not my only opensource arrangement

If nobody would contribute, there probably wouldn't be any free software would there? It's good to realise that your free to create tickets, but for your wishes to progress it might need more then placing an order.....

**Comment by AdSchellevis** [comment]
@jpawlowski fair enough, thanks for taking the time to explain your motivation. We're all busy indeed, as long as expectations match reality it's certainly fine by me. 

(no offence taken by the way, just making sure we all understand the rules)

**Comment by johnaheadley** [comment]
Should this be closed?

> In case there are multiple certificates with the same common name but with different settings (e.g. different SAN or key length/type), it is impossible to distinguish between them in any of the GUI views

> Either a dedicated custom certificate name shall be possible or at least one should be able to see the description field content in every view somehow

At least for System > Trust > Certificates, all the above are true now.

- Name column shows custom name
- Distinguished Name column shows SANs
- In Use column displays the info button which allows you to see all details of cert, including key length/type

![Screen Shot 2019-08-10 at 10 35 21 AM](https://user-images.githubusercontent.com/11711559/62825116-8a67fe80-bb5b-11e9-9485-f6e9ed8e6159.png)

The only thing I can see to add here is that System > Trust > Authorities does not have the info button. What do you all think?

**Comment by AdSchellevis** [comment]
@johnaheadley I agree, if there's anything still missing, it's better to open a new issue with a precise description of what's missing.
