### ISSUE TITLE
Feature request: DHCP leases counter

### ISSUE THREAD

**Issue by 2fun0** [opnsense/core#2924]
Hi,

would be nice to have a counter of how many DHCP leases are in use. I am aware that you can gather it by yourself with the CLI but would be convenient to have the summary in the same page as the status.

Thank you for the great job!

**Comment by fichtner** [comment]
<img width="317" alt="screenshot 2018-11-19 at 7 54 34 am" src="https://user-images.githubusercontent.com/1915288/48690882-a0e6b800-ebd0-11e8-83b3-c16bd24c382e.png">

will look like this :)

**Comment by Megachip** [comment]
Can we have it per subnet and also in %?
