### ISSUE TITLE
flow_aggregate.py randomly stops working

### ISSUE THREAD

**Issue by mibofra** [opnsense/core#2928]
https://github.com/opnsense/core/blob/2d0075de05b3838fe19d57f5bdd8388df119467f/src/opnsense/scripts/netflow/lib/aggregate.py#L251

Hi! Some times has happened that flow_aggregate stopped to work because in this line sometimes it happens to have a float division by zero.

Well, I love the project, but really I was pissed off. So I've modified the line in:

`                consume_perc = (consume_end_time - consume_start_time) / (float(flow['duration_ms']) / float(1000))`

I've been working with this modification for some weeks, at least a month, and it is working! Just, every time I update the firewall, to another release, I've to modify again the code.

Because I think it could help others, please, try to give this line a chance in upstream :) . Thanks!

**Comment by AdSchellevis** [comment]
@mibofra nice catch, the `/1000` should have been` /1000.0` to avoid a division by zero.

**Comment by AdSchellevis** [comment]
can you try https://github.com/opnsense/core/commit/bb90be17c700454e3f99c78740d8ba709988c61d ? it should have the same result as your fix

**Comment by mibofra** [comment]
Sorry, you are right. I've casted both but 1000.0 is the right precision. Thanks a lot! It was annoying to me, I guess to others too.

**Comment by fichtner** [comment]
@mibofra many thanks, it will be added to the 18.7.8 release.
