### ISSUE TITLE
add d3js to standard library and replace prototype in diag_logs_filter_summary.php 

### ISSUE THREAD

**Issue by AdSchellevis** [opnsense/core#294]
From an earlier idea of @fabianfrz we would like to use d3js for some additional insights. Too prevent all kinds of javascript libraries doing almost the same thing, we should however choose what to use and try to stick to it.

In diag_logs_filter_summary.php  the prototype.js is used, but wasn't available in OPNsense, as a result of that the diagrams weren't shown. 
The short time solution is to pull prototype.js in ( https://github.com/opnsense/core/pull/293 ).
When this fix is done, prototype must leave our system again.

**Comment by jschellevis** [comment]
Done... diag_los_filter_summary fixed in f9333ee
