### ISSUE TITLE
boostrap dropdown colors changed? why ? (latest 19.1 dev)

### ISSUE THREAD

**Issue by opnsenseuser** [opnsense/core#2947]
![fields](https://user-images.githubusercontent.com/34602360/48802153-a518ef80-ed0e-11e8-95bc-6601701ca9d5.jpg)
![fields_opnsense](https://user-images.githubusercontent.com/34602360/48802154-a518ef80-ed0e-11e8-83a6-52cc9fab5fd3.jpg)
@fichtner Do I have to adjust the themes again?

**Comment by fichtner** [comment]
https://github.com/opnsense/core/pull/2939/files -- the css file is now being versioned, so you can add the new file and have compatibility for production and development version. I believe this change will stay on development for a while, maybe until 19.1.

**Comment by opnsenseuser** [comment]
@fichtner but this is only for dev and not nessesary for prod? 
or is it just about the change of name of bootstrap files? Will this stay with the new name in the future or will it get back the old name?

I do not necessarily want to include two files, because it also increases the loading time.

**Comment by fichtner** [comment]
the bootstrap select version was updated, which updated css as well. only one file is used depending on which version is running.

**Comment by opnsenseuser** [comment]
that means I have to adjust the new file and put in the respective theme directory? do I have to integrate the file in the main.css of the respective themes? best regards

**Comment by fichtner** [comment]
nope, just add the new css file and adjust colours to taste

**Comment by opnsenseuser** [comment]
Ok, thx. I will do this in the evening and make a pr for both themes!

**Comment by opnsenseuser** [comment]
@marjohn56 hope you are well. FYI, regards rene

**Comment by marjohn56** [comment]
I'm fine, just extremely busy with a massive work project which is taking up all my time, and likely to do so through until February.
