### ISSUE TITLE
FR: harden config import

### ISSUE THREAD

**Issue by EugenMayer** [opnsense/core#2949]
After trying the config import yesterday (first time) i ended up having a couple of surprises which i think we could fix in 19.0 and end up closing the gap to "install the configuration on a new hardware and you are set to go"

**I. Plugins**
a) Persist the list of "plugins" installed when saving a configuration. 
b) Create a new section in "import" and add "Plugins" 
c) when importing a configuration, try to activate the plugins. If it does not work ( missing or similar ) show an warning ( do not hard error )

---

**II. Validation of interfaces**
My interfaces changed from vtnet0/1 to em0/1 - i understand that its hard to fix this is when i remap the interfaces - but we could at least validate and point the user on where he needs adjustments.

What happened to me was that after re-assigning the interfaces, several things were "invisibly broken":
 - inbound/outbound NAT rules where broken - one could see that there was no interface from the UI
 - Gateways where broken
 - VLAN devices where broken (binding to vtentX still)

Most of the issues are very easy to fix for the human, i expect it will be rather hard for us to do this automatically. What is not easy for the human is, that he has to find all this places himself. so what i would suggest would be

a) on import / save interface assignment run a validation of all settings which "use the inferface as primary key" and tell the users that X, Y, Z is using a interface which no longer exist
b) If it would be any possible ( might be a lot of effort ) provide deep links into the configuration sections

---

**III. Minimum platform version**
a) Save the platform version during the configuration export
b) Save the minimum version of a platform you need when importing (just have a method returning a static string and change that if we have upstream changes which break config compat, e.g. aliases in 18.7.5 .. which are incompatible with 18.7.0 .. so min would be 18.7.5 )

The above is just the first step/milstone, later
c) give all "config importers" so the GUI / `opnsense-importer` the ability to validate this and tell the user about the issue. Allow the user to force the import anyway (to keep legacy support in every case) but this will help users to understand, that they need to upgrade first.

---

I am aware that this is rather a larger FR, maybe needs to be splited up in several, let me know. I think all of them are long hanging fruits and can be implemented rather "defensively" .. but adding a huge value to OPNsense USP of "all configuration is serialised and can be reimported" - letting you setup a new box very fast and convenient.

**Comment by soder10** [comment]
I think the removal of "igb" from Freebsd 12.0 will be a disaster for all upgrades from 11.x

**Comment by fichtner** [comment]
Just some thoughts...

I) should be https://github.com/opnsense/core/issues/1663 but we'll never probe or install automatically, just hint at missing things...
II) not sure, we could stall and wait for input or we could recover from scratch like when hard disk is inserted into a new hardware? middle grounds are fuzzy and highly subjective :/
III) c) is what we discussed for the import page tying all MVC-related configuration models to the import in order to validate data. for a command line tool spanning a) and b) its harder for similar reasons as II)

**Comment by fichtner** [comment]
timeout

**Comment by EugenMayer** [comment]
Close anytime you like
