### ISSUE TITLE
Captive Portal: problem with allowed ip address and logged users

### ISSUE THREAD

**Issue by woooow1** [opnsense/core#2956]
I have problem with captive portal in 18.7.7, and now in 18.7.8.After reboot allowed ip addresses are not allowed, and logged users must logout, and then login again. If I re-apply settings in 
Services: Captive Portal: Administration, everything start to work.
 
Log show me this:

captiveportal: Traceback (most recent call last): File "/usr/local/opnsense/scripts/OPNsense/CaptivePortal/cp-background-process.py", line 218, in main bgprocess.db.update_accounting_info(bgprocess.ipfw.list_accounting_info()) File "/usr/local/opnsense/scripts/OPNsense/CaptivePortal/lib/ipfw.py", line 104, in list_accounting_info stderr=devnull) File "/usr/local/lib/python2.7/subprocess.py", line 190, in check_call raise CalledProcessError(retcode, cmd) CalledProcessError: Command '['/sbin/ipfw', '-aT', 'list']' returned non-zero exit status 71

**Comment by fichtner** [comment]
@AdSchellevis looks like this is due to https://github.com/opnsense/core/issues/2569 -- shall we move captive portal setup to last action after ipfw setup or is there a more graceful way to deal with this?

**Comment by AdSchellevis** [comment]
@fichtner I'm afraid we should do that, I don't have a real better looking solution at the moment.

**Comment by woooow1** [comment]
Confirmed as working!
