### ISSUE TITLE
OpenVPN Client Specific Override is not bound to a server

### ISSUE THREAD

**Issue by sjorge** [opnsense/core#296]
The client override should be bound to a server.

User A can connect to Server 1 and Server 2, he could need specific settings that is different between server 1 and server 2, say give him a fixed IP in 2 different networks. This is currently not possible.

Ideally there should be a checkbox list for each server. So a profile can be enabled on multiple servers too.

I guess the easiest implementations is to store them somewhere and symlink them in a per server directory.

**Comment by AdSchellevis** [comment]
@sjorge I've just created a fix for this feature request, if you have time to test, you can download the next files over a 16.1 release.

```
curl -o /usr/local/etc/inc/openvpn.inc https://raw.githubusercontent.com/opnsense/core/master/src/etc/inc/openvpn.inc
curl -o /usr/local/www/vpn_openvpn_csc.php https://raw.githubusercontent.com/opnsense/core/master/src/www/vpn_openvpn_csc.php
curl -o /usr/local/www/vpn_openvpn_server.php https://raw.githubusercontent.com/opnsense/core/master/src/www/vpn_openvpn_server.php
```

**Comment by sjorge** [comment]
I'm not near my setup at the moment so testing is a bit hard. 

If I don't forget I'll try to poke it this weekend

---
~ sjorge 

On 2016-02-11 18:30, Ad Schellevis wrote:

> @sjorge [1] I've just created a fix for this feature request, if you have time to test, you can download the next files over a 16.1 release.
> 
> curl -o /usr/local/etc/inc/openvpn.inc https://raw.githubusercontent.com/opnsense/core/master/src/etc/inc/openvpn.inc
> curl -o /usr/local/www/vpn_openvpn_csc.php https://raw.githubusercontent.com/opnsense/core/master/src/www/vpn_openvpn_csc.php
> curl -o /usr/local/www/vpn_openvpn_server.php https://raw.githubusercontent.com/opnsense/core/master/src/www/vpn_openvpn_server.php
> 
> --
> Reply to this email directly or view it on GitHub [2].
 

Links:
------
[1] https://github.com/sjorge
[2] https://github.com/opnsense/core/issues/296#issuecomment-182967742

**Comment by AdSchellevis** [comment]
Thanks in advance!

**Comment by fichtner** [comment]
@sjorge any news here? :)

**Comment by sjorge** [comment]
Looks good at first glance, due to losing my 2nd external IP i can't give it a very thorough shake down though.

**Comment by AdSchellevis** [comment]
@sjorge Thanks for testing!
