### ISSUE TITLE
system log widget - lines limiting?

### ISSUE THREAD

**Issue by opnsenseuser** [opnsense/core#2960]
in my opinion, the lines should be limited, because the user can anyway come at any time with a click in the detail view of the system logs. And so on the dashboard would also allow a much clearer presentation. and it would not turn out to be an endless line view as I have stated in my screenshot.

![grafik](https://user-images.githubusercontent.com/34602360/48933494-bf1a2400-ef00-11e8-8c15-046203946332.png)

**Comment by opnsenseuser** [comment]
@AdSchellevis can we also limit the lines for the log widget?

**Comment by AdSchellevis** [comment]
@opnsenseuser you mean the length of the line? Kind of "`my very long log line....`"

**Comment by opnsenseuser** [comment]
@AdSchellevis The log entrie should have a limited number of lines. The screenshot shows a single log entrie and that is so long, that it even at 1080 height, the browser scrolls. and that for a single log entry!. And if I allow 20 log entries I have an endless long column

**Comment by opnsenseuser** [comment]
@AdSchellevis of course, this is 6 columns dashboard view!

**Comment by AdSchellevis** [comment]
I don't think there's a great solution for this, data will always wrap. We might limit line length, which has other disadvantages. I guess this widget isn't really that useful to be honest.

**Comment by opnsenseuser** [comment]
@AdSchellevis yes, fix should be like you said -> "my very long log line....". for more details you have the detail view of the system logs!

**Comment by AdSchellevis** [comment]
Let's keep the issue open, it's not very high on my priority list, but don't mind a fix either.

**Comment by opnsenseuser** [comment]
@AdSchellevis I understand you and also the problematic, but, that would make the system log pointless for me, since I have to scroll endlessly each time and this is no longer quick and easy to read.

**Comment by opnsenseuser** [comment]
@AdSchellevis and for me the dashboard should be easy and quick to read!... but thx for your support. i´ll keep it open!
