### ISSUE TITLE
Features Request: On Radius, Captive Portal, Wizard and Proxy

### ISSUE THREAD

**Issue by akram1** [opnsense/core#2962]
OPNSense is getting better on every release. There couple of features I see it missing.

Radius
    add For Users
        1- Max Daily Download (MB)
        2- Max Daily Upload (MB)
        3- Generate Password
        4- Mass copy of user account with new generated passwords
        5- User Account Template: a template is a place to store account configurations and apply it on specified users instead coping the same configuration on each user.
        
Captive Portal
    1- Auto delete expired vouchers and voucher group if group is empty

Access
   More options on Password Generator
        1- Select box: Generate Password using: Only Uppercase, Only lower case, both, numbers only
   
Wizard
    Configure
        1- Captive Portal
        2- MultiWAN
        3- Radius
        4- Access LAN From outside through NAT farwarding
        5- Proxy
        6- VPN
    All wizards changes can be reverted by making use of backup and restore features. All wizard are very easy to follow and to configure.
        
Proxy
    1- Adapt https caching without certificate as an option

**Comment by mimugmail** [comment]
For Radius adding Max-Up is not a problem, but you need an application respecting these values.
Templates would need group support which relies on SQL .. I dont have the time to add this, but I'd be glad to help if someone likes to. Otherwise you could also use the API to script this.

I'm not a fan of wizards .. they are error prone and the user doesn't learn anything, also when it comes to troubleshooting.

**Comment by akram1** [comment]
1- Do you mean Max-Up and Max-Down or just up?
2- What about captive portal: Auto delete expired vouchers and voucher group if group is empty?
3- Can you ease Voucher Generator. Users complain about mixed capital and small letters in User/pass.
4- https proxy without certificate as an option
Proxy implements the so-called “peek and splice” behavior: it establishes the SSL connection with remote sites and checks the validity of certificates without decrypting the traffic. Then the server can filter requested URLs using the web filter and return back the response to the client.

**Comment by mimugmail** [comment]
1) both
2-4) other dev's, not me

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository, 
please read https://github.com/opnsense/core/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue, 
just let us know, so we can reopen the issue and assign an owner to it.
