### ISSUE TITLE
Support being a DHCP server for remote subnets

### ISSUE THREAD

**Issue by steveo1664** [opnsense/core#2963]
We have OPNsense deployed in a datacentre where we need to issue DHCP IP addresses from OPNsense to remote subnets (i.e. they have been configured to use DHCP relay).

Is it possible for OPNsense to support issuing IP addresses to remote subnets using DHCP relay?

**Comment by fichtner** [comment]
You're likely referring to https://github.com/opnsense/core/issues/910 ?

**Comment by steveo1664** [comment]
ooops, sorry.
