### ISSUE TITLE
Network insight, cleanup and testability

### ISSUE THREAD

**Issue by AdSchellevis** [opnsense/core#2964]
Cleanup the flowd aggregator and ease testability a bit (support custom config paths).

**Comment by fichtner** [comment]
Both my main installs have issues since this work started with flowd_aggregate stopping soon after startup. On the office box port total still work, but traffic is always empty.

**Comment by AdSchellevis** [comment]
@fichtner sorry about that, I just noticed the same on my box too, fix will follow

**Comment by fichtner** [comment]
@AdSchellevis no worries, just letting you know before forgetting about it again :)

**Comment by AdSchellevis** [comment]
@fichtner can you sync again? the current status should be good, I've fiddled a bit with parameters, it should be more consistent now.

**Comment by fichtner** [comment]
looks good, many thanks!
