### ISSUE TITLE
OpenVPN & OSPF problem on 18.7.8

### ISSUE THREAD

**Issue by fprina** [opnsense/core#2971]
After the update to 18.7.8 (from 18.7.7) my OpenVPN & OSPF stopped to work; I see the "_ospf neighbor_" but the routes are not exchanged 
  
From my tests the problem is related to the following PF rules:
```
pass out log route-to (ovpnc1 10.8.146.12) inet from 10.8.146.12 to ! (ovpnc1:network) flags S/SA keep state allow-opts label "let out anything from firewall host it
self"
pass out log route-to (ovpnc2 10.8.147.12) inet from 10.8.147.12 to ! (ovpnc2:network) flags S/SA keep state allow-opts label "let out anything from firewall host it
self"
```
That rules are missing in 18.7.7 and if I remove them from 18.7.8 all restart to work as I expect 

PS:
In the 18.7.7 the "_route-to_" rules was present for all the interfaces except the "_ovpn_"

**Comment by AdSchellevis** [comment]
I don't see obvious changes in gateway or firewall code between 18.7.7 and 18.7.8 which could explain this. You could hoever disable the automatic route-to rules and add manual ones to prevent this. (
"Disable force gateway" in system_advanced_firewall.php).

Maybe you defined manual gateways over openvpn at some point in time?

Gateways are linked here
https://github.com/opnsense/core/blob/2601f23b74d5d713b1920586c63c6d7f6bb5e537/src/etc/inc/filter.lib.inc#L74-L75

Which then generate the mentioned rules here
https://github.com/opnsense/core/blob/2601f23b74d5d713b1920586c63c6d7f6bb5e537/src/etc/inc/filter.lib.inc#L509-L524

**Comment by fprina** [comment]
Yes maybe I defined manual gateways over openvpn at some point as "random tests" but not in the current configuration.

To be able to manage in OSPF plugin the interfaces create by OpenVPN I've assigned a them via the web interface.
 
"Disable force gateway" seems solve the problem but honestly I don't really understand the meaning and moreover consequence ... :-(

**Comment by AdSchellevis** [comment]
It generates rules to force the gateway of outbound packets when there's a gateway defined for the network, you can also add the desired rules manually. (Usually on your WAN interface you want to prevent packets using another gateway then the defined one)

**Comment by fprina** [comment]
Maybe the recent changes added something that manage the assigned ovpn interfaces or the auto generated gatway as the others.

I tried to remove the assignment and the route-to rules magically disappear (as the related auto generated gatway)... 

... unfortunatelly the OSPF stopped to work because of the missing configuration of the interfaces

**Comment by fichtner** [comment]
"Maybe" needs to replaced by finding the bad commits if they exist :) something can have changed, but it could also be undocumented / undefined behaviour which now breaks due to complexity limitations or general "no, this shouldn't have worked before" so we can fix it properly and lower long-term maintenance.

**Comment by mimugmail** [comment]
Disable Force Gateway has to be enabled on Multi WAN .. and since you have a routed Tunnel, Multi WAN also fits here ..

**Comment by fprina** [comment]
There are no "bad commits" it's looks to a more consistent behaviour now ... was my implementation that used to work _just with a bit of "luck"_ :-P

For curiosity I tryed to search something in the recent commits relate to the gateways but nothing evident to my eyes. 

"Disable Force Gateway " solve my proble so I close the issue.

Thanks to all

**Comment by fichtner** [comment]
@fprina thanks for the response. if there's oddity to work on I'm happy to take a closer look... I am reworking some interface/gateway logic at the moment.

**Comment by fprina** [comment]
@fichtner as _"oddity"_ I've just noticed that  the "Dashboard: gateway widget" of 18.7.8 show the IP address for the OpenVPN  <interface_name>_VPNV4 auto created gateway; in the previous release was listed the interfaces but without the address
