### ISSUE TITLE
Preceeding space in opvn config for key-direction 1

### ISSUE THREAD

**Issue by jdavey-enable** [opnsense/core#2972]
The exported client ovpn configuration file has " key-direction 1" at the bottom with a space in front.
The workaround is to add additional configuration options of "key-direction 1" without the space.

**Comment by AdSchellevis** [comment]
We're going to drop the old exporter in favour of the new one being developed now in 19.1, this will also fix the access space in "key-direction"

https://github.com/opnsense/core/blob/ceb54b9657474649d4853edc712c38d0eba9276c/src/opnsense/mvc/app/library/OPNsense/OpenVPN/PlainOpenVPN.php#L170
