### ISSUE TITLE
Proxy Auto-Config rules order of proxy entries

### ISSUE THREAD

**Issue by Kimotu** [opnsense/core#2979]
I created two proxy entries and a direct one.

When I use the rules to combine matches and proxies, my proxy order gets messed up when saving the rule.

I want: proxy1, proxy2, direct

When I save, it gets reversed to direct, proxy2, proxy1. The direct "proxy" should act as fall-back. The order is not alphabetical. I tried to name them A, B, C and order is still, C, B, A. I even added them in reverse order, but sort criteria must be something else, even not ip address because proxy1 is lower ip than proxy2.

The resulting wpad.dat creates the saved order which is wrong. The order should be kept the way you add the proxies.

**Comment by fabianfrz** [comment]
(FYI) @fichtner @AdSchellevis this is a model relation field and the usual GUI component (select_multiple). Maybe there is something you want to do in the used scripts but I don't think there is something we can do.

**Comment by mimugmail** [comment]
Is this sorting related? I did workaround this in frr/bgp with extra priority field

**Comment by fichtner** [comment]
isn't this the same issue as always? expecting order when we don't pledge order in the model-relation selection?

**Comment by fabianfrz** [comment]
maybe yes, some kind of an order field can be added but I think that users expect it to be stored in the order they enter data. Maybe an UX issue.

I never planned that to be ordered because it is designed like  "use A and if it fails, use B".

**Comment by mimugmail** [comment]
Yep, but as always there's one guy using it the way you never thought of.

This is how I did it:
https://github.com/opnsense/plugins/blob/master/net/frr/src/opnsense/service/templates/OPNsense/Quagga/bgpd.conf#L172

**Comment by Kimotu** [comment]
It's designed to be used in order from left to right with fallback of last
resort in very right.

Even Mozilla developer pages show examples explicitly mentioning fallback
solutions in very right.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Proxy_servers_and_tunneling/Proxy_Auto-Configuration_(PAC)_file#Setting_a_proxy_for_a_specific_protocol

Am Mi., 28. Nov. 2018, 20:48 hat Michael <notifications@github.com>
geschrieben:

**Comment by fichtner** [comment]
Sorry for the confusion. We're not talking about PAC.

**Comment by Kimotu** [comment]
Any progress this subject? Maybe you can do the sorting in backend by name? Then I could use prefixes 01_proxy, 02_proxy, 03_direct to set order?

**Comment by fichtner** [comment]
Sort order was introduced in recent 19.1.x versions for HAProxy in particular. Maybe it can be used here too. @fabianfrz will be back next week and likely look into it.
