### ISSUE TITLE
Running out of swap 1x/week

### ISSUE THREAD

**Issue by larseggert** [opnsense/core#2981]
I have a pretty basic setup of opnsense, but under 18.7.6 and 18.7.7, it has been running out of swap (`swap_pager_getswapspace(16): failed`). When that happens, the OS starts killing processes, and once it's killed `dhcpd`, there goes my connectivity.

It's hard to figure out what is causing this, opening the ticket to see if anyone has any debugging ideas or other ideas what I could try. The hardware (i5, 8GB) should be pretty overpowered for my current DSL 50/10 link (see attached [dmesg.txt](https://github.com/opnsense/core/files/2627964/dmesg.txt)).

(I could obviously periodically reboot it, but that's not really a satisfactory solution)

**Comment by mimugmail** [comment]
Which services so you Run? I know rspamd is very memory intensive

**Comment by larseggert** [comment]
I just disabled `suricata`, to see if that is the culprit. These remain: 
```
apinger
configd
dhcpd
dhcpd6
dyndns
flowd_aggregate
ipfw
login
ntpd
openssh
pf
radvd
samplicate
strongswan
syslog
unbound
```

**Comment by mimugmail** [comment]
Stop Insight/Netflow for one week and see what happens. If you dont need the old graphs you can first try to repair and/or delete the DB. 

Syslog should also give you more Info when it happens

**Comment by larseggert** [comment]
Done. How do I delete the database?

**Comment by mimugmail** [comment]
Reporting : Settings : Reset Netflow Data (but only if you dont need them)
