### ISSUE TITLE
GeoIP alias fails if you don't specify IPv4 and/or IPv6

### ISSUE THREAD

**Issue by Taomyn** [opnsense/core#2986]
v18.7.8-amd64

The GUI when configuring a GeoIP alias doesn't check if the IP type is set to either IPv4 and/or IPv6 which means if left blank the alias does not work.

For example, create a GeoIP alias for one country and it can look like this:

![clipboard01](https://user-images.githubusercontent.com/4365929/49278288-9bb52300-f484-11e8-99c4-58622e22d5f0.jpg)

Create a WAN rule that uses this alias, I was blocking IPs not from the alias (source inverted), to a specific TCP port. The rule was blocking all IPs even from Luxembourg.

Changed the alias to:

![clipboard02](https://user-images.githubusercontent.com/4365929/49278370-dc14a100-f484-11e8-83d2-59f285f08452.jpg)

And the rule worked correctly, only blocking non-Luxembourg IPs

**Comment by AdSchellevis** [comment]
it should add both when empty, but it doesn't appear to do so.... I'll prepare a fix right away.

**Comment by AdSchellevis** [comment]
To try:

```
opnsense-patch a8b0c06
````

On a console, then apply the aliases again.

**Comment by Taomyn** [comment]
Thanks for the prompt response.

I will test it tonight as I'm remote and don't want to risk locking myself out.

**Comment by AdSchellevis** [comment]
No rush, thanks for reporting.

**Comment by Taomyn** [comment]
I just remembered, I think when I set it to IPv4 and IPv6, it also failed to work on the IPv4 only rule. I can double check later but I'm sure that's what happened. It goes along with recommendation to always split IPv4 and IPv6 rules apart that someone on the forum once told me.

**Comment by AdSchellevis** [comment]
It shouldn't do that, you can easily check what's in the table using https://your.host/ui/firewall/alias_util/ checking both on my end looks normal.
