### ISSUE TITLE
GEO_IP doesn´t work - crashes!

### ISSUE THREAD

**Issue by opnsenseuser** [opnsense/core#2990]
First of all, I've chosen alias as all countries that I need and then create the rule. but if I want to look at the pftable, the browser crashes and no content is displayed.

![geo_ip_alias](https://user-images.githubusercontent.com/34602360/49325722-8b19b100-f547-11e8-9fcb-5046085469dd.jpg)

![geo_ip_crashes_browser](https://user-images.githubusercontent.com/34602360/49325724-8e14a180-f547-11e8-9580-3c483f953044.jpg)

**Comment by AdSchellevis** [comment]
@opnsenseuser the content is too large for your browser,  pagination in the api call isn't supported here at the moment.

**Comment by opnsenseuser** [comment]
@AdSchellevis great 👍

**Comment by opnsenseuser** [comment]
@AdSchellevis 
@marjohn56 seems like it doesn´t work. i´m not the only one with this problem 

see https://forum.opnsense.org/index.php?topic=10192
and
https://forum.opnsense.org/index.php?topic=10458.0

**Comment by marjohn56** [comment]
Yup, reported this weeks ago, was told it was too late to hold back the release. My live system is still on 18.7.5_1 because of it.

**Comment by opnsenseuser** [comment]
is there a solution? and if when ?

**Comment by AdSchellevis** [comment]
@opnsenseuser please try not to clutter issues with too much noise. We've identified this issue (too much entries to view in the diagnostic page), someone else might have another issue https://github.com/opnsense/core/issues/2986, both in the same area and totally unrelated....

This isn't helpful....

**Comment by opnsenseuser** [comment]
@AdSchellevis sorry, was not my intention. will not happen anymore

**Comment by AdSchellevis** [comment]
closed by https://github.com/opnsense/core/pull/3039
