### ISSUE TITLE
Lobby: Dashboard loads all plugins.inc.d/*.inc

### ISSUE THREAD

**Issue by NOYB** [opnsense/core#2991]
Is it intended for the Lobby: Dashboard to load all the includes in plugins.inc.d?

plugins.inc.d/abc123.inc:
```
<?php
function abc123() {
    $zyx987 = 'abc123zyx987';
}
function abc123() {
    $azyx987 = 'abc123zyx987';
}

// PHP Fatal error:  Cannot redeclare abc123() (previously declared in /usr/local/etc/inc/plugins.inc.d/abc123.inc:3) in /usr/local/etc/inc/plugins.inc.d/abc123.inc on line 7
```
// Load Lobby: Dashboard page results in function re-declare.  i.e. the abc123.inc file was loaded.  Why?  It is not used by core or plugins.

19.1.b_405

**Comment by fichtner** [comment]
plugins.inc.d contains info such as services to be displayed in the service widget. we need to read all of them and we should not guard against fatal errors during require.

**Comment by NOYB** [comment]
Thanks for the explanation.  Please entertain a follow up question.

Does the services widget or other dashboard features need dyndns.inc, rfc2136.inc, wol.inc, and such?
Their respective widgets obviously.  But those have, or should have, their own require statements.
Just seems like that if plugins.inc.d/*.inc is to be loaded that maybe some of these don't need to be there.  Maybe in a respective directory instead.  But I'm probably still missing something here.

Thanks

P.S. Wasn't intending to imply to guard against fatal errors during require.  Was just an illustration to show it was loading.
