### ISSUE TITLE
Outbound NAT Destination IP invalide

### ISSUE THREAD

**Issue by kenshin33** [opnsense/core#2992]
Tryin to add a no nat rule (from  a specific IO to a specific IP) I  get an error saying that a valid destination IP is required (the IP I put in is valid)
grep and git blame took me to  line 181 of src/www/firewall_nat_out_edit.php 
 
https://github.com/opnsense/core/commit/d4b2f161e8f6379ccda95a049a6681b7be4e5380 modified said line 
from 

      if (!(in_array($pconfig['destination'], array("any","(self)")) || is_ipaddroralias($pconfig['destination']))) {
to

      if (!is_specialnet($pconfig['destination']) && is_ipaddroralias($pconfig['destination'])) {

seems like a typo and should be 

      if (!is_specialnet($pconfig['destination']) && !is_ipaddroralias($pconfig['destination'])) {

**Comment by AdSchellevis** [comment]
@kenshin33 Thanks, it's a typo indeed

**Comment by fichtner** [comment]
Nice catch, fixed via 98bd679ba
