### ISSUE TITLE
OPNsense boxes crashing regularly on automatic upgrades

### ISSUE THREAD

**Issue by EugenMayer** [opnsense/core#2993]
I had this issue with all boxes when upgrading from 18.7.4 to 18.7.7- all boxes crashed on Sunday when trying to auto upgrade ( cron .. which is an issue for itself, since i deactivated it and it is still running .. opening a follow up issue on that #2994 ).

Today it happened with the 18.7.8 upgrade where ruby was part of it.

So whenever the upgrade is triggered using cron, the whole box stucks in the terms:
 - it does not longer accept connections
 - connecting using tty / serial and then entering the user - no chance to enter the password and connect to the shell
 - there is no way i can "inspect" the box further more

If have this issue on several boxes, all of them are KVM based ( proxmox 5 ) and for all of them i can fix it by upgrading through the cli.

Could there be a forgotten "non-interfactive" flag on the upgrades which then somehow leaves the box with an open read for a question? Since i do not configure the cron-job from firmware upgrades but chose it from the select box, i am not sure what there actually is.

This somehow changed somewhat in the early 18.7 or 18.1 where those upgrades were working without issues, maybe someone remembers what changed?

I cannot provide any further informations about the box status because i cannot connect to it, neither through ssh or tty/serial as mentioned above.

The part with ruby is total guessing / gut feeling, i would not say there is a fact to that right now.

Also interesting:
 - 2 other boxes, also 100% the same, same services, config and proxmox (and patch level) upgraded just fine from 18.7.7 to 18.7.8

**Comment by fichtner** [comment]
Likely a local issue. Timeout.
