### ISSUE TITLE
cron enable/disable UX probably confusing

### ISSUE THREAD

**Issue by EugenMayer** [opnsense/core#2994]
I disabled those firmware upgrade jobs

![image](https://user-images.githubusercontent.com/136934/49337776-f089a280-f618-11e8-88c0-74ee174afa32.png)

but there are still executed every sunday, see #2993 -

Since i am not that keen with the FreeBSD layout ( or the opnsense layout ) i am not able to provide anything else, i would need guidance for that.

- Checked /etc/crontab /etc/cron.d but those seem empty an probably not used by opnsense
- /usr/local/etc/crontab does not exist
- find /usr/local -name crontab did not show anything

Found `/usr/local/opnsense/service/templates/OPNsense/Cron/user.cron` and found some things under `/var` but i was not able to find anything further, sorry.

**Comment by mimugmail** [comment]
Are you sure you hit `Apply`? 
Can not reproduce here ... 

Model is OK:
https://github.com/opnsense/core/blob/master/src/opnsense/mvc/app/models/OPNsense/Cron/Cron.xml#L14

Templating also (checks if enabled):
https://github.com/opnsense/core/blob/master/src/opnsense/service/templates/OPNsense/Cron/user.cron#L10-L15

And `Apply` restarts cron:

```
Dec  2 10:12:57 OPNsense configd.py: generate template container OPNsense/Cron
Dec  2 10:12:57 OPNsense configd.py:  OPNsense/Cron generated //var/cron/tabs/nobody
Dec  2 10:12:57 OPNsense configd.py: [ae6b218d-606c-4810-919f-53be5a341748] restarting cron

```

**Comment by AdSchellevis** [comment]
duplicate https://github.com/opnsense/core/issues/2101
