### ISSUE TITLE
Adding a VLAN on a LAGG breaks connectivity

### ISSUE THREAD

**Issue by fraenki** [opnsense/core#2995]
(Tested on OPNsense 18.7.8 as well as 18.1.3)

I've added a new VLAN on a LAGG interface and this broke connectivity to/from OPNsense for 1-2 minutes:

```
Dec  2 22:19:42 opnsense kernel: vlan12: changing name to 'lagg0_vlan140'
Dec  2 22:19:43 opnsense kernel: ix0: link state changed to DOWN
Dec  2 22:19:43 opnsense kernel: ix1: link state changed to DOWN
Dec  2 22:19:43 opnsense kernel: lagg0: link state changed to DOWN
Dec  2 22:19:43 opnsense kernel: carp: 220@lagg0_vlan220: MASTER -> INIT (hardware interface down)
Dec  2 22:19:43 opnsense kernel: carp: demoted by 240 to 240 (interface down)
Dec  2 22:19:43 opnsense kernel: lagg0_vlan220: link state changed to DOWN
...
```

As can be seen from the log output, both uplink interfaces ix0 and ix1 went DOWN while adding the VLAN. As a result, the LAGG went down too and all CARP addresses followed.

Is there anything that could be improved to minimize the downtime? I'd think that adding a VLAN should not cause a downtime at all.

**Comment by AdSchellevis** [comment]
@fraenki is this the latests version of OPNsense? I know there was a similar issue a long time ago, but some cards cause the same issue too.

**Comment by fraenki** [comment]
@AdSchellevis Sorry for that. 18.7.8 it is.

**Comment by AdSchellevis** [comment]
any hardware offloading enabled? "VLAN Hardware Filtering" should be set to "Leave default" for this to work without interruptions.

**Comment by AdSchellevis** [comment]
just checked on my vm, no interruptions there, I kind of expect settings in this case.

**Comment by fraenki** [comment]
@AdSchellevis Settings on the affected host:

![int_settings](https://user-images.githubusercontent.com/909706/49380717-85bc9200-f712-11e8-87c4-f7d41a6a0168.png)

**Comment by fichtner** [comment]
can you try to set VLAN HW filter to "leave default" + reboot

**Comment by fraenki** [comment]
Sure, will try.

**Comment by fraenki** [comment]
Disabling VLAN HW filter fixed the issue, a new VLAN could be added without any downtime. Thanks!

**Comment by fichtner** [comment]
4ba0fa679d it's the default for the 18.7.8 images coming this week. We missed this default configuration change for 18.7 unfortunately.
