### ISSUE TITLE
revise the /cf approach for embedded devices with limited write cycles

### ISSUE THREAD

**Issue by fichtner** [opnsense/core#3]
The general idea implemented previously is okay, but inconsistent. /conf may be a symlink, although /cf should really have a complete directory mirror, so each time we want to write we force the prefix /cf and be done with it. Might also involve renaming /cf to /rw for clarity. This approach works for normal installations, too. No reason to have an if else mess in the code. Feedback welcome! :)

**Comment by jschellevis** [comment]
As discussed we will remove /cf/conf (and /cf) in favor of /conf, no symlink any more.
