### ISSUE TITLE
importer: zfs listing could yield a description separated via whitespace

### ISSUE THREAD

**Issue by fichtner** [opnsense/core#3010]

**Comment by alexpro** [comment]
There is a quite simple solution using IFS variable, I just tested it with simple sh script:
```
#!/bin/sh

zpool import -aNf

ORIGINAL_IFS=${IFS}

IFS=$'\t'

zpool get -H cachefile | while read ZPOOL ZMORE; do
        if [ "$(mount | grep -w / | grep -c ${ZPOOL})" = "0" ]; then
            zpool export ${ZPOOL} >/dev/null 2>/dev/null
            echo "zfs/${ZPOOL}"
        fi
done

IFS=${ORIGINAL_IFS}
```
I have two non-root ZFS pools in my test system and one containing spaces in its name.
Output of zpool get -H cachefile:
```
root@fbsd11-zfs-test:~# zpool get -H cachefile
medved  cachefile       -       default
zfs pool with spaces    cachefile       -       default
zroot   cachefile       -       default
```
Output of script:
```
root@fbsd11-zfs-test:~# ./zt
zfs/medved
zfs/zfs pool with spaces
root@fbsd11-zfs-test:~#
```

**Comment by fichtner** [comment]
should we be supporting ZFS pools with spaces? I'm surprised this works... What I mean was list them in a more useful way:

```
zfs/pool1      Some type of description / Size
zfs/pool2      Some type of other description / Size
```

The reason is that there would be more help in scenarios where more than one ZFS pool exists so one knows which one to grab the configuration from.

**Comment by fichtner** [comment]
@alexpro FYIW, import works well with your changes... I tested this extensively 👍

**Comment by alexpro** [comment]
Size of the pool is quite difficult to determine, because pool may contain several physical drives or partitions with different sizes. I don't even know for now, how to do this better... Pool configuration must be determined first, and then it's need to calculate sizes of all pool members according to configuration.

**Comment by fichtner** [comment]
I'm leaving this as is, not the prettiest thing in the world, but it seems ZFS is not built for scripting... ;)
