### ISSUE TITLE
User import not working

### ISSUE THREAD

**Issue by ahaase-c4u** [opnsense/core#3012]
After update to OPNsense 18.7.8 the user import for ldap users does not work in Firefox 60.3.0. There is no popup or popup request. Even completely disabling popup blocker does not solve the issue.

Not sure, whether this is related to the bug, but opening the browser console and the clicking on import, there gets displayes the message, that an event is not defined. When using Chrome, all works fine.

**Comment by AdSchellevis** [comment]
@ahaase-c4u thanks, https://github.com/opnsense/core/commit/e17dc86235a51f962796d61f4e74d73c692f6d01 should fix the issue

**Comment by ahaase-c4u** [comment]
I can confirm, the patch fixes the issue. Thank you very much.
