### ISSUE TITLE
Tokenizer2 delimiter in UI - can't use Regex quantifiers because of comma

### ISSUE THREAD

**Issue by sammie-p** [opnsense/core#3013]
On the proxy ACLs page, I'm trying to add the following regex to blacklist:
192\.168\.[0-9]{1,3}\.[0-9]{1,3}

But the field keeps separating by comma.

Please provide an option to use a different delimiter or choose a delimiter that is never part of a regex expression.

**Comment by mimugmail** [comment]
The field doesn't support regex, just use 192.168.0.0/16 ...

**Comment by sammie-p** [comment]
The field is Blacklist on the Web Proxy -> Access Control List tab.
![capture](https://user-images.githubusercontent.com/19430483/49491505-8ab34a00-f8a8-11e8-8a2e-cd57861eb5eb.PNG)

**Comment by sammie-p** [comment]
The issue is we have internally hosted websites (eg http://192.168.0.1/) that we want to block for users of our 'guest' VLAN. We can firewall our internal network to block traffic from the guest VLAN, but when the guests are using the transparent proxy, this firewalling is bypassed.

**Comment by mimugmail** [comment]
Workaround would be to add a `no rdr` rule in front of the transparent proxy NAT.

**Comment by sammie-p** [comment]
Thanks, I will add a firewall rule as a workaround.

**Comment by AdSchellevis** [comment]
timeout (https://github.com/opnsense/core/blob/master/CONTRIBUTING.md)
