### ISSUE TITLE
Feature Request: List link status in interface assignment

### ISSUE THREAD

**Issue by mimugmail** [opnsense/core#3019]
See screenshot:

![image](https://user-images.githubusercontent.com/20438689/49581870-a0317e00-f953-11e8-85c4-9b8c61d84ccb.png)

One of these interfaces has a new link (co-worker plugged cable). 
Would it be possible to add the link status in the dropdown list? So I know which interface to configure/assign?

In Interfaces : Overview I can also check the link status, but only for already assigned interfaces. So for this problem it's only possible going to the CLI and check the carrier state via ifconfig.

Perhaps there's an easy solution for this?

Ideas?

**Comment by AdSchellevis** [comment]
link status sounds useful indeed.

**Comment by AdSchellevis** [comment]
this?
![image](https://user-images.githubusercontent.com/9783985/49586674-1dfc8600-f962-11e8-86e8-db43ee8a749b.png)

**Comment by mimugmail** [comment]
Looks nice .. perhaps the downlink a bit more red as with a high resolution green and orange is quite near :)
