### ISSUE TITLE
Unbound as forwarder only does not work / option ignored

### ISSUE THREAD

**Issue by Kimotu** [opnsense/core#3020]
In latest opnSense release 18.7.8, unbound ignores the option to work as forwarder only.

No matter whether ` Enable Forwarding Mode ` is checked or not, it always queries root servers. I also checked the config files in `/var/unbound` and with grep no forwarding option in config is found.

I have added system dns servers in ` System: Settings: General` that shall be used.

**Comment by fichtner** [comment]
To pinpoint we need the last know good release?

**Comment by fichtner** [comment]
I see what you're saying. Let me work on this, I think get_dns_servers() should be removed completely as it has side-effects. It's only used once really in the unbound code and dnsmasq does this more gracefully already (good comparison for forwarding mode).

**Comment by fichtner** [comment]
Can you try this patch? 5cf8b4f2e

    # opnsense-patch 5cf8b4f2e


Thanks,
Franco

**Comment by Kimotu** [comment]
I can try it on Monday.

Am Fr., 7. Dez. 2018, 13:33 hat Franco Fichtner <notifications@github.com>
geschrieben:

**Comment by fichtner** [comment]
@Kimotu not trying to rush you but if you can confirm today I can shortcut this to 18.7.9 for Wednesday :)

**Comment by Kimotu** [comment]
@fichtner Sorry for late answer, but I was ill.

I applied the patch and forwarders get added as expected. So your fix works.

**Comment by fichtner** [comment]
Thanks, will ship in 18.7.10. 18.7.9 is going out today so you will need to reapply the patch after update.

Hope you're feeling better!


Cheers,
Franco
