### ISSUE TITLE
OpenVPN nat firewall race

### ISSUE THREAD

**Issue by AdSchellevis** [opnsense/core#3023]
I don't have a proper solution for this yet, but in some cases when having portforwards from the OpenVPN net the filter  isn't loaded during boot. 

Caused by https://github.com/opnsense/core/blob/71043f1bb796fdc51444f8ad176e3546208054fe/src/opnsense/mvc/app/library/OPNsense/Firewall/ForwardRule.php#L62

The problem is that `openvpn:network` complains in these cases., I'm not sure if the issue was caused by the last change in this file or it has always been there, it could also be some race condition.

**Comment by fichtner** [comment]
Would try to remove () to see if the issue persists.

**Comment by AdSchellevis** [comment]
@fichtner there wasn't enough time todo so, maybe I can replicate the behaviour.
