### ISSUE TITLE
{} (empty Hash) is defined

### ISSUE THREAD

**Issue by fabianfrz** [opnsense/core#3028]
The return value [here](https://github.com/opnsense/core/blob/master/src/opnsense/service/modules/addons/template_helpers.py#L114) is defined in a template so the usual `xyz is defined` check does not work.

See https://github.com/opnsense/plugins/pull/1051/files#diff-679ee727c01829533c1fe26132e2ccdaR231 for a working workaround.

**Comment by AdSchellevis** [comment]
@fabianfrz your proposal is to drop `{} `and return None? or am I missing something?

**Comment by fabianfrz** [comment]
Maybe it works then but it would be a breaking change which I would not do in a minor release

**Comment by AdSchellevis** [comment]
I guess, the following construct should also (already) work in your situation:

`{%         if location.urlpattern %}`

**Comment by fabianfrz** [comment]
I can try it - it just needs to be a false value but the problem is that this affects maintainability as a contributor may not understand why there is a match to an arbitary field.

**Comment by AdSchellevis** [comment]
I'm not sure I understand, `getUUID()` returns an empty object, so a check for existence for any property would in this case always result in false.
