### ISSUE TITLE
firewall: logging for NAT rules

### ISSUE THREAD

**Issue by AdSchellevis** [opnsense/core#3033]
leftover from https://github.com/opnsense/core/issues/1494 see https://github.com/opnsense/core/commit/c6df560fa6133c781a6588e64a364c616903da08

**Comment by fichtner** [comment]
Thanks... wanted to talk about that when you have some time

**Comment by AdSchellevis** [comment]
found it while going through the diffs

**Comment by fichtner** [comment]
As per @sjorge we do not seem to support "nat" as well, although "rdr" already works:

![dzszqrzw0aeevfg jpg-large](https://user-images.githubusercontent.com/1915288/52773929-660fe700-303c-11e9-9638-20352786749f.jpeg)

![dzwgszcxcae_mhi jpg-large](https://user-images.githubusercontent.com/1915288/52773875-3f51b080-303c-11e9-996f-3e33f014ba33.jpeg)

It's probably best to assume "rdr" and "nat" are the same class (colour) of traffic.

**Comment by AdSchellevis** [comment]
@fichtner is there still work left for me here? it looks finished within the options available, or am I wrong?

**Comment by fichtner** [comment]
The label parsing is wrong, nat and rdr and the firewall block pass have sequential numbers that overlap...

**Comment by AdSchellevis** [comment]
ok, rdr/nat/... don't support labels, suppressing is no prblem, useful labels might be challenging

**Comment by fichtner** [comment]
ok, just something slightly more useful than XXX maybe then? :)

**Comment by AdSchellevis** [comment]
I have an idea, not sure if it works.

**Comment by AdSchellevis** [comment]
doesn't work, to provide meaningful descriptions you would need to reverse engineer the parsing logic of pfctl.... the contents of /tmp/rules.debug never add up ;(

**Comment by fichtner** [comment]
MAybe just a stub then such as "NAT rule" ?

**Comment by AdSchellevis** [comment]
yep, that will be it, together with a filter on the labels fetched from the rulest
