### ISSUE TITLE
Unable to install OPnsense on Dell R220

### ISSUE THREAD

**Issue by zhouska** [opnsense/core#3036]
I'm facing installer issues when attempting install onto Dell R220 with 32GB RAM. 

I've tried most recent images for USB and DVD, GPT and MBR versions, but the installer fails at various phases of 'cpdup' command:

FAILED with a return code of  1
 
There are no any meaningless logs I can see to decipher what is wrong with the installation.

**Comment by fichtner** [comment]
There is a log under /tmp/installer.log -- but if cpdup fails there's a bad write return from the harddisk. Could be bad wiring or hardware, driver compat issue.

Have you tried with the 19.1-BETA images? They have a more recent kernel...  https://forum.opnsense.org/index.php?topic=10135.0

**Comment by zhouska** [comment]
hm, tried it just now, the same problem.... Most recent debian installs onto the server without any issues... Getting scsi medium errors in the log - Error 5: Untertryable error, and then vm_fault.  I'm using the virtual media to mount the iso.

**Comment by fichtner** [comment]
Sorry, can't help with all hardware of 19.1 is not better in this regard.
