### ISSUE TITLE
Backup options for NextCloud

### ISSUE THREAD

**Issue by pazifi** [opnsense/core#3049]
Feature request:
Hello dear opnsense team

It would be very nice if you could set that the backups are either deleted automatically after a certain number or time span
and/or
that the backup is only written when changes are made.

Greetings
pazifi

**Comment by fabianfrz** [comment]
@pazifi nextcloud should be able to handle that itself:

![grafik](https://user-images.githubusercontent.com/3713914/50054649-80b10700-0144-11e9-8e28-fb33b8867ef9.png)

See this article how to configure it: https://docs.nextcloud.com/server/12/admin_manual/file_workflows/retention.html

**Comment by pazifi** [comment]
Thank you, bit i think this is not a good option because auto tagging of files has no simple option for folder or file name.
Only things like MIME type, file size, time, url, user agent, request time...

The only useful option is usergroup, that is okay if a user is only for backups. 

I can handle it.

**Comment by Alphakilo** [comment]
> The only useful option is usergroup, that is okay if a user is only for backups.

@pazifi I use the source IP address for that purpose. Works flawless:
![2018-12-29-190037_1920x1080_scrot](https://user-images.githubusercontent.com/8202374/50540980-94288d00-0b9c-11e9-9e3e-1f4acf515c3a.png)

**Comment by pazifi** [comment]
Yes, this is an option, also with an extra account for backups. (When the router and a data synchronization behind the same IP).

Thank you.

**Comment by abplfab** [comment]
I've created a bash script which I run daily in cron
`
#!/bin/bash
# Remove Files older 30d
/usr/bin/find /export/data-oc/oc-data/<nextcloud user>/files/ -name "*.xml" -type f -mtime +30 -exec rm -rf {} \; 2> /dev/null

# Rename : time to - (else Files don't sync in Windows)
for i in $(find /export/data-oc/oc-data/<nextcloud user>/files/ -name '*.xml' | grep ":") ; do echo $i; nn=$(echo $i | sed -e 's/:/-/g') ; echo $nn ; mv -i $i $nn ; done

# Rescan Folder for Nextcloud
/usr/local/bin/sudo -u www php /usr/local/www/nextcloud/occ files:scan <nextcloud user>

`

**Comment by fichtner** [comment]
timeout
