### ISSUE TITLE
Google drive backups do not work anymore

### ISSUE THREAD

**Issue by coaxial** [opnsense/core#3050]
Versions:
```
OPNsense 18.7.8-amd64
FreeBSD 11.1-RELEASE-p15
OpenSSL 1.0.2q 20 Nov 2018
```

Using the Google Drive option under System > Configuration > Backups, and testing the setup with the button in the UI results in a failure.

I also get crash reports once in a while that backing up to Drive failed. This used to work flawlessly.

**Comment by AdSchellevis** [comment]
Just tested locally, seems to work over here. 
It might help if you add the output of the report, there's not much to go on now.

**Comment by coaxial** [comment]
I don't know how to generate the report manually. When I test the setup with the button, all I'm getting is this message:

`The following input errors were detected:

    Saved settings, but remote backup failed.`

But there is no mention of a report. The error reports pop up once in a while on the dashboard, I don't know how to generate them manually.

**Comment by coaxial** [comment]
There it is:

```
PHP Fatal error:  Uncaught Google_IO_Exception: Operation timed out after 100000 milliseconds with 0 bytes received in /usr/local/opnsense/contrib/google-api-php-client/Google/IO/Curl.php:115
Stack trace:
#0 /usr/local/opnsense/contrib/google-api-php-client/Google/IO/Abstract.php(136): Google_IO_Curl->executeRequest(Object(Google_Http_Request))
#1 /usr/local/opnsense/contrib/google-api-php-client/Google/Http/REST.php(60): Google_IO_Abstract->makeRequest(Object(Google_Http_Request))
#2 /usr/local/opnsense/contrib/google-api-php-client/Google/Task/Runner.php(174): Google_Http_REST::doExecute(Object(Google_Client), Object(Google_Http_Request))
#3 /usr/local/opnsense/contrib/google-api-php-client/Google/Http/REST.php(46): Google_Task_Runner->run()
#4 /usr/local/opnsense/contrib/google-api-php-client/Google/Client.php(590): Google_Http_REST::execute(Object(Google_Client), Object(Google_Http_Request))
#5 /usr/local/opnsense/contrib/google-api-php-client/Google/Service/Resource.php(231): Google_Client->execute(Object(Google_Http_Requ in /usr/local/opnsense/contrib/google-api-php-client/Google/IO/Curl.php on line 115
```

```
User-Agent Mozilla/5.0 (X11; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/60.0
FreeBSD 11.1-RELEASE-p17  bf74bfa8a63(stable/18.7) amd64
OPNsense 18.7.9 068523882
Plugins os-acme-client-1.18 os-dyndns-1.10_1 os-node_exporter-1.0 os-theme-rebellion-1.8.1 
Time Mon, 17 Dec 2018 09:10:55 -0500
OpenSSL 1.0.2q  20 Nov 2018
PHP 7.1.25
```

**Comment by AdSchellevis** [comment]
the error isn't nice, we should probably catch and log these, but it's basically saying it can't reach google. could be dns related, or some gateway issue.

**Comment by coaxial** [comment]
I cheked on the gdrive and it seems the config eventually gets saved. I can't understand why the test button in the GUI would report a failure then?

**Comment by AdSchellevis** [comment]
unstable connection maybe

**Comment by coaxial** [comment]
It could be, but seems unlikely. My connection is very stable and pings don't get interrupted while the gdrive is being tested. Would like to help pinpoint the issue, if you have an ideas of things to try I'd be happy to report back with the results.

**Comment by NoLooseEnds** [comment]
I have the same issue. It started after an upgrade a few versions back. I have reported in the error via the built-in bug system.

**Comment by calvinbui** [comment]
Been getting the same as well

**Comment by leobossmann** [comment]
Same here, ran fine for the first four or five backups, then kept crashing

**Comment by leobossmann** [comment]
I just created a new p12 key and tried again, it seems to works now. Will check tomorrow. I rebooted the firewall several times, could that be the issue?

**Comment by ontaris** [comment]
Same issue here with exactly same errors. Tried multiple times. Re-creating a p12 key or service account did not help.

In the google console however I see accesses to google drive API result in HTTP 200 responses, so no errors. No backup files are created nevertheless.

**Comment by AdSchellevis** [comment]
There is an api update for google https://github.com/googleapis/google-api-php-client/releases, but it seem to require a lot of work to implement. 

We might consider to do so at a later moment in time, although most issues seem to be a result of connectivity issues to the google servers (dns, routing, etc).

**Comment by fichtner** [comment]
timeout
