### ISSUE TITLE
OpenVPN "Client Specific Overrides" not updating in 18.7.9

### ISSUE THREAD

**Issue by Gamebase32** [opnsense/core#3053]
I have added a new firewall on a remote site with OPNsense 18.7.9 and upgraded the existing firewall to 18.7.9. Now the "disable" directive for "Client Specific Overrides" does not seem to have effect anymore. I enabled a specific user to not be able to connect with the option "Connection blocking". Then changed it to be allowed to connect again, but the logs on the client state:
`Dec 18 11:14:27 | openvpn[37724]: AUTH: Received control message: AUTH_FAILED`
On the server I get:
`Dec 18 11:14:25 | openvpn[87724]: opnsense-02/xxx.xxx.xxx.5:49612 MULTI: client has been rejected due to 'disable' directive`
I have restarted both the OpenVPN client service on the second firewall, and restarted the OpenVPN server service on the first firewall. Both firewalls have also been restarted.

**Comment by AdSchellevis** [comment]
What version have you upgraded from? and what does the rest of the log on the server look like?

**Comment by Gamebase32** [comment]
> What version have you upgraded from?

`Dec 17 21:30:44 | pkg-static: opnsense upgraded: 18.7.8 -> 18.7.9`
> and what does the rest of the log on the server look like?

**Server:**
Date	Message
Dec 18 11:40:00	openvpn[87724]: opnsense-02/xxx.xxx.xxx.5:31970 Connection reset, restarting [0]
Dec 18 11:39:59	openvpn[87724]: opnsense-02/xxx.xxx.xxx.5:31970 MULTI: client has been rejected due to 'disable' directive
Dec 18 11:39:59	openvpn[87724]: opnsense-02/xxx.xxx.xxx.5:31970 MULTI_sva: pool returned IPv4=10.40.4.10, IPv6=xxxx:xxxx:xxxx:4::1001
Dec 18 11:39:59	openvpn[87724]: xxx.xxx.xxx.5:31970 [opnsense-02] Peer Connection Initiated with [AF_INET]xxx.xxx.xxx.5:31970
Dec 18 11:39:59	openvpn: user 'opnsense-02' authenticated using 'AD <redacted>'
Dec 18 11:39:58	openvpn[87724]: xxx.xxx.xxx.5:31970 peer info: IV_TCPNL=1
Dec 18 11:39:58	openvpn[87724]: xxx.xxx.xxx.5:31970 peer info: IV_COMP_STUBv2=1
Dec 18 11:39:58	openvpn[87724]: xxx.xxx.xxx.5:31970 peer info: IV_COMP_STUB=1
Dec 18 11:39:58	openvpn[87724]: xxx.xxx.xxx.5:31970 peer info: IV_LZO=1
Dec 18 11:39:58	openvpn[87724]: xxx.xxx.xxx.5:31970 peer info: IV_LZ4v2=1
Dec 18 11:39:58	openvpn[87724]: xxx.xxx.xxx.5:31970 peer info: IV_LZ4=1
Dec 18 11:39:58	openvpn[87724]: xxx.xxx.xxx.5:31970 peer info: IV_NCP=2
Dec 18 11:39:58	openvpn[87724]: xxx.xxx.xxx.5:31970 peer info: IV_PROTO=2
Dec 18 11:39:58	openvpn[87724]: xxx.xxx.xxx.5:31970 peer info: IV_PLAT=freebsd
Dec 18 11:39:58	openvpn[87724]: xxx.xxx.xxx.5:31970 peer info: IV_VER=2.4.6
Dec 18 11:39:57	openvpn[87724]: TCP connection established with [AF_INET]xxx.xxx.xxx.5:31970
Dec 18 11:39:57	openvpn[87724]: pfsense/xxx.xxx.xxx.5:44660 Connection reset, restarting [0]

**Client:**
Date	Message
Dec 18 11:40:00	openvpn[64162]: SIGTERM[soft,auth-failure] received, process exiting
Dec 18 11:40:00	openvpn[64162]: AUTH: Received control message: AUTH_FAILED
Dec 18 11:39:59	openvpn[64162]: [opnsense-01.<domainname>] Peer Connection Initiated with [AF_INET]xxx.xxx.xxx.160:1196
Dec 18 11:39:58	openvpn[64162]: WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
Dec 18 11:39:58	openvpn[64162]: TCPv4_CLIENT link remote: [AF_INET]xxx.xxx.xxx.160:1196
Dec 18 11:39:58	openvpn[64162]: TCPv4_CLIENT link local: (not bound)
Dec 18 11:39:58	openvpn[64162]: TCP connection established with [AF_INET]xxx.xxx.xxx.160:1196
Dec 18 11:39:57	openvpn[64162]: Attempting to establish TCP connection with [AF_INET]xxx.xxx.xxx.160:1196 [nonblock]
Dec 18 11:39:57	openvpn[64162]: TCP/UDP: Preserving recently used remote address: [AF_INET]xxx.xxx.xxx.160:1196
Dec 18 11:39:57	openvpn[64162]: NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
Dec 18 11:39:57	openvpn[64162]: WARNING: No server certificate verification method has been enabled. See http://openvpn.net/howto.html#mitm for more info.
Dec 18 11:39:57	openvpn[63953]: library versions: OpenSSL 1.0.2q 20 Nov 2018, LZO 2.10
Dec 18 11:39:57	openvpn[63953]: OpenVPN 2.4.6 amd64-portbld-freebsd11.1 [SSL (OpenSSL)] [LZO] [LZ4] [MH/RECVDA] [AEAD] built on Dec 11 2018
Dec 18 11:39:57	openvpn[63953]: WARNING: file '/var/etc/openvpn/client1.up' is group or others accessible
Dec 18 11:39:57	openvpn[42777]: SIGTERM[hard,] received, process exiting
Dec 18 11:39:57	openvpn[42777]: /usr/local/etc/inc/plugins.inc.d/openvpn/ovpn-linkdown ovpnc1 1500 1554 10.40.4.6 10.40.4.5 init
Dec 18 11:39:57	openvpn[42777]: delete_route_ipv6(xxxx:xxxx:xxxx::/48)
Dec 18 11:39:57	openvpn[42777]: event_wait : Interrupted system call (code=4)

**Comment by AdSchellevis** [comment]
I don't think much has changed between those two versions in this regard.
You could check the contents of `/var/etc/openvpn-csc/` (`find /var/etc/openvpn-csc/`), if there's a profile stuck there. The interesting thing is that it doesn't seem to think there's a csc configured at the moment as the authentication should output about the location:

https://github.com/opnsense/core/blob/1cd0c08082b6bc28fe67982dfdd6bfa194e4f80e/src/etc/inc/plugins.inc.d/openvpn/auth-user.php#L132

**Comment by Gamebase32** [comment]
And indeed there was a profile stuck there. After removing it the user was able to create a connection.
```
xxx@opnsense-01:~ % find /var/etc/openvpn-csc/
/var/etc/openvpn-csc/
/var/etc/openvpn-csc/1
/var/etc/openvpn-csc/2
/var/etc/openvpn-csc/4
/var/etc/openvpn-csc/4/opnsense-02
xxx@opnsense-01:~ % cat /var/etc/openvpn-csc/4/opnsense-02
disable
-- output cut here --
```

**Comment by AdSchellevis** [comment]
If there's no new csc configured, it won't touch the one already there.  I'm not sure we should do anything else.

**Comment by AdSchellevis** [comment]
We can probably close this issue, if we see other people having difficulties with old abandoned csc fles we might consider providing a cleanup button.
