### ISSUE TITLE
User Import button for LDAP won't show up

### ISSUE THREAD

**Issue by Papy-Bretzel** [opnsense/core#3057]
Hi.
First of all, thank your for this great solution.
I encountered this bug for now couple of weeks on both Firefox and Chrome.

I installed and upgraded the lastest version of OpnSense (18.7.9). I was successfully able to establish my Microsoft Active Directory connection through the **System>Access>Servers** interface. I tested it and I can get the fields for my user with the **System>Access>Test** page.

However, I can't get the "Import User" button to show up, as described in your official LDAP support [documentation](https://wiki.opnsense.org/manual/how-tos/user-ldap.html). I tried to restart my OpnSense instance (Windows style), multiple web browsers, but wasn't successful.

![image](https://user-images.githubusercontent.com/32303253/50226529-b3a50600-03a3-11e9-94e1-10c2c3824c1d.png)

It's actually bit weird as I see some issue closing up speaking about this exact same behaviour but only on Firefox. And the best part is that it is marked as solved in the 18.7.9 [patch note](https://forum.opnsense.org/index.php?action=profile;area=showposts;sa=topics;u=10). What am I missing ?

Thank you for your time

**Comment by fichtner** [comment]
Hi,

You will need to configure you LDAP/AD as a System Administration Authentication Server. The revised docs are here:

https://github.com/opnsense/docs/blob/080b6626f4af6f139271cd90358c9ed26df535b7/source/manual/users.rst#authentication-services


Cheers,
Franco

**Comment by Papy-Bretzel** [comment]
Hi again. 

I locked myself out 🥇 
It's working. Thank you

**Comment by fichtner** [comment]
> I locked myself out

I do hope not in the worst possible way.


Cheers,
Franco
