### ISSUE TITLE
Attempting to delete in-use alias causes crash, trapping needs improving.

### ISSUE THREAD

**Issue by stilez** [opnsense/core#3058]
I attempted to delete a host alias that was in use, and got this error:

OPNsense\Base\UserException: Cannot delete alias. Currently in use by 
[filter.rule.8/destination.address] [RULE NAME/DESCRIP]
[filter.rule.9/destination.address] [RULE NAME/DESCRIP] in /usr/local/opnsense/mvc/app/controllers/OPNsense/Firewall/Api/AliasController.php:138
Stack trace:
#0 [internal function]: OPNsense\Firewall\Api\AliasController->delItemAction('4a424d80-1e69-4...')
#1 [internal function]: Phalcon\Dispatcher->callActionMethod(Object(OPNsense\Firewall\Api\AliasController), 'delItemAction', Array)
#2 [internal function]: Phalcon\Dispatcher->dispatch()
#3 /usr/local/opnsense/www/api.php(26): Phalcon\Mvc\Application->handle()
#4 {main}

Deleting an alias which the user hasn't remembered is still in use, should result in a simple error, not a PHP crash, needs trapping.

**Comment by AdSchellevis** [comment]
it's intended, user exceptions are catched properly in the gui.
![image](https://user-images.githubusercontent.com/9783985/50283099-2ae6a280-0455-11e9-8f3b-74f1a228253a.png)

**Comment by AdSchellevis** [comment]
Where did you get this message? and what version are you using?

**Comment by AdSchellevis** [comment]
https://github.com/opnsense/core/commit/ab3b5b58de8d613c6454a4bbd882225ecf948371
