### ISSUE TITLE
Attempt to update an IP alias gives "bad IP" error

### ISSUE THREAD

**Issue by stilez** [opnsense/core#3059]
Steps to replicate:

1. Define a host alias, with a single IPv4 address, and save it.
2. Open it again to edit it, place the cursor AFTER the saved IP address, then type a space, then a second IPv4 address, and save it.
3.  When I did this, it said "bad alias" for the 2nd ewntry and refused to save it.

Now, do step 2 again, this time puttingthe cursor at the START of the field and entering the 2nd IP BEFORE the first IP, not after it. This time, for me anyway, it reported the SAVED (old) IP as an error. So it's allowing the 1st and blocking the 2nd onward.

Finally, create a new host alias, and this time enter 2 IPv4 addresses at the same time, instead of one, then saving, then adding another. This time it allows it.

Hoping that this is a reproducible error!

**Comment by AdSchellevis** [comment]
I don't think we have an error called "bad alias"....
