### ISSUE TITLE
configd: files generated from templates do not have trailing newlines

### ISSUE THREAD

**Issue by fichtner** [opnsense/core#306]
Similar issue/fix here: https://github.com/saltstack/salt/commit/bdf5d0dc01230d684b861f5bbeded992a474dd8c

**Comment by AdSchellevis** [comment]
Do you have an example? If the last tag is a template expression, the newline is cut on purpose. (trim_blocks, see http://jinja.pocoo.org/docs/dev/templates/ )

**Comment by fichtner** [comment]
Noticed this before, behaviour is consistent...

    root@os:~ # cat /etc/rc.conf.d/squid 
    squid_enable=YES
    squid_opnsense_bootup_run="/usr/local/opnsense/scripts/proxy/setup.sh"root@os:~ #

**Comment by fichtner** [comment]
Note that "trailing newlines" means "the very last newline in the template" here. Sorry for the ambiguity.

**Comment by AdSchellevis** [comment]
strange, same cat on my end:

root@OPNsense:~/core # cat /etc/rc.conf.d/squid
squid_enable=YES
squid_opnsense_bootup_run="/usr/local/opnsense/scripts/proxy/setup.sh"
root@OPNsense:~/core # 

what does src/opnsense/service/templates/OPNsense/Proxy/rc.conf.d look like on your end? does it contain the trailing newline?

**Comment by fichtner** [comment]
No, it has the same defect. That was my reason for submitting this today. :)

**Comment by AdSchellevis** [comment]
Now I'm confused.... the template is missing the end of line on your end and the output also doesn't have the line? My version does have the end of line in both.
If the end of line is not in the source, it shouldn't be in the target as well.. that's how it's supposed to work.

**Comment by fichtner** [comment]
Sorry, I debugged using suricata file, then I mixed up the template question you had. The templates all have newlines as per cleanfile script, the actual files generated don't.

**Comment by AdSchellevis** [comment]
Ok, no problem. Only thing weird in here is why my install doesn't show the same behaviour. I will try the same on another box as well, maybe I can reproduce it somewhere. This shouldn't go wrong if the last tag isn't a template tag.

**Comment by AdSchellevis** [comment]
Fixed in https://github.com/opnsense/core/commit/d8a81cda7b0213e581fd6fe7c68231aa6fdae6d2
