### ISSUE TITLE
Firewall: Aliases - cannot paste hostnames

### ISSUE THREAD

**Issue by mrPsycho** [opnsense/core#3060]
OPNsense 18.7.9-amd64

when i'm adding hosts by hand - everything works
when i'm adding it with copy&paste (even from plaintext) - error shows: 

```
Entry "test.com " is not a valid hostname or IP address.
```

**Comment by fichtner** [comment]
Values are comma-separated, no whitespace allowed

**Comment by mrPsycho** [comment]
yep. you opened my eyes. 


so, it could be feature request for far far future

**Comment by fichtner** [comment]
we have this discussion from time to time, but manipulating user values to accommodate for passing validation is not the best approach in the world. we found one instance where a password given was whitespace trimmed and stored... not ideal by any standard.

**Comment by fichtner** [comment]
nevertheless, thanks for the report! :)
