### ISSUE TITLE
OpenVPN Queue overflow

### ISSUE THREAD

**Issue by hvalencia89** [opnsense/core#3066]
When restart service OpenVPN and have 60 user or  more.
The queue OpenVPN is overflow for connection client.

![openvpn](https://user-images.githubusercontent.com/46072913/50377065-11bc2e00-05dc-11e9-9ba8-f4f5d1298f13.png)

**Comment by AdSchellevis** [comment]
To find the correct culprit for your message, it might be worth to read https://blog.tyk.nu/blog/fun-with-freebsd-listen-queue-overflow/ 

The logging is somewhat confusing, since it misses the corresponding pid.

**Comment by hvalencia89** [comment]
Hello AdSchellevis,
I am find with  only process unknown for queue overflow
root ?? 13103 9 stream /var/run/configd.socket


root@Elektra:~ # cat /var/log/system.log
Dec 23 07:55:59 Elektra opnsense: /usr/local/etc/rc.sshd: Started creating your SSH keys. SSH startup is being delayed a wee bit.
Dec 23 07:55:59 Elektra opnsense: /usr/local/etc/rc.sshd: Completed creating your SSH keys. SSH will now be started.
Dec 23 07:55:59 Elektra sshd[20519]: Server listening on ::1 port 22.
Dec 23 07:55:59 Elektra sshd[20519]: Server listening on 127.0.0.1 port 22.
Dec 23 07:55:59 Elektra sshd[20519]: Server listening on 192.168.89.2 port 22.
Dec 23 08:06:34 Elektra opnsense: user 'root' authenticated successfully
Dec 23 08:06:34 Elektra sshd[43081]: Accepted keyboard-interactive/pam for root from 172.16.48.26 port 58655 ssh2
Dec 23 08:10:48 Elektra kernel: sonewconn: pcb 0xfffff80105f0ecb0: Listen queue overflow: 2 already in queue awaiting acceptance (51 occurrences)
Dec 23 08:11:48 Elektra kernel: sonewconn: pcb 0xfffff80105f0ecb0: Listen queue overflow: 2 already in queue awaiting acceptance (568 occurrences)
Dec 23 08:12:49 Elektra kernel: sonewconn: pcb 0xfffff80105f0ecb0: Listen queue overflow: 2 already in queue awaiting acceptance (476 occurrences)
Dec 23 08:13:49 Elektra kernel: sonewconn: pcb 0xfffff80105f0ecb0: Listen queue overflow: 2 already in queue awaiting acceptance (312 occurrences)
Dec 23 08:14:49 Elektra kernel: sonewconn: pcb 0xfffff80105f0ecb0: Listen queue overflow: 2 already in queue awaiting acceptance (134 occurrences)
Dec 23 08:21:18 Elektra kernel: sonewconn: pcb 0xfffff80105f0ecb0: Listen queue overflow: 2 already in queue awaiting acceptance (13 occurrences)
Dec 23 08:22:18 Elektra kernel: sonewconn: pcb 0xfffff80105f0ecb0: Listen queue overflow: 2 already in queue awaiting acceptance (554 occurrences)
Dec 23 08:23:18 Elektra kernel: sonewconn: pcb 0xfffff80105f0ecb0: Listen queue overflow: 2 already in queue awaiting acceptance (502 occurrences)
Dec 23 08:24:18 Elektra kernel: sonewconn: pcb 0xfffff80105f0ecb0: Listen queue overflow: 2 already in queue awaiting acceptance (304 occurrences)
Dec 23 08:25:19 Elektra kernel: sonewconn: pcb 0xfffff80105f0ecb0: Listen queue overflow: 2 already in queue awaiting acceptance (116 occurrences)
Dec 23 08:26:44 Elektra kernel: sonewconn: pcb 0xfffff80105f0ecb0: Listen queue overflow: 2 already in queue awaiting acceptance (10 occurrences)
Dec 23 08:27:44 Elektra kernel: sonewconn: pcb 0xfffff80105f0ecb0: Listen queue overflow: 2 already in queue awaiting acceptance (6911 occurrences)
Dec 23 08:28:44 Elektra kernel: sonewconn: pcb 0xfffff80105f0ecb0: Listen queue overflow: 2 already in queue awaiting acceptance (2637 occurrences)
root@Elektra:~ #
root@Elektra:~ #  netstat -Aan | grep fffff80105
fffff80105e36410 tcp4     238      0 192.168.89.2.1194  187.135.22.83.5524 ESTABLISHED
fffff80105f48410 tcp4       0      0 192.168.89.2.1194  189.180.210.149.34 LAST_ACK
fffff80105fc5820 tcp4       0   2880 192.168.89.2.1194  187.148.171.91.527 LAST_ACK
fffff801056da820 tcp4       0      0 192.168.89.2.1194  170.78.191.93.5943 LAST_ACK
fffff80105716910 udp6       0      0 *.123              *.*
fffff80105705e10 stream      0      0                0                0                0                0
fffff8010568f960 stream      0      0                0 fffff80006d651e0                0                0
fffff80006d651e0 stream      0      0                0 fffff8010568f960                0                0
fffff80006f1b1e0 stream      0      0 fffff80105656760                0                0                0 /var/etc/openvpn/server1.sock
fffff801057062d0 stream      0      0                0                0                0                0 /var/run/configd.socket
fffff801056bd960 dgram       0      0                0 fffff80128b9d2d0                0 fffff80006d972d0
fffff80128b9d2d0 dgram       0      0 fffff8013ab97000                0 fffff801056bd960                0 /var/run/logpriv
fffff80006f023c0 dgram       0      0                0                0                0 fffff801056bb870
fffff801056bc5a0 dgram       0      0                0                0                0 fffff80006b46b40
fffff801056bd870 dgram       0      0                0                0                0 fffff80006d994b0
fffff80006d994b0 dgram       0      0                0                0                0 fffff801056bd960
root@Elektra:~ # sockstat -l | grep /var/etc/openvpn/server1.sock
root     openvpn    27696 7  stream /var/etc/openvpn/server1.sock
root@Elektra:~ # sockstat -l | grep /var/run/configd.socket
root     awk        13160 5  stream /var/run/configd.socket
root     awk        13160 9  stream /var/run/configd.socket
root     pfctl      13103 5  stream /var/run/configd.socket
root     ??         13103 9  stream /var/run/configd.socket
root     sh         12758 5  stream /var/run/configd.socket
root     sh         12758 9  stream /var/run/configd.socket
root     php        12499 5  stream /var/run/configd.socket
root     php        12499 9  stream /var/run/configd.socket
root     sh         9157  5  stream /var/run/configd.socket
root     sh         9157  9  stream /var/run/configd.socket
root     cron       15662 5  stream /var/run/configd.socket
root     cron       15662 7  stream /var/run/configd.socket
root     sh         43754 5  stream /var/run/configd.socket
root     sh         43754 9  stream /var/run/configd.socket
root     lighttpd   40341 5  stream /var/run/configd.socket
root     lighttpd   40341 9  stream /var/run/configd.socket
root     openvpn    27696 5  stream /var/run/configd.socket
root     openvpn    27696 9  stream /var/run/configd.socket
root     python2.7  410   5  stream /var/run/configd.socket

**Comment by AdSchellevis** [comment]
I don't see `fffff80105f0ecb0` anywhere in the netstat output maybe it's related to something else (currently not active) on the machine.

**Comment by hvalencia89** [comment]
after the overflow the references are lost and show 
root ?? 13103 9 stream /var/run/configd.socket
What is the other procedure for detect problem?

**Comment by AdSchellevis** [comment]
I don't expect configd is related to your issue.
Within community support time I can't really help you out further.

**Comment by hvalencia89** [comment]
the process involved in the problem is
unix 0/0/1	/var/etc/openvpn/server1.sock
and the queue the socket the system.
And where can I contact pay support.

**Comment by AdSchellevis** [comment]
The strange thing is that the pcb doesn't match the socket from openvpn, which suggest the problem might be elsewhere.

Our commercial support options are available at https://www.deciso.com/business-support/
