### ISSUE TITLE
Outbound NAT for local services

### ISSUE THREAD

**Issue by mrbarletta** [opnsense/core#3068]
Outbound NAT is not being applied to packets leaving the WAN (far gateway).

If I SSH into the firewall  I can ping/download and update correctly, everything works as expected.

BUT Letsencrypt acme service  is failing and tcpdump is showing that packets are not being NAT translated ONLY for this service.

This is a far gateway so NAT is always needed as WAN <-> ISP uses a private net. 

I can't find a setting to make this work, considering that everything else is working as expected I am requesting your help.

thanks for the great opnsense :)

**Comment by fichtner** [comment]
Hi @mrbarletta,

Outbound NAT only works when the incoming traffic is marked for NAT. Since local traffic originates not from external interfaces it's not possible to set an outbound NAT in this way. Ideally, the service should use the NAT IP address to talk on the external side so it doesn't need NAT.


Cheers,
Franco

**Comment by mrbarletta** [comment]
Thanks @fichtner for your prompt reply.

Do you recommend doing a patch to the letsencrypt plugin?

Maybe detect if far-gateway setting is set and enable a setting to define the interface/IP to use for outgoing traffic?

**Comment by fichtner** [comment]
I'm unsure where the problem lies. It sounds like this is due to a complication in your WAN setup?

**Comment by mrbarletta** [comment]
to be honest its the only customer that has that kind of service (WAN using a private IP and having a /28 public address space ) is that very uncommon?

**Comment by mimugmail** [comment]
This is really uncommon. It would mean Squid would also not work as there is no bind option for outgoing connections integrated (in UI).

**Comment by mrbarletta** [comment]
thanks - I will have to ask the ISP to change that, but I will loose 1 public IP from the available range.

**Comment by mimugmail** [comment]
You will loose 3, network address, broadcast and Gateway of provider

**Comment by fabianfrz** [comment]
@mimugmail in best case you loose only two in a /31 network in IPv4 - also known as peer to peer. The problem is, that not all operating systems support it.
