### ISSUE TITLE
FW groups are not kept in sync in the rule’s source/destination fields

### ISSUE THREAD

**Issue by fbruetting** [opnsense/core#3076]
```
OPNsense 18.7.9-amd64
FreeBSD 11.1-RELEASE-p17
OpenSSL 1.0.2q 20 Nov 2018
```

When I alter my firewall group from say `Intranet` to `IntranetA`, the interface is changed accordingly in the affected groups, but the source (and I assume also the destination) field is not kept up-to-date (see screen shot below).

When this webpage is loaded and the fields match *correctly*, I recognized that first, the text field with the content `Intranet` is shown, and then gets immediately converted into a sole drop-down-menu-button (without the text field being displayed anymore). So it seems that OPNsense doesn’t save the group ID but instead the group name, which then get’s compared, matched and converted to the correct group (and then being displayed as a selection in the drop-down-menu instead of pure text). This seems to be the root of the problem here.

Additionally, changing the group name doesn’t cause the firewall rules to get reloaded (which would be correct, if the described bug wouldn’t be the case), so I first recognized this bug when I rebooted my router after months and thus had to debug all my rules, because I wasn’t able to infer what caused my network outage.

![bildschirmfoto von 2018-12-29 03-14-27](https://user-images.githubusercontent.com/10520767/50532332-318dad80-0b18-11e9-9dc1-db4692849745.png)

**Comment by AdSchellevis** [comment]
source and destination aren't related to the selected interface, you can match traffic coming from another interface as well. It's intended behaviour.

**Comment by fbruetting** [comment]
Yeah this might be the case for when I enter the name by pure text. But when I in contrast select it from a drop-down menu, I expect the group to be kept in sync with the actual group.

**Comment by AdSchellevis** [comment]
it's not a group, you're selecting an interface and source/target networks....

**Comment by AdSchellevis** [comment]
ok, you renamed the interface group expecting that it would seek and replace the occurrences in the configuration, which it indeed doesn't do. 

Maybe we could check (some of the) address fields as well on rename, since it also does that for the interface fields, but I'm doubting a bit an "interface group" network matches what you think it will match. 
Have you tried the functionality and confirmed it matches the correct traffic (from both physical networks)?

**Comment by fbruetting** [comment]
Search-and-replace is quite be error-prone. (What happens if you try to rename a group to an already existing group name? Or if you have something entered in plain text, which should stay the same?)

What about implementing internal reference IDs for all automatically created drop-down-items instead? So when a group gets created, it could get a unique ID like `$int_group_0`. All rules then could internally use that ID and on the user-facing side, this ID just needs to get replaced by its name. Renaming then wouldn’t be a problem at all, consistency would be insured and robustness increased.

**Comment by AdSchellevis** [comment]
It's legacy code, our new style code uses uuid's internally (although this wouldn't necessarily be error prone, since you know where to look and what it looks like, and source and target are unique...).
 
You haven't answered my question (does your rule match the correct traffic), but if you would like to prepare a pull request for a manageable change, just let us know.

We know what an ideal world looks like, in reality there are always constraints to take into account.

**Comment by fbruetting** [comment]
As soon as I rename the interface from `Intranet` to `IntranetA` without fixing the rule right after, I get connection problems. When I then fix the source network in the rule, everything works fine again. So I assume that the rule works (I currently have some other issues, thus not 100% sure).

**Comment by AdSchellevis** [comment]
Can you let us know if the rule matches the expected traffic? like I said, I'm not sure (and would setup things differently)

If it works, we should probably rename these items, otherwise we might need to exclude these kind of networks from the selection list.

**Comment by AdSchellevis** [comment]
No problem, I'm not sure what you're trying to reach, but aliases might help you out here (for the source/destination part), interface groups to match traffic on multiple interfaces itself are a useful tool to match on more interfaces at once.

**Comment by fbruetting** [comment]
I created two distinct subnets for LAN and WIFI (hence two interfaces). Via the interface group I tried to summarize the rules which should affect both subnets equally.

**Comment by fichtner** [comment]
timeout
