### ISSUE TITLE
Interface groups: Problems with inactive members

### ISSUE THREAD

**Issue by fbruetting** [opnsense/core#3082]
```
OPNsense 18.7.9-amd64
FreeBSD 11.1-RELEASE-p17
OpenSSL 1.0.2q 20 Nov 2018
```

When I create an interface group consisting of two interfaces and then deactivate both of them (like for test purposes), I cannot alter the interface group anymore. When I try to edit such a group, OPNsense recognizes that none of the interfaces is available anymore and thus it doesn’t let me save. I therefore have to enable all members temporarily, for being able to rename the group.

Small UX issue… maybe groups could be enabled to also handle inactive interfaces?

**Comment by AdSchellevis** [comment]
It should be safe to drop the "is enabled" constraint, groups can be created without actual interfaces in them and the interface setup links the group to the real interface. I'll change the edit form.

**Comment by fichtner** [comment]
Lands in 18.7.10 :)

**Comment by fbruetting** [comment]
Nice! Thank you!
