### ISSUE TITLE
VLAN assignments GUI issue.

### ISSUE THREAD

**Issue by nivek1612** [opnsense/core#3085]
After upgrading it 19.1.b I noticed that the GUI is incorrectly presenting the VLAN assignments

I have to VLANS

![screenshot 2018-12-31 at 10 47 43](https://user-images.githubusercontent.com/23481092/50557884-92201480-0ce9-11e9-81bf-e16640b88099.png)

Here are the Assignments at 18.7.9

![screenshot 2018-12-31 at 02 21 20](https://user-images.githubusercontent.com/23481092/50557822-26d64280-0ce9-11e9-80b7-0c5598930d87.png)

But at 19.1 VLAN840 is being shown as on vlan832

![screenshot 2018-12-29 at 17 30 24](https://user-images.githubusercontent.com/23481092/50557852-5f761c00-0ce9-11e9-9277-3216865664c2.png)

Also when trying to select a VLAN it is impossible to tell which one to use as both appear to be the same VLAN. 

![screenshot 2018-12-31 at 10 50 22](https://user-images.githubusercontent.com/23481092/50557918-fcd15000-0ce9-11e9-9bd9-033351a81bb4.png)

NOTE the VLANS are still functioning correctly and ifconfig from the shell shows them set up correctly

**Comment by AdSchellevis** [comment]
can you check the `<interfaces>` section of your config.xml? I don't see anything similar on my end (and the upgrade itself doesn't change the configuration).

**Comment by nivek1612** [comment]
Config.xml looks to be accurate from what I can see hence why I think its just a GUI presentation issue

**Comment by AdSchellevis** [comment]
can you post the `interfaces` and `vlan` sections here? (without ip addresses)

**Comment by nivek1612** [comment]
Sure here it is I have two WAN's and two LAN's 
WAN is on igb0 but with two VLANs 832 and 840 to allow for Orange France FTTP for internet and TV respectively
WAN on opt4 is my failover WAN to SFR FTTP service. No VLANs required

LAN on igb2 is standard LAN for all my PC etc.
TVLAN on opt3 is the LAN on which only my TV decoders sit (avoids me needing to do igmp snooping to stop LAN flooding.

`<interfaces>
    <wan>
      <if>igb0_vlan832</if>
      <descr/>
      <enable>1</enable>
      <spoofmac>30:7c:b2:ff:ff:ff</spoofmac>
      <blockpriv>1</blockpriv>
      <blockbogons>1</blockbogons>
      <ipaddr>dhcp</ipaddr>
      <dhcphostname/>
      <alias-address/>
      <alias-subnet>32</alias-subnet>
      <dhcprejectfrom>192.168.x.x</dhcprejectfrom>
      <adv_dhcp_pt_timeout/>
      <adv_dhcp_pt_retry/>
      <adv_dhcp_pt_select_timeout/>
      <adv_dhcp_pt_reboot/>
      <adv_dhcp_pt_backoff_cutoff/>
      <adv_dhcp_pt_initial_interval/>
      <adv_dhcp_pt_values>SavedCfg</adv_dhcp_pt_values>
      <adv_dhcp_send_options>dhcp-class-identifier "sagem", user-class "+FSVDSL_livebox.Internet.softathome.Livebox3"</adv_dhcp_send_options>
      <adv_dhcp_request_options>subnet-mask, broadcast-address, dhcp-lease-time, dhcp-renewal-time, dhcp-rebinding-time, domain-search, routers, domain-name-servers</adv_dhcp_request_options>
      <adv_dhcp_required_options/>
      <adv_dhcp_option_modifiers>vlan-parent "igb0", vlan-id 832, vlan-pcp 6</adv_dhcp_option_modifiers>
      <adv_dhcp_config_advanced>advanced</adv_dhcp_config_advanced>
      <adv_dhcp_config_file_override/>
      <adv_dhcp_config_file_override_path/>
      <ipaddrv6>dhcp6</ipaddrv6>
      <dhcp6-ia-pd-len>0</dhcp6-ia-pd-len>
      <dhcp6sendsolicit>1</dhcp6sendsolicit>
      <dhcp6norelease>1</dhcp6norelease>
      <dhcp6vlanprio>6</dhcp6vlanprio>
      <adv_dhcp6_interface_statement_send_options>ia-pd 0, raw-option 6 00:0b:00:11:00:17:00:18, raw-option 15 00:2b:46:53:56:44:53:4c:5f:6c:69:76:65:62:6f:78:2e:49:6e:74:65:72:6e:65:74:2e:73:6f:66:74:61:74:68:6f:6d:65:2e:6c:69:76:65:62:6f:78:33, raw-option 16 00:00:04:0e:00:05:73:61:67:65:6d</adv_dhcp6_interface_statement_send_options>
      <adv_dhcp6_interface_statement_request_options/>
      <adv_dhcp6_interface_statement_information_only_enable/>
      <adv_dhcp6_interface_statement_script/>
      <adv_dhcp6_id_assoc_statement_address_enable/>
      <adv_dhcp6_id_assoc_statement_address/>
      <adv_dhcp6_id_assoc_statement_address_id/>
      <adv_dhcp6_id_assoc_statement_address_pltime/>
      <adv_dhcp6_id_assoc_statement_address_vltime/>
      <adv_dhcp6_id_assoc_statement_prefix_enable>on</adv_dhcp6_id_assoc_statement_prefix_enable>
      <adv_dhcp6_id_assoc_statement_prefix/>
      <adv_dhcp6_id_assoc_statement_prefix_id>0</adv_dhcp6_id_assoc_statement_prefix_id>
      <adv_dhcp6_id_assoc_statement_prefix_pltime/>
      <adv_dhcp6_id_assoc_statement_prefix_vltime/>
      <adv_dhcp6_prefix_interface_statement_sla_len>8</adv_dhcp6_prefix_interface_statement_sla_len>
      <adv_dhcp6_authentication_statement_authname/>
      <adv_dhcp6_authentication_statement_protocol/>
      <adv_dhcp6_authentication_statement_algorithm/>
      <adv_dhcp6_authentication_statement_rdm/>
      <adv_dhcp6_key_info_statement_keyname/>
      <adv_dhcp6_key_info_statement_realm/>
      <adv_dhcp6_key_info_statement_keyid/>
      <adv_dhcp6_key_info_statement_secret/>
      <adv_dhcp6_key_info_statement_expire/>
      <adv_dhcp6_config_advanced>advanced</adv_dhcp6_config_advanced>
      <adv_dhcp6_config_file_override/>
      <adv_dhcp6_config_file_override_path/>
    </wan>
    <lan>
      <if>igb1</if>
      <descr>LAN</descr>
      <enable>1</enable>
      <spoofmac/>
      <ipaddr>192.168.x.x</ipaddr>
      <subnet>24</subnet>
      <ipaddrv6>track6</ipaddrv6>
      <track6-interface>wan</track6-interface>
      <track6-prefix-id>0</track6-prefix-id>
    </lan>
    <openvpn>
      <internal_dynamic>1</internal_dynamic>
      <enable>1</enable>
      <if>openvpn</if>
      <descr>OpenVPN</descr>
      <type>group</type>
      <virtual>1</virtual>
    </openvpn>
    <opt2>
      <if>igb0_vlan840</if>
      <descr>VLAN840</descr>
      <enable>1</enable>
      <spoofmac/>
      <ipaddr>192.168.x.x</ipaddr>
      <subnet>24</subnet>
    </opt2>
    <opt3>
      <if>igb2</if>
      <descr>TVLAN</descr>
      <enable>1</enable>
      <spoofmac/>
      <ipaddr>192.168.x.x</ipaddr>
      <subnet>24</subnet>
    </opt3>
    <opt4>
      <if>igb3</if>
      <descr>SFR</descr>
      <enable>1</enable>
      <spoofmac>40:62:31:ff:ff:ff</spoofmac>
      <blockpriv>1</blockpriv>
      <blockbogons>1</blockbogons>
      <ipaddr>dhcp</ipaddr>
      <dhcphostname/>
      <alias-address/>
      <alias-subnet>32</alias-subnet>
      <dhcprejectfrom>192.168.x.x</dhcprejectfrom>
      <adv_dhcp_pt_timeout/>
      <adv_dhcp_pt_retry/>
      <adv_dhcp_pt_select_timeout/>
      <adv_dhcp_pt_reboot/>
      <adv_dhcp_pt_backoff_cutoff/>
      <adv_dhcp_pt_initial_interval/>
      <adv_dhcp_pt_values>SavedCfg</adv_dhcp_pt_values>
      <adv_dhcp_send_options/>
      <adv_dhcp_request_options/>
      <adv_dhcp_required_options/>
      <adv_dhcp_option_modifiers/>
      <adv_dhcp_config_advanced/>
      <adv_dhcp_config_file_override/>
      <adv_dhcp_config_file_override_path/>
    </opt4>
  </interfaces>


  <vlans>
    <vlan>
      <if>igb0</if>
      <tag>832</tag>
      <pcp>0</pcp>
      <descr>Orange FTTP VLAN</descr>
      <vlanif>igb0_vlan832</vlanif>
    </vlan>
    <vlan>
      <if>igb0</if>
      <tag>840</tag>
      <pcp>5</pcp>
      <descr>TV VLAN 840</descr>
      <vlanif>igb0_vlan840</vlanif>
    </vlan>
  </vlans>`

**Comment by nivek1612** [comment]
Google Chrome Version 71.0.3578.98 (Official Build) (64-bit)on Mac OS

**Comment by AdSchellevis** [comment]
Can you try another browser as well, although I'm also using Chrome, I can't seem to replicate your issue.

**Comment by nivek1612** [comment]
Same in Safari and Firefox. 
Here is a weird thing though if I add a new VLAN 

![screenshot 2019-01-02 at 09 00 20](https://user-images.githubusercontent.com/23481092/50586896-747eb680-0e73-11e9-9042-eb8e0f2a35fc.png)

The interface assignments now look like this. VLAN 840 now shows twice but the new VLAN 838 does not 

![screenshot 2019-01-02 at 09 00 07](https://user-images.githubusercontent.com/23481092/50586923-95dfa280-0e73-11e9-91fd-481d2ce4c7ed.png)

**Comment by nivek1612** [comment]
@AdSchellevis did you test on a 19.1 built from a 19.1 image or a system upgraded from the GUI - 18.7.9 - 19.1.b

I have just checked another system that was upgraded an it showing a similar problem but this time my pppoe0 interface is bing listed a bridge 

<img width="1360" alt="screenshot 2019-01-02 at 10 40 25" src="https://user-images.githubusercontent.com/23481092/50588910-2de18a00-0e7c-11e9-80a9-678bc188c474.png">

<img width="1395" alt="screenshot 2019-01-02 at 10 43 18" src="https://user-images.githubusercontent.com/23481092/50588914-31751100-0e7c-11e9-9136-9114a0f53189.png">

**Comment by marjohn56** [comment]
Ad - I'm testing and seeing the same issues. On my test system I deleted the Bridge a couple of days ago for testing something else. I can create the bridge again but it does not show up in the drop downs to allow me to assign it to LAN.

**Comment by marjohn56** [comment]
note - I have just done a code-core and upgrade too,

**Comment by marjohn56** [comment]
Might be a cache thing... just asking Kev to try that. Seems mine is OK now.,

**Comment by AdSchellevis** [comment]
the reference assignment was intentional, but we can add the status field to `interfaces[]` as well, I'll create a patch later today

**Comment by nivek1612** [comment]
Martins change also fixed the issue for me

**Comment by marjohn56** [comment]
Without that change I do not see Bridge listed, I see the openvpn interface listed twice.

**Comment by marjohn56** [comment]
That appears to work fine. Kev... do you concur?

**Comment by nivek1612** [comment]
Yes confirmed works for me as well

**Comment by AdSchellevis** [comment]
thanks @nivek1612 @marjohn56 for confirming.
