### ISSUE TITLE
OPNsense 15.7.7_3-amd64 - DHCPv6 on WAN Interface Blocked by Firewall

### ISSUE THREAD

**Issue by cbasolutions** [opnsense/core#309]
With DHCPv6 enabled on the WAN Interface, the firewall is blocking the traffic with the ISP server. The WAN Interface is unable to obtain a DHCPv6 IP. 
 
OPNsense 15.7.7_3-amd64	
FreeBSD 10.1-RELEASE-p16	
LibreSSL 2.2.1

Additionally - and perhaps for a different issue - this article describes a basic ruleset for an IPv6 firewall of which certain elements may be worth considering:

http://pivotallabs.com/configuring-freebsd-9-1-as-an-ipv6-dhcp-client/

**Comment by fichtner** [comment]
I'm unsure which traffic is missing. I use DHCPv6 on the WAN and can obtain an IPv6 address. The rules generated on WAN for DHCPv6 are:

    pass in quick on $WAN proto udp from fe80::/10 port = 546 to fe80::/10 port = 546  label "allow dhcpv6 client in WAN"
    pass in quick on $WAN proto udp from any port = 547 to any port = 546 label "allow dhcpv6 client in WAN"
    pass out quick on $WAN proto udp from any port = 546 to any port = 547 label "allow dhcpv6 client out WAN"

**Comment by cbasolutions** [comment]
I don't have those rules on my web view. Are they behind the scenes? 

I am getting this in my logs when filtering for blocks:

Act	Time		If	  Source						Destination					Proto
X Aug 9 12:34:17	WAN  [fe80::xxx:xxxx:xxxx:xxxx]:547	  [fe80::xxx:xxxx:xxxx:xxxx]:546	UDP
X Aug 9 12:34:17	WAN  [fe80::xxx:xxxx:xxxx:xxxx]:547	  [fe80::xxx:xxxx:xxxx:xxxx]:546	UDP
X Aug 9 12:32:18	WAN  [fe80::xxx:xxxx:xxxx:xxxx]:547	  [fe80::xxx:xxxx:xxxx:xxxx]:546	UDP
X Aug 9 12:32:18	WAN  [fe80::xxx:xxxx:xxxx:xxxx]:547	  [fe80::xxx:xxxx:xxxx:xxxx]:546	UDP

The destination matches the link local for my WAN interface.

**Comment by fichtner** [comment]
The are from /tmp/rules.debug -- there ought to be a block with a header "# allow our DHCPv6 client out to the WAN"

or something else is overriding your traffic. Which rule causes this? Click "x" to reveal this.

**Comment by cbasolutions** [comment]
The rule that triggered this action is:

@40 block drop in log quick on em1 from <bogonsv6:0> to any label "block bogon IPv6 networks from WAN"

**Comment by fichtner** [comment]
Is /usr/local/etc/bogonsv6 empty? If not, does it have a line beginning with a "fe80:" entry?

**Comment by fichtner** [comment]
I could reproduce with an empty file. That's really funny as the "default" file shipped with the system has been empty forever. To fix, run this on the command line:

    # /usr/local/etc/rc.update_bogons 1

I'll put a few initial values into /usr/local/etc/bogonsv6.sample to avoid this problem in the future.

Let me know if this helped or not.

**Comment by fichtner** [comment]
There was more to it apparently after having had a little push in the right direction. Traffic is now passed. Closing in time for 15.7.8.
