### ISSUE TITLE
OpenVPN Client Export doesn't work

### ISSUE THREAD

**Issue by clebig** [opnsense/core#3090]
Dear OPNSense team,

I'm trying to use OpenVPN Client Export but I can't choose the server for which I want to generate the client.

The drop-down list is empty. 

![screenshot_20190102_163153](https://user-images.githubusercontent.com/17143757/50599061-2686a480-0ead-11e9-9429-b325ac7d942c.png)
![screenshot_20190102_163223](https://user-images.githubusercontent.com/17143757/50599062-2686a480-0ead-11e9-9e8b-2e1b4cb579da.png)

Happy new year !

**Comment by mimugmail** [comment]
You are sure server type is remote access and you have choosen an authentication backend?

**Comment by AdSchellevis** [comment]
The development version has a new (and simplified) module for this, which will be released with 19.1 later this month.

**Comment by clebig** [comment]
> You are sure server type is remote access and you have choosen an authentication backend?

You are right, I was using Peer To Peer (SSL/TLS) mode...  

Now it works, thank you.

What changes between Peer To Peer and Remote Access modes in OPNSense's backend exept you can use an authentication backend ?
