### ISSUE TITLE
unbound: Align *-cache-slabs settings with num-threads

### ISSUE THREAD

**Issue by jpawlowski** [opnsense/core#3092]
The [Unbound documentation](https://www.nlnetlabs.nl/documentation/unbound/howto-optimise/) says

> Set `*-slabs` to a power of 2 close to the `num-threads` value. Do this for `msg-cache-slabs`, `rrset-cache-slabs`, `infra-cache-slabs` and `key-cache-slabs`.

However, on my machine I can see the settings do not follow that rule:

``````
num-threads: 4
msg-cache-slabs: 4
rrset-cache-slabs: 4
infra-cache-slabs: 4
key-cache-slabs: 4
``````

According to the official documentation, all `*-cache-slabs` settings shall be 8 in that case, not 4.
This shall be corrected in the code.

**Comment by sunbearc22** [comment]
Am I correct to understand the following concerning optimization:

1. When Unbound is to be used as an Authoritative, Validating, Recursive Caching DNS, all attributes with `*-slabs` should have a value of `num-threads` to a power of 2?
2. When Unbond is forwarding via DNS over TLS, recursive caching DNS, TCP port 853 ENCRYPTED,  all attributes with `*-slabs` should use the set default values?
