### ISSUE TITLE
DHCP Leases Columns Sortable?

### ISSUE THREAD

**Issue by unipacket1** [opnsense/core#3095]
On the DHCP leases page, the column headings are clickable (cursor does not change but can still click on them.)  The page refreshes like it tries to sort the columns but nothing changes.  Not sure if the columns are suppose to be sort-able or not.

**Comment by soder10** [comment]
I have to agree, its a little bit confusing that these columns in the DHCP  lease page are not formatted to look like  actual headers of a table. However if I click on for example the "status" column, it does sort the lines as per status: first inactive entries and last the active lines. Hiwever I could not reverse the order: active entries at the top and inactive entries at thw bottom. So it seems sorting works only half-way.

**Comment by MichaelDeciso** [comment]
I will port this page to use MVC and Bootgrid, which should also take care of this.

**Comment by fichtner** [comment]
timeout

**Comment by mimugmail** [comment]
Wasn't there a PR from @MichaelDeciso regarding MVC rewrite? :)

**Comment by fichtner** [comment]
yes, it was rejected

**Comment by soder10** [comment]
Guys, just for me to understand: this one is not going to work then ever?

**Comment by mimugmail** [comment]
IMHO it was rejected because it had no use case .. but this would be one :)

**Comment by fichtner** [comment]
When I click on the MAC column it loads https://10.0.0.1/status_dhcp_leases.php?all=0&order=mac and the table is ordered after reload.

**Comment by AdSchellevis** [comment]
It was rejected because there was too much work needed to make it functional and within code quality checks, nobody is working on this now, but if people plan to work on it they can always opt for reopening the ticket.....

**Comment by mimugmail** [comment]
Ah, ok, just had this PR in mind when I saw this closed one in mailbox.

**Comment by AdSchellevis** [comment]
No problem, we're just not planning to work on this at the moment. Other priorities
