### ISSUE TITLE
[Feature request] CARP addresses in rules SRC/DST drop down list

### ISSUE THREAD

**Issue by clebig** [opnsense/core#3098]
Dear OPNSense team again,

Would it be possible to have the CARP IPs visible with the NIC they belongs to in the source/destination drop down list in the "rules" form ? So we could select directly the CARP IP without having to remember them ?.

**Comment by mimugmail** [comment]
@clebig You can add the nic name yourself in the description field which would be displayed in braces in firewall rules.

**Comment by clebig** [comment]
I have checked, my CARP VIF already had a description but they are not shown in the interface selection drop-down list, when I'm trying to add a firewall rule.

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository, 
please read https://github.com/opnsense/core/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue, 
just let us know, so we can reopen the issue and assign an owner to it.
