### ISSUE TITLE
Typo in actions_system.conf

### ISSUE THREAD

**Issue by Epoxide** [opnsense/core#3101]
There's a typo in /usr/local/opnsense/service/conf/actions.d/actions_interface.conf

[remote.backup]
command:/usr/local/opnsense/scripts/remote_backup.php
**oarameters:**
type:script
message:Performing remote backup
description:Remote backup

**Comment by fichtner** [comment]
@Epoxide indeed, thanks! not an operational issue but better fixed than not. :)
