### ISSUE TITLE
Feature Request: Alias Table completion / GUI persistence

### ISSUE THREAD

**Issue by mahescho** [opnsense/core#3113]
Nice to have completion for alias lists. Thanks!

It would be nice to have completion for all IPs (v4&v6) and nets/prefixes known to the firewall (by interfaces and virtual IPs) for completion too.

It would also be nice to have GUI persistence in the alias table so sort order and lines to be displayed are persistent over sessions.

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository, 
please read https://github.com/opnsense/core/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue, 
just let us know, so we can reopen the issue and assign an owner to it.
