### ISSUE TITLE
Virtual IPs

### ISSUE THREAD

**Issue by mahescho** [opnsense/core#3114]
I don't understand the placement and name of so called "Virtual IPs". I had to ask at the forum to find out how to add IP aliases to interfaces. This statement itself explains where this IMHO belongs to. Why is is this called "Virtual IP" and why is is placed in the "Firewall" section. For me this is completely unintuitive.

When you look at FreeBSD you add IP aliases by "ifconfig" and get them displayed by "ifconfig". They do not reside in /etc/pf.conf or get displayed by "pfctl". I would expect to be able to add IPs to interfaces in a list for IPv4 and IPv6.

**Comment by theq86** [comment]
It also seems that source-code-like it would be possible to add an IPv6 alias.
However, if I want to add one, I am offered a max of 32 bit.
The select box does indeed HAVE 128 bits but all options above 32 are HIDDEN
Why? Can't understand.

**Comment by mimugmail** [comment]
Insert a v6 address and click the dropdown, it'll allow up to 128 then

**Comment by theq86** [comment]
Cool, that worked. However, not very intuitive. Thanks

**Comment by mimugmail** [comment]
Indeed, but there's already a duplicate issue for it in the works. Would you mind closing this one? THanks

**Comment by theq86** [comment]
I can't, I'm not the issue creator.

**Comment by fichtner** [comment]
Which issue number? Will close in exchange for issue number. ;)

**Comment by mimugmail** [comment]
Yes, close. I'll check Docs and add If not there (v6)

**Comment by AdSchellevis** [comment]
@mimugmail thanks!
