### ISSUE TITLE
Feature Request: Traffic Widget

### ISSUE THREAD

**Issue by mahescho** [opnsense/core#3115]
It would be nice to be able to choose wich interfaces is displayed in the traffic widget. Currently I've 17 (18 with the currently unused IPSEC) and only 4 are of real interest. I know that I can disable the graph by clicking at the interface. But I want to be able to remove the texts too because I will get more interfaces an the widget does not grow. There is nearly no space left for the graphs.

![trafficgraph](https://user-images.githubusercontent.com/5101589/50853704-4d4c4b80-1383-11e9-9160-45012ea36329.png)

**Comment by mahescho** [comment]
It gets more and more useless ...
![Auswahl_158](https://user-images.githubusercontent.com/5101589/55273898-b2a04080-52d1-11e9-8e79-4cca4c857f17.png)

**Comment by mimugmail** [comment]
In such environments you need more powerful tools than on device monitoring, dont you think?

**Comment by mahescho** [comment]
Point me to where to start and I will try to fix it.

**Comment by mahescho** [comment]
> In such environments you need more powerful tools than on device monitoring, dont you think?

I think the traffic widget should provide an overview. Displaying each and every VLAN does not make any sense.

**Comment by fabianfrz** [comment]
You are probably looking for:

* https://github.com/opnsense/core/blob/master/src/www/widgets/widgets/traffic_graphs.widget.php#L172
* https://github.com/opnsense/core/blob/master/src/www/widgets/widgets/traffic_graphs.widget.php#L182

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository, 
please read https://github.com/opnsense/core/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue, 
just let us know, so we can reopen the issue and assign an owner to it.

**Comment by fukawi2** [comment]
I too would like this feature. In my case, my internet is provided via a PPP session, so I end up with 2 interfaces showing essentially the same details: the physical link to the modem, as well as the PPP session. Since the PPP session transits via the physical modem interface, the traffic is shown twice:

![image](https://user-images.githubusercontent.com/139959/88510014-83b0f080-d025-11ea-86c9-a34c00991ed5.png)

Side note: why is IPsec displayed even when IPsec is not configured?
