### ISSUE TITLE
Groups after user add are not corrent

### ISSUE THREAD

**Issue by sjorge** [opnsense/core#312]
After a fresh installed I added a user:
![screenshot](http://i.imgur.com/ySASfAg.png)
Notice //root// is in **admins** and **all**, but //sjorge// is only in **admins**.

![screenshot](http://i.imgur.com/2fHcijb.png)
But the groups pages lists 2 users for All, as I suspect is correct as sjorge seems to be part of that also.

**Comment by AdSchellevis** [comment]
It seems to be an issue in the default config, the "all" group is a bit odd... you shouldn't be able to add users to it. (but all users are a virtual member of "all" :) )
I  have removed it from our default config template, but as we're not creating new iso images at the 
moment it won't make it automatically into new installs. 

(you can remove root from the all group manually if you like, the gui doesn't allow you to do that, but in or out functionally won't make a difference)
