### ISSUE TITLE
VLAN assignment to WLAN parent interface issue

### ISSUE THREAD

**Issue by BPtLNfxZWo** [opnsense/core#3120]
Assigning an VLAN-ID to an WLAN parent interface e.g ath0_wlan1 results in a crash with the following notification:

> opnsense: /usr/local/etc/rc.filter_configure: New alert found: There were error(s) loading the rules: /tmp/rules.debug:97: interface name too long - The line in question reads [97]: scrub on ath0_wlanX_vlanXX all

OPNsense 18.7.10-amd64
FreeBSD 11.1-RELEASE-p18
OpenSSL 1.0.2q 20 Nov 2018

Steps to reproduce:
1) Interfaces: Wireless: Devices -> Add an Wireless interface, will be automatically named ath0_wlanX
2) Interfaces: Other Types: VLAN -> Assign VLAN ID to that Interface, will be named as ath0_wlanX_vlanXX

results in mentioned error

**Comment by fichtner** [comment]
Hi, thanks for the report. Interface names are 15 characters plus terminating zero so this is hitting a brick wall... VLAN notation could be changed, but will require a bit of dedicated work and QA time.

**Comment by BPtLNfxZWo** [comment]
Thanks for the answer. I'll switch to an external VLAN capable AP soon which is anyway recommended.

**Comment by bewue** [comment]
> 
> 
> Hi, thanks for the report. Interface names are 15 characters plus terminating zero so this is hitting a brick wall... VLAN notation could be changed, but will require a bit of dedicated work and QA time.

A quick solution would be to limit the character length in the input field?

General: The warnings in the upper right corner can easily be overlooked. A red icon at this point for example would be helpful.

**Comment by fichtner** [comment]
Tracked via #3222
