### ISSUE TITLE
[Posssible DOS] Unbound crash on ethernet device

### ISSUE THREAD

**Issue by lhorace** [opnsense/core#3122]
Hello,

This raised alarms for me reading this thread https://forum.opnsense.org/index.php?topic=10958.new;topicseen#new. A unprivileged process can crash ''driver' in 'freebsb'?

**Comment by fichtner** [comment]
Unlikely a driver "crash" as in "panic". I'm grasping at straws because interface code didn't change in 18.7.9 -> 18.7.10 but there seems to be a latent issue with some mildly related parts. It probably makes sense once we find it but for now it's unclear.

**Comment by lhorace** [comment]
Alright, my gist about Freebsb, it seems ancient and fragile compared to Linux from reading the forums and ticket issues. Although, I haven't ran into issues myself, knock on wood.

**Comment by fichtner** [comment]
You see, people only report what doesn't work when it doesn't work for whatever reason. It's complex networking world and no hardware or software is perfect. :)

**Comment by lukeb2e** [comment]
I encountered a similar issue with my unbound.
The unbound crashed with a segmentation fault in random time intervals. The logs didn't specify anything else.

After some trial and error I think it is related to the fact that I used libressl instead of openssl and dns over tls.
