### ISSUE TITLE
system: static/MVC hybrid model array vivification issue

### ISSUE THREAD

**Issue by fichtner** [opnsense/core#3123]
via: https://forum.opnsense.org/index.php?topic=10932.0

**Comment by AdSchellevis** [comment]
This looks related (or inflicted) by https://github.com/opnsense/core/issues/3024, feel free to assign me if this is the case.

**Comment by fichtner** [comment]
It goes back a while longer with a rework in inc/ code and that static code has no real iterator that is free of side effects. I think that merging static code and new models is not the way to go anymore although it looked nice to avoid migrations. It just creates bugs further down the road. :(

**Comment by AdSchellevis** [comment]
I’m afraid you’re right, it looked simple at first, but maybe complicated later on. In this case we’re stuck in this situation, but it’s likely fixable. I’ll take a look at it when I can.

**Comment by fichtner** [comment]
Maybe could drop invalid data from the model on migrations? It would fix itself on updates then...

The issue that caused this is: https://github.com/opnsense/core/blob/f6aaaa0b957e87703c6b04a2b8a51ed55e019ce7/src/etc/inc/util.inc#L1200

Damage is done so adding protection here won't be a good solution. :/

```
config[8336]: Model OPNsense\Routes\Route can't be saved, skip ( Phalcon\Validation\Exception: [OPNsense\Routes\Route:route.51dc1e9b-6f9d-487f-b05a-ae2ff624040a.network] Specify a valid network matching the gateways ip protocol. [OPNsense\Routes\Route:route.51dc1e9b-6f9d-487f-b05a-ae2ff624040a.gateway] Specify a valid gateway from the list matching the networks ip protocol. [OPNsense\Routes\Route:route.51dc1e9b-6f9d-487f-b05a-ae2ff624040a.network] Specify a valid network matching the gateways ip protocol. [OPNsense\Routes\Route:route.51dc1e9b-6f9d-487f-b05a-ae2ff624040a.gateway] Specify a valid gateway from the list matching the networks ip protocol. in /usr/local/opnsense/mvc/app/models/OPNsense/Base/BaseModel.php:538 Stack trace: #0 /usr/local/opnsense/mvc/app/models/OPNsense/Base/BaseModel.php(645): OPNsense\Base\BaseModel->serializeToConfig() #1 /usr/local/opnsense/mvc/script/run_migrations.php(56): OPNsense\Base\BaseModel->runMigrations() #2 {main} )
```

**Comment by AdSchellevis** [comment]
Dropping data has consequences too, I’ll have to look into it. The risk I see now is when a software update invalidates your model, you might loose connectivity in the worst case.
Let me het back on this, it should be possible to edit the illegal entry, which would make the issue a bit better, although I’m not sure what’s needed to fix that yet.

**Comment by christianuhlmann** [comment]
I have the same error in version:
OPNsense 18.7.10-amd64
FreeBSD 11.1-RELEASE-p18
OpenSSL 1.0.2q 20 Nov 2018
actual stable from website

**Comment by fichtner** [comment]
Yup, edit /conf/config.xml and remove this block:

```
  <staticroutes>
    <route/>
  </staticroutes>
```

**Comment by christianuhlmann** [comment]
@fichtner thanks for the info, I have already done this as mentioned in https://forum.opnsense.org/index.php?topic=828.0
