### ISSUE TITLE
Dashboard: Monit Widget 6 Columns pagination view problem

### ISSUE THREAD

**Issue by opnsenseuser** [opnsense/core#3126]
![6columns_monit_widget](https://user-images.githubusercontent.com/34602360/51083209-6142d500-1716-11e9-9de0-1d37dfee7dc7.jpg)

fixed should look like this:
![fixed](https://user-images.githubusercontent.com/34602360/51083214-6d2e9700-1716-11e9-88ba-44d158c4c059.jpg)

**Comment by fabianfrz** [comment]
this is a dangerous css option but probably does what you expect (white-space: no-wrap):
https://www.w3schools.com/cssref/playit.asp?filename=playcss_white-space&preval=nowrap

**Comment by opnsenseuser** [comment]
@fabianfrz maybe it would be even better to take away the pagination and replace it with a scrollbar, if the list is longer than .... whatever!!

**Comment by fbrendel** [comment]
Yes, a scrollbar would be better than the pagination.
But that requires a fixed widget height. How high should it be?
@AdSchellevis can we set it within the css of the theme?

**Comment by AdSchellevis** [comment]
@fbrendel it would probably be best to start with a class added in the widget itself, so the theme can overwrite it if needed. I know it's suboptimal, but custom theme's might render odd defaults otherwise.

**Comment by MichaelDeciso** [comment]
It looks like this has been fixed (at least on my dashboard) by #3147 and this can be closed.

**Comment by fichtner** [comment]
Indeed, thanks for the heads-up.
