### ISSUE TITLE
Default gateway lost on CARP master after failback on HA cluster setup with single public IP

### ISSUE THREAD

**Issue by snum** [opnsense/core#3128]
I have a high availability cluster (let's call them fw1 and fw2) setup with a single public IP as a CARP VIP in order to preserve public IPs in my /29 block. The setup is working fine, even when failing over to fw2 via CARP maintenance mode or unplugging WAN cable on fw1. The issue is that when fw1 resumes master via turning off maintenance mode or plugging in WAN cable on fw1, it no longer has a default gateway under routes. I have to either manually add the route (route add default A.B.C.170) or reboot fw1 to bring back the default route.

Here's my configuration…

**fw1**
Version: OPNsense 18.7.10-amd64

_LAN interface_
Block private networks: unchecked
Block bogon networks: unchecked
IPv4 static address: 10.0.10.101/24
IPv4 upstream gateway: auto-detect

_WAN interface_
Block private networks: unchecked
Block bogon networks: checked
IPv4 static address: 10.0.99.101/29
IPv4 upstream gateway: auto-detect

_Sync interface_
Block private networks: unchecked
Block bogon networks: unchecked
IPv4 static address: 10.0.90.101/24
IPv4 upstream gateway: auto-detect

_Virtual IPs_
LAN VIP
Mode: CARP
Interface: LAN
Address: 10.0.10.100/24
Gateway:
VHID: 101
Advbase: 1
Advskew: 0

WAN VIP
Mode: CARP
Interface: WAN
Address: A.B.C.170/29
Gateway:
VHID: 109
Advbase: 1
Advskew: 0

**fw2**
Version: OPNsense 18.7.10-amd64

_LAN interface_
Block private networks: unchecked
Block bogon networks: unchecked
IPv4 static address: 10.0.10.102/24
IPv4 upstream gateway: auto-detect

_WAN interface_
Block private networks: unchecked
Block bogon networks: checked
IPv4 static address: 10.0.99.102/29
IPv4 upstream gateway: auto-detect

_Sync interface_
Block private networks: unchecked
Block bogon networks: unchecked
IPv4 static address: 10.0.90.102/24
IPv4 upstream gateway: auto-detect

_Virtual IPs_
LAN VIP
Mode: CARP
Interface: LAN
Address: 10.0.10.100/24
Gateway:
VHID: 101
Advbase: 1
Advskew: 100

WAN VIP
Mode: CARP
Interface: WAN
Address: A.B.C.170/29
Gateway:
VHID: 109
Advbase: 1
Advskew: 100

**Both firewalls**
_VLANs_
LAN: 10
Sync: 90
WAN: 99

_Gateways_
Manual gateway created: A.B.C.169
Default gateway: checked
Far gateway: checked
Disable gateway monitoring: unchecked
Mark gateway as down: unchecked

_Aliases_
LAN_CARP
Host: 10.0.10.100

WAN_CARP
Host: A.B.C.170

_NAT_
Manual outbound NAT: checked

LAN rule
Interface: WAN
TCP/IP: IPv4
Protocol: any
Source address: 10.0.10.0/24
Translation: A.B.C.170 (WAN_CARP)

This bug was also experienced in pfSense ([#8465](
https://redmine.pfsense.org/issues/8465)), but has recently been resolved.

**Comment by mimugmail** [comment]
If you use real IPs from your /29 as system IPs everything works fine?

**Comment by snum** [comment]
Correct, the default gateway is not lost on CARP master after failback when using public IPs on the WAN interfaces. My system has since been upgraded to the following since the original post, but still experiencing this issue throughout the various releases:

OPNsense 19.1.7-amd64
FreeBSD 11.2-RELEASE-p8-HBSD

**Comment by RamazanKara** [comment]
I can confirm the exact same issue on my side. Near similar setup. Gateway seems to just disappear when setting the firewall to maintenance mode. Simply turning the gateway on and off again on the wan port of the master fixes this for me. Weird Bug.

**Comment by fichtner** [comment]
Is this still the case on 19.7.x ? The gateway code was rewritten considerably.

**Comment by fichtner** [comment]
Lots of changes leading up to 19.7.4 and no feedback so I will close this now.

**Comment by kenshin33** [comment]
Hi, sorry for the necromancy.
 
I can confirm the same problem (it bit really hard this morning).
Transitioning from  BACKUP to MASTER no problems at all,  MASTER -> BACKUP the default gw is lost  (no default entry in netstat -rn).  In the UI (System->GW->Single), the gateway shows as enabled/active, disabling it and enabling it solve the problem until the next time. 

I'm on the latest version (19.7.9_1)

**Comment by maj0rmil4d** [comment]
same issue over here 👍

**Comment by maj0rmil4d** [comment]
well we solved the problem by this way , first create a script to check if the default route is still exists or no then if does not just add it :) 

I added a cronjob for this though

fixgw.sh : 

HOSTNAME="$(hostname)"

if ! [ $(route -n show 0.0.0.0 | grep gateway | cut -d ":" -f 2 | cut -d " " -f 2) == "10.10.10.1" ]; then route add -net 0.0.0.0/0 10.10.10.1 ; fi

[fixgw.sh.txt](https://github.com/opnsense/core/files/5329887/fixgw.sh.txt)
![fixgw-pf](https://user-images.githubusercontent.com/46486478/95128144-dc0f1780-0765-11eb-97a3-b454212db71e.png)

**Comment by bbtaeuber** [comment]
Hi everybody!

This problem still occurs in version 21.1.5 (again).
