### ISSUE TITLE
Interface assignment and IDS messed up after update to 15.7.7_3

### ISSUE THREAD

**Issue by mschilt** [opnsense/core#313]
Did an update yesterday to 15.7.7_3-amd64. Worked first without issues and did not reboot.
Today had NAT issues with one device so I decided to reboot. After reboot the box seemed to be dead.

Analysis showed that the port assignment was messed up.
Before upgrade: 
WAN: re0
LAN: re2
opt1 -> ath0 (wireless)

After upgrade: 
WAN: re1
LAN: re0
(wlan config not present)

So I decided to just restore the interface config from a backup I did one month ago (July 11th).
Did not work. Error message was "XML error: FILE at line 1570 cannot occur more than once"

Next try was a backup from July 3rd which worked.

After changing the cabling again the box seemed to be working so I had a look at the Line 1570 in that 'non-working' backup.
The line mentioned contained the <files><file xxx > settings of the IDS Rules. 

So I decided to check the IDS configuration. After clicking "Services / IDS" I ended up in a broken page. 
Logo was not loading, HTML was displayed without style information. The general log said "no matching csrf found for request" but not 
sure if this message is from that requests to the IDS Page.

Tried to disable IDS and re-enabling it again (never underestimate self-healing powers).
Did not work. When trying to disable the IDS on the broken page the following error message popped up:
 
 Unable to save data, an internal error occurred.
 Response from server was: 
 {"readyState":4,"responseText":"","status":200,"statusText":"OK"}

Crash reporter says ther no programming bug was detected.

Action items:
a) Add Information about request for the CSRF message
b) Is there a DTD/XSD for checking a backup file for validity?
c) Add version information in backup files since their format obviously changes over time.
d) What can I do to revive the IDS configuration?
e) Would provide my config backups to you but they contain data I am not willing to share. Could be beneficial for Opnsense development to have kind of a 'privacy/anonymization' tool for backups.

Hardware: Pcengines APU

**Comment by AdSchellevis** [comment]
If you have the original (working) copy of your previous install, you can try to fix it manually.
All the new OPNsense tags are placed in the xml file under the <OPNsense> tag, if you copy this full tag into your previous working copy all should work.
(just copy it over /conf/config.xml)

I would be happy to check your config, but if you can't send it that would be difficult.

The issues seem to come from some old code, related to the restore function. 

For all new components, like IDS the definition is stored into the model xml file, which can be validated with a few lines of code.The rest is unfortunately legacy code, without a definition to check against. 

There is version information in the backup files from the old system, up until now we haven't had migration issues for upcoming versions. We will add a new tag later on to better distinct the version together with migration code if needed.
Migration form older pfSense / m0n0wall version should still work like it did (using the old version tag).

Can we rename this issue to fixing the "XML error: FILE at line 1570 cannot occur more than once" ?

**Comment by mschilt** [comment]
Sorry for mixing up things. This 'issue' is a collection of different issues. So just changing the title is not optimal. I should have split it up into 'atomic' issues at the beginning. Lets try this now:

Problem 1: Interfaces got messed up during the upgrade from 15.7.6 to 15.7.7_3-amd64. Complete Wireless configuration was lost.
-> still have no idea why this happened. Recovery was a bit tricky and would have caused a downtime if this did not happen in a test environment. Root cause? How to prevent this from happening again?

Problem 2: broken WebUI after restoring an 'old' opnsense backup.
-> Found the issue: the old backup defined 'pfsense_ng' as theme but there is no such theme anymore. Everything is now working again after manually switching theme to 'simple' and then to 'opnsense'.
I believe the restore functionality should check for the theme and not restore 'non-existing' themes.
-> Bug

Problem 3: restoring an older configuration was not possible. Import reported "XML error: FILE at line 1570 cannot occur more than once". This is odd because there are almost always more than one 'file' lines in the rules configuration of the IDS. Nobody will be running the IDS with only one 'rules' file. 
-> Bug in the "restore" functionality? 

Enhancement 1: XSD schema file to check backup files for validity. 
Enhancement 2: Add more documentation around the message 'no matching CSRF found for request'
Enhancement 3: We need an 'anonymization tool' for configuration files so they can be attached to issues without bothering about sensitive data.


Hope things are more clear now.
Do you want to split this into different issues on Github for tracking?

**Comment by AdSchellevis** [comment]
Sorry for the late response, but if you can split it into different issues that would certainly help.
