### ISSUE TITLE
[feature request] Show BIOS information on dashboard

### ISSUE THREAD

**Issue by x-jokay** [opnsense/core#3131]
It would be great to be able to see the BIOS information on the dashboard.

This is how it looks on pfSense :wink:

![20190114_bios](https://user-images.githubusercontent.com/18613935/51101792-76823700-17dc-11e9-9d52-764b1c705b5a.jpg)

Vendor:
```sh
/bin/kenv -q smbios.bios.vendor
```

Version:
```sh
/bin/kenv -q smbios.bios.version
```

Release date:
```sh
/bin/kenv -q smbios.bios.reldate
```

**Comment by fichtner** [comment]
19.1 will feature a brand new dmidecode plugin which adds a dashboard widget...
<img width="594" alt="screenshot 2019-01-14 at 9 16 47 am" src="https://user-images.githubusercontent.com/1915288/51101936-29eb2b80-17dd-11e9-826c-400d5396a75c.png">

**Comment by x-jokay** [comment]
And for the system a combination of these two:

Maker:
```sh
/bin/kenv -q smbios.system.maker
```

Product:
```sh
/bin/kenv -q smbios.system.product
```

**Comment by x-jokay** [comment]
@fichtner this looks great, thx for the information.

**Comment by x-jokay** [comment]
Can be closed, as it will be available in release `19.1`.

**Comment by fichtner** [comment]
Case closed? :)

**Comment by fichtner** [comment]
Nevermind, thanks!

**Comment by x-jokay** [comment]
Looks good 👍
