### ISSUE TITLE
Virtual IP assigned before bridge interface is live

### ISSUE THREAD

**Issue by BCurrell** [opnsense/core#3135]
I am currently setting up high availability Opnsense firewalls, with a similar pair of high availability ethernet providers. This setup requires me to bridge together 2 WAN ports so I can connect to both ethernet providers at the same time.

Following the CARP documentation, I have set up a virtual IP on the bridged WAN interface, which works until reboot. When the firewalls come online, there is an error message stating that it could not "find a required assigned IP address on the interface".

By going into the virtual IP settings, changing nothing, clicking save and applying the changes, the virtual IP gets assigned as expected.

My assumption is that the virtual IP is trying to be assigned before the bridged interface is up.

I am currently using Opnsense 17.1, and have not yet tested 18, however I couldn't find any mention of the issue anywhere, so I don't think it has been raised / resolved.

**Comment by fichtner** [comment]
Hi @BCurrell,

Bridges implementation has always been a problem over the years for several design reasons. I am also not aware of a fix or raised bug report regarding this. It is worth trying out 19.1 and reporting back so we can pin down the issue and try to fix it. Are you able to do this?

Until confirmation I'll keep this at "support" for clarity of the pending issue status.


Cheers,
Franco

**Comment by fichtner** [comment]
No report since 19.1: fixed or timeout.

**Comment by BCurrell** [comment]
Hi fichtner,

I thought I had responded to this ticket.

The issue continued in 19.1, however we removed the bridged interface in our environment so we were no longer affected.

Thanks,
B

**Comment by fichtner** [comment]
@BCurrell thanks for the update. I'm working in a related code area by coincidence now and I will take a closer look therefore. :)
