### ISSUE TITLE
empty entry in static routes since 18.7.10 Bug

### ISSUE THREAD

**Issue by mr44er** [opnsense/core#3136]
![screenshot_2019-01-17](https://user-images.githubusercontent.com/46787531/51327953-a21e4f00-1a72-11e9-8e0e-b0835bd7788f.png)

This empty entry blocks everything on webgui with static routes. No adding, no deleting, no changing, nothing! Changing routes from the console works as usual.
I inspected this further and had it reproduced on 2 machines with 18.7.10

Bug appears not on 18.7, so if you install from the actual download media and don't update firmware, everything works as expected. My workaround for now is adding minimum one or more entries for static routes and then update firmware. This way works.

The bug appears instantly, when you update from 18.7 to 18.7.10 without setting a static route before.
I tried resetting 18.7.10 to factory defaults, empty entry is still there.
Resetting to factory defaults and on first reboot **only** assigning lan-interface is ok and the entry is not there.
Instantly after assigning a second interface it will show up this empty entry, which blocks completely every action with static routes for the webgui.

**Comment by AdSchellevis** [comment]
duplicate https://github.com/opnsense/core/issues/3123

**Comment by fichtner** [comment]
https://github.com/opnsense/core/commit/a111b34

    # opnsense-patch a111b34
