### ISSUE TITLE
Alias not working for NAT rule.

### ISSUE THREAD

**Issue by TheSagest** [opnsense/core#3137]
I am using squid with ssl in transparent mode. This configuration works as expected. I have the two NAT rules for passing to squid on 127.0.0.1, and I have implemented block rules so the proxy cannot be bypassed. So far so good. I have added a few No Bump sites to allow iphones to see updates.

All is good (except for a few sites like Netflix etc. this is another matter). I try to load up the play station and when I do a network test, it fails connection to the play station network. I have 2 play stations and so I thought I would create an alias for them so I can add rules to bypass the proxy, I can also add other IPs to it later so they bypass the proxy.
Alias - Host(s) -192.168.1.246 192.168.1.245
NAT Rule (This is to NOT NAT to Squid The IP's in the Alias)
LAN TCP/UDP !Alias * * 80 127.0.0.1 3128
LAN TCP/UDP !Alias * * 443 127.0.0.1 3129

THIS DOES NOT WORK

How ever if I replace the Alias with the IP address it will work as expected.

I have rebooted to see if that fixes the Alias issue. It doesn't. Change to the IP and it works straight away after applying the change (no reboot necessary).

This is from this forum thread https://forum.opnsense.org/index.php?topic=10916.msg50502#msg50502

All my other aliases work, it seems maybe related to the "invert" NOT selection.

**Comment by AdSchellevis** [comment]
Very likely a configuration issue, tried the same over here (! source address versus ! source alias), without any issues.

**Comment by TheSagest** [comment]
I just checked firmware and it was 18.7.9.
Updated and it is OK.

Sorry, been testing on several boxes.

The Sage !!
