### ISSUE TITLE
Import and Update own public certificate scheduled from shell

### ISSUE THREAD

**Issue by gertfriend** [opnsense/core#3140]
Hello,

i would like to ask here also for the following Topic because here are more technical people: https://forum.opnsense.org/index.php?topic=9863.0

I have the Needs to update the gui certificate hosted on a webserver (internal). So i would like to ask if someone could write a script to download the certificate files and update the gui-certificate. For this i have a Let's encrypt Wildcard certificate witch i use for also for internal hosted Webpages.

Thanks

**Comment by fichtner** [comment]
Sorry, this is not possible. Please keep in mind opening support tickets for community support may or may not work out and if we respond it takes time off other things so we always have to weigh importance...
