### ISSUE TITLE
reporting: when health / RRD graphs are disabled the page is blank

### ISSUE THREAD

**Issue by fichtner** [opnsense/core#3141]
Low priority. Nano images these days disable these graphs by default.

**Comment by AdSchellevis** [comment]
https://github.com/opnsense/core/commit/5f32b0788a8a307cb1650d2c4e5d9d74df6e4647 
![image](https://user-images.githubusercontent.com/9783985/68961145-f9479a00-07d1-11ea-8ba0-8c1d47b8867a.png)
