### ISSUE TITLE
19.1 rc1 - monit widget tool doesn´t show status information

### ISSUE THREAD

**Issue by opnsenseuser** [opnsense/core#3142]
After updating to 19.1 rc1 monit widget doesn´t show any content anymore.
i reinstalled it using gui and restarted the firewall. no difference.

status of the tool says everything is alright!

this is what i see on the dashboard:
![grafik](https://user-images.githubusercontent.com/34602360/51494116-d3bb5100-1db7-11e9-8156-2f9c2c5620fa.png)

this is what the status view shows:
![grafik](https://user-images.githubusercontent.com/34602360/51494424-e4b89200-1db8-11e9-9557-6a144d5e1a7c.png)

**Comment by fichtner** [comment]
Have you read the release notes till the end? There is a known issue with monit code and a patch command.

**Comment by opnsenseuser** [comment]
ok, my fault -> i close this issue!

**Comment by opnsenseuser** [comment]
but the widget problem still extists!

**Comment by fichtner** [comment]
# opnsense-patch 5bb48c3

**Comment by opnsenseuser** [comment]
👍 thx
