### ISSUE TITLE
Functions from util.inc in template

### ISSUE THREAD

**Issue by kekek2** [opnsense/core#3143]
I need this functions in template https://github.com/opnsense/core/blob/master/src/etc/inc/util.inc#L273-L305
I see four possibilities.
1. Add more fields to the model to be calculated in PHP code.
2. Write these functions in the template.
3. Patch src/opnsense/service/modules/template.py and add in it such filters.
4. To make a mechanism that such filters can be dynamically loaded from plugins.
Which option is better ?

**Comment by fichtner** [comment]
timeout
