### ISSUE TITLE
[Feature Request] Add Snyk Git Repo Bot That Finds Known Vulnerabilities

### ISSUE THREAD

**Issue by rebekah65** [opnsense/core#3144]
I think its worth adding support for Snyk, which is a git hub bot that finds and can fix known vulnerabilities in open-source dependencies used in this repository. 

Its easy to implement and with out any coding needed, it can be set to automaticly run for every PR or build.

Also, Snyk can be set to send alerts when vulnerabilities are found, or new upgrades or patchis to fix the vulnerabilities are available.

To implement:

>  - Go to the integrations page and click “Connect to GitHub”.
>  - You need to grant Snyk additional GitHub permissions. Choose to give access to public and private repositories, or grant access to public repositories only.
>  - Next, you’ll see a list of all GitHub repos across your GitHub organisations. Select the repos you would like to test with Snyk. If you have supported manifest files at the root, or one or two directories deep, Snyk will automatically recognise and create projects for them.
>  - Click on the button at the bottom of the page “Add selected repositories to Snyk”. The selected repos appear in your projects, and will be continuously checked for vulnerabilities.
>  - Clicking “View report” on any project lets you view & fix vulnerabilities right away. You’ll be able to review the suggested remediations, and create a PR with the required upgrades or patches.

Git:
https://github.com/snyk/snyk

Documents/Wiki:
https://snyk.io/docs/github/

![snyk_test_in_pr](https://user-images.githubusercontent.com/43880872/51545583-306f4800-1e5a-11e9-80ba-fc8f0a0c1d75.png)

**Comment by AdSchellevis** [comment]
spam?

**Comment by rebekah65** [comment]
No, i have recently discovered Snyk and it can really help to stop easley rectifiable vulnerabilities wildest not causing too much time for devs.
So, surely its a win win.

**Comment by L1ghtn1ng** [comment]
I was using that for a while but I prefer dependabot that would also be worth a look
________________________________

**Comment by rebekah65** [comment]
@L1ghtn1ng 
I haven't heard of dependabot but, it's worth a look.
Does it support and detect as many vulnerabilities and dependencies as Snyk.

**Comment by L1ghtn1ng** [comment]
It just makes sure that your dependencies are up to date which inturn fixes the issues in your dependencies
________________________________

**Comment by MichaelDeciso** [comment]
Judging from the Snyk docs, it doesn't support PHP, even though a sizeable portion of OPNsense's code is in PHP. Also, we do not have a lot of external dependencies, which is what this tool scans for. I'm sure it's useful for the kind of project it was intended for, but OPNsense does not appear to be one of them.

**Comment by rebekah65** [comment]
@MichaelDeciso
I could be wrong but, to my knowledge both Snyk and Dependabot, support PHP and more.
https://snyk.io/docs/
https://dependabot.com/#languages

**Comment by MichaelDeciso** [comment]
It still leaves the point that OPNsense barely _has_ external dependencies, and that it doesn't handle them via tools like Composer or NPM. Tools like Snyk and Dependabot simply won't work with projects like ours, even if they support PHP.
