### ISSUE TITLE
[MVC] Enable tokenize2 "sortable"

### ISSUE THREAD

**Issue by fraenki** [opnsense/core#3145]
As discussed in https://github.com/opnsense/plugins/issues/582, we should integrate the new version of tokenize2 which makes it possible to use the "sortable" functionality without jQuery.

Ping @AdSchellevis :)

**Comment by AdSchellevis** [comment]
@fraenki can you try https://github.com/opnsense/core/commit/aec3515ceeb225541d0cc38fa8a9b0f6530f11dc + https://github.com/opnsense/core/commit/49244f477166191f7df5e1352faf8ef9c4488def ?

**Comment by fraenki** [comment]
@AdSchellevis I've tested both commits as well as the backend commit https://github.com/opnsense/core/commit/0a0c80c006fb759f502373f53a5895e805d4770f. But if I set `<Sorted>Y</Sorted>` in the Model (i.e. for HAProxy), the `sortable` attribute is not set for tokenize2 (at least I couldn't find it in the HTML/CSS code in my browser), so it does nothing.

Could it be that a tiny little piece of code is still missing to enable the tokenize2 `sortable` attribute in the frontend?

**Comment by AdSchellevis** [comment]
@fraenki sorry for the late reply, but with https://github.com/opnsense/core/commit/a8d89dadc5ade1d5b8c2b4904c37e6b9e3110dd6 you can now use  `<sortable>true</sortable>` in your form fields.

**Comment by fraenki** [comment]
@AdSchellevis Great, works as expected! Thank you!

@fichtner Not sure what was already merged/cherry-picked, but you also need to merge the new tokenize2 lib for this to work: https://github.com/opnsense/core/commit/aec3515ceeb225541d0cc38fa8a9b0f6530f11dc, https://github.com/opnsense/core/commit/49244f477166191f7df5e1352faf8ef9c4488def

**Comment by fichtner** [comment]
@fraenki 19.1.2 will have all of it
