### ISSUE TITLE
IPSEC: GUI broken in IE11

### ISSUE THREAD

**Issue by smr1983** [opnsense/core#3149]
Tested on Windows Server 2016 with IE11.

The second dropdown in the Phase 1 algorithm settings remains empty after selecting a value in the first dropdown.  Also the certificate fields remain obligated to fill, even when using PSK.

In the end the ipsec.conf is flawed.

With Chrome the issue isn't present and the final ipsec.conf is also working.

**Comment by fabianfrz** [comment]
@AdSchellevis I don't see any ES6+ specific function which may also cause trouble on outdated browsers. Maybe the console reveals something. Maybe it is due to an additional restriction on Windows Server since it is not the same IE as the one you get with the "normal" Windows.

**Comment by AdSchellevis** [comment]
@fabianfrz could very well be, since this won't impact many users and I can't reproduce it myself, it's very low on my priority list.

**Comment by smr1983** [comment]
@AdSchellevis 

Javascript is enabled.

I get a console error when opening the tunnel settings page: SCRIPT438: Object doesn't support property or method 'includes' in jquery-3.2.1.min.js (2,31689).

I also tested this on my own W10 - IE11 combination and I get the exact same error. So I have this error on both WS2016 - IE11 and W10 - IE11 on three different installations of OPNSense.

**Comment by smr1983** [comment]
@AdSchellevis 

Looks like includes isn't working on IE: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/includes#Browser_compatibility

**Comment by AdSchellevis** [comment]
@smr1983 can you try https://github.com/opnsense/core/commit/eff447b55902f48b59e4ac11081cce71445077b6 ?

**Comment by fabianfrz** [comment]
@AdSchellevis includes is an ES6 function. I use it as well in the nginx plugin. In this case I would recommend using a polyfill (patching the string class) instead of going back to the less beautiful ES5 check.

**Comment by fabianfrz** [comment]
```js
if (typeof(String.prototype.includesx) != 'function') {
    String.prototype.includes = function (needle) {
        return this.indexOf(needle) >= 0
    }
}
```

**Comment by fabianfrz** [comment]
Additionally to the comment of @AdSchellevis: use ctrl + f5 if it does not work immediately - the script may be cached in the browser.

**Comment by smr1983** [comment]
I've tested https://github.com/opnsense/core/commit/ebb365f0618ad383c05aa7ada6f0a5461419d5cc and validated that opnsense.js included the changed code, but the tunnel settings is still raising the same console error. So it looks like the patch in opnsense.js is ignored and it is still using the jquery version of include instead of the version in opnsense.js.

After I reverted that commit and patched with https://github.com/opnsense/core/commit/eff447b55902f48b59e4ac11081cce71445077b6 I retested the tunnel settings and that commit does indeed solve the issue.

**Comment by AdSchellevis** [comment]
ok, let's revert https://github.com/opnsense/core/commit/ebb365f0618ad383c05aa7ada6f0a5461419d5cc and add https://github.com/opnsense/core/commit/eff447b55902f48b59e4ac11081cce71445077b6 then, knowing that IE11 support will likely be less perfect on other areas.

**Comment by smr1983** [comment]
Thanks for the fix. Hopefully this will save others some hours debugging ipsec issues.

**Comment by AdSchellevis** [comment]
@fabianfrz probably, for the ipsec case it's better to switch to `indexOf` for increased compatibility. I have no issue in accepting a patch to opnsense.js to fix issues which might occur in plugins. (Although I can't test it myself at the moment)

**Comment by fichtner** [comment]
Here's more:

```
$ git grep "\.includes"
src/opnsense/mvc/app/views/OPNsense/Diagnostics/fw_log.volt:                if (!hostnameMap.hasOwnProperty(address) && !to_fetch.includes(address)) {
src/opnsense/mvc/app/views/OPNsense/Firewall/alias.volt:                if (!regions.includes(item.region) && item.region != null) {
```

From looking at plugins, it also seems that FRR/Quagga and Nginx also use it.

**Comment by AdSchellevis** [comment]
@fichtner https://github.com/opnsense/core/commit/9abf5af9a76623842e80591a273420bb3bd38b50

**Comment by fichtner** [comment]
@AdSchellevis thanks a lot 👍

**Comment by fabianfrz** [comment]
@fichtner FRR is using the lodash function, which is not native anyway (https://lodash.com/docs/4.17.10#includes). The nginx plugin JavaScript code written entirely in ES6.

**Comment by fichtner** [comment]
okay, fine then this is all sorted. thanks ❤️
