### ISSUE TITLE
Feature Request:- Copy feature for ALL values in an input box for ease of transfer.

### ISSUE THREAD

**Issue by TheSagest** [opnsense/core#3159]
I would like to see a "COPY" to clipboard? or  Text view for the values in an input box so that it makes it easier to copy a large list of values, say, from a test machine, to a production machine. EG copy the list of SSL No Bump from test machine to production machine.

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository, 
please read https://github.com/opnsense/core/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue, 
just let us know, so we can reopen the issue and assign an owner to it.
