### ISSUE TITLE
[FEATURE REQUEST] IDS Alert Widget

### ISSUE THREAD

**Issue by lattera** [opnsense/core#316]
It'd be nice to see the latest IDS alerts on the dashboard.

**Comment by mschilt** [comment]
I would love to have something like a 'light version' of evebox (http://blog.jasonish.org/2014/05/22/evebox-an-eve-event-viewer-for-suricataelasticsearch/) 

Evebox uses elasticsearch (most often combined with logstash) so I think this would be an overkill for Opnsense. But the look&feel of evebox is great.

**Comment by fichtner** [comment]
Continued in #1025
