### ISSUE TITLE
[19.1RC1][ui] Failing input validator for descriptions if using any non alphanumeric characters

### ISSUE THREAD

**Issue by lhorace** [opnsense/core#3160]
Hello everyone,

I'm not sure if this is intended design choice, see below:

`Description should be a string between 1 and 255 characters`

If it is intended behavior, can the error description also include what is allowed, eg `[A-Za-z.]` ? My assumption here, if one is calling it a `string`, can't a `string` include any `UTF-8` characters?

I encountered this problem when I wanted to include 10.0.0.0/16 in my alias description for clarity sake.

Much appreciated,
Regards.

**Comment by AdSchellevis** [comment]
Th description isn't really used anywhere else, valid input is defined here https://github.com/opnsense/core/blob/53a17f99285722121f9b06141a8b998c7f14e9fd/src/opnsense/mvc/app/models/OPNsense/IDS/IDS.xml#L48 I don't mind to replace this with a better description, but have no suggestions myself at this time (the same message is used for some other fields as well)

**Comment by lhorace** [comment]
`Description should be [\t\n\v\f\r 0-9a-zA-Z.\-,_\x{00A0}-\x{FFFF}] and a string between 1 and 255 characters`?

I guess some of the regex tokens could be left out to avoid confusing users who aren't familiar with regex. This here is an example of similar error messages when failing input validation that I come across.

**Comment by AdSchellevis** [comment]
so, if we're going to replace the message, it should be user-friendly (which would always leave a bit of room for interpretation). 

Better suggestions are welcome, we're not going to add the technical text in the message.

**Comment by AdSchellevis** [comment]
The validation prevents script tags to be inserted (for example), so we prefer to keep input cleansing.

**Comment by AdSchellevis** [comment]
@lhorace ok, you're right, it's not consistent. I'm going to drop the constraint (only keeping the limit)

There will likely be other descriptions suffering from the same issue, if reported, we'll evaluate per case what todo.
