### ISSUE TITLE
Unable to use port ranges in traffic shaper

### ISSUE THREAD

**Issue by StevenNexus** [opnsense/core#3162]
When trying to create firewall shaper rules. The UI will not allow entering of port ranges for _dst-port_ or _src-port_ fields. Please see example marked up screen capture.

![image](https://user-images.githubusercontent.com/31380256/51857065-48821400-22ff-11e9-9e10-a60dc5cc974b.png)

**Comment by 2bithacker** [comment]
I'm seeing this same behavior, was trying to set up a rule to prioritize mosh traffic, which uses a range of UDP ports.

**Comment by AdSchellevis** [comment]
I think this worked by accident a long time ago, our port validator seems to be missing support for ranges. I'll put it on my list.

**Comment by AdSchellevis** [comment]
https://github.com/opnsense/core/commit/0f6b29f5bbe15e7bf3b2e276f36e4921626d2e1e should do the trick

**Comment by StevenNexus** [comment]
Do I test this patch by running the dev branch or can I test this patch using production 18.7.10_3-amd64?

**Comment by AdSchellevis** [comment]
I think it fits 18.7 too, we'er very busy with 19.1 at the moment, so you have to test for yourself to be sure.

**Comment by beemac88** [comment]
Is there no way to use an **alias** for these fields? That, comma separated, or by using tab as shown here?
![image](https://user-images.githubusercontent.com/62079514/78316996-1980b700-752f-11ea-9295-a8bd5853be79.png)

The image shows a list of non-contiguous ports that I'm trying to use in two separate traffic shaper rules, and I just updated to 20.1.3 from 19.7.8 in hopes of fixing this. In _both_ releases, I can only enter one range. It will accept one port at a time, or a single range, but not a combination. I tried the same in **Src-port** just to test and it's the same result.

I even tried manually downloading
[PortField.php](https://raw.githubusercontent.com/opnsense/core/1a110daaa8e2849ac91d233e632e9c0e6947acd5/src/opnsense/mvc/app/models/OPNsense/Base/FieldTypes/PortField.php)
and
[TrafficShaper.php](https://raw.githubusercontent.com/opnsense/core/0f6b29f5bbe15e7bf3b2e276f36e4921626d2e1e/src/opnsense/mvc/app/models/OPNsense/TrafficShaper/TrafficShaper.xml)
and updating them in their respective folders via ssh, but the issue persists.

Is there something I'm missing? Has anyone else been able to use aliases or more than one range per rule?

**Comment by opensourcefan** [comment]
Sorry for waking up a stale thread but I've been having this issue for as long as I've been using the Shaper. 

For the life of me I can't get it to accept anything separated by a comma and many times it doesn't accept ports separated by dashes. It seems to be a crap shoot of just doing it over and over until it lets me through. Then it works. 

I'm on the latest version but has been happening for many. 

Bare bones installed on a Dell Optiplex 9020 SFF

I have tried for example:

https, imap
(https, imap)
https,imap
(https,imap)
80, 443
(80, 443)
etc etc

**Comment by fichtner** [comment]
This may change over time as FreeBSD 14 and higher offers a pf-to-dummynet feature maybe obsoleting the IPFW integration. FreeBSD 14.1 will ship in 24.7 and then we can take a closer look if it is feasible.


Cheers,
Franco

**Comment by kozistan** [comment]
Hi Fraco, is there any update for this issue?

**Comment by fichtner** [comment]
You can use traffic shaping in the firewall rules now (advanced, experimental)

**Comment by kozistan** [comment]
Thanks for your reply. Yes, i've tried that, but not working once is applied on a firewall rule. 
The same is working as the traffic shaping rule. I thought, ok is still experimental :)

Could you please tell me, once i've apply traffic shaping on a firewall rule, will i see statistic of the queue on traffic shaping stats?

**Comment by kozistan** [comment]
> Thanks for your reply. Yes, i've tried that, but not working once is applied on a firewall rule. The same is working as the traffic shaping rule. I thought, ok is still experimental :)
> 
> Could you please tell me, once i've apply traffic shaping on a firewall rule, will i see statistic of the queue on traffic shaping stats?

-- understand, as traffic shaper is separate layer for queueing with ipfw it can not show statistics from opnsense pf.
for now i finished shaping with  traffic shaper rules, and will wait for non-experimental version of the shaper whitin the firewall.

**Comment by fichtner** [comment]
@kozistan sorry for the late reply. We've seen the same limitation from pf-to-dummynet. For now we're not going to do anything about it, but we're moving captive portal from ipfw to pf, eventually removing the ipfw use completely, but that could take 1-2 more years.


Cheers,
Franco
