### ISSUE TITLE
Huawei ME909s-120 miniPCIe can't connect due to missing CPIN submission

### ISSUE THREAD

**Issue by rackmatrix-david-rene** [opnsense/core#3164]
Hello everyone,

My configuration is
OPNsense : 18.7.8
LTE modem : Huawei ME909s-120 minipcie

that configuration already working well under pfSense. That's why I thought we are near to make it working under OPNsense.

my ppp settings

![screenshot_2018-11-28 devices point-to-point interfaces opnsense localdomain](https://user-images.githubusercontent.com/14163205/51974981-7c854280-2481-11e9-879a-09ac7bf43b70.png)

the error is mainly **CME Error (SIM failure?).**

```
Mar  2 01:49:14 OPNsense ppp: [wan_link0] Link: reconnection attempt 58 in 4 seconds
Mar  2 01:49:18 OPNsense ppp: [wan_link0] Link: reconnection attempt 58
Mar  2 01:49:19 OPNsense ppp: [wan_link0] CHAT: Detected Custom modem.
Mar  2 01:49:19 OPNsense ppp: [wan_link0] CHAT: Dialing server at *99#...
Mar  2 01:49:19 OPNsense ppp: [wan_link0] CHAT: ATDT*99#
Mar  2 01:49:19 OPNsense ppp: [wan_link0] CHAT: CME Error (SIM failure?).
Mar  2 01:49:19 OPNsense ppp: [wan_link0] MODEM: chat script failed
Mar  2 01:49:19 OPNsense ppp: [wan_link0] Link: DOWN event
Mar  2 01:49:19 OPNsense ppp: [wan_link0] LCP: Down event
```
The WAN is red and not connected 

as you can see on settings the SIM PIN code was provided on interface.

I decided to deal directly with the modem to submit the PIN code by hand
```

cu -l /dev/cuaU0.2   //connect to modem
Connected
AT+CPIN?  //asking of the status of the SIM PIN CODE

+CPIN: SIM PIN  //answer that the SIM PIN is required. This is means never submitted of submit failed

OK

AT+CPIN="1234" //submit the PIN code. The answer is OK

OK
```

After submitting the PIN code by hand, the modem can connect see the following picture, WAN is green and has IP address, etc.

![screenshot_2019-01-30 dashboard lobby opnsense localdomain](https://user-images.githubusercontent.com/14163205/51975744-49dc4980-2483-11e9-950f-0f805ae23ce2.png)

Conclusion:
the submission of the PIN code is missing. I also try to configure SIM PIN wait with 40 seconds with same result.

**Comment by AdSchellevis** [comment]
@rackmatrix-david-rene can you compare the contents of both mpd files from OPNsense and pfSense? (or send them to me)

If it functions on the exact same device in pfSense, it would suggest a different command set between these: 

https://github.com/pfsense/pfsense/blob/0b4c14a491664053aad3cc76e1ffd67b70ff2da1/src/etc/inc/interfaces.inc#L2521

https://github.com/opnsense/core/blob/2c61e068a2907d45881792f67f81114ca3c50820/src/etc/inc/interfaces.inc#L1452

**Comment by rackmatrix-david-rene** [comment]
I found the difference. This not located in interfaces.inc, but in mpd.script

I also noticed that the pfsense 2.4.2 has same issue as OPNsense but not pfSense 2.4.4.

the difference is located at line 438 in OPNsense mpd.script the 2 following lines are missing in OPNsense and pfsense 2.4.2

	if $SimPin != "" call DialPeerSetPin
	if $APN != "" call DialPeerSetAPN

this is fit with the issue because simpin was submitted. With that 2 lines it will.

I'll change the mpd.script in OPNsense and will report my result.

**Comment by fichtner** [comment]
That would be https://github.com/pfsense/pfsense/commit/c22d91427 then.

**Comment by fichtner** [comment]
And this broke it... https://github.com/pfsense/pfsense/commit/75e89498529eca6f ... ouch :)

**Comment by rackmatrix-david-rene** [comment]
I confirm,

now it's working well with that 2 added lines

**Comment by AdSchellevis** [comment]
@rackmatrix-david-rene it seems to only happen when "Init String" is used, by default it should use the  ModemIdentHuawei. I'll add these two lines in ModemIdentCustom and close the issue.
