### ISSUE TITLE
When a new firewall rule is created, possible to kill existing sessions that match new rule?

### ISSUE THREAD

**Issue by unipacket1** [opnsense/core#3166]
Not sure if this is a feature request or if the ability already exists and I'm missing it.

When a new firewall rule is created and the action is set to block, any existing sessions that were open before the rule was created/saved continue to work until that session is closed. Would it be possible to change it so that when the firewall rules are reloaded after a new rule is created, any existing sessions that match the new rule are blocked? 

For example, a PC starts a continious ping to google.com.  Then, a new firewall rule is added to block ping outbound.  Because the PC's continious ping was started before the rule was created, ping continues to work until it is stopped.  If the ping is stopped and restarted, then the firewall blocks the traffic.

**Comment by AdSchellevis** [comment]
it won't be possible you can't map a new rule to an existing state with certainty, you can drop specific states using diag_dump_states.php

**Comment by unipacket1** [comment]
Thanks AdSchellevis!

Just from a technical standpoint, is it because of how pf handles sessions and rules?  The reason I ask is that Ive used some linux based firewalls and when a new rule is created, any open connections matching the new rule are blocked.

**Comment by AdSchellevis** [comment]
I think conntrack in Linux is different in that regard, maybe they link the rule to the state so they can remove it when it's not there anymore. 

By my knowledge, the state table in FreeBSD only contains the state and not the origin of the state.

**Comment by unipacket1** [comment]
Ok, was curious.  Thanks again!
