### ISSUE TITLE
Remove multiple entries - removing only one

### ISSUE THREAD

**Issue by Nornode** [opnsense/core#3168]
**VERSION:**
OPNsense 18.7.10-amd64
FreeBSD 11.1-RELEASE-p18
OpenSSL 1.0.2q 20 Nov 2018

**Current Outcome:**
Services > HAproxy > Settings > Real Servers
Marking several lines/Checking the cross mark to remove all entries - Clicking trashcan below entries next to "+" sign.
Only the last line is removed
This has also been tested in 
Services > Let's Encrypt > Validation Methods with the same behaviour.

**Expected outcome:** 
All Checked lines would be removed

**Comment by AdSchellevis** [comment]
duplicate https://github.com/opnsense/core/issues/3062
