### ISSUE TITLE
List of packages update : display version issue

### ISSUE THREAD

**Issue by gitdevmod** [opnsense/core#317]
In the list of packages update (to 15.7.8), there is a small display version issue for package openldap-client and openssh-portable

![opnsense_2015-08-13_00-38-14](https://cloud.githubusercontent.com/assets/2040775/9236177/8d4aa5c6-4143-11e5-98fc-eb20da331d16.png)

**Comment by fichtner** [comment]
Fixed in https://github.com/opnsense/core/commit/6f075701a257890238018469a173986a1b702296 and already queued up for 15.7.9 -- but nice catch :)
