### ISSUE TITLE
FW-Rules/NAT-Rules: Content Popup for generated aliases too

### ISSUE THREAD

**Issue by bewue** [opnsense/core#3170]
On firewall and NAT pages theres a really usefull content popup for aliases
created by the user, showing up on mouse hover event.
It would be nice to have this too for automatic generated aliases ("X net", "X address"). 
Including all virtual IPs too etc.

**Comment by AdSchellevis** [comment]
timeout (since we use internal pf modifiers, like `:network` and `:0` we don't actually persist these values either, which makes it more difficult to guarantee the correct output as well)
