### ISSUE TITLE
Restore Firewall settings option does not load Aliasses

### ISSUE THREAD

**Issue by Northguy** [opnsense/core#3171]
After experiencing issues with R19.1 I decided to revert to factory settings and to load individual settings step by step. When restoring firewall settings through System > Configuration > Backups > Restore Area > Firewall Rules, the rules are restored, but the Aliasses are not. Resulting in Firewall rules to filter Drop tables without having the accompanying Alias to specify the drop table. 

Aliasses are under   <Firewall> XML tag, so I suppose they should be loaded?

**Comment by mimugmail** [comment]
OPNsense Additions

**Comment by Northguy** [comment]
Don't know if this is the root cause, but line breaks in XML section for Alias look strange.

![2019-02-01_12-06-46](https://user-images.githubusercontent.com/1189058/52119659-0831d700-261a-11e9-824b-0cfc74227a64.png)

**Comment by fichtner** [comment]
This is normal in the new model. The content is stored as is, no fancy XML indent :)

**Comment by Northguy** [comment]
> OPNsense Additions

@mimugmail are you suggesting I should load that specific entry through the backup options? Isn't this strange, as Aliasses are in XML under Firewall section? 

OPNsense Additions is a bit non-descriptive for me. What does this restore?

**Comment by fichtner** [comment]
Everything inside &lt;OPNsense/&gt;. Lack of a fully-fledged model import leaves this as a single batch import, but you can always alter the config.xml that you upload to fit your needs.

Longer story: Alias API moved alias out of the old firewall XML location into our own namespace.

**Comment by AdSchellevis** [comment]
The alias module should have its own export/import at some point, using proper validations on import. 

Let's mark this issue as a feature request, we internally discussed this some time ago and somewhere in the road to 19.7 I will probably add some functions there.

**Comment by Northguy** [comment]
OK, thanks @AdSchellevis, @mimugmail, @fichtner. Resolution was indeed OPNsense Additions. I managed to restore the aliases by importing a modified XML. Agree to put as feature request.
