### ISSUE TITLE
Config Backup via Nextcloud fails because OPNsense doesn't trust its own CA

### ISSUE THREAD

**Issue by pwhack** [opnsense/core#3181]
Hi,

I have a self-hosted instance of Nextcloud and have secured it with an SSL certificate generated by my instance of OPNsense's CA feature. It appears the OPNsense config backup to this instance of Nextcloud is failing due to `"ssl_verify_result":20`. Some quick Googling seems to indicate this is PHP's cURL library saying it could not verify the server's (Nextcloud's) certificate chain. That's odd since the client in this case, OPNsense, _is_ the CA and should include its own CA cert in its truststore when making requests.

I could definitely be wrong but all I have to go on is a generic error in the UI that says `The following input errors were detected: Saved settings, but remote backup failed` and a general log entry below:

`config[43427]: {"url":"https:\/\/privatecloud.localsite.net\/remote.php\/dav\/files\/opnsense-backup\/","content_type":null,"http_code":0,"header_size":0,"request_size":0,"filetime":-1,"ssl_verify_result":20,"redirect_count":0,"total_time":0.108257,"namelookup_time":0.002475,"connect_time":0.003079,"pretransfer_time":0,"size_upload":0,"size_download":0,"speed_download":0,"speed_upload":0,"download_content_length":-1,"upload_content_length":-1,"starttransfer_time":0,"redirect_time":0,"redirect_url":"","primary_ip":"192.168.0.3","certinfo":[],"primary_port":443,"local_ip":"192.168.0.1","local_port":34030}`

Please let me know if there's anything else I should try or log data to collect.
Thanks!

**Comment by fabianfrz** [comment]
See #1460

**Comment by fichtner** [comment]
Duplicate.
