### ISSUE TITLE
19.1 Emerging Threats rules not updating.

### ISSUE THREAD

**Issue by RadarExile** [opnsense/core#3183]
Whether initiated by cron or manually from the interface, the Emerging Threats IDS rules do not update consistently. It seems that they will update exactly once - If I install the ET Telemetry plugin, I can update the rules once after installing it, and future updates seem to fail, with the Abuse.ch timestamp changing but the Emerging Threats timestamps not changing. If I then remove the ET Telemetry plugin, I can update the ET Open rules once, and future updates will fail until I reinstall the ET Telemetry plugin and do this all over again. The Abuse.ch rules are updating fine, every time.

![emergingthreats](https://user-images.githubusercontent.com/47326425/52217042-8c40c480-288f-11e9-80fe-1ab6b0a20736.png)

**Comment by AdSchellevis** [comment]
they only update when there's new data, all ET rules have a version file available (as of 19.1 the ET open uses this too).

**Comment by unipacket1** [comment]
Would it help to display the installed version and the latest version available for download in addition to the last download date and time?  That way one could see if they are not updating?
