### ISSUE TITLE
Cannot access Outlook (Hotmail, Live, etc) and O365 emails

### ISSUE THREAD

**Issue by yhap2003** [opnsense/core#3184]
This one is very odd. First of all, my 18.7.10_4 works great! I have no issue.
19.1 has an issue when i'm on iphone or android devices, it does not connect to the server for my hotmail, live or company o365 account.
As soon as I take wifi off and use LTE, my emails work.

I have a fresh install of 19.1, no firewall rules blocking anything and that was the first problem I notice because i basically live off my smart phone now.

I believe it's an issue with 19.1, I even tried to update through the DEV channel but it too has the same issue. Hopefully it's not just me that has the problem.

**Comment by AdSchellevis** [comment]
might be https://github.com/opnsense/core/issues/3173 if the mtu value of your network card is set using dhcp.

**Comment by yhap2003** [comment]
> might be #3173 if the mtu value of your network card is set using dhcp.

Thank you! It is indeed related!
For others having the same issue.
Go into Interfaces | [WAN] enter 1500 in MTU box
Then go to DHCP client configuration | change Configuration Mode to Advanced | Under Option Modifiers	enter supersede interface-mtu 0

I didn't need to reboot the firewall but it's worth rebooting if it still doesn't work for you

**Comment by fichtner** [comment]
Thanks for the update. We'll fix this one tomorrow in 19.1.1.


Cheers,
Franco
