### ISSUE TITLE
Gateway monitoring status misleading

### ISSUE THREAD

**Issue by soder10** [opnsense/core#3186]
Hello all,

I just figured out recently that the gateway status widget on the dashboard is showing me a very misleading output. I realised, that some time in the past 6 months since I have the firewall running, the gw monitoring has been put into "disabled" state. Still, all icons and hints suggest its "green", "running", and "ONLINE".

How do I mean "disabled"?  System \ Gateway \ Single -> select my PPPOE gateway -> edit properties -> Disable gateway monitoring : This will consider this gateway as always being "up".

Bamm, its checked! TBH I cannot recall having disabled it myself for sure. Or can it be a default value (the help text isnt helpful to figure this out)?

And here comes my big confusion: nothing really suggests that the ONLINE status of the gateway monitoring is a result of a static "set it to online no matter what". Even RTT and RTTd (actually what is this RTTd by the way?) says 0 (I assume it should be read as ZERO MILLISEC, as no indication of unit to be seen). If there was no real measurement, shouldnt it rather say: "n/a" instead?

My def gw (1st hop in my ISP network)  is actually filtering out ICMP ECHO, so I cannot even ping it. Thatswhy it was strange the monitoring can say its ONLINE for sure. I had to setup the alternate monitoring IP as the 2nd hop in the traceroute instead, to get meaningful results and transition from OFFLINE to ONLINE.

Can the icon of the ONLINE state at least suggest its hardcoded + the RTT / RTTd say n/a instead of 0 when no real measurements are done?

**Comment by fichtner** [comment]
In all bluntness, it makes no difference. If monitoring is off the status *must be* good otherwise components expecting actual gateway status will go into fail mode. If you want to change displays please create PRs to discuss.

**Comment by soder10** [comment]
I think what was requested in this thread to mark with a custom color, that the status is OK not because any real world active monitoring proves it, but because a flag hidden in the config says so, regardless of what is the reality.

**Comment by fichtner** [comment]
I'm not sure there's anything to do without raising further questions: if we show "online (disabled)" it needs explaining. If we say "disabled" it needs explaining. If it's "online" it needs explaining. And all of this only because the gateway monitoring creates this visibility. If we strip the feature the assumption about "onlineness" is still the same and there's no magic config trickery involved.

**Comment by fichtner** [comment]
(I'm all for explaining how this works in the docs but we can't just start changing the representation for something that *a lot* of people assume is how it is. I have rarely seen such a discussion to be honest. And still it's solvable as it's just a knowledge gap here.)
