### ISSUE TITLE
Halt privilege dysfunctional

### ISSUE THREAD

**Issue by bleetsheep** [opnsense/core#3187]
When granting the halt (and/or reboot) privilege to an otherwise unprivileged user, the power menu is not shown. When granting the halt privilege, it also breaks the login process. Steps to reproduce:

1. Create a new group
1. Edit group privileges to include "Diagnostics: Halt System"
1. Create a new user
1. Add user to the group
1. Log in with user

Expected result: user is logged in and able to halt the system

Actual result: user is redirected to `https://ui/core/halt`. When trying to access the page directly (`https://10.0.0.1/ui/core/halt`), the user is redirected, presumably because the permission is not granted and the system then tries to redirect the user to their default page.

If you additionally grant any other permissions, you can access those pages by navigating directly to the correct URL. In the menu, one can see that the Power menu is not shown. Presumably, this permission is completely broken and not only redirects incorrectly.

The reboot permission simply does nothing, but does not break the login/main page redirect.

**Comment by AdSchellevis** [comment]
@bleetsheep thanks, https://github.com/opnsense/core/commit/7ee1110d0f0e58a4d18246dbcbba276065243af1 should fix it.

**Comment by bleetsheep** [comment]
Holy crap that was fast; bedankt, Ad!

When would this make it into a release, i.e. that it gets pulled in the update system for production?

**Comment by AdSchellevis** [comment]
you can use `opnsense-patch 7ee1110` in the meantime, 19.1.2 will likely include the patch (within a few weeks)
