### ISSUE TITLE
Better separation of privileges for system updates

### ISSUE THREAD

**Issue by bleetsheep** [opnsense/core#3188]
Currently, there is one permission for system updates. This grants the user access to the screen for system updates, including the tab where they can change which server the updates are pulled from. If you can control what packages are being installed as root, any such user is basically root. There is no point doing updates with an account other than root.

The feature request is to add a permission that allows only pressing the update button and not changing which packages are installed, where they are pulled from, etc.

**Comment by fichtner** [comment]
Let’s discuss this for a moment: you trust this user to do a potentially problematic upgrade, but not enough to let it see all options? Why not use a cron job instead and cut out the middle man?

**Comment by bleetsheep** [comment]
An adversary running an upgrade is only slightly worse than a cronjob running it: they might be aware of a vulnerability in the new version and immediately upgrade my system to make sure I suffer from it, but in such a case, odds are that I would fall for the same update myself. It's definitely an advantage for an adversary to have an account on our system, and it's also definitely an advantage to have privileges assigned, and they can time upgrades for the worst possible moment where a reboot would break the video stream of a product demo or something... but that's all much better than being able to configure their own server as being the update server and pulling any package which then runs as root.

As for a cronjob, how do I get a notification if something fails? How do I get a message if a reboot is required?

**Comment by fichtner** [comment]
I don't understand. How is an adversary by definition someone who could have an account, even with privileges? You seem to ask for an alternate GUI for the firmware updates and we do not intend to provide one.

The whole point about the cron job is that you don't have to do anything.

In this particular use case you describe you can use the API and a token to build a custom application to update:

https://docs.opnsense.org/development/api.html
https://docs.opnsense.org/development/api/core/firmware.html
https://docs.opnsense.org/development/how-tos/api.html

**Comment by bleetsheep** [comment]
> you can use the API and a token to build a custom application to update.

Are you seriously saying "just build an application to do updates for you"? Because besides that sounding like overkill, that statement can apply to every single component of opnsense: everything can be done using custom software, but that's the whole point of using opnsense: all the necessary features are available without having to rebuild the equivalent of opnsense.

Does it not make sense that updates should be run with a low privileged account (heck, I'd almost be fine with it being an unauthenticated GET from the LAN side) so that the admin account only needs to be taken out of the vault for changes that would be advantageous to an attacker?

**Comment by fichtner** [comment]
No, I tend to disagree and I've offered you solutions which you ignore for unknown reasons and still push your agenda. I don't have any more free time to give to your cause, sorry.
