### ISSUE TITLE
Reboot command is not executed

### ISSUE THREAD

**Issue by jstrebel** [opnsense/core#319]
Either trough GUI or trough the CLI I can't reboot the System.
I use 15.7.8 amd64 running on APU
( to execute a reboot i need to go into the shell (option 8) and enter shutdown -r now and then the box reboots)

**Comment by fichtner** [comment]
I saw this just today while testing on a WRAP. Will take this.

**Comment by fichtner** [comment]
All my test cases work now:
GUI halt, reboot, factory reset
Console halt, reboot, factory reset

Will be part of 15.7.9
