### ISSUE TITLE
IPsec multiple Phase 2 failed

### ISSUE THREAD

**Issue by xarados** [opnsense/core#3192]
I has setup Ipsec VPN with one customer, he have 8 Subnets on customer side for each subnet i have create a separate Phase 2 entrie. We use our public IP for communication with the endpoint, so our internal lan was outbound natted to the range of our public ip. My Problem is that traffic goes only to the subnet wich is defined as last in Phase 2. Each other routes are setup but no traffic goes throught the tunnel in each subnet.

When i only use one of the 8 subnets defined in Phase 2 the Traffic goes through the tunnel, so my outbound nat is not the problem.

![ipsec_remote_1](https://user-images.githubusercontent.com/1060030/52278960-ab575900-2958-11e9-8ba3-40d71bc61f88.jpg)

ipsec statusall con3 
Status of IKE charon daemon (strongSwan 5.7.1, FreeBSD 11.2-RELEASE-p8-HBSD, amd64): 
 uptime: 7 minutes, since Feb 04 14:42:27 2019 
 worker threads: 11 of 16 idle, 5/0/0/0 working, job queue: 0/0/0/0, scheduled: 22 
 loaded plugins: charon aes des blowfish rc2 sha2 sha1 md4 md5 random nonce x509 revocation constraints pubkey pkcs1 pkcs7 pkcs8 pkcs12 pgp dnskey sshkey pem openssl fips-prf curve25519 xcbc cmac hmac gcm attr kernel-pfkey kernel-pfroute 
resolve socket-default stroke vici updown eap-identity eap-md5 eap-mschapv2 eap-radius eap-tls eap-ttls eap-peap xauth-generic whitelist addrblock counters 
Listening IP addresses: 
 212.x.x.x 
 212.x.x.x 
 192.x.x.x 
 10.x.x.1 
 172.x.x.x 
 212.x.x.178 
 212.x.x.179 
 212.x.x.180 
 212.x.x.181 
 212.x.x.182 
 192.x.x.x 
Connections: 
       con3:  212.x.x.178...136.x.x.x  IKEv2, dpddelay=10s 
       con3:   local:  [212.x.x.178] uses pre-shared key authentication 
       con3:   remote: [136.x.x.x] uses pre-shared key authentication 
       con3:   child:  212.x.x.176/29 === x.x.x.x/8 TUNNEL, dpdaction=clear 
   con3-001:   child:  212.x.x.176/29 === 136.x.x.0/19 TUNNEL, dpdaction=clear 
   con3-002:   child:  212.x.x.176/29 === 136.x.x.x/15 TUNNEL, dpdaction=clear 
   con3-003:   child:  212.x.x.176/29 === 136.x.x.x/16 TUNNEL, dpdaction=clear 
   con3-004:   child:  212.x.x.176/29 === 136.x.x.x/20 TUNNEL, dpdaction=clear 
   con3-005:   child:  212.x.x.176/29 === 136.x.x.x/19 TUNNEL, dpdaction=clear 
   con3-006:   child:  212.x.x.176/29 === 136.x.x.x/21 TUNNEL, dpdaction=clear 
   con3-007:   child:  212.x.x.176/29 === 136.x.x.x/21 TUNNEL, dpdaction=clear 
Security Associations (4 up, 0 connecting): 
       con3[8]: ESTABLISHED 5 seconds ago, 212.x.x.178[212.x.x.178]...136.x.x.x[136.x.x.x] 
       con3[8]: IKEv2 SPIs: 3eaf068fb2f8c707_i* 8a3908635c83cb96_r, pre-shared key reauthentication in 23 hours 
       con3[8]: IKE proposal: AES_CBC_256/HMAC_SHA2_256_128/PRF_HMAC_SHA2_256/MODP_2048 
       con3{17}:  INSTALLED, TUNNEL, reqid 13, ESP SPIs: cd1a77c3_i 80739a69_o 
       con3{17}:  AES_CBC_256/HMAC_SHA2_512_256, 0 bytes_i, 0 bytes_o, rekeying in 44 minutes 
       con3{17}:   212.x.x.176/29 === x.x.x.x/8

If you need more information let me know.

**Comment by mimugmail** [comment]
When you do outbound NAT you should also add spd I'd guess .. 

Can you verify local initiated connection from Firewall itself to all networks? This should work.

**Comment by xarados** [comment]
￼What do you mean exactly?

**Comment by xarados** [comment]
@mimugmail i have more information from our customer:
Model: Cisco ASR1002
IOS Version: 16.3

Phase 1 settings:
```
sh crypto ikev2 sa remote 212.x.x.178
Tunnel-id Local                 Remote                fvrf/ivrf            Status
31        136.x.x.9/4500       212.x.x.178/4500   none/none            READY
      Encr: AES-CBC, keysize: 256, PRF: SHA256, Hash: SHA256, DH Grp:14, Auth sign: PSK, Auth verify: PSK
      Life/Active Time: 86400/40 sec
```
Phase 2 settings:
```
crypto map MYMAP 17058 ipsec-isakmp
description HAJMA COMSTAR AUTOMOTIVE TECHNOLOGIES PVT LTD
set peer 212.x.x.178
set transform-set TRAN30-ESP-AES256-ESP-SHA512-HMAC
set pfs group24
set ikev2-profile PROFILE10
match address ACL_HAJMA
reverse-route static
```
Routes for IPsec that ends on our Subnet 212.x.x.176/29:
```
19.x.x.x/8
136..x.x.x/15
136.x.x.x/16
136.x.x.x/20
136.x.x.x/19
136.x.x.x/19
136.x.x.x/21
136.x.x.x/21
```

**Comment by mimugmail** [comment]
Why don't you just ask the other side for enabled tcp services on 2-3 different networks,, like rdp or smtp?

**Comment by xarados** [comment]
There are services running on different subnets (SSH, HTTP/s, ...).

**Comment by mimugmail** [comment]
And what happens when you do a telnet to these ports via the Firewall directly asked here: https://github.com/opnsense/core/issues/3192#issuecomment-460685360

**Comment by xarados** [comment]
Permission denied for telnet/ping command.

```
telnet 136.x.x.x 443
Trying 136.x.x.x ...
telnet: connect to address 136.x.x.x: Permission denied
telnet: Unable to connect to remote host
```

**Comment by mimugmail** [comment]
ok, open a second terminal and do "tcpdump -n -i enc0" .. then on first terminal the telnet again and post the output of tcpdump

**Comment by xarados** [comment]
I have test to 2 different Subnets with Ping and telnet:
![screenshot_20190206_150725](https://user-images.githubusercontent.com/1060030/52347163-9692c800-2a21-11e9-914c-7a1355d56f77.png)

**Comment by mimugmail** [comment]
As it travels through the tunnel it looks fine to me.
You have to mark the network in SPD (phase2 at the end) 

https://wiki.opnsense.org/manual/how-tos/ipsec-s2s-binat.html

**Comment by xarados** [comment]
My internal LAN is marked in SPD Phase 2.
BINAT rules have i not, i have outbound nat configured.
When i would save a new BINAT rule it is not possible.

![screenshot_20190206_153435](https://user-images.githubusercontent.com/1060030/52348645-1ff7c980-2a25-11e9-9cb5-79a62bfb6e92.png)

**Comment by xarados** [comment]
Hi @mimugmail is there are already news or
do you need more information?

**Comment by mimugmail** [comment]
The screenshot is incomplete

**Comment by xarados** [comment]
@mimugmail here a complete Screenshot.

![screenshot_20190210_151524](https://user-images.githubusercontent.com/1060030/52534880-4a0ffb00-2d47-11e9-9892-c9528900d237.png)

**Comment by mimugmail** [comment]
Can you try with all same subnet masks, I'm not sure if this works.

**Comment by xarados** [comment]
When i set my external subnet (/29) from  to the same range like my internal (/16) i can save. Destination IP can be unchanged.

![screenshot_20190210_154846](https://user-images.githubusercontent.com/1060030/52535170-80e81000-2d4b-11e9-9189-02b79788cf1d.png)

**Comment by xarados** [comment]
After some research we are also affected by #2173.
As Workaround we use a Script that deletes all old SPDs and set new SPDs with the changed unique IDs. 

Will there be a solution to the problem in the foreseeable future?

**Comment by AdSchellevis** [comment]
only for verified cases (not using dynamic addresses), such as  https://github.com/opnsense/core/commit/8f45e0d8623a6da395e12be5b51b3ab74e490f77 

We keep https://github.com/opnsense/core/issues/1773 for tracking, although some scenarios will likely remain unsupported as long as nobody comes up with viable pull requests.

**Comment by AdSchellevis** [comment]
since this is related to https://github.com/opnsense/core/issues/1773, we should close this issue as duplicate.
