### ISSUE TITLE
19.1.1 OpenVPN Client Export Issues

### ISSUE THREAD

**Issue by bewue** [opnsense/core#3193]
My OpenVPN server is listening on TCP Port 443.

I have applied the patches (but same issues after update to 19.1.1):
`opnsense-patch 9eebb2eb7 81364dd3d 6ee58cc30 e9d1aa4`
suggested here: (https://github.com/opnsense/core/issues/3174#issuecomment-459977612)

Then the exported client config works with my "OpenVPN Connect" client on android.
But there is still one error (and two warnings) with the current openvpn.net community client for windows.
(https://swupdate.openvpn.org/community/releases/openvpn-install-2.4.6-I602.exe)

`Options error: Unrecognized option or missing or extra parameter(s) in my_VPN.ovpn:4: tcp-client (2.4.5)`

Theres no option "tcp-client"?
When the option is removed the VPN client connect is succesful.

And two warnings:
`Tue Feb 05 15:07:16 2019 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this`
`Tue Feb 05 15:07:15 2019 WARNING: No server certificate verification method has been enabled.  See http://openvpn.net/howto.html#mitm for more info.`

The warning messages disappear if i add the following to my client config:
`auth-nocache`
`verify-x509-name opnsense_vpn_server name`

Maybe this should be added to the exported client config?

**Comment by AdSchellevis** [comment]
`verify-x509-name ... name` shouldn't be necessary, `verify-x509-name .... subject `should be in there

`auth-nocache` could be a useful addition, I'll have to check it it should be default/optional

**Comment by AdSchellevis** [comment]
selected server mode? most settings in the export depend on the server end, your issue doesn't contain a lot of context.

**Comment by bewue** [comment]
> 
> 
> selected server mode? most settings in the export depend on the server end, your issue doesn't contain a lot of context.

Server Mode is "Remote Access ( User Auth )"

**Comment by AdSchellevis** [comment]
```
opnsense-patch c83aa08c
```

**Comment by bewue** [comment]
> ```
> opnsense-patch c83aa08c
> ```

The patch did the fix for the `verify-x509-name ...` issue, thanks :)!

The error with  the `tcp-client` option is still present.
`tcp-client` should be `proto tcp-client` ?

**Comment by AdSchellevis** [comment]
@bewue right, missed that one, https://github.com/opnsense/core/commit/710b82917a94d941a48af45746cdf0e4b20b851a

**Comment by bewue** [comment]
> 
> 
> @bewue right, missed that one, [710b829](https://github.com/opnsense/core/commit/710b82917a94d941a48af45746cdf0e4b20b851a)

@AdSchellevis ok, `proto tcp-client` was added to the exported client config. The config now works out of the box.

**Comment by AdSchellevis** [comment]
@bewue ok, thanks for confirming, I'll take a look if we should do anything with `auth-nocache`, since you can easily add it now, I'm a bit if doubt if we should add more checkboxes...
