### ISSUE TITLE
19.1 OpenVPN Problems with multiple OpenVPN server instances

### ISSUE THREAD

**Issue by bewue** [opnsense/core#3194]
The Roadwarrior VPN worked until i configured a second OpenVPN server.
Server1: TCP 443, IPv4 Tunnel Network: 10.50.0.0/24
Server2: UDP 443, IPv4 Tunnel Network: 10.50.1.0/24

On the OpenVPN interface i have allowed IPv4+6* from [10.50.0.0/24 and 10.50.1.0/24] to any.
So everything should be allowed.

But in the firewall logs i see blocked packages by "default deny" on interface ovpns2.
Then i assigned the two OpenVPN interfaces (ovpns1 and ovpns2, Interfaces -> Assignments )
and applied the same rule as above on both. But the traffic was still blocked.

I logged in to the OPNsense and tried to ping the local VPN endpoint:
`root@fw:~ # ping 10.50.0.1`
`PING 10.50.0.1 (10.50.0.1): 56 data bytes`
`36 bytes from localhost (127.0.0.1): Time to live exceeded`
`Vr HL TOS  Len   ID Flg  off TTL Pro  cks      Src      Dst`
` 4  5  00 0054 200c   0 0000  01  01 84a2 10.200.0.1  10.50.0.1`

-> Time to live exceeded

btw. do i have to assign the additional OpenVPN interfaces und place the firewall rules on them?
...One interface for all OpenVPN connections would be fine for me! ;)

**Comment by fichtner** [comment]
@bewue is this still the case for you?

**Comment by bewue** [comment]
@fichtner i'm currently running version 19.1.9 and everything works!
The same scenario as above, but I have not assigned the two OpenVPN interfaces (ovpnsX).

**Comment by fichtner** [comment]
Ok, nice to hear. I think assigning is mostly for OpenVPN clients anyway. Close issue?
