### ISSUE TITLE
GUI of monit - doesn´t allow hostnames

### ISSUE THREAD

**Issue by MikeyMikeDO** [opnsense/core#3195]
monit configuration: Service and type "Remote Host" in Field "Adress" no hostnames are allowed.
--> Error: "Address must be a valid IPv4 address".

But in the monit manual its possible to choose an IP Adress or a hostname. So i can´t check a dynamic hosts.

**Comment by AdSchellevis** [comment]
@MikeyMikeDO thanks for reporting, the validation is faulty indeed.
