### ISSUE TITLE
Bug: hostname aliases are only resolved to v4 addresses, not working with v6

### ISSUE THREAD

**Issue by theq86** [opnsense/core#3196]
I can't access the webinterface via IPv6. Is that normal? And can I enable it somehow?

**Comment by fichtner** [comment]
lighttpd doesn't like link-local, but assigned static or tracked IPv6 should work. my static setup responds to IPv6.

**Comment by theq86** [comment]
Seems this turns into either a bug or a feature request.
The firewall blocks the incoming connection.
Reason: I'm using a hostname alias. Hostname aliases are resolved to their IP addresses according to the documentation. This seems to be true for A records only. May that be true?
I have 2 rules that should make the alias pass. For IPv6 and IPv4. Only the v4 rule works. When I statically entered the v6 IP into the rule it worked. Unfortunately this is not a durable solution since the addresses change from while to while.

**Comment by fichtner** [comment]
I'm not sure what the bug or feature is... if DNS of the OPNsense to a link local and that isn't working for lighttpd we'd have to look at support it for lighttpd, no?

**Comment by theq86** [comment]
No. It's an issue with the firewall aliases, see above.

if you create a host alias for example.org it is resolved and the Firewall uses the resolved ip for it's rule.

That works well with IPv4 but not with IPv6 so I assume AAAA records are not also resolved and used if the firewall rule is a v6 rule.
It has nothing to do with link-local addresses or the webserver.

**Comment by fichtner** [comment]
Now I'm utterly confused. You wrote initially:

> I can't access the webinterface via IPv6. Is that normal? And can I enable it somehow?

**Comment by theq86** [comment]
Yes. But after some debugging I got to the real problem. The webserver is ok and responds on v6. I got it working.
The reason that it did not work was the firewall that blocked my http requests because my pass rule did contain an alias whose ipv6 address did not get resolved.

**Comment by fichtner** [comment]
Ok, how can I reproduce this locally?

**Comment by theq86** [comment]
Take an OPNsense instance with both, a public static IPv4 and IPv6 address on WAN.

Use case is accessing the Webinterface from the internet.

Take a subdomain (fw.example.org) and give it an A record and an AAAA record using the above public addresses.

Use this subdomain as the opnsense's hostname.

Disable the anti lockout rule on WAN

Add an firewall alias of type host and assign it your fqdn.

Add a v4 rule that let's pass tcp:443 packages from the above alias on WAN

Do the same for v6

Result:

IPv4 will pass because hostname is resolved to it's ipv4 address.

IPv6 will not pass.

Then add the same v6 rule but replace the alias with the specific ipv6 address.

Then ipv6  will pass.

This is why I think that resolving the ip address for aliases works just for the v4 address.

Hope that clear's up what I mean.

**Comment by fichtner** [comment]
Do you set an inet protocol or assume it will be "both"? This could be a bug in pf, or the default behaviour indeed. Also what is your setting for preferring IPv4 over IPv6 ?

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository, 
please read https://github.com/opnsense/core/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue, 
just let us know, so we can reopen the issue and assign an owner to it.

**Comment by jbcorreia** [comment]
I'm seeing a related issue where some host aliases are resolving only AAAA records, I was expecting both AAAA and A records to be added to the alias table, but only AAAA are there, I have dual-stack ipv4/ipv6. Is this a known bug?
