### ISSUE TITLE
Setting Speed/Duplex on interface causes flapping

### ISSUE THREAD

**Issue by beren12** [opnsense/core#3198]
I have an intel quad card using igb driver and if you set the speed or duplex setting, even to just autoselect, opnsense gets confused and starts bringing the interface up and down. We diagnosed this with @fichtner 

Maybe the best solution would be to somehow not have opnsense freak out every time an interface goes down/up? The real problem is that opnsense sees the interface go down so it tries to bring it down, but by then it's back up, so it re-initializes which makes it toggle down, so it takes it down, etc. It seems to be just a race condition.

**Comment by AdSchellevis** [comment]
This should probably probe first: https://github.com/opnsense/core/blob/7363445d8d5d6d0f4f259af973f3c40ce38c69a6/src/etc/inc/interfaces.inc#L2409-L2419

(did the same for offloading settings, which has similar issues)

**Comment by AdSchellevis** [comment]
@beren12 can  you try https://github.com/opnsense/core/commit/7aab4a99d3581abbe909c31ffd8cefdc8deab9d9 ?

**Comment by Northguy** [comment]
> @beren12 can you try [7aab4a9](https://github.com/opnsense/core/commit/7aab4a99d3581abbe909c31ffd8cefdc8deab9d9) ?

@AdSchellevis : willing to give it a try. How should I apply patch from CLI?

**Comment by AdSchellevis** [comment]
```
opnsense-patch 7aab4a9
```

**Comment by Northguy** [comment]
> ```
> opnsense-patch 7aab4a9
> ```

Applied this patch, but (as you mentioned in my own issue) it only applies to the media and not to my specific error. In other words, does not help in my situation.
