### ISSUE TITLE
Upgrade from console not working

### ISSUE THREAD

**Issue by RobertVanPapeveld** [opnsense/core#32]
In console menu option 12 Upgrade from console is not working. 
![screenshot console menu](https://cloud.githubusercontent.com/assets/10436489/5877777/4214da96-a322-11e4-8a6d-aac4d24de9cf.png)

**Comment by jschellevis** [comment]
pkg upgrade -n
followed by pkg upgrade -y

**Comment by fichtner** [comment]
I'll take care of this right after 15.1.6 including base update scripting.
