### ISSUE TITLE
WebProxy: safePorts / sslPorts mask

### ISSUE THREAD

**Issue by juliocbc** [opnsense/core#3203]
https://github.com/opnsense/core/blob/33815986852d2c9a88a4950895b619e8c5377e76/src/opnsense/mvc/app/models/OPNsense/Proxy/Proxy.xml#L345

When you try to put an invalid tcp port like ex.: 80830 the mask matches and put this on the squid.conf file causing an error: 

`FATAL: Bungled /usr/local/etc/squid/squid.conf line 50: acl Safe_ports port 80830 # unknown`

Suggestion: Make some regex like [that](https://www.regexpal.com/104146) (I've tried to modify to merge with the current mask without sucess yet)

**Comment by AdSchellevis** [comment]
we have a port validator, https://github.com/opnsense/core/blob/master/src/opnsense/mvc/app/models/OPNsense/Base/FieldTypes/PortField.php. we should probably add support for lists there and change the safePorts type.

**Comment by mimugmail** [comment]
Something like this:

```
                <safePorts type="PortField">
                    <Required>N</Required>
                    <FieldSeparator>,</FieldSeparator>
                    <asList>Y</asList>
                </safePorts>

```

But it would break the defaults ..

**Comment by AdSchellevis** [comment]
@mimugmail your right, my mistake, probably better to fix with a regex in that case.

**Comment by AdSchellevis** [comment]
timeout (https://github.com/opnsense/core/blob/master/CONTRIBUTING.md)
