### ISSUE TITLE
LDAP SSL authentication broken

### ISSUE THREAD

**Issue by itn3rd77** [opnsense/core#3206]
Hi @fabianfrz ,

thanks for your great work on the NGINX plugin and the integration of the Advanced Authentication through the available back-ends. After struggling for hours and debugging I give up now and open this issue so someone with more brain power and knowledge in OPNSense can hopefully do the last steps.

I have an LDAP backend for authentication using SSL. The error message from ldap_bind is ```error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed (unable to get local issuer certificate)``` 
When I test the authentication through ```diag_authentication.php``` everything works fine. After digging around in ```diag_authentication.php``` I saw some magic:
 ```
        // temporary fix, ldap handler doesn't do this init yet
        ldap_setup_caenv($auth_cfg);
```

I gave my best to incorporate this inside ```ngx_auth.php``` but still no luck. The error remains.

```
function password_auth_test($username, $password, $auth_server)
{
    $auth_cfg = auth_get_authserver($auth_server);
    if ($auth_cfg['type'] == 'ldap' || $auth_cfg['type'] == 'ldap-totp') {
        // temporary fix, ldap handler doesn't do this init yet
        ldap_setup_caenv($auth_cfg);
    }

    $authFactory = new OPNsense\Auth\AuthenticationFactory;
    $authenticator = $authFactory->get($auth_server);

    return $authenticator->authenticate($username, $password);
}
```

I hope you have a clue how to get this working.

Thanks and best regards
Ingo

**Comment by AdSchellevis** [comment]
we should move the functionality of `ldap_setup_caenv()` to our mvc framework, when I have some time available I'll try to dig into this.

**Comment by AdSchellevis** [comment]
https://github.com/opnsense/core/commit/afcbdee036bb4650bf65e1f8ea0f71277f877ba9 should do the trick, @itn3rd77 can you test and confirm?

**Comment by itn3rd77** [comment]
Thanks @AdSchellevis . I will test and report back.

**Comment by itn3rd77** [comment]
Hi @AdSchellevis,

still not working for me. Here is the error message:

```
LDAP bind error (error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed (unable to get local issuer certificate))
```
Could you please improve the error logging on [LDAP.phpLDAP.php#L327](https://github.com/opnsense/core/blob/afcbdee036bb4650bf65e1f8ea0f71277f877ba9/src/opnsense/mvc/app/library/OPNsense/Auth/LDAP.php#L327) (and propably others) to
```
                ldap_get_option($this->ldapHandle, LDAP_OPT_ERROR_STRING, $error_string);
                syslog(LOG_ERR, 'LDAP bind error (' . $error_string .')');
```
This way a user can see the error message ```LDAP bind error (error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed (unable to get local issuer certificate))``` inside ```diag_logs.php``` instead of ```LDAP bind error (Can't contact LDAP server)```.

Maybe it is some sort of permission problem as this only happens with the www/nginx plugin?

Btw: Instead of the hacky putenv magic couldn't we change the SSL handling to the proper use of LDAP_OPT_X...  [ldap_set_option](http://php.net/manual/de/function.ldap-set-option.php) options?

**Comment by AdSchellevis** [comment]
@itn3rd77 if the authentication tester functions, it's likely a permission issue indeed. the cert can only be read by root at the moment as far as I can see. 

At the moment I don't have a functional test setup here, if you can do some additional testing, I'll happily change the `putenv` and add some extra logging in there.

**Comment by fichtner** [comment]
why not 664? It's only a CA bundle...

https://github.com/opnsense/core/commit/afcbdee036bb4650bf65e1f8ea0f71277f877ba9#diff-931fc3c602fece8c5f8c50e404587185R274

**Comment by AdSchellevis** [comment]
@fichtner right, when I’m at home I’ll take a look

**Comment by AdSchellevis** [comment]
@itn3rd77 https://github.com/opnsense/core/commit/d718992c7691411554306a120a64f1502a04bda7 needs testing, should fix the privilege issue in your case, improves logging and removes the `putenv` where there's an alternative (as of php 7.1).

**Comment by fichtner** [comment]
right, 644 of course, thanks 👍

**Comment by itn3rd77** [comment]
@AdSchellevis Sure will test and report back. Do I have to revert something or simply ```opnsense-patch d718992```?

**Comment by fabianfrz** [comment]
@itn3rd77 just apply it on top of the old one. Just call the command which you have written.

**Comment by itn3rd77** [comment]
Ok now everything is broken.  The file inside ```/var/run/cert``` is zero.

```
root@fw:/ # ls -la /var/run/certs/5a0d7473d7ac4.ca
-rw-r--r--  1 root  wheel  0 Feb 10 21:08 /var/run/certs/5a0d7473d7ac4.ca
```

**Comment by fabianfrz** [comment]
@AdSchellevis you forgot to define $ca which is used in line 289

**Comment by fabianfrz** [comment]
@itn3rd77  #3217 please test it. Please also note that you need to add my username with the right parameter to opnsense-patch.

**Comment by AdSchellevis** [comment]
oops, last minute refactor issue, sorry about that. $this->ldapCAcert should contain only the ref, I'll fix and close https://github.com/opnsense/core/pull/3217

**Comment by AdSchellevis** [comment]
https://github.com/opnsense/core/commit/12b80b85a8571d0c63b8bc1feeb748da2a5aef91 fixes the missing $ca and simplifies logic a bit. 

on a clean install, you should need following to test:

```
opnsense-patch afcbdee d718992 12b80b8
```

**Comment by itn3rd77** [comment]
Hi @AdSchellevis,

after hours of debugging and googling I finally managed to get the whole LDAP SSL stuff working.

The trick (only approved by try and error) was to set all ```LDAP_OPT_X_TLS...``` options before the ldap_connect() call in a 'global' scope (no handle). I even was able to eliminate the last remaining putenv by the option ```LDAP_OPT_X_TLS_REQUIRE_CERT```.

Enclosed you find my modified ```connect($bind_url,...)``` function from ```LDAP.php```. 

```
    public function connect($bind_url, $userdn = null, $password = null, $timeout = 30)
    {
        $retval = false;
        set_error_handler(
            function () {
                null;
            }
        );

        $this->closeLDAPHandle();

        // Note: All TLS options must be set before ldap_connect is called
        if (!empty($this->ldapCAcert)) {
            ldap_set_option(NULL, LDAP_OPT_X_TLS_REQUIRE_CERT, LDAP_OPT_X_TLS_HARD);
            ldap_set_option(NULL, LDAP_OPT_X_TLS_CACERTDIR, '/var/run/certs');
            ldap_set_option(NULL, LDAP_OPT_X_TLS_CACERTFILE, "/var/run/certs/{$this->ldapCAcert}.ca");
        } else {
            ldap_set_option(NULL, LDAP_OPT_X_TLS_REQUIRE_CERT, LDAP_OPT_X_TLS_NEVER);
        }

        $this->ldapHandle = @ldap_connect($bind_url);

        if ($this->useStartTLS) {
            ldap_set_option($this->ldapHandle, LDAP_OPT_PROTOCOL_VERSION, 3);
            if (ldap_start_tls($this->ldapHandle) === false) {
                $this->logLdapError("Could not startTLS on ldap connection");
                $this->ldapHandle = false;
            }
        }

        if ($this->ldapHandle !== false) {
            ldap_set_option($this->ldapHandle, LDAP_OPT_NETWORK_TIMEOUT, $timeout);
            ldap_set_option($this->ldapHandle, LDAP_OPT_REFERRALS, 0);
            ldap_set_option($this->ldapHandle, LDAP_OPT_DEREF, LDAP_DEREF_SEARCHING);
            ldap_set_option($this->ldapHandle, LDAP_OPT_PROTOCOL_VERSION, (int)$this->ldapVersion);

            $bindResult = @ldap_bind($this->ldapHandle, $userdn, $password);
            if ($bindResult) {
                $retval = true;
            } else {
                $this->logLdapError("LDAP bind error");
            }
        }

        restore_error_handler();
        if (!$retval) {
            $this->ldapHandle = null;
        }
        return $retval;
    }
```
If you like just take it over otherwise I am happy to make a pull request.

Beste regards and thanks all for tackling this mulish beast
Ingo

**Comment by AdSchellevis** [comment]
@itn3rd77 hmm, that kind of reverts back to what the putenv was doing in the first place. no need for a pull request, I'll copy your settings and commit it later. I would appreciate a final check if you can spare some extra minutes, as said, I don't have anything similar running here at the moment.

**Comment by itn3rd77** [comment]
Mmhh yes. It's more or less the same, but feels a bit better to use some official documented functions. But that's personal preference I think. 

Sure you can count on me for a final test.

**Comment by AdSchellevis** [comment]
@itn3rd77 ok, thanks, with https://github.com/opnsense/core/commit/3acb8c4d90c26a98973f77eeb3fca466f0356cb4 we should have reached a functional state :) 

If it's ok now, can you close the issue? thanks!

**Comment by itn3rd77** [comment]
Morning @AdSchellevis,

let's go for the next round. I have tested the changes in https://github.com/opnsense/core/commit/3acb8c4d90c26a98973f77eeb3fca466f0356cb4 and I everyting is working fine (Standard, StartTLS and SSL).

Just one little remark. As setup is a single word shouldn't the function better named ```setupCaEnv```? And is't it better style to make the ```function``` private. I would not expect that someone must call this ```function``` from outside, or?

https://github.com/opnsense/core/blob/7f3f522673767bdb13e5e9c283ee65d1e0c1a74d/src/opnsense/mvc/app/library/OPNsense/Auth/LDAP.php#L275

While testing StartTLS I detected a bug inside ```system_usermanager_settings_ldapacpicker.php``` which I think rendered StartTLS useless in the past. For StartTLS to work the LDAP URL must not start with ``` ldaps```. The following if statement must therefore extended.

https://github.com/opnsense/core/blob/7f3f522673767bdb13e5e9c283ee65d1e0c1a74d/src/www/system_usermanager_settings_ldapacpicker.php#L37

to

```
if (isset($_POST['urltype']) && (strstr($_POST['urltype'], "Standard") || strstr($_POST['urltype'], "StartTLS"))) {
```

**Comment by AdSchellevis** [comment]
morning @itn3rd77 thanks for testing, unfortunately the setup can't be private at the moment, since it's used in some other parts of the system. I don't have the time available at the moment to refactor those. I agree about your remark of the function name `setUpCaEnv` would be better named `setupCaEnv`, going to change it, fix the ldap picker and close this issue. 

If you have the time available to refactor the other users of the setup function, feel free to create a pull request, I will look at it when I have a bit of spare time.

**Comment by itn3rd77** [comment]
Hi,

I am a bit astonished that this bug fix was not included in the latest 19.1.2 release. Are there any strong reason to postpone til 19.7 milestone? This is clearly a bug limiting security of the OPNsense installation.

Best regards
Ingo

**Comment by mimugmail** [comment]
It means it's in the ToDo until 19.7 comes, it can also be in 19.1.4 e.g.

**Comment by itn3rd77** [comment]
Thanks @mimugmail for enlighten me!

**Comment by fichtner** [comment]
> I am a bit astonished that this bug fix

I see this as a a feature addition to a critical system (authentication) with all the lines required to be changed to get this done. There was no benefit rushing this into 19.1.2 in risk vs. reward terms.
