### ISSUE TITLE
Freature Request for Logs for CPU/Traffic Graph on Dashboard

### ISSUE THREAD

**Issue by mstrdraco** [opnsense/core#3207]
I'm curious if you could make a small "log" or make the CPU usage/Traffic Graph usage more static on the dashboard?  IE if you leave the page on the dashboard it builds up a graph for CPU usage/Traffic Graph and such on the widget.    Sadly if you move to a different page on the GUI or close the browser and go back it starts all over again so you loose that history.  It would be nice to be able to set this for say 24 hrs, or maybe a couple of days so you can monitor for CPU/Traffic spikes.

**Comment by AdSchellevis** [comment]
check reporting --> health, these statistics are gathered over time.

**Comment by mstrdraco** [comment]
Is there a way to make the Widgets pull from that?  The widgets make it much quicker/easier to get an Idea/feel for what's going on instead of having to try and decipher the statistics?

**Comment by AdSchellevis** [comment]
We don't have widgets utilising rrd data, no plans to build them either (there are quite some statistics available, it would likely be quite some work developing something user friendly within the limit space of a widget)

**Comment by mstrdraco** [comment]
Ok thanks it was worth a shot, never know until you ask :)
