### ISSUE TITLE
Logging not available for failed upgrades

### ISSUE THREAD

**Issue by madtempest** [opnsense/core#3212]
Hi

As per my thread https://forum.opnsense.org/index.php?topic=11518.0 it appears that there is no logs capturing information around in-place upgrades.

The steps I took to upgrade are covered in the thread but here they are again:
1) Attemped to upgrade via the web GUI
2) Attempted to upgrade via the physical console
3) Changed the mirror to another mirror
3) Set the flavour specifically to OpenSSL

At no point does it appear that any logging is performed - or that anyone was able to provide any information as to where logs are being kept or if they are being written at all. This severely challenges the capabilities of both savvier users and the development teams ability to diagnose these faults for other users.

Please consider this a feature request to enable or have logging for in-place upgrades.

**Comment by fichtner** [comment]
We recommend using a serial console to capture the output. VGA works as well, but in this case a video is a better tool. I know this is inconvenient, but upgrades are supposed to be as early as possible on boot and we cannot rely on a lot of tools and ask users not to do unsupervised upgrades.

**Comment by fichtner** [comment]
That being said take a look at this, information freely available in the forum:

https://forum.opnsense.org/index.php?topic=9521.msg51688#msg51688

And on a final note the default installs will not block in this way. Steps to reproduce (or said console output) are highly appreciated. For now we can't assume it is an unmodified OPNsense system because of lack of steps to reproduce and the upgrade testing we do which does not show this issue.

**Comment by madtempest** [comment]
Sensei won't run on a Celeron CPU ;) so that wasn't the issue. 

I did have the saltstack repository in place, but I fail to see how this would impact the installation.

Reiterating, logging would have made this a whole lot more sensible. I recognise that the install is very early in the boot sequence, but that does not preclude there being some kind output to stdout. I mean I am getting VGA output telling me "Installing Opnsense 19.1.txz" followed by "Please reboot" so clearly there is something being delivered to stdout, which in turn could be delivered to a log file. As could data for stderror.

As to "we can't assume it is an unmodified OPNsense system because of lack of steps to reproduce and the upgrade testing we do which does not show this issue." logging would make your lives so much easier in these circumstances don't you agree?

And logging is my feature request here.

**Comment by fichtner** [comment]
First and foremost, I would like to treat this as a support ticket and bring you safely to 19.1. Did the commands work for you?

> I did have the saltstack repository in place, but I fail to see how this would impact the installation.

It is the same as Sensei in this regard, they have a separate repository and that may be the cause of the upgrade stall.

**Comment by madtempest** [comment]
This feature request has been made after I did a new install because I got tired of the install failing after days and days. Not so surprisingly, it all went swimmingly apart from some minor config stuff that was missing - stuff that I was trying to use Salt to manage because it is my third party scripts to manage in my environment.

I've captured the commands for the future however.

**Comment by fichtner** [comment]
https://github.com/opnsense/update/issues/42
