### ISSUE TITLE
19.1.1 Alias API fails to retain data or create new alias

### ISSUE THREAD

**Issue by chrismarkovic** [opnsense/core#3214]
When using the alias_util api for Add / List, I am able to add an address to an existing alias list which is visible in the web interface. The additional entry will be added and will be visible via the API if "list"ing the alias, but after 10 - 20 seconds it will drop every entry in the list except the new one I just added. The 

Existing Alias:

name: myalias
Hosts: 100.100.100.100

POST details:
    addurl = 'https://fw/api/firewall/alias_util/add/myalias'

    addalias = requests.post(addurl,
                    verify=False,
                    auth=(api_key, api_secret),
                    json={'address': '200.200.200.200'})

i.e: listing the alias:
{u'current': 1, u'rowCount': 9999, u'total': 2, u'rows': [{u'ip': u'100.100.100.100'}, {u'ip': u'200.200.200.200'}]
}

after 10 seconds or so:
{u'current': 1, u'rowCount': 9999, u'total': 1, u'rows': [{u'ip': u'200.200.200.200'}]}

Additionally, when adding a NEW alias via the API, the alias is not visible in the web interface, nor selectable for any rules. 

Please let me know if you require any further info or if I'm doing something wrong :)

**Comment by AdSchellevis** [comment]
Can you replicate the exact same behaviour using the gui? if so, please provide steps and alias type used. All endpoints are also available through the user interface.

**Comment by chrismarkovic** [comment]
I'm sorry, I'm not quite sure I understand you. I can use the gui to add/remove/modify an alias, then click apply and it works as expected. This is only occurring when using the /api/firewall/alias_util/add/ endpoint. Is there another API endpoint I should be trying or another component in the gui you're referring to?

**Comment by AdSchellevis** [comment]
The alias_util endpoint is available in the diagnostic section (https://your-host/ui/firewall/alias_util/), could you replicate your issue there?

**Comment by chrismarkovic** [comment]
Yes, that has the same symptom. The new address added via the "Quick add address" box, adds the address into the list and then the existing entry vanishes after 10 - 20 seconds

**Comment by AdSchellevis** [comment]
Which type of alias are you using?

**Comment by chrismarkovic** [comment]
I'm just working with the default Host(s) one

**Comment by AdSchellevis** [comment]
looks like a bug, it's replacing the content instead of adding it...

**Comment by chrismarkovic** [comment]
Thank you for your help with this. We've been looking forward to this feature :)

**Comment by chrismarkovic** [comment]
Is it also intentional that the API created Alias would not be assignable to rules via the gui?

**Comment by AdSchellevis** [comment]
https://github.com/opnsense/core/commit/50c25eaf6b1ddbac78a4618ce38d70393141f534 fixes the replacement on my end.

Install locally using:
```
opnsense-patch 50c25ea
```

**Comment by AdSchellevis** [comment]
if the alias is visible in the interface, you should be able to assign it.
