### ISSUE TITLE
19.1.1 Alias doesn't show up when created by new entry

### ISSUE THREAD

**Issue by chrismarkovic** [opnsense/core#3215]
When using the alias_util api endpoint to add an entry for a new Alias, the Alias does not display in the gui Alias view. The created aliases do appear under the alias_util gui endpoint and entries can be manipulated there but they are not assignable to rules nor can they be deleted.

alias_util ui:
![image](https://user-images.githubusercontent.com/40845383/52536543-e7dee680-2d96-11e9-8e1b-a46c4b0995d9.png)

alias ui:
![image](https://user-images.githubusercontent.com/40845383/52536549-faf1b680-2d96-11e9-9833-61345991f6b3.png)

**Comment by AdSchellevis** [comment]
oops, you added a new one using the alias_util? it shouldn't do that, it doesn't know which type to create either.

**Comment by chrismarkovic** [comment]
*facepalm* That would be the reason ;) 
Is there a proper method for creating and deleting the blank Aliases?

**Comment by AdSchellevis** [comment]
yes, the other endpoints, in the alias menu.

**Comment by chrismarkovic** [comment]
I'm sorry to ask, but I would assume I could use the getAliasUUID, use that uuid in the delItem to remove the "orphaned ones", but they do not appear to have a UUID. They don't return anything, whereas normal ones do.

**Comment by AdSchellevis** [comment]
no problem, you mean the ones created alias_util? you could leave them or remove them from the console.

There's a script available, we don't seem to use it anymore (I think we had a button for this some time ago, but in normal situations this shouldn't be needed):

```
 /usr/local/opnsense/scripts/filter/kill_table.py myalias
```

Will likely do the trick
