### ISSUE TITLE
Suricata, no way to turn certain rules off

### ISSUE THREAD

**Issue by L1ghtn1ng** [opnsense/core#3216]
Title says it all. I want to turn for example; 

SURICATA STREAM Packet with invalid timestamp

So it does not fill my logs up. This is one of Suricata's built in rules. When I search for the sid it does not show up in the rules

**Comment by L1ghtn1ng** [comment]
I used to be able to do this back in 18.1, is it due to the new version that this cannot be down anymore?

**Comment by AdSchellevis** [comment]
probably a left over from your testing yesterday, I don't think we install these files by default.

easiest fix is to `rm /usr/local/etc/suricata/rules/*.rules `and `download + apply`

**Comment by L1ghtn1ng** [comment]
Seems okay after doing your fix, if I do not update this by Wednesday this can be closed as it should be good

**Comment by AdSchellevis** [comment]
@L1ghtn1ng just reopen when not solved
