### ISSUE TITLE
firmware: blank page

### ISSUE THREAD

**Issue by tomcheung789** [opnsense/core#322]
The firmware page is showing a blank page, after upgraded to 15.7.8.

OPNsense 15.7.8-amd64, FreeBSD 10.1-RELEASE-p17, LibreSSL 2.2.2

<img width="881" alt="firmware" src="https://cloud.githubusercontent.com/assets/4339086/9288781/da474664-438b-11e5-9736-0fc24ab9c3f8.png">

**Comment by fichtner** [comment]
Have you tried a different browser? Are you using a non-English language? There were no changes in the page in 15.7.8. If something went wrong with the package install (check your disk space), you can fix it via:

    # pkg install -f opnsense

You'll still be able to upgrade via root console option "12".

**Comment by tomcheung789** [comment]
I reinstalled the package and works fine now, thanks.

**Comment by fichtner** [comment]
Cool, thanks. You may want to check if you have disk space available. It might be related to low free space?

**Comment by tomcheung789** [comment]
There have 2GB free space, I think it should be enough for the upgrade.
