### ISSUE TITLE
[Feature request] Forward To Gateway 

### ISSUE THREAD

**Issue by zero77** [opnsense/core#3225]
At the moment when configuring dhcp you seem to only have the one option of selecting a default gateway. Alongside this, can you give users the option to use opnsense as a gateway and forward to the actual gateway on a different subnet.

Because, this would be especially useful when using opnsense with coaxial router/modems that don't give you many configuration options or similar situations.

For example, if your opnsense has an address of  10.0.0.1/24, and your default gateway is 10.0.1.1, and in the dhcp config options you have 10.0.0.1 as the default gateway which then forwards all traffic to 10.0.1.1.

Thanks

**Comment by AdSchellevis** [comment]
I'm not sure what your looking for here, how should the `dhcpd.conf` look like in your proposed scenario?

**Comment by zero77** [comment]
@AdSchellevis 
Essentially what i would like to do is  configure opnsense as default gateway using dhcp. But, then forward all traffic to the actual gateway.

Also, where can i find the dhcpd.conf file.

**Comment by zero77** [comment]
@AdSchellevis 
I imagine it would look the same but, traffic going to opnsense that's meant for the default gateway, would then be forwarded by opnsense to the actual default gateway, like using a proxy.

**Comment by mimugmail** [comment]
Sounds like you want to set the default gateway in OPNsense to the one you need to reach?

**Comment by zero77** [comment]
Yes, but only opnsense, the rest of the network should use opnsense as the default gateway.
Sorry, if i am explaining this badly.

**Comment by AdSchellevis** [comment]
/var/dhcpd/etc/dhcpd.conf

**Comment by mimugmail** [comment]
I'm quite sure the forums with a nice drawing is the better place where ppl can help you

**Comment by zero77** [comment]
@mimugmail 
> I'm quite sure the forums with a nice drawing is the better place where ppl can help you

Ok thanks for the suggestion, i have followed your advice.
https://forum.opnsense.org/index.php?topic=11621.0

**Comment by AdSchellevis** [comment]
let's close this issue, feel free to open a new one when the forum discussion leads to a feature request.
