### ISSUE TITLE
OpenVPN Server: Pushing IPv6 routes fail

### ISSUE THREAD

**Issue by lattera** [opnsense/core#3226]
When using IPv6 with OpenVPN in server mode, pushing IPv6 routes with the `IPv6 Remote Network` GUI option fails.

The OpenVPN server config OPNsense generates produces this output:

````
route-ipv6 <route>
````

For example, if I wanted to route `::/3`, then OPNsense would generate:

```
route-ipv6 ::/3
```

Instead, it needs to generate:

```
push "route-ipv6 ::/3"
```

Essentially, it's missing the `push` syntax.

**Comment by lattera** [comment]
Using the `advanced configuration` section is an acceptable workaround for now until a fix is committed.

**Comment by lattera** [comment]
Looks like I need more caffeine. I used the wrong option. I should've used `IPv6 Local Network`. Closing this issue out due to PEBCAK.

**Comment by fichtner** [comment]
happens to all of us, thanks for posting the solution! :)
