### ISSUE TITLE
openvpn status icons 404

### ISSUE THREAD

**Issue by groveld** [opnsense/core#323]
on the status_openvpn.php page the icons (kill client) are not displayed properly, it tries to use an bg image which does not exist.

<img width="1068" alt="schermafbeelding 2015-08-15 om 14 38 03" src="https://cloud.githubusercontent.com/assets/3328493/9288838/a5623060-435b-11e5-9d4b-bfdc9b9f7a0f.png">

**Comment by AdSchellevis** [comment]
Should be fixed in one of the following releases, the openvpn pages have been completely refactored last week.
more info in : https://github.com/opnsense/core/commit/8714dfca1976d2386e6c8c97f0b756cb8f3744b1

**Comment by groveld** [comment]
nice!

**Comment by fichtner** [comment]
These changes are in the development package "opnsense-devel", and I think 15.7.9 will have these updates for OpenVPN, too.
