### ISSUE TITLE
Execute custom Command on Carp Failover

### ISSUE THREAD

**Issue by splattner** [opnsense/core#3232]
I'd like to execute some custom Commands on a Carp Failover Event because our Cloud Provider needs us to call an API to Switch a VIP from one VM to an other.

So in the Firewall: Virtual IPs: Settings Dialog a I need a way to add some Code or similar with access to some Variables e.g. Current State (Master/Backup) and the VIP Address

Then I cloud call the API, whenever a VM (= Router) becomes Master and Switch the VIP to this VM.

**Comment by fichtner** [comment]
Documented here https://docs.opnsense.org/development/backend/autorun.html
