### ISSUE TITLE
Double layer openvpn problem after upgrade to 19.1

### ISSUE THREAD

**Issue by ofit** [opnsense/core#3236]
Hello guys.
**Problem 1**

I use Double layer Openvpn on Opnsense, but after upgrading the system to 19.1 at boot does not use OpenVPN_1 tunnel. That means it use only OpenVPN_2 not OpenVPN_2 inside OpenVPN_1. If stop and start OpenVPN_2 it is work ok, OpenVPN_2 inside OpenVPN_1. Please fix this bug. Thanks

Double layer Openvpn -> OpenVPN_2 inside OpenVPN_1

Post on forum.opnsense.org
https://forum.opnsense.org/index.php?topic=11650

**Problem 2**
From https://github.com/opnsense/core/issues/3259

I use Double layer Openvpn on Opnsense, but when WAN changing IP (i mean reconnecting) OpenVPN_2 not start inside OpenVPN_1. OpenVPN_1 up ok. I need manually start OpenVPN_2 almost every time.
I think bug because OpenVPN_2 do not wait until  OpenVPN_1 up and stop at all. Please fix this bug. Thanks

This bug was on 19.1 and 18.7+ versions.
Double layer Openvpn -> OpenVPN_2 inside OpenVPN_1
OpenVPN_1 and OpenVPN_2 use UDP and AES
WAN is pppoe connetion that recconnect and get new ip one time in 2-3 days

Post on forum.opnsense.org
https://forum.opnsense.org/index.php?topic=11829

**Comment by fichtner** [comment]
see https://forum.opnsense.org/index.php?topic=11650.0

**Comment by ofit** [comment]
Why is it close? OPNsense 19.1.7-amd64 still have this bugs.

**Comment by AdSchellevis** [comment]
timeout, https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

**Comment by ofit** [comment]
Ok. And what i should do? Create it again? or did something else?

**Comment by AdSchellevis** [comment]
If your planning to work on "it" yourself, you can always ask to reopen, but as long as there's nobody working on it, it doesn't make sense to keep it open endlessly. (not the support tag as well)

**Comment by ofit** [comment]
ok. Thanks
