### ISSUE TITLE
IPv6 prefix tracking on WAN broken on 19.1.1

### ISSUE THREAD

**Issue by klada** [opnsense/core#3240]
**Describe the bug**

I have a FTTH connection from Deutsche Telekom. They use PPPoE and DHCPv6 for IPv6 connectivity. I am getting a **dynamic** /56 prefix from them. I have split the prefix across multiple interfaces using prefix tracking on WAN interface.

Whenever a new prefix is assigned to me (e.g. after a PPP reconnect) the new prefix is not picked up by the tracking interfaces (LAN and GUEST in my case). This breaks IPv6 connectivity on these interfaces, causing massive timeouts for all IPv6-enabled clients on the networks.

The WAN interface itself (pppoe0) picks up the new prefix, so the firewall can ping IPv6 addresses on the internet even after a PPPoE reconnect.

**To Reproduce**

1. Configure WAN interface with PPPoE and DHCPv6 (request /56 prefix, use IPv4 connectivity)
2. Configure interface tracking for IPv6 on LAN interface
3. The LAN interface gets a subnet from the assigned prefix
4. Power cycle the FTTH modem (to force reconnection)
5. The WAN interface gets a new IPv6 address and a new prefix, the LAN interface keeps the old prefix
6. The new IPv6 prefix is only picked up the the LAN interface after a reboot

**Expected behavior**

The new IPv6 prefix should be picked up by all interfaces after it changes on the WAN interface.

**Environment**
Software version used and hardware type if relevant.
e.g.: 

OPNsense 19.1.1-amd64
Network Intel® I210-AT
APU2C4

**Comment by marjohn56** [comment]
Have you enabled a sticky ipv6 DUID in Interfaces:Settings?

Click on the 'Insert existing DUID' and then save. Then try reproducing.

**Comment by klada** [comment]
Thanks for the input.

Unfortunately I am still getting a dynamic prefix, even if the DUID the OPNsense DHCPv6 client sends out to my ISP stays the same. This is (unfortunately) common practice among ISPs.

I was however able to resolve the issue. It turns out that the "Prevent release" option is required for Deutsche Telekom IPv6. Kinda weird.

Anyway, I am sorry for spamming the issue tracker → closing.

**Comment by marjohn56** [comment]
That's quite normal to use prevent release, I assumed you already had that selected.

**Comment by fichtner** [comment]
No worries, thanks for posting the solution. :)
