### ISSUE TITLE
PAM: extend opnsense-auth to support different helpers

### ISSUE THREAD

**Issue by AdSchellevis** [opnsense/core#3242]
To better guard config.xml access, authenticators should ideally prevent the need of config.xml access. Currently services that are using our integrated authentication system, also need access to the config.xml. 

Since we already use `opnsense-auth` to enable pam on console and ssh, it would be the most logical step to smarten it and move other services to the same approach. 

This probably also prevents issues like https://github.com/opnsense/core/issues/3241 since pam is more standardized.

**Comment by fichtner** [comment]
I like this. service= is already passed to the script and opnsense-auth-test allows to script the service from the command line. The challenge is to pull an auth server list from a plugin, along with passing the user to do selective authentication maybe... we’d also need pre and post hooks, maybe getting the authentication services could be considered pre hook already. Post hook requires authentication state, maybe which server took the authentication.

Best case this allows to boil down authentication to a single opnsense-auth-test call from the service side.

**Comment by AdSchellevis** [comment]
it should (original plan was to move ipsec to pam first), this was just work not high enough on the priority list sofar. We should probably add this on the roadmap for 19.7

**Comment by fichtner** [comment]
Ok 👍

**Comment by AdSchellevis** [comment]
for reference, concepts explained in https://github.com/opnsense/docs/commit/53c89fb7da19ec89908ec225743cc215fe716e65

**Comment by AdSchellevis** [comment]
this should be it, documentation aligned in https://github.com/opnsense/core/issues/3242

Now we can start changing the services (pam consumers), such as the proxy.

**Comment by AdSchellevis** [comment]
https://docs.opnsense.org/development/components/authentication.html
