### ISSUE TITLE
AHCI timeouts after upgrade to 19.1.1 on PC Engines apu4b4

### ISSUE THREAD

**Issue by reet-** [opnsense/core#3244]
After upgrading my opnsense firewall from 18.7.10 to 19.1.1  yesterday, I have major outages. As it turns out these are due to AHCI timeouts/hangs (see the attached screenshots) only visible on the serial console since no login is possible any more, web GUI is dead. 

The firewall runs fine at first, the issue appears after some time. 

**Screenshots**
![opnsense_ahci_timeouts](https://user-images.githubusercontent.com/5601828/53000182-165c6180-3428-11e9-8029-b853ac385603.png)

**Environment**
OPNsense 19.1.1-amd64 with latest kernel.
(I currently reverted to FreeBSD 11.1-RELEASE-p18 which does not contain this  bug)
PC Engines APU.4B4 system board 4GB
AMD GX-412TC SOC (4 cores)

SSD M-Sata 60GB MLC Phison
ada0 at ahcich0 bus 0 scbus0 target 0 lun 0
uhub0: ada0: <SATA SSD SBFM01.2> ACS-4 ATA SATA 3.x device
ada0: Serial Number A4620786198900445883
ada0: 600.000MB/s transfers (SATA 3.x, UDMA6, PIO 8192bytes)
ada0: Command Queueing enabled
ada0: 57241MB (117231408 512 byte sectors)

**Comment by AdSchellevis** [comment]
duplicate https://github.com/opnsense/core/issues/3180, please use our template next time.
