### ISSUE TITLE
mvc, phalcon framework 4.0, PHP 7.2

### ISSUE THREAD

**Issue by AdSchellevis** [opnsense/core#3245]
Not sure when this will be released, but Phalcon 4 will definitely break things.

Run into a "Wrong number of parameters" in `Phalcon\Mvc\Application->handle()`, while upgrading my mac. 

https://blog.phalconphp.com/post/upgrading-to-v4-alpha-1

Keeping this here for tracking purposes.

**Comment by fichtner** [comment]
It’s PHP 7.3 only so it will be a while. ;)

**Comment by AdSchellevis** [comment]
7.2 if I read the article correct, but indeed, no rush

**Comment by fichtner** [comment]
Ah, right. It’s a little better then. I have 7.2 planned for 19.1.x so we will be ready by 19.7 for it if need be.

**Comment by fichtner** [comment]
https://github.com/opnsense/ports/commit/938bcbebcd

Now that 19.1.2 ships the 2.7 -> 2.8 LibreSSL update I'll work on PHP 7.2 migration for 19.1.4 or 19.1.5 and then we'll have this as a test package :)

**Comment by fichtner** [comment]
LibreSSL 2.9 in 19.1.10, PHP 7.2 and Phalcon 4 likely into 20.1...
