### ISSUE TITLE
IPv6 Gateway on gif interface erroneously reports address not in subnet

### ISSUE THREAD

**Issue by mrdaemon** [opnsense/core#3246]
GIF tunnel setup for ipv6 traffic, tunnel interface (associated to opt3 in opnsense) has an address of 2001:470:1c:xxx::2.
Gateway for interface is 2001:470:1c:xxx::1. They are absolutely within the same /64 subnet.

Trying to either
1. Edit the automatically created gateway settings (description, default gateway checkmark, anything) in `/system_gateways.php`
2.  Manually create this gateway via `/system_gateways.php` and selecting opt3 as the interface

Results in the error message:

```
The following input errors were detected:

    The gateway address "2001:470:1c:xxx::1" does not lie within one of the chosen interface's IPv6 subnets.
```
None of the settings are saved. Such a gateway can _only_ be created via `/interfaces.php?if=opt3` by clicking the inline "add gateway" button. It cannot be edited after the fact, so if you forgot or elected not to check Default Gateway in there, your only recourse is to delete the gateway entirely and recreate it via `/interfaces.php` inline.

Checking the "Far Gateway" option in `/system_gateways.php` does not help and the error message still shows up and prevents changes from being saved.

Environment
--------------

OPNsense 19.1.1-i386/LibreSSL
HE tunnelbroker

**Comment by fichtner** [comment]
It should create the gateway for the tunnel automatically and it will use a dynamic setting so you would only have to set the gateway to default as described via:

https://docs.opnsense.org/manual/how-tos/ipv6_tunnelbroker.html

**Comment by mrdaemon** [comment]
From the linked documentation:


```
The newly created interface must now be set as the default IPv6 gateway under System->Gateways->Single by editing the new gateway entry TUNNELBROKER_TUNNELV6 and checking Default Gateway before saving.
```

Doing this results in the error message above, as described. It can only be added via inline editing in the interface properties. Setting the gateway as default after the fact will not work and trigger the error message.

**Comment by fichtner** [comment]
No, the gateway will appear automatically and set the gateway to „dynamic“. Try deleting your current GW.

**Comment by mrdaemon** [comment]
Ah, I see, I had the ipv6 configuration set to static in the tunnel interface, it has to be set to None for the gateway to appear, which is the part I was missing.

That said, manually creating the gatway via the inline controls in edit interface _does_ work. It just can't ever be edited again.

**Comment by fichtner** [comment]
Ok, thanks, I’ll fix the validation in the ajax add.

**Comment by fichtner** [comment]
This will not happen anymore since e40b8f51ac30a9f29f.
