### ISSUE TITLE
[RFC] MVC: automatically sort dropdown field content

### ISSUE THREAD

**Issue by fraenki** [opnsense/core#3251]
### Problem description

Currently **dropdown lists** don't seem to be sorted at all. The content is randomly added to these fields (or in the order in which it appears in config.xml).

For example, the content of a `CertificateField` type is not sorted:
![unsorted](https://user-images.githubusercontent.com/909706/53372760-fbbc4800-3953-11e9-8742-8b69af9b5ea3.png)

### Feature request

Unsorted content is confusing for users. All **dropdown lists** should be **automatically** sorted:

* `CertificateField` items should always be sorted by `descr` (which usually contains the name of the certificate)
* `ModelRelationField` should allow to specify which field should be used for sorting, i.e. by specifying a new `<sort_field>name</sort_field>` attribute

This was requested for the os-haproxy plugin (https://github.com/opnsense/plugins/issues/687), but I've noticed several other places where automatic sorting would make sense.

### Possible issues

Automatic sorting cannot be used when using the new `<sortable>true</sortable>` attribute, because for _some_ fields the item sort order has a special meaning (i.e. priority).

**Comment by AdSchellevis** [comment]
output sorting depends on the field type, as far as the output json is concerned. I'm not sure if the tokeniser has options to apply sorting, otherwise we have to sort the various fieldtypes delivering these lists. I'll take a look when I have some time available.

**Comment by AdSchellevis** [comment]
@fraenki here you are https://github.com/opnsense/core/commit/560a6cb79ebf00d3d9166f621bb6ab923cbeab08

**Comment by fraenki** [comment]
@AdSchellevis fantastique! <3
