### ISSUE TITLE
Unbound can't listen on more than one WAN IP if a user has PPP with a block of public IPs, ignores VIPs, and fails to start if VIPs added in an attempt to fix these issues.

### ISSUE THREAD

**Issue by stilez** [opnsense/core#3256]
SCENARIO #1:  A user has a PPPoE WAN with a block of IPs (say 1.2.3.0/26), and has Unbound exposed to the Internet (maybe authoritative, or serving strictly controlled peers etc).

PROBLEM:   PPP(oE) WANs get a single IP address, if the user has a block of IPs they add those as Virtual IPs on the WAN. But if the user selected "listen interfaces", then OPNsense will actually only listen on the single IP address, it will ignore any VIPs on that interface. Basically Unbound can't be made to listen on the WAN as a whole, even by selecting "listen: WAN (and others)", because the back end doesn't check for VIPs / NAT that may exist and influence which IPs to listen/bind to on the interface.

SUB-PROBLEM - there's also apparently a bug in Unbound, if you do try and forcibly add the VIPs in custom config, Unbound itself won't start. Commenting them out with a "#" allows it to start - but then it can't listen to them. _(I might suspect that's because the single IP "represents" its entire interface, so a VIP being added is a duplicate. Except it clearly doesn't listen to the entire interface so that's not the reason.)_

SCENARIO #2: A user defines a virtual IP on the LAN, that's outside the LAN's configured subnet. Then when the user directs Unbound to listen "on the LAN", it seems it may not listen to the VIP, it just looks at the LAN's "home" address within its subnet. 

I've checked scenario #1 carefully. The subproblem has been reported to its own tracker (https://nlnetlabs.nl/bugs-script/show_bug.cgi?id=4228). Scenario #2 seems like it's likely to fail because it's very similar, and should be checked in testing any fix.

**Comment by fichtner** [comment]
@stilez thanks. we read VIPs from ifconfig directly so can you provide an ifconfig output of such a system and the listen: directives from /var/unbound/unbound.conf ? example IPs are enough. It looks like we're reading the wrong interface...


Cheers,
Franco

**Comment by fichtner** [comment]
PS:  scenario 1 is likely an upstream issue out of our control but, scenario 2 seems solvable :)

**Comment by stilez** [comment]
I ran some ifconfig - no VIPs appeared. I ended up with a ton of debug code in /usr/local/etc/inc/interfaces.inc. I'm not sure if you're setting VIPs on the wrong IF when it's PPP, or whether it's the right IF but here's some kind of routing/addressing data missing (the error meaning isn't clear to me). 

This is what I get, sorry about my raw debug output!

On boot, when it configures and brings up BVIPs, I get this:

```
VIP interface matches interface being configured, or latter is empty. Configuring this VIP on wan

Entering interfaces_ipalias_configure(). 
VIP data to configure is:
Array
(
    [type] => single
    [subnet_bits] => 32
    [mode] => ipalias
    [interface] => wan
    [descr] => server3
    [subnet] => x.x.x..98
)

VIP data for ifconfig is: vip_subnet=x.x.x.98 vip_subnetbits=32 if='pppoe0' family(af)=inet vhid= gateway=

Creating alias:  /sbin/ifconfig 'pppoe0' inet 'x.x.x.98'/'32' alias
Exiting interfaces_ipalias_configure()
```

But when I try that in shell (with or without quotes escaped), it errors out:

```
/sbin/ifconfig pppoe0 inet x.x.x.98/32 alias
ifconfig: ioctl (SIOCAIFADDR): Destination address required

```
The error isn't clear if the issue is, (A) it needs some extra args, or (B) it should be configured on the underlying interface (not the ppp interface), but I'm still pretty sure it's (B).  When I run the same command but change "pppoe0" to "em0" (underlying WAN interface), it works as expected: the alias shows up in ifconfig under em0 and I can also ping from the wan correctly (with replies from the same alias IP).

"Bug scope" question - is this likely to affect any other kind of IP/alias/interface, where one interface underlies another? Because that kind of situation happens a lot (VIPs on bridges between VLANs on PPP interfaces defined on physical interfaces, or whatever else it might be!!). Or is does it just affect anything defined on PPP's? Or just VIP on PPP? Or just IP alias on PPP?

Also when you have a patch for this, I'll test it here, to check that Unbound now listens on all WAN VIPs when WAN is selected, not just the single IP that's used for the PPP entry in $config.

**Comment by stilez** [comment]
Regarding the listening to WAN by Unbound,  unbound_generate_config() in /usr/local/etc/inc/plugins.inc.d/unbound.inc  simply never checks the output of ifconfig or $config's VIP section, so it never attempts to add VIPs to the listening range. In my setup, listening on the WAN adds just one line to unbound.conf:  "interface: x.x.x.97" (first IP and "representative" IP on PPP link).

I wrote a patch for this, but Unbound failed - probably as the aliases actually didn't exist. When IP aliases are set up on the right IF, I'll test it again.

But I didn't know about how to see aliases, so I probed $config's VIP section. Would it be more accurate and robust to  parse the output of ifconfig for each selected IF in turn, to check for any IPs/nets referenced but not listened?  Several reasons why this might be better:

* PF lets you define an IP alias for x.x.x.97 even when that's the IP allocated to the PPP link already, but Unbound then complains at the duplication because it ends up with 2 copies of that line - one from the interface defs, one from VIP defs, and I had to explicitly check that - which could involve looking for overlapping IP subnets etc if it's CARP, perhaps. Parsing ifconfig output instead of $config VIP might simplify that. 
* Avoids accidental omissions, duplications, or other validity-checking
* Guaranteed to catch all (and only!) the defined IPs on selected IFs, however they came to exist

What do you think?

**Comment by fichtner** [comment]
interfaces_addresses() reads from ifconfig for unbound when you set WAN explicitly. Otherwise it binds all so it naturally responds to all.

I think there is an issue with FreeBSD where you can set the alias on PPPoE but ifconfig will not display it which would explain the issue both for us and Unbound.

**Comment by stilez** [comment]
Last, something I've wanted to add for ages! - when you define a PPP interface, allow the user to manually enter some extra IPs/IP ranges that exist on that interface, in the interface config itself. When the IF is configured, these are automatically enumerated and added "behind the scene". Advantages: - (A) much more intuitive, IP aliases still confuse many people, who just want to say "I have this block of IPs on my WAN"; (B) people with many WAN IPs, like a /23 or something, can assume it's automatically enumerated rather than each needing manual entry. (C) it's simple to do.

Would you accept a patch to do this?

**Comment by fichtner** [comment]
Reference to previous https://forum.opnsense.org/index.php?topic=10462.0

**Comment by stilez** [comment]
> I think there is an issue with FreeBSD where you can set the alias on PPPoE but ifconfig will not display it which would explain the issue both for us and Unbound.

I'm not so sure. Running "ifconfig pppoe0 inet IP/32 alias" actually errors out rather than  appearing to succeed + IP aliases on pppoe0  omitted from ifconfig afterwards. If you can set IP aliases on a PPP IF, there's clearly some missing data needed (at best), it's not just an omission in output when ifconfig is queried afterwards.

**Comment by fichtner** [comment]
Errors out with "File exists"? ;)

**Comment by stilez** [comment]
> Errors out with "File exists"? ;)

No - error output is in comment #4 ;)
```
/sbin/ifconfig pppoe0 inet x.x.x.98/32 alias
ifconfig: ioctl (SIOCAIFADDR): Destination address required
```

**Comment by fichtner** [comment]
your manual command is incomplete and we have had a fix for a while

https://forum.opnsense.org/index.php?topic=6690.msg28823#msg28823
https://github.com/opnsense/core/commit/b15d6d48d707832cd6bb0779fd5a28de18441ea0

**Comment by stilez** [comment]
That patch allows the user to set a gateway for an IP alias. In my case the gateway and IPs are dynamic (they can change on reconnection), so I can't set it statically in config. So I had left it empty, hence why there's no gateway in the command it is trying to run.

4 fairly simple issues then:

- interfaces_ipalias_configure() - and perhaps other similar code for other interface types - should check rc and propagate a user-visible error text if an alias didn't configure. It doesn't error-check, and the silence has led me to believe incorrectly since I set it up, that IP aliases were being created and working.

- If a gateway is _required_ for certain types, as the help text states, then firewall_virtual_ip_edit.php should raise an error is an alias is defined on such an interface without a gateway. This is slightly different - the above bullet is if the ifconfig command fails, this bullet is to improve input validation before trying ifconfig.

- Help text is deficient and missing the key info. "For some types a gateway is required" is roundabout wording, and doesn't tell the user what gateway to enter (the user will have the gateway automatically pushed by ISP and has no reason to know it, or may not even know it's being set). For example, is "gateway" here referring to selecting a router gateway to use, not the ISP gateway? If it means a router gateway, then it is  easier to have a gateway selector dropdown. But if it means the ISP's gateway, what to enter if the ISP gateway is dynamic?

- It's simpler to define the VIP on the underlying interface _even if it could be defined on the PPP interface_: no gateway needed at all. It seems to work (?), much simpler, no gateway needed.  Maybe  encourage users to do that instead, even if technically "the wrong interface"?

Maybe a help text edit would be beneficial? _"Certain types of interface (PPP, PPPoE, tun) require a gateway to be entered here. This should be [ your ISP's gateway | either your ISPs gateway or a local gateway ].  In such cases, or if the gateway is unknown or dynamic, it may be simpler to define the Virtual IP on the underlying interface instead, which usually does not need a gateway to be entered."_ I'm not sure of the exact wording, but perhaps some enhanced help text like this would help a lot, whatever else is done.

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository, 
please read https://github.com/opnsense/core/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue, 
just let us know, so we can reopen the issue and assign an owner to it.
