### ISSUE TITLE
ntpd not starting up at all, works after disabling ntpdate_sync_once.sh

### ISSUE THREAD

**Issue by hkirschk** [opnsense/core#3258]
On my system ntpd did not start at all. What I saw was that script ntpdate_sync_once.sh was called very often (every 10 seconds) to set the system time, but ntpdate itself failed with:

`ntpdate[61668]: 37.58.57.238 rate limit response from server.`

This in consequence prevented ntpd.inc (which started ntpdate_sync_once.sh) to start up ntpd at all. As I assume, the error message above is raised by ntpdate requesting an update from the ntp server(s) too frequently. This in turn happened on my system because ntpdate_sync_once.sh was called very often (every 10 seconds), i.e. in the moment the scipt ntpdate_sync_once.sh terminated, it was called anew again. So there was no chance to get rid of that error message, since the frequency of ntpdate requests remained high.

Not sure if reproducing is that easy. My system is a relatively fresh setup (before I was using pfsense for 2+ years). I don't know the trigger which caused calling ntpdate_sync_once.sh that frequently, I assume it is somewhat linked to newwanip being called, and that was also called frequently due to a misconfiguration of my Dynamic DNS service (fixed in the meantime).

The expected behaviour is that ntpdate_sync_once.sh does only moderate calls by ntpdate to the ntp server(s), preventing it from receving the rate limit response.

An example from ntpd.log:

```
Feb 26 19:13:34 opnsense-wan ntpdate[44331]: 176.221.42.125 rate limit response from server.
Feb 26 19:14:42 opnsense-wan ntpdate[3829]: 37.58.57.238 rate limit response from server.
Feb 26 19:14:53 opnsense-wan ntpdate[61668]: 37.58.57.238 rate limit response from server.
Feb 26 19:15:04 opnsense-wan ntpdate[2123]: 37.58.57.238 rate limit response from server.
Feb 26 19:15:13 opnsense-wan ntpdate[22885]: 37.58.57.238 rate limit response from server.
Feb 26 19:15:23 opnsense-wan ntpdate[79016]: 37.58.57.238 rate limit response from server.
Feb 26 19:15:33 opnsense-wan ntpdate[31828]: 37.58.57.238 rate limit response from server.
Feb 26 19:15:43 opnsense-wan ntpdate[21766]: 37.58.57.238 rate limit response from server.
Feb 26 19:15:54 opnsense-wan ntpdate[79775]: 37.58.57.238 rate limit response from server.
Feb 26 19:16:05 opnsense-wan ntpdate[32479]: 37.58.57.238 rate limit response from server.
Feb 26 19:16:14 opnsense-wan ntpdate[23447]: 37.58.57.238 rate limit response from server.
Feb 26 19:16:23 opnsense-wan ntpdate[77773]: 37.58.57.238 rate limit response from server.
Feb 26 19:16:23 opnsense-wan ntpdate[77773]: 129.70.132.34 rate limit response from server.
Feb 26 19:16:33 opnsense-wan ntpdate[90706]: 37.58.57.238 rate limit response from server.
Feb 26 19:16:44 opnsense-wan ntpdate[90738]: 37.58.57.238 rate limit response from server.
Feb 26 19:16:54 opnsense-wan ntpdate[71957]: 37.58.57.238 rate limit response from server.
```

As additional information, I fixed this behaviour by effectively disabling ntpdate_sync_once.sh by inserting an `exit 0' line near the beginning of the script, i.e. disabling the script, doing nothing at all. After that, ntpd starts up correctly and seems to work properly:

```
# ps aux|grep ntpd
root    64279   0.0  0.8 1063844  6272  -  Ss   08:02     0:03.70 /usr/local/sbin/ntpd -g -c /var/etc/ntpd.conf -p /var/run/ntpd.pid
# ntpq -p
     remote           refid      st t when poll reach   delay   offset  jitter
==============================================================================
*node2.eriomem.n 131.188.3.220    2 u   36  128  377   14.336    7.091   0.240
-clients11.arcan 162.23.41.55     2 u   35  128  377   14.412    7.366   1.134
+nbg01.muxx.net  129.69.1.153     2 u   63  128  377   26.689    2.339   0.383
+ntp.jaxxnet.org 85.199.214.102   2 u   32  128  377   13.659    7.002   1.269
```

If at all, the script should only do a single call to ntpdate (with less frequency)l. See also the bug report for pfsense at [https://redmine.pfsense.org/issues/6053](https://redmine.pfsense.org/issues/6053) where the author recommends to remove ntpdate_sync_once.sh completely (which was what I did effectively & solved the problem for me). Since ntpd is started with the `-g' option, a previous time setting by ntpdate seems to be redundant anyway.

My system:

- OPNsense 19.7.a_39-amd64, FreeBSD 11.2-RELEASE-p8-HBSD, OpenSSL 1.0.2q 20 Nov 2018
- opnsense running as bhyve guest on FreeNAS 11.2
- Supermicro A1SAi
- Network virtio-net

**Comment by AdSchellevis** [comment]
timeout (https://github.com/opnsense/core/blob/master/CONTRIBUTING.md)
