### ISSUE TITLE
Double layer Openvpn and WAN reconnecting

### ISSUE THREAD

**Issue by ofit** [opnsense/core#3259]
Hello guys.
I use Double layer Openvpn on Opnsense, but when WAN changing IP (i mean reconnecting) OpenVPN_2 not start inside OpenVPN_1. OpenVPN_1 up ok. I need manually start OpenVPN_2 almost every time.
I think bug because OpenVPN_2 do not wait until  OpenVPN_1 up and stop at all. Please fix this bug. Thanks

This bug was on 19.1 and 18.7+ versions.
Double layer Openvpn -> OpenVPN_2 inside OpenVPN_1
OpenVPN_1 and OpenVPN_2 use UDP and AES
WAN is pppoe connetion that recconnect and get new ip one time in 2-3 days

Post on forum.opnsense.org
https://forum.opnsense.org/index.php?topic=11829

**Comment by fichtner** [comment]
It's better to keep this in one thread... two issues with "double layer openvpn" in title from same author https://github.com/opnsense/core/issues/3236
