### ISSUE TITLE
Unbound: Alias support

### ISSUE THREAD

**Issue by MarkNBroadhead** [opnsense/core#3260]
Greetings,

I have read the contributing guidelines and searched existing issues. My feature request is related to a problem I have. PfSense has a feature that is extremely convenient for me and it is keeping me from moving to OpnSense. I want to move to OpnSense. I have a docker server with many images behind a proxy that routes based on hostname. When I add a new image, I add a new DNS record for that image. All images have the same IP address. Changing this IP address is tedious with dozens of A records. 

I would like the ability to create multiple A records in Unbound from one DNS override entry, tied to multiple dns name aliases. This would allow one IP address change to affect multiple records, giving the flexibility of a CNAME record in configuration.
This would be implemented in the GUI in the same fashion as the Dnsmasq aliases, but would, on the back-end, create multiple A records instead of CNAME records.

This is implemented in the following PfSense files:
[GUI to add Overrides and their aliases - services_unbound_host_edit.php](https://github.com/pfsense/pfsense/blob/0b4c14a491664053aad3cc76e1ffd67b70ff2da1/src/usr/local/www/services_unbound_host_edit.php)
[GUI listing DNS overrides and their aliases, also post page - services_unbound.php](https://github.com/pfsense/pfsense/blob/0b4c14a491664053aad3cc76e1ffd67b70ff2da1/src/usr/local/www/services_unbound.php)
[Backend service for creating configuration](https://github.com/pfsense/pfsense/blob/7e8bfed216304b37342a0800eb35ef7c29546f5d/src/etc/inc/unbound.inc)

The aliases are also stored in config.xml. I would post more but I have not dug into how that system works.

A screenshot of how this is represented in the GUI:
![image](https://user-images.githubusercontent.com/7092769/53543312-84b3ba80-3adf-11e9-825b-a07d5b955bd6.png)

Alternatives I have considered: Doing it all with A records, switching to Dnsmasq dns, SSHing into the box and using vi find & replace in the configuration for the one IP address.

**Comment by fichtner** [comment]
Hi @MarkNBroadhead,

Sorry, maybe I misunderstand you. I'm not sure how the feature works and technically I can't derive it from your description / requirement, but I'll take a look as per our discussion via: https://github.com/opnsense/core/issues/1041


Cheers,
Franco

**Comment by fichtner** [comment]
Looking at this further I see two things:

Aliases are a mere convenience feature to not type the IP multiple times.
Aliases are flushed to the /etc/hosts file so that they work regardless of the firewall using its own resolver.

Can you tell me how this doesn't work on OPNsense in your use case. I want to help, but I don't see the technical issue and maybe we can find the correct setup or add something that makes things work correctly in your end. At the moment, I still don't see the need for this.


Thanks,
Franco

**Comment by fichtner** [comment]
Oh wait so all you need is a way to enter multiple host names here?

<img width="744" alt="screenshot 2019-02-28 at 8 44 34 am" src="https://user-images.githubusercontent.com/1915288/53549736-4ba63500-3b35-11e9-833c-064c3d6362be.png">

**Comment by MarkNBroadhead** [comment]
I'd be happy to walk you through it in more detail if it would help.

**Comment by fichtner** [comment]
Ah, ok, sure. I didn't even know Dnsmasq host overrides supported this... oO

**Comment by fichtner** [comment]
@MarkNBroadhead work in progress:

    # opnsense-patch 8143857

What do you think?

**Comment by fichtner** [comment]
@MarkNBroadhead if there's no feedback it'll likely be merged in 19.1.4.

**Comment by MarkNBroadhead** [comment]
Have tested, this works _exactly_ as I had hoped. Thank you so much!!!

**Comment by fichtner** [comment]
Yay, no problem. I’ll try to squeeze this into the upcoming 19.1.3 then as the impact is pretty low for existing installs.

Thanks for bearing with me. 😊

**Comment by MarkNBroadhead** [comment]
Sure thing. One question. I'm not sure how installs go. Will I need to revert these files before I upgrade to 19.1.3 or will the upgrade copy over the files?

Dude, no apologies required. I'm shocked you cranked this out so quickly. You rock!

**Comment by fichtner** [comment]
If the code is in 19.1.3 you won't have to do anything other than upgrade. If it's not in 19.1.3 and you upgrade you lose the functionality but not your settings. In the latter case a patch reapply will suffice to bring it back.
