### ISSUE TITLE
Add separator to firewall rules for a better overview.

### ISSUE THREAD

**Issue by kongreddgrass** [opnsense/core#3262]
[yes] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[yes] I have searched the existing issues and I'm convinced that mine is new.

**Is your feature request related to a problem? Please describe.**
Sometimes i lose track of the many firewall rules (about 50 rules per interface). I like the already existing categorization of the rules, but they make it more difficult to recognize the order of the rules.

**Describe the solution you'd like**
I would like to have the possibility to add separators for a better overview. A separator should contain a description. Whether a separator can be assigned a color (similar to pfSense) would not even matter to me. 

**Describe alternatives you've considered**
...

**Additional context**
...

**Comment by AdSchellevis** [comment]
won't work, categories don't affect evaluation order (only serve as filter). please use our feature request template to request new features....

**Comment by kongreddgrass** [comment]
> 
> 
> won't work, categories don't affect evaluation order (only serve as filter). please use our feature request template to request new features....

Thank you very much for the quick answer. I thought you couldn't combine categories with separators. 

I have just edited / adapted the feature request according to your specifications.

**Comment by siedler2** [comment]
+1
Visually grouping rules would be a great improvement for large filter sets.
For me, colouring groups would be a nice addon, to show which rules are more or less critical, for example.
Additionally, folding groups could help to obtain a better overwiew!

**Comment by unipacket1** [comment]
Agree this would be a great feature add :smile:

**Comment by QuoxelNet** [comment]
This would be a great feature for me, too!

**Comment by Safranil** [comment]
+1, I miss this feature too.

**Comment by fichtner** [comment]
I want to be clear: This was discussed internally a number of times and we want to focus on functional improvements. The separator does not fall into this category so no work will be done from the core team on this. There are far more important issues than this and +1 asking will *not* magically change this.

**Comment by fichtner** [comment]
Closing since no contributor is assinged according to https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
