### ISSUE TITLE
Auth for Parent Proxy

### ISSUE THREAD

**Issue by Kornexl** [opnsense/core#3264]
We use opnsense in version OPNsense 19.1.1-amd64

We use the Parent Proxy feature to configure a parent proxy. Our parent needs authentification
 
`
cache_peer <host_parent> <port> <port2> <some parameters> login=<user:pass>
`
It would be nice if these parameters and the credentials would be configurable in the browser.
Now i have to change this line in parentproxy.conf or in the template.
These changes will be overwritten by updates.

**Comment by AdSchellevis** [comment]
????

**Comment by Kornexl** [comment]
I clicked too early
We have to use a parent proxy but with authorization 
cache_peer host parent 3128 0 no-query <some parameters> login=<user:pass>

It would be nice if these parameters and the credentials would be configurable in the browser.
Now i have to change this line in parentproxy.conf or in the template

**Comment by AdSchellevis** [comment]
things happen, better to open a new issue or edit the text then :)

**Comment by mimugmail** [comment]
I can add this tomorrow ...
