### ISSUE TITLE
Transparent Proxy:  Destination in proposed redirection rule 

### ISSUE THREAD

**Issue by mschilt** [opnsense/core#327]
Was locking me out of the WebUI when quickly trying out the new 'transparent proxy' feature. 
I am not sure what happened but I believe that my connection to the Opnsense WebUI was redirected to squid. 

Wouldn't it be better to change the rule destination of the proposed redirecting rule to "!LAN Address" instead of "any" so traffic to the FW never gets redirected. This should of course need to be done for both HTTP and HTTPS.

**Comment by AdSchellevis** [comment]
Just checked it, maybe we should add an extra (internal) rule for the "anti lockout rule" to prevent redirection for traffic directed at the firewall itself. 
(similar to the ones in there for the filter)

**Comment by AdSchellevis** [comment]
added anti lockout on redirects in https://github.com/opnsense/core/commit/0b41c4c959f2d1b235984c5dd51bddb8d1f07325

**Comment by fichtner** [comment]
@AdSchellevis Good idea. It would be great if the rule would show up in the GUI as well like it does for the other anti-lockout rule?

**Comment by AdSchellevis** [comment]
@fichtner Yes it would, I will try to fix this when I'm re-factoring that page later this week.
