### ISSUE TITLE
[Feature Request] Create secret key/cert, with downloading secret key and without saving secret key

### ISSUE THREAD

**Issue by nhirokinet** [opnsense/core#3272]
**Imortant notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[v] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[v] I have searched the existing issues and I'm convinced that mine is new.

**Is your feature request related to a problem? Please describe.**

OpenVPN for Android seems not to have a menu to create PKI key pair. I (and most Android users, I guess) did not install, or feel hard to install, terminals apps avaiable to use `openssl` commands.

Currently I do in the system **other than OPNsense**:

- Create key pair and CSR on laptop
- Sign a CSR on CA
- Copy private key, CSR, and ovpn files to SD card or equivalent area of Android device
- Import ovpn file in OpenVPN for Android, and remove credentials as this is visible for all apps in the device
- Erase credentials from laptop

This seems to be not too bad, but I think it is not the best for the very nice web UI implemented in OPNsence.

**Describe the solution you'd like**

Procedures like:

- Create private key/CSR pair in web UI (within one page, not saved anywhere)
- Download the private key (credentials saved only in clients)
- Press some button (I guess this is written "Next")  that makes private key downloading link not available anymore (note that stopping here makes nothing; the private key is just a useless file here)
- Seemlessly sign CSR and certificates are added to certmanager, where config.xml is modified first in this procedure (This makes this operation meaning, and this is commited to OPNsense storage)
- Then the secret key is available only for the admin who did this procedures (and the admin who broke into process protection or broke system, if any), and trusted by the CA cert

With conditions that no credentials are written into disk/SSD of OPNsense except for swaps.

**Describe alternatives you've considered**

There might be multiple choices:

- Plan 1: adding "download secret key and fix CSR" button to the screen added in #3234 
- Plan 2: adding some sub-menus to "Create an internal Certificate" menu
- Plan 3: adding additional menu to "Method" in system_certmanager.php
- Plan 4: create certificate like before. Just add "erase private key".
  - First I thought this, but this is not good that this remains in System > Configuration > Backups unless deleting explicitly.

There plans differs in a view point of implementation. Also, there may be some other better opinion.

**Additional context**

I'm willing to write codes and make a pull request after #3234 is merged, as long as no one else does it earlier than me; not preventing someone willing to write a code for this issue, of course.

I'm waiting for comments, especially for which plan seems good.

**Comment by AdSchellevis** [comment]
@nhirokinet Isn't what your looking for just an "internal certificate"? The scenario I'm familiar with is the one we've described here https://docs.opnsense.org/manual/how-tos/sslvpn_client.html Or are you looking for something else? (if so can you dump the openssl commands in the order you're using them for your scenario)

**Comment by nhirokinet** [comment]
It is almost the same as "internal certificate". Only the difference is the secret key is saved only onto client's download folder, and not onto the server (so that server does not lead to key compromise anymore).

**Comment by AdSchellevis** [comment]
I wouldn't mind adding some checkbox for local download only onto the existing feature, but let's try to keep it simple. If you want to create a proposal, be my guest, I'll take a look when it's there.

**Comment by nhirokinet** [comment]
Okay, currently it seems of 4 ideas I wrote on the descrpiption of this issue, it seems I'd take "Plan 2: adding some sub-menus to "Create an internal Certificate" menu", with trying to keep as simple as possible. "Sub-menu" here would be a button or checkbos.

I'll make a pull request when some proposal is available. If someone wants to comment something before the pull request opens, please comment here.

**Comment by nhirokinet** [comment]
Pull request above solved this feature request.
