### ISSUE TITLE
FR: Set IP of CSO during OpenVPN authentication using LDAP attributes

### ISSUE THREAD

**Issue by EugenMayer** [opnsense/core#3274]
I am currently, with 18.1 using a custom API to generate local CCDs ( CSO ). Seeing that 19.1 no handles CSO dynamically on auth, i have checked the `IAuthConnector ` implementation of ldap

https://github.com/opnsense/core/blob/master/src/opnsense/mvc/app/library/OPNsense/Auth/LDAP.php#L468 

since that is the API triggered for the CSO attribute mapping using `$authenticator->getLastAuthProperties()`

https://github.com/opnsense/core/blob/master/src/etc/inc/plugins.inc.d/openvpn/auth-user.php#L128

**Question:** 
Am i right that basically all available LDAP attributes on the user being fetched are mapped into the hashmap that is then fetched by e.g. the CSO api with `$authenticator->getLastAuthProperties()`

https://github.com/opnsense/core/blob/master/src/opnsense/mvc/app/library/OPNsense/Auth/LDAP.php#L474

So whatever i have in LDAP, its part of that hashmap. That said, what would be the key i would need to set in ldap to map this to the client ip? Looking up https://github.com/opnsense/core/blob/master/src/etc/inc/plugins.inc.d/openvpn/auth-user.php#L60 i guess it would need to be `Framed-IP-Address` and `Framed-IP-Netmask` , right?

Now i am neither sure ldap would return those values case-sensitive nor i am not sure a field name like `Framed-IP-Address` would be allowed anyway. 

**Suggestion**
This said, i would like to either add a PR to map the "usual/common" ldap based ip/network defintion to https://github.com/opnsense/core/blob/master/src/etc/inc/plugins.inc.d/openvpn/auth-user.php#L57
 or alternatively have an extendable api so one can define the attribute mapping themself.

For the former i know `ipHostNumber` and `ipNetmaskNumber` for the netmask from the `ipHost` schema. Since we hardcoded the values for Radius in here, we might as well do that for ldap (for now) until having either an api like the latter or whatever suits you best. 

I would happily provide a PR for the former, but just wanted to know if that is something you guys would consider / i understood it right / it is desired. Thanks!

**Comment by EugenMayer** [comment]
for an reference I tried to look up if `ipHostName` is an actual standard, which is rfc2307bis:
- https://wiki.archlinux.org/index.php/LDAP_Hosts
- https://docs.microsoft.com/en-us/windows/desktop/adschema/c-iphost
- https://tools.ietf.org/html/draft-howard-rfc2307bis-02
- https://ldapwiki.com/wiki/SchemaRFC2307Bis

So it at least seems there has been an official draft and quite some implementations of it with some few differences, while the attributes named here seem to be the absolute CORE of it.

From my POV it might be considered a good reason for a default, being part of the default scheme set in openlap and Microsoft active directorie.

So implementing those hard-coded similar to Freeradius would help a common ground of people.

**Comment by AdSchellevis** [comment]
History about this should be here https://github.com/opnsense/core/issues/2076, https://github.com/opnsense/core/pull/2084, https://github.com/opnsense/core/issues/2348 , I'm not sure the https://tools.ietf.org/html/draft-howard-rfc2307bis-02 actually means the same as https://tools.ietf.org/html/rfc2865#page-34. 

If it does we could support the additional properties in https://github.com/opnsense/core/blob/master/src/etc/inc/plugins.inc.d/openvpn/auth-user.php#L57.

It would help if we could find some real world implementations, such as original supported openvpn connectors implementing the proposed standard.

Your last report (a year ago), did cost me a lot of time to workout the actual intended (rfc) behaviour, in stead of your proposed solution. I don't intend to do so at the moment, without solid documentation and references to real world implementations.

**Comment by EugenMayer** [comment]
#2076 is freeradius and most probably the motivation for this implementation right now
#2084 was intended but never accepted since the API changed

#2348 was where Freeradius support actually has been added and you actually did all the work. As you will see, it was not for me or any proposal of mine - my name is not listed there once :)

I opted out in #2076 since the route it took was not at all what i was looking at so i closed it to not drag anybody into it.

This proposal leans to exactly what you already have and most probably designed https://github.com/opnsense/core/blob/master/src/etc/inc/plugins.inc.d/openvpn/auth-user.php#L57 for - if that method is not there to map arbitrary properties (auth properties) but rather only from FreeRadius, why not just call it this way?

Of course https://tools.ietf.org/html/rfc2865#page-34 has nothing to do with the LDAP schema RFC proposed in https://tools.ietf.org/html/draft-howard-rfc2307bis-02 - since the former is for Radius (only) and the latter is for Ldap ( only ).

 https://tools.ietf.org/html/rfc2865#page-34 cannot be implemented in LDAP at all, the attribute naming is not allowed in a directory implementation - so that is by no means a common, service agnostic standard and i doubt there is one.

I think there are standards per services, so a couple for Radius, some other for LDAP and other IPs.

That said, i yet could not find any other standard for IP/Netmask mapping for LDAP other then https://tools.ietf.org/html/draft-howard-rfc2307bis-02 and both big implementations, openldap and Microsoft AD implement that standard by default and AFAICS there is no other way to express IP/netmask in both of them with the default schemes - that sounds at least convincing to me.

Still, i would be open to any other alternative, better scheme or standard for LDAP, if there is any - i cannot find a single alternative so i cannot even compare any.

**Comment by EugenMayer** [comment]
After starting the implementation including a LDAP example server with the proper schemes it seems, that it is rather easy to go with `ipHostNumber` by using `ipHost` scheme, `ipNetmaskNumer` though seems a little complicated.

One needs to add `ipNetwork` as a structural object, which then though means, you no longer can use `person` - the point is, semantically `ipNetwork` does mean "a network" and this does exclude it being `a person`.

In fact, there is not other structural field in openldap for netmask at all - also the whole dhcp* namespace seem not to offer any semantic value for this.

So indeed there seem to be no real standard to add and `ip` AND `netmask` to a person in ldap, the latter being the problematic case.

Right now i would assume the best compromise for now being, to detect, if `ipHostNumber` is in a CIDR annotation and if yes, use this for netmask. Otherwise, if not, `ipNetmaskNumber` needs to be set. This would

  - work in an environment where `ipHostNumer` would be an IP and `ipNetmaskNumber` is for the netmask part - so where people decided to break with the semantic meaning of `ipNetwork`
 - work in an environemtn where `ipHostNumber` is in a CIDR annotation for people decided to rather break the expected "value" in `ipHostNumber` being not an ip, but CIDR

I think this alternatives let the people chose, which they think is best for them while the overall implementation to offer both is rather simple, see https://github.com/opnsense/core/p

**Comment by EugenMayer** [comment]
I would suggest probably closing the issue in favour of the PR #3277 and continue there if anything is needed - @AdSchellevis just as you like

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository, 
please read https://github.com/opnsense/core/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue, 
just let us know, so we can reopen the issue and assign an owner to it.
