### ISSUE TITLE
Development "make mount" (no longer) working

### ISSUE THREAD

**Issue by EugenMayer** [opnsense/core#3276]
With the current 19.1 platform i am not longer able to call `make mount`, it erros with:

```
root@OPNsense:~/core # pwd
/root/core
root@OPNsense:~/core # make mount
Enabling core.git live mount...done
configd not running? (check /var/run/configd.pid).
Starting configd.
limits: /usr/local/opnsense/service/configd.py: No such file or directory
/usr/local/etc/rc.d/configd: WARNING: failed to start configd
*** Error code 1

Stop.
make: stopped in /root/core
```

running mount once again seems to no longer show errors:

```
root@OPNsense:~/core # make mount
root@OPNsense:~/core # 
```

I am using what is described here https://wiki.opnsense.org/development/workflow.html#packages and also worked with 18.x using vagrant automation beforehand - so there might be something that has been changed or maybe i am doing something wrong?

The OPNsense instance is a fresh 19.1 - no configuration changes, just a plain installation booted from https://app.vagrantup.com/eugenmayer/boxes/opnsense/versions/19.1

**Comment by AdSchellevis** [comment]
python 3 conversion, stop configd, mount, start configd

**Comment by EugenMayer** [comment]
@AdSchellevis is that a "not to myself" or should i pick up that information somehow? (not sure how to help out with this yet)

**Comment by fichtner** [comment]
From a release engineering perspective make mount / unmount was a very early way to test changes and has long been superseded by the more robust "make package" as that will take care of installing required dependencies as well as full access to rc boot sequence.

**Comment by EugenMayer** [comment]
@fichtner so the docs probably are outdated at this point? Make package somehow sounds for plugins only - will this work for core too?

Also make package sounds like it would repackage it, not live mount it, so hot-working on the code is not possible then? Thanks!

**Comment by EugenMayer** [comment]
Maybe for further clarification, what i do is 

1. Checking out the core https://github.com/EugenMayer/opnsense-openvpn-ldap-cso/blob/master/makefile#L13
2. Then keeping the core in sync with the vagrant box: https://github.com/EugenMayer/opnsense-openvpn-ldap-cso/blob/master/Vagrantfile#L52
3. Live editing locally, while the code gets synced into the vagrant box 

=> development

**Comment by fichtner** [comment]
the dev guide is from 2015/2016 unfortunately and needs updating

you are correct about repackaging. you can work hot-work the code directly in the installed system instead and use "make collect", or do "make install" from the core.git, or work in core.git and use "make package". there are a number of ways to do it

**Comment by EugenMayer** [comment]
Which way should i pick for that "hot-work"? repackaging on each change sounds not the right way to got for it

what is `make collect` and `make install` - also needs to be triggered on each change, right?

**Comment by fichtner** [comment]
make install is in between make mount / make package... you edit core.git and make install will push it to the system--- but you still have dependency issues worst case

make collect allows you to work in /usr/local and the core.git invoke for collect will pull all the system files into the repository for doing the commit of the changes.

**Comment by fichtner** [comment]
PS: I guess that sometimes make package is needed when dependencies change..otherwise lighter workflows apply to taste

**Comment by EugenMayer** [comment]
i do not have any dependency changes during that, most probably that will be the case for most of the contributors which are working on the core ( rather a core-developer thing ).

So what would be the best way to do it for now - ignoring dependencies - and how would we update the docs for it?

**Comment by fichtner** [comment]
when we talk about the python 3 snafu you have dependency issues because only make package will install python 3 correctly (unless you are on 19.1.2 -devel prior to starting your edits)

**Comment by EugenMayer** [comment]
Still cryptic for me :)

i am on 19.1.0 since there is no ISO for 19.1.2 i guess - i could run a upgrade on packaging.

What would be the manual way:

`pkg install python3` or something? Maybe you could describe it a little briefly so i can try it and we could upgrade the docs

**Comment by fichtner** [comment]
If you use master on 19.1.0 just use "make package" once... there's no point in describing things that are automatically fixed. :)

**Comment by EugenMayer** [comment]
Ah, sure. so `make package` and then mount can be used? Well that is an easy fix for sure. I will try that

**Comment by EugenMayer** [comment]
Well i tried `make package`, while it runs through without any issues, `make mount` right after it fails the exact same way:

```
root@OPNsense:~/core # make mount
Enabling core.git live mount...done
configd not running? (check /var/run/configd.pid).
Starting configd.
Unable to lock on the pidfile.
/usr/local/etc/rc.d/configd: WARNING: failed to start configd
*** Error code 1

Stop.
make: stopped in /root/core
```

Did i miss something?

**Comment by fichtner** [comment]
# service configd restart

Python 3 upgrade is a little bumpier than usual

**Comment by EugenMayer** [comment]
Did not help either:

so what i do is: `make package && service configd restart &&  make mount`
And the last 2 run down like this

```
    opnsense: Stopping configd.
    opnsense: ..done
    opnsense: Starting configd.
```

and right after it now the mount
```
    opnsense: Enabling core.git live mount...
    opnsense: done
    opnsense: configd not running? (check /var/run/configd.pid).
    opnsense: Starting configd.
    opnsense: Unable to lock on the pidfile.
    opnsense: /usr/local/etc/rc.d/configd: WARNING: failed to start configd
    opnsense: *** Error code 1
    opnsense: 
    opnsense: Stop.
    opnsense: make: stopped in /root/core
```

Still not working ;/

**Comment by AdSchellevis** [comment]
https://github.com/opnsense/core/blob/master/README.md

**Comment by fichtner** [comment]
sorry, all this talk about undocumented stuff that is from the past...

instead of "make package" use "make upgrade"

**Comment by EugenMayer** [comment]
I am not sure what is undocumented.. `make mount` is part of the official docs?

if `make upgrade` or `make package` is ancient - which one to use today? i do not have any issues with adopting to the current status quo - but i have no idea what is done right now, since i guess the docs are outdated.

**Comment by fichtner** [comment]
> if make upgrade or make package is ancient - which one to use today?

it's not ancient -.-

**Comment by EugenMayer** [comment]
@fichtner then i am just confused :) I am not sure which on is the "undocumented stuff from the past" then? I got `make mount` from https://docs.opnsense.org/development/workflow.html#packages and `make upgrade` from you here, which is not ancient but something is .. sorry this is entirely confusing :)


anyway, tried `make upgrade`

```
make upgrade
pkg: No package(s) matching opnsense-devel
>>> Cannot find package.  Please run 'opnsense-update -t opnsense-devel'
*** Error code 1

Stop.
make: stopped in /root/core
```

tried to ` opnsense-update -t opnsense-devel` which did quiet something, but `make upgrade` still fails after it.

What i have right now is

`make upgrade && service configd restart &&  make mount`

**Comment by fichtner** [comment]
```
make upgrade
pkg: No package(s) matching opnsense-devel
>>> Cannot find package.  Please run 'opnsense-update -t opnsense-devel'
*** Error code 1

Stop.
make: stopped in /root/core
```

I'm sorry but this is totally ****ed up. You try to retrofit master into a release installation. Make mount will be the one thing that you shouldn't run in those cases as you're going to clobber your system beyond repair sooner or later.

**Comment by EugenMayer** [comment]
Well beside i do not care about the system being frankenstein since it is a vagrant box anyway, what would be the "state of the art" way of developing opnsense core?

a) Starting with a fresh freebsd then install opnsense and go from there?
b) Or just be the one having freebsd as desktop and just "run it here?
c) something else?

**Comment by fichtner** [comment]
1. install 19.1, set firmware settings release type to "development", fetch updates
2. opnsense-code core
3. cd /usr/core
4. make upgrade

**Comment by EugenMayer** [comment]
1. are there any docs on how to do this on the cli?
2. when using a "custom core" repo ( https://eugenmayer/opnsense/core ) since one is working on a feature / contribution branch, how would that look like in this case? Instead of letting it "pull" from remote, can i somehow place the repo into the VM somehow ( to use rsync / local code folder )?

**Comment by fichtner** [comment]
You can set up /usr/core from wherever you like, fully manual or by tool from standard or custom remote:

    # man opnsense-code

**Comment by EugenMayer** [comment]
thanks.

`install 19.1, set firmware settings release type to "development", fetch updates` any docs about this?

After doing make upgrade in /usr/core is `make mount` supposed to work or how are changes in /usr/core applied to the runtime ( or does the runtime symlinks ? )

**Comment by fichtner** [comment]
https://docs.opnsense.org/manual/updates.html?highlight=development#update-settings

I will say no more about make mount as it is clear that it shouldn't be used without proper care. it is provided as is for backwards compat and general foot shooting.

**Comment by EugenMayer** [comment]
Considering the scope of this issue, i would suggest we close it - should we? It is up to you, there is no reason of my side to keep it open, let me know

**Comment by fichtner** [comment]
Ok, please close. I'll find the time to update the dev workflow doc soon.

**Comment by EugenMayer** [comment]
I would have PRed the docs, but i simply do not understand the most recent / state of the art dev workflow and writing docs or even correct the current would be too error prone. Thanks for looking into that when you find time
