### ISSUE TITLE
Login a user to the captive portal by api

### ISSUE THREAD

**Issue by RomanJos** [opnsense/core#3278]
**Hi its my first time here don't hesitate to correct me.**
I've see in the captive portal's default html an ajax request to authenticate the user but there is any solution to give an access to a ip address by the api because some devices don't have a browser or they have but maybe its not compatible etc like some smart tv or gaming devices.

Thanks.

**Comment by fabianfrz** [comment]
first of all, the captive portal supports whitelisting of MAC addresses and yes, this is supported if you insist on doing this:

https://github.com/opnsense/core/blob/master/src/opnsense/mvc/app/controllers/OPNsense/CaptivePortal/Api/SessionController.php#L108
Call
```
POST /api/captiveportal/session/connect/{portal id}
```
Payload:
```json
{"user":"xxx", "ip":"xxx"}
```

**Comment by RomanJos** [comment]
Oh perfect si i just type in the user the voucher id ? in this case its perfect ! thank you !

**Comment by fabianfrz** [comment]
no, in this case you don't even need a voucher.

**Comment by RomanJos** [comment]
But what can i put in the user fields ? i can type anything and it will create a voucher automatically or it will whiteliste this ip but in this case i don't remember that there is a user section; maybe by user you mean user in the System -> Access ->Users but in this case it will not be good because i'm trying to assign a voucher per ip without sending them the voucher code (because some time they can't)
thank you

**Comment by fabianfrz** [comment]
afaik you can enter anything in the user field - it will be shown on the session page to disconnect the user again.

**Comment by RomanJos** [comment]
oh okay so its perfect its like creating a voucher but with a custom name and without a password and also just for an ip but can i put a sort of like "auto-set-fixe-ip with the dhcp so anytime they connect or make dhcp request whatever they get the same ip ?

**Comment by RomanJos** [comment]
i think there is some limitation here because if someone put his ip on static while the one that i give access isn't connected he can steal his access

**Comment by fabianfrz** [comment]
@AdSchellevis @jschellevis Since you worked on that, it is better if you explain that in detail.

**Comment by AdSchellevis** [comment]
There will always some limitations :) If @RomanJos wants to discuss use cases around captive portal, it's probably better to use the forum (https://forum.opnsense.org) for that.

**Comment by RomanJos** [comment]
hmm I have an idea: sometimes I connect to a wifi access point and I'm mostly alone on the network with a crazy address like 251.13.41.59 and I think it's the firewall that assigns me this IP address so it's harder for me to scan the network if I do not let a program run for hours to scan the entire network, do you think Opsense can do that because that will solve all the above problems! or maybe i can assign ipv6 instead of ipv4 because most people do not know how it works but i do not know too lol.

**Comment by RomanJos** [comment]
so yeah i think the best solution for this is an automatic static IP assignment through DHCP. I don't know if its possible but if we can assign some ip in the 10.0.0.0/8 subnet randomly to assign ip like 10.54.6.19 and 10.1.251.125 etc it will be difficult to know the ip and in the wifi antenna i can set an option to disable the icmp echo (it act like a firewall) and it work very well i can't see anybody connected to the network with this option. So if OPNsense can do this i can use the api link provided by @fabianfrz without risk of ip stoling 😃

**Comment by RomanJos** [comment]
So i think this thread is a little died lol but i have found a sort of a solution : if i assign some ip like i normally do but to prevent people to scan the network or whatever i can set an option in the ubiquiti antenna to reject all icmp request etc so the antenna become a small firewall. but if there was a solution to assign a random ip to a devices that will be much better 😄
