### ISSUE TITLE
Traffic Graphs don't follow OPNSense style

### ISSUE THREAD

**Issue by sjorge** [opnsense/core#328]
The red highlights don't fit with the overall orange highlights.

**Comment by fichtner** [comment]
@fabianfrz thanks, looks sweet. any thing else here or close?

**Comment by sjorge** [comment]
Is this in opnsense-devel? If so I will check it out this weekend

**Comment by fichtner** [comment]
It will be in 15.7.12 by default

**Comment by fabianfrz** [comment]
I think @sjorge should decide if we should close it.

**Comment by fichtner** [comment]
a screenshot for reference...

<img width="1060" alt="screen shot 2015-09-11 at 12 38 41" src="https://cloud.githubusercontent.com/assets/1915288/9813010/1e397e36-5882-11e5-9dbf-0490f8b7a917.png">

**Comment by sjorge** [comment]
Looks good to me
