### ISSUE TITLE
Linux and macOS Do Not Get the IPv6 Address in their Reservation

### ISSUE THREAD

**Issue by SirWobbyTheFirst** [opnsense/core#3280]
I have OPNsense setup in my network with IPv4 and IPv6 enabled both on the LAN and WAN side, all devices get an IPv4 and IPv6 address and are able to talk to the resources on the network and Internet using both protocols with no issue.

For some of my devices, I have DHCPv4 and DHCPv6 reservations set up and for most of these devices, both reservations work but I have noticed that only Windows respects them, I have a vCenter 6.7 VCSA setup and that will not respect the DHCPv6 reservation I have set up. When I go into the DHCPv6 Leases section of the dashboard, I can see two entries for the same DUIDs but with different IPv6 addresses.

If I go into the console of the VCSA, I also see that it is not getting the correct IPv6 address, I initially thought this was an issue with the VCSA but it seems macOS does not get the correct IPv6 address. If I set the addresses they get as the reserved address, then when the lease expires, they get a new IPv6 address altogether.

As seen in the attached screenshot for the VCSA, both entries have the same DUID and MAC address but the reservation never switches to active. And the same happens to macOS, only Windows gets the correct reservation, both the VCSA and macOS are on a stock configuration to rule out something I did.

![image](https://user-images.githubusercontent.com/47334951/53695028-7bac3d00-3dae-11e9-9df5-332b954700bb.png)

**Comment by maurice-w** [comment]
The screenshot seems to show a DUID-EN (`00:02`) generated by systemd (`00:00:ab:11`). But it has a `b6` prefix which makes no sense. What DUID is shown in the vCSA console?

**Comment by SirWobbyTheFirst** [comment]
I cannot find out, the one command available in Photon OS doesn’t produce any output. 😂 But I spun up a Windows Server DHCP Server and in the DHCP manager console, the B6 is not presented by both Photon OS, the VCSA and macOS and reservations work just fine using that.

**Comment by maurice-w** [comment]
My guess would be that the OPNsense GUI has some issue displaying certain DUIDs correctly. Now if you use an incorrectly displayed DUID to create a static mapping... things go wrong.
Try saving the static mappings with the correct DUID and see if it works. All valid DUIDs start with `00:01`, `00:02`, `00:03` or `00:04`.

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository, 
please read https://github.com/opnsense/core/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue, 
just let us know, so we can reopen the issue and assign an owner to it.
