### ISSUE TITLE
system: when monitoring is disabled gateway force down is ignored

### ISSUE THREAD

**Issue by AndyX90** [opnsense/core#3281]
My Environment:
  19.1.2 on DEC4630
  WAN: 
    - Tier 1 - PPPoE
    - Tier 2 - static
  OpenVPN:
    - one client to remote site

Problem:
OpenVPN-Client-Gateway becomes default Gateway, even if in MWAN configuration the GW is set to "NEVER".
 
NOTE: 
- System -> Gateways -> Single = WAN - default
- System -> Routes -> Status = OpenVPN-Client Gateway - default
- GW-Monitoring on VPN-Gateway is disabled.

**Comment by AdSchellevis** [comment]
could be related to https://github.com/opnsense/core/issues/2279, although there's not a lot of information in the ticket. Could you please use our templates to create issues and/or feature requests?

**Comment by mimugmail** [comment]
Just tick Mark Gateway as down in OpenVPN gateway ...

**Comment by AndyX90** [comment]
Thanks for Your quick replies.
Okay, sorry for not using your template.

The problem only appears since the upgrade to 19.1.

Here some logs:
`Feb 25 13:34:50	opnsense: /usr/local/etc/rc.openvpn: OpenVPN: One or more OpenVPN tunnel endpoints may have changed its IP. Reloading endpoints that may use MROFallback.
Feb 25 13:34:50	opnsense: /usr/local/etc/rc.filter_configure: Cannot switch while 0 inet6 gateways are up
Feb 25 13:34:50	opnsense: /usr/local/etc/rc.filter_configure: ROUTING: keeping current default gateway 'X.X.X.X'
Feb 25 13:34:40	opnsense: /usr/local/etc/rc.openvpn: OpenVPN: One or more OpenVPN tunnel endpoints may have changed its IP. Reloading endpoints that may use MROFallback.
Feb 25 13:34:39	opnsense: /usr/local/etc/rc.filter_configure: Cannot switch while 0 inet6 gateways are up
Feb 25 13:34:39	opnsense: /usr/local/etc/rc.filter_configure: ROUTING: creating /tmp/pppoe0_defaultgw using 'X.X.X.X'
Feb 25 13:34:39	opnsense: /usr/local/etc/rc.filter_configure: ROUTING: removing /tmp/ovpnc2_defaultgw
Feb 25 13:34:38	opnsense: /usr/local/etc/rc.filter_configure: Cannot switch while 0 inet6 gateways are up
Feb 25 13:34:38	opnsense: /usr/local/etc/rc.filter_configure: ROUTING: creating /tmp/ovpnc2_defaultgw using 'Y.Y.Y.Y'
Feb 25 13:34:38	opnsense: /usr/local/etc/rc.filter_configure: ROUTING: removing /tmp/pppoe0_defaultgw
Feb 25 13:34:38	opnsense: /system_gateway_groups.php: Adding static route for monitor 8.8.8.8 via X.X.X.X
Feb 25 13:34:38	opnsense: /system_gateway_groups.php: Removing static route for monitor 8.8.8.8 via X.X.X.X
Feb 25 13:34:38	opnsense: /system_gateway_groups.php: ROUTING: skipping IPv6 default route
Feb 25 13:34:38	opnsense: /system_gateway_groups.php: ROUTING: creating /tmp/pppoe0_defaultgw using 'X.X.X.X'
Feb 25 13:34:38	opnsense: /system_gateway_groups.php: ROUTING: removing /tmp/ovpnc2_defaultgw
Feb 25 13:34:38	opnsense: /system_gateway_groups.php: ROUTING: setting IPv4 default route to X.X.X.X
Feb 25 13:34:38	opnsense: /system_gateway_groups.php: ROUTING: no IPv6 default gateway set, assuming wan
Feb 25 13:34:38	opnsense: /system_gateway_groups.php: ROUTING: IPv4 default gateway set to wan
Feb 25 13:34:38	opnsense: /system_gateway_groups.php: ROUTING: entering configure using defaults
Feb 25 13:34:04	opnsense: /usr/local/etc/rc.newwanip: Cannot switch while 0 inet6 gateways are up
Feb 25 13:34:04	opnsense: /usr/local/etc/rc.newwanip: ROUTING: creating /tmp/ovpnc2_defaultgw using 'Y.Y.Y.Y'
Feb 25 13:34:04	opnsense: /usr/local/etc/rc.newwanip: ROUTING: removing /tmp/pppoe0_defaultgw
Feb 25 13:34:04	opnsense: /usr/local/etc/rc.newwanip: Adding static route for monitor 8.8.8.8 via X.X.X.X
Feb 25 13:34:04	opnsense: /usr/local/etc/rc.newwanip: Removing static route for monitor 8.8.8.8 via X.X.X.X
Feb 25 13:34:04	opnsense: /usr/local/etc/rc.newwanip: ROUTING: skipping IPv6 default route
Feb 25 13:34:04	opnsense: /usr/local/etc/rc.newwanip: ROUTING: skipping IPv4 default route
Feb 25 13:34:04	opnsense: /usr/local/etc/rc.newwanip: ROUTING: no IPv6 default gateway set, assuming wan
Feb 25 13:34:04	opnsense: /usr/local/etc/rc.newwanip: ROUTING: IPv4 default gateway set to wan
Feb 25 13:34:04	opnsense: /usr/local/etc/rc.newwanip: ROUTING: entering configure using 'opt7'
Feb 25 13:34:04	opnsense: /usr/local/etc/rc.newwanip: On (IP address: Y.Y.Y.X) (interface: S2S[opt7]) (real interface: ovpnc2).
Feb 25 13:34:04	opnsense: /usr/local/etc/rc.newwanip: IP renewal is starting on 'ovpnc2'`

**Comment by AndyX90** [comment]
Thanks for Your quick replies.
Okay, sorry for not using your template.

The problem only appears since the upgrade to 19.1.

Here some logs:

> Feb 25 13:34:50	opnsense: /usr/local/etc/rc.openvpn: OpenVPN: One or more OpenVPN tunnel endpoints may have changed its IP. Reloading endpoints that may use Fallback.
Feb 25 13:34:50	opnsense: /usr/local/etc/rc.filter_configure: Cannot switch while 0 inet6 gateways are up
Feb 25 13:34:50	opnsense: /usr/local/etc/rc.filter_configure: ROUTING: keeping current default gateway 'X.X.X.X'
Feb 25 13:34:40	opnsense: /usr/local/etc/rc.openvpn: OpenVPN: One or more OpenVPN tunnel endpoints may have changed its IP. Reloading endpoints that may use Fallback.
Feb 25 13:34:39	opnsense: /usr/local/etc/rc.filter_configure: Cannot switch while 0 inet6 gateways are up
Feb 25 13:34:39	opnsense: /usr/local/etc/rc.filter_configure: ROUTING: creating /tmp/pppoe0_defaultgw using 'X.X.X.X'
Feb 25 13:34:39	opnsense: /usr/local/etc/rc.filter_configure: ROUTING: removing /tmp/ovpnc2_defaultgw
Feb 25 13:34:38	opnsense: /usr/local/etc/rc.filter_configure: Cannot switch while 0 inet6 gateways are up
Feb 25 13:34:38	opnsense: /usr/local/etc/rc.filter_configure: ROUTING: creating /tmp/ovpnc2_defaultgw using 'Y.Y.Y.Y'
Feb 25 13:34:38	opnsense: /usr/local/etc/rc.filter_configure: ROUTING: removing /tmp/pppoe0_defaultgw
Feb 25 13:34:38	opnsense: /system_gateway_groups.php: Adding static route for monitor 8.8.8.8 via X.X.X.X
Feb 25 13:34:38	opnsense: /system_gateway_groups.php: Removing static route for monitor 8.8.8.8 via X.X.X.X
Feb 25 13:34:38	opnsense: /system_gateway_groups.php: ROUTING: skipping IPv6 default route
Feb 25 13:34:38	opnsense: /system_gateway_groups.php: ROUTING: creating /tmp/pppoe0_defaultgw using 'X.X.X.X'
Feb 25 13:34:38	opnsense: /system_gateway_groups.php: ROUTING: removing /tmp/ovpnc2_defaultgw
Feb 25 13:34:38	opnsense: /system_gateway_groups.php: ROUTING: setting IPv4 default route to X.X.X.X
Feb 25 13:34:38	opnsense: /system_gateway_groups.php: ROUTING: no IPv6 default gateway set, assuming wan
Feb 25 13:34:38	opnsense: /system_gateway_groups.php: ROUTING: IPv4 default gateway set to wan
Feb 25 13:34:38	opnsense: /system_gateway_groups.php: ROUTING: entering configure using defaults
Feb 25 13:34:04	opnsense: /usr/local/etc/rc.newwanip: Cannot switch while 0 inet6 gateways are up
Feb 25 13:34:04	opnsense: /usr/local/etc/rc.newwanip: ROUTING: creating /tmp/ovpnc2_defaultgw using 'Y.Y.Y.Y'
Feb 25 13:34:04	opnsense: /usr/local/etc/rc.newwanip: ROUTING: removing /tmp/pppoe0_defaultgw
Feb 25 13:34:04	opnsense: /usr/local/etc/rc.newwanip: Adding static route for monitor 8.8.8.8 via X.X.X.X
Feb 25 13:34:04	opnsense: /usr/local/etc/rc.newwanip: Removing static route for monitor 8.8.8.8 via X.X.X.X
Feb 25 13:34:04	opnsense: /usr/local/etc/rc.newwanip: ROUTING: skipping IPv6 default route
Feb 25 13:34:04	opnsense: /usr/local/etc/rc.newwanip: ROUTING: skipping IPv4 default route
Feb 25 13:34:04	opnsense: /usr/local/etc/rc.newwanip: ROUTING: no IPv6 default gateway set, assuming wan
Feb 25 13:34:04	opnsense: /usr/local/etc/rc.newwanip: ROUTING: IPv4 default gateway set to wan
Feb 25 13:34:04	opnsense: /usr/local/etc/rc.newwanip: ROUTING: entering configure using 'opt7'
Feb 25 13:34:04	opnsense: /usr/local/etc/rc.newwanip: On (IP address: Y.Y.Y.X) (interface: S2S[opt7]) (real interface: ovpnc2).
Feb 25 13:34:04	opnsense: /usr/local/etc/rc.newwanip: IP renewal is starting on 'ovpnc2'

**Comment by mimugmail** [comment]
> Just tick Mark Gateway as down in OpenVPN gateway ...

You did this?

**Comment by AndyX90** [comment]
> > Just tick Mark Gateway as down in OpenVPN gateway ...
> 
> You did this?

Not yet. I will try and report.

**Comment by AndyX90** [comment]
I set "Mark Gateway as Down" but it has no impact.
Default route is still set to VPNGW afterwards.
The only thing what helps is to manually give it a weight below the other gateways...
Btw. "Mark Gateway as Down" still displays it as online on Dashboard - Gateways...

**Comment by mimugmail** [comment]
@fichtner did something changed on this? Today I had a similar problem where a gateway which was marked as down was chosen as default :/

**Comment by fichtner** [comment]
I'm not sure where the bug should be. No fundamentally shifting work was done for #2279 -- maybe an apinger vs. dpinger oddity?

**Comment by mimugmail** [comment]
I have some crazy log regarding dpinger:

```
Feb  6 11:14:28 pmg-fw1 dpinger: send_interval 1000ms  loss_interval 2000ms  time_period 60000ms  report_interval 0ms  data_len 0  alert_interval 1000ms  latency_alarm
500ms  loss_alarm 20%  dest_addr 17.21.68.26  bind_addr 17.21.68.36  identifier "GW_WAN "
Feb  6 11:14:28 pmg-fw1 dpinger: send_interval 1000ms  loss_interval 2000ms  time_period 60000ms  report_interval 0ms  data_len 0  alert_interval 1000ms  latency_alarm
500ms  loss_alarm 20%  dest_addr 17.21.68.27  bind_addr 17.21.68.36  identifier "GW_WAN2 "
Mar  6 10:43:30 pmg-fw1 dpinger: send_interval 1000ms  loss_interval 2000ms  time_period 60000ms  report_interval 0ms  data_len 0  alert_interval 1000ms  latency_alarm
500ms  loss_alarm 20%  dest_addr 17.21.68.26  bind_addr 17.21.68.36  identifier "GW_WAN "
Mar  6 10:43:30 pmg-fw1 dpinger: send_interval 1000ms  loss_interval 2000ms  time_period 60000ms  report_interval 0ms  data_len 0  alert_interval 1000ms  latency_alarm
500ms  loss_alarm 20%  dest_addr 17.21.68.27  bind_addr 17.21.68.36  identifier "GW_WAN2 "
Mar  6 11:09:56 pmg-fw1 dpinger: send_interval 1000ms  loss_interval 2000ms  time_period 60000ms  report_interval 0ms  data_len 0  alert_interval 1000ms  latency_alarm 500ms  loss_alarm 20%  dest_addr 17.21.68.26  bind_addr 17.21.68.36  identifier "GW_WAN "
Mar  6 11:09:56 pmg-fw1 dpinger: send_interval 1000ms  loss_interval 2000ms  time_period 60000ms  report_interval 0ms  data_len 0  alert_interval 1000ms  latency_alarm 500ms  loss_alarm 20%  dest_addr 17.21.68.27  bind_addr 17.21.68.36  identifier "GW_WAN2 "
Mar  6 11:09:57 pmg-fw1 dpinger: GW_WAN 17.21.68.26: Alarm latency 140us stddev 0us loss 50%
Mar  6 11:09:57 pmg-fw1 dpinger: GATEWAY ALARM: GW_WAN (Addr: 17.21.68.26 Alarm: 1 RTT: 140ms RTTd: 0ms Loss: 50%)
Mar  6 11:10:08 pmg-fw1 dpinger: GW_WAN 17.21.68.26: Clear latency 135us stddev 31us loss 0%
Mar  6 11:10:08 pmg-fw1 dpinger: GATEWAY ALARM: GW_WAN (Addr: 17.21.68.26 Alarm: 0 RTT: 135ms RTTd: 31ms Loss: 0%)
^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@
```

**Comment by AndyX90** [comment]
Very confusing. In my case, it should never use this gateway.

**Comment by mimugmail** [comment]
@AndyX90 Did changing the weight fixed it for the moment (cause of script restart) is it reproducable fixed?

**Comment by AndyX90** [comment]
Sorry for the late reply. Yes, setting the weight of the VPN-Gateway above the other ones fixes it temporary.

**Comment by mimugmail** [comment]
Temporary? So it might only be the restart of the script and not the setting of the weight, correct?

**Comment by AndyX90** [comment]
No, sorry. It fixes the problem.
But with temporary i mean that it should be a temporary solution, because the setting "NEVER" should exclude this gateway in Multiwan-Configuration.

**Comment by mimugmail** [comment]
when @fichtner and I were hunting this one my initial wish was to use the weight in advanced gateway config to set a priority how gateways are switched .. but we didn't find the time yet to optimize this behavior

**Comment by fichtner** [comment]
If you use default gateway switching you need to set mark gateway down. There is no way around this at the moment until the default gateway switching via gateway group is implemented.
