### ISSUE TITLE
New OpenVPN Client Export Broken

### ISSUE THREAD

**Issue by xenorites** [opnsense/core#3283]
The new version of the client export has several missing features, and produces currently unusable config files.

For example, you are now unable to have a client export that will use the Windows certificate store instead of a cert file. Also, for some reason it capitalizes "TCP" and "UDP" for the protocol, which many clients do not like.

**Comment by AdSchellevis** [comment]
and you're planning to work on things you're missing?

**Comment by fichtner** [comment]
what @AdSchellevis is trying to say:

* please quantify and qualify "several missing features"
* please qualify "unusable config files"
* please tell us if you have tested the latest version19.1.2 -- at least one bug you mention has been fixed so it would save you the time reporting it ;)


Cheers,
Franco

**Comment by Sovenger** [comment]
I don't know if this was included before, but the docs say there should be an export option named "OpenVPN Connect" but there isn't. See here where the iOS directions list this: https://docs.opnsense.org/manual/how-tos/sslvpn_client.html#ios

Let me know if this is a separate bug and i'll log it as such.

**Comment by AdSchellevis** [comment]
@Sovenger it's more a documentation issue, the iOS app should accept the standard packages if I'm not mistaken. If someone wants to help out fixing the docs, that would be highly appreciated.

**Comment by Sovenger** [comment]
> @Sovenger it's more a documentation issue, the iOS app should accept the standard packages if I'm not mistaken. If someone wants to help out fixing the docs, that would be highly appreciated.

I'm happy to update the docs once we nail down what the process should be. I've tried an additional 4 other steps after the point that I linked you to and still wasn't able to get it to work (e.g. messing around with different certs, reformatting the .ovpn file, and importing the certs to the phone's keychain).

What should the docs say?

**Comment by AdSchellevis** [comment]
@Sovenger can you explain what you've tried on your ios device? I'll try the same steps on my iOS device and see what happens.

**Comment by Sovenger** [comment]
@AdSchellevis sure!

1. Follow all steps in the docs here, https://docs.opnsense.org/manual/how-tos/sslvpn_client.html up to the iOS part
2. From the iOS steps: VPN -> OpenVPN -> Client Export
3. Under Accounts / Certificates section of that screen, click the download arrow icon on the right of the user line
4. Unzip the download somewhere on your desktop. You'll have three files: .key, .ovpn, and a .p12.
5. On your phone, download the OpenVPN Connect app.
6. On your desktop, plug in your phone with a USB cable
7. Open iTunes
8. Click the mini phone icon in the upper left header area
9. Click File Sharing, in the left menu
10. Find and clickon the OpenVPN app
11. In the right pane, scroll down to the bottom and click Add File
12. Find and select all three files to upload
13. May need to click sync, however, mine auto-synced. YMMV
14. Open the OpenVPN app on the phone and it should list both the p12 and .ovpn profiles as ready to import
15. Click "Add" on each of them. The cert will ask you for a password, just hit OK (blank pw)
16. Everything SHOULD be ready now. Click the connect slider on the new profile. It'll try to connect, ask for a password and token, input it and then it'll fail.

**Comment by AdSchellevis** [comment]
ok, just tested this on my device, very easy. 

1. install the ios client (same as you already did)
2. go to the exporter and choose "File Only" which is the default for most embedded device types (this includes all the required cert in text mode)
3. go to iTunes, drop .ovpn profile onto the iOS devive
4. go to the iOS device and connect. 

That's basically all :) 

You can find our docs repository here https://github.com/opnsense/docs

**Comment by Sovenger** [comment]
@AdSchellevis that worked :).

I'll look at getting these documentation changes into a pull request.

@xenorites back to you.

**Comment by AdSchellevis** [comment]
@Sovenger thanks in advance!

**Comment by xenorites** [comment]
Missing features:

- Yealink Phone Export (separate issue exists)
- Inability to use Windows Cert Store

Unusable config issues:

- Having the "Validate server subject" box checked results in a server validation error when attempting to connect - it appears to attempt to use the full subject in the config produced, but this causes issues. Solution was only name verification.
- The config files produced have the protocol capitalized, which neither the Gnome GUI nor the OpenVPN Windows binary support. Solution was lower-case protocols in the config file.

I have not had time to test; only discovered the issues while setting up some new users. I will try and take some time later this week or this weekend to do further digging into any issues or solutions.

**Comment by AdSchellevis** [comment]
timeout

(Windows cert store fixed in https://github.com/opnsense/core/issues/3500)
