### ISSUE TITLE
Multiple Gateway Bug on OPNsense 19.1.2

### ISSUE THREAD

**Issue by sachaz** [opnsense/core#3284]
Related to #2835 I still have the issue on OpnSense v19.1.2:
tried as suggested to Disable force Gateway with no effect

**Comment by sachaz** [comment]
From a firewall rule, when I'm trying to set a gateway the matching traffic is not routed to this gateway.
Here is a rule on lan interface (igb3) that doesn't work (I changed just for here the gateway's IP to $pppoe1_GW ):
pass in quick on igb3 route-to (pppoe1 $pppoe1_GW) inet from (igb3:network) to <Video_VOIP> flags S/SA set ( prio 4 ) keep state label "USER_RULE"

- each WAN interface is replying from outside.
- No default gateway is set.
- Tested with Firewall : Settings : Advanced : Disable force Gateway checked or not

**Comment by fichtner** [comment]
Might have been https://github.com/opnsense/core/issues/3281 ?
