### ISSUE TITLE
[feature request] rc.syshook after update

### ISSUE THREAD

**Issue by thutex** [opnsense/core#3288]
----EDIT----
feature request changed to a more general and useful request for a way to (automatically) run a script after an update.
--------------
I personally like the default theme (more than the alternatives), but do not like the orange color scheme.
Currently i run a modified theme of the default where basically the only things changed, are the orange colors to a more "calm" blue.
however, this ofcourse runs the risk of becoming out of sync with the main theme.

thus, it would be very nice if there would be a menu that would allow us to change the main theme colors from the gui.

**Comment by AdSchellevis** [comment]
sorry, we're not going to do that, theme's don't change very often (an old theme from 17.1 probably still renders fine on 19.1 for example). Replacing only the base colours to your liking isn't a lot of work

**Comment by thutex** [comment]
i understand.
how about, perhaps, an option for a "run after update" command?

**Comment by AdSchellevis** [comment]
run after update? you can copy the theme and select it in System -> Settings  -> General, your choice will be persistent.

**Comment by fichtner** [comment]
I see need for a rc.syshook after update too, but in this case @AdSchellevis is right: copy the "opnsense" directory and adjust to your liking, it will not be touched by the rest of the system / updates.

**Comment by thutex** [comment]
agreed that for the theme we can do that @AdSchellevis .
the "run after update" was intended more general. i will modify the title to reflect the modified feature request (like @fichtner says, a syshook to run after an update.)

in my case, for example, i tend to try changing things through the cli when not (yet) supported in opnsense.
but, when updating the existing config file i made is often overwritten, so an automated way to put that back would be nice.
(its like this i got nut working for my ups through blazer_usb)

**Comment by AdSchellevis** [comment]
@fichtner after update is probably debatable, in theory every package should be self contained, a better question is which feature wasn't pluggable for which a hack-after was needed....

**Comment by fichtner** [comment]
@AdSchellevis it's for when you want to keep patches active with opnsense-patch automatically applied on update. boot-time may not be enough if there is no reboot update

**Comment by AdSchellevis** [comment]
sure, just saying, these things are tricky and can lead to deadlocks / weird support issues nobody understands... not against it in principle, but a bit concerned.

**Comment by thutex** [comment]
@AdSchellevis maybe there is a way for such functionality to log the changed files for troubleshooting purposes?
i.e, maybe we could have a gui wrapper around a script, where you would be able to enter the commands you want executed through the gui and then the actual script would do something like this:

```
find / -type f -mtime -1 > /tmp/beforeupdate.log
-run actual script here-
find / -type f -mtime -1 > /tmp/afterupdate.log
diff -u /tmp/beforeupdate.log /tmp.afterupdate.log > /tmp/updatedchanges.log
```

**Comment by AdSchellevis** [comment]
The syshook change @fichtner suggested probably won't collect this, although the patch utility caches installed ones nowadays. 
A gui to add scripts is something we're not going to consider, we carefully removed all such features over the years for valid reasons :)

**Comment by fichtner** [comment]
we have a health audit, that should be enough to find clobbered / manipulated installed files

hooks can only be accessed from the plugins or command line, you have to know what you are doing

the real question is: what process do you want to use to update the theme files when the syshook is executed? that's the most fragile part ;)

**Comment by thutex** [comment]
for now, i am doing it just with a shell script and sed:

sed -i .orig 's/EA7105/60AADF/g' /usr/local/opnsense/www/themes/opnsense/build/css/main.css
sed -i .orig 's/b85904/4791C6/g' /usr/local/opnsense/www/themes/opnsense/build/css/main.css
sed -i .orig 's/D95100/2D77AC/g' /usr/local/opnsense/www/themes/opnsense/build/css/main.css
sed -i .orig 's/9c3a00/004479/g' /usr/local/opnsense/www/themes/opnsense/build/css/main.css
sed -i .orig 's/ED9A50/93DDFF/g' /usr/local/opnsense/www/themes/opnsense/build/css/main.css
sed -i .orig 's/fedcbd/BDEAFF/g' /usr/local/opnsense/www/themes/opnsense/build/css/main.css

**Comment by fichtner** [comment]
```
Writing firmware setting...done.
Configuring login behaviour...done.
Configuring system logging...done.
>>> Invoking update script 'foo'
Foo!
>>> Error in update script 'foo'
Message from opnsense-devel-19.7.r_6:

Carry on my wayward son
Starting web GUI...done.
```
