### ISSUE TITLE
repo-OPNsense.sqlite failed: No such file or directory

### ISSUE THREAD

**Issue by JasonNaughton** [opnsense/core#3289]
Hi All,

Upgraded from 18.7.7 to 19.1.  The process took abit but on reboot the system came up.   Unfortunately I can no longer update the box after migrating.  Every attempt to do so comes back with:

# pkg update
Updating OPNsense repository catalogue...
pkg: Repository OPNsense load error: access repo file(/var/db/pkg/repo-OPNsense.sqlite) failed: No such file or directory
Certificate verification failed for /C=US/O=Let's Encrypt/CN=Let's Encrypt Authority X3
2803841504888:error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed:/usr/src/crypto/openssl/ssl/s3_clnt.c:1269:
Certificate verification failed for /C=US/O=Let's Encrypt/CN=Let's Encrypt Authority X3
2803841504888:error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed:/usr/src/crypto/openssl/ssl/s3_clnt.c:1269:
Certificate verification failed for /C=US/O=Let's Encrypt/CN=Let's Encrypt Authority X3
2803841504888:error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed:/usr/src/crypto/openssl/ssl/s3_clnt.c:1269:
pkg: https://pkg.opnsense.org/FreeBSD:11:amd64/19.1/latest/meta.txz: Authentication error
repository OPNsense has no meta file, using default settings
Certificate verification failed for /C=US/O=Let's Encrypt/CN=Let's Encrypt Authority X3
2803841504888:error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed:/usr/src/crypto/openssl/ssl/s3_clnt.c:1269:
Certificate verification failed for /C=US/O=Let's Encrypt/CN=Let's Encrypt Authority X3
2803841504888:error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed:/usr/src/crypto/openssl/ssl/s3_clnt.c:1269:
Certificate verification failed for /C=US/O=Let's Encrypt/CN=Let's Encrypt Authority X3
2803841504888:error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed:/usr/src/crypto/openssl/ssl/s3_clnt.c:1269:
pkg: https://pkg.opnsense.org/FreeBSD:11:amd64/19.1/latest/packagesite.txz: Authentication error
Unable to update repository OPNsense
Error updating repositories!

I have internet access as I can ping google as such:

# ping www.google.ca
PING www.google.ca (172.217.13.131): 56 data bytes
64 bytes from 172.217.13.131: icmp_seq=0 ttl=47 time=13.637 ms
64 bytes from 172.217.13.131: icmp_seq=1 ttl=47 time=13.639 ms
64 bytes from 172.217.13.131: icmp_seq=2 ttl=47 time=11.082 ms
^C
--- www.google.ca ping statistics ---
3 packets transmitted, 3 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 11.082/12.786/13.639/1.205 ms

Any way I can get the repo-OPNsense.sqlite rebuilt as it appears not to exist in the folder that I'm attempting to access during an update.

**Comment by thutex** [comment]
just a question... are you doing the pingtest from your machine or from the firewall?
i ask because it seems somewhat similar as to what i experienced with dns for the firewall being on 127.0.0.1 and not working.
can you try to add alias 127.0.0.1 to the loopback interface on firewall - virtual ips - settings and see if that makes a difference ?

**Comment by AdSchellevis** [comment]
perhaps a proxy in between? "Authentication error" suggests it can not access the location. 

You could try to set the mirror manually and choose `http://pkg.opnsense.org` which was our previous default.

**Comment by fichtner** [comment]
Authentication error: TLS verification failed.

**Comment by JasonNaughton** [comment]
> just a question... are you doing the pingtest from your machine or from the firewall?
> i ask because it seems somewhat similar as to what i experienced with dns for the firewall being on 127.0.0.1 and not working.
> can you try to add alias 127.0.0.1 to the loopback interface on firewall - virtual ips - settings and see if that makes a difference ?

Helllo ThuTex

I was pinging on the opnsense firewall itself.  I have access to console.

**Comment by fichtner** [comment]
@JasonNaughton you should try the bootstrap sequence provided at https://github.com/opnsense/update#opnsense-bootstrap

**Comment by JasonNaughton** [comment]
> perhaps a proxy in between? "Authentication error" suggests it can not access the location.
> 
> You could try to set the mirror manually and choose `http://pkg.opnsense.org` which was our previous default.

How would I manually set the mirror?   I assumed as the first error that came up was the fact that the repo-OPNsense.sqlite file did not exist (and I’ve verified that via console) that the rest of the errors were due to this.   Does this file get transferred from the mirror?

**Comment by JasonNaughton** [comment]
> perhaps a proxy in between? "Authentication error" suggests it can not access the location.
> 
> You could try to set the mirror manually and choose `http://pkg.opnsense.org` which was our previous default.

Sorry I forgot to answer your first question.  Remember I had 18.7.7 working on the OPNsense firewall without any issues.  It was only after I did an update from 18.7.7 to 19.1 did this error show up.

**Comment by JasonNaughton** [comment]
> @JasonNaughton you should try the bootstrap sequence provided at https://github.com/opnsense/update#opnsense-bootstrap
> 
> (ca_root_nss package may be clobbered for you at the moment so the verify fails)

Hello fichtner,

I’ll look at the bootstrap process thanks.

**Comment by JasonNaughton** [comment]
> @JasonNaughton you should try the bootstrap sequence provided at https://github.com/opnsense/update#opnsense-bootstrap
> 
> (ca_root_nss package may be clobbered for you at the moment so the verify fails)

Just glanced over the process, it indicates that it will do a factory reset, but then by default it won’t clobber the configuration?   I won’t be able to do the pkg install ca_root_nss as the repo-OPNsense.sqlite does not exist:

# pkg install ca_root_nss
Updating OPNsense repository catalogue...
pkg: Repository OPNsense load error: access repo file(/var/db/pkg/repo-OPNsense.sqlite) failed: No such file or directory

I get the same type of error when I attempt to do the pkg update.  Any other idea how to address this?

**Comment by fichtner** [comment]
config will be kept

skip ca_root_nss install, run:

    # ./opnsense-bootstrap -i

**Comment by JasonNaughton** [comment]
Attempted to simply do the fetch of the bootstrap script and it too failed due to the SSL authentication issues:

# fetch https://raw.githubusercontent.com/opnsense/update/master/bootstrap/opnsense-bootstrap.sh
Certificate verification failed for /C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert SHA2 High Assurance Server CA
5710991603320:error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed:/usr/src/crypto/openssl/ssl/s3_clnt.c:1269:
fetch: https://raw.githubusercontent.com/opnsense/update/master/bootstrap/opnsense-bootstrap.sh: Authentication error

**Comment by fichtner** [comment]
use fetch --no-verify-peer

**Comment by JasonNaughton** [comment]
Okay there seems to be a bit of a problem here.  I issued the command:

opnsense-bootstrap -i

The system downloaded about 120 packages and then issued:
% /etc/rc.d/devfs restart 
Message from opnsense-19.1.2:

Here be dragons
Fetching base-19.1.2-amd64.txz: .......................................................

It’s been giving me the dot’s now since 12 noon... How long should this take it’s about 6 hours later...

Cheers,

Jason Naughton, P.Eng, M.E.Sc,
Professional Contractor,
JMN Planning, Pickering, Ontario,
Office: (647)-693-4880

**Comment by fichtner** [comment]
It would indicate it has trouble fetching again, which was part of your original problem. Sometimes this was due to MTU or IPv6 connectivity issues, but I can't help but think it's not something OPNsense does on its own. It's something in the surroundings. :/

**Comment by JasonNaughton** [comment]
Hello Fichtner,

I downloaded the USB key for 19.1, pulled another box off the shelf,
booted off of the USB key, dropped my config into /conf/config.xml and
rebooted.   We're now operational with the same network config that we had
on the culprit box.  I can only assume there must have been some sort of
hardware issue that was causing the station not to update.   Sorry for the
trouble.

Cheers

> It would indicate it has trouble fetching again, which was part of your
> original problem. Sometimes this was due to MTU or IPv6 connectivity
> issues, but I can't help but think it's not something OPNsense does on its
> own. It's something in the surroundings. :/
>
> --
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/opnsense/core/issues/3289#issuecomment-470409811


Jason Naughton,  P.Eng, M.E.Sc,
Professional Contractor,
JMN Planning,  Pickering, Ontario,
Office: (647)-693-4880

**Comment by fichtner** [comment]
Hi Jason,

No worries. Happy to hear it was resolved.


Cheers,
Franco
