### ISSUE TITLE
configd: additional features for plugins

### ISSUE THREAD

**Issue by fichtner** [opnsense/core#329]
o hotplug support for actions
o fail when reloading a missing template
o template revoke for plugin deinstall
o template trigger on bootup

**Comment by AdSchellevis** [comment]
"template trigger on bootup" is in.
The other subjects very likely won't get in soon:
* hotplug is a nice to have for now
* not sure what "fail when reloading a missing template" should do
* the deinstall is probably better to leave it at the plugin deinstall script, targets may contain patterns which make this a bit tricky.

**Comment by fichtner** [comment]
Okay, I'm happy with "fail when reloading a missing template", if you tell it to reload "fooo", it will say "ok" and not return an error. Makes it hard to catch typos in plugins early.

**Comment by AdSchellevis** [comment]
Ah, you want an error if no files where generated?

**Comment by fichtner** [comment]
No, an error when a template is invoked that does not exist.

**Comment by AdSchellevis** [comment]
fixed.

**Comment by fichtner** [comment]
Brilliant, closing.
