### ISSUE TITLE
Squid does not bind to ipv6 addresses

### ISSUE THREAD

**Issue by Kimotu** [opnsense/core#3292]
[x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[x] I have searched the existing issues and I'm convinced that mine is new.

**Describe the bug**
Interface runs dual-stack - has ipv4 and ipv6 address. When enabling squid it only binds to interface ipv4 address and ipv6 addresses that are **defined as CARP** - but **not** to the native interface ipv6 address.

**To Reproduce**
1. Assign ipv6 address to interface
2. enable web proxy for this interface
3. take a look at /usr/local/etc/squid/squid.conf

**Expected behavior**
Squid should bind to all interface addresses where it is enabled (ipv4+ipv6)

**Additional context**
Why need ipv6 in dual-stack environment when clients could use ipv4 address?
Reason: transparent ipv6 proxy [https://forum.opnsense.org/index.php?topic=11251.0](https://forum.opnsense.org/index.php?topic=11251.0)

> IPv6 addresses have the concept of "scopes".  A scope is the domain in which a particular address is valid.  Localhost (::1) has local scope, link-local addresses (fe80:*) have link-local scope, site-local addresses (fec0:*) have site-local scope, and global addresses (everythign else) have global scope.  Since ::1 only has local scope, it's only valid for traffic that originates and ends on the local machine.  For that reason, it is specifically forbidden to assign ::1 to a real network interface.
>Your PF rule redirects a packet to ::1, but doesn't change the receiving interface.  Thus, it violates scoping rules.  You can tell by running 'netstat -s -f inet6 | grep "violated scope"' before and after generating the traffic that you want to redirect.  The check is in in6_setscope().

>The simple workaround is to change your rdr rule to redirect to your actual link-local, site-local, or global IPv6 address instead of ::1.

[https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=193568](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=193568)

Due to this scope thing, you cannot simply intercept and redirect ipv6:80 traffic just to [::1]:3128. You have to redirect is to "your actual link-local, site-local, or global IPv6 address".

Thus squid should not just add the interface ipv6 address for listening, it should additionally add the _intercept_ option to it (it does not hurt if you explicitly use an ipv6 address as proxy address).

**Hint**
If you are going to include an option to _add the new firewall rule_ for redirect or extend the existing one for dual-stack, make sure that the rule is

`rdr on <intercept_if> inet6 proto tcp from ! (self) port 1024:65535 to any port = http -> <intercept_if_ipv6> port 3128`

Without the **! (self)** I got proxy loops. Seems that squid used the interface ipv6 address as  source address to query the server in internet and this traffic got intercepted again, forwarded to squid and ... loop.

**Environment**

OPNsense 19.1.2-amd64
FreeBSD 11.2-RELEASE-p9-HBSD
OpenSSL 1.0.2q 20 Nov 2018

**Comment by ssbarnea** [comment]
I wonder if your problem has something to do with mine as described at https://forum.opnsense.org/index.php?topic=12145.msg55622#msg55622 -- clearly we both have IPv4+IPv6 setup.

**Comment by Kimotu** [comment]
Any chance to get the ipv6 addresses added? I just had the issue that I assigned proxy via wpad.dat/proxy.pac with a fqdn that resolves to ipv4+ipv6.
The application got proxy via script, resolved the proxy fqdn and then tried as first the ipv6 address which timed out, since squid did not bind to it. This caused an error.
As soon as I manually added the ipv6 address to squid.conf, the application worked.

**Comment by jnsbyr** [comment]
I have switched from IPv4 to dual stack operation on my opnsense but squid does not bind to IPv6 addresses like @Kimotu has described. Here is a hack to resolve this issue: edit file _/usr/local/etc/squid/squid.conf_ and replace the lines with _http_port_ with

`http_port <your proxy port number>`

and restart squid using the web interface. See https://wiki.squid-cache.org/Features/IPv6 for more details on running squid with IPv6. The restart of squid may take a while but afterwards squid will bind to IPv4 and IPv6 on all interfaces. You should use firewall rules to prevent access to squid from interfaces where it is not desired. Also note that this hack is lost when you modify the config via web interface.

So please, developers, have a look at this problem and find a way to include IPv6 binding for squid. One simple way to do it could be to just add a single _http_port_ line with the port number when no interface is selected in the web interface.

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository, 
please read https://github.com/opnsense/core/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue, 
just let us know, so we can reopen the issue and assign an owner to it.
