### ISSUE TITLE
IPv6 portforward rule creates rules for all interfaces

### ISSUE THREAD

**Issue by Kimotu** [opnsense/core#3293]
[x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[x] I have searched the existing issues and I'm convinced that mine is new.

**Describe the bug**

One portforward rule for ipv6 in OPNsense gui creates multiple rules in pf (one for each interface instead just for the selected interface)

Interface lan = lagg0_vlan40 with ipv6 2001:AAAA:BBBB:XXXX::1

Rule created in gui:
```

If	Proto 	Address 		Ports 			Address 	Ports 		IP 			Ports 	Description 	 
lan 	TCP 	! This Firewall 	Port_Unprivileged  	* 		80 (HTTP) 	2001:AAAA:BBBB:XXXX::1 	3128 	transparent ipv6 proxy
```

Rules created in pf:

```
rdr on em2 inet6 proto tcp from ! (self) port 1024:65535 to any port = http -> 2001:AAAA:BBBB:XXXX::1 port 3128
rdr on em4_vlan10 inet6 proto tcp from ! (self) port 1024:65535 to any port = http -> 2001:AAAA:BBBB:XXXX::1 port 3128
rdr on em4_vlan60 inet6 proto tcp from ! (self) port 1024:65535 to any port = http -> 2001:AAAA:BBBB:XXXX::1 port 3128
rdr on em4 inet6 proto tcp from ! (self) port 1024:65535 to any port = http -> 2001:AAAA:BBBB:XXXX::1 port 3128
rdr on lagg1 inet6 proto tcp from ! (self) port 1024:65535 to any port = http -> 2001:AAAA:BBBB:XXXX::1 port 3128
rdr on lagg0_vlan20 inet6 proto tcp from ! (self) port 1024:65535 to any port = http -> 2001:AAAA:BBBB:XXXX::1 port 3128
rdr on lagg0_vlan30 inet6 proto tcp from ! (self) port 1024:65535 to any port = http -> 2001:AAAA:BBBB:XXXX::1 port 3128
rdr on lagg0_vlan40 inet6 proto tcp from ! (self) port 1024:65535 to any port = http -> 2001:AAAA:BBBB:XXXX::1 port 3128

```

**To Reproduce**
1. Firewalls | NAT | Port Forward
2. Add an ipv6 rule that redirects a port
3. Save and apply
4. Control via _pfctl -sn_

**Expected behavior**
Just one rule that is assigned to correct interface (lagg0_vlan40). The other rules are trash, since due to ipv6 link scope, forwards cross interfaces to ip6 addresses not local will not work anyway.

Just this rule should have been created:

`rdr on lagg0_vlan40 inet6 proto tcp from ! (self) port 1024:65535 to any port = http -> 2001:AAAA:BBBB:XXXX::1 port 3128`

**Environment**
OPNsense 19.1.2-amd64
FreeBSD 11.2-RELEASE-p9-HBSD
OpenSSL 1.0.2q 20 Nov 2018

**Comment by AdSchellevis** [comment]
reflection enabled? 
[Firewall->Settings->Advanced]
![image](https://user-images.githubusercontent.com/9783985/53961241-67d34480-40e8-11e9-866e-80220fb1ddba.png)

[portforward rule]
![image](https://user-images.githubusercontent.com/9783985/53961275-7ae61480-40e8-11e9-99a8-51d3d6309131.png)


if not, please send the output of:
```
grep 3128 /tmp/rules.debug
```

**Comment by Kimotu** [comment]
Global reflections were active and in rule _system default_ was set. I set it to _disabled_ in rule and now the rdr rule looks like it should.

I will have to read about reflections. I still do not get the sense why these additional rules get added. I think they would make sense outside-inside if more external addresses are configured. But in my case with inside-localhost redirect, those additional rules do not make sense.

**Comment by Kimotu** [comment]
Thanks!
