### ISSUE TITLE
captive portal : adding CAS SSO authentication

### ISSUE THREAD

**Issue by rrignier** [opnsense/core#3294]
Hello there, I'm a long time user of pfsense boxes and newer ones are now Opnsense. Great job for the interface rewriting !

Central Authentication Server is an auth SSO web service often used in educational environements and has benefits to grants tickets instead of username/password. https://www.apereo.org/projects/cas

This feature is a missing one in most of the captive portal projects, so I decided to try to implement it in the Opnsense captive portal. I have succeeded but I think the bad way : 
I used a modified captive portal web server with php enabled in the CP chroot, and a modified default template with phpCAS client installed.
It would be best to implemented it in the API but seems too difficult for me: no traditional login/password form and eraly redirects before the headers are sent.

I think I could implement it more nicely witin the ui, and the services but need your opinion before I fork the core.

Here is the link of the project : https://github.com/rrignier/opnsense-captive-cas

Regards

**Comment by AdSchellevis** [comment]
@rrignier the code indeed doesn't comply with our standards, our captive portal client code doesn't include php script execution to keep a clear separation between untrusted client code and guarded api end points for example.

We have had the question before to include sso using cas, saml or OAuth2, but it's quite some work to implement it properly, for which we have no funding (just not enough demand either).

If you could develop an implementation, which doesn't require php in the captive portal http server and could easily be validated/tested, I would gladly have a look, but the amount of time I can spend on the subject is quite limited.

**Comment by rrignier** [comment]
OK, I'll have a look in the api to see what could be implemented. if I have time to this.
Thank you for report.

**Comment by rrignier** [comment]
needs more compliant implementation
