### ISSUE TITLE
[Feature request] VPN IPsec Mobile Clients: Radius: Assign specific virtual IP range to users in specific groups

### ISSUE THREAD

**Issue by stumbaumr** [opnsense/core#3295]
**Is your feature request related to a problem? Please describe.**
I would like to assign IPsec mobile users into separate virtual IP pools. I require this to allow/prohibit access to users in certain groups to specific network resources.

Example: Three groups (Admins, Developers, Users) have separate virtual IP pools. These network ranges are then used in firewall rules on the current IPsec peer or even on another firewall behind a IPsec tunnel in a different location.

The groups and users are configured on a remote Radius server.

**Describe the solution you'd like**
I would like to use the "Group Selection" feature described here:
https://wiki.strongswan.org/projects/strongswan/wiki/EAPRadius

I understand that this is a very specific setup. So maybe it would be best to have a text field "Advanced Configuration" where the content is saved into `/usr/local/etc/ipsec.advanced.conf` and an `include ipsec.advanced.conf` statement in ipsec.conf. Almost same as OpenVPN has it.

For strongswan.conf the only requirement is to add `class_group = yes` to the eap-radius section. It seems it does not hurt in case it is set and no class is passed back from the Radius server. 

**Describe alternatives you've considered**
As far as I understand there is currently no functionality that allows users to be assigned into specific virtual IP ranges.

And from my searches it seems I am not the first person to ask.

Here is my tested configuration I would like in ipsec.advanced.conf

```
conn mobile
  aggressive = no
  fragmentation = yes
  keyexchange = ike
  mobike = yes
  reauth = yes
  rekey = yes
  forceencaps = yes
  installpolicy = yes
  ikelifetime = 28800s
  ike = aes256-aesxcbc-modp2048,aes256-aesxcbc-modp1024,aes256-sha512-modp2048,aes256-sha512-modp1024,aes256-sha384-modp2048,aes256-sha384-modp1024,aes256-sha256-modp2048,aes256-sha256-modp1024!
  dpdaction = clear
  dpddelay = 10s
  dpdtimeout = 60s
  left = XX.XX.XX.XX
  leftid = vpn.example.com
  leftauth = pubkey
  leftcert = /usr/local/etc/ipsec.d/certs/cert-2.crt
  leftsendcert = always
  rightsendcert = never
  right = %any

conn mobile-ops
  also = mobile
  rightauth=eap-radius
  eap_identity = %any
  rightgroups="VPN-OPS" 
  leftsubnet=10.0.0.0/8,192.168.0.0/22
  rightsourceip = 10.20.35.32/28
  auto = add

conn mobile-dev
  also = mobile
  rightauth=eap-radius
  eap_identity = %any
  rightgroups="VPN-DEV" 
  leftsubnet=10.0.0.0/8
  rightsourceip = 10.20.35.0/27
  auto = add

conn mobile-user
  also = mobile
  rightauth=eap-radius
  eap_identity = %any
  rightgroups="VPN-USER" 
  leftsubnet=10.0.0.0/8
  rightsourceip = 10.20.35.128/25
  auto = add
```

Do you think there is a chance of a PR for this being accepted?

**Comment by mimugmail** [comment]
Currently this only works with OpenVPN. For IPSec you can only use one Pool / Policy.

**Comment by stumbaumr** [comment]
The above config example will create three policies (three phase 1 with four phase 2). So yes, one virtual IP pool (rightsourceip) per policy.

**Comment by mimugmail** [comment]
When you search the closed issues you will find one of me asking the same. There are some problems when mixing auth types. 

I know it's technically easy to implement via CLI but quite a lot of rewrite for the UI part.

**Comment by stumbaumr** [comment]
> I know it's technically easy to implement via CLI but quite a lot of rewrite for the UI part.

Very true!

That is why I wanted to suggest a "Advanced Configuration" Text Box. I am sure that my requirement is very specific and not worth implementing/maintaining it in the GUI. But currently any reconfiguration/restart of the IPsec will break my configuration from the command line and I have no backup/version management of it.

That is why I was asking if a PR for a "Advanced Configuration" Text Box would stand a chance.

**Comment by stumbaumr** [comment]
So we created a PR for that then...

**Comment by stumbaumr** [comment]
So this actually works for us. It is not as nice as PR #3298 since there is no config backup and no config sync to the HA backup system.

**Comment by stumbaumr** [comment]
Since 23.1 swanctl.conf is used and ipsec.conf has been abolished.
The [tutorial](https://forum.opnsense.org/index.php?topic=12147.0) to assign IP address ranges based on the class_group no longer works.
After looking through the new VPN->IPsec->Connections it would be awesome to just add "Class" as additional field when selecting "EAP Radius" as Authentication. Adding it using include files is error prone since the UUID generated seems to change sometimes...
This also requires to add class_group = yes in strongswan.conf in the eap-radius section.

@AdSchellevis Any chance a PR for this would be accepted?

**Comment by AdSchellevis** [comment]
@stumbaumr if it's not too large, I'm certainly willing to take a look. is there any downside in always adding "class_group = yes" in strongswan?

**Comment by stumbaumr** [comment]
Just remembered there was this "Synchronize groups" checkbox in the Radius server setup - I would base it on that.

**Comment by stumbaumr** [comment]
So here is the PR for this... https://github.com/opnsense/core/pull/6826

I left the fix for https://github.com/opnsense/core/issues/6824 out of it since @AdSchellevis assigned it to himself already...

**Comment by Monviech** [comment]
@stumbaumr It was total coincidence that I was led on the same path with the eap_id. Hope it didn't complicate things for you.

**Comment by stumbaumr** [comment]
@AdSchellevis , do I need to reopen this issue so the PR https://github.com/opnsense/core/pull/6826  related to it is not forgotten? I see no option here in the issue to reopen it - should I create a new issue?

**Comment by fichtner** [comment]
@stumbaumr this this wasn't closed because of a shipped feature I've reopened and tagged it accordingly

**Comment by AdSchellevis** [comment]
@stumbaumr a variation of your request has been merged in https://github.com/opnsense/core/commit/928d2f829947017bb91078128e9421d250fe2880. thanks!

**Comment by stumbaumr** [comment]
@AdSchellevis It looks like you are not adding the selected group into the remote section. So the first available section is assigned to every user... which in my case is the admin group... bummer...
```
        remote-7d99b294-06a9-4db8-a9d7-0df5ca994da8 {
            round = 0
            auth = eap-radius
            eap_id = %any
        }
```
Parameter groups is missing there... compare with https://github.com/opnsense/core/issues/3295#issuecomment-1706853647

**Comment by AdSchellevis** [comment]
ok, I do seem to inject the wrong payload (gid), but on my end there certainly is something when selected.

```
        remote-76bec83c-0dc4-45d9-91b0-16f7ecbec186 {
            round = 0
            auth = eap-radius
            groups = 2001,2002,2011
        }
```

**Comment by stumbaumr** [comment]
Ok, I think I found the mistake - I applied just the patch to the current 23.7.9 - obviously there is a lot missing to the 24.1 ...

**Comment by fichtner** [comment]
Might just be af46866998fc62c82 which came in after the fact :)

**Comment by stumbaumr** [comment]
So I installed the development version on a test system today and tested it. Seems all ok!

Thanks so much!!!
