### ISSUE TITLE
Restore Plugins from Backup

### ISSUE THREAD

**Issue by imidoriya** [opnsense/core#3297]
While it appears the backup contains plugin configuration settings, the restore doesn't actually reinstall the plugins.  It's great that it has my Let's Encrypt config, but I'm missing a component if after restore, I have the config but the plugin is not running.  I have to remember what plugins were installed and reinstall them manually.  In some cases, the plugins may be critical to operation, such as a nginx reverse proxy that hosts a website.

It would be great if the backup contained the plugins installed and upon restore, Opnsense reinstalled them (or offered to reinstall them in the case where you may not want to do so).

**Comment by fichtner** [comment]
same as #1663
