### ISSUE TITLE
Unable to choose bitmask when adding new ip4 static route

### ISSUE THREAD

**Issue by doublej74** [opnsense/core#330]
When adding a static route the field for ip address supports ip4 as well as ip6 addresses(? or what else is the 128?), but when entering an ip4 address, user can not set the bitmask(range: 1-32) correctly.

Workaround: first create the static route with the incorrect bitmask, save it, then edit the route. Current workaround is not user-friendly, especially when adding a lot of routes.

Proposal for fix: remove the dropdown box for the bitmask and require a CIDR value in the field (many other fields in opnsense work like this, e.g. fields in OpenVPN settings use CIDR values)

**Comment by AdSchellevis** [comment]
We reworked the page some months ago, issue should be fixed.
