### ISSUE TITLE
VPN IPsec Mobile clients: setup uniqueids = yes instead of never

### ISSUE THREAD

**Issue by stumbaumr** [opnsense/core#3300]
**Describe the bug**
We have remote developers that connect more than once with userid and password. For example they develop mobile webpages on their Laptop and use their smartphone to verify.

The IPsec configuration hardcodes `uniqueids = yes` in the setup section. So this will only allow one mobile client per userid. 

**To Reproduce**
1. Setup IPsec Mobile clients to authenticate using IKEv2 and EAP-Radius
2. Log on using device A
3. Log on using device B

Observe on both devices the assigned IP address. One of the devices will not be able to use its connection.

**Expected behavior**
Device A und B should be usable at the same time.

**Additional context**
According to https://wiki.strongswan.org/issues/2648 the solution would be to use never instead of yes.

Would you accept a PR to make uniqueids configurable?

**Environment**
Software version used and hardware type if relevant.

OPNsense 19.1.3 (amd64, OpenSSL).

**Comment by AdSchellevis** [comment]
@stumbaumr as long as the default stays the same and the option contains a clear explanation, it wouldn't be a problem to add the option, although reading the strongswan issue, I'm not convinced that it's needed. It's probably good to try it first, if the fix works for you, it would be good to add a note in the help text for which scenario this could be a good idea.

**Comment by fichtner** [comment]
Assuming that #3311 allows this.
