### ISSUE TITLE
Unbound statistics empty after 19.1.3

### ISSUE THREAD

**Issue by soder10** [opnsense/core#3302]
Hello devs!

**Describe the bug**
After upgrade to 19.1.3, the unbound statistics page does not show any output. Only the auto refresh button is displayed, but no results.

**To Reproduce**
Goto services \ unbound \ statistics

**Expected behavior**
On 19.1.1 (before update) it was showing the statistics correctly.

**Additional context**
Run from CLI:
unbound-control -c /var/unbound/unbound.conf stats_noreset -> does show the stats correctly

**Environment** 
OPNsense 19.1.3 (amd64, OpenSSL).

**Comment by fichtner** [comment]
Looks ok from here, GUI fills correctly, console provides output:

```
# configctl unbound stats
{"thread0": {"recursion": {"time": {"avg": "0.074472", "median": "0.0487491"}}, "tcpusage": "0", "num": {"queries_ip_ratelimited": "0", "recursivereplies": "365", "cachemiss": "365", "cachehits": "1380", "zero_ttl": "851", "prefetch": "866", "queries": "1745"}, "requestlist": {"overwritten": "0", "max": "10", "current": {"all": "0", "user": "0"}, "avg": "0.811535", "exceeded": "0"}}, "thread3": {"recursion": {"time": {"avg": "0.064594", "median": "0.0462393"}}, "tcpusage": "0", "num": {"queries_ip_ratelimited": "0", "recursivereplies": "135", "cachemiss": "135", "cachehits": "577", "zero_ttl": "360", "prefetch": "369", "queries": "712"}, "requestlist": {"overwritten": "0", "max": "3", "current": {"all": "0", "user": "0"}, "avg": "0.119048", "exceeded": "0"}}, "thread2": {"recursion": {"time": {"avg": "0.083584", "median": "0.052992"}}, "tcpusage": "0", "num": {"queries_ip_ratelimited": "0", "recursivereplies": "225", "cachemiss": "225", "cachehits": "792", "zero_ttl": "482", "prefetch": "486", "queries": "1017"}, "requestlist": {"overwritten": "0", "max": "10", "current": {"all": "0", "user": "0"}, "avg": "0.45429", "exceeded": "0"}}, "thread1": {"recursion": {"time": {"avg": "0.087068", "median": "0.0465651"}}, "tcpusage": "0", "num": {"queries_ip_ratelimited": "0", "recursivereplies": "56", "cachemiss": "56", "cachehits": "226", "zero_ttl": "106", "prefetch": "110", "queries": "282"}, "requestlist": {"overwritten": "0", "max": "5", "current": {"all": "0", "user": "0"}, "avg": "0.216867", "exceeded": "0"}}, "time": {"now": "1552205520.479343", "up": "45045.713027", "elapsed": "45045.713027"}, "total": {"recursion": {"time": {"avg": "0.076293", "median": "0.0486364"}}, "tcpusage": "0", "num": {"queries_ip_ratelimited": "0", "recursivereplies": "781", "cachemiss": "781", "cachehits": "2975", "zero_ttl": "851", "prefetch": "1831", "queries": "3756"}, "requestlist": {"overwritten": "0", "max": "10", "current": {"all": "0", "user": "0"}, "avg": "0.542879", "exceeded": "0"}}}
```

Can you try the configctl on your end?

**Comment by soder10** [comment]
I got a not very descriptive "Execute error"

**Comment by AdSchellevis** [comment]
your log should contain details (system -> log files -> backend)

**Comment by soder10** [comment]
Thats what I see there:

configd.py: [e2233e41-5827-4c40-b461-06ae21e61e2d] Script action failed with Command '/usr/local/opnsense/scripts/unbound/wrapper.py -s' returned non-zero exit status 1 at Traceback (most recent call last): File "/usr/local/opnsense/service/modules/processhandler.py", line 481, in execute stdout=output_stream, stderr=error_stream) File "/usr/local/lib/python2.7/subprocess.py", line 190, in check_call raise CalledProcessError(retcode, cmd) CalledProcessError: Command '/usr/local/opnsense/scripts/unbound/wrapper.py -s' returned non-zero exit status 1

**Comment by AdSchellevis** [comment]
ok, and now run:
```
/usr/local/opnsense/scripts/unbound/wrapper.py -s
```

**Comment by soder10** [comment]
Traceback (most recent call last):
  File "/usr/local/opnsense/scripts/unbound/wrapper.py", line 95, in <module>
    ptr[key] = value.strip()
TypeError: 'str' object does not support item assignment
root@FW01:~ #

**Comment by AdSchellevis** [comment]
@soder10 hmm, that's unexpected, the key seems to be duplicate, try https://github.com/opnsense/core/commit/64c7d460491cb3eb12f94a88fae436bf53c9e465

```
opnsense-patch 64c7d46
```

and then see if the output looks normal, there might be something else we're missing here, this only prevents it from crashing.

**Comment by soder10** [comment]
root@FW01:~ # /usr/local/opnsense/scripts/unbound/wrapper.py -s
Traceback (most recent call last):
  File "/usr/local/opnsense/scripts/unbound/wrapper.py", line 94, in <module>
    if len(keys) == 0 and type(ptr[key]) == dict:
KeyError: 'queries'

**Comment by AdSchellevis** [comment]
ok, let's revert the patch by running opnsense-patch again, wrong fix

**Comment by AdSchellevis** [comment]
new patch https://github.com/opnsense/core/commit/435d984984a12501b3e828f722cadbf28aed24f4, I've reverted the other in https://github.com/opnsense/core/commit/435d984984a12501b3e828f722cadbf28aed24f4

**Comment by soder10** [comment]
root@FW01:~ # /usr/local/opnsense/scripts/unbound/wrapper.py -s
Traceback (most recent call last):
  File "/usr/local/opnsense/scripts/unbound/wrapper.py", line 95, in <module>
    ptr[key] = value.strip()
TypeError: 'str' object does not support item assignment
root@FW01:~ #

**Comment by AdSchellevis** [comment]
I meant, https://github.com/opnsense/core/commit/1855ce9488336e397244c69c2f05eee31ca09a42, your back to the original now.

```
opnsense-patch 1855ce94
```

should do the trick

**Comment by soder10** [comment]
Same result, even after 1855ce94

**Comment by AdSchellevis** [comment]
can't be the exact same, the line number differs.

**Comment by soder10** [comment]
Ok, I think I run the patch 1855ce94 two times, so the 2nd run rolled back everything that the 1st run changed. So after I run the patch for the 3rd time, the result is different in the number of line:

root@FW01:~ # /usr/local/opnsense/scripts/unbound/wrapper.py -s
Traceback (most recent call last):
  File "/usr/local/opnsense/scripts/unbound/wrapper.py", line 96, in <module>
    ptr[key] = value.strip()
TypeError: 'str' object does not support item assignment

**Comment by AdSchellevis** [comment]
it's a bit difficult, since I can't reproduce the issue on my end, but reading it again, the issue is different than I though.

**Comment by AdSchellevis** [comment]
ok, before adding other patches without being able to reproduce this, can you dump the output of?

```
 /usr/local/sbin/unbound-control -c /var/unbound/unbound.conf stats_noreset
```

**Comment by soder10** [comment]
Sure.

root@FW01:~ #
root@FW01:~ #
root@FW01:~ # /usr/local/sbin/unbound-control -c /var/unbound/unbound.conf stats_noreset
thread0.num.queries=1830
thread0.num.queries_ip_ratelimited=0
thread0.num.cachehits=1301
thread0.num.cachemiss=529
thread0.num.prefetch=24
thread0.num.zero_ttl=0
thread0.num.recursivereplies=529
thread0.requestlist.avg=0.282098
thread0.requestlist.max=12
thread0.requestlist.overwritten=0
thread0.requestlist.exceeded=0
thread0.requestlist.current.all=0
thread0.requestlist.current.user=0
thread0.recursion.time.avg=0.115224
thread0.recursion.time.median=0.064901
thread0.tcpusage=0
thread1.num.queries=2215
thread1.num.queries_ip_ratelimited=0
thread1.num.cachehits=1577
thread1.num.cachemiss=638
thread1.num.prefetch=36
thread1.num.zero_ttl=0
thread1.num.recursivereplies=638
thread1.requestlist.avg=0.281899
thread1.requestlist.max=8
thread1.requestlist.overwritten=0
thread1.requestlist.exceeded=0
thread1.requestlist.current.all=0
thread1.requestlist.current.user=0
thread1.recursion.time.avg=0.123264
thread1.recursion.time.median=0.0597768
thread1.tcpusage=0
thread2.num.queries=1967
thread2.num.queries_ip_ratelimited=0
thread2.num.cachehits=1416
thread2.num.cachemiss=551
thread2.num.prefetch=28
thread2.num.zero_ttl=0
thread2.num.recursivereplies=551
thread2.requestlist.avg=0.170984
thread2.requestlist.max=4
thread2.requestlist.overwritten=0
thread2.requestlist.exceeded=0
thread2.requestlist.current.all=0
thread2.requestlist.current.user=0
thread2.recursion.time.avg=0.114515
thread2.recursion.time.median=0.0595474
thread2.tcpusage=0
thread3.num.queries=1888
thread3.num.queries_ip_ratelimited=0
thread3.num.cachehits=1318
thread3.num.cachemiss=570
thread3.num.prefetch=34
thread3.num.zero_ttl=0
thread3.num.recursivereplies=570
thread3.requestlist.avg=0.256623
thread3.requestlist.max=6
thread3.requestlist.overwritten=0
thread3.requestlist.exceeded=0
thread3.requestlist.current.all=0
thread3.requestlist.current.user=0
thread3.recursion.time.avg=0.124987
thread3.recursion.time.median=0.0652859
thread3.tcpusage=0
total.num.queries=7900
total.num.queries_ip_ratelimited=0
total.num.cachehits=5612
total.num.cachemiss=2288
total.num.prefetch=122
total.num.zero_ttl=0
total.num.recursivereplies=2288
total.requestlist.avg=0.248963
total.requestlist.max=12
total.requestlist.overwritten=0
total.requestlist.exceeded=0
total.requestlist.current.all=0
total.requestlist.current.user=0
total.recursion.time.avg=0.119727
total.recursion.time.median=0.0623777
total.tcpusage=0
time.now=1552226102.614317
time.up=102338.104443
time.elapsed=102338.104443
mem.cache.rrset=3391830
mem.cache.message=1402392
mem.mod.iterator=16556
mem.mod.validator=0
mem.mod.respip=0
mem.streamwait=0
histogram.000000.000000.to.000000.000001=25
histogram.000000.000001.to.000000.000002=0
histogram.000000.000002.to.000000.000004=0
histogram.000000.000004.to.000000.000008=0
histogram.000000.000008.to.000000.000016=0
histogram.000000.000016.to.000000.000032=0
histogram.000000.000032.to.000000.000064=0
histogram.000000.000064.to.000000.000128=0
histogram.000000.000128.to.000000.000256=0
histogram.000000.000256.to.000000.000512=0
histogram.000000.000512.to.000000.001024=0
histogram.000000.001024.to.000000.002048=2
histogram.000000.002048.to.000000.004096=97
histogram.000000.004096.to.000000.008192=113
histogram.000000.008192.to.000000.016384=52
histogram.000000.016384.to.000000.032768=344
histogram.000000.032768.to.000000.065536=570
histogram.000000.065536.to.000000.131072=479
histogram.000000.131072.to.000000.262144=378
histogram.000000.262144.to.000000.524288=157
histogram.000000.524288.to.000001.000000=49
histogram.000001.000000.to.000002.000000=19
histogram.000002.000000.to.000004.000000=3
histogram.000004.000000.to.000008.000000=0
histogram.000008.000000.to.000016.000000=0
histogram.000016.000000.to.000032.000000=0
histogram.000032.000000.to.000064.000000=0
histogram.000064.000000.to.000128.000000=0
histogram.000128.000000.to.000256.000000=0
histogram.000256.000000.to.000512.000000=0
histogram.000512.000000.to.001024.000000=0
histogram.001024.000000.to.002048.000000=0
histogram.002048.000000.to.004096.000000=0
histogram.004096.000000.to.008192.000000=0
histogram.008192.000000.to.016384.000000=0
histogram.016384.000000.to.032768.000000=0
histogram.032768.000000.to.065536.000000=0
histogram.065536.000000.to.131072.000000=0
histogram.131072.000000.to.262144.000000=0
histogram.262144.000000.to.524288.000000=0
num.query.type.A=7169
num.query.type.PTR=3
num.query.type.AAAA=716
num.query.type.SRV=12
num.query.class.IN=7900
num.query.opcode.QUERY=7900
num.query.tcp=0
num.query.tcpout=3
num.query.tls=0
num.query.tls.resume=0
num.query.ipv6=0
num.query.flags.QR=0
num.query.flags.AA=0
num.query.flags.TC=0
num.query.flags.RD=7900
num.query.flags.RA=0
num.query.flags.Z=0
num.query.flags.AD=0
num.query.flags.CD=0
num.query.edns.present=0
num.query.edns.DO=0
num.answer.rcode.NOERROR=7611
num.answer.rcode.FORMERR=0
num.answer.rcode.SERVFAIL=0
num.answer.rcode.NXDOMAIN=289
num.answer.rcode.NOTIMPL=0
num.answer.rcode.REFUSED=0
num.answer.rcode.nodata=472
num.query.ratelimited=0
num.answer.secure=0
num.answer.bogus=0
num.rrset.bogus=0
num.query.aggressive.NOERROR=0
num.query.aggressive.NXDOMAIN=0
unwanted.queries=0
unwanted.replies=0
msg.cache.count=4733
rrset.cache.count=12064
infra.cache.count=3239
key.cache.count=0
num.query.authzone.up=0
num.query.authzone.down=0
root@FW01:~ #

**Comment by AdSchellevis** [comment]
found it,  keep the last patch and add this:
```
opnsense-patch  041d6ea
```

**Comment by soder10** [comment]
Yep, it works now! Thanks for the awesome quick resolution!
