### ISSUE TITLE
Cannot save outbound NAT rule when setting destination to "any"

### ISSUE THREAD

**Issue by oparoz** [opnsense/core#3303]
**Describe the bug**

Something broke in 19.1.3 when adding an outbound NAT rule with the destination set to "any"

```
The following input errors were detected:

    The field Destination bit count is required.
```

**To Reproduce**
1. Go to 'Firewall->NAT->Outbound'
2. Create a new rule
3. Set destination to "any"
1. Press "Save"

**Expected behavior**
Rule should be saved and I should be able to reload the FW

**Workaround**

Set destination as single host or network. A new field is revealed which says "any", the destination is greyed out.
Be careful, every time you save the rule, it gets reset to destination = any and the bug will be back.

**Environment**

OPNsense 19.1.3 (amd64, OpenSSL).

**Comment by AdSchellevis** [comment]
looks like an intended side affect of https://github.com/opnsense/core/commit/a5505463abb92f7728b3ab953db7c58a9cd00dee

**Comment by AdSchellevis** [comment]
@oparoz thanks for reporting, should be fixable with:
```
opnsense-patch edc971d0
```
