### ISSUE TITLE
[feature request] IKEv2 Mobile Client implementation

### ISSUE THREAD

**Issue by yacob841** [opnsense/core#3306]
I would like the ability to route all of my networks traffic with IKEv2 to my VPN provider. They supply me with the hostname, username, and password to access the service. I have seen this option in a lot of consumer grade equipment, however those routers are too weak to handle the encryption so that is why I thought OPNSense would be perfect but I can't find an equivalent setting for me to use on OPNSense.

**Comment by AdSchellevis** [comment]
I think you better try our forum (https://forum.opnsense.org), this looks more of a "how to use" question.

**Comment by yacob841** [comment]
Hmm... I'll try that. I tried asking on Reddit and someone commented "We mainly support site-to-site or server mode for mobile clients. You're looking for a mobile client implementation to connect to a remote server. Unsure what this would take to implement, but this question is best raised here: https://github.com/opnsense/core/issues"
