### ISSUE TITLE
HAProxy > Public Services > Select Rules > one rule is always missing

### ISSUE THREAD

**Issue by mayerthomas** [opnsense/core#3308]
When I want to select rules for a public service (frontend), the dropdown always shows one rule less as i have defined in the rules section. 

Example: When I have defined 9 rules in the rules-section, only 8 rules are shown in the select-rules-dropdown of a public service.

I observed this behaviour on Firefox and Chromium.

Another wish: the dropdown list of rules should be orderd by rulename.

**Comment by fichtner** [comment]
That was https://github.com/opnsense/core/pull/3301 and fixed today in 19.1.4.

**Comment by mayerthomas** [comment]
Thank you!
Great job!
