### ISSUE TITLE
19.1.3 Firewall: NAT: Outbound Manual or Hybrid - no possible create rules !

### ISSUE THREAD

**Issue by JBBERLIN** [opnsense/core#3309]
Fresh 19.1.3 install, setting Outbound to manual or hybrid, then is no chance to add any rules that get "any" as source or destination, because every time you get follow error:

> The following input errors were detected:

    The field Source bit count is required.
    The field Destination bit count is required.

**Comment by fichtner** [comment]
https://github.com/opnsense/core/issues/3303
