### ISSUE TITLE
firewall: floating rules and destination ports

### ISSUE THREAD

**Issue by fichtner** [opnsense/core#331]
cannot add rules with destination port (or range): edit page offers port, but it's not saved

**Comment by AdSchellevis** [comment]
almost there :) ... it's in the queue

**Comment by fichtner** [comment]
Great, just keeping a log of user feedback, adding issues.

**Comment by AdSchellevis** [comment]
thanks!

**Comment by AdSchellevis** [comment]
Page is completely restructured in the current dev version, changing dest port works fine now.

**Comment by rstander** [comment]
Is there a time frame when this will be released into stable release/updated firmware?
I want to lock down access from LAN to a DMZ interface, but the destination ports are not saved.

**Comment by AdSchellevis** [comment]
did you select tcp or udp? when proto is any, a port is not applicable. This code is certainly in the current version.

**Comment by rstander** [comment]
Thanks for the extremely quick response. I had it set to tcp, but it did not apply. 

I had them all disabled, but after enabling again it started accepting it now. I’ll see if I can get a reproducible scenario.

 

Maybe just another quick question. When I do a tcp port scan of my public dns name port 80 and 8080 shows up as available. There are other ports too, but they have port forwards setup thus correct. 

The strange part is that I have the web ui set to use another port than 80, and redirect from 80 is disabled. Port 8080 is the proxy service port, but the proxy interfaces is only lan. So my logic says that 80 & 8080 should not show on a tcp port scan.

 

Regards

Riaan

**Comment by AdSchellevis** [comment]
I've checked with some of our boxes, but they don't show up as available on a portscan.
Maybe it's better to move this question / discussion to our forum, over here they will get lost rapidly.
