### ISSUE TITLE
Route-based IPsec: Gateway creation complains since IP is not configured on Interface

### ISSUE THREAD

**Issue by stumbaumr** [opnsense/core#3314]
**Describe the bug**

Testing Route-based IPsec:
https://github.com/opnsense/core/issues/2332
```
pkg install -f opnsense
opnsense-patch 8490bc7
```
Configure Phase2 as route based
Confirm tunnel works by pinging remote address

Create new gateway under system -> gateways

Error message
The gateway address "<remote IP address" does not lie within one of the chosen interface's IPv4 subnets.

**Expected behavior**

The ipsec1000 interfaces IP address is not configured in the interface. Either configure it their (somehow) or adjust/remove error message.

**Comment by AdSchellevis** [comment]
check "far gateway"

**Comment by stumbaumr** [comment]
I did that of course to continue. 

But the ipsec1000 interface and the remote address are basically on the same net, so the error message does not seem to fit...

**Comment by AdSchellevis** [comment]
no, they are not, the local address is /32, easy to overlook.

**Comment by stumbaumr** [comment]
Ah - true! Sorry, my mistake...
