### ISSUE TITLE
IPSec: strongswan unity plugin - UNITY_BANNER attribute needs double quotes

### ISSUE THREAD

**Issue by Kimotu** [opnsense/core#3317]
[X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[X] I have searched the existing issues and I'm convinced that mine is new.

**Describe the bug**
With a one line banner, it will not be shown in client, with multiline banner, strongswan will not start.

**To Reproduce**
1. Goto VPN: IPsec: Mobile Clients
2. Set Login Banner
3. Restart VPN service
4a. See no login banner if it is a single line
4b. VPN service will fail to start if banner was multi line

**Expected behavior**
Successful start of VPN service and bannern shown to client

**Hot to fix it**
Use double quotes to attribute UNITY_BANNER (28672)
```
plugins {
        attr {
            28672 = "Welcome to VPN"
       }
}
```
At the moment it looks like:
```
plugins {
        attr {
            28672 = Welcome to VPN
       }
}
```

**Environment**
OPNsense 19.1.3-amd64
FreeBSD 11.2-RELEASE-p9-HBSD
OpenSSL 1.0.2r 26 Feb 2019

**Comment by AdSchellevis** [comment]
@Kimotu Thanks for the report, https://github.com/opnsense/core/commit/c8e905c4048924ce94b8c5e37b0166c3c7252cef  should fix it
