### ISSUE TITLE
ipsec: PFS mobile setting written to any phase 2

### ISSUE THREAD

**Issue by stumbaumr** [opnsense/core#3323]
**Describe the bug**
Created IPsec Mobile Client Settings and activated Phase2 PFS Group and set it to 2 (1024 bits).

Created a route-based IPsec Tunnel and set Phase2 PFS Group to 14.

In ipsec.conf the route-based entry has the ESP modified from the Mobile client setting.

**To Reproduce**
See above.

**Expected behavior**
The Mobile Client Phase2 PFS Group should only modify Mobile Clients IPsec. I actually see no benefit from having that setting in Mobile Client at all, since even for the mobile clients we have to create a Phase2 manually...

**Environment**
Software version used and hardware type if relevant.

OPNsense 19.1.4 (amd64, OpenSSL).

**Comment by mimugmail** [comment]
When you set PFS group on mobile VPN page it always overrides the one on P2

**Comment by stumbaumr** [comment]
I don't think it should do that for a non-Mobile IPsec connection... or at least it should be somewhere documented that it does...

Use case:
IPsec mobile clients connect to the opnsense in the office. From there they get routed over a IPsec tunnel to various datacenters of various partners. Some of those require PFS 21, other 14, other do not care at all...

So it was quite time consuming to find out that this "Mobile Client" setting also fiddled around in our other tunnels...

**Comment by fichtner** [comment]
A proposed solution to a problem relating to a setting that in all likelihood users already rely on for their daily use should be put forward that addresses concerns of backwards-compatibility and improving POLA at the same time. I'm sure "I don't think it should do that"does not cover these requirements.

**Comment by stumbaumr** [comment]
`overrides all **mobile** phase2 settings`

...and in the route-based IPsec routes as well...

**Comment by fichtner** [comment]
Should we adjust the help text accordingly? IMO if it's a real issue that can't be documented I'd rather see this override gone. But that would require analysis why this setting exists in the first place.

**Comment by stumbaumr** [comment]
Just had a look into the code. It seems really to do it for all of them. So adjusting the help text should fix that, but...

As far as I understand the Mobile Client PFS group is also set in the attr plugin in strongswan and the sent to clients that understand the attr.

So if it is set of course the Phase 2 should be set accordingly - but only for that one mobile connection... and not for all of the ipsec connections...
