### ISSUE TITLE
HA, multi-WAN, fail over with state sync enabled causes return packets to route out of the default gateway

### ISSUE THREAD

**Issue by iMiMx** [opnsense/core#3324]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[-] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

ACK

[-] I have searched the existing issues and I'm convinced that mine is new.

ACK, as far as I can tell.  I have previously raised this under the General forum, I have since performed more searches and reviewed all configuration/subnet masks/CARP config again.

https://forum.opnsense.org/index.php?topic=11933.0

**Describe the bug**
- Single IP from the ISP for WAN1, which is configured as a CARP VIP with RFC1918 on Node A and Node B interfaces.
- A further /27 subnet is routed to the single CARP IP for WAN1
- IP aliases are set up for the same VHID as WAN1 CARP
- WAN2 has the default gateway, all IP addresses are externally reachable/routeable (non-rfc1918) for both nodes and CARP.

When I perform a fail over from Node A -> Node B, with state synced, the IP aliases fail over correctly.  However, the egress packets for 80.x.x.0/27 IP aliases are routed out of the default WAN2 gateway once failed over to Node B.  If I clear the state on the firewall, things then sort themselves out.

Node A
WAN1: 10.0.0.1/30 (RFC1918)
WAN2: 37.x.x.1/27 (Default GW)

Node B
WAN1: 10.0.0.2/30 (RFC1918)
WAN2: 37.x.x.2/27 (Default GW)

CARP:
WAN1 VIP: 78.x.x.1/30 (Single IP from ISP)
WAN2 VIP: 37.x.x.3/27

IP Aliases:
80.x.x.1/27 - WAN1 (routed by ISP to 78.x.x.1). 
80.x.x.2/27 - WAN1 (routed by ISP to 78.x.x.1).
80.x.x.3/27 - WAN1 (routed by ISP to 78.x.x.1).
...
80.x.x.30/27 - WAN1 (routed by ISP to 78.x.x.1). 

Gateways, monitoring disabled for both:
WAN1: 78.x.x.2/30
WAN2: 37.x.x.30/27 (Default GW)

**To Reproduce**
Setup as per the above, multi-wan, with IP aliases on the non-default-gateway WAN.  With state sync enabled, the egress/return packets route out of the default gateway, rather than the gateway for the specified WAN.  With state sync disabled, fail-over happens, correct routing is seen.

**Expected behavior**
Fail over nodes, correct routing for the IP aliases out of their gateway (not the default gateway) as specified in the pf rules.

`pass out log route-to (em0 78.x.x.2) inet from 86.x.x.1 to ! (em0:network) flags S/SA keep state allow-opts label "let out anything from firewall host itself"`

**Relevant log files**
Traffic is seen egress on the default gateway WAN2, rather than the correct WAN1.

**Additional context**
I have checked all subnet masks, there are no /32s (point made in pfSense docs), all have correct subnets.  All works fine with state sync disabled.  

It seems almost as if, after fail over, the pf rule to route to the correct GW is ignored and instead it takes the default route via WAN2 37.x.x.30/27 rather than WAN1 78.x.x.2.

`pass out log route-to (em0 78.x.x.2) inet from 86.x.x.1 to ! (em0:network) flags S/SA keep state allow-opts label "let out anything from firewall host itself"`

**Environment**
Software version used and hardware type if relevant.
test

OPNsense 19.1.4-amd64FreeBSD 11.2-RELEASE-p9-HBSD
OpenSSL 1.0.2r  26 Feb 2019
CPU Type | Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz (8 cores)

**Comment by iMiMx** [comment]
Just attempted on 19.1.7, same problem still seen - only occurs when state sync is enabled, with it disabled traffic routes to the correct gateway/internet.

**Comment by fichtner** [comment]
Timeout as per https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
