### ISSUE TITLE
PPPoE MTU issue in 19.1.3

### ISSUE THREAD

**Issue by djhau** [opnsense/core#3327]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[-] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[-] I have searched the existing issues and I'm convinced that mine is new.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Relevant log files**
If applicable, information from log files supporting your claim.

**Additional context**

**Environment**
Software version used and hardware type if relevant.
e.g.: 

OPNsense 19.1.1 (amd64, OpenSSL).  
Intel® Xeon™ E3-1225V5 3.3Ghz Quad Core
Network Intel® I210-AT

**Comment by AdSchellevis** [comment]
???

**Comment by AdSchellevis** [comment]
spam

**Comment by djhau** [comment]
With a PPPoE interface configuration setting the MTU to 1500 results in PPPoE MTU of 1492, which is fine, but if you ping with DF set to a packet size over 1492, no ICMP packet too big message is generated.

![Screen Shot 2019-03-14 at 5 50 10 am](https://user-images.githubusercontent.com/32971051/54308052-144b8400-461d-11e9-9f87-9e6611c7c843.png)


dhunt@Debian:~$ ping -s 1464 -M do 150.101.32.161
PING 150.101.32.161 (150.101.32.161) 1464(1492) bytes of data.
1472 bytes from 150.101.32.161: icmp_req=1 ttl=249 time=6.65 ms
1472 bytes from 150.101.32.161: icmp_req=2 ttl=249 time=9.91 ms
1472 bytes from 150.101.32.161: icmp_req=3 ttl=249 time=6.70 ms
1472 bytes from 150.101.32.161: icmp_req=4 ttl=249 time=6.72 ms
1472 bytes from 150.101.32.161: icmp_req=5 ttl=249 time=7.14 ms
1472 bytes from 150.101.32.161: icmp_req=6 ttl=249 time=6.79 ms

*** No ICMP packet too big messages received ***
dhunt@Debian:~$ ping -s 1465 -M do 150.101.32.161
PING 150.101.32.161 (150.101.32.161) 1465(1493) bytes of data.
^C
--- 150.101.32.161 ping statistics ---
14 packets transmitted, 0 received, 100% packet loss, time 13103ms

dhunt@Debian:~$

OPNSense 19.1.3
VMWare ESXI 6.7.0
VMSwitch and interface set to MTU 1500
CPU E5-2430 0 @ 2.20GHz
NIC - Broadcom BCM 5720
