### ISSUE TITLE
IPsec Mobile Client: Windows 10 client does not honor more than one leftsubnet

### ISSUE THREAD

**Issue by stumbaumr** [opnsense/core#3331]
**Describe the bug**
We want to use Windows 10 as IKEv2 Mobile Clients with split-tunneling. Therefore we configured more than one leftsubnet (more than one Phase2 so to speak). The Windows 10 IKEv2 client only honors the first entry in the leftsubnet. All other leftsubnets are ignored.

This is expected behaviour:
https://wiki.strongswan.org/projects/strongswan/wiki/WindowsClients#Split-routing-on-Windows-10-and-Windows-10-Mobile
(I just had to scream as I found this googling!!!)

According to `ipsec statusall` the dhcp plugin (https://wiki.strongswan.org/projects/strongswan/wiki/DHCPPlugin ) required for this is not enabled.

So from my point of view multiple split-tunnel networks never worked for some clients.

I can not decide if this is a bug or a feature request. But to continue to make Windows 10 clients work the strongswan dhcp plugin is required.

**To Reproduce**
Create two Mobile Client Phase 2 Entries and connect using a Windows 10 client.

Check `route PRINT` output and look for the leftsubnets. Only the first one will show.

**Expected behavior**
Windows 10 IKEv2 Clients should behave like Linux, MacOS, iOS clients...

**Environment**
Software version used and hardware type if relevant.

OPNsense 19.1.4 (amd64, OpenSSL).

**Comment by mimugmail** [comment]
Really? I have a customer using this, never heard of any problems. 
Have you tried setting the other routes manually?

**Comment by stumbaumr** [comment]
What do you mean by setting the routes manually (Like everytime the mobile user connects asking for a teamviewer session and adding routes on the client manually?)?

Maybe I have to elaborate:
- Windows 10 built-in IKEv2 client
- leftsubnet = 10.0.0.0/8,173.194.0.0/16,172.217.0.0/8

So the last two ranges are external and should be routed for the client through the split tunnel and accessed using the OPNsense WAN.

It works properly for a MacOS or IOS client. For Win10 we get an access denied, since only the Firewalls WAN IP is allowed to connect...

I am going to try setting a route manually and see if it is at least working like that...

**Comment by mimugmail** [comment]
I remeber the customer had some kind of script, also connecting shared after setting the routes

**Comment by stumbaumr** [comment]
So this is how the routing table looks like before connecting to the VPN
```
C:\Users\rosa>route PRINT
===========================================================================
Schnittstellenliste
  1...........................Software Loopback Interface 1
 17...1c c1 de 5f bb a8 ......Intel(R) 82567LM-3 Gigabit Network Connection
===========================================================================

IPv4-Routentabelle
===========================================================================
Aktive Routen:
     Netzwerkziel    Netzwerkmaske          Gateway    Schnittstelle Metrik
          0.0.0.0          0.0.0.0    192.168.178.1   192.168.178.47    200
        127.0.0.0        255.0.0.0   Auf Verbindung         127.0.0.1    331
        127.0.0.1  255.255.255.255   Auf Verbindung         127.0.0.1    331
  127.255.255.255  255.255.255.255   Auf Verbindung         127.0.0.1    331
    192.168.178.0    255.255.255.0   Auf Verbindung    192.168.178.47    356
   192.168.178.47  255.255.255.255   Auf Verbindung    192.168.178.47    356
  192.168.178.255  255.255.255.255   Auf Verbindung    192.168.178.47    356
        224.0.0.0        240.0.0.0   Auf Verbindung         127.0.0.1    331
        224.0.0.0        240.0.0.0   Auf Verbindung    192.168.178.47    356
  255.255.255.255  255.255.255.255   Auf Verbindung         127.0.0.1    331
  255.255.255.255  255.255.255.255   Auf Verbindung    192.168.178.47    356
===========================================================================
Ständige Routen:
  Keine

IPv6-Routentabelle
===========================================================================
Aktive Routen:
 If Metrik Netzwerkziel             Gateway
  1    331 ::1/128                  Auf Verbindung
  1    331 ff00::/8                 Auf Verbindung
===========================================================================
Ständige Routen:
  Keine
```

This is what it looks like after connecting
```
C:\Users\rosa>route PRINT
===========================================================================
Schnittstellenliste
 29...........................Contoso VPN
  1...........................Software Loopback Interface 1
 17...1c c1 de 5f bb a8 ......Intel(R) 82567LM-3 Gigabit Network Connection
===========================================================================

IPv4-Routentabelle
===========================================================================
Aktive Routen:
     Netzwerkziel    Netzwerkmaske          Gateway    Schnittstelle Metrik
          0.0.0.0          0.0.0.0    192.168.178.1   192.168.178.47    200
         10.0.0.0        255.0.0.0   Auf Verbindung       10.20.35.35     26
      10.20.35.35  255.255.255.255   Auf Verbindung       10.20.35.35    281
   10.255.255.255  255.255.255.255   Auf Verbindung       10.20.35.35    281
   VPN.Gateway.IP  255.255.255.255    192.168.178.1    192.168.178.47    101
        127.0.0.0        255.0.0.0   Auf Verbindung         127.0.0.1    331
        127.0.0.1  255.255.255.255   Auf Verbindung         127.0.0.1    331
  127.255.255.255  255.255.255.255   Auf Verbindung         127.0.0.1    331
    192.168.178.0    255.255.255.0   Auf Verbindung    192.168.178.47    356
   192.168.178.47  255.255.255.255   Auf Verbindung    192.168.178.47    356
  192.168.178.255  255.255.255.255   Auf Verbindung    192.168.178.47    356
        224.0.0.0        240.0.0.0   Auf Verbindung         127.0.0.1    331
        224.0.0.0        240.0.0.0   Auf Verbindung    192.168.178.47    356
        224.0.0.0        240.0.0.0   Auf Verbindung       10.20.35.35    281
  255.255.255.255  255.255.255.255   Auf Verbindung         127.0.0.1    331
  255.255.255.255  255.255.255.255   Auf Verbindung    192.168.178.47    356
  255.255.255.255  255.255.255.255   Auf Verbindung       10.20.35.35    281
===========================================================================
Ständige Routen:
  Keine

IPv6-Routentabelle
===========================================================================
Aktive Routen:
 If Metrik Netzwerkziel             Gateway
  1    331 ::1/128                  Auf Verbindung
  1    331 ff00::/8                 Auf Verbindung
===========================================================================
Ständige Routen:
  Keine
```

So there are two of the leftsubnets missing.

Looking at VPN Connection for the SplitTunneling state
```
PS C:\Users\rosa> Get-VpnConnection


Name                  : Contoso VPN
ServerAddress         : VPN.Gateway.IP
AllUserConnection     : False
Guid                  : {1B70F902-333C-43FA-ACD6-C4E291897952}
TunnelType            : Ikev2
AuthenticationMethod  : {Eap}
EncryptionLevel       : Required
L2tpIPsecAuth         :
UseWinlogonCredential : False
EapConfigXmlStream    : #document
ConnectionStatus      : Connected
RememberCredential    : False
SplitTunneling        : True
DnsSuffix             :
IdleDisconnectSeconds : 0
```

So to add a route
```
netsh interface ipv4>add route 173.194.0.0/16 "Contoso VPN"
Für den angeforderten Vorgang sind erhöhte Rechte erforderlich (Als Administrator ausführen).
```
one would have to be local administrator.

I do not think that is the correct direction to go here.

And how would a script be executed as soon as the IKEv2 VPN client starts?

**Comment by stumbaumr** [comment]
So maybe I have been to long away from Windows Administration...
https://serverfault.com/questions/740142/how-to-add-persistent-route-for-2-vpn-connections-when-interface-varies

```
Add-VpnConnectionRoute -ConnectionName "VPN Connection Name" -DestinationPrefix 10.0.0.0/16
```
does the trick and is persistent. So after reconnecting the route is there again...

Excellent!!! And thanks for the hint, @mimugmail

**Comment by AdSchellevis** [comment]
@stumbaumr you can contribute to the docs here https://github.com/opnsense/docs, thanks in advance!

**Comment by stumbaumr** [comment]
Still have to work on the VPN for Linux Mint and Chromebooks.... but yeah, I think I should write a HowTo with our specific setup...

**Comment by mimugmail** [comment]
Would be awesome :)

**Comment by stumbaumr** [comment]
So Linux Mint with bionic underneath seems to have this bug... which breaks DNS resolution...
https://bugs.launchpad.net/ubuntu/+source/strongswan/+bug/1772705

So VPN for Linux Mint has been worked on...

**Comment by stumbaumr** [comment]
HowTo is done: https://forum.opnsense.org/index.php?topic=12147.0
