### ISSUE TITLE
Feature Request: Fetch CRL from URL

### ISSUE THREAD

**Issue by MatthiasLohr** [opnsense/core#3335]
**Problem Description**

When dealing with multiple Certificate Authorities, one has also manage the Certificate Revocation Lists (CRLs). Managing it on a manual basis (downloading it from a known URL, copy&paste it into the admin interface) is a really boring and unnecessary work.

**Solution Proposal**

It would be great if there would be a third option when adding a CRL: "Fetch from URL". The specified URL should be stored and the according CRL should be downloaded based on a cronjob, so no manual work is needed anymore.

Best regards
Matthias

**Comment by fichtner** [comment]
Hi Matthias,

Merging CRL is difficult as we assemble a CRL from the serial numbers revoked each time-- no actual CRL involved at this point.

Merging would indicate reading an existing CRL and then building on top of it. It's not impossible but largely outside of our core missing of OPNsense begin the actual certificate authority so if there's really no other way around this it needs to be contributed from someone within the community.


Cheers,
Franco

**Comment by MatthiasLohr** [comment]
I'm not sure if we are talking about the same. I'm talking about the situation, where there private key for the CA is not stored on the OPNSense device. In this case, CRLs are generated somewhere else and have to be copy&pasted to OPNSense. There is no merging in this process, just transferring a CRL from an existing source to OPNSense. The only thing I propose in this task is to help to automate this process, since currently you have to update it manually.

**Comment by mimugmail** [comment]
The Trust section is not API enabled so the only option is to mangle /conf/config.xml by hand or something like ansible xml module.
If crl is already created to can have a look at gencert php scripts from Radius plugin, should be able to fetch them via http and put in the config.

**Comment by MatthiasLohr** [comment]
@mimugmail, I'm not sure if I understand your comment correctly, so I try to clarify what I mean to avoid further misunderstandings.

Let's use [CAcert](http://www.cacert.org/) as an example for an existing CA. They provide their certificates and CRLs here: http://www.cacert.org/index.php?id=3. I can easily import the certificates by downloading the files and copy&paste the contents into OPNsense. This is ok to be a manual process, since the certificates do not change that often. But for CRLs, it's important to have fast updates.

For now, the process is: Downloading the CRL manually and copy&paste the contents here: 
![image](https://user-images.githubusercontent.com/781926/65018696-ff341280-d929-11e9-970b-8c3fff46e96f.png)

What I now suggest, could be implemented in two steps:

First, instead of having a field for the CRL contents, there should be the option do use an URL instead of the final CRL and some kind of refresh button. Every time I press this refresh button, OPNsense should download the file located behind this URL and replace the CRL contents with the content found using this URL. Since the Webinterface is obviously able to modifiy the CRL configuration at this point, just fetching contents from an URL and then doing the already implemented configuration update stuff shouldn't be a problem in my opinion. One could even keep the CRL text field, so the user is free to update it manually or by using the URL+refresh button.

In the next step, I just want an automation for the new refresh button, based on a cronjob.

I think this Feature Request is security relevant, since an outdated CRL can have huge security impacts (certificates are revoked, if there's a urgent problem and you can't wait until it expires). This is not a problem at all if the OPNsense internal CA functionality is used, but for integration in existing infrastructures with existing CAs it would be a major point for PKI security.

**Comment by mimugmail** [comment]
@MatthiasLohr everything you enter in UI is saved as xml in /conf/config.xml, just have a look at the file. You can also edit it manually or by any parser and the UI will recognize it.

**Comment by MatthiasLohr** [comment]
But that still doesn't resolve my problem since this config has to be distributed to OpenVPN etc. and all other places, where the CRL gets processed. Maybe I can implement it for myself as an (really) ugly hack, but I think it would be a great security improvement if it's done the professional way and integrated in OPNsense.

**Comment by fichtner** [comment]
Aha, actually OpenVPN is where the rubber meets the road... Local CRL is only ever used in OpenVPN server instances. So you have an external CA and you want external CRL support.

The thing is, as previously mentioned, we don't have a real CRL in the config.xml. It only stores the contents of the CRL so we can't dump CRLs into the config.xml as we would constantly need to sync it. Especially if there are no moving parts it's questionable to store it permanently if some other location will give us the fresh CRL that OpenVPN actually needs to operate.

So when using an external Client CA you want something that fetches the CRL to OpenVPN say once a day for it to work correctly under the restrictions imposed by said external CA ?

**Comment by MatthiasLohr** [comment]
> The thing is, as previously mentioned, we don't have a real CRL in the config.xml. It only stores the contents of the CRL [...]

Sorry, I don't get this. What's the difference between a real and a non-real CRL? A CRL is just a string, usually - but not necessarily - written to a file.
> [...] so we can't dump CRLs into the config.xml as we would constantly need to sync it.

But how does it currently work? Somehow, the interface shown in the screenshot above does it. Do I understand correctly that your main criticism is that the automated (e.g. daily) update would be too much overhead by parsing the rest of the file and only replacing this single variable? How is a CRL currently passed to OpenVPN?

> So when using an external Client CA you want something that fetches the CRL to OpenVPN say once a day for it to work correctly under the restrictions imposed by said external CA?

At the end, yes, that would solve my current problem. I thought that CRLs might be used in more places (in OPNsense) than only OpenVPN. If that is the case, then of course an automated update of the CRL should not only affect OpenVPN but anything else connected with this CA/CRL. If OpenVPN is the only point where it is used, than it's sufficient to have that for OpenVPN (but should somehow be scalable if more use cases for CRLs in OPNsense coming up).

**Comment by fichtner** [comment]
> Sorry, I don't get this. What's the difference between a real and a non-real CRL? A CRL is just a string, usually - but not necessarily - written to a file.

No, a CRL is a signed list of revoked certificates in a special ASN1 format, Base64 encoded or not. 

The config.xml stores your revocations, but not the CRL. No CA private key = no signature = no CRL. As such there's no point in reverse-engineer-storing revocation status of external CAs in the config.xml because we can't rewrite the CRL file because we don't have the private key. But maybe this is besides the point /use case entirely.

> But how does it currently work? Somehow, the interface shown in the screenshot above does it. Do I understand correctly that your main criticism is that the automated (e.g. daily) update would be too much overhead by parsing the rest of the file and only replacing this single variable? How is a CRL currently passed to OpenVPN?

We have to assume a CRL is generated from the private key of the CA and the revocation information stored in the config.xml and OpenVPN is presented a file it can use. We're not necessarily here to explain reviewable open source code that actually works and we don't use it to infer that other use cases are supposed to work because something we don't know how it works works already. ;)

> At the end, yes, that would solve my current problem. I thought that CRLs might be used in more places (in OPNsense) than only OpenVPN.

Not to my knowledge, no.

> In that case, then of course an automated update of the CRL should not only affect OpenVPN but anything else connected with this CA/CRL. If OpenVPN is the only point where it is used, than it's sufficient to have that for OpenVPN (but should somehow be scalable if more use cases for CRLs in OPNsense coming up).

We don't need a bakery to make pancakes here. You have to be aware of the fact that not all people even use a CRL with their X.509 client auth, if they use it at all and don't mix it with user passwords that supersede revocation status requirement as well.

The more precise the request, the less code and friction in the implementation.

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository, 
please read https://github.com/opnsense/core/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue, 
just let us know, so we can reopen the issue and assign an owner to it.

**Comment by MatthiasLohr** [comment]
180 days of inactivity?! Is my math that wrong or yours? Last activity was 2019-09-1, for me the timediff is 51 days...
