### ISSUE TITLE
VPN IPsec Mobile Client: Generating strongswan.conf eap-radius plugin setting from vpn_ipsec_mobile.php instead of Phase1

### ISSUE THREAD

**Issue by stumbaumr** [opnsense/core#3339]
**Is your feature request related to a problem? Please describe.**
Going through my current setup using bespoke include files for strongswan I realised that the information on how to setup the eap-radius plugin in strongswan.conf is already existing in vpn_ipsec_mobile.php. But currently have to set it up using a strongswan.conf include file since I do not create a mobile phase 1.

**Describe the solution you'd like**
Would a PR be acceptable to move the functionality from Tunnel Phase 1 to Mobile Client? Or are there any obstacles?

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository, 
please read https://github.com/opnsense/core/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue, 
just let us know, so we can reopen the issue and assign an owner to it.
