### ISSUE TITLE
Router Advertisements: 'Advertise Default Gateway' setting not working

### ISSUE THREAD

**Issue by maurice-w** [opnsense/core#3343]
**Describe the bug**
Enabling 'Advertise Default Gateway' in the 'Router Advertisements' settings adds a `::/0` route to RAs, disabling it removes that route. This is not the correct way of (not) advertising a default gateway: Receipt of **any** RA with Router Lifetime > 0 will cause hosts to install a default route to the RA's source address, so advertising a `::/0` route is redundant at least. This also means that disabling 'Advertise Default Gateway' does not stop hosts from installing a default route (because the Router Lifetime in RAs is still > 0).

**To Reproduce**
1. Go to 'Services' / 'Router Advertisements' / 'LAN'
2. Enable 'Advertise Default Gateway' and save
3. Do a packet capture on the LAN interface and have a look at the RAs. They contain route information for `::/0` (which is redundant).
4. Go to 'Services' / 'Router Advertisements' / 'LAN'
5. Disable 'Advertise Default Gateway' and save
6. Check whether hosts in the LAN still use OPNsense as their default gateway. Spoiler: They do, which means that this setting does not have the desired effect.
7. Do a packet capture on the LAN interface and have a look at the RAs. They don't contain route information for `::/0` (good), but the Router Lifetime is > 0 (bad).

**Expected behavior**
- RAs should never contain route information for `::/0`.
- Disabling 'Advertise Default Gateway' should set the Router Lifetime to 0.

**Additional context**
[RFC 4861 (Neighbor Discovery for IP version 6 (IPv6))](https://tools.ietf.org/html/rfc4861)
> A router might want to send Router Advertisements without advertising itself as a default router. For instance, a router might advertise prefixes for stateless address autoconfiguration while not wishing to forward packets. Such a router sets the Router Lifetime field in outgoing advertisements to zero.

**Environment**
OPNsense 19.1.4-amd64

**Comment by fichtner** [comment]
@maurice-w please double-check e67dade

**Comment by maurice-w** [comment]
Thanks @fichtner, works as expected after applying the patch to 19.7.a_701 and re-saving the RA config.

**Comment by fichtner** [comment]
@maurice-w Thanks for testing. Side question, does the CARP feature mentioned in the patch make sense to you? (using RemoveRoute off / DeprecatePrefix off)

**Comment by maurice-w** [comment]
@fichtner So if I get this correctly, the intention is to prevent radvd from deprecating the advertised routes and prefixes if an interface is shut down but happens to be a CARP interface? Because from a host perspective nothing changes? Sounds good to me. `FlushRDNSS` and `FlushDNSSL` should consequently be turned off, too.

What we probably can't prevent is radvd setting the Router Lifetime to 0 in the shutdown RA. At least I can't find an option for that.

Do you know if radvd gets shut down _before_ a CARP interface goes down? So does it actually send a shutdown RA?

**Comment by fichtner** [comment]
@maurice-w Radvd isn't shutting down on the backup in normal operation mode and if it crashes it can't send a shutdown RA anyway. I'm unsure about flushing RDNSS/DNSSL because the routers advertise their own IP, not the CARP (you can only use CARP IP for responding) so the other node needs to advertise its IP as well and clients should flush indeed. In that sense it's a little weird because both nodes' Radvd is running and advertising, you just don't want it to strip routes in case one shuts down (which can't really happen).

As said in the commit, the CARP support is pretty weird and I'm not sure anyone uses it.

But then again we still don't HUP radvd and always restart when necessary on IPv6 changes, which might be part of the issue. Should we maybe switch that behaviour in general?

**Comment by maurice-w** [comment]
@fichtner, about the CARP issue: First, I don't have a CARP setup, so take these thoughts with caution:
- The routers advertising their own IP addresses as RDNSS (instead of the CARP virtual IP) seems a bit odd. Is that intentional? Does DHCPv6 / DHCPv4 do the same thing?
- In many scenarios (especially HA) DNS resolvers run on separate boxes, not on the routers. So no need to flush RDNSS on a router failover.
- DNSSL won't change because of a router failover so no need to flush this.
- radvd running on all CARP nodes all the time seems weird indeed. That makes all of this pretty hypothetical anyway. :-) But in general, preventing zero lifetimes in shutdown RAs makes sense in a CARP scenario. radvd might get shut down on one node accidentally or when doing maintenance.

About reloading vs. restarting radvd on IPv6 changes in general:
- Restarting makes things easy. radvd can do the cleanup automatically by sending a shutdown RA with zero lifetimes for pretty much anything it advertises. But:
- This causes interruption in the LAN. All hosts drop their auto-configured addresses, routes, connections etc. - see #3415.
- Just reloading the radvd config (without a restart) on IPv6 config changes allows the hosts to transition without interruption. But this is a multi-step procedure of changing and reloading the config several times. If not done correctly (e. g. not deprecating an old prefix) it can cause a mess. I think this better fits in #3415 so I'll come up with something and comment there.
