### ISSUE TITLE
Feature Request: Multiple ports per Shaping Rule

### ISSUE THREAD

**Issue by FingerlessGlov3s** [opnsense/core#3347]
**Problem**
When creating Shaper rules it would be nice if you can specify multiple ports per rule, instead of just one port/range at a time.

**Describe the solution you'd like**
Rather than one rule for port 22 and then another for say port 443. So the ability to just put 80,443,587 in the ports field, or if possible Alias support.

**Comment by FingerlessGlov3s** [comment]
Any news on this issue or will the shaper rules be getting Alias support?

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository, 
please read https://github.com/opnsense/core/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue, 
just let us know, so we can reopen the issue and assign an owner to it.
