### ISSUE TITLE
Firewall -> Aliases: Mark more than one line for deletion only deletes lowest entry

### ISSUE THREAD

**Issue by stumbaumr** [opnsense/core#3348]
**Describe the bug**
Goto Firewall -> Aliases, mark more than one entry, press the delete button on the bottom. There comes the pop-up, if you want to delete the selected items. But it will only delete the lowest entry

**To Reproduce**
Create 5 Alias entries. Mark three for deletion. It will only delete the lowest one.

**Expected behavior**
Marking the selected entries and pressing "Delete selected" should delete all of the selected.

**Environment**

OPNsense 19.1.4 (amd64, OpenSSL).

**Comment by fichtner** [comment]
Could it be https://github.com/opnsense/core/commit/7e25aa70a23a0b99ba53e45a376fcf249405e645 ?

**Comment by AdSchellevis** [comment]
@fichtner yes, noticed the same on my end last weekend, https://github.com/opnsense/core/commit/7e25aa70a23a0b99ba53e45a376fcf249405e645 locks before config read.
