### ISSUE TITLE
19.1.4: Monit Input validation

### ISSUE THREAD

**Issue by scheltowski** [opnsense/core#3350]
At the activation of monit in the web GUI the following error appears: "Input Validation Please correct validation errors in form"

Also a message
>The Monit configuration has been changed 
>You must apply the changes in order for them to take effect.

shows every time on changing to monit settings.

**To Reproduce**
1. Go to 'Services -> Monit -> Settings'
2. Click on 'Enable monit' and then 'save'

Or try to delete any of monit service tests.

**Expected behavior**
Enabling monit should be possible as well as deleting pre-installed service tests.

**Screenshots**
![2019-03-19 15_58_03-](https://user-images.githubusercontent.com/48724665/54617028-e0c78a00-4a60-11e9-858a-d649cebc37cb.png)
![2019-03-19 15_58_22](https://user-images.githubusercontent.com/48724665/54617012-ddcc9980-4a60-11e9-9531-f693296d2e0e.png)

**Relevant log files**
config[58846]: [OPNsense\Monit\Monit:test.2046d9af-27f8-4545-8436-f70b3f2fb378.type] Cannot change the type. Test is linked to a service.

**Additional context**
Probably here's a problem: https://github.com/opnsense/core/pull/3155/files#diff-ea3a2954359d1fa4526c676604094329R83

Worked well with 19.1.1

**Environment**
hw.model: Intel Xeon Processor (Skylake, IBRS)
hw.machine: amd64
hw.ncpu: 1

hw.physmem: 2058842112

**Comment by scheltowski** [comment]
Kind of workaround: download the configuration, remove all the monit related stuff then restore the config.

**Comment by AdSchellevis** [comment]
could this be the fix https://github.com/opnsense/core/commit/9746ebf8f19046cca1a01d4f3277ec7bf02e0595 ?

**Comment by fbrendel** [comment]
@AdSchellevis yes, it is.

The migration has failed and the error message goes out of scope too fast during an update.

**Comment by AdSchellevis** [comment]
ok, let's close it then.
