### ISSUE TITLE
Feature Request : add TAP and TUN interfaces management

### ISSUE THREAD

**Issue by elclaudio** [opnsense/core#3351]
It would be very nice to have the possibility (via the GUI) to create TAP and TUN interfaces by adding a new section in Interfaces / other types / Tun-Tap

Right now, it's pretty straightforward to create them via the console, but they don't survive a reboot unless you have a method to recreate them at each boot. Plus, they aren t saved with config.

There is many possible uses with this kind of interfaces, for exemple, you could affect different services to different virtual interfaces within the same subnet but with different ip. Or like I do, use them with virtualized environments like bhyve or jails. 

It should be simple to add this, I mean, I bet a few hours of coding or less for opnsense devs.

looking forward to it

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository, 
please read https://github.com/opnsense/core/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue, 
just let us know, so we can reopen the issue and assign an owner to it.

**Comment by beren12** [comment]
Would be nice to have this, for something like adguard to bind to so it can get an updated ip via dhcpv6 if your prefix changes (thanks comcast)
