### ISSUE TITLE
Web Proxy does not work on VLAN interfaces with CARP IP only

### ISSUE THREAD

**Issue by apas-iut** [opnsense/core#3353]
[x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[x] I have searched the existing issues and I'm convinced that mine is new.

**Describe the bug**
Whenever you try to add VLAN interface to Web Proxy changes do not come to daemon settings file.

**To Reproduce**
1. Setup a Web Proxy on LAN interface
2. Add VLAN interface with one or more IP addresses to "Proxy interfaces" list and click Apply.
3. Check the squid configuration file `/usr/local/etc/squid/squid.conf` or just the output of `sockstat -l | grep 3128`
4. There is not VLAN IP addresses in the output

**Expected behavior**
VLAN IPs with opened 3128 port

**Additional context**
If I remove LAN interface and leave only VLAN interface in Web Proxy settings then nothing changes in output.

**Environment**
OPNsense 19.1.4-amd64
FreeBSD 11.2-RELEASE-p9-HBSD
It is VM in ESXi 5.5

**Comment by AdSchellevis** [comment]
static ip defined? you can not bind the proxy to dhcp interfaces.

**Comment by apas-iut** [comment]
all my interfaces have static IPs only.

**Comment by AdSchellevis** [comment]
not very logical, there shouldn't be a difference if an interface is either a vlan or a raw interface. More details might help, at my end this doesn't happen, but there aren't a lot of details in the ticket.

**Comment by apas-iut** [comment]
All my VLANs have CARP IP only. Probably the problem in this. Because VLAN interface by it self does not have any binded IP.

**Comment by apas-iut** [comment]
I did a test with fresh installation of OPNsense 19.1.4 in Vbox VM.
I made 3 interfaces:
1. LAN with static IPv4 address only.
2. VLAN22 with 1static and 1CARP IP.
3. VLAN33 with 1CARP IP only.

Then I gradually added these 3 interfaces into Web Proxy config.
1. LAN only - Ok
2. LAN+VLAN22 - Ok. 3 sockets are opened (2 for static IPs and 1 for CARP IP).
3. LAN+VLAN22+VLAN33 - NOk. Same 3 sockets are opened only. CARP IP from VLAN33 is not included into squid config.

@AdSchellevis what do you think is this a bug or a feature?
Actually I don't like the idea of forcing usage of additional IPs on every interface because it looks like a wastage of IP address space.

**Comment by AdSchellevis** [comment]
@apas-iut it looks like a bug, you likely have some errors in your log. can you try https://github.com/opnsense/core/commit/d8f656f1b791053899a04761a5d609015eb9006f ?

Install from console using:

```
opnsense-patch 47a3b241 d8f656f
```

(https://github.com/opnsense/core/commit/47a3b2419d4dfd994b2c7d79b7cbacc7f457d4e8 is only a small style fix blocking this diff)

**Comment by apas-iut** [comment]
@AdSchellevis I applied the patch to the same VM and tested scenario again. I can confirm that it works with all possible combinations of static IPs now.
Thank you for this rapid fix!

**Comment by fichtner** [comment]
Thanks, it'll be added to 19.1.5 :)
