### ISSUE TITLE
Cosmetic issues in: Firewall_schedule_edit.php

### ISSUE THREAD

**Issue by Northguy** [opnsense/core#3357]
Minor cosmetic issues: 
1) description of scheduled ranges in Firewall Schedule is displayed in HTML encoded string. Cannot find where/how to fix. See screenshot below.

2) Variable naming contains a typo. Tried to repair in commit 551d935c5ffd87fbd54e494a6ea718acde28328e but don't know how to cherrypick this commit into a pull request.

![2019-03-21_22-39-18](https://user-images.githubusercontent.com/1189058/54787281-96463900-4c2b-11e9-90a6-a3c549af8f15.png)

**Comment by AdSchellevis** [comment]
it's a bit tricky this one, the code underneath is horrible, I fixed some escape / xss issues after a tip from one of our users in https://github.com/opnsense/core/commit/80d94767a7f6dbb278ab1abfdba2ccc3c839a4fb , this probably is an unintended aside affect.

https://github.com/opnsense/core/commit/551d935c5ffd87fbd54e494a6ea718acde28328e likely puts the xss issue back in ;(

I'm open for other fixes, let's mark this as a bug for now.

**Comment by Northguy** [comment]
Hi Ad, I am not very experienced with PHP, but google mentioned URLdecode() of the string to remove the HTML entities? Tried it myself, but this only yielded a non responsive webpage.

Regarding issue 2) can you cherrypick my commit from my own fork?

**Comment by AdSchellevis** [comment]
The problem is that this code is Javascript, but as mentioned the page is horrible to maintain (needs a lot of work, not very high on our priority list).

Yes, I can pick a single commit from your fork, but since it will most likely reintroduce the same issue of script execution, I'm not going to.

**Comment by Northguy** [comment]
OK clear.

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository, 
please read https://github.com/opnsense/core/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue, 
just let us know, so we can reopen the issue and assign an owner to it.
