### ISSUE TITLE
FQDN Based Firewall rules

### ISSUE THREAD

**Issue by bigops** [opnsense/core#3359]
With more and more services moving to the cloud, many managed instances like databases and load balancers are only available via FQDN.  Many of the commercial firewalls now support FQDN based firewall rules where access can be permitted based on an FQDN in in the rules.  There seems to be an option to use FQDN in the Alisas, but it is not very clear if the Alias takes note of the DNS TTL to re-evaluate the FQDN.   

This request is to have FQDN as an option on the Firwall configuration window so that the rules can be better managed than having Alisas for each FQDN

**Comment by mimugmail** [comment]
The biggest problem is that cloud services have one name and multiple IP addresses behind, answering via round-robin. How should the Firewall handle this when the client itself does the DNS request?

**Comment by bigops** [comment]
So here is the issue that is at hand.   The client does the DNS request and say it gets an IP.  Normally in an enterprise setting all outbound connections are denied unless explicitly permitted.   When this request from the client hits the firewall unless there is an FQDN rule which is already evaluated and permitted the connection is blocked.   From what I understand is that the Firewall should continuously evaluate the FQDNs permitted based on their TTL values and update the firewall state table.

**Comment by AdSchellevis** [comment]
usually it doesn't, this either hooks into a centralised dns which feeds its knowledge to the firewall or more common just timeouts the entries requested from the firewall,  which you can already easily setup....
![image](https://user-images.githubusercontent.com/9783985/54827771-0a77ef80-4cb3-11e9-8705-fff709cee643.png)
