### ISSUE TITLE
Broken IPSec after 19.1.3

### ISSUE THREAD

**Issue by opthomas-prime** [opnsense/core#3360]
I realized this morning that several IPSec-connections are misbehaving. I didn't find any hints in the logs.
After some trial and error i checked _VPN -> IPSec -> Status Overview -> (i)_  and noticed, that there are multiple SPI's for a single Phase 2 configuration. For every additional connection attempt there would appear another SPI. All _Bytes out_ counters stayed on 0.
After reading some changelogs (IPSec-related changes in 19.1.3 and 19.1.4) i downgraded to 19.1.2 with `opnsense-revert -r 19.1.2 base`. All S2S connections are working again.
I actually downgraded to 19.1.3 first and it was still broken. So i'm pretty sure that the update 19.1.2 -> 19.1.3 broke it...
I'm surprised there are no other Issues/Tasks regarding this problem. I checked for configuration problems multiple times.
I checked the diff between 19.1.2 and 19.1.3. There are plenty of changes (Regarding NIC's/IPSec/Firewall-stuff which may introduce the problem) and i can't manage to check which change is the faulty one today. If you give me some pointers i will give my best to track the issue down ASAP.

**Comment by AdSchellevis** [comment]
for 19.1.4 it could be https://github.com/opnsense/core/commit/15b9be0369e390a8276946fa5dae1ac8fae4f85a 19.1.3 is almost the same as 19.1.2.

**Comment by opthomas-prime** [comment]
I'm pretty confident the downgrade to 19.1.2 did the trick - but well, i panicked a bit. I will update step-wise later when office gets emptier to reproduce the issue. When im on 19.1.4 i can apply your patch using `opnsense-patch`, right?

**Comment by AdSchellevis** [comment]
better wait for 19.1.5 in this case, the patch doesn't easily match

**Comment by opthomas-prime** [comment]
Alright! Thanks for the hint. I'll leave the issue open until i verified that 19.1.4 introduced the problem.

**Comment by opthomas-prime** [comment]
As announced by @AdSchellevis, the issue is resolved in 19.1.5. Thanks!
