### ISSUE TITLE
Multi-WAN broken

### ISSUE THREAD

**Issue by arhue** [opnsense/core#3364]
Using `OPNsense 19.1.4-amd64`(virtualised on Proxmox) and I have broken multi WAN. Both WAN gateways show 0 ms ping and 0% packet loss all the time, hence when one of the links goes down, it doesn't detect it to do the failover. I'm using PPPoE for uplinks.

![Screenshot from 2019-03-24 21-05-53](https://user-images.githubusercontent.com/9057510/54881734-f847ae00-4e78-11e9-9a8d-6b42b7ab2d38.png)

Open to give more info if needed.

**Comment by fichtner** [comment]
You may have your monitoring switched off (see gateway edit). Please don't use inflammatory subjects such as "xxx is broken" if you are looking for community support.

**Comment by arhue** [comment]
My intention was not to be inflammatory in any way. Sorry if I came across as such.

Found "Disable Gateway Monitoring" which I had missed and was the culprit. Sorry about this. Closing this issue.

**Comment by fichtner** [comment]
Happy to hear, thanks for the feedback. :)
