### ISSUE TITLE
Router Advertisements UI: "RA Sending" checkbox is redundant

### ISSUE THREAD

**Issue by maurice-w** [opnsense/core#3365]
In `services_router_advertisements.php`, the checkbox to enable / disable RAs ("RA Sending") is kind of buried in the settings. Strictly speaking not a bug, but since unchecking this makes all the other settings on this page irrelevant it should be at the top. This would also make it consistent with other configuration pages (DHCPv4, DHCPv6, Dnsmasq, Unbound etc.) where the `Enable` checkbox is always at the top.

**Comment by fichtner** [comment]
I'm not sure because "Router Advertisements" -> "Disable" is the authoritative spot and it is already on top and working as expected?

**Comment by maurice-w** [comment]
You're right, I forgot about this setting. So this gives us two redundant ways of disabling RAs:

- Setting "Router Advertisements" to "Disabled" completely removes the configuration for the interface from `radvd.conf`. This is the sledgehammer approach.
- Unchecking "RA Sending" only removes `AdvSendAdvert on` from `radvd.conf`, so this toggles the on / off switch.

Both settings result in no RAs being sent from the interface (as expected), but we only need one. I suggest removing the "Disabled" option from "Router Advertisements" and moving "RA Sending" to the top.

**Comment by fichtner** [comment]
The original issue was #945. I'm unable to follow your reasoning with regards to an underlying bug or feature request (both of those would demand code changes).

A question has been answered herewith so I hope we're good as is. :)


Cheers,
Franco

**Comment by maurice-w** [comment]
Thanks for pointing me to #945 where the "RA Sending" checkbox seems to have been introduced. There you wrote:
> One can now also completely disable advertisement sending and solicitation responding.

Which is what setting "Router Advertisements" to "Disabled" already did. The "RA Sending" checkbox is redundant because it does the same thing. It doesn't matter whether you remove the entire configuration or the `AdvSendAdvert on` line only.

By default, solicited RAs are sent as unicasts anyway (as recommended by RFC 7772). To disable multicast RAs, you would have to set `UnicastOnly on` (not recommended for most scenarios).

It seems you could use some help fixing the RA stuff (including #3343 and #3366)? I could write down what input fields / checkboxes should be available in the UI (including the help texts) and what each of them should put in `radvd.conf`. Unfortunately I currently can't help with the actual implementation.

**Comment by fichtner** [comment]
@maurice-w I'm happy about all help even if just what to configure and how. But I don't want to touch working areas for cleanups too much unless they are natural progression. This issue here is more of a split in terms of how useful that particular option in the daemon is in the scope of its integration, but not anything that is purely wrong or counter-intuitive.

That being said, always happy to review and implement with the help of users. :)

**Comment by maurice-w** [comment]
Thanks for cleaning this up, @franco. I understand that it makes things easier for the core team if such issues are not only reported, but also fixed right away by the users who report them.
However, while I can diagnose such things, at this point in time I don't feel confident to fix them myself. PHP and such is just something I've never touched.

It was my impression that properly investigating, documenting and reporting issues is an appreciated contribution, even when having to leave the actual fixing part to someone familiar with the OPNsense code. Please let me know if I got this wrong.
I'm aware I could have made this report easier to deal with by realising in the first place that it's not actually about a checkbox in the wrong place, but about a redundant checkbox. I'll try to be more thorough before creating future reports.

Cheers and thanks, again, for all your work
Maurice

**Comment by fichtner** [comment]
HI Maurice,

I apologise for being blunt. It is part of a general issue. You have helped a great deal and I thank you for it.

The code is relatively easy and all initial coding help very much improves the precision of your analysis and I think analysing it is the harder part vs. adding a preliminary PR. We're more than glad to go into code review, which looks at correctness, style tips and so on.

But I can understand if you do not want to open a PR in your case. The explanation is perfectly fine.

Forgive me for wanting more as it makes this project even better. I do have to try always. :)


Cheers,
Franco

PS: Poor guy @ .. franco .. it's not me and he doesn't enjoy being pinged by accident ;)

**Comment by maurice-w** [comment]
No worries! And sorry for mixing up your name; fixed it.
