### ISSUE TITLE
strongswan_enabled warning on acpi shutdown [probably harmless]

### ISSUE THREAD

**Issue by sjorge** [opnsense/core#337]
```/etc/rc.shutdown: WARNING: $strongswan_enable is not set properly - see rc.conf(5).```

**Comment by fichtner** [comment]
That is init shutdown code that shouldn't be executed, not sure how to hook into acpi to use our own reboot command instead. Will investigate.

**Comment by sjorge** [comment]
Well it seems to launch rc.shutdown as per the manpages: https://www.freebsd.org/doc/handbook/boot-shutdown.html

**Comment by fichtner** [comment]
/etc/rc.shutdown offers no override. There's /etc/rc.shutdown.local via /etc/rc.d/local, but that doesn't really help as we don't want it to trigger at all, not wrap inside the wrapper.  Can't solve this. :(
