### ISSUE TITLE
19.1.x dmesg missing timestamp

### ISSUE THREAD

**Issue by rantwolf** [opnsense/core#3371]
Hi.
Last weekend my opnsense machine hangs up.
Only a hard reset helped.
After this I was trying to read the log files and find out where the issue is located.
But I didn't see any timestamps in the dmesg log file.

I can enable this, but it doesn't survive an upgrade.
Is it possible to enable this by default in the firmware?

**Comment by fichtner** [comment]
The timestamps destroy parsing of dmesg entries so their use is not recommended at the moment. I know HardenedBSD enabled them by default but it breaks several things so it needs work to be able to work with them consistently.
