### ISSUE TITLE
Add support for plain interfaces in firewall rules

### ISSUE THREAD

**Issue by klada** [opnsense/core#3380]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[x] I have searched the existing issues and I'm convinced that mine is new.

**Is your feature request related to a problem? Please describe.**

Right now writing firewall rules such as "allow Internet access for LAN" requires a inverted destination match such as "allow all traffic to all destinations except !10.0.0.0/8".

For IPv4 in NAT environments this is possible, because you can simply exclude all private networks through an alias. For IPv6 with dynamic prefixes this is not possible at all right now. While support for dynamic IPv6 prefixes is handled by #2544 we could also make rules such as "allow Internet access" even easier by allowing rules to contain the actual outbound interface.

**Describe the solution you'd like**

Right now for firewall rules you can select

* **Interface Address**
* **Interface Network**
* Alias
* Custom IP

as a destination in firewall rules. It would be super-handy if, in addition to the options mentioned above, the actual **Interface** could be specified. This would make firewall rules even easier to read and write and even chaning IPv6 prefixes and subnets would not be an issue any more.

**Additional context**

The [German OPNsense forum](https://forum.opnsense.org/index.php?topic=12192.0) contains some details regarding the IPv6 problem which would be solved by this. This is however not only useful for IPv6 environments with changing prefixes, basically interface-based rules are an essential feature of many firewalls.

**Comment by klada** [comment]
> As far as I know you can't use the interface where a packet came from originally, other than collecting the networks from userspace and generate alias entries or rules with it.

The following rule was suggested on the forum:

```
pass in quick on em0 inet6 from any to nfe0 flags S/SA keep state
```

I actually don't know if this is a valid rule, but it looks legit to me. At least for someone coming from the iptables world.


> Are you sure your request isn't the same as #2544 from a different angle?

It isn't the same as #2544 but it would easily solve (part of) the problem mentioned there. And it would solve even more problems, by making firewall rules easier to write.

However I understand that if `pf` really cannot handle outbound interfaces in rules, this feature request is invalid. Sorry in that case.

**Comment by AdSchellevis** [comment]
You can easily test these things via a console and edit `/tmp/rules.debug` then load using `pfctl -f /tmp/rules.debug` if successful, you can add a label to track how this translates in `pf`.

For example: 

`pass in log on em2 inet from any to em1 flags S/SA keep state label "XXXX"
`

Then `pfctl -sr | grep XXXX`, would translate to something like:
```
pass in log on em2 inet from any to 10.111.15.2 flags S/SA keep state label "XXXX"
pass in log on em2 inet from any to 10.102.1.1 flags S/SA keep state label "XXXX"
````

Which are the associated addresses of em1.

I kind of expect for the rules you want to create you will need an alias serving the nets. You could probably easily script this, but I don't see a very practical easy to build generic solution at the moment.

**Comment by AdSchellevis** [comment]
@klada your welcome, it would have been nice if there was an easy fix.
