### ISSUE TITLE
19.1.5: IPsec includes are missing

### ISSUE THREAD

**Issue by stumbaumr** [opnsense/core#3387]
**Describe the bug**
With https://github.com/opnsense/core/pull/3311 the include functionality of StrongSwan was activated.
It seems that the directories are created with the upgrade, but the include statements are missing from the files (ipsec.conf, ipsec.secrets and strongswan.conf ...).

**To Reproduce**
Upgrade to 19.1.5 and check if the generated files contain an include statement at the bottom.

**Expected behavior**
Improve on cherry picking ;-) 

**Environment**
Software version used and hardware type if relevant.

OPNsense 19.1.5 (amd64, OpenSSL).

**Comment by fichtner** [comment]
It was left out intentionally. As you can see from #3311 we had not negotiated an ETA.

**Comment by stumbaumr** [comment]
So you create the directories on the OS but did not add the code for creating the includes?

Where do you negotiate the corresponding ETA? Since the PR is merged and closed...

**Comment by AdSchellevis** [comment]
@stumbaumr "we had **not** negotiated an ETA",  please stop wasting people's time like this. You can easily track what is either in a release by its tag or in a release when checking its branch (stable/19.1 in this case).

**Comment by fichtner** [comment]
It’s all in the dev version shipped alongside 19.1.5. I don’t think it’s necessary to criticise our release engineering for stable versions which has little to do with your request here.

 Most changes go through development version to next major release (19.7). Backports are made consciously based on positive impact. The change at hand is not a necessity for 19.1 by any means.

I’m happy to explain and backport, but only when requests are made in a civil manner and unclear procedures are not automatically labelled as fundamentally broken.

**Comment by stumbaumr** [comment]
Sorry if I stepped on your toes. Did not mean any offense.

The release procedure was indeed unclear to me. I had the impression that merged ment it would be included in the next release.
