### ISSUE TITLE
19.1.5: Cannot save aliases any more

### ISSUE THREAD

**Issue by klada** [opnsense/core#3389]
**Describe the bug**
I just upgraded from 19.1.4 to 19.1.5 and noticed that you cannot click "Save" in the alias interface any more.

**To Reproduce**
1. Go to 'Firewall -> Aliases'
2. Click on 'Add new Alias'
3. Click "Save"
4. Nothing happens

**Expected behavior**
Alias should be saved.

**Environment**
Software version used and hardware type if relevant.
e.g.:

OPNsense 19.1.5 (amd64, OpenSSL).
APU2C4

**Comment by fichtner** [comment]
Update to 19.1.5_1, went out half an hour ago.
