### ISSUE TITLE
HA sync error/warning

### ISSUE THREAD

**Issue by kenshin33** [opnsense/core#3390]
Since update to (19.1.5 and then 19.1.5_1), notice appears whenever the configuration is synced (either manually or automatically)
it reads [An error occured while atempting XMLRPC sync with username USERNAME and https://ip.of.other.fw/xmlrpc.php parse error not well formed]

**To Reproduce**

1. Go to 'System->HA->status '
2. try to sync config 
4. See Notice apear 

**Expected behavior**
No notice and configuration sync

**Relevant log files**
running /usr/local/etc/rc.filter_synchronize
yields :

         send >>> 
         Host: 172.16.0.2
         User-Agent: XML_RPC
         Content-Type: text/xml
         Content-Length: 117
         Authorization: Basic XXXXX
         <?xml version="1.0"?>
         <methodCall>
         <methodName>opnsense.firmware_version</methodName>
         <params>
         </params></methodCall>received >>> 
         
         Warning: count(): Parameter must be an array or an object that implements Countable in /usr/local/opnsense/contrib/IXR/IXR_Library.php on line 420
         
         Warning: Cannot modify header information - headers already sent by (output started at /usr/local/opnsense/contrib/IXR/IXR_Library.php:420) in /usr/local/opnsense/contrib/IXR/IXR_Library.php on line 464
         
         Warning: Cannot modify header information - headers already sent by (output started at /usr/local/opnsense/contrib/IXR/IXR_Library.php:420) in /usr/local/opnsense/contrib/IXR/IXR_Library.php on line 465
         
         Warning: Cannot modify header information - headers already sent by (output started at /usr/local/opnsense/contrib/IXR/IXR_Library.php:420) in /usr/local/opnsense/contrib/IXR/IXR_Library.php on line 466
         
         Warning: Cannot modify header information - headers already sent by (output started at /usr/local/opnsense/contrib/IXR/IXR_Library.php:420) in /usr/local/opnsense/contrib/IXR/IXR_Library.php on line 467
         <?xml version="1.0"?>
         <methodResponse>
           <params>
             <param>
               <value>
               <struct>
           <member><name>base</name><value><struct>
           <member><name>version</name><value><string>19.1.4</string></value></member>
         </struct></value></member>
           <member><name>firmware</name><value><struct>
           <member><name>version</name><value><string>19.1.5_1</string></value></member>
         </struct></value></member>
           <member><name>kernel</name><value><struct>
           <member><name>version</name><value><string>19.1.4</string></value></member>
         </struct></value></member>
         </struct>
               </value>
             </param>
           </params>
         </methodResponse>
         error >>> 
         parse error. not well formed

**Environment**
OPNsense 19.1.15_1 (amd64, OpenSSL).

**Comment by kenshin33** [comment]
this seems to fix it !
```diff
--- /usr/local/opnsense/contrib/IXR/IXR_Library.php     2019-04-05 17:13:17.690656000 -0400
+++ ./IXR_Library.php   2019-04-05 17:41:22.909773000 -0400
@@ -417,7 +417,7 @@ EOD;
         $method = $this->callbacks[$methodname];
 
         // Perform the callback and send the response
-        if (count($args) == 1) {
+        if ((is_array($args) || $args instanceof Countable) && count($args) == 1) {
             // If only one paramater just send that instead of the whole array
             $args = $args[0];
         }
```

**Comment by AdSchellevis** [comment]
Which options are enabled under System -> High Availability -> Settings?

**Comment by kenshin33** [comment]
All except  Monit and Intrusion detection.
Plus the following plugins :

- WOL
- Zabbix
- Relayd

**Comment by AdSchellevis** [comment]
can you try to disable the plugins sync and see if it persists?

(you can't do a two way sync, since the nodes don't know when a specific entry was changed)

**Comment by kenshin33** [comment]
tested with change reverted :  the notice appears.
unticked all plugins, saved and synced again : the notice does NOT appear.
if I tick any thing and save,  the notice appears.

(that was my impression. Thanks for the confirmation)

**Comment by chrko** [comment]
This error also occurs at my test system. I think this is due upgrading php from 7.1 to 7.2:
https://www.php.net/manual/en/migration72.incompatible.php#migration72.incompatible.warn-on-non-countable-types

**Comment by chrko** [comment]
> this seems to fix it !
> 
> ```diff
> --- /usr/local/opnsense/contrib/IXR/IXR_Library.php     2019-04-05 17:13:17.690656000 -0400
> +++ ./IXR_Library.php   2019-04-05 17:41:22.909773000 -0400
> @@ -417,7 +417,7 @@ EOD;
>          $method = $this->callbacks[$methodname];
>  
>          // Perform the callback and send the response
> -        if (count($args) == 1) {
> +        if ((is_array($args) || $args instanceof Countable) && count($args) == 1) {
>              // If only one paramater just send that instead of the whole array
>              $args = $args[0];
>          }
> ```

Works perfectly ;)

**Comment by AdSchellevis** [comment]
@chrko it looks like you're right, the warning wasn't in 7.1, we have seen some other small glitches as well.

**Comment by AdSchellevis** [comment]
@kenshin33 @chrko can you test and confirm https://github.com/opnsense/core/commit/945202230726af76582103680fa4c49114670752

**Comment by kenshin33** [comment]
@AdSchellevis I did and it seemed to work (before creating the issue).
By work I mean : the notice no longer appears and the slave node picks up the changes

**Comment by LPJon** [comment]
```
--- /usr/local/opnsense/contrib/IXR/IXR_Library.php     2019-04-05 17:13:17.690656000 -0400
+++ ./IXR_Library.php   2019-04-05 17:41:22.909773000 -0400
@@ -417,7 +417,7 @@ EOD;
         $method = $this->callbacks[$methodname];
 
         // Perform the callback and send the response
-        if (count($args) == 1) {
+        if ((is_array($args) || $args instanceof Countable) && count($args) == 1) {
             // If only one paramater just send that instead of the whole array
             $args = $args[0];
         }
```
@chrko I feel a bit like a noob here but I implemented these changes with no change in result? I'm slightly confused am I supposed to remove the file "IXR_Library.php" and then recreate it with only the above mentioned code in it. Or was that simply make a backup of the original file first? On a side note the code I see does not have "EOD;" just before the "$method = " variable. The earliest that "EOD;" appears before the section mentioned above is on line 407. Would it be too much to ask to have the entire modified file posted here. I've been doing this for years but this isn't matching what I have. My OPNSense version is 19.1.5_1.
