### ISSUE TITLE
Warning in System: Access: Groups If the group has no member.

### ISSUE THREAD

**Issue by datiscum** [opnsense/core#3391]
If a system group has no members, the following is displayed:

Warning: count(): Parameter must be an array or an object that implements Countable in /usr/local/www/system_groupmanager.php on line 388 0

OPNsense 19.1.5 (amd64, OpenSSL).

**Comment by AdSchellevis** [comment]
@datiscum thanks for reporting, it's probably a regression in php7.2 migration.
