### ISSUE TITLE
Feature request: Squid - SSL-Filtering per Interface

### ISSUE THREAD

**Issue by AndyX90** [opnsense/core#3394]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[+] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[+] I have searched the existing issues and I'm convinced that mine is new.

**Is your feature request related to a problem? Please describe.**
The SSL-Filtering in Squid can only be done for the whole Machine.

**Describe the solution you'd like**
I would like to have the option to do ssl-bump on LAN for my Windows-Clients and SNI-Filter only on WiFi-Interfaces for Mobile-Devices.

**Describe alternatives you've considered**
An alternative would be to provide a possibility via GUI for multiple Squid-Instances.

**Additional context**
-

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository, 
please read https://github.com/opnsense/core/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue, 
just let us know, so we can reopen the issue and assign an owner to it.
