### ISSUE TITLE
Feature request: Webserver - Proxy Auto-Config

### ISSUE THREAD

**Issue by AndyX90** [opnsense/core#3397]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[+] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[+] I have searched the existing issues and I'm convinced that mine is new.

**Is your feature request related to a problem? Please describe.**
I would like to have different webserver ports for webinterface/management and proxy autoconfig.
For compatibility reasons it is better to serve the autoconfig via HTTP.
But I don't want to be forced to give all clients also webaccess to my firewall.
Also it is not recommendable to use HTTP for webmanagement.

**Describe the solution you'd like**
Separate the webinterface and the proxy-autoconfig via virtualhosts or use different webservers.

**Describe alternatives you've considered**
-

**Additional context**

**Comment by fabianfrz** [comment]
Users usually serve the file via the nginx plugin and the web interface via HTTPS so it should work. When you don't want to run it together with the main web server.

**Comment by AndyX90** [comment]
Yes that would be possible, i personally serve this mostly via IIS.
But in my opinion serving it externally or via plugin is uncomfortable. 
It would be nice to have the possibility in the GUI to at least change the port of the, whatever serves this file.
I thought about something like [this ](https://www.hiawatha-webserver.org/) to separate it completely.

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository, 
please read https://github.com/opnsense/core/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue, 
just let us know, so we can reopen the issue and assign an owner to it.
