### ISSUE TITLE
NAT after IPSec phase 2 isn't working with multiple networks

### ISSUE THREAD

**Issue by araujorm** [opnsense/core#3398]
**Describe the bug**
NAT after IPSec phase 2 isn't working with multiple networks.

This is a continuation of https://github.com/opnsense/core/issues/2173 since we believe it's not solved, and also believe it's not the same as https://github.com/opnsense/core/issues/1773 as we are currently having issues on an environment that uses a IPSec connection with the need for NAT and uses the IP addresses of the gateways as the identifiers.

**To Reproduce**

We have a test case where this is happening, in an environment we are trying to migrate from an old Linux machine to a new Opnsense powered device.

Specifically:
- we have 2 local networks (net1, net2) of which only one (net2) is on the encryption domain
- we have 3 remote networks, and all are on the encryption domain (we do not control the remote side and can't change this setup)
- the old VPN server was a Linux and all we had to do was do outbound NAT for net1 to SNAT as one of the IP addresses of net2
- on opnsense, we already added net1 to the "manual SPD entries" of the 3 phase 2 entries (something we didn't have to do on Linux, but here is different and we can live with that), however it sometimes work and sometimes does not
- other thing we noted of relevance: the tunnel isn't automatically established if someone tries to connect from net1 to the remote networks, but if we connect from net2 to the remote networks, it's established; after that, sometimes the connections start working from net1 to the remote networks.

**Expected behavior**
We should be able to always see the connection be established when we connect from net1 (the one that isn't on the encryption domain) to a machine on any of the 3 remote networks, even if the IPSec connection isn't established before that (we should also be able to get that behaviour every time, for the matter, which we aren't being able, as described above).

**Screenshots**
Not applicable but feel free to ask for any specific ones you might need.

**Relevant log files**
Not applicable but feel free to ask for any specific ones you might need.

**Additional context**
This problem is blocking the migration of the old Linux device, which still works without issues.

**Environment**
Software version used and hardware type if relevant.
e.g.:

OPNsense 19.1.4

**Comment by fichtner** [comment]
Closing as per https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

**Comment by mimugmail** [comment]
@araujorm this is now working out of the box starting with 21.1 RC1 .. maybe you have time to test :)

**Comment by araujorm** [comment]
> @araujorm this is now working out of the box starting with 21.1 RC1 .. maybe you have time to test :)

Thanks, but meanwhile 1.5 years have passed while the issue was simply ignored by the devs  (which simply closed the issue with the justification that... the issue was ignored). We've since stopped recommending this solution to our customers and never looked back.

**Comment by fichtner** [comment]
@araujorm thanks for ranting back, really appreciate it ❤️
