### ISSUE TITLE
OPNsense®  pfSense® comparison info

### ISSUE THREAD

**Issue by topstarnetwork** [opnsense/core#34]
Hello,
could you please tell me what is the OPNsense®  pfSense® features, functionalities comparison?
Does OPNsense®  has more features then pfSense® and why should I use opnsense instead of pfsense???

regards, Heather

**Comment by jschellevis** [comment]
Hi Heather,

We have setup a new page on our wiki, to give a more detailed explanation on why we have forked pfSense. See: https://wiki.opnsense.org/index.php/OPNsense:So_why_did_we_fork%3F

As you can see the focus of our project is not so much on more features.
Although I am sure new and exiting things will happen after 15.7 has been released.

If you have particular interest in certain features, just let us know here on github so we can consider it.
Or even better, if you would like to join our effort you are more than welcome to do so.

**Comment by topstarnetwork** [comment]
It is clear now, thanks.
