### ISSUE TITLE
NAT port forwarding rules not created correctly when using interface group

### ISSUE THREAD

**Issue by niziak** [opnsense/core#3402]
OPNsense 19.7.a_442-amd64
FreeBSD 11.2-RELEASE-p9-HBSD
OpenSSL 1.0.2r 26 Feb 2019

I have system with two WAN interfaces with separate IP addresses. WAN interfaces are grouped into one `WAN` firewall group (NOTE: `WAN` is not a real interface)

Interface assignment:
  * em0 - WAN1
  * em1 - WAN2
  * bge0 - LAN

I want to use one port forwarding rule to work on both WAN IP addressees. 
The rule I'm using is simple:
Firewall --> NAT --> Port Forward:
  * Interface:  `WAN`
  * IPv4, TCP/UDP
  * Destination: `WAN net` 
  * Destination port range: 18080 - 18090
  * Redirect target IP: `Single host or Network` `192.168.0.120`
  * Redirect target port: `18080`
Firewall --> Settings --> Advanced
  * Reflection for port forwards ENABLED
  * Automatic outbound NAT for Reflection ENABLED
  * Static route filtering (Bypass firewall rules for traffic on the same interface) ENABLED

Tests:
  * external host --> WAN1_IP:18083 TCP works as expected
  * external host --> WAN2_IP:18083 TCP - NOT WORKING
     * connection is successfully forwarded from WAN2_IP into LAN 192.168.0.120, but response from 192.168.0.120 is send using wrong WAN interface: Packet with WAN2_IP is sent using WAN1 interface.
  *  LAN host 192.168.0.90 --> WAN1_IP:18083 TCP - NOT WORKING
    * traffic from LAN IP 192.168.0.90 to WAN1_IP is redirected to 192.168.0.120, withhout changing source adddress, so 192.168.0.120 responds directly to 192.168.0.90, which is incorrect
  *  LAN host 192.168.0.90 --> WAN2_IP:18083 TCP - NOT WORKING
     * like above

When I create two rules (for each WAN interface) everything works perfectly.

I can see that some rules are missing comparing to working rule.

Not working rules created for interface group WAN
```
rdr on WAN inet proto tcp from any to (WAN:network) port 18080:18090 -> 192.168.0.120 port 18080:18090
rdr on WAN inet proto udp from any to (WAN:network) port 18080:18090 -> 192.168.0.120 port 18080:18090
rdr on bge0 inet proto tcp from any to (WAN:network) port 18080:18090 -> 192.168.0.120 port 18080:18090
rdr on bge0 inet proto udp from any to (WAN:network) port 18080:18090 -> 192.168.0.120 port 18080:18090
pass in quick on WAN inet proto tcp from any to 192.168.0.120 port 18080:18090 flags S/SA keep state label "3d902b1e4f999ab27539984627212efd"
pass in quick on WAN inet proto udp from any to 192.168.0.120 port 18080:18090 keep state label "3d902b1e4f999ab27539984627212efd"
```

Working rules created for real WAN1 interface (em0).
```
nat on em0 inet proto tcp from (em0:network) to 192.168.0.120 port 18080:18090 -> { WAN1_IPs } port 1024:65535 round-robin
nat on em0 inet proto udp from (em0:network) to 192.168.0.120 port 18080:18090 -> { WAN1_IPs } port 1024:65535 round-robin
nat on bge0 inet proto tcp from (bge0:network) to 192.168.0.120 port 18080:18090 -> 192.168.0.1 port 1024:65535
nat on bge0 inet proto udp from (bge0:network) to 192.168.0.120 port 18080:18090 -> 192.168.0.1 port 1024:65535
rdr on em0 inet proto tcp from any to (WAN:network) port 18080:18090 -> 192.168.0.120 port 18080:18090
rdr on em0 inet proto udp from any to (WAN:network) port 18080:18090 -> 192.168.0.120 port 18080:18090
rdr on bge0 inet proto tcp from any to (WAN:network) port 18080:18090 -> 192.168.0.120 port 18080:18090
rdr on bge0 inet proto udp from any to (WAN:network) port 18080:18090 -> 192.168.0.120 port 18080:18090
pass in quick on em0 reply-to (em0 WAN1_GW ) inet proto tcp from any to 192.168.0.120 port 18080:18090 flags S/SA keep state label "c3cdc999fae8f21a3234b731d3349398"
pass in quick on em0 reply-to (em0 WAN1_GW ) inet proto udp from any to 192.168.0.120 port 18080:18090 keep state label "c3cdc999fae8f21a3234b731d3349398"
```

Additional, small issue (not really issue?): 
I'm using multiwan setup, so I made a rule to route all LAN traffic to gateway group. This is in conflict with NAT reflection rules.
As workaround I've created `Firewall-->Rules-->LAN` to permit LAN to LAN traffic using default gateway. 
I think this rule should be automatically generated when `Firewall-->Settings-->Advanced:  Static route filtering (Bypass firewall rules for traffic on the same interface)` is ENABLED.

**Comment by fichtner** [comment]
To me this looks like a FreeBSD bug incorrectly resolving groups with the :network operator. It should be reported here https://bugs.freebsd.org/bugzilla/

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository, 
please read https://github.com/opnsense/core/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue, 
just let us know, so we can reopen the issue and assign an owner to it.
