### ISSUE TITLE
IPv6 ipsec tunnel use link local address in left parameter

### ISSUE THREAD

**Issue by chaispaquichui** [opnsense/core#3404]
**Describe the bug**
When configuring an ipv6 ipsec tunnel, opnsense use the link-local address of the wan interface in the left parameter of ipsec.conf

/usr/local/etc/ipsec.conf
--- SNIP ---
conn con2
  aggressive = no
  fragmentation = yes
  keyexchange = ikev2
  mobike = yes
  reauth = yes
  rekey = yes
  forceencaps = no
  installpolicy = yes
  
  dpdaction = none
  **left = fe80::f053:29c:69a4:2619**
  right = 3000::2

**To Reproduce**
1. Create an ipv6 tunnel with ipsec and select Wan as the local interface

**Expected behavior**
Opnsense should use the GUA of the wan interface instead of the link local address

**Environment**

OPNsense 19.1.5_1-amd64
FreeBSD 11.2-RELEASE-p9-HBSD
OpenSSL 1.0.2r 26 Feb 2019

**Comment by chaispaquichui** [comment]
Just in case : yes, I've a GUA on the wan interface

pppoe0: flags=88d1<UP,POINTOPOINT,RUNNING,NOARP,SIMPLEX,MULTICAST> metric 0 mtu 1492
	inet6 fe80::f053:29c:69a4:2619%pppoe0 prefixlen 64 scopeid 0xa 
	inet6 fe80::5c43:47f:56fb:f03e%pppoe0 prefixlen 64 scopeid 0xa 
	inet6 2a02:a03f:4410:19bf:f053:29c:69a4:2619 prefixlen 64 autoconf

**Comment by chaispaquichui** [comment]
I found this in the code of the function get_interface_ipv6

```
{
    global $config;
    $realif = get_real_interface($interface, 'inet6');
    if ($realif) {
        return isset($config['interfaces'][$interface]['dhcp6prefixonly']) ?
            find_interface_ipv6_ll($realif) : find_interface_ipv6($realif);
    }
    if (strstr($interface, '_vip')) {
        return get_configured_carp_interface_list($interface, 'inet6');
    }
    return null;
}
```
So if the interface is configured with dhcpv6 (which is my case), the function always return the link local address. Why is this necessary ? It brokes ipsec in my case...

**Comment by chaispaquichui** [comment]
It also breaks the firewall rules related to the wan interface. For example, I just created a rule to allow openvpn over ipv6 on the wan interface 

![image](https://user-images.githubusercontent.com/38246962/56076475-f450e100-5dd1-11e9-9477-4dd7d50dec35.png)

This is the result in packet filter : 

pass in log quick on pppoe0 reply-to (pppoe0 **fe80::d2f0:dbff:fe85:2000**) inet6 proto udp from any to (pppoe0) port = openvpn keep state label "USER_RULE: Openvpn ipv6"

**Comment by fichtner** [comment]
If you set dhcp6prefixonly then we will ignore anything non-link local. If your ISP gives you a non-link-local but requires you to request a prefix only that is how it must be by the virtue of their rules. Instead, try to move phase 1 to LAN instead of WAN, it works just the same.

**Comment by chaispaquichui** [comment]
So if I understand correctly, you automatically ignore the GUA because there is some scenario where the ISP doesn't "give" a GUA on the wan interface ?

I know I can use the LAN interface but it's not intuitive, would it be possible to document this behavior ?

**Comment by fichtner** [comment]
The question is do you need to use request prefix only option? If IPv6 works without this non-standard option you're fine as is. If not you need to bind IPsec or any other service to an IPv6 interface with a global address as knowingly accepted by the system.

The problem with documenting this IPv6 oddity is that the people looking for the problem are very unlikely to find the appropriate spot in the documentation which is amount to a footnote to IPv6 interface configuration. Link-local on WAN is perfectly fine in IPv6 and sometimes even required when you only get a link-local gateway.

Removing the settings lock on link-local address may break router connectivity or monitoring thereof so this is particular reported issue here is the lesser of the two.

**Comment by chaispaquichui** [comment]
Sorry, I forgot that I've selected this option on the wan interface... Everything make more sense now :)

Thx and sorry for the waste of time !

**Comment by fichtner** [comment]
If it works this way I'm happy. No worries. :)
