### ISSUE TITLE
IPV6: Track Interface: Doesn't allow full use of all prefix bits

### ISSUE THREAD

**Issue by lrosenman** [opnsense/core#3405]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[x] I have searched the existing issues and I'm convinced that mine is new.

**Describe the bug**
Having an existing interface setup
Request /60 from provider
 Add another interface.
Set TRACK INTERFACE to WAN
set prefix id to 15 (b'1111')
get error message about prefix id out of range
(also /var/etc/dhcp6c_<wan>.conf *DOES NOT* get rewritten
**To Reproduce**
Having an existing interface setup
Request /60 from provider
 Add another interface.
Set TRACK INTERFACE to WAN
set prefix id to 15 (b'1111')
get error message about prefix id out of range
(also /var/etc/dhcp6c_<wan>.conf *DOES NOT* get rewritten

**Expected behavior**
for a /60 ability to use prefix id's 0 (b'0000') to 15 (b'1111').
and re-write dhcp6c_<tracked interface>.conf and restart dhcp6c
on *ANY* change to IPv6 parameters on the tracking interfaces.

**Screenshots**

**Relevant log files**
If applicable, information from log files supporting your claim.

**Additional context**

**Environment**
Software version used and hardware type if relevant.
e.g.:

OPNsense 19.1.6 (amd64, OpenSSL).
Intel® i3-7100U Quadcore
Network Intel® 82583V x 6

**Comment by maurice-w** [comment]
The prefix ID is hexadecimal - entering '15' equals 10101b. Valid prefix IDs for a /60 delegated prefix are '0' to 'F', so the 'out of range' error message is correct.

**Comment by lrosenman** [comment]
That should be explained in the help, and given as additional information in the error message.
