### ISSUE TITLE
dhcp6c: Config not rewritten when interfaces added after the first.

### ISSUE THREAD

**Issue by lrosenman** [opnsense/core#3406]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[x] I have searched the existing issues and I'm convinced that mine is new.

**Describe the bug**
Can't add 2nd-nth tracking interface
**To Reproduce**
Have an existing WAN connection with PD
Have an existing LAN connection tracking WAN (prefix id 0)
add another interface (of any flavor)
set to IPv6 Track Wan / Prefix id 1
set it to allow modifying DHCPD/RA

**Expected behavior**
prefix-interface stanza added to /var/etc/dhcp6c_<wan>.conf
restart dhcp6c
**Screenshots**

**Relevant log files**
If applicable, information from log files supporting your claim.

**Additional context**

**Environment**
Software version used and hardware type if relevant.
e.g.:

OPNsense 19.1.6 (amd64, OpenSSL).
Intel® i3-7100U Quad Core
Network Intel® 82583V

**Comment by lrosenman** [comment]
Anyone?

**Comment by fichtner** [comment]
Nice spot, can you try this patch?

    # opnsense-patch 88c5ffa


Cheers,
Franco

**Comment by fichtner** [comment]
Deconfigure now works as expected too. There's still an older bug that I'd like to address before closing: checking wether the same prefix ID is already used.

**Comment by fichtner** [comment]
@lrosenman Thanks for the report and sorry for the delay ❤️

**Comment by lrosenman** [comment]
How can I get all the commits on a 19.1.x release/box/etc?

**Comment by fichtner** [comment]
@lrosenman let's discuss here about schedule. I can't promise it for 19.1.7 but I can make a single-patch backport for on top of 19.1.6 if you want to test?

**Comment by lrosenman** [comment]
I'd love that and *WILL* test :)

**Comment by fichtner** [comment]
Okay, great! It's 81ca8c9 for both tickets. Apply and subsequently remove by running the same command below:

    # opnsense-patch 81ca8c9

**Comment by fichtner** [comment]
PS: I don't always have time to respond quickly, but GitHub is indeed the best and quickest way do discuss issues, patches, solutions and release schedules. Closing tickets is just for recording issues as done in the roadmap item "19.7". Ping still works reliably afterwards :)

**Comment by lrosenman** [comment]
Deleting the interface should cause a rewrite as well, and does *NOT* at the moment with the above patch.

**Comment by lrosenman** [comment]
the rest looks great!

**Comment by fichtner** [comment]
@lrosenman nice, thanks a lot. I have an idea about deletion. Will patch tomorrow and follow-up.

**Comment by fichtner** [comment]
7ff838cac on top should do the trick:

    # opnsense-patch 7ff838cac

I think I can shortcut these to 19.1.7 with the help of your testing. I just have to make sure my office setup likes this as well. Due to the Easter holidays couldn't deploy it there yet but will do it on Thursday.

**Comment by lrosenman** [comment]
Confirmed it now does the right thing here.  Thanks!

**Comment by fichtner** [comment]
@lrosenman great, thanks for your help!
