### ISSUE TITLE
Update Alias from https source always complains about not using certificate verification

### ISSUE THREAD

**Issue by kevemueller** [opnsense/core#3413]
[x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[x] I have searched the existing issues and I'm convinced that mine is new.

**Describe the bug**
Aliases can be populated from URLs.
When defining a https URL the underlying update_tables.py code always emits an error message on stderr.
`/usr/local/lib/python2.7/site-packages/urllib3/connectionpool.py:858: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)`
As this code is run in cron context, cron tries to send the error message by mail, which fails and results in a log entry with the error message.
The error message is produced regardless of the setting of `Firewall/Settings/Advanced/Check certificate of aliases URLs`.

**To Reproduce**
1. Define an URLTable Alias, e.g. https://www.spamhaus.org/drop/edrop.txt
2. Wait until cron triggers the update.
3. Check log
4. Invalidate the downloaded table
5. Trigger a manual download by issuing the command `/usr/local/bin/flock -n -E 0 -o /tmp/filter_update_tables.lock /usr/local/opnsense/scripts/filter/update_tables.py > /dev/null`
6. The error message is displayed on the console.

**Expected behavior**
`Firewall/Settings/Advanced/Check certificate of aliases URLs`, 
* if disabled means that the user knows the risk. The warning should not be issued, or swallowed with 2>/dev/null.
* if enabled, the request should validate the certificate, there should be no warning in the first place.

Not emitting anything on stderr automatically gets rid of the cron / mail / logging issue.

**Relevant log files**
```
Apr 13 17:39:00 X update_tables.py: fetch alias url https://www.spamhaus.org/drop/edrop.txt (lines: 124)
Apr 13 17:39:02 X cron[49413]: (root) MAIL (mailed 292 bytes of output but got status 0x0001 )
```

**Environment**
OPNsense 19.1.5_1 (amd64/OpenSSL)

**Comment by AdSchellevis** [comment]
yes, while doing the python 2 ->3 conversion, I noticed the same, should already be fixed in master https://github.com/opnsense/core/blob/master/src/opnsense/scripts/filter/update_tables.py#L42
