### ISSUE TITLE
IPv6: Daily service disruption on prefix change

### ISSUE THREAD

**Issue by klada** [opnsense/core#3415]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[x] I have searched the existing issues and I'm convinced that mine is new.

**Describe the bug**

When OPNsense is set up with a dynamic ISP prefix (including prefix delegation and prefix tracking on interfaces), the interfaces go down for a few seconds every day when the prefix changes. This (obviously) **interrupts all network connections**.

However the PPPoE connection in my case remains online (no daily reconnects). It's just that my ISP announces a new IPv6 prefix every 22 hours (which remains valid for 24 hours). The IPv4 address remains the same.

**To Reproduce**

1. Enable IPv6 with DHCP-over-IPv4 on PPPoE connection
2. Set up prefix tracking for interfaces
3. A new IPv6 address will eventually be picked up by the interfaces
4. Wait until the IPv6 prefix is due for renewal (22 hours in my case)
5. As soon as a new prefix is announced the interfaces go down for a second and are brought up again with a new IPv6 address from the new prefix. **The old address is lost**.

This causes service disruption for the clients (both IPv4 and IPv6) and all clients need to reconfigure their IPv6 addresses immediately.

**Expected behavior**

There are actually two issues here:

1. The interfaces should not be brought down at all. It's a simple address change (more precisely an additional IPv6 address). IPv4 connectivity is not affected and hence should not be touched at all.
2. The old addresses should not be removed from the interfaces (they should only be marked as "deprecated"). The new interface address from the new prefix should be set as an additional IPv6 address with the "preferred" flag. The new prefix should be announced.

This way clients which still have an address from the old prefix will keep their connectivity. As soon as a client picks up a Router Advertisement with the new prefix it can deprecate it's old IPv6 addresses.

**Relevant log files**

/var/log/system.log

```
Apr 14 10:05:40 gate dhcp6c[30391]: Sending Renew
Apr 14 10:05:40 gate dhcp6c[30391]: Received REPLY for RENEW
Apr 14 10:12:19 gate kernel: igb1: link state changed to DOWN
Apr 14 10:12:19 gate kernel: igb1_vlan50: link state changed to DOWN
Apr 14 10:12:19 gate kernel: igb1_vlan100: link state changed to DOWN
Apr 14 10:12:19 gate kernel: igb1_vlan200: link state changed to DOWN
Apr 14 10:12:19 gate kernel: igb1_vlan30: link state changed to DOWN
Apr 14 10:12:19 gate opnsense: /usr/local/etc/rc.linkup: DEVD Ethernet detached event for lan
Apr 14 10:12:20 gate opnsense: /usr/local/etc/rc.linkup: Hotplug event detected for MMT(opt3) but ignoring since interface is configured with static IP (192.168.50.254 ::)
Apr 14 10:12:21 gate opnsense: /usr/local/etc/rc.linkup: DEVD Ethernet detached event for opt2
Apr 14 10:12:21 gate opnsense: /usr/local/etc/rc.linkup: Hotplug event detected for SRV(opt1) but ignoring since interface is configured with static IP (192.168.200.254 ::)
Apr 14 10:12:22 gate kernel: igb1: link state changed to UP
Apr 14 10:12:22 gate kernel: igb1_vlan50: link state changed to UP
Apr 14 10:12:22 gate kernel: igb1_vlan100: link state changed to UP
Apr 14 10:12:22 gate kernel: igb1_vlan200: link state changed to UP
Apr 14 10:12:22 gate kernel: igb1_vlan30: link state changed to UP
Apr 14 10:12:23 gate opnsense: /usr/local/etc/rc.linkup: Hotplug event detected for OG(opt4) but ignoring since interface is configured with static IP (192.168.30.254 ::)
Apr 14 10:12:23 gate opnsense: /usr/local/etc/rc.linkup: DEVD Ethernet attached event for lan
Apr 14 10:12:23 gate opnsense: /usr/local/etc/rc.linkup: HOTPLUG: Configuring interface lan
Apr 14 10:12:24 gate dhcp6c[30391]: restarting
Apr 14 10:12:24 gate dhcp6c[30391]: Bypassing address release because of -n flag
Apr 14 10:12:24 gate dhcp6c[30391]: failed to remove an address on igb1_vlan100: Can't assign requested address
Apr 14 10:12:24 gate dhcp6c[30391]: failed to remove an address on igb1: Can't assign requested address
Apr 14 10:12:24 gate dhcp6c[30391]: Sending Solicit
Apr 14 10:12:24 gate opnsense: /usr/local/etc/rc.linkup: ROUTING: entering configure using 'lan'
Apr 14 10:12:24 gate opnsense: /usr/local/etc/rc.linkup: ROUTING: IPv4 default gateway set to wan
Apr 14 10:12:24 gate opnsense: /usr/local/etc/rc.linkup: ROUTING: no IPv6 default gateway set, assuming wan
Apr 14 10:12:24 gate opnsense: /usr/local/etc/rc.linkup: ROUTING: skipping IPv4 default route
Apr 14 10:12:24 gate opnsense: /usr/local/etc/rc.linkup: ROUTING: skipping IPv6 default route
Apr 14 10:12:25 gate dhcp6c[30391]: Sending Request
Apr 14 10:12:25 gate dhcp6c[30391]: Received REPLY for REQUEST
Apr 14 10:12:25 gate dhcp6c[30391]: add an address 2003:f4:xxxx:5364:2099:d2ff:fe7b:xxxx/64 on igb1_vlan100
Apr 14 10:12:25 gate dhcp6c[30391]: add an address 2003:f4:xxxx:5314:2099:d2ff:fe7b:xxxx/64 on igb1
Apr 14 10:12:25 gate dhcp6c: dhcp6c REQUEST on pppoe0 - running newipv6
Apr 14 10:12:25 gate opnsense: /usr/local/etc/rc.newwanipv6: IP renewal is starting on 'pppoe0'
Apr 14 10:12:25 gate opnsense: /usr/local/etc/rc.newwanipv6: On (IP address: fe80::20d:b9ff:fe4a:xxxx) (interface: WAN[wan]) (real interface: pppoe0).
Apr 14 10:12:29 gate opnsense: /usr/local/etc/rc.linkup: Warning! services_dhcpdv4_configure() found no suitable IPv4 address on opt2
Apr 14 10:12:31 gate opnsense: /usr/local/etc/rc.linkup: Hotplug event detected for MMT(opt3) but ignoring since interface is configured with static IP (192.168.50.254 ::)
Apr 14 10:12:31 gate opnsense: /usr/local/etc/rc.newwanip: IP renewal is starting on 'igb1_vlan50'
Apr 14 10:12:31 gate opnsense: /usr/local/etc/rc.newwanip: On (IP address: 192.168.50.254) (interface: MMT[opt3]) (real interface: igb1_vlan50).
Apr 14 10:12:32 gate opnsense: /usr/local/etc/rc.linkup: DEVD Ethernet attached event for opt2
Apr 14 10:12:32 gate opnsense: /usr/local/etc/rc.linkup: HOTPLUG: Configuring interface opt2
Apr 14 10:12:32 gate dhcp6c[30391]: restarting
Apr 14 10:12:32 gate dhcp6c[30391]: Bypassing address release because of -n flag
Apr 14 10:12:32 gate dhcp6c[30391]: failed to remove an address on igb1_vlan100: Can't assign requested address
Apr 14 10:12:32 gate dhcp6c[30391]: remove an address 2003:f4:xxxx:5314:2099:d2ff:fe7b:xxxx/64 on igb1
Apr 14 10:12:33 gate opnsense: /usr/local/etc/rc.linkup: ROUTING: entering configure using 'opt2'
Apr 14 10:12:33 gate opnsense: /usr/local/etc/rc.linkup: ROUTING: IPv4 default gateway set to wan
Apr 14 10:12:33 gate opnsense: /usr/local/etc/rc.linkup: ROUTING: no IPv6 default gateway set, assuming wan
Apr 14 10:12:33 gate opnsense: /usr/local/etc/rc.linkup: ROUTING: skipping IPv4 default route
Apr 14 10:12:33 gate opnsense: /usr/local/etc/rc.linkup: ROUTING: skipping IPv6 default route
Apr 14 10:12:33 gate dhcp6c[30391]: Sending Solicit
Apr 14 10:12:34 gate dhcp6c[30391]: Sending Request
Apr 14 10:12:34 gate dhcp6c[30391]: Received REPLY for REQUEST
Apr 14 10:12:34 gate dhcp6c[30391]: add an address 2003:f4:xxxx:5364:2099:d2ff:fe7b:xxxx/64 on igb1_vlan100
Apr 14 10:12:34 gate dhcp6c[30391]: add an address 2003:f4:xxxx:5314:2099:d2ff:fe7b:xxxx/64 on igb1
Apr 14 10:12:34 gate dhcp6c: dhcp6c REQUEST on pppoe0 - running newipv6
Apr 14 10:12:35 gate opnsense: /usr/local/etc/rc.newwanipv6: IP renewal is starting on 'pppoe0'
Apr 14 10:12:35 gate opnsense: /usr/local/etc/rc.newwanipv6: On (IP address: fe80::20d:b9ff:fe4a:xxxx) (interface: WAN[wan]) (real interface: pppoe0).
Apr 14 10:12:41 gate opnsense: /usr/local/etc/rc.linkup: Hotplug event detected for SRV(opt1) but ignoring since interface is configured with static IP (192.168.200.254 ::)
Apr 14 10:12:41 gate opnsense: /usr/local/etc/rc.newwanip: IP renewal is starting on 'igb1_vlan200'
Apr 14 10:12:41 gate opnsense: /usr/local/etc/rc.newwanip: On (IP address: 192.168.200.254) (interface: SRV[opt1]) (real interface: igb1_vlan200).
Apr 14 10:12:43 gate opnsense: /usr/local/etc/rc.linkup: Hotplug event detected for OG(opt4) but ignoring since interface is configured with static IP (192.168.30.254 ::)
Apr 14 10:12:43 gate opnsense: /usr/local/etc/rc.newwanip: IP renewal is starting on 'igb1_vlan30'
Apr 14 10:12:43 gate opnsense: /usr/local/etc/rc.newwanip: On (IP address: 192.168.30.254) (interface: OG[opt4]) (real interface: igb1_vlan30).
```

PPPoE Setup:

![ipv6](https://user-images.githubusercontent.com/3250940/56093412-c0a4b280-5ec8-11e9-8b3e-18d0d852b288.jpg)

**Additional context**

See RFC4862 and RFC3315 for details about `preferred-lifetime` and `valid-lifetime`.

**Environment**
Software version used and hardware type if relevant.
e.g.:

OPNsense 19.1.6-amd64
APU2C4

**Comment by aofwer** [comment]
I can confirm this issue. I am getting a short interface UP/DOWN toggle roughly every 48 hours. This only happens when IPv6 with prefix tracking is enabled. With IPv6 disabled I am not getting these disconnects.

Observations:

- PPPoE connection/interface does not toggle. There is no forced PPPoE disconnect from my ISP
- IPv4 and IPv6 address/prefix **does not change**

I _think_ the reason for the interface toggling is that my my ISP assigns me a new **temporary** IPv6 address and prefix every 2 days. OPNsense does not really care about these temporary addresses, as it only uses the permanent IPv6 prefix anyway. I also don't see why the local interfaces should be brought up/down at all.

Is there any way we can help debugging this further? How can I see the actual reason for the interface toggling? Right now I can only see a dhcp6c log entry, followed by the interface DOWN message.

**Comment by marjohn56** [comment]
When dhcp6c receives a renew then nothing should happen. The script it calls is /var/etc/dhcp6c_*_script.sh. It should look like this:

`#!/bin/sh
if [ -n 'debug' ]; then
	/usr/bin/logger -t dhcp6c "dhcp6c $REASON on igb0"
fi
case $REASON in
REQUEST|RELEASE)
	/usr/bin/logger -t dhcp6c "dhcp6c $REASON on igb0 - running newipv6"
	/usr/local/opnsense/service/configd_ctl.py interface newipv6 igb0
	;;
*)
	;;
esac
`
The only time the script does anything is on REQUEST or RELEASE. We see it gets a REPLY message which means no change, do nothing. Something else is causing the interface to drop and that causes dhcp6c to restart and send a REQUEST message. Not seeing anything like that on my system - my logs show this:

`
Apr 25 07:27:11 | dhcp6c: dhcp6c RENEW on igb0
-- | --
Apr 25 07:27:11 | dhcp6c[76594]: T1(2250) and/or T2(3600) is locally determined
Apr 25 07:27:11 | dhcp6c[76594]: Received REPLY for RENEW
Apr 25 07:27:11 | dhcp6c: dhcp6c RENEW on igb0
`

**Comment by fichtner** [comment]
@klada I am guessing this is radvd advertising the routes as being removed due to WAN changing its prefix. I'm not sure if we can keep the old and the new address on the WAN. To me shifting the prefix is always a bad way to mess with customers and there's no real difference if the ISP gives you a chance to use the new prefix while the old one is still going ok. It essentially means you have to know how long their lifetime is so it can be configured properly. And besides, that is almost equal to IPv4 connection reset, where you are going to be disrupted anyway.

FWIW, I've marked this as "feature" to discuss options because I'm not sure there is any particular bug here. It's more of a requirement that "it should not" but the "how" currently eludes me.

@aofwer can you try 8279f2828, i.e.

    # opnsense-patch 8279f2828


Cheers,
Franco

**Comment by klada** [comment]
@fichtner I did some observations and it turns out that I am not getting a new prefix every 24 hours any more (I am on 19.1.7 by now). I don't know if my ISP has changed something regarding the prefix or if something IPv6-related has changed in OPNsense. The bad news is that the interface toggling every ~24 hours is still there. 

Is there any way to debug the prefix announcements from the ISP? I have already enabled DHCP client debugging for my WAN connection (PPPoE), but I don't see any relevant information in the log.

**Comment by aofwer** [comment]
I've upgraded from 19.1.5 to 19.1.8 and I have not had a single interface toggle for over 4 days now. I did not test the suggested patch yet, as I wanted to see if the upgrade fixes things. So far it's looking good at my side.

**Comment by klada** [comment]
I have switched my hardware (from APU2C2 to APU4C4) and also started with a fresh config on 19.1.8 and the issue is gone. So I am closing this, as it's working for me now.

**Comment by mr44er** [comment]
I stumbled across this behaviour during multiwan-test and can confirm this.

LAN-Interface configured with WAN-Tracking loses its IP on reconnect. Simply opening the problematic LAN-IF, save and reload with nothing changed is my workaround so far.

I have PPPoE too in Germany, so 24h disconnect from ISP is same like the OP, but I have a **static prefix**, so dynamic prefix shouldn't be the problem here.
