### ISSUE TITLE
Nextcloud Backup doesn't work

### ISSUE THREAD

**Issue by enoch85** [opnsense/core#3417]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

**Describe the bug**
I have had opnsense backups through nextcloud working just fine for several months. Now I changed the server (put up a new one with all the latest dependencies and so on) running Nextcloud 15.0.7

No matter what I try it always fails.

In my previous setup I had the local IP 192.168.4.111 configured without any errors. Trying to do the same thing on this new server ends up with this error message:

```
The following input errors were detected:

    The url must be valid without a trailing slash. For example: https://nextcloud.example.com or https://example.com/nextcloud
```

I've tried adding both http:// and https:// and the same with /nextcloud in the end (not valid in my case but just for testing). I've also tried to add the full DNS domain name, it still doesn't work.

Either I'm doing it wrong (following the instructions) or the app needs an update.

**To Reproduce**
1.Follow the instructions here: https://wiki.opnsense.org/manual/how-tos/cloud_backup.html
2. Try all possible URLs
3. Read a lot of forum posts
4. It wont' work

**Expected behavior**
Nextcloud backups should work

**Relevant log files**
https://cloud.hanssonit.se/s/x7aoMWTipcbej32

**Environment**
Nextcloud 15.0.7
OPNsense 19.1.6-amd64
FreeBSD 11.2-RELEASE-p9-HBSD
OpenSSL 1.0.2r 26 Feb 2019

**Comment by fabianfrz** [comment]
Your IP address works out of the box:

![Bildschirmfoto vom 2019-04-15 um 19 01 13](https://user-images.githubusercontent.com/3713914/56151164-f329da80-5fb0-11e9-92ea-add3f19070fb.png)

The backup just fails in my setup as this is not my instance. I use a FQDN with https:// prefix.

**Comment by enoch85** [comment]
Well, it doesn't work since the backup fails. :) And what do you mean by "my" IP address?

Are you running Apache? Did you do any extra configuration, like adding entries in the `/etc/hosts` file?

It worked without the https.// http:// prefix before, what changed? I read in the forums that the app was pretty hardcoded...

**Comment by fabianfrz** [comment]
It works when I enter my own server name. With your IP I refer the IP you have given me in your error description where you mention that the validation fails.

## Are you running Apache?

no, nginx/1.14.2

## Did you do any extra configuration, like adding entries in the /etc/hosts file?

Yes but only HTTP-01 handling for let's encrypt

## It worked without the https.// http:// prefix before, what changed? I read in the forums that the app was pretty hardcoded...

It still is - it just forces the following regex: /^https?:\/\/.*[^\/]$/ (https://github.com/opnsense/core/blob/master/src/opnsense/mvc/app/models/OPNsense/Backup/NextcloudSettings.xml#L12)

This means it MUST start with http:// or https:// and then it must end with at least one character which is not a slash (the characters in between can be whatever they are).

**Comment by enoch85** [comment]
So I've tried with:

http://mynextcloud.example.com/nextcloud
https://mynextcloud.example.com
https://192.168.15.111
https://192.168.15.111

Same thing for three different servers, all end up with the same error. "Backup could not be performed" as in the logs.

So what are you saying is wrong here? Thanks so far.

**Comment by fabianfrz** [comment]
What does the log say? at least there is no field validation error anymore. Do you have nextcloud in the root directory?

**Comment by enoch85** [comment]
You have the log in the issue. :)

**Comment by enoch85** [comment]
>  Do you have nextcloud in the root directory?

I've created a seperate user on Nextcloud with the sole purpose of doing these backups, and the files are stored in /OPNsense-Backup

**Comment by fabianfrz** [comment]
yes but if you switch to the system log, you should get an error message with a JSON result why it failed.

**Comment by enoch85** [comment]
Do you mean this: https://cloud.hanssonit.se/s/x7aoMWTipcbej32

![Screenshot from 2019-04-21 14:33:33](https://user-images.githubusercontent.com/4511254/56470102-7b413180-6442-11e9-9c9f-42eb1a1c79b3.png)

**Comment by fabianfrz** [comment]
```
"http_code":503
```
this means that the connection between your load balancer and your webserver is broken.

the other stuff looks like a generic HTTPS error (establishing an HTTPS connection fails ` "ssl_verify_result":1`)

**Comment by enoch85** [comment]
**Conclusion:**

It worked before on another server, the app updated, now it doesn't work with the exact same settings.

Proxy settings are *exactly* the same. The cert is also valid. As you notice I was trying on a local IP which has a self-sigend cert = not valid, whilst the FQDN are valid.

Everything is quite easy to test.

So what changed in the app that broke the setup? Before the change of needing (https:// | http://) it was working, now it doesn't since it's needed in the updated app.

Thanks for your help so far.

**Comment by enoch85** [comment]
OK, sorry, I think it is a server error after all. 

Found this when looking though all my logs:

```
[Sun Apr 21 17:48:43.517321 2019] [proxy_fcgi:error] [pid 15047:tid 139834429515520] [client 192.168.10.1:12061] AH01079: failed to make connection to backend: httpd-UDS
```

**Comment by enoch85** [comment]
...but only when trying over HTTP though. No error on HTTPS, both with FQDN and local IP.

Worth noticing is that 443 is the only Virtual Host configured on the backend.

**Comment by enoch85** [comment]
So my educated guess:

USING FQDN = Should work but doesn't
Using local IP = Complains about unvalid cert

So, FDQDN should work, but doesn't

**Comment by fabianfrz** [comment]
When I look at this page, your process may run out of memory (same error code):
https://support.plesk.com/hc/en-us/articles/213411429-Website-shows-503-Service-Unavailable-Unable-to-allocate-bytes-in-shared-memory

Can you check your systemd journal (your PHP unit is probably called php-fpm)

**Comment by enoch85** [comment]
OK, my bad. Sorry.

Enabled a HTTP config (only 443 was enaled before) and now it works.

For others coming here, this only allows OPNsense, no one else to access on port 80:

```
<VirtualHost *:80>
    Header always set Strict-Transport-Security "max-age=63072000; includeSubDomains; preload"

### SETTINGS ###
    <FilesMatch "\.php$">
        SetHandler "proxy:unix:/run/php/php7.2-fpm.nextcloud.sock|fcgi://localhost"
    </FilesMatch>

    DocumentRoot /var/www/nextcloud

    <Directory /var/www/nextcloud>
    Options Indexes FollowSymLinks
    AllowOverride All
    # Only allow connections from OPNsense:
    Require all denied
    Require ip 192.168.10.1/32
    </Directory>

    <IfModule mod_dav.c>
    Dav off
    </IfModule>

    <Directory "/var/ncdata">
    # just in case if .htaccess gets disabled
    Require all denied
    </Directory>

    SetEnv HOME /var/www/nextcloud
    SetEnv HTTP_HOME /var/www/nextcloud

</VirtualHost>
```
