### ISSUE TITLE
Dynamic DNS after DSL reconnect

### ISSUE THREAD

**Issue by monreal** [opnsense/core#3422]
**Describe the bug**
I connect to the internet using a DSL modem connected to my OPNsense via PPPoE. Sadly, my line is not very stable so at times I get multiple reconnects a day. The connection works fine again after 1-2 minutes but what does not work is my dynamic DNS. The problem seems to be that it tries to update the record while the connection is still not fully working.

**To Reproduce**
1. set up Dyn DNS
2. make modem lose the connection
3. wait for OPNsense to reconnect
4. check DNS record => still old IP
5. check log => "Could not resolve host"

**Expected behavior**
The DNS record should be updated as soon as the internet connection is working again.

**Relevant log files**
Apr 14 08:30:10 	opnsense: /usr/local/etc/rc.newwanip: Curl error occurred: Could not resolve host: dyndns.xxxxxxxx.xxx
Apr 14 08:30:10 	opnsense: /usr/local/etc/rc.newwanipv6: On (IP address: fe80::xxxxxxx) (interface: WAN[wan]) (real interface: pppoe0).
Apr 14 08:30:10 	opnsense: /usr/local/etc/rc.newwanipv6: IP renewal is starting on 'pppoe0'

**Environment**
OPNsense 19.1.5 (amd64, OpenSSL)

**Comment by fichtner** [comment]
Not sure what to do here. Are you using Unbound/Dnsmasq on the firewall or global DNS settings (System: Settings: General) or both... State of "Do not use the local DNS service as a nameserver for this system" setting is also important. 

If you use Unbound and the system is allowed to use it too it should cache the result so you won't have these problems hopefully. Worst case here the option "Serve expired responses" should be used.

**Comment by monreal** [comment]
Thanks for those ideas!
In fact I use unbounded and the system was using it. "Serve expired responses" is off. I will now try with "Do not use the local DNS service as a nameserver for this system" set to "off".

**Comment by fichtner** [comment]
Closing as per https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
