### ISSUE TITLE
locked myself out by changing auth server

### ISSUE THREAD

**Issue by claasgo** [opnsense/core#3426]
**Is your feature request related to a problem? Please describe.**
I was playing around with LDAP + OTP to test several things.
To Import my LDAP Users, I changed 
System: Settings: Administration -> Authentication -> Servers to my LDAP Servers but did NOT check local database.

Next day, after my session was interruppted, I was'nt able to login with my local Admin Accounts. Had to restore a backup wich causes downtimes.

**Describe the solution you'd like**

minimum the default root Admin should has access to the console everytime, maybe to the webui too!

**Comment by fichtner** [comment]
I'm afraid the system is unforgiving when disabling local authentication. It's a multi-select nowadays so unchecking is a very conscious decision. Warning dialogs probably don't matter either. The best way is to update the docs mentioning this can happen and having a plan B for recovery (ssh with auth key or unlocked console).

**Comment by claasgo** [comment]
Thank you, did not thought about the ssh-key way, that worked for me on my failover system.

**Comment by fichtner** [comment]
Sure, no problem. Close issue? :)
