### ISSUE TITLE
firmware: update info not cached

### ISSUE THREAD

**Issue by mschilt** [opnsense/core#343]
Usually I click the 'check for updates' button in the dashboard, see that there is something new available. 
If there is an update available I have to navigate to 'System / Firmware' and click 'fetch updates' again to fetch the information about updates a second time before I can install it.
Its not a big issue but doing this 'see if there is something new' twice all the time feels a bit weird.

Couldn't that information be cached somewhere (with a short timeframe) so that the process would be faster and more straight forward? Or I am just doing this the wrong way around :-) ?

**Comment by fichtner** [comment]
It could be stored in the user session. Discussed this briefly, but as you said it is a minor issue. We tried to cache it on the file system previously, but that was prone to race or go stale/invalid.

**Comment by mschilt** [comment]
btw.. fetching updates from CLI is an order of magnitude faster than fetching them in the GUI..
