### ISSUE TITLE
Log Files: Backend: "Configd.py [...] Performing remote backup" does not apply

### ISSUE THREAD

**Issue by alexara** [opnsense/core#3430]
[x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[x] I have searched the existing issues and I'm convinced that mine is new.

**Describe the bug**
Studying the backend log file I found that every night at 1 am `configd.py` reports ` Performing remote backup` although no remote backups have been configured or enabled at all under `System -> Configuration -> BackUp`.

[According to the docs](https://wiki.opnsense.org/manual/how-tos/cloud_backup.html#remote-backup), the remote backup actually refers only to Google Drive and Nextcloud. 
However, those are not enabled at my setup.

That's why I think this log line is kind of a bug.

**Environment**
OPNsense 19.1.6 (amd64, [OpenSSL).](url)

Happy Eastern!

**Comment by AdSchellevis** [comment]
@alexara thanks, happy easter to you too. With https://github.com/opnsense/core/commit/2e896d47b3dd66b3ef0a019102d04b2f1635822c it should disable to cron when there's no backup configured.
