### ISSUE TITLE
sdhci_acpi/mmc broken on v19.1

### ISSUE THREAD

**Issue by heri16** [opnsense/core#3433]
**Important notices**

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

- [x] I have searched the existing issues and I'm convinced that mine is new.

**Describe the bug**

The internal eMMC of my Upboard could be detected by both FreeBSD 11.2 and OPNsense v18 . On v19.1, it fails with a "Error reading EXT_CSD Bad CRC". I thought the board was bad and so went back to reinstall FreeBSD 11.2 and the problem was not there.

**Expected behavior**
OPNsense should distribute a version of HardernedBSD 11.2 that supports all the eMMC modules that FreeBSD 11.2 supports.

**Relevant log files**
If applicable, information from log files supporting your claim.

**Environment**

OPNsense 19.1.4 (amd64, OpenSSL).
Intel Atom® x5-Z8350 Processor (2M Cache, 1.44 GHz up to 1.92 GHz) CPU with 64-bit architecture; Quad Core
Network Realtek RTL8111G (LDO)

https://www.intel.com/content/www/us/en/support/articles/000022699/emerging-technologies/intel-realsense-technology.html

**Comment by fichtner** [comment]
You can read more about it here: https://forum.opnsense.org/index.php?topic=12378.0

Legacy support is broken in FreeBSD 11.2 which we would like to not break for every consumer. FreeBSD 11.3 at the moment has patches that neither some eMMC nor legacy boot are working despite the ticket...

https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=231713

At the moment we will have to sit this out.

**Comment by heri16** [comment]
No plans for another ticket on FreeBSD upstream?

**Comment by fichtner** [comment]
I'm watching the issue posted, but I don't have the means to test and report. Someone with the error will have to do it.


Cheers,
Franco

**Comment by fichtner** [comment]
We will start from scratch with HardenedBSD 12.1 in OPNsense 20.1 and there won't be anything we can do for 19.7 anymore so I'm closing this ticket.

**Comment by heri16** [comment]
@fichtner any updates on this?
