### ISSUE TITLE
Live view does not work anymore

### ISSUE THREAD

**Issue by berlinbikerx** [opnsense/core#3434]
The log file live view of the firewall rules does not work anymore. The GUI appears, but no log entries are displayed.

The page in question is
https://opnsense/ui/diagnostics/firewall/log

After requesting the live view, the following entries are logged in the backend logs of https://opnsense/configd_logs.php:

`
configd.py: [09116932-80fc-4c0c-a8c3-04b1913f6ebe] Script action failed with Command '/usr/local/opnsense/scripts/filter/read_log.py /limit '25' /digest ''' returned non-zero exit status 1. at Traceback (most recent call last): File "/usr/local/opnsense/service/modules/processhandler.py", line 484, in execute stdout=output_stream, stderr=error_stream) File "/usr/local/lib/python3.6/subprocess.py", line 311, in check_call raise CalledProcessError(retcode, cmd) subprocess.CalledProcessError: Command '/usr/local/opnsense/scripts/filter/read_log.py /limit '25' /digest ''' returned non-zero exit status 1.
`

I'm using OPNsense 19.7.a_487 (amd64/OpenSSL) (development version)

**Comment by AdSchellevis** [comment]
It seems you're using a development version, can you run the following on a console and dump the output?
```
/usr/local/opnsense/scripts/filter/read_log.py /limit '25' /digest ''
```

**Comment by berlinbikerx** [comment]
Yes, it's a dev version, the output follows:

`
[volker@gateway ~]$ /usr/local/opnsense/scripts/filter/read_log.py /limit '25' /digest ''
Traceback (most recent call last):
  File "/usr/local/opnsense/scripts/filter/read_log.py", line 112, in <module>
    running_conf_descr = fetch_rule_details()
  File "/usr/local/opnsense/scripts/filter/read_log.py", line 79, in fetch_rule_details
    for line in f_in:
  File "/usr/local/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 760: ordinal not in range(128)
[volker@gateway ~]$ 
`

**Comment by AdSchellevis** [comment]
seems like an encoding issue in the transition to python 3 , can you try https://github.com/opnsense/core/commit/2940f6adc804b7a0d05c2c1040e13fb604d4c0e9

Install using: 
```
opnsense-patch 2940f6a
````

I'm not 100% sure this  works, it not, I'll have to reproduce your issue somehow.

**Comment by berlinbikerx** [comment]
The patch made the live log work again on my installation.

Thanks a lot for the quick response.

**Comment by AdSchellevis** [comment]
@berlinbikerx thanks for reporting back!
