### ISSUE TITLE
Wireguard freezes whole system

### ISSUE THREAD

**Issue by patrick7** [opnsense/core#3437]
**Describe the bug**
Every second or third change in the wireguard config freezes the whole box, a cold reboot is necessary

**To Reproduce**
Change some wireguard settings, enable/disable local, peers, ...

**Expected behavior**
Not to freeze the box :-)

**Relevant log files**
Will see if I can get some after the box is rebooted on site

**Environment**
Software version used and hardware type if relevant.

OPNsense 19.1.6 (amd64, OpenSSL).
PCEngines APU2

**Comment by fichtner** [comment]
This is a known upstream issue to be fixed there soon, see https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=233955
