### ISSUE TITLE
'dev option' to enable http error log to catch UI issues

### ISSUE THREAD

**Issue by mschilt** [opnsense/core#344]
Would be great to have a misc setting that enables error logs for lightttpd.
Unfortunately the config file is 'hardcoded' so changing the config change is tricky and the config file gets overwritten all the time when lighttpd is restarted using rc-scripts.

Relevant part of the config file: 
debug.log-file-not-found     = "enable"

**Comment by fichtner** [comment]
There is a Log file settings toggle for "Web Server Log": Hint: If this is checked, errors from the lighttpd web server process for the GUI or Captive Portal will appear in the main system log.

Maybe we can just reuse it and/or splitt off the web log into a separate thingy.

**Comment by fichtner** [comment]
timeout
