### ISSUE TITLE
Feature Request: Select multiple plugins to install

### ISSUE THREAD

**Issue by lattera** [opnsense/core#3440]
Plugins currently must be installed one-by-one. Being able to select multiple plugins and install them in one go would improve usability. Perhaps a checkbox to the left of the plugin name and a new button to install selected plugins.

**Comment by fichtner** [comment]
@lattera are you talking about first time setup, config.xml import setup or general use?

For the second case there is this planned: #1663, for the other two the work is clear but I'm not entirely sure it's worth all the work and JS fiddling.

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository, 
please read https://github.com/opnsense/core/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue, 
just let us know, so we can reopen the issue and assign an owner to it.
