### ISSUE TITLE
Add a way to limit failed user logins per IP

### ISSUE THREAD

**Issue by pksadiq** [opnsense/core#3441]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[-] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[-] I have searched the existing issues and I'm convinced that mine is new.

It would be nice if there is a way to limit failed login attempts on web UI, like blocking the IP for some `n` minutes for `m` failed login attempts.  This can help avoid brute force attempts to some extend.

**Comment by AdSchellevis** [comment]
the webui and ssh are already guarded by https://github.com/opnsense/sshlockout_pf

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository, 
please read https://github.com/opnsense/core/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue, 
just let us know, so we can reopen the issue and assign an owner to it.
