### ISSUE TITLE
squid crashes when shutting down

### ISSUE THREAD

**Issue by Kimotu** [opnsense/core#3442]
[X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[X] I have searched the existing issues and I'm convinced that mine is new.

**Describe the bug**
Whenever squid shall be restarted or the system reboot/shutdown, squid crashes with segment violation and stays for ages in state D

**To Reproduce**
- Services --> squid --> stop
- Services --> squid --> restart
- Power --> Reboot
- Power --> Power off

**Expected behavior**
Restart of service or immediate reboot/shutdown

**Screenshots**

```
 Performing sanity check on squid configuration.
 2019/04/25 12:55:08| Warning: empty ACL: acl bump_nobumpsites ssl::server_name "/usr/local/etc/squid/nobumpsites.acl"
 Configuration for squid passes.
 Stopping squid.
 Waiting for PIDS: 11320
```
At this stage it needs minutes/hours for process finishing. To restart squid, I have to wait till it is in state 'D', then delete the pid to start a new instance while the one in state 'D' finally dies.

For fast reboots I have to press power button which affects filesystem.

**Relevant log files**
```
2019/04/25 12:12:39 kid1| Logfile: opening log stdio:/var/log/squid/netdb.state
2019/04/25 12:12:39 kid1| Logfile: closing log stdio:/var/log/squid/netdb.state
2019/04/25 12:12:39 kid1| NETDB state saved; 9 entries, 3 msec
2019/04/25 12:53:40| Set Current Directory to /var/squid/cache
2019/04/25 12:53:40 kid1| Preparing for shutdown after 680 requests
2019/04/25 12:53:40 kid1| Waiting 30 seconds for active connections to finish
2019/04/25 12:53:40 kid1| Closing HTTP port 127.0.0.1:3128
2019/04/25 12:53:40 kid1| Closing HTTP port [::1]:3128
[... some more ipv4 and ipv6 addresses]
2019/04/25 12:53:40 kid1| Closing HTTPS port 127.0.0.1:3129
2019/04/25 12:53:40 kid1| Closing HTTPS port [::1]:3129
2019/04/25 12:53:40 kid1| Closing Pinger socket on FD 53
2019/04/25 12:53:40 kid1| Closing SNMP receiving port [::]:3401
2019/04/25 12:54:11 kid1| Shutdown: NTLM authentication.
2019/04/25 12:54:11 kid1| Shutdown: Negotiate authentication.
2019/04/25 12:54:12 kid1| Shutdown: Digest authentication.
2019/04/25 12:54:12 kid1| Shutdown: Basic authentication.
2019/04/25 12:54:12 kid1| Shutting down...
2019/04/25 12:54:12 kid1| storeDirWriteCleanLogs: Starting...
2019/04/25 12:54:12 kid1|   Finished.  Wrote 0 entries.
2019/04/25 12:54:12 kid1|   Took 0.00 seconds (  0.00 entries/sec).
CPU Usage: 10.554 seconds = 8.807 user + 1.747 sys
Maximum Resident Size: 4562016 KB
Page faults with physical i/o: 9
2019/04/25 12:54:12 kid1| Logfile: closing log stdio:/var/log/squid/store.log
2019/04/25 12:54:12 kid1| Logfile: closing log stdio:/var/log/squid/access.log
2019/04/25 12:54:12 kid1| Open FD UNSTARTED     6 DNS Socket IPv6
2019/04/25 12:54:12 kid1| Open FD READ/WRITE    7 DNS Socket IPv4
2019/04/25 12:54:12 kid1| Open FD UNSTARTED     9 ssl_crtd #1
2019/04/25 12:54:12 kid1| Open FD UNSTARTED    11 ssl_crtd #2
2019/04/25 12:54:12 kid1| Open FD UNSTARTED    13 ssl_crtd #3
2019/04/25 12:54:12 kid1| Open FD UNSTARTED    15 ssl_crtd #4
2019/04/25 12:54:12 kid1| Open FD UNSTARTED    17 ssl_crtd #5
2019/04/25 12:54:12 kid1| Open FD READ/WRITE   55 client https start
2019/04/25 12:54:12 kid1| Open FD READ/WRITE   57 s-usc1c-nss-250.firebaseio.com                                                                                                                                                             :443
2019/04/25 12:54:12 kid1| Open FD READ/WRITE   62 client https start
2019/04/25 12:54:12 kid1| Open FD READ/WRITE   63 fls-eu.amazon.de:443
2019/04/25 12:54:12 kid1| Open FD READ/WRITE   66 client https start
2019/04/25 12:54:12 kid1| Open FD READ/WRITE   68 client https start
2019/04/25 12:54:12 kid1| Open FD READ/WRITE   69 push.services.mozilla.com:443
2019/04/25 12:54:12 kid1| Open FD READ/WRITE   70 client.wns.windows.com:443
FATAL: Received Segment Violation...dying.
2019/04/25 12:54:14 kid1| storeDirWriteCleanLogs: Starting...
2019/04/25 12:54:14 kid1|   Finished.  Wrote 0 entries.
2019/04/25 12:54:14 kid1|   Took 0.00 seconds (  0.00 entries/sec).
2019/04/25 12:55:09| Set Current Directory to /var/squid/cache
```

**Additional context**
I also have this problem on another opnsense with version 19.1.5 and had it with 19.1.4.
I thought a more powerful machine would solve it. Problems seems to occure more often if ssl inspection is enabled. I just use 'Log SNI information only'. So no need for bump sites.

**Environment**
Software version used and hardware type if relevant.
e.g.:

OPNsense 19.1.6-amd64
FreeBSD 11.2-RELEASE-p9-HBSD
OpenSSL 1.0.2r 26 Feb 2019

Intel(R) Xeon(R) Silver 4116 CPU @ 2.10GHz (24 cores)

**Comment by juliocbc** [comment]
Same behaviour here!! I've noted that are a huge RAM consumption when try to stop/shutdown the squid process. 

Another strange behaviour that may be related is the high Inactive memory the process hangs.

I just add the `memory_pools off` directive to `squid.conf` to try decreasing the memory usage.

OPNsense 18.7.10-amd64
FreeBSD 11.1-RELEASE-p18
OpenSSL 1.0.2q 20 Nov 2018

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository, 
please read https://github.com/opnsense/core/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue, 
just let us know, so we can reopen the issue and assign an owner to it.
