### ISSUE TITLE
Encoding errors on leases page

### ISSUE THREAD

**Issue by sjorge** [opnsense/core#3450]
**Describe the bug**
When viewing the DHCP lease page not all text is displayed properly.

e.g. the description "Trådfri" shows the raw escapped html version instead of the actually correct text. The page where you configure statpic mappings is fine.

leases page:
![leases page screenshot](https://i.imgur.com/C5P2Uem.png)

static mapping page:
![stattic mapping screenshot](https://imgur.com/ebPWEtz.png)

**To Reproduce**
1. Create a static DHCP mapping and give it a description with some non base set letters in it like the scandianvion å, ö, Ø, ...
2. Make sure something grabs the lease
3. Check the leases page

**Expected behavior**
That the text shows up correctly in all places.

**Screenshots**
See above

**Relevant log files**
N/a

**Additional context**
N/a

**Environment**
OPNsense 19.1.6-amd64

**Comment by sjorge** [comment]
There seems to be a similar issue on the firewall rule page, atleast for the ' and " characters which are perfectly fine and accepted in the edit rule page.

So this might be a more general issue.

**Comment by AdSchellevis** [comment]
duplicate https://github.com/opnsense/core/issues/3427, usually all parameters are escaped all at once,  it looks like this page had an extra escape in the field. If you find others, please check the current issues/code and open an issue if it's not already there. Thanks!

**Comment by sjorge** [comment]
I did searched, did not remove the default filter that excludes closed issues. My bad

**Comment by AdSchellevis** [comment]
things happen, don't worry :)
