### ISSUE TITLE
firmware: cron jobs vs. plugins

### ISSUE THREAD

**Issue by curiousgrge** [opnsense/core#3451]
Installed Let's Encrypt Plugin to tinker and only browsed through the different setup sequences including automation.

After removing plugin, found an enabled job to renew certificates still exists from System, Settings, Cron.  This particular job cannot be deleted regardless of how I try from the GUI.

While the job can be disabled, would like the ability to remove it completely.

OPNsense 19.1.4 amd64 nano

**Comment by fichtner** [comment]
I tried to remove the delete button when the item cannot be deleted to create more visibility, but it's not easily possible and the issue has been dormant for 2 years now so I think we should close this and need to reevaluate with new data points (bugs reported).
