### ISSUE TITLE
Squid logs are not sent to syslog

### ISSUE THREAD

**Issue by netranger512** [opnsense/core#3454]
**Description**

Squid access logs are sent to the captive portal logs when **Web Proxy > Log Target > Syslog** is selected. This stops them from being sent to the syslog server at all (probably because Captive Portal is not used in my setup)
Other logtypes get correctly sent to the syslog server (firewall logs, surricata logs etc.)

**To Reproduce**
- Set **Remote Syslog Servers** to your syslog server IP
- Activate **Web Proxy > Log Target > Syslog** 
- Use the webproxy to access some sites, the logs will end up in the captive portal log

**Expected behavior**
- The squid access logs should end up in the correct log file and/or be sent to the server configured under **Remote Syslog Servers**

**Screenshots**

![log_captive](https://user-images.githubusercontent.com/50147745/56976297-ef7e8200-6b72-11e9-833c-ef31979dd79a.PNG)
![log_wp](https://user-images.githubusercontent.com/50147745/56976298-f0171880-6b72-11e9-97a5-77f5e0264867.PNG)

**Environment**

SW: OPNsense 19.1.4-amd64/ FreeBSD 11.2-RELEASE-p9-HBSD / OpenSSL 1.0.2r 26 Feb 2019
HW: APU2C4
NIC: Intel i210AT LAN

**Comment by AdSchellevis** [comment]
oops, it seems that https://github.com/opnsense/core/commit/dd2f34ffd9c40d81cf4617c0cb72c50cb32cdbac was accidentally removed in https://github.com/opnsense/core/commit/86d290ec28d0de48128754e91cb12543df09f6d9. There probably aren't a lot of people using this. I'll re-add and close the issue when done.

**Comment by fichtner** [comment]
This wasn't a head-on accident, "/var/ log/squid.syslog.log" is a really weird way to name a file for a service that throws its logs into /var/log/squid/" to begin with. I think the preferred way was to have something like a "proxy.log" file, but that would be reserved for core services then since we can't "plug" the file name at the moment from separate plugins.

**Comment by AdSchellevis** [comment]
The naming is weird indeed, but we can't mix syslog and file targets due to clog at the moment. The target was used, so we should place something back to make sure the feature can work. /var/log/squid.log is probably the closest thing to logic within the boundaries we have at the moment.

**Comment by AdSchellevis** [comment]
@fichtner within the available constraints, this https://github.com/opnsense/core/commit/464495b58e9d600a76f14c25e5959112426c4e48 is the best I can think of at the moment. Feel free to revert and replace for something better.

**Comment by fichtner** [comment]
Will be in 19.1.10.
