### ISSUE TITLE
Save voucher database of opnsense

### ISSUE THREAD

**Issue by RomanJos** [opnsense/core#3456]
Hi there is an option to save the voucher already generated ? because if i reset my machine and apply my config file i need to re-generate the list of voucher and give the new one to the client. Thanks a lot.

**Comment by AdSchellevis** [comment]
the vouchers are stored in `/conf/vouchers_*`, we don't offer a gui option to backup these files from the gui at the moment (you can use scp/sftp).

**Comment by RomanJos** [comment]
Perfect ! So if i reset my machine i will need to generate some new voucher to get a new voucher_xxxxxxx.db and replace them with this file. Thanks
