### ISSUE TITLE
Port aliases not working due to incorrect handling of port alias "content" field

### ISSUE THREAD

**Issue by jospanier** [opnsense/core#3458]
port alias GUI parsing has a small but ugly flaw. 
I added a ports alias into the GUI, but the rule using the alias did not work.
Upon closer inspection I noticed that the GUI had allowed me to add an additionan space in front of the actual port numbers. This is the downlodas JSON for the port aliases. admin_ports is working, broken ports is not working. Both were entered via GUI.
"""
{
  "aliases": {
    "alias": {
      "20fe1b7f-f4cd-459d-a432-61b237ec63a3": {
        "enabled": "1",
        "name": "admin_ports",
        "type": "port",
        "proto": "",
        "updatefreq": "",
        "content": "80\n443\n22",
        "description": ""
      },
      "925b5867-b983-4962-a9ff-592cf5d96e72": {
        "enabled": "1",
        "name": "broken_ports",
        "type": "port",
        "proto": "",
        "updatefreq": "",
        "content": "80\n 443\n 22",
        "description": ""
      }
    }
  }
}
"""
to reproduce this bug simply add a port alias via GUI with this strin into the "Content" field:
"""
80, 443, 22
"""
note the additional space after each comma. Resulting alias does not work as expected

the expected behavior would be for the GUI to validate the input and then strip leading and trailing whitespace per port

**Environment**
OPNsense 19.1.7-amd64
same bug also on a OPNsense 19.1.5-amd64

**Comment by AdSchellevis** [comment]
We don't change data in validation, but it should signal the user if the data isn't valid. I'll take a look

**Comment by AdSchellevis** [comment]
confirmed, fixed in https://github.com/opnsense/core/commit/f2305e34456fe9d5d81e887b43f356a9a5d88cb4
