### ISSUE TITLE
OpenVPN GUI: setting for TLS Authentication always overwritten

### ISSUE THREAD

**Issue by fraenki** [opnsense/core#346]
If you edit an existing OpenVPN Server configuration the settings for "TLS Authentication" will always be set to "enabled".

Steps to reproduce:
- edit an existing OpenVPN server configuration
- disable "TLS Authentication"
- save config
- now the options is removed from openvpn configuration file

Result:
- edit the OpenVPN server configuration again
- now the "TLS Authentication" setting is shown as "enabled" again
- if you save this (unmodified) configuration you'll actually change the TLS configuration

Expected result:
- the setting for "TLS Authentication" should be read from the existing configuration, instead of overwriting it with a default value

**Comment by AdSchellevis** [comment]
@fraenki Thanks for reporting.
Should be fixed with https://github.com/opnsense/core/commit/505db10bc7507882d2e7b0330ad1ba52a04ef20e

**Comment by olliff** [comment]
the described issue also applies to the openvpn CLIENT configuration, and hasn't been fixed by now.
