### ISSUE TITLE
firewall rules overview (19.7) - page spacing on the left side too small

### ISSUE THREAD

**Issue by opnsenseuser** [opnsense/core#3462]
I noticed that in the dev version 19.7 the side clearance on the left side no longer fits. Reason is the new class "table-condensed". If you remove this class, then again fits the page distance. Under 19.1, this class has not yet existed.
Have attached two screenshots for comparison.

problem with "table-condensed" class
![grafik](https://user-images.githubusercontent.com/34602360/57181244-755f3d80-6e91-11e9-9d2e-bd3ef56a1e76.png)

without "table-condensed" class
![grafik](https://user-images.githubusercontent.com/34602360/57181283-fae2ed80-6e91-11e9-94f2-94f550977c83.png)

**Comment by AdSchellevis** [comment]
we should probably center the checkbox, table-condensed is standard bootstrap.

**Comment by opnsenseuser** [comment]
@AdSchellevis ok, we could change it with center or padding in the main file (firewall-rules.php) , or use an existing class or define one? .. do you want to do it or should I?  rene

**Comment by AdSchellevis** [comment]
@opnsenseuser I'll take a look

**Comment by AdSchellevis** [comment]
@opnsenseuser this https://github.com/opnsense/core/commit/a6013d0545c43b32a3d87f7c68d1ce617c8b610c should be better

**Comment by opnsenseuser** [comment]
great, but one important thing is still missing!

![grafik](https://user-images.githubusercontent.com/34602360/57194091-d4c95600-6f42-11e9-81bd-87779b3915a3.png)

**Comment by opnsenseuser** [comment]
@AdSchellevis 

in the 19.1 version the class "table-condensed" is not used. only this alone makes the difference!
See comparison 19.7 / 19.1
![grafik](https://user-images.githubusercontent.com/34602360/57194360-52429580-6f46-11e9-828a-80dc1655c397.png)

**Comment by AdSchellevis** [comment]
@opnsenseuser the table-condensed is a standard bootstrap class, but since "condensed", it lacks right spacing. The condensed layout offers more space and overview, which was a conscious choice.

**Comment by opnsenseuser** [comment]
@AdSchellevis 
my solution would be to hardcode this into the firewall-rule.php

> table#rules {
>     margin: 15px;
> }

it fits perfect!
also the distance fits. and the class ".select-col" could be removed. what do you think?

![grafik](https://user-images.githubusercontent.com/34602360/57194603-fd544e80-6f48-11e9-9a12-a10599637f11.png)

**Comment by opnsenseuser** [comment]
@AdSchellevis or just margin-left:15px. as you wish!

**Comment by opnsenseuser** [comment]
@AdSchellevis sorry, padding:15px is better!!

**Comment by opnsenseuser** [comment]
@AdSchellevis Unfortunately, my solution does not seem to be perfect either. But you should still work on it and leave the problem open in all cases. 
best regards, rene

**Comment by opnsenseuser** [comment]
@AdSchellevis 
i found a 100% working solution.
only needs three hardcoded entries

    #rules > thead > tr > th{
      padding-left: 15px;
    }
    #rules > tbody > tr > td{
      padding-left: 15px;
    }
    #rules > tfoot > tr > td {
      padding-left: 15px;
    }

or just

#rules > thead > tr > th, #rules > tbody > tr > td, #rules > tfoot > tr > td{
      padding-left: 15px;
 }

**Comment by AdSchellevis** [comment]
@opnsenseuser if you replace my version with a PR with your proposition, I'll have a look. It looks workable for me. Thanks in advance.

**Comment by opnsenseuser** [comment]
@AdSchellevis i take care of it!

**Comment by opnsenseuser** [comment]
@AdSchellevis https://github.com/opnsense/core/pull/3467

**Comment by AdSchellevis** [comment]
@opnsenseuser at a first glance the padding looks good, I'll take a closer look later. thanks
