### ISSUE TITLE
ver. 19.1.7 NAT Rule issues - GUI and References to Aliases broken

### ISSUE THREAD

**Issue by stefan-kos** [opnsense/core#3463]
Hello dear OPNsense Team,

I found an issue in the Outbound NAT Rules view when using an Alias for a group of networks and negating it for the destination. It shows only the '!' sign but not the Alias object. But the configuration XML looks good and it works correctly.

The second is, using an Alias in the destination field on outbound NAT => change the name of the Alias, the reference to it gets broken, and in the Gui then something else happens.

1. Create 3 network aliases e.g. Net_10_1_1_0_24 (10.1.1.0/24), Net_10_2_1.... , Net_10_3_...
2. Create another alias e.g. All_Internal_Networks (add all 3 above aliases)
3. Create a manual outbound NAT rule and using the All_Internal_Networks alias in the Destination field and negate it.
4. Save the rule - the Alias is not showing in the Rule, just the exclamation sign.

Reproducing the second can be done with the same alias.
1. Just rename the existing alias to something else
2. Edit the before created NAT Rule and look at the destination field

<img width="1298" alt="nat png" src="https://user-images.githubusercontent.com/50271649/57182085-9167dc80-6e9b-11e9-9bf7-4ca06c6bbb6e.png">

OPNsense 19.1.7-amd64
FreeBSD 11.2-RELEASE-p9-HBSD
OpenSSL 1.0.2r 26 Feb 2019

Very best regards, Stefan

**Comment by AdSchellevis** [comment]
@stefan-kos thanks for reporting, looks like a typo. should be fixed with https://github.com/opnsense/core/commit/97d0b22a603fc22537d1a13db2359f42a9c15dde

**Comment by stefan-kos** [comment]
Hello sir, wow! That was the quickest response ever I experienced in my live while making a bug report!
Thank you all for your great work on this! Need to say this. Cheers, Stefan

**Comment by stefan-kos** [comment]
Hello again, btw., I just fixed it manually quickly, it works! Great, thanks a lot!

**Comment by AdSchellevis** [comment]
thanks for confirming!
