### ISSUE TITLE
IPS duplicate entries

### ISSUE THREAD

**Issue by L1ghtn1ng** [opnsense/core#3465]
**Describe the bug**
Duplicate entries in the alerts tab for IPS alerts

**To Reproduce**
Steps to reproduce the behaviour:
1. Have eicar rule installed and set to drop
2. Generate an alert
3. See error in the alerts tab

**Expected behaviour**
No duplicate entries

**Screenshots**
![image](https://user-images.githubusercontent.com/3628354/57186937-6b642b80-6edf-11e9-9882-12d998e3b37e.png)

**Relevant log files**
When I query the API I have found the following
```
{'alert': 'OPNsense test eicar virus', 'action': 'blocked', 'alert_sid': '7999999', 'dest_ip': '10.0.0.3', 'dest_port': '56816', 'event_type': 'drop', 'in_iface': 'em1+', 'proto': 'TCP', 'src_ip': '213.211.198.58', 'src_port': '80', 'timestamp': '2019-05-05T01:47:45.807239+0100', 'total alerts': '2'}
{'alert': 'OPNsense test eicar virus', 'action': 'blocked', 'alert_sid': '7999999', 'dest_ip': '10.0.0.3', 'dest_port': '56816', 'event_type': 'alert', 'in_iface': 'em1+', 'proto': 'TCP', 'src_ip': '213.211.198.58', 'src_port': '80', 'timestamp': '2019-05-05T01:47:45.807239+0100', 'total alerts': '2'}
```
From this we can see that we are getting the drop and alert events when only should be having drops. All my rules are set to drop. 
**Environment**
OPNsense 19.1.7 (amd64, LibreSSL).
A10 Desktop

**Comment by AdSchellevis** [comment]
I think this has been the case all along with netmap enabled, could be a result of having both alerts and drops logged, could also be related to traffic passing netmap twice. 

If there's a known version where this was different, I gladly take a look if there's something we changed.

**Comment by L1ghtn1ng** [comment]
@AdSchellevis I cannot remember unfortunatley

**Comment by L1ghtn1ng** [comment]
@AdSchellevis This is what I get in my eve.json and from me playing around with the API I have found a way of fixing the output from my python script when querying the API.

Can this be done in the dropAlertLog.py file if this is the correct place and you can see what I am trying to get at?
```
    ips_url = 'https://10.0.0.1/api/ids/service/queryAlerts'
    request = requests.post(ips_url, auth=(key, secret))

    if request.status_code == 200:
        response = request.text
        parsed_json = json.loads(response)
        alerts = parsed_json['rows']
        for entries in alerts:
            # Skip printing logs that have event type alert as all we want is drop ones
            if entries['event_type'] == 'alert':
                continue
            else:
                send_email(subject='IPS Report', message={
                    'alert': '{alert}'.format(**entries),
                    'action': '{alert_action}'.format(**entries),
                    'alert_sid': '{alert_sid}'.format(**entries),
                    'dest_ip': '{dest_ip}'.format(**entries),
                    'dest_port': '{dest_port}'.format(**entries),
                    'event_type': '{event_type}'.format(**entries),
                    'in_iface': '{in_iface}'.format(**entries),
                    'proto': '{proto}'.format(**entries),
                    'src_ip': '{src_ip}'.format(**entries),
                    'src_port': '{src_port}'.format(**entries),
                    'timestamp': '{timestamp}'.format(**entries),
                    'total alerts': '{}'.format(parsed_json['total'])
                })
    elif request.status_code == 401:
        print('Authentication Failure, check api key and secret')
    else:
        print(request)


if __name__ == '__main__':
    try:
        main()
    except KeyboardInterrupt:
        print('\nctrl+c detected, quitting...')
```

```
{"timestamp":"2019-05-31T00:16:34.517908+0100","flow_id":1423093999449949,"in_iface":"em1+","event_type":"alert","src_ip":"213.211.198.58","src_port":80,"dest_ip":"10.0.0.3","dest_port":53502,"proto":"TCP","alert":{"action":"blocked","gid":1,"signature_id":7999999,"rev":1,"signatur>
{"timestamp":"2019-05-31T00:16:34.517908+0100","flow_id":1423093999449949,"in_iface":"em1+","event_type":"drop","src_ip":"213.211.198.58","src_port":80,"dest_ip":"10.0.0.3","dest_port":53502,"proto":"TCP","drop":{"len":409,"tos":0,"ttl":58,"ipid":54580,"tcpseq":3561322068,"tcpack":>
{"timestamp":"2019-05-31T00:16:41.209048+0100","flow_id":1423093999449949,"in_iface":"em1","event_type":"drop","src_ip":"10.0.0.3","src_port":53502,"dest_ip":"213.211.198.58","dest_port":80,"proto":"TCP","drop":{"len":52,"tos":0,"ttl":64,"ipid":55009,"tcpseq":445430533,"tcpack":356>
```

**Comment by AdSchellevis** [comment]
@L1ghtn1ng you could do that in your script, but we shouldn't generally hide alerts for all users, no. Adding extra filters to the user interface would be good, but not planned by us at the moment. Our alert view is rather simple, most people use additional tools to collect metrics.

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository, 
please read https://github.com/opnsense/core/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue, 
just let us know, so we can reopen the issue and assign an owner to it.
