### ISSUE TITLE
OpenVPN GUI: setting "Topology" not respected for CSCs

### ISSUE THREAD

**Issue by fraenki** [opnsense/core#347]
The OpenVPN server configuration allows to enable the "Topology" setting, which enables the "topology subnet" option in OpenVPN.

Unfortunately, when enabling this setting and combining it with _Client specific overrides_, it may lead to a flawed CSC (client specific configuration). The VPN client may report something like this:

```Tun interface setup failed: addr_pair_mask_parse_error: AddrMaskPair parse error 
'ifconfig': 10.x.x.2/10.x.x.1: ipv4_exception: malformed netmask```

As you can see from the message above, the CSC is still configured for "topology net30", while it should've been updated for the new "topology subnet" setting.

Actual CSC for "topology subnet":
```ifconfig-push 10.x.x.2 10.x.x.1```

Expected CSC for "topology subnet":
```ifconfig-push 10.x.x.2 255.255.255.0```

**Comment by AdSchellevis** [comment]
this one can only be solved in conjunction with https://github.com/opnsense/core/issues/296, in the current version you just don't know which server the override is bound to.

**Comment by AdSchellevis** [comment]
@fraenki both https://github.com/opnsense/core/issues/296 and this issue should be fixed win the following commit https://github.com/opnsense/core/commit/d101b28e4582bb68a329505bf17480e8302b6240 

If you have time to test, just download the next files on a 16.1 release:

```
curl -o /usr/local/etc/inc/openvpn.inc https://raw.githubusercontent.com/opnsense/core/master/src/etc/inc/openvpn.inc
curl -o /usr/local/www/vpn_openvpn_csc.php https://raw.githubusercontent.com/opnsense/core/master/src/www/vpn_openvpn_csc.php
curl -o /usr/local/www/vpn_openvpn_server.php https://raw.githubusercontent.com/opnsense/core/master/src/www/vpn_openvpn_server.php
```

**Comment by fichtner** [comment]
@fraenki any news here? :)

**Comment by AdSchellevis** [comment]
timeout.
