### ISSUE TITLE
LDAP: support memberof attribute to synchronise groups

### ISSUE THREAD

**Issue by AdSchellevis** [opnsense/core#3471]
With https://github.com/opnsense/core/commit/1ddbb3bdbb2c895b4c224d39e16120d5db94bebf we are able to request user attributes after login, if the ldap (AD) server supports it, we can use this to synchronise groups after successful login.

In case of MS AD there's one small remark, the primary user group won't be reported (by default) in `memberof`. Use the authentication tester to test if your server supports the memberof attribute.

**Comment by ruffy91** [comment]
It seems I am unable to get nested groups which the user is member of.
As most Windows users follow AGDLP (Global group containing user, local group giving permission, global group added as member of local group) best practice this poses a problem.

Resolving nested groups should be possible using LDAP_MATCHING_RULE_IN_CHAIN (1.2.840.113556.1.4.1941) in the search query.
For example:

To find all groups including nested which User1 is member of:
(member:1.2.840.113556.1.4.1941:=CN=User1,OU=X,DC=domain,DC=com) 
Or searching for all users including nested which are member of A Group:
(memberOf:1.2.840.113556.1.4.1941:=CN=A Group,OU=Y,DC=domain,DC=com)
 
Could you please add a switch which allows selecting this behavior to include nested groups.

**Comment by AdSchellevis** [comment]
@ruffy91 this ticket is closed (we usually don't respond on closed tickets), feel free to open a new one with a feature request if there's something missing.I'm not sure you can easily return the nested attribute, you could try to fiddle a bit with the query settings and check the output in the tester tool.

The code responsible for reading the attributes is:
https://github.com/opnsense/core/blob/7218726f59c39cf6a76b0b2d09aa247d19f066c0/src/opnsense/mvc/app/library/OPNsense/Auth/LDAP.php#L571-L586

If you can output the results in ldap_get_entries(), which also returns in the tester tool, it likely wouldn't be a huge issue to add the feature. A quick search online doesn't show a lot of functional examples.

**Comment by rudiservo** [comment]
The Cloud import button is missing after I added LDAP server (Zentyal, I can communicate with it):

Also I got this error, is it linked somehow?

`[07-Oct-2019 16:24:01 Atlantic/Azores] PHP Warning:  implode(): Invalid arguments passed in /usr/local/www/system_authservers.php on line 249`
