### ISSUE TITLE
Intrusion Detection: api error while editing rules

### ISSUE THREAD

**Issue by dinguz** [opnsense/core#3474]
**Describe the bug**

Error at editing Intrusion Detection rules: 

**To Reproduce**

Go to Services -> Intrusion Detection -> Administration -> Rules
wait a few seconds, then see error:

An API exception occured:
Error at /usr/local/opnsense/mvc/app/controllers/OPNsense/IDS/Api/SettingsController.php:137 - count(): Parameter must be an array or an object that implements Countable (errno=2)

**Expected behavior**

Edit IDS rules

**Screenshots**

![Clipboard01](https://user-images.githubusercontent.com/50438934/57432834-333e4f00-7237-11e9-84f7-5775c5d74cb8.jpg)

**Environment**

OPNsense 19.1.7 (amd64/OpenSSL)
Intel(R) Atom(TM) CPU  C2358
Network Intel igb

**Comment by fichtner** [comment]
@dinguz we've been unable to reproduce this. can you install the "os-debug" plugin and show the error message again... it should have a stack trace attached

**Comment by dinguz** [comment]
Hi Franco,

I have done as you requested; I have installed os-debug and rebooted to be
sure. To my surprise the error is gone, everything works as expected.
After that I decided to test again, so I uninstalled os-debug and rebooted,
and then the error came right back. So I presume having os-debug installed
masks the problem somehow.


Kind regards,

Derkjan de Haan


Op do 9 mei 2019 om 08:55 schreef Franco Fichtner <notifications@github.com

**Comment by fichtner** [comment]
Hi Derkjan,

Aha, thanks for this tip! I'll try to reproduce this further.

Just one question: this is a new install from a 19.1.4 image?


Cheers,
Franco

**Comment by dinguz** [comment]
Hi Franco,

I bought this device with a fresh install of 18.7 on it, IIRC. When I
started using it, I did a factory reset and upgrade to 19.1.


Kind regards,

Derkjan de Haan

Op do 9 mei 2019 om 10:47 schreef Franco Fichtner <notifications@github.com>:

**Comment by BobbyGil** [comment]
My OpnSense at all sites had the same issue and after installing the plugin os-debug ; the issues disappeared. I will install it all of them.

**Comment by ssbarnea** [comment]
I can confirm the the issue on 19.1.9 but installing os-debug the issue did not disapear. For the moment I disabled the intrussion detection as it was of not much use in broken state.

**Comment by fichtner** [comment]
Does the following patch fix it?

# opnsense-patch 67b404f

**Comment by dinguz** [comment]
Yes, with this patch it's working fine now, without having os-debug
installed. Many thanks!


Met vriendelijke groet,

Derkjan de Haan


Op zo 23 jun. 2019 om 20:49 schreef Franco Fichtner <
notifications@github.com>:

**Comment by fichtner** [comment]
Hi Derkjan,

Thanks for confirming. This patch will be added to 19.1.10 or 19.1.11. I'm not 100% sure yet.


Cheers,
Franco
