### ISSUE TITLE
Port Aliases not correctly sanitized/validated when pasting

### ISSUE THREAD

**Issue by ruffy91** [opnsense/core#3475]
**Describe the bug**
When pasting lists of ports into a Port alias the input is not correctly validated.

**To Reproduce**
1. Create Port alias
2. Paste following input: 20, 21, 22, 23
3. alias is created with ports [20] [ 21] [ 22] [ 23]
4. Use alias in Firewall rule
5. only port 20 is in the rule, because there is an space in front of every following port

The issue does not happen when manually adding the ports becuase there a space creates a new entry.

**Expected behavior**
Spaces and other invalid characters are either removed or throw an error when creating the alias

**Environment**
OPNsense 19.1.7 (amd64, OpenSSL).
Chrome or Firefox

**Comment by AdSchellevis** [comment]
duplicate https://github.com/opnsense/core/issues/3458
