### ISSUE TITLE
CARP IPv6 / ND / CARP with IPv6 on WAN doesn't work as expected. 

### ISSUE THREAD

**Issue by abplfab** [opnsense/core#3476]
More Investigations done and found a workaround. See also #1790 
Setup:
Our Net: 2a02:aa08:xy:900::/56
Provider Router 2a02:aa08:xy:900::1
WAN Net: 2a02:aa08:xy:900::/64
LAN Net: 2a02:aa08:xy:902::/64
OPNsense1 WAN IPv6: 2a02:aa08:xy:900::14/64
OPNsense2 WAN IPv6: 2a02:aa08:xy:900::13/64
OPNsense WAN CARP vIP: 2a02:aa08:xy:900::2/64
Workstation on WAN Switch  2a02:aa08:xy:900::6
All WAN Devices are connected on the same switch.

What we found out:
* ::2 iCARP vIP s only reachable from devices in the WAN net
* Pinging the CARP WAN vIP ::2 from the ::6 Workstation is always possible, after that ::2 is also pingable from outside the 2a02:aa08:xy:900::/64 net for about 20s and all routing etc. is working as expected

Investigation & temporary solution from our provider:

> Unser ipv6 neighbor table zeigt den Eintrag erst wenn wir die Addresse  2A02:AA08:xy:900::2 pingen, kurz danach lauft der Eintrag ab.
> 
> ch-mceBUB010#sh ipv6  nei vrf INTERNET1                                              
> Load for five secs: 1%/0%; one minute: 1%; five minutes: 1% Time source is NTP, 12:42:02.924 CEST Fri May 10 2019
> 
> IPv6 Address                              Age Link-layer Addr State Interface
> 2A02:AA08:xy:900::6                       0 000d.b94f.619a  REACH Gi9
> 2A02:AA08:xy:900::13                      0 0cc4.7a97.e943  REACH Gi9
> 2A02:AA08:xy:900::14                      0 0cc4.7a97.e5e3  REACH Gi9
> 2A02:AA08:F000:5::1                         0 70e4.2268.1074  REACH Gi8.1188
> FE80::72E4:22FF:FE68:1074                   0 70e4.2268.1074  REACH Gi8.1188
> 
> 
> 
> Wir stellen fest dass kurz nach einem Ping aus dem connected Interface , die CARP ( 2A02:AA08:xy:900::2 ) gibt Antwort zu unserem NS mit eineme NA und ARP Addresse.
> 
> May 10 12:38:30.791 CEST: ICMPv6-ND: (GigabitEthernet9,2A02:AA08:xy:900::2) DELETE -> INCMP
> May 10 12:38:30.791 CEST: ICMPv6-ND: (GigabitEthernet9,2A02:AA08:xy:900::2) Sending NS               ---------------------------> neighbor Sollicitation
> May 10 12:38:30.791 CEST: ICMPv6-ND: (GigabitEthernet9,2A02:AA08:xy:900::2) Queued data for resolution
> May 10 12:38:30.795 CEST: ICMPv6-ND: (GigabitEthernet9,2A02:AA08:xy:900::2) Received NA from 2A02:AA08:xy:900::14        -------------> neighbor Advertissement
> May 10 12:38:30.795 CEST: ICMPv6-ND: (GigabitEthernet9,2A02:AA08:xy:900::2) LLA 0000.5e00.0114 May 10 12:38:30.795 CEST: ICMPv6-ND: (GigabitEthernet9,2A02:AA08:xy:900::2) INCMP -> REACH
> 
> 
> aus einem anderen Interface , gibt die CARP ( 2A02:AA08:xy:900::2 ) kein antwort zu unserem NS und deswegen kennt unser Router die entsprechende ARP nicht. 
> 
> 
> May 10 12:31:44.852 CEST: ICMPv6-ND: (GigabitEthernet9,2A02:AA08:xy:900::2) Resolution request 
> May 10 12:31:44.852 CEST: ICMPv6-ND: (GigabitEthernet9,2A02:AA08:xy:900::2) DELETE -> INCMP 
> May 10 12:31:44.852 CEST: ICMPv6-ND: (GigabitEthernet9,2A02:AA08:xy:900::2) Sending NS 
> May 10 12:31:44.852 CEST: ICMPv6-ND: (GigabitEthernet9,2A02:AA08:xy:900::2) Queued data for resolution 
> May 10 12:31:45.880 CEST: ICMPv6-ND: (GigabitEthernet9,2A02:AA08:xy:900::2) Sending NS 
> May 10 12:31:46.852 CEST: ICMPv6-ND: (GigabitEthernet9,2A02:AA08:xy:900::2) Replaced data for resolution 
> May 10 12:31:46.904 CEST: ICMPv6-ND: (GigabitEthernet9,2A02:AA08:xy:900::2) Sending NS 
> May 10 12:31:47.928 CEST: ICMPv6-ND: (GigabitEthernet9,2A02:AA08:xy:900::2) INCMP -> DELETE 
> May 10 12:31:48.852 CEST: ICMPv6-ND: (GigabitEthernet9,2A02:AA08:xy:900::2) Resolution request 
> May 10 12:31:48.852 CEST: ICMPv6-ND: (GigabitEthernet9,2A02:AA08:xy:900::2) DELETE -> INCMP 
> May 10 12:31:48.852 CEST: ICMPv6-ND: (GigabitEthernet9,2A02:AA08:xy:900::2) Sending NS 
> May 10 12:31:48.852 CEST: ICMPv6-ND: (GigabitEthernet9,2A02:AA08:xy:900::2) Queued data for resolution 
> May 10 12:31:49.944 CEST: ICMPv6-ND: (GigabitEthernet9,2A02:AA08:xy:900::2) Sending NS 
> May 10 12:31:50.852 CEST: ICMPv6-ND: (GigabitEthernet9,2A02:AA08:xy:900::2) Replaced data for resolution 
> May 10 12:31:51.032 CEST: ICMPv6-ND: (GigabitEthernet9,2A02:AA08:xy:900::2) Sending NS 
> May 10 12:31:52.112 CEST: ICMPv6-ND: (GigabitEthernet9,2A02:AA08:xy:900::2) INCMP -> DELETE

Workaround:
> statische Binding Lösung: 
> ch-mceBUB010(config)#ipv6 neighbor 2A02:AA08:xy:900::2 gigabitEthernet 9 0000.5e00.0114

But I guess there should be a smarter & nicer solution...

Also investigating the following behavor:
* With the solution above, the CARP vIP is pingable and smokeping looks ok: http://batman.home4u.ch/cgi/smokeping.cgi?target=asterix-neratec-com-ip6
* The "real" IPv6 Addresses of the firewall shows ugly loss: http://batman.home4u.ch/cgi/smokeping.cgi?target=asterix1-neratec-com-ip6 && http://batman.home4u.ch/cgi/smokeping.cgi?target=asterix2-neratec-com-ip6

**Comment by fichtner** [comment]
Habe you looked at https://github.com/opnsense/core/issues/3468 ?

**Comment by abplfab** [comment]
Not yet, but applied the patch and testing...

**Comment by abplfab** [comment]
Provider removed the static mapping in his router. The patch from #3468 doesn't solve the problem.

**Comment by abplfab** [comment]
Any Updates on that?

**Comment by abplfab** [comment]
Reads very similar https://forums.freebsd.org/threads/freebsd-12-not-answering-neighbor-solicitation.69035/

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/core/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
