### ISSUE TITLE
Possibility to configure DHCP failover parameters (split, mclt)

### ISSUE THREAD

**Issue by clystron** [opnsense/core#3479]
It would be helpful to be able to specify failover parameters for dhcpd, "split" would be the most interesting one for me but maybe you could add an "advanced" text-area so that multiple parameters could be configured.

**Comment by clystron** [comment]
In the meantime I have created a pull-request for the "split"-parameter (#3484), if there is still missing information please let me know.

**Comment by AdSchellevis** [comment]
@clystron thanks, closed with https://github.com/opnsense/core/pull/3484
