### ISSUE TITLE
Opnsense Firewall rebooted itself and then stuck at Error " trying to mount root from ufs"

### ISSUE THREAD

**Issue by Ifwanfly** [opnsense/core#3480]
Hi Guys,

Need yours kind assistance on this.
I'm having issue with the opnsense firewall running version on below.
The firewall will reboot itself after running for a period of time and then stuck at booting screen.
Trying to search the info from opnsense forum but unfortunately the forum seems like inaccessible [ Sorry Guest, you are banned from using this forum! This ban is not set to expire.]

Firmware Version
OPNsense 18.1.6-amd64
Intel(R) Xeon(R) CPU E31225 @ 3.10GHz (4 cores)
FreeBSD 11.1-RELEASE-p9
OpenSSL 1.0.2o 27 Mar 2018

**To Reproduce**
1. Manually rebooted the firewall and then it will stuck at booting screen with below error
=====================================
Trying to mount root from ufs:/dev/gpt/rootfs [rw]...
WARNING: /mnt was not properly dismounted
WARNING: /mnt: mount pending error: block 40 files 0
WARNING: /mnt: reload pending error: block 40 files 0
WARNING: /mnt: reload pending error: block 40 files 0
=====================================

Workaround
have to forced shutdown the appliance and power on again in order to boot up properly

**Screenshots**
![WhatsApp Image 2019-03-28 at 10 59 25 (1)](https://user-images.githubusercontent.com/50606667/57668174-0b852780-7639-11e9-8c88-b97d01829850.jpeg)

**Relevant log files**
Not able to located any relevant log message in /var/log

**Comment by fichtner** [comment]
> Manually rebooted the firewall and then it will stuck at booting screen with below error

My best help here is recommending to not do this. The file system is really sensitive to this and will fault on you.
