### ISSUE TITLE
Feature request: HTML5-Application-Portal

### ISSUE THREAD

**Issue by AndyX90** [opnsense/core#3481]
[+] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[+] I have searched the existing issues and I'm convinced that mine is new.

**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
It would be great to implement a HTML5-Webportal to provide access to local VNC/RDP/SSH Resources without the need of a specific Client.
This could be reached with [Apache Guacamole™](https://guacamole.apache.org/).
Other Firewall-Appliances (like Sophos UTM) provide similar functionality and call this "HTML5-VPN-Portal".

**Describe alternatives you've considered**
-

**Additional context**
It could be delivered securely by requiring a clientcertificate for authentication.

**Comment by AdSchellevis** [comment]
We had a similar discussion last year (https://github.com/opnsense/tools/issues/91), Guacamole™ looks too heavy weighted and difficult to integrate neatly into the existing framework. If it would be a feature for core, someone probably have to dig into the details.

**Comment by mimugmail** [comment]
It has too many dependencies, on vanilla FreeBSD 12 the pkg needs around 1GB of additional packages. It could be developed as an external or commercial plugin like Sensei with an own repo

**Comment by fabianfrz** [comment]
@AdSchellevis deploying the UI is easy. You just need to place the WAR file into the deployment directory of WildFly. It will register under the context path '/guacamole' so in the frontend there is only a proxy rule needed (note: must support websockets) and no conflict possible. The server is a C application, which means it should be deployed using the standard RC system.
Authentication is done using modules, so this can be integrated easily but still has the problem that is pulls in a lot of dependencies.

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/core/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
