### ISSUE TITLE
Services > DHCPv4 > Leases is omitting interface name in overview table

### ISSUE THREAD

**Issue by Northguy** [opnsense/core#3487]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[YES] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[YES] I have searched the existing issues and I'm convinced that mine is new.

**Describe the bug**
When a Static lease configuration through _Services > DHCPv4 > LAN > DHCP Static Mappings for this interface_ is used to add hostname and description, while fixed IP is not filled in, the interface name for this MAC address is not shown in _Services > DHCPv4 > Leases_ table.

**To Reproduce**
1. Go to 'Services > DHCPv4 > LAN > DHCP Static Mappings for this interface'
2. Add MAC address
3. Add description
4. Add Hostname
5. **do not** add IP
6. Apply
7. Go to 'Services > DHCPv4 > Leases' and observe table

**Expected behavior**
Interface name should be visible

**Screenshots**
![image](https://user-images.githubusercontent.com/1189058/57918091-61a2d680-7896-11e9-9da9-0e440242d66d.png)

**Relevant log files**
N/A

**Additional context**
Follow-up of https://github.com/opnsense/core/issues/2946#issuecomment-493134765

**Environment**
OPNsense 19.1.7-amd64FreeBSD 11.2-RELEASE-p9-HBSDOpenSSL 1.0.2r 26 Feb 2019
opnsense-patch 839ec35 applied

**Comment by AdSchellevis** [comment]
@Northguy can you try https://github.com/opnsense/core/commit/446caa9941ee8c56d22220211aab72dfc77af426 + https://github.com/opnsense/core/commit/fb4a9bedaa599b8b06ae31c91c20eb3269e1b3c0 

```
opnsense-patch 446caa99 fb4a9be
```

**Comment by Northguy** [comment]
@AdSchellevis Looks good for IPv4. Cannot test IPv6 as I don't have IPv6 setup.

**Comment by AdSchellevis** [comment]
@Northguy thanks for confirming, IPv6 is different, if something similar pops-up there, we'll have a look when reported.
