### ISSUE TITLE
haproxy log broken in 19.1.8

### ISSUE THREAD

**Issue by Kimotu** [opnsense/core#3493]
With opnsense update 19.1.8 the haproxy logs are shown broken. Date and Message should be shown separetely/splitted into two columns. Instead, both columns show whole message including date.

how it looks like:
```
Date                                                      | Message
--                                                        | --
May 20 16:16:22 fw02 haproxy[10576]: Proxy Admin started. | 20 16:16:22 fw02 haproxy[10576]: Proxy Admin started.
```
how it should look alike:
```
Date            | Message
--              | --
May 20 16:16:22 | fw02 haproxy[10576]: Proxy Admin started.
```

Till 19.1.7 display was correct,

**Comment by AdSchellevis** [comment]
@Kimotu it looks like we missed some lines, can you try https://github.com/opnsense/core/commit/95b4ae224a3025a419efcd270905e58e9cf3bb51 ?
```
opnsense-patch 95b4ae2
```

**Comment by abplfab** [comment]
Same error with all logs. Patch fixes view.

**Comment by Kimotu** [comment]
Patch worked. :-)

**Comment by fichtner** [comment]
Small review fail in the patch, no functional issue... will mop this up in 19.1.9... sorry for the trouble.
