### ISSUE TITLE
Plain Log file parsing (all logs) not correct

### ISSUE THREAD

**Issue by stefan-kos** [opnsense/core#3494]
Hello dear OPNsense'rs,

since upgrading from 19.1.7 to 19.1.8, all log file parsing is not correct in the cols.
For example in Firewall -> Log files -> Plain view.

The Date and Message part is actually in both cols, Date and Message except Month name. This happens with every log file. I tried to reset all logs and rebooted, but still the same issue.

<img width="1268" alt="Bildschirmfoto 2019-05-21 um 22 10 25" src="https://user-images.githubusercontent.com/50271649/58127624-0c5c2180-7c16-11e9-9636-613f9f502991.png">

Firewall Log Live view is ok.

Thank you so much, cheers, Stefan

**Comment by fichtner** [comment]
Hi Stefan,

See https://github.com/opnsense/core/issues/3493 with patch.


Cheers,
Franco

**Comment by stefan-kos** [comment]
Hi Franco,

thanks for your answer, yes that works. I tried to find but maybe I overseen #3493 while not looked in the closed ones, sorry for this.

Cheers, Stefan

**Comment by fichtner** [comment]
@stefan-kos no worries 👍
