### ISSUE TITLE
master: text coloring for apply message in rules is unreadable

### ISSUE THREAD

**Issue by mimugmail** [opnsense/core#3497]
Current master, when applying a firewall rule it looks like this:

![image](https://user-images.githubusercontent.com/20438689/58179011-999b8680-7ca7-11e9-87af-64e0e5006d8c.png)

Maybe this needs some tuning? :)

**Comment by fichtner** [comment]
Yes.... I made an experiment.... we do not use alert-success anywhere yet

**Comment by mimugmail** [comment]
Ok, you are aware, fine with it :)

**Comment by AdSchellevis** [comment]
I think we better keep info in these cases, contextually there isn't a big difference between success and info here, I do like the warning when an apply is needed by the way 👍

**Comment by fichtner** [comment]
Changed it back to what it was before... but what I'd like to see is to make all of them look better... compare them as they are now:

<img width="1160" alt="Screenshot 2019-05-23 at 8 29 56 AM" src="https://user-images.githubusercontent.com/1915288/58230669-4708ab80-7d35-11e9-8044-7477ad673be1.png">

And here is bootstrap:

<img width="836" alt="Screenshot 2019-05-23 at 8 30 12 AM" src="https://user-images.githubusercontent.com/1915288/58230682-4d972300-7d35-11e9-9dc5-591a50a7198c.png">
