### ISSUE TITLE
19.1.8 System: log widget - text warp for 6 columns ?

### ISSUE THREAD

**Issue by opnsenseuser** [opnsense/core#3498]
if the dashboard consists of 6 columns, then the class "nowrap" is certainly not of advantage when it comes to easy readability. You have to scroll endlessly to the right and then to the left again to read the text completely. but this should not be the case especially on the dashboard. the dashboard should be fast and easy to read. how do you see it ?

no wrap css:
![grafik](https://user-images.githubusercontent.com/34602360/58197230-20625a80-7ccc-11e9-8cc3-d33933857dc9.png)

with wrap:
![wrap](https://user-images.githubusercontent.com/34602360/58197076-c95c8580-7ccb-11e9-9970-8adc648d23cc.jpg)

**Comment by stumbaumr** [comment]
Hi,

/configd_logs.php seems broken as well. The column "Date" is not properly parsed and then long log messages push everything else to the right.

**Comment by AdSchellevis** [comment]
seems like duplicate https://github.com/opnsense/core/issues/3493
