### ISSUE TITLE
OpenVPN: Reintroduce MS Certificate Storage option in client export

### ISSUE THREAD

**Issue by mimugmail** [opnsense/core#3500]
Hi,

since the rewrite of OpenVPN Client Exporter to MVC it seems the the option for MS Certificate Storage is gone (seen screenshot):

![image](https://user-images.githubusercontent.com/20438689/58257721-b69c8c00-7d71-11e9-9824-e38552211272.png)

I'd like this feature back since it offers way more security. The rolled out config is not moveable, so the client can't install the same config on private machines. I tried it manually with removing pkcs12 statement from exported config, adding ca option with ca.crt file (linked CA) and option `cryptoapicert "SUBJ: CN-Name" ` and it works (but isn't fun)

Thx
Michael

**Comment by AdSchellevis** [comment]
@mimugmail can you try https://github.com/opnsense/core/commit/8bb3f1f38c420141d84733a23c3595ec4d0da3bc ?

**Comment by mimugmail** [comment]
Hi @AdSchellevis, looks good, but the pkcs12 is not included in this zip.

**Comment by AdSchellevis** [comment]
@mimugmail wasn't that the point of using the windows cert store?

**Comment by mimugmail** [comment]
My fault, in UI is you can set a password for `P12 Password/confirm` so I thought it'll be included in the zip.
Maybe add a constraint here and then we're good to go. 

Works very nice here. thx :)

**Comment by AdSchellevis** [comment]
@mimugmail I think I'll better hide the option in the ui, it's not stored in the config and not used when send, I'll commit and close, feel free to reopen if it's not what you expected. Thanks for sponsoring the feature.

**Comment by mimugmail** [comment]
Beautiful! Always a pleasure to work with you :) 

@fichtner is it too late for 19.1.9?

**Comment by fichtner** [comment]
@mimugmail no, but I fear that 19.1.9 won't be this week

**Comment by mimugmail** [comment]
That's no big deal for me, I have 3 weeks time, or will just use opnsense-patch :)
