### ISSUE TITLE
move to syslog-ng

### ISSUE THREAD

**Issue by AdSchellevis** [opnsense/core#3505]
One of the long term wishes is to use syslog-ng as our primary logging facility, which would enable us to support some enhanced features such as syslog over tcp (needed for https://github.com/opnsense/core/issues/3401) and support more fine grained filters (https://github.com/opnsense/core/issues/1857).

Since our current syslogd implementation is patched with clog for circular logging, which is very convenient for smaller and ramdisk setups, it would be a rather large change to replace all at once.

The current plan is to route `syslog-ng` messages to `syslogd` for legacy logging, so we can gradually extend features without losing the current setup and offer selectable replacement in the future.

As far as I could find, syslog-ng doesn't seem to support circular logs.

**Comment by mimugmail** [comment]
When it comes to business case, most critical part is that you don't have to log specific stuff over a common time, and you also have to garantuee to keep logs for a given time. Both is impossible with circular logging.

**Comment by evbevz** [comment]
syslog-ng doesn't support circular.

**Comment by AdSchellevis** [comment]
@mimugmail I know, eventually we might want to ditch clog support, but for the sake of progress and compatibility we should try to avoid replacing all at the same time. Earlier efforts to replace syslog kind of missed steps in between, which is what I'm suggesting here.

**Comment by evbevz** [comment]
But it supports 'program' destination. Maybe it will be a replacement for clog?

**Comment by AdSchellevis** [comment]
It's probably less weighty to keep the old syslogd to write circular logs, we might look into 'program' output at some point in time.

**Comment by AdSchellevis** [comment]
https://github.com/opnsense/core/pull/3524
