### ISSUE TITLE
openvpn client: unable to configure split-dns settings

### ISSUE THREAD

**Issue by ssbarnea** [opnsense/core#3506]
OpenVPN clients are able to configure split DNS settings, where VPN DNS is used only for specific domain (list).

I was not able to find any such settings in OpnSense VPN Client configuration and I am worried that it may not even work well its own DNS resolver (Unbound DNS).

Assuming that `example.com` is the corporate domain which we want to resolve using VPN DNS servers, the expected behavior is to use VPN servers for queries made to this domain and its default ones for the others. If the VPN goes down the resolution is supposed to happen using default DNS configuration on the router.

I know that as a workaround I could manually identify which DNS servers are reported by the OpenVPN server and manually configure them inside Unbound DNS. 

Clearly this has few serious issues:

* the entire coporatate domain will become unaccesible when VPN is down (and obviously some of the sites un the same domain are normally  accessible from outside VPN).
* the ability to use optimal DNS server for each VPN endpoint is lost because you would have to hardcode some of them and not be able to use the one returned by the endpoint. Corporate OpenVPN deployments with multiple geographical endpoints will report each different DNS servers to use, the ones closer to the endpoint.

**Comment by fichtner** [comment]
Closing as per https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
