### ISSUE TITLE
Renaming of gateway not working

### ISSUE THREAD

**Issue by truquete** [opnsense/core#3508]
Tested with
OPNsense 19.1.8-amd64
FreeBSD 11.2-RELEASE-p10-HBSD
OpenSSL 1.0.2r 26 Feb 2019

Problem: 
- when renaming a gateway, all firewall rules using that gateway go back to default
- the firewall list will still show the previous (before renaming) gateway under column "gateway", despite the rule not working anymore as expected
- if you are using a VPN as a gateway, you might unexpectedly start leaking data through your WAN

Expected behavior:
I can think of a few options, in order of preference:
1) When renaming a gateway, all firewall rules using that gateway should be updated with to use the new name
2) If renaming is not possible without side effects like current behavior, renaming should be forbidden
3) if a firewall rule goes back to default after renaming gateway, a big fat warning should be given if all rules go back to default. In addition, no incorrect/now non-existent gateway should be listed under column "gateway" in firewall rules. 

Steps to reproduce the problem:
1) Set up some firewall rule to use a specific gateway
2) Go to gateways tab and rename the gateway used in (1)
3) Observe now in the firewall rule in (1) how the previous gateway name is still listed in the column "gateway"
4) Edit the firewall rule in (1) and observe how the field "Gateway" at the bottom has now be reverted to "default"
5) Bonus: fix the problem by selecting the proper gateway in the pull-down menu (4)

**Comment by AdSchellevis** [comment]
The most simple and pragmatic solution would probably be to drop support for renaming gateways. 

Since the components using the gateway (firewall, routing, plugins) have no way of knowing something has changed and the name is the linking pin to the functionality, we likely better validate if already set and warn the user about renaming (some other areas in the system have the same behaviour).

Ideally the name wouldn't have been the key to the functionality, but that's difficult to change at the moment.

**Comment by mimugmail** [comment]
Agree, also had some trouble with it on some test systems

**Comment by truquete** [comment]
I'm not a web programmer, so I have no idea how hard is to prevent renaming when editing a gateway. Excuse my ignorance, but I don't quite understand why is it so hard to do this right. The brute force approach, if I were to do this again, would be to export the configuration, edit the xlm, find/replace name in full (watching out for text within other strings), reimport. I'm not sure why the gui can't do something like this (without intermediate XML, of course) 

The proper way, if I were to code this, would be to assign an ID to each gateway. All references would be based on this ID rather than name, and the name would then be just a property linked to this gateway ID. 

But once again, I'm no developer so I have honestly no idea what's the best way to do this. Import is though that this gets fixed in order to prevent situations where traffic is leaked outside the vpn without warning, as it happened to me.

**Comment by mimugmail** [comment]
Thats why Ad Said:

Ideally the name wouldn't have been the key to the functionality, but that's difficult to change at the moment.

**Comment by AdSchellevis** [comment]
can't reproduce, renaming gateways is already not allowed:

https://github.com/opnsense/core/blob/b16e03cb686c6b2afff232d066a7113b02d2be8a/src/www/system_gateways_edit.php#L173-L181

**Comment by truquete** [comment]
@AdSchellevis could you please share your opnsense version? If the fix is specific to a development version, I'll check it in a VM and if I can confirm the fix I'll close the ticket. I'm using latest mainline as stated in my top post.

**Comment by AdSchellevis** [comment]
that's odd, I've tried both development as 19.1.8 
![image](https://user-images.githubusercontent.com/9783985/58763967-1826dc80-8562-11e9-88d6-02518d0cb0f5.png)

**Comment by truquete** [comment]
thanks everyone for their help with this topic so far. I have tried to reproduce it again, and this time I was not able to rename the gateway by editing it directly. I see two possible scenarios:

1. My system was in some special state of configuration where opnsense allowed me to rename the gateway
2. I did not in fact rename the gateway as I had thought, and I did something else that looked very similar and confused me.

Regarding (1), I am not sure what I could have done differently. I'm no php coder, so I can't tell exactly what the first "if" statement guards. It looks like it checks if it is talking about the same gateway or not. If this turns to false, the second condition wouldn't be be called. Is there any special use-case that could fool that clause?

Regarding (2), I tried experimenting and found a similar but not exactly the same use-case: while renaming _an interface_, the following two scenarios happened to me:

1. The gateway gets renamed, essentially triggering the scenario described in my first post, except there is no manual renaming of the gateway but rather indirectly.
2. Instead of (1), sometimes opnsense copies the gateway using a naming convention of the new name. This makes sense, because in this way your previous firewall rules keep working. The problem is that when this happened, I was then allowed to delete this gateway (trash icon showed up). And this also leads to the scenario I described, where the name of a non-existent gateway is listed as gateway in the firewall rule that was using it. And when you edit the rule, you will see "default" instead.

I couldn't really tell why sometimes (1) happens, or sometimes (2)

But I can see to problems, which maybe should be reported as separate tickets and close this one:
1. sometimes a gateway is renamed upon renaming an interface, although renaming of gateway is prohibited
2. when renaming an interface, sometimes a new gateway is created, but the original gateway can be deleted, although is being used by some firewall rules.

I accept proposals on how to proceed. Should I close this ticket and open a new one? It would be good if someone could give me some insight regarding when a new gateway is created while renaming an interface, so I can explain the use-case better.

**Comment by AdSchellevis** [comment]
There might be some glitch in a specific scenario, but please, pretty please, before opening an issue, make sure there is a step by step scenario where a specific issue occurs.... This type of debugging cost us quite some time, which can't be spent elsewhere. 

Can you close this one?

**Comment by truquete** [comment]
Technically speaking, the ticket is valid because the gateway can be renamed indirectly, causing the aforementioned problems. My mistake was claiming that the gateway renaming could be done in the edit field, when in this case is done indirectly. Sorry about that. I'll close this particular topic and open one for the "renaming of interface".
