### ISSUE TITLE
DHCPv4 default gateway (interface IP) not propagated to dhcpd.conf

### ISSUE THREAD

**Issue by cbrueffer** [opnsense/core#3509]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[x] I have searched the existing issues and I'm convinced that mine is new.

**Describe the bug**

In thr DHCPv4 service the description of the Gateway field reads "The default is to use the IP on this interface of the firewall as the gateway. [...]" This does not work and one must specifically enter the gateway address to make this work.

**To Reproduce**
1. Configure a [LAN] interface with IP address 192.168.1.1
2. Go to Services->DHCPv4->[LAN]
3. Enable the DHCP server
4. Make sure the `Gateway` field is empty, hence the IP address of the LAN interface should be used by default (as per the help entry)
5. Save and apply
6. Open `/var/dhcpd/etc/dhcpd.conf` on the commandline and observe the missing `option routers 192.168.1.1;` line

**Expected behavior**

After following the instructions above an `option routers 192.168.1.1;` entry should be written so DHCP clients receive a default gateway

**Mitigation**

Explicitly setting the Gateway field to 192.168.1.1 causes the correct dhcpd.conf line to be written.

**Environment**
Software version used and hardware type if relevant.
e.g.:

OPNsense 19.1.8-amd64
FreeBSD 11.2-RELEASE-p10-HBSD
OpenSSL 1.0.2r 26 Feb 2019

I first observed the issue with 19.1.1, haven't tested earlier versions.

**Comment by AdSchellevis** [comment]
Can you share screenshots of your interface config, dhcp and configured gateways? Usually this indicates another configuration issue, most likely suspect a missing default (IPv4) gateway.

Same kind of setup on my end works like a charm (its the default factory default if I'm not mistaken).

(related code)

https://github.com/opnsense/core/blob/98abca91a68d7118a9dd75c610a566e7ea38c123/src/etc/inc/services.inc#L503-L510

https://github.com/opnsense/core/blob/98abca91a68d7118a9dd75c610a566e7ea38c123/src/etc/inc/services.inc#L808-L818

**Comment by cbrueffer** [comment]
Thanks for the quick reply! Here's a screenshot of my LAN interface config:

![screenshot-lan-interface-config](https://user-images.githubusercontent.com/2705287/58705414-6d6ebc80-83af-11e9-94ab-f0396b46a7cd.png)

**Comment by AdSchellevis** [comment]
can you share a screenshot of the gateways as well (you can wipe the addresses). It's likely an issue with the gateway selection. 

We have quite some changes stashed for 19.7 related to gateway selection, so it might solve itself, but nothing you can easily test without trying the development version.

**Comment by cbrueffer** [comment]
![screenshot-gateways](https://user-images.githubusercontent.com/2705287/58706396-3f3eac00-83b2-11e9-96d3-0bfa882fbfe8.png)

**Comment by AdSchellevis** [comment]
yep, it's offline, so not considered as valid gateway. if you don't want to monitor the gateway, just disable monitoring ("Disable Gateway Monitoring")

**Comment by cbrueffer** [comment]
That seems to have fixed my DHCP issue, thanks! A bit non-intuitive :-)

**Comment by AdSchellevis** [comment]
you're welcome. Removing it now might break other configurations, but I agree it's not the nicest construction in the world :) The easiest fix is probably to improve the help text, so it reflects the actual behaviour.  

If you have suggestions or would like to create a PR for a better text, that would be highly appreciated.

**Comment by cbrueffer** [comment]
Maybe adding a subclause to the text would be helpful, e.g. `The default is to use the IP on this interface of the firewall as the gateway, if a valid (online) gateway has been configured under System->Gateways`. That at least would have steered me in the right direction.

**Comment by AdSchellevis** [comment]
let's do that, I'm pretty sure I've answered a similar question before, better tell people where to look in the first place :)

**Comment by AdSchellevis** [comment]
@cbrueffer this https://github.com/opnsense/core/commit/a79bb94cb7580b80a642da2b6154e56f41c94add should help.
