### ISSUE TITLE
Backup page does not download configuration if French language is selected

### ISSUE THREAD

**Issue by gitdevmod** [opnsense/core#351]
I'm trying fr_FR.mo translation file (uploaded to /usr/local/share/locale/fr_FR/LC_MESSAGES/OPNsense.mo) 
in file /usr/local/www/system_general.php in get_locale_list() added:
$locales['fr_FR'] = gettext('French');
then restarted webconfigurator and selected French in Settings.

If I try to download ALL configuration Backup it only refresh the page, with Dutch it works

**Comment by fichtner** [comment]
Fixed since. :)
