### ISSUE TITLE
flowd_aggregate.py too slow

### ISSUE THREAD

**Issue by andreas-p** [opnsense/core#3510]
I've been observing flowd_aggregate.py not rotating the flowd.log. It appears that at higher firewall loads the aggregate_flowd() procedure is too slow too keep up with flowd.log increase rate, so the check_rotate() proc isn't called any more.

I added some logging code to flowd_aggregate.py to track how long the aggregate section will run. These numbers were taken after /var/log/flowd* and /var/netflow/* where purged.

With low load (non-business hours), I see about 1.5k/s packets, 10k pfstates, 330 known IPs. The aggregator takes some 15 seconds, which means that it is loaded at about 50% capacity (since it will take a 15s nap after the run).
When load increases in the morning, at 9:00 there are some 3-4k/s packets, 16k pfstates, 440 IPs and the aggregator will take >45s. With a little more load, the aggregator will run indefinitely, so there's no logrotation any more. Two hours later, the firewall processes some 5k packets/s, 23k pfstates, 620 IPs, with a CPU load of 1.3 (1 caused by flowd_aggregate.py), 15% CPU (8-core, so just a few % for traffic handling). The disk is a server-grade SATA-DOM SSD, no bottleneck here I guess. In total, the hardware seems generously sized for the traffic handled.

System is C3758 8-Core, GB RAM (1.5G in use), 16GB Supermicro SATA DOM SSD, with latest 19.1.8 running.

**Comment by AdSchellevis** [comment]
new version in master is about 30% faster, but the C3758 itself isn't a very fast system (single core performance is what matters here). flow aggregation is a pretty consuming process.

**Comment by evbevz** [comment]
https://github.com/opnsense/core/pull/1752

**Comment by AdSchellevis** [comment]
@evbevz would you be so kind to stop spamming? as explained in the issue, reading the file isn't the issue, or can you show profiler output supporting your claim?

**Comment by andreas-p** [comment]
I'm not sure that even that 30% increase and some additional boost from a faster CPU (which isn't feasable for may anyway) would be sufficient. At least, a little more load would drive the aggregator into saturation again.
In addition, I'd suggest to skip the 15s nap if the aggregator already took more than 10s or so.

**Comment by evbevz** [comment]
No problem, Ad. I just wanted to give a solution for andreas.

**Comment by fichtner** [comment]
Please be advised that suggestions can't be shipped or tested. We cannot possibly stretch out the open source project to fulfil the needs for every user. The need to administrate systems doesn't end when the operating system boots so there's always room for improvement in deployments.

If this should be improved in software please provide clear, simple and small pull requests and adhere to code review discussion. So far we don't have that so what we have is what we will stick to.

**Comment by andreas-p** [comment]
@AdSchellevis the improvement from master will be in 19.1.9? Do you think there's more room for improvement, maybe some different aggregator approach?

@fichtner currently, using the standard opnSense feature "Netflow - Capture Local" may bring the firewall down to its knees in a non-obvious way (by filling the disk to >100% when only 100MB of data is expected), so this issue isn't a single user one.

**Comment by fichtner** [comment]
@andreas-p if you feel the need to improve it I'd be very happy about it. from a triaging perspective you're inferring your issue is a global one, but in practice you're overestimating the impact and therefore come off as more demanding than appropriate. this is as much your open source project as it is mine or everyone else's

**Comment by AdSchellevis** [comment]
@andreas-p it will be in 19.7, I've run quite extensive profiles on the current code, in some situations it might even be better (due to a commit issue). A very different approach isn't feasible at the moment (we aggregate data live, needing only a limited code footprint, no heavy dependencies such as elastic search)

**Comment by andreas-p** [comment]
@AdSchellevis 
Oh dear, I certainly didn't want to suggest a monster like elastic search on the firewall... This would be obviously a topic for an external collector and aggregator. The local can't be a complete solution and will always have its limits.
For some months, I had no problems (watching historic diskspace, probably the logfile was filled during the day, and aggregated/rotated at night), and something (small traffic increase/minor software change/or so) kicked it over the edge, which I didn't expect. Maybe the aggregator could notice somehow that it won't be able to cope with flowd data in a reasonable time, and shutdown gracefully instead of trying indefinitely (needing a kill -9 to stop)? Or drop flows in a predictable way?

**Comment by fichtner** [comment]
The Python 3 rewrite is in now for 19.7. It's faster, but it won't be fast enough on hardware not capable to let it run fast enough. It was lucky we had to redo the code due to the Python 3 migration, but other than that there are no more plans to speed up this code from the core team side.
