### ISSUE TITLE
dpinger does not respect virtual IPs in different subnets

### ISSUE THREAD

**Issue by WRMSRwasTaken** [opnsense/core#3512]
Hello,

we have 2 different WAN routers in front of our Firewall with a /30 transfer subnet for BGP each. Both routers and the firewall share the same Layer 2 connection on a switch, the firewall is configured on a LAG of two ports on the firewall itself connected to the same switch. All ports are in the same VLAN.

One transfer subnet is `10.10.10.76/30` where the router's IP is `10.10.10.77` and our IP is `10.10.10.78`. For the other router the transfer subnet is `10.10.10.72/30` where the other side is `10.10.10.73` and we are `10.10.10.74`.

For security reasons, the real IPs have been swapped out with RFC1918 ones.
To get this setup working, we set a static IPv4 `10.10.10.78/30` on the LAG and set a virtual IP `10.10.10.74/30` on the LAG too.

frr is able to establish a BGP session with both routers, which basically means that the L2 and L3 configuration is working. Now the following problem:

As we're only exporting prefixes to those two BGP neighbors without importing any, we wanted to use the gateway featrues of OPNsense itself. 
We created a new gateway entry for each router (`10.10.10.77` and `10.10.10.73`) which resulted in `10.10.10.77` being marked as UP and `10.10.10.73` being marked as DOWN.

Pinging the gateways itself from CLI shows that both respond to ICMP echo requests. Investigating on CLI with tcpdump reveals the following:
```
10:35:05.493041 IP 10.10.10.78 > 10.10.10.73: ICMP echo request, id 11556, seq 7641, length 8
```
where you can see, that the firewall tries to ping the gateway in the subnet of the virtual IP with the "real" IP set on the LAG which obviously does not work which is why the gateway is marked as DOWN.

Further investigating revealed, that the dpinger process itself is being started with the following parameters:
```
root           11556   0.0  0.0    8956   2400  -  Is   15:01        0:11.07 /usr/local/bin/dpinger -f -S -r 0 -i <name1> -B 10.10.10.78 -p [...]
root           86313   0.0  0.0    6908   2356  -  Is   15:01        0:10.79 /usr/local/bin/dpinger -f -S -r 0 -i <name2> -B 10.10.10.78 -p [...]
```
Looking into dpinger help: `-B bind (source) address` is set to a wrong address here on one of the processes which is why it tries to ping the gateway from the wrong source address / subnet.

The workaround at the moment is forcing the marked down gateway as always up in the gateway settings and creating a gateway group with both gateways and setting the forced-online gateway to a lower tier than the gateway where the ICMP monitoring works. This basically creates a active-standby configuration where it only uses the gateway with non-working monitoring only if the first one with working ICMP monitoring is marked as down.

The question is: Is this intended behavior, a bug or is this a case that has never been considered before? Would it be possible to add a dropdown to the gateway creation mask to set that bind IP?

Our version is `OPNsense 19.1.4 (amd64/OpenSSL)` on `Intel(R) Xeon(R) CPU D-1518 @ 2.20GHz` with two `Intel x520` NICs.

Thanks.

**Comment by fichtner** [comment]
It looks like a feature request. Traditionally, you wouldn't select "WAN" or "OPTX" but it would also list the VIPs there. That's a slippery slope so simply adding the options will not achieve much and I expect this to go into improving gateway monitoring code to deal with VIPs, which will also likely increase complexity of the code to avoid a whole new class of gateway monitoring mismatch bugs.

I'll tag this as "help wanted" so that someone willing to work on it can pick it up.

**Comment by mimugmail** [comment]
@WRMSRwasTaken you create 2 /30 networks on the same L2 domain (VLAN)? You should really fix this, or just use one network for all three. Also you should consider default-originate on both upstream peers, would make the network design more consistent. BGP can handle this easily ...

**Comment by WRMSRwasTaken** [comment]
@mimugmail Unfortunately, a subnet for all three devices is not possible as the upstream ISP only assings separate transfer subnets for each router. I've already asked for VRRP or HSRP (w.e.) on their side but they don't do this for this type of connection / contract we're using.

I am currently thinking of deleting the LAG itself and assign a /30 to each of those two interfaces.

There is a detail I did not mention earlier: We're actually using two switches, with the firewall's LAG being connected to both switches and the two ISP routers being connected to one switch each.
When one Switch fails, the dpinger will register one router as down and the ISP router on that switch is going to have a timed out BGP session which results in the prefixes not being routed to this router anymore (we're not using BFD so this takes a while).

We're not currently importing the default route via BGP (although the ISP has default-originate set) because we're using a Gateway on a different line currently. This is going to change in a later time.

**Comment by mimugmail** [comment]
> @mimugmail Unfortunately, a subnet for all three devices is not possible as the upstream ISP only assings separate transfer subnets for each router. I've already asked for VRRP or HSRP (w.e.) on their side but they don't do this for this type of connection / contract we're using.

So you have too few interfaces on your Firewall, correct?

> I am currently thinking of deleting the LAG itself and assign a /30 to each of those two interfaces in different VLANs.

Do you run HA or single unit?

> There is a detail I did not mention earlier: We're actually using two switches, with the firewall's LAG being connected to both switches and the two ISP routers being connected to one switch each.
> When one Switch fails, the dpinger will register one router as down and the ISP router on that switch is going to have a timed out BGP session which results in the prefixes not being routed to this router anymore (we're not using BFD so this takes a while).
> 
> So I think that might work.

Trust me, BGP failover is not the fastest, but the most stable. If your lines are such flaky that you insist on dpinger there's really something wrong with your ISP.

> We're not currently importing the default route via BGP (although the ISP has default-originate set) because we're using a Gateway on a different line currently. This is going to change in a later time.

**Comment by WRMSRwasTaken** [comment]
> So you have too few interfaces on your Firewall, correct?
Yes, unfortunately. But the ISP also gave us only one Port per Router on their side. We plan on adding a 2nd node for HA later which we're going to need a shared L2 anyway for CARP to work on our side.

> Do you run HA or single unit?
It's a single node for now, but as I already mentioned, we plan to add a 2nd node later on. But thinking about it, this seems to work to create a CARP /30 IP for each router subnet and run two BGP sessions from the active node to both routers instead of just running 1 BGP session per firewall because both firewall nodes are connected to both switches.

**Comment by mimugmail** [comment]
I don't get it, you create on a switch e.g. Vlan30, plug provider1 in and a second port with Vlan30 and plug OPNsense in it. Same for second ISP line with Vlan31. Isn't this what you want? It would also fit in HA examples since you just create for both Vlans new ports.

**Comment by WRMSRwasTaken** [comment]
> I don't get it, you create on a switch e.g. Vlan30, plug provider1 in and a second port with Vlan30 and plug OPNsense in it. Same for second ISP line with Vlan31. Isn't this what you want? It would also fit in HA examples since you just create for both Vlans new ports.

You got it. This is exactly going to be my approach right now.

**Comment by WRMSRwasTaken** [comment]
So because I don't need multiple IPs per Interface anymore this issue is not going to be relevant for me anymore.
