### ISSUE TITLE
Enabling a rule in Suricata changes the action

### ISSUE THREAD

**Issue by Flightkick** [opnsense/core#3513]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[X] I have searched the existing issues and I'm convinced that mine is new.

**Describe the bug**
When enabling a rule in Suricata, the action changes from Drop to Alert.

**To Reproduce**
1. Go to `/ui/ids#rules`
2. Click on the checkbox to enable a disabled rule which has it's current action set to Drop
3. Wait for the rule to be enabled
4. The rule should now be enabled **but the action also changed to Alert**

**Expected behavior**
I do not expect the Action (Drop / Alert) to change when a rule gets enabled.

**Screenshots**
![before](https://user-images.githubusercontent.com/8693699/58869637-e7a88500-86be-11e9-9a82-299cfd98a391.png)
![during-enabling](https://user-images.githubusercontent.com/8693699/58869656-f4c57400-86be-11e9-8e1a-42847a692322.png)
![after](https://user-images.githubusercontent.com/8693699/58869695-073fad80-86bf-11e9-8be7-ff696091156f.png)

**Relevant log files**
N/A

**Additional context**
I'm also missing the ability to bulk change the Action of rules. It is currently possible to enable / disable rules in bulk but it's not possible to change the actions. I'm creating a seperate feature request for that (https://github.com/opnsense/core/issues/3514).

**Environment**
Software version used and hardware type if relevant.
e.g.:

OPNsense 19.1.8-amd64

**Comment by AdSchellevis** [comment]
@Flightkick thanks for the report, https://github.com/opnsense/core/commit/3af744e03dd8191fa239b2a91823657f1c87e735 should fix the issue.

On a console, use the following to apply the patch:
```
opnsense-patch 3af744e
```

**Comment by Flightkick** [comment]
@AdSchellevis sorry for my late reply, thank you for the fixes to both this issue and changing rules in bulk (https://github.com/opnsense/core/issues/3514)

**Comment by mimugmail** [comment]
Just tested it with latest master, really nice work Ad, love it :)

**Comment by fichtner** [comment]
It’ll be in 19.1.10 😊
