### ISSUE TITLE
Allow changing Suricata rule actions in bulk

### ISSUE THREAD

**Issue by Flightkick** [opnsense/core#3514]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[X] I have searched the existing issues and I'm convinced that mine is new.

**Is your feature request related to a problem? Please describe.**
It is possible to select multiple rules and enable / disable them in bulk. But it is not possible to bulk change their actions. E.g. if I would like to test rules first by setting their actions to Alert and after a while convert them to Drop. I would have to do so manually for each rule, which is a lot of tedious work.

**Describe the solution you'd like**
I would like to be able to select multiple rules and change their action in bulk.
![example](https://user-images.githubusercontent.com/8693699/58871024-90f07a80-86c1-11e9-9d27-fb420bf04331.png)

**Describe alternatives you've considered**
None of which I deem feasible.

**Additional context**
This feature would also have helped with the bug report I wrote earlier (https://github.com/opnsense/core/issues/3513)

OPNsense 19.1.8-amd64

**Comment by AdSchellevis** [comment]
can't promise anything yet, but it certainly something worth to look into.
