### ISSUE TITLE
CARP disable preempt doesn't work

### ISSUE THREAD

**Issue by andreas-p** [opnsense/core#3515]
I have System/Settings/HA/Disable Preempt checked on 19.1.8. When rebooting the master, the second system will happily switch to master. When the first machine comes up again, I would expect it to remain backup, instead it reclaims master again.

excerpts from system.log:
13:55:01 fw kernel: ix4: link state changed to UP
13:55:03 fw kernel: lagg0: link state changed to UP
13:55:04 fw kernel: carp: 100@ix4: BACKUP -> MASTER (preempting a slower master)
13:55:06 fw kernel: carp: 171@lagg0: BACKUP -> MASTER (master timed out)

Isn't the "Disable Prempt" setting meant to prevent "preempting a slower master"? The "master timed out" might be switch related, investigating that separately.

**Comment by mimugmail** [comment]
Can you check the value of `net.inet.carp.preempt` on both units after reboot?

**Comment by andreas-p** [comment]
net.inet.carp.preempt is 1 on both units. According to the docs https://www.freebsd.org/cgi/man.cgi?query=carp&sektion=4 , this appears wrong to me.

**Comment by andreas-p** [comment]
Oh my, your question triggered something... There was net.inet.carp.preempt=1 configured in the Tunables section, no wonder the checkbox is overridden.
The comment on that entry was "fail all interfaces simultaneously", but this appears wrong.
Closing, sorry for the noise.
