### ISSUE TITLE
Block all IPv6 - Disable logging

### ISSUE THREAD

**Issue by imidoriya** [opnsense/core#3517]
There is no option to disable the logging on the "Block all IPv6" rule.  Can you add an option to on that rule to turn off logging?  It's at the top of the floating and it doesn't seem I can put a rule above it to do the same thing without logging.

**Comment by fichtner** [comment]
From my understanding IPv6 block logging is hardwired to logging option for default blocking (on or off globally).

**Comment by imidoriya** [comment]
It's not the "Default deny rule" if that's what you're suggesting.  
The option is under "Firewall: Settings: Advanced" and unchecking "Allow IPv6".  This creates a floating rule that blocks all IPv6 traffic, however, there is no option to not log it. It's filling up my firewall logs and it's not anything I care to see.  Since you're specifically disabling it, you would almost think to set logging off by default.

**Comment by fichtner** [comment]
I'm not here to argue, just to help. I'll reiterate more explicitly: when you go to System: Settings: Logging you can disable default block logging.

**Comment by imidoriya** [comment]
Sorry, not arguing.  Just trying to understand and explain.  Yeah, I don't want to disable all block logging.  If IPv4 traffic is blocked, I want to see that.  Since it creates it's own rule, it would be nice to have the option to turn it off.

I could turn it back on and then create my own rule - I've done that before, but it would be nice to have that option in there.

**Comment by fichtner** [comment]
Understood. I'm assigning this to the community pool for a contributor to grab and implement.

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/core/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.

**Comment by bajtekv** [comment]
1) Interfaces -> WAN -> IPv6 configuration: **None**
2) Interfaces -> Settings -> **Allow IPv6: [checked]** _(if this is unchecked, it will create automatic logging rules)_
3) System -> gateways -> choose **Edit**(pencil) under Gateway of _Address family IPv6_ : **Disabled [checked]** _(status will turn to grey plug and Priority to defunct)_
4) try to see the packets: **_root@opn# tcpdump ip6_**

Now you shouldn't see any IPv6 logs.
