### ISSUE TITLE
Log files in web gui shows log message in Date column

### ISSUE THREAD

**Issue by marr1977** [opnsense/core#3518]
**Describe the bug**
When looking at any log file in the web gui, the Date column contains the date and time plus the log message. The Message column contains part of the date plus the log message.

**Expected behavior**
The Date column should only contain the date. The Message column should only contain the log message.

**Screenshots**
![Screenshot_20190605_220555](https://user-images.githubusercontent.com/9639840/58986869-98597600-87de-11e9-9be0-9077945138cf.png)

**Relevant log files**

**Additional context**

**Environment**
OPNsense 19.1.8-amd64
FreeBSD 11.2-RELEASE-p10-HBSD
OpenSSL 1.0.2r 26 Feb 2019

**Comment by fichtner** [comment]
Fixed tomorrow in 19.1.9, see https://github.com/opnsense/core/issues/3493#issuecomment-494119420

**Comment by marr1977** [comment]
Ok, thanks, sorry for the duplicate!

**Comment by fichtner** [comment]
No worries. 😊
