### ISSUE TITLE
/usr/sbin/pw 'groupmod' [...] returned exit code '67'

### ISSUE THREAD

**Issue by zaggash** [opnsense/core#3519]
**Describe the bug**
Sometime, I have this message in the 'General' 'System' logs: 
`/system_usermanager.php: The command '/usr/sbin/pw 'groupmod' 'IPSEC' -g '2001' -M '2001'' returned exit code '67', the output was 'pw: user `2001' does not exist'`

it could also come like this:
` /usr/local/etc/rc.configure_firmware: The command '/usr/sbin/pw groupdel '2001'' returned exit code '65', the output was 'pw: unknown group `2001''`

I had the same log messages with UID GID 2000 before.
I  tried to remove the group and user and recreated it.
But it doesn't fix the issue.

**Additional context**
I created an VPN IPsec (VPN: IPsec: Mobile Clients ) and created a user into a group to get access to the VPN.
The VPN is working, but the previous log lines are printed time to time.

To force the log to be printed, I go to System: Firmware: Setting and press 'Save'
This force the following line in the logs:
` /usr/local/etc/rc.configure_firmware: The command '/usr/sbin/pw groupdel '2001'' returned exit code '65', the output was 'pw: unknown group `2001''`

**Environment**
OPNsense 
19.1.8-amd64FreeBSD 11.2-RELEASE-p10-HBSD
OpenSSL 1.0.2r 26 Feb 2019
Intel(R) Core(TM) i7-5550U CPU @ 2.00GHz (4 cores)

**Comment by AdSchellevis** [comment]
@zaggash nice catch, thanks. it seems we missed a `-g` in `pw groupdel` as we tried to delete on gid.

https://github.com/opnsense/core/blob/ca5140cbf7b8c232f0c5e70f8d0610722f3563eb/src/etc/inc/auth.inc#L413

I'll add and close the issue with the commit

**Comment by AdSchellevis** [comment]
groupmod might be an issue after boot after shutdown issues, the parameters for groupmod are correct.

**Comment by fichtner** [comment]
Wow, this bug is easily 10 years old...
