### ISSUE TITLE
Wrong dhcpd.conf entries generated for ddns net entries

### ISSUE THREAD

**Issue by rmx-it** [opnsense/core#352]
Hi,
I've two configured two local networks where ddns updates shall occure:
10.0.0.0/24 (LAN) and 10.0.3.0/24 (WLAN)

Opnsense generates a wrong zone for the 10.0.0.0/24 net inside ddhcpd.conf:
...
zone rm-i.net. {
        primary 127.0.0.1;
        key xkey;
}
zone 10.in-addr.arpa {
        primary 127.0.0.1;
        key xkey;
}
zone 3.0.10.in-addr.arpa {
        primary 127.0.0.1;
        key xkey.;
}
...

zone 10.in-addr.arpa should be zone 0.0.10.in-addr.arpa !

Thanks,
Michael

**Comment by AdSchellevis** [comment]
Apparently it's looking at the address in stead of the mask. 
This should be fixed with https://github.com/opnsense/core/commit/70f89cfc2767efc88e4ec836c344d898d726ceae

**Comment by fichtner** [comment]
I'd like to get confirmation from @rmx-it on that before this goes into the stable/15.7 branch.

**Comment by rmx-it** [comment]
Hi,
jup. Now produces: zone 0.0.10.in-addr.arpa

Thanks!

**Comment by fichtner** [comment]
Ok, applied to stable and closed. :)
