### ISSUE TITLE
dpinger states gateway always as online

### ISSUE THREAD

**Issue by SvenBunge** [opnsense/core#3520]
**Description of the bug**
dpinger states a line always as up if the monitoring IP is reachable - regardless of the gateway itself: dpinger is pinging the given IP address but not through the given gateway. So a gateway like a dumb dsl router with the attached line is still stated a online even the line is down - or even better: the whole dsl router is down.

Due this issue line switching and loadbalancing is not working as expected.

**To Reproduce**
1. Go to the gateway page - https://<opnsense IP>/system_gateways.php
2. Add a new gateway, use IP in your network, select a pingable IP in the internet for monitoring
3. Ensure the default gateway of the firewall is up
4. Save configuration and apply it.
5. the new gateway comes up and is still online - but the gateway doesn't exist on the network.

* Add an unpingable address to it the gateway entry the gateway is stated as down.

**Expected behavior**
When the internet IP is not available **over the given gateway**, the gateway must stated as down.

**Screenshots**
Follow the steps to reproduce and it is shown like this:
![dpinger3](https://user-images.githubusercontent.com/2501349/59065034-133c9280-88ac-11e9-940c-56e711fcc2fa.png)
Here is the entry:
![dpinger4](https://user-images.githubusercontent.com/2501349/59065146-56970100-88ac-11e9-997f-67cb97d65117.png)

Here is the configuration of multi wan and connections:
![dpinger5](https://user-images.githubusercontent.com/2501349/59065368-d3c27600-88ac-11e9-9fe4-9b3791ca2df5.png)

**Relevant log files**
After applying the configuration the gateway log:
Jun 6 22:45:11 fw1 dpinger: send_interval 1000ms loss_interval 2000ms time_period 60000ms report_interval 0ms data_len 0 alert_interval 1000ms latency_alarm 500ms loss_alarm 20% dest_addr 78.47.166.55 bind_addr 192.168.XXX.247 identifier "NEW " | 6 22:45:11 fw1 dpinger: send_interval 1000ms loss_interval 2000ms time_period 60000ms report_interval 0ms data_len 0 alert_interval 1000ms latency_alarm 500ms loss_alarm 20% dest_addr 78.47.166.55 bind_addr 192.168.XXX.247 identifier "NEW "

(.247 is the firewall IP on the WAN-Connection Network to the DSL router)

-- | --

**Additional context**

**Environment**
AMD G-T40E Processor (2 cores), 4GB RAM, SD-Card Drive
OPNsense 19.1.8-amd64
FreeBSD 11.2-RELEASE-p10-HBSD
OpenSSL 1.0.2r 26 Feb 2019

The Firewall is connected via 1GBit VLAN to a switch. The Switch is VLAN capable and the WAN network with all lines and also the internal LAN networks are connected. The switch is using different VLANs to separate the networks.

**Comment by mimugmail** [comment]
Can you post a Screenshot of your routing table? Is Interface : WAN : upstream gateway set to autodetect?

**Comment by SvenBunge** [comment]
If readded the gateway like described above and checked the routing table. There is no entry.
Also the RTT and RTTd of the entry is 0.0ms on https://<opnsense-ip>/system_gateways.php

Without obfuscation my routing table looks like: 
<img width="1273" alt="dpinger6" src="https://user-images.githubusercontent.com/2501349/59127337-aedf0900-8967-11e9-92e6-8413c8da8a47.png">

Regarding the interface configuration: When I put the upstream gateway to *auto*, the firewall is stopping the routing to all of the gateways. So I've selected one gateway out of the list of the network available gateways (working DSL line). 
But for your analyses I've selected *auto-detect* for the option *IPv4 Upstream Gateway*, applied the settings and after one minute the routing stopped again. I've checked the routing table and the firewall has selected the dead-gateway as the default one.
(The gateway is currently NOT part of any gateway group and it hasn't a DNS resolver directly assigned).
<img width="1164" alt="dpinger7" src="https://user-images.githubusercontent.com/2501349/59128129-73453e80-8969-11e9-8e32-b6af8e6b671e.png">

The gateway is still stated as online!!
<img width="558" alt="dpinger8" src="https://user-images.githubusercontent.com/2501349/59128144-7b9d7980-8969-11e9-84c2-8e551863c0fa.png">

Does this help? Could you reproduce this on your installation?
Maybe the issue comes only in conjunction with multiple gateway over one single interface / subnet?

**Comment by SvenBunge** [comment]
Are you able to reproduce my issue / scenario?

**Comment by fichtner** [comment]
Are there any comparable results on 19.7.4?
