### ISSUE TITLE
Insight "No Data Available" after Upgrade

### ISSUE THREAD

**Issue by berlinbikerx** [opnsense/core#3523]
After executing updates to recent versions of OPNsense, insight does not work anymore. Instead of the graphs, it only shows "No Data Available".

This happened after the upgrade to 19.1.8 as well as today after upgrade to 19.1.9.

The only way to get the graphin back is by resetting the netflow data; doing a repair only does not help.

Software version:
OPNsense 19.7.b_92-amd64
FreeBSD 11.2-RELEASE-p10-HBSD
OpenSSL 1.0.2s 28 May 2019

**Comment by AdSchellevis** [comment]
can you check the logs in `System -> Logfiles -> Backend` ? If something crashed, I expect there will be some details in there.

**Comment by berlinbikerx** [comment]
Sorry, I accidentally cleared the log file :-( (it does not have a confirmation dialog)

I will check again during the next upgrade and come back with the results.

**Comment by fichtner** [comment]
Closing as per https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
