### ISSUE TITLE
Show SID in IDS Alerts tab

### ISSUE THREAD

**Issue by lattera** [opnsense/core#3527]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[-] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[-] I have searched the existing issues and I'm convinced that mine is new.

**Is your feature request related to a problem? Please describe.**
I would like to be able to see the SID in the alerts grid so that I don't have to click the Edit button to find crucial info.

**Describe the solution you'd like**
A column in between Timestamp and Action (of the `Services::Intrusion Detection::Alerts` page) that shows the SID of the alert.

**Describe alternatives you've considered**
I guess the new column could go anywhere, but between Timestamp and Action seems most intuitive for me.

**Additional context**
Pretty straightforward.

**Comment by AdSchellevis** [comment]
@lattera that is indeed practical, here you go https://github.com/opnsense/core/commit/f32816d53a26dd37046d8ab025b46676711d35bf
