### ISSUE TITLE
syntax error in DNS forwarder when adding override host 15.7_628_AMD64

### ISSUE THREAD

**Issue by doublej74** [opnsense/core#353]
When trying to add a host to the override section under DNS Forwarder, the 15.7_628_AMD64 version pops a syntax error:

Parse error: syntax error, unexpected ')' in /usr/local/www/services_dnsmasq_edit.php on line 250

**Comment by AdSchellevis** [comment]
are you using the latest version? 
This commit https://github.com/opnsense/core/commit/f9b697e29477d2efdbf815723b875ce3580d7876 seems to contain the fix.

**Comment by fichtner** [comment]
628 is quite old, we're now at 824 :)

**Comment by doublej74** [comment]
confirm in the latest version it's fixed
