### ISSUE TITLE
Firewall - Alias - bad format

### ISSUE THREAD

**Issue by KevDBG** [opnsense/core#3532]
**Describe the bug**
In version 19.1.9-amd64 is not possible to add alias with specific format. Maybe the regex control is not good.

**To Reproduce**
1. Go to Firewall > Aliases
2. Click on '+' to add a new
3. Select a type "hosts", in content put "ecr.eu-west-2.amazonaws.com" or "prod-eu-west-2-starport-layer-bucket.s3.eu-west-2.amazonaws.com"
4. The error is :

> Entry " prod-eu-west-2-starport-layer-bucket.s3.eu-west-2.amazonaws.com" is not a valid hostname or IP address.

**Expected behavior**

In version OPNsense 18.1.9-amd64 it's works. The alias is created successfully.

--

**Screenshots**
![image (4)](https://user-images.githubusercontent.com/6896709/59357229-be28d280-8d2a-11e9-8b78-b30a5ffa4dad.png)

**Relevant log files**
NA

**Additional context**
NA

**Environment**
 version 19.1.9-amd64

Thanks for your help,

**Comment by AdSchellevis** [comment]
it looks like you have a space before the url.

**Comment by KevDBG** [comment]
My bad @AdSchellevis  !! You are right !! 

Sorry for the noise.

**Comment by AdSchellevis** [comment]
@KevDBG things happen :)
