### ISSUE TITLE
Interfaces -> Overview: confusing counters

### ISSUE THREAD

**Issue by soder10** [opnsense/core#3533]
When I check Interfaces -> Overview -> expand one of the interfaces, I see the following counters:

a) In/out packets                               62078526 / 77008330 (26.76 GB / 56.86 GB )
b) In/out packets (pass)                     61229829 / 77008330 (26.74 GB / 56.86 GB )
c) In/out packets (block)                    23686613 / 0                (829 KB / 0 bytes )

This type of text is very misleading, or at least difficult to process by the human brain:
a) is clear sort of, but the title should clearly say this is the counter for TOTAL, for example:
 --> In/out packets total

Then comes the b) and c) that are somewhat more confusing:
you get the (pass) and (block) words in the counter names in parenthesis, and you get values: first, you see value represented as number of packets: first value for inbound direction, then second value for outbound direction. Then a second pair of values (in parenthesis) represent bytes of traffic, again first value for inbound direction , then second value for outbound direction.

Simply, the second value in parenthesis could be misinterpreted with the value description of the beginning of the counter.

b) and c) could be renamed to remove this confusion:

New names could be:
b) In/out packets PASSED                     61229829 / 77008330 (26.74 GB / 56.86 GB )
c) In/out packets BLOCKED                  23686613 / 0                (829 KB / 0 bytes )

So no parenthesis for the counter NAME, not to confuse with the byte counter VALUE in parenthesis.

Reading this whole report may sound more complicated than understanding what I really wanted to say.

**Comment by soder10** [comment]
Or another type of approach could be, to separate packet counters and bytetraffic counters:

In/out packets PASSED 61229829 / 77008330
In/out bytes PASSED 26.74 GB / 56.86 GB
In/out packets BLOCKED 23686613 / 0
In/out bytes BLOCKED 829 KB / 0 bytes

**Comment by soder10** [comment]
Nobody finds this confusing, or just nobody cares?

**Comment by AdSchellevis** [comment]
@soder10 you can create a pull request if you have better ideas, personally I don't think there's something to fix at the moment, but there's always room for improvement.

**Comment by fichtner** [comment]
Closing as per https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
