### ISSUE TITLE
OpenVPN: WebUI does not always include DHCP DNS push options in config files

### ISSUE THREAD

**Issue by MarinBernard** [opnsense/core#3534]
**Describe the bug**
We use OPNsense as an OpenVPN server on 3 distinct sites, all with an identical configuration (the only differences are IP subnets). On all three sites, the OpenVPN instance also runs a DNS redirector to serve DNS requests from remote OpenVPN clients. We thus need to push the IP address of the OpenVPN instance as a DNS server to our clients. We use the dedicated section in the config form to do that. On one server, it works fine. On the two others, the DNS servers are never pushed to the clients because the "push" directives are missing from the resulting server config files.

**To Reproduce**
1. Create a new OpenVPN server connection
2. Fill the form with data shown in the screenshot section.
3. Check the generated config file:
````
root@ade-vsrv-rtr-04:/var/etc/openvpn # cat server1.conf
dev ovpns1
verb 5
dev-type tun
dev-node /dev/tun1
writepid /var/run/openvpn_server1.pid
script-security 3
daemon
keepalive 10 60
ping-timer-rem
persist-tun
persist-key
proto udp4
cipher AES-256-CBC
auth SHA512
up /usr/local/etc/inc/plugins.inc.d/openvpn/ovpn-linkup
down /usr/local/etc/inc/plugins.inc.d/openvpn/ovpn-linkdown
local 109.3.215.99
client-connect "/usr/local/etc/inc/plugins.inc.d/openvpn/ovpn_setup_cso.php server1"
tls-server
server 10.6.9.0 255.255.255.0
client-config-dir /var/etc/openvpn-csc/1
ifconfig 10.6.9.1 10.6.9.2
tls-verify "/usr/local/etc/inc/plugins.inc.d/openvpn/ovpn_auth_verify tls 'ade-vsrv-rtr-04.dmz.ade.intranet.pep06.fr' 2"
lport 1194
management /var/etc/openvpn/server1.sock unix
max-clients 8
push "route 10.6.0.0 255.255.0.0"
ca /var/etc/openvpn/server1.ca 
cert /var/etc/openvpn/server1.cert 
key /var/etc/openvpn/server1.key 
dh /usr/local/etc/dh-parameters.2048.sample
tls-auth /var/etc/openvpn/server1.tls-auth 0
passtos
persist-remote-ip
float
keepalive 5 20
````

**Expected behavior**
The config file should include the following line:
````
push "dhcp-option DNS 10.6.9.1"
````

**Screenshots**
![01](https://user-images.githubusercontent.com/12986051/59419882-254a9380-8dcc-11e9-80c3-9b6bd8f2becc.JPG)
![02](https://user-images.githubusercontent.com/12986051/59419883-254a9380-8dcc-11e9-9617-a2815b6c20d8.JPG)
![03](https://user-images.githubusercontent.com/12986051/59419884-254a9380-8dcc-11e9-8c64-8004018b8b2e.JPG)
![04](https://user-images.githubusercontent.com/12986051/59419885-254a9380-8dcc-11e9-8d9c-d20373458083.JPG)

**Environment**
OPNsense 19.1.9-amd64
FreeBSD 11.2-RELEASE-p10-HBSD
LibreSSL 2.8.3
Intel(R) Xeon(R) CPU E3-1240 v5 @ 3.50GHz (1 cores)

**Comment by MarinBernard** [comment]
Well,

After I checked out the config again, it appears that the server mode on the failing servers was not set to "remote access" but to "peer to peer". Everything works fine since I corrected it.

Sorry for the noise!

**Comment by gurpal2000** [comment]
I have observed this myself. But no-one has said why the options are not pushed for peer to peer Vs other. Where are the different profiles' capabilities mentioned in documentation either in opnsense or upstream?
