### ISSUE TITLE
Fatal error: require_once(): Failed opening required 'phpseclib/File/X509.php' 

### ISSUE THREAD

**Issue by iMiMx** [opnsense/core#3536]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[-] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
ACK

[-] I have searched the existing issues and I'm convinced that mine is new.
ACK

**Describe the bug**
Fatal error: require_once(): Failed opening required 'phpseclib/File/X509.php' (include_path='.:/usr/local/etc/inc:/usr/local/www:/usr/local/opnsense/mvc:/usr/local/opnsense/contrib:/usr/local/share/pear:/usr/local/share') in /usr/local/www/system_certmanager.php on line 32 

From system_certmanager.php after creating a CA.  Have also submitted an error report directly from the box.

**To Reproduce**
1. Install from latest ISO on download page, 19.1.4 (I think)
2. Upgrade to latest, 19.1.9
3. Create a CA
4. Try to create a cert, system_certmanager.php page then throws the above error.

**Expected behavior**
No error, should load cert manager page.

**Environment**
Software version used and hardware type if relevant.
e.g.:

OPNsense 19.1.9-amd64
FreeBSD 11.2-RELEASE-p10-HBSD
OpenSSL 1.0.2s 28 May 2019

**Comment by iMiMx** [comment]
root@4G-ResVPN-FW00:~ # find / -name X509.php
/lost+found/#1772777/X509.php

Presumably something went wrong with the upgrade.

**Comment by iMiMx** [comment]
'opnsense-update -fp' fixed it

**Comment by fichtner** [comment]
Looks like UFS misbehaved on this one. The 'opnsense-update -fp' is indeed the proper fix. Nice job 👍
