### ISSUE TITLE
CA 400 bad request upon signing new certs with special characters.

### ISSUE THREAD

**Issue by jamiew0w** [opnsense/core#3538]
**Describe the bug**
In newer versions (past 2 releases at least) signing CSRs for subdomains or domains with a hyphen (-) throw a 400 bad request.

**To Reproduce**
1. Go to 'system' -> 'trust' -> 'certificates'
2. Select 'sign certificate'
3. Toss in your CSR and open browser console
4. Click add, get 400 bad response.

**Expected behavior**
It should sign the cert and add it the list to download etc.

**Screenshots**
![](https://down.loaded.ie/nMjPyjLj.png)
**Relevant log files**

Snipped out part of the URL as it just appears to pass the CSR.

```
lighttpd[43602]: (response.c.346) invalid character in URI -> 400 /system_certmanager.php?act=csr_info_json&csr=-----BEGIN%20CERTIFICATE%20REQUEST-----%0AMIIC9DCCAdwCAQAwgYkxCzAJBgHAxDTALBgNVBAsMBHdlbHAx%0AGDAWBgNVBAMMD[R_E_D_A_C_T_E_D]WRIW%2Blm9cKau0nRshW%2BEsIrvnbr%0AfJ3Ob1x80fPjgLSn90feAsCyf6
```

**Environment**
Software version used and hardware type if relevant.
Newest release, hardware etc shouldn't be relevant. The last time I signed certs was the 27th May which I believe, was 2 releases ago (or 1) and there *was* domains with a hyphen included then. Tested with stock safari & no extensions and issue remains.

**Comment by AdSchellevis** [comment]
@jamiew0w can you try https://github.com/opnsense/core/commit/6b92b8170271335a80a8beb971c3fdf63160478f ? I could reproduce the issue on my end, patch fixed it for me.

To install via console:
```
opnsense-patch 6b92b81
```

**Comment by jamiew0w** [comment]
Hello @AdSchellevis 

Awesome work! Does this require a restart to work?
I presume so, I applied the patch but no success and I can't restart for now (or at least for a few days) but I trust your judgement.

Thanks so much for your work on this, you guys are awesome!

**Comment by AdSchellevis** [comment]
@jamiew0w a reboot shouldn't be necessary, a page reload should be enough. can you check if the patch was installed correctly? 

```
grep "'act'" /usr/local/www/system_certmanager.php | grep isset
```

should output something like:
```
    $act = isset($_GET['act']) ? $_GET['act'] : null;
    $act = isset($_POST['act']) ? $_POST['act'] : null;
        $act = isset($_GET['act']) ? $_GET['act'] : null;
```

**Comment by nhirokinet** [comment]
I just met the bug same as this now, and found this issue and `opnsense-patch 6b92b81` on OPNsense 19.1.9 solved my problem.

Sorry if it is the bug I embedded.

**Comment by AdSchellevis** [comment]
@nhirokinet no problem, things happen, I didn't notice the issue either :)

**Comment by nhirokinet** [comment]
Anyway, +1 to your patch. Thanks!

**Comment by jamiew0w** [comment]
No joy on my end I'm afraid @AdSchellevis 

```
grep "'act'" /usr/local/www/system_certmanager.php | grep isset
    $act = isset($_GET['act']) ? $_GET['act'] : null;
    $act = isset($_POST['act']) ? $_POST['act'] : null;
        $act = isset($_GET['act']) ? $_GET['act'] : null;
```

Patching:

```
opnsense-patch 6b92b81
Found local copy of 6b92b81, skipping fetch.
Hmm...  Looks like a unified diff to me...
The text leading up to this was:
--------------------------
|From 6b92b8170271335a80a8beb971c3fdf63160478f Mon Sep 17 00:00:00 2001
|From: Ad Schellevis <ad@opnsense.org>
|Date: Mon, 17 Jun 2019 08:53:05 +0200
|Subject: [PATCH] Trust, import csr. move csr_info and csr_info_json  commands
| to post to prevent sending large / possible illegal blobs of data in uri.
| closes https://github.com/opnsense/core/issues/3538
|
|---
| src/www/system_certmanager.php | 61 +++++++++++++++-------------------
| 1 file changed, 27 insertions(+), 34 deletions(-)
|
|diff --git a/src/www/system_certmanager.php b/src/www/system_certmanager.php
|index 8f6d9aea1b..0d455bfb42 100644
|--- a/src/www/system_certmanager.php
|+++ b/src/www/system_certmanager.php
--------------------------
Patching file www/system_certmanager.php using Plan A...
Reversed (or previously applied) patch detected!  Assuming -R.Hunk #1 succeeded at 257.
Hunk #2 succeeded at 344.
Hunk #3 succeeded at 356.
Hunk #4 succeeded at 374.
Hunk #5 succeeded at 383.
Hunk #6 succeeded at 396.
Hunk #7 succeeded at 490.
Hunk #8 succeeded at 913.
Hunk #9 succeeded at 931.
done
All patches have been applied successfully.  Have a nice day.
```

So looks like it was indeed patched first time, issue remains though. Sorry for the slow replies, really busy lately. Also! This isn't important or mission critical to me, I'm more than happy to wait until next release so don't sweat it because it's not working on my machine (currently). I'm just happy I could report this and bring it to light :D

Thanks for everything!

**Comment by AdSchellevis** [comment]
@jamiew0w no problem, the code looks good, so I'm not sure why it does't work on your end. I can't reproduce it on my machine with the current development code. If you have some time to prepare a test case, I'll gladly take another look and reopen the issue, no rush needed.

**Comment by jamiew0w** [comment]
@AdSchellevis Small update, I squeezed in a reboot today which unfortunately, didn't resolve this on my end. I'd be interested in seeing if this is more widespread or limited to just myself. That said, still not a big deal or anything - just figured that feedback may be useful.

**Comment by AdSchellevis** [comment]
@jamiew0w ok, thanks for letting us know. Let's see if the next release fixes your issue, if not, we can reopen this issue and see if we can collect more feedback from others.
