### ISSUE TITLE
DNS Forwarder

### ISSUE THREAD

**Issue by fatchoy** [opnsense/core#354]
Hi, it's not an issue but in the services.inc dnsmasq is identified as "DNS forwarder" and Unbound is named "Unbound DNS Forwarder" but in the services list, they are respectively "DNS Forwarder" and "DNS Resolver", I propose to rename the Unbound service to "Unbound DNS Resolver"

**Comment by fichtner** [comment]
On a related note: I like neither the forwarder nor resolver thing to be honest. There's a DNS server that happens to run dnsmasq, there's another one using unbound. The GUIs are different when they shouldn't. In the long run, there will only be one server. It's been hell to have to support both and the associated confusion.

I would rather use something like "Dnsmasq DNS Server" and "Unbound DNS Server"?

**Comment by fatchoy** [comment]
Agreed, my note was just to point out the difference between the naming in the services submenu and the status services items.

**Comment by fichtner** [comment]
Fair enough, and thanks for that. I always try to go a little further so I thought it was good to write this down in a related ticket and leave it here for discussion. :)

The naming fix we can probably get into 15.7.12.

**Comment by 8191** [comment]
Which services/functions can unbound not provide at the moment, which dnsmasq can? Or: what keeps you from dropping dnsmasq right now? 

btw: DNS = Domain Name _System_ 😉

**Comment by fichtner** [comment]
Hehe, you got me. :)

Dnsmasq works more reliable. Unbound was at one point imported from packages and you already found an issue with it. The integration of unbound (because of having been a package once) is a bit cleaner though. I don't know what the endgame was for importing unbound, now there's two and nothing happens anymore...

**Comment by fichtner** [comment]
(I realise that doesn't answer your question. I don't know a better one.)

**Comment by 8191** [comment]
So the plan is dropping dnsmasq or unbound? Or dropping both for the sake of a new, clean application for dnsmasq/unbound/bind/etc...  :grinning:

**Comment by fatchoy** [comment]
Having the option to run a resolver such as OPNsense is great in those time of censorship. Blockage of website in europe are done with DNS poisoning at the ISP level. 
Having your own resolver make you independent of your ISP decision over the DNS service.

**Comment by 8191** [comment]
I think dnsmasq also is capable of resolving, not only forwarding.

**Comment by fatchoy** [comment]
Unfortunately not, dnsmasq rely on external DNS.

**Comment by fichtner** [comment]
overcome by events :)
