### ISSUE TITLE
Syslog: remove legacy remote logging

### ISSUE THREAD

**Issue by AdSchellevis** [opnsense/core#3540]
With the new options available in 19.7 we should begin to schedule removal of the old remote logging options in diag_logs_settings.php

Setting up new remote loggers is quite easy with the new grid in /ui/syslog/ and has more options than the old version. I would like to suggest to just ditch "Remote Logging Options" in 20.1 and skip migration code to avoid spending quite some time on this area.

**Comment by fichtner** [comment]
Indeed, good approach. 👍
