### ISSUE TITLE
Create and retrieve OpenVPN: Client Specific Overrides through API

### ISSUE THREAD

**Issue by gvecchicert** [opnsense/core#3541]
Hi guys,

please consider to add creation and retrieving Client Specific Overrides for a specific OpenVPN server instance through API

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/core/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.

**Comment by chimmmpie** [comment]
@AdSchellevis What would be needed to implement this? 
The OpenVPN code seems very old to me. The client export code seems a bit newer but it still does not comply with the coding standard. 
Does the whole OpenVPN code need to be refactored or is something in between also acceptable?

**Comment by AdSchellevis** [comment]
@chimmmpie most is old, except for the exporter which we rebuild quite some years ago. Redesigning the CSO frontend would be preferable, but requires quite an investment from our end and comes with additional challenges such as the need to drop "advanced" inputs as well.

**Comment by chimmmpie** [comment]
Is there anything that can be done on the short & mid term to get API support for it? What kind of contributions would be acceptable as the investment to redesign it fully is too high?

**Comment by AdSchellevis** [comment]
I don't think there's really a middle ground here, the smallest unit to redesign is the override section. There's no need to refactor all OpenVPN components.

**Comment by chimmmpie** [comment]
Than we should start making a list of all the options required in the interface. 
For me the option to assign a static IP to the user is important. But i think there are more that should considered.

**Comment by AdSchellevis** [comment]
It's probably easier to use radius to distribute the addresses, in which case you don't need to use manual overrides anyway.

**Comment by mimugmail** [comment]
And Radius is API enabled :)

**Comment by kozistan** [comment]
i would really appreciate option to use CSO API. 
I have many VPN Servers and over 150users so this option would be very useful. Is there any chance this will be done?

**Comment by fichtner** [comment]
To my knowledge this was released almost 2 years ago in 23.7.

**Comment by kozistan** [comment]
> To my knowledge this was released almost 2 years ago in 23.7.

you're right https://docs.opnsense.org/development/api/core/openvpn.html

thanks for your reply!
