### ISSUE TITLE
IPsec Passthrough networks not working

### ISSUE THREAD

**Issue by shaun040** [opnsense/core#3543]
**Describe the bug**

On a full tunnel, where remote subnet in phase2 is 0.0.0.0/0. This will force all traffic configured in source over the tunnel unless exceptions are created in Passthrough networks.

When passthrough networks are added to Passthrough Networks, adding a network like 192.168.0.0/24 should be sufficient. This does not work and tunnels listed in passthrough are still routed down the tunnel

**To Reproduce**
1. Establish IPsec VPN tunnel
2. Configure Phase 2 to be a single device behind OPNSense with remote being 0.0.0.0/0
3. Go to VPN --> IPsec --> Advanced Settings
4. Configure your pass through networks 
5. Click Save
6. Try to access internal resources from a device.

**Expected behavior**
Adding a subnet under IPsec --> Advanced Settings --> Passthrough networks will not send traffic to those subnets down the tunnel

**Additional context**
The tunnel in question is a full s2s so all internet traffic should egress down the ipsec tunnel from a specific host and\or network configured in the phase2 entry but not networks specified in Passthrough networks.

I did see this closed report where it was brought up to add locally attached interfaces to bypass the tunnel. 

This would be helpful but if getting passthrough networks to work, would be sufficient enough.

https://github.com/opnsense/core/issues/2571

**Environment**
Software version used and hardware type if relevant.
e.g.:

OPNsense 19.1.9 (amd64, OpenSSL 1.0.2s).
Intel® Atom E3845
Hardware: Protectli Micro Appliance

**Comment by AdSchellevis** [comment]
just to be sure, did you try to restart ipsec? I'm not entirely sure a reload always works in this case. You can check the generated config in `/usr/local/etc/ipsec.conf`, which should contain a pass through like this:

```
conn pass
  right=127.0.0.1 # so this connection does not get used for other purposes
  leftsubnet=x.x.x.x/24
  rightsubnet=x.x.x.x/24
  type=passthrough
  auto=route
```

The feature was originally added in https://github.com/opnsense/core/issues/1890

**Comment by mimugmail** [comment]
Yes, some situations require restart (e.g. via  Dashboard Service cycle)
