### ISSUE TITLE
Kvm machine make opnsense down for the whole network

### ISSUE THREAD

**Issue by RomanJos** [opnsense/core#3544]
Hi i'm having some issue regarding opnsense and my kvm windows, when i start the vm and download from it i have no longer the dhcp server working, the dns etc but i don't hear the beep that opnsense make at boot so it doesn't restart, I checked the dmesg message after shut down windows and wait for 1-2 minutes for opnsense to be able to connect and its a spam of `arp : 192.168.1.5 has moved from 00:19:87:65:43:21 to 12:34:56:78:91:00` and inversed (not the actual message its what i remember). in windows i get a lease from opnsense like a normal pc so i don't really know why it show some message like this.
My kvm setup when i saw the logs was one ethernet card for linux and another for windows like if they were two distinct computer but i have now changed I created a nat for it but it doesn't work either my only choice is to be on the network of my 4G router instead of opnsense. i didn't see the dmesg with the nic but i beleive its same.

**Comment by fichtner** [comment]
Not using a ticket template.
