### ISSUE TITLE
Webproxy / reset cache and other state files

### ISSUE THREAD

**Issue by AdSchellevis** [opnsense/core#3545]
When performing a major upgrade, there's a change that binary files don't match the new version resulting in issues like https://forum.opnsense.org/index.php?topic=13179.msg60642#msg60642

A button to reset / cleanup state (files in /var/squid) would be helpful here, both for the cached objects as ssl_crtd.

**Comment by AdSchellevis** [comment]
![image](https://user-images.githubusercontent.com/9783985/59844914-4a0ab200-935c-11e9-9eec-e9058c0bc9da.png)

**Comment by ssbarnea** [comment]
There is clearly something wrong with current implementation as I can confirm what other user already remarked: fixing this required: stopping squid, using reset button, rebooting router, starting squid again. This was the only think what made 19.7 work again and is clearly far from desired user experience, where the service should repair itself.

**Comment by fichtner** [comment]
@ssbarnea patches welcome
