### ISSUE TITLE
DHCPv6 ddns configuration from webgui does not accept an IPv6 dns address

### ISSUE THREAD

**Issue by Stifler6996** [opnsense/core#3546]
[X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[X] I have searched the existing issues and I'm convinced that mine is new.

**Describe the bug**
In the DHCP6 settings, when attempting to configure DDNS through the webgui, the setting "Enter the primary domain name server IP address for the dynamic domain name" -- the webgui is (I believe incorrectly) expecting an IPv4 address for the dns server.

I expect that this is due to duplication of the webgui component for DHCPv4 to the new DHCPv6 configuration page(s). 

**To Reproduce**
1. Go to 'services -> dhcpv6 -> lan -> dynamic dns [advanced] '
2. Click on 'Enter the primary domain name server IP address for the dynamic domain name'
3. Enter the IPv6 address of your dns server
4. Tick "Enable registration of DHCP client names in DNS"
5. Add domain to "Enter the dynamic DNS domain which will be used to register client names in the DNS server" Box.
6. Click "SAVE"
7. See error

**Expected behavior**
Accept the IPv6 address of the DNS server.

**Additional context**
You will be required to enter the domain name in "Enter the dynamic DNS domain which will be used to register client names in the DNS server" under the same settings in order to test.

**Environment**
opnsense 19.1.9

![image](https://user-images.githubusercontent.com/12870096/59857550-5290d600-93b8-11e9-83d0-8b11587faf6b.png)

**Comment by AdSchellevis** [comment]
doesn't show an error on my end (using a google address)
![image](https://user-images.githubusercontent.com/9783985/59856756-d9718e80-9377-11e9-83fb-3c0e3abea39f.png)

**Comment by Stifler6996** [comment]
Sorry, I assumed that it was implied that the settings would be applied.

I have amended my steps.

**Comment by AdSchellevis** [comment]
I'm not sure what you mean, what settings did you enter? or is your ticket about the IPv4 message?

**Comment by Stifler6996** [comment]
For the purpose of replication,  I tested with Google dns, same as you did.

And yes, the result is that the address is not accepted, and that message appears at the top, expecting an ipv4 value.

**Comment by AdSchellevis** [comment]
are you sure there are no spaces in front or behind the address? I don't think the development version is different in this regard.

**Comment by AdSchellevis** [comment]
@Stifler6996 ok, can you try this:

```
opnsense-patch  c5c6bb1 9bf0756
```

Seems like a faulty validation indeed

**Comment by Stifler6996** [comment]
I have copied/pasted the address as well as typed it out.
In both cases, I checked for spaces before and after the address before applying the settings.

I have not tried using a 'long' ipv6. In all cases I used the short form with :: within the address.

**Comment by Stifler6996** [comment]
I'll need to clone the appliance before doing patch testing.

I presume the code you supplied is a cli/shell command?

**Comment by AdSchellevis** [comment]
yes, you can execute opnsense-patch in a shell

**Comment by Stifler6996** [comment]
This patch has resolved the exact problem of entering an IPv6 address in the ddns settings "primary domain name server" as required for the DHCPv6 server, when configuring the DDNS component.

Very good.

**Comment by AdSchellevis** [comment]
@Stifler6996 thanks for confirming
