### ISSUE TITLE
reporting: Netflow validation listen vs. egress

### ISSUE THREAD

**Issue by fichtner** [opnsense/core#3547]
https://github.com/opnsense/core/issues/2197 changed the text to make it clearer, but it's further from the truth now. What we need is a validation between listen and egress so that we can confirm egress is a subset of listening interfaces.

**Comment by AdSchellevis** [comment]
https://github.com/opnsense/core/commit/658e3d00924a857d8db9acda4f90d8d2d97ccb50 adds the validation

**Comment by fichtner** [comment]
❤️
