### ISSUE TITLE
Unbound crash "fatal error"

### ISSUE THREAD

**Issue by stilez** [opnsense/core#3548]
I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md;  and I have searched the existing issues and I'm convinced that mine is new.

**Describe the bug**

Unbound service stopped due to a fatal error, log reports unreadable config but can't be sure if this is the "real" underlying reason, as it had no problem restarting the service. 

The router hadn't been touched or rstarted or the GUI entered for some time (1-2 weeks), so this isn't an effect of any recent change or altered usage. No idea how to reproduce, no obvious signs of it being triggered by anything anyone has done, or by any recent restart, config change, upgrade etc. 

**Relevant log files**

(18:20:13 was the service restart AFAIK)

> 18:20:13 	unbound: [25022:0] debug: chdir to /var/unbound
> 16:20:41 	unbound: [80234:0] fatal error: Could not read config file: /unbound.conf. Maybe try unbound -dd, it stays on the commandline to see more errors, or unbound-checkconf
> 16:20:41 	unbound: [80234:0] notice: Restart of unbound 1.9.1.
> 16:20:41 	unbound: [80234:0] debug: cache memory msg=132120 rrset=459800 infra=1998160 val=740026
> 16:20:41 	unbound: [80234:0] info: 0.065536 0.131072 4
> 16:20:41 	unbound: [80234:0] info: lower(secs) upper(secs) recursions
> 16:20:41 	unbound: [80234:0] info: [25%]=0.08192 median[50%]=0.098304 [75%]=0.114688
> 16:20:41 	unbound: [80234:0] info: histogram of recursion processing times
> 16:20:41 	unbound: [80234:0] info: average recursion processing time 0.090076 sec
> 16:20:41 	unbound: [80234:0] info: mesh has 0 recursion states (0 with reply, 0 detached), 0 waiting replies, 4 recursion replies sent, 0 replies dropped, 0 states jostled out
> 16:20:41 	unbound: [80234:0] info: server stats for thread 3: requestlist max 1 avg 0.5 exceeded 0 jostled 0
> 16:20:41 	unbound: [80234:0] info: server stats for thread 3: 6 queries, 2 answers from cache, 4 recursions, 0 prefetch, 0 rejected by ip ratelimiting
> 16:20:41 	unbound: [80234:0] debug: cache memory msg=132120 rrset=459800 infra=1998160 val=740026
> 16:20:41 	unbound: [80234:0] info: 0.131072 0.262144 1
> 16:20:41 	unbound: [80234:0] info: lower(secs) upper(secs) recursions
> 16:20:41 	unbound: [80234:0] info: [25%]=0 median[50%]=0 [75%]=0
> 16:20:41 	unbound: [80234:0] info: histogram of recursion processing times
> 16:20:41 	unbound: [80234:0] info: average recursion processing time 0.133496 sec
> 16:20:41 	unbound: [80234:0] info: mesh has 0 recursion states (0 with reply, 0 detached), 0 waiting replies, 1 recursion replies sent, 0 replies dropped, 0 states jostled out
> 16:20:41 	unbound: [80234:0] info: server stats for thread 2: requestlist max 0 avg 0 exceeded 0 jostled 0
> 16:20:41 	unbound: [80234:0] info: server stats for thread 2: 3 queries, 2 answers from cache, 1 recursions, 0 prefetch, 0 rejected by ip ratelimiting
> 16:20:41 	unbound: [80234:0] debug: cache memory msg=132120 rrset=459800 infra=1998160 val=740026
> 16:20:41 	unbound: [80234:0] info: 0.000000 0.000001 1
> 16:20:41 	unbound: [80234:0] info: lower(secs) upper(secs) recursions
> 16:20:41 	unbound: [80234:0] info: [25%]=0 median[50%]=0 [75%]=0
> 16:20:41 	unbound: [80234:0] info: histogram of recursion processing times
> 16:20:41 	unbound: [80234:0] info: average recursion processing time 0.000000 sec
> 16:20:41 	unbound: [80234:0] info: mesh has 0 recursion states (0 with reply, 0 detached), 0 waiting replies, 1 recursion replies sent, 0 replies dropped, 0 states jostled out
> 16:20:41 	unbound: [80234:0] info: server stats for thread 1: requestlist max 0 avg 0 exceeded 0 jostled 0
> 16:20:41 	unbound: [80234:0] info: server stats for thread 1: 1 queries, 0 answers from cache, 1 recursions, 0 prefetch, 0 rejected by ip ratelimiting
> 16:20:41 	unbound: [80234:0] debug: cache memory msg=132120 rrset=459800 infra=1998160 val=740026
> 16:20:41 	unbound: [80234:0] info: 0.131072 0.262144 1
> 16:20:41 	unbound: [80234:0] info: lower(secs) upper(secs) recursions
> 16:20:41 	unbound: [80234:0] info: [25%]=0 median[50%]=0 [75%]=0
> 16:20:41 	unbound: [80234:0] info: histogram of recursion processing times
> 16:20:41 	unbound: [80234:0] info: average recursion processing time 0.139036 sec
> 16:20:41 	unbound: [80234:0] info: mesh has 0 recursion states (0 with reply, 0 detached), 0 waiting replies, 1 recursion replies sent, 0 replies dropped, 0 states jostled out
> 16:20:41 	unbound: [80234:0] info: server stats for thread 0: requestlist max 0 avg 0 exceeded 0 jostled 0
> 16:20:41 	unbound: [80234:0] info: server stats for thread 0: 3 queries, 2 answers from cache, 1 recursions, 0 prefetch, 0 rejected by ip ratelimiting
> 16:20:41 	unbound: [80234:0] info: service stopped (unbound 1.9.1).
> 16:20:08 	unbound: [80234:0] info: 192.168.100.2 statsfe2.ws.microsoft.com. A IN NXDOMAIN 0.000000 1 43
> 16:20:08 	unbound: [80234:0] info: statsfe2.ws.microsoft.com. static 192.168.100.2@58561 statsfe2.ws.microsoft.com. A IN
> 16:20:08 	unbound: [80234:0] info: 192.168.100.2 statsfe2.ws.microsoft.com. A IN
> 16:18:47 	unbound: [80234:1] debug: cache memory msg=2194897 rrset=4951992 infra=1998160 val=740026
> 16:18:47 	unbound: [80234:1] info: 192.168.100.2 dnl-11.geo.kaspersky.com. A IN NOERROR 0.000000 0 58
> 16:18:47 	unbound: [80234:1] info: validator operate: query dnl-11.geo.kaspersky.com. A IN
> 16:18:47 	unbound: [80234:1] debug: validator[module 0] operate: extstate:module_wait_module event:module_event_moddone
> 16:18:47 	unbound: [80234:1] info: finishing processing for dnl-11.geo.kaspersky.com. A IN
> 16:18:47 	unbound: [80234:1] info: resolving dnl-11.geo.kaspersky.com. A IN
> 16:18:47 	unbound: [80234:1] debug: iterator[module 1] operate: extstate:module_state_initial event:module_event_pass
> 16:18:47 	unbound: [80234:1] info: validator operate: query dnl-11.geo.kaspersky.com. A IN
> 16:18:47 	unbound: [80234:1] debug: validator[module 0] operate: extstate:module_state_initial event:module_event_new
> 16:18:47 	unbound: [80234:1] info: . transparent 192.168.100.2@51394 dnl-11.geo.kaspersky.com. A IN
> 16:18:47 	unbound: [80234:3] info: 192.168.100.2 dnl-11.geo.kaspersky.com. AAAA IN NOERROR 0.000000 1 114
> 16:18:47 	unbound: [80234:1] info: 192.168.100.2 dnl-11.geo.kaspersky.com. A IN

A search for "fatal" using GUI in the unbound log showed these results, so it's not an isolated occurrance:

> Jun 21 16:20:41 | unbound: [80234:0] fatal error: Could not read config file:  /unbound.conf. Maybe try unbound -dd, it stays on the commandline to see  more errors, or unbound-checkconf
> Jun 16 21:45:32 | unbound: [18001:0] fatal error: Could not read config file:  /unbound.conf. Maybe try unbound -dd, it stays on the commandline to see  more errors, or unbound-checkconf
> May 16 04:49:25 | unbound: [28034:0] fatal error: Could not read config file:  /unbound.conf. Maybe try unbound -dd, it stays on the commandline to see  more errors, or unbound-checkconf
> May 16 02:37:17 | unbound: [75566:0] fatal error: Could not read config file:  /unbound.conf. Maybe try unbound -dd, it stays on the commandline to see  more errors, or unbound-checkconf
> 
> 

**Environment (copypasted from GUI/Lobby)**

OPNsense 19.1.6-amd64
FreeBSD 11.2-RELEASE-p9-HBSD
OpenSSL 1.0.2r  26 Feb 2019
CPU Type Intel(R) Core(TM) i5-2310 CPU @ 2.90GHz (4 cores)
Load average | 0.25, 0.29, 0.34
Uptime | 53 days 08:40:45
Current date/time | Fri Jun 21 18:41:08 BST 2019
Last config change | Mon Apr 29 10:00:40 BST 2019
State table size | 0 % ( 628/806000 )
MBUF Usage | 1 % ( 6840/501676 )
Memory usage | 14 % ( 1172/8067 MB )
SWAP usage | 0 % ( 0/4096 MB )
Disk usage | 9% / [ufs] (5.4G/68G)

**Comment by fichtner** [comment]
Is this still happening on 19.7.4?
