### ISSUE TITLE
Alias lag a sane default sorting

### ISSUE THREAD

**Issue by Nico82x** [opnsense/core#3550]
The "Alias" feature seems to lack a good default sorting (again as it seems?). Adding multiple very similar named entries of the same type leads to them being inserted at some random position as it seems. Manually sorting by Name works of course but shouldn't be required. Furthermore the default list size is just 7 which is surprisingly small. I'd vote fot this number to be increased to 20 by default for example.

**Environment**
OPNsense 19.1.9-amd64

Thanks!

**Comment by AdSchellevis** [comment]
The development version stores settings (https://github.com/opnsense/core/commit/7367a3bc455c741e5894b131f16e52d348ae5d09, https://github.com/opnsense/core/commit/53bc9f49c3c6dabd13fb4ae856488e6b95952979 ), although I’m not sure it remembers sorting as well. The “again” in your issue probably relates to an ancient version which had no sorting options at all (which made forced automatic sorting the only option).

Please check the development version first.
