### ISSUE TITLE
Traffic shaping: Pipe/Queue Mask 'empty' not available/possible

### ISSUE THREAD

**Issue by mr44er** [opnsense/core#3552]
System: OPNsense 19.1.9-amd64 / OpenSSL 1.0.2s 28 May 2019

An empty mask is not available to choose. Problem exists on pipe and queue.
Tested with Firefox and Chromium on FreeBSD + Firefox and Edge on Windows10.
Predefined is always 'MIME-Version: 1.0.... etc' as in the screenshot.

![masknotempty](https://user-images.githubusercontent.com/46787531/60108278-a3ae1a80-9768-11e9-8b5f-e8fa1db4f82b.jpeg)

Mask should be empty on adding a new pipe or queue, right? I can't say for sure, because it's my first time using traffic shaping.

As a result, traffic shaping doesn't work at all with FQ-CoDel.

This user has the same problem:
https://forum.opnsense.org/index.php?topic=12735.msg58902#msg58902

**Comment by fichtner** [comment]
This is a translation issue, an empty "" string is pushed to the translation which yields this translation meta-data.

**Comment by mr44er** [comment]
Ah, ok. So for now is there anything I could manually edit in config to get this to work?

**Comment by fichtner** [comment]
Selecting the "weird" value should work. If not, switch GUI to English and retry.

**Comment by fichtner** [comment]
# opnsense-patch 6b6e3ed

should work as well :)

**Comment by mr44er** [comment]
![maskempty](https://user-images.githubusercontent.com/46787531/60110521-7c594c80-976c-11e9-8058-d781d73b6c9a.png)

Ah, thank you!
'weird' value didn't work, I tried. Switching from german to english did the trick, so I guess it'll work now. :)

**Comment by fichtner** [comment]
I'm not aware of operational differences between GUI labels and underlying data. Chances are the original issue you're seeing is still there so be careful.

**Comment by mr44er** [comment]
I will check carefully, system isn't in productive mode for now.
