### ISSUE TITLE
iPXE filename support in network booting options

### ISSUE THREAD

**Issue by eburghar** [opnsense/core#3557]
iPXE has a lot of extra options which simplify provisioning servers in a datacenter, and when you can't (or don't want to) flash your network card, you have to chainload ipxe from pxe.

To avoid infinite loop (pxe loads ipxe that again requests boot parameters and loads itself), you either need to compile ipxe with an embedded script which contains a static chainload (http://ipxe.org/howto/chainloading), or be able to differentiate ipxe requests in dhcp parameters from regular pxe ones.

```diff
--- a/usr/local/etc/inc/services.inc 2018-03-22 19:30:37.637717000 +0100
+++ b/usr/local/etc/inc/services.inc 2018-03-22 19:35:45.577577000 +0100
@@ -811,7 +811,9 @@
                 $dhcpdconf .= "  next-server {$dhcpifconf['nextserver']};\n";
             }
             if (!empty($dhcpifconf['filename']) && !empty($dhcpifconf['filename32']) && !empty($dhcpifconf['filename64'])) {
-                $dhcpdconf .= "  if option arch = 00:06 {\n";
+                $dhcpdconf .= "  if exists user-class and option user-class = \"iPXE\" {\n";
+                $dhcpdconf .= "    filename \"http://mb.local.lan/boot.ipxe\";\n"; 
+                $dhcpdconf .= "  } else if option arch = 00:06 {\n";
                 $dhcpdconf .= "    filename \"{$dhcpifconf['filename32']}\";\n";
                 $dhcpdconf .= "  } else if option arch = 00:07 {\n";
                 $dhcpdconf .= "    filename \"{$dhcpifconf['filename64']}\";\n";
```

It would be nice to have an option field `$dhcpifconf['filenameipxe']` to deal with this user case.

**Comment by fichtner** [comment]
Not using a ticket template.
