### ISSUE TITLE
IPSec interface does not show under Interfaces

### ISSUE THREAD

**Issue by Nornode** [opnsense/core#3558]
Similar to #1435
I have three tunnels up and running (great!) however I don't have an interface for IPsec.
So I'm unable to assign that for a Gateway.

OPNsense 19.1.9-amd64
FreeBSD 11.2-RELEASE-p10-HBSD
OpenSSL 1.0.2s 28 May 2019

**Comment by fichtner** [comment]
Slight misconception here. If you need routable IPsec you need to follow this doc which will automatically provide you with interfaces:

https://docs.opnsense.org/manual/how-tos/ipsec-s2s-route.html

**Comment by Nornode** [comment]
Wow! that was fast! - Thanks!
Humm, I'm sorry if I misunderstood this then! 
Let me note also I do not want to route my whole SiteB traffic to SiteA but only a handful assigned by a firewall rule.
Also, if you may know? (I know it's far fetched) SiteA is a Fortigate device, do I need to change anything on that side?

**Comment by mimugmail** [comment]
You can just add routes for single IP addresses with route-based IPSEC, no problem. Should also be same for Fortigate.

**Comment by fichtner** [comment]
For OPNsense, the most important settings are phase 1 leave install policy unchecked and phase 2 set mode to "Route-based" for the interfaces to appear.

**Comment by Nornode** [comment]
Alright, Thanks! - I'll figure things out! 
Thanks for your blazing fast support and comments!
