### ISSUE TITLE
interfaces: lockout on LAN disable?

### ISSUE THREAD

**Issue by fichtner** [opnsense/core#356]
"I logged in as usual via OPT1 as the non-root Admin, I then disabled the LAN interface and the Web UI is not contactable - is this expected behaviour or should I still be able to manage the server if the LAN is down?"

via: https://forum.opnsense.org/index.php?topic=1308.0

**Comment by AdSchellevis** [comment]
Some additional info, it looks related to lighthttp. 

A snapshot of the affective pf rules:
OPT1 = "{ vmx2 }"
scrub on $OPT1 all no-df   fragment reassemble
antispoof log for $OPT1
pass  in  quick  on $OPT1 inet proto tcp  from any to any flags S/SA keep state  label "USER_RULE"

**Comment by fichtner** [comment]
Most likely related to the fundamental fix that went into 15.7.22.
