### ISSUE TITLE
Default number of rows per page, on paged tables.

### ISSUE THREAD

**Issue by FingerlessGlov3s** [opnsense/core#3560]
When you browsing Aliases, the view defaults to 7 rows a page, it would be great if we could set a default of say 14 or 20. So you don't have to change it every time.

Same with the Shaper page, and any other pages like it.

**Describe the solution you'd like**
WebUI settings page, with settings like this to set default rows per page.

**Describe alternatives you've considered**
None that I know of.

**Additional context**
![image](https://user-images.githubusercontent.com/3495647/60626300-45291200-9de2-11e9-97b1-8698064f3c36.png)

**Comment by AdSchellevis** [comment]
duplicate https://github.com/opnsense/core/issues/3550
