### ISSUE TITLE
Feature request: Dashboard widget for intrusion detection alerts

### ISSUE THREAD

**Issue by lwilli90** [opnsense/core#3561]
Dashboard widget for intrusion detection alerts.

This would show the last X number of intrusion detection alerts.  With options to change the number and frequency of updates similar to how the Firewall logs widget is setup.  

The title of the widget should be a link directly the alerts page (/ui/ids#alerts), again, similar to how clicking on the title of the Firewall logs widget takes you straight to the firewall logs page (/ui/diagnostics/firewall/log).

**Comment by StevenNexus** [comment]
Great idea, the Alerts tab of the IDS is an area I check most often when I have to check up on the firewall.

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/core/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
