### ISSUE TITLE
Changing alias will not show "reload filters" message in GUI

### ISSUE THREAD

**Issue by markusd112** [opnsense/core#3562]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[X] I have searched the existing issues and I'm convinced that mine is new.

**Describe the bug**
I am using several alias in my firewall rules. When changing an used alias, the change is not active after saving the alias, since you have reload the rulesets/apply changes. For all other changes in the rules there appears an information message that the changes will take effect after a reload/applying. When changing the aliases no message is displayed in the WebGUI, nor the user can find anywhere an "apply changes" button...

**To Reproduce**
1. Use an alias in some firewall rule, e.g. for a destination port
2. change the alias, e.g. add another port
3. no information is displayed in the WebGUI

**Expected behavior**
There should be displayed an information message with a button to reload firewall rules, when changing an alias, as already implemented when changing firewall rules:
![Bildschirmfoto 2019-07-07 um 07 15 41](https://user-images.githubusercontent.com/14372683/60764297-58104080-a087-11e9-9a31-37771290cb56.png)

**Relevant log files**
n/a

**Additional context**
n/a

**Environment**
OPNsense 19.1.9-amd64

**Comment by fichtner** [comment]
This was a feature added to the upcoming 19.7.

**Comment by rtheil-growlink** [comment]
This seems to still not be a thing. When I update an alias that is associated with a rule, there is no way to apply the change. I must go into the firewall and edit a rule to have the apply button pop up.

**Comment by rtheil-growlink** [comment]
When making a change to an alias, it does not apply that change. I must edit a rule with that alias and save it, then apply. On 24.7.3_1

Also checked alias diagnostics, and the IP of my alias is nowhere listed, but I have confirmed that the change of the alias alone definitely does not apply the change without also saving a firewall rule (making no changes) and applying that change.

**Comment by fichtner** [comment]
But do you hit apply on the alias page to apply the alias change?

**Comment by rtheil-growlink** [comment]
I have figured out why this was happening. When you make a change to an alias, the apply change button shows up at the bottom of the list. In my case this is just barely off screen when my window is maximized, so I would never see it or notice that the vertical scroll had either appeared or grown. This is inconsistent UX since everywhere else the apply button appears at the top of the list. Seems like this page should be changed to make the experience consistent with other areas. Thanks for the help, because I was so confused why this was not working.
