### ISSUE TITLE
geoip - Schweiz/Switzerland: Cannot allocate memory

### ISSUE THREAD

**Issue by mr44er** [opnsense/core#3564]
[x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[x] I have searched the existing issues and I'm convinced that mine is new.

**Describe the bug**
I want to create a block alias for every country in ipv4 and ipv6 except germany. When I tick everything except germany and apply, I'll get 'Cannot allocate memory'.
I switched RAM from 4GB to 8GB which increased the table from 405000 to 815000, but it's the same result. In Switzerland lies the bug.

**To Reproduce**
It works when I untick Switzerland, but additionally it should be then 47 out of 49 selected. Anyways, it shows 46 out of 49, which I guess could lead to the bug.

![1](https://user-images.githubusercontent.com/46787531/60921035-e5c37a00-a299-11e9-894b-19d1b258451e.png)
![2](https://user-images.githubusercontent.com/46787531/60921036-e5c37a00-a299-11e9-9797-07a284dcedc5.png)
![3](https://user-images.githubusercontent.com/46787531/60921038-e5c37a00-a299-11e9-8c46-cf121567db56.png)

OPNsense 19.1.10 (amd64, LibreSSL).
AMD Opteron(tm) Processor 4234
Intel 82574L Gigabit Network Connection

**Comment by fichtner** [comment]
Under Firewall: Settings: Advanced set "Firewall Maximum Table Entries" to e.g. 6000000.

**Comment by mr44er** [comment]
6 zeroes, double-check.
But now: 
![4](https://user-images.githubusercontent.com/46787531/60922584-5b7d1500-a29d-11e9-947a-2f7acd9c436b.png)

Maybe reboot helps?
And it still says `47 out of 49 selected` with only Germany unticked.

**Comment by fichtner** [comment]
Still too low maybe? If you have IPv6 enabled table entry count could be huge.

**Comment by mr44er** [comment]
I know that it will get huge, but I have no idea in GB what huge means. I have no experience with it. Isn't there a crude rule of thumb? ;)

After reboot, no message so far.

**Comment by mimugmail** [comment]
Why not choose only DE and CH and negate/invert the rule?

**Comment by mr44er** [comment]
Sounds good, will try that. I really have no experience with the possibilities of more advanced fw-rules.

**Comment by mimugmail** [comment]
Just create the identical rule and hit "invert" checkbox .. (of course with new alias containing only the two).

**Comment by mr44er** [comment]
Nice, thank you!
![6](https://user-images.githubusercontent.com/46787531/60960348-1fcc6480-a30a-11e9-92bd-7bf548957ec1.png)

Helps understanding, what invert means. I only wanted to allow DE, so it should work now and problem is solved. :)

**Comment by mr44er** [comment]
After some days and some machines testing...
**only germany + invert** works so nice and fast.
