### ISSUE TITLE
Modem Huawei E3372h don't connect

### ISSUE THREAD

**Issue by orzechszek** [opnsense/core#3565]
OPNsense 19.1.4-amd64
Intel® Celeron n3160
Network Realtek

During connection I'm still getting: 
CHAT: The modem is not responding to "AT" at ModemCmd: label.

I have modem in "stick" mode.
I've updated "init string" with: "&F&C1&D2E0S0=0", also "Z", "F" or empty.
It looks like init string wasn't updated and used in new configuration. 
I've changed init string in PFSense with "&F&C1&D2E0S0=0" and it started working.

**Comment by orzechszek** [comment]
The same behavior on OPNsense-19.7.r1-OpenSSL-vga-amd64

**Comment by orzechszek** [comment]
It's not a bug? On two types of version I can't connect. I do the same on pfsense and it worka.

**Comment by fichtner** [comment]
Not using a ticket template.
