### ISSUE TITLE
captiveportal: provide login/logout information to external applications (plugins)

### ISSUE THREAD

**Issue by muratbalaban43** [opnsense/core#3566]
plugins/vendor/sunnyvalley/sensei has the ability to enforce policies according to users/groups. 

We have an Active Directory agent application that is capable of feeding user login/logout information to Sensei. 

We were thinking if that could also be possible for OPNsense captive portal. 

Do you think it might be a good idea to provide this info to third party applications? 

My first bet would be that plugins could register themselves to a service, and whenever there is a login/logout event, these callbacks could be fired & fed with the relevant information.

**Comment by AdSchellevis** [comment]
I'm not entirely sure what you mean, if the agent grants/denies access, it might already be able to grant/deny captive portal access using its admin endpoint.

If it's something different and in need of some event handler, we might look into the details after 19.7 is released in case we could think of something generic.

**Comment by muratbalaban43** [comment]
Hi Ad,

Yep, we could do it if users are authenticated via AD. If the user is authenticated via a local database, AD agent would be of no use. 

Agreed. I'll provide more info for a more generic implementation.

For now, I guess we'll be implementing a mini service polling the sqlite database for new login/logouts.

**Comment by muratbalaban43** [comment]
Hi Ad,

We solved this by implementing a mini service polling the captive user database in intervals. 

Looks fine for now, so closing.
