### ISSUE TITLE
OpenVPN server wizard always asks to create a new CA

### ISSUE THREAD

**Issue by int-red** [opnsense/core#3568]
When you use the OpenVPN server wizard to create a new server you are always asked to
create a New Certificate Authority (CA) Certificate. 
You can not use an already existing CA. There should be an option to select an existing CA.

**Comment by johnaheadley** [comment]
@fichtner can this be closed now?

**Comment by AdSchellevis** [comment]
fixed in https://github.com/opnsense/core/pull/3614 thanks to @johnaheadley 👍
