### ISSUE TITLE
WARNING: /mnt was not properly dismounted message on console

### ISSUE THREAD

**Issue by gitdevmod** [opnsense/core#357]
OPNsense 15.7.11-i386
FreeBSD 10.1-RELEASE-p18
LibreSSL 2.2.2

When booting the following messages appears on console after reboot with GUI and console
![capture d ecran_2015-08-27_22-53-35](https://cloud.githubusercontent.com/assets/2040775/9532866/81262064-4d0e-11e5-98ce-998e9a9743e0.png)

This is weird because mount command does not report /mnt mounted
root@OPNsense:~ # mount
/dev/ada0s1a on / (ufs, local, noatime, soft-updates)
devfs on /dev (devfs, local, multilabel)
devfs on /var/dhcpd/dev (devfs, local, multilabel)

**Comment by fichtner** [comment]
known to happen especially with VM. not fatal, not fixable.
