### ISSUE TITLE
Firewall/Alias: "External (Advanced)" type have no where to input content

### ISSUE THREAD

**Issue by SuperMarioSF** [opnsense/core#3571]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

✔ I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

✔ I have searched the existing issues and I'm convinced that mine is new.

**Describe the bug**
I'm attempted to add some external alias but when I selected "External (Advanced)" type, the "Content" field have no way to input anything. There is only a "Clear All" button there.
No javascript warning or error shown in browser console.

**To Reproduce**
1. Go to 'Firewall/Aliases'
2. Click on add button
3. Select type to "External (Advanced)"
4. You will see there is no way to input for content.

**Expected behavior**
At least I should have something can do some input.

**Screenshots**
![Image](https://user-images.githubusercontent.com/13301406/61267373-4ab32e80-a7ca-11e9-9896-547c03c9801b.png)

**Relevant log files**
(no browser console log were ever produced.)

**Additional context**
(None)

**Environment**
OPNsense 19.1.10 (amd64, OpenSSL).
Google Chrome 75.0.3770.100 (release) (64-bit Windows) (cohort: Stable)

**Comment by mimugmail** [comment]
What do you want to achieve with it? External is for plugins like nginx.
I think what you want/need is URL Table (IP).

**Comment by SuperMarioSF** [comment]
> 
> 
> What do you want to achieve with it? External is for plugins like nginx.
> I think what you want/need is URL Table (IP).

I want to import a bunch of networks into table but there does not have anyway to direct import them. The default import need a json file, I'm currently using this way to achieve my goal.
There is no document talking about this, so I have no idea what is going on at the begining.

Sorry for the noise. This issue will be closed

**Comment by mimugmail** [comment]
Add alias, Type Network, in content field paste a csv list :)

**Comment by SuperMarioSF** [comment]
> 
> 
> Add alias, Type Network, in content field paste a csv list :)

I tried one network by line and it seems doesn't work.
I converted into json and it works well. Thanks.

**Comment by mimugmail** [comment]
csv = comma separated value, but json is also perfectly fine :)
