### ISSUE TITLE
Warning: Invalid argument supplied for foreach()

### ISSUE THREAD

**Issue by mr44er** [opnsense/core#3576]
**Describe the bug**
It is shown after upgrade from 19.1 to 19.7 above every interface on Firewall->Rules->if

**Whole error-message:**

`Warning: Invalid argument supplied for foreach() in /usr/local/opnsense/mvc/app/library/OPNsense/Firewall/Plugin.php on line 134 `

![fw](https://user-images.githubusercontent.com/46787531/61377675-f8464080-a8a3-11e9-9da2-d604914609da.png)

I don't have gateway groups at the moment configured.

**Comment by AdSchellevis** [comment]
@mr44er thanks for reporting, https://github.com/opnsense/core/commit/5dca5cc7238a84a8611becbc48623c8e4646367a should fix this.

From a console, run:

```
opnsense-patch 5dca5cc
```
