### ISSUE TITLE
"syslog_ng already running?" after bootstrap

### ISSUE THREAD

**Issue by mr44er** [opnsense/core#3577]
**Describe the bug**
Freshly installed FreeBSD 11.2-RELEASE bootstrapped to 19.7 and I see `syslog_ng already running?` in boot messages. Guess this shouldn't be.

**Screenshots**
![syslog_ng](https://user-images.githubusercontent.com/46787531/61402400-5f2f1e00-a8d3-11e9-8904-5a867b377bf5.png)

**Comment by fichtner** [comment]
Small cosmetic issue, will fix this in 19.7.x.. thanks!

**Comment by mr44er** [comment]
>cosmetic issue

Phew, good to know. ;)
