### ISSUE TITLE
Translation/MIME Version error for german language in tunables

### ISSUE THREAD

**Issue by mr44er** [opnsense/core#3578]
**Describe the bug**
Setting a tunable and leaving the description box empty when having german language set, gives 'MIME-Versin: 1.0...."

May affect other languages, too.

**Screenshots**
![tunables](https://user-images.githubusercontent.com/46787531/61402781-1d52a780-a8d4-11e9-97b0-01978c6350f0.png)

**Comment by AdSchellevis** [comment]
for some reason that seems to be the translation of an empty string, search `msgid ""` in https://raw.githubusercontent.com/opnsense/lang/master/de_DE.po to see what I mean.

could be an issue of POEditor

**Comment by mr44er** [comment]
> seems to be the translation of an empty string

Exactly!

I had this empty string/MIME bug some weeks ago in another menu. fichtner fixed it back then.

**Comment by AdSchellevis** [comment]
https://github.com/opnsense/core/commit/7738ac0bb95a75653ecb9c3487d01895fd3340ab should polish it away

**Comment by mr44er** [comment]
Works perfect, thank you!
