### ISSUE TITLE
sysctl: invalid uint64_t '512M' / tunable not recognized

### ISSUE THREAD

**Issue by mr44er** [opnsense/core#3579]
**Describe the bug**
Setting `vfs.zfs.arc_max="512M"` respectively in tunables does give error message after reboot.

Maybe it's bonded to other bug with MIME-Type?

**Screenshots**
![zfs_arc](https://user-images.githubusercontent.com/46787531/61403522-bfbf5a80-a8d5-11e9-819d-f31d763caf2c.png)

**Comment by AdSchellevis** [comment]
I don't think so, you can easily grep the tunable on disk using:
```
grep vfs.zfs.arc_max /boot/loader*
```

**Comment by mr44er** [comment]
You're right, it works.

Anyways, I looked into /boot/loader.conf and the tunable is listed under `# dynamically generated tunables settings follow`.
`vfs.zfs.arc_max` isn't _dynamic_ at all and needs reboot.

I am unsure now, if I should write it to `/boot/loader.conf.local` for purpose and clarity.

**Comment by AdSchellevis** [comment]
It's not necessarily needed, but you will see some messages when the property is read only.

**Comment by mr44er** [comment]
>you will see some messages when the property is read only

Aight then, I can live with that. :)

**Comment by AdSchellevis** [comment]
@mr44er can you please close your question if not relevant anymore?

**Comment by mr44er** [comment]
Sure, will do. Thx!
