### ISSUE TITLE
Route-based IPsec / SNAT / packets are not entering the tunnel

### ISSUE THREAD

**Issue by jroehler23** [opnsense/core#3580]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[X] I have searched the existing issues and I'm convinced that mine is new.

**Describe the bug**
After switching from a policy base IPSec to route-based IPSec the SNATed packets are not entering the tunnel. In the firewall log I can see the transformation of the packets with activated and deactivated rules. I have tried the 1to1 NAT like before and the outbound NAT. Both have the same impact on the addresses in the firewall log, but the packets are not reaching the other end of the tunnel.

**To Reproduce**
Configure an route-based IPSec connection with 0.0.0.0 <> 0.0.0.0 "policy". Try to SNAT one of networks from side A and look at the end on side B.

**Expected behavior**

**Environment**

OPNsense 19.1.10-amd64
FreeBSD 11.2-RELEASE-p10-HBSD
OpenSSL 1.0.2s 28 May 2019
--

**Comment by AdSchellevis** [comment]
just to be sure, you configured the rule on the VTI device? (not on ipsec in general)

**Comment by jroehler23** [comment]
I have tried both. The old configuration IPSec and the new vti device.

**Comment by jroehler23** [comment]
In the firewall log I can see the packet two times. First on the vti and then on the IPSec device.

**Comment by AdSchellevis** [comment]
you should configure your nat rule on the vti device, more details might help by the way (your ticket doesn't contain a lot of it, exact rule, expected result, etc). 

I'm quite sure I've tested a source nat entry quite recently.

**Comment by jroehler23** [comment]
I have a closed network at several remote locations all with network 192.168.50.0/24. The devices in this network can only comunicate with the gateway .201. They are very old and it is not possible to reconfigure them.

With DNAT the destination is changed to the communication server IP in the local network 192.168.200.15. This is working because I see the packets in the local OPNsense with a source address of the remote location, e.g. 192.168.50.101.

Now I must change the source address to an address which belongs to the location. Before I have used 1to1 NAT with this configuration:

Schnittstelle | Externe IP | Interne IP | Ziel IP | Beschreibung
IPSec | 192.168.203.201/32 | 192.168.50.0/24 | 192.168.200.0/24

Now it is the same but with "vti_test" as "Schnittstelle".

I also tried the outbound NAT with this configuration:

Schnittstelle | Quelle | Quellport | Ziel | Zielport | NAT Adresse | NAT Port | Statischer Port | Beschreibung | 
vti_test | INFO Netzwerk | * | 192.168.200.0/24 | * | LAN Adresse | * | NEIN |

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/core/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
