### ISSUE TITLE
The display for the automatically generated rules contains some errors

### ISSUE THREAD

**Issue by bewue** [opnsense/core#3581]
**Describe the bug**
The new display feature for the automatically generated rules contains some errors on my WAN interface. (DHCPv6 on WAN interface was enabled)
1. Rules 1-3 should be Protocol IPv6 not IPv4
2. With rules 4-5 the "Source" field is missing the pftables name (bogons)

The "real" rules seem to be set correctly.

**To Reproduce**
Open the display for the automatically generated rules.

**Screenshots**
![OPNsense-1](https://user-images.githubusercontent.com/38508611/61406370-0021d700-a8dc-11e9-8c97-6c084f7163e8.png)

**Environment**
OPNsense 19.7

**Comment by mr44er** [comment]
It's correct when you receive ipv6 through ipv4-connection on PPPoE to ISP.

**Comment by bewue** [comment]
@mr44er with port 546/547? ...anyway, like i said the "real" rules were IPv6 - its an display error!

**Comment by mr44er** [comment]
> with port 546/547?

Yes.

**Comment by fichtner** [comment]
Hmm, it's a litte diff between the old system using empty to mean ipv4 but "inet46" is both and in the MVC rules empty is both types and there's no "inet46". So the rules actually hit on both IPv4 and IPv6 but obviously only work for IPv6 due to the nature of the protocol it's trying to catch.

**Comment by AdSchellevis** [comment]
With the specified settings, it should look like this:
![image](https://user-images.githubusercontent.com/9783985/61435885-d8f9f280-a939-11e9-9edd-eac4486691d2.png)

(first rule has an address, and thus an ipproto, others match both)

https://github.com/opnsense/core/commit/7665d2bc7f76700bef5ee3170f2dc5186a1e1395 tries to reassemble the ipproto when not set, similar to what pf does internally.

**Comment by bewue** [comment]
What about the second issue?

> 2. With rules 4-5 the "Source" field is missing the pftables name (bogons)"

**Comment by AdSchellevis** [comment]
missed that one, we can either `htmlspecialchars()` or remove `<>` signs, I think we should display as `<bogons>` in this case. since it's not a user generated alias, we can't do anything useful with it.

**Comment by AdSchellevis** [comment]
![image](https://user-images.githubusercontent.com/9783985/61452494-28511a80-a95c-11e9-9e9b-964e9deee517.png)

**Comment by fichtner** [comment]
looks good. it could link to the diagnostics table page, but I'm not a huge fan of the idea.
