### ISSUE TITLE
Problems after Upgrade

### ISSUE THREAD

**Issue by patrick7** [opnsense/core#3585]
After upgading to 19.7 I get the following error above the firewall rule table (which is broken sometimes btw):

Warning: Invalid argument supplied for foreach() in /usr/local/opnsense/mvc/app/library/OPNsense/Firewall/Plugin.php on line 134

Also see: https://forum.opnsense.org/index.php?topic=13512.0

**Comment by AdSchellevis** [comment]
duplicate of https://github.com/opnsense/core/issues/3576
