### ISSUE TITLE
squid crashing

### ISSUE THREAD

**Issue by fabianfrz** [opnsense/core#3590]
**Describe the bug**

squid is crashing and the following error is logged:

nter an option: pid 45066 (squid), uid 100: exited on signal 6 (core dumped)
[HBSD SEGVGUARD] [squid (45066)] Suspension expired.
 -> pid: 45066 ppid: 10036 p_pax: 0xa50<SEGVGUARD,ASLR,NOSHLIBRANDOM,NODISALLOWMAP32BIT>

**To Reproduce**

boot opnsense 19.7

**Expected behavior**

squid should run flawlessly

**Screenshots**

![grafik](https://user-images.githubusercontent.com/3713914/61578761-e1019000-aafb-11e9-8eb4-0be454124065.png)

**Relevant log files**
If applicable, information from log files supporting your claim.

none

**Additional context**

* Upgraded appliance from 19.1.x
* APU 1d4

**Environment**
Software version used and hardware type if relevant.
e.g.:

OPNsense 19.7 (amd64/LibreSSL)

From Syslog:
```
CPU: AMD G-T40E Processor (1000.02-MHz K8-class CPU)
Origin="AuthenticAMD"  Id=0x500f20  Family=0x14  Model=0x2  Stepping=0
Features=0x178bfbff<FPU,VME,DE,PSE,TSC,MSR,PAE,MCE,CX8,APIC,SEP,MTRR,PGE,MCA,CMOV,PAT,PSE36,CLFLUSH,MMX,FXSR,SSE,SSE2,HTT>
Features2=0x802209<SSE3,MON,SSSE3,CX16,POPCNT>
AMD Features=0x2e500800<SYSCALL,NX,MMX+,FFXSR,Page1GB,RDTSCP,LM>
AMD Features2=0x35ff<LAHF,CMP,SVM,ExtAPIC,CR8,ABM,SSE4A,MAS,Prefetch,IBS,SKINIT,WDT>
SVM: NP,NRIP,NAsids=8
TSC: P-state invariant, performance statistics
real memory  = 4815060992 (4592 MB)
avail memory = 4068708352 (3880 MB)
```

**Comment by mimugmail** [comment]
Did you reset via support Tab?

**Comment by fabianfrz** [comment]
I'll give it a try tomorrow

**Comment by fabianfrz** [comment]
seems like that or the reboot fixed it.
