### ISSUE TITLE
Firewall rules for DHCPv6 server are autogenerated even if server is disabled

### ISSUE THREAD

**Issue by maurice-w** [opnsense/core#3591]
[x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
[x] I have searched the existing issues and I'm convinced that mine is new.

**Describe the bug**
"Allow access to DHCPv6 server" firewall rules are autogenerated for all tracking IPv6 interfaces, even if the DHCPv6 server is disabled.

**To Reproduce**
1. Create two LAN interfaces, set their IPv6 configuration type to 'Track Interface' and enable manual configuration ('Allow manual adjustment of DHCPv6 and Router Advertisements') for both of them.
2. Go to 'Services' / 'DHCPv6', enable the DHCPv6 server on one of the interfaces and disable it on the other.
3. Go to 'Firewall' / 'Rules' and check the rules for both interfaces.
4. You'll see that "allow access to DHCPv6 server" rules have been autogenerated for both interfaces.

**Expected behavior**
"Allow access to DHCPv6 server" firewall rules should only be autogenerated for interfaces on which the DHCPv6 server is enabled.

**Additional context**
This bug might or might not have been around for a while. I just noticed it in 19.7 because autogenerated firewall rules are now visible in the UI.
It seems to be specific to _tracking_ interfaces (works correctly on interfaces with a _static_ IPv6 configuration).

**Environment**
OPNsense 19.7 (amd64, OpenSSL)
Hyper-V Generation 2 VM

**Comment by AdSchellevis** [comment]
@maurice-w the rules for track have been around for quite some time https://github.com/pfsense/pfsense/commit/f9eb5ebb334675e0b4d83c5cbee92efd6178ffd4 . It doesn't look very logical to open these ports when DHCPv6 isn't active on the interface indeed

**Comment by AdSchellevis** [comment]
@maurice-w https://github.com/opnsense/core/commit/cb786592df2bbdc5a7adb710bc612037a5099658 should fix it, it looks like the same applied for dhcrelay6 (added while not active)

**Comment by AdSchellevis** [comment]
After talking to @fichtner it seems that we do need these ports for track interfaces, as dhcpv6 is enabled automatically:

https://github.com/opnsense/core/blob/cb786592df2bbdc5a7adb710bc612037a5099658/src/etc/inc/plugins.inc.d/dhcpd.inc#L1238-L1343

Let's keep the relayd fix and revert the other part.
