### ISSUE TITLE
Small fix: correct swapinfo in WEBIF on ZFS mirror

### ISSUE THREAD

**Issue by mr44er** [opnsense/core#3592]
[X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[X] I have searched the existing issues and I'm convinced that mine is new.

**Describe the bug**
Bootstrapped install (FreeBSD 11.2-RELEASE to OPNsense 19.7) on ZFS mirror doesn't show whole swapsize in WEBIF.

**To Reproduce**
If you create a zfs mirror and set a swap partition on both disk, after the bootstrap process the WEBIF does only show half the size or only one disk, I don't know the detection code.

**Expected behavior**
In my case it should show 4GB of swap instead of 2GB.

**Screenshots**
![swapinfo](https://user-images.githubusercontent.com/46787531/61593892-c86da480-abe5-11e9-9ba4-75b4c560de6b.png)
`top`
![top](https://user-images.githubusercontent.com/46787531/61593936-4f228180-abe6-11e9-94ea-c51aba28b0eb.png)

![webinterface](https://user-images.githubusercontent.com/46787531/61593893-c86da480-abe5-11e9-87bd-52251af4c314.png)

**Comment by mr44er** [comment]
Sorry for dumb question, but do I understand the 'incomplete'-label correctly, that I delivered not enough information?

**Comment by AdSchellevis** [comment]
`incomplete` means not using formal templates, which we kindly ask anyone to use to ease processing.

**Comment by mr44er** [comment]
Alright and thx for enlightening, will do in future. :)

**Comment by fichtner** [comment]
@mr44er thanks for the report! it would only show the last swap, with patch now it shows both as merging is probably more obscure
