### ISSUE TITLE
PHP warning

### ISSUE THREAD

**Issue by fichtner** [opnsense/core#3593]
Warning: Invalid argument supplied for foreach() in /usr/local/opnsense/mvc/app/library/OPNsense/Firewall/Plugin.php on line 134

You'd know better how to fix... :)

**Comment by AdSchellevis** [comment]
should be https://github.com/opnsense/core/issues/3576, can you try https://github.com/opnsense/core/commit/5dca5cc7238a84a8611becbc48623c8e4646367a ?

**Comment by fichtner** [comment]
Right ok, I'll ask in the forum where I got this from :)
