### ISSUE TITLE
Firewall: manage egress rules per interface

### ISSUE THREAD

**Issue by AdSchellevis** [opnsense/core#3594]
Currently the direction of the traffic can only be chosen in floating rules, but in some scenario's it's much easier to create outbound rules (only inbound is supported now).

When using a lot of interfaces, which should all be allowed to access devices on one specific interface, this would save quite some rules and is easier to track for the administrator.

This FR should add direction as on option and while already changing these pages, also allow to create "non quick" rules on interfaces. 
Functionally the "regular" rules would be more aligned with the "floating" rules as we have now, with the exception that you can't add multiple interfaces in a normal rule due to the inability to reorder a single rule in multiple rulesets (rules are positional).

Considerations while adding this:

- Validate if "policy based routing" is used for outbound rules, since this is not compatible
- Mark outbound rules in the overview grid
- Mark non-quick rules in the overview grid 

--------
Test current status (including relevant commits in master) on 19.7.1:
```
pkg install -f opnsense
opnsense-patch f8d5c01 534f3c8 4d9026e 649e7b1 179798d f11da62
```

**Comment by mimugmail** [comment]
So for a LAN rule you have a dropdown for outgoing interface and rule logic is still inbound? Outbound should be multi select for multi wan setups. Just a quick thought

**Comment by AdSchellevis** [comment]
@mimugmail no, this is just about the `in`/`out` part of the rule, pf doesn't support in / out interfaces per rule (as ipfw does)

Specifically, these will become available in per interface rules:
![image](https://user-images.githubusercontent.com/9783985/61810353-61e3c300-ae3f-11e9-8628-39aafbbf8414.png)
![image](https://user-images.githubusercontent.com/9783985/61810378-6b6d2b00-ae3f-11e9-8be2-bd2585569c07.png)

**Comment by fichtner** [comment]
I would like to see in/out, but not any for the same policy routing fail reason. People won't understand this worst case.

**Comment by mimugmail** [comment]
This issue is based in the wishes from wowas in IRC, correct?

**Comment by AdSchellevis** [comment]
no, one of our clients. For traceability I made sure there's an issue to refer in future commits.

**Comment by AdSchellevis** [comment]
note to self: missed a rule in our overview while debugging this (https://github.com/opnsense/core/commit/f8d5c01a6f4ab2ef307324acd4711cd76e005827)
