### ISSUE TITLE
Failed to get first DHCP lease hostname in ARP list

### ISSUE THREAD

**Issue by leonardorufino** [opnsense/core#3595]
Introduction:
I have some MAC addresses and I need to figure out their IP addresses for traffic shaping purposes.
Since there is no OPNsense API call to get the DHCP leases, I am using the ARP list (api/diagnostics/interface/getArp) to convert MAC to IP address.
However when the IP changes for a MAC address, I have more than one row in ARP list for the same MAC address (each one with a different IP address).
As there is no time information in each row from ARP list and the list is not ordered, the way I found to find out the current IP for a specific MAC is to check the hostname field in each row in ARP list, since the hostname will be present only for active leases (old IP addresses will have empty hostname in ARP list).

Bug:
In _src/opnsense/scripts/interfaces/list_arp.py_ (lines 40 to 49), the parsing of _/var/dhcpd/var/db/dhcpd.leases_ does not seem right.
Since my _/var/dhcpd/var/db/dhcpd.leases_ has same comments and info at the beginning, the first lease fails to parse and its hostname is not populated in ARP list.
Here is my _/var/dhcpd/var/db/dhcpd.leases_ file:

```
root@OPNsense:~ # cat /var/dhcpd/var/db/dhcpd.leases
# The format of this file is documented in the dhcpd.leases(5) manual page.
# This lease file was written by isc-dhcp-4.4.1

# authoring-byte-order entry is generated, DO NOT DELETE
authoring-byte-order little-endian;

server-duid (...)

lease 10.0.0.17 {
  (...)
}
lease 10.0.0.18 {
  (...)
}
```

The line **if lease.strip().find('lease') == 0 and lease.find('{') > -1:** in _src/opnsense/scripts/interfaces/list_arp.py_ gets the word lease in position 53 (middle of the comment in first line) and the symbol "{" in position 293.
Since 53 != 0, the first lease is ignored and the ARP list only shows the hostname for IP 10.0.0.18.
The expected behavior would be for the ARP list to show the hostname for both IP addresses: 10.0.0.17 and 10.0.0.18.

**Comment by AdSchellevis** [comment]
@leonardorufino https://github.com/opnsense/core/commit/3a0b9e1620c7fa03bb645f78d2a248bd99d0caf2 should do the trick

**Comment by leonardorufino** [comment]
3a0b9e1 solved the issue.
Thank you.

**Comment by leonardorufino** [comment]
3a0b9e1 solved the issue for that _/var/dhcpd/var/db/dhcpd.leases_ file I mentioned, but I still see the bug when there are non-lease lines between leases. Please check _server-duid_ below:

```
root@OPNsense:~ # cat /var/dhcpd/var/db/dhcpd.leases
# The format of this file is documented in the dhcpd.leases(5) manual page.
# This lease file was written by isc-dhcp-4.4.1

# authoring-byte-order entry is generated, DO NOT DELETE
authoring-byte-order little-endian;

lease 10.0.0.4 {
  (...)
}
server-duid (...);

lease 10.0.0.24 {
  (...)
}
```

**Comment by AdSchellevis** [comment]
@leonardorufino you're right, this was too easy. I kind of forgot we already had a proper lease reader, https://github.com/opnsense/core/commit/eb0e73607e13cb2c9c399fc53b72706fad835352 implements the same thing we use for unbound.

**Comment by leonardorufino** [comment]
Using this DHCP reader looks good.
However you need to change line 66 from
`record['hostname'] = dhcp_leases[record['ip']]['hostname']`
to
`record['hostname'] = dhcp_leases[record['ip']]`
since you removed the _hostname_ dict key from _dhcp_leases[ip]_.

**Comment by AdSchellevis** [comment]
@leonardorufino oops, totally forgot the hostname clause https://github.com/opnsense/core/commit/f5c2f7760bccf452e46b4254face61ab2da6b030.

**Comment by leonardorufino** [comment]
No problem.
Thank you.
