### ISSUE TITLE
Can't create outbound NAT with PPPoE Interface as NAT target

### ISSUE THREAD

**Issue by DerEnderKeks** [opnsense/core#3596]
**Describe the bug**
When I try to create an outbound NAT rule with my PPPoE WAN interface (`WAN address`) as `Translation / target` I get the following error message:

```
The following input errors were detected:
- A valid target IP address must be specified.
```

**To Reproduce**
1. Go to `Firewall ‣ NAT ‣ Outbound`
2. Click on `Add`
3. Set the following options (defaults omitted):
```
Interface: WireGuard (or any other interface)
Source address: WireGuard net (or any other net)
Destination invert: true
Destination address: RFC1918 (alias for private ips)
Translation / target: WAN address
```
4. Click on `Save`

**Expected behavior**
The rule should be created like when I select any other interface as target.

**Screenshots**
<details>
 <summary>
Error Message + Settings
</summary>

![nat_error](https://user-images.githubusercontent.com/12559640/61863610-3d83f700-aed0-11e9-9be4-03bc4c99ebb4.png)

</details>

**Additional context**
Possibly related to #400 as it describes the exact same issue (but is closed since a long time).

**Environment**
OPNsense 19.7 (amd64, LibreSSL)

**Comment by AdSchellevis** [comment]
@DerEnderKeks can you post a screenshot of the selection list? `XXX address` should only be visible for static configured interfaces.

https://github.com/opnsense/core/blob/64c4d89b9dd99b9041f0984bec39ed76ed9dc978/src/www/firewall_nat_out_edit.php#L42-L46

**Comment by DerEnderKeks** [comment]
Sure:
![KZspTQYF](https://user-images.githubusercontent.com/12559640/61865888-60b0a580-aed4-11e9-9c53-1a785492f3ca.png)
![BsH37-nj](https://user-images.githubusercontent.com/12559640/61865891-61e1d280-aed4-11e9-807c-58807309ebd2.png)

**Comment by AdSchellevis** [comment]
can you share the interface page as well? (without addresses / usernames, etc, etc)

**Comment by DerEnderKeks** [comment]
![vZMYEkD_](https://user-images.githubusercontent.com/12559640/61868362-87bda600-aed9-11e9-91ef-06248b6ce165.png)
![d3cYC3WU](https://user-images.githubusercontent.com/12559640/61868365-88eed300-aed9-11e9-869b-4aa37c81c5c2.png)

**Comment by AdSchellevis** [comment]
ok, thanks, it shouldn't display wan in the outbound rules, "Interface address" can be used instead.

**Comment by DerEnderKeks** [comment]
So if I select `Interface address` it will also translate to the WAN address if it routes something over it?

**Comment by AdSchellevis** [comment]
interface address will translate to the first address of the physical interface (in pf terms `XXXX:0`), which in your case is the same as wan on the wan interface.

**Comment by DerEnderKeks** [comment]
I'm sorry, but I don't think I understand quite yet.
Why is the address of the WAN interface the one it would pick out of the multiple interfaces (including VLANs) I have? In my setup there is only one physical interface which itself has no address as everything is in VLANs (even the WAN, it's actually just a PPPoE device on the VLAN9 interface).

**Comment by AdSchellevis** [comment]
usually you want to be able to access the internet from some (or any) of the attached networks, which would mean that you need to nat on the interface where the traffic is leaving (usually wan).

**Comment by DerEnderKeks** [comment]
Ok, I just figured out what was wrong in my setup.
In the NAT rule I selected the Wireguard (and not the WAN) interface. That's why I was so confused with what you meant. But it all makes sense now and works fine.
Thanks for your help anyway!
