### ISSUE TITLE
Add an option to Gateways to don't force setting default route when only one GW is available

### ISSUE THREAD

**Issue by mimugmail** [opnsense/core#3597]
[X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[X] I have searched the existing issues and I'm convinced that mine is new.

As discussed with @AdSchellevis one of my clients uses FRR and receives a default gateway via it's provider (via BGP protocol). For internal routing client uses static routes so he has to add a gateway. Also when "Upstream Gateway" is unticked, OPNsense still sets a default gateway pointing to it (the internal one). 

Maybe an additonal checkbox or something would be nice to disable this feature as local routes always have a higher administrative distance than dynamic learned ones

**Describe alternatives you've considered**
Alternative would be to add static route management via FRR plugin which we already considered some months ago (should a be ticket in plugins repo)

**Comment by AdSchellevis** [comment]
@mimugmail as we discussed this briefly on irc, it was my understanding that you want the option to disable the creation of the default gateway (so if set, no default is created). Or did I misunderstood?

**Comment by mimugmail** [comment]
@AdSchellevis correct, I updated the text a bit. 
In sum, if you have a gateway, it is used as default gateway and this should be configurable. :)
Thanks!

**Comment by AdSchellevis** [comment]
@mimugmail I'm looking at this issue again, I'm a little bit in doubt if we should do anything new here. We already have a checkbox named `Mark Gateway as Down` , which now only works for groups. wouldn't it be more logical if down really means down, so not available for routing at all? Adding more knobs might be more confusing, to be honest, I wouldn't know why it should be down in a group but still would be a valid target for your default route.

If we change this, we should probably wait for 20.1 since it changes behaviour (a bit)

**Comment by mimugmail** [comment]
No problem to wait for 20.1 
Imagine, OPNsense a ISP edge router usually uses BGP to receive routes, so it doesn't make sense to have a default route (when having multiple upstreams). So far so good. 

Now, imagine you have some kind of management LAN and want to set a route there. Routes can only be set with a gateway. So you create a gateway for an internal resource and point the route to it, e.g. route 10.2.1.0/24 via gateway 10.1.1.1.  So far so good. :)

But now, there is some kind of check routine, that when you have one gateway, no matter if it's used as default or whatever, this gateway is treated as default. So in upper case the default gateway for this ISP router would be the internal resource. 

I'm not sure if marking a gateway as down works when you also use it for static routes?

**Comment by AdSchellevis** [comment]
We should be able to keep the static routes as is and only influence the default gateway, if we just add a condition here :

https://github.com/opnsense/core/blob/612cdd511807e7f4c807d18cb4d07096abd6f9ff/src/opnsense/mvc/app/library/OPNsense/Routing/Gateways.php#L292


In which case `disabled` means, not being used at all (including static) and `Mark Gateway as Down` means not being considered within automatic gateways (either group or default).

Partly this already is the case when using default gateway switching, this 
https://github.com/opnsense/core/blob/c5b41f098eed2727cab8f14afb2d8463b66bcb1c/src/etc/inc/filter.inc#L299

will exclude force_down, but the default configure defined here 
https://github.com/opnsense/core/blob/548932a71a3755050e3767050afe90dc0782c836/src/etc/inc/system.inc#L467

Doesn't follow the same logic. So in my opinion we would make it more consistent when changing this.

**Comment by mimugmail** [comment]
Closed via 64fd58d
