### ISSUE TITLE
System/Settings/General DNS gateway setting not saved

### ISSUE THREAD

**Issue by AdSchellevis** [opnsense/core#3599]
When changing a  gateway in the DNS settings, it always seems to fall back to "none" after save on OPNsense 19.7[.1]

**Comment by AdSchellevis** [comment]
to install on OPNsense 19.7.1 :
```
opnsense-patch c94c09e
```

**Comment by cmb991** [comment]
I applied the patch and its not showing new gateways added for other wan interfaces.

![Gateway on Dashboard](https://user-images.githubusercontent.com/30929454/62014350-f024b580-b16d-11e9-9440-801d113c0b84.PNG)
![Gateways](https://user-images.githubusercontent.com/30929454/62014352-f7e45a00-b16d-11e9-969e-77abc7c578d4.PNG)

**Comment by AdSchellevis** [comment]
the monitoring services aren't related to dns gateway settings, which is what this issue is about
