### ISSUE TITLE
LDAP groups not mapped.

### ISSUE THREAD

**Issue by kmohan1985** [opnsense/core#360]
I tried to map the LDAP groups to grant access the opnsense. AD Authentication accepted but no groups were displayed. 

User: XXXXX  authenticated successfully.
This user is a member of these groups: 

I added groups called opnsense. and also make a member as the group. But doesn't work.

**Comment by AdSchellevis** [comment]
OPNsense doesn't map remote ldap groups, you can import users and manage the groups in OPNsense from the user manager.
There's a button at the right corner of the user manager to import users.
At the moment there's no sync option for groups.

For more information about the design choice, see https://github.com/opnsense/core/issues/266

**Comment by kmohan1985** [comment]
Thank you so Much. Appriciated !!!

**Comment by Flos** [comment]
I currently switching from pfsense to opnsense. I can't find anything good behind the new LDAP behaviour in opnsense. I also don't see the import user option, I can only add a user.  

```
OPNsense 16.1.8-amd64	
FreeBSD 10.2-RELEASE-p14	
OpenSSL 1.0.2g 1 Mar 2016
```

The group mapping was a nice and powerfull feature. Now I have to import and create the users, I have  to assign the rights by creating groups, and assigning these groups again to the users. Even when they are in the AD already a member of that group. If I get a new IT-Admin I have to remember that I have to add him also in opnsense, not only in AD. If every application does it like this It will be a mess to maintain the application pool.

**Comment by fenderle** [comment]
I too don't see a button and would really prefer group mapping. Just my 5 cents.
