### ISSUE TITLE
Intrusion detection log: Is this a bug or safe to ignore

### ISSUE THREAD

**Issue by marjohn56** [opnsense/core#3602]
`suricata[4994]: [100247] <Error> -- [ERRCODE: SC_ERR_INVALID_SIGNATURE(39)] - error parsing signature "alert smb any any -> $DC_SERVERS 445 (msg: "ATTACK AD [PTsecurity] Possible MS-RPRN abuse. Hash or Ticket theft"; flow: to_server, established, no_stream; content:"SMB"; offset: 5; depth: 3; content: "|05 00 00|"; distance: 0; content: "|41 00|"; distance: 19; within: 2; content: "|00 01 00 00|"; distance: 36; within: 4; content: "|5C 00 5C 00|"; fast_pattern; distance: 0; flowbits: isset, DCERPC.BIND.SPOOLSS; reference: url, posts.specterops.io/not-a-security-boundary-breaking-forest-trusts-cd125829518d; reference: url, github.com/ptresearch/AttackDetection; metadata: Open Ptsecurity.com ruleset; classtype: attempted-recon; sid: 10004153; rev: 1;)" from file /usr/local/etc/suricata/opnsense.rules/pt.research.rules at line 271`

suricata[4994]: [100247] <Error> -- [ERRCODE: SC_ERR_UNDEFINED_VAR(101)] - Variable "DC_SERVERS" is not defined in configuration file

19.7.1
Qotom i5

**Comment by AdSchellevis** [comment]
Hi Martin, 

You can disable the rule, it belongs to the pt.research rules, see https://github.com/opnsense/plugins/issues/577

Best regards,

Ad

**Comment by marjohn56** [comment]
Ah, OK... would this help you to nail it?

https://github.com/ptresearch/AttackDetection/issues/8

**Comment by AdSchellevis** [comment]
@marjohn56 I kind of added the plugin a long time ago as an example of how to add a ruleset, it's not really a core issue that they require other settings now. Since the ruleset may only be used in non-commercial setups, I'm not a user of it myself.

**Comment by marjohn56** [comment]
Not a problem, but useful for others to know. Easy to fix if they follow the instructions.
