### ISSUE TITLE
WebProxy (squid) SSL inspection only works in transparent mode

### ISSUE THREAD

**Issue by vistalba** [opnsense/core#3603]
**Describe the bug**
I've activated web proxy on opnsense 19.7.1 and it works fine in transparent mode.
http on port 3128
https on port 3129

If I disable transparent mode and configure the proxy directly in e.g. Firefox only http is working. All https websites can't load.

I tested with telnet also... 3128 is working but 3129 isn't.
If I activate the NAT-Rule for transparent mode, also https sites are working over squid with SSL inspection.

**To Reproduce**

1, activate web proxy with SSL inspection
2. activate transparent mode for http and https traffic
3. add fw and nat rule for http/https to redirect to transparent squid
4. check squid is working for http and https traffic (check certificate on https because of the SSL inspection)
5. disable NAT rules
6. configure squid proxy manually in e.g. firefox http=tcp3128 and https=3129
7. try to reguest http/https sites
8. check listener e.g. with telnet (3128 and 3129). -> for 3129 there is no listener.

**Expected behavior**
@step 7 http and https should work with SSL inspection.

**Environment**
ESX 6.7
OPNsense 19.7.1-amd64
FreeBSD 11.2-RELEASE-p11-HBSD
OpenSSL 1.0.2s 28 May 2019

**Comment by AdSchellevis** [comment]
sslbump is only for transparent mode, your browser will use `connect` to access tls sites over the same 3128 port.

https://en.wikipedia.org/wiki/HTTP_tunnel

**Comment by vistalba** [comment]
@AdSchellevis 

Okay, just to clarify:

If `sslbump` is active in transparent mode 3128 is used for http and 3129 for https (like in the NAT rules).
If I configure the proxy e.g. in Firefox I've to use 3128 for http `AND` https? Is `sslbump` in this case working too?

**Comment by AdSchellevis** [comment]
If I'm reading the generated configuration correctly, bump is also enabled when requested on 3128 in your case.

`/usr/local/etc/squid/squid.conf` contains a line like:

```
http_port xxx.xxx.xxxx.xxx:3128  ssl-bump cert=/var/squid/ssl/ca.pem dynamic_cert_mem_cache_size=10MB generate-host-certificates=on
```

Most use this transparent as far as I know.

**Comment by vistalba** [comment]
@AdSchellevis Tried on my system... look as it would work as expected.

It is like this:

tcp3128 - transparent for http. + Use this when config a proxy manually for http AND https
tcp3129 - us this only for transparent https

**Comment by AdSchellevis** [comment]
case close then?

**Comment by vistalba** [comment]
Yes, I think it's okay.

Just one strange thing I mentioned.
SSL bump is working well in Firefox on Win10 and also on my iPhone if I use Google Chrome/Safari (cert is installed). But it desn't work when I use iOS Apps. (e.g. Tripadvisor isn't able to connect to api.tripadvisor.com and with browser it's working)

**Comment by mimugmail** [comment]
Most apps use certificate pinning, you'll see that most of them wont work (Twitter, News etc.)

**Comment by vistalba** [comment]
@mimugmail Yes, I guess this is the problem. How can I find the right domains to exclude them. The log often only shows IP addresses. :(

**Comment by mimugmail** [comment]
I gave up on this as the exclude list is not easy to handle with more than 50

**Comment by vistalba** [comment]
@mimugmail I just think about use a different VLAN for iOS/Android Clients over wifi without `ssl bump`. I just want to do this because of the clamav/icap solution. But if I've to except every domain used by iOS-Apps for multiple devices (in office environment) this isn't maintainable. 

Is there a way... to enable `ssl bump` but just for some of the interfaces?

As I see I can just select an interface and then use NAT to bring traffic to it. (transparent mode).
What I want is to activate "Log SNI information only" just for some of the interfaces ... other should use `ssl bump`.

**Comment by elliotclee** [comment]
I know this is an old issue, but since I was trying to accomplish something similar to some of this stuff:

The solution is to generate a wpad.dat file with code that sends the client to proxy port 3128 if the requested url is http:// and to proxy port 3129 if the requested url is https:// .

A UI workaround is to disable the 'SSL inspection' checkbox in the web GUI if transparent proxy is not checked...
