### ISSUE TITLE
Gateway Display GUI not showing all added gateways

### ISSUE THREAD

**Issue by nivek1612** [opnsense/core#3607]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[X] I have searched the existing issues and I'm convinced that mine is new.

**Describe the bug**
From from GUI add a gateway. It does not appear in the list of gateways. Tried a few times same results. 

**To Reproduce**
1. Go to System: Gatways
2. Click on add gateway
3. Add revelant gateway data
4. Click save/apply

**Expected behavior**

**Screenshots**
Gateway GUI after adding the gateways

![Screenshot 2019-07-28 at 08 13 38](https://user-images.githubusercontent.com/23481092/62006950-b1631100-b115-11e9-9c33-4fa42ab2027b.png)

**Relevant log files**

Extract of config.xml shows all added gateways

![Screenshot 2019-07-28 at 08 26 41](https://user-images.githubusercontent.com/23481092/62006963-ca6bc200-b115-11e9-8f22-109605b77013.png)

![Screenshot 2019-07-28 at 08 26 56](https://user-images.githubusercontent.com/23481092/62006952-b58f2e80-b115-11e9-97c7-82ed8c8307ae.png)

**Additional context**
None

**Environment**
OPNsense 19.7.1 (amd64, OpenSSL).

**Comment by nivek1612** [comment]
I added a couple of new gateways using the GUI. It did not appear. I tried again but still no gateway appeared. However dpinger was showing the gateway as being monitored as I had added a monitor ip. I then checked the config.xml. All the gateways I added where there see code below

`<gateways>
    <gateway_item>
      <interface>wan</interface>
      <gateway>dynamic</gateway>
      <name>WAN_PPPOE</name>
      <weight>1</weight>
      <ipprotocol>inet</ipprotocol>
      <interval/>
      <descr>Interface WAN_PPPOE Gateway</descr>
      <avg_delay_samples/>
      <avg_loss_samples/>
      <avg_loss_delay_samples/>
      <monitor>8.8.8.8</monitor>
      <defaultgw>1</defaultgw>
    </gateway_item>
    <gateway_item>
      <interface>wan</interface>
      <gateway>2a02:8011:d000:22e::1</gateway>
      <name>GWv6</name>
      <priority>255</priority>
      <weight>1</weight>
      <ipprotocol>inet6</ipprotocol>
      <interval/>
      <descr>WAN IPv6</descr>
      <monitor>2001:4860:4860::8888</monitor>
    </gateway_item>
    <gateway_item>
      <interface>opt6</interface>
      <gateway>dynamic</gateway>
      <name>WAN_GW</name>
      <priority>254</priority>
      <weight>1</weight>
      <ipprotocol>inet6</ipprotocol>
      <interval/>
      <descr>Interface WAN_GW Gateway</descr>
      <monitor>2001:4860:4860::8844</monitor>
      <defaultgw>1</defaultgw>
    </gateway_item>
    <gateway_item>
      <interface>wan</interface>
      <gateway>dynamic</gateway>
      <name>TEST</name>
      <priority>255</priority>
      <weight>1</weight>
      <ipprotocol>inet</ipprotocol>
      <interval/>
      <descr/>
      <monitor_disable>1</monitor_disable>
    </gateway_item>
    <gateway_item>
      <interface>opt6</interface>
      <gateway>dynamic</gateway>
      <name>4G_WAN</name>
      <priority>255</priority>
      <weight>1</weight>
      <ipprotocol>inet</ipprotocol>
      <interval/>
      <descr/>
      <monitor_disable>1</monitor_disable>
    </gateway_item>
    <gateway_item>
      <interface>opt6</interface>
      <gateway>dynamic</gateway>
      <name>4G_WAN</name>
      <priority>255</priority>
      <weight>1</weight>
      <ipprotocol>inet</ipprotocol>
      <interval/>
      <descr/>
      <monitor_disable>1</monitor_disable>
    </gateway_item>
    <gateway_item>
      <interface>wan</interface>
      <gateway>dynamic</gateway>
      <name>4G_WAN</name>
      <priority>255</priority>
      <weight>1</weight>
      <ipprotocol>inet</ipprotocol>
      <interval/>
      <descr/>
      <monitor_disable>1</monitor_disable>
    </gateway_item>
  </gateways>`

but the GUI is only showing the first two

![Screenshot 2019-07-28 at 08 13 38](https://user-images.githubusercontent.com/23481092/62006614-e882f380-b110-11e9-87ca-f444e57ac8d4.png)

**Comment by AdSchellevis** [comment]
@nivek1612 can you please fill in the template In stead of dumping our questions?

**Comment by nivek1612** [comment]
@AdSchellevis sorry had just landed in the US after a long flight so was not paying attention

Hope format is ok now

**Comment by AdSchellevis** [comment]
most of the non showing ones don't seem to be functional, right? since 19.7 we only show valid gateways, multiple "dynamic" gateways on the same interface don't do anything.  I figure that the opt6 isn't functional yet, kind of looks similar to https://github.com/opnsense/core/issues/3604

**Comment by nivek1612** [comment]
Ok so that makes some sense but the fact that if you create "bad' gateway it is left in the config.xml with no way to edit seems a little strange. How about an option to 'Display inactive gateways' so that at least we can remove them

**Comment by AdSchellevis** [comment]
We could show inactive to some extend, but since the old system allowed creating overlapping items, there could still be items in the config that aren't visible.
The "dynamic" items are unique per interface, which doesn't seem to be the case in your config (which would require deleting "the same" item multiple times).

**Comment by nivek1612** [comment]
Ok I'll tidy up the config.xml manually then reload it. Hopefully that will tied me over.
