### ISSUE TITLE
WebProxy access_log to remote syslog

### ISSUE THREAD

**Issue by vistalba** [opnsense/core#3609]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I always used the following to forward my access_log to splunk: `access_log udp://192.168.4.63:514`

Add solution to specify custom options or add it as a specific setting as log option (just to specify ip, port and protocol udp/tcp)

**Comment by AdSchellevis** [comment]
@vistalba you should already be able to do so, choose syslog
![image](https://user-images.githubusercontent.com/9783985/62034352-286bd880-b1ee-11e9-8234-c1ed81542428.png)
Goto syslog targets:
![image](https://user-images.githubusercontent.com/9783985/62034779-e8f1bc00-b1ee-11e9-8f29-68acac923eda.png)
And filter your log traffic:
![image](https://user-images.githubusercontent.com/9783985/62034761-e2fbdb00-b1ee-11e9-8647-41fe0c1d69e7.png)

**Comment by vistalba** [comment]
Thanks... didn't get that point that the Application is named "squid" in "Logs/Targets" and "WebProxy" in WebGUI.
