### ISSUE TITLE
PHP error when logging into dashboard.

### ISSUE THREAD

**Issue by jsbsmd** [opnsense/core#3613]
This error does not seem to disrupt the functionality but when logging into the dashboard, it always comes up.

information:

OPNsense 19.7.1-amd64
FreeBSD 11.2-RELEASE-p11-HBSD
OpenSSL 1.0.2s 28 May 2019

**System Information:**

User-Agent Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0
FreeBSD 11.2-RELEASE-p11-HBSD  ab3b8b47944(stable/19.7) amd64
OPNsense 19.7.1 b0b59da08
Plugins os-dyndns-1.16_1 os-ntopng-1.2 os-redis-1.1 os-smart-2.0 
Time Mon, 29 Jul 2019 13:52:19 -0400
OpenSSL 1.0.2s  28 May 2019
PHP 7.2.20

**PHP Errors:**

[28-Jul-2019 01:01:41 America/Toronto] PHP Fatal error:  Uncaught Google_IO_Exception: Operation timed out after 100001 milliseconds with 0 bytes received in /usr/local/opnsense/contrib/google-api-php-client/Google/IO/Curl.php:115
Stack trace:
#0 /usr/local/opnsense/contrib/google-api-php-client/Google/IO/Abstract.php(136): Google_IO_Curl->executeRequest(Object(Google_Http_Request))
#1 /usr/local/opnsense/contrib/google-api-php-client/Google/Http/REST.php(60): Google_IO_Abstract->makeRequest(Object(Google_Http_Request))
#2 /usr/local/opnsense/contrib/google-api-php-client/Google/Task/Runner.php(174): Google_Http_REST::doExecute(Object(Google_Client), Object(Google_Http_Request))
#3 /usr/local/opnsense/contrib/google-api-php-client/Google/Http/REST.php(46): Google_Task_Runner->run()
#4 /usr/local/opnsense/contrib/google-api-php-client/Google/Client.php(590): Google_Http_REST::execute(Object(Google_Client), Object(Google_Http_Request))
#5 /usr/local/opnsense/contrib/google-api-php-client/Google/Service/Resource.php(231): Google_Client->execute(Object(Google_Http_Requ in /usr/local/opnsense/contrib/google-api-php-client/Google/IO/Curl.php on line 115
[29-Jul-2019 01:01:41 America/Toronto] PHP Fatal error:  Uncaught Google_IO_Exception: Operation timed out after 100000 milliseconds with 0 bytes received in /usr/local/opnsense/contrib/google-api-php-client/Google/IO/Curl.php:115
Stack trace:
#0 /usr/local/opnsense/contrib/google-api-php-client/Google/IO/Abstract.php(136): Google_IO_Curl->executeRequest(Object(Google_Http_Request))
#1 /usr/local/opnsense/contrib/google-api-php-client/Google/Http/REST.php(60): Google_IO_Abstract->makeRequest(Object(Google_Http_Request))
#2 /usr/local/opnsense/contrib/google-api-php-client/Google/Task/Runner.php(174): Google_Http_REST::doExecute(Object(Google_Client), Object(Google_Http_Request))
#3 /usr/local/opnsense/contrib/google-api-php-client/Google/Http/REST.php(46): Google_Task_Runner->run()
#4 /usr/local/opnsense/contrib/google-api-php-client/Google/Client.php(590): Google_Http_REST::execute(Object(Google_Client), Object(Google_Http_Request))
#5 /usr/local/opnsense/contrib/google-api-php-client/Google/Service/Resource.php(231): Google_Client->execute(Object(Google_Http_Requ in /usr/local/opnsense/contrib/google-api-php-client/Google/IO/Curl.php on line 115

**dmesg.boot:**

Copyright (c) 2013-2018 The HardenedBSD Project.
Copyright (c) 1992-2018 The FreeBSD Project.
Copyright (c) 1979, 1980, 1983, 1986, 1988, 1989, 1991, 1992, 1993, 1994
	The Regents of the University of California. All rights reserved.
FreeBSD is a registered trademark of The FreeBSD Foundation.
FreeBSD 11.2-RELEASE-p11-HBSD  ab3b8b47944(stable/19.7) amd64
FreeBSD clang version 6.0.0 (tags/RELEASE_600/final 326565) (based on LLVM 6.0.0)
VT(vga): resolution 640x480
HardenedBSD: initialize and check features (__HardenedBSD_version 1100056 __FreeBSD_version 1102000).
CPU: Intel(R) Core(TM)2 Duo CPU     E6850  @ 3.00GHz (2992.54-MHz K8-class CPU)
  Origin="GenuineIntel"  Id=0x6fb  Family=0x6  Model=0xf  Stepping=11
  Features=0xbfebfbff
  Features2=0xe3fd
  AMD Features=0x20100800
  AMD Features2=0x1
  VT-x: (disabled in BIOS) HLT,PAUSE
  TSC: P-state invariant, performance statistics
real memory  = 2147483648 (2048 MB)
avail memory = 2003718144 (1910 MB)
Event timer "LAPIC" quality 100
ACPI APIC Table: 
FreeBSD/SMP: Multiprocessor System Detected: 2 CPUs
FreeBSD/SMP: 1 package(s) x 2 core(s)
Firmware Warning (ACPI): 32/64X length mismatch in FADT/Gpe0Block: 128/64 (20171214/tbfadt-748)
Firmware Warning (ACPI): Incorrect checksum in table [TCPA] - 0x00, should be 0x87 (20171214/tbprint-337)
ioapic0: Changing APIC ID to 8
ioapic0  irqs 0-23 on motherboard
SMP: AP CPU #1 Launched!
Timecounter "TSC-low" frequency 1496269957 Hz quality 1000
random: entropy device external interface
wlan: mac acl policy registered
000.000017 [4213] netmap_init               netmap: loaded module
module_register_init: MOD_LOAD (vesa, 0xffffffff8114ade0, 0) error 19
kbd1 at kbdmux0
nexus0
vtvga0:  on motherboard
cryptosoft0:  on motherboard
acpi0:  on motherboard
acpi0: Power Button (fixed)
cpu0:  on acpi0
cpu1:  on acpi0
atrtc0:  port 0x70-0x7f irq 8 on acpi0
atrtc0: registered as a time-of-day clock, resolution 1.000000s
Event timer "RTC" frequency 32768 Hz quality 0
attimer0:  port 0x40-0x5f irq 0 on acpi0
Timecounter "i8254" frequency 1193182 Hz quality 0
Event timer "i8254" frequency 1193182 Hz quality 100
hpet0:  iomem 0xfed00000-0xfed003ff on acpi0
Timecounter "HPET" frequency 14318180 Hz quality 950
Event timer "HPET" frequency 14318180 Hz quality 450
Event timer "HPET1" frequency 14318180 Hz quality 440
Event timer "HPET2" frequency 14318180 Hz quality 440
Event timer "HPET3" frequency 14318180 Hz quality 440
Timecounter "ACPI-fast" frequency 3579545 Hz quality 900
acpi_timer0: <24-bit timer at 3.579545MHz> port 0x808-0x80b on acpi0
acpi_button0:  on acpi0
pcib0:  port 0xcf8-0xcff on acpi0
pcib0: Length mismatch for 3 range: ec00001 vs ec00000
pci0:  on pcib0
pcib1:  irq 16 at device 1.0 on pci0
pci1:  on pcib1
vgapci0:  port 0xec90-0xec97 mem 0xfea00000-0xfea7ffff,0xd0000000-0xdfffffff,0xfeb00000-0xfebfffff irq 16 at device 2.0 on pci0
agp0:  on vgapci0
agp0: aperture size is 256M, detected 7164k stolen memory
vgapci0: Boot video device
vgapci1:  mem 0xfea80000-0xfeafffff at device 2.1 on pci0
pci0:  at device 3.0 (no driver attached)
atapci0:  port 0xfe80-0xfe87,0xfe90-0xfe93,0xfea0-0xfea7,0xfeb0-0xfeb3,0xfef0-0xfeff irq 18 at device 3.2 on pci0
ata2:  at channel 0 on atapci0
ata3:  at channel 1 on atapci0
pci0:  at device 3.3 (no driver attached)
em0:  port 0xecc0-0xecdf mem 0xfe9e0000-0xfe9fffff,0xfe9db000-0xfe9dbfff irq 21 at device 25.0 on pci0
em0: Using an MSI interrupt
em0: Ethernet address: 00:21:9b:7e:a6:b1
em0: netmap queues/slots: TX 1/1024, RX 1/1024
uhci0:  port 0xff20-0xff3f irq 16 at device 26.0 on pci0
uhci0: LegSup = 0x2f00
usbus0 on uhci0
usbus0: 12Mbps Full Speed USB v1.0
uhci1:  port 0xff00-0xff1f irq 17 at device 26.1 on pci0
uhci1: LegSup = 0x2f00
usbus1 on uhci1
usbus1: 12Mbps Full Speed USB v1.0
ehci0:  mem 0xfe9d9c00-0xfe9d9fff irq 22 at device 26.7 on pci0
usbus2: EHCI version 1.0
usbus2 on ehci0
usbus2: 480Mbps High Speed USB v2.0
hdac0:  mem 0xfe9dc000-0xfe9dffff irq 16 at device 27.0 on pci0
pcib2:  irq 16 at device 28.0 on pci0
pcib2: [GIANT-LOCKED]
uhci2:  port 0xff80-0xff9f irq 23 at device 29.0 on pci0
usbus3 on uhci2
usbus3: 12Mbps Full Speed USB v1.0
uhci3:  port 0xff60-0xff7f irq 17 at device 29.1 on pci0
usbus4 on uhci3
usbus4: 12Mbps Full Speed USB v1.0
uhci4:  port 0xff40-0xff5f irq 18 at device 29.2 on pci0
usbus5 on uhci4
usbus5: 12Mbps Full Speed USB v1.0
ehci1:  mem 0xff980800-0xff980bff irq 23 at device 29.7 on pci0
usbus6: EHCI version 1.0
usbus6 on ehci1
usbus6: 480Mbps High Speed USB v2.0
pcib3:  at device 30.0 on pci0
pci2:  on pcib3
rl0:  port 0xdc00-0xdcff mem 0xfe5fff00-0xfe5fffff irq 18 at device 2.0 on pci2
miibus0:  on rl0
rlphy0:  PHY 0 on miibus0
rlphy0:  10baseT, 10baseT-FDX, 100baseTX, 100baseTX-FDX, auto
rl0: Ethernet address: 00:1d:0f:c3:08:5e
isab0:  at device 31.0 on pci0
isa0:  on isab0
ahci0:  port 0xfe00-0xfe07,0xfe10-0xfe13,0xfe20-0xfe27,0xfe30-0xfe33,0xfec0-0xfedf mem 0xff970000-0xff9707ff irq 18 at device 31.2 on pci0
ahci0: AHCI v1.20 with 6 3Gbps ports, Port Multiplier supported
ahcich0:  at channel 0 on ahci0
ahcich1:  at channel 1 on ahci0
ahcich2:  at channel 2 on ahci0
ahcich3:  at channel 3 on ahci0
ahcich5:  at channel 5 on ahci0
ahciem0:  on ahci0
ppc0:  port 0x378-0x37f,0x778-0x77f irq 7 on acpi0
ppc0: SMC-like chipset (ECP/EPP/PS2/NIBBLE) in COMPATIBLE mode
ppc0: FIFO with 16/16/8 bytes threshold
ppbus0:  on ppc0
lpt0:  on ppbus0
lpt0: Interrupt-driven port
ppi0:  on ppbus0
uart0: <16550 or compatible> port 0x3f8-0x3ff irq 4 flags 0x10 on acpi0
orm0:  at iomem 0xc0000-0xcb7ff,0xcb800-0xcd7ff,0xcd800-0xce7ff,0xce800-0xd0fff,0xd1000-0xd3fff on isa0
atkbdc0:  at port 0x60,0x64 on isa0
atkbd0:  irq 1 on atkbdc0
kbd0 at atkbd0
atkbd0: [GIANT-LOCKED]
est0:  on cpu0
est: CPU supports Enhanced Speedstep, but is not recognized.
est: cpu_vendor GenuineIntel, msr 92a092a0600092a
device_attach: est0 attach returned 6
est1:  on cpu1
est: CPU supports Enhanced Speedstep, but is not recognized.
est: cpu_vendor GenuineIntel, msr 92a092a0600092a
device_attach: est1 attach returned 6
Timecounters tick every 1.000 msec
hdacc0:  at cad 0 on hdac0
hdaa0:  at nid 1 on hdacc0
pcm0:  at nid 18 and 20 on hdaa0
pcm1:  at nid 17 and 21 on hdaa0
ugen5.1:  at usbus5
ugen6.1:  at usbus6
uhub0:  on usbus5
uhub1:  on usbus6
ugen3.1:  at usbus3
ugen1.1:  at usbus1
uhub2:  on usbus3
uhub3:  on usbus1
ugen0.1:  at usbus0
ugen4.1:  at usbus4
uhub4:  on usbus0
uhub5:  on usbus4
ugen2.1:  at usbus2
uhub6:  on usbus2
uhub0: 2 ports with 2 removable, self powered
uhub2: 2 ports with 2 removable, self powered
uhub3: 2 ports with 2 removable, self powered
uhub4: 2 ports with 2 removable, self powered
uhub5: 2 ports with 2 removable, self powered
ses0 at ahciem0 bus 0 scbus7 target 0 lun 0
ses0:  SEMB S-E-S 2.00 device
cd0 at ahcich1 bus 0 scbus3 target 0 lun 0
ses0: SEMB SES Device
cd0:  Removable CD-ROM SCSI device
cd0: 150.000MB/s transfers (SATA 1.x, UDMA5, ATAPI 12bytes, PIO 8192bytes)
cd0: Attempt to query device size failed: NOT READY, Medium not present - tray closed
ada0 at ahcich0 bus 0 scbus2 target 0 lun 0
ada0:  ATA-7 SATA 2.x device
ada0: Serial Number WD-WCAP93714759
ada0: 300.000MB/s transfers (SATA 2.x, UDMA6, PIO 8192bytes)
ada0: Command Queueing enabled
ada0: 152627MB (312581808 512 byte sectors)
Trying to mount root from ufs:/dev/gpt/rootfs [rw]...
uhub1: 6 ports with 6 removable, self powered
uhub6: 6 ports with 6 removable, self powered
random: unblocking device.
ugen1.2:  at usbus1
ukbd0 on uhub3
ukbd0:  on usbus1
kbd2 at ukbd0

OPNsense (c) 2014-2019 Deciso B.V.

**Comment by AdSchellevis** [comment]
likely a connectivity issue while using backup to gdrive, same as https://github.com/opnsense/core/issues/3050

**Comment by jsbsmd** [comment]
i will look into that thanks and close if it is the issue.

**Comment by mr44er** [comment]
Yep, my first shot would be deactivating backup to gdrive.

**Comment by jsbsmd** [comment]
Yes it was backup to gdrive. Maybe something a to bit easier to read for error message would be nice.
ie: "backup to google drive has failed"  ;)
