### ISSUE TITLE
Cron log every minute.. bug or feature?

### ISSUE THREAD

**Issue by marjohn56** [opnsense/core#3616]
I'm not sure if this is a bug or a 'feature' but if its the latter, is there a way to turn it off?

Jul 30 20:28:00 | /usr/sbin/cron[71267]: (root) CMD ((/usr/local/bin/flock -n -E 0 -o /tmp/filter_update_tables.lock /usr/local/opnsense/scripts/filter/update_tables.py) > /dev/null)
-- | --
Jul 30 20:27:00 | /usr/sbin/cron[67987]: (root) CMD ((/usr/local/bin/flock -n -E 0 -o /tmp/filter_update_tables.lock /usr/local/opnsense/scripts/filter/update_tables.py) > /dev/null)
Jul 30 20:26:00 | /usr/sbin/cron[24900]: (root) CMD ((/usr/local/bin/flock -n -E 0 -o /tmp/filter_update_tables.lock /usr/local/opnsense/scripts/filter/update_tables.py) > /dev/null)
Jul 30 20:25:00 | /usr/sbin/cron[57999]: (root) CMD ((/usr/local/bin/flock -n -E 0 -o /tmp/filter_update_tables.lock /usr/local/opnsense/scripts/filter/update_tables.py) > /dev/null)

**Comment by AdSchellevis** [comment]
I'm not sure, it's probably a side affect of catching all in syslog-ng, I have to check what the log level of the messages is (if it's debug, we shouldn't forward them, otherwise we might move them to their own log file for clarity).

**Comment by AdSchellevis** [comment]
@marjohn56 it's a bug, should be fixed with https://github.com/opnsense/core/commit/387d41d7684b9ae0a9fbf18d2d18e1663a69da99 (remember to restart syslog-ng in services). We needed a custom output template to glue both syslog systems, which missed the `pri` tag

**Comment by marjohn56** [comment]
Thanks Ad, looking  good now,
