### ISSUE TITLE
Firewall Inspect feature shows N/A for most of the rules

### ISSUE THREAD

**Issue by JasMan78** [opnsense/core#3620]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[x] I have searched the existing issues and I'm convinced that mine is new.

**Describe the bug**
Firewall statistics (Inspect) shows N/A for Evaluations, States, Packets and Bytes for most of the rules. Only the NAT rules show current statistics

**To Reproduce**
1. Go to 'Firewall > Rules > INTERFACE'
2. Click on 'Inspect'

**Expected behavior**
The new 'Inspect' feature should show statistics for each of the firewall rules (as I understand).

**Screenshots**
![grafik](https://user-images.githubusercontent.com/20991399/62319853-2bd9bb00-b49f-11e9-904f-1e07499a0ff6.png)

**Relevant log files**
Don't know which log file could help to identify the issue.

**Additional context**
I've already asked some forum members if they knew the issue or how to solve it. But nobody else seems to have this issue.

**Environment**
OPNsense 19.7.1 (amd64)
Intel(R) Celeron(R) CPU J1900 @ 1.99GHz (4 cores)
OnBoard Realtek
2 x Realtek GbE OnBoard LAN chips (10/100/1000 Mbit)

**Comment by AdSchellevis** [comment]
I haven't seen the issue either, some things you could try:

Reload ruleset to make sure there are no parsing issues:
```
pfctl -f /tmp/rules.debug
```

(shouldn't generate output)


Check the output of the following command (which is the same as our stats use):
```
/sbin/pfctl -sr -v
```

The labels (e.g. 57e45e98f405ff38156d7ccef945da92) should match in /tmp/rules.debug where you can find the description (or the other way around).

**Comment by fichtner** [comment]
it could be rules optimised out so no stats can be gathered in the first place

**Comment by JasMan78** [comment]
The reload of the ruleset didn't helped.

The output of the second command shows me values for all my rules. 

````
pass in quick on hn1_vlan10 inet proto tcp from <Email_Clients> to ! <Private_Networks> port = imaps flags S/SA keep state label "43043f5837bb8a73d9aa4d6b4cef689f"
  [ Evaluations: 4         Packets: 140       Bytes: 51905       States: 0     ]
  [ Inserted: uid 0 pid 85819 State Creations: 1     ]
````

The WebGUI still shows N/A

![grafik](https://user-images.githubusercontent.com/20991399/62321986-45c9cc80-b4a4-11e9-8114-359c5ea2f1ed.png)

**Comment by JasMan78** [comment]
Yeeeehaaa, I've found the issue. :)
I associated each rule to a category like "LAN > Internet" or "WAN > DMZ".
The inspect feature don't like the ">" sign. After I'd removed it, the values were shown.

**Comment by fichtner** [comment]
HTML encode -> hash mismatch maybe?

**Comment by AdSchellevis** [comment]
`OPNsense\Firewall\Util::calcRuleHash()` on escaped content seems to be the culprit indeed, will fix in close in the next commit.
