### ISSUE TITLE
Syslog: allow use of FQDN for remote logging

### ISSUE THREAD

**Issue by skazi0** [opnsense/core#3622]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[x] I have searched the existing issues and I'm convinced that mine is new.

**Is your feature request related to a problem? Please describe.**
New syslog-ng implementation (i.e. Logging/targets) doesn't use FQDN in messages. This is default behavior of syslog-ng (See https://www.syslog-ng.com/technical-documents/doc/syslog-ng-open-source-edition/3.21/administration-guide/use-fqdn). With central logging it is better to use FQDNs as there could be multiple hosts with the same hostname but different domains sending messages to the same central syslog.
It could also be considered a regression as the old remote logging implementation used FQDNs.

**Describe the solution you'd like**
Syslog-ng has an option which will solve this problem https://www.syslog-ng.com/technical-documents/doc/syslog-ng-open-source-edition/3.21/administration-guide/use-fqdn. I have tested it on my system and it seems to work correctly (even with `keep_hostname(yes)` although the documentation says otherwise).
This could be done as an option (with ON as default) or hardcoded to ON to keep backward compatibility.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by AdSchellevis** [comment]
@skazi0 can you post your sample config?

**Comment by skazi0** [comment]
I have just added one line so my `syslog-ng.conf` looks like this now:
```
@version:3.21
@include "scl.conf"

#
# options
#
options {
    keep_hostname(yes);
	use_fqdn(yes);
    chain_hostnames(off);
    flush_lines(0);
    threaded(yes);
    create_dirs(yes);
};

source s_all {
    internal();
    unix-dgram("/var/run/log");
    unix-dgram("/var/run/logpriv" perm(0600));
    unix-dgram("/var/dhcpd/var/run/log" dir_perm(0755));
    unix-dgram("/var/unbound/var/run/log" dir_perm(0755));
};

@include "/usr/local/etc/syslog-ng.conf.d/*.conf"

**Comment by AdSchellevis** [comment]
@skazi0 I agree it looks like a regression, since we used to send fqdn before. https://github.com/opnsense/core/commit/2d7f9cae2db548d9727a99ba42079dccc0b27e9b should fix it.
