### ISSUE TITLE
Unbound: allow virtual IP as listen interface (like ntpd)

### ISSUE THREAD

**Issue by tokred** [opnsense/core#3623]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[x] I have searched the existing issues and I'm convinced that mine is new.

**Is your feature request related to a problem? Please describe.**
When managing a larger number of attached subnets and letting the central firewall handle DNS resolution, I prefer to distribute a single DNS resolver IP over having multiple resolver IPs (=per subnet), i.e. using one common target like 10.0.0.53 instead of using 192.168.1.1, 192.168.2.1, 192.168.3.1, etc.
This makes things a bit easier when using dig/nslookup/etc. to do testing, because I do not have to think about in which subnet I am currently located, because there is "just one resolver IP".

**Describe the solution you'd like**
As OPNsense allows to define virtual IPs, it would be great if I could bind Unbound to one of these virtual IPs. This is already supported with ntpd where the Interfaces drop-down shows virtual IPs, but not for Unbound where I only see "physical" interfaces. I'd like to ask to harmonize the two services.

**Describe alternatives you've considered**
The alternative is to manually set the `interface:` parameter via Unbound Custom options field, which is fine but according to help text "This option will be removed in the future due to being insecure by nature".

**Comment by fichtner** [comment]
Hi @tokred,

You are referring to an older component which does things not in the way we want. Unbound is hard-wired to listen to *all* VIPs of the selected interfaces. There is no desire to change to a more selective behaviour here.


Cheers,
Franco

**Comment by tokred** [comment]
Hi @fichtner,
thanks for your response! Not sure what you mean by older component, but when you are saying it is a strategic decision not to do that, I can accept that. Would have been nice though. ;-)

Regards

**Comment by fichtner** [comment]
Hi @tokred,

Older components here means static PHP pages with no service file templating. These components create a lot of work to maintain and depending on their origin (date and author) they do different things as was customary at the time of the code creation.

We try to remove that drift from the code and it's a long path ahead still so we have to be a bid rigid about our long term goals. :)


Cheers,
Franco
