### ISSUE TITLE
Opnsense 19.7 - terrible NIC performance on i440fx, other issues.

### ISSUE THREAD

**Issue by tsalwierz** [opnsense/core#3624]
Hi all!

I recently had to reinstall opnsense due to a issue upgrading from development to production. I am on 19.7 using i440fx/kvm with virtio enabled in tunables. I have one NIC going through PCI-Passthrough and one virtio bridge. Virtio hard drive.

Issues at hand:

* Internet speed is under 600KB/s on file transfers with wget with occasional bursts up to 1.5MB/s.
* Speedtest.net shows horrible results. Around 50Mbps down and 4.5Mbps up.
* WAN link is detected at 100 TX instead of 1000 T. Manually setting 1000 T disables WAN.

Setup:

Default settings on everything with a minor exception to LRO offloading being enabled and Unbound setup.

Host node:
E3-1240 V3
32GB ECC
512GB SSD
Integrated intel nics with supermicro, both intel.

VM:
i440fx, cpu host-passthrough full check, 4 threads (2 cores). QEMU is latest version. Uses OVMF.
One nic is PCI passthrough and the other is a virtio bridge.

How this is a Opnsense/HardenedBSD issue:

Installed pfsense with exact same VM config (different hdd). Configured setup to be identical including LRO offloading.

Not only does pfsense have no issue it also:

* Detects KVM hypervisor
* Detects VirtIO out of box
* Properly identifies WAN as 1000 T
* Properly identifies VirtIO NIC at 10Gbps (they can go over, though)

See attached. The higher speed images are pfsense and the slower are opnsense.

I want to continue using opnsense but I'm not going to setup a dedicated 1U server for it which amounts to over $800 with my current hardware. I don't have an atom or rasberry pi (if they work?) leaving virtualization as the only option unless I want to get a power hungry cheap xeon server on ebay.
![firefox_r6AVdwgQA6](https://user-images.githubusercontent.com/7935624/62378168-15f8e400-b4f9-11e9-8a87-06754cd39b35.png)
![firefox_Eb0QMETKmY](https://user-images.githubusercontent.com/7935624/62378184-1d1ff200-b4f9-11e9-9a13-0e413fc23188.png)
![firefox_g6yFdW1gp3](https://user-images.githubusercontent.com/7935624/62378191-20b37900-b4f9-11e9-90ee-abb5d4f05386.png)

**Comment by AdSchellevis** [comment]
Vultr (https://www.vultr.com/) seems to be using Virtio as well, works like a charm, cheapest vm (which isn't very fast) outputs:

![image](https://user-images.githubusercontent.com/9783985/62381961-e7a4f400-b54c-11e9-9145-1997c0ce382b.png)

![image](https://user-images.githubusercontent.com/9783985/62382092-2aff6280-b54d-11e9-802d-0a79825380f4.png)

```
root@OPNsense:~ # pciconf -lVv

hostb0@pci0:0:0:0:	class=0x060000 card=0x11001af4 chip=0x12378086 rev=0x02 hdr=0x00
    vendor     = 'Intel Corporation'
    device     = '440FX - 82441FX PMC [Natoma]'
    class      = bridge
    subclass   = HOST-PCI

......

virtio_pci0@pci0:0:3:0:	class=0x020000 card=0x00011af4 chip=0x10001af4 rev=0x00 hdr=0x00
    vendor     = 'Red Hat, Inc.'
    device     = 'Virtio network device'
    class      = network
    subclass   = ethernet


......
```

**Comment by tsalwierz** [comment]
This is what I'm seeing, starting with pfsense followed by opnsense:

`[2.4.4-RELEASE][admin@router.localdomain]/root: ifconfig
vtnet0: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500
        options=c04b8<VLAN_MTU,VLAN_HWTAGGING,JUMBO_MTU,VLAN_HWCSUM,LRO,VLAN_HWTSO,LINKSTATE>
        ether 52:54:00:bd:32:67
        hwaddr 52:54:00:bd:32:67
        inet6 fe80::5054:ff:febd:3267%vtnet0 prefixlen 64 scopeid 0x1
        inet 10.0.0.1 netmask 0xff000000 broadcast 10.255.255.255
        nd6 options=21<PERFORMNUD,AUTO_LINKLOCAL>
        media: Ethernet 10Gbase-T <full-duplex>
        status: active
igb0: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500
        options=404b8<VLAN_MTU,VLAN_HWTAGGING,JUMBO_MTU,VLAN_HWCSUM,LRO,VLAN_HWTSO>
        ether 00:25:90:d9:dc:36
        hwaddr 00:25:90:d9:dc:36
        inet6 fe80::225:90ff:fed9:dc36%igb0 prefixlen 64 scopeid 0x2
        inet 192.168.10.154 netmask 0xffffff00 broadcast 192.168.10.255
        nd6 options=23<PERFORMNUD,ACCEPT_RTADV,AUTO_LINKLOCAL>
        media: Ethernet autoselect (1000baseT <full-duplex>)
        status: active
enc0: flags=0<> metric 0 mtu 1536
        nd6 options=21<PERFORMNUD,AUTO_LINKLOCAL>
        groups: enc
lo0: flags=8049<UP,LOOPBACK,RUNNING,MULTICAST> metric 0 mtu 16384
        options=600003<RXCSUM,TXCSUM,RXCSUM_IPV6,TXCSUM_IPV6>
        inet6 ::1 prefixlen 128
        inet6 fe80::1%lo0 prefixlen 64 scopeid 0x4
        inet 127.0.0.1 netmask 0xff000000
        nd6 options=21<PERFORMNUD,AUTO_LINKLOCAL>
        groups: lo
pflog0: flags=100<PROMISC> metric 0 mtu 33160
        groups: pflog
pfsync0: flags=0<> metric 0 mtu 1500
        groups: pfsync
        syncpeer: 224.0.0.240 maxupd: 128 defer: on
        syncok: 1
`
`[2.4.4-RELEASE][admin@router.localdomain]/root: speedtest-cli
Retrieving speedtest.net configuration...
Testing from Frontier Communications (ip)...
Retrieving speedtest.net server list...
Selecting best server based on ping...

Hosted by Whidbey Telecom (Langley, WA) [18.58 km]: 20.905 ms
Testing download speed................................................................................
Download: 96.16 Mbit/s
Testing upload speed................................................................................................
Upload: 101.63 Mbit/s
`

`[2.4.4-RELEASE][admin@router.localdomain]/root: pciconf -lVv
hostb0@pci0:0:0:0:      class=0x060000 card=0x11001af4 chip=0x12378086 rev=0x02 hdr=0x00
    vendor     = 'Intel Corporation'
    device     = '440FX - 82441FX PMC [Natoma]'
    class      = bridge
    subclass   = HOST-PCI
isab0@pci0:0:1:0:       class=0x060100 card=0x11001af4 chip=0x70008086 rev=0x00 hdr=0x00
    vendor     = 'Intel Corporation'
    device     = '82371SB PIIX3 ISA [Natoma/Triton II]'
    class      = bridge
    subclass   = PCI-ISA
atapci0@pci0:0:1:1:     class=0x010180 card=0x11001af4 chip=0x70108086 rev=0x00 hdr=0x00
    vendor     = 'Intel Corporation'
    device     = '82371SB PIIX3 IDE [Natoma/Triton II]'
    class      = mass storage
    subclass   = ATA
none0@pci0:0:1:3:       class=0x068000 card=0x11001af4 chip=0x71138086 rev=0x03 hdr=0x00
    vendor     = 'Intel Corporation'
    device     = '82371AB/EB/MB PIIX4 ACPI'
    class      = bridge
vgapci0@pci0:0:2:0:     class=0x030000 card=0x11001af4 chip=0x01001b36 rev=0x04 hdr=0x00
    vendor     = 'Red Hat, Inc.'
    device     = 'QXL paravirtual graphic card'
    class      = display
    subclass   = VGA
virtio_pci0@pci0:0:3:0: class=0x020000 card=0x00011af4 chip=0x10001af4 rev=0x00 hdr=0x00
    vendor     = 'Red Hat, Inc.'
    device     = 'Virtio network device'
    class      = network
    subclass   = ethernet
uhci0@pci0:0:4:0:       class=0x0c0300 card=0x11001af4 chip=0x29348086 rev=0x03 hdr=0x00
    vendor     = 'Intel Corporation'
    device     = '82801I (ICH9 Family) USB UHCI Controller'
    class      = serial bus
    subclass   = USB
uhci1@pci0:0:4:1:       class=0x0c0300 card=0x11001af4 chip=0x29358086 rev=0x03 hdr=0x00
    vendor     = 'Intel Corporation'
    device     = '82801I (ICH9 Family) USB UHCI Controller'
    class      = serial bus
    subclass   = USB
uhci2@pci0:0:4:2:       class=0x0c0300 card=0x11001af4 chip=0x29368086 rev=0x03 hdr=0x00
    vendor     = 'Intel Corporation'
    device     = '82801I (ICH9 Family) USB UHCI Controller'
    class      = serial bus
    subclass   = USB
ehci0@pci0:0:4:7:       class=0x0c0320 card=0x11001af4 chip=0x293a8086 rev=0x03 hdr=0x00
    vendor     = 'Intel Corporation'
    device     = '82801I (ICH9 Family) USB2 EHCI Controller'
    class      = serial bus
    subclass   = USB
ahci0@pci0:0:5:0:       class=0x010601 card=0x11001af4 chip=0x29228086 rev=0x02 hdr=0x00
    vendor     = 'Intel Corporation'
    device     = '82801IR/IO/IH (ICH9R/DO/DH) 6 port SATA Controller [AHCI mode]'
    class      = mass storage
    subclass   = SATA
virtio_pci1@pci0:0:6:0: class=0x078000 card=0x00031af4 chip=0x10031af4 rev=0x00 hdr=0x00
    vendor     = 'Red Hat, Inc.'
    device     = 'Virtio console'
    class      = simple comms
igb0@pci0:0:8:0:        class=0x020000 card=0x153315d9 chip=0x15338086 rev=0x03 hdr=0x00
    vendor     = 'Intel Corporation'
    device     = 'I210 Gigabit Network Connection'
    class      = network
    subclass   = ethernet
virtio_pci2@pci0:0:9:0: class=0x00ff00 card=0x00051af4 chip=0x10021af4 rev=0x00 hdr=0x00
    vendor     = 'Red Hat, Inc.'
    device     = 'Virtio memory balloon'
    class      = old
virtio_pci3@pci0:0:10:0:        class=0x010000 card=0x00021af4 chip=0x10011af4 rev=0x00 hdr=0x00
    vendor     = 'Red Hat, Inc.'
    device     = 'Virtio block device'
    class      = mass storage
    subclass   = SCSI
`
`root@OPNsense:~ # ifconfig
vtnet0: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500
        options=c04b8<VLAN_MTU,VLAN_HWTAGGING,JUMBO_MTU,VLAN_HWCSUM,LRO,VLAN_HWTSO,LINKSTATE>
        ether 52:54:00:bd:32:67
        hwaddr 52:54:00:bd:32:67
        inet6 fe80::5054:ff:febd:3267%vtnet0 prefixlen 64 scopeid 0x1
        inet 10.0.0.1 netmask 0xff000000 broadcast 10.255.255.255
        nd6 options=21<PERFORMNUD,AUTO_LINKLOCAL>
        media: Ethernet 10Gbase-T <full-duplex>
        status: active
igb0: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500
        options=404b8<VLAN_MTU,VLAN_HWTAGGING,JUMBO_MTU,VLAN_HWCSUM,LRO,VLAN_HWTSO>
        ether 00:25:90:d9:dc:36
        hwaddr 00:25:90:d9:dc:36
        inet6 fe80::225:90ff:fed9:dc36%igb0 prefixlen 64 scopeid 0x2
        inet 192.168.10.154 netmask 0xffffff00 broadcast 192.168.10.255
        nd6 options=23<PERFORMNUD,ACCEPT_RTADV,AUTO_LINKLOCAL>
        media: Ethernet 100baseTX <full-duplex>
        status: active
lo0: flags=8049<UP,LOOPBACK,RUNNING,MULTICAST> metric 0 mtu 16384
        options=600003<RXCSUM,TXCSUM,RXCSUM_IPV6,TXCSUM_IPV6>
        inet6 ::1 prefixlen 128
        inet6 fe80::1%lo0 prefixlen 64 scopeid 0x3
        inet 127.0.0.1 netmask 0xff000000
        nd6 options=21<PERFORMNUD,AUTO_LINKLOCAL>
        groups: lo
enc0: flags=0<> metric 0 mtu 1536
        nd6 options=21<PERFORMNUD,AUTO_LINKLOCAL>
        groups: enc
pflog0: flags=100<PROMISC> metric 0 mtu 33160
        groups: pflog
pfsync0: flags=0<> metric 0 mtu 1500
        groups: pfsync
        syncpeer: 0.0.0.0 maxupd: 128 defer: off
`
`root@OPNsense:~ # speedtest-cli
Retrieving speedtest.net configuration...
Testing from Frontier Communications (ip)...
Retrieving speedtest.net server list...
Selecting best server based on ping...
Hosted by Speedtest.net (Seattle, WA) [51.99 km]: 23.595 ms
Testing download speed................................................................................
Download: 29.86 Mbit/s
Testing upload speed................................................................................................
Upload: 19.93 Mbit/s
`
`root@OPNsense:~ # pciconf -lVv
hostb0@pci0:0:0:0:      class=0x060000 card=0x11001af4 chip=0x12378086 rev=0x02 hdr=0x00
    vendor     = 'Intel Corporation'
    device     = '440FX - 82441FX PMC [Natoma]'
    class      = bridge
    subclass   = HOST-PCI
isab0@pci0:0:1:0:       class=0x060100 card=0x11001af4 chip=0x70008086 rev=0x00 hdr=0x00
    vendor     = 'Intel Corporation'
    device     = '82371SB PIIX3 ISA [Natoma/Triton II]'
    class      = bridge
    subclass   = PCI-ISA
atapci0@pci0:0:1:1:     class=0x010180 card=0x11001af4 chip=0x70108086 rev=0x00 hdr=0x00
    vendor     = 'Intel Corporation'
    device     = '82371SB PIIX3 IDE [Natoma/Triton II]'
    class      = mass storage
    subclass   = ATA
none0@pci0:0:1:3:       class=0x068000 card=0x11001af4 chip=0x71138086 rev=0x03 hdr=0x00
    vendor     = 'Intel Corporation'
    device     = '82371AB/EB/MB PIIX4 ACPI'
    class      = bridge
vgapci0@pci0:0:2:0:     class=0x030000 card=0x11001af4 chip=0x01001b36 rev=0x04 hdr=0x00
    vendor     = 'Red Hat, Inc.'
    device     = 'QXL paravirtual graphic card'
    class      = display
    subclass   = VGA
virtio_pci0@pci0:0:3:0: class=0x020000 card=0x00011af4 chip=0x10001af4 rev=0x00 hdr=0x00
    vendor     = 'Red Hat, Inc.'
    device     = 'Virtio network device'
    class      = network
    subclass   = ethernet
uhci0@pci0:0:4:0:       class=0x0c0300 card=0x11001af4 chip=0x29348086 rev=0x03 hdr=0x00
    vendor     = 'Intel Corporation'
    device     = '82801I (ICH9 Family) USB UHCI Controller'
    class      = serial bus
    subclass   = USB
uhci1@pci0:0:4:1:       class=0x0c0300 card=0x11001af4 chip=0x29358086 rev=0x03 hdr=0x00
    vendor     = 'Intel Corporation'
    device     = '82801I (ICH9 Family) USB UHCI Controller'
    class      = serial bus
    subclass   = USB
uhci2@pci0:0:4:2:       class=0x0c0300 card=0x11001af4 chip=0x29368086 rev=0x03 hdr=0x00
    vendor     = 'Intel Corporation'
    device     = '82801I (ICH9 Family) USB UHCI Controller'
    class      = serial bus
    subclass   = USB
ehci0@pci0:0:4:7:       class=0x0c0320 card=0x11001af4 chip=0x293a8086 rev=0x03 hdr=0x00
    vendor     = 'Intel Corporation'
    device     = '82801I (ICH9 Family) USB2 EHCI Controller'
    class      = serial bus
    subclass   = USB
ahci0@pci0:0:5:0:       class=0x010601 card=0x11001af4 chip=0x29228086 rev=0x02 hdr=0x00
    vendor     = 'Intel Corporation'
    device     = '82801IR/IO/IH (ICH9R/DO/DH) 6 port SATA Controller [AHCI mode]'
    class      = mass storage
    subclass   = SATA
virtio_pci1@pci0:0:6:0: class=0x078000 card=0x00031af4 chip=0x10031af4 rev=0x00 hdr=0x00
    vendor     = 'Red Hat, Inc.'
    device     = 'Virtio console'
    class      = simple comms
igb0@pci0:0:8:0:        class=0x020000 card=0x153315d9 chip=0x15338086 rev=0x03 hdr=0x00
    vendor     = 'Intel Corporation'
    device     = 'I210 Gigabit Network Connection'
    class      = network
    subclass   = ethernet
virtio_pci2@pci0:0:9:0: class=0x00ff00 card=0x00051af4 chip=0x10021af4 rev=0x00 hdr=0x00
    vendor     = 'Red Hat, Inc.'
    device     = 'Virtio memory balloon'
    class      = old
virtio_pci3@pci0:0:10:0:        class=0x010000 card=0x00021af4 chip=0x10011af4 rev=0x00 hdr=0x00
    vendor     = 'Red Hat, Inc.'
    device     = 'Virtio block device'
    class      = mass storage
    subclass   = SCSI
`

**Comment by AdSchellevis** [comment]
```
igb0: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500
options=404b8<VLAN_MTU,VLAN_HWTAGGING,JUMBO_MTU,VLAN_HWCSUM,LRO,VLAN_HWTSO>
ether 00:25:90:d9:dc:36
hwaddr 00:25:90:d9:dc:36
inet6 fe80::225:90ff:fed9:dc36%igb0 prefixlen 64 scopeid 0x2
inet 192.168.10.154 netmask 0xffffff00 broadcast 192.168.10.255
nd6 options=23<PERFORMNUD,ACCEPT_RTADV,AUTO_LINKLOCAL>
media: Ethernet 100baseTX 
status: active
```
^^^ I would configure the same interface type on both, this doesn't look like vtnet

**Comment by tsalwierz** [comment]
> 
> 
> ```
> igb0: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500
> options=404b8<VLAN_MTU,VLAN_HWTAGGING,JUMBO_MTU,VLAN_HWCSUM,LRO,VLAN_HWTSO>
> ether 00:25:90:d9:dc:36
> hwaddr 00:25:90:d9:dc:36
> inet6 fe80::225:90ff:fed9:dc36%igb0 prefixlen 64 scopeid 0x2
> inet 192.168.10.154 netmask 0xffffff00 broadcast 192.168.10.255
> nd6 options=23<PERFORMNUD,ACCEPT_RTADV,AUTO_LINKLOCAL>
> media: Ethernet 100baseTX 
> status: active
> ```
> 
> ^^^ I would configure the same interface type on both, this doesn't look like vtnet

igb0 is the pci-passthrough card so it's not going to see vtnet. Also doesn't explain the speed differences between pfsense and opnsense as they both have that configuration. Also doesn't explain why 19.1 didn't have this issue.

The card in question:

`<hostdev mode="subsystem" type="pci" managed="yes">
  <driver name="vfio"/>
  <source>
    <address domain="0x0000" bus="0x04" slot="0x00" function="0x0"/>
  </source>
  <alias name="hostdev0"/>
  <address type="pci" domain="0x0000" bus="0x00" slot="0x08" function="0x0"/>
</hostdev>`

**Comment by AdSchellevis** [comment]
not sure what "this" issue is, 19.1 is new information in this ticket, I suspect something changed in between setups, you could install 19.1 and step through the changes (https://github.com/opnsense/core/issues/3611#issuecomment-516034089) and see when your issue appears. 

As said, Vultr uses virtio too, which seems to be working like a charm.

**Comment by tsalwierz** [comment]
> 
> 
> not sure what "this" issue is, 19.1 is new information in this ticket, I suspect something changed in between setups, you could install 19.1 and step through the changes ([#3611 (comment)](https://github.com/opnsense/core/issues/3611#issuecomment-516034089)) and see when your issue appears.
> 
> As said, Vultr uses virtio too, which seems to be working like a charm.

Does Vultur use KVM/i440fx/Q35? I checked their FAQ and can't find any information about it. I know back in 2016 they used KVM but times have changed and they now advertise their services as cloud-based.

At any rate, I can tell you that I've used this same configuration with Opnsense for a few months now. This issue only happened after I reinstalled into 19.7. It ran fine on 19.1.

The XML file does not change between Opnsense 19.7 and pfsense, so it's definitely something to do with Opnsense/HardenedBSD. There is literally nothing changing between the two other then the .raw hard drive image file.

**Comment by AdSchellevis** [comment]
I'm not sure what Vultr uses, although lspci looks quite similar (both look like i440fx in stead of Q35, https://wiki.qemu.org/images/4/4e/Q35.pdf).

My suggestion just is to test step by step and check when the issue occurs, if you install the netmap kernel on 19.1 (as referred earlier), you would have (as good as) the same kernel as 19.7, which makes it easier to rule things out. 
In our experience it's easy to make changes somewhere in the system and accidentally assume the setup is the same as it was before.

**Comment by tsalwierz** [comment]
> 
> 
> I'm not sure what Vultr uses, although lspci looks quite similar (both look like i440fx in stead of Q35, https://wiki.qemu.org/images/4/4e/Q35.pdf).
> 
> My suggestion just is to test step by step and check when the issue occurs, if you install the netmap kernel on 19.1 (as referred earlier), you would have (as good as) the same kernel as 19.7, which makes it easier to rule things out.
> In our experience it's easy to make changes somewhere in the system and accidentally assume the setup is the same as it was before.

The netmap kernel has a signature error.

I've narrowed down the problem to suppress arp messages & LRO offloading. Enabling both of these options and rebooting causes the web panel to become inaccessible and makes text scroll painfully slow on the terminal output. Entire VM becomes unresponsive to input. No text appears as new on the terminal output.

Since LRO works on pfsense I'm going to assume it's the ARP suppression.
