### ISSUE TITLE
Services Gateway Issue

### ISSUE THREAD

**Issue by cmb991** [opnsense/core#3625]
**Important notices**
Our forum is located at https://forum.opnsense.org , please consider joining discussions there in stead of using GitHub for these matters.

Before you ask a new question, we ask you kindly to acknowledge the following:

[X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[X] I have searched the existing issues and I'm convinced that mine is new.

I'm trying to delete some dpinger services manually.  It seems that if you go to your gateways > New > create a new gateway, it won't show the gateway in the gateways but it still makes a dpinger for it.  What is the best way to do this?

![dpinger](https://user-images.githubusercontent.com/30929454/62407355-28206400-b585-11e9-828c-a79b1a34a84e.PNG)

**Comment by AdSchellevis** [comment]
can you post a screenshot of your gateways (without addresses)? It might be a bug, since dpinger reads the config directly there might be items that are not valid anymore which we now hide (since 19.7). If that's the case and you're not in a huge hurry, I'll try to look into it in the following days.

The work around is to remove the item(s) from your config.xml manually.

**Comment by cmb991** [comment]
Please see attached.  I believe I have all of these settings correct for Verizon to be the failover too.

**Comment by AdSchellevis** [comment]
@cmb991 it looks like your attachments lost,  can you try pasting them online?

**Comment by cmb991** [comment]
Sorry.  Here are the pictures.  The setup is Xfinity as the primary connection and Verizon as the failover.  Although, I’m noticing Verizon is taking the primary spot when I plug it in, so I’m not sure what that is about.  
![F1D9A24D-E53D-48BC-A379-39D6609744A5](https://user-images.githubusercontent.com/30929454/62424876-dbcb4600-b6a2-11e9-81a0-4cb9c6d15a39.png)
![431D8C6E-302D-4803-89A3-616252FDB972](https://user-images.githubusercontent.com/30929454/62424877-dbcb4600-b6a2-11e9-98ae-25891acd849f.png)
![F9D9608C-CF7C-4D61-8B26-17CC2B0B9B3D](https://user-images.githubusercontent.com/30929454/62424878-dbcb4600-b6a2-11e9-902c-68437439cbec.png)
![4A3E61BB-236A-4C7E-9BDF-BD3336E4C08B](https://user-images.githubusercontent.com/30929454/62424879-dbcb4600-b6a2-11e9-961f-5ba17eef00d1.png)
![23DF4653-B3EB-4E96-BB2F-6CDDE468D004](https://user-images.githubusercontent.com/30929454/62424880-dbcb4600-b6a2-11e9-9075-09b604e29764.png)
![03568A4A-79C0-4401-B8B0-B4DC827CBEBA](https://user-images.githubusercontent.com/30929454/62424881-dbcb4600-b6a2-11e9-9839-255fb8fbb57c.png)
![4BCAFD06-7FC8-4066-AC00-37591A80CE90](https://user-images.githubusercontent.com/30929454/62424882-dbcb4600-b6a2-11e9-955b-5c89a84d5060.png)
![A65550F5-EB06-49D4-BBB7-B3B72B09995E](https://user-images.githubusercontent.com/30929454/62424883-dc63dc80-b6a2-11e9-9219-ecc8216ec3c9.png)

**Comment by AdSchellevis** [comment]
@cmb991 https://github.com/opnsense/core/commit/93bbe1ee168bbe0297746c2a2f68a5a4a4cd0972 should fix the visibility issue. It's probably best to wait for 19.7.2 tomorrow and apply this patch on top (there are some other changes stashed in the same files). 

![image](https://user-images.githubusercontent.com/9783985/62427291-4905c800-b6f1-11e9-9faa-30af0ccfef7e.png)

**Comment by AdSchellevis** [comment]
I missed a spot (https://github.com/opnsense/core/commit/74ff64787cf78654595231a359b47cad6a88511e) and found another small presentation issue while working on this item https://github.com/opnsense/core/commit/bb6833d5013facc058a70376362ad0b45409ff03.

To install all changes on OPNsense 19.7.2:

```
opnsense-patch 93bbe1e 74ff647 bb6833d
```

**Comment by cmb991** [comment]
Everything seems to be working now, I just had a question about this setup now; the firewall rules, I only have the one LAN rule in a gateway group called failover.  Does that local DNS route firewall rule that the guide says to put in need to have the failover gateway or no since its locally doing the DNS reroute?  Screenshot below
![firewall rules](https://user-images.githubusercontent.com/30929454/62492778-7f991c80-b79d-11e9-9db8-4531dfdabda4.PNG)

**Comment by AdSchellevis** [comment]
@cmb991 thanks for confirming, let's close the issue then. 

The port 53 rule prevents dns traffic being send to the gateway, which is needed if you are using a local forwarder (unbound for example)

**Comment by skl283** [comment]
> ```
> opnsense-patch 93bbe1e 74ff647 bb6833d
> ```

works! The Gateways are now displayed. But i've found a litte Problem with the Checkbox in front of the entries. If i mark all entries and klick on the trash. Some will be present. I have to purge every single item in the list.

**Comment by AdSchellevis** [comment]
@skl283 I haven't seen the select all issue yet, but I'll try it out on a box over here.

**Comment by skl283** [comment]
No Problem.Had just issue while delete all "testing"entries before applying the patches ;-)

**Comment by alexanderharm** [comment]
I had a similar issue since upgrading to 19.7.2. One issue remains though: after applying your patches I cannot modify the automatically generated gateway of a DHCP WAN connection! See attached screenshot. How can I set upstream gateway or priority now? Or do I need a gateway group by default if one WAN connection is DHCP based?

<img width="939" alt="Screen Shot 2019-08-08 at 08 57 55" src="https://user-images.githubusercontent.com/16108584/62681962-40481700-b9bb-11e9-938f-a4012ce042a3.png">

**Comment by AdSchellevis** [comment]
@alexanderharm the buttons aren't shown on the right? can you resize your screen a bit? when it's a bit smaller it should resize to xs and show the buttons again.  You should also be able to scroll to the right (the buttons should be there, there just don't seem to be enough space there).

**Comment by alexanderharm** [comment]
Thanks, resizing the screen did the job.

**Comment by AdSchellevis** [comment]
we might use "table-condensed" to strip some of the margins, same as we did recently on the firewall pages.

**Comment by AdSchellevis** [comment]
@alexanderharm https://github.com/opnsense/core/commit/1aad01cc92c42f3a24ea61f231c3692b6f07dd3c should be better. (although it can still break out in some situations)
