### ISSUE TITLE
Add patch freebsd sonewconn

### ISSUE THREAD

**Issue by Hvalecia** [opnsense/core#3627]
Hello, 

In teh las version FreeBSD 
Stable release: HardenedBSD-stable 12-STABLE v1200059

It is add patch for PCB failed.

It is posible add path in OPNsense

Merge r344741: Remove bogus assert that I added in r319722. It is a legitimate case to call soabort() on a newborn socket created by sonewconn() in case if further setup of PCB failed. Code in sofree() handles such socket correctly.

https://hardenedbsd.org/article/op/2019-06-08/stable-release-hardenedbsd-stable-12-stable-v1200059

Regards, Humberto

**Comment by AdSchellevis** [comment]
we're using HBSD 11.2

**Comment by fichtner** [comment]
I'm sure it'll be part of HardenedBSD 12.1
