### ISSUE TITLE
unbound.inc loglevel

### ISSUE THREAD

**Issue by fatchoy** [opnsense/core#363]
I've realized it wasn't possible to change the log verbosity in unbound. The verbosity in the unbound.conf was always set to 1, whatever the value selected in the webinterface.
I found that this value is stored under $config['unbound']['log_verbosity'] in service_unbound_advanced.php
and in $config['unbound']['loglevel'] in unbound.inc

I've changed from loglevel to log_verbosity on line 211 in unbound.inc and it's working fine

**Comment by AdSchellevis** [comment]
Thanks for reporting, I've changed it right away.
https://github.com/opnsense/core/commit/16ed1470d223b9e3f60e053d8f296e41b5797d2a
