### ISSUE TITLE
Monit Email Notifications

### ISSUE THREAD

**Issue by cmb991** [opnsense/core#3631]
**Important notices**
Our forum is located at https://forum.opnsense.org , please consider joining discussions there in stead of using GitHub for these matters.

Before you ask a new question, we ask you kindly to acknowledge the following:

[X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[X] I have searched the existing issues and I'm convinced that mine is new.

I’m trying to setup Monits to email me when my primary interface goes down and my backup internet is now active; then vice versa.  I don’t see much documentation on this situation.  Would you be able to help me?

**Comment by mimugmail** [comment]
Have you searched the forums? I think the forums are a better place for such questions.
Here's a good start: https://forum.opnsense.org/index.php?topic=5303.0

The dev of monit feature is also active on IRC for specific questions (faunsen)

**Comment by cmb991** [comment]
I did search the forums and even made a post but never got any replies.  Ill try IRC, thanks.
