### ISSUE TITLE
HASync / XMLRPC remove legacy push on changes

### ISSUE THREAD

**Issue by AdSchellevis** [opnsense/core#3635]
This seemed to have slipped my mind a bit, but I think we should remove the hasync in config writes. When the backup node doesn't respond, the master can become quite unresponsive and new style components don't do this anyway.

My proposal would be to just ditch these lines:
https://github.com/opnsense/core/blob/f9610615ecdfdc70e5cf8d7c2b1c56522a53527d/src/etc/inc/config.inc#L162-L165

In order for the backup device to do anything with the new settings, you should already go to the ha status page (which also transfers the settings).

Most legacy pages already inform the user about this fact:

https://github.com/opnsense/core/blob/f0495cdedc8f0c1f57651d0f878d1387919f1adb/src/www/guiconfig.inc#L296-L300

**Comment by mimugmail** [comment]
Technically it's a step backwards, on the other side when there is a warning with the link like you mentioned I'm fine with it. My only concern is that every customer I told auto sync always work for firewall rules. :) 

I'd love to see something like forcing HA sync off when other node is unreachable, but no idea how to realize this.

In sum, for me it's ok .. maybe consider it a major change (-> 20.1).

**Comment by AdSchellevis** [comment]
>  My only concern is that every customer I told auto sync always work for firewall rules. :)

That's only the sync, it doesn't reload at the moment.... which is actually a good thing in my opinion, if you wreck the master, you still have the ability to fix the backup.

We always tell our customers to sync after (important) changes.

> I'd love to see something like forcing HA sync off when other node is unreachable, but no idea how to realize this.

Some cron job forcing a sync every X interval might probably be a better alternative, at the mimim it should be a separate process (which it now isn't and can slowdown your changes).
I'm not planning to build something for this.

> In sum, for me it's ok .. maybe consider it a major change (-> 20.1).

Let's mature this for a moment, it's not pressing to do this now, although I have seen multiple installations with issues caused by this. I kind of forgot about it, originally we intended to do this in 19.7.

**Comment by Kimmax** [comment]
I too thought for some reason sync would be all automagically last time I installed a HA setup and had to rediscover that you have to manually sync.
Arguments for no auto-sync are solid, I would +1 for the extra hint and manual sync with the extra option to setup a cronjob for it

**Comment by mimugmail** [comment]
> That's only the sync, it doesn't reload at the moment.... which is actually a good thing in my opinion, if you wreck the master, you still have the ability to fix the backup.

Good argument, haven't thought about this yet

> Some cron job forcing a sync every X interval might probably be a better alternative, at the mimim it should be a separate process (which it now isn't and can slowdown your changes).
> I'm not planning to build something for this.

It would break argument above, so using cron isn't the best idea, correct.

> Let's mature this for a moment, it's not pressing to do this now, although I have seen multiple installations with issues caused by this. I kind of forgot about it, originally we intended to do this in 19.7.

Good! I appreciate latest issues and PR opened the last weeks, more better to track than just  commits, thank you! :)

**Comment by stumbaumr** [comment]
I would prefer to have the autosync configurable. So since there is already a checkbox for each module to sync or not to sync you could create another checkbox to autosync after apply is pressed.

And since it is configurable to sync a module - maybe include parts of Interfaces (not the interface specific IP address ;-) ), but like the assignments, names, etc. Most proper HA setups are on technical identical machines...
