### ISSUE TITLE
CARP: optionally promote/demote on service status

### ISSUE THREAD

**Issue by AdSchellevis** [opnsense/core#3636]
Currently carp status is only determined by its own settings and the status of pfsync, in some cases it would be practical if we could trigger demotion similar to pfsync (when service(s) not ready, keep demotion factor on X)

One of the use-cases where we would need such behaviour is for carp promotion when ospf (via frr) isn't available yet. (OpenBSD has a specific feature for this https://man.openbsd.org/ospfd.conf.5 --> demote)

The facility we like to introduce here should make it possible to have events that add/subtract a predefined "services ready" factor to carp demotion.

On boot-up, the happy flow should probably look something like:

1. ***system boot***
2. set initial demotion value using `early` event (probably be the output of our new facility function)
3. ***continue boot****
4. kernel event: pfsync ready, subtracts `net.pfsync.carp_demotion_factor` from `net.inet.carp.demotion`
5. `emit event`: service started (might be some script hook to signal change)
6. `catch event`: set demotion based on "service(s) read"

There are some details that need further thinking, such as what happens in maintenance mode and how to make sure service events are properly catched.

**Comment by AdSchellevis** [comment]
The initial version is pushed in https://github.com/opnsense/core/commit/bd07529372d28edcd0b71be987cc71b7ae9cb525 + https://github.com/opnsense/core/commit/25c36b004e52add884b11fd5b7e2061d5364d571, install https://github.com/opnsense/core/commit/853a4392c11f8ae22c50dac89006172b64df45d1 as well to make sure the carp status page shows "demotion" as well for easier testing.

Install on OPNsense 19.7.2
```
opnsense-patch 853a439 bd07529 25c36b0
service configd restart
```

Next create a test check script, which always exits with a status 1

```
mkdir /usr/local/etc/rc.carp_service_status.d
vi /usr/local/etc/rc.carp_service_status.d/test1234
```
With content like this:
```
#!/bin/sh
exit 1
```

Make sure it's executable:
```
chmod 755 /usr/local/etc/rc.carp_service_status.d/test1234
```

Check demotion before triggering event (updated carp status page):
![image](https://user-images.githubusercontent.com/9783985/62788845-0f093d00-bac8-11e9-9d2b-2436bb835010.png)

Emit event:
```
configctl interface update carp service_status
```


![image](https://user-images.githubusercontent.com/9783985/62788901-247e6700-bac8-11e9-80f8-d0d5a5c42548.png)

Next reboot the device and it should be demoted after boot, because of the early boot event.

**Comment by ruffy91** [comment]
Don't forget that it's possible that both master and backup have demotion because for example a service has been misconfigured and cannot start or both are rebooting and services are not yet up.
Your last screenshot shows just that.
The message says it has been demoted but both VIP are still master.

**Comment by AdSchellevis** [comment]
@ruffy91 our description is indeed not correct, demoted doesn't say anything about it's status within the cluster. We probably should change the text at some point (although it's not very important).

**Comment by AdSchellevis** [comment]
merged into master, needs a bit of documentation, see issue https://github.com/opnsense/docs/issues/193
