### ISSUE TITLE
Static routing issue

### ISSUE THREAD

**Issue by Math43** [opnsense/core#3637]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[x] I have searched the existing issues and I'm convinced that mine is new.

**Describe the bug**
Bad static routing decision is taken while routing table is correct.

Here is my routing table extract:
root@OPNsense:~ # netstat -r4
Routing tables
Internet:
Destination        Gateway            Flags     Netif Expire
default                  A.B.C.D               UGS        vmx3
100.64.0.0/24      172.18.4.21        UGS        vmx1
172.21.0.0/16      172.18.4.20        UGS        vmx1

I'm able to reach 100.64.0.0/24 but not able to reach 172.21.0.0/16, there is the traceroute:
root@OPNsense:~ # traceroute 172.21.169.103
traceroute to 172.21.169.103 (172.21.169.103), 64 hops max, 40 byte packets
 1  172.18.4.21 (172.18.4.21)  0.523 ms  0.262 ms  0.200 ms
 2  *  * *
Wrong next hop is choosen. If I change Gateway priority of the two gateway (172.18.4.21 / 172.18.4.20), the behavior is reversed (172.21.0.0/16 is reachable but not 100.64.0.0/24)

**To Reproduce**
Create two gateways in the same subnet,
Route one subnet via the first gateway and second subnet via the second gateway

**Relevant log files**
Don't know which log file could help to identify the issue.

**Additional context**
I've already asked some forum members if they knew the issue or how to solve it. But nobody else seems to have this issue.

**Environment**
OPNsense 19.7.2 
(was working on 19.1)

**Comment by AdSchellevis** [comment]
sounds like a policy based routing issue, best check (automatic) firewall rules first.

**Comment by Math43** [comment]
Hello AdSchellevis, 

Effectively, after a tcpdump, i find my packet matching this rule:
@73 pass out log on vmx1 route-to (vmx1 172.18.4.21) inet from 172.18.4.25 to ! (vmx1:network:1) flags S/SA keep state allow-opts label "2ff18b6378c052f6d36a245571286063"

How to find corresping rule in WebUI ?

Regards,
Math

**Comment by AdSchellevis** [comment]
@Math43 no problem, that was what I meant :) (you should see the rule on your wan connection under automatic rules as well)
