### ISSUE TITLE
Auto-added VPN rules don't work as expected

### ISSUE THREAD

**Issue by bodote** [opnsense/core#3638]
**Important notices**
[yes] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
[yes] I have searched the existing issues and I'm convinced that mine is new.
**Describe the bug**
http://xx/firewall_rules.php?if=wan
http://xx/vpn_ipsec_settings.php#disablevpnrules

the "Auto-added VPN rules" don't work, IPSec connection can not be established. 
Only when additional manual firewall rules for UDP port 500 and 4500  (see screenshots below) are added, then connection works.

**To Reproduce**
on VirtualBox: 2 OpnSense  called RT-1 and RT-3 , connected directly by host - only network, having connection (ping works) 
configure a VPN connection:
RT-1 : start immediately , RT-3. respond only
key exchange auto, Nat-Traversal: disabled 
Auto-added VPN rules NOT disabled
remaining config items using default settings.

ERROR: you can see rejected packets in the rules-log for ports 500 and 4500 until manual rules are added.

**Expected behavior**
Auto-added VPN rules should work in a way that at least in this simple setup the IPSec connection can be established. Otherwise the "Auto-added VPN rules" should be removed entirely

**Screenshots**

![Bildschirmfoto 2019-08-10 um 21 46 09](https://user-images.githubusercontent.com/8531026/62826385-da29e280-bbba-11e9-8c52-ec7aab4461cb.png)

![Bildschirmfoto 2019-08-10 um 21 43 24](https://user-images.githubusercontent.com/8531026/62826405-09405400-bbbb-11e9-88de-22f152bdfafb.png)

**Environment**
Software version used and hardware type if relevant.
OPNsense 19.7.1-amd64
FreeBSD 11.2-RELEASE-p11-HBSD
OpenSSL 1.0.2s 28 May 2019
VirtualBox 6.0.10
EDIT: 
i didn't see that the 4th automatic generated rule is actually for ESP not UDP, so the actual bug is that there is the UDP rule for port 4500 missing, because this seems to be necessary at least during connection negotiation, right?

**Comment by dklimpel** [comment]
I had the same problem.
Nevertheless I had disabled NAT-T for VPN, the VPN tried to use NAT-T.
After I had enabled NAT-T in VPN configuration, i got the auto rule for 4500/UDP. Now it works.

**Comment by bodote** [comment]
...but the forth autogenerated rule even with NAT-T disabled (see screenshot of my first post)  should actually already allow all traffic from 192.0.2.1 for all ports including 4500/udp, but it does not , right ?

**Comment by dklimpel** [comment]
The fourth rule ist ESP not UDP and does not allow 4500/udp.

**Comment by bodote** [comment]
ok, thank you for point that out, see my edit in the original post

**Comment by AdSchellevis** [comment]
@dklimpel are you sure NAT-traversal is not set to off (in your phase 1)?

![image](https://user-images.githubusercontent.com/9783985/62832221-4f350080-bc2b-11e9-8e19-b6f31b93fd36.png)

![image](https://user-images.githubusercontent.com/9783985/62832226-67a51b00-bc2b-11e9-85a4-f07555d2b0aa.png)


https://github.com/opnsense/core/blob/cfead4c8a8bd9568fdaae248fc6e32e4b435c757/src/etc/inc/plugins.inc.d/ipsec.inc#L271-L284

**Comment by dklimpel** [comment]
In my opinion everything ist fine with FW rules. When I turn on NAT-T in phase 1 then is there a FW rule 4500/udp. And when I turn off NAT-T then ist there no FW rule 4500/udp.

I was suprised that, when NAT-T is turn off in phase 1, IPsec try to connect with 4500/udp. I have two opnsense with direct internet access PPPoE without NAT. I had no problem. I had turn on NAT-T and everything was fine for me.

**Comment by mimugmail** [comment]
Impossible to debug without logs. If one side decides it's behind Nat it will tell other side and they try port 4500.

**Comment by bodote** [comment]
Nat-Traversal is intentionally disabled, since both OPNSense are connected to the same VirtualBox -host - only network without any NAT in between. Nevertheless the UDP 4500 seems essential for the connection.

**Comment by dklimpel** [comment]
https://wiki.strongswan.org/projects/strongswan/wiki/NatTraversal

> If a NAT situation is detected, the client switches to UDP port 4500 to send the IKE_AUTH request (only if it used port 500 initially, see below regarding custom ports) and UDP encapsulation will be activated for IPsec SAs.

> NAT-T cannot be disabled in the charon IKE daemon. If you don't like the automatic port floating to UDP/4500 due to the MOBIKE protocol, which happens even if no NAT situation exists, then you can disable MOBIKE by disabling the mobike option in your connection definition.

**Comment by bodote** [comment]
if usage of UDP port 4500 depends on the MOBIKE protocol, then the auto added filter rules should depend on this parameter, in that regard, right ?

**Comment by AdSchellevis** [comment]
no, if you disable Nat-Traversal explicitly (which isn't an option in Strongswan itself), it won't be enabled in the rule.... simple as that. can we close this support ticket? just set the option to "enable" (not force), which is the default, and it works as expected (without leading to a different ipsec config).  


https://github.com/opnsense/core/blob/d241a6413873999486cff0423a82dc0fc313066e/src/etc/inc/plugins.inc.d/ipsec.inc#L1326-L1329

**Comment by bodote** [comment]
ok
