### ISSUE TITLE
cURL work only via default gateway

### ISSUE THREAD

**Issue by definitio** [opnsense/core#3639]
**Describe the bug**
After 19.7.2 update cURL can't connect via non default gateway.

**To Reproduce**
1. Run `curl --interface <non default interface> opnsense.org`
2. See error: `curl: (7) Failed to connect to opnsense.org port 80: Operation timed out`

**Expected behavior**
cURL should work via non default gateways too, as it was before update.

**Comment by AdSchellevis** [comment]
@definitio very likely this https://github.com/opnsense/core/commit/7bfadb2acd4660b05d11059152dec7d88a90b288.

In which case, the following commands should fix it:
```
opnsense-patch 7bfadb2
/usr/local/etc/rc.filter_configure 
```

**Comment by definitio** [comment]
It works. Thanks!

**Comment by FingerlessGlov3s** [comment]
Works a treat, Thank you!!

**Comment by mr44er** [comment]
Pulled some hair out to find this.

I had the **very** same problem with openvpn as client, which did not respect the gw of the interface it should bind to! -> https://github.com/opnsense/core/issues/3588

This fix with the old behaviour is really important!

Now openvpn-client and dyndns works again! :)
