### ISSUE TITLE
Option to boot directly into installer

### ISSUE THREAD

**Issue by Kimmax** [opnsense/core#3641]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[x] I have searched the existing issues and I'm convinced that mine is new.

**Is your feature request related to a problem? Please describe.**
Having to walk through the network setup routine and then login as `installer` to get the setup started seems counter-intuitive. 

**Describe the solution you'd like**
I think having an extra entry in the boot menu to directly boot into the installer would be, in my opinion, optimal.

**Describe alternatives you've considered**
I'm not sure about alternative solutions to handle this better.

**Comment by fichtner** [comment]
Hi @Kimmax,

I have no knowledge of boot loader being able to control the rc sequence or even auto-login an installer user without a password. There's at least 4 easy ways to get to the installer but if typing a username and password is already too much I'm out of ideas I'm afraid.

Some people have complained that they do not want to auto-boot installers. Others do. I do not know what most users want and hopefully it aligns with what we already have.


Cheers,
Franco

**Comment by Kimmax** [comment]
Hi @fichtner,

I don't think logging in as _installer_ is a bad way to do it, however what I find me doing is booting the live environment, walking through the (shell) wizard to setup LAN/WAN IPs/Interfaces etc. only to immediately start the installer and doing the same steps again after booting from the actual boot disk.

What I thought would be an improvement is being able to directly jump to the installer and do the whole initial setup once after booting the real installed system.

Now that I think of it persisting the settings from the live boot to the installed image might be a way to do it too / maybe as an option to copy the config over after installing

I don't know how the boot process works in FreeBSD, for Debian like systems I'd pass a custom script to `init=` as kernel parameter from grub, that could handle the install process. But I'm also not familiar with the OPNSense install process, so no idea if that would be even applicable here.

It's really just an idea, nothing else

**Comment by fichtner** [comment]
> Now that I think of it persisting the settings from the live boot to the installed image might be a way to do it too / maybe as an option to copy the config over after installing

Are you sure?  The install will clone the live system. It has been this way for a long time so that you can even reach the GUI, configure more advanced stuff and when it feels right install onto the disk with all configuration in place.

**Comment by Kimmax** [comment]
This sounds exactly like what I would like to see, so if it's already there I don't know what I did wrong the last few installs.. 
Looks like I'll have to test it out once again and see what's up with my mind heh

**Comment by fichtner** [comment]
If you can reproduce let me know the steps so I can double-check. Thanks! ❤️
