### ISSUE TITLE
Download logs button

### ISSUE THREAD

**Issue by banym** [opnsense/core#3645]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[-] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[-] I have searched the existing issues and I'm convinced that mine is new.

**Is your feature request related to a problem? Please describe.**
When you check logs, it only shows you the defined amount of lines from the log. This helps if the error you are looking for happened recently but there is no direkt way to get the old entries of the log file.

**Describe the solution you'd like**
A download logs functionality would be nice. This could download the current logs or there can be an overview page where you can download all logs and the rotated versions as a .zip file.

**Describe alternatives you've considered**
An alternative could be a log overview page with pagination functionality and search functionality by date and age of entries. This would it make easier to debugg erros happened in the past if no central logging is in place.

**Comment by AdSchellevis** [comment]
the raw logs likely won't be of much use, since they are circular (needs `clog` to read), you might consider sending logs to a remote syslog server, which is actually quite easy to setup.

**Comment by banym** [comment]
Then maybe the log view could be generated as download for a defined count of lines or the complete available log? 

I know the logserver would be a better solution, in some cases when I face a problem where the firewall from time to time is not online, the messages directly on the box are helpfull.

**Comment by AdSchellevis** [comment]
the new log view will have a button to download the visible items.

![image](https://user-images.githubusercontent.com/9783985/70260538-cc632300-1790-11ea-95aa-e69a2bf836bc.png)
