### ISSUE TITLE
Gateway Group and Local Ping

### ISSUE THREAD

**Issue by cmb991** [opnsense/core#3646]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[X] I have searched the existing issues and I'm convinced that mine is new.

**Describe the bug**
After setting up a gateway group of two WAN connections, and going to your LAN rules, changing their gateway to the gateway group, you can no longer ping your local gateway.

**Comment by AdSchellevis** [comment]
With policy based routing, don't forget to exclude local traffic.
