### ISSUE TITLE
DSCP value not manipulated

### ISSUE THREAD

**Issue by vlcty** [opnsense/core#3647]
**Describe the bug**
I'm currently debugging a problem (not OPNsense related) with a client sending IP packets with a DSCP value of 4 (Video). To check if that's really the problem I wanted to clear that field and set it to 0 aka "Best effort".   
Under "Advanced Options" there is an action called "Set priority" which does exactly what I wanted to do. However when creating a rule and applying it a network trace shows that the value is not touched by OPNsense.

The clients IPv4 address is 10.20.10.42 and is located on the LAN interface.

**To Reproduce**
1. Go to Firewall -> Rules -> LAN -> Add
2. Set "Source" to 10.20.10.42, "TCP/IP Version" to IPv4 and "Protocol" to "any" 
3. Open "Advanced Options"
4. Set unter "Set priority" -> "All packets" to "Best Effort (0, default)" and "Low Delay/TCP ACK" also to "Best Effort (0, default)"
5. Tick the option "Log packets that are handled by this rule"
6. Safe the rule, move it so it's the first rule and apply the changes
7. Start a network trace and let the client produce traffic

**Expected behavior**
The DSCP value is set to 0.

**Actual behavior**
A network trace on LAN and/or WAN shows that the DSCP value is untouched and still 4. According to the firewall log the rule is evaluated and matched/executed.

**Screenshots**
none

**Relevant log files**
none

**Additional context**
NAT is done between LAN and WAN.

**Environment**
Updated OPNsense today to the latest Version. I've virtualized it using KVM with VirtIO network cards on an Archlinux hypervisor. The virtualized LAN and WAN interfaces are regular layer 3 interfaces (no VLAN inside OPNsense). On the host they are both attached to regular bridges. I've done the tracing directly with OPNsense and additionally on the bridges.

OPNsense 19.7.2-amd64   
FreeBSD 11.2-RELEASE-p12-HBSD   
OpenSSL 1.0.2s 28 May 2019

**Comment by mimugmail** [comment]
Always thought this is ToS and not CoS/DSCP. Can you check this?

**Comment by vlcty** [comment]
According to my research the TOS field in IPv4 was redefined to DSCP some time ago and the values are somehow mapped.

**Comment by AdSchellevis** [comment]
If I'm reading the manual correctly, set prio only tags vlan's 

our help text:
```
Set the priority of packets matching this rule. If both priorities are set here, packets with a TOS of "lowdelay" or TCP ACKs with no data payload will be assigned the latter. If the packets are transmitted on a VLAN interface, the queueing priority will be written as the priority code point in the 802.1Q VLAN header.
```

man pf.conf:

```
     set prio priority | (priority, priority)
           Packets matching this rule will be assigned a specific queueing
           priority.  Priorities are assigned as integers 0 through 7.  If the
           packet is transmitted on a vlan(4) interface, the queueing priority
           will be written as the priority code point in the 802.1Q VLAN
           header.  If two priorities are given, packets which have a TOS of
           lowdelay and TCP ACKs with no data payload will be assigned to the
           second one.

           For example:

                 pass in proto tcp to port 25 set prio 2
                 pass in proto tcp to port 22 set prio (2, 5)

```

You should be able to set a tos for a specific value using (Firewall -> Settings -> Normalisation) by the way.

tcp dump without normalisation:
```
07:25:11.629662 IP (tos 0x0, ttl 64, id 0, offset 0, flags [DF], proto ICMP (1), length 84)
    xxx.xxx.xxx.xxx > xxx.xxx.xxx.xxx: ICMP echo reply, id 40798, seq 104, length 64
```

tcp dump with tos set to 0x2c:
```
07:40:40.285918 IP (tos 0x2c, ttl 63, id 0, offset 0, flags [DF], proto ICMP (1), length 84)
    xxx.xxx.xxx.xxx > xxx.xxx.xxx.xxx: ICMP echo request, id 40276, seq 1, length 64
```

**Comment by vlcty** [comment]
I can confirm that the normalisations settings do what I want. Thanks for that! I'm closing this now.
