### ISSUE TITLE
Import Amazon VPC configuration file to setup IPSec VPN

### ISSUE THREAD

**Issue by ringods** [opnsense/core#365]
When using Amazon Virtual Private Cloud (VPC), after creating the VPN Connection, one can download the configuration:

http://docs.aws.amazon.com/AmazonVPC/latest/UserGuide/VPC_VPN.html

The configuration file can be downloaded in a number of different formats. It would be handy that OPNsense could support one of these formats as to setup an IPSec VPN connection just by importing that file.

**Comment by AdSchellevis** [comment]
timeout

**Comment by jeremyforan** [comment]
+1 . this would be really great.
