### ISSUE TITLE
netflow: set active/inactive timeout

### ISSUE THREAD

**Issue by fbrendel** [opnsense/core#3650]
I'd like to set the active/inactive timeouts for the [NetFlow](https://www.freebsd.org/cgi/man.cgi?query=ng_netflow&apropos=0&sektion=4&manpath=FreeBSD+11.2-RELEASE&arch=default&format=html) exporter.
The default active timeout of 30 minutes is to long and 15 seconds for inactive is to short for us.

**Comment by AdSchellevis** [comment]
I'm not sure we could influence this easily with `ng_netflow`, maybe the man page could help you out https://www.freebsd.org/cgi/man.cgi?query=ng_netflow

To fiddle with settings, change `/usr/local/etc/rc.d/netflow` and reload should do the trick.

Netgraph isn't really easy unfortunately.

ps: would you be so kind to use our templates for feature requests in the future?

**Comment by fbrendel** [comment]
> I'm not sure we could influence this easily with `ng_netflow`, maybe the man page could help you out https://www.freebsd.org/cgi/man.cgi?query=ng_netflow

It's easy to implement and I can do that.
I just made this feature request to be sure it's documented and no one is already working on it :wink: 
 
> ps: would you be so kind to use our templates for feature requests in the future?

Yes, of course. Was a bit too lazy to fill in the form for this little request. Sorry.

**Comment by AdSchellevis** [comment]
Added in https://github.com/opnsense/core/pull/3651, for reference, default values remain unchanged with the new code (I couldn't find the defaults in the man page):

https://github.com/opnsense/src/blob/8d1a9170bd4d9d50ffeecc2c8366ec34b8ebdb02/sys/netgraph/netflow/netflow.h#L33-L34
