### ISSUE TITLE
OpenVPN Disable Gateway Checkbox

### ISSUE THREAD

**Issue by cmb991** [opnsense/core#3652]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[X] I have searched the existing issues and I'm convinced that mine is new.

**Describe the bug**
Once you configure the OpenVPN server, if you check the box for gateway and put an IP in it, then save it.  If you edit the OpenVPN server and try to uncheck gateway checkbox, it remains checked after saving.

**Comment by AdSchellevis** [comment]
you mean "Redirect Gateway"? doesn't appear to have an issue on my end.

**Comment by cmb991** [comment]
No, if you check the box to put in a custom DNS server and you put a server in (1.1.1.1).  Then save your settings.
Then go back to edit the open vpn server and Uncheck the dns server box and save your settings.
Now edit it one more time and the dns settings are still there even though you unchecked the box.

**Comment by AdSchellevis** [comment]
You're being a little bit confusing here, "gateway checkbox" isn't the same as "dns checkbox".... These toggles on screen only hide the data underneath it seems, which probably is the case for all of them.

https://github.com/opnsense/core/blob/a21baa1d854c23106dbe31459d1050e3b0cda577/src/www/vpn_openvpn_server.php#L560-L566

Just clear the values and you should be good to go.

**Comment by cmb991** [comment]
I’ll upload a video in the morning.  I didn’t mean the gateway box, I meant the DNS box.  If you put a DNS server in there and save, you can edit the server but if you try to uncheck the dns box (clear the value) and save again, it doesn’t remove the dns values.  They are still there if you go to edit the server again.

**Comment by AdSchellevis** [comment]
just clear the values.... the checkboxes are a bit deceiving there as said.

**Comment by cmb991** [comment]
Ah that did it.  So just unchecking the box won’t clear the value.  You just have to clear the value and save.  I figured unchecking the box would clear the value.

**Comment by AdSchellevis** [comment]
Yes indeed, those checkboxes kind of act like the "advanced" button in some of the legacy pages. A more consistent mode of operation would be nicer indeed, but it's not high enough on our priority list at the moment. 

You could try to open an issue with a somewhat better description, so we can tag it "help wanted" and see if someone likes to pick it up. I'm closing this one for now.
