### ISSUE TITLE
Cron job not running to schedule

### ISSUE THREAD

**Issue by fenice2** [opnsense/core#3654]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[x] I have searched the existing issues and I'm convinced that mine is new.

I had a problem creating a cron job to run a regular script, it's described in this forum thread: 
https://forum.opnsense.org/index.php?topic=13831.msg63646#msg63646 

I marked that thread as 'resolved' because the cron job started working, however after leaving it running for a while it seems the job is not running to schedule.

After the job started running regularly and left overnight I checked to see if it was OK but noticed that instead of running every thirty minutes it was running every hour.

As I'm not too knowledgable on the internals of OPNsense and I may have made some incorrect assumptions here.

I dumped the cron file (hopefully the correct one):

cat /var/cron/tabs/nobody
```
# DO NOT EDIT THIS FILE -- OPNsense auto-generated file
#
# User-defined crontab files can be loaded via /etc/cron.d
# or /usr/local/etc/cron.d and follow the same format as
# /etc/crontab, see the crontab(5) manual page.
SHELL=/bin/sh
PATH=/etc:/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin
#minute hour    mday    month   wday    command
# Origin/Description: IDS/ids rule updates
19      3       *       *       0       /usr/local/sbin/configctl ids update 
# Origin/Description: cron/Reset WAN Interface if down
*       *       *       *       *       /usr/local/sbin/configctl firmware auto-update 
# Origin/Description: cron/Freebox connectivity check
15      *       *       *       *       /usr/local/sbin/configctl freeboxcheck reload 
# Origin/Description: cron/Freebox 5min Check
5       *       *       *       *       /usr/local/sbin/configctl freebox5mincheck reload 
```

There are two jobs that are of interest, the first is the 'freeboxcheck', that's set to run every 15 minutes in this test but as you can see from the log, it's running every hour:

```
Aug 18 00:15:13 opnsense01 freebox-check: Gateway non-responsive to ping. Date: Sun Aug 18 00:15:13 UTC 2019 
Aug 18 00:15:15 opnsense01 freebox-check: DNS1 responded to ping. Date: Sun Aug 18 00:15:15 UTC 2019 
Aug 18 01:15:13 opnsense01 freebox-check: Gateway non-responsive to ping. Date: Sun Aug 18 01:15:13 UTC 2019 
Aug 18 01:15:15 opnsense01 freebox-check: DNS1 responded to ping. Date: Sun Aug 18 01:15:15 UTC 2019 
Aug 18 02:15:13 opnsense01 freebox-check: Gateway non-responsive to ping. Date: Sun Aug 18 02:15:13 UTC 2019 
Aug 18 02:15:15 opnsense01 freebox-check: DNS1 responded to ping. Date: Sun Aug 18 02:15:15 UTC 2019 
Aug 18 03:15:13 opnsense01 freebox-check: Gateway non-responsive to ping. Date: Sun Aug 18 03:15:13 UTC 2019 
Aug 18 03:15:15 opnsense01 freebox-check: DNS1 responded to ping. Date: Sun Aug 18 03:15:15 UTC 2019 
```
The second job is just the same as the first but set to run every five minutes, here's the log for that:

```
Aug 18 00:05:13 opnsense01 freebox-check_5min: Gateway non-responsive to ping. Date: Sun Aug 18 00:05:13 UTC 2019 
Aug 18 00:05:15 opnsense01 freebox-check_5min: DNS1 responded to ping. Date: Sun Aug 18 00:05:15 UTC 2019 
Aug 18 01:05:13 opnsense01 freebox-check_5min: Gateway non-responsive to ping. Date: Sun Aug 18 01:05:13 UTC 2019 
Aug 18 01:05:15 opnsense01 freebox-check_5min: DNS1 responded to ping. Date: Sun Aug 18 01:05:15 UTC 2019 
Aug 18 02:05:13 opnsense01 freebox-check_5min: Gateway non-responsive to ping. Date: Sun Aug 18 02:05:13 UTC 2019 
Aug 18 02:05:15 opnsense01 freebox-check_5min: DNS1 responded to ping. Date: Sun Aug 18 02:05:15 UTC 2019 
Aug 18 03:05:13 opnsense01 freebox-check_5min: Gateway non-responsive to ping. Date: Sun Aug 18 03:05:13 UTC 2019 
```
Rebooting OPNsesnse or restarting all the services makes no difference to the schedule of these jobs. If there's anything else needed then let me know and I'll provide it.

I'm currently on the latest release and running in a VM on ESXi 6.7:

OPNsense 19.7.2-amd64
FreeBSD 11.2-RELEASE-p12-HBSD
OpenSSL 1.0.2s 28 May 2019

**Comment by fichtner** [comment]
It’s correct. Your jobs are set to run at 5 and 15 of every hour, every 5 or 15 minutes.

**Comment by fenice2** [comment]
Ah, my problem - I don't seem to know how to configure cron!! Franco, thanks for the quick reply and I'm sorry for the noise and I'll read the manual in a bit more detail. :(

**Comment by fichtner** [comment]
No worries, cron can be confusing. I keep forgetting that hours are second and minutes are first. :)
