### ISSUE TITLE
Empty p12 certificate of imported certificate

### ISSUE THREAD

**Issue by benkuly** [opnsense/core#3660]
**Important notices**
[x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
[x] I have searched the existing issues and I'm convinced that mine is new.

**Describe the bug**
Empty p12 certificate when try to download an imported existing certificate. This seems to lead to failed connections with OpenVPN.

**To Reproduce**
1. Import an existing certifitcate (with private key)
2. Export ca+user cert+user key in .p12 format

**Expected behavior**
No empty .p12 file.

**Environment**
OPNsense 19.7.2-amd64

**Comment by AdSchellevis** [comment]
doesn't happen on my end, can you supply sample data and detailed steps?

**Comment by benkuly** [comment]
I will try to provide sample data as soon as possible. This is the error in the log.

`[19-Aug-2019 19:53:08 Europe/Berlin] Exception: Error at /usr/local/opnsense/mvc/app/library/OPNsense/OpenVPN/BaseExporter.php:68 - openssl_pkcs12_export(): cannot get private key from parameter 3 (errno=2) in /usr/local/opnsense/mvc/app/controllers/OPNsense/Base/ApiControllerBase.php:85
Stack trace:
#0 [internal function]: OPNsense\Base\ApiControllerBase->APIErrorHandler(2, 'openssl_pkcs12_...', '/usr/local/opns...', 68, Array)
#1 /usr/local/opnsense/mvc/app/library/OPNsense/OpenVPN/BaseExporter.php(68): openssl_pkcs12_export(Resource id #41, NULL, false, '', Array)
#2 /usr/local/opnsense/mvc/app/library/OPNsense/OpenVPN/ArchiveOpenVPN.php(83): OPNsense\OpenVPN\BaseExporter->export_pkcs12(Resource id #41, false, NULL, Array)
#3 /usr/local/opnsense/mvc/app/controllers/OPNsense/OpenVPN/Api/ExportController.php(405): OPNsense\OpenVPN\ArchiveOpenVPN->getContent()
#4 [internal function]: OPNsense\OpenVPN\Api\ExportController->downloadAction('1', '5d5ad650c047e')
#5 [internal function]: Phalcon\Dispatcher->callActionMethod(Object(OPNsense\OpenVPN\Api\ExportController), 'downloadAction', Array)
#6 [internal function]: Phalcon\Dispatcher->dispatch()
#7 /usr/local/opnsense/www/api.php(26): Phalcon\Mvc\Application->handle()
#8 {main}`

**Comment by benkuly** [comment]
sorry, my fault. the private key was crypted.
