### ISSUE TITLE
19.7: IPv6 gif tunnel not transitioning away from "tentative" flag

### ISSUE THREAD

**Issue by lattera** [opnsense/core#3662]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[-] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[-] I have searched the existing issues and I'm convinced that mine is new.

**Describe the bug**

**To Reproduce**
1. Install OPNsense 19.7
2. Set up a 6-in-4 gif tunnel, like that provided by TunnelBroker
3. The gif0 interface does not leave the "tentative" state unless the interface is reconfigured (disable and re-enable the interface is enough.)

**Expected behavior**
The gif0 interface should leave the tentative state, especially since DAD doesn't need to be performed given it has a static IPv6 address.

**Screenshots**
I'm still doing some debugging. I'll add screenshots soon.

**Relevant log files**
Let me know what log files, if any, to attach.

**Additional context**
I also noticed that there's no place in the interface's config for custom ifconfig options. It'd be very nice to be able to set custom options to pass to ifconfig.

**Environment**
OPNsense 19.7.2 on a PC-Engines APU4.

**Comment by mr44er** [comment]
Just a guess:

https://github.com/opnsense/core/issues/3639

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/core/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
