### ISSUE TITLE
MTU override is ignored

### ISSUE THREAD

**Issue by fliiiix** [opnsense/core#3663]
**Describe the bug**
MTU override is ignored on gif interface.
As you can see in the screenshot it should be 1230 but
when I check with ifconfig it is 1280. 
(Which is the max mtu when you do MTU discovery, so my theory is that it is overwritten by mtu discovery)

**To Reproduce**
1. Go to a gif interface 
2. set a mtu
3. save and apply
4. check mtu with `ifconfig -a | grep mtu`

**Expected behavior**
The configured MTU should be applied. 

**Screenshots**
![Screenshot_2019-08-21-HE_NET_v6](https://user-images.githubusercontent.com/1682954/63455112-5d192b80-c44c-11e9-920d-b696130f5273.png)

**Environment**

OPNsense 19.7.2-amd64FreeBSD  
11.2-RELEASE-p12-HBSD  
LibreSSL 2.9.2

**Comment by AdSchellevis** [comment]
The minimum for gif is 1280 if I remember correctly:

```
# ifconfig gif0 mtu 1230
ifconfig: ioctl SIOCSIFMTU (set mtu): Invalid argument
```

```
# ifconfig gif0 mtu 1290
```

**Comment by fliiiix** [comment]
Why is that the case? (You are right the smallest value accepted is 1280)  
When even the man page recommends setting it to 1240.
https://www.freebsd.org/cgi/man.cgi?query=gif&sektion=4&manpath=FreeBSD+12.0-RELEASE+and+Ports#BUGS

**Comment by AdSchellevis** [comment]
https://github.com/freebsd/freebsd/blob/c4ed3acb9f59d3498905e95d5d445c5046fdfdb6/sys/net/if_gif.h#L80-L82

**Comment by fliiiix** [comment]
Unfortunate. I will open a bug on the freebsd side. 

Maybe it's worth considering to show any indication of these values in the UI.
