### ISSUE TITLE
Alias Pop Up Change

### ISSUE THREAD

**Issue by LittleSchelle** [opnsense/core#3664]
If i move my mouse over an alias, there comes a pop up that show's me the description of the alias. If i want to see the IP's, Ports, or whatever of the Alias, i need to go to change it.

Can the Pop up be changed, so you move the mouse over the alias and for the first few seconds you see the description of the alias. After that time it changes to show you the IP's. Maybe with a setting for enable this feature and a setting for how many seconds the description will be visible, before it changes to the IP's.

**Comment by mimugmail** [comment]
If the description of Alias is empty you will see the first 10 contents. Best to leave description empty and give itself a descriptive label :)
