### ISSUE TITLE
Gateway change on Default allow LAN to any rule breaks unbound dns and icmp

### ISSUE THREAD

**Issue by zer00k** [opnsense/core#3666]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[X] I have searched the existing issues and I'm convinced that mine is new.

**Describe the bug**
Changing the "Gateway" setting on the LAN firewall policy "Default allow LAN to any rule" breaks unbound dns, the firewall stops responding to icmp etc. on the LAN interface.

I may of missed a setting, but I can't see why it breaks things.
I have a WAN GW from my ISP, and multiple OpenVPN GW's, and want to ensure LAN traffic always uses the ISP GW, and then I will use more specific rules and outbound NAT to force individual clients over their respective OpenVPN links

**To Reproduce**
1. Go to 'LAN firewall policy'
2. Click on 'Default allow LAN to any rule'
3. Scroll down to 'Gateway'
4. Change gateway to WAN_DHCP
4. Unbound DNS stops responding, ping of FW LAN address fails

**Expected behavior**
LAN traffic should use WAN_DHCP gateway.
Services and icmp should remain unaffected

**Environment**

OPNsense 19.7.2-amd64
Vmware ESXi 6.7 latest
Network - vmxnet3 adapters

**Comment by AdSchellevis** [comment]
https://docs.opnsense.org/manual/firewall.html?highlight=policy#policy-based-routing

**Comment by mimugmail** [comment]
Also here: https://docs.opnsense.org/manual/how-tos/multiwan.html

Step 5
