### ISSUE TITLE
Routing over non-primary gateways is currently broken

### ISSUE THREAD

**Issue by drivera73** [opnsense/core#3668]
Hi, all!

I currently have the following configuration in my firewall:

- a physical gateway which leads to the Cable ISP circuit, marked as upstream with priority 1
- a physical gateway which leads to the ADSL ISP circuit as a backup for when Cable goes out, marked as upstream with priority 2
- two virtual gateways (IPv4 and IPv6) from a long-lived OpenVPN site-to-site, called "MASKVPN", _**not**_ marked as upstream, with priority 255
- two virtual gateways (IPv4 and IPv6) from a long-lived OpenVPN site-to-site, called "USVPN", _**not**_ marked as upstream, with priority 255

It turns out that when the primary circuit is up, the firewall is unable to route any traffic through any gateway other than the primary one.

My previous configuration had me configure the two physical gateways as part of a gateway group, for failover. However, failover wasn't working properly (the failover algorithm would try to select a VPN gateway as the next primary, instead of the other physical circuit within the group!!!)... so I was forced to put them all within the same group, with matching priorities to ensure the physical circuits would always be chosen ahead of the virtual ones. I supposed this "feature" is why the new "upstream"+priority approach was taken.

Now, in this previous configuration I was 100% able to ping over both physical links - i.e. if I need to run a ping comparison, traceroute comparison, bandwidth test, etc.  However, now it seems that the firewall itself is unable to route via any of the inactive gateways even though external hosts can definitely route correctly.

For example: if I run a diagnostic ping - either from the UI or the SSH CLI - like the following:

`# ping -S <ip-of-non-default-gateway> -c 3 8.8.8.8`

The result is 100% packet loss.

However, I can definitely ping the remote, custom-set "Monitor IP" for the secondary (standby) interface. This has been confirmed as working. Also, this has an explicit routing entry in the routing table (which could explain why the firewall is able to route through it).

It seems something is either wrong with the routing, or the firewall is not properly tracking "connection state" with regards to these outgoing pings (at least).  Again: this only fails if the ping is done from the firewall itself. Hosts routing through the firewall and being shoehorned into the correct routing choice have no issue in routing traffic over the correct circuits.

However, naturally this puts a damper on the ability to debug issues by running diagnostics directly from the firewall.

Cheers!

**Comment by AdSchellevis** [comment]
duplicate of https://github.com/opnsense/core/issues/3639 ?

**Comment by drivera73** [comment]
It is indeed. The patch fixed the issue (after a reboot, which wasn't mentioned, but no biggie). Thanks!

**Comment by AdSchellevis** [comment]
@drivera73 can you close both issues?

**Comment by drivera73** [comment]
Ah...the button is at the bottom :)  too used to JIRA.  Done with this one!
