### ISSUE TITLE
Upstream gateways not being swapped for failover

### ISSUE THREAD

**Issue by drivera73** [opnsense/core#3669]
Hi.

I've had a few outages recently where the firewall has failed to swap out the primary _**upstream**_ gateway to the secondary upstream gateway.  There are other gateways defined, two per VPN client (on for IPv4, one for IPv6, even though IPv6 is disabled for all of the OpenVPN clients), but none of them are marked as upstream, and they all have a priority of 255. The upstream gateways have a priority of 1 and 2 respectively.

For some reason even though the gateway monitor detects that the "Monitor IP" at the far end of the primary gateway is down, it will not succeed when performing a swapout to the secondary gateway, which is up at the time.

I've [attached the log](https://github.com/opnsense/core/files/3538357/outage.log) for the event to help trace the issue. I think this issue may be related to [this one](https://github.com/opnsense/core/issues/3668) because if dpinger is being unable to validate the status of other gateways by issuing pings (that end up going unanswered), then it's perfectly understandable that it may hang in a state where it fails to make a decision for a long time, and thus fails to execute any failover reconfiguration. But that's just my inexperienced, $0.02 ;)

Cheers!

**Comment by AdSchellevis** [comment]
might also be https://github.com/opnsense/core/issues/3639, patch command is in the issue

**Comment by AdSchellevis** [comment]
close as well?

**Comment by drivera73** [comment]
Confirmed it's #3639 as well. Failover seems to now be working properly. Thanks!
