### ISSUE TITLE
OPNsense 19.7.2-amd64 in Xenserer 7.1 hangs on command sysctl -A

### ISSUE THREAD

**Issue by GiviLaph** [opnsense/core#3675]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[-] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[-] I have searched the existing issues and I'm convinced that mine is new.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Relevant log files**
If applicable, information from log files supporting your claim.

**Additional context**

**Environment**
Software version used and hardware type if relevant.
e.g.:

OPNsense 19.1.1 (amd64, OpenSSL).
Intel® Xeon™ E3-1225V5 3.3Ghz Quad Core
Network Intel® I210-AT

**Comment by GiviLaph** [comment]
Hello!
1) OPNsense 19.7.2-amd64 VM in Xenserer 7.1 (all updates and xentools are installed). 
2) Type sysctl -A in Xencenter VM console or in ssh console.
3) VM hangs with 100% CPU load. Only Force Reboot from Xencenter helps.
Thank you!
Best Regards,
Oleg.

**Comment by fichtner** [comment]
Hi Oleg,

It is worth testing the behaviour on FreeBSD or HardenedBSD and report the issue there if it persists. It's not something that is in the scope of our project.

We can, however, take patches if they exist in said projects. :)


Cheers,
Franco

**Comment by GiviLaph** [comment]
Hi, Franco!

1. The same Xenserer 7.1 and VM with FreeBSD 10.2-RELEASE on it (xentools are installed).
2. sysctl -A in Xencenter VM console or in ssh console.
3. Everything works fine.

Sysctl command is very usefull when diagnosting or tuning the system. For example https://forum.opnsense.org/index.php?topic=6590.0

sysctl -A # Shows system variables

Unfortunately, i haven't any hardware server to test OPNsense 19.7.2-amd64 and sysctl -A command.

Thank you!
Best Regards,
Oleg.

**Comment by fichtner** [comment]
OPNsense 19.1/19.7 uses HardenedBSD 11.2. You can also try FreeBSD 11.2, but 10.2 won't give us a good data point.
