### ISSUE TITLE
Remove SHA1 as an option when creating certificates

### ISSUE THREAD

**Issue by johnaheadley** [opnsense/core#3687]
**Describe the bug**
SHA1 is deprecated and considered insecure by all major browsers. 

[Chrome](https://security.googleblog.com/2016/11/sha-1-certificates-in-chrome.html) - January 2017
[Firefox](https://blog.mozilla.org/security/2017/02/23/the-end-of-sha-1-on-the-public-web/) - February 2017
[IE](https://blogs.windows.com/msedgedev/2016/11/18/countdown-to-sha-1-deprecation/) - May 2017

New certificates will not be issued by public CAs with SHA1.

[Digicert](https://knowledge.digicert.com/generalinformation/INFO3977.html) - January 2016
[GoDaddy](https://www.godaddy.com/help/information-about-requiring-the-sha-2-hash-function-4818) - January 2017

SHA1 should be removed from the list of digest algorithms when creating a new client/server certificate or CA.

**To Reproduce**

Navigate to System > Trust > Certificates or System > Trust > Authorities and select New.

SHA1 is listed as a choice of digest algorithm.

**Expected behavior**
OPNsense should not allow the administrator to create a new CA or client/server certificate using the SHA1 digest algorithm. 

**Screenshots**
![Screen Shot 2019-08-31 at 9 14 19 AM](https://user-images.githubusercontent.com/11711559/64066516-bcef9f00-cbcf-11e9-883a-bd48812d29b9.png)

**Additional context**
I can remove SHA1 in PR #3649, if you all agree on the removal.

**Environment**
OPNsense 19.7.2

**Comment by AdSchellevis** [comment]
I'm not sure we should remove the option to create those, some old equipment might need it and openssl also supports it. If we vote for remove, I would say, only in a major upgrade.

**Comment by fichtner** [comment]
Defaults change, options remain...

**Comment by johnaheadley** [comment]
The user could always import a SHA1 certificate if needed even if we removed SHA1 from OPNsense's cert creation menus, but I understand that you want to offer the option in case someone needs it.

Also, I see that 3rd party NACs, like Aruba ClearPass, still offer SHA1 as an option, so I guess we would be breaking the norm to remove it. I will go ahead and close this out!
