### ISSUE TITLE
Upstream gateway failover works only once

### ISSUE THREAD

**Issue by drivera73** [opnsense/core#3688]
**Describe the bug**
This issue is related to [this one](https://github.com/opnsense/core/issues/3669) which was thought to be fixed, but apparently isn't. I've managed to resolve the routing issues laid out in [this other issue](https://github.com/opnsense/core/issues/3670), and thought failover was fixed as a result.

Apparently, it's not. [Log attached](https://github.com/opnsense/core/files/3562851/no-failover.log).

**To Reproduce**
1. Configure a dual-WAN setup with monitor IPs for each gateway **_inside_** the "far" network for each gateway, different from the actual gateway IPs for each network, herein referred to as MonIP-A for network A, and MonIP-B for network B.
2. Configure GW-A and GW-B to be upstream, with priorities 1 and 2 respectively
3. Ensure both MonIP-A and MonIP-B are both fully accessible to ping from the firewall (for monitoring)
4. Validate that GW-A is selected as the default route
5. Save and apply the GW settings
5. Disable ping traffic to MonIP-A, observe failover happen
6. Enable ping traffic to MonIP-A, observer failback happen
7. Disable ping traffic to MonIP-A, observe failover **_NOT_** happen, despite ping connectivity not being available to MonIP-A

In some cases I've even observed the firewall UI properly show that failover has happened, but in reality it has not (i.e. netstat -rn still shows the default gateway pointed to GW-A when it should have pointed to GW-B ... this is reflected in the [log attached](https://github.com/opnsense/core/files/3562851/no-failover.log)).

**Expected behavior**
Failover should happen automatically any number of times required

**CAVEAT:** I've noticed that if I modify a setting in the gateway configuration, that seems to "reset everything" and failover will work again after that ... _**ONCE**_...

**Relevant log files**
[Relevant log files](https://github.com/opnsense/core/files/3562851/no-failover.log).

**Additional context**
A power outage and failure on the Cable link was the trigger (as shown in the logs), but apparently there was another outage overnight which would have triggered the "correct failover", causing this "second failover" to not execute properly.  The issue here seems to be that for some reason dpinger is getting hung up.

I noticed that even though MonIP-A is provably inaccessible, even after 5 minutes the gateways page continues to report GW-A as up, and even keeps the packet loss numbers updated when they couldn't possilby be.

The way I'm testing the ping accessibility is by directly disabling ping access in the machine selected as the monitoring IP (i.e. it's a Linux box with Shorwewall, and I enable/disable Ping acceptance as required).

**Environment**
OPNsense 19.7.2-amd64 (with patch 7bfadb2)
FreeBSD 11.2-RELEASE-p12-HBSD
OpenSSL 1.0.2s 28 May 2019
Protectli FW4B with 8GB RAM and 256GB SSD

**Comment by mr44er** [comment]
>OPNsense 19.7.2-amd64

Try 19.7.3 first, it's out for some days.
Also try to de-set upstream on both gateways and only work with priority.

You have 'allow to change default gw' activated?

**Comment by drivera73** [comment]
Just updated to 19.7.3, and still having this issue. Also, 19.7.3 doesn't seem to be automatically updating the Gateways page every few seconds as the previous version did.

Allow change default GW is activated.

Disabled "upstream" on both gateways, and made no difference.

Made sure that the MonIP-A machine's (the one I'm using to simulate the outages with) connection states were cleared (shorewall restart -p) in case that was polluting things.

However, what DID fix the issue is me changing the monitoring parameters like so:
* reduce the Time Period setting to 30 seconds from the default of 60
* return the packet loss thresholds to the defaults of 10%-20% from 1%-5% (this might have been what did it)

So failover seems to be working normally now.  However, I'm sure the gateways page used to refresh automatically and I'm positive it's no longer doing that, so I might report that separately.

Cheers!
