### ISSUE TITLE
GRE no more reply-to

### ISSUE THREAD

**Issue by sachaz** [opnsense/core#3691]
Since 19.7.3 the packets coming to GRE are outgoing on egress: the GRE is not considered as a gateway interface so there is no more reply-to in the rule:
pass in quick on gre0 inet all flags S/SA keep state label ...
this should be something like: pass in quick on gre0 reply-to (gre0 $gre_gw) inet from any to (gre0)...

**Comment by sachaz** [comment]
there is no more reply-to rule on gre, what do you need more ?

**Comment by AdSchellevis** [comment]
We offer issue templates with questions to answer and kindly ask you to use them. "incomplete" means no template is used, not all questions have been answered, which costs us more time than we likely would spare.

**Comment by fichtner** [comment]
Not using a ticket template.
