### ISSUE TITLE
Fallback configuration activated by timer or missing commit.

### ISSUE THREAD

**Issue by banym** [opnsense/core#3695]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[-] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[-] I have searched the existing issues and I'm convinced that mine is new.

**Is your feature request related to a problem? Please describe.**
If changes on remote firewalls are necessary that possibly could cause a not working configuration or a lock out situation. It would be nice to be able to have a mechanism to revert to a marked configuration automatically if no commit or approve action is taken by the user.

**Describe the solution you'd like**
It would be nice to lock the firewall in a "major change" mode where only one session is able to do changes until the major change mode is exited. This mode should be able to define a working configuration from the backup config history or the current configuration when this specific mode is activiated. It should be possible to set a timer for change commitment. Now the administrator can for exampel make significant changes to routing or rules that possible could lock him out of the firewall. If he does not approve that his change was sucessfull and workes as intended the firewall roles back to the defined configuration. This way the administrator can log in an "try" again or rethink his change. 

**Describe alternatives you've considered**
No other alternatives where discussed up to now.

**Additional context**
This feature would make administration of remote sites easier and helps to do critical changes if necessary. If the config roles back in a case of missconfiguration the firewall is available again.

**Comment by fichtner** [comment]
Hi Dominik,

This loosely relates to #3042 and I see this one here as a more useful approach than the other, but that's only personal taste. To ensure consistency a discussion should be started over there as to how much intersection is there between what people require vs. what your solution could offer.

Would you mind to do this to gather more information?


Cheers,
Franco

**Comment by banym** [comment]
I agree, i will let this one open for reference but join the discussion over there. Thank you for the hint, and sorry for the double posting.

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/core/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
