### ISSUE TITLE
Firewall rules - presentation error hover "pass / (disable) rule"

### ISSUE THREAD

**Issue by opnsenseuser** [opnsense/core#3700]
If i point with the mouse over any "pass rule" (firewall rules), a small point appears.

![grafik](https://user-images.githubusercontent.com/34602360/64470580-d780c580-d145-11e9-9597-51eb41cb1741.png)

**Comment by opnsenseuser** [comment]
i found out that the problem is:

![grafik](https://user-images.githubusercontent.com/34602360/64491570-55d68800-d26a-11e9-957f-239001339eb0.png)

**Comment by fichtner** [comment]
For me it's a normal "hand" pointer thing.

**Comment by opnsenseuser** [comment]
@fichtner Don´t you see the orange dot? Its on all templates!
regards René

![grafik](https://user-images.githubusercontent.com/34602360/65046932-cca60c00-d961-11e9-83ad-0c2a0f68e1f7.png)

**Comment by fichtner** [comment]
Okay, I made it nicer then.

**Comment by opnsenseuser** [comment]
perfect !!! thx 👍 
regards rené
