### ISSUE TITLE
Captive Portal - Error in log

### ISSUE THREAD

**Issue by tech62** [opnsense/core#3704]
I've got this error when i try to use the captive portal service

>  captiveportal: Traceback (most recent call last): File  "/usr/local/opnsense/scripts/OPNsense/CaptivePortal/cp-background-process.py",  line 217, in main bgprocess.sync_zone(zoneid) File  "/usr/local/opnsense/scripts/OPNsense/CaptivePortal/cp-background-process.py",  line 153, in sync_zone and time.time() - float(db_client['startTime'])  > db_client['acc_session_timeout']: TypeError: '>' not supported  between instances of 'float' and 'str'

Any Idea ?

OPNsense 19.7.4_1-amd64
FreeBSD 11.2-RELEASE-p14-HBSD

**Comment by fabianfrz** [comment]
try to write `float(` before and `)` after db_client['acc_session_timeout']` in the given file and line and report back if that works.

**Comment by tech62** [comment]
Sorry :/

> captiveportal: Traceback (most recent call last): File "/usr/local/opnsense/scripts/OPNsense/CaptivePortal/cp-background-process.py", line 217, in main bgprocess.sync_zone(zoneid) File "/usr/local/opnsense/scripts/OPNsense/CaptivePortal/cp-background-process.py", line 153, in sync_zone and time.time() - float(db_client['startTime']) > float(db_client['acc_session_timeout']): ValueError: could not convert string to float:

**Comment by dbquintao** [comment]
I also have the same problem. 

I delete the file /var/captiveportal/captiveportal.sqlite and then after a while the error start to show in log again.

**Comment by fabianfrz** [comment]
Then it is quite interesting which value that is since it is supposed to be numeric bug it is something that cannot even be cast.
You could print it but I am not sure if it will be visible.

**Comment by tech62** [comment]
How can i get anything to help you to resolve this issue ?

**Comment by fichtner** [comment]
Please sit tight, @AdSchellevis is on vacation and would know how to troubleshoot.

**Comment by AdSchellevis** [comment]
This might point to another issue, although it shouldn't crash on type issues, which is what https://github.com/opnsense/core/commit/ebd9ea254282812bf6397f51742ed9e88c0b3121 fixes
