### ISSUE TITLE
Create tags (friendly names) for MAC addresses in ARP table

### ISSUE THREAD

**Issue by DolpheusLabs** [opnsense/core#3705]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[-] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
Yes
[-] I have searched the existing issues and I'm convinced that mine is new.
Yes
**Is your feature request related to a problem? Please describe.**
Looking through the IP/MAC/Mfg in the Arp table when chasing down wayward hosts is sometimes hard to do without an Excel sheet or similar. Once I've traced one down, I have no way to update  the record.
**Describe the solution you'd like**
I would like to be able to edit the records in /ui/diagnostics/interface/arp    and/or in      /status_dhcp_leases.php       so that I can add a friendly tag to the record (presumably using the MAC as the key here would be one way). I wouldn't want to overwrite the Hostname or other fields provided back by the host; I'd prefer to let the host tell me what it is with the ability for me to add metadata in OPNSense.
**Describe alternatives you've considered**
I'm concerned with this that VLANs or virtualization might get wonky with this -- perhaps several hosts would show up with the same information about themselves in some edge cases. Still, I think having this would be useful. 

**Additional context**

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/core/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
