### ISSUE TITLE
firewall rules user-related

### ISSUE THREAD

**Issue by unicorn667** [opnsense/core#3709]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

Hi all,

Sophos xg/Stormshield have a nice feature called firewall user rule. User will be authenticated by the firewall/ad and after this, the user have enabled is own user firewall rule. 

At the moment you have a policy based rule set.
Client with IP => allow, deny so you must do this vor all your networks/clients.

With user rule set
user login on any client => allow,deny for user or group and no matter in which network located. 

advatage of user rule set, you must not open whole networks for ssh/http

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/core/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
