### ISSUE TITLE
Add an option to proxy to select the outgoing interface

### ISSUE THREAD

**Issue by ruffy91** [opnsense/core#3710]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[x] I have searched the existing issues and I'm convinced that mine is new.

**Is your feature request related to a problem? Please describe.**
I set up the Proxy to blacklist some URLs.
But when the clients use the proxy they can access all IPs on all interfaces as they want and completely bypass the firewall rules, because squid is running on the firewall and all connections out the firewall are allowed by default.

**Describe the solution you'd like**
I would like to be able to select a destination interface in Proxy settings where requests are allowed to exit.

**Describe alternatives you've considered**
I considered setting up ACLs in Squid to block all non-wanted access to all other Interfaces. This works mostly in a NATed IPv4 environment, because I can just block all access to RFC1918 IPs.
But as soon as I add IPv6 or non-private IPs on interfaces this breaks apart quickly as the manual maintenance needed on the ACLs quickly rises and the chance for fatal misconfiguration rises.
Also IMHO this is the wrong approach (blocking unwanted access instead of allowing wanted access).

**Additional context**
The behaviour as requested by me is how most commercial UTM products handle it.
Sophos UTM/XG does not allow any connections via proxy to local destinations by default.
There is an exception list to allow access to local destinations via proxy.

FortiGate for example has it as following: For the Forwarding Proxy you have to select a destination interface. All proxy requests exit on this interface IP and Firewall rules are applied normally to these packets.

**Comment by ruffy91** [comment]
Please allow at least to define ACL with destination networks. Like this I could create ACLs for all the local networks that deny everything.

**Comment by mimugmail** [comment]
Destination networks could be achived defining them in a file and load via remote acl's

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/core/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
