### ISSUE TITLE
DHCPv4: Additional pool with MAC address control does not filter on MAC address

### ISSUE THREAD

**Issue by Northguy** [opnsense/core#3711]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[X] I have searched the existing issues and I'm convinced that mine is new.

**Describe the bug**
Objective: I have bought myself some IoT devices (smart powerplugs) which I want to separate from my other devices, therefore I want to separate them in a separate IP Pool which is filtered on MAC address. MAC address range of the supplier is a good filter to 'group' the devices in a separate pool.

As it now seems, only 1 device ends up in the additional pool. All other devices with the same starting MAC end up in the main DHCP pool.

**To Reproduce**
1. Configure DHCP main pool and additional pool with separate IP ranges
![image](https://user-images.githubusercontent.com/1189058/65178265-ab741700-da58-11e9-81e4-cf7758d37565.png)

2. Edit main DHCP Pool and add MAC device ranges that need to be in additional pool to the **deny** list under MAC address control
![image](https://user-images.githubusercontent.com/1189058/65178373-deb6a600-da58-11e9-8a36-269d26bbd8d7.png)

3. Edit additional DHCP pooland add MAC device ranges that need to be in additional pool to the **allow** list under MAC address control
![image](https://user-images.githubusercontent.com/1189058/65178542-44a32d80-da59-11e9-88f2-b25659c5faf5.png)

4. Save and Restart DHCP; check ARP scan/leases table
![image](https://user-images.githubusercontent.com/1189058/65180082-64882080-da5c-11e9-95b1-4c480e8ce6be.png)

5. Find only 1 MAC address as 192.168.1.90. All others are in main pool in stead of additional pool

**Expected behavior**
Expected behaviour would be that all devices with a MAC address under DENY of main pool are DENIED an IP for that pool range and all the devices with MAC address under ALLOW of additional pool are given IP from that POOL

**Screenshots**
see above

**Relevant log files**
n/a

**Additional context**
Additional remark, not directly related to issue: MAC Address Control is an advanced feature which is in collapsed state by default. It stays in this state, although values are entered in the fields. It would be logical that once an "advanced" field is populated, the values are also shown by default. This logic would apply to all fields with the 'advanced' tag.

**Environment**

OPNsense 19.7.4_1-amd64
FreeBSD 11.2-RELEASE-p14-HBSD
OpenSSL 1.0.2s 28 May 2019
Platform
Manufacturer | PC Engines
Product Name | apu2
Version | 1.0
Serial Number | 
Family | Not Specified

Vendor | coreboot
Version | v4.10.0.0
Release Date | 08/08/2019

**Comment by Northguy** [comment]
Configuration from _cat /var/dhcpd/etc/dhcpd.conf_

```
option domain-name "localdomain";
option ldap-server code 95 = text;
option arch code 93 = unsigned integer 16; # RFC4578
option pac-webui code 252 = text;

default-lease-time 7200;
max-lease-time 86400;
log-facility local7;
one-lease-per-client true;
deny duplicates;
ping-check true;
update-conflict-detection false;
authoritative;
class "840d8e" {
  match if substring (hardware, 1, 3) = 84:0d:8e;
}
class "68572D" {
  match if substring (hardware, 1, 3) = 68:57:2D;
}
class "C44f33" {
  match if substring (hardware, 1, 3) = C4:4f:33;
}

subnet 192.168.1.0 netmask 255.255.255.0 {
  pool {
    deny members of "840d8e";
    deny members of "68572D";
    deny members of "C44f33";
    range 192.168.1.100 192.168.1.245;
  }

  pool {
    allow members of "840d8e";
    allow members of "68572D";
    allow members of "C44f33";
    deny unknown-clients;
    range 192.168.1.90 192.168.1.99;
  }

  option routers 192.168.1.1;
  option domain-name-servers 192.168.1.1;

}

```

Output of _/var/log/dhcpd.log_


```
Sep 23 22:05:33 OPNsense dhcpd: DHCPDISCOVER from 68:57:2d:**:**:** via igb0: network 192.168.1.0/24: no free leases
Sep 23 22:05:37 OPNsense dhcpd: DHCPDISCOVER from 68:57:2d:**:**:** via igb0: network 192.168.1.0/24: no free leases
Sep 23 22:05:39 OPNsense dhcpd: DHCPDISCOVER from c4:4f:33:**:**:** via igb0: network 192.168.1.0/24: no free leases
Sep 23 22:05:41 OPNsense dhcpd: DHCPDISCOVER from c4:4f:33:**:**:** via igb0: network 192.168.1.0/24: no free leases
Sep 23 22:05:42 OPNsense dhcpd: DHCPDISCOVER from 84:0d:8e:**:**:** via igb0: network 192.168.1.0/24: no free leases
Sep 23 22:05:44 OPNsense dhcpd: DHCPDISCOVER from 84:0d:8e:**:**:** via igb0: network 192.168.1.0/24: no free leases
Sep 23 22:05:45 OPNsense dhcpd: DHCPDISCOVER from c4:4f:33:**:**:** via igb0: network 192.168.1.0/24: no free leases
Sep 23 22:05:45 OPNsense dhcpd: DHCPDISCOVER from 68:57:2d:**:**:** via igb0: network 192.168.1.0/24: no free leases
Sep 23 22:05:53 OPNsense dhcpd: DHCPDISCOVER from c4:4f:33:**:**:** via igb0: network 192.168.1.0/24: no free leases
Sep 23 22:06:03 OPNsense dhcpd: DHCPDISCOVER from 68:57:2d:**:**:** via igb0: network 192.168.1.0/24: no free leases
Sep 23 22:06:04 OPNsense dhcpd: DHCPDISCOVER from 84:0d:8e:**:**:** via igb0: network 192.168.1.0/24: no free leases
Sep 23 22:06:06 OPNsense dhcpd: DHCPDISCOVER from 84:0d:8e:**:**:** via igb0: network 192.168.1.0/24: no free leases
Sep 23 22:06:07 OPNsense dhcpd: DHCPDISCOVER from 68:57:2d:**:**:** via igb0: network 192.168.1.0/24: no free leases
Sep 23 22:06:08 OPNsense dhcpd: DHCPDISCOVER from 84:0d:8e:**:**:** via igb0: network 192.168.1.0/24: no free leases
Sep 23 22:06:09 OPNsense dhcpd: DHCPDISCOVER from c4:4f:33:**:**:** via igb0: network 192.168.1.0/24: no free leases
Sep 23 22:06:09 OPNsense dhcpd: DHCPDISCOVER from 84:0d:8e:**:**:** via igb0: network 192.168.1.0/24: no free leases
Sep 23 22:06:10 OPNsense dhcpd: DHCPDISCOVER from 84:0d:8e:**:**:** via igb0: network 192.168.1.0/24: no free leases
Sep 23 22:06:13 OPNsense dhcpd: DHCPDISCOVER from 84:0d:8e:**:**:** via igb0: network 192.168.1.0/24: no free leases
Sep 23 22:06:15 OPNsense dhcpd: DHCPDISCOVER from 68:57:2d:**:**:** via igb0: network 192.168.1.0/24: no free leases
Sep 23 22:06:18 OPNsense dhcpd: DHCPDISCOVER from 84:0d:8e:**:**:** via igb0: network 192.168.1.0/24: no free leases
Sep 23 22:06:21 OPNsense dhcpd: DHCPDISCOVER from 84:0d:8e:**:**:** via igb0: network 192.168.1.0/24: no free leases
Sep 23 22:06:31 OPNsense dhcpd: DHCPDISCOVER from 68:57:2d:**:**:** via igb0: network 192.168.1.0/24: no free leases
Sep 23 22:06:34 OPNsense dhcpd: DHCPDISCOVER from c4:4f:33:**:**:** via igb0: network 192.168.1.0/24: no free leases
Sep 23 22:06:34 OPNsense dhcpd: DHCPDISCOVER from 84:0d:8e:**:**:** via igb0: network 192.168.1.0/24: no free leases
Sep 23 22:06:36 OPNsense dhcpd: DHCPDISCOVER from c4:4f:33:**:**:** via igb0: network 192.168.1.0/24: no free leases
Sep 23 22:06:37 OPNsense dhcpd: DHCPDISCOVER from 84:0d:8e:**:**:** via igb0: network 192.168.1.0/24: no free leases
Sep 23 22:06:40 OPNsense dhcpd: DHCPDISCOVER from c4:4f:33:**:**:** via igb0: network 192.168.1.0/24: no free leases
Sep 23 22:06:48 OPNsense dhcpd: DHCPDISCOVER from c4:4f:33:**:**:** via igb0: network 192.168.1.0/24: no free leases
Sep 23 22:06:59 OPNsense dhcpd: DHCPDISCOVER from 84:0d:8e:**:**:** via igb0: network 192.168.1.0/24: no free leases
Sep 23 22:07:01 OPNsense dhcpd: DHCPDISCOVER from 84:0d:8e:**:**:** via igb0: network 192.168.1.0/24: no free leases
Sep 23 22:07:03 OPNsense dhcpd: DHCPDISCOVER from 68:57:2d:**:**:** via igb0: network 192.168.1.0/24: no free leases
Sep 23 22:07:04 OPNsense dhcpd: DHCPDISCOVER from c4:4f:33:**:**:** via igb0: network 192.168.1.0/24: no free leases
Sep 23 22:07:04 OPNsense dhcpd: DHCPDISCOVER from 68:57:2d:**:**:** via igb0: network 192.168.1.0/24: no free leases
Sep 23 22:07:05 OPNsense dhcpd: DHCPDISCOVER from 84:0d:8e:**:**:** via igb0: network 192.168.1.0/24: no free leases
Sep 23 22:07:06 OPNsense dhcpd: DHCPDISCOVER from 68:57:2d:**:**:** via igb0: network 192.168.1.0/24: no free leases
Sep 23 22:07:08 OPNsense dhcpd: DHCPDISCOVER from 84:0d:8e:**:**:** via igb0: network 192.168.1.0/24: no free leases

```

**Comment by Northguy** [comment]
Hmm... added some additional info and unintentionally closed the issue. Issue is still valid

**Comment by AdSchellevis** [comment]
question is if it's intended to work this way, my first try would be to ditch the deny list and see if the client receives an address within the correct pool. The man page might help you out about preference in pool assignments, see https://www.freebsd.org/cgi/man.cgi?query=dhcpd.conf

**Comment by Northguy** [comment]
Hi Ad, I already checked the man page and according to the Man page, the config as described above is perfectly valid. 
```

       As you can see in the preceding example,	pools can  have	 permit	 lists
       that  control  which  clients  are allowed access to the	pool and which
       aren't.	Each entry in a	pool's permit list is introduced with the  al-
       low  or	deny  keyword.	  If a pool has	a permit list, then only those
       clients that match specific entries on the permit list will be eligible
       to  be  assigned	 addresses from	the pool.   If a pool has a deny list,
       then only those clients that do not match any entries on	the deny  list
       will  be	 eligible.     If both permit and deny lists exist for a pool,
       then only clients that match the	permit list and	do not match the  deny
       list will be allowed access.
```

**Comment by Northguy** [comment]
I stand corrected... stupid mistake found. In second pool, the "deny unknown-clients;" field was ticked, which effectively blocked the devices on the "allow" list from registering in the appropriate range.

  pool {
    allow members of "840d8e";
    allow members of "68572D";
    allow members of "C44f33";
    _deny unknown-clients;_
    range 192.168.1.90 192.168.1.99;
