### ISSUE TITLE
monitrc wrong permissions when HA sync is done

### ISSUE THREAD

**Issue by Kimotu** [opnsense/core#3713]
[X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[X] I have searched the existing issues and I'm convinced that mine is new.

**Describe the bug**
When monit configuration is sync'ed from ha master to slave, the file _/usr/local/etc/monitrc_ is created with wrong permissions (0644). When manually controlling monit, you get the message:

`The control file '/usr/local/etc/monitrc' permission 0644 is wrong, maximum 0700 allowed`

**To Reproduce**
1. activate and use monit
2. trigger a configuration sync to backup node
3. login to backup node (cli/ssh)
4. Type: _monit monitor all_
5. See error message

**Expected behavior**
No error message

**Additional context**
Solution: Simply change file mode to 0600, after syncing.

When on backup node in gui under _Services: Monit: Settings_ the save and apply button is pressed, the configuration has the right permissions. So this is just an issue when the configuration is created by HA sync.

**Environment**
Software version used and hardware type if relevant.

OPNsense 19.7.4_1-amd64
FreeBSD 11.2-RELEASE-p14-HBSD
OpenSSL 1.0.2s 28 May 2019

**Comment by fichtner** [comment]
Hi @Kimotu,

Your simple solution is in place:

https://github.com/opnsense/core/blob/188c517a262d8ebd9752dc0a12acfab73bc4786a/src/opnsense/scripts/OPNsense/Monit/setup.sh#L3

And should be executed on all remote actions:

https://github.com/opnsense/core/blob/master/src/opnsense/service/conf/actions.d/actions_monit.conf

I'm not sure what is missing / why something is not syncing 100% if it all jumps through the same hoops. Do you have any idea?


Cheers,
Franco

**Comment by Kimotu** [comment]
Sorry, @fichtner, I am not familar with the ha sync code. I just recognized that every time I sync from primary to secondary node and run 'monit monitor all', this message appears. Then I fix it manually and it works till the next sync is triggered.
Maybe a cleanup script after sync that 'fixes' permissions and applies the wrong ones on monitrc?

**Comment by fichtner** [comment]
Not sure where "monit monitor all" is dispatched (not in our code if I'm seeing this correctly) so the way to avoid that is do what the actions template do and run

    /usr/local/opnsense/scripts/OPNsense/Monit/setup.sh; monit monitor all

instead.

**Comment by Kimotu** [comment]
Oh sorry, you missunderstood me.

'monit monitor all' is not executed by OPNsense itself. I manually execute it on cli sometimes, when a monit action triggered the 'unmonitor' action because self-health (e.g. 5 restarts) did not work. Then I manually fix the issue and activate the monitoring again by executing this command.

**Comment by fichtner** [comment]
Ideally, this shouldn't happen when you go to the HA services page and restart the monit service in order to fix the sync and the permission with it.

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/core/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.

**Comment by rodgers-95** [comment]
Hello, 
I know this issue has been automatically timed-out (after 180 days of inactivity), without actually being resolved.

I am in exactly the same situation, and I don't know what to do anymore.
Could someone please help me?
Thanks in advance

Damien

**Comment by rodgers-95** [comment]
Hello,

After some investigation, I have more information: 

This error only concerns my firewall backup (HA).

If I manually run the script /usr/local/opnsense/scripts/OPNsense/Monit/setup.sh, the rights are now correct (700) on the file /usr/local/etc/monitrc on the backup

However, after a "synchronize config to backup", the permissions become bad again (644) on the backup.

The master keeps the correct rights (700) on the file /usr/local/etc/monitrc.

I have the feeling that the script usr/local/opnsense/scripts/OPNsense/Monit/setup.sh does not run when I launch a "synchronize config to backup".

Thanks in advance for your help.

Damien

**Comment by fichtner** [comment]
What version are you on?

**Comment by rodgers-95** [comment]
23.1.1_2 on both (master / backup)

**Comment by fichtner** [comment]
Perhaps because the service on the other end isn't restarted? Easy to check for PID at the other end.


Cheers,
Franco

**Comment by rodgers-95** [comment]
Hello,

Sorry for the delay in answering :/

It seems that monit is well started on the 2 servers. 
In the tabs monit > settings, the service is well started
In the tab monit > status, everything is 'OK'.

I don't know how this can come from ?

**Comment by fichtner** [comment]
you will need to check the pid of monit to see if a restart is actually issues (which runs setup.sh too)

**Comment by uhelmig** [comment]
I have the same problem with monit. It seems, that the "Restart"-Button" on the gui is not working. Tested from the master node (System: High Availability: Status) and directly from the slave node (Services: Monit: Settings). In both cases, the file permission is not set.

Workaround: Stopping and starting the service sets the file permissions correctly.

In addition, the "Restart"-Button" is working when the file permissions are set correctly (pid changes). It seems, that the restart fails (pid not changed) when the file permissions aren't set correctly after ha sync execution.

**Comment by fichtner** [comment]
Please try to confirm the PID stays the same. The way monit rc is integrated is it does a config check on restart/reload. If it considers this issue fatal (error condition) it could prevent the system from actually fixing it.

**Comment by uhelmig** [comment]
I can confirm, that the PID stays the same.

Teststeps:

1) Get PID on ha slave:
        root@router02:~ # monit
        Monit daemon with PID 57133 awakened
        root@router02:~ # ps -x | grep monit
        57133  -  I         0:00.08 /usr/local/bin/monit -c /usr/local/etc/monitrc

2) Start ha sync from ha master and restart monit via gui on ha slave

3) Get PID on ha slave:
        root@router02:~ # monit
        The control file '/usr/local/etc/monitrc' permission 0644 is wrong, maximum 0700 allowed
        root@router02:~ # ps -x | grep monit
        57133  -  I         0:00.08 /usr/local/bin/monit -c /usr/local/etc/monitrc

4) Fix permissions and restart monit via gui on ha slave again
        chmod 600 /usr/local/etc/monitrc

5) Get PID on ha slave again:
        root@router02:~ # monit
        Monit daemon with PID 30192 awakened
        root@router02:~ # ps -x | grep monit
        30192  -  S         0:00.01 /usr/local/bin/monit -c /usr/local/etc/monitrc

**Comment by fichtner** [comment]
I’ll take a closer look when I’m back at the office, thanks for providing additional context!

**Comment by hobbes444** [comment]
As a remark, I have a standalone opnsense with the same issue here, the permissions are wrong. I have never setup HA with it. It might have always been wrong, it's the first time I tried to use monit. `chmod 600 /usr/local/etc/monitrc` fixes the issue as expected.

**Comment by fbrendel** [comment]
Hi, the problem is the `monit_checkconfig` function in the monit rc.d script.
This function is executed before the _monit_setup_ command on service restart.

```
# sysrc -s monit monit_setup
monit_setup: /usr/local/opnsense/scripts/OPNsense/Monit/setup.sh

# /usr/local/etc/rc.d/monit restart
Performing sanity check on monit configuration:
The control file '/usr/local/etc/monitrc' permission 0644 is wrong, maximum 0700 allowed
```

**Comment by fbrendel** [comment]
@fichtner, @AdSchellevis
We could add the setup.sh to the configd start, stop, restart commands as with the check command.

**Comment by fichtner** [comment]
Yeah the rc script is sort of sabotaging itself here https://github.com/opnsense/ports/blob/ac45c6509dc31cb671e34e9efce72487ae12902f/sysutils/monit/files/monit.in#L24-L25

**Comment by fbrendel** [comment]
> but that's FreeBSD ports territory.

Extra patch for the monit port?
Would be the easiest. :smiley:

**Comment by fichtner** [comment]
Yep, but ideally that should be reported to bugs.freebsd.org too. A lot of these problems stem from the approach that manually fixing this once makes it work but automation is not kept in mind.

**Comment by fbrendel** [comment]
OK then...
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=275214

**Comment by fichtner** [comment]
I've fixed this here after looking more closely: https://github.com/opnsense/src/commit/a5d76bf490

Since restart rc command is split into stop start phase but restart_precmd is out of sync instead of overriding start_precmd. The monit rc file could also be modified but other ports's rc files will run into the same issue for different reasons.

**Comment by fbrendel** [comment]
But, in this case, wouldn't it be better to extend the template system to add file permissions?
I mean the system that creates the files is also responsible for their permissions.

**Comment by fichtner** [comment]
sure, but name_setup would still be inferior if not fixed and setup.sh already changes the permission. That's much easier than revamping the template system and there are also things the template system cannot do which setup.sh can like:

https://github.com/opnsense/core/blob/137e7af193e4/src/opnsense/scripts/proxy/setup.sh
