### ISSUE TITLE
firewall: tcp flags not applied if protocol is any

### ISSUE THREAD

**Issue by tobiaskohlbau** [opnsense/core#3714]
- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

- [x] I have searched the existing issues and I'm convinced that mine is new.

**Describe the bug**
The firewall offers the option to introduce tcp flags within the advanced settings. This options are shown even if TCP isn't selected as the current protocol. I presumed that it would automatically create one rule for udp without the flags and one with tcp and it's selected flags. But this isn't the case if `any` protocol is selected the rule gets applied without any tcpflags. 

**To Reproduce**
1. Go to 'Firewall'
2. Click on 'Rules'
3. Add new rule
3. Select protocol 'any'
4. Select some TCP Flags
5. Apply rule
6. Observe `pfctl -sr`

**Expected behavior**
I presumed that it would automatically create one rule for udp without the flags and one with tcp and it's selected flags. I don't know enough about PF if it's ignoring the protocol if tcp flags are set. I found that the default rule has `S/SA` activated and is applied to UDP and TCP.

**Additional context**
I could imagine three possible solutions to this problem.
1. State the observed behavior within the documentation or webinterface. Like for e.g. 
> Please notice that TCPFlags are only applied if the protocol tcp is selected.
2. Hide the TCPFlags within advanced menu if protcols UDP or any are selected.
3. Introduce two rules one for UDP without any flags and every other setting matching and one for tcp with flags set.
4. Introduce one rule which has the flags applied and protocol any. This depends on PF if it's allowed to create such rules.

The easiest solution would be the first one. But I would tend towards the second or fourth option as this makes it more convenient to use. Although I came up with the third option I would not go down this route as it's non verbose to create two rules out of one (I don't know why I presumed that this would be the implemented way). 

Edit: I totally forgot to add that I would like to work on this if one solution is selected. Good opportunity to get involved.

**Comment by AdSchellevis** [comment]
my suggestion would be to keep it simple, how about https://github.com/opnsense/core/commit/04c1decd190bdefcab9d0f2a79acd3c641b05db5 ? 

In which case it matches the parsing logic found here : https://github.com/opnsense/core/blob/eeae08415038e80285c100c5e4c425830adc40b3/src/opnsense/mvc/app/library/OPNsense/Firewall/FilterRule.php#L176-L191

**Comment by tobiaskohlbau** [comment]
Your implementation looks good to me, thanks for the fast resolving.

**Comment by AdSchellevis** [comment]
@tobiaskohlbau ok, thanks for confirming.
