### ISSUE TITLE
Add option to hide/show interfaces in Traffic graph widget

### ISSUE THREAD

**Issue by Kimotu** [opnsense/core#3716]
[X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[X] I have searched the existing issues and I'm convinced that mine is new.

**Is your feature request related to a problem? Please describe.**
When having many interfaces, no graphs are visible any more. You just see the interface legend (names and colors).

**Describe the solution you'd like**
Please add an option to show/hide interfaces, like you did it with 'interfaces' or 'interface statistics' widget.

**Describe alternatives you've considered**
* Allow several traffic graph widgets where you can select displayed interfaces.
* Make the widget span multiple columns. Currently it is just 1 col. If multi columns like 'interface statistics' widget, the legends would more expand and maybe graphs visible.

**Comment by fichtner** [comment]
#3115
