### ISSUE TITLE
Add Phase2 description to IPsec overview

### ISSUE THREAD

**Issue by mimugmail** [opnsense/core#3717]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[x] I have searched the existing issues and I'm convinced that mine is new.

I have some customers with many Phase2 SA's to a tunnel endpoint. As there are many interfaces (DMZ1-4 etc) involved, it would be quite nice to have the description of every Phase2 also in the overview.  Currently this is only  available for Phase1.

Use-case would be when talking with customer and he tells me SA from DMZ3 to SAP partner not working I first have to check IP addesses which takes some time. In this case I could clearly see which SA is affected and check it's settings.

Just an idea, maybe I can also push a PR, but not sure if everyone agrees (scaling issues?).

**Comment by AdSchellevis** [comment]
@mimugmail you mean vpn_ipsec.php?  it would probably be better to change the layout a bit as well while there, clicking "show ..." all the time isn't very convenient either.

**Comment by mimugmail** [comment]
Yes, but when you have multiple endpoints it also doesnt scale to have them e.g. auto-collapsed

**Comment by AdSchellevis** [comment]
I'm not sure why we shouldn't just always show all items and reorder the layout, the headings don't add much in phase 2 (a tooltip on the item to explain what it is would be more then enough)

**Comment by mimugmail** [comment]
If you have something in your mind which would fit nicely I'm happy to test :)

**Comment by AdSchellevis** [comment]
Not 100% sure yet, but we could merge all into a single table a fiddle a bit with the styles, something like:

![image](https://user-images.githubusercontent.com/9783985/70567844-00768380-1b97-11ea-921c-d0c2abfeff1e.png)

Although it will always be a bit crowded on the page I guess.

**Comment by mimugmail** [comment]
It looks good, but the table headers are a bit misleading then. How about a button left to Type header for "Expand / Collapse All" to defaults to collapse?

**Comment by AdSchellevis** [comment]
keep the second heading and a button left (show/hide phase2)? I think that might work indeed

**Comment by mimugmail** [comment]
I'd love to see this one 👍

**Comment by AdSchellevis** [comment]
ok, I'll try to commit something this week.

**Comment by AdSchellevis** [comment]
@mimugmail can you try https://github.com/opnsense/core/commit/f78df07af61ef598e9c3899f5ed16cc4cf8deec4 ?

**Comment by mimugmail** [comment]
Looks good! 

Before:
![image](https://user-images.githubusercontent.com/20438689/70703778-0e302400-1cd1-11ea-8e46-23a6b8e9709a.png)


After:
![image](https://user-images.githubusercontent.com/20438689/70703822-2142f400-1cd1-11ea-8d63-3d413dc0f185.png)


After (collapsed):
![image](https://user-images.githubusercontent.com/20438689/70703850-33bd2d80-1cd1-11ea-8059-7fb4cbb35e8f.png)


P.S.: Dont mind multiple mobiles .. test machine :)

**Comment by AdSchellevis** [comment]
@mimugmail thanks, I think we can close the issue in that case.

**Comment by mimugmail** [comment]
Indeed, thanks for all :)
