### ISSUE TITLE
Bootstrap-select not rendered properly in Firefox

### ISSUE THREAD

**Issue by yapsr** [opnsense/core#3719]
Select / dropdown boxes are not rendered properly.

**To Reproduce**
1. Go to "Lobby: Dashboard"
2. Look at any select box:

![image](https://user-images.githubusercontent.com/3018553/65425461-50eb0a00-de0e-11e9-8f6f-74dde21cda7d.png)

**Expected behavior**
I would expect a nicely rendered select box / dropdown. This bug does not happen in another brand browser, like Google Chrome for Linux Version 77.0.3865.90 (Official Build) (64-bit) :
![image](https://user-images.githubusercontent.com/3018553/65425701-e090b880-de0e-11e9-880c-c37c3281cc39.png)

**Environment**
OPNsense 19.7.4_1-amd64
FreeBSD 11.2-RELEASE-p14-HBSD
OpenSSL 1.0.2s 28 May 2019

Browser: Firefox 60.8.0esr (64-bit) (Firefox Quantum Extended Support Release) 

Platform: Debian 10.0 Buster

**Comment by fichtner** [comment]
Hi,

Kinda missing the info here which Firefox is affected.


Cheers,
Franco

**Comment by fichtner** [comment]
So is this still happening on the latest Firefox?

**Comment by yapsr** [comment]
Yes, I'm currently using Firefox Quantum 68.2.0esr (64-bit)

**Comment by fabianfrz** [comment]
Latest Firefox is 72 with a hot fix.

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/core/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
