### ISSUE TITLE
No more autocompletion for aliases

### ISSUE THREAD

**Issue by fraenki** [opnsense/core#372]
It seems that the recent overhaul of the firewall-related GUI parts removed autocompletion for aliases. 

Steps to reproduce:
* Firewall -> Aliases -> Ports -> Add (or Edit)
* Port(s) -> enter an existing (ports) alias

Expected result:
* while typing the first letter(s) of the alias, autocompletion should be activated and complete the alias name (or suggest possible matches)

Actual result:
* no autocompletion

I was using this feature to easily build groups of aliases. Now I need to exactly remember and type the full name. :(

**Comment by fichtner** [comment]
I did not find this, the new autocompletion works well with annotations and all. Are you still able to reproduce on opnsense-devel?

**Comment by AdSchellevis** [comment]
It looks like the old code had an auto-complete in the alias edit itself, we dropped that feature with the cleanup of the page.
Maybe a similar kind of behaviour can be achieved if we include a duplicate option on an existing alias, which should be more in line with other similar pages.

I rather don't copy the auto-complete feature back, because of the amount of work it will take to bring that feature up to quality and the I'm pretty convinced the new feature is easier to use in all the other pages.

**Comment by fichtner** [comment]
Whoopsie, and this? @AdSchellevis

**Comment by AdSchellevis** [comment]
@fichtner leave this one open for now, the easiest solution is to add the copy feature to the overview page... but this still needs to be done. Maybe rename to something like "Aliases: add copy to overview"?

**Comment by fichtner** [comment]
Is this still relevant?

**Comment by fraenki** [comment]
I make heavy use of nested aliases, thus having a choice to select existing aliases would be important to me. I'd figure something like the alias selection that can be found in the firewall rules might be appropiate here too.

**Comment by fichtner** [comment]
Ok, hopefully the implementation won't be brittle by being recursive. Normally, this is done by grouping single aliases into alias groups?

**Comment by fraenki** [comment]
Alias groups would be a perfect replacement for nested aliases, IMHO :)

**Comment by AdSchellevis** [comment]
I'm going to reintroduce the typeahead feature again with the component we're also using for the searchbox. 
The nesting should work for port and host/network aliases if I'm interpreting the code behind it correctly.

**Comment by fraenki** [comment]
Thanks @AdSchellevis, can't wait to try it out! :+1:
