### ISSUE TITLE
Captive portal - voucher expires end date

### ISSUE THREAD

**Issue by klaasth** [opnsense/core#3720]
When creating vouchers in "Services" - "Captive Portal" - "Vouchers", you can select "custom hours" in the "Expires in"-field.  It would be more convenient to enter a date or select a date from a date/time picker.

![OPNsense-voucher](https://user-images.githubusercontent.com/6384275/65411352-ee354680-ddec-11e9-98a5-26ce3e023201.PNG)

**Comment by fichtner** [comment]
https://forum.opnsense.org/index.php?topic=14297.0

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/core/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
