### ISSUE TITLE
OpenVPN configuration getting wrong IP address

### ISSUE THREAD

**Issue by noseshimself** [opnsense/core#3723]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[-] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[-] I have searched the existing issues and I'm convinced that mine is new.

**Describe the bug**
The data entered into the configuration page will result in an incorrect OpenVPN configuration assigning a broadcast address to one of the partners.
**To Reproduce**
1. Define a (UDP or TCP) OpenVPN server as "Peer to Peer ( Shared Key )" (which in itself is wrong because if you are using TCP for this there are dedicated client and server side!).
Put a valid /30 network start address into the field "IPv4 Tunnel Network", e. g. 192.168.188.148/30
2. Get shell access to the machine and take a look at the /var/etc/openvpn/server<x>.conf, you will find a correct entry
ifconfig 192.168.188.149 192.168.188.150
[although this makes me unhappy, I would like to be able to specify which addresses will be used by each system]

**Expected behavior**
Expected behavior would be using the defined addresses for the connection. But the server will get the first address of the subnet (which by historic definitions will be the Sun reserverd first broadcast address). The connection comes up but results in address errors and will be closed by the client.

Log files show something different:

Sep 24 14:02:47 OPNsense openvpn[19628]: Local Options String (VER=V4): 'V4,dev-type tun,link-mtu 1545,tun-mtu 1500,proto UDPv4,ifconfig 192.168.188.148 192.168.188.150,comp-lzo,cipher BF-CBC,auth SHA1,keysize 128,secret'
Sep 24 14:02:47 OPNsense openvpn[19628]: Expected Remote Options String (VER=V4): 'V4,dev-type tun,link-mtu 1545,tun-mtu 1500,proto UDPv4,ifconfig 192.168.188.148 192.168.188.150,comp-lzo,cipher BF-CBC,auth SHA1,keysize 128,secret'

**Screenshots**

**Relevant log files**
see abnove

**Additional context**
The entire configuration interface needs an update for connections using a common key file and no certificate based authentication.

**Environment**
OPNsense 19.7.4 (amd64, OpenSSL).
DEC600

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/core/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
