### ISSUE TITLE
Unbound DNS does not reload after adding new OpenVPN

### ISSUE THREAD

**Issue by dasty** [opnsense/core#3727]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

**Describe the bug**

**To Reproduce**
1. Go to OpenVPN and add a new VPN connection using some new address range
2. Notice that aew address range (belonging to OpenVPN) is registered to Unbound DNS server (Services => Unbound DNS => Access Lists)

**Expected behavior**
The clients connected over VPN can use DNS

**Actual behavior**
The clients can connect over VPN, but can **NOT** use DNS

**Workaround**
Restart/reload unbound DNS server configuration manually.

**Environment**
OPNsense 19.7.4_1-amd64 (but was happening on 19.1 as well)

**Misc**
[-] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
DONE

[-] I have searched the existing issues and I'm convinced that mine is new.
**YES, I searched for "dns openvpn is:open " and "unbound openvpn is:open" **

**Comment by AdSchellevis** [comment]
We might consider emitting a `newwanip` event after save, otherwise it should likely be solved with a bit of extra documentation (cluttering services is something we try to prevent, unless proper event hooks can be used). @fichtner what do you think?

**Comment by fichtner** [comment]
@AdSchellevis we end up emitting newwanip for almost everything. Reloading unbound is already as bad as it gets with cache being flushed. I noticed a similar issue with IPv6 tracking and unbound ACL for internal LAN IPv6 not being accepted because of this. There's really no full scale solution to visibility issues from "listen to all" but then also "name this and that explicitly and reload on all relevant events too".

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/core/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
