### ISSUE TITLE
All traffic blocked with route-based IPSec

### ISSUE THREAD

**Issue by bewue** [opnsense/core#3728]
**Describe the bug**
When a Phase-2 with route-based IPSec is enabled, all network traffic is blocked.
**Edit:** See https://github.com/opnsense/core/issues/3728#issuecomment-535484848
Even a ping to 127.0.0.1 from the local console (Xen management console) fails.
The scenario was tested on different OPNSense machines:
19.1.6 and 19.7.4, on HA cluster machines and a single machine, all running on Xen.
No gateway or routes where added by me to route traffic via the tunnel at this point.

This routes are additionally added if i enable IPSec:
x.x.x.x = default gw ip
y.y.y.y = IPSec remote endpoint
```
> 0.0.0.0/1          x.x.x.x                 US             xn0
> 10.50.222.1      link#6                UHS          lo0
> 10.50.222.2      link#6                UH            ipsec100
> 128.0.0.0/1       x.x.x.x                US             xn0
> y.y.y.y           x.x.x.x                UGHS        xn0
> fe80::%ipsec1000/64                 link#6  U   ipsec100
> fe80::3862:fee8:d761:3d78%ipsec1000 link#6  UHS         lo0
```
Why 0.0.0.0/1 and 128.0.0.0/1 was added?

**To Reproduce**
Add a IPSec route-based Phase-2, IPsec has to be enabled ("Enable IPsec" checkbox).

**Expected behavior**
The traffic still flows

**Relevant log files**
```
...
Sep 26 12:03:55 | ipsec_starter[34819]:
Sep 26 12:03:55 | ipsec_starter[34819]: 'con1' routed
Sep 26 12:03:55 | ipsec_starter[34819]: charon (43129) started after 40 ms
Sep 26 12:03:55 | ipsec_starter[20725]: no files found matching '/usr/local/etc/ipsec.opnsense.d/*.conf'
Sep 26 12:03:55 | ipsec_starter[20725]: Starting strongSwan 5.8.0 IPsec [starter]...
....
```

**Environment**
OPNsense 19.1.6 (amd64, OpenSSL) on Xen (XCP-ng 7.4.0)
OPNsense 19.7.4 (amd64, OpenSSL) on Xen (XCP-ng 7.6.0)

**Comment by mimugmail** [comment]
Are you sure this is not related to XCP-ng? On bare-metal there's no issue ...

**Comment by bewue** [comment]
I think i found the cause:
In Phase 1 "Install policy" enabled + a route-based Phase-2 Entry!
IMHO, a modified UI config flow or a warning alert would be really appropriate.

**Comment by mimugmail** [comment]
https://docs.opnsense.org/manual/how-tos/ipsec-s2s-route.html?highlight=route%20based#id5

maybe there is a bug somewhere when migrating existing connections? currently unsure

**Comment by bewue** [comment]
> 
> 
> https://docs.opnsense.org/manual/how-tos/ipsec-s2s-route.html?highlight=route%20based#id5
> 
> maybe there is a bug somewhere when migrating existing connections? currently unsure

I dont think so. Same problem on an fresh 19.7.4 install. I Just forgot to uncheck "Install policy"!

**Comment by fichtner** [comment]
This is clear documentation material.

**Comment by bewue** [comment]
@fichtner imagine the following situtation:

There is already an IPSec phase 1 entry with several "policy based" phase 2 entries. "Install policy" in phase-1 is checked.
After one month you add another phase 2 entry but this time "route based". As soon as you click "Apply" **all network traffic** on the OPNsense will be blocked. If you do not have direct console access you are lost.

That could and should be prevented by the UI!

**Comment by mimugmail** [comment]
It's prohibited to mix multiple of them. The problem is the old/legacy design. 
`type = route` is neither Phase1 nor Phase2, it's a setting of the connection itself, but it's relation is to Phase2 values. There is no correct space to place this option.

**Comment by bewue** [comment]
You could gray out the "Route-based" option entry if "Install policy" is activated in Phase-1. If there is a "Route-based" Phase-2, "install policy" should be grayed out.

A info text should also be added in Phase-2 to "Mode" option, to clarify that "Install policy" has to be disabled to use the "Route-based" mode.

**Comment by mimugmail** [comment]
I think @AdSchellevis knows best how to solve best.

**Comment by SuperMarioSF** [comment]
Hello there. I'm facing the same problem as described in this issue, the difference is I am using a physical machine, and everything is just after an fresh install (even without any plugin installed). There is no existing network interference here, everything is new. I found this problem during a test for a new device for a new network.

I'm using OpnSense 19.7.4 (amd64, OpenSSL) on an Intel Core i7-2700K based physical machine with on board Realtek NIC and 2 dual port Intel NIC (5 interfaces total).

Even I specified all quick pass rules, the traffic is still blocked, both inbound and outbound.

**Comment by AdSchellevis** [comment]
@mimugmail I kind of agree with @fichtner on this point.... it's about documentation, I can think of multiple settings which could prevent access to your machine, which doesn't mean we need to validate all setup faults people can think of. If someone wants to contribute a PR with a workable solution, which doesn't bite other setups... I'll gladly take a look.

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/core/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
