### ISSUE TITLE
Unable to remove entry from a list of aliases

### ISSUE THREAD

**Issue by fraenki** [opnsense/core#373]
After the recent overhaul of the firewall-related GUI parts, it is no longer possible to remove an alias from a list of multiple aliases. There is a +-button to add one more ip/port/host to the alias list, but no button to remove an alias.

It is possible to empty the values of an alias...

![o01](https://cloud.githubusercontent.com/assets/909706/9787175/a697dcd6-57c0-11e5-93fb-4d8dea1cc08e.png)

...but it's not being removed from the alias list...

![o02](https://cloud.githubusercontent.com/assets/909706/9787183/b29cea30-57c0-11e5-98df-971229172792.png)

...as you can tell from the comma at the end of the list.

**Comment by AdSchellevis** [comment]
@fraenki I forgot this one, should be fixed with https://github.com/opnsense/core/commit/5a06c8b129a24a3150dd9e78f7eb60be84fb7c38
