### ISSUE TITLE
form POST fails in FF when accessing GUI with IPv6 literals and 1st party isolation enabled

### ISSUE THREAD

**Issue by jospanier** [opnsense/core#3731]
**Bug Description**
GUI does not handle POST correctly while accessed via IPv6 literal, e.g. https://[2001:db8:1111:2222::1] when Firefox first party isolation is enabled (privacy.firstparty.isolate = true). Same works corrctly with IPv4.

**To Reproduce**
1. assign IPv6 to LAN interface
2. enable first party isolation in FF (privacy.firstparty.isolate = true)
3. login with GUI (e.g. https://[2001:db8:1111:2222::1]/ )
4. browse to any form that would POST data
5. click "Save"

**Expected behavior**
same page is loaded with new parameters, instead a new login is requested

**Additional context**
POST results in 302, but followed by GET with new PHPSESSID

**Environment**
OPNsense 19.7.4_1-amd64
Intel Core i7 9xx (Nehalem Class Core i7) (8 cores)
Firefox 69.0.1 (privacy.firstparty.isolate = true)

**Comment by AdSchellevis** [comment]
sounds more like a browser issue or an internal php issue, you could check the system log if it logged out your session and check if new pages (beginning with /ui/) are treated equally, but as far as I know both paths for ipv4 and ipv6 are equal.

**Comment by jospanier** [comment]
checking logs: not logged out
new pages: load normally, because browser sends previous session cookie
agreed that this issue has to do with something between firefox+IPv6+FPI and phalcon.

**Comment by jospanier** [comment]
Opened https://github.com/phalcon/cphalcon/issues/14428
Can you maybe jump in and provide some of the requested additional details about the POST handling code?

**Comment by AdSchellevis** [comment]
if you have questions about some details of our implementation, you can always ask them here, no problem.

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/core/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
