### ISSUE TITLE
Alert if resolving hostname Alias fails

### ISSUE THREAD

**Issue by fukawi2** [opnsense/core#3737]
- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

- [x] I have searched the existing issues and I'm convinced that mine is new.

**Is your feature request related to a problem? Please describe.**
When OPNsense reloads firewall Aliases, if any hostnames are unable to be resolved, they are silently ignored, and nothing added to the corresponding pfTable. This can happen for example due to an invalid hostname (typo, removed RR etc), or DNS problems.

**To Reproduce**
1. Create a firewall alias with the content `google.com` (valid hostname) and `foobar.google.com` (invalid hostname - returns NXDOMAIN).
2. Save & Apply Aliases.
3. Go to Firewall -> Diagnostics -> pfTables and select your Alias from step 1.
4. The pfTable for the Alias will only contain IP Address(es) for `google.com`, and nothing for `foobar.google.com`

**Describe the solution you'd like**
A warning that resolving the hostname failed - perhaps in the "Notices" area at the top-right of the page?

**Describe alternatives you've considered**
We have spent a lot of time debugging what we thought were firewall issues, that were actually caused by DNS issues. Had we received some kind of alert as described above, we would have saved a lot of time from looking in the wrong places. Presently we have to manually perform random spot-checks on the pfTables to ensure they are accurate.

**Comment by AdSchellevis** [comment]
we can push messages to syslog, in which case they land in the system log.

https://github.com/opnsense/core/blob/3ef14d17e3b4f4ed38cbe8a9a3861ca5914ee59e/src/opnsense/scripts/filter/lib/alias.py#L122-L123

The notices are legacy software, which we are not going to extend any further.
