### ISSUE TITLE
Certificate export in .p12 doesn't verify passphrase

### ISSUE THREAD

**Issue by TotalGriffLock** [opnsense/core#3739]
When you have a certificate and matching private key in the firewall's "Trust" section and you want to download it as a .p12 file, it asks you to enter a passphrase to secure the .p12. It asks for it twice, to confirm:

![image](https://user-images.githubusercontent.com/29902212/65980134-76ab8b00-e46e-11e9-895b-6ff025c99dfd.png)

However it completely ignores the confirm field and encrypts the .p12 with whatever is typed in the first password box.

Steps to recreate:
Create Certificate
Download as .p12 bundle
Enter correct passphrase in Password field
Enter anything at all in Confirm field (you can even leave it blank!)
.p12 file downloads and can be decrypted using passphrase from Password field

Reproduced on OPNsense 19.7.4_1-amd64

**Comment by AdSchellevis** [comment]
it only shows its different using an orange border, better to prevent download indeed. https://github.com/opnsense/core/commit/371447e6f132af885b5b01f47ab0bffe7bdbb16d disables the button when not equal. Thanks for reporting.
