### ISSUE TITLE
Aliases no longer recognized in new firewall rules

### ISSUE THREAD

**Issue by fraenki** [opnsense/core#374]
After the recent overhaul of the firewall-related GUI parts, aliases are no longer recognized in _new_ firewall rules.

If I create a new firewall rule and choose an existing alias as _destination_, it will be shown as if I've chosen a network instead:

![a01](https://cloud.githubusercontent.com/assets/909706/9787404/efac49d2-57c2-11e5-9faf-7464d95e8b4d.png)

On already existing firewall rules aliases will have an icon to the right:

![a02](https://cloud.githubusercontent.com/assets/909706/9787430/16a8cdc6-57c3-11e5-96e4-c948d3aaef5a.png)

It's not only a display bug, but instead invalid configuration will be added to `config.xml`:

```
<!-- old firewall rule with working alias -->
      <destination>
        <address>nameserver</address>
        <port>53</port>
      </destination>
<!-- new firewall rule with broken alias -->
      <destination>
        <address>backup_server/128</address>
        <port>22</port>
      </destination>
```

**Comment by fraenki** [comment]
@fichtner Maybe you can have a quick look at this and tell me, if this is actually broken or if it's just me (again). I'll stop reporting more issues until I hear from you.

**Comment by fichtner** [comment]
Looks like a bug, will investigate. Keep them coming. :)

**Comment by fichtner** [comment]
Are you using the master branch mounted into the system or did you apply patches manually? Which version is this, exactly?

**Comment by fraenki** [comment]
@fichtner I've applied some patches manually to fix another problem (#368, www/vpn\*, www/firewall*, etc/inc/vpn.inc, etc/inc/vpn.inc, opnsense/mvc, opnsense/www/themes/opnsense).

**Comment by fichtner** [comment]
Can you try with the latest opnsense-devel? It has all the fixes in place, short of a small CSRF issue fixed via: https://github.com/opnsense/core/commit/ab1ad19c1fc6ec92cc74b0eab3912ad9a6cbc25a

**Comment by AdSchellevis** [comment]
@fraenki @fichtner the last version of guiconfig.inc is probably not used in this test, this commit https://github.com/opnsense/core/commit/354d35b313b27d8a1bf88da2afebccbb691f8f18 fixes aliases / netmask issues.

**Comment by fichtner** [comment]
@AdSchellevis is this safe to put on stable as well? I have avoided it for now, but if it's good I would like to merge it?

**Comment by AdSchellevis** [comment]
@fichtner it should work without issues, a lot of old pages perform almost the same check with makes this one for the old pages a bit overlapping, but that shouldn't hurt :)

**Comment by fichtner** [comment]
great, merged :)

**Comment by AdSchellevis** [comment]
thanks!
