### ISSUE TITLE
LDAPS handling in PHP is broken

### ISSUE THREAD

**Issue by jpawlowski** [opnsense/core#3741]
Due to a PHP bug mentioned [here](https://bugs.php.net/bug.php?id=73558), the `LDAP_OPT_X_TLS_*` parameters in [Auth/LDAP.php](https://github.com/opnsense/core/blob/master/src/opnsense/mvc/app/library/OPNsense/Auth/LDAP.php) will be ignored. Therefore, the certificate chain cannot be validaded when using a TLS connection for LDAP.

However, there is an easy workaround to make this work (also see forum topic [here](https://forum.opnsense.org/index.php?topic=14381.0)).

The parameters may simply put into `/root/.ldaprc` in a slightly different way, basically dropping the `LDAP_OPT_` prefix:

```conf
TLS_REQUIRE_CERT TLS_HARD
TLS_CACERTDIR /var/run/certs
```

I wasn't able to validate whether `TLS_HARD` should also drop the prefix or not.
Also, `TLS_CACERTFILE` needs to be dropped entirely because otherwise it is not possible to configure multiple connections using different CAs.

This might also fix other issues that were discussed here as well, e.g. #3206 .

**Comment by jpawlowski** [comment]
I have to add, that after adding this server to the list of authentication options in `System > Administration > Authentication`, the authentication no longer works. Not sure why because there literally was no other change in between.

**Comment by AdSchellevis** [comment]
@jpawlowski is this the same issue as https://github.com/opnsense/core/issues/3445 ?

**Comment by jpawlowski** [comment]
I think it is not because the other issue states that testing the credentials is not an issue. The issue here starts at the very beginning when adding the server to the list and testing it. This might very well be the actual root cause for #3445 as it is the foundation to import users.

This connection is not using StartTLS but immediate TLS in port 636. From a certificate chain validation point of view, this should be the same though.

**Comment by jpawlowski** [comment]
Okay, reading further in [PHP ticket 73558](https://bugs.php.net/bug.php?id=73558), the last post about adding an environment variable named `LDAPTLS_CACERTDIR` seems to do the trick (again).

To make this available to the PHP process, I deleted `/root/.ldaprc`, then changed `:setenv=MAIL=/var/mail/$,BLOCKSIZE=K:\` in `/etc/login.conf` to `:setenv=MAIL=/var/mail/$,BLOCKSIZE=K,LDAPTLS_CACERTDIR=/var/run/certs:\`. After rebuilding the db using `cap_mkdb /etc/login.conf`, I would then reboot the device.

Voilà, works again - without `.ldaprc`.

**Comment by jpawlowski** [comment]
Forget everything I wrote earlier.

It turns out that the trust store got somewhat confused about creating a chain of root and sub CA in a single entry. This workaround is needed as the `LDAP.php` script currently does not resolve the full tree but would simply take only the single entry that you set in the LDAP server configuration.

I will open a separate feature request for this.
