### ISSUE TITLE
IPv6: When I set the prefix delegation size to /62 dhcpd6 (DHCPv6 Server) stops and can not restart

### ISSUE THREAD

**Issue by agl7** [opnsense/core#3743]
Hello,
my english language is not good, I hope you understand what I write here:

Version:
OPNsense 19.7.4_1-amd64
FreeBSD 11.2-RELEASE-p14-HBSD
OpenSSL 1.0.2s 28 May 2019

Hardware: PC-Engines, CPU-Typ: AMD GX-412TC SOC (4 cores),
with 4 interfaces: WAN (connected to the router), LAN, DMZ and WLAN

IPv6 in my router (FRITZ!Box):
Internet, IPv6: connected since 02.10.2019, 14:45 Uhr,
IPv6-Adresse: 2a02:810d::35:2011:9a58:4464:2e3b, Gültigkeit: 5048/2348s,
IPv6-Prefix: 2a02:810d:1a80:700::/62, Gültigkeit: 5048/2348s

WAN configuration in OPNsence (is connected to the first LAN-Interface of my router):
IPv6 configuration typ: DHCPv6
DHCPv6 Clientkonfiguration:
modus: simple
Request only an IPv6 prefix: yes
Prefixdelegationsize: /63 bit <--------------- !!!
Send an IPv6-Präfixnote: yes
IPv6-Prefix: 2a02:810d:1a80:700:: (used by the Router)

WLAN-Interface:
IPv6-configuration-typ: Track Interface
IPv6-Track-interface: IPv6-interface: WAN, IPv6 Prefix ID: 0x0
--> Then the IPv6-Prefix is: 2a02:810d:1a80:702::

LAN-Interface:
IPv6-configuration-typ: Track interface
IPv6-Track-Interface: IPv6-interface: WAN, IPv6 Prefix ID: 0x1
--> Then the IPv6-Prefix is: 2a02:810d:1a80:703::

DMZ-Interface:
No IPv6-Konfiguration because there is no another free IPv6 Prefix ID.

When I set the Prefixdelegationsize to 63 the dhcpd6 runs normal and all works well. I have IPv6 only on the Interfaces WLAN and LAN. the DMZ have only IPv4.

But when I set the Prefixdelegationsize to 62 (what I need to have also IPv6 on DMZ) the dhcpd6 stops and can not restart.
Following IPv6-Configuration set I for Prefixdelegationsize 62:

WAN configuration in OPNsence (is connected to the first LAN-Interface of my router):
IPv6 configuration typ: DHCPv6
DHCPv6 Clientkonfiguration:
modus: simple
Request only an IPv6 prefix: yes
Prefixdelegationsize: /62 bit <------------------ !!!
Send an IPv6-Präfixnote: yes
IPv6-Prefix: 2a02:810d:1a80:700:: (used by the Router)

WLAN-Interface:
IPv6-configuration-typ: Track Interface
IPv6-Track-interface: IPv6-interface: WAN, IPv6 Prefix ID: 0x2
--> Then the IPv6-Prefix must be: 2a02:810d:1a80:702::

LAN-Interface:
IPv6-configuration-typ: Track interface
IPv6-Track-Interface: IPv6-interface: WAN, IPv6 Prefix ID: 0x3
--> Then the IPv6-Prefix must be: 2a02:810d:1a80:703::

DMZ-Interface:
IPv6-configuration-typ: Track interface
IPv6-Track-Interface: IPv6-interface: WAN, IPv6 Prefix ID: 0x1
--> Then the IPv6-Prefix must be: 2a02:810d:1a80:701::

When I do setup this configuration the DHCPv6-Server stops and can not restart.
The IPv6-configuration of the clients can not initialisized!

Best Regards
Andreas Gerlich

**Comment by agl7** [comment]
I have updated the issue template.

**Comment by marjohn56** [comment]
I can confirm the following on test. Primary router set to issue /62 prefixes, secondary router set to request /62 prefixes. DHCP6 server is running on secondary. Setting the secondary dhcp6 server to manual I can see I have a /63 available prefix delegation size.

**Comment by agl7** [comment]
At 07.10.19 at 11:23 wrote Martin Wasley:
> I can confirm the following on test. Primary router set to issue /62
> prefixes, secondary router set to request /62 prefixes. DHCP6 server is
> running on secondary. Setting the secondary dhcp6 server to manual I can
> see I have a /63 available prefix delegation size.
> 

I have a little bit difficulties to understand. Is that a bug? In the
menu of opnsense I can set up /62 prefix delegation size, so I mean that
should be right to set, or?

Best Regards
Andreas Gerlich

-- 
Dipl.-Ing.(FH) Andreas Gerlich
Dominikus-Zimmermann-Str. 6
D-86956 Schongau
Germany

Tel.: +49(0)8861/6 90 95 11 (phone with voice box)
      +49(0) 163/4 36 32 32 (mobile phone)

Email: Andreas.Gerlich@in-ulm.de
Nick im IRCNet: agl

GPG-Key: 5D8EA14A
Fingerprint: 4450 3C20 E8B4 E492 D822 BEB4 3B97 10F8 5D8E A14A

University of Ulm, Germany
open source project "Yet Another Z80 Emulator by AG":
--> http://yaze-ag.de/

**Comment by marjohn56** [comment]
I'm checking the dhcp6c responses, which has indirectly led me to an unrelated bug which I need to look at. At present my test system all checks out correctly. I have my WAN set up to request a /62. I then  have three interfaces, LAN2, LAN2, LAN3. I am using Track WAN interface for each and I increment the IPv6 Prefix ID by 1 on each interface, so they are 1,2,3. I have then moved my LAN cable from my PC to each port and the correct IPv6 prefix is given by dhcpd6 on each port. I have checked both the radvd.conf when manual overide is not used and the dhcp6d.conf when it is and both are correct. 

I was going to ask you to set the debug option in dhcp6c so we can see what prefix length is being obtained by dhcp6c, but there is a bug in the 'debug' output and it's not showing the prefix info. There is a way around that but you would manually need to run dhcp6c from the shell with  full debug mode '-D' and foreground mode '-f' to see the full debug output.

Do you know what prefix size your ISP is giving you? Sounds to me like they are only giving you a /62, so then that will only be a /63 on the Opnsense router.

**Comment by agl7** [comment]
Hello Martin Wasley,

Am 12.10.19 um 13:28 wrote Martin Wasley:
> I'm checking the dhcp6c responses, which has indirectly led me to an
> unrelated bug which I need to look at. At present my test system all
> checks out correctly. I have my WAN set up to request a /62. I then have
> three interfaces, LAN2, LAN2, LAN3. I am using Track WAN interface for
> each and I increment the IPv6 Prefix ID by 1 on each interface, so they
> are 1,2,3. I have then moved my LAN cable from my PC to each port and
> the correct IPv6 prefix is given by dhcpd6 on each port. I have checked
> both the radvd.conf when manual overide is not used and the dhcp6d.conf
> when it is and both are correct.

What have you there for the IPv6-Praefix-Length from your ISP?

> 
> I was going to ask you to set the debug option in dhcp6c so we can see
> what prefix length is being obtained by dhcp6c, but there is a bug in
> the 'debug' output and it's not showing the prefix info. There is a way
> around that but you would manually need to run dhcp6c from the shell
> with full debug mode '-D' and foreground mode '-f' to see the full debug
> output.
> 
> Do you know what prefix size your ISP is giving you? Sounds to me like
> they are only giving you a /62, so then that will only be a /63 on the
> Opnsense router.

My Cable-Fritz!Box (Internet-Router) have a fix installed
IPv6-Praefix-Length of /62 in the firmware. In the forum of
"Kabel-Deutschland" (my ISP) there are a lot of people which have the
same problem like I. The IPv6-Praefix-Length can not changed it's fix on
/62.
I have to change the Internet-Provider to get an another
IPv6-Praefix-Length.

Best Regards
Andreas Gerlich
-- 
Dipl.-Ing.(FH) Andreas Gerlich
Dominikus-Zimmermann-Str. 6
D-86956 Schongau
Germany

Tel.: +49(0)8861/6 90 95 11 (phone with voice box)
      +49(0) 163/4 36 32 32 (mobile phone)

Email: Andreas.Gerlich@in-ulm.de
Nick im IRCNet: agl

GPG-Key: 5D8EA14A
Fingerprint: 4450 3C20 E8B4 E492 D822 BEB4 3B97 10F8 5D8E A14A

University of Ulm, Germany
open source project "Yet Another Z80 Emulator by AG":
--> http://yaze-ag.de/

**Comment by marjohn56** [comment]
My ISP does things properly, I get a /48 Prefix.

I would suggest you find a sensible ISP, there is absolutely no reason to limit users to a /62, it's stupid.
