### ISSUE TITLE
Default Gateway being de-configured during prolonged outages in dual-WAN failover scenario

### ISSUE THREAD

**Issue by drivera73** [opnsense/core#3747]
**Describe the bug**
Firewall failover works, but on prolonged outages apparently the gateway maintenance logic gets confused after some time and shoots the default gateway configuration in the head. It can be restored by simply "blank-editing" (edit, save without changes) any of the single gateway configurations and hitting the "Apply" button, but obviously this is less than ideal.

**To Reproduce**

1. Configure a dual-WAN setup with monitor IPs for each gateway inside the "far" network for each gateway, different from the actual gateway IPs for each network, herein referred to as MonIP-A for network A, and MonIP-B for network B.
2. Configure GW-A and GW-B to be upstream, with priorities 1 and 2 respectively
Ensure both MonIP-A and MonIP-B are both fully accessible to ping from the firewall (for monitoring)
3. Validate that GW-A is selected as the default route
4. Save and apply the GW settings
5. Disable ping traffic to MonIP-A, observe failover happen
6. Leave the system on failover for a "good amount of time" (an hour-ish for me).

**Expected behavior**
The system's default gateway should continue to be set GW-B.

**Expected behavior**
After some time (at most an hour), the system's default gateway configuration is cleared which messes up the routing.

**Relevant log files**
[Relevant Log File](https://github.com/opnsense/core/files/3689372/failover.log)

**Additional context**
An outage on my primary Cable link was the trigger (as shown in the logs). I was out of my house a the time, and when I came back ~1 hour after the outage, internet access was broken. I fixed by the above procedure of "gateway edit-save without changes-apply".

Even though the default gateway was unconfigured, routing to special routes (i.e. routes defined for the Gateways) was working fine. However, because there was no default gateway configured, no other traffic was being routed.

Also, by a cursory analysis of the logs it would appear that for some reason the configuration script is considering non-upstream gateways as eligible for default gateway configuration. At some point it tries to set **_opt7_** as the gateway device, but no such **physical** device exists (igb0-1-2-3 only, everything else is a virtual/VPN interface). The **_opt7_** device is a VPN device which shouldn't be considered as an upstream device since it's explicitly NOT configured as one. Only igb3 (BKUP, opt2) and igb2 (MAIN, opt1) are eligible to be used as upstream devices as per the gateway configurations.

**Environment**
OPNsense 19.7.4_1-amd64
FreeBSD 11.2-RELEASE-p14-HBSD
OpenSSL 1.0.2s 28 May 2019
Protectli FW4B with 8GB RAM and 256GB SSD

**Comment by drivera73** [comment]
I have collected a [possibly better log](https://github.com/opnsense/core/files/3906191/outage.zip), and may have a lead. I think the issue has to do with DHCP.

In my setup, the primary circuit is configured via DHCP from the ISP. To avoid the circuit being considered "UP" when it really isn't, I've configured the firewall to ignore DHCP served up by the modem itself since this would mean that the link could be "seen as UP", but in reality isn't because connectivity to the internet has not yet been fully restored (i.e. don't have my public IP yet).

**SIDENOTE:** I should probably reverse this since now I'm evaluating circuit health based on the reachability of well-known public IPs on the internet, so this may be moot at this point. Now back to the show :)

So I've noticed that the default gateway configuration seems to be clobbered after attempts to retrieve a DHCP configuration from the previous DHCP host (192.168.11.31 in the logs, I believe) fail. This seems to trigger default gateway configuration, which ends up somehow clobbering a known-good configuration (i.e. the backup circuit).

This makes sense because the configuration will get clobbered periodically and I'll have to log on and do these "manual" repairs every so often - every 20 minutes or so.

Here's an index of the log, for ease of navigation:

- 11:15:17 -> outage on MAIN detected, reconfriguration for failover to BKUP circuit begins and succeeds
- 11:42:44 -> default gateway configuration is clobbered and left blank despite the secondary circuit being up and available
- 11:48:16 -> "outage" (misconfiguration) fixed by employing the "save+no changes+apply" method (edit any non-VPN gateway, make no changes, save, hit apply...default GW will be reconfigured properly this time)
- 12:07:08 -> default gateway configuration is clobbered AGAIN and left blank despite the secondary circuit being up and available
- 12:09:58 -> "outage" (misconfiguration) fixed AGAIN by employing the "save+no changes+apply" method

Sure enough: as I was writing this post, the config got clobbered again about 20 minutes after I fixed it last. I'll try modifying the DHCP configuration to not refuse DHCP from the modem, and see if that helps.

Cheers!

**Comment by drivera73** [comment]
More news: changed the DHCP setting, and now it won't crash as before. However, it won't fail back either... apparently the specialized route to the main gateway's monitor IP isn't being re-added...

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/core/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
