### ISSUE TITLE
OpenVPN: User specific client export view

### ISSUE THREAD

**Issue by jpawlowski** [opnsense/core#3748]
The current OpenVPN client export view was made for admins only it seems.
Assigning this single view for access by a regular user will give more options than intended, which will not allow any kind of end-user self-service.

It would be great if there was a lightweight view for the end-user were s/he may only download a configuration file especially prepared for personal use, no access to other users certificates. Also, generating a certificate on the fly would be neat.

It might not be pretty straight forward though as the admin would need to be able to set some presets, e.g. a canonical hostname (basically everything that the current client export view will offer, just as a preset (maybe even hidden).

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/core/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
