### ISSUE TITLE
openvpn: export page improvements

### ISSUE THREAD

**Issue by fichtner** [opnsense/core#375]
* Tell the current page viewer that no users have been configured, an empty table always leads to questions.
* If users have been configured for OpenVPN rights, list them, but deactivate them when no certificate has been assigned.
* If the user is not an admin, only ever list his own client export data.

via: https://forum.opnsense.org/index.php?topic=1347.0

**Comment by andreasvel** [comment]
also should be hidden all other client profiles- just the profile for the user should be shown

**Comment by fichtner** [comment]
(thanks, updated)

**Comment by AdSchellevis** [comment]
I think the recent changes fixes most of the issues (https://github.com/opnsense/core/commit/cb7aaea59699a1a6dcb9d29771a2eae215996c2d https://github.com/opnsense/core/commit/3284b185014dc48c8845f80fbe98c7b1180601b9)... feel free to open a new issue when needed.
