### ISSUE TITLE
SSH-VPN

### ISSUE THREAD

**Issue by rlfnb** [opnsense/core#3750]
Im every time forced to setup vpn connections to make my daily wotk more comfortable. Unfortunately, more or less each VPN implementation needs an extra installed package/software. 

But, more or less each and every machine has a working OpenSSH installation and OpenSSH supports since ages the createion of layer3 (and even layer2) VPNs. 
Yes I know the "drawbacks" of TCP, but to be honest, its not an issue for me at all compared to install additional software on VPN legs. 
ssh -w <lid>:<rid> targetHost creates two tun devices, tun<lid> on the calling machine and tun<rid> on the called machine. Giving them two IPs and adding a route and basic VPN is ready to rumble. A small sophisticated shell script might restart the connection in case of failure (TCP).
 
Find further information here: 
 - https://man.openbsd.org/ssh
 - https://help.ubuntu.com/community/SSH_VPN

**Comment by mimugmail** [comment]
Is it possible to give the tun device a name like ssh1 or srv0 in the same commandline?

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/core/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
