### ISSUE TITLE
IPSec Clients Restricted to LAN

### ISSUE THREAD

**Issue by johnstonjs** [opnsense/core#3751]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[+] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[+] I have searched the existing issues and I'm convinced that mine is new.

**Describe the bug**
There's one function provided that I have been unable to get working as intended - IPSec Road-Warrior with Tunneled Internet Access.

I want mobile devices, including laptops, tablets, and phones, to be able to connect using IPSec VPN and have access to both the internal network [LAN] and route all internet traffic through the VPN [WAN].  So far I can get very effective access to the internal network [LAN], but depending on settings will either get non-tunneled access to the internet, or no access to the internet.

This seems to be a recurring issue, as resource [2] outlines the exact problem I'm currently having.  Unfortunately, I've attempted to implement all of the steps shown, including creation of a manual NAT rule for IPSec routing to no avail.

Following the Road-Warrior guide in resource [1], I'm able to connect to the internal network but the connection to any internet site is not routed through the VPN.  Previous form postings [3] and [4] show similar issues, while [2] and [5] provide guidance on how to resolve.  Unfortunately, none of this is working for me.

My ipsec.conf file is configured with (obscuring actual hostname):

```
# This file is automatically generated. Do not edit
config setup
  uniqueids = yes

conn con1
  aggressive = no
  fragmentation = yes
  keyexchange = ikev2
  mobike = yes
  reauth = yes
  rekey = yes
  forceencaps = no
  installpolicy = yes
  type = tunnel
 
  left = %any
  right = %any
 
  leftid = my.personal.domain
  ikelifetime = 1440s
  lifetime = 1440s
  rightsourceip = 192.168.2.0/24
  ike = aes256-sha256-modp2048!
  leftauth = pubkey
  rightauth = eap-radius
  rightsendcert = never
  eap_identity = %any
  leftcert = /usr/local/etc/ipsec.d/certs/cert-1.crt
  leftsendcert = always
  leftsubnet = 0.0.0.0/0
  esp = aes256-sha256-modp2048!
  auto = add

include ipsec.opnsense.d/*.conf
```

Finding local domains seems to work fine.  Using Unbound DNS I have an override for the OPNSense domain name (my.personal.domain in ipsec.conf) which redirects to the local IP.  This lets me use LetsEncrypt on the OPNSense web interface.  Pointing a VPN-connected client to my.personal.domain brings up the OPNSense web interface, which is only accessible on LAN.  Unfortunately, attempting to access any other domain results in a timeout.

I've tried following the guidance in [2] and [5] below, but without success.  If anyone can help, please let me know.  I'm happy to provide additional configuration details as needed.

Online resources used:
1: https://docs.opnsense.org/manual/how-tos/ipsec-road.html
2: https://forum.opnsense.org/index.php?topic=11340.0
3: https://forum.opnsense.org/index.php?topic=6842.0
4: https://forum.opnsense.org/index.php?topic=7341.0
5: https://forum.opnsense.org/index.php?topic=9478.0

**To Reproduce**

I can provide relevant sections of OPNSense config upon request

**Expected behavior**
The expected behavior is for IPSec clients to have an internal IP and be able to access both the internal network and route traffic to/from the internet.

**Relevant log files**
If applicable, information from log files supporting your claim.

**Additional context**
Using both iOS and MacOS built-in IPSec clients.

**Environment**
Software version used and hardware type if relevant.

OPNsense 19.7.4_1-amd64
FreeBSD 11.2-RELEASE-p14-HBSD
OpenSSL 1.0.2s 28 May 2019

Intel(R) Core(TM) i5-4430 CPU @ 3.00GHz (4 cores), 8 GB RAM

**Comment by tamersaadeh** [comment]
I think this might be related a NAT issue, for me it was as simple as adding an outbound NAT rule as follows:

| Setting | Value |
|-|-|
| Interface | WAN |
| Source | 10.0.0.0/24 (IPsec virtual IP subnet) |
| Source Port | * |
| Destination | * |
| Destination Port | * |
| NAT Address | WAN address |
| NAT Port | * |
| Static Port | NO |

Hope that it helps.

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/core/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
