### ISSUE TITLE
IPSec with dpd, but none configured

### ISSUE THREAD

**Issue by ahaase-c4u** [opnsense/core#3752]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[x] I have searched the existing issues and I'm convinced that mine is new.

**Describe the bug**
We have made an update to opnsense 19.7.4 last week. Since then we are experiencing weird behaviour regarding dead peer detection. We are operating several IPSec about 20 vpns to different customers. 3 of them use dpd, which is reflected in /conf/config.xml correctly. When taking a look into generated /usr/local/etc/ipsec.conf, we see 15 occurances of dpd configuration, which is of course executed as stated there.

All connections before the first having dpd do not have the configuration for dead peer detection, all following connect do have the confs, regardless of the frontend configuration. 

**To Reproduce**
1. Configure an ipsec connection not having dpd enabled.
2. Configure a second ipsec connection having dpd.
3. Configure a third one without dpd enabled.

**Expected behavior**
Only second connection should have dpd enabled. But second and all following connections have.

**Environment**
Software version used and hardware type if relevant.
e.g.:

OPNsense 19.7.4 (amd64, OpenSSL).
Intel® Xeon™ E3-1230V2 3.3Ghz

**Comment by fichtner** [comment]
Thanks for the report! Please try the patch below:

    # opnsense-patch 046d821

**Comment by ahaase-c4u** [comment]
Great, ipsec.conf now looks as expected. Thank you very much.

**Comment by fichtner** [comment]
Thanks for confirming :) We'll add this patch to 19.7.5 then.

Cheers,
Franco
