### ISSUE TITLE
Description Field Changed / Automatically Populated with "System Administrator"

### ISSUE THREAD

**Issue by ChuckWhitson** [opnsense/core#3756]
[X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[X] I have searched the existing issues and I'm convinced that mine is new.

**Describe the bug**

- The current OPNsense version where the bug first appeared: 19.7.4_1

- The last OPNsense version where the bug did not exist: 19.7.4

- The exact URL of the GUI page involved (if any):
/services_dhcp_edit.php?if=opt2
/services_unbound_host_edit.php
/services_dyndns_edit.php

- A list of steps to replicate the bug
Create a new or edit an existing element.

When modifying DHCP static mappings, the description field is changed / automatically populated with the text "System Administrator"
This also applies to Unbound DNS Overrides as well as Dynamic DNS entries from what I've gathered thus far.

**Comment by bsd-source** [comment]
I tested the DHCP static mappings by creating a new one and also modifying and existing one using OPNsense 19.7.4_1-amd64. I was unable to reproduce the issue, I did not test the Unbound DNS Overrides or anything else.

**Comment by fichtner** [comment]
Sounds like a rogue browser or third party tool autofill? Stranger things have happened. Try a different browser to confirm.

**Comment by ChuckWhitson** [comment]
Confirmed to not occur with browser addons disabled.

**Comment by ChuckWhitson** [comment]
- Closed
