### ISSUE TITLE
Dpinger is ignoring configured latency thresholds

### ISSUE THREAD

**Issue by muchahagrande** [opnsense/core#3759]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[*] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[*] I have searched the existing issues and I'm convinced that mine is new.

**Describe the bug**
I'm using 19.7.5. I enhabled the advanced options of gateway monitoring and edited latency thresholds of my IPv6 TUNNEL GATEWAY. I read that default values are from 200 to 500, but as I'm having about 250 all the time, I changed the values to 300/600, so the status below 300 should be "Online".
When I accept these values, dpinger keeps showing "warning (latency)" with a RTT of 217.8 ms.
I think that dpinger is not using my values but the default ones.

*Tip*: to validate your setup was working with the previous version, use opnsense-revert (https://docs.opnsense.org/manual/opnsense_tools.html#opnsense-revert)

**To Reproduce**
1. Go to 'System > Gateway > Single'
2. Click on 'Edit gateway setting'
3. Scroll down to 'Advanced' and click it
4. Edit Latency Thresholds to other values than the defaults
5. Save the changes
6. On the gateway list check the status of the edited gateway.

**Expected behavior**
If the RTT value indicated by dpinger is lower than the low threshold value, the gateway status should be "Online".

I'm using a virtualized OPNSense with VMWare ESXi 6.
The virtual interfaces are Intel E1000.
OPNsense 19.7.5-amd64
FreeBSD 11.2-RELEASE-p14-HBSD
OpenSSL 1.0.2t 10 Sep 2019

**Comment by definitio** [comment]
I have the same problem with Packet Loss thresholds.

**Comment by AdSchellevis** [comment]
it looks like a bug, can you install https://github.com/opnsense/core/commit/c83daaa54b5e0873c28fbf4cae706f1b55f59538, https://github.com/opnsense/core/commit/bb7557d38f57f5ec3b10b30c68247db761848417 and https://github.com/opnsense/core/commit/d5bd3a6cb7c5d2f155e709be02e56c2c215f9391 and run `pluginctl -r return_gateways_status` for me?

```
opnsense-patch c83daaa bb7557d d5bd3a6
pluginctl -r return_gateways_status
```

It kind of looks like milliseconds and seconds are swapped somewhere.

**Comment by definitio** [comment]
```
{
    "dpinger": {
        "WAN_DHCP6": {
            "name": "WAN_DHCP6",
            "status": "none",
            "stddev": "~",
            "delay": "~",
            "loss": "~"
        },
        "WAN_PPPOE": {
            "delay": "39.7 ms",
            "stddev": "5.4 ms",
            "loss": "0.0 %",
            "status": "none",
            "details": {
                "gwname": "WAN_PPPOE",
                "latency_avg": 39.7,
                "latency_stddev": 5.4,
                "loss": "0",
                "status": "none",
                "alert_interval": "1",
                "interval": "1",
                "latencyhigh": "500",
                "latencylow": "200",
                "loss_interval": "2",
                "losshigh": "20",
                "losslow": "10",
                "time_period": "60"
            },
            "name": "WAN_PPPOE"
        },
        "FALLBACK_DHCP": {
            "delay": "76.4 ms",
            "stddev": "16.9 ms",
            "loss": "0.0 %",
            "status": "none",
            "details": {
                "gwname": "FALLBACK_DHCP",
                "latency_avg": 76.4,
                "latency_stddev": 16.9,
                "loss": "0",
                "status": "none",
                "alert_interval": "1",
                "interval": "1",
                "latencyhigh": "500",
                "latencylow": "200",
                "loss_interval": "2",
                "losshigh": "20",
                "losslow": "10",
                "time_period": "60"
            },
            "name": "FALLBACK_DHCP"
        }
    }
}
```
The last gateway configured to have 20/50 Packet Loss thresholds.

**Comment by AdSchellevis** [comment]
@definitio your status looks normal (reports none), nothing to debug here if you ask me.

**Comment by definitio** [comment]
@AdSchellevis FALLBACK_DHCP has "losslow": "10" and "losshigh": "20" but they should be 20 and 50. My settings are ignored.

**Comment by AdSchellevis** [comment]
got it, https://github.com/opnsense/core/commit/4f3781cfa9210b83608fac51ad1e99f80bf59103 fixes the missing values.

```
opnsense-patch 4f3781c
```

should do the trick

**Comment by definitio** [comment]
@AdSchellevis Thank you.

**Comment by muchahagrande** [comment]
Ok... I tested the patch and it's working. Thank you.
