### ISSUE TITLE
Tokenizer broken since 19.7.5

### ISSUE THREAD

**Issue by mimugmail** [opnsense/core#3760]
Hi,

related to https://github.com/opnsense/plugins/issues/1537 I checked the functionality of this field and as soon as I hit return, comma or whatever to tokenize the value, it's gone. I checked on different places like FRR BGP Networks field, also Whitelist filed in Maltrail plugin. Everywhere the value is gone (just in time when trying to tokenize, not saving).
Maybe it's related to this:

o ui: fix tokenizer reorder on multiple saves

I doublecheck with 19.7.4 where everything works fine, also when reverting back it works again.

Maybe worth considering a hotfix release :(

**Comment by fichtner** [comment]
Which browser... all browsers?

**Comment by mimugmail** [comment]
Chrome latest in Windows. I didnt test others as it was reproduceable via revert. I can test later today

**Comment by AdSchellevis** [comment]
@mimugmail it's probably this https://github.com/opnsense/core/commit/a4217d8fcccad2676fc6e449d15df3437d814bff, strange it didn't popup on my end when testing, maybe it only has an issue if there's no content in the field. I'll have to check

**Comment by AdSchellevis** [comment]
@mimugmail can you try https://github.com/opnsense/core/commit/7a5a2712cdb8dc5cb4e2b7fae46430bd8849799f ?

**Comment by mimugmail** [comment]
@fichtner also happens to Firefox 69
@AdSchellevis patch works fine on my end, thx! :)

**Comment by mimugmail** [comment]
opnsense-patch 7a5a271

For Forum linking

**Comment by AndyX90** [comment]
After the patch i am not able to open the add-alias window.

**Comment by mimugmail** [comment]
Can you switch browser? For me it works fine.

**Comment by AndyX90** [comment]
I have tried with patch in Firefox and Chromium. Same result. Reverted to 19.7.4_1

**Comment by stalks** [comment]
Using Chrome this patch worked, thanks :)

**Comment by P2AK** [comment]
The patch also doesn't work for me when using Firefox, Chrome or Safari on OS X.  The alias I'm trying to edit also appears empty the first time I open it, but if I hit cancel and re-edit it, then the alias  shows its content.  I still can't add anything new to it after it shows its content though.

**Comment by stalks** [comment]
I applied the patch to OPNsense 19.7.5-amd64. I manually adjusted opnsense.js using the diff page 7a5a271

**Comment by fichtner** [comment]
I'll reopen for now. It seems safer to issue a revert of the original fix for a hotfix release today and then reassess the situation, ok?

**Comment by mimugmail** [comment]
Revert and hotfix sounds good :)

**Comment by AdSchellevis** [comment]
revert and hotfix is ok, but someone still should test master which reproducible issue https://github.com/opnsense/core/commit/7a5a2712cdb8dc5cb4e2b7fae46430bd8849799f has (if any), Most of the time these reports come from improper installation or issues reloading the page. (I'm quite certain the patch fixes the original issue, leaving the issue open without new evidence likely wouldn't result in other outcomes).

**Comment by fichtner** [comment]
Ok, closing and picking this back up for 19.7.6 backporting unless somebody points to an issue with the latest change.
