### ISSUE TITLE
OPNsense 19.7.5: Not able to add value to alias

### ISSUE THREAD

**Issue by JasMan78** [opnsense/core#3761]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[x] I have searched the existing issues and I'm convinced that mine is new.

**Describe the bug**
When I try to create an new alias or add e.g. a new port to an existing alias, the mask only suggest existing host aliases. Manuell input results in deleting the input.

**To Reproduce**
1. Go to 'Firewall:Alias'
2. Click on 'New alias' or edit an existing alias
3. Try to input a value in the content field
4. Value disappears as soon as you hit enter or choose another field

**Expected behavior**
Value should stay in the field

**Relevant log files**
I have not found any related log files.

**Additional context**
Reverted to 19.7.4_1. 
In this version I get also only suggestions for existing host aliases even when I create an port alias. But the manuell input works.

**Environment**
OPNsense 19.7.5 amd64
Intel(R) Celeron(R) CPU J1900 @ 1.99GHz (4 cores)
OnBoard Realtek
2 x Realtek GbE OnBoard LAN chips (10/100/1000 Mbit)

**Comment by mimugmail** [comment]
Duplicate of #3760

**Comment by JasMan78** [comment]
@mimugmail Thank you. Patch works also for me.
