### ISSUE TITLE
Lockout rule defaults to 192.168.1.1 only

### ISSUE THREAD

**Issue by tpcr** [opnsense/core#3763]
if I enable the lockout rule, it defaults to subnet 192.168.1.1/24
I have both 192.168.1.1/24 and 192.168.100.1/24 subnets on different interfaces
192.168.100.1/24 is the primary LAN interface.
The lockout rule only applies to 192.168.1.1. I want it on the other subnet.

**Comment by mimugmail** [comment]
Seems 1.0/24 is you LAN assignment. You can change this via assignments.

**Comment by fichtner** [comment]
Lockout is pinned to LAN if there, or lowest OPTx or WAN if nothing else found.

Conceptually, how would this need to be improved? Ideally without a select box for LANs because that will undo the automatic rule and potentially add pain for users who delete/shift their LAN interfaces around.

**Comment by tpcr** [comment]
I switched around the interfaces and it works now. LAN needs to be set as the primary local network. I can see that now. Thanks
