### ISSUE TITLE
Feature: allow editing, deleting existing dhcp static leases and add not existing devices (not yet connected)

### ISSUE THREAD

**Issue by terxw** [opnsense/core#3764]
Hi,

I would like to edit existing static leases or to delete them and add new ones, even if the device is not connected e.g add custom mac adress for devices which will be added in future, just like my [ asus router had 😁 ](https://www.asus.com/support/FAQ/114068/)

Importing and exporting static leases could be also good addition.

Thanx.

**Comment by RomanJos** [comment]
You can already add a static lease by MAC address in Service -> DHCP -> [interface] and scroll to the bottom. You may need to adjust your dhcp range (you can't assign a static lease inside what the DHCP server cover ex: assign 192.168.1.15 where the DHCP cover 192.168.1.10-254)
Exporting can be done by downloading the general config and importing just below it

**Comment by npradhan** [comment]
@jaxjexjox The way that I found is to go to System:Configuration:Backups, backup your configuration to an XML file, and edit the entries that look like this:

  <staticmap>
        <mac>00:16:01:0a:58:24</mac>
        <ipaddr>10.4.12.5</ipaddr>
        <hostname>Terrastatiion</hostname>
        <winsserver/>
        <dnsserver/>
        <ntpserver/>
  </staticmap>

And then just restore it. This workaround works, but this "bug" is very real - there should really be a way to do this through the UI.

**Comment by dj-sf** [comment]
> @jaxjexjox The way that I found is to go to System:Configuration:Backups, backup your configuration to an XML file, and edit the entries that look like this:
> 
> ```
>   <staticmap>
>         <mac>00:16:01:0a:58:24</mac>
>         <ipaddr>10.4.12.5</ipaddr>
>         <hostname>Terrastatiion</hostname>
>         <winsserver/>
>         <dnsserver/>
>         <ntpserver/>
>   </staticmap>
> ```
> 
> And then just restore it. This workaround works, but this "bug" is very real - there should really be a way to do this through the UI.

This worked for me, thank you. I also agree that this should be doable via the UI.
