### ISSUE TITLE
PPPoE manual Connect/Disconnect

### ISSUE THREAD

**Issue by logicethos** [opnsense/core#3766]
Been having some issues with my ISP connection, and I needed a way to manually connect & disconnect the PPPoE.  But there is no obvious way to do that, other than shut down OpnSense.

**Comment by fichtner** [comment]
Isn't that what Interfaces: Overview: Connect/Disconnect buttons are for?

**Comment by logicethos** [comment]
Doh, yes, I didn't know that existed.  Thanks.

**Comment by fichtner** [comment]
No worries, happy to help. :)
