### ISSUE TITLE
AC 9260 support? 

### ISSUE THREAD

**Issue by chymian** [opnsense/core#3767]
Hello,

I'm researching FW solutions for my customers and the question raised, whether OpSe is supporting a Intel Corporation Wireless-AC 9260 (rev 29)?

And in a deeper look, is it possible to to connect:

1) WLAN (wpa_supplicant) & Cable-ethernet to a WAN side,
2) hostap to the lan side? (optional)

I could have asked this questions in your forum, i know, but since you have tracking-software installed and  you expect your customers to be tracked by google, it's a NO GO. (there are other captcha solutions out there)

TIA
guenter

**Comment by bsd-source** [comment]
OPNsense is currently based on FreeBSD 11.2. Driver support is based on what FreeBSD supports. You need to ask your question on the FreeBSD forums.

Also reference being tracked by google. If you don't know how to avoid be tracked by logging in and posting to the OPNsense forum then you are in the wrong business.

**Comment by fichtner** [comment]
To be frank, wireless support isn't great with OPN and HBSD and FBSD et al. You should look for another solution.
