### ISSUE TITLE
System Tunables table visual bug in 19.7.5_5

### ISSUE THREAD

**Issue by Deutschi** [opnsense/core#3772]
**Describe the bug**
After upgrading to 19.7.5_5, the System - Settings - Tunables table is buggy. If you add new values, the table shows duplicate entries of the previous added row. The normal last row "Tunables are composed of runtime settings [...]" is gone.

**To Reproduce**
1. Have fresh 19.7.5_5 installed
2. Go to System - Settings - Tunables
3. Add a new value, then scroll all the way down
4. You should see duplicate entries and NOT the one you just added

**Expected behavior**
The new key/value should be in last position and there should be no duplicates

**Screenshots**
1. fresh 19.7, default values
> ![step1](https://user-images.githubusercontent.com/2011264/67103643-d7082f80-f1c5-11e9-916c-44bd29f9950d.jpg)

2. 19.7, add "test/test"
> ![step2](https://user-images.githubusercontent.com/2011264/67103657-dc657a00-f1c5-11e9-88ed-d2bb2e7d8eac.jpg)

3. fresh 19.7, update to 19.7.5_5, default values
> ![step3](https://user-images.githubusercontent.com/2011264/67102685-2cdbd800-f1c4-11e9-83e3-396d7f7e17c6.jpg)

4. 19.7.5_5, add "test/test"
> ![step4](https://user-images.githubusercontent.com/2011264/67102691-2f3e3200-f1c4-11e9-84b3-c8500924207f.jpg)

5. 19.7.5_5, add "test2/test2"
> ![step5](https://user-images.githubusercontent.com/2011264/67102693-3107f580-f1c4-11e9-918c-d29b03c5e27f.jpg)

**Additional context**
I verified this by installing a fresh OPNsense 19.7 several times now, without changing anything besides my timezone. The Tunables table works. After upgrading to 19.7.5_5, the weird behaviour is present.

**Environment**
OPNsense 19.7-amd64
FreeBSD 11.2-RELEASE-p11-HBSD
OpenSSL 1.0.2s 28 May 2019

and

OPNsense 19.7.5_5-amd64
FreeBSD 11.2-RELEASE-p14-HBSD
OpenSSL 1.0.2t 10 Sep 2019

HP ProLiant DL20 Gen10
Intel(R) Xeon(R) E-2136 CPU @ 3.30GHz
Broadcom NetXtreme BCM5720 Gigabit Ethernet
VMware ESXi, 6.7.0, 14320388

**Comment by AdSchellevis** [comment]
should be fixed with https://github.com/opnsense/core/commit/9299386602f613878f3ec166d6490230edb7230a also reported on the forum 
https://forum.opnsense.org/index.php?topic=14652.0

To test on your install:
```
opnsense-patch  9299386
```

**Comment by Deutschi** [comment]
Thank you, the patch fixes this issue. The little hint at the end

> Tunables are composed of runtime settings for sysctl.conf which take effect immediately after apply and boot settings for loader.conf which require a reboot.

is still gone though. Is this intended?

**Comment by AdSchellevis** [comment]
it looks like it https://github.com/opnsense/core/commit/ed785a66122f14f8d4b5ad1b0a1dea10efd43708 , should be visible after edit now (at least it does on my end)

**Comment by Deutschi** [comment]
Alright, thank you very much and have a nice weekend :-)

**Comment by AdSchellevis** [comment]
you're welcome, enjoy your weekend too.
