### ISSUE TITLE
Firewall groups are not synched

### ISSUE THREAD

**Issue by Nico82x** [opnsense/core#3779]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[x] I have searched the existing issues and I'm convinced that mine is new.

**Describe the bug**
Firewall groups and their members are not synched in HA configuration but the rules are. After adding the groups and setting membership on the 2nd node the rules are there.

**Expected behavior**
Groups should sync as well but maybe this is not a bug but a missing feature?

OPNsense 19.7.3-amd64
FreeBSD 11.2-RELEASE-p14-HBSD
OpenSSL 1.0.2s 28 May 2019

**Comment by AdSchellevis** [comment]
This should do the trick:
```
opnsense-patch c6cb6df 63769da 9cbc0aa
```


Although it seems that `interfaces_group_setup()` isn't cleaning on a new run, which could lead to groups being out of sync (same might be the case for the master). I'm opening a new issue for that, closing this one as being implemented.
