### ISSUE TITLE
OpenVPN traffic issues when using TCP tunnel

### ISSUE THREAD

**Issue by FingerlessGlov3s** [opnsense/core#3782]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[X] I have searched the existing issues and I'm convinced that mine is new.

**Describe the bug**
A clear and concise description of what the bug is, including last known working version (if any).

If you create a fresh simple TCP OpenVPN tunnel to a VPN server such as PIA, you get tunnel stability issues. Website take ages to load, speed test can take ages to start. Ping is sometimes all over the place, I've even see it drop from 200ms+ to 20ms by starting a speedtest, which I find odd (if anything you expect it the other way around).
Soon as you change the tunnel to UDP, all problems stop.

davidebeatrici, on IRC brought up this issue on his install, he's connecting to a softether VPN Server, using the latest OPNsense. I get the same issues he does connecting to PIA servers, after some testing.

**Expected behavior**
Stable VPN connection and low latency ping, just like it is over UDP.

**Screenshots**
![image](https://user-images.githubusercontent.com/3495647/67510006-17ffb880-f68c-11e9-8b35-29200f686bb3.png)
Ping lowered when the speedtest started and went high again when I stopped it.
![image](https://user-images.githubusercontent.com/3495647/67510557-1387cf80-f68d-11e9-8d17-6af258c3319c.png)
![image](https://user-images.githubusercontent.com/3495647/67510596-23071880-f68d-11e9-993d-64249fdcc4f6.png)

**Additional context**

**Environment**
Software version used and hardware type if relevant.
Test on OPNsense 19.7.4 and 19.7.5

davidebeatrici, has tested this on PFsense and the issue does not occur or when he connects from a client rather than OPNsense.

OPNsense 19.7.4 (amd64, OpenSSL).
Intel® i3-7100u
Network Intel® I210-AT

**Comment by FingerlessGlov3s** [comment]
Ping @davidebeatrici

**Comment by mimugmail** [comment]
Can you share Pia account via IRC?

**Comment by FingerlessGlov3s** [comment]
> Can you share Pia account via IRC?

I'm not 100% sure I want to do that :-s.

You could fire up a VPS somewhere and use this

https://github.com/angristan/openvpn-install

```
curl -sL https://raw.githubusercontent.com/angristan/openvpn-install/master/openvpn-install.sh | sudo bash -
```

**Comment by davidebeatrici** [comment]
I would like to add an important detail about the issue: it's not strictly related to OpenVPN, it happens with SoftEther VPN (client) as well.

I suspect it's a bug with TUN/TAP interfaces, possibly in the kernel.

In my case the VPN connection is not usable at all: as soon as there is traffic flowing through it, both latency and packet loss increase dramatically, eventually leading to the OpenVPN client reconnecting to the VPN server due to timeout.

**Comment by mimugmail** [comment]
But is this reproduceable with OpenVpn with tcp in general? I dont think so

**Comment by FingerlessGlov3s** [comment]
> But is this reproduceable with OpenVpn with tcp in general? I dont think so

Why I tested it with PIA

**Comment by mimugmail** [comment]
TCP inside TCP is always a bad idea when your main line experience only small packet loss

https://sshuttle.readthedocs.io/en/stable/how-it-works.html

**Comment by davidebeatrici** [comment]
I'm aware that TCP inside TCP may cause issues, but the same setup works well with pfSense.

**Comment by mimugmail** [comment]
Did you try disabling scrubbing rules?

**Comment by davidebeatrici** [comment]
What are those?

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/core/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
