### ISSUE TITLE
Webproxy - Enforce Group

### ISSUE THREAD

**Issue by AndyX90** [opnsense/core#3784]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[x] I have searched the existing issues and I'm convinced that mine is new.

**Is your feature request related to a problem? Please describe.**
In Webproxy - Authentication Settings, there is a setting called "Enforce local group"
(Restrict access to users in the selected (local)group.
NOTE: please be aware that users (or vouchers) which aren't administered locally will be denied when using this option.) I have an LDAP-Authentication Backend with Single Sign on enabled and want to require a specific domain group for Internet Access.

**Describe the solution you'd like**
Enhance this functionality to enforce a specific domain group.

**Comment by AdSchellevis** [comment]
You can either choose to sync groups via ldap ("Synchronize groups") or use extended queries to limit the allowed users.

**Comment by AndyX90** [comment]
Yes, you're right! Sorry.
