### ISSUE TITLE
User import not showing new available users to import

### ISSUE THREAD

**Issue by ahaase-c4u** [opnsense/core#3786]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[x] I have searched the existing issues and I'm convinced that mine is new.

**Describe the bug**
Our opnsense is connected to an Active Directory. When trying to add a user to the firewall, the list, where normally the new user can be checked, is empty. We verified, that our ldap configuration is correct and also temporarily removed the extended query, which restricts the group of users that can be selected. But the behaviour didn't change.

**To Reproduce**
1. add user to correct ldap group
2. In System -> Access -> Users click on the cloud to import new user
3. In the opened popup window the list of users to import is empty

**Expected behavior**
The list should contain the users being in the correct group, but not existing on the firewall yet.

**Environment**
Software version used and hardware type if relevant.
e.g.:

OPNsense 19.7.5_5-amd64

**Comment by ahaase-c4u** [comment]
New info: after diving into OPNsense/Auth/LDAP.php and checking how search() works, it turns out, that this is a question of ldapScope. We had configured search scope of "one level", but our users exist within OUs. So the search() couldn't find anything.

The only thing, that makes me wonder, is the fact, that we didn't change anything in search scope settings or user hierarchy for months. Maybe there existed a bug in an older version of opnsense, that is now fixed and leads to this behaviour?

Nevertheless, my problem is fixed.

**Comment by AdSchellevis** [comment]
between 19.7.4 and 19.7.5_5 there weren't any changes to this area as far as I know, the scope has been there for a long way too (years, probably since our first version). I don't think we should keep this one open, maybe someone accidentally changed a setting somewhere.
