### ISSUE TITLE
OPNsense VM crashes on Hyper-V and AMD CPUs

### ISSUE THREAD

**Issue by StrikerTwo** [opnsense/core#3789]
I have installed a new virtual machine using the latest OPNsense image (19.7) on my Windows Server 2016. 
The virtual machine intermittingly just switches off. Sometimes this happens right after booting, sometimes during initial setup, sometimes during install and sometimes during normal operation.

The eventlog shows a critical event ID 18580, source Hyper-V worker: 
"<VM>" wurde ausgeschaltet, da für den virtuellen Prozessor aufgrund einer Abweichung der TLB-Seitengröße ein Fehler aufgetreten ist.
Googling that error message (yes, I tried the english version "TLB page size mismatch" as well) shows ONLY a OPNsense forum thread:
https://forum.opnsense.org/index.php?topic=13606.0

Comparing the two issues shows that we both use Hyper-V on an (older) AMD processor: An AMD Phenom II X4 in my case, and an AMD Opteron 6134 in koldomon's. Also for him this only happened after an OPNsense upgrade to 18.7.

This probably is an upstream issue with FreeBSD, but maybe you have an idea (or back channels to ask BSD people ;))

**Comment by rootwyrm** [comment]
This is actually a hardware issue on the CPUs in question. Specifically, AMD Erratum 298.

https://www.anandtech.com/show/2477/2
https://www.amd.com/system/files/TechDocs/41322_10h_Rev_Gd.pdf

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/core/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.

**Comment by ChristianUlbrich** [comment]
FWIW this does not seem to be related to _only_ Hyper-V, but _also_ to ESXi. Booting current (19.7+) OPNSense on an updated ESXi 6.5 on an (arguably somewhat ancient) HP DL385 G6 (with 2xOpteron 2425HE) **crashes the whole system**. Although this is most likely a ESXi bug as well, it would be fine, to get to know _the special kernel boot parameter_ allowing booting OPNSense on K10-based Istanbul cores... :)

**Comment by ZenithElevate** [comment]
The same problem under Hyper V on Xeons: non-stop crashes with 26.1.
