### ISSUE TITLE
Adding a Virtual IP to LAN makes system inaccessible from WAN until reboot

### ISSUE THREAD

**Issue by syserr0r** [opnsense/core#379]
LAN interface is 192.168.1.254/24; I accidentally added a Virtual IP for 192.168.2.254/32 (instead of /24) and the webgui and all forwarded ports were inaccessible from WAN.

I was able to remote in from another connection and the webgui was still accessible on the LAN network -- both after removing and after re-adding the LAN virtual IP (with the correct subnet) the box was still inaccessible from WAN.

This may already have been proposed, but a change-confirmation option such as that found in [Vyatta](http://vyos.net/wiki/FAQ#I_am_afraid_my_changes_may_break_connectivity_or_make_system_inaccessible_in_other_way._What_should_I_do.3F) would be fantastic

**Comment by fraenki** [comment]
:+1:  I like the idea of an (optional) automatic config rollback

**Comment by fichtner** [comment]
I also like it. :) The current reality is that some pages do have an apply while others don't. There's no underlying pattern or common "apply widget" in the code and we'd certainly wish not to touch the old pages, but that does not seem doable.

Not sure what makes WAN lock up like that, so I'll take a closer look-

**Comment by fichtner** [comment]
After some internal discussion rollbacks are on the far horizon, and the underlying bug report is a setup problem and never happened again to my knowledge -> closing.
