### ISSUE TITLE
Allow the administrator to specify multiple IPsec phase 1 encryption algorithms

### ISSUE THREAD

**Issue by whislock** [opnsense/core#3790]
StrongSwan allows for the configuration of multiple encryption/authentication algorithms for phase 1 settings. OPNsense does, too, for everything but the encryption algorithm itself. It would be great if we could get a multi-select or a checkable list for this, similar to phase 2 configuration. It's very handy to be able to deal with OS-level client defaults without having to manually configure something.

**Comment by whislock** [comment]
What about this is incomplete?

**Comment by AdSchellevis** [comment]
https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

> incomplete: issue template missing or incomplete

**Comment by whislock** [comment]
I'll try this again.
