### ISSUE TITLE
Captive portal not authenticating

### ISSUE THREAD

**Issue by Osvalcosta** [opnsense/core#3791]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[-] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[-] I have searched the existing issues and I'm convinced that mine is new.

**Describe the bug**
A clear and concise description of what the bug is, including last known working version (if any).

*Tip*: to validate your setup was working with the previous version, use opnsense-revert (https://docs.opnsense.org/manual/opnsense_tools.html#opnsense-revert)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Relevant log files**
If applicable, information from log files supporting your claim.

**Additional context**

**Environment**
Software version used and hardware type if relevant.
e.g.:

OPNsense 19.1.1 (amd64, OpenSSL).
Intel® Xeon™ E3-1225V5 3.3Ghz Quad Core
Network Intel® I210-AT

**Comment by Osvalcosta** [comment]
![Screenshot from 2019-11-05 10-08-03](https://user-images.githubusercontent.com/11290058/68193916-53678480-ffb4-11e9-87d2-93b230460f16.png)
all the setup are fine, when you authenticate the user and password.... voulcher or local user you get this error

**Comment by jbdu12** [comment]
Hello,
I have a same problem: authentication failed on the portal page.
It's a new installation of OPNSENSE 19.7.6.
I use local database for authentification. If I test in "SYSTEM:ACCESS:TESTER", it's good.

In "Service:Captive Portal:Log File, i have  with a good user "toto": 
![Capture d’écran de 2019-11-06 14-12-16](https://user-images.githubusercontent.com/57445162/68301222-c699f500-009f-11ea-8b61-193184127cf1.png)

For test, i use a fake user "tata", i have a DENY.
![Capture d’écran de 2019-11-06 14-20-16](https://user-images.githubusercontent.com/57445162/68301600-9c950280-00a0-11ea-80a4-867948d13914.png)

With my good user, I have not DENY of captive's log.....  

Do you have idea?

thanks

**Comment by Osvalcosta** [comment]
I got fixed, delete the database and update the system, i did it and everything is working fine
