### ISSUE TITLE
NPTv6, gateway NDP breaks when adding another VIP

### ISSUE THREAD

**Issue by FingerlessGlov3s** [opnsense/core#3793]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[X] I have searched the existing issues and I'm convinced that mine is new.

**Describe the bug**
I'll try my best to explain this issue, I'll start from the beginning
So I have a OVH server setup, which is running Proxmox, I install OPNsense as a VM.
I've configured WAN IPv6, with my /64 prefix. Turned off gateway monitoring.
I've created some fdxx::/64 networks. So to get internet access I'm using NPTv6. So I add some VIPs against the WAN interface, go in to NPTv6, add the mapping, it works cool, I can ping6 google.com
So I go to add another VIP but, after applying the new VIP. The ping stops in the VM.
I look at the NDP table and see this. "2001:41d0:899:75f::1" which is my gateway is now, incomplete on the linklayer, strange I thought. I've found various ways for it to get working again.

- Ping an IPv6 address from the WAN interface's main IPv6 address
- Turn on gateway monitoring (basically does the first option for you, every second or so)
- any form of IPv6 traffic that isn't for the NPTv6 mapped addresses gets it working again.

```
root@OPNsense:~ # ndp -a
Neighbor                             Linklayer Address  Netif Expire    S Flags
fe80::580d:bff:fe75:f202%vtnet1_vlan30 5a:0d:0b:75:f2:02 vtnet1_vlan30 permanent R
fd1b:28f4:abda:20::1                 5a:0d:0b:75:f2:02 vtnet1_vlan20 permanent R
fd1b:28f4:abda:20::10                72:d9:a6:a3:4a:e4 vtnet1_vlan20 8s        R
fe80::70d9:a6ff:fea3:4ae4%vtnet1_vlan20 72:d9:a6:a3:4a:e4 vtnet1_vlan20 10s       R
fe80::580d:bff:fe75:f202%vtnet1_vlan20 5a:0d:0b:75:f2:02 vtnet1_vlan20 permanent R
fe80::580d:bff:fe75:f202%vtnet1_vlan5 5a:0d:0b:75:f2:02 vtnet1_vlan5 permanent R
fe80::580d:bff:fe75:f202%vtnet1_vlan10 5a:0d:0b:75:f2:02 vtnet1_vlan10 permanent R
fe80::580d:bff:fe75:f202%vtnet1      5a:0d:0b:75:f2:02 vtnet1 permanent R
2001:41d0:899:75f::1                 (incomplete)      vtnet0 1s        I  3
2001:41d0:899:75f:abcd::1            02:00:00:eb:cc:89 vtnet0 permanent R
2001:41d0:899:75f:4::2               02:00:00:eb:cc:89 vtnet0 permanent R
2001:41d0:899:75f:4::6               02:00:00:eb:cc:89 vtnet0 permanent R
fe80::ec4:7aff:fe7b:6f7a%vtnet0      0c:c4:7a:7b:6f:7a vtnet0 23h49m6s  S R
fe80::ff:feeb:cc89%vtnet0            02:00:00:eb:cc:89 vtnet0 permanent R
2001:41d0:899:75f:0:b19:a55:9a1      02:00:00:eb:cc:89 vtnet0 permanent R
```

I'm using 128 to 128 NPTv6 mappings.

**Expected behavior**
New VIP to be added and NPTv6 to keep working and passing traffic.

**Additional context**
I've tested this on PFsense, to make sure its not something weird with Proxmox or OVH's network. It works as expected in Pfsense.
I had to do the following here: https://forum.proxmox.com/threads/opnsense-pfsense-ipv6-and-vips-vips-not-routable-ovh-network.59711/post-275643
To get IPv6 working in PFsense and OPNsense, but I think its safe to say its a OPN bug???

**Environment**
Software version used and hardware type if relevant.
OPNsense 19.7.6
PFsense 2.4.4
Proxmox 6.0.9

CPU: Virtualised (Intel(R) Xeon(R) CPU D-1520 @ 2.20GHz)
Virtio network adapter.
1GB RAM
2 vCPU Cores

**Comment by FingerlessGlov3s** [comment]
Left OPNsense over night, with no IPv6 traffic going.
NDP no longer has the gateway in the NDP table and can't ping6 from a VM with NPT setup.
I've setup the same thing on another VM but with PFsense as its router, PFsense still has it in the NDP tablel

So I delete the NDP records on PFsense using ndp -d 2001:41d0:899:75f::1, to see if it comes back.
30 seconds later it comes back in to the NDP table, which isn't happening in OPNsense.

PFsense IPv6 setup is the same as OPNsense, just different IPs, Still using the same 2001:41d0:899:75f:: prefix

**Comment by fichtner** [comment]
Ideally, we'd need rule screenshot and relevant rule from /tmp/rules.debug

Chances are the rule references all interface addresses in which case this includes VIPs by default. This is may be expected. What use case is the VIP on WAN for?

**Comment by FingerlessGlov3s** [comment]
Not sure which screenshots you would like be see below for some you might be interested in.
I'm adding a VIP on the WAN, so I have another IPv6 address I can use NPTv6 with, so I can then map fd:: network IP with it, to give that VM IPv6 Internet.


![image](https://user-images.githubusercontent.com/3495647/68328918-22787400-00c8-11ea-818b-43da8854f9df.png)
![image](https://user-images.githubusercontent.com/3495647/68329102-771bef00-00c8-11ea-98d6-bfbb4d608109.png)
These Mapping both use /128
![image](https://user-images.githubusercontent.com/3495647/68329140-8dc24600-00c8-11ea-8024-e668512a8fe0.png)
![image](https://user-images.githubusercontent.com/3495647/68329349-f6a9be00-00c8-11ea-94e7-86793eb5fd32.png)


![image](https://user-images.githubusercontent.com/3495647/68329375-032e1680-00c9-11ea-8090-fe1791d18b38.png)
![image](https://user-images.githubusercontent.com/3495647/68329424-180aaa00-00c9-11ea-8e54-c12885dd8c10.png)
![image](https://user-images.githubusercontent.com/3495647/68329466-2d7fd400-00c9-11ea-93f3-d6d38f472b03.png)
![image](https://user-images.githubusercontent.com/3495647/68329568-6ae46180-00c9-11ea-98ee-3ae9fcf3d4c5.png)


[rules_debug.zip](https://github.com/opnsense/core/files/3816275/rules_debug.zip)

**Comment by FingerlessGlov3s** [comment]
Just had the issue happening, without changing anything in OPNsense.
Was looking at the NDP table, via SSH `ndp -a`, I did a ping6, cancelled it and then second go of doing it. I wouldn't ping6 google.com and the gateway had gone to (incomplete) again.

Very strange behaviour.

**Comment by FingerlessGlov3s** [comment]
Installed OPNsense on another VM, same host and setttings.

I've set it up as close as I can get to the live OPNsense VM, it has IPv4 and IPv6 setup on the WAN.
Same NAT rules, same NPTv6, same gateway.
IPv6, is in the same /64 prefix, just using different IPs of course.

I've gone through all the settings, and I can't see any difference now.
Only difference is a few firewall rules, which are allow rules for specific ports on the Live instance.

Anything else I can compare them with?

Not sure there is any WebUI settings for NDP anyway, but I could be wrong.

**Comment by FingerlessGlov3s** [comment]
To get the test OPNsense to work exactly the same, I decided to copy over the rest of the config, so it would be all the same. So I went slowly through all the config keeping an eye on the NDP table, didn't take too long, good old copy n paste.

Soon as I set one of the VLAN interfaces IPV6 address to fd1b:28f4:abda:20::1/64 and then setup its corresponding fd1b:28f4:abda:20::10/128 NPT mapping for the Ubuntu server VM. The issue started happening. Even though another VM which was created for testing this, worked fine with NPTv6 with a different fd:: network. So I thought, lets change this to another prefix, so I changed it to fd37:c611:72fb:20/64. I've not had the issue happen again yet, even after adding more VIPs.

I'm sure that fd1b:28f4:abda:20::1/64, is a unique local address (ULA), so not sure why it made it break.

Shall keep an eye on NDP table now, to see if it has indeed fixed it.

**Comment by FingerlessGlov3s** [comment]
This has indeed fixed the issue.

I shall close the issue, not sure if the same will happen to some one else, if they set their network up with the fd1b:28f4:abda:20::/64 IPv6 address. Please open if someone gets a similar issue or this would be investigated by OPNsense team.

This is a very strange issue.
