### ISSUE TITLE
Allow the administrator to specify multiple IPsec IKE/SA algorithms

### ISSUE THREAD

**Issue by cyveris** [opnsense/core#3794]
**Is your feature request related to a problem? Please describe.**
As I'm sure everyone that's tried to deploy an IPsec road-warrior VPN is aware, client operating systems have a multitude of default IKE/SA cryptographic configurations that may or may not be easy to modify. macOS/iOS are particularly nasty examples of this - crypto configurations can't be modified without writing a .mobileconfig profile. The IKE (phase 1) configuration facility within IPsec tunnel configuration allows the administrator to select multiple has algorithms and DH groups for a single phase 1 configuration, but only a single encryption algorithm. The SA (phase 2) configuration facility allows for the selection of multiple encryption algorithms and hash algorithms, but only one DH group. This can, in theory, lead to a configuration that is not universally compatible with the default crypto configs across all client operating systems that an administrator may target.

**Describe the solution you'd like**
Modify the IPsec phase 1 and phase 2 UIs to allow for multiple selections across all three cryptographic parameters: encryption algorithm, hash algorithm, and DH group.

**Describe alternatives you've considered**
The only other alternative I can think of is hand-jamming this into ipsec.conf, which would get clobbered if any settings are saved within the web UI.

**Additional context**
https://www.dropbox.com/s/smulg8lv91nzec2/Screenshot%202019-11-06%2007.57.29.png
https://www.dropbox.com/s/psgoes894y23qfm/Screenshot%202019-11-06%2007.57.54.png

**Comment by stumbaumr** [comment]
Have a look at https://forum.opnsense.org/index.php?topic=12147.0

You can use the includes to even overwrite settings from the webgui.

I used https://ldx.ca/notes/ipsec-os-x-el-capitan.html as a source for a common setup for all my clients. Might still be up-to-date...

**Comment by whislock** [comment]
I'm aware that includes are usable, and I am **very** well versed in IPsec configuration per OS. I just think it would be far more ideal to have the option exposed in the UI.

**Comment by mimugmail** [comment]
Indeed, but usually every client around should support AES256:
https://docs.opnsense.org/manual/how-tos/ipsec-rw.html

**Comment by AdSchellevis** [comment]
It will be difficult to change this and keeping backward compatibility, specifically for the `encryption-algorithm` part (which contains different key lengths for aes, camellia and blowfish and can't therefor simply be replaced with a new comma separated value or list) . 

Originating from here:

https://github.com/opnsense/core/blob/d6434881269e220dab48015104bbc13e97e52162/src/etc/inc/plugins.inc.d/ipsec.inc#L83-L96

and 

https://github.com/opnsense/core/blob/d6434881269e220dab48015104bbc13e97e52162/src/etc/inc/plugins.inc.d/ipsec.inc#L115-L128

We're not planning to work on this ourselves, marking this as "help wanted" in case someone wants to give this a try on the following months to come (it will timeout automatically after a couple of months if no one steps up).

**Comment by johnaheadley** [comment]
@AdSchellevis For backwards compatibility, what do you think of this design?

The default page would look the same,

![one-encryption-algo-default](https://user-images.githubusercontent.com/11711559/69905064-c372eb80-1363-11ea-997e-4a4eb48588ea.png)

but if you clicked the plus sign, then you get more rows to add another encryption/authentication algorithm set.

![two-encryption-algos](https://user-images.githubusercontent.com/11711559/69905083-db4a6f80-1363-11ea-98b1-975ec18ad239.png)

**Comment by AdSchellevis** [comment]
@johnaheadley it could work, but it's a bit tricky to fit it in nicely. A single combined selection would be easier from a ui perspective, but is difficult to keep backwards compatible. If you want to give it a shot, just open a PR and I try to review it when I can.

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/core/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
