### ISSUE TITLE
Line separators to improve the organization of many entries (specifically Firewall Rules)

### ISSUE THREAD

**Issue by Nico82x** [opnsense/core#3795]
Hi,

I think it would be great to have the option to install line separators between many rules to improve rule management. Maybe with an optional description like "some exceptions". I know there is a grouping feature but at least we do not really use this one in our daily business since using those filters the order of the rules in the global context is lost. A line separator with descriptions like "put all exceptions below this line" would make a lot of tasks much easier and improve the general overview.
This is not limited to firewall rules but this is the place where we have lots of entries typically. 

Thanks,
Nicolaj

**Comment by fichtner** [comment]
Hi Nicolaj,

We do have a category-based tagging which works well for organising and have no plans to support something else in this regard for now.


Cheers,
Franco

**Comment by Nico82x** [comment]
Hi Franco,

yes, I'm aware of that. Was just an idea to further improve that but if there are no plans, there is nothing I can do about it. Still very happy with the product! Thanks for the quick reply.

All the best,
Nicolaj

**Comment by fiddletwix** [comment]
Franco,

Can you elaborate why there are no plans for this feature? Is it a technical issue or more a prioritization issue? I ask because as a recent convert to opnsense I found the feature invaluable when managing fw and nat rules in pfsense

**Comment by AdSchellevis** [comment]
It doesn't fit out vision, as explained on multiple occasions (such as https://github.com/opnsense/core/issues/3262 and the forum likely has multiple topics too), we're always open for pull-requests improving the current mechanisms in place (categories), just aren't going to add rules without content for presentation purposes only.

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/core/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
