### ISSUE TITLE
IPS permits traffic despite being blocked in the log.

### ISSUE THREAD

**Issue by miodzicho** [opnsense/core#3799]
Configured Suricata, enabled, IPS mode enabled, ET telemtry rules downloaded and enabled. Under alert I see SSH scan has been blocked, however I have NAT to internal SSH gateway, and I see IP which should be blocked is reaching gateway...

2019-11-07T12:05:40.644965+0100   2001219   blocked   WAN   185.232.x.x   62920   x.x.x.x   22   ET SCAN Potential SSH Scan

OPNSense 19.7.6
Suricata 4.1.5_1

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/core/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
