### ISSUE TITLE
Time zone Etc/GMT

### ISSUE THREAD

**Issue by jorgevisentini** [opnsense/core#3800]
Hi.

I think we have a bug on Time zone settings (**System: Settings: General**)

I set Time zone to **Etc/GMT-3** and the time has been increased to +3.
I think it's inverted because **Etc/GMT+3** turn back 3 hours

I am from Brazil, where the time zone is America/Sao_Paulo or Etc/GMT-3.

Thank you all!

**Comment by fichtner** [comment]
I built a test kernel with the latest tzdata release. It's unlikely something is horribly broken the way described. Try the kernel and if it persists we need to properly define the "measuring method" taking place here.

    # opnsense-update -br 19.7.3_2
    # opnsense-shell reboot


Cheers,
Franco

**Comment by fichtner** [comment]
America/Sao_Paulo works, but Etc/GMT is indeed reversed. I don't recommend using them at the moment. I don't think there's anything we can do from the GUI since we select the appropriate file which either has the wrong name or wrong content.

**Comment by fichtner** [comment]
Soo... It turns out the inversion is *intended* by tzdata for the Etc category.

https://stackoverflow.com/questions/49916815/strange-timezone-etc-gmt-1-in-firefox

```
The tz database identifiers of the form Etc/GMT±* deliberately have an inverted sign than the usual forms we expect under ISO 8601. That is, they are in terms of positive values being West of GMT, rather than positive values being East of GMT. This is covered both in the Wikipedia article on the tz database, and in the commentary in the tz database itself.
```

https://en.wikipedia.org/wiki/Tz_database#Area
https://github.com/eggert/tz/blob/2018d/etcetera#L36-L42

As such, I vote for close also because this is the first in years this was raised. Ok?

**Comment by jorgevisentini** [comment]
Thank you for your explanation.

Now I understand why.
Soo yes, you cant close, please.

Thank you all.
