### ISSUE TITLE
Route configuration after reboot

### ISSUE THREAD

**Issue by axldd** [opnsense/core#3803]
Hi,

I have connected a remote network to my local network (both routers run OPNsense 19.7.6-amd64) via an OpenVPN tunnel. The connection works reliably.
To make a subnet on one side of the tunnel (VPN server side) available to hosts on the remote network, i added a route in webgui/ui/routes on the remote OPNsense instance. This also works as expected. Now I have realized, that after I rebooted the remote router, the route is not working anymore. I have to go to the webgui, disable and then enable the route again to get it to work.
Is this the expected behaviour? To clarify the setup, I'll try to ASCII paint a diagram:
```

192.168.2.0/24 
opnsense2 <-- remote network
-------------
10.10.0.2
|
openvpn tunnel
|
10.10.0.1
-------------
opnsense1 <--- local
192.168.1.0/24
|
192.168.3.0/24

```
To make the 192.168.3.0/24 network availabe from the remote network, I added the route net: 192.168.3.0/24 gw: 10.10.0.1 to the opnsense2 router. This works but after rebooting opnsense2 I have to disable and enable the route manually to get it to work.

**Comment by mimugmail** [comment]
The route get's executed before the tunnel is up. 
Normally you don't need a route, this is handled by local and remote network via OpenVPN configuration, please check these values.

**Comment by axldd** [comment]
Thanks for the quick reply!
The remote router (OpenVPN client) has 192.168.1.0/24 as remote network and the server has 192.168.1.0/24 set as local and 192.168.2.0/24 as remote. The communication between these two also works fine. I added the route for the .3 network

**Comment by mimugmail** [comment]
And why don't you add .3 network in OpenVPN? This will also work :)

**Comment by axldd** [comment]
Okay I did not notice that it is possible to add more than one network in the text fields (I know, the I should have looked at the tooltips first^^).
Thanks a lot!

**Comment by mimugmail** [comment]
@fichtner this maybe also affects other ticket regarding routed IPSEC and missing routes after reboot.
