### ISSUE TITLE
Timeout while connecting to the selected mirror

### ISSUE THREAD

**Issue by labsy** [opnsense/core#3809]
Hi,

**BUG DESCRIPTION**
running on ESX 6.5u3, after upgrading 19.1.10 to 19.7.4 (automatically) I've gut the issue looking for UPDATES. Now I am on 19.7.4, there are 2 newer versions, but when I try "Check for Updates" I get:

Timeout while connecting to the selected mirror.

Seems like I am not alone:
https://forum.opnsense.org/index.php?topic=13727.msg63204#msg63204

And seems like version 19.1 had the same problems:
https://forum.opnsense.org/index.php?topic=11341.0

**LOGS**
I don't know which LOGS to examine, but what I can find under GUI, the only relevant seems to be:

Nov 10 03:15:36 | kernel: pkg-static: Repository OPNsense cannot be opened. 'pkg update' required
Nov 10 03:15:36 | kernel: pkg-static: Repository OPNsense has a wrong packagesite, need to re-create database

Please, let me know if I can help debugging further.
thank you!

**Comment by fichtner** [comment]
I suppose it's a MTU issue. Big TCP packets don't get forwarded by the host, maybe because of VLANs here or there lowering the maximum packet size invisibly.

On your [WAN] try to lower the MTU by 8 or 16 to test that theory.


Cheers,
Franco

**Comment by labsy** [comment]
Deafult 1500 MTU definitelly was not OK, so I drilled down to usual 1472:
`ping -D -s 1472 <gateway>`
What's weird, I cannot ping anything beyond NAT. Also DNS lookup does not pass Masquerading.
As I have single WAN adapter, but with multiple WAN IP addresses, I guess some SNAT/Masque might have get interpreted wrong after upgrade.

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/core/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.

**Comment by cynay** [comment]
I have the same problem, but when i connect over ssh an choose: 12 Update from console it works?!

**Comment by PaddyMac** [comment]
I'm having the same issue on a fresh install of OPNsense 20.7 running under bhyve on FreeBSD 13-CURRENT. I just get a timeout whether I try to update package info from the web GUI or by running "pkg update" from a shell. I've tried all the US mirrors in the dropdown box. If you need information to help troubleshoot, just tell me what you need.

**Comment by maxfield-allison** [comment]
I'm also encountering this issue now on 20.7.4

**Comment by maxfield-allison** [comment]
Very strange, after some digging it looks like something is causing resolv.conf to drop any nameserver entries. I added "nameserver 1.1.1.1" and instantly pkg was able to work properly.

**Comment by maxfield-allison** [comment]
Even more digging, I changed my unbound dns interface settings to only allow the networks that my Pihole's are running on, saved and applied. Refreshed resolv.conf and boom nameserver entry is gone.

**Comment by maxfield-allison** [comment]
looks like saving and applying without changing any settings in unbound causes the nameserver entry to be deleted. I'll keep looking and see if I can find the culprit. Feel free to reopen and assign this to me as a possible bug @AdSchellevis

**Comment by maxfield-allison** [comment]
I was able to determine that without any DNS servers listed under "system>settings>general DNS servers" and with the "Do not use the local DNS service as a nameserver for this system" box checked, the system doesn't fall back to any nameservers by default. Likely isn't the issue here but it will be good to know in case someone else finds themselves at the same edge I did.

**Comment by cynay** [comment]
I tried saving and applying with and without changing any settings in unbound. But in my case the entries resolv.conf didn't vanish.

I have done a few changes since i had the problem, like adding blacklists to unbound and more. Looks like on my side the problem isn't there anymore, updates over the GUI started working again (no timeout).
