### ISSUE TITLE
Unable to set static IPv4 address on interface

### ISSUE THREAD

**Issue by Celestialdeath99** [opnsense/core#3811]
**Description**
I added a new VLAN and assigned it to a new interface. However when I went to set the IPv4 Configuration type to static it would not accecpt any IP address. It states the following error:
![image](https://user-images.githubusercontent.com/6267549/68560960-3a722f80-0409-11ea-8e95-85ede489e877.png)

No matter what IP I enter or what network mask I select the issue occurs. I have 5 other interfaces that were configured a long time ago that did not have issues, but now I cannot create this interface I need.

**To Reproduce**
1. Go to 'Interfaces'
2. Create a new interface then click on it to edit it.
3. Enable the interface then attempt to set a static IPv4 address.

**Expected behavior**
The IP address should be set for the interface.

**Screenshots**
You can see the IP I tried to set was 10.0.300.1/24 below however the error at the top of the page occurred.
![image](https://user-images.githubusercontent.com/6267549/68561132-da2fbd80-0409-11ea-8edf-6cb21da97d36.png)

Additionally this is my Interface Assignments page:
![image](https://user-images.githubusercontent.com/6267549/68561189-1b27d200-040a-11ea-8592-2032a768da48.png)

**Additional context**
I have attempted to perform this action in the latest version of Google Chrome, Firefox, Microsoft Edge, and Safari and the issue occurs on all the browsers.

**Relevant log files**
I was unable to locate any messages in any of the logs regarding this issue.

**Environment**
OPNsense 19.7.6-amd64
FreeBSD 11.2-RELEASE-p14-HBSD
OpenSSL 1.0.2t 10 Sep 2019
Intel(R) Xeon(R) CPU E5649 @ 2.53GHz (12 cores)

**Comment by fichtner** [comment]
Hi,

"300" is not a valid 8 bit unsigned integer. The maximum is 255.


Cheers,
Franco

**Comment by Celestialdeath99** [comment]
Sorry, that was a bad example as you are correct. However the issue I am having still occurs even with a valid 8 bit unsigned integer. For example, the address 10.0.100.1 also produces the error. Again I was unable to locate any thing referencing it in the logs.

![image](https://user-images.githubusercontent.com/6267549/68619544-4acded00-0491-11ea-8ff2-016fb6cc85a8.png)

**Comment by AdSchellevis** [comment]
copy->paste issue? (space[s] in front or behind)

**Comment by Celestialdeath99** [comment]
I am not copying or pasting. I am typing it in. It still occurs across all the major browsers as I mentioned earlier as well.

**Comment by AdSchellevis** [comment]
works like a charm over here, same version. maybe some vague browser plugin trying to inject something that doesn't belong in the field, the validation itself is pretty straightforward.

https://github.com/opnsense/core/blob/b97789b2d9ea717a2e70b1c2f7a42cfbbdbebf0c/src/www/interfaces.php#L810-L813

**Comment by Celestialdeath99** [comment]
I have no plugins installed in the browsers, that and it was occurring across all the browsers I tested. I just tried it again today and it worked now. I am not sure what was going on but it is now working.
