### ISSUE TITLE
IPsec IKEv2 mutual RSA/EAP-TLS not working as peer id setting is missing

### ISSUE THREAD

**Issue by wh0else** [opnsense/core#3815]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[x] I have searched the existing issues and I'm convinced that mine is new.

See issue https://github.com/opnsense/core/issues/2070 - can't reopen, same issue

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/core/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
