### ISSUE TITLE
[Bug] Wifi is broken in 20.1

### ISSUE THREAD

**Issue by DarkSunOne** [opnsense/core#3818]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[x] I have searched the existing issues and I'm convinced that mine is new.

**Describe the bug**
When assigning a f.e. run0_wlan1 to the wan interface, the interface type switches to cable, so your not able to to change the wifi settings again until you completely remove the wan interface, and reassign it.

WPA Settings seems to be ignored:
When creating a wifi ap interface, with enabled WPA(2) settings, the provided network is still 'Open' further its only possible to join open networks as a client.

Used wlan: Ralink USB Wlan-stick with  RT5370 chipset (works well when configuring in commandline)

**To Reproduce WAN interface problems**
1. Attach wlan stick and create a wlan device under "Interfaces -> Wireless -> Devices"
2. Assign the created wlan device to wan, and enter wlan settings
3. hit save

**Expected behavior**
Wan interface connects to wifi, and settings can be changed later

**Screenshots**
(will upload later today)

**Relevant log files**
No logs found

**To Reproduce missing WPA settings**
1. Attach wlan stick and create a wlan device under "Interfaces -> Wireless -> Devices"
2. Assign the created wlan device to opt1
3. change wlan settings to ap
4. enable wpa2 and enter a passphrase
5. hit save & apply
6. See error

**Expected behavior**
There should be a new wifi which is wpa2 secured

**Screenshots**
(will upload later today)

**Environment**
Software version used and hardware type if relevant.
e.g.:

OPNsense 20.1 (armv7, OpenSSL).
ARM Cortex-A9 r4p1
&
OPNsense 20.1 (aarch64, OpenSSL).
ARM Cortex-A53
[Ralink WiFi Dongle RT5370 Chipsatz](https://www.amazon.de/gp/product/B015TCA2EM)

All the best,
René

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/core/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
