### ISSUE TITLE
Table Column Sorting Feature Request

### ISSUE THREAD

**Issue by djmixman** [opnsense/core#3819]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[x] I have searched the existing issues and I'm convinced that mine is new.

The only issue I found similar was for one section.

**Is your feature request related to a problem? Please describe.**

I'm always frustrated when I can't sort the tables by headings because it makes it very difficult to easily find data in a large table.

**Describe the solution you'd like**

I would like to be able to click on the headings in any table and have it sort data by that heading.

**Describe alternatives you've considered**

The only alternative is that I can think of at the moment is to live with it or switch back to the competitor. :'(

**Additional context**

No other context at this time.

**Comment by djmixman** [comment]
Important notices
Before you add a new report, we ask you kindly to acknowledge the following:

[x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[x] I have searched the existing issues and I'm convinced that mine is new.

The only issue I found similar was for one section.

Is your feature request related to a problem? Please describe.

I'm always frustrated when I can't sort the tables by headings because it makes it very difficult to easily find data in a large table.

Describe the solution you'd like

I would like to be able to click on the headings in any table and have it sort data by that heading.

Describe alternatives you've considered

The only alternative is that I can think of at the moment is to live with it or switch back to the competitor. :'(

Additional context

No other context at this time.

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/core/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
