### ISSUE TITLE
Add browser version and os to crash report

### ISSUE THREAD

**Issue by jschellevis** [opnsense/core#382]
Would be very useful to have details on the browser and os version when submitting a crash report.
Certainly when an issue is related to css of javascript thing may differ from browser to browser.

**Comment by fichtner** [comment]
@fabianfrz woah, that was fast :) if you want to take issues let us know so we can assign you up front to avoid work collisions

**Comment by fichtner** [comment]
@fabianfrz Small question, are you able to close this issue? If you can, please do.

**Comment by fabianfrz** [comment]
Sadly no.
See https://help.github.com/articles/permission-levels-for-an-organization-repository/

**Comment by fichtner** [comment]
I didn't mean to close this, github autoclosed it. You are assigned, that should be enough power to close it or reopen?

**Comment by fabianfrz** [comment]
no, I can only comment on this issue

**Comment by fichtner** [comment]
Ok, bummer :(
