### ISSUE TITLE
lighttpd use port 80 on top of configured port when setted to use https 

### ISSUE THREAD

**Issue by antipiot** [opnsense/core#3820]
**Describe the bug**
I acces my opnsense using port 444 Https.

Using Haproxy to bind on 0.0.0.0:443 and 0.0.0.0:80 fail to start because port 80 is in use by lighttpd.

`root     lighttpd   31825 7  tcp4   *:80                  *:*`

if i set opnsense to use port 444 for http access, the use of the port 80 dissapear and let the port 444 alon.
if i set back to https port 444, lighttpd load back the port 80 wich deny me the use of haproxy

**To Reproduce**
1. set alternative http port on system/settings/administration tab
2. use `sockstat -4 -l | grep lighttpd` to check lighttpd only use the configured port
3. on system/settings/administration tab, now enable https and apply
4. use `sockstat -4 -l | grep lighttpd` to check that now lighttpd use the configured alternative port AND the port 80.

**Expected behavior**
Enabling Https on system/settings/administration should not start the listening on port 80

**Screenshots**
Good conf :-)
```
root     lighttpd   31825 5  tcp4   *:444                 *:*

```
Bad conf :-(
```
root     lighttpd   31825 5  tcp4   *:444                 *:*
root     lighttpd   31825 7  tcp4   *:80                  *:*
```

OPNsense 19.7.6-amd64
FreeBSD 11.2-RELEASE-p14-HBSD
OpenSSL 1.0.2t 10 Sep 2019
AMD GX-412TC SOC (4 cores)

**Comment by fichtner** [comment]
HTTP is normal if you have the redirect rule enabled.

**Comment by antipiot** [comment]
Ho!
I feel dumb now :-/

It indeed fixed this.

Many thanks!

**Comment by fichtner** [comment]
No worries. Rock on 😊
