### ISSUE TITLE
Allow strongSwan's dpdaction set to be "clear" if the connection method is set to "Start on traffic"

### ISSUE THREAD

**Issue by WRMSRwasTaken** [opnsense/core#3821]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[x] I have searched the existing issues and I'm convinced that mine is new.

**Is your feature request related to a problem? Please describe.**
It's (hopefully) not a problem.

**Describe the solution you'd like**
I am running a CARP cluster which is initiating IPsec connections to another peer.
Due to the fact that we have the database clients on our side, initiating the connection to the database server behind the peer Firewall is mandatory for us. Having the connection open constantly is not an option, because the peer closes SAs after 30 minutes of inactivity.
This is why the connection method is set to `Start on traffic` instead of `Respond only`.

Unfortunately, setting the connection method to `Start on traffic` sets strongSwan's `dpdaction` to `restart` and only setting it to `Respoond only` sets it to `clear`.

This is not much of an issue, but when the firewall does a CARP failover, the new master node initiates the connection and the old node runs into a DPD timeout, successfully clearing all SA entries. But it keeps on trying to re-establish the connection and it fails, because the own IPsec peer IP is set to the CARP virtual IP and the new master node receives the response DPD packets.

The previous node is now the standby node, thus not receiving IPsec traffic now, so it should close the IPsec tunnel istead of trying to reconnect it, until it becomes master again, receiving traffic for the IPsec tunnel. For now, I have to manually stop the tunnel on that backup node by hand in the web UI.

I can't tell (for now) if the connection from the master node is going to run into issues, if the opposite peer still receives the DPD packets from the new standby node.

**Describe alternatives you've considered**
Add an Option to configure strongSwan's `dpdaction` config option in the web UI, or set `dpdaction` to `clear` if the connection method is set to `Start on traffic`. Then it should automatically re-establish the tunnel again anyway, when the tunnel receives traffic.

Another option would be to make strongSwan's `inactivity` option configurable. Then it'd close down the tunnel after the timespan set in `inactivity` anyway, because it's the standby node.

This is somewhat related to https://github.com/opnsense/core/issues/3291

**Comment by AdSchellevis** [comment]
If the (new) backup is still sending out messages (successfully) to the other end, there's likely another issue. The carp address should be used to send out traffic, either by binding it to the address or using an outbound nat rule).

Changing the behaviour for `dpdaction` could be problematic without touching existing setups, but if there's a valid reason for doing so, we should take a look at our options (and the way we explain these options to the user).

**Comment by WRMSRwasTaken** [comment]
Yes, the local interface is set to the CARP IP. The new backup node is sending out DPD packets via the CARP IP but never receives them, but the actual master does.

Looking into the logs, it keeps on trying to reach the other peer as a backup node, until I manually stop it.

**Comment by AdSchellevis** [comment]
if I'm not mistaken @mimugmail has more of these setups active, maybe he knows if there's an omission here.

**Comment by mimugmail** [comment]
> The new backup node is sending out DPD packets via the CARP IP but never receives them, but the actual master does. This is why the backup nodes then stop all child SAs but keeps the parent SA alive.

This sounds like you have to check "Disable MOBIKE" in Phase1

**Comment by WRMSRwasTaken** [comment]
Unfortunately, disabling MOBIKE did not change this behavior. A node still tries to restart all child SAs, after it became the CARP standby node.

```
Nov 19 09:36:22 	charon: 07[NET] <con1|2> sending packet: from <ip1>[500] to <ip2>[500] (464 bytes)
Nov 19 09:36:22 	charon: 07[IKE] <con1|2> retransmit 3 of request with message ID 0
Nov 19 09:36:09 	charon: 07[NET] <con1|2> sending packet: from <ip1>[500] to <ip2>[500] (464 bytes)
Nov 19 09:36:09 	charon: 07[IKE] <con1|2> retransmit 2 of request with message ID 0
Nov 19 09:36:02 	charon: 07[NET] <con1|2> sending packet: from <ip1>[500] to <ip2>[500] (464 bytes)
Nov 19 09:36:02 	charon: 07[IKE] <con1|2> retransmit 1 of request with message ID 0
Nov 19 09:35:58 	charon: 10[NET] <con1|1> sending packet: from <ip1>[500] to <ip2>[500] (464 bytes)
Nov 19 09:35:58 	charon: 10[ENC] <con1|1> generating IKE_SA_INIT request 0 [ SA KE No N(NATD_S_IP) N(NATD_D_IP) N(FRAG_SUP) N(HASH_ALG) N(REDIR_SUP) ]
Nov 19 09:35:58 	charon: 10[IKE] <con1|1> initiating IKE_SA con1[2] to <ip2>
Nov 19 09:35:58 	charon: 10[IKE] <con1|1> restarting CHILD_SA con1
Nov 19 09:35:58 	charon: 10[IKE] <con1|1> giving up after 5 retransmits
Nov 19 09:34:42 	charon: 13[NET] <con1|1> sending packet: from <ip1>[500] to <ip2>[500] (80 bytes)
Nov 19 09:34:42 	charon: 13[IKE] <con1|1> retransmit 5 of request with message ID 15
Nov 19 09:34:00 	charon: 05[NET] <con1|1> sending packet: from <ip1>[500] to <ip2>[500] (80 bytes)
Nov 19 09:34:00 	charon: 05[IKE] <con1|1> retransmit 4 of request with message ID 15
Nov 19 09:33:37 	charon: 05[NET] <con1|1> sending packet: from <ip1>[500] to <ip2>[500] (80 bytes)
Nov 19 09:33:37 	charon: 05[IKE] <con1|1> retransmit 3 of request with message ID 15
Nov 19 09:33:24 	charon: 05[NET] <con1|1> sending packet: from <ip1>[500] to <ip2>[500] (80 bytes)
Nov 19 09:33:24 	charon: 05[IKE] <con1|1> retransmit 2 of request with message ID 15
Nov 19 09:33:17 	charon: 05[NET] <con1|1> sending packet: from <ip1>[500] to <ip2>[500] (80 bytes)
Nov 19 09:33:17 	charon: 05[IKE] <con1|1> retransmit 1 of request with message ID 15
Nov 19 09:33:12 	charon: 12[NET] <con1|1> sending packet: from <ip1>[500] to <ip2>[500] (80 bytes)
Nov 19 09:33:12 	charon: 12[ENC] <con1|1> generating INFORMATIONAL request 15 [ ]
Nov 19 09:33:12 	charon: 12[IKE] <con1|1> sending DPD request
```

Manually adding the following to a configuration file in `/usr/local/etc/ipsec.opnsense.d/`
```
conn con1
  dpdaction = clear
```
yields the results I am looking for:
```
Nov 19 09:44:25 	charon: 08[IKE] <con1|1> giving up after 5 retransmits
Nov 19 09:43:09 	charon: 16[NET] <con1|1> sending packet: from <ip1>[500] to <ip2>[500] (80 bytes)
Nov 19 09:43:09 	charon: 16[IKE] <con1|1> retransmit 5 of request with message ID 5
Nov 19 09:42:27 	charon: 16[NET] <con1|1> sending packet: from <ip1>[500] to <ip2>[500] (80 bytes)
Nov 19 09:42:27 	charon: 16[IKE] <con1|1> retransmit 4 of request with message ID 5
Nov 19 09:42:04 	charon: 05[NET] <con1|1> sending packet: from <ip1>[500] to <ip2>[500] (80 bytes)
Nov 19 09:42:04 	charon: 05[IKE] <con1|1> retransmit 3 of request with message ID 5
Nov 19 09:41:51 	charon: 05[NET] <con1|1> sending packet: from <ip1>[500] to <ip2>[500] (80 bytes)
Nov 19 09:41:51 	charon: 05[IKE] <con1|1> retransmit 2 of request with message ID 5
Nov 19 09:41:43 	charon: 05[NET] <con1|1> sending packet: from <ip1>[500] to <ip2>[500] (80 bytes)
Nov 19 09:41:43 	charon: 05[IKE] <con1|1> retransmit 1 of request with message ID 5
Nov 19 09:41:39 	charon: 05[NET] <con1|1> sending packet: from <ip1>[500] to <ip2>[500] (80 bytes)
Nov 19 09:41:39 	charon: 05[ENC] <con1|1> generating INFORMATIONAL request 5 [ ]
Nov 19 09:41:39 	charon: 05[IKE] <con1|1> sending DPD request
```

Now the tunnel is being shut down (the orange button in the overview) on the standby node, and it's automatically started again, if CARP promotes this node to master again.

**Comment by AdSchellevis** [comment]
https://github.com/opnsense/core/pull/3851
