### ISSUE TITLE
OpenVPN client export custom config text area not showing multiple lines

### ISSUE THREAD

**Issue by muchahagrande** [opnsense/core#3825]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[yes] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[yes] I have searched the existing issues and I'm convinced that mine is new.

**Describe the bug**
In OpenVPN > Client Export there is a text field to add a custom config that will be returned in 
the output file.
When I add 3 commands on 3 different lines to this field, all 3 commands are shown in one line separated with spaces, when there should be seen as 3 consecutive lines of text.

**To Reproduce**
1. Go to 'VPN > OpenVPN > Client Export'
2. Click on 'Custom config text field'
3. Write some line of text and press Enter to continue writing on the next line
4. The problem is that the new line is shown as a space so the following line is shown just next to the previous one, so all entered commands are shown on one long line

**Expected behavior**
The various entered lines of custom config should be seen one on multiple lines of text.

**Screenshots**
This is how I see 3 command:

> fragment 1250 mssfix 1250 tun-mtu 1500

This is how it should be seen:

> fragment 1250
> mssfix 1250
> tun-mtu 1500

OPNsense 19.7.6-amd64
FreeBSD 11.2-RELEASE-p14-HBSD
OpenSSL 1.0.2t 10 Sep 2019
Running on VMWare ESXi 6.7

**Comment by AdSchellevis** [comment]
I can't reproduce this on my end (using Chrome):
![image](https://user-images.githubusercontent.com/9783985/69336074-57ef9680-0c5e-11ea-9bc8-3213b926f23d.png)

The generated config file shows multiple lines as well.

Maybe a browser issue?

**Comment by muchahagrande** [comment]
You are right, I'm using Firefox. I've just tested with Chrome and it shows fine.
Exported config shows multiple lines on both browsers.
May be it can be fixed by using the same textbox attributes that are being used in Advanced Config of the OpenVPN configuration.

**Comment by AdSchellevis** [comment]
Its' not the input itself, for some reason the content seems to be cleansed in firefox.
![image](https://user-images.githubusercontent.com/9783985/69339742-575afe00-0c66-11ea-845b-1b6fdd572ee2.png)
![image](https://user-images.githubusercontent.com/9783985/69339769-6a6dce00-0c66-11ea-8399-24f815b65de5.png)

**Comment by AdSchellevis** [comment]
ok, looks like this https://bugzilla.mozilla.org/show_bug.cgi?id=1137650 should be fixed with https://github.com/opnsense/core/commit/fde54d978e82bdb1c4460715f9f1f4a5e1025a47 (`opnsense-patch fde54d9` on a console)

**Comment by muchahagrande** [comment]
@AdSchellevis ... tested and now it's ok... thank you

![imagen](https://user-images.githubusercontent.com/20299175/69349758-160f2200-0c57-11ea-93e3-4ef3005effa2.png)
