### ISSUE TITLE
IPsec settings synced to the backup node are not properly committed to the system

### ISSUE THREAD

**Issue by WRMSRwasTaken** [opnsense/core#3827]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[x] I have searched the existing issues and I'm convinced that mine is new.

**Describe the bug**
Every config change on the IPsec tunnel settings tab is not properly committed to the backup node.
Pressing `save`, `Apply changes` and under the `High availability` tab the `all` button (or even `Synchronize` and `restart` button on the `strongswan` line) does not actually write the new `/usr/local/etc/ipsec.conf` on the backup node.
To workaround this, someone just has to logon onto the backup node, and press `save` on the 
IPsec `Tunnel Settings` tab. (The `Apply changes` banner does not even appear, because the changed config has been already entered the config xml).

For example, changing the `MOBIKE` flag on the first first node does not get properly replicated, after committing the change on the first node, and syncing it to the backup node:

```
root@fw01:~ # grep mobike /usr/local/etc/ipsec.conf
  mobike = yes
```
```
root@fw02:~ # grep mobike /usr/local/etc/ipsec.conf
  mobike = no
```
After just pressing `save` on the backup node:
```
root@fw02:~ # grep mobike /usr/local/etc/ipsec.conf
  mobike = yes
```

**To Reproduce**
1. Go to 'IPsec' -> 'Tunnel Settings'
2. Create a new Phase 1 entry. This is already enough to demonstrate it in our case.
3. Save the tunnel, save all tunnel settings, apply the changes to the system
4. Sync the configuration to the backup node on the 'System' -> 'High availability' tab
5. SSH onto both machines and compare the `/usr/local/etc/ipsec.conf` file

**Expected behavior**
Without having to click `save` on the backup node, the new `/usr/local/etc/ipsec.conf` file gets written automatically after syncing the settings to the backup node.

**Screenshots**
N/A

**Relevant log files**
Nothing in the `var/log/system.log` file.

**Additional context**
N/A

**Environment**
Software version used and hardware type if relevant.
e.g.:

OPNsense 19.7.6-amd64
FreeBSD 11.2-RELEASE-p14-HBSD
OpenSSL 1.0.2t 10 Sep 2019
Intel(R) Xeon(R) Silver 4215 CPU @ 2.50GHz (32 cores)
2x Dual Port Intel x520 Cards

**Comment by AdSchellevis** [comment]
did you restart strongswan on the backup (via the master)?

**Comment by WRMSRwasTaken** [comment]
Yes, as already written, i've clicked the `all` button which does this automatically, and even only the `sync` and `restart` button on the strongswan line.

**Comment by WRMSRwasTaken** [comment]
I've reproduced this on 2 OPNsense clusters running the latest version. I might set up a fresh OPNsense cluster the next days, to see if I can reproduce this behavior on a new install.

**Comment by AdSchellevis** [comment]
no need, just reproduced it here, one moment

**Comment by AdSchellevis** [comment]
https://github.com/opnsense/core/commit/5c954133b8e8a9b4fcd6ed0b8b471b4234bf05e2 should fix it, to try, run the following on the backup: 
```
opnsense-patch 5c954133b8
service configd restart
```

And sync from the master again.

**Comment by WRMSRwasTaken** [comment]
Yes, that fixes it. After it restarted the strongSwan service, the new config file gets written to the disk. Thanks!

**Comment by AdSchellevis** [comment]
you're welcome, closing the issue. have a nice weekend.
