### ISSUE TITLE
IPv6 IPsec Tunnel (route-based), setting gateway to endpoint in tunnel is impossible

### ISSUE THREAD

**Issue by soulsymphonies** [opnsense/core#3829]
**Describe the bug**
I have an IPv6 IPsec Tunnel (route based) between Firewall 1 (HG) and Firewall 2 (VR) up and running.

If I want to create the appropriate gateway to the endpoint at the other side of the tunnel it doesn't work. Although I check "Far Gateway", as it is a point-to-point connection and the IPv6 address lies outside the actual interface's subnet, I still get the following error "The gateway address "fdd4:5942:9a1d:2550::40" does not lie within one of the chosen interface's IPv6 subnets"

**Expected behavior**
With "Far Gateway" checked the Gateway outside the IPv6 subnet of the tunnel interface should have been accepted.

**Screenshots**
[IPv6 Tunnel.pdf](https://github.com/opnsense/core/files/3887264/IPv6.Tunnel.pdf)

**Comment by fichtner** [comment]
IPv6 has no far gateway concept. You subnet size is mismatching.

**Comment by soulsymphonies** [comment]
Could you please help me, what am I getting wrong here.

I have my IPv6 subnet (fdd4:5942:9a1d:0550::/64) and both firewalls are part of it, HG has fdd4:5942:9a1d:0550::40/64 and VR has fdd4:5942:9a1d:0550::10/64 and I establish my Phase 1 of the IPv6 tunnel via these two endpoints in the same subnet.

Then I define two totally independet "virtual" IPv6 endpoints in Phase 2 of the tunnel setup, which have no subnet mask whatsoever, just two plain IPv6 addresses as I do it in IPv4 route-based tunnels, VR has fdd4:5942:9a1d:2550::10/128 and HG has fdd4:5942:9a1d:0550::40/128 as these two point-to-point virtual IPs so that I can set up a gateway.

Maybe I'm twisting things up, what would be the right way to do it in IPv6, as this is obviously not working. Maybe you could provide me a little example with some "made-up" working IPv6 subnets and IPv6 addresses for such a VTI setup, so that I can figure out, what I'm missing here.

I would be very grateful for assistance and thank you in advance,
Robert

**Comment by bewue** [comment]
> fdd4:5942:9a1d:2550::10/128 and HG has fdd4:5942:9a1d:0550::40/128 as these two point-to-point virtual IPs so that I can set up a gateway.

**2550 != 0550**
Try using IPs out of the same /64 subnet?

**Comment by soulsymphonies** [comment]
I have done that and used the same subnet. The problem however is, that it is a route-based tunnel and in the Web UI I can only provide a remote and local IPv6 address, but not add a subnet mask to it. It is just the same with an IPv4 route-based tunnel. Would be, of course, different if I used a policy based tunnel.

![route-based](https://user-images.githubusercontent.com/19210054/69646040-6deac600-1067-11ea-846f-b7e23c15b2e6.jpg)

If I log in to the ssh console on the Firewall I get the following output of IPv6 addresses, which are then /128 addresses, which are just single adresses and are obviously not belonging to a subnet

Firewall 1 HG
Tunnel VR <> FWCluster HG (ipsec3000) -> v6: fdd4:5942:9a1d:550::140/128
Firewall 2 VR
Tunnel VR <> FWCluster HG (ipsec1000) -> v6: fdd4:5942:9a1d:550::110/128

I can add fdd4:5942:9a1d:550::110 as gateway on Firewall 2 VR, but not fdd4:5942:9a1d:550::140, as it does not, and cannot even belong to the same subnet, because the interface has a /128 address, and the Web UI doesn't give me another option when I create a route based IPv6 tunnel.

So probably it is an issue with the WebUI.

**Comment by bewue** [comment]
@soulsymphonies try using IPs out of an different subnet (e.g. fd00:2000::1, fd00:2000::2) for "Tunnel network" local and remote addresses. That did work for me with an dummy IPsec tunnel config.  I was able to create an gw for the local address (fd00:2000::1).

**Comment by soulsymphonies** [comment]
Thank you for your response.

My OPNsense version  ist19.7.7

I followed your advice and used a completely different subnet.

- on firewall 1 (HG) in Phase 2 of the route-based IPv6 tunnel I set as as local IP 
fd00:2000::2 and as remote IP fd00:2000::1

![grafik](https://user-images.githubusercontent.com/19210054/69704208-45101280-10f3-11ea-9b2e-20ff70113d98.png)

![grafik](https://user-images.githubusercontent.com/19210054/69704249-55c08880-10f3-11ea-9cc3-9633bbab7bff.png)

Tunnel is up and running
![grafik](https://user-images.githubusercontent.com/19210054/69704277-6113b400-10f3-11ea-8c9c-79caff5620ec.png)

- on firewall 2 (VR) in Phase 2 of the route-based IPv6 tunnel I set as local IP fd00:2000::1 and as remote IP fd00:2000:1

![grafik](https://user-images.githubusercontent.com/19210054/69704769-69202380-10f4-11ea-85e6-eb06ada7f848.png)

![grafik](https://user-images.githubusercontent.com/19210054/69704785-750be580-10f4-11ea-80de-a0fcd5556c86.png)

Tunnel is up and running
![grafik](https://user-images.githubusercontent.com/19210054/69704800-7d642080-10f4-11ea-8518-59a49e8ac831.png)

If I now try to create the Gateway from Firewall 2 (VR) to Firewall 1 (HG) via the established IPv6 route-based tunnel, I get the same error message.

If I enter the virtual remote IP fd00:2000::1as the gateway IPv6 address - which is the endpoint IP that I defined in Phase 2 for Firewall 1 (HG) - which I obviously require to set the gateway the right way, I get the error, that the gateway does lie outside the interfaces's subnet

![grafik](https://user-images.githubusercontent.com/19210054/69704998-ed72a680-10f4-11ea-8372-a0668d8f17e1.png)

The only IPv6 address that the WebUI accepts is the virtual local IP fd00:2000::2 of the local Firewall 2 (VR) which would not give me the opportunity to route at all, as I require the "far" tunnel IPv6 of Firewall 1 (HG) which can't be set.

If I do the same thing with an IPv4 route-based tunnel and set the remote IPv4 address and I set "Far Gateway" it works as expected, so I have no way to create a route-based IPv6 tunnel, policy IPv6 tunnels however works.

It comes all down to the WebUI not accepting the correct IPv6 address of the remote firewall that was defined in Phase 2, as a valid gateway address.

So I'm stuck, the WebUI just doesn't allow me to set the correct remote IP for the gateway. I only could edit /config/config.xml via shell, which I won't do because it's not supported

I've no idea what to do now, but there has to be a way to get that running.
Thank you in advance for any further idea and assistance

**Comment by soulsymphonies** [comment]
Thank you for your assistance, I appreciate it much.
I have OPNsense version 19.7.7, I just had an error in my thinking, thanks to your help I got it running now.

**Comment by fichtner** [comment]
Great to hear, and thanks for the support. So this can be closed? 😊

**Comment by soulsymphonies** [comment]
Yes it can be closed.

And thank you for this great piece of software, I love OPNsense and I honor all the dedication, time and effort that all those who contribute put into it.
