### ISSUE TITLE
Unbound doesn't start with include /<filename>.conf args on 19.7.7 

### ISSUE THREAD

**Issue by mihaibalaci** [opnsense/core#3830]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

**Describe the bug**
After upgrading to version 19.7.7 Unboand service refuses to start by using this as arguments in the Custome Options
include:/var/unbound/ad-blacklist.conf
server:
      forward-zone:
       name: "."
       forward-ssl-upstream: yes
       forward-addr: 1.1.1.1@853
       forward-addr: 9.9.9.9@853

If I comment the include line works perfectly. 

**To Reproduce**
1. Go to Services -> Unbound -> General -> Custome Options
2. See error - service not loading and there is no log record on log-level 5

**Expected behavior**
Service to start

**Screenshots**
<img width="1368" alt="image" src="https://user-images.githubusercontent.com/9979225/69627126-b64bb900-1052-11ea-8e50-8b9b45ed1d75.png">

**Relevant log files**
I only get this:

Nov 26 13:32:38 | unbound: [15614:1] info: generate keytag query _ta-4f66. NULL IN
-- | --
Nov 26 13:32:38 | unbound: [15614:2] info: generate keytag query _ta-4f66. NULL IN
Nov 26 13:32:38 | unbound: [15614:4] info: generate keytag query _ta-4f66. NULL IN
Nov 26 13:32:38 | unbound: [15614:0] info: start of service (unbound 1.9.4).
Nov 26 13:32:37 | unbound: [15614:0] notice: init module 1: iterator
Nov 26 13:32:37 | unbound: [15614:0] notice: init module 0: validator

**Additional context**
No

**Environment**
OPNsense 19.7.7-amd64
FreeBSD 11.2-RELEASE-p16-HBSD
OpenSSL 1.0.2t 10 Sep 2019

**Comment by fichtner** [comment]
Hi, as this is a core ticket and “ad-blacklist” turns up empty you should ask the provider of the file for support, not the core team. If ad-blacklist is a custom file we will close this issue. Thanks for your understanding.
