### ISSUE TITLE
Change defaults for SSH Listen Interfaces

### ISSUE THREAD

**Issue by RubenMeneses** [opnsense/core#3833]
A defaults value suggestion purely from the point of view of security
for the SSH settings under
System-->Settings-->Listen Interfaces

Currently
(All recommended)

Suggestion
(LAN)
Cheers.

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/core/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
