### ISSUE TITLE
Saving DHCPv6 settings deletes advanced RA options

### ISSUE THREAD

**Issue by maurice-w** [opnsense/core#3834]
[X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[X] I have searched the existing issues and I'm convinced that mine is new.

**Describe the bug**
When saving the DHCPv6 settings, the advanced Router Advertisement options for that interface get deleted from the config.

**To Reproduce**
1. Go to 'Services: Router Advertisements: [LAN]'
2. Click on 'Show advanced options', enter some values and click 'Save'. Works as expected.
3. Go to 'Services: DHCPv6: [LAN]' and click 'Save' (you don't have to actually change anything).
4. Go back to 'Services: Router Advertisements: [LAN]'. You can see that the previously entered advanced options are gone.

**Expected behavior**
This should obviously not happen. :-)

**Environment**
OPNsense 19.7.7 (amd64, OpenSSL)

**Comment by AdSchellevis** [comment]
@maurice-w https://github.com/opnsense/core/commit/fd979aa2c29d252beffb27b51e03ba2bd16df9b2 should fix it. both pages unfortunately are using the same config section, which can cause annoying races.

**Comment by maurice-w** [comment]
Thanks for the instant fix! Applied the patch and it seems to work.

(It might be a good idea to separate the DHCPv6 and RA configs in the long run. The shared config has other unwanted side effects. For example, saving the DHCPv6 config triggers a restart of radvd, which causes interruption in _all_ LANs.)
