### ISSUE TITLE
Multiple vpn user from a lan to my opnsense server

### ISSUE THREAD

**Issue by gmisterk** [opnsense/core#3841]
Hi everybody,

I have a lan with 4 computers in siteA
and in siteB, i have a opnsense serveur with VPN.

It work fine but only for one computer (client vpn)
If someone is siteA is connected to siteB, other client can't connect to vpn server.

Any suggestion to permet all computer in siteA lan to access siteB in same time ?

Thank you for  your help

OPNsense 16.7.14

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/core/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
