### ISSUE TITLE
OpenVPN / WARNING ifconfig is present in remote config

### ISSUE THREAD

**Issue by superwinni2** [opnsense/core#3842]
**Describe the bug**
I have 2 OPNsense on different locations connected via OpenVPN.
Config is very standard, nothing special.
I get the error on remote machine 
`openvpn[94930]: WARNING: 'ifconfig' is present in remote config but missing in local config, remote='ifconfig 172.16.104.2 172.16.104.1'`

*Local FW config File:*
```
dev ovpns3
verb 1
dev-type tun
dev-node /dev/tun3
writepid /var/run/openvpn_server3.pid
script-security 3
daemon
keepalive 10 60
ping-timer-rem
persist-tun
persist-key
proto udp
cipher AES-256-CBC
auth SHA512
up /usr/local/etc/inc/plugins.inc.d/openvpn/ovpn-linkup
down /usr/local/etc/inc/plugins.inc.d/openvpn/ovpn-linkdown
local 1.2.3.4
tls-server
ifconfig 172.16.104.1 172.16.104.2
tls-verify "/usr/local/etc/inc/plugins.inc.d/openvpn/ovpn_auth_verify tls 'OPNsenseVPNServer' 1"
lport 7217
management /var/etc/openvpn/server3.sock unix
push "route 10.10.100.0 255.255.255.0"
push "route 10.10.50.0 255.255.254.0"
push "route 172.20.1.0 255.255.255.0"
route 10.10.104.0 255.255.255.0
ca /var/etc/openvpn/server3.ca
cert /var/etc/openvpn/server3.cert
key /var/etc/openvpn/server3.key
dh /usr/local/etc/dh-parameters.4096.sample
crl-verify /var/etc/openvpn/server3.crl-verify
tls-auth /var/etc/openvpn/server3.tls-auth 0
comp-lzo adaptive
persist-remote-ip
float
```

*Remote (Client) VPN Config File:*
```
dev ovpnc1
verb 1
dev-type tun
dev-node /dev/tun1
writepid /var/run/openvpn_client1.pid
script-security 3
daemon
keepalive 10 60
ping-timer-rem
persist-tun
persist-key
proto udp
cipher AES-256-CBC
auth SHA512
up /usr/local/etc/inc/plugins.inc.d/openvpn/ovpn-linkup
down /usr/local/etc/inc/plugins.inc.d/openvpn/ovpn-linkdown
tls-client
client
nobind
management /var/etc/openvpn/client1.sock unix
remote vpn.domain.net 7217
ifconfig 172.16.104.2 172.16.104.1
route 0.0.0.0 128.0.0.0
route 172.20.20.10 255.255.255.255
ca /var/etc/openvpn/client1.ca
cert /var/etc/openvpn/client1.cert
key /var/etc/openvpn/client1.key
tls-auth /var/etc/openvpn/client1.tls-auth 1
comp-lzo adaptive
resolv-retry infinite
```

**To Reproduce**
I would say configure a VPN Server with same configs...

**Expected behavior**
No Error 

**log files**
Look on Top.

**Additional context**
I've updated the OPNsense since ~18.1

**Environment**
Server:
OPNsense 19.7.7-amd64
FreeBSD 11.2-RELEASE-p16-HBSD
OpenSSL 1.0.2t 10 Sep 2019
Intel(R) Xeon(R) E-2136 CPU @ 3.30GHz (12 cores)

Client:
OPNsense 19.7.6-i386
FreeBSD 11.2-RELEASE-p14-HBSD
OpenSSL 1.0.2t 10 Sep 2019
Intel(R) Celeron(R) M processor 1.50GHz (1 cores)

**Comment by Shesoff** [comment]
I have same WARNING

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/core/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
