### ISSUE TITLE
firewall schedules has incorrect character encoding (utf-8)

### ISSUE THREAD

**Issue by ikke-t** [opnsense/core#3843]
**Describe the bug**

There is lots of garbage text in descriptions of firewall schedules pages "Firewall: Settings: Schedules". This is due that once you write UTF-8 characters like öä, they get incorrectly stored as non utf-8, and therefore always looks awful.

This text: "arkiaamuja edeltävä ilta"
becomes: "arkiaamua%252520edelt%2525E4v%2525E4%252520ilta"

This is both on the overview page, as well as on the list of rules while you edit the rule, and it originally was filled into field "Time Range Description" while in edit mode.

**To Reproduce**

1. Go to Firewall: Settings: Schedules
2. Click on 'Add' or edit an existing one.
3. Select what ever, and put this into the "Time Range Description" field: "päivä ja yö"
4. Add rule and save.

**Expected behavior**

All descriptions should look like "päivä ja yö" (day and night in Finnish)

**Screenshots**

![Screenshot from 2019-12-09 19-19-45](https://user-images.githubusercontent.com/1146409/70458501-d9e31a80-1aba-11ea-963a-0ae8f3969274.png)
![Screenshot from 2019-12-09 19-20-01](https://user-images.githubusercontent.com/1146409/70458502-d9e31a80-1aba-11ea-8a93-b37ee3e47c3f.png)

**Relevant log files**

**Additional context**

**Environment**

Firefox
OPNsense 19.7.7-amd64

**Comment by AdSchellevis** [comment]
I don't think there's an easy fix here, this xss fix caused it https://github.com/opnsense/core/commit/80d94767a7f6dbb278ab1abfdba2ccc3c839a4fb. the code for the schedule pages is quite old and not too great unfortunately.

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/core/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
