### ISSUE TITLE
Firewall/Diagnostics/pfTables truncates last alias entry in list

### ISSUE THREAD

**Issue by ddimick** [opnsense/core#3848]
When looking at an alias in Firewall/Diagnostics/pfTables, the last entry row is not shown. For example, an alias with three entries will only show two rows even though it says "Showing 1 to 3 of 3 entries". Looking at the first 20 entries on a larger alias, only 19 are shown. If an alias only contains one entry, nothing at all is shown. Bug affects host and network alias types, have not tested with other types.

**To Reproduce**
1. Create a host or network alias with at least one entry.
2. Examine the table in the diagnostics section.
3. Note how many entries is says it is showing versus how many it is actually showing.

**Expected behavior**
All alias entries should be visible.

**Screenshots**
http://prntscr.com/qc9day
http://prntscr.com/qc9dyk

**Environment**
OPNsense 19.7.7-amd64
FreeBSD 11.2-RELEASE-p16-HBSD
OpenSSL 1.0.2t 10 Sep 2019
Chromium: 79.0.3945.79 (Official Build) (64-bit)

**Comment by marjohn56** [comment]
Just checked against my live system which is running 20.1.a_229 , looks OK. Perhaps it's fixed in 20.1

![Alias_edit](https://user-images.githubusercontent.com/17962918/71040465-8c9c2400-211e-11ea-9f01-cd84e3cb5ba5.PNG)
![pfTable](https://user-images.githubusercontent.com/17962918/71040466-8c9c2400-211e-11ea-9f52-a5a6f567bc74.PNG)

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/core/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
