### ISSUE TITLE
OpenVPN policy routing gateway address misinterpretation issue

### ISSUE THREAD

**Issue by hippi-viking** [opnsense/core#3849]
Hello,

There might be a parameter misinterpretation issue in either the System/Gateway parsing script (or the OpenVPN client) - I could not pinpoint the bug in the source code yet but probably the former.

The issue is the following:
- OpenVPN client set up with `Don't pull routes` ticked -> to enable policy routing
- under System/Gateway/Single/OpenVPN interface if `IP address` is set to `dynamic` the gateway address is filled in with the IP of the _local tunnel client_ instead of the _upstream tunnel server_ -> this creates a loop on the local end of tunnel not letting traffic go upstream

I suspect the OpenVPN server DHCP response is misinterpreted in the System/Gateway definition script. The tunnel builds up as per:

`Dec 18 16:41:43 	openvpn[69755]: /usr/local/etc/inc/plugins.inc.d/openvpn/ovpn-linkup ovpnc1 1500 1585 10.8.1.30 255.255.255.0 init`
`Dec 18 16:41:43 	openvpn[69755]: /sbin/ifconfig ovpnc1 10.8.1.30 10.8.1.1 mtu 1500 netmask 255.255.255.0 up`

But for the gateway 10.8.1.30 is taken as the gateway IP address by the responsible script whereas it is the address of the local client, 10.8.1.1 being the upstream gateway in this example

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/core/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
