### ISSUE TITLE
Error creating Portaliases

### ISSUE THREAD

**Issue by hsiewert** [opnsense/core#3850]

**Comment by AdSchellevis** [comment]
`1005:1008` https://docs.opnsense.org/manual/aliases.html?highlight=range

**Comment by hsiewert** [comment]
rtfm ... I'm sorry ;-(

**Comment by fichtner** [comment]
@hsiewert no worries, but would you mind keeping the original description intact for others who will find this issue later on? an answer without a question is not as effective. thanks! :)
