### ISSUE TITLE
Update Netdata service

### ISSUE THREAD

**Issue by wsurvive** [opnsense/core#3853]
Hi there,

I was wondering if you could update the version of Netdata that's included in OPNSense?

It ships with 1.17, ports has 1.19. 

Of particular interest is Unbound monitoring is redone in 1.19.

Thank you!@

**Comment by fichtner** [comment]
This request is incomplete since you did not use our template or at least provide a version reference of OPNsense. The more relevant issue, however, is that 19.7.8 has the version you want and that is out since Thursday. 😉

**Comment by wsurvive** [comment]
Hi Franco,

Right you are. I had to "F5" the tab to see the new version.

Where do I find the correct template? Or where is the right place to open a
ticket? I didn't find anything & saw the tracker here & went for it.

I ask because I have a feature I'd love to have on OPNsense. I use ULA
addresses  (like RFC 1918 addresses) internally. I statically assign
addresses & have manual control over internal naming\DNS. Works a treat.

Save for one thing. I can't assign a ULA address to my router so I can't
use DHCPv6, I can't really use DHCPv6 at all because I don't have a static
IPv6 address to give it. Charter seems to be pretty "sticky" with their
DHCP assignments, IPv6 seems to be much more fluid.

Tell me where to file this and I'll do it. Or tell me I'm an idiot and that
this won't work. If it was possible it would be awesome !

Thank you!

-Will
