### ISSUE TITLE
OpenVPN - Client Specific Overrides - Tunnel Network

### ISSUE THREAD

**Issue by AndyX90** [opnsense/core#3854]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[x] I have searched the existing issues and I'm convinced that mine is new.

**Describe the bug**
If i have set up a OpenVPN Server, e.g. on Port 1194 UDP, define a tunnel network(e.g. 10.1.1.0/24) and specify a separate tunnel network(e.g. 10.1.2.0/24) for specific clients via client specific override, the clients matching this override always get the same ip-addresses (e.g. 10.1.2.4) and therefore kill the other ones connectivity.

**To Reproduce**
1. Go to 'VPN' -> 'OpenVPN' -> 'Client Specific Override'
2. Click on '(+) Add'
3. Fill in the matching information
4. Scroll down to 'IPv4 Tunnel Network'
5. Insert a different tunnel network then the server's tunnel network
6. Create a second override for a second client with the same tunnel network
7. See the connected clients ip-addresses

**Expected behavior**
The clients connected should get different IP adresses from the overridden pool.

**Screenshots**
none

**Relevant log files**
none

**Additional context**
none

**Environment**
OPNsense 19.7.7 (amd64, OpenSSL).
Intel® Xeon™ E3-1225V5 3.3Ghz Quad Core
Network Intel® I210-AT

**Comment by mimugmail** [comment]
I always thougt the override address has to be in the tunnel network of the server instance or otherwise create a second one?

**Comment by AdSchellevis** [comment]
if I remember correctly, an overwrite is an address, not a pool.

**Comment by AndyX90** [comment]
If that is the case, the 'Client Specific Overrides' GUI is not clear enough. It should not be possible to set a 'Tunnel Network' rather an 'IP-Address'.
But if i understand [that](https://openvpn.net/community-resources/configuring-client-specific-rules-and-access-policies/) correctly, it would be possible to support multiple ip-ranges on a single openvpn server.

**Comment by thejacko12354** [comment]
Hi There,
I got basicly the same problem but I can say if I'm creating a 'Client Specific Override'. The file just doesn't get created, '/var/etc/openvpn-csc/1/' is always empty.
If I create the file by hand and set a ifconfig-push in it, it just works as expected.

OPNsense 20.1.3-amd64
FreeBSD 11.2-RELEASE-p17-HBSD
OpenSSL 1.1.1d 10 Sep 2019

**Comment by Mad-Onion** [comment]
Same problem here with the current release: I migrated from old to new hardware, the other site's appliance connected without problems, but the internal routes where missing.

I found out that the folder /var/etc/openvpn-csc/1 of server 1 stays empty, even if I create a new client-override. GUI shows 5 activated CSCs, but none of them is generated into the filesystem.

OPNsense 20.1.5-amd64
FreeBSD 11.2-RELEASE-p18-HBSD
OpenSSL 1.1.1f 31 Mar 2020

**Comment by AdSchellevis** [comment]
`openvpn_csc_conf_write()` is responsible for writing the files within the  authentication sequence, dynamic types can collect data while connecting. The logs show usually provide quite some insights into this process. 

https://github.com/opnsense/core/blob/8b5a54e0307f11655d99ddf5254ff5769b5fa6ba/src/etc/inc/plugins.inc.d/openvpn.inc#L1023

**Comment by Mad-Onion** [comment]
@AdSchellevis I use the local database as auth-backend with enforcement of a local group containing the allowed VPN's users.

When I look into the logfiles I see:
> openvpn: user 'VPN_XYZ' authenticated using 'Local Database'

"VPN_XYZ" is ok as my usernames for the VPN start with "VPN_". But looking into https://github.com/opnsense/core/blob/8b5a54e0307f11655d99ddf5254ff5769b5fa6ba/src/etc/inc/plugins.inc.d/openvpn/auth-user.php#L146 I see that this logentry will be generated if `$cso_filename` is empty, which contains the result of https://github.com/opnsense/core/blob/8b5a54e0307f11655d99ddf5254ff5769b5fa6ba/src/etc/inc/plugins.inc.d/openvpn.inc#L1023 which in turn is only empty if its `$conf` is empty - and that shouldn't be the case as there are settings configured in the GUI.

May you take a look or tell me how to search further?

**Comment by AdSchellevis** [comment]
@Mad-Onion a couple of things I can think of:

Mismatch in the common_name (I think that's the most common one)
https://github.com/opnsense/core/blob/8b5a54e0307f11655d99ddf5254ff5769b5fa6ba/src/etc/inc/plugins.inc.d/openvpn/auth-user.php#L131-L133

Missing vpnid (not bound to a server), this might be a bug. Easy to test by choosing the one server in the csc.

https://github.com/opnsense/core/blob/8b5a54e0307f11655d99ddf5254ff5769b5fa6ba/src/etc/inc/plugins.inc.d/openvpn.inc#L1025

**Comment by Mad-Onion** [comment]
@AdSchellevis I added a log-statement returning the CN and the VPN-ID the openvpn_csc_conf_write-method receives:
```
function openvpn_csc_conf_write($settings, $server, $target_filename = null)
{
    log_error(sprintf('Building CSC for CN \'%s\' and VPN-ID \'%s\'', $settings['common_name'], $server['vpnid']));
    log_error(print_r($settings, true));

    if (empty($settings['common_name']) || empty($server['vpnid'])) {
        return false;
    }
```

This is the output (newest entry on top)
```
2020-04-29T10:21:34	openvpn: user 'VPN_XYZ' authenticated using 'Local Database'
2020-04-29T10:21:34	openvpn: /usr/local/etc/inc/plugins.inc.d/openvpn/auth-user.php: Array ( [common_name] => )
2020-04-29T10:21:34	openvpn: /usr/local/etc/inc/plugins.inc.d/openvpn/auth-user.php: Building CSC for CN '' and VPN-ID '1'
```
So there seems to be a problem so that the method is called without any CN at all...

**Comment by AdSchellevis** [comment]
@Mad-Onion looks like either the client isn't using a cert and `Force CSO Login Matching` is disabled or `Force CSO Login Matching` is enabled and it isn't using a username+password combination

**Comment by Mad-Onion** [comment]
Fu*k... `Force CSO Login Matching` wasn't checked...
Thanks a lot @AdSchellevis

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/core/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
