### ISSUE TITLE
Can't login in captive portal

### ISSUE THREAD

**Issue by RomanJos** [opnsense/core#3855]
Hi I can no longer authenticate using captive portal. At first it was AUTH but no internet and no sessions for the allowed ip addresses, and this #3612 fixed it in half (I deleted /conf/captiveportal.sqlite and /var/captiveportal/captiveportal.sqlite) and completly rebooted.
Now I have DENY for everything no matter what I do. 
I also created another voucher 'server' and generated one voucher but I got DENY and no session. the things is that even with deny the voucher change its state to 'valid'.
Do you have any idea ?

**Comment by RomanJos** [comment]
I tried to study your codes and got trapped by trying to log in a file instead of syslog in AuthenticationFactory.php. I can no longer connect into it with either ssh or direct console or even with another tty with the console. do you have any idea again ?

**Comment by RomanJos** [comment]
Lol by chance I was still logged in the web gui so I reinstalled the opnsense package and now it work but I still have my login issue :(

**Comment by RomanJos** [comment]
OMG why enforce local group is set to admin by default ? Everything work now.

**Comment by Hibbelharry** [comment]
> OMG why enforce local group is set to admin by default ? Everything work now.

What did you do to get rid of that problem? We're seemingly running into the same issue.

**Comment by RomanJos** [comment]
Hi I just saw your issue, I don't have any error if i set it to none everything work fine now

**Comment by fichtner** [comment]
this might be of relevance: https://github.com/opnsense/core/issues/3891
