### ISSUE TITLE
Dynamic DNS Plugin - OpenDNS Missing since 19.7.7

### ISSUE THREAD

**Issue by DanMc85** [opnsense/core#3857]
OpenDNS option is missing from the Dynamic DNS since 19.7.7.

It made existing entries error out and it is no longer in the drop down list to re-select.

Can this code be put back into Dynamic DNS?

It allowed for OpenDNS's paid IP filtering DNS service to always work if a Dynamic Public IP changed on the OPNsense Fireewall.

https://support.opendns.com/hc/en-us/articles/227987767-Using-Dynamic-DNS-with-OpenDNS

**Comment by fichtner** [comment]
Ok, shouldn't be hard to find a solution :)
