### ISSUE TITLE
IPsec IKEv2: No private key found

### ISSUE THREAD

**Issue by hockey6611** [opnsense/core#3859]
I have configured an IPsec VPN and it appears that strongswan is not configured to used the private key of my lets encrypt certificate. I receive the following error in the GUI log: "no private key found". and when the `ipsec listcerts` command is run in the terminal the private key appears to be missing. ([Resource](https://lists.strongswan.org/pipermail/users/2010-June/000378.html))

![log](https://user-images.githubusercontent.com/28613898/71539025-ad752e00-2903-11ea-8574-988b5d91f48c.JPG)
![putty](https://user-images.githubusercontent.com/28613898/71539026-ad752e00-2903-11ea-86c4-a45448e5257d.JPG)

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/core/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
