### ISSUE TITLE
config: new components do not rewrite revision section

### ISSUE THREAD

**Issue by fichtner** [opnsense/core#386]
make_config_revision_entry() should be used here as well with the appropriate information to make the config audit log viable again. See screenshot:

<img width="1032" alt="screen shot 2015-09-16 at 14 49 55" src="https://cloud.githubusercontent.com/assets/1915288/9904987/41f452f2-5c82-11e5-8990-13576b2a17e0.png">

**Comment by AdSchellevis** [comment]
fixed with https://github.com/opnsense/core/commit/11913af853eb83da7dc60f3963f7f1ba045b01c5
