### ISSUE TITLE
No way to prevent OPNSense from performing relative DNS lookup for Host aliases

### ISSUE THREAD

**Issue by paul-palmer** [opnsense/core#3861]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[y] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[y] I have searched the existing issues and I'm convinced that mine is new.

**Is your feature request related to a problem? Please describe.**

We are running OPNsense 19.7.8-amd64.

We have recently started paying very close attention to the DNS queries on our network and we have discovered that our Host alias entries are triggering surprising DNS queries. For example, if we have a Host Alias for foo.bar.com, when the firewall attempts to resolve the alias, it will perform a DNS lookup for foo.bar.com.our.tld.com. That is, it always seems to attempt to lookup a Host Alias as a relative name (applying the firewall's domain) even when it clearly ends in a TLD. This in itself is arguably a bug. However, it would seem that the problem could be avoided if we could explicitly enter absolute DNS names such as "foo.bar.com." (trailing period intentional). However, the GUI's validity checks reject any attempts to enter a name that ends in a period.

**Describe the solution you'd like**

I would like the GUI to allow us to enter absolute DNS names.

**Describe alternatives you've considered**

Alternatively, correct current behavior where the firewall attempts to resolve DNS names that end in a TLD as if they were relative names. I believe a case can be made for both changes.

**Additional context**

**Comment by fichtner** [comment]
I'm marking this "incomplete" because we have no information about where the host overrides come from: Unbound or Dnsmasq, and which DNS settings are used under System: Settings: General.

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/core/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
