### ISSUE TITLE
Widget / System >> dead link

### ISSUE THREAD

**Issue by opnsenseuser** [opnsense/core#3862]
click on link in system widget ends up in "page not found"

![grafik](https://user-images.githubusercontent.com/34602360/71555085-f3c3ad80-2a27-11ea-8c2a-8b53e68daf67.png)

![grafik](https://user-images.githubusercontent.com/34602360/71555065-b101d580-2a27-11ea-9bf8-49fc30179a9e.png)

**Comment by fichtner** [comment]
I can't stress the point made in https://github.com/opnsense/core/blob/master/CONTRIBUTING.md#issue-reports which would make this a lot faster to fix given the necessary reference and context:

* The current OPNsense version where the bug first appeared
* The last OPNsense version where the bug did not exist
* The exact URL of the GUI page involved (if any)
* A list of steps to replicate the bug

**Comment by fichtner** [comment]
I can't stress the point made in https://github.com/opnsense/core/blob/master/CONTRIBUTING.md#issue-reports enough which would make this a lot faster to fix given the necessary reference and context:

* The current OPNsense version where the bug first appeared
* The last OPNsense version where the bug did not exist
* The exact URL of the GUI page involved (if any)
* A list of steps to replicate the bug
