### ISSUE TITLE
Excessive logging for plugins_run() specifically dpinger_status

### ISSUE THREAD

**Issue by marjohn56** [opnsense/core#3863]
My system logs are full of this:

![image](https://user-images.githubusercontent.com/17962918/71555703-f40f7900-2a26-11ea-82c8-ab9f85978420.png)

I've disabled it on my system by commenting out the relevant syslog() calls in plugins_run() in the plugins.inc file. This might be a developer thing but we could do with some sort of verbose or info setting option for logging. Just a thought....

**Comment by AdSchellevis** [comment]
I'll take a look, for 95% of the calls, you really want to know it's actually doing something, but gateway status is excessive indeed (maybe some others too).

**Comment by AdSchellevis** [comment]
I think the issue only exists in `plugins_run`, which at the moment is only used for gateway status. I moved the log level to debug in https://github.com/opnsense/core/commit/b94a5ce129fb9e8572e9ac9bd15648b34fe4ef9e, which should be enough. other plugins are called less excessive and the data is more relevant when tracking issues.

**Comment by marjohn56** [comment]
Maybe.. but I cannot see any others..

That function already has a $verbose argument, although it's not used. Perhaps a config option 'Verbose Logging' and pick  that up in the call or in the function. Could be used elsewhere too. I can add that if you like,.

**Comment by AdSchellevis** [comment]
the verbose is for console output, logging should just obey levels. in most cases you really want to know which parts are executed when an event is triggered (for example when someone pulls the plug of an interface, multiple parts are executed). if there are other calls which flood the log, just let me know, we might want to move some more levels up, although we likely also want some option to flush debug to some log as well in that case.
