### ISSUE TITLE
OpenVPN Client Exporter doesn't check for expired cert

### ISSUE THREAD

**Issue by RamXX** [opnsense/core#3864]
I noticed an expired cert message in my Viscosity logs that prevented the link to establish. The exporter should verify the cert is still valid before generating the bundle.

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/core/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
