### ISSUE TITLE
Widget - RSS Feeds - save settings problem

### ISSUE THREAD

**Issue by opnsenseuser** [opnsense/core#3867]
The settings cannot be saved. If you click on save, the RSS feeds appear in a new page without formatting. Nothing else happens. I have attached a screenshot. This problem has been around for ages.

![](https://user-images.githubusercontent.com/34602360/71473610-f4660500-27d7-11ea-9da6-2b95033beee2.png)

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/core/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.

**Comment by beltet** [comment]
Hi!
I have the same problem.
I was fiddeling with the edit option on the RSS widget. And just typed TEST in the box.

Afterwards the RSS feed broke and when trying to edit it back to a blank page, the widget goes to a new window, without any data.

![Screenshot from 2021-09-16 16-30-47](https://user-images.githubusercontent.com/25572550/133631162-1eae6934-82da-438a-9b35-b446a7d685ed.png)

![Screenshot from 2021-09-16 16-31-06](https://user-images.githubusercontent.com/25572550/133631185-e8be1a7f-f753-4108-b85f-63f48a95e16c.png)

![Screenshot from 2021-09-16 16-31-40](https://user-images.githubusercontent.com/25572550/133631197-c2552bf0-4805-415d-9269-6dc00bda4df4.png)

**Comment by fichtner** [comment]
First of all what version are you using and secondly there was a fix in 21.7.2 actually…

**Comment by beltet** [comment]
> First of all what version are you using and secondly there was a fix in 21.7.2 actually…

Ok. I did have a older version. I usually update frequently. But I realized now that I have stumbled into a bug, and was still on 21.1.9.
Updated just now, and I can confirm, the bug is not present any more. Thanks you for the heads up!
