### ISSUE TITLE
Enabling Suricata IPS causes intermittent freezes

### ISSUE THREAD

**Issue by abraha2d** [opnsense/core#3868]
I recently started using OPNsense as a VM (configuration below). I configured Suricata IDS, and it seems to be working properly. However, after enabling IPS mode, the VM freezes intermittently. If I disable IPS, the freezes stop. The freezes last anywhere from below 10 seconds to almost 60 seconds, and the time between freezes ranges from a few minutes to multiple hours.

During these freezes, OPNsense is completely unresponsive (can't SSH in, existing SSH sessions freeze, does not respond to pings, etc). Internet access is also lost. Nothing is logged in `dmesg` or in the suricata logs that could indicate what the cause of the freeze is. If i run `top`/`htop` in an SSH connection, as soon as it unfreezes, I don't see any indication of high CPU load or anything

I read that Suricata IPS has issues when used with NICs of type `virtio`, so I tried switching the type to `e1000`. Unfortunately, that did not solve the issue either.

**Expected behavior**
OPNsense should not freeze intermittently when enabling Suricata IPS.

**Environment**
OPNsense 19.7.8 (amd64, OpenSSL 1.0.2t)
VM host: Proxmox VE 6.1-5
VM configuration:
- Memory: 8GB (no balooning)
- Processors: 4 cores when using `virtio` interfaces, 8 cores when using `e1000` interfaces`
- Machine type: SeaBIOS, i440fx
- LAN interface: tried both `virtio` and `e1000`
- WAN interface: tried both `virtio` and `e1000`

**Relevant stuff**
`top` and `htop` right after unfreeze (using `virtio` interfaces):
[Screenshot_20191231_141207](https://user-images.githubusercontent.com/5976139/71647254-03f6b980-2cc2-11ea-8251-239b85e1a8aa.png)

Excerpt of ping trace during a freeze (using `e1000` interfaces, 192.168.97.1 is the LAN IP of the OPNsense VM):
```
64 bytes from 192.168.97.1: icmp_seq=1433 ttl=64 time=1.32 ms
64 bytes from 192.168.97.1: icmp_seq=1434 ttl=64 time=1.26 ms
64 bytes from 192.168.97.1: icmp_seq=1435 ttl=64 time=1.21 ms
64 bytes from 192.168.97.1: icmp_seq=1436 ttl=64 time=1.54 ms
64 bytes from 192.168.97.1: icmp_seq=1437 ttl=64 time=1.27 ms
64 bytes from 192.168.97.1: icmp_seq=1438 ttl=64 time=1.21 ms
64 bytes from 192.168.97.1: icmp_seq=1439 ttl=64 time=1.30 ms
64 bytes from 192.168.97.1: icmp_seq=1440 ttl=64 time=1.29 ms
64 bytes from 192.168.97.1: icmp_seq=1441 ttl=64 time=1.30 ms
64 bytes from 192.168.97.1: icmp_seq=1442 ttl=64 time=1.20 ms
64 bytes from 192.168.97.1: icmp_seq=1443 ttl=64 time=22019 ms
64 bytes from 192.168.97.1: icmp_seq=1444 ttl=64 time=20993 ms
64 bytes from 192.168.97.1: icmp_seq=1445 ttl=64 time=19968 ms
64 bytes from 192.168.97.1: icmp_seq=1446 ttl=64 time=18944 ms
64 bytes from 192.168.97.1: icmp_seq=1447 ttl=64 time=17920 ms
64 bytes from 192.168.97.1: icmp_seq=1448 ttl=64 time=16896 ms
64 bytes from 192.168.97.1: icmp_seq=1449 ttl=64 time=15873 ms
64 bytes from 192.168.97.1: icmp_seq=1450 ttl=64 time=14848 ms
64 bytes from 192.168.97.1: icmp_seq=1451 ttl=64 time=13825 ms
64 bytes from 192.168.97.1: icmp_seq=1452 ttl=64 time=12800 ms
64 bytes from 192.168.97.1: icmp_seq=1453 ttl=64 time=11776 ms
64 bytes from 192.168.97.1: icmp_seq=1454 ttl=64 time=10753 ms
64 bytes from 192.168.97.1: icmp_seq=1455 ttl=64 time=9729 ms
64 bytes from 192.168.97.1: icmp_seq=1456 ttl=64 time=8706 ms
64 bytes from 192.168.97.1: icmp_seq=1457 ttl=64 time=7683 ms
64 bytes from 192.168.97.1: icmp_seq=1458 ttl=64 time=6659 ms
64 bytes from 192.168.97.1: icmp_seq=1459 ttl=64 time=5635 ms
64 bytes from 192.168.97.1: icmp_seq=1460 ttl=64 time=4611 ms
64 bytes from 192.168.97.1: icmp_seq=1461 ttl=64 time=3587 ms
64 bytes from 192.168.97.1: icmp_seq=1462 ttl=64 time=2563 ms
64 bytes from 192.168.97.1: icmp_seq=1463 ttl=64 time=1539 ms
64 bytes from 192.168.97.1: icmp_seq=1464 ttl=64 time=516 ms
64 bytes from 192.168.97.1: icmp_seq=1465 ttl=64 time=1.06 ms
64 bytes from 192.168.97.1: icmp_seq=1466 ttl=64 time=1.48 ms
64 bytes from 192.168.97.1: icmp_seq=1467 ttl=64 time=1.37 ms
64 bytes from 192.168.97.1: icmp_seq=1468 ttl=64 time=1.45 ms
64 bytes from 192.168.97.1: icmp_seq=1469 ttl=64 time=1.24 ms
```

Whole ping trace (ran it overnight):
[ping.log](https://github.com/opnsense/core/files/4014631/ping.log)

Graph of the above ping trace (time vs. icmp_seq), with freezes highlighted:
![Screenshot_20200101_203007](https://user-images.githubusercontent.com/5976139/71648701-a704fe80-2cd5-11ea-9656-f92fdf42f79e.png)

**Comment by DumboJet** [comment]
I have the same problem on a VirtualBox VM.
I am testing OpnSense.

When using the "ET telemetry" rules and IDS is enabled, all seems OK.
Once I enable IPS, I lose the connection to the web interface and the OS screen in VirtualBox seems almost unresponsive. E.g. I type my username and hit ENTER to login, and nothing happens.
I send the "ACPI shutdown" signal to the VM and nothing happens.
Only on some rare occasions, the "ACPI shutdown" signal works and shuts down the VM. Most of the times, nothing happens.

I am monitoring the WAN interface only.

Also, another thing I noticed, is that when I reboot the VM, I have a few seconds to login into the web interface and change the settings. After that time has passed, I lose control again, unless I disable the IPS and restart.

I tried giving it more RAM (2GB total) but I got kicked out again, after IPS was enabled.
Before it kicks me out, the CPU was at 100%.
A few moments later, I tried to connect back in and it worked, but the CPU was too high, even with no traffic passing through the firewall!

Here is the listing from the "System: Diagnostics: Activity" section during that period:
![image](https://user-images.githubusercontent.com/8492662/82153761-2f91cf00-9872-11ea-8823-17c4434aa22a.png)
The numbers shown in the Dashboard are more horrifying than those above.
Also, the management GUI has become slower.

For sure, one improvement could be to display a warning when enabling the IPS with RAM less than 1.5GB or so. Or give an indication for the requirements in the UI, next to the IPS switch.
For the CPU issues and the slowness, I am not sure what is going on.
There is zero traffic on my VM, so the CPU should at least be below 10%.

**Comment by abraha2d** [comment]
Hmm from how you describe it, that doesn't seems to be the same problem i was facing. Anyways, I've used PCI passthrough to dedicate a NIC to OPNsense for the WAN interface, and it seems to work that way to solve my problem.

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/core/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
