### ISSUE TITLE
20.1.b_43 Bug in GUI ---- System: Trust: Certificates 

### ISSUE THREAD

**Issue by nivek1612** [opnsense/core#3869]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[X] I have searched the existing issues and I'm convinced that mine is new.

When adding a new certificate via the GUI at System: Trust: Certificates the selection of "Method" has no effect on restricting the input fields. All fields are shown for all methods "Import An Existing" "Create an Internal" etc

**Note certificates appear to be generated correctly** 

**To Reproduce**
1. Go to System: Trust: Certificates
2. Click on Method
3. All inputs fields for all Methods remain visible

<img width="872" alt="Screenshot 2020-01-02 at 15 52 58" src="https://user-images.githubusercontent.com/23481092/71676361-fbf95100-2d77-11ea-835b-2bcadd3158f1.png">
 

**Expected behavior**
1. Go to System: Trust: Certificates
2. Click on Method
3. Only the input fields relative to the selected method should be shown 

**Screenshots**
Attached 

**Relevant log files**
N/A

**Additional context**
N/A

**Environment**
OPNsense 20.1.b_43-amd64
FreeBSD 11.2-RELEASE-p16-HBSD
OpenSSL 1.0.2t 10 Sep 2019

**Comment by AdSchellevis** [comment]
@nivek1612 thanks, seems to be a jQuery compatibility issue:
```
jQuery.fn.size() is deprecated and removed; use the .length property
```

Will close with a fix asap.
