### ISSUE TITLE
System: Configuration: Defaults: allow reboot as well as shutdown + confirmation dialog

### ISSUE THREAD

**Issue by igpit** [opnsense/core#3872]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[x] I have searched the existing issues and I'm convinced that mine is new.

**Use case**
Be able to reconfigure the system right after a configuration reset and reboot, without need to manually power on (e.g. firewall being remote, having separate connection to the first LAN port getting configured to default 192.168.1.1/24)

**Current behaviour**
"Shut down after changes are complete".

**Proposed solution**
Remove the "yes" button, instead show 2 buttons 
1. Load defaults and poweroff
2. Load defaults and reboot

As an extra, add a confirmation dialog before performing the config reset.

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/core/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
