### ISSUE TITLE
Multiple OpenVPN instances in one firewall interface

### ISSUE THREAD

**Issue by Nico82x** [opnsense/core#3877]
[+] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[+] I have searched the existing issues and I'm convinced that mine is new.

Hi,

as we all know, multiple OpenVPN instances are handled in the same firewall interface. This leads to a requirement to divide them by the source IPs (and might actually be abused for simple spoofed packets for certain scenarios). Therefore I'd like to ask if it is possible to create an own (virtual?) firewall instance for each OpenVPN instance. I guess in the end each instance gets it's own interface in the OS but since the naming might not be reliable, you chose this way instead. It'd be great if there was a solution for that which fits better to the general concept used in OPNsense.

Thanks,
Nicolaj

**Comment by Nico82x** [comment]
Hi again,

it seems that one can manually assign new interface to those instances. A feature I wasn't aware of until now. I guess this is exactly what I was looking for then. Sorry for this unrequired feature request then.

Best,
Nicolaj

**Comment by fichtner** [comment]
Hi Nicolaj,

No problem. I'm assuming this can be closed then.


Cheers,
Franco
