### ISSUE TITLE
API: VPN Status

### ISSUE THREAD

**Issue by bluesource** [opnsense/core#3878]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[x] I have searched the existing issues and I'm convinced that mine is new.

**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
add some VPN Tunnel states (Tunnel, Phase 1 /2) into the API for monitoring purposes:

- API should contain the status of the VPN Tunnel as shown in the OpnSense Dashboard (see screenshot)
- API should contain the status of the Phase2 Entries as shown in VPN -> IPSec -> Status Overview

**Describe alternatives you've considered**
parsing the vpn status of the dashboard - will run into issues upon updates of opnsense - not a valuable solution

**Additional context**
![image](https://user-images.githubusercontent.com/3057403/71886693-efd90f00-313c-11ea-9c46-df9acec14a86.png)

**Comment by bluesource** [comment]
@AdSchellevis I really don't know whats missing in the ticket and why its marked incomplete :)
thanks and regards, 
Michael

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/core/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
