### ISSUE TITLE
Problem with failover latency based

### ISSUE THREAD

**Issue by fgendorf** [opnsense/core#3879]
**Describe the bug**
Hi, the failover based on latency are buggy, when latency is high the gateway are removed from group gateways many times, and when the latency is normal again, the gateway returns to group only one time, and the connections don't go through it and I need apply firewall rules again.

**Expected behavior**
If latency is already high, and the gateway was removed from group gateways, it not should removed again and again

**Relevant log files**
Jan 8 01:31:08	monit[39059]: 'gateway_alert' status succeeded (0) -- no output
Jan 8 01:29:08	monit[39059]: 'gateway_alert' status failed (1) -- MONITOR: FLINGW has high latency, removing from routing group ESSSFLNGW
Jan 8 01:27:08	monit[39059]: 'gateway_alert' status failed (1) -- MONITOR: FLINGW has high latency, removing from routing group ESSSFLNGW
Jan 8 01:25:08	monit[39059]: 'gateway_alert' status failed (1) -- MONITOR: FLINGW has high latency, removing from routing group ESSSFLNGW
Jan 8 01:23:07	monit[39059]: 'gateway_alert' status failed (1) -- MONITOR: FLINGW has high latency, removing from routing group ESSSFLNGW
Jan 8 01:21:07	monit[39059]: 'gateway_alert' status failed (1) -- MONITOR: FLINGW has high latency, removing from routing group ESSSFLNGW
Jan 8 01:19:07	monit[39059]: 'gateway_alert' status failed (1) -- MONITOR: FLINGW has high latency, removing from routing group ESSSFLNGW
Jan 8 01:17:07	monit[39059]: 'gateway_alert' status failed (1) -- MONITOR: FLINGW has high latency, removing from routing group ESSSFLNGW
Jan 8 01:15:07	monit[39059]: 'gateway_alert' status failed (1) -- MONITOR: FLINGW has high latency, removing from routing group ESSSFLNGW
Jan 8 01:13:07	monit[39059]: 'gateway_alert' status failed (1) -- MONITOR: FLINGW has high latency, removing from routing group ESSSFLNGW
Jan 8 01:11:07	monit[39059]: 'gateway_alert' status failed (1) -- MONITOR: FLINGW has high latency, removing from routing group ESSSFLNGW
Jan 8 01:09:06	monit[39059]: 'gateway_alert' status failed (1) -- MONITOR: FLINGW has high latency, removing from routing group ESSSFLNGW
Jan 8 01:07:06	monit[39059]: 'gateway_alert' status failed (1) -- MONITOR: FLINGW has high latency, removing from routing group ESSSFLNGW

**Environment**
OPNsense 19.781 (amd64, OpenSSL).

**Comment by AdSchellevis** [comment]
The message isn't totally correct, its Monit reporting the status (not performing actions). 

https://github.com/opnsense/core/blob/168be32071ea4739ddab0aef5dd53ade49544c66/src/opnsense/scripts/OPNsense/Monit/gateway_alert#L63-L69

You can safely disable the monit check if your not interested in the messages, dpinger takes care of the actual switches using a monitor event.

https://github.com/opnsense/core/blob/a7b528be2b5a5128612ea95f65beb96862988977/src/etc/inc/plugins.inc.d/dpinger.inc#L236-L237

**Comment by fgendorf** [comment]
Thanks @AdSchellevis , I will remove monit checks, but my doubt is why connections still outing by secondary gateway after primary returns to group. Does any command to verify which gateway are currently operating?

**Comment by AdSchellevis** [comment]
The gateway page should show the current statuses. Low level you can always check `/tmp/rules.debug` for the rules that are generated for policy-based routing.

**Comment by fgendorf** [comment]
Very thank you @AdSchellevis, have a nice day

**Comment by fgendorf** [comment]
Hi Again, I just confirmed, the failover not return to primary gateway always.
All gateways are with status Online (so outgoing traffic should  going to 187.XXX.XXX.XXX), but in rules.debug is:
```pass in quick on em1 route-to {( em2 200.XXX.XXX.XXX )} sticky-address inet from {10.0.0.0/23} to {any} keep state label "8f91442a5874adfddf4c7d7--------"```

**Comment by AdSchellevis** [comment]
there are two things you can look at, first one is what happens if you regenerate the rules from the console (`configctl filter reload`), next you could check if the monitor event actually fired when you thought it should (I think it should be in the gateway log)

**Comment by fgendorf** [comment]
I just did the `filter reload`, and will wait for the high latency occur

**Comment by AdSchellevis** [comment]
but did the `rules.debug` change afterwards?

**Comment by fgendorf** [comment]
Yes, like I says before:
from
```pass in quick on em1 route-to {( em2 200.XXX.XXX.XXX )} sticky-address inet from {10.0.0.0/23} to {any} keep state label "8f91442a5874adfddf4c7d7--------"```
to
```pass in quick on em1 route-to {( em0 187.XXX.XXX.XXX )( em0 187.XXX.XXX.XXX )} sticky-address inet from {10.0.0.0/23} to {any} keep state label "8f91442a5874adfddf4c7d---------"```

**Comment by fgendorf** [comment]
Good morning (from Brazil)
OK, some firsts interaction works, high latency changed to 
```
pass in quick on em1 route-to {( em2 200.XXX.XXX.XXX )} sticky-address inet from {10.0.0.0/23} to {any} keep state label "8f91442a5874adfddf4c7d79---------"
```

when normalize returned to 

```
pass in quick on em1 route-to {( em0 187.XXX.XXX.XXX )( em0 187.XXX.XXX.XXX )} sticky-address inet from {10.0.0.0/23} to {any} keep state label "8f91442a5874adfddf4c7d----------"
``` 


but after some swaps it stops to return to primary gateway, the last swap to secondary gateway it stay on secondary until now... below are the log, this last interaction of dpinger registered Clear latency, but the gateway stay on secondary 

```
pass in quick on em1 route-to {( em2 200.XXX.XXX.XXX )} sticky-address inet from {10.0.0.0/23} to {any} keep state label "8f91442a5874adfddf4c----------"
```

The log files Gateways:

```
Jan 10 09:16:07 | dpinger: GATEWAY ALARM: FLINGW (Addr: 172.217.30.111 Alarm: 0 RTT: 25619ms RTTd: 9302ms Loss: 0%)
-- | --
Jan 10 09:16:07 | dpinger: FLINGW 172.217.30.111: Clear latency 25619us stddev 9302us loss 0%
Jan 10 09:15:46 | dpinger: GATEWAY ALARM: FLINGW (Addr: 172.217.30.111 Alarm: 1 RTT: 26073ms RTTd: 9403ms Loss: 0%)
Jan 10 09:15:46 | dpinger: FLINGW 172.217.30.111: Alarm latency 26073us stddev 9403us loss 0%
Jan 10 08:44:18 | dpinger: GATEWAY ALARM: FLINGW (Addr: 172.217.30.111 Alarm: 0 RTT: 22115ms RTTd: 197ms Loss: 0%)
Jan 10 08:44:18 | dpinger: FLINGW 172.217.30.111: Clear latency 22115us stddev 197us loss 0%
Jan 10 08:43:25 | dpinger: GATEWAY ALARM: FLINGW (Addr: 172.217.30.111 Alarm: 1 RTT: 27256ms RTTd: 9155ms Loss: 0%)
Jan 10 08:43:25 | dpinger: FLINGW 172.217.30.111: Alarm latency 27256us stddev 9155us loss 0%
Jan 10 08:02:27 | dpinger: GATEWAY ALARM: FLINGW (Addr: 172.217.30.111 Alarm: 0 RTT: 21957ms RTTd: 176ms Loss: 0%)
Jan 10 08:02:27 | dpinger: FLINGW 172.217.30.111: Clear latency 21957us stddev 176us loss 0%
Jan 10 08:01:39 | dpinger: GATEWAY ALARM: FLINGW (Addr: 172.217.30.111 Alarm: 1 RTT: 27431ms RTTd: 13045ms Loss: 0%)
Jan 10 08:01:39 | dpinger: FLINGW 172.217.30.111: Alarm latency 27431us stddev 13045us loss 0%
```

I don't did any changes on opnsense in mean time to avoid external influence.
Does exists a number of swaps that gateways groups can do?

Thanks

**Comment by AdSchellevis** [comment]
you try to inspect the system log, usually it should trigger `/usr/local/etc/rc.filter_configure` on monitor event, if it did on the time you expect, maybe it has some more context about it.

**Comment by fgendorf** [comment]
the system log :
```
Jan 10 09:16:07 | opnsense: /usr/local/etc/rc.filter_configure: ROUTING: creating /tmp/em0_defaultgw using '187.XXX.XXX.XXX'
-- | --
Jan 10 09:16:07 | opnsense: /usr/local/etc/rc.filter_configure: ROUTING: removing /tmp/em2_defaultgw
```
Apparently it runs... but the rules not applied

**Comment by AdSchellevis** [comment]
that's the output of the default gateway switching, which means that at that point in time it did trigger and preferred the other gateway as default. The groups are populated with the active gateways (I don't think they are in the log by themselves).

**Comment by fgendorf** [comment]
anything else I can do to find where is the issue?

**Comment by fgendorf** [comment]
I must disable "Allow default gateway switching" ?

**Comment by AdSchellevis** [comment]
default gateways switching is independent, so you can just leave it on if you would like to use it. My community support time is over, maybe someone else wants to step in or has additional ideas.

**Comment by fgendorf** [comment]
Ok, thanks for your time

**Comment by fgendorf** [comment]
Hi @AdSchellevis , just to inform you, I found the problem, maybe is not an expected behavior,
the range of latency are 10ms ex: beetwen 30 and 40ms, when the gateway primary latency cross the highest value of range, it is swapped to secondary, IF the latency reduce to 35ms, it became yellow and not return to primary, after if it reduce to 20ms, I guess from RED do yellow and yellow to green the trigger not change the rules, juste RED do Green.

I put the same value to From and To in Latency thresholds and the issue not occurred anymore.

Thanks for you help

**Comment by AdSchellevis** [comment]
thanks for letting us know, I'm not sure what the exact behaviour of the timings should be from the top of my mind (and when it signals an event), it might be good to extend the docs a bit for these settings.

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/core/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
