### ISSUE TITLE
MAC address database outdated

### ISSUE THREAD

**Issue by xpac1985** [opnsense/core#3883]
**Describe the bug**
The MAC address database used to get e.g. the hardware vendor from a mac address in the DHCP -> Leases page is pretty outdated.
According to [this forum post](https://forum.opnsense.org/index.php?topic=10380.0#msg47557), OPNsense uses the netaddr Python lib, which hasn't been updated since January 2017 and has no self-update mechanism built in. From the issues in their Github project, this has been mentioned multiple times, but it seems to be rather dead.

**To Reproduce**
1. Go to Services -> DHCPv4 -> Leases (status_dhcp_leases.php)
2. Have any recent device on your network
3. See vendor names only for older hardware.

**Expected behavior**
Show vendor names for all MAC addresses.

**Additional context**
Maybe using the mac-vendor-lookup Python library is a valid replacement:
https://pypi.org/project/mac-vendor-lookup/

**Comment by AdSchellevis** [comment]
It's probably better to see how https://github.com/netaddr/netaddr/pull/189 pins out, the PR is only a couple of months old, which isn't unusual for these kind of projects, migrating to something else in the hope that it won't get abandoned  has risks of its own.

Another library to only fetch http://standards-oui.ieee.org/oui.txt is something I would rather prevent from happening.

**Comment by xpac1985** [comment]
Yeah, I see the reasoning behind this. I just pointed to that lib because it allows to automatically pull the list for updates, while netaddr has it statically bundled and you'll have to wait for another release to be available for up to date data. It's not super important though, so I don't wanna cause a lotta work. ;-)

**Comment by brianmaissy** [comment]
Hey, I saw that you referenced my PR to netaddr. I'm trying to get it merged, but the maintainer isn't being so responsive. If it continues this way at some point I will also give up, and then I might fork the project and continue maintaining it (or at least updating the databases) myself. We'll be in touch.

**Comment by brianmaissy** [comment]
Sorry it's been a while and I haven't been in touch. We ended up vendoring it, but it looks like the project might be back to active maintenance.

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/core/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.

**Comment by ChriZ982** [comment]
Hello everyone,

it seems that the MAC database is outdated again. The netaddr repository has not seen any contributions since 2 years:

![grafik](https://user-images.githubusercontent.com/28103843/214107509-321c4413-a7ac-45b1-a1c5-dfee05a6d7c2.png)

I think it would be best to revisit this issue and download the MAC database regularly: https://github.com/opnsense/core/issues/5205

Best regards,
Chris

**Comment by AdSchellevis** [comment]
@ChriZ982 are you planning to work on it? reopening doesn't really make sense if there's no owner for the issue

**Comment by AdSchellevis** [comment]
@ChriZ982 we don't have plans to change this at the moment, it would be more logical to fix this upstream to be honest.
