### ISSUE TITLE
Aggregate squid localnet src ips

### ISSUE THREAD

**Issue by Kimotu** [opnsense/core#3884]
[x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[x] I have searched the existing issues and I'm convinced that mine is new.

**Is your feature request related to a problem? Please describe.**
When working with ip aliases, VIPs, etc. there may exist several addresses within the same subnet. This will cause warning when using 'squid -k check'

squid.conf
```
acl localnet src 10.8.0.0/24 # Possible internal network (interfaces v4)
acl localnet src 2002:db8:b00:9080::/64 # Possible internal network (interfaces v6)
acl localnet src 10.8.0.4/32 # Possible internal network (aliases)
acl localnet src 2002:db8:b00:9080::4/64 # Possible internal network (aliases)
acl localnet src 192.168.2.0/24 # Possible internal network (interfaces v4)
acl localnet src 192.168.2.136/32 # Possible internal network (aliases)
acl localnet src 192.168.2.137/32 # Possible internal network (aliases)
acl localnet src 192.168.2.138/32 # Possible internal network (aliases)
acl localnet src 192.168.2.132/32 # Possible internal network (aliases)

```
squid -k check
```
2020/01/14 08:09:25| WARNING: (A) '10.8.0.4' is a subnetwork of (B) '10.8.0.0/24'
2020/01/14 08:09:25| WARNING: because of this '10.8.0.4' is ignored to keep splay tree searching predictable
2020/01/14 08:09:25| WARNING: You should probably remove '10.8.0.4' from the ACL named 'localnet'
2020/01/14 08:09:25| aclIpParseIpData: WARNING: Netmask masks away part of the specified IP in '2002:db8:b00:1020::4/64'
2020/01/14 08:09:25| WARNING: (B) '2002:db8:b00:1020::/64' is a subnetwork of (A) '2002:db8:b00:1020::/64'
2020/01/14 08:09:25| WARNING: because of this '2001:7c0:b00:1020::/64' is ignored to keep splay tree searching predictable
2020/01/14 08:09:25| WARNING: You should probably remove '2001:7c0:b00:9080::/64' from the ACL named 'localnet'
2020/01/14 08:09:25| WARNING: (A) '192.168.2.136' is a subnetwork of (B) '192.168.2.0/24'
2020/01/14 08:09:25| WARNING: because of this '192.168.2.136' is ignored to keep splay tree searching predictable
2020/01/14 08:09:25| WARNING: You should probably remove '192.168.2.136' from the ACL named 'localnet'
2020/01/14 08:09:25| WARNING: (A) '192.168.2.136' is a subnetwork of (B) '192.168.2.0/24'
2020/01/14 08:09:25| WARNING: because of this '192.168.2.136' is ignored to keep splay tree searching predictable
2020/01/14 08:09:25| WARNING: You should probably remove '192.168.2.136' from the ACL named 'localnet'
2020/01/14 08:09:25| WARNING: (A) '192.168.2.137' is a subnetwork of (B) '192.168.2.0/24'
2020/01/14 08:09:25| WARNING: because of this '192.168.2.137' is ignored to keep splay tree searching predictable
2020/01/14 08:09:25| WARNING: You should probably remove '192.168.2.137' from the ACL named 'localnet'
2020/01/14 08:09:25| WARNING: (A) '192.168.2.138' is a subnetwork of (B) '192.168.2.0/24'
2020/01/14 08:09:25| WARNING: because of this '192.168.2.138' is ignored to keep splay tree searching predictable
2020/01/14 08:09:25| WARNING: You should probably remove '192.168.2.138' from the ACL named 'localnet'
2020/01/14 08:09:25| WARNING: (A) '192.168.2.132' is a subnetwork of (B) '192.168.2.0/24'
2020/01/14 08:09:25| WARNING: because of this '192.168.2.132' is ignored to keep splay tree searching predictable
2020/01/14 08:09:25| WARNING: You should probably remove '192.168.2.132' from the ACL named 'localnet'
```

**Describe the solution you'd like**
Run the src ips through aggregate (https://www.freebsd.org/cgi/man.cgi?query=aggregate).
Unforunatelly I am not familar with Jinja and how/whether you can filter via external commands. One must build one list from core/src/opnsense/service/templates/OPNsense/Proxy/squid.conf  lines 120 (interface addr) and 129 (VIPs), pipe it through aggregate and then build the acls.

I think aggregate will just handle ipv4.

**Describe alternatives you've considered**
If template engine cannot call external filters (I fear so, at least without additional python code), you could use php when save button is pressed to aggregate the IPs and write result as config entry to config.xml for localnets which can be used directly by template engine.

**Comment by AdSchellevis** [comment]
Although I don't like these warnings as well, it's highly unlikely that we're able to fix this completely, the same kind of messages will appear on IPv6, partly domain names in black/whitelists, etc etc.  

Filtering from within Jinja would only be possible if we would add additional helper functions to deduplicate the addresses, which would add more magic and would likely be difficult to debug in case of issues.

In case of ip aliases specifically, it might be an option to filter overlapping items here https://github.com/opnsense/core/blob/41d5cdb83dcd8396b96919ba977bede903f0200f/src/opnsense/service/templates/OPNsense/Proxy/squid.conf#L130

Using something like the following, which should check if both addresses are in the same net (https://netaddr.readthedocs.io/en/latest/tutorial_01.html#comparing-ip-addresses) :
```
helpers.getIPNetwork('10.0.0.1/24') == helpers.getIPNetwork('10.0.0.3/24')
```

As far as I know there's no downside of having these warnings other than log spam, but if someone would try to fix this (partially), just open a PR and we'll try to guide you through the process.

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/core/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
