### ISSUE TITLE
GeoIP issues

### ISSUE THREAD

**Issue by immakinbacon** [opnsense/core#3886]
1. The GeoIP tab is misspelled "GeopIP" unless I am missing something.
2. After following the https://docs.opnsense.org/manual/how-tos/maxmind_geo_ip.html HowTo I am still receiving the error to update the source in the GeoIP tab. I have verified that I am able to download the zip via the URL I have in the URL field.

Running OPNsense 19.7.9

**Comment by mimugmail** [comment]
1. already fixed in master
2. add a new rule with new alias and check back, this should force a trigger

**Comment by immakinbacon** [comment]
That did it thank you!
