### ISSUE TITLE
Command to kill states on a cron job

### ISSUE THREAD

**Issue by muchahagrande** [opnsense/core#3887]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[yes] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[yes] I have searched the existing issues and I'm convinced that mine is new.

**Is your feature request related to a problem? Please describe.**
I have a pf states inconsistence from time to time on a PBX behind an OPNSense firewall.
My PBX loses conectivity with a trunk provider and I can't figure out why.
At first this happend when my ISP changed the public IP, but it hasn't changed for a long while and the problem persists.

**Describe the solution you'd like**
I'd like to automate the steps I found to be the work around to this issue.
Actually I go to Firewall > Diagnostics > State Dump and filter the states related to the VOIP trunk provider IP address.
The state table shows two states, and then, after the filter is applied I press the kill button and when the PBX registers again it generates new states and the problem is gone.
I would like a new option in the Command combo box of the Edit Job menu at System > Settings > Cron.
The new command would be named 'Kill states' and the filter would be set in the Parameter box below the Command combo.
The parameter could accept IPs or Aliases.
I could execute this command every hour and in the worst case the VOIP service would fail for that time.

**Describe alternatives you've considered**
I have tested pfctl command with the -k command using the IP address of the trunk provider and it worked.
The alternative is to add the cron job manually from a commnad shell but it will not survive system updates.

**Additional context**

![imagen](https://user-images.githubusercontent.com/20299175/72550443-80b49680-3871-11ea-843b-f0d49f57a75b.png)

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/core/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
