### ISSUE TITLE
Implement help request directly in the web ui's different page

### ISSUE THREAD

**Issue by RomanJos** [opnsense/core#3889]
Hi everyone I had a hard time debugging my captive portal issue wich turned out to be because of enforce local group was set to "Admin" in my captive portal settings.
It would be cool to be able to post our config for this part/plugin only and appear on a small box (like when you press Win + G on windows you can see people that want to play) for my case on the captive portal page so if anyone feel free to give a quick anonymous help it may help or at least give a starting point to te person in need 😃

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/core/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
