### ISSUE TITLE
captive portal - cannot disable "enforce local group"

### ISSUE THREAD

**Issue by eliteadmin** [opnsense/core#3891]
**Describe the bug**
The setting Enforce Local Group: none in Services -> Captive Portal -> Administration is obviously not adopted. The setting always remains set to "admin". Thus, no LDAP authentication is possible.

**To Reproduce**

1. Go to 'Services -> Captive Portal -> Administration'
2. Click on 'Enforce Local Group'
3. Scroll down to 'none'

**Expected behavior**
NOT "Enforce Local Group" to "admin"

**Environment**
OPNsense 19.7.9_1-amd64
FreeBSD 11.2-RELEASE-p16-HBSD
OpenSSL 1.0.2u 20 Dec 2019

**Comment by AdSchellevis** [comment]
```
opnsense-patch c0b7d96
```

should probably do the trick.

**Comment by eliteadmin** [comment]
> opnsense-patch c0b7d96

> should probably do the trick.

Thank you! Works fine.
