### ISSUE TITLE
Connectivity lost when I "Enable Static ARP entries" Option in the DHCP section

### ISSUE THREAD

**Issue by JOduMonT** [opnsense/core#3894]
Hi;

as in this issue (https://github.com/opnsense/core/issues/1828)
it happen systematically to me
After enabling **Static ARP entries** than a reboot OPNSense lost his connectivity, sometimes I don't even need to reboot.

OPNSense 19.7 installed from DVD.iso
Package up2date or not it don't really matter
With or without prior configuration it don't really matter neither

##### My config is a brand new Proxmox 6.1
OPNSense as the first KVM
1 vCPU
4GiB of RAM
2 NIC
\- virtio
\- pci passthrough: Intel 82574L

#### To Reproduce
1. download OPNSense
2. install OPNSense
3. configure DHCPv4
4. enable Static ARP entries

**Comment by JOduMonT** [comment]
@AdSchellevis I add the To reproduce in my Issue, if other info are missing, could you point it out please ?
Thank You for your help :)

**Comment by AdSchellevis** [comment]
Incomplete generally means that our template isn't used, which makes it harder for people to assess. Otherwise it would probably receive a (cummunity) support tag. By the way, the help text for this specific option tells the following:

> 
> Warning: This option persists even if DHCP server is disabled. Only the machines listed below will be able to communicate with the firewall on this NIC.
> --
> 

Your issue doesn't appear to contain static entries (or it's not mentioned), nor does it seem to contain details of what you expect the device todo.

**Comment by JOduMonT** [comment]
@AdSchellevis 
Oh; thank for your time and your explanation. I've never considered the github template on this way, and never truly respect them, but since than I will do the effort ;)

Also; I presumed **Enable Static ARP entries** was reservation like in Windows DHCP and **Deny unknown clients** was the option to only the machines listed below to communicate with the firewall.

**Comment by nyanmeister** [comment]
I was impacted by this too, I wish the warning text was more terse and to the point about how it would basically break everything instantly.
