### ISSUE TITLE
SNMP enabling crashed the box

### ISSUE THREAD

**Issue by fichtner** [opnsense/core#39]
Related to https://redmine.pfsense.org/issues/4403

If anybody has a crash report I'd be delighted.

**Comment by jschellevis** [comment]
Not sure who has reported this issue for OPNsense, but tested with latest release works fine.
Proof :-)

![schermafbeelding 2015-06-23 om 17 46 55](https://cloud.githubusercontent.com/assets/9606698/8310408/01f3aa4e-19d0-11e5-9cb9-5f8a81d8795c.png)
![schermafbeelding 2015-06-23 om 17 46 40](https://cloud.githubusercontent.com/assets/9606698/8310410/0215f018-19d0-11e5-862c-741516cda333.png)

**Comment by jschellevis** [comment]
Close? Close?

**Comment by fichtner** [comment]
No, needs to be fixed for empty SD slot case. Fringe case, but still unresolved in FreeBSD. :(

**Comment by jschellevis** [comment]
ok... 
It does work on Netboard A10 with SSD and empty SD slot.. but on APU the SD card slot is actually a converter..

**Comment by fichtner** [comment]
Timeout
