### ISSUE TITLE
IPS/ Suricata syslog does not show all alerts that are listed in the "Alerts" view of the web interface

### ISSUE THREAD

**Issue by fmarceau-stratacache** [opnsense/core#3900]
Hello OPNsense team,

We are using OPNsense 19.7.6-amd64.

I have an issue with Suricata external logging. It seems that not all alerts end up in the syslog !

A previous issue was raised about a year and a half ago regarding this and it got closed :
> https://github.com/opnsense/core/issues/2809

What we experience is exactly the same as what is mentioned in the above issue. When we compare the two following views we don't have the same output :
- Services > Intrusion Detection > Administration > Alerts
- Services > Intrusion Detection > Administration > Log File

Just to make it clear, the alerts action from the "Alerts" view is blocked so I expect that they should all be sent to syslog-ng.

Please let me know if there's anything I can do/ provide to help you guys with this.

Thanks

**Comment by fmarceau-stratacache** [comment]
@AdSchellevis This is a repost of a closed issue that was never fixed and wasn't tagged as incomplete. I can copy & paste the content of the older issue if you want as I have the same exact problem.

**Comment by AdSchellevis** [comment]
It's usually not very useful to repost issues without new or extended context, but that's another issue. 

Nowadays we offer templates, which if not used, normally would lead to the `incomplete` label. People can still discuss, try to help, extend the issue to something reproducible,  the core team likely won't spend a lot of time on it.

**Comment by fmarceau-stratacache** [comment]
@AdSchellevis here's the template filled :

**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
[X] I have searched the existing issues and I'm convinced that mine is new.

**Describe the bug**
We have an issue with the IDS logging. 

After configuring a new "Logging target" that collects the suricata application logs (all levels (except debug) & facilities) and transports them via TCP(4) to a remote syslog server, we are missing a lot of alerts when we compare what we receive on our remote syslog server with the ones displayed in the GUI at the following page :
- Services > Intrusion Detection > Administration > Alerts

However, it seems that what we are receiving matches the content of this view / log file from the GUI :
- Services > Intrusion Detection > Administration > Log File

Also, just to make it clear, the "Logging target" that I configured doesn't have any droppped or queued packets and is receiving logs.

**To Reproduce**
Steps to reproduce the behavior:
1. Setup a remote syslog server that listens for connections in TCP
2. Add & enable the remote syslog in "System > Settings > Logging / targets" :
  a. Enabled: X
  b. Transport: TCP(4)
  c. Applications: suricata (suricata)
  d. Levels: info, notice, warn, error, critical, alert, emergency
  f. Facilities: Nothing selected => (Doc says: omit to select all)
  g. Hostname: Your remote syslog server address/ host
  h. Port: Your remote syslog server port
  i. Description: fmarceau-stratacache suricata alerts logging issue
3. Go to 'Services > Intrusion Detection > Administration > Rules'
  a. Enable all the rules
4. Do a quick test and try to go on dropbox.com to hit the "OPN_File_Transfer - Dropbox - DNS request for dropbox.com" rule (Signature Id #53000027)
5. Validate that the request is blocked (the website doesn't resolve), that an alert is generated and states that the request has been blocked and that this alert is present in the two following views :
- Services > Intrusion Detection > Administration > Alerts
- Services > Intrusion Detection > Administration > Log File
6. Validate that the alert makes it to the external syslog server
7. Write a load test script that hits multiple rules of the IDS and run it for some time...
8. After a while, compare the content of your remote syslog server and the two following views :
- Services > Intrusion Detection > Administration > Alerts
- Services > Intrusion Detection > Administration > Log File

**Expected behavior**
I expect the IDS blocked alerts associated to the IDS rules that I've enabled to make it to the IDS log file and to my remote syslog server.

**Screenshots**
I attached four screenshots. One from my logging target statistics view, one is from the IDS alerts view, anothing from the IDS log file view and one from my remote logging server. As you can see by looking at the timestamps, the content of the ones from the IDS log file view & my remote logging server match but when you compare them with the content of the IDS alerts view you see something different. Also, if you check the logging target statistics view, there are no dropped or queued events. 

![IDS - Alerts view](https://user-images.githubusercontent.com/60523461/73677868-2f840f80-4685-11ea-9a59-df17b97c5818.png)
![IDS - Log File view](https://user-images.githubusercontent.com/60523461/73677869-2f840f80-4685-11ea-86e9-e81a68b102f7.png)
![Logging target](https://user-images.githubusercontent.com/60523461/73677870-2f840f80-4685-11ea-9d8c-2b7d07195a4a.png)
![Remote syslog server logs](https://user-images.githubusercontent.com/60523461/73677871-301ca600-4685-11ea-97b2-c97b60c514e3.png)

**Relevant log files**
Nothing to add here, let me know if you need anything.

**Additional context**
Nothing to add here, let me know if you need anything.

**Environment**
OPNsense 19.7.6-amd64
- FreeBSD 11.2-RELEASE-p14-HBSD
- OpenSSL 1.0.2t 10 Sep 2019
Intel(R) Xeon(R) E-2134 CPU @ 3.50GHz (8 cores)

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/core/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
