### ISSUE TITLE
security/acme-client Retrieve Cert/Key via REST API

### ISSUE THREAD

**Issue by Shackelford-Arden** [opnsense/core#3901]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[-] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[-] I have searched the existing issues and I'm convinced that mine is new.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
(e.g. I would like an input field in the `/ui/firewall/alias` which would add .... to ....)

**Describe alternatives you've considered**

**Additional context**

**Comment by AdSchellevis** [comment]
empty template, if the intend is to open a ticket for acme client, please do so in plugins containing all relevant information.

**Comment by Shackelford-Arden** [comment]
Not really sure what happened to all the stuff I entered but I'll get that remedied and submitted in the right section. Sorry about that!

**Comment by AdSchellevis** [comment]
no problem, things happen :)
