### ISSUE TITLE
Larger text input box for SSH keys

### ISSUE THREAD

**Issue by darkain** [opnsense/core#3905]
It would be nice to have a larger text input box for SSH keys. I use these extensively for remote management. Since I have multiple Yubikeys (each with their own unique SSH public key) and multiple services with automation to update my OPNsense routers over SSH, I have quite a few keys I need to handle. By default, the text input box is only visibly a single line and visually truncated after ~30 characters. It would be nice to set the text box to 100% width of the column it is in, and then make it 10+ rows in length.

**Comment by AdSchellevis** [comment]
@darkain can you try https://github.com/opnsense/core/commit/6cb988ea0625cbb61fd91693dd8149328cd6e5d8 ? should fix the with, height is only expanded upon visit (as it was, I don't want to change that0.

```
opnsense-patch 6cb988e
```

**Comment by darkain** [comment]
Yup, this works significantly better. Thanks!

**Comment by AdSchellevis** [comment]
your welcome.
