### ISSUE TITLE
OpenVPN with client specific overrides IPv6 address doesn't work

### ISSUE THREAD

**Issue by trunet** [opnsense/core#3907]
**Describe the bug**
When setting static IPv6 IPs to an openvpn client, it gives a different IPv6 in the subnet (:2 instead of :102).

Note that the generated openvpn-csc file, also have a wrong syntax for ifconfig-ipv6-push.  [OpenVPN documentation] states that it should be IP/64 and not IP[SPACE]64.
```
ifconfig-ipv6-push ipv6addr/bits ipv6remote
```

Probably related code is on [src/etc/inc/plugins.inc.d/openvpn.inc#L1074].

**To Reproduce**
I have a normal OpenVPN server, with client specific override settings:
```
IPv4 Tunnel Network: 192.168.199.102/24
IPv6 Tunnel Network: 2001:[REDACTED]:[REDACTED]:199::102/64
```

Generated /var/etc/openvpn-csc/1/[REDACTED]:
```
ifconfig-push 192.168.199.102 255.255.255.0
ifconfig-ipv6-push 2001:[REDACTED]:[REDACTED]:199::2 64
```

**Expected behavior**
It should give 2001:[REDACTED]:[REDACTED]:199::102/64 to the client

**Relevant log files**
/var/log/openvpn.log
```
Feb  3 13:40:41 firewall01 openvpn[82635]: [REDACTED]/[REDACTED]:35402 RESOLVE: Cannot resolve host address: 64: (hostname nor servname provided, or not known)
```

**Environment**
OPNsense 20.1 (amd64, OpenSSL).

[src/etc/inc/plugins.inc.d/openvpn.inc#L1074]: https://github.com/opnsense/core/blob/master/src/etc/inc/plugins.inc.d/openvpn.inc#L1074
[OpenVPN documentation]: https://openvpn.net/community-resources/reference-manual-for-openvpn-2-4/

**Comment by AdSchellevis** [comment]
@trunet can you try https://github.com/opnsense/core/commit/ccc0f37098ff2cd021ad95a49c3963ce4990c286

From a console you should be able to run the following command (and restart openvpn to be sure)
```
opnsense-patch ccc0f37
```

It looks like it's only the slash indeed, but I haven't validated this on my end.

**Comment by trunet** [comment]
Hello... Thanks for that, but I think this only fixes one part of this bug.

The second part is why is it giving :2 instead of :102 as I configured...

**Comment by AdSchellevis** [comment]
oops, missed a spot there, can you add https://github.com/opnsense/core/commit/f670ba6e2d0580a4621f912621841cd70d6fd747 as well then?

**Comment by trunet** [comment]
It's odd...

Now, the csc file is fine:
```
ifconfig-push 192.168.199.102 255.255.255.0
ifconfig-ipv6-push 2001:470:7d5d:199::102/64
```

But my client after reconnecting is still getting ::2.
```
utun10: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> mtu 1500
	inet 192.168.199.102 --> 192.168.199.102 netmask 0xffffff00
	inet6 fe80::[REDACTED]%utun10 prefixlen 64 scopeid 0xf
	inet6 2001:[REDACTED]:[REDACTED]:199::2 prefixlen 64
	nd6 options=201<PERFORMNUD,DAD>
```

**Comment by AdSchellevis** [comment]
what does the log say on the other end?

**Comment by trunet** [comment]
I have this on the client:
```
2020-02-03 14:18:10: Opened utun device utun10
2020-02-03 14:18:10: /sbin/ifconfig utun10 delete
2020-02-03 14:18:10: NOTE: Tried to delete pre-existing tun/tap instance -- No Problem if failure
2020-02-03 14:18:10: /sbin/ifconfig utun10 192.168.199.102 192.168.199.102 netmask 255.255.255.0 mtu 1500 up
2020-02-03 14:18:10: /sbin/ifconfig utun10 inet6 2001:[REDACTED]:[REDACTED]:199::2/64
2020-02-03 14:18:10: Initialization Sequence Completed
2020-02-03 14:18:10: DNS mode set to Split
2020-02-03 14:18:11: State changed to Connected
```

On another firewall I have with pfSense, it works fine. My csc file is like this there:
```
ifconfig-push 192.168.198.102 255.255.255.0
ifconfig-ipv6-push 2001:[REDACTED]:[REDACTED]:198::102/64 2001:470:b348:198::1
```

**Comment by AdSchellevis** [comment]
ok, we should push the start address, can you add this https://github.com/opnsense/core/commit/ff290c95ec27b7afb306ab63295ccd390da1ea18 as well?

**Comment by trunet** [comment]
this did the trick, it's working fine now. Thank you very much man, appreciate it.

```
utun10: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> mtu 1500
	inet 192.168.199.102 --> 192.168.199.102 netmask 0xffffff00
	inet6 fe80::[REDACTED]%utun10 prefixlen 64 scopeid 0xe
	inet6 2001:[REDACTED]:[REDACTED]:199::102 prefixlen 64
	nd6 options=201<PERFORMNUD,DAD>
```

**Comment by AdSchellevis** [comment]
your welcome, thanks for reporting back
