### ISSUE TITLE
DHCPv6 allows to configure DDNS (Dynamic DNS) but fails to add configuration on config file

### ISSUE THREAD

**Issue by trunet** [opnsense/core#3908]
**Describe the bug**
If you configure Dynamic DNS settings on DHCPv6, only ddns-domainname is being set. No key, no algorithm, nothing.

Would also be nice to add the algorithms drop-down list from https://github.com/opnsense/core/pull/2651 to DHCPv6 settings.

**To Reproduce**
Configure DHCPv6 with Dynamic DNS. Add all 4 settings, only ddns-domainname reaches the configuration file.

**Expected behavior**
If it's on the GUI, this should add the settings to the configuration file.

**Environment**
OPNsense 20.1 (amd64, OpenSSL).

**Comment by trunet** [comment]
BTW, I'll work on that on my fork and will send a PR.

**Comment by trunet** [comment]
The code is very spaghetti :D

Can anybody enlighten me if there's a way to manually (from the CLI) trigger the DHCP config files regeneration and if possible how usually do you debug it?

**Comment by trunet** [comment]
Work in Progress PR: https://github.com/opnsense/core/pull/3909

**Comment by AdSchellevis** [comment]
```
pluginctl dhcp
```

would probably do the trick to restart the dhcp service

**Comment by trunet** [comment]
@AdSchellevis Can you check the PR and see if it's good for you?

**Comment by AdSchellevis** [comment]
At the moment I don't have a lot of time to dig into it. Looking at it briefly I think it could be simplified a bit, the existing legacy code isn't too great, if possible, we try to minimise the amount of new code in there as much as possible.

I'll get back to you on this.
