### ISSUE TITLE
Menu: move "User Manager" to "User"

### ISSUE THREAD

**Issue by fabianfrz** [opnsense/core#391]

**Comment by fichtner** [comment]
I'm totally unsure this is a good idea. The "user" section was added by us to make room for the user-specific password changer, which was almost completely unreachable in the previous navigation structure. Then we added the logout, a feature associated to the actual user/session.

The user manager is fundamentally different as it is a admin-oriented task that makes sense to be under "system".

System modifies all aspects of a system, user only modifies things for a particular user. Does that sound reasonable?

**Comment by fabianfrz** [comment]
Yes, should I close this issue?

**Comment by fichtner** [comment]
Just did not want to close it prematurely. Will so now, thanks.
