### ISSUE TITLE
Can't activate Single Gateway (VPN)

### ISSUE THREAD

**Issue by stackpivot** [opnsense/core#3917]
**Describe the bug**
I installed VPN clients (OpenConnect and Wireguard) following the publicly available tutorials. But can not activate them under gateways.

**To Reproduce**
1. Add WG client according to https://docs.opnsense.org/manual/how-tos/wireguard-client-azire.html
2. Add gateway 
3. Try to activate gateway

**Expected behavior**
Gateway should be able to activate but is always disabled.

**Screenshots**
Wireguard client is working:
![Image of WG cient]
(https://i.imgur.com/L2dosdc.png)

VLAN to be routed through Wirguard Client (not really relevant, just listing to give context)
![Image of VLAN interface]
(https://i.imgur.com/4uLzL79.png)

NAT rule for Wireguard Client
![Image of NAT]
(https://i.imgur.com/BB2L3v3.png)

Firewall rule to fwd to gateway
![Image of FW rule]
(https://i.imgur.com/i2NDgax.png)

!!!! Gateway that can not be activated:
![Image of boken gateway activation]
(https://i.imgur.com/OD7AsTF.png)

**Relevant log files**
I already tried to look at the logs, but they are empty.

File /var/log/gateways.log yielded no results.

**Additional context**
I tried removing, and creating it new, and I have the same issue with the OpenConnect VPN client, so I assume its no issue with WireGuard but with actual gateway logic.

**Environment**

OPNsense 19.7.10_1-amd64
FreeBSD 11.2-RELEASE-p16-HBSD
OpenSSL 1.0.2u 20 Dec 2019
AMD GX-412TC SOC (4 cores)

**Comment by stackpivot** [comment]
Can someone please help me here? Problem still persists

**Comment by stackpivot** [comment]
How will I get support for this? willing to pay some money to get this resolved

**Comment by mimugmail** [comment]
Openconnect doesnt work with gateway I guess. For Wireguard search Forums for 1.2.3.4 and you will find how to add gateway

**Comment by stackpivot** [comment]
That's not really helping, as I am not even able to enable the gateway, as seen in the screenshots

**Comment by mimugmail** [comment]
Please Open a forum thread for this top and close the issue. I can better help you over there

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/core/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
