### ISSUE TITLE
Support configuration of getty terminal type 3wire in /etc/ttys

### ISSUE THREAD

**Issue by crowbarz** [opnsense/core#3921]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[Y] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[Y] I have searched the existing issues and I'm convinced that mine is new.
https://github.com/opnsense/core/issues?utf8=%E2%9C%93&q=is%3Aissue+clocal
https://github.com/opnsense/core/issues?utf8=%E2%9C%93&q=is%3Aissue+%2Fetc%2Fttys+
However there is mention of the same issue here: https://forum.opnsense.org/index.php?topic=11735.msg53413#msg53413

**Is your feature request related to a problem? Please describe.**
Serial console hangs on login when accessed from a terminal device that doesn't assert DCD. This principally happens when /bin/sh is run at login as the default shell. [It occurs in FreeBSD as well](https://www.freebsd.org/doc/handbook/term.html#term-debug), the solution there is to change `getty` to use terminal type `3wire` which sets termcap `clocal` through `/etc/gettytab` option `nc` (this option is not included in type `std`). However, [this forum post](https://forum.opnsense.org/index.php?topic=6702.0) mentions that `/etc/ttys` is deliberately regenerated whenever System > Settings > Administration is saved, so whilst I can modify it after boot/configuration there's no way to persist this change across reboots/reconfiguration.

**Describe the solution you'd like**
A checkbox option in System > Settings > Administration that replaces terminal type `std` with `3wire` in [`system.inc`](https://github.com/opnsense/core/blob/master/src/etc/inc/system.inc#L1132). Alternatively, perhaps the default terminal type for serial consoles can be changed from `std` to `3wire`, though it's unclear to me what this might break.

**Comment by fichtner** [comment]
I had a bit of time to research. We have the required "3wire" in FreeBSD, but not "al.3wire" which is a pfSense solution. I just wonder why their FreeBSD programmers do not provide these patches to FreeBSD itself. ;)

https://github.com/pfsense/FreeBSD-src/commit/3e6062ee30 from 2016... plenty of time to move it to FreeBSD as well *shrugs*

We will have to add something similar before we can switch to 3wire consistently.
