### ISSUE TITLE
Suspecting a missing break statement in src/www/interfaces.php

### ISSUE THREAD

**Issue by khorben** [opnsense/core#3922]
Hi there,

it seems to me that a `break;` statement might be missing here:
https://github.com/opnsense/core/blob/9f3f4d7336ba8655803471096ad60f476fdb0939/src/www/interfaces.php#L693

Without it, I believe that interfaces configured as type "none" will check the DHCP settings anyway. This is probably not harmful but unintentional nonetheless.

HTH,
-- khorben

**Comment by AdSchellevis** [comment]
@khorben you're right, thanks! fixed in https://github.com/opnsense/core/commit/65b80e6a551aab30a58164eef80bdc5a1a42de5b
