### ISSUE TITLE
Add source IP address parameter while setting up a logging destination 

### ISSUE THREAD

**Issue by PacoTyson** [opnsense/core#3924]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[X] I have searched the existing issues and I'm convinced that mine is new.

**Is your feature request related to a problem? Please describe.**
When sending logs to a remote syslog server, the OPNsense system uses a source IP that is not allowed to reach the remote syslog server.

**Describe the solution you'd like**
I'd like to force the source IP address when setting up a logging destination (in System:Settings:Logging / targets).
According to the [syslog-ng doc](https://www.syslog-ng.com/technical-documents/doc/syslog-ng-open-source-edition/3.25/administration-guide/42#TOPIC-1349450), one must add the line : 
`localip("<source_ip_address>")`
in the network() section of /usr/local/etc/syslog-ng.conf.d/syslog-ng-destinations.conf file

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/core/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.

**Comment by skid9000** [comment]
Hello,

i second this issue. I can't send logs to my syslog server in any of my setups due to this.
Is there a workaround possible in the meantime? I tried to edit manually the file and restart syslog-ng but it gets overwritten right away...
