### ISSUE TITLE
memberOf not correctly parsed

### ISSUE THREAD

**Issue by Koma-Andrea** [opnsense/core#3925]
**Describe the bug**
When using [freeipa](https://www.freeipa.org/) groups (memberof) are not correctly parsed.

**To Reproduce**
1) Configure with or without bind LDAP endpoint to FreeIPA host (vanilla, no configuration other than create an user and add it to a group).
2) Use the tester

**Expected behavior**
The groups should be listed

**Screenshots**
<img width="731" alt="Screenshot 2020-02-12 at 10 11 43" src="https://user-images.githubusercontent.com/247170/74319972-1f081f00-4d80-11ea-918b-90b884153c2a.png">
<img width="1377" alt="Screenshot 2020-02-12 at 10 11 14" src="https://user-images.githubusercontent.com/247170/74319992-25969680-4d80-11ea-9f9e-9da59ed31953.png">

```
User: acervesa authenticated successfully.
This user is a member of these groups:


Attributes received from server:
dn => uid=acervesa,cn=users,cn=accounts,dc=ocplab,dc=local
givenname => Andrea
sn => Cervesatz
uid => acervesa
cn => Andrea Cervesatz
displayname => Andrea Cervesatz
initials => AC
gecos => Andrea Cervesatz
krbprincipalname => acervesa@OCPLAB.LOCAL
objectclass => top person organizationalperson inetorgperson inetuser posixaccount krbprincipalaux krbticketpolicyaux ipaobject ipasshuser ipaSshGroupOfPubKeys mepOriginEntry
loginshell => /bin/sh
homedirectory => /home/acervesa
mail => acervesa@ocplab.local
krbcanonicalname => acervesa@OCPLAB.LOCAL
ipauniqueid => d50cd940-4d07-11ea-9fcf-005056a1c440
uidnumber => 271000006
gidnumber => 271000006
krbpasswordexpiration => 20200211195101Z
krblastpwdchange => 20200211195101Z
krbextradata => �C^root/admin@OCPLAB.LOCAL
mepmanagedentry => cn=acervesa,cn=groups,cn=accounts,dc=ocplab,dc=local
memberof => cn=admins,cn=groups,cn=accounts,dc=ocplab,dc=local cn=Replication Administrators,cn=privileges,cn=pbac,dc=ocplab,dc=local cn=Add Replication Agreements,cn=permissions,cn=pbac,dc=ocplab,dc=local cn=Modify Replication Agreements,cn=permissions,cn=pbac,dc=ocplab,dc=local cn=Read Replication Agreements,cn=permissions,cn=pbac,dc=ocplab,dc=local cn=Remove Replication Agreements,cn=permissions,cn=pbac,dc=ocplab,dc=local cn=Modify DNA Range,cn=permissions,cn=pbac,dc=ocplab,dc=local cn=Read PassSync Managers Configuration,cn=permissions,cn=pbac,dc=ocplab,dc=local cn=Modify PassSync Managers Configuration,cn=permissions,cn=pbac,dc=ocplab,dc=local cn=Read LDBM Database Configuration,cn=permissions,cn=pbac,dc=ocplab,dc=local cn=Add Configuration Sub-Entries,cn=permissions,cn=pbac,dc=ocplab,dc=local cn=Read DNA Range,cn=permissions,cn=pbac,dc=ocplab,dc=local cn=Host Enrollment,cn=privileges,cn=pbac,dc=ocplab,dc=local cn=System: Add krbPrincipalName to a Host,cn=permissions,cn=pbac,dc=ocplab,dc=local cn=System: Enroll a Host,cn=permissions,cn=pbac,dc=ocplab,dc=local cn=System: Manage Host Certificates,cn=permissions,cn=pbac,dc=ocplab,dc=local cn=System: Manage Host Enrollment Password,cn=permissions,cn=pbac,dc=ocplab,dc=local cn=System: Manage Host Keytab,cn=permissions,cn=pbac,dc=ocplab,dc=local cn=System: Manage Host Principals,cn=permissions,cn=pbac,dc=ocplab,dc=local cn=ipausers,cn=groups,cn=accounts,dc=ocplab,dc=local cn=vpn,cn=groups,cn=accounts,dc=ocplab,dc=local cn=fwadmin,cn=groups,cn=accounts,dc=ocplab,dc=local
```

OPNsense 19.7.9_1-amd64
FreeBSD 11.2-RELEASE-p16-HBSD
OpenSSL 1.0.2u 20 Dec 2019

This problem is present from at least 1.5 years.
In  pfSense I got it working by playing with attrivutes.

**Comment by AdSchellevis** [comment]
the memberof attribute type doesn't seem valid (no valid split character), maybe you can reconfigure freeipa, others seem to have similar issues with the format as well (https://confluence.atlassian.com/stashkb/ldap-groups-are-not-being-populated-with-users-using-freeipa-695109328.html)

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/core/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.

**Comment by Angelinsky7** [comment]
i've got the same issue from a Microsoft LDAP Active Directory.
My memberof field is separated with " " (space) like all microsoft AD field.
and thus, opnsense cannot parse the groups

**Comment by AdSchellevis** [comment]
Fields shouldn't be separated by spaces, our gui sometimes seems to suggest they are space separated, where in reality we concat different results on separate lines:
https://github.com/opnsense/core/blob/9679471d906631fe5f55efdda5b1174734278622/src/opnsense/mvc/app/library/OPNsense/Auth/LDAP.php#L578

To make it more clear I've just added https://github.com/opnsense/core/commit/d49e44ac01e8dabcd3561858d04a0b94cc0bd0fe to line break  multiple responses

Found some examples of rfc2307bis responses online as well here : https://unofficialaciguide.com/2019/07/31/ldap-schemas-for-aci-administrators-rfc2307-vs-rfc2307bis/

**Comment by nikolaysu** [comment]
Maybe this will help someone
I had the same problem version - OpnSense 24.1.4 + FreeIPA
If you set Initial Template - Novell eDirectory, then Extended Query
memberof=cn=usergrp.openvpn.main,cn=groups,cn=accounts,dc=..... works correctly
