### ISSUE TITLE
OpenVPN Server config / Checkbox not working

### ISSUE THREAD

**Issue by superwinni2** [opnsense/core#3926]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[-] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[-] I have searched the existing issues and I'm convinced that mine is new.

**Describe the bug**
1. You've got configured an OpenVPN Server and (for example) set the checkbox at "DNS Servers" and typed in an IP of your DNS Server. After this you saved the configuration.
2. You want to delete the DNS Server config entry and uncheck the checkbox  for "DNS Servers" and save, the entry is still valid until you delete and uncheck the checkbox after that.

**To Reproduce**
See on top.

**Expected behavior**
If I uncheck the checkbox even with entrys in them, they should be disabled or deleted.

**Environment**
Software version used and hardware type if relevant.
e.g.:

OPNsense 19.7.9_1 (amd64, OpenSSL).
Intel(R) Xeon(R) E-2136 CPU @ 3.30GHz (12 cores)

but also happens on:
OPNsense 20.1-amd64
Intel(R) Core(TM) i3-4030U CPU @ 1.90GHz

**Comment by AdSchellevis** [comment]
That's probably the case with more of those legacy toggles, it's not high on our list of things todo, since you either have to work your way through all of them or keep it as is. 

Let's label this request "help-wanted" and see if someone else wants to give it a spin.

**Comment by superwinni2** [comment]
Okay 👍 
I also thought it's not a heavy problem :)
I just thought I'm just telling it so it's there. :)

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/core/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
