### ISSUE TITLE
LAGG & VLAN status on dashboard

### ISSUE THREAD

**Issue by darkain** [opnsense/core#3928]
![image](https://user-images.githubusercontent.com/2524251/74400338-6ddea480-4dd2-11ea-9db9-5aa51f318a24.png)

I'd like to see LAGG & VLAN status on the dashboard under Interfaces (or in some new panel).

In the provided screen shot, COSPIX and LAN interfaces are each VLANs which share a common LAGG interface.

Things I'd like to see on the dashboard (and this list may increase over time, too)

1) VLAN ID
2) Parent LAGG interface
3) LAGG parent adapters
4) The status of each LAGG parent adapter (UP/DOWN, link speed)

For my example, one possible solution would be to replace "Ethernet autoselect" with the parent interface. This would be ```VLAN-5 on LAGG-1``` for example.

Right now, the LAGGs themselves can be added as interfaces under ```Assign Interfaces``` page, but once they're added, they display no useful information in the ```Interfaces``` dashboard. Instead of "Ethernet autoselect", it would be nice to see all of its parent interfaces as well, along with their link speeds and statuses.

**Comment by botboe** [comment]
Is there some kind of documentation regarding the development / customizing of widgets?

**Comment by AdSchellevis** [comment]
@botboe unfortunately not, no, it's legacy code, which so-far hasn't been very much on our radar other than performing cleanups and small rewrites. 

If your looking for a simple example, this might help https://github.com/opnsense/plugins/tree/master/security/etpro-telemetry/src/www/widgets

The interfaces widget consists of https://github.com/opnsense/core/blob/master/src/www/widgets/widgets/interface_list.widget.php for the static frontend code, which has an update hook here 
https://github.com/opnsense/core/blob/f394fed/src/www/widgets/widgets/interface_list.widget.php#L115

which is being served data on intervals from here https://github.com/opnsense/core/blob/master/src/www/widgets/api/plugins/interfaces.inc

using this to update: https://github.com/opnsense/core/blob/f394fed/src/www/widgets/widgets/interface_list.widget.php#L67

**Comment by botboe** [comment]
Thank you @AdSchellevis, after finishing my radsecproxy-plugin I will give it a try :-)

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/core/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
