### ISSUE TITLE
Strongswan  missing CURL support - OCSP/CRL not working

### ISSUE THREAD

**Issue by fdhuart** [opnsense/core#3929]
Dear OPNsense Team,

It seems that with OPNSense release up to 20.1,
Strongswan is compiled without curl support. 

Would it be then possible to : 
- Add curl support (configure --enable-curl)
- Add through the UI a strictcrlpolicy parameter, which configures the ipsec.conf "setup" section.
- Add through the UI a "CA" config section with configures  the "cacert", "crluri" and "ocspuri" parameters into the ca section of ipsec.conf.

This will implement a proper x509 certificate validation process.

Thank you.
Kind Regards.
Thank you.
Kind Regards.

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/core/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
