### ISSUE TITLE
Sessions stay valid after validity ends if expiry date for voucher is set

### ISSUE THREAD

**Issue by xx4h** [opnsense/core#3930]
If we generate Vouchers and set an expiry date, the expiry date will be set as session timeout, instead of the validity time.

This is due to the following part in the code
```php
if ($row['expirytime'] > 0 && $row['expirytime'] > time()) {
    $this->lastAuthProperties['session_timeout'] = $row['expirytime'] - time();
    return true;    
} elseif (time() - $row['starttime'] < $row['validity']) {
    $this->lastAuthProperties['session_timeout'] = $row['validity'] - (time() - $row['starttime']);
    return true;    
}
```
from [src/opnsense/mvc/app/library/OPNsense/Auth/Voucher.php](https://github.com/opnsense/core/blob/2856288bbf1b42a9b9e06959c308b89f4a208acb/src/opnsense/mvc/app/library/OPNsense/Auth/Voucher.php#L424) because of the precedence of expiry time over validity.

**This is security relevant**

**To Reproduce**
1. Go to **Services** -> **Captive Portal** -> **Vouchers**
2. Click on **Create vouchers**
3. Create Voucher with
  * **Validity**: Custom(minutes) 5
  * **Expires in**: 3 month
  * **Number of vouchers**: 1 (should be irrelevant)
  * **Groupname**: whatever
4. Use the generated voucher, Session won't be invalidated/cleaned up after 5 Minutes, instead it will wait for expiry, so validity will be 3 month

**Expected behavior**
Session will be invalidated after validity has reached its end, not after expiry of the voucher itself.

[✓] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
[✓] I have searched the existing issues and I'm convinced that mine is new.

**Comment by AdSchellevis** [comment]
@xx4h thank you for the thorough report and provided PR. While looking at it, I wondered if the correct session_timeout shouldn't the the lowest of these two values. 

In most circumstances your fix would very likely be better than the current situation, but expirytime could still be triggered before the validity left on the ticket. What do you think?

**Comment by xx4h** [comment]
@AdSchellevis thank you for the quick response. In my opinion the expiry date is only to ensure the voucher is no longer used after this date. If we use the voucher one minute before expiry we should get a session of the length **validity**.

But as you mentioned it, i saw another point. As we don‘t ever have a validity of **forever** we don‘t need to use expiry at all („elseif“ wouldn‘t even ever be used in my PR), so we could remove the „elseif“ completely? What do you think?

Highly appreciate the discussion.

**Comment by xx4h** [comment]
After another „playthrough“ i have to slightly correct my last comment. As we are in the authenticate function, we need to check the **expiry** too. So my new suggestion would be to combine the current „if“ and „elseif“ conditions into one „if“.
So we ensure
1. Voucher is not expired
2. Validity (based on starttime) has not reached its end

I’ll provide a new PR. What do you think?

**Comment by AdSchellevis** [comment]
I think that should do the trick indeed, if you update the PR I'll take a look.

**Comment by xx4h** [comment]
I already updated the commit 36049b47de48337cdcf9c1af66b1ef9a1fb18766

**Comment by AdSchellevis** [comment]
my mistake, totally missed the commit. I think that's almost complete, but `session_timeout` should probably also be influenced by whichever comes first (validity or expiry).

something like:

```
$this->lastAuthProperties['session_timeout'] = min(
       $row['validity'] - (time() - $row['starttime']),
       $row['expirytime'] - time()
);
```

**Comment by xx4h** [comment]
No problem. So you don't agree with me on
> In my opinion the expiry date is only to ensure the voucher is no longer used after this date. If we use the voucher one minute before expiry we should get a session of the length **validity**.

I'm fine with that, just want to get sure, that we discussed it.

**Comment by AdSchellevis** [comment]
I agree there's room for interpretation, although I expect the most logic situation is to stop the session on expirytime as well, which is more or less backwards compatible with the situation we had before too.
