### ISSUE TITLE
[FR] Add a button to force syncing the pfsync table

### ISSUE THREAD

**Issue by mimugmail** [opnsense/core#3932]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[X] I have searched the existing issues and I'm convinced that mine is new.

**Is your feature request related to a problem? Please describe.**
Last time I did an update to a cluster, I updated unit2 first, reloaded the device and wanted to switch over from unit1 to unit2 for preparing the update on unit1.
The problem is, that after a reload the state table of pfsync is different, since long-term connections wont get synchronized. This means if you want a clean failover you have to wait a couple of hours.
Already talked to @AdSchellevis and we didn't found a solution, but now this link (from 2006) popped up:

https://lists.freebsd.org/pipermail/freebsd-net/2006-May/010823.html

**Describe the solution you'd like**
Maybe add a button to VIP status page to force a pfsync, calling the command in the mailing list with the interface name set in HA state sync. This should be enough.

**Describe alternatives you've considered**
The alternative would be to wait a couple of hours.
I'm wondering why this wasn't discussed earlier since running connections would break after a reboot without synching state and switchover

**Comment by AdSchellevis** [comment]
I've seen that link too, but what should be the enforcement command in your opinion? The text seems to be about the normal configuration, or am I missing something?

**Comment by mimugmail** [comment]
Hm, adding the command demotes unit .. seems it's just like enabling and disabling state sync

**Comment by AdSchellevis** [comment]
I don't think we should go there, wouldn't mind if you could force a sync, but I don't think removing pfsync and re-adding it is the best thing todo.

**Comment by mimugmail** [comment]
Yes, not the best approach. I just tested disabling and enabling state sync, but this forces also a quick failover back and forth. I think there's really no good way :(
