### ISSUE TITLE
FIDO/FIDO2/U2F Support

### ISSUE THREAD

**Issue by lattera** [opnsense/core#3935]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[x] I have searched the existing issues and I'm convinced that mine is new.

**Is your feature request related to a problem? Please describe.**
OPNsense currently supports TOTP-based two-factor authentication (2FA). With the advent of webauthn and modern browser support for FIDO/FIDO2/U2F, hardware-based 2FA tokens, like a Yubikey, can now be supported in the browser.

I don't know if/how this would work with other services, like OpenVPN, where TOTP-based 2FA is natively supported. I'm thinking that, like OpenSSH, support in OpenVPN might have to be explicitly developed (and is outside the scope of this feature request, of course).

**Describe the solution you'd like**
Sorry, I kinda included that in the problem description. ;)

**Describe alternatives you've considered**
Not sure there's really much to say here.

**Additional context**
TOTP-based 2FA is a great feature. Expanding 2FA support to include hardware-based tokens would be awesome++.

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/core/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.

**Comment by andreas-p** [comment]
@AdSchellevis I'm willing to contribute and maintain WebAuthn in OpnSense, but I'd need some support: While I'm an experienced programmer, I'm not familiar with OpnSense programming internals, so I'd need some directions. Where should I address my questions for getting implementation hints (which mailing list/forum/?) Do I absolutely need the FreeBSD environment for packaging or can I perform that under Linux or MacOS as well?

**Comment by AdSchellevis** [comment]
hi @andreas-p our docs (https://docs.opnsense.org/develop.html) contain most of the info, our forum is available here https://forum.opnsense.org/, you do need FreeBSD to package software, some tasks can be performed using other operating systems as well (mvc code for example, using our ui_devtools). 

Although to be honest, these types of tasks (authentication) are more complex , need quite some background knowledge on various subjects and might need more guidance than we are able to provide. Don't want to discourage you from opening a PR, but we are quite critical when it comes to code contributions in core, if it doesn't fit our guidelines or long term vision we can't include it.

**Comment by andreas-p** [comment]
@AdSchellevis before I start I would explore the chances for inclusion as official plugin. I don't want to create my own nightmare on the instances I'm responsible for by having to manually fix my stuff after each update.

I believe I know what I do with authentication, and following guidelines won't be a problem either, but I'd like to check against those "long term visions" first.

I got a good clue how to do the verification itself (in library/OPNsense/Auth), as single auth mechanism and stacked with local or ldap; haven't looked so far how to add a list of authorized devices to the user_manager for key management/enrollment.

What are those "various subjects" that I might have to care about? I'd appreciate early guidance and feedback on this.

**Comment by AdSchellevis** [comment]
@andreas-p we're a bit more laid back about plugins (they should follow guidelines though), if all requirements fit within the current auth framework (https://docs.opnsense.org/development/components/authentication.html), you can just start your work there and you should be good. I currently have the feeling that it's not fully possible, but haven't looked into the details to know for sure.

Our time is limited, providing feedback costs a lot of time which we can't always spare. When functionality is clearly contained in a plugin, we (core team) don't have to aim for the same high standards as for our core system. When our (commercial) customers ask, we always make the clear distinction between which software we officially maintain and which packages we advise to use (or stay away from). 

About the instances you're responsible for, just keep in mind that when building a plugin, your responsibility grows 😊 (the original author is responsible for his/her work, when support/development stops and breaks in the future, there's no guarantee functionality remains)

**Comment by andreas-p** [comment]
It appears that there are two issues that can't work as plugin right now:

- There's no extensibility in authgui to query for credential information. Actually, IMHO this should be reworked anyway, because appending the TOTP verification code to the password isn't very user friendly right now; the VC should have its separate input field. This could be implemented as hook in every authenticator "renderCredentialQuestion()" or so, instead of the static generated passwordfld. Most existing modules will render the password field (only once, authgui has to drop duplicates), while TOTP will ask for the verification code, and a webautn authenticator would render "enter key and press button". I'd make a PR for this hook separately/as preparation.
- Listing and adding security keys should naturally go to system_usermanager, but I can't see any means of extensibility here. Any good idea?

**Comment by fichtner** [comment]
I just want to leave a comment here: can we be done with the negativity and "all must be reworked because my use case is different". This argument is beating a dead horse: "the VC should have its separate input field". It's a myth that can't be implemented in any user+password scenario.

**Comment by andreas-p** [comment]
@fichtner you're probably referring to TOTP use cases beyond WebGUI, for services that aren't 2FA aware. Certainly, a second factor input field wouldn't replace the prepend or append scenario for this, it's WebGUI only behaving more passwd manager compatible.

**Comment by fichtner** [comment]
Yes, if the use case is GUI access (not counting fallback issues with SSH/console here) adding a conditional provider for the login screen is probably an easier task than rewriting a generic framework for a single use case.

**Comment by andreas-p** [comment]
@AdSchellevis fair enough. Still not proposing solutions, but evaluating candidates for minimal core impact. Do you have suggestions for sk management?

**Comment by olmari** [comment]
While I'm no dev, I'd so much love to have proper FIDO2 login for Opnsense too... I can't offer much coding help, but I definitely can provide testing help...

**Comment by jorgegv** [comment]
I would also be very willing to do testing for the FIDO/FIDO2 functionality. We are currently migrating away from our current VPN solution, and it's a pity OPNsense does not have this feature.

**Comment by palindsay** [comment]
+1 for FIDO2/U2F support. Hardware security tokens are becoming a global requirement given adoption of Fedramp and other regional laws for Business entities.

**Comment by bracklanna** [comment]
+ 1. Also available to do testing of a possible Opnsense web-gui sk (FIDO/FIDO2/WebAuthn etc.) plugin. I have a number of Yubikey 5-series devices with current firmware.

**Comment by peliilep** [comment]
+1 for FIDO2/U2F support.

**Comment by JamieLaing** [comment]
+1 - FIDO2/U2F would be great

**Comment by NoSilver78** [comment]
+1 - FIDO2/U2F

**Comment by mrtreg** [comment]
+1 - FIDO2/U2F

**Comment by JCalvi** [comment]
+1 - FIDO2/U2F

**Comment by mathias4github** [comment]
+1 - FIDO2/U2F

**Comment by vpx23** [comment]
@andreas-p This could be a starting point for a plugin:

https://developers.yubico.com/pam-u2f/
https://www.freshports.org/security/pam_u2f/

**Comment by zen2** [comment]
+1 - FIDO2/U2F
