### ISSUE TITLE
Outbound NAT rule creation in specific Multi-WAN, Multi-VPN (point-to-point) configurations breaks proper NAT

### ISSUE THREAD

**Issue by johannrichard** [opnsense/core#3936]
I think I might have run into an edge case with OPNSense's way to create Outbound NAT rules for `pf` by using the `(ifname:0)` syntax instead of an IP address (as pfSense does). If I understand the `pf_if.c` code in HardenedBSD and the code in `src/opnsense/mvc/app/library/OPNsense/Firewall/SNatRule.php` correctly, this particular way of creating NAT rules in OPNsense creates a problem when multiple point-to-point interfaces/connections (i.e. VPN and similar ones) sit in the same subnet. 

In this case, only one of these interfaces will have proper routes established. Because of a  workaround for ppp connections implemented in `pf_if.c`, pf will fail to do NAT properly for the other point-to-point interfaces as they lack the routes. (As a starting point, see https://github.com/HardenedBSD/hardenedBSD-stable/blob/4b7aa7e714f8e605d92664b99043ea558da56bfb/sys/netpfil/pf/pf_if.c#L532 for more details). 

In consequence, NAT and PBR over these gateways will not work as expected. 

A possible solution might be that OPNsense sets an IP instead of an `(ifname:0)` when creating the Outbound NAT rules for `pf`, either through a specific setting for the Firewall, or by making a distinction between the two ways the user can select the Interface address in the Outbound NAT UI.  

The problem can most probably be traced down to interactions between (current) OPNSense and Hardened/FreeBSD code. Therefore, I hope you're fine if I don't post tons of screenshots to document but provide the relevant details and necessary steps to recreate the setup that causes the problem below. 

## Details & How to reproduce
 
* OPNSense 20.1 
* Multi-WAN - Multi-VPN setup as per the explanations below
* No fancy settings, essentially disabling any NAT / reflection related settings (although these don't play a role in my understanding)
* NAT & PBR routing over multiple VPN-WAN gateways  is failing for all but the first VPN connection coming up

### How to reproduce

* Create multiple (2+) OpenVPN connections and corresponding interface definitions whose underlying interfaces have an IP in the same subnet (e.g. `10.10.0.0/24`). Disable pulling / adding any routes by the VPN client. Let's assume the two clients end up being `ovpnc3` and `ovpnc5` and interfaces `VPNGW1` and `VPNGW2` respectively 
* Create the corresponding gateways `VPNGW1_IPV4` and `VPNGW2_IPV4` (these can have monitoring disabled, it’s just for the PBR rules)
* Create NAT rules for each of these interfaces where the interface is the respective interface of the VPN client and the translation target is set to “Interface address”
* Create PBR rules that routes some traffic over one gateway, and some over the others (simple setup is sufficient, for example routing traffic for `8.8.8.8` over `VPNGW1_IPV4`, and `9.9.9.9` over `VPNGW2_IPV4`) 

The following snippets contain the `pf` NAT rules created by OPNSense, typical interface definitions, and example states when trying to ping the different targets with PBR.

* `vmx0` is the WAN interface
* `ovpnc5`, `ovpnc3` are the two VPN interfaces
* traffic to `9.9.9.9` is PBR over the gateway `VPNGW1_IPV4` associated to `ovpnc3`, and
* traffic to `8.8.8.8` is routed over the gateway `VPNGW2_IPV4` associated to `ovpnc5`
* `ovpnc5` is the connection that came up first, followed by the one establised through `ovpnc3`

#### NAT rules as per `pfctl -sn` / `/tmp/rules.debug`

* Setup is manual Outbound NAT rules and straightforward, i.e. one NAT rule per gateway/interface, with the translation target being set to "Interface address” or to the alias for the respective interface address in the dropdown (e.g. `VPNGW1 address` or `VPNGW2 address`).
* WAN has its own Outbound NAT rule on `vmx0` 
* `NET_HOMES` is a table containing the local subnets (e.g. `10.0.10.0/24`)
 
```
[...]
nat log on vmx0 inet from <NET_HOMES> to any -> (vmx0:0) port 1024:65535
nat log on ovpnc5 inet from <NET_HOMES> to any -> (ovpnc5:0) port 1024:65535
nat log on ovpnc3 inet from <NET_HOMES> to any -> (ovpnc3:0) port 1024:65535
[...]
``` 
#### Typical interface definitions
Nothing fancy here, established by OpenVPN when bringing up the interfaces. As one can see, both connections share the same interface gateway and sit on the same subnet.  

```
[...]
ovpnc3: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> metric 0 mtu 1505
	options=80000<LINKSTATE>
	inet6 fe80::240:xxxx:xxxx:xxx%ovpnc3 prefixlen 64 scopeid 0x12 
	inet6 fdda:d0d0:xxxx:xxxx::1008 prefixlen 64 
	inet 10.10.0.10 --> 10.10.0.1 netmask 0xffff0000 
	nd6 options=21<PERFORMNUD,AUTO_LINKLOCAL>
	groups: tun openvpn 
	Opened by PID 58825
ovpnc5:
flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> metric 0 mtu 1505
	options=80000<LINKSTATE>
	inet6 fe80::240:xxxx:xxxx:xxx%ovpnc3 prefixlen 64 scopeid 0x12 
	inet6 fdda:d0d0:xxxx:xxxx::1009 prefixlen 64 
	inet 10.10.0.8 --> 10.10.0.1 netmask 0xffff0000 
	nd6 options=21<PERFORMNUD,AUTO_LINKLOCAL>
	groups: tun openvpn 
	Opened by PID 57497
[...]
```

#### pfStates as per ‘pftop’ for two pings to the two servers with PBR over different gateways

* From a machine connected to the firewall, ping `8.8.8.8` and `9.9.9.9`. According to the PBR setup, they should exit via their respective gateway.  
* When inspecting the state tables, we can see that only the traffic over `ovpnc5` (`10.10.0.8`) is properly NAT’ed
* No NAT for the traffic over `ovpnc3` (`10.10.0.10`), which results in the return packets being discarded 

```
all	icmp	10.10.0.8:30350 (10.0.10.247:30511) -> 8.8.8.8:30350	0:0	
all	icmp	8.8.8.8:30511 <- 10.0.10.247:30511	0:0
all	icmp	10.0.10.247:30511 -> 9.9.9.9:30511	0:0	
all	icmp	9.9.9.9:30511 <- 10.0.10.247:30511	0:0
```

### Routing table
As we can see, one of the differences between the two interfaces is a difference related to the routing table. 

When the first VPN connection (`ovpnc5` with IP `10.10.0.8` and gateway `10.10.0.1`) is established, OPNSense will create default routes for this interface, routing all traffic to the VPN gateway `10.10.0.1`) over an interface route (It is my understanding that this is happening for every openvpn connection even if "Don't pull routes" and "Don't add / remove routes" are set as this is related to the interface creation itself and not to the specific OpenVPN Client settings). OPNsense attempts to do so as well for the second connection that's coming up (`ovpnc3` with IP `10.10.0.10` and gateway `10.10.0.1`) but fails to do so as a gateway and subnet route already exist in the routing table. Both connections establish a route to the `lo0` interface for their interface address. 

A typical routing table `netstat -rna4` would thus contains something like the following once the two connections are up:

```
[...]
10.10.0.0/16       10.10.0.1          UGS      ovpnc5
10.10.0.1          link#17            UH       ovpnc5
10.10.0.8          link#17            UHS         lo0
10.10.0.10         link#18            UHS         lo0
[...]
```

This is expected behaviour and, to my understanding, should in principle not be a problem *per se* if PBR is used to route traffic with pf over multiple WAN/VPN connections. 

### Related workaround for point-to-point connections in `pf_if.c`

The rules created by OPNSense via `src/opnsense/mvc/app/library/OPNsense/Firewall/SNatRule.php` are loaded and ingested by `pf`, which will do some processing. Amon other things, it must find the current IP for each interface that was referenced in the rule via the `(ifname:0)` syntax and load this into its internal tables. 

If I am not mistaken, the code responsible for this is found in `sys/netpfil/pf/pf_if.c` in FreeBSD / HardenedBSD, in function `pfi_instance_add`. It contains a workaround for `ppp` connections which are referenced as `(ifname:0)` in the NAT rule *and* which don't have an interface route associated to them in the routing table. This is entirely related to PPP / ICPC and dates back to a bug report in 2004.  

The workaround is applied to all interfaces that: 

* Have the `POINTTOPOINT` flag set, 
* Don't have an alias, and
* Don't have an interface route in the routing table  

Looking at our setup, all but the first VPN interface created as outlined above share these properties (you can see this in the `ifconfig` extract and the routing table extract above). Consequentially, the interface will be skipped when establishing the NAT rule in `pf`. Which explains why Outbound NAT is only working for the first OpenVPN interface but not for the subsequent ones that sit on the same subnet.

``` sys/netpfil/pf/pf_if.c:517
static void
pfi_instance_add(struct ifnet *ifp, int net, int flags)
{
	struct ifaddr	*ia;
	int		 got4 = 0, got6 = 0;
	int		 net2, af;

	IF_ADDR_RLOCK(ifp);
	TAILQ_FOREACH(ia, &ifp->if_addrhead, ifa_list) {
		if (ia->ifa_addr == NULL)
			continue;
		af = ia->ifa_addr->sa_family;
		if (af != AF_INET && af != AF_INET6)
	continue;

/*
		 * XXX: For point-to-point interfaces, (ifname:0) and IPv4,
		 *      jump over addresses without a proper route to work
		 *      around a problem with ppp not fully removing the
		 *      address used during IPCP.
		 */
		if ((ifp->if_flags & IFF_POINTOPOINT) &&
		    !(ia->ifa_flags & IFA_ROUTE) &&
		    (flags & PFI_AFLAG_NOALIAS) && (af == AF_INET))
			continue;
		if ((flags & PFI_AFLAG_BROADCAST) && af == AF_INET6)
			continue;
		if ((flags & PFI_AFLAG_BROADCAST) &&
		    !(ifp->if_flags & IFF_BROADCAST))
			continue;
		if ((flags & PFI_AFLAG_PEER) &&
		    !(ifp->if_flags & IFF_POINTOPOINT))
			continue;
		if ((flags & PFI_AFLAG_NETWORK) && af == AF_INET6 &&
		    IN6_IS_ADDR_LINKLOCAL(
		    &((struct sockaddr_in6 *)ia->ifa_addr)->sin6_addr))
			continue;
		if (flags & PFI_AFLAG_NOALIAS) {
			if (af == AF_INET && got4)
				continue;
			if (af == AF_INET6 && got6)
				continue;
		}
[...]
```

### Additional info / comparison to pfSense where this setup works flawlessly
The same setup (multiple vpn interfaces in the same subnet and PBR) works in pfSense. The difference between thw two: When creating NAT rules, pfSense always uses the IP's of the network interfaces whereas OPNSense will use an interface name (e.g. `(ifname:0)` instead (As found in `src/opnsense/mvc/app/library/OPNsense/Firewall/SNatRule.php`). 

For example, the NAT rules for the same setup look like the following in pfSense:

```
[...]
nat on vmx0 inet from <NET_HOMES> to any -> aaa.bb.xx.yyy port 1024:65535
nat on ovpnc3 inet from <NET_HOMES> to any -> 10.10.0.10 port 1024:65535
nat on ovpnc5 inet from <NET_HOMES> to any -> 10.10.0.8 port 1024:65535
[...]
```

As for OPNsense: If the translation target for the NAT rules is set manually to the (current) IP of the respective VPN client in OPNSense, everything works. However, this is not workable as the interface IP might change when the OpenVPN client disconnects or when the system is rebooted. 

## Possible solution

Provide a way to tell OPNSense to use the interface IP instead of the `(ifname:0)` notation when creating the NAT rules. For example, either as a separate setting for NAT / Firewall rules or by making a difference between choosing "Interface address" or the specific interface alias entry (e.g. like "VPNGW1 address")  where one would keep the `(ifname:0)` syntax and the other one would always use the real, current IP.

**Comment by AdSchellevis** [comment]
The easiest workaround is probably to just add manual outbound rules in case `:0` doesn't translate to the non-aliased address as it should do (https://www.freebsd.org/cgi/man.cgi?query=pf.conf). 

In most cases, selecting `:0` is the more stable choice, which is why I don't expect we're going to switch back to trying to figure out current addresses in the filter code (it has a lot of other downsides).

The `pfi_instance_add` change seems to originate from https://github.com/freebsd/freebsd/commit/a944d25e86e59d66a75ce7a73391be1eb074193b, openbsd doesn't seem to do something similar on their end by the way.

Quickest way to find out if this is indeed your issue, would probably be to build a kernel without the specific section.

**Comment by johannrichard** [comment]
I understand your reasoning for keeping :0, after all it’s supposed to be stable w.r.t. to changes of the interface IP. And yes, I also saw that OpenBSD never implemented this patch although they followed the initial (broken) fix in FreeBSD only to revert it back and leave it as is. 

As for the workaround, I’m of course happy to try anything which doesn’t need changing the code on your side. However, just to be sure I understand you correctly: do you mean manual outbound rules with manually set IP from the interface, set via the UI? This I’ve tried and it would of course work. But it will break every time the interface IP changes so in practice it’s not really usable. 

I’ve also tried to set something else than an IP in the UI (e.g. the ifname) but unless I’m completely blind, this was not accepted in the UI unless it was of course a string like optXip that is then again translated to `(ifname:0)`.

I’ll dig deeper in the various ways how manual rules can be set (e.g. outside the UI if needed) and any hint is welcome.

**Comment by johannrichard** [comment]
Just thinking out loud: 

One way to workaround would be to use an alias table that’s updated with the current IP of the interface from `/tmp/ifname_router`, involving some scripting on my side but in a way that’s reliably updating the IP in the NAT rules. 

This would only break if the interface name changes which should only be the case if I create / delete a new client and/or reassign a different client to an interface.

**Comment by AdSchellevis** [comment]
You could indeed create an alias and maintain it with a script triggered by a `newwanip` event (for example). 

We currently don't support this kind of functionality from the gui (other then creating external aliases and documentation on how to build your own plugins https://docs.opnsense.org/development/backend/legacy.html?highlight=newwanip#configure)

**Comment by johannrichard** [comment]
@AdSchellevis thanks for the suggestions and discussion. I'll look into a plugin and potential other approaches to a sustainable solution (including in the upstream BSD code, I think there were changes to ppp since the change in 2004 and it might be the workaround in pf_if is not needed anymore). I guess you can agree that the issue can be closed.

**Comment by AdSchellevis** [comment]
@johannrichard you're welcome, the fix in FreeBSD seems to be rather old indeed (https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=69954 if I found the correct ticket) afterwards a lot has changed, including a new major version in 2007 (which just pulled this back in).
