### ISSUE TITLE
Warning: Illegal string offset 'lan' in /usr/local/opnsense/scripts/shell/setaddr.php on line 544

### ISSUE THREAD

**Issue by mr44er** [opnsense/core#3939]
[X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[X] I have searched the existing issues and I'm convinced that mine is new.

**Describe the bug**
I get the error message 'Warning: Illegal string offset 'lan' in /usr/local/opnsense/scripts/shell/setaddr.php on line 544' after 'Do you want to enable the DHCP server on WAN? [y/N] n'

**To Reproduce**
Fresh install of OPNsense-20.1-OpenSSL-serial-amd64.img with vm-bhyve-1.3.0 on FreeBSD 12.1-RELEASE-p2.
Nothing fancy, only with 1 NIC (network0_type="virtio-net"), Guided installation, GPT, just standard.
First boot of installation, configuration of just WAN, because of the single NIC.
First login to webinterface, I set firmware to LibreSSL, save, then ticked the update to force.
Update runs up to OPNsense 20.1.1 (amd64/LibreSSL).
Then I did '4) Reset to factory defaults'. After reboot, going freshly through '2) Set interface IP address'
After 'Do you want to enable the DHCP server on WAN? [y/N] n' error message 'Warning: Illegal string offset 'lan' in /usr/local/opnsense/scripts/shell/setaddr.php on line 544'

**Additional context**
Besides that no problems noticed so far

**Environment**
OPNsense 20.1.1 (amd64/LibreSSL)
vm-bhyve-1.3.0 on FreeBSD 12.1-RELEASE-p2
virtio_pci0@pci0:0:4:0: class=0x010000 card=0x00021af4 chip=0x10011af4 rev=0x00 hdr=0x00
    vendor     = 'Red Hat, Inc.'
    device     = 'Virtio block device'
    class      = mass storage
    subclass   = SCSI
virtio_pci1@pci0:0:5:0: class=0x020000 card=0x00011af4 chip=0x10001af4 rev=0x00 hdr=0x00
    vendor     = 'Red Hat, Inc.'
    device     = 'Virtio network device'
    class      = network
    subclass   = ethernet

**Comment by AdSchellevis** [comment]
https://github.com/opnsense/core/commit/1f1776260d1cd189830d308402cd63a1281a28c4 should do the trick, if `$config['dhcpd']['lan']` doesn't exist it complained, the new check should prevent this. Thanks for reporting!
