### ISSUE TITLE
Add possibility to add multiple 2FA token devices or to create emergency backup codes

### ISSUE THREAD

**Issue by BPtLNfxZWo** [opnsense/core#3940]
If you use 2FA and lose your token generator app phone access to GUI is not possible. Would be create to be able to

- register multiple devices (token generator apps)
- or to create during the configuration (strong) backup codes

If possible please take this into consideration

**Comment by Ornias1993** [comment]
It might be worth combining this with:
#3935

And just do one big update to 2FA code...

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/core/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.

**Comment by ericschdt** [comment]
> If you use 2FA and lose your token generator app phone access to GUI is not possible

You can enter the TOPT secrete key at multiple devices. Eg besides Android I use KeepassXC as a backup on the desktop.
