### ISSUE TITLE
Interface name issues

### ISSUE THREAD

**Issue by Kimotu** [opnsense/core#3942]
[X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[X] I have searched the existing issues and I'm convinced that mine is new.

**Describe the bug**
I created a new vlan (other|vlan), set as description 'DMZ-2: Webserver', then created a new interface in assignments and wondered about the auto-created name '[DMZ-2: Webserver]'. Up to 19.7. the new interface was just named OPT_XX - dashes, spaces and colons where not possible as interface name, yet.

First I thought to rename my existing interfaces, since dashes look better than underscores and colons are useful as separator, but then I decided to use the existing scheme and named it 'DMZ_2'.

But whatever I entered as description (=name), the interface name was NOT changed as long as I just changed the description and pressed save. When I checked 'enabled' AND changed interface description, the name was changed.

Now as the interface is enabled, I can just change the interface name again, but no colon, space or dash. When I use one of those characters, it gets removed when saving. So I assume, the previous auto-created name [DMZ-2: Webserver] derived from the vlan description, lacks this character substitution.

**To Reproduce**
1. Create new vlan (interfaces|other types|vlan) with tag and name like 'DMZ-1: Test' (colons, spaces and dashes)
2. Create new interface (interfaces|assignments), select your new vlan as new interface and don't change the loaded vlan description
3. Press the add (+) button
4. Interface named [DMZ-1: Test] should be created
5. Do not enable it, just change the description (=interface name) and press save
6. name should not be changed
7. Enable interface and  change description (=interface name) and press save
8. name should be changed
9. Set 'invalid' name like before (with colons, spaces, dashes) and save
10. Now invalid characters should removed

Both carp members where I added a vlan to a lagg device, had this issue.

**Expected behavior**
Either characters like space, dash, colon are valid as interface name, I expect that I can change existing interfaces to names including it. Or I expect that new created interfaces are either named OPT_XX again or are named with those invalid characters removed ('DMZ1Test').

But no mix-mode. Otherwise i assume there will raise other issues if the system expects interface names without these characters, but with this bug|trick, it is possible to create interfaces with these characters.

**Environment**
OPNsense 20.1-amd64
FreeBSD 11.2-RELEASE-p16-HBSD
OpenSSL 1.1.1d  10 Sep 2019

**Comment by AdSchellevis** [comment]
https://github.com/opnsense/core/commit/2a80d1a8a2c82be409f211fcb36132204d1ac64e aligns behaviour for the description field.  Leftover from https://github.com/opnsense/core/pull/3808,  copy was introduced with https://github.com/opnsense/core/commit/ee542d28221f7b20dfa53e92abb0c19749b8c7b6
