### ISSUE TITLE
DHCP leases with whitespace hostname writes invalid entries to unbound dhcpleases.conf

### ISSUE THREAD

**Issue by smallsam** [opnsense/core#3944]
**Describe the bug**
When Register DHCP leases option is enabled in Unbound DNS server, any DHCP leases with a whitespace hostname will end up writing invalid entries like:

local-data-ptr: "192.168.3.183 .dyn.home"
local-data: ".dyn.home IN A 192.168.3.183"

to /var/unbound/dhcpleases.conf

This prevents unbound from starting showing errors like:
error: error parsing local-data at 2 '.dyn.home IN A 192.168.3.183': Empty label
error: Bad local-data RR .dyn.home IN A 192.168.3.183
fatal error: Could not set up local zones

**To Reproduce**
Add lease to /var/dhcpd/var/db/dhcpd.leases
like:
lease 192.168.3.183 {
  starts 4 2020/02/13 12:18:05;
  ends 3 2020/12/09 12:18:05;
  cltt 4 2020/02/13 12:18:05;
  binding state active;
  next binding state free;
  rewind binding state free;
  hardware ethernet 7c:69:aa:aa:aa:aa;
  set vendor-class-identifier = "Cisco AIR-CT2504-K9";
  client-hostname " ";
}

**Expected behavior**
I don't expect a DNS entry written when the hostname is just whitespace.

**Relevant log files**
If applicable, information from log files supporting your claim.

**Additional context**
The UI trims the whitespace hostname in the status_dhcp_leases.php view so it looks like other leases with no hostname.
However other leases without a hostname omit the client-hostname stanza in the lease file and they are not written out to the unbound conf. This whitespace hostname does however. For background, this was a factory reset Cisco AIR-CT2504-K9 which generated this DHCP request.

**Environment**
OPNsense 20.1.1-amd64
--

**Comment by AdSchellevis** [comment]
@smallsam https://github.com/opnsense/core/commit/49afa0595e3992e80cb9ebe1b9a30d9556d38c47 should fix it, thanks for the report!

To test, just install the patch using :
```
opnsense-patch 49afa05
```

and restart unbound from the services page (which should restart unbound_dhcpd.py as well).
