### ISSUE TITLE
20.1 changed dhcpv6 staticmapping value domain into domainsearchlist --> auto-DNS-registration fails

### ISSUE THREAD

**Issue by Kimotu** [opnsense/core#3945]
[X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[X] I have searched the existing issues and I'm convinced that mine is new.

**Describe the bug**
In previous versions before 20.1 you could add static dhcpv6 leases and activate the option 'Register DHCP static mappings' in unbound. No need to add an extra DNS record.

In 20.1 the dhcpv6 static-leases changed the domain entry to domain-searchlist. Thus no DNS entries are created. Entries created with 19.X and migrated by upgrade to 20.1. still have the correct domain value in configuration and get registered.

ATM I manually have to download configuration, add the <domain> XML entry and restore DHCP configuration. 

Previously:
```
<staticmap>
        <duid>00:01:23:45:67:89:01:12:34:56:78:90:aa:bb</duid>
        <ipaddrv6>2002:db::1</ipaddrv6>
        <hostname>www</hostname>
        <descr>Webserver</descr>
        <domain>dmz.domain.tld</domain>
/staticmap>
```
created an AAAA record with www.dmz.domain.tld IN AAAA 2002:db::1

In 20.1:

```
 <staticmap>
        <duid>00:01:23:45:67:89:01:12:34:56:78:90:aa:bb</duid>
        <ipaddrv6>2002:db::1</ipaddrv6>
        <hostname>www</hostname>
        <descr>Webserver</descr>
        <domainsearchlist>dmz.domain.tld;domain.tld</domainsearchlist>
</staticmap>  
```

**To Reproduce**
Create static dhcpv6 lease and activate option to register DHCP leases in unbound.

**Expected behavior**
Possibility to add a domain in static lease configuration and get correct DNS records auto-created by unbound.

**Additional context**
If really needs to set an extra domainsearch-list per host, then at least reactivate the domain option in lease configuration.

**Environment**
OPNsense 20.1.1-amd64
FreeBSD 11.2-RELEASE-p16-HBSD
OpenSSL 1.1.1d 10 Sep 2019

**Comment by AdSchellevis** [comment]
Seems to be introduced with https://github.com/opnsense/core/issues/2336, maybe better ask @maurice-w how this was intended to work. I'm not a huge fan of these application dependancies, since they always have a higher risk of breakage. 

We have a couple of options available in my opinion:

- Register the dns domain with the entry, which would re-add both fields as extra
- Traverse the `domainsearchlist` items and register them all, if that makes sense.
- Ditch the feature and remove the code in unbound, change description that this feature only applies to ipv4 .

**Comment by maurice-w** [comment]
Right, I didn't consider the unbound dependencies. I'll take a look.

**Comment by maurice-w** [comment]
I can't reproduce that _no_ DNS entries are created for new static mappings. However, the system domain is used for these DNS entries, not the 'Domain search list' domain(s). @Kimotu, can you confirm?

@AdSchellevis, I suggest we re-introduce the `<domain>` option in the `<staticmap>` section of the XML and add same code to `services_dhcpv6_edit.php` which sets it to the first domain in the domain search list. This would avoid changes to the unbound code and maintain some backward compatibility.

**Comment by AdSchellevis** [comment]
@maurice-w I'm ok with that, as long as the help text explains the use-case

**Comment by Kimotu** [comment]
@maurice-w Sorry for late reply. Registering all domains in search path does not make much sense. But registering the first one is ok. But if a `<domain>` option exists, use it preferably for backward compatibility. I added most static leases with 19.7 and all entries have `<domain>` option, but no `<domainsearchlist>`, since it did not exist prior 20.1.

Else the upgrade process would have to rewrite the mappings, but for 20.1 this is too late.

**Comment by maurice-w** [comment]
@Kimotu, using the first domain in the `domainsearchlist` or the `domain` as a legacy fallback is exactly what #3946 does. See the discussion there. It also migrates `domain` to `domainsearchlist` if you edit a static mapping created in pre-20.1. No bulk migration though.
