### ISSUE TITLE
Assign static route to gateway group

### ISSUE THREAD

**Issue by darkain** [opnsense/core#3947]
Pretty simple concept (maybe complex to implement?)

Allow assigning a static route to a gateway group rather than just a single gateway. This way if a particular gateway goes down (or is still up but has high latency or high packet loss), the static route will shift to the backup gateway.

And down the line, this would be a first step into getting static route ECMP as well (that'll be another ticket for another day tho)

**Comment by AdSchellevis** [comment]
For static routing we're constraint by what route(8) has to offer (https://www.freebsd.org/cgi/man.cgi?route), policy based routing is a different concept using pf's route-to constructs.

When opening future tickets, please consider using our templates, this avoids incomplete labels and increases the chances of receiving feedback.

**Comment by darkain** [comment]
The policies already exist otherwise though. Gateway reliability is already tracked via dpinger. Gateway groups already take this status information into consideration. I don't think it would be that hard to add a hook into the way gateway groups already handles this to add/remove static routes based on gateway availability.  Unless you're suggesting that these hooks don't even exist in the first place? And that anything and everything gateway groups currently does is handled at the lower os/service layer?

**Comment by AdSchellevis** [comment]
Members of a group can share traffic (see `man pf.conf`). We definitely do not consider dropping static routes other than the default gateway switching which is already in there. Static means static...  You could take a look at dynamic routing protocols, which are likely more suited for these use-cases.

Unfortunately FreeBSD doesn't support route metrics, which might be a fit without trashing the routing table on every disruption.

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/core/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
