### ISSUE TITLE
Password for OpenDNS service stored in plaintext in config.xml file

### ISSUE THREAD

**Issue by nmataka** [opnsense/core#3948]
I apologize if this isn't the write place to post this, but it seems to fit...

Anyway, my system info:
OPNsense 20.1.1-amd64
FreeBSD 11.2-RELEASE-p16-HBSD
OpenSSL 1.1.1d 10 Sep 2019

Had to made an edit to the config.xml file after accidentally deleting the wrong interface, and I noticed that when the service is configured via the GUI, the password for this field is written to the config.xml file in plain text. I noticed other places within the file where the password was encrypted, but not here, so I figured this was most likely a bug/oversight?

**Comment by AdSchellevis** [comment]
It needs the password to authenticate, unlike most other stored passwords which are stored hashed since they are never needed in plain text to authenticate to something else.

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/core/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
