### ISSUE TITLE
Traffic Shaper TCP (ACK only) catches all tcp traffic 

### ISSUE THREAD

**Issue by maxfield-allison** [opnsense/core#3954]
Issue is referenced in this thread on the forums: https://forum.opnsense.org/index.php?topic=6004.0
**Describe the bug**
The traffic shaper protocol option "TCP (ACK packets only)" captures all tcp traffic instead of only ACK packets. The inverse is also true for "TCP (Non-ACK packets)"
**To Reproduce**
1. In Traffic Shaper>Settings create an upload pipe less than ISP bandwidth on WAN interface.
2. Create a rule pointed at the pipe with protocol TCP (ACK packets only) selected 
3. Apply the rule and reset states 
4. Run an upload or speedtest

**Expected behavior**
Only TCP ACK packets are captured and forwarded

**Environment**

OPNsense 20.1.1 (amd64, OpenSSL).
Intel i5
igb and em NIC drivers

**Comment by AdSchellevis** [comment]
Counters are running on my end (speedtest slows down as well). 
```
# ipfw show | grep tcpflags
60003 34280 36812136 pipe 10000 tcp from any to any tcpflags ack via le1 // wan: 5 Mbps
```

```
# ipfw show | grep tcpflags
60003     98      5660 pipe 10000 tcp from any to any not tcpflags ack via le1 // wan: 5 Mbps
```

**Comment by maxfield-allison** [comment]
Forgive my ignorance, Does this mean you've reproduced the issue?

**Comment by AdSchellevis** [comment]
No problem, I couldn't reproduce it at my end, matching the traffic seems to be working fine on my machine.  You probably have to dig a bit deeper in `ipfw` to inspect if traffic is matching or it's accidentally being affected by one of the other rules.

**Comment by maxfield-allison** [comment]
Let me clarify a difference from my original post; I forgot to mention I'm using a weighted queue between the pipe and rule. I have the tcp ack only targeting a queue which is then fed to the upload pipe I set for 5Mbps to ensure ack packets always have bandwidth. These are now the only rule and queue for the pipe. Swapping the target for the high priority queue from the 5Mb priority upload pipe to the 40Mb lan upload pipe makes the speedtest show the correct bandwidth. Disabling the ack only rule also shows the correct 40mbps on the speedtest. only when I'm pointing the rule and queue at the 5mb pipe am i seeing the speedtest drop to 5mbps. I admit, I could be mistaken but i don't think the speedtest only uses ack packets. dslreports.com/speedtest
![image](https://user-images.githubusercontent.com/42394355/75578932-ccdb2500-5a32-11ea-8e2b-23b68d9de53f.png)

![image](https://user-images.githubusercontent.com/42394355/75578980-dd8b9b00-5a32-11ea-907e-718a45cf9db6.png)

![image](https://user-images.githubusercontent.com/42394355/75579018-ed0ae400-5a32-11ea-8a99-1cb0acde9f54.png)

![image](https://user-images.githubusercontent.com/42394355/75579054-ff851d80-5a32-11ea-9428-3988ad45c12a.png)

**Comment by henwoodenator** [comment]
I'm also seeing the exact same issue, I have a weighted setup, one pipe down and one up. 1, 50 & 100 weighted queues for each direction. Rules direct traffic to the appropriate queue as per their priority. ACK packets are directed to the high priority queue.
I've got HTTP & HTTPS rules which aren't doing anything, because the TCP(ack only) rule takes all the traffic.
Using OPNSense version 20.1.6

**Comment by chrissi323** [comment]
I'm also seeing this exact issue with OPNsense 20.1.7

**Comment by maxfield-allison** [comment]
Quick update, After digging through the forum https://forum.opnsense.org/index.php?topic=17372.0

to Summarize 

> 
> it matches all tcp traffic with ACK set, which is indeed most of the traffic.
> M0n0wall used the same technology (tcpflags in ipfw), but offered the option to select or deselect any of them.
> 
> It was added a very long time ago (https://github.com/opnsense/core/issues/528), but doesn't look very useful indeed.
> 
> There are a couple of options, open a feature request to add flags as an option, so you can select which ones need to be set, maybe accompanied by a switch to expect exactly these flags (negate the rest). 
> Selecting both which must be set and which may not be set (like m0n0 did) could also be an option, but in our layout can be a bit confusing.
> 
> The other option is to fix the flags on this option to something more logical (tcpflags ack,!psh ?)
> 
> 

> The current code:
> Code: [Select]
> tcpflags ack
> 
> Ad suggested:
> Code: [Select]
> tcpflags ack,!psh
> which I think would be an improvement.
> 
> My suggestion would be to try and narrow it down to packets doing nothing but ack by excluding larger payloads. E.g.:
> Code: [Select]
> tcpflags ack iplen 52

**Comment by maxfield-allison** [comment]
#4132 addresses this issue and there are workarounds posted in the comments until/if the change is merged
