### ISSUE TITLE
StartTLS authentication won't work with LDAP/AD

### ISSUE THREAD

**Issue by mamalos** [opnsense/core#3956]
Hi,

I tried to use LDAP authentication on OPNsense 20.1-amd64 using a samba4 AD domain (on an Ubuntu server 18.04) by following the [documentation's how-to](https://docs.opnsense.org/manual/how-tos/user-ldap.html) with no luck, despite having "installed" the AD's CA pem certificate using **System->Trust->Authorities**. [Here's](https://pasteboard.co/IWC50WN.png) the OPNsense config I used (which is basically what the how-to suggests, with the specification that _StartTLS_ is selected).

"No luck" means that when I was clicking on **Authentication containers** _Select_ button, the list of containers was always empty (so, the form was never completed).

When I was running **ldapsearch** manually from OPNsense shell, by executing the following command, everything worked fine:

```
ldapsearch -h 192.168.2.120 -D "CN=Administrator,CN=Users,DC=example,DC=com" -W -b "DC=example,DC=com" -s sub -x -ZZ -LLL
```

Once I made TLS authentication over LDAP optional in **smb.conf**, by adding:

```ini   
client ldap sasl wrapping = sign
ldap server require strong auth = no
```

in the **[global]** stanza, things worked normally, regardless of the value of **Transport** in the GUI (_StartTLS_ or _TCP-Standard_). When I enforced TLS authentication back again, _StartTLS_ stopped working, which leads me to believe that OPNsense never uses _StartTLS_ - since both options (_StartTLS_ and _TCP-Standard_) work fine when TLS authentication is optional whereas none of them works when TLS is enforced.

Unfortunately, since it's samba LDAP and not OpenLDAP (where logs are very verbose), I have no logs to confirm my assumption. 

**Steps to reproduce**
_System->Trust->Authorities:_
1. Click **+Add**
2. Type something in **Descriptive name**.
3. Copy samba's CA pem certificate in **Certificate data** (on my samba DC, it was in **/var/lib/samba/private/tls/ca.pem**).
4. Click **Save**.

_System->Access->Servers:_ Use relevant info from your domain as shown in the [link](https://pasteboard.co/IWC50WN.png) I provided previously.

**Versions**
OPNsense 20.1-amd64
Ubuntu 18.04.1 LTS Server
samba: 4.7.6+dfsg~ubuntu-0ubuntu2.15

**Additional info**
Before filing this issue, this problem has been discussed in IRC (#opnsense) and has been confirmed by one more person.

**Last working version**
I don't think I can use **opnsense-revert** in this case, because there doesn't seem to be something wrong with the installed libaries/packages (**ldapsearch** works just fine with TLS). It just seems to be a GUI issue.

**Comment by EHRETic** [comment]
Hi there,

I seem to have the same kind of issue with OPNsense 20.1.2. Can't get AD to authenticate.
I still get "opnsense: LDAP bind error [,Can't contact LDAP server]" when trying on SSL. TLS and without encryption are not working and will probably never on such platform.

AD server : Windows 2019 core "hardened" with CIS settings (https://www.cisecurity.org)
Certificate : I've imported the CA's certificate that sign all certificates in my environement in the trust section.

Patch c4fba1c seems to change anything, but I don't know if it should on 20.X... (mentionned in issue 3445)

I looked at my security GPOs, and I've that if I look at "LDAP" keyword:
- Domain controller: LDAP server signing requirements | Require signing
- Network security: LDAP client signing requirements | Negotiate signing
- Extended Protection for LDAP Authentication (Domain Controllers only) | Enabled |  Configure LdapEnforceChannelBinding Enabled, always (recommended)

Don't know how this could affect the behavior but I confirm the above. Any clue ? :-)

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/core/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
