### ISSUE TITLE
DHCP broken when having vlans with suricata enabled

### ISSUE THREAD

**Issue by L1ghtn1ng** [opnsense/core#3957]
For context please see the following Twitter thread https://twitter.com/jay_townsend1/status/1232411111150039042?s=19

**Comment by L1ghtn1ng** [comment]
The is is the same as #3182 issue and I am on opnsense 20.1.1 on A10 gen1

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/core/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
