### ISSUE TITLE
download_geoip.py does not respect CAs in System: Trust: Authorities 

### ISSUE THREAD

**Issue by paul-palmer** [opnsense/core#3958]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[-] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[-] I have searched the existing issues and I'm convinced that mine is new.

**Is your feature request related to a problem? Please describe.**

Since the addition of the GeoIP setting tab, I have been unable to download GeoIP data from our server. From the command line if I run download_geoip.py I get:

> OpenSSL.SSL.Error: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')]

We are downloading the GeoIP data from an internal server whose certificate is signed by an internal CA. This CA is listed in "System: Trust: Authorities", but download_geoip.py does not seem to honor that. I have temporarily replaced the certificate with one generated by Let's Encrypt and verified that the data then successfully downloads, so I am confident that this is the only problem. Unfortunately, keeping a Let's Encrypt certificate on this server is not a viable long-term solution for us.

**Describe the solution you'd like**
I would like to be able to download GeoIP data from a server whose certificate is signed with an internal signing certificate.

**Describe alternatives you've considered**

I verified that our internal CA is being populated in /etc/ssl/cert.perm. I would like either see download_geoip.py honor /etc/ssl/cert.perm or "System: Trust: Authorities" also populate CAs whereever download_geoip.py is looking for them.

**Additional context**

**Comment by fichtner** [comment]
Long story short: https://github.com/certifi/python-certifi/issues/22

We use Python to download the files.

**Comment by paul-palmer** [comment]
would it be hard to use system to invoke curl to download the file and then have the python script read the file from disk instead?

**Comment by AdSchellevis** [comment]
Exiting python to download a file using curl will get hackery pretty quickly unfortunately, I don't think the python requests library supports other options than `certifi` at the moment and we don't want to solve the same kind of problem in multiple areas.

We're open for suggestions, as long as they can be implemented generically and don't turn into a lot of magic.

**Comment by paul-palmer** [comment]
What about using pycurl instead of certifi? It would allow you to specify CA locations.

**Comment by jhermann** [comment]
When using `requests`, things are easy: [CA Certs Handling](https://github.com/jhermann/jhermann.github.io/wiki/PythonHowto#ca-certs-handling)

**Comment by AdSchellevis** [comment]
Looking at our forum, I was under the impression that people already tried that https://forum.opnsense.org/index.php?topic=6679.0 , we do use python `requests` indeed (and don't intend switching to something else currently).  

If someone wants to try this, the following should be enough to add REQUESTS_CA_BUNDLE to the environment:
```
set REQUESTS_CA_BUNDLE="/usr/local/openssl/cert.pem"
```

**Comment by fichtner** [comment]
I would prefer /etc/ssl/cert.pem for future compatibility (this is where FreeBSD looks for certificates as well)

**Comment by jhermann** [comment]
There is no simple / single answer, just lists: https://serverfault.com/a/722646

**Comment by AdSchellevis** [comment]
so things aren't easy.... (when using `requests`)

**Comment by jhermann** [comment]
Depends on what *hard* things you've seen in the wild – setting an env var counts as easy in my book. ;)

**Comment by AdSchellevis** [comment]
@jhermann just repeating your own words, first it's simple, then there's no simple answer. It would be more meaningful if one just tried something out on OPNsense, just my two cents....

**Comment by AdSchellevis** [comment]
should likely work since https://github.com/opnsense/core/commit/ae3650587394f0fb6d3c129ae00a7f5d0b079dc7
