### ISSUE TITLE
Logging during leap day

### ISSUE THREAD

**Issue by JeniCzech92** [opnsense/core#3959]
Version: running latest OPNsense 20.1.1-amd64,

Description: Logging feature of many components like surricata, strongswan (but not all of them) was not working during the leap day - after accessing WebGUI page, it was stuck at loading, unless the log was freshly cleared (In that case it correctly reported clear log). I have checked the actual log files and they were corrupted so it's not an issue of the web front end apparently, but some of the components clearly cannot work correctly with time during such day and in the end it might have possibly other side effects.

How to reproduce: Run the firewall during a leap day and open logs (or make it think it is a leap day)

**Comment by JeniCzech92** [comment]
Seems like this would fix it for next years: https://github.com/opnsense/core/commit/e3774ddfb6caaa48727029241a8486065d3c56a8

**Comment by AdSchellevis** [comment]
@JeniCzech92 thanks for creating the issue and referring to the fix from yesterday, good to have a link here.
