### ISSUE TITLE
captive portal: missing redirect on radius authentication

### ISSUE THREAD

**Issue by fichtner** [opnsense/core#396]

**Comment by jsp91470** [comment]
Any update on this?  I have opnsense just about working but this is a show-stopper for us.  No description of this bug, but if it's getting a blank page after authenticating via RADIUS, that's what we're seeing.  Everything works fine using local authentication.

**Comment by AdSchellevis** [comment]
@fichtner probably picked this one of our forum.

We're in the process of rewriting the captive portal completely for the 16.1 release, I think this https://github.com/opnsense/core/commit/8f5a725fcf99ba4d64ef4a40f6dd111b36c55e4a is the radius issue, but I don't have a setup available to test now.
If you have time to test if this solves the redirect, that would be very nice.

**Comment by fichtner** [comment]
I'll keep track of the bug reports in the hopes we get more collaboration. This was all that the info that got previously. Ultimately we need users to report these things and describe them so can find them and have a way to verify they are working afterwards.

Fix looks ok, thanks, will be in 15.7.16. :)
