### ISSUE TITLE
Change Linsten queue size for OpenVPN

### ISSUE THREAD

**Issue by hvalencia89** [opnsense/core#3960]
The Queue size for OpenVPN is 32 and in the system is other

![imagen](https://user-images.githubusercontent.com/46072913/75645161-758fad00-5c0a-11ea-9959-465adf7015fe.png)

What is the procedure for change size?

![imagen](https://user-images.githubusercontent.com/46072913/75645071-3e210080-5c0a-11ea-8320-c32c5295c1a5.png)

Regards, Humberto Valencia Toxqui.

**Comment by AdSchellevis** [comment]
you can change sysctl tunables in system tunables  https://docs.opnsense.org/manual/settingsmenu.html#tunables

**Comment by hvalencia89** [comment]
Hello AdSchellevis,

I have modified the parameter and restart the firewall
But I still get the same result

![imagen](https://user-images.githubusercontent.com/46072913/75716622-2e023300-5c95-11ea-9f3f-f85e32b6167d.png)
![imagen](https://user-images.githubusercontent.com/46072913/75717581-fd22fd80-5c96-11ea-8eb8-ee0606ccf65f.png)

![imagen](https://user-images.githubusercontent.com/46072913/75717626-17f57200-5c97-11ea-87b6-0eb7f24769e8.png)

The OpenVPN is 32 afther of  value change 
 sysctl kern.ipc.soacceptqueue=256

Regards, Humberto Valencia Toxqui

**Comment by AdSchellevis** [comment]
sysctl works like a charm on my end, just add and apply:
![image](https://user-images.githubusercontent.com/9783985/75752455-0ceb2200-5d29-11ea-846e-c5c974c74d8c.png)

```
# sysctl -a | grep soaccep
kern.ipc.soacceptqueue: 256
```

**Comment by hvalencia89** [comment]
Hello  AdSchellevis ,
The change in variable accept queue is OK and because in listen queue is 128 and Open VPN is 32
What is the variable for change the value in the queue?

![imagen](https://user-images.githubusercontent.com/46072913/75795782-64dd5500-5d38-11ea-9611-15d475e083b6.png)

Regards, Humberto Valencia Toxqui.

**Comment by AdSchellevis** [comment]
I was only responding to the sysctl question, the specific queue sizes are likely application settings.

**Comment by hvalencia89** [comment]
Hello AdSchellevis,
I change value of varible kern.ipc.somaxconn

![imagen](https://user-images.githubusercontent.com/46072913/75802039-b0483100-5d41-11ea-9f4e-885248a6a6fe.png)

But not change value in OpenVPN queue

Suggestion or dependeci in  listen queue OpenVPN

Regads, Humberto Valencia Toxqui

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/core/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
