### ISSUE TITLE
DHCP lease does not show in multiple VLANs

### ISSUE THREAD

**Issue by jwoodard80** [opnsense/core#3962]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[-] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[-] I have searched the existing issues and I'm convinced that mine is new.

**Describe the bug**
I'm not sure I described the problem correctly. However, I had a device that was static assigned in one VLAN (VLAN0 -> 10.20.30.x), however, was accidentally connected in another (VLAN 90 -> 10.20.90.x). The logs showed that the device was given a IP in VLAN90, however, it did not appear in the leases.

I spent several minutes trying to figure out what was going on and checking logs. I finally tested by deleting the static assigned and refreshing. After refreshing, my IP lease in the incorrect VLAN appeared. 

I am unsure if this is by design, however, I don't believe it should be. When I click "Leases" I'm assuming that i'm going to be seeing ALL leases. I should be able to see that a MAC is appearing in both VLANs as this is what we display the online/offline for. If an address appears online in VLAN "X" it should (depending on lease times, etc) be offline VLAN "Y". 

**To Reproduce**
1. Create 2 VLANs
2. Create a static lease in VLAN 1 for device
3. Bring device up in VLAN 2
4. Device will not show in the "Leases" page in VLAN 2 but will continue to show offline in VLAN 1
5. However, the device can be looked up in the Logs

**Expected behavior**
Leases should show ALL leases including duplicates. In the above example I would expect to see an offline static lease in the correct desired location but ALSO a DHCP lease in the incorrect VLAN.  

**Environment**
OPNsense 20.1.3-amd64
FreeBSD 11.2-RELEASE-p17-HBSD
OpenSSL 1.1.1d 10 Sep 2019
CPU Type Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz (4 cores)

**Comment by jwoodard80** [comment]
Can someone please let me know what I can do to change this from "incomplete"? Is this something I have left out?

**Comment by jwoodard80** [comment]
I have edited the ticket to hopefully make it somehow complete.

**Comment by klausagnoletti** [comment]
Just wanted to chip in on this. I have the same problem, but not related to VLANS, I think. I have a 1-physical NIC (opnsense on a NUC) and a managed switch though. My VLAN30 i my LAN where I have all my clients. Here I experience that I can't see or edit all current DHCP leases. Some just aren't there. For instance, there is an expired lease for my laptop (flaplet) on 10.20.30.50 showing up in the GUI (which I can't edit or delete). This lease isn't effectuated - instead the client gets a random ip at 10.20.30.129. I have a few other examples. All leases are created a lot of releases ago on a fw that has been continually updated for at least 2-3 yrs. Maybe that is related somehow.

**Comment by jwoodard80** [comment]
Can anyone let me know if any progress has been made on this? @AdSchellevis is there anything else I can do to help resolve this?

**Comment by AdSchellevis** [comment]
it's a community support ticket, by my knowledge `dhcpd` doesn't know which interface is involved, all leases are collected in  `/var/dhcpd/var/db/dhcpd.leases`

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/core/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.

**Comment by dj0abr** [comment]
Hi,
just found this closed issue, I have the same problem with OpnSense 21.1.1
I have 3 VLANs.
Services: DHCPv4: Leases only shows leases from the first VLAN.
Anyway, the DHCP servers on the other VLANs are working fine, but the leases are not shown in the list.

**Comment by marjohn56** [comment]
Can only say that they all show up find on mine
`



QPVLAN | 10.4.12.3 | 24:5e:be:00:0b:ddQNAP Systems, Inc. | LQNAP | QNAP Server |   |   |   | static |  
QPVLAN | 10.4.12.5 | 00:16:01:0a:58:24BUFFALO.INC | Terrastatiion |   |   |   |   | static |  
QPVLAN | 10.4.12.7 | 00:15:5d:0c:0a:01Microsoft Corporation | freenas |   |   |   |   | static |  
QPVLAN | 10.4.12.9 | 00:15:5d:0c:0a:00Microsoft Corporation | HyperV-Win10 |   |   |   |   | static |  
QPVLAN | 10.4.12.10 | 00:1b:21:35:2b:d7Intel Corporate | Server-2016 |   |   |   |   | static |  
QPVLAN | 10.4.12.26 | 00:10:7f:40:6a:a6CRESTRON ELECTRONICS, INC. | MC3-7F406AA6 |   |   |   |   | static |  
QPVLAN | 10.4.12.29 | 02:42:a3:00:c8:93 | DSLWebstats | Webstats on QNAP Container |   |   |   | static |  
QPVLAN | 10.4.12.30 | 00:0c:29:ed:f9:92VMware, Inc. | Server |   |   |   |   | static |  
QPVLAN | 10.4.12.31 | 00:15:5d:0c:0a:12Microsoft Corporation | mailgate | Mail Cleaner |   |   |   | static |  
QPVLAN | 10.4.12.36 | b0:e8:92:8f:1c:52Seiko Epson Corporation | EPS-PRINTER |   |   |   |   | static |  
QPVLAN | 10.4.12.37 | 98:4b:e1:3f:49:4cHewlett Packard | LORIPRINTER |   |   |   |   | static |  
QPVLAN | 10.4.12.48 | 60:a4:4c:b5:45:3eASUSTek COMPUTER INC. | Lori-PC2 |   |   |   |   | static |  
QPVLAN | 10.4.12.69 | 70:85:c2:a5:07:7dASRock Incorporation | Martins-PC |   |   |   |   | static |  
QPVLAN | 10.4.12.70 | 98:da:c4:66:92:f0TP-LINK TECHNOLOGIES CO.,LTD. | TPLINK-WAP-MS |   |   |   |   | static |  
QPVLAN | 10.4.12.71 | 98:da:c4:c2:01:d2TP-LINK TECHNOLOGIES CO.,LTD. | TPLINK-WAP-LOFT |   |   |   |   | static |  
QPVLAN | 10.4.12.72 | 50:d4:f7:3c:ad:f0TP-LINK TECHNOLOGIES CO.,LTD. | TPLINK-WAP-HALL |   |   |   |   | static |  
QPVLAN | 10.4.12.101 | 2c:fd:a1:26:0c:35ASUSTek COMPUTER INC. | android-3588147a82cc70fe |   | 2021/03/06 10:37:50 UTC | 2021/03/06 12:37:50 UTC |   | active |  
QPVLAN | 10.4.12.105 | 2c:fd:ab:42:0d:d8Motorola (Wuhan) Mobility Technologies Communication Co., Ltd. | PictureFrame |   | 2021/03/06 10:28:05 UTC | 2021/03/06 12:28:05 UTC |   | static |  
QPVLAN | 10.4.12.114 | 80:c7:55:df:ce:66Panasonic Appliances Company | COM-MID1 |   | 2021/03/06 10:33:46 UTC | 2021/03/06 12:33:46 UTC |   | active |  
QPVLAN | 10.4.12.149 | b0:3e:51:88:1c:6aBSkyB Ltd |   |   | 2021/03/06 10:35:19 UTC | 2021/03/06 12:35:19 UTC |   | active |  
QPVLAN | 10.4.12.169 | c8:5b:76:27:c6:83LCFC(HeFei) Electronics Technology co., ltd | LAPTOP-QEJ8VV83 |   | 2021/03/06 10:27:20 UTC | 2021/03/06 12:27:20 UTC |   | active |  
QPVLAN | 10.4.12.185 | 98:06:3c:1f:a9:bdSamsung Electronics Co.,Ltd | localhost |   | 2021/03/06 09:04:15 UTC | 2021/03/06 11:04:15 UTC |   | active |  
QPVLAN | 10.4.12.191 | 84:c5:a6:be:8f:5cIntel Corporate | DESKTOP-0K5JB2D |   | 2021/03/06 10:13:40 UTC | 2021/03/06 12:13:40 UTC |   | active |  
QPVLAN | 10.4.12.192 | 02:3e:c0:84:d2:1c | Galaxy-S10 |   | 2021/03/06 10:29:58 UTC | 2021/03/06 12:29:58 UTC |   | active |  
QPVLAN | 10.4.12.193 | d2:d9:a9:c5:46:c5 | loris-iPhone |   | 2021/03/06 09:00:44 UTC | 2021/03/07 09:00:44 UTC |   | active |  
QPVLAN | 10.4.12.197 | 40:62:31:00:c1:afGIFA | OPNsense |   | 2021/03/06 10:56:19 UTC | 2021/03/06 12:56:19 UTC |   | active |  
QPVLAN | 10.4.12.199 | a8:34:6a:5c:a9:5cSamsung Electronics Co.,Ltd | GalaxyWatch-A95B |   | 2021/03/06 10:47:27 UTC | 2021/03/06 12:47:27 UTC |   | active |  
VLANIOT | 10.4.15.11 | 5c:41:5a:75:ef:95Amazon.com, LLC | Bedroom-Spot | Echo Spot |   |   |   | static |  
VLANIOT | 10.4.15.12 | fc:a6:67:2e:52:f9Amazon Technologies Inc. | Bedroom-Dot | Echo Dot |   |   |   | static |  
VLANIOT | 10.4.15.13 | 3c:5c:c4:ad:16:47Amazon Technologies Inc. | Kichen-Dot | Echo Dot |   |   |   | static |  
VLANIOT | 10.4.15.15 | cc:9e:a2:c7:d4:f0Amazon Technologies Inc. | Lounge-Dot | Echo Dot |   |   |   | static |  
VLANIOT | 10.4.15.16 | 14:91:38:ab:b3:3cAmazon Technologies Inc. | Martins-Echo | Echo Dot |   |   |   | static |  
VLANIOT | 10.4.15.17 | 08:a6:bc:2f:69:3dAmazon Technologies Inc. | Loris-Dot | Echo Dot | 2021/03/06 10:34:18 UTC | 2021/03/06 12:34:18 UTC |   | static |  
VLANIOT | 10.4.15.34 | 00:15:5d:0c:0a:0eMicrosoft Corporation | webserver |   |   |   |   | static |  
VLANIOT | 10.4.15.51 | 90:70:65:07:15:daTexas Instruments | Ring |   |   |   |   | static |  
VLANIOT | 10.4.15.52 | 60:64:05:cc:6e:9bTexas Instruments | Ring-Bell | Ring Bell |   |   |   | static |  
VLANIOT | 10.4.15.71 | c8:db:26:08:b2:b6Logitech | Harmony-Lounge | Harmony Remote Hub |   |   |   | static |  
VLANIOT | 10.4.15.89 | f0:5c:77:32:82:9cGoogle, Inc. | Chromecast |   |   |   |   | static |  
VLANIOT | 10.4.15.91 | 78:3e:53:db:24:1aBSkyB Ltd | SkyRx | Sky Receiver Lounge |   |   |   | static |  
VLANIOT | 10.4.15.99 | 80:7d:3a:7b:a8:7bEspressif Inc. | ESP_7BA87B |   | 2021/03/06 10:48:24 UTC | 2021/03/06 12:48:24 UTC |   | active |  
VLANIOT | 10.4.15.100 | f4:cf:a2:c4:18:d8Espressif Inc. | ESP_C418D8 |   | 2021/03/06 10:49:51 UTC | 2021/03/06 12:49:51 UTC |   | active |  
VLANIOT | 10.4.15.101 | c4:4f:33:b0:00:26Espressif Inc. | ESP_B00026 |   | 2021/03/06 10:57:34 UTC | 2021/03/06 12:57:34 UTC |   | active |  
VLANIOT | 10.4.15.102 | c4:4f:33:b0:03:2bEspressif Inc. | ESP_B0032B |   | 2021/03/06 10:35:29 UTC | 2021/03/06 12:35:29 UTC |   | active |  
VLANIOT | 10.4.15.140 | 00:17:88:67:a1:7cPhilips Lighting BV | Philips-hue |   | 2021/03/06 10:50:54 UTC | 2021/03/06 12:50:54 UTC |   | active |  
VLANIOT | 10.4.15.141 | dc:54:d7:99:65:c8Amazon Technologies Inc. | amazon-6a9428d47 |   | 2021/03/06 10:37:48 UTC | 2021/03/06 12:37:48 UTC |   | active |  
VLANIOT | 10.4.15.149 | 00:04:20:fe:de:b0Slim Devices, Inc. | HarmonyHub |   | 2021/03/06 10:48:44 UTC | 2021/03/06 12:48:44 UTC |   | active |  
VLANIOT | 10.4.15.171 | 08:a6:bc:a0:12:3eAmazon Technologies Inc. | amazon-24dfbef8f |   | 2021/03/06 10:33:37 UTC | 2021/03/06 12:33:37 UTC |   | active |  
CRESTRON_VLAN | 10.4.20.27 | 00:10:7f:04:df:c0CRESTRON ELECTRONICS, INC. | CRESPRO2 |   |   |   |   | static

`

**Comment by dj0abr** [comment]
a friend has no problem too, all is show. Another friend has the same problem I have, only one vlan is shown.
So it looks to be a sporadic problem. How can we track it?

**Comment by marjohn56** [comment]
Let's try and work out the commonalities, I am all static, running OPNsense 21.7.a_113-amd64.

**Comment by marjohn56** [comment]
Let's also check our ranges. My statics are always below 100 or above 199, dynamics are between 100 & 199 only.

**Comment by pattisonmichael** [comment]
I Have the same issue on OPNsense 21.1.5. If there is a static map it will not show a dynamic lease anymore.
However it will show the static map online based on the MAC but that wrong. For example I had a device getting 192.168.70.10 from the dynamic range. Then I changed it to a static map at 192.168.70.4. Now I see the lease for 192.168.70.4 as online but actually the device is still on .10 reachable. This is very irritating as it's not a true reflection of the dhcp leases.
The logs show correctly that the device is on .10 in the dynamic range.
@AdSchellevis can you reopen this ticket please?

**Comment by AdSchellevis** [comment]
@pattisonmichael not without someone volunteering to work on it, no, please read our  contributing guideline for details about our policy (https://github.com/opnsense/core/blob/master/CONTRIBUTING.md)

**Comment by pattisonmichael** [comment]
@AdSchellevis I read through this now but i'm not sure which part you refer too.
Anyways this seems to me like a quiet serious bug, DHCP being a core function of a router and it seems like there are enough people affected to at least raise their voice in this ticket.

I'm not expecting instant results but feel that this should at least warrant further investigation by someone who knows the in and outs.

**Comment by AdSchellevis** [comment]
issues timeout after 180 days, if there's no one actively working on it. It was marked as support by the way, just remember that issues aren't always bugs.  Looking at the comments, it looks like multiple people already have taken a look at it by the way..

**Comment by RandMental** [comment]
Still the same problem

**Comment by NateroniPizza** [comment]
Issue still present.

**Comment by SMAW** [comment]
Same Issue here, v23.1.11

**Comment by JSuenram** [comment]
Can confirm, 2 fresh installs with BE based on 24.10_7 both show no leases at all, while Log shows leases are given out to clients....
