### ISSUE TITLE
proxy support for firmware/plugin updates

### ISSUE THREAD

**Issue by ionoci** [opnsense/core#3965]
Hi, 

we are using OPNsense for production- and lab-environments and are very satisfied(thanks for your great work).
As we use layered defense, some of our instances may reach the update-sites only via http-proxy. We used the workaround mentioned in #1239, but this is too complicated for our youngsters.

Could you please integrate proxy support into System:Firmware?

Best regards

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/core/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
