### ISSUE TITLE
Captive Portal - Force the use of classic dns system instead of DoH

### ISSUE THREAD

**Issue by tech62** [opnsense/core#3967]
In anticipation of a deployment of the DoH functionnality in EU by Mozilla and others browsers , can we develop a feature to block automatically "canary domain" provide by Mozilla to force the classic DNS use  ? [https://support.mozilla.org/en-US/kb/canary-domain-use-application-dnsnet](url)

There's legal informations to be logged according the FR/EU legislation when providing Wifi guest access to internet and this system can be used to bypass the logging system (the queries are sent with the use of 443 port instead of the 53 port)

Thanks

**Comment by tech62** [comment]
Incomplete ? what information do you need ?

**Comment by AdSchellevis** [comment]
https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

**Comment by tech62** [comment]
I've expose the need, you can tag this issue as "feature".
I can't see what i've to add

With DoH the users will pass their DNS queries to the 443 port (https) instead of the 53 port, the 443 is encrypted, so we will not able to log the users activities but uniquely the traffic who's transitting (IP DST / SRC) but legaly we need to identify what site were visited by what user when the justice will requesting the logs

And because one server like can hosts many sites and in their majority aren't illegal, i think we need to block the "[canary domain](https://support.mozilla.org/en-US/kb/canary-domain-use-application-dnsnet)" to force the utilization of the classic dns port (53 - unencrypted)

**Comment by tech62** [comment]
https://isc.sans.edu/forums/diary/Blocking+Firefox+DoH+with+Bind/25316

**Comment by mimugmail** [comment]
@tech62 so you can install BIND plugin and add the zone like described in the article?

**Comment by tech62** [comment]
Yes, i can, but i think, if it's possible , adding an option who's set the settings automatically (like the checkbox to set the proxy transparent or the SNI option in the proxy part) to reduce the risk of bad manipulation and make this configuration easily

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/core/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
