### ISSUE TITLE
CA/Cert Generation: Optional fields are treated as mandatory

### ISSUE THREAD

**Issue by ghost** [opnsense/core#3968]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[X] I have searched the existing issues and I'm convinced that mine is new.

**Describe the bug**
Within System > Trust > Authorities/Certificates, the interface requires ALL distinguished name fields (Country code, state/province, city, org, email address, common name) to be entered in order to create a CA or a certificate.

None of these fields (save for the common name for practical purposes) are actually required by the standard. These fields, except for common name, should be made optional. The country code should be allowed to be left blank. Also, a field for "organizational unit" should be added.

**To Reproduce**
1. In the navigation menu, click `System`.
2. Click on `Trust`.
3. Click on `Authorities`.
4. Attempt to generate an internal CA with only the Common Name field populated under the Distinguished Name fields.

**Expected behavior**
An internal CA certificate should be generated with a distinguishedName of the form `/CN=Test CA`.

**Screenshots**
![image](https://user-images.githubusercontent.com/44786627/76134584-62575580-5fed-11ea-94fb-acbe4ef567bd.png)

```
OPNsense 20.1.2-amd64
FreeBSD 11.2-RELEASE-p17-HBSD
OpenSSL 1.1.1d 10 Sep 2019
```

**Comment by pmhausen** [comment]
Seconded. Specifically the email address in my case. I ended up creating a manual CSR and signing that, then importing cert and key.
All of these fields should be optional.

**Comment by eigenfire** [comment]
I've taken a swing at CA/cert UI updates to the above effect. Haven't added the OU fields where relevant yet.

https://github.com/eigenfire/core/tree/cert-ui-rework

**Comment by eigenfire** [comment]
@pmhausen Would you be willing to test this out?

**Comment by pmhausen** [comment]
How can I run this? I have exactly one productive OPNsense installation at the moment.
For my own changes to the collectd config I manually copied the files to my system to test ...

**Comment by pmhausen** [comment]
I'll have a look. Not today, though.

**Comment by eigenfire** [comment]
@pmhausen Not gonna whine about the when, you're willing to help. Thanks!

**Comment by eigenfire** [comment]
Added OU fields and opened PR #4219.

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/core/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
