### ISSUE TITLE
Updating an interface not possible with configured CARP IPs and IPv4 set to none

### ISSUE THREAD

**Issue by Nico82x** [opnsense/core#3970]
**Describe the bug**
It is not possible to update an interface when CARP is configured and therefore the IPv4 configuration is set to none. The error message is "This interface is referenced by IPv4 VIPs. Please delete those before setting the interface to 'none' configuration."

**To Reproduce**
1. Go to interface and choose an interface with no IPv4 configured and configured CARP IPs
1. No real changes are required, just click "Save"
3. An error comes up (see above) and no changes are made

**Expected behavior**
The IPv4 setting was none before so the system should accept the input.

**Environment**
OPNsense 20.1.2-amd64
FreeBSD 11.2-RELEASE-p17-HBSD
OpenSSL 1.1.1d 10 Sep 2019

**Comment by AdSchellevis** [comment]
Can't reproduce on my end, logic looks ok too 
https://github.com/opnsense/core/blob/2a80d1a8a2c82be409f211fcb36132204d1ac64e/src/www/interfaces.php#L689-L696

If you're 100% sure there are no attached virtual ip's, you probably need to supply more data.... (screenshots, steps to reproduce on a clean install)

**Comment by Nico82x** [comment]
Hi,

no there **ARE** virtual IPs configured. The point is that I cannot rename an interface with VIPs configured although it's maybe just the name or any other setting (like Ipv6 which is not related to IPv4 / CARP).

**Comment by AdSchellevis** [comment]
Shouting your case usually doesn't help proving your right. clean install, reproducible steps increases the likelihood of help.

**Comment by Nico82x** [comment]
This wasn't meant as shouting, just to emphasise this. It is actually a clean install and I've noticed the exact same behaviour on different setups as well. Your initial reply seems that you misunderstood the description so to make it clear: 

- I'm talking about an interface with no IP directly configured (so IPv4 = none)
- at least one CARP IP configured on that very interface
- an attempt to update this interface which leads to the error mentioned above: you cannot update interface with IPv4 = none and CARP upon it which seems odd

**Comment by AdSchellevis** [comment]
so, either the virtual ip's should validate if there's an address configured on the interface (preventing this situation from happening) or this validation might not be needed. In the last case, someone needs to  validate the affect on all options available in the VirtualIP section (carp, ip alias, ...)

**Comment by Nico82x** [comment]
It seems to me the validation is not needed but at least renaming an interface should always be possible since it's just a cosmetical thing without any changes on the backend.
Just found another (related) bug:
- You can disable an interface with configured VIPs but
- you cannot enable it afterwards but you have to remove the VIPs first from the config

Shall I open a separate ticket for that?

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/core/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
