### ISSUE TITLE
Pixel phone outbound traffic or DNS lookups intermittently stop working

### ISSUE THREAD

**Issue by BCurrell** [opnsense/core#3974]
This is a bit of a weird bug, and I'm not sure if its Opnsense or something to do with the Pixel phones that is at fault, or even how to start running it down.

We have 3 sites where we use Opnsense firewalls:

Head Office:
- 2* firewalls in HA
- Intel Pentium G2130 / G2120
- 8GB RAM
- 4GB Compact Flash
- Opnsense 19.1

Director House 1:
- Single firewall
- Intel Atom D525
- 2GB RAM
- 4GB Compact Flash
- Opnsense 16.7 -> 19.1 -> 19.7

Director House 2:
- Single firewall
- Intel Atom C2358
- 2GB RAM
- 16GB MicroSD
- Opnsense 16.7

At the tail end of last year, Director 1 and his wife changed their phones to a Google Pixel 4 and Google Pixel 3 respectively. After a few weeks, they noticed that sometimes, their phones would randomly stop passing data. We originally put this down to WiFi, so spent the next couple of months running it down. With the intermittent nature of the issue, it was a long process, involving replacement APs and a Raspberry Pi connected to WiFi trying to catch the same symptoms in progress. We never got any useful logs from the Pi, and put it down to the phones losing connectivity at different times, meaning we couldn't line anything up. They also started using their laptops / surfaces on WiFi to see if they were having the same issue, if it was happening at the same time, if it was location dependent. This is where we noticed that only the phones were affected.

During the testing period, we also tried to run down what actually stopped working. We determined that we were still able to connect to one of our servers via the IP address, so we assumed it was DNS related. We use Slack for internal communication, and messages were coming in but not going out. I've previously seen that after messing around with VPNs and DNS, so that strengthened the argument. Director 1 was able to access some websites by the URL when he actively tried to during this drops, and some did return the page. This may have been cache though.

Director 1 had to replace his phone due to an unrelated fault (remaining with a Pixel 4), but the connectivity issue continued. At this time, their house was still running on 16.7, so after exhausting all options with the WiFi for now, we decided to upgrade the firewall. We went to 19.1 first using the built in updater, but during the upgrade to 19.7, it bricked the firewall and we had to re-install. We didn't have a backup, so the firewall was configured from scratch, excluding most of the port forwards and firewall rules due to the urgency. At this point, 20.1 had been released for a couple of days, but we chose not to upgrade just yet until we put it through our own testintg.

For about a week, no further instances of the phones losing connectivity, but then it started up again. It's at this point that we were ready to test a lightweight router solution we were working on, starting with Director 1. We replaced the Opnsense firewall with this router, and for the next 2 weeks, we had no issues. This router solution has been in place for 6 weeks with no return of the issue I'm reporting in such a verbose manner.

Last week, Director 2 also upgraded his phone to a Google Pixel 4. Today, at head office, both directors started experiencing the exact same issue, where they were unable to do anything from their phones. The rest of the office are on a combination of Samsungs, OnePlus' and iPhones, and no-one else experienced it. Our firewalls have been live in our office for months without this being a problem. The directors aren't in the office every day, and will rarely be on their phones whilst they are in, opting instead to use their surfaces or desk phones.

I'm still waiting for confirmation if Director 2 has experienced this issue at home.

I'm at a bit of a loss as to what could be happening. On the face of it, it seems that Opnsense and Pixel don't work together, which sounds ridiculous.

Have you heard anything similar in the past? Have you got any suggestions for diagnosing this on our LAN?

We are currently installing 20.1 on the Atom D525 device and will run some testing with that to see if its been resolved in the current release, but it will be an intrusive change to do the same at the head office, so we're not able and willing to do that just yet.

**Comment by BCurrell** [comment]
New development as of today:

Senior developer has experienced the bug as well, this time with a Huawei P30 Lite

**Comment by iMiMx** [comment]
Just in case, do you use Cloudflare 1.1.1.1 public DNS by any chance?  This has been a bit 'wonky' for me for a few weeks., randomly not resolving some DNS queries (Google, Twitter, various other sites).

**Comment by BCurrell** [comment]
DNS is handled by our domain controller at head office, which then uses 8.8.8.8. I believe the director houses also use 8.8.8.8 directly. We didn't try another DNS provider.

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/core/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
