### ISSUE TITLE
Firewall rules won't apply when one of the interfaces lacks an address on failover

### ISSUE THREAD

**Issue by drivera-armedia** [opnsense/core#3978]
**Important notices**
[X] I have read the contributing guide lines at 
[X] I have searched the existing issues and I'm convinced that mine is new.

**Describe the bug**
When dealing with a failover scenario in a multi-WAN setup, if the primary interface goes down (i.e. upstream outage) **_and_** its DHCP lease expires, the interface won't have an address assigned to it and any and all changes to firewall rules will fail.

The following notices will start accumulating on the top of the page:
```
03-12-20 12:49:29 [ There were error(s) loading the rules: /tmp/rules.debug:85: no translation address with matching address family found. - The line in question reads [85]: nat on igb2 inet proto tcp from (igb2:network) to $VPNGATE port {22} -> igb2 port 1024:65535 # vpngate/ssh ]
```
 Some functionality (notably, policy-routed VPNs) will fail to function correctly due to the above notice during rule application.

When the DHCP lease is refreshed (i.e. service returns), everything goes back to normal. The common denominator seems to be that while the interface has an IP assigned - regardless of whether service is actually available through the circuit - everything works as intended, even during failover (thanks to info from [this ticket](https://github.com/opnsense/core/issues/3961), I applied the patch mentioned therein and that resolved other problems I was having regarding default gateways).

**To Reproduce**
1. Install OPNsense 20.1, apply all updates
1. Configure WAN1 using DHCP, set its gateway to be upstream with priority 1, and gateway monitoring using a "far" IP (i.e. 8.8.8.8)
1. Configure WAN2 using DHCP, set its gateway to be upstream with priority 2, and gateway monitoring using a "far" IP (i.e. 8.8.4.4)
1. Configure all other gateways set Disable Gateway Monitoring and Mark Gateway as Down
1. Configure GW Monitoring like described in https://docs.opnsense.org/manual/how-tos/multiwan.html
1. Enable gateway switching
1. Configure policy based routing like described in https://docs.opnsense.org/manual/how-tos/multiwan.html
1. Confiure an SSH port forwarding on both WAN1 and WAN2 to an internal server (named VPNGATE in our example), and use a Host Alias to refer to the server's IP.
1. Wait for both WAN gateways to be up and available
1. Verify routing over both WAN gateways
1. Unplug the cable for WAN1 at either end
1. Wait for the IP address on the WAN1 interface to be cleared out

**Expected behavior**
No loss of traffic routing or functionality due to failover to WAN2, ability to change or modify rules and have them take effect immediately, functionality continues upon return to service of WAN1.

**Actual behavior**
Some or all routing functionality is lost, rules can be changed in the UI and saved, but do not take effect immediately - the above notice is the only indication of an error.

**Environment**
OPNsense 20.1.2-amd64
FreeBSD 11.2-RELEASE-p17-HBSD
OpenSSL 1.1.1d 10 Sep 2019
Protectlii FW4B

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/core/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
