### ISSUE TITLE
Reconnect/reset VPN client connections on failback after successful failover

### ISSUE THREAD

**Issue by drivera-armedia** [opnsense/core#3979]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[X] I have read the contributing guide lines at 
[X] I have searched the existing issues and I'm convinced that mine is new.

**Is your feature request related to a problem? Please describe.**
After failover on a Multi-WAN setup, some static OpenVPN client connections successfully re-establish using the alternative circuit and routing through those works fine. However, when failback happens (i.e. the primary circuit returns to service) those connections will still remain over the backup circuit as opposed to being re-established over the primary circuit (which has higher bandwidth).

**Describe the solution you'd like**
It would be nice to have a feature that triggers VPN reconnections on failback within a failover scenario so that the higher-bandwidth, primary circuit can be leveraged again.

**Describe alternatives you've considered**
I've considered setting up a script that monitors the currently active primary gateway and triggers the VPNs to reconnect whenever the gateway changes, but I don't know which script(s) to invoke on the command-line in order to do that, or if that's even the right approach.

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/core/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
