### ISSUE TITLE
devd.log gets spammed with errors if cd/dvd-drive left empty.

### ISSUE THREAD

**Issue by jamiew0w** [opnsense/core#3980]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md 

- [x] I have searched the existing issues and I'm convinced that mine is new. (re-opening of old bug #1484) 

**Describe the bug**

In short if you use a server with a cd/dvd-drive and leave the drive empty, after installing and running OPNSense devd.log gets spammed with devd errors every few seconds.

I'm aware this is either a FreeBSD or Hardened BSD (upstream) related issue, however it sounds like this change may have been fixed - in which case it has again re-appeared. I can't say _when_ it has started, I only noticed it when I started paying more attention to my logs so it's evident on  20.1.2 and  20.1.1.

**To Reproduce**
1. Use a server that has a cd-rom/dvd-rom drive
2. Leave the drive empty
3. Install OPNSense
4. Watch devd.log

**Expected behavior**
devd.log shouldn't be spammed with these messages.

**Screenshots**
Not applicable

**Relevant log files**

```
2020-03-16 01:43:36 | 2020-03-16T01:43:36+00:00 OPNsense.lan devd: Processing event '!system=CAM subsystem=periph type=error device=cd0 serial="108240289685" cam_status="0xcc" scsi_status=2 scsi_sense="70 02 3a 01" CDB="00 00 00 00 00 00 " '
-- | --
  |   | 2020-03-16 01:43:33 | 2020-03-16T01:43:33+00:00 OPNsense.lan devd: Processing event '!system=CAM subsystem=periph type=error device=cd0 serial="108240289685" cam_status="0xcc" scsi_status=2 scsi_sense="70 02 3a 01" CDB="00 00 00 00 00 00 " '
  |   | 2020-03-16 01:43:30 | 2020-03-16T01:43:30+00:00 OPNsense.lan devd: Processing event '!system=CAM subsystem=periph type=error device=cd0 serial="108240289685" cam_status="0xcc" scsi_status=2 scsi_sense="70 02 3a 01" CDB="00 00 00 00 00 00 " '
  |   | 2020-03-16 01:43:27 | 2020-03-16T01:43:27+00:00 OPNsense.lan devd: Processing event '!system=CAM subsystem=periph type=error device=cd0 serial="108240289685" cam_status="0xcc" scsi_status=2 scsi_sense="70 02 3a 01" CDB="00 00 00 00 00 00 " '
  |   | 2020-03-16 01:43:24 | 2020-03-16T01:43:24+00:00 OPNsense.lan devd: Processing event '!system=CAM subsystem=periph type=error device=cd0 serial="108240289685" cam_status="0xcc" scsi_status=2 scsi_sense="70 02 3a 01" CDB="00 00 00 00 00 00 " '
  |   | 2020-03-16 01:43:21 | 2020-03-16T01:43:21+00:00 OPNsense.lan devd: Processing event '!system=CAM subsystem=periph type=error device=cd0 serial="108240289685" cam_status="0xcc" scsi_status=2 scsi_sense="70 02 3a 01" CDB="00 00 00 00 00 00 " '
  |   | 2020-03-16 01:43:18 | 2020-03-16T01:43:18+00:00 OPNsense.lan devd: Processing event '!system=CAM subsystem=periph type=error device=cd0 serial="108240289685" cam_status="0xcc" scsi_status=2 scsi_sense="70 02 3a 01" CDB="00 00 00 00 00 00 " '
  |   | 2020-03-16 01:43:15 | 2020-03-16T01:43:15+00:00 OPNsense.lan devd: Processing event '!system=CAM subsystem=periph type=error device=cd0 serial="108240289685" cam_status="0xcc" scsi_status=2 scsi_sense="70 02 3a 01" CDB="00 00 00 00 00 00 " '
  |   | 2020-03-16 01:43:12 | 2020-03-16T01:43:12+00:00 OPNsense.lan devd: Processing event '!system=CAM subsystem=periph type=error device=cd0 serial="108240289685" cam_status="0xcc" scsi_status=2 scsi_sense="70 02 3a 01" CDB="00 00 00 00 00 00 " '
```

**Additional context**
Issue previously reported in #1484

**Environment**
20.2.2 & 20.2.1 at least, likely previous versions also.

```
OPNsense 20.1.2-amd64
FreeBSD 11.2-RELEASE-p17-HBSD
OpenSSL 1.1.1d 10 Sep 2019
```

Hardware not really necessary, only cd/dvd-drive necessary to replicate.

---

Note: I have tested serveral FreeBSD fixes however haven't found a permanent fix that works. 

I think [this](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=209368) is where the bug was eventually fixed but I could be wrong.

**Comment by jamiew0w** [comment]
This appears to have been fixed in recent updates so closing it out.

**Comment by zsbolyoczki** [comment]
Hi,

I'm facing this on a fresh FreeBSD 12.1 install on qemu. 
I have "ejected" the DVD from the VM (but the drive is still there ofc) and my syslog is full with this:
```
'!system=CAM subsystem=periph type=error device=cd0 serial="QM00002" cam_status="0xcc" scsi_status=2 scsi_sense="70 02 3a 00" CDB="00 00 00 00 00 00 " '
```

**Comment by barzog** [comment]
I confirm that on latest opnsense (21.7.7) this one exists and we receive 20k syslog messages per day per appliance.

**Comment by barzog** [comment]
But in my case creating /etc/rc.conf.d/devd with contents devd_flags="-q" and restarting /etc/rc.d/devd restart - solves problem

**Comment by ed006949** [comment]
> But in my case creating /etc/rc.conf.d/devd with contents devd_flags="-q" and restarting /etc/rc.d/devd restart - solves problem

this will not help with reboot
