### ISSUE TITLE
openvpn, Local Port in use

### ISSUE THREAD

**Issue by hudecof** [opnsense/core#3984]
**Describe the bug**
Unable to assing OpenVPNserver on the same port, on primary and alias ip.

**To Reproduce**
- create alias ip for WAN interface
- create openvpn server on WAN interface, udp/1194
- create openvpn server on WAN/alias  interface, udp/1194

You will get error **The specified 'Local port' is in use. Please select another value**

**Expected behavior**
The openvpn server should be created.

**Screenshots**
N/A

**Relevant log files**
N/A

**Additional context**
The function **openvpn_port_used** in **/usr/local/etc/inc/plugins.inc.d/openvpn.inc** do not comparethe **ipaddr** field.

For WAN interface this value is missing, for WAN/ALIAS is present.

**Environment**

  | OPNsense 19.7.10_1-amd64FreeBSD 11.2-RELEASE-p16-HBSDOpenSSL 1.0.2u 20 Dec 2019
-- | --

**Comment by AdSchellevis** [comment]
https://github.com/opnsense/core/commit/5dd129c967d001e7c08b06a280624346959faec1 should fix this on the latest version (20.1.2).

**Comment by hudecof** [comment]
@AdSchellevis thans, that was quick
