### ISSUE TITLE
Interfaces assignment / Include description for IPSEC and OpenVPN tunnels

### ISSUE THREAD

**Issue by alexandredulche** [opnsense/core#3986]
In version 20.1.2, on the interface/assignment page OpenVPN/IPSEC tunnels are displayed in the dropbox menu as  : 
- ipsec1000 (00:00:00:00:00:00)
- ovpnc1 (00:00:00:00:00:00)

At the same time those ID are not displayed in the status or tunnel configuration pages for OpenVPN/IPSEC tunnels.

It makes it difficult to choose your tunnels when you have many.
Instead it could be displayed as : 

- ipsec1000 (description)
- ovpnc1 (description)

**Comment by AdSchellevis** [comment]
`ifconfig` doesn't know how they are related (these originate directly from ifconfig, the device names aren't persisted in the configuration for these types).

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/core/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
