### ISSUE TITLE
opnsense and pfsense openVPN route explanation do not match

### ISSUE THREAD

**Issue by Perflyst** [opnsense/core#3987]
If you navigate to VPN -> OpenVPN -> Clients -> Add you can see the following:
On opnsense and pfsense there explanations for these two route push checkboxes are swapped. I am not sure which of both is correct.

1. image is from pfsense
2. image is from opnsense

![pfsense](https://user-images.githubusercontent.com/26308977/76875163-7b26fd00-6870-11ea-93c9-a37d4ac794e8.png)

![opnsense](https://user-images.githubusercontent.com/26308977/76874176-17e89b00-686f-11ea-9bdf-5c228da7d1f2.png)

I am opening this on GitHub because it might need to be replaced in the code. Therefore it is maybe also a bug.

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues and I'm convinced that mine is new.

**Comment by AdSchellevis** [comment]
Don't pull routes links to `route-nopull`
https://github.com/opnsense/core/blob/5dd129c967d001e7c08b06a280624346959faec1/src/etc/inc/plugins.inc.d/openvpn.inc#L922-L924

The other one to `route-noexec`
https://github.com/opnsense/core/blob/5dd129c967d001e7c08b06a280624346959faec1/src/etc/inc/plugins.inc.d/openvpn.inc#L926-L928

OpenVPN documents its settings here https://openvpn.net/community-resources/reference-manual-for-openvpn-2-4/

I think we're good :)

We forked pfSense more than 5 years ago and went very different directions......

**Comment by Perflyst** [comment]
So `Don't add/remove routes` is route-noexec?
In the OpenVPN documentation route-noexec is explained with `Don’t add or remove routes automatically. Instead pass routes to --route-up script using environmental variables.` which is what pfsense does. opnsense does mention --route-up `Don't pull routes`

**Comment by Perflyst** [comment]
Looks like you forked a few days/weeks/months too early https://redmine.pfsense.org/issues/4273 ;)

**Comment by AdSchellevis** [comment]
hehe, you're right, even reading it again, I totally missed the swap :) Let me fix that and close the issue..


.... although.... It's never too early to fork pfsense ;)
