### ISSUE TITLE
Backup to Nextcloud 

### ISSUE THREAD

**Issue by q-wertz** [opnsense/core#3988]
**Is your feature request related to a problem? Please describe.**
At the moment as far as I understand it, it is not possible to backup into a subdirectory of nextcloud. (Short discussion was here https://github.com/opnsense/core/issues/2250, but not really a solution). If I add a path to the Directory Name field I get the error 

> The Backup Directory can only consist of alphanumeric characters.

If I use e.g. `example.com/nextcloud/remote.php/dav/files/USERNAME/Backups`  as update URL i get the error

> Saved settings, but remote backup failed.

**Describe the solution you'd like**
It would be nice to either be able to use one of the two methods for putting the Update into a specific folder.

**Additional context**
I think it would be more convenient and would also support other webdav services if a general "add webdav backup" with the link method would be available.
Based on this one can also implement a short cut for nextcloud (and other webdav servers) where one only has to enter the base url and in the Directory field one can enter the path and in the background the strings will be concatenated according to the Nextcloud requirements.

**Comment by fabianfrz** [comment]
Your nextcloud url should be https://example.com/nextcloud and your directory Backups. Then it should work to send files into that directory.

**Comment by q-wertz** [comment]
I can send files to so root directory of my user, but not into a subfolder (e.g. Backups/opnsense).

**Comment by fabianfrz** [comment]
backslashes should be never allowed. Slashes could be theoretically in the URL but I have not implemented the MKCOL requests (create directory in nextcloud) to ensure that the directory exists when I try to write the file into it.

**Comment by q-wertz** [comment]
Sorry I confused the two.
Do you think that would be a big effort?
I maybe can try to change the code and make a pull request but may take a while (I don't know much about php)...

**Comment by fabianfrz** [comment]
You do not only need php knowlege, also WEBDAV knowlege is required.

**Comment by appletalk** [comment]
+1 this issue.  Automatic Nextcloud backups are great, but being able to organize them into a subdir would be greatly preferred

**Comment by maxxer** [comment]
I posted a PR which implements subdir allowance. I made a couple of tests with the default config and with subdirs and seems to work fine

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/core/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.

**Comment by maxxer** [comment]
> If someone wants to step up and work on this issue, just let us know, so we can reopen the issue and assign an owner to it.

The PR is open and waiting for a review

**Comment by AdSchellevis** [comment]
we'll keep https://github.com/opnsense/core/pull/4077 open
