### ISSUE TITLE
Create a GUI-Element to control stongswans reuse_ikesa option

### ISSUE THREAD

**Issue by JuergenGarbe-GH** [opnsense/core#3990]
Related and tested OPNsense version: 20.1 (production).
As descriped in  https://forum.opnsense.org/index.php?topic=16218.new;topicseen#new 
there is an issue trying to connect to an ASA 5540 using IPSec with more than 1 Phase 2 definitions.
This issue can be solved by setting strongswans option "reuse_ikesa=no".
In the test case that was done by creating a file /usr/local/etc/strongswan.opnsense.d/noreuse_ikesa.conf with a line
   charon { reuse_ikesa=no }
and restarting ipsec.
Because I was not the only one who had this problem (which was my luck: I got this solution offered!), I think it would be a good idea to create a GUI Element to be able to enable or disable the "reuse_ikesa" option.

**Comment by oyvellef** [comment]
Still an issue that is very hard to troubleshoot, Palo Alto firewalls need this setting for IPSec tunnels to be stable and rekey without downtime.
