### ISSUE TITLE
Empty username and password form fields are auto populated with the browser saved system login credentials.

### ISSUE THREAD

**Issue by NOYB** [opnsense/core#3993]
Empty username and password form fields are auto populated with the browser saved system login credentials.

This occurs with new forms (Add) or existing in which username and password are empty.

Some examples:
System: Access: Users: (add):  . . ./system_usermanager.php?act=new
Services: Dynamic DNS: (add): . . ./services_dyndns_edit.php
Services: OpenDNS: . . ./services_opendns.php

Browsers: Edge, probably Chrome too.

**Comment by AdSchellevis** [comment]
you could try `autocomplete="new-password"` (https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion), but browser hints are just that, hints, easy to ignore.

**Comment by fichtner** [comment]
From experience I can share that browsers do what they want... auto-fill inappropriate fields worst case in the eyes of the beholder despite hints and "proper engineering" of the website. The situation is an uphill battle and you deal with funny things like

autocomplete
autocapitalize
autocorrect

**per** field **per** context and the browsers will only **maybe** do what you intended.

**Comment by fichtner** [comment]
And this is browsers only, you also have to deal with auto-fill plugins. ;)

**Comment by AdSchellevis** [comment]
yep, it's a hint, as an old colleague of ones said about database hints "it's like asking your wife something, she might do it, you never know for sure"

**Comment by fichtner** [comment]
Maybe to share my favourite moment: browser auto-fills a disabled form field replacing the original content... ouchie...

**Comment by NOYB** [comment]
Why is autocomplete being globally set to off?
This prevents/overrides the use of any other settings such as new-password on password fields.  This results empty username and password fields being autofilled with the browser stored system login user credentials.

**Comment by fichtner** [comment]
> Why is autocomplete being globally set to off?

Let's back off a little. What is this issue raising awareness for (code, pages, expected vs. actual behaviour) and what will it solve so that we know what code is necessary to do it?

**Comment by NOYB** [comment]
I spelled this out in the opening.
Behavior: Empty username/password fields are being auto populated with the browser stored system login credentials.
Expected: Empty username/passwords fields not auto populated with the browser stored system login credentials.

Why is it a problem?
1) They are in the way.
2) They are not the correct values for the form.
3) Easy to inadvertently submit the form with those incorrect username and password values and break a service etc. that is not using authentication credentials.  Which is why the fields were blank in the first place.
4) Easy to inadvertently submit those system login credentials and have them end up in the system config for prying eyes to see.

What is needed is not that complicated.
1) Stop globally setting autocomlete to off.
2) Apply autocomplete="new-password" attribute on password fields that should not be populated with the system login credentials.

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/core/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.

**Comment by Seegras** [comment]
Also this keeps you from automatic login and password management from working. So please do not set autocomplete=off on the login-page.

**Comment by AdSchellevis** [comment]
@Seegras and I assume you checked if it was indeed changed in upcoming 22.1 before placing a comment...

https://github.com/opnsense/core/blob/a99a6549eb0fe4eb85e83fc725262dc920ff5bb8/src/etc/inc/authgui.inc#L361-L369
