### ISSUE TITLE
[Version:Current,VGA, LibreSSL]    Wrong display driver?

### ISSUE THREAD

**Issue by annadevries1992** [opnsense/core#3996]
Issue:
Display shows opnsense console in ~3 pixel font, and in wrong video-memory area, with gibberish.
Tried changing to VT driver, ..and back, but doesn't help. 

All is fine when booting from USB-Stick in Live-CD mode, with importing config for harddisk. 

Version:
= Clean install, and update to current.
OPNsense 20.1.3-amd64
FreeBSD 11.2-RELEASE-p17-HBSD
LibreSSL 3.0.2
Hardware:  HP 8460p
Bootmode: MBR

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/core/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
