### ISSUE TITLE
'quick' setting not applied to rules

### ISSUE THREAD

**Issue by rdhia** [opnsense/core#3998]
I've setup firewall rules on openvpn, the 'quick' setting is likely randomly applied to rules

I've opnsense 19.7.10 installed
openvpn server is configured on the firewall with tunnel net 10.0.54.0/24
on the capture my ip when connected to openvpn is 10.0.54.2
on the first and last log lines connection to the same ip is once allowed and once blocked
![OpenVPN Rules Firewall](https://user-images.githubusercontent.com/4179763/74480269-e320a700-4eb0-11ea-900c-f88280b680ae.png)
![Live View Log Files Firewall](https://user-images.githubusercontent.com/4179763/74480305-f2075980-4eb0-11ea-8e48-f7d470401868.png)

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/core/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
