### ISSUE TITLE
LDAP group sync removing users after update 20.1.3

### ISSUE THREAD

**Issue by ruffy91** [opnsense/core#3999]
[x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[x] I have searched the existing issues and I'm convinced that mine is new.

**Describe the bug**
Group Sync for LDAP servers is no longer working and is even removing the users from groups when logging in.
After reverting to 20.1.2 it works again

**To Reproduce**
1. create local group G_Users
2. create AD group G_Users
3. configure LDAP server using G_Users with group sync
4.a. in 20.1.2 login with user in G_Users to OPNsense GUI -> User gets added in local group G_Users
4.b. in 20.1.3 login with user in G_Users to OPNsense GUI -> User gets removed from local group G_Users

**Expected behavior**
Login with user in G_Users to OPNsense GUI -> User gets added in local group G_Users

**Additional context**
I assume the behaviour stems from #3870

**Comment by AdSchellevis** [comment]
you can always try if this specific commit https://github.com/opnsense/core/commit/7d363ce28788fb6577c123cba68871c3906ccb08 is your issue by reverting it with `opnsense-patch`. If I'm not mistaken, I've tested mixed variants on my end too, which looked fine. more details can be collected using the authentication test tool included in OPNsense.

**Comment by ruffy91** [comment]
I verified that it is commit 7d363ce which is causing the problem:
2020-03-24T17:01:32 | opnsense: /index.php: Successful login for user 'adm_prr' from: 10.99.1.6
-- | --
2020-03-24T17:01:32 | opnsense: User: policy change for adm_prr link group G_OPNsense_Admins [CN=G_OPNsense_Admins,OU=Groups,OU=xx,DC=intra,DC=xxx,DC=ch]
2020-03-24T17:01:02 | opnsense: /index.php: Successful login for user 'adm_frr' from: 10.99.1.14
2020-03-24T17:01:02 | opnsense: User: policy change for adm_frr link group G_OPNsense_Admins [CN=G_OPNsense_Admins,OU=Groups,OU=xx,DC=intra,DC=xxx,DC=ch]
> opnsense-patch 7d363ce 
2020-03-24T16:58:53 | opnsense: User: policy change for adm_frr unlink group G_OPNsense_Admins 
> using the tester for adm_frr
2020-03-24T16:58:37 | opnsense: /index.php: Successful login for user 'adm_prr' from: 10.99.1.6
2020-03-24T16:58:37 | opnsense: User: policy change for adm_prr unlink group G_OPNsense_Admins
> logging in in GUI with adm_prr
> Installed 20.1.3

Also in the tester with and without this patch the memberof attribute is exactly the same:
memberof => CN=G_OPNsense_Admins,OU=Groups,OU=xx,DC=intra,DC=xxx,DC=ch CN=G_NETWORK_ADMINS,OU=Administratoren,OU=xx,DC=intra,DC=xxx,DC=ch

**Comment by AdSchellevis** [comment]
`G_Users` doesn't equal `G_OPNsense_Admins`, are you testing exactly the same? Your data looks suspicious.

**Comment by AdSchellevis** [comment]
https://github.com/opnsense/core/commit/db249059748a318d3ebf80b117768f22f22f1b1f should fix it, please try to be consistent in your reports next time. We can't always reproduce the same case and inconsistencies have the risk of landing at the bottom of the stack....

**Comment by ruffy91** [comment]
We synchronize multiple groups not only these two.
I now see that it only happens when using the Limit groups field. As I can see you already found the bug.
Thanks for the fast fix.
