### ISSUE TITLE
don't hardcode an initial root password

### ISSUE THREAD

**Issue by fichtner** [opnsense/core#4]
Also interesting for factory reset. We should prompt for a new password in those cases via @timelessp (twitter)

**Comment by mschilt** [comment]
Why not just mandatory ask for a password during installation? 
For example Check Point is doing it that way. 

Of cause should someone have a very volatile mind they are free to reinstall it from scratch. 
Because its the initial installation there is nothing lost. 

.. and maybe some basic complexity rules should be in place.

**Comment by mschilt** [comment]
Do you consider re-opening this issue since using default user/passwords has proven to be not a good idea (Mirai et al) .

**Comment by fichtner** [comment]
@mschilt sure, but I just can't do this all on my own...

There needs to be a good plan, i.e. not only setting the password during installer, but how to make it the "factory" reset without possibly tainting the config.xml, revoking the rights to read the stored factory password. Add a way to reset the factory reset password. Insist on a sufficiently decent password complexity. Coding the installer bits in lua. And possibly more. Thoughts?

**Comment by mschilt** [comment]
Ok. Agree.  Thanks for reopening.
A 'factory' reset seems pointless when there is no 'factory default'. This should be just the normal 'reset password' process. However I agree that resetting the password is probably difficult without knowing the current password (given serial console is pw protected). We also don't know whether there are any buttons on the boxes that could be used (press für 10second to reset pw). 
I can only think of using morse code with interface link up/down. Or something like an additional menu item on the serial console when there are all links down (requiring user to unplug all cables).
Password complexity could be treated as different issue.

**Comment by fichtner** [comment]
Further tracking via https://github.com/opnsense/bsdinstaller/issues/4
