### ISSUE TITLE
vxlan interface does not start after reboot

### ISSUE THREAD

**Issue by sooslaca** [opnsense/core#4001]
**Description of the bug**
After reboot vxlan interface is not created

**Steps to Reproduce**
1. Create a vxlan interface (Interfaces -> Other Types -> VXLAN) 
2. Login via SSH you'll see **vxlan0**
3. Reboot host
4. Check interface on UI it is still there
5. Check on SSH, it's not there

**Expected behavior**
Retain vxlan0 after reboot

**Environment**
Version: 20.1.3 (installed)
VMWare ESXi 6.7 U2

**Comment by sooslaca** [comment]
just tried, it's still an issue with 20.1.5

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/core/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
