### ISSUE TITLE
Client Export - wrong config get exported

### ISSUE THREAD

**Issue by claasgo** [opnsense/core#4002]
**Describe the bug**
OpnSense 20.1.3
Currently 270 + Client Certs exists

If i export a new OpenVPN Conifg, it could happen, that the wrong file will be downloaded.
For example, if i want to export the latest conifg (e.g. number 274), then (browser independend, safari, ff, chrome..) the config number 272 will be downloaded.
HA Slave has the same failure.

*Tip*: to validate your setup was working with the previous version, use opnsense-revert (https://docs.opnsense.org/manual/opnsense_tools.html#opnsense-revert)

**To Reproduce**
1. Go to VPN
2. Click on OpenVPN
3. Click on Client Export
4. Download the latest Config (File only/Archive.. does'nt matter)

**Expected behavior**
The Config name, that I click should be exported, not the conifg "2 lines before".

**Screenshots**
Number for Certs: https://paste.pics/40a088ebc709eac9326c7b1fda894919
That config i want to export: https://paste.pics/a53293aa6f55088a328332893ca81f67
The highlighted config i get instead: https://paste.pics/971e88c356c6a9d385cd149b17f84154

**Relevant log files**
If applicable, information from log files supporting your claim.

**Additional context**

**Environment**
OPNSense 20.1.3-amd64
FreeBSD 11.2-RELEASE-p17-HBSD
OpenSSL 1.1.1.d 10 Sep 2019
HA-Setup

**Comment by claasgo** [comment]
current workaround: revoke and delete the affected cert and recreate it.

**Comment by AdSchellevis** [comment]
manually imported certs perhaps, exports are linked to certificate id's if their not unique (which normally shouldn't happen when creating via the gui), you might end up with the wrong entry...

**Comment by claasgo** [comment]
I do not import any certs manually. Everything only happens via WebUI.

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/core/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
