### ISSUE TITLE
High CPU usage when PC downloading

### ISSUE THREAD

**Issue by yhap2003** [opnsense/core#4003]
On the latest version:
OPNsense 20.1.3-i386
FreeBSD 11.2-RELEASE-p17-HBSD
OpenSSL 1.1.1d 10 Sep 2019

I never had this issue with the previous release.
I'm on Steam, Uplay downloading games and updates but when I try to access my firewall, the CPU usage is high, it makes my firewall very sluggish. As soon as I pause the download, the CPU usage goes back to normal.

top -aSH

last pid: 95780;  load averages:  9.45,  8.12,  5.26    up 0+00:31:10  09:39:47
188 processes: 9 running, 141 sleeping, 38 waiting
CPU:  0.4% user,  0.0% nice, 51.2% system, 47.5% interrupt,  1.0% idle
Mem: 108M Active, 66M Inact, 90M Wired, 43M Buf, 1722M Free
Swap:

  PID USERNAME   PRI NICE   SIZE    RES STATE   C   TIME    WCPU COMMAND
   12 root       -92    -     0K   328K CPU0    0   8:28  70.68% [intr{irq259:
    0 root       -92    -     0K   264K -       1   4:07  35.25% [kernel{em1 rx
    0 root       -92    -     0K   264K RUN     1   4:40  34.29% [kernel{em0 rx
40467 root        74    0  7840K  3972K RUN     1   0:01  32.52% /sbin/sysctl -
   12 root       -92    -     0K   328K RUN     0   2:19  16.41% [intr{irq262:
   12 root       -92    -     0K   328K WAIT    1   0:17   2.57% [intr{irq263:
   12 root       -92    -     0K   328K WAIT    1   0:08   0.97% [intr{irq260:
   11 root       155 ki31     0K    16K RUN     1  14:33   0.85% [idle{idle: cp
   12 root       -92    -     0K   328K RUN     0   0:08   0.69% [intr{irq265:
    0 root       -92    -     0K   264K RUN     1   0:12   0.67% [kernel{dummyn
   11 root       155 ki31     0K    16K RUN     0  14:32   0.52% [idle{idle: cp
95780 root        30    0  6188K  2092K piperd  1   0:00   0.40% grep temperatu
42669 root        20    0  6140K  1936K bpf     1   0:01   0.39% /usr/local/sbi
58425 root        20    0  7280K  3824K CPU1    1   0:05   0.36% top -aSH
   16 root       -16    -     0K     8K -       0   0:04   0.26% [rand_harvestq
71878 root        20    0  6008K  1924K select  1   0:04   0.22% /usr/local/sbi
   12 root       -92    -     0K   328K WAIT    0   0:01   0.14% [intr{irq268:

**Comment by mimugmail** [comment]
Hardware specs missing, throughput, services used.

For me it sounds you have a process running disturbing the flow like IPS, maltrail or whatever

**Comment by yhap2003** [comment]
Using a Soekris box net6501-70 Board. - http://www.soekris.com/products/net6501-1.html
2xTranscend 4GB SLC mSATA SSD (mirrored)

Service | Description | Status
configd | System Configuration Daemon |  
dhcpd | DHCPv4 Server |  
dhcpd6 | DHCPv6 Server |  
dyndns | Dynamic DNS |  
ifgroups | Interface groups |  
ipfw | Shaper |  
login | Users and Groups |  
mdns-repeater | MDNS Repeater |  
ntpd | Network Time Daemon |  
openssh | Secure Shell Daemon |  
pf | Packet Filter |  
radvd | Router Advertisement Daemon |  
syslog-ng | Remote Syslog |  
syslogd | Local Syslog |  
unbound | Unbound DNS |

**Comment by mimugmail** [comment]
Throughput while this cpu spike?

**Comment by yhap2003** [comment]
downloading a 16GB game at 35Mbps.

**Comment by mimugmail** [comment]
Can you try disabling shaper and restart?

**Comment by yhap2003** [comment]
I did tried that. I initially thought it might be because it needs to analyse all the packets so I disabled it along with QOS and VLAN, retarted the box, tried it and still the same result.

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/core/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
