### ISSUE TITLE
OpenVPN/UDP multihomed is losing packets

### ISSUE THREAD

**Issue by noseshimself** [opnsense/core#4004]
**Describe the bug**
UDP connections with OpenVPN connections on multihomed OpnSense systems are (randomly) taking a long time to come up or fail completely.

Please see the openvpn man page:

> –multihome
> Configure a multi-homed UDP server. This option needs to be used when a server has more than one IP address (e.g. multiple interfaces, or secondary IP addresses), and is not using –local to force binding to one specific address only. This option will add some extra lookups to the packet path to ensure that the UDP reply packets are always sent from the address that the client is talking to. This is not supported on all platforms, and it adds more processing, so it’s not enabled by default.Note: this option is only relevant for UDP servers.
> Note 2: if you do an IPv6+IPv4 dual-stack bind on a Linux machine with multiple IPv4 address, connections to IPv4 addresses will not work right on kernels before 3.15, due to missing kernel support for the IPv4-mapped case (some distributions have ported this to earlier kernel versions, though).
> 
> A clear and concise description of what the bug is, including last known working version (if any).
> 
> *Tip*: to validate your setup was working with the previous version, use opnsense-revert (https://docs.opnsense.org/manual/opnsense_tools.html#opnsense-revert)
> 

**To Reproduce**
1) Set up a multihomed OpnSense system; to add to the confusion, put several layers of NAT in front of it which makes triggering the problem easier.
2) Set up an openvpn server with the options to bind to any interface and using UDP (or UDP4)
3) Connect to the server.

4) Patching the configuration by adding a line "multihome" in the advanced configuration section solves the proble,

**Expected behavior**
Connection should come up within 30s.

**Additional context**
A change in the UI --> options generation should be added. If Interface is set to "any" AND any kind of UDP is used, the option "multihome" has to be added to the generated openvpn configuration file.
Not removing the ability to add own configuration options in future OpnSense versions should be reconsidered.

**Environment**
Current OpnSense with openvpn 2.4.8 as of today. Problem is showing up on all openvpn 2.4.* versions.

**Comment by AdSchellevis** [comment]
@noseshimself https://github.com/opnsense/core/commit/8b5a54e0307f11655d99ddf5254ff5769b5fa6ba should to the trick.
