### ISSUE TITLE
Alias Groups/List 

### ISSUE THREAD

**Issue by banym** [opnsense/core#4006]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[-] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[-] I have searched the existing issues and I'm convinced that mine is new.

**Is your feature request related to a problem? Please describe.**
If you have big lists of aliases the interface makes it complicated to keep track of all networks and hosts contained in one alias. 

**Describe the solution you'd like**
It would nice to have a new type of alias that only can contain other aliases. It could be called "alias group". The view of the alias group maybe should not only show the containing aliases but resolv and display the description in table view or similar. That would make it easier to manage the aliases in one group and review and audit them in a quick way what the alias means. 

The alias group only should be able to contain other aliases. No mixed types and manual defined networks or hosts. 

No free text input within the interface only alias selection. The interface should make it possible to select the aliases maybe from table view with multiple selection to make creation of an alias group safe and easy. 

**Describe alternatives you've considered**
A table view that resolves the alias description of the elements. 

**Additional context**
The import / export is not an option for all administrators. Some of them don't want to handle json input output.

**Comment by AdSchellevis** [comment]
@banym https://github.com/opnsense/core/commit/7ee060456b735d25bd7cabc3e14e9b483330f231 should do the trick. 
![image](https://user-images.githubusercontent.com/9783985/77914342-0d2dfd00-7296-11ea-8864-2336ea5cb324.png)
