### ISSUE TITLE
Firefox requires login twice before it logges in.

### ISSUE THREAD

**Issue by banym** [opnsense/core#4007]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[-] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[-] I have searched the existing issues and I'm convinced that mine is new.

**Describe the bug**
With Firefox using different opnsense firewall interface the login does not work with the first login. Entering the same data twice directly after the login page apears again works then. Access the same firewall interfaces with chrome works with first login.

*Tip*: to validate your setup was working with the previous version, use opnsense-revert (https://docs.opnsense.org/manual/opnsense_tools.html#opnsense-revert)

**To Reproduce**

1. Use latest Firefox
2. Access firewall on GUI 
3. Enter login data
4. After the page reloads and redirects you back to login page enter same data again

**Expected behavior**
First login should work with all browsers.

**Environment**
Firefox 74.0
OPNsense 20.1.3-amd64

**Comment by AdSchellevis** [comment]
I'm afraid this is browser related, seen some weird glitches in the past with Chrome as well.

**Comment by fichtner** [comment]
I have the Chrome issue, less frequent now than before. Chrome would send a wrong CSRF token the first time even though it should have loaded the page fresh. I never found out why on the server-side so I am also assuming this is client-related.

**Comment by banym** [comment]
Could it help to set the headers to not cache the GUI at all?

**Comment by fichtner** [comment]
<img width="418" alt="Screenshot 2020-03-28 at 7 32 50 AM" src="https://user-images.githubusercontent.com/1915288/77816821-68a99080-70c6-11ea-86cf-de2b6a315860.png">

:)

**Comment by banym** [comment]
Well, than I will try to find a way to reproduce it in a stable way to have a closer look what I see on client side.

**Comment by bsd-source** [comment]
Environment
Firefox 74.0
OPNsense 20.1.3-amd64

I'm using the same Firefox and OPNsense version as banym. I have no issues with logging in the firt time.

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/core/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
