### ISSUE TITLE
OpenVPN Client Export PKS Password Error on Export

### ISSUE THREAD

**Issue by devopsmyth** [opnsense/core#4008]
**Describe the bug**
When trying to export an OpenVPN Client archive with a PKS password instead of Windows Stored cert, I get the following error:

```
An API exception occured
Error at /usr/local/opnsense/mvc/app/library/OPNsense/OpenVPN/BaseExporter.php:68 - openssl_pkcs12_export(): cannot get private key from parameter 3 (errno=2)
```

**To Reproduce**
1. Go to https://firewall/ui/openvpn/export
2. Uncheck Windows Certificate System Store
3. Enter a password into P12 Password/Confirm
4. Click the download icon "cloud with down arrow towards bottom right"
5. See API error

An API exception occured
Error at /usr/local/opnsense/mvc/app/library/OPNsense/OpenVPN/BaseExporter.php:68 - openssl_pkcs12_export(): cannot get private key from parameter 3 (errno=2)

**Expected behavior**
A downloaded OpenVPN archive with password protection on the certificate file.

**Environment**
Latest Production 

**Versions**
OPNsense 20.1.3-amd64
FreeBSD 11.2-RELEASE-p17-HBSD
OpenSSL 1.1.1d  10 Sep 2019
CPU Type | Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 cores)

**Comment by AdSchellevis** [comment]
Most likely scenario is that the private key isn't stored on the firewall, the message could be more user-friendly, but to export a pkcs12 it needs both (public + private key)

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/core/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
