### ISSUE TITLE
Groups with space in name are invalid

### ISSUE THREAD

**Issue by syserr0r** [opnsense/core#4009]
## Environment:
- Currently running 20.1.3
- System set-up with auth from both 'Local Database' and 'AD LDAP + TOTP' server connecting to AD
- Both AD and Firewall have 'VPN Users' group; LDAP filters memberOf to 'VPN Users' group
- Users created previously that are part of the 'VPN Users' group remain so
  - Note: AD 'VPN Users' group used to be called 'VPN Access' -- this was renamed to 'VPN Users' and LDAP filter updated; OPNsense group has always been called 'VPN Users'

## To Reproduce:
- 'Import' a new user from LDAP
  - After adding, user **does not** have 'VPN Users' membership in OPNsense
- Edit user to add 'VPN Users' membership
- After some period of time (< 30 mins) the user no longer shows as a member of 'VPN Users'
- This entry is shown in the system logs: 
```
opnsense: /system_usermanager.php: The command '/usr/sbin/pw 'groupadd' 'VPN Users' -g '2000' -M '2001,2007,2006,2005,2009,2008,2010,2012'' returned exit code '65', the output was 'pw: invalid character ` ' at position 3 in userid/group name'
```

Renaming the group to `VPN` appears to have worked around the issue -- I'm not sure if the AD LDAP linking is related or if this is just spaces in group names are not handled well

**Comment by AdSchellevis** [comment]
groups with spaces aren't allowed, when trying to add one in the UI it will signal an error like:
![image](https://user-images.githubusercontent.com/9783985/77853867-d947ce80-71e6-11ea-80ac-5d69eda4e32b.png)

**Comment by syserr0r** [comment]
The group was created a long time ago -- although odd that it worked as long as it did.

Nothing to be done then, other than possibly correcting old group names?
