### ISSUE TITLE
submenu items should collapse when clicking on another one like the top menu

### ISSUE THREAD

**Issue by fichtner** [opnsense/core#401]

**Comment by fichtner** [comment]
You're on fire, many thanks! :)

Behaviour remains a little weird when switching back and forth between parent menus and now collapses on all clicks, which looks a bit jumpy?

**Comment by AdSchellevis** [comment]
Oops, I should have filtered on the non "mainmenu" parent items... will be fixed in the next commit.

**Comment by fichtner** [comment]
Way better, thanks again. :)

**Comment by fichtner** [comment]
@AdSchellevis  Looking at the commits later I was thinking if we could further shrink the menu size, maybe by providing a render call through MVC going directly to the volt (partial maybe?). Old GUI parts will still be there for a bit longer. What do you think?

**Comment by fichtner** [comment]
Not shrink, remove duplication I mean...

**Comment by AdSchellevis** [comment]
Don't know, it's not very nice doing it twice, but integrating volt to generate a partial maybe a bit of an overkill here..

**Comment by fichtner** [comment]
Ok, nevermind. :)

**Comment by fichtner** [comment]
One tiny issue left: when collapsing and expanding back into the original menu section, submenu section doesn't automatically expand back, losing the background highlight visibility. It works for non submenu items, but only because they don't have to expand. :)

**Comment by AdSchellevis** [comment]
I know, it's a minor glitch we have to live with for now... it's not very easy to fix.
