### ISSUE TITLE
PR_CONNECT_RESET_ERROR on apply modification

### ISSUE THREAD

**Issue by Math43** [opnsense/core#4010]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[X] I have searched the existing issues and I'm convinced that mine is new.

**Describe the bug**
After adding a rule or a virtual ip, after press "Apply", browser is loading during a few seconds and return me a PR_CONNECT_RESET_ERROR. I'm not sure when the issue happen first but I think it's when I editing a virtual IP.

If I have open a ssh session on the firewall to watch the logs i'm disconnected.

I'm not able to see anything in the logs, is there any way to have more verbose logs of the GUI ?

**To Reproduce**
Edit and apply a virtual IP

**Expected behavior**
Browser respond with PR_CONNECT_RESET_ERROR .

**Environment**
OPNsense 20.1.3-amd64 on ESX6.5

**Comment by Math43** [comment]
After investigation, PR_CONNECT_RESET_ERROR occurs on apply button of Aliases, Virtual IP, firewalls pages.

Problem seems to be bound to gateway. I've two wan interfaces so two gateways configure with monitoring enable, if a disable gateway monitoring no more "PR_CONNECT_RESET_ERROR"

Config to avoid error is as following:
```
  <gateways>
    <gateway_item>
      <interface>opt5</interface>
      <gateway>A.B.C.D</gateway>
      <name>WAN_GTW_V6</name>
      <priority>240</priority>
      <weight>1</weight>
      <ipprotocol>inet</ipprotocol>
      <interval/>
      <descr>WAN outgoing via public vlan 6</descr>
      <monitor_disable>1</monitor_disable>
      <defaultgw>1</defaultgw>
    </gateway_item>
    <gateway_item>
      <interface>wan</interface>
      <gateway>E.F.G.H</gateway>
      <name>WAN_GTW_V7</name>
      <priority>250</priority>
      <weight>1</weight>
      <ipprotocol>inet</ipprotocol>
      <interval/>
      <descr>WAN outgoing via public vlan 7</descr>
      <monitor_disable>1</monitor_disable>
      <force_down>1</force_down>
    </gateway_item>
  </gateways>
```
Regards,
Math

**Comment by fichtner** [comment]
This probably relates to  9b957e31d6's statement of "everything else is GUI trigger-happy disruption", however, if the GUI requests a filter reload and default gateway changes then this behaviour will still occur as the page in question calls filter_configure() where the gateway switching resides on apply.

**Comment by fichtner** [comment]
Thinking more about this... can you tell us if you connect to the GUI directly or indirectly? Could you also attach the system log snipped from when you trigger this behaviour?

**Comment by Math43** [comment]
Could you "elaborated" directly or indirectly for the GUI, i'm not sure if my answer is appropriate but i'm connecting to the firewall with an mgmt ip on a mgmt interface of the opnsense, no routing is used, i'm directly connected.

How to find the corresponding system log ?

Thanks !

**Comment by fichtner** [comment]
Directly attached network, or some form of routing I meant, so then it's directly attached.

Log is under System: Log Files: General.


Cheers,
Franco

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/core/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
