### ISSUE TITLE
OpenVPN: UDP Routing problem with SIP and RTP packets

### ISSUE THREAD

**Issue by Freddyvdh** [opnsense/core#4011]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[x] I have searched the existing issues and I'm convinced that mine is new.

**Describe the bug**
I'm using the OPNsense with OpenVPN, which works fine until now. We started using Softphones because of the corona virus and I get some issues:
Outgoing call: The called can here me, but I can not hear him.
Incoming call: The called can here me and I can hear him.

I made some tests and found out following by packet capture on the OPNsense:
On a outgoing call the RTP packets the VPN clients sends the outgoing packets through the tunnel, but the incoming packets are not sent through the VPN tunnel, but to the WAN interface.
On the incoming call the outgoing and incoming RTP packets are send through the tunnel as aspected.

I also checked the States Dump and filtered by the VPN client and RTP port and recognized, that the arrow for source -> router -> destination is different:

Outgoing call (not working):
![States Dump not working](https://user-images.githubusercontent.com/6376400/78079378-48225480-73ac-11ea-96f2-aebe59f36639.png)

Packet captures:
IGB0: LAN
IGB1: WAN (Group is used, default is IGB1, backup IGB2)
![packetcapture_igb0](https://user-images.githubusercontent.com/6376400/78080925-9127d800-73af-11ea-89d8-0352ceae0bd4.png)
![packetcapture_igb1](https://user-images.githubusercontent.com/6376400/78080927-9422c880-73af-11ea-988f-9bf70004c9f8.png)
![packetcapture_ovpns1](https://user-images.githubusercontent.com/6376400/78080934-96852280-73af-11ea-9550-5817e7fac377.png)

Incoming call (working):
![States Dump working](https://user-images.githubusercontent.com/6376400/78079473-7d2ea700-73ac-11ea-9261-f0b8a4b56c90.png)

![packetcapture_igb0](https://user-images.githubusercontent.com/6376400/78080952-9e44c700-73af-11ea-8522-9db78e902912.png)
![packetcapture_igb1](https://user-images.githubusercontent.com/6376400/78080962-a13fb780-73af-11ea-97ca-aa20c1f92080.png)
![packetcapture_ovpns1](https://user-images.githubusercontent.com/6376400/78080968-a4d33e80-73af-11ea-8106-6c675132ea9c.png)

VPN Client is 10.10.11.38
Telephone system is 192.168.252.3

After an incoming call, the outgoing call works fine too, until an undefined time. Sometimes it happens, that I can't hear the called anymore.

Sometimes it happens, that the client can not register, because no response sip packets are received.

**Environment**
Software version used and hardware type if relevant.
OPNsense 20.1.3-amd64
APU2 board

**Comment by Freddyvdh** [comment]
Hi,

means the label support, that we need to buy a [support ticket](https://opnsense.org/support-overview/commercial-support/)?

Another hint: When the packets are not routed correctly and I remove the wrong state entry in the States Dump view, after that the packets are routed correctly after a second.

**Comment by AdSchellevis** [comment]
Not necessarily, other people may step up, but we as core team can only spend limited time on free support.

**Comment by fichtner** [comment]
"support" short for "community support" means that this issue is free for all community members to help out on a volunteer basis, see https://github.com/opnsense/core/blob/master/CONTRIBUTING.md#issue-reports

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/core/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
