### ISSUE TITLE
Support dnsmasq and pf Tables

### ISSUE THREAD

**Issue by frankenbubble** [opnsense/core#4014]
a feature of t1n1wall is that you can create a pf Table (called ip pools from when it was ipf based , before it moved to pf) and have it populated by the ip address that dnsmasq resolves designated fqdns to.   

t1n1wall doesn't have a mechanism to prune the tables, but recommends setting a cron job to prune old entries out (flush table based on table entry time, or set max-ttl in dnsmasq and flush entries older than that set ttl)

https://sourceforge.net/p/t1n1wall/code/129/

This allows you to have a firewall rule based on fqdns, that keeps current

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/core/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
