### ISSUE TITLE
Hostcentral mirror is gone

### ISSUE THREAD

**Issue by fukawi2** [opnsense/core#4015]
[x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[x] I have searched the existing issues and I'm convinced that mine is new.

**Describe the bug**
The mirror "Hostcentral (HTTP,Melbourne, Australia)" appears to have deleted their opnsense mirror. The URL returns 404 now for the top-level directory http://mirror.as24220.net/opnsense/

**To Reproduce**

1. Select "Hostcentral (HTTP,Melbourne,Australia)" in System -> Firmware -> Settings
2. Attempt to update opnsense firmware.

**Expected behavior**
Mirror provides updates.

**Relevant log files**
```
# opnsense-update
Updating OPNsense repository catalogue...
pkg-static: http://mirror.as24220.net/opnsense/FreeBSD:11:amd64/19.7/latest/meta.txz: Not Found
repository OPNsense has no meta file, using default settings
pkg-static: http://mirror.as24220.net/opnsense/FreeBSD:11:amd64/19.7/latest/packagesite.txz: Not Found
Unable to update repository OPNsense
Error updating repositories!
```

**Environment**
OPNsense 20.1.r_12-amd64

**Comment by fichtner** [comment]
@fukawi2 thanks for the report! I contacted the maintainer for assistance.

**Comment by fichtner** [comment]
It's back now, pending a bit of audit in the next 24 hours. :)
