### ISSUE TITLE
use firewall groups to group the menu when interfaces are listed

### ISSUE THREAD

**Issue by fichtner** [opnsense/core#4016]
One issue is the firewall rules menu which will not directly benefit from this...

If we ever need to change this to where it was it would be good to add a switch to individual groups to not group interfaces in the GUI. This way we can have the best of both worlds... arrange a certain way, use another way.

**Comment by fichtner** [comment]
@AdSchellevis e9eb81a87f38 should fix all use cases as discussed, even #ref usage :)

**Comment by AdSchellevis** [comment]
@fichtner nice catch, looks good at a first glance, I'll do some more testing later, but we probably leave this on devel for at least one version

**Comment by fichtner** [comment]
Some fixes and fe3266033843, we might come back to firewall rules grouping after this ships in 20.7. Too much complexity there and too little experience with the practicality of it yet.
