### ISSUE TITLE
Dashboard notices do not fit on line

### ISSUE THREAD

**Issue by NOYB** [opnsense/core#4018]
Dashboard notices do not fit on line.  The left portion is truncated.  The narrower the browser window the more that is truncated.  See attached image which is from full screen browser and still truncated.

OPNsense 20.7.b_29
![Snap1](https://user-images.githubusercontent.com/1977521/78463097-e56fd800-768d-11ea-89ef-bfa902a7b2c6.jpg)

**Comment by fichtner** [comment]
@AdSchellevis it might be a good point in time to remove file_notice() and related code? They are not supported by MVC anyway.

**Comment by AdSchellevis** [comment]
@fichtner probably, yes, only current issue as far as I see is the lack of feedback when reloading the filter, if we fix that, the few messages left could just go to syslog.

**Comment by fichtner** [comment]
something like an API error popup? I realise it requires a bit of async functionality, but maybe something that uses syslog-ng to pipe the error for one-time use?

**Comment by AdSchellevis** [comment]
I haven't given it much thought yet, but using syslog output as events works like a charm indeed, using the same to catch carp changes. We probably need some logic to set filters so the pattern is reusable.

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/core/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
