### ISSUE TITLE
Firewall: problem with select all when using filter on category

### ISSUE THREAD

**Issue by lastuptodate** [opnsense/core#4020]
**To Reproduce**
1. Go to Firewall -> WAN
2. Add a first rule with Category "Test1"
3. Add a second rule with Category "Test2"
4. Filter view on Category "Test1"
5. Click on the top little case "select all"
6. Click on the bottom "delete selected"

All rules have been deleted :-(

**Expected behavior**
Only the rule Test1 should be deleted because of filter Test1

**Screenshots**
![opnsense](https://user-images.githubusercontent.com/7996346/78658304-4e439400-78ca-11ea-87a5-e5e6a4919ad8.PNG)

**Environment**
Software version used and hardware type if relevant.
e.g.:

OPNsense 20.1.3

**Comment by AdSchellevis** [comment]
@lastuptodate can you try https://github.com/opnsense/core/commit/285f7c65edae7673ed317a30557518f44993960e

From a console:
`
opnsense-patch 285f7c6
`

**Comment by lastuptodate** [comment]
Thank for your reactivity !
Your path is working fine, thank you so much!
We can close this case
