### ISSUE TITLE
Routing: ipsec route not applied for IPSec route-based interface after reboot

### ISSUE THREAD

**Issue by lastuptodate** [opnsense/core#4021]
**Describe the bug**
Given I have a route-based IPSec VPN
Given I have this VPN with connection method "start immediate"
Given I have manual routes for this network (routes using VPN interface)

If i reboot OPNSense server, route are applied before VPN interface came up.
As VPN isn't yet UP, VPN routes are not applied.
When VPN came up, I need to manually re-apply route in order to have ipsec rules UP

**Expected behavior**
VPN routes should be also applied after VPN came UP

**Comment by fichtner** [comment]
Probably #3414, but missing basic info.

**Comment by AdSchellevis** [comment]
A basic setup (two machines connected using VTI, static route setup between them), does work on our end after reboots.

**Comment by mimugmail** [comment]
Maybe there is a process or service where IPsec comes up too late?

**Comment by lastuptodate** [comment]
Sorry for this case, as fichtner say, I confirm that this is a Duplicate of https://github.com/opnsense/core/issues/3414#
I close this case so we can continue on #3414 
Thank you all for your reactivity

**Comment by AdSchellevis** [comment]
@mimugmail logically the status from IPsec shouldn't matter that much, since vti is setup separately as a "dump" tunnel device in `ipsec_configure_vti`. I haven't seen it fail before.

**Comment by lastuptodate** [comment]
Post #3414 updated
