### ISSUE TITLE
OpenVPN Client kill switch not working

### ISSUE THREAD

**Issue by Mirhol** [opnsense/core#4023]
**Describe the bug**
The client kill switch on the connection status page of OpenVPN is not working. If it is pressed nothing happens.
Was reported with [Issue 687](https://github.com/opnsense/core/issues/687) and should have been fixed with 16.7.

**To Reproduce**
1. Set up OpenVPN Server
2. Connect a client
3. Go to VPN>OpenVPN>Connection Status
4. Try to kill client connection

**Expected behavior**
The client connection should be terminated.

**Screenshots**
![image](https://user-images.githubusercontent.com/63337562/78755467-80f89580-7979-11ea-943a-6389f21a9765.png)

**Environment**
Software version used and hardware type if relevant.
e.g.:

OPNsense 20.1.3-amd64
FreeBSD 11.2-RELEASE-p17-HBSD
OpenSSL 1.1.1d 10 Sep 2019
Tested on different hardware

**Comment by Mirhol** [comment]
A little more testing showed the problem only occurs when there is no Interface defined for the OpenVPN Server:
![image](https://user-images.githubusercontent.com/63337562/80197543-11dc9b80-861f-11ea-9bab-66ab121924c8.png)

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/core/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.

**Comment by IB-Rahn** [comment]
Hello, this issue is still not resolved and we experience the same behaviour as OP.

**Comment by Alwaysin** [comment]
I've shamelessly copied the issue to #5038 because this one is wrongly closed
