### ISSUE TITLE
Log viewer:  download button and full selection

### ISSUE THREAD

**Issue by AdSchellevis** [opnsense/core#4026]
The download button uses the same row limit as the screen, which can be impractical if one wants to download the file or all messages of a certain type. 

We should either dump all or offer the ability to download all (filtered) results.

**Comment by fichtner** [comment]
yes, pass the filter and download all matches (no filter all lines)

**Comment by AdSchellevis** [comment]
now it's dumping the grid, so I have to change that, probably add a new endpoint.

**Comment by AdSchellevis** [comment]
cc @jschellevis https://github.com/opnsense/core/commit/4bdb4cfeb4f0bfc318f10040c9862f64d8c520b1
