### ISSUE TITLE
Default rule missing to pass icmpv6 from source "::" for ND, RA and so on

### ISSUE THREAD

**Issue by IsaacFL** [opnsense/core#4028]
[-] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
yes

[-] I have searched the existing issues and I'm convinced that mine is new.
it currently exists in OPNsense, I have seen it in other routers so I knew to look for it here.

**Describe the bug**
There is a default set of rules in OPNsense to pass specific ICMPv6 packets at all times, for things like ND, RA, and so on. These are in place to ensure these features function properly even without a user adding rules to pass them.

Currently these rules do not include a rule to pass from a source of :: to the multicast destination.  The address "::" is defined as the unspecified address.

When some ipv6 devices initially start up they send a router solicitation with a source address of "::" and currently the OPNsense does not have a rule to pass them into the router. 

This can cause problems with some devices not able to verify they are connected to the router. You can verify by seeing entries in the firewall log that are being dropped with "::" as the source trying to do router discovery.

RFC 4861 Neighbor Discovery in IPv6 has cases where the source address is unspecified ("::")
i.e. Par 4.1 Router Solicitation Message Format

```
Source Address
                 An IP address assigned to the sending interface, or
                 the unspecified address if no address is assigned
                 to the sending interface.

  Destination Address
                 Typically the all-routers multicast address.
```

Fix:
Add rule to pass inet6 proto ipv6-icmp from :: to ff02::/16
There is currently a rule to pass from {fe80::/10} to {fe80::/10,ff02::/16}  icmp6-type {128,133,134,135,136}, so just need to add :: as a source.

**Environment**
Versions	OPNsense 20.1.4-amd64
FreeBSD 11.2-RELEASE-p18-HBSD
OpenSSL 1.1.1f 31 Mar 2020

**Comment by AdSchellevis** [comment]
@IsaacFL can you check https://github.com/opnsense/core/commit/25630084d05bbac336b04566c1872506ca944ba9, before merging to master I would like to ask @fichtner to verify if he agrees on this too. Reading the RFC, it looks like the right thing todo.

**Comment by IsaacFL** [comment]
I commented that the destination needs to also include the multicast (
ff02::/16 )  as a destination.

**Comment by AdSchellevis** [comment]
@IsaacFL miscommunication it seems, the first commit contained the wrong address.

**Comment by AdSchellevis** [comment]
closing the issue, as discussed in https://github.com/opnsense/core/commit/25630084d05bbac336b04566c1872506ca944ba9#commitcomment-38417763, we can extend addresses later if needed
