### ISSUE TITLE
NAT not applied to new OPT1 if.

### ISSUE THREAD

**Issue by RogerHall** [opnsense/core#4033]
OPNsense 20.1.4-amd64

I have had an install for some time now with WAN and LAN interfaces only. Today I added OPT1. I had a single new rule to allow all traffic in on OPT1. The behavior I saw was that I could ssh from LAN to OPT1, but it took several seconds for password prompt. Ping from LAN to OPT1 ok. ssh and ping from OPT1 to LAN or public sites failing.

After hours of confusion, the problem was fixed by performing the following action.
Firewall --> NAT --> Outbound.
Change from: "Automatic outbound NAT rule generation" 
Change to: "Hybrid outbound NAT rule generation". 

That was it. Everything started to work after that. I then reverted the outbound NAT back to the original setting and it continued to function correctly.

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/core/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
