### ISSUE TITLE
fetchACLs.py return http code 406

### ISSUE THREAD

**Issue by anja98** [opnsense/core#4034]
**Describe the bug**
Proxy is unable to download from remote ACL url with "fetchACLs.py" return http code 406 

This is because fetchACLs.py does not set the HTTP header user-agent properly. The default user-agent "python-requests/2.22.0" is can cause errors if the remote ACL server has Mod_Security configured.

To fix this, set the HTTP header user-agent in fetchACLs.py to something like:
'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36'

**To Reproduce**
1. Go to 'Services: Web Proxy: Administration'
2. Click on 'Remote Access Control Lists'
3. Add a new remote ACL with URL 'https://edgearmour.io/support/edgephish.tar.gz'
4. Remote ACL download fail with HTTP error code 406
5. See error HTTP code 406 in System > Log Files > General

To simulate the error using curl:
```
# curl -H 'user-agent: python-requests/2.22.0' https://edgearmour.io/support/edgephish.tar.gz

returns:
<head><title>Not Acceptable!</title></head><body><h1>Not Acceptable!</h1><p>An appropriate representation of the requested resource could not be found on this server. This error was generated by Mod_Security.</p></body></html>
```
**Expected behavior**
Remote ACL should be download properly 

**Relevant log files**
System > Log Files > General shows the following log: 
/fetchACLs.py: proxy acl: error downloading https://edgearmour.io/support/edgephish.tar.gz (http code: 406)

**Additional context**

**Environment**
Software version used and hardware type if relevant.
OPNsense 19.7.10_1-amd64

**Comment by AdSchellevis** [comment]
It's more an upstream issue, if the provider chooses to not accept automated scripts (using curl, python, etc), I'm not sure we should try to trick ourselves into acceptance. I wouldn't mind changing the agent to OPNsense/$version or something similar, but choosing a random agent from a browser is not really preferred.

**Comment by fichtner** [comment]
In the crash reporter we already use "OPNsense/20.1.4", but not to reach the outside. The side effects of this are uncertain. FWIW, cURL uses "curl/7.64.1" by default.

If that is the upstream policy and it can change for whatever reason I think we should simply remove the list if we have it somewhere as a standard list. If not, this can always fail for one reason or another.

In any case you should reach out to the provider of the list and ask them why such a policy is in place. If it is used to avoid scripts from leveraging the lists automatically, we would be circumventing usage terms.


Cheers,
Franco

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/core/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
