### ISSUE TITLE
The traffic shaper isn't working properly

### ISSUE THREAD

**Issue by Dark-over-lordz** [opnsense/core#4035]
Hi, all.

I don't have much experience with forum/social media stuff, so if I mess something up, please overlook this. I'm actually studying biomedical science at uni and play games on console most of the time; nothing to do with programming or computers.

I moved from pfsense to opnsense because it has good traffic shaping options. I setted up the traffic shaper according to the opnsense manuel to distribute bandwith evenly, while it works properly and does distribute evenly, when the actual internet speed drops 50% less than the stated value/bandwith on the pipe the distribution doesn't work.

This could be tested by having two computers connect to the opnsense and download from many different servers/sources simultaneously using something like DAP which usually downloads at the maximum speed of the broadband package if enough sources/files are started at the same time. The sources could be dummy files from tele2 and others.

When the speed is set to 350 down and 37 up, and the actual internet speed is similar, the shaper divides the speed roughly 50:50, but when the actual internet speed fell below 100 then there was no shaping and one computer had 90-95 for itself while the other had 1-5. I think because 350 / 2 = 175, while at the time the actual internet speed fell to 100, so / 2 = 50 which is less than 175 (175 being 50% of 350) so no shaping was done as the value of each computer when evenly divided (50) was less than the stated division (175).

As internet package speeds or stated speeds vary greatly in some cases to what actual speeds one gets and is also subject to great variation throughout the day, the bandwith value should be loosely relative to the value stated or should work by value +-90%. It could also be based on wan choking set point which could be a percentage or based on the amount/speed of traffic passing through the wan.

Is there a solution to this, where the bandwith is equally distributed among, say 6 users, and stays relatively stable even when the actual internet speed fluctuates greatly, while as members leave, the bandwith is redistributed amongst active users?

Thank you for your time today.

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/core/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
