### ISSUE TITLE
GIF Tunnel :  Firewall rules only func in Group 

### ISSUE THREAD

**Issue by QDaniel** [opnsense/core#4039]
When add a HE.net Tunnel (https://docs.opnsense.org/manual/how-tos/ipv6_tunnelbroker.html)
Firewall rules to the Interface has only effects when it set as floating  or in a Group.
Direct Rules are saved correct to the protocol but don't pass.

**To Reproduce**
1. Add a GIF Tunnel (He.net)
2.  Assign Interface
3. Set Default gateway for IPv6
4. Set a IPv6 Adress from routed network to LAN interface

5. Add a pass Rule to allow icmp at GIF Interface -> NOT FUNC
6. Add a Interface Group with the GIF INterface as Member
7. Add a pass Rule to allow icmp at Group Interface -> ALL OK

** System  **
OPNsense 20.1.4-amd64
FreeBSD 11.2-RELEASE-p18-HBSD
OpenSSL 1.1.1f 31 Mar 2020

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/core/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
