### ISSUE TITLE
traffic graphs truncate IP

### ISSUE THREAD

**Issue by fichtner** [opnsense/core#404]
plus traffic graphs are truncated: https://forum.opnsense.org/index.php?topic=1443.0

**Comment by fichtner** [comment]
tech issue, needs proper replacement

**Comment by fichtner** [comment]
do not mix two issues, bad @fichtner :P

**Comment by AdSchellevis** [comment]
Can't reproduce on my end.... displays normally, when testing with a fake ip 999.999.999.998 
(page status_graph.php)

**Comment by fichtner** [comment]
I will ping the forum again, otherwise we close next time :)
