### ISSUE TITLE
Ipsec VTI MTU MSS UDP solution inside

### ISSUE THREAD

**Issue by lastuptodate** [opnsense/core#4042]
Hello Everybody !
Here is my setup:
Site A (10.21.0.0/16)----OpnSenseA-------ipsec VTI-------OpnsenseB------SiteB (198.18.0.0/26)

**Here is some solutions that I hope, will help people to understand MTU value on Ipsec (VTI in my exemple)...**

**FOR TCP:**
By default, ipsecX000 interfaces have 1400 MTU.
As I do not want to change MTU for all computers on SiteA and B, on both Opnsense (A +B), I put MSS value 1360 on ipsec interfaces (interfaces -> ipsec interface -> MSS).
This settings will add "max-mss 1320" on scrub ipsec interface (see /tmp/rules.debug)
Now, when my 2 sites wants to comunicate via TCP each others, they can "deal" MSS value and lowering to 1320.

In this exemple, capture from site A:
![TCP](https://user-images.githubusercontent.com/7996346/79455469-35835e80-7fed-11ea-82a5-e6d71f56a421.PNG)

- First line: Site A is sending MSS=1460 but this value will be decreased to 1320 when passing on OpnsenseA. Site B will received MSS=1320. 

- Second line: Site B was sending MSS=1460 but this value has been decreased to 1320 by OpnsenseB as you can see.

Site A and B are now sending 1320 frame each others for this TCP session.
No more TCP problem :-)

**FOR UDP:**
more complexe because UDP is not affected by MSS value.
In my case, a nagios server on site B was trying to fetch a snmp value from a server on site A
The snmp result value was so big that server on site A split UDP response (fragment):

![UDP1](https://user-images.githubusercontent.com/7996346/79456162-4da7ad80-7fee-11ea-844f-8b3594562700.PNG)

This fragment package travel without problem inside OpensenseA LAN, OpnsenseA Ipsec (and wan), OnsenseB Wan and Ipsec **BUT this UDP package is reassembled by OpnsenseB on LAN interface**:

![UDP2](https://user-images.githubusercontent.com/7996346/79456517-f0602c00-7fee-11ea-86ff-433f01dc2f76.PNG).

Aouch ! 1861 will never travel inside my B network and will never be delivered.
Snmp request from nagios was telling me: timeout.....

Why this package is reassemble ? because "scrub" is enable by default on OPNsense and by default scrub reassemble fragments...
When Firewall -> Settings -> Normalization is left by default and Mss value is applyied on ipsec interface, here is scrub config:

![scrub](https://user-images.githubusercontent.com/7996346/79457016-c65b3980-7fef-11ea-95d7-b9c6631a244d.PNG)

Here is what I have done on OpnsenseB:

![scrub2](https://user-images.githubusercontent.com/7996346/79459854-3a97dc00-7ff4-11ea-8a17-5b0ddd9636ca.PNG)

Result: 
![scrub3](https://user-images.githubusercontent.com/7996346/79459874-41265380-7ff4-11ea-897f-52a8853e7244.PNG)

My snmp package is no more reassemble and my snmp query/big response is working fine :-)

Don't forget to also modify OpnsenseA.

I hope this post will help some people.
I let admins change title, perhaps attach related issue, and finaly close this case
Best regards

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/core/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.

**Comment by igolman** [comment]
@lastuptodate thank you for sharing! 🍺

I had almost the same problem in VTI Route-based S2S Tunnel:
- ICMP/UDP worked
- TCP 
  - HTTP worked
  - HTTPs hanged on `Initiating SSL handshake.`

Setting the MSS value of VTI to 1360 on both ends and restarting the tunnel did help. 👍

Cheers!
