### ISSUE TITLE
flowd_aggregate crashes with KeyError: 'flow_finish'

### ISSUE THREAD

**Issue by awerner** [opnsense/core#4046]
**Describe the bug**
I upgraded to OPNsense 20.1.4-amd64 yesterday and noticed flowd_aggregate not starting. 
Resetting the netflow data and removing the ``/var/log/flowd.log*`` files helped, but I think flowd_aggregate should handle the KeyError withour crashing.

**To Reproduce**
- I'm using flowd, samplicate, surricata with ET Telemetry edition.

**Expected behavior**
flowd_aggregate starts normally

**Console Output**

```python
# python3 /usr/local/opnsense/scripts/netflow/flowd_aggregate.py --console
Traceback (most recent call last):
  File "/usr/local/opnsense/scripts/netflow/flowd_aggregate.py", line 224, in <module>
    Main()
  File "/usr/local/opnsense/scripts/netflow/flowd_aggregate.py", line 136, in __init__
    self.run()
  File "/usr/local/opnsense/scripts/netflow/flowd_aggregate.py", line 160, in run
    aggregate_flowd(self.config, do_vacuum)
  File "/usr/local/opnsense/scripts/netflow/flowd_aggregate.py", line 68, in aggregate_flowd
    for flow_record in parse_flow(prev_recv, config.flowd_source):
  File "/usr/local/opnsense/scripts/netflow/lib/parse.py", line 72, in parse_flow
    for flow_record in FlowParser(filename, recv_stamp):
  File "/usr/local/opnsense/scripts/netflow/lib/flowparser.py", line 182, in __iter__
    record['flow_end'] = record['recv_sec'] - (record['sys_uptime_ms'] - record['flow_finish']) / 1000.0
KeyError: 'flow_finish'

```

**Environment**
- ``OPNsense 20.1.4-amd64``
- ``Intel(R) Celeron(R) CPU  J3160  @ 1.60GHz (4 cores)``
- ``os-acme-client``
- ``os-dyndns``
- ``os-etpro-telemetry``
- ``os-freeradius``
- ``os-lldpd``
- ``os-netdata``
- ``os-wireguard``
- ``os-zabbix-agent``
- ``os-zerotier``

**Comment by AdSchellevis** [comment]
It's probably related to longer lasting flows, which don't have an end yet, it's likely difficult to reproduce.

**Comment by awerner** [comment]
@AdSchellevis Unfortunately I have not kept a backup of the flowd.log to reproduce the issue :(

**Comment by AdSchellevis** [comment]
@awerner no problem, https://github.com/opnsense/core/commit/0c3359689d600ba37a7b6beed810c3a817120b21 should prevent this from happening.
