### ISSUE TITLE
Wlidcard override in Unbound DNS prevents Unbound from starting

### ISSUE THREAD

**Issue by kuruoujou** [opnsense/core#4049]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

- [x] I have searched the existing issues and I'm convinced that mine is new.

**Describe the bug**
When adding a wildcard override to Unbound DNS, the service stops and reports an error involving a local-data redirect in the logs. Unbound doesn't start again unless the offending wlidcard override is removed. This has only been tested and confirmed as an issue when the domain matches the domain in System > Settings > General > Domain.

This is my first install of opnsense, so I do not know if this is regression.

**To Reproduce**
1. Go to Services > Unbound DNS > Overrides
2. Click "+" in the top-right to create a new override
3. Follow the instructions to create a wildcard override. This can be done with the following example settings:
    1. Host: *
    2. Domain: example.com (must match System > Settings > General > Domain)
    3. Type: A or AAAA
    4. IP: 192.168.1.100 (can be anything)
4. Click "Save"
5. Unbound will no longer be running. See error in Services > Unbound DNS > Log Files.

**Expected behavior**
A wildcard override to be created, and any domains not otherwise overridden to be directed to the wildcard IP.

**Relevant log files**
```
2020-04-20T17:32:08 | unbound: [47388:0] fatal error: Could not set up local zones
-- | --
2020-04-20T17:32:08 | unbound: [47388:0] error: local-data in redirect zone must reside at top of zone, not at <other-override> IN A <ip-address>
2020-04-20T17:32:08 | unbound: [47388:0] warning: duplicate local-zone <example.com>.
```

**Additional context**
This appears related to but distinct from #2331. In that issue, the Local Zone Type in Services > Unbound DNS > General was being explicitly set to "redirect". In this issue, it is implicit. The issue appears to be in core/unbound.inc, in this switch statement: https://github.com/opnsense/core/blob/e9eb81a87f38edf508d8c0c82f0ec2d086b448fc/src/etc/inc/plugins.inc.d/unbound.inc#L612-L627

What it's doing makes sense in general, however instead of updating the existing local-zone (which has already been determined to be an issue in #2331), it's duplicating the zone. Ultimately the problem is the same from Unbound's perspective, except now it has two local-zones to contend with instead of just one.

I'm really new to opnsense, as in less than a week, so my apologies if this has already been reported somewhere. I searched the web and GitHub, and all I could find was a single German-language post from last month with no responses, and I can't find the link again. If you need any more info, let me know.

**Environment**
OPNSense 20.1.4 (amd64, OpenSSL)
Intel® Core™ i5-4250U CPU @ 1.30GHz (4 cores)

**Comment by AdSchellevis** [comment]
Looking at the configuration it generates  (`/var/unbound/host_entries.conf`), it sounds reasonable it can't register local addresses to the local configured domain and redirect the same domain in full somewhere else.

The legacy code for unbound unfortunately isn't great, I see some directions to "fix" the issue, but none of them seem great at the moment:

- Validate that you can't redirect your own local domain (easy fix, doesn't solve anything, just prevents adding it)
- skip registering local domains on the zone ready to be redirected, a quick sweep in https://github.com/opnsense/core/blob/master/src/etc/inc/plugins.inc.d/unbound.inc shows quite some entries originating to `$config['system']['domain']`, which potentially should all be discarded when transferring the zone.

**Comment by kuruoujou** [comment]
Yeah, I’m not sure what the best route forward here would be, honestly. For my own personal case, I like having the wildcard so when I spin up a new service on my personal kube cluster, I don’t have to worry about setting up DNS on the router for it. It’s a minor thing though and not something that’s really a big problem for me.

I think for me the first solution is probably sufficient, but I’m not sure if it’s the best one. It seems to me like setting a wildcard should work even if there are local addresses configured. I don’t really know how to go about setting that up, though.

**Comment by AdSchellevis** [comment]
let's start with option 1 and leave the ticket open marked "help wanted", a workaround might be to just use a different domain for this machine if it's not really used.

**Comment by Melantrix** [comment]
In other DNS servers software and hosted solutions you are able to add a wildcard domain as a sort of catch all statement. 

So i think the solution is as follows:

if a request comes, check if there is a more specific match (an override). If not and if there is a wildcard statement return that record. If there is not a wildcard statement do a lookup or return NXDOMAIN. 

I think it's more a question of prioritizing the overrides in comparison with the wildcard record. 

I know that's it's harder then it looks, but a solution like this would be ideal. This is especially usefull for split dns zones. 

if you have a zone that's 'live' (so a .com or .eu address and not a .local) you sometimes end up with records for outside (and thus public ip's) and a local zone with the same records but with different ip's. In my case i have a wildcard in the external zone but it's not possible to have it internal because of this problem.

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/core/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.

**Comment by violuke** [comment]
This is still broken, tested today on OPNsense 20.7.8, could this be re-opened?

**Comment by toddritt** [comment]
I also still have this issue in: 
OPNsense 21.1.2-amd64
FreeBSD 12.1-RELEASE-p13-HBSD
OpenSSL 1.1.1j 16 Feb 2021

**Comment by CuBiC3D** [comment]
@AdSchellevis can we reopen this, since the plan was to actually fix it?

**Comment by AdSchellevis** [comment]
@CuBiC3D feel free to open a PR if you're planning to work on it, we'll reopen when there's viable progress. please read our guidelines for more details (https://github.com/opnsense/core/blob/master/CONTRIBUTING.md)

**Comment by zacheryph** [comment]
I manage to run into this issue after using opnsense for all of... 2 hours. It's kind of sad to see active issues that get closed with no solution, prevention, warning, nothing. This _IS_ an active issue no? I do understand not having the time or a particular people just not caring about this issue, but closed would imply resolved in some way? not... thrown on the floor, forgotten or, _it's not being worked on, we don't care_.

I still had this issue after removing an override, having _ONLY_ the wildcard remain and the settings domain not matching. So some something was hanging around after the fact..

* system > settings domain is `localdomain`
* add wildcard for `x.com`
* add host for `y.x.com`
* apply
* remove host for `y.x.com`
* apply
* continue to get local-data error and unbound not starting up

**Comment by fichtner** [comment]
TBH, just provide a PR or adjust the attitude. Both work for me. Project contributors do a lot each day and most of them on a voluntary basis. You can’t take away their achievements.

For everything else check the contribution guidelines. There are notes  issue interaction and closed state and timeouts. It’s all there really and I’m happy to explain if it isn’t glossed over like here.


Cheers,
Franco

**Comment by phedders** [comment]
I think there is an easy solution to this problem

`error:` **local-data in redirect zone must reside** at top of zone, not at dhcpclient1.mydomain IN A 10.1.1.4

This suggests to me that we only need to be able to indicate that an override entry must be at the end of the zone file - ***after*** all the other overrides and DHCP entries.

I'm not sure what the best way to do this in the interface is however.

**Comment by l-rossetti** [comment]
I still have the same issue, there's a way to solve it?

**Comment by AdSchellevis** [comment]
@l-rossetti  https://github.com/opnsense/core/issues/4049#issuecomment-617081011 << don't try to redirect your own local domain? which was also the proposed fix for this issue. PR's are still welcome.

**Comment by l-rossetti** [comment]
@AdSchellevis how to avoid the redirect on my local domain? Not sure I got it

**Comment by MrStarktastic** [comment]
I have the exact same issue that @LP0101 described and his workaround worked for me.
It's not very pretty IMO, so hoping this will be fixed someday. Maybe I will open up a PR if I have the time.
In general I believe the best idea is to prioritize wildcard entries below explicit ones.

**Comment by toxic0berliner** [comment]
same issue here, same workaround, for those wanting in and new to unbound conf like I just was 5 minutes ago : 
```
local-zone: "example.com" redirect
local-data: "example.com 86400 IN A 192.168.1.1"
local-zone: "mail.example.com" redirect
local-data: "mail.example.com 86400 IN A 192.168.1.2"
```

**Comment by deviantintegral** [comment]
For anyone else looking at this in relation to wildcards, it turns out you don't need to specify any sort of wildcard configuration. For example:

```
local-zone: "home.mydomain.ca" redirect
local-data: "home.mydomain.ca 300 IN A 192.168.20.213"
```

Will also work for `*.home.mydomain.ca` to resolve to 192.168.20.213.

**Comment by fede843** [comment]
This still not good. It does not integrate with the GUI. There is no way you can set a global domain under system properties, and then use the same domain as wildcard DNS Resolver.
It is a simple and fundamental feature to have. Am I missing something here?

**Comment by toxic0berliner** [comment]
If you're not too lazy as we are @fede843 you could open a feature request and mention we all here would like it in the GUI as well. But this issue being close I doubt it would ever become a feature. I would actually upvote you feature request 😉 Maybe even a Push Request would have more chances of catching the attention of the right peoples...

**Comment by RT-Tap** [comment]
Putting this here for anyone that comes here from google.
My fix was adding `*` to `Host` field when defining an override.

**Comment by ryanwinter** [comment]
Same solution here, in the UX you would enter the host as "*" and enter the subdomain in the "domain" field.
<img width="693" alt="image" src="https://github.com/opnsense/core/assets/10238039/07ee39e8-73c1-4b81-b117-45cb5ff8ef9e">

```
> nslookup a.test
Name:    a.test
Address:  192.168.0.1

> nslookup sub.test
Name:    sub.test
Address:  192.168.0.2
```

**Comment by gleitoncampos** [comment]
> Putting this here for anyone that comes here from google. My fix was adding `*` to `Host` field when defining an override.

For me, this workaround didn't work. With or without "*" in host crashs the Unbound service with "duplicate local-zone" error...

**Comment by RT-Tap** [comment]
> > Putting this here for anyone that comes here from google. My fix was adding `*` to `Host` field when defining an override.
> 
> For me, this workaround didn't work. With or without "*" in host crashs the Unbound service with "duplicate local-zone" error...
> 
> I just wanna to redirect all my local domain to my traefik... "*.domain.local > 192.168.1.1"

If i remember correctly Opnsense explicitly tells you not to use `.local ` for your local domain because issue will arise, I wanted to do the same thing but didn't after seeing that message I just don't remember when/where I saw it or why you shouldn't.

Also I'm assuming your LAN is 192.168.1.1 and so you put traefik on the same interface as opnsense? Why? I'm no expert but that doesnt sound safe like at all. I think you need to re evaluate your setup because unless your using a different port they would both be occupying port 80 on the same interface.

**Comment by gleitoncampos** [comment]
> > > Putting this here for anyone that comes here from google. My fix was adding `*` to `Host` field when defining an override.
> > 
> > 
> > For me, this workaround didn't work. With or without "*" in host crashs the Unbound service with "duplicate local-zone" error...
> > I just wanna to redirect all my local domain to my traefik... "*.domain.local > 192.168.1.1"
> 
> If i remember correctly Opnsense explicitly tells you not to use `.local ` for your local domain because issue will arise, I wanted to do the same thing but didn't after seeing that message I just don't remember when/where I saw it or why you shouldn't but that could be part of your issue.
> 
> Also I'm assuming your LAN is 192.168.1.1 and so you put traefik on the same interface as opnsense? Why? I'm no expert but that doesn't sound like a good idea. I think you need to re evaluate your setup because unless your using a different port they would both be occupying port 80 on the same interface anyway.

All the domains and IP mentioned are fictional, don't care about them.
BUT, the workaround that worked form me was: REMOVE opnsense from the domain, using just a placeholder like "opn.arpa.home" and in traefik create a route with the correct domain "opn.mydomain.tld" and add this name in hosts file inside opn to avoid warnings and errors in web interface

**Comment by scubbo** [comment]
I don't know if this is the same bug or not, though it seems similar - whenever I try to create a wildcard override, the service fails to start up, and logs show `local-data in redirect zone must reside at top of zone, not at *.<domain> TXT "<name of server>"`, where `<domain>` is the domain of the override and `<name of server>` is the name of the server the override was pointed at.

Note two differences from the original bug:
* `TXT "<name of server>"`, not `A <ip>` in the log message
* No `warning: duplicate local-zone` log message

This behaviour is consistent for `<domain>` being:
* The domain of the router
* A subdomain of the router
* A completely different domain

I'd be happy to create this as a separate issue if it warrants it, but I thought it best to raise it here in case it's simply a different representation of the same bug (though, [workarounds](https://github.com/opnsense/core/issues/4049#issuecomment-1294771636) suggested [above][(https://github.com/opnsense/core/issues/4049#issuecomment-1478058051) do not appear to work here)

**Comment by kub3let** [comment]
This is still broken, the workaround does not work for PTR lookups.

I'm using generic Split DNS with a Wildcard Override.

There is no way to setup a PTR override if you don't edit the Unbound config directly.

**Comment by scubbo** [comment]
That's disappointing. Should there be a change to the UI, then? For my installation (possibly not the latest), there's still an info caption reading "_Name of the host, without the domain part. Use "*" to create a wildcard entry._".

**Comment by instantdreams** [comment]
I was previously using the following configuration:
  * Domain Name Host: Azure DNS Zones
       * CNAME Record Example: nextcloud.example.com
       * CNAME Record Alias: example.duckdns.org
   * Dynamic DNS Host: Duck DNS
       * Duck DNS Domain: example
       * Duck DNS IP: [home network ip address]
   * Internet Service Provider: Fibre ONT
       * ONT Configuration: Bridge Mode to Personal Router
   * Router: Netgear RBR850
       * Port Forwarding: 80 to server edge
       * Port Forwarding: 443 to server edge
   * Server: edge
       * Docker Container: duckdns
           * Port: None
           * Function: Refreshes Duck DNS IP regularly
       * Docker Container: traefik
           * Port: 443 & 80 (https and http traffic)
           * Port: 8888 (web ui)
           * Function: Reverse Proxy
           * Configuration:
               * Domain Name: nextcloud.example.com
               * Scheme: http
               * Forward: services
               * Port: port
               * SSL Certificate: wildcard example.com

I replaced my Netgear Router with opnsense and for life of me could not work out how to forward wildcard queries to my reverse proxy. I finally found [various](https://utcc.utoronto.ca/~cks/space/blog/sysadmin/UnboundLocalDNSOverride) [suggestions](https://www.reddit.com/r/opnsense/comments/1318ork/unbound_dns_override_not_working_as_expected/) on the use of unbound overrides. I had the same problem described here.

My problem is that I had set my domain name to example.com, so a duplicate entry in the `host_entries.conf` file tripped the error.

The solution was to set my system domain to `home.arpa` and then add the wildcard override. Now my configuration looks like this:
  * Domain Name Host: Azure DNS Zones
       * CNAME Record Example: immich.example.com
       * CNAME Record Alias: example.duckdns.org
   * Dynamic DNS Host: Duck DNS
       * Duck DNS Domain: example
       * Duck DNS IP: [home network ip address]
   * Internet Service Provider: Fibre ONT
       * ONT Configuration: Bridge Mode to opnsense
   * Router: opnsense
       * Firewall : NAT : Port Forward : 80 to server edge
       * Firewall : NAT : Port Forward : 443 to server edge
       * Firewall : Rules: WAN : 80 to server edge
       * Firewall : Rules: LAN : 443 to server edge
       * Firewall : Rules: LAN : 80 to server edge
       * Firewall : Rules: LAN : 443 to server edge
   * Server: edge
       * Docker Container: duckdns
           * Port: None
           * Function: Refreshes Duck DNS IP regularly
       * Docker Container: traefik
           * Port: 443 & 80 (https and http traffic)
           * Port: 8888 (web ui)
           * Function: Reverse Proxy
           * Configuration:
               * Domain Name: immich.example.com
               * Scheme: http
               * Forward: services
               * Port: port
               * SSL Certificate: wildcard example.com

Everything is now resolving again!

**Comment by gspe** [comment]
> The solution was to set my system domain to `home.arpa` and then add the wildcard override.

This solution worked well for me also!
