### ISSUE TITLE
scrub pf rule customization

### ISSUE THREAD

**Issue by fichtner** [opnsense/core#405]
Hi, I think it would be a great feature to be able to customize the "scrub" pf rules in OPNsense;
    Some ISPs (notably Google Fiber) require that the Type of Service field of packets be set, in order
    to get full upload speed. 
    Google Fiber limits your upload speed to 10mbit without the ToS field being set (vs 1gbit when it
    is set). I think it is a bit silly to need to have a managed switch, just to set the ToS for packets, when
    OPNsense should be easily capable of doing so.

    Perhaps this only needs some quick check-box option on the interface settings specifically for Google
    Fiber? (at least for now), but I think (at least further down the line) something a bit more robust would
    make sense.

    These are the PF scrub rules required to set the ToS field correctly for Google Fiber:

    scrub out on $WAN proto udp from port 67 to port 68 set-tos 0x40 # set DHCP packets to class 2
    scrub out on $WAN proto igmp set-tos 0xC0 # set IGMP packets to class 6
    scrub out on $WAN set-tos 0x60 # set all other packets to class 3

via: https://forum.opnsense.org/index.php?topic=1414.0

**Comment by AdSchellevis** [comment]
https://github.com/opnsense/core/commit/faa4e13efca8c83343e97023ea23b8181ef5f9c4
