### ISSUE TITLE
VXLAN interfaces lose their IP configuration when updating VXLAN interface assignment

### ISSUE THREAD

**Issue by markusnasholm** [opnsense/core#4050]
When updating VXLAN interface assignments, such as adding a new VXLAN interface and assigning it a name, all existing VXLAN interfaces lose their IP configuration.

**To Reproduce**

1. Go to Interfaces -> Other Types -> VXLAN, and add a new one.
2. Go to Interfaces -> Assignments, and assign the interface a name.
3. Go to Interfaces -> [1st VXLAN], and give it a static IPv4 address and save.
4. Go back to Interfaces -> Other Types -> VXLAN, and add clone the first one, giving it a new VNI.
5. Go to Interfaces -> Assignments, again and assign the second interface a name.
6. Go back to Interfaces -> [1st VXLAN], and you will se that it has lost it's IPv4 address.

**Expected Behavior**
The VXLAN interface keeps it's IP configuration

**Environment**
Tested on OPNsense 20.1.4 on both a KVM VM and a physical x86_64 host.

**Comment by markusnasholm** [comment]
also, As far as I can tell this only affects VXLAN and not regular interfaces.

**Comment by AdSchellevis** [comment]
I could reproduce it at first, then I couldn't, it seems the steps to flush addresses are a bit different,  hit save on the assignment page and it will flush the vxlan addresses.

**Comment by AdSchellevis** [comment]
https://github.com/opnsense/core/commit/3b3577f1f582c2b75660501f0736bf66b8d3abea should fix this issue, but we do need to check the interfaces page as well.

to test, use:
```
opnsense-patch 3b3577f
```
