### ISSUE TITLE
Unbound crash: restarted then unable to read unbound.conf

### ISSUE THREAD

**Issue by stilez** [opnsense/core#4052]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[-] I have read the contributing guide lines  - YES
[-] I have searched the existing issues and I'm convinced that mine is new. - YES

**Describe the bug**

Having done nothing to change my router for weeks, I lost Unbound "out of the blue". The following logs are available:

**UNBOUND LOG:**
Time | Message
-- | --
Apr 21 12:06:40 | unbound: [97766:0] fatal error: Could not read config file: /unbound.conf. Maybe try  unbound -dd, it stays on the commandline to see more errors, or  unbound-checkconf
Apr 21 12:06:40 | unbound: [97766:0] notice: Restart of unbound 1.9.3.
Apr 21 12:06:40 | unbound: [97766:0] debug: cache memory msg=263192 rrset=525336 infra=3640742 val=1162370

System logs around (and bracketing) that time:

**BACKEND:**
Time | Message
-- | --
Apr 21 13:15:59 | configd.py: [9ddc290d-db39-47ad-b60c-1d90ec8d3353] list installed devices
Apr 21 12:06:40 | configd.py: [99f0d627-c031-4b66-bfdb-126da6789116] New IPv4 on igb1
Apr 21 12:06:40 | configd.py: [806129aa-4127-46ce-9dcb-eed03c499e9b] Linkup starting igb1
Apr 21 12:06:37 | configd.py: [4bfe570d-fa44-4de2-a7f2-0f13a0fcd803] Linkup stopping igb1
Apr 21 03:01:00 | configd.py: [2ce30085-a2c4-4124-b11b-bbe5d4984019] update bogons database via cron

**GENERAL:**
Time | Message
-- | --
Apr 21 13:15:59 | opnsense: /index.php: Successful login for user 'root' from: 10.x.x.x
Apr 21 12:06:40 | opnsense: /usr/local/etc/rc.newwanip: On (IP address: 10.x.x.x) (interface: NEW_WIFI[opt2]) (real interface: igb1).
Apr 21 12:06:40 | opnsense: /usr/local/etc/rc.newwanip: IP renewal is starting on 'igb1'
Apr 21 12:06:40 | opnsense: /usr/local/etc/rc.linkup: Hotplug event detected for  NEW_WIFI(opt2) but ignoring since interface is configured with static IP  (10.x.x.x ::)
Apr 21 12:06:40 | kernel: igb1: link state changed to UP
Apr 21 12:06:37 | opnsense: /usr/local/etc/rc.linkup: Hotplug event detected for  NEW_WIFI(opt2) but ignoring since interface is configured with static IP  (10.x.x.x ::)
Apr 21 12:06:37 | kernel: igb1: link state changed to DOWN
Apr 21 03:06:33 | root: update bogons is ending the update cycle

**To Reproduce** - Unclear
**Expected behavior** - Obvious
**Screenshots** - Logs are better
**Additional context** - Nothing had been changed or happened for a long time

**Environment** 
OPNsense 19.7.4_1-amd64FreeBSD 11.2-RELEASE-p14-HBSDOpenSSL 1.0.2s  28 May 2019
Intel(R) Core(TM) i5-2310 CPU @ 2.90GHz (4 cores)

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/core/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
