### ISSUE TITLE
dhcp server in relay mode, but dhcp static entries are active, preventing acces to firewall

### ISSUE THREAD

**Issue by benibilme** [opnsense/core#4055]
Hello,

I am using opnsense 20.1.4.  Just before encountering following problem, I have upgraded the firewall from 19 series. 

This issue took me several days to figure out, I had to reset, downgrade the opnsense to eliminate the possibilities and localize the problem. I thought the problem caused by the upgrade initially. 

Recently I have added several new machines to the network, after upgrading the opnsense, and these machines were added to the previously defined group aliases which would let them access WAN/internet. 

However the new machines could not access the WAN or even ping the firewall. 

I have been using separate dhcp server backed by a radius server. Opnsense dhcp normally not active and just relaying to the separate dhcp server. Once there was a problem with the dhcp server and I migrated the dhcp to opnsense for a short period of time. I have defined/replicated static entries in opnsense. After the original dhcp server's problem was solved, it was activated and the opnsense dhcp server is disabled and was put again in relay mode. 

However, the static entries were left, with reasoning that they might be needed it in the future for similar case. There was a checkbox which said do not pass unknown clients, it was also left ticked. 

Contrary to my expectation, this setting was active and was not allowing any new machine that was not defined in dhcp static enteries. dhcp entries even take precedence to firewall rules. Machines not whitelisted can not even ping the firewall nor pass it even though the firewall rules allow.  But firewall live log states different. The live log shows that the packet are passing based the configured rule.  

This made me think that, firewall had a problem, it is showing that it is allowing the packet but the new machines can not ping the firewall or access the WAN.  This behavior is tricking users. 

If this is a feature, I would call it, unconventional and tricky feature, if possible must be abandoned. Firewall rules must not be superseded by dhcp, whose static enteries must have not been active in the first place in my opinion. 

**Dhcp server's this feature even supersedes anti-lock rules which is dangerous.** 

This seems not an acceptable behavior in my opinion. 

The issue is posted in opnsense forum and received no feedback. 
[First post](https://forum.opnsense.org/index.php?topic=16872.msg76960#msg76960)
[Second post](https://forum.opnsense.org/index.php?topic=16908.msg76959#msg76959)

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/core/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
