### ISSUE TITLE
OpenVPN WAN Interface VIP

### ISSUE THREAD

**Issue by jeffg2k** [opnsense/core#4056]
When binding the OpenVPN to the WAN interface, it doesn't include the WAN virtual IP (WAN VIP).  That seems odd to me.  Also, bind to ALL doesn't include the WAN VIP.  I have to specifically select the WAN VIP to bind to that interface, which for the most part is fine, since that is the high availability IP, but I expected binding to WAN to include both the real and virtual IP.  This seemed like a bug that it didn't.

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/core/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
