### ISSUE TITLE
syslog-ng remote logging filter discontinuity

### ISSUE THREAD

**Issue by hippi-viking** [opnsense/core#4060]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[X] I have searched the existing issues and I'm convinced that mine is new.

**Describe the bug**
System/Settings/Logging / targets: Levels and Facilities filters does not seem to have any effect on remote log filtering.

**To Reproduce**
1. Go to System/Settings/Logging / targets
2. Define remote logging target
3. Filter logs to send by Application / Level / Facility
4. Check remote logs

**Expected behavior**
Remote logs are filtered according to the above settings, only log lines matching the above filters are sent over to the remote log server.

**Screenshots**
[Logging / targets](https://ibb.co/51z4DbN)

Selected filters:
- Applications: dhcpd, dnsmasq, filterlog, dpinger, openvpn, pkg, pkg-static, unbound, suricata
- Levels: info, notice, warn, error, critical, alert, emergency
- Facilities: kernel messages, system daemons, security/authorization messages, network news subsystem, security/authorization messages _(yes, there is two of these)_, log alert, locally used (0-7)

**Resulting syslog-ng config**
/usr/local/etc/syslog-ng.conf.d/legacy-remote.conf:
```

destination d_legacy_remote {

network("[remote server's hostname]" transport("udp") port(514) ip-protocol(4) localip([local IP]));

};



# section filters
filter f_remote_system {
    not facility(daemon, local0, local1, local2, local3, local4, local5, local6, local7, user);
};
filter f_remote_filter {
    program(filterlog);
};
filter f_remote_dhcp {
    program("dhcrelay") or
    program("dhcpd");
};
filter f_remote_dns {
    program("unbound") or
    program("dnsmasq");
};
filter f_remote_mail {
    program("postfix");
};
filter f_remote_portalauth {
    program("captiveportal");
};
filter f_remote_vpn {
    program("l2tps") or
    program("poes") or
    program("pptps") or
    program("charon") or
    program("openvpn") or
    program("tinc*");
};
filter f_remote_ids {
    program("suricata");
};
filter f_remote_apinger {
    program("dpinger");
};
filter f_remote_relayd {
    program("haproxy") or
    program("relayd");
};
filter f_remote_hostapd {
    program("hostapd");
};

### log section system ####
log {
    source(s_all);
    filter(f_remote_system);
    destination(d_legacy_remote);
};
### log section filter ####
log {
    source(s_all);
    filter(f_remote_filter);
    destination(d_legacy_remote);
};
### log section dns ####
log {
    source(s_all);
    filter(f_remote_dns);
    destination(d_legacy_remote);
};
### log section mail ####
log {
    source(s_all);
    filter(f_remote_mail);
    destination(d_legacy_remote);
};
### log section portalauth ####
log {
    source(s_all);
    filter(f_remote_portalauth);
    destination(d_legacy_remote);
};
### log section vpn ####
log {
    source(s_all);
    filter(f_remote_vpn);
    destination(d_legacy_remote);
};
### log section ids ####
log {
    source(s_all);
    filter(f_remote_ids);
    destination(d_legacy_remote);
};
### log section apinger ####
log {
    source(s_all);
    filter(f_remote_apinger);
    destination(d_legacy_remote);
};
### log section relayd ####
log {
    source(s_all);
    filter(f_remote_relayd);
    destination(d_legacy_remote);
};
```

**Conclusion**
Filters set in the GUI does not reflect the actual syslog-ng config file used!

**Environment**
OPNsense 20.1.5 (amd64, OpenSSL)
AMD G-T44R Processor (1 cores) _- sic!_
Network HP NC364T

**Comment by AdSchellevis** [comment]
@hippi-viking you can remove legacy-remote.conf, it's a left over from an older version.  /usr/local/etc/syslog-ng.conf.d/syslog-ng-destinations.conf  should contain your settings after apply, mine looks a bit like the following when entering similar data:
```

### log target b9813721-3594-47f9-89ab-ad1a451b1101 : test1 ####
filter f_b9813721359447f989abad1a451b1101_program {
    program("configd.py") or program("dhcpd") or program("dhcrelay") or program("dnsmasq") or program("filterlog") or program("dpinger") or program("charon") or program("lighttpd") or program("ntp") or program("ntpd") or program("ntpdate") or program("openvpn") or program("pkg") or program("captiveportal") or program("ppp") or program("unbound") or program("bgpd")
};
filter f_b9813721359447f989abad1a451b1101_level {
    level(info,notice,warn,err,crit,alert,emerg)
};
filter f_b9813721359447f989abad1a451b1101_facility {
    facility(kern,daemon,auth,news,authpriv,local0,local1,local2,local3,local4,local5,local6)
};

destination d_b9813721359447f989abad1a451b1101 {
    network(
        "XXX.XXX.XXX.XXX"
        transport("udp")
        port(514)
        ip-protocol(4)
        persist-name("b9813721359447f989abad1a451b1101")
    );
};

log {
    source(s_all);
    filter(f_b9813721359447f989abad1a451b1101_program);
    filter(f_b9813721359447f989abad1a451b1101_level);
    filter(f_b9813721359447f989abad1a451b1101_facility);
    destination(d_b9813721359447f989abad1a451b1101);
};


```

**Comment by hippi-viking** [comment]
Indeed, thank you. I did recreate the remote logging config as it was recommended at the time thus the file existed but it was confusing that making changes to legacy-remote.conf also changed the behaviour of syslog-ng. This should be a non-issue for newly configured instances.
