### ISSUE TITLE
URL open redirect leads to phishing attacks

### ISSUE THREAD

**Issue by naivekun** [opnsense/core#4061]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[x] I have searched the existing issues and I'm convinced that mine is new.

**Describe the bug**
Redirect URL in login page was not filtered and can redirect user to any website.
Attackers can send a URL like `https://<FIREWALL_IP>/?url=http://phishing-site.com/` to firewall user. If user enter the credential and login, he will be redirected to malicious page

**To Reproduce**
1. Access `https://<FIREWALL_IP>/?url=http://example.com`
2. Enter the credential.
3. User was redirected to `http://example.com`

**Environment**
OPNsense 20.1-amd64
FreeBSD 11.2-RELEASE-p16-HBSD
OpenSSL 1.1.1d 10 Sep 2019

**Comment by naivekun** [comment]
https://github.com/opnsense/core/blob/2a216f91c79a469138e5d302b5eb03b3c3743d13/src/etc/inc/authgui.inc#L117

**Comment by fichtner** [comment]
Can you explain how that differs from clicking the malicious URL itself? Auth step or not, what is the severity assessment?

**Comment by naivekun** [comment]
Malicious URL itself does not starts with "http://<REAL_IP_ADDRESS>". I'll give you an example.
If someone send you a link like "http://192.168.1.1/?url=http://bit.ly/xxxxx", "192.168.1.1" makes user feel safe instead of "http://bit.ly/xxxxx" and users are more likely to click a URL contains a trusted domain or IP address.
referrer: https://cwe.mitre.org/data/definitions/601.html

**Comment by naivekun** [comment]
Another reasonable payload is like `http://192.168.1.1/?url=http://csrf_token_XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.hacker.com` which is more easily to obfuscate user. `csrf_token_XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX` is a fake subdomain of hacker.com.

**Comment by AdSchellevis** [comment]
https://github.com/opnsense/core/commit/0d07fae36a6bf45be91da03e7fc33188c897bd5a should prevent off site redirects.
