### ISSUE TITLE
API: DHCP settings and static mappings

### ISSUE THREAD

**Issue by yannik-b** [opnsense/core#4062]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[x] I have searched the existing issues and I'm convinced that mine is new.

**Is your feature request related to a problem? Please describe.**
I use OPNsense in a shared apartment with 5 users in different VLANs. I have the DHCP option "Deny unknown clients" active. I want to setup a small web service, in which every user can see (only) his own known devices and configure new ones. Therefore I need a API endpoint.

**Describe the solution you'd like**
Implementation of a new API endpoint to configure DHCP server options and static mappings per Interface and list static mappings.

**Describe alternatives you've considered**
Edit user privileges, so a user can edit static mappings not only global, but per Interface in Web UI.

**Additional context**
-/-

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/core/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
