### ISSUE TITLE
[Feature Request] Improved log filtering capabilities

### ISSUE THREAD

**Issue by lordraiden** [opnsense/core#4065]
**Is your feature request related to a problem? Please describe.**
A more powerfull way to filter logs in order to do a proper firewall troubleshooting

**Describe the solution you'd like**
A box or a dropdown to select the firewall rule for which I want to filter the logs.
In particular it would be interesting to filter logs by fw rule ID

**Describe alternatives you've considered**
Something similar to this would be fine.
This filters can stack, so you can apply different conditions together to refine the logs
![imagen](https://user-images.githubusercontent.com/17175395/80285175-68330280-8723-11ea-8d26-b53f21f87b60.png)
![imagen](https://user-images.githubusercontent.com/17175395/80285209-91ec2980-8723-11ea-9615-b5991333e6dc.png)
![imagen](https://user-images.githubusercontent.com/17175395/80285223-af20f800-8723-11ea-8191-9635ba94eb50.png)

**Comment by lordraiden** [comment]
@AdSchellevis Help wanted label?

**Comment by fichtner** [comment]
Free for all to contribute.

**Comment by AdSchellevis** [comment]
I've just added https://github.com/opnsense/core/commit/2966211a8fa77330d80e3ea4c88698beb6d0c2d5, which should functionally do what you're looking for. Although the layout could certainly be improved, I'm not planning to work on that currently (it's quite time-consuming).

![image](https://user-images.githubusercontent.com/9783985/82809771-2665bb00-9e8d-11ea-81c6-9aa66844b1c7.png)

Example above filters on unique `rule id` and `protocol`

**Comment by fichtner** [comment]
Does this supersede https://github.com/opnsense/core/issues/2195 ?

**Comment by AdSchellevis** [comment]
@fichtner that looks quite similar, although I haven't included all fields (just add the options to the `filter_tag` select if needed)

**Comment by lordraiden** [comment]
Thanks I think at least with rule ID and protocol is more than enough for almost any firewall rule troubleshotting purpose.

Probably a stupid question but where in the WebUI can I see the rule id of a firewall rule?

**Comment by AdSchellevis** [comment]
it's not a stupid question, in the rule overview, click on 
![image](https://user-images.githubusercontent.com/9783985/82819908-81a1a880-9ea1-11ea-833a-0a60c8665097.png) The info button for the log lines will also display the rule hash

![image](https://user-images.githubusercontent.com/9783985/82820016-adbd2980-9ea1-11ea-9215-0da195e92bb4.png)
