### ISSUE TITLE
Corrupted entries in firewall logs

### ISSUE THREAD

**Issue by BPtLNfxZWo** [opnsense/core#4067]
Since update to 20.1.5 a entry with interface S appears randomly in the logs.
![Entry](https://user-images.githubusercontent.com/10586541/80298336-816f9980-878b-11ea-92e0-d6edbd62711f.JPG)

![Details](https://user-images.githubusercontent.com/10586541/80298340-892f3e00-878b-11ea-86cf-0e9be4ad315c.JPG)

All other log entries are ok

**Comment by fichtner** [comment]
It's probably greedy matching issue with  2fad6bf36d0eb. Can you confirm?

    # opnsense-patch 2fad6bf36d0eb

**Comment by BPtLNfxZWo** [comment]
I've applied the patch and at least in the first 5 minutes it seems to be ok.
