### ISSUE TITLE
Interface enable (disable) not working

### ISSUE THREAD

**Issue by sooslaca** [opnsense/core#4073]
**Describe the bug**
as per https://docs.opnsense.org/manual/interfaces.html tick out "Enable interface" = "Disable the interface without needing to remove its assignment altogether."
But it doesn't do anything

**To Reproduce**
1. Go to Interfaces -> Any interface of yours
2. Click on 'Enable interface' to be ticked out  (no tick in the box)
3. Save
4. go to SSH
5. ifconfig xyz where xyz is the interface you'll see it's still UP
```
vmx3: flags=8943<UP,BROADCAST,RUNNING,PROMISC,SIMPLEX,MULTICAST> metric 0 mtu 1500
```

**Expected behavior**
To see interface down
```
vmx3: flags=8902<BROADCAST,PROMISC,SIMPLEX,MULTICAST> metric 0 mtu 1500
```

**Environment**
Version: 20.1.5 (installed)
VMWare ESXi 6.7 U2

**Comment by maurice-w** [comment]
"Doesn't do anything" is not quite correct. All IP addresses get removed immediately (except for IPv6 link-local), but a reboot is required for the interface to actually go down.

**Comment by sooslaca** [comment]
possibly that's right, I did not have an IP configured on the interface as it's part of a bridge so I did not see this behavior. Still the expected outcome imho should be to shut down interface immediately.

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/core/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
