### ISSUE TITLE
dhcp lease removes unbound override entry

### ISSUE THREAD

**Issue by oerik** [opnsense/core#4074]
An unbound override, in my case a wildcard entry, is removed by an existing dhcp lease for that IP address. This is somewhat inconvenient and I doubt that this is correct behaviour. If I remove the `unbound_control(['local_data_remove', tmp_fqdn])` line my wildcard is operating as expected.

https://github.com/opnsense/core/blob/0f444e7751abd42a346b48aaded620dbdf8693ab/src/opnsense/scripts/dns/unbound_dhcpd.py#L148-L155

**Comment by AdSchellevis** [comment]
for reference, please read https://github.com/opnsense/core/issues/3730

if the log line contains the wildcard, it might be an option to skip that specific one, the general behaviour is a bit expected, registering dhcp leases for overlapping entries isn't really supported (you can disable the function).

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/core/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
