### ISSUE TITLE
Reduce space consumption of suricata stats.log

### ISSUE THREAD

**Issue by jkellerer** [opnsense/core#4085]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[x] I have searched the existing issues and I'm convinced that mine is new.

**Is your feature request related to a problem? Please describe.**
In Opnsense 20.1, after 7 days of uptime, the log folder is ~500mb in size. >90% of the space (470mb) is consumed by "`/var/log/suricata/stats.log.*`" (8 files ~60mb each), even when several additional plugins are installed.

I haven't found any process consuming the files so I assume they are for diagnostics only and it is quite a lot of space permanently consumed by files needed for special cases. 

Suricata was updated in "master" but the behaviour for stats log doesn't seem to be different (e.g. stats logging was not by thread in 20.1 and isn't in 20.7).

**Describe the solution you'd like**
A quick solution to reduce excessive space consumption is adding the compression flag "Z" to [newsyslog.conf](https://github.com/opnsense/core/blob/master/src/opnsense/service/templates/OPNsense/IDS/newsyslog.conf) for the "stats.log" entry.
In my tests compression level is > 30x, thus the max consumption is ~75mb (7x60mb/30 + 60mb)

**Describe alternatives you've considered**
Alternatively the suricata UI could have options to toggle the generation of stats.log and its retention. This is however much more effort and has the side effect that the data may not be available when needed for diagnostics.

**Additional context**
_N/A_

**Comment by AdSchellevis** [comment]
@jkellerer let's start with the compression indeed, currently we only use the tail of the stats log ourselves  (https://github.com/opnsense/plugins/blob/89f57e69dbac3a843abda78e95f731a141a3b491/security/etpro-telemetry/src/opnsense/scripts/etpro_telemetry/telemetry/system.py#L116), I don't expect a lot of people rely on the archives, so this should be rather safe. I wouldn't mind adding a toggle for the number of backups to keep in a future version (and keep the default the same).

**Comment by jkellerer** [comment]
@AdSchellevis, thanks a lot for the prompt solution. I think compression is the best option since 7 compressed rotated log files only consume ~15mb, not sure if we really need to make it more customisable without having a good reason. At least this solution is fine for me, so I'm closing the issue now.
