### ISSUE TITLE
IDS: Error reading data from iface 'gif0' & syslog CPU spike

### ISSUE THREAD

**Issue by MysticRyuujin** [opnsense/core#4089]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

- [x] I have searched the existing issues and I'm convinced that mine is new.

**Describe the bug**
When the Intrusion Detection service is configured to monitor a "GIF" interface it floods the logs with:
`Error reading data from iface 'gif0': (55u) No buffer space available`

Also the syslog service spikes in CPU use to bring my effective system CPU use to 90%+

I've come across other posts stating that IDS is not supported on pppoe interfaces, and I've come across other posts suggesting other people have had similar experiences, but I cannot find anything definitive to state this is a known issue with GIF tunnels or a new/unknown bug.

I had the IDS configured this way prior to upgrading the firmware today, however, I did not NOTICE this behavior (the log message or the CPU spike). That isn't to say the behavior wasn't the same prior to update, just that I didn't notice it until monit sent me a CPU alert and I investigated.

**Expected behavior**
I would like to be able to turn on Intrusion Detection for my IPv6 TunnelBroker connection.

**Environment**
Hyper-V Gen2 Virtual Machine
```
OPNsense 20.1.6-amd64
FreeBSD 11.2-RELEASE-p19-HBSD
OpenSSL 1.1.1g 21 Apr 2020
```

**Comment by AdSchellevis** [comment]
IDS mode should very likely work, IPS mode not (needs hardware support for netmap)

**Comment by MysticRyuujin** [comment]
It doesn't appear to be possible to run 1 interface in IPS and 1 in IDS.

I do see that under Interfaces it does say "only use physical interfaces here", so that seems to be part of the extended help.

That's unfortunate.

Thanks for the clarification though.

**Comment by L1ghtn1ng** [comment]
@MysticRyuujin Is a GIF interface like a form of vlan(not familiar with this interface type)? if so you would need to use promiscuous mode as well but there is a bug for that which should hopefully be fixed in 20.7 when it is released.

**Comment by MysticRyuujin** [comment]
It's a generic tunnel interface used in my case for a hurricane electric IPv6 interface

**Comment by L1ghtn1ng** [comment]
Ah okay thanks
________________________________
