### ISSUE TITLE
Port Range in Outbound Nat Rule not Possible

### ISSUE THREAD

**Issue by Marv2190** [opnsense/core#4090]
**To Reproduce**
1. Go to 'NAT -> Outbound'
2. Click on 'New Rule'
3. Scroll down to 'Source port'
4. Try to Create a Rule with a Port Range 
5. See error ->   You must supply either a valid port or port alias for the destination port entry.

**Expected behavior**
Normally a Outbound NAT Entry with the PortRange should be created.

**Screenshots**
Attached
![opnsenseoutbound](https://user-images.githubusercontent.com/24812585/81239151-50515d80-9004-11ea-8f33-86470c303194.png)

**Environment**
Software version used and hardware type if relevant.

OPNsense 20.1.6-amd64
FreeBSD 11.2-RELEASE-p19-HBSD

**Comment by mimugmail** [comment]
Please set the correct protocol

**Comment by Marv2190** [comment]
The Protocoll doenst matter. I can choose just TCP and get the same Result. Its not possible to add an Range here. 
Btw. Pfsense suffered the same Bug some time ago:
https://redmine.pfsense.org/issues/4300

**Comment by AdSchellevis** [comment]
https://github.com/opnsense/core/commit/adbb91289f67f2dfd508df9c45fb15233e117629 should do the trick
