### ISSUE TITLE
spurious "Array" prefix in user-defined aliases

### ISSUE THREAD

**Issue by fichtner** [opnsense/core#41]
I created some aliases and started creating Port Forward NAT-rules (Firewall->NAT) using said aliases. In the rules-list the alias gets prefixed with Array (ie. when I created a Port Forward NAT for my mailhost I see 'Arraymailports' as Dest. ports, 'Arraymailhost' as NAT IP, 'Arraymailports' as NAT Ports).

The rules auto-created in Firewall->Rules are not prefixed with Array.

via https://forum.opnsense.org/index.php?topic=55.msg154#msg154

**Comment by sjorge** [comment]
+1 can confirm, http://i.imgur.com/HjD846J.png

**Comment by AdSchellevis** [comment]
fixed in https://github.com/opnsense/core/commit/4d177fb5c31cd4e5c8ee5e7e518d9d038f3ff8a8

**Comment by mannkind** [comment]
The aliases no longer appear at all on Firewall->NAT. They appear correctly on Firewall->Rules.

**Comment by sjorge** [comment]
#77 was created for this
