### ISSUE TITLE
uniqid for old IPSEC Ph2 entries missing

### ISSUE THREAD

**Issue by andreas-p** [opnsense/core#4105]
I have some aged IPSEC connections defined, I now need to edit with 20.1.x.

Some entries that have been added more recently (1-2 years or so) will edit normally, but others (older than 2 years) can not be edited correctly; while the overview page will show the remote network address, the edit dialog has an empty field. Saving with new values will not work.

Comparing working to non-working entries in the config.xml, the difference seems to be the uniqid: the older ph2 definitions don't have these.

IMHO the uniqid should be added automatically when such older definitions are touched.

**Comment by mimugmail** [comment]
Do you mean reqid? I found a bug couple of minutes ago, that when you have 3 tunnels and the one in the middle is route based, every following conmection also gets a reqid. When moving route based to the bottom everything is fine

**Comment by andreas-p** [comment]
No, I really mean uniqid.
I added uniqid entries for those entries to the config file, and was able to edit using the GUI again.

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/core/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
