### ISSUE TITLE
"Apply" button times out when a gateway is down

### ISSUE THREAD

**Issue by alexandredulche** [opnsense/core#4107]
**Describe the bug**
In a dual WAN configuration, my main WAN is currently down.
When making configuration changes such as firewall rules or IPSEC, clicking on the apply button ends up in a ERR_CONNECT_TIMEOUT in Chrome.
Manually disabling the broken gateway, web UI changes apply in 1 second (as should be).
Marking gateway as down doesn't help.

**To Reproduce**
In a 2 gateways setup :
1. Go to 'Gateways' and click 'Mark gateway as down', apply
Alternatively, break your WAN access (DSL router out of sync in my case)
2. Try to make changes such as firewall rule
3. Click apply
4. Wait for the timeout

**Expected behavior**
Changes should be immediate, regardless of gateway status.

**Screenshots**
N/A

**Relevant log files**
I tried to find something in the webUI log, but came out empty-handed. Please let me know where to look.

**Additional context**
My DSL connection went down (issue on ISP side).
I tried playing around with DNS settings, firewall rules, gateway groups. Each setting change was very long to apply, usually Chrome times out.

**Environment**
OPNsense 20.1.6 (amd64, OpenSSL) on VMWare VM (2 vCPU 4Go RAM)

**Comment by hxw** [comment]
I am testing opnsense as a replacement firewall so, no actual WAN connections are plugged
so I ran into this issue.  I was not able to get anything in error_log file from php, the file does not get created.

By clicking on the green triangle to disable the gateway cause the apply to work normally.

As far as I could determine by truss on the lighttpd process the system_gateways.php crashes.

**Comment by AdSchellevis** [comment]
could be related to https://github.com/opnsense/core/commit/f80081f110f45c8a50e11e556cb978488ca19c87

**Comment by hxw** [comment]
I have OPNsense 20.7.b_224-amd64
I expect this change is more recent

**Comment by hxw** [comment]
I switched back to production OPNsense 20.1.8_1-amd64
and tried a few more tests, occasionally the process would complete and the success message
would be displayed taking about 32 seconds (just looking at clock)

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/core/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
