### ISSUE TITLE
Wi-Fi interface not properly detected

### ISSUE THREAD

**Issue by gregober** [opnsense/core#411]
Context : APU1D - WLAN card  wle200nx based on Atheros 9280 chipset

When a WLAN interface is assigned using the "assign" button - It won't natively be considered as a WLAN / Wi-Fi interface but rather as a "normal" interface (preventing access to the WLAN contextual infos : no WiFi settings available).  

One has to go to Wireless interface and assign a "sub-interface" based on the native WLAN card in order to get this working.

**Comment by fichtner** [comment]
I'm afraid this is precisely how wireless devices work in FreeBSD: https://www.freebsd.org/doc/handbook/network-wireless.html

Not sure how to proceed other than hiding the parent wifi interfaces from the assign screen...

**Comment by ylli2000** [comment]
I am with gregober. while it is logically "correct" to assign a "sub-interface" to WLAN from a developer's point's view, it is illogical from a pure user point of view. Let's hide the truth of how wireless devices work in freeBSD, one would naturally think a WLAN device is physically different from a LAN device. 

From user point of view, the system should know when to enable SSID, private keys and all those options when it comes to a WLAN device. Now the Interfaces->Assignment option knows that it is a WLAN and treat it as a LAN device is not user friendly enough imho. It proves its programming correctness but trading off its GUI user friendliness.

**Comment by fichtner** [comment]
I agree with this, but it's impossible to abstract away from the notion of a "parent", we'd still have to select the chip to do the actual WiFi setup. It's the clone although we don't have to name it that. Fundamentally, the wireless clones work exactly like setting up VLANs so the process is not unreasonable...

What do you want to have done here? One of the things that bugs me is the wireless parent selection in the assignments, but I don't see more. Any help is appreciated.
