### ISSUE TITLE
IPv6 no longer working when SOLICIT required

### ISSUE THREAD

**Issue by kylegordon** [opnsense/core#4114]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[x] I have searched the existing issues and I'm convinced that mine is new.

**Describe the bug**
Last known working 19.7, but possibly in early 20s. IPv6 setup for Zen Internet as per https://docs.opnsense.org/manual/how-tos/IPv6_ZenUK.html was followed in late February, and has been working since then. Recently upgraded to latest last week, and have noticed IPv6 is no longer working. LAN interface, configured as Tracked, is no longer being given an IPv6 IP, even though WAN is.

The option "Directly send SOLICIT" now appears to be missing from the UI, even though it is a requirement for Zen, described in the howto, and listed in the documentation. I can only assume this is the reason for the failure of Route Advertisement. 

Happy to test this if someone advises what config file to edit.

**To Reproduce**
Use an ISP that requires Directly Send Solicit

**Comment by fichtner** [comment]
As you can see from the patch the "removal" merely enables directly send solicit by default for everyone:

https://github.com/opnsense/core/commit/48e0c47a968b4f55bbe299d6b961613fa8d86802#diff-1332c372788c9e1a8c6c9bae9ebb55a5

While the docs need updating your issue seems to be elsewhere and is not currently visible from the information you reported.

**Comment by marjohn56** [comment]
@kylegordon - I wrote the doc and I'll update it. I use Zen on static, but I'll quickly switch to dhcp6 and check it.

**Comment by marjohn56** [comment]
![image](https://user-images.githubusercontent.com/17962918/82023864-d6197c80-9686-11ea-8ffe-e16ace01e9a9.png)

dhcp6c working fine. Can you check your system log and filter using dhcp6c, see what it says.

**Comment by kylegordon** [comment]
@fichtner no problem, thank you for the clarification :+1: 

@marjohn56 aha, thanks for the info and hints. I've disabled and reenabled the WAN interface (couldn't do it during work hours since working from home these days), and have gotten the following results. 

The LAN interface *did* now get an IP address assigned, even though it's been spinning for at least the past 24 hours with hundreds of "dhcp6c[7680]: Sending Solicit" messages. In the past 36 hours, it's only been Sending Solicit messages from dhcpc6, interspersed with 3 occasions where dhcp6c was restarted and it issued a 'restarting' message.

I'll shortly reboot and see how well it can bring up the whole config.

```
May 15 22:06:43 firewall dhcp6c: RTSOLD script - Sending SIGHUP to dhcp6c for interface wan(pppoe0) 
May 15 22:06:43 firewall dhcp6c[7680]: restarting 
May 15 22:06:44 firewall dhcp6c: RTSOLD script - Sending SIGHUP to dhcp6c for interface wan(pppoe0) 
May 15 22:06:44 firewall dhcp6c[7680]: restarting 
May 15 22:06:44 firewall dhcp6c[7680]: Sending Solicit 
May 15 22:06:45 firewall dhcp6c[7680]: Sending Solicit 
May 15 22:06:48 firewall dhcp6c[7680]: Sending Solicit 
May 15 22:06:52 firewall dhcp6c[7680]: Sending Solicit 
May 15 22:07:00 firewall dhcp6c[7680]: Sending Solicit 
May 15 22:07:17 firewall dhcp6c[7680]: Sending Solicit 
May 15 22:07:50 firewall dhcp6c[7680]: Sending Solicit 
May 15 22:07:51 firewall dhcp6c[7680]: Sending Request 
May 15 22:07:51 firewall dhcp6c[7680]: Received REPLY for REQUEST 
May 15 22:07:51 firewall dhcp6c[7680]: add an address 2a02:8010:66ab:0:5054:ff:fe6f:2f08/64 on vtnet0 
May 15 22:07:51 firewall dhcp6c[7680]: status code for PD-0: success 
May 15 22:07:51 firewall dhcp6c[7680]: status code for NA-0: no addresses 
May 15 22:07:51 firewall dhcp6c: dhcp6c REQUEST on pppoe0 
May 15 22:07:51 firewall dhcp6c: dhcp6c REQUEST on pppoe0 - running newipv6 
May 15 22:07:52 firewall dhcp6c[7680]: Sending Solicit 
May 15 22:07:53 firewall dhcp6c[7680]: Sending Solicit 
May 15 22:07:55 firewall dhcp6c[7680]: Sending Solicit 
May 15 22:07:59 firewall dhcp6c[7680]: Sending Solicit 
May 15 22:08:07 firewall dhcp6c[7680]: Sending Solicit 
May 15 22:08:24 firewall dhcp6c[7680]: Sending Solicit 
```

**Comment by kylegordon** [comment]
Yep, a reboot brought it all back nicely and as expected. I'm at a loss as to why dhcp6c was spinning on Sending Solicit and not getting a reply. Maybe something somewhere got wedged.

Thank you for your time! Greatly appreciated :+1:

**Comment by fichtner** [comment]
Happy to hear 😊
