### ISSUE TITLE
Unbound DNS Alias doesn't resolve unless you specify the FQDN, while a hostname only search will

### ISSUE THREAD

**Issue by MarkIannucci** [opnsense/core#4119]
**Important notices**
I have read the contributing guide lines.  I have searched the existing issues and I'm convinced that mine is new.

**Describe the bug**
If I ping a hostname without the alias, it resolves to the IP address.  However, if I ping an Unbound DNS alias, it does not resolve.

**To Reproduce**
1.  Create a dns override in unbound with an accurate hostname.  Fill in localdomain as the domain 
2.  Add a alias to it; leave the domain empty on the alias
3.  Ping the alias without inputting the domain

**Expected behavior**
The alias resolves, like the hostname does.  Unfortunately it does not.

**Screenshots**

![image](https://user-images.githubusercontent.com/16762974/82246942-d160fc80-9902-11ea-9558-e333f2bbc315.png)

**Environment**
Software version used and hardware type if relevant.
e.g.:

OPNsense 20.1.6-amd64
FreeBSD 11.2-RELEASE-p19-HBSD
OpenSSL 1.1.1g 21 Apr 2020

--sorry about my enter fail which created an initially incomplete bug report.

**Comment by maurice-w** [comment]
You need to fill in the local domain for the alias, too.

**Comment by MarkIannucci** [comment]
Thank you for lending a hand on this.  I suspect you mean like this?

![image](https://user-images.githubusercontent.com/16762974/82626679-a5b17100-9ba5-11ea-9820-5d89ad751a0f.png)

I tried that and it worked.  Thank you :)
