### ISSUE TITLE
Remote Syslog keeps sending to old target

### ISSUE THREAD

**Issue by 90er** [opnsense/core#4121]
I recently changed the Remote Syslog Target in OPNsense 20.1.2 (https://<FQDN>/ui/syslog/) and applied the change. I confirmed it by checking the incoming logs at the new Syslog Server.

Today i wanted to shut down the old Syslog Server and have seen, that the OPNsense System is still sending the events to the old Syslog Target as well.

The section "System: Settings: Logging / targets" only shows the new Syslog Target. Even restarting the service "syslog-ng" doesn't fix it.

Information: i'm using explicit ip-addresses for the Logging targets and not DNS.

Thanks,
Wolfgang

**Comment by 90er** [comment]
This also happens with OPNsense 20.1.4.

**Comment by AdSchellevis** [comment]
it's a leftover from an older version, see https://github.com/opnsense/core/issues/4060#issuecomment-619572007

**Comment by 90er** [comment]
@AdSchellevis thanks a lot. Do you think this will be fixed soon? I would wait then and give feedback as tester ;-)

**Comment by AdSchellevis** [comment]
just remove the file as mentioned in the comment

**Comment by Bytechanger** [comment]
Me too,
is there a way to disable reporting? SSH and change a config or something else?

**Comment by mimugmail** [comment]
Do a fgrep with your syslog IP over /usr/local/etc.
Maybe theres a stale file

**Comment by AdSchellevis** [comment]
`rm /usr/local/etc/syslog-ng.conf.d/syslog-ng-destinations.conf`  (In which case I'm repeating myself https://github.com/opnsense/core/issues/4060#issuecomment-619572007)

**Comment by Bytechanger** [comment]
Hi,

thanks, but

1) fgrep "172.30.90.81" /usr/local/etc
   returning nothing

2) cat /usr/local/etc/syslog-ng.conf.d/syslog-ng-destinations.conf
  returning nothing
file has one empty line...

Greets

Byte

**Comment by mimugmail** [comment]
fgrep -r ..

**Comment by Bytechanger** [comment]
OK thanks, found it now.

I deleted legacy-remote.conf now, restart service and logging stops! Thanks.
One more question, do I need 
/usr/local/etc/syslog-ng.conf.d/legacy.conf ?
It sounds like an "old" config?!

```
#
# OPNsense legacy log target
# send all received local events to platform standard syslogd
#

destination legacy_dst {
    unix-dgram("/var/run/legacy_log" flags(syslog-protocol));
};

log {
    source(s_all);
    destination(legacy_dst);
};
```
Is the config normal? I don´t want to log to much data.

Greets

Byte

**Comment by fichtner** [comment]
Might be better to make legacy.conf an empty template and remove in next major version?

**Comment by AdSchellevis** [comment]
@fichtner I don't think we should do anything, the major upgrade change log (https://docs.opnsense.org/releases/20.1.html?highlight=syslog#january-30-2020) clearly stated which steps to perform before upgrade, you are allowed to keep old configs, but the system won't manage them anymore in that case.

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/core/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
