### ISSUE TITLE
No traffic after update to 20.1.7

### ISSUE THREAD

**Issue by monreal** [opnsense/core#4128]
**Describe the bug**
After update form 20.1.6 to 20.1.7 my firewall which is connected to the internet via pppoe to a DSL modem gets IPv4 and IPv6 IPs which I can ping successfully but no other trafic works. For example I cannot ping 8.8.8.8 vor 1.1.1.1 (ping: sendto: no route to host).

I would love to revert to 20.1.6 but as the system can't reach mirrors I get "Fetching opnsense.txz: .. Failed"

**To Reproduce**
1. update to 20.1.7
2. See error

**Expected behavior**
Connection and trafic working as before

**Additional context**
What I find very strange: i had a ping to 8.8.8.8 running in a terminal and noticed that up to three pings successfully go through when appling wan interface changes vor reloadung the wan/pppoe. After that i get no Route to host again. But for a Moment, it works. 

**Environment**
Software version used and hardware type if relevant.
e.g.:

OPNsense 20.1.7 (amd64, OpenSSL).

**Comment by monreal** [comment]
I now configured "allow DNS server list to be overwritten by DHCP/PPP in wan". The opnsense system gets DNS Servers of my provider (t-online). Form the firewall system I can ping those DNS servers and DNS resolution works. But still no pings to public servers or any other connections to the outside.

**Comment by monreal** [comment]
Connected my emergency router to verify there is nothing wrong with the provider after all andit all works fine. So there is something wrong with either 20.1.7 or the upgrade process.

**Comment by mimugmail** [comment]
Output of ifconfig and netstat -nr would be nice

**Comment by marjohn56** [comment]
@mimugmail - I thought you were psychic?

**Comment by monreal** [comment]
[ip.txt](https://github.com/opnsense/core/files/4671825/ip.txt)

**Comment by monreal** [comment]
> Output of ifconfig and netstat -nr would be nice

The file I just attached includes the output of ifconfig and netstat -nr and also show how ping works for a short while when reloading the WAN interface

**Comment by mimugmail** [comment]
There is no default gateway for IPv4? Can you check System : Gateways : Single? If there is an active one?

Also follow `clog -f /var/log/ppps.log` if you constantly loose your uplink

**Comment by monreal** [comment]
![gateways](https://user-images.githubusercontent.com/54005/82732947-de218e00-9d10-11ea-8c03-dd86624ddb8b.png)

Gateways look fine to me on GUI ?

**Comment by monreal** [comment]
[ppps.log](https://github.com/opnsense/core/files/4671900/ppps.log)

Problems starts on May 22

**Comment by mimugmail** [comment]
So, every 2 hours your provider shuts down your ppp session. 

Can you try to set v4 gateway prio to 250?

**Comment by monreal** [comment]
> So, every 2 hours your provider shuts down your ppp session.

How would you see this? I did not have any issues until yesterday evening when I updated to the latest version of Opnsense and the reconnects you see in the log are probably all caused by manual resets and reboots

**Comment by mimugmail** [comment]
Just read the logs? 

```
May 22 22:32:11 fw1 ppp: [wan]   020d:b9ff:fe4d:18d8 -> 2a8a:1cff:fe63:fa41 
May 23 02:02:11 fw1 ppp: [wan_link0] LCP: rec'd Terminate Request #187 (Opened) 
May 23 02:02:11 fw1 ppp: [wan_link0] LCP: state change Opened --> Stopping 
May 23 02:02:11 fw1 ppp: [wan_link0] Link: Leave bundle "wan" 
May 23 02:02:11 fw1 ppp: [wan] Bundle: Status update: up 0 links, total bandwidth 9600 bps 
May 23 02:02:11 fw1 ppp: [wan] IPCP: Close event 
May 23 02:02:11 fw1 ppp: [wan] IPCP: state change Opened --> Closing 
May 23 02:02:11 fw1 ppp: [wan] IPCP: SendTerminateReq #4 
May 23 02:02:11 fw1 ppp: [wan] IPCP: LayerDown 
May 23 02:02:11 fw1 ppp: [wan] IFACE: Delete route 0.0.0.0/0 62.155.241.143 failed: No such process 
```

Received terminate request.

I updated my home firewall to 20.1.7 and also connected  via Telekom, seems fine so far.

**Comment by monreal** [comment]
Maybe this one is because the link is not being used at all? I started the update to 20.1.7 at around 22:30 I guess and after that no real data (except those pings I mentioned) seems to be able to go through the pppoe link

**Comment by monreal** [comment]
> So, every 2 hours your provider shuts down your ppp session.
> 
> Can you try to set v4 gateway prio to 250?

Tried that and also tried prio 1, no change.

What I did notice: during the second where traffic dies work (when the ping is successful) I can even load a website like Google.com

Made a local mirror and downgraded to 20.1.6 but sadly it did not help. Firmware health complains about missing php72 packages though, so maybe the revert did not fully work. Did not try to revert the kernel. Updated back to 20.1.7, no error messages on update but still the same problem

**Comment by monreal** [comment]
Ran netstat -nr druing the second where it works on wan reload and compared the output with what I get after that:

The following is present during the second where it works:
default            62.155.241.143     UGS      pppoe0

The following gets added when the V4 default route gets removed:
2003:c8:4f24:7300::/64            link#8                        U      igb1_vla
2003:c8:4f24:7300:20d:b9ff:fe4d:18d9 link#8                     UHS         lo0

**Comment by monreal** [comment]
In System: Routes: Configuration I found a static route with Network Address 0.0.0.0/0 on gateway WAN_PPPOE and status "disabled". I have no idea why the route was added there. Either enabling or removing the static route entry seems to fix my problem. Did anything on upgrade from 20.1.6 to 20.1.7 mess with static routes?

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/core/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
