### ISSUE TITLE
option 9 pfTop from console menu : permission denied

### ISSUE THREAD

**Issue by gitdevmod** [opnsense/core#413]
option 9 pfTop from console menu fails with

> Error Reading status (DIOCGETSTATUS): Permission denied

OPNsense 15.7.15-amd64

**Comment by fichtner** [comment]
Does this fix the problem?

# pkg install -yf pftop

**Comment by gitdevmod** [comment]
I reinstalled the system and I can't reproduce. You can close the issue.
