### ISSUE TITLE
OpenVPN connection applies incorrect Policy-based routing rules

### ISSUE THREAD

**Issue by drivera-armedia** [opnsense/core#4133]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[X] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md

[X] I have searched the existing issues and I'm convinced that mine is new.

[X] The title contains the plugin to which this issue belongs

**Describe the bug**
I'm trying to deploy a PureVPN link to my OPNSense firewall (fully updated, 20.1.7). The link comes up fine, and I can ping across it from within the firewall. However, the rules generated for policy-based routing are generated using the wrong value. I'll grant you right off the bat that I may have missed something regarding configuration, but I don't think so.

I have other OpenVPN clients working just fine, I think it has to do with this client using **subnet** topology (i.e. --topology subnet).

When rendering the rules for policy-based routing, the rule generator uses the VPN link's local IP as the gateway target for routing, instead of the remote IP. Here's the ifconfig output for the VPN client's interface:
```
ovpnc6: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> metric 0 mtu 1500
	options=80000<LINKSTATE>
	inet6 fe80::2e0:67ff:fe0e:3504%ovpnc6 prefixlen 64 scopeid 0xe
	inet 37.230.169.211 --> 37.230.169.193 netmask 0xffffffc0
	nd6 options=21<PERFORMNUD,AUTO_LINKLOCAL>
	groups: tun openvpn
	Opened by PID 15600
```

Also, here are the routing tables that are active when the client is up (IPv4 only, for brevity):

```
Routing tables

Internet:
Destination        Gateway            Flags     Netif Expire
default            186.15.162.1       UGS        igb2
8.8.4.4            192.168.200.1      UGHS       igb3
8.8.8.8            186.15.162.1       UGHS       igb2
10.38.0.81         link#11            UH       ovpnc5
10.38.0.82         link#11            UHS         lo0
37.230.169.192/26  37.230.169.193     UGS      ovpnc6
37.230.169.193     link#14            UH       ovpnc6
37.230.169.211     link#14            UHS         lo0
127.0.0.1          link#5             UH          lo0
186.15.162.0/24    link#3             U          igb2
186.15.162.164     link#3             UHS         lo0
186.15.224.84      186.15.162.1       UGHS       igb2
192.168.0.0/22     link#2             U          igb1
192.168.2.1        link#2             UHS         lo0
192.168.2.1/32     link#2             U          igb1
192.168.2.2        link#2             UHS         lo0
192.168.2.2/32     link#2             U          igb1
192.168.3.254      link#2             UHS         lo0
192.168.4.0/24     192.168.4.2        UGS      ovpns1
192.168.4.1        link#12            UHS         lo0
192.168.4.2        link#12            UH       ovpns1
192.168.5.0/24     192.168.5.2        UGS      ovpns2
192.168.5.1        link#13            UHS         lo0
192.168.5.2        link#13            UH       ovpns2
192.168.6.0/24     192.168.6.2        UGS      ovpns3
192.168.6.1        link#9             UHS         lo0
192.168.6.2        link#9             UH       ovpns3
192.168.200.0/24   link#4             U          igb3
192.168.200.2      link#4             UHS         lo0
192.168.255.5      link#10            UH       ovpnc4
192.168.255.6      link#10            UHS         lo0
200.91.75.6        192.168.200.1      UGHS       igb3
```

For clarity, here's an extract of the incorrect pfctl rules:

```
pass out route-to (ovpnc6 37.230.169.211) inet from 37.230.169.211 to ! (ovpnc6:network) flags S/SA keep state allow-opts label "87da0913f3cda568f73a7be10c81afbf"
pass in quick on ovpnc6 reply-to (ovpnc6 37.230.169.211) inet proto icmp from any to (self) icmp-type echoreq keep state label "4dadfb416040bd237bbf65e0e2ae9078"
pass in quick on igb1 route-to (ovpnc6 37.230.169.211) inet from <MASKVPN_CLIENT> to ! (igb1:network) flags S/SA keep state label "3d3b054f06749f915e330760df158d84"
block return in log quick on ovpnc6 reply-to (ovpnc6 37.230.169.211) inet all label "ff47eff3fcc7bc4766bdb4b39d48123f"
```

These rules instruct the PBR to route/accept/reject traffic using 37.230.169.211. That happens to be the firewall's local IP on that interface. The error is that every instance of **_37.230.169.211_** in these lines should instead point to **_37.230.169.193_**, except the second one in line 1, which is correct, like so:

```
pass out route-to (ovpnc6 37.230.169.193) inet from 37.230.169.211 to ! (ovpnc6:network) flags S/SA keep state allow-opts label "87da0913f3cda568f73a7be10c81afbf"
pass in quick on ovpnc6 reply-to (ovpnc6 37.230.169.193) inet proto icmp from any to (self) icmp-type echoreq keep state label "4dadfb416040bd237bbf65e0e2ae9078"
pass in quick on igb1 route-to (ovpnc6 37.230.169.193) inet from <MASKVPN_CLIENT> to ! (igb1:network) flags S/SA keep state label "3d3b054f06749f915e330760df158d84"
block return in log quick on ovpnc6 reply-to (ovpnc6 37.230.169.193) inet all label "ff47eff3fcc7bc4766bdb4b39d48123f"
```

**To Reproduce**
1. Go to 'VPN/OpenVPN/Clients'
2. Click on 'Add'
3. Create an OpenVPN connection as per:
![](https://user-images.githubusercontent.com/6098503/82929411-d6483080-9f40-11ea-9c85-9737707f7716.png)
4. Enter the following into the _**Advanced Configuration**_ text area:
```
pull-filter ignore "redirect-gateway"
explicit-exit-notify

fast-io
remote-random
verify-x509-name Secure-Server name
remote-cert-tls server
key-direction 1
sndbuf 524288
rcvbuf 524288
```
5. Bring the client up.
6. Verify that the OpenVPN configuration looks like [this example](https://github.com/opnsense/plugins/files/4683901/client6.txt)
(obvious differences notwithstanding).
7. Validate that the IPv4 routing table looks like the one shown above.
8. Validate that the ifconfig parameters are consistent with the routing table for the client interface.
9. Add a policy-based routing rule that tunnels traffic for a specific set of clients (defined by an alias group) over the VPN client's gateway.
10. Apply all changes
11. Verify that the rules are rendered using incorrect values, as shown above.
12. Verify that any traffic from the clients that should be routed over the VPN actually gets no farther than the firewall itself (i.e. ping time reflects LAN connectivity, vs. WAN).

**Expected behavior**
The rules should be generated to properly render using the correct IPs for routing. Modifying the rules manually does achieve this intended behavior and traffic is routed properly.

**Screenshots**
See above.

**Relevant log files**
Here's the OpenVPN client log from the [connection coming up](https://github.com/opnsense/plugins/files/4683878/openvpn.log).

**Additional context**
IP Addresses are assigned dynamically, and thus I can't manually add rules using them in an attempt to pre-empt the issue. Thus, every time the link goes down for whatever reason, connectivity is lost and a manual rework is required.

**Environment**
OPNsense 20.1.7-amd64
FreeBSD 11.2-RELEASE-p20-HBSD
OpenSSL 1.1.1g 21 Apr 2020

**Comment by drivera-armedia** [comment]
Further proof of something weird going on, the machine's local IP is also selected as the gateway IP:

![Gateways](https://user-images.githubusercontent.com/6098503/82936245-858a0500-9f4b-11ea-8fc1-f9ec74437b63.png)

**Comment by drivera-armedia** [comment]
It gets trickier: the correct gateway IP address is only given to the ifconfig command. The --up command (referenced in the configuration file) never sees it, not as a parameter nor an environment variable.

These are the parameters sent (different IPs, same issue):
```
ovpnc6 1500 1558 141.101.149.211 255.255.255.192 init
```

This is the environment during execution of --up:

```
PWD=/
X509_0_C=HK
X509_0_CN=Secure-Server
X509_0_L=HK
X509_0_O=Secure-Server
X509_0_OU=IT
X509_0_ST=Central
X509_0_emailAddress=mail@host.domain
X509_0_name=changeme
X509_1_C=HK
X509_1_CN=Secure-ServerCA
X509_1_L=HK
X509_1_O=Secure-ServerCA
X509_1_OU=IT
X509_1_ST=Central
X509_1_emailAddress=mail@host.domain
X509_1_name=Secure-ServerCA
common_name=Secure-Server
config=/var/etc/openvpn/client6.conf
daemon=1
daemon_log_redirect=0
daemon_pid=90191
daemon_start_time=1590519840
dev=ovpnc6
dev_type=tun
foreign_option_1=dhcp-option DNS 141.101.149.3
foreign_option_2=dhcp-option DNS 141.101.149.5
ifconfig_broadcast=141.101.149.255
ifconfig_local=141.101.149.211
ifconfig_netmask=255.255.255.192
link_mtu=1558
proto_1=udp4
remote_1=<server-remote-ip>
remote_port_1=53
script_context=init
script_type=up
tls_digest_0=c4:21:55:de:da:b2:95:87:2f:16:66:a2:33:9b:fd:8d:95:31:a2:3a
tls_digest_1=1e:9e:f4:a4:a7:62:d9:20:78:ab:3f:aa:96:f1:88:02:f0:4b:e4:99
tls_digest_sha256_0=85:aa:36:26:78:4b:33:99:68:22:8a:dd:2a:0c:d8:a5:33:46:28:59:c0:2f:e3:07:cc:90:6a:85:1d:a6:1a:32
tls_digest_sha256_1=cf:db:d6:4f:77:bb:b7:c8:dc:80:41:19:b4:ee:3d:f3:71:a1:48:12:93:0c:ff:2c:73:68:81:bf:4f:e9:ac:4d
tls_id_0=C=HK, ST=Central, L=HK, O=Secure-Server, OU=IT, CN=Secure-Server, name=changeme, emailAddress=mail@host.domain
tls_id_1=C=HK, ST=Central, L=HK, O=Secure-ServerCA, OU=IT, CN=Secure-ServerCA, name=Secure-ServerCA, emailAddress=mail@host.domain
tls_serial_0=2
tls_serial_1=14472060699488478373
tls_serial_hex_0=02
tls_serial_hex_1=c8:d7:16:87:a8:e6:e4:a5
trusted_ip=141.101.149.4
trusted_port=53
tun_mtu=1500
untrusted_ip=141.101.149.4
untrusted_port=53
verb=4
xormask_1=
xormasklen_1=0
xormethod_1=0
```

The correct Gateway IP should have been 141.101.149.193, as set via ifconfig:

```
ovpnc6: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> metric 0 mtu 1500
	options=80000<LINKSTATE>
	inet6 fe80::2e0:67ff:fe0e:3504%ovpnc6 prefixlen 64 scopeid 0xe 
	inet 141.101.149.211 --> 141.101.149.193 netmask 0xffffffc0 
	nd6 options=21<PERFORMNUD,AUTO_LINKLOCAL>
	groups: tun openvpn 
	Opened by PID 90191
```

As far as I can tell that's the only reliable place to find it...

**Comment by drivera73** [comment]
See https://github.com/opnsense/core/pull/4134 for a proposed fix.

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/core/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
