### ISSUE TITLE
automatically generated gateway name can contain forbidden characters 

### ISSUE THREAD

**Issue by jjvandenberg** [opnsense/core#4143]
while setting up an IPsec VPN, I checked the option "This Interface does not require an intermediate system to act as a gateway". The option is under Interfaces --> <interface created by ipsec phase 2 rule>

When checked, a Gateway is automatically created under System --> Gateways --> Single

in my case, it's AZURE-IPSEC_GW. it uses the interface name to construct a gateway name.

However, this name does not meet the restrictions for gateway names, it can not contain a dash!

So now I cannot edit the gateway, it will report "The following input errors were detected:
The name must be less than 32 characters long and may only consist of the following characters: a-z, A-Z, 0-9, _"

Workaround for now is using a very strict naming convention that never contains any other character anytime anyplace anywhere, however I think I should report this for further finetuning the interface

**Comment by mimugmail** [comment]
The name comes from the description text of the VPN tunnel. Add preg filter for dash seems a bit hard

**Comment by fabianfrz** [comment]
@mimugmail Dash has a special meaning in regex, maybe you need to escape it with a backslash.
