### ISSUE TITLE
Gateways and gateways widget display  issue

### ISSUE THREAD

**Issue by marjohn56** [opnsense/core#4148]
On some systems where a dynamic V6 WAN address is in use the gateway widget and gateways page display the gateway as '~'. This appears to be due to this piece of code in /Opnsense/Routing/Gateways.php.

/**/ Dynamic IPv6 interface, but no router solicit response received using rtsold.
                        $gwkey = $this->newKey($thisconf['priority'], !empty($thisconf['defaultgw']));
                        // gateway should only contain a valid address, make sure its empty
                        unset($thisconf['gateway']);
                        $this->cached_gateways[$gwkey] = $thiscon**f;

This results in null being returned when queried and hence the resultant '~'.  In the system I have looked at ( not mine )  commenting out the unset($thisconf['gateway']); then gave me 'dynamic' in the gateways widget and page, which is more acceptable. However I did not look deeper to see if this has any other side effects.

**Comment by AdSchellevis** [comment]
it  has, dynamic isn't a valid gateway definition, in most cases this means there's no router file written to disk leading to an undefined gateway (https://docs.opnsense.org/manual/gateways.html#missing-dynamic-gateway).  The output of `getGateways()` should only return valid addresses which can be used in a route command.

**Comment by marjohn56** [comment]
OK, well I did a hacked version of rtsold, which writes the *v6 files even if the 'ohterconfig' flag is not set, that works, but then i was getting no ipv6 routing, even though the default v6 route and the *v6 files agreed. Very odd... any ideas why that may have been?

**Comment by marjohn56** [comment]
Here's a netstat from the users system I can remote into. First is the working table:
![image](https://user-images.githubusercontent.com/17962918/83399617-6bdc3800-a3f9-11ea-9ccb-56203a3753fe.png)

and now the one where I have hacked rtsold to write the route files.

![image](https://user-images.githubusercontent.com/17962918/83399683-86161600-a3f9-11ea-9418-06f482654178.png)

The only difference i can see us the 'Use' value, and I can't seem to find a reference for that in the (8)

**Comment by marjohn56** [comment]
Ah.. it does work, It's a dpinger thing... just trying to work that out now.
