### ISSUE TITLE
Logout and Help missing from navbar on mobile display

### ISSUE THREAD

**Issue by cbasolutions** [opnsense/core#415]
The logout and help icons are missing from the navbar when viewing from a mobile phone.

![screen shot 2015-10-02 at 1 12 14 pm](https://cloud.githubusercontent.com/assets/7894078/10252785/b7df7640-6907-11e5-9a46-9898d5ca6787.png)

**Comment by AdSchellevis** [comment]
It's supposed to hide on mobile, because it's in one block together with the status messages and won't display correctly on mobile if all text is shown.
Both items should be available in the menu on your mobile device.

**Comment by fichtner** [comment]
@cbasolutions close this? :)

btw, footer size has been reduced and now doesn't wrap ;)
