### ISSUE TITLE
Add asList to HostnameField in model

### ISSUE THREAD

**Issue by mimugmail** [opnsense/core#4157]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[X] I have searched the existing issues and I'm convinced that mine is new.

**Is your feature request related to a problem? Please describe.**
Like described in plugin PR I need the asList parameter in Model also for HostnameField:
https://github.com/opnsense/plugins/pull/1871

I use both variants here:
https://github.com/mimugmail/plugins/blob/patch-6/net/chrony/src/opnsense/mvc/app/models/OPNsense/Chrony/General.xml

But it only works for NetworkField, other gives a validation error

**Comment by AdSchellevis** [comment]
@mimugmail what kind of error do you see when using the model?  `setAsList()` is already in there and seems to be working as a charm on my end (tried it on another existing model). When set, it should return the item as a list when inspecting the network traffic.

```
   .....
    "peers": {
      "0.opnsense.pool.ntp.org": {
        "value": "0.opnsense.pool.ntp.org",
        "selected": 1
      }
    },
   .....
``` 

https://github.com/opnsense/core/blob/a73b211d0a2a935b807997fc9b45c59e3f1ea7cc/src/opnsense/mvc/app/models/OPNsense/Base/FieldTypes/HostnameField.php#L95-L106

**Comment by mimugmail** [comment]
Hi Ad,

on my end I get:

![image](https://user-images.githubusercontent.com/20438689/86589345-d26eeb80-bf8d-11ea-970c-6fbb0940a404.png)

This is my model:

```
<model>
    <mount>//OPNsense/chrony/general</mount>
    <description>Chrony configuration</description>
    <version>0.0.1</version>
    <items>
        <enabled type="BooleanField">
            <default>0</default>
            <Required>Y</Required>
        </enabled>
        <port type="PortField">
            <default>323</default>
            <Required>Y</Required>
        </port>
        <peers type="HostnameField">
            <default>0.opnsense.pool.ntp.org</default>
            <Required>Y</Required>
            <asList>Y</asList>
        </peers>
        <allowednetworks type="NetworkField">
            <Required>N</Required>
            <asList>Y</asList>
        </allowednetworks>
    </items>
</model>

```

For `allowednetworks` it works fine ...

**Comment by AdSchellevis** [comment]
Hi Michael, can you dump the request and response content from the network? (both json objects)

**Comment by mimugmail** [comment]
argh ... I foget to add `<FieldSeparator>,</FieldSeparator>`
Sorry for wasting your valueable time :(

**Comment by AdSchellevis** [comment]
hehe, things happen. let's call this case closed then :)
