### ISSUE TITLE
Unable to choose interfaces in LAGG, therefore LAGG can't be used

### ISSUE THREAD

**Issue by doublej74** [opnsense/core#416]
Unable to choose interfaces in LAGG, parent interfaces list is empty, rendering the LAGG functionality as useless.
Tried it with the latest development release(OPNsense 15.7_1082-amd64) on several systems.

**Comment by fichtner** [comment]
It's only empty if the interfaces have already been assigned. What exactly are you trying to do? How much NICs, what is already set up? As far as I know plenty of people use LAGG successfully. :)

**Comment by doublej74** [comment]
Oh, okay. I'm going to test it with unassigned ones. I think that when no valid interfaces are available it should be indicated. Now it just shows an ackward looking list, that seemed to be as a bug.

**Comment by fichtner** [comment]
We could patch up the LAGG dialog, but that won't help much with all the other static pages that need the same fix and have been labeled by some as "a dead end code base". We're already migrating parts of the GUI to a more flexible and component-based framework to address such problems way easier in the future. Please bear with us. :)
