### ISSUE TITLE
Monitor multiple IPs through/for a gateway

### ISSUE THREAD

**Issue by thutex** [opnsense/core#4163]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[x] I have searched the existing issues and I'm convinced that mine is new.

**Is your feature request related to a problem? Please describe.**

gateway monitoring only allows to monitor a single ip, limiting (smallscale) debugging.
You cannot always set up a dedicated system for something like smokeping, while you would still want to monitor connection quality.

Right now the issue is, when only being able to monitor a single IP for/through the gateway:

 ->if you monitor your next-hop, you do not know if you have packet loss behind your provider network. (so you might get a perfect looking graph, but internet quality is horrible)

-> if you monitor an internet location (say 1.1.1.1), and you experience loss, you can't determine if it is your provider's network or somewhere on the internet itself.
(meaning you don't really have a way to communicate this to the provider without, again, setting up a dedicated machine or vm)

**Describe the solution you'd like**

the solution would be to be able to monitor both, and in doing so being able to compare graphs.
(or the CSVs, ofcourse)

From what i have found online it seems to be out of the scope for dpinger.
I suggest to create an option in the frontend to add an ip to monitor,
which would then do something like running a bash script to create and update the database with the ping results.
we could then show these results in a graph on the health page.

maybe adding the choice of which gateway to use for this ping on top would also allow for monitoring the quality of available links towards a certain target.

an added bonus (imho) would be having something useful that has been requested in the pfsense community for years without results. (adding yet another reason for people to choose OPNSense)

**Comment by AdSchellevis** [comment]
To be honest, network monitoring is likely better handled using zabbix or nagios (or a similar system). 

Although I also misuse dpinger sometimes to monitor a specific host, it’s purpose from the firewall is mainly to take action when appropriate (demote gateways).

I think you can already add extra gateways with a low priority for monitoring purposes.

**Comment by thutex** [comment]
Alas, adding an extra gateway for monitoring is not possible (it does add, but then shows up as defunct)

I agree if you need full or extensive monitoring, you would need something else, however the idea here would not be full-blown monitoring, but rather confirming that:
A) the gateway is actually up, reachable, and has no packet loss and 
B) it can actually reach the internet, and there is no packet loss there

the specific reason i am asking/suggesting this, is because i am in a situation where i am talking to my provider about packet loss, and it would help to be able to monitor both the gateway IP and the remote IP to find where the packet loss is actually happening.

as i said, it's always possible to set up a new machine just for this, but the reasons for preferring this on the firewall are, to name 2:

-> it is always the first in line (most reliable to do this simple quick testing)
-> it is always on anyway, meaning you don't have to leave another machine running

i would never ask or expect the firewall to be doing real network monitoring, but graphing some ping tests is something that i'd assume to be an acceptable thing for a firewall to do.

though this is not the case for me, i assume that, for example, in production environments where you manage client firewalls you would be able to use this to monitor their network connectivity and quality to follow up on specific issues a client might report (about packet loss),
since you would be unlikely to monitor their connection from your network (due to resources, dynamic ip, ...)
this way you would be able to get the results without having to tell the customer you will set up a monitoring and see what happens next week.

**Comment by mimugmail** [comment]
You can add these IPs as gateways and dont set upstream gateway. Also tick far gateway when not in range.

Usually you take smokeping for this :)

**Comment by thutex** [comment]
adding the IP to monitor as a gateway itself does indeed work, so i have done that now, which "solves" my current issue for monitoring the GW and and internet target but it's probably not really the best thing to do, so this request would make it somewhat more "clean" to monitor i suppose.

and integrating smokeping to opnsense is not desirable, while setting up a new machine (virtual or otherwise, which has to run 24/7 alongside your firewall) to monitor 1 extra IP would be overkill as well.

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/core/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
