### ISSUE TITLE
Add Uplink (pppoe) (historical) connectivity logging

### ISSUE THREAD

**Issue by thutex** [opnsense/core#4164]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[x I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[x] I have searched the existing issues and I'm convinced that mine is new.

**Is your feature request related to a problem? Please describe.**

There is a lack of monitoring/logging the availability of the upstream connection (with PPPOE).
This might be of little consequence when the uplink is a router or cable modem (i would assume there might be other ways to discover or log the reasons for connectivity loss in that case)
Right now i can monitor if my vdsl link goes down (fritzbox would catch this, which i can reach through the firewall), but there is no way to see if my PPPOE connection was lost somewhere in the last week, for example.

**Describe the solution you'd like**
Since OPNSense will most likely notice a PPPOE session disconnecting and reconnecting, i would like to ask for these events to be logged into a timestamped logfile accessible through the GUI's logging option.

This would make it significantly easier to troubleshoot some issues with the PPPOE session, without having to relocate it to the modem.

Less specific to PPPOE, but still related to this request would be adding a physical connection up/down logging to this file.
(which would report physical uplink down, covering dhcp/cable modem uplinks)

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/core/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
