### ISSUE TITLE
Firewall: Diagnostics: pfTables - one entry missing in the list

### ISSUE THREAD

**Issue by astromeier** [opnsense/core#4165]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

Issue #3848 is on V19, I can see that error on
OPNsense 20.1.7-amd64
FreeBSD 11.2-RELEASE-p20-HBSD
OpenSSL 1.1.1g 21 Apr 2020

[X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[X] I have searched the existing issues and I'm convinced that mine is new.

**Describe the bug**
In the Firewall: Diagnostics: pfTables list is one entry missing.
Seen in the 19 and 20 version of opnsense

One side remark: sorting rows (e.g. packets) by clicking on them doesn't work....

**To Reproduce**
Take an alias with a low count of entries and list them
Goto Firewall: Diagnostics: pfTables and choose that alias.
Look at the line "Showing 1 to xx of xx entries"
Count the list entries  - one is missing....
Compare with the alias list - one is missing and not the first or last...

**Expected behavior**
The pfTables list should show the correct number of entries

**Screenshots**
see attachment
![Missing_Entry](https://user-images.githubusercontent.com/38014958/84429639-cdd24400-ac28-11ea-80e8-a9931aa2c9e1.png)
The alias contains one IP address which is not listed, but counted:
"Showing 1 to 1 of  entries"

**Relevant log files**
none

**Additional context**
none

**Environment**
OPNsense V19 and V20 series
actual:
OPNsense 20.1.7-amd64
FreeBSD 11.2-RELEASE-p20-HBSD
OpenSSL 1.1.1g 21 Apr 2020

**Comment by AdSchellevis** [comment]
can't reproduce, an alias with a single item in it look normal on my end (chrome 83.0.4103.97)
![image](https://user-images.githubusercontent.com/9783985/84561208-c73bed80-ad4a-11ea-9948-2442cfbb6f22.png)

**Comment by astromeier** [comment]
Ok - issue was on my side:
All three browsers I used (Opera, Chromium and Firefox) seemed to have cached data that produces my issue. 
Forced reload with cache bypass (Ctrl + F5 or shift + F5) didn't help.
Manual deletion of all browser data of my three browsers helped ...
Issue closed..

**Comment by astromeier** [comment]
Delete all browser data (not only cache) helps. 
Forced reload with cache bypass (Ctrl + F5 or shift + F5) didn't help.
