### ISSUE TITLE
ESXI 7 - Add a 4 network adapter

### ISSUE THREAD

**Issue by NelioRomao** [opnsense/core#4167]
***GOT REQUEST TO AUDIT HEALTH***
>>> Check installed kernel version
Version 20.1.7 is correct.
>>> Check for missing or altered kernel files
No problems detected.
>>> Check installed base version
Version 20.1.7 is correct.
>>> Check for missing or altered base files
No problems detected.
>>> Check for and install missing package dependencies
Checking all packages: .......... done
>>> Check for missing or altered package files
Checking all packages: .......... done
>>> Check for core packages consistency
Checking core packages: ..................................................................... done
***DONE***

ESXI SERVER : 7.0.0 (Build 15843807)

Step 1
  Go to VMware vSphere 7 Hypervisor
  Edit VM - OPNsense

  Assign 3 Network Adapters with **Manual assign MAC ADDRESS** not automatic
  to insure that OPNsense don't lose any assignment interfaces!!! or the ESXI don't
  change MAC Address them.

Step 2
 Configure 3 interfaces in OPNsense
 WAN - DHCP
 LAN -  DHCP server on + Firewall rules
 OPT1  - DHCP server on + Firewall rules

Step 3
  Shutdown OPNsense

Step 4
 Go to VMware vSphere 7 Hypervisor
 EDIT VM - OPNsense
 Add a new Network Adapter with manual or automatic MAC Address.

Step 5
 Start OPNsense

Step 6 (chaos begins)
   Now interfaces that have been assign to  physical/virtual adapter have lost
   there  physical/virtual network adapter and get a different one.

EX:
    **On the first boot**
       LAN - vmx0  (00:50:56:37:F0:F1)
       WAN - vmx1 (00:50:56:37:F0:F2)
       OPT1 - vmx2 (00:50:56:37:F0:F3)

    **Second boot** with the new network adapter added **but not Assign**
       LAN - vmx0  (00:50:56:37:F0:F2)
       WAN - vmx1 (00:50:56:37:F0:F4)
       OPT1 - vmx2 (00:50:56:37:F0:F3)

The order that physic  adapter get assign to interface on the begin  of the setup
have just **been change  automatic.!**!!!!

That means the WAN interface will not get a valid IP  from the ISP because know
is on the wrong network adapter  and no access to the GUI.

**Comment by Bran-Ko** [comment]
I have the same behaviour on every OPNsens @esxi (on different esxi versions). I try to fix them but unsuccessfully...

**Comment by mimugmail** [comment]
You will also see this behavior with vanilla FreeBSD, as it doesnt use UUIDs like Linux

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/core/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
