### ISSUE TITLE
proxy server: cache management options

### ISSUE THREAD

**Issue by fichtner** [opnsense/core#417]
HDD and RAM cache size et al.

good example via: https://doc.pfsense.org/index.php/Setup_Squid_as_a_Transparent_Proxy

**Comment by AdSchellevis** [comment]
Not sure if we're missing something here, General Proxy settings -> Local cache setting defines cache sizes.
Resulting in : cache_dir ufs .... (http://www.squid-cache.org/Doc/config/cache_dir/)

**Comment by AdSchellevis** [comment]
Maybe only add configurable "cache_mem", this one is now defaulting at 256MB
