### ISSUE TITLE
Assigning an IP alias to the loopback interfaces makes it appear as unconfigurable interface in the interfaces section

### ISSUE THREAD

**Issue by WRMSRwasTaken** [opnsense/core#4170]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[x] I have searched the existing issues and I'm convinced that mine is new.

**Describe the bug**
Adding an IP alias to Loopback via Firewall -> Virtual IPs creates a new interface in the Interfaces tab named `LO0`. Clicking it will bring you to the Assignments section.

**To Reproduce**
1. Go to Firewall -> Virtual IPs -> Settings
2. Assign a new IP Alias to the Loopback interface (in my case `192.168.1.1/32`)
4. Apply the configuration

**Expected behavior**
The `lo0` interface should not appear on the interfaces section.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/4244869/84649953-aec50200-af07-11ea-82c0-1c973006e14e.png)
![grafik](https://user-images.githubusercontent.com/4244869/84649383-ba63f900-af06-11ea-803d-1a4f6fe6c39b.png)

**Relevant log files**
N/A

**Additional context**
Downloading a config dump and looking at the XML file, there is a self closing `<lo0/>` tag in the `<interfaces>` section. I think this is redundant and might cause this behavior, because the assigned VIP to the loopback interface is already stored in the `<virtualip>` section in the XML config file.

**Environment**
Software version used and hardware type if relevant.
e.g.:

OPNsense 20.1.7-amd64
FreeBSD 11.2-RELEASE-p20-HBSD
OpenSSL 1.1.1g 21 Apr 2020

Seen on our datacenter firewall, tested on Virtualbox aswell.

**Comment by AdSchellevis** [comment]
Is there only one vip? or are there more? on my and adding a loopback address seems to work like a charm.

![image](https://user-images.githubusercontent.com/9783985/84650498-a91bec00-af08-11ea-987a-8d5d84a95b5f.png)

```
lo0: flags=8049<UP,LOOPBACK,RUNNING,MULTICAST> metric 0 mtu 16384
	options=600003<RXCSUM,TXCSUM,RXCSUM_IPV6,TXCSUM_IPV6>
	inet6 ::1 prefixlen 128 
	inet6 fe80::1%lo0 prefixlen 64 scopeid 0x6 
	inet 127.0.0.1 netmask 0xff000000 
	inet 192.168.123.125 netmask 0xffffffff 
	nd6 options=21<PERFORMNUD,AUTO_LINKLOCAL>
	groups: lo 
```
(haven't tried it on an empty box, the interface section probably shouldn't interfere, the current master branch adds lo0 with details for consistency reasons, although I'm not 100% sure this change will make it to the release version)

**Comment by WRMSRwasTaken** [comment]
It's a fresh installation for me. This is the first added virtual IP.

**Comment by WRMSRwasTaken** [comment]
If I download the config dump, open it in an editor and edit out the self closing `<lo0/>` tag in the `<interfaces>` section, the unclickable interface in the web GUI is gone, while still being configured.

**Comment by AdSchellevis** [comment]
I probably misunderstood, your lo0 interface has the additional address, but there's also an empty lo0 tag in the interface section, right?

**Comment by WRMSRwasTaken** [comment]
Yes, exactly. Clicking it will just redirect you to the assignments section. And it's not listed there aswell.

**Comment by AdSchellevis** [comment]
ok, that's odd indeed, did it first appear after saving the VIP?

**Comment by WRMSRwasTaken** [comment]
Yes. As I said, I was able to remove the empty lo0 from the interface list. But clicking edit in the virtual IP section and hitting save directly afterwards and applying the config makes it appear as empty in the Interfaces section again. So I guess this would happen on your box aswell.

**Comment by AdSchellevis** [comment]
but did it show after save or apply? both are different actions, I expect some function reads (and taints) the lo0 interface section. We have seen similar behaviour with some of our other legacy components in the past as well (and not a lot of people use VIPs on lo0, so it's easily unnoticed)

**Comment by WRMSRwasTaken** [comment]
Give me a second, I am able to try this via Virtualbox snapshots...

**Comment by WRMSRwasTaken** [comment]
Just creating the VIP and saving out without applying it makes it already appear:
![grafik](https://user-images.githubusercontent.com/4244869/84654044-c784e600-af0e-11ea-9222-7eaeb6fc58cb.png)

**Comment by AdSchellevis** [comment]
ok, thanks, I'll take a look.

**Comment by AdSchellevis** [comment]
@WRMSRwasTaken https://github.com/opnsense/core/commit/eb7c62b605fd949e2a5e7e3585bdada1918b764c should to the trick.

**Comment by WRMSRwasTaken** [comment]
Yes! Running `opnsense-patch eb7c62b` and trying to recreate the problem does not make it appear anymore in the Interfaces section.

**Comment by WRMSRwasTaken** [comment]
The question now is: How to deal with configs already having the self-closing tag in the config / having the empty lo0 interfaces showing up on the Interfaces section. 

I think downloading the config and editing it is not very appealing to most people...

**Comment by AdSchellevis** [comment]
probably not, but since this has been in there for a very long time, I think we can avoid further actions at the moment. (if it happens a lot, we could exclude empty entries for the menu)
