### ISSUE TITLE
Proxy: custom error pages

### ISSUE THREAD

**Issue by AdSchellevis** [opnsense/core#4174]
Our proxy error pages use the squid defaults at the moment, since people want to be able to customise these pages, this FR should allow an option to store custom pages in the configuration.

As suggested in https://github.com/opnsense/core/issues/828, a similar option as the Captive portal would be provided to upload/download pages the user can change and upload.

Relevant configuration section:

https://github.com/opnsense/core/blob/ae39e9be1773560d9800d42193acde134569e305/src/opnsense/service/templates/OPNsense/Proxy/squid.conf#L455

------
Sponsored by Incenter Technology (https://www.incenter.tech/)

**Comment by AdSchellevis** [comment]
to install on OPNsense 20.1.7 :
```
opnsense-patch  b4212f7 d7abe75 53460ce 
mv /usr/local/opnsense/scripts/proxy/install_template.py  /usr/local/opnsense/scripts/proxy/deploy_error_pages.py
mkdir -p /usr/local/opnsense/data/proxy
mv /usr/local/opnsense/scripts/proxy/template_error_pages /usr/local/opnsense/data/proxy/
opnsense-patch f32e4b2  

service configd restart
```

**Comment by AndyX90** [comment]
@AdSchellevis Would it be possible to include the C-ICAP - MALWARE FOUND - Page?

**Comment by AdSchellevis** [comment]
@AndyX90 probably not, because it's not part of the squid errors (if I'm not mistaken c-icap hosts its files somewhere else as well). If there is a feedback possible to return icap errors into squid's normal stack, it might be suitable, but I don't think there is.

**Comment by AndyX90** [comment]
@AdSchellevis Okay, my approach was that the Squid-Proxy-Template engine could be extended to nearly the whole system, including some plugin-themings as well. Like custom nginx pages (https://github.com/opnsense/plugins/tree/master/www/nginx/src/etc/nginx/views), icap (https://github.com/opnsense/plugins/tree/master/www/c-icap/src/opnsense/service/templates/OPNsense/CICAP) and maybe others. So that you can present a nearly uniform design to the users.

**Comment by AdSchellevis** [comment]
@AndyX90 I can see why that looks attractive, but these components don't have a real relation with each other, which would taint the separation of concerns.

This often leads to either illogical spots from the user to change things (Nginx has no relation with proxy) or vague issues since services get glued together (restart squid, c-icap doesn't know). 

We have spend years to remove most of these constructions from our code base, which is why we are very cautious bringing these back in. (For this to function properly would mean there would be some kind of contract between services to use this functionality, which isn't on our wish list at the moment).

**Comment by AndyX90** [comment]
@AdSchellevis Okay, i understand. Thank you anyway!
