### ISSUE TITLE
Alias for OpenVPN feature request

### ISSUE THREAD

**Issue by hypemedia** [opnsense/core#4176]
In OpenVPN Server config there is an option to add IPv4 Local Network that it will add the IP to the route. Not the only possibility is to use the text field and add the IP's as comma separated. But if you use this and add several IP's it becomes almost impossible to manage. Is there any possibility of adding here an ALIAS as it possible in the firewall config.

It will make the whole process more easy to configure and specially maintain if you have many IPs

**Comment by maxfield-allison** [comment]
looking at this now

**Comment by AdSchellevis** [comment]
@maxfield-allison this might not be the base issue to track to be honest, since it has a risk of cluttering components that should be more or less loosely coupled.

**Comment by maxfield-allison** [comment]
@AdSchellevis after looking through the files, I'm in agreement. Don't see any simple way of doing it.

**Comment by hypemedia** [comment]
OK I see but any type of improvement on that field can be done? If you have  many IPs that you want to route in it is impossible to do that from the small input text field.

**Comment by maxfield-allison** [comment]
Can you explain in more detail how many IP's and whether they are subnets or individual IP addresses?

**Comment by maxfield-allison** [comment]
@hypemedia A possible workaround would be to assign only the subnets you need to allow access to and then use a firewall alias to block or pass traffic to those specific devices.

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/core/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
