### ISSUE TITLE
Zerotier  stops after a while (30min - 2h) 

### ISSUE THREAD

**Issue by jstrebel** [opnsense/core#4177]
In the Dashbord the Icon indcates red. Under VPN Zerotier the green "arrow flag" is on.  under Networks I get unable to retrieve network info.  Sometime I can restart zerotier via the shell "zerotier-one". Sometime "zerotier-one" just hangs. Checking via myzerotier shows OPNsense was connected.  But it lost the zerotier connection.
Running the latest 20.1.7 on APU3
What can I do helping, to get better info to find the root cause?
Jakob

**Comment by AdSchellevis** [comment]
duplicate https://github.com/opnsense/plugins/issues/1876, no need for new tickets in core.
