### ISSUE TITLE
ipsec Phase2 config, multiple left|rightsubnet

### ISSUE THREAD

**Issue by sooslaca** [opnsense/core#4183]
Hi Team,

Per https://wiki.strongswan.org/projects/strongswan/wiki/ConnSection ipsec.conf left|rightsubnet supports comma separated list of subnets.
On opnsense UI "VPN: IPsec: Tunnel Settings" (Add new Phase2) Local Network Type can only be "Address/Network"

**Describe the solution you'd like**
Can there be a "Custom"/"Manual" option there so I can write comma separated list right there?

**Describe alternatives you've considered**
Don't see any alternatives for this other than creating one Phase2 entry per subnet which is not ideal for my use case.
I saw "Manual SPD entries" on the bottom that does not create the same as multiple subnets as the client is roadwarrior.

**Additional context**
NA

**Comment by mimugmail** [comment]
Currently not possible and hard to implement. You could add your custom conn via include file.

**Comment by lastuptodate** [comment]
To implement multiple comma separated left subnet, you can add multiple phase 2 (same phase 2 proposal but different local network)

Be carefull that Microsoft Windows do not push automatically routes. You have to play with add-vpnconnectionroutes...

**Comment by sooslaca** [comment]
I think that results two different `conn` sections as subconn like `conn con6-003`
Include file works well though, thanks for that @mimugmail

**Comment by lastuptodate** [comment]
> I think that results two different `conn` sections as subconn like `conn con6-003`
> Include file works well though, thanks for that @mimugmail

I have done that on my ipsec and I have only 1 "conn con1" with:
leftsubnet = 10.0.0.0/8,198.18.0.0/26,198.19.139.64/29
