### ISSUE TITLE
IPs in ARP table not sorted numerically

### ISSUE THREAD

**Issue by xorbital** [opnsense/core#4185]
**Describe the bug**
The ARP table sorts the IPs in this order:
- 192.168.1.1
- 192.168.1.11
- 192.168.1.2

**To Reproduce**
Go to Interfaces - Diagnostics - ARP table
Click on "IP" to sort via IP.

**Expected behavior**
The IPs should be sorted in numeric ascending / descending order

**Screenshots**
![Screenshot_2020-06-26 ARP Tabelle Diagnose Schnittstellen OPNsense localdomain](https://user-images.githubusercontent.com/53773184/85863441-70f79180-b7c3-11ea-89f8-9c5e572294fd.png)

**Relevant log files**
(not applicable)

**Additional context**
It seems like the IPs are interpreted as a string while there should probably be some number sorting going on.

**Environment**
OPNsense 20.1.7-amd64

Thank you very much for your work on this project, I really appreciate it :heart:

**Comment by pakair** [comment]
arp -n | sort -V produces ip-sorted output.
