### ISSUE TITLE
Allow to enter a note/description for items in alias

### ISSUE THREAD

**Issue by andrewhotlab** [opnsense/core#4190]
Hi to all, OPNsense GUI is very nice, especially compared to pfSense's one, but I miss so badly a little yet essential feature that makes me feel bad each time I insert multiple items inside an alias (a list of networks, hosts, or ports): there is no way to add a comment/note for each of them, making impossible to remember each network/host/port's meaning.

Here is the pfSense screenshot:

![Screenshot_2020-07-02_19-29-19](https://user-images.githubusercontent.com/26433166/86391646-6d1faf80-bc9a-11ea-9522-3d42b6d534ce.png)

While this is the corresponding screen in OPNsense's GUI:

![Screenshot_2020-07-02_19-29-58](https://user-images.githubusercontent.com/26433166/86391683-7ad53500-bc9a-11ea-9b0b-e6333cd372c0.png)

Call me pedantic, but I believe that such a feature is so useful that its absence makes absurdly cumbersome for a lot of people to manage aliases in OPNsense... please add it to the next release! Or at least point me to the right path to work for building it (I'm not a developer, but I need it so badly that I'll give it a shot).

Thanks, and keep up the wonderful work with OPNsense!

**Comment by AdSchellevis** [comment]
For background information why this feature won't be included, see this forum thread https://forum.opnsense.org/index.php?topic=9302.0 for network/hosts groups we added a type to improve overview in https://github.com/opnsense/core/issues/4006

**Comment by andrewhotlab** [comment]
Thank, this makes operations for maintaining aliases a way more difficult in a lot of scenarios, but if it's technically needed to make API work for a future where we'll be able to manage a bunch of firewalls from a central location, we'll likely cope with it! :)
