### ISSUE TITLE
Make provision for fallover upon loss of gateway connection when using multiple WAN connections attached to different routers

### ISSUE THREAD

**Issue by sesquipedality** [opnsense/core#4194]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[-] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

Yes

[-] I have searched the existing issues and I'm convinced that mine is new.

Yes

**Is your feature request related to a problem? Please describe.**

I am trying to set up redundant routing using a local CARP interface.  I have two opnsense routers connected to two different ISPs.  I have configured one as the CARP master, which pushes relevant configuration to the backup.   When the master is down, this works as expected, and the backup takes over the CARP interface.   However, when the master loses its WAN connection, fallback does not occur because the master is still able to process packets

**Describe the solution you'd like**
(e.g. I would like an input field in the `/ui/firewall/alias` which would add .... to ....)

I would like OPNsense to be able to dynamically adjust the skew on the carp interface if the WAN link is down.  This can be accomplished using "sysctl net.inet.carp.demotion".  Ideally it should be able to increase its skew above the backup if there is no WAN traffic, and to drop it below the backup when WAN traffic is restored.

**Describe alternatives you've considered**

Alternatives are to configure a WAN group with routing from the master to the backup.  This is tricky to get working (I haven't managed it) and can result in packets taking a different route on send to return., which can lead to other problems.   

**Additional context**

**Comment by sesquipedality** [comment]
Practically I think this could be added by adding another option to firewall_virtual_ip_edit.php as follows:

Tickbox: Change skew if gateway down
Gateway: Dropdown of gateway or gateway group
Skew offset: positive or negative number

Then whatever code monitorrs the gateway status could apply/disapply the skew when the gateway status changes.

**Comment by AdSchellevis** [comment]
I'm not planning to work on this, but can give you some pointers on how this should work, since we added a similar mechanism for frr some time ago (https://github.com/opnsense/plugins/pull/1460).

https://docs.opnsense.org/development/backend/carp.html

The challenge here is to come to an easy to understand feature, since quite some people will expect different things here.

**Comment by mimugmail** [comment]
> I'm not planning to work on this, but can give you some pointers on how this should work, since we added a similar mechanism for frr some time ago ([opnsense/plugins#1460](https://github.com/opnsense/plugins/pull/1460)).
> 
> https://docs.opnsense.org/development/backend/carp.html
> 
> The challenge here is to come to an easy to understand feature, since quite some people will expect different things here.

.. or you change your network design so both units are master / slave or neither carp is used and you have dynamic routing internally

**Comment by sesquipedality** [comment]
The issue is that there are NATed incoming services and both WAN links are dynamic IP which means I am reliant on dyndns, so I don't think I can make the routers interchangeable.   Even if I could, neither would gracefully fall back to the other on loss of gateway connectivity.

I think dynamic routing using OSPF may be an option, and I'll look into that some more I think.

**Comment by mimugmail** [comment]
It will fit really smart since also cheap 3rd party routers can run OSPF, or even some switches are capable :)
