### ISSUE TITLE
Flushing alias through API not working

### ISSUE THREAD

**Issue by jvandenbroek** [opnsense/core#4196]
Flushing an hosts or networks alias through API or via Firewall -> Diagnostics -> pfTables doesn't retain. At first it seems empty, but entries are still there at Firewall -> Aliases. 

OPNsense 20.1.8_1-amd64
FreeBSD 11.2-RELEASE-p20-HBSD
OpenSSL 1.1.1g 21 Apr 2020

**Comment by zerwes** [comment]
I can confirm this:
```
"POST /api/firewall/alias_util/flush/GE_BLOCKBADGUYS_dynamic HTTP/1.1" 200 17
<Response [200]>
```
seems ok
```
"GET /api/firewall/alias_util/list/GE_BLOCKBADGUYS_dynamic HTTP/1.1" 200 49
<Response [200]>
{'current': 1, 'rowCount': 9999, 'rows': [], 'total': 0}
```
but re-fetching the alias **after some time** using `alias_util` or **directly after the flush action** using `/api/firewall/alias/getItem/$UUID` still shows up the list
```
"GET /api/firewall/alias_util/list/GE_BLOCKBADGUYS_dynamic HTTP/1.1" 200 111
<Response [200]>
{   'current': 1,
    'rowCount': 9999,
    'rows': [   {'ip': '11.22.33.44'},
                {'ip': '11.22.33.55'},
                {'ip': '11.22.33.66'}],
    'total': 3}
```

As @jvandenbroek already noticed, this can even be reproduced using the UI Firewall -> Diagnostics -> pfTables:

1. select a alias
2. press flush
3. ack w/ `yes`
4. the list will disappear
5. press the refresh button each 10 seconds
6. at least after the 4. refresh the list will show up as it was originally ...

**Comment by AdSchellevis** [comment]
Flush isn't persistent indeed, it's only intended for dynamic aliases (like gui-lock) which will populate again when needed.
you can just use the alias delete end point followed by apply from an api perspective.

**Comment by zerwes** [comment]
Hm ... this is not documented and it is a behavior that differs from the other actions.

**Comment by AdSchellevis** [comment]
it has been like this for ages, but do feel free to contribute to the docs (https://github.com/opnsense/docs) to explain this better. Explaining the behaviour in the docs would certainly help.

**Comment by zerwes** [comment]
Created a PR with some short notes added regarding the flush behavior.
https://github.com/opnsense/docs/pull/298

**Comment by zerwes** [comment]
> OPNsense-bot closed this 1 hour ago
to late ist to late, even if it is just one hour :-1:

**Comment by marjohn56** [comment]
The PR isn't closed though.
