### ISSUE TITLE
"Monit" is unable to monitor "/var/log/system.log" for changes

### ISSUE THREAD

**Issue by vicmarto** [opnsense/core#4197]
**Describe the bug**
"Monit" is unable to monitor "/var/log/system.log" for changes.

**To Reproduce**
1. In "Services > Monit > Settings":
2. Configure "General Settings" with your preferred SMTP server
3. Configure "Alert Settings" with your email
4. Configure "Service Test Settings" as:
- Name: ALL
- Condition: content = ".*"
- Action: Alert
5. Configure "Service Settings" as:
- Enable service checks: [√]
- Name: system.log
- Path: /var/log/system.log
- Test: [√] ALL

**Expected behavior**
An email with all changes in "/var/log/system.log"

**Additional context**
It's working with other files, even files with a 600 permissions like "/var/log/system.log"

**Environment**
opnsense 20.1.8

**Comment by AdSchellevis** [comment]
system.log is a circular log file, which needs `clog` to be parsed. OPNsense 20.7 will offer the possibility to disable legacy clog format in favour of a log directory (with a file per day e.g. `/var/log/system/system_YYYYMMDD.log`

**Comment by vicmarto** [comment]
Thank you very much @AdSchellevis, this explains all.
