### ISSUE TITLE
SSH to OPNSense via IPV6 to firewall doesn't work on boot

### ISSUE THREAD

**Issue by IShouldHaveBeenAQATester** [opnsense/core#4198]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[X] I have searched the existing issues and I'm convinced that mine is new.

**Describe the bug**
A clear and concise description of what the bug is, including last known working version (if any).

*Tip*: to validate your setup was working with the previous version, use opnsense-revert (https://docs.opnsense.org/manual/opnsense_tools.html#opnsense-revert)

**To Reproduce**
1. Restart OPNSense.
2. Wait for ipv6 pd to be assigned on wan.
3. Wait for ipv6 on lan (which is tracking wan) to get an IP
4. I can now SSH into opensense box via LAN IPV4 (static), but not IPV6 (tracking wan)
5. Try to ping ipv6 lan interface (works)
6. Try to ssh to ipv6 lan interface (doesn't work...just hangs waiting for a response)
7.  Go into System -> Settings -> Administration and **disable** ssh.  Click apply.
8.  Go into System -> Settings -> Administration and **enable** ssh.  Click apply.

**Expected behavior**
Expected that ssh will be listening on ipv6 (or restart/reload) after PD is acquired on wan & assigned to tracking interfaces

**Screenshots**

**Relevant log files**

**Additional context**

**Environment**
Software version used and hardware type if relevant.
e.g.:

Only tried in OPNSense 20.1.7 and 20.1.8.  Comcast (Business) is my provider.

**Comment by fichtner** [comment]
You probably use explicit SSH interface binding? The tracked LAN IPv6 addresses are not updated in SSH automatically as that would entail a lot of messaging glue and semi-spurious restarts of the SSH daemon. In these cases it is easier to let it listen to all interfaces...

**Comment by IShouldHaveBeenAQATester** [comment]
I have it set to "LAN".  Is it better to just not check an interface so it listens "globally"?  Will it then automatically respond to any ip?

Also:  From a UI perspective, I'd assume that if I check "LAN" in the  GUI, it would work on the LAN interface, no matter if it's v4/v6, dhcp/static, etc.

**Comment by fichtner** [comment]
@IShouldHaveBeenAQATester It will latch on to any currently present IP addresses. I've advocated against this feature for a long time, people kept asking for it, and it was thus implemented under the condition of these limitations.

**Comment by IShouldHaveBeenAQATester** [comment]
I think we can close this issue.  I've decided to just go into the dashboard & restart all the services every once in a while when stuff stops working.

**Comment by fichtner** [comment]
Ok, thanks!

**Comment by amezin** [comment]
Hit by this issue today. Connecting to IPv4 address worked fine, but connecting using a hostname was hanging.

I tried to set the interface explicitly, because every time I setup something to listen on all interfaces through GUI, I'm afraid that the GUI will be too smart and will generate a rule allowing connections from WAN (yes, it does not happen, but I'm still worried).

> The tracked LAN IPv6 addresses are not updated in SSH automatically as that would entail a lot of messaging glue and semi-spurious restarts of the SSH daemon

But what's wrong with restarting sshd? As far as I know existing connections aren't affected by sshd restarts.

Would be nice if the GUI at least had an explicit warning about that (i. e. "addresses won't be updated dynamically" or "IPv6 won't work" instead of just "Use with care")

**Comment by fichtner** [comment]
Use your ISP's shifting IPv6 prefix with care is where we should document it. We can't brace for every possible side effect from this root cause.

**Comment by antcilli** [comment]
> Hit by this issue today. Connecting to IPv4 address worked fine, but connecting using a hostname was hanging.

I get this when browsing to the Web GUI. My Windows PC resolves the hostname of the firewall to the IPv6 address, but the Web GUI won't load then, so I always have to access it by IPv4 address.
