### ISSUE TITLE
OPNsense dont connect to LDAPS

### ISSUE THREAD

**Issue by thorstensd** [opnsense/core#4199]
Hello,

I`m having trouble connecting with LDAPS SSL 636 to dc.domain.intern which is a Windows active directory controller. So I think I found a bug somewhere.

Error Log is showing: 
opnsense: LDAP bind error [error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed (unable to get local issuer certificate),Can't contact LDAP server]

With the same LDAP server settings on 389 unencrypted I do not have any issues.

I test a simple ldaps connect with the shell on my OPNsense server with:
ldapsearch -H ldaps://dc.domain.intern -D ldap@domain.intern -w Passsword -s sub -b DC=domain,DC=intern
I can connect to my Active Directory and it is listing up my entrys

With
openssl s_client -connect dc.domain.intern:636 -showcerts
it shows me my internal certificate which should be correct, but of course with  Verify return code: 21 (unable to verify the first certificate), because its a internal certificate.
I can use LDAPS with other systems in my network.

Version
OPNsense 20.1.3-amd64
FreeBSD 11.2-RELEASE-p17-HBSD
OpenSSL 1.1.1d 10 Sep 2019

**Comment by mimugmail** [comment]
It's not a bug, it's intended to deny If verification fails. Try to import them as trusted certificates. You could also use stunnel plugin or also HAProxy which would also support loadbalancing over multiple DCs

**Comment by thorstensd** [comment]
thank you very much for your feedback - I tryed to add the certificate from my AD to OPNsense. I took the certificate data from the response of:
openssl s_client -connect dc.domain.intern:636 -showcerts

to system -> trust -> authoritys inside the certificate data field and restarted the OPN to be sure. But nothing has changed :-(

**Comment by thorstensd** [comment]
also added the certificate to system-> trust -> certificate including its private key. Still the same problem.

**Comment by thorstensd** [comment]
For anybody else in future having this kind of problem - I found 2 solutions.
1. I´m using a Windows certificate autority inside my network. In all Infos I found in the web, there was single information missing. The one and only thing you need to do (if you Microsoft Authority is up and running), is to put you internal public CA certificate into system -> trust -> authority (only data field needed). Make a reboot of opensense and it will work (in my case).
2. solution, use the HA-Bridge, I found a very simple instruction and it is working exactly how its written in this documentation:
https://www.routerperformance.net/opnsense-bypass-ldaps-errors-via-haproxy/

I will close this ticket and thanks a lot to your help.

**Comment by mimugmail** [comment]
2nd was written by me .. wasn't aware I put it on my blog 👍
