### ISSUE TITLE
OpenVPN User Authentication Fails

### ISSUE THREAD

**Issue by mannkind** [opnsense/core#42]
OpenVPN user authentication fails due to */usr/local/sbin/ovpn_auth_verify* trying to execute php scripts using *fcgicli*.

**Comment by fichtner** [comment]
This is a naughty one. Thanks for the report. Will definitely be fixed in time for 15.1.6.

**Comment by fichtner** [comment]
@AdSchellevis will you take this as well? That'd be awesome!

**Comment by AdSchellevis** [comment]
replaced the fcgi parts, but I have no setup to test it at the moment.

**Comment by mannkind** [comment]
@AdSchellevis Not working; auth failed still. I can't making a pull request right now, but I made a few comments on the commit.

**Comment by fichtner** [comment]
https://github.com/opnsense/core/commit/ed7e3c3e17b21f14b4f466531813ce1c296e8a61 has the $argv syntax fix.

It's trivial to wrap this up with the git installed on the box which you seem to have. Need to push out 15.1.6 right now though. Thanks for your help so far @mannkind :)

**Comment by AdSchellevis** [comment]
@mannkind thanks for your comments, I have found some more issues in the code which prevents this from working.
I have committed an other fix (https://github.com/opnsense/core/commit/3f8a9f08981d4b1f2f80a609da366ba99b96bad4). At the moment I'm unable to test this myself, so if you could find the time and test this again that would be great.

**Comment by mannkind** [comment]
@AdSchellevis  - Seems to be working after 3f8a9f0 (+ typo fix in fc27ba4). Thanks!

**Comment by fichtner** [comment]
@mannkind  Small tweaks to script. Don't think it will break, but please retest one more time and close the issue if ok. :)

**Comment by mannkind** [comment]
Continues to  function for me. Thanks again!
