### ISSUE TITLE
API exception occurs when IPsec is disabled

### ISSUE THREAD

**Issue by marcingarski** [opnsense/core#4200]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[+] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[+] I have searched the existing issues and I'm convinced that mine is new.

**Describe the bug**
API exception occurs if you go to VPN -> IPsec -> RSA Key Pairs page when IPsec is disabled (which is default).

```Error at /usr/local/opnsense/mvc/app/controllers/OPNsense/Base/ApiMutableServiceControllerBase.php:211 - Method OPNsense\Base\FieldTypes\LegacyLinkField::__toString() must return a string value (errno=4096)```

**To Reproduce**
1. Disable IPsec
2. Go to VPN -> IPsec -> RSA Key Pairs

**Expected behavior**
API exception does not occur

**Additional context**
If IPsec is enabled, the error does not show

**Environment**
OPNsense 20.1.8_1-amd64

**Comment by AdSchellevis** [comment]
this looks related to php 7.3, seems to happen when `__toString()` returns `null`, we need to check other field types as well, since I'm pretty sure this wasn't introduced recently (returning null)

**Comment by AdSchellevis** [comment]
checked, this seems to be the only case, fixed in https://github.com/opnsense/core/commit/7c43c8be36fee6438d0221904c70448000b6e3c1
