### ISSUE TITLE
FR: add "keyingtries" to IPsec Phase1 config

### ISSUE THREAD

**Issue by mimugmail** [opnsense/core#4204]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[X] I have searched the existing issues and I'm convinced that mine is new.

It happened to 3 of my customers which had an local outage or ISP with DPD enabled and action restart, that when the line was longer not available, DPD restarted VPN 5 times after the last restart it stopped doing anything. 
Also when traffic started in the morning both sides (both OPN) didn't try to bring up the tunnel. IMHO this could easily fixed when adding a field keyingtries with an integer value when 0 puts a `%forever` in it and otherwise a number (3 is default). 
As this topic doesn't seems to be noisy, it could only affect setups where DPD action `restart` is set (which is not a default).

Opinions?

**Comment by AdSchellevis** [comment]
Really no clue if it should be in there, pfSense had it in there by default a log time ago https://github.com/pfsense/pfsense/commit/9f6a5b506745475b53593c811ff8cda34ae2797b. Personally I don't mind making it optional, although from a usability perspective I'm not a huge fan of the 1000 knobs IPsec comes with.

Let's try to collect some feedback in this ticket, if there are good reasons to add it, we should do so.

**Comment by mimugmail** [comment]
Maybe reopen please. Got some positive Feedback:

https://forum.opnsense.org/index.php?topic=22217.msg105794;topicseen#msg105794

**Comment by AdSchellevis** [comment]
@mimugmail ok, it's open, but in the current state if will close automatically, so what's the plan here. Do you just want to add the (optional) setting? or is there more involved?

**Comment by mimugmail** [comment]
I'd like an integer field where 0 is %forever

**Comment by AdSchellevis** [comment]
@mimugmail no promises, but I'll take a look.

**Comment by AdSchellevis** [comment]
@mimugmail there you go https://github.com/opnsense/core/commit/e2534f5a09abc8d5bda930907dd14f6c7ba4e913, -1 means forever, 0 doesn't play well with `empty()`

**Comment by mimugmail** [comment]
Thank you Ad, this makes IPsec way more stable on unreliable uplinks

**Comment by AdSchellevis** [comment]
you're more than welcome Michael

**Comment by peysche** [comment]
THX I need This to as well

**Comment by Sieboldianus** [comment]
Is it correct that `-1` does not work in the GUI yet?

![Image](https://github.com/user-attachments/assets/6193ab51-ef2b-42e4-9297-d2c6a77244b4)

**Comment by AdSchellevis** [comment]
@Sieboldianus that's not an option, see also https://docs.strongswan.org/docs/latest/swanctl/swanctlConf.html.

**Comment by Sieboldianus** [comment]
Ok, thanks - so the only available option is `0`, where it doesn't clearly say what `fails with a permanent error` means.

**Comment by AdSchellevis** [comment]
The %forever likely came from the older migration notes (https://wiki.strongswan.org/projects/strongswan/wiki/Fromipsecconf), but as the documentation has no mention about the effect, we haven't included it in our new version to avoid undocumented side-affects. 

If it does make sense and there is upstream documentation about it, just open a new ticket (with references) so we can assess options.

**Comment by Monviech** [comment]
@Sieboldianus You can also use a high number instead (e.g., 99999). I have some feedback that this works nicely too.

**Comment by Sieboldianus** [comment]
> 99999

Good idea. However, this value is not accepted by the latest OPNsense GUI (I also tried `9999`, which is also not accepted).

**Comment by AdSchellevis** [comment]
the current max is 1000 

https://github.com/opnsense/core/blob/4d47320aba850dbc0c6e29fc2949959adb27a614/src/opnsense/mvc/app/models/OPNsense/IPsec/Swanctl.xml#L100

when something else is needed, best open a new ticket so we can track the request.
