### ISSUE TITLE
Support for OCSP stapling in administration webserver UI

### ISSUE THREAD

**Issue by pixelsquared** [opnsense/core#4205]
**Is your feature request related to a problem? Please describe.**
I am not able to **correctly** use certs that have "OCSP Must Staple" set for the administration web UI.

**Describe the solution you'd like**
I would like an option to enable OCSP stapling for the administration webserver.

**Comment by fichtner** [comment]
Apparently, this was just implemented for a future version of lighttpd so it is not completely out of scope anymore:

https://redmine.lighttpd.net/issues/2469

But FWIW you can use Nginx or HAProxy plugins to do the thing already.


Cheers,
Franco

**Comment by gstrauss** [comment]
OCSP stapling is supported in since lighttpd 1.4.56 (released Nov 2020)

Latest version of lighttpd at this moment is lighttpd 1.4.59 (released Feb 2021)

**Comment by ThePowerOfDreams** [comment]
Can we revive this? Franco seems to agree it's a good idea:

https://forum.opnsense.org/index.php?topic=26812.msg130038#msg130038

**Comment by fichtner** [comment]
There is a draft here but the question only comes up once or twice a year to be fair... https://github.com/opnsense/core/pull/5567

So we are well below the threshold for any sort of sensible user testing.

**Comment by ThePowerOfDreams** [comment]
So enable it in a dev build and we'll test it. ;)
