### ISSUE TITLE
Services: Network Time: Status - GPS Clock coordinates and gmaps link incorrect

### ISSUE THREAD

**Issue by mikahe** [opnsense/core#4209]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
[x] I have searched the existing issues and I'm convinced that mine is new.

**Describe the bug**
Network Time Status page shows incorrect Clock Latitude and Longitude compared to GPS. Formatting and conversions aren't correct. Also Google Maps Link has incorrect coordinates.

**To Reproduce**
1. Configure Network Time with GPS Generic/NMEA serial device
2. Go to 'Services: Network Time: Status'
3. Scroll down to 'Clock Latitude'
Clock Latitude and Clock Longitude
dedd.ddddd (ddmm° mmmm.00000 [N|S|E|W])

In first field I'm seeing that degrees are +1 compared to correct full degrees. Also decimal points and degrees symbol are in incorrect places.

No conversion between decimal degrees, degrees and decimal minutes (or degrees, minutes, decimal seconds) should change the degrees part of the coordinate.

**Expected behavior**
Clock Latitude and Clock Longitude should probably be shown in the below format (at least in parenthesis dd° mm.mmmm is correct location with the shown digits, and that's also in NMEA GPGGA message, i.e. ddmm.mmmm):

Clock Latitude and Clock Longitude
dd.ddddddd (dd° mm.mmmm [N|S|E|W])

Google Maps Link should be based on decimal degrees:
http://maps.google.com/?q=dd.ddddddd,dd.ddddddd

**Environment**
OPNsense 20.1.8_1-amd64

**Comment by mikahe** [comment]
The coordinates are apparently output here: src/www/status_ntpd.php:
Latitude:
<td><?= sprintf("%.5f", $gps_lat); ?> (<?= sprintf("%d", $gps_lat_deg); ?>&deg; <?= sprintf("%.5f", $gps_lat_min*60); ?><?= $gps_lat_dir ?>)</td>

**Comment by mikahe** [comment]
This is how the incorrect Lat sum is calculated:

lat+lon	6240.45
	
gps_lat_deg	6126
gps_lat_min	114.45
	
sum	of above = 6240.45

**Comment by mikahe** [comment]
The root cause of the bug is that degrees and whole minutes are combined in gps_lat_deg, so that's not actually correct. gps_lat_min contains only decimal part of minutes.

Easiest fix would probably be to set these deg and min variables correctly. Other calculations seem to be done based on this assumption.

**Comment by mikahe** [comment]
One fix would be to add these two lines:

                    $gps_lat_min = $gps_lat_deg % 100 + $gps_lat_min / 10000.0;
                    $gps_lat_deg = intdiv($gps_lat_deg, 100);

between these two lines:

                    list ($gps_lat_deg, $gps_lat_min) = explode('.', $gps_vars[3]);
                    $gps_lat_min /= 60.0;

And do the same for $gps_lon_ 's too!

**Comment by AdSchellevis** [comment]
@mikahe I'm not using the ntp gps feature at the moment, at a first glance I wouldn't mind removing the link since it's quite old and nobody noticed it over the years, but if you open a pull request with the proposed changes I'll take a look and try to merge it asap.

**Comment by mikahe** [comment]
I improved the proposed solution in pull request. The Google maps link is nice to verify that location is correct. Actually I wouldn't mind adding also openstreetmap.org link there too, but that's another topic.
