### ISSUE TITLE
Firewall: States Dump sometimes empty (maybe over 1000)

### ISSUE THREAD

**Issue by mimugmail** [opnsense/core#4210]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[X] I have searched the existing issues and I'm convinced that mine is new.

**Describe the bug**
I'm currently on a customer installation debugging loadbalancing problem with 20.1.8_1, customer has 2 WANs, both pppoe, but sometimes I see packets on WAN1 leaving with IP of WAN2 and vice versa. Then I tried to list the states and saw an empty page. When clicking couple of times states are there again.

configd.log:
`Jul 15 09:19:50 firewall configd.py: [e7330cef-8a2c-471d-b2fa-2a0fa36ec0a5] Script action failed with Command '/usr/local/opnsense/scripts/filter/list_states.py --filter='' --limit='10000'' returned non-zero exit status 1. at Traceback (most recent call last):   File "/usr/local/opnsense/service/modules/processhandler.py", line 484, in execute     stdout=output_stream, stderr=error_stream)   File "/usr/local/lib/python3.7/subprocess.py", line 363, in check_call     raise CalledProcessError(retcode, cmd) subprocess.CalledProcessError: Command '/usr/local/opnsense/scripts/filter/list_states.py --filter='' --limit='10000'' returned non-zero exit status 1.
`

```
root@firewall:~ # /usr/local/opnsense/scripts/filter/list_states.py
Traceback (most recent call last):
  File "/usr/local/opnsense/scripts/filter/list_states.py", line 89, in <module>
    record['nat_port'] = parts[3].split(':')[1][:-1]
IndexError: list index out of range
```

I'm not sure if this is related to the NAT problem, but it seems to be a bug for sure. :)

**Comment by AdSchellevis** [comment]
https://github.com/opnsense/core/commit/94985b4f80f3972112c717ff9760e6d92ac8c0e8 should suppress the error, although I haven't seen state output without nat port set to anything
