### ISSUE TITLE
Firewall - Shaper - Status: incorrect view

### ISSUE THREAD

**Issue by dinguz** [opnsense/core#4213]
**Describe the bug**
In Firewall - Shaper - Status view, with 'Show active flows' enabled, only part of the traffic is shown.

This particularly seems to happen with setups that don't use queues. I have traffic shaping setup in a way where a rule points to a pipe, and queues are not used

**Expected behavior**
All traffic is visible

**Screenshots**
![Clipboard01](https://user-images.githubusercontent.com/50438934/87949838-d418d300-caa6-11ea-9161-c71ba202daa4.jpg)

![Clipboard03](https://user-images.githubusercontent.com/50438934/87949860-daa74a80-caa6-11ea-9f25-6059b9632bc7.jpg)

**Environment**
FreeBSD haanjdj.ddns.net 11.2-RELEASE-p20-HBSD FreeBSD 11.2-RELEASE-p20-HBSD  07ef86ce9ca(stable/20.1)  amd64
HW is a Barracuda F18

**Comment by dmindfuse** [comment]
Has anyone had a chance to follow up on this presentation issue? I'm not literate in the programming language myself.

**Comment by Oriann** [comment]
For me whole **Current activity** is not showing up...

**Comment by MikeBishop** [comment]
So is a more accurate statement of this issue that "Show active flows does nothing if FlowQueue-CoDel is selected"?

**Comment by Oriann** [comment]
@MikeBishop yes

**Comment by dmindfuse** [comment]
> So is a more accurate statement of this issue that "Show active flows does nothing if FlowQueue-CoDel is selected"?

Yes

**Comment by dinguz** [comment]
The underlying reason for flows not being displayed when using
FQ-CoDel, is probably that the command line output doesn't show it
either:

q75537  50 sl. 0 flows (1 buckets) sched 10001 weight 0 lmax 0 pri 0 droptail
 sched 10001 type FQ_CODEL flags 0x0 0 buckets 1 active
 FQ_CODEL target 5ms interval 100ms quantum 1514 limit 10240 flows 1024 ECN
   Children flowsets: 10000
  0 ip           0.0.0.0/0             0.0.0.0/0        1       52  0    0   0


Met vriendelijke groet,

Derkjan de Haan

Op vr 23 aug 2024 om 09:36 schreef dmindfuse ***@***.***>:
