### ISSUE TITLE
Display issue reading IPSec logs

### ISSUE THREAD

**Issue by scs-tech** [opnsense/core#4215]
When looking at the log files in the IPSec section of VPN  (VPN/IPsec/Log File), the bottom page selector is not working properly.
Clicking on the right hand double chevron should take you to the last page, instead it behaves the same as the right hand single chevron - only advancing one page.
The left hand double and single chevrons work as expected.

![7-20-2020 3-36-25 PM](https://user-images.githubusercontent.com/10707743/87993504-7fbe2500-ca9f-11ea-9602-aa7efe951e2a.jpg)

**Comment by scs-tech** [comment]
My apologies for not having a complete "issue" template filled out:

    The current OPNsense version where the bug first appeared:
Unsure.  The issue is occuring on:
OPNsense 20.1.7-amd64
The problem also occurred on a previous version, but I dont know what version that was.

    The last OPNsense version where the bug did not exist
Unknown

    The exact URL of the GUI page involved (if any)
https://10.10.10.1/ui/diagnostics/log/core/ipsec

    A list of steps to replicate the bug
In the menu tree, go to VPN, IPsec, Log file.  With loged data in the log file containing more than 3 pages, press the right hand double chevron - it should go to the last page, it does not, it advanced only one page.

Let me know if there is more information needed.

**Comment by AdSchellevis** [comment]
This question pops up from time to time, https://github.com/opnsense/core/issues/756#issuecomment-180848249, https://github.com/opnsense/core/issues/4076, https://github.com/opnsense/core/issues/4053, https://github.com/opnsense/core/issues/756 best we can do is explain this in the docs (added a ticket here https://github.com/opnsense/docs/issues/274).
