### ISSUE TITLE
ui: unify "add" buttons in legacy page lists

### ISSUE THREAD

**Issue by abplfab** [opnsense/core#4216]
**Unify the add buttons in lists**
On some Pages there is the orange "Add" Button on top of the page / list. On other pages there is only the small "+" at the end of the list.

**Pages with orange add button on top**

Move the buttons to the table header, markup add buttons with btn-primary. After carrying this out get rid of $main_button use in fbegin.inc.

- [x] System: Access: *
- [x] System: Gateways: *
- [x] System: Settings: Tunables
- [x] System: Trust: *
- [x] Interfaces: Wireless: Devices
- [x] Interfaces: Point-to-Point: Devices
- [x] Interfaces: Other Types: Bridge
- [x] Interfaces: Other Types: GIF
- [x] Interfaces: Other Types: GRE
- [x] Interfaces: Other Types: LAGG
- [x] Interfaces: Other Types: VLAN
- [ ] Firewall: Rules
- [ ] Firewall: NAT
- [x] Firewall: Groups
- [x] Firewall: Virtual IPs: Settings
- [x] VPN: IPsec: Pre-Shared Keys
- [x] VPN: OpenVPN: *
- [x] Services: Unbound DNS: Access Lists
- [x] Services: DynDNS
- [x] Services: RFC2136
- [x] Services: IGMP Proxy

**Pages with small "+"**

Change these to use fa-fw everywhere and btn-primary on add.

- [x] System: Routes: Configuration
- [x] System: Settings: Cron
- [x] System: Settings: Logging / targets
- [x] Interfaces: Other Types: Loopback
- [x] Interfaces: Other Types: VXLAN
- [x] Firewall: Aliases
- [x] Firewall: Shaper: *
- [x] VPN: IPsec: Tunnel Settings
- [x] VPN: IPsec: RSA Key Pairs
- [x] Services: Captive Portal: Administration
- [x] Services: Dnsmasq DNS: Settings
- [x] Services: DHCPv4: "interface"
- [x] Services: DHCPv6: "interface"
- [x] Services: Unbound DNS: Overrides

**Comment by fichtner** [comment]
At a quick glance we are talking about unification between old static pages (.php ending) and MVC endpoints.

Since MVC is the way to go and the only way the templates will pick up the correct style is to rewrite the static pages one by one in full (layout and feature, adding API, etc.) in full this will simply take a while longer. ;)


Cheers,
Franco

**Comment by JeGr** [comment]
Should consider to be re-opened as with

* Firewall: Categories

a new contender to the "cleanup" list already arrived and to coordinate the cleanup and unification it would be helpful to have a complete list and a plan how the UI should look like. :)

**Comment by AdSchellevis** [comment]
The new styling is rather simple, no need to keep issues open to know which pages haven't been converted to mvc. The new categories page is structured like all other mvc pages by my knowledge. (add/delete at the bottom of the grid)

**Comment by fichtner** [comment]
Whether people like it or not I will work on static pages to look like this and then we will discuss MVC adjustments:

<img width="1384" alt="Screenshot 2021-04-01 at 09 17 14" src="https://user-images.githubusercontent.com/1915288/113257610-23b4cd00-92cb-11eb-853e-b0fcc09ba18c.png">

That means we will likely remove most top right buttons, a.k.a. $main_buttons magic
