### ISSUE TITLE
Wireguard Configuration Sync Via backup/restore

### ISSUE THREAD

**Issue by tworth04** [opnsense/core#4220]
Adding a feature request for Wireguard to be added to the restore portion of the Config > Backup > restore from backup.

Can this be added as a single option for WG only rather then loading the full opnsense config for all items?

Thanks All!

**Comment by AdSchellevis** [comment]
The legacy export page won't be extended, from our vision if components (such as Wireguard) want to be able to support import/export functionality, it should be taken care from with the component/plugin. The partial import/export option currently available has no way to validate correctness of configuration data (and can lead to broken setups). 

The firewall alias module for example can be exported/imported from within the module.

**Comment by tworth04** [comment]
No worries. i mentioned this in the forums and was told to make a feature request as it wouldn't be difficult.  Sorry for the trouble

**Comment by mimugmail** [comment]
I'll add a sync button for HA as this was the feature you requested in the forums :)
