### ISSUE TITLE
Duplicate entry of IPv4 upstream gateway after changing [WAN] interface IP address

### ISSUE THREAD

**Issue by marcingarski** [opnsense/core#4224]
**Important notices**
[+] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[+] I have searched the existing issues and I'm convinced that mine is new.

**Describe the bug**
Setting new [WAN] interface IP address using virtual terminal cause duplicate entry of the same IPv4 upstream gateway under Interfaces -> [WAN]. Under System: Gateways: Single there is always one gateway visible.

**To Reproduce**
1. Using virtual terminal login on **root** account
2. Set interface IP address (2)
3. Go to Web GUI -> Interfaces -> [WAN]
4. Expand IPv4 upstream gateway list

**Expected behavior**
Only one gateway is visible

**Screenshots**
**Before** setting new WAN interface IP address

- Interfaces: [WAN]

![1](https://user-images.githubusercontent.com/37661097/88401610-3f75e400-cdca-11ea-9010-df800b45f933.png)

- System: Gateways: Single

![2](https://user-images.githubusercontent.com/37661097/88401629-443a9800-cdca-11ea-850c-5af3cdce03fa.png)
**After** setting new WAN interface IP address

- Interfaces: [WAN]

![3](https://user-images.githubusercontent.com/37661097/88401682-53b9e100-cdca-11ea-83d5-fbc57ae9e133.png)

- System: Gateways: Single

![4](https://user-images.githubusercontent.com/37661097/88401689-54eb0e00-cdca-11ea-9ece-09c427f6e9a8.png)

**Environment**
OPNsense 20.1.9-amd64

**Comment by Tetedeiench** [comment]
Encountered this today on OpnSense 20.7 - you also can't switch value (selecting another gets you the first one selected). Any update ?

**Comment by LordNullPointer** [comment]
I also have this issue but no solution for it. Is there any particular reason for that behavior? If you change the IP address again, you get 3 entries in that list.

I also noticed, that you can't change the WAN IP address manually when you also have to change the Upstream Gateway address? For example when you switch to a completely different subnet. You're forced to do this via CLI directly on the host. Maybe this problem has also something to do with the unchangeable Upstream Gateway address.
