### ISSUE TITLE
Aliases in Traffic Shaper Rules

### ISSUE THREAD

**Issue by MaartenJB** [opnsense/core#4226]
Hi,

I'm checking out the latest production version of OPNsense (OPNsense 20.1.7-amd64), and I notice I still can't use aliases. This would greatly enhance the usage of the shaper configuration. Setting up a shaper configuration for a slightly more advanced network is a pain a.t.m.

Link to feature
https://......../ui/trafficshaper#rules [then edit the rule]

Request:
Ability to use aliases in the shaper rules in the hosts/port fields

Is there any plan on implementing this feature?

Best regards,

Maarten

**Comment by MaartenJB** [comment]
Sorry guys, I'm trying to help here, don't know what I'm doing wrong to get an incomplete tag, I'll just close it as no one can be bothered to point me in the right direction.

**Comment by AdSchellevis** [comment]
@MaartenJB as described in https://github.com/opnsense/core/blob/master/CONTRIBUTING.md, the incomplete tag is assigned if our issue template isn't used.
