### ISSUE TITLE
netflix/stan chromecast not working on vanilla install

### ISSUE THREAD

**Issue by paladin0** [opnsense/core#4228]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[-] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
YES
[-] I have searched the existing issues and I'm convinced that mine is new.
YES

**Describe the bug**
A clear and concise description of what the bug is, including last known working version (if any).

Netflix/Stan and Chromecast is not working under a fresh vanilla opnsense install

I have just moved from an old pfsense version 1.2 install on a Soekris net 5501 box using a CF card as storage.
With the exact same network setup both the old pfsense image AND a factory standard ISP router work perfectly.

I have already put a post on the forum however it hasnt had any replies yet so i thought i would post here as it appears to be a bug given that its a new install with out of the box config

My setup is ISP Modem <> NET5501 <> Switch <> PC netflix works fine
                                                                              <> Google Wifi in bridge mode <> Android Tab and phone  (netflix/stand chromecast not working)
                                                                               <> ipad netflix works fine

It appears to be something specific with how android is working with opnsense as my ipad is fine.

we did view some of the logs and got blocks and after checking the data it was the akami servers which seems to be netflix content providers

*Tip*: to validate your setup was working with the previous version, use opnsense-revert (https://docs.opnsense.org/manual/opnsense_tools.html#opnsense-revert)

**To Reproduce**
1. Fresh install of opensense on net5501 or potentially any 32 bit device
2. vr0 LAN, VR1 WAN
3. wifi ap restart
4. launch netflix app and it fails

**Expected behavior**
Really plug and play just like the ipad appears to be

**Comment by fichtner** [comment]
I am not sure this is about 32 bit but FWIW 32 bit will no longer be maintained beyond 20.1.9 which came out next week.

**Comment by paladin0** [comment]
Im not 100% its about 32 bit. But we cant figure out why no one else has had this problem when all we did was the base install
