### ISSUE TITLE
Using logging targets, not able to write filter.log entries to external syslog server

### ISSUE THREAD

**Issue by greggitter** [opnsense/core#4229]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[-] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[-] I have searched the existing issues and I'm convinced that mine is new.

**Describe the bug**
Prior to logging targets and 20.7 RC1 I had set up a remote syslog server to capture firewall rules checked for logging (for debugging and security purposes).  This worked without issue.  Once logging targets were added, my legacy setup continued to work until installing 20.7 RC1.  Now that it no longer works I added via logging targets, choosing Application: Filterlog, Levels: Nothing selected, Facilities: Nothing selected...other fields are for the external syslog.  Logging targets work for other Applications (or when Nothing is selected here too)...but...firewall rules marked for logging are never captured.  Thus the syslog server is configured properly and verified to be communicating with OPNsense.

Looking in /var/log/filter.log, I can see the records same as in the Live Filter view.  I can't say when this first occurred as it was my first attempt at adding a logging target for this scenario.

I've removed the legacy configurations as mentioned [here](https://github.com/opnsense/core/issues/4060).
I also deleted all log files (not folders) in /var/log/* as mentioned in a post on the forums for a different but related issue with logging in general.  No affect.

1. Go to Logging Targets in Settings, add shown below.
2. Verify there are firewall rules with logging enabled and they are being triggered.
3. Verify they appear in Live View but then are not sent to external syslog.
4. No errors I've seen.

**Expected behavior**
Expect to see records show in external syslog files.

**Screenshots**
![image](https://user-images.githubusercontent.com/68356047/88800768-aacb0780-d176-11ea-9d51-6ca2b2061b51.png)

**Relevant log files**
None.

**Additional context**
None.

**Environment**
Software version used and hardware type if relevant.

OPNsense 20.7.r_13-amd64
FreeBSD 12.1-RELEASE-p7-HBSD
OpenSSL 1.1.1g 21 Apr 2020
HP 620T Plus/AMD GX-420CA/8GB/250GB SSD
HP NC365T 4-PORT

Note: This was also posted [in the forum](https://forum.opnsense.org/index.php?topic=18257.0), but no responses...it wasn't entirely clear how to report these issues...I'm assuming here is better.

**Comment by AdSchellevis** [comment]
https://github.com/opnsense/core/commit/629f7f8529764e4d6d6cc6d67a24055114ac224e + https://github.com/opnsense/core/commit/bc31d6c9fff7d6242ba8e568eb1eece46cdb274b should fix this, it's due to the switch to rfc5424 on FreeBSD 12.x (we missed a spot there)

**Comment by greggitter** [comment]
That fixed it.  Thanks.  👍
