### ISSUE TITLE
CloudFlare Dynamic DNS not functional

### ISSUE THREAD

**Issue by schrombomb** [opnsense/core#423]
It seems the code for CloudFlare in /usr/local/etc/inc/dyndns.class is outdated, resulting in failed updates. I found a patch someone made on the pfsense forums (https://forum.pfsense.org/index.php?topic=87436.msg534817#msg534817) and it got Dynamic DNS updates working like a charm on my 15.7.15 system. Perhaps something similar could be implemented into OPNSense?

**Comment by fichtner** [comment]
Thanks, I'll take it. :)
