### ISSUE TITLE
Multiple LDAP servers in System --> Access --> Server

### ISSUE THREAD

**Issue by websiteforstudents** [opnsense/core#4230]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[-] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

Yes

[-] I have searched the existing issues and I'm convinced that mine is new.

Yes

**Is your feature request related to a problem? Please describe.**

Not a problem, but feature request

**Describe the solution you'd like**
(e.g. I would like an input field in the `/ui/firewall/alias` which would add .... to ....)

When you go to System: Access: Server and try to add a new LDAP connection to authenticate for OpenVPN and other services, only a single IP address is allowed in the Hostname | IP address field.

Is it possible to add multiple addresses? In most LDAP environment, there are usually 2 servers.

**Describe alternatives you've considered**

I am currently using a single IP address to authenticate against Windows Active Directory server.

**Additional context**

**Comment by mimugmail** [comment]
You can do this via HAProxy: https://www.routerperformance.net/opnsense-bypass-ldaps-errors-via-haproxy/
HAProxy also has very good health checking so you can balance or failover for multiple DCs

**Comment by marcquark** [comment]
Shouldn't it be possible to add another authentication server to OPNSense, and basically mirror all settings except for the server name or IP? I'm playing around with the most recent release and it looks like it allows you to select multiple authentication sources for an OpenVPN server. So just tick them both and profit?

**Comment by websiteforstudents** [comment]
> Shouldn't it be possible to add another authentication server to OPNSense, and basically mirror all settings except for the server name or IP? I'm playing around with the most recent release and it looks like it allows you to select multiple authentication sources for an OpenVPN server. So just tick them both and profit?

This works. You can create multiple authentication server, then use all when setting up OpenVPN.
