### ISSUE TITLE
Boot screen issue with OPNsense 20.7 on APU4D4

### ISSUE THREAD

**Issue by fire-burner** [opnsense/core#4231]
Hi all,

i had recently switched my hardware from a low performance Fujitsu Futro S550-2 to an APU4D4.

When booting the installer the boot screen is shown properly and installation went fine.
The serial connection afterwards works fine for the whole boot process except the boot screen, which is totally distorted and so nothing can be selected:
                 H  ____________    __________    __________                                                
                 H//    ____ ___  ||//  ____    ||                                                
                 H||  ||    ||  ||  ||____//  ||  ||    ||  ||______    ______  __  ____    ______    _____ 
                 H||  ||    ||  ||    ______//||  ||    ||  //  ____||//  __  \\  ''__  \\//  ____||//  __ \
                 H||  ||____||  ||  ||        ||  ||    ||  \\____  \\    ____//  ||  ||  \\____  \\    ___/
                 H||__________//||__||        ||__||  //____||______//\\______||__||  ||__||______//\\_____|

 H++===================H===================H++=======================================@@@@@@@@@@@@@@@@@@@@@@@
 H||                                       H|| H@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
 H||HH..HBBoooott  MMuullttii  UUsseerr  [[EEnntteerr]]@@@                                        @@@@@@@@@@
 H||HH..HBBoooott  [[SS]]iinnggllee  UUsseerr| H        @@@@@@@@@@                        @@@@@@@@@@        
 13;HH..H[[EEsscc]]aappee  ttoo  llooaaddeerr  pprroommpptt@@@@@@@@@              @@@@@@@@@@@@@@@@@@@@@@
 H||HH..HRReebboooott                      H|| H            \\\\\\\\\\                  //////////          
 H||                                       H|| H))))))))))))))))))))))))              ((((((((((((((((((((((
 H||HOOppttiioonnss::                      H|| H            //////////                  \\\\\\\\\\          
 H||HH..H[[KK]]eerrnneell::  kkeerrnneell  ((11  ooff  22))@@@@@@@@@@@@@              @@@@@@@@@@@@@@@@@@@@@@
 H||HH..HCCoonnffiigguurO]]ppttiioonnss......| H        @@@@@@@@@@                        @@@@@@@@@@        
 H||                                       H|| H@@@@@@@@@@                                        @@@@@@@@@@
 H||                                       H|| H@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
 H||                                       H|| H@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@    
 H++=======================================H++==========================                                    
   H                                                                              aarryy  LLiioonn''''      

 /bboooo]] /kssiizzee==00xx11000000 aattaa==00xx11ee33442ssyymmss==[[00xx88++00xx8188ee99ee88|| 
8++00xx11aaccee9922// 
 /bboooott//kkeerrnneell//ccaarrpp..kkoo  ssiizzee  00xx1100225500  aatt  00xx226688ff000000 

 /bboooott//kkeerrnneell//iiff__bbrriiddggee..kkoo  ssiizzee  00xxff999988  aatt  00xx2266aa00000000 

 looaaddiinngg  rreeqquuiirreedd  mmoodduullee  ''bbrriiddggeessttpp'' 
                  ssiizzee  00xx558822ff00  aat0  00xx2266ee77000000 0000 
 /bboooott//kkeerrnneell//bbrriiddggeessttpp..kkoo  ssiizzee  00xx7722aa88  aatt  00xx2266bb00000000 
 Boooottiinngg...... ell//ppfflloogg..kkoo  ssiizzee  00xx22aaff88  aatt  00xx22774400000000 
 /bboooott//kkeerrnneell//iiff__eenncc..kkoo  ssiizzee  00xx33ee7788  aatt  00xx2266bb88000000 
KDB: debugger backends: ddbpffssyynncc..kkoo  ssiizzee  00xxeebbdd00  aatt  00xx22774433000000
KDB: current backend: ddb/iiff__ggrree..kkoo  //

Afterwards everything is printed normally:
---<<BOOT>>---
Copyright (c) 2013-2019 The HardenedBSD Project.
Copyright (c) 1992-2019 The FreeBSD Project.
Copyright (c) 1979, 1980, 1983, 1986, 1988, 1989, 1991, 1992, 1993, 1994
        The Regents of the University of California. All rights reserved.
FreeBSD is a registered trademark of The FreeBSD Foundation.
FreeBSD 12.1-RELEASE-p7-HBSD #0  427d53bc125(stable/20.7)-dirty: Sun Jul 26 05:51:42 CEST 2020
    root@sensey64:/usr/obj/usr/src/amd64.amd64/sys/SMP amd64
FreeBSD clang version 8.0.1 (tags/RELEASE_801/final 366581) (based on LLVM 8.0.1)
VT(vga): resolution 640x480
HardenedBSD: initialize and check features (__HardenedBSD_version 1200059 __FreeBSD_version 1201000).
CPU: AMD GX-412TC SOC                                (998.15-MHz K8-class CPU)

The issue was also there with 20.1.x (the first version I had installed)
I use 115200 baud (with picocom from Linux via a serial - USB adapter)

my setup:
OPNsense 20.7-amd64FreeBSD 12.1-RELEASE-p7-HBSDLibreSSL 3.0.2
PC Engines APU4D4
AMD GX-412TC

![Screenshot_20200731_123131](https://user-images.githubusercontent.com/24722229/89027099-346f0680-d32a-11ea-93ab-b59dfc28a74c.jpeg)

**Comment by fichtner** [comment]
I think this is a BIOS issue "xx" character sequence means bold font...

**Comment by fire-burner** [comment]
I am running the newest available Coreboot v4.12.0.2

**Comment by TheNec** [comment]
Hello,

I am not 100% sure but I think I had a quite similar problem some months ago with an (older) apu and a headless debian installation. The problem was the text encoding of the (windows) terminal software. After switching from Tera Term (which has many options that can screw such things up) to PuTTY the problem was gone and I don't really known what the problem was but I didn't really care afterwards. You should try another terminal software or check the settings =)

Kind regards!

btw. Harry Lion is great^^

**Comment by fire-burner** [comment]
I just tested with Putty from Windows and I can see the same distorted screen output

**Comment by ddragic** [comment]
It's been a while since I installed opnsense on APU2, but I think this is the text console redirect (to serial) feature of the apu bios. As can be seen all the characters are printed twice, probably because the boot loader is using both the vga/text console and serial console.

I think it's possible to either disable this in the bios or configure the boot loader to only output to serial.

**Comment by TheNec** [comment]
I don't have OPNsense installed directly on my APU but with Proxmox the Boot Screen works without problems =)

My BIOS (version v4.11.0.3) console settings are:
  t Serial console - Currently Enabled
  k Redirect console output to COM2 - Currently Disabled

You may try that and if that doesn't work for you then maybe it's a BIOS Problem as Franco suggested. Then you may downgrade the BIOS and check if it works after that.

**Comment by fire-burner** [comment]
I had opened an issue on the pcengines side, but it looks like the serial https://github.com/pcengines/coreboot/issues/464
According to them, serial should be set to "-S115200 -h" in /boot.config.
Unfortunately this settings is not persistent in OPNsense.

But I also realized, that VGA was set as default console in my OPNsense.
So after setting the serial port as default and disabling the second console, the boot menu is shown correctly.
Only the boot line before the menu is still distorted.

So that might then be connected to the console setting of -D instead of -h?

**Comment by fichtner** [comment]
Ok, we can try forcing -h on serial as primary console in configuration.

**Comment by fire-burner** [comment]
Thanks Franco

**Comment by fichtner** [comment]
@fire-burner thank you for the qualified follow-up!

**Comment by fichtner** [comment]
PS: just needs testing, but I expect it to land in 21.1.4 and the new images for 21.7 will have it as well.
