### ISSUE TITLE
Using logging targets, but no log traffic leaves the pfsense

### ISSUE THREAD

**Issue by new-gen23** [opnsense/core#4233]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:
[-] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
[-] I have searched the existing issues and I'm convinced that mine is new.

**Describe the bug**
A clear and concise description of what the bug is, including last known working version (if any).

**To Reproduce**
1. I upgraded to 20.7
2. Goto  System -> settings -> logging targets
3. Added Logging rule as can been seen in the screenshot.
4. Started tcpdump on opensense and destination on port 1514. Nothing goes through. 

**Expected behavior**
Should see traffic at target logstash, but nothing leaves the pfsense. Checked firewall but nothing is blocking. Ping also goes through to the log target.

**Screenshots**
![rules](https://user-images.githubusercontent.com/1741662/89101839-065df500-d404-11ea-9444-9476bac132b2.jpg)

**Environment**
Software version used and hardware type if relevant.
e.g.:
![version](https://user-images.githubusercontent.com/1741662/89101832-f80fd900-d403-11ea-9a39-8ff19fb45980.jpg)

Are you sure,issue https://github.com/opnsense/core/issues/4229 was solved?

**Comment by AdSchellevis** [comment]
pfsense??? but yes, issue was resolved according to https://github.com/opnsense/core/issues/4229#issuecomment-665651582 likely a filter issue, always try to capture more data first to test the concept and filter accordingly next. Chances are that both applications don't emit authorisation messages for example (or not that frequent)

**Comment by new-gen23** [comment]
Switching to TCP seems to have solved the problem. Thats sufficient for me. Still no idea why UDP did not output anything.

**Comment by AdSchellevis** [comment]
no problem, let's consider this issue closed then.
