### ISSUE TITLE
Firewal Rule Configuration partially ignored

### ISSUE THREAD

**Issue by new-gen23** [opnsense/core#4237]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[x] I have searched the existing issues and I'm convinced that mine is new.

**Describe the bug**
I want to block all DNS traffic on port 53 and allow only DNS resolving on the unbound dns running on the firewall. However, whenever I try to block only port 53 or allow port 53, the frontend ignores it and stores a wildcard.

**To Reproduce**
1. Go to 'Firewall' -> Rules -> igb0
2. Click on 'add rule'
3.Create a  rule to allow dns to this firewall on port 53
Action: Pass
Disable: false
Interface: igb0
Direction: in
TCP/IP Version: IPv4
Protocol: UDP
Source :any
Destination: This firewall
Destination port range: from any
Destination port range: to (other) 53
Rest left as default
4. Click save
5. (optionally, click apply changes if you trust what is displayed)

**Expected behavior**
Now, the overview should show the rule with destination port 53. However, the port is marked with a wildcard (*)

**Screenshots**
![fw_rule](https://user-images.githubusercontent.com/1741662/89132479-bf135980-d514-11ea-9d83-1768fee42c8a.jpeg)
![fw_rule2](https://user-images.githubusercontent.com/1741662/89132537-3648ed80-d515-11ea-84e2-71f9e88354ff.jpeg)
"pfctl -sr | grep igb0 | grep 53" shows also with port 53 destination. 

**Environment**
Software version 20.7 (installed)

FreeBSD fw.localdomain 12.1-RELEASE-p7-HBSD FreeBSD 12.1-RELEASE-p7-HBSD #0  427d53bc125(stable/20.7)-dirty: Sun Jul 26 05:51:42 CEST 2020     root@sensey64:/usr/obj/usr/src/amd64.amd64/sys/SMP  amd64

**Comment by mimugmail** [comment]
Destination port DNS or range starting AND ending with 53.

**Comment by new-gen23** [comment]
I followed your advice and it seems to create the right rule. Thank you for the clarification.
