### ISSUE TITLE
filter_update dies with large blocklists

### ISSUE THREAD

**Issue by waffshappen** [opnsense/core#4239]
**Important notices**

[X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[X] I have searched the existing issues and I'm convinced that mine is new.

**Describe the bug**
Importing the FireHOL blocklists into the alias tables will cause a python process to spawn to update them. If these lists are sufficiently large (WIRED memory on my instance was ~2GB for all of them it seems, not sure) then during the update it will crash. The crash will consume all system resources for a moment and pause all connections for 8-10 seconds then the system will resume, and respawn the updater process soon after causing an endless loop of failed updates. 

This was - somehow - working with no issues on 20.1, and while i agree the blocklists are huge they should not cause a failure on a  5GB vm  with 1.5GB free, ~2 needed for the lists (all memory the process and blocklists use(s|d) is marked as WIRED). Or atleast the alias updater should wait much longer between attempts.

**To Reproduce**
1. Add a lot of FireHOL blocklists
https://iplists.firehol.org/?ipset=firehol_abusers_30d
https://iplists.firehol.org/?ipset=firehol_level4
etc.
2. Wait for the alias updater to spawn
3. Observe crash and degraded performance over and over and over

**Expected behavior**
Lists should be updated swappable and only fetched, then processed, one by one and no idea but i have to say i have no idea how the in-memory final replacement works. But it should be able to support blocklist updates without running out of memory on a 5GB ram vm (800MB idle used without blocklists right now).
Or atleast if it crashes it shouldn't try again and again and essentially kill connectivty for it.

**Environment**

OPNsense 20.7 (amd64, OpenSSL).
Qemu VM, 5GB ram, 4 cores

**Comment by OliverO2** [comment]
You have probably run into the problem that `pfctl -T replace` updates a maximum of 32768 address table entries with the OPNsense default configuration: [bugs.freebsd.org – 235754 – pfctl: Lower limit for \-T replace than \-T add](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=235754)

Try this:
1. In the Web UI navigate to _System: Settings: Tunables_.
1. Click _Add_.
1. Fill in fields as follows:
    * Tunable: `net.pf.request_maxcount`
    * Description:
        ```
        Maximum number of pf address table entries to change per call. NOTE: pfctl -T replace will use only half the number.
        ```
    * Value: `131070`
1. Save.
1. Apply.
1. Reload your block lists.
