### ISSUE TITLE
LAN and OPT interface bytes in/out & packets in/out statistics are backwards

### ISSUE THREAD

**Issue by bsd-source** [opnsense/core#4241]
[X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[X] I have searched the existing issues and I'm convinced that mine is new.

**Describe the bug**
LAN and OPT interface statistics for Packets In and Packets Out as well as Bytes In and Bytes Out are backwards.

**To Reproduce**
1. Go to Interfaces --> Overview in webgui
2. Click on LAN or any OPT interface
3. You should see that In/out packets are backwards
4. Note: WAN interface does not have this issue.

**To Reproduce**
1. Add Interface Statistics widget to Dashboard
2. You should see that Packets In/Packets out and Bytes In/Bytes Out are backwards for LAN or OPT interfaces
3. Note: WAN interface does not have this issue

**Expected behavior**
Packets in/out as well as bytes in/out should be accurate for both the webgui Dashboard Interface Statistics widget and Interfaces --> Overview section.

**Additional Note**
I just recently installed OPNsense 20.7 from a downloaded image. I did not upgrade to 20.7 from my previous 20.1 setup. I don't know if 20.1 has the same issue.

**Environment**
OPNsense 20.7-amd64
FreeBSD 12.1-RELEASE-p7-HBSD
OpenSSL 1.1.1g 21 Apr 2020

Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz (4 cores)
Onboard LAN: 6 x Intel I211-AT Gigabit LAN

![1](https://user-images.githubusercontent.com/1825683/89213224-9f624c80-d579-11ea-8f7a-be7dadb6a872.jpg)
![2](https://user-images.githubusercontent.com/1825683/89213237-a25d3d00-d579-11ea-8828-1657104f578b.jpg)

**Comment by AdSchellevis** [comment]
In on WAN out on LAN looks quite normal, why do you think they're in reverse?

**Comment by bsd-source** [comment]
34.24 GB in on the WAN and 28.09 GB out on the LAN. I was under the impression the "in" would be downloading and "out" would be uploading. I'm actualy downloading a considerable amount more info compared to the amount I'm uploading. I'm streaming in movies from Hulu.

**Comment by AdSchellevis** [comment]
exactly my point, you're downloading 32GB from WAN, which goes out to clients on LAN and OPT.

**Comment by bsd-source** [comment]
Obviously I misundertsood the readings. I expected the LAN to have bytes in similar to the WAN.
