### ISSUE TITLE
Exception: Error at /usr/local/opnsense/mvc/app/models/OPNsense/Base/Menu/MenuSystem.php:274

### ISSUE THREAD

**Issue by soleilblanc99** [opnsense/core#4243]
Since the upgrade to 20.7 (from latest 20.1) I'm receiving the following error (at the /index.php url)

![image](https://user-images.githubusercontent.com/43672060/89362682-7a1a2f00-d69c-11ea-9418-b8089a876643.png)

`[04-Aug-2020 21:39:29 America/Toronto] Exception: Error at /usr/local/opnsense/mvc/app/models/OPNsense/Base/Menu/MenuSystem.php:274 - Undefined index: enc0 (errno=8) in /usr/local/opnsense/mvc/app/controllers/OPNsense/Base/ApiControllerBase.php:87
Stack trace:
#0 /usr/local/opnsense/mvc/app/models/OPNsense/Base/Menu/MenuSystem.php(274): OPNsense\Base\ApiControllerBase->APIErrorHandler(8, 'Undefined index...', '/usr/local/opns...', 274, Array)
#1 /usr/local/opnsense/mvc/app/controllers/OPNsense/Core/Api/MenuController.php(105): OPNsense\Base\Menu\MenuSystem->__construct()
#2 /usr/local/opnsense/mvc/app/controllers/OPNsense/Core/Api/MenuController.php(185): OPNsense\Core\Api\MenuController->getMenu(NULL)
#3 [internal function]: OPNsense\Core\Api\MenuController->searchAction()
#4 [internal function]: Phalcon\Dispatcher->callActionMethod(Object(OPNsense\Core\Api\MenuController), 'searchAction', Array)
#5 [internal function]: Phalcon\Dispatcher->dispatch()
#6 /usr/local/opnsense/www/api.php(26): Phalcon\Mvc\Application->handle()
#7 {main}`

Config was working correctly in previous version.  This error happen everytime i log on the firewall but does not seem to be causing other problems.

Here's the system information
`User-Agent Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:79.0) Gecko/20100101 Firefox/79.0
FreeBSD 12.1-RELEASE-p7-HBSD #0  427d53bc125(stable/20.7)-dirty: Sun Jul 26 05:51:42 CEST 2020     root@sensey64:/usr/obj/usr/src/amd64.amd64/sys/SMP amd64
OPNsense 20.7 3526fcaac
Plugins os-dmidecode-1.1 os-dyndns-1.22 os-intrusion-detection-content-snort-vrt-1.1 os-lldpd-1.1 os-mdns-repeater-1.0 os-ntopng-1.2 os-redis-1.1 os-sensei-1.5.2_1 os-sensei-updater-1.5.1 os-smart-2.1 os-sunnyvalley-1.2 os-theme-cicada-1.24 os-zabbix-agent-1.7 
Time Tue, 04 Aug 2020 21:39:30 -0400
OpenSSL 1.1.1g  21 Apr 2020
PHP 7.3.20`

Hardware:
`Intel(R) Pentium(R) CPU G4560 @ 3.50GHz (4 cores)', Shuttle DH-110, 8GB RAM, 500GB ssd`

Let me know what testing or log files are required.  I've used the submit report option from the UI as well.

Thank you

**Comment by vikashpatel2980263-coder** [comment]
{ "errorMessage": "/usr/local/opnsense/mvc/app/controllers/OPNsense/Firewall/Api/RulesController.php:337: Class \"OPNsense\\Core\\UUID\" not found", "errorTrace": "#0 [internal function]: OPNsense\\Firewall\\Api\\RulesController->addRuleAction()\n#1 [internal function]: Phalcon\\Dispatcher\\AbstractDispatcher->callActionMethod(Object(OPNsense\\Firewall\\Api\\RulesController), 'addRuleAction', Array)\n#2 [internal function]: Phalcon\\Dispatcher\\AbstractDispatcher->dispatch()\n#3 /usr/local/opnsense/www/api.php(24): Phalcon\\Mvc\\Application->handle('/api/firewall/r...')\n#4 {main}", "errorTitle": "An API exception occurred" }

**Comment by fichtner** [comment]
Maybe it's just me. I cannot find the file that produces the error?

    # ls /usr/local/opnsense/mvc/app/controllers/OPNsense/Firewall/Api/RulesController.php
    ls: /usr/local/opnsense/mvc/app/controllers/OPNsense/Firewall/Api/RulesController.php: No such file or directory

Please provide context and/or open a new ticked when you are sure we can help you with a file we do maintain.


Cheers,
Franco
