### ISSUE TITLE
Multicast is badly broken on FreeBSD 12.x need to update kernel to fix it

### ISSUE THREAD

**Issue by RyuunoAelia** [opnsense/core#4249]
**Describe the bug**
A Kernel Bug create issues with multicast, mainly interfaces never leaving multicast groups.
A bugfix is already present in upstream FreeBSD 12 STABLE  https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=246629 please include this fix into opnsense kernel.

**To Reproduce**
Use a program that will register to a multicast group (example is igmpproxy), and see that the group is never left.

**Expected behavior**
The multicast group should be left at least when the program is terminated.

**Additional context**
The bug is fixed upstream.

**Environment**
any opnsense version using FreeBSD 12 on any hardware.

**Comment by AdSchellevis** [comment]
https://github.com/opnsense/src/commit/d6dc01f471b47c7967f44e9ce6d47a6f8682ca6f

**Comment by RyuunoAelia** [comment]
well you have the code, but when will this be released ?
