### ISSUE TITLE
jQuery 3.4.1 is causing our PCI audit scan to fail, but it's not even used

### ISSUE THREAD

**Issue by violuke** [opnsense/core#4250]
**Describe the bug**
We use SecurityMetrics for our PCI compliance scanning. They don't like jQuery < 3.5.0 due to XSS issues. Please see screenshot:
<img width="1150" alt="Screenshot 2020-08-10 at 10 37 52 am" src="https://user-images.githubusercontent.com/6420347/89769817-bcf16200-daf5-11ea-8d0f-2885ba281d87.png">

I know that jQuery was upgraded to 3.5.1 in 23729215e4aaefa46a6019c0698cfb74ce0c04f6 (which is great) but although the HTML no longer points to jQuery 3.4.1, the security scanner still knows it's there and expects it to be removed. I realise that 3.4.1 was left in to ensure a smooth upgrade, but can this now be removed completely? Thank you.

**Environment**
OPNsense 20.7-amd64
FreeBSD 12.1-RELEASE-p7-HBSD
OpenSSL 1.1.1g 21 Apr 2020

**Comment by AdSchellevis** [comment]
Some external templates still rely on it, so it will likely stay for at least a couple of months. Probably best to add an exclusion for it in your regular scan.

**Comment by violuke** [comment]
👍 Thanks. I'll request this exception and hopefully they'll be ok with it.

**Comment by violuke** [comment]
Sorry for not investigating properly before. It looks like 3.4.1 is still in use on the main login screen and was missed during the upgrade to 3.5.1, see https://github.com/opnsense/core/blob/b62ba739680ce05cac7794a957669a05bda18bc5/src/etc/inc/authgui.inc#L337

Can this be updated and a patch release made ASAP to help us (and presumably others) pass our security scans? Thanks.

**Comment by AdSchellevis** [comment]
@violuke nice catch, we'll schedule a fix for a next release, probably 20.7.1.

**Comment by L1ghtn1ng** [comment]
@violuke you can use the opnsense-patch <commit hash> which will patch your system so you can pass the scan
