### ISSUE TITLE
Multiple notices: [ There were error(s) loading the rules: /tmp/rules.debug:18: syntax error - The line in question reads [18]: table   persist   ]

### ISSUE THREAD

**Issue by DoogeJ** [opnsense/core#4251]
I have read the contributing guide lines.
I have searched the existing issues and I'm convinced that mine is new.

**Describe the bug**
I get a lot of these 'unread notices':

[ There were error(s) loading the rules: /tmp/rules.debug:18: syntax error - The line in question reads [18]: table   persist   ]
I'm not sure what to do with this. I tried three fresh installations, didn't manually change any config files.

Similar messages can be found in the General log:

opnsense[87408]: /usr/local/etc/rc.filter_configure: There were error(s) loading the rules: /tmp/rules.debug:16: syntax error - The line in question reads [16]: table <file> persist

opnsense[8788]: /usr/local/etc/rc.filter_configure: There were error(s) loading the rules: /tmp/rules.debug:16: syntax error - The line in question reads [16]: table <file> persist

**Screenshots**
https://i.imgur.com/eMynhDr.png

**Environment**
OPNsense 20.7-amd64
Windows Server 2019 with Hyper-V
DVD iso installation source

**Comment by AdSchellevis** [comment]
What does line 18 of the file state? (open  /tmp/rules.debug in a console using `vi` or `less`), it's quite unlikely a clean install causes this, are you sure you didn't import a config file from somewhere else? (pfSense, m0n0wall)

**Comment by DoogeJ** [comment]
@AdSchellevis 
Not importing a file, 100% clean install - added a single port forwarding rule but the error existed before that.
Line 18 states "table <bogons>  persist"

Attached is the complete file.
[rules.debug.txt](https://github.com/opnsense/core/files/5062592/rules.debug.txt)

**Comment by AdSchellevis** [comment]
created an alias named "file"?

```
table <file>  persist  
file = "<file>"
```

It's a reserved word, which probably skips our validation.

**Comment by DoogeJ** [comment]
> created an alias named "file"?
> 
> ```
> table <file>  persist  
> file = "<file>"
> ```
> 
> It's a reserved word, which probably skips our validation.

Ah yes.. My file server; LOL. Thanks! I'm going to try this.
