### ISSUE TITLE
Logs do not show new entries after updating to 20.7

### ISSUE THREAD

**Issue by ahaase-c4u** [opnsense/core#4252]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[x] I have searched the existing issues and I'm convinced that mine is new.

**Describe the bug**
On our opnsense we use local logging. In 20.1.x it was possible to show log entries regarding dhcp requests and log rules. Now after updating to 20.7, there are no new entries displayed. DHCP works, firewalling too. But the log entries are missing. We do not use log servers, and of course we didn't disable local logging.

**To Reproduce**
1. Go to 'Services' - 'DHCPv4' 
2. Click on 'Log file'
3. See error. 'No results found!'

Another chance to see the problem:
1. Go to 'System' - 'Log Files'
2. Click on 'Backend' or 'Web GUI'
3. See error. Logs are empty. Clicking on 'General' recent log entries are displayed.

And last, but not least:
1. Go to 'Firewall' - 'Log Files'
2. Click on 'Live View'
3. See error. No entries get displayed, but the firewall is used normally. So there should be records.

**Expected behavior**
Displaying logs should be possible as in version 20.1.x

**Environment**
Software version used and hardware type if relevant.

OPNsense 20.7-amd64
FreeBSD 12.1-RELEASE-p7-HBSD
OpenSSL 1.1.1g 21 Apr 2020

**Comment by AdSchellevis** [comment]
syslog-ng not running? can you try https://github.com/opnsense/core/commit/2784956853f43a61ed9c97e27dd38f95cd818671 and reboot? (`opnsense-patch 2784956` from the console)

**Comment by ahaase-c4u** [comment]
Doing so, all works fine again. Thank you for your help :-)

**Comment by ahaase-c4u** [comment]
Sorry to say, but the problem reoccured. I see log entries from 4:45pm, but no one after that. So loggings seems to do not work again.

**Comment by ahaase-c4u** [comment]
Checking this some more in detail, I saw that there is no process syslog-ng running on my firewall. Additionally looking into /etc/rc.conf.d/syslog_ng, I see:

syslog_ng_enable="YES"
syslog_ng_pid="/var/run/syslog-ng.pid"
syslog_ng_skip="YES"

Is "enable" and "skip" correct?

**Comment by AdSchellevis** [comment]
@ahaase-c4u yes it is, it shouldn't try to start it during normal rc startup, which is what the `syslog_ng_skip` is doing. syslog-ng seems to be quite sensitive, mostly on the legacy hook to pass events to the legacy syslog. If you don't need clog (not using an embedded device and a bit of free storage available), you can also disable legacy logging, in which case the issue is likely gone.

**Comment by ahaase-c4u** [comment]
It's a DEC2630 with 100g free disk space, so I'll give it a try. All I have to do is checking "Disable circular logs" in 'System' -> 'Settings' -> 'Logging'?

**Comment by AdSchellevis** [comment]
yep, that's all., best reset the logs afterwards to cleanup old ones.

**Comment by ahaase-c4u** [comment]
Seems not to help. Now I have subdirectories in /var/log for filter, dhcp, system and so on. But the logs only contain entries in a time range of 5 seconds and then nothing is being logged.

**Comment by AdSchellevis** [comment]
ok, that sounds odd, syslog-ng still crashing?

**Comment by ahaase-c4u** [comment]
I don't find another hint for a crashing syslogd. But after a reboot some minutes ago, no syslogd is running. Processlist only shows:

root@gw02-che:~ # ps auxw | grep log
root   21335   0.0  0.3 1144408 12228  -  Is   20:24    0:09.48 /usr/local/libexec/ipsec/charon --use-syslog
root   33949   0.0  0.1 1061692  3236  -  Ss   20:31    0:00.07 /usr/local/sbin/filterlog -i pflog0 -p /var/run/filterlog.pid
root   15734   0.0  0.1 1061116  3156  0  S+   20:32    0:00.00 grep log
root@gw02-che:~ #

**Comment by AdSchellevis** [comment]
what happens if you start syslog-ng manually? 

```
service syslog-ng start
```

**Comment by ahaase-c4u** [comment]
Now after starting syslog-ng once by "service syslog-ng start" I see the following processlist:

root@gw02-che:~ # ps auxw | grep syslog
root   21335   0.0  0.3 1144428 12256  -  Is   20:24    0:09.50 /usr/local/libexec/ipsec/charon --use-syslog
root   34109   0.0  0.2   19300  7664  -  I    20:33    0:00.00 /usr/local/sbin/syslog-ng -p /var/run/syslog-ng.pid
root   56479   0.0  0.3   26484 10684  -  Ss   20:33    0:00.14 /usr/local/sbin/syslog-ng -p /var/run/syslog-ng.pid
root   88271   0.0  0.3   21076 11208  -  S    20:33    0:00.19 /usr/local/bin/python3 /usr/local/opnsense/scripts/syslog/lockout_handler (python3.7)
root   63569   0.0  0.1 1061144  3164  0  S+   20:34    0:00.00 grep syslog
root@gw02-che:~ # 

Firewall-Log seems normal and shows denied packets and some permitted. So manual start seems to do the trick until next reboot or whatever.

**Comment by AdSchellevis** [comment]
what does dmesg show?

**Comment by ahaase-c4u** [comment]
There is the hint for the crashing syslog-ng:

root@gw02-che:~ # dmesg | grep log
  AMD Features2=0x154037ff<LAHF,CMP,SVM,ExtAPIC,CR8,ABM,SSE4A,MAS,Prefetch,OSVW,IBS,SKINIT,WDT,Topology,PNXC,DBE,PL2I>
pid 93641 (syslog-ng), jid 0, uid 0: exited on signal 11 (core dumped)
pflog0: promiscuous mode enabled
pflog0: promiscuous mode disabled
pflog0: promiscuous mode enabled
**pid 60579 (syslog-ng), jid 0, uid 0: exited on signal 11 (core dumped)**
ipfw2 (+ipv6) initialized, divert loadable, nat loadable, default to accept, logging disabled
pflog0: promiscuous mode disabled
pflog0: promiscuous mode enabled
root@gw02-che:~ #

**Comment by AdSchellevis** [comment]
Unfortunately I can't reproduce this easily, but something seems off. Are you using any remote logging by the way?

**Comment by ahaase-c4u** [comment]
No, not on this device. Does it make sense in case, the syslog dies? I can configure some remote logging, if it helps.

**Comment by AdSchellevis** [comment]
shouldn't be necessary, so far I've only seem similar unstable behaviour when sending messages to the other syslog daemon (using it's domain socket). Just to be sure, can you try upgrading to todays release and see if that makes a difference? (I expect you're still on 20.7)

**Comment by ahaase-c4u** [comment]
Yes, there's been still 20.7 on the device. Update to 20.7.1 succeeded and after reboot syslog-ng is running normally. Live log is showing recent data. I'll keep an eye on it until tomorrow and close the issue, if the problem does not come back.

Thank you for your help.

**Comment by AdSchellevis** [comment]
your welcome, thank you for the feedback

**Comment by ahaase-c4u** [comment]
After update and running for one night, all seems pretty fine. In case, there come back any problems, I'll let you know.
