### ISSUE TITLE
FIDO2 Webauthn Passwordless Authentification

### ISSUE THREAD

**Issue by danielferster** [opnsense/core#4254]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[X] I have searched the existing issues and I'm convinced that mine is new.

**Is your feature request related to a problem? Please describe.**

Hey there!
Since FIDO2 and Webauthn is now official released and widely supported on all platforms (Windows, Android, Linux, iOS, macOS) and nearly all browsers (Chrome, Firefox, Safari) it would be very cool to implement this future technology to prevent a growing number of passwords for all the different services in our life’s.

**Describe the solution you'd like**
Webauthn is well documented and would be easy to implement for authentification. For example Nextcloud also managed to implement it - it’s opensource so have a look at it.

https://nextcloud.com/blog/nextcloud-hub-brings-productivity-to-home-office/
https://github.com/duo-labs/webauthn
https://github.com/w3c/webauthn

**Comment by JulienFloris** [comment]
Any update on this feature request, or is this wrong place to ask?

**Comment by AdSchellevis** [comment]
it's labelled "help wanted" and closed due to inactivity, I don't expect this to gain traction soon unless someone is willing to spend enough time on it (in which case we can reopen and assign the ticket)
