### ISSUE TITLE
Opnsense stop working after vmware snapshot,need to reboot

### ISSUE THREAD

**Issue by Maurotb** [opnsense/core#4256]
**Describe the bug**
If i make a snapshot (states+disk+memory) of opnsense  
my network card stop working (my ping is 1-3 secs)
Randomly on wan, lan or both
If i make only disk snapshot, i have not any issue
I have try to disable all offload, same result.
CPU and interrupt is ok during problem
To resolve i need to reboot opnsense

1. On vmware make a state vm snapshot
2. wait some seconds
3. opnsense not responding on some interface
4. ping interface result 1-3 secs latency

**Environment**
OPNsense 20.7-amd64
esxi 7.0 , vcenter 7.0
vmxnet3 network card

**Comment by fichtner** [comment]
This is appropriate for the forum as was already discussed there. If you want this fixed look at raising tickets for VMware or FreeBSD although chances are probably low that things are going to change.
