### ISSUE TITLE
haproxy widget

### ISSUE THREAD

**Issue by Lebernd** [opnsense/core#4259]
**Is your feature request related to a problem? Please describe.**
Using haproxy to serve websites - I have no option to monitor connection basics in the lobby.

**Describe the solution you'd like**
A simple overview of the current connections would be great.
- Health of backends
- Connections to frontends/public service (up to a certain number)

**Describe alternatives you've considered**
A second browser-tab with the haproxy stats.

**Comment by AdSchellevis** [comment]
@Lebernd would you be so kind to open requests in the correct repo? I've just moved you other question to plugin, haproxy isn't part of core either.....

**Comment by Lebernd** [comment]
@AdSchellevis sorry - of course.
