### ISSUE TITLE
Live view broken after upgrading to 20.7.1

### ISSUE THREAD

**Issue by hmr-it-jr** [opnsense/core#4262]
After upgrading to OPNsense 20.7.1 the live view is completely broken. It's not updating anymore.

Happens both for the widget on the bashboard and for the advanced live view in Firewall -> Log Files ->Live View

There is now live view anymore it's just showing like 10 entries after reboot and then it's frozen.

**Comment by fichtner** [comment]
Please take a look at our contribution guide, the issue template and using the template to find issues similar to yours. I can say with 100% certainty: they exist and most have been resolved.
