### ISSUE TITLE
filter/update_tables.py fails silently, discarding error output from pfctl

### ISSUE THREAD

**Issue by OliverO2** [opnsense/core#4266]
* [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
* [x] I have searched the existing issues and I'm convinced that mine is new.

**Describe the bug**

`/usr/local/opnsense/scripts/filter/update_tables.py` fails silently, for example when trying to handle a blocklist of more than 32768 entries (see #4239). There is no error message when invoking the table update from the Web UI (by applying an alias change). No output appears in the log.

**Additional context**

`update_tables.py` contains several invocations of `subprocess.run` with `capture_output=True`. [The doc](https://docs.python.org/3/library/subprocess.html) says this means `stdout` and `stderr` will be captured separately. However, `update_tables.py` does not pick up any `stderr` output.

I'd suggest to either
* change `capture_output=True` to `stdout=subprocess.PIPE, stderr=subprocess.STDOUT`, or
* handle `stderr` output

on each invocation.

**Environment**

OPNsense 20.7

**Comment by AdSchellevis** [comment]
This worked before, it should reflect the error to the user when there isn't enough memory for example. This looks like a typo here https://github.com/opnsense/core/blob/ce2b145185aed9a9306380a46f773d211623df45/src/opnsense/scripts/filter/update_tables.py#L163-L172 introduced in https://github.com/opnsense/core/commit/867856733bdb17268adfb405aee26d779df35cd4

stdout should have been stderr. 

Thanks for reporting, I'll close the issue with the commit fixing it.

**Comment by OliverO2** [comment]
I see. If `stdout` is being ignored intentionally, it could be made clear (and avoids a pipe resource) by specifying `stdout=subprocess.DEVNULL, stderr=subprocess.PIPE`.

Note that the other `pfctl` calls (`-T show` and `-T kill`) could still fail silently.

**Comment by AdSchellevis** [comment]
I know, but these are less crucial in general, we can send output to the log, but in this case probably wouldn't really help. The configuration error (not enough memory) happens quite often which is the situation 99% of the users trip into.

About the stdout / stderr, that's just how it's supposed to work according to the docs:

> If capture_output is true, stdout and stderr will be captured. When used, the internal Popen object is automatically created with stdout=PIPE and stderr=PIPE. The stdout and stderr arguments may not be supplied at the same time as capture_output.

**Comment by OliverO2** [comment]
Yes, the doc is right, but that way you have a dangling pipe for `stdout` with no one reading from it. This will deadlock your process once there's enough output to fill the pipe's buffer. The docs have this warning:
> Warning Use communicate() rather than .stdin.write, .stdout.read or .stderr.read to avoid deadlocks due to any of the other OS pipe buffers filling up and blocking the child process.

**Comment by AdSchellevis** [comment]
The implication of this would be larger than the update_tables.py script, since in reality we haven't witnessed issue of this kind and the same documentation contains examples reading directly from the pipe as well, I would rather prevent adding more logic now. The same document also seems a bit ambiguous on when  Popen.communicate() is used internally.

**Comment by OliverO2** [comment]
I know you can get away with the simple model in `subprocess.run` most of the time. Problems start, for example, when there's unexpected runaway output of the command invoked. Or when output grows to a size exceeding the OS's pipe buffer. If so, it becomes hard to diagnose. I've experienced this more than once, and it's a general unixoid thing, not even Python-specific.

If output is meant to be ignored anyway, you'd just be safe with `stdout=subprocess.DEVNULL, stderr=subprocess.PIPE`.

**Comment by AdSchellevis** [comment]
no, you won't, since as mentioned earlier it's not a valid option. I'm not going to discuss this further, as far as I know it's not needed to wrap it, since `run() `encapsulates `Popen.communicate()` internally.

https://github.com/python/cpython/blob/5654f83b9706af88040f515791f1cdc5d81cd9d6/Lib/subprocess.py#L491

**Comment by OliverO2** [comment]
OK, I'm pretty sure its just a misunderstanding as `capture_output=True` is just a shortcut for `stdout=subprocess.PIPE, stderr=subprocess.PIPE`, and the question remains why you'd prefer to leave an unread pipe open, but let's leave it at that.

**Comment by AdSchellevis** [comment]
just read the python source an you'll see

**Comment by OliverO2** [comment]
I have read the source, I don't see that it contradicts what I have tried to convey.

The buffer filling up and blocking the process cannot be seen in the Python interpreter/library code (not even on the C level) as it happens behind the scenes in the popen(3) library function: After a [v]fork(2) system call, the stdin/stdout/stderr descriptors of the child process are connected to file descriptors of the parent process, which are then represented by the above Python `std*` file objects. Whenever an output file descriptor is open but never read, further output blocks the process once its buffer fills up. Connecting such a file descriptor to `/dev/null` prevents this.

But again, I'm not trying to push anyone.

**Comment by AdSchellevis** [comment]
Maybe there's some miscommunication, the only thing I tried to tell you here is that you can't set `stderr` or `stdout` while using capture output:

https://github.com/python/cpython/blob/5654f83b9706af88040f515791f1cdc5d81cd9d6/Lib/subprocess.py#L482-L485

Next it uses  `process.communicate` to capture the output into both byte or string buffers (depending configuration), which should prevent any type of locking

https://github.com/python/cpython/blob/5654f83b9706af88040f515791f1cdc5d81cd9d6/Lib/subprocess.py#L491

If you're using Popen directly, the doc states you should not use read() or write() directly, which isn't what we're doing (anywhere in the code as far as I know).

So either we have a hypothetical discussion of what should be best when not using `subprocess.run()` or there's a miscommunication of how `subprocess.run()` handles the underlaying pipes (which should be safe according to their own source and docs). 
Just trying to point you in the right direction, but if you still don't see my point, I suggest we just keep it that way as I'm pretty sure we should change anything other than what was broken (reading stdout in stead of stderr). 

As far as I can find it always reads both channels (stderr, stdout), no matter if you're going to use the output and uses `communicate()` to fetch the results.

**Comment by OliverO2** [comment]
I absolutely agree with you on not mixing `capture_output` with `stdout`/`stderr`. That's why the initial issue description reads

> change capture_output=True to stdout=subprocess.PIPE, stderr=subprocess.STDOUT

which was meant to say "replace the `capture_output` shortcut entirely". And later on the intention was to replace `capture_output=True` with `stdout=subprocess.DEVNULL, stderr=subprocess.PIPE` where stdout should be ignored.

Verifying the `_communicate` function

https://github.com/python/cpython/blob/5654f83b9706af88040f515791f1cdc5d81cd9d6/Lib/subprocess.py#L1370

I stand corrected and you are right that both outputs are read completely in a way that's blocking-free (via separate threads). Sorry for my wrong assumption that `stdout`/`stderr` are file-like objects being read on demand.

So employing my above suggestion would save some resources (two extra threads plus output memory) by avoiding the call to `_communicate` (note the underscore) entirely. But leaving it as it is now does no further harm. Thanks!
