### ISSUE TITLE
Missing translations

### ISSUE THREAD

**Issue by fichtner** [opnsense/core#427]
Reported by: @DokuKaefer

**Comment by thelinuxfr** [comment]
hello @fabianfrz I see that the task assigned to you, tell me if you need help ;)

@fichtner : Perhaps we need to update the task marking what is done (with ~~text~~) :D

**Comment by fichtner** [comment]
@thelinuxfr feel free to take this as well, I can also add you to contributors so we can assign tickets to you :)

I already deleted some of the ones that are done, but I haven't checked all of them yet.

**Comment by thelinuxfr** [comment]
Done for https://github.com/opnsense/core/blob/master/src/www/load_balancer_virtual_server.php#L131

**Comment by fichtner** [comment]
updated desc, thanks :)

**Comment by fichtner** [comment]
@thelinuxfr updated the list at the top :)

**Comment by thelinuxfr** [comment]
Hi @fichtner I think it is already fixed to the links below :
- https://github.com/opnsense/core/blob/master/src/www/vpn_openvpn_export_shared.php#L77
- https://github.com/opnsense/core/blob/master/src/www/vpn_openvpn_export_shared.php#L86
- https://github.com/opnsense/core/blob/master/src/www/vpn_openvpn_export_shared.php#L91
- https://github.com/opnsense/core/blob/master/src/www/vpn_openvpn_export_shared.php#L104
- https://github.com/opnsense/core/blob/master/src/www/vpn_openvpn_export_shared.php#L117

**Comment by fichtner** [comment]
Indeed, thanks, I'll remove them :)

**Comment by fichtner** [comment]
@thelinuxfr Almost there :)

**Comment by thelinuxfr** [comment]
Hi @fichtner 
Fixed for : 
- https://github.com/opnsense/core/blob/master/src/etc/inc/load_balancer_maintable.inc#L150
- https://github.com/opnsense/core/blob/master/src/etc/inc/load_balancer_maintable.inc#L158
- https://github.com/opnsense/core/blob/master/src/etc/inc/load_balancer_maintable.inc#L162

See something to translate the remaining lines?

**Comment by fichtner** [comment]
All done, thank you @fabianfrz and @thelinuxfr  :)
