### ISSUE TITLE
Traffic graph does not show the bandwidth of IPS enabled interfaces

### ISSUE THREAD

**Issue by JasMan78** [opnsense/core#4272]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[x] I have searched the existing issues and I'm convinced that mine is new.

**Describe the bug**
The "Traffic Graph" does not show the current bandwidth of physical interfaces, on which IPS is enabled and no VLANs are configured. The table below the graph shows the correct bandwitdh.
As soon as I disable IPS (not IDS) or remove the affected interface from the IDS/IPS settings, the bandwidth is shown.

Physical interfaces, which have additional VLANs configured, are both shown correctly.

This happens since I've switched to a new hardware appliance with Intel network interfaces.
On my old hardware appliance with Realtek interfaces and the same IDS/IPS and VLAN configuration, the graph shows the bandwidth for all interfaces correctly.

I've found another user in the forum which is having the same issue (3): https://forum.opnsense.org/index.php?topic=18496.msg84177#msg84177

**To Reproduce**
1. Go to "Services: Intrusion Detection: Administration"
2. Enable IDS and IPS.
3. Add a physical interface which has no VLANs configured
4. Switch to the "Traffic graph"
5. As soon as all IDS/IPS rules are loaded, the bandwidth in the graph for the interface drops down to zero
6. The table at the bottom shows the correct current bandwidth

**Expected behavior**
No idea :)

**Screenshots**
![OPNsense - Trafficgraph Issue](https://user-images.githubusercontent.com/20991399/90443392-78a92780-e0dc-11ea-87d5-76f6985a0bc2.jpg)

**Relevant log files**
Please let me know if you need a log file to identify the issue.

**Environment**
OPNsense 20.7.1-amd64
Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 cores)/NRG IPU662
Networ Interfaces: Intel i211AT

**Comment by AdSchellevis** [comment]
Best try the test kernel when it comes out (https://forum.opnsense.org/index.php?topic=17363.msg84952#msg84952), although I'm not sure if this issue already has an upstream fix. Intel 211 doesn't seem to obey the bpf zerocopy toggle (https://docs.opnsense.org/troubleshooting/network.html). We're not using i211 ourselves, i210 works like a charm.

**Comment by JasMan78** [comment]
Same with OPNsense 20.7.3-amd64.

**Comment by AdSchellevis** [comment]
tried the new netmap test kernel ? (https://forum.opnsense.org/index.php?topic=19175.msg88695#msg88695)

**Comment by JasMan78** [comment]
@AdSchellevis Ooops, sorry. I didn't get an info about your answer/request. 

I've installed the 20.7.4 update today, still no WAN traffic shown in the traffic graph.

**Comment by AdSchellevis** [comment]
@JasMan78 hmm, this is odd, I really thought I tested the graph with an i210 and zerocopy_enable (which already worked), but it seems that the new netmap kernel broke bpf in this case as well now. I probably didn't wait long enough for suricata to startup, maybe @muratbalaban43  has an idea, I think they where also looking into this subject.

**Comment by muratbalaban43** [comment]
@AdSchellevis , you're right. We are on this. Looks like netmap comes into the scene earlier than bpf.

**Comment by AdSchellevis** [comment]
@muratbalaban43 it's odd, using an earlier kernel I can't seem to get a functional bpf at all anymore (on my intel i210), so either my initial tests where flawed or I'm overlooking something completely different.

**Comment by muratbalaban43** [comment]
@AdSchellevis thanks for the update. Hopefully, I'll have some news next week.

**Comment by maxfield-allison** [comment]
I encountered this behavior when I enable promiscuous mode on Suricat running only on the physical WAN interface, igb0. disabling promiscuous immediately rectified the issue.

**Comment by ghost235** [comment]
Same with e1000 AND vmxnet3 on VMWare 6.5.0 with 20.7.4

**Comment by gitterdoneplease** [comment]
Seeing this exact behavior with em drivers too. Intel 82574L

**Comment by swhite2** [comment]
Please see https://github.com/opnsense/src/pull/95 for a fix to this issue. Keep in mind that if a driver is NOT integrated with iflib, the driver is responsible for supplying its statistics to the ifnet structure. Based on this, they may or may not cause the traffic graph to flatline.

All drivers mentioned in this issue are integrated with iflib, as such they should now report traffic in IPS mode.

Tested and confirmed on e1000.
