### ISSUE TITLE
Restoring a Backup with VLANs makes system unreachable

### ISSUE THREAD

**Issue by dinoex** [opnsense/core#4275]
I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

I have searched the existing issues and I'm convinced that mine is new.

**Describe the bug**
Valid Backup from 20.1.9_1, New Box upgraded to 20.7.1.
Restoring Backup with VLANs makes system unreachable

**To Reproduce**
Old Box running  20.1.9_1, using interfaces "em0" to "em3"
New Box upgraded to 20.7.1, using interfaces "igb0" to "igb3"
Restoring Backup  by GUI with Reboot.
Watching the serial console to assign interfaces.
No dialog could be entered in console.
System does not come back.

**Expected behavior**
Dialog on the console or GUI to assign Interfaces, 
or Migration of Interfaces based on the same order.

**Relevant log files**
serial console output
```
Initializing...........done.
igb0: link state changed to UP
igb1: link state changed to UP
igb3: link state changed to UP
Starting device manager...done.
Configuring login behaviour...done.

Default interfaces not found -- Running interface assignment option.

Press any key to start the manual interface assignment: 1

Valid interfaces are:
igb0             f4:90:ea:00:**:03 Intel(R) PRO/1000 PCI-Express Network Driver
igb1             f4:90:ea:00:**:04 Intel(R) PRO/1000 PCI-Express Network Driver
igb2             f4:90:ea:00::**::05 Intel(R) PRO/1000 PCI-Express Network Driver
igb3             f4:90:ea:00::**::06 Intel(R) PRO/1000 PCI-Express Network Driver

You now have the opportunity to configure VLANs.  If you don't require VLANs
for initial connectivity, say no here and use the GUI to configure VLANs later.

Do you want to configure VLANs now? [y/N]: n

VLAN interfaces:

em0_vlan25      VLAN tag 25, parent interface em0

If you do not know the names of your interfaces, you may choose to use
auto-detection. In that case, disconnect all interfaces now before
hitting 'a' to initiate auto detection.

Enter the WAN interface name or 'a' for auto-detection: igb1


Enter the LAN interface name or 'a' for auto-detection
NOTE: this enables full Firewalling/NAT mode.
(or nothing if finished): igb0

Optional interface 1 description found: OPT1
Enter the Optional interface 1 name or 'a' for auto-detection
(or nothing if finished):

The interfaces will be assigned as follows:

WAN  -> igb1
LAN  -> igb0

Do you want to proceed? [y/N]: y

Writing configuration...done.

```
**Additional context**
Workaround:
Logging in in serial console
Using the saved backup and converting the inferfaces with sed:

`sed -e 's|em0|igb0|' -e 's|em0|igb0|' -e 's|em1|igb1|' -e 's|em2|igb2|'  -e 's|em3|igb3|' /conf/backup/config-1597766805.0764.xml > /conf/config.xml
`

**Environment**
Old Box:
OPNsense 20.1.9_1 (amd64, OpenSSL).
AMD GX-416RA SOC (1597.14-MHz K8-class CPU)
interfaces "em0" to "em3"

New Box:
OPNsense  20.7.1 (amd64, OpenSSL).
AMD GX-416RA SOC (1597.14-MHz K8-class CPU)
Intel(R) PRO/1000 Network Connection, Version - 2.5.3-k
interfaces "igb0" to "igb3"

**Comment by fichtner** [comment]
Looks like the rename wasn’t complete as it’s still insisting on em0_vlan25.

**Comment by dinoex** [comment]
I was watching on the serial console assigning interfaces automatically and non interactive.

The Problem:
The user has no way to intercept the auto renaming failing.

**Comment by fichtner** [comment]
We could reject backup import on mismatches if that is in any form or shape more user friendly. In a way, it's not really a backup.. it's using a backup to do a migration and that requires external knowledge in the form of config.xml edits.

**Comment by dinoex** [comment]
Thanks.

with pfsense the Script was interactive to allow migration.
on OPNsense the standard input seems to be redirected to /dev/null.

I though this was an unintended feature regression.

**Comment by fichtner** [comment]
Hi Dirk,

I think it just stalled instead of going into auto-select after a brief timeout like it has been on OPNsense for most versions. For some that is preferable, but we also received a lot of complains for it from the other half of the users who had an opinion on this and it can clash with automatic SSH access for installer.

> OPNsense the standard input seems to be redirected to /dev/null

I don't believe that is true. Are you not seeing boot messages from rc system?


Cheers,
Franco
