### ISSUE TITLE
Feature request: Configurable IPv6 Prefix Advertisements

### ISSUE THREAD

**Issue by Senjuu** [opnsense/core#4276]
My Problem is the use of Global Unique und Unique Local Unicast addresses at the same time on the same interface which is supportet by the IPv6 standard. To utilize this it would be needed to advertise them which should be configurable under `/services_router_advertisements.php` there should be a new list like "Advertise Routes" which would configure the "ICMPv6 Option (Prefix Information)" in the ICMPv6 Packets of type "Router Advertisment (134)".

Respecting the possibility of dynamic prefixes via interface tracking, it should be considered the possibility how to enter this possibly changing prefix into this form.

**Comment by Senjuu** [comment]
As I am new to writing feature requests on GitHub I hope it is not rude to ask for guidance why my request recieved the "incomplete" label, but as far as I can see I considered every aspect of the issue template:
 - I described my problem ([...] the use of Global Unique und Unique Local Unicast addresses at the same time [...]
 - I described the solution I would like ([...] a [...] list like "Advertise Routes", [...] under `/services_router_advertisements.php` [...]) and noted a clear and concise description of what I want to happen ([...] configure the "ICMPv6 Option (Prefix Information)" in the ICMPv6 Packets of type "Router Advertisment (134)" .)

**Comment by AdSchellevis** [comment]
It's not rude, no problem at all, we tend to mark issue incomplete if our templates aren't used.
