### ISSUE TITLE
Web Proxy - Custom error pages

### ISSUE THREAD

**Issue by pkejval** [opnsense/core#4278]
**Describe the bug**
Web Proxy custom error pages aren't displayed.

**To Reproduce**
1. Go to Services -> Web Proxy -> Administration
2. Select "User error pages" to "Custom"
3. Go to "Error Pages" tab.
4. Click on Download.
5. Unzip downloaded file "proxy_template.zip"
6. Modify any file. For this example we will edit "ERR_DNS_FAIL.html"
7. Zip folder "proxy_template" into "proxy_template.zip" file.
8. Select and upload modified "proxy_template.zip". Web GUI says "saved" with no error.
9. Navigate to some non-existent domain for example "http://fsdfsdfsdfsdf.org/"

**Expected behavior**
We should see our modified "ERR_DNS_FAIL.html" page but we can see default one.

**File**
[proxy_template.zip](https://github.com/opnsense/core/files/5101750/proxy_template.zip)

**Comment by AdSchellevis** [comment]
did you restart the proxy?

**Comment by pkejval** [comment]
Yes, I tried to restart it too but not working either.

Stáhnout Outlook pro Android<https://aka.ms/ghei36>

________________________________

**Comment by AdSchellevis** [comment]
@pkejval you're right, it's a bug. the build process renames the template file, https://github.com/opnsense/core/commit/7b5c5c9b17a5d5a401bc895fc64b522041c6cdec should fix that and adds an apply button on the same screen.

You should be able to fix it using (on a console):
```
opnsense-patch 7b5c5c9
```

**Comment by AdSchellevis** [comment]
the fix seems to mispace the buttons a bit, I'll try to fix that later.

**Comment by pkejval** [comment]
I can confirm it's fixed by https://github.com/opnsense/core/commit/7b5c5c9b17a5d5a401bc895fc64b522041c6cdec

Thank you! :+1:
