### ISSUE TITLE
health: resolve interface names for traffic and packets

### ISSUE THREAD

**Issue by fichtner** [opnsense/core#428]
Is this easily possible in the drop down menu?

via: https://forum.opnsense.org/index.php?topic=1452.0

**Comment by AdSchellevis** [comment]
From an architecture point of view, this should be handled by the process collecting the data. The module using the data (health) has no knowledge of the items it's processing other then what's statically defined in the view definitions.
Unfortunately the collector part is still legacy code, so without glueing everything together from all different angles, there is no easy fix for this one at the moment.
I will assign this to myself, this needs some more thinking I guess.

**Comment by fichtner** [comment]
If not it can be ditched. Consider this nice to have only. Thanks for your thoughts. :)
