### ISSUE TITLE
Feature request: Add 'Enabled' (yes/no) filter options to IDS rule administration

### ISSUE THREAD

**Issue by OliverO2** [opnsense/core#4280]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[x] I have searched the existing issues and I'm convinced that mine is new.

**Is your feature request related to a problem? Please describe.**
When I was deciding whether to disable additional rules in response to alarms like `ET DNS Query for .*** TLD`, I used a search for `TLD`. Dealing with larger result sets would be more efficient if I could limit the results to contain just those rules which are currently enabled.

Vice versa, when reviewing rules, I'd like to see just those which were previously disabled.

**Describe the solution you'd like**
_Services: Intrusion Detection: Administration_ contains a useful filter drop-down. I'd like it to contain additional filter options to select
* enabled rules only, or
* disabled rules only.

**Describe alternatives you've considered**
None found.

**Comment by AdSchellevis** [comment]
https://github.com/opnsense/core/commit/5d8302f3c39a784abf805d02d60b6753263598aa should do the trick, just take care that it only filters "applied" state, same as the action filter does.

**Comment by OliverO2** [comment]
Excellent, thanks!

**Comment by AdSchellevis** [comment]
@OliverO2 your welcome, I'll close the issue, feel free to reopen if needed

**Comment by OliverO2** [comment]
Don't think I have sufficient privileges to reopen, but I'll certainly give it a try once it appears in an upcoming release. Will report if necessary.

**Comment by OliverO2** [comment]
Having tested this in the meantime all I can say is: Works like a charm! Very valuable to review disabled rules from time to time.
