### ISSUE TITLE
IPv6 connection is lost on the LAN interface after the tracked WAN interface (PPPoE) reconnected

### ISSUE THREAD

**Issue by norg** [opnsense/core#4282]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[X] I have searched the existing issues and I'm convinced that mine is new.

**Describe the bug**
With the update from 20.1 to 20.7 the IPv6 issues got worse for the case when the PPPoE WAN connection is lost and reconnected.
Whenever the VDSL Sync was lost and the PPPoE had to re-establish the connnection the IPv6 connection (except link local for sure) is gone on the LAN interface that is tracking the WAN (VDSL) interface.

In the past I had the same issue but it was not happening all the time and if it happened the workaround was to run `/var/etc/rtsold_pppoe0_script.sh` thanks to a hint from Franco F. This doesn't fix it anymore.

My current manual workaround is to go to the UI and go to the LAN Interface, don't change anything, just press "Save" and apply so that the interface is reconfigured with the same settings and IPv6 connection is back and now also for the clients in my network.

**To Reproduce**
1. Wait for (or trigger) PPPoE disconnect
2. Wait for established PPPoE link
3. See IPv6 on WAN working but not on LAN interface
4. Reconfigure LAN interface to get it working again

**Expected behavior**

Stable IPv6 connection, even after WAN reconnects.

**Screenshots**

**Relevant log files**

Let me know which ones are necessary.

**Additional context**

I'm willing to debug and manually add additional debug infos if it helps. I'm trying to understand how the different parts interact with each other with regards to IPv6.

Since it's "fixed" by manually triggering LAN interface reconfigure I would guess that configuration is fine but that the tracking between WAN and LAN interface has some bigger issue now. So feel free to guide me into which files I should look.

WAN (VDSL) interface is configured for IPv6 like this:

IPv6 Configuration Type - DHCPv6
Configuration Mode - Basic
Request only an IPv6 Prefix - Checked
Prefix Delegation Size - 56
Send IPv6 Preifx hint - Checked
Use IPv4 connectivity - Checked

LAN interface configuration for IPv6:

IPv6 Configuration Type - Track Interface
Track IPv6 Interface - VDSL (Name of the WAN interface in my setup)
IPv6 Prefix ID - 0x24

**Environment**

OPNsense 20.7.1-amd64
AMD GX-416RA SOC (4 cores)
OPNsense A10 Quad Core SSD Desktop Gen2

Thanks!

**Comment by IShouldHaveBeenAQATester** [comment]
I often have similar symptoms, no ppoe though.  I have lan track wan (ipv6pd).  It works great until the OPNSense stops routing ipv6 for whatever reason.  Client still has an address (slaac) as does the opensense wan/lan interface.

If I turn OFF tracking on LAN & turn it back no again it starts working again.  Sometimes it fails after 2 hours, sometimes after 4+ days.  No way to tell.

**Comment by ivwang** [comment]
Could it be radvd randomly stopping responding to route solicitation or broadcasting router advertisement?

In 20.7.* this is particularly observable, though I suspect it has already been that way since earlier.

In my environment (20.7.2) radvd rarely responds to RS, it does send RA to broadcast all-nodes address but that also randomly stops (and sometimes after like hours it starts sending again)

It can be observed from node side Wireshark. Sometimes RA is not seen even max RA interval has elapsed.

**Comment by greggitter** [comment]
> In my environment (20.7.2) radvd rarely responds to RS, it does send RA to broadcast all-nodes address but that also randomly stops (and sometimes after like hours it starts sending again)
> 
> It can be observed from node side Wireshark. Sometimes RA is not seen even max RA interval has elapsed.

I also observe the same where I don't recall the issue prior to 20.7.  Also perhaps related, from a cold boot I get no ipv6 connectivity without resaving both the wan and then lan interface pages (no changes, just save/apply).  Then after a period of seconds to minutes hosts will become live with ipv6.  My connection is native DHCPv6 from spectrum ISP, using stateless (i.e., dhcpv6 disabled, "unmanaged" selected in Router Advertisements manual settings with 100/200 interval) on opnsense and a /56 prefix if that matters.  I also have track wan for lan.  Have not had it stop working once it starts.

**Comment by norg** [comment]
Does anyone have any guides how to debug it further so we can help the OPNSense folks to find the root cause?

I currently have to disable IPv6 cause my servers at home aren't reachable in a stable way due to that issue :/

**Comment by greggitter** [comment]
The 2nd to last post [here](https://forum.opnsense.org/index.php?topic=18549.15) shows how to get debug information for radvd.  That's all I know unless you can get definitive steps to reproduce, especially without waiting x number of hours/days.  I'm not pppoe so I'm guessing this problem may me more widespread.  For me I can reproduce the problem with a cold boot.

**Comment by klada** [comment]
It seems I am also hit by this bug now. I have lost all IPv6 connectivity after a PPPoE reconnect. The box has lost all IPv6 addresses, also the WAN IPv6 address. Reboot fixes this.

This is not related to radvd in my case (although radvd has other issues). Where can we get the DHCPv6 client log? I'd like to check wether a prefix was received or not.

**Comment by marjohn56** [comment]
Enable the debug level you want in Interfaces->Settings, dhcp6c debug info should appear in the system log. Preferably reboot after changing and saving the log level.

**Comment by klada** [comment]
OK, this is the dhcp6c log when my ISP triggers a PPPoE reconnect:

<details>

<summary>
system.log

</summary>

```
Sep 17 17:49:46 gate opnsense[46750]: plugins_configure dhcp (,inet6) 
Sep 17 17:49:46 gate opnsense[46750]: plugins_configure dhcp (execute task : dhcpd_dhcp_configure(,inet6)) 
Sep 17 17:49:47 gate dhcp6c[15986]: RTSOLD script - Sending SIGHUP to dhcp6c 
Sep 17 17:49:47 gate dhcp6c[41806]: restarting 
Sep 17 17:49:47 gate dhcp6c[41806]: Start address release 
Sep 17 17:49:47 gate dhcp6c[41806]: release an IA: PD-0 
Sep 17 17:49:47 gate dhcp6c[41806]: reset a timer on pppoe0, state=RELEASE, timeo=0, retrans=911 
Sep 17 17:49:47 gate dhcp6c[41806]: Sending Release 
Sep 17 17:49:47 gate dhcp6c[41806]: a new XID (95b6d5) is generated 
Sep 17 17:49:47 gate dhcp6c[41806]: set client ID (len 14) 
Sep 17 17:49:47 gate dhcp6c[41806]: set server ID (len 26) 
Sep 17 17:49:47 gate dhcp6c[41806]: set elapsed time (len 2) 
Sep 17 17:49:47 gate dhcp6c[41806]: set IA_PD prefix 
Sep 17 17:49:47 gate dhcp6c[41806]: set IA_PD 
Sep 17 17:49:47 gate dhcp6c[41806]: send release to ff02::1:2%pppoe0 
Sep 17 17:49:47 gate dhcp6c[41806]: remove an IA: PD-0 
Sep 17 17:49:47 gate dhcp6c[41806]: remove a site prefix 2003:f4:e730:f00::/56 
Sep 17 17:49:47 gate dhcp6c[41806]: remove an address 2003:f4:e730:f64:2099:d2ff:fe7b:b5e8/64 on igb2_vlan10 
Sep 17 17:49:47 gate dhcp6c[41806]: remove an address 2003:f4:e730:f14:2099:d2ff:fe7b:b5e8/64 on igb2 
Sep 17 17:49:47 gate dhcp6c[41806]: remove an address 2003:f4:e730:f1e:2099:d2ff:fe7b:b5e8/64 on igb2_vlan3 
Sep 17 17:49:47 gate dhcp6c[41806]: reset a timer on pppoe0, state=INIT, timeo=0, retrans=256 
Sep 17 17:49:47 gate dhcp6c[41806]: removing an event on pppoe0, state=INIT 
Sep 17 17:49:47 gate dhcp6c[41806]: <3>[interface] (9) 
Sep 17 17:49:47 gate dhcp6c[41806]: <5>[pppoe0] (6) 
Sep 17 17:49:47 gate dhcp6c[41806]: <3>end of sentence [;] (1) 
Sep 17 17:49:47 gate dhcp6c[41806]: <3>end of sentence [;] (1) 
Sep 17 17:49:47 gate dhcp6c[41806]: <3>[id-assoc] (8) 
Sep 17 17:49:47 gate dhcp6c[41806]: <13>[pd] (2) 
Sep 17 17:49:47 gate dhcp6c[41806]: <13>[0] (1) 
Sep 17 17:49:47 gate dhcp6c[41806]: <13>begin of closure [{] (1) 
Sep 17 17:49:47 gate dhcp6c[41806]: <3>[prefix] (6) 
Sep 17 17:49:47 gate dhcp6c[41806]: <3>[::] (2) 
Sep 17 17:49:47 gate dhcp6c[41806]: <3>[/] (1) 
Sep 17 17:49:47 gate dhcp6c[41806]: <3>[56] (2) 
Sep 17 17:49:47 gate dhcp6c[41806]: <3>[infinity] (8) 
Sep 17 17:49:47 gate dhcp6c[41806]: <3>end of sentence [;] (1) 
Sep 17 17:49:47 gate dhcp6c[41806]: <3>[prefix-interface] (16) 
Sep 17 17:49:47 gate dhcp6c[41806]: <5>[igb2_vlan10] (11) 
Sep 17 17:49:47 gate dhcp6c[41806]: <3>begin of closure [{] (1) 
Sep 17 17:49:47 gate dhcp6c[41806]: <3>[sla-id] (6) 
Sep 17 17:49:47 gate dhcp6c[41806]: <3>[100] (3) 
Sep 17 17:49:47 gate dhcp6c[41806]: <3>end of sentence [;] (1) 
Sep 17 17:49:47 gate dhcp6c[41806]: <3>[sla-len] (7) 
Sep 17 17:49:47 gate dhcp6c[41806]: <3>[8] (1) 
Sep 17 17:49:47 gate dhcp6c[41806]: <3>end of sentence [;] (1) 
Sep 17 17:49:47 gate dhcp6c[41806]: <3>end of closure [}] (1) 
Sep 17 17:49:47 gate dhcp6c[41806]: <3>end of sentence [;] (1) 
Sep 17 17:49:47 gate dhcp6c[41806]: <3>[prefix-interface] (16) 
Sep 17 17:49:47 gate dhcp6c[41806]: <3>begin of closure [{] (1) 
Sep 17 17:49:47 gate dhcp6c[41806]: <3>[sla-len] (7) 
Sep 17 17:49:47 gate dhcp6c[41806]: <3>[8] (1) 
Sep 17 17:49:47 gate dhcp6c[41806]: <3>end of sentence [;] (1) 
Sep 17 17:49:47 gate dhcp6c[41806]: <3>end of closure [}] (1) 
Sep 17 17:49:47 gate dhcp6c[41806]: <3>end of sentence [;] (1) 
Sep 17 17:49:47 gate dhcp6c[41806]: <3>[prefix-interface] (16) 
Sep 17 17:49:47 gate dhcp6c[41806]: <3>[send] (4) 
Sep 17 17:49:47 gate dhcp6c[41806]: <3>end of sentence [;] (1) 
Sep 17 17:49:47 gate dhcp6c[41806]: <3>comment [# request prefix delegation] (27) 
Sep 17 17:49:47 gate dhcp6c[41806]: <3>[request] (7) 
Sep 17 17:49:47 gate dhcp6c[41806]: <3>end of sentence [;] (1) 
Sep 17 17:49:47 gate dhcp6c[41806]: <3>[request] (7) 
Sep 17 17:49:47 gate dhcp6c[41806]: <3>[domain-name] (11) 
Sep 17 17:49:47 gate dhcp6c[41806]: <3>end of sentence [;] (1) 
Sep 17 17:49:47 gate dhcp6c[41806]: <3>[script] (6) 
Sep 17 17:49:47 gate dhcp6c[41806]: <3>["/var/etc/dhcp6c_wan_script.sh"] (31) 
Sep 17 17:49:47 gate dhcp6c[41806]: <3>[prefix-interface] (16) 
Sep 17 17:49:47 gate dhcp6c[41806]: <3>begin of closure [{] (1) 
Sep 17 17:49:47 gate dhcp6c[41806]: <3>[sla-id] (6) 
Sep 17 17:49:47 gate dhcp6c[41806]: <3>[100] (3) 
Sep 17 17:49:47 gate dhcp6c[41806]: <3>end of sentence [;] (1) 
Sep 17 17:49:47 gate dhcp6c[41806]: <3>[sla-len] (7) 
Sep 17 17:49:47 gate dhcp6c[41806]: <3>[8] (1) 
Sep 17 17:49:47 gate dhcp6c[41806]: <3>end of sentence [;] (1) 
Sep 17 17:49:47 gate dhcp6c[41806]: <3>end of closure [}] (1) 
Sep 17 17:49:47 gate dhcp6c[41806]: <3>end of sentence [;] (1) 
Sep 17 17:49:47 gate dhcp6c[41806]: <3>[prefix-interface] (16) 
Sep 17 17:49:47 gate dhcp6c[41806]: <5>[igb2] (4) 
Sep 17 17:49:47 gate dhcp6c[41806]: <3>begin of closure [{] (1) 
Sep 17 17:49:47 gate dhcp6c[41806]: <3>[sla-id] (6) 
Sep 17 17:49:47 gate dhcp6c[41806]: <3>[20] (2) 
Sep 17 17:49:47 gate dhcp6c[41806]: <3>end of sentence [;] (1) 
Sep 17 17:49:47 gate dhcp6c[41806]: <3>[sla-len] (7) 
Sep 17 17:49:47 gate dhcp6c[41806]: <3>[8] (1) 
Sep 17 17:49:47 gate dhcp6c[41806]: <3>end of sentence [;] (1) 
Sep 17 17:49:47 gate dhcp6c[41806]: <3>end of closure [}] (1) 
Sep 17 17:49:47 gate dhcp6c[41806]: <3>end of sentence [;] (1) 
Sep 17 17:49:47 gate dhcp6c[41806]: called 
Sep 17 17:49:47 gate dhcp6c[41806]: called 
Sep 17 17:49:47 gate dhcp6c[41806]: reset a timer on pppoe0, state=INIT, timeo=0, retrans=244 
Sep 17 17:49:48 gate dhcp6c[41806]: Sending Solicit 
Sep 17 17:49:48 gate dhcp6c[41806]: a new XID (7a6251) is generated 
Sep 17 17:49:48 gate dhcp6c[41806]: set client ID (len 14) 
Sep 17 17:49:48 gate dhcp6c[41806]: set elapsed time (len 2) 
Sep 17 17:49:48 gate dhcp6c[41806]: set option request (len 4) 
Sep 17 17:49:48 gate dhcp6c[41806]: set IA_PD prefix 
Sep 17 17:49:48 gate dhcp6c[41806]: set IA_PD 
Sep 17 17:49:48 gate dhcp6c[41806]: send solicit to ff02::1:2%pppoe0 
Sep 17 17:49:48 gate dhcp6c[41806]: reset a timer on pppoe0, state=SOLICIT, timeo=0, retrans=1055 
Sep 17 17:49:48 gate dhcp6c[41806]: receive advertise from fe80::9ecc:83ff:fecb:e52c%pppoe0 on pppoe0 
Sep 17 17:49:48 gate dhcp6c[41806]: get DHCP option client ID, len 14 
Sep 17 17:49:48 gate dhcp6c[41806]:   DUID: 00:01:00:01:23:f5:45:6f:00:0d:b9:4a:7c:00 
Sep 17 17:49:48 gate dhcp6c[41806]: get DHCP option server ID, len 26 
Sep 17 17:49:48 gate dhcp6c[41806]:   DUID: 00:02:00:00:05:83:39:63:3a:63:63:3a:38:33:3a:63:62:3a:65:38:3a:34:30:00:00:00 
Sep 17 17:49:48 gate dhcp6c[41806]: get DHCP option IA_PD, len 41 
Sep 17 17:49:48 gate dhcp6c[41806]:   IA_PD: ID=0, T1=900, T2=1440 
Sep 17 17:49:48 gate dhcp6c[41806]: get DHCP option IA_PD prefix, len 25 
Sep 17 17:49:48 gate dhcp6c[41806]:   IA_PD prefix: 2003:f4:e730:2400::/56 pltime=1800 vltime=131378754631744 
Sep 17 17:49:48 gate dhcp6c[41806]: get DHCP option DNS, len 32 
Sep 17 17:49:48 gate dhcp6c[41806]: server ID: 00:02:00:00:05:83:39:63:3a:63:63:3a:38:33:3a:63:62:3a:65:38:3a:34:30:00:00:00, pref=-1 
Sep 17 17:49:48 gate dhcp6c[41806]: reset timer for pppoe0 to 0.689848 
Sep 17 17:49:48 gate dhcp6c[41806]: Sending Release 
Sep 17 17:49:48 gate dhcp6c[41806]: set client ID (len 14) 
Sep 17 17:49:48 gate dhcp6c[41806]: set server ID (len 26) 
Sep 17 17:49:48 gate dhcp6c[41806]: set elapsed time (len 2) 
Sep 17 17:49:48 gate dhcp6c[41806]: set IA_PD prefix 
Sep 17 17:49:48 gate dhcp6c[41806]: set IA_PD 
Sep 17 17:49:48 gate dhcp6c[41806]: send release to ff02::1:2%pppoe0 
Sep 17 17:49:48 gate dhcp6c[41806]: reset a timer on pppoe0, state=RELEASE, timeo=1, retrans=1839 
Sep 17 17:49:49 gate dhcp6c[41806]: picked a server (ID: 00:02:00:00:05:83:39:63:3a:63:63:3a:38:33:3a:63:62:3a:65:38:3a:34:30:00:00:00) 
Sep 17 17:49:49 gate dhcp6c[41806]: Sending Request 
Sep 17 17:49:49 gate dhcp6c[41806]: a new XID (f00431) is generated 
Sep 17 17:49:49 gate dhcp6c[41806]: set client ID (len 14) 
Sep 17 17:49:49 gate dhcp6c[41806]: set server ID (len 26) 
Sep 17 17:49:49 gate dhcp6c[41806]: set elapsed time (len 2) 
Sep 17 17:49:49 gate dhcp6c[41806]: set option request (len 4) 
Sep 17 17:49:49 gate dhcp6c[41806]: set IA_PD prefix 
Sep 17 17:49:49 gate dhcp6c[41806]: set IA_PD 
Sep 17 17:49:49 gate dhcp6c[41806]: send request to ff02::1:2%pppoe0 
Sep 17 17:49:49 gate dhcp6c[41806]: reset a timer on pppoe0, state=REQUEST, timeo=0, retrans=991 
Sep 17 17:49:49 gate dhcp6c[41806]: receive reply from fe80::9ecc:83ff:fecb:e52c%pppoe0 on pppoe0 
Sep 17 17:49:49 gate dhcp6c[41806]: get DHCP option client ID, len 14 
Sep 17 17:49:49 gate dhcp6c[41806]:   DUID: 00:01:00:01:23:f5:45:6f:00:0d:b9:4a:7c:00 
Sep 17 17:49:49 gate dhcp6c[41806]: get DHCP option server ID, len 26 
Sep 17 17:49:49 gate dhcp6c[41806]:   DUID: 00:02:00:00:05:83:39:63:3a:63:63:3a:38:33:3a:63:62:3a:65:38:3a:34:30:00:00:00 
Sep 17 17:49:49 gate dhcp6c[41806]: get DHCP option status code, len 2 
Sep 17 17:49:49 gate dhcp6c[41806]:   status code: success 
Sep 17 17:49:49 gate dhcp6c[41806]: get DHCP option DNS, len 32 
Sep 17 17:49:49 gate dhcp6c[41806]: Received REPLY for REQUEST 
Sep 17 17:49:49 gate dhcp6c[41806]: status code: success 
Sep 17 17:49:49 gate dhcp6c[41806]: nameserver[0] 2003:180:2:6000:0:1:0:53 
Sep 17 17:49:49 gate dhcp6c[41806]: nameserver[1] 2003:180:2::1:0:53 
Sep 17 17:49:49 gate dhcp6c[41806]: executes /var/etc/dhcp6c_wan_script.sh 
Sep 17 17:49:49 gate dhcp6c[48263]: dhcp6c REQUEST on pppoe0 
Sep 17 17:49:49 gate dhcp6c[54958]: dhcp6c REQUEST on pppoe0 - running newipv6 
Sep 17 17:49:50 gate opnsense[11269]: plugins_configure dhcp (,inet6) 
Sep 17 17:49:50 gate opnsense[11269]: plugins_configure dhcp (execute task : dhcpd_dhcp_configure(,inet6)) 
Sep 17 17:49:50 gate opnsense[11269]: /usr/local/etc/rc.newwanipv6: Warning! dhcpd_radvd_configure(manual) found no suitable IPv6 address on igb2 
Sep 17 17:49:50 gate opnsense[11269]: /usr/local/etc/rc.newwanipv6: Warning! dhcpd_radvd_configure(manual) found no suitable IPv6 address on igb2_vlan10 
Sep 17 17:49:50 gate opnsense[11269]: /usr/local/etc/rc.newwanipv6: Warning! dhcpd_radvd_configure(manual) found no suitable IPv6 address on igb2_vlan3 
Sep 17 17:49:51 gate dhcp6c[41806]: script "/var/etc/dhcp6c_wan_script.sh" terminated 
Sep 17 17:49:51 gate dhcp6c[41806]: removing an event on pppoe0, state=REQUEST 
Sep 17 17:49:51 gate dhcp6c[41806]: removing server (ID: 00:02:00:00:05:83:39:63:3a:63:63:3a:38:33:3a:63:62:3a:65:38:3a:34:30:00:00:00) 
Sep 17 17:49:51 gate dhcp6c[41806]: got an expected reply, sleeping. 
Sep 17 17:49:51 gate dhcp6c[41806]: Sending Release 
Sep 17 17:49:51 gate dhcp6c[41806]: set client ID (len 14) 
Sep 17 17:49:51 gate dhcp6c[41806]: set server ID (len 26) 
Sep 17 17:49:51 gate dhcp6c[41806]: set elapsed time (len 2) 
Sep 17 17:49:51 gate dhcp6c[41806]: set IA_PD prefix 
Sep 17 17:49:51 gate dhcp6c[41806]: set IA_PD 
Sep 17 17:49:51 gate dhcp6c[41806]: send release to ff02::1:2%pppoe0 
Sep 17 17:49:51 gate dhcp6c[41806]: reset a timer on pppoe0, state=RELEASE, timeo=2, retrans=3564 
Sep 17 17:49:51 gate dhcp6c[41806]: receive reply from fe80::9ecc:83ff:fecb:e52c%pppoe0 on pppoe0 
Sep 17 17:49:51 gate dhcp6c[41806]: get DHCP option client ID, len 14 
Sep 17 17:49:51 gate dhcp6c[41806]:   DUID: 00:01:00:01:23:f5:45:6f:00:0d:b9:4a:7c:00 
Sep 17 17:49:51 gate dhcp6c[41806]: get DHCP option server ID, len 26 
Sep 17 17:49:51 gate dhcp6c[41806]:   DUID: 00:02:00:00:05:83:39:63:3a:63:63:3a:38:33:3a:63:62:3a:65:38:3a:34:30:00:00:00 
Sep 17 17:49:51 gate dhcp6c[41806]: get DHCP option status code, len 2 
Sep 17 17:49:51 gate dhcp6c[41806]:   status code: success 
Sep 17 17:49:51 gate dhcp6c[41806]: Received REPLY for RELEASE 
Sep 17 17:49:51 gate dhcp6c[41806]: status code: success 
Sep 17 17:49:51 gate dhcp6c[41806]: executes /var/etc/dhcp6c_wan_script.sh 
Sep 17 17:49:51 gate dhcp6c[68154]: dhcp6c RELEASE on pppoe0 
Sep 17 17:49:51 gate dhcp6c[70560]: dhcp6c RELEASE on pppoe0 - running newipv6 
Sep 17 17:49:52 gate opnsense[80034]: plugins_configure dhcp (,inet6) 
Sep 17 17:49:52 gate opnsense[80034]: plugins_configure dhcp (execute task : dhcpd_dhcp_configure(,inet6)) 
Sep 17 17:49:53 gate opnsense[80034]: /usr/local/etc/rc.newwanipv6: Warning! dhcpd_radvd_configure(manual) found no suitable IPv6 address on igb2 
Sep 17 17:49:53 gate opnsense[80034]: /usr/local/etc/rc.newwanipv6: Warning! dhcpd_radvd_configure(manual) found no suitable IPv6 address on igb2_vlan10 
Sep 17 17:49:53 gate opnsense[80034]: /usr/local/etc/rc.newwanipv6: Warning! dhcpd_radvd_configure(manual) found no suitable IPv6 address on igb2_vlan3 
Sep 17 17:49:54 gate dhcp6c[41806]: script "/var/etc/dhcp6c_wan_script.sh" terminated 
Sep 17 17:49:54 gate dhcp6c[41806]: removing an event on pppoe0, state=RELEASE 
Sep 17 17:49:54 gate dhcp6c[41806]: got an expected reply, sleeping. 
```
</details>

You can see that the existing IP addresses are teared down from the interfaces (which is correct) and that there is a new prefix delegated through dhcp6c (`2003:f4:e730:2400::/56` in this case). However the new prefix is not applied by OPNsense until you reboot or change the WAN interface. So yes, this is broken.

**Comment by marjohn56** [comment]
Opnsense doesn't apply the addresses to the interfaces, dhcp6c does. There are some lines missing from the debug log, have you removed them? You should not be seeing a 'reply to release' from the server. Can you enable the Prevent  Release option in the interface settings.

**Comment by klada** [comment]
@marjohn56 I did not remove any lines from the system.log. The output starts right when the PPPoE link came back.

But your hint regarding "Prevent Release" is looking very promising :+1:.  I have enabled this option and it looks like the IPv6 connectivity does indeed survive PPPoE reconnects now.

**Everybody**: Please check if you have enabled this option under "Interfaces" -> "Settings"

The only thing which makes me wonder is that I have never touched this option between OPNsense updates. For some reason it just broke with the 20.7 upgrade. Weird.

**Comment by marjohn56** [comment]
I believe there were some changes made by in 20.7 to the way dhcp6c is called, I haven't looked at them as I've been busy with other projects, but when I get a bit of time I'll take a gander and see if something has been done that breaks anything, dhcp6c can be a little finicky.

**Comment by marjohn56** [comment]
Ah, maybe you had no release in earlier versions, but it was moved from the WAN interface itself to the Interfaces->Settings as we needed to allow for multiple WAN dhcp6c service, perhaps that was it.

**Comment by klada** [comment]
@marjohn56 This explains it. I have just looked it up in one of my backups and I do get this entry in the backup XML file:
```xml
  <interfaces>
    <wan>
      <dhcp6norelease>1</dhcp6norelease>
    </wan>
  </interfaces>
```

So I had configured this earlier. It looks like this setting is lost in the upgrade path from 20.1 to 20.7.

I guess this bug is still legit though, as the setting should have been migrated to the global interface settings. I don't know if you guys want to handle this or leave it as is.

**Comment by marjohn56** [comment]
too late now I guess, anyone who has updated has the problem. Only thing to do is post it on the forum.

**Comment by AdSchellevis** [comment]
@klada we don't offer migrations for legacy code, usually we try to mention non compatible changes in the change log. 
As @marjohn56 mentioned the feature was moved to interfaces -> settings in https://github.com/opnsense/core/commit/d87ce014d96f19cc8a94b8ed4cf9453d57aa0de9 (https://github.com/opnsense/core/pull/4099), since this is a general setting which can't be configured on a per interface basis. Even if we would have offered migrations, it would have been a "guestimate" about the correct setting when multiple interfaces would be involved.

**Comment by norg** [comment]
To that point now I'm a bit confused, do we mix several issues in the same?

**Comment by marjohn56** [comment]
It seems there are a couple of issues, the one mentioned above regarding prevent release which should help with pppoe resets  and another with radvd. The radvd appears to be an upstream problem.









Seems there
