### ISSUE TITLE
widget "interfaces" improvement: use space for interface name, show netmask, show config type

### ISSUE THREAD

**Issue by igpit** [opnsense/core#4283]
1. even with enough space available, long interface names get split across several lines
2. show netmask for each interface (or an optional column)
3. show interface config type (static IP, DHCP, optional column)

![opnsense-interfaces](https://user-images.githubusercontent.com/31316031/90977237-26d12900-e544-11ea-80c0-2cf9a054257a.png)

**Comment by marjohn56** [comment]
@igpit - I'll redo this is a plugin, that way it doesn't affect the core and it's optional.

**Comment by marjohn56** [comment]
@igpit - plugin has been PR'd. Here's a link to the installer pkg. 
https://www.dropbox.com/s/anphgkmjgl84xv9/os-interfaces_plus_widget-devel-0.1_1.txz?dl=0

Copy it to your /tmp folder, then cd to temp, then install it.
#pkg install os-interfaces_plus_widget-devel-0.1_1.txz

Refresh your lobby page then goto the add widgets and you should see it available there. The widget has a couple of checkboxes, use as you wish.
