### ISSUE TITLE
ipsec doesn't recover timely after pppoe (re)connect with IP address change

### ISSUE THREAD

**Issue by igpit** [opnsense/core#4285]
1. define a PPPoE connection over some interface, to be used as connection to the internet
2. configure a IPSec tunnel (used IKEv2, identified by static IP <-> distinguished name) over that pppoe link to some other router 
3. have a pppoe reconnect (e.g. forced disconnect by provider / cable unplugged / pppoe disconnect+connect) while getting a new IP assigned.
4. DynDNS will run fine to update the name 
5. wait "ages" for ipsec to start working again while regular internet connectivity has already been restored

workaround
restart the ipsec service manually after pppoe brought back up

expectation
opnsense knows what ipsec connections are based on which underlying connections, and if one gets changed, also reconnect ipsec based on that.
 
tested on OPNsense 20.7.1-amd64

**Comment by igpit** [comment]
after restarting my pppoe

`/usr/local/sbin/configctl interface reconfigure opt14`

i checked that i got a new ip , e.g. 

`cat /tmp/pppoe0_ip`

pinging the internet from the opnsense works again.

my still running ping from some LAN-box <-> opnsense <-> IPSec <-> pfsense <-> another LAN-box still times out. running the following makes the ping go through again instantly:

`ipsec up con2`

offtopic, but maybe you can enlighten me or tell me if this is intended and why: while doing this reconnect test, i keep pings running from the LAN box to some internet hosts like 1.1.1.1, 8.8.8.8 and 9.9.9.9 to see if the internet connection is there. when the reconfigure/reconnect on the pppoe completes, those pings often still keep failing , although the connection has been re-established - pings from the opnsense to the internet work. also if i start my LAN box a "new" ping to a different internet host, it also goes thtough instantly. i looked at the opnsense firewall live view, i do see there the "new" ping in green, the failing old pings dont even show up, not in red, not in any way. if i wait a while like a minute and then start pinging those "failing hosts", they go through again.  what am i missing?

**Comment by mimugmail** [comment]
Can you check IPsec.log?
