### ISSUE TITLE
simplify scheduled pppoe reconnect

### ISSUE THREAD

**Issue by igpit** [opnsense/core#4286]
OPNsense 20.7.1-amd64

the way i found to perform a scheduled pppoe reconnect is to create a cron job with "periodic interface reset" and entering the corresponding optXX interface as parameter.  also, the interface name also has to be looked up in "Interfaces => Overview" - it is not visible in the interface page itself. 

with many providers forcing a reconnect every 24h it would be nice to integrate that feature in the pppoe interface page itself: add a
- checkbox: "perform automatic interface reconnect"
- text field hours
- text field minutes

**Comment by fichtner** [comment]
We don't want to go backwards to overcomplicate again. You said it works as expected. All it needs is a select box for the cron parameter to automatically assign the interface.
