### ISSUE TITLE
Fail update 20.7 on XCP-NG

### ISSUE THREAD

**Issue by natux54** [opnsense/core#4289]
Hello
My OPNSensse is virtualized on an XCP-NG 8.1 hypervisor, after upgrading from 20.1 to 20.7 the OPNsense startup runs in loop on errors and doesn't want to start anymore.

You can see this problem in attechements files

thank you for your help

![opnsense_20 7_02](https://user-images.githubusercontent.com/13085042/91027109-ee8d2180-e5fb-11ea-9434-8c57162ff675.png)
![opnsense_20 7_01](https://user-images.githubusercontent.com/13085042/91027110-ef25b800-e5fb-11ea-84df-98d1797bf228.png)

**Comment by L1ghtn1ng** [comment]
@lattera me anything to you as I am looking at setting up a lab with xcp-ng and would like to make sure I do not hit this etc? @natux54 Just out of interest does a clean install hit this issue?

**Comment by natux54** [comment]
@L1ghtn1ng a clean installation does not affect this problem.
but when an additional interface is activated the problem returns.
