### ISSUE TITLE
Outbound NAT rule breaks when renaming an Alias it is using

### ISSUE THREAD

**Issue by koelle25** [opnsense/core#4292]
[x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[x] I have searched the existing issues and I'm convinced that mine is new.

**Describe the bug**
We have an *Outbound NAT* rule, which is using an *Alias* (from `/ui/firewall/alias`) as the *Destination Address*.
When renaming this Alias (and pressing *Apply* ofc) this change is not reflected into the Outbound NAT rule. When opening the edit page of the Outbound NAT rule the *Destination Address* is now `Single host or network` with the old Alias name as the value.

**To Reproduce**
1. Go to 'Firewall > Aliases' (`/ui/firewall/alias`) and add a Host alias
1. Go to 'Firewall > NAT > Outbound' (`/firewall_nat_out.php`) and add a new rule using the previously created Alias as the *Destination address*
1. Go back to 'Firewall > Aliases' and rename the Alias
1. Go back to 'Firewall > NAT > Outbound', edit the rule in question and see that the Alias is not selected anymore.

**Expected behavior**
Renaming an Alias does reflect into Outbound NAT rules (it works e.g. for rules in 'NAT > Port Forward').

**Screenshots**
Before renaming the Alias:
![Before renaming the Alias](https://user-images.githubusercontent.com/915514/91050558-1cd02880-e61f-11ea-8aac-8b25d655c2bf.png)
After renaming the Alias:
![After renaming the Alias](https://user-images.githubusercontent.com/915514/91050510-0c1fb280-e61f-11ea-9799-5999d936f6c5.png)

**Environment**
OPNsense 20.1.9-amd64
FreeBSD 11.2-RELEASE-p20-HBSD
OpenSSL 1.1.1g  21 Apr 2020

**Comment by glasid** [comment]
I'm having exactly the same issue.
