### ISSUE TITLE
OpenVPN ccd-exclusive not working

### ISSUE THREAD

**Issue by Lightning1984** [opnsense/core#4293]
Hi,

I'm currently trying to migrate from PFSense (Version 2.3.4)  to an OPNSense platform (20.7.1).
Unfortunately i have encountered an issue with OpenVPN which doesn't allow me finish migration.

In general I'm using certificate only based authentication + TLS authentication.
For additional security I'm using the "ccd-exclusive" directive which prevents any client without a "Client Specific Override" configured from connecting. 
On PFSense each entry on the "Client Specific Overrides" admin page creates a file in the relevant csc folder, i.e. "/var/etc/openvpn-csc/server2".
On OPNSense the csc folder visible in the OpenVPN config remains empty (/var/etc/openvpn-csc/4), instead AFAIK the overrides are dynamically created when a client connects by invoking some script: client-connect "/usr/local/etc/inc/plugins.inc.d/openvpn/ovpn_setup_cso.php server4"

Without "ccd-exclusive" configured everything works normal, the client can connect and also the client specific settings defined in the web gui for the client in question get pushed to the client (i.e. IP address, routes, DNS, etc.)

When ccd-exclusive directive is present in the OpenVPN configuration clients can no longer connect due to the following error:
Tue Aug 25 10:09:08 2020 a.b.c.d:10524 TLS Auth Error: --client-config-dir authentication failed for common name 'XXX-MOBILE' file='/var/etc/openvpn-csc/4/XXX-MOBILE'

When manually creating the file in the csc folder the connection works again, two lines show up in the log:
Tue Aug 25 11:01:58 2020 XXX-MOBILE/a.b.c.d:10462 OPTIONS IMPORT: reading client specific options from: /var/etc/openvpn-csc/4/XXX-MOBILE
Tue Aug 25 11:01:58 2020 XXX-MOBILE/a.b.c.d:10462 OPTIONS IMPORT: reading client specific options from: /tmp/openvpn_cc_6473f5202ef9d246c77bc1221621b4a.tmp

So it looks like the "client-connect" script is generating the file too late in the connection setup sequence.
Is there a way to revert back to the old file based Client Specific Overrides or any other trick to make ccd-exclusive work again.

regards
Rupert

**Comment by kosli** [comment]
I have the need too to use the **ccd-exclusive** option, whereas obviously this would only work if the client specific configs are stored in the **client-config-dir**. 

As OPNsense is using a dnyamic **client-connect** script to provide the options to the client, I suppose the **client-config-dir** option should be removed from the generated server config?

Nevertheless, the behavior of **ccd-exclusive** could be emulated by adapting the client-connect script https://github.com/opnsense/core/blob/master/src/etc/inc/plugins.inc.d/openvpn/ovpn_setup_cso.php
