### ISSUE TITLE
add all dns characters to alias names

### ISSUE THREAD

**Issue by colttt** [opnsense/core#4294]
**Is your feature request related to a problem? Please describe.**
Hello, at the moment we evaluate OPNsense to replace our current firewall. We had a lot of hosts in our FW and when we add/create hosts we use IP and DNS-Name, but it looks like that is not possible with OPNsense, but Alias don't support '.' and '-' its not possible.
btw: it would also be good to find the alias not only by the name, also with the IP-address

**Describe the solution you'd like**
I would like an input field in the `/ui/firewall/alias` which would add the possibility to use '.' and '-'
And also make it possible to search via IP in /firewall_rules_edit.php

**Describe alternatives you've considered**
when you add an host IP and dns **must** match, if you wnat you can add a Tag/Alias, but everything must be searchable

**Comment by AdSchellevis** [comment]
alias names are bound by the rules the underlaying technology (pf) has set, you can use any description you like, names need to follow rules.

**Comment by Tragen** [comment]
https://github.com/opnsense/core/issues/1434
I requested the same 3.5 years ago.
It's not nice but we replace - with _ currently.
I would also like to see this.

**Comment by fichtner** [comment]
Technical limitation and work required aside--is this a real world issue after 3.5 years of going without this? What do you expect from fixing this?

**Comment by Tragen** [comment]
It is not a real issue, it is an inconvenience and annoyance.
When you script opnsense, you always have to "translate" computer-names and usernames aso.
The same for wireguard endpoint names. No .-_ allowed
