### ISSUE TITLE
UI Label in opnsense still refers to pfSense

### ISSUE THREAD

**Issue by spiriapbergeron** [opnsense/core#4296]
See where it says "pfSync nodes" in Interfaces->Virtual IPs -> Status
(I can only assume that "pfSync" refers to "pfSense" ?

![image](https://user-images.githubusercontent.com/50995128/91274547-d8db4180-e74c-11ea-9701-b34e5eaccf42.png)

**Comment by fichtner** [comment]
pfsync is a technical term for state table synchronisation in pf.

https://man.openbsd.org/pfsync.4
