### ISSUE TITLE
GUI is missing VIP interfaces once cluster got updated to 20.7

### ISSUE THREAD

**Issue by NielsPiersma** [opnsense/core#4297]
This afternoon I've updated OPNSENSE on a DEC2670 Deciso appliance.
After the update the VIP interfaces have disappeared below "Firewall" in the GUI.

It was expected to find the VIP interfaces under 'firewall'

Direct link to carp_status is working

eg https://x.y.z/firewall_virtual_ip.php#Firewall_VIP

Hardware; DEC2670
OPNsense 20.7 (amd64, OpenSSL).
AMD GX-416RA SOC
Network Intel igb
![VIP missing](https://user-images.githubusercontent.com/70269175/91300481-a14bb400-e7a3-11ea-906e-c7d1da3fa25e.PNG)

**Comment by mimugmail** [comment]
Moved to Interfaces Section

**Comment by fichtner** [comment]
Accepted "solution" in the forum already. :)
