### ISSUE TITLE
20.7.1 - Firewall, Live View not working

### ISSUE THREAD

**Issue by pkejval** [opnsense/core#4298]
After updating from 20.7 to 20.7.1 Firewall, Live View is not updating anymore. I can see old data from 2020-08-14 before I updated OPNsense. I have 2 independed machines with OPNsense and both are in same state.

I tried to clear log in Firewall, Plain view. Log is empty now, no new entries are added.

**Comment by AdSchellevis** [comment]
this https://github.com/opnsense/core/issues/4263#issuecomment-675431582 ?

**Comment by pkejval** [comment]
Yes! It's working after installing that package and running `/usr/local/etc/rc.d/syslog-ng start`

**Comment by AdSchellevis** [comment]
will be fixed in the next release, it's an issue with syslog-ng.
