### ISSUE TITLE
Feature request: Add 'is not' & 'no contains' to Firewall / Live View

### ISSUE THREAD

**Issue by sibelle-labs** [opnsense/core#4299]
Feature request: 
Add 'is not' & 'no contains' to Firewall / Live View
Nice on big networks with multiple VLAN / Subnets, etc 

Example:
1th badge: interface is lan
2th badge: src no contains 172.30.*
3th badge: dst ist not 192.168.*

Thanks a lot !
cheers

![grafik](https://user-images.githubusercontent.com/65012538/91726065-ed319b00-eb9f-11ea-96d1-54f2fb9cf502.png)

**Comment by andreaslink-de** [comment]
I fully second this, I had a host spamming with broadcast I would have preferred to get ignored for the moment. So good idea for filtering. I'd also like to Filter on IPv6 or IPv4 only, I don't see, I can do this right now, expect with approaches of filter on ":" in source/dest addresses.

**Comment by AdSchellevis** [comment]
closed with https://github.com/opnsense/core/pull/4402
