### ISSUE TITLE
rulecache.py parsing bad formatted rules

### ISSUE THREAD

**Issue by kulikov-a** [opnsense/core#4302]
Hi!
IDS PT Research ruleset have bad formatted rules.
rulecache.py throws error parsing rules metadata:
root@OPNsense:~ # /usr/local/opnsense/scripts/suricata/installRules.py
Traceback (most recent call last):
File "/usr/local/opnsense/scripts/suricata/installRules.py", line 56, in
for rule_info_record in RuleCache.list_rules(filename=filename):
File "/usr/local/opnsense/scripts/suricata/lib/rulecache.py", line 110, in list_rules
record['metadata'][parts[0]] = parts[1]
IndexError: list index out of range

bad formatted "metadata" strings examples:
"metadata: id_140409,created_at 2017_6_2, url, https://blog.fortinet.com/2016/07/27/bayrob-an-ancient-evil-awakens-ii"
(metadata "url" comma separated from value ("..blog.frtinet.."); metadata (id_140409) without value)

**Comment by AdSchellevis** [comment]
@kulikov-a can you try https://github.com/opnsense/core/commit/f082239c5ca5f28901fa7dc6a9d104648616043e ?

**Comment by kulikov-a** [comment]
updates without error but loose bunch of metadata
eg
raw rule:
alert tcp $EXTERNAL_NET [20000:] -> $HOME_NET any (msg: "MALWARE [PTsecurity] Bayrob detected ";flow: established, to_client; flowbits:isset,PT.Bayrob0; dsize:2; flags:PA;stream_size:server,=,3;stream_size:client,<,400;flowbits:unset,PT.Bayrob0; classtype: trojan-activity; metadata: id_140409,created_at 2017_6_2, url, https://blog.fortinet.com/2016/07/27/bayrob-an-ancient-evil-awakens-ii; reference: url, github.com/ptresearch/AttackDetection; metadata: Open Ptsecurity.com ruleset; sid: 11001394; rev: 2;)
rule detail in GUI:

Signature Id | 11001394 |  
-- | -- | --
Revision | 2 |  
Message | MALWARE [PTsecurity] Bayrob detected |  
Open | Ptsecurity.com ruleset |  
classtype | trojan-activity |  
created_at | 2017_6_2 |  
reference_html | github.com/ptresearch/AttackDetection |  
source | pt.research.rules

**Comment by AdSchellevis** [comment]
I don't think we can (or should) fix invalid metadata, the format is well defined at https://suricata.readthedocs.io/en/suricata-4.1.4/rules/meta.html#metadata  ,

**Comment by kulikov-a** [comment]
completely agree. just opened a ticket at ptresearch (https://github.com/ptresearch/AttackDetection/issues/22)
but may be last one "if"?)
                            if prop == 'metadata':
                                count = 1
                                for mdtag in list(csv.reader([value], delimiter=","))[0]:
                                      count += 1
                                      parts = mdtag.split(maxsplit=1)
                                      if len(parts) > 1:
                                        record['metadata'][parts[0]] = parts[1]
                                      else:
                                        record['metadata']['meta'+str(count)] = parts[0]
                            else:
                                record[prop] = value

and we can view all meta:

Signature Id | 11001394 |  
-- | -- | --
Revision | 2 |  
Message | MALWARE [PTsecurity] Bayrob detected |  
Open | Ptsecurity.com ruleset |  
classtype | trojan-activity |  
created_at | 2017_6_2 |  
meta2 | id_140409 |  
meta4 | url |  
meta5 | https://blog.fortinet.com/2016/07/27/bayrob-an-ancient-evil-awakens-ii |  
reference_html | github.com/ptresearch/AttackDetection |  
source | pt.research.rules

**Comment by AdSchellevis** [comment]
not going to do that metaX as field doesn't really offer a lot of value, it's an upstream issue.

**Comment by kulikov-a** [comment]
hi!This is definitely an upstream issue. 
just because they don't react to tickets I tried to work around it. because we are losing vulnerability description links in rule details.on the other hand we can always google it .
Thank you very much for quick responses and veeeeery nice software!
