### ISSUE TITLE
Firewall bricks itself every day or 2

### ISSUE THREAD

**Issue by loganx1121** [opnsense/core#4305]
![photo_2020-08-27_06-21-40](https://user-images.githubusercontent.com/56660155/91434127-5c229300-e832-11ea-87d9-a42f0a43357c.jpg)

Since upgrading to the latest version of OPNsense 20.7.1, my firewall will lock/stop passing traffic every day or so.  I saw a post about the same issue on the opnsense forums and it seems like downgrading the firmware fixed it for him.  I hooked up a monitor to mine after the last time...this is what I saw when I woke up this morning with no firewall.  Firewall was always stable until the recent upgrade.

FYI when this happens, I cannot ssh to any of the interfaces or access the web GUI.  I have to manually power off the firewall, then power back on.  I read on the other post that before downgrading the firmware, the gentleman was able to kind of get around this with a cron job that rebooted his firewall at 5 AM every morning.  

Steps to reproduce (for me anyway) is to upgrade to 20.7.1 and just let the firewall run for a day or two.  It seems to be pretty random when it happens, but always with a day or two of a hard reboot.  While it's running everything works fine.  I've already reinstalled 20.7.1 a few times with fresh iso's but the problem keeps coming back

**Comment by fichtner** [comment]
Disable IPS mode or Sensei. Intel drivers have netmap issues on FreeBSD 12.1.

**Comment by loganx1121** [comment]
> Disable IPS mode or Sensei. Intel drivers have netmap issues on FreeBSD 12.1.

Under services > Intrusion detection > the only thing I have enabled is syslog alerts.  IDS and IPS are both off.  Must be sensei then.  I found a post on the opnsense forums with a beta patch/version and I"m trying that now.  Will report back.

**Comment by fichtner** [comment]
It needs a kernel replacement, installing Sensei beta isn’t changing this. There are a few unofficial test kernels available, e.g.

    # opnsense-update -kr 20.7.1-netmap4
    # opnsense-shell reboot

But it’s too early for a release kernel update WRT netmap.

**Comment by loganx1121** [comment]
> It needs a kernel replacement, installing Sensei beta isn’t changing this. There are a few unofficial test kernels available, e.g.
> 
> ```
> # opnsense-update -kr 20.7.1-netmap4
> # opnsense-shell reboot
> ```
> 
> But it’s too early for a release kernel update WRT netmap.

Ah ok.  So I guess downgrading the firmware until this gets hashed out would be the best option?

**Comment by fichtner** [comment]
In general yes, but downgrading major OS version is difficult. You need a reinstall with config importer if you don’t have snapshots (looks like Hardware anyway).

**Comment by loganx1121** [comment]
This was the "beta" thing recommended to install on the opnsense forum.  I'm actually not sure if it's a sensei beta or a kernel beta but this is what I tried.

pkg add -f https://updates.sunnyvalley.io/opnsense/updates/netmap-kernel/os-sensei-1.6.beta1.txz

**Comment by loganx1121** [comment]
Sorry...early morning and not enough coffee.  I see there is both a test kernel and a sensei beta so I'm trying that.
