### ISSUE TITLE
Unbound configuration incorrectly calculates *-slabs options for performance.

### ISSUE THREAD

**Issue by Stifler6996** [opnsense/core#4308]
**Describe the bug**
As per this performance tuning guide by NLnet labs:
https://nlnetlabs.nl/documentation/unbound/howto-optimise/
```
Set *-slabs to a power of 2 close to the num-threads value.
Do this for msg-cache-slabs, rrset-cache-slabs, infra-cache-slabs and key-cache-slabs.
This reduces lock contention.
```

Opnsense takes num-threads and appears to "*2" the value and apply that. so with my 16 threads, it applies a value of 32 to each of the *-slabs options. whereas the correct value should be 4.

The correct calculation should be `p2value = pow(2, ceil(log(x)/log(2)));` which will result in the correct value

**To Reproduce**
Run unbound on a multicore processor > 2 cores

**Expected behavior**
1 core = value of 1
2 cores = value of 1
4 cores = value of 2
-6 cores = value of 3 (it is 2.58 which is closer to 3 than 2)
8 cores = value of 3
10 cores = 3
12 cores = 4
16 cores = 4
32 cores = 5

**Screenshots**
![image](https://user-images.githubusercontent.com/12870096/91544216-9426f480-e95e-11ea-8d3c-ad24e07d4aba.png)

**Environment**
OPNsense 20.1.9_1-amd64
FreeBSD 11.2-RELEASE-p20-HBSD
OpenSSL 1.1.1g 21 Apr 2020

(I cannot run 20.7 due to the current - crippling - bug with vmx vmware net drivers and promiscuous mode)

**Comment by fichtner** [comment]
https://github.com/opnsense/core/issues/3092 and especially https://github.com/opnsense/core/commit/0c751d732a4d3

Feel free to disagree, but don't point fingers if you cannot pull up this freely available information and ask why it was done.

**Comment by Stifler6996** [comment]
https://github.com/opnsense/core/issues/3092#issuecomment-451131487
This post is incorrect.

It should be `2**1` 2**2` rather than what that post suggested. Or in more traditional terms `2^1` `2^2` `2^3`

The wording is a bit sloppy in the NLnet labs documentation, but the calculation is to create a fair and not "unnecessary" number of slabs. The point is to reduce lock contention and _not_ to produce excess overhead.

My offer of calculation `log(cpusnumber) / log(2)` and then ceiling that value is what was intended in that performance guide.
It gives you a reasonable and fair number of pages for Unbound to use for its caching and then threading purposes.

**Comment by Stifler6996** [comment]
As a comment, this website is a classic example of misunderstanding: https://calomel.org/unbound_dns.html

The cache is not a `2 ^ num-threads` this is way to many and massively over fragmented.

**Comment by fichtner** [comment]
Forgive me for assuming "power of 2" means 1, 2, 4, 8, 16, 32, etc. ;)

**Comment by Stifler6996** [comment]
I agree that it is confusing 😃 .

`Set *-slabs to a power of 2 close to the num-threads value.`

But the subtlety is in the words "close to" . There is no need for "close to" if it was a simple `2^4` and walk away happy.

It is "close to" because one needs to chose a value that calculates a result that is "close to" your total number of cpus/threads.

I know, it did my head in for a while too.  😄

**Comment by fichtner** [comment]
Well, shame on the official docs to omit the calculation or a reference table.

This is the rub-in: power of two means just that and "close to" means one of those specifically, whether up or down the official docs also don't say. Shame on them again. Your over-fragmented is my lock contention avoidance under heavy load.

also calomel wasn't used in any of our research so mentioning a site that especially OpenBSD folks don't think offers good advice but has fancy graphics is not helpful to the technical discussion at hand.

To make this more productive and looking at your install 16 CPUs is a lot, maybe too much so you look for a way to decrease slabs and threads maybe by offering a thread override so you can set it to something lower.


Cheers,
Franco

**Comment by Stifler6996** [comment]
Well I agree, 16 is a lot, but since this is all done in one of my esx hypervisors, it doesnt matter that I give it 16 or 8 vcpu, since opnsense isnt "working hard" 99% of the time.

I currently override using this in the custom options (which concerns me, because as you state its insecure, and you will remove eventually - but I will would like full control over settings)

```
server:
 use-caps-for-id: yes
 val-clean-additional: yes
 #reuse port is broken in current version of FreeBSD/HardenedBSD)
 so-reuseport: no
 num-threads: 16
 msg-cache-slabs: 4
 rrset-cache-slabs: 4
 infra-cache-slabs: 4
 key-cache-slabs: 4
```
And it works fine, nicely balanced and sharing the workload evenly. So I can fix it.

Oh and a quick test showed that I can set num-threads to 8 and *-slabs to 3 and no change in performance so I am over committing on the VM, but since the HVisor is distributing, I never noticed. just more threads to go around.

The thing I notice (since I only give the VM 4G memory), is the decreased usage going from 32 to 4 with *-slabs. with no noticeable difference in perf.

I use namebench for testing (unselect everything and just run on the local dns)

![image](https://user-images.githubusercontent.com/12870096/91549608-5928bf00-e966-11ea-81df-4c2e833a3632.png)
https://code.google.com/archive/p/namebench/

Restart Unbound to clear cache and test (use top 2k and do first 250). then run a second/third time to see cache performance.

**Comment by fichtner** [comment]
You can drop your files into the file system "override", something we prefer vs. pushing raw settings from the GUI:

    # grep 'include.*\*' /var/unbound/unbound.conf
    include: /var/unbound/etc/*.conf


Cheers,
Franco
