### ISSUE TITLE
Possible Bug: routing issue possible firewall rules issue not being followed for vlan

### ISSUE THREAD

**Issue by upended** [opnsense/core#4310]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[-] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[-] I have searched the existing issues and I'm convinced that mine is new.

**Describe the bug**
A clear and concise description of what the bug is, including last known working version (if any).

*Tip*: to validate your setup was working with the previous version, use opnsense-revert (https://docs.opnsense.org/manual/opnsense_tools.html#opnsense-revert)

Connections from an internal vlan to a different internal vlan, are being routed to external interface if there is a rule for the destination port. When no rule exist, the traffic is blocked as expected.

The firewall has several individual port rules.
interface = vlan 1 192.168.10.0/24
Allow IN S=192.168.10.2 D=192.168.20.2 port 5555
Allow IN S=192.168.10.2 D=192.168.20.2 port 5556
Allow IN S=192.168.10.2 D=192.168.20.2 port 5557
Allow IN S=192.168.10.2 D=ANY port 80
Allow IN S=192.168.10.2 D=ANY port 443
Block IN Any / Any / Any
Block Out  Any / Any / Any

interface = vlan 2 192.168.20.0/24
Allow Out S=192.168.10.2 D=192.168.20.2 port 5555
Allow Out S=192.168.10.2 D=192.168.20.2 port 5556
Allow Out S=192.168.10.2 D=192.168.20.2 port 5557
Block IN Any / Any / Any
Block Out  Any / Any / Any

interface = VPNservice1
no rules

interface = VPNservice2
no rules

When computer A 192.168.10.2 on vlan1 is attempting to connect to computer B 192.168.20.2:22, the firewall live view shows denied by explicit deny rule. Working as expected.
vlan1|   | Aug 31 11:04:39 | 192.168.10.2:56765 | 192.168.20.2:22 | tcp | Deny: vlan1 to ALL: Inbound Traffic 
vlan1|   | Aug 31 11:04:27 | 192.168.10.2:56762 | 192.168.20.2:22 | tcp | Deny: vlan1 to ALL: Inbound Traffic

When attempting to connect from 192.168.10.2 to vlan2 192.168.20.3 port 80, traffic is sent from vlan1 to **EXTERNAL interface 10.0.0.2/16** VPNservice.

VPNservice1|   | Aug 31 10:43:00 | 10.0.0.5:11783 | 192.168.20.2:80 | tcp | let out anything from firewall host itself (force gw) |  
vlan1 |   | Aug 31 10:43:00 | 192.168.10.2:56368 | 192.168.20.2:80 | tcp | Allow HTTP to Websites

When attempting to connect from 192.168.10.2 to vlan2 192.168.20.3 port 443, traffic is sent from vlan1 to **EXTERNAL interface 10.0.0.2/16** VPNservice.

VPNservice2 |   | Aug 31 11:07:25 | 10.6.0.2:7829 | 192.168.20.3:443 | tcp | let out anything from firewall host itself (force gw) |  
vlan1 |   | Aug 31 11:07:25 | 192.168.10.2:56807 | 192.168.20.3:443 | tcp | Allow HTTPS to Websites

VPNservice2 |   | Aug 31 11:07:06 | 10.6.0.2:36134 | 192.168.20.2:443 | tcp | let out anything from firewall host itself (force gw) |  
vlan1 |   | Aug 31 11:07:06 | 192.168.10.2:56802 | 192.168.20.2:443 | tcp | Allow HTTPS to Websites

When attempting to connect from 192.168.10.2 to vlan2 192.168.20.2:5555, traffic is sent sent correctly according to the FW live view, however, tcpdump show traffic being sent 1 way.

30:12.7 | IP | 192.168.10.2.57223 | > | 192.168.20.2.7443 | Flags | [S], | seq | 2083935862, | win | 8192, | options | [mss 1460,nop,wscale2,nop,nop,sackOK], | length | 0
30:13.0 | IP | 192.168.10.2.57224 | > | 192.168.20.2.7443 | Flags | [S], | seq | 2854825982, | win | 8192, | options | [mss 1460,nop,wscale2,nop,nop,sackOK], | length | 0
30:18.7 | IP | 192.168.10.2.57222 | > | 192.168.20.2.7443 | Flags | [S], | seq | 3714687900, | win | 8192, | options | [mss1460,nop,nop,sackOK], | length | 0
30:18.7 | IP | 192.168.10.2.57223 | > | 192.168.20.2.7443 | Flags | [S], | seq | 2083935862, | win | 8192, | options | [mss1460,nop,nop,sackOK], | length | 0

**To Reproduce**
Recent changes:
Configured vlans for explicit deny rules for Inbound ipv4+6 including those reporting issues with above.
Configured vlans for explicit deny rules for Outbound ipv4+6 including those reporting issues with above.

**Expected behavior**
The traffic should be blocked.  As there is an established network for segment 192.168.20.0/24, any traffic with a destination of 192.168.20.0/24 should be routed to this segment and not sent to another interface.  

 

**Screenshots**

**Relevant log files**
_tcpdump_
30:12.7 | IP | 192.168.10.2.57223 | > | 192.168.20.2.7443 | Flags | [S], | seq | 2083935862, | win | 8192, | options | [mss 1460,nop,wscale2,nop,nop,sackOK], | length | 0
30:13.0 | IP | 192.168.10.2.57224 | > | 192.168.20.2.7443 | Flags | [S], | seq | 2854825982, | win | 8192, | options | [mss 1460,nop,wscale2,nop,nop,sackOK], | length | 0
30:18.7 | IP | 192.168.10.2.57222 | > | 192.168.20.2.7443 | Flags | [S], | seq | 3714687900, | win | 8192, | options | [mss1460,nop,nop,sackOK], | length | 0
30:18.7 | IP | 192.168.10.2.57223 | > | 192.168.20.2.7443 | Flags | [S], | seq | 2083935862, | win | 8192, | options | [mss1460,nop,nop,sackOK], | length | 0

_firewall live view_
  | Interface |   | Time | Source | Destination | Proto | Label
  | VPNservice1 |   | 8/31/2020 13:07 | 10.0.0.5:60801 | 192.168.20.2:443 | tcp | let out anything from firewall host   itself (force gw)
  | VLAN1 |   | 8/31/2020 13:07 | 192.168.10.2:58846 | 192.168.20.2:443 | tcp | Allow HTTPS to internet
  | VPNservice1 |   | 8/31/2020 13:07 | 10.0.0.5:6369 | 192.168.20.2:443 | tcp | let out anything from firewall host   itself (force gw)
  | VLAN1 |   | 8/31/2020 13:07 | 192.168.10.2:58845 | 192.168.20.2:443 | tcp | Allow HTTPS to internet
  | VPNservice1 |   | 8/31/2020 13:07 | 10.0.0.5:37938 | 192.168.20.2:443 | tcp | let out anything from firewall host   itself (force gw)
  | VLAN1 |   | 8/31/2020 13:07 | 192.168.10.2:58844 | 192.168.20.2:443 | tcp | Allow HTTPS to internet
  | VPNservice1 |   | 8/31/2020 13:07 | 10.0.0.5:47479 | 192.168.20.2:443 | tcp | let out anything from firewall host   itself (force gw)
  | VLAN1 |   | 8/31/2020 13:07 | 192.168.10.2:58843 | 192.168.20.2:443 | tcp | Allow HTTPS to internet
  | VPNservice1 |   | 8/31/2020 13:07 | 10.0.0.5:62317 | 192.168.20.2:443 | tcp | let out anything from firewall host   itself (force gw)
  | VLAN1 |   | 8/31/2020 13:07 | 192.168.10.2:58842 | 192.168.20.2:443 | tcp | Allow HTTPS to internet
  | VPNservice1 |   | 8/31/2020 13:07 | 10.0.0.5:24285 | 192.168.20.2:443 | tcp | let out anything from firewall host   itself (force gw)
  | VLAN1 |   | 8/31/2020 13:07 | 192.168.10.2:58841 | 192.168.20.2:443 | tcp | Allow HTTPS to internet

**Additional context**

**Environment**
Software version used and hardware type if relevant.
e.g.:

OPNsense 20.7.1-amd64FreeBSD 12.1-RELEASE-p8-HBSD

**Comment by upended** [comment]
This is not a bug?

**Comment by AdSchellevis** [comment]
could very well be a configuration issue, policy based routing for example. a generic routing issue is unlikely as it would influence a lot of people. If at some point in time it turns out that there is a (reproducible) bug, we can easily change the tag.

**Comment by upended** [comment]
Thank you.

**Comment by upended** [comment]
Not a bug.
