### ISSUE TITLE
No logs for OpenVPN client

### ISSUE THREAD

**Issue by jgoerzen** [opnsense/core#4315]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[X] I have searched the existing issues and I'm convinced that mine is new.

**Describe the bug**
I have configured OpenVPN client on my OPNSense 20.7.1 system.  (This problem also was present in 20.7).

Under OpenVPN, connection status shows the connection is up.  Traffic is using it.  But I can't get any logs into the OpenVPN log section.  I have tried increasing verbosity, but it didn't help.

**To Reproduce**
1. Go to VPN -> OpenVPN -> Clients.  Define and enable one.
2. Go to PVN -> OpenVPN -> Log File and observe it's empty.

Downloading the log file results in a 0-byte download.

**Expected behavior**

Starting or restarting OpenVPN should result in log entries.  Neither does.

**Environment**
Software version used and hardware type if relevant.
e.g.:

OPNsense 20.7.1-amd64
FreeBSD 12.1-RELEASE-p8-HBSD
OpenSSL 1.1.1g 21 Apr 2020
Intel(R) Celeron(R) CPU J1900 @ 1.99GHz (4 cores)

**Comment by AdSchellevis** [comment]
duplicate https://github.com/opnsense/core/issues/4263#issuecomment-675431582 ?

**Comment by jgoerzen** [comment]
@AdSchellevis No, I don't think so.  No evidence of that in the logs.  Also syslogd has been up (according to ps) since the system booted.

Also, other logs are working: firewall, unbound, ntpd, etc.  It's only OpenVPN that's not.

**Comment by AdSchellevis** [comment]
ok, just checking, on my end OpenVPN (client) does log normally.

**Comment by jgoerzen** [comment]
I'm happy to do whatever debugging is needed to figure this one out.

**Comment by jgoerzen** [comment]
After upgrading to 20.7.2 tonight, this issue is resolved!

**Comment by fichtner** [comment]
Thanks, closing this then. 😊
