### ISSUE TITLE
pf: tables/aliases exclusions

### ISSUE THREAD

**Issue by kulikov-a** [opnsense/core#4317]
Hi!
pf supports exclusions in tables (eg { 192.168.2.0/24, !192.168.2.5 }) but 
AliasContentField.php and alias.py do not allow to add addresses with exclamation mark.
the idea is to create an Alias (Network(s) type) with subnets to exclude from blacklists and create a merged table (Network group type alias) with blacklist URLTable(IPs) and exclude alias (eg use FireHOL level1 list "cutting" some private subnet from it).
I tried (add "!" sign processing in address validation in php and py files) and it works.
I think it would be great to add this feture to Aliases.
How stupid is this thought?
How difficult is it to add?
Can you add this feature?
Thanks!!

**Comment by AdSchellevis** [comment]
wouldn't that just match all addresses in the world except `192.168.2.5`?

**Comment by kulikov-a** [comment]
no
"table <clients> { 192.168.2.0/24, !192.168.2.5 }
In this example, the 192.168.2.0/24 network is part of the table, except for the address 192.168.2.5, which is excluded using the ! erator. "
https://www.freebsd.org/doc/handbook/firewalls-pf.html
tested with pfctl. working fine with host address and subnets

**Comment by AdSchellevis** [comment]
Best fill in our feature request form (template) in that case, no promises, but it's something we might add in a future version.

**Comment by kulikov-a** [comment]
ok! Thank you!
