### ISSUE TITLE
There is no API function to drop current connections after calling reconfigure alias API function

### ISSUE THREAD

**Issue by Actpohomoc** [opnsense/core#4319]
I think that absence of this feature is **security bug** of the OPNsense  firewall.

If I using API function to change firewall alias that rules access to my inside network I have to be sure that all current connections dropped after calling reconfigure function.

I proposed the solution here (https://github.com/opnsense/core/pull/4316)
After discussion my PR was closed with reason (https://github.com/opnsense/core/pull/4316#issuecomment-685851713) 

Please vote for this feature by adding your comment here.
Hope that everybody can find my PR to correct the security bug if using API to reconfigure aliases.
I am using it in telegram bot to update host alias of remote access to my network in very fast way.

**Comment by fichtner** [comment]
My two cents: you are asking for a feature. Claiming "security bug" is a bit of a stretch. Do you know of CVEs assigned to similar issues in other software? Can you give more insights on your thread model?

**Comment by Actpohomoc** [comment]
> My two cents: you are asking for a feature. Claiming "security bug" is a bit of a stretch. Do you know of CVEs assigned to similar issues in other software? Can you give more insights on your thread model?

We have API to reconfigure firewall rules. But all existing connections will be continue to work. So if you have someone who are already in your system and you want quickly remove his connection - you can't. You have to manually login in to your system and kill sessions manually. 

Maybe claiming "security bug" is just to attract attention to the problem. 

Now I can see KILL buttons on the states page. This may help. 
But If someone find your admin password using the API calls can be the only way to help.
