### ISSUE TITLE
refresh_aliases() fails with "Invalid argument"

### ISSUE THREAD

**Issue by fraenki** [opnsense/core#4321]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[x] I have searched the existing issues and I'm convinced that mine is new.

**Describe the bug**
After updating from 20.1.9 to 20.7.2 applying/reloading the existing list of aliases leads to the following error:

```
Sep  4 01:04:58 opnsense configd.py[96512]: message 0b886246-4e61-4845-9bb4-2e67cafbf070 [filter.refresh_aliases] returned {"status": "error", "messages": ["Invalid argument."]}    
```

I would like to track down this error, but the log does not contain enough information to do so. How could I get more (debug) output or find the (supposedly) broken alias?

**Expected behavior**
Reload/apply aliases without an error. If this fails, the log should contain the ID or name of the alias that fails.

**Relevant log files**
```
Sep  4 01:04:58 opnsense configd.py[96512]: message 0b886246-4e61-4845-9bb4-2e67cafbf070 [filter.refresh_aliases] returned {"status": "error", "messages": ["Invalid argument."]}    
```

**Additional context**
The problem first appeared on 20.7.x, the same list of aliases worked fine on 20.1.4 for quite some time. However, this installation is ~5 years old, so new/better alias validations might have hit me this time.

**Environment**
OPNsense 20.7.2 (amd64, OpenSSL).

**Comment by AdSchellevis** [comment]
It should be a pfctl error:
https://github.com/opnsense/core/blob/80696b3be7cf3f1d16d418e438b9bc8978e0435f/src/opnsense/scripts/filter/update_tables.py#L167-L172


can you try https://github.com/opnsense/core/commit/abcb23703fd2d534e6b5ba6f9c538760e35a3e3e ?  It should append the alias name in the message.

**Comment by fraenki** [comment]
@AdSchellevis, thank you, the error in the GUI contains the alias name. Thanks!
However, I've noticed that `configd.log` does no longer contain the error message after applying the patch. Is this expected?

**Comment by AdSchellevis** [comment]
not really, no, I haven't changed anything in that area.

**Comment by fraenki** [comment]
FWIW, the alias that lead to the "invalid argument" error was a GeoIP alias. Editing and saving did not change anything. I've then added a new GeoIP aliases and suddenly the error was gone. :)
