### ISSUE TITLE
select outgoing gateway/interface for traffic originating from opnsense itself / rules for loopback?

### ISSUE THREAD

**Issue by igpit** [opnsense/core#4322]
OPNsense 20.7.2-amd64

**use case**
run speedtest (Ookla CLI version) from opnsense itself. 
ideally using "-I \<interfaceName\>" to select outgoing interface to test. 
alternatively configure through UI where/how traffic will leave opnsense. 

**setup**
2 DHCP-WAN interfaces. configured 2 gateway groups preferWan1, preferWan2. 
wan1 is the default gateway. 
installed Ookla speedtest CLI version on console. 

**my findings so far**
- traffic from speedtest running in opnsense shell uses the default gateway as seen in "netstat -rn4"
- when using "-I wan2" i see in firewall live view, that packets leave opnsense through wan1 but the source address is from wan2. thus replies are received on wan2 but get then dropped by default deny rule (ofc - they are no reply on that interface)
- workaround: add a static route to routing table to talk to desired server through wan2 , works. 
- looked at involved DNS requests, they originate from loopback to running dnsmasq server. 
- the actual traffic itself is NOT visible on loopback - should it? so it is sent from wan address directly? 
- using "-I lo0" or "-i 127.0.0.1" has no efffect, not visible in loopback live view. 

**question**
- how can traffic originating from some process on opnsense be directed to some gateway/interface? through rules in the UI?
- as the traffic does apparently not originate from loopback, a rule in loopback does not match, thus setting a gateway group there does not help
- rules for wan1/wan2 will only apply after a interface has already been selected?

**Comment by mimugmail** [comment]
When a local process initiates a connection, the default gateway is always used. If you have PBR or loadsharing, you can try to set your LAN IP as a source, this sometimes works.
