### ISSUE TITLE
pppoe: IPv6 single gateway gets created and configured with link local address, while IPv6 configuration type=none

### ISSUE THREAD

**Issue by igpit** [opnsense/core#4324]
OPNsense 20.7.2-amd64

configure a pppoe interface to use configuration types IPv4 DHCP, IPv6 None. 
connect pppoe.
notice: Single gateway with IPv6 link local address is created. 

expected: only IPv4 gateway.

**Comment by bitcmacleod** [comment]
I'm also experiencing this same issue - is there no resolution to this?
