### ISSUE TITLE
Multi-WAN + IPsec Blocks each other

### ISSUE THREAD

**Issue by Thalooka** [opnsense/core#4326]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[X] I have searched the existing issues and I'm convinced that mine is new.

**Describe the bug**
WAN1 (DHCP) this interface is used with IPsec
WAN2 (PPPOE) this interface is used in the same Balance GW as WAN1 (all works fine till IPsec is enabled)

The Bug/Problem comes up instant after adding IPsec then either the IPsec or the WAN2 GW cant be enabled anymore.
Both MultiWan as like IPsec (Site to Site to another OPNsense) are configured by offical guides.
It seems like the routes dont work since nothing is Blocked via Firewall but when i check the routed all is fine.

revert tested, no fix sadly

**To Reproduce**
1. Configure Multiwan with one DHCP n one PPPOE
2. Configure Firewall Rules to use just one WAN n not the balanced GW Group
3. Configure IPsec n Firewall
4. See either IPsec or PPPOE not working

**Expected behavior**
Both working IPsec and PPPOE

**Relevant log files**
Logs dont show any error, all seems fine there but every reboot its random whats working PPPOE WAN or IPsec

**Environment**
Software version used and hardware type if relevant.
e.g.:

OPNsense 20.7.2 (amd64, OpenSSL).
Intel(R) Atom(TM) CPU C2558 @ 2.40GHz (4 cores)

**Comment by Thalooka** [comment]
So i tested a few things n it seems to be linked to either pppoe or gateway of pppoe since when i disable it ipsec starts after a reboot but the gateway cant be enabled anymore

**Comment by mimugmail** [comment]
This all doesnt really makes sense. Screenshots of IPsec Phase1 and 2, Gateways, Gateway groups and Rules Tabs

**Comment by Thalooka** [comment]
so i used the gui to report the problem maybe there are more configs in that.
First off this is my ipsec conf, its just dif for ip n nets on the hosts:
![ipsec phase1 local](https://user-images.githubusercontent.com/15342014/92333234-4e67db80-f084-11ea-85c1-ac006a0f1162.JPG)
![ipsec phase2 local](https://user-images.githubusercontent.com/15342014/92333227-4c058180-f084-11ea-9727-0ccd211a5e7c.JPG)
![ipsec connected](https://user-images.githubusercontent.com/15342014/92333232-4dcf4500-f084-11ea-84a1-30450c3d9349.JPG)
![ipsec firewall rules](https://user-images.githubusercontent.com/15342014/92333233-4dcf4500-f084-11ea-9e7d-a6fa24ad2233.JPG)
With this all IPsec shows connected but as long as WAN2_PPPOE is online i cant ping anything from there for example 10.200.0.1 the firewall interface. It looks like this:
![gateways group before reboot](https://user-images.githubusercontent.com/15342014/92333229-4c9e1800-f084-11ea-8f69-ed5d768ed5f4.JPG)
![gateways single before reboot](https://user-images.githubusercontent.com/15342014/92333231-4d36ae80-f084-11ea-8464-50aa17e6f88a.JPG)
However after i reboot IPsec works like a charm i can ping i get to all services in the lan on the other site n so on, sadly WAN2 cant be enabled anymore n shows defunct all time no matter what i try to reenable it i will stay "disabled defunct"
![gateways single after reboot](https://user-images.githubusercontent.com/15342014/92333230-4d36ae80-f084-11ea-8ab7-1f5839e63119.jpg)

i even tried delete full wan2 n then rebuild it since i though maybe its a config fail by myself but same errors then.

**Comment by Thalooka** [comment]
So further error testing from me i can enable wan2_pppoe if i disable auto gen rules in ipsec (log shows it goes on WAN2 to set the routing) when i then enable wan2_pppoe it comes up and runs but gets packetloss and additionally the ipsec network is not reachable anymore even when adding a manual rule with the right interface

**Comment by Thalooka** [comment]
@mimugmail anything else needed to check whats the bug here?
sry for the bad eng im from germany actually^^

**Comment by mimugmail** [comment]
WAN_PPPOE should be priority 2 and not equal to 1

**Comment by Thalooka** [comment]
@mimugmail just a quick reply, thanks a lot for this information seems like i gotta learn much since i didnt knew this had such an impact.
i changed the priority, after that it didnt work i had to reboot but then all worked, could i just ask out of curiosity why when i set both to 1 why it always takes the pppoe and disables the gateway completely?
"Priority | Prioritizes this gateway, a lower value means more important." i though of this like when i got two wan's with same speed to give them same priority.

thanks a lot since this simple comment fixed the problem i had trouble for near two days now 🥇 i wish a happy day!

**Comment by mimugmail** [comment]
The priority sets the default gateway of the system itself and all it's services (like Ipsec). There can only be one active at a time and when you have two with the same priority it's unpredictable what happens. 

The loadbalancing via Groups are totally different as this only affects traffic going THROUGH the firewall (not IPsec since this is locally initiated). 

Hope this makes it bit clearer.

**Comment by Thalooka** [comment]
ah great thanks for the competent help! will close the issue since its fixed now
