### ISSUE TITLE
pfInfo: show loaded nat and rdr rules

### ISSUE THREAD

**Issue by kulikov-a** [opnsense/core#4331]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[-] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[-] I have searched the existing issues and I'm convinced that mine is new.

**Is your feature request related to a problem? Please describe.**
at this moment there is no way to see the summary of currently loaded nat and rdr rules (pfctl -vvsnat)
in the Firewall-Diagnostics-pfInfo menu.
only currently loaded filter rules (pfctl -vvsrules).
it would be convenient to review the nat and rdr rules sometimes

**Describe the solution you'd like**
add "Nat" tab to pfInfo page
https://github.com/opnsense/core/pull/4330

**Describe alternatives you've considered**

**Additional context**

**Comment by AdSchellevis** [comment]
@kulikov-a thanks for taking care of this yourself. Your PR was just merged.
