### ISSUE TITLE
Request to add IPv6 OpenDNS resolvers to OpenDNS configuration

### ISSUE THREAD

**Issue by StopTrain** [opnsense/core#434]
Setting up OpenDNS for the first time on OPNsense and all is working, but I noticed it is only showing their IPv4 resolvers.   Researched and found they do have IPv6 addresses as well.

Link to the article:
https://support.opendns.com/entries/26056194-Does-OpenDNS-support-IPv6-

The addresses are:

2620:0:ccc::2 
2620:0:ccd::2

Thank you!

**Comment by sjorge** [comment]
:+1: on this

**Comment by StopTrain** [comment]
Totally agree.  IPv6 is really making people realize they are behind :+1:
