### ISSUE TITLE
[Bug/Q] Trying to find Secure Shell / SSH settings with the search box does not return anything

### ISSUE THREAD

**Issue by TheNec** [opnsense/core#4343]
[x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[x] I have searched the existing issues and I'm convinced that mine is new.

**Describe the bug** // **To Reproduce**
Type in ssh or secure or shell in the search box does not find 'System' - 'Settings' - 'Administration' -> 'Secure Shell' or anything else // I just found out that this also happens with other search terms for settings. Is it indended that you can only find menu items there?

**Expected behavior**
Show 'System' - 'Settings' - 'Administration' - 'Secure Shell'

**Environment**
Recent stable OPNsense (amd64, LibreSSL) but happened in older versions, too.

**Comment by AdSchellevis** [comment]
Yes, it’s intended. we only offer menu item search, specific features, either legacy or new style mvc are not indexed. This would require another contextual layer in the menu structure.

**Comment by TheNec** [comment]
Thanks for your response!

Maybe this should be a medium or long-term change to full text search. To be honest. I never use the search box. Except for one or two times a year when I want to use SSH but then I do not find anything unless clicking manual through the entire settings. =)

Het beste uit Duitsland :)
