### ISSUE TITLE
[Q] Roadmap for 21.1 still missing / Friendly reminder / No ETA ;)

### ISSUE THREAD

**Issue by TheNec** [opnsense/core#4344]
[x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[x] I have searched the existing issues and I'm convinced that mine is new.

I do not want to put pressure on anyone and maybe someone has just forgotten it or it's not yet time for that but the roadmap at https://opnsense.org/about/road-map/ is missing informations about Mickey Mouse... or was it Mysterious Manatee? =)

**Comment by AdSchellevis** [comment]
It’s on the list of things todo, no need for a tracking issue. Likely at the end of the month a first version will be online.
