### ISSUE TITLE
[Bug/FReq] Search box is missing on tablet in portrait mode even if there is enough space for it

### ISSUE THREAD

**Issue by TheNec** [opnsense/core#4345]
[x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[x] I have searched the existing issues and I'm convinced that mine is new.

**Describe the bug**
On tablet in portrait mode there is no search box visible and I don't know if this is intended (FReq) or not (Bug)

**Expected behavior**
Search box is available if there is enough space for it

**Environment**
Tablet 10.1", 1200x1920px (portrait mode), recent firefox stable 80.1.2 but also happened in older versions

**Comment by AdSchellevis** [comment]
Our forum is a better place to ask questions and discuss possible options, you can find it at https://forum.opnsense.org

**Comment by fichtner** [comment]
When you see the minified menu bottom at the top there will be no additional information in the title bar other than the minified logo. Since there is no screenshot that is just a guess.


Cheers,
Franco

**Comment by TheNec** [comment]
Thanks for your responses!

In the row where the Home and Menu buttons are located would be enough space for the search box as like in other views.

***

![Screenshot_20200913-183727](https://user-images.githubusercontent.com/6561415/93023709-0d764680-f5f1-11ea-8a9b-7f5d0e5ee431.jpg)

***

Grüßle =)
