### ISSUE TITLE
Fresh Install, GUI looses WAN gateway address

### ISSUE THREAD

**Issue by gauthig** [opnsense/core#4347]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[-] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[-] I have searched the existing issues and I'm convinced that mine is new.

**Describe the bug**
Fresh install (tried 4 times, 2 as VM and 2 on bare metal).  
After first reboot on the console interface I assign interface and IP addresses.
After assigning IP's and setting gateway address for WAN interface, I run the console cli first update and version 20.7.2 get loaded.
Next reboot - go to the LAN GUI IP and the wizard starts, when page: System: Wizard: Configure WAN Interface is displayed, the correct WAN IP is already in the box but the WAN gateway is blank.  

**To Reproduce**
Either repeat install or reset config to default, same results will occur. 

**Expected behavior**
If the WAN IP and Gateway are setup form the console, it should also be in the wizard GUI.

**Environment**
Software version used and hardware type if relevant.
20.7 amd64 ISO install

**Comment by fichtner** [comment]
Thanks for the report. The shell gateway name was not aligning with the proper naming schema.


Cheers,
Franco
