### ISSUE TITLE
Selection possibility for multiple LDAP servers while initiating an import

### ISSUE THREAD

**Issue by gjduran** [opnsense/core#4349]
While defining multiple LDAP servers only the first one as defined in config.xml shows up while opening the import window. To show a second or another server one need to manipulate the order in config.xlm which is doable but not very convenient. In case more than one LDAP server has been defined a selection window of available LDAP servers prior to the "system_usermanager_import_ldap.php" window would solve this issue (or a toggle function in the latter one).

**Comment by gjduran** [comment]
Hi Ad, Could you please explain why this feature request has been labeled incomplete?

**Comment by gjduran** [comment]
Hi Ad, Could you please explain why this feature request has been labeled incomplete?

**Comment by gjduran** [comment]
Hi Ad, Could you please explain why this feature request has been labeled incomplete?

**Comment by gjduran** [comment]
Hi Ad, Could you please explain why this feature request has been labeled incomplete?

**Comment by mimugmail** [comment]
Because you didnt use the template (and one time asking is enough)

You can use HAProxy as a workaround which can handle failover and loadsharing really nice

**Comment by gjduran** [comment]
Thanks for your response however, I do not understand how HAProxy could be used to work around the issue as described. 
Here's the missing template with answers:

**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[-] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
**[Yes I did.]**
[-] I have searched the existing issues and I'm convinced that mine is new.
**[Yes I did.]**
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
**[Stated in my first submission.]**

**Describe the solution you'd like**
A clear and concise description of what you want to happen.
(e.g. I would like an input field in the `/ui/firewall/alias` which would add .... to ....)
**[Stated in my first submission.]**
**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've considered.
**[Stated in my first submission.]**

**Additional context**
Add any other context or screenshots about the feature request here.

**Comment by mimugmail** [comment]
Ah, OK, you want to handle different servers with different users and handle them like tenants. I fear that this was never in project scope. No idea how easy this would be when it comes to server selection during authentication

**Comment by AdSchellevis** [comment]
I don't think we're going to this this, eventually it would probably be better to import users on the fly after successful login 

https://github.com/opnsense/core/blob/ecfd53ac2f60c6abd259702ed9e183acef967ea3/src/opnsense/mvc/app/library/OPNsense/Auth/LDAP.php#L478-L482

**Comment by gjduran** [comment]
@ mimugmail: Yeah, that's indeed the intention as I have multiple tenants to serve using different LDAP instances. Looking into the PHP code (system_usermanager_import_ldap.php) it doesn't appear that difficult to achieve but that's maybe because I need it to use with OpenVPN and there I can select the LDAP server per user and that works. I don't want these users to have access to OPNsense anyway or are there other login needs I may overlook? But I believe the dn is already stored with the user so an extra field to what LDAP server the user belongs might be an option to make the appropriate selection at all times. 
@  AdSchellevis: User creation is a whole different story and I don't see the need for that as LDAP in general is serving a whole lot of other needs and converting OPNsense into a LDAP manager may be a little over the top.

**Comment by AdSchellevis** [comment]
doing an import is the same as creating users (within the login sequence).... when trying to import from multiple sources things tend to complicate quite quickly, in most situations one would like to manage the privileges within ldap any way (it's usually the next question, which ,when the user exists, is already supported).

**Comment by gjduran** [comment]
@ Ad: your last comment appears quite cryptic to me. 
I don't understand;:
>  (within the login sequence)
It's obvious that things may get complicated but that's the challenge isn't it?
Maybe I'm just too selfish while looking into my own use case. Within that scope I don't think it's over complicated but I have to admit that I have not looked into other use cases than OpenVPN. I'm fine for now just editing the config.xml manually as that works fine for my needs.

**Comment by gjduran** [comment]
@ Ad: your last comment appears quite cryptic to me.
I don't understand: "(within the login sequence)"
It's obvious that things may get complicated but that's the challenge isn't it?
Maybe I'm just too selfish while looking into my own use case. Within that scope I don't think it's over complicated but I have to admit that I have not looked into other use cases than OpenVPN. I'm fine for now just editing the config.xml manually as that works fine for my needs.

**Comment by AdSchellevis** [comment]
for OpenVPN itself you don't really need to import the users if you can use extended queries (https://docs.opnsense.org/manual/how-tos/user-ldap.html ). The import is required to use the local group policies. 

When a local link (a user record) is required, from a management perspective it would be most convenient if these where created on initial successful attempt, which is how it can work for group synchronisation nowadays. Trying to import users from multiple sources is just not something we're aiming for at the moment (also would work, but the current option already isn't great in my opinion, still legacy style code for example and can't cope very well with large datasets if I remember correctly).

**Comment by gjduran** [comment]
Hello Ad,

> for OpenVPN itself you don't really need to import the users
If I understand right from your comment,  for OpenVPN there is no need to import or add local users in System: Access: Users.
If this is the case than I wonder how to configure users in OpenVPN. Should I put the LDAP dn in the username field? And if so will OPNsense poll all available LDAP servers to authenticate?

**Comment by gjduran** [comment]
Hello Ad,
If I understand right from your comment, for OpenVPN there is no need to import or add local users in System: Access: Users.
If this is the case than I wonder how to configure users in OpenVPN. Should I put the LDAP dn in the username field? And if so will OPNsense poll all available LDAP servers to authenticate?

**Comment by fichtner** [comment]
In general you use the remote LDAP as the authentication backend for the OpenVPN server. That's enough for "Remote access (User Auth)" mode.
