### ISSUE TITLE
Interface to Modem fails to start after reboot

### ISSUE THREAD

**Issue by WombatHollow** [opnsense/core#4351]
**Describe the bug**

The ethernet interface to a DWM312 Dlink LTE modem fails to to restart after a reboot of OPNSense.

Can be manually restored by either disabling that interface in opnSense/interface and re-enable, or unplugging ethernet cable and reconnecting.  But as this system is unmanned, it is not always practical (and missing internet access means not possible remotely connect and rectify).

1.  The DWM312 is in Bridge mode and its web interface is normally accessible on 192.168.0.1 from internal network (10.0.0.0/24), but this web interface is also lost after reset.

2.  A previous Netgear LB2120 modem did not exhibit this behavior (Modem removed due to internal LTE failure...and Netgear poor support) with OPNSense 20.1.7.

3.  A separate interface to a Netgear 7000 series ADSL modem also in bridge mode(PPPoE) does not exhibit problem.  But this internet connection is being removed due to performance/cost issues.

3. Problem observed with OPNSense  20.1.7, 20.7.0 and 20.7.2.

**Expected behavior**
After OPNSense report, the interface should return to operating without external intervention

**Environment**

OPNSense 20.7.2 amd64
Intel(R) Core(TM) i5-2500 CPU @ 3.30GHz (4 cores)
Ethernet 2 x Intel quad port card (used by LAN) plus 1 Gigabyte Motherboard Ethernet (used by Modem)

**Comment by mimugmail** [comment]
Anything in the console while rebooting?
