### ISSUE TITLE
Services: Unbound DNS: Miscellaneous does not get synced to backup firewall

### ISSUE THREAD

**Issue by sorano** [opnsense/core#4352]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[X] I have searched the existing issues and I'm convinced that mine is new.

**Describe the bug**
When you run OPNsense in High Availability any changes made under Services: Unbound DNS: Miscellaneous does not get synced to backup firewall when you run Synchronize config to backup.

Affects both Private Domains and  DNS over TLS Servers.

If I'm not mistaken the Miscellaneous section was added in 20.7 so no earlier version to test against.

**To Reproduce**
1. Go to Services: Unbound DNS: Miscellaneous and input your config.
2. Click on System: High Availability: Status and start Synchronize
3. Check your standby host.
4. See error that none of your Unbound DNS: Miscellaneous config gets synced to the standby host.

**Expected behavior**
Both Primary and Standby host should have same configuration after sync.

**Environment**
OPNsense 20.7.2-amd64
FreeBSD 12.1-RELEASE-p9-HBSD
OpenSSL 1.1.1g 21 Apr 2020
--

**Comment by AdSchellevis** [comment]
https://github.com/opnsense/core/commit/09f82165593b065c016b79ba34f16be922509684 should do the trick.
