### ISSUE TITLE
Disabled LAN cannot be reenabled due to DHCPv6 Server is active.

### ISSUE THREAD

**Issue by miodzicho** [opnsense/core#4353]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[-] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[-] I have searched the existing issues and I'm convinced that mine is new.

**Describe the bug**
I disabled LAN interface and cannot reenable it back due to error : The following input errors were detected:

The DHCPv6 Server is active on this interface and it can be used only with a static IPv6 configuration. Please disable the DHCPv6 Server service on this interface first, then change the interface configuration.
DHCPDv6 is disabled

**To Reproduce**
1. disable LAN interface, apply and save
2. enable LAN, see error

**Expected behavior**
LAN interface reenabled

**Environment**
Software version used and hardware type if relevant.

OPNsense 20.7.2-amd64
FreeBSD 12.1-RELEASE-p8-HBSD
OpenSSL 1.1.1g 21 Apr 2020

**Comment by marjohn56** [comment]
At the bottom of the LAN configuration page is an option for manual configuration. Select that and save. Once you have done that you can go to the dhcpv6 services and disable the server for the LAN. Once disabled there you can now turn off the manual configuration option in the LAN, apply and save and that should see you OK.

**Comment by miodzicho** [comment]
This solved issue, thank you.

**Comment by marjohn56** [comment]
OK, please close this issue.
