### ISSUE TITLE
"Reverse token order" help text is incorrect

### ISSUE THREAD

**Issue by bobpaul** [opnsense/core#4354]
**Problem**
Under System ‣ Access ‣ Servers ‣ Add the `Local + Timebased One Time Password` option offers an option "Reverse token order" which is described as "Require the password in front of the token instead of behind it." 

Reading this description, it sounds like checking the box will require the token in front of the password and leaving the box unchecked will require the token behind the password. However, it's the opposite.

**Proposed Fix**
I propose changing the text to "Checking this box requires the token after the password. Default requires the token in front."

-----

I assume this problem also affects `LDAP + Timebased One Time Password`, but I don't have an LDAP server handy to test with.

**Comment by fichtner** [comment]
A number of years with this like so. Are you sure?

**Comment by mimugmail** [comment]
@bobpaul please double check in your side

**Comment by bobpaul** [comment]
@mimugmail I just set this up last night for the first time. I found the help text a bit ambiguous so I wasn't surprised when it didn't work as I initially expected. When the box is checked, OTP goes after password. When the box is unchecked, OTP goes before the password. It behaves the same both through System ‣ Tester as well as when logging in with an OpenVPN client.

----

The [Road Warrior guide ](https://docs.opnsense.org/manual/how-t
os/sslvpn_client.html) is even written with the assumption that NOT checking the box results in typing your OTP code before the password. Since the guide is old, this behavior has clearly been like this for a long time and changing the help text is the best solution as it won't break existing systems.

> Now first change the Type to Local + Timebased One time Password Enter a Descriptive name such as TOTP VPN Access Server

> For our example we leave everything else default as we will be using Google’s Authenticator and the defaults are correct for that.

Leaving everything default leaves the box unchecked.

> **Connect & login**

> In the password field enter your TOTP token first followed by your password.

**Comment by fichtner** [comment]
I agree the text can be improved. I don't agree with rewriting the sentence in a way that makes sense to you leaving all the other people who apparently understood this for the last few years. First of all we have to agree that the current text isn't actually wrong as you implied. Then we can work on a better wording.

**Comment by marjohn56** [comment]
It should be 'before' and 'after' not 'in front' or 'behind'

i.e. 'The cat is asleep on the dog'

In the above sentence, the word 'cat' is before 'dog', not in front of it, and 'dog' is after 'cat' not behind it. You read left to right, not front to back... that is of course unless it's arabic then it's all out of the window. :)

**Comment by bobpaul** [comment]
@fichtner I modeled the new text after the help text on other checkboxes I saw in OPNSense. Generally speaking, the text should describe what happens when the box is checked. The current text describes what happens when the box is unchecked. The proposed text is intended to make it very clear what happens when the box is checked and when the box is unchecked.

@marjohn56 I like that suggestion.
