### ISSUE TITLE
Api support for vlan / interfaces 

### ISSUE THREAD

**Issue by thomasfinstad** [opnsense/core#4355]
There is currently no programmatic way to add, update, remove interfaces, specifically vlans, via the api. 

Now that the new firewall api plugin let's us use the api to manipulate the firewall rules, an api for vlans would empower us to automatically create entire network segments via the api.

**Comment by gratuxri** [comment]
API for settings would be nice as well, e.g. enabling ssh, set hostname and domain, ...
