### ISSUE TITLE
DHCP - Dynamic DNS Registration - No zone for DNS domain of additional pool in dhcpd.conf

### ISSUE THREAD

**Issue by FromageBlue** [opnsense/core#4356]
**Describe the bug**
Configured a DHCPv4 service for an interface via the WebUI (services_dhcp.php) and added a Dynamic DNS configuration that updates a DNS zone (mydomain.com) on an external DNS server.
When adding an additional pool which also has a Dynamic DNS configuration that updates a different zone (qa.mydomain.com) on the same external DNS server, DNS updates are done on mydomain.com and not qa.mydomain.com

In /var/dhcpd/etc/dhcpd.conf, the zone declaration for the dynamic DNS domain associated with the Dynamic DNS configuration of the additional pool (i.e. qa.mydomain.com) does not get created. We should see:
zone qa.mydomain.com. {
primary 10.2.0.100;
key ddns-router;
}
but we don't.
To make this explanation simple, I posted in log section my /var/dhcpd/etc/dhcpd.conf from my opensense.

**To Reproduce**

   1. Go to Services: DHCPv4: [interface]
   2. Configure DHCP.
   3. Enable registration of DHCP client names in DNS to mydomain.com
   4. Configure additional pool with registration of DHCP client names in DNS to qa.mydomain.com

**Expected behavior**
Clients that are part of the additional pool should have there domain name registered to the qa.mydomain.com zone.

**Screenshots**

**Relevant log files**
**_/var/dhcpd/etc/dhcpd.conf_**
option domain-name "mydomain.com";
option ldap-server code 95 = text;
option arch code 93 = unsigned integer 16; # RFC4578
option pac-webui code 252 = text;
option custom-opt5-0 code 121 = string;

default-lease-time 7200;
max-lease-time 86400;
log-facility local7;
one-lease-per-client true;
deny duplicates;
ping-check true;
update-conflict-detection false;
authoritative

subnet 10.2.64.0 netmask 255.255.248.0 {
pool {
option domain-name-servers 10.2.0.100,10.2.0.101;
deny members of "A6AAA4";
ddns-update-style interim;
range 10.2.65.1 10.2.71.250;
}

pool {
option domain-name-servers 10.2.0.100,10.2.0.101;
option domain-name "qa.mydomain.com";
ddns-domainname "qa.mydomain.com";
ddns-update-style interim;
range 10.2.71.251 10.2.71.254;
}

option routers 10.2.64.1;
option domain-name "mydomain.com";
option domain-search "qa.mydomain.com","mydomain.com";
ddns-domainname "mydomain.com";
option domain-name-servers 10.2.0.100,10.2.0.101;
option netbios-name-servers 10.2.0.100;
option netbios-node-type 8;
option ntp-servers 10.2.0.100,10.2.0.101;

next-server 10.2.1.107;
filename "/pxelinux.0";
}
ddns-update-style interim;
update-static-leases on;
key ddns-router {
algorithm hmac-md5;
secret REMOVED;
}
zone mydomain.com. {
primary 10.2.0.100;
key ddns-router;
}
zone 64.2.10.in-addr.arpa. {
primary 10.2.0.100;
key ddns-router;
}

**Additional context**

**Environment**
OPNsense 20.7.1-amd64
FreeBSD 12.1-RELEASE-p8-HBSD
OpenSSL 1.1.1g 21 Apr 2020

**Comment by AdSchellevis** [comment]
https://github.com/opnsense/core/pull/4370  merged, @FromageBlue thanks for looking into this. tried your patch on my end with some random values and inspected the configuration, seems to result in a parsable configuration, we'll try to add this into one of our next minor releases.

**Comment by fichtner** [comment]
@FromageBlue A bit baffled about this I looked where we might have lost this working code but it seems it was never properly implemented. Thanks for the find! :)
