### ISSUE TITLE
radvd advanced configuration limits maximum MTU to 8192

### ISSUE THREAD

**Issue by sbuzonas** [opnsense/core#4359]
**Describe the bug**
There is a unexplained limit of 8192 on radvd advanced configuration:
https://github.com/opnsense/core/blob/d727353c25605bad41e376da2f4394bd98259b11/src/www/services_router_advertisements.php#L139

**To Reproduce**
1. Go to 'Router Advertisements > [LAN]'
2. Click on 'Advanced Configuration'
3. Set MTU to a value larger than 8192, e.g. 9180
4. Click on 'Save'
5. See error

**Expected behavior**
The AdvLinkMTU should be permitted to set between IPv6 minimum of 1280 up to and including the MTU for the interface.  

**Additional context**
AFAIK the current limit in the kernel is 16110, but that may change as new hardware introduces larger values.

**Environment**
OPNsense 20.7.2-amd64
FreeBSD 12.1-RELEASE-p8-HBSD
LibreSSL 3.1.4

**Comment by AdSchellevis** [comment]
it was introduced here https://github.com/opnsense/core/commit/e85557938c30d3c71e698c1cf88bdfaebc422972 https://github.com/opnsense/core/pull/4064 at a first glance I would expect 8192 is the default max, but the network driver might support bigger.  

https://github.com/freebsd/freebsd/blob/8da0425cac925384e84381ca4cb1810a04523c0c/sys/net/ethernet.h#L390

Since our interface page caps at 9214 (https://github.com/opnsense/core/commit/13f8ba23478e6b3f7cbfc17f594284f2bd3f1b81), I wouldn't mind setting both to the correct maximum, but we probably need a reference somewhere to prevent the same question at a later point in time,
https://github.com/opnsense/core/blob/58e3c456554284f88329af19a45c517a6b87d300/src/www/interfaces.php#L883-L887

**Comment by fichtner** [comment]
How much is enough? :)

If 9214 is ok for this particular use case we should probably use that value and the next time we find MTU of 9214 is not enough we can grep for all values...

**Comment by sbuzonas** [comment]
I think in this case, it's invalid to advertise a link MTU larger than the interface MTU.  If the max was obtained by whatever is set on the interface you wouldn't need to update multiple maximums.  The default value if unset gets the interface MTU as is, and works as expected.

The 16110 number is from the e1000 readme https://github.com/freebsd/freebsd/blob/master/sys/dev/e1000/README#L175

**Comment by fichtner** [comment]
The sky is the limit then. Remove the check you suggest? We won't be reading interface MTU for service configuration to validate this at run time.

**Comment by stumbaumr** [comment]
The MTU is limited by each MTU of all the devices on the path between the source and the destination. If a switch on the path only supports a MTU of 9000 it does not help that the network card supports 16110...

**Comment by sbuzonas** [comment]
@stumbaumr I don't understand the statement there.  For the subnet in question, I'm running on a hypervisor in a VM to VM net with MTU of 12148 for that broadcast domain (iSCSI).  There's a veth on the same link dedicated for off-link communication which is SLAAC from the radvd. I have my OPNSense MTU on that domain set to 9188 for encapsulation overhead going off-host, but I want to advertise 9180 to leave room for UDP encapsulation if necessary for some destinations.

Sure, you certainly want your MTU to be under the max MTU of any switching infrastructure within the broadcast domain.  But for the most part, when you need to reduce your frame size to traverse though such a switch, you use a stateful gateway that clears the DF bit and fragments/reassembles and keep that lower MTU off link.

**Comment by stumbaumr** [comment]
@sbuzonas You are correct, I did not make myself clear. My statement was intended to make clear that an upper limit check is dependant on the switching infrastructure and destinations surounding the OPNsense - for which the OPnsense has no knowledge about.

Therefore an upper limit check should be removed.

**Comment by fichtner** [comment]
Hmm, I don't fully agree with removing the upper bound. We probably have a hard limit anyway imposed by the TCP/IP stack, but in general it means we raise it quite a bit to allow for all possible use cases.

**Comment by AdSchellevis** [comment]
Which kind of brings this back to the original question, is there a proper upper bound defined anywhere so we can force the same value in all cases. These values have a risk of dropping in the same discussion again at a later point in time. In reality there are probably not a lot of installations where a value higher than 9000 is used anyway.
Super jumbo frames seem to reach up to 64k (https://en.wikipedia.org/wiki/Jumbo_frame#Super_jumbo_frames), but I wouldn't be surprised if most of the drivers around only support mtu sizes below 10k.

Removing the limit or setting an arbitrary one will cause noise at a later point in time with the risk of starting this discussion again. Personally I don't mind changing the maximum value, but given the time spend on these types of tickets by all of us, I really want to avoid tripping into this next year again.

**Comment by fichtner** [comment]
It’s already causing a lot of noise so I think the discussion is valid either way 😉

**Comment by AdSchellevis** [comment]
I agree it's a valid discussion, my remarks are only about the eventual conclusion, which should be clear and avoid future discussions.

**Comment by fichtner** [comment]
A near theoretical limit of 64k is probably best to retain some form of validation although highly improbable. Anything lower will wake this question again in the future. What do you think?

**Comment by AdSchellevis** [comment]
I'm afraid 64k will indeed be the limit even if 99% of the drivers won's support it. a loopback uses 16k by default for example and can be set to a maximum of 65535.

**Comment by stumbaumr** [comment]
According to https://tools.ietf.org/html/rfc791 the official maximum MTU is 65535. People adjusting the MTU normally know what they are doing. Jumbo Frames are in the range over 1500 and Super Jumbo Frames are over 9000 up to 64.000 . IP over Infiniband (IPoIB) is at a MTU of 64K in connected mode. MTU sizes within the data center will go up to that maximum eventually.

So yes, if you do not want this discussion ever again go for an upper limit of 64K (65535).

**Comment by AdSchellevis** [comment]
ok 65535 it is https://github.com/opnsense/core/commit/5f108f698ead6cbdfa287038d84e723037a7258c
