### ISSUE TITLE
ntp serial gps settings not being saved

### ISSUE THREAD

**Issue by fichtner** [opnsense/core#436]
NTP service configuration does not "keep" settings for 'Serial GPS' tab page, through save.
    
    set configuration:  Ublox, /dev/cacU0, 9600  -- reset config to "/dev/cacu1", 4800.
    
    set configuration: Generic, /dev/cacU0,9600 -- reset config to "/dev/cacu1",4800
    
    set configuration:  Custom,/dev/cacU0,9600 -- reset config to "/dev/cacu1",9600
    
    Correct (confirmed from terminal) configuration settings should be:
    Ublox
    /dev/cacU0
    9600

via: crash reporter

**Comment by paul-chambers** [comment]
I'm still seeing this symptom on 18.1.12. Attempting to use a Navius NSA-U3 GPS receiver (SIRF chipset on USB), can't get the 'SIRF' setting 'stick' in the Web UI (Services->Network Time->GPS, GPS drop-down), keeps resetting to 'Generic' when I save the GPS settings.

**Comment by AdSchellevis** [comment]
@paul-chambers could you try https://github.com/opnsense/core/commit/c0d37accc5fd8fde7eecd30bf44f93fbe24c11bb ?

To install from the console, use:
`
opnsense-patch c0d37a
`

**Comment by paul-chambers** [comment]
That seems to have done the trick - thanks, Ad. Confirming I can now select the 'SiRF' option after applying c0d37ac.

The actual GPS time source is still 'pending', and I see:
--
Jul 18 17:49:26 | ntpd[69099]: GPS_NMEA(0) serial /dev/gps0 open at 4800 bps
Jul 18 17:49:26 | ntpd[69099]: mlockall(): Cannot allocate memory
Jul 18 17:50:35 | ntpd[69099]: kernel reports TIME_ERROR: 0x2007: PPS Frequency Sync wanted but no PPS; PPS Time Sync wanted but no PPS signal
--
...in the log, but I'm sure that's unrelated to this.
