### ISSUE TITLE
Firewall > Logs > Live View: add "is not" and "does not contain"; add IPv4/IPv6 checkboxes; etc.

### ISSUE THREAD

**Issue by eddyg** [opnsense/core#4365]
- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues and I'm convinced that mine is new.

**Describe the solution you'd like**
This is a feature request for several enhancements to filtering packets in the **Firewall > Logs > Live View** screen.

1. A **host** option that matches either **src** or **dst** would be useful. _(Note: **dst** is in the list twice in 20.7.2.)_
2. A **port** option that matches either **src_port** or **dst_port** would be useful. 
3. Currently you can only filter by **is** and **contains**. It would be very helpful to be able to use **is not** and **doesn't contain** as options to _invert_ a match criteria. For example, **port is not 5353**.
4. It would be helpful to have checkboxes for **Show IPv4** and **Show IPv6** which can be toggled off/on to hide that type of traffic when you're looking for something related to one protocol or the other. And when _both_ are unchecked, only non-IPv4 and non-IPv6 protocols would be shown, such as ESP (the equivalent of `not (ip or ip6)` when using `tcpdump`).

Thanks for considering this suggestion.

**Comment by AdSchellevis** [comment]
this https://github.com/opnsense/core/commit/a539124fe93dbaa37fa9d18f7af5b738926d4eb0 is as far as I'm willing to go now. (combined with the work @devNan0 did on the not condition that's probably all except point 4).
