### ISSUE TITLE
Allow for encrypted private keys when defining an existing CA.

### ISSUE THREAD

**Issue by fkelava** [opnsense/core#4366]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[ X ] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[ X ] I have searched the existing issues and I'm convinced that mine is new.

**Is your feature request related to a problem? Please describe.**
When defining an existing certificate authority in System -> Trust -> Authorities and providing an encrypted private key, OPNsense will state that _Encrypted private keys are not yet supported._ I'd simply like to ask whether support for this will be included in a future release, if at all. If it is too costly to implement or there is no point, that's also perfectly fine.

**Describe the solution you'd like**
I'd like OPNsense to accept encrypted private keys when defining an existing CA. Ideally, it would prompt for the decryption passphrase every time a new certificate needs to be created, or you can just prompt once, during entry, and store the plain copy. Either approach works perfectly fine and is faster than having to go to the locked-down CA machine, in my instance. 😄 

**Describe alternatives you've considered**
This is just my laziness speaking. Of course, I _can_ always just decrypt it beforehand, but I forget more often than not and it'd save me a bit of time if this was supported. This is a pure luxury feature, lowest priority- I'm just asking because "not _yet_ supported" gives me hope! 😄 

**Additional context**
Nothing special to add. Again, if you can, great, if not, also great. Thank you for all of your hard work on OPNsense!

**Comment by AdSchellevis** [comment]
it has been "not yet" for 10 years ;) https://github.com/pfsense/pfsense/commit/46698c3f3c5e3f2e98829757616ddda3ce779b6d We don't have plans to support a decryption key, but Iet's keep the request open for a couple of months. A simple paragraph in the docs to explain how to remove the key could also be an option. labeling this "help wanted"
