### ISSUE TITLE
Firewall/Live-View: OpenVPN filter doesn't work

### ISSUE THREAD

**Issue by devNan0** [opnsense/core#4369]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[x] I have searched the existing issues and I'm convinced that mine is new.

**Describe the bug**
The interface filter for 'OpenVPN' doesn't work.
If activated no lines will be displayed

**To Reproduce**
1. Go to 'Firewall' -> 'Log Files' -> 'Live View'
2. Select to 'interface' filter
3. Select 'contains' or 'is' (Both options bring the same result)
4. Select 'OpenVPN' in the list of interfaces
4. Hit the '+' button to apply the filter

**Expected behavior**
Log view with only 'OpenVPN' interfaces

**Screenshots**
![1600804714](https://user-images.githubusercontent.com/49376203/93931812-94c56780-fd1f-11ea-9a48-e224697e6504.png)

**Environment**
OPNsense 20.7.2 (amd64, OpenSSL).
AMD GX-412TC SOC (4 cores)

**Comment by devNan0** [comment]
As far as i found in the code:
JavaScript filters for 'OpenVPN' interface.
But the JSON log line contains 'ovpns1',  'ovpns2',  'ovpns3', ....

**Comment by AdSchellevis** [comment]
@devNan0 it should omit OpenVPN and other interface groups, since they can't exist in the log output. This means that in order to filter them you need to assign the interface first (Interfaces -> Assignments), there's currently not a lot we can't do about that since these types aren't automatically registered.

**Comment by devNan0** [comment]
Ah i see. Thanks for pointing that out.
