### ISSUE TITLE
WAN - Default DHCP, LAN Default Address

### ISSUE THREAD

**Issue by gauthig** [opnsense/core#4371]
**Is your feature request related to a problem? Please describe.**
When installing, changing NICs/Drivers, VLANS or Static IPs, it is real frustrating that after you do option 1 - assign interfaces that the system automatically makes the LAN 192.168.1.1 and the WAN DHCP.  

LAN Issue -  If you are building a second test firewall or HA box, it may be on the same LAN and for 2 minutes it tells the switch that it is the same IP as the other one (if you use 192.18.1.0/24).  

WAN Issue - It takes about 2 minutes for the DHCP to timeout. 

**Describe the solution you'd like**
When assigning interfaces for the first time, jump into Set IP Address before enabling devices.

**Describe alternatives you've considered**
Another option would be to set interfaces to disabled until user goes into Option 2 Set IP Addresses

**Comment by fichtner** [comment]
Since version 19.1 you can skip the addition of WAN/LAN and add as many OPT interfaces as you want.


Cheers,
Franco
