### ISSUE TITLE
WebGUI Listen Interface "use the default" button not reverting to default

### ISSUE THREAD

**Issue by pabe-github** [opnsense/core#4373]
[X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
[X] I have searched the existing issues and I'm convinced that mine is new.

**Describe the bug**
"Use the default" Button of Web GUI Listen Interface change does not revert back to the default.
When the user trusts this button, does not verify the Listen Interfaces again, changes something else and Saves, the Listen Interfaces get changed

**To Reproduce**
1. Go to System -> Settings -> Administration
2. Web GUI Listen Interfaces should be the defaul "All (recommended)"
3. When changing that to anything else raises the Warning popup with the Options "use the default" and "I know what I am doing"
4. Clicking "use the default" does not revert back

**Expected behavior**
Revert the Listen Interfaces back to the default

**Screenshots**
![1](https://user-images.githubusercontent.com/42635243/94113343-0ba95000-fe47-11ea-9e2f-8f839ae5ef48.PNG)
![2](https://user-images.githubusercontent.com/42635243/94113362-119f3100-fe47-11ea-9507-e44641f4946c.PNG)
![3](https://user-images.githubusercontent.com/42635243/94113371-1368f480-fe47-11ea-8395-f5cbdcc5b475.PNG)

**Environment**
OPNsense 20.7.2 (amd64, OpenSSL).

**Comment by fichtner** [comment]
I just saw, thanks for adding a ticket :)

**Comment by fichtner** [comment]
magic via @AdSchellevis  6cac461e6e
