### ISSUE TITLE
If using bridges, hide members from Firewall => Rules menu

### ISSUE THREAD

**Issue by Nimloth** [opnsense/core#4374]
When using several bridges with several member interfaces, the Firewall rules section is, I think, unneccessarily cluttered and confusing.

According to the description of the tunables, setting
a) net.link.bridge.pfil_member=0
b) net.link.bridge.pfil_bridge = 1
will a) disable filtering on the bridge member interfaces and b) enable filtering on the bridge itself.

My assumption is that, in this case, all filtering **has to happen on the bridge itself** and **member interfaces will to be ignored** when evaluating firewall rules.

If those assumptions are correct, then I think it would be reasonable to expect that bridge member interfaces should not be selectable when viewing or creating firewall rules either in the Firewall => Rules menu or in dropdowns within the rule editor.

Currently, this is not the case at all:

Imagine a setup with both WLAN and LAN where I use VLANs to separate a (production) work network from a (testing) lab network. For each VLAN, I have a vlan interface for the LAN port (trunk to be fed into a switch) as well as a Wireless (virtual) AP as members of a bridge.

The result is that under Firewall => Rules, I have menu entries for

WORK (bridge0)
WORK_WIFI (ath0_wlan1)
WORK_WIRED (vlan 100 on igb1)
LAB (bridge1)
LAB_WIFI (ath0_wlan2)
LAB_WIRED (vlan 200 on igb1)

Given my assumptions above are correct, I would have expected only the interfaces WORK and LAB (bridge0 and bridge1) to be available when specifying rules. The _WIFI and _WIRED interfaces should not be available in this context.

As a sort of minimal solution, it would be nice to be able to hide interfaces manually, by specifying them, e.g. on the Firewall => Settings page. (The settings of the Interfaces widget on the dashboard comes to mind, where you can specify which interfaces to hide/show.)

**Comment by Nimloth** [comment]
@AdSchellevis please let me know if anything else is missing / what is making this an incomplete request.

**Comment by mimugmail** [comment]
Because you didnt use the template.
Bridges in FreeBSD are no fun, best advise is to use floating rules only.

**Comment by Nimloth** [comment]
@mimugmail 
I assume that by template you mean the default text that is given when I open a new feature request?
Consider for a moment the possibility that I did try to observe the template and follow its outline.
Furthermore, please consider that I specifically asked 'if anything else is missing / what is making this an incomplete request'. I did so as a contingency in case I had not correctly followed the template, which is to say that I was aware of the possibility of not getting it right.
Given the above, replying that I have not correctly followed the template is not helpful as it merely confirms that I still got this wrong. Clearly outlining how my request could be amended to conform to the template would be way more productive as it would enable learning from mistakes. As it is, I am no closer to understanding what is required as I was before. Having re-read the template has not helped me, either. Please let me know how this needs to be written / formatted so that the incomplete label can be removed.

(And just as an afterthought: If people - and I saw lots of incomplete labels among other issues - tend to get this wrong, it may certainly be their fault for ignoring or not following the guidelines / template. But maybe, just _maybe_ it could also be that the template is not intuitive or explicit enough or lacks clear examples.)

Now, about bridges and floating rules... Whether or not bridges are 'fun' to work with is irrelevant to my request.
Had I specified that I was trying to achieve a certain result, then any alternative suggestions as to how the desired result could be achieved would certainly have been helpful and highly appreciacted. However, I was describing a situation where bridges **are** used. And my suggestion / enhancement request still stands: **If** you use bridges as outlined, then the bridge's member interfaces should be hidden as described.

**Comment by mimugmail** [comment]
Have you tested if only using the bridgeinterface is enough? I have in mind that when Unit 1 on igb1 wants reach Unit 2 in igb2 it's not enough to add a rule on the bridge interface

**Comment by Nimloth** [comment]
In my setup, yes, it is enough to setup rules only on the bridges. There are no rules defined on the member interfaces at all.
