### ISSUE TITLE
Disabled Syslog in GUI, but OPNSense still reporting all the time!

### ISSUE THREAD

**Issue by Bytechanger** [opnsense/core#4378]
OPNsense 20.7.3-amd64
FreeBSD 12.1-RELEASE-p10-HBSD
OpenSSL 1.1.1g 21 Apr 2020

Hi,

I disabled remote syslog in OPNSense, 
 System->Logging/targets.
I REMOVED all entrys here.

But on my remote syslog there where many entrys.

Than, I look at my config-file and found:

```
<syslog>
    <reverse>1</reverse>
    <nentries>50</nentries>
    <remoteserver>172.30.90.81</remoteserver>
    <remoteserver2/>
    <remoteserver3/>
    <sourceip/>
    <ipproto>ipv4</ipproto>
    <logall>1</logall>
    <enable>1</enable>
    <nologdefaultblock>1</nologdefaultblock>
    <nologdefaultpass>1</nologdefaultpass>
    <nologbogons>1</nologbogons>
    <nologprivatenets>1</nologprivatenets>
  </syslog>
```

I changed it into:

```
 <syslog>
    <reverse>1</reverse>
    <nentries>50</nentries>
    <remoteserver/>
    <remoteserver2/>
    <remoteserver3/>
    <sourceip/>
    <ipproto>ipv4</ipproto>
    <nologlighttpd>1</nologlighttpd>
    <nologbogons>1</nologbogons>
    <nologprivatenets>1</nologprivatenets>
    <nologdefaultpass>1</nologdefaultpass>
  </syslog>
```

and import syslog config.

Restart OPNSense, but all the times I get entrys in remote server.

When I disable the syslogserver (destination) in OPNSense log there where entrys like:
Syslog connection broken; fd='21', server='AF_INET(172.30.90.81:514)', time_reopen='60'

So I´m not able to disable syslog!

Greets

Byte

**Comment by Bytechanger** [comment]
Why incomplete? Do you need more information?

**Comment by AdSchellevis** [comment]
issue template not used (please read https://github.com/opnsense/core/blob/master/CONTRIBUTING.md)

**Comment by Bytechanger** [comment]
When creating bug reports, please make sure you provide the following:

The current OPNsense version where the bug first appeared
The last OPNsense version where the bug did not exist
--> I dont know, because I disabled remote syslog first time.


The exact URL of the GUI page involved (if any)
-->  no url

A list of steps to replicate the bug
->  At a further version (1 year ago) set a remote syslogserver.
At actually version, remove it. In my case, it was empty in GUI, but in config file still there. And OPNsense still logs remotely.
Than remove syslig from config and import it again.
OPNSense still logs remotly...
Dont know what to say more

**Comment by AdSchellevis** [comment]
We create issue templates for good reasons (structure the support flow, make it easier for people to read and interpret reports), unfortunately GitHub doesn't support enforcing policies, so we usually label them. 

One of the things we ask to acknowledge in the template is _"I have searched the existing issues and I'm convinced that mine is new."._  Which is also a question to browse reports before opening new ones,  in this case reading existing reports around syslog and remote logging should result in not opening an issue, since it looks quite similar to  https://github.com/opnsense/core/issues/4121

**Comment by Bytechanger** [comment]
You are right, its similar.

**Comment by AdSchellevis** [comment]
duplicate
