### ISSUE TITLE
Allow to create BINAT rules

### ISSUE THREAD

**Issue by fraenki** [opnsense/core#438]
While debugging an IPsec/NAT issue in #369 with @AdSchellevis, we've discovered that it is possible to create BINAT rules when configured an IPsec Phase 2 entry accordingly. This lead to the following questions:

1. Shouldn't it be possible to create BINAT rules from the Firewall->NAT menu too?
1. Would this make the IPsec Phase 2 NAT "hack" obsolete? (i.e. not adding an phase 2 configuration to ipsec.conf if it's only for NAT/BINAT)

Examples for BINAT rules derived from phase 2 configuration:

```
binat on enc0 inet from 172.16.1.5 to 10.11.12.0/24 -> 192.168.0.254
binat on enc0 inet from 172.16.2.0/24 to 10.22.13.0/24 -> 192.168.1.0/24
```

**Comment by AdSchellevis** [comment]
@fraenki you should be able to setup binat using nat 1:1 (firewall_nat_1to1.php) and enable nat reflection, it looks like the same rules are generated then as when using the ipsec option.

**Comment by fraenki** [comment]
Confirmed, it's possible to create binat rules using the 1:1 NAT option. Apparently a shortcoming on my side, I'm sorry.

This solved my first question. The second question will be further discussed in #440.
