### ISSUE TITLE
Unbound misses IPv6 ACL when WAN goes up and down

### ISSUE THREAD

**Issue by floeff** [opnsense/core#4380]
This bug seems related to https://github.com/opnsense/core/issues/4142, https://github.com/opnsense/core/issues/3342 and https://forum.opnsense.org/index.php?topic=13196.msg60662

I'm on OPNsense 20.7.3

From time to time, OPNsense's Unbound refuses to answer queries from my local network via IPv6, while IPv4 works reliably.
I am on a bridged cable modem, getting a static IPv4 and a static IPv6 /56 prefix, both assigned via DHCP.
The LAN interface is configured as tracking.

While on services_unbound_acls.php the IP networks are listed correctly, it seems the start order of services causes problems, as /var/unbound/access_lists.conf is updated not reliably, missing the local /64 network, and therefore refusing queries from my local IPv6 network.

The problem occurs when the WAN interface goes down, e.g. in case of a network outage, and can at least somtimes be reproduced if I choose menu option 11 in SSH, to restart all services.

As a really ugly workaround, I've added "::/1 allow" via a custom access list, but somehow doesn't feel proper. :-)

In some issue I read restarting Unbound isn't done on purpose, to avoid purging the cache. I wonder if it doesn't make sense to propagate the link local addres (fe80) as local DNS resolver instead of the public IPv6 address, to work around this problem.

**Comment by DiGitHubCap** [comment]
This is still an issue. It shouldn't be closed.

**Comment by fichtner** [comment]
Several tickets still open really.

**Comment by DiGitHubCap** [comment]
Ah, I didn't notice there were other tickets. Sorry.

For others' reference, #4970 is tracking this.
