### ISSUE TITLE
OpenVPN set auth-retry to nointeract

### ISSUE THREAD

**Issue by kosli** [opnsense/core#4382]
Hi

I noticed that my OPNsense clients stopped connecting to my server as I was doing some changes on the server. As the server had returned an error status via the client-connect script, all clients stopped connecting to the server. This means I need to connect to every single OPNsense box and manually disable and enable the OpenVPN service to get them connected again.

As my expectation for a VPN client is to have it "always on", I would suggest to add the 
`auth-retry nointeract`
option into the config file, similiar to the resolv-retry here: https://github.com/opnsense/core/blob/0b379917aecaa3cad23d1fae9514997563d63cee/src/etc/inc/plugins.inc.d/openvpn.inc#L933
Either as default or via a tickbox.

Currently I have added the **auth-retry** option via the **Advanced configuration** field, but this won't be possible in the future as this field is going to be removed.

Kind regards
 KoS

**Comment by kosli** [comment]
btw here is the description from the [OpenVPN manual](https://openvpn.net/community-resources/reference-manual-for-openvpn-2-4/):

**–auth-retry type**
Controls how OpenVPN responds to username/password verification errors such as the client-side response to an AUTH_FAILED message from the server or verification failure of the private key password.Normally used to prevent auth errors from being fatal on the client side, and to permit username/password requeries in case of error.

An AUTH_FAILED message is generated by the server if the client fails –auth-user-pass authentication, or if the server-side –client-connect script returns an error status when the client tries to connect.

type can be one of:

**none** — Client will exit with a fatal error (this is the default).
**nointeract** — Client will retry the connection without requerying for an –auth-user-pass username/password. Use this option for unattended clients.
**interact** — Client will requery for an –auth-user-pass username/password and/or private key password before attempting a reconnection.

Note that while this option cannot be pushed, it can be controlled from the management interface.

**Comment by jacob8000** [comment]
This issue is still relevant and it should be opened
