### ISSUE TITLE
Firewall Destination WAN_address should not include VIPs

### ISSUE THREAD

**Issue by knxuf** [opnsense/core#4386]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[X] I have searched the existing issues and I'm convinced that mine is new.

**Describe the bug**
if you want a service only listen on the real WAN_address of a carp cluster for example ssh and not on the VIP interfaces it is not possible because if you use an alias for each WAN ips it will be synced.

WAN_address should be only the real Interface IP without VIPs because VIPs can be selected as Destination on both hosts, but not the local interface

**To Reproduce**
1. create HA Setup with nodes WAN IP .2 and .4  with VIP .3
2. create firewall rule with Destination WAN_address and pass SSH

**Expected behavior**
SSH ist only reachable via .2 on node 1 and on .4 on node 2 but not on the VIP with .3 IP

**Screenshots**

**Relevant log files**

**Additional context**

**Environment**
OPNsense 20.7.3-amd64FreeBSD 12.1-RELEASE-p10-HBSDOpenSSL 1.1.1g 21 Apr 2020
CPU Type | Intel(R) Xeon(R) Gold 6136 CPU @ 3.00GHz (4 cores)
VMX

**Comment by mimugmail** [comment]
What has listening port to do with a Firewall alias?

**Comment by knxuf** [comment]
for example SSH service, i dont want it to be reachable on the VIPs. How do i do this with a synced config.
I can't choose an IP address because it will be synced to the other host that has another WAN IP.
If I choose destination "WAN_address" it is reachable on the WAN IP of that specific firewall host but also on all VIPs.

**Comment by mimugmail** [comment]
Settings of sshd are not synced

**Comment by knxuf** [comment]
it doesn't matter.

changed to only listen on specific interfaces (which of cause incl. WAN on which the VIP is)
still reachabel on the VIP NIC

Firewall rule
  | IPv4 TCP | GEO_DACH | * | WAN_NC address | 22 (SSH) | * | * | Allow SSH from GEOIP DACH
