### ISSUE TITLE
IPsec NAT rules not fully disabled

### ISSUE THREAD

**Issue by fraenki** [opnsense/core#439]
This is related to #369. When disabling a IPsec NAT rule (VPN->IPsec->Tunnels) and clicking _"Apply"_ the pf NAT rules will be not disabled. You'll see that the entry is removed from `ipsec.conf`, but the pf rule is still enabled:

```
# pfctl -s nat | grep enc0 | grep 172
No ALTQ support in kernel
ALTQ related functions disabled
binat on enc0 inet from 172.16.2.0/24 to 10.22.13.0/24 -> 192.168.1.0/24
```

**Comment by AdSchellevis** [comment]
@fraenki maybe we should look at the ipsec nat issue when we're both online, I think you should be able to setup the situation you want using the nat 1:1 option, all needed to nat your ipsec seems to be in there.
