### ISSUE TITLE
Outbound NAT

### ISSUE THREAD

**Issue by candrist** [opnsense/core#44]
I am trying to use outbound nat, but the firewall seems to be ignoring my rule.

![outboundnat](https://cloud.githubusercontent.com/assets/11068001/6259744/475a27ba-b793-11e4-919d-bc641ac0d34c.PNG)

**Comment by StopTrain** [comment]
I believe you're trying to use this in Hybrid mode and by default, the internal LAN NAT rules would most likely override the one you're trying to use.  It appears, if I'm reading this correctly and correct me please if I'm wrong, you're trying to NAT all ports, from an internal machine, that goes out the WAN Address.  Essentially breaking NAT for anything else trying to get out to the internet?

**Comment by fichtner** [comment]
Tagged solved via https://forum.opnsense.org/index.php?topic=54.0
