### ISSUE TITLE
Virtual IP/CARP Settings are not synced to the secondary FWs

### ISSUE THREAD

**Issue by derjohn** [opnsense/core#4409]
Hello,
I am using OPNsense 20.7.3-amd64. My observations is, that the CARP Settings are not sync'ed to the secondary. That might be since the "Virtual IPs" are a submenu item of "interfaces" instead of "Firewall".

I double checked that the XMLRPC sync of "Virtual IPs | Synchronize the CARP Virtual IPs to the other HA host." is activated. I changed Carp PW, Skew and description but the change never arrived on the secondary.

I adapted it manually to workaround the issue.

rgds,
derjohn

**Comment by mimugmail** [comment]
Did you force a manual sync after adding it?

**Comment by derjohn** [comment]
Yes, I clicked the link "Perform synchronization" in the "Configuration Synchronization Settings (XMLRPC Sync) Perform synchronization" panel. There is button to do so and after clicking you're redirected to "System: High Availability: Status".

**Comment by derjohn** [comment]
Hmmm ... I checked with firewall rules on the WAN interfaces. They aren't sycned, too. So the issues is probably somewhere else.

**Comment by derjohn** [comment]
Now I clicked the the  "Perform synchronization", which brings me to "System: High Availability: Status" Panel, there I click on "Synchronize config to backup" and then it works.

Is it the intended URL of the the "Perform synchronization" Link? Furthermore "Synchronize config to backup" reads like I want to perform a backup to the cloud storage. Shouldn't the wording be something like "Synchronize config to secondary firewall" ?




--

**Comment by derjohn** [comment]
And: Shouldn't the config sync occur on every "apply" I click? I re-tested: That doesn't happen. Only manual sync works. I cant find a button for "enable auto sync". Is it normal behavior?

**Comment by AdSchellevis** [comment]
no https://docs.opnsense.org/manual/hacarp.html

**Comment by derjohn** [comment]
hahaha an RTFM, Thx :) 

I checked the logs and see this one ONLY if I click manual sync

opnsense[27413] | /usr/local/etc/rc.filter_synchronize: Filter sync successfully completed with https://172.20.255.2:10443/xmlrpc.php.

If I add e.g. a  new WAN Firewall rule, nothing happens.

**Comment by derjohn** [comment]
@AdSchellevis In the docs there is written "Configuration changes made on the primary system are synchronized on demand to the secondary firewall." Does that "demand" mean, I have to initiate that manually, i.e. it does not directly after clicking apply on the primary FW?

**Comment by AdSchellevis** [comment]
@derjohn you have to initialise it manually indeed, as explained in the document under workflow (https://docs.opnsense.org/manual/hacarp.html#workflow).

**Comment by fhloston** [comment]
Did this change recently? I was under the impression that for example firewall rules were indeed XMLRPC-synced but not activated yet?

**Comment by mimugmail** [comment]
I'd call it a "fuck I kicked myself out from cluster - phew, wasn't synchronized to backup-unit"-feature

**Comment by derjohn** [comment]
At least for the firewall rules there is a message after apply
"The changes have been applied successfully, remember to update your backup server in System: High availablity: status"

So: Works as designed. #closing
