### ISSUE TITLE
User management - use "auth user changed" event

### ISSUE THREAD

**Issue by AdSchellevis** [opnsense/core#4411]
In https://github.com/opnsense/core/commit/ecfd53ac2f60c6abd259702ed9e183acef967ea we added an event which can capture user (group) changes, in order to make this more useful, it would be good if the same event is being fired when a user or group is changed via the web interface.

This can be used for example to replicate user information to another service which may need to know the context of the user for performance reasons (lots of queries) or missing integration options.

Adding the event should be rather harmless, which should easy the release path, in a future release we might consider removing some logic (e.g. `core_user_changed_groups()` already updates the local groups)

**Comment by AdSchellevis** [comment]
@fichtner I would probably like to move this to production in the next release, so I've tried to lower the risk by keeping the current system group commands in place (we can remove these later, but we probably better check together if the code does what I think it does).

**Comment by fichtner** [comment]
dea732c it is then. close this one? :)

**Comment by AdSchellevis** [comment]
@fichtner thanks, case closed indeed :)
