### ISSUE TITLE
Services: Unbound DNS: Blacklist / unexpected behaviour

### ISSUE THREAD

**Issue by geraldurbas** [opnsense/core#4413]
In Verison 20.7.3 (installed)
if i change the blacklist or Check and uncheck 'Enable'  in /ui/unbound/dnsbl/index
the behaviour is confusing.

-> /var/unbound/etc/dnsbl.conf 
is cleared after unchecking but the update process for /var/unbound/etc/dnsbl.conf
is not initiated...

Empty File Happens with the next cronjob Run...
its ok - but i guess (since enabling start to download and update) its ok to do the  update process for dnsbl.conf with unchecking too...

Even Restarting og unbound isnt updating the dnsbl.conf File

**Comment by mimugmail** [comment]
Can you check latest master? There were significant changes and my latest test went fine.
