### ISSUE TITLE
[RFE] Improve handling of Client Specific Overrides (OpenVPN)

### ISSUE THREAD

**Issue by fraenki** [opnsense/core#442]
### The Story
I have a rather complex OpenVPN server configuration with multiple VPN networks and many _Client Specific Overrides_. Each VPN network is assigned to special firewall rules, providing either more or less access to my infrastructure. This makes it quite easy to limit access for our clerks, but provide full access for sysadmins and furthermore provide very limited access for external staff.

### The Problem
To get this working, I have to create a _Client Specific Override_ for every user. Besides that I need to change the _Tunnel Network_ setting to match with the appropiate VPN network. Now the problem is that I need to *manually* select *a unique /30* network for every single user. This is a hassle and prone to errors, especially if you have many users (duplicate client IP addresses).

### My Proposal
I'd love to only provide one of my /24 VPN networks and OPNsense would automatically choose a free IP address/network (depending on [topology setting](https://community.openvpn.net/openvpn/wiki/Topology)) for me.

Example:
* OpenVPN _Topology_ is configured to _net30_
* CSC for user1 is configured to use the 10.99.0.0/24 _Tunnel Network_ and to automatically select the IP address
  * OPNsense would automatically select the first /30 and use 10.99.0.0/30
* CSC for user2 is configured to use the 10.99.0.0/24 _Tunnel Network_ and to automatically select the IP address
  * OPNsense would automatically select the second /30 and use 10.99.0.4/30
* CSC for developer1 is configured to use the 10.33.0.0/24 _Tunnel Network_ and to automatically select the IP address
  * OPNsense would automatically select the first /30 and use 10.33.0.0/30

OPNsense would _permanently_ assign this IP address and write it to the config.xml. Once the _Client Specific Override_ is deleted the IP would be released.

Of course, in some situations it may be required to manually assign the IP address/network. That's why there should be a checkbox to enable/disable the automatic assignment.

**Comment by fraenki** [comment]
If you accept this proposal, it might be a good idea to fix #347 alongside.

**Comment by AdSchellevis** [comment]
@fraenki should a copy feature and a display for the used address/range in the overview grid also be an option? In the current form I just don't think this one is going to make it, it would add a lot of extra complexity for a limited use case.

**Comment by fraenki** [comment]
@AdSchellevis I agree that this is rarely asked for and maybe not worth to add a lot of extra code/complexity. A copy feature would be very nice, though! I'm note sure how the "overview grid" may work...

**Comment by AdSchellevis** [comment]
@fraenki I mean show the tunnel network in vpn_openvpn_csc.php, so its easier to detect accidental overlaps.

**Comment by fraenki** [comment]
@AdSchellevis Ahh yes, this would be useful. I'm currently adding the tunnel network to the description manually...
