### ISSUE TITLE
OpenVPN interface is missing as a selectable option in Live View

### ISSUE THREAD

**Issue by gjduran** [opnsense/core#4421]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[X] I have searched the existing issues and I'm convinced that mine is new.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
OpenVPN interface is missing as a selectable option in Live View so would be nice if OpenVPN could be added to the drop down list of interfaces in Live View once OpenVPN is in use. 

**Describe alternatives you've considered**

**Additional context**

**Comment by fichtner** [comment]
See https://github.com/opnsense/core/issues/4369
