### ISSUE TITLE
Incorrect parsing of DUID in dhcpd6.leases

### ISSUE THREAD

**Issue by mjholgate** [opnsense/core#4423]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[X] I have searched the existing issues and I'm convinced that mine is new.

**Describe the bug**
When displaying the DHCPv6 lease page, the DUID column shows a duplicate hex value if the ia-na line in `dhcpd6.leases` contains a \" (i.e. hex 0x22).

ia-na "\001\000\000\000\000\001\000\001\"\001\002\003\004\005\006\007\010\011" {

Is displayed as `00:01:00:01:22:22:01:02:03:04:05:06:07:08:09` but should be displayed as `00:01:00:01:22:01:02:03:04:05:06:07:08:09`.

If you add a static lease by pressing the + button, the incorrect value will be used.

**To Reproduce**

Hard to reproduce unless you've got a machine with a DUID containing hex 0x22, but this can be shown via the php command line:

```
php> $foo = parse_duid('\001\000\000\000\000\001\000\001\"\001\002\003\004\005\006\007\010\011');
php > echo implode(":", $foo[1]);
00:01:00:01:22:22:01:02:03:04:05:06:07:08:09
```

**Expected behavior**
Output should be 00:01:00:01:22:01:02:03:04:05:06:07:08:09

**Screenshots**

**Relevant log files**
If applicable, information from log files supporting your claim.

**Additional context**
I have a PR which I *hope* will fix this issue. I've tested it from the php command line, but have no way to test it in real life.

**Environment**
OPNsense 20.7.3 (amd64).

**Comment by mjholgate** [comment]
Please see my fix in the PR. Please note that it is only tested in isolation and not within the product! Hopefully it will be useful anyway.

**Comment by fichtner** [comment]
same as #4591

**Comment by fichtner** [comment]
thanks, will be added to 20.7.8 ❤️
