### ISSUE TITLE
CLEANUP REQUEST - Firewall: Shaper: Status displays deleted Pipe

### ISSUE THREAD

**Issue by davidgriffeth** [opnsense/core#4428]
I initially created 3 pipes in Firewall: Shaper. Subsequently, I decided I only needed 2 of the pipes, and I deleted the 3rd pipe. The deleted pipe still shows in Firewall: Shaper: Status despite the fact that it has been deleted.

In the attached image, Pipe # 10002 is the deleted pipe.

The current OPNsense version where the bug appears: OPNsense 20.7.3-amd64
The exact URL of the GUI page involved:  https://192.168.0.1/ui/trafficshaper/service/statistics

![deleted pipe](https://user-images.githubusercontent.com/54635775/97018110-bed79880-151c-11eb-82fa-c3e072dd3f2b.PNG)

**Comment by fichtner** [comment]
This is expected. You need to flush the whole shaper system with the respective GUI button (next to apply if I recall correctly).

**Comment by davidgriffeth** [comment]
Ahh, I needed to push the "reset" button. Thank you!
