### ISSUE TITLE
firewall/aliases: condense into one page

### ISSUE THREAD

**Issue by sjorge** [opnsense/core#443]
e.g. on ip, default to hosts, on port default to port when clicking the add button

**Comment by fichtner** [comment]
Maybe we can get rid of "faking" pages, the URL is the same anyway?

**Comment by fichtner** [comment]
Whoops, wrong button :D

**Comment by fichtner** [comment]
I think I'm going to work that into the 16.1 menu changes, only one alias page and be done with it.

**Comment by sjorge** [comment]
sounds good to me.

**Comment by fichtner** [comment]
brilliant, cheers for the feedback :)

**Comment by fichtner** [comment]
* Network aliases edit allows comma-separated entries per entry
* Import page only does networks, global description seeps into item description
