### ISSUE TITLE
Changing "speed and duplex" seems to have no effect

### ISSUE THREAD

**Issue by larseggert** [opnsense/core#4435]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[x] I have searched the existing issues and I'm convinced that mine is new.

**Describe the bug**
Changing "speed and duplex" for an interface in the GUI does not seem to have any effect - `ifconfig` output still shows `media: Ethernet autoselect (1000baseT <full-duplex>)`.

**To Reproduce**
1. Go to Interfaces, pick one, change "Speed and duplex"
2. Click on "Save"
3. Log in via SSH and look at the `ifconfig` output of the respective interface.

**Expected behavior**
Would have expected the media output to change away from the default.

**Comment by AdSchellevis** [comment]
not all network drivers probably support setting the link, it's not a generic thing.

**Comment by larseggert** [comment]
This is with an `igb` device.
