### ISSUE TITLE
Create IPv6 Far Gateway

### ISSUE THREAD

**Issue by Crazyachmed** [opnsense/core#4436]
**Describe the bug**
Creating a "Far Gateway" for IPv6 is not possible as the config is blocked by the UI with the message "The gateway address xxx does not lie within one of the chosen interface's IPv6 subnets."

This is possible for IPv4 without any trouble.

**To Reproduce**
1. Go to System -> Gateways -> Single -> Add
2. Name: Test, Interface: WAN, Address Family: IPv6, IP Adress: 2606:4700:4700::1111, Far Gateway: True, Disable Gateway Monitoring: False
3. Save

**Expected behavior**
Gateway is created as it is when using IPv4

**Additional context**
I have trouble with my ISP and want to add Cloudflare and Cisco DNS as "dummy" gateways so I can see the outages in the gateway monitoring graphs. This works fine for IPv4, but I want to check both address families for outages.

**Environment**
OPNsense 20.7.4-amd64
FreeBSD 12.1-RELEASE-p10-HBSD
OpenSSL 1.1.1h 22 Sep 2020

**Comment by AdSchellevis** [comment]
although I'm not entirely sure this works, but can you try https://github.com/opnsense/core/commit/d87f4d79c42deb84b51a0cac59f06cb55b93a199 ?

**Comment by fichtner** [comment]
Far gateway concept for IPv6 does not work in kernel.

**Comment by AdSchellevis** [comment]
ok, let me revert my quick fix then.

**Comment by AdSchellevis** [comment]
we could add another validation noting that far only works on IPv4

**Comment by fichtner** [comment]
I thought about removing it from the page, but the rendering is not completely trivial (when creating the gateway we would have to hide it dynamically).

**Comment by fichtner** [comment]
For technical reference: if you need an IPv6 gateway use link local or widen your WAN subnet to include the "far" gateway. There is no other way to fix this.
