### ISSUE TITLE
APU's do not restart after a power fail (v 12.7) but 19.1 is ok

### ISSUE THREAD

**Issue by jstrebel** [opnsense/core#4437]
I had a power fail with my APU3 running 20.7 Software. The Box did not come up.
The following errors are observed on the serial console.

CYLINDER GROUP 104: BAD MAGIC NUMBER
UNEXPECTED SOFT UPDATE INCONSISTENCY

REBUILD CYLINDER GROUP? yes
(it continues for minutes. More on: https://forum.opnsense.org/index.php?topic=19846.0

I tried also with APU2 problem is the same after a power fail.
Then I reverted to a old version where I remembered it was ok.
With version 19.1 APU restarts properly after power fail.

Jakob

**Comment by jstrebel** [comment]
@AdSchellevis What do you mean with support?

**Comment by AdSchellevis** [comment]
@jstrebel other than not using our templates (which I would normally mark as incomplete), it's a  community support ticket, often hardware or bios related (the forum is a better place for these items).

**Comment by jstrebel** [comment]
@AdSchellevis Thank you for the explanation. It seems to me that none of the experienced users is interessted in this.
@fichtner  Hallo Franco hast du mir einen Tip wie ich weiterkomme. Das ganze Ding wieder neu aufsetzen nach einem Powerfail ist etwas umständlich. liebe Grüsse jakob

**Comment by fichtner** [comment]
This is still true: https://forum.opnsense.org/index.php?topic=19846.msg91684#msg91684

Quoting here for further reference:

> Your filesystem is full when you pull the power. That is the problem. Always monitor disk usage and make sure there is space left.
> 
> It is normal for UFS (and every other FS, btw) to lose a couple of transactions that are "in flight" when you just pull the plug. But the reason why the FS cannot be repaired automatically at the next reboot is simply that your media is full. See all the "No space left on device" messages.

**Comment by jstrebel** [comment]
@fichtner Thank you Franco.
It seems to me the error message "file system is full" is misleading.
- Both tests were done immediately after a fresh install of OPNsense 12.7 (SD Card with 64GB and mSata 16GB)
- The Problem does not occur doing the same tests with Version 19.1
regards Jakob

**Comment by jstrebel** [comment]
Thanks to the suggestion of Michael Steinmann from PCengines. He suggested to download the serial image,  boot it from the USB and install it to the mSATA. Disconnect power and reconnect it do not create the problem as reported.
