### ISSUE TITLE
ipsec ike1 hybrid-rsa xauth failed

### ISSUE THREAD

**Issue by gratuxri** [opnsense/core#4438]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[X] I have searched the existing issues and I'm convinced that mine is new.

**Describe the bug**
I have followed howto at https://docs.opnsense.org/manual/how-tos/ipsec-road.html and https://docs.opnsense.org/manual/how-tos/ipsec-rw-srv-ikev1xauth.html as a result working ipsec ike1 hybrid-rsa xauth, but without working xauth authentication.
Here are some logs with replaced ${USER}, ${FQDN}
2020-11-02T00:25:07 | charon[38591] | 15[IKE] <con1\|3> XAuth authentication of '${USER}' failed
2020-11-02T00:25:07 | charon[38591] | 15[IKE] <con1\|3> no XAuth secret found for '${FQDN}' - '${USER}'

After adding to /usr/local/etc/ipsec.secrets.opnsense.d/user.secrets lines like 
`[ <servername> ] <username> : XAUTH "<password>"`
It works correctly.

Sorry, but I'm new to opnsense and don't have this setup on old versions.

**Expected behavior**
2020-11-02T00:27:19 | charon[38591] | 14[IKE] <con1\|1> XAuth authentication of '${USER}' successful

**Environment**
KVM with OPNsense 20.7.4 (amd64, OpenSSL).

**Comment by gratuxri** [comment]
It's reproducible on two instances. I mean to get it working is some code needed ;) Maybe it's better to mark it as bug?

**Comment by AdSchellevis** [comment]
the ticket doesn't contain a lot of info, so no, currently this is community support unless there's clear evidence of a bug. I'm pretty sure the two scenario's described where tested at some point in time, a typo is easily made.

**Comment by gratuxri** [comment]
Which Information are you missing? It's helpfull to post here anonymous config.xml?

**Comment by gratuxri** [comment]
It's the same issue on 21.1. In https://www.strongswan.org/testing/testresults/ikev1/xauth-id-rsa-hybrid/ -> moon -> ipsec.secrets is typical example for created secrets file. If I'm grepping opnsense-core for XAUTH it has no results

**Comment by fichtner** [comment]
Ehh... sure...

    % git grep -i xauth | wc -l
          24

But what are we looking for?!

**Comment by fichtner** [comment]
FWIW, XAUTH is implemented using PAM and you need to select an authentication database and put the user there. PSK secrets won't do it.

**Comment by fichtner** [comment]
The setup procedure is explained here in all the details... https://docs.opnsense.org/manual/how-tos/ipsec-rw-srv-ikev1xauth.html

**Comment by gratuxri** [comment]
I have installed fresh 21.1.1 on my test environment: https://bit.ly/3rHHXjn 
You can see, that I have followed your manual in details + added dh1024, SHA384 for more compatibility
Login information for root I have send encrypted to your mail. You can do all legal stuff ;)
In /root/ you can find configfiles maybe for some diffs ;) and more login information for tests.
I have tested it with android smartphone.
Please, let me know, if I can destroy this test setup.
