### ISSUE TITLE
OpenVPN UDP multihome replies with wrong source address

### ISSUE THREAD

**Issue by marcquark** [opnsense/core#4442]
**Important notices**
[x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
[x] I have searched the existing issues and I'm convinced that mine is new.

**Describe the bug**
OpenVPN server with multihome and UDP configured on OPNsense. Clients trying to connect from a LAN interface to the WAN IP of OPNsense will see an error and the connection will fail.

**To Reproduce**
1. Set up a multihomed OpenVPN Server with UDP
2. Connect from LAN interface using the WAN IP of OPNsense
3. See error in the form of `2020-11-04 14:40:45 TCP/UDP: Incoming packet rejected from [AF_INET]10.1.0.5:1194[2], expected peer address: [AF_INET]X.X.X.X:1194 (allow this incoming source address/port by removing --remote or adding --float)` where X.X.X.X denotes the WAN IP

**Expected behavior**
The source address in reply packets should be set to the WAN IP

**Screenshots**
-

**Relevant log files**
see above

**Additional context**
This is a known FreeBSD bug that is also documented in the OpenVPN Bugtracker: https://community.openvpn.net/openvpn/ticket/1057?__cf_chl_jschl_tk__=860d2031af4b60cff1d0a5978c2647d38a3afff8-1604497905-0-ARbvwYt2zW3OhgEl1k5_zI2g5qzx9pLsosGPASo8SNCANlIoRPZ4V8raxsjTStUom8ve9YG90kreDoTup9OEADsLRwWyWc2SAqaaqmPWFyyyGbOQTkPz5RwF1UGA8ltNoot0uckoH-NNAEsnJCEaK3aUH9IwxkWh6_htE6EpUNbOR9F0ggG5-x-pMJw7HJ2I31BqsbC2r_1LpacUig4BvANAw9EUzbhK37iQiwMkqzClFIZK6TOPMtB7GI2eYCiyiVkAY2qfjlmHpaqFIYjqZlANf10RqKR5UCPJUrwT78_X
It looks like recently the patch made it into FreeBSD 12. It would be great if that could be made available in OPNSense, too.

**Environment**
OPNsense 20.7.4-amd64
FreeBSD 12.1-RELEASE-p10-HBSD
OpenSSL 1.1.1h  22 Sep 2020

Hardware info is irrelevant here

**Comment by marcquark** [comment]
It also looks like OpenVPN doesn't bind to the Carp VIP properly in multihome mode. It works fine when i select it directly. Could be related to or duplicate of #4056

**Comment by mimugmail** [comment]
Regarding carp let it listen to LAN VIP and add a port forward for both WAN

**Comment by mimugmail** [comment]
Regarding first do the same and be sure that both wans have an upstream gateway

**Comment by marcquark** [comment]
Thx for the suggested workarounds!

They don't cover all cases though, dualstack is the first one that springs to mind. I'm aware that there are ways to achieve everything i want/need (i have dualstack-enabled, LAN-connectable VPNs running for ~3 years with pfSense). The point is with multihome i'd be able to simplify configuration and management quite significantly. This is a bug in the FreeBSD kernel which is fixed upstream. I just wanted to report the issue since i couldn't find any mention of it here in the project yet. _Also i like OPNsense and consider switching over from pfs, a working multihomed OpenVPN would be one more reason to do it sooner rather than later_

**Comment by mimugmail** [comment]
Ah, multihome is a definition of OpenVPN, thought you mean multiple WANs. So, 12.2 is plannend for 21.7 ..

**Comment by marcquark** [comment]
Yeah, multihome support for OpenVPN has already been added in https://github.com/opnsense/core/commit/4af3e1065b120f7d4530b22e79ad9bf7cfab49e5 so i guess with 12.2 the problem should be fixed automatically.

**Comment by fichtner** [comment]
What FreeBSD issue are we talking about? Why wait if there is a fix available.

**Comment by marcquark** [comment]
https://reviews.freebsd.org/D24135
That's what i got from the OpenVPN issue i linked above. I'm having a bit of a hard time understanding FreeBSD's VCS and releases, nur theres a comment in the OpenVPN bugtracker that it is now merged into FreeBSD 12.2
I'd love to see it available in OPNsense. If you have a Testing build that i can throw onto my lab box, let me know!

**Comment by fichtner** [comment]
Thanks, this is it then https://github.com/opnsense/src/commit/dc4568bfca -- I'll try to send you a test kernel today.

**Comment by fichtner** [comment]
Try this one:

    # opnsense-update -kr 20.7.4-ovpn
    # opnsense-shell reboot

**Comment by marcquark** [comment]
awesome! install and reboot was successful. however i feel like now i'm hit by #4056 because there's no reply traffic at all now. i see the firewall passing the initiating packets though
![grafik](https://user-images.githubusercontent.com/23556080/98236539-ce66d080-1f63-11eb-83f8-be4f6f099806.png)
i tried crafting a port-forward rule as a hacky workaround but that failed so far. i'll keep trying for a bit to see if i can get it to work.

**Comment by marcquark** [comment]
humm, something is weird, maybe not exactly #4056 because i tested the following (this is with multihome+udp in all cases). for simplicity i'm just going to call the interfaces LAN1/LAN2/WAN
- Connect from LAN1 to OPNsense's LAN1 IP (DNS spoofed): works
- Connect from LAN1 to OPNsense's LAN2 IP (DNS spoofed): no reply traffic, can see the state in the firewall log though and traffic is passed
- Connect from LAN1 to OPNsense's WAN CARP IP: no reply traffic, can see the state in the firewall log though and traffic is passed
- Connect from somewhere else (i.e. another internet line) to OPNsense's WAN CARP IP: works

**Comment by marcquark** [comment]
OK i have a workaround using a port-forward rule, example:
- Interface LAN1
- Destination This Firewall, Port 1194 (OpenVPN)
- Redirect Target IP: Any IP that sits on LAN1. I'm using the CARP IP because then i can also sync the rule to my backup device

**Comment by fichtner** [comment]
@marcquark would you mind retesting with stock kernel? we discussed internally briefly and we are not sure about the impact.

**Comment by marcquark** [comment]
reverted back to stock kernel, can't connect anymore (same error again). so the patch definitely fixes the issue

for what it's worth, it's the same on pfsense. i've spent hours scratching my head trying to figure out wth i'm doing wrong. ultimately their support team also confirmed it as a kernel bug.

**Comment by AdSchellevis** [comment]
and this is an ipv4 over ipv6 setup? just asking, because your issue doesn't mention any ipv6.

**Comment by fichtner** [comment]
@marcquark thanks for confirming. we will likely add this patch in the next kernel update (20.7.6) by the looks of it some time around end of November/beginning of December

**Comment by marcquark** [comment]
That would be a great thing!

@AdSchellevis to answer the question, during my initial tests (i.e. up until you asked) everything was IPv4-only. I've now added IPv6 addresses to the WAN side of my lab cluster (one on each interface and a CARP address). Connecting over the internet via IPv6 works fine, too. So i tested the following scenarios:

* IPv4 from LAN
* IPv4 from WAN
* IPv6 from WAN

and that all works. The only thing i couldn't test was connecting from an IPv6-enabled LAN interface because i don't have one in my lab at the moment. Not too much of a concern for me right now though :)

**Comment by AdSchellevis** [comment]
I'm just a bit worried about the release process here, https://reviews.freebsd.org/D24135 doesn't appear to be closed, but the patch does live in https://github.com/freebsd/freebsd/commit/227b726e7f37ee3e87692defb983706c22a62773 upstream.  Maybe it's not an issue we need to solve now, but a clearer tracking of how and when patches are accepted upstream would likely improve the stability of the bsd network stack in general.

**Comment by marcquark** [comment]
closing this one as it's fixed in recent versions
