### ISSUE TITLE
feature: Adding the abbility to Assign static DHCP leases in the DHCP range

### ISSUE THREAD

**Issue by lfirewall1243** [opnsense/core#4444]
It would be perfect to have the abbility to add static leases in the DHCP Range. Like its possible on any other DHCP Server.

**Comment by fichtner** [comment]
Will you be available take potential support cases stemming from this request? ;)

Also, please follow our contribution guide and template.

**Comment by lucas12433** [comment]
I am not really into programming. I dont think I would be a real help.
But when it comes to testing or something else, I am there to support it.

**Comment by Gauss23** [comment]
Have a look at my PR https://github.com/opnsense/core/pull/4447
