### ISSUE TITLE
IDPS: replace current ruleset filter option with policy editor

### ISSUE THREAD

**Issue by AdSchellevis** [opnsense/core#4445]
Problem description
------

Suricata rules can contain metadata, which can identify the intended audience and purpose of rules (such as expected performance impact, cve's and applications involved, etc, etc).

Although you can already change policies on a per rule basis, this is often rather labor extensive and doesn't cope well with future changes. Using the metadata in the rules should ease maintenance. 

While adding these policies it would be practical to move the existing "filter" construction available in the rulesets as well, to avoid confusion on what to set where (in which case as policy would just turn into a filter and action to perform).

Planned change
---------

A new form containing a grid which contains policies in which case someone can select rules from one or multiple rulesets and a planned action to perform. 

An example could be select all threads aimed at `Adobe flash` with `critical severity` and `drop` traffic when hit.

Since the current "drop" filter rules would evaluate as select all `alert` rules in `file` and `drop` traffic, it should be a rather easy migration

**Comment by j0nny55555** [comment]
Hello, 

What controls the state of custom.yaml in /usr/local/etc/suricata and how does it get applied/copied? Also I'm interested in how we might be able to provide a BPF to be used by Suricata + Netmap and/or other packet access methods.

Doing some initial looking around to see how and what controls the state of custom.yaml and further, why if I try to manage it at its location (/usr/local/opnsense/service/templates/OPNsense/IDS) my Suricata will not start correctly, but if I use my own detailed 'custom.yaml' and manually copy over the destination (/usr/local/etc/suricata) and reload/restart Suricata it completes the action with the custom.yaml I have provided.

Further, I have found how to use 'suricata-update' to manage rule modification and after an upcoming release update, the 1+ hour update process now takes 2+ minutes. Vast improvement for suricata-update that comes with Suricata. If we were able to use the Policy+Meta to introduce the disable/enable/drop/modify update that suricata-update can provide we will have a vastly more powerful IDS/IPS Management experience.

OPNSense IDS rules updated via suricata-update:
https://forum.suricata.io/t/slow-suricata-update-on-an-opnsense-router-takes-30-minutes-for-200k-rules/5068/14?u=jonny5

Doing discovery on our Forum:
https://forum.opnsense.org/index.php?topic=44128.msg221528#msg221528
