### ISSUE TITLE
Clients loosing IPv6 address after some time, radvd crashes

### ISSUE THREAD

**Issue by teisho** [opnsense/core#4446]
**Describe the bug**
After a while all clients lose their IPv6 address on all interfaces. After clicking on "restart" in the dashboard of radvd it works again. Sometimes a few hours, sometimes the whole day. radvd seems to crash.

**To Reproduce**
Wait..

**Expected behavior**
Clients should not loose their IPv6 addresses.

**Relevant log files**
I can't find a logfile for radvd, sorry.

**Additional context**

**Environment**
OPNsense 20.7.4-amd64
AMD GX-412TC SOC (4 cores)
Intel i210AT

**Comment by AdSchellevis** [comment]
duplicate https://github.com/opnsense/core/issues/4338, to help track this down, best document your case in the comments there.
