### ISSUE TITLE
virtual ip subnet config gone

### ISSUE THREAD

**Issue by fichtner** [opnsense/core#445]
"i had installed OPNSense some month ago and configured mutliple virtual ips to an interface like 192.168.3.1/24 and then the LAN interface could act as gateway for the network 192.168.3.0. Last weekend i updated to latest version and now i cant give new virtual ips with subnet 24 only 32?"

via: IRC Freenode #OPNsense Whoopi

**Comment by AdSchellevis** [comment]
Are you sure the type was correctly selected? 
If I'm not mistaken, the IP alias must be one address, proxy arp and other may contain nets.
On my end I can create both proxy arps and Other type with different subnets.

**Comment by fichtner** [comment]
He was talking about plain IP alias. It's still an address, but it acts different depending on the subnet mask set. That changed with the transformation I guess?

**Comment by AdSchellevis** [comment]
I'm not fully sure, as far as I know you can only add IP aliases within the net of the interface, I will checkout an older version to be sure what the behaviour was.

**Comment by AdSchellevis** [comment]
Ok, strange... the old version locked "single interface" but let you select a subnet.

**Comment by fichtner** [comment]
You're awesome, thanks! :)
