### ISSUE TITLE
DHCPv4: Allow to create IP pools outside of the directly connected subnets

### ISSUE THREAD

**Issue by tofazzz** [opnsense/core#4450]
Hi all,

Since isc-dhcp44-server-4.4.2_1 supports the feature to configure IP pool outside of a directly connected subnet, it would be possible to have the feature in OPNsense as well?

In order to enable the functionality we  just need to add an empty pool for the directly connected subnet:

subnet XXX.XXX.XXX.XXX netmask XXX.XXX.XXX.XXX {
}

Then it'll be possible to create IP pools for other networks.

Since after the change OPNsense's DHCPv4 will be handling different pool leases, I think it would be needed to reorganize the leases page and divide them in each configured subnet.

Also, if it would be possible to add to the lease counter the total IP configured in a pool (i.e. 5/100) instead of just displaying (5) it would be awesome.

Thank you for your hard work!
tofaz

**Comment by tofazzz** [comment]
What's incomplete?

**Comment by Forsakenrox** [comment]
and so ? Opnsense still cant create pools for virtual ips after 3 years of this PR🤣
