### ISSUE TITLE
Auth - LDAP+TOTP: support case insensitive username match

### ISSUE THREAD

**Issue by AdSchellevis** [opnsense/core#4451]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[x] I have searched the existing issues and I'm convinced that mine is new.

**Is your feature request related to a problem? Please describe.**
Some LDAP servers communicate usernames with mixed cases and authenticate without bothering about case (e.g. root v.s. RoOt).

**Describe the solution you'd like**
It would be practical to allow case insensitive matching when collecting local users, so combining totp with ldap would be more fluent. 

**Describe alternatives you've considered**
Uniform names on import, but it would only fix part of the problem (people can login using `root`, not using `RoOt` ).

**Additional context**
https://forum.opnsense.org/index.php?topic=18251.msg90920

**Comment by AdSchellevis** [comment]
test on OPNsense 20.7.4:
```
opnsense-patch  d992cfc
```

**Comment by CSIR-FB** [comment]
Hi Ad,

I have tested with Win10 and Android on 20.7.4, and can confirm this patch works correctly.
Will ask more people to test for me.

Thank you.
Craig

**Comment by AdSchellevis** [comment]
Hi Craig, 

Thanks for confirming, I expect we will aim for 20.7.6 to include this in the release version.

Best regards,

Ad

**Comment by AdSchellevis** [comment]
reopening this issue, when using local access control lists, the current patch isn't complete. The login page sets `Username` in the session to the name actual provided (e.g. UsEr) which is then used to match ACL's.

relevant code blocks:

https://github.com/opnsense/core/blob/b9823cd4d18c91976231f63d45b0840748eedd8e/src/etc/inc/authgui.inc#L111-L114

https://github.com/opnsense/core/blob/de291e62660996b04d589381cad3396db5e9eb80/src/opnsense/mvc/app/controllers/OPNsense/Base/ControllerRoot.php#L156



https://github.com/opnsense/core/blob/de291e62660996b04d589381cad3396db5e9eb80/src/opnsense/mvc/app/controllers/OPNsense/Base/ControllerRoot.php#L156

**Comment by AdSchellevis** [comment]
short term this https://github.com/opnsense/core/commit/edf1e2e8e03ef90892c480a5e25cb70bf34dfed0 should work, long term the login sequence need some work to make it more consistent https://github.com/opnsense/core/issues/4505

**Comment by AdSchellevis** [comment]
on 20.7.6:

```
opnsense-patch  d992cfc  edf1e2e 9679471
```

should work to apply case insensitivity matching on LDAP as well. cc @CSIR-FB
