### ISSUE TITLE
LDAP server configuration - "Authentication containers" select

### ISSUE THREAD

**Issue by GeoCookie** [opnsense/core#4453]
Hi there,

I got a small question about LDAP configuration with STARTTLS.

When configuring LDAP Server with STARTTLS, the select "Authentication containers" return nothing
![image](https://user-images.githubusercontent.com/43962716/98803485-1fb80980-2415-11eb-997f-3433ee89dff7.png)

This is because OPNSense bind to the LDAP server in TCP standard mode, even if STARTTLS is selected
![image](https://user-images.githubusercontent.com/43962716/98803691-702f6700-2415-11eb-93db-8a49ba4eb30b.png)

![image](https://user-images.githubusercontent.com/43962716/98803508-2cd4f880-2415-11eb-97f4-fab91deccd24.png)

Other than that, LDAP authentication works fine for both webui and OpenVPN login with STARTTLS
![image](https://user-images.githubusercontent.com/43962716/98803531-36f6f700-2415-11eb-88ee-923a42b90e1e.png)

Is it a normal behavior or am I missing something ?

**Comment by GeoCookie** [comment]
**Describe the bug**
When configuring an LDAP server, OPSense uses an insecure connection to the ldap server when the "Select" button of the "Authentication containers" line is clicked even if StartTLS is selected as the transport mode
My OpenLDAP server only accepts secure connections (LDAPS or LDAP / TLS) so the connection is refused.


**To Reproduce**
Steps to reproduce the behavior:
Go to "System: Access: Servers" and click "Add"
![image](https://user-images.githubusercontent.com/43962716/98829123-1fca0080-2439-11eb-941a-35b1995ca678.png)

Type a descriptive name and select LDAP.
Type the hostname and the port value
Select "StartTLS" as transport mode
Type bind credentials and Base DN
![image](https://user-images.githubusercontent.com/43962716/98828300-358af600-2438-11eb-931b-615b73057a93.png)

Choose "Authentication containers" by clicking on the "Select" button
Nothing is returned by OPNSense
![image](https://user-images.githubusercontent.com/43962716/98826446-fa87c300-2435-11eb-8889-d4515b9d88cd.png)


**Expected behavior**
Something as stated in the document: https://docs.opnsense.org/manual/how-tos/user-ldap.html
![image](https://user-images.githubusercontent.com/43962716/98828566-8569bd00-2438-11eb-9e7c-3ac6a690456e.png)


**Screenshots**
On the OpenLDAP server logs, it appears that OPNSense use a non-secured connection to retrieve information, even if StartTLS is selected.
![image](https://user-images.githubusercontent.com/43962716/98828657-a29e8b80-2438-11eb-8964-92b8efeb42de.png)
My OpenLDAP server only accepts secure connections (LDAPS or LDAP / TLS) so the connection is refused.


**Relevant log files**
See screenshots
On the General log in "System: Log Files: General"
![image](https://user-images.githubusercontent.com/43962716/98830259-7b48be00-243a-11eb-93ba-4bf2fc68898c.png)


**Additional context**
OpenLDAP uses a certificate issued by OPNSense, therefore it is trusted
Once the LDAP server is configured, I can retrieve the LDAP users from the "System: Access: Users" menu OPNSense uses a secure TLS connection as expected
![image](https://user-images.githubusercontent.com/43962716/98828793-cc57b280-2438-11eb-8c6f-427a469ae5f9.png)


**Environment**
OPNsense 20.7.4-amd64
FreeBSD 12.1-RELEASE-p10-HBSD
OpenSSL 1.1.1h 22 Sep 2020
Running on a Hyper-V virtual machine

**Comment by cbrueffer** [comment]
Hi @GeoCookie, may I ask why you closed this PR? I'm think I see the same issue with OPNsense 21.1.1 in the following setup:

My network LDAP server is configured as accepting both unencrypted and encrypted (StartTLS or SSL) connections. In the OPNsense "adding an LDAP server" dialog, the connection type is configured as using StartTLS. Clicking `Select` to pick the authentication containers works, but later in the Tester, authentication does not work. If I change the connection type to `TCP - Standard` while leaving everything else unchanged the Tester authentication works.

The problem appears to be in `opnsense-core/src/www/system_usermanager_settings_ldapacpicker.php`, where based on the `urltype` (Standard, StartTLS, SSL) only the scheme (`ldap` or `ldaps`) is set, but not whether or not to use StartTLS.
