### ISSUE TITLE
GIF0 interface doesn't display IPv6 address in console

### ISSUE THREAD

**Issue by chromecapone** [opnsense/core#4457]
I have a tunnel broker account with Hurricane Electric. The connectivity portion works perfectly. No issues there.

On the console, the IPv6 address is not displayed. Not sure why?

![gif0 - console](https://user-images.githubusercontent.com/14158432/98977862-17300380-24e7-11eb-8d34-fbd3f2a9ae90.PNG)

Also, the DDNS (OPT2/GIF0 - Cloudflare) the interface doesn't get updated b/c the DDNS client doesn't have an IP address to read and update. Here's a couple of screenshots to make it alittle clearer...

![DDNS - Dashboard](https://user-images.githubusercontent.com/14158432/98977891-231bc580-24e7-11eb-8df8-056304cb8b68.PNG)

If you look at the Interfaces attachment, you can see that OPT2 has an IP address...but for some reason the address it not displayed in the console...and the DDNS client doesn't pick it up...

![Interfaces - Dashboard](https://user-images.githubusercontent.com/14158432/98977931-3038b480-24e7-11eb-9931-2dfefabc7f02.PNG)

I would expect the IP address to be listed, so, the DDNS can pickup the address and update the DDNS provider (Cloudflare in this case), if the IPv6 address changes.

I am running OPNsense 20.7.4-amd64

If there's something else that I can provide, please let me know.

Thanks.

**Comment by chromecapone** [comment]
I posted this first in the forums... No response.

https://forum.opnsense.org/index.php?topic=19955.0

I don't think it's a support issue... But it definitely could be... Can you help?

**Comment by AdSchellevis** [comment]
Can you post thee output of the following command?

```
ifconfig gif0
```

At a first glance I would expect you have an issue in your `gif` interface configuration, parsing the address shouldn't be different than using any other interface as far as I can remember.

**Comment by fichtner** [comment]
Hmm, gif is the tunnel, the real IPv6 is attached to LAN as far as I can tell?

**Comment by AdSchellevis** [comment]
depending on the connectivity type if I'm not mistaken, on my end a test gif interface has a ipv4 address for example:

```
 OPT8 (gif0)     -> v4: 10.233.1.2/32
```

but it's still early, not enough coffee yet :)

**Comment by fichtner** [comment]
Certainly, having DDNS pick up the IP of the tunnel endpoint is irrelevant because DDNS can pick up the working LAN IPv6. I wouldn't try to glue everything together on the assumption that "it should" work this way because that's a lot of assumptions from a missing IPv6 in the console.

**Comment by chromecapone** [comment]
Thanks Guys for jumping on this one. Here's the output of the ipconfig gif0:

![image](https://user-images.githubusercontent.com/14158432/99086114-0fc83300-2597-11eb-8ba4-0305ff0f9bc8.png)

I redacted a portion of the IP addresses...

**Comment by chromecapone** [comment]
If I change the Cloudflare DDNS v6 to the LAN interface... I get a crash report... 

PHP Warning:  Invalid argument supplied for foreach() in /usr/local/etc/inc/plugins.inc.d/dyndns/phpDynDNS.inc on line 838

And the DDNS still shows N/A for the address

Not sure if the crash is expected...I am doubtful... 

I guess it SHOULD pickup the ipv6 LAN address and report that to CLOUDFLARE v6...

**Comment by chromecapone** [comment]
Any update on this one?
