### ISSUE TITLE
Proxy Transparente ssl man in the middle  + Windows Update

### ISSUE THREAD

**Issue by jcxhard** [opnsense/core#4463]
Hello people,

Using the Transparent Proxy ssl man in the middle, there is a certain difficulty of the hosts when using the windows update, I added some addresses in the Foward Proxy section, SSL in the bump sites, some addresses so that it doesn't pass the proxy's SSL inspection, as shown below :

.microsoft.com
.windowsupdate.com

In the WebProxy in Acess Log, follow this line with error:

0 - TCP_DENIED / 403 18766 GET http://www.microsoft.com/pkiops/certs/Microsoft%20ECC%20Product%20Root%20Certificate%20Authority%202018.crt - HIER_NONE / - text / html; charset = utf-8

**Comment by mimugmail** [comment]
Same as before, please use the forums, there are way more people around spending time to others problems. Thx :)
