### ISSUE TITLE
Proxy Transparente ssl man in the middle

### ISSUE THREAD

**Issue by jcxhard** [opnsense/core#4464]
Hello people!!! 

Has anyone ever experienced this. I'm using Opnsense with transparent proxy, SSL Inspection used, I created the certificate and installed it on the clients. Only that some sites Squid is unable to access appears the message "Error of Issuer Certificate, does not recognize the CA. Dai enabling the SNI Information dai this same site works normally, as it does not filter the SSL content, passing through Squid I noticed that with this option enabled, Clamav stops inspecting malicious sites with the https protocol.

**Comment by mimugmail** [comment]
This is called certificate pinning, for better discussion please open a thread in forums as github is more focused on development topics

**Comment by jcxhard** [comment]
thank you!!!
