### ISSUE TITLE
Firewall: NAT: Outbound

### ISSUE THREAD

**Issue by dstr-wpd** [opnsense/core#4465]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[x] I have searched the existing issues and I'm convinced that mine is new.

**Describe the bug**
Automatic Outbound NAT Rules are not created in the backend or not working as expected. I had to turn automatic NAT rules completely off and had to add an:

WAN | any | * | * | * | Interface address
-- | -- | -- | -- | -- | --

rule in order to get packets out of the physical Interfaces to the WAN interfaces, and back. The problem I observed initially, that NATed packets couldn’t find its way back from the WAN interface into the physical interfaces.

+ when the automatic NAT rules are deleted, they are not being added back when switched to automatic outbound rules.

*Tip*: to validate your setup was working with the previous version, use opnsense-revert (https://docs.opnsense.org/manual/opnsense_tools.html#opnsense-revert)
Will try this now.

Automatic outbound rules activated but not created, and packets not finding its way out.
![opnsense2](https://user-images.githubusercontent.com/74531770/99230832-143b5880-27f0-11eb-8672-2b906e01e9e5.PNG)

I think my other screenshots are worthless

**Environment**

Versions | 
OPNsense 20.7-amd64
FreeBSD 12.1-RELEASE-p7-HBSD
OpenSSL 1.1.1g 21 Apr 2020
Jetway HBJC390F541AA19B
CPU | Intel® Celeron J1900, 2.0GHz Quad-Core SoC, 10W, Bay Trail
LAN | 10 * Intel i211AT Gigabit LAN

**Comment by dstr-wpd** [comment]
Okay I just realized that because of the NAT issue an update wasn’t successfully. I will update to 20.7.4 now and see if this issue still persist.

**Comment by dstr-wpd** [comment]
> Okay I just realized that because of the NAT issue an update wasn’t successfully. I will update to 20.7.4 now and see if this issue still persist.

This bug still persist with 20.7.4. No automatic outbound NAT rules are added when chosen.

**Comment by mimugmail** [comment]
They are only enabled when WAN is DHCP, PPPoE or has an upstream gateway set

**Comment by dstr-wpd** [comment]
right... I've configured the upstream gateway on the WAN interface again and enabled automatic outbound rules. this time it seems to be working as expected.
