### ISSUE TITLE
Squid Web proxy: help text doesn't match dropdown options

### ISSUE THREAD

**Issue by tigersharke** [opnsense/core#4467]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[x] I have searched the existing issues and I'm convinced that mine is new.

**Describe the bug**
The help text for "X-Forwarded-For header handling" dropdown includes an option not available in the dropdown control.

*Tip*: n/a

**To Reproduce**
1. Go to 'Services: Web Proxy: Administration' > 'General Proxy Settings'
2. Click 'advanced mode' , Click 'full help'
3. Scroll down to 'X-Forwarded-For header handling'
4. See described omission.

**Expected behavior**
Help text and available options should match 1:1.  There are six possible options described: "On", Default, "Off", "Transparent", "Delete", "Truncate" but only five possible in dropdown selector. The help text description for the default should be mentioned first, the Delete option added to dropdown selector or its help text removed.

**Screenshots**
![image](https://user-images.githubusercontent.com/2823721/99314273-76af4b80-2826-11eb-8960-e812b8b73a79.png)

![image](https://user-images.githubusercontent.com/2823721/99314238-67300280-2826-11eb-8dfb-194557028b77.png)

**Relevant log files**
n/a

**Additional context**
n/a

**Environment**
OPNsense 20.7.4-amd64FreeBSD 12.1-RELEASE-p10-HBSDLibreSSL 3.1.4
CPU Type | AMD Phenom(tm) II X4 960T Processor (4 cores)

**Comment by AdSchellevis** [comment]
added missing option in https://github.com/opnsense/core/commit/4632286c55864d729ed119fb93b688d1a8d15378, personally I do find the help text a bit too elaborate, but the option delete itself is indeed missing.
