### ISSUE TITLE
NAT reflection for 1:1 (bi)nat not working as expected

### ISSUE THREAD

**Issue by alie2n** [opnsense/core#4469]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[x] I have searched the existing issues and I'm convinced that mine is new.

**Describe the bug**
I'm working with a Opnsense 20.1.7. 
I already checked the box: Firewall->Settings-Advanced->"Reflection for 1:1"
After creating a new 1:1 nat rule several rdr rules are created besides the binat rule. But the rdr rule for the lan interface is missing

*Tip*: to validate your setup was working with the previous version, use opnsense-revert (https://docs.opnsense.org/manual/opnsense_tools.html#opnsense-revert)

**To Reproduce**

1. Go to 'Firewall->NAT->1:1'
2. Create a new NAT Rule
2.1. on interface: wan 
2.2. external network: virtual wan ip/32 (e.g. 1.2.3.4/32)
2.3. type: binat
2.3. source: dmz lan ip/32 (e.g. 10.10.10.100/32)
2.4. Destionation: any
2.5. Nat reflection: use system default

**Expected behavior**
On every other interface (except dmz lan and wan) there should be a rdr rule that forwards traffic from the lan segment(s) to the dmz lan whe accessing the virtual wan ip. As a result I cannot access the dmz lan ip from the lan segment(s). Access is only possible from the internet.

**Additional context**
When I create the port forwarding rule manually on the lan interface I can access the dmz lan ip from the lan segment(s).

**Environment**
OPNsense 20.1.7 (amd64, OpenSSL).
vmWare virtual machine
seven network interfaces
ipsec
manual outbound nat
openvpn
carp ip adresses

**Comment by gslongo** [comment]
Does it has been solved ?

**Comment by alie2n** [comment]
It is working now, but in the mean time we have changed quite a bit and I cannot say for sure what really fixed the issue. 
This issue can stay closed.
