### ISSUE TITLE
gateway name with just numbers is not possible

### ISSUE THREAD

**Issue by colttt** [opnsense/core#4470]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[x] I have read the contributing guidelines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[x] I have searched the existing issues and I'm convinced that mine is new.

**Describe the bug**
in /system_gateways.php the name must have a letter, the description said it must one of the letter a-Z, 0-9, _ but when I just use 7750 as a name it does not work

**To Reproduce**
1. Go to '/system_gateways.php'
2. Click on 'Add'
3. Scroll down to 'use a name with just numbers in it (eg 7750)'

**Expected behavior**
either a correct error message that I can't use only numbers or it should work with just numbers

**Comment by AdSchellevis** [comment]
seems to be a left over from our parent project, in our case it doesn't make sense to check for a valid "alias name" fixed in https://github.com/opnsense/core/commit/9924a2c81156527861ec6fea55596449b7b74c75

**Comment by fichtner** [comment]
I will briefly reopen this:

```
% git grep is_validaliasname
src/etc/inc/util.inc:function is_validaliasname($name)
src/www/firewall_schedule_edit.php:    $valid = is_validaliasname($pconfig['name']);
src/www/system_gateway_groups_edit.php:    $valid = is_validaliasname($pconfig['name']);
```

Looks like is_validaliasname can be shelved completely?

**Comment by AdSchellevis** [comment]
@fichtner I haven't looked at the schedule part, but it definitely seems so, yes
