### ISSUE TITLE
MultiWan Policy based routing and Shared forwarding

### ISSUE THREAD

**Issue by wiesel24** [opnsense/core#4471]
If you activate Shared Forwarding while you using Mutlti Wan with Policy Routing to GW Group in Firewall a lot of packets get denied from the default deny rule. Use Sticky Connection also activated. 
**To Reproduce**
1. Go to 'Firewall -> Advanced -> Shared Forwarding'
2. Click on 'Activate Shared Forwarding'
3. Scroll down to 'Firewall Logs -> Live View '

**Expected behavior**
Is that activating Shared Forwarding also allow to use Shaper with Multi Wan

**Environment**

OPNsense 20.7 (amd64, OpenSSL).
Intel® Xeon™ E3-1225V5 3.3Ghz Quad Core
Network Intel® I210-AT

**Comment by wiesel24** [comment]
related to https://github.com/opnsense/src/issues/38
So it seems this is a pending problem. Any chance to get this fixed with next version?

**Comment by mimugmail** [comment]
No, its more a collection of known limitatons. Multiwan and SF works. Maybe there are some quirks during enabling but in general it works pretty good

**Comment by wiesel24** [comment]
What do you mean with quirks. Tried with reboot, but does not help. I've done everything according to the Multiwan Setup tutorial.

**Comment by mimugmail** [comment]
Please close this one here and go in in forums.

**Comment by wiesel24** [comment]
I've already posted in forum. Nobody had any clue about this issue. For me it's a bug, cause I've already installed a fresh opnsense and only did multiwan setup according to the Multiwan Setup tutorial.

**Comment by fichtner** [comment]
Posting the link with the prior forum discussion is also a good idea while raising issues here to get more context and/or to steer help to where it should go.

**Comment by wiesel24** [comment]
@fichtner My only intention was, tell them that might be a bug and not a wrong configuration. What is wrong with that. It seems that nobody want to investigate any time in a problem from an newbie....

**Comment by mimugmail** [comment]
Please dont take it as an offense, but if I would try to reproduce every problem the ppl post here and in Forums, this would be a full time job (unpaid for sure). Lets try to go on in the Forums. I dont have a loadsharing setup cause I only use failover, but we may find a solution over there. :)

**Comment by wiesel24** [comment]
@mimugmail ok will discuss it further in the forum. I always to try to find solutions. For me it's clear that Opnsense is an Opensource Project and most of you doing it for unpaid....
