### ISSUE TITLE
Unable to add IPv6 phase 2 on routed IPSec

### ISSUE THREAD

**Issue by 11harveyj** [opnsense/core#4472]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[X] I have searched the existing issues and I'm convinced that mine is new. (Not new, however related to #3573 

**Describe the bug**
When adding a new phase 2 entry for a IPSec tunnel with IPv6 addresses, the following errors are seen:
```
A valid local network IP address must be specified.
A valid remote network IP address must be specified.
```

The IP addresses used are in the format:
1234:567:8abc::123

*Tip*: to validate your setup was working with the previous version, use opnsense-revert (https://docs.opnsense.org/manual/opnsense_tools.html#opnsense-revert)

**To Reproduce**
1. Create IPSec phase 1 configuration
2. Add a new phase 2 config in Routed-VTI mode
3. Use IPv6 addresses rather than IPv4 addresses

**Expected behavior**
The IP addresses should be added to the IPSec P2 configuration and also should show as an assigned IP address in the interface configuration. I can confirm this works in PFSense.

**Screenshots**

**Relevant log files**
If applicable, information from log files supporting your claim.

**Additional context**

**Environment**
OPNsense 20.7.4 (amd64, OpenSSL).
Intel® Core 2 Duo E1500
Sophos UTM220r5

**Comment by AdSchellevis** [comment]
phase 1 protocol set to ipv4? route-based to an ipv6 endpint seems to validate fine here.

**Comment by 11harveyj** [comment]
@AdSchellevis - ahh yes, set to IPv4.

However, is there a reason that we can't use both IPv4 and IPv6 addresses in one phase 1 config? Its something that works fine in Pfsense.

**Comment by AdSchellevis** [comment]
I haven't tried it, but I don't mind removing the validation and let you report back if if it works.

**Comment by 11harveyj** [comment]
Could we try it? It might be a useful feature for someone (including me) if they want an IPv4 & IPv6 tunnel in one interface.

**Comment by AdSchellevis** [comment]
```
opnsense-patch 6ae303f
```

**Comment by 11harveyj** [comment]
So, the IPv6 address added successfully and was also assigned to the IPSec interface, but the IPSec link went down and wouldn't come back up... Doing some further testing.

**Comment by 11harveyj** [comment]
Also, when trying to modify the PFS key group for the ipv6 p2 entry, the following error was seen:

`The following input errors were detected:

Phase2 with this Local/Remote networks combination is already defined for this Phase1.`

**Comment by 11harveyj** [comment]
Ok, so, after creating the P2 entry with an IPv6 address, the IPSec interface does assign the correct IP... However... Traffic doesn't seem to route through (the remote IPv6 address does not respond to pings, firewall is open for all traffic).
It also seems that it cannot handle both a P2 entry for an IPv4 and IPv6 address at the same time. Only one of the IP addresses is used. For example, if I do a ifconfig:

ipsec1000: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> metric 0 mtu 1400
        tunnel inet _Local public IPv4 Address_ --> _Remote public IPv4 Address_
        inet6 fe80::21a:8cff:fe3d:2868%ipsec1000 prefixlen 64 scopeid 0x1e
        inet6 _Local P2 IPv6 address_ --> _Remote P2 IPv6 address_ prefixlen 128
        groups: ipsec
        reqid: 1000
        nd6 options=21<PERFORMNUD,AUTO_LINKLOCAL>


Ping from the Diagnostics section of Opnsense UI:

`# /sbin/ping6 -c '3' '_Local P2 IPv6 address_'
PING6(56=40+8+8 bytes) _Local P2 IPv6 address_ --> _Remote P2 IPv6 address_

--- _Remote P2 IPv6 address_ ping6 statistics ---
3 packets transmitted, 0 packets received, 100.0% packet loss`


Checking the IPSec logs, we see:

2020-11-18T17:31:28 | charon[3983] | 16[KNL] <con1\|1> querying policy 0.0.0.0/0 === 0.0.0.0/0 in failed, not found
-- | -- | --
2020-11-18T17:31:28 | charon[3983] | 16[KNL] <con1\|1> querying policy 0.0.0.0/0 === 0.0.0.0/0 in failed, not found
2020-11-18T17:31:27 | charon[3983] | 16[NET] <con1\|1> sending packet: from _Local public IPv4 Address_[500] to _Remote public IPv4 Address_[500] (76 bytes)
2020-11-18T17:31:27 | charon[3983] | 16[ENC] <con1\|1> generating INFORMATIONAL response 817 [ ]
2020-11-18T17:31:27 | charon[3983] | 16[ENC] <con1\|1> parsed INFORMATIONAL request 817 [ ]
2020-11-18T17:31:27 | charon[3983] | 16[NET] <con1\|1> received packet: from _Remote public IPv4 Address_[500] to _Local public IPv4 Address_[500] (76 bytes)
2020-11-18T17:31:18 | charon[3983] | 16[ENC] <con1\|1> parsed INFORMATIONAL response 1162 [ ]
2020-11-18T17:31:18 | charon[3983] | 16[NET] <con1\|1> received packet: from _Remote public IPv4 Address_[500] to _Local public IPv4 Address_[500] (76 bytes)
2020-11-18T17:31:18 | charon[3983] | 16[NET] <con1\|1> sending packet: from _Local public IPv4 Address_[500] to _Remote public IPv4 Address_[500] (76 bytes)
2020-11-18T17:31:18 | charon[3983] | 16[ENC] <con1\|1> generating INFORMATIONAL request 1162 [ ]
2020-11-18T17:31:18 | charon[3983] | 16[IKE] <con1\|1> sending DPD request
2020-11-18T17:31:18 | charon[3983] | 16[KNL] <con1\|1> querying policy 0.0.0.0/0 === 0.0.0.0/0 in failed, not found
2020-11-18T17:31:18 | charon[3983] | 16[KNL] <con1\|1> querying policy 0.0.0.0/0 === 0.0.0.0/0 in failed, not found
2020-11-18T17:31:09 | charon[3983] | 16[KNL] <con1\|1> querying policy 0.0.0.0/0 === 0.0.0.0/0 in failed, not found
2020-11-18T17:31:09 | charon[3983] | 16[KNL] <con1\|1> querying policy 0.0.0.0/0 === 0.0.0.0/0 in failed, not found
2020-11-18T17:31:08 | charon[3983] | 16[NET] <con1\|1> sending packet: from _Local public IPv4 Address_[500] to _Remote public IPv4 Address_[500] (76 bytes)
2020-11-18T17:31:08 | charon[3983] | 16[ENC] <con1\|1> generating INFORMATIONAL response 816 [ ]
2020-11-18T17:31:08 | charon[3983] | 16[ENC] <con1\|1> parsed INFORMATIONAL request 816 [ ]
2020-11-18T17:31:08 | charon[3983] | 16[NET] <con1\|1> received packet: from _Remote public IPv4 Address_[500] to _Local public IPv4 Address_[500] (76 bytes)
2020-11-18T17:30:59 | charon[3983] | 16[ENC] <con1\|1> parsed INFORMATIONAL response 1161 [ ]


P2 entries below:

ESP Route-based | 172.16.55.13 | 172.16.55.14 | AES (256 bits) + SHA256 + 14 (2048 bits)
ESP Route-based | _Local P2 IPv6 address_ | _Remote P2 IPv6 address_ | AES (256 bits) + SHA256 + 14 (2048 bits)

I'm using Opnsense locally, and PFSense on the remote side.

**Comment by AdSchellevis** [comment]
it's probably best to compare `ipsec.conf ` on both sides, I can't pull in large backend changes at the moment since we are already working on a larger overhaul, but if we know what's different we can see if/when we can add it.

**Comment by 11harveyj** [comment]
I've got the 2 ipsec.conf files here..
London is PFSense
Norwich is Opnsense


London:
```
# This file is automatically generated. Do not edit
config setup
        uniqueids = yes

conn bypasslan
        leftsubnet = London LAN IPv4 subnet,London LAN IPv6 subnet
        rightsubnet = London LAN IPv4 subnet,London LAN IPv6 subnet
        authby = never
        type = passthrough
        auto = route

conn con1000
        reqid = 1000
        fragmentation = yes
        keyexchange = ikev2
        reauth = yes
        forceencaps = no
        mobike = no

        rekey = yes
        installpolicy = no

        dpdaction = restart
        dpddelay = 10s
        dpdtimeout = 60s

        auto = start
        left = London WAN IPv4
        right = Norwich WAN IPv4
        leftid = London WAN IPv4
        ikelifetime = 28800s
        lifetime = 3600s
        ike = aes256-aesxcbc-modp4096!
        esp = aes256-sha256-modp2048!
        leftauth = psk
        rightauth = psk
        rightid = Norwich WAN IPv4
        rightsubnet = 172.16.55.13,1234:123:abcd::603,0.0.0.0/0
        leftsubnet = 172.16.55.14,1234:123:abcd::602,0.0.0.0/0

```




Norwich:
```
# This file is automatically generated. Do not edit
config setup
  uniqueids = yes

conn con1
  aggressive = no
  fragmentation = yes
  keyexchange = ikev2
  mobike = no
  reauth = yes
  rekey = yes
  forceencaps = no
  installpolicy = no

  dpdaction = restart
  dpddelay = 10s
  dpdtimeout = 60s

  left = Norwich WAN IPv4
  right = London WAN IPv4

  leftid = Norwich WAN IPv4
  ikelifetime = 28800s
  lifetime = 3600s
  ike = aes256-aesxcbc-modp4096!
  leftauth = psk
  rightauth = psk
  rightid = London WAN IPv4
  reqid = 1000
  rightsubnet = 0.0.0.0/0
  leftsubnet = 0.0.0.0/0
  esp = aes256-sha256-modp2048!
  auto = start

include ipsec.opnsense.d/*.conf
```


Looks like on Pfsense its adding the specific IP addresses under left and right subnet. But on Opnsense its just a "catch-all" `0.0.0.0/0`

**Comment by AdSchellevis** [comment]
I believe their traffic/policy selector isn't correct, in which case the selector should follow the protocol (which I think our end does).

https://github.com/opnsense/core/blob/87efd07831bc136416a5bd435e6bb67716c16ce7/src/etc/inc/plugins.inc.d/ipsec.inc#L1495-L1503

Can you try with OPNsense machines on both ends?

Some references about strongswan VTI we used while implementing the feature (although most is Linux related):

https://wiki.strongswan.org/projects/strongswan/wiki/RouteBasedVPN
https://wiki.strongswan.org/issues/2913

**Comment by 11harveyj** [comment]
No worries. I'll give it a go perhaps this weekend.

**Comment by AdSchellevis** [comment]
@11harveyj any news? or should we close this one?

**Comment by 11harveyj** [comment]
@AdSchellevis no news :( I moved away from Opnsense in the end due to some hardware issues that I couldn't resolve.

Will close. Thank you for your time 👍
