### ISSUE TITLE
Please allow log file live view to be larger, 5000 is current max, 10000 and 20000 options would really help.

### ISSUE THREAD

**Issue by pallebone** [opnsense/core#4476]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:
[-] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
Yes
[-] I have searched the existing issues and I'm convinced that mine is new.
Yes
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I would like to request the option to have a larger log for live view, currently I am finding 5000 entries quite constrained. It is possible to use a syslog server, however in some cases this is not setup or always running and a larger log would really help as hardware has become more powerful and modern, there is no real reason why 5000 was chosen as an arbitrary limit.

**Describe alternatives you've considered**
An alternative (syslog server) would work, but for ease of administration and convenience it would be nice to be able to have a larger log file built into the system, or a configurable value for how many entries you want to keep.

**Additional context**
Thank you for considering this request.

Kind regards
Peter

**Comment by AdSchellevis** [comment]
Hi Peter,

Wouldn't it be more practical to download the log? I can't really imagine it's convenient to scroll through a (filtered set) of more than 5000 records. (it might be sloppy in your browser as well)

Best regards,

Ad Schellevis

**Comment by pallebone** [comment]
Hi,

I can try some other way. I mean the live view is working really well for me right now, I like how it displays. It is very convenient, at least in my opinion, and personally Im not having a performance issue. It would just be nice to be able to see more via the web browser and be able to scroll further back in time. I use it every day in my work flow and my only constraint is that I cannot go back af far as I would like, everything else about it I like.

I mean I can understand if this is not a feature you want to entertain but from my perspective it would be helpful, not sure if its difficult to do or anything but thought I would ask just in case. if not then obviously I will have to try go some other way to do the same thing :)

Kind regards
Peter

**Comment by AdSchellevis** [comment]
Hi Peter,

It's not difficult, just trying to figure out if we're solving the right issue here (missing export of the data in the grid v.s. larger list).  You can easily try if it would work with larger lists in your case by adding options here:

https://github.com/opnsense/core/blob/281f319904bf66094731320e3f4624a8c1c5d94e/src/opnsense/mvc/app/views/OPNsense/Diagnostics/fw_log.volt#L495

Personally a list of > 5000 doesn't feel like something I would like to scroll through on a daily basis, this doesn't mean we shouldn't offer the possibility at all if there are valid use cases for it.

Best regards,

Ad

**Comment by pallebone** [comment]
Hi, 

Ok this is excellent. Are you suggesting I just edit this file and retry? Do I need to restart anything and or provide any feedback afterwards?

Kind regards
Peter

**Comment by AdSchellevis** [comment]
just edit and reload the page. if it solves your issue, we can discuss which entries we might add.

**Comment by pallebone** [comment]
Hi,

This option appears to have worked very well, and done exactly what you said it would.

I had to locate the file in a different area on my system and I just appended a line to the end, but it did work as expected:
![image](https://user-images.githubusercontent.com/11403137/99843165-19c1d700-2b3f-11eb-86fd-bad8990d1be7.png)
![image](https://user-images.githubusercontent.com/11403137/99843200-2ba37a00-2b3f-11eb-8f44-88bf39f39a6f.png)

**Comment by pallebone** [comment]
Thank you :)

**Comment by AdSchellevis** [comment]
@pallebone so, 20.000 records works without issues on your end, which is also the maximum your seeking?

**Comment by pallebone** [comment]
Hi!

Well personally I would be happy with adding the 2 options (10000 and 20000) so that the GUI is consistent in how it offers options, each time multiplying by 2x the previous value offered. Thats just my personal preference, and wouldnt want assume I can speak for everyone in the whole world, but it seems logical to me :)

Also, I would like to confirm on Monday that the solution is working because as it happened there was an update to OpnSense, which I applied today and it has wiped the change I made, so I will need to reapply it (I will have time to do this Monday as its midnight now) and then recheck its working again. I hope this is OK! Dont want to make you do anything without double and triple checking everything for you :)

Kind regards,
Peter

**Comment by AdSchellevis** [comment]
Hi Peter,

Just try this on a console Monday:
```
opnsense-patch 7cb67a9
```

After which you should have the new options available.

Best regards,

Ad

**Comment by pallebone** [comment]
Hi @AdSchellevis 

Thank you, I got home early and tried it today, it works perfectly as you predicted so thank you for this very much!

Also thanks for taking the time to respond to my query and assist in providing a suitable addition for me :)

Kind regards
Pete
