### ISSUE TITLE
FW applying "default blocking rule" ignoring existent rules and "Bypass firewall rules for traffic on the same interface"

### ISSUE THREAD

**Issue by SergioRius** [opnsense/core#4478]
[X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[X] I have searched the existing issues and I'm convinced that mine is new.

**Describe the bug**
The Firewall drops connections without any sense. Even when I have them allowed with rules or between hosts on the same interface and having "Bypass firewall rules for traffic on the same interface" activated. This is constant and I don't know what logic is following or the cause. It's totally unusable and I already brought it up from zero several times with the same rules.

Additionally, IP leases that aren't registered on DHCP are showing in FW logs. I know this is not an attack, but seems like DHCP failing. It had supplied dynamic IPs to macs that had fixed IPs, happened two days ago.

**To Reproduce**
I don't know how to reproduce it. It simply started acting like this more and more after some upgrades.
I had setup two interface groups in the past for rules across several interfaces and I migrated them to floating but it didn't help.
I would gladly send my config file using a private secure channel.

**Screenshots**
![image](https://user-images.githubusercontent.com/1693727/100015766-c10d6b00-2dd8-11eb-896d-fe5af9bd2c39.png)

![image](https://user-images.githubusercontent.com/1693727/100015906-f0bc7300-2dd8-11eb-8d88-f74724693a62.png)

![image](https://user-images.githubusercontent.com/1693727/100015638-97ecda80-2dd8-11eb-8e05-24e1379e1285.png)

**Relevant log files**
Please tell me what logs I should post and I'll gladly do

**Environment**
OPNsense 20.7-amd64
ESXi 6.7 VM

Edit: Added a filter output.
[filter.log](https://github.com/opnsense/core/files/5585983/filter.log)

**Comment by fichtner** [comment]
These are invalid state drops: out of order packets, duplicates, interface mismatch and such. There is a lot of information on default rule drops on the forums.

Cheers,
Franco

**Comment by SergioRius** [comment]
But it is not limited to those packets that I screen captured. I understand what you mean, but how could be that I'm almost without network. It is randomly by device blocking some connections. Some "don't see" an internet connection alive, even when it is. I can write here from this station. NAS seems offline for some devices... It seems to me excessive.

**Comment by mimugmail** [comment]
Why so you see packets for the same network in the Firewall? Usually this is a layer2 problem

**Comment by SergioRius** [comment]
I only have a switch and a physical server+ISP router+Wifi AP in this network now. And I don't have any cable loops that I know.
Should be only a failing switch, then. I'll replace with a brand new that I have at hand and check it.

**Comment by mimugmail** [comment]
Do you use bridging on Firewall?

**Comment by SergioRius** [comment]
Not that I know.

> Do you use bridging on Firewall?

Not that I know.
There are only 4 interfaces for 4 vlans. One being the WAN with the ISP router as only client, one management, iot with almost all devices connected via WiFi and a couple of VM servers, and then the trusted lan with two computers also via WiFi.
There are no vpn or anything aside pihole in a VM. Dhcp serves pihole as dns and pihole transfers to opnsense.

**Comment by SergioRius** [comment]
The ESXi server is connected with only one lan cable and it has only one vswitch with vlans configured.
Opnsense is a VM on a trunk.

**Comment by mimugmail** [comment]
So, if neither 192.168.50.201  nor 192.168.50.203 is the IP of OPNsense, you have a problem in your Layer2 subnet, and when you use virtual AND trunk on a vswitch I'd guess it's a misconfig of ESX.

Better to reach out at the forums as there are way many more users with such experience as here are most dev-only guys without ESX background

**Comment by SergioRius** [comment]
In firmware it says that there are plugins "missing" ¿?

```
os-sensei (missing) | N/A | N/A | N/A | -- | -- | -- | -- | --
os-sunnyvalley (missing) | 1.2 | 324B | Vendor repository for Sensei (Next Generation Firewall Extensions)

```
I can't do anything about this.

**Comment by mimugmail** [comment]
This means you restored the config from a backup and in the new installation the packages are not installed yet.

**Comment by SergioRius** [comment]
Also, I just tried to save a change to dashboard and it thrown an error, but in the info I see things that can be related to network:
fw wan vlan ip / wan vlan -> `arpresolve: can't allocate llinfo for 192.168.8.1 on em0_vlan8`

Update also seems stuck fetching the first package (unbound) but inet is online.

[dmesg_boot.log](https://github.com/opnsense/core/files/5589388/dmesg_boot.log)

**Comment by mimugmail** [comment]
> Better to reach out at the forums as there are way many more users with such experience as here are most dev-only guys without ESX background

...

**Comment by SergioRius** [comment]
I can confirm that the problem was a failing switch. A full power cycle (with rest until cold) solved the continuous blockages in the FW, and it seems to degrade with time.
There may be other configuration problems due to a configuration import during a migration with residual tags present. I found things related to CARP and unbound that shouldn't be there. I'll start a new VM from scratch.
Thanks and sorry for the false positive.

**Comment by SergioRius** [comment]
Nope. The issue persists and it's caused by opnsense.
As the issue seemed to be solved, I deactivated the logs for some rules. After deactivating logs for "igmp announces" rule I noticed that plenty of those hits where still logged, so I went to reset the states and here we go, with the fw log crazy with all kinds of blocks as it was before.
Letting it rest doesn't make it work again.

**Comment by db260179** [comment]
It seems like you are suffering from Asymmetric routing, in one of the blocks, click on the info, does it show PA,RA?

So a good start to diagnose this is do some packet capture, then debug in wireshark, and look for connection drops or any related issues.

We dont know what your routing structure is or gateways is setup, but from my own personal experience with both pfsense and opnsense, Two firewall options I have to tweak are setting 'Sloppy state' on rules and 'State timeouts (default is 30s)'

Usually this corrects most of default blocking issues.

**Comment by upended** [comment]
I am having a similar issue, where rules allowing Inbound FW proxy (for http, https, and ftp) are being ignored. The lower deny rule is being used thus blocking said traffic.

Should I add my information to this ticket or create another one?

Note: I have captures, the flags on the packets are ONLY sync (not PA, etc) from what I have gathered so far.
  
The Firewall: Diagnostics: States Dump AND Firewall: Diagnostics: pfTop both do not have any listings for the ports in question.

**Comment by darzanebor** [comment]
had similar issues, not adequate firewall behavior in opnsense, switched to pfsense and it work like a charm. I configure firewall rules as I like and they are applied with no issues. Several times tried to switch to opnsense but without working firewall it loos any sense to have it. :(

**Comment by worldomkar** [comment]
This is a big showstopper. I believe this started at least a couple of months, where I started using squid on opnsense to enable devices on my network get to internet.

This is a case for all default opnsense wizard setup - and run through numerous sequential updates to latest packages - and rebooted each time.

Squid package works flawlessly, but default routing blocks legit traffic - observable from sluggish performance. Simple "brew upgrade" on MacOS hangs - and no it's not Mac issue - on mobile hotspot things are fluid.

I can see from Live firewall log the legit connections are being flagged as state violation.
Even tweaking firewall optimisation doesn't help or change its behaviour a bit.

In its current state, though awesome, it renders opnsense useless for acting as basic home firewall router for me.
