### ISSUE TITLE
Certain ET rulesets don't install properly

### ISSUE THREAD

**Issue by shonjir** [opnsense/core#4479]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[X] I have searched the existing issues and I'm convinced that mine is new.

**Describe the bug**
Some Emerging Threats rule files aren't populated with downloaded rules and instead only contain an <code>opnsense_download_hash</code> header.  It seems that only rule files that are prefixed with 'emerging-' contain rules.

The following ruleset categories are affected:

- botcc.rules
- botcc.portgrouped.rules
- ciarmy.rules
- compromised.rules
- drop.rules
- dshield.rules
- tor.rules

I've verified that this affects the core et-open ruleset and the et-telemetry plugin on my installation.  It may also affect et-pro but I have no way of testing this.

*Tip*: to validate your setup was working with the previous version, use opnsense-revert (https://docs.opnsense.org/manual/opnsense_tools.html#opnsense-revert)

I have just enabled the IPS for the first time on OPNsense 20.7 so I do not know when the bug began.

**To Reproduce**
1. Enable any of the aforementioned rulesets (ex: ET-open/botcc.rules).
2. Open a shell on the firewall
3. Navigate to /usr/local/etc/suricata/opnsense.rules
4. cat botcc.rules
5. Observe there are no rules in the file

An affected rule file looks like this:

<code>root@OPNsense:/var/unbound/etc # more /usr/local/etc/suricata/opnsense.rules/botcc.rules
#@opnsense_download_hash:e214f8d0ae092644570cca4c940bba2e</code>

In the UI, searching the rules tab for 'botcc' also results in no rules displayed.

**Expected behavior**
The rules files would contain rules, and rules would be available in the UI for the selected category.

For example, ET-open/botcc.rules:
https://rules.emergingthreats.net/open/suricata-5.0/rules/botcc.rules

As of the time of this bug report botcc.rules has the following as the first few rules:

<code>alert ip $HOME_NET any -> [109.196.130.50,151.13.184.200] any (msg:"ET CNC Shadowserver Reported CnC Server IP group 1"; reference:url,doc.emergingthreats.net/bin/view/Main/BotCC; reference:url,www.shadowserver.org; threshold: type limit, track by_src, seconds 3600, count 1; flowbits:set,ET.Evil; flowbits:set,ET.BotccIP; classtype:trojan-activity; sid:2404000; rev:5923; metadata:affected_product Any, attack_target Any, deployment Perimeter, tag Shadowserver, signature_severity Major, created_at 2012_05_04, updated_at 2020_11_20;)
alert ip $HOME_NET any -> [154.35.64.107,154.35.64.18] any (msg:"ET CNC Shadowserver Reported CnC Server IP group 2"; reference:url,doc.emergingthreats.net/bin/view/Main/BotCC; reference:url,www.shadowserver.org; threshold: type limit, track by_src, seconds 3600, count 1; flowbits:set,ET.Evil; flowbits:set,ET.BotccIP; classtype:trojan-activity; sid:2404001; rev:5923; metadata:affected_product Any, attack_target Any, deployment Perimeter, tag Shadowserver, signature_severity Major, created_at 2012_05_04, updated_at 2020_11_20;)
alert ip $HOME_NET any -> [154.35.64.54,154.35.64.82] any (msg:"ET CNC Shadowserver Reported CnC Server IP group 3"; reference:url,doc.emergingthreats.net/bin/view/Main/BotCC; reference:url,www.shadowserver.org; threshold: type limit, track by_src, seconds 3600, count 1; flowbits:set,ET.Evil; flowbits:set,ET.BotccIP; classtype:trojan-activity; sid:2404002; rev:5923; metadata:affected_product Any, attack_target Any, deployment Perimeter, tag Shadowserver, signature_severity Major, created_at 2012_05_04, updated_at 2020_11_20;)
alert ip $HOME_NET any -> [174.59.20.100,176.34.209.220] any (msg:"ET CNC Shadowserver Reported CnC Server IP group 4"; reference:url,doc.emergingthreats.net/bin/view/Main/BotCC; reference:url,www.shadowserver.org; threshold: type limit, track by_src, seconds 3600, count 1; flowbits:set,ET.Evil; flowbits:set,ET.BotccIP; classtype:trojan-activity; sid:2404003; rev:5923; metadata:affected_product Any, attack_target Any, deployment Perimeter, tag Shadowserver, signature_severity Major, created_at 2012_05_04, updated_at 2020_11_20;)
</code>

**Screenshots**
Not applicable.

**Relevant log files**
No logs are generated for the rule update.

**Additional context**

**Environment**
OPNsense 20.7.5-amd64
FreeBSD 12.1-RELEASE-p10-HBSD
OpenSSL 1.1.1h 22 Sep 2020

**Comment by AdSchellevis** [comment]
when using et-open these should contain content, when using etpro-telemetry, these won't. so the question is, are you using ETPro-Telemetry?

**Comment by shonjir** [comment]
Using telemetry.  At the very least this violates the principle of least surprise.  If those rules aren't present in telemetry they should not be selectable, and the text should indicate that the rules are nerfed.
