### ISSUE TITLE
Feature - two-factor authentication

### ISSUE THREAD

**Issue by tortellini28** [opnsense/core#449]
Feature Request:

Have packages and a dedicated web page for two-factor authentication to login into the web admin pages, SSH, VPN, etc.

Duo Security is popular two-factor.

**Comment by sjorge** [comment]
yubikey is also pupular

**Comment by oparoz** [comment]
I think a standard 2FA should be used so that we can simply use an app.

**Comment by 8191** [comment]
One premise from my side: the second factor should - for obvious reasons - not require any Internet connection.

**Comment by AdSchellevis** [comment]
For all components using our shared authentication system (not being console/ssh), one time passwords based on RFC 6238 (http://tools.ietf.org/html/rfc6238) are available in our repository now.

Usage is quite simple, add a new server using the type "Local + Timebased One Time Password" and generate an otp seed for all affected users in the user manager.
Google provides an easy app to use this kind of tokens on your mobile (https://support.google.com/accounts/answer/1066447), a link with QRcode is provided in the help message of the otp seed.

**Comment by fichtner** [comment]
Push with 16.1.14? :)

**Comment by AdSchellevis** [comment]
@fichtner sure, why not :) impact is low... only need to make sure the local auth change (https://github.com/opnsense/core/commit/109fb513378be6eb50d72b9c77a650e75243bc39) is in there as well.

**Comment by fichtner** [comment]
@AdSchellevis saw this, ok, will add it to 16.1.14. good stuff. 👍

**Comment by linuxmail** [comment]
hi,

I would find it also great, if Yubikey where supported, with a custom server URL. In this case, Yubi is not authenticated against the cloud service, but an own Yubi server :-)
