### ISSUE TITLE
Adding a dual stack rule with IPv6-only L4 protocol prevent the firewall from starting

### ISSUE THREAD

**Issue by kedare** [opnsense/core#4493]
**Describe the bug**
When adding a IPv4+IPv6 rule applying to a IPv6-ICMP protocol, I am not getting any error when applying the rule from the web UI, but at the next reboot of the device, the firewall service will fail to start and complain of an error at the following line (/tmp/rules.debug) 

```
pass in quick on igb1_vlan101 inet proto ipv6-icmp from {any} to {any} keep state label "f319cdcfed31fd3af08b790a85cec5ef"
```

Disabling the rule in the web ui fix the issues, maybe there should be some kind of validation to avoid putting this kind of rule ?

**To Reproduce**
1. Go to your firewall rules
2. Add a new 'IPv4+IPv6' rule with a L4 protocol condition to IPv6-ICMP
3. Click 'Apply the firewall changes'
4. Reboot
5. You will see in the boot logs that the firewall rules have failed to load and you will probably not have IPv4 Internet access if you depend on NAT

**Expected behavior**
An error should show up when validating the form or when reloading the rules first, to prevent the whole firewall to break at reboot.

**Environment**
OPNsense 20.7.5-amd64
FreeBSD 12.1-RELEASE-p10-HBSD
OpenSSL 1.1.1h  22 Sep 2020

**Comment by fichtner** [comment]
What is the error message in this case?

**Comment by AdSchellevis** [comment]
/tmp/rules.debug:xxx: proto icmp6 doesn't match address family inet

**Comment by kedare** [comment]
Yes indeed this was the error message, I could not reproduce the issue without breaking my network as I don't have a lab setup for opnsense :)

Also do we know if the opposite happens ? (ICMP protocol when address family is IPv6 will break it too?)

Thanks for the fix :)
