### ISSUE TITLE
pf: reply-to not set for IPv6 GW

### ISSUE THREAD

**Issue by kulikov-a** [opnsense/core#4494]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[-] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[-] I have searched the existing issues and I'm convinced that mine is new.

**Describe the bug**
Hello everybody.
I noticed that for rules with a permitted reply-to directive, this directive is not set for the corresponding rule in rule.debug with the inet6 protocol.
Is that what you intended? If so, please explain why?
This can be easily fixed in the Gateways.php  getInterfaceGateway function:
**before (set only ipv4 gw name):**
 // The interface might have a gateway configured
            if (isset($this->configHandle->interfaces->$interface)) {
                $intf_gateway = $this->configHandle->interfaces->$interface->gateway;
            } else {
                $intf_gateway = null;
            }
**after (set gw name according to ip ver):**
  // The interface might have a gateway configured
            if (isset($this->configHandle->interfaces->$interface)) {
                if ($ipproto == "inet") {
                    $intf_gateway = $this->configHandle->interfaces->$interface->gateway;
                } else {
                    $intf_gateway = $this->configHandle->interfaces->$interface->gatewayv6;
                }
            } else {
                $intf_gateway = null;
            }

Thanks!

**Environment**
Software version used and hardware type if relevant.
e.g.:

OPNsense 20.7.4

**Comment by AdSchellevis** [comment]
@kulikov-a looks like a bug to me, https://github.com/opnsense/core/commit/80d7eb0ea7c42dee23429541eeb4664d14f3a40f should fix it.
