### ISSUE TITLE
PHP script killing system (/usr/local/opnsense/scripts/dhcp/prefixes.php)

### ISSUE THREAD

**Issue by Uglymotha** [opnsense/core#4496]
PHP processes keep piling up until they completely kill my system. I have to kill -9 them and then restart the webgui.

OPNsense 20.7.5-amd64
FreeBSD 12.1-RELEASE-p10-HBSD
OpenSSL 1.1.1h 22 Sep 2020

Intel(R) Atom(TM) CPU C2750 @ 2.40GHz (8 cores)
16GB memory.

last pid: 21828;  load averages: 42.68, 42.11, 41.15                                                                                                                   up 2+16:51:52  08:59:51
137 processes: 41 running, 95 sleeping, 1 zombie
CPU: 97.3% user,  0.0% nice,  2.0% system,  0.7% interrupt,  0.0% idle
Mem: 1727M Active, 7762M Inact, 2568M Wired, 1486M Buf, 5094M Free
Swap: 8192M Total, 8192M Free

  PID USERNAME    THR PRI NICE   SIZE    RES STATE    C   TIME    WCPU COMMAND
99267 root          1  78    0   180M   139M RUN      5   0:33  22.79% php
53268 root          1  78    0   180M   139M CPU5     5  25:39  22.40% php
 8009 root          1  77    0   180M   139M CPU7     7  70:23  22.15% php
10711 root          1  78    0   180M   139M RUN      2  71:06  21.76% php
41482 root          1  78    0   180M   139M RUN      6  54:02  21.64% php
14513 root          1  78    0   180M   139M RUN      6  38:51  21.29% php
50502 root          1  77    0   180M   139M RUN      1   2:05  21.28% php
95803 root          1  78    0   180M   139M RUN      2  34:22  21.01% php
26951 root          1  77    0   180M   139M RUN      1  56:07  20.78% php
88505 root          1  77    0   180M   139M RUN      7  76:02  20.76% php
21427 root          1  78    0   180M   139M RUN      2   5:44  20.59% php
84324 root          1  78    0   180M   139M RUN      5  62:07  20.54% php
77888 root          1  77    0   180M   139M RUN      0  36:27  20.23% php
22115 root          1  77    0   180M   139M CPU3     3  51:03  19.66% php
49015 root          1  77    0   180M   139M RUN      0  66:00  19.64% php
 6399 root          1  77    0   180M   139M RUN      4  27:03  19.54% php
69112 root          1  77    0   180M   139M RUN      3  32:45  19.22% php
81307 root          1  78    0   180M   139M RUN      4  27:45  19.18% php
 5725 root          1  77    0   180M   139M RUN      7  26:20  19.08% php
19032 root          1  77    0   180M   139M RUN      7  68:46  19.07% php
78005 root          1  77    0   180M   139M RUN      0  49:48  19.00% php
69272 root          1  77    0   180M   139M RUN      6  47:53  18.85% php
40220 root          1  77    0   180M   139M RUN      1  64:56  18.80% php
61401 root          1  77    0   180M   139M RUN      0  31:04  18.62% php
64220 root          1  77    0   180M   139M RUN      3   5:05  18.49% php
21070 root          1  77    0   180M   139M RUN      6  23:26  18.40% php
89111 root          1  77    0   180M   139M CPU0     0  41:00  18.40% php
21091 root          1  77    0   180M   139M RUN      5  24:54  18.32% php
20546 root          1  77    0   180M   139M RUN      6   1:38  18.12% php
11478 root          1  77    0   180M   139M RUN      7  63:22  18.10% php
38040 root          1  77    0   180M   139M RUN      4  73:10  18.03% php
39348 root          1  77    0   180M   139M RUN      3  79:25  17.63% php
 1649 root          1  77    0   180M   139M RUN      1  35:52  17.63% php
78890 root          1  77    0   180M   139M CPU4     4  46:45  17.55% php
 3406 root          1  77    0   180M   139M RUN      2  40:18  17.54% php
67685 root          1  77    0   180M   139M RUN      1   8:52  17.05% php

# ps aux |grep php
root      20546 21.7  0.9  184008 142784  -  R    08:50      1:58.82 /usr/local/bin/php /usr/local/opnsense/scripts/dhcp/prefixes.php
root      64220 21.4  0.9  184008 142768  -  R    08:32      5:25.40 /usr/local/bin/php /usr/local/opnsense/scripts/dhcp/prefixes.php
root      19032 21.3  0.9  184008 142616  -  R    03:54     69:07.09 /usr/local/bin/php /usr/local/opnsense/scripts/dhcp/prefixes.php
root      14513 21.1  0.9  184008 142696  -  R    05:50     39:10.99 /usr/local/bin/php /usr/local/opnsense/scripts/dhcp/prefixes.php
root      61401 21.0  0.9  184008 142704  -  R    06:22     31:24.17 /usr/local/bin/php /usr/local/opnsense/scripts/dhcp/prefixes.php
root      84324 21.0  0.9  184008 142648  -  R    04:20     62:27.76 /usr/local/bin/php /usr/local/opnsense/scripts/dhcp/prefixes.php
root      95803 21.0  0.9  184008 142696  -  R    06:09     34:42.66 /usr/local/bin/php /usr/local/opnsense/scripts/dhcp/prefixes.php
root      49015 20.9  0.9  184008 142620  -  R    04:05     66:20.35 /usr/local/bin/php /usr/local/opnsense/scripts/dhcp/prefixes.php
root      21070 20.8  0.9  184008 142704  -  R    06:58     23:46.25 /usr/local/bin/php /usr/local/opnsense/scripts/dhcp/prefixes.php
root       5725 20.7  0.9  184008 142728  -  R    06:43     26:40.44 /usr/local/bin/php /usr/local/opnsense/scripts/dhcp/prefixes.php
root      41482 20.6  0.9  184008 142668  -  R    04:50     54:22.35 /usr/local/bin/php /usr/local/opnsense/scripts/dhcp/prefixes.php

**Comment by AdSchellevis** [comment]
best check your logs, likely a cause of excessive dhcp reloads (could be due to interface reloads or stability issues). The script itself looks old and inherited (https://github.com/opnsense/core/blob/stable/15.7/src/sbin/prefixes.php) the actual intend isn't very clear and when using a large log buffer, this will take ages to finish.

**Comment by Uglymotha** [comment]
You're right. Had a look at the script, and though I'm no php programmer it seems the scripts walks the log to find released prefixes to remove them from the route table. I wonder if that's really needed.

Anyway I had a large logfile size set to 200M and clearing and reinitializing the dhcpd.log to a smaller size fixes the issue.

Also found that the backend log was full of these messages:

2020-12-03T09:23:31 | configd.py[37856] | unable to sendback response [Error (-15) ] for [dhcpd][update][['prefixes']] {0df17e5d-a147-4516-90fa-403cd6972a06}, message was Traceback (most recent call last): File "/usr/local/opnsense/service/modules/processhandler.py", line 202, in run self.connection.sendall(('%s\n' % result).encode()) BrokenPipeError: [Errno 32] Broken pipe
-- | -- | --
