### ISSUE TITLE
Support IP2Location Lite as alternate to Maxmind for GeoIP

### ISSUE THREAD

**Issue by Taomyn** [opnsense/core#4498]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[X] I have searched the existing issues and I'm convinced that mine is new.

**Is your feature request related to a problem? Please describe.**
The Maxmind GeoIP is not the only provider plus in my experience seems to be missing many IP to Location entries - I am constantly seeing mail server connections from RU/CN and other countries I have set to be blocked still reaching my internal network.

**Describe the solution you'd like**
Add support for IP2Location's Lite service which when I have looked up the IPs not present in the Maxmind data has so far always been present with IP2Location files: https://lite.ip2location.com/database/ip-country

**Additional context**
Take your pick of which files to support:
![image](https://user-images.githubusercontent.com/4365929/101018758-3d881280-356c-11eb-8453-90028375e8f7.png)

**Comment by ip2location** [comment]
@Taomyn Glad you find IP2Location LITE database useful.

If opnsense interested to integrate IP2Location LITE, please ping us and we are pleased to assist in term of integration.

**Comment by AdSchellevis** [comment]
We don't have immediate plans to include geoip databases, partly because our business edition comes with a (commercial) geoip database included and the format we support is well described in our docs (https://docs.opnsense.org/manual/aliases.html#geoip). Offering a feed for OPNsense should be rather easy
