### ISSUE TITLE
IPSec: Unable to connect from OS X's built in VPN-client.

### ISSUE THREAD

**Issue by tyrefors** [opnsense/core#45]
While trying to connect to an IPSec-server via OS X's built in VPN client these errors occur:
Feb 11 20:55:47	charon: 03[NET] sending packet: from [server-ip][500] to [client-ip][500] (36 bytes)
Feb 11 20:55:47	charon: 03[ENC] generating INFORMATIONAL response 0 [ N(INVAL_MAJOR) ]
Feb 11 20:55:44	charon: 03[NET] received unsupported IKE version 1.0 from [client-ip], sending INVALID_MAJOR_VERSION
Feb 11 20:55:44	charon: 03[NET] sending packet: from [server-ip][500] to [client-ip][500] (36 bytes)
Feb 11 20:55:44	charon: 03[ENC] generating INFORMATIONAL response 0 [ N(INVAL_MAJOR) ]
Feb 11 20:55:41	charon: 03[NET] received unsupported IKE version 1.0 from [client-ip], sending INVALID_MAJOR_VERSION
Feb 11 20:55:41	charon: 03[NET] sending packet: from [server-ip][500] to [client-ip][500] (36 bytes)

**Comment by tyrefors** [comment]
This was fixed in a pfsense snapshot on June 24th, 2014 (see https://forum.pfsense.org/index.php?topic=78431.0).

The issue seems to be that StrongSwan was built without support for IKEv1.

**Comment by fichtner** [comment]
Thanks, will see if this gets bumped into 15.1.6. :)

**Comment by fichtner** [comment]
Should be fixed via https://github.com/opnsense/tools/commit/b4156f168eccf50f17d44a063189e3ac700005cc
