### ISSUE TITLE
status.php: add limiter info reminiscent m0n0wall

### ISSUE THREAD

**Issue by fichtner** [opnsense/core#450]

**Comment by AdSchellevis** [comment]
@fichtner I don't think m0n0 had limiter statistics, not 100% sure, but I think ipfw only provides statics of the running pipes.

**Comment by fichtner** [comment]
Referencing what @skarekrow said "just basic statistics showing me the bits/kbits/mbits a second for each pipe/queue it is in. "

I looked, it may be ipf related? we do have all the ipfw stuff, that's the same...

**Comment by AdSchellevis** [comment]
If this shows all needed:
/sbin/ipfw pipe show
/sbin/ipfw queue show

It shouldn't be to to big of an issue, parse and hook it into configd. If we're looking for something else... it might be difficult.

**Comment by fichtner** [comment]
@skarekrow does the above suffice?
@AdSchellevis can you provide a sample output for reference?

**Comment by AdSchellevis** [comment]
root@fw1:~ # /sbin/ipfw queue show
q10000  50 sl. 1 flows (1 buckets) sched 10000 weight 100 lmax 0 pri 0 droptail
BKT Prot ___Source IP/port____ ____Dest. IP/port____ Tot_pkt/bytes Pkt/Byte Drp
  0 ip           0.0.0.0/0             0.0.0.0/0        3      499  0    0   0
q10001  50 sl. 0 flows (1 buckets) sched 10000 weight 100 lmax 0 pri 0 droptail

root@fw1:~ # /sbin/ipfw pipe show
10000:  10.000 Mbit/s    0 ms burst 0 
q141072  50 sl. 0 flows (1 buckets) sched 75536 weight 0 lmax 0 pri 0 droptail
 sched 75536 type FIFO flags 0x0 0 buckets 0 active

**Comment by skarekrow** [comment]
That should suffice yes, thanks @fichtner @AdSchellevis! I just needed a way to see what queue my rules were matching for my sanity, and to monitor them when tweaking them further.

**Comment by skarekrow** [comment]
I confirmed that m0n0wall used `ipfw show` to let me see each rule. That alone is sufficient for me as I can clearly see what is matching and if packets are going in. I'm not going to say no to a fancy GUI that does the work for me :P But that alone would suffice. :)

**Comment by fichtner** [comment]
Added ipfw queue and pipe info to status.php, will all be available in 15.7.19

**Comment by skarekrow** [comment]
Thanks!
