### ISSUE TITLE
IPv6 IPSEC breaks firewall

### ISSUE THREAD

**Issue by Uglymotha** [opnsense/core#4502]
When using IPv6 IPSEC VPN, opnsense apparently autocreates some incorrect firewall rules.

Dec  5 12:33:18 rdifw01 opnsense[31248]: /usr/local/etc/rc.filter_configure: There were error(s) loading the rules: /tmp/rules.debug:656: no routing address with matching address family found. - The line in question reads [656]: pass in log on lagg3_vlan34 reply-to ( lagg3_vlan34 82.197.194.1 ) proto udp from {2a02:a449:5bed:1::1} to {any} port {500} keep state label "4efa00dbb8dc13c5842f13c5dfe5e5f1" # IPsec: RobsMind IPv6

Either disabling the auto rule creation for IPSEC or setting the parent interface to any works around this.

**Comment by fichtner** [comment]
This might be https://github.com/opnsense/core/issues/4494 (fix included)

**Comment by Uglymotha** [comment]
Tried but no success. This issue lies a little bit deeper and it is because I use a 6RD configuration, so there is:
1. A valid IPv4 address on the interface, ( lagg3_vlan34 82.197.194.1 ) and it is not possible to select the wan_stf interface here.
2. No explicit IPv6 Gateway set because it's 6RD.

Probably the functionality should be changed to not autocreate these pf rules for ipv6 (6rd) interfaces, since it is not needed in this situation (no NAT).
May be a good idea to offer the autocreation of pf rules on a per P1 basis instead of just 1 global setting. Since just switching it off breaks IPv4 tunnels which do need this. Probably me, but I have not been able to create these rules manually.

**Comment by Uglymotha** [comment]
OPNsense 20.7.5-amd64
FreeBSD 12.1-RELEASE-p10-HBSD
OpenSSL 1.1.1h 22 Sep 2020
