### ISSUE TITLE
add some futures in unbound dns 

### ISSUE THREAD

**Issue by amrahmades** [opnsense/core#4507]
hello  ,, 

its seems GUI doesn't have an option for DNS over TLS yet, which will be a great add  !

also options like  Aggressive NSEC
https://tools.ietf.org/html/rfc8198

Bit 0x20 Support 
https://tools.ietf.org/html/draft-vixie-dnsext-dns0x20-00

**Comment by Bramzor** [comment]
There is a DNSCrypt plugin that can be used for DNSoverTLS. In that case you can either use that one as DNS server or you can pass Unbound towards DNSoverTLS like mentioned on this page: https://forum.opnsense.org/index.php?topic=10670.0

**Comment by amrahmades** [comment]
1 - using two DNS servers is quite annoying :/ , i believe it better to relay on only one , while UNBOUND is supporting TLS, beside other privacy/security features.

2 - i was able to activate DNS over TLS by filling TLS server list , but it will not work unless remove servers list form general configuration (system itself) . i think it's going to be better if unbound able to grab system dns server list, and start DoT if option selected , Thoughts?

**Comment by amrahmades** [comment]
@AdSchellevis 

is any thing is not clear about adding option for  Aggressive NSEC and , Bit 0x20 Support ?

1 -  Aggressive Use of DNSSEC-Validated Cache:
   This increases performance, decreases latency, decreases
   resource utilization on both authoritative and recursive servers, and
   increases privacy.
   
   2 -  Use of Bit 0x20 in DNS Labels to Improve Transaction Identity .
   
   Thoughts?

**Comment by AdSchellevis** [comment]
best read the contribution guidelines about issues and feature requests (https://github.com/opnsense/core/blob/master/CONTRIBUTING.md)
