### ISSUE TITLE
TOTP input field not displayed at Tester

### ISSUE THREAD

**Issue by ericschdt** [opnsense/core#4509]
**Important notices**
[x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
[x] I have searched the existing issues and I'm convinced that mine is new.

**Describe the bug**
I set up a `Local+Timebased One Time Password` server as described here:
https://docs.opnsense.org/manual/how-tos/two_factor.html#step-1-add-new-authentication-server

Further I generated a TOTP secret key and scanned the QR code with andOTP.

Now when I wanted to test it at `System -> Access -> Tester` and choose the TOTP server, I do not see any TOTP input field.
If I enter the correct credentials and click on "OK" it says 
> The following input errors were detected:  Authentication failed.

as expected. 

**Screenshots**
![Screenshot_20201209_143818](https://user-images.githubusercontent.com/43318127/101637248-699c0b80-3a24-11eb-9f21-97531bf9dbf9.png)

**Environment**
OPNsense 20.7.6-amd64
Firefox 83 (all content blocking addons are disabled for OPNsense)

**Firefox console output** 
(German though) Does not show anything obvious to me:
[console-export-2020-12-9_13-44-46.txt](https://github.com/opnsense/core/files/5666241/console-export-2020-12-9_13-44-46.txt)

**Comment by AdSchellevis** [comment]
https://docs.opnsense.org/manual/how-tos/two_factor.html#step-5-test-the-token

> Select the Authentication server you have configured, and enter the user name. Then enter the *token + password, remember the order is token and then password in the same field.

**Comment by ericschdt** [comment]
I am pretty sure I follows the instructions:

![Screen Capture_select-area_20201209145758](https://user-images.githubusercontent.com/43318127/101639052-c00a4980-3a26-11eb-89f4-dd45f04fa38c.gif)

**Comment by AdSchellevis** [comment]
entered the token followed by the password in the password field and the time is right? these are the most common mistakes made by our users.

**Comment by ericschdt** [comment]
Thanks, that I missed this point. An extra field would feel more intuitive to me though.
