### ISSUE TITLE
Interface Statistics Widget table rotation

### ISSUE THREAD

**Issue by FingerlessGlov3s** [opnsense/core#4510]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[X] I have searched the existing issues and I'm convinced that mine is new.

**Is your feature request related to a problem? Please describe.**
As you can see my screenshot below and this is on a 1440p monitor by the way, is that I have so many interfaces, that the table gets too wide and it goes under other widgets (2 columns on my dashboard).

![image](https://user-images.githubusercontent.com/3495647/101663714-f2c23b00-3a42-11eb-9b47-b8c186456f52.png)

**Describe the solution you'd like**
I would like to have the Interface Statistics Widget table rotated, to allow a OPNsense instance with many interfaces display correctly. If we were to rotate it around this would make all interface viewable, and should also make it visible on all screen sizes and if you have more columns on your dashboard.

Interfaces down the first column and then the packets, bytes, errors along the top, if that makes sense?

**Describe alternatives you've considered**
There isn't really other than not using the Interface Statistics Widget.
Getting a 21:9 4k monitor... tempting but expensive.

**Additional context**
Only really effects people with loads of interfaces.

**Comment by FingerlessGlov3s** [comment]
Hopefully my PR for this is up to scratch. It's my first PR for OPNsense 🤭

**Comment by AdSchellevis** [comment]
https://github.com/opnsense/core/pull/4957
