### ISSUE TITLE
WebUI: Lobby - Dashboard - Traffic Graph - Widget-Title -> Link to /status_graph.php

### ISSUE THREAD

**Issue by rolsch** [opnsense/core#4511]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
[x] I have searched the existing issues and I'm convinced that mine is new.

**Describe the bug**
The link /status_graph.php over the Navigation "Lobby - Dashboard - Traffic Graph -> Widget-Title" points to a "Page not found".
This link should corrected due the change "reporting: traffic graph replacement using iftop".

**To Reproduce**
1. Go to Navigation "Lobby - Dashboard - "Traffic Graph" Widget
2. Click on the Widget-Title "Traffic Graph"
3. Page not found

**Expected behavior**
Shoud open the path /ui/diagnostics/traffic (?)

**Environment**
OPNsense 20.7.6-amd64
FreeBSD 12.1-RELEASE-p11-HBSD
OpenSSL 1.1.1h 22 Sep 2020

**Comment by AdSchellevis** [comment]
@rolsch thanks for reporting!
