### ISSUE TITLE
20.7.6 Update: WebUI: Reporting - Traffic -> Interface pre-selection are not persistent

### ISSUE THREAD

**Issue by rolsch** [opnsense/core#4512]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
[x] I have searched the existing issues and I'm convinced that mine is new.

**Describe the bug**
The interface selection/pre-selection are not persistent.

**To Reproduce**
1. Go to 'Reporting - Traffic'
2. Click on 'the right side the Inteface-Box and select/de-select some additional interfaces for traffic display'
3. The selected interfaces are displayed in the traffic graph
4. click at the left side again Reporting - Traffic
5. now the selected Interfaces was de-selected

**Expected behavior**
The selected interfaces should be persistent.

Remark
A Save-Button are needed - then maybe is this bug changed to feature request.
... and changechable colors for the interfaces should nicer... 

**Screenshots**
OPNsense 20.7.6-amd64
FreeBSD 12.1-RELEASE-p11-HBSD
OpenSSL 1.1.1h 22 Sep 2020

Regards
Roland
![10-12-_2020_09-23-08](https://user-images.githubusercontent.com/5867018/101740646-67d85380-3ac9-11eb-8b8c-1076263e12e2.jpg)

**Comment by 1e100** [comment]
Also, if possible, bring back the per-client sorted list below. Without it I can't really tell who's using the internet at any given moment.

**Comment by AdSchellevis** [comment]
@1e100 you can, just point to dot on the chart below (we're currently not planning to add another grid with roughly the same information)

**Comment by 1e100** [comment]
@AdSchellevis best I can tell this information can only be shown temporarily now, and worse, I have to track the dots with my mouse. The dot graph shows near zero information without hovering. I'm scratching my head here wondering how this new graph is an improvement in any way compared to what was there before.

**Comment by AdSchellevis** [comment]
@1e100 you can always extract data using network Insight, which is able to keep track over time. The active hotspots (who are the top users right now) is clearly visible in the graph as it is. There's just not more room on the screen. 

The topic of this FR (persist interface selection) might make it into OPNsense eventually, by saving the last choice in the browsers local storage (like we do for some other options as well).

**Comment by rolsch** [comment]
> @AdSchellevis best I can tell this information can only be shown temporarily now, and worse, I have to track the dots with my mouse. There's also no hostname resolution. The dot graph shows near zero information without hovering. I'm scratching my head here wondering how this new graph is an improvement in any way compared to what was there before.

Ahh, yes, I agree with this opinion.
For example, I also need the view with the sorting option by IP or BR-in/BR-out.
I have not found such helpful analysis options elsewhere.


![10-12-_2020_09-23-08](https://user-images.githubusercontent.com/5867018/102696827-85c45780-4231-11eb-8d9b-07e8fb270446.jpg)

**Comment by mimugmail** [comment]
ntopng would be an option :)

**Comment by AdSchellevis** [comment]
similar output as what iftop delivers command line might be an option to add, the feed used to collect the grid (`/api/diagnostics/traffic/top/lan,wan`) might be added into a separate tab. Just add another ticket an I'll see if that's an option.
