### ISSUE TITLE
CARP not working for IPv6 addresses

### ISSUE THREAD

**Issue by LiohMoeller** [opnsense/core#4515]
[x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[x] I have searched the existing issues and I'm convinced that mine is new.

We have configured CARP successfully for IPv4 and now have added additional IPv6 CARP VIP which does not work.

Firewall rules have been set accordingly:

![grafik](https://user-images.githubusercontent.com/1267594/101790866-34b2b600-3b03-11eb-90a2-6439472c6260.png)

No additional IP Aliases have been configured on that specific vhid group. The group is not used elsewhere on that network and virtual IP password is correct.

#3411 seems to be somewhat related, as on my setup a failover results in both nodes staying in master state for the specific CARP IP.

I can confirm that disabling:

Firewall -> Settings -> Advanced -> Multi-WAN -> Use shared forwarding between packet filter, traffic shaper and captive portal

which actually disables `net.pf.share_forward` and `net.pf.share_forward6`, works around the issue.

The proposed patch c5d6b6c seemed to build be for 19.1 release as the 20.7+ _./src/etc/inc/filter.lib.inc_ looks completely different. So either it has been re-indroduced, or I am missing something.

**Comment by LiohMoeller** [comment]
https://github.com/opnsense/core/issues/3411 seems to be somewhat related, as also on my setup a failover results in both nodes staying in master state.

**Comment by LiohMoeller** [comment]
I can confirm that disabling:

Firewall -> Settings -> Advanced -> Multi-WAN -> Use shared forwarding between packet filter, traffic shaper and captive portal

which actually disables net.pf.share_forward and net.pf.share_forward6, works around the issue.

The proposed patch https://github.com/opnsense/core/commit/c5d6b6cacf98fa1953b748fd2c0b6817dd31a3e9 seemed to build be for 19.1 release as the 20.7+ ./src/etc/inc/filter.lib.inc looks completely different. So either it has been re-indroduced, or I am missing something.

**Comment by maxfield-allison** [comment]
Can confirm, I'm also encountering this behavior running opnsense on kvm and baremetal running in HA.

**Comment by fichtner** [comment]
We will very likely improve shared forwarding IPv6 support next year. I'll put this on my list.

**Comment by mimugmail** [comment]
Please reopen .. this should be tracked, maybe we find a fix sometimes

**Comment by AdSchellevis** [comment]
@mimugmail I'm doubting this is a generic issue to be honest, could be driver related as well. If we plan to keep it open, there should be at least an owner (otherwise bot will close eventually anyways). In my opinion we can always reopen if there are more clear pointers and someone is willing to work on the ticket.

**Comment by mimugmail** [comment]
I'll test it on a machine which I need to roll out next week. If I cant reproduce maybe better let it closed then :)

**Comment by LiohMoeller** [comment]
If you try, please try it on KVM.

**Comment by bbccdd** [comment]
Just a shout out that I'm also interested!

**Comment by mimugmail** [comment]
Carp and v6 runs quite smooth in default setup :)

**Comment by bbccdd** [comment]
That is great to hear @mimugmail! However, altough I've got my Cisco Certified Network Associate (CCNA) papers all the way back from 2003, I never got to IPv6. I'd like to use two routers (one vm and one in hardware) that can both serve LAN clients access to the internet when one of them goes down (planned or unplanned). What starting point / pointers could you give me to get started please? (my ISP already provided a /56 segment).

**Comment by mimugmail** [comment]
The starting point is, using CARP in a mix of hardware and VM will fail! Dont so it
