### ISSUE TITLE
Traffic reporting is still not working. No bandwidth for any interface. No IPSEC interface selection

### ISSUE THREAD

**Issue by Stifler6996** [opnsense/core#4517]
**Describe the bug**
Still not seeing any throughput data on traffic graph.
Also unable to select IPSEC interface.

**To Reproduce**

Open dashboard. look at Traffic graph.
Open Reporting -> Traffic, look at graph.

**Expected behavior**
1) To see bandwidth data. Interestingly something is sort of working, as you can see in the screenshot below of the Reporting->Traffic page, "Top Hosts" is displaying data, but bandwidth is not available for the interfaces that are selectable.

2) To be able to select IPSEC as an interface.

**Screenshots**
![image](https://user-images.githubusercontent.com/12870096/101968724-6f862c80-3c70-11eb-8b82-ea4ac9718bbb.png)

![image](https://user-images.githubusercontent.com/12870096/101968778-d6a3e100-3c70-11eb-9e81-84bccc619e89.png)

**Environment**
ESXi Virtual machine (ESXi/vCenter 6.7)
Network: VMXNET3
OPNsense 20.7.6 (amd64, OpenSSL).
Dual Intel(R) Xeon(R) CPU E5-2620 v4@2.10GHz (physical)
VM = 4x vCPU.

**Comment by Stifler6996** [comment]
Still no help on this problem?

I don't think support tag is appropriate, since clearly this is a bug. The fact that I cannot select and see IPSEC traffic makes me think that it was not implemented properly. The previous iteration could do this.

Secondly, I did a fresh build and added my backup config. It still does not work.

**Comment by psychogun** [comment]
@Stifler6996 

Hi

Just curious - which network driver are you using for this OPNsense guest? ... and since this is virtualized, have you installed the VMware tools from System > Firmware > Plugin? I do not know if this will help though :)

**Comment by Stifler6996** [comment]
@psychogun 

Hi,
For all my vNIC's I am using VMXNET3. Yes, I do have the os-vmware plugin installed.

The things that I can confirm are:
1. If I disable IDS - the monitoring will start working. The problem still exists in the IDS package(s).
2. Using IDS, I have IPS enabled (offloading disabled) and Promiscuous Mode enabled.
3. I have tried adding "net.bpf.zerocopy_enable" in tunables (and a reboot), with no success.

I'm not too fond of familiar with bsd, I was hoping to see if I could confirm a vmxnet module was loaded but apparently modprobe type commands don't exist. and klist/lkdload didn't appear to be particularly helpful.
