### ISSUE TITLE
Unable to configure monit to monitor changed link capacity on WAN/DHCP links

### ISSUE THREAD

**Issue by crowbarz** [opnsense/core#4522]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[x] I have searched the existing issues and I'm convinced that mine is new.

**Describe the bug**
I am trying to monitor and alert when the interfaces facing my ISP's CPE drop from 1000baseT to 100baseT connectivity using monit on opnsense. Whilst I am able to create a service test for `changed link capacity` [per Monit documentation](https://mmonit.com/monit/documentation/monit.html#Link-capacity), I am unable to apply this service test to a Monit service for either of the ISP interfaces as neither of them appear in the interfaces list when type `Network` is selected in the service configuration.

**To Reproduce**
1. In `Services > Monit > Settings > Service Test Settings`, create a new test `NetworkCapacity` with condition `changed link capacity`.
2. In `Services > Monit > Settings > Service Settings`, click Add (`+`) and select type `Network`.
3. Open Interface drop-down menu and note that WAN interfaces are not included in the list, only LAN interfaces.

**Expected behavior**
I had hoped to be able to monitor `changed link capacity` on WAN interfaces.

**Additional context**
One of my ISP links is > 100Mbps, so when the CPE link dropped down to 100baseT it caused a performance limitation on that ISP link. Currently the only way to detect this condition is by manual review of the firewall's interfaces dashboard.

In my multi-WAN configuration, both ISPs are configured to obtain IP address via DHCP. There is code that [might exclude DHCP interfaces from an interface list](https://github.com/opnsense/core/blob/6e2375b0447853d241f11185dc08cde62652cd6d/src/opnsense/mvc/app/models/OPNsense/Monit/Monit.xml#L239) but I am not 100% sure that this code is applied in the use case described in this issue.

The `changed link capacity` condition itself appears to be supported as it's [referenced as a valid condition](https://github.com/opnsense/core/blob/6e2375b0447853d241f11185dc08cde62652cd6d/src/opnsense/mvc/app/models/OPNsense/Monit/Monit.php#L131).

I also see a [forum discussion thread](https://forum.opnsense.org/index.php?topic=18197.0) from several months ago, but there were no responses to it.

**Environment**
OPNsense 20.7.5 (amd64, OpenSSL)
Running on bare metal Intel Core i5 CPU with Intel I211-AT networking

**Comment by willivolt** [comment]
I've hit this issue too.  I am lucky that I am in a position to change my WAN to a static IP to get WAN interface to show in the UI drop down.

**Comment by david-aggeler** [comment]
Also see https://forum.opnsense.org/index.php?topic=18197.msg82575#msg82575

There is a DHCP filter in /opnsense/mvc/app/models/OPNsense/Monit/Monit.xml (line 242)

To me, this filter does not make much sense for Monit. I've removed the filter on my setup, and changed it in the UI.
igb0 does not show in the UI, but rather it's parent name WAN. The new selection correctly makes it into /usr/local/etc/monitrc and I get alerts.

```
check network WAN  interface igb0
   if download > 6000 kB/s then alert 
   if upload > 600 kB/s then alert
```

**Comment by Styx13** [comment]
I would like to re-open this issue.
I have the same problem, I would like to configure some monit alert on my WAN interface.

As indicated by @david-aggeler in a comment above (https://github.com/opnsense/core/issues/4522#issuecomment-843426090), there is a DHCP filter  that prevents DHCP based interfaced to appear in Monit.

Would it be possible to add an option in Monit general config to allow listing of DHCP enabled interfaces ?

Thank you !

**Comment by AdSchellevis** [comment]
We can reopen an issue if someone volunteers on working on it, so we can assign the ticket to that person. Currently there doesn't appear to be enough interest on spending time on this.

**Comment by sas101** [comment]
I have the same issue and would be interested in this. I hope there are more people interested...

If there is a filter for the UI - is the fix potentially really that simple to remove that filter? Or is there more to consider?
