### ISSUE TITLE
Error Core/Config.php array_keys() expects parameter 1 to be array

### ISSUE THREAD

**Issue by Bramzor** [opnsense/core#4530]
**Describe the bug**
Got the following error breaking parts of the GUI:

    Error Core/Config.php array_keys() expects parameter 1 to be array, string given (errno=2)

Apparently its related to the function isArraySequential(&$arrayData) which fails when it is triggered on a string as $arrayData

https://github.com/opnsense/core/blob/master/src/opnsense/mvc/app/library/OPNsense/Core/Config.php#L80

When I print out $xmlNodeName on line https://github.com/opnsense/core/blob/master/src/opnsense/mvc/app/library/OPNsense/Core/Config.php#L114

I do get "ca". Which is an empty string. Right before I receive the mentioned error.

**Work Around**
I've added an is_array check in the function on line 80 and returned an empty string in that case. This helped me work around this issue but I assume it should never get into this situation right?

**To Reproduce**
Not sure how I got in this situation. Issue was visible using the iperf plugin but seems unrelated. Seems just a code bug.

**Expected behavior**
Should not run a function that crashes on string value.

**Environment**
Software version:

FreeBSD 12.1-RELEASE-p11-HBSD #0  74f1f081a1e(stable/20.7)-dirty: Fri Dec  4 13:40:15 CET 2020     root@sensey64:/usr/obj/usr/src/amd64.amd64/sys/SMP amd64
OPNsense 20.7.6 ec006cefe
Plugins os-acme-client-2.1 os-dyndns-1.23 os-iperf-1.0 
Time Thu, 17 Dec 2020 05:13:24 +0100
OpenSSL 1.1.1h  22 Sep 2020
PHP 7.3.25

Plugins:

os-acme-client (installed) | 2.1 | 562KiB | Let's Encrypt client |  
-- | -- | -- | -- | --
os-dnscrypt-proxy (installed) | 1.8 | 79.1KiB | Flexible DNS proxy supporting DNSCrypt and DoH |  
os-iperf (installed) | 1.0 | 24.3KiB | Connection speed tester |  
os-maltrail (installed) | 1.5 | 39.9KiB | Malicious traffic detection system |  
os-theme-vicuna (installed) | 1.1 | 5.24MiB | The vicuna theme - dark anthrazit |  
os-dyndns (installed) | 1.23 | 160KiB | Dynamic DNS Support

**Comment by AdSchellevis** [comment]
was there more data in the traceback? if needed we can safeguard the function, but I do like to understand why it got here in the first place.

**Comment by AdSchellevis** [comment]
never mind, https://github.com/opnsense/core/commit/03f71e97e9b76556d40684300713f91179e5138e moves the previous is_array() into the function which should prevent this anyways. If there is another bug causing this, I'm interested in the next traceback when it happens.

**Comment by Bramzor** [comment]
@AdSchellevis : I did trigger the bug report from the GUI, which should include the full trace. Not sure what caused it but  since it crashes after xmlNodeName echo's ca during debugging, I assume it's some kind of "ca" field that is an empty string? 
Under system -> Trust -> Authorities , I do have an empty certificate, self signed with no name.
Not sure if this is normal or which plugin created this.

Might be Let's Encrypt which is active. OpenVPN I'm not using, but I did click on "Use a wizard to setup a new server" once but did not go through with the step "Create a New Certificate Authority (CA) Certificate".

Also I did try out Tailscale installation as mentioned in : https://github.com/tailscale/tailscale/issues/787 . Not sure if this one creates a certificate which is visible for OPNsense and which causes this issue.

Should I just remove the empty self signed certificate?

**Comment by AdSchellevis** [comment]
@Bramzor I would remove the empty record indeed, it might be a bug in the let's encrypt plugin as it inserts certs too (although I'm not sure). Sometimes the config history helps in tracking these down when the faulty data was generated recently.
