### ISSUE TITLE
Backed-up configurations not restored properly

### ISSUE THREAD

**Issue by af-admin** [opnsense/core#4531]
**Describe the bug**
Some options from saved configurations are correctly parsed and displayed on the web interface, but not applied. 

**To Reproduce**
1. Create a NAT rule to forward SSH ports. E.g. create a rule which maps inbound connections on port 12345 to port 22. Apply the auto-generated WAN rules accordingly.
2. Back up the configuration with the newly created NAT rule. 
3. Restore configuration and reboot opnsense. 
4. Attempt to connect via ssh on port 12345. See error (In my case, I tried to connect using openssh to another compatible client behind opnsense so the exact error was "no route to host")

**Expected behavior**
A successful connection.

**Screenshots and additional context**
I created a discussion topic (in German) on the forums here: https://forum.opnsense.org/index.php?topic=20466.0 which also contains screenshots. The suggested workaround was to create the old setting anew, I just created a new one (cloning the existing NAT rule with slight modifications). 

**Environment**
OPNsense 20.7 (amd64, OpenSSL).
FreeBSD 12.1-RELEASE-p11-HBSD
PCEngines APU3C4

**Comment by fichtner** [comment]
Complex restore should force a reboot to be sure. I guess that works?

**Comment by af-admin** [comment]
Not sure what you mean by "complex". I backed up the complete config, no encryption of the config, then restored it completely. Yes, indeed I was prompted to stand by for reboot.

**Comment by fichtner** [comment]
Complex means interface changes, etc.

**Comment by af-admin** [comment]
The SSH box runs on its own (VLAN) interface configured by opnsense. The original NAT route displayed correctly on the UI, but did not work. OTOH, unfortunately I  currently cannot test whether changing the VLAN but keeping the NAT rule also works.
