### ISSUE TITLE
HTTP sending empty reply after update to 20.7.7

### ISSUE THREAD

**Issue by ahaase-c4u** [opnsense/core#4532]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[*] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[*] I have searched the existing issues and I'm convinced that mine is new.

**Describe the bug**
opnSense with 20.7.6 correctly forwarded http requests to https, if configured so. After updating to 20.7.7, http is not possible anymore, https works correctly. I see this on 2 different firewalls, reboot of one of them did not change anything.

**To Reproduce**
1. Update to opnSense 20.7.7
2. curl -I http://IP
3. You see: curl: (52) Empty reply from server

**Expected behavior**
opnSense should show login screen via http or rediret to https, depending on what is configured.

OPNsense 20.7.7 (amd64, OpenSSL).

**Comment by fichtner** [comment]
Might be lighttpd update. If you use redirect to https your source url can probably be fixed to avoid this.

**Comment by AdSchellevis** [comment]
shouldn't it just redirect, when printing headers as well, it looks like this on my end:
```
# curl -v -l http://xxxx/
*   Trying xxxx...
* TCP_NODELAY set
* Connected to xxxx (xxxx) port 80 (#0)
> GET / HTTP/1.1
> Host: xxxx
> User-Agent: curl/7.64.1
> Accept: */*
> 
< HTTP/1.1 301 Moved Permanently
< Location: https://10.37.132.100/
< Content-Length: 0
< Date: Thu, 17 Dec 2020 18:45:53 GMT
< Server: OPNsense
< 
* Connection #0 to host 10.37.132.100 left intact
* Closing connection 0
```

**Comment by ahaase-c4u** [comment]
Yes, if you configured http to redirect to https. But on my 20.7.7 exactly nothing is in reply. Can I adjust the redirect myself, or has this to be done by the next update?

**Comment by fichtner** [comment]
https://twitter.com/opnsense/status/1339847119977533442

**Comment by fichtner** [comment]
See 4533
