### ISSUE TITLE
Please add an option to disable RDNSS in radvd

### ISSUE THREAD

**Issue by gk998** [opnsense/core#4537]
[x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[x] I have searched the existing issues and I'm convinced that mine is new.
I found #4087, but it has been closed without comment

**Is your feature request related to a problem? Please describe.**
There are some cases where one does not want to have DNS Servers assigned via SLAAC 

**Describe the solution you'd like**
I know, it is against the RFCs, but radvd itself allows it not to advertise DNS Servers. There can be some conditions where such a behaviour is desired. I just found out, that pfsense already implemented this:
https://redmine.pfsense.org/issues/9302
https://github.com/pfsense/pfsense/commit/e26ad76e8fd9b947f2ad97195d2153da14d8c594

It would be great to have this as well in opnsense!

**Comment by marjohn56** [comment]
I've quickly done this in commit #4571 , Try it with opnsense-patch d692980 , let us know how you get on. The patch can be reversed by issuing the same command again.

**Comment by marjohn56** [comment]
Due to a moment of idiocy I put the config in dhcpv6 and not Router Advertisements. I have not corrected that and the patch is now  e3a9fce

**Comment by gk998** [comment]
Sorry for the late reply. Thanks @marjohn56, your patch is looking good here :)

**Comment by fichtner** [comment]
There was an issue with the code (old var still used in dhcpd.inc) so I manually pushed 8ded045. Thanks ❤️
