### ISSUE TITLE
pfsync not working on a lagg if MTU is bigger than 1500

### ISSUE THREAD

**Issue by WRMSRwasTaken** [opnsense/core#4540]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[x] I have searched the existing issues and I'm convinced that mine is new.

**Describe the bug**
Firewall state sync via pfsync does not seem to work when the synchronize interface is on a lagg with MTU bigger than 1500.
Might also be possible that the problem occurs on a non-lagg interface with a MTU higher than 1500.

**To Reproduce**
1. Create a interface lagg (in my case type failover) and set MTU to 9000
2. Create a VLAN on that lagg which will be the firewall sync VLAN
3. Reboot. This is important, see below.
4. Configure pfsync with the peer IP on that new VLAN (does not work with multicast IP either)

**Expected behavior**
pfsync starts syncing firewall states.

**Relevant log files**
```
kernel: carp: demoted by 240 to 240 (pfsync bulk start)
kernel: carp: demoted by -240 to 0 (pfsync bulk fail)
```
Nothing more visible in logs. The firewall crashed one time while trying to troubleshoot, I've submitted a bug ticket, see below.

**Additional context**
Having the pfsync configured, and just changing the lagg MTU to 1500 and rebooting, everyting starts to work.

Deconfiguring pfsync and reboot.
Setting the lagg MTU to 9000 (from 1500 at boot!) and rebooting the node and setting up pfsync again sets the pfsync device to 9000 MTU which does not work, pfsync will not start syncing.
Setting the lagg MTU to 9000 (from 1500 at boot!) and not rebooting the node afterwards and configuring pfsync sets the pfsync device to 1500 and syncing starts while the lagg interface is on MTU 9000.

Having the lagg set to MTU 9000 and rebooting the node (which sets the pfsync0 to 9000 MTU aswell) and changing the MTU of pfsync0 to 1500 via ifconfig does not seem to work either, I tried:

```
ifconfig pfsync0 down
ifconfig pfsync0 mtu 1500
ifconfig pfsync0 up
```

To test, if this works without a VLAN on the lagg has still to be tested from my side.

While writing this ticket and testing to reproduce this behavior, my 2nd firewall node just crashed. I've submitted a sub report mentioning my Github username. I've also copied the text from the report problem page and can them provide here aswell if requested (of if the report did not arrive for some reason).

Edit 1: The underlaying network is set to handle jumbo frames correctly. I can ping the other node with `ping -s 8000 10.1.5.1`

Edit 2: A short extract from the log containing the stack trace:
```
__HardenedBSD_version = 1200059 __FreeBSD_version = 1201000
version = FreeBSD 12.1-RELEASE-p7-HBSD #0  427d53bc125(stable/20.7)-dirty: Sun Jul 26 05:51:42 CEST 2020
    root@sensey64:/usr/obj/usr/src/amd64.amd64/sys/SMP
KDB: stack backtrace:
db_trace_self_wrapper() at db_trace_self_wrapper+0x2b/frame 0xfffffe009d7122d0
vpanic() at vpanic+0x1a2/frame 0xfffffe009d712320
panic() at panic+0x43/frame 0xfffffe009d712380
trap_fatal() at trap_fatal+0x39c/frame 0xfffffe009d7123e0
trap_pfault() at trap_pfault+0x49/frame 0xfffffe009d712440
trap() at trap+0x29f/frame 0xfffffe009d712550
calltrap() at calltrap+0x8/frame 0xfffffe009d712550
--- trap 0xc, rip = 0xffffffff826fe706, rsp = 0xfffffe009d712620, rbp = 0xfffffe009d712640 ---
pfsync_state_export() at pfsync_state_export+0x26/frame 0xfffffe009d712640
pfsync_sendout() at pfsync_sendout+0x1eb/frame 0xfffffe009d7126f0
pfsyncioctl() at pfsyncioctl+0x653/frame 0xfffffe009d712770
ifioctl() at ifioctl+0x4f0/frame 0xfffffe009d712830
kern_ioctl() at kern_ioctl+0x2be/frame 0xfffffe009d7128a0
sys_ioctl() at sys_ioctl+0x15d/frame 0xfffffe009d712970
amd64_syscall() at amd64_syscall+0x364/frame 0xfffffe009d712ab0
fast_syscall_common() at fast_syscall_common+0x101/frame 0xfffffe009d712ab0
--- syscall (54, FreeBSD ELF64, sys_ioctl), rip = 0x3a9e9e0b47a, rsp = 0x78298f1d3c48, rbp = 0x78298f1d3c80 ---
KDB: enter: panic
panic.txt0600001213770074174  7143 ustarrootwheelpage faultversion.txt06000022613770074174  7625 ustarrootwheelFreeBSD 12.1-RELEASE-p7-HBSD #0  427d53bc125(stable/20.7)-dirty: Sun Jul 26 05:51:42 CEST 2020
    root@sensey64:/usr/obj/usr/src/amd64.amd64/sys/SMP
```

Edit 3: The crashdump might've not arrived at your place. The node needs some more preparations for a functioning uplink. I hope the copied data from the page is enough, or if there are the dumps still residing on the file system.
The same problem occurs also on version `OPNsense 20.7.6-amd64` which is the version the other node runs.

**Environment**
OPNsense 20.7-amd64
FreeBSD 12.1-RELEASE-p7-HBSD
OpenSSL 1.1.1g 21 Apr 2020

The nic used with both ports in the lagg:
```
ix2@pci0:5:0:0: class=0x020000 card=0x00038086 chip=0x10fb8086 rev=0x01 hdr=0x00
    vendor     = 'Intel Corporation'
    device     = '82599ES 10-Gigabit SFI/SFP+ Network Connection'
    class      = network
    subclass   = ethernet
ix3@pci0:5:0:1: class=0x020000 card=0x00038086 chip=0x10fb8086 rev=0x01 hdr=0x00
    vendor     = 'Intel Corporation'
    device     = '82599ES 10-Gigabit SFI/SFP+ Network Connection'
    class      = network
    subclass   = ethernet
```

**Comment by WRMSRwasTaken** [comment]
Hello OPNsense maintainers,

do you need additional information? If so, how can I supply them? Can you reproduce this bug? 

As the problem is very likely in the HardenedBSD (or maybe even FreeBSD) kernel, has this problem already been passed to the HBSD devs? If so, can you acknowledge this bug?

**Comment by AdSchellevis** [comment]
tagged the ticket community support for now,  not a lot of people will probably try this, since pfsync packets themselves are quite small. Since hbsd/OPNsense is quite similar to FreeBSD on this topic, it probably exists upstream as well. You can always try to reproduce and create a ticket there as well.

**Comment by WRMSRwasTaken** [comment]
Okay, thank you. Then my next step will be to try to reproduce this with HardenedBSD and FreeBSD.

**Comment by toxic0berliner** [comment]
Thanks to this issue I finally solved mine : pfsync needs to be run on an interface that has MTU 1500.

I sync states on an itnerface which is a VLAN, I wish to use jumboframes on some other VLANs, so I had to set the parent MTU to 900 and I went on to set MTU 9000 to all VLANs... This broke all my states sync, with no real complaint just seeing it doesnt work and pfsync0 interface showing in/out errors on the interface->overview page...

Setting the MTU to "blank" for the interface that I use to sync states suddenly brought state sync to life...

This should really be solved I think, I expected all sync packets to be way samll and never hit the MTU of 1500 anyway so changing it to 9000 felt safe for me... I couldn't find it documented anywhere...

I think this deserves some more love to either fix or document...

**Comment by WRMSRwasTaken** [comment]
> I sync states on an itnerface which is a VLAN, I wish to use jumboframes on some other VLANs, so I had to set the parent MTU to 900 and I went on to set MTU 9000 to all VLANs... This broke all my states sync, with no real complaint just seeing it doesnt work and pfsync0 interface showing in/out errors on the interface->overview page...

Why so complicated, just set the parent to 9k and the VLAN you're using for pfsync explicitely to 1500, this is/was my workaround. Unofrunately, I've switched my employer since then and I don't have access to this setup anymore, so I am only able to help with this in lab environments.

**Comment by wolfspyre** [comment]
It **DEFINITELY** warrants mentioning in documentation, and preferably a check when selecting the heartbeat/pfsync interface.

if this isn't going to be fixed, (preferable) at **least** notify the user that they're entering buglandia and are likely to regret the decision.... That way they'll at least be aware to look for problems.... 

nothing other than increasing errors on the pfsync interface indicated a problem.... that feels like a problem to me in and of itself; but I digress.

**Comment by toxic0berliner** [comment]
It's a tricky one and indeed I also believe it warrants a check or at least documentation. I think @WRMSRwasTaken should reopen the issue 😁

**Comment by AdSchellevis** [comment]
that only makes sense if someone plans to write some documentation, you can open a PR here https://github.com/opnsense/docs
