### ISSUE TITLE
Configuring DHCPv6 options where an unsigned integer is required, causes dhcpdv6 to not start

### ISSUE THREAD

**Issue by Wireheadbe** [opnsense/core#4542]
**Describe the bug**
Configuring DHCPv6 options where an unsigned integer is required, causes dhcpdv6 to not start.

E.g. when configuring numbered option "7" ("OPTION_PREFERENCE" - see http://www.ipamworldwide.com/ipam/isc-dhcpv6-options.html); and selecting "Unsigned 8-bit integer" and setting it to 255; dhcpdv6 will not start anymore and bail out with the error:
```
/etc/dhcpdv6.conf line 19: expecting number.
  option custom-lan-0 "255"
                       ^
```

**Expected behavior**
If the uint8 is configured within the config in an unquoted fashion, then there is no error. 

**Config extract**
```
option custom-lan-0 code 7 = unsigned integer 8;

[...]
subnet6 2a02:1811:dead:b33f::/64 {
  range6 2a02:1811:dead:b33f::30 2a02:1811:dead:b33f::91;
  option dhcp6.domain-search "somedomain.xyz";
  option custom-lan-0 "255";
}
```
I think it should be:
```
option custom-lan-0 255;
```

**Environment**
OPNsense 20.7.7_1

**Comment by marjohn56** [comment]
PR #4573

**Comment by Wireheadbe** [comment]
> 
> 
> PR #4573

Awesome! Thanks!

**Comment by Wireheadbe** [comment]
![image](https://user-images.githubusercontent.com/4497972/103755223-c384f680-500d-11eb-9cfa-b882a17bb90f.png)
Seems to work fine - consider this issue closed if it gets merged 👍🏻

**Comment by marjohn56** [comment]
OK.. down to @fichtner | @AdSchellevis to pull it in now.

**Comment by AdSchellevis** [comment]
@marjohn56 thanks for the fix and @Wireheadbe thanks for testing and confirming. Just merged it to be included in a future release
