### ISSUE TITLE
Extremely High latency with OPNsense 20.7 compared with 20.1 (X710-T4)

### ISSUE THREAD

**Issue by Xboarder56** [opnsense/core#4543]
Important notices
Before you add a new report, we ask you kindly to acknowledge the following:

[x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[x] I have searched the existing issues and I'm convinced that mine is new.

The system is ESXi 7.0u1 using a Ryzen 3900x processor with passthrough of multiple intel cards including i210, X550-AT2, and X710-T4. 

The VM is configured with passthrough of the i210 and the X710-T4 currently but after performing the passthrough it gets extreme latency with the default live configuration for any of the X710-T4 (IXL0-4) interfaces. A simple ethernet connection from port 0 of the X710-T4 gets the following ping results:

Reply from 192.168.1.1: bytes=32 time=1ms TTL=64
Reply from 192.168.1.1: bytes=32 time=294ms TTL=64
Reply from 192.168.1.1: bytes=32 time=4ms TTL=64
Reply from 192.168.1.1: bytes=32 time=124ms TTL=64
Reply from 192.168.1.1: bytes=32 time=1ms TTL=64
Reply from 192.168.1.1: bytes=32 time=231ms TTL=64
Reply from 192.168.1.1: bytes=32 time=1ms TTL=64
Reply from 192.168.1.1: bytes=32 time=248ms TTL=64
Reply from 192.168.1.1: bytes=32 time=32ms TTL=64
Reply from 192.168.1.1: bytes=32 time=276ms TTL=64
Reply from 192.168.1.1: bytes=32 time=1ms TTL=64
Reply from 192.168.1.1: bytes=32 time=135ms TTL=64
Reply from 192.168.1.1: bytes=32 time=93ms TTL=64
Reply from 192.168.1.1: bytes=32 time<1ms TTL=64
Reply from 192.168.1.1: bytes=32 time=309ms TTL=64
Reply from 192.168.1.1: bytes=32 time=67ms TTL=64
Reply from 192.168.1.1: bytes=32 time<1ms TTL=64
Reply from 192.168.1.1: bytes=32 time=218ms TTL=64

Attempting this same setup but passing in the i210 as the primary lan interface (igb0) and the ping is ~1-2ms which is expected for the direct connection. Passing in the X550-AT2 (IX0) interface gets the expected ping as well. 

Booting OPNsense 20.1 without doing any additional upgrades and running the live environment on the X710-T4 inside of a ESXi VM returns expected ping results of ~1-2ms with a direct connection to the laptop. 

Another odd discovery is booting the entire server off the OPNsense live cd 20.7 the ping results are working as expected on the X710-T4 card. Expanding on this, I installed 20.1 and upgraded it to 20.1.9 and this worked perfectly fine pinging from the lan device. As soon as the upgrade to 20.7 took affect the issue was present. 

Booting from a beta build of hardenBSD 13 on the same VM config with the X710 passed through shows the ping working as expected.

**Comment by bewue** [comment]
We have similar problems since the update to 20.7. high and fluctuating ping RTT for all traffic which traverses the firewall. We run opnsene as guest on an Xen Host. Meanwhile i thought an Xen update was the issue but maybe its actually an issue with opnsense.

I haven't been able to verify that yet, but I suspect problems with netmap which has been in use since 20.7.4, as far as i know.

**Comment by Xboarder56** [comment]
@bewue are you using a specific network card and is it pass through as well?

**Comment by bewue** [comment]
No idea which network card we use.
But the VM runs in HVM mode and the interfaces are named xn[n] in opnsense. I think that there is no passthrough involved.

At home I have opnsense bare-metal running and can not find any problems there. Of course, the system is also much less stressed. @Xboarder56 Were the opnsene under load during your tests?

It may be that the problem only occurs in connection with virtualization?

**Comment by Xboarder56** [comment]
No load whatsoever, I didn’t even have the wan connected. Just 1 machine connected directly to the lan network.
