### ISSUE TITLE
DHCP: Cannot add static mapping with same hostname using different domain name

### ISSUE THREAD

**Issue by marcquark** [opnsense/core#4544]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[x] I have searched the existing issues and I'm convinced that mine is new.

**Describe the bug**
I'm attempting to configure DHCP static mappings on an interface, where there would be two seperate mappings (different MAC and IP addresses) using the same value for "Hostname", but the 2nd entry uses a different value for "Domain Name". This should work, but the input validation does not accept that constellation.
[This check](https://github.com/opnsense/core/blob/master/src/www/services_dhcp_edit.php#L132) seems to be responsible and should be extended to not only compare the hostname, but rather the combination of hostname and domain. It's a bit more than simply comparing the domain fields though, consider this corner case:
* Entry 1 has an empty "Domain Name"
* Entry 2 has a non-empty "Domain Name" but it's the same as the one configured on the interface-level DHCP settings. Or if that's empty, too then the system-wide domain name.
* In this case, validation should fail

**To Reproduce**
1. Go to Settings->DHCPv4->(your interface)
2. Add one static host entry with hostname "hostA"
3. Try to add another static entry with hostname "hostA" and domain name "some-custom-domainname.example.com"
4. See error "This Hostname, IP, MAC address or Client identifier already exists."

**Expected behavior**
If the domain name does not conflict with the resulting domain name of the first entry, the validation should pass and the static mapping should be created

**Screenshots**
-

**Relevant log files**
-

**Additional context**
-

**Environment**
OPNsense 20.7.7 (amd64, OpenSSL)
hardware irrelevant

**Comment by AdSchellevis** [comment]
@marcquark can you try https://github.com/opnsense/core/commit/51c04e7abfa8286a12f5c59c84f3bd868079de07 ?

**Comment by marcquark** [comment]
works, but it doesn't validate against the domain name set on the interface. so if my systemdomain is "system.domain.example.com" and i configure "other.domain.example.com" on the specific interface, i can add an entry "hostA" with empty domain field and another entry "hostA" with domain name set to "other.domain.example.com" and it will go through. that's a conflict and should be caught i think

**Comment by marcquark** [comment]
oh, sorry, to clarify: it's not a problem for the DHCP service, but it causes duplicates in unbound's host_entries.conf when choosing to register static DHCP mappings

**Comment by marcquark** [comment]
hmmh, on the other hand, it doesn't break anything. unbound will just return two A records with different IPs for the same hostname. i guess if one does that they either have a reason to do it or made a mistake which can be fixed? so it may be OK to not prevent the user from creating such a scenario

**Comment by AdSchellevis** [comment]
well, I missed the interface domain, which should be in the list, let me try to add it in a sec. these structures are almost impossible to validate properly.

**Comment by AdSchellevis** [comment]
there you go https://github.com/opnsense/core/commit/6c1b8a993ea48ec29dca64bb284dd7dc2e7aee6a

**Comment by marcquark** [comment]
yup, that did the trick. thx!
