### ISSUE TITLE
[FR] Disable autoscroll when user scrolls upwards in live updater log

### ISSUE THREAD

**Issue by ericschdt** [opnsense/core#4545]
Currently the updater always scrolls to the button automatically during an update. If you want to read something while it stands still or something which left the view of the visible content, you cannot do that: Once the next log lin comes in, the scrollbar's position is reset again to the bottom.

Thus it would be convenient if the scrollbar would stay at the position where it is when scrolled up and auto scroll, if it's at the bottom.

**Comment by fichtner** [comment]
This probably won't make 21.1 but I promise to took at how it could be solved.

**Comment by fichtner** [comment]
@ericschdt 09659ff25 seems to work, please give it a go if you can

    # opnsense-patch 09659ff25

**Comment by ericschdt** [comment]
Thank you!
