### ISSUE TITLE
Automatic backup with rrd data

### ISSUE THREAD

**Issue by Matriciel** [opnsense/core#4546]
In 20.7, automatic backup to Nextcloud instance exist, but there is no options to add RRD data in the backup (like manual backup).

Can you add this option in backup configuration page.

**Comment by Matriciel** [comment]
Hi,
What is incomplete in the request ?

**Comment by fichtner** [comment]
Issue template wasn't used. In this case it's a feature request better suited for the plugin area as the RRD data is not configuration data relevant for config.xml. At some point in time, it might also be useful to decouple the RRD data from the (optional) config.xml export.


Cheers,
Franco
