### ISSUE TITLE
Forum registration not working

### ISSUE THREAD

**Issue by SokoFromNZ** [opnsense/core#4549]
Hi guys,

I'm trying for days on end now to register in the forum. I don't get the activation email (I don't have a junk/spam filter). I've also tried to resend the activation email and also to change the email.

Can someone here have a look into this?

thanks

Soko

**Comment by AdSchellevis** [comment]
I think I found your email address in the awaiting registration section of our forum, can you try to login. if it doesn't work, just send as an email at project at opnsense.org

**Comment by SokoFromNZ** [comment]
Thanks heaps, I'm in the forum now!
