### ISSUE TITLE
Captive Portal: Client Browser type detection

### ISSUE THREAD

**Issue by jstrebel** [opnsense/core#455]
Hi, would be useful if we could detect the client type. We see more and more sites which are built either for Mobile or PC. This feature would improve the user experience.
Jakob

**Comment by AdSchellevis** [comment]
Hi Jakob,

You could probably best solve this with a custom template, the new system (in development) offers an easy method to develop those templates (default is a simple bootstrap theme).
Most parts of the new captive portal already function, only a frontend for vouchers is still in development.
Regards,

Ad
