### ISSUE TITLE
Low urgency feature request - refresh button on live log

### ISSUE THREAD

**Issue by pallebone** [opnsense/core#4550]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[-] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

YES

[-] I have searched the existing issues and I'm convinced that mine is new.

YES

**Is your feature request related to a problem? Please describe.**

NO ISSUE - Feature enhancement request. 

**Describe the solution you'd like**

Hello again, sorry to bother you again with another feature request for the live log page, I use this page a lot and notice missing features as I am always using it. Apologies again this request is low urgency as it doesnt stop me from using the product effectively but would be a nice to have. 

On the firewall log there is no manual refresh button to refresh just 1 time. I can only tick the auto refresh and untick it. On larger amounts of logs this is not always desirable as I want just a snapshot in time for me to review while autorefresh can sometimes refresh more than the single time I am looking for. Also when changing between number of entries shown, if auto refresh is off, nothing is shown when selecting a different amount of logs because there is no way to one time refresh the entries. 

I have attached a screenshot of the intrusion detection page which has a button that allows a single 1 time refresh. 

I would ask for a single time refresh button be added like the intrusion detection page so I dont have to use auto refresh (which can be a slow script when there are a large number of logs) and can click the refresh button just one time. 

To be clear this is a low urgency request and does not impact daily use of the product. I am only asking for this feature if it is very easy to implement and does not stress anyone out. 

An alternative option would be if the auto refresh is turned off, when changing the number of entries shown (eg: from 25 to 100 say) that the entries refresh a single time so something is displayed rather than nothing. Either option would work for me personally although a button to click to refresh would be nicer. 

**Describe alternatives you've considered**

No other option currently exists. To reiterate if this request is too hard to do then that is fine. Im only asking if its easy as it is a feature enhancement. The product works correctly without the feature but it would help to have a refresh button. 
![0995C4DB-2C3C-4250-9D1B-E8A52FA9896A](https://user-images.githubusercontent.com/11403137/103157432-ba2f9a80-4780-11eb-98c0-f44fee00dc1f.jpeg)
![10D4063D-175F-47B3-9228-50F9C2FCA10D](https://user-images.githubusercontent.com/11403137/103157434-c1ef3f00-4780-11eb-9c53-6e886fcd681b.png)

**Additional context**

Thank you for taking the time to read my request. If it is too difficult to add that if fine :)

Hope you had a good Christmas and have a happy new year :)

-P

**Comment by AdSchellevis** [comment]
@pallebone https://github.com/opnsense/core/commit/7331b2717bc54dd197d5032073273c8d50a5a31d should do the trick, there was room for an extra button available, so easy fix I would say.

**Comment by pallebone** [comment]
Thank you very much for this. Have a good new year :)

**Comment by AdSchellevis** [comment]
you're welcome, best wishes for 2021 to you too!
