### ISSUE TITLE
IPv6 doesn't work with 2 ISP (Multi-WAN) configuration

### ISSUE THREAD

**Issue by kkoshelev** [opnsense/core#4556]
[x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
[x] I have searched the existing issues and I'm convinced that mine is new.
Similar to #3601, #3604.

In the configuration, below LAN traffic is routed to WAN2 gateway, while it should be routed to WAN. As a result, ipv6 is not available on LAN because WAN2 ISP blocks it.

WAN - Comcast ISP DHCPv6 2601:xxx /60 delegated
WAN2 - AT&T ISP DHCPv6 2600:xxx /64 delegated
LAN - Track WAN #0

Actually all ipv6 traffic is always routed to WAN2 (default gateway) while expected it sorted out by source address.

Adding Firewall > Routes > LAN role to forward ipv6 traffic to WAN makes no difference.

**Ping WAN**
# /sbin/ping6 -S '2001:xxx' -c '3' 'google.com'
PING6(56=40+8+8 bytes) 2001:xxx --> 2607:f8b0:4001:c05::65

--- google.com ping6 statistics ---
3 packets transmitted, 0 packets received, 100.0% packet loss

**Ping WAN2**
# /sbin/ping6 -S '2600:xxx' -c '3' 'google.com'
PING6(56=40+8+8 bytes) 2600:xxx --> 2607:f8b0:4001:c05::64
16 bytes from 2607:f8b0:4001:c05::64, icmp_seq=0 hlim=104 time=50.842 ms
16 bytes from 2607:f8b0:4001:c05::64, icmp_seq=1 hlim=104 time=50.686 ms
16 bytes from 2607:f8b0:4001:c05::64, icmp_seq=2 hlim=104 time=51.769 ms

--- google.com ping6 statistics ---
3 packets transmitted, 3 packets received, 0.0% packet loss
round-trip min/avg/max/std-dev = 50.686/51.099/51.769/0.478 ms

**ROUTES**

ipv6 | default | fe80::e7c:28ff:fe75:13e0%vmx2 | UGS | 3271 | 1500 | vmx2 | WAN2 |   |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
ipv6 | ::1 | link#5 | UH | 404663 | 16384 | lo0 | Loopback |   |  
ipv6 | 2001:558:xxx | link#2 | UHS | 0 | 16384 | lo0 | Loopback |   |  
ipv6 | 2001:4860:4860::8844 | fe80::e7cxxx%vmx2 | UGHS | 3074 | 1500 | vmx2 | WAN2 |   |  
ipv6 | 2001:4860:4860::8888 | fe80::xxx%vmx1 | UGHS | 0 | 1500 | vmx1 | WAN |   |  
ipv6 | 2600:xxx:6310::/64 | link#3 | U | 0 | 1500 | vmx2 | WAN2 |   |  
ipv6 | 2600:xxx:6310::49 | link#3 | UHS | 0 | 16384 | lo0 | Loopback |   |  
ipv6 | 2600:xxx:6310:20c:29ff:fe3f:b509 | link#3 | UHS | 0 | 16384 | lo0 | Loopback |   |  
ipv6 | 2601:xxx:65a0::/64 | link#1 | U | 1647 | 1500 | vmx0 | LAN |   |  
ipv6 | 2601:xxx:65a0:20c:29ff:fe3f:b5f5 | link#1 | UHS | 0 | 16384 | lo0 | Loopback |   |  

**To Reproduce**
See above

**Expected behavior**
Expected to be able to use both WAN/WAN2 interfaces with ipv6

**Environment**
OPNsense 20.7.7-amd64
FreeBSD 12.1-RELEASE-p11-HBSD
OpenSSL 1.1.1i 8 Dec 2020

**Comment by mimugmail** [comment]
Try disabling shared forwarding in Firewall Settings Advanced

**Comment by kkoshelev** [comment]
Disabling 'Shared forwarding' in Firewall Settings Advanced made gateway able to ping but LAN traffic is still routed to default (wrong) ipv6 gateway.
