### ISSUE TITLE
CaptivePortal Fails to Upload/Accept Template

### ISSUE THREAD

**Issue by tong2x** [opnsense/core#4558]
**Describe the bug**
uploading modified captiveportal template fails. does not show up in the template list. however uploading unmodified template file is accepted.  even just adding a image file in the archive, makes it fail to upload. also tried upload previous template file and those are not accepted also.

what I have done so far
1) modified as little as possible, even adding 1 image file fails to upload
2) Reset to default the system, set minimum settings and upload template fails
3) changed to development version

**To Reproduce**
1. Go to 'services'
2. Click on 'captive portal'
3. Click on 'administrator'
4.  Click on 'templates'
5.  Click on 'add'
6. Enter name and upload template file

**Expected behavior**
it should accept the new modified template file. im just using simple html. 

**Relevant log files**
most not acepted template show no logs... some that would show this on log
`2020-12-29T15:25:37   configd.py[21139]   [a922a169-75f8-4825-b177-b9f86287c90c] Script action failed with Command '/usr/local/opnsense/scripts/OPNsense/CaptivePortal/strip_template.py 'cp_2cfdbd8d-c875-430b-af03-3897a1af90ff.tmp'' returned non-zero exit status 1. at Traceback (most recent call last): File "/usr/local/opnsense/service/modules/processhandler.py", line 479, in execute stdout=output_stream, stderr=error_stream) File "/usr/local/lib/python3.7/subprocess.py", line 363, in check_call raise CalledProcessError(retcode, cmd) subprocess.CalledProcessError: Command '/usr/local/opnsense/scripts/OPNsense/CaptivePortal/strip_template.py 'cp_2cfdbd8d-c875-430b-af03-3897a1af90ff.tmp'' returned non-zero exit status 1.`

upload the default unmodifed template shows
`2020-12-29T15:34:49   configd.py[21139]   [9a61b866-280c-4471-a8c1-58002e77b404] strip user captiveportal web template package and return new base64 encoded content`

**Additional context**
I would believe that 20.7.5 should be working since at that time, I uploaded a christmas template, which was accepted.

OPNsense 20.7.7_1-amd64
Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 cores)

OPNsense 20.7.7_1-amd64
Intel(R) Celeron(R) CPU 1037U @ 1.80GHz (2 cores)

OPNsense 20.7.7_1-amd64
Intel(R) Core(TM) i3-7100U CPU @ 2.40GHz (4 cores)

OPNsense 21.1.a_272-amd64
Intel(R) Celeron(R) CPU 1037U @ 1.80GHz (2 cores)

**Comment by fichtner** [comment]
Probably #4533

**Comment by fichtner** [comment]
Yes, was #4533
