### ISSUE TITLE
typo in proxy config may prevent squid from starting, timing out configd

### ISSUE THREAD

**Issue by fichtner** [opnsense/core#456]
Could this be the case? If not or too old feel free to close.

    [05-Nov-2015 21:18:00 XXX/XXX] PHP Fatal error:  Uncaught exception 'Exception' with
    message 'Timeout (120) executing :proxy restart' in
    /usr/local/opnsense/mvc/app/library/OPNsense/Core/Backend.php:100
    Stack trace:
    #0 /usr/local/etc/inc/legacy_bindings.inc(56): OPNsense\Core\Backend->configdRun('proxy restart', false)
    #1 /usr/local/www/status_services.php(271): configd_run('proxy restart')
    #2 /usr/local/www/status_services.php(57): service_control_restart('squid', Array)
    #3 {main} thrown in /usr/local/opnsense/mvc/app/library/OPNsense/Core/Backend.php on line 100
 
    This may or may not have been as a result of a typo in the squid.conf
    file resulting in squid being unable to start.

via: Crash Reporter (version 15.7.11)

**Comment by AdSchellevis** [comment]
Not sure, a solution in this case could be to push the restart to the background and not wait for a response, or log the timeout to syslog instead of crashing out... getting squid 100% valid all the time looks quite impossible with the number of (advanced) configurable options in there (we don't have a full dependency matrix).

**Comment by fichtner** [comment]
Is there a sanity check option included in squid we could weave into the restart command to abort early?

**Comment by AdSchellevis** [comment]
squid -k parse, but I don't think that solves anything, because if the parse fails.... it won't wait.

**Comment by fichtner** [comment]
something like this maybe?

    if squid -k parse; then squidstart1234; else false; fi

**Comment by AdSchellevis** [comment]
Need to test, but.... very likely won't solve your timeout issue, it looks like it doesn't know it's wrongly configured and waits for something...

**Comment by fichtner** [comment]
I've never seen this again, closing.
