### ISSUE TITLE
Dpinger not working on link local - link local gateway route issue

### ISSUE THREAD

**Issue by marjohn56** [opnsense/core#4565]
[x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
[x] I have searched the existing issues and I'm convinced that mine is new.

This is on a clean install on my test system, but have had this issue for a long time on previous releases.

**REPLICATION**
The upstream gateway is my primary Opnsense router which is working correctly oddly enough; Sometimes difficult to replicate, hence the 'not everyone' I was able to replicate this with ease by disabling and then re-enabling the WAN interface, doing so immediately resulted in a dpinger failure and also a ping from the shell to the gateway would fail.

This issue is odd in that it's not always, often the gateway monitor is working after a reboot, and it appears that not everyone has the problem but there are reports on the forum going back many months.

 Any dpinger IPv6 or local pings to the gateway come back with no route to host.  Using Wireshark I observed there are **no** ICMPV6 packets  leaving Opnsense. Checking Netstat there is no issue with the gateways and normal traffic flows fine, it seems only ICMPv6 packets are affected. 

Looking at the firewall code it seems that ICMPv6 type 129 ( Echo Replies ) are allowed, but not Type 128 ( Echo Requests ) **from** the  WAN interface. I modified line 242 in filter.lib.,inc to include type 128 ICMPv6 packets and now see packets leaving ( and getting responses ) the firewall.

After applying this change I have not seen the issue re-appear even after multiple WAN disable/enable events.

OPNsense 20.7.7_1-amd64
FreeBSD 12.1-RELEASE-p11-HBSD
OpenSSL 1.1.1i 8 Dec 2020

**Comment by fichtner** [comment]
@marjohn56 thanks, it seems to make sense when the state tracking fails. I'm still wondering about the other IPv6 essentials if we should add 129 as well to avoid further issues or just leave it where it is now. Maybe @AdSchellevis can share a thought here as well.

**Comment by marjohn56** [comment]
129 is for replies on an 'out' rule, so I guess maybe not. Though with ICMPv6 if you read one set of requirements it says all ICMPv6 should be allowed and on another it says only certain ICMPv6 should be allowed.. I guess it's a stick your finger in the air and see which way the wind blows.  I suppose purists would say 129 should not be there and its down to the user to allow 129 if they wish with their own rule. Personally, I'd leave it as is.

**Comment by AdSchellevis** [comment]
I don't mind adding 129 as well here, standards and IPv6 seem to be a bit fluent from time to time, so if this fixes the issue for most users I guess we should just add it and consider this case closed. Thanks @marjohn56 @fichtner

**Comment by shonjir** [comment]
Suggest referring to the RFC4890, "Traffic that must not be dropped"
https://tools.ietf.org/html/rfc4890#section-4.3

**Comment by AdSchellevis** [comment]
@shonjir we could change "IPv6 requirements (ICMP)"  for (something like) "IPv6 RFC4890 requirements (ICMP)" in the rule description if that helps explain the automatic rules. I expect all of the rules have a relation with that rfc.


https://github.com/opnsense/core/blob/4e0fdb516ad48e4f64821dfdefec50595d514b0f/src/etc/inc/filter.lib.inc#L232-L267

**Comment by shonjir** [comment]
@AdSchellevis I think your proposal is good - it helps explain where the requirements come from and that's usually a good thing.

**Comment by AdSchellevis** [comment]
@shonjir ok, I've added it for a future release, it's good to know origins of decisions indeed.

**Comment by fichtner** [comment]
We will add all this for 20.7.8. Thanks to all!
