### ISSUE TITLE
Config.xml - password not imported from pfSense

### ISSUE THREAD

**Issue by SamantazFox** [opnsense/core#4570]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

- [x] I have searched the existing issues and I'm convinced that mine is new.

**Describe the bug**
Impossible to login to live mode (neither with `root`, `installer` nor `admin`) when config.xml was imported from an existing 2.4.x pfSense installation.

**To Reproduce**
1. Have a pfSense 2.4.x (2.4.5 in my case) install on ada0
2. Use the latest installer (20.7 at time of writing)
3. Run config importer when prompted 
4. Let the live mode initialize itself
5. Try to log in (webGUI/SSH) with the user password from the pfSense from step 1

**Expected behavior**
The `admin` password from a previous pfSense install can be used in OPNsense with the `root` or `installer` users, either from the webGUI or SSH, as described in the [Install docs](https://docs.opnsense.org/manual/install.html#live-environment)

**Additional context**
It seems likely that the problem come from the password field in the XML config file.

In OPNsense, the users' passwords are stored in a [`<passwd>` tag](https://github.com/opnsense/core/blob/master/src/etc/config.xml.sample#L227), where as in pfsense, they're stored in a [`<bcrypt-hash>` tag](https://github.com/pfsense/pfsense/blob/master/src/conf.default/config.xml#L31).

Furthermore, the default user in OPNsense is [`root`](https://github.com/opnsense/core/blob/master/src/etc/config.xml.sample#L223), where as in pfSense, it's [`admin`](https://github.com/pfsense/pfsense/blob/master/src/conf.default/config.xml#L27).

**Environment**
PCengine APU2
OPNsense 20.7 (amd64, OpenSSL) (serial image)

**Comment by AdSchellevis** [comment]
We generally advice to build a configuration from scratch our configuration isn't compatible with pfSense (we're not aiming for compatibility at the moment either). In the past we created some scripts for customers to ease the work, but since we diverted quite a bit, they will always be incomplete.

**Comment by fichtner** [comment]
A bit of trivia: compatibility was broken for non-technical reasons via https://github.com/pfsense/pfsense/commit/9219378b58 ;)

**Comment by SamantazFox** [comment]
> We generally advice to build a configuration from scratch
I have half a thousand firewall rules, plus many other configs (VPN, certs, ...), I'd like to avoid spending my next two weeks re-doing them :)

> A bit of trivia: compatibility was broken for non-technical reasons via [pfsense/pfsense@9219378](https://github.com/pfsense/pfsense/commit/9219378b58) ;)
Ah, yes, the famous OPN/pf senses war x)

**Comment by AdSchellevis** [comment]
nothing todo with a war, we don't offer imports for other firewall vendors either.

**Comment by fichtner** [comment]
> Ah, yes, the famous OPN/pf senses war x)

Well no, they changed the name for no apparent reason. If you rename "bcrypt-hash" to "password" it will likely work like it always did.

**Comment by SamantazFox** [comment]
mmh, okay. I was going to open another issue because pfSense also moved `/conf` to `/cf/conf`, and the installer can't find it. Should I, or not?

**Comment by AdSchellevis** [comment]
best don't bother, we don't offer a seamless migration and since quite some things are different, we really do advice to start from scratch so you always know which settings are different from our standards (and for which reasons).

**Comment by fichtner** [comment]
nah, just import config.xml into newly set up box from the GUI with a temporary IP :)

**Comment by SamantazFox** [comment]
> nah, just import config.xml into newly set up box from the GUI with a temporary IP :)

Sadly I can't, as the default IP will collide with another super important device on the network... I've tried to change the defaults right after flashing the installer on a USB stick, but it seems that Linux doesn't like ufs...

**Comment by fichtner** [comment]
ok or you could add msdosfs stick with /conf/config.xml structure and use that for early import, but as my newly esteemed  colleague @AdSchellevis said it is not unlikely that other things will go wrong later on since the format has diverged quite a bit over the years.

https://docs.opnsense.org/manual/install.html?highlight=early#opnsense-importer

**Comment by SamantazFox** [comment]
Could it be at least possible that, in case of a failure of the import script, the user is dropped in a root shell to solve the situation by themselves?

My biggest issue so far was that I couldn't access the shell once the live system had initialized (I'm stuck at the"welcome to OPNsense, ... <IP addresses> ... you can login with root or installer ...." prompt, and input are accepted on the serial console anymore)

**Comment by fichtner** [comment]
I'm not sure about how to detect an error lest to say if it is recoverable, but if you type "!" in the early importer it drops you into a shell...

**Comment by SamantazFox** [comment]
For the early importer, I managed to get a root shell by spamming ctrl+C a dozen times, but a hint would be nice!

I don't know how the whole XML parsing process works, but being verbose on it and allowing to drop in a root shell after that everything (GUI, firewall, etc...) had initialized would be nice, as a reboot don't allow to keep the useful informations on screen.
