### ISSUE TITLE
IPV6-ICMP Rules broken

### ISSUE THREAD

**Issue by dariks** [opnsense/core#4575]
- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues and I am convinced that mine is new.

**Describe the bug**

Creating and/or editing ICMPv6 (IPV6-ICMP) Rules leads to an Error.

The Error is as follows:
"The following input errors were detected:
You can not assign an ICMP type to a rule that applies to IPv4 and IPv6."

I'm very sure that I'm not combining a ICMPv4 and ICMPv6 Rule.

This Issue occurs since OPNSense 20.7.6 and still is a Issue as of 20.7.7 (even with the latest hotfix). Reverting to 20.7.5 fixes this issue.
In the 20.7.5 Changelog i think the Error is related to this change: "firewall: add validation for ipv6-icmp combined with inet"

1. Go to 'Firewall', 'Rules', [any Interface] (I tried specific Interfaces and Floating too)
2. Click on '(+) Add'
3. Add Rule as follows: "Pass; WAN; in; IPv6, IPV6-ICMP ;any ;any ;any
4. Click Save
5. Error appears

Error Message:
"The following input errors were detected:
You can not assign an ICMP type to a rule that applies to IPv4 and IPv6."

**Expected behavior**

Rule should be saved and be able to Apply. Saving Rule first checks it and returns Error

**Screenshots**
![opn-rule-1](https://user-images.githubusercontent.com/11924209/103744220-b3651b00-4ffd-11eb-8d62-a2e310bd20b9.png)
![opn-rule-2](https://user-images.githubusercontent.com/11924209/103744228-b6f8a200-4ffd-11eb-955a-6ab14005be36.png)
![opn-rule-error](https://user-images.githubusercontent.com/11924209/103744232-b8c26580-4ffd-11eb-9940-f79b106722a7.png)

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 20.7.7_1 (amd64, OpenSSL).
Supermicro SYS-E200-8D
Intel(R) Xeon(R) CPU D-1528 @ 1.90GHz (6 cores)
32GB DDR4 ECC
Network 2x Intel® i350-AM2
Network 2x SoC 10G RJ45

**Comment by fichtner** [comment]
Should be https://github.com/opnsense/core/issues/4562 with fix on the way in 20.7.8
