### ISSUE TITLE
Traffic not flowing over clean GRE after cron reboot

### ISSUE THREAD

**Issue by peironem** [opnsense/core#4576]
<h3>Important notices</h3>
Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues and I am convinced that mine is new.

<h3>Describe the bug</h3>
Traffic routed over clean GRE tunnel seems to stop after a scheduled device reboot.

Let's say i have a site A with two lans, one wan, one gre
 - igb0 172.115.28.90 (MPLS IP assigned by ISP)
 - igb1 192.168.1.0/24
 - igb2 172.16.10.0/24
 - gre0 10.10.10.1/30 (Leaning on WAN igb0 GW 10.10.10.2)

Let's say i have a site B with one lan and one wan
 - igb0 172.115.28.100 (MPLS IP assigned by ISP)
 - igb1 172.16.10.0/24
 - gre0 10.10.10.2/30 (Leaning on WAN igb0 GW 10.10.10.1)

Site A routes when GRE is up:
192.168.0.0/24 via 10.10.10.2

Site B routes when GRE is up:
192.168.1.0/24 via 10.10.10.1
172.16.10.0/24 via 10.10.10.1

After Cron scheduled device reboot i'm always founding traffic not flowing trough GRE tunnel, notice that GRE tunnel is up and reachable both directions. I'm actually just solving the problem disabling and enabling back the 3 routes writed above: after that i can see all the traffic flow over GRE tunnel as expected.

<h3>To Reproduce</h3>
Configure GRE tunnel between two devices, A and B.
On B: route A Lan over GRE with a static rotue entry
On A: route B Lan over GRE with a static route entry

Configure on Cron a scheduled reboot: once the device comes back up traffic will be forwarded to 0.0.0.0/0 ignoring the static route(s) entry(es).

<h3>Expected behavior</h3>
I'm just expecting the traffic to flow over GRE as statics routes tolds to it.

<h3>Screenshots</h3>
N/A

<h3>Relevant log files</h3>
N/A

<h3>Additional context</h3>
N/A

<h3>Environment</h3>
OPNsense 20.7.7_1 (site A)

OPNsense 20.1.8_1 (site B)

**Comment by peironem** [comment]
Hi.
I was digging a bit on the problem via ssh:  i can clearly see that the gui isn't creating the routes under BSD os.

OS before cron reboot
> root@opnsense:~ # route show 192.168.1.0/24
>  route to: 192.168.1.0
> destination: 192.168.1.0
>      mask: 255.255.255.0
> gateway: 10.10.10.1
>          fib: 0
> interface: gre0
>       flags: <UP,GATEWAY,DONE,STATIC>
> recvpipe  sendpipe  ssthresh  rtt,msec    mtu        weight    expire
>      0              0             0             0       1476            1           0

OS after cron reboot
> root@opnsense:~ # route show 192.168.1.0/24
> route: route has not been found

OS after disabling and reenabling back static routes
> root@opnsense:~ # route show 192.168.1.0/24
>  route to: 192.168.1.0
> destination: 192.168.1.0
>      mask: 255.255.255.0
> gateway: 10.10.10.1
>          fib: 0
> interface: gre0
>       flags: <UP,GATEWAY,DONE,STATIC>
> recvpipe  sendpipe  ssthresh  rtt,msec    mtu        weight    expire
>      0              0             0             0       1476            1           0

**Comment by fichtner** [comment]
Can you try this patch? https://github.com/opnsense/core/issues/3414#issuecomment-759328642

**Comment by fichtner** [comment]
@peironem are you on 21.1 now? I prepared another patch that looks like it will help in your case: a980771

    # opnsense-patch a980771


Cheers,
Franco

**Comment by fichtner** [comment]
Sorry, it needs two patches:

    # opnsense-patch a980771 90ad674

**Comment by peironem** [comment]
Sorry @fichtner i moved all our firewalls on pfsense distribution because this issue was creating some nasty broblems on our sites interconnections.
If i'll buy any new firewall i'll test this.
Thanks anyway for your help.

**Comment by fichtner** [comment]
Ok, no problem.

Note to self: clean up rc.newwanip
