### ISSUE TITLE
GUI: sidebar persistent state

### ISSUE THREAD

**Issue by kulikov-a** [opnsense/core#4580]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues and I am convinced that mine is new.

**Is your feature request related to a problem? Please describe.**

Hi!
At the moment the sidebar state is not persisted between tabs\sessions.
imho it would be more convenient if this setting were more persistent

**Describe the solution you like**

Could you please move the toggle_sidebar_preset to localStorage in opnsense_theme.js?
Thanks!

**Describe alternatives you considered**

A clear and concise description of any alternative solutions or features you considered.

**Additional context**

Add any other context or screenshots about the feature request here or links to relevant forum thread or similar

**Comment by AdSchellevis** [comment]
@kulikov-a sure, sounds like a good idea. https://github.com/opnsense/core/commit/7c50093c122e74a45918c5a59b3d3f950775e095 moves the setting from session to local

**Comment by kulikov-a** [comment]
Thanks!!
