### ISSUE TITLE
Firewall / NAT: support category filters

### ISSUE THREAD

**Issue by AdSchellevis** [opnsense/core#4587]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues and I am convinced that mine is new.

**Is your feature request related to a problem? Please describe.**

Categories are currently only supported in the firewall section itself, when utilising large number of port forwards and/or outbound nat rules it could be practical to use the same concept there as well.

**Describe the solution you like**

Move the categories into a separate module to be used in other firewall sections as well and refactor the current legacy pages for outbound nat rules and port forwards to include categories. In a future version there's also a wish to support multiple category tags on a single rule, in which case we would replace the current type ahead input for the same tokeniser used in other components.

**Describe alternatives you considered**

none

**Additional context**

By moving the categories into its own model we also might consider options like color tags in the future and can reuse items in different sections. In case we would eventually replace the legacy input screens for api enabled ones these patterns should be easy to adopt as well.

-----

sponsored by : Modirum (https://www.modirum.com/)

**Comment by mimugmail** [comment]
Colors would be nice, so when you have e.g. 3 categories selected you still see which rule is for which category

**Comment by fichtner** [comment]
@AdSchellevis are you aiming for 21.1?

**Comment by AdSchellevis** [comment]
@fichtner no promises, but giving it a try

**Comment by fichtner** [comment]
no worries, better flip milestones then :)

**Comment by opnsenseuser** [comment]
@AdSchellevis do I have to adapt this for the other themes (cicada, vicuna e.g)? What exactly has to be done? regards rené

**Comment by AdSchellevis** [comment]
@opnsenseuser I don't expect you will need changes for the themes, the standard theme wasn't changed either for this and the category selector itself was already in the firewall page, only the backend code changed (the badge on the right will likely also work on the other themes, colours are selectable). I think the color selector is the only small item that might have a small risk of looking different, the layout of the component is sort of standard.

![image](https://user-images.githubusercontent.com/9783985/105142684-2b9e0700-5afb-11eb-9157-44f4a9f79d45.png)

![image](https://user-images.githubusercontent.com/9783985/105142947-7c156480-5afb-11eb-9f1f-63d73ca8f58a.png)

**Comment by 8191** [comment]
@AdSchellevis Just tested the new functionality, looks really like a big step head in organizing a big amount of rules. 👍🏻 

Some minor UI topics I found:
*  Helptext of the "automatic" checkbox reads: _Automatically added, will be removed when **used**_ I guess it should read "unused"?
* Does it make sense to have the checkbox read-only?
* Fields in the form are written in uppercase in all other forms, except the category add/edit form (Color instead of color). Also the tab in the view is written in lowercase currently. --> #4634

What's your opinion on following improvements:
* Display mouse-over text when hoovering over a coloured bullet.
* Add "(no category)" to the filter box at the top to allow identifying rules without category.

**Comment by AdSchellevis** [comment]
@8191 Thanks, I've corrected the help text. We don't need to change the property to read-only, since you may choose to persist the automatic ones as well (remove marker). The proposed additions look practical, if you open a ticket, I'll try to tale a look later.

**Comment by opnsenseuser** [comment]
@AdSchellevis i need a few little color changes. can i put the modified pick-a-color-1.2.3.min.css into each theme folder? Like >> /build/css/pick-a-color-1.2.3.min.css. Does this work?

Regards René

**Comment by AdSchellevis** [comment]
@opnsenseuser that should work indeed, it picks the stylesheet from the theme folder first.

**Comment by opnsenseuser** [comment]
👍

**Comment by opnsenseuser** [comment]
@AdSchellevis I just wanted to ask you what you think of adjusting the category color window to the width of the dropdown menu. i know that this is not important for a firewall, but a gui has to look tidy for me, then it is clearer and it is also more fun. what do you mean?

![grafik](https://user-images.githubusercontent.com/34602360/106356541-aab3ec00-6300-11eb-9ce9-fbc9809bb9ca.png)

**Comment by AdSchellevis** [comment]
@opnsenseuser that looks neat indeed, if it's only a single diff we need to change with an additional style, I don't mind that much, for the standard theme I do prefer to keep the default stylesheets as much as possible to avoid future breakage when new versions are released.
