### ISSUE TITLE
API: Firewall: Import Aliases as JSON

### ISSUE THREAD

**Issue by 8191** [opnsense/core#4589]
**Important notices**

Our forum is located at https://forum.opnsense.org , please consider joining discussions there in stead of using GitHub for these matters.

Before you ask a new question, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues and I am convinced that mine is new.

The current firewall API for the alias controller allows `import`ing aliases only as PHP arrays. As the `export` command outputs a JSON formatted string, import should also allow sending JSON strings.
I'd like to implement that, but I'm not sure which HTTP mechanism would be the right one.

1. File uploading with Content-Type application/json (`$this->request->getUploadedFiles()` in the controller)
2. Sending POST data with content-type application/json (`$this->request->getPost()` in the controller)

I personally would prefer option 1, but I could not find any API method accepting files, so far. What's the right paradigm to choose here?

**Comment by AdSchellevis** [comment]
I'm note exactly sure what you mean, the request structure is more or less the same as the response.

push json encoded in:
https://github.com/opnsense/core/blob/9fba75cc70c7a1687564cb5b8ca419202e1eebef/src/opnsense/mvc/app/views/OPNsense/Firewall/alias.volt#L364

being fetched in the controller like other responses are handled as well
https://github.com/opnsense/core/blob/9fba75cc70c7a1687564cb5b8ca419202e1eebef/src/opnsense/mvc/app/controllers/OPNsense/Firewall/Api/AliasController.php#L287

The framework deserialises the post json encoded data.

sample post data:

```
{"data":{"aliases":{"alias":{"9369c77d-3fca-4b87-9930-17261003e773":{"enabled":"1","name":"CH","type":"geoip","proto":"IPv4","counters":"0","updatefreq":"","content":"CH","description":"CH"}}}}}
```

**Comment by 8191** [comment]
@AdSchellevis Thanks for the explanation! There was actually a misunderstanding on my side.

Key facts for others having a similar issue:
* HTTP request content-type needs to be application/json so that Phalcon actually performs json deserialisation.
* The output of the export command needs to be wrapped in a json object's `data` attribute before importing.

Example using cURL:
```sh
$aliases = $(curl -u "apikey":"apisecret" https://opnsense/api/firewall/alias/export)
curl -u "apikey":"apisecret" https://opnsense/api/firewall/alias/import --header "Content-Type: application/json" --data '{"data":'$aliases'}'
```
