### ISSUE TITLE
Unbound Blacklist: Generated dnsbl.conf starts splitting domain names when a list is over a certain amount of lines

### ISSUE THREAD

**Issue by defiantmonkey** [opnsense/core#4595]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues and I am convinced that mine is new.

**Describe the bug**

When generating the dnsbl.conf of a list that contains a certain number of lines/domains (so far from the lists I've tested, seems to be around 100,000 lines), the number of entries in dnsbl.conf and the original list do not match, with some domains seeming getting split in dnsbl.conf (ie: 077ca5eaa2c83c12d5f6dd3389e9016f.redinuid.imrworldwide.com in the orginal becoming two entries in dnsbl.conf - 077ca5eaa2c83c12d5f6dd3389e9016f.redinuid. and imrworldwide.com). I only noticed this due to a bigger list I was working with somehow getting the TLD "org" in the list and did a compare using meld.

**To Reproduce**

1. Enable Unbound service and Blacklist
2. In blacklist configuration, with no other lists enabled, toggle advanced mode and enter a list in "URLs of Blacklists" such as https://raw.githubusercontent.com/lightswitch05/hosts/master/docs/lists/ads-and-tracking-extended.txt
3. Save and let the downloader run
4. Go to logs and filter for download
5. See that lines/records from download are greater in number than the number of domains from the original list
6. Copy both original list and dnsbl.conf, stripped to only the domain names and sorted, into a compare tool like meld then see that some domains from dnsbl.conf are different/not present in the original list

**Expected behavior**

The dnsbl.conf is populated with an equal or lesser number of entries without domains having been split in the process. 

**Screenshots**

N/A

**Relevant log files**

Here's the log output from testing with only this list being downloaded: https://raw.githubusercontent.com/lightswitch05/hosts/master/docs/lists/ads-and-tracking-extended.txt

unbound[87006] | blacklist  download  https://raw.githubusercontent.com/lightswitch05/hosts/master/docs/lists/ads-and-tracking-extended.txt  (lines: 271128 exclude: 2 black: 271102
unbound[87006] | blacklist download done in 1.86 seconds (271102 records)

**Additional context**

N/A

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 20.7.7_1 (amd64, LibreSSL 3.1.5).
qemu VM emulating pc-i440fx-3.1
8GB RAM and 2 vCPU

**Comment by defiantmonkey** [comment]
I came across a bit of an interesting finding when trying things out a bit more. For context, I'm mirroring a lot of the lists I use to my own hosted gitea instance (in case they become unavailble mainly). 

Trying out this list: https://raw.githubusercontent.com/hectorm/hmirror/master/data/zerodot1-coinblockerlists/list.txt
I got the expected number of domains, log output:
blacklist download https://raw.githubusercontent.com/hectorm/hmirror/master/data/zerodot1-coinblockerlists/list.txt (lines: 89562 exclude: 18 black: 89544

Now, for privacy reasons I'm not linking to my own hosted gitea account, but I did find another gitea instance, make an account there, and mirror the same repository. Using the mirrored list from either gitea repo provided the exact same result (https://gitea.gwm.dev/defiantmonkey/hmirror/raw/branch/master/data/zerodot1-coinblockerlists/list.txt):
blacklist download https://gitea.gwm.dev/defiantmonkey/hmirror/raw/branch/master/data/zerodot1-coinblockerlists/list.txt (lines: 89700 exclude: 34 black: 89663

I had another list around 66,000 domains or so that had no issue when using my instance link for the blacklist url. This may seem at first like it's a gitea issue since the above comparison only had issue on the gitea instance, but my original example  in the first post was also from github, which provided more domains than the original list specified.

Thus this looks like it could be an issue either with how the file is being downloaded, or possibly some sort of character encoding issue. I'm not expert, but it seems like a good starting point...

**Comment by kulikov-a** [comment]
I can confirm this behavior.
tested on https://raw.githubusercontent.com/lightswitch05/hosts/master/docs/lists/ads-and-tracking-extended.txt
And this is not in records sanitizing \ whitelisting.
dumped lines to file before string 114 in https://github.com/opnsense/core/blob/master/src/opnsense/scripts/unbound/download_blacklists.py.
broken lines are already there. like:
`0.0.0.0 5c9e9d3c40464f1287a5fb2c3d9fac1
f-964d5cc6cbb7.cdn.usw.forter.com`
want to try `iter_content` instead of `raw` in `requests`

**Comment by kulikov-a** [comment]
its in 
`
                parts = (prev_chop + chop).split('\n')
                if len(parts) > chop.find('\n'):
                     prev_chop = parts.pop()
                else:
                    prev_chop = ''
                for part in parts:
                    yield part
`
so there may be a situations when the chunk ends, the comparison condition is not met and the splitted string is sent to the array part array
imho its should be
`
                parts = (prev_chop + chop).split('\n')
                if chop[-1] != "\n":
                     prev_chop = parts.pop()
                else:
                    prev_chop = ''
                for part in parts:
                    yield part
`

**Comment by AdSchellevis** [comment]
@kulikov-a  sounds reasonable, you should only check if the file ends without a `\n` it would still return the last row (I expect so, but better to check). If you open a PR,, I'll give it a try on my end and merge it.

**Comment by kulikov-a** [comment]
@AdSchellevis 
thanks! will check on file without end `\n` (should return last string via `prev_chop` in `if not chop` part) and make PR

**Comment by defiantmonkey** [comment]
Sorry hadn't had a chance to play around with tstuff for a while, I can confirm this issue is resolved, so I will close this now, thanks for fixing!
