### ISSUE TITLE
Captive portal: SSL enabled on HTTP port, too

### ISSUE THREAD

**Issue by pief** [opnsense/core#4596]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I have searched the existing issues and I am convinced that mine is new.

**Describe the bug**

In my OpnSense setup I noticed that common browsers' captive portal detection wasn't working anymore since last applying updates before Xmas. The captive portal's HTTP port was always closing connections immediately. Turns out this is because SSL is wrongly enabled for the HTTP port as well.

**To Reproduce**

1. Activate a captive portal configuration with a SSL certificate.
2. Try e.g. Firefox on the restricted interface and browse to http://detectportal.firefox.com

**Expected behavior**

The captive portal should appear.

**Additional context**

See the template [lighttpd-zone.conf](https://github.com/opnsense/core/blob/master/src/opnsense/service/templates/OPNsense/Captiveportal/lighttpd-zone.conf): as soon as a SSL certificate is configured `ssl.engine = "enable"` gets enabled globally. There is no block that selectively disables SSL for the HTTP port.

**Suggested fix**

Add `ssl.engine = "disabled"` to these blocks:

```
$SERVER["socket"] == ":{{ cp_zone_item.zoneid|int + 9000 }}" {
	ssl.engine = "disable"  # <-- *** new line added ***
	$HTTP["host"] =~ "([^:/]+)" {
		url.redirect = ( "^(.*)$" => "{{cp_zone_item.redirect_host}}?redirurl=%1$1")
	}
}
$SERVER["socket"] == "[::]:{{ cp_zone_item.zoneid|int + 9000 }}" {
	ssl.engine = "disable"  # <-- *** new line added ***
	$HTTP["host"] =~ "([^:/]+)" {
		url.redirect = ( "(.*)" => "{{cp_zone_item.redirect_host}}?redirurl=%1$1")
	}
}
```

**Environment**

OPNsense 20.7.7

**Comment by fichtner** [comment]
Same issue as GUI, ok, will fix in 20.7.8. 😔

**Comment by pief** [comment]
Thank you! But what did you mean with "Same issue as GUI"?

**Comment by fichtner** [comment]
See https://github.com/opnsense/core/commit/729265228bf which was the "_1" part of 20.7.7 update (hotfix).

**Comment by fichtner** [comment]
Thanks for the report ❤️
