### ISSUE TITLE
DHCP Lease Update script does not add PTR correctly in Unbound

### ISSUE THREAD

**Issue by mmeier86** [opnsense/core#4597]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues and I am convinced that mine is new.

**Describe the bug**

The [unbound_dhcp.py script](https://github.com/opnsense/core/blob/master/src/opnsense/scripts/dns/unbound_dhcpd.py) for updating DHCP leases in Unbound does not work for the PTR entries. In particular, the live update via `unbound-control` does not work for the PTR (A record works as expected). The `local-data-ptr` entry in `dhcpleases.conf` works correctly, so after a restart of Unbound, the IP is correctly resolved to the right hostname.

I believe the culprit here is the following line in the `unbound_dhcp.py` script:

https://github.com/opnsense/core/blob/bdc443096370efd38e5833eb11858d6dcdb16e5d/src/opnsense/scripts/dns/unbound_dhcpd.py#L154

The problem seems to be the format of the entry for PTR send with `unbound-control local_data`. I tried the command the script would execute while being logged into my OPNSense box with `unbound-control -c /path/here local_data "10.86.5.21 PTR amun.home"`. This returned `ok`, but `nslookup 10.86.5.21` still returned `** server can't find 21.5.86.10.in-addr.arpa: NXDOMAIN`. 

After some different ways of formatting, the following worked: `unbound-control -c /path/here local_data "21.5.86.10.in-addr.arpa IN PTR amun.home"`

**To Reproduce**

In the following reproduction, I've got a host `amun.home` which gets the DHCP IP `10.86.5.21`, dynamically.

Steps to reproduce the actual error I observed:
1. Delete lease in DHCP config
2. Wait until lease expires and is removed from Unbound
3. run `nslookup 10.86.5.21`. This fails as expected with `** server can't find 21.5.86.10.in-addr.arpa: NXDOMAIN`
4. Have the machine get a new lease
5. run `nslookup amun.home`. Observe that you get the correct IP, `10.86.5.21` back
6. run `nslookup 10.86.5.21`. This fails again with `** server can't find 21.5.86.10.in-addr.arpa: NXDOMAIN`
7. Have a look at `/var/unbound/dhcpleases.conf` and observe that the correct entry `local-data-ptr: "10.86.5.21 amun.home"` exists
8. Restart Unbound
9. run `nslookup 10.86.5.21` yet again. Observe that you now get the correct hostname

**Expected behavior**

A reverse DNS lookup on the address of a host added to Unbound via DHCP returns that host's FQDN.

**Environment**

OPNsense 20.7.7 (amd64, OpenSSL).

**Comment by AdSchellevis** [comment]
you can use `unbound-control` to query the local data to see what it registered, the same doesn't appear to be happening on our setup (at a first glance it doesn't look like a general bug).

```
unbound-control -c /var/unbound/unbound.conf list_local_data 
```

**Comment by mmeier86** [comment]
I can reproduce the faulty behaviour manually like this, for an imaginary host "test.home" with IP "10.86.5.24". For reference, "home" is my local domain and my DHCP hands out addresses in the range "10.86.5.[20-50]", so this should simulate a real host.

All commands executed on my OPNsense box as root.

- Make sure no record exists for the machine: `nslookup 10.86.5.24`
- Check local data: `unbound-control -c /var/unbound/unbound.conf list_local_data | grep "test.home"` returns nothing
- Manually replay the command the `unbound_dhcp.py` script would use to make the live update: `unbound-control -c /var/unbound/unbound.conf local_data "10.86.5.28 PTR test.home"`
  - As said, the update of the `dhcpleases.conf` file works without issue
- Check whether Unbound answers the query correctly: `nslookup 10.86.5.24`
  - Returns `** server can't find 28.5.86.10.in-addr.arpa: NXDOMAIN` again
- Check local data: `unbound-control -c /var/unbound/unbound.conf list_local_data | grep "test.home"`
  - Returns `10.86.5.28.     3600    IN      PTR     test.home.`
  - This should be `28.5.86.10.in-addr.arpa  3600    IN      PTR     test.home.`

Running the changed command as proposed above:

- Command with correct syntax: `unbound-control -c /var/unbound/unbound.conf local_data "28.5.86.10.in-addr.arpa PTR test.home"`
  - Checking DNS: `nslookup 10.86.5.28` returns `28.5.86.10.in-addr.arpa name = test.home.`
- Checking local data: `unbound-control -c /var/unbound/unbound.conf list_local_data | grep "test.home"`
  - now returns both, the initial (wrong) entry, and the following new entry: `28.5.86.10.in-addr.arpa.        3600    IN      PTR     test.home.`
