### ISSUE TITLE
MVC: configuration serialisation reorders existing arguments causing spurious differentials

### ISSUE THREAD

**Issue by fichtner** [opnsense/core#4603]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues and I am convinced that mine is new.

**Describe the bug**

In the MVC saving new items can reorder the existing items in a config.xml.

**To Reproduce**

E.g. adding second entry to traffic shaper.

**Expected behavior**

Instead of reordering, the nodes should not switch places.

**Screenshots**

````
@@ -2703,52 +2703,6 @@
         <dotservers/>
       </miscellaneous>
     </unboundplus>
-    <TrafficShaper version="1.0.3">
[snipped]
-    </TrafficShaper>
     <Tinc version="1.0.2">
       <networks/>
       <hosts/>
@@ -3196,6 +3150,74 @@
         <LogPayload>0</LogPayload>
       </general>
     </IDS>
+    <TrafficShaper version="1.0.3">
[snipped]
+    </TrafficShaper>
   </OPNsense>
````

**Relevant log files**

N/A

**Additional context**

N/A

**Environment**

All recent versions.

**Comment by AdSchellevis** [comment]
@fichtner https://github.com/opnsense/core/commit/d406ff2a8348c3a5ce896b6e024ce2acc6b8632d should fix the sorting issue.

**Comment by fichtner** [comment]
confirmed... this is awesome, thanks a lot! ❤️
