### ISSUE TITLE
MVC Framework: Access IntegerField's Integer Value

### ISSUE THREAD

**Issue by 8191** [opnsense/core#4607]
**Important notices**

Our forum is located at https://forum.opnsense.org , please consider joining discussions there in stead of using GitHub for these matters.

Before you ask a new question, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues and I am convinced that mine is new.
-------

**What's the "right" way to access the integer value of a field defined as `IntegerField` in the model?**

As the `IntegerField` class is directly derived from `BaseField` and does not provide any method to access the `$internalValue`, only can only indirectly access the value via the `__toString` method. Therefore accessing the actual value of an integer field seems quite strange to me, and I'm not sure if that's the intended way:

```php
$mdl = MyModel();
$value = intval((string)$mdl->intValue);
```

What's the intention of the various field types? Only providing input validation, or also providing the right value on a programmatic level?

**Comment by AdSchellevis** [comment]
it's only input validation, 90% of the output ends up in template output which is generated from xml anyways. Offering some sort of cast handle shouldn't be too difficult, so far there hasn't been demand for it yet.
