### ISSUE TITLE
Clicking Pie Chart Slice in Insight with Reverse Lookup Checked Writes Invalid Details Filter

### ISSUE THREAD

**Issue by c0nsumer** [opnsense/core#4609]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I have searched the existing issues and I am convinced that mine is new.

**Describe the bug**

In _Insight_, after turning on _Reverse dns_ and clicking a slice of the pie to jump to _Details_ view, the view shows nothing because the _(src) Address_ filter is invalid. (It is populated with the hostname.)

**To Reproduce**

1. Go to Insight, Totals tab.
2. In _Top usage ports / sources (bytes)_ check the _Reverse lookup_ box.
3. Click a portion of the pie chart that has a resolved address to jump to the _Details_ tab.
4. Note the _(src) Address_ is populated with the resolved hostname and not the IP, resulting in no data being found.

**Expected behavior**

I'd expect that _(src) Address_ would be populated with the IP so the _Details_ view can show information.

**Environment**

OPNsense 20.7.7_1-amd64
FreeBSD 12.1-RELEASE-p11-HBSD
OpenSSL 1.1.1i 8 Dec 2020

**Comment by AdSchellevis** [comment]
https://github.com/opnsense/core/commit/c797bfd220c40e914f3bdd1dbd07c9c4377984f8 should do the trick, to test it should be enough to opnsense-patch on a console and reload the page:

```
opnsense-patch c797bfd
```

**Comment by c0nsumer** [comment]
Well, thank you! That was incredibly quick and is now working just as I'd expect. Thank you!
