### ISSUE TITLE
OPNsense 21.1.r_1-amd64 out of swap space

### ISSUE THREAD

**Issue by marshalleq** [opnsense/core#4610]
**Describe the bug**
I upgraded to OPNsense 21.1.r_1-amd64 yesterday with the idea to help get Suricata working properly.  I woke up this morning with no internet which turned out to be a non functioning DNS since 3am.

Looking in my OPNSense logs at 3am I can see two things happen:

1 - The cron job 'Update and reload detection rules' ran
2 - An error about running out of swap space occurred towards the end of this update (as per below logs).

Further investigation shows that the two processes using the most memory are Suricata and ClamAV and that my memory has now gone up to about 98% utilised where previously it was 30-50% utilised.

This has been running fine for many months prior to upgrading to the beta, however it could well be that something in the beta is actually running properly causing the memory requirement to go up (probably Suricata or ClamAV).  I did notice a few times that ClamAV would be stopped when I logged into the WebUI, but that didn't seem to be about a lack of memory.

I'll see what else I can find out and also look to get some more memory installed (only has 4GB right now).

<img width="1088" alt="Screen Shot 2021-01-17 at 8 40 22 AM" src="https://user-images.githubusercontent.com/13308996/104821571-bbe10f80-58a1-11eb-92dc-f29b277ca49a.png">
<img width="432" alt="Screen Shot 2021-01-17 at 8 40 57 AM" src="https://user-images.githubusercontent.com/13308996/104821581-c1d6f080-58a1-11eb-8982-8551e5ff125c.png">

**Comment by marshalleq** [comment]
Update - While restarting the services (ClamAV first, then Suricata), I have an out of swap space message again and again no DNS.  I can see it again in the logs.  I guess it's just using too much memory.  I can't remember if there was an option to setup SWAP in the install and if I just disabled it, or if it's literally using it all up.  Either way.  More RAM is needed.  Would it be useful to anyone if I checked that there was indeed less ram needed on stable by downgrading the OS to stable?

Thanks.

**Comment by marshalleq** [comment]
I've upgraded the RAM to 16GB now - should be enough.  So that should hopefully prevent the swap space being needed - will found out in due course.  I think it would be worthwhile to understand if there is an increased memory usage as it would probably change the requirements of firewalls with limited memory - like mine was.

**Comment by rudiservo** [comment]
@marshalleq  are you using Suricata policies and Hyperscan?

**Comment by marshalleq** [comment]
I was/am yes. But I have upgraded the ram now and it's not been an issue since.
