### ISSUE TITLE
20.7.7 bug No check for $data throws error on reporting -> Traffic

### ISSUE THREAD

**Issue by Z0t** [opnsense/core#4611]
Since 20.7.7 I get the following error randomly when monitoring traffic flow.  This resets the page and can be impactful when tracking live traffic issues.

The error reported:

`/usr/local/opnsense/mvc/app/controllers/OPNsense/Diagnostics/Api/TrafficController.php:74 - Invalid argument supplied for foreach() (errno=2)`

This seem to happen several times an hour which puts a pop up for each time the error happens.

https://github.com/opnsense/core/blob/de291e62660996b04d589381cad3396db5e9eb80/src/opnsense/mvc/app/controllers/OPNsense/Diagnostics/Api/TrafficController.php#L74

        if (count($iflist) > 0) {
            $data = (new Backend())->configdpRun('interface show top', [implode(",", $iflist)]);
            $data = json_decode($data, true);
            foreach ($data as $if => $content) {
                if (isset($ifmap[$if])) {
                    $response[$ifmap[$if]] = $content;
                }
            }
        }

It would appear that $data is not returning valid structures and there is not check for valid structure before the foreach so it fails.

This has been reported in the forums at least twice, and I've submitted "Crash" reports but the UI says it is not a crash (after I submit of course).

https://forum.opnsense.org/index.php?topic=20802.msg96877#msg96877

https://forum.opnsense.org/index.php?topic=20521.msg95452#msg95452

@AdSchellevis  this appears to be from your [commit ](https://github.com/opnsense/core/commit/4186f2bbe5dfd28dc7bf9f47585121e3273297f1)23 days ago

**Comment by AdSchellevis** [comment]
My commit is exactly the fix for this issue and is scheduled for 20.7.8 if I'm not mistaken (note the line 74 is now an is_array()).
```
Error at /usr/local/opnsense/mvc/app/controllers/OPNsense/Diagnostics/Api/TrafficController.php:74 - Invalid argument supplied for foreach() (errno=2)
```

**Comment by Z0t** [comment]
Ahh sorry I misread git blame.  I am not on the forums; it'd be good if someone could reply to those messages. Also if a maintainer could tag this with the release ID (rather than assume it is 20.7.8).

Thanks!

**Comment by fichtner** [comment]
There is nothing here to do but wait for 20.7.8 for 2-3 more days now.


Cheers,
Franco

**Comment by AdSchellevis** [comment]
sounds like a solid plan, lets close the issue
