### ISSUE TITLE
Local Authentication for IPsec Mobile Client VPN with EAP-MSCHAPV2 Fails

### ISSUE THREAD

**Issue by c0nsumer** [opnsense/core#4613]
Note: This issue may be similar to [4438](https://github.com/opnsense/core/issues/4438), but I have more information.

**Describe the bug**

I have created an and set up an IPsec VPN for mobile clients with EAP-MSCHAPV2 authentication. Authentication fails for local users who appear like they should have access.

**To Reproduce**

1. Create a local user in OPNsense user with a PSK defined, make them a member of a group called 'vpn'. 
2. Enable _IPsec Mobile Client Support_ and set _Enforce local group_ to the 'vpn' group.
3. Set up an IPsec tunnel for the mobile clients to use, with _EAP-MSCHAPV2_ for authentication on Phase 1.
4. Attempt to connect and authentication will fail. Something akin to this will be logged in the IPsec _Log File_:
`2021-01-17T21:54:00 | charon[56124] | 09[IKE] <con1\|19> no EAP key found for hosts 'CN=blah.example.com' - 'username'`

**Expected behavior**

I would expect that a user in the 'vpn' group would have access to the IPsec Mobile Client connection using its password via EAP-MSCHAPV2.

**Additional context**

In `/usr/local/etc/ipsec.secrets` I found the username listed, but with a PSK. This appears to be why EAP was failing. If I manually add an entry (eg: `username : EAP "password"`) and reload the secrets (`ipsec reload`) then authentication succeeds.

If I delete the user from OPNsense and create _Pre-Shared Key_ under _IPsec_ with the username as _Identifier_, password as _Pre-Shared Key_ and _Type_ as _EAP_ then authentication will succeed.

A few extra notes:

- After deleting the user from OPNsense, and before adding it as a standalone PSK, the PSK for this user was still present in `/usr/local/etc/ipsec.secrets`.)
- If the user is created without a PSK, there will be no PSK (nor EAP entry) in `/usr/local/etc/ipsec.secrets` and authentication will still fail.

**Environment**

OPNsense 20.7.7_1-amd64
FreeBSD 12.1-RELEASE-p11-HBSD
OpenSSL 1.1.1i 8 Dec 2020

**Comment by AdSchellevis** [comment]
eap-mschapv2 authentication has no direct relation with user management as far as I know (it needs the raw password to work), see https://docs.opnsense.org/manual/how-tos/ipsec-rw-srv-mschapv2.html#step-4-add-ipsec-users

At a first glance the system works as described in this case. (only confusing part is that you can still set a psk under the user, we should probably migrate those into the psk option at some time to avoid confusion.

**Comment by c0nsumer** [comment]
Ahhhhh, got it. Because of how things were listed it looked like it _should_ work, especially as many clients consider the EAP-MSCHAPV2 credentials a username/password and not a PSK. But I can also see how it is that.

Sounds like if I want something more traditional username/password then I need to use RADIUS as an intermediary.

Thanks!

**Comment by AdSchellevis** [comment]
close issue?

**Comment by c0nsumer** [comment]
Sorry! Sure, closed.
