### ISSUE TITLE
Unable to set hostname via CLI

### ISSUE THREAD

**Issue by torrycrass** [opnsense/core#4617]
- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I have searched the existing issues and I am convinced that mine is new.

**Is your feature request related to a problem? Please describe.**

- Yes
- Unable to set hostname by CLI and web GUI not easily available results in the hostname not being able to be set.

**Describe the solution you like**

- The ability (or instructions provided) to set the hostname for an OpnSense system via the CLI.

**Describe alternatives you considered**

- None at this time

**Additional context**

- None at this time

**Comment by ddowse** [comment]
>     * The ability (or instructions provided) to set the hostname for an OpnSense system via the CLI.

Just saw this and Ok - this maybe hackish, but it's doable, you can edit `/conf/config.xml` and change `<hostname>OLDHOSTNAME</hostname>` to your new hostname. And then run `/usr/local/etc/rc.reload_all`.

**Comment by AdSchellevis** [comment]
not a priority for core at the moment, closing.
