### ISSUE TITLE
Unbound crash leads to not working IPsec tunnels and Interface problems

### ISSUE THREAD

**Issue by banym** [opnsense/core#4618]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues and I am convinced that mine is new.

**Describe the bug**

The unbound service in version 20.7.7_1 randomly crashes. If the service is not running, the IPsec tunnels configured on that box start to not operate correctly. It is not possible to view the IPsec "Status Overview" Page anymore. 
The unbound service is shown as down. If you start it the services and connections start to work again, the "Status Overview" page whos its content again.
The IPsec tunnels not working are NOT using DDNS. But in the complete configuration there are tunnels using DDNS. 

In some cases after the reboot, only 3 out of more than 15-20 tunnels are shown in the IPsec Status Overview page. The configuration is still there, restarting IPsec service does not help. Rebooting the firewall helps and everything works again. 

**To Reproduce**

Not sure if you can reproduce this without crashing unbound or stop the service

**Expected behavior**

unbound should restart after crash ar at least connections not relaying on ddns should work properly without dns service running.

Software version used and hardware type if relevant, e.g.:

OPNsense 20.7.7_1 (amd64, OpenSSL).
Intel(R) Xeon(R) CPU E3-1220 v6 @ 3.00GHz (4 cores)
Intel NICs

**Comment by fichtner** [comment]
Unbound version from firmware packages page please. Are you on the latest version?

In general servcies are as good as their upstream releases and 1.13.0 is a bit underperforming.


Cheers,
Franco

**Comment by banym** [comment]
Hi Franco,

yes it is unbound | 1.13.0.
This box is on 20.7.7_1. 

Regards,
Dominik

**Comment by fichtner** [comment]
Hi Dominik,

Check for updates... it should pull in 1.13.0_1 which takes care of this. It's up for about two weeks now.


Cheers,
Franco

**Comment by banym** [comment]
Hi Franco,

o.k thanks. Did installe it in this moment, will keep an eye on that box. 

Regards,
Dominik
