### ISSUE TITLE
wrong error message when we have a whitespace in front

### ISSUE THREAD

**Issue by colttt** [opnsense/core#4620]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues and I am convinced that mine is new.

**Describe the bug**

If you assign an IP to an Interface, and you have a white space in front of the IP (typical a copy&paste issue) and then want to assign or add a gateway. it comes the error message:
> The gateway address "172.20.1.50" does not lie within one of the chosen interface's IPv4 subnets.

**To Reproduce**

1. Interfaces and choose one of them
2. add an IP address with a whith space in front
3. add a new gateway

**Expected behavior**
An error message that a not valid character is in the IP field.

**Comment by fichtner** [comment]
If you hit save below you get the correct error. There's not a lot we can do if you change the input and go on an AJAX gateway save request without saving the interface configuration first.

**Comment by kulikov-a** [comment]
@colttt 
I think that an input mask or instant input validation are technically possible (is it really necessary to overload the GUI with such things if it is assumed that not a simple user, but an administrator is working?). but the interface address must in any case be stored in the configuration before the gateway address is checked against this address
