### ISSUE TITLE
Unbound access-control. CIDR /0 can't be selected

### ISSUE THREAD

**Issue by b0ma** [opnsense/core#4627]
https://github.com/opnsense/core/blob/703faa82ffbd4fa30e8ec2a05893d4fba498790e/src/www/services_unbound_acls.php#L290

CIDR /0 can't be selected. This would allow access for all clients.
Otherwise there is no easy way to get access with dynamic IPv6 addresses.

Example for /var/unbound/access_lists.conf

```
access-control: 0.0.0.0/0 allow
access-control: ::0/0 allow
```

**Comment by AdSchellevis** [comment]
https://github.com/opnsense/core/commit/f1f0c3f0790f0c8e1cf495db308e6055b03feb67 should do the trick here.
