### ISSUE TITLE
(cleanup) Add "+ Add" Button at Firewall -> Alias Page 

### ISSUE THREAD

**Issue by Farma12** [opnsense/core#4628]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues and I am convinced that mine is new.

**Describe the bug**
When clicking on Firewall->Groups, Firewall->Rules->LAN, VPN->OpenVPN->Clients, etc., there is always a +Add button on the top right. In Firewall->Aliases this button is missing. Instead there is a small +button at the end of the alias list. 

**To Reproduce**

1. Go to 'Firewall'
2. Click on 'Aliases'

**Expected behavior**
I would expect the +Add Button to be at the same right upper corner as within the other pages.

**Screenshots**
![Alias](https://user-images.githubusercontent.com/11560303/105628146-7097a580-5e3b-11eb-83c3-6686b13d6bc3.png)

**Relevant log files**

no log files

**Additional context**

no additional context

**Environment**

Software version used and hardware type if relevant, e.g.:
OPNsense 20.7.8-amd64
FreeBSD 12.1-RELEASE-p12-HBSD
OpenSSL 1.1.1i 8 Dec 2020

**Comment by AdSchellevis** [comment]
same as https://github.com/opnsense/core/issues/4381 and https://github.com/opnsense/core/issues/4216

**Comment by JeGr** [comment]
> same as #4381 and #4216

Indeed, but #4381 was closed as duplicate (correctly so) and #4216 was already bot-closed (which is not so helpful I suppose?)
So perhaps we could re-open #4216? As the new menu-item "categories" under "firewall" was copied from "aliases" (I guess, as it uses the same icon and the page is also missing the +Add button ;)) I think that would help weeding out those differences. :)

**Comment by AdSchellevis** [comment]
Likely not going to fix anything as long as nobody is planning to do the work, just to be clear, the new format doesn't have big buttons on top, the older pages might have them. Cleaning up means removing the big top buttons. 

Since grid styles are different on these pages as well, it doesn't make much sense only to remove the big buttons now without rebuilding the component into an mvc one (which is quite some work).

**Comment by JeGr** [comment]
I'm all for unification and making the UI consistent! And don't take that the wrong way, but I had quite a few customers where I did remote support and they ALL searched for the big and colorful(!) button on top rather then a tiny little plus that don't stand out the least (no color, no text, nothing) and - on top of that - is on the bottom of the list.

I'd really recommend to add color and/or text to the button and include a top-row in addition to the bottom row as the people just don't find it in a sea of lines with various other similar looking buttons right above it. The big Add button actually was a better idea then I first thought and will be missed for sure!

I'd love to see some color indicators that draw attention to the little [+] guy. Even me knowing it's there have sometimes problem with larger rulesets or tables to find it. And yeah, normally list is capped to 7-10 entries, but in larger rulesets you have to display more if you want to keep track, what the customer has done there ;)

**Comment by fichtner** [comment]
#4216 is open, closing this now.
