### ISSUE TITLE
Unbound: Allow multiple IPs for Host and Domain Overrides.

### ISSUE THREAD

**Issue by Napsterbater** [opnsense/core#4630]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues and I am convinced that mine is new.

**Is your feature request related to a problem? Please describe.**

QOL (Quality of life) Improvement

**Describe the solution you like**

Allow the IP filed in both Host and Domain overrides to accept multiple IPv4 and/or IPv6 addresses.

**Describe alternatives you considered**

Current Alternative is to make repeated entries with repeated and redundant data.

**Additional context**

Seems Domain Overrides, already combines them in the config file, just need the GUI to allow for inputting the data in one field instead of multiple entries.

Example:
```
forward-zone:
	name: "napshome.local"
	forward-addr: 10.0.1.20
	forward-addr: 10.0.1.1
	forward-addr: 10.0.1.2@5353
```

For host overrides, I dont think its needs or even can be combined in a similar manner in the config, but when multiple IPs are configured in the GUI it should be able to "expand" that to as many entries as needed.

**Comment by j0nny55555** [comment]
This would be a great add!! It would seem my config of two IPs each having the same name does the expected, but I do not know how to verify.

Again - I've got a local domain and redudant IPs to resolve that local domain and I would like Unbound to forward to whichever is up/responding of the two or more or less both as I believe it works in DNS.

**Comment by simonmicro** [comment]
:+1: Indeed, I also need that feature for exactly that reason.

**Comment by blodone** [comment]
yes that would be nice according to the round robin (RR) DNS design

**Comment by bernardgut** [comment]
Yes, I don't know why this was closed. Especially nowadays with Cilium.

**Comment by fichtner** [comment]
just open a new ticket, nobody knew in 2011 that in 2024 4 people would comment on this... ;)

**Comment by Meltr0** [comment]
Was a new ticket opened for this? I've been hoping for this for a long time, was looking at having to do some sort of HAProxy configuration on the firewall itself or having to implement VRRP or CARP on Windows. This would be far easier

**Comment by sanitybit** [comment]
@Meltr0 @bernardgut @blodone @simonmicro @j0nny55555 

Please add your support to #7819
