### ISSUE TITLE
bogon exclusion rules

### ISSUE THREAD

**Issue by commandline-be** [opnsense/core#4632]
**Is your feature request related to a problem? Please describe.**

On multiple occassions legitimate address (such as for dhcp) get blocked due to bogon filtering enabled on WAN. 

**Describe the solution you like**

There should be an easy way to edit the bogon list permanently with exceptions.

**Describe alternatives you considered**

stop using opnsense

**Additional context**

bogon filtering is cool to have as a feature, it proves also an unnecessary source of issues

**Comment by fichtner** [comment]
Disable bogon blocking? Add bogon alias yourself? Which addresses are you talking about? This is a thin case and I appreciate more info.

Cheers,
Franco

**Comment by mimugmail** [comment]
For me it better worked out to disable bogon filter and use FireHOL3 list as an url table since it also includes bogons.

**Comment by kulikov-a** [comment]
https://docs.opnsense.org/manual/aliases.html#exclusions

**Comment by IsaacFL** [comment]
> 
> 
> https://docs.opnsense.org/manual/aliases.html#exclusions
I have ran into the same issue.

The issue is that bogons and bogonsv6, while they show as aliases, and can be used in rules. If you try to use the exclusion method discussed in the documentation, these 2 aliases are not in the pick list for a network group. 

Therefore, it is not possible to create a network group alias with the bogons or bogonsv6.

**Comment by IsaacFL** [comment]
> FireHOL3 list

The problem is that the FireHOL lists are ipv4 only.  The bogonsv6 are more in need of exclusions because there are so many that are in the list that have legitimate uses. i.e. 64:ff9b::/96 and ULAs.

**Comment by IsaacFL** [comment]
In General, I find I only need to use the bogon blocking to prevent unroutable bogon traffic from leaving the WAN interface.

What I find that seems to be working for me, is to create an ipv6 rule on the WAN interface that is direction "out", src=!this firewall, dst=bogonsv6.  I always log it.  The ipv4 one is the same, but use source any and bogons.

Now I have just started using opnsense again, and so far haven't seen any issues with it that way as far DHCP, etc.

**Comment by IsaacFL** [comment]
Sorry for train of thought, but while I was looking at the DHCP rules, I noticed that on the "allow DHCP client on WAN", neither the in or out rules have "quick" set, so they are last match.  Couldn't any rule on the WAN block DHCP?  I noticed in my old pfsense, that they use "quick".
from pfsense:
# allow our DHCP client out to the WAN
pass in  quick on $WAN proto udp from any port = 67 to any port = 68 tracker 1000000561 label "allow dhcp client out WAN"
pass out  quick on $WAN proto udp from any port = 68 to any port = 67 tracker 1000000562 label "allow dhcp client out WAN"

**Comment by kulikov-a** [comment]
@IsaacFL 

> while they show as aliases, and can be used in rules
yes, because its "external" aliases. i think you can try to disable bogon filter as @mimugmail said, google for **sense bogons lists (v4 and v6), add this to the new "URL Table (IPs)" Alias and then combine it with exclusions alias

**Comment by commandline-be** [comment]
consider to reopen this issue or document the below behavior

when enabled bogon filtering on LAN, blocks DHCP
when enabled bogon filtering on WAN, does not seem to block DHCP

**Comment by commandline-be** [comment]
Please consdider making a box for [ in | out ] blocking of bogon instead of just blocking on the interface, or set an option to not filter 0.0.0.0 as a bogon.

![image](https://github.com/user-attachments/assets/b00822b2-4b1f-495a-821c-d378a8dd8707)

**Comment by AdSchellevis** [comment]
@commandline-be just create any rule you like using the `bogons[v6]` aliases (as you would do for any other type of traffic), no need for new toggles....

**Comment by IsaacFL** [comment]
> @commandline-be just create any rule you like using the `bogons[v6]` aliases (as you would do for any other type of traffic), no need for new toggles....

This is what I did. Create an alias with Bogons, and !0.0.0.0 for your case.

**Comment by commandline-be** [comment]
trying to get my head around what is suggested here

especially since filtering on bogon with a routable IP does permit udp-dhcp
while bogon filtering with a non-routable IP does not permit udp-dhcp
