### ISSUE TITLE
Firewall Categories: Potential Improvements

### ISSUE THREAD

**Issue by 8191** [opnsense/core#4637]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues and I am convinced that mine is new.

**Is your feature request related to a problem? Please describe.**
When administrating many different firewall rules and categories with many different colours, it's hard to
1. remember the colour-code, and
2. maintain the categories for each rule.

**Describe the solution you like**
1. Display mouse-over text when hoovering over a coloured bullet.
2. Add "(no category)" to the filter box at the top to allow identifying rules without category (this is especially useful when not all categories have colours assigned).

**Describe alternatives you considered**
1. Legend at the bottom - disadvantage is, that it's currently not permanently visible when many rules are displayed.
2. none.

**Additional context**
Feature #4587

**Comment by swhite2** [comment]
See #4775

**Comment by AdSchellevis** [comment]
@swhite2 thanks! (https://github.com/opnsense/core/pull/4790)
