### ISSUE TITLE
Insight: Interface totals (bit/sec) IN graph disappears after setting dropdown to "Last Year, 24 hour average"

### ISSUE THREAD

**Issue by casparcedro** [opnsense/core#4639]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I have searched the existing issues and I am convinced that mine is new.

**Describe the bug**

Interface totals (bit/sec) IN graph disappears after setting dropdown to "Last Year, 24 hour average." The URL path for this page is /ui/diagnostics/networkinsight.

**To Reproduce**

1. Go to 'Reporting -> Insight'
2. Click on dropdown at top right and set it to 'Last Year, 24 hour average'
3. Graph for IN that originally shows data no longer does.

**Expected behavior**

The IN graph should show the data as required

**Screenshots**

Before:
![image](https://user-images.githubusercontent.com/8496424/105771584-c5681880-5f2e-11eb-9c6d-3801910a51f2.png)

After:
![image](https://user-images.githubusercontent.com/8496424/105771181-2b07d500-5f2e-11eb-8870-cbfbba633339.png)

**Relevant log files**
System -> Log Files shows nothing interesting but inspecting the console on firefox yields the following error:

Uncaught TypeError: f[p][g] is undefined
    n https://192.168.1.1:943/ui/js/d3.min.js?v=f13e8636c4101a22:4
    b https://192.168.1.1:943/ui/js/nv.d3.min.js?v=f13e8636c4101a22:10
    each https://192.168.1.1:943/ui/js/d3.min.js?v=f13e8636c4101a22:5
    Y https://192.168.1.1:943/ui/js/d3.min.js?v=f13e8636c4101a22:1
    each https://192.168.1.1:943/ui/js/d3.min.js?v=f13e8636c4101a22:5
    b https://192.168.1.1:943/ui/js/nv.d3.min.js?v=f13e8636c4101a22:10
    call https://192.168.1.1:943/ui/js/d3.min.js?v=f13e8636c4101a22:3
    b https://192.168.1.1:943/ui/js/nv.d3.min.js?v=f13e8636c4101a22:10
    each https://192.168.1.1:943/ui/js/d3.min.js?v=f13e8636c4101a22:3
    Y https://192.168.1.1:943/ui/js/d3.min.js?v=f13e8636c4101a22:1
    each https://192.168.1.1:943/ui/js/d3.min.js?v=f13e8636c4101a22:3
    b https://192.168.1.1:943/ui/js/nv.d3.min.js?v=f13e8636c4101a22:10
    call https://192.168.1.1:943/ui/js/d3.min.js?v=f13e8636c4101a22:3
    chart_interface_totals https://192.168.1.1:943/ui/diagnostics/networkinsight:1501
    c https://192.168.1.1:943/ui/js/nv.d3.min.js?v=f13e8636c4101a22:3
d3.min.js:4:25998
    n https://192.168.1.1:943/ui/js/d3.min.js?v=f13e8636c4101a22:4
    b https://192.168.1.1:943/ui/js/nv.d3.min.js?v=f13e8636c4101a22:10
    each https://192.168.1.1:943/ui/js/d3.min.js?v=f13e8636c4101a22:5
    Y https://192.168.1.1:943/ui/js/d3.min.js?v=f13e8636c4101a22:1
    each https://192.168.1.1:943/ui/js/d3.min.js?v=f13e8636c4101a22:5
    b https://192.168.1.1:943/ui/js/nv.d3.min.js?v=f13e8636c4101a22:10
    call https://192.168.1.1:943/ui/js/d3.min.js?v=f13e8636c4101a22:3
    b https://192.168.1.1:943/ui/js/nv.d3.min.js?v=f13e8636c4101a22:10
    each https://192.168.1.1:943/ui/js/d3.min.js?v=f13e8636c4101a22:3
    Y https://192.168.1.1:943/ui/js/d3.min.js?v=f13e8636c4101a22:1
    each https://192.168.1.1:943/ui/js/d3.min.js?v=f13e8636c4101a22:3
    b https://192.168.1.1:943/ui/js/nv.d3.min.js?v=f13e8636c4101a22:10
    call https://192.168.1.1:943/ui/js/d3.min.js?v=f13e8636c4101a22:3
    chart_interface_totals https://192.168.1.1:943/ui/diagnostics/networkinsight:1501
    c https://192.168.1.1:943/ui/js/nv.d3.min.js?v=f13e8636c4101a22:3

**Additional context**

No other context.

**Environment**

Software version used and hardware type:
OPNsense 20.7.8-amd64
FreeBSD 12.1-RELEASE-p12-HBSD
LibreSSL 3.2.3
AMD GX-420CA SOC with Radeon(tm) HD Graphics (4 cores)
Network 4 port 1 gigabit card

**Comment by AdSchellevis** [comment]
probably a bug in the nvd3 library, but not very consistent behaviour (I can't reproduce it reliably on my end). Unfortunately the lib doesn't seem to be under active development anymore https://github.com/novus/nvd3

**Comment by casparcedro** [comment]
Same issue with the latest update:
OPNsense 21.1-amd64
FreeBSD 12.1-RELEASE-p12-HBSD
LibreSSL 3.2.3

Have you tried to reproduce the issue with more data? I have the same issue with traffic over a few gigabytes to a terabyte.

**Comment by AdSchellevis** [comment]
Eventually we might consider switching to chart.js, but to be honest, I haven't seen really great libraries which are well maintained and feature rich at the same time, spend way too much time debugging all sorts of JS issues on components that seemed to have lost traction somewhere along the way in the last couple of years.

At the end of the day, someone needs to put a lot of time in this to either find the issue (which isn't very reproducible) or rewrite quite some code to plug something else in and hope that it vanishes. 

We added chart.js in 21.1, we will probably replace nvd3 where possible, not solid plans yet.
