### ISSUE TITLE
Editing gateways automatically generated from GRE tunnels result in a "name too long" error

### ISSUE THREAD

**Issue by WRMSRwasTaken** [opnsense/core#4643]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues and I am convinced that mine is new.

**Describe the bug**

We have set up 4 GRE tunnels (xxxxx being adequate length replacement):
- xxxxx_hrs_gre_trans0_test
- xxxxx_hrs_gre_trans1_test
- xxxxx_hrs_gre_trans0_prod
- xxxxx_hrs_gre_trans1_prod

This will result in 4 (single) gateways automatically created:
- XXXXX_HRS_GRE_TRANS1_PROD_TUNNELV4 
- XXXXX_HRS_GRE_TRANS0_PROD_TUNNELV4 
- XXXXX_HRS_GRE_TRANS1_TEST_TUNNELV4 
- XXXXX_HRS_GRE_TRANS0_TEST_TUNNELV4

Because of the topic in https://github.com/opnsense/core/issues/3966, those gateways will be candidates for default upstream selection. To avoid this, I wanted to force those (automatically generated) gateways to down state, which will result in an error: `The name must be less than 32 characters long and may only consist of the following characters: a-z, A-Z, 0-9, _`

I can't verify though if forcing an autogenerated, marked as down gateway will survive a reboot or if it will be marked as up again after a reboot.

**To Reproduce**

1. Create a GRE tunnel with the name set to `xxxxx_hrs_gre_trans0_test`
2. Maybe reboot?
3. Edit the newly created gateway being named `XXXXX_HRS_GRE_TRANS1_PROD_TUNNELV4`, tick the `Mark Gateway as Down` box w/o editing anything other

**Expected behavior**

The gateway should be marked as down *and* the marked down state should survive a reboot

**Screenshots**

N/A

**Relevant log files**

N/A

**Additional context**

N/A

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 20.7.6-amd64
FreeBSD 12.1-RELEASE-p11-HBSD
OpenSSL 1.1.1h 22 Sep 2020
Intel X520-DA2 NICs

**Comment by WRMSRwasTaken** [comment]
One solution could be not displaying the text area to change the name at all since it is autogenerated.

**Comment by fichtner** [comment]
FWIW, the page isn't very clever about it and add/edit share the same code so it thinks it's being tricked... I'll take it.
