### ISSUE TITLE
Transition of metadata from live log to new firewall rules form

### ISSUE THREAD

**Issue by doschn** [opnsense/core#4644]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [ x ] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [ x ] I have searched the existing issues and I am convinced that mine is new.

**Is your feature request related to a problem? Please describe.**
no - this feature request is not related to any problem. 

A clear and concise description of what the problem is including your motivation for the request,
I'd like to request a feature which speeds up the creation of firewall rules for blocked traffic from the live view of the Firewall Logs (/ui/diagnostics/firewall/log). 

**Describe the solution you like**

I would like request a button at the bottom of the "Detailed rule info" window, next to the inspect and close buttons within the firewall live logs, which transfers the following or selected logged information of the inspected event into the form for creating new firewall rules. 
- dir
- dst
- dstport
- interface
- protocol
- src
- version

(e.g. I would like an input field in the `/ui/firewall/alias` which would add .... to ....)
see above
**Describe alternatives you considered**
- not appliccable - 

**Additional context**
During the Implementation of new OPNsense instances at customer sites or when implementing new applications at existing sites the creation of a large number the firewall rules is required. To speed up this process an transition of metadata of blocked traffic, recorded within the logs, into new firewall rules would be great. 

Add any other context or screenshots about the feature request here or links to relevant forum thread or similar
![Req](https://user-images.githubusercontent.com/78094711/106020114-b2d31800-60c3-11eb-9dfb-13f808c65180.png)

**Comment by LensHunnel** [comment]
Any news on that issue ?
