### ISSUE TITLE
dnsmasq: need the --address= overrides settings before deprecating custom options

### ISSUE THREAD

**Issue by johnnyslee** [opnsense/core#4645]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I have searched the existing issues and I am convinced that mine is new.

**Is your feature request related to a problem? Please describe.**

Currently, with just two lines of dnsmasq custom options:
```
address=/netflix.com/netflix.net/nflxvideo.net/nflximg.net/nflxext.com/nflxso.net/::
server=/netflix.com/netflix.net/nflxvideo.net/nflximg.net/nflxext.com/nflxso.net/#
```
I can easily make those domains, and their subdomains, to be resolved to ipv4 addresses only.
But **Dnsmasq DNS: Deprecate custom options**, which is listed on the roadmap of the upcoming version of OPNsense, will make this setup much much harder, because the *Host Overrides* settings make use of a hosts file which does not support wildcard domain.

**Describe the solution you like**

Just like the *Domain Overrides* settings turning entries into multiple `--server=` options, a *Wildcard Host Overrides* settings which turn entries into multiple `--address=` options would do the job.

**Describe alternatives you considered**

Do not deprecate custom options if possible.

**Additional context**

Reason I need to filter out netflix's ipv6 addresses: https://gist.github.com/jamesmacwhite/6a642cb6bad00c5cefa91ec3d742e2a6

**Comment by AdSchellevis** [comment]
not yet published to docs.opnsense.org, but custom options can be provided using the instructions in https://github.com/opnsense/docs/blob/master/source/manual/dnsmasq.rst
