### ISSUE TITLE
Watchdog Based on Monit

### ISSUE THREAD

**Issue by 8191** [opnsense/core#4646]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues and I am convinced that mine is new.

**Is your feature request related to a problem? Please describe.**

Facing #4563 on several instance, I configured monit to automatically restart unbound if not running. So I had the idea what about having this as a feature, to automatically configure monit for all services which are enabled.

**Describe the solution you like**

Whenever one enables a service (unbound, dnsmasq, OpenVPN, proxy, etc.) a monit service is created with a _start program_ command targeting `configctl <service> start`.

**Describe alternatives you considered**

A proper watchdog deamon could be added to OPNsense, but I think monit should do as well.

**Comment by AdSchellevis** [comment]
I think Monit itself is perfectly capable of serving as a watchdog, only challenge is how to integrate it into the existing structure. Personally I rather would have seen an implementation where one could select a list of options to test and associated actions, but unfortunately the current more or less free form input skipped through my attention.

We could consider adding a type in the service area using a well defined structure of commands underneath, maybe deprecate the custom type in the long run.
