### ISSUE TITLE
Widget for Interface totals

### ISSUE THREAD

**Issue by psychogun** [opnsense/core#4647]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues and I am convinced that mine is new.

**Is your feature request related to a problem? Please describe.**

Logging in to different firewalls and using the Dashboard to have a quick glance of the status on different sites; temperature, load, gateways etc., I would prefer that I also could view a **historical** Traffic graph, not the real time which is now provided by `Traffic Graph`.

**Describe the solution you like**

I would really like the to have the option to select a widget on the Dashboard showing traffic which is more like the one you get from Reporting > Insight > Totals. 

**Describe alternatives you considered**

Alternatively, I would perhaps look into doing a Grafana dashboard and start using this for my quick overviews. Or Zabbix. 

https://github.com/b4b857f6ee/opnsense_grafana_dashboard
https://github.com/VictorRobellini/pfSense-Dashboard
 

**Additional context**

https://forum.opnsense.org/index.php?topic=20896.0

**Comment by AdSchellevis** [comment]
We should replace it with chart.js, nothing more, nothing less. I'll put it on the list.

**Comment by AdSchellevis** [comment]
(historical data is provided using Network Insights and system health)

**Comment by AdSchellevis** [comment]
Misread the ticket the first time, adding a widget for the netflow data can probably be implemented in a similar way as I just did for the traffic graph widget  in case anyone is looking for some inspiration (https://github.com/opnsense/core/commit/c3ca1f61b3e70f319d0ca3c75bc881aa4d6a3f6a)
