### ISSUE TITLE
Firewall Logs Widget - repeats the same log entries multiple times

### ISSUE THREAD

**Issue by thowe-switzerland** [opnsense/core#4648]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues and I am convinced that mine is new.

**Describe the bug**

The "Firewall Logs" Widget shows entries multiple times if there are only a few entries in the log file.

If e.g. the filter.log is containing only two entries and you are opening the dashboard page, initially there are only two entries shown. But every second these two entries are added again and again until the maximum of entries in the widget is reached.

Not sure with which version this behavior started. Noticed it with version OPNsense 20.7.8-amd64 for the first time.

**To Reproduce**

1. Make sure you have a small number of entries in the firewall log (e.g. 1 or 2)
2. Click on Dashboard
3. Make sure you have the Firewall Logs Widget installed
4. Check that every second (probably with every update of the content of the list), the entries in the list get added to the entries already shown in the widget until the maximum of entries to be shown is reached

**Expected behavior**

Only the last n entries should be listed in the widget. Every item should be shown at most once.

**Describe alternatives you considered**

Delete Firewall Logs Widget and re-adding it did not help.

**Screenshots**

The firewall log with one entry:
![image](https://user-images.githubusercontent.com/2715436/106203218-57845100-61bb-11eb-9f28-016c7e421681.png)

Firewall Logs Widget after 5 seconds on the Dashboard:
![image](https://user-images.githubusercontent.com/2715436/106203650-09bc1880-61bc-11eb-9f58-3cfd2bc46647.png)

**Relevant log files**
[filter.log](https://github.com/opnsense/core/files/5890179/filter.log)

**Additional context**

Firewall has been in use for several years. Followed nearly every update.

**Environment**

OPNsense 20.7.8-amd64
FreeBSD 12.1-RELEASE-p12-HBSD
OpenSSL 1.1.1i 8 Dec 2020
AMD GX-412TC SOC (4 cores) (APU2E4)
Network Intel® I210-AT

**Comment by thowe-switzerland** [comment]
Addendum: After the update to 21.1 (which went smooth!), the error in the Widget also shows up (at least in my context).

Current system after the update (also affected):
OPNsense 21.1-amd64
FreeBSD 12.1-RELEASE-p12-HBSD

**Comment by fichtner** [comment]
Sali @thowe-switzerland,

Can you try this patch to confirm?

    # opnsense-patch 5bfd6b66

Fixed also the maximum display being off by one and save button position.


Cheers,
Franco

**Comment by thowe-switzerland** [comment]
Sälüt Franco :-)

Thanks for the quick patch. There still seems to be a problem: Now the one entry in the log file is first shown once, a second later twice. What changed is, that it does no longer "fill up" to the maximum.

After patching but before restart, the following error was  shown in GUI:
`[01-Feb-2021 11:11:13 Europe/Zurich] PHP Warning:  in_array() expects parameter 2 to be array, string given in /usr/local/www/firewall_rules_edit.php on line 1222
`

What I have done:
- applied the patch
- Forced reload of GUI in the browser --> one entry shown twice + error message
- restart firewall
- Reload GUI in the browser --> one entry shown twice + no error message

**Comment by fichtner** [comment]
PHP warning is from firewall categories rework, patches are 25573505db and 1ed095bc878

Can you confirm that the entry is duplicated?

    # clog /var/log/filter.log

**Comment by fichtner** [comment]
Looks good on my end: 11 entries in log and dashboard with limit set higher or equal to entry count ... no flapping of entries and truncating to e.g. 5 now also works correctly, but you never know with these JS things... :)

**Comment by thowe-switzerland** [comment]
Strange. But yes. IT is not always deterministic... ;-)

I am sorry to say, that my situation is as follows (Note: in the meantime I am on 21.1):

![image](https://user-images.githubusercontent.com/2715436/106449822-ae707b80-6484-11eb-874c-ad3d6c26a14d.png)

![image](https://user-images.githubusercontent.com/2715436/106449463-4ae64e00-6484-11eb-94d0-25d193cd1cab.png)

**Comment by fichtner** [comment]
Odd, which parameters do you use in the widget?

**Comment by thowe-switzerland** [comment]
These are the parameters of my widget:
![image](https://user-images.githubusercontent.com/2715436/106463731-141a3300-6498-11eb-8e90-701ff18e495c.png)

**Comment by fichtner** [comment]
No other reports so I think unless need data points are added we can't do more.
