### ISSUE TITLE
Diagnostics: ARP Table make it sortable

### ISSUE THREAD

**Issue by fichtner** [opnsense/core#465]
bootgrid in MVC already support this, so all we need to do is move the ARP table there

via: https://forum.opnsense.org/index.php?topic=1669.0

**Comment by AdSchellevis** [comment]
For an example, look at https://<ip>/ui/captiveportal/voucher/ the bootgrid plugin delivers sorting out of the box :)

**Comment by fichtner** [comment]
Indeed, this sort of closes itself once we do the proper migration. Cool. :)

**Comment by fichtner** [comment]
Already done by the great @AdSchellevis
