### ISSUE TITLE
ipfw delay parameter is set out of order

### ISSUE THREAD

**Issue by tswalker** [opnsense/core#4650]
**Important notices**
- [X ] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X ] I have searched the existing issues and I am convinced that mine is new.

**Bug Description**
Delay parameter is not respected by ipfw in the order it is set within the ipfw.rules configuration file.  It needs to be set immediately after the "config" switch to be accepted otherwise an "Invalid" parameter error occurs.

**To Reproduce**

1. Go to:  Firewall > Shaper > Pipes
2. Click on:  any pipe to be edited
3. Scroll down to:  Delay
4. add any value for ms delay settings to be applied to the pipe

**Expected behavior**

Setting the delay property for pipes for ipfw via the web GUI should apply given parameter to the pipe via the ipfw configurator.

**Describe alternatives you considered**
using SSH and man handling it via CLI

**Additional context**

NOTE: adjusting the parameter order does allow the application of the delay property "if" delay is set immediately following the "config" switch.

example:
ipfw pipe 10000 config delay 100 bw 15Mbit/s type  fq_codel ecn quantum 300

**Environment**
OPNsense 21.1-amd64
HWProbe: https://bsd-hardware.info/?probe=563c0c9894

**Comment by tswalker** [comment]
Also please note, that if I adjust the rules or queues and hit "apply", the ipfw.rules file overrides any changes made in the command line.  However, if 'after' applying any shaper changes, and I edit the ipfw.rules file to adjust the delay to follow "config", then click "reset" the settings are appropriately applied.

However, clicking "apply" at any point incorrectly re-writes the delay parameter order, and i have to again set it via CLI...  lol

minor issue probably, but I do not know how to make a PR and see if i can fix it somehow.

**Comment by AdSchellevis** [comment]
it's not intended to be manually edited, I can't reproduce issues with ordering (it parses and seems to apply properly).

Can you check the contents of the pipe? mine shows the following with 200ms.
```
# ipfw pipe 10008 show
10008:   9.999 Mbit/s  200 ms burst 0 
q141080  50 sl. 0 flows (1 buckets) sched 75544 weight 0 lmax 0 pri 0 droptail
 sched 75544 type FIFO flags 0x0 0 buckets 0 active
```

**Comment by razblack** [comment]
here is the configuration in gui:
![pipe_10008](https://user-images.githubusercontent.com/18149815/106367168-50b62500-6306-11eb-89ba-10604a6e6444.png)


cli after hitting "apply" from gui:

root@OPNsense:~ # ipfw sched 10008 show
10008:   2.750 Mbit/s    0 ms burst 0
q75544  50 sl. 0 flows (1 buckets) sched 10008 weight 0 lmax 0 pri 0 droptail
 sched 10008 type FQ_CODEL flags 0x1 256 buckets 2 active
 FQ_CODEL target 5ms interval 100ms quantum 300 limit 10240 flows 1024 NoECN
    mask:  0x00 0x00000000/0x0000 -> 0xffffffff/0x0000
   Children flowsets: 10009 10008 10007 10006 10004
BKT Prot ___Source IP/port____ ____Dest. IP/port____ Tot_pkt/bytes Pkt/Byte Drp
163 ip           0.0.0.0/0          10.0.0.163/0      747  1030014  1 1420   0
165 ip           0.0.0.0/0          10.0.0.165/0        1       80  0    0   0

root@OPNsense:~ # ipfw pipe 10008 show
10008:   2.750 Mbit/s    0 ms burst 0
q75544  50 sl. 0 flows (1 buckets) sched 10008 weight 0 lmax 0 pri 0 droptail
 sched 75544 type FIFO flags 0x1 256 buckets 0 active
    mask:  0x00 0x00000000/0x0000 -> 0xffffffff/0x0000


ipfw.rules:
#=============================================================================
define dummynet pipes
#=============================================================================
pipe 10008 config bw 2750Kbit/s mask dst-ip 0xffffffff  type  fq_codel  delay 100  noecn    quantum 300

cli with change of parameter order:
`root@OPNsense:/usr/local/etc # ipfw pipe 10008 config delay 100 bw 2750Kbit/s mask dst-ip 0xffffffff  type  fq_codel  noecn    quantum 300`

root@OPNsense:/usr/local/etc # ipfw sched 10008 show
10008:   2.750 Mbit/s  100 ms burst 0
q75544  50 sl. 0 flows (1 buckets) sched 10008 weight 0 lmax 0 pri 0 droptail
 sched 10008 type FQ_CODEL flags 0x1 256 buckets 2 active
 FQ_CODEL target 5ms interval 100ms quantum 300 limit 10240 flows 1024 NoECN
    mask:  0x00 0x00000000/0x0000 -> 0xffffffff/0x0000
   Children flowsets: 10009 10008 10007 10006 10004
BKT Prot ___Source IP/port____ ____Dest. IP/port____ Tot_pkt/bytes Pkt/Byte Drp
162 ip           0.0.0.0/0          10.0.0.162/0        1       79  0    0   0
163 ip           0.0.0.0/0          10.0.0.163/0     1749  2423079  0    0   3

root@OPNsense:/usr/local/etc # ipfw pipe 10008 show
10008:   2.750 Mbit/s  100 ms burst 0
q75544  50 sl. 0 flows (1 buckets) sched 10008 weight 0 lmax 0 pri 0 droptail
 sched 75544 type FIFO flags 0x1 256 buckets 0 active
    mask:  0x00 0x00000000/0x0000 -> 0xffffffff/0x0000
root@OPNsense:/usr/local/etc #



Seems for whatever reason, delay is not sticking in ipfw.rules from gui 'apply'.

(note: some of the other parameters are sticky cause i haven't rebooted yet like limit and flows)

**Comment by AdSchellevis** [comment]
at a first glance it looks like codel is in the wrong spot, I'll try to take a look tomorrow.

**Comment by AdSchellevis** [comment]
@razblack https://github.com/opnsense/core/commit/ff547eba3716c1e3e4ca4a14b2ef421be1c39e2c should do the trick, if not, feel free to reopen.

**Comment by razblack** [comment]
pulled, tested.. fixed!  
@AdSchellevis thank you

**Comment by AdSchellevis** [comment]
@razblack thanks for letting us know, we'll try to schedule the patch for our next release.

**Comment by fichtner** [comment]
Done 26 minutes ago :D
