### ISSUE TITLE
bug: PHP Warning:  implode(): Invalid arguments passed in /usr/local/www/firewall_nat_edit.php

### ISSUE THREAD

**Issue by johnthegreat** [opnsense/core#4655]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues and I am convinced that mine is new.

**Describe the bug**

A clear and concise description of what the bug is, including last known working version (if any).

When there are no Firewall Categories*, then creating or editing a NAT Port Forward rule, then going back to the Dashboard, I see this: "A problem was detected. Click here for more information." After clicking, it takes me to the `System: Firmware: Reporter` tool (`crash_reporter.php`) and it has the following under `PHP Errors:`:

```
PHP Warning:  implode(): Invalid arguments passed in /usr/local/www/firewall_nat_edit.php on line 216
```

\* Tested on a fresh install and skipped setup wizard. I did not test the case if a firewall category is added then deleted.

The Git Blame shows this functionality is extremely new, this leads me to believe this issue _only applies to the latest 21.1 release_:
https://github.com/opnsense/core/blame/5008929159fd62f7962956bafbec9030f62c69f9/src/www/firewall_nat_edit.php#L216

I am a PHP developer and this would be a simple code fix (Per the [PHP implode docs](https://www.php.net/manual/en/function.implode), the second parameter should be an array.). It could be fixed in a few ways, see below (haven't tested yet). I am happy to create a PR if needed. 

```
// PHP 5.4+ Syntax
$natent['category'] = is_array($pconfig['category']) ? implode(",",$pconfig['category']) : [];
```

```
// PHP 7+ Syntax
// Only works if $pconfig['category'] is null
$natent['category'] = implode(",",$pconfig['category'] ?? []);
```

**To Reproduce**

1. Ensure that you have no firewall categories (`Firewall` > `Categories`).
2. Click on `Firewall` > `NAT` > `Port Forward` (`firewall_nat_edit.php`)
3. Add a new Port Forward rule. Set Interface, Destination, Destination port range, Redirect target IP; the actual values shouldn't matter. Save the new rule.
4. Return to `Lobby` > `Dashboard` (`index.php`)
5. Ensure that you see `A problem was detected. Click here for more information.`. Click on the 'here' link. You should be taken to the `System: Firmware: Reporter` page (`crash_reporter.php`)
6. You should see `PHP Warning:  implode(): Invalid arguments passed in /usr/local/www/firewall_nat_edit.php on line 216` under the `PHP Errors:` section of the page.

**Expected behavior**

I would expect to not see 'A problem was detected. Click here for more information' every time I create or edit a NAT Port Forward rule.

**Describe alternatives you considered**

N/A

**Screenshots**

![image](https://user-images.githubusercontent.com/4603616/106395842-a6033c80-63c1-11eb-815a-30abea5b491c.png)

![image](https://user-images.githubusercontent.com/4603616/106395760-3a20d400-63c1-11eb-9bcd-ee11a1cfc69c.png)

**Relevant log files**

N/A

**Additional context**

I was able to produce numerous times on both bare-metal and virtual machines.
I have also verified that this has not been updated in the [latest master](https://github.com/opnsense/core/blame/master/src/www/firewall_nat_edit.php#L216).

**Environment**

Software version used and hardware type if relevant, e.g.:

```
FreeBSD 12.1-RELEASE-p12-HBSD #0  3c6040c7243(stable/21.1)-dirty: Mon Jan 25 12:27:52 CET 2021     root@sensey:/usr/obj/usr/src/amd64.amd64/sys/SMP amd64
OPNsense 21.1 500892915
Plugins os-dyndns-1.23 
Time Sun, 31 Jan 2021 12:33:22 +0000
OpenSSL 1.1.1i  8 Dec 2020
PHP 7.3.26
```

**Comment by AdSchellevis** [comment]
https://github.com/opnsense/core/commit/34698ef09c781919aa151ed72a31804d7a0d9819 checks for existence,I really expected the empty arrays to be returned on POST, apparently their not there. thanks for reporting!
