### ISSUE TITLE
Feature Request: LDAP: Automatically scheduled re-import

### ISSUE THREAD

**Issue by felixdivo** [opnsense/core#4660]
**Is your feature request related to a problem? Please describe.**

We have an LDAP server and want to grant access to the frontend GUI via that. When we change users (that is, if we add new ones or delete old ones/remove some admin group membership) we want the access to OPNsene to be automatically updated. Besides convenience, this is also a security feature: One cannot forget to retract access.

**Describe the solution you'd like**

The [docs](https://docs.opnsense.org/manual/how-tos/user-ldap.html) say:
> When using LDAP for the GUI the privileges have to be defined with the local user manager, to do so an import of the users from the LDAP source is required.

We would value if this step is not required. Could this restriction be lifted, e.g. by allowing for a automatically scheduled re-import from LDAP every X hours/upon a new login attempt? This may be optional.

**Describe alternatives you've considered**
Manual re-imports work, but are tedious and typically something you want to avoid by using LDAP.

**Additional context**

I didn't quite understand where LDAP is implemented and thus did not put it into the title as requested. I think it's either `www/web-proxy-sso/` or `net/freeradius/`.

**Comment by AdSchellevis** [comment]
basically this https://github.com/opnsense/core/blob/9679471d906631fe5f55efdda5b1174734278622/src/opnsense/mvc/app/library/OPNsense/Auth/LDAP.php#L499-L500

although not very high on our list of things todo at the moment (more or less a feature for larger instances, might also be a candidate for the Business Edition in the future or a sponsored contribution).

**Comment by felixdivo** [comment]
Sounds right. Or simply periodically triggering the "Import users with LDAP" from the GUI (at `System > Access > Users`) for members of some group.

However, "removal if not present in LDAP" would still lack in both cases.

**Comment by CodyChell** [comment]
I've also found that this would be a nice feature to add. I am managing over 40 opnsense firewalls in our environment and it's time consuming to say the least whenever I would have to onboard a new user to have access to all the gui options. 

On top of having the manually import users, there should be a way to put someone in an automatic AD group that gives them X amount of access. AD Groups work great after their imported, but imagine having to import the users having 10-20 users to have access to the gui and then have to do that 40-50 times. All users imported seem to have automatically no group, something I am missing here?

Also another somewhat frustrating is that the LDAP username is case sensitive. If I type in my user name with out the capitals, it'll cause me to get a page that says I don't have any pages assigned to my user. Obviously works when I use the correct username with all the correct letters that are capitalized.

**Comment by ciroiriarte** [comment]
> Also another somewhat frustrating is that the LDAP username is case sensitive. If I type in my user name with out the capitals, it'll cause me to get a page that says I don't have any pages assigned to my user. Obviously works when I use the correct username with all the correct letters that are capitalized.

An optional parameter would help it, "screw case" which when set makes NEWDN=strtolower(actualDN) and stores NEWDN instead of actualDN.

**Comment by AdSchellevis** [comment]
> Also another somewhat frustrating is that the LDAP username is case sensitive. If I type in my user name with out the capitals, it'll cause me to get a page that says I don't have any pages assigned to my user. Obviously works when I use the correct username with all the correct letters that are capitalized.
>>An optional parameter would help it, "screw case" which when set makes NEWDN=strtolower(actualDN) and stores NEWDN instead of actualDN.

euh this? --> https://docs.opnsense.org/releases/CE_21.1.html#january-28-2021 
(system: allow case-insensitive matching for LDAP user authentication)
![image](https://user-images.githubusercontent.com/9783985/126949632-02c60c8d-2cef-4c67-b3ed-cd4873fd0eea.png)

**Comment by ciroiriarte** [comment]
Oh, already fixed!. My comment arrived late, and checking the dates, the report too.

My apologies.
