### ISSUE TITLE
Add Alias does not work, javascript error string.replaceAll is not a function

### ISSUE THREAD

**Issue by gunnicom** [opnsense/core#4661]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues and I am convinced that mine is new.

Slicking on the "+" symbol on Firewall -> Aliases does not work.Javascript console shows:
uncaught Typeerror
string.replaceAll is not a function

Relatively fresh installation. Did installed version 20.7 4 days ago, then updated as 21.1 came out. Did not configure much before updating.

1. Go to 'Firewall -> Aliases'
2. Click on "+" symbol in last row of aliases
3. See error

**Expected behavior**
Aliases should be added.

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 21.1 (amd64, OpenSSL).
ESX VM on ESX 6.7

**Comment by fichtner** [comment]
A bit late to the party ;)

https://github.com/opnsense/core/issues/4654

**Comment by gunnicom** [comment]
Sorry for duplicat. Did not see the other.

**Comment by fichtner** [comment]
Does the patch work for you?

**Comment by gunnicom** [comment]
@fichtner  Just tested it, and it seems to work.

**Comment by fichtner** [comment]
Thanks, then I'll queue this up for 21.1.1 👍
