### ISSUE TITLE
Slow API response on 'api/diagnostics/interface/getArp'

### ISSUE THREAD

**Issue by divanikus** [opnsense/core#4666]
**Describe the bug**

After updating to 21.1 API requests for ARP tables became very slow to respond. This, for example, breaks `pyopnsense` library, because response isn't fulfilled within DEFAULT_TIMEOUT of 5 seconds.

**To Reproduce**

```
 curl --trace-time -k -v -u 'xxx:xxx' 'https://192.168.0.50/api/diagnostics/interface/getArp'
15:10:17.828000 *   Trying 192.168.0.50...
15:10:17.843000 * TCP_NODELAY set
15:10:17.859000 * Connected to 192.168.0.50 (192.168.0.50) port 443 (#0)
15:10:17.859000 * schannel: SSL/TLS connection with 192.168.0.50 port 443 (step 1/3)
15:10:17.859000 * schannel: disabled server certificate revocation checks
15:10:17.875000 * schannel: verifyhost setting prevents Schannel from comparing the supplied target name with the subject names in server certificates.
15:10:17.875000 * schannel: using IP address, SNI is not supported by OS.
15:10:17.875000 * schannel: sending initial handshake data: sending 153 bytes...
15:10:17.875000 * schannel: sent initial handshake data: sent 153 bytes
15:10:17.890000 * schannel: SSL/TLS connection with 192.168.0.50 port 443 (step 2/3)
15:10:17.890000 * schannel: failed to receive handshake, need more data
15:10:17.937000 * schannel: SSL/TLS connection with 192.168.0.50 port 443 (step 2/3)
15:10:17.937000 * schannel: encrypted data got 2287
15:10:17.937000 * schannel: encrypted data buffer: offset 2287 length 4096
15:10:17.953000 * schannel: sending next handshake data: sending 93 bytes...
15:10:17.953000 * schannel: SSL/TLS connection with 192.168.0.50 port 443 (step 2/3)
15:10:17.953000 * schannel: encrypted data got 242
15:10:17.953000 * schannel: encrypted data buffer: offset 242 length 4096
15:10:17.968000 * schannel: SSL/TLS handshake complete
15:10:17.968000 * schannel: SSL/TLS connection with 192.168.0.50 port 443 (step 3/3)
15:10:17.968000 * schannel: stored credential handle in session cache
15:10:17.968000 * Server auth using Basic with user 'xxx'
15:10:17.984000 > GET /api/diagnostics/interface/getArp HTTP/1.1
15:10:17.984000 > Host: 192.168.0.50
15:10:17.984000 > Authorization: Basic xxxxxx
15:10:17.984000 > User-Agent: curl/7.55.1
15:10:17.984000 > Accept: */*
15:10:17.984000 >
15:10:30.156000 * schannel: client wants to read 102400 bytes
15:10:30.156000 * schannel: encdata_buffer resized 103424
15:10:30.171000 * schannel: encrypted data buffer: offset 0 length 103424
15:10:30.171000 * schannel: encrypted data got 8173
15:10:30.171000 * schannel: encrypted data buffer: offset 8173 length 103424
15:10:30.171000 * schannel: decrypted data length: 8144
15:10:30.171000 * schannel: decrypted data added: 8144
15:10:30.171000 * schannel: decrypted data cached: offset 8144 length 102400
15:10:30.171000 * schannel: encrypted data buffer: offset 0 length 103424
15:10:30.187000 * schannel: decrypted data buffer: offset 8144 length 102400
15:10:30.187000 * schannel: schannel_recv cleanup
15:10:30.187000 * schannel: decrypted data returned 8144
15:10:30.187000 * schannel: decrypted data buffer: offset 0 length 102400
15:10:30.187000 < HTTP/1.1 200 OK
15:10:30.187000 < Content-Type: application/json; charset=UTF-8
15:10:30.203000 < Expires: Fri, 05 Feb 2021 14:10:29 GMT
15:10:30.203000 < Cache-Control: max-age=180000
15:10:30.203000 < Content-Length: 7930
15:10:30.203000 < Date: Wed, 03 Feb 2021 12:10:29 GMT
15:10:30.203000 < Server: OPNsense
15:10:30.203000 <
[{"mac":"58:2d:34:00:cb:a6","ip":"192.168.0.40","intf":"bridge0","expired":false,"expires":588,"permanent":false,"type":"bridge","manufacturer":"Qingping Electronics (Suzhou) Co., Ltd","hostname":"","intf_description":"LAN"}...]
```

Some of the output is redacted.

**Expected behavior**

Previous version 20.7 responded within 5 second interval.

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 21.1 (amd64, OpenSSL).
Intel(R) Celeron(R) CPU J3160 @ 1.60GHz (4 cores)

**Comment by xorbital** [comment]
Affected as well after the upgrade, the consequence of pyopnsense breaking is that the Home Assistant Integration for device / presence tracking stops working too.
To be clear - this is affecting the GUI as well, the table takes a very long time to load :thinking: 
I guess if this is the result of a necessary change to the underlying code which can't be sped up we could pass this along to the downstream projects for them to increase the timeouts and grace periods for requests.
Still hope that this isn't intentional though.

**Comment by AdSchellevis** [comment]
looks like an upstream issue in `py-netaddr` after upgrading to 0.8.0, `oui.registration` lookups are probably slower in the new version, since the lookup itself isn't really rocket science,  I temporary wrote an alternative version using their mac database which is part of the library. can you try https://github.com/opnsense/core/commit/dd2231ee54bfc414291f4e1d362e453eea29013c?
 
From the console, patch using:
```
opnsense-patch dd2231e
```

**Comment by xorbital** [comment]
> looks like an upstream issue in `py-netaddr` after upgrading to 0.8.0, `oui.registration` lookups are probably slower in the new version, since the lookup itself isn't really rocket science, I temporary wrote an alternative version using their mac database which is part of the library. can you try [dd2231e](https://github.com/opnsense/core/commit/dd2231ee54bfc414291f4e1d362e453eea29013c)?
> 
> From the console, patch using:
> 
> ```
> opnsense-patch dd2231e
> ```

Applied the patch, the table loads quickly again in the UI, currently testing with Home Assistant :+1:

**Comment by AdSchellevis** [comment]
I'll ask @fichtner if we can stuff this in 21.1.2, it's not a very huge change on our end, if we're already to far in the release process it will likely make it into 21.1.3

**Comment by xorbital** [comment]
Lovely! The Home Assistant / pyopnsense integration seems to be working fine again.
Thank you very much! :smile:

**Comment by Tw1sted-Turtle** [comment]
I'm having this same issue and when I try using the patch above I get the following:
```
Fetched dd2231e via https://github.com/opnsense/core
2 out of 2 hunks failed while patching opnsense/scripts/interfaces/list_arp.py
```
Home Assistant integration still errors out for me.
