### ISSUE TITLE
IDS: config messup from Rule adjustments tab possible

### ISSUE THREAD

**Issue by kulikov-a** [opnsense/core#4667]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues and I am convinced that mine is new.

**Describe the bug**

Hi!
Sorry, just one more about IDS after https://github.com/opnsense/core/commit/a2a21829fae11a1ad6d738cbd2c1639687ee6f53
From the "Rule adjustments" tab it is possible to accidentally spoil the IDS config.

**To Reproduce**

1. Go to Services: Intrusion Detection: Policy -> Rule adjustments tab
2. Hit clone\copy button instead of edit (this happens to me quite often)
3. Change Rule status or action and click Save
4. Click Apply
5. Should get error like
![ids_config_corrupt](https://user-images.githubusercontent.com/36099472/106761817-4073b200-6646-11eb-8381-9cf598013577.PNG)

in the configuration, an entry is created for the rule with duplicate sid
IDS fails to install rules
need to find and delete duplicate first

**Expected behavior**

rules with duplicate sid should not be written to the configuration
imho this is due to that the user could create only userDefinedRules and there was no need to check the sid.
imho checking the uniqueness of sid can be a resource-intensive and time-consuming operation with a large number of 'manual' rules

**Describe alternatives you considered**

remove or hide (i was only able to hide the clone button with css) the ability to copy\add an item on the Rule adjustments tab.
ejecting a rule from a policy is possible and more convenient on the Services: Intrusion Detection: Administration:Rules tab

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 21.1-amd64 with https://github.com/opnsense/core/commit/a2a21829fae11a1ad6d738cbd2c1639687ee6f53

**Comment by AdSchellevis** [comment]
@kulikov-a  definitely not my lucky day, but still thanks for testing! I'll prepare and push a fix shortly

**Comment by AdSchellevis** [comment]
this https://github.com/opnsense/core/commit/0101becd997d3ac477b567688de2d4674a816c66 should fix it

**Comment by kulikov-a** [comment]
wha! it was fast)
checked. working. the "new" rule takes precedence over the old one. although both are displayed in the Rule adjustments tab and this is a little confusing. but the main thing is that it does not destroy the config
thanks!

**Comment by AdSchellevis** [comment]
I know, you can add both, but since we discourage the use anyways, I think this is good enough.

**Comment by kulikov-a** [comment]
agree! thanks again)
