### ISSUE TITLE
Error when trying to load into Firewall Alias IP Table with a large number of IPs

### ISSUE THREAD

**Issue by Limych** [opnsense/core#4669]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues and I am convinced that mine is new.

**Describe the bug**

OPNsense 21.1-amd64
FreeBSD 12.1-RELEASE-p12-HBSD
OpenSSL 1.1.1i 8 Dec 2020

I am trying to load an alias IP table with a large number of addresses from a remote server.
When I click Apply, the interface first thinks for a long time, after which it displays a window with the text `Invalid argument. [A_test]`. Through `Firewall> Diagnostics> pfTables`, I see that the table is empty.

I decided to find out the reason through direct control with `pfctl`. Here's what happened in the end:
```sh
#
[... Many attempts at sizing the list...]
# tail -n 32768 ~/iptable >/tmp/iptable
# pfctl -t "A_test" -T replace -f /tmp/iptable && pfctl -t "A_test" -T show | wc -l
1 addresses added.
   32768
# tail -n 32769 ~/iptable >/tmp/iptable
# pfctl -t "A_test" -T replace -f /tmp/iptable && pfctl -t "A_test" -T show | wc -l
pfctl: Invalid argument.
#
```

At the same time, the `Firewall> Settings> Advanced> Firewall Maximum Table Entries` field is empty, i.e."On your system the default size is: 200000"

**To Reproduce**

**Expected behavior**

**Describe alternatives you considered**

A clear and concise description of any alternative solutions or workaround you considered.

**Screenshots**

**Relevant log files**

If applicable, information from log files supporting your claim.

**Additional context**

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 21.1-amd64
FreeBSD 12.1-RELEASE-p12-HBSD
OpenSSL 1.1.1i 8 Dec 2020

**Comment by Limych** [comment]
When I explicitly enter "200000" in the `Firewall> Settings> Advanced> Firewall Maximum Table Entries` field, we get the following failure threshold:

```sh
# tail -n 131072 ~/iptable >/tmp/iptable
# pfctl -t "A_test" -T replace -f /tmp/iptable && pfctl -t "A_test" -T show | wc -l
2 addresses added.
  131072
# tail -n 131073 ~/iptable >/tmp/iptable
# pfctl -t "A_test" -T replace -f /tmp/iptable && pfctl -t "A_test" -T show | wc -l
pfctl: Invalid argument.
# 
```

**Comment by kulikov-a** [comment]
@Limych 
what if you flush the table before replace?

**Comment by Limych** [comment]
> what if you flush the table before replace?

While I was trying to figure out the situation, flush did not help. I also got out an error. But I was doing it via `Firewall> Diagnostics> pfTables` interface.

Now, sorry, I can’t check it anymore. This is the main firewall and this check will negatively affect its functioning.

Now I just put an unrealistically large limit in that field, which allowed me to somehow solve the problem.

**Comment by kulikov-a** [comment]
yes. I just think that may be the value of the net.pf.request_maxcount should be twice the length of the list since you not flushing table before reloading new data (so pfctl needs to load table and new data)

**Comment by kulikov-a** [comment]
and yes. it looks like it is
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=235754#c1

**Comment by Limych** [comment]
No, not twice. My test iptable had 147,000 records in total. And with an explicitly specified limit of 200,000 records, the actual limit for some reason turned out to be 131,000... Strange.

**Comment by kulikov-a** [comment]
if you already load 131072 record and try to load 131073 record it gives 262145 records

**Comment by Limych** [comment]
But this does not explain why if I already have 131071 records, I can load 131072. The amount will also be higher than 200000.
The test lists each time differed by only one address. Both in quantity and in content.

**Comment by fichtner** [comment]
Increasing table limit the value was always necessary when using large alias lists. The default of 20000 is rather low and already bumped when internal IPv6 bogon alias is required. Increasing it will make your issues disappear since we also increase net.pf.request_maxcount with it. For all else please use the FreeBSD bug tracker as we will not handle how and why FreeBSD behaves in a particular way in these edge cases.


Cheers,
Franco

**Comment by Limych** [comment]
Thanks, I've already figured out that this is not an OPNsense bug, but a FreeBSD bug. But then it makes sense to at least point out to users such a feature of the system's behavior.

Note that the default value for that field is not 20,000, but 200,000. I figured this would be enough for my list of 147,000 entries. But it turned out that no ... Yes, and the reason for the error was not clear, as I described above.

I am sure there will be many more people who will also stumble upon this problem.

**Comment by kulikov-a** [comment]
@fichtner 
please dont close this yet. i want to test the idea of double the for replacement value for "pfctl -replace". left to find such a giant list). sounds quite logical to me
and please can you look at https://forum.opnsense.org/index.php?topic=20412.0  doesn't look like a bug to you? thanks
@Limych 
I am looking for a large list and will try to figure out the relationship of values for add and replace more precisely.

**Comment by Limych** [comment]
@kulikov-a
Here is my large list generator: https://github.com/Limych/antizapret
But last version generate more compact version of list. About 41000 records.

That version of main script generate about 147000 records: https://github.com/Limych/antizapret/blob/a8fc07377a2e1e4eb3fcda3b35c4f74d10bd572a/antizapret.pl

**Comment by kulikov-a** [comment]
@Limych 
ничего себе табличка )
tested. for this specific table (147259 records), a minimum value of 147259 is required for net.pf.request_maxcount in order to successfully execute the -Tadd command.
to execute the -Treplace command (regardless of whether the table was flushed before that) it was necessary to set the minimum value to 262144.
imho this is due to some buffering when processing the -Treplace command (checking if the limit is exceeded occurs only after reading the next block?). and although the minimum value of request_maxcount can be set slightly lower than two list lengths, so that the replaceis guaranteed to work easier to set it to twice the expected length of the largest table (by the way, on my test VM the default value is set to 1M)

**Comment by kulikov-a** [comment]
@fichtner 
thanks for not closing!
it seems to me that the question has been sorted out, if @Limych  does not mind )

**Comment by Limych** [comment]
Yes, thanks.

**Comment by fichtner** [comment]
Ok, nice, thank you both. Closing then :)
