### ISSUE TITLE
system: move nextcloud backup to plugins

### ISSUE THREAD

**Issue by fichtner** [opnsense/core#4670]
Move the functionality to plugins where it can exist as community-supported code. No automatic plugin registration is planned.

**Comment by HumanG33k** [comment]
Several questions
do you will do the same with the google one ? (maybe already)
I do not use the google one (i prefer the nextcloud one). but i want to know if their is a plan to plugininify not essential stuff ? 
it will be provide by default ? (the nextcloud plugin)

**Comment by fichtner** [comment]
Good questions. The current issue we have is that contributors sometimes do not maintain their code so we are not comfortable providing dependency-less functionality in the core for these. NextCloud backup is one of these cases.

There will probably be no migration path. 21.7 will no longer have the code, but anyone having done the major upgrade can grab it from the plugins and enjoy the same functionality.

Preinstalled plugins are not for community images except for dyndns where people kept asking for it.

In the case of Google Backup I do not know. But we will discuss internally.


Cheers,
Franco

**Comment by HumanG33k** [comment]
Thx.

Providing a by default backup tools (at least one) is a key feature even for community.
i understand the fact of keeping "not own" code is not easy.

Not related :
I m not a firewall or network expert by there is an official way to provide ideas and feedback.

**Comment by AdSchellevis** [comment]
Google backup will likely stay, I've added it back in 2015 and upgraded it to a new api version in 2019. (Unless google stops offering the service in it's present form)
It's also intended as an example to build other options.

Best regards,

Ad
