### ISSUE TITLE
Gateway monitoring doesn't work for dynamic IP after upgrade to 21.1

### ISSUE THREAD

**Issue by definitio** [opnsense/core#4676]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues and I am convinced that mine is new.

**Describe the bug**

Wireguard gateways with dynamic IPs have `Offline` statuses, but they are working fine.

**Relevant log files**

There are similiar lines for every gateway:
```
/system_gateways.php: The WG_1_GW IPv4 gateway address is invalid, skipping.
```

**Additional context**

Gateways IPs are set to `dynamic`. Monitoring is working when `IP address` is set to real gateway IP.

**Environment**

OPNsense 20.1 (amd64, OpenSSL).

**Comment by mimugmail** [comment]
What was the last working version?

**Comment by definitio** [comment]
20.7.7 or 20.7.8.

**Comment by mrzaz** [comment]
I have seen this as well but have started on 21.1.3 so I do not have any tests on older versions.
See screenshots from Gateway setup in OPNsense vs pfSense. (which I am migrating from)

Dynamically created gateways with IP dynamic does not seem to work with gateway IP and monitorIP.
(even if they are available in the IPSec Routed P2 config.)

**OPNSense**

![opnsense_Gateway_Overview](https://user-images.githubusercontent.com/9613777/113323114-df025380-9315-11eb-981e-bda495ffe54b.jpg)
![opnsense_Gateway_Edit](https://user-images.githubusercontent.com/9613777/113323122-e1fd4400-9315-11eb-8432-0e8b836838bb.jpg)

**pfSense**

![pfsense_Gateway_Overview](https://user-images.githubusercontent.com/9613777/113323146-eaee1580-9315-11eb-8520-84d859a463e3.jpg)
![pfsense_Gateway_Edit](https://user-images.githubusercontent.com/9613777/113323244-09eca780-9316-11eb-9515-aac4452f9113.jpg)
![pfsense_Gateway_Widget](https://user-images.githubusercontent.com/9613777/113323252-0ce79800-9316-11eb-9610-a46da7ffe14e.jpg)

Best regards
Dan Lundqvist
Stockholm, Sweden
