### ISSUE TITLE
No console after issueing a factory reset (console menu option 4)

### ISSUE THREAD

**Issue by MNMtm** [opnsense/core#468]
Problem is caused by the absence of loader.conf.local in /boot.
When making a copy of loader.conf to loader.conf.local, the console returns normally after a factory reset.

**Comment by fichtner** [comment]
Which image and version is this? We never once write loader.conf.local and I can't reproduce on a recent iso install. :(

**Comment by MNMtm** [comment]
Problem already existed in 15.7.11 and is still present in the most recent ISO (15.7.18), which I installed via USB key.
The problem already occurs on a fresh install. Just issue a factory reset from the console menu and the console will not come up after the system has restarted.

**Comment by fichtner** [comment]
Let's slow down a little, ISO via USB key? Can you let me have the exact image name you used so that I can retest...

**Comment by MNMtm** [comment]
Sorry, I meant the serial installer: http://sourceforge.net/projects/opnsense/files/15.7.18/OPNsense-15.7.18-OpenSSL-serial-amd64.img.bz2/download

**Comment by fichtner** [comment]
Thanks, will test when I get back home on the weekend. :)

**Comment by fichtner** [comment]
(FWIW, ISO+VM seems to be unaffected)

**Comment by MNMtm** [comment]
Sorry for the confusion about the installer type. :$

**Comment by fichtner** [comment]
No worries, let's keep the bug repots coming :D

**Comment by MNMtm** [comment]
FYI: we always use the serial installer on our appliances. Even the QuadCore Gen3, which does have on-board VGA. But this connector only exists on the mainboard as a pin-header, so it is not accessible to the user. The video interface is used by VNC via AMT though, but normally the console port is used for console access.
