### ISSUE TITLE
Refresh button in log reverts number selected to default.

### ISSUE THREAD

**Issue by upended** [opnsense/core#4681]
No existing report open.

**Describe the bug**
In System: Diagnostics: Activity
When changing the default log count value from 10 to any other value, the amount selected will change back to 10 when selecting refresh.

Revert is not possible as current version is 21.1.

**To Reproduce**
1 Go to page System: Diagnostics: Activity
2 Change log amount from 10 to anything else.  
3. Click on refresh button at the bottom right.
4. Log refresh displaying only 10 entries.

**Expected behavior**
After step 3 (above) Log should display amount selected in step 2.

**Describe alternatives you considered**
Only other option is to manually change every time after refresh.

**Screenshots**
N/A

**Relevant log files**
N/A

**Additional context**
None

**Environment**

Software version used and hardware type if relevant, e.g.:
Versions | OPNsense 21.1-amd64FreeBSD 12.1-RELEASE-p12-HBSD

**Comment by AdSchellevis** [comment]
https://github.com/opnsense/core/commit/d641c00528e95e44bd74f7ed232ec2858f6358bf should keep the grid in shape during reloads of content.
