### ISSUE TITLE
Log pages do not advance (fastforward) to end (last page), 

### ISSUE THREAD

**Issue by upended** [opnsense/core#4682]
No open ticket for issue

**Describe the bug**
System: Log Files: Backend
System: Log Files: General  
System: Log Files: Web GUI
Services: Intrusion Detection: Administration
Services: Web Proxy: Cache Log

The log file does not advance to the last page of the log when clicking on the >> icon.  

A clear and concise description of what the bug is, including last known working version (if any).
When on any of the  pages, selecting > will advance to the next page.  When selecting >>, it only advances to the next page.

Even after advancing several pages, by clicking on the page numbers or >, >> "fast forward" does not advance to end pages.  

Selecting "rewind" will display the first page of log, however, >> still will not advance to end. No testing resulted in >> in advancing more than 1 page.

To account the situation where "the log does not know how many pages can be displayed total" it can not fast forward to the last page as this is a dynamic log and therefore unknown.  This issue exists even when the following actions are taken.
On the first page, advance multiple pages, i.e. page 19 (out of presumable hundreds, as my log contains over 50000 entries), click on << (rewind) to page 1, then click >> (fast forward) to page 19.  However, page 2 is displayed not 19.

At this time both > (next page) and >> (fast forward) have the same actions.  This issue is will all the log pages tested so far. (listed above).

Note: the entry count at the bottom right does not work correctly either as showing ## to ## of XX entries indicates there are only XX entries when in fact there are potentially thousands more.  Even using the advance to page 19 action, rewind to page 1  does not update the total ## of entries the page was able to display moments prior. 

BTW: The entry count (top right) does not impact this issue.

Can not revert on 21.1

**To Reproduce**
1. Go to System: Log Files: General (or any of the 3 pages)
2. Click on click on >>.
3. Will receive next page.

**Expected behavior**
When clicking on >>, page displayed should be of last in log file.

**Describe alternatives you considered**

None,  have to manually continue clicking page by page to review end of file. (The file can have hundreds of pages to advance through before even arrive toward relevant information).  Even with displaying 500 or 1000 entries per page.

**Screenshots**
N/A

**Relevant log files**
Issues are not logged.

**Environment**
Versions | OPNsense 21.1-amd64FreeBSD 12.1-RELEASE-p12-HBSD

**Comment by AdSchellevis** [comment]
https://docs.opnsense.org/manual/gui.html#page-navigation

**Comment by upended** [comment]
I had read that, but does not advancing to page 19 establish the size of the underlying data and number of the subsequent records? By going back to page 1 (from 19) would establish the log is at least 19 pages and the entries contained within?

**Comment by AdSchellevis** [comment]
you don't know the number of records until you actually read them, which in this case a bit a chicken and egg problem. If records would be equally sized, one could calculate the number of pages, but this isn't the case.
