### ISSUE TITLE
installation and keyboard stuck at "Guided installation" - new workaround and bug issue

### ISSUE THREAD

**Issue by FrySlim** [opnsense/core#4685]
There seems to be still a freeze bug in 21.1 "Marvelous Meerkat" in installation GUI at least while installing in a hyper-v VM:
Earlier someone reported the issue with the keyboard stuck at "Guided installation" and a workaround pressing Ctrl-C and continue with relogin as the "installer" user.

I now realised another strange behaviours at the same menu during installation: 
When I enter the "choose font" entry in the previous menu but don't change anything but press ESC to return to the menu or select the "Return to Configure Console" and the "Accept these Settings", the "Guided installation" menu selection works also fine. 
:EDIT: This only works, if you do not enter the keyboard layout submenu after entering the change font submenu. In this case you can use the cursor keys but do not get to the "Guided installation" choice any more :/EDIT:
It seems, that the ESC or "Return to Configure Console" in the change font submenu initializes some menu index variables which is not done, when directly going through to the "guided installation" menu.

By means, going into the "choose font" menu without changing anything before proceeding is another workaround for the keyboard stuck at "guided installation".

Until you fixed the menu/index bug.

Regards
FrySlim

**Comment by UltraHKR** [comment]
This also happen on a VM setup on VMware ESXi-6.7.0-20191204001-standard.

Thankfully I searched and read this... (I was starting to bang my keyboard.)

**Comment by fichtner** [comment]
Installer has been replaced in 21.1.5 in time for use in 21.7.
