### ISSUE TITLE
Suricata rules with "flowbits:noalert" are blocked (false positive) (resurface with 21.1)

### ISSUE THREAD

**Issue by thebitjockey** [opnsense/core#4687]
Here was the original issue that was fixed. #3386

It appears the change to using policies in 21.1 took out the bugfix that changed ignored changing flowbits:noalert rules.  I also do not see a way to add a policy to skip those.

I have emerging-current_events.rules and emerging-trojan.rules set to change all rules to drop.  I am getting false drops from SIDs 2020573 and 2022317 both which have flowbits:noalert set.

alert http $HOME_NET any -> $EXTERNAL_NET any (msg:"ET CURRENT_EVENTS INFO .exe download with no referer (noalert)"; flow:established,to_server; content:".exe"; http_uri; fast_pattern; content:!"Referer|3a|"; http_header; flowbits:set,exe.no.referer; flowbits:noalert; classtype:bad-unknown; sid:2020573; rev:3; metadata:created_at 2015_02_26, updated_at 2020_09_29;)

alert http $HOME_NET any -> $EXTERNAL_NET any (msg:"ET TROJAN Zbot download config - SET"; flow:established,to_server; content:"GET"; http_method; content:".dat"; http_uri; content:!"Content-Type|3a|"; http_header; content:!"Referer"; http_header; pcre:"/\.dat$/U"; flowbits:set,ET.zbot.dat; flowbits:noalert; classtype:trojan-activity; sid:2022317; rev:2; metadata:created_at 2015_12_30, updated_at 2020_06_17;)

--

**Comment by AdSchellevis** [comment]
a bit too late for 21.1.1 which is scheduled for tomorrow, but https://github.com/opnsense/core/commit/f79c311abfd21ab22a708dd5f6a17b62bf017325 excludes the `flowbits:noalert`again, totally missed that one while refactoring the rule updater.
