### ISSUE TITLE
add terminal definition for opnsense in virtualized environment

### ISSUE THREAD

**Issue by spi43984** [opnsense/core#4688]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

[+] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
[+] I have searched the existing issues and I am convinced that mine is new.

**Is your feature request related to a problem? Please describe.**
With Opnsense 21.1 as a PVH guest in Xen there is no serial console.

**Describe the solution you like**
Please add in the file /usr/local/etc/rc.subr.d/recover after the line
`dcons	"/usr/libexec/getty std.9600"	vt100	off secure`
the new line
`xc0     "/usr/libexec/getty Pc"         xterm   on  secure`

[https://github.com/opnsense/core/blob/master/src/etc/rc.subr.d/recover#L181](url)

**Additional context**

While running Opnsense as HVM guest the ttys are just fine, with PVH a tty xc0 is needed. Added that myself to /usr/local/etc/rc.subr.d/recover and it works just fine as well.

Update:
xc0 definition is missing in 21.7 as well. Adding this line brings terminal back in 21.7 as well.

**Comment by fichtner** [comment]
@spi43984 please try this patch:

    # opnsense-patch d5d52ac


Cheers,
Franco
