### ISSUE TITLE
Settings-Tunables edit button opens wrong setting 

### ISSUE THREAD

**Issue by gunnicom** [opnsense/core#4697]
- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues and I am convinced that mine is new.

When going to Settings-Tunables and trying to edit a value, a different value is opened for editing.

1. Go to System-Settings->Tunables
2. Click on edit button for 'hw.ibrs_disable'
3. See edit for 'vfs.read_max' is opened

Seems to be wrong for most of the edit buttons.

**Expected behavior**

The correct value should be opened for editing

**Describe alternatives you considered**

As a workaround I manipulate the url parameter for "id" until I found the correct id for editing the value.

**Environment**

OPNsense OPNsense 21.1.1-amd64    (updateted from 20.7 to 21.1 to 21.1.1)
Browser Chrome & Firefox

**Comment by fichtner** [comment]
ugh, php is horrible...added sorting to the page in 21.1.1 ... I'll fix it

**Comment by gunnicom** [comment]
Wow, that was a fast response :D

**Comment by fichtner** [comment]
Sorry, lunch got in the way ;)

    # opnsense-patch 10646e04c6

That should fix it.


Cheers,
Franco

**Comment by gunnicom** [comment]
Yes. Patch seems to work for me.

**Comment by fichtner** [comment]
Thanks, will be in 21.1.2 ❤️
