### ISSUE TITLE
[IDS/IPS] Status of the et_telemetry rules not correct

### ISSUE THREAD

**Issue by beksphm** [opnsense/core#4698]
**Environment**

OPNsense 21.1.1-amd64
FreeBSD 12.1-RELEASE-p13-HBSD
OpenSSL 1.1.1i 8 Dec 2020
Intel(R) Core(TM) i9-10900 CPU @ 2.80GHz (20 cores)

**Issue**
Status of the et_telemetry IDS/IPS rules not correct

I have a cron definition to update and reload intrusion detection rules every Monday till Friday. I've noticed that the files are updated in directory /usr/local/etc/suricata/opnsense.rules/.
But the status in the Proofpoint widget and in the **Download** tab of 'Services: Intrusion Detection: Administration' is showing an old Last rule download date and time. This date and time is the same for all files in directory /usr/local/etc/suricata/rules, which is a different location.
Which version of the rules is being used and is the status in the widget/administration page correct?

**Comment by AdSchellevis** [comment]
The widget shows the data as being reported by Proofpoint, you can always check if it downloads from the correct location (search emergingthreats in Ssytem->Log Files -> General)

**Comment by beksphm** [comment]
Hello Ad,


The files on the Proofpoint site are newer and larger in size. Furthermore, the current version is 9675 (https://rules.emergingthreats.net/version.txt), as my OPNsense installation is downloading an older version.

And the files in directory /usr/local/etc/suricata/opnsense.rules/ are bigger and newer than the files in /usr/local/etc/suricata/rules.

What am I missing?


Best regards,

Patrick Beks

________________________________

**Comment by AdSchellevis** [comment]
Hi Patrick,

I would start checking the system log to see what it tries to download as suggested, you can trigger the download manually to make sure the entries are easy to find.

Best regards,

Ad

**Comment by rudiservo** [comment]
@AdSchellevis I think that something changed in the rules to download.
https://www.proofpoint.com/us/corporate-blog/post/emerging-threats-announcing-support-suricata-50

here are the rules.
https://rules.emergingthreats.net/open/suricata-5.0/https://rules.emergingthreats.net/open/suricata-5.0/

on the file https://github.com/opnsense/core/blob/master/src/opnsense/scripts/suricata/metadata/rules/et-open.xml
it's downloading the rules for suricata 4, OpnSense Suricata is on v5, I don't really know if that has anything to do with it but, here it is.

also the FAQ is on http and they do not have a redirect so it needs to be changed to:
https://doc.emergingthreats.net/bin/view/Main/EmergingFAQ

Just one final note, it's hard to understand what each rule set has in general without going on the site and look at it.
some of it is not that self explanatory.

**Comment by AdSchellevis** [comment]
It didn’t, we still use v4 rulesets until Proofpoint is ready to ship v5 rules for  telemetry. Both ruleset are compatible with suri 5. Please check the logs as suggested before looking at external causes.

**Comment by beksphm** [comment]
Hello Ad,


In my OPNsense setup, I'm downloading the rules once a day (See attached log extract). I did a manual download on February 20th. Since than, my rules aren't updated.

My installation is still on version 9682, as Proofpoint is on version 9684. I'll keep monitoring the rules download the forthcoming week.


Best regards,

Patrick Beks


________________________________

**Comment by AdSchellevis** [comment]
@beksphm  attachment is missing, but this looks like an upstream problem. Asked Proofpoint to take a look at their end.

**Comment by AdSchellevis** [comment]
Just talked to Proofpoint, their aware of the issue, this sometimes seems to happen when rule publishing for the Telemetry pipeline isn't fully in sync with the normal workflow. They are working on a larger overhaul of the backend pipeline for the Telemetry delivery, which should eventually also include Suricata version 5 rules. If they can temporary fix the async issue, they will probably try to do that in the mean time.

**Comment by beksphm** [comment]
Hello Ad,


The past days, the rules have been automatically updated.


Best regards,

Patrick Beks

________________________________

**Comment by AdSchellevis** [comment]
Hi Patrick, 

Lets close this issue then and call it a fluke on Proofpoints end. 

Best regards,

Ad

**Comment by beksphm** [comment]
Agreed.

________________________________
