### ISSUE TITLE
Interface diagnostics tools inappropriately preferring IPv6 ULA over IPv6 GUA

### ISSUE THREAD

**Issue by Greelan** [opnsense/core#4702]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues and I am convinced that mine is new.

**Describe the bug**

When an IPv6  ULA (Virtual IP/IP Alias) is configured on a LAN/VLAN interface, the diagnostics tools under the Interfaces menu use that ULA in preference to any IPv6 GUA that is also configured on the interface. This can cause the diagnostics tool to fail - for example, when ping is used to ping an external IP address/domain over IPv6 using the LAN interface, the ULA configured on the interface is used as the source address, causing the ping to fail (100% packet loss).

When using traceroute on the LAN interface, it fails to produce any output at all.

This issue appears to be the same as mentioned [here](https://github.com/opnsense/core/issues/3310#issuecomment-584420007).

It may also be related to this [issue](https://github.com/opnsense/core/issues/4651#issue-797330179), if the patch introduced for that issue uses similar logic to present the IPv6 addresses on an interface in the Overview menu. As noted in this [comment](https://github.com/opnsense/core/issues/4651#issuecomment-778565211), after the patch has been applied, the ULA is always shown before the GUA, suggesting that it is being preferred also for display purposes. Previously (ie before OPNsense 21.1), the GUA was shown first.

**To Reproduce**

1. Configure an IPv6 ULA (Virtual IP/IP Alias) on a LAN/VLAN interface, which also has an IPv6 GUA configured.
2. Use the ping diagnostic tool to ping an external IP/domain over IPv6 using the LAN/VLAN as the Source, rather than the default.
3. Use the traceroute diagnostic tool to trace the route over IPv6 to an external IP/domain using the LAN/VLAN as the Source, rather than the default.

**Expected behavior**

I would expect that, at the very least, the IPv6 GUA should be preferred to the IPv6 ULA. However, more appropriately, I think the user should have the option of selecting the desired source address configured on a non-default interface, as this would be more useful when using the tool for diagnostics.

That is at least for ping. That is likely also the appropriate course for other tools such as traceroute, but each tool would need to be assessed based on the underlying logic for selecting an alternative source address/interface.

**Describe alternatives you considered**

None.

**Screenshots**

For illustrative purposes, I have provided CLI output and screenshots for my LAN interface and associated ping6 on that interface.

```$ ifconfig igb1
igb1: flags=28943<UP,BROADCAST,RUNNING,PROMISC,SIMPLEX,MULTICAST,PPROMISC> metric 0 mtu 1500
	options=900028<VLAN_MTU,JUMBO_MTU,NETMAP>
	ether b4:96:91:70:32:61
	inet6 fe80::b696:91ff:fe70:3261%igb1 prefixlen 64 scopeid 0x2
	inet6 fdfd:2553:8868:1::1 prefixlen 64
	inet6 2403:xxxx:xxxx:xxxx:b696:91ff:fe70:3261 prefixlen 64
	inet 192.168.1.1 netmask 0xffffff00 broadcast 192.168.1.255
	media: Ethernet autoselect (1000baseT <full-duplex>)
	status: active
	nd6 options=21<PERFORMNUD,AUTO_LINKLOCAL>
```

![Screen Shot 2021-02-14 at 1 13 59 pm](https://user-images.githubusercontent.com/53196309/107866969-8b08f000-6eca-11eb-9877-c80991f2c00e.png)

![Screen Shot 2021-02-14 at 1 14 41 pm](https://user-images.githubusercontent.com/53196309/107866972-91976780-6eca-11eb-9a7c-63ddf8616618.png)

**Relevant log files**

N/A.

**Additional context**

None.

**Environment**

OPNsense 21.1.1-amd64
FreeBSD 12.1-RELEASE-p13-HBSD
OpenSSL 1.1.1i 8 Dec 2020

**Comment by fichtner** [comment]
The patch should improve the situation in most cases, but it requires further work.
