### ISSUE TITLE
Squid, wrong perms on OPNsense error pages

### ISSUE THREAD

**Issue by Grogdor** [opnsense/core#4703]
This doesn't work for user 'squid':
drwxr-xr-- root wheel /usr/local/etc/squid/errors/local
-rw-r----- root  wheel (files within ^)

Had to chmod 755 local/ and 644 the files within to match the rest of the error page translations.

Versions:
OPNsense 21.1.1-amd64
FreeBSD 12.1-RELEASE-p13-HBSD
OpenSSL 1.1.1i  8 Dec 2020

1) fresh install, navigate to [Services: Web Proxy: Administration, General Proxy Settings](https://192.168.1.1/ui/proxy)
2) check box to Enable proxy
3) set User error pages dropdown to OPNsense
4) hit Apply

5) Go to [Services: Web Proxy: Cache Log](https://192.168.1.1/ui/diagnostics/log/squid/cache)
6) See errors such as:
`2021-02-13T19:45:22 | squid | kid1\| ERROR: loading file '/usr/local/etc/squid/errors/local/ERR_CONNECT_FAIL': (13) Permission denied
`
7) Point a client browser at Web Proxy
8) Navigate to invalid/inaccessible URL
9) Observe resulting error page

Expected result: OPNsense error pages would be shown
Actual result: Squid error pages (logo) is displayed instead, as the OPNsense pages cannot be loaded by user 'squid' due to permissions.

**Comment by AdSchellevis** [comment]
Although I'm not sure why the default in your case isn't correct, https://github.com/opnsense/core/commit/a4f48f7a916e0c5c36f47b78dc6543b0338098d7 should fix it.

Just use `opnsense-patch a4f48f7` to install on the box and apply proxy settings again for restart.
