### ISSUE TITLE
Creating a new API key requires a page reload to show it with Safari

### ISSUE THREAD

**Issue by fl1ger** [opnsense/core#4706]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [ X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [ X] I have searched the existing issues and I am convinced that mine is new.

**Describe the bug**

A clear and concise description of what the bug is, including last known working version (if any).

On
OPNsense 21.1.1-amd64
FreeBSD 12.1-RELEASE-p13-HBSD
OpenSSL 1.1.1i 8 Dec 2020

when I want to add an API key at:
      https://OPNSENSEHOST/system_usermanager.php
the resulting API key is downloaded, but does not show in the list until I reload the page.

I am using Safari Version 14.1 (15611.1.14, 15611) on MacOS Catalina (10.15.7)

*Tip*: to validate your setup was working with the previous version, use opnsense-revert (https://docs.opnsense.org/manual/opnsense_tools.html#opnsense-revert)

**To Reproduce**

1. Go to System->Access->Users
2. Click edit on an existing user
3. Scroll down to API Keys
4. Click + to add a. new API key

The download works, however the list stays empty. I can reproduce this a couple of times, every time there is a download, but the list keeps empty. After a reload all the keys are there.

**Expected behavior**

The API key should appear in the list of API keys after it is downloaded.

**Environment**

OPNsense 21.1.1-amd64
FreeBSD 12.1-RELEASE-p13-HBSD
OpenSSL 1.1.1i 8 Dec 2020

**Comment by AdSchellevis** [comment]
https://github.com/opnsense/core/commit/73ffa7b1abd01f5a7cf039d8ffe2550e618d70bf should fix it on Safari, install using :
```
opnsense-patch  73ffa7b
```
