### ISSUE TITLE
Selecting "Insert my currently connected MAC address (use with care)" fills in wrong MAC address

### ISSUE THREAD

**Issue by teosoft123** [opnsense/core#4709]
**Selecting "Insert my currently connected MAC address (use with care)" fills in wrong MAC address**

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I have searched the existing issues and I am convinced that mine is new.

Please note that this issue causes unexpected consequences when Dynamic DNS us used and ISP issues different IP addresses for different MACs. Which they do. Dynamic DNS does not update quickly enough and as a result, access for certain features that rely on Dynamic DNS is lost. Features such as, but not limited to, issuing Let's Encrypt certificates by means of the eponymous OPNSense plugin before Dynamic DNS changes are fully propagated; it just fails to validate host using HTTP(S) method.

**Describe the bug**

On Interfaces: [WAN] page, I needed to spoof **em0** interface Mac address. Clicking on the link 
"Insert my currently connected MAC address (use with care)" 
fills in wrong MAC address. The filled in MAC belongs to **em1**, LAN.
Other two interfaces have no cables connected. Both **em2** and **em3** devices are configured as OPT1 and OPT2.
OPT3 is configured as **ovpns1**

**Steps to reproduce the behavior:**

In command line:

1. Run ifconfig.
2. Write down MAC addresses for em0 and em1

In WebUI:

1. Go to 'Interfaces'
2. Click on '[WAN]'
3. Scroll down to 'MAC address'
4. Expand (i) help
5. Click on "Insert my currently connected MAC address (use with care)"
6. Compare inserted MAC against those of em0 and em1
7. The inserted MAC is that of the **em1**, LAN

**Expected behavior**

The inserted MAC is that of the **em0**, WAN

**Describe alternatives you considered**

Workaround:
Manually insert the MAC address of **em0** as found by ifconfig

**Environment**

**Software version used and hardware type:**

Software: **OPNsense 21.1.1 (amd64, OpenSSL).**
Hardware: **FW4A – 4 Port Intel ® E3845**, https://protectli.com/product/fw4a/

**Comment by AdSchellevis** [comment]
probably using nat or otherwise not directly connected, the button itself just asks "your" address from the arp table https://github.com/opnsense/core/blob/7fda1670ceaf1ccfda9409471911426e9dc3735e/src/www/interfaces.php#L1845-L1848

**Comment by teosoft123** [comment]
The firewall's em0 interface is connected to Arris modem. I suppose it would be a direct connection. Unless I don't understand what you mean; would you please elaborate?

I confirm that the code snippet above works correctly.
I connected as admin and ran the following:

`/usr/sbin/arp -an | grep [my-external-ip] | cut -d" " -f4`

and it returned the correct MAC for the external, i.e. WAN/em0 interface.

Therefore, the `REMOTE_ADDR` is most likely set to LAN IP, not the WAN IP.

https://github.com/opnsense/core/blob/7fda1670ceaf1ccfda9409471911426e9dc3735e/src/www/interfaces.php#L1845

And running the above with `[my-internal-ip]` returns the em1 MAC, which confirms my idea of `REMOTE_ADDR` being incorrect at that point.

**Comment by AdSchellevis** [comment]
it's likely a configuration issue, using nat could be a cause. More information on "remote_addr" is available in the php reference manual https://www.php.net/manual/en/reserved.variables.server.php

**Comment by fichtner** [comment]
It works normal under the conditions it was designed. Which plugins are you using. Squid (web proxy) as well by any chance?

**Comment by teosoft123** [comment]
It makes sense now. My WebUI is behind HAProxy for some connections, and I can access it directly as well.
Perhaps instead of relying on PHP, that doesn't really know the real configuration you can make a call and fetch the remote address from configuration files. 

When I connect to WebUI `directly` is fills the WAN MAC address field with the MAC address of the interface of the computer that runs the browser accessing WebUI. 

Which means the entire idea of using PHPs `REMOTE_ADDR` env in this place is flawed;  the var is set to the remote address of the client accessing the server. And this is confirmed by the doc linked by @AdSchellevis,

https://www.php.net/manual/en/reserved.variables.server.php:

`'REMOTE_ADDR'
The IP address from which the user is viewing the current page.`

Perhaps I misunderstand the idea of `Insert my currently connected MAC address (use with care)` and it indeed inserts the currently connected computer's MAC address (one of them, as some computers tend to have many).

If this is indeed the case, I think the feature will cause more harm than good and, as cool as it is, must be removed. People who know what they're doing will find the proper MAC address. People who don't should not be able to shoot themselves in the foot. Wouldn't you agree? :)

**Comment by AdSchellevis** [comment]
I simply don't agree, the description is quite clear, it tries to use your address and warns to use with care. If we're going to remove all features someone doesn't understand we likely end up with an empty machine, wouldn't we...

**Comment by fichtner** [comment]
It’s supposed to get the client IP currently connected, which works because your client is HAProxy if you prefer to redirect local traffic. There is no magic involved.

I also suspect your client MAC is not the MAC you want, but that’s another topic.


Cheers,
Franco

**Comment by teosoft123** [comment]
@fichtner Now I understand. Indeed for most people this will not fill out the MAC address they'd want. 

This is a remnant feature that each WiFi router implemented when ISPs would not allow people to switch devices, tying the service to the MAC address that was used when the service was first installed. My ISP does not do that; I can switch devices and get IP address for any MAC, but it will be different IP address, per DHCP spec.

I find this feature more confusing than useful, but maybe it's just me. 

@AdSchellevis the description is not quite clear because there's no such thing as `currently connected MAC address` in most people's mind. My currently connected `computer` has 7 MAC addresses, per `ifconfig` and most people would be at loss as to which one is actually connected.

I want to say that I love OPNSense. I use it for ~7 years and it had never failed me. This ticket is just my attempt at improvement. The logic behind the behavior is quite clear. Perhaps somewhat more elaborated explanation would deter people from getting unexpected results.

**Comment by AdSchellevis** [comment]
fair enough, I don't mind if someone thinks of better wording and proposes a change, from the firewall's point of view your connected ip address maps to a single mac address.
