### ISSUE TITLE
config import: improve backup restore for individual sections

### ISSUE THREAD

**Issue by majorsl** [opnsense/core#471]
I'm not sure if this is an issue or by design. I recently had to rebuild my OPNsense install, either because something got corrupted or of an unknown bug. However, in troubleshooting this, I decided to backup only the configurations that I needed for a restore and ones that I didn't believe led to the mishap.

I only backed up my NAT config and not the firewall rules/aliases/etc.

Upon restoring NAT, that section was properly populated, however the corresponding firewall rules were not populated as they would have been under manual NAT rule creation.

The result was a populated NAT that didn't have associated firewall rules and was non-functional after restore.

**Comment by AdSchellevis** [comment]
It's by design, it probably would have been better to have a more functional backup option and only give the user the option to backup the "firewall" section, because you always have to backup all related options manually now.

**Comment by fichtner** [comment]
How about merging Rules/NAT selection for a start?

**Comment by AdSchellevis** [comment]
Then the problem will return in Aliases... We should clean the backup/restore code at some point, but not today.
To be honest, partial backup will get even more complex in the future with the uuid's in the new components which maycontain relations. I think we need to let this one rest for now.

**Comment by fichtner** [comment]
Remove partial backups for safety reasons then?  :D

**Comment by majorsl** [comment]
For me, and maybe I'm unique, the ability to backup and restore pieces was very handy in my troubleshooting an issue. It was nice to be able to restore just my DHCP w/static addresses along with NAT. I see how it would get complicated with firewall, NAT and aliases all intertwined, however.

**Comment by fichtner** [comment]
Thanks for your feedback! :) How about a hybrid approach, simplifying export to full, making import "mix and match" if requested? Mix and match meaning pick multiple categories, not just one.

**Comment by majorsl** [comment]
Brilliant. That would be fantastic.

**Comment by fichtner** [comment]
parse_xml_config() must be removed for 16.7.1, one more call-site is the System: Configuration: Backup Section Restore.

**Comment by fichtner** [comment]
New feature(s) to be added: make the current configuration the factory reset configuration + reset the factory reset configuration to the default configuration (confusing but useful)
