### ISSUE TITLE
pfTables displays n-1 items

### ISSUE THREAD

**Issue by lcer** [opnsense/core#4711]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x ] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x ] I have searched the existing issues and I am convinced that mine is new.

**Describe the bug**
At the UI http://opnsense/ui/firewall/alias_util/  for every table 1 Item is missing. I.g. if an Alias has 4 Members, only 3 are displayed but "show 1 to 4 of 4" is stated. If ther is only 1 entry for the alias, an empty List ist shown.

**To Reproduce**
1. Open aliases and edit one of them
2. Count the member entries of this alias.
3. Go to  pfTables http://opnsense/ui/firewall/alias_util
4. Count the entries.

This seems to be a problem only for this UI-table, other tables e.g. /ui/diagnostics/interface/routes count and display well.

**Expected behavior**

All entries should be shown. This is important for checking aliases of type "URL Tables (IPs)"
 
**Environment**

OPNsense 21.1.1-amd64
FreeBSD 12.1-RELEASE-p13-HBSD
OpenSSL 1.1.1i 8 Dec 2020
AMD GX-420MC SOC (4 cores)
UI-Language german

**Comment by fichtner** [comment]
Already queued up for 21.1.2 https://github.com/opnsense/core/commit/8e90585b467
