### ISSUE TITLE
IPsec service no longer starting automatically on boot

### ISSUE THREAD

**Issue by fraenki** [opnsense/core#472]
Just updated from 15.7.16-amd64 to 15.7.19-amd64. After performing the required reboot the service `ipsec` was not started automatically. A second reboot showed the same problem. The service state in `Status -> Services` says `Stopped`. I am able to manually start the service, but it should come up automatically again. I never had this issue with previous releases.

Sidenote: I have two instances of OPNsense running, so this bug may be specific to this failover scenario.

**Comment by fraenki** [comment]
Update: After downgrading to 15.7.18 the ipsec service automatically starts on system boot again, so the problem only occurs with 15.7.19.

**Comment by fichtner** [comment]
@fraenki Close this as well?

**Comment by fraenki** [comment]
Yes, 15.7.20 solved this issue as well.
