### ISSUE TITLE
No identical Interface devices will overwrite slave virtual IP assigment

### ISSUE THREAD

**Issue by mohnewald** [opnsense/core#4720]
Hello,

i have a HA-Setup and my interface Names seem to differ (emX vs igbX, etc..).
It seems that when doing a sync from master to slave it will wipe on the virtual IP adressassigment.

This then makes the HA/Carp unhappy. E.g. DHCP-Failover

![interface names and assignment](https://user-images.githubusercontent.com/5985132/108371027-9b3c0a80-71fd-11eb-9efb-42b2e4d8414c.png)

Is this a bug or how can i fix this?

**Comment by mimugmail** [comment]
Neither bug nor fixing, just unsupported: https://docs.opnsense.org/manual/how-tos/carp.html
First Warning box ...
