### ISSUE TITLE
system: remove DH parameters magic

### ISSUE THREAD

**Issue by fichtner** [opnsense/core#4722]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues and I am convinced that mine is new.

**Is your feature request related to a problem? Please describe.**

Since f29c0b9728c32f DH parameter fiddling is not being used by web GUI anymore. The only other consumer is OpenVPN, but using the same logic OpenVPN/OpenSSL/LibreSSL should provide adequate defaults.

**Describe the solution you like**

Remove all the related code bits around DH parameter handling.

IPFire forum discussion suggest using something like this instead

```
dh none
ecdh-curve secp384r1
```

**Describe alternatives you considered**

Ditch all dhparameter handling and move biggest RFC based file to openvpn as static configuration option.

**Additional context**

https://forum.ipfire.org/viewtopic.php?t=22664

**Comment by fichtner** [comment]
@AdSchellevis what do you think about 7eadf5f4475 ?

**Comment by AdSchellevis** [comment]
@fichtner I think we should do this indeed, I can't really find a reason why we shouldn't use RFC 7919 to be honest.

**Comment by fichtner** [comment]
ok, this is taken care of then :)
