### ISSUE TITLE
Top Talkers: showing IPs outside of interface network

### ISSUE THREAD

**Issue by thutex** [opnsense/core#4724]
Top talkers tab currently seems to filter on interface, but not on clients for that interface.
the function is great, and i am very aware this is a young feature that will be improved greatly over time, as we have seen with every part of opnsense, but that being said i would like to remark this:

Say we have WAN and LAN, and decide we only want the top talkers on the LAN.

currently we get:

LAN - LAN IP - IN/OUT stats
LAN - WAN IP - IN/OUT stats

like so:

![landefault_wanips](https://user-images.githubusercontent.com/14796137/108564195-06233980-7303-11eb-9127-a7010c95ea43.png)

i am assuming this is because currently it filters on interface, not filtering out IPs that do not actually belong to that interface.

as witnessed in 2 topics on the forums*, this confuses people (at first, me as well), because you would expect the top talker belonging TO the filtered network to be shown, not the places it is talking to.
with a few devices on the network, and the auto-refresh which cannot be paused, it also becomes fairly difficult to use fairly fast.

so i suggest filtering out the top talkers from a specific interface if they do not actually belong to that interface, so you can have a quick overview of which client on your network is causing a problem, and leaving the detailed analysis of the streams at the insights detail page.

* https://forum.opnsense.org/index.php?topic=21190.0 and https://forum.opnsense.org/index.php?topic=21513

**Comment by AdSchellevis** [comment]
@thutex Looking at this again, I'm not 100% sure I've interpreted the iftop output correctly, so the question is if the stats are correct on the network in question. If you look at the numbers in/out, do they match up?

On a side note, usually we'll mark free-form tickets incomplete, could you be so kind using our templates next time?

**Comment by thutex** [comment]
Sorry about not using the template, i started off with the template but had trouble explaining the issue within the template boundaries.

currently the output from the command '/usr/local/sbin/iftop', '-nNb', '-i', interface, '-s', '2', '-t' is this:
>   1 10.0.5.1                                 =>     5.17Kb     5.17Kb     5.17Kb     1.29KB
     10.0.5.100                               <=     2.98Kb     2.98Kb     2.98Kb       764B
   2 179.60.195.x                            =>       568b       568b       568b       142B
     10.0.5.100                               <=       540b       540b       540b       135B

and it seems right now each line is shown as an individual talker on the selected interface,
while we should only show the second line as that is the actual talker on the interface.
so 10.0.5.1 and 179.60.195.x in this case should not be shown.

on top of that, the above should probably combine the 2 lines, since both are from 10.0.5.100,
and then combine the stats to get the actual in/out from that ip (so we don't risk 100 lines from 1 host, which would make top talkers useless for diagnostics).
but i have no clue as to how we can best do this... maybe jnettop -if available- could be a better alternative?
something like  '/usr/local/sbin/jnettop', '-i', interface, '--local-aggr port --remote-aggr port --display text -t 5 --format src$,$dst$,$proto$,$srcbps$,$dstbps$,$totalbps$'' would give us 

> 10.0.5.100,179.60.195.51,TCP,42,44,86
> 10.0.5.100,142.250.179.206,TCP,35,35,70

which is a much more flexible output? (but it would mean another extra package, since jnettop is not installed or available by default)

**Comment by AdSchellevis** [comment]
@thutex no worries, let's see how we can improve this. I rather stay at `iftop` at the moment, we do need to aggregate in any case. Maybe if I spotted `jnettop` earlier we might have used that one, the output looks a bit more practical indeed.

When I looked at the output again yesterday I also came to the same conclusion, we should aggregate on the second entry, which is the actual talker. Let me try to prepare a patch for this.

**Comment by AdSchellevis** [comment]
@thutex can you try https://github.com/opnsense/core/commit/13c4f8eab6cefd8174f1079981035c0697f3932f?

We should probably also change the api output and gui so we don't have to push in/out separately as we do now, but I first just want to check if we can reach the proper output, which is what this commit should already do.

**Comment by thutex** [comment]
@AdSchellevis just applied it.
I will keep an eye on it to see if anything seems off, but at first look it seems to be exactly what you'd expect!
