### ISSUE TITLE
system: lighttpd chain issue

### ISSUE THREAD

**Issue by fichtner** [opnsense/core#4728]
See note from Glenn at https://forum.opnsense.org/index.php?topic=20856.msg101806#msg101806

```
    ssl.privkey= "/etc/lighttpd/certs/www.example.com/privkey.pem"
    ssl.pemfile= "/etc/lighttpd/certs/www.example.com/fullchain.pem"
```

**Comment by fichtner** [comment]
@fraenki would you mind testing this with a LE certificate?

**Comment by fraenki** [comment]
@fichtner Did a quick testing on 21.1.1 with https://github.com/opnsense/core/commit/48c9b3b403d2b00c58fead8d40913b0d29b03042 applied and it still seems to work as expected. The certificate is still reported as valid in Firefox and Chrome, so I'd say the chain is complete.

**Comment by fichtner** [comment]
thank you ❤️
