### ISSUE TITLE
Firewall live view filters not filtering correctly 

### ISSUE THREAD

**Issue by upended** [opnsense/core#4730]
![Capture](https://user-images.githubusercontent.com/63566363/108615703-873e0780-73bb-11eb-9428-644d08d93921.JPG)
![Capture2](https://user-images.githubusercontent.com/63566363/108615866-26173380-73bd-11eb-8b91-22a6cfc30c14.JPG)

**Important notices**

There are no open tickets related to this issue.

**Describe the bug**
In FW Live View, records matching filter criteria are not matched when using 127.0.0.1 as part of the filter.  When using other filters without using 127.0.0.1, result appear to be correct.

Displays various activity, mostly IPv6 even though not using IPv6 in network. This includes blocked traffic, and pass traffic with ports not configured in filter.

**To Reproduce**

1 Got to firewall live view.
2. Enter any filters needed, except 127.0.0.1 and select "or".
 Ex: DP=443 or DP=80 or SRC=XXXXXX  
3. Use dest and is not 127.0.0.1.
Also happens with 
dest does not contain 127.0.0.1
src and is not 127.0.0.1

**Expected behavior**

When applying filters, for the records to be displayed which only meet the filter criteria.

**Describe alternatives you considered**

There are none.

**Screenshots**

Included

**Relevant log files**

This is a log

**Additional context**

**Environment**

opnsense 21.1

**Comment by upended** [comment]
Also happens with label!~ipv6 or int_name~wan

**Comment by AdSchellevis** [comment]
looks quite normal to me, when using or, any of the criteria should match, there's no special handling in 127.0.0.1, the filters don't know the difference between any other address or localhost.  or type filters usually are only suitable when trying to filter (only) a set of addresses or a set of ports.

**Comment by upended** [comment]
I ran into this today. Filters Used 
srcport,dstport=53 src,dst!=192.168.0.1

Based off these filters, no record with 192.168.0.1 should be listed.  Yet, that is all that is listed for Destination.  (first image)

![Capture](https://user-images.githubusercontent.com/63566363/109553045-60509700-7a87-11eb-8136-013d594a4462.JPG)


Looking at the second image and using the same filter, only 1 record should be displayed.
![Capture2](https://user-images.githubusercontent.com/63566363/109556156-45802180-7a8b-11eb-8737-abff91e9c6e7.JPG)

**Comment by AdSchellevis** [comment]
the `!` `host` might indeed have an issue, the original ticket clearly hasn't (as stated earlier). "host" and "port" are special cases, which normally act as an `or` but in case of an inverted selection should probably act as an `and` condition.

**Comment by upended** [comment]
This is not limited to hosts.  I am seeing additional evidence pointing to the negation (!) as the cause.

![Capture](https://user-images.githubusercontent.com/63566363/112042607-f1ee7a00-8b04-11eb-9e15-99afe1644be7.JPG)

**Comment by upended** [comment]
Is there any progress on this? Also the status has not been changed to programming error.  Will the status be change; or is there something else needed?

**Comment by AdSchellevis** [comment]
> the ! host might indeed have an issue, the original ticket clearly hasn't (as stated earlier). "host" and "port" are special cases, which normally act as an or but in case of an inverted selection should probably act as an and condition.

so far it's a support case, the original tickets doesn't seem to suggest a bug, there might be an edge case (as mentioned in the comments). Likely the best thing todo is to open a new ticket if you can isolate an (one) issue so there's something which might be worth investigating, most of the ticket and the comments are false assumptions about how the logic should work, which doesn't provide much to work on.

**Comment by upended** [comment]
Closing ticket, created #4988.
