### ISSUE TITLE
Feature Request: Firewall Live Log Templates

### ISSUE THREAD

**Issue by kosta880** [opnsense/core#4731]
[x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
[x] I have searched the existing issues and I am convinced that mine is new.

I find myself often re-adding filters like (just an example) to troubleshoot similar issues - this is a typical filter I use to troubleshoot issues in and between internal networks.
action~block
label!~IPv6
interface_name!=WAN
interface_name!=Loopback

I am missing here a possibility to create a template with various filters which can quickly be applied when entering the page.
Sort of:
Create a new template, add desired filters, meaningful name/description, save, and then I get a list of filters to choose from.
Possibly an additional option that would leave the last setting that was set, not resetting each time I enter the Live View.

Thank you.

**Comment by AdSchellevis** [comment]
closing in favour of https://github.com/opnsense/core/issues/4859
