### ISSUE TITLE
XSS Vulnerability - savemsg

### ISSUE THREAD

**Issue by MTecknology** [opnsense/core#4745]
The web interface appears to use a ``savemsg`` variable from the URL and does not sanitize the input. This leads to a URL such as ``https://<ip>/carp_status.php?savemsg=<script>window.alert("sometext");</script>`` being perfectly valid (produced a popup box). This means that a crafted URL can be used to perform an XSS-based attack against users.

Yes, one would like to assume that users with access to a firewall would know better, but experience tells us all that it would be a false assumption.

**Expected behavior**

At a minimum, the text should be sanitized. It would be better if the message didn't come from user input (an invalid login message, for example).

**Environment**

OPNsense 21.1-amd64
FreeBSD 12.1-RELEASE-p12-HBSD
LibreSSL 3.2.3

**Comment by fichtner** [comment]
It looks ok to me to be honest... already commented on IRC ;)

<img width="679" alt="Screenshot 2021-02-24 at 11 05 58" src="https://user-images.githubusercontent.com/1915288/108984524-4df1ea00-7690-11eb-9bb5-d711bcad30b6.png">

**Comment by MTecknology** [comment]
On my system, this produced a pop-up box with "sometext".

**Comment by MTecknology** [comment]
After chatting with @fichtner on IRC, it sounds like the lack of sanitization might be a problem with my browser or a plugin.

**Comment by fichtner** [comment]
FWIW, I checked all of these and savemsg is always encoded correctly:

```
% git grep savemsg=                            
src/www/carp_status.php:    header(url_safe('Location: /carp_status.php?savemsg=%s', array($savemsg)));
src/www/firewall_scrub.php:        header(url_safe('Location: /firewall_scrub.php?savemsg=yes'));
src/www/system_general.php:        header(url_safe('Location: /system_general.php?savemsg=%s', array('The changes have been applied successfully.')));
src/www/system_usermanager.php:            header(url_safe('Location: /system_usermanager.php?savemsg=%s', array($savemsg)));
src/www/system_usermanager.php:        header(url_safe('Location: /system_usermanager.php?savemsg=%s&act=edit&userid=%d', array($savemsg, $id)));
src/www/system_usermanager.php:        header(url_safe('Location: /system_usermanager.php?savemsg=%s&act=edit&userid=%d', array($savemsg, $id)));
src/www/system_usermanager.php:                header(url_safe('Location: /system_usermanager.php?savemsg=%s', array(get_std_save_message(true))));
src/www/system_usermanager.php:                header(url_safe('Location: /system_usermanager.php?act=edit&userid=%d&savemsg=%s', array(isset($id) ? $id : count($a_user) - 1, get_std_save_message(true))));
src/www/system_usermanager_addprivs.php:            header(url_safe('Location: /system_usermanager.php?act=edit&userid=%d&savemsg=%s', array($userid, $savemsg)));
src/www/system_usermanager_passwordmg.php:            header(url_safe('Location: /system_usermanager_passwordmg.php?savemsg=%s', array('Saved settings for user "%s"')));
src/www/vpn_ipsec_mobile.php:        header(url_safe('Location: /vpn_ipsec_mobile.php?savemsg=%s', array($savemsg)));
```
