### ISSUE TITLE
Move Interface Grouping from Firewall to Interfaces in Menu

### ISSUE THREAD

**Issue by gunnicom** [opnsense/core#4747]
- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues and I am convinced that mine is new.

**Is your feature request related to a problem? Please describe.**

Groups of Interfaces can be created at "Firewall -> Groups".
I did this and then wondered why I cannot see my Interfaces at "Interfaces". I then found them but grouped under the new Group.

**Describe the solution you like**

For me it seems more logical that the grouping (as it also effects the Interface view) would be done under "Interfaces -> Groups" and not under "Firewall -> Groups"

**Describe alternatives you considered**

Your opinion might vary, and maybe there is a good reason to keep it like now, that I did not see.

**Additional context**

OPNsense 21.1.2

**Comment by fichtner** [comment]
It used to be there, but since it is only a firewall abstraction it was moved.

**Comment by fichtner** [comment]
Context c2190c1f52f and https://github.com/opnsense/core/issues/4016

**Comment by gunnicom** [comment]
It is no major problem for me. Maybe I think different. I was a little bit confused as this grouping has an effect on display of interfaces.

**Comment by fichtner** [comment]
Ok, thanks, in this case I'll close the ticket. In any case thanks for your feedback. :)
