### ISSUE TITLE
IPFW / shaper: large (long) SRC / DST entries in rule won't be parsed by ipfw / no more rules active

### ISSUE THREAD

**Issue by botboe** [opnsense/core#4756]
- [ x ] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [ x ] I have searched the existing issues and I am convinced that mine is new.

**Shaper: handling of large (long) SRC / DST entries in rules**
I successfully added the list of Cisco-Webex-hosts into the Source-field of a shaper-rule. When applying the settings and reviewing the status-page I saw that no rule was active anymore but the dashboard said the ipfw-status was fine.

I restarted the ipfw-daemon manually and saw this error:
```
root@foowall:~ # service ipfw restart
Line 89: address list too long
Firewall rules loaded.
```
Where line 89 (which is really quite long) contained my Webex-IPs:
```
add 60002 queue 10011 ip from any to 3.22.157.0/26,18.181.178.128/25,69.26.160.0/19,3.25.56.0/25,18.181.204.0/25,114.29.192.0/19,3.101.70.0/25,18.230.160.0/25,150.253.128.0/17,3.101.71.0/24,20.50.235.0/24,170.72.0.0/16,3.101.77.128/28,20.53.87.0/24,170.133.128.0/18,3.235.73.128/25,40.119.234.0/24,173.39.224.0/19,3.235.80.0/23,44.234.52.192/26,173.243.0.0/20,3.235.122.0/24,52.232.210.0/24,207.182.160.0/19,3.235.123.0/25,62.109.192.0/18,209.197.192.0/19,18.132.77.0/25,64.68.96.0/19,210.4.192.0/20,18.141.157.0/25,66.114.160.0/20,216.151.128.0/19,18.181.18.0/25,66.163.32.0/19 src-port  any dst-port any    via igb0 // 5e11c675-e756-436a-8ac0-3dc7e23607d7 opt3: WebConf-ViConf - Upload
```

Splitting this single rule into two worked as a workaround, but can't be the solution. The main problem is that you don't get feedback in the GUI that the configfile was not parsed successfully, as the ipfw runs anyway.

**Environment**
 - OPNsense 21.1.1-amd64
 - FreeBSD 12.1-RELEASE-p13-HBSD
 - OpenSSL 1.1.1i 8 Dec 2020
 - Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz (4 cores)

**Comment by AdSchellevis** [comment]
the number of accepted addresses in single rules is limited indeed, I've prepared a patch https://github.com/opnsense/core/commit/f4966e15c6bb7d4e5a2e9e8fb21cfe9051d1f072 to use tables when more than one address is provided.

Can you try  this (on 21.1.2, from the console):
```
opnsense-patch f4966e1
```

then reload the ruleset
