### ISSUE TITLE
OPNSense 21.1.2 breaks multible IPSEC Road Warrior connections from one IP

### ISSUE THREAD

**Issue by goodomens42** [opnsense/core#4757]
Since updating to 21.1.2 multible IPSEC Road Warrior connections originating from one IP address "kick out" each other.
We are using mobile IKEv2 VPN with Microsoft RADIUS authentication, most users are using the builtin Windows10 client, some of them StrongSwan on Android. Each user has it's own RADIUS account.

With 20.7.7 everything worked like a charm, independent connections originating from one IP (eg two Laptops behind the same NAT Router) were possible. I haven't tested StrongSwan on Andoid yet, but at least with Windows10 clients this behaviour is broken since updating to 21.1.2.

**To Reproduce**

1. Enable mobile VPN in OPNsense with IKEv2 and EAP-RADIUS Authentication
2. Create two VPN Users user1 and user2 with different RADIUS accounts and set up a Windows10 Client connection for each of them on two  laptops laptop1 and laptop2
3. Place both laptops behind the same NAT router and start the VPN for user1
4. Ping an address through the tunnel
5. Start the VPN for user2 on laptop2
6. The ping in 4) will stall

**Expected behavior**

Should work as it did in 20.7.7.

**Describe alternatives you considered**

no workarround except going back to 20.7.7 which we will to tonight

**Environment**

OPNsense 21.1.2 (amd64, OpenSSL).

**Comment by goodomens42** [comment]
The problem was also reported on the OPNSense forum, see [https://forum.opnsense.org/index.php?topic=21623.0]

**Comment by mimugmail** [comment]
Let's stick to the forums as there's a broader community but leave this one open here if we found out that it's a but introduced with X :)

**Comment by mimugmail** [comment]
@goodomens42 can you try this on your end? 
https://forum.opnsense.org/index.php?topic=21766.0

**Comment by goodomens42** [comment]
@mimugmail

> @goodomens42 can you try this on your end?
> https://forum.opnsense.org/index.php?topic=21766.0

haven't tried, but IPSEC site-to-site worked fine with 21.1.2
Right now we are back on 20.7.8_4 and everything is working as it should.

To come there I reverted to a VM snapshot with 20.7.7_1, did the updates and tested with pings after each update as decribed above

20.7.7_1   works fine
20.7.8_4   works fine
21.1         fails, as soon as the second connection is started, the first ping stalls
21.1.2      fails, as soon as the second connection is started, the first ping stalls

So the problem seems to come with 21.1

**Comment by AdSchellevis** [comment]
As discussed and tested with @mimugmail, https://github.com/opnsense/core/commit/8bf80e028a6fd414c2f1ba92d194f12dd8f8f427 removed sticky reqid from mobile connections. 

To test locally, use opnsense-patch and reboot the machine (easiest option, stop / start ipsec should probably also work):

```
opnsense-patch  8bf80e0 
```

**Comment by goodomens42** [comment]
> To test locally, use opnsense-patch and reboot the machine (easiest option, stop / start ipsec should probably also work):
> ```
> opnsense-patch  8bf80e0 
> ```
Just tested, works fine with 21.1.2, thanks a lot !

**Comment by AdSchellevis** [comment]
@goodomens42 thanks for confirming!

**Comment by fichtner** [comment]
@AdSchellevis this is a 21.1.3 candidate, right?

**Comment by AdSchellevis** [comment]
@fichtner yes please, thanks for asking, almost forgot :)

**Comment by brunotl** [comment]
seem's the problem is back, i have exactly the same problem with "OPNsense 23.1.1_2-amd64"

**Comment by fichtner** [comment]
@brunotl qualified new ticket please. it's unlikely the same issue

**Comment by AdSchellevis** [comment]
@brunotl can you try https://github.com/opnsense/core/commit/9be878390a762f8d23c09789ef34696f53b0ab3e ?

**Comment by brunotl** [comment]
seem's ihave missed something, i got an error when i try to apply your patch : 

```
root@dcfw:~ # opnsense-patch 9be8783
Fetched 9be8783 via https://github.com/opnsense/core
1 out of 1 hunks failed while patching etc/inc/plugins.inc.d/ipsec.inc
```

**Comment by AdSchellevis** [comment]
the master branch has more changes (https://github.com/opnsense/core/commits/9be878390a762f8d23c09789ef34696f53b0ab3e/src/etc/inc/plugins.inc.d/ipsec.inc), might be easier to just edit these couple of lines for now

**Comment by brunotl** [comment]
@AdSchellevis manualy pached, and rebooted, problem still the same ...

**Comment by AdSchellevis** [comment]
best open a new ticket than as @fichtner suggested and try to collect some details in it. `/usr/local/etc/swanctl/swanctl.conf`  should contain the relevant configuration to inspect.
