### ISSUE TITLE
IPS alerts part 3 - paging

### ISSUE THREAD

**Issue by mnaiman** [opnsense/core#4759]
Continuation of https://github.com/opnsense/core/issues/4753
Now there some glitch in paging or alerts enumeration.

Same steps to setup environment.
Waiting few hours to collect some alerts.

115 alters collected. 
![image](https://user-images.githubusercontent.com/2264442/109294882-1c168a00-782e-11eb-9410-89e1185a3033.png)
Paging set to greater than 115, like 500.

All 115 are enumerated ok.
At the end of page is paging
![image](https://user-images.githubusercontent.com/2264442/109294760-e83b6480-782d-11eb-8f8d-ba76d1ec5ae7.png)

7 pages? Why?

If I switch to second page it is empty
![image](https://user-images.githubusercontent.com/2264442/109294913-289ae280-782e-11eb-9f7c-3a5d8d5aad70.png)

It could be related to fact, that there was great amount of alerts, they were deleted using this button
![image](https://user-images.githubusercontent.com/2264442/109294986-449e8400-782e-11eb-9152-ca3e7522d659.png)
but some COUNT of alerts is not reset.

**Comment by mnaiman** [comment]
Ah, maybe it is not problem of delete button.
Further testing - no matter of what is selected here 
![image](https://user-images.githubusercontent.com/2264442/109295312-d5755f80-782e-11eb-98b6-f53627e1d730.png)

Paging still uses number 7 
![image](https://user-images.githubusercontent.com/2264442/109295344-e2924e80-782e-11eb-8950-1da67519d881.png)

Number 7 is selected in dropdown at page initial load. So dropdown is filling table with correct number of alerts, but does not update paging.

**Comment by AdSchellevis** [comment]
it can't know the number of pages, some background https://docs.opnsense.org/manual/gui.html#page-navigation

**Comment by mnaiman** [comment]
Ah, ok, so Im closing this. Thanks for response.
