### ISSUE TITLE
Document Cron job templates (in particular "Automatic firmware update")

### ISSUE THREAD

**Issue by felixdivo** [opnsense/core#4760]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues and I am convinced that mine is new.

**Is your feature request related to a problem? Please describe.**

Automatic updates are very useful, but it's not entirely clear how the "Automatic firmware update" Cron job template works. It can be found here: `https://your.router/ui/cron > (+) button > Command > Automatic firmware update`.

**Describe the solution you like**

Update [the docs](https://docs.opnsense.org/manual/settingsmenu.html#cron) to describe what the jobs do in more detail. Currently, they are not listed at all. In particular, we were interested in how to configure the update to only perform the ones were no restart is required, or if that is even directly supported.

**Describe alternatives you considered**

Open an issue/ask in the form each time there is a question.

**Comment by fichtner** [comment]
There is no granularity in updates and that is why no more information is given. Updates are applied, reboots are done as required by the update.


Cheers,
Franco

**Comment by luispabon** [comment]
>  reboots are done as required by the update.

The docs should certainly at the very least mention this. I could only find this information on this very page.

**Comment by fichtner** [comment]
There is no inconsistency in firmware update behaviour between GUI, console and cron in terms of reboot behaviour. What do you expect of it that would not match reality?

**Comment by luispabon** [comment]
This is the entry:

![image](https://github.com/opnsense/core/assets/6388823/6dfa6904-9c35-4ecc-a5f0-2ca1306d89f0)

That it will reboot if necessary is a pretty important tidbit of information that imho should be mentioned there. Otherwise we expect people to know this indirectly from having noticed the GUI or console do a certain thing when manually applying updates. I for one hadn't made the connection.

**Comment by fichtner** [comment]
I am not fully aware if the actual firmware page documents this as you expect. The information would make a lot more sense there as opposed to a cron job description.

One of the downsides of people asking for documentation of cron jobs is that they are heavily bound to the current implementation and settings and user changes. It would probably be better to point to the actual script being executed than to try and describe what each script does (and why), but that’s only my opinion.


Cheers,
Franco
