### ISSUE TITLE
Larger drop down menus for higher resolution screens

### ISSUE THREAD

**Issue by tomlawesome** [opnsense/core#4766]
Larger resolution screens (Such as 4K monitors) have very small drop down menus in the webGUI.

**Describe the solution you like**
Increase drop down size for monitors with a higher native resolution, or allow the user to specify it. This will allow quicker changing of options for users with a large screen when performing configuration. 

**Describe alternatives you considered**
Searching for the result -- whilst this is possible, it involves switching to KB and performing keystrokes, then using mouse clicks. 
Scroll the mouse wheel -- this is slower than typing a search. 

**Additional context**

![photo_2021-02-28_15-43-00](https://user-images.githubusercontent.com/76453276/109424513-cda6ee00-79db-11eb-8d98-fe50c89f163d.jpg)

**Comments**

Whilst this is not a big issue for performance / capability, it would be a nice small tweak for usability. OPNsense already has the best firewall GUI and this will help keep it that way!

**Comment by FingerlessGlov3s** [comment]
This would also be handy for myself, since I have 2 1440p monitors.

**Comment by AdSchellevis** [comment]
we use bootstrap select (https://developer.snapappointments.com/bootstrap-select/options/) for these, if I'm not mistaken it sometimes annoyingly overflows when not pre-setting to a fix number of visible options. `data-size='auto'`  should size with the screen, but previous experiences on our end weren't great when used.

**Comment by tomlawesome** [comment]
> we use bootstrap select (https://developer.snapappointments.com/bootstrap-select/options/) for these, if I'm not mistaken it sometimes annoyingly overflows when not pre-setting to a fix number of visible options. `data-size='auto'` should size with the screen, but previous experiences on our end weren't great when used.

Cool. It's not a major issue or anything, rather a small usability thing. Felt like it was worth mentioning.
