### ISSUE TITLE
Enable dhcp6c auto SLA-LEN correct

### ISSUE THREAD

**Issue by marjohn56** [opnsense/core#4768]
Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues and I am convinced that mine is new.

dhcp6c relies on the user inputting the correct SLA-LEN so that it matches the prefix given by the ISP, if this does not occur then there are no IPv6 addresses applied to the tracking interfaces. We also 'guestimate' the prefix provided.

dhpc6c should be able to correct this for us, and use the supplied prefix to configure the interfaces, saving the user the hassle of having to find out what the ISP is providing.

This is a discussion, though I already have a dhcp6c version that does this. I have also added a new flag to the command line, 'a' which is 'auto' if this flag is set then dhcp6c will auto correct and configure the tracking interfaces automatically, disregarding what the user has set the SLA-LEN to, if 'a' is not set then dhcp6c will behave as it always did.

There's a PR for this in dhcp6c

**Comment by maurice-w** [comment]
Great idea!
This will only work though if the delegated prefix is shorter than the requested one, not the other way round, correct? Let's say you request a /56 and configure 8-bit subnet IDs (like a1, a2, b1, b2) for the tracking LAN interfaces. But the ISP only delegates a /60. The only thing we can do now is fail gracefully. Or am I missing something?

**Comment by marjohn56** [comment]
Well I tested with asking for a 60, my primary was set to dish out /56, that worked, so then I set my primary to give out /60 and asked for a /56. that worked too. Just thinking how I can test this to breaking point. I guess If add a couple more VLANs, I have three on the test already, so that would be 5 and set the primary to give out a /62 and see what happens... I'll go play.

**Comment by maurice-w** [comment]
You probably used shorter subnet IDs then (1 hex digit)?
If you use 8-bit subnet IDs (2 hex digits) and get a /60 delegation, there is just no way to merge prefix (60) + subnet ID (8) to a /64.

**Comment by marjohn56** [comment]
Or I could remove the second catch I put in where the prefix is smaller than requested, in which case dhcp6c will barf as it always did.

**Comment by marjohn56** [comment]
@maurice-w - why would you use a 2 digit prefix ID anyway, what benefit is there over using 1,2,3,4.... etc

**Comment by marjohn56** [comment]
I have an idea... might be a good one or not, but that's what discussions are for. If we make the 'a' flag an option in the interfaces settings section for dhcp6c,  if not set then it will allow you to set the IPv6 PrefixIDs for the tracking interfaces, if it is set then you have no choice and it will assign the prefixes in sequential order to the max allowed by the received prefix. 
Thoughts?

**Comment by marjohn56** [comment]
OK, that works.. Added a little check that counts the number of prefixes given out and I override the SLA_ID, just going sequential. SO for example I have six VLANs, only first four are getting an address, the other two there's no address applied. That's probably the best the can be hoped for.

**Comment by maurice-w** [comment]
Indeed, that's what discussions are for!
Subnet IDs are widely used to represent existing information like VLAN IDs. That's actually more common than simple sequential numbering.
I don't think we can or should automate everything. If the delegated prefix length doesn't match the requested one but we can still fit the user-configured subnet IDs, by all means, let's do it. But if they don't fit, gracefully fail and let the user know.
My opinion about automatically assigning subnet IDs: No. Just no. That's fine for basic plug'n'play consumer routers, but not for something like OPNsense.

**Comment by marjohn56** [comment]
But that's why we make it idiot proof... and there are a lot out there 😉. You have the option, auto or not. If we leave auto off by default  then that's one way to keep your IDs, or Auto is on by default so it will work out of the box.

I could put a check in there to see if the ID supplied is valid for the prefix obtained and log a message if it isn't. 
As a certain robot once said, more input needed.

**Comment by maurice-w** [comment]
> I could put a check in there to see if the ID supplied is valid for the prefix obtained and log a message if it isn't.

Definitely a good idea! Maybe even an error message on the dashboard?

Whether we should try to attract more "idiots" is a more fundamental question. I'd say, if you have to rely on your firewall to auto-create an address plan for you, OPNsense is out of your league. Or is that to harsh?

**Comment by marjohn56** [comment]
A bit harsh, we all need to start somewhere. Some days I still do a 'doh' moment with IPv6 and I would guess there are many who are completely lost with IPv6. Rather than turn people away by trying to make it exclusive to those who 'understand' it should be as idiot proof as possible, meaning less time wasted in the forums trying to guide someone through a setup.

**Comment by marjohn56** [comment]
Note sure how we could flag a warning in the GUI, perhaps I'd need to make dhcp6c write a file to temp. I'll leave that to those with better brains in that department to think on. TBH, I quiet like the idea of assigning all available prefixes and then skipping the interfaces our excess to the prefix size, Looks like this:

![image](https://user-images.githubusercontent.com/17962918/109570380-d8e44180-7ae1-11eb-9d57-323cb5aad02d.png)

**Comment by maurice-w** [comment]
You do have a point regarding the out-of-box experience. After a new user has completed the initial wizard, IPv6 should "just work". But isn't that already the case? The default is a single LAN with subnet ID 0, tracking the single WAN. This works for any delegated prefix size.

When you add additional LANs and enable tracking, _maybe_ we could intelligently prefill the subnet ID in interfaces.php (currently always 0). As in: Prefill the lowest value not currently configured on any other interface.
But automatic assignments at runtime? I'm not convinced. Weird things could happen. Remove an interface and suddenly the subnets of your other interfaces change. Or something like that. OPNsense barely works with dynamic prefixes, and now add dynamic subnet IDs on top of that?

If we detect at runtime that a configured subnet ID doesn't fit the delegated prefix, skipping the interface and logging an error certainly is a good idea. As in: Don't assign a GUA, don't enable radvd + dhcpd6.

**Comment by marjohn56** [comment]
Not sure it does run 'OOTB' with any prefix, What's the default SLA-LEN, 8 ? 

I take your point about a removed interface re-assigning prefixes, however the idea is not to force users to go the auto route, just to make sure it auto configures. Once that is done then the information is all there to allow the user to disable auto configure as they see fit. Need the thoughts of @fichtner and @AdSchellevis etc.

**Comment by maurice-w** [comment]
> Not sure it does run 'OOTB' with any prefix, What's the default SLA-LEN, 8 ?

0, but doesn't really matter with SLA-LEN autocorrect in place (which I very much agree with). I didn't mean to say "works OOTB right now", but "doesn't require dynamic subnet ID assignment to work OOTB".

I just don't see the advantage of dynamic subnet ID assignment at runtime over 'assisted' static assignment at the time of configuration. Even as an optional setting. Agreed, more input required or we'll start going in circles. :)
