### ISSUE TITLE
Version 21.7.a_115 >> reset all local conflicts >> ends up in a sidebar problem

### ISSUE THREAD

**Issue by opnsenseuser** [opnsense/core#4769]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues and I am convinced that mine is new.

**Describe the bug**

Version 21.7.a_115 >> Resolve plugin conflicts >> Reset all local conflicts ends up in a sidebar problem

**To Reproduce**

1. System: Firmware
2. Click on Status
3. Click on Resolve plugin conflicts
4. Choose Reset all local conflicts
5. See error (screenshot)
6. you have to reload the page to get rid of the problem

OPNsense 21.7.a_115 (amd64, OpenSSL).
Oracle VM Intel® Core(TM) i7-4790K CPU @ 4.00GHz (1 cores)
Network Intel® I210-AT

![grafik](https://user-images.githubusercontent.com/34602360/109496735-592e8680-7a91-11eb-87f6-bed25bee5062.png)

**Comment by fichtner** [comment]
It’s a known issue via #4500 and we will fix it, although the sidebar code is a little guilty of caching the menu structures persistently. ;)
