### ISSUE TITLE
IPsec failover broken: both nodes connecting

### ISSUE THREAD

**Issue by fraenki** [opnsense/core#477]
After updating from 15.7.16 to 15.7.18 (and 15.7.19) my secondary firewall node is now trying to establish IPsec tunnels, although my primary firewall node is still alive.

On the secondary firewall node I can see that CARP status is `BACKUP` and pfsync is working as expected (changes on the primary node make it through to the secondary node).

I've already rebootet my primary and secondary firewall nodes multiple times, but the secondary node keeps trying to do IPsec...

```
Security Associations (0 up, 2 connecting):
        con6[5]: CONNECTING, A.A.A.A[%any]...B.B.B.B[%any]
        con6[5]: IKEv1 SPIs: 6d249f4974d563ea_i* 0000000000000000_r
        con6[5]: Tasks queued: QUICK_MODE 
        con6[5]: Tasks active: ISAKMP_VENDOR ISAKMP_CERT_PRE MAIN_MODE ISAKMP_CERT_POST ISAKMP_NATD 
    con1-000[6]: CONNECTING, A.A.A.A[%any]...C.C.C.C[%any]
    con1-000[6]: IKEv1 SPIs: ccd7cc58a362b883_i* 0000000000000000_r
    con1-000[6]: Tasks queued: QUICK_MODE 
    con1-000[6]: Tasks active: ISAKMP_VENDOR ISAKMP_CERT_PRE MAIN_MODE ISAKMP_CERT_POST ISAKMP_NATD 
```

The only way to workaround this issue was to stop the `ipsec` service on the secondary node.

**Comment by fraenki** [comment]
Update: this issue still exists after upgrading to 15.7.20.

**Comment by AdSchellevis** [comment]
I'm not sure how this should work, for as far as I know if the tunnel is using the carp interface it cannot connect to the outside world, but the daemon (ipsec in this case) doesn't know that so might keep trying.
Only reference I could find quickly was https://redmine.pfsense.org/issues/1698

**Comment by AdSchellevis** [comment]
The trick seems to be adding an option to make the tunnel responder only.... that is, if the other side isn't using the same kind of configuration.
I think we could add this rather easily into a future release.

**Comment by AdSchellevis** [comment]
https://github.com/opnsense/core/commit/158269e1dc371f3f7e44c9bd3745a98ddff9d882 adds the option to select the connection behaviour (only accept, always connect, connect on traffic {route}).
