### ISSUE TITLE
Upgrade OpenVPN to 2.5.x for ChaCha20 support

### ISSUE THREAD

**Issue by beren12** [opnsense/core#4776]
OpenVPN 2.5 has been released officially and includes support for the ChaCha20 cipher. This is great for low power devices who don't have AES acceleration built in. As an example, my raspberry pi zero can encrypt 45MB/s with chacha20 and 10 MB/s with aes-128-gcm. Sadly, on things like my asus routers, wireguard is not an option, only openvpn so this is quite a boost in speed for them. openssl is already shipping in opnsense with chacha support, so it should be a fairly simple update.

**Comment by beren12** [comment]
it's in fresh ports now: https://www.freshports.org/security/openvpn

**Comment by fichtner** [comment]
@beren12 2.5.3 does not list ChaCha20 in supported ciphers with LibreSSL, other than the new OpenVPN will be ready with 21.1.8.

**Comment by beren12** [comment]
Great as long as it works with open SSL

**Comment by fichtner** [comment]
Looks like a larger issue: https://github.com/libressl-portable/portable/issues/483

There is no reason we should keep this open since we don't know how long it will take.
