### ISSUE TITLE
FR: Whitelist for URL table under Firewall > Aliases

### ISSUE THREAD

**Issue by Christophe999s** [opnsense/core#4779]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I have searched the existing issues and I am convinced that mine is new.

**Is your feature request related to a problem? Please describe.**

It would be useful to have the option to whitelist certain ip's under Firewall > Aliases, similar to the whitelists in Unbound 
![image](https://user-images.githubusercontent.com/36367001/110027214-fe678a00-7d31-11eb-9a7a-53c1fed12bc6.png)

**Describe the solution you like**

Have a whitelist option like unbound

**Comment by mimugmail** [comment]
Usually you add a Whitelist alias and put the exclude rule above

**Comment by AdSchellevis** [comment]
https://docs.opnsense.org/manual/aliases.html#nesting

**Comment by Christophe999s** [comment]
> https://docs.opnsense.org/manual/aliases.html#nesting

Thanks! Didn't know that was an option, just implemented this and works fine.
