### ISSUE TITLE
CARP; virtual IP - ioctl (SIOCDIFADDR): Can't assign requested address

### ISSUE THREAD

**Issue by phhutter** [opnsense/core#4792]
**Describe the bug**
Virtual IPs are in state DISABLED and I'm not able to bring them up.
![grafik](https://user-images.githubusercontent.com/26787995/110550764-8a175700-8134-11eb-98cc-fc796e2c56fa.png)

Configuration should be fine:
![grafik](https://user-images.githubusercontent.com/26787995/110550722-779d1d80-8134-11eb-8e71-2d955b6eba19.png)

While restarting CARP I can see following error messages in /var/log/system.log:
```
/firewall_virtual_ip.php: The command '/sbin/ifconfig 'em0' inet '192.168.0.28' -alias' failed to execute
/firewall_virtual_ip.php: The command '/sbin/ifconfig vhid '6' advskew '0' advbase '1' pass '123'' returned exit code '1', the output was 'ifconfig: interface vhid does not exist'
/firewall_virtual_ip.php: The command '/sbin/ifconfig '192.168.0.28'/'24' alias vhid '6'' returned exit code '1', the output was 'ifconfig: interface 192.168.0.28/24 does not exist'
```
![grafik](https://user-images.githubusercontent.com/26787995/110550588-41f83480-8134-11eb-8c69-42e34f9ce177.png)

Indeed, when I try to add the alias IP manually, It doesn't work either:
![grafik](https://user-images.githubusercontent.com/26787995/110550529-25f49300-8134-11eb-9116-81c8f3fbc6d4.png)

**additional information**
Versions | OPNsense 21.7.a_115-amd64FreeBSD 12.1-RELEASE-p13-HBSDOpenSSL 1.1.1j  16 Feb 2021

**Comment by fichtner** [comment]
Can you try this patch?

    # opnsense-patch 9fddac6

I'm not sure about the other issue but at least in the CARP case we miss the interface which got deleted by accident.

Thanks for running the development version ❤️

**Comment by lattera** [comment]
I believe this was a regression in 00e6895821ed0d8c7d18d5456102951c69a8933e as noted in this comment: https://github.com/opnsense/core/commit/00e6895821ed0d8c7d18d5456102951c69a8933e#commitcomment-47892107

**Comment by lattera** [comment]
Though this is tangential to the issue at hand, what would you like to call it?

**Comment by fichtner** [comment]
I just wish we could focus on work at hand. Providing a bug report is great, providing a PR too. Leaving comments everywhere is not  .

**Comment by lattera** [comment]
I couldn't disagree less. But whatever.

**Comment by fichtner** [comment]
Least you could do is test the patch, but yes whatever. Let’s have a pointless debate instead. 🤷‍♂️

**Comment by lattera** [comment]
Already planned testing the patch. Got a build going now. :)

**Comment by lattera** [comment]
Tested successfully.

**Comment by fichtner** [comment]
Ok, thanks!

**Comment by phhutter** [comment]
Yes, your patch fixes the issue.
All CARP interfaces are online and the errors are gone!
