### ISSUE TITLE
Cannot Delete Backend Pool in haproxy

### ISSUE THREAD

**Issue by drinn** [opnsense/core#4799]
When trying to delete a backend pool from haproxy -> settings -> virtual services -> backend pools, one of my backend pools says that it cannot deleted because the item "is in use by" a few items in the "Rules" section.

The backend pool that I'm trying to delete, however, does not currently have any of those rules in its configuration.

Please let me know if you would like me to gather any other information and I'll be happy to provide it to you.

EDIT: I'm currently running the latest release version of opnsense - OPNsense 21.1.3-amd64

**Comment by sorano** [comment]
This is related to Plugins and not Core. https://github.com/opnsense/plugins
Please close and open it there (or move if possible).

Do you have the same problem regarding of which backend you try to remove?
Otherwise I'd say a copy of your config would be needed in order to troubleshoot.

**Comment by drinn** [comment]
I am able to create a clone of a backend that I cannot delete and remove the clone just fine. I am just unable to remove the original ones.

I will recreate this ticket over in Plugins. Thanks!
