### ISSUE TITLE
Menu does not expand for 'Services: UPnP & NAT-PMP'

### ISSUE THREAD

**Issue by sjorge** [opnsense/core#48]
When opening the 'Services: UPnP & NAT-PMP ' page the menu auto-colapses
http://i.imgur.com/iazrHdr.png

**Comment by fichtner** [comment]
Already fixed and part of the upcoming 15.1.6, see https://github.com/opnsense/core/commit/99a8f51d6b9eac6d772af5539e9b9c17b619accc
