### ISSUE TITLE
No Wireless Interfaces on 11-CURRENT

### ISSUE THREAD

**Issue by lattera** [opnsense/core#480]
Because of the way wireless is now exposed in 11-CURRENT, custom OPNSense builds based on FreeBSD 11-CURRENT do not show any available wireless devices. I haven't looked at OPNSense's code at all, but it likely queries the interfaces based on the output from `ifconfig`. When on 11-CURRENT, OPNSense should search for wireless interfaces by querying `sysctl net.wlan.devices`.

My next build of OPNSense based on HardenedBSD will use 11-CURRENT. So this is a blocker for my next release.

**Comment by fichtner** [comment]
Is there a (semi-)official document that describes the changes in detail?

I will have to tag this enhancement and not provide an ETA until I know the scope of this rework. :(

**Comment by gonzopancho** [comment]
Side-effect of the new ifnet KPI. The basic idea is that the struct ifnet remains only in the wlan(4) driver itself, while all underlying hardware drivers aren't aware of struct ifnet. The stack is already converted, drivers are still in-process.  See also: D2655.

**Comment by lattera** [comment]
@fichtner, no worries about time. If you show me where to look, I'd be happy to do the work and submit a pull request.

**Comment by fichtner** [comment]
Timelines changed. Needs 10.3 to compile 11 anyway as 10.2 doesn't work... scheduled for after 16.7.

**Comment by AdSchellevis** [comment]
note to self:

`ifconfig wlan0 create wlandev ath0; ifconfig wlan0 ether`

**Comment by fichtner** [comment]
since fixed on master
