### ISSUE TITLE
No working dashboard title (links) after update to 21.1.3

### ISSUE THREAD

**Issue by jokay** [opnsense/core#4802]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues and I am convinced that mine is new.

**Describe the bug**

After the update to **21.1.3** the dashboard title (links) do no longer work correctly.

**To Reproduce**

Update to **21.1.3** and have a look at the dashboard.

**Expected behavior**

Working dashboard title (links).

**Describe alternatives you considered**

Live with it.

**Screenshots**

![screen-1](https://user-images.githubusercontent.com/18613935/110848700-adfea800-82ae-11eb-8b70-29489335cf68.png)

![screen-2](https://user-images.githubusercontent.com/18613935/110848728-b2c35c00-82ae-11eb-939d-b57abb81671d.png)

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 21.1.3 (amd64, LibreSSL).

**Comment by fichtner** [comment]
Also need to search for closed issues ;)
