### ISSUE TITLE
API call firmware/status fails after upgrade to 21.1.3

### ISSUE THREAD

**Issue by astrandb** [opnsense/core#4805]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X ] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X ] I have searched the existing issues and I am convinced that mine is new.

**Describe the bug**

The API /api/core/firmware/status is not working properly after upgrade to 21.1.3. It fails with the message: 
`Firmware status check was aborted internally. Please try again.` I have tried again many times with the same result.
After a manual button press on "Check for updates" the API call works as expected but I suspect that "Check for updates" is never executed by the API call. 

**To Reproduce**

1. Update to 21.1.3
2. DO NOT press check for upgrades button or link
3. Send API call /api/core/firmware/status

**Expected behavior**

The API call should report when there are new updates/upgrades available

**Describe alternatives you considered**
Manually logging into each router every day and clicking on "Check for updates" - not a very attractive workaround

OPNsense 21.1.3 (amd64, OpenSSL).

**Comment by fichtner** [comment]
Need to call check before status always. Status might be going away too, superseded by info call.

**Comment by astrandb** [comment]
OK, thank you. 
After some trials and errors i found out that a POST to /api/core/firmware/check initiated the upgrade check. 
I fully respect that you have other priorities than documenting the details of the API but I would appreciate if you try to remember to flag this type of breaking changes in the changelog. Or perhaps you did and I missed it.
I am over all very happy with OPNsense and I use the API monitor the firmware status of our 12 routers around the country.

**Comment by fichtner** [comment]
I added a note here https://github.com/opnsense/changelog/commit/5b3ee939fbc1

Docs only have this at the moment: https://github.com/opnsense/docs/commit/70166cc65 so note that "upgrade" call is now "update" does not take any arguments to simplify the process.

I will think of a way to make the status more robust since the check now runs in the background asynchronously like the updates itself.


Cheers,
Franco

**Comment by astrandb** [comment]
In the meantime I will send a check call every 24h and a status call 
every 4h, without synchronization.. Then I will get notification of pending updates/upgrades within 28 hours which is good enough for me.

**Comment by fichtner** [comment]
9541c1f9632afce9ad4bf3fdb74de3e18c767912 63af98ed5b9dc10a0ebfa8df02a136691a2f65dc 9541c1f9632afce9ad4bf3fdb74de3e18c767912

Long story short if you run the status call as POST it will now do a synchronous check on the firmware within the constraints of the eventual backend timeout. We expect this to be part of 21.1.4.

**Comment by astrandb** [comment]
OK thanks. I'll patch and verify later today.

**Comment by fichtner** [comment]
Thanks, clean backport is 0a42a196625a188
