### ISSUE TITLE
Allow to create fe80::1 gateway on various interfaces

### ISSUE THREAD

**Issue by muchahagrande** [opnsense/core#4809]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues and I am convinced that mine is new.

**Is your feature request related to a problem? Please describe.**

I have a case of not routing IPv6.
My ISP doesn't allows me to bridge the GPON router they gave me. So I'm using it with a DMZ pointing to OPNSense. Double IPv4 NAT.
Recently they implemented IPv6 and they are giving me a /64 prefix.
If I connect my PC directly to the ISPs router, I can use IPv6 without a problem. But when I set IPv6 on OPNSense WAN I can't connect with IPv6 from inside the network. I can ping google from WAN but not from LAN or the hosts inside the net.
The ISP router passes to OPNSense, via DHCPv6 an IP and fe80::1 as the gateway.
Digging into the case, I found this [https://blogs.infoblox.com/ipv6-coe/fe80-1-is-a-perfectly-valid-ipv6-default-gateway-address](url)
It says that if I set gateway to fe80::1 on every interface, IPv6 will work fine, but when I try to create the gateway for LAN it doesn't allow me because fe80::1 is already defined as gateway for WAN.

**Describe the solution you like**

The solution I'm asking for is the possibility to create fe80::1 as gateway for different interfaces given that it is a special link-local address that exists on every interface.

**Comment by muchahagrande** [comment]
@AdSchellevis , I have a problem with my GPON router that is not assigning OPNSense correct prefix and IPv6 addresses,
marjohn56 and Maurice helped me at the forum to find out that the problem is not related to gateway but to this behavior, so this issue may be closed

**Comment by AdSchellevis** [comment]
@muchahagrande ok, thanks for letting us know. closing the issue then.
