### ISSUE TITLE
IPsec status on GUI not correct

### ISSUE THREAD

**Issue by 8191** [opnsense/core#481]
Even if there are connected IPsec tunnels, the status on the GUI (e.g. dashboard widget or Status --> IPsec) always shows the tunnels as inactive.

How to verify: `ipsec status` lists established SAs, but dashboard widget shows 0 active tunnels and IPsec status lists tunnel in status "x N".

 OPNsense 15.7.18_1-i386

**Comment by fichtner** [comment]
Can you try 15.7.20, the IPsec status backend was completely rewritten in 15.7.19.

**Comment by fraenki** [comment]
On 15.7.20 the IPsec status looks good, at least in my case.

**Comment by 8191** [comment]
I'll have a look at 15.7.20. Thanks.

**Comment by 8191** [comment]
Looks much better on 15.7.20.
