### ISSUE TITLE
Dashboard widget titles

### ISSUE THREAD

**Issue by HNJAMeindersma** [opnsense/core#4810]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I have searched the existing issues and I am convinced that mine is new.

**Describe the bug**

Since update 21.1.3 the dashboard widget titles seem to be not translating to their "pretty title". Also the link behind the dashboard widget titles is incorrect and widget title "system_information_title_link" directs to "https://x.x.x.x/system_information_title_link".

**To Reproduce**

Updated from OPNsense 21.1.2-amd64 to OPNsense 21.1.3-amd64.

**Expected behavior**

Dashboard widget title placeholders should be replaced by their clean variant on the selected UI language.

**Describe alternatives you considered**

Reboot did not fix the issue. Same for a fresh cache-less and cookie-less browser.

**Screenshots**

![Screenshot-20210313111356-724x220](https://user-images.githubusercontent.com/26845295/111026908-456a1500-83ed-11eb-9b43-309565270759.png)

**Relevant log files**

None

**Additional context**

None

**Environment**

OPNsense 21.1.3-amd64
FreeBSD 12.1-RELEASE-p14-HBSD
OpenSSL 1.1.1j 16 Feb 2021
Intel(R) Core(TM) i3-5005U CPU @ 2.00GHz

**Comment by AdSchellevis** [comment]
duplicate https://github.com/opnsense/core/issues/4795
