### ISSUE TITLE
Firewall log widget: Selection/filter not working with renamed interface name

### ISSUE THREAD

**Issue by wormgat** [opnsense/core#4815]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I have searched the existing issues and I am convinced that mine is new.

**Describe the bug**
After renaming "WAN" interface to "WANCBL" the filter is not longer working. Selecting "All" or renaming interface back to "WAN" activates the filter again:
A clear and concise description of what the bug is, including last known working version (if any).

*Tip*: to validate your setup was working with the previous version, use opnsense-revert (https://docs.opnsense.org/manual/opnsense_tools.html#opnsense-revert)

**To Reproduce**

1. Go to 'Lobby / Dashboard / log_title'
2. Click on 'pencil'
3. Click on 'Interfaces to display:'
1.  Select renamed WAN interface

**Expected behavior**
Only entries relating to the selected interface should be shown.

**Screenshots**

Tried to attach the sreenshots from my incomplete ticket #4806, but it shows the following messsage: "Somthing went really wrong, and we can't process that file."
I am sorry for that, I din't learn to operate github, maybe i am to stupid.

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 21.1.3 (amd64, OpenSSL).
APU.2C4 GX-3^1 TC Quad Core
4 GB RAM, 16GB mSATA SSD

**Comment by wormgat** [comment]
Firewall Log Widget still not fixed concerning selection of interface which is renamed.

**Comment by fichtner** [comment]
I’m not sure how you think this works, but if the code didn’t hit the project yet how can something be opportunistically solved in a coincidentally timed release?

**Comment by wormgat** [comment]
I do not know how it works, maybe that's the problem. I just wanted to give feedback. I beg your pardon if I made a wrong impression.
