### ISSUE TITLE
IPsec phase 1 encryption algorithm not shown correctly in GUI

### ISSUE THREAD

**Issue by 8191** [opnsense/core#482]
When modifying and existing IPsec phase 1 entry, which uses AES with <256 bits keysize, the GUI always selects "256 bits" keys size for AES. If not recognized by the user the keysize value is saved with 256 bits instead of the old value.

How to reproduce:
1. Create an IPsec phase 1 entry with AES e.g. 128 bits and save the entry.
2. Edit the phase 1 entry in the IPsec GUI
3. The GUI shows "256 bits" for AES keysize, even 128 is configured

 OPNsense 15.7.18_1-i386

**Comment by AdSchellevis** [comment]
duplicate, closed in dev, more info https://github.com/opnsense/core/issues/350 and https://github.com/opnsense/core/commit/10a0fd8e56d2d28aa78fcb2be3e6376c15650d98
