### ISSUE TITLE
IPS: Suricata Errors in log when enabling new Threatfox feed

### ISSUE THREAD

**Issue by sorano** [opnsense/core#4821]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I have searched the existing issues and I am convinced that mine is new.

**Describe the bug**
I decided to try out the new abuse.ch/ThreatFox feed that was added in 21.1.3

After enabling and downloading the ruleset I got errors in suricata.log

**To Reproduce**

1. Enable and download the abuse.ch/ThreatFox ruleset and save
2. Click on Log file
3. See errors in log file

**Expected behavior**
No error logs would be expected

**Relevant log files**
> Mar 14 20:50:20 fw01 suricata[75199]: [100127] <Error> -- [ERRCODE: SC_ERR_INVALID_SIGNATURE(39)] - bad input for keyword content: '"'
Mar 14 20:50:20 fw01 suricata[75199]: [100127] <Error> -- [ERRCODE: SC_ERR_INVALID_SIGNATURE(39)] - error parsing signature "alert http $HOME_NET any -> $EXTERNAL_NET any (msg:"ThreatFox botnet C2 traffic (url - confidence level: 50%)"; flow:established,from_client; http.method; content:"GET"; http.uri; content:""; depth:0; nocase; http.host; content:"nyqualitypizza.top"; depth:18; isdataat:!1,relative; reference:url, threatfox.abuse.ch/ioc/2917/; target:src_ip; metadata: confidence_level 50, first_seen 2021_03_09; classtype:trojan-activity; sid:90002917; rev:1;)" from file /usr/local/etc/suricata/opnsense.rules/abuse.ch.threatfox.rules at line 472
Mar 14 20:50:20 fw01 suricata[75199]: [100127] <Error> -- [ERRCODE: SC_ERR_INVALID_SIGNATURE(39)] - bad input for keyword content: '"'
Mar 14 20:50:20 fw01 suricata[75199]: [100127] <Error> -- [ERRCODE: SC_ERR_INVALID_SIGNATURE(39)] - error parsing signature "alert http $HOME_NET any -> $EXTERNAL_NET any (msg:"ThreatFox botnet C2 traffic (url - confidence level: 50%)"; flow:established,from_client; http.method; content:"GET"; http.uri; content:""; depth:0; nocase; http.host; content:"againstpolicebrutality.top"; depth:26; isdataat:!1,relative; reference:url, threatfox.abuse.ch/ioc/2918/; target:src_ip; metadata: confidence_level 50, first_seen 2021_03_09; classtype:trojan-activity; sid:90002918; rev:1;)" from file /usr/local/etc/suricata/opnsense.rules/abuse.ch.threatfox.rules at line 473
Mar 14 20:50:20 fw01 suricata[75199]: [100127] <Error> -- [ERRCODE: SC_ERR_INVALID_SIGNATURE(39)] - bad input for keyword content: '"'
Mar 14 20:50:20 fw01 suricata[75199]: [100127] <Error> -- [ERRCODE: SC_ERR_INVALID_SIGNATURE(39)] - error parsing signature "alert http $HOME_NET any -> $EXTERNAL_NET any (msg:"ThreatFox botnet C2 traffic (url - confidence level: 75%)"; flow:established,from_client; http.method; content:"GET"; http.uri; content:""; depth:0; nocase; http.host; content:"monkeyplanet.net"; depth:16; isdataat:!1,relative; reference:url, threatfox.abuse.ch/ioc/2800/; target:src_ip; metadata: confidence_level 75, first_seen 2021_03_08; classtype:trojan-activity; sid:90002800; rev:1;)" from file /usr/local/etc/suricata/opnsense.rules/abuse.ch.threatfox.rules at line 529

**Environment**

OPNsense 21.1.3-amd64
FreeBSD 12.1-RELEASE-p14-HBSD
OpenSSL 1.1.1j 16 Feb 2021

Running Suricata on WAN, all offloading disabled.

**Comment by dantichrist69** [comment]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:
 

- [ ] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [ ] I have searched the existing issues and found this one so I added the errors from my log to it.

**Describe the bug**
I decided to try out the new abuse.ch/ThreatFox feed that was added in 21.1.3

After enabling and downloading the ruleset I got errors in suricata.log

**To Reproduce**

1. Enable and download the abuse.ch/ThreatFox ruleset, and save.
2. Click on Log file.
3. See errors in log file.

**Expected behavior**
No error logs are expected.

**Relevant log files**

> 2021-03-26T21:10:16 | suricata[33294] | [100111] <Error> -- [ERRCODE: SC_ERR_INVALID_SIGNATURE(39)] - error parsing signature "alert http $HOME_NET any -> $EXTERNAL_NET any (msg:"ThreatFox botnet C2 traffic (url - confidence level: 75%)"; flow:established,from_client; http.method; content:"GET"; http.uri; content:""; depth:0; nocase; http.host; content:"monkeyplanet.net"; depth:16; isdataat:!1,relative; reference:url, threatfox.abuse.ch/ioc/2800/; target:src_ip; metadata: confidence_level 75, first_seen 2021_03_08; classtype:trojan-activity; sid:90002800; rev:1;)" from file /usr/local/etc/suricata/opnsense.rules/abuse.ch.threatfox.rules at line 1344 |  
> -- | -- | -- | --
> 2021-03-26T21:10:16 | suricata[33294] | [100111] <Error> -- [ERRCODE: SC_ERR_INVALID_SIGNATURE(39)] - bad input for keyword content: '"' |  
> 2021-03-26T21:10:16 | suricata[33294] | [100111] <Error> -- [ERRCODE: SC_ERR_INVALID_SIGNATURE(39)] - error parsing signature "alert http $HOME_NET any -> $EXTERNAL_NET any (msg:"ThreatFox botnet C2 traffic (url - confidence level: 50%)"; flow:established,from_client; http.method; content:"GET"; http.uri; content:""; depth:0; nocase; http.host; content:"againstpolicebrutality.top"; depth:26; isdataat:!1,relative; reference:url, threatfox.abuse.ch/ioc/2918/; target:src_ip; metadata: confidence_level 50, first_seen 2021_03_09; classtype:trojan-activity; sid:90002918; rev:1;)" from file /usr/local/etc/suricata/opnsense.rules/abuse.ch.threatfox.rules at line 1288 |  
> 2021-03-26T21:10:16 | suricata[33294] | [100111] <Error> -- [ERRCODE: SC_ERR_INVALID_SIGNATURE(39)] - bad input for keyword content: '"' |  
> 2021-03-26T21:10:16 | suricata[33294] | [100111] <Error> -- [ERRCODE: SC_ERR_INVALID_SIGNATURE(39)] - error parsing signature "alert http $HOME_NET any -> $EXTERNAL_NET any (msg:"ThreatFox botnet C2 traffic (url - confidence level: 50%)"; flow:established,from_client; http.method; content:"GET"; http.uri; content:""; depth:0; nocase; http.host; content:"nyqualitypizza.top"; depth:18; isdataat:!1,relative; reference:url, threatfox.abuse.ch/ioc/2917/; target:src_ip; metadata: confidence_level 50, first_seen 2021_03_09; classtype:trojan-activity; sid:90002917; rev:1;)" from file /usr/local/etc/suricata/opnsense.rules/abuse.ch.threatfox.rules at line 1287 |  
> 2021-03-26T21:10:16 | suricata[33294] | [100111] <Error> -- [ERRCODE: SC_ERR_INVALID_SIGNATURE(39)] - bad input for keyword content: '"'
> 

**Environment**

OPNsense 21.1.3-amd64
FreeBSD 12.1-RELEASE-p14-HBSD
OpenSSL 1.1.1j 16 Feb 2021

Running Suricata on WAN and LAN, all offloading is disabled.

**Comment by kulikov-a** [comment]
obvious syntax errors in rules imho

**Comment by fichtner** [comment]
I reckon this has been fixed....
