### ISSUE TITLE
show rulerumbers Firewall->rules

### ISSUE THREAD

**Issue by colttt** [opnsense/core#4827]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues and I am convinced that mine is new.

**Is your feature request related to a problem? Please describe.**

Hello, 
it woul be very nice if we see the rule numbers in Firewall->Rules->Floating(whatever).

It's very usefull when you talk to a collegue and ask something about a specific rule. It can take a long time to find it.

**Describe the solution you like**
show the rulenumbers in rules for a better overview and its better searchable

**Comment by AdSchellevis** [comment]
![image](https://user-images.githubusercontent.com/9783985/111172718-58741500-85a6-11eb-97cb-1f3be55bbd8d.png)
 click the question mark and the hash numbers appear...

**Comment by colttt** [comment]
Ehm, no.. That is not what I ask for ;-)
I dont want to saiy, lets chck rule "3e1207066c64b3b4dad67a32443fabcd", I want to say "lets check rule 15" 
something like that:
![image](https://user-images.githubusercontent.com/10084871/111174846-14820f80-85a8-11eb-8df6-7d19d49ce4fe.png)

**Comment by AdSchellevis** [comment]
The screen already is full enough as it is, we generally advise to use proper descriptions and categories on rules which also help a lot in communication among peers.

**Comment by mimugmail** [comment]
Just gives the rule a name or number in description

**Comment by fichtner** [comment]
Nothing to do here as discussed.
