### ISSUE TITLE
DHCP server does not provide DNS server in bootp ACK message if not configured explicitly

### ISSUE THREAD

**Issue by 8191** [opnsense/core#483]
The DHCP server's GUI mentions, that it provides the firewall's IP as a DNS server if the firewall is configured as DNS resolver or forwarder:
_NOTE: leave blank to use the system default DNS servers - this interface's IP if DNS forwarder is enabled, otherwise the servers configured on the General page._

I've configured a DNS resolver and a DHCP server with empty DNS fields, but the DHCP server does not offer an DNS server. It's required to put the firewall's IP into the DNS server field of the DHCP server to provide a DNS server to DHCP clients.

 OPNsense 15.7.18_1-i386

**Comment by fichtner** [comment]
What is your WAN setup like? Did you change DNS options under System: Settings: General?

**Comment by 8191** [comment]
I receive my WAN DNS via DHCP from my ISP. The DNS settings are empty at Settings: General.

**Comment by fichtner** [comment]
There is something consistent in your setup, unbound not starting correctly, then dns not being picked up by dhcp. Need to get you on 15.7.20, then get to the bottom of this. Could also try dnsmasq forwarder in the GUI. It has been in the code longer and may have superior stability.

**Comment by fichtner** [comment]
Manuel, is this still happening on 15.7.22?

**Comment by 8191** [comment]
Yes it's still happening. But this time the _globally configured_ DNS server (`/etc/resolv.conf`) is provided to DHCP clients instead of an empty DNS field.
