### ISSUE TITLE
Update 20.1.3 broke my General log, and the widget

### ISSUE THREAD

**Issue by Taomyn** [opnsense/core#4830]
Since I applied the latest patch I now get

![image](https://user-images.githubusercontent.com/4365929/111175094-58751480-85a8-11eb-8474-d99f2a1728ec.png)
![image](https://user-images.githubusercontent.com/4365929/111175136-64f96d00-85a8-11eb-8a83-467fc369a082.png)

```
[547c6f90-d720-4689-bb8c-ceb9d01b0188] Script action failed with Command '/usr/local/opnsense/scripts/systemhealth/queryLog.py --limit '200' --offset '0' --filter '' --module 'core' --filename 'system'' returned non-zero exit status 1. at Traceback (most recent call last): File "/usr/local/opnsense/service/modules/processhandler.py", line 479, in execute stdout=output_stream, stderr=error_stream) File "/usr/local/lib/python3.7/subprocess.py", line 363, in check_call raise CalledProcessError(retcode, cmd) subprocess.CalledProcessError: Command '/usr/local/opnsense/scripts/systemhealth/queryLog.py --limit '200' --offset '0' --filter '' --module 'core' --filename 'system'' returned non-zero exit status 1.
```

And the General log will no longer display anything. I attempted to restart the all the services of the firewall and I was left with:

```
Enter an option: 11

Writing firmware setting...done.
Writing trust files...done.
Configuring login behaviour...done.
Configuring CRON...done.
Setting timezone...done.
Setting hostname: bart.star-one.co.uk
Generating /etc/hosts...done.
Generating /etc/resolv.conf...done.
Configuring loopback interface...done.
Creating wireless clone interfaces...done.
Configuring VLAN interfaces...done.
Configuring DMZ interface...done.
Configuring GUEST interface...done.
Configuring LAN interface...done.
Configuring WAN interface...done.
Creating IPsec VTI instances...done.
Creating OpenVPN instances...done.
Setting up routes...done.
Configuring firewall........done.
Starting PFLOG...done.
Starting DHCPv4 service...done.
Starting router advertisement service...done.
Starting NTP service...done.
Configuring OpenSSH...done.
Starting Unbound DNS...done.
Starting web GUI...done.
Syncing OpenVPN settings...
```

So I used the console to log in and perform a reboot which brought the firewall back to life but the General log is still broken.

OPNsense 21.1.3_3-amd64
FreeBSD 12.1-RELEASE-p14-HBSD
OpenSSL 1.1.1j 16 Feb 2021

_Originally posted by @Taomyn in https://github.com/opnsense/core/issues/4795#issuecomment-798898349_

**Comment by kulikov-a** [comment]
have you tried to clear the General log in  System: Log Files: General ?
and what if you run this via shell?
`/usr/local/opnsense/scripts/systemhealth/queryLog.py --limit '200' --offset '0' --filter '' --module 'core' --filename 'system'`

**Comment by Taomyn** [comment]
@kulikov-a 

I ran the command first and got

```
root@bart:~ # /usr/local/opnsense/scripts/systemhealth/queryLog.py --limit '200' --offset '0' --filter '' --module 'core' --filename 'system'
Traceback (most recent call last):
  File "/usr/local/opnsense/scripts/systemhealth/queryLog.py", line 94, in <module>
    for rec in reverse_log_reader(filename):
  File "/usr/local/opnsense/site-python/log_helper.py", line 61, in reverse_log_reader
    data = input_stream.read(block_size) + data
  File "/usr/local/lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xac in position 61914: invalid start byte


```

Then I cleared the log, why I didn't think of this in the first place is beyond me, and now all is good.

```
root@bart:~ # /usr/local/opnsense/scripts/systemhealth/queryLog.py --limit '200' --offset '0' --filter '' --module 'core' --filename 'system'
{"filters":"","rows":[{"timestamp":"2021-03-15T20:24:01","parser":"SysLogFormat","process_name":"syslog-ng[23571]","rnum":2,"line":"syslog-ng starting up; version='3.31.1'"},{"timestamp":"2021-03-15T20:24:01","parser":"SysLogFormat","process_name":"syslogd","rnum":3,"line":"kernel boot file is \/boot\/kernel\/kernel"}],"total_rows":2,"origin":"system"}

```

Thanks for the help.

**Comment by AdSchellevis** [comment]
probably garbage in the log output, maybe after a filesystem corruption. https://github.com/opnsense/core/commit/94a8906ef94ce6d0fa7ea878d83986479c1d40ca ignores what it can't read.

**Comment by Taomyn** [comment]
Hi @AdSchellevis after rebooting my firewall last night I just noticed that it's happened again, but before I flushed the log I thought I would try the patch - it helps and it now shows and the strange line is always at the top:

![image](https://user-images.githubusercontent.com/4365929/111652899-bd7a7580-8807-11eb-904e-dea9328451b4.png)
![image](https://user-images.githubusercontent.com/4365929/111653312-1ba75880-8808-11eb-8679-952f8c532bb3.png)


When ran the command you request before, this is the first entry:

`{"filters":"","rows":[{"timestamp":null,"parser":null,"process_name":"","rnum":1,"line":"CLOG\u0000\u0000\u0000\u0000\ufffd\ufffd\u0001\u0000\ufffd\u000f"}
`

I have no clue where it's coming from.

**Comment by AdSchellevis** [comment]
@Taomyn likely disc corruptions, the rotating log files are more sensitive as well. My suggestion would be to switch from circular logs to standard logs (System -> Settings -> Logging  : Disable circular logs), which is the default nowadays

**Comment by Taomyn** [comment]
> @Taomyn likely disc corruptions, the rotating log files are more sensitive as well. My suggestion would be to switch from circular logs to standard logs (System -> Settings -> Logging : Disable circular logs), which is the default nowadays

It's not the disk, it checks out fine. Have switched off circular logging as you recommended and will see how it goes, thanks.
