### ISSUE TITLE
Policy install on routed ipsec VPNS

### ISSUE THREAD

**Issue by smalchow** [opnsense/core#4838]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues and I am convinced that mine is new.

**Describe the bug**

Not a bug only a possible improvement

It is possible to keep "Install policy" enabled on routed IPSec VPNs, the second you do this however, you loose connectivity to the box.

**To Reproduce**

Create a routed VPN with "install policy" ticked and start it

**Expected behavior**

Though it is strictly speak not a bug, but maybe lets say a convenience thing - i would expect that the policy install on routed VPNS does not occur since it is not needed by design.
It is mentioned in the documentation properly and i found this only because we were testing several setups and once i forgot to untick.

**Describe alternatives you considered**

No workaround, just follow the documentation, but it could potentially save alot of pain for a few people especially if the box is remote

**Screenshots**

n/a

**Relevant log files**

n/a

**Additional context**

n/a

**Environment**

OPNsense 21.1.3_3-amd64
FreeBSD 12.1-RELEASE-p14-HBSD
OpenSSL 1.1.1j 16 Feb 2021

with 2 patches installed from here

https://github.com/opnsense/core/issues/4700

**Comment by AdSchellevis** [comment]
It might be good to add a validation in the ui, silencing the `installpolicy` without the ui reflecting it isn't preferable, other then that I haven't seen situations where installpolicy was a good idea to set on VTI.
