### ISSUE TITLE
unbound cannot be started via Status: Services

### ISSUE THREAD

**Issue by 8191** [opnsense/core#484]
When stopping unbound via Status: Services, it cannot be started again via the "play" button. Also the logs do not contain an error after clicking the play button.

To start unbound again one needs to go to Services: DNS Resolver, save and then apply the unchanged settings.

**Comment by fichtner** [comment]
Manuel, is this still the case?

**Comment by 8191** [comment]
@fichtner ahm... Actually I cannot find the _Status: Services_ page anymore in current master tree... :confused:

**Comment by fichtner** [comment]
System: Diagnostics: Services :)

**Comment by 8191** [comment]
@fichtner  ah, thanks...

Yes it's still the case. The problem is, that unbound had no start command listed in the start service logic. Fixed with #513.

**Comment by fichtner** [comment]
@8191 thanks :)
