### ISSUE TITLE
[FR]IDS/IPS: Drop event logging switch and alert details

### ISSUE THREAD

**Issue by kulikov-a** [opnsense/core#4841]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues and I am convinced that mine is new.

**Is your feature request related to a problem? Please describe.**

Hi!
now if the IPS drops the packet two lines appear in the Alerts tab: one for the Alert event and the second for the Drop event.
both contain the same information although the Alert event may contain information about the payload
![IDS_de0](https://user-images.githubusercontent.com/36099472/111654816-279c1600-881a-11eb-8c4c-f00638f133d1.PNG)

**Describe the solution you like**

could you please consider adding an Drop events logging switch. and adding debug info display for Drop events?

![IDS_de1](https://user-images.githubusercontent.com/36099472/111655148-75188300-881a-11eb-9f0f-d661cbab9a3e.PNG)
![IDS_de2](https://user-images.githubusercontent.com/36099472/111655171-7a75cd80-881a-11eb-8fd5-6b4f8eef81b6.PNG)

Thanks!
**Describe alternatives you considered**

Just disable drop events logging in suricata.yaml template:
`        
     - drop:
            alerts: yes      # log alerts that caused drops
            flows: start     # start or all: 'start' logs only a single drop
                             # per flow direction. All logs each dropped pkt.

`

**Additional context**

Add any other context or screenshots about the feature request here or links to relevant forum thread or similar

**Comment by AdSchellevis** [comment]
I think there was another ticket about this a long time ago and there was some issue with solving it without side affects, so I'm a bit cautious here....

**Comment by kulikov-a** [comment]
@AdSchellevis 
thanks. hmm. searched before making the request. perhaps not enough. I'll try again

**Comment by AdSchellevis** [comment]
no problem, not saying we shouldn't look at this, just cautious ;)

**Comment by kulikov-a** [comment]
) thanks. I see the commit when it appeared but unfortunately there is no additional information why
https://github.com/opnsense/core/commit/573612d48ebe6142015befbe558a2c9829e85fcb#diff-61dc886561c7b1530e89119eab64a828fb1dc9f63768d4d307a99063c73316e2

**Comment by AdSchellevis** [comment]
Maybe it crosses my mind one of these days, vaguely remember there was "something" with it.

**Comment by kulikov-a** [comment]
in any case, this is another reason to once again compare the behavior with enabled and disabled logging. I will test it for a while. thanks!
