### ISSUE TITLE
Time notation in Reporting:Traffic and Dashboard traffic widget always 12-hours

### ISSUE THREAD

**Issue by mjanssens** [opnsense/core#4852]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x]  I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues and I am convinced that mine is new.

**Describe the bug**
Time notation in Reporting:Traffic and Dashboard traffic widget always is 12-hours, so am-pm, not 24-hours notation

**To Reproduce**

1. Go to 'Reporting: Traffic'
2. View time notation below graph
3. Or see the traffic widget in Dashboard

**Expected behavior**
The time zone on my OPNsense instance is Europe/Amsterdam
The time notation in other gui areas is 24-hours. Only in the traffic graphs the notation is English so 12-hours and am-pm.

Software version used and hardware type if relevant, e.g.:
OPNsense 21.1.3-amd64

Minor detail, so no hurry, keep up your good work ;-)

**Comment by AdSchellevis** [comment]
https://github.com/opnsense/core/commit/3d3810b42d1664087594ecc8fadc43568056220c should fix the 24hour format, which is indeed the default in other sections as well. For some reason it doesn't appear to be very trivial to change this in chart.js, a generic change to change the format for all cases where data is formatted would be practical.
