### ISSUE TITLE
wrong status in carp_status.php

### ISSUE THREAD

**Issue by colttt** [opnsense/core#4854]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues and I am convinced that mine is new.

**Describe the bug**

I've setup an HA, it works fine, but it looks like that the status of the carp is broken

**To Reproduce**

Create an HA with 7 virtual IPs/Carp-IPs in 4 of them it's fine in the rest there is something wrong (see pictures)
On FW-Master it looks like:
![fw_master](https://user-images.githubusercontent.com/10084871/111980098-24e53d80-8b06-11eb-86b4-a5192789c40a.png)

on the Backup machine it looks like:
![fw_backup](https://user-images.githubusercontent.com/10084871/111980125-2d3d7880-8b06-11eb-87a7-dc286b90c21a.png)

**Expected behavior**

a working status overview ;-) it should show a consistent status

**Relevant log files**
if you need logfiles please tell me which one

**Environment**

OPNsense 20.7.8-amd64
FreeBSD 12.1-RELEASE-p12-HBSD
OpenSSL 1.1.1j  16 Feb 2021
Intel(R) Xeon(R) CPU E5-2620 v4 @ 2.10GHz (16 cores)

**Comment by AdSchellevis** [comment]
Usually the cause of configuration/cabling issues, best keep community support questions and discussions on the forum.

**Comment by colttt** [comment]
ok got it, some VLANs are still pointed to the current FW, tomorrow we switch to OPNsense, that includes all VLANs and that should fix this
