### ISSUE TITLE
DHCP - Cannot save settings when static lease exists within the DHCP range

### ISSUE THREAD

**Issue by dsimoes** [opnsense/core#4855]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues and I am convinced that mine is new.

**Describe the bug**

With 21.1, we are now able to set static leases with IP Address within the DHCP range. (See #4447 )
But one validation remained on the DHCP service configuration that prevents saving and updating the config form if a static lease exists. Error message:

The following input errors were detected:
- The DHCP range cannot overlap any static DHCP mappings.

**To Reproduce**

1. On DHCPv4, set a new static lease with IP Address inside the DHCP range
2. Go back to DHCPv4 service configuration and try to click "Save"
4. See validation error that prevents saving settings.

**Expected behavior**

This validation should be removed and we should be able to update the DHCPv4 settings while having the static lease with an IP address within the DHCP range.

**Environment**

Software version used:

OPNsense 21.1.2-amd64

**Comment by mimizone** [comment]
is that something fixed in recent releases that allow static lease in the DHCP range? thanks.

**Comment by fichtner** [comment]
Yes, but it leads to isc-dhcpd giving out leases for the reserved IP address anyway.
