### ISSUE TITLE
URL table alias not coping with special characters in comments

### ISSUE THREAD

**Issue by marcelmah** [opnsense/core#4856]
Hi,

I'm running OPNsense 21.1.3_3 and we use an alias to change our firewall rules from a central location.
We host a textfile with some IP's on a webserver.

This URL is used in a URL table alias that reloads every day.
I recently added a IP at the end with a comment behind it that had a 'é' in it like:
4.3.2.1/32 ; collegue privé

After adding this, the alias wont succesfully load anymore and will throw this error in the log: 
2021-03-22T14:30:00 | /update_tables.py[71861] | error fetching alias url http://somedomain.com/support.txt

When I remove the special char It works fine again.

**Comment by kulikov-a** [comment]
Hi.
I can not reproduce this behavior with files on github (with utf-8 content-type) 
if you open your url in a browser in what encoding does the server returns this file?

**Comment by marcelmah** [comment]
Hi,

If I check in my browser it shows gzip as content-encoding.

**Comment by kulikov-a** [comment]
@marcelmah 
sorry, not `content-encoding` header. encoding on `content-type:` header

**Comment by marcelmah** [comment]
Is this what you mean?
HTTP/1.1 200 OK
Date: Tue, 23 Mar 2021 10:36:26 GMT
Server: Abyss/2.7.0.0-X1-Win32 AbyssLib/2.7.0.0
Content-Type: text/plain
Last-Modified: Mon, 22 Mar 2021 13:30:28 GMT
Vary: Accept-Encoding, User-Agent
Content-Encoding: gzip

**Comment by kulikov-a** [comment]
yes
may be `Content-Type: text/plain` is the issue. server should add the `charset` value to this header (like `content-type: text/plain; charset=utf-8`) so the client can handle content right. can you try to set this on your server? (may be somewhere in MIME settings)

**Comment by marcelmah** [comment]
Hi,

I changed the MIME type for the .txt file to text/plain;charset=utf-8
I can now use é again without errors.

So this was a configuration error on the webserver side and does not need fixing on the OPNsense side right?

**Comment by kulikov-a** [comment]
I could be wrong but imho yes - upstream issue.
(https://www.w3.org/International/articles/http-charset/index.en)
guessing the file charset on the opnsense side is not the best idea.

**Comment by marcelmah** [comment]
Alright, I agree.

This issue can be closed, thnx for the help!
