### ISSUE TITLE
Add Ability to Save Filters in Firewall Live Log View 

### ISSUE THREAD

**Issue by borkedporcupine** [opnsense/core#4859]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [ x ] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [ x ] I have searched the existing issues and I am convinced that mine is new.

**Is your feature request related to a problem? Please describe.**

This is a feature request, not related to a problem. 

**Describe the solution you like**

On the firewall live log page, /ui/diagnostics/firewall/log I think it would be useful if we could save filters for common filtering tasks.  I find myself doing repetitive tasks when digging through logs, would like to be able to save the filters for quick filtering. 

**Describe alternatives you considered**

Alternative is a manually choosing filters each time. 

**Additional context**

Something like this is what I would like to see (down toward the bottom) https://campus.barracuda.com/product/webapplicationfirewall/doc/78810008/types-of-logs/

**Comment by AdSchellevis** [comment]
https://github.com/opnsense/core/issues/4731 sounds quite similar, since this template is more complete, I'll close the other one.

**Comment by kulikov-a** [comment]
Hello everyone!
did I get the idea right? (grid-MVC for templates storing. quick manipulation directly on Live View)

https://user-images.githubusercontent.com/36099472/113257088-c290f780-92d2-11eb-9f44-a3d9420967cf.mp4

**Comment by borkedporcupine** [comment]
> Hello everyone!
> did I get the idea right? (grid-MVC for templates storing. quick manipulation directly on Live View)
> 
>  lv-templ.mp4

@kulikov-a This looks fantastic.

**Comment by kulikov-a** [comment]
Thanks! then i continue with this approach)
I did not plan any other functions so as not to clutter up the interface (even editing is not planned: "select->modify->del->add with old name"  are enough imho)
please tell if something is missing

**Comment by kulikov-a** [comment]
Hi everyone.
Me again. All functions are ready, template editing is added. If there are no other suggestions and comments, then I'm ready to clean up the code and prepare a pr.

https://user-images.githubusercontent.com/36099472/113511741-21bc6980-956a-11eb-9ae7-445a275b8fd0.mp4
