### ISSUE TITLE
IPSec ID Mismatch

### ISSUE THREAD

**Issue by SXN31** [opnsense/core#4860]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x ] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x ] I have searched the existing issues and I am convinced that mine is new.

**Is your feature request related to a problem? Please describe.**

When attempting to establish an IPSec site-to-site from one pfSense firewall to an OPNsense firewall with the same settings, the tunnel fails. As referenced in the forum post [here](https://forum.opnsense.org/index.php?topic=22197.0) it appears there is a mismatch with how pfsense and OPNsense generate the ipsec configurations.

Namely, 
pfSense tends to use a type prefix and value where as OPNsense does not.

Example:
Selecting Dynamic DNS in pfSense: leftid = dns:vpn2.domain
Selecting Dynamic DNS in OPNsense: leftid = 10.0.0.0
Selecting Distinguished Name in pfSense: rightid = fqdn:vpn1.domain
Selecting Distinguished Name in OPNSense: rightid = vpn2.domain

**Describe the solution you like**
From the strongSwan documentation found [here](https://wiki.strongswan.org/projects/strongswan/wiki/IdentityParsing) it appears if the value has the form<type>:<value> (supported since 5.2.2), the type and value are explicitly specified.

The following types are known: ipv4, ipv6, ipv4net, ipv6net, ipv4range, ipv6range, rfc822, email, userfqdn, fqdn,
dns, asn1dn, asn1gn and keyid. Custom type prefixes may be specified by surrounding the numerical type value
with curly brackets.

The solution I'm proposing is to explicitly declare types or provide the option to do so rather than allow for the automatic parsing to do its thing. It appears that pfSense's implementation is utilizing this typing.

If you read the strongswan documentation under left|rightid = <id>it does specify some potential challenges with parsing, but I'm not well-versed enough in IPSec to understand if that would be problematic or not.

**Describe alternatives you considered**

There was a patch made for keyid, I could just install the patch and use keyid as my identifiers until I replace my pfSense at the remote location with a new OPNsense box.

**Additional context**

https://forum.opnsense.org/index.php?topic=22197.0

https://wiki.strongswan.org/projects/strongswan/wiki/ConnSection

**Comment by AdSchellevis** [comment]
For reference the keyid patch https://github.com/opnsense/core/commit/81fa4ec53df1dfd5319573852817a3bf9b457ce4, personally I don't mind too much to enforce typing on the ones that "auto detect" now, but only in a major release for obvious reasons.

The list of available options is defined here:
https://github.com/opnsense/core/blob/642ee1514f2ae1a30cbf9578f27adc5f8fdb99ab/src/www/vpn_ipsec_phase1.php#L852-L857


`dyn_dns` and `peeraddress` resolve explicitly, `peeraddress` is defined by this machines address (`ipsec_get_phase1_src()`), which  leaves the following options:

*  address --> probably best leave as is, can be ipv4/ipv6
* fqdn --> prefix fqdn
* user_fqdn --> prefix userfqdn
* asn1dn --> prefix asn1dn
* keyid (already in master)


`ipsec_find_id()` handles the mapping, but is used to return the address and/or the identifier at the moment, we should probably alter this a bit when prefixing type.

**Comment by armin1402** [comment]
It seems i'm also affected by this Issue, some IPsec connections are failing in Phase 1, because IDs cant be matched.

**Comment by SXN31** [comment]
> 
> 
> It seems i'm also affected by this Issue, some IPsec connections are failing in Phase 1, because IDs cant be matched.

Without patching it my workaround is to use Mutual PSK instead of certificates and on the OPNsense side for identifiers I am using KeyID tags like so:
![image](https://user-images.githubusercontent.com/43016545/115332767-59700780-a14d-11eb-9976-3d067da94482.png)

On the pfSense side it would look like this:

![image](https://user-images.githubusercontent.com/43016545/115332853-7e647a80-a14d-11eb-98fc-b9710b1d4e79.png)

This has allowed me to establish my ipsec tunnels between pfSense and OPNsense reliably for the time being.
