### ISSUE TITLE
Remove option "disable" in NAT Traversal in IPSEC Phase 1 settings

### ISSUE THREAD

**Issue by goodomens42** [opnsense/core#4862]
- [ x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [ x] I have searched the existing issues and I am convinced that mine is new.

**Describe the bug**

OPNSense offers options "Disable", "Enable" and "Force" in IPSEC Phase 1 NAT Traversal settings.
In fact strongswan seems not allow to disable NAT-T anymore since release 5.0.0, see [https://wiki.strongswan.org/projects/strongswan/wiki/NatTraversal](https://wiki.strongswan.org/projects/strongswan/wiki/NatTraversal).
Took me quite a while to find out, why disabling NAT-T did not work :)

The option value "Disable" is therefore pointless and maybe the Dropdown-Field should be replaced by a tickmark "Force NAT-T".

A hint "To disable NAT-T make shure that MOBIKE is disabled" when clicking the "i" icon might be helpful as well, as this seems to be the only way to disable NAT-T 

**Environment**

OPNsense 21.1.3_3 (amd64, OpenSSL).

**Comment by AdSchellevis** [comment]
off influences automatic firewall rules:
https://github.com/opnsense/core/blob/81fa4ec53df1dfd5319573852817a3bf9b457ce4/src/etc/inc/plugins.inc.d/ipsec.inc#L294-L307

force sets `forceencaps`, on leaves nat-t in it's default state.

https://github.com/opnsense/core/blob/81fa4ec53df1dfd5319573852817a3bf9b457ce4/src/etc/inc/plugins.inc.d/ipsec.inc#L1641-L1644

**Comment by goodomens42** [comment]
Thanks for clarifying ! I overlooked this, in my testing automatic firewall rules were turned off.
