### ISSUE TITLE
Feature Request: dhcp relay HA mode

### ISSUE THREAD

**Issue by ind-georghuber** [opnsense/core#4864]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues and I am convinced that mine is new. **See  #4307 - state incomplete, so new one**

**Is your feature request related to a problem? Please describe.**

I am missing a solution for the high availablility handling of dhcp relay (dhcrelay).
One point is the config (xmlrpc) sync, which is not implemented for the dhcp relay config till version 21.1.3.

The other point is the service handling. At the moment, there is no option, to decide on which firewall of a cluster the dhcp relay service should be active. In my case that is a problem, because only the master firewall can communicate with the dhcp server. More in solution.

**Describe the solution you like**

For the first point: 
I would like an input field in "/ui/system_hasync.php" where you can choose dhcp-relay for xmlrpc sync.
For the second:
The service dhcp-relay should only be active on the master firewall of a carp cluster.

A clear and concise description of any alternative solutions or features you considered.
For the first point:
Maybe integrate the config sync to the dhcpd checkbox .

Thank you.

**Comment by AdSchellevis** [comment]
the config sync part is included in https://github.com/opnsense/core/commit/b2074ef3a3b73cddb2d688ad7056cdd691b8dea7, in order to keep both active the service should probably be able to bind on a carp ip, which is currently not a priority on our end.

**Comment by raspitoaster** [comment]
I found this feature request when looking for a solution of my problem  #6226
A possible solution would be to have the DHCRELAY only active on the MASTER firewall node.
I tried to use a CARP hook but did not succeed - a copy of the WIREGUARD hook that works on my setups.
Can you point me to an error in the script or is the CARP-hook approach not feasible?

credits to 
Copyright (C) 2004 Scott Ullrich <sullrich@gmail.com>
and https://gist.github.com/jprenken/18ca7bf14ddae547ae0fdf6f56d72573
 
```
#!/usr/local/bin/php
<?php
require_once("config.inc");
require_once("interfaces.inc");
require_once("util.inc");

$subsystem = !empty($argv[1]) ? $argv[1] : '';
$type = !empty($argv[2]) ? $argv[2] : '';

if ($type != 'MASTER' && $type != 'BACKUP') {
    log_error("Carp '$type' event unknown from source '{$subsystem}'");
    exit(1);
}

if (!strstr($subsystem, '@')) {
    log_error("Carp '$type' event triggered from wrong source '{$subsystem}'");
    exit(1);
}

if ($type === "MASTER") {
    log_error("Enabling DHCRELAY due to CARP event '$type'");
    if (isset($config['OPNsense']['dhcrelay']['enable'])) {
      $config['OPNsense']['dhcrelay']['enable'] = '1';
    }
    configd_run('dhcrelay start');
    sleep(1);
    configd_run('dhcrelay start');
    write_config("Enable DHCRELAY due to CARP event '$type'", false);
} else {
    log_error("Disabling DHCRELAY due to CARP event '$type'");
    configd_run('dhcrelay stop');
    sleep(1);
    configd_run('dhcrelay stop');
    if (isset($config['OPNsense']['dhcrelay']['enable'])) {
        $config['OPNsense']['dhcrelay']['enable'] = '0';
    }
    write_config("Disable DHCRELAY due to CARP event '$type'", false);
}
```
