### ISSUE TITLE
IPv6 Route Advertisement RDNSS lifetime is too short per RFC recommendation.

### ISSUE THREAD

**Issue by Napsterbater** [opnsense/core#4867]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues and I am convinced that mine is new.

**Describe the bug**

IPv6 Route Advertisement RDNSS lifetime is too short per RFC recommendation.
RFC8106 5.1 says RDNSS Lifetime "SHOULD by default be at least 3 * MaxRtrAdvInterval"

additonally

> The rationale of the default value of the Lifetime field is as
>          follows.  The Router Lifetime field, set by AdvDefaultLifetime,
>          has the default of 3 * MaxRtrAdvInterval as specified in
>          [RFC4861], so such a default or a larger default can allow for
>          the reliability of DNS options even under the loss of RAs on
>          links with a relatively high rate of packet loss.  Note that
>          the ratio of AdvDefaultLifetime to MaxRtrAdvInterval is the
>          number of unsolicited multicast RAs sent by the router.  Since
>          the DNS option entries can survive for at most three
>          consecutive losses of RAs containing DNS options, the default
>          value of the Lifetime lets the DNS option entries be resilient
>          to packet-loss environments.

**To Reproduce**

Simply enable Router Advertisements with DNS server configured 

**Expected behavior**

RDNSS Lifetime should be 3 times the Maximum Interval

**Describe alternatives you considered**

OPNsense should add to the radvd config:

`AdvRDNSSLifetime 3060
`
this would go in the same block at the RDNSS changing

`RDNSS 2001:470:****:1::3 2001:470:****:2::8 { };
`
to
```
         RDNSS 2001:470:****:1::3 2001:470:****:2::8 {
         AdvRDNSSLifetime 3060 
         };
```
In this case 3060 is 3 times 1020, my configured Maximum Interval

**Relevant log files**

RA from Packet Cap

> Internet Control Message Protocol v6
>     Type: Router Advertisement (134)
>     Code: 0
>     Checksum: 0xa4b8 [correct]
>     [Checksum Status: Good]
>     Cur hop limit: 64
>     Flags: 0xc0, Managed address configuration, Other configuration, Prf (Default Router Preference): Medium
>     Router lifetime (s): 3060
>     Reachable time (ms): 0
>     Retrans timer (ms): 0
>     ICMPv6 Option (Prefix information : 2001:470:****:1::/64)
>     ICMPv6 Option (Prefix information : fda9:26a9:1c47:1::/64)
>         Type: Prefix information (3)
>         Length: 4 (32 bytes)
>         Prefix Length: 64
>         Flag: 0xc0, On-link flag(L), Autonomous address-configuration flag(A)
>         Valid Lifetime: 86400
>         Preferred Lifetime: 14400
>         Reserved
>         Prefix: fda9:26a9:1c47:1::
>     ICMPv6 Option (Route Information : Medium ::/0)
>         Type: Route Information (24)
>         Length: 3 (24 bytes)
>         Prefix Length: 0
>         Flag: 0x00, Route Preference: Medium
>         Route Lifetime: 3060
>         Prefix: ::
>     ICMPv6 Option (Recursive DNS Server 2001:470:****:1::3 2001:470:****:2::8)
>         Type: Recursive DNS Server (25)
>         Length: 5 (40 bytes)
>         Reserved
>         Lifetime: 1020
>         Recursive DNS Servers: 2001:470:****:1::3
>         Recursive DNS Servers: 2001:470:****:2::8
>     ICMPv6 Option (DNS Search List Option napshome.local)
>         Type: DNS Search List Option (31)
>         Length: 3 (24 bytes)
>         Reserved
>         Lifetime: 1020
>         Domain Names: napshome.local
>     ICMPv6 Option (MTU : 1500)
>         Type: MTU (5)
>         Length: 1 (8 bytes)
>         Reserved
>         MTU: 1500
>     ICMPv6 Option (Source link-layer address : 00:15:5d:01:f1:12)
>         Type: Source link-layer address (1)
>         Length: 1 (8 bytes)
>         Link-layer address: Microsof_01:f1:12 (00:15:5d:01:f1:12)
> 

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 21.1.3_3-amd64FreeBSD 12.1-RELEASE-p14-HBSDOpenSSL 1.1.1j 16 Feb 2021
Windows Server 2019 Hyper-V, AMD Ryzen 9 3950X, 4GB RAm

**Comment by fichtner** [comment]
Thanks for you report. radvd.conf still claims:

    Default: 2*MaxRtrAdvInterval

And we validate the advanced value according to this manual page. I don't mind bumping the value validation, but what is the upper bound then if 3*MaxRtrAdvInterval is the default -- is it also the maximum value?


Cheers,
Franco

**Comment by Napsterbater** [comment]
> Thanks for your report. radvd.conf still claims:
> 
> ```
> Default: 2*MaxRtrAdvInterval
> ```

Yes, that is claimed, but that is not reality. I was involved in the "other" group with this same issue. radvd is simply using the MaxRtrAdvInterval as is. 

I have 1020 set in my config for the MaxRtrAdvInterval, and you can see 1020 is used for the RDNSS lifetime as well. 

RFC says this could be set to "infinity" (Max 32bit Value), but if this is going to be left unconfigurable which should be fine, then the default miniimum recomendation of 3 * MaxRtrAdvInterval  should be sufficient. 



> And we validate the advanced value according to this manual page. I don't mind bumping the value validation, but what is the

What do you mean by this? 

Right now this is that my radvd conf has.

> interface igb1 {
> 	AdvSendAdvert on;
> 	MinRtrAdvInterval 510;
> 	MaxRtrAdvInterval 1020;
> 	AdvLinkMTU 1500;
> 	AdvDefaultPreference medium;
> 	AdvManagedFlag on;
> 	AdvOtherConfigFlag on;
> 	prefix 2001:470:****:1::/64 {
> 		DeprecatePrefix off;
> 		AdvOnLink on;
> 		AdvAutonomous on;
> 	};
> 	prefix fda9:26a9:1c47:1::/64 {
> 		DeprecatePrefix off;
> 		AdvOnLink on;
> 		AdvAutonomous on;
> 	};
> 	route ::/0 {
> 		RemoveRoute off;
> 	};
> 	RDNSS 2001:470:****:1::3 2001:470:****:2::8 {
> 	};
> 	DNSSL napshome.local {
> 	};
> };

This is what this part need to look like to fix this. Again MaxRtrAdvInterval * 3 = 3060
> 	};
> 	RDNSS 2001:470:****:1::3 2001:470:****:2::8 {
>      AdvRDNSSLifetime 3060 
> 	};

**Comment by maurice-w** [comment]
@fichtner, bumping the value validation for the advanced options makes sense. 👍
@Napsterbater, regarding the defaults, wouldn't it be better to raise an radvd issue?
https://github.com/radvd-project/radvd/issues

**Comment by fichtner** [comment]
So the last question is if radvd accepts values outside the interval it documents, otherwise the whole request doesn’t make sense until radvd is patched.

**Comment by Napsterbater** [comment]
Yes it does. This is already been implemented on other platforms. Hence why I've made the suggestion here.

If the radvd config is generated with the change I'm suggested it will solve the problem. You can manually add that to the config And it will work.

That one line just needs to be added to the RDNSS section in the value Just needs to be based on the max advertisement interval whether that be the default if it wasn't manually set or whatever the user set.

And just to be clear I'm not suggesting any changes to the max advertisement interval in case that was unclear. This only affects the RDNSS section of the config.

**Comment by maurice-w** [comment]
Defaults have been changed in radvd master: radvd-project/radvd#151
I removed the bounds for the advanced options in #4893 and tried 86400 seconds. Works fine with the current radvd 2.19.

@Napsterbater, if you need a larger AdvRDNSSLifetime now, you may try `opnsense-patch cf873b5` and specify the desired value in the advanced options.
