### ISSUE TITLE
EDNS not working for IPv6 nameserver behind opnsense

### ISSUE THREAD

**Issue by mauline** [opnsense/core#4869]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues and I am convinced that mine is new.

**Describe the bug**

This is for opnsense OPNsense 21.1-amd64 running on a pc-engines APU. 

A DNSSEC enabled DNS server with an IPv6 address behind an opnsense firewall has problems with some queries. This is what the "EDNS compliance tester" at https://ednscomp.isc.org/ednscomp/ says:

dns=ok edns=ok edns1=ok edns@512=ok ednsopt=ok edns1opt=ok **do=timeout** ednsflags=ok **docookie=timeout** edns512tcp=ok optlist=ok 

(please note the timeout errors).

The issue seems to be related to large UDP packets and packet reassembly. With *Firewall: Settings: Normalization:Disable interface scrub* enabled, IPv6 works, but IPv4 fails. Disabling the setting, IPv4 works, but IPv6 queries do not work.

DNS can be made working by disabling the line

$scrubrules .= "scrub on {$scrubcfg['if']} inet6 all {$scrubnodf} {$scrubrnid} {$mssclampv6}\n";

in filter.inc.

**To Reproduce**

1. Setup a DNSSEC enabled name server with a IPv6 address behind an opnsense firewall.
2. Make sure *Firewall: Settings: Normalization:Disable interface scrub* is disabled.
3. Visit https://ednscomp.isc.org/ednscomp/, enter a zone served by this nameserver and press sumbit.
4. Check for errors.

**Expected behavior**

IPv6 UDP packets of arbitrary length should reach the nameserver.

**Additional context**

pfsense has a similar error that could also be resolved by editing the php that generates the scrubing rules. There was a blog describing this error which is gone. The old page is available using the wayback archive:

https://web.archive.org/web/20200811014208/https://melkfl.es/article/2018/07/edns/

**Environment**

Software version used and hardware type:

opnsense OPNsense 21.1-amd64
PC-Engines APU 4D4

**Comment by AdSchellevis** [comment]
Interface scrub rules aren't generated when disabled:
https://github.com/opnsense/core/blob/f3e6a227e5817c61f71d4b485284a60a472949e2/src/etc/inc/filter.inc#L671-L673 


The referenced scrub v6 rule is part of the same block.

**Comment by mauline** [comment]
I'm sorry for not being precise enough.

...
2. Make sure Firewall: Settings: Normalization:Disable interface scrub is disabled.
...

Means that the box is not ticked. So because the box is not ticked, scrubbing is not disabled, which means that the scrub rules in filter.inc are generated.

**Comment by AdSchellevis** [comment]
yes, my point exactly, if you do want to disable scrubbing, you need to disable it. The rule itself is needed for this https://github.com/opnsense/core/issues/4484. You can always create more fine grained rules if needed manually.

**Comment by mauline** [comment]
Actually I don't want to disable scrubbing in general. I would like to disable defragmentation for IPv6 which seems to the the problem. Citing from the blog page linked in the issue: 

"A bit more fiddling later, and it looked like my pfSense was indeed reassembling the IPv6 packets (which is a bad idea to begin with), and then trying to shove them into its WAN interface in their reassembled state. The packets being >1500 bytes in size, that would trigger an ICMPv6 message that the packet was too big and so the packet would make like Jimmy Hoffa and disappear."

opnsense seems to behave identical here. 

Regarding fine grained rules: How would I disable defragmentation for IPv6 (maybe for just one interface)? I've looked into *Firewall: Settings: Normalization:Detailed settings*, but could not find anything regarding defragmentation.

**Comment by AdSchellevis** [comment]
just disable the interface scrubbing, which is a general setting and build your own with the rules below....
![image](https://user-images.githubusercontent.com/9783985/112622470-5b36fb80-8e2b-11eb-814d-fbda52f1d71e.png)


All that's in the general rule should be configurable manually too. If I'm not mistaken "fragment reassemble" is standard when scrub is enabled, but you can always inspect pf.conf (`man pf.conf`)

**Comment by mauline** [comment]
As said above, I cannot find anything that relates to fragment reassembly in the detailed firewall scrub rules. Could you please advise me? Maybe I'm looking in the wrong place?

Besides that, if opnsense reassembles IPv6 fragments but does not fragment them again before passing them to the target interface, this is clearly a bug in my eyes. This means that no IPv6 UDP packet > 1500 bytes will reach its destination.

**Comment by kulikov-a** [comment]
@mauline 
Hi
from pf.conf man:
     When forwarding reassembled IPv6 packets, pf refragments them with	the
     original maximum fragment size.  This allows the sender to	determine the
     optimal fragment size by path MTU discovery.
so no, of course pf doesn't try to send unfragmented traffic. 
imho the question is why the PMTUD does not work in this setup (I'm afraid packet capturing will be needed to understand what is happening with icmpv6 type 2 messages).

another issue is pf itself imho. based on this post from pf maintainer,  imho fragment reassembly is always enabled with scrub enabled:
https://forums.freebsd.org/threads/omitting-fragment-reassemble.77854/post-485611

so imho if it is not possible to solve the PMTUD issues and the only way is to disable the reassembly (which is not good imho), then you can try to disable the scrub only for ipv6 and only for your name server.
@AdSchellevis pointed out how you can try to do this (disabling the general scrubbing and building your own)

**Comment by mauline** [comment]
Thanks a lot for your comment! I will do some packet capturing this weekend and post the results.

Actually I see no reason why opnsense does reassembly of IPv6 UDP packets at all. In the DNS case, the client tries to detect the maximum transfer unit and the sender fragments the packet according to this number. If some router in between starts to reassemble packets without both sides knowing, PMTUD does no longer work. For IPv4, reassembly is necessary to make NAT work. But using NAT for IPv6 is pretty uncommon, so I doubt, reassembly is necessary at all.

Regarding the workaround pointed out by @AdSchellevis, I'm still missing how to do this. I cannot find any setting in the GUI that enables me to configure packet reassembly based on an interface or destination host level. Can you give me a hint?

**Comment by AdSchellevis** [comment]
@mauline the plus sign at the top right corner can be used to add custom rules.

**Comment by kulikov-a** [comment]
@mauline 
if something happens to the traffic, then this is not an opnsense decision, but pf. and pf, if we believe the quote from man, tries not to interfere with the ipv6 PMTUD between endpoints.
reassembly itself is useful if it works correctly. because it allows you to check not only the IP headers but also the headers of subprotocols (ports, icmp codes etc.)
if pf has any issues with ipv6 reassembly, then it would be interesting to understand and inform the maintainer

in Firewall: Settings: Normalization you can "Disable interface scrub" and Add your manual scrub rules

hmm
@AdSchellevis  I cannot find an option to specify only the inet\ipv4 proto in the scrub rule settings. bad looking or really missed?

**Comment by AdSchellevis** [comment]
@kulikov-a I think we've omitted the protocol selection indeed, but that probably doesn't matter as you still can match on source / destination networks (0.0.0.0/0).

**Comment by mauline** [comment]
@kulikov-a Thank you. I will come up with some packet captures and then we can continue the discussion.

> in Firewall: Settings: Normalization you can "Disable interface scrub" and Add your manual scrub rules

I know, but ok. So I disable interface scrub which globally disables packet reassembly.

Which setting in the manual scrub rules enables packet reassembly for packets matching this rule? Under "Normalization" I can see 5 settings, but none of them changes IP reassembly. Or am I missing something?

**Comment by kulikov-a** [comment]
@AdSchellevis tricky! thanks )
@mauline 
so imho you cant try to disable "Disable interface scrub" and add scrubbing for ipv4 sources only. or even try to make a Network Group Alias to exclude DNS server from all internal networks

**Comment by kulikov-a** [comment]
@mauline 
i think you need to disable scrubbing at all for this source. by enabling it for all except DNS host ipv6 address

**Comment by kulikov-a** [comment]
@mauline 
as mentioned in the https://forums.freebsd.org/threads/omitting-fragment-reassemble.77854/post-485611, there is a feeling that at the moment there is no way to enable scrubbing without reassembly. so you will have to completely disable scrubbing for this source

**Comment by kulikov-a** [comment]
@AdSchellevis 
sorry, maybe for such a case of granular scrub settings it is worth adding the ability to create "no scrub" rules?
(I can try to make a pr sometime)
Or have I missed something and there is such ability?

**Comment by AdSchellevis** [comment]
@kulikov-a to be honest, I don't think it adds much. maybe it's easier to just add the protocol so you can generate the exact same with two rules, maybe accompanied with some documentation (https://github.com/opnsense/docs/blob/master/source/manual/firewall_scrub.rst).

**Comment by kulikov-a** [comment]
@AdSchellevis from what I see (manual scrub rules are written before the general ones) this could be done using one "no scrub" rule without turning off the general rules.
but of course the same can be done with existing capabilities, thanks!

**Comment by mauline** [comment]
@kulikov-a Ok so, I've created packet captures of working and non working scenarios and I can confirm the behavior described by me above:

On response to a DNS query, the DNS server sends a correctly fragmented reply. The firewall reassembles the fragments, and tries to send the reassembled packet over the outgoing interface, where it will be refused and an ICMP "packet too large" error is generated.

Problem is that the sender (DNS server) cannot do anything to remedy, because even if it creates smaller fragments in response the the ICMP error, this will have no effect. I haven't investigated why it works with IPv4 (see below for reason), but I would assume that for IPv4 the packet is again split into fragments before sending it over the outgoing interface. As a consequence opnsense breaks all IPv6 connections using packets larger the the MTU of the outgoing interface - if not serious trickery is applied.

Anyway, I'm not going to pursue this any further. It seems some opnsense members aren't really interested in improving opnsense. See #4872. I'm not going to work in a toxic climate like this and therefore closing this issue.

**Comment by AdSchellevis** [comment]
@mauline Maybe we got off on the wrong foot here, maybe something is lost in translation, it might be good to re-read some of the posts before jumping to conclusions. I'm (and I think most people involved in the project) are open for discussions, just saying it really helps if you're not jumping to conclusions and throw Wiki articles around about what a clone means.... There's often more to it then the single issue you're having your eye on at the time. Not trying to pursue you in doing anything, just asking for an open mind.

**Comment by maurice-w** [comment]
There might indeed be issues with pf (not refragmenting reassembled IPv6 packets) or OPNsense (no straightforward way to disable IPv6 fragment reassemble) which deserve further investigation.

That being said, taking a look at the bigger picture might be a good idea, too. Issues with fragmented IPv6 packets are unfortunately common and best avoided by not generating them in the first place. For DNS servers, this can and should be done by setting an appropriate EDNS buffer size: https://dnsflagday.net/2020/#action-authoritative-dns-operators

**Comment by kulikov-a** [comment]
@mauline offtopic: I've been pestering devs for almost a year with questions, suggestions, and pieces of code (not always smart at all). And my opinion, if i may - you are in a hurry with conclusions (wrong foot really)
if you decide to try again:

could you describe in more detail: does the ICMP "packet too large" reach the server? Does server change the fragment size?Does pf change the size of the outgoing packet in accordance with the new size of the outgoing packet from the server?
and, by the way, is it possible to try without pf ipv6 nat (may be ipv6-nat is the issue)?

**Comment by chrcoluk** [comment]
In FreeBSD !3 or 14 ((I cannot remember which), support for disabling reassembly in scrub was fixed.  So assuming you on a build of OPNsense new enough then you can add 'no reassemble' to the syntax for the scrub rule on IPv6, you can patch the rule generation so is different scrub rules for inet and inet6.
