### ISSUE TITLE
firewall/logs: normal view "Act" column needs a brush-up

### ISSUE THREAD

**Issue by fichtner** [opnsense/core#487]
The X-is clickable, but counter-intuitive.

**Comment by fichtner** [comment]
@8191 what do you think, close this then? :)

**Comment by fichtner** [comment]
@8191 ping :)

**Comment by 8191** [comment]
I'm not totally convinced with the current solution (neither the "normal" nor the "dynamic" view), since it's not completely intuitive. But I cannot imaging a better solution neither... :confused:

**Comment by fichtner** [comment]
True. Ok, let's leave this open.

**Comment by fichtner** [comment]
Was discussed internally, need to close without further sense of direction in favour of a new ticket, as soon as a direction is proposed.
