### ISSUE TITLE
Implement Negotiable Crypto Parameters (NCP) OpenVPN

### ISSUE THREAD

**Issue by FingerlessGlov3s** [opnsense/core#4871]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I have searched the existing issues and I am convinced that mine is new.

**Is your feature request related to a problem? Please describe.**
Negotiable Crypto Parameters (NCP) OpenVPN would aid us in moving to new cyphers as and when ones are depreciated or considered not as secure, EG CBC to GCM. Say the server your connecting to will be changing ciphers soon, you can add the list of NCP ciphers for less downtime, when the switchover happens.

**Describe the solution you like**

In the WebUI to be able to select from a list of supported ciphers, ones I wish to be for the NCP.

**Describe alternatives you considered**

Trying to update Server and clients at the same time, with small deployments this is easy but there's a point where it harder to do all of them at the same time.

**Additional context**

https://community.openvpn.net/openvpn/wiki/CipherNegotiation

**Comment by beren12** [comment]
This would be amazing now that chacha is supported in opnsense's openvpn!

**Comment by beren12** [comment]
I've managed to do it via an advanced config at least.

**Comment by AdSchellevis** [comment]
the new `Instances` ui for 23.7 offers `data-ciphers` and `data-ciphers-fallback`, which the document (https://community.openvpn.net/openvpn/wiki/CipherNegotiation) describes.
