### ISSUE TITLE
Proxy Client can't reach website as CA is unknown (too new ??? )

### ISSUE THREAD

**Issue by hunter86bg** [opnsense/core#4873]
The CA and cert of the site seems valid as multiple clients can download it via multiple browsers (when not behind the proxy).
The URL that causes the error:  [HPE](https://downloads.hpe.com/pub/softlib2/software1/pubsw-linux/p803169573/v173093/hp-health-10.92-5.5.rhel8.x86_64.rpm)
```
The following error was encountered while trying to retrieve the URL: https://gslb-downloads-hpe-com.ext.hpe.com/*

Failed to establish a secure connection to 15.241.20.93

The system returned:

(92) Protocol error (TLS code: X509_V_ERR_UNABLE_TO_GET_ISSUER_CERT_LOCALLY)
SSL Certficate error: certificate issuer (CA) not known: /C=US/O=DigiCert Inc/CN=DigiCert TLS RSA SHA256 2020 CA1

This proxy and the remote host failed to negotiate a mutually acceptable security settings for handling your request. It is possible that the remote host does not support secure connections, or the proxy is not satisfied with the host security credentials.
```

**Comment by kulikov-a** [comment]
this HPE server does not provide the intermediate authority certificate 
https://wiki.squid-cache.org/ConfigExamples/Intercept/SslBumpExplicit#Missing_intermediate_certificates

**Comment by hunter86bg** [comment]
Stranglely, many browsers do not complain about that... I'm not sure if it's a bug then.

**Comment by kulikov-a** [comment]
browsers and squid-4 and above are able to independently download the certificate of an intermediate CA thanks to the information in the server certificate. 
what are the squid settings? https inspection enabled? "log sni info only" diabled? authentication required?

**Comment by hunter86bg** [comment]
Enable SSL inspection - checked
Log SNI information only - unchecked

I can't thind the 'Authentication required' option, but as I'm using it as a transparent proxy most probably it's disabled.

**Comment by kulikov-a** [comment]
got it. so squid blocks its own requests on sub-CA cert fetching
working solution afaik:
http://squid-web-proxy-cache.1019090.n4.nabble.com/Squid-won-t-download-intermediate-certificates-td4688931.html
you can try to add certsfetc.conf file to  /usr/local/etc/squid/pre-auth/  dir with:
`
###
#Allow fetch intermediate certs before required authentication
acl fetched_certificate transaction_initiator certificate-fetching
cache allow fetched_certificate
http_access allow fetched_certificate
###
`
should work imho

**Comment by hunter86bg** [comment]
I can confirm that it worked

**Comment by hunter86bg** [comment]
Funny thing is that I just tried to reach [Squid wiki from above](https://wiki.squid-cache.org/ConfigExamples/Intercept/SslBumpExplicit#Missing_intermediate_certificates) and I got error even after applying the fix:
```
The following error was encountered while trying to retrieve the URL: https://master.squid-cache.org/*

Failed to establish a secure connection to 104.130.201.120

The system returned:

(92) Protocol error (TLS code: X509_V_ERR_UNABLE_TO_GET_ISSUER_CERT_LOCALLY)
SSL Certficate error: certificate issuer (CA) not known: /C=US/O=Let's Encrypt/CN=R3

This proxy and the remote host failed to negotiate a mutually acceptable security settings for handling your request. It is possible that the remote host does not support secure connections, or the proxy is not satisfied with the host security credentials.
```
Could it be the same issue and the fix not working at full extent ?

**Comment by kulikov-a** [comment]
imho it seems even funnier:
- master.squid-cache.org uses LE cert
- master.squid-cache.org uses LE cert from R3 sub-CA
- R3 LE certs do not contain (accessMethod = 1.3.6.1.5.5.7.48.2) information (so the cert should be provided by the server)
- master.squid-cache.org attaches  **X3**  intermediate authority certificate 🤣 
https://www.sslshopper.com/ssl-checker.html#hostname=master.squid-cache.org

so your squid doesn't know where to get a intermediate authority certificate
you can try to add R3 cert to System: Trust: Authorities, restart squid and check again
