### ISSUE TITLE
opnsense won't update

### ISSUE THREAD

**Issue by atxbyea** [opnsense/core#4874]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues and I am convinced that mine is new.

**Describe the bug**
Trying to upgrade opnsense fails, whatever mirror I select yields the same error, have had no issues upgrading before the current try.

Just reports back `root@sasuke:~ # pkg update
Updating OPNsense repository catalogue...
pkg: http://mirror.as24220.net/opnsense/FreeBSD:12:amd64/21.1/latest/meta.txz: No address record
repository OPNsense has no meta file, using default settings
Unable to update repository OPNsense
Error updating repositories!

`
A clear and concise description of what the bug is, including last known working version (if any).

*Tip*: to validate your setup was working with the previous version, use opnsense-revert (https://docs.opnsense.org/manual/opnsense_tools.html#opnsense-revert)

**To Reproduce**
Checking for updated in the GUI or doing `pkg update` or `opnsense-upgrade` from cli

**Expected behavior**
The system to upgrade

**Describe alternatives you considered**

A clear and concise description of any alternative solutions or workaround you considered.

**Screenshots**

**Relevant log files**

If applicable, information from log files supporting your claim.

**Additional context**

`root@sasuke:~ # uname -a
FreeBSD sasuke.eirikzlab.local 12.1-RELEASE-p14-HBSD FreeBSD 12.1-RELEASE-p14-HBSD #0  e10a7efcee1(stable/21.1)-dirty: Mon Mar  8 14:52:22 CET 2021     root@sensey:/usr/obj/usr/src/amd64.amd64/sys/SMP  amd64
root@sasuke:~ # freebsd-version -u
12.1-RELEASE-p14-HBSD
root@sasuke:~ # opnsense-version 
OPNsense 21.1.3 (amd64/OpenSSL)

`

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 19.1.1 (amd64, OpenSSL).
Intel® Xeon™ E3-1225V5 3.3Ghz Quad Core
Network Intel® I210-AT

**Comment by AdSchellevis** [comment]
sounds like dns (System -> Settings -> General is usually a good place to start in these matters)

**Comment by atxbyea** [comment]
Interesting  @AdSchellevis because I did check DNS , it was set to 1.1.1.1 and was working fine, and all my clients used opnsense for DNS... But changing it to 8.8.8.8 made it work again.

This has been broken for over two weeks, I just haven't had time to look at it before tonight
Thanks, working now, for no good reason :-)
