### ISSUE TITLE
Inconsistent UI for L3 menu items

### ISSUE THREAD

**Issue by mihakralj** [opnsense/core#4875]
- [ x ] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [ x ] I have searched the existing issues and I am convinced that mine is new.

**Describe the bug**
There are many inconsistent ways how OPNsense hadles level-3 menu items:

- Unbound DNS (for example) displays all level-3 items in the side menu, highlighting the currently active page in the menu, and then displaying the content in the main panel with descriptive title: _Services: Unbound DNS: General_. No sub-menus or tabs are displaying on the top of the main panel.

- _Firewall: Aliases_ is using only tabs on top of the main panel to let user navigate between level-3 pages (Aliases and GeoIP setting). There is no navigational clue of level-3 items in the menu on the left - the only item that appears there is level-2 (Aliases)

- Variation to the one above is _Firewall: Log Files: Overview_, as it is the 4th level of nesting - but displays only level 3 menus and then shows level 4 navigational elements in the main panel.

- _Firewall: Shaper_ and  _System: Firmware_  use a new variation of tabs and menus for level-3 items: when a user navigates to the level-2 item, suddenly **ALL** level-3 menu items get lit at the same time, while also displaying tab navigation on the top of the main panel. User can navigate between level-3 screens either by clicking tabs on the top or clicking any of lit items in the menu, but there is no visual clue left in the menu for the current position (as **all** level-3 items are lit).

**Expected behavior**
The double navigational paradigm of the nested menus on the left *and* the navigational tabs on the top needs to be resolved and we need concise UX guidelines to prevent future experiments with navigation. 

**Suggestion:** we eliminate ALL tabs and move ALL navigation to the menu structure on the right, regardless of how many nested menus the feature or plugin requires. Users should always assume that navigation between pages is done exclusively in the menu tree on the left, and assume that only one item at the time will be lit in the menu (matching the information in the main panel)

**Alternative suggestion:** we declare that menu structure is used for (all) major navigation (level 1-3), allowing tabs to be used only for level 4 sub-pages and minor navigation. This one is less ideal as it keeps mixing the navigational paradigm between side menu and top tabs, yet it would be more consistent than the current mix.

**Screenshots**
Unbound handling level-3 menus with no tabs:
![image](https://user-images.githubusercontent.com/31756078/112741540-96c0eb00-8f3b-11eb-902a-0487c45d11d3.png)

Firewall using tabs but no menus for level-3 items:
![image](https://user-images.githubusercontent.com/31756078/112741550-ae986f00-8f3b-11eb-88c5-acfa3410d986.png)

Firmware update activates ALL level-3 items and also shows tabs:
![image](https://user-images.githubusercontent.com/31756078/112741565-db4c8680-8f3b-11eb-81fa-108e2115ccac.png)

**Environment**
OPNsense 21.7.a_255

**Comment by mihakralj** [comment]
@fichtner if you can point me to the php/html code that generates the L3 menu tree with wrong (missing) classes, I can try to clean it up...

**Comment by AdSchellevis** [comment]
I don't think there's anything missing there, in some case one could debate that tabs might also exist in the menu, but there's a strong relation between navigation an how underlaying code is separated (for good reasons). 

Currently I don't think we do have plans to change this, other than adding a menu item here and there if it's more logical (although navigation will only work properly when the content is being served from a different endpoint, so a single page using references [#] can't be rendered server side). Small changes within the available framework, which are easy to review, might be acceptable though. 

There's always some room for improvements, but we also need to weight the time spend on these type of issues verses the gain and possible chance of regressions. Changing code by itself doesn't really help when the general point is around documentation of a style guide and general consensus about it.

**Comment by mihakralj** [comment]
Let me address only one issue that is shown on the last screenshot (and let's park all others): the issue of lighting-up ALL level-3 menu items by using class `list-group-item menu-level-3-item  active ` across all items, not just a single active item that is selected.

The proposed change: all L3 items get the class `list-group-item menu-level-3-item` and only the currently selected (highlighted) item gets the class `list-group-item menu-level-3-item  active `.

Because all entries got the .active class, I cannot filter that out in the theme through jquery of css overload...

Let me know if this makes sense? Everywhere else the UI adds .active class only to one element, not all menu elements in its branch...

**Comment by mihakralj** [comment]
For clarity:
![image](https://user-images.githubusercontent.com/31756078/117258593-fbf0e180-ae01-11eb-95c8-32ad4c37a964.png)

**Comment by AdSchellevis** [comment]
> (although navigation will only work properly when the content is being served from a different endpoint, so a single page using references [#] can't be rendered server side).

^^ that's logical, could be changed when binding to different endpoints, but has other downsides.

**Comment by mihakralj** [comment]
Do I understand that correctly: because all of the Firmware pages are actually rendered from one single endpoint, we cannot generate a dynamic context-aware menu server-side?

If true, how about adding jquery events instead?

**Comment by AdSchellevis** [comment]
yes. Not going to consider that due to the amount of added complexity and the fact that both legacy template and mvc template would likely require changes. It's simply not worth the effort.
