### ISSUE TITLE
Address family validation fails when adding static routes to interface with dynamic gateway policy

### ISSUE THREAD

**Issue by maurice-w** [opnsense/core#4880]
- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues and I am convinced that mine is new.

**Describe the bug**

You can add static routes directly to an interface (without an actual gateway) by enabling "dynamic gateway policy" and adding a dynamic "dummy gateway". When adding static routes to such a "gateway", the address family is not validated correctly: You can add IPv4 routes to an IPv6 "gateway" and you can't add IPv6 routes at all.

**To Reproduce**

1. Go to 'Interfaces: [Interface]', set the 'IPv6 Configuration Type' to 'Static IPv6', enable 'Dynamic gateway policy', enter a valid IPv6 address, save and apply.
2. Go to 'System: Gateways: Single', add a gateway, select the previously configured interface, set 'Address Family' to IPv6, enter 'dynamic' in the 'IP address' field, save and apply.
3. Go to 'System: Routes: Configuration', add a route, enter a valid IPv6 network in the 'Network Address' field, select the previously configured 'Gateway', save.
4. See error messages: 'Specify a valid network matching the gateways ip protocol.', 'Specify a valid gateway from the list matching the networks ip protocol.'
5. Enter a valid IPv4 network in the 'Network Address' field, save again.
6. See error: Route gets saved despite the protocol mismatch.

**Expected behavior**

You should (only) be able to add IPv4 routes to IPv4 gateways / interfaces and IPv6 routes to IPv6 gateways / interfaces.

**Describe alternatives you considered**

Manually add IPv6 routes via shell.

**Environment**

OPNsense 21.7.a_255 (amd64, OpenSSL)

**Comment by AdSchellevis** [comment]
The `Dynamic gateway policy` option is intended to be able to omit an address for tunnel type devices (https://docs.opnsense.org/manual/interfaces.html), if you do want to set an address for the gateway, make sure to disable the dynamic option (in which case normal gateway rules should apply)

**Comment by maurice-w** [comment]
I do _not_ want to set an address for the gateway and indeed tested this with a tunnel interface (WireGuard). Sorry I didn't mention that, wanted to keep it easy to reproduce. You can of course set the interface's 'IPv6 Configuration Type' to 'None' and let wg set the interface address. That's the only difference and it doesn't make a difference regarding the bug.

**Comment by AdSchellevis** [comment]
@maurice-w ok, got it, had to read your issue again, seemed to have missed the point the first time.

**Comment by AdSchellevis** [comment]
@maurice-w can you try https://github.com/opnsense/core/commit/384018c52233e85746e81ed0c2158d4307943802 ?

**Comment by maurice-w** [comment]
Thank you @AdSchellevis, that fixed it! Adding IPv6 routes works and so does the actual routing.

Btw, I stumbled over this while unsuccessfully trying to set up policy based routing with such a "gateway". That doesn't seem to work at all (neither IPv4 nor IPv6). Would you mind taking a look before I open another issue?
https://forum.opnsense.org/index.php?topic=22348

**Comment by AdSchellevis** [comment]
@maurice-w maybe better open a new ticket, I'm not sure what we're looking at here. destination routing with the dynamic gateways works (it's the same as openvpn uses), but maybe I'm overseeing a glitch elsewhere, although I thought I've seen functional OpenVPN cases which use the same type of routing.
