### ISSUE TITLE
System: Wizard: Configure LAN Interface dhcp 

### ISSUE THREAD

**Issue by it-jonas** [opnsense/core#4882]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [ x ] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [ x ] I have searched the existing issues and I am convinced that mine is new.

**Describe the bug**

Setup fails if LAN IP address is dhcp. 

**To Reproduce**

1. Install opnsense on device
2. change LAN IP via terminal to dhcp
3. open browser and start wizzard go to System: Wizard: Configure LAN Interface 

**Expected behavior**

I would expect to continue with the setup.

**Screenshots**

![Screenshot from 2021-03-31 02-13-55](https://user-images.githubusercontent.com/20993035/113072563-a81e2780-91c7-11eb-9988-4bd0eb1f9041.png)

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 21.1-amd64
FreeBSD 12.1- RELEASE-p12-HBSD
OpenSSL 1.1.1i  8 Dec 2020

**Comment by AdSchellevis** [comment]
we should probably disable the wizard when configured via console, the state isn't as predictable as it should be in that case.
