### ISSUE TITLE
Implement RFC 6824

### ISSUE THREAD

**Issue by lordkitsuna** [opnsense/core#4883]
- [✓] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [✓] I have searched the existing issues and I am convinced that mine is new.

**Is your feature request related to a problem? Please describe.**
No my feature request is not directly related to a problem

A clear and concise description of what the problem is including your motivation for the request,
i.e. "For the purpose of [...] I am missing a solution that will [...]."

Motivation for my request is having access to multiple WAN uplinks as well as a VPS with enough bandwidth to service both links fully with low and stable latency. I would like to be able to use a wireguard vpn setup to bond these uplinks using MPTCP so that a single tcp connection/flow can utilize both links fully. i have been able to verify using a linux machine that this can work but ideally i would be able to do it right in the router so my entire lan can transparently have that boost. 

have RFC 6824 support added to the kernel so it can be used on the system.

**Describe alternatives you considered**
I have considered just setting up a linux router, and indeed have one currently for testing but ideally i would be able to keep using opnsense.

**Comment by fichtner** [comment]
Please check with FreeBSD where this has been added?
