### ISSUE TITLE
Implement pfsense equivalent of: "OpenVPN Clients [ ] Register connected OpenVPN clients in the DNS Resolver"

### ISSUE THREAD

**Issue by Alives** [opnsense/core#4885]
- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues and I am convinced that mine is new.

Implement pfsense's unbound DNS resolver feature: **Register connected OpenVPN clients in the DNS Resolver**

**OpenVPN Clients [ ] Register connected OpenVPN clients in the DNS Resolver**
> If this option is set, then the common name (CN) of connected OpenVPN clients will be registered in the DNS Resolver, so that their name can be resolved. This only works for OpenVPN servers (Remote Access SSL/TLS or User Auth with Username as Common Name option) operating in "tun" mode. The domain in System: General Setup should also be set to the proper value.

**Comment by Alives** [comment]
FWIW this seems to be accomplished via learn-address scripts in openvpn config but the implementation relies on some unbound config snippets as well: https://github.com/pfsense/pfsense/blob/b5b748705873aec3ac035a69821f3b1302c3e9cd/src/usr/local/sbin/openvpn.learn-address.sh

**Comment by AdSchellevis** [comment]
It's a bit similar to what we do for dhcp addresses and blacklist control (`unbound-control`), but glueing all kinds of services together is not something I'm personally a huge fan of unless a clear separation can be made (avoid race conditions and unwanted dependencies). 

The  `learn-address` in openvpn looks practical for tracking users by the way, for example to update a firewall alias with a users current address. Disadvantage of unbound control is that you will need to track state in some way in case unbound restarts, which has the tendency to lead to more logic and chance of regressions.

For a limited set of users, it's often easy enough to use client specific overrides to pin the address and add those in unbound or dnsmasq.

**Comment by Alives** [comment]
Yes, the latter is specifically what I ended up implementing in order to regain the "feature" I was using in pfsense.  It seems they're generating unbound config on openvpn client changes to preserve state.

**Comment by AdSchellevis** [comment]
I know, it's not very pretty (although likely difficult to fix otherwise), it's probably not very high on our wish-list given earlier experiences.

**Comment by beren12** [comment]
This would be nice, as would an ip-pool file option to keep the same client ip in openvpn.

**Comment by ulope** [comment]
Just to add my voice here. 
I'm currently evaluating switching to opnsense, but unfortunately this feature is a pretty essential requirement for us. 
With almost 50 users and almost as many services connected via VPN manual management of addresses ist just too much of a hassle.

**Comment by beren12** [comment]
You can do like I did and use an advanced config for static vpn addresses. I would recommend using ssh to verify it's the correct config name (I have 1 server so it's server1). In advanced settings:

ifconfig-pool-persist /var/etc/openvpn/server1.ip-pool 86400

**Comment by beren12** [comment]
Oh if you make any changes to the file you need to do it with openvpn stopped as it writes the file on exit.

**Comment by ITJamie** [comment]
+1 on wanting this feature

**Comment by Galaxy102** [comment]
+1, this is an important feature IMHO. I'd be glad to help if I could receive some pointers on where to begin.
