### ISSUE TITLE
Run on both HTTP and HTTPS by default, add setup wizard section to choose

### ISSUE THREAD

**Issue by Alives** [opnsense/core#4886]
- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues and I am convinced that mine is new.

I got burned by my browser caching pre-existing HSTS for the domain I use opnsense from.  I'd prefer that my password only be sent in HTTPS since it's required on first www login.  It'd be nice if initially both HTTP/HTTPS were used with a setup wizard section to specify, with HTTPS being default, not HTTP.

**Comment by fichtner** [comment]
I don't think that's possible. Connect by IP should not be an issue.

**Comment by Alives** [comment]
I don't follow?  I'm asking that HTTP/80 and HTTPS/443 be enabled by default on a fresh install.

**Comment by AdSchellevis** [comment]
they are, http redirects to https on a default install.

**Comment by fichtner** [comment]
I seem to have tripped over “for the domain I use” assuming the connection was made through a hostname and not the IP. I can see that being problematic and DNS rebind protection might be triggered as well over HTTP too.

**Comment by Alives** [comment]
Did a fresh reinstall, you are correct.  I accidentally reverted to HTTP for the configuration protocal via console during assigning IP address to the LAN interface. Sorry about the confusion.
