### ISSUE TITLE
Routing entry getting lost when modifying IPSec Routed dynamically created Gateway Monitoring IP.

### ISSUE THREAD

**Issue by mrzaz** [opnsense/core#4888]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I have searched the existing issues and I am convinced that mine is new.

**Describe the bug**

I have found bug with IPSec Routed and a routing entry getting lost causing issues to ping/reach remote tunnel-IP.
Could be reproduced every time. Caused by a bug in the code handling Disable/Enable gateway monitoring AND when
adding and then later removing a manually entered Monitor IP.

* The current OPNsense version where the bug first appeared
Tested/found on 21.1.3 and 21.1.4

* The last OPNsense version where the bug did not exist
N/A

* A list of steps to replicate the bug
**To Reproduce**

Prerequsit:
- Tested with 21.1.4
- Setup IPSec Routed in both end. 
example:
I have a IPSec routed net with phase1 and phase2 setup with a tunnel-net 10.6.110.0/30.
Router1   10.6.110.1/30     (LAN: 192.168.120.221/24)
Router2   10.6.110.2/30     (LAN: 192.168.120.231/24)
- Have enabled "Dynamic gateway policy" and it has created the Dynamic Gateways in the gateway tab.
- I have also added rule on IPSec+VTI_ifc+LAN with a "Allow Firewall to respond to pings"
  Dir: in, IPv4, ICMP, Any, This Firewall
- Configured the dynamicly created gateways with "Far Gateway"

1. restart routers. Both routers have the following entries. (reversed order in router2)
```
Destination        Gateway            Flags     Netif Expire
default            178.132.x.y      UGS      vtnet0
10.6.110.1         link#7             UHS         lo0
10.6.110.2         link#7             UH       ipsec1
```

2. Go to Gateways and edit the dynamic gateway created from IPsec.

3. Untick the "Disable Gateway Monitoring" and enter the tunnelIP on the other side and press APPLY.
(eg. 10.6.110.2)

4. Go to Gateways and edit the dynamic gateway created from IPsec again.

5. Tick the "Disable Gateway Monitoring" and remove the tunnelIP so editbox is blank and press APPLY.

6. Now the routing table has lost one entry. (the "10.6.110.2         link#7             UH       ipsec1"
```
Destination        Gateway            Flags     Netif Expire
default            178.132.x.y        UGS      vtnet0
10.6.110.1         link#7             UHS         lo0
```

This is a bug and can be reproduced every time.

**Expected behavior**

Even when changning "Disable Gateway Monitoring" and the "Monitoring IP" it should never loose any routing table entries.

**Describe alternatives you considered**

N/A

**Screenshots**

**OPNSense screenshots**

![opnsense_Gateway_Overview](https://user-images.githubusercontent.com/9613777/113326020-7321ea00-9319-11eb-9322-6a839c688d66.jpg)
![opnsense_Gateway_Edit](https://user-images.githubusercontent.com/9613777/113318767-15899f80-9311-11eb-97e7-761b6c933106.jpg)

**pfSense screenshots**

![pfsense_Gateway_Overview](https://user-images.githubusercontent.com/9613777/113325944-5685b200-9319-11eb-91d7-93ce71014c59.jpg)
![pfsense_Gateway_Edit](https://user-images.githubusercontent.com/9613777/113325955-5a193900-9319-11eb-973a-55c252ecb3b5.jpg)
![pfsense_Gateway_Widget](https://user-images.githubusercontent.com/9613777/113318866-2c2ff680-9311-11eb-997b-df6739f7a3bd.jpg)

**Relevant log files**

If applicable, information from log files supporting your claim.

BEFORE
```
root@Router2:~ # netstat -r -n -4
Routing tables

Internet:
Destination        Gateway            Flags     Netif Expire
default            178.132.x.y         UGS      vtnet0
10.6.110.1         link#7             UH       ipsec1
10.6.110.2         link#7             UHS         lo0
127.0.0.1          link#4             UH          lo0
178.132.x.y/27   link#1             U        vtnet0
178.132.x.z       link#1             UHS         lo0
192.168.120.0/24   link#2             U        vtnet1
192.168.120.221/32 ipsec1             US       ipsec1
192.168.120.231    link#2             UHS         lo0
```

root@Router2:~ # netstat -r -n -4
Routing tables

AFTER REPRODUCED ISSUE
```
Internet:
Destination        Gateway            Flags     Netif Expire
default            178.132.x.y          UGS      vtnet0
10.6.110.2         link#7             UHS         lo0
127.0.0.1          link#4             UH          lo0
178.132.x.y/27   link#1             U        vtnet0
178.132.x.z        link#1             UHS         lo0
192.168.120.0/24   link#2             U        vtnet1
192.168.120.221/32 ipsec1             US       ipsec1
192.168.120.231    link#2             UHS         lo0
```

**Additional context**

Have also seen a few other problem that I will report separatly:
- When both entries exists and you could ping the remote tunnel IP both from commandline or through OPNSense webgui, 
if you enable gateway monitoring the monitorIP shows as blank and Gateway also blank and it is always OFFLINE.

- In pfSense, from where I am currently migrating, the IPSecRouted dynamicly created gateways always picks up and shows 
the Gateway IP and the Monitor IP even if IP says "dynamic".  OPNSense does NOT do that. 
This could possible be an additional bug that I may report in anonther bug report.
See attach screenshots.

**Environment**
At the moment running in a VM in Unraid but has reproduced in real HW as well.
Running OPNSense v21.1.4 (amd64)
I7 2660k, 24GB RAM DDR3
Network Intel Server NIC 4port

If you need any more assistance or more logs/reproduction please let me know.

Dan Lundqvist
Stockholm, Sweden
danne@mrzaz.com
betateam.mrzaz@gmail.com

Best regards
Dan Lundqvist

**Comment by spali** [comment]
Can confirm on 21.1.4.
Even without changing anything and hitting "Apply" in the IPsec Tunnel Settings wipes out all manually configured static routes.
If it matters, I have routed and non routed tunnels.
It seems to just not reload the configuration of the manually defined static routes after reloading the IPsec routes.

Current workaround is to just hit "Apply" also on the route configuration manually after each change on IPsec. But can't say if this also happens during a automatic rule reload from IPsec side.

**Comment by mrzaz** [comment]
Hello,
I'm not sure if this is the same as I describe, as the routing entry that 
gets removed in my case is the IPSEC-VTI auto-created remote Tunnel-IP that 
is defined in the Phase2 entry.

Have not tested what happens when press apply in IPSec as my fault occurred 
when modifying the MonitorIP in the gateway settings adding and then 
removing an IP in the text field and enabling/disabling the MonitorIP function.

Will try and get back on that one...

Best regards
Dan Lundqvist
Stockholm, Sweden
