### ISSUE TITLE
system: remove /dev/crypto GUI support along with OpenVPN engine support

### ISSUE THREAD

**Issue by fichtner** [opnsense/core#4896]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues and I am convinced that mine is new.

**Is your feature request related to a problem? Please describe.**

OpenSSL 1.1.1k broke /dev/crypto on FreeBSD < 13.

**Describe the solution you like**

Remove /dev/crypto magic since we will likely never be able to use it anymore.

**Describe alternatives you considered**

Doing clean backports of OpenSSL ;)

**Additional context**

https://forum.opnsense.org/index.php?topic=22374.0

**Comment by AdSchellevis** [comment]
isn't this only very old hardware support? I remember https://github.com/opnsense/tools/issues/26, where we removed it from being build into the kernel.

**Comment by fichtner** [comment]
Yes, that one. Unfortunately even on modern systems it breaks all HTTPS servers when enabled with 1.1.1k...  https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=254643

**Comment by AdSchellevis** [comment]
removal seems like a fine option indeed :)

**Comment by fichtner** [comment]
@AdSchellevis shall we kill the OpenVPN OpenSSL engine support with it? Yeah, you could still load /dev/crypto but need an older OpenSSL or the one from base or your own OpenSSL fork... LibreSSL hasn't had /dev/crypto support for a long time and the only remaining engine I see is https://en.wikipedia.org/wiki/RDRAND but that is from 2012 and even has a mention of FreeBSD moving away from it for /dev/random source.

**Comment by AdSchellevis** [comment]
@fichtner I think that's ok, just ping me when you have a commit to double check

**Comment by fichtner** [comment]
@AdSchellevis this would be it d17e70b39ba237637

**Comment by AdSchellevis** [comment]
@fichtner thanks, looks good indeed

**Comment by fichtner** [comment]
all done then :)
