### ISSUE TITLE
Add option to configure AdvRASrcAddress and DeprecatePrefix for radvd

### ISSUE THREAD

**Issue by adengg** [opnsense/core#4897]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues and I am convinced that mine is new.

**Is your feature request related to a problem? Please describe.**

For the purpose of HA setups i'm missing the option to configure AdvRASrcAddress in radvd
to be able to seamlessly swith the routing with CARP instead of having to wait for the client to figure out
that the router is down and switch to the other one if both anounce their _first_ link-local address instead of
a shared CARP address.

**Describe the solution you like**

Having an Input field in services_router_advertisements.php to customize AdvRASrcAddress allow for a transparent failover from the clients perspective.
Related to that having the option to also customize DeprecatePrefix in order to not remove the route when shutting down one of the routers.

**Describe alternatives you considered**

I looked into reducing the lifetime of the announced routes by adapting  MinRtrAdvInterval and MaxRtrAdvInterval to force faster switchover by the client, but it still leads to interruptions.

**Additional context**

The entry for the Setting in the radvd.conf manpage explicitly describes the setting for HA setups:
       By default radvd will use the first link-local address for the
       interface as the source address for route advertisements. This can be
       overwritten by manually setting the list of acceptable source
       addresses. If done, radvd will use the first address from the interface
       that is present in the configured source addresses only. This
       functionality will NOT spoof the source address, but may be useful in
       combination with VRRP or other functionality that

       AdvRASrcAddress {
               list of IPv6 addresses
       };

I also tested it by manually adapting the configuration and it seems to work as expected

**Comment by vnxme** [comment]
@adengg Thank you for raising this issue. Agree that a configurable AdvRASrcAddress option may contribute a lot to the high availability options OPNsense provides.

**Comment by meyergru** [comment]
I have subscribed to this issue because I think that the DeprecatePrefix option is also vital:

In case of a WAN IPv6 prefix change, this allows for an immediate invalidation of the old prefix upon radvd configuration change (and restart) . The old, invalid prefix normally still gets used by the clients until its preferred lifetime runs out.

This need is often missed in router and firewalling products, even if radvd is beinh employed: In Europe - at least in Germany -  most providers assign dynamic IPv6 prefixes via PPPoE connections, this seems to be handled differently in other parts of the world.

**Comment by fichtner** [comment]
I tend to agree that local CARP plus delegated prefix change is difficult, but does it really use a GUA CARP address that is automatically registered between failover peers? This is missing the use case (reproductivity).
