### ISSUE TITLE
Suricata doesn't seem to detect test case when IPS is ON

### ISSUE THREAD

**Issue by spiriapbergeron** [opnsense/core#4901]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues and I am convinced that mine is new.

**Describe the bug**

I have been following the video here:  https://www.youtube.com/watch?v=_yIq3GM4gjA

Things go well. I start to configure things, starting at 13:15 or so. But soon things start to go wrong.

As per the webinar: 

13:20: I click "enabled", then Apply.  Only my LAN interface is selected, as expected.
13:48: I select **_OPNsense-App-detect/test_**, and click the "Enable" orange button.
14:09: I click "Download and apply rules".  I see the date/time and checkmark. There is nothing in the "Filter" column, as expected.
14:50: I setup the schedule, accept the default.
15:38: I open a command prompt and use curl to download test file:  

```
c:\users\myself> curl http://pkg.opnsense.org/test/eicar.com.txt
X5O!P%@AP[4\PZX54(P^)7CC)7}$EICAR-STANDARD-ANTIVIRUS-TEST-FILE!$H+H*
```

(as expected)

16:00: I go to the alert section, and indeed I see the alert: 
![image](https://user-images.githubusercontent.com/50995128/113669915-6d623680-9682-11eb-9a94-5aabc4a5c7bc.png)

Now things go wrong.

To make sure I am not crazy, I first start fresh by deleting my log file, by pressing the little trash icon. The alerts list says: "No Alerts Found!", as expected.

18:08: In Administration Settings,  click "IPS mode", and Apply.   I click the shortcut to go to Interface settings, and I confirm that Hardware CRC, TSO, LRO are disabled.  Hardware VLAN dropdown is also disabled.
![image](https://user-images.githubusercontent.com/50995128/113673194-ad2b1d00-9686-11eb-801d-d480cf68a6e3.png)

19:16: I click on the "Download" tab, I select the test rule again, press the orange button "Enable (drop filter)", and "Download & Update Rules"
![image](https://user-images.githubusercontent.com/50995128/113670615-5b34c800-9683-11eb-82a9-d45af33e161d.png)

19:43: I go to my console, try to download the file again. 

**Unexpectedly** I can download the file.

![image](https://user-images.githubusercontent.com/50995128/113670826-946d3800-9683-11eb-9ec2-04ac7dcceaa6.png)

I go to my alerts section: and I don't even get an alert. 

![image](https://user-images.githubusercontent.com/50995128/113670915-ac44bc00-9683-11eb-9909-b5062a4eab9b.png)

(and I can no longer follow the instructions on the webinar).

To make sure I am not crazy, I go to Administration Settings, and **UNCHECK** IPS mode, and Apply.

I go to my console and use curl to download the file again.

If I go to my alerts tab, I now see the following
![image](https://user-images.githubusercontent.com/50995128/113671116-f037c100-9683-11eb-9cf2-be5485ac0e30.png)

Notice it still says "Allowed", even though It was set to dropped (the only thing I changed was to unchecked IPS mode): 

Thus, on my router, choosing IPS does not seem to work correctly to block traffic.

I have performed the same steps many times before filing the report, and there does not seem to be a workaround.

I have also noticed strange behavior when adding my WAN interface (some rules can be set to drop, others still remain allowed even though I can clearly see they are meant to be set to drop), but this will be another topic for another day.

My system:

OPNsense 20.7.8_4-amd64
FreeBSD 12.1-RELEASE-p12-HBSD
OpenSSL 1.1.1i 8 Dec 2020

My OPNsense runs on the following device:
https://www.aliexpress.com/item/4000266234442.html

I3-5010U
4 GB RAM
6x LAN intel i211AT Gigabit ethernet.

I hope this was detailed enough, thank you.

**Comment by kulikov-a** [comment]
hi
do you use vlans? any clues in logs when switch IDS to IPS?
