### ISSUE TITLE
Introduce a short random delay to stagger alias update cron jobs

### ISSUE THREAD

**Issue by marinbernard-pep06** [opnsense/core#4903]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues and I am convinced that mine is new.

**Is your feature request related to a problem? Please describe.**

OPNsense regularly updates pf tables by running a Python script (`/usr/local/opnsense/scripts/filter/update_tables.py`) as a cron job, on every minute. This job results in a substantial increase of CPU load (100% single core usage) for a few seconds.

When several OPNsense VMs are hosted on a single hypervisor, with properly configured time synchronization, the current schedule triggers the cron job at the very same moment on every VM. This leads to every-minute CPU spikes (100% CPU usage on all cores for 3 to 5 secondes) on the host system, as all VM compete for CPU time.

**Describe the solution you like**

As we run many (several tens) OPNsense VMs on the same hardware, this is becoming a real problem for us. I am aware that our usage of OPNsense is rather uncommon, and that most users will never experience the same issue. A simple way to solve this would be to add a short, random sleep period before each invocation of the cron job. Something like:

```
/bin/sleep $(jot -r 1 1 45) && (/usr/local/bin/flock -n -E 0 -o /tmp/filter_update_tables.lock /usr/local/opnsense/scripts/filter/update_tables.py) > /dev/null
```

**Describe alternatives you considered**

Alternatively, the sleep delay could be introduced somewhere at the beginning of the Python script. But this would not prevent all VMs to invoke the python3 interpreter at the same time. I would not be surprised if the mere invocation of the interpreter turned out to be the most CPU intensive task of the whole cron job, so I'm not sure whether this solution is valid.

**Additional context**

My old [post on the OPNsense forum](https://forum.opnsense.org/index.php?topic=17953.msg81563) about the same issue.

Thank you

**Comment by fichtner** [comment]
This is for @AdSchellevis to review, but a quick note here is that we run into backend timeout unpredictably sooner with this, which is not ideal.

**Comment by fichtner** [comment]
Ah ok, the autocron uses a non-configctl command invoke duplication. It would be best to solve both issues here.

**Comment by AdSchellevis** [comment]
As far as i know the job is always executed in the background, so a random wait shouldn't be an issue. In some other scripting for the ET-Pro telemetry rules we added it in the script itself (https://github.com/opnsense/plugins/blob/6370b5374a91b0dfa99c7cd9d22370839b3d0ea8/security/etpro-telemetry/src/opnsense/scripts/etpro_telemetry/send_heartbeat.py#L72). 

If we move it to the script, the question is if we should also move the locking in there and maybe use a parameter to toggle. When the gui asks for an update, it's less logical to delay.

**Comment by marinbernard-pep06** [comment]
Hi,

Could you clarify the priority of this issue ? I need to know this to decide what to do on my side.

Thanks!

**Comment by AdSchellevis** [comment]
@marinbernard-pep06 not very high, it's not planned on our end and nobody is assigned to the ticket. We can label it help wanted to see if someone wants to work on it. if it's a priority on your end you could always consider non community (commercial) options.

**Comment by marinbernard-pep06** [comment]
> if it's a priority on your end you could always consider non community (commercial) options.
Do you mean [OPNsense Business Edition](https://shop.opnsense.com/product/opnsense-business-edition/) ? Would a subscription give a higher priority to such feature requests ?

**Comment by AdSchellevis** [comment]
no, I mean commercial support or custom development depending on the scope of the request. We can also mark it help wanted first to see if someone bites (although it will still need time from our end for planning and review, which is limited, but with a solid PR chances are larger it will be processed earlier). If time isn't of the essence, you can just wait and see if your request is being incorporated at no charge.

**Comment by marinbernard-pep06** [comment]
I'm still thinking about a decent way to solve this issue in the long run, and it seems to me that randomizing alias refreshes is probably not the best idea.

Our instances currently use 850+ aliases, and the numbers are still increasing. Those aliases are mostly (99%) static, which AFAIK makes running ``update_tables.py`` useless for them, as they do not include resolvable or expirable content. Yet, the CPU cost of running ``update_tables.py`` keeps on increasing as our number of aliases grows.

Staggering script invocations won't be much help in the end, because the real issue here is the CPU cost involved by table refreshes. IMHO, the simplest way to work around this would be to increase the delay between table refreshes, by having it configurable from the GUI. As of now, any crontab customization is lost on config refresh, so we cannot even handle this manually.

Running the cron job every 5 to 10 minutes would greatly lighten the charge on the CPU, while still enforcing table updates at a reasonable interval. My understanding of the framework is rather basic though. Would such a change have functional or security implications ?

**Comment by AdSchellevis** [comment]
I think there are several options to limit the weight, the ones that come to mind are the following from my perspective:

-  A configurable interval  as suggested (although not needed for most users and has the disadvantage of a less quick recover on initial boot on tmpfs filesystems).
- Optionally disable the auto task and let the user schedule using the cron gui for custom scenario's, probably easier to implement, same disadvantages as the first one. 
- Optimise what the action is doing, if I'm not mistaken the script compares before and after situation to minimise work combined with a TTL per entry, running a profiler on the script with a similar setup might help understand why it's slow and if there are ways to improve that. 
- Try to outsmart the scheduling determining when it makes sense to do any work, although you can only do that from within the script, if the input doesn't change and none of the TTL's are set to expire and the most recent execution didn't yield any errors, one could "cache" the results (skip doing work)

I'm currently not convinced that this specific scenario is only possible using different scheduling intervals, but in order to know what's happening someone should spend time analysing what's going on and where improvements are possible.

**Comment by thewriteway** [comment]
Could this be resolved with the big leap in performance with Python 3.11 https://github.com/opnsense/core/issues/7246 ?

**Comment by fichtner** [comment]
Unlikely.
