### ISSUE TITLE
ApiMutableModelControllerBase - save() does not return created UUID

### ISSUE THREAD

**Issue by Sebclem** [opnsense/core#4904]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues and I am convinced that mine is new.

**Describe the bug**

The [`save()` method of ApiMutableModelControllerBase](https://github.com/opnsense/core/blob/0b9a77806902ca28f4c4080fb62d4e7f2c5643b2/src/opnsense/mvc/app/controllers/OPNsense/Base/ApiMutableModelControllerBase.php#L247) does not return the created UUID.
This is an issue when you use the API (for example the Wireguard One https://github.com/opnsense/plugins/issues/2315) because you don't get the UUID in response, example:
Creating a new Wireguard server `wireguard/server/addServer` only return `{"result":"saved"}`.
But creating a client `wireguard/client/addClient` return `{"result":"saved","uuid":"28d016f2-xxxx-xxxx-xxxxxx-xxxxxxx"}` because this enpoint use the [`addBase()` method](https://github.com/opnsense/core/blob/0b9a77806902ca28f4c4080fb62d4e7f2c5643b2/src/opnsense/mvc/app/controllers/OPNsense/Base/ApiMutableModelControllerBase.php#L384) that return the UUID.

**To Reproduce**

1. Create (for example) a new WG server with the API (`wireguard/server/addServe)

**Expected behavior**

The [`save()` method of ApiMutableModelControllerBase](https://github.com/opnsense/core/blob/0b9a77806902ca28f4c4080fb62d4e7f2c5643b2/src/opnsense/mvc/app/controllers/OPNsense/Base/ApiMutableModelControllerBase.php#L247) should return the created UUID like [`addBase()`](https://github.com/opnsense/core/blob/0b9a77806902ca28f4c4080fb62d4e7f2c5643b2/src/opnsense/mvc/app/controllers/OPNsense/Base/ApiMutableModelControllerBase.php#L384)

**Environment**
OPNsense 21.1.4-amd64

**Comment by AdSchellevis** [comment]
@Sebclem I've added the uuid in `validateAndSave()` when available, although technically I think @mimugmail could also use the standard wrappers, there aren't a lot of direct callers for this one. As of https://github.com/opnsense/core/commit/28c69fd7cd7d2cb64b3d4f1b8e1ebd60df4dbd97 `addBase()` also supports overlays.
