### ISSUE TITLE
Policy based routing doesn't work with 'dynamic gateway policy' type interfaces

### ISSUE THREAD

**Issue by maurice-w** [opnsense/core#4905]
- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues and I am convinced that mine is new.

**Describe the bug**

Policy based routing doesn't work with tunnel interfaces which don't have a real gateway ('dynamic gateway policy' enabled). The resulting pf rules are missing the `route-to <interface>` parameter. I tested this with WireGuard, but it's probably a firewall issue.

**To Reproduce**

1. Go to 'VPN: WireGuard: Local', add a new instance, enter an IPv4 'Tunnel Address' (/32), check 'Disable Routes', save and apply.
2. Go to 'Interfaces: Assignments', assign, enable and lock the wgX interface, check 'Dynamic gateway policy', save and apply.
3. Go to 'System: Gateways: Single', verify that a gateway for wgX was created and is online (gateway monitoring is disabled).
4. Go to 'Firewall: Rules: LAN', add a 'pass in IPv4 any / any / any' rule, set the 'Gateway' to the wgX gateway, save and apply.
5. Go to 'Firewall: Diagnostics: pfInfo: Rules' and look up the rule.
6. See error: The rule is missing the `route-to wgX` parameter.
7. Go to 'Firewall: Settings: Advanced', enable 'Skip rules', save.
8. Go back to 'Firewall: Diagnostics: pfInfo: Rules' and look up the rule again.
9. See error: The rule is missing entirely.
10. Rinse & repeat everything with IPv6. Same behaviour.

**Expected behavior**

Policy based routing should work with 'dynamic gateway policy' type interfaces. pf rules must contain the `route-to <interface>` parameter.

**Describe alternatives you considered**

Use the 'fake gateway IP address hack' suggested in the docs (https://docs.opnsense.org/manual/how-tos/wireguard-selective-routing.html). This is problematic with IPv6 though because IPv6 gateways don't support the 'Far Gateway' setting.

**Additional context**

https://github.com/opnsense/core/issues/4880#issuecomment-812823714
https://forum.opnsense.org/index.php?topic=22348

**Environment**

OPNsense 21.7.a_314 (amd64, OpenSSL)
Hyper-V

**Comment by fichtner** [comment]
> Use the 'fake gateway IP address hack' suggested in the docs (https://docs.opnsense.org/manual/how-tos/wireguard-selective-routing.html). This is problematic with IPv6 though because IPv6 gateways don't support the 'Far Gateway' setting.

Maybe as a thought the far-gateway does not work, but widening the prefix does and we use that successfully in FreeBSD. Something like IPv6-Gateway/0 might work when we trigger far-gateway on IPv6 to emulate that?

**Comment by maurice-w** [comment]
Workarounds are possible, but solving the actual issue might be preferable. `route-to` doesn't require a next-hop IP address, `route-to <interface>` should work just fine. This is probably just a glitch in the OPNsense code which parses the firewall rules from the config and creates the pf rules.

**Comment by fichtner** [comment]
I would consider a permanent workaround to support far gateway in IPv6 a viable solution for users looking for it specifically. We could solve both things, otherwise lose the opportunity to test this properly. Seems like a good test case here...

**Comment by AdSchellevis** [comment]
@maurice-w this https://github.com/opnsense/core/commit/cdf328078bd3e16e1f4beb9b0d6956595fb59c67 should do the trick.

**Comment by maurice-w** [comment]
Thanks @AdSchellevis, route-to now gets added correctly and PBR works!

In the commit you also mention support for reply-to. I did a quick test and that part doesn't work for me. When adding a 'pass in' rule to a dynamic gateway policy type interface, the rule gets created but is missing the reply-to. Reply-to is not disabled (neither globally nor for this specific rule) and does work on interfaces with a "real" gateway.

**Comment by AdSchellevis** [comment]
@maurice-w it only includes explicit `reply-to` references, I think automatic IPsec rules are the only one that use this. I'm a bit cautious about some of the automatic rules since these may have side affects. For some reason I think it might be better to add support for manual reply-to rules at some point in time.

**Comment by maurice-w** [comment]
Got it! And +1 for an option to manually enable reply-to for specific rules.

**Comment by AdSchellevis** [comment]
@maurice-w as promised, https://github.com/opnsense/core/commit/286000deabbb24c2d0f923bce109cbb9a3e3d1ef should do the trick
