### ISSUE TITLE
Captive Portal: Session cannot be disconnected

### ISSUE THREAD

**Issue by ChristophD1986** [opnsense/core#4908]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues and I am convinced that mine is new.

**Describe the bug**

With the “Captive Portal” service, ongoing sessions cannot be manually disconnected via the trash button on the “Sessions” page. After clicking on the trash button, the window “Do you want to disconnect this client” appears. After confirming with "yes", the session will still be displayed and will not be disconnected. The iddle & hard Timeot is 0.

**To Reproduce**

1. Open Services
2. Open Captive Portal
3. Open Sessions
4. Click on Trash
5. Confirm with yes

**Expected behavior**

The session should end

**Describe alternatives you considered**

--

**Screenshots**

--

**Relevant log files**

--

**Additional context**

--

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 21.1.4-amd64
Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz (4 cores)

**Comment by AdSchellevis** [comment]
looks like the session id was parsed with the wrong case. https://github.com/opnsense/core/commit/45f440af2c746f167bc2990dab3b77aa9170ab42 should fix it, install using:
```
opnsense-patch  45f440a
```
