### ISSUE TITLE
Simplify inital setup Q&A steps

### ISSUE THREAD

**Issue by 8191** [opnsense/core#491]
The questions asked during initial setup (or to change interfaces via the console) are quite verbose and take much time to read and understand. The questions should be short keywords and not complete sentences to avoid misinterpretation or errors of the user.

__Example:__
```
Enter the WAN interface name or 'a' for auto-detection: em0

Enter the LAN interface name or 'a' for auto-detection
NOTE: this enables full Firewalling/NAT mode.
(or nothing if finished): em1

Enter the Optional 1 interface name or 'a' for auto-detection
(or nothing if finished):
```

__Suggestion:__
```
Assign each network zone to a network interface or enter 'a' for auto-detection.

WAN: em0
LAN: em1
OPT1: em2
```
In my opinion even more confusing is the IP address assignment via the console:

__Currently:__
```
Available interfaces:

1 - WAN (em0 - dhcp)
2 - LAN (em1 - static)

Enter the number of the interface you wish to configure: 2

Enter the new LAN IPv4 address.  Press <ENTER> for none:
> 10.101.0.1

Subnet masks are entered as bit counts (as in CIDR notation) in OPNsense.
e.g. 255.255.255.0 = 24
     255.255.0.0   = 16
     255.0.0.0     = 8

Enter the new LAN IPv4 subnet bit count (1 to 31):
> 24

For a WAN, enter the new LAN IPv4 upstream gateway address.
For a LAN, press <ENTER> for none:
>

Enter the new LAN IPv6 address.  Press <ENTER> for none:
> fd10:1::1

Subnet masks are entered as bit counts (as in CIDR notation) in OPNsense.
e.g. ffff:ffff:ffff:ffff:ffff:ffff:ffff:ff00 = 120
e.g. ffff:ffff:ffff:ffff:ffff:ffff:ffff:0    = 112
e.g. ffff:ffff:ffff:ffff:ffff:ffff:0:0       =  96
e.g. ffff:ffff:ffff:ffff:ffff:0:0:0          =  80
e.g. ffff:ffff:ffff:ffff:0:0:0:0             =  64

Enter the new LAN IPv6 subnet bit count (1 to 127):
> 48

For a WAN, enter the new LAN IPv6 upstream gateway address.
For a LAN, press <ENTER> for none:
>

Do you want to enable the DHCP server on LAN? (y/n) y
Enter the start address of the IPv4 client address range: 10.101.0.100
Enter the end address of the IPv4 client address range: 10.101.0.200

(...)

The IPv4 LAN address has been set to 10.101.0.1/24

The IPv6 LAN address has been set to fd10:1::1/48
You can now access the webConfigurator by opening the following URL in you web
browser:
                https://10.101.0.1/
				https://[fd10:1::1]/
```
What confused me the most the first time I've seen that Q&A session was the gateway question `For a WAN, enter the new LAN IPv4 upstream gateway address. For a LAN, press <ENTER> for none:`. I was asking myself _why am I asked the WAN gateway now? I'm configuring the LAN interface, am I?_...

__Suggestion:__
```
Available interfaces:

1 - WAN (em0 - dhcp)
2 - LAN (em1 - static: 192.168.1.1)

Which interface should be modified? 2

Please enter the new interface configuration.

IPv4 address: 10.101.0.1
IPv4 netmask (CIDR): 16
IPv4 gateway (or nothing to use WAN interface): 
IPv6 address (or nothing to do not use IPv6): fd10:1::1
IPv6 netmask: 48
IPv6 gateway (or nothing to use WAN interface):

Enable DHCPv4 (y/n)? y
DHCPv4 range start address: 10.101.0.100
DHCPv4 range end address: 10.101.0.200

Enable DHCPv6 (y/n)? n

The LAN interface has been configured as follows:
IPv4: 10.101.0.1/16
IPv6: fd10:1::1/48

You can now access the web GUI using the following URL in your browser:

https://10.101.0.1/
https://[fd10:1::1]/
```

Also the explanations about netmask notations (decimal vs. CIDR) is not really required anymore, especially for IPv6. I've never even seen IPv6 noted netmasks in a different notation than CIDR.

**Comment by fichtner** [comment]
> On 30 Nov 2015, at 8:37 PM, 8191 <notifications@github.com> wrote:
> 
> The questions asked during initial setup (or to change interfaces via the console) is quite verbose and takes much time to read/understand. The questions should be short keywords and not complete sentences to avoid misinterpretation or errors of the user.
> 
> Example:
> 
> Enter the WAN interface name or 'a' for auto-detection: em0
> 
> Enter the LAN interface name or 'a' for auto-detection
> NOTE: this enables full Firewalling/NAT mode.
> (or nothing if finished): em1
> 
> Enter the Optional 1 interface name or 'a' for auto-detection
> (or nothing if finished):
> 
> Suggestion:
> 
> Assign each network zone to a network interface or enter 'a' for auto-detection.
> 
> WAN: em0
> LAN: em1
> OPT1: em2
> 
> In my opinion even more confusing is the IP address assignment via the console:

I like this.  I have another idea for simplicity that I want to try before we focus
on (2) while I add your suggestion to it as well.

**Comment by fichtner** [comment]
> On 30 Nov 2015, at 8:37 PM, 8191 <notifications@github.com> wrote:
> 
> The questions asked during initial setup (or to change interfaces via the console) is quite verbose and takes much time to read/understand. The questions should be short keywords and not complete sentences to avoid misinterpretation or errors of the user.
> 
> Example:
> 
> Enter the WAN interface name or 'a' for auto-detection: em0
> 
> Enter the LAN interface name or 'a' for auto-detection
> NOTE: this enables full Firewalling/NAT mode.
> (or nothing if finished): em1
> 
> Enter the Optional 1 interface name or 'a' for auto-detection
> (or nothing if finished):
> 
> Suggestion:
> 
> Assign each network zone to a network interface or enter 'a' for auto-detection.
> 
> WAN: em0
> LAN: em1
> OPT1: em2
> 
> In my opinion even more confusing is the IP address assignment via the console:

I like this.  I have another idea for simplicity that I want to try before we focus
on (2) while I add your suggestion to it as well.

**Comment by fichtner** [comment]
An user noted that the auto-configuration could show the type of config that it would do *before* the timer starts.

See: https://forum.opnsense.org/index.php?topic=1846.0

**Comment by fichtner** [comment]
I tried playing with this, but other than condensing text this doesn't add a benefit at the price of somebody else not having enough information. Personally, I shift through the steps without reading anymore. Closing.
