### ISSUE TITLE
IDS/IPS - Allow combination of ET telemetry and ET open rulesets to be selected

### ISSUE THREAD

**Issue by TurtleRecall** [opnsense/core#4914]
**Issue**

Currently, OPNsense's Suricata IDS/IPS allows use of either ET Open rulesets or ET Telemetry rulesets, but not both together/a combination of the two.

As per this thread (https://forum.opnsense.org/index.php?topic=15693.0) a number of quite useful emerging threat rulesets are populated (and regularly updated) in ET open but empty in ET telemetry, examples of empty rulesets from this thread (https://forum.opnsense.org/index.php?topic=14921.0) are:

dshield.rules
drop.rules
compromised.rules
botcc.rules
botcc.portgrouped.rules
ciarmy.rules

Prior to moving to telemetry I was seeing the ET open rules dropping quite a lot of incoming traffic from known compromised IPs etc, so this feels like useful functionality/protection that is being lost by using telemetry rulesets.

**Feature Request**

There was a suggestion from AdSchellevis in the above thread that a core issue could/should be raised to investigate the possibility of running ET telemetry and ET open side by side (or perhaps only allow use/selection of the relevant open ruleset where the telemetry ruleset is empty?).   

I've searched for closed issues but can't see any related to this, apologies if this has already been discussed.*

##EDIT##

Found a previous issue logged and closed as a support issue: https://github.com/opnsense/core/issues/4479.  I feel the above is still a valid feature request, maybe for those specific 'empty' telemetry rules mentioned above, to ensure defence in depth by allowing wholesale blocking of known compromised IPs, tor exit points, botnets etc, as well as the advantage of the more up-to-date specific rules present in the telemetry rulesets.

**Comment by AdSchellevis** [comment]
It wouldn't be very difficult to create a plugin which contains a subset of the open rules if the files in telemetry are empty. personally I don't expect a lot of these alerts hold much value, since the traffic is often already being blocked by the firewall, but if we can compile a list of the missing files and one or two people who want to try it out, I can add a plugin for the et-open "subset".

**Comment by TurtleRecall** [comment]
Hi Ad, thanks for the prompt response!  I can see the bot has marked this issue as incomplete, I couldn't see a template to follow when creating the issue/following the contributing guidelines link.  Apologies if I've missed something obvious...

Using the ET telemetry plugin, the below rules seem to solely contain a hash (as per below):

$ cat botcc.rules
#@opnsense_download_hash:887c65404492ccd36954f01694a3972e$
$ cat dshield.rules
#@opnsense_download_hash:887c65404492ccd36954f01694a3972e$
$ cat drop.rules
#@opnsense_download_hash:887c65404492ccd36954f01694a3972e$
$ cat compromised.rules
#@opnsense_download_hash:887c65404492ccd36954f01694a3972e$
$ cat botcc.rules
#@opnsense_download_hash:887c65404492ccd36954f01694a3972e$
$ cat botcc.portgrouped.rules
#@opnsense_download_hash:887c65404492ccd36954f01694a3972e$
$ cat ciarmy.rules
#@opnsense_download_hash:887c65404492ccd36954f01694a3972e$
$ cat tor.rules
#@opnsense_download_hash:887c65404492ccd36954f01694a3972e$

I'm a pretty new OPNsense user, but when I was using the ET open rulesets I can confirm these were blocking traffic and based on the forum posts I linked above from 2019 and 2020, I suppose it wouldn't be unreasonable to assume that these rulesets have been consistently empty in the telemetry pack?

I'd be more than happy to test if you were able to find the time to create a plugin for the ET open subset.  Please let me know if you need any further info!

**Comment by AdSchellevis** [comment]
technically you will only need to copy https://github.com/opnsense/plugins/blob/master/security/intrusion-detection-content-et-open/src/opnsense/scripts/suricata/metadata/rules/et-open-extra.xml into `/usr/local/opnsense/scripts/suricata/metadata/rules/` , the next development version will ship the additional plugin.
