### ISSUE TITLE
json_decode() can go OOM when processing larger files

### ISSUE THREAD

**Issue by fichtner** [opnsense/core#492]
In a recent crash report, a 20 MB file is expanded to several hundreds of MB, first hitting memory limits, and if memory limits are lifted, processing timeouts. CANNOT COMPUTE. :)

**Comment by fichtner** [comment]
This may be fixed in PHP 7, bumping to 16.7.

**Comment by AdSchellevis** [comment]
I would definitely want to test that, PHP 7 will provide some other improvements as well, but will also bring quite some backward incompatible changes.

**Comment by fichtner** [comment]
FreeBSD ports are not there yet anyway. Lots of time. :)

**Comment by fabianfrz** [comment]
At the moment (8.1.2015) PHP 7 cannot be used because phalcon is not compatible.

https://github.com/phalcon/cphalcon/issues/10378

**Comment by fichtner** [comment]
First test build for PHP 7.0 is done, this is queued up for 17.1. No need to keep this reminder.
