### ISSUE TITLE
Missing auto generated WAN firewall rules for permit IPsec when IPsec P1 using CARP address

### ISSUE THREAD

**Issue by nzkiwi68** [opnsense/core#4920]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:
[X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
[X] I have searched the existing issues and I'm convinced that mine is new.

**Describe the bug**
The automatically generated firewall rules for allowing IPsec traffic on the WAN interface are missing if the P1 IPsec interface address for opnSense is a CARP address.

**To Reproduce**
1. Create a WAN carp address
2. Make a site to site IPsec VPN and set the IPsec P1 interface address to be the WAN carp address
3. On _GUI > Firewall > Rules > WAN_ expand the "Automatically generate rules" and notice no firewall rules are created for this IPsec site to site VPN

**Expected behavior**
opnSense normally creates a series of IN and OUT firewall rules on the WAN interface to and from the remote VPN endpoint IP address to permit IPsec traffic.

**These firewall WAN automatically generated rules are missing if the IPsec source IP address for opnSense is a CARP address.**

**Describe alternatives you considered**
I tried making manual firewall rules instead and this mostly worked, but, it's not possible to exactly duplicate the automatically created rules because the OUT rule references a gateway and this cannot be made manually, you get an error;

_The following input errors were detected:
    Policy based routing (gateway setting) is only supported on inbound rules._

**Relevant log files**
none

**Additional context**
none

**Environment**
OPNsense 21.1.4-amd64

**Comment by nzkiwi68** [comment]
Here's 3 screen shots, showing an IPSEC VPN with the phase using a CARP address and the Firewall WAN auto rules, 3 of them, but no allow rules for the IPSEC tunnels...
![fw auto WAN rules](https://user-images.githubusercontent.com/67399588/116176613-88e2cd80-a766-11eb-9d5c-77d1029abd0b.PNG)
![ipsec CARP pic1](https://user-images.githubusercontent.com/67399588/116176615-8a13fa80-a766-11eb-8710-5faa8b09de50.PNG)
![ipsec CARP pic2](https://user-images.githubusercontent.com/67399588/116176616-8aac9100-a766-11eb-879a-679c3b0d74b0.PNG)

**Comment by AdSchellevis** [comment]
looks like a typo indeed, https://github.com/opnsense/core/commit/45b697f6db341709e4b93ec3d3110823927bf2e1 should fix it

**Comment by nzkiwi68** [comment]
I applied the patch 45b697f to my HA cluster and removed my manual WAN allow IPSEC fw rules.

I confirm 21.1.5 patch 45b697f works and correctly now adds the WAN allow IPSEC rules for the CARP IP address.

Thanks!

**Comment by AdSchellevis** [comment]
@nzkiwi68 thanks for confirming, we'll try to queue this for 21.1.6
