### ISSUE TITLE
Tunnel endpoint IPs of manual SPDs do not get updated for DynDNS peers

### ISSUE THREAD

**Issue by Colani1200** [opnsense/core#4922]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x ] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x ] I have searched the existing issues and I am convinced that mine is new.

**Describe the bug**

When an IPsec tunnel to a DynDNS peer is created with manual SPD entries in phase2, the tunnel endpoint IP for these entries in the SPD database does not get updated when the peer IP address changes. Only the manual SPDs are affected, the others are updating without problems. Even a restart of the IPsec service does not clear the incorrect entries, a reboot of the OPNsense is neccessary to get rid of them.

**To Reproduce**

1. Create an IPsec tunnel to a DynDNS peer
2. Add a manual SPD in phase2
3. Let the peer change its IP address
4. Verify the entries under VPN-> IPsec-> Security Policy Database
5. Result: The manual SPD entry still refers to the old tunnel endpoint IP

**Expected behavior**

All SPD entries refer to the new tunnel endpoint IP.

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 24.1.4 (amd64, OpenSSL).

**Comment by AdSchellevis** [comment]
I think this more or less duplicates https://github.com/opnsense/core/issues/4860

**Comment by Colani1200** [comment]
> 
> 
> I think this more or less duplicates #4860

Not sure about that. Maybe I should add some more information:

- Both peers are running OPNsense
- The tunnel works perfectly fine until the IP address of the DynDNS peer changes.
- After the DynDNS peer has changed its IP, only traffic originating from the primary source network defined in phase2 is able to pass through the tunnel. Traffic from the network which is defined as manual SPD no longer passes the tunnel because of the incorrect tunnel endpoint IP in the Security Policy Database.

**Comment by AdSchellevis** [comment]
which I think is the same thing as the other issue, since it probably does a reverse lookup instead of pointing to the dyndns name. you could check the contents of /usr/local/etc/ipsec.conf to be sure.

**Comment by Colani1200** [comment]
> you could check the contents of /usr/local/etc/ipsec.conf to be sure.

I checked that file, I have the DynDNS fqdn both in the _right_ and _rightid_ parameter.

**Comment by Colani1200** [comment]
If you need a DynDNS peer for testing, I'm happy to provide one.

**Comment by domi2001** [comment]
I have exactly the same problem.

**Comment by sandro64** [comment]
same problem here. please fix it

**Comment by fichtner** [comment]
Locking this, please don't ping closed tickets from tickets from 2021 and add your problem description too.
