### ISSUE TITLE
Add audit log target and move related syslog messages

### ISSUE THREAD

**Issue by AdSchellevis** [opnsense/core#4925]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues and I am convinced that mine is new.

**Is your feature request related to a problem? Please describe.**

In enterprise networks administrators do want to monitor access and changes to the system. Currently some (syslog)messages are being broadcasted when audit events happen, but most end up in the general system logging and can not be extracted for remote syslog usage due to missing application definitions.

**Describe the solution you like**

The proposed solution contains the first step into a better auditable system and starts with defining an `audit` log target including an application definition and separate log view in `System->Log Files -> Audit`.

When the target is there, the following events should be changed to use the new target or being added when not yet available:

- User authenticated successfully 
- User authentication failure
- New user created from the user interface
- New group created from the user interface
- Configuration changed (message like `root@xxxx: /firewall_nat_edit.php made changes`, which is also being saved in the configuration)

**Describe alternatives you considered**

Add missing application targets (webgui, opnsense, sshd), but this would only cover part of the problem and doesn't provide a clear view of audit events within the system.

**Additional context**

Add any other context or screenshots about the feature request here or links to relevant forum thread or similar

**Comment by mimugmail** [comment]
Really nice idea / request! 👍

**Comment by AdSchellevis** [comment]
To install on 21.1.5:
```
opnsense-patch cfb84fe ca21b966a
rm /tmp/opnsense_menu_cache.xml 
pluginctl -s syslog-ng restart
```

The user interface captures application "audit" or facility "auth", which requires two rules when configuring remote syslog.  All our audit messages are send by "audit" now.

Some sample messages (taken from `/var/log/audit/`):

```
Apr 20 10:36:32 xxxx audit[xxxx]: user xxxx authenticated successfully for sshd [using OPNsense\Auth\Services\System + OPNsense\Auth\Local]
Apr 20 10:35:58 xxxx audit[xxxx]: user xxxx authenticated successfully for WebGui [using OPNsense\Auth\Services\WebGui + OPNsense\Auth\Local]
Apr 20 10:39:30 xxxx audit[xxxx]: user xxxx failed authentication for WebGui on OPNsense\Auth\Services\WebGui via OPNsense\Auth\Local
Apr 20 10:39:30 xxxx audit[xxxx]: user xxxx could not authenticate for WebGui. [using OPNsense\Auth\Services\WebGui + OPNsense\Auth\Local]
Apr 20 10:37:58 xxxx audit[xxxx]: user xxxx@xxxx changed configuration to /conf/backup/config-1618907878.2588.xml in /system_usermanager.php?act=edit&userid=0 [user "xxxx" changed]
Apr 20 10:42:13 xxxx audit[xxxx]: user xxxx@xxxx changed configuration to /conf/backup/config-1618908133.3258.xml in /system_groupmanager.php?act=edit&groupid=2 [group "xxxx" changed]
Apr 20 10:43:14 xxxx audit[xxxx]: user xxxx@xxxx changed configuration to /conf/backup/config-1618908194.9835.xml in /system_groupmanager.php?act=new [group "x123754" created]
Apr 20 10:37:47 xxxx audit[xxxx]: user xxxx@xxxx changed configuration to /conf/backup/config-1618907867.0236.xml in /api/routes/routes/setroute/xxxx-xxxx-xxxx-xxxx-xxxx
```
