### ISSUE TITLE
Issue while creating Firewall rules

### ISSUE THREAD

**Issue by bharathmsd7** [opnsense/core#4926]
**Whenever I try to add Firewall Rule It throws an error**

What  I did is Firewall -> Rules -> LAN
Added a Firewall rule to Block the HTTP request.
I Tried with other rules too, same problem exist.
Went through the forum (https://forum.opnsense.org/index.php?topic=21232.0). It says, this may be due to the browser cache or a old browser. 
But I tried it in a freshly installed browser.

Following error message is in the log

**PHP Errors**
 PHP Warning:  in_array() expects parameter 2 to be array, string given in /usr/local/www/firewall_rules_edit.php on line 1222

**System Information**

User-Agent Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.128 Safari/537.36
FreeBSD 12.1-RELEASE-p12-HBSD #0  3c6040c7243(stable/21.1)-dirty: Mon Jan 25 12:27:52 CET 2021     root@sensey:/usr/obj/usr/src/amd64.amd64/sys/SMP amd64
OPNsense 21.1 500892915
Plugins os-dyndns-1.23 
Time Thu, 15 Apr 2021 18:18:38 +0530
OpenSSL 1.1.1i  8 Dec 2020
PHP 7.3.26

**Comment by fichtner** [comment]
You should update to 21.1.4 and see the issue disappear...

**Comment by bharathmsd7** [comment]
> You should update to 21.1.4 and see the issue disappear...

Thanks for that. I made Firmware update to 21.1.4, Now its working fine.
