### ISSUE TITLE
Feature Request: Show aliases in firewall rule list tooltip

### ISSUE THREAD

**Issue by 8191** [opnsense/core#493]
It would be nice to see a list of elements hidden behind an alias within a tooltip when hoovering over the name of an alias in the firewall rule list.

**Comment by AdSchellevis** [comment]
We had some tooltips with different implementations earlier, but switched to the current solution (with links to the aliases) to make things more consistent.
Very often the aliases contain more items then can be displayed nicely in the tooltip, which results in incomplete overviews.
 
Personally I don't see the tooltips being reintroduced at short notice, but if they are reintroduced, they need to have a single clear implementation across the system.

**Comment by 8191** [comment]
What about showing the description in a tooltip?

The point is, that the names are quite restricted in its available character set (a-zA-Z0-9_), so sometimes I cannot really choose a good name for a specific alias. Being able to see the description within the firewall rule set, would save me from some clicks to the 'Alias' page.

**Comment by AdSchellevis** [comment]
Good idea, we could use the standard bootstrap tooltips in the different grid overviews, avoiding the need of building new things here.
Let's keep this one open.

**Comment by AdSchellevis** [comment]
This one looks solved with the PR provided last month, I'm going to close it now.
