### ISSUE TITLE
RADVD  using VIP subnet as primary address if there is a leading zero in any part of the VIP address.

### ISSUE THREAD

**Issue by marjohn56** [opnsense/core#4933]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x ] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [ x] I have searched the existing issues and I am convinced that mine is new.

RADVD using VIP address as the primary address; VIP address not detected as such.

Create a VIP with zero's in the address, such as fdc9:0bf4:80a7:a30c::1

**Expected behavior**

Should be detected as a VIP address, but it's not.

radvd.conf should contain two subnets, one the primary, one the VIP. If the address is entered as above the comparison fails and only the VIP subnet is added to radvd.conf

OPNsense 21.1.4_16-amd64
FreeBSD 12.1-RELEASE-p15-HBSD
OpenSSL 1.1.1k 25 Mar 2021

PR issued to correct this: #4932

**Comment by marjohn56** [comment]
Changed subject to more reflect the issue.

**Comment by maurice-w** [comment]
🤣
That's one of these weird ones you can really only find by chance, isn't it?
(I use IPv6 VIPs, which work correctly, but did indeed enter them without leading zeros. Just out of habit, not because I thought it might cause issues.)

**Comment by marjohn56** [comment]
I was responding to an issue where the OP said only the VIP address is advertised, now I know we went through this last year, so it was either a regression or finger trouble... so I thought. I just happened to enter a random ULA, guess that was a lucky address. Now, if I can only do the same thing for the lottery I'd be really happy! 

It did lead me on to something else though, should dhcpdv6 be able to hand out ULA addresses too?

**Comment by maurice-w** [comment]
I think we briefly discussed VIP support for dhcpd6 last year, but postponed it. If you have a lot of spare time, why not? ;-) Being able to hand out addresses from VIP subnets definitely would make sense.
About VIP PD, I'm not so sure. Given the fact that VIPs are always static, I would have to think about a use case which could not be solved by static routes.
Before addressing such PD edge cases, maybe a more fundamental issue should be solved first: PD doesn't work if the downstream router only requests a prefix, but not an address. We discussed this on the forum a long time ago and I think you came to the conclusion that there is no easy solution. And I never opened an issue for it. I probably should.

**Comment by marjohn56** [comment]
I've just tried it using the 'shared-network' config option, what I was seeing was only the ULA addresses being given out; probably a  deeper understanding of what's meant to happen would help but a five minute google doesn't give much info on it. Bit of an edge case.

**Comment by marjohn56** [comment]
The issue with the prefix only is a tad more complex and my brain says no at the moment. Get's complex too as I would need to start messing with the route tables etc on my primary and that could lead to a shouting match with SWMBO when she cannot successfully surf the shopping channels! :)
