### ISSUE TITLE
IPSec private networks not added to auto NAT rules

### ISSUE THREAD

**Issue by keithjjones** [opnsense/core#4948]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [ X ] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [ X ] I have searched the existing issues and I am convinced that mine is new.

**Describe the bug**

A clear and concise description of what the bug is, including last known working version (if any).

*Tip*: to validate your setup was working with the previous version, use opnsense-revert (https://docs.opnsense.org/manual/opnsense_tools.html#opnsense-revert)

I downloaded 21.1 and updated to latest release today. I set up IPSec, mobile road-warrior style. I used the network 10.0.1.0/24 for the mobile clients. I left NAT on the default (Auto) setting and the 10.0.1.1 IP address is leaving the WAN port and never making it back. I added a manual NAT rule and it took care of the issue. You might want to add a rule like this with the Auto NAT setting so the user does not have to add it, or add the need for manual NAT to the documentation. Screenshot of my rule is included. Thanks!

**To Reproduce**

1. I described it above.

**Expected behavior**

You would expect private IPSec IP addresses to be NAT'd.

**Describe alternatives you considered**

I wrote my own rule.

**Screenshots**

Attached.

**Relevant log files**

If applicable, information from log files supporting your claim.

N/A

**Additional context**

N/A

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 21.1.5-amd64FreeBSD 12.1-RELEASE-p16-HBSDOpenSSL 1.1.1k 25 Mar 2021

![image](https://user-images.githubusercontent.com/5360855/116146318-5e343e80-a6ac-11eb-8407-64edeb7241e7.png)

**Comment by keithjjones** [comment]
This was also a vmware session.

**Comment by nzkiwi68** [comment]
I don't see this as an issue.

If OPNsense was to auto add NAT rules for road warrior tunnel all situations for IPSEC, then, what about OpenVPN or site to site VPN tunnels that also tunnel all?

Pretty normal to have to write your own NAT rule in this case.
Also, the code required to parse IPSEC and OpenVPN and more, looking for these type of situations would be very complex.

However, perhaps the OPNsense documentation could make mention of the need to write your own NAT rule.
[https://docs.opnsense.org/manual/how-tos/ipsec-road.html](url)

**Comment by keithjjones** [comment]
It was definitely an issue for me that unnecessarily killed a big chunk of my day.  This could have easily made me move on to another open source routing option thinking OpnSense was broken had I been a less technical user.  That would have been a shame since it is a very simple fix if you either tell the user about it or do it for them like the NAT screen suggests.  

It doesn't make sense to me to automatically NAT the LAN but not NAT the IPSec/OpenVPN or any other private IP address space interface going out the WAN, especially if you are advertising to the user you are taking care of things automatically in the NAT screen.  That's not a consistent message.  It's just three address spaces you can add to the NAT rules (10.X.X.X, 192.168.X.X, 172.16-31.X.X) on the WAN, which could even be a checkbox somewhere in the VPN setup screens.  It does not seem that complicated.  At a minimum I would put in a big warning or user prompt this rule must be set up just like setting up the two phases for IPSec or things won't work.  An unsuspecting user will be sending their internal IP traffic to the WAN automatically, especially since you use all private IP addresses as your examples here:

https://docs.opnsense.org/manual/how-tos/ipsec-road.html

If you disagree and think this still is not an issue, feel free to close this as I personally know how to fix this bug in OpnSense.  I'm trying to report this to hopefully help you increase the OpnSense user base.  Thanks.

**Comment by AdSchellevis** [comment]
@keithjjones looking at the code, it looks like a bug indeed, the intend was to add mobile networks to the outbound nat rules. https://github.com/opnsense/core/commit/5e5e2ada3a680ae3f20ab14f2e3e2d17ea69ec62 should fix it, thanks!

**Comment by gecko-dev** [comment]
The same behavour happens on the new Swanctl.
Adresses/Networks from the new Poolinterface not added to auto NAT rules.

**Comment by fichtner** [comment]
IPsec connections GUI does not offer automatic rules.

**Comment by gecko-dev** [comment]
For Clarification

VPN > IPSEC > mobile Clients > Virtual IPv4 Adress Pool >> NAT-Rule added automaticly
VPN > IPSEC > Connections > Pools >> NAT-Rule  must be added manually

**Comment by AdSchellevis** [comment]
that is indeed a correct conclusion, you have to add suitable rules manually.
