### ISSUE TITLE
Add support for OpenVPN Client Specfic Overrides by username when using LDAP password authentication

### ISSUE THREAD

**Issue by nzkiwi68** [opnsense/core#4951]
**Important notices**

- [X ] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X ] I have searched the existing issues and I am convinced that mine is new.

**Is your feature request related to a problem? Please describe.**

21.1.5 OpenVPN supports Client Specific Overrides only when using X.509.
If you are using OpenVPN with additional User authentication and would like to pass client specific overrides based on the username logging in, this does not work.

Remote Access (SSL/TLS + User Auth) - the OpenVPN client specific overrides do not work for the username logging on.

**Describe the solution you like**

Please add the ability for OpenVPN Client Specific Overrides to match X.509 or the username for VPN's using password authentication.

**Additional context**

pfSense help states:
_Enter the X.509 common name for the client certificate, or the username for VPNs utilizing password authentication. This match is case sensitive._
![OpenVPN](https://user-images.githubusercontent.com/67399588/116338354-b3e52400-a82f-11eb-8c60-3e6152323d71.PNG)
![pfSense](https://user-images.githubusercontent.com/67399588/116338540-fe66a080-a82f-11eb-9b37-ab1bb70c34c4.PNG)

**Comment by AdSchellevis** [comment]
did you check "force CSO login matching" on the server? I think it's only the description that differs here.
![image](https://user-images.githubusercontent.com/9783985/116385054-ba1bd600-a818-11eb-93be-b3654599173f.png)

**Comment by nzkiwi68** [comment]
You're right!

I did not understand the "force CSO login matching" option until you pointed it out to me. It works perfectly with this option selected.

Thanks and sorry about wasting your time.

**Comment by AdSchellevis** [comment]
no problem,  we can always use help with improving the documentation on various topics (https://github.com/opnsense/docs)
