### ISSUE TITLE
RADVD: CARP aliases missing and RA Interface option won't change source address

### ISSUE THREAD

**Issue by vnxme** [opnsense/core#4953]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I have searched the existing issues and I am convinced that mine is new.

**Describe the bug**

There is an option in RADVD configuration called "RA Interface". As suggested by the help text, the user can "select the interface for the router advertisement (RA) daemon". The list basically contains 3 options: 
- dynamic = default behaviour
- static = adding DeprecatePrefix off for each prefix and RemoveRoute off for ::/0 route
By the way, it seems  https://github.com/opnsense/core/commit/028b129f8715fe72b071a88026599fd7e846a9ea still hasn't been released as of 21.1.5.
- IPv6 CARP address(-es) = completely the same as static

However, it is possible to create an alias IPv6 for CARP (e.g. you may have a CARP IPv4 with VHID 254 and an alias IPv6 with the same VHID on one interface). And the **problem A** is that such CARP aliases are missing in the RA interface list. A possible reason is https://github.com/opnsense/core/blob/af587e812a7b8d96cf3fd84869dc7e00bbfe09b3/src/etc/inc/util.inc#L827-L850

What is more, the **problem B** is that the configuration doesn't match the help text provided for the RA Interface option. If you select an IPv6 CARP in the RA Interface list, the RADVD (and even DHCPDv6) configuration won't change a bit. But this option, as far as I understand the intention, is about chaging the source IP of the daemon and its behaviour when the daemon restarts.

**Expected behavior**

- (A) Both natural IPv6 CARP addresses and alias IPv6 addresses for other CARP addresses on the interface should be listed (https://github.com/opnsense/core/issues/4934 seems to be related);
- (B) Unless RA Interface is dynamic or static, the RADVD should use the selected virtual IP as a packet source (it seems like AdvRASrcAddress is needed and that is what https://github.com/opnsense/core/issues/4897 is about).
- (C) Overall, the RA Interface option itself is rather complicated for understanding in the way it is implemented today, so it is also possible to divide it into 2 options: a DeprecatePrefix switch and an AdvRASrcAddress multiselectable list.

**Describe alternatives you considered**

Don't use high availability options OPNsense provides and CARP in particular.

**Environment**

OPNsense 21.1.5 (amd64, OpenSSL)

**Comment by fichtner** [comment]
A)

As far as I understand CARP aliases are a newer concept that may not be properly interpreted everywhere. A patch here would be a better first step.

B)

> But this option, as far as I understand the intention, is about changing the source IP of the daemon and its behaviour when the daemon restarts.

You can't change a source address to a CARP address. It violates the protocol.

C)

I agree it's complicated, but only because the network setup inherently is as well. Adding more tuning settings does not help the argument but makes it more problematic IMO.


Cheers,
Franco

**Comment by fichtner** [comment]
All code is in place for upcoming 22.1.b2.
