### ISSUE TITLE
Virtual IPs: impossible to add multiple fe80::/64 CARP addresses

### ISSUE THREAD

**Issue by vnxme** [opnsense/core#4955]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I have searched the existing issues and I am convinced that mine is new.

**Describe the bug**

There may be such circumstances that you have several VLANs and you would like to create an IPv6 link-local CARP for each of them, e.g. fe80::1:1/64 (inspired by [this article](https://fy.blackhats.net.au/blog/html/2018/11/01/high_available_radvd_on_linux.html)). As of 21.1.5, it seems to work fine when you add the first one, but when it comes to the second one, the web interface throws an error saying "This IP address is being used by another interface or VIP". In other words, when validating the input fields, the page doesn't take into account the scope of fe80::/10 addresses. Thus, now you are locked with only one IPv6 link-local CARP per OPNsense machine.

**To Reproduce**

1. Go to Interfaces -> Virtual IPs -> Settings
2. Add a new CARP for some interface, e.g. fe80::1:1/64 and VHID 1
3. Copy this CARP, change interface and try to save

**Expected behavior**

Since fe80::/10 addresses are link scoped, the setup with multiple CARP addresses of this type is valid and should be possible.

**Describe alternatives you considered**

Don't use high availability options OPNsense provides and CARP in particular.

**Environment**

OPNsense 21.1.5 (amd64, OpenSSL)

**Comment by fichtner** [comment]
A patch already exists via forum discussion: https://github.com/opnsense/core/commit/2b7beb78b3804f62d9fe804fe614ca7b20284e43

**Comment by vnxme** [comment]
@fichtner That's it, thank you! Do you plan to release it as a part of 21.1.6?

**Comment by fichtner** [comment]
@vnxme not 100% sure about this change. 21.1.7 is probably safer as I am not much available for the next month.
