### ISSUE TITLE
Is making OpenVPN optional (move it to plugins repo) possible?

### ISSUE THREAD

**Issue by jokay** [opnsense/core#4961]
**Important notices**

Our forum is located at https://forum.opnsense.org , please consider joining discussions there in stead of using GitHub for these matters.

Before you ask a new question, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues and I am convinced that mine is *(hopefully)* new.

--

As someone no longer using OpenVPN at all *(switched everything to WireGuard)* I suggest making OpenVPN optional and move it (all dependencies)) to the `plugins` repo, do you think this is possible?

In fact, this is what motivated me to create this issue :wink:

![openvpn](https://user-images.githubusercontent.com/18613935/116604240-250b0100-a92e-11eb-8e97-19e9995a0e56.png)

**Comment by fichtner** [comment]
As far as I understand we don't use deferred authentication so it's a false positive. OpenVPN will probably not move out of core soon. ;)

Also we added 2.4.11 for 21.1.6 next week. So I am going to close this...


Cheers,
Franco

**Comment by jokay** [comment]
> OpenVPN will probably not move out of core soon. ;)

Well, I don't understand why this should be part of the core but ok :wink:

**Comment by fichtner** [comment]
OpenVPN and IPsec are integral tools of day to day networking. Installing via plugin is possible, but more work for all involved. If you don't use vulnerable code you are very much ok. :)
