### ISSUE TITLE
ui: change icon for "restart service" to fa-repeat

### ISSUE THREAD

**Issue by Batnun** [opnsense/core#4972]
Too many times I find myself clicking on "Refresh", but accidently choosing "restart service" instead. Is it possible to change the restart icon?

![Screenshot_1](https://user-images.githubusercontent.com/13527785/117000300-c8666800-acd8-11eb-9573-40a450779b5d.png)

**Comment by fichtner** [comment]
Change it to what exactly? https://fontawesome.com/v4.7.0/icons/

**Comment by Batnun** [comment]
I'm not an expert, and have no experience in UI/UX, but maybe something like that?
https://www.onlinewebfonts.com/icon/487163

**Comment by fichtner** [comment]
I posted the link to the relevant font awesome for a reason. We are likely not adding another font library.

**Comment by Batnun** [comment]
Ok, so how about changing the "restart service" to one of the following options? It just needs to be different...
https://fontawesome.com/v4.7.0/icon/retweet
https://fontawesome.com/v4.7.0/icon/repeat

**Comment by mihakralj** [comment]
Just to complete the circle from a [reddit discussion](https://www.reddit.com/r/OPNsenseFirewall/comments/n4lv9f/refresh_and_restart_service_icons_are_identical/) :

Restart icon can be overloaded in the `main.css` with:
`.fa.fa-refresh.fa-fw::before {content: "\f079";}` - retweet icon
`.fa.fa-refresh.fa-fw::before {content: "\f01e";}` - repeat icon
`.fa.fa-refresh.fa-fw::before {content: "\f110";}` - spinner icon

Beauty is in the eye of beholder, but:
- spinner icon is a no-go as we already use its animated version to signal to wait (for API call returns)
- repeat icon makes it even more similar to a browser refresh icon
- retweet icon is commonly used to RETWEET stuff - and we don't want to retweet the Unbound status!

**Comment by Batnun** [comment]
Maybe, but anything is better than two IDENTICAL icons, very close to each other, with completely different purpose...

**Comment by fichtner** [comment]
I don't mind fa-repeat if it brings us an inch closer to the optimal solution.

**Comment by mimugmail** [comment]
Today I powered off a customer Firewall instead of rebooting. Things happen when your not focused. Quite sure it may happen to others also when Icon changes. But indeed, same Icons on same area are confusing.
Confirmaton warning when hitting restart? :)

**Comment by fichtner** [comment]
> Confirmaton warning when hitting restart? :)

On the service or the firewall? oO

**Comment by mimugmail** [comment]
Service Icon in screenshot. A bootstrap warning asking If you really want to restart the service

**Comment by fichtner** [comment]
The worst thing that could happen is remote lockout. ;) Let’s start with the icon and see what happens.

**Comment by mihakralj** [comment]
@fichtner what are your thoughts to refresh the iconset to a bit younger fontawesome? New duotone icons look amazing:
![image](https://user-images.githubusercontent.com/31756078/117059902-2abd6980-acd5-11eb-8773-cafabfefbb4a.png)
![image](https://user-images.githubusercontent.com/31756078/117059968-3872ef00-acd5-11eb-99b3-6b4203ba5333.png)

**Comment by fichtner** [comment]
These are still conceptually the same icons we have right now? Color-coding helps distinguish, but also makes it harder to explain/document.

**Comment by mihakralj** [comment]
The same set as the good ol' v.4.7 we have today, except this one is from v.6.0 font.
How about I bake the new style into one OPNsense theme and then you be the judge if we push it to the main branch?

**Comment by mihakralj** [comment]
Attached is a theme that is identical to the default OPNsense theme, except it includes FontAwesome 6 icons. The disabling of current FontAwesome 4 happens in theme.js alongside with injection of three checkboxes that you will see in the top right corner:
- no checkboxes set: Solid icons (.fas)
- first checkbox set: Duotone icons (.fad)
- second checkbox set: light icons (.fal)
- third checkbox set: regular icons (.far)

I believe that the new FontAwesome icon pack includes much better/diverse choices for icons than what we are constrained to today. Few screenshots:
![image](https://user-images.githubusercontent.com/31756078/117100886-c5e02e80-ad29-11eb-8f2f-002ce08e98ad.png)
![image](https://user-images.githubusercontent.com/31756078/117100902-d4c6e100-ad29-11eb-9820-c799bd5b0ab6.png)
![image](https://user-images.githubusercontent.com/31756078/117100913-ddb7b280-ad29-11eb-86a5-741ceee81f09.png)
![image](https://user-images.githubusercontent.com/31756078/117100932-e6a88400-ad29-11eb-8d48-7fcb905a582f.png)

[fontawesome6.zip](https://github.com/opnsense/core/files/6425189/fontawesome6.zip)

**Comment by fichtner** [comment]
Updating to newer bootstrap is certainly a good idea, although a bit out of scope for this issue. Happy to review a minimal patch for the core theme although that won’t be included in 21.1.x for sure. We have to make sure all older themes still work and all icons are gracefully replaced (network time seems to be gone).

**Comment by mihakralj** [comment]
there is a `shims.css` included in FontAwesome 6 - and it remaps most (but not all) old icons into new ones.
If there is interest, I can create a Pull Request with a theme that can help us fully validate and test the new **FontAwesome** and **Bootstrap** library.
