### ISSUE TITLE
rules processing problem with a tunnel through a tunnel

### ISSUE THREAD

**Issue by boistordu** [opnsense/core#4974]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I have searched the existing issues and I am convinced that mine is new.

**Describe the bug**

this a following on the bug: https://github.com/opnsense/core/issues/4973

It's an openvpn tunnel inside a wireguard tunnel.
In the first case, you can see that there is no rules to wg0 which is for what I can understand, expected.
In the second case which is the same configuration conceptually, then all of a sudden the rules processing system is mixing all those rules between the 2 links. 

on both openvpn links there are some portforwarding rules. So if the second case is the normal situation then I should have a lot more rules in the first case.

*Tip*: to validate your setup was working with the previous version, use opnsense-revert (https://docs.opnsense.org/manual/opnsense_tools.html#opnsense-revert)

**Expected behavior**

rules should be contained to one interface each other.

**Screenshots**

**Relevant log files**
[ruleswg0.txt](https://github.com/opnsense/core/files/6422171/ruleswg0.txt)
[ruleswg1.txt](https://github.com/opnsense/core/files/6422173/ruleswg1.txt)
[rules.txt](https://github.com/opnsense/core/files/6422175/rules.txt)

If applicable, information from log files supporting your claim.

**Additional context**

this is firewall for an isolated server hosting several VMs which are separated from the main network. 

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 21.1.5-amd64
FreeBSD 12.1-RELEASE-p16-HBSD
OpenSSL 1.1.1k 25 Mar 2021

a vm in fedora server 34

**Comment by boistordu** [comment]
@AdSchellevis as here, 2 same scenario, 2 same configuration, different result and you are labeling it as community support where if find pretty odd to actually have very different listing of rules which you can compare to the whole one.

**Comment by AdSchellevis** [comment]
as @fichtner already stated in the other ticket (https://github.com/opnsense/core/issues/4973), its part of the triage process.
