### ISSUE TITLE
Default gateway lost on CARP master after failback on HA cluster setup with single public IP

### ISSUE THREAD

**Issue by bbtaeuber** [opnsense/core#4977]
Hi everybody!

This problem still occurs in version 21.1.5 (again).

Original issue in https://github.com/opnsense/core/issues/3128

**Comment by mimugmail** [comment]
Logs, screenshots, anything? HA works in general so it's an individual problem and needs proper description.

**Comment by bbtaeuber** [comment]
My colleague has a suggestion what the reason for this behaviour might be. We can't test before Tuesday next week.
I'll keep you informed. Please don't close this issue before.

**Comment by kenshin33** [comment]
@bbtaeuber could you share that suggestion ... I might be able to test!
@mimugmail the failover works  but the transition from MASTER to BACKUP takes away the default gateway with it (on the now backup). 
Also, may be not the place to discuss here (it needs a an issue on it's own), in my setup the backup would still want to use the wan floating ip to communicate with the exterior world, need  to toggle carp on/off (temporarily disable CARP -> enter persistent CARP Maintenance mode -> Leave Maintenance mode -> Enable CARP)   to make it use it's own ip, and that again takes down the default gateway on the backup.

**Comment by mimugmail** [comment]
Please open a thread in forums and we discuss it there
