### ISSUE TITLE
Squid proxy blacklistS (Remote Access Control Lists)

### ISSUE THREAD

**Issue by spirillen** [opnsense/core#4979]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[-] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md

[X] I have searched the existing issues and I'm convinced that mine is new.

[X] The title contains the plugin to which this issue belongs

**Describe the bug**
A clear and concise description of what the bug is, including last known working version (if any).

*Tip*: to validate your setup was working with the previous version, use opnsense-revert (https://docs.opnsense.org/manual/opnsense_tools.html#opnsense-revert)

**To Reproduce**
1. Go to webproxy 
2. Click on Remote Access Control Lists
3. Add some _non_ `shallalist.de` to the blacklists
4. Disregarding which alternative source that is added, only the shellalist can be loaded

**Expected behavior**
All lists should be downloaded and added to the ACL (squid.conf is currect)

**Screenshots**
![image](https://user-images.githubusercontent.com/44526987/117283425-10ff5c00-ae66-11eb-80ce-ab8473ef54d1.png)

![image](https://user-images.githubusercontent.com/44526987/117283639-45731800-ae66-11eb-9552-a796eab6ba04.png)

**Relevant log files**
unable to sendback response [OK ] for [proxy][fetchacls][None] {c95780d2-f5e1-4362-9335-a84cdf5f3ce5}, message was Traceback (most recent call last): File "/usr/local/opnsense/service/modules/processhandler.py", line 202, in run self.connection.sendall(('%s\n' % result).encode()) BrokenPipeError: [Errno 32] Broken pipe
![image](https://user-images.githubusercontent.com/44526987/117283886-8e2ad100-ae66-11eb-8cea-3056f12b4763.png)

**Additional context**
If you disable shella and then `apply` or `Download ACL & apply` the shella list are removed (as should be), but then if you enable all lists from the screenshots nothing is downloaded and applied.

```conf
# ACL lists

# ACL - Remote fetched Blacklist (remoteblacklist)
acl remoteblacklist_mex dstdomain "/usr/local/etc/squid/acl/mex"
acl remoteblacklist_ut1 dstdomain "/usr/local/etc/squid/acl/ut1"
acl remoteblacklist_shallalist dstdomain "/usr/local/etc/squid/acl/shallalist"
acl remoteblacklist_mesd dstdomain "/usr/local/etc/squid/acl/mesd"

# ACL list (Deny) remoteblacklist_mex
http_access deny remoteblacklist_mex
# ACL list (Deny) remoteblacklist_ut1
http_access deny remoteblacklist_ut1
# ACL list (Deny) remoteblacklist_shallalist
http_access deny remoteblacklist_shallalist
# ACL list (Deny) remoteblacklist_mesd
http_access deny remoteblacklist_mesd
```
```shell
# ls -lha /usr/local/etc/squid/acl
total 372
drwxr-x---  2 root  squid   512B May  6 12:26 .
drwxr-xr-x  8 root  squid   512B Apr  5 02:00 ..
-rw-r-----  1 root  squid   361K May  6 12:24 shallalist
```

**Environment**
Versions: OPNsense 21.1.5-amd64
                FreeBSD 12.1-RELEASE-p16-HBSD
                OpenSSL 1.1.1k  25 Mar 2021

Intel(R) Xeon(R) CPU E5504 @ 2.00GHz (8 cores)
Network Broadcom

`https://bsd-hardware.info/?probe=59c59bda2a`

**Comment by AdSchellevis** [comment]
leading the lists likely costs more than 120 seconds, after which the frontend stops listening for a response. you can easily test if that's the case by executing the following command on a console and see how long it takes to return:

```
/usr/local/opnsense/scripts/proxy/fetchACLs.py 
```

**Comment by spirillen** [comment]
Hey @AdSchellevis thanks for your feedback, however your suggestion doesn't reply any time taken in console

![image](https://user-images.githubusercontent.com/44526987/117372962-b21ffe00-aeca-11eb-90ec-71cf2cffa755.png)

```shell
# python3.7 /usr/local/opnsense/scripts/proxy/fetchACLs.py
root@firewall:~ # time python3.7 /usr/local/opnsense/scripts/proxy/fetchACLs.py
0.474u 0.031s 0:00.50 100.0%    5+179k 0+0io 0pf+0w
root@firewall:~ #
```

And another thing That crossed my mind I have forgotten to mention in the original posts is:

This issue have been persistent since I started using OpnSense back in november/december last year. To that story belongs that, until middle of Marts of was hooked up on a 150/50Mb connection with a usual time to first response was approximatly 40ms, also to the lists mentioned.

Since then I've been connected through the worst ADSL I've ever been tied to, at best 8/0.75Mb

You also rights if it times out before 120 sec..., that maid me take a second look, to see if there was a place to change such default timeout/Wait, but did not "just" spot such option, is there a way to change this system wise or is that only something to be done in the python script it self?
Alternatively, I would suggest such option for others on a very bad(poor connection.

A few curl calls to the lists.

Was any of this any helpfully response?

```
time curl -I 'https://raw.githubusercontent.com/My-External-Stuff/squid-proxy/master/blacklists.tar.gz'

real    0m1,021s
user    0m0,017s
sys     0m0,018s
```

```
time curl -I 'http://squidguard.mesd.k12.or.us/blacklists.tgz'

real    0m59,895s
user    0m0,015s
sys     0m0,006s
```

```
time curl -I 'ftp://ftp.ut-capitole.fr/pub/reseau/cache/squidguard_contrib/blacklists.tar.gz'

real    0m4,193s
user    0m0,009s
sys     0m0,009s
```

**Comment by AdSchellevis** [comment]
@spirillen hmm, I'm not entirely sure why the scripts exits immediately on your end, but the traceback in the original ticket suggests that it didn't exit that fast the first time for some reason. 

We could probably change the broken pipe message to a warning, since it's usually a sign that the client stopped waiting for a response (while the server completed the request). Often it's nothing to worry about, the timeout currently can't be configured, but waiting for more than 2 minutes usually isn't great either.

**Comment by spirillen** [comment]
> Often it's nothing to worry about, the timeout currently can't be configured, but waiting for more than 2 minutes usually isn't great either.

Agreed, I would even say a default of 60 would bee better, AND then have the ability to change this value based on the individual user experience (connections)

> hmm, I'm not entirely sure why the scripts exits immediately on your end

A debug level logging would have been nice, to see where the script is actually failing, IF there is such option (as I haven't spotted it yet) Please let me know and I'll share it, it could also bee I found a local issue that prevent this from succeeding :smirk:

**Comment by AdSchellevis** [comment]
The script itself logs in the general system log if I'm not mistaken, but if it runs longer than 120 seconds it likely didn't fail. (process is detached from the frontend, so configd reports it can't reports status back, but the action itself would have run normally in that case)

**Comment by spirillen** [comment]
This issue still persist, with the same errors even that 2 new factors are present

  1. On low latency fiber (Plenty of free bandwidth)
  2. OPNsense 21.1.7_1-amd64 | FreeBSD 12.1-RELEASE-p18-HBSD | FreeBSD 12.1-RELEASE-p18-HBSD

Errors are the very same as earlier in this thread. Anybody how have another idea to what to do? I would actually like to have these filters activated.
