### ISSUE TITLE
DHCP leases are not listed as used

### ISSUE THREAD

**Issue by upended** [opnsense/core#4985]
**Describe the bug**
Opnsense 192.168.1.1 (FW1) is the DHCP server. There is also a secondary internal FW(2) 192.168.1.2 (Address on Opnsense LAN) which is configured for Dynamic NAT.  Clients 192.168.2.X (behind FW2) pulls IP's from the FW1 DHCP server, however, the leases tab is missing entries for these clients (both on show active and static leases only, and show all configured leases).  

client-A         <->        LAN    FW2     WAN        <->        LAN      Opnsense     WAN
192.168.2.10       192.168.2.1        192.168.1.2           192.168.1.1                   Public IP

**To Reproduce**
Configure opnsense as a DHCP server.
Configure a second FW to access opnsense LAN and use 1-to-1 IP NAT.

**Expected behavior**
For the DHCP IP addresses in use to be listed on the Leases tab as to be able to revoke / manage them.
When there are 10 clients in the FW2 LAN connecting to FW1, each should have an entry with the DHCP address, i.e. 192.168.1.10-19 and the FW2 MAC address. 

**Describe alternatives you considered**
Created an additional lease pool, did not correct issue.

**Screenshots**
Included

![Capture-C](https://user-images.githubusercontent.com/63566363/118088161-7fb74a80-b37b-11eb-90ca-168e00128e53.JPG)
![Capture-B](https://user-images.githubusercontent.com/63566363/118088166-804fe100-b37b-11eb-86e4-83a184803498.JPG)
![Capture-A](https://user-images.githubusercontent.com/63566363/118088167-81810e00-b37b-11eb-86de-b079bc6c8e57.JPG)

**Relevant log files**
Refer to images.

**Additional context**
Issue occurs whether FW2 has a static or reserved DHCP address. 

**Environment**
Versions | OPNsense 21.1.5-amd64FreeBSD 12.1-RELEASE-p16-HBSD

**Comment by upended** [comment]
Has this been looked into?

**Comment by fichtner** [comment]
I’m unsure what the issue is supposed to be. Is everything in the leases file on the disk or not? Have you tried 21.7 yet?

**Comment by upended** [comment]
The FW is on 21.7.1.  

On opnsense, there are 2 DHCP pools for LAN.  
LAN Pool 1 is 192.168.1.3-19
LAN Pool 2 is 192.168.1.20-50
(Image 3) The leases showing on Services:DHCP:Lease are only from Pool2.  There are no records for Pool1.

(Image 2) Shows computers requesting and receiving IPs from Pool1.

(Image 1) Show computers from Pool1 having active connections.

Example:  Looking at IP 192.168.1.10, The computer is requesting and receiving an IP from the DHCP server (Pool1), we see activity for that IP on the firewall live view.  Looking at the lease page, it's missing.   

All the IP's that can be seen as DHCP request (image 2) should also be seen as a lease (image 3)  but when having 2 pools, not all of them are listed as they should be.

**Comment by fichtner** [comment]
So what's in /var/dhcpd/var/db/dhcpd.leases then?

**Comment by fichtner** [comment]
I unified DHCPv4 lease read with the code in DHCPv6 which is more robust. If the leases still don't show they are not in dhcpd.leases which means we can't do anything about it.

**Comment by upended** [comment]
The IPs for pool 1 are missing from.  If there is more than 1 pool for dhcp addresses, how does opnsense retain information for each one? 

I'm guessing there may be something that is not accounting for multiple pools on the same interface.  Where DHCP has a table automatically configured when DHCP is started for that interface, but it may not have an option to automatically create a second table for that same interface when adding a second pool.

Do you have any additional areas I can look into so you have more information to work with?

**Comment by fichtner** [comment]
There is no special pool handling on our part that would cause leases to disappear.

**Comment by upended** [comment]
They do not disappear, rather never show up on the table as if the table is not to show a second pool.  Would that make a difference?

**Comment by fichtner** [comment]
As I said the only question I have is whether they are in var/dhcpd/var/db/dhcpd.leases from the box that doesn't show them or not... If they aren't there we would be chasing shadows in dhcpd server code territory which is out of our scope. If they are in there and our reader is faulty that's likely an easy fix.

**Comment by upended** [comment]
Okay

**Comment by upended** [comment]
Would it be possible to have this listed as upstream, since it appears to be with the DHCP code.

**Comment by fichtner** [comment]
Sure, but we will not be able to keep this open forever.
