### ISSUE TITLE
Firewall live view filters not filtering correctly subsequent to #4730

### ISSUE THREAD

**Issue by upended** [opnsense/core#4988]
**Describe the bug**
In FW Live View, the filters have been configured to using the "is not" option.  The filtered records include entries which should not be included.

This has also been seen when using other combination of filters / variables. As shown with ticket #4730.

Example1:  port is not 53, will display entries contain traffic with port 53.

Example2: host is not 192.168.1.1, will display entries containing traffic with IP 192.168.1.1

**To Reproduce**
Go to Firewall: Log Files: Live View
select a port or ip you would like to filter out of results
select "is not" and enter value.

**Expected behavior**
For records matching the filtered out criteria to not be displayed.  

**Describe alternatives you considered**
The filter stops operating correctly once the negation has been used and effects the filter when selecting multiple criteria are used.

**Screenshots**
![112042607-f1ee7a00-8b04-11eb-9e15-99afe1644be7](https://user-images.githubusercontent.com/63566363/118174491-bd4fbe00-b3e3-11eb-9400-c9877920706d.JPG)

![image](https://user-images.githubusercontent.com/63566363/118174567-dbb5b980-b3e3-11eb-88b3-f5b4e105d10a.png)

**Relevant log files**
none

**Additional context**

**Environment**

OPNsense 21.1.3_3

**Comment by upended** [comment]
Created new ticket, closing.

**Comment by upended** [comment]
Closed wrong ticket.

**Comment by fichtner** [comment]
To make this even more interesting, the new template filter code in 21.1.6 will not save src,dst (host) and srcport,dstport (port) correctly anyway.

**Comment by fichtner** [comment]
@upended can you try this one top of 21.1.6?

    # opnsense-patch 47d6832ed


Cheers,
Franco

**Comment by fichtner** [comment]
One more issue reported via https://forum.opnsense.org/index.php?topic=23309.0 is the add button click area is odd.

**Comment by fichtner** [comment]
I think the last issue will be addressed by @kulikov-a soon enough. Closing. :)

**Comment by upended** [comment]
This ticket should not have been closed.  Please allow for a testing period and for users to respond.  

**Still experiencing issues after patching.**

 # opnsense-patch 47d6832ed
Fetched 47d6832ed via https://github.com/opnsense/core
Hmm...  Looks like a unified diff to me...
The text leading up to this was:
--------------------------
|From 47d6832edcdb447aa5dd4175b92f730803dd065e Mon Sep 17 00:00:00 2001
|From: Franco Fichtner <franco@opnsense.org>
|Date: Fri, 28 May 2021 12:08:24 +0200
|Subject: [PATCH] firewall: change live log group matcher to correctly flip
| logic #4988
|
|---
| .../views/OPNsense/Diagnostics/fw_log.volt    | 57 +++++++++++++------
| 1 file changed, 39 insertions(+), 18 deletions(-)
|
|diff --git a/src/opnsense/mvc/app/views/OPNsense/Diagnostics/fw_log.volt b/src/opnsense/mvc/app/views/OPNsense/Diagnostics/fw_log.volt
|index 6a61515b96..ff1fa04a23 100644
|--- a/src/opnsense/mvc/app/views/OPNsense/Diagnostics/fw_log.volt
|+++ b/src/opnsense/mvc/app/views/OPNsense/Diagnostics/fw_log.volt
--------------------------
Patching file opnsense/mvc/app/views/OPNsense/Diagnostics/fw_log.volt using Plan A...
Hunk #1 succeeded at 388.
Hunk #2 succeeded at 422.
Hunk #3 succeeded at 467.
Hunk #4 succeeded at 688.
done
All patches have been applied successfully.  Have a nice day.
root@firewall:/home/root#
*** FINAL System shutdown message from root@firewall ***

System going down IMMEDIATELY



**Noticed this entry which did not exist before.**

System: Diagnostics: Activity


4220 | elasticsea | 20 | 0 | 3589 | 2274 | uwait | 3 | 0:03 | 0.10% | /usr/local/openjdk8/bin/java -Xms2g -Xmx2g -XX:+UseConcMarkSweepGC -XX:CMSInitiatingOccupancyFraction=75 -XX:+UseCMSInitiatingOccupancyOnly -XX:+AlwaysPreTouch -server -Xss1m -Djava.awt.headless=true -Dfile.encoding=UTF-8 -Djna.nosys=true -Djdk.io.permissionsUseCanonicalPath=true -Dio.netty.noUnsafe=true -Dio.netty.noKeySetOptimization=true -Dio.netty.recycler.maxCapacityPerThread=0 -Dlog4j.shutdownHookEnabled=false -Dlog4j2.disable.jmx=true -Dlog4j.skipJansi=true -XX:+HeapDumpOnOutOfMemoryError -Des.path.home=/usr/local/lib/elasticsearch -cp /usr/local/lib/elasticsearch/lib/* org.elasticsearch.bootstrap.Elasticsearch -d --pidfile=/var/run/elasticsearch/elasticsearch.pid -Epath.conf=/usr/local/etc/elasticsearch{C2 CompilerThread0}
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --




![image](https://user-images.githubusercontent.com/63566363/120866929-baa93a00-c545-11eb-950f-59aea34432d7.png)

**Comment by fichtner** [comment]
7 week of multiple feedback is enough. I don’t think Sensei process info matters here. 

Make sure you have the patch correctly applied. ;)

**Comment by fichtner** [comment]
Nothing wrong with the solution, just a typo in !~ case... dd54795
