### ISSUE TITLE
Logging: Add a symlink for e.g. system.log to system_todaysdate.log for log parsing

### ISSUE THREAD

**Issue by mimugmail** [opnsense/core#4993]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I have searched the existing issues and I am convinced that mine is new.

**Is your feature request related to a problem? Please describe.**

With the new text based logging there is now the chance to follow logfiles with monit and watch for specific events like also asked here: https://github.com/opnsense/core/issues/4197

The problem with the new style is that monit is unable to track wildcard logfiles:
https://stackoverflow.com/questions/50150045/wildcards-in-monit-paths

**Describe the solution you like**

It would be nice to have symlink e.g. /var/log/system/system.log pointing always to the current file of the day.
Probably also naming the file of today just system.log and the day after renaming it like linux logrotate would also work.

**Describe alternatives you considered**

There may be some alternatives like log2mail which should be able to handle this, but one of the biggest lacks compared to commercial vendors is, that there is no watchdog, or proactive events when an event occurs. With this it would be easy to add more defaults to monit, e.g. watching for labels in filter rules (coming soon) and send an alert, for example when you have an URL table alias with known C2C IPs, if you see a dropped packet from inside to outside, there is already an infection and you want to get informed by this as quickly as possible.

**Additional context**

https://www.reddit.com/r/opnsense/comments/na6ts5/logwatch_alternative/

**Comment by AdSchellevis** [comment]
I don't mind adding some logic to present a current view, we do however need to be careful with naming. `/var/log/system.log` would collide with the legacy clog files,  maybe `/var/log/system/latest.log` might be a safer option. (I'm open for other alternatives as well)

**Comment by mimugmail** [comment]
latest.log in each folder would also be fine. I try to find some sane defaults, maybe something like gateway flapping detection.

**Comment by AdSchellevis** [comment]
ok, conceptually this is easy, in practice there's a challenge.

When the files are there, we could easily [re]create symlinks for all directories in `/var/log/`, e.g.
```
ln -s -f /var/log/system/system_20210517.log /var/log/system/latest.log
```

but... `syslog-ng` creates the files when there's data flowing in, so  not all files will be there when the day shifts to the next.

I don't  think we can easily hook something in `syslog-ng` to signal us that a file is created (unless `hook-commands()` triggers on target changes), we could bluntly let cron recreate symlinks every few seconds/minutes/..., but it's not very pretty to be honest.  creating links upfront isn't either (since there's no target in that case)

Suggestions are more than welcome.

**Comment by mimugmail** [comment]
Do you think its worth to ask Peter if there is a way in syslog-ng itself?

https://github.com/opnsense/core/blob/master/src/opnsense/service/templates/OPNsense/Syslog/syslog-ng-local.conf#L37

**Comment by AdSchellevis** [comment]
A thought let's give it a try and looked at syslog-ng's GitHub then found this ticket https://github.com/syslog-ng/syslog-ng/issues/3654, which more or less looks like the functionality we're missing if I'm reading it correctly.

**Comment by mimugmail** [comment]
https://forum.opnsense.org/index.php?topic=24545.msg117705#msg117705

Two more with similar requirements.
No direction is really satisfying :/

**Comment by fichtner** [comment]
I suppose we can set a symlink via cron at 0:01?

**Comment by AdSchellevis** [comment]
nope, we can't since files (and directories) are created on first use, hence the pointer to https://github.com/syslog-ng/syslog-ng/issues/3654

**Comment by fichtner** [comment]
> but... syslog-ng creates the files when there's data flowing in, so not all files will be there when the day shifts to the next.

sure, fair point, but so we update every once in a while instead of once only and else keep the symlink on old "latest" file. All of this only if directories exist. it doesn't make much difference for users of this link?

**Comment by AdSchellevis** [comment]
I was hoping for an upstream fix, there are work arounds, but everything costs time, we will fix this sometime either with a facility available upstream or a workaround which is likely less accurate (cron or watcher).

**Comment by fichtner** [comment]
I just saw that https://github.com/opnsense/core/blob/master/src/opnsense/scripts/syslog/log_archive already exists and is hooked into cron. Just leaving this here as a note to self.

**Comment by fichtner** [comment]
@mimugmail @AdSchellevis dd6a04a should be all there is to it. I added opnsense-log helper in 731a69c to test flexibility and to ease diving into logs. We can extend as needed... it's going to be cool! Close?
