### ISSUE TITLE
Floating rule breaks default deny all 

### ISSUE THREAD

**Issue by btv** [opnsense/core#4994]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [ x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x ] I have searched the existing issues and I am convinced that mine is new.

**Describe the bug**

I noticed while playing with my firewall configuration that a machine was able to talk to the internet while no explicit  rule allowed it to.In researching why, I discovered that a aut-ogenerated firewall rule, was overriding the "deny-all" rule, allowing outside communication.

I believe the autogenerated line seems comes from here: https://github.com/opnsense/core/blob/5e5e2ada3a680ae3f20ab14f2e3e2d17ea69ec62/src/etc/inc/filter.lib.inc#L540.

Though, when I tried commenting that out in my system, the line still appeared in the gui. I'm not sure how to fix this, but I feel like it needs to be. I'm happy to help however I can to get this resolved. 

*Tip*: to validate your setup was working with the previous version, use opnsense-revert (https://docs.opnsense.org/manual/opnsense_tools.html#opnsense-revert)

**To Reproduce**

1. Go to 'Firewall->Rules'
2. Click on 'Floating'
3. Open up the auto-generated rules
4. See bad rule

**Expected behavior**

A line link this shouldn't exist. Breaks the "Default deny-all rule"

**Describe alternatives you considered**

Mentioned in the description to try and fix the problem. I don't know enough about opnsense to know if what I did actually worked.

**Screenshots**

![2021-05-16-103525_1463x35_scrot](https://user-images.githubusercontent.com/61864/118405247-2b8abf80-b634-11eb-9b73-5cc52f654a93.png)

**Relevant log files**

Not sure what I can add here. Happy to upon request.
**Additional context**

:shrug: 
**Environment**

Software version used and hardware type if relevant, e.g.:
OPNsense 21.1.5-amd64
FreeBSD 12.1-RELEASE-p16-HBSD
OpenSSL 1.1.1k 25 Mar 2021

**Comment by AdSchellevis** [comment]
outbound isn't filtered by default, see https://docs.opnsense.org/manual/firewall.html#direction for more details how to construct firewall rules. (this doesn't allow inbound traffic)

**Comment by btv** [comment]
Thank you for the clarification. That is good to know that outbound isn't filtered by default.

**Comment by btv** [comment]
If this rule is there as intended, please feel free to close this ticket.

**Comment by AdSchellevis** [comment]
this rule is indeed as intended, logically it can't be the cause of inbound traffic being allowed (when not already allowed inbound by another rule). You can always discuss on the forum where the issue in your setup might be.
