### ISSUE TITLE
FRR Static Routes

### ISSUE THREAD

**Issue by smalchow** [opnsense/core#4995]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [ x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x ] I have searched the existing issues and I am convinced that mine is new.

**Is your feature request related to a problem? Please describe.**

The problem is, that there is redistribution for kernel (static) routes, connected networks and static routes, however,  there is no way to configure static routes in the FRR configuration, and therefore you can not redistribute static routes anyways, 

Routes that are inserted using gateways and route configurations in "system" are not static routes in FRR speak, they are kernel routes.

**Describe the solution you like**

Add a way to configure FRR static routes, it should probably be a tab in Routing -> General

![image](https://user-images.githubusercontent.com/8308427/118475260-50526600-b70c-11eb-8d8a-512d07d392d5.png)

routes written to FRR like this

https://docs.frrouting.org/en/latest/static.html

should be properly redistributed.

**Describe alternatives you considered**

There is no real alterantive, we can not redistribute Kernel Routes since that is too much

**Comment by mimugmail** [comment]
There is already a ticket in plugins. I will add it when BFD is finished

**Comment by smalchow** [comment]
Sorry, i did not find that, i was search before, which ticket is it so i can watch it

**Comment by mimugmail** [comment]
https://github.com/opnsense/plugins/issues/2284
