### ISSUE TITLE
Dummynet fast io sysctl overwritten later during boot

### ISSUE THREAD

**Issue by dinguz** [opnsense/core#4996]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues and I am convinced that mine is new.

**Is your feature request related to a problem? Please describe.**

A clear and concise description of what the problem is including your motivation for the request,
i.e. "For the purpose of [...] I am missing a solution that will [...]."

I am looking for a way to disable dummynet fast io, as this is documented to mess up the network statistics by allowing some packet to bypass parts of the dummynet flow.

This is achieved by setting net.inet.ip.dummynet.io_fast=0.

The issue is that you can set this tunable in the System ->Settings->Tunables page, but this does not seem to work properly. This is because this sysctl has been hardcoded to 1 in /usr/local/etc/rc.ipfw which gets executed later during the boot process.
Another sysctl has been hardcoded in this file: net.inet.ip.dummynet.hash_size=256

**Describe the solution you like**

(e.g. I would like an input field in the `/ui/firewall/alias` which would add .... to ....)

I would suggest to move these settings to the tunables config page, and list them there, together with a short explanation of why the developers deemed them necessary.

**Describe alternatives you considered**

A clear and concise description of any alternative solutions or features you considered.

Just remove these sysctl settings from /usr/local/etc/rc.ipfw

**Additional context**

Add any other context or screenshots about the feature request here or links to relevant forum thread or similar

**Comment by iMiMx** [comment]
I stumbled across the below, when seeing out of order packets:

https://redmine.pfsense.org/issues/11192

Then I stumbled across your post... whilst not a 'fix' to the fast_io issue, if you set a delay of 1ms on the pipe the consequence is that fast_io is bypassed.

... confirmed I see the same with the hashing issue, only option is to either hack the rc.ipfw you note above, or apply manually.
