### ISSUE TITLE
automatic interface assignment may not be the best thing in the world

### ISSUE THREAD

**Issue by fichtner** [opnsense/core#5]
With em0 and em1 present the config currently skips interface assignment. Want to deploy a better way of doing that consistently. Also, initial IP assignment is missing. Workarounds like the LiveCD exist, but are a little too inconvenient on first glance. via @timelessp (twitter)

**Comment by jschellevis** [comment]
Lets make it more clever and have first two interfaces setup as LAN/WAN or if only one setup as WAN.
Make sure the configmenu option 1 works for manual configuration after bootup.
