### ISSUE TITLE
Add support for image/svg+xml to the portal page system

### ISSUE THREAD

**Issue by havarh** [opnsense/core#50]
If I try to use SVG images in the portal page file as a CSS background image, the SVG file isn't displayed. E.g. this example CSS doesn't work:
input.auth_user {
  background-image: url(captiveportal-user-icon.svg);
}
To fix this I had to edit this file:
/usr/local/etc/inc/system.inc
And add this to the mimetype.assign var:
".svg" => "image/svg+xml",
after doing this the SVG images are shown.
(PS! the same bug also exists in pfSense)

**Comment by jschellevis** [comment]
Thanks' I will add it to fix this issue.
