### ISSUE TITLE
OpenVPN Wizard on 21.1.5

### ISSUE THREAD

**Issue by mac-linux-free** [opnsense/core#5000]
OpenVPN Wizard exits with:

"Fatal error: .... Too few  arguments... cert_create ()"

**To Reproduce**

1. Install 21.1
2. Update to 21.1.5
3. Start OpenVPN Wizard and short after finish the error occurs

4. Downgrade with opnsense-revert -r 21.1.4 opnsense
5. Start OpenVPN Wizard it finishes
6. Upgrade to 21.1.5 again and VPN works but the Wizard does not.

Software version used and hardware type if relevant, e.g.:

OPNsense 21.1.5 (amd64, OpenSSL).
Intel(R) Atom(TM) CPU E3845 @ 1.91GHz (4 cores)
Network Intel® 4x Gigabit

**Comment by fichtner** [comment]
This was https://github.com/opnsense/core/issues/4943
