### ISSUE TITLE
System: Diagnostics: Activity numeric sort order for most colums

### ISSUE THREAD

**Issue by n8falke** [opnsense/core#5004]
**Description**

Trying to find a process with high memory usage is hard, because sorting in System -> Diagnostics -> Activity uses text sorting. So in reverse sort a process with 91 is before 1234.

**Solution**

It would help to get numeric order for PID, PRE, SIZE, RES and if easy to solve for WCPU. If the framework supports time interval sorting getting TIME sorted would be great.

**Comment by hippi-viking** [comment]
- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [  ] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

Hello, I ty to help out here as I noticed the same behaviour. It is basically a duplicate issue of #2130 and it seems that the solution to display/handle units in #3009 no longer applies.

![opnsense-activity](https://user-images.githubusercontent.com/33314937/120286383-b531c280-c2ad-11eb-802c-fa10aef99b72.png)
