### ISSUE TITLE
firewall: NAT rule logging improvements

### ISSUE THREAD

**Issue by pallebone** [opnsense/core#5005]
**Important notices**

Our forum is located at https://forum.opnsense.org , please consider joining discussions there in stead of using GitHub for these matters.

Before you ask a new question, we ask you kindly to acknowledge the following:

- [YES] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [YES] I have searched the existing issues and I am convinced that mine is new.

Hello,

I tried asking my question on the forum, but nobody knows the answer.
https://forum.opnsense.org/index.php?topic=23192.0

Im happy to either continue on the forum or here depending on your preference, but I dont know how to get this information from the logs.

Please let me know your preferred method to proceed and I will do my best to accommodate as you require :)

I believe this information should be exposed because it has security implications, being able to monitor what external addresses internal IP's are accessing.

Looking forward to your insight :) Hope you are having a good day so far :)

Kind regards
Peter

**Comment by pallebone** [comment]
Hi,

If you need any further info please let me know :)

Kind regards
Pete

**Comment by pallebone** [comment]
Additional information from KeyHand here:

https://forum.opnsense.org/index.php?topic=23192.msg112811#msg112811

**Comment by fichtner** [comment]
Hi Peter,

This is a fun one. ;)

When using port forwards and using Filter rule association "pass" with logging enabled will pop up the traffic in the firewall log:

<img width="1396" alt="Screenshot 2021-06-29 at 17 42 56" src="https://user-images.githubusercontent.com/1915288/123829966-2b543400-d903-11eb-9266-e1dc26005605.png">

The problem here is as described a limitation of the filterlog output. However, a state is being created for this redirect rule:

<img width="1411" alt="Screenshot 2021-06-29 at 17 41 11" src="https://user-images.githubusercontent.com/1915288/123830093-48890280-d903-11eb-9ba2-13a756dfc7c2.png">

And you can see the NAT origin...

There are two TODO's here:

1. Try to emulate this with an associated filter pass rule (logging enabled correctly? I couldn't tell from first test as it wasn't working). 

2. Tie states listing closer to port forward rules. One of the issues is that rdr/nat/binat rules do not support labels as far as I understand so tracking is more difficult. We also do not dump the state ID in the filterlog. ;(


Cheers,
Franco

**Comment by pallebone** [comment]
Hello Franco,

Thank you for your reply.

I tried to follow your screenshots but I do not have a "Firewall:Diagnostics:States" page. I only have States dump, States reset, or States summary. This page you have accessed I cannot find.

In addition, if you would like me to check anything please let me know and I will do so :)

Kind regards,
Pete

**Comment by fichtner** [comment]
Hi Pete,

The page I showed is from the upcoming 21.7 release. It sort of replaces the states dump page, although the NAT information is on that older page as well.

With an associated pass rule, using inspect on the development version allows to directly fetch the associated states. Though the logging is incorrect IMO as rdr is no longer logged (not the final action I suppose):

<img width="1179" alt="Screenshot 2021-06-29 at 9 13 25 PM" src="https://user-images.githubusercontent.com/1915288/123854787-6f553200-d91f-11eb-8156-9bdb7b3e7cd1.png">
<img width="1175" alt="Screenshot 2021-06-29 at 9 14 15 PM" src="https://user-images.githubusercontent.com/1915288/123854808-74b27c80-d91f-11eb-8351-306ae2188294.png">
<img width="1176" alt="Screenshot 2021-06-29 at 9 14 28 PM" src="https://user-images.githubusercontent.com/1915288/123854828-78de9a00-d91f-11eb-918f-5799b1b56319.png">


Cheers,
Franco

**Comment by fichtner** [comment]
Hi Pete,

With https://github.com/opnsense/src/commit/bdb244c37d and a separate firewall pass rule it looks like this now:

<img width="1392" alt="Screenshot 2021-06-30 at 09 47 20" src="https://user-images.githubusercontent.com/1915288/123922516-651b4e00-d988-11eb-9ba1-67de2703f9aa.png">

I suppose seeing NAT log pre-NAT and firewall rule post-NAT is the desired result? :)


Cheers,
Franco

**Comment by pallebone** [comment]
Hi Franco,

This is very interesting. how did you manage to achieve this result? 

I do not use the dev version... is there any way I can test this to check what happens my side? It looks like it is showing both the original destination and the destination after the rewrite occurs in your screenshot which is excellent.

Kind regards
Peter

**Comment by fichtner** [comment]
The snapshot kernel to try is:

    # opnsense-update -zkr 21.7.r1_1
    # opnsense-shell reboot


Cheers,
Franco

**Comment by pallebone** [comment]
Hi Franco,

Thank you for your reply. Apologies for bothering you further but I was not able to complete this. This is the output:

Enter an option: 8

root@OPNsense:~ # opnsense-update -zkr 21.7.r1_1
Fetching kernel-21.7.r1_1-amd64.txz: .. failed, no signature found
root@OPNsense:~ # 

Kind regards
Peter

**Comment by fichtner** [comment]
Hi Pete,

Which mirror are you using? The default mirror should be good. The file was only published today.


Cheers,
Franco

**Comment by pallebone** [comment]
Apologies again. It must be something my side. I cannot get it to work.

My settings are:
Mirror: Default
Flavour: Libressl
Type: Community.

Could it be because I am using libressl (not a default setting).

Sorry I feel bad wasting your time. This is most likely due to my specific config its not working so apologies again in advance.

Kind regards
Pete

**Comment by fichtner** [comment]
Sorry, my fault... it's actually:

    # opnsense-update -kr 21.7.r_1

**Comment by pallebone** [comment]
> Sorry, my fault... it's actually:
> 
> ```
> # opnsense-update -kr 21.7.r_1
> ```

No problem, actually it was opnsense-update -zkr 21.7.r_1 but I managed to guess that myself so it has installed. I will test and come back to you in a little while :)

**Comment by pallebone** [comment]
I can confirm that the new patch indeed fixes it - see below:
![RDR](https://user-images.githubusercontent.com/11403137/123975088-1cb15f80-d98b-11eb-8451-0e6734785cf3.png)

All info is now exposed as requested in the OP.

Thank you very much for this. Can I ask how you managed to add this functionality into OpnSense? It seems like it would have been a nightmare to add.

Kind regards,
Peter

**Comment by fichtner** [comment]
Hi Peter,

It was a mix of reading a bit of source code and remembering that logging already worked somehow. Glad we could put the pieces together.

This will likely end up in OPNsense 21.7, but not the RC1 to be released next week.

To keep the code in place lock "kernel" package from the firmware packages tab.

Close then? :)


Cheers,
Franco

**Comment by pallebone** [comment]
Yes please. Thank you for your time. It is appreciated.

Kind regards
Peter.
