### ISSUE TITLE
IPv6 ULA/VIP addresses are not properly being compressed before comparing them to the interface address for radvd

### ISSUE THREAD

**Issue by jdeluyck** [opnsense/core#5008]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues and I am convinced that mine is new.

**Describe the bug**

I'm configuring IPv6 in my house:
* ISP offers PD /60, not static
* LAN is static ipv4, track interface ipv6 on PD 0x4

For having some internal stability, I added a VIP ULA on top of the interface, fddf:xxxx:yyyy:34::1/64. 
Forgot to set "Allow manual adjustment of DHCPv6 and Router Advertisements". so re-edited the interface, hit save, hit apply, and suddenly only my VIP was being announced by radvd - no longer the GUA.

**To Reproduce**

1. Configure WAN with ipv6 (PD), save, apply
2. Configure LAN with ipv6, track interface, check "Allow manual adjustment of DHCPv6 and Router Advertisements"
3. Hit save
4. Hit apply

Check that radvd is advertising the primary range, all works, happy campers.

5. Add VIP on the LAN interface, hit save - VIP doesn't show up 
6. Restart radvd - both ranges are announced

7. Re-edit the interface, don't change anything, just hit save
8. Hit apply
9. GUA range disappears from radvd config, only VIP ULA range remains, breaking your network after a while.

**Expected behavior**

Both ranges should keep being announced by radvd. It's probably something that gets overwritten instead of appended.

**Screenshots**

radvd config after applying everything correcty:
```
# cat radvd.conf
# Automatically generated, do not edit
# Generated for DHCPv6 server lan
interface igb1_vlan134 {
        AdvSendAdvert on;
        MinRtrAdvInterval 200;
        MaxRtrAdvInterval 600;
        AdvLinkMTU 1500;
        AdvDefaultPreference medium;
        AdvManagedFlag on;
        AdvOtherConfigFlag on;
        prefix 2a02:xxxx:xxxx:xxxx::/64 {
                DeprecatePrefix on;
                AdvOnLink on;
                AdvAutonomous on;
        };
        prefix fddf:xxxx:xxxx:34::/64 {
                DeprecatePrefix on;
                AdvOnLink on;
                AdvAutonomous on;
        };
        RDNSS fddf:xxxx:xxxx:34::2 fddf:xxxx:xxxx:34::3 {
        };
        DNSSL home.lan {
        };
};
# Generated for DHCPv6 server opt3
interface igb1_vlan135 {
        AdvSendAdvert on;
        MinRtrAdvInterval 200;
        MaxRtrAdvInterval 600;
        AdvLinkMTU 1500;
        AdvDefaultPreference medium;
        prefix 2a02:xxx:xxx:xxx::/64 {
                DeprecatePrefix on;
                AdvOnLink on;
                AdvAutonomous on;
        };
        RDNSS 2606:4700:4700::1111 2620:fe::fe {
        };
        DNSSL telenet.be {
        };
};
```
radvd.conf after the second edit:
```
# cat radvd.conf
# Automatically generated, do not edit
# Generated for DHCPv6 server lan
interface igb1_vlan134 {
        AdvSendAdvert on;
        MinRtrAdvInterval 200;
        MaxRtrAdvInterval 600;
        AdvLinkMTU 1500;
        AdvDefaultPreference medium;
        AdvManagedFlag on;
        AdvOtherConfigFlag on;
        prefix fddf:xxxx:xxxx:34::/64 {
                DeprecatePrefix on;
                AdvOnLink on;
                AdvAutonomous on;
        };
        RDNSS fddf:xxxx:xxxx:34::2 fddf:xxxx:xxxx:34::3 {
        };
        DNSSL home.lan {
        };
};
# Generated for DHCPv6 server opt3
interface igb1_vlan135 {
        AdvSendAdvert on;
        MinRtrAdvInterval 200;
        MaxRtrAdvInterval 600;
        AdvLinkMTU 1500;
        AdvDefaultPreference medium;
        prefix 2a02:xxxx:xxxx:xxxx::/64 {
                DeprecatePrefix on;
                AdvOnLink on;
                AdvAutonomous on;
        };
        RDNSS 2606:4700:4700::1111 2620:fe::fe {
        };
        DNSSL telenet.be {
        };
};

````
As you can see, the entry for igb1_vlan134 is missing the primary range.

**Environment**

OPNsense 21.1.5-amd64
FreeBSD 12.1-RELEASE-p16-HBSD
OpenSSL 1.1.1k 25 Mar 2021

**Comment by jdeluyck** [comment]
Re-writing the radvd config via first removing the IP address, and then disabling/enabling dhcpv6 puts everything back the way it's supposed to be.

**Comment by fichtner** [comment]
I can see the same thing after applying a tracking LAN, but there is a second rewrite that puts the address back via rc.newwanipv6 -- do you have "Prevent release" set in Interfaces: Settings?

**Comment by jdeluyck** [comment]
> I can see the same thing after applying a tracking LAN, but there is a second rewrite that puts the address back via rc.newwanipv6 -- do you have "Prevent release" set in Interfaces: Settings?

Can't access the UI at this moment - assuming it's "<lock>" in the config.xml, yes it is set.

**Comment by fichtner** [comment]
No, it's a global dhcp6c setting.

**Comment by jdeluyck** [comment]
> No, it's a global dhcp6c setting.

Found it. Nope, not set:

![Screenshot 2021-05-26 at 13 34 56](https://user-images.githubusercontent.com/5451787/119653090-365d0580-be27-11eb-92ab-f4117d81153e.png)

**Comment by fichtner** [comment]
Can you set your dhcp6c to debug level and try the save/apply after a reboot. system log is essential in this case. I expect dhcp6c will not regrab the lease? Does the GUA come back naturally or do you need to force it (looking at ifconfig after save/apply).

**Comment by jdeluyck** [comment]
After setting up a lab I can easily recreate the problem.

Client interface:
```
fda4:4fab:7fec::1/128
fd3b:6a15:4ca5:f1:6c34:68ff:fe9b:25b0/64
```
with fda4* being the VIP

After resaving and applying the interface I see both the VIP and the GUA on the interface itself. So that works fine.
What fails is that the radvd config only reports the VIP, not the GUA.

**Comment by jdeluyck** [comment]
The title of PR https://github.com/opnsense/core/pull/4932 looks like this might be it?

**Comment by fichtner** [comment]
No it should pick up both if they are there. It's a different issue.

I'm going through the log now. I'm not sure what's going on.

**Comment by fichtner** [comment]
@jdeluyck can you share your dhcp6c config?

    # cat /var/etc/dhcp6c_wan.conf

When I look at my box it does not mess with addresses on the tracking interfaces but yours does

> add an address fd3b:6a15:4ca5:f1:6c34:68ff:fe9b:25b0/64 on em2
> remove an address fd3b:6a15:4ca5:f1:6c34:68ff:fe9b:25b0/64 on em2

Something is different on your end of the dhcp6c behaviour that causes this so this might be larger back and forth with questions to get to the bottom of it...

**Comment by jdeluyck** [comment]
@fichtner It's pretty much a basic opnsense install. Still on .5, haven't patched ot .6 yet.

```
# cat /var/etc/dhcp6c_wan.conf
interface em1 {
  send ia-na 0; # request stateful address
  send ia-pd 0; # request prefix delegation
  request domain-name-servers;
  request domain-name;
  script "/var/etc/dhcp6c_wan_script.sh"; # we'd like some nameservers please
};
id-assoc na 0 { };
id-assoc pd 0 {
  prefix ::/60 infinity;
  prefix-interface em2 {
    sla-id 1;
    sla-len 4;
  };
};
```

**Comment by fichtner** [comment]
ah ok, can you enable "Request only an IPv6 prefix" and try with that...

**Comment by jdeluyck** [comment]
That's on the WAN (em1) interface?

**Comment by fichtner** [comment]
Correct

**Comment by fichtner** [comment]
Also "Send IPv6 prefix hint" is enabled for you? It can also mess with results.

**Comment by jdeluyck** [comment]
Ok, enabled that option, rebooted
Removed ULA, restarted radvd, add VIP, restart radvd, so I have both again on the interface and in radvd

Save, apply em2 interface, same issue.

I do have 'sent ipv6 prefix hint' enabled yes.

**Comment by jdeluyck** [comment]
OK. fun fact. I had disabled 'send prefix hint', re-setup the ULA, and then rebooted. This results in a broken configuration too.

[system-no-send-hint.log](https://github.com/opnsense/core/files/6560658/system-no-send-hint.log)

**Comment by fichtner** [comment]
I tried to emulate all your settings but my LAN IPv6 and radvd.conf always come back fine automatically no matter if there is a VIP included or not.

Are you always testing against the same (ISP?) DHCPv6 server?

**Comment by jdeluyck** [comment]
Upgraded my lab and my home router to Opnsense 21.1.6 - this issue is still present.
Been digging through some of the php code but it's rather a haystack if you're not working with it daily.

**Comment by jdeluyck** [comment]
I have been going through the code in ```inc/interfaces.inc``` and ```inc/plugins.inc.d/dhcpd.inc```, adding a ton of error_log() and I believe I've found where it goes wrong:

When in ```dhcpd.inc``` we request the interface primary ip using
```
list ($ifcfgipv6, $networkv6) = interfaces_primary_address6($dhcpv6if, $realif, $ifconfig_details);
```
we pass $realif which contains (at that time):
```
[06-Jun-2021 10:38:00 Etc/UTC] realif: em2
[06-Jun-2021 10:38:00 Etc/UTC] Array
(
    [192.168.100.1/24] => Array
        (
            [family] => inet
            [scope] =>
            [name] => em2
        )
 
    [fda4:4fab:7fec::1/128] => Array
        (
            [family] => inet6
            [scope] =>
            [name] => em2
        )
    
    [fd3b:6a15:4ca5:f1:6c34:68ff:fe9b:25b0/64] => Array
        (
            [family] => inet6
            [scope] =>
            [name] => em2
        )
 
    [fe80::6c34:68ff:fe9b:25b0/64] => Array
        (
            [family] => inet6
            [scope] => 1    
            [name] => em2
        )

)
```

As you can see, the VIP is the first IP address in the array. And at the end of the foreach in ```interfaces.inc``` there is the 
```
break; /* all done */
```
statement which causes only the first ip in the list to be actually looked at.
