### ISSUE TITLE
TCP Session drops since 20.1.4

### ISSUE THREAD

**Issue by DarkSunOne** [opnsense/core#5012]
Hello everyone,

since the update to 20.1.4 we encounter strange connection issues.

It seems, that valid tcp sessions gets dropped randomly, and all further packets show up with TCP:FA, TCP:FPA and TCP:RA (blocked) on the firewall.

This is totally annoying because SSH sessions are freezing, JetBrains Software neeeds to be reopened for automatic uploads, various online streams suddenly stocks and so on. 
The disconnects usually occurs every 1 to 5 minutes.

The problem also occurs from one LAN on the OpnSense to an other LAN.

I searched a lot, and have absolutely no idea what could cause this problem.
Before the update to 20.1.4 everything worked without any problem.

Anyone an idea?
I am desperate and need a stable internet connection to work :-(

**Comment by NerdyProjects** [comment]
I can confirm this as well, administrating an OPNSense box which got a second WAN interface using an LTE connection yesterday. The gateway group has LTE on tier1 and DSL on tier 2 (failover) and is only used for a separate network. The primary LAN network using ONLY DSL WAN (via default gateway, e.g. no specific gateway assigned, the DSL "single" gateway is marked upstream). All TCP Connections get dropped whenever the state of the gateway group changes. This is really annoying and disrupting services when playing with an unrelated connection :-(

Using
```
OPNsense 21.1.7_1-amd64
FreeBSD 12.1-RELEASE-p18-HBSD
OpenSSL 1.1.1k 25 Mar 2021
```

**Comment by mimugmail** [comment]
Firewall Settings Advanced .. Disable Kill states

**Comment by NerdyProjects** [comment]
Oh, thank you! Makes sense somehow, I wonder how related that is to this issue then...
