### ISSUE TITLE
Suricata - template for custom.yaml missing crucial syntax in order to be included

### ISSUE THREAD

**Issue by sigurdvaa** [opnsense/core#5018]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**

Not exactly sure how to classify this, so apologies if i got it wrong. It's more like a suggestion for a simple user friendly improvement.

Template for custom.yaml is missing crucial syntax in order to be included.
After tuning performance for Suricata i needed to make a change persistent. I added `runmode: autofp` to the file `/usr/local/opnsense/service/templates/OPNsense/IDS/custom.yaml` and clicked Apply in the Web UI for IDS administration to trigger OPNsense to create the new config. Suricata then failed to start because the `custom.yaml` file was missing these lines at the top:
```
%YAML 1.1
---
```

What i did:
1. SSH to OPNsense and opened a shell. Edited and saved the template for custom.yaml file in order to make my changes persistent `/usr/local/opnsense/service/templates/OPNsense/IDS/custom.yaml`:
```
runmode: autofp
```
2. In the Web UI, Services -> Intrusion Detection -> Administration
3. Clicked Apply to make OPNsense create new configuration using the template to create the file `/usr/local/etc/suricata/custom.yaml`, which is included at the bottom of `/usr/local/etc/suricata/suricata.yaml`
4. After OPNsense was finish saving config it failed to start Suricata, showing `Error (1)`
5. Went back to ssh and the shell on OPNsense, started Suricata manually to properly view the error:
```
root@OPNsense:~ # /usr/local/etc/rc.d/suricata start
Starting suricata.
28/5/2021 -- 16:30:43 - <Info> - Including configuration file installed_rules.yaml.
28/5/2021 -- 16:30:43 - <Info> - Configuration node 'rule-files' redefined.
28/5/2021 -- 16:30:43 - <Info> - Including configuration file custom.yaml.
28/5/2021 -- 16:30:43 - <Error> - [ERRCODE: SC_ERR_CONF_YAML_ERROR(242)] - ERROR: Invalid configuration file.
28/5/2021 -- 16:30:43 - <Error> - [ERRCODE: SC_ERR_CONF_YAML_ERROR(242)] - The configuration file must begin with the following two lines: %YAML 1.1 and ---
28/5/2021 -- 16:30:43 - <Error> - [ERRCODE: SC_ERR_CONF_YAML_ERROR(242)] - Failed to include configuration file custom.yaml
```
6. Added the missing lines to the file `/usr/local/opnsense/service/templates/OPNsense/IDS/custom.yaml`:
```
%YAML 1.1
---
runmode: autofp
```
7. Clicked Apply again in the Web UI and Suricata successfully started.

**Describe the solution you like**

Perhaps the template `src/opnsense/service/templates/OPNsense/IDS/custom.yaml.sample` could include the following:
```
%YAML 1.1
---
# add custom persistent config below
```

**Comment by AdSchellevis** [comment]
this https://github.com/opnsense/core/commit/f43ea56336bf538573f13a7e3773ed30fcff119d ?

**Comment by sigurdvaa** [comment]
I think both lines are needed:
```
%YAML 1.1
---
```
and then perhaps a helpful comment stating that changes should be added below, as the file has to start with those two lines

**Comment by AdSchellevis** [comment]
@sigurdvaa to quick a fix yesterday, this should be better https://github.com/opnsense/core/commit/e038c1573c772decf9858869ebaa273efebb74bf
