### ISSUE TITLE
Port Forward, no longer by default creates Associated Firewall Rule (Filter rule association)

### ISSUE THREAD

**Issue by FingerlessGlov3s** [opnsense/core#5019]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**
When you want to create a port forward, in recent versions of OPNsense it no longer creates the associated firewall rule by default. You now have to change the drop down from "None" to "Add associated filter rule". I'm not sure if this is a unwanted bug from this commit https://github.com/opnsense/core/commit/b0e9007b46a151da7eee4af78dc9c5f627c5ce56

I know few people in IRC and other support channels have asked why their Port Forwarding isn't working and then turns out they were unaware of this dropdown option changing its default to no longer creating the firewall rule association by default.

**To Reproduce**

Steps to reproduce the behaviour:
1. Go to 'FIREWALL: NAT: PORT FORWARD'
2. Click on 'Add'
3. Scroll down to 'Filter rule association'
4. See default option is now "None" instead of the old "Add associated filter rule"

**Expected behaviour**

Defaults to "Add associated filter rule", which will leads to less confusion and how people expect it to work by default. 

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 21.1.6 (amd64, OpenSSL).
Intel(R) Core(TM) i3-7100U CPU @ 2.40GHz (4 cores)
Network Intel® I210 (6 of)

**Comment by AdSchellevis** [comment]
@FingerlessGlov3s the previous behaviour seemed to be more or less accidental, but I agree there's no reason to change the default. should be fixed with https://github.com/opnsense/core/commit/11f3de09726f30e437ed7525d1f5bd3dca962b89

**Comment by FingerlessGlov3s** [comment]
Can confirm patch works.
