### ISSUE TITLE
I lose ipv6 after a few minutes

### ISSUE THREAD

**Issue by Hoerli1337** [opnsense/core#5021]
**Describe the bug**

My ISP provides a /56 prefix over IPv6.
I have a PPPoE connection (FTTH connection).
I also get an IPv6 assigned without any problems when I start OPNsense.
My computer also gets an IPv6 assigned.
Up to here everything is fine.
I only get an IP address assigned via interface logging if I create a WAN rule that allows port 547 -> 546.
I found this hint in the internet.
([](https://homenetworkguy.com/how-to/configure-ipv6-opnsense-with-isp-such-as-comcast-xfinity/))

After about 2-3 minutes, the connection drops for all IPv6 packets.
If I restart the firewall or reboot my PC, I can connect to the internet again via IPv6 for 2-3 minutes.
Both devices still have an IPv6 address assigned.
OPNsense also has an address for the LAN and WAN interface.

Only now comes the strange thing, if I execute a ping command, the result looks like this:
PC -> OPNsense LAN interface = OK
PC -> OPNsense WAN interface = Not ok
PC -> WAN address = Not ok
OPNsense WAN -> WAN address = OK (Ping tool in the web interface)
OPNsense LAN -> WAN address = OK (Ping tool in the web interface)

As it looks, OPNsense suddenly starts dropping the packets.
For whatever reason.
I have a rule for IPv4 and IPv6 each, which is structured as follows:
LAN -> WAN | IPv4 / IPv6 | any -> any

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 21.1.6-amd64 (amd64, OpenSSL)
FreeBSD 12.1-RELEASE-p126-HBSD
OpenSSL 1.1.1k
Intel® Core i5-10500T
RAM: 2x 4GB
Network Intel® X550-T2 (WAN + LAN)
Network 2: Intel I219-V (OnBoard-LAN)

I created this issue here because there seems to be another person who has the same problem on the OPNsense forum, but there is no solution to it yet:
https://forum.opnsense.org/index.php?topic=22052.0

**Comment by sourcenux** [comment]
Could you check if the opnsense blocks any ICMP(v6) traffic? ( Firewall > Log Files > Live View )
