### ISSUE TITLE
Shaper fails on VLAN interfaces

### ISSUE THREAD

**Issue by dlasher** [opnsense/core#5026]
**Describe the bug**
Traffic shapers fail when applied to an interface assigned to a VLAN. Same traffic shaper works when applied to a non VLAN interface. ipfw fails to match

opnsense router
em0 : wan
re0: access port - vlan 20
re1: trunk to switch
re2: trunk to switch
re1.vlan20 - interface off re1

**To Reproduce**
* create rule, shaping traffic 10Mup/10M down to/from MYNET & WAN. 

60001   0     0 queue 10004 ip from any to any xmit em0 recv re0
60002   0     0 queue 10005 ip from any to any xmit re0 recv em0

* assign MYNET interface to re0
* bandwidth test -  see 10M/10M
* assign MYNET interface to RE1.VLAN20

60001   0     0 queue 10004 ip from any to any xmit em0 recv re1_vlan20
60002   0     0 queue 10005 ip from any to any xmit re1_vlan20 recv em0

* repeat test
* see full bandwidth up/down

OPNsense 20.1.9-i386
FreeBSD 11.2-RELEASE-p20-HBSD
OpenSSL 1.1.1g 21 Apr 2020

**Expected behavior**
traffic shaped correctly

**Comment by iMiMx** [comment]
@dlasher Did you fix this?  

I *think* disabling shared forwarding resolved it for me - I could sort of get it to work with it on, by using interface 1 and interface 2 with the appropriate direction, but any subnet matching failed - and there were problems with the upload shaping - disabling Shared Forwarding, I think has resolved it for me with VLANs.

I still do need to try re-enabling and then rebooting, as sometimes shaping didn't always work correctly until a reboot was performed.
