### ISSUE TITLE
DHCP lease hostnames are not synchronized between peers what is causing DNS resolving issues

### ISSUE THREAD

**Issue by pcmediapear** [opnsense/core#5029]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[-] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md

[-] I have searched the existing issues and I'm convinced that mine is new.

[-] The title contains the plugin to which this issue belongs

**Describe the bug**
by using two opnsense systems in failover DHCP and DNS configuration DHCP lease synchronization does not synchronize hostnames between peers what is causing DNS resolving issues of DHCP clients with unbound DNS resolver

*Tip*: to validate your setup was working with the previous version, use opnsense-revert (https://docs.opnsense.org/manual/opnsense_tools.html#opnsense-revert)

**To Reproduce**
1. configure DHCP peers on two opnsense systems
2. on both configure two unbound DNS resolvers with registering DHCP leases
3. start some DHCP client
4. wait for sync between DHCP peers
5. lease is synchronized to peer but without hostname
6. unbound running on opnsense where lease has been synchronized cant resolve hostname

**Expected behavior**
both peers should have exact same DHCP leases including hostnames

**Screenshots**
on left DHCP leases on peer without hostnames and on right DHCP leases on peer with hostnames
![image](https://user-images.githubusercontent.com/10603554/120541865-b583a800-c3ea-11eb-9459-fd5da120c932.png)

**Relevant log files**
If applicable, information from log files supporting your claim.

**Additional context**

**Environment**
OPNsense 21.1.5-amd64
FreeBSD 12.1-RELEASE-p16-HBSD
OpenSSL 1.1.1k 25 Mar 2021

KVM virtual machines

**Comment by fichtner** [comment]
Is the hostname part of the static lease configuration? If not the hostname is simply read from the active DHCP lease file and the passive box is unable to gather this information since it does not know about the leases handed out by the active box.


Cheers,
Franco

**Comment by pcmediapear** [comment]
tested leases are dynamic
as you can see on screenshot passive box knows about leases on active box (lease IP, mac and date/time is synchronized and same on both systems)

regards

**Comment by fichtner** [comment]
I can neither confirm nor deny from the cropped screenshot. ;)

**Comment by pcmediapear** [comment]
is there any way how can i upload or send you better screenshot but not public?

**Comment by fichtner** [comment]
try franco@opnsense.org :)

**Comment by pcmediapear** [comment]
seems to be an old issue: https://forum.opnsense.org/index.php?topic=5293.0

**Comment by fichtner** [comment]
Sorry I dropped the ball on this last time. Looking further I don’t know if this can ever be fixed: https://serverfault.com/questions/842621/isc-dhcp-server-doesnt-share-hostnames-with-failover-peer
