### ISSUE TITLE
OpenVPN Client kill switch not working

### ISSUE THREAD

**Issue by Alwaysin** [opnsense/core#5038]
This is a reopen of #4023 

**Describe the bug**
The client kill switch on the connection status page of OpenVPN is not working. If it is pressed nothing happens.
Was reported with Issue #687 and should have been fixed with 16.7.

**To Reproduce**

Set up OpenVPN Server
Connect a client
Go to VPN>OpenVPN>Connection Status
Try to kill client connection
Expected behavior
The client connection should be terminated.

This apparently only happens when the interface of the openvpn server listens to "any".

By command-line, the kill is working:
```
 # nc -U /var/etc/openvpn/server1.sock
>INFO:OpenVPN Management Interface Version 1 -- type 'help' for more info
kill user
SUCCESS: common name 'user' found, 1 client(s) killed
^C
```

**Screenshots**
![image](https://user-images.githubusercontent.com/63337562/78755467-80f89580-7979-11ea-943a-6389f21a9765.png)

**Environment**
Software version used and hardware type if relevant.
e.g.:

OPNsense 21.1.4-amd64
FreeBSD 12.1-RELEASE-p15-HBSD
OpenSSL 1.1.1k 25 Mar 2021

**Comment by fichtner** [comment]
@Alwaysin The kill function kills via "Real Address" (minus port), not common name. Can you try to see what error it returns from the command line?


Cheers,
Franco

**Comment by Alwaysin** [comment]
Now that you mention it, via the comand-line I first tried with the real address and it didn't work, so did it again with the common name and it worked. I'll try again to see if I can catch the error.

**Comment by fichtner** [comment]
@Alwaysin any news here?

**Comment by Alwaysin** [comment]
@fichtner So, I did the test again on latest version of OPNSense.

- Killing via the interface is not working. Page refreshes but client stays connected  (and stays on the list for that matter)

- Killing via IP:port is not working on the command line, saying the client is not found:

```
# nc -U /var/etc/openvpn/server1.sock
>INFO:OpenVPN Management Interface Version 3 -- type 'help' for more info
kill 185.228.229.117:62123
ERROR: client at address 185.228.229.117:62123 not found
kill "185.228.229.117:62123"
ERROR: client at address 185.228.229.117:62123 not found
kill ademma
SUCCESS: common name 'ademma' found, 1 client(s) killed
```

Killing via the name is still working.

Is there anywhere else I can check logs? I saw nothing in /var/log/*

By the way, I don't know if it is the kill or just the fact I connected to the socket, but it breaks the interface by not displaying any of the connections anymore ("No OpenVPN clients are connected to this instance." whereas this is not true")

**Comment by Alwaysin** [comment]
@OPNsense-bot Not fair.

**Comment by AdSchellevis** [comment]
@Alwaysin can you try https://github.com/opnsense/core/commit/03f7dbc43146460b98a85d8fdde8683d363963e9 ? 

On OPNsense 21.7.6 the following should easily patch it:

```
opnsense-patch 03f7dbc
```

**Comment by Alwaysin** [comment]
I have upgraded to 22.1 and I can confirm this is now working. Thank you!
