### ISSUE TITLE
Captive portal + transparent proxy seem broken in 21.1.6

### ISSUE THREAD

**Issue by marinbernard-pep06** [opnsense/core#5039]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

Enabling transparent proxy features for a captive portal zone seem to have no effect in OPNsense 21.1.6. http/https traffic falls through ipfw without being redirected to the loopback  address, then it hits pf, where it is logged and dropped.

**To Reproduce**

1. Enable Squid
2. Set Squid to listen to the loopback interface with transparent proxying enabled
3. Create a captive portal zone with transparent proxy enabled
4. Add a firewall rule to allow hosts belonging to the captive portal subnet to connect to ``127.0.0.0:3128-3129/tcp``
5. Authenticate to the captive portal and try to browse the Internet

**Expected behavior**

http/https traffic from authenticated hosts should be transparently forwarded to the local Squid instance listening to ``127.0.0.1``.

**Describe alternatives you considered**

So far, we've been using pf rules with policy routing to redirect http/https traffic from authenticated clients to an external proxy server. This is still working fine, but we'd like to move the proxy to the same box as the captive portal, and this bug prevents such a move.

Adding NAT rules to redirect http/https traffic to the local proxy is not a solution, as pf NAT rules are processed _before_ ipfw rules, and would bypass the captive portal entirely.

**Screenshots**

Captive portal zone configuration (sorry for the French localization):

![capture](https://user-images.githubusercontent.com/68065424/121323011-c020ce80-c90f-11eb-9758-ba75f8a31549.JPG)

**Relevant log files**

Here is our ipfw rule set. The rwo rules for transparent proxying are present, but I'm not sure if they're reachable.

```
00100 allow pfsync from any to any
00110 allow carp from any to any
00120 allow layer2 mac-type 0x0806,0x8035
00130 allow layer2 mac-type 0x888e,0x88c7
00140 allow layer2 mac-type 0x8863,0x8864
00150 deny layer2 not mac-type 0x0800,0x86dd
00200 skipto 60000 ip6 from ::1 to any
00201 skipto 60000 ip4 from 127.0.0.0/8 to any
00202 skipto 60000 ip6 from any to ::1
00203 skipto 60000 ip4 from any to 127.0.0.0/8
01001 skipto 60000 udp from any to me 53 via vtnet1 keep-state :default
01001 skipto 60000 ip from any to { 255.255.255.255 or me } in via vtnet1
01001 skipto 60000 ip from { 255.255.255.255 or me } to any out via vtnet1
01001 skipto 60000 icmp from { 255.255.255.255 or me } to any out via vtnet1 icmptypes 0
01001 skipto 60000 icmp from any to { 255.255.255.255 or me } in via vtnet1 icmptypes 8
03000 skipto tablearg ip from table(0) to any via vtnet1
03000 skipto tablearg ip from any to table(0) via vtnet1
05000 fwd 127.0.0.1,8000 tcp from any to any 443 in via vtnet1
05000 allow ip from any to any 443 via vtnet1
05000 fwd 127.0.0.1,9000 tcp from any to any 80 in via vtnet1
05000 allow ip from any to any 80 via vtnet1
06000 skipto 60000 tcp from any to any out
06002 skipto 65534 ip from any to any via vtnet1
06199 skipto 60000 ip from any to any
30000 count ip from 10.6.102.15 to any
30000 count ip from any to 10.6.102.15
30000 skipto 60000 ip from any to any
30001 count ip from 10.6.102.18 to any
30001 count ip from any to 10.6.102.18
30001 skipto 60000 ip from any to any
30002 count ip from 10.6.102.34 to any
30002 count ip from any to 10.6.102.34
30002 skipto 60000 ip from any to any
30003 count ip from 10.6.102.35 to any
30003 count ip from any to 10.6.102.35
30003 skipto 60000 ip from any to any
30004 count ip from 10.6.102.40 to any
30004 count ip from any to 10.6.102.40
30004 skipto 60000 ip from any to any
30005 count ip from 10.6.102.44 to any
30005 count ip from any to 10.6.102.44
30005 skipto 60000 ip from any to any
30006 count ip from 10.6.102.52 to any
30006 count ip from any to 10.6.102.52
30006 skipto 60000 ip from any to any
30007 count ip from 10.6.102.53 to any
30007 count ip from any to 10.6.102.53
30007 skipto 60000 ip from any to any
30008 count ip from 10.6.102.84 to any
30008 count ip from any to 10.6.102.84
30008 skipto 60000 ip from any to any
30009 count ip from 10.6.102.88 to any
30009 count ip from any to 10.6.102.88
30009 skipto 60000 ip from any to any
60000 return
60005 skipto 65533 tcp from me to any 80 via vtnet1
60005 skipto 65533 tcp from me to any 443 via vtnet1
65532 fwd 127.0.0.1,3128 tcp from any to any 80 via vtnet1
65532 fwd 127.0.0.1,3129 tcp from any to any 443 via vtnet1
65533 allow ip from any to any
65534 deny ip from any to any
65535 allow ip from any to any
```

**Additional context**

Captive portal zone subnet: ``10.6.102.0/25``
Captive portal server address: ``10.6.102.126/25``

**Environment**

OPNsense 21.1.6 (amd64, LibreSSL).
KVM host with 4096GB RAM
virtio adapters

**Comment by fichtner** [comment]
So when was this working last (version)?

**Comment by marinbernard-pep06** [comment]
I have no idea. Until then we used policy routing to force http traffic through an external proxy server, so we've never used the feature before. I'll try to make some tests this afternoon with ``opnsense-revert``, but am unsure about how previous versions will deal with config schema changes. I may have to go back to ``16.7``, where the transparent proxy feature was [implemented](https://github.com/opnsense/core/commit/782152ffb3a2a9b4b07fccd8c64cdb7950413357). At that time, it was probably working.

**Comment by fichtner** [comment]
It seems a bit odd... and you can't easily revert major versions.

> Adding NAT rules to redirect http/https traffic to the local proxy is not a solution, as pf NAT rules are processed before ipfw rules, and would bypass the captive portal entirely.

I have no idea why they would bypass it with shared forwarding in place (default configuration).

Even then, why not use a squid based authentication instead of an added captive portal layer?


Cheers,
Franco

**Comment by marinbernard-pep06** [comment]
> > Adding NAT rules to redirect http/https traffic to the local proxy is not a solution, as pf NAT rules are processed before ipfw rules, and would bypass the captive portal entirely.
> 
> I have no idea why they would bypass it with shared forwarding in place (default configuration).

Yes, shared forwarding is enabled. Adding NAT rules does indeed redirect http traffic the our local proxy, but it happens for any host on the CP subnet, authenticated or not. AFAIK, this is the behaviour which led to the addition of the transparent proxy feature in captive portal zones, as there was no way to have both captive portal + transparent proxy working on the same box at that time.

> Even then, why not use a squid based authentication instead of an added captive portal layer?

Captive portal authentication is required because we need to authenticate all kinds of traffic (including non-HTTP). This is a guest network, and using disposable paper vouchers is a great solution. I'd like to avoid adding another layer of authentication in Squid. For us, transparent proxying after CP authentication is the ideal way to go.

**Comment by fichtner** [comment]
Relevant ticket was https://github.com/opnsense/core/issues/1189

I am not aware of any changes, breaking or otherwise. I can test this afternoon briefly.

**Comment by marinbernard-pep06** [comment]
I managed to get it working. The firewall rule I added was allowing hosts from the CP zone to connect to ``127.0.0.1:3128-3129/tcp``, as we would for a classic NAT setup:

```
pass in log quick on vtnet1 inet proto tcp from (vtnet1:network:1) to 127.0.0.1 port = 3128 flags S/SA keep state
```

Changing the rule to allow CP hosts to connect any non-private host made it work. (``GRP_IANA_PRIVATE`` is an alias for RFC1918 ranges):

```
pass in log quick on vtnet1 inet proto tcp from (vtnet1:network:1) to ! <GRP_IANA_PRIVATE:5> port = http flags S/SA keep state
```

I can see the traffic flowing in Squid access log, so it seems OK. Could you confirm that this behaviour is expected ?

**Comment by fichtner** [comment]
127.0.0.1 cannot be reached by outside hosts so rules for it will not do anything (you can see from the inspect statistics feature).

In general a pass rule for the interface is all that is needed and the redirects are, eh, transparent so to speak. Of course, you probably want to avoid your guests from accessing other subnets, but that could also be done by a separate block rule. 


Cheers,
Franco

**Comment by marinbernard-pep06** [comment]
> 127.0.0.1 cannot be reached by outside hosts so rules for it will not do anything (you can see from the inspect statistics feature).

Yes, this is true for standard rules, but when NAT is used to redirect traffic to a loopback address, such a rule must be added to the firewall to allow inbound packets to pass (allowing traffic to the original destination is not enough).

What I do not understand is where exactly IPFW stands in the whole traffic flow: are IPFW rules processed before or after pf ones ? Intuitively, I would say that pf rules are evaluated _before_ IPFW, but i'm not very sure of it.

Anyway, feel free to close the ticket if everything is working as expected.

Thanks!

**Comment by fichtner** [comment]
> such a rule must be added to the firewall to allow inbound packets to pass 

In the most restrictive sense yes, but you essentially want the traffic to go through the firewall and not just to a local destination only. That is still true for transparent proxy use where you happen to hit an "allow all from this firewall" implicit rule by chance.

And since NAT isn't being used here from the POV of pf(4) this is further evidence that it requires a global rule view, not just a mini view of what is going to happen with the traffic. After all pf(4) is only doing what it is told.

To visualize:

pf in -> ipfw in -> ipfw out -> pf out + NAT


Cheers,
Franco

**Comment by marinbernard-pep06** [comment]
I'm sorry, I must be dumb, but I'm still lost. When the traffic hits the proxy on loopback, Squid itself creates a new connection to fetch the requested resource from a remote host. This outbound connection is also evaluated ("allow all from this firewall') and given its own entry in the state table. So if whole flow is comprised of 2 independent connections (1 in from the client, 1 out from the proxy), how is pf able to link the two and allow them both with a single rule ?

if pf wraps the whole ipfw processing

**Comment by marinbernard-pep06** [comment]
Oh, I got it. The rule only allows the traffic in. Since proxy redirection is handled *after* by IPFW, pf has no insight on it.

Thanks and sorry!

**Comment by fichtner** [comment]
Yes, correct. All interface-based rules are default to inbound filtering.

Not a problem, always happy to discuss and troubleshoot :)
