### ISSUE TITLE
Feature: floating firewall rules should show if they are "quick"

### ISSUE THREAD

**Issue by 8191** [opnsense/core#504]
Floating firewall rules are not quick by default (in contrast to interface rules, which are always "quick"). The rule overview should show if a floating rule is quick (i.e. first-match), or not (i.e. last-match), since the rule behaves completely different in those cases.

**Comment by fichtner** [comment]
I think that the floating rules are something that is rarely used. Another funny thing about them is that it supports "match" type rules, but only there (like quick). FreeBSD has never had match in pf by default, so we have a patch to enable match, but don't use it everywhere.

Also, "non-quick" is pretty dangerous as soon as one starts to use quick rules. Since it's the default everywhere else and the user has no notion of order between rules tabs.... kill non-quick floating rules?!

**Comment by 8191** [comment]
I never got cozy with the last-match concept by pf. It's just a big source of errors, when you're used to (all) other firewalls where all rules are applied on a first-match basis. I also cannot imagine any scenario where a last-match rule gives any benefit, which would not be possible with first-match...

**Comment by fraenki** [comment]
> Also, "non-quick" is pretty dangerous as soon as one starts to use quick rules. Since it's the default everywhere else and the user has no notion of order between rules tabs.... kill non-quick floating rules?!

I make heavy use of floating rules to keep my per-interface ruleset as small as possible. For this purpose it is crucial to have both non-quick and quick floating rules. So I'm clearly against killing non-quick floating rules. 

But I'd like so see some icon indicate if a floating rule is quick or non-quick. Maybe we should just use the (i) icon that indicates advanced settings on per-interface rules.

**Comment by 8191** [comment]
@fraenki Thanks, nice implementation. One caveat: non-floating rules are always quick in OPNsense, so we should also show the icon there.

**Comment by fichtner** [comment]
@fabianfrz did the implementation, but I would want two things changed...

(a) The default for new floating rules should be quick, not as it currently is,
(b) Flip the indicator, showing it only when the rule is non-quick.

FWIW, quick is the keyword, but the actual explanation is "first match" or "last match".

**Comment by 8191** [comment]
> BTW, quick is the keyword, but the actual explanation is "match first" or "match last".
You're right. Anyway, I do not like the term "match last", since it's actually not guaranteed to match at all. But I cannot come up with any better term neither...

**Comment by fichtner** [comment]
This was done, picking up the pieces in follow up tickets. Thanks everyone :)
