### ISSUE TITLE
Bridge interface initialization before OpenVPN tap is available

### ISSUE THREAD

**Issue by Desdinova** [opnsense/core#5040]
We experience a problem with our OPNsense:
The firewall has a bridge that bridges a LAN interface with an OpenVPN tap interface. We connect to sites with layer 2 with this method.

The problem is: When OPNsense is restarted, the bridge interface comes up before the OpenVPN tunnel is established and therefore doesn't add the tap interface to the bridge.

The problem exists on version 20.7.8 and 21.1.6.

**Comment by fichtner** [comment]
@Desdinova can you try 45884380f77b ?

    # opnsense-patch 45884380f77b

**Comment by Desdinova** [comment]
@fichtner Thank you for your quick response! I will test this next week. Unfortunately this is the only firewall where we have no remote access to.

**Comment by fichtner** [comment]
I'm quite sure this helps so I have added it to 21.1.7 release for tomorrow. Feedback still welcome.

**Comment by fichtner** [comment]
@Desdinova any luck so far? :)

**Comment by Desdinova** [comment]
@fichtner  One of my colleagues on the way to the customer right now. I'll update in a few hours. :)

**Comment by Desdinova** [comment]
@fichtner Final update: Everthing works fine now! :) We updated to 21.1.7 and performed a few restarts to test the bridge status. The OpenVPN interface was always present as a bridge member.

Thank you very much for fixing this so quickly! :)

**Comment by fichtner** [comment]
Great, thanks for the report. ❤️
