### ISSUE TITLE
Unbound doesn't use GIF tunnel as Outgoing Network Interface

### ISSUE THREAD

**Issue by wobblywob** [opnsense/core#5052]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

Unbound does not use IPv6 GIF tunnel interface for queries specified in Domain Overrides.

*Tip*: to validate your setup was working with the previous version, use opnsense-revert (https://docs.opnsense.org/manual/opnsense_tools.html#opnsense-revert)

**To Reproduce**

1. Create Hurricane Electric IPv6 GIF tunnel
2. Specify domain override (i.e test.com)
3. Select GIF tunnel in Unbound -> General -> Outgoing Network Interfaces
4. Query anything from the override (i.e. subdomain.test.com)
5. No queries made via the GIF tunnel 

**Expected behavior**

Unbound should use selected GIF tunnel to send queries to specified IPs in Domain Overrides.

**Describe alternatives you considered**

Tried setting the HE Tunnel as the only outgoing network interface but Unbound uses WAN IPv6 instead.

Ran packet capture and I saw no outgoing packets from the GIF tunnel. Firewall rules are the same as the WAN interface (which works). Just in case, I added an allow firewall rule with direction out to port 53

**Additional context**

I don't know if it's related or not, but ping6 from the GUI doesn't seem to work either when selecting the GIF Tunnel interface as a Source Address but it does work when pinging via console with the -S switch. Furthermore, when connecting to the console, I'm seeing all IPs for available interfaces except for the gif tunnel which shows up with "WAN_HETUNNEL (gif0) ->    "

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 21.1.5, 21.1.6, 21.1.7 (amd64, OpenSSL).
VM, bridge mode (not passthrough)

Tried this on 3 separate opnsense instances.

**Comment by fichtner** [comment]
I'm guessing you need to select LAN interface instead of the GIF tunnel, but IMO expecting Unbound to select the right interface AND IP family for the matching domain overrides is a little strange to me.


Cheers,
Franco

**Comment by wobblywob** [comment]
> I'm guessing you need to select LAN interface instead of the GIF tunnel, but IMO expecting Unbound to select the right interface AND IP family for the matching domain overrides is a little strange to me.
> 
> Cheers,
> Franco

Indeed, selecting HE LAN instead of HE WAN works so IMO this workaround confirms that this is a bug when selecting the gif's WAN interface. This scenario worked on pfsense 2.4.5 because unbound would send queries on _all_ selected interfaces.

**Comment by fichtner** [comment]
Maybe you can check the unbound config on the file system and see if the GIF interface address is actually picked up. That might not be the case.

**Comment by wobblywob** [comment]
> Maybe you can check the unbound config on the file system and see if the GIF interface address is actually picked up. That might not be the case.

You are right, the interface doesn't seem to be picked up in the conf file.

**Comment by fichtner** [comment]
Ok, let me propose a fix in a bit :)

**Comment by wobblywob** [comment]
> Ok, let me propose a fix in a bit :)

Thanks for the help!

**Comment by fichtner** [comment]
Turns out it worked in IPv4 case but not IPv6... patch is relatively simple: https://github.com/opnsense/core/commit/1b051f3df

You can try this locally via:

    # opnsense-patch 1b051f3df


Cheers,
Franco

**Comment by wobblywob** [comment]
I've applied the patch and did some tests. So far it looks like it works with all of the above: the IP shows up in the console, Unbound queries work and ping from the GUI via selected interface also works.

Thanks again!

**Comment by fichtner** [comment]
No problem, thanks for testing ❤️
