### ISSUE TITLE
Create firewall rules directly from live log

### ISSUE THREAD

**Issue by kosta880** [opnsense/core#5053]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**

When doing firewall migrations, i.e. building from scratch, especially when creating many rules (as in allow only what is needed), I find myself creating many rules by hand - the only way.

**Describe the solution you like**

I'd like a plus sign (or a similar button) on the live view beside the "i" button, to create a rule. Live log would be a perfect place to take "interface, destination (ip+port), protocol" and show me a template to create a firewall rule. I then just change what needed, and voila, rule is created.

**Describe alternatives you considered**

None, really.

Thank you.

**Comment by maxfield-allison** [comment]
I'll take a look at this when I have some spare time in about 12 hours. I'd really like this feature as well.

**Comment by kosta880** [comment]
Sorry, was absent, just saw your message. Just wanted to say: That would really awesome! Thanks.

**Comment by maxfield-allison** [comment]
agreed, I ended up looking into it but im not that versed in php and work picked up. I may take another crack at it over the next few weeks.
