### ISSUE TITLE
Unintelligible symbol in Chinese translation

### ISSUE THREAD

**Issue by CallMeR** [opnsense/core#5054]
Something broken the translation of page Firmware --> log （ /ui/diagnostic/log/core/pkg ）
Version OPNsense 21.1.7-amd64
opnsense-lang 21.1.7

<img width="574" alt="image" src="https://user-images.githubusercontent.com/11908641/122425557-2669b900-cfc2-11eb-8961-fa6f9095f1ef.png">

<img width="581" alt="image" src="https://user-images.githubusercontent.com/11908641/122425640-36819880-cfc2-11eb-89b1-0365469e434a.png">

**Comment by fichtner** [comment]
Hi @CallMeR,

No, sorry, it works for me in Chrome, Firefox and Safari.

Can you check another browser?

I know these type of errors can happen, but they never persist.


Cheers,
Franco

**Comment by CallMeR** [comment]
Sure
I'll try another browser :)
