### ISSUE TITLE
Renaming firewall group doesn't change the group interface reference in the rule

### ISSUE THREAD

**Issue by kosta880** [opnsense/core#5056]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

If I rename a firewall group and I have a source in the rule set to that group, the Source in the rule will change from Group to "Single host or Network" and Name_of_the_group.

**To Reproduce**

Create a Group Group1. Create a firewall rule, that has a source set to Group1.
Edit the Group name, change to Group2.
Go back into the Firewall -> Group2.
Edit the rule, source remains Group1, selected Single host or Network.

**Expected behavior**

I would expect the source to automatically change to Group2 net.

**Environment**

Latest update, 21.1.7.
Intel(R) Core(TM) i3-6320 CPU @ 3.90GHz (4 cores)
16GB RAM

**Comment by AdSchellevis** [comment]
in the same corner as https://github.com/opnsense/core/issues/5035, probably best to look at both tickets a once.
