### ISSUE TITLE
Interface improvements (buttons)

### ISSUE THREAD

**Issue by kosta880** [opnsense/core#5057]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**

Workflow problem. I am missing "interface-unity", and suggest some improvements.
Problems:
- some pages under Firewall offer "+ Add" to add a rule or entry, some don't (Aliases being my biggest problem, when I have many aliases, always have to scroll to the bottom of the page to create new alias with the + sign).
- "Apply Changes" - don't understand the need for it. I create or change the rule, I must apply changes. But I cannot cancel the change? What is the point having to apply then? Doesn't make much sense.
- Apply changes remains only on the page where changes were made (e.g. Firewall rules)

**Describe the solution you like**
Add "+ Add" to:
Firewall -> Aliases
Firewall -> Categories
Firewall -> Shaper -> Pipes/Queues/Rules
Leave the small + sign at the end.

Add "Cancel" button, to revert the changes, if this is doable.
Move the Apply Changes out of the Firewall page to the top (left from the username) and let it sit there until confirmed when changes pending.

**Comment by kosta880** [comment]
Sorry, seems I missed this one: [#5047](https://github.com/opnsense/core/issues/5047)
Similar to my suggestion for Apply Changes.

**Comment by fichtner** [comment]
1. Please don’t merge different ideas in one collection ticket. It’s harder or impossible to get them done in practice. Discussions are going to be convoluted too.
2. I’m going to close this, because it is a duplicate and you haven’t searched for issues as you stated.

**Comment by kosta880** [comment]
My apologies. I will be more vigilant in the future and will not merge.
