### ISSUE TITLE
Refresh button in Live View does nothing?

### ISSUE THREAD

**Issue by kosta880** [opnsense/core#5058]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

Pressing the two round arrows in live view does nothing. My guess is it should "refresh" the view, as in delete all shown packets and start fresh.

**To Reproduce**

Simply pressing the button does nothing.

**Expected behavior**

As described, I would expect it to refresh something...

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 21.1.7-1 (amd64, OpenSSL).
Intel(R) Core(TM) i3-6320 CPU @ 3.90GHz (4 cores)
Intel NIC

**Comment by fichtner** [comment]
It just updates the view and it works fine.

You can easily confirm by disabling auto-refresh...


Cheers,
Franco
