### ISSUE TITLE
Add "+ Add" button to all Firewall pages

### ISSUE THREAD

**Issue by kosta880** [opnsense/core#5059]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**

Workflow problem. I am missing "+ Add" buttons on some firewall pages. And find myself, often on the Aliases page, scrolling down to the end of the page, to just add an alias. Becomes a problem with many aliases.

**Describe the solution you like**

Add "+ Add" to:
Firewall -> Aliases
Firewall -> Categories
Firewall -> Shaper -> Pipes/Queues/Rules
Leave the small + sign at the end too.

**Comment by fichtner** [comment]
Again, no, that’s https://github.com/opnsense/core/issues/4216
