### ISSUE TITLE
Hide nonexistent "Far Gateway" option for IPv6 gateways

### ISSUE THREAD

**Issue by Greelan** [opnsense/core#5066]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

When trying to add an IPv6 gateway to an interface, even if "Far Gateway" is selected OPNsense gives an error that the gateway IP address is not within the subnet assigned to the interface (if that is in fact the case).

The reason seems to be that line 127 for IPv6 in https://github.com/opnsense/core/blob/master/src/www/system_gateways_edit.php does not have the same far gateway check as line 97 for IPv4. Is this deliberate?

(The use case here is trying to create a gateway for a WireGuard interface, where the interface has both an IPv4 /32 configured and an IPv6 /128 configured. A gateway with a different IP is allowed for IPv4 if "Far Gateway" is selected, but not for IPv6. This is for the purpose of selective routing as per https://docs.opnsense.org/manual/how-tos/wireguard-selective-routing.html, where the VPN provider (Mullvad) provides both an IPv4 address and an IPv6 ULA for the tunnel. That said, the WireGuard Local configuration only allows one IP to be specified for the gateway, so even if an IPv6 gateway could be established it is not clear how that can be set for the WireGuard configuration as well as the IPv4 gateway... @FingerlessGlov3s, any thoughts on this last point? Is the only option to create the routes manually?)

**To Reproduce**

Steps to reproduce the behaviour:
1. Create a WireGuard interface with an IPv6 /128 address
2. Try to create an IPv6 gateway on that interface with a different IPv6 address and with "Far Gateway" selected

**Expected behaviour**

The error would not appear if "Far Gateway" is selected.

**Describe alternatives you considered**

N/A.

**Screenshots**

N/A.

**Relevant log files**

N/A.

**Additional context**

None.

**Environment**

OPNsense 21.1.7_1-amd64
FreeBSD 12.1-RELEASE-p18-HBSD
OpenSSL 1.1.1k 25 Mar 2021

**Comment by Greelan** [comment]
Ah, just saw this: https://github.com/opnsense/core/issues/4436. Assume that is my answer?

**Comment by fichtner** [comment]
Hi @Greelan,

I'm not sure about the WG gateway, but at least from the kernel perspective IPv6 does not allow far gateways, i.e. gateways that lie outside the subnet mask of the interface IPv6 address.

The UI could be improved to reflect that I guess.


Cheers,
Franco
