### ISSUE TITLE
Inconsistency: what is a "VPN" in OPNsense?

### ISSUE THREAD

**Issue by 8191** [opnsense/core#507]
There are different services in OPNsense potentially having some properties of a _VPN_: IPsec, OpenVPN, L2TP, PPTP, PPPoE (?), PPP (?), etc. . Some of them are called "VPN" at different points of the GUI, but others are not:

* The screen _System: System logs: VPN_ shows L2TP, PPTP, and PPPoE, but not IPsec and OpenVPN
* In the main section _VPN_ there are only IPsec, OpenVPN, and L2TP configurable
* PPTP and PPPoE are configured in the section _Services_

__Suggestions:__
* Maybe PPTP should move from the _Services_ to the _VPN_ section?
* I think PPP and PPPoE are not really considered VPN technologies (are they?). Maybe they should be called something like "dial-in services"?
* The screen _System: System logs: VPN_ should either contain also IPsec and OpenVPN logs, or should be renamed to something different than _VPN_. Also either PPP __and__ PPPoE should be shown, or non of them.

Other suggestions/opinions?

**Comment by fichtner** [comment]
PPTP is not secure, so it was just recently moved to Services to retain backwards compatibility. The VPN Diagnostics page still needs work as described in #461. L2TP I was also thinking of moving out of VPN, so there are only IPsec and OpenVPN as the true VPN solutions...

The pages have always been this way. By reordering the menu we've made these problems more visible and they will be cleaned up for 16.1 for sure.

PS: Some page names still have a "vpn_" prefix, but we'd like to avoid moving files as much as possible, it is risky as the pages may be called from various other pages, are registered in the ACL, etc.

**Comment by 8191** [comment]
@fichtner Technically speaking a VPN does not need to be secure. :wink: The traditional definition of a VPN does not require encryption, I would say... But from the point of usability I totally agree that PPTP should not be "promoted" as a VPN with similar features as IPsec.

What about renaming the _System: System logs: VPN_ to _System: System logs: Dial in services_ and removing PPTP and L2TP? The logs for these services could then go to the corresponding config section (like IPsec has it): _Services: PPTP: Log file_ and _VPN: L2TP: Log file_

**Comment by fichtner** [comment]
You're right, maybe as a sidestep to the whole debate we could actually call the VPN section "Secure VPN", but that is also a bit risky. The philosophy is to promote the best choices for VPN if users do not know it. If e.g. they know they need to use PPTP there is nothing that will stop them from using it. With that reasoning, it may be ok to leave VPN as OpenVPN and IPsec only.

The VPN Log will be split up, PPPoE goes to the PPPoE Service, PPTP to the PPTP Service and LT2P to the L2TP Service. The only reason I haven't done this yet is that the logs pages are all clones of each other and duplicate a lot of lines of code. Before adding new log pages, we should make sure we don't just copy them but reduce the code into a single template function/file maybe.

**Comment by 8191** [comment]
Sounds good to me! So let's close this issue, since #461 already deals with that topic?

**Comment by fichtner** [comment]
Let's leave this open, I've deleted the task from the other ticket. Thanks. :)

**Comment by 8191** [comment]
One more thing regarding L2TP and PPTP: What about having a sub item in VPN called _Legacy_ and putting L2TP and PPTP in there?

**Comment by fichtner** [comment]
We'd need a sub-sub menu level for this to work with the current menu flow. We've added one for the current structure, pushing for one more will not make it much better, especially when there only one potential use case (as of now).

**Comment by 8191** [comment]
The DNS services (Forwarder, Resolver, Dynamic DNS) would also be a candidate... :wink:

**Comment by fichtner** [comment]
DNS Filter and DynDNS (both types) have been merged into DNS Tools. DNS Resolver/Forwarder is a whole other story. The idea was to hide the one that isn't enabled and make a config setting to switch it and then finally merge the rest of the DNS Tools into the remaining item.

**Comment by fichtner** [comment]
Small ending note: VPN is now again meant in the traditional sense of Virtual Private Network. Thus, it now has a globe icon. PPTP was moved back. Only IPsec and OpenVPN get a closed lock to indicate their secure status. L2TP and PPTP are unlocked. I hope that's clear now. :)
