### ISSUE TITLE
For RA 'Router Priority' does not change default gateway preference

### ISSUE THREAD

**Issue by 53c70r** [opnsense/core#5079]
Setting 'Router Priority' in 'Router Advertisements' to values differing from 'Normal' does not change the advertises preferences which router should be prioritized in high availability setups.
This results in two servers now advertising the same default gateway preference causing trouble in Master/Slave - CARP HA setups.

**Comment by fichtner** [comment]
Have you confirmed this in /var/etc/radvd.conf ? FWIW, RA priority does not say anything about CARP in particular.

**Comment by 53c70r** [comment]
I'll check tomorrow the radvd.conf.
On client side both default routes were signaled as "medium" at least.

**Comment by fichtner** [comment]
I suppose if both sides are set to the same value that's true (including the HA sync option).

**Comment by 53c70r** [comment]
HA sync was disabled for dhcpv6/RA one set to medium the other to low.

**Comment by fichtner** [comment]
Ok, I'm not seeing any oddities on our end with that being said. Looking forward to hearing more details.

**Comment by 53c70r** [comment]
I checked again if RA received by clients contains the corresponding pref flags.
Since the clients receive the correct flags I consider this a client side problem and will close the ticket.
