### ISSUE TITLE
TOTP time drift specified breaks auth

### ISSUE THREAD

**Issue by hereCOMESlappy** [opnsense/core#5081]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [ x ] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [ x ] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

v21.1.7_1 - When I set 120 seconds in "Time Window" and 120 seconds in "Grace period" when creating an authentication server with TOTP, it breaks and when testing with Tester in will never pass authentication.

If I remove the Time Window and Grace period, it works

**To Reproduce**

Have a user with a TOTP seed created

Create a server of type "Local Authentication + TOTP"

Set "Time Window" and "Grace Period" to 120

Check "Reverse token order" to place TOTP code after password

Go to Tester and test the authentication, it fails.

**Expected behavior**

Tester should show that the authentication passes

**Describe alternatives you considered**

When I removed the Time Window and Grace Period (Made them blank) and they use default values, then it is working in that case.

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 21.1.7_1 (amd64, OpenSSL 1.1.1.1k).

**Comment by AdSchellevis** [comment]
You are aware that the other end needs to use the same "Time Window" as well (https://en.wikipedia.org/wiki/Time-based_One-Time_Password)? if the token switches every 30 seconds in the authenticator app, the server needs to use the same. The grace period however is flexible, it just defines how many of the generated numbers may be used.

**Comment by hereCOMESlappy** [comment]
> You are aware that the other end needs to use the same "Time Window" as well

Hmmm I think I wasn't, the info said : "The time period in which the token will be valid, default is 30 seconds. " and so I assumed from that wording by bringing it up to 120 seconds it meant that the code would be usable for 120 seconds. But I guess that's what the Grace period is for instead.
