### ISSUE TITLE
Unfortunate restart button icon / no refresh button

### ISSUE THREAD

**Issue by andreas-p** [opnsense/core#5084]
While not a technical bug, I consider this a gui design bug:

the "restart" button uses a graphic that is widely used as "refresh". Although I know this, it still happens to me that I'm mis-using the button. Latest incident: When observing the VPN/IPSEC/Status Overview, I wanted to refresh the display. Hitting the button I falsely identified as "refresh button", I restarted the ipsec service (deleting all traffic data and rendering the examination pointless, bummer.

Please consider changing the icon to the widely used restart icon (stop+start). In addition, a refresh button would be convenient (clicking the menu item isn't too intuitive and will close the traffic info box).

**Comment by fichtner** [comment]
Please consult https://github.com/opnsense/core/issues/4972 for prior work. As you haven't added a version number I cannot say wether you glossed over the recent change or actually having an issue with it.

**Comment by andreas-p** [comment]
Ok since I've been hit by this issue for ages I didn't expect such recent work, so I wasn't aware of #4972 . Continuing there.
