### ISSUE TITLE
All dynamic DNS updates conditional on CARP status

### ISSUE THREAD

**Issue by sesquipedality** [opnsense/core#5085]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**

A clear and concise description of what the problem is including your motivation for the request,
i.e. "For the purpose of [...] I am missing a solution that will [...]."

I have a CARP master and slave router, connected to different WAN connections for redundancy.  If the primary link goes down, the secondary takes over as master, and internet service is uninterupted.  What cannot be migrated with this setup are the services running inside my network, as they are all identified by dynamic DNS hostnames.  I cannot have both machines updating the hostnames because that would result in constant switching when both routers were operating.

**Describe the solution you like**

(e.g. I would like an input field in the `/ui/firewall/alias` which would add .... to ....)

I would like the dynamic DNS plugin to allow me to specify that I want certain dynamic hostnames to update only when the machine is CARP master.  That way when the master goes down, the secondary will start setting the DNS to point to it.  Transfer of the services ought then to be as seamless as transferring the connection internally.

**Describe alternatives you considered**

A clear and concise description of any alternative solutions or features you considered.

**Additional context**

Custom scripting to monitor CARP status and do the updates manually.  In my experience OpnSense does not play nice with user cron jobs, and I would prefer to keep using the built in DynDNS support if possible.

There may be another cleverer way to do this, DNS priorities perhaps, but my provider doesn't support setting a DNS priority when updating.

Add any other context or screenshots about the feature request here or links to relevant forum thread or similar

**Comment by sesquipedality** [comment]
This seems to have been listed as incomplete because I forgot to tick the boxes confirming I have read the policy and checked for similar issues.  For the avoidance of doubt I did both of these things before posting.  Please reflag appropriately.

**Comment by AdSchellevis** [comment]
for custom scripting on carp events, you might look at syshooks (https://docs.opnsense.org/development/backend/autorun.html#syshook)

**Comment by sesquipedality** [comment]
Thanks, that might present another way to approach this, although at the cost of periodic dyndns refreshes when the link status doesn't change.   That shouldn't be a problem if my provider leaves dyndns entries in place until overwritten.
