### ISSUE TITLE
Unbound doesn't work on interface assigned to WireGuard

### ISSUE THREAD

**Issue by kasper93** [opnsense/core#5088]
**Describe the bug**

When enabling WG interface is assigned ip. Problem is unbound access list is not updated and dns requests are refused from this interface.

**To Reproduce**

1. Set WireGuard
2. Assign interface
3. Reboot 
4. Connect to WG and try to query unbound server it will get refused. (unboud is set to all requests from all interfaces)

To workaround you need to manually restart unbound service after each reboot or WG configuration change.

**Expected behavior**

Unbound works...

**Comment by fichtner** [comment]
So you have selected specific interfaces in the unbound configuration?

**Comment by kasper93** [comment]
Like I said Unbound is set to "All" interfaces, but it doesn't matter if you select interfaces explicitly. The WG interface is not added to listening interfaces of unbound. Toggling interface or WG doesn't help, you need to restart unbound service manually.

After reboot (or change in WG config):
```
# cat /var/unbound/unbound.conf | grep ^interface:
interface: 192.168.1.1
interface: 127.0.0.1
```

After manually restarting unbound:

```
# cat /var/unbound/unbound.conf | grep ^interface:
interface: 192.168.1.1
interface: 192.168.100.1
interface: 127.0.0.1
```

Removed some unrelated interfaces, but you should get the idea, STR is in first post.

**Comment by AdSchellevis** [comment]
when it's set to "All" (no items selected), it should end up with something like this (which it does on my end):

```
# cat /var/unbound/unbound.conf | grep ^interface: 
interface: 0.0.0.0
```


Selecting "all" separate interfaces would end up with a listener on each one of them....

**Comment by fichtner** [comment]
Which means this is an ACL issue and easily doable by adding a manual entry. 😊

**Comment by mimugmail** [comment]
@AdSchellevis https://twitter.com/igor_os777/status/1413473270909661194?s=19

**Comment by kasper93** [comment]
> when it's set to "All" (no items selected), it should end up with something like this (which it does on my end):

Ah you are right, I tested with some interfaces selected. In this case there are two complementary issues. When `all` is selected indeed listen interface will be `0.0.0.0`, but still ACL `/var/unbound/access_lists.conf` will be missing WG interface address. If not `all` is selected, both listen interface `unbound.conf ` and acl `access_lists.conf` will be missing WG interface address.

> 
> 
> @AdSchellevis https://twitter.com/igor_os777/status/1413473270909661194

@mimugmail I mean really... There is no technical reason not to use either. And it is faster if you already had a less or cat command in history or want to change keyword without hotkeys dance to change second arg.

**Comment by fichtner** [comment]
The interfaces issue is not a bug. It only really works with static interfaces, but it’s mostly irrelevant to user desires wanting to “slim down” so this pops up all the time. However, the defaults are perfectly fine and safe.

The ACL issue is related to https://github.com/opnsense/core/issues/4040 which will be worked on next week. Maybe we can just push ACLs to unbound-control as we shouldn’t restart unbound all the time because an unstable VPN tunnel goes up and down. It flushed the cache while at it as this is the way unbound works.

**Comment by AdSchellevis** [comment]
@mimugmail I know, I know, I'm misusing [a] cat. was merely copying the line above, although being honest, I do use cat+grep|awk|.. quite often as well while fiddling on the shell :)

**Comment by fichtner** [comment]
Unfortunately for #4040 we cannot alter access-control with unbound-control, see

https://github.com/NLnetLabs/unbound/blob/45be3412678e42de728fd4e257893afceaf6c896/util/config_file.c#L788-L789

So we more or less go back to manual cache retain in Unbound: https://github.com/opnsense/core/issues/2750 and are thus able to reload as often as we want. Service is still disrupted though...

**Comment by fichtner** [comment]
4a1bc9f8b5 which is part of 21.7 actually removed the reload block so this has been solved.
