### ISSUE TITLE
Support for more formats for IP Aliases (ASN#, gzip IP lists, JSON)

### ISSUE THREAD

**Issue by nwo422** [opnsense/core#5096]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**

It would be a great addition if dynamic Aliases supported more formats such as:

- ASN#
- IP lists other than plain test (e.g. gzip lists)
- JSON like the one used by AWS ip range (https://ip-ranges.amazonaws.com/ip-ranges.json) or GitHub (https://api.github.com/meta) which are currently not parsed correctly by OPNsense

**Describe the solution you like**

Have a new ASN type alias in the Aliases page and have the Alias URL parser to support additional formats other than plain text ip lists

**Describe alternatives you considered**

Manually creating and maintaining aliases with 1000's of IPs is not a reasonable solution

**Additional context**

Add any other context or screenshots about the feature request here or links to relevant forum thread or similar

**Comment by wrobelda** [comment]
This sounds like a legitimate request, can it be acknowledged instead of closing it?

**Comment by mimugmail** [comment]
This issue is marked as help needed. If anyone wants to work on such a feature this issue can be reopened and assigned to this user

**Comment by openaspace** [comment]
no solution?
