### ISSUE TITLE
Adding domain search list to resolv.conf generate

### ISSUE THREAD

**Issue by pfevre** [opnsense/core#5102]
I'd like to add a field in System/settings/general that could be use to define a custom search list of domain is resolv.conf
I know where to add the code (line 161 of/usr/local/etc/inc/system.inc) for resolv.conf generation but I'd like to have help to introduce new config key: "domain search list"
to get something like:
```php
if (isset($syscfg['domainsearchlist'])) { ...
}
```
by the way Freebsd does not allow several "search" line in resolv.conf it only take the last one.
So the
```php
if (isset($syscfg['dnsallowoverride'])) {
        foreach (get_searchdomains() as $searchserver) {
            $resolvconf .= "search {$searchserver}\n";
        }
```
is buggy

Best regards

**Comment by pfevre** [comment]
I made a PR to add the feature.

**Comment by fichtner** [comment]
Hi @pfevre,

thanks for the bug report. I fixed it according to resolv.conf manual page see 5ec2b4.

As for your PR can you rebase that and discuss afterwards? I can see the use case but the implementation is a bit loose shuffling something into resolv.conf without further validation...

**Comment by pfevre** [comment]
I hope I did the validation correctly.
Let me know I will patch my install to check.
