### ISSUE TITLE
Traffic shaping wizard

### ISSUE THREAD

**Issue by coldbootinitheart** [opnsense/core#5107]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**

Currently OPNsense lacks any wizard to help with traffic shaping and everything needs to be done using pipes, queues manually, I think a wizard akin to pfsense's would help people new to traffic shaping and also have major convenience benefits.

**Comment by fichtner** [comment]
The short answer: a traffic shaping wizard will have to be implemented after the wizard subsystem has been replaced and there is no ETA nor contributor for this.
