### ISSUE TITLE
Not possible to set net.inet.ip.dummynet.pipe_slot_limit via System -> Settings -> Tunables, nor loader.conf.local

### ISSUE THREAD

**Issue by iMiMx** [opnsense/core#5110]
**Describe the bug**

Looking to increase the value of net.inet.ip.dummynet.pipe_slot_limit

When set via System -> Settings -> Tunables, or loader.conf.local, then restarting the firewall the modified value is not set - instead, defaulting to 100.  

Presumably because the dummynet module is not loaded at the point when the tunables are set (found another example of something similar on 'another' BSD based firewall that was patched/resolved).

**To Reproduce**

1. System -> Tunables -> Set net.inet.ip.dummynet.pipe_slot_limit to non-100 value
2. Restart the Firewall
3. Query net.inet.ip.dummynet.pipe_slot_limit, is set to 100

**Expected behavior**

The customised value is set, not the default 100 value.

**Work around**

Manually reload the sysctl service via the UI, after the firewall has booted, sets the correct value.

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 21.1.8_1-amd64

**Comment by fichtner** [comment]
I guess you can add "ipfw_load" with "YES" value to tunables and it should work.

Cheers,
Franco

**Comment by iMiMx** [comment]
I added to loader.conf.local (tried tunables via the UI as well)

```
ipfw_load="YES"
net.inet.ip.dummynet.pipe_slot_limit=300
```

Restarted the firewall, value of 100 is shown:

```
sysctl net.inet.ip.dummynet.pipe_slot_limit
net.inet.ip.dummynet.pipe_slot_limit: 100
```

**Comment by fichtner** [comment]
Sorry for cross-posting. It's rather confusing. Answer here. https://github.com/opnsense/core/issues/5111#issuecomment-884101863

**Comment by iMiMx** [comment]
Easy, perhaps, but still learning - but I tried my best to research, found evidence of someone else seeing the issue, they were asked to report but didn't as far as I can see.

I can confirm that the below, resolves this specific issue - but not the UI issue (will reply there for that.

```
ipfw_load="YES"
dummynet_load="YES"
net.inet.ip.dummynet.pipe_slot_limit=300
```

Is then set correctly:

```
sysctl net.inet.ip.dummynet.pipe_slot_limit
net.inet.ip.dummynet.pipe_slot_limit: 300
```
