### ISSUE TITLE
Shaper Pipe -> Queues slots limit appears to be hardcoded to 100 Max in the UI

### ISSUE THREAD

**Issue by iMiMx** [opnsense/core#5111]
**Describe the bug**

Potentially also related to the below:

https://github.com/opnsense/core/issues/5110

When increasing net.inet.ip.dummynet.pipe_slot_limit, the UI does not allow the Shaper -> Pipe -> Queue slot/size to be increased above 100 - it appears to perhaps be hardcoded in the UI.

As I understand it, the value of net.inet.ip.dummynet.pipe_slot_limit should be the sum of ALL Pipe Queue values, with the default of 50, assuming 2 queues, this value is reasonable.  Although I'm not 100% on this...

But, if you wish to increase net.inet.ip.dummynet.pipe_slot_limit to 600, for arguments sake, to perhaps allow for 300 per pipe, with 2 pipes, a value of 300 needs to be configurable in the UI per pipe:

However, it returns:

https://www.dropbox.com/s/x1p88hj6x71pvuz/Screenshot%202021-07-21%20at%2011.27.07.png?dl=0

FreeBSD documentation states

> queue {slots | sizeKbytes}
> 	   Queue size, in slots	or KBytes.  Default value is 50	slots, which
> 	   is the typical queue	size for Ethernet devices.  Note that for slow
> 	   speed links you should keep the queue size short or your traffic
> 	   might be affected by	a significant queueing delay.  E.g., 50	max-
> 	   sized ethernet packets (1500	bytes) mean 600Kbit or 20s of queue on
> 	   a 30Kbit/s pipe.  Even worse	effects	can result if you get packets
> 	   from	an interface with a much larger	MTU, e.g. the loopback inter-
> 	   face	with its 16KB packets.	The sysctl(8) variables
> 	   net.inet.ip.dummynet.pipe_byte_limit	and
> 	   net.inet.ip.dummynet.pipe_slot_limit	control	the maximum lengths
> 	   that	can be specified.

**To Reproduce**

1. Set net.inet.ip.dummynet.pipe_slot_limit to above 100 value
2. Firewall -> Shaper -> Pipes
3. Add a new pipe
3. Configure the Pipe Queue value, above 100
4. Error is returned

**Expected behavior**

The value configurable in UI, should either have no limit, or take its limit from the sysctl value - it appears to be hardcoded to a maximum of 100, via the UI.

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 21.1.8_1-amd64

**Comment by iMiMx** [comment]
I did find the below forum post, where a report was requested, but I can't see that it was reported:

https://forum.opnsense.org/index.php?topic=13249.0

**Comment by fichtner** [comment]
I guess you can add "ipfw_load" with "YES" value to tunables and it should work.


Cheers,
Franco

**Comment by iMiMx** [comment]
I added this to Tunables, then restarted the firewall.  With a slot_limit set to 300.

After a firewall restart, the 100 value is still shown:

```
sysctl net.inet.ip.dummynet.pipe_slot_limit
net.inet.ip.dummynet.pipe_slot_limit: 100
```

**Comment by fichtner** [comment]
You will have to add dummynet_load -> YES then.

I don't like it when no effort is given. It's really easy to figure out.


Cheers,
Franco

**Comment by iMiMx** [comment]
This does not resolve the UI issue:

```
ipfw_load="YES"
dummynet_load="YES"
net.inet.ip.dummynet.pipe_slot_limit=300
```

Is set correctly after firewall restart:

```
sysctl net.inet.ip.dummynet.pipe_slot_limit
net.inet.ip.dummynet.pipe_slot_limit: 300
```

UI limitation still persists:

https://www.dropbox.com/s/85x3sox08n55a1v/Screenshot%202021-07-21%20at%2012.10.19.png?dl=0

**Comment by fichtner** [comment]
Sure, it's two different issues around the same restriction.

I don't know how to make this flexible at the moment, but you can always edit it and see if it works:

    # vi +39 /usr/local/opnsense/mvc/app/models/OPNsense/TrafficShaper/TrafficShaper.xml

**Comment by iMiMx** [comment]
Seems to, yes - confirmed changes can be applied and shown correctly with 'ipfw pipe show'.

Whilst I assume these changes will perhaps be lost with a firmware upgrade, should/would the customised rules persist (not cause an error loading, verifying) as long as they are not edited?

Thank you for your time

**Comment by fichtner** [comment]
It will likely give an error on editing the rule with the bad value... not sure if adding/editing other rules is affected too.

**Comment by fichtner** [comment]
PS: The same could be achieved by changing the value in the /conf/config.xml

**Comment by iMiMx** [comment]
Understood - all things considered, I think I'm best off not... either looking at the code for a way to patch/resolve properly, contributing, or another solution to my problem :)

**Comment by fichtner** [comment]
we could bump the default and raise it. question is what particular use case requires this on your end? we'd like to understand the problem. not jump to a solution. :)

**Comment by iMiMx** [comment]
I perhaps need to do some more research - on what constitutes a 'queue slot'.

I had assumed, perhaps incorrectly, that this would be an IP if masking source/destination.  The default of 50 would perhaps be too low, I could see a requirement for above 100 if my assumption is correct.

**Comment by fichtner** [comment]
Ok, take your time. I'm not an expert on the shaper stuff, but I can try to assist if you have more data.

**Comment by iMiMx** [comment]
Presumably the default of 50 comes from net.link.ifqmaxlen, which also has a default of 50.

Relating to ipfw queue slots, the FreeBSD documentation states:

queue {slots | sizeKbytes}
Queue size, in slots or KBytes. Default value is 50 slots, which
is the typical queue size for Ethernet devices. Note that for slow
speed links you should keep the queue size short or your traffic
might be affected by a significant queueing delay. E.g., 50 max-
sized ethernet packets (1500 bytes) mean 600Kbit or 20s of queue on
a 30Kbit/s pipe. 

Presumably, an above-50, or even 100, limit is not entirely unreasonable, for longer paths, fatter pipes, than the default?
