### ISSUE TITLE
DHCPv6 "domain search" not honored while setting reverse resolution

### ISSUE THREAD

**Issue by ciroiriarte** [opnsense/core#5113]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

DHCPv6 overrides/reservations allow you to define the domain search list. According to the inline help, the first domain is used for DNS registration, but it's not honored for reverse resolution:

"If you want to use a custom domain search list for this host, you may optionally specify one or multiple domains here. Use the semicolon character as separator. **The first domain in this list will also be used for DNS registration of this host if enabled**. If empty, the first domain in the interface's domain search list will be used. If this is empty, too, the system domain will be used."

**To Reproduce**

1. Go to 'Services / DHCPv6 / LAN'
2. Add an static map, stating "something.com; yourdomain.com" for domain search list. yourdomain.com is the domain defined globally in the firewall
3. Allow the client to request IP.
4. IPv6 PTR record points to myhost.yourdomain.com instead of myhost.something.com
5. AAAA record is not set, since OPNSense doesn't handle something.com, which is expected/fine for my usecase.

**Expected behavior**

I would expect reverse resolution to answer that the IP points to myhost.something.com, being that the first entry in the domain search list.

**Describe alternatives you considered**

I've added an override within unbound, but that adds a second entry, hence the test IPv6 returns both "myhost.something.com" and "myhost.yourdomain.com". This breaks services that expect a single entry in the answer.

**Additional context**

Tested with OPNSense + FreeIPA, where some hosts need to be registered in other domain (not controlled by OPNSense), but reverse resolution is handled by OPNSense only.

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 21.1.8_1-amd64

**Comment by fichtner** [comment]
For static IPv6 address on LAN I think the solution is d2a183a7a8

    # opnsense-patch d2a183a7a8


Cheers,
Franco

**Comment by ciroiriarte** [comment]
If I apply this patch, do I need to apply any special procedure once it gets merged and released as a regular update?

**Comment by fichtner** [comment]
As it will be shipped in 21.1.9 there is nothing else to take care of during the next upgrade... given that this patch actually solves your issue (it should but we never know until we know).


Cheers,
Franco

**Comment by ciroiriarte** [comment]
I was more concerned about having to remove the patch before updating to avoid breaking things, something like that.

**Comment by fichtner** [comment]
Patches are automatically removed on updates. The only issue there is is when you need a patch but upgrade to a version without the patch it needs to be reapplied. In this particular case it’s not required.

**Comment by fichtner** [comment]
@ciroiriarte not sure if this was resolved with the patch... 21.1.9 will be out in a few hours so ideally I'd like to close or see if there is another error somewhere.

**Comment by fichtner** [comment]
Thanks!

**Comment by ciroiriarte** [comment]
to you
