### ISSUE TITLE
Alias resolv status and completion details

### ISSUE THREAD

**Issue by coldbootinitheart** [opnsense/core#5117]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

Currently if you create an Alias containing huge number of domain names, the firewall might take a few hours to resolv all of them, during that period timeouts and unresolvable domain names are bound to occur, and if the resolv process dies at somepoint you need to delete the alias and recreate it to trigger another resolv session (atleast from my testing). Apart from checking system > logs > general or the /var/db/aliastable directory there is no conveninet way to see the total amount of domains in the source, the amount which the firewall resolved and is resolving, and lastly the amount of domains unable to be resolved. Nor is there any indication (in the gui) of failure.

A progress bar with the above mentioned details and maybe a button to force trigger the resolv process, would be extremely helpful.

**Comment by AdSchellevis** [comment]
A progress bar is almost impossible the way alias resolving works, since we don't know the amount of work needed upfront. It's a recursive system for which every node calculates it's own work. However the time it takes to resolve hostnames could be improved quite a bit when using the new `asyncio` options in python.
