### ISSUE TITLE
unbound: use domain name specified in dhcp server when registering names

### ISSUE THREAD

**Issue by fichtner** [opnsense/core#5118]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**

Unbound will not register different domains for dynamic leases according to their domain name settings in the DHCP configuration.

**Describe the solution you like**

A configuration file for the lease watcher should be written prior to starting it to provide the daemon with the necessary lease ranges and domain names to be used.

**Describe alternatives you considered**

Leaving the current limitation in place which is fine for a larger portion of the user base.

**Additional context**

Recent discussion here: https://forum.opnsense.org/index.php?topic=24084.0

**Comment by ctrlbrk42** [comment]
Thank you franco :)  

I added my +1 to show support.

**Comment by hemirunner426** [comment]
+1.  Please let me know what you need for logs.
