### ISSUE TITLE
Additional BOOTP/DHCP Options didn't survive update

### ISSUE THREAD

**Issue by majorsl** [opnsense/core#512]
When I went from 15.7.18 to 15.7.21, I had one custom item in "Additional BOOTP/DHCP Options".

That didn't seem to survive the trip during the update. No big deal, I put it back, but it took me a few days to notice it was gone.

**Comment by fichtner** [comment]
Did you check your config history when this happened any maybe why? System: Config: History is pretty usable these days to find out when the entry disappeared and why or which component did the actual change.

**Comment by majorsl** [comment]
Hmmm, okay, I download some Configs to compare. In everything I downloaded the option I set is there, both before and after the upgrade - it never was lost.  However, I'm CERTAIN it wasn't showing up after and I put it back just today.

Is it possible that it was there in the config and just not shown in the GUI?

I'll make a note to check this again on the next update and see what happens.

**Comment by fichtner** [comment]
You don't have to download, you can select revisions to compare directly in the GUI :)

I will try to reproduce, thanks.

**Comment by majorsl** [comment]
15.7.22 had no problems with this. Worked as expected.

**Comment by fichtner** [comment]
Maybe this happened while editing another setting on the same page or simply saving it again?

**Comment by fichtner** [comment]
closing, can reopen if it happens again :)
