### ISSUE TITLE
Unbound stops forwarding to authoritative

### ISSUE THREAD

**Issue by ciroiriarte** [opnsense/core#5121]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

I have internal forwarding ("domain override" in GUI parlance) to a given domain, sending all requests related to it to two servers running bind backed by FreeIPA directory (2 hosts, several destinations including IPv4 & IPv6 addresses).

It all works for some time, and suddenly answers are replaced with NXDOMAIN from root servers

When works:

`
; <<>> DiG 9.16.6 <<>> @10.X.Y.2 cloudtest5.ipa.my.lab
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 56263
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;cloudtest5.ipa.my.lab.                IN      A

;; ANSWER SECTION:
cloudtest5.ipa.my.lab. 85141   IN      A       10.X.Y.Z

;; Query time: 0 msec
;; SERVER: 10.X.Y.2#53(10.X.Y.2)
;; WHEN: Tue Jul 27 17:17:45 EST 2021
;; MSG SIZE  rcvd: 67
`

When it doesn't work:

`
; <<>> DiG 9.16.6 <<>> @10.X.Y.2 cloudtest5.ipa.my.lab
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: **NXDOMAIN**, id: 5649
;; flags: qr rd ra ad; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;cloudtest5.ipa.my.lab.                IN      A

;; AUTHORITY SECTION:
.                       **3014    IN      SOA     a.root-servers.net. nstld.verisign-grs.com. 2021072802 1800 900 604800 86400**

;; Query time: 0 msec
;; SERVER: 10.X.Y.2#53(10.X.Y.2)
;; WHEN: Wed Jul 28 12:37:10 EST 2021
;; MSG SIZE  rcvd: 126

`

Querying the authoritative VMs, they always answer.

**To Reproduce**

1. Go to '/services_unbound_overrides.php'
2. Add domain entries pointing to several servers storing the same information
3. Keep querying the unbound resolver from time to time using dig, until it fails to resolve
4. You should see a NXDOMAIN error that seems to come all the way up form the root servers.

**Expected behavior**

I would expect to have consistent answer always forwarding to the authoritative.

**Describe alternatives you considered**

Restarting service regularly, but would be an ugly hack.

**Screenshots**

domain forwarding configuration:

![image](https://user-images.githubusercontent.com/1750260/127382905-d562c3eb-c183-43f8-a8f2-43bc94d01878.png)

**Relevant log files**

Couldn't find any relevant log entries. Will keep testing/reviewing & update with the findings

**Additional context**

Authoritative VMs running in the same virtual environment, both firewall and FreeIPA are configured with dual stack.

**Environment**

OPNsense 21.1.9-amd64
FreeBSD 12.1-RELEASE-p19-HBSD
OpenSSL 1.1.1k 25 Mar 2021

VM hosted on PVE 7.0

**Comment by xbb** [comment]
Did you try to configure one override at a time to see it this is happening with just one of them?

I use a stub-zone for my local zone with a configuration similar to this one:

```
server:
    domain-insecure: "example.com"
    private-domain: "example.com"

stub-zone:
    name: "example.com"
    stub-addr: 10.0.0.21
    stub-addr: 10.0.0.22
```

`domain-insecure` ignores DNSSEC validation for that domain
`private-domain` allows that domain to serve private addresses

**Comment by ciroiriarte** [comment]
Thanks for the feedback. What led me to open a ticket was the "works initially until it doesn't". Reading the unbound documentation, it seems the "stub-zone" you suggested is more appropiated for my use case.

Either using forwarding or the sub, it seems also the DNSSEC "skip" is required.

Right now I'm fiddling with the template setup to include those advanced configurations, I still can't make it work. I wonder if any of the advanced configuration methods mentioned in https://docs.opnsense.org/manual/unbound.html#advanced-configurations gets picked up by the backup module, do you know if that's the case?, which method are you using?

**Comment by xbb** [comment]
If you are still in 21.1.9 I think you have to use `/var/unbound/etc/`, but it was changed to `/usr/local/etc/unbound.opnsense.d/` in 21.7 (make sure you have a backup because, in my case `/var/unbound/etc` was cleared after the upgrade).

I place my advanced config files in `/root/conf/unbound/<name>.conf` with appropriate owner/permissions (root:unbound 750) and make links to the required destinations, in this case `/usr/local/etc/unbound.opnsense.d/<name>.conf` because I'm in 21.7

The backup module won't backup them for you

**Comment by fichtner** [comment]
If Unbound stops doing its job while not being restarted / reconfigured why not report a bug to Unbound to get it fixed? I mean how can we help here?


Cheers,
Franco

**Comment by ciroiriarte** [comment]
> If you are still in 21.1.9 I think you have to use `/var/unbound/etc/`, but it was changed to `/usr/local/etc/unbound.opnsense.d/` in 21.7 (make sure you have a backup because, in my case `/var/unbound/etc` was cleared after the upgrade).
> 
> I place my advanced config files in `/root/conf/unbound/<name>.conf` with appropriate owner/permissions (root:unbound 750) and make links to the required destinations, in this case `/usr/local/etc/unbound.opnsense.d/<name>.conf` because I'm in 21.7
> 
> The backup module won't backup them for you

I updated to 21.7-amd64, recreated config files from template & restarted Unbound. Now the stub-zone config is taken into consideration by the daemon. Will monitor the behaviour as it usually takes hours to fail.

**Comment by fichtner** [comment]
@ciroiriarte I'm not entirely sure but it looks that way... check for pid change and/or try to only reload the service to see if it was unbound itself, not the config:

    # cat /var/run/unbound.pid
    # /usr/local/sbin/unbound-control -c /var/unbound/unbound.conf reload


Cheers,
Franco

**Comment by ciroiriarte** [comment]
Well, PID didn't change, and starts working after reload.

# doesn't resolve 
root@vfw01:~ # cat /var/run/unbound.pid
35192
root@vfw01:~ # /usr/local/sbin/unbound-control -c /var/unbound/unbound.conf reload
ok

# resolves/forwards again
root@vfw01:~ # cat /var/run/unbound.pid
35192
