### ISSUE TITLE
Cannot boot after update to 21.7

### ISSUE THREAD

**Issue by r4nc0r** [opnsense/core#5123]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**
After the update to 21.7, my opnsense could boot, the error message can be seen in the screenshot below.
If I choose the Kernel.old in the boot screen, the opnsense boots correctly.

**To Reproduce**

1. Go to System -> Firmware -> Updates
2. Click on Update (to 21.7)
3. Opnsense doesnt boot after successful update

**Screenshots**

![opnsense error](https://user-images.githubusercontent.com/15196129/127446345-c7b0c04a-ec80-4056-a49f-562a5a2a29bf.png)

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 21.7 (amd64, OpenSSL).
Intel Celeron G3900 2-Core 2,80GHz 2MB
8 GB (1x 8GB) ECC DDR4 2666 RAM
Supermicro X11SSH-LN4F with a Onboard Quad LAN with Intel® Ethernet Controller I210-AT

**Comment by fichtner** [comment]
See https://forum.opnsense.org/index.php?topic=23867.0 the current assumption is that this is a kernel issue not a core issue and you can help verify. Thanks.

**Comment by r4nc0r** [comment]
Thanks for the link, i registered at the forum and posted my issue there as well :)

**Comment by fichtner** [comment]
> If i select the Kernel.old image in the boot screen, the opnsense starts fine. But I have to do this on every startup/reboot.
Modify message

Great tip, thanks a lot!

**Comment by AdSchellevis** [comment]
out of curiosity, which type of storage is being used here and is this a standard (ufs) install?

**Comment by r4nc0r** [comment]
a samsung ssd software raid, and yes a standard ufs install

**Comment by AdSchellevis** [comment]
likely this https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=229745 (and some luck it didn't trigger before in my humble opinion)

**Comment by r4nc0r** [comment]
issue has been resolved, the Kernel for 21.7 was updated in the opnsense repositories
https://forum.opnsense.org/index.php?topic=23867.0
