### ISSUE TITLE
IPsec Phase2 subnet dropdown always defaults to /32 after 21.7 update

### ISSUE THREAD

**Issue by mimugmail** [opnsense/core#5129]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

I have a Site2Site IPsec where left is LAN and right is 192.168.1.0/24.
After update everything runs fine, but when I edit the P2 and do nothing, the dropdown of netmask is /32 so the current value of it is not loaded. If I then just save the netmask also in ipsec.conf changes to /32.

Reproduceable when switching between 21.1 and 21.7

*Tip*: to validate your setup was working with the previous version, use opnsense-revert (https://docs.opnsense.org/manual/opnsense_tools.html#opnsense-revert)

**To Reproduce**

See above

**Expected behavior**

**Describe alternatives you considered**

A clear and concise description of any alternative solutions or workaround you considered.

**Screenshots**

Overview: 
![image](https://user-images.githubusercontent.com/20438689/127632290-2a51f2f6-17be-4968-b188-9ae8485d8ca7.png)

Edit P2:
![image](https://user-images.githubusercontent.com/20438689/127632358-fb5005e9-e321-4770-a94d-d90b5c5fc50e.png)

**Relevant log files**

If applicable, information from log files supporting your claim.

**Additional context**

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 19.1.1 (amd64, OpenSSL).
Intel® Xeon™ E3-1225V5 3.3Ghz Quad Core
Network Intel® I210-AT

**Comment by fichtner** [comment]
Can you try  60d6243 ?

**Comment by mimugmail** [comment]
Yep, works for me, thx

**Comment by fichtner** [comment]
❤️
