### ISSUE TITLE
IDS add ability to download custom URLs rulesets

### ISSUE THREAD

**Issue by nzkiwi68** [opnsense/core#5131]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**

There's no inherent ability to add a custom / additional URL source of rules to download and add to IDS.
I have a paid subscription to the Spamhaus Botnet Controller List and I'd love to be able to easily add this to IDS.

**Describe the solution you like**

Add a new GUI function to add custom download sources as a TAB
![IDS custom](https://user-images.githubusercontent.com/67399588/127725571-b737d3cc-f93c-4026-a114-ad4c3b5cd493.PNG)
.
Collect the following information:
* Description
* Alias
* URL download source
* Documentation URL (optional)

Example of my own custom rule .xml file.

`<?xml version="1.0"?>
<ruleset>
    <location url="https://pub-api.spamhaus.org/api/snort/" prefix="spamhausBCL"/>
    <files>
        <file url="https://pub-api.spamhaus.org/api/snort/?account=xxxxxxxxxxx&key=yyyyyyyyyy"
              description="Spamhaus Botnet Controller List"
              documentation_url="https://www.spamhaus.org/bcl/"
        >spamhausBCL.rules</file>    
    </files>
</ruleset>`

**Describe alternatives you considered**

There are none. Manually adding my own custom file to usr/local/opnsense/scripts/suricata/metadata/rules doesn't seem to work and ideally it would all be based in the GUI anyway.

**Additional context**

https://forum.opnsense.org/index.php?topic=24175.0

**Comment by AdSchellevis** [comment]
Manual downloads are not likely to be included, the xml definitions are quite easy to build, but you should be able to install manual rules in the normal way, just copy rule files to `/usr/local/etc/suricata/rules/` and execute `configctl ids update` to make sure the new files are being processed by suricata.

It might be a good idea to add the manual procedure to the docs sometime.

**Comment by mimugmail** [comment]
If you have a collection of some feeds I can add a plugin via my repo

**Comment by AdSchellevis** [comment]
@mimugmail as separate plugins, you can also add them to our repo, we also offer some others there like the sourcefire rules (https://github.com/opnsense/plugins/tree/master/security/intrusion-detection-content-snort-vrt)

**Comment by nzkiwi68** [comment]
> 
> 
> If you have a collection of some feeds I can add a plugin via my repo

I'd love you to add the Spamhaus Botnet Controller List, BUT!

It's a paid service so, the URL is;
**https://pub-api.spamhaus.org/api/snort/?account=xxxxxxxx&key=yyyyyyyy**

Where xxxxxxxx = your account number with Spamhaus and yyyyyyyy = your assigned API key

So each person must be able to supply their account number and API key for it to download.

**Comment by fichtner** [comment]
Same for ET pro and snort plugin. There are methods for this to set placeholders that can be filled from the GUI.

**Comment by kulikov-a** [comment]
@nzkiwi68 
hi. just my 2 cents
-you have params in url. if you add this ruleset via xml in ../suricata/metadat.. you need to escape "&" sign with` &amp;`
(tested. works. able to download rules)
-it's better to hide your login and key in the first post )
-as far as I can see this ruleset contains blocking rules by ip only? Isn't it faster to use ip-blocking in pf if spamhouse provides this list in the form of a simple list?

**Comment by nzkiwi68** [comment]
> 
> 
> @nzkiwi68
> hi. just my 2 cents
> -you have params in url. if you add this ruleset via xml in ../suricata/metadata.. you need to escape "&" sign with `&amp;`
> (tested. works. able to download rules)
> -it's better to hide your login and key in the first post )
> -as far as I can see this ruleset contains blocking rules by ip only? Isn't it faster to use ip-blocking in pf if spamhouse provides this list in the form of a simple list?

Opps!!!! I certainly meant to hide it but somehow I overlooked that. How embarrassing. Thanks for the note.
Spamhaus don't provide a simple IP list, the other list is via BGP.

I'll try the escape thing and see if it loads then....

**Comment by nzkiwi68** [comment]
Thanks!
Escaping the & worked perfectly. Sorry it took my so long to get back and try this.

I guess adding something to the manual for how to do this work be fine. It wasn't hard to do the XML thing. I just needed to know about the escaping the &.

Thanks again.

**Comment by AdSchellevis** [comment]
Sounds like case closed then :)

**Comment by Anth0rx** [comment]
> Manual downloads are not likely to be included, the xml definitions are quite easy to build, but you should be able to install manual rules in the normal way, just copy rule files to `/usr/local/etc/suricata/rules/` and execute `configctl ids update` to make sure the new files are being processed by suricata.
> 
> It might be a good idea to add the manual procedure to the docs sometime.

@AdSchellevis It seems rule files placed in the mentioned path get flushed on a regular basis.

**Comment by AdSchellevis** [comment]
@Anth0rx not by our software, which is quite easy to check (I do have one custom file on my development machine, which survived for years).

create a rules file and execute the download and merge `/usr/local/opnsense/scripts/suricata/rule-updater.py`, which should be the only proces in core touching these files.
