### ISSUE TITLE
Encoding error with special characters within the webinterface

### ISSUE THREAD

**Issue by Pascal3366** [opnsense/core#5132]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

This bug affects the OPNSense webinterface.
On some (but not all) pages special character like ä/ö/ü cannot be displayed correctly.
This seems to be somewhat related to the encoding although website encoding is set to UTF8 
which is perfectly fine.
If I change a tab back and forth e.g. in the surricata settings the special characters (umlauts) are suddenly there again or cannot be displayed again.

**To Reproduce**

1. Go to any page with umlauts (prerequisite: you are using a language with umlauts like 'German')
2. Click on any page with umlauts e.g. Services -> Intrusion Detection -> Management
3. The special characters are not displayed correctly. Instead there is a Unicode error <?>
4. See the encoding error

**Expected behavior**

The characters should be displayed correctly (ä,ö,ü)

**Describe alternatives you considered**

I double checked the selected language in the webinterface.

**Screenshots**

![](https://i.imgur.com/ZVjYGiA.png)

**Relevant log files**
 
I was not able to find any related error in the logs

**Additional context**

**Environment**

OPNsense 21.7-amd64
FreeBSD 12.1-RELEASE-p19-HBSD
OpenSSL 1.1.1k 25 Mar 2021
Intel(R) Core(TM) i5-4440 CPU @ 3.10GHz (4 cores)

**Comment by fichtner** [comment]
Does this patch help? https://github.com/opnsense/core/pull/5071

**Comment by Pascal3366** [comment]
> Does this patch help? #5071

Yes this commit seems to fix this bug.

**Comment by fichtner** [comment]
I'll just file this under cleanup. I have no idea why it only fails sometimes and something slightly related fixes that even though it's not needed in the first place.
