### ISSUE TITLE
Editing an existing IPsec Tunnel (Phase 2) overrides the Subnet Mask to 32

### ISSUE THREAD

**Issue by cluck** [opnsense/core#5134]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [-] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [-] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

Editing an existing IPsec Tunnel (Phase 2) overrides the previously configured subnet mask to 32 in the local and remote setting, at least for when Type 'Network' is selected.

**To Reproduce**

1. Edit an existing IPsec Tunnel Phase 2 which corresponds to the bug description above.

**Expected behavior**

Load the pre-existing value.

**Describe alternatives you considered**

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 21.7-amd64
FreeBSD 12.1-RELEASE-p19-HBSD
OpenSSL 1.1.1k 25 Mar 2021

**Comment by cluck** [comment]
The same happens on the Firewall Rules editor (here for a 'Single host or Network' Source).

**Comment by fichtner** [comment]
https://github.com/opnsense/core/issues/5129

**Comment by cluck** [comment]
Note: #5129 targets 22.1. Not sure if this means that the fix lands in 21.7.x soon.

**Comment by AdSchellevis** [comment]
Note: always keep an eye on the commits in stable (https://github.com/opnsense/core/tree/stable/21.7) to know what's being stashed for release,  which will likely include this commit shortly as well....
