### ISSUE TITLE
IPsec VTI interface name is linked to IKE Phase 1 Description, Interface settings not operable

### ISSUE THREAD

**Issue by cluck** [opnsense/core#5135]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [-] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [-] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

For IPsec VTI ("routed") interfaces, the interface name/descrption can't be edited in the usual place (the name just jumps back to the previous one upon save). Instead, the name is linked to the Descriton field in the IKE2 Phase 1.

**To Reproduce**

1. Try to rename the interface/description of a "routed" VTI interface

**Expected behavior**

The description field to work in the interace edit form.

**Describe alternatives you considered**

Change the descrption in the Phase 1 edit form.

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 21.7-amd64
FreeBSD 12.1-RELEASE-p19-HBSD
OpenSSL 1.1.1k 25 Mar 2021

**Comment by mimugmail** [comment]
The description is used as interface label, renaming might cause errors. Better to delete the P1 and set it up again

**Comment by cluck** [comment]
Can't confirm deleting is needed, as changing the description in the P1 works fine here. It is at the interface level where it becomes confusing, just at UI level. At this point I think greying out the description on VTI interfaces while adding a note about this inheritance from P1 is a perfectly good solution to this.
