### ISSUE TITLE
firmware: execute plugin resolution in console firmware update

### ISSUE THREAD

**Issue by fichtner** [opnsense/core#5136]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**

When restoring a configuration from a new install or doing an in-place installation the plugins will be missing. If GUI accessibility is affected by this (e.g. HAProxy setup) then you can't easily resolve plugin conflicts from the GUI.

**Describe the solution you like**

Now that we have the resolve plugin conflicts feature since 21.1.3 we should make it available on the console firmware upgrade. Maybe the easiest way would be to unconditionally invoke the plugin resolution on selecting option 12 after confirmation prior to kernel/base installation.

**Describe alternatives you considered**

A clear and concise description of any alternative solutions or features you considered.

**Additional context**

https://forum.opnsense.org/index.php?topic=24174.0

**Comment by teosoft123** [comment]
Hi Franco, I'm not sure one of the use cases will be covered, namely, if one (like I did) performs a fresh install from USB, and importing existing configuration. In this case, it's a fresh install, not an upgrade. 
If menu 12 will offer plugin reconciliation even when there's no new updates, this will work, and only for people who read documentation :) because menu 12 per se does not suggest that it can also reconcile the plugins.
I agree that adding a new menu entry might not be justified for such a narrow case. I dunno, many  help menu is needed?
All the menus are easy to understand, but now menu 12 has a hidden feature.

**Comment by fichtner** [comment]
Hi Oleg,

You are quite right, but... (famous "but" 😄 )

1. It's not such much hidden as it is automatic one might argue. The description in the script can be updated, the docs can be extended. Suggestions are welcome here.
2. It will work when there are no new updates.
3. We work under the constraint that remote packages being installed belong to a particular stable version. We did have issues in the past with bugfixes causing errors when people used a newer plugin (let's say 21.1.9 for example) with the newly installed 21.1 version. This combination needs to be avoided and I think we added a version check into the plugin installation from the GUI that says you need to update first to install the plugins. Actually, I think there is a bug in the plugin resolve that does not check for this yet.
4. From the GUI we have all sorts of "guided" (even if just visually) functionality and plugin conflicts handling is one of them. But on the console such things tend to get in the way of clear and simple workflow and it's often better to bundle existing features there for maximum effect.
5. Updating to the latest stable version is always recommended and should be done after each new installation which removes the blocking condition of point 3 automatically.


Cheers,
Franco

**Comment by teosoft123** [comment]
No worries, Franko. Perfect is, indeed, an enemy of good enough!
I installed 21.7 from USB stick today, and immediately after that, upgraded it to 21.7.1 from command line, and all plugins were installed. 
Unfortunately, HAProxy didn't start; I've experienced this before and it's unrelated.
Thank you!

 - Oleg

**Comment by fichtner** [comment]
Oleg, thanks for your input. Very helpful :)

Maybe https://github.com/opnsense/core/commit/0304b783a42 can help with this in the future? This allows to restart all plugin services as well from the shell.


Cheers,
Franco
