### ISSUE TITLE
Dashboard interface statistics widget - numbers don't line up

### ISSUE THREAD

**Issue by LennertVA** [opnsense/core#5137]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

I noticed there's a significant offset between the reported outgoing packets/bytes in the dashboard widget, and what is expected. I was expecting to see the outgoing WAN packets/bytes to be similar to the sum of the ingress of the other interfaces (plus whatever is generated by the firewall itself, e.g. management UI, SSH etc., but that's low enough to ignore here), there is a 40% higher number shown (see screenshot).

I checked the source of the widget and it uses pfctl numbers, so when I pulled those for the WAN interface, there is a big difference in what pfctl reports for outgoing WAN compared to what netstat sees (see output below).

What is most surprising me, is that this is **only for the outgoing WAN**. Incoming WAN, plus all other interfaces, have netstat and pfctl info fairly similar, as expected.

Any feedback on which number is correct, and how to make them line up? In the screenshot e.g., it seems as if there's 16GB appearing out of thin air (or from inside the firewall itself, which is not the case). This is pretty counter-intuitive, and has sent me  on a wild goose chase to find out what is generating this phantom traffic. 

**To Reproduce**

1. Enable the "Interface Statistics" widget on dashboard
2. Observe that outgoing WAN traffic is reported to be much higher than expected
3. Observe that netstat and pfctl statistics for outgoing WAN are vastly different

**Expected behavior**

I'd expect the numbers within the widget to make sense, which in turn means I'd expect the numbers in pfctl to make sense (like netstat, which does).

**Describe alternatives you considered**

N/A

**Screenshots**

![](https://user-images.githubusercontent.com/1744652/127679289-7d8b554a-10d7-4836-8919-c33a6143f82e.png)

**Relevant log files**

```
% sudo pfctl -i vmx1 -vvs Interfaces ; netstat -idb -I vmx1
No ALTQ support in kernel
ALTQ related functions disabled
vmx1
        Cleared:     Fri Jul 30 10:03:29 2021
        References:  124               
        In4/Pass:    [ Packets: 237320498          Bytes: 191259096190       ]
        In4/Block:   [ Packets: 66374              Bytes: 20490242           ]
        Out4/Pass:   [ Packets: 413745500          Bytes: 374882590676       ]
        Out4/Block:  [ Packets: 0                  Bytes: 0                  ]
        In6/Pass:    [ Packets: 46660606           Bytes: 47932781891        ]
        In6/Block:   [ Packets: 5323               Bytes: 3180023            ]
        Out6/Pass:   [ Packets: 57325096           Bytes: 47469630413        ]
        Out6/Block:  [ Packets: 0                  Bytes: 0                  ]
Name    Mtu Network       Address              Ipkts Ierrs Idrop     Ibytes    Opkts Oerrs     Obytes  Coll  Drop
vmx1   1500 <Link#2>      00:50:56:01:bl:ah 284052872     0     0 243269730831 297427867     0 248588902255     0     0 
vmx1      - fe80::%vmx1/6 fe80::bla:56ff:fe      760     -     -      48640      762     -      54864     -     - 
vmx1      - 135.bla.bla.0 bastion              80795     -     -    9916604    17108     -    1381093     -     - 
vmx1      - 2a01:bla:bla:2 bastion              15934     -     -    3441702     7351     -     722999     -     - 
```

**Additional context**

N/A

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 21.7-amd64
VM on VMware ESXi 7.2, Intel(R) Xeon(R) CPU E3-1275 v5 @ 3.60GHz (2 cores)

**Comment by AdSchellevis** [comment]
both `pfctl` and `netstat` measure different things, but at a first glance I would expect source (policy based) routing is in play passing packets duplicate through the interface (in which case `pfctl` may count these twice, you probably have to dig through the pfctl/kernel docs to find the details.

**Comment by LennertVA** [comment]
Wouldn't it make more sense then to base the statistics on netstat then, rather than pfctl? After all, when reading "Interface Statistics - bytes out" it would be logical to assume that this means the amount of bytes actually put on the network, which is not the case now it seems. It would also make the different numbers within the same widget to be aligned and not show "phantom" traffic.

**Comment by AdSchellevis** [comment]
to be honest when looking at the code, I do agree on that. This has been in here for a very long time, but since the same widget already uses the output `ifinfo`. can you check if the output of `ifinfo` reflects the right info?

**Comment by LennertVA** [comment]
> to be honest when looking at the code, I do agree on that. This has been in here for a very long time, but since the same widget already uses the output `ifinfo`. can you check if the output of `ifinfo` reflects the right info?

Yes, from what I can tell it does:

```
% sudo pfctl -i vmx1 -vvs Interfaces ; netstat -idb -I vmx1 ; ifinfo vmx1 | grep -e 'packets' -e 'bytes'
No ALTQ support in kernel
ALTQ related functions disabled
vmx1
        Cleared:     Fri Jul 30 10:03:29 2021
        References:  121               
        In4/Pass:    [ Packets: 2599443847         Bytes: 2171598934382      ]
        In4/Block:   [ Packets: 921400             Bytes: 73759301           ]
        Out4/Pass:   [ Packets: 4583998460         Bytes: 4327818566207      ]
        Out4/Block:  [ Packets: 0                  Bytes: 0                  ]
        In6/Pass:    [ Packets: 513220278          Bytes: 551510891824       ]
        In6/Block:   [ Packets: 8074               Bytes: 3697579            ]
        Out6/Pass:   [ Packets: 570403188          Bytes: 427999700657       ]
        Out6/Block:  [ Packets: 0                  Bytes: 0                  ]
Name    Mtu Network       Address              Ipkts Ierrs Idrop     Ibytes    Opkts Oerrs     Obytes  Coll  Drop
vmx1   1500 <Link#2>      00:50:56:01:0c:87 3113593917     0     0 2767662676322 3248840274     0 2800253395171     0     0 
vmx1      - fe80::%vmx1/6 fe80::250:56ff:fe     8206     -     -     525184     8208     -     590976     -     - 
vmx1      - 135.181.209.0 bastion             762605     -     -   90945056   156851     -   12697400     -     - 
vmx1      - 2a01:4f9:3a:2 bastion              96583     -     -   28171125    68900     -    6772039     -     - 
        packets received: 3113593968
        packets transmitted: 3248840332
        bytes received: 2767662730767
        bytes transmitted: 2800253446837
        packets for unknown protocol: 0
```

**Comment by AdSchellevis** [comment]
ok, let's change this to `ifinfo` then. Only status_interfaces.php will remain using the pf counters in that case, which makes more sense as it shows pass and block counters as well.

**Comment by fichtner** [comment]
status_interfaces.php uses the same filter counters... should it be replaced too and the backend script removed?

**Comment by AdSchellevis** [comment]
@fichtner I think we can keep the counters in status_interfaces.php because it also counts block/pass events (from the same source)

**Comment by fichtner** [comment]
@AdSchellevis ok, sounds good 👍
