### ISSUE TITLE
Unbound custom forwarders when Forwarding Mode Enabled.

### ISSUE THREAD

**Issue by FingerlessGlov3s** [opnsense/core#5138]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**

Back in 21.1 and prior there was a custom options option in unbound, this had now been removed. If you want forwards all DNS requests of unbound to say DNSCrypt for an example, this can no longer be done from within the WebUI. I think you should be able to do this without the requirement for a user to create a custom .conf file in "/usr/local/etc/unbound.opnsense.d/" to enable use of different DNS server(s) upstream when using unbound. You may not always want to use the same System DNS as you do for upstream unbound.

Example of contents of old custom options field, now required in custom file via CLI, when using DNSCrypt 
```
forward-zone:
  name: "."
  forward-addr: 127.0.0.1@15353
```

**Describe the solution you like**

Very simple extra field adding to "DNS Query Forwarding".
A text entry box, when left empty it'll use the DNS servers list from "System: Settings: General" when filled in it'll use those IPs listed for forwarding, making sure custom DNS ports are useable as well. So then you can specify "127.0.0.1@15353" as a DNS server to forward to, which could would solve the issue of any custom options required, making it much more user friendly.

**Describe alternatives you considered**

Using custom .conf file in "/usr/local/etc/unbound.opnsense.d/", work but I think this extra option would benefit many users.

**Additional context**

Screenshot of the idea
![image](https://user-images.githubusercontent.com/3495647/127926180-44a0e3b3-e6af-43ad-ba1b-a655edf1b9d0.png)

**Comment by FingerlessGlov3s** [comment]
One to make note of is if 127.0.0.1 is trying to be forwarded too `do-not-query-localhost: no` is required to allow this.

**Comment by fichtner** [comment]
@FingerlessGlov3s 2fa400beca is already in 21.7.1 and 580e6c7cc8107 is on the way

I still have trouble wrapping my head around a simple way to provide a forwarder interface that supports DoT, internal forwards and manual ones... it's a lot of modes that do almost the same (especially config-wise)

**Comment by fichtner** [comment]
To be shipped in 22.1.5 via bab7883c5674
