### ISSUE TITLE
[IPv6] NPTv6 should be able to track WAN interface address changes

### ISSUE THREAD

**Issue by ckauhaus** [opnsense/core#5139]
# Problem

I've got a WAN interface which receives a dynamic /56 prefix via DHCPv6. I'd like to use fixed ULA addressing with my LANs and have NPTv6 translate according to the prefix the WAN interface got today.

Currently, NPTv6 allows only static global/local prefixes. 

# Proposed solution

A feature similar to "Track interface", which allows me to specify the global NPTv6 prefix relative to an interface's address.

# Additional context

I'm behind a DTAG DSL line with dual stack configuration. After establishing a connection, they provide my both a dynamic IPv4 address and a dynamic IPv6 prefix. On the inside, I have stable IPv4 addressing (using NAT) but ever changing IPv6 addresses, which are a nuisance.

**Comment by fichtner** [comment]
See https://github.com/opnsense/core/issues/2544
