### ISSUE TITLE
CARP entry / wrong netmask

### ISSUE THREAD

**Issue by smalchow** [opnsense/core#5153]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

IN a previously configure carp entry (IPv4), the IPv4 netmask switches to /32 without any user interaction (seems to be the default), if you are not careful you overwrite the correct netmask and the basically kills the complete carp.

**To Reproduce**

1. Go to "Interfaces -> Virtual IPs -> Settings"
2. Click on "edit" on an existing IPv4 Carp entry
3. the IPv4 netmask will show as /32
4. when you click on "Save" the wrong netmask is saved

**Expected behavior**

The netmask should stay as previously configured.

**Describe alternatives you considered**

The workaround is to configure the netmask again when entering the entry

**Screenshots**

**Relevant log files**

If applicable, information from log files supporting your claim.

**Additional context**

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 21.7.1
KVM
virtio network interfaces

**Comment by fichtner** [comment]
Supposed to be fixed with https://github.com/opnsense/core/issues/5129 -- are you sure this is on 21.7.1?

**Comment by smalchow** [comment]
I am so sorry, yes, it is fixed in 21.7.1, i did the configuration this weekend and realized this, and the issue this morning after updating yesterday evening

**Comment by fichtner** [comment]
Ok thanks for confirming :)
