### ISSUE TITLE
IPSec Mutual RSA does not work as intended in 21.7 

### ISSUE THREAD

**Issue by dBitech** [opnsense/core#5155]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

OPNsense 21.7 (amd64, OpenSSL).

I'm experiencing the same issue as described [https://forum.opnsense.org/index.php?topic=24208.0](https://forum.opnsense.org/index.php?topic=24208.0) where asn1dn is being prepended and now the peer config is not found.   I have also confirmed that this does not work as expected, and receive the no peer config match when both endpoints in question are running OPNsence 21.7.

With the recent change in the way 21.7 handles the RSA certificate by using the new identity parsing with the ":" (https://wiki.strongswan.org/projects/strongswan/wiki/IdentityParsing)  I ran into some issues.

I have another strongswan instance running on a Linux server (not OPNSense), and on that remote instance, I have strongswan configured to use certificate in p12 format (which is supported as indicated here: https://wiki.strongswan.org/projects/strongswan/wiki/P12Secret

However, strongswan is a bit difficult on how the leftid / rightid needs to be filled in order for it to properly find the private key in the p12 certificate.
I found out that the best way to find out the private key in the p12 certificate to use is to use the asn1dn for rightid/leftid.

However, to use it properly, double quotes need to be put in place, and if they are not put exactly as strongswan expects.. then it won't find the private key to use in the p12 certificate.

For it to find it, the proper syntax is to have the whole "asn1dn:#307e310b30..."  in between double-quotes.
So, this does not work : asn1dn:"#307e310b30..."

And unfortunately, in version 21.7, it automatically writes the asn1dn:  for us when we select it in the dropdown with no possibility to add the double quotes before.
In the previous version (21.1 and before) it did not add the asn1dn:    so, it was easy to just go and put in the input field the whole "asn1dn:#307e310b30..."   and that would work.
But now, putting the whole "asn1dn:#307e310b30..."   in the field results in  asn1dn"asn1dn:#307e310b30..."   in the configuration file which is not working of course.
So, all this results in the IPSEC on OPNSense never finding a proper match (because of the way it generates the input in the config)

**Comment by AdSchellevis** [comment]
@dBitech can you try https://github.com/opnsense/core/commit/9963de28c04fb847a6dc49564747ffcd71fca5f7?

```
opnsense-patch 9963de2
```

**Comment by dBitech** [comment]
While this patch does make a way to have the VPN functional, it's not user-friendly in the least. 

You have to enter the peer Distinguished Name in HEX encoded.  You can get it  via ```pki --dn --in <cert>``` however there is nothing about this that is friendly. I would recommend reverting back to the old (21.1) behavior until a properly tested solution can be implemented in 22.1

**Comment by AdSchellevis** [comment]
how would that be any better? this commit only fixes the quoting as described in https://wiki.strongswan.org/projects/strongswan/wiki/IdentityParsing, in the previous version you needed to extract the exact same information.

**Comment by mtrr** [comment]
not entirely true, you could also have "CN=....." as leftid/rightid:

--
If the string value contains an equal sign (=), it is assumed to be a Distinguished Name (DN), with RDNs separated by
commas (,) or slashes (/ - the string must start with a slash to use this syntax). See the table below for supported RDNs.
An attempt is made to create a binary ASN.1 encoding from this string. If that fails the type is set to KEY_ID with the literal
string value adopted as encoding.
--

reverting back to the 21.1 behaviour would be nice, an alternative could be to have a "raw" option in the dropdown.

**Comment by fichtner** [comment]
Can we please stick to protocol here and not drag out fixes by adding complex follow up requests that clog up the process. If someone would open a ticket anytime in the last 5 years about things like this it would probably not take forever to to get included. ;)

**Comment by mtrr** [comment]
I meant that with 21.1 it was possible to have "CN=..." as either left or rightid, after the update that obviously ceased to work. 

cheers

**Comment by AdSchellevis** [comment]
We should probably add an auto-detection type and be done with it, as far as I can find you can't enforce type when using a cert reference (https://wiki.strongswan.org/issues/1028), so either you fix the type explicitly or you hope it leads to a result (which it doesn't do in all cases, https://github.com/opnsense/core/issues/4860) 

The previous approach (21.1 and earlier) assumed explicit typing, which in reality it didn't enforce, making "auto" an explicit choice sounds like a step forward.

**Comment by dBitech** [comment]
> I meant that with 21.1 it was possible to have "CN=..." as either left or rightid, after the update that obviously ceased to work.
> 
> cheers

And this was the identification method I used previously.  and in my opinion, this should still be supported.

**Comment by AdSchellevis** [comment]
@dBitech it does help if tickets contain all relevant details, but https://github.com/opnsense/core/commit/92ea6508887fef8b3fb4457c24163de52ba82fb6 contains the "auto" option which let's strongswan decide for it's own in the hope that it keeps working (parsing seems to be subjected to change, in which case we're not going to try to fix it, unless there's an explicit option). Closing this now, you can try the auto option using `opnsense-patch 92ea650`

**Comment by dBitech** [comment]
> @dBitech it does help if tickets contain all relevant details, but [92ea650](https://github.com/opnsense/core/commit/92ea6508887fef8b3fb4457c24163de52ba82fb6) contains the "auto" option which let's strongswan decide for it's own in the hope that it keeps working (parsing seems to be subjected to change, in which case we're not going to try to fix it, unless there's an explicit option). Closing this now, you can try the auto option using `opnsense-patch 92ea650`

I can confirm that "auto" restores the pre 21.7 behavior, allowing for CN=..... in the peer ID field as per [92ea650](https://github.com/opnsense/core/commit/92ea6508887fef8b3fb4457c24163de52ba82fb6)
