### ISSUE TITLE
Make Unbound DNS rebinding protection optional

### ISSUE THREAD

**Issue by feld** [opnsense/core#5161]
I migrated from my own DNS server to Unbound on OpnSense a while ago and recently had to access a serial console of a server at work. I was unable to resolve the domain because the address is within 10.0.0.0/8. Please allow me to turn off DNS rebinding protection. Serving RFC1918 addresses in public DNS responses is normal. Forcing use of a private DNS server over a VPN or using split-view DNS is really not best practice anymore. 

edit: I really don't want to have to try to add `private-domains` every time I encounter this issue, and I also serve users who won't even know to tell me that they're having this specific issue.

**Comment by fichtner** [comment]
Does System: Settings: Administration: "Disable DNS Rebinding Checks" do the trick?


Cheers,
Franco

**Comment by feld** [comment]
Yes, now the real mystery is why that isn't in the Unbound service configuration section. I don't think it should be global; it should be an option for each DNS server software that supports this. Please consider changing this in a future release.

**Comment by fichtner** [comment]
@reitermarkus mind taking this to https://github.com/opnsense/core/issues/5481 as we worked on the subsystem this week? It's better than trying to discuss on a closed support ticket.
