### ISSUE TITLE
support isc-dhcp include directive in web ui for dhcp configuration

### ISSUE THREAD

**Issue by razamatan** [opnsense/core#5162]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue
  - similar requests:
    - https://github.com/opnsense/core/issues/4814 - could have been addressed by this feature request

**Is your feature request related to a problem? Please describe.**

Sometimes, people just want to have custom settings in their dhcp configurations. For my purposes, I wanted my PXE clients to always download iPXE to have a consistent boot experience w/ PXE across hardware.  What I've done for now is patch `/usr/local/etc/inc/plugins.inc.d/dhcpd.inc` with this patch:

```
--- dhcpd.inc.old       2021-01-23 02:18:12.837213000 -0800
+++ dhcpd.inc   2021-01-23 02:24:36.257887000 -0800
@@ -635,6 +635,12 @@
 update-conflict-detection false;
 authoritative;
 
+if exists user-class and option user-class = "iPXE" {
+  filename "http://myspecialserver/pxe/ipxe/boot.ipxe";
+} else {
+  filename "undionly.kpxe";
+}
+
 EOD;
 
     $dhcpdifs = array();
```

**Describe the solution you like**

 It would be great to have an advanced setting in dhcp (both v4 and v6) that lets users point to a single [include file](https://kb.isc.org/docs/isc-dhcp-44-manual-pages-dhcpdconf#reference-declarations) that the user is free to manipulate in isolation. This gives end users flexibility to have custom setups without needing to patch core opnsense files.

**Describe alternatives you considered**

Keep patching `/usr/local/etc/inc/plugins.inc.d/dhcpd.inc`.

**Additional context**

Add any other context or screenshots about the feature request here or links to relevant forum thread or similar

**Comment by alex-s-team** [comment]
this request has existed for quite some time, but did not get any traction:

https://github.com/opnsense/core/issues/3557

after patching the plugin source ipxe works, but thats not a very satisfying solution.

**Comment by fichtner** [comment]
Did a flat include into resulting dhcpd.conf for IPv4 and IPv6 separately via directories that can actually create multiple files if needed.
