### ISSUE TITLE
All log views in web interface are showing old data

### ISSUE THREAD

**Issue by hanzoh** [opnsense/core#5164]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

Any log view (firewall live view or plain view, unbound log, system log) shows old logging data.
For firewall, I found that in /var/log/filter there is one file filter_20210813.log which has the last entry from Aug 13 10:10:04. This is exactly the entry that I see in the web interface.

**To Reproduce**

1. Go to http://<opnsense-ip>/ui/diagnostics/firewall/log
2. See outdated logs, refreshing does nothing.

**Expected behavior**

Most recent log entries should be shown.

**Describe alternatives you considered**

I have already reinstalled OPNsense (running in a Proxmox VM) and imported my configuration, same result.

**Screenshots**

n/a

**Relevant log files**

n/a

**Additional context**

n/a

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 20.8.1 (amd64, OpenSSL).
Intel(R) Core(TM) i3-7100 CPU @ 3.90GHz (2 cores)
Running in Proxmox VM (OVMF UEFI)

**Comment by joeyboon** [comment]
I can confirm I have the same problem. I had to restore after an SSD failure, used the backup config, everything worked great, but the GUI show logfiles in /var/log/FOLDERNAME/*, whilst /var/log/system.log is up to date. Same goes for firewall, unbound, etc.

Running:
OPNsense 21.7.3-amd64
FreeBSD 12.1-RELEASE-p20-HBSD*
AMD Ryzen 5 3500X 6-Core Processor (6 cores)

**Comment by AdSchellevis** [comment]
`/var/log/system.log` is only populated if circular logs are enabled (System->Settings->Logging "Disable circular logs" unchecked)

**Comment by hanzoh** [comment]
Yes! Disabling circular logs shows the live log for firewall again, also unbound log shows current entries.
Is this the new default in 21.7?

**Comment by joeyboon** [comment]
I solved the issues by resetting the log files in System -> Settings -> Logging -> Reset Log Files.

**Comment by AdSchellevis** [comment]
@hanzoh it's the new default since 21.7 indeed, if after an install old log files are still present I could imagine that leads to some confusion (the reader supports both, but will always assume the new format is preferred (and will order syslog.log after syslog/syslog_XX.log for example). close issue?
