### ISSUE TITLE
Feature Request: Add secure_mode option to UPnP configuration GUI

### ISSUE THREAD

**Issue by nettexan** [opnsense/core#517]
Would like to see secure_mode=yes in miniupnpd.conf as a toggle in the GUI.

While it doesn't make anything necessarily more secure it is a useful option to be able to easily toggle on, I would even argue it should be on by default (I don't think it is).

**Comment by fichtner** [comment]
Let's get the toggle into 15.7, switch defaults with 16.1 :)

**Comment by Self-Hosting-Group** [comment]
Configuration option implemented in OPNsense 25.7.9 for UPnP IGD and PCP protocol
