### ISSUE TITLE
Multi-WAN - local services work only on main WAN

### ISSUE THREAD

**Issue by OlegVekhov** [opnsense/core#5170]
Fresh install 21.7.1

Add two WAN interfaces, each with own gateway.

Enable SSH
Add rules on each WAN to allow incoming traffic on 80 and 22 TCP ports

I can access HTTP Web Configurator and SSH only on WAN where gateway is marked "Active"

If I manualy change gateway, WAN2 gateway becomes active, and I can access services only on WAN2

**Expected behavior**

Access to SSH and HTTP via any WAN address from Internet.

**Comment by mimugmail** [comment]
Interfaces besides DHCP and pppoe need an upstream gateway set in interface section

**Comment by OlegVekhov** [comment]
> Interfaces besides DHCP and pppoe need an upstream gateway set in interface section

Static interfaces, ethernet. Every interface has assigned upstream gateway in interface section

**Comment by mimugmail** [comment]
Then every packet reaches its Interface gets a reply-to rule and should work (if you did not manually disabled it)

**Comment by OlegVekhov** [comment]
> Then every packet reaches its Interface gets a reply-to rule and should work (if you did not manually disabled it)

I know it should work, but it not working. Tried many things before writing this issue. Was testing on production - neither port forward not local services working. 

Installed on test machine - the same situation. FYI, test machine which you can try yourself: 

http://86.62.114.187 - works
http://91.108.34.28 - not working

login and password default, fresh livecd boot

**Comment by marvinwankersteen** [comment]
@OlegVekhov Did you found a solution? I have the same problem for every incoming request.
The reply is returned on the non-active interface/gateway, with the active interface WAN IP.

Edit**:
Maybe you have created an Interface-Group for both WAN-Interfaces.
For interface groups, the "reply-to" does not seem to work.
In my version 22.1.6, the "Full-Help" at "Firewall --> Groups --> Create --> Members" says: _Rules for WAN type interfaces in groups do not contain the reply-to mechanism upon which Multi-WAN typically relies._

This solved the problem for me.
In the documentation is also a note about that: https://docs.opnsense.org/manual/firewall_groups.html#
