### ISSUE TITLE
Feature Request: Custom script on events

### ISSUE THREAD

**Issue by budimanjojo** [opnsense/core#5171]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**

According to the documentation here: https://docs.opnsense.org/development/backend/autorun.html
I can put script in the usr/local/etc/rc.syshook.d/<subdir> directory for some events. But I don't see something like "WAN Up", "VPN connected", etc. Is it possible to have this functionality? I don't think this should be hard to achieve. My use case for this feature request is because my ISP doesn't always give me private public IP and I need to keep reconnecting PPPoE connection until I get a "real" public IP. In Merlin firmware for my Asus router, I simply put a script in the wan-up event directory that check if I got IP address starting with `10.`, `172.`,`192.`, and if it's true, do "service wan restart". This script will automatically run whenever there is a wan up event that always change my WAN IP. Documentation for the merlin can be read here: https://github.com/RMerl/asuswrt-merlin.ng/wiki/User-scripts

**Describe the solution you like**

There are some ways to achieve this. Maybe as a custom post script after ddns update will do the same thing. But I think the best place is in the user script like the official documentation I linked above, because we can have custom scripts not only on wan event, but any events that can happen in the OS. 

I think this can also be achieved using Monit, but monit need to keep monitoring for IP changes which is not ideal for something that only need to happen not so often.

Thanks before 😊

**Comment by AdSchellevis** [comment]
the plugin framework more or less offer what you're looking for https://docs.opnsense.org/development/backend/legacy.html#configure

**Comment by budimanjojo** [comment]
@AdSchellevis Thanks! Can you help me with this?
Here is my current script:
```
    #!/bin/sh
    
    interface="vtnet0"
    WAN_IP=$(ifconfig $interface | grep "inet " | cut -d " " -f2)
    
    case $WAN_IP in
        10.*|172.*|192.*)
            echo "Private IP, restart WAN"
            ifconfig $interface down && ifconfig $interface up;;
        *)
            echo "Public IP, good!";;
    esac
```
Do I just put this script in the /usr/local/etc/inc/plugins.inc.d/newwanip_configure?

**Comment by budimanjojo** [comment]
After looking at some files in the directory, seems like I got a glimpse on how this work. Please guide me on this as I don't know much about php. Is this what I should do?
1. Create a file in `/usr/local/etc/inc/plugins.inc.d/mycustomjob.inc`
2. Inside that file, have this function, something like this:
```
<?php

function mycustomjob_configure()
{
    return array(
        'newwanip' => array('mycustomjob_configure_do')
    );
}

function mycustomjob_configure_do($verbose = true)
{
    <my script goes here>
}
```

Is that correct? Now the problem is I don't know how to convert my bash script into php :D

**Comment by AdSchellevis** [comment]
that should be more or less the trick indeed, worst case you can always use exec (https://www.php.net/manual/en/function.exec.php) to start another script :)

**Comment by budimanjojo** [comment]
I will try it. Thank you! Should I close this issue or leave it open?

**Comment by AdSchellevis** [comment]
close please :)
