### ISSUE TITLE
WIP: full dnsmasq support

### ISSUE THREAD

**Issue by comotion** [opnsense/core#5176]
- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues and I am convinced that mine is new.

Due to the lack of response on #4978 we started extending the dnsmasq plugin to support the dhcp and router advertisement features that dnsmasq supports, while remaining backward compatible, keeping the features that co-exist with ISC dhcpd and unbound. The intent is to contribute this back to opnsense core in the form of one or more pull requests, so that those who wish it can run a dual-stack, failover router with functioning dns on opnsense using dnsmasq.

Since the pull request will be rather large and we want to have a high likelyhood of getting it merged we would like to give the maintainers a proper heads up, make sure we aren't creating any conflicts. Please let us know if there is anything we should pay extra attention to.

This is still a work in progress, so I am not opening a pull request here yet, but if you are interested the not-yet-squashed diff can be found here https://github.com/Huddly/opnsense-core/pull/1

**Comment by AdSchellevis** [comment]
Realistically these type of PR's cost quite some time on our end and to be honest dnsmasq isn't really a priority since the combination of isc-dhcp and unbound delivers more or less the same functionality.  Don't get me wrong, dnsmasq is a nice all in one solution, we just have to choose preferences sometimes (and we don't want to expand the legacy code base, since at some point in time we have to spend a lot of time refactoring it again to mvc).

**Comment by comotion** [comment]
Indeed, reviewing a large-ish PR can cost quite some time at the maintainer end, and I hope to make that job as easy as possible. Through some quality code I hope to convince you that the feature is both neccessary and easy to maintain.

I've taken a look at the roadmap and it's hard to see what the priorities are after the 21.7 release.
The real issues we are seeing in the isc-dhcp and unbound combination will make the single-program solution help a lot in dual-stack deployments.
These issues nonwithstanding, the PR we are working on will simply expand the usability of the existing plugin, and doesn't mix code and presentation.
