### ISSUE TITLE
Donation via standard platforms

### ISSUE THREAD

**Issue by PetrVladimirov** [opnsense/core#5183]
Many people like OpnSense and appreciate the project openness.  

At the same time there are not so many opportunities to give back for non-developers or those with limited time.

I would suggest to provide an opportunity to donate money via standard platforms like OpenCollective, Patreon, Liberapay or GitHub native functionality.

In comparison to the currently available donation method via PayPal the suggested options provide:
- greater transparency
- better sense of contribution to a community
- more options for contributors to donate (some may prefer them over paypal for various reasons) 
- drive for bigger donations, especially if there is a clear gap between cost and income

As it is not so difficult to implement nowadays the benefits may quickly outperform the time spent.

**Comment by fichtner** [comment]
Hi,

> At the same time there are not so many opportunities to give back for non-developers or those with limited time.

So what problem are we attempting to solve here? What is "limited time" for non-developers and also for project owners?


Cheers,
Franco

**Comment by PetrVladimirov** [comment]
Thank you for the quick reply.

> > At the same time there are not so many opportunities to give back for non-developers or those with limited time.
> 
> So what problem are we attempting to solve here? What is "limited time" for non-developers and also for project owners?
- As I understand the only way non-developers can contribute (except paypal donations) is by testing and submitting issues. If they have no or limited time for doing that, donating via specialized platforms may be a way to go for them. 
- For developers that technically can contribute, but have no or limited time for doing that - money donation might be a way to go too.

> > more options for contributors to donate (some may prefer them over paypal for various reasons)
> 
> This seems like the only clear advantage to the proposal. I am not sure what transparency here means and how it is better (wording "greater").
- Re transparency: I didn't find a way to get a view on the amount of money gathered and amount of active contributors. These features are usually an inherent part of the donation platforms and having them in place will increase transparency in the donation space.

**Comment by mimugmail** [comment]
Is there a reason why you open the issues on multiple open source projects? Is there a personal reason about it?
https://github.com/wazuh/wazuh/issues/9932

**Comment by PetrVladimirov** [comment]
> Is there a reason why you open the issues on multiple open source projects? Is there a personal reason about it?
> [wazuh/wazuh#9932](https://github.com/wazuh/wazuh/issues/9932)

If an attempt to increase amount of donations for beloved projects for their long-term sustainability can be named a personal reason, then this is it :).
