### ISSUE TITLE
GRE: Firewall groups are not reassigned after editing tunnel configuration

### ISSUE THREAD

**Issue by vnxme** [opnsense/core#5189]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

When changing the existing GRE tunnel configuration on /[interfaces_gre_edit.php](https://github.com/opnsense/core/blob/master/src/www/interfaces_gre_edit.php), the tunnel seems to be recreated missing the corresponding firewall groups it is assigned to by [/interfaces_groups_edit.php](https://github.com/opnsense/core/blob/master/src/www/interfaces_groups_edit.php).

**To Reproduce**

1. Create a new GRE tunnel
2. Assign it to any firewall group, e.g. "test"
3. Use ifconfig to ensure it is assigned to "gre" and "test" groups
4. Change the tunnel configuration
5. Use ifconfig to ensure it is assigned to "gre" group only

**Expected behavior**

After editing tunnel configuration firewall groups should be reassigned.

**Environment**

OPNsense 21.7.1 (amd64, OpenSSL).

**Comment by fichtner** [comment]
0d5ef68 should fix it. VLANs and Bridges were suffering from the same problem.


Cheers,
Franco
