### ISSUE TITLE
Automate Git backup of config

### ISSUE THREAD

**Issue by tomlawesome** [opnsense/core#5190]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**
Not realted to an issue.

**Describe the solution you like**

Additions to the Web UI to allow automated backup of OPNsense config via Git. 

The UI would have various options for how often to push to the repo. 

**Describe alternatives you considered**
Running the update script from Cron

**Additional context**
I host my config in a (self-host) GitLab repo as an offsite backup. This would capture changes regularly and provide a simple method from which I can migrate to a clean install. 

Running a push every day automatically would allow me to effectively have daily snapshots of my config, so that I can prevent the loss of changes/tweaks and have a remote backup of them outside of OPNsense in case the drive dies.

**Comment by AdSchellevis** [comment]
https://docs.opnsense.org/manual/git-backup.html ?

**Comment by tomlawesome** [comment]
> https://docs.opnsense.org/manual/git-backup.html ?

Ah damn, I missed that apologies. 

Thanks so much for such a quick reply.
