### ISSUE TITLE
Allow logging on a specific fw rule to bypass filter.log and directly go to remote syslog server

### ISSUE THREAD

**Issue by pallebone** [opnsense/core#5191]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [ YES ] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [ YES ] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**

Logging in a granular way is very important in day to day, and I have this setup quite nicely. However I would also like to be able to log all traffic on an any any rule that would create too many log entries on the filter.log file when reviewing the live view or parsing the filter.log file.

As a result of this need to log all traffic, but not actually refer to it daily, I would like to be able to set logging on a specific firewall rule to only log to a remote syslog server that can hold a large amount of raw traffic log data for a period of time. This will keep clear the daily live view log and plain log files stored on the filter.log file in /var/log/

At the same time the syslog server will capture all log data that is needed while not hindering the more granular daily use of live log on the firewall itself.

**Describe the solution you like**
I would like an option on a firewall rule where it states "log packets that are handled by this rule" to also have an option "log packets that are handled by this rule only to remote syslog"

This means the firewall will only forward on the logging to the remote syslog for this specific rule and not attempt to write it in the local log file at all.
Under remote syslog settings where one normally sets filter (filterlog) a new entry might need to be created to indicate an option for remote only to monitor appropriatly.

**Describe alternatives you considered**

It would be possible to abandon using live log or the local log files altogether and only use a remote syslog server, but this would reduce ease of administration and the easy to use functionality of the log included on opnsense.

**Additional context**

None.

Many thanks for your consideration.
Kind regards
Pete

**Comment by AdSchellevis** [comment]
It's definitely not very high on our priority list, but in theory you should be able to create more logging interfaces and choose where to send messages to in `pf`.  

In most cases local disc space isn't a huge issue, in which case it doesn't make a lot of sense to add the complexity needed for multiple log targets (it will need additional `pflog` interfaces, listeners to handle the messages {currently handled by `filterlog`} and glue to allow configuration, a lot of work for a small use case).

**Comment by pallebone** [comment]
Ok no problem I understand. Maybe this will change in the future :)
Maybe even just a different log file on the disk for some rules would be helpful.
But no worries, thanks for checking anyway :)

Pete
