### ISSUE TITLE
ssh id is not kept across reboot

### ISSUE THREAD

**Issue by JulienDlq** [opnsense/core#5193]
**Describe the bug**

If I ssh-copy-id on my opnsense, then I can use my ssh keys to connect to my opnsense, that's cool.
But, after a reboot, id is lost on my opnsense, so I have to ssh-copy-id again in order to use my ssh keys to connect to my opnsense, that's not cool.

**To Reproduce**

1. ssh-copy-id your keys to opnsense
2. connect to opnsense, the keys are accepted
3. reboot
4. connect to opnsense, it asks for password…

**Expected behavior**

connect to opnsense, the keys are accepted.

**Describe alternatives you considered**

Remember to push again with ssh-copy-id my keys to my opnsense if I reboot it.

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 21.7.1-amd64
FreeBSD 12.1-RELEASE-p19-HBSD
OpenSSL 1.1.1k 25 Mar 2021
Intel Core Processor (Skylake, IBRS) (4 cores)

**Comment by fichtner** [comment]
TBH, I don't know what ssh-copy-id does and I suspect that it's simply not supported in the grand scheme of things. If you want your keys to stick you should add them from the GUI.

**Comment by fichtner** [comment]
No problem. :)
