### ISSUE TITLE
OPNsense 21.7.1-amd64 out of swap space

### ISSUE THREAD

**Issue by HuseyinPARMAKSIZ** [opnsense/core#5195]
**Current software version and hardware information:**
![image](https://user-images.githubusercontent.com/47844849/131840676-481a532a-dee1-45a7-b59d-ef1c6c491fe9.png)
yesterday we just got an error like this:
![image](https://user-images.githubusercontent.com/47844849/131841048-346dfe87-5c09-4cae-ae2c-bbd3e472f5f0.png)
After this error, the suricata service stopped and we restarted it. Suricata lists are updated daily via cron around 19:30.
![image](https://user-images.githubusercontent.com/47844849/131841265-e11d9b9f-c0cd-43fb-9d51-999bf7361437.png)
Below is the output of the above command.
![image](https://user-images.githubusercontent.com/47844849/131841332-00af2280-643f-4ffb-beae-968d9d565f29.png)
Any idea why swap usage is 99% and above, even though ram usage is not excessive?
https://roofman.me/2021/01/26/opnsense-resize-disk-space/ I'm going to try swapoff and swapon parameters like at this address, otherwise I'm thinking of restarting the server. But the reboot process is in the range of 10-15 minutes on the R720 server, so how can we find a solution without interruption.
we are using Suricata policies with Hyperscan.Is there a list of rules you can recommend apart from the following?
![image](https://user-images.githubusercontent.com/47844849/131842087-94a43d08-44b9-42bf-aaff-0e46a04538b9.png)

**Comment by fichtner** [comment]
You are out of RAM. Please add more RAM.

**Comment by HuseyinPARMAKSIZ** [comment]
server has 32GB of ram, insufficient?

**Comment by fichtner** [comment]
I don't know. It's not my server or setup. :)

**Comment by HuseyinPARMAKSIZ** [comment]
![image](https://user-images.githubusercontent.com/47844849/131845665-a7b0bdfe-8c02-4d3e-97a2-1390a43953f6.png)
It seems like the ram is not actively used in the live system, it claims to use cacti close to 100%, but I think it includes the laundry part.
![image](https://user-images.githubusercontent.com/47844849/131845759-be3534cf-b5f1-4649-8d35-ed6f25b8f8df.png)

**Comment by fichtner** [comment]
What can I say? The SWAP was touched shortly before 6 p.m. and has been wired since. It's pretty obvious you were out of RAM even if just for the shortest amount of time.

**Comment by mimugmail** [comment]
Do you run maltrail?

**Comment by HuseyinPARMAKSIZ** [comment]
we don't use maltrail yet, can you recommend in terms of system resources?

**Comment by HuseyinPARMAKSIZ** [comment]
We do not observe any problems after server cold reboot. I turned off the extra unbound service and narrowed the AmaVis parameters.  and now the use of RAM is around 10%.

**Comment by fichtner** [comment]
Ok cool, close this ticket then? :)
