### ISSUE TITLE
Google Drive password with '"' and '>' is not correctly escaped

### ISSUE THREAD

**Issue by CalmViper** [opnsense/core#5197]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

When inputing password with `"` and `>` into Google Drive's Password and Confirm box, password is getting splitted and part of it is shown below the input

**To Reproduce**

1. Go to 'diag_backup.php'
2. Input Google Drive data
3. In `Password` and `Confirm` input paste `"sometext>thisshouldnotbevisible`
4. Click `Setup/Test Google Drive`

**Expected behavior**

Password is replaced with dots

**Screenshots**

![image](https://user-images.githubusercontent.com/83116251/132135328-bc5ce39c-bff2-4da4-b60e-05fdb82cdc70.png)

**Relevant log files**

If applicable, information from log files supporting your claim.

**Additional context**

**Environment**

OPNsense 21.1.9_1-amd64
FreeBSD 12.1-RELEASE-p19-HBSD
OpenSSL 1.1.1k 25 Mar 2021

**Comment by AdSchellevis** [comment]
oops, wrong source used, https://github.com/opnsense/core/commit/4c4266045e88eb1411429104ca47e5cbf254a8cc should fix this.
