### ISSUE TITLE
IPv6 not updated on rtadvd when PPPoE IP/6rd IPv6 update

### ISSUE THREAD

**Issue by neelchauhan** [opnsense/core#5198]
**Describe the bug**

I have an OPNsense 21.7 box on CenturyLink Fiber, and whenever the PPPoE session changes the IPv4 (which for some reason happens often), and therefore the IPv6 which is via 6rd, rtadvd continues to broadcast the old prefix unless i restart rtadvd or reboot the router.

**To Reproduce**

1. Setup PPPoE/6rd.
2. Wait for the IPv4 to change
3. IPv6 router advertisements advertise the old IPv4, unless you restart rtadvd

**Expected behavior**

**Describe alternatives you considered**

A clear and concise description of any alternative solutions or workaround you considered.

**Screenshots**

N/A (for now)

**Relevant log files**

N/A (for now)

**Additional context**

IPv6 is via 6rd - no native IPv6.

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 21.7 (amd64, OpenSSL).
Intel Core i3-10100
HP S01-pF1013w
Intel i350-T4 + Realtek Onboard for PPPoE (Yes, I know Realtek NICs are "bad")

**Comment by fichtner** [comment]
Hi @neelchauhan,

I don't have any experience with 6RD on PPPoE so I need more help to get the full picture.

What are your PPPoE settings? Specifically are you using the "Use IPv4 connectivity" advanced option? What is the contents of /var/etc/radvd.conf before and after manual fix?

Also, 21.7.1 has a fix for shifting prefix on PPPoE in general so it would be good to know that this is not what you're looking for.


Cheers,
Franco

**Comment by fichtner** [comment]
@neelchauhan ping :)

**Comment by hemirunner426** [comment]
I’m seeing the same behavior in 21.7.3.  I do have prefer ipv4 setting checked.

I’ll have to get a dump of radvd.conf and post it here.
Happy to provide any other info.

**Comment by hemirunner426** [comment]
Here is my radvd.conf

# Automatically generated, do not edit
# Generated for DHCPv6 server lan
interface igb1 {
        AdvSendAdvert on;
        MinRtrAdvInterval 200;
        MaxRtrAdvInterval 600;
        AdvLinkMTU 1280;
        AdvDefaultPreference medium;
        AdvManagedFlag on;
        AdvOtherConfigFlag on;
        prefix 2602:ae:11a8:ca00::/64 {
                DeprecatePrefix on;
                AdvOnLink on;
                AdvAutonomous on;
        };
        RDNSS 2602:ae:11a8:ca00::1 {
        };
        DNSSL anderson.lan guest.anderson.lan iot.anderson.lan vpn.anderson.lan contoso.local {
        };
};

For now, I've turned off the prefer IPv4 setting to see if this changes any behavior.

**Comment by neelchauhan** [comment]
For me, I'm now primarily using Hurricane Electric tunnels since:

 * HE 6in4 has better performance than CenturyLink 6rd
 * HE tunnels have static IPv6 prefixes, whereas a router reboot can change CenturyLink's IPv6 prefixes (nor surprising)

The only thing I did is blackhole Netflix and CenturyLink's website from the tunnel, so I'm not blocked.

Google Fiber/Webpass in my previous place, "dynamic" IPs were generally very stable. CenturyLink, "dynamic" is truly dynamic.
