### ISSUE TITLE
UI bug expanding aliases in firewall rules

### ISSUE THREAD

**Issue by knan-md** [opnsense/core#5199]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x ] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x ] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

In firewall rules, when hovering over an alias to inspect it - the UI only shows 10 entries even if there are more, with no indication that there are more. This is confusing.

I would expect there to be a ... or similar to indicate that there are more entries in the alias.

**To Reproduce**

1. Go to Firewall => Aliases
2. Add an alias with more than 10 hosts/ips
3. Apply
4. Go to firewall => rules => floating (for example)
5. Add a firewall rule using your big alias
6. Hover over the alias in the rule list
7. See that the alias tooltip only lists 10 items, with no indication that there are more

**Expected behavior**

I would expect an indication that there are more than 10 entries in the alias, for example an ellipsis (...)

**Describe alternatives you considered**

Listing all entries in the tooltip may be unmanageable for big aliases.

**Screenshots**

<img width="1306" alt="Screenshot 2021-09-06 at 14 42 28" src="https://user-images.githubusercontent.com/61788597/132221717-30a65379-bc4d-437f-8f1f-add8ed45b7f5.png">

**Environment**

OPNsense 21.7.1

**Comment by mimugmail** [comment]
Not a bug, its hardcoded to the first 10 for safety reason

**Comment by knan-md** [comment]
As I wrote, I understand that, but then you need to indicate that there are more entries that are not shown.

**Comment by fichtner** [comment]
@knan-md can you try this patch?

    # opnsense-patch 35ec0ae


Cheers,
Franco

**Comment by knan-md** [comment]
Looks good to me! Tested on our firewall with no issues.

**Comment by fichtner** [comment]
@knan-md great, thanks for the report!
