### ISSUE TITLE
CARP backup doesn't stop service

### ISSUE THREAD

**Issue by LensHunnel** [opnsense/core#5200]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

Hello,

I have two Opnsense instance working as active/passive. There is a openvpn server on each node. The openvpn server listens to a Virtual CARP IP.

When the second node become CARP master (for node 1 maintenance) openvpn starts on the second node and that's great. The problem is that when the node 1 become CARP master and the second node become CARP backup, openvpn server doesn't stop. 

**To Reproduce**

1. Setup two instances of opnsense with an openvpn server configured to listen on a virtual CARP IP. 
2. Stop the node 1 ( CARP master), the second node will become CARP master. 
3. Start the node 1, it should become CARP master  and the node 2 CARP Backup.
4. Openvpn server starts working on node 1 
5. Problem: Openvpn server is still working on node 2 

**Expected behavior**

After starting the node 1 (CARP Master), the second node (CARP Backup) should stop all service attached to a virtual CARP IP.

**Describe alternatives you considered**

I could use monit to stop openvpn when carp status become BACKUP.

**Environment**

Software version used and hardware type if relevant:

OPNsense 21.1.9_1-amd64
FreeBSD 12.1-RELEASE-p19-HBSD
OpenSSL 1.1.1k 25 Mar 2021

**Comment by fichtner** [comment]
Looks like you talk about ecdf0404b73d but I don't see the full picture. Can you elaborate why this is bad (now anyway)?


Thanks,
Franco

**Comment by fichtner** [comment]
I guess e6d3d95ba63cea39 is a little clearer for context.

**Comment by LensHunnel** [comment]
It shouldn't have two openvpn servers working at the same time if we have an HA setup working with one node active at time, shall we ? 

When a node becomes a CARP backup, shouldn't it stop the openvpn server? to match the configuration one node active at time ?

**Comment by fichtner** [comment]
Basic question rather is: what is the downside of an unreachable server left active on the backup node? For one it can help with transition by leaving it on as standby.

**Comment by LensHunnel** [comment]
The problem is about network routes. The second node still have a route to the VPN network. So when trying to access the second node with an IP in the VPN Network. It doesn't work.

**Comment by LensHunnel** [comment]
I will use monit to stop openvpn when carp status become BACKUP.

**Comment by fichtner** [comment]
> The problem is about network routes. The second node still have a route to the VPN network. So when trying to access the second node with an IP in the VPN Network. It doesn't work.

Which configuration option in the server is causing this?

**Comment by LensHunnel** [comment]
Sorry about the delay, there isn't an option for that. In HA configuration, I have a node 1 with disable preempt deselected and a second node with disable preempt selected. That makes node 1 become CARP MASTER at boot. ith that configuration when I shutdown node 1, the node 2 become CARP Master and starts its VPN server with a Tunnel Network set for example (172.16.0.0/16). Then when I start node 1, it becomes CARP MASTER and starts its VPN server which has the same configuration that node 2. The problem, I can't reach the node 2 with a VPN client  because its VPN server still started and node 2 has a route to the VPN network via its own tunnel interface which doesn't work because node 2 isn't MASTER anymore.

Is it more clear ? if not, no worries I found an alternative to work it around. Thanks for your time

**Comment by AdSchellevis** [comment]
Usually these type of issues are related to misconfigurations in which case "crashing out the server" smoothens part of the operation, but doesn't bring the desired behaviour. 

Disabling preempt often masquerades other issues, for most setups you really don't want to disable this option (as it decouples the behaviour where all carp interfaces act as a group as explained in https://docs.opnsense.org/manual/hacarp.html#disable-preempt)

**Comment by LensHunnel** [comment]
Hello @AdSchellevis 

Even leaving the default setup (disable preempt deselected), there is the same issue.

**Comment by AdSchellevis** [comment]
@LensHunnel I was just mentioning what the advised setup is and why services shouldn't stop when changing roles, but if you have a workaround, maybe it's better to close the issue.
