### ISSUE TITLE
Netmask for IPSec routed tunnels is calculated incorrectly

### ISSUE THREAD

**Issue by bimbar** [opnsense/core#5201]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

A clear and concise description of what the bug is, including last known working version (if any).

*Tip*: to validate your setup was working with the previous version, use opnsense-revert (https://docs.opnsense.org/manual/opnsense_tools.html#opnsense-revert)

**To Reproduce**

Create a routed ipsec tunnel. Enter values for local and remote address that are not neighbors (form a /30 network).
Then, the subnet mask is automatically calculated in weird and wildly wrong ways.

**Expected behavior**

There is a local and a remote address, but no subnet mask can be entered. Thus, the subnet mask should be automatically calculated correctly. Or better still, I expected a way to enter a subnet mask.

**Describe alternatives you considered**

Just use /30 networks, that should in theory work.

**Additional context**

This has been extensively discussed in the forum here: https://forum.opnsense.org/index.php?topic=24546.0 and here: https://forum.opnsense.org/index.php?topic=23901.0 . The exact place it goes wrong is here as referenced by franco in the forums: https://github.com/opnsense/core/blob/1aeb52063159df6da3546d132a765557e6a96a6d/src/etc/inc/plugins.inc.d/ipsec.inc#L1871 .

Now what I would wish to be the solution is to be able to enter the subnet mask manually, since no automatism can possibly encompass all the reasons someone might have to use a specific mask (at least, I don't see how it would decide between /30 and /31), but at least it should calculate it correctly, so it doesn't fail if the IP addresses are too far apart or use an unexpected value.

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 21.7 (amd64, OpenSSL), but probably every version since the feature was introduced.

**Comment by AdSchellevis** [comment]
The current calculation intends to return the smallest possible subnet where both addresses can reach each other, which is basically the only purpose of specifying the net here. If we can’t calculate it properly, a workaround might be to add a subnet selector, although this will lead to confusion by other users… it’s probably a good idea to extend the ticket with some test cases first, which work and which are (obviously) wrong.

**Comment by mimugmail** [comment]
Sounds similar (or duplicate) of https://github.com/opnsense/core/issues/4029 
There's also an explanation on which cases it fails or might fail

**Comment by bimbar** [comment]
It pretty much fails all the time, because it does not use a base 2 logarithm, but subtracts the IPs from one another. In one of the threads I referenced a subnet mask of -68 was calculated.

Besides, with IPv6 you would want to be able to decide if you want to use a /127, a /126 or a /64 as link network.

Also, this might really be a duplicate of #4029, as mimugmail mentions.

**Comment by AdSchellevis** [comment]
Let’s try to reason if this is only a bug (wrong net calculated) or there is a missing feature as well.

> Besides, with IPv6 you would want to be able to decide if you want to use a /127, a /126 or a /64 as link network.

Which use case would require to reach other addresses then the predefined tunnel endpoint? ( hence requiring a larger net than minimum)

not saying there is an easy fix for the calculation, but if there is a fix, it might be cleaner given the existing situation.

**Comment by bimbar** [comment]
> Let’s try to reason if this is only a bug (wrong net calculated) or there is a missing feature as well.
> 
> > Besides, with IPv6 you would want to be able to decide if you want to use a /127, a /126 or a /64 as link network.
> 
> Which use case would require to reach other addresses then the predefined tunnel endpoint? ( hence requiring a larger net than minimum)
> 
> not saying there is an easy fix for the calculation, but if there is a fix, it might be cleaner given the existing situation.

In IPv4 I would want to specify whether it should be a /31 or a /30, since both are perfectly valid.
Similar thing about /126 and /127. Additionally with /64 all the IPv6 mechanisms for SLAAC and link-local addresses could be used.

**Comment by AdSchellevis** [comment]
Don’t get me wrong, but I haven’t heard a reason why different options should be possible if the calculation is correct (which currently isn’t the case). If there are valid use cases where not only both ends of the tunnel should be accessible, that would be good to know, when trying to come up with a fix.

working around the problem by changing the scenery usually has downsides for others.

When this turns out to be only a bug, we should try to fix it first, unless there are other scenarios which we have overseen and simply won’t ever work when fixing the bug.

**Comment by bimbar** [comment]
Routed ipsec tunnels are often used to connect to clouds, where it may not be possible to configure the netmask freely, and the client side has to comply.
Does the current interface even tell me which mask it has calculated? If not, how would I know how to configure the other side?
Also there is the possibility that the other side also chooses netmasks automatically - what if it chooses a different one?

I think automatic calculation of the netmask is just a bad idea.

**Comment by AdSchellevis** [comment]
If I’m not mistaken the interfaces overview should represent the configured settings. 

As long as both ends are “within visible range” mask likely doesn’t matter, although you can easily test that if you have doubts.

Claiming the current input type is a bad choice likely doesn’t help identifying the issue at hand.  To be honest, I’m not sure I agree either in this case that adding a mask would be more clear for everybody (and given our current situation, it will likely lead to confusion by others)

So, the question remains, are there actual situations where the minimal calculated subnet doesn’t work (when properly calculated)

**Comment by bimbar** [comment]
I thought that the netmask and network has to be the same one on both sides for the tunnel to work.

**Comment by bimbar** [comment]
Well, it does work, at least between opnsense and vyos:

`ipsec1: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> metric 0 mtu 1400
	tunnel inet 10.0.5.1 --> 10.0.5.254
	inet6 fe80::20d:b9ff:fe4e:dc84%ipsec1 prefixlen 64 scopeid 0x10
	inet 192.168.1.2 --> 192.168.1.1 netmask 0xfffffffc
	groups: ipsec
	reqid: 1
	nd6 options=23<PERFORMNUD,ACCEPT_RTADV,AUTO_LINKLOCAL>`

`vti1: flags=209<UP,POINTOPOINT,RUNNING,NOARP>  mtu 1500
        inet 192.168.1.1  netmask 255.255.255.255  destination 192.168.1.1
        tunnel   txqueuelen 1000  (IPIP Tunnel)
        RX packets 8  bytes 672 (672.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 8  bytes 672 (672.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0`

**Comment by fichtner** [comment]
How about 9e44d9a1a ?

    # opnsense-patch 9e44d9a1a


Cheers,
Franco

**Comment by fichtner** [comment]
No feedback for 14 days on a patch that is hot for discussion seems strange to me. ;)

**Comment by mimugmail** [comment]
Like the crowd around someone injured, everyone thinks the other guy will help :)

**Comment by fichtner** [comment]
FWIW, I'm going to close this and target 22.1 for this change for lack of further feedback.
