### ISSUE TITLE
Migrate Python3.8

### ISSUE THREAD

**Issue by EmperorsLoungeVPN** [opnsense/core#5207]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

A clear and concise description of what the bug is, including last known working version (if any).

*Tip*: to validate your setup was working with the previous version, use opnsense-revert (https://docs.opnsense.org/manual/opnsense_tools.html#opnsense-revert)

**To Reproduce**

**Expected behavior**

**Describe alternatives you considered**

A clear and concise description of any alternative solutions or workaround you considered.

**Screenshots**

**Relevant log files**

If applicable, information from log files supporting your claim.

**Additional context**

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 19.1.1 (amd64, OpenSSL).
Intel® Xeon™ E3-1225V5 3.3Ghz Quad Core
Network Intel® I210-AT

**Comment by EmperorsLoungeVPN** [comment]
How do I migrate the python vulnerability. 

Reference

https://vuxml.freebsd.org/freebsd/145ce848-1165-11ec-ac7e-08002789875b.html

**Comment by fichtner** [comment]
21.7.3 will address this...

**Comment by EmperorsLoungeVPN** [comment]
Okay thanks.
