### ISSUE TITLE
LAGG hashing configurability improvements

### ISSUE THREAD

**Issue by alex-h7h** [opnsense/core#5208]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**

- The LAGG hashing layers are not configurable via the web interface. The default "l2,l3,l4" is therefore used. This setting is used to determine which LAGG interface each packet is sent from, based on src/dst information from the layer2/layer3/layer4 headers. In an ideal case, packets for a single connection should always exit via a single interface, and both sides of the LAGG should use the same hashing algorithm.
- The recently-added "use flowid" option should also be available for "loadbalance" type LAGGs, per the ifconfig documentation.

**Describe the solution you like**

- The layers for LAGG hashing should be configurable (choose any number of {l2, l3, l4}) for LACP and loadbalance-type LAGGs.
- The recently-added "use flowid" option should be also configurable for loadbalance-type LAGGs.

**Describe alternatives you considered**

Alternatives are to apply this manually on boot using custom scripts, or to accept the default options.

**Additional context**

Further discussion and background available here: https://github.com/opnsense/core/issues/5157#issuecomment-913900460

**Comment by AdSchellevis** [comment]
@alex-h7h can you try https://github.com/opnsense/core/commit/0e10b291b2f9b83485ec20963a900b758a935c69? Should do the same as your PR, found some edge cases (default handling) and simplifications
