### ISSUE TITLE
Upgrade to 21.7.2 bricked my system

### ISSUE THREAD

**Issue by brad0** [opnsense/core#5210]
**Describe the bug**

I upgraded to 21.7.2 from 21.7.1 and it left my system in a bricked state. The WAN interface is configured including a GIF tunnel and an OpenVPN tunnel but the VLAN interfaces were not configured. I see them as vlan3/4/5/6 instead of mce0_vlan3/4/5/6 as they should be and no IPv4 or IPv6 addresses nor the parent interface set.

*Tip*: to validate your setup was working with the previous version, use opnsense-revert (https://docs.opnsense.org/manual/opnsense_tools.html#opnsense-revert)

I try opnsense-revert as shown in the documentation and it just says "Package 'opnsense' is not installed.".

**To Reproduce**

Upgrade to 21.7.2.

**Expected behavior**

The system would come back up as it usually does with upgrades in the past.

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 21.7.2 (amd64, LibreSSL).
Intel Core i5-2400 3.1 GHz Quad Core
Mellanox ConnectX-4 adapter
Intel X550-T2 adapter

**Comment by fichtner** [comment]
I suppose you run the development version?

**Comment by brad0** [comment]
Yes. I did "opnsense-update -t opnsense" to switch back and everything is running again. Why did something as straightforward as VLANs and their respective settings break?

**Comment by fichtner** [comment]
I refactored a function, but it had a copy+paste error... this is the fix from yesterday https://github.com/opnsense/core/commit/ba505fb122

Make sure to change the release type from the GUI as well or it will bring you back to development on the next update again.

**Comment by fichtner** [comment]
FWIW, the opnsense-devel package of 21.7.2 has been replaced with a newer update that doesn't show this problem anymore.
