### ISSUE TITLE
ntpd shows stopped when active

### ISSUE THREAD

**Issue by haberdabers** [opnsense/core#5214]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

NTPD on the opnsense gui shows stopped and wont start saying something is all ready listening. When you check the status NTPD is running ok:

sockstat -4 -l | grep 123
root     ntpd       85389 21 udp4   *:123                 *:*
root     ntpd       85389 22 udp4   10.123.100.1:123      *:*
root     ntpd       85389 24 udp4   10.123.10.1:123       *:*
root     ntpd       85389 26 udp4   10.123.20.1:123       *:*
root     ntpd       85389 29 udp4   127.0.0.1:123         *:*

ps -awx -l | grep 85389
    0 85389     1   0  20   0   18800    6740 select   Ss    -      0:08.62 /usr/local/sbin/ntpd -g -c /var/etc/ntpd.conf -p /var/r

NTPD Log:

2021-09-15T10:38:17 | ntpd[94124] | daemon child exited with code 1 |  
-- | -- | -- | --
2021-09-15T10:38:17 | ntpd[37504] | unable to bind to wildcard address :: - another process may be running - EXITING |  
2021-09-15T10:38:17 | ntpd[37504] | restrict: 'monitor' cannot be disabled while 'limited' is enabled |  
2021-09-15T10:38:17 | ntpd[37504] | gps base set to 2021-07-25 (week 2168) |  
2021-09-15T10:38:17 | ntpd[37504] | basedate set to 2021-07-22 |  
2021-09-15T10:38:17 | ntpd[37504] | proto: precision = 2.584 usec (-18)

**To Reproduce**

Hard to reproduce seems random. Killing the process and restart the service corrects it.

**Environment**

OPNsense 21.7.2_1-amd64
FreeBSD 12.1-RELEASE-p20-HBSD
OpenSSL 1.1.1l 24 Aug 2021

**Comment by fichtner** [comment]
I think ntpd is running but clobbers its pid file. You can confirm with

    # pgrep ntpd
    # cat /var/run/ntpd.pid

It should show different PIDs...

If you don't need an NTP server you can also switch to client mode since 21.7.

As for the "bug" maybe we can remove reliance on the pid file, but I haven't been able to reproduce this yet.


Cheers,
Franco

**Comment by joeyboon** [comment]
I have the same problem, I confirmed the service runs even when the GUI states that it does not. Killing the ntpd process via CLI allows me to restart it via GUI and CLI.
