### ISSUE TITLE
Netflow No data avaiable flowd aggregate not running Cannot 'start' flowd_aggregate. Set flowd_aggregate_enable to YES in /etc/rc.conf or use 'onestart' instead of 'start'.

### ISSUE THREAD

**Issue by terxw** [opnsense/core#5218]
- [ x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [ x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Description**

I dont have any report in netflow Health (Reporting -> Health) or Insight (Reporting -> Insight)

```
No Data Avaiable
```
Neflow config:

https://imgur.com/a/JiZYZJ4

While troubleshooting, I became aware that service flodw aggregate is not running, which is responsible for data collection

service flowd_aggregate is not runnig and I cann not start it, if i try to run it from commandline:

`
service flowd_aggregate start
`

 I get:

`
Cannot 'start' flowd_aggregate. Set flowd_aggregate_enable to YES in /etc/rc.conf or use 'onestart' instead of 'start'.
`

If I try to edit rc.conf

`
vi /etc/rc.conf 
`

/etc/rc.conf  file is empty

If I try to edit /etc/rc.conf.d/flowd_aggregate

`
vi /etc/rc.conf.d/flowd_aggregate
`

```
#
# Automatic generated configuration for netflow.
# Do not edit this file manually.
#
flowd_enable="NO"
root@OPNsense:~ # cat /etc/rc.conf.d/flowd_aggregate
#
# Automatic generated configuration for netflow.
# Do not edit this file manually.
#
Flowd_aggregate_enable="YES"
```

the service is disabled and I can not edit it, because its changed during editing
also flowd:

```
cat /etc/rc.conf.d/flowd
```

```
#
# Automatic generated configuration for netflow.
# Do not edit this file manually.
#
flowd_enable="NO"

```

There are no errors in log files, eg:
```
clog /var/log/system.log | grep flowd
```
will output:

```
Sep 17 14:43:17 OPNsense /flowd_aggregate.py[79818]: startup, check database. 
Sep 17 14:43:17 OPNsense /flowd_aggregate.py[79818]: start watching flowd 
Sep 17 14:43:17 OPNsense /flowd_aggregate.py[79818]: vacuum done
.
.
.
.
.
Sep 17 14:52:23 OPNsense /flowd_aggregate.py[84598]: sqlite3 repair /var/netflow/metadata.sqlite 
Sep 17 14:52:23 OPNsense /flowd_aggregate.py[84598]: sqlite3 repair /var/netflow/metadata.sqlite [done] 
Sep 17 14:52:23 OPNsense /flowd_aggregate.py[84598]: sqlite3 repair /var/netflow/interface_000300.sqlite 
Sep 17 14:52:23 OPNsense /flowd_aggregate.py[84598]: sqlite3 repair /var/netflow/interface_000300.sqlite [done] 
Sep 17 14:52:23 OPNsense /flowd_aggregate.py[84598]: sqlite3 repair /var/netflow/interface_003600.sqlite 
Sep 17 14:52:23 OPNsense /flowd_aggregate.py[84598]: sqlite3 repair /var/netflow/interface_003600.sqlite [done] 
Sep 17 14:52:23 OPNsense /flowd_aggregate.py[84598]: sqlite3 repair /var/netflow/interface_086400.sqlite 
Sep 17 14:52:23 OPNsense /flowd_aggregate.py[84598]: sqlite3 repair /var/netflow/interface_086400.sqlite [done] 
Sep 17 14:52:23 OPNsense /flowd_aggregate.py[84598]: sqlite3 repair /var/netflow/dst_port_000300.sqlite 
Sep 17 14:52:23 OPNsense /flowd_aggregate.py[84598]: sqlite3 repair /var/netflow/dst_port_000300.sqlite [done] 
Sep 17 14:52:23 OPNsense /flowd_aggregate.py[84598]: sqlite3 repair /var/netflow/dst_port_086400.sqlite 
Sep 17 14:52:23 OPNsense /flowd_aggregate.py[84598]: sqlite3 repair /var/netflow/dst_port_086400.sqlite [done] 
Sep 17 14:52:23 OPNsense /flowd_aggregate.py[84598]: sqlite3 repair /var/netflow/src_addr_details_086400.sqlite 
Sep 17 14:52:23 OPNsense /flowd_aggregate.py[84598]: sqlite3 repair /var/netflow/src_addr_details_086400.sqlite [done] 
Sep 17 14:52:23 OPNsense /flowd_aggregate.py[84598]: sqlite3 repair /var/netflow/src_addr_000300.sqlite 
Sep 17 14:52:23 OPNsense /flowd_aggregate.py[84598]: sqlite3 repair /var/netflow/src_addr_000300.sqlite [done] 
Sep 17 14:52:23 OPNsense /flowd_aggregate.py[84598]: sqlite3 repair /var/netflow/src_addr_086400.sqlite 
Sep 17 14:52:23 OPNsense /flowd_aggregate.py[84598]: sqlite3 repair /var/netflow/src_addr_086400.sqlite [done] 

```

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 21.7.2_1-amd64
FreeBSD 12.1-RELEASE-p20-HBSD
OpenSSL 1.1.1 24 Aug 2021

**Comment by AdSchellevis** [comment]
the "capture local" setting is responsible for toggling the rc config, which at a first glance is properly configured on your end. Can you try to apply the settings again and if that finishes without errors, go to the console and execute the following command to ask `configd` to refresh the netflow config:
```
configctl template reload OPNsense/Netflow
```

**Comment by terxw** [comment]
No change after reapplying setting and after running

```
configctl template reload OPNsense/Netflow
```
In the log no change

```
grep -r /var/log/ -e "flowd"

```

```
/var/log/configd.log:Sep 17 16:28:34 OPNsense configd.py[31328]:  OPNsense/Netflow generated //etc/rc.conf.d/flowd 
/var/log/configd.log:Sep 17 16:28:34 OPNsense configd.py[31328]:  OPNsense/Netflow generated //etc/rc.conf.d/flowd_aggregate 
/var/log/configd.log:Sep 17 16:28:34 OPNsense configd.py[31328]:  OPNsense/Netflow generated //usr/local/etc/flowd.conf 
/var/log/configd.log:Sep 17 16:29:44 OPNsense configd.py[31328]:  OPNsense/Netflow generated //etc/rc.conf.d/flowd 
/var/log/configd.log:Sep 17 16:29:44 OPNsense configd.py[31328]:  OPNsense/Netflow generated //etc/rc.conf.d/flowd_aggregate 
/var/log/configd.log:Sep 17 16:29:44 OPNsense configd.py[31328]:  OPNsense/Netflow generated //usr/local/etc/flowd.conf 
/var/log/configd.log:Sep 17 16:29:59 OPNsense configd.py[31328]:  OPNsense/Netflow generated //etc/rc.conf.d/flowd 
/var/log/configd.log:Sep 17 16:29:59 OPNsense configd.py[31328]:  OPNsense/Netflow generated //etc/rc.conf.d/flowd_aggregate 
/var/log/configd.log:Sep 17 16:29:59 OPNsense configd.py[31328]:  OPNsense/Netflow generated //usr/local/etc/flowd.conf 
```
there are some other older entries, which are maybe corelated?

Log here:
```
/var/log/userlog:2021-09-12 13:32:11 [unknown:groupadd] _flowd(542)
/var/log/userlog:2021-09-12 13:32:11 [unknown:useradd] _flowd(542):_flowd(542):flowd privilege separation user:/var/empty:/usr/sbin/nologin
/var/log/userlog:2021-09-12 13:39:13 [unknown:groupadd] _flowd(542)
/var/log/userlog:2021-09-12 13:39:13 [unknown:useradd] _flowd(542):_flowd(542):flowd privilege separation user:/var/empty:/usr/sbin/nologin
```

Another interesting thing is after resetting neflow data as suggested in earlier forum posts, the connection to opnsense is lost...

**Comment by AdSchellevis** [comment]
doesn't ring a bell here, resetting the netflow only removes the data and restarts the connected services (if I'm not mistaken it just runs this script https://github.com/opnsense/core/blob/master/src/opnsense/scripts/netflow/flush_all.sh), maybe netgraph(4) is less stable on some network drivers, but personally I never seen these types of issues. 

The template itself (reponsible for setting `flowd_aggregate_enable="YES"`) is quite simple and unlikely to fail, it just reads the `<collect><enable></enable></collect>` in the Netflow section and outputs the results. Did you import or edit the config.xml manually? if that's the case, that could be a reason for unexpected behaviour.

**Comment by terxw** [comment]
Thank you for suggestion!

Yes, I imported my config manualy (after troubleshooting dns problem)
And I had netflow section 3 times in row.

After exporting, deleting redundant sections and reimporting

```
      <collect>
        <enable>1</enable>
      </collect>

```

And it is working!
