### ISSUE TITLE
How do i translate the same action from this TPLINK router config to OPNsense

### ISSUE THREAD

**Issue by Francabicon** [opnsense/core#5222]
So I'm trying to connect to PPPOE but they had this config to do which i don't know how to translate to OPNsense
![image](https://user-images.githubusercontent.com/52349593/133879783-bf121e2f-401e-4a8d-b7a8-d9444444e316.png)

This is my current config
![image](https://user-images.githubusercontent.com/52349593/133879887-eb7b7230-5fc2-433f-8153-25e3c331be4e.png)

Please do help me I've tried for a month to solve this issue. I'm really noob at this.

**Comment by muchahagrande** [comment]
Hi @Francabicon, you can ask this in the forum to get help from the community: https://forum.opnsense.org/index.php?board=1.0
Here you can get support for bugs or ask for new features.
Cheers...

**Comment by Francabicon** [comment]
Hi @muchahagrande well that is what i did exactly but no one replied to it so yeah but i manage to get it work already by rebooting the router and the config that i shown in the picture is correct. Thanks Mate.
