### ISSUE TITLE
New Dashboard Widget "URL Table IP Summary" and show info about URL Table IPs

### ISSUE THREAD

**Issue by nzkiwi68** [opnsense/core#5223]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:
- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**
Sort of.
I use a number of URL Table IP aliases and fetch all sorts of thing, such as;
- DShield.org Most Active Attacking IPs	https://feeds.dshield.org/top10-2.txt
- www.blocklist.de	https://lists.blocklist.de/lists/all.txt
- DShield.org Recommended Block List	https://feeds.dshield.org/block.txt
- Spamhaus DROP BL	https://www.spamhaus.org/drop/drop.txt
- Spamhaus Extended DROP BL    https://www.spamhaus.org/drop/edrop.txt
- abuse SSLBL Botnet C2 IP Blacklist     https://sslbl.abuse.ch/blacklist/sslipblacklist.txt

I then use 2 floating rules, one to drop from source and one to drop to destination for protection.

_**The issue is, if anything breaks, if a list changes and no longer updates, or, worse it's empty, you just don't easily know.**_

It's a very manual manual process to go into
Firewall > Diagnostic > Aliases 
and then select each URL tables alias in turn to check if it has any IP addresses and then you still don't know when it was last updated.

**Describe the solution you like**

A Dashboard Widget that contained all of the URL Table IP aliases and showed their status
`Name,     Total IP addresses,     Refresh Frequency,     last updated (date & time)`

That way, you can easily at a glance see that the URL Table Aliases are functioning correctly (or not).

**Describe alternatives you considered**

There isn't one, only a very manual process.

**Comment by nzkiwi68** [comment]
I hate to mention pfBlocker, but, such a widget will go a long way to making the "URL Table IPs" more useful and more functional.

pfBlocker has a Dashboard widget and that's how you can see easily if it's working correctly.

**Comment by AdSchellevis** [comment]
Extending the `Firewall > Diagnostic > Aliases` view with some information to ease troubleshooting might be something to consider, most people use a lot of aliases which doesn't really present well in a widget. 

Some sort of log triggered notification might be practical at some point in time as well, but is more or less a generic feature, usually all relevant information is already in there.

**Comment by nzkiwi68** [comment]
I'm not suggesting the widget showed all aliases, but, specifically only "URL Table (IPs)".
I imagine you're right that others use lots of aliases, but lots of "URL Table (IPs)" aliases?
I do use "URL Table IPs" but only a few and certainly not lots.

Have a look at a working pfSense firewall with the pfBlockerNG dashboard widget. It is readily apparent that all the IP lists are downloaded because the "Count" is not zero and "Updated" column showing a date and time last updated.

I found recently on a product firewall by chance that one "URL Table (IPs)" was empty and also there's no easy way to know if it does contain IPs when it was last downloaded successfully.

pfBlocker Widget:
![pfBlocker](https://user-images.githubusercontent.com/67399588/133989455-219881d9-c484-44da-9eeb-d5f411cd58d3.PNG)
.

**Comment by AdSchellevis** [comment]
Just saying we don't consider adding a dashboard widget, if someone does want to work on such a feature, I don't mind that much, it could be a plugin as well.

Failures during updates should be in the log, when a list contains items, it doesn't guarantee a successful load, depends on how items are being flushed and what happens after download failures (often the previous state stays in the table).

**Comment by nzkiwi68** [comment]
>....when a list contains items, it doesn't guarantee a successful load, depends on how items are being flushed and what happens after download failures....

And that is essentially what such a widget does. It shows in a simple format that the IP address lists are not empty and have been updated. This gives you the confidence that your **URL Table (IPs)** aliases are working correctly.

It may well be logged, but it's just totally impractical to troll through the log to ensure your URL table IPs are up to date.

It's that widget that makes pfBlocker so darn useful, in a single glance I can tell if all is well or not.

Perhaps someone who writes code will pick this idea up. Maybe...

**Comment by AdSchellevis** [comment]
> Perhaps someone who writes code will pick this idea up. Maybe...

you never know, but improving the current diagnostics view might be a good idea as well.

**Comment by nzkiwi68** [comment]
I'm no programmer, but if you're going to go to effort of writing code that pulls URL Tables (IPs) into a list and displays them as;
`Name, Total IP addresses, Refresh Frequency, last updated (date & time)`

How much extra effort is that to make that view available as widget?

**Comment by AdSchellevis** [comment]
I was think maybe we could add the number of entries and last updated in the current dropdown to keep the current overview consistent, otherwise the whole page should be refactored (or extended with some sort of "overview" tab).

**Comment by nzkiwi68** [comment]
Yes, sounds good, certainly an improvement.

Still, terribly manual to need to specifically drill down to diagnostics to see if the URL Table IPs are working. Maybe later on someone can pickup that code and make it into a widget...

**Comment by kulikov-a** [comment]
as an immediate help, can suggest adding the `pfctl -vvsTables` output to the pfInfo page (just a little code to the page and pfinfo.py script). this allows to take a look at the tables on the subject of health and stats.
small problem: the output only displays the time the table was last cleared, and the tables are not flushed before reloading.
but I have a feeling that @AdSchellevis  has already started adding this info to another script )

**Comment by AdSchellevis** [comment]
@kulikov-a I was indeed thinking about this a bit, the most logical place seems to be the current alias grid, this is heading into the master branch 
![image](https://user-images.githubusercontent.com/9783985/134216986-999dd466-dcba-41f4-bfbf-14dffeb3bd13.png)

**Comment by kulikov-a** [comment]
@AdSchellevis an ideal place imho

**Comment by nzkiwi68** [comment]
Thanks btw for picking up this idea....
