### ISSUE TITLE
TLS-crypt broken (?)

### ISSUE THREAD

**Issue by trendchiller** [opnsense/core#5232]
When I create a new (or edit an existing) OpenVPN-Server with TLS-Crypt it does NOT work, because only TLS-auth is written to the corresponding config file (under /var/etc/openvpn)

written:
tls-auth /var/etc/openvpn/server3.tls-auth 0

should be:
tls-crypt /var/etc/openvpn/server3.tls-auth

I'm using OPNsense 21.7.3-amd64

**Comment by fichtner** [comment]
https://github.com/opnsense/core/pull/4592#issuecomment-925525114
