### ISSUE TITLE
Port Forward creation page doesn’t retain filter-rule-association when input validation fails

### ISSUE THREAD

**Issue by delan** [opnsense/core#5234]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

* OPNsense 21.7.2_1-amd64 is affected
* not sure about last known good version (new to opnsense)
* URL affected: /firewall_nat_edit.php

When creating a port forward, if the input validation fails, the **Filter rule association** (filter-rule-association) is always reset to **None**, regardless of your original choice. All other dropdowns I can find on that page seem to work correctly.

**To Reproduce**

1. Go to **Firewall** > **NAT** > **Port Forward**
2. Click **+** (Add)
3. See that **Firewall rule association** is **Add associated filter rule** (add-associated)
4. Optionally set **Firewall rule association** to any value other than **None**
3. Click **Save**
4. See that **Firewall rule association** is **None**

**Additional context**

I’m not really familiar with the project, but completely guessing, possible causes:

* there could be a bug in one of the selected="selected" conditions in the \<option>s
* all other \<select>s on that page have class="selectpicker", so they use a slightly different dropdown widget

See also #5019, which changed the default value of this field.

**Comment by AdSchellevis** [comment]
@delan can you try https://github.com/opnsense/core/commit/eb85feceb817808ccafffc44965e68c171744b74 ? This old code is still mind boggling from time to time, different names are used for new and existing entries which easily leads to confusions (filter-rule-association vs associated-rule-id). 

The following command should patch the latest OPNsense version:
```
opnsense-patch eb85fec
```

**Comment by delan** [comment]
Thanks for the quick fix @AdSchellevis! The patch works well, both when creating and cloning.

**Comment by AdSchellevis** [comment]
@delan thanks for reporting back!
