### ISSUE TITLE
plugin: unbound SRV records overrides

### ISSUE THREAD

**Issue by mnaiman** [opnsense/core#5237]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [ x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [ x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**

With removal of custom options it would be great to support SRV records (and maybe more DNS record types) in overrides.

**Describe the solution you like**

So far following config in custom options worked.
server:
local-data: "_service._tcp.domain. 3600 IN SRV 0 100 88 host.domain."

**Describe alternatives you considered**

To get rid of custom settings

**Additional context**

N/A

**Comment by toxic0berliner** [comment]
I'm also very interested by this one !
I was using it for my apt-proxy to be discovered easily : 
`local-data: "_apt_proxy._tcp. 180 IN SRV 10 0 3142 my-apt-proxy-server.lan."`
I've seen advice that I should use a "real" DNS server for that, but thet feels like a lot of work for only one line that is possible with unbound and just not with the gui...

I'll try to have a look if I can make a PR but I'm really new at dev on opnSense
