### ISSUE TITLE
Routing Problem when using two pppoe Connections from the same Internetprovider with the same PPP link target

### ISSUE THREAD

**Issue by zingelmann** [opnsense/core#5238]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [ ] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [ ] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

Routing Problem when using two pppoe Connections from the same Internetprovider with the same PPP link target

A clear and concise description of what the bug is, including last known working version (if any).

Actually running OPNSense 21.7.3_1 on the system. Two VDSL modems are connected to two network ports on the system. Each pppoe client is using its own network interface.

The internet provider uses two upstream gateways for the connections to terminate.  Sometimes it happens that both pppoe connections are linked to the same link target. 

e.g. 
pppoe0: flags=88d1<UP,POINTOPOINT,RUNNING,NOARP,SIMPLEX,MULTICAST> metric 0 mtu 1492
        inet6 fe80::290:bff:fe99:87ce%pppoe0 prefixlen 64 scopeid 0x19
        inet xxx.xxx.95.41 --> 213.157.2.17 netmask 0xffffffff
        nd6 options=21<PERFORMNUD,AUTO_LINKLOCAL>

pppoe1: flags=88d1<UP,POINTOPOINT,RUNNING,NOARP,SIMPLEX,MULTICAST> metric 0 mtu 1492
        inet xxx.xxx.95.30 --> 213.157.2.17 netmask 0xffffffff
        inet6 fe80::290:bff:fe99:87ce%pppoe1 prefixlen 64 scopeid 0x1a
        nd6 options=23<PERFORMNUD,ACCEPT_RTADV,AUTO_LINKLOCAL>

![image](https://user-images.githubusercontent.com/74189886/134904893-8d1abaec-a912-4530-bdcc-e7501818a800.png)

I created a gateway for each connection and added an extra monitoring ip, because the default, the ppp link target is the same in this case. But I get 

Routing tables
Internet:
Destination        Gateway            Flags     Netif Expire
default            213.157.2.17       UGS      pppoe0
1.0.0.1            213.157.2.17       UGHS     pppoe0
1.1.1.1            213.157.2.17       UGHS     pppoe0

the gateway monitoring daemon didn't mention the outgoing interface when creating a routing entry, I suppose. 

When the routes are added manually, I get the same result even if the gateway is selected correctly

![image](https://user-images.githubusercontent.com/74189886/134905052-c5b5b000-e939-44b9-b4bc-6a66428c06b7.png)

Routing tables

Internet:
Destination        Gateway            Flags     Netif Expire
default            213.157.2.17       UGS      pppoe0
1.0.0.1/32         213.157.2.17       UGS      pppoe0
1.1.1.1/32         213.157.2.17       UGS      pppoe0

so in this case, there won't be any connection possible over pppoe1 from the system itself. When I try to point any other traffic from a connected subnet to be sent over the second gateway, no connection is possible.

Set manually I can create a correct result by using the interface names:

route add 1.0.0.1 -iface pppoe1
 route add 1.1.1.1 -iface pppoe0

Internet:
Destination        Gateway            Flags     Netif Expire
default            213.157.2.17       UGS      pppoe0
1.0.0.1            pppoe1             UHS      pppoe1
1.1.1.1            pppoe0             UHS      pppoe0

Is there anything possible to solve this issue? I have to reconnect the interfaces till two different link targets are configured by my ISP.

*Tip*: to validate your setup was working with the previous version, use opnsense-revert (https://docs.opnsense.org/manual/opnsense_tools.html#opnsense-revert)

**To Reproduce**

**Expected behavior**

**Describe alternatives you considered**

A clear and concise description of any alternative solutions or workaround you considered.

**Screenshots**

**Relevant log files**

If applicable, information from log files supporting your claim.

**Additional context**

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 19.1.1 (amd64, OpenSSL).
Intel® Xeon™ E3-1225V5 3.3Ghz Quad Core
Network Intel® I210-AT

**Comment by fichtner** [comment]
Sorry, same gateway IP for two connections is not supported by FreeBSD.


Cheers,
Franco

**Comment by zingelmann** [comment]
Hi Franco, 

thanks for your reply - so in this case only the ISP can change something by providing different gateways for the two connections, right? Strange behaviour - I'm shure I'm not the only user with two internet connections from the same provider - shure that the problem exisits too for other user. Perhaps someone had experience with this?

Thanks in advance
Vivian

**Comment by fichtner** [comment]
Hi Vivian,

It should suffice when the ISP can assign an alias to the same gateway for you to use that second IP address in the second gateway setting. Gateway routes are host routes (/32) so you can have only one in the routing table.

As far as I understand this has been a general FreeBSD problematic for a long time. It might be solvable with separate routing tables, but we don't support this in OPNsense.


Cheers,
Franco
