### ISSUE TITLE
OpenVPN client export: support OpenVPN Connect client

### ISSUE THREAD

**Issue by neonknight** [opnsense/core#5245]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**

OpenVPN client export already supports a variety of different OpenVPN clients (e.g. Viscosity) with distinct configuration packages. OpenVPN Connect seems to be a new client which requires yet another format of exported configuration. As this client seems to be the official client by [openvpn.net Website](https://openvpn.net/vpn-client/) it may gain much more popularity in future, thus support for its configuration format would be beneficial to both opnsense Administrators and OpenVPN Connect users.

**Describe the solution you like**

Add another option to the dropdown in "Export type". The format required by OpenVPN Connect is nothing entirely new. The export generated needs the same .p12 file as included in the "Archive" option in combination with the configuration file as generated by the "File Only" option.

**Describe alternatives you considered**

Currently the only alternative is to first download the "Archive" format, then the "File Only" format and manually recombine the two to a new archive. This is not very admin friendly as you first need to find out that this would be a working solution.

**Additional context**

n/a

**Comment by AdSchellevis** [comment]
The file option is intended for the standard OpenVPN client (which is more or less the same as the command line version if I'm not mistaken) and ships the certificate in the `<cert>` section in standard pem format, which usually works out of the box.

**Comment by neonknight** [comment]
"OpenVPN Connect client" is NOT command line openvpn. It's a GUI client for Windows and other OS. Please click the link in my ticket for more information.

**Comment by AdSchellevis** [comment]
yes, which underneath uses the same client if I'm not mistaken and accepts an ovpn profile (which is our plain file format). It's not that I don't know their client, I've used it before on other platforms where Viscosity isn't supported....

**Comment by neonknight** [comment]
If the VPN server requires user certificates then the p12 certificate store from the archive and the plain text file are both needed. The plain file alone is not enough. We trialed&errored a while to find out how to configure that client correctly.

**Comment by AdSchellevis** [comment]
Maybe there's something else specific in your use case, but the file version should contain the same certificate information (only can't carry a password as that's part of the p12 format).

https://github.com/opnsense/core/blob/58186f8c4ed345d0f7a830045b84355ea2247984/src/opnsense/mvc/app/library/OPNsense/OpenVPN/ArchiveOpenVPN.php#L80-L88

https://github.com/opnsense/core/blob/58186f8c4ed345d0f7a830045b84355ea2247984/src/opnsense/mvc/app/library/OPNsense/OpenVPN/PlainOpenVPN.php#L182-L190

What sort of issues are you facing when using the plain file directly (without wrapping it into a new archive, which shouldn't be needed)?
