### ISSUE TITLE
Cannot configure OpenVPN site to site tunnel network with mask /31 or /30

### ISSUE THREAD

**Issue by zapotah** [opnsense/core#5248]
Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

Configuring a new site-to-site tunnel with a tunnel network of mask /30 or /31 fails

**To Reproduce**

1. Configure New OpenVPN server/client type of site to site
2. Configure normal parameters
3. Set tunnel network to be of /30 or /31 (or /127 or /126)
4. Configurator complains minimum netmask needs to be /29

**Expected behavior**

OpenVPN allows you to configure a proper ptp network on the tun interface

**Describe alternatives you considered**

Configuring any prefix larger is nonsense on ptp links.

**Additional Context**

If fixing this is supposed to be a part of #3146 then it should be expedited. This is a blocker for migrating and deployments are on hold again until fixed.

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 21.7.3 (amd64, OpenSSL).
Virtualized with host-cpu passthrough on zen 2 epyc
Virtio-net

**Comment by AdSchellevis** [comment]
duplicate https://github.com/opnsense/core/issues/5212 ?

**Comment by zapotah** [comment]
I even tried searching through closed issues.... the patch does indeed allow /30 to be configured.

**Comment by AdSchellevis** [comment]
@zapotah things happen, glad it fixes your issue.
