### ISSUE TITLE
OpenVPN Space In IPv4 Remote Network

### ISSUE THREAD

**Issue by Unit764** [opnsense/core#5249]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

Version: OPNsense 21.7.3_1-amd64
OpenVPN client IPv4 Remote Network no longer accepts a space after the comma.
Example: "192.168.0.0/16, 192.144.1.0/24"
Previous version (21.7.1-amd64, openvpn 2.5.3) would accept and ignore the space, and place routes in System:Routes:Status page.
Routers that are upgraded retain the previous information with the space, but routes will not be place in the Ssytem:Routes:Status page.  This breaks previously working routes to the OpenVPN Server.

GUI error message:
--------------------------------------------------------
The following input errors were detected:

'192.168.0.0/16, 192.144.76.0/24' in 'IPv4 Remote Network' may only contain valid ipv4 CIDR range(s) separated by commas.
--------------------------------------------------------

Removing the space after the comma resolves the issue.
Example: "192.168.0.0/16,192.144.76.0/24"

**To Reproduce**

1. Go to VPN > OpenVPN > Clients
2. Click on Edit
3. Scroll down to IPv4 Remote Network
Enter a combination of IPv4 address with a space after the comma
--------------------------------------------------------
The following input errors were detected:

'192.168.0.0/16, 192.144.76.0/24' in 'IPv4 Remote Network' may only contain valid ipv4 CIDR range(s) separated by commas.
--------------------------------------------------------

**Expected behavior**
Past behavior would save with no error and space was ignored.
Either space should be removed during the upgrade, or should be ignored as per past behavior.

**Describe alternatives you considered**
Enter a combination of IPv4 address without a space after the comma.

**Screenshots**
NA

**Relevant log files**
NA

**Additional context**
NA

**Environment**
Software version used and hardware type if relevant, e.g.:
OPNsense 21.7.3_1-amd64
FreeBSD 12.1-RELEASE-p20-HBSD
OpenSSL 1.1.1l 24 Aug 2021
openvpn 2.5.3
Intel i5 7200U

**Comment by AdSchellevis** [comment]
The validation was recently changed in https://github.com/opnsense/core/commit/1b9e263195c82824f172038c7dd154863dfcdae0, not accepting spaces in the gui for these fields is a change made on purpose to prevent the need to trim values all over the place. Just remove the space and save again.

**Comment by Unit764** [comment]
Mabey I should rewrite this as upgrading a router can break VPN static routs, the error message does not properly describe the error, or both?  When the routers update in a multi user site, each user would need to be called and told how to reconfigure the router.  It would be nice if the update would take this into consideration and remove the spaces to prevent end user headaches.  Just a recommendation, thank you for a great product that has worked well for many years!

**Comment by fichtner** [comment]
@Unit764 We thought about the impact and this wasn't an easy choice. Actually we stumbled into these irregularities in the OpenVPN handling code while ironing out 2.5 migration issues post 21.7... OpenVPN isn't that consistent with its setups and documentation is softer than the daemon's configuration errors. So from our view to avoid future issues with improperly verified data in the config.xml and no way to migrate this data for the user (our MVC components can do this, but OpenVPN is a legacy part of the system) we would rather make this validation stricter in a minor update than a major update so that's what happened in 21.7.x gradually.


Cheers,
Franco

**Comment by hayer** [comment]
> The validation was recently changed in [1b9e263](https://github.com/opnsense/core/commit/1b9e263195c82824f172038c7dd154863dfcdae0), not accepting spaces in the gui for these fields is a change made on purpose to prevent the need to trim values all over the place. Just remove the space and save again.

Does that rather point to bad design on the backend part? Now the solution is to make it harder for the user?

**Comment by someone83474** [comment]
This change broke our vpn after the upgrade OPNsense 21.7.3_1-amd64. Since the error message only appears if you are changing the vpn config, it was not clear for us why the vpn broke. So, yes I think this should be mentioned somewhere in the upgrade informationen.

**Comment by Unit764** [comment]
Closing issue.  Enough time has passed that problem should not appear in current versions.
