### ISSUE TITLE
SUIRCATA: Won't load custom-rules.xml anymore since 21.7.3 upgrade

### ISSUE THREAD

**Issue by nzkiwi68** [opnsense/core#5252]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

You could put custom rules in 
`/usr/local/opnsense/scripts/suricata/metadata/rules/`

and these would be loaded and appear 
**Services > Intrusion Detection > Administration > Download**

**To Reproduce**

Place a suitable custom-rule.xml file in the correct directory, the new ruleset never gets loaded.

**Expected behavior**

The ruleset would get loaded and appear in **Services > Intrusion Detection > Administration > Download**

**Describe alternatives you considered**

Rollback is the only alternative

**Screenshots**

I can upload if required

**Additional context**

Probably the issue began with the first release of 21.7.3 but I never noticed my custom IPS rules were no longer getting loaded

**Environment**

OPNsense 21.7.3_3 (amd64, OpenSSL).
Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz (8 cores)
Network Intel® I210-AT

**Comment by AdSchellevis** [comment]
If the download tab contains rulesets, it's likely an issue with your definition. All standard (and plugin) rulesets are registered equally.

**Comment by nzkiwi68** [comment]
Oh no!

You're right, I updated the URL and forgot to escape the ampersand!

My fault, thanks.
