### ISSUE TITLE
Automatic user creation on LDAP does not read properties

### ISSUE THREAD

**Issue by mondbaron** [opnsense/core#5255]
**Important notices**

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

The feature "system: allow automatic user creation on LDAP-based logins" introduced in 21.7.3 does not respect the "Read properties" setting of the LDAP server configuration. It does not syncronize the properties such as Full Name and Email, while manual import on user page still does it correctly. Further an automatically created user is still listed in the list for manual import, but a manual re-import does not change anything. This leads to an inconsistent user database.

**To Reproduce**

- on System > Access > Servers: enable "Read properties" and "Automatic user creation"
- on System > Access > Users: delete if neccessary and import a new users from LDAP - should work fine
- on System > Access > Users: delete user again
- Login to trigger the auto creation
- on System > Access > Users: the automatically created user does not have any of the LDAP properties
- on System > Access > Users: manual re-import of this users seems to be possible, but does not change anything

**Expected behavior**

An automatically created user should be imported in accordance with the manual user import.

**Describe alternatives you considered**

N/A

**Screenshots**

N/A

**Relevant log files**

N/A

**Additional context**

N/A

**Environment**

OPNsense 21.7.3_3-amd64
FreeBSD 12.1-RELEASE-p20-HBSD
OpenSSL 1.1.1l 24 Aug 2021

**Comment by AdSchellevis** [comment]
I don't think we should try to mimic the same behaviour for additional properties as upstream information can change at any time without being noticed and the returned user properties don't seem to return the same information in all cases as an explicit search query does. 

The intend of the automated import is only to make sure there's an anchor in which authorisation can function for users managed elsewhere (when needing information about the user, such as his/her email address, best check the original provider).
