### ISSUE TITLE
[Bug] dynamic lease host name overwrite from static leases page no longer works

### ISSUE THREAD

**Issue by Northguy** [opnsense/core#5264]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Installed version**
OPNsense 21.7.3_3-amd64
FreeBSD 12.1-RELEASE-p20-HBSD
OpenSSL 1.1.1l 24 Aug 2021

**Describe the bug**

Some devices are not identifiable in the dhcp leases table as they do not report a hostname. By creating a "static" lease by entering a host name/description for those devices on the 'static leases' page, while NOT entering a static IP address, it used to be possible to make such dynamic leases recognizable in the leases page. 

This functionality was implemented with #839ec35 in 19.7 as a result of bug report #2946 . It seems functionality is broken with latest release.

**To Reproduce**

1) Identify a dynamic lease without hostname and description on leases page:
![image](https://user-images.githubusercontent.com/1189058/136623668-606a152c-964f-4092-89d5-32dccd325082.png)

2) Create static map for mentioned lease, fill in host name and description but omit an IP, as indicated by help (see yellow marked). Save the mapping
![image](https://user-images.githubusercontent.com/1189058/136624250-9d6a39c1-1f52-40b2-bdb6-1852e10407ac.png)

3) Go back to leases page, find host by IP/MAC -> Hostname and description not updated.

**Expected behavior**

Dynamic lease updated with host name and description as entered on the static leases page. 

![image](https://user-images.githubusercontent.com/1189058/136624664-1927ae70-c410-4544-a430-d8351847ad34.png)

**Comment by AdSchellevis** [comment]
@Northguy can you try https://github.com/opnsense/core/commit/8547872c4b4928668c79ea1561e864d427f640c7 ?
 ```
opnsense-patch 8547872
```
