### ISSUE TITLE
Help pages for MVC apps always leads to help.php?page=firewall_virtual_ip.php

### ISSUE THREAD

**Issue by 8191** [opnsense/core#527]
The help link at the top right of the OPNsense web GUI always leads to `/help.php?page=firewall_virtual_ip.php` if the currently shown page is a MVC app.

**Comment by fichtner** [comment]
I remember this, @AdSchellevis wanted to remove it or link to the wiki home page instead.

**Comment by AdSchellevis** [comment]
yes, because there's no wiki content for it :)
May I trash it this time?

**Comment by fichtner** [comment]
Fine by me.
