### ISSUE TITLE
Feature Request: New Access Server - "LDAP + Radius"

### ISSUE THREAD

**Issue by nzkiwi68** [opnsense/core#5283]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:
- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**
Today, Access Server types are;

- LDAP
- LDAP + TOTP
- Local + TOTP
- Radius
- Voucher
 
I have a need to use LDAP and Radius. We already have several customers who already have have a token/MFA solution. Most (and certainly the ones I use) can test the existing tokens via a PAP Radius query. It would be very awesome to have a new Access Server type;
- LDAP + Radius

**Describe the solution you like**
Create a new Access Server type, "LDAP + Radius". It would function similar to the existing "LDAP + TOTP" and strip the specified token length from the start or end of the  entered password and send the entered "username" plus token as Radius PAP query to the specified Radius server.

In this way, the customer gets awesome multi factor authentication leveraging their existing LDAP and existing Token source.

There are so many possibilities with "LDAP + Radius".

**Describe alternatives you considered**
The existing "LDAP + TOTP" is excellent, but, it requires a new token. For larger organizations that already have a token provisioning system, they could reuse their existing token solution and avoid "token hell" where users end up with multiple tokens for various logon systems.

**Additional context**
I'm no programmer, but, hopefully this isn't too big a job. The "Radius" Access Server type exists, the "LDAP" Access Server type exists and the concept of tokens with "LDAP + TOTP" exists.

Hopefully the existing Radius definition is PAP as the Token Radius systems I have seen only use PAP, no huge need for lots of security since it's a TOTP password anyway and plus the shared secret.

**Comment by mimugmail** [comment]
Usually the Radius service offering MFA should have an LDAP connector to strip the password, like privacyIDEA
