### ISSUE TITLE
Feature request: RFC 3576 / DM / CoA support

### ISSUE THREAD

**Issue by yankaiqian** [opnsense/core#529]
Can you help to add the "Dynamic Authorization Extensions" support in the captive portal?

It will allow Radius server send DM/CoA message to "OPNsense" and change a user session.

    Disconnect Messages (DM)
    Change-of-Authorization Messages (CoA)

**Comment by AdSchellevis** [comment]
We have limited time available, but if you send in code we will certainly try to look at it and give feedback. Please use the new captive portal system from development when extending authentication support (it uses the new pluggable auth system).

**Comment by AdSchellevis** [comment]
timeout.
