### ISSUE TITLE
Unbound blocklist only for defined subnets or interfaces

### ISSUE THREAD

**Issue by mayerthomas** [opnsense/core#5293]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [ X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [ X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**

Would it be possible, to configure unbound in a way, that the blocklist only takes action to defined subnets or interfaces?
Therefore for other subnets/interfaces the blocklist should not be enabled.

**Describe the solution you like**

_Example_
- Interface/Subnet "guests" with enabled blocklist (e. g. ads, facebook, ...)
- Interface/Subnet "office" with blocklist disabled

**Describe alternatives you considered**
none

**Additional context**
none

**Comment by AdSchellevis** [comment]
It's probably easier to use dnsmasq (or bind) for the unfiltered interface(s) and unbound for the rest, I don't expect you can easily exclude interfaces from the `local-data` registrations as we use them without adding a lot of unwanted complexity for others.
