### ISSUE TITLE
LDAP: Add function to import LDAP group instead of single users

### ISSUE THREAD

**Issue by pbosgraaf** [opnsense/core#5294]
[x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
[x] I am convinced that my issue is new after having checked both open and closed issues at 

Currently when you configure LDAP as an authentication source you are able to import indivdual LDAP users and assign then to a group.

I would like to request a feature that allows you to import and LDAP group and assign permissions on this group.
This would make user management much easier because often roles are defined as group in the corporate AD, which opnsense would then follow.

**Describe alternatives you considered**

Currently CRUD-ing users manually to the opnsense fw.
We are evaluating the possibility of an external script that lists LDAP group memberships and CRUDs against the opsense API.

**Comment by AdSchellevis** [comment]
We offer `Synchronize groups` and  `automatic user creation`  as a replacement for manual imports, see https://docs.opnsense.org/manual/how-tos/user-ldap.html#step-1-1-optional-synchronize-groups and https://docs.opnsense.org/manual/how-tos/user-ldap.html#step-4-import-users for more info.
