### ISSUE TITLE
Bug: DHCP MACs bleed into other DHCP VLAN configurations, rendering "deny unknown clients" not to work properly

### ISSUE THREAD

**Issue by module0x90** [opnsense/core#5298]
**Describe the bug**

It is a bit tricky to describe what I figured out. So let's take baby steps...
I am using DHCPv4 only.

Prerequisites
2 VLANs setup with DHCP
The first VLAN ("VLAN1") is set to "deny unknown clients". It has a DHCP range configured though.
The other ("VLAN2") is just pure DHCP, "deny unknown clients" is not ticked. The available range is the whole network.
You have hosts setup in VLAN2(!) with their MAC and a static IP address (within the assigned range).
It is important to note, that those hosts are not connected to VLAN1 network or configured on DHCP on VLAN1  in any sort of form.

**To Reproduce**

You take one of the hosts from VLAN2 and hook them up to a port in VLAN1, the device is configured to use DHCP.
That host gets an IP from the DHCP range from VLAN1.

**Expected behavior**

Considering that VLAN1 has "deny unknown clients" I expect that the DHCP server is refusing to serve these clients, same what you get when connecting any new device not having assigned a DHCP static yet.
Yes, you could argue that it behaves as expected, as I have configured a DHCP range. But in this instance it grants technically network access to this client (I am aware DHCP is not  a security feature).
Also, the tooltip on "deny unknown clients" states: If this is checked, only the clients defined below will get DHCP leases from this server.

**Describe alternatives you considered**

It appears "deny unknown clients" is ignored when the host's MAC is listed in other DHCP VLAN configs. This is not
expected behaviour. DHCP MACs somewhat "bleed" into other DHCP VLAN configurations.

**Environment**

OPNsense 21.7.3_3
Intel(R) Atom(TM) CPU D425 @ 1.80GHz (2 cores)

**Comment by module0x90** [comment]
I really don't know what's missing here.
I will leave it at that. There is nothing to add from my side.

**Comment by Crapshit** [comment]
Today morning I found out that I have the same exact situation on OPNsense 22.1.6.
I have two VLAN's and both have the option "deny unknown clients" ticked.
My client A is registered with a static DHCPv4 lease in VLAN 1.
I connected it by mistake to VLAN 2 and I immediately got an ipv4 address from within the DCHP range of VLAN.
I would also expect that I will not get any up address for client A in VLAN 2.
Only in VLAN 1 where I have the static lease.

Could you please check this issue here, because it's pending long?

Thank you very much :)

BR
Crapi

**Comment by AdSchellevis** [comment]
Isn't really fixable within the current implementation scope "unknown-clients" is a global operator (https://kb.isc.org/docs/isc-dhcp-41-manual-pages-dhcpdconf).  A documentation / help label update is likely the best we can do. Just open a pull-request with suggestions.

**Comment by Crapshit** [comment]
@AdSchellevis to change that scope is not possible? If this is more a feature as an issue, I would create a feature request, but after reading your message I'm not sure if this would ever be developed?
I'm not a developer who can help, I could only describe my feature wish and do some donations 😊.
Btw I love OPNsense... Coming from AVM only hardware as a consumer with no deep network knowledge 😅

**Comment by AdSchellevis** [comment]
@Crapshit without an easy option in `isc-dhcpd` it's not likely we will spend time on such a feature given the low demand and huge costs involved. Most implementation examples I've seen so-far use a single `dhcpd` for multiple interfaces (same as on our end), in which case you're pretty much bound to the options upstream (isc-dhcp) provides.

**Comment by module0x90** [comment]
Considering it is global, as you said, what if it is only a "global option" then within OPNsense?
Right now it is an option for each DHCP scope/network and that at least made me assume it is local and configurable to each scope.
