### ISSUE TITLE
DHCPv4 Server: release IPs addresses for networks/subnets not directly connected to an interface

### ISSUE THREAD

**Issue by xeucs** [opnsense/core#5299]
Hi,

I am writing here to pull the following request about DHCPv4 Server.
We have many instance of virtualized OPNsense in our Datacenter and the most important feature that this wonderful Firewall miss is the ability to release, via its DHCPv4 Server, IPs addresses that are not in the subnet of the interface where OPNsense receives the DHCPv4 requests. For instance if we have 2 or more branch offices in which are present only cisco routers (one per office) and one of the host in that office make a DHCPv4 request, the cisco router forwards this request via dhcp relay to our OPNsense. The problem is that OPNsense is not able to process this request because it receives this request on an interface that is not directly connected (layer 2) to the host that needs to receive a specific ip address.

Thank you

**Comment by mimugmail** [comment]
Look at Freeradius Plugin as I wrote in Forums
