### ISSUE TITLE
Dummynet not working

### ISSUE THREAD

**Issue by AdSchellevis** [opnsense/core#53]
after kernel fix, re-enable dummynet in :
src/etc/inc/shaper.inc
src/etc/inc/captiveportal.inc

**Comment by fichtner** [comment]
@AdSchellevis Doesn't look relevant anymore? :)

**Comment by AdSchellevis** [comment]
I think your right, lets close it for now.

**Comment by fichtner** [comment]
Closing stuff is fun :D
