### ISSUE TITLE
Unable to use commas in advanced DHCP client options

### ISSUE THREAD

**Issue by svdlinden** [opnsense/core#530]
When using 
```
dhcp-class-identifier "10008,100,,"
```
as send options in the advanced DHCP configuration, the actual value used by dhclient is something like
```
100008;\tsend 100;\t send ;\t send
```
which is completely bogus.

This happens because the field value is split at commas and commas between double quotes are not ignored as they should be (see https://github.com/opnsense/core/blob/master/src/etc/inc/interfaces.inc#L3833)

Instead of using
```
$options = split(",", $wancfg['adv_dhcp_send_options']);
```
a regex could be used:
```
$options = preg_split('/\s*,\s*(?=(?:[^"]*"[^"]*")*[^"]*$)/', $wancfg['adv_dhcp_send_options']);
```
This splits the string at commas (with any number of spaces before or after) provided that the quotes in the rest of the string are balanced (which would indicate that the comma is not in a quoted value). The trim also becomes superfluous.

Also applies to
 - adv_dhcp_option_modifiers
 - adv_dhcp6_interface_statement_send_options
 - adv_dhcp6_interface_statement_request_options

I'll make a patch if I find the time.

**Comment by AdSchellevis** [comment]
@svdlinden thanks for the feedback, I have replaced the split with your regex. Can you validate commit https://github.com/opnsense/core/commit/dbaf457bf149bdff1e7a14abeefd36f238d8af2c ?

Thanks in advance.

**Comment by svdlinden** [comment]
LGTM. You can also remove the trim() call two lines below. 

Thanks!
