### ISSUE TITLE
Feature Request: "Remote" Groups

### ISSUE THREAD

**Issue by kaysond** [opnsense/core#5303]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**

Right now, functionality of Groups is somewhat hampered by the fact that they are tied to local system groups. This means group names have length limits and can't accommodate all characters used in LDAP groups (esp. spaces).

Additionally, it requires synchronizing groups and importing users to the local database in order to grant GUI access. This requires some level of manual intervention that is generally not desired when using a centralized user database like LDAP.

This seems to have come up a lot recently: #5295 #5116 #4660 #4963

My proposed solution would address all of these

**Describe the solution you like**

"Remote Groups" would be a new type of group that can be used for anything not related to OS-level groups, such as GUI privileges, and can bypass naming restrictions.

pfSense implements this and I think their description is useful:

> Groups from remote sources, such as authentication servers (RADIUS or LDAP). These groups are not exposed to the operating system, and thus are only available for use in the GUI and other similar uses not involving the operating system layer. This scope has relaxed name restrictions, for example, group names may be longer and may contain spaces.

[pfSense Docs - User Management](https://docs.netgate.com/pfsense/en/latest/usermanager/groups.html#group-settings)

**Describe alternatives you considered**

An alternative could be group aliases, as described [here](https://github.com/opnsense/core/issues/5295#issuecomment-948315582), but I think Remote Groups is better because it addresses other issues with group sync and user importing. 

**Additional context**

I posted a thread in the forums about my experience setting up LDAP, which was frustrating compared to the ease of the rest of OPNsense setup: https://forum.opnsense.org/index.php?topic=25234.0

For the use case of using LDAP and existing users/groups to grant GUI access, Remote Groups would make the process much easier and completely automatic.

Example implementation from pfSense interface:
![image](https://user-images.githubusercontent.com/1147328/138501687-1246b531-47de-4cd9-9da3-63290e443b35.png)

**Comment by cmprmsd** [comment]
When testing LDAP integration with OPNSense we also wondered how the deletion of group memberships on the domain is handled. Currently it seems that the user is not revoked from the group, when I remove the user from the domain group. 

Synchronization only adds people to the local group but does not revoke the access.

At least this feature should be implemented in order to make sure no access is left when e.g. the Active Directory team does remove people from e.g. a ProxyUser group.

**Comment by AdSchellevis** [comment]
@cmprmsd ldap group membership is enforced upon login when "Synchronize groups" is used (https://docs.opnsense.org/manual/how-tos/user-ldap.html#step-1-add-new-ldap-server).

**Comment by cmprmsd** [comment]
We use synchronize groups. But when the user is removed from the group the user is not removed from the local opnsense group. 

I only tested it with the "test user" functionality. 
Maybe that's a workflow issue with the test user menu? 

The user should be removed from the local group when the user is removed in active directory right?

**Comment by AdSchellevis** [comment]
when the user is successfully logged in, the groups will be synced first. cleaning up (removing) users automatically is only offered in the Business Edition (as mentioned in the docs)

**Comment by cmprmsd** [comment]
Oh yeah, there it is: 

> As of version business edition 21.10, the system will automatically query the ldap servers and remove unexisting users. (not available in the community version of OPNsense)


Sad. Didn't know there are features that are available only in a paid version. 😿 

Thanks for the clarification though!

**Comment by AdSchellevis** [comment]
You can also delete users manually on periodic bases, if there's no user in LDAP, it can't login anyway so usually there's no real rush... but on the other end, it's not that odd paying a few bucks for software your using every day ;)

**Comment by cmprmsd** [comment]
That is true. The pricing seems reasonable :)
Have a great new year 😊
