### ISSUE TITLE
Manage custom DHCPD configuration directly by web interface.

### ISSUE THREAD

**Issue by agostinimarco** [opnsense/core#5308]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**
All started after reading this issues https://github.com/opnsense/core/issues/5299 but probably exists more other examples.

We have many instance of virtualized OPNsense in our Datacenter and the most important feature that this wonderful Firewall miss is the ability to release, via its DHCPv4 Server, IPs addresses that are not in the subnet of the interface where OPNsense receives the DHCPv4 requests. For instance if we have 2 or more branch offices in which are present only cisco routers (one per office) and one of the host in that office make a DHCPv4 request, the cisco router forwards this request via dhcp relay to our OPNsense. The problem is that OPNsense is not able to process this request because it receives this request on an interface that is not directly connected (layer 2) to the host that needs to receive a specific ip address.

After some investigation I realized that isc-dhcp, used by OpnSense, is able to manage this kind of configuration but OpnSense web interface no.

**Describe the solution you like**
I made some modification to OPNSense source code to include some customized row to dhcdp.conf file used by isc-dhcp.
I created a new simple interface on OPNSense to add the "custom row" to an external file "dhcpd.conf.custom" and I applied to /usr/local/etc/inc/plugins.inc.d/dhcpd.inc some rows of code to add an include to dhcpd.conf that point to new file "dhcpd.conf.custom".
I think that this update will be usefull for all parameters that are presents on isc-dhcp but is not actually managed by OPNSense interface.

**Additional context**
On the attached file [dhcp_custom.zip](https://github.com/opnsense/core/files/7412951/dhcp_custom.zip) you will find:
- /usr/local/www/services_dhcp_custom.php that contain the web interface
- /usr/local/opnsense/mvc/app/models/OPNsense/Core/Menu/Menu.xml with the call to services_dhcp_custom.php
- /usr/local/opnsense/mvc/app/models/OPNsense/Core/ACL/ACL.xml with the call to services_dhcp_custom.php
- /usr/local/etc/inc/plugins.inc.d/dhcpd.inc an altered version to manage an automatic include of new dhcpd.conf.custom file to dhcp.conf file

**Comment by agh1467** [comment]
Considering that nested `ArrayField`s aren't possible at the moment using MVC, maybe the existing `/services_dhcp.php?if=lan&act=newpool` could be changed to support arbitrary pool definitions? It looks like the current functionality allows for additional pools only within the interface subnet, and it pre-defines subnet and subnet mask which would have to be editable to support arbitrary subnet definition not related to the interface.

If `ArrayField` could be nested, this would be a good opportunity for it.

Since the config can support multiple subnets, and items within the subnets can be multiple too.
```
# A slightly different configuration for an internal subnet.
subnet 10.5.5.0 netmask 255.255.255.224 {
  range 10.5.5.26 10.5.5.30;
  option domain-name-servers ns1.internal.example.org;
  option domain-name "internal.example.org";
  option routers 10.5.5.1;
  option broadcast-address 10.5.5.31;
  default-lease-time 600;
  max-lease-time 7200;
}
```
The model could looks like this:
```xml
<pools>
    <entries type="ArrayField">
        <subnet type="NetworkField">
            <required>Y</required>
        </subnet>
        <netmask type="NetworkField">
            <required>Y</required>
        </netmask>
        <keys>
            <entries type="ArrayField">
                <key_name type="OptionField">
                    <required>Y</required>
                    <optionvalues>
                        <option>range</option>
                        <option>option</option>
                        <option>default-least-time</option>
                        ...
                    </optionvalues>
                </key_name>
                <option_name type="TextField">
                    <required>N</required>
                </option_name>
                <key_value type="TextField">
                    <required>N</required>
                </key_value>
            </entries>
        </keys>
    </entries>
</pools>
```

Intending to allow definition of multiple subnet {} definitions, each with their own options (keys, values). They could be accessed on a separate page built with the MVC and utilize bootgrids to create and edit the pools.
