### ISSUE TITLE
Changing Virtual IP Interface fails due to IP already in use

### ISSUE THREAD

**Issue by syserr0r** [opnsense/core#531]
Changing a virtual IP 1.2.3.4 from interface WAN1 to interface WAN2 fails as the virtual IP is already in use by WAN1.

```
The following input errors were detected:
• This IP address is being used by another interface or VIP.
```

![Image of error](http://i.imgur.com/jJBsZWz.png)

This is on version `15.7.22` of package `opnsense`

Current workaround is to remove the VIP and re-add with the desired interface.

**Comment by fichtner** [comment]
Nice catch, should make it into 15.7.23.

**Comment by fichtner** [comment]
Took a bit longer, sorry :(
