### ISSUE TITLE
(connection.c.750) invalid request-line -> sending Status 400 when Captive Portal is enabled

### ISSUE THREAD

**Issue by agostinimarco** [opnsense/core#5312]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X ] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [ X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**
After enabled Captive Portal services, when a client (Android or normal pc with Windows/Linux) try connect with captive portal, on OPNSense console continuous appear this error message:
"OPNsense.domain.local lighttpd 48651 - - (connection.c.750) invalid request-line -> sending Status 400"

**To Reproduce**
1. enable Captive Portal from OPNSense web interface
2. connect with a PC to the ethernet where Captive Portal is present
3. Whatc the OPNSense console to see the error message above

**Screenshots**
![error](https://user-images.githubusercontent.com/62963471/139014562-9c65d388-1127-4cdf-bed0-8ed6329965fa.jpg)

**Relevant log files**
I looked on /var/log and on /var/log/lighttpd but I can't found nothing relevant.

**Environment**
OPNsense 21.7.3_3-amd64
FreeBSD 12.1-RELEASE-p20-HBSD
OpenSSL 1.1.1l 24 Aug 2021

**Comment by myghi63** [comment]
I'm having the same issue now with OpnSense 24.7.5 (same warnings). Captive portal by itself works, but never redirects the normal requests to it, requiring the user to manually type the ip address and port.
