### ISSUE TITLE
rc.reload_all causes boots to be stuck when used with ZeroTier

### ISSUE THREAD

**Issue by lflare** [opnsense/core#5315]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

I am not entirely sure if this is the correct repository to open this issue at, but after the PR #5136, booting OPNsense with the two new lines of the following, when combined with the ZeroTier plugin, causes the boot to be stuck after the `Firewall rules loaded` log line.

```
[...]
passthru('/usr/local/etc/rc.freebsd stop');
passthru('/usr/local/etc/rc.freebsd start');
```

*Tip*: to validate your setup was working with the previous version, use opnsense-revert (https://docs.opnsense.org/manual/opnsense_tools.html#opnsense-revert)

**To Reproduce**

1. Install `opnsense-zerotier`
2. Join a network
3. Reboot?
4. Get stuck waiting for the heat death of the universe while booting.

**Expected behavior**

For the boot process to complete without a hiccup.

**Describe alternatives you considered**

Commenting the two lines of `passthru` out prevents the boot process from being stuck after the `Firewall rules loaded` log line.

**Screenshots**

**Relevant log files**

**Additional context**

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 21.7.4 (amd64, OpenSSL).
Intel i7-8559U
Proxmox KVM

**Comment by smg-ca** [comment]
Hey this is a pretty old issue but seems to be still not fixed correctly.

Starting the freebsd stuff (it must be a "legit/default" plugin -> udpbroadcastrelay) will freeze the start command.
So changing the output __from stdout to stderr__ will solve the issue of freezing and the output will still be shown:
`passthru('/usr/local/etc/rc.freebsd start');` => `passthru('/usr/local/etc/rc.freebsd start 1>&2');`
