### ISSUE TITLE
Php error during guided configuration of LAN network

### ISSUE THREAD

**Issue by benstadin** [opnsense/core#5316]
- [ x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x ] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

After a fresh install, the guided configuration process shows an php error after setting an IP address to the LAN interface. 

The following error message is shown:

`Warning: Illegal string offset 'lan' in /usr/local/www/wizard.php(155) : eval()'d code on line 17 Fatal error: Uncaught Error: Cannot use string offset as an array in /usr/local/www/wizard.php(155) : eval()'d code:17 Stack trace: #0 /usr/local/www/wizard.php(155): eval() #1 {main} thrown in /usr/local/www/wizard.php(155) : eval()'d code on line 17`

**To Reproduce**

1. Reset to factory defaults in cli. 
2. Setup: Single WAN interface (I have more but chose single WAN in order to enable Web Gui access for a hosted instance)
3. Go to the Web Gui and walk through the guided process. When you reach the LAN step, enter a valid IP address. Clicking on save shows the php error below.

**Expected behavior**

Clicking the save button should proceed with the next step.

**Describe alternatives you considered**

A clear and concise description of any alternative solutions or workaround you considered.

**Screenshots**

**Relevant log files**

If applicable, information from log files supporting your claim.

**Additional context**

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 21.7.4 (amd64, OpenSSL).
AMD Ryzen 3600 Six Core
Network: 1 x 1 GBit copper, 2 x 10 Gbit LWL

**Comment by kulikov-a** [comment]
imho it looks like dhcpd part of config not having 'lan' array in it? is it brand new install or did you perform any actions with the config before starting the wizard?

**Comment by fichtner** [comment]
As stated WAN only setup was configured. Wizard expects the default WAN/LAN combination it seems.

**Comment by AdSchellevis** [comment]
seems like it https://github.com/opnsense/core/commit/3be0173e550f0361a2cbde90bca446568cccd675 should at least make sure it won't try to push anything it can't. php code wrapped in xml, always a monstrosity to properly debug.
