### ISSUE TITLE
The same 'Monitor IP' cannot be used for more than one gateway

### ISSUE THREAD

**Issue by syserr0r** [opnsense/core#532]
We have three WAN links, each is to a local device (ADSL/VDSL modem) so will always ping, even when the link is down.

We use google-public-dns as an alternate Monitor IP (8.8.8.8 and 8.8.4.4), however we cannot re-use these IPs for the third WAN link.

Could you also confirm that the monitoring uses the gateway interface and not the default gateway.
(i.e. WAN1 is the default gateway, WAN2 has a monitor IP of 8.8.4.4, if WAN2 goes down will the monitoring pick it up, or continue to ping over WAN1?)

**Comment by syserr0r** [comment]
Update: I can confirm that WAN2 is marked as UP on the Gateways > Status page even when it is down -- this is when using 8.8.4.4 as the monitor IP.

Should I raise another issue for the monitoring not using that interface/gateway or is this working as intended?

**Comment by fichtner** [comment]
There's also 4.2.2.1 - 4.2.2.6.

I'm not sure if reusing the same IP for multiple WAN links is a good setup. I'll dig into the code soonish. Normally you can force an interface for the ping and hope the kernel won't route it otherwise when the connection is lost but the link is still up.

**Comment by fichtner** [comment]
I'll have to mark this won't fix, a monitoring gateway sets a host route and must stick to it. We were discussing suppression of the monitoring host route entry, that will switch the monitor to whatever link is open, but it won't monitor the gateway anymore.
