### ISSUE TITLE
Schedule Updates

### ISSUE THREAD

**Issue by themonkeymixer** [opnsense/core#5322]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [ ] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [ ] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**

A clear and concise description of what the problem is including your motivation for the request,
i.e. "For the purpose of [...] I am missing a solution that will [...]."

**Describe the solution you like**
Hi, thanks for a great product and the awesome support!
One thing that we see in some other firewalls that I think is missing here is the ability to schedule updates for a specific time.
Many of our OPNsense systems are in use during production hours but are completely available during weekends for example.
This would really help us to keep systems patched and current.

(e.g. I would like an input field in the `/ui/firewall/alias` which would add .... to ....)

**Describe alternatives you considered**

A clear and concise description of any alternative solutions or features you considered.

**Additional context**

Add any other context or screenshots about the feature request here or links to relevant forum thread or similar

**Comment by fichtner** [comment]
Hi @themonkeymixer,

The scope of this request is a little unclear. We already have cron-based update command that you can set from the GUI.

if you talk about one-shot schedule that feature was discussed a while back and although it’s possible it’s some work to get it polished so we might only do it for the business edition when requested by customers.

But using the „at“ utility it‘s possible to do this on the command line already. It’s only a single command and if you are interested I can try to find the forum post that covers this.


Cheers,
Franco

**Comment by superwinni2** [comment]
Maybe you are searching for this:
System -> Settings -> Cron:
Create Cronjob with Command "Automatic firmware update".
