### ISSUE TITLE
Users cannot view or create log file templates unless "GUI: All pages" permission is given

### ISSUE THREAD

**Issue by Samdotr** [opnsense/core#5326]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

When on Firewall > Diagnostics > Live View page (`ui/diagnostics/firewall/log`), users cannot see existing templates or save new ones unless they've been granted the "GUI: All pages" permission. 

**To Reproduce**

1. Create a user or group with all permissions granted **except** "GUI: All pages".
2. Log into the Web GUI with the new user and go to Firewall > Diagnostics > Live View
3. Add a filter then click on >> arrow icon
4. Enter a name and try to save
5. See error: **Template save failed. Message: undefined**

**Expected behavior**

I would expect that granting the permission for "Diagnostics: Logs: Firewall: Live View" would also provide the permission to view and save templates.

**Describe alternatives you considered**

I am not aware of any alternatives/workarounds to this issue

**Screenshots**

This is the error seen when trying to save a template
<img width="1237" alt="templatesavefailed" src="https://user-images.githubusercontent.com/22962548/139560635-e4f1db31-b6b0-469f-afa3-1002034fa245.png">

This is the permission I'd expect to allow a user to view and save live view templates
<img width="432" alt="liveview" src="https://user-images.githubusercontent.com/22962548/139560639-39db8d10-a424-45c6-a0fc-6cf1260fd6d7.png">

This is the permission which actually allows the user to view and save templates (but cannot be used since it provides access to everything else in the Web GUI)
<img width="428" alt="allpages" src="https://user-images.githubusercontent.com/22962548/139560710-700c23e0-01de-4a9a-85fe-cd5ca492533e.png">

**Relevant log files**

N/A

**Additional context**

N/A

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 27.1.3_3 (amd64, OpenSSL).

**Comment by kulikov-a** [comment]
hi
sorry, i forgot about that
will make a pr

**Comment by AdSchellevis** [comment]
should be fixed with https://github.com/opnsense/core/pull/5327/commits/c87c34f6f97bc1c7f21793300f3702c87ce65e65
