### ISSUE TITLE
LDAPS with self signed certs broken in 21.7.4

### ISSUE THREAD

**Issue by rene-bayer** [opnsense/core#5328]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

LDAPS authentication for VPN dialin worked without any problems before updating.
after updating I had to switch back to LDAP only (without encryption) to get it back working again.

opnsense-revert would also work - but I cant install plugins then.

**To Reproduce**

1. setup LDAP server with SSL (for example an Univention LDAP server)
2. add CA certificate (used for the ldap server certificate) under Trust -> Certificates -> Authorities
3. setup LDAPS accounting server
4. test Login 

Error:
![image](https://user-images.githubusercontent.com/11734245/139574557-62260561-c1a7-4916-80e8-baa87077f117.png)

**Expected behavior**

Login succeed

**Describe alternatives you considered**

This worked with 21.7.3 - after upgrade to 21.7.4 this is broken.
Tested with two different setups

**Screenshots**

NaN

**Relevant log files**

NaN

**Additional context**

NaN

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 21.7.4-amd64
OpenSSL 1.1.1l 24 Aug 2021
Intel(R) Xeon(R) E-2224 CPU @ 3.40GHz (4 cores)

**Comment by AdSchellevis** [comment]
duplicate https://github.com/opnsense/core/issues/5314, might also be fixed with https://github.com/opnsense/core/pull/5323

**Comment by rene-bayer** [comment]
Oh god .... missed that one, sorry :-)
