### ISSUE TITLE
Interfaces - log and exit interface_configure() when device node doesn't exist

### ISSUE THREAD

**Issue by AdSchellevis** [opnsense/core#5334]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**

When there's a mismatch in configured interfaces and actual existing device nodes,  `interface_configure()` will just continue to execute `ifconfig` actions on un-existing interfaces, leading to messages like:

```
The command '/sbin/ifconfig 'xxx' inet6 -accept_rtadv' returned exit code '1', the output was 'ifconfig: interface xxx does not exist'
```

**Describe the solution you like**

Usually when `interface_configure()` is called on a device node which doesn't exist it's a sign of an underlaying configuration issue or a race condition.

**Describe alternatives you considered**

prevent calling `interface_configure()` when the device node doesn't exist.

**Additional context**

none

**Comment by fichtner** [comment]
22.1-RC1 is out with all the code included so safe to close.
