### ISSUE TITLE
Captive Portal and IPv6

### ISSUE THREAD

**Issue by botboe** [opnsense/core#5335]
- [ X ] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [ X ] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

I tried to extend my working captive portal to use IPv6 as a dualstack guest-network but ran into several problems. It seemed that these inconnectivities where CP-related so that I looked into the issues here and found #1820 from 2017. Is this still correct? What is the problem with IPv6 and the CP in detail? Maybe I can deep-dive into it when I'm done with my master-thesis in the beginning of next year...

**Comment by AdSchellevis** [comment]
Should still be the case indeed, (most) rules are ipv4 only (https://github.com/opnsense/core/blob/master/src/opnsense/service/templates/OPNsense/IPFW/ipfw.conf), in theory it might be possible to support it (depending on ipfw's fwd options), it just a lot of work to refactor and test for little gain. 

We did put quite some time in it to build and extend captive portal, but in reality most of our customers don't appear to be using it, so I don't expect we will spend a lot of time on this matter at this point in time. 

If you do want to explore options, I would start with the template and work your way in.

**Comment by abdulkader-alrezej** [comment]
An Innovative IPv6 Captive Portal Solution with Integrated DNS and Proxy Services, The IPv6Spot project is an open-source.
https://github.com/abdulkader-alrezej/ipv6spot
