### ISSUE TITLE
Feature Request/Redesign of the Overview of Interfaces

### ISSUE THREAD

**Issue by andreasvel** [opnsense/core#534]
Hi,
the Overview Page for the Interface is good, but i think it would be smarter to make it more wider and reduce the space in the vertical direction to have about 10 or more interfaces on a short view (on a screen with 1920x1200)

**Comment by fichtner** [comment]
Yes, the overview should be more widget-like that it currently is.

**Comment by andreasvel** [comment]
give me a hint to test it and to edit and i will try it and post the results

**Comment by fichtner** [comment]
via a9fa3d528bcc37555cec
