### ISSUE TITLE
Distinguish between cores and threads

### ISSUE THREAD

**Issue by NOYB** [opnsense/core#5340]
Would expect something like (2 cores, 4 threads) to be reported.
![i3 2 Cores, 4 Threads](https://user-images.githubusercontent.com/1977521/140410604-fa3b020f-fb76-49eb-b2f5-2000079b6062.jpg)

For thermal sensors would expect Core 0 and Core 1 to be reported.  Not Core 0, Core 1, Core 2, Core 3.
Where cores 0 & 1 are apparently the two core 0 threads and cores 2 & 3 are apparently the two core 1 threads.
![i3 2 Cores, 4 Threads (Thermal Sensors)](https://user-images.githubusercontent.com/1977521/140410658-fa32b48d-c4ac-4b4a-9be8-354756978545.jpg)

**Comment by fichtner** [comment]
https://github.com/opnsense/changelog/blob/52567435aa2fe35428895f67b780f74cd0adf898/community/22.1/22.1#L56
