### ISSUE TITLE
template_helpers: add a helper function for printing a timestamp to inject into templated config files

### ISSUE THREAD

**Issue by g-a-c** [opnsense/core#5341]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**

While making changes to `net/frr` it became apparent that there is a fixed timestamp at the top of the `bgpd.conf` file which never changes; this makes it more difficult to tell whether your config changes are taking effect.

Jinja2 doesn't have any built-in timestamping functions, so a helper could be created for this purpose, and then any configuration files which support comments could be tagged with their generation time

**Describe the solution you like**
An example of how I see this working would be:

in `template_helpers.py`:
```python
import datetime
[...]
    @staticmethod
    def getUtcTime():
        """ return UTC timestamp in ISO 8601 format with second granularity
            :return: string
        """
        result = datetime.datetime.utcnow().astimezone().isoformat(timespec="seconds")
        
        return result
```
in `/usr/local/opnsense/service/templates/OPNsense/Quagga/bgpd.conf` or any other config template:
```
!
! Zebra configuration saved from vty
!   {{ helpers.getUtcTime() }}
!
```
which would ultimately become (in `/usr/local/etc/frr/bgpd.conf` or any other config file dynamically generated through Jinja2):
```
!
! Zebra configuration saved from vty
!   2021-11-05T23:05:44+00:00
!
```

**Describe alternatives you considered**

A clear and concise description of any alternative solutions or features you considered.

**Additional context**

Add any other context or screenshots about the feature request here or links to relevant forum thread or similar

**Comment by AdSchellevis** [comment]
I'm not against adding some additional functions into the "helper" scope, but we might need to refactor some bits and pieces to make this a bit more extendable. 

The addons (https://github.com/opnsense/core/tree/master/src/opnsense/service/modules/addons) idea originally was to easily plug in new shared functionality (like the timestamp) at some point, it just didn't mature very well. 

Let me think about this for a while, maybe we can combine the "pluggable" idea with this one.
