### ISSUE TITLE
Multicast Leaking Between LAN & WAN

### ISSUE THREAD

**Issue by roofman2008** [opnsense/core#5343]
I noticed weird behavior in the firewall with the "Multicast Traffic", the LAN multicast traffic appear on the WAN.

I'm using OPNSense over ESXi with 2 VMWare Virtual Network Cards.

I tried to sniffer the network from outside the firewall and i can see LAN IPs with Mutlicast Destination. 

I don't have any IGMP Proxy or Repeater.

Can anyone support.

**Sample**
![image](https://user-images.githubusercontent.com/47033463/140659971-5a4174bf-e34a-4efe-9a9a-5dab5f9b2dca.png)

Here is my firewall configurations on each interface
![image](https://user-images.githubusercontent.com/47033463/140660035-16f13df6-0bcf-48c1-b881-5f7f1170c41b.png)
![image](https://user-images.githubusercontent.com/47033463/140660054-c6e1b02f-0346-4195-9673-55877ff63f4e.png)
![image](https://user-images.githubusercontent.com/47033463/140660074-083a872e-cedb-4e22-bf7d-c6fd5914699d.png)

**Comment by mimugmail** [comment]
Sounds like promisc mode in the VM. Its a problem of your hypervisor or VM config, not related to OPNsense itself.

**Comment by roofman2008** [comment]
I'm splitting the interfaces into different port group like that
![image](https://user-images.githubusercontent.com/47033463/140663434-42111537-17a6-43cd-a56f-9078018c2774.png)

and promiscuous mode is disabled
![image](https://user-images.githubusercontent.com/47033463/140663444-ab02fe4b-bd23-4d0c-a27d-c4b86f5c7079.png)

**Comment by roofman2008** [comment]
I figured out the issue, the problem in the configuration, i'm using vSwitch which is by default a broadcast domain.

If i'm wrong fix me please.

**Comment by mimugmail** [comment]
Not an expert, better close here and switch to forums where more people with esxi skills are around :)
