### ISSUE TITLE
Many duplicate disk usage entries (tmpfs; RAM disk) (system info widget)

### ISSUE THREAD

**Issue by NOYB** [opnsense/core#5344]
Many duplicate disk usage entries in system info widget.
tmpfs; RAM disk

OPNsense 21.7.4
11th Gen Intel(R) Core(TM) i3-1115G4 @ 3.00GHz (2 cores, 4 threads)
ZFS USB Flash Drive
![System Information Widget - Disk usage - duplicates](https://user-images.githubusercontent.com/1977521/140666652-ef6a3df2-b47e-411d-a6d2-d86b1c3d18e7.jpg)

**Comment by fichtner** [comment]
https://github.com/opnsense/core/blob/44d015f053d665757b20b1f287df86e181803140/src/www/widgets/api/plugins/system.inc#L133

**Comment by NOYB** [comment]
PR #5348
