### ISSUE TITLE
Unexpected behavior when syncing pf-configuration 

### ISSUE THREAD

**Issue by rvn2p** [opnsense/core#5346]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**
Hi,
i use a pair of systems with pf-sync and several carp IPs. When creating the firewalls i created the interfaces on both sides but in creating i did not follow the same sequence for several site2site links.
Therefore there exist two wireguard interfaces (I call them s2s1 (wg0) and s2s2 (wg1)) which are present on both sides. When i switch it from master to slave the firewall rules from s2s1 (wg0)  on fw1 are applied to s2s2 (wg1) on fw2 which is incorrect.

When analzing the beaviour further i noticed that on one firewall the gui link to the ruleset for s2s1 is https://fw1/interfaces.php?if=opt1  and on the other one it is https://fw1/interfaces.php?if=opt2.  I could fix this by deleting all the interfaces on fw2 and re-creating them in the exact order that i did on fw1 becuase i could not alter the mapping of the wireguard interfaces (wg0,wg1) towards the internal opt1/opt2 names anywhere in the gui.

**To Reproduce**

1. Create a pair of opnsense clusters with two wireguard interfaces
2. map and activate the interfaces in another order on the second fw
3. create a dummy rule for both wireguard interfaces
4. activate the seconadry fw (e.g. enter persistenc carp maintainance mode)
4. see that the firewall rule lands in the wrong table

**Expected behavior**

I would either:
 expect the rules from one link to land in the correct link on the second fw when syncing (based on interface name)
or:
have an alternative to change the mapping of for example op1 from one wireguard interface to another
or:
get a clear warning when entering maintainence mode that the ruleset on one firewall will be transferred to a different interface

**Describe alternatives you considered**

It might just be a user error on my sight or generally understood that devices have to be created on both sides in the exact order (i was creating around a dozend so i forgot to keep track of the order)

**Environment**
2x :
OPNsense 21.7.4-amd64FreeBSD 12.1-RELEASE-p20-HBSDOpenSSL 1.1.1l 24 Aug 2021
Intel(R) Xeon(R) E-2224 CPU @ 3.40GHz (4 cores)

**Comment by mimugmail** [comment]
https://docs.opnsense.org/manual/how-tos/carp.html#setup-interfaces-basic-firewall-rules
Read the Warning box, you need to assign both in the correct order

**Comment by rvn2p** [comment]
Fair enough i did not read the manual thoroughly enough.

**Comment by rvn2p** [comment]
I would still be great to get a warning because the results are horrible once the firewall switches over and every interface get another table.
