### ISSUE TITLE
GUI unresponsive / slow - ifconfig bg-job "hangs"

### ISSUE THREAD

**Issue by botboe** [opnsense/core#5349]
- [ X ] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [ X ] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**
Presumably since the update to v21.7.4 I experience a unresponsive / hanging GUI in some cases (opening the dashboard, saving settings).
I can see a high load for `ifconfig` at that moment of the delay.

```
PID USERNAME    THR PRI NICE   SIZE    RES STATE    C   TIME    WCPU COMMAND
24919 root          1  74    0  1037M  3388K CPU3     3   0:02  88.77% ifconfig
```

`ps wwaux` showed that the process `ifconfig -m -v` gets started in the backgroud an is probably parsed for the interface-dashlet. Manually calling ifconfig show that it needs more than three seconds to complete
```
root@osense:~ # time ifconfig -m -v
[...]
0.007u 3.039s 0:03.09 98.0%     229+960k 0+0io 0pf+0w
```

I get the slowest output for my ix-interfaces, where I can see following error: `media: Ethernet autoselect (Unknown <rxpause,txpause>)` while the rest of the output for the same interface seems to be ok:
```
ix0: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500
        options=803828<VLAN_MTU,JUMBO_MTU,WOL_UCAST,WOL_MCAST,WOL_MAGIC>
        capabilities=f53fbb<RXCSUM,TXCSUM,VLAN_MTU,VLAN_HWTAGGING,JUMBO_MTU,VLAN_HWCSUM,TSO4,TSO6,LRO,WOL_UCAST,WOL_MCAST,WOL_MAGIC,VLAN_HWFILTER,VLAN_HWTSO,NETMAP,RXCSUM_IPV6,TXCSUM_IPV6>
        ether 00:90:0b:XX:YY:ZZ
        inet 192.168.XX.YY netmask 0xfffffff8 broadcast 192.168.XX.YY
        inet6 fe80::290:bff:XX%ix0 prefixlen 64 scopeid 0x1
        inet6 2a03:XX::1 prefixlen 64
        media: Ethernet autoselect (Unknown <rxpause,txpause>)
        status: active
        supported media:
                media autoselect
        nd6 options=21<PERFORMNUD,AUTO_LINKLOCAL>
        plugged: SFP/SFP+/SFP28 1000BASE-LX (LC)
        vendor: WTD PN: RTXM191-400 SN: CN4BDYB39G DATE: 2014-12-18
```

**To Reproduce**

1. Open the dashboard or save interface-settings.

**Environment**
OPNsense 21.7.4-amd64
FreeBSD 12.1-RELEASE-p20-HBSD
OpenSSL 1.1.1l  24 Aug 2021

scope7-5210 Appliance
Intel® XEON™ E3-1275v6 with AES-NI
Intel 82599EB + PLX8724 4

**Comment by fichtner** [comment]
Yes, looks like an ixgbe hardware/driver issue where the I2C read times out for unknown reasons and causes these delays.

We have a kernel workaround for the slowness, but it's not a solution. I can post the kernel here shortly.


Cheers,
Franco

**Comment by mimugmail** [comment]
I'm interested in this too, I have a customer with 400 VLANs where a plug-out and -in let the system hang for ages.

**Comment by fichtner** [comment]
# opnsense-update -kr 21.7.4-ixgbe && yes | opnsense-shell reboot

**Comment by AdSchellevis** [comment]
some more background, forum post https://forum.opnsense.org/index.php?topic=25440.15 and workaround to avoid the 1 second delay with unoccupied slots or "faulty" cables https://github.com/opnsense/src/commit/938a0467e8cbf9e47629aff57e04250e7f6be251 + https://github.com/opnsense/src/commit/d1422fe670a0c828efee0003fee4ce46173069d2

**Comment by botboe** [comment]
But that won't fix the `Ethernet autoselect (Unknown <rxpause,txpause>)`-problem, will it?

**Comment by fichtner** [comment]
What's our baseline on that expectation?

**Comment by AdSchellevis** [comment]
> I'm interested in this too, I have a customer with 400 VLANs where a plug-out and -in of the cable let the system hang for ages.


@mimugmail 22.1 will likely help a lot in these types of setups, calling ifconfig on the FreeBSD 13 seems to be much faster on the machines I've tested. It could also be that the link issue with ixgbe is less prominent on the new version too if it uses a non locked action to the driver (https://github.com/opnsense/src/blob/938a0467e8cbf9e47629aff57e04250e7f6be251/sys/dev/ixgbe/ixgbe_phy.c#L2075-L2077)

**Comment by botboe** [comment]
> 
> 
> ```
> # opnsense-update -kr 21.7.4-ixgbe && yes | opnsense-shell reboot
> ```
This fixed the described behavior! Ist this update-proof, or will this fix be part of the next update?

**Comment by fichtner** [comment]
@botboe Will be part of 21.7.5.. thanks for the test drive 👍
