### ISSUE TITLE
Feature Request for Routing Status Page

### ISSUE THREAD

**Issue by andreasvel** [opnsense/core#535]
Hi,
dont know if its possible but would be nice if its possible to show routing entries made by firewall rules or a hint to them.

**Comment by AdSchellevis** [comment]
Don't you mean diag_routes.php ? firewall rules don't create routing entries, gateways and static routes do....

**Comment by andreasvel** [comment]
Right, this is the page.
but you can make firewall rules to route certain traffic to a special gateway - so you have made a route

**Comment by fichtner** [comment]
These are completely different subsystems with different constraints and options. I wouldn't advise to mix them--it makes the current diagnostics page (which belongs to routes where system routes are set up) more complex and pushes the page "out of scope".

**Comment by andreasvel** [comment]
ok,
but an overview what firewall depends rules makes routing ?

**Comment by fichtner** [comment]
What is your use case?

**Comment by andreasvel** [comment]
To get an overview over routing packets. On 2 WANs to other Firewall it was a problem to resolve on the firewall where the packets was transfered to

**Comment by fichtner** [comment]
Andreas, I think you are looking for Firewall: Diagnostics: pfInfo, tab "Rules".

**Comment by andreasvel** [comment]
yes its right, there you can see - but I suggest that its not a good overview
just a request to make it visible on this page or a subpage ?!

**Comment by fichtner** [comment]
I'm not convinced. The API provides the raw data for external filtering if needed now and this is only for trouble-shooting for a very small amount of filter rules as you said. I don't see how this is beneficial in the grand scheme of things without considerable work on the requirement scope itself.

**Comment by andreasvel** [comment]
Its just a try to check up whats the effective routing or to solve routing problems
I had yesterday problems to make an rule based routing. adding the static route helped - but i hoped i could just make it with routing with a rule instead of an whole static route
