### ISSUE TITLE
suricata: support multiple policy property in metadata

### ISSUE THREAD

**Issue by aque** [opnsense/core#5350]
- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**
Snort VRT signatures can have multiple Policy properties in its metadata, but only the last listed policy is added to `rules.sqlite`. The Policy property is used to tweak between security and connectivity/performance.

For example, `sid:22061` in `snort_vrt.malware-other.rules`
```
# grep 'sid:22061' /usr/local/etc/suricata/rules/snort_vrt.malware-other.rules 
alert tcp $EXTERNAL_NET $HTTP_PORTS -> $HOME_NET any (msg:"MALWARE-OTHER Alureon - Malicious IFRAME load attempt";
 flow:to_client,established; file_data; content:"name=|5C 22|Twitter|5C 22| scrolling=|5C 22|auto|5C 22| frameborder=|5C 22|no|5C 22| align=|5C 22|center|5C 22| height = |5C 22|1px|5C 22| width = |5C 22|1px|5C 22|>";
 fast_pattern:only; metadata:policy balanced-ips alert, policy max-detect-ips drop, policy security-ips drop, ruleset community, service http;
 reference:url,attack.mitre.org/techniques/T1102; classtype:trojan-activity; sid:22061; rev:8;)
```

The Policy recommends setting this rule to alert or drop depending on preference ([Ref](https://www.cisco.com/c/en/us/support/docs/security/firepower-ngfw/214405-what-are-the-metrics-used-to-determine-t.html)):
* Balanced Security and Connectivity (`balanced-ips`) = Alert
* Maximum Detection (`max-detect-ips`) = Drop
* Security Over Connectivity (`security-ips`) = Drop

The rows for `sid:22061` only show a single Policy property:
```
# sqlite3 -header /usr/local/etc/suricata/rules/rules.sqlite 'select * from rule_properties where sid=22061;'
sid|property|value
22061|classtype|trojan-activity
22061|policy|security-ips drop
22061|ruleset|community
22061|service|http
```

And because of the order, `balanced-ips` is not an option in the GUI for Policy:
```
# sqlite3 /usr/local/etc/suricata/rules/rules.sqlite 'select distinct value from rule_properties where property="policy" order by value;'
max-detect-ips alert
max-detect-ips drop
security-ips alert
security-ips drop
```

**To Reproduce**

1. Enable `Snort VRT/malware-other`
2. Create a Suricata policy for signatures with `balanced-ips drop`

**Expected behavior**
Create a Suricata policy that sets signatures with `balanced-ips drop` policies to Drop.

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 21.7.4-amd64
Intel(R) Core(TM) i5-5300U

**Comment by AdSchellevis** [comment]
https://github.com/opnsense/core/commit/c28567ec1d1b0671e8e5def76c127029c38b41bd should do the trick here. 

To install on OPNsense 21.7.5 use the statement below
```
opnsense-patch c28567e
```

@kulikov-a I just noticed your commit as well, wasn't aware that you would like to take a shot here.

**Comment by kulikov-a** [comment]
@AdSchellevis Oops. I didn’t know that the link in the comments is also reflected in the source ) (just seemed interesting and wanted to check it on  test vm. I didn’t check it much and wasn’t going to suggest it yet)

**Comment by AdSchellevis** [comment]
@kulikov-a hehe, no problem at all, it was on my list to check this weekend, after my push I noticed your commit.
