### ISSUE TITLE
RA interface setting does not use custom name

### ISSUE THREAD

**Issue by Enn0** [opnsense/core#5354]
- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**
Entirely cosmetic issue.
 If I rename my interfaces e.g. WAN "external", LAN "internal" and OPT1 "DMZ", then the RA dialog still shows WAN, LAN and OPT1 while all other parts of the system I am aware of show Uplink, Internal and DMZ.

1. Create a few interfaces, they get names WAN, LAN, OPT1, etc.
2. Rename said interfaces WAN: external, LAN: internal, OPT1: DMZ
3. You'll see that these new names (external, internal, DMZ) will now be displayed (almost) everywhere.
4. EXCEPT, when configuring manual Router Advertisements (Services > Router Advertisements: [new interface name]), here the RA interface still mentions the default (WAN, LAN, OPT1, etc.) name.

**Expected behavior**
That RA interface should show my custom interface names.

![image](https://user-images.githubusercontent.com/6248627/141302595-8ff90ae2-c8b4-48b2-8f3b-eab27a48fe88.png)
**Relevant log files**

**Environment**
OPNsense 21.7.4-amd64
FreeBSD 12.1-RELEASE-p20-HBSD
OpenSSL 1.1.1l 24 Aug 202

**Comment by fichtner** [comment]
Fair enough, I'll fix this. :)


Cheers,
Franco
