### ISSUE TITLE
Unbound: do not add entries for "ifconfig"

### ISSUE THREAD

**Issue by ihatemicrosoft-was-already-taken** [opnsense/core#5355]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**

On a query to the local host name of OPNsense, unbound will return A/AAAA records for ALL interfaces. This doesn't make sense for my setup, as my OPNsense machine (or rather: Web GUI and SSH) is reachable via one of those IPs only. This (also) due to the respective Listen Interfaces configuration.

When I now try to use the hostname to connect to either SSH or Web GUI, most of the time it won't work because unbound will answer queries with a "wrong" IP. This also renders my TLS certificate for the GUI (via ACME/LE) useless. This also decreases security in a way, because to the browser, the certificate always is "wrong".

**Describe the solution you like**
As a "minimal" solution, there should be a flag in the Unbound configuration which lets one turn off generation of all "ifconfig" records for unbound. 

A more sophisticated solution might take a look at the listen interface configuration for the Web GUI and generate only the record(s) needed without the need to create an extra override record.

**Describe alternatives you considered**
The only alternative I can think of is overriding the IP address in the local hosts file of the (web) client, which in reality isn't an alternative, but a nasty workaround.

dnsmasq unfortunately isn't an alternative either, as it behaves the same way.

**Additional context**

No additional context here.

**Comment by fichtner** [comment]
I'm not sure I understand. If you set the specific listen interface Unbound should not generate more entries than required?


Cheers,
Franco

**Comment by ihatemicrosoft-was-already-taken** [comment]
As a workaround, I now changed the hostname to something random. In order to make GUI access work, I had to disable 
DNS Rebinding Checks and the HTTP_REFERRER enforcement check. Not really a desireable configuration.

**Comment by Wireheadbe** [comment]
Hmm, I'm in the same boat. I've got an always-on OpenVPN on my Android phone, and when I connect even on internal Wi-Fi, unbound frequently resolves the local lan OpenVPN host record, to the external IP, instead of the internal IP. This possibly could be prevented by disabling the function "function unbound_add_host_entries($ifconfig_details = null)" via e.g. a checkbox, similar to the one there is for DNSmasq ("Don't read the hostnames in /etc/hosts." - but then for interfaces ..)

**Comment by jPhy** [comment]
Same problem here. I have a High-Availability setup with two OPNSense-Servers. Both Servers are physically connected to two Networks. One is the usual LAN, the other one I call WANCONNECTOR which is the link from each OPNSense to a modem. The WAN is pppoe via the same physical interface as WANCONNECTOR.
The problem with unbound now is that a DNS-query for either OPNSense server will return ALL IP-Address on ALL interfaces, that is the one assigned to LAN (the one I would want to get) but also the WAN AND the WANCONNECTOR ones which I would like to have removed from the DNS reply.
Restricting the "Network Interfaces" on the Unbound General settings page to LAN stopped working for me after the update from OPNSense-22.1 to OPNSense-22.1.1_1: With OPNSense-22.1.1_1 DNS-queries to the LAN-CARP-Address are ignored while they were answered with OPNSense-22.1. I would like to keep sending the DNS-queries to the CARP-Address though.
