### ISSUE TITLE
Request / proposal for GUI of Submenu Items

### ISSUE THREAD

**Issue by andreasvel** [opnsense/core#536]
Hi,
to get more space on the left/menu would it be better the icons would be in the submenu on the left side

for the interface items it could be nice if the icons are colored if i a interace is up (green) or down (red)

**Comment by fichtner** [comment]
This will make the menu slower without caching. Caching will make the information less reliable. We'll also have services to deal with and we already said it's too loaded to push the status color into the menu. It won't even update during the lifetime of the page unless we add more JavaScript. All of this creates more trouble that it's worth. The Dashboard is the place for such information.
