### ISSUE TITLE
System log: Show more details in case of `resolving hostnames`

### ISSUE THREAD

**Issue by ericschdt** [opnsense/core#5363]
**Important notices**

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

### System
OPNsense 21.7.5-amd64
FreeBSD 12.1-RELEASE-p21-HBSD
OpenSSL 1.1.1l  24 Aug 2021

### Issue
The system logs is spammed with 
```
2021-11-20T15:51:02 | /update_tables.py[12924] | resolving 2 hostnames (1 addresses) for Meet_Test took 0.12 seconds
2021-11-20T15:46:02 | /update_tables.py[31664] | resolving 2 hostnames (1 addresses) for Meet_Test took 0.25 seconds
...
```

At this point I want to determine which client is responsible for it and what `Meet_Test` refers to. Unfortunately,  the system log does not give me any more information.

Therefore two questions: 
1) Are these hostname lookups probably generated by OPNsense or one of its plugins itself?
2) Could the log of OPNsense expanded with more details to easier track the source down?

**Comment by AdSchellevis** [comment]
The log comes from here https://github.com/opnsense/core/blob/d0630be3b09dc99315fe423f00c50d79dafd8065/src/opnsense/scripts/filter/lib/__init__.py#L136-L138

But being more verbose likely isn't the best option here since there are people injecting thousands of hostnames in a single alias which would flood syslog.

**Comment by kulikov-a** [comment]
> At this point I want to determine which client is responsible for it and what Meet_Test refers to

@ericschdt if I understood your questions correctly, then you can see the process name in the log line (in this case, it is a `update_tables.py` (that is, the process of aliases updating) and `Meet_Test` is the firewall Alias name).

**Comment by ericschdt** [comment]
Thank you for the hints, I will look into it again asap and report back if necessary. I guess until then I can close it. :)
