### ISSUE TITLE
Request of a new Menu 

### ISSUE THREAD

**Issue by andreasvel** [opnsense/core#537]
Hi,
its nice to have arranged the Tools/Diagnostic in the submenu to which it belongs - but i think one menu just with diagnostic tools and so on would be faster for checking some thing on the normal work progress.

the other points where to find the tools shouldnt beerased - just one compact menu with the tools for fast access should be possible

**Comment by fichtner** [comment]
We'll solve this differently, but I'm not at liberty to discuss yet. Planned for 16.1. :)
