### ISSUE TITLE
OpenVPN - Client Specific Overrides - Virtual network routes are not applied

### ISSUE THREAD

**Issue by lotzofwork** [opnsense/core#5375]
**_Before you add a new report, we ask you kindly to acknowledge the following:_**

- [x ] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x ] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue_

**Describe the bug**

_A clear and concise description of what the bug is, including last known working version (if any)._

If you set up an OpenVPN remote access (Client/Server) solution with TLS and "Client Specific Overrides" activated, the network routes for the additional IPv4 Tunnel Network and interfaces are not written to the routing table.

(1) If you join the VPN **without** Client Specific Overrides everything works fine.
(2) If you join the VPN **with** Client Specific Overrides the ipconfig is correctly applied and used by the VPN Client.

Reply-packets from other network devices addressed to the additional overwritten "IPv4 Tunnel Network" are sent to the Default Gateway instead of the source VPN interface.

For more details please visit the opnsense forum:
https://forum.opnsense.org/index.php?topic=25737.0

OPNsense version details:

- OPNsense 21.7.5-amd64
- FreeBSD 12.1-RELEASE-p21-HBSD
- OpenSSL 1.1.1l 24 Aug 2021 

Last known working version:

- unknown

**To Reproduce**

_Steps to reproduce the behavior:_

1. Set the firewall rules under Firewall -> Rules for all interfaces to:

=> Allow ANY to ANY with ANY Service/Protocol

2. Create a new vpn server under VPN -> OpenVPN -> Servers

- Device Mode: tun
- Interface: WAN
- Local port: 1194
- Server Mode: SSL/TLS + UserAuth
- Backend for authentication: LDAP via Synology NAS
- TLS Authentication: Enabled (Auth+Enc)
- IPv4 Tunnel Network: 172.20.20.0/24
- IPv4 Local Network: 192.168.1.0/24,192.168.2.0/24,192.168.3.0/24,192.168.4.0/24
- Type-of-Service: **true**
- Duplicate Connections: **true**
- Dynamic IP: **true**
- Address Pool: **true**
- Topology: **false**
- DNS Default Domain: true, lastname.local
- DNS Servers: 192.168.3.4
- Force DNS cache update: **true**
- Prevent DNS leaks: **true**
- Force CSO Login Matching: **true**

3. Configure two users on your LDAP-Server:

=> prename.lastname

4. Configure a "Client Specific Override" for the second user:

- servers: select the VPN server from above
- diffrent IPv4 Tunnel Network: 172.20.21.0/24
- Redirect Gateway: **true**
- Server Definitions: **true**
- DNS Default Domain: lastname.local => same as in VPNserver settings
- diffrent DNS Servers: 192.168.3.10

5. Connect to the vpn-server with the second user with CSP profile

**Expected behavior**
_A clear and concise description of what you expected to happen._

Both users should be able to communicate with other network devices.
Instead the user with active CSP cannot receive reply packets, because the firewall routes them to the default gateway.
Network 172.20.21.0/24 is an unknown network and interface 172.20.21.1/32 is not known by the firewall.

**Describe alternatives you considered**

_A clear and concise description of any alternative solutions or workaround you considered._

I´ve tried to manually add the routes for the 172.20.21.0/24 network, but thats not permitted.
I´ve tried it with VIPs linked to the ovpn interface, but that had no impact.

**Screenshots**

Feel free to ask me, if you need some specific details.

**Relevant log files**

_If applicable, information from log files supporting your claim._

Feel free to ask me, if you need some specific details.

**Additional context**

_Add any other context about the problem here._

Nothing to add.

**Environment**

Software version used and hardware type if relevant, e.g.:

- OPNsense 21.7.5-amd64
- FreeBSD 12.1-RELEASE-p21-HBSD
- OpenSSL 1.1.1l 24 Aug 2021 

- Intel(R) Celeron(R) CPU J3455 @ 1.50GHz (2 cores)
- Virtual Machine on a Synology DS1019+ device

**Comment by AdSchellevis** [comment]
most likely same as https://github.com/opnsense/core/issues/5296, in which case the solution can be found in the ticket.

**Comment by lotzofwork** [comment]
> most likely same as #5296, in which case the solution can be found in the ticket.

Hello Schellevis,

thank you for your fast reply. 
I´ve searched trough all cases, before I´ve created this ticket.

In Ticket #5296 the solutions says: 

=> Activate "Force CSO Login Matching"

I want to refer to the settings section for the vpn server in my ticket, where I mentioned that this option is set to true.
The ip settings are also correctly set at client side. I did a packet capture and I saw, that it seems to be a routing problem.

Best regards

**Comment by lotzofwork** [comment]
To make things more clear I have added a draw of the vpn traffic flow:

green: packet is sent, path is correct
red: packet is coming back, path turns wrong
purple: path that I would expect to happen

No NAT in between. IP adresses in the packet are correct set.

![draw](https://user-images.githubusercontent.com/7348786/143689203-786539e5-19f5-415f-94c1-0534677fe0cf.png)

**Comment by AdSchellevis** [comment]
Just dropping some notes here, but the most important part in the other ticket actually is (https://github.com/opnsense/core/issues/5296#issuecomment-948329595)

> Best check the openvpn logs after login, since client specific overrides can be dynamic (radius for example), these are generated during login.

If you're using client specific overrides, knowing the are being generated and used is the most important part in my humble opinion.

**Comment by lotzofwork** [comment]
Here´s a full OpenVPN-Log with replaced personal data.
CSO part begins at line 3304 user you should focus on is prename1.lastname.

[openvpn_cleared.log](https://github.com/opnsense/core/files/7627415/openvpn_cleared.log)

For me there is nothing special to see. Everything looks correct.

@noseshimself

I think this is the cause of the error. You probably have the same problem.

**Comment by lotzofwork** [comment]
The /32 CIDR should just indicate that its a single IP instead of a whole network. On some devices you need to specify it that way. Just forgot to add the /32 to the Default Gateway and OPNsense IP in the drawing. Another fail of my side is that the random host in reality is behind the default gateway which holds the static backroutes to the opnsense for the vpn. But traffic flow is fine till packets come back from destination host to vpn source over opnsense.

**Comment by lotzofwork** [comment]
ZIP-File in the attachment contains a packet capture from WAN and OVPN interface.

I´ve started a Domain Lookup from my mobilephone which is connected from vpn with CSO active.
Lookup is against Google Public DNS-Server 8.8.8.8 searching for DNS-Records of www.google.de.

The capture clearly shows answer packets arrive at WAN interface, but they are not forwarded/routed to the ovpn interface from opnsense itself.

[Packetcapture.zip](https://github.com/opnsense/core/files/7627822/Packetcapture.zip)

**Comment by AdSchellevis** [comment]
reading the original issue again, I'm not sure if the assumption that a route should be created is correct. The tunnel network itself is point to point, so it will only accept traffic originating from `172.20.22.1` to the other end (easy to test using ping from the machine and bind to the openvpn interface). 

You could try to add 172.20.22.0/24 as remote network as well, manually register routes using the advanced text field or use static routes.

**Comment by lotzofwork** [comment]
> reading the original issue again, I'm not sure if the assumption that a route should be created is correct. The tunnel network itself is point to point, so it will only accept traffic originating from `172.20.22.1` to the other end (easy to test using ping from the machine and bind to the openvpn interface).

The openvpn interface is not selectible from the list at the diagnosis tools:
![grafik](https://user-images.githubusercontent.com/7348786/144130394-03d4fae7-dce6-4bc4-a427-ac18b7df8dd0.png)

If the vpn tunnel would only accept source traffic from 172.20.22.1 (VPN Gateway), opnsense should do a NAT.
But instead (as seen in the packet capture) the real vpn-client-address 172.20.22.2 is used.

Or did you mean something diffrent? Maybe I can´t follow you here at the moment.

> You could try to add 172.20.22.0/24 as remote network as well, manually register routes using the advanced text field or use static routes.

**Register as remote network**
I haven't tried this yet, thinking that this option is only for S2S VPN tunnels.
But I will soon give you an answer on this.

**The advanced text field**
"This option will be removed in the future due to  being insecure by nature. In the mean time only full administrators are  allowed to change this setting."

**Static routes**
The OpenVPN interface is not selectible from the list while configuring a gateway. A gateway is needed to create a static route entry. I´ve tried that before.

**Comment by lotzofwork** [comment]
> You could try to add 172.20.22.0/24 as remote network as well[...]

Just tried that. It dosn´t work. Same problem still exists.

**Comment by AdSchellevis** [comment]
> Static routes
> The OpenVPN interface is not selectible from the list while configuring a gateway. A gateway is needed to create a static route entry. I´ve tried that before.

You can assign the interface in Interfaces->Assignments, after which you should also be able to ping from it by the way

**Comment by lotzofwork** [comment]
> You can assign the interface in Interfaces->Assignments, after which you should also be able to ping from it by the way

![grafik](https://user-images.githubusercontent.com/7348786/144212073-08b4f01c-233d-4d2c-b297-c083ac1a7b2f.png)

Yes. I´ve already assigned it. But I also needed to enable the interface itself. Last time i did this, it messed up with non accessible network devices. This time it´s the same. 

![grafik](https://user-images.githubusercontent.com/7348786/144215898-daaa4449-97d0-4729-94f2-3c1d16187e91.png)

When the ovpn interface is set to enable, OPNsense applies NAT to all VPN-devices and routes the traffic back to the default gateway. Even users without CSP are not able to ping or use devices from the vpn.

**Comment by lotzofwork** [comment]
Same thing happens, if I directly try to ping my smartphone from VPN-Interface itself:

![grafik](https://user-images.githubusercontent.com/7348786/144217385-b63ea278-ff6e-45d2-8910-e8d0b6282476.png)

PING-Requests for my phone (in this case 172.20.20.10) go to the MAC-Adress of my default gateway.
