### ISSUE TITLE
Captive portal get mac address 

### ISSUE THREAD

**Issue by autoantwort** [opnsense/core#5379]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**
We currently use mac based auth for our users. If they have not entered their mac in our management portal, they get assigned into an own vlan with captive portal. I now want to redirect them to the management site, but with the mac in the url so that they don't have to look up the mac in their OS.  
It is already possible to get the mac, but only when the user is logged in, but then the user has internet access. One can log in a user for one second via js, but if people are smart they check that... 

**Describe the solution you like**
An api endpoint to get the mac, or return it in the `/api/captiveportal/access/status/<zoneid>/` request even if the user is not logged in, but this can be expensive I think. 

**Describe alternatives you considered**
Doing the login -> status -> logout requests in a php script, but the captive portal does not support php sites.

**Comment by william-bohannan** [comment]
Guessing this has to do with "extended pre auth data" however there doesnt seem to be much information on how to use it, checked the docs, forums and ai.  Have asked on ticket #8533 as well.

**Comment by william-bohannan** [comment]
Ticket #8533 has the solution.
