### ISSUE TITLE
OpenVPN input validation error

### ISSUE THREAD

**Issue by OleSta** [opnsense/core#5388]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md

[x] I have searched the existing issues and I'm convinced that mine is new.

[x] The title contains the plugin to which this issue belongs

**Describe the bug**
When creating OpenVPN client Specific Overrides I get input error with valid content.
***
The following input errors were detected:
'192.168.10.0/24, 192.168.12.0/24' in 'IPv4 Local Network' may only contain valid ipv4 CIDR range(s) separated by commas.
***

*Tip*: to validate your setup was working with the previous version, use opnsense-revert (https://docs.opnsense.org/manual/opnsense_tools.html#opnsense-revert)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Relevant log files**
If applicable, information from log files supporting your claim.

**Additional context**

**Environment**
Software version used and hardware type if relevant.
e.g.:

OPNsense 21.7.6

**Comment by AdSchellevis** [comment]
duplicate https://github.com/opnsense/core/issues/5249 remove spaces and you're ready to go.
