### ISSUE TITLE
firmware: status endpoint status error is not appropriate anymore

### ISSUE THREAD

**Issue by jwoodard80** [opnsense/core#5394]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

Someone wanting just a overview of the product JSON has to make a call to /api/core/firmware/info which brings in a lot more information than might be needed (changelog, packages, plugins, etc). This takes several seconds longer to pull this information than other API calls. However, it must be made as I cannot find the data by other calls. 

I would like to suggest adding a GET command of "general" to the Firmware controller which would pull in just general overall information about the installation. 

- Product Series
- Product Version
- Product Arch
- Product Name
- Install Date (Optional)

I would see this as very useful in monitoring software like Zabbix, Solarwinds when trying to setup a device. 

As an alternative.... a parameter could be added to return only requested section

Example /api/core/firmware/info/product would return

  "product": {
    "product_abi": "21.7",
    "product_arch": "amd64",
    "product_check": null,
    "product_copyright_owner": "Deciso B.V.",
    "product_copyright_url": "https://www.deciso.com/",
    "product_copyright_years": "2014-2021",
    "product_crypto": "OpenSSL",
    "product_email": "project@opnsense.org",
    "product_flavour": "OpenSSL",
    "product_hash": "acdaa7649",
    "product_id": "opnsense",
    "product_mirror": "https://pkg.opnsense.org/FreeBSD:12:amd64/21.7",
    "product_name": "OPNsense",
    "product_nickname": "Noble Nightingale",
    "product_repos": "OPNsense",
    "product_series": "21.7",
    "product_time": "Sat Dec 4 00:25:32 CST 2021",
    "product_version": "21.7.6",
    "product_website": "https://opnsense.org/"
  }

**Comment by fichtner** [comment]
Hi @jwoodard80,

The "status" endpoint should be what you are looking for. Yes, it crunches the product_check information, but only based on a previously issued check state it it doesn't waste any time checking for the update. That's the case since 21.1.3.


Cheers,
Franco

**Comment by jwoodard80** [comment]
Thank you for replying back with this information! 

I did try that endpoint, however, I get the below message. I just assumed it was because I am on the current version and there is no update. I am happy to provide any information I can to resolve this. 

{
  "status_msg": "Firmware status check was aborted internally. Please try again.",
  "status": "error"
}

My end goal is to try and make a comprehensive Zabbix Template.

**Comment by fichtner** [comment]
602d5c5 should do the trick and returns product info under 'product' key. It might not apply to 21.7 as of yet since we have other changes queued up there.


Cheers,
Franco

**Comment by jwoodard80** [comment]
This is great!  Thank you so much for this! cannot wait to give this a go. :-)

**Comment by fichtner** [comment]
@jwoodard80 22.1-BETA3 will have it if you have a chance to take a stab at that... should be released with 21.7.7 some time next week.
