### ISSUE TITLE
Edit Alias enhancement suggestion

### ISSUE THREAD

**Issue by NOYB** [opnsense/core#5403]
Rather than a content box full of addresses, a 2 column table of addresses and descriptions would be more humanly useful.
![Edit Alias](https://user-images.githubusercontent.com/1977521/145733647-a104631d-b7c0-4aa4-9fd6-e09a72b0ed24.jpg)

**Comment by agh1467** [comment]
This is a good idea, and would be helpful in better tracking what things are. However, this would require an ArrayField within an ArrayField which isn't possible given the design of the current model structure.

I did a mock up of what it might look like regardless though:

![image](https://user-images.githubusercontent.com/7823088/146200119-2028100f-635b-4f5e-9179-93b50af7811a.png)
