### ISSUE TITLE
LDAP Import tool doesn't list all users from AD. 

### ISSUE THREAD

**Issue by pierryangelo** [opnsense/core#5404]
I am using OPNSense to implement a VPN service in my job. That was all fine, I have OpenVPN + Backend Authentication [LDAP (Active Directory) +TOTP]. 

I must import the users from Active Directory because I am creating individual keys for them in order to authenticate in OpenVPN. 

The problem is that "system_usermanager_import_ldap.php" doens't show all users that I have in the organizational units I selected when configuring the authentication server. Some objects are shown, but others don't.

- It's not a problem with extended query;
- It's not because I doesn't have selected the correct containers;

I believe the problem is occuring because there are too many objects in one of the authentication containers selected. Just objects from this container are not shown when trying to import. 

I mean, just users from this container are not shown in the import tool, but it is selected. This container has more than 3k user objects.
OU=Geral,OU=Usuarios,DC=teste,DC=com,DC=br

What can I do?

Software version used and hardware type if relevant, e.g.:
OPNsense 21.7.6-amd64
FreeBSD 12.1-RELEASE-p21-HBSD
OpenSSL 1.1.1l 24 Aug 2021

**Comment by mimugmail** [comment]
Are you sure this is allowed in your AD? I had a similar problem where only 1000 objects were sent back to the query. Was a setting in domain controller.

**Comment by fichtner** [comment]
Yes, LDAP servers commonly limit the result set they return.


Cheers,
Franco

**Comment by pierryangelo** [comment]
Guys, the problem was what you said. I talked with the guy responsible for Windows Server Administration and asked him to increase the limit of the result set. The problem was solved.

Thanks a lot. Sorry for sumit this as an issue.
