### ISSUE TITLE
Edit Alias row following Type not alternating color

### ISSUE THREAD

**Issue by agh1467** [opnsense/core#5407]
**Describe the bug**

On the Firewall -> Aliases -> Edit Alias -> Type row

The color of the visible rows following Type aren't always alternating colors as expected. With some Type selections the coloring switches:

![image](https://user-images.githubusercontent.com/7823088/146213726-25e60a55-9bc4-4c7b-b75a-bed592bee084.png)

With "URL Table (IPs)" selected an additional row is shown between Type, and Content which makes the coloring of the following rows as expected:

![image](https://user-images.githubusercontent.com/7823088/146213978-7c950edb-173b-4e41-a070-7a7342fa147a.png)

In the HTML, there are hidden rows following the Type row. (I think) these rows are colored by the CSS class `table-striped` which alternates row colors as they are defined in the HTML table when the page is rendered. These rows are then made visible or not depending on the value of the Type field via javascript which switches the attributes of the DOMs as the value of Type changes.

Since these rows are colored by the CSS regardless of their visible state, it makes it look like the rows aren't following the alternating color scheme correctly.

**To Reproduce**

1. Select 'Firewall' main menu item
2. Select 'Aliases' submenu item
3. Click the '+' (Add) button on the Aliases list
4. Select a Type to change the visible state of the hidden rows

**Expected behavior**

Each row being the alternate color of the previous row regardless of which rows are visible.

**Additional context**

Source file where HTML, and Javascript is which controls this functionality:
[alias.volt](https://github.com/opnsense/core/blob/master/src/opnsense/mvc/app/views/OPNsense/Firewall/alias.volt)

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 21.7.6-amd64

**Comment by agh1467** [comment]
I looked around and this is not an uncommon issue, and people have posted several possible solutions, none of which I found to fit the case with OPNsense. So, I made a rudimentary solution which just re-colors the rows. It's not good, but it does work.

fd8c2d14d22341791ee2813a1aef87f1700ee454

![image](https://user-images.githubusercontent.com/7823088/146308153-ecabd8d0-ef8a-4310-86a5-91fbcd54ced6.png)

![image](https://user-images.githubusercontent.com/7823088/146308264-8b45997c-dc64-486e-9717-35828d786449.png)

**Comment by AdSchellevis** [comment]
@agh1467 best open a pull request, the proposed looks reasonable at a first glance.

**Comment by kulikov-a** [comment]
@agh1467 Hi! May be it can be done shorter? like https://github.com/opnsense/core/commit/979062d047429ef0180774f06c5b14457d768c3a
but it's still nasty to manipulate DOMs like this just for stripes fixing (

**Comment by agh1467** [comment]
I created a pull request here: #5416

@kulikov-a I didn't realize that the rows would re-paint when when removing/adding rows to the table. Your approach worked as expected after a minor change. The `clone()` approach ended up copying the row which resulted in duplicate elements (with children) with duplicate IDs which would probably cause issues when executing saveFormAndReconfigure(). To mitigate that potential, I changed it to an explicit `<tr>` definition using `after()` without any ids (and no children) instead. I also added an additional condition to the `find()` requiring that a row have an id attribute just in case.

After considering the approach, the planning I mentioned isn't really required since the `remove()`/ `each()` approach wipes and resets the rows with each change universally, so this functionality would just have to be dropped into the template only when appropriate. From an MVC templating perspective, I ended up with something a little different which I've used in my plugin. 

That approach is by explicitly adding/removing the dummy row whenever a row is hidden/shown. This way the rows get added/removed at the time of hide/show instead of afterwards with a function, and the `change()` isn't executing extra stuff when there are no rows to hide/show. This also means not having to conditionally add the `remove()`/`each()` at all.

Like this:
```
            selected_row.hide()
            selected_row.after('<tr class="dummy_row" style="display: none"></tr>');
```
```
            selected_row.show()
            selected_row.next("tr[class=dummy_row]").remove();
```
In the case of this volt though, doing that would mean a bunch of extra lines doing basically the same thing that the function can complete with fewer lines.

**Comment by kulikov-a** [comment]
@agh1467 Hi! sorry for delay

> The clone() approach ended up copying the row which resulted in duplicate elements (with children) with duplicate IDs which would probably cause issues

technically i removed id in `removeAttr('id')` part but I totally agree that my example is absolutely rough. just to express the idea more clearly )

there is another idea: since technically such issue can arise not only in the alias edit form and opnsense_ui.js already contains a initFormAdvancedUI() function to workaround the stripe issue with "show advanced" toggle:
https://github.com/opnsense/core/blob/9b8024ea85d425612c80849056dac54a7f659cd4/src/opnsense/www/js/opnsense_ui.js#L414
 it might be worth considering a more global solution and add something simillar to workaround this as well? or for example just add, say, something like fn.showStriped / fn.hideStriped functions? of course if @AdSchellevis  agrees with the idea

**Comment by agh1467** [comment]
I hadn't noticed that function before. I'm going to at least change the row definition to be something similar to what's done in `initFormAdvancedUI()`, using some attribute like `data-advanced='hidden_row'`.

**Comment by agh1467** [comment]
@kulikov-a I ran through some ideas with respect to a global solution, and I think it would be possible with something like you've said.

A similar approach to how `initFormAdvancedUI()` does it could be used by specifying an attribute (or more):

Like:`data-field-visible="alias_type: geo_ip,[value2],[...]"`

Explanation: The field id on which the visibility of this field is dependent upon, along with the value(s) of the said field id should be to make this row visible. I.E. when alias_type is geo_ip, then make this field visible (this field being the GeoIP field). Each dependent field could get such an attribute which would say when it should be visible. Assumption would have to be made that all other times the row should be hidden.

Then, on the alias_type field, attach to change()

And execute `$('[data-field-visible]').toggleVisible()`

```
$.fn.toggleVisible()
  compares field_id.val() to data-field-visible value
    if match 
        $(this).show()
        Remove extra hidden row
        maybe other stuff too
    else
        $(this).hide()
        Add extra hidden row
        maybe other stuff too
```

The show/hide activities could still be separate functions depending on how much work they really need to do, and how useful they would be as separate functions.

There would also have to be an accommodation for performing the initial toggleVisible after `mapDataToFormUI()` is done.

**Comment by kulikov-a** [comment]
@agh1467 sorry for delay.
good approach imho! but for me it's hard to predict how complex the application might be without sample code (..
speaking of a more general solution, I honestly meant only the solution of the stripe issues (I did not even aim to solve the general approach of dependent rows hiding).
I was talking about something like https://github.com/kulikov-a/core/commit/cf5d10a97a1ff96c218bdcb29abab1ff28779611#diff-2272aba16c14c7e1dea19b239c61c8182488f005f30625739be56117b729b68f

**Comment by kulikov-a** [comment]
@agh1467 I apologize if my interference confused the process started as a small fix :confused:
@AdSchellevis could you please share your opinion in which direction it is more correct to move on (local (`alias.volt`) fix? global stripes control on show/hide? stripes control via dependent rows toggling?)

**Comment by AdSchellevis** [comment]
@kulikov-a fixing the issue generically for all forms sounds indeed like a better plan, I never used the `MutationObserver()` myself, according to https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver it might be wise to test some different browsers before pulling it in, the `observe` method seems to have some different remarks.

**Comment by kulikov-a** [comment]
@AdSchellevis thanks! yes, tested with `MutationObserver()` - works on ie, chrome, opera, ff. `observe` config contains `attributes: true` so it should work on old versions too. 
checking on performance impact (since I try to observe the tables in full. for example, for a haproxy settings page it is 150 targets). haven't noticed any problems yet

**Comment by AdSchellevis** [comment]
@kulikov-a it sounds like a practical solution, as soon as there's a PR I'll give it a spin on my end too. thanks!

**Comment by kulikov-a** [comment]
@AdSchellevis thanks! (its possible to optimize the checks conditions before the PR imho)
@agh1467 what do you think of this variant?

**Comment by agh1467** [comment]
@kulikov-a It seems to do what you intend for it to do. I don't understand fully, but it does work.

I found something somewhat unexpected with how I happen to be hiding/showing rows in my plugin. I'm utilizing the jQuery fadeIn()/fadeOut(), and this activity seems to cause the function to add a dummy row each time the row "changes." My default fade time is 400ms and it adds about 25 rows after each hidden row, extending the timer makes it add hundreds. Toggling the row visibility it continues to add more rows. Also once a row has faded out, it doesn't appear it can be brought back with a fadeIn() or even with a show().

You can reproduce this behavior via the console (in Firefox) using these steps:
1. Go to Firewall Alias page
2. Click Add/Edit alias
3. Select GeoIP in Type field
4. Right click->Inspect Content row, and find the <tr> for it
5. Go to Console, and run `$('tr[id="row_alias.content"').fadeOut(2000)`
6. Switch back to Inspector and look for dummy rows injected after the <tr> content row (maybe a couple hundred)

Bonus

7. Switch Type to something else, and switch back to GeoIP
8. Content row won't come back, not even for other types which use the Content row.

I looked through the Core source and found only one other location where fadeIn/fadeOut is used and it's not affected. No one else appears to be using it in plugins that I could find.

I'd still vote for your solution over mine since it's a universal hands-off solution and mine is specific. The situation with my plugin row fades is probably a corner case, and I can live without the fades if I have to. It would be nice if they could still work though.

**Comment by kulikov-a** [comment]
@agh1467 thanks alot fo response! yes, if solution is claimed to be universal it should handle all "style" attribute changes and not only if it contains "display" value only. (fadeOut adds/changes 'opacity' style). in this case we dont even need previousValue imho - just check dummy row presence. can you check with https://github.com/kulikov-a/core/commit/ebf819c29537e1870c6b6179535bc9d465308892 please?

> Bonus
Switch Type to something else, and switch back to GeoIP
Content row won't come back, not even for other types which use the Content row.

i dont think  it should since https://github.com/opnsense/core/blob/cece0d28dee933d8edd581f804cebfaef8f66833/src/opnsense/mvc/app/views/OPNsense/Firewall/alias.volt#L206
not switching "row_alias.content" visibility. if you hide it with `fadeOut` manually it will remain hidden?

**Comment by agh1467** [comment]
@kulikov-a I checked this out and it addresses the issue I saw. Both fadeIn/fadeOut work as expected. Also I see what you mean about the content row visibility, my mistake. I thought it was an example of the issue of the rows not coming back. The rows that I saw the issue of them not coming back were in my plugin, and they reappear correctly now with the new commit.

**Comment by kulikov-a** [comment]
@agh1467 great, thanks! should I make a request from this or will you try?

**Comment by agh1467** [comment]
I'm not sure what you mean, but if everyone agrees, I'll close my pull request, as there would be no need for it.

**Comment by kulikov-a** [comment]
Sorry, I mean, are you okay with the `MutationObserver()` variant and should I make a pull request from it or will you take care of it (may be improve something)?

**Comment by agh1467** [comment]
I'm OK with the `MutationObserver()` variant. I don't have anything to make improvements on for it.
