### ISSUE TITLE
Automatic Float Rule Logging

### ISSUE THREAD

**Issue by NOYB** [opnsense/core#5412]
Automatic floating rule indicates logging is disabled.  Seems to be logged anyway though.
Whatever the intended behavior it would be nice if logging indicator and behavior matched each other.
Perhaps even ability to toggle the logging same as on the other rules would be nice.
21.7.7

![Automatic Floating Rule](https://user-images.githubusercontent.com/1977521/146530927-80baefdb-aa94-44bf-a3fd-dd5d5c11aad2.jpg)
![Log](https://user-images.githubusercontent.com/1977521/146531260-52d0cbcf-4872-463d-bda1-8c624f1fba8a.jpg)
![Detailed rule info](https://user-images.githubusercontent.com/1977521/146531523-4f45da8c-ec28-4649-b5d5-ac0367b39ce5.jpg)

**Comment by NOYB** [comment]
Also would be nice if source addresses that are blocked at an interface, such as WAN, would not be allowed any degree of ingress.

**Comment by kulikov-a** [comment]
this is a strange log output: the packet data clearly indicates that this is rdr rule, and this is a ip4 tcp syn packet. the name of the rule is outdated, probably pf rules manipulations were carried out without closing the  live log.
Can I ask a question? This is not the first time you create a ticket and continue to delete the template during creation, this has some special meaning (it is much more convenient to read the request within the template)?

**Comment by agh1467** [comment]
Definitely something strange happened. That rule should only apply to ICMP6 + IPv6 packets, and none of the src/dst/port/proto  match that. That rule from your screenshot is not configured to log, and I also see 5 of those floating rules all with the same label. It's not clear which rule it's hitting.

The floating rules on my system aren't configured to log, and I'm assuming that's default. If you were to lookup the rule by id in `pfctl -s rules` I wonder if it would match the info you have in your screenshot. You can also confirm here that the rules aren't logging as well. If a rule is logging, the word "log" will appear after the direction (in/out) in the line for that rule. These floating rules shouldn't have log in them.

**Comment by NOYB** [comment]
Yes should only apply to IPv6 and there is no IPv6 on that WAN interface.  ISP doesn't support IPv6 yet.
All of the automatic float rules are indicated to be logging disabled.
My guess is that it's some other rule that's actually being hit, maybe not even a float, but by some kind of indexing bug or something that rule label is getting picked for the log entry.
There is a port forward NAT rule, that's probably what's actually being hit (rdr).  But the log entry label is from one of those automatic float rules.

Functionally it's probably working as designed.  Though I'd prefer pre NAT rather than post NAT filtering.  To me that's a porous firewall.

The float:
```
root@OPNsense:~ # pfctl -s rules | grep ac4ceb5ac705e7d37dc6113e25801573
pass in quick inet6 proto ipv6-icmp all icmp6-type unreach keep state label "ac4ceb5ac705e7d37dc6113e25801573"
pass in quick inet6 proto ipv6-icmp all icmp6-type toobig keep state label "ac4ceb5ac705e7d37dc6113e25801573"
pass in quick inet6 proto ipv6-icmp all icmp6-type neighbrsol keep state label "ac4ceb5ac705e7d37dc6113e25801573"
pass in quick inet6 proto ipv6-icmp all icmp6-type neighbradv keep state label "ac4ceb5ac705e7d37dc6113e25801573"
root@OPNsense:~ #
```

The NAT associated Filter:
```
root@OPNsense:~ # pfctl -s rules | grep 2e11b51f8336b5f2a3e3efef8f323c06
block drop in log quick on re0_vlan99 reply-to (re0_vlan99 50.3x.4x.1) inet proto tcp from any to any port = 32400 label "2e11b51f8336b5f2a3e3efef8f323c06"
block drop in log quick on re0_vlan99 reply-to (re0_vlan99 50.3x.4x.1) inet proto udp from any to any port = 32400 label "2e11b51f8336b5f2a3e3efef8f323c06"
root@OPNsense:~ #
```
50.3x.4x.1 is the ISP WAN gateway

**Comment by kulikov-a** [comment]
> But the log entry label is from one of those automatic float rules

yes, this is possible under some circumstances (for example, immediately after changing the firewall configuration with the live log opened). `pf` logs cannot contain a rule description and you have to compare the entries in the log with the entries in the rules file. when changing rules, temporary desynchronization is possible when displaying a rule that triggered before the change.

> Functionally it's probably working as designed. Though I'd prefer pre NAT rather than post NAT filtering. To me that's a porous firewall.

thats how `pf` itself works. 
```
Since translation occurs before filtering the filter engine will see
     packets as	they look after	any addresses and ports	have been translated.
     Filter rules will therefore have to filter	based on the translated	ad-
     dress and port number.

```

**Comment by NOYB** [comment]
Or it could just simply be that the NAT rule doesn't have a label so the first one in prio:1 is picked.
The log will display the NAT rule label if one forced on it in rules.debug.

**Comment by kulikov-a** [comment]
@NOYB 
i think i found something
any chance your rdr rule is created with "Pass" in 'Filter rule association'?

**Comment by NOYB** [comment]
No.
Filter rule association is "Rule "+NAT Rule Description
None of the NAT/RDR rules have an associated label rid in /tmp/rules.debug.  Manually adding a label rid causes the NAT/RDR label to be displayed in firewall log.

Hitting different NAT rules displays different labels of firewall rules.  None of them correct.
Seems that the lack of label rid on NAT rules is central to the issue.

**Comment by kulikov-a** [comment]
upd: looks like 'rdr pass ' is not the only option for this. 
@fichtner sorry, can you look at filterlog when you have time please?
it seems that for rdr rules a label can be taken from the filter rules with the same number
something like 
`10,,,1d245529367b2e34eeaff16086aeafe9,hn0,match,rdr,in,4,0x0,,127,10855,0,DF,6,tcp,48,172.17.1.54,172.17.1.103,58354,888,0,S,3726562532,,65280,,mss;nop;nop;sackOK`
where @10 is the number of rdr rule and the number of filter rule with `1d245529367b2e34eeaff16086aeafe9` label

**Comment by fichtner** [comment]
The contents of the labels/rule nr can be displayed using:

    # filterlog -l

Mine starts with "18: 02f4bab031b57d1e30553ce08e0ec131" and a quick test of a rdr rule yields the rule number 4 so that's lower than 18. Not sure what I am missing.

**Comment by kulikov-a** [comment]
thanks for joining. IMHO the number of the first filter rule with label in the list will depend on the configuration (number of interfaces, ipv6 presence, scrub, anti-spoof settings etc.) but not on the number of nat rules (the numbering is not end-to-end, and does not start with nat rules). imho if  you create enough nat rules, then for the @18 nat rule filterlog will set a label from the @18 filter rule (although, if i understand it right, there should not be labels for  nat/rdr actions). or i missing something?

**Comment by fichtner** [comment]
We can exclude the types that don't have labels, but I need to know what's going on first. :) My understanding was the rule nr was unique but that does not seem the case. Let me check the kernel code.


Cheers,
Franco

**Comment by kulikov-a** [comment]
thanks! my conclusion is based on a comparison of the output of `pfctl -vvsr`/`-vvsn`. (numbering is independent for the filter rules, nat rules and rdr rules). and read_log.py output

**Comment by fichtner** [comment]
how about https://github.com/opnsense/ports/commit/2e27655d84da91ac35e010f2651193dfdf41d511 then?

**Comment by kulikov-a** [comment]
@fichtner thanks!! works good for plain view now for me. imho a little refactor of read_log.py needed for live view (now it returns empty rule description for such cases) because of:
https://github.com/opnsense/core/blob/f83209cae3f7a40f12941dea1af8f5c11e72548c/src/opnsense/scripts/filter/read_log.py#L188-L193

so matching filter and nat numbers triggers " rule['rulenr'] in running_conf_descr['line_ids']"  elif and `rule['label'] = "%s rule" % rule['action']` not set. should i make a pr? (how is it more convenient?)

**Comment by fichtner** [comment]
from the side of filterlog we need to leave the emtpy field for backwards compat since we only insert known good rule labels there so adjusting read_log.py is best here... the details view in live log also has a silly rid 0 display with a defunct link for these btw. happy about PRs :)

**Comment by fichtner** [comment]
All done, thanks!
