### ISSUE TITLE
queryLog custom log formats

### ISSUE THREAD

**Issue by agh1467** [opnsense/core#5418]
**Important notices**

Our forum is located at https://forum.opnsense.org , please consider joining discussions there in stead of using GitHub for these matters.

Before you ask a new question, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue
----
I'm working on a plugin and was looking at using the built-in `/api/diagnostics/log/` to return the logs since they're located in /var/log. Doing some digging, I found that API uses a backend configd function which calls a python script [queryLog.py](https://github.com/opnsense/core/blob/master/src/opnsense/scripts/systemhealth/queryLog.py). This then loads some log formats defined in some python classes from an adjacent directory.

My question is, how do we define custom log formats for plugins? What I'm finding is that the only formats allowed are defined in [logformats/\_\_init__.py](https://github.com/opnsense/core/blob/master/src/opnsense/scripts/systemhealth/logformats/__init__.py), and on top of those, only specific formats predefined in queryLog can be structured into the JSON output:

https://github.com/opnsense/core/blob/master/src/opnsense/scripts/systemhealth/queryLog.py#L112-L130
```
                            if frmt:
                                if issubclass(frmt.__class__, BaseLogFormat):
                                    # backwards compatibility, old style log handler
                                    record['timestamp'] = frmt.timestamp(rec['line'])
                                    record['process_name'] = frmt.process_name(rec['line'])
                                    record['line'] = frmt.line(rec['line'])
                                    record['parser'] = frmt.name
                                else:
                                    record['timestamp'] = frmt.timestamp
                                    record['process_name'] = frmt.process_name
                                    record['pid'] = frmt.pid
                                    record['facility'] = frmt.facility
                                    record['severity'] = frmt.severity_str
                                    record['line'] = frmt.line
                                    record['parser'] = frmt.name
                            else:
                                record['line'] = rec['line']
                            if len(severity) == 0 or record['severity'] in severity:
                                result['rows'].append(record)
```

As I understand it, plugin developers won't be able to return anything other than what's defined in this if statement. For example, I have a DNS query log which I'd like to have the columns:
* source IP
* query
* query type
* status
* duration
* resolver name

**Comment by AdSchellevis** [comment]
The log enpoints are only intended for standard log output (more or less RFC5424), if you need anything else, you will have to offer your own implementation. We don't parse output of services as there will be many,

**Comment by agh1467** [comment]
Alright. Thanks for the explanation!
