### ISSUE TITLE
07[IKE] <con1|651> giving up after 5 retransmits

### ISSUE THREAD

**Issue by dstr-wpd** [opnsense/core#5421]
DPD giving up after the default 5

![image](https://user-images.githubusercontent.com/74531770/146893873-3e30e673-d6f8-4701-a58d-54e2a37c6655.png)

I tried to lower the value already, but it does still not take it. 

![image](https://user-images.githubusercontent.com/74531770/146893922-fde7aa72-7207-42c4-835e-aa17f08db85a.png)

![image](https://user-images.githubusercontent.com/74531770/146893980-f748b664-99a2-492c-822f-58287b4d690b.png)

**Comment by dstr-wpd** [comment]
Another one:
![image](https://user-images.githubusercontent.com/74531770/146895292-f1e3b77b-f87a-4772-94f3-ee6557fd3339.png)

![image](https://user-images.githubusercontent.com/74531770/146895188-d827f0f2-ea7a-4434-806f-30bcc8516c79.png)

**Comment by mimugmail** [comment]
Keyingtries -1

**Comment by dstr-wpd** [comment]
thank you mimugmail, will try that.

**Comment by dstr-wpd** [comment]
Okay this seems to have solved it for the minute at least.
But I would still consider this an Bug, because the values from the GUI are obviously not taken.

**Comment by AdSchellevis** [comment]
it's not, dead peer and keying are different types of issues (https://wiki.strongswan.org/projects/strongswan/wiki/connsection)

**Comment by dstr-wpd** [comment]
Okay I think I see what you did there: retries are not retries in DPD because it does not have such value, its "dpdtimeout" calculated with "dpddelay" value. got it

**Comment by AdSchellevis** [comment]
close?
