### ISSUE TITLE
Ipsec interface description is not stored when saving.

### ISSUE THREAD

**Issue by pbosgraaf** [opnsense/core#5425]
- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at 

**Describe the bug**

When i configure an ipsec connection and establish a connection i used to be able to set a interface description by going to:
Interfaces > IpsecX > Description field

This field was then used as the interface name throughout the opnsense environment.
Now it seems the description field does not get stored when the settings are saved, instead after pressing save the screen is reloaded and the description disappears.

I've tried this with two opnsense installs, my main router and a vm spun up for this purpose. (both running OPNsense 21.7.7-amd64)
I've also tried two browsers, chrome and firefox.

Can you validate this finding?

Thanks,
Peter

**Comment by AdSchellevis** [comment]
You can change the name in the tunnel itself for VTI interfaces, if I remember correctly, that has been the case all along. The automatically added interfaces retrieve their (permanent) description from 

https://github.com/opnsense/core/blob/26df508f075aeb3ab119abb3aa72fc792c676fd5/src/etc/inc/plugins.inc.d/ipsec.inc#L206

**Comment by pbosgraaf** [comment]
I don't fully understand what you mean, I've attached example screenshots to iilustrate.

interfaces - assignments.PNG = showing existing named ipsec interfaces and my new ipsec3 interface
interface with description.PNG = showing the interface definition of one of the named interfaces
interface without description.PNG = showing the interface definition of the unnamed ipsec3 interface

The named ipsec interfaces have the description altered and saved a long time ago, may be years ago.
When i try to change the description of the new ipsec3 interface it does not persist a save.

The ipsec tunnels also have a description but (at least for me) this does not match the interface naming in the environment.

![interface with description](https://user-images.githubusercontent.com/4615032/147358060-2e7de852-abba-4ee9-9230-cbefa1eb2aa8.PNG)
![interface without description](https://user-images.githubusercontent.com/4615032/147358062-60d5d3b6-6fcf-40b2-83f3-72aec6bef4c7.PNG)
![interfaces - assignments](https://user-images.githubusercontent.com/4615032/147358063-5fee5fd7-563f-4763-a5dd-64d28261c0ec.PNG)

**Comment by AdSchellevis** [comment]
You need to change the IPsec descriptions in `VPN->IPsec->Phase 1` (or phase 2 if the definition leads to more VTI devices)
