### ISSUE TITLE
Interface column under the Floating rules page

### ISSUE THREAD

**Issue by kabaga** [opnsense/core#5426]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [ x ] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [ x ] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**

No, it is not related to a problem, but it would help to read the Floating rules.

**Describe the solution you like**

I would to have the Interface to be added as a column on the Floating rules page. It would be easier read the rulesets if the Interfaces is visible.

**Describe alternatives you considered**

An option to enable and disable what column can be added to the Floating rules page.

**Additional context**

N/A

**Comment by agh1467** [comment]
I think one of the things to consider is that the interface field is a multi-select, and it would be a challenge to have the field visualized on the table without it getting out of hand. I do see the value that it would offer.

Maybe it could work if long interface lists could be ellipses'd (...), and offer a hover over tool tip to show the full list. Some bootgrid lists already utilize ellipses for long lists, but without the tool tip.

**Comment by kabaga** [comment]
Yes, if there is a long list ellipses + hover over (similar) to aliases would be great or an option to drag the column space horizontally.

**Comment by kabaga** [comment]
Do we have an ETA when will this feature will get implemented?

**Comment by AdSchellevis** [comment]
It probably won't. There are rules per interface and firewall groups to help organise rulesets, Floating rules aren't used frequently and often involve multiple interfaces as explained earlier.

**Comment by kabaga** [comment]
It makes sense to add an interface column to help show what is going on with the ruleset. Other firewalls do it; e.g. pfSense, Juniper SRX, Palo Alto Firewall, etc.

**Comment by aerkaya1** [comment]
We have a device with a lot of networks and we use floating rules heavily. This should be a really important feature. Similar things exist in palo alto and fortigate. We desperately need this feature.
