### ISSUE TITLE
"RA subnets" without affect (rtadvd)

### ISSUE THREAD

**Issue by danrl** [opnsense/core#543]
Services -> DHCPv6 -> $iface -> Router Advertisements

RA Subnets are not doing anything, at least I can not figure out what these should be. Should they be advertised as Route Information Option by rtadvd? Should they advertised as Prefix Information Option by rtadvd?

Whatever I put in there, they do not end up in the RA on that interface. Tried to hunt that down in the source files. Still unclear what it is supposed to do. Any hints?

**Comment by danrl** [comment]
Working on a fix. Currently building. Feel free to review general idea. a981f9a80a0c6c7c6b8db91f4d51084bc0462728

**Comment by fichtner** [comment]
@danrl do you still want to upstream this? :)

**Comment by danrl** [comment]
I'm sorry, the fix did not work in a reliable way and I discarded it after a while.

**Comment by fichtner** [comment]
Ok, I'm out of ideas... better close then?

**Comment by danrl** [comment]
Well, I think it is a UX issue at first. Then, it is also a bit scary that there are options/input fields which outputs and effects are unclear at least.

**Comment by fichtner** [comment]
@AdSchellevis did a facelift of router advertisement page that will be in 16.1.6, please double-check and report back if needed.
