### ISSUE TITLE
Firewall log html entities

### ISSUE THREAD

**Issue by NOYB** [opnsense/core#5432]
html reserved characters such as `&` are displayed as html named entities (`&amp;`).

To reproduce trigger and log a firewall rule that includes an `&` in the description.  Then view it in the firewall log "Live View" and detail info pane.

Expected Result: `&`
Actual Result: `&amp;`

Rel: 21.7.7

**Comment by agh1467** [comment]
I looked into this, and found that this is a result of the following structure:

https://github.com/opnsense/core/blob/master/src/opnsense/mvc/app/controllers/OPNsense/Base/ApiControllerBase.php#L247-L251
```
        if ($this->isExternalClient()) {
            $this->response->setContent(json_encode($data));
        } else {
            $this->response->setContent(htmlspecialchars(json_encode($data), ENT_NOQUOTES));
        }
```

The function `htmlspecialchars(json_encode($data), ENT_NOQUOTES)` is converting the ampersand to a HTML safe version. It should also be doing it for all the other special characters as well. The structure here is intentionally doing this, so I doubt that it would be a good idea to turn this off. Turning it off globally is probably not an option, but maybe there would be a way to convert it back for only the label field, or something like that.

**Comment by agh1467** [comment]
Ok. I have a working solution. This is in the Javascript for when the table row is built, and sends the text through `innerHTML` and then we pull the value which will result in decoding of the encoded entities.

https://github.com/agh1467/core/commit/efd25656404f2db06d2df2f0998893a7dfd24e9a

@kulikov-a Would you happen to have an opinion on this?

**Comment by kulikov-a** [comment]
@agh1467 Hi!
I'm not a security expert (and by the way, not a dev  :wink:  Perhaps you wanted to ask @AdSchellevis  opinion?), but in my understanding, XSS mitigate is not even necessary here: this is not arbitrary input field, rule description is stored in the config in encoded form. so, technically, a code like:
```
                                    case 'string':
                                        log_td.html(record[column_name]);
                                        break;

```
should be ok too.

**Comment by AdSchellevis** [comment]
@kulikov-a  in this case `item.html()` might be rather safe, since the endpoint doesn't return unescaped data, but in order to unpack and prevent execution we should html decode the data and put it back in as @agh1467 suggests, although we shouldn't need an additional object to do so  in my opinion. In @agh1467's example the `textarea` type is just a wrapper to dump data without evaluation and fetch the inner data. I think we can also reuse the already existing object `log_td` and do something similar. 

https://github.com/opnsense/core/commit/5da7349a129b77ccc9efcd1e7a5457d4461f0db2 should do the trick

**Comment by kulikov-a** [comment]
@AdSchellevis Hi. Coud you explain in a little more detail please. I always thought the `log_td.text(log_td.html(record[column_name]).text());` technique is XSS-vulnerable (can be verified with a `b = $("<td/>").text($('<img src=a onerror=alert("XSS")>').html().text());` in the console. jquery required). so if we still implement XSS protection then we should use the `textarea ` technique. but if we believe that there is no XSS threat (record data is always encoded), then simple  `log_td.html(record[column_name]);` does the same? what im missing here?

**Comment by AdSchellevis** [comment]
@kulikov-a you're right, mine works with a <script> tag, but fails on your test case. I think you're right, we better opt for a simple `html()`  here as the endpoint isn't capable of delivering unescaped data. I'm also not 100% sure you can't breakout the `textarea`  construction either.  If you have time for a PR, be my guest :)

**Comment by kulikov-a** [comment]
@AdSchellevis thanks!)
yes, I also think that `textarea `should be checked on injection like `</textarea><img src=# onerror=alert("XSS")>`
` If you have time for a PR`
sure, thanks!

**Comment by agh1467** [comment]
Thanks for taking a look, everyone! Can this be re-closed now? Both the main view label, and the detail pane label have been fixed now.

**Comment by AdSchellevis** [comment]
@agh1467 let's close this one indeed. thanks!

**Comment by NOYB** [comment]
Thanks everyone.  Looks good.  Clean and concise.
