### ISSUE TITLE
Store bootgrid settings in local browser storage

### ISSUE THREAD

**Issue by 8191** [opnsense/core#5439]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**

Many MVC pages make use of jQuery Bootgrid (by using the OPNsense specific UIBootgrid wrapper). Bootgrid allows the user to configure many things:
- Search filters
- Elements displayed per page
- Column visibility
- Selected page

Unfortunately these settings are lost as soon as the user leaves the page.

It would be a great feature to persist those settings on a per-user basis. When a user opens a settings page they've already modified before (e.g. changed visible columns, number of rows per page, etc.) the previous settings are restored. Settings could be stored in the local browser storage.

**Describe the solution you like**
The PR  rstaib/jquery-bootgrid#392 could be incorporated into OPNsense's jQuery Bootstrap.

_Note: this is a manual task as OPNsense's jQuery Bootgrid already diverged from its upstream._
Question: where is "the master-copy" of jQuery boostrap? In the [opnsense/core](https://github.com/opnsense/core/blob/master/src/opnsense/www/js/jquery.bootgrid.js) or in [opnsense/jquery-bootstrap](https://github.com/opnsense/jquery-bootgrid) repository?

**Describe alternatives you considered**
Implementation of a "workaround" into the `UIBootgrid` function
https://github.com/opnsense/core/blob/6439c039d571519196e4c1cf5733006dcfa1321d/src/opnsense/www/js/opnsense_bootgrid_plugin.js#L59
to simulate restoring the settings, e.g. using
```javascript
var rowCount = localStorage.getItem(grid_id+"_rowCount");
$(this_grid).find('.bootgrid-pagination-count ul.dropdown-menu li a[data-action=' + rowCount + ']').trigger('click');
```

Not really nice and most likely time consuming for things like selecting columns.

**To clarify/discuss**
- Which settings to persist
- Design (implement in opnsense_bootgrid_plugin (UIBootgrid) or in jquery-bootgrid)
- How to uniquely identify a bootgrid (is the HTML ID sufficient or do we need to consider the browser URL as well?)

**Comment by AdSchellevis** [comment]
@8191 I've kept https://github.com/opnsense/jquery-bootgrid up to date with our changes in core, but it has been a long time since I last tried to really build the component. I don't mind accepting PR's on our fork as long as the grunt build still works. Unfortunately the original component seems more or less dead since we start using it.

**Comment by 8191** [comment]
@AdSchellevis While creating PR opnsense/jquery-bootgrid#5 I recognized that parts of this functionality is already implemented in the OPNsense Bootgrid plugin wrapper:

Store settings:
https://github.com/opnsense/core/blob/6439c039d571519196e4c1cf5733006dcfa1321d/src/opnsense/www/js/opnsense_bootgrid_plugin.js#L398-L422

Load settings:
https://github.com/opnsense/core/blob/6439c039d571519196e4c1cf5733006dcfa1321d/src/opnsense/www/js/opnsense_bootgrid_plugin.js#L384-L388

Mentioned functionality requires each bootgrid to specify `data-store-selection="true"`, which currently is solely the case for the alias view of the firewall module. I believe this functionality is useful for all bootgrids - I cannot imagine any downside.

So from my point of view there are two approaches now:
1. Pull opnsense/jquery-bootgrid#5 and remove stated functionality from core (PR to be created)
2. Reject opnsense/jquery-bootgrid#5 and extend the functionality in core to also persist sorting order

Approach 2 has some down-sides from my point of view; it's actually a workaround not a solution (it's the wrong place to do something like this in a wrapper I'd say). The current implementation changes the order of the row count drop-down box, so that the stored selection is always on first position. Might be a bit awkward as maybe a high number is on the first place:
![image](https://user-images.githubusercontent.com/5854959/147796234-730795cb-d9e7-4feb-ac9f-ba943d8e2228.png)

How to proceed?

**Comment by AdSchellevis** [comment]
@8191 I agree the `jquery-bootgrid` is the logical place, back in 2019 I was probably still hoping the original project would come to live at some point, so I rather stayed away from changing the original source. I used this quite often in other projects, but for some reason  never enabled it by default on the other grids.  

Let's go for option 1, I will probably need some time to review and test before we can release this by the way.

**Comment by 8191** [comment]
@AdSchellevis Great! I'll prepare a PR for core then.
