### ISSUE TITLE
MTU/MSS change not possible with VIPs assigned

### ISSUE THREAD

**Issue by eimann** [opnsense/core#5447]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**
In Interface > [Interface Name] chaging MTU/MSS fails when IPv4 or IPv6 Configuration Type is set to none and VIPs have been assigned to the Interface.

"This interface is referenced by IPv6 VIPs. Please delete those before setting the interface to 'none' configuration."

Note: The configuration type has not been changed. Only MTU/MSS have been changed.

**To Reproduce**

Create GRE tunnel
Assign GRE tunnel to Interface
Assign VIP to new Interface
Set MTU or MSS

=> Failure

Remove VIP
Set MTU or MSS

=> Works

**Expected behavior**

MTU/MSS should be settable without removing VIP.
Error is misleading, as IPvX Configuration Type has not been changed.

**Environment**

OPNsense 21.7.7-amd64
FreeBSD 12.1-RELEASE-p21-HBSD
OpenSSL 1.1.1l 24 Aug 2021

**Comment by fichtner** [comment]
Hi @eimann, I think this limitation was lifted from upcoming 22.1 or there is a ticket for it to do it.

Cheers,
Franco

**Comment by eimann** [comment]
Thanks @fichtner I'll check once released :)

**Comment by fichtner** [comment]
@eimann FYI it's e6f9b9a38832

    # opnsense-patch e6f9b9a38832

Feel free to close if this works for you. :)


Cheers,
Franco

**Comment by eimann** [comment]
Hey Franco,

the live patching is certainly cool :-O
And the patch works to my satisfaction. Thank you very much for getting back to it so fast!

Cheers,
Dominik

**Comment by fichtner** [comment]
@eimann cool, make sure to reapply when needed after next 21.7.x updates... but as said will be in 22.1 by default.


Cheers,
Franco
