### ISSUE TITLE
Issue while trying to restore configuration

### ISSUE THREAD

**Issue by Fazelesswhite** [opnsense/core#545]
Hey guys,

I was trying to restore a backup config file on opnsense and it gives me :  The configuration could not be restored (file upload error).

What can I do to fix it? Thanks!

**Comment by AdSchellevis** [comment]
@Fazelesswhite did you try upgrading first after installation? It looks like is_uploaded_file fails in your case. 
How big is your config file? it might be a php maximum your hitting here.

**Comment by Fazelesswhite** [comment]
It's 40 KB, I don't think that's the problem..

**Comment by AdSchellevis** [comment]
Your right, 40kb can't be an issue here.. what version of OPNsense do you use?

**Comment by Fazelesswhite** [comment]
11.2 is the version I'm using, thanks for such swift responses

**Comment by AdSchellevis** [comment]
are you sure? our latest version is 15.7.22, can you try an upgrade first?

**Comment by Fazelesswhite** [comment]
'''
<opnsense>
  <version>11.2</version>
  <theme>opnsense</theme>
  <sysctl>
'''
In my xml file I saw this, that's what I thought the version was haha, on the dashboard it shows, 15.7.99_1689-i386

**Comment by AdSchellevis** [comment]
your using the development version :) can you try switching to stable and see if the issue persists? We did some refactoring on this page, maybe it's introduced a new issue, although the processing code shouldn't be that different.

just to be sure, can you also check what  df -h outputs on the console?

**Comment by Fazelesswhite** [comment]
Oh so I built an old version of opnsense? How can I build using the latest source? I'm gonna test the config thingy with the latest version of opnsense from the site

**Comment by AdSchellevis** [comment]
switching back and forth is explained here https://forum.opnsense.org/index.php?topic=917.0

**Comment by hobi82** [comment]
I also have an issue restoring any configurations on a freshly updated 15.7.23 amd64 version. Error msg. is always:

"The following input errors were detected: The configuration could not be restored (file upload error)."

I did the following: downloaded the newest vga USB img 15.7.18 from the San Francisco mirror and wrote the image to the USB stick as described by the wiki. I did a default installation of that version from USB and left everything default except WAN I set to DHCP and connected with a laptop to the GUI. Then I immediately went to the firmware upgrade section to upgrade OPNSense as suggested further above. First it upgraded pkg to 1.6.2 and afterwards over 60 system packages and rebooted. OPNSense version changed from 15.7.18 -> 15.7.23.

Then when I export ALL config into a file and immediately try to reimport it, it comes up with the abovementioned error. Alternatively I also can't import my old config with 15.7.23 anymore (source of that second config file was 15.7.17).

Is there anything wrong with the import process?? I can provide some files (wireshark pcap or HTTP POST of the import process, ASCII output of the same).

I found some things on the web which might help:

https://redmine.pfsense.org/issues/5187
http://stackoverflow.com/questions/4007969/application-x-www-form-urlencoded-or-multipart-form-data

**Comment by fichtner** [comment]
Hi there,

Thanks for the detailed report. The browser type probably matters, IE 9 and below are known to cause upload compatibility woes.

Which browser do you use? And can you double-check using an up-to-date Firefox or Chrome to confirm?


Cheers,
Franco

**Comment by hobi82** [comment]
Cheers for your prompt reply. I have tried the following browsers:

Firefox 42 and 43
Chromium (Chrome) 47.0.2526.73

All under Linux Mint 17.3 and all had the same result: "The following input errors were detected: The configuration could not be restored (file upload error)."

**Comment by AdSchellevis** [comment]
I just checked again, if the machine already has a restore scheduled it ruins the form tag due to misplacement of the first one (although this shouldn't be your issue here). 
The issue seems to be a missing enctype="multipart/form-data" part in the form tag which was accidentally removed in the last cleanup.

I've fixed both in https://github.com/opnsense/core/commit/ba1d5f0f64b652ec3d9fca200238b373bfb0c4e7 

In case you want to test this without pulling all in, you can run the following command from the console:
```
curl -o /usr/local/www/diag_backup.php  https://raw.githubusercontent.com/opnsense/core/master/src/www/diag_backup.php
```

**Comment by fichtner** [comment]
Thanks Ad :)

**Comment by hobi82** [comment]
Thanks a lot :)
