### ISSUE TITLE
Insecure Default Hash Algorithms for IPsec P2

### ISSUE THREAD

**Issue by 8191** [opnsense/core#5450]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

When creating a new IPsec phase 2 entry per default MD5 and SHA-1 are selected, which are both insecure.

**To Reproduce**

1. Go to 'VPN' > 'IPsec' > 'Tunnel Settings'
2. Create a Phase 1 entry
3. Create a Phase 2 entry
4. Check default selection in "Hash Algorithms"

**Expected behavior**

MD5 and SHA-1 shall be unchecked and a secure (SHA-3) algorithm shall be checked.

**Describe alternatives you considered**

A clear and concise description of any alternative solutions or workaround you considered.

**Screenshots**

![image](https://user-images.githubusercontent.com/5854959/147870165-c5647377-33c1-43d6-b64d-6bced2abe541.png)

**Relevant log files**

-

**Additional context**

Maybe MD5 and SHA-1 (and DES) should even get an "insecure" label added in the GUI?

**Environment**

OPNsense 22.1 dev (amd64, OpenSSL).

**Comment by AdSchellevis** [comment]
@8191 how about https://github.com/opnsense/core/commit/dd1776030c2fac435be19d6dc82c9c9f5e442896? for most setups the aesgcm variants are the best option to use in terms of security and performance, so maybe best select those as defaults while here too.

**Comment by 8191** [comment]
Sorry, should have pulled before...

**Comment by 8191** [comment]
@AdSchellevis I just stumbled upon  [this change in FreeBSD 13](https://cgit.freebsd.org/src/commit/?id=16aabb761c0a). It seems that most legacy algos are not even supported anymore.

**Comment by fichtner** [comment]
That seems rather excessive and destructive oO

**Comment by AdSchellevis** [comment]
That does indeed seems rather excessive and destructive, it's also pretty weird removing non-recommended protocols, as they are, well, not recommend, but certainly not forbidden (https://wiki.strongswan.org/projects/strongswan/wiki/Changelog56#Version-561).

We should probably discuss reverting that commit on our end for 22.1, as this will cripple quite some setups for no valid reason.
In the long term we should drop it (as we can't maintain this level of deviation), but maybe a two step approach (remove from ui in 22.1 and completely as of 22.7/23.1) would be more user-friendly.

I missed it in the FreeBSD release notes, but does indeed state the following:

> Removed support for IPsec algorithms deprecated by RFC 8221 as well as Triple DES

**Comment by fichtner** [comment]
There is no point reverting stuff like https://cgit.freebsd.org/src/commit/?id=16aabb761c0a as it comes with a 1,5 year trail of functional removal and reworks of opencrypto kernel library. What we need to do is assess real world impact and offer appropriate migration notes.

**Comment by 8191** [comment]
👍 to temporarily reverting this for 22.1, but we should anyway add a warning maybe to the release notes of 22.1 (that those algos are now deprecated and subject of removal in 22.7) and I would even display a warning banner in the IPsec config page as long as one connection uses such an algo.

**Comment by 8191** [comment]
@fichtner Sorry didn't see your comment before. 
Well now it's a bit late for migration notes and recommendations. We should have done this with 21.7.7... Don't you think?
It lies in the nature of a VPN that one wants to interface a device of a potential third party without direct control of their capabilities. A short transition phase would be appreciated by many users I'd assume...

**Comment by 8191** [comment]
Hm. Valid point, @fichtner 
Well then the only option is to remove the algos and add this breaking change prominently to the release notes of 22.1 giving users the option to defer an update until their peers are ready.
