### ISSUE TITLE
LAN to LAN Traffic is Being Blocked

### ISSUE THREAD

**Issue by Danny2100** [opnsense/core#5452]
I set Opnsense up yesterday on a protectli.

I have 3 Networks.

LAN 192.168.1.0/24
IOT 192.168.4.0/24
IPCameras 192.168.2.0/24

LAN and IOT have internet and are functional. IPCameras is functional as well with 0 internet access just 3 ports are open to the blue iris server only.

On LAN I have phones and a blue iris server besides other things but this is where I noticed an issue.

There is a "default deny rule" I can't find anywhere blocking traffic from the blue iris server to 2 phones on the same subnet. 

What is odd is that prior to locking IOT down from accessing LAN with the exception of home assistant and a tablet I was able to access the blue Iris server on IOT but not on LAN.

I have no floating rules other than those auto-generated. The only LAN rule I have other than those auto-generated is to allow LAN to access any destination.

On LAN you can see I attempted to create a rule anyway that mirrored what was being blocked and it did not work so I disabled it. It was still being blocked even when I mirrored what the log said. Source 192.168.1.246:81 and destination any. It was still blocked by the "default rule"

IOT Rules:
https://i.imgur.com/HzFHzgx.png

LAN Rules:
https://i.imgur.com/m2hst0X.png

IPCameras Rules:
https://i.imgur.com/lLksoq7.png

Logs:
https://i.imgur.com/8672qMG.png

I also noticed that for rules I created I can click on the rid link to find the rule however for this "default deny rule" I am unable to.

Detailed Rule Info:
https://i.imgur.com/XxsmuK4.png

Any help would be appreciated. I tried researching this issue and could only find LAN to WAN issues but not LAN to LAN.

**Comment by fichtner** [comment]
Your issue is really not with a stateful firewall when your LAN traffic is not finding itself away from the firewall. Your LAN traffic does not communicate over OPNsense. Never. Check your switches and cabling.


Cheers,
Franco

**Comment by Danny2100** [comment]
How come it shows it's being blocked though?

**Comment by fichtner** [comment]
It's the correct question, but I can't give the answer. It's being blocked because it shouldn't arrive at the firewall. It's also irrelevant because the firewall won't be able to block on the switch behind it....

**Comment by fichtner** [comment]
Maybe more clear: it's blocking transit from LAN to outside networks where your internal LAN traffic shouldn't be going. So it's doing the correct thing really.

**Comment by Danny2100** [comment]
I found the issue after you said it's likely a switch/destination issue.

I had my server setup with a subnet mask of 255.255.255.255  by accident when it should be 255.255.255.0 it works now. Thank you for your help I would have never thought of it.

**Comment by fichtner** [comment]
Nice, happy to be of help :)
