### ISSUE TITLE
Captive Portal not redirecting to login page 

### ISSUE THREAD

**Issue by aledalla** [opnsense/core#5459]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x ] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x ] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

Captive Portal has different problems on different devices:
1. Windows machines - Network is connected with right parameters but either no action to login is displayed or any redirect occurs when trying to navigate, as a result, users can't provide credentials to surf the web. 
2. Android devices - We made lot of tests and figured out that on certain models, things go well, while on others, a notification to authenticate to Captive Portal only happpens the first time.  If that android phone disconnects the network and re connect, it will never asked to login to Captive Portal, as a result users are unable to surf the web as mentioned at point 1.

Already searched online and figured out that is not an https redirect problem, because that happen also when trying to search over http.
Followed this tutorial to setup the Captive Portal: https://docs.opnsense.org/manual/how-tos/guestnet.html

**To Reproduce**

1. Use this tutorial to setup the Captive Portal: https://docs.opnsense.org/manual/how-tos/guestnet.html

**Expected behavior**

I expect to get a notification everytime I connect to CaptivePortal that brings me to Login Page or get redirected to the Login Page if session is not authenticated yet.

**Environment**

OPNsense 21.7.7-amd64, OpenSSL.
Intel(R) Xeon(R) Gold 5120 CPU @ 2.20GHz (4 cores)

**Comment by agussutrisno1979** [comment]
I have that problem, too. can't automatically enter login page 
can access login page with  enter manually gateway address with port 8000

**Comment by reesericci** [comment]
I have this problem as well

**Comment by skydiablo** [comment]
hmmm... this is not good, i have recognized the same problem as well! i'm not sure on which point this happens, any suggestion to debug this problem?

**Comment by GitDiHub** [comment]
i have that problem too

**Comment by thelegendk** [comment]
Same issue still

**Comment by elonden** [comment]
Ditto here. Can't really figure out why it wouldn't pop up with the captive portal screen. It used to work but stopped when an update got installed a few months back. I'm not using it often but when I have guests over I would like them to use that functionality.

**Comment by andreas-bulling** [comment]
same problem here. Pity that nobody seems to care that this feature is not working for so many people.

**Comment by fichtner** [comment]
This does not look like a wide spread issue judging by the few responses each year. And please don’t post to closed tickets. Instead, open a new ticket and provide at least a traceable piece of evidence like a packet capture showing the issue.

Cheers,
Franco

**Comment by swhite2** [comment]
I would like to point out that there is https://docs.opnsense.org/manual/captiveportal.html#modern-portal-support now, which may or may not help, but given that this seems to be an issue with specific clients, perhaps compatibility comes into play here.

**Comment by mimugmail** [comment]
> same problem here. Pity that nobody seems to care that this feature is not working for so many people.

It could be DNS as usual, strange v6 behavior or using upstream rules on the interface
