### ISSUE TITLE
Firewall: NAT: Outbound German Form Bug

### ISSUE THREAD

**Issue by sepei** [opnsense/core#546]
Hello,

when you want to activate as example Manual Outbound NAT rule generation
(AON - Advanced Outbound NAT) its not working when the language is set to German (or others?).
I think this is because the formdata includes in the save field "Speichern". Maybe it just apply when save value is "Save"?

Post:
Formdata German (nothing happens)
save:Speichern
mode:advanced

Formdata English (working)
save:Save
mode:advanced

**Comment by sepei** [comment]
It should be on Line 65 in the firewall_nat_out.php:
} elseif (isset($pconfig['save']) && $pconfig['save'] == "Save") {

**Comment by fichtner** [comment]
Fixed, will be part of 15.7.23, thanks!
