### ISSUE TITLE
IPsec with 22.1 does not work out of the box

### ISSUE THREAD

**Issue by 8191** [opnsense/core#5464]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

When configuring an IPsec connection within 22.1 the connection does not start up automatically.

**To Reproduce**

1. Create an IPsec configuration (P1+P2)
2. Enable IPsec
3. Check logs
  * connection does not come up
  * Error: `unable to add SAD entry with SPI c6651939: Invalid argument (22)`
4. Manually load ipsec kernel module (e.g. `kldload ipsec` or via tunables GUI).
5. Connection starts up

**Expected behavior**

Connection should start in default configuration without additional configurations by the user.

**Describe alternatives you considered**

User can manually add the "ipsec_load yes" configuration to the tunables GUI - not really practicable

**Screenshots**

**Relevant log files**

Following log lines are present during charon startup when the kernel module is not loaded:
```
2022-01-04T13:30:35	Informational	charon	00[NET] enabling UDP decapsulation for IPv4 on port 4500 failed	
2022-01-04T13:30:35	Informational	charon	00[KNL] unable to set UDP_ENCAP: Protocol not available	
2022-01-04T13:30:35	Informational	charon	00[NET] installing IKE bypass policy failed	
2022-01-04T13:30:35	Informational	charon	00[KNL] unable to set IPSEC_POLICY on socket: Protocol not available	
2022-01-04T13:30:35	Informational	charon	00[NET] installing IKE bypass policy failed	
2022-01-04T13:30:35	Informational	charon	00[KNL] unable to set IPSEC_POLICY on socket: Protocol not available	
2022-01-04T13:30:35	Informational	charon	00[NET] enabling UDP decapsulation for IPv6 on port 4500 failed	
2022-01-04T13:30:35	Informational	charon	00[KNL] unable to set UDP_ENCAP: Invalid argument	
2022-01-04T13:30:35	Informational	charon	00[NET] installing IKE bypass policy failed	
2022-01-04T13:30:35	Informational	charon	00[KNL] unable to set IPSEC_POLICY on socket: Protocol not available	
2022-01-04T13:30:35	Informational	charon	00[NET] installing IKE bypass policy failed	
2022-01-04T13:30:35	Informational	charon	00[KNL] unable to set IPSEC_POLICY on socket: Protocol not available	
2022-01-04T13:30:35	Informational	charon	00[DMN] Starting IKE charon daemon (strongSwan 5.9.4, FreeBSD 13.0-STABLE, amd64)
```

**Additional context**

https://forum.opnsense.org/index.php?topic=26231.0

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 22.1_b189 (amd64, OpenSSL).

**Comment by fichtner** [comment]
Is this for route-based connections?

**Comment by 8191** [comment]
General - for all kind of connections

**Comment by fichtner** [comment]
@AdSchellevis and I were testing due to MD5 HMAC yesterday and haven't seen this? hmmmm

**Comment by 8191** [comment]
What I don't understand is, why for FreeBSD 12 the kernel module is not needed, but for FreeBSD 13 now it is.

Output from 22.1 (with working IPsec):
```
mf@opnsense-dev2:~ % kldstat
Id Refs Address                Size Name
 1   44 0xffffffff80200000  2157978 kernel
 2    1 0xffffffff82358000    1fe90 ipsec.ko
 3    1 0xffffffff82379000    181d0 if_lagg.ko
 4    2 0xffffffff82392000     3538 if_infiniband.ko
 5    1 0xffffffff82396000     3b18 pflog.ko
 6    3 0xffffffff8239a000    73db0 pf.ko
 7    1 0xffffffff8240e000     e4f0 if_bridge.ko
 8    2 0xffffffff8241d000     7870 bridgestp.ko
 9    1 0xffffffff82425000     4b58 if_enc.ko
10    1 0xffffffff8242a000     ba48 if_gre.ko
11    1 0xffffffff82436000     f460 carp.ko
12    1 0xffffffff82446000     e318 pfsync.ko
13    1 0xffffffff82720000     3218 intpm.ko
14    1 0xffffffff82724000     2180 smbus.ko
15    2 0xffffffff82727000    27048 ipfw.ko
16    1 0xffffffff8274f000    12520 dummynet.ko
17    1 0xffffffff82762000     9718 unionfs.ko
```

Output from 21.7 (with working IPsec):
```
mf@opnsense-prod:~ % kldstat
Id Refs Address                Size Name
 1   28 0xffffffff80200000  2693678 kernel
 2    1 0xffffffff82895000    10250 carp.ko
 3    1 0xffffffff828a6000     f998 if_bridge.ko
 4    2 0xffffffff828b6000     72a8 bridgestp.ko
 5    1 0xffffffff828be000     3e78 if_enc.ko
 6    1 0xffffffff828c2000     b2f8 if_gre.ko
 7    1 0xffffffff828ce000    16008 if_lagg.ko
 8    1 0xffffffff828e5000     8b60 if_tap.ko
 9    3 0xffffffff828ee000    58440 pf.ko
10    1 0xffffffff82947000     2af8 pflog.ko
11    1 0xffffffff8294a000     ec30 pfsync.ko
12    1 0xffffffff82a1a000     2668 intpm.ko
13    1 0xffffffff82a1d000      b50 smbus.ko
14    1 0xffffffff82a1e000     8dd0 aesni.ko
```

**Comment by fichtner** [comment]
https://github.com/opnsense/src/commit/542970fa2d3fb4 then

**Comment by fichtner** [comment]
We can add it to loader but it would be nicer if strongswan did it

**Comment by 8191** [comment]
> @AdSchellevis and I were testing due to MD5 HMAC yesterday and haven't seen this? hmmmm
Is the module loaded (for whatever reason) on your test env?

> We can add it to loader but it would be nicer if strongswan did it
Why not adding it globally, unconditionally, via rc.loader.d/20-modules?

**Comment by AdSchellevis** [comment]
> Is the module loaded (for whatever reason) on your test env?

Let me bootup the test vm, it was migrated into 22.1 but worked instantly

**Comment by fichtner** [comment]
> Is the module loaded (for whatever reason) on your test env?

I don't see why it should be. The commit mentioned ifconfig can load it automatically. Maybe the difference is still route-based vs. enc0.

> Why not adding it globally, unconditionally, via rc.loader.d/20-modules?

That's what I meant, but if it's such a performance penalty users who don't need ipsec might not want that.

**Comment by AdSchellevis** [comment]
yep, the module is loaded on my end, which is logical when ifconfig loads it. So for non VTI tunnels we might need to make sure it's loaded from our service boilerplate.

**Comment by fichtner** [comment]
I guess we should just follow https://github.com/freebsd/freebsd-ports/commit/3b35676c7a812c7 as the commit implied when we start strongswan (ipsec configure)

**Comment by AdSchellevis** [comment]
shall I add this one while working on removing the non supported ciphers? I do have changes planned in the same file anyway

**Comment by fichtner** [comment]
I don't see where this went afterwards in racoon2... the code seems to disappear indicating that they reintroduced the problem later on, but please do use it if it works. Handing ticket over.

**Comment by 8191** [comment]
The reason why ifconfig does not load the module for tunnels seems to be here:
https://github.com/opnsense/src/blob/c101da50ed8c3de61b4728e06370e6e496dff071/sbin/ifconfig/ifconfig.c#L147-L154

**Comment by fichtner** [comment]
it's not really ifconfigs fault in this case. if you load the module I think enc0 appears so either we need to ifconfig enc create once if enc0 isn't there or use the sysctl/kldload approach.

**Comment by fichtner** [comment]
(creating enc0 if it doesn't exist if it loads the kernel module looks like a more logical approach)

**Comment by AdSchellevis** [comment]
fixed in https://github.com/opnsense/core/commit/7672d54c78c794bce8f42603e5c0fc81fd2246bd
