### ISSUE TITLE
"/var/log/flowd.log" not rotating - filling up disk

### ISSUE THREAD

**Issue by TheHellSite** [opnsense/core#5469]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [ X ] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [ X ] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

--> Well the issue is not entirely new, but still present.

**Describe the bug**

"/var/log/flowd.log"  does not get rotated thus filling up the whole disk over time.
For me it will grow by about 15 GB of disk space a month if not cleared manually.

**To Reproduce**

OPNsense --> Reporting --> NetFlow --> Enable: Capture local

**Expected behavior**

flowd.log should stick to the settings applied in "System --> Settings --> Logging".

**Describe alternatives you considered**

Workaround: OPNsense --> Reporting --> Settings --> Reset NetFlow Data

**Environment**

OPNsense 21.7.7-amd64
FreeBSD 12.1-RELEASE-p21-HBSD
OpenSSL 1.1.1l  24 Aug 2021

Intel(R) Xeon(R) CPU E5-2620 0 @ 2.00GHz (4 cores)

**Comment by mschilt** [comment]
same here. 

I see a python3.8. process running hogging one cpu core and the file /var/log/flowd.log keeps filling up the disk. 

Resetting the netflow data (/usr/local/opnsense/scripts/netflow/flush_all.sh all) does not really help for me. It instantly starts to re-fill the disk  (flowd.log maxing out the disk space).

**Comment by AdSchellevis** [comment]
if flowd aggregate dies (for whatever reason), it won't rotate. 

You can always try to run the aggregator in console (frontend) mode to see if it does.

```
/usr/local/opnsense/scripts/netflow/flowd_aggregate.py --console
```

**Comment by cayenne17** [comment]
same problem and is not solved

**Comment by AdSchellevis** [comment]
Without additional details that wouldn't make much sense would it? (https://github.com/opnsense/core/issues/5469#issuecomment-1119329078)

**Comment by cayenne17** [comment]
I don't know how to solve the problem by disabling the logs
The command `/usr/local/opnsense/scripts/netflow/flowd_aggregate.py --console` Don't give anything in return

**Comment by cayenne17** [comment]
> Without additional details that wouldn't make much sense would it? ([#5469 (comment)](https://github.com/opnsense/core/issues/5469#issuecomment-1119329078))

I don't know how to solve the problem by disabling the logs
The command `/usr/local/opnsense/scripts/netflow/flowd_aggregate.py --console` Don't give anything in return

**Comment by Xev** [comment]
> Without additional details that wouldn't make much sense would it? ([#5469 (comment)](https://github.com/opnsense/core/issues/5469#issuecomment-1119329078))

`$ /usr/local/opnsense/scripts/netflow/flowd_aggregate.py --console`
```
Traceback (most recent call last):
  File "/usr/local/opnsense/scripts/netflow/flowd_aggregate.py", line 224, in <module>
    Main()
  File "/usr/local/opnsense/scripts/netflow/flowd_aggregate.py", line 136, in __init__
    self.run()
  File "/usr/local/opnsense/scripts/netflow/flowd_aggregate.py", line 160, in run
    aggregate_flowd(self.config, do_vacuum)
  File "/usr/local/opnsense/scripts/netflow/flowd_aggregate.py", line 68, in aggregate_flowd
    for flow_record in parse_flow(prev_recv, config.flowd_source):
  File "/usr/local/opnsense/scripts/netflow/lib/parse.py", line 72, in parse_flow
    for flow_record in FlowParser(filename, recv_stamp):
  File "/usr/local/opnsense/scripts/netflow/lib/flowparser.py", line 135, in __iter__
    with open(self._filename, 'rb') as flowh:
PermissionError: [Errno 13] Permission denied: '/var/log/flowd.log'
```

`$ sudo /usr/local/opnsense/scripts/netflow/flowd_aggregate.py --console`
```
Traceback (most recent call last):
  File "/usr/local/opnsense/scripts/netflow/flowd_aggregate.py", line 224, in <module>
    Main()
  File "/usr/local/opnsense/scripts/netflow/flowd_aggregate.py", line 136, in __init__
    self.run()
  File "/usr/local/opnsense/scripts/netflow/flowd_aggregate.py", line 160, in run
    aggregate_flowd(self.config, do_vacuum)
  File "/usr/local/opnsense/scripts/netflow/flowd_aggregate.py", line 80, in aggregate_flowd
    stream_agg_object.add(copy.copy(flow_record))
  File "/usr/local/opnsense/scripts/netflow/lib/aggregates/interface.py", line 72, in add
    super(FlowInterfaceTotals, self).add(flow)
  File "/usr/local/opnsense/scripts/netflow/lib/aggregates/__init__.py", line 187, in add
    self._update_cur.execute(self._insert_stmt, flow)
sqlite3.DatabaseError: database disk image is malformed
```

**Comment by codiflow** [comment]
I'm experiencing the same issue like the threadstarter. Maybe this log entry in System -> Protocol -> General helps finding the main cause?

```
2023-05-04T11:00:11 | Error | flowd_aggregate.py | sqlite3 repair /var/netflow/src_addr_details_086400.sqlite
2023-05-04T10:59:55 | Notice | flowd_aggregate.py | startup, check database.
```

`/usr/local/opnsense/scripts/netflow/flowd_aggregate.py --console` does output the following after some time of waiting:

```
[...]
Runtime error near line 3209: disk I/O error (10)
Runtime error near line 3210: disk I/O error (10)
Runtime error near line 3211: disk I/O error (10)
Runtime error near line 3212: disk I/O error (10)
Runtime error near line 3213: disk I/O error (10)
Runtime error near line 3214: disk I/O error (10)
Runtime error near line 3215: disk I/O error (10)
Runtime error near line 3216: disk I/O error (10)
Runtime error near line 3217: disk I/O error (10)
Runtime error near line 3218: disk I/O error (10)
Runtime error near line 3219: disk I/O error (10)
Runtime error near line 3220: disk I/O error (10)
Runtime error near line 3221: disk I/O error (10)
Runtime error near line 3222: disk I/O error (10)
Runtime error near line 3223: disk I/O error (10)
Runtime error near line 3224: disk I/O error (10)
[...]
```

I ran `/usr/local/opnsense/scripts/netflow/flush_all.sh all` to temporary mitigate the problem. Let's see what happens now.

**Comment by AdSchellevis** [comment]
```
Runtime error near line 3209: disk I/O error (10)
```

sounds like disk full....

**Comment by codiflow** [comment]
Stuff was strange regarding the disk space. The log file was displayed to consume about 29 GB (!) but /var/log/ was only filled with about 17GB. Anyway – after flushing the database everything seems to be OK by now.

I will report back if the problem with not working log rotation persists.

**Comment by rhoot** [comment]
I had the same problem, and running `flowd_aggregate.py --console` gave me:
```
Traceback (most recent call last):
  File "/usr/local/opnsense/scripts/netflow/flowd_aggregate.py", line 224, in <module>
    Main()
  File "/usr/local/opnsense/scripts/netflow/flowd_aggregate.py", line 136, in __init__
    self.run()
  File "/usr/local/opnsense/scripts/netflow/flowd_aggregate.py", line 160, in run
    aggregate_flowd(self.config, do_vacuum)
  File "/usr/local/opnsense/scripts/netflow/flowd_aggregate.py", line 80, in aggregate_flowd
    stream_agg_object.add(copy.copy(flow_record))
  File "/usr/local/opnsense/scripts/netflow/lib/aggregates/interface.py", line 75, in add
    super(FlowInterfaceTotals, self).add(flow)
  File "/usr/local/opnsense/scripts/netflow/lib/aggregates/__init__.py", line 187, in add
    self._update_cur.execute(self._insert_stmt, flow)
sqlite3.DatabaseError: database disk image is malformed
```
Running `flush_all.sh` fixed it for me too (obviously, as it deletes the sqlite db).

**Comment by noctarius** [comment]
I know the issue is closed, but I have something along the lines. While the error message is different, it also fails to update the SQLite DB.

Would `flush_all.sh` solve it? Resetting it from the UI didn't help. While it seems like it removed a lot, the log file keeps growing again.

```
root@firewall:~ # /usr/local/opnsense/scripts/netflow/flowd_aggregate.py --console
Traceback (most recent call last):
  File "/usr/local/opnsense/scripts/netflow/flowd_aggregate.py", line 224, in <module>
    Main()
  File "/usr/local/opnsense/scripts/netflow/flowd_aggregate.py", line 136, in __init__
    self.run()
  File "/usr/local/opnsense/scripts/netflow/flowd_aggregate.py", line 160, in run
    aggregate_flowd(self.config, do_vacuum)
  File "/usr/local/opnsense/scripts/netflow/flowd_aggregate.py", line 80, in aggregate_flowd
    stream_agg_object.add(copy.copy(flow_record))
  File "/usr/local/opnsense/scripts/netflow/lib/aggregates/interface.py", line 72, in add
    super(FlowInterfaceTotals, self).add(flow)
  File "/usr/local/opnsense/scripts/netflow/lib/aggregates/__init__.py", line 185, in add
    self._update_cur.execute(self._update_stmt, flow)
sqlite3.OperationalError: attempt to write a readonly database
```

**Comment by immanuelfodor** [comment]
I'm so used to this view that I started to not care, just clear all logs before doing an update. This should be fixed :( 

![image](https://github.com/opnsense/core/assets/21174107/63603536-ebcb-41dc-ba04-ab907a15ba5c)

**Comment by j0nny55555** [comment]
Does flowd_aggregate.py --console have access or ability to maintain access to a /var/log that is using tmpfs (RAM Disk) without crashing? This is happening for me too.

I am also sending Netflow v9 to a data stack, but, the in OPNSense graphs are live and quite good, so, not really wanting to have to turn that off, just have logs rotated, and I really don't expect to need on device netflow/flow agg for more than 24 hours tops, I'll ask my data stack on the side long term questions
![image](https://github.com/opnsense/core/assets/3521352/eef72b65-b57d-4b8f-9138-1e565ea24c23)

**Comment by KDGundermann** [comment]
Have the same problem here today:
```
-rw-------   1 root           wheel          161573183844 Feb 25 18:26 flowd.log
-rw-------   1 root           wheel              16221368 Dec  6 15:22 flowd.log.000001
-rw-------   1 root           wheel              10557136 Dec  6 15:12 flowd.log.000002
-rw-------   1 root           wheel              17352592 Dec  6 14:35 flowd.log.000003
-rw-------   1 root           wheel              11100656 Dec  6 14:29 flowd.log.000004
-rw-------   1 root           wheel              10565304 Dec  6 14:23 flowd.log.000005
-rw-------   1 root           wheel              12999716 Dec  6 14:18 flowd.log.000006
-rw-------   1 root           wheel              12927196 Dec  6 14:13 flowd.log.000007
-rw-------   1 root           wheel              13939012 Dec  6 14:09 flowd.log.000008
-rw-------   1 root           wheel              10855272 Dec  6 14:04 flowd.log.000009
-rw-------   1 root           wheel              13171392 Dec  6 14:00 flowd.log.000010
```

```
root@fw01:/var/log/system # /usr/local/opnsense/scripts/netflow/flowd_aggregate.py --console
Runtime error near line 22: disk I/O error (10)
Runtime error near line 24: disk I/O error (10)
Runtime error near line 35: disk I/O error (10)
Runtime error near line 43: disk I/O error (10)
Runtime error near line 48: disk I/O error (10)
Runtime error near line 57: disk I/O error (10)
Runtime error near line 66: disk I/O error (10)
Runtime error near line 71: disk I/O error (10)
Runtime error near line 88: disk I/O error (10)
Runtime error near line 90: disk I/O error (10)
```
But enough disk space:
```
root@fw01:/var/log/system # df
Filesystem               1K-blocks      Used     Avail Capacity  Mounted on
/dev/gpt/rootfs          475315420 277944060 159346128    64%    /
devfs                            1         1         0   100%    /dev
fdescfs                          1         1         0   100%    /dev/fd
procfs                           4         4         0   100%    /proc
devfs                            1         1         0   100%    /var/dhcpd/dev
/dev/md43                    49180       272     44976     1%    /usr/local/zenarmor/output/active/temp
devfs                            1         1         0   100%    /var/unbound/dev
/usr/local/lib/python3.9 475315420 277944060 159346128    64%    /var/unbound/usr/local/lib/python3.9
```

OPNsense 23.10.1_2-amd64
FreeBSD 13.2-RELEASE-p7
OpenSSL 1.1.1w

Happend today (28.01.2026) again with 
OPNsense 25.10.1_2-amd64

**Comment by cpatulea** [comment]
OPNsense 22.7.11 (amd64/LibreSSL)

```
# service flowd_aggregate status
flowd_aggregate is not running.

/var/log # ls -l flowd*
-rw-------  1 root  wheel  35719606688 Dec 23 00:50 flowd.log
-rw-------  1 root  wheel     10507500 Jul 28  2021 flowd.log.000001
-rw-------  1 root  wheel     10492576 Jul 28  2021 flowd.log.000002
-rw-------  1 root  wheel     10488492 Jul 27  2021 flowd.log.000003
-rw-------  1 root  wheel     10487792 Jul 26  2021 flowd.log.000004
-rw-------  1 root  wheel     10491032 Jul 25  2021 flowd.log.000005
-rw-------  1 root  wheel     10499636 Jul 24  2021 flowd.log.000006
-rw-------  1 root  wheel     10492432 Jul 24  2021 flowd.log.000007
-rw-------  1 root  wheel     10487316 Jul 23  2021 flowd.log.000008
-rw-------  1 root  wheel     10520552 Jul 23  2021 flowd.log.000009
-rw-------  1 root  wheel     10522800 Jul 23  2021 flowd.log.000010

# df -h
Filesystem                  Size    Used   Avail Capacity  Mounted on
/dev/gpt/rootfs             442G     38G    369G     9%    /

/var/log/system # grep flowd *
...
system_20241214.log:<11>1 2024-12-14T22:03:20-05:00 <snip> flowd_aggregate.py 98510 - [meta sequenceId="1"] flowd aggregate died with message Traceback (most recent call last):   File "/usr/local/opnsense/scripts/netflow/flowd_aggregate.py", line 160, in run     aggregate_flowd(self.config, do_vacuum)   File "/usr/local/opnsense/scripts/netflow/flowd_aggregate.py", line 80, in aggregate_flowd     stream_agg_object.add(copy.copy(flow_record))   File "/usr/local/opnsense/scripts/netflow/lib/aggregates/source.py", line 110, in add     super(FlowSourceAddrDetails, self).add(flow)   File "/usr/local/opnsense/scripts/netflow/lib/aggregates/__init__.py", line 185, in add     self._update_cur.execute(self._update_stmt, flow) OverflowError: Python int too large to convert to SQLite INTEGER
```

**Comment by borysohnsorge** [comment]
Same here:
`Versions
OPNsense 24.7.11_2-amd64
FreeBSD 14.1-RELEASE-p6
OpenSSL 3.0.15`

`root@opnsense1:~ # service flowd_aggregate status
flowd_aggregate is running as pid 35195.`

`root@opnsense1:~ # df -h
Filesystem                   Size    Used   Avail Capacity  Mounted on
zroot/ROOT/20241218215706     28G    3.0G     25G    10%    /
devfs                        1.0K      0B    1.0K     0%    /dev
/dev/gpt/efiboot0            260M    1.8M    258M     1%    /boot/efi
zroot/tmp                     25G    2.4M     25G     0%    /tmp
zroot                         25G     96K     25G     0%    /zroot
zroot/var/log                109G     84G     25G    77%    /var/log
zroot/var/audit               25G     96K     25G     0%    /var/audit
zroot/var/crash               25G     96K     25G     0%    /var/crash
zroot/usr/home                25G     96K     25G     0%    /usr/home
zroot/var/mail                25G    144K     25G     0%    /var/mail
zroot/usr/ports               25G     96K     25G     0%    /usr/ports
zroot/usr/src                 25G     96K     25G     0%    /usr/src
zroot/var/tmp                 25G    432K     25G     0%    /var/tmp
devfs                        1.0K      0B    1.0K     0%    /var/dhcpd/dev
devfs                        1.0K      0B    1.0K     0%    /var/unbound/dev
/usr/local/lib/python3.11     28G    3.0G     25G    10%    /var/unbound/usr/local/lib/python3.11
/lib                          28G    3.0G     25G    10%    /var/unbound/lib
root@opnsense1:~ #`

`root@opnsense1:/var/log # ls -l flowd*
-rw-------  1 root wheel 511416393296 Apr  1 09:47 flowd.log
-rw-------  1 root wheel     34848724 Mar 10 16:31 flowd.log.000001
-rw-------  1 root wheel     33043536 Mar 10 16:29 flowd.log.000002
-rw-------  1 root wheel     34271772 Mar 10 16:26 flowd.log.000003
-rw-------  1 root wheel     34834672 Mar 10 16:24 flowd.log.000004
-rw-------  1 root wheel     35791900 Mar 10 16:21 flowd.log.000005
-rw-------  1 root wheel     36629600 Mar 10 16:18 flowd.log.000006
-rw-------  1 root wheel     36972300 Mar 10 16:16 flowd.log.000007
-rw-------  1 root wheel     37931036 Mar 10 16:13 flowd.log.000008
-rw-------  1 root wheel    349863348 Mar 10 16:10 flowd.log.000009
-rw-------  1 root wheel     20982408 Mar 10 15:44 flowd.log.000010
root@opnsense1:/var/log # `

`root@opnsense1:/var/log/system # grep flowd *
system_20250310.log:<13>1 2025-03-10T08:13:49+01:00 opnsense1 flowd_aggregate.py 38623 - [meta sequenceId="1"] startup, check database.
system_20250310.log:<13>1 2025-03-10T08:16:10+01:00 opnsense1 flowd_aggregate.py 38623 - [meta sequenceId="1"] start watching flowd
system_20250310.log:<11>1 2025-03-10T13:25:03+01:00 opnsense1 flowd_aggregate.py 38623 - [meta sequenceId="1"] flowd aggregate died with message Traceback (most recent call last):   File "/usr/local/opnsense/scripts/netflow/flowd_aggregate.py", line 160, in run     aggregate_flowd(self.config, do_vacuum)   File "/usr/local/opnsense/scripts/netflow/flowd_aggregate.py", line 68, in aggregate_flowd     for flow_record in parse_flow(prev_recv, config.flowd_source):   File "/usr/local/opnsense/scripts/netflow/lib/parse.py", line 73, in parse_flow     for flow_record in FlowParser(filename, recv_stamp):   File "/usr/local/opnsense/scripts/netflow/lib/flowparser.py", line 142, in __iter__     record = self._parse_binary(              ^^^^^^^^^^^^^^^^^^^   File "/usr/local/opnsense/scripts/netflow/lib/flowparser.py", line 116, in _parse_binary     fsize = self.calculate_size(self.field_definition[fieldname])             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   File "/usr/local/opnsense/scripts/netflow/lib/flowparser.py", line 91, in calculate_size     def calculate_size(self, fmt):      KeyboardInterrupt 
system_20250310.log:<13>1 2025-03-10T13:25:15+01:00 opnsense1 flowd_aggregate.py 3006 - [meta sequenceId="2"] startup, check database.
system_20250310.log:<13>1 2025-03-10T13:25:50+01:00 opnsense1 flowd_aggregate.py 35195 - [meta sequenceId="5"] startup, check database.
system_20250310.log:<13>1 2025-03-10T13:25:50+01:00 opnsense1 flowd_aggregate.py 35195 - [meta sequenceId="6"] start watching flowd
system_20250310.log:<13>1 2025-03-10T13:25:50+01:00 opnsense1 flowd_aggregate.py 35195 - [meta sequenceId="7"] vacuum done
`

`last pid: 52178;  load averages:  2.13,  1.70,  1.56                                                                                                                                                                                                                                                                                               up 84+18:04:20  09:53:40
112 processes: 3 running, 109 sleeping
CPU: 50.4% user,  0.3% nice,  1.9% system,  2.6% interrupt, 44.9% idle
Mem: 187M Active, 135M Inact, 241M Laundry, 6801M Wired, 1896K Buf, 403M Free
ARC: 5879M Total, 3773M MFU, 1838M MRU, 15M Anon, 64M Header, 187M Other
     5333M Compressed, 23G Uncompressed, 4.51:1 Ratio

  PID USERNAME    THR PRI NICE   SIZE    RES STATE    C   TIME    WCPU COMMAND
35195 root          1 132    0    58M    38M CPU3     3 520.0H  99.69% python3.11
25387 root          1 125    0    50M    34M CPU2     2   1:49  99.68% python3.11
16873 root          4  20    0    50M    14M kqread   2  46.0H   1.27% syslog-ng
  637 root          1  20    0    13M  2120K bpf      0  16:26   1.08% filterlog
27940 netdata      55  68   19   493M   191M pause    0  25.3H   0.95% netdata`

`root@opnsense1:~ # ps waux | grep 25387
root           25387  99.0  0.4   51432  34436  1  R+   09:50        2:15.77 /usr/local/bin/python3 /usr/local/opnsense/scripts/netflow/flowd_aggregate.py --console (python3.11)
root           85704   0.0  0.0    4524   1420  3  R+   09:54        0:00.00 grep 25387
root@opnsense1:~ # ps waux | grep 35195
root           35195 100.0  0.5   59848  38484  -  Rs   10Mar25  31202:26.20 /usr/local/bin/python3 /usr/local/opnsense/scripts/netflow/flowd_aggregate.py (python3.11)
root           85886   0.0  0.0   12720   1816  3  S+   09:54        0:00.00 grep 35195
root@opnsense1:~ # `

**Comment by jeffstearns** [comment]
I see the same error.  flowd.log grows without bound, filling /var/log.  The log file doesn't rotate; it just grows without bound.
OPNsense 26.7.1_1-amd64 FreeBSD 15.1-RELEASE-p1
```
Error flowd_aggregate.py
flowd aggregate died with message Traceback (most recent call last):
File "/usr/local/opnsense/scripts/netflow/flowd_aggregate.py", line 162, in run aggregate_flowd(self.config, do_vacuum) 
File "/usr/local/opnsense/scripts/netflow/flowd_aggregate.py", line 86, in aggregate_flowd stream_agg_object.cleanup(do_vacuum) 
File "/usr/local/opnsense/scripts/netflow/lib/aggregates/__init__.py", line 213, in cleanup self._update_cur.execute('vacuum') 
sqlite3.DatabaseError: database disk image is malformed
```
