### ISSUE TITLE
system/ntpd rate limit on by default, restrict: detach limited from kod

### ISSUE THREAD

**Issue by ZsZs73** [opnsense/core#5470]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues and I am convinced that mine is new.

**Is your feature request related to a problem? Please describe.**
I've learned it in the hard way that the rate limit is ON as per default NTPD configuration (both `restrict` and `restrict -6` commands have the flag`limit`). 
`limit` can be enabled/disabled only together with `kod` flag. 
See `/usr/local/etc/inc/plugins.inc.d/ntpd.inc`
```
375     if (empty($config['ntpd']['kod'])) { /*note: this one works backwards */
376         $ntpcfg .= ' kod limited';
377     }
```
IMHO the default rate limit very strict. The default `discard` allows `average` 32s (2^5) between two requests from the same source and the `minimum` between two requests is 4s (2^2) seconds according to the [ntp.conf manual](https://www.freebsd.org/cgi/man.cgi?query=ntp.conf)
Most of the modern clients have `server` parameter with `iburst` configured by default which triggers the default rate limit immediately.

**To Reproduce**

1. Go to 'Services / Network time'
2. Click on 'General'
3. Scroll down to 'Access restriction'
4. Click Advanced button
4. Check 'Enable Kiss-o'-death packets' checkbox
5. Result: 'kod limited' will be added to `restrict` and `restrict -6` commands of `/var/etc/ntpd.conf`
6. Uncheck ' Enable Kiss-o'-death packets' checkbox
7. Result: 'kod limited' will be removed from `restrict` and `restrict -6` commands of `/var/etc/ntpd.conf`

**Expected behavior**
- option 1: `limited` should have its own checkbox on the UI and it should be unchecked by default. Easy to implement.
- option 2: the optimal solution would be to make it possible to add multiple `restrict` and `restrict -6` lines with all possible flags shown. More complex to implement as it needs an array of checkboxes with mandatory (`default`) and optional networks.

Note 1: currently restrictions are getting applied to all clients (`restrict default` means: `restrict address 0.0.0.0  mask 0.0.0.0`, so any clients). The only way to add custom restrictions is to add complete `restrict` commands to the Advanced section of Services / Network Time / General which is not recommended.
Note 2: the _'These options control access to NTP from the WAN'_ label in the Access restriction section is misleading as restrictions get applied to source IPs and not to interfaces.

**Workaround**

As my firewall provides NTP service to local hosts only which are under my control I could disable rate limiting by unchecking 'Enable Kiss-o'-death packets'.

**Version**
OPNsense 21.7.7-amd64
FreeBSD 12.1-RELEASE-p21-HBSD
OpenSSL 1.1.1l 24 Aug 2021

I am aware of that NTP service does not belog to the core business of OPNsense, so the granularity provided by option 2 might sound overkill.

I am going to prepare an PR to address this. Please advise which option to implement.

update1: add checkboxes from the template

**Comment by ZsZs73** [comment]
Some humans might still be interested in this.

**Comment by fichtner** [comment]
@ZsZs73 it would still be nice to have the full template in the report (with the confirmation  checkboxes in particular)

I'd opt for option 1 to not introduce too much code into the static pages since eventually we need to migrate away from it to MVC. Is that something you are capable of submitting? I'm happy to review PR together.


Cheers,
Franco
