### ISSUE TITLE
PHP warnings on boot

### ISSUE THREAD

**Issue by zaroth** [opnsense/core#5476]
After rebooting OPNsense, the following bug report appears several times in the WebGUI. No visible issues at the first glance at least.

```PHP Warning:  in_array() expects parameter 2 to be array, null given in /usr/local/www/system_general.php on line 461```

System information:

```FreeBSD 12.1-RELEASE-p21-HBSD #0  04bde01a034(stable/21.7)-dirty: Mon Dec 13 09:07:56 CET 2021     root@sensey:/usr/obj/usr/src/amd64.amd64/sys/SMP amd64
OPNsense 21.7.7 3f5165238
Plugins os-acme-client-3.6 os-dmidecode-1.1_1 os-theme-cicada-1.28 os-wireguard-1.9 
OpenSSL 1.1.1l  24 Aug 2021
PHP 7.4.26
```

**Comment by kulikov-a** [comment]
config broken? no complaints about other lines like 47?

**Comment by 8191** [comment]
> config broken?

I also thought about that, but regardless of the configuration `$pconfig['dnsallowoverride_exclude']` should be a valid array:
https://github.com/opnsense/core/blob/88334b838a13c7083f5ad29044ff65d4bb5f14ba/src/www/system_general.php#L46-L50

The only way I can imagine that `$pconfig['dnsallowoverride_exclude']` is null in line 461 is, that the page was accessed with neither a GET nor a POST request, which is quite unlikely, I assume...

**Comment by 8191** [comment]
> config broken?

I also thought about that, but regardless of the configuration `$pconfig['dnsallowoverride_exclude']` should be a valid array:
https://github.com/opnsense/core/blob/88334b838a13c7083f5ad29044ff65d4bb5f14ba/src/www/system_general.php#L46-L50

The only way I can imagine that `$pconfig['dnsallowoverride_exclude']` is null in line 461 is, that the page was accessed with neither a GET nor a POST request, which is quite unlikely, I assume...

**Comment by kulikov-a** [comment]
> neither a GET nor a POST request

or `$config['system']['dnsallowoverride_exclude']` returns array somehow?

**Comment by zaroth** [comment]
@kulikov-a 

Nope, that error message seems to be the only thing going wrong in the error log. I looked again closer at it and it seems to be 3 occurences with 2 error messages every time:

![image](https://user-images.githubusercontent.com/840021/149637317-92bad61c-37f4-4eac-b6f2-5ededca9cb90.png)

**Comment by 8191** [comment]
@zaroth Did you open the corresponding page using your browser? Or are these log entries without user interaction?

**Comment by zaroth** [comment]
Unfortunately, it's hard to say now - I might very well have been modifying configuration at that time, even referring to DNS overrides, as recently I was updating my Unbound configuration in OPNsense. To check out if the issue still persists, I have restarted OPNsense today, navigated to all the tabs related to DNS I could think of, and there were no errors messages present in the dashboard this time.

**Comment by fichtner** [comment]
@kulikov-a so can be closed?

**Comment by kulikov-a** [comment]
@fichtner yep, reproduced with a syntax error in the Domain field and an empty "Exclude interfaces" list. https://github.com/opnsense/core/commit/68775a50e8980cfa4d88f476260e321e7008ee45 fixes this. so imho it's definitely fixed )

**Comment by fichtner** [comment]
Ok great 😊
