### ISSUE TITLE
Top Talkers gives duplicate total for Total In and Total Out

### ISSUE THREAD

**Issue by Codelica** [opnsense/core#5479]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X ] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [ X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

In the Traffic "Top Talkers" table, the "Total In" and "Total Out" statistics are always the *same* for a given address, rather than individual totals for in and out traffic:

![Top-Talkers](https://user-images.githubusercontent.com/386101/149673706-f55ec3e7-311f-4a65-984c-512765574e11.jpg)

**To Reproduce**

1. Enable Netflow statistics
2. Browse to Reporting -> Traffic -> Top Talkers
3. Allow data to gather and notice Total In = Total Out for each address

**Expected behavior**

Total In and Total Out should be separate statistics.

**Describe alternatives you considered**

No workarounds.

**Screenshots**

See above.

**Relevant log files**

N/A.

**Additional context**

Reported in the forums last summer:

https://forum.opnsense.org/index.php?topic=23768.0
https://forum.opnsense.org/index.php?topic=23163.0

And there was a GitHub issue for it that was auto-closed do to formatting.

**Environment**

Appears to have been a problem in at least 21.1, but I'm still seeing it in 22.1.r1 still.

**Comment by AdSchellevis** [comment]
https://github.com/opnsense/core/commit/cb73aa736d381ab395f2c34545d40d821d0a7100 should do the trick, thanks for reporting!
