### ISSUE TITLE
Dashboard CPU Current static

### ISSUE THREAD

**Issue by sepei** [opnsense/core#548]
Hi,

is the current CPU value static?
I all the time get:
Current: 274 MHz, Max: 2194 MHz
Just the current is wrong the rest is right (CPU-TYPE, Cores, ...).

**Comment by fichtner** [comment]
This is directly read from the kernel on refresh. Are you using powerd? Is your system busy?

It it's newer hardware it's probably not busy and thus ok.

**Comment by sepei** [comment]
Its an Vmware Virtual Maschine and Vsphere show me something different. First I though maybe just Vsphere is not so correct, but after I testet with Openvpn and AES-256CBC on a 200Mbit line and it would be a nice dream when only 274Mhz are needed for about 150 Mbit throughput :) 
On pfsense the value is correct. It is a fresh installed maschine so I dont know the first question. How I can look at that?

**Comment by fichtner** [comment]
Okay, thanks for the feedback. :)

You can double check on the console:

# sysctl dev.cpu.0.freq

Either the value is being cached by the statistics page response itself, or the value is indeed static.

Does pfSense run in the exact same environment, and if so, which version?

**Comment by sepei** [comment]
Hm on latest Version of pfsense sysctl dev.cpu.0.freq gives also 274 Mhz. Strange like 2 month ago where I did setup the Openvpn Clients at this VM and the cpu usage was correct. So I guess its an freebsd issue and has not really something todo with opnsense.

**Comment by fichtner** [comment]
Thanks for checking back... I can leave this open for a bit, see if I find some related info over the holidays.

**Comment by sepei** [comment]
In my opinion it should be closed because its not so important and also pfsense got also the issue. Better keep the focus on 16.1 :) Thanks for this great fork of pfsense. 
I only miss some addons and rrd graphs / bandwith monitoring.

**Comment by fichtner** [comment]
Plugins are definitely being populated in 2016. As for RRD, would you mind going to add your thoughts to https://forum.opnsense.org/index.php?topic=1852.0 -- I specifically want to know how System Health doesn't work for you and what we can do to change that. Thank you!
