### ISSUE TITLE
Systemhealth "wrong" interfacename on optional interfaces

### ISSUE THREAD

**Issue by sepei** [opnsense/core#549]
Hello again,

there is a Bug in the systemhealth page. Under packets / traffic there are the automaticaly created adapter names (opt1, opt2, op3). I renamed it after adding but on the health page there is still the old created ones.

**Comment by fichtner** [comment]
this duplicates #428, we are unsure how to properly change it :)

The gist is this: the database content is fixed, but the interface names may be changed in the GUI all the time tough. It's nice to have to map them, but it's not a priority.
