### ISSUE TITLE
DHCP client doesn't set fargw

### ISSUE THREAD

**Issue by jplitza** [opnsense/core#5493]
When a DHCP server replies with netmask /32, OPNsense doesn't correctly set the gateway (which is outside the "subnet"). Configuring this manually works fine.

Manually inserting `$thisconf['fargw'] = 1;` into this block makes it work via DHCP too:
https://github.com/opnsense/core/blob/68775a50e8980cfa4d88f476260e321e7008ee45/src/opnsense/mvc/app/library/OPNsense/Routing/Gateways.php#L242-L248

Obviously setting fargw should only happen when needed - which is why this isn't a PR... yet.

**Comment by fichtner** [comment]
Hi @jplitza,

That’s an interesting observation. I suppose detecting this is useful regardless of how it could be carried out (and when).

One thing to note about the far gateway setting is that it will stick to the configuration once saved (automatic gateway becoming a manual gateway). In that case if DHCP should lease a normal IP with same subnet gateway later on the setting would stick to it and maybe break connectivity (although I’m not sure).

Maybe dynamic gateways must overwrite this setting according to the detected situation?


Cheers,
Franco

**Comment by jplitza** [comment]
@fichtner TBH, I'm not even a user of OPNsense, so I'm not at all familiar with the concepts you mention ("automatic gateway becoming a manual gateway", "dynamic gateway") and the implications of the proposed change on them. I'm just looking into rolling out such a DHCP setup in our ISP network, and one of our customers is using OPNsense, so I dug into the code.

**Comment by fichtner** [comment]
Ok, no problem. Let me assign this and try to work on an out of the box solution.

Bit at least setting far gateway manually for your customers is an easy workaround to get it running.


Cheers,
Franco

**Comment by fichtner** [comment]
Proposal is in there to be released in 22.7 at the latest.
