### ISSUE TITLE
BaseField: Add __isset() magic method to prevent excessive typecasting

### ISSUE THREAD

**Issue by swhite2** [opnsense/core#5496]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**

When accessing model data via the intended internal methods, such as when using `iterateItems()`, accessing and interpreting an internal configuration node is made easy via the internal __get() method in `BaseField.php`. However, using `empty()` or `isset()` to determine whether a node contains a value is in this context only valid by typecasting the result, e.g. a `string`. A quick example:

https://github.com/opnsense/core/blob/af587e812a7b8d96cf3fd84869dc7e00bbfe09b3/src/opnsense/mvc/app/models/OPNsense/Firewall/Category.php#L136-L143
This is because the returned value is by definition a non-existing property of the `BaseField` class. The PHP docs state the following:

```
(https://www.php.net/manual/en/function.empty.php)
Empty(): (Return value)
Returns false if var exists and has a non-empty, non-zero value, aka falsey, see conversion to boolean. Otherwise returns true.
```
The assumption here is that the var exists, which is not the case since the node exists (or doesn't exist) only in the `internalChildnodes` array, not as part of the relevant class/base class. Therefore, `empty()` will always return true if directly called on a node without typecasting the result, even though it could actually be a proper string. This is also the case for `isset()`, though this could warrant further discussion.

I think this may already be going wrong in places. A first GitHub search result:
https://github.com/opnsense/core/blob/af587e812a7b8d96cf3fd84869dc7e00bbfe09b3/src/opnsense/mvc/app/models/OPNsense/Firewall/Alias.php#L110-L131
shows a non-typecasted result being fed into `empty()` - therefore I worry about the validity of this code. 

**Describe the solution you like**

If we dig deeper in the docs, we see that in these specific cases (a var is a non-existing property), empty() does the following:
```
__isset() is triggered by calling isset() or empty() on inaccessible (protected or private) or non-existing properties.
```
typecasting the result (and by extension easy-to-make mistakes with non-obvious side effects) can be avoided by overloading the `__isset()` magic method in `BaseField.php` as described here: https://www.php.net/manual/en/function.empty.php#93117. This tackles both `empty()` and `isset()`, since they both use the __isset() magic method if it is defined.

Thus a solution is:

```php
    public function __isset($name)
    {
        return isset($this->internalChildnodes[$name]);
    }
```

in https://github.com/opnsense/core/blob/master/src/opnsense/mvc/app/models/OPNsense/Base/FieldTypes/BaseField.php.

**Describe alternatives you considered**

None.

**Additional context**

None.

**Comment by AdSchellevis** [comment]
@swhite2 sounds like a good addition indeed, if you add a PR we can skim the code for the ones we currently cast statically (`grep -r 'empty((string)' src/`)

**Comment by swhite2** [comment]
> @swhite2 sounds like a good addition indeed, if you add a PR we can skim the code for the ones we currently cast statically (`grep -r 'empty((string)' src/`)

@AdSchellevis Would you like me to remove the static casts in the PR as well?

**Comment by AdSchellevis** [comment]
@swhite2 rather split it in two, one PR to extend the base class and one for using the new functionality.
