### ISSUE TITLE
RRD graphs are obnoxiously large

### ISSUE THREAD

**Issue by phillijw** [opnsense/core#55]
I find it difficult to read with the extra large size of these graphs. The pixelated image actually makes it harder to look at even though it's bigger and easier to see. I would suggest making these a bit smaller.

**Comment by StopTrain** [comment]
I'm in total agreement with this.

**Comment by cbasolutions** [comment]
Pull request submitted.

**Comment by fichtner** [comment]
Merged, thanks! :)
