### ISSUE TITLE
IPsec should prevent enabling duplicate Phase 2 remote subnet

### ISSUE THREAD

**Issue by nzkiwi68** [opnsense/core#5503]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**
I am migrating a larger site with 170+ site to site IPsec VPNs from another firewall to OPNsense. The clone an existing phase 1 entry and the extra check box "Clone phase2" is a huge help in creating so many tunnels.

I made a mistake with the cloned site to site VPN and forgot to alter the phase 2 tunnel remote subnet and enabled it. OPNsense allowed two IPsec site to site VPNs to start with duplicate phase 2 entries which should not be possible.

OPNsense on enabling any phase 2 tunnel should sanity check for any overlapping or duplicate remote subnets and refuse to start that phase 2 entry and write a useful log entry "Duplicate or overlapping phase 2 remote network detected - phase 2 xxxxx disabled"

**To Reproduce**
1. Create an IPsec phase 1 and phase 2 site to site VPN and enable it
2. Clone the above entry by clicking on clone phase 1 and select "Clone phase2"
3. Start the cloned IPsec tunnel and it's associated phase 2 entry
4. You will now have duplicate phase 2 entries running which will not work properly

**Expected behavior**
OPNsense on enabling any phase 2 tunnel should sanity check for any overlapping or duplicate remote subnets and refuse to start that phase 2 entry and write a useful log entry "Duplicate or overlapping phase 2 remote network detected - phase 2 xxxxx disabled"

**Describe alternatives you considered**
None

**Environment**
OPNsense 21.7.7

**Comment by AdSchellevis** [comment]
I'm not sure this is a good idea as duplicate tunnels are permitted, in which case you would need to compare the full phase 1 (source, destination, proposal) entry for an overlap (which also makes it less likely to ever trigger on a useful configuration mistake).

**Comment by nzkiwi68** [comment]
1. pfSense prevents the creation of duplicate phase 2 entries, which is actually kind of annoying. There are cases where you might want the remote the subnet of say 10.20.30.0/24 setup against two different IPsec SA, one standby for cold/warm failover. Also, I really like how OPNsense allows the cloning of a SA and the associated phase 2 but leaves the phase 2 disabled, it's great when you have to create a lot of very similar site to site VPN tunnels.

2. You don't need to compare phase 1 ever, just simply on enabling any phase 2, check for any existing and enabled over lapping phase 2.

3. Duplicate phase 2 tunnels are impossible. You cannot have traffic arriving at OPNsense LAN interface destined to a remote subnet of 10.20.30.0/24 and this be reachable via phase 1 SA xxx (and it's associated phase 2) and phase 1 SA yyy (and it's associated phase 2). How will the firewall decide which SA to route the traffic down? When inbound IPsec traffic arrives from 10.20.30.0/24 from say Phase 1 SA yyy, might the firewall answer via Phase 1 SA xxx? Surely this will result in asymmetric traffic. 

4.  The behavior I see would be:
On manually clicking to enable a phase 2, check if the remote subnet overlaps and if it does, don't enable it.
On starting up (normally IPsec service starting), each phase 2 that gets enabled in turn, checks for any existing phase 2 that overlaps and won't start phase 2 if it overlaps. This happens sequentially from the first SA to the last.

**Comment by nzkiwi68** [comment]
Ok!
I have gone off and read about how Strongwan does actually overlapping phase 2 subnets.
However, for that to be useful, you would need to support the StrongSwan  the priority of policies stuff and expose that functionality so that we could influence which phase 2 was preferred for routing.

Ultimately, it would be simpler to not allow duplicate phase 2 - otherwise it get messy fast.
