### ISSUE TITLE
[ui] Users -> All is weird

### ISSUE THREAD

**Issue by sjorge** [opnsense/core#551]
Perhaps renaming 'Users' top menu item to 'Users and Groups' and then renaming the 'All' sub-menu-item to 'Users' would make more sense?

**Comment by fichtner** [comment]
Users section has been renamed "Access Control", All was renamed to "Users" a week or so ago. We're shaping as fast as we can with all of those "weird" corners. All out with 15.7.23.

Most of the time the grouping is logical, but the flat hierarchy wasn't as flat as it could have been. That's only seen when we're done with this. :)

**Comment by sjorge** [comment]
Cool! I had a few minutes to spare so I'm giving the latest release another shake down.

**Comment by fichtner** [comment]
Sure, please do go on :)
