### ISSUE TITLE
MVC page using legacy config generation does not properly update service configuration

### ISSUE THREAD

**Issue by swhite2** [opnsense/core#5513]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

Right now the legacy restart/reconfigure(apply) buttons in the webgui do not function the same as the MVC restart/configure(apply) buttons. The MVC status widget actions and the reconfigure button assume that all configuration is generated via the template system, while the legacy restart/reconfigure actions configure *both* legacy and templated configuration data. Since it is sometimes necessary to prevent large pieces of logic cluttering up a template or minimizing impact, legacy config generation might be utilized instead, while the MVC model is used to do model validation and page rendering. Currently, this is the case for Unbound -> Overrides -> Host entries, which I migrated last week. 

The overall effect is that both applying and restarting the service from this MVC page (in this example Host Overrides) does not actually update the configuration in /var/unbound/* unless (from a users' perspective):
1. You restart the service from any legacy page.
2. You reboot the system.

Which in both case activate the relevant pluginctl hooks.

The question now becomes how we might do this correctly.

It seems https://github.com/opnsense/core/blob/master/src/opnsense/scripts/unbound/start.sh must always be called to properly start Unbound, which is called in both the MVC and legacy cases (https://github.com/opnsense/core/blob/master/src/etc/inc/plugins.inc.d/unbound.inc#L419 and https://github.com/opnsense/core/blob/master/src/opnsense/mvc/app/controllers/OPNsense/Base/ApiMutableServiceControllerBase.php#L187), so I suspect interference here is not necessary. I would say that overriding the reconfigureAction() method and calling a pluginctl hook in Unbounds' ServiceController might be a solution. This provides the added benefit of having a single legacy hook to signal that a transition in the future might be necessary. The downside is that it's not a generic solution - meaning one could add a host entry, switch to another MVC page for the same service and restart it from there, which would also not properly update the configuration.

Please correct me if I'm wrong in any of these statements @AdSchellevis @fichtner.

**To Reproduce**

1. Go to Unbound->Overrides->Host entries (default page)
2. Add a host entry
3. Click Apply and/or restart the service
4. Observe /var/unbound/host_entries.conf has not changed
5. Go to Unbound->General
6. Click apply and/or restart
7. Observe /var/unbound/host_entries.conf has updated correctly.

**Expected behavior**

I would expect the configuration file to properly update.

**Describe alternatives you considered**

None

**Screenshots**

None

**Relevant log files**

None

**Additional context**

None

**Environment**

OPNsense 21.7.a_1178-amd64 (amd64, OpenSSL).

**Comment by fichtner** [comment]
Yes, these differences exist due to the hybrid nature of the Unbound integration. Moving all to MVC would be the most consistent fix.

traditionally legacy services have a single configure function that does „templating“ and service restart/stop depending on the configuration.

the mvc code decoupled this behaviour.

**Comment by swhite2** [comment]
> Yes, these differences exist due to the hybrid nature of the Unbound integration. Moving all to MVC would be the most consistent fix.

Since legacy code is not to be used in the mvc code, I'm unsure of how to move forward for now unless we all agree to move the whole thing to a template.

**Comment by fichtner** [comment]
We should fix existing problems within this, but I think it works ok at the moment the way it is unless I’m missing something. As I said best way to deal with this is get rid of legacy code. That doesn’t mean we have to at this point in time. 😊

**Comment by swhite2** [comment]
Well, the main issue still remains, 'apply' and 'restart' basically does nothing in the hosts section. Whether or not this is a major issue is up to you of course :)

worst case scenario it might lead to some annoyance.

**Comment by fichtner** [comment]
Will take a closer look on Monday.
