### ISSUE TITLE
Post-22.1 errors from pkg during update check

### ISSUE THREAD

**Issue by shonjir** [opnsense/core#5515]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

Receiving I/O and permission errors for pkg repo cache files during update check since upgrade to 22.1.

To upgrade I first upgraded to 21.7.8, then I converted from UFS to ZFS during the 22.1 upgrade process.  It seems as if the repo cache files may not have correct permissions following config import.

**To Reproduce**

1.  Upgrade firewall from 22.7.8 (UFS) to 22.1 (ZFS) with configuration import.
2.  Run check for update process.  Errors will occur.

**Expected behavior**

Update check should not produce errors

**Describe alternatives you considered**

Considered manually changing permissions on pkg repo cache.   Cache databases are all owned by root with 644 permissions.

**Screenshots**

```
root@opnsense:/var/db # ls -l pkg
total 17686
-rw-r--r--  1 root  wheel       158 Jan 28 11:02 OPNsense.meta
-rw-r--r--  1 root  wheel       158 Jan 27 23:40 SunnyValley.meta
-rw-r--r--  1 root  wheel  14114816 Jan 28 11:02 local.sqlite
-rw-r--r--  1 root  wheel   1630208 Jan 25 01:36 repo-OPNsense.sqlite
-rw-r--r--  1 root  wheel    237568 Jan 27 23:40 repo-SunnyValley.sqlite
-r--r--r--  1 root  wheel   6968604 Jan 28 03:13 vuln.xml

```

![image](https://user-images.githubusercontent.com/11600703/151609282-1a91a897-0684-46b9-88eb-5c28fade6f18.png)

**Relevant log files**

See screenshot

**Additional context**

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 22.1-amd64
FreeBSD 13.0-STABLE
OpenSSL 1.1.1m 14 Dec 2021

**Comment by fichtner** [comment]
Sounds like a package database corruption of some sort. Note the database will not be cloned from the UFS system so it got corrupted from the install media maybe.

**Comment by shonjir** [comment]
That's possible.  Do you think I should just remove the package databases and let them rebuild?

**Comment by fichtner** [comment]
Rebuilding is a bit tricky. The least destructive way is moving the database to a different folder and running „opnsense-bootstrap“ utility without parameters to reinstall everything cleanly.

**Comment by shonjir** [comment]
Running `pkg update` from the command line produces no errors, and other `pkg` functions seem to be fine also.  `pkg check -s -n` produces no issues either, nor does `pkg upgrade -n`  (I'm using -n to avoid accidentally modifying the system while testing the pkgdb)

The system hasn't produced any new errors since the ones in the screenshot, but I'm at a loss to explain why.   I removed a plugin today (happened to be the etpro telemetry plugin) so maybe that fixed the database?

**Comment by fichtner** [comment]
Not sure but if not an operational issue give it some slack and keep this issue open for a bit longer? 😊

Cheers,
Franco

**Comment by shonjir** [comment]
It doesn't seem to be causing any issues.  I'll monitor and see what happens.

**Comment by shonjir** [comment]
The errors have not recurred since the last ones in the screenshot and things seem to be operating fine.  At this point I'm chalking it up to some transient post-upgrade behavior related to restoration after changing the filesystem.

I've not dug into the code but given the post-upgrade circumstances maybe the relevant code is missing a 'database exists' check before moving on to modification operations, and because of that more worrisome messages are generated than are really warranted.
