### ISSUE TITLE
Option to not have CARP VIPs automatically used by services

### ISSUE THREAD

**Issue by fraenki** [opnsense/core#5517]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**

I want what was already requested in #5086:

> For the purpose of running multiple services on same ports on different Virtual IPs, it would be nice to have an option to not have VIPs automatically used by the services running on that interface.

However, in #5086 this was only implemented for IP aliases, but not for CARP VIPs for unknown reason.

When adding/editing a VIP in `Interfaces: Virtual IPs: Settings` and switching "Mode" from "IP Alias" to "CARP", the option "Allow service binding" is not usable. Not sure if this is just an oversight or if there are reasons for not supporting it with CARP.

**Describe the solution you like**

The option "Allow service binding" should also be available for CARP VIPs.

**Describe alternatives you considered**

An alternative was proposed in #4554, but was rejected and #5086 was suggested instead.

**Additional context**

OPNsense 22.1

**Comment by fichtner** [comment]
Hi @fraenki,

I suppose nobody asked for it specifically. There was ample radio silence on much of our new features in 22.1 even during RC phase. 😉


Cheers,
Franco

**Comment by fichtner** [comment]
@fraenki one thing this changes is that CARP VIPs are now considered aliases for functions that require to pull a primary address from the system. I'm unsure this won't introduce any problems but at first glance it looks like an oversight to not have had CARP addresses in there. Let me know how that works for you.

**Comment by fichtner** [comment]
messed up commit so here is the offical patch plug:

    # opnsense-patch 973dfb1 add23ab

**Comment by fraenki** [comment]
@fichtner I've just tested it and it seems to work as expected. Thanks! No unwanted side-effects so far.

**Comment by fichtner** [comment]
@fraenki thanks, I suppose you have both carp and ipalias in use?

**Comment by fraenki** [comment]
@fichtner I only use CARP VIPs, so I haven't tested IP aliases.

**Comment by fichtner** [comment]
@fraenki ok no big deal... I was only curious. IP aliases look good from my end. Thanks a lot!
