### ISSUE TITLE
[ui] add/edit user 'Expiration date' field should be datepicker

### ISSUE THREAD

**Issue by sjorge** [opnsense/core#552]

**Comment by AdSchellevis** [comment]
We've removed the date picker because the old one isn't bootstrap compatible, we might want to import another one at some point. 
Any suggestions are welcome here.

**Comment by sjorge** [comment]
Last time I needed one I used: https://github.com/eternicode/bootstrap-datepicker, worked pretty well.

**Comment by AdSchellevis** [comment]
Looks nice, I will keep it in mind.
