### ISSUE TITLE
OS Routing table is not updated after a route has changed to another gateway.

### ISSUE THREAD

**Issue by brendanbank** [opnsense/core#5520]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guidelines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

I boot reconfigured routes it's applied correctly to the os routing table. But when I change the route to another gateway it is _not_ applied to the routing table. A workaround is to delete the route first and then re-apply. 

**To Reproduce**

I create to go 'System -> Routes -> Configuration' and I change one of my routes to a different Gateway.
I click on Save. And then on Apply 

I check the route via 'System -> Routes -> Status' and the route still points to the _Old_ Gateway.

**Expected behavior**

After changing the route I expect that the route points to the new gateway. 

**Workaround**

If you delete the route through 'System -> Routes -> Status' and reaply the route through 'System -> Routes -> Configuration'  the route is changed to the new gateway.

**Additional context**

The Interface is a separate virtual interface (vlan)

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 22.1 amd64 / OpenSSL 1.1.1m 14 Dec 2021
Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (4 cores, 8 threads)
Network Intel(R) I210 Flashless (Copper)

**Comment by AdSchellevis** [comment]
@brendanbank https://github.com/opnsense/core/commit/52d3e7c6768b1863ac8b91d8da43d39e5c7bd364 should fix the issue which apparently has been in OPNsense for ages.. 

Thanks for reporting, to patch from the console use:
```
opnsense-patch 52d3e7c
```
