### ISSUE TITLE
hardware offloads settings in 21.1

### ISSUE THREAD

**Issue by galibozek** [opnsense/core#5521]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

Following update to 22.1 default hardware offloads settings changed for VirtIO network device from disabled to enabled. Causing network performance problems on kvm/proxmox.

although the interface settings hardware offloads was disabled
![screenshot_20220129_135017](https://user-images.githubusercontent.com/70749001/151668026-5acbe2fc-e448-4236-934d-bfeea6b58784.png)
(it looks like the settings not applied)
```
# ifconfig
vtnet0:
...
 options=4c07bb<RXCSUM,TXCSUM,VLAN_MTU,VLAN_HWTAGGING,JUMBO_MTU,VLAN_HWCSUM,TSO4,TSO6,LRO,VLAN_HWTSO,LINKSTATE,TXCSUM_IPV6>
...
```

**To Reproduce**

1. Upgrade opnsense from 21.7.8 to 22.1 on kvm with virtio network device and disabled hardware offloads in interface settings

**Expected behavior**

Acceptance parameters from interface settings and disabled like it was in opnsense 21.7:

```
# ifconfig
vtnet0:
...
 options=4c00b8<VLAN_MTU,VLAN_HWTAGGING,JUMBO_MTU,VLAN_HWCSUM,VLAN_HWTSO,LINKSTATE,TXCSUM_IPV6>
...
```

**Workaround**

I have added:
`@reboot root ifconfig vtnet0 -rxcsum -txcsum -tso -lro`
to cron

**Environment**

OPNsense 22.1 (amd64, OpenSSL).
Proxmox 7 (Qemu/kvm 6.1)

**Comment by deku-m** [comment]
I had the same i went back to 21.7.8. 
It was also complaining about it that i need to adjust it for my vlan300 every time (is needed for WAN provider).

**Comment by AdSchellevis** [comment]
when `vtnet0` isn't assigned, it won't be altered anymore in 22.1 either, from the release notes:

> Media settings are no longer shown for non-parent interfaces and need to be set individually to take effect. This can introduce unwanted configuration due to previous side effects in the code. If the parent interface was not previously assigned please assign it to reapply the required media settings.

If this is your problem, just assign the interface and you should be good to go.

**Comment by deku-m** [comment]
> when `vtnet0` isn't assigned, it won't be altered anymore in 22.1 either, from the release notes:
> 
> > Media settings are no longer shown for non-parent interfaces and need to be set individually to take effect. This can introduce unwanted configuration due to previous side effects in the code. If the parent interface was not previously assigned please assign it to reapply the required media settings.
> 
> If this is your problem, just assign the interface and you should be good to go.

I myself dont really understand. 
VNET0 isnt used but vlan300 was already created underneath you say remove it?
As 300 is assigned to it...

**Comment by AdSchellevis** [comment]
Hardware settings belong to "physical" interfaces, so in order to apply them, you will need to have the parent device in your configuration. This is indeed different than what it was prior to 22.1 as noted in the release notes. (just assign+enable and leave addresses set to "None")

**Comment by muhlba91** [comment]
@galibozek @deku-m what kind of performance problems did you encounter? (i'm asking to figure out if my problem is related or not.)

i'm also running on proxmox and tried upgrading a few days ago but reverted back relatively quickly due to a dramatic break of routing performance.
i also need to use vlan for my wan connection but opnsense was able to reach full bandwidth (~50MB/s).
i was able to reach the full bandwidth when accessing opnsense via lan (e.g. download a huge file from opnsense to a local computer).
however, routing my lan into the internet resulted in a total breakdown of bandwidth - all computers who needed to route through opnsense only reached a total of 1MB/s max.

**Comment by galibozek** [comment]
@AdSchellevis assignment parent interface (and enable) solved the problem, maybe it is worth writing the relevant information in the interface settings tab (hardware offloads)

**Comment by AdSchellevis** [comment]
@galibozek sure, why not, added in https://github.com/opnsense/core/commit/f041bb8ceb3f35327f12b68071e76a0fec5e024e

**Comment by Miskerest** [comment]
@muhlba91 This is almost certainly the same issue I encountered in my Reddit post [here.](https://www.reddit.com/r/opnsense/comments/sgf54z/wan_speeds_on_lan_subnets_much_slower_after/?) 

Is the solution to break out each interface by VLAN in the hypervisor?
