### ISSUE TITLE
"latest.log" symlink not being re-created on "Reset Log Files"

### ISSUE THREAD

**Issue by curana** [opnsense/core#5524]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

When you click on "Reset Log Files" in "System > Settings > Logging", the symbolic link "latest.log" is not being re-created which can cause alerts e.g. in monit if you are monitoring the "latest.log" file/symlink.

**To Reproduce**

1. Go to 'System > Settings > Logging'
2. Click on 'Reset Log Files'
3. Check via terminal "/var/log/system/"
4. The symbolic link "latest.log" is gone and not re-created automatically. Via cronjob later it is though.

**Expected behavior**

Resetting the log files should remove all log files, create empty new ones (what it does) but also re-create the symbolic link "latest.log" at the same time and not wait for the hourly cronjob to run.

**Describe alternatives you considered**

n/a

**Screenshots**

n/a

**Relevant log files**

n/a

**Additional context**

n/a

**Environment**

OPNsense 22.1-amd64
FreeBSD 13.0-STABLE
OpenSSL 1.1.1m 14 Dec 2021

**Comment by AdSchellevis** [comment]
which more or less was one of my concerns in https://github.com/opnsense/core/issues/4993, you can't instantly add symlinks as you don't know which files are going to be there (files are created upon first usage in syslog-ng). I guess this is a side-affect we will have to live with unless syslog-ng adds another hook which will trigger us to know new files have arrived....

**Comment by curana** [comment]
> which more or less was one of my concerns in #4993, you can't instantly add symlinks as you don't know which files are going to be there (files are created upon first usage in syslog-ng).

I agree, but the naming convention is pretty clear, so we could just create a file ourselves and not have to wait for syslog-ng, right? We don't wait for a syslog-internal ID or something that we can't predict.

Or we just don't delete the latest file and just "clear" it? I think there should be possibilities.

**Comment by AdSchellevis** [comment]
Keeping the `latest.log` files on flush so they eventually link to a log file again is likely the easiest and most consistent fix, although it has downsides as well (leaving files which will never link to anything for example).  

I'll remove the support tag, but personally I don't plan to spend much time on the subject as I can already see the next tickets dropping in convincing me my initial concerns where correct.

**Comment by curana** [comment]
Ok, thanks.
