### ISSUE TITLE
- firewall floating rules which contain host aliases synchronized using xmlrpc (HA) synchronization are not working on secondary firewall

### ISSUE THREAD

**Issue by pcmediapear** [opnsense/core#5525]
Before you add a new report, we ask you kindly to acknowledge the following:
- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**
- firewall floating rules which contain host aliases synchronized using xmlrpc (HA) synchronization are not working on secondary firewall

**To Reproduce**
- install two (primary and secondary) firewalls with carp interface
- create firewall host alias with one or more IP addresses on primary firewall (for example IP used on clients in network behind firewalls)
- create firewall floating rule with before created host alias on primary firewall (for example for allowing DNS on firewall or internet)
- configure HA and synchronize alias and rule from primary to secondary firewall
- turn off (or disable carp on) primary firewall and check if rule is working on secondary (in our case if client behind firewall is able to reach DNS on firewall or internet)

**Expected behavior**
- floating rules with host aliases should work like on primary firewall

A clear and concise description of any alternative solutions or workaround you considered.
- define all rules without using aliases but maintaining will be too difficult

**Environment**
OPNsense 22.1-amd64 (same it was also on older version 21.7)
FreeBSD 13.0-STABLE
OpenSSL 1.1.1m 14 Dec 2021
KVM virtualization

**Comment by AdSchellevis** [comment]
Most common mistake in these cases is missing the restart action of the firewall from the master, either using the "restart all" button or per service.
![image](https://user-images.githubusercontent.com/9783985/151709448-02d0eecf-2a34-410f-9af0-dfb00c1f951f.png)

![image](https://user-images.githubusercontent.com/9783985/151709461-57c032ef-c40b-4df2-ae7e-bef087cb99eb.png)


The active state on the backup firewall is easy to inspect, just check if the rules are equal and if the current content of the alias is as expected (Firewall: Diagnostics: Aliases).

**Comment by pcmediapear** [comment]
restart of all services do not help
I have also tried to synchronize and reboot both firewalls multiple times but it also do not help

by inspecting of aliases on secondary firewall most of them return "No results found!"
seems that if in alias is used at least one IP from local IP range it does not work
for example geoip aliases or aliases with public IPs are displayed

by inspection of aliases on primary firewall all aliases are displayed correctly

recreating of aliases also not help

**Comment by AdSchellevis** [comment]
If these aliases depend on internet access (geoip and/or url sources), make sure the backup is able to access the source data. System logging will likely report errors when it's not able to download external content.

**Comment by pcmediapear** [comment]
geoip aliases are displayed correctly by inspection

but not most of aliases with manually defined IPs if these IPs are part of IP range used on firewall
for example if IP address on secondary firewall on LAN (carp) or VPN (wireguard) interface is 192.168.111.12 (carp IP 192.168.111.10) most of aliases with IPs within network 192.168.111.0/24 are not working

maybe same behavior is also on standard LAN interface without using carp

**Comment by AdSchellevis** [comment]
best check the logs if something is off, when both configurations look the same from the gui it doesn't really make sense if settings aren't applied properly.

**Comment by pcmediapear** [comment]
hello and sorry for delay

log from primary firewall:
![image](https://user-images.githubusercontent.com/10603554/153711073-3591fc29-b832-4d3c-9982-1d992db7186a.png)

log from secondary firewall:
![image](https://user-images.githubusercontent.com/10603554/153711192-28f2b2c2-1589-403e-bf68-7d1be0fd6031.png)

**Comment by AdSchellevis** [comment]
ok, now try to execute the following command on the secondary firewall:
```
/usr/local/opnsense/scripts/filter/update_tables.py 
```

**Comment by pcmediapear** [comment]
output:
```
root@secondary:~ # /usr/local/opnsense/scripts/filter/update_tables.py
Traceback (most recent call last):
  File "/usr/local/opnsense/scripts/filter/update_tables.py", line 131, in <module>
    alias_content = alias.resolve()
  File "/usr/local/opnsense/scripts/filter/lib/alias.py", line 236, in resolve
    undo_content = open(self._filename_alias_content, 'r').read()
  File "/usr/local/lib/python3.8/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb1 in position 1: invalid start byte
```

**Comment by AdSchellevis** [comment]
highly likely a local file corruption preventing alias reload, https://github.com/opnsense/core/commit/edeec7d621f899b789e24a7a08613dffa28d0bcf should fix it. removing all files in `/var/db/aliastables/` should fix it as well.

**Comment by pcmediapear** [comment]
after applying patch it works again :thumbsup:

thank you
