### ISSUE TITLE
LAGG is not working correctly

### ISSUE THREAD

**Issue by kabaga** [opnsense/core#5526]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [ x ] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [ x ] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**
I have an Intel x520-DA2 dual 10Gbps card. I have an LACP between the OPNsense and Mikrotik CRS320. Each Mikrotik interface is showing 10Gbps. However, the OPNsense LAGG interface is showing 2.85Gbps instead of 20Gbps
I have this issue since I started using OPNsense version 21.7.x. I noticed this when I was reviewing OPNsense via LibreNMS. When I was using VyOS and didn't have this problem.

This is what I got from LibreNMS polling.
```array (
    'ifName' => 'lagg0',
    'ifInMulticastPkts' => '712042',
    'ifInBroadcastPkts' => '0',
    'ifOutMulticastPkts' => '19739',
    'ifOutBroadcastPkts' => '0',
    'ifHCInOctets' => '534772543099',
    'ifHCInUcastPkts' => '388523597',
    'ifHCInMulticastPkts' => '712042',
    'ifHCInBroadcastPkts' => '0',
    'ifHCOutOctets' => '148403034269',
    'ifHCOutUcastPkts' => '194768742',
    'ifHCOutMulticastPkts' => '19739',
    'ifHCOutBroadcastPkts' => '0',
    'ifHighSpeed' => '2820',
    'ifPromiscuousMode' => 'false',
    'ifConnectorPresent' => 'true',
    'ifAlias' => '',
    'ifCounterDiscontinuityTime' => '0:0:00:00.00',
    'ifDescr' => 'lagg0',
    'ifAdminStatus' => 'up',
    'ifOperStatus' => 'up',
    'ifLastChange' => '0',
    'ifType' => 'ethernetCsmacd',
    'ifPhysAddress' => '0:1b:21:b9:f4:a0',
    'ifMtu' => '1500',
    'ifInErrors' => '0',
    'ifOutErrors' => '2660',
    'ifInDiscards' => '0',
    'ifOutDiscards' => '0',
  ),
```
This is the ifconfig from OPNsense.
```
ifconfig -vv ix0
ix0: flags=28963<UP,BROADCAST,RUNNING,PROMISC,SIMPLEX,MULTICAST,PPROMISC> metric 0 mtu 1500
	options=4f03f2b<RXCSUM,TXCSUM,VLAN_MTU,JUMBO_MTU,TSO4,TSO6,LRO,WOL_UCAST,WOL_MCAST,WOL_MAGIC,NETMAP,RXCSUM_IPV6,TXCSUM_IPV6,NOMAP>
	ether 00:1b:21:b9:f4:a0
	media: Ethernet autoselect (10Gbase-Twinax <full-duplex,rxpause,txpause>)
	status: active
	nd6 options=29<PERFORMNUD,IFDISABLED,AUTO_LINKLOCAL>
	plugged: SFP/SFP+/SFP28 Unknown (Copper pigtail)
	vendor: OEM PN: SFP-H10GB-CU1M SN: CSS11J51828 DATE: 2019-05-01

ifconfig -vv ix1
ix1: flags=28963<UP,BROADCAST,RUNNING,PROMISC,SIMPLEX,MULTICAST,PPROMISC> metric 0 mtu 1500
	options=4f03f2b<RXCSUM,TXCSUM,VLAN_MTU,JUMBO_MTU,TSO4,TSO6,LRO,WOL_UCAST,WOL_MCAST,WOL_MAGIC,NETMAP,RXCSUM_IPV6,TXCSUM_IPV6,NOMAP>
	ether 00:1b:21:b9:f4:a0
	hwaddr 00:1b:21:b9:f4:a1
	media: Ethernet autoselect (10Gbase-Twinax <full-duplex,rxpause,txpause>)
	status: active
	nd6 options=29<PERFORMNUD,IFDISABLED,AUTO_LINKLOCAL>
	plugged: SFP/SFP+/SFP28 Unknown (Copper pigtail)
	vendor: OEM PN: SFP-H10GB-CU1M SN: CSS11J51972 DATE: 2019-05-01

ifconfig -vv lagg0
lagg0: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500
	description: LAN
	options=4f03f2b<RXCSUM,TXCSUM,VLAN_MTU,JUMBO_MTU,TSO4,TSO6,LRO,WOL_UCAST,WOL_MCAST,WOL_MAGIC,NETMAP,RXCSUM_IPV6,TXCSUM_IPV6,NOMAP>
	ether 00:1b:21:b9:f4:a0
	laggproto lacp lagghash l2,l3
	lagg options:
		flags=94<USE_NUMA,LACP_STRICT,LACP_FAST_TIMO>
		flowid_shift: 16
	lagg statistics:
		active ports: 2
		flapping: 10
	lag id: [(8000,00-1B-21-B9-F4-A0,0172,0000,0000),
		 (FFFF,74-4D-28-57-36-D5,0021,0000,0000)]
	laggport: ix0 flags=1c<ACTIVE,COLLECTING,DISTRIBUTING> state=3f<ACTIVITY,TIMEOUT,AGGREGATION,SYNC,COLLECTING,DISTRIBUTING>
		[(8000,00-1B-21-B9-F4-A0,0172,8000,0001),
		 (FFFF,74-4D-28-57-36-D5,0021,00FF,0001)]
	laggport: ix1 flags=1c<ACTIVE,COLLECTING,DISTRIBUTING> state=3f<ACTIVITY,TIMEOUT,AGGREGATION,SYNC,COLLECTING,DISTRIBUTING>
		[(8000,00-1B-21-B9-F4-A0,0172,8000,0002),
		 (FFFF,74-4D-28-57-36-D5,0021,00FF,0002)]
	groups: lagg
	media: Ethernet autoselect
	status: active
	nd6 options=29<PERFORMNUD,IFDISABLED,AUTO_LINKLOCAL>

```
Under FRR, it shows it is 20Gbps.
```
show interface lagg0
Interface lagg0 is up, line protocol is up
  Link ups:      12    last: 2022/01/31 00:45:22.96
  Link downs:    11    last: 2022/01/31 00:42:59.80
  vrf: default
  index 11 metric 1 mtu 1500 speed 20000 
  flags: <UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST>
  Type: Ethernet
  HWaddr: 00:1b:21:b9:f4:a0
  Interface Type Other
  Interface Slave Type None
    input packets 388940977, bytes 534819806617, dropped 0, multicast packets 715567
    input errors 0
    output packets 195616571, bytes 149543758476, multicast packets 19818
    output errors 2660
    collisions 0
```
Here is the LAGG settings. https://imgur.com/a/Fllutp1

I tried to install pfSense with the same config and LibreNMS was reporting it was 4Gbps.

**To Reproduce**

I am not sure it is always been like this since my installation.

**Expected behavior**

The LAGG interface should be reporting as 20Gbps and not 2.85Gbps.

**Describe alternatives you considered**

N/A

**Screenshots**

Provided above

**Relevant log files**

N/A

**Additional context**

N/A

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 22.1-amd64
FreeBSD 13.0-STABLE
OpenSSL 1.1.1m 14 Dec 2021

https://bsd-hardware.info/?probe=bab9a21997

**Comment by kabaga** [comment]
Do we have any updates or idea what is going on?
I purchased new sets of 10Gbps transceivers and replaced the DAC that I was using, but no changes. 

```
ix1: flags=28963<UP,BROADCAST,RUNNING,PROMISC,SIMPLEX,MULTICAST,PPROMISC> metric 0 mtu 1500
	options=4f03f2b<RXCSUM,TXCSUM,VLAN_MTU,JUMBO_MTU,TSO4,TSO6,LRO,WOL_UCAST,WOL_MCAST,WOL_MAGIC,NETMAP,RXCSUM_IPV6,TXCSUM_IPV6,NOMAP>
	ether 00:1b:21:b9:f4:a0
	hwaddr 00:1b:21:b9:f4:a1
	media: Ethernet autoselect (10Gbase-SR <full-duplex,rxpause,txpause>)
	status: active
	nd6 options=29<PERFORMNUD,IFDISABLED,AUTO_LINKLOCAL>
	plugged: SFP/SFP+/SFP28 10G Base-SR (LC)
	vendor: OEM PN: SFP-10G-SR SN: CSG101L31421 DATE: 2021-03-05
	module temperature: 47.06 C voltage: 3.33 Volts
	lane 1: RX power: 0.62 mW (-2.06 dBm) TX bias: 7.22 mA

```

**Comment by AdSchellevis** [comment]
likely a driver issue, best scout https://bugs.freebsd.org/bugzilla/ or report an issue there. Unfortunately `ix` isn't Intel's best, the 700 series (ixl) are way less problematic in our experience.

**Comment by kabaga** [comment]
According to https://bsd-hardware.info/?id=pci:8086-10fb-108e-7b11 it is supported. What is the best 10G cards that are compatible with OPNsense?
Do you have specific models?

**Comment by AdSchellevis** [comment]
Intel 700 series (`ixl`) are quite good in our experience as mentioned before, `ix` (500 series) works, but we have seen more issues to be honest (such as https://github.com/opnsense/src/commit/1c99b63a2ba211773159c1580836d3999d687db5).

**Comment by ToasterInWater** [comment]
We have the same problem with a 4*10G lagg and on Observium SNMP it only shows a lagg at 1.35Gb, this is a value that varies from time to time but I never seen it go above 3Gb.
On the switch side the lagg is shown to be at 40Gb on SNMP Observium as well as in cli.
The NIC is intel x710 DA4.
The switch DELL N4032F.
LACP IEEE 802.3ad.

OPNSense is the 22.1.5-AMD64 version. 

Does anyone have an idea where the problem is coming from ?

**Comment by kabaga** [comment]
I gave up on this. I bought a Chelsio card and it worked. I guess OPNsense does not support Intel cards. It can only see it, but cannot use it fully. However, with pfSense, the same card that I have shows higher speed/bandwidth and throughput compared to OPNsense, but not at 10Gbps
