### ISSUE TITLE
Auto-generated firewall rules block IPv6 link local (fe80::/10) to multicast traffic (ff02::/16)

### ISSUE THREAD

**Issue by jonathonwiebe** [opnsense/core#5528]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [ x ] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [ x ] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

The auto-generated firewall rules allow for all IPv4+6 traffic from `LAN net` to `*`, but as `fe80::/10` isn't part of `LAN net`, IPv6 link-local multicast traffic is blocked as per the example from the firewall log:
`LAN		Dec 31 09:16:25	[fe80::199b:4bd7:2e6f:441c]:65055	[ff02::c]:3702	udp	Default deny rule`

Similar (but not identical) problems have been fixed under issue opnsense/core#4028.

Blocking this traffic may also cause issues for Apple mDNS clients as there is no allowed traffic from `fe80::/10` to `ff02::FB`, but I do not have a device to reproduce.

**To Reproduce**

1. From a Windows device, open File Explorer (triggers WSD discovery multicast)
2. Check firewall logs for blocked traffic

**Expected behavior**

An auto-generated rule for LAN interface for `fe80::/10` <> `ff02::/16` traffic should be added, without this rule, devices fail over to IPv4 multicast instead of using IPv6.

**Describe alternatives you considered**

Specific ports could be allowed (like the `DHCPv6 allow rule`) vs allowing `* link-local multicast`, but this doesn't match the expected behavior compared to local multicast in the current IPv4 rules.

`fe80::/10` packets should never route past the local link so there should be no additional security risk.

**Screenshots**

**Relevant log files**

If applicable, information from log files supporting your claim.

**Additional context**

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 21.7.7-amd64
FreeBSD 12.1-RELEASE-p21-HBSD
OpenSSL 1.1.1l 24 Aug 2021

**Comment by fichtner** [comment]
This is too much effort to unclog in pf(4) so we will add an automatic rule for the firewall.

**Comment by fichtner** [comment]
[c7e67c6](https://github.com/opnsense/core/commit/c7e67c6752ec79a4a059686ed5a08f3f0d01153c) includes link-local via network selector on IPv6 rules which should fix this for all use cases, even existing default pass rules.


Cheers,
Franco
