### ISSUE TITLE
PF ruleset optimization and labels

### ISSUE THREAD

**Issue by kulikov-a** [opnsense/core#5529]
Hi!
Paying attention to the output of the `pfctl -vvsr` command, i got the impression that for some reason rules were not optimized (specially created duplicate rules or rules that are a subset of others fall into the final set of rules regardless of the `ruleset-optimization` value or `pfctl -o` flag value).
Creating a debug rules file and removing the `label` parameter from the rules seems to make the optimizer work.
Could this line be the reason?
https://github.com/opnsense/src/blob/5b292547700ec25c23d0bf2d0f2563a2fc0be10d/sbin/pfctl/pfctl_optimize.c#L112

and if it is (and OPNsense uses rules labels internally) may it be omitted from BARRIER set?)

Thanks!

upd:
Hah! only now I have read this part of the man more carefully)
```
           If per-rule accounting is important for
	   billing purposes or whatnot,	either the ruleset optimizer should
	   not be used or a label field	should be added	to all of the account-
	   ing rules to	act as optimization barriers.
```

**Comment by AdSchellevis** [comment]
@kulikov-a transferred the ticket to core as the barrier has been there before (https://github.com/freebsd/freebsd-src/blob/release/12.1.0/sbin/pfctl/pfctl_optimize.c#L111) and it's highly unlikely anything good will come out of it. So we're going to remove the option to simplify things.

**Comment by kulikov-a** [comment]
@AdSchellevis sad but reasonable. thanks!
