### ISSUE TITLE
Add "iftop" to the Firewall's Diagnostic section

### ISSUE THREAD

**Issue by tofazzz** [opnsense/core#5534]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**
No problems

A clear and concise description of what the problem is including your motivation for the request,
i.e. "For the purpose of [...] I am missing a solution that will [...]."

For the purpose of monitoring connections/traffic on a specific interface, it would be possible to have "iftop" as a tool under Firewall -> Diagnostic? Maybe with the option to select the interface with a drop-down menu that it will re-lunch "iftop" with the correct "-i" flag value. Since "iftop" is already installed and it would be very useful to have it handy in the GUI.

**Describe the solution you like**
"iftop" as a diagnostic tool under the "Firewall" section

(e.g. I would like an input field in the `/ui/firewall/alias` which would add .... to ....)

**Describe alternatives you considered**

A clear and concise description of any alternative solutions or features you considered.

**Additional context**

Add any other context or screenshots about the feature request here or links to relevant forum thread or similar

**Comment by AdSchellevis** [comment]
that would be `Reporting: Traffic` as a user friendly interface

https://github.com/opnsense/core/blob/277ffb6ac50010e17d2daff6aad72672ff2ecdef/src/opnsense/scripts/interfaces/traffic_top.py#L44
