### ISSUE TITLE
Is there a way to manually adjust state timeouts?

### ISSUE THREAD

**Issue by Danny2100** [opnsense/core#5543]
**Important notices**

Our forum is located at https://forum.opnsense.org , please consider joining discussions there in stead of using GitHub for these matters.

Before you ask a new question, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

I see that on pfsense you can manually adjust specific state timeouts rather than changing all the values using the "firewall optimization" setting. However I don't see that setting on opnsense.

I think it probably makes sense if it's possible to adjust 3 state timeouts I should do that rather than changing the setting from "normal" to "conservative" which changes a lot of timeout settings. 

https://forum.netgate.com/topic/116472/guide-manually-adjusting-state-timeouts-for-sensitive-services-e-g-voip

I'm having some issues with wifi calling and changing this would be helpful.

```
udp.first                   300s
udp.single                  150s
udp.multiple                900s
```

**Comment by nerlins** [comment]
Seriously, devs, you can't answer this person's question? I am having the same issue and have the exact same question.

**Comment by AdSchellevis** [comment]
The forum is better suitable for discussions, timeouts can't be set manually, the requested ones are the defaults for `conservative` optimization.

https://github.com/opnsense/core/blob/657265a410389394cddccf2cda8138fc82513af7/src/etc/inc/filter.inc#L389-L394

**Comment by nerlins** [comment]
Appreciate the quick response. Not the answer I think both of us were hoping for, but, at least there is an answer to the question.

**Comment by Danny2100** [comment]
> Appreciate the quick response. Not the answer I think both of us were hoping for, but, at least there is an answer to the question.

Yep I thought it could conserve CPU mostly by only adjusting timeouts for those 3 not adjusting all state timeouts by using ```conservative```. Does it only adjust 3 timeouts when changing to ```conservative``` as that's what the code appears to be doing.

From pfsense ```conservative``` is this

```
tcp.first                  3600s
tcp.opening                 900s
tcp.established          432000s
tcp.closing                3600s
tcp.finwait                 600s
tcp.closed                  180s
tcp.tsdiff                   60s
udp.first                   300s
udp.single                  150s
udp.multiple                900s
icmp.first                   20s
icmp.error                   10s
other.first                  60s
other.single                 30s
other.multiple               60s
frag                         30s
interval                     10s
adaptive.start           120000 states
adaptive.end             240000 states
src.track                     0s
```
https://forum.netgate.com/topic/116472/guide-manually-adjusting-state-timeouts-for-sensitive-services-e-g-voip

**Comment by nerlins** [comment]
@AdSchellevis 
> The forum is better suitable for discussions, timeouts can't be set manually, the requested ones are the defaults for `conservative` optimization.
> 
Can we think of this as a feature request, then?

@Danny2100  If you feel like it, jump over to this post on the forum. You say conservative fixed the issue for you, and I bet others would like to hear about it. Conservative has still not fixed the issue for me.

https://forum.opnsense.org/index.php?topic=27588.0
