### ISSUE TITLE
Internal certificates missing subjectAltName

### ISSUE THREAD

**Issue by nicoulaj** [opnsense/core#5544]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

Using the cert manager UI, generating internal certificates used to produce certificates including the `subjectAltName` field, eg:
```
subjectAltName=DNS:foo.tld,URI:https://foo.tld, emailAddress=foo@foo.tld, ST=Foo, O=Foo, L=Foo, CN=foo.tlf, C=FOO
```

But since a 21.x release, the "Alternative Names" form field started to be ignored:
```
emailAddress=foo@foo.tld, ST=Foo, O=Foo, L=Foo, CN=foo.tlf, C=FOO
```

I don't know which 21.x release broke it for sure, but it was one released before 26 May 2021, which leaves 21.1 to 21.1.6.

**To Reproduce**

1. Go to System > Trust > Certificates
2. Click on '+'
3. Generate an internal certificate with some values on "Alternative Names"
4. See certificate missing `subjectAltName` in the UI

**Comment by kulikov-a** [comment]
>  which 21.x release broke it for sure

21.1.5 IIRC
sorry, why do you think that the `subjectAltName` extension should be present in the `DN` value?
`subjectAltName` should be present in` X509v3 extensions` if you hit "info" button

**Comment by nicoulaj** [comment]
My mistake, a misconfiguration on my reverse proxy got me confused, the certificates generated by OPNsense are perfectly fine. Thanks for pointing me at #4761 anyway!
