### ISSUE TITLE
Incorrect reverse ip6.arpa zone for DHCPv6 registration in DNS

### ISSUE THREAD

**Issue by guidodo** [opnsense/core#5545]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

The reverse zone is being incorrectly set in the configuration file /var/dhcpd/etc/dhcpdv6.conf if it ends with a zero. Instead of being configured as a reverse for the zone 1234:5678:abcd:10::/64, a configuration is being created for the reverse zone of 1234:5678:abcd:10::/60.

**To Reproduce**

1. Have an interface configured with 1234:5678:abcd:10::/64
2. Go to 'Interfaces' -> 'LAN'
3. Configure the interface with the static IPv6 1234:5678:abcd:10::1/64
4. Go to 'Services' -> 'DHCPv6' -> 'LAN'
5. Check 'Enable DHCPv6 server on LAN interface'
6. Configure a range from '1234:5678:abcd:10:1234:abcd:0:0' to '1234:5678:abcd:10:1234:abcd:ffff:ffff'
7. Scroll down to 'Dynamic DNS'
8. Click 'Advanced'
9. Check 'Enable registration of DHCP client names in DNS.'
10. Set name of forward zone, set IPv6 of DNS server, set key name and password as configured on DNS server
11. Save settings
12. Log in to OPNsense over SSH
13. Verify configuration in /var/dhcpd/etc/dhcpdv6.conf

**Expected behavior**

Expected OPNsense to configure zone 0.1.0.0.d.c.b.a.8.7.6.5.4.3.2.1.ip6.arpa. as this corresponds to the devices network settings of 1234:5678:abcd:10::/64. OPNsense erroneously configures the zone 1.0.0.d.c.b.a.8.7.6.5.4.3.2.1.ip6.arpa. instead.

**Describe alternatives you considered**

Manually editing /var/dhcpd/etc/dhcpdv6.conf on the console instead of relying on GUI.

**Additional context**

A /48 range has been assigned (ex. 1234:5678:abcd::/48). This range is being divided in /64 assigned to the interfaces. Among these 1234:5678:abcd:10::/64 and 1234:5678:abcd:15::/64 have been configured. DHCPv6 has been activated to register IPv6 addresses automagically in DNS. For this the option 'registration of DHCP client names in DNS' has been enabled. The reverse zone for the ::15::/64 is being set up correctly, whereas the ::10::/64 is being misconfigured.

Good result: zone 5.1.0.0.d.c.b.a.8.7.6.5.4.3.2.1.ip6.arpa.
Wrong result: zone 1.0.0.d.c.b.a.8.7.6.5.4.3.2.1.ip6.arpa.

Afterthought: it would be nice if DHCPv6 could be configured to write the reverse PTR into the zone d.c.b.a.8.7.6.5.4.3.2.1.ip6.arpa (i.e. a single zone for the full /48)

**Environment**

This has been seen on versions 21.7.7 and 22.1. I haven't tested earlier versions.

OPNsense 22.1-amd64
FreeBSD 13.0-STABLE
OpenSSL 1.1.1m 14 Dec 2021

**Comment by fichtner** [comment]
@guidodo Can you point me to the code line in question? I'm not entirely sure about it.


Thanks,
Franco

**Comment by guidodo** [comment]
@fichtner I believe the code line in question is at line 1511 of /usr/local/etc/inc/plugins.inc.d/dhcpd.inc

`            foreach ($revsubnet as $octet) {`
`                if ($octet == "0") {`
`                    array_shift($revsubnet);`

This seems to ignore the netmask and simply keep dropping all nibbles that are set to "0".

I have attached two patches:
- a fully working quick patch which is suitable for netmasks that align with the nibble boundaries; it also works for unaligned netmasks, although the correct way would be to configure multiple reverse zones;
- a pseudo patch that calculates the required multiple reverse zones for unaligned netmasks; the calculation is fully working, however as this changes the result from a single string into an array of strings, it will require further changes in other parts of the code.

[Pseudo_Patch.txt](https://github.com/opnsense/core/files/8017889/Pseudo_Patch.txt)
[Quick_Patch.txt](https://github.com/opnsense/core/files/8017890/Quick_Patch.txt)
