### ISSUE TITLE
Interface VLAN value not respected VS parent interface

### ISSUE THREAD

**Issue by RedVortex** [opnsense/core#5546]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [ X ] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [ X ] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

(Previous issue was closed without a fix as we couldn't identify exactly where the problem was : https://github.com/opnsense/core/issues/4032)

**Describe the bug**

The MTU value in the VLAN interface configuration isn't respected when it is the same as the parent interface and defaults to 1500.

This is not a new bug for 22.1, it was already not working in previous versions but I don't know when this issue started to happen. It used to work some time ago however.

**To Reproduce**

Interface (ix1) MTU is configured at 9000. Vlan (ix1_vlan420) is also configured at 9000.

After saving, applying and even rebooting. The interface (ix1) is 9000 in overview. But the vlan (ix1_vlan420) is only 1500.

This seems to happen when the interface and the vlan interface have the same MTU. When that happens, it looks like the vlan defaults to 1500, instead of what is configured in the UI.

If I put let's say 9000 on ix1 and 8999 on ix1_vlan420. 8999 is now applied properly to the vlan, I see 8999 on the vlan in overview. If I put 9000 again on the vlan, the vlan now goes back 1500.

**Expected behavior**

VLAN MTU should be what is configured in UI

**Describe alternatives you considered**

No workaround besides going in the command line to manually set the VLAN interface MTU

**Screenshots**

UI configs
![image](https://user-images.githubusercontent.com/13983955/152658427-3978f89a-1a46-41c2-88b3-759478f63e80.png)
![image](https://user-images.githubusercontent.com/13983955/152658454-8175b05c-a09a-440c-9e50-7d974bd47c28.png)
![image](https://user-images.githubusercontent.com/13983955/152658472-d20ddc37-46c6-483e-a25a-26f3f127f2a9.png)

ifconfig
`ix1: flags=8863<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 9000
	description: ix1`

`ix1_vlan420: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500
	vlan: 420 vlanproto: 802.1q vlanpcp: 0 parent interface: ix1`

config.xml
`    <opt2>
      <if>ix1_vlan420</if>
      <descr>SRV</descr>
      <enable>1</enable>
      <lock>1</lock>
      <spoofmac/>
      <mtu>9000</mtu>
      <ipaddr>192.168.42.1</ipaddr>
      <subnet>24</subnet>
    </opt2>
`
`
    <opt7>
      <if>ix1</if>
      <descr>ix1</descr>
      <enable>1</enable>
      <lock>1</lock>
      <spoofmac/>
      <mtu>9000</mtu>
    </opt7>
`

**Relevant log files**

None

**Additional context**

None

**Environment**

OPNsense 22.1-amd64
FreeBSD 13.0-STABLE
OpenSSL 1.1.1m 14 Dec 2021

NIC: Intel X520 dual SFP+

**Comment by fichtner** [comment]
@RedVortex the kernel was playing tricks on us not erroring out on setting an impossible MTU on the VLAN first (9000) during boot while the parent wasn't yet configured. Can you try 6866efff70f?

    # opnsense-patch 6866efff70f


Cheers,
Franco

**Comment by RedVortex** [comment]
Works perfectly with this patch, @fichtner !

I tested by simply re-saving the bad MTU vlan interface and the MTU got updated right away to what it should be (9000).

I also rebooted completely to make sure everything works well with the patch. Both the parent and vlan interfaces have the right MTU also on bootup. So updating the interface and rebooting both work.

`ix1: flags=8863<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 9000
	description: ix1`

`ix1_vlan420: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 9000
	vlan: 420 vlanproto: 802.1q vlanpcp: 0 parent interface: ix1`

Thanks a lot for this fix, it seems like you nailed it !

**Comment by fichtner** [comment]
Hopefully... I can't move this to 22.1.1 at the moment for risk of regression but it should be good for 22.1.2. Trying to follow up on the old issue with a patch to gather more feedback.

Looks like I wasn't correct about silent errors, but in any case the errors that were there do not occur any longer.

Thanks again for the report. ❤️ 


Cheers,
Franco

**Comment by RedVortex** [comment]
@fichtner should this issue be re-opened for a future fix since it was rolled back, I think ? Or maybe it is scheduled for a later release ?

To be clear, this is still an issue for 22.1.3 riught now but the patch we tested in 22.1 worked well.

Thanks,
Patrick

**Comment by fichtner** [comment]
@RedVortex it's not on 22.1.3 indeed. We were waiting to batch VLAN changes into 22.1.4.


Cheers,
Franco
