### ISSUE TITLE
Unbound: DHCP registration does not sanitize names causing unbound to fail

### ISSUE THREAD

**Issue by bimbar** [opnsense/core#5550]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

Some weird chinese phone got a DHCP lease and it killed the Unbound service.

**To Reproduce**

Get a device with a weird name into your dhcp leases.

**Expected behavior**

I think the synchronization should make the name DNS compatible.

**Relevant log files**

2022-02-07T09:04:31 | unbound[45196] | [45196:0] fatal error: Could not set up local zones
2022-02-07T09:04:31 | unbound[45196] | [45196:0] error: Bad local-data RR MI8Lite-...int.xxx.xx IN A 172.28.25.230 
2022-02-07T09:04:31 | unbound[45196] | [45196:0] error: error parsing local-data at 11 'MI8Lite-...int.xxx.xx IN A 172.28.25.230': Empty label

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 21.10.2 (amd64, OpenSSL).

**Comment by AdSchellevis** [comment]
Can you share the strings written for this host in `/var/unbound/dhcpleases.conf`?

**Comment by bimbar** [comment]
local-data-ptr: "172.28.25.230 MI8Lite-...int.xxx.xx"
local-data: "MI8Lite-...int.xxx.xx IN A 172.28.25.230"

**Comment by AdSchellevis** [comment]
do you know what the actual name is? I expect something like `MI8Lite-` followed by Chinese characters, which are replaced with a point (`.`)

**Comment by bimbar** [comment]
I don't think I can find out the actual name.

**Comment by nblomquist** [comment]
I am also getting this failure. It totally locks up my opnsense router, to the point that I need to reboot the box. Unbound then fails to start and I can go in and untick the Register DHCP Leases box.

Here is the entries from /var/unbound/dhcpleases.conf
```
local-data-ptr: "172.28.1.109 onn..localdomain"
local-data: "onn..localdomain IN A 172.28.1.109"
```

I don't see anything in the opnsense page to point to 'onn****'.

![image](https://user-images.githubusercontent.com/4588867/160904195-2411d7ed-f425-4daf-ab58-01588e99b809.png)

**Comment by AdSchellevis** [comment]
@nblomquist I probably need the lease info from `/var/dhcpd/var/db/dhcpd.leases`,  if you can share the lease for this host that would be helpful.

**Comment by nblomquist** [comment]
Here is the lease object from that file.

```
lease 172.28.1.109 {                  
  starts 5 2022/03/25 22:29:47;       
  ends 6 2022/03/26 00:29:47;         
  tstp 6 2022/03/26 00:29:47;         
  cltt 5 2022/03/25 22:29:47;         
  binding state free;                 
  hardware ethernet f0:a3:b2:XX:XX:XX;
}   
```                                  

I have XXed out the mac. If you need that I can PM or something.

I am not even sure what device this is. The lease is from the 25th.

**Comment by nblomquist** [comment]
I figured out the device.
It is an `onn.` branded Roku TV.
The brand actually contains the period ( . ).

I wonder if the client is sending back a hostname or something of `onn.` Which then gets concatenated with another period to create `onn..localdomain`.

**Comment by nblomquist** [comment]
Interesting piece about special characters:

https://community.roku.com/t5/Network-Wireless-Wired-Connections/Roku-Onn-50-Inch-TV-wont-connect-SOLVED/td-p/624409

https://forums.tomshardware.com/threads/connected-device-not-showing-up-in-dhcp-client-table-and-only-receiving-ipv6-address.3729961/

My TV is not 50 inch, but I wouldn't doubt the above is shared between models of `onn.` TVs.

**Comment by AdSchellevis** [comment]
ok, this is a bit unexpected, your lease doesn't contain a `client-hostname` or a `hostname-override`, which is where the client-hostname on our end should be populated from:

https://github.com/opnsense/core/blob/3ca57fae8b8f460eedb0a649e26ea7fac95bf9c9/src/opnsense/site-python/watchers/dhcpd.py#L75-L78

**Comment by nblomquist** [comment]
I can try to delete the lease or something. I can then reconnect the TV and see if it gives me more? Not sure if I can for a renew on that TV... May be forget the wifi and try again?

**Comment by nblomquist** [comment]
I reconnected the TV and then got back `client-hostname` = "KitchenRokuTV".

I wonder if the bad name came before I got it all setup on the Roku Account and renamed and everything. I can probably Factory reset it and play with it. But that will have to wait until the weekend.

**Comment by nblomquist** [comment]
I factory reset the `onn.` TV. It came up with a client-hostname = "onnRokuTV-147". So that isn't strange.
I did find a lot of `null` bytes in the dhcpd.leases near-ish to the entry for this.
![Screenshot 2022-04-02 093242](https://user-images.githubusercontent.com/4588867/161385662-24aa022d-cb77-4fd0-9c22-1566dae5b0e0.png)

**Comment by AdSchellevis** [comment]
@nblomquist ok, that's odd, but with this lease file does it produce faulty records in `/var/unbound/dhcpleases.conf`?

**Comment by nblomquist** [comment]
@AdSchellevis yes.

**Comment by AdSchellevis** [comment]
@nblomquist could you offer a sample file? (via email is also ok, my address is ad at project domain)

**Comment by nblomquist** [comment]
@AdSchellevis I have sent it to your email. Thanks!

**Comment by AdSchellevis** [comment]
@nblomquist thanks, unfortunately I can't seem to be able to reproduce an issue. the garbage data could have been a result from an unplanned reboot, but doesn't seem to produce issues on my end. 

Since most leases are expired in the file, I changed the end dates from the ones valid until today and started the watcher manually using:

```
/usr/local/opnsense/scripts/dns/unbound_dhcpd.py --foreground --source /tmp/dhcpd.leases--target /tmp/dhcpleases.conf
```

`/tmp/dhcpd.leases` is the file you send me, `/tmp/dhcpleases.conf` the output it produces which looks normal on my end.
