### ISSUE TITLE
Gateway monitoring fails for 2nd wireguard interface

### ISSUE THREAD

**Issue by muok** [opnsense/core#5555]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

A clear and concise description of what the bug is, including last known working version (if any).

Gateway monitoring fails when a second wireguard interface is used (wg1), at the same time, gateway monitoring for the first wireguard interface works as expected (wg0).

To manually bring (wg1) up, I have to disable gateway monitoring for that interface. Everything works as expected if gateway monitoring is disabled for (wg1).

It doesn't matter what IP I use for the gateway monitoring, it will all fail for (wg1).

**To Reproduce**

1. Add new WG gateway
2. Add manual gateway monitoring IP for the new WG gateway
3. Go back to dashboard, immediate FAIL appears. 

**Expected behavior**

For gateway monitoring to work as expected with (WG0) and (WAN).

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 22.1-amd64
FreeBSD 13.0-STABLE
OpenSSL 1.1.1m 14 Dec 2021

**Comment by mimugmail** [comment]
Because you push all traffic via first WG instance? Better to open a thread in forums where Community is broader than here (mostly devs)

**Comment by muok** [comment]
> Because you push all traffic via first WG instance? Better to open a thread in forums where Community is broader than here (mostly devs)

No. Only selected IPs on the network are pushed through the first WG instance.
