### ISSUE TITLE
Base: Phalcon upgrade

### ISSUE THREAD

**Issue by AdSchellevis** [opnsense/core#5558]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**

When upgrading to PHP 8.x our current Phalcon version isn't compatible anymore.  Looking at the releases in https://github.com/phalcon/cphalcon/releases there doesn't appear to be a compatible version yet.

According to https://github.com/phalcon/cphalcon/issues/15186 both the unreleased version 4.2 and 5 will be supporting PHP 8.

**Describe the solution you like**

It's probably best to aim for version 5,  as different beta version have been released. We will need to investigate what changed this time to assess impact on our end.  

**Additional context**

- https://docs.phalcon.io/5.0/en/upgrade
- https://github.com/phalcon/cphalcon/releases
- https://github.com/phalcon/phalcon/discussions/86

**Comment by swhite2** [comment]
php74-phalcon5 support: https://github.com/opnsense/core/pull/5711

**Comment by fichtner** [comment]
Phalcon is working nicely, no need to keep this open.
