### ISSUE TITLE
System: Settings: Miscellaneous - Add support for QAT and allow to select multiple hardware acceleration options 

### ISSUE THREAD

**Issue by AdSchellevis** [opnsense/core#5559]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**

With the our new FreeBSD 13 base, we can now support the intel QAT module for selected processor families. While there we should improve the current hardware acceleration handling as we currently only select to select a single accelerator (`crypto_hardware`).

**Describe the solution you like**

Allow selecting different crypto options at once so we can `kldload` all at once during boot.
https://github.com/opnsense/core/blob/fc51b1541a8af8ef4ee9059b783bdb1aeb7027b5/src/etc/inc/system.inc#L838-L841

**Additional context**

- https://www.freebsd.org/cgi/man.cgi?qat

**Comment by fichtner** [comment]
Done :)
