### ISSUE TITLE
Interfaces: Other Types: VLAN - Add stacked VLAN support (IEEE 802.1ad / QinQ)

### ISSUE THREAD

**Issue by AdSchellevis** [opnsense/core#5560]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**

Since FreeBSD 13 its possible to stack vlans on top of vlans (IEEE 802.1ad), although in the past it should have been possible to build a QinQ using `netgraph`, it didn't work reliable forcing us to remove it back in 2018 (https://github.com/opnsense/core/issues/2274). 

Given the new functionality it seems like a good idea to give this another try as the interface is much cleaner now.

**Describe the solution you like**

Ideally the possibility to select a vlan in the vlan configuration, maybe refactor the current frontend while there. 

**Additional context**

- https://reviews.freebsd.org/D26436

**Comment by mimugmail** [comment]
Setting a Vlan as parent interface might also make sense from a user perspective
