### ISSUE TITLE
Can't get IPV6 to work, trying to add 'Prevent Release', but it doesn't exist.

### ISSUE THREAD

**Issue by bjornstevens** [opnsense/core#5572]
I've been using OPNsense for a couple of years now and have always been working with IPV4. Recently my ISP also allowed my home to have IPV6 enabled, but I can't get it to work out.

From the email I've gotten from my ISP they only said to configure the Prefix delegation size to 56, and to have it as DHCPv6. Whilst it does allow my NIC to go to IPv6, I can't seem to get an IP.

![afbeelding](https://user-images.githubusercontent.com/23235234/153754664-e5526a48-1f72-4967-8864-d3e1ce91d836.png)

While I was googling I found out that I probably need to enable the so-called function 'Prevent release' under DHCPv6 client configuration. 
But there it stops for me, I can't find the Prevent release button, even though it is shown on the website.
https://docs.opnsense.org/manual/interfaces.html

Is there any way I can get this back, or am I doing something completely wrong?

Greetings,
Bjorn

**Comment by bjornstevens** [comment]
> oops someone forgot to update the docs, `Prevent release` can be found in `Interfaces: Settings`. fixed in [opnsense/docs@cc02767](https://github.com/opnsense/docs/commit/cc027679f65fd1551d30536afbef36f18caea9b5)

Oh thanks! There it was, sadly I still don't have IPv6 but this is at least a step forward ( I hope)

**Comment by fichtner** [comment]
I would try to enable send prefix hint and also enable only request prefix. Some providers don't work without those (despite what they say).

Mind you, prevent release only works if you already got one which you said you haven't.


Cheers,
Franco

**Comment by bjornstevens** [comment]
> also enable only request prefix

Doesn't this mean that the WAN won't get an IP?, because who does then get the IPV6 ip?

(Do note I am new to IPv6 and am just trying to get a lan-to-wan internet connection over IPv6)

I've tried to follow this, but did not work: https://docs.opnsense.org/manual/how-tos/ipv6_dsl.html

**Comment by fichtner** [comment]
Yes and no depending on you ISP.

Yes, but you still get a link-local router which you can use and it works.

No, since it would still work with SLAAC afterwards if the ISP configured it.

Any sort of "generic" IPv6 configuration is bound to fail for ISP reasons. There's a bunch of specific tutorials in the documentation for this purpose but unfortunately not a lot of users submit their success stories for the documentation.


Cheers,
Franco

**Comment by bjornstevens** [comment]
> PS: If you don't have PPPoE "Use IPv4 connectivity" does nothing. It's worth disabling it but I doubt it makes a difference. If you want to look closer set debug level for IPv6 client and grab the logs from system log.

As right now my Interfaces settings are like this:
![afbeelding](https://user-images.githubusercontent.com/23235234/153770444-92a23ac3-a72f-4f9a-a14b-d4b2410b44f5.png)

I wonder if any DHCP Unique Identifier is needed?

I've also seen that I need to restart my modem/router to be able to pass the 'Prefix Delegation' or so. Is it common to restart the router to achieve this?

Also, my WAN setup now contains the following: 
![afbeelding](https://user-images.githubusercontent.com/23235234/153770548-01e5c507-c109-4685-8076-6cf865d39e94.png)

**Comment by fichtner** [comment]
> I wonder if any DHCP Unique Identifier is needed?

One is generated by dhcp6c and stored on the system. Grab the logs from dhcp6c under system: log files: general.

In general it also matters if you try to emulate ISP router or are behind it.

**Comment by fichtner** [comment]
(oh and those interface generic IPv6 client settings require a reboot for better or worse)

**Comment by bjornstevens** [comment]
> > I wonder if any DHCP Unique Identifier is needed?
> 
> One is generated by dhcp6c and stored on the system. Grab the logs from dhcp6c under system: log files: general.
> 
> In general it also matters if you try to emulate ISP router or are behind it.

![afbeelding](https://user-images.githubusercontent.com/23235234/153770721-d6c0cd71-8555-457e-a6ca-835bb98ebe65.png)

The network infrastructure is a bit complex, but the WAN port is the only devices connected to the modem (which is set to bridge mode and also provides the IPv4).

**Comment by fichtner** [comment]
@bjornstevens can you disable the trackers? ue0 in particular.. something errors out here

**Comment by bjornstevens** [comment]
> 

I removed the ue0, since it is/was a backup WAN connection that doesn't get used anymore.
What do you mean by disable trackers?; Monitoring of the gateway?

**Comment by fichtner** [comment]
the tracking configuration from the non-wan interfaces (ue0 being one of them)

**Comment by bjornstevens** [comment]
![afbeelding](https://user-images.githubusercontent.com/23235234/153869228-e52d96d1-271e-40ee-899c-d59801bd56b6.png)

The only one tracking right now is LAN, I will disable that one and reboot later today!
