### ISSUE TITLE
Syslog-ng does not send traffic over policy-based IPSEC tunnels for lack of localip() setting

### ISSUE THREAD

**Issue by sempervictus** [opnsense/core#5586]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

Syslog-ng cannot figure out how to send traffic to remote targets over policy-based IPSEC tunnels.

**To Reproduce**

1. Configure site to site IPSEC tunnel with policy selectors
2. Configure ACLs and verify ability to send syslog to the target manually
3. Configure logging target to a remote host over the tunnel
4. Watch nothing be received on the remote-end

**Expected behavior**

1. GUI permits setting the source-IP for syslog transmission
2. syslog-ng config sets the `localip()` parameter to the provided address in step 1

**Environment**

OPNsense 22.1.1_3 (amd64, OpenSSL).

**Notes**
1. Manually added the `localip()` param to the configuration
2. Executed `pkill -HUP syslog-ng` to reset the logger without letting the GUI reset the config
3. Observed log data coming in

**Comment by AdSchellevis** [comment]
If I'm not mistaken you can work around this by using static routes, binding to interfaces (which aren't stable) is something we do try to prevent.

**Comment by sempervictus** [comment]
Could you please define what you mean by static routes in the context of an IPSEC site-to-site which has no actual gateway to route through (just policy selectors)? I might be missing something pretty basic here if there's a way to set that up on a dynamic interface with no next-hop, apologies.

**Comment by AdSchellevis** [comment]
It has been some time that I looked into this, but at the top of my head, you should add a gateway pointing to your "lan" address (your end of the policy) and a static route sending traffic for the other end to there. In which case the firewall will automatically know which address to use.

**Comment by mimugmail** [comment]
Maybe you can also add your WAN IP to syslog server as a another P2 so it matches the IPsec tunnel. This also works fine for LDAP

**Comment by sempervictus** [comment]
@AdSchellevis: could you please elaborate on that a bit? A gateway pointing to what "lan" address (does "lan" mean non-routable block or a logical zone in this context)? We have opnsenses with multiple "lan addresses" in some cases, and multiple WAN addresses. The destination "lan" address of the syslog server is on a remote subnet which is not routed but policy-selected via IPSEC. If we had routed ipsec links, this would likely work off the bat, but the fact that syslog-ng is trying to find a _route_ where IPSEC uses a _policy_ seems to be the failure point (therefore requiring a dedicated saddr to meet the policy spec).

@mimugmail: we cannot risk having syslog go over the WAN - that config _sounds_ like if the IPSEC tunnel is down it would send traffic from the WAN interface and we use OPNSense because the environments are often small medical facilities which have significant regulatory requirements for data privacy (a syslog entry with a username is a violation of MA law if leaked because that's PII, if its a patient connecting via web-proxy thats 100X worse). Secrecy of transmission is critical, hence the expensive tunnels all over the place. I might not be groking the suggestion correctly though? Could you elaborate a bit on how that would be done through the configuration process? Thank you

**Comment by AdSchellevis** [comment]
the policy part should trap the traffic if it originates from the correct address, which is more or less the same as what you would do with a `ping -S <firewall_lan_address> <target>`. 
So logically you only need to make sure the traffic would be directed to the correct local address, which would enforce the IPsec trap to send it to the other end. 

On my end with ping (omitting the `-S` when a route is set) works like a charm.

**Comment by sempervictus** [comment]
So i think that the "if it originates from the correct address" piece is the concern. syslog-ng doesn't know what address to send from to a destination not in the routing table. In the `ping -S <firewall_lan_address> <target>` paradigm, i'm requesting the ability to do the equivalent of `syslog-ng -S <firewall_lan_address> <target>`

**Comment by AdSchellevis** [comment]
I've made a suggestion on how this works and why services know their correct source address, it's up to you if you do want to try it out or not.  

Improvements to the documentation are always welcome (https://github.com/opnsense/docs), I'm just trying to prevent solving a generic problem in a specific manor here. We've just seen too much of these issues from ghosts of the past.

If Cisco/Juniper/.. have best practices for similar problems available which are worth reading, you can always add links to those in the ticket for discussion. In my experience most best practice documents from the larger vendors point to binding on loopback interfaces and handle traffic via routing and firewall features.

**Comment by AdSchellevis** [comment]
that should be it indeed, works like a charm on my end and is quite flexible. if it doesn't, just share some screenshots.

**Comment by sempervictus** [comment]
Looks like you need to disable the automatic gateway rules for this to work, but can confirm that the route is picked up after that and a logger restart, and syslog is now coming through without hand-written configs. Thank you.

**Comment by AdSchellevis** [comment]
@sempervictus a great opportunity to contribute to the docs to help the next person? we do accept PR's :)

**Comment by sempervictus** [comment]
Digging through the repo now to see how to do this. A bit more used to writing docs inline w/ code in all my projects or keeping wikis for infra/systems/etc from the front-side of the wiki, not the src :smile:

**Comment by turboproc** [comment]
Had a similar issue where the package repo needs to be reached over the IPSec tunnel and pkg not being able to set the relevant src IP address. Solution provided above solved it immediate;y.

**Comment by xentity** [comment]
We configure a loopback management interface w/ management IP for remote sites. This IP is used for HTTPS, SSH and SNMP from the local to the remote device. But this does not work well for the reverse way. In ScreenOS there were in many menus the option to determine the local interface. If not set, the nearest interface based on the routing table taken. I miss that option for OPNsense. Other option may be, that if there is an interface called "MGMT", it is used as source for initiating traffic to Syslog, LDAP, etc.

However, it understood that you managed to solve that problem for sending syslog to a target that is reachable through a tunnel. But I do not understand the solution. Can someone elaborate that a bit, please?
