### ISSUE TITLE
PFStatistcs API not returning values

### ISSUE THREAD

**Issue by tcsi-github** [opnsense/core#5593]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [ X ] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [ X ] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

I am unable to get any return on an API call to the pfstatistcs endpoint. I will be the first to say that I'm learning, however, I have tried to look at code to find how to call it correctly and I am able to call other endpoints with no problem. 

Documentation shows that there is a "section" parameter but I have not been able to include this in anyway yet to get results. 

https://XX.XX.XX.XX/api/diagnostics/firewall/pfStatistcs

I have tried 

- pfstatistcs?info
- pfstatistcs?info=null
- pfstatistcs?info=info
- memory, timeouts, etc. as well

PFStatistcs.py shows that I 

    sections = {
        'info': pfctl_info,
        'memory': pfctl_memory,
        'timeouts': pfctl_timeouts,
        'interfaces': pfctl_interfaces,
        'rules': pfctl_rules
    }

**To Reproduce**

Try GET API call to https://XX.XX.XX.XX/api/diagnostics/firewall/pfStatistcs

**Expected behavior**

Return of some value.... ANYTHING! :-)  

**Environment**

OPNsense 22.1.1_3-amd64
Intel(R) Atom(TM) CPU C3758 @ 2.20GHz (4 cores, 4 threads)

**Comment by kulikov-a** [comment]
i think it would be api/diagnostics/firewall/pf_statistcs/{section} like api/diagnostics/firewall/pf_statistcs/rules ?
you can check api calls on browser dev console in Firewall: Diagnostics: Statistics

**Comment by AdSchellevis** [comment]
easiest way as always is to go to the page (https://x.x.x.x/ui/diagnostics/firewall/statistics) and open inspect network traffic in the browser.  works for all endpoints

**Comment by jwoodard80** [comment]
OK, I will try that and report back.
