### ISSUE TITLE
Configured DNS servers not reachable any more after a few seconds

### ISSUE THREAD

**Issue by StephanTexxpro** [opnsense/core#5596]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

Running OPNsense 22.1.1_3-amd64 in an ESXi environment with a multi WAN setup (2 uplinks).

I've configured four nameservers in 'System - General', in each case two per uplink interface.

The OPNsense box refuses to talk to two of the four configured DNS-Servers after a few seconds / minutes (could not identify any pattern). After a modification in the DNS-Server's list (System - General) and a click on 'Save', it is working again for a few seconds / minutes.

While the OPNsense box itself rejects to talk to the respective nameservers, they are still reachable from the clients behind the OPNsense box.

I've checked the routes which are setup in the routing table to the nameservers (please see bold lines).

When all of the nameservers are reachable, the routing table looks like:

root@OPNsense:~ # netstat -rn
Routing tables

Internet:
Destination        Gateway            Flags     Netif Expire
default            62.155.245.126     UGS      pppoe1
**1.1.1.1            100.64.0.1         UGHS       vmx0**
**8.8.4.4            62.155.245.126     UGHS     pppoe1**
**8.8.8.8            62.155.245.126     UGHS     pppoe1**
10.1.1.0/24        link#4             U          vmx1
10.1.1.252         link#4             UHS         lo0
10.1.8.0/24        link#15            U           wg3
10.1.8.1           link#15            UHS         lo0
10.1.9.0/24        link#16            U           wg4
10.1.9.1           link#16            UHS         lo0
10.1.9.100         link#16            UHS         wg4
10.1.20.0/24       link#13            U           wg1
10.1.20.1          link#13            UHS         lo0
10.1.21.0/24       link#14            U           wg2
10.1.21.1          link#14            UHS         lo0
62.155.245.126     link#10            UH       pppoe1
**94.247.43.254      100.64.0.1         UGHS       vmx0**
100.64.0.0/10      link#2             U          vmx0
100.80.211.9       link#2             UHS         lo0
104.16.132.229     100.64.0.1         UGHS       vmx0
127.0.0.1          link#7             UH          lo0
172.17.6.0/24      link#12            U           wg0
172.17.6.1         link#12            UHS         lo0
188.246.4.1        link#11            UH        l2tp0
188.246.4.12       link#11            UHS         lo0
188.246.9.0/27     link#5             U          vmx2
188.246.9.1        link#5             UHS         lo0
192.168.100.0/24   link#2             U          vmx0
192.168.100.2      link#2             UHS         lo0
217.232.221.48     link#10            UHS         lo0

When connectivity is lost, the routing table looks like:

root@OPNsense:~ # netstat -rn
Routing tables

Internet:
Destination        Gateway            Flags     Netif Expire
default            62.155.245.126     UGS      pppoe1
**1.1.1.1            link#2             UHS        vmx0                 <= unreachable** 
**8.8.4.4            62.155.245.126     UGHS     pppoe1**
**8.8.8.8            link#2             UHS        vmx0                 <= unreachable**
10.1.1.0/24        link#4             U          vmx1
10.1.1.252         link#4             UHS         lo0
10.1.8.0/24        link#15            U           wg3
10.1.8.1           link#15            UHS         lo0
10.1.9.0/24        link#16            U           wg4
10.1.9.1           link#16            UHS         lo0
10.1.9.100         link#16            UHS         wg4
10.1.20.0/24       link#13            U           wg1
10.1.20.1          link#13            UHS         lo0
10.1.21.0/24       link#14            U           wg2
10.1.21.1          link#14            UHS         lo0
62.155.245.126     link#10            UH       pppoe1
**94.247.43.254      100.64.0.1         UGHS       vmx0**
100.64.0.0/10      link#2             U          vmx0
100.80.211.9       link#2             UHS         lo0
104.16.132.229     100.64.0.1         UGHS       vmx0
127.0.0.1          link#7             UH          lo0
172.17.6.0/24      link#12            U           wg0
172.17.6.1         link#12            UHS         lo0
188.246.4.1        link#11            UH        l2tp0
188.246.4.12       link#11            UHS         lo0
188.246.9.0/27     link#5             U          vmx2
188.246.9.1        link#5             UHS         lo0
192.168.100.0/24   link#2             U          vmx0
192.168.100.2      link#2             UHS         lo0
217.232.221.48     link#10            UHS         lo0

As you can see, the gateway IP address was changed to `link#2` and the gateway was switched for the 8.8.8.8 nameserver from pppoe1 interface to vmx0 interface. This only happens to the first two configured nameservers, the other two (94.247.43.254 and 8.8.4.4) are still reachable and have an IP address as gateway.

**Expected behavior**

Configured nameservers should not lose connectivity from the firewall. As this seems to happen when the gateway IP is substituted to "link#X', no substitution should take place.

**Describe alternatives you considered**

N/A

**Screenshots**

![2022-02-23 11_43_35-General _ Settings _ System _ OPNsense oepf cc](https://user-images.githubusercontent.com/25078059/155316989-b217d715-7476-4dbf-9042-7a2ad4e2693e.png)

**Relevant log files**

N/A

**Additional context**

N/A

**Environment**

OPNsense 22.1.1_3-amd64
Virtuelle ESXi 7.0 U2-Maschine
Network Intel 2x quad port, igbn driver on esxi level

**Comment by StephanTexxpro** [comment]
Just tried a workaround with setting a static route to the host over the respective gateway. That replaces the link#2 with the correct gateway IP and the connectivity is reestablished. However after a few seconds / minutes the gateway IP is replaced again by link#2 and the conectivity is lost.

**Comment by mimugmail** [comment]
Do you use these IP addresses also for gateway monitoring with flipped gateways?

**Comment by StephanTexxpro** [comment]
You're talking about the single gateways, right? In that case: no
![2022-02-23 16_11_00-Single _ Gateways _ System _ OPNsense oepf cc](https://user-images.githubusercontent.com/25078059/155347977-08ace428-9101-4f5a-a94f-c73ffe96d51c.png)
.

**Comment by mimugmail** [comment]
Hm, if you are using default gateway switching I even wouldn't do such routes.
I would leave all empty and let unbound do the handling at all .. then it's all up to the system without any magic.

**Comment by StephanTexxpro** [comment]
OK, removed the nameservers from 'System - General' and let Unbound do the magic. So at least the delays / failures in name resolution are gone. Also completely removed the IP adresses of the two problematic nameservers (1.1.1.1 and 8.8.8.8) from any place in the config.
Fun fact: the two IP adresses (1.1.1.1 and 8.8.8.8) reappeared again after a few seconds in the routing table, both not reachable from the firewall from this moment on.
Did some more research tonight, my conclusion for the moment is that this is not an opensense issue, but one of the uplink provider (Starlink in that case), as Starlink seems to be pushing these entries together with the WAN interface IP address as classles static routes (dhcp option 121). Seems to be a coincidence, that the (probabely) pushed nameservers are the same I used in my config.
So closing the ticket for the time being and moving the topic to the forum.

**Comment by fichtner** [comment]
@StephanTexxpro There is some wobbliness stemming from https://github.com/opnsense/core/issues/5565 where routes are created when servers are pushed via dns even if they are set to be ignored by the system. I want to solve this for 22.1.2.
