### ISSUE TITLE
Unbound - Overrides don't override Blocklists

### ISSUE THREAD

**Issue by bedub1** [opnsense/core#5599]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**
If you setup a Blocklist to block URL's (setting them to IP 0.0.0.0), and then want to override that BlockList, the override doesn't take effect.  The system still returns 0.0.0.0 as the IP for the URL you've created an override for.

**To Reproduce**

1.     Enable and properly configure Unbound
2.     Enable a blocklist
3.     Create an Override, for a URL that exists in a blocklist
4.     Query the Unbound DNS resolver for that URL
5.     Observe it responds with 0.0.0.0 per the blocklist, and not the proper IP as defined in the Override.

**Expected behavior**

I expect to receive the IP set in the Override list.

**Describe alternatives you considered**
I had to create an entry in my Hosts file on my PC to mitigate this issue.

**Screenshots**

Can include if necessary.

**Relevant log files**

Can include nslookup screenshots, WireShark logs, and logs from Unbound.

**Additional context**

N/A

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 22.1.1_3-amd64
Exact URL: services_unbound_overrides.php

**Comment by AdSchellevis** [comment]
Long term we might consider changing the loading order (although that might bring challenges of its own), short term you could use the  "Whitelist Domains" option to make sure blocklists skip certain patterns.

**Comment by swhite2** [comment]
This has been fixed as part of https://github.com/opnsense/core/commit/d14ffae4660621e57eeb41fdee8183d8dc8e7355.
