### ISSUE TITLE
Errors in Squid Log

### ISSUE THREAD

**Issue by majorsl** [opnsense/core#560]
I've enabled Squid via the GUI and not done anything to it via the CLI.

I'm getting the following repeating over and over in the Squid Cache Log:

Fatal error: require_once():	Failed opening required 'script/load_phalcon.php' (include_path='.:/usr/local/share/pear') in /usr/local/etc/inc/legacy_bindings.inc on line 30
2015/12/23 17:30:54 kid1|	helperHandleRead: unexpected read from basicauthenticator #Hlpr11255563, 174 bytes '
'	
Warning: require_once(script/load_phalcon.php): failed	to open stream: No such file or directory in /usr/local/etc/inc/legacy_bindings.inc on line 30
2015/12/23 17:30:54 kid1|	helperHandleRead: unexpected read from basicauthenticator #Hlpr11255563, 151 bytes '
2015/12/23 17:30:54 kid1|	helperOpenServers: Starting 1/5 'squid.auth-user.php' processes
2015/12/23 17:30:54 kid1|	Starting new helpers
2015/12/23 17:30:54 kid1|	Too few basicauthenticator processes are running (need 1/5)
2015/12/23 17:30:54 kid1|	WARNING: basicauthenticator #Hlpr11255562 exited

**Comment by majorsl** [comment]
Okay, this was shortly after updating to 15.7.23. Restarting the service fixed the above...

HOWEVER, Squid has, for lack of a better term, gone haywire.  I've used it for the past couple of releases just fine, now it wants authentication to go anywhere even though I've exempted my entire subnet in the Access Control Lists as well as checking "Allow Interface Subnets" in General Forward Settings.

**Comment by fichtner** [comment]
Does this pertain even after reboot?

**Comment by fichtner** [comment]
(There were two small changes in the authentication part of squid that allow LDAP connectivity as well)

**Comment by AdSchellevis** [comment]
@majorsl can you check Forward proxy-> authentication settings? In you case "Authentication method" should be empty.

**Comment by majorsl** [comment]
Thank you! That was the tip I needed. Authentication method was empty and I was still getting the authentication dialog box.  I needed to click "Clear All" and that is what did it.

Also on that topic, I generally find empty choices for boxes a little confusing. Would it be better have "none" or perhaps "no authentication needed" as a choice for that area to clarify it a bit?  That could just be my personal preference speaking. Just a suggestion.

**Comment by fichtner** [comment]
Since we use a "tag" style selector, displaying something when nothing selected would be confusing. Out of lack of better ideas, I'm happy the original issue was resolved, so closing this. :)
