### ISSUE TITLE
Trust CA's not removed from /usr/local/etc/ipsec.d/cacerts/

### ISSUE THREAD

**Issue by joelmacklow** [opnsense/core#5600]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:
- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**
Removing CA's from System -> Trust -> Authorities doesn't flush them. When a certificate is being used for an IPSEC VPN connection, strongswan tries to check using the CA's. Even after removing a CA and restarting strongswan the CA's are still cached.  swanctl --flush-certs does nothing.

**To Reproduce**
1. Go to System -> Trust -> Authorities and delete a CA intermediate or root that was previously loaded
2. Go to VPN -> IPSEC -> Status Overview and start a certificate based VPN
3. Go to VPN -> IPSEC -> Log File and check the connection log.  In the list of certificate fetching errors (a separate issue I believe) you will see fetch errors for the CA that was deleted in step 1.
4. swanctl --list-certs will also display the cached certificate that is loaded.

**Expected behavior**
When a CA is deleted (or added) from Trust Authorities, the cache is updated to use the updated list of CA's

**Describe alternatives you considered**
swanctl --flush-certs doesn't make any difference. Neither does restarting strongswan

**Environment**
OPNsense 21.7.8-amd64

**Comment by fichtner** [comment]
@joelmacklow I'm not sure about which cache file you talk about, but the authoritative file /etc/ssl/cert.pem is rewritten on adding and removing a CA, i.e.

https://github.com/opnsense/core/blob/87f0302e79815765284b299791da2cf1f49c4e52/src/www/system_camanager.php#L252

Can you check your /etc/ssl/cert.pem for desired state?


Cheers,
Franco

**Comment by joelmacklow** [comment]
Thanks @fichtner ....Yes, I believe /etc/ssl/cert.pem should be accurate in terms of holding the global root CA's. I note that my file currently ends with:

`##  Number of certificates: 132
##  End of file.

# DigiCert Intermediate
#(system local trust) skip intermediate certificate /C=US/O=DigiCert Inc/CN=DigiCert TLS RSA SHA256 2020 CA1 from DigiCert Intermediate`

which is the intermediate CA I have added.  However,  it appears copies of any CA intermediate certs added to the system CA are added to /usr/local/etc/ipsec.d/cacerts for strongswan.

When they are removed from the System->Trust->Authorities, the relevant CA certs for strongswan are not removed from /usr/local/etc/ipsec.d/cacerts/

This causes issues with certificate based VPN connections trying to use removed CA's and causing errors in the VPN connection and VPN logging.

swanctl --flush-certs doesn't appear to do anything.  If I manually delete a CA cert from /usr/local/etc/ipsec.d/cacerts/ and then restart strongswan then swanctl --list-certs no longer displays the removed CA.

It appears to me that the functionality that currently removes a CA from the system CA database should also remove it from /usr/local/etc/ipsec.d/cacerts/, but currently doesn't.

**Comment by fichtner** [comment]
@joelmacklow thanks that makes sense. Does the following fix the situation manually?

    # configctl ipsec

**Comment by joelmacklow** [comment]
Hi @fichtner. Sadly, no, that doesn't fix it.

- Confirmed that adding a new CA to trusts - not visible in /usr/local/etc/ipsec.d/cacerts/
- Restart strongswan - CA now visible in /usr/local/etc/ipsec.d/cacerts/
- Run `sudo pluginctl ipsec` - CA still visible in /usr/local/etc/ipsec.d/cacerts/

**Comment by joelmacklow** [comment]
Awesome work @AdSchellevis. Tested and works as expected. Thank you!
