### ISSUE TITLE
Google Drive Config Restore Fails

### ISSUE THREAD

**Issue by joelmacklow** [opnsense/core#5605]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:
- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**
There seems to be an issue with the XML backup to Google Drive.  When you download a backup file from Google and use the Restore function, the page diag_backup.php throws the following error:
`Fatal error: Uncaught OPNsense\Core\ConfigException: invalid config xml in /usr/local/opnsense/mvc/app/library/OPNsense/Core/Config.php:368 Stack trace: #0 /usr/local/opnsense/mvc/app/library/OPNsense/Core/Config.php(174): OPNsense\Core\Config->loadFromStream(Resource id #36) #1 /usr/local/etc/inc/config.inc(55): OPNsense\Core\Config->toArrayFromFile('/tmp/tmpxml', Array) #2 /usr/local/www/diag_backup.php(54): load_config_from_file('/tmp/tmpxml') #3 /usr/local/www/diag_backup.php(214): restore_config_section('wol', '---- BEGIN conf...') #4 {main} thrown in /usr/local/opnsense/mvc/app/library/OPNsense/Core/Config.php on line 368`

**To Reproduce**
- Go to System:Backups:Restore
- Choose file and load backup xml file
- Choose area for restore
- Click restore configuration

**Expected behavior**
The backup is restored to the device and rebooted (if selected) or if a config section is chosen that section is restored without reboot.

**Environment**
Software version used and hardware type if relevant, e.g.:
OPNsense 21.7.7/ 21.7.8 and 22.1

**Comment by AdSchellevis** [comment]
@joelmacklow did you try to set a password (in `Configuration file is encrypted.`)?

**Comment by joelmacklow** [comment]
@AdSchellevis No I did not. No doubt this will solve it. Thanks for your help.
