### ISSUE TITLE
Have CARP switch to active only when everything else is running

### ISSUE THREAD

**Issue by bimbar** [opnsense/core#5612]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**

The problem is that when the master firewall comes up, carp starts very early, before all other services are up, leading to an outage.

**Describe the solution you like**

I would prefer the firewall to be fully up and running before it attracts the CARP addresses to itself. That would align closer to the failover modes of traditional firewalls as well.
Maybe that's not the right solution either, but I feel the behaviour of opnsense in that case is not as good as it should be, and not as good as other firewalls.

**Describe alternatives you considered**

Possibly a different cluster model from carp.

**Additional context**

When using VPN, BGP over said VPN, IPS and CARP, it takes an inordinately long time to settle into a stable state.

**Comment by mimugmail** [comment]
But this would cause trouble because Services sometimes needs the IP to bind to it?

**Comment by fichtner** [comment]
Probably more about keeping demotion on boot until services are started (move syshook from `early` to `boot`) and then promoting it to gain master state. I agree with this, but leave it up to @AdSchellevis since he knows more about this.

**Comment by AdSchellevis** [comment]
Its the responsibility of the service to handle carp's demotion on bootup, `frr` with `ospf` can do so for example using it's service check script (https://github.com/opnsense/plugins/blob/master/net/frr/src/etc/rc.carp_service_status.d/carp_frr_ospf), as explained in https://docs.opnsense.org/development/backend/carp.html

**Comment by bimbar** [comment]
> Probably more about keeping demotion on boot until services are started (move syshook from `early` to `boot`) and then promoting it to gain master state. I agree with this, but leave it up to @AdSchellevis since he knows more about this.

That seems like a great idea to achieve this.
A particular problem for example has been that carp comes up, the firewall goes active, and not only are a few services missing, like bind, at that point, but also Suricata has not started yet. So when IPS comes up, the interfaces go down again for a moment and the FW goes through the whole carp switching back and forth thing again. It comes to the point where it might have been quicker and more stable to just have one firewall and reboot that.

**Comment by AdSchellevis** [comment]
> That seems like a great idea to achieve this.

As explained in my post, it isn't, as you never know when you're "ready". 

> What is probably a different issue is the way opnsense handles interface configuration changes - say I add a VLAN interface, press apply, then the FW restarts all network interfaces,

It shouldn't, don't expect it does so either.

> , leading BGP to switch, and then everything to switch back, leading to further outages.

That could very well be the case, but is up to the routing daemon to handle, FRR doesn't natively support carp as OpenBSD does (https://man.openbsd.org/bgpd.conf.5).

> A particular problem in all this is Suricata, which leads to a second switchover a little time later when it comes up and interrupts network connectivity when it binds to the interfaces.

Netmap can be a bit annoying indeed as it "disconnects" the interface,  the actual affects do vary a bit per network interface type. Theoretically it should be possible to offer a similar "demotion" option for Suricata, knowing when it's "ready to serve" might be the tricky part.

> So the solution has been to configure very short BGP timers and disable IPS, which I don't want to do.

In order for BGP to act normally during failover, a similar solution as implemented for OSPF is probably needed (which we conceptually borrowed from OpenBSD and was funded by one of our customers, https://github.com/opnsense/plugins/issues/2091).

**Comment by AdSchellevis** [comment]
@bimbar you likely have to dig deeper then, could be another configuration issue leading to that behaviour or (virtual) hardware issues. It's not generic behaviour to drop communication when adding a virtual ip address (we would experience a lot more issues if that were the case).

**Comment by bimbar** [comment]
> 

To clarify, I did not add the address, I created a VLAN interface on an existing VLAN trunk, mapped it to a new interface, and then set an IP address on that interface.
The downtime happened when setting the IPv4 address on the new interface.

**Comment by AdSchellevis** [comment]
You can always open a ticket containing enough details about the issue you're facing (steps to reproduce, events according to the logs, etc etc).

**Comment by bimbar** [comment]
Ok, let's split that discussion off.

Would it be possible to implement such a trigger for when suricata is done loading?
