### ISSUE TITLE
Default CARP allow rule

### ISSUE THREAD

**Issue by ljauri** [opnsense/core#5613]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

We noticed that the OPNSense has a default rule allowing CARP traffic from any to any, and it is not configurable from the GUI:
pass log quick proto carp all keep state label

The rules come from:
[https://github.com/pfsense/pfsense/commit/62010384be01b9a38dca527805164af9cc48adfe](url)

It seems that this rule allows IP packets to forward if the IP protocol header is set to 112 (CARP/VRRP) even if the CARP is not in use. 

So when a user thinks that the traffic would be totally blocked, this is not the case.

**To Reproduce**

Craft an IP packet with IP Header field set to 112 (CARP/VRRP) with and it will be allowed by PF and depending on the destination address, forwarded.

**Expected behavior**

With default block all rules, the user would expect all traffic to be blocked.

**Describe alternatives you considered**

CARP is needed for failover cluster communication. The protocol seems to state that the destination address is a multicast address and TTL is 255, as the traffic should stay on local net only.

Would it be sufficient that the rule be defined by default so that the destination address is not any, but the multicast address 224.0.0.18 and IPv6 FF02::12 respectively. It seems that the CARP traffic would not need to go to unicast address in any case. 
pass in quick inet proto carp from any to 224.0.0.18 
pass in quick inet6 proto carp from any to ff02::12 

Also if it would be possible to match to the TTL 255 as well, it should be more in line with CARP protocol. But I couldn't find a way to do this with PF.

Also it might be worth considering the rule to be disabled completely where CARP is not used with interface.

**Screenshots**

**Relevant log files**

If applicable, information from log files supporting your claim.

**Additional context**

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 21.7.7 (amd64, OpenSSL).

**Comment by AdSchellevis** [comment]
https://github.com/opnsense/core/commit/c5c1ed91210fe7665ba79e6542f9f2ab17f021e3 constrains destination addresses to those defined in rfc5798 (https://datatracker.ietf.org/doc/html/rfc5798)
