### ISSUE TITLE
After upgrading to 22.1.2 very low WAN upload speed

### ISSUE THREAD

**Issue by arstom** [opnsense/core#5617]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

I've upgrade my OPNsense instance from 21.1 to 22.1.2 and facing an issue with my WAN upload speed. It's only related to upload, download speed is as before.
I have no glue where this extreme low rate is coming from. Normally, it should be 50 MBit/s but I'm only reaching 1 to 5 MBit/s. I've also reinstalled my OPNsense from scratch directly on 22.1 but there is the same behavior. When I do the same setup on 21.1 again WAN upload speed is at normal speed again.

I'm running OPNsense with qemu virtualization on my Linux server. I have not changed my setup itself, I've "only" upgraded to 22.1.2.

**To Reproduce**

Unfortunately, I cannot provide steps for that. After installing and doing the setup the behaviour is noticeable.

**Expected behavior**

Upload WAN speed should be as in version 21.1

**Describe alternatives you considered**

Rolled back my setup to 21.1

**Environment**

OPNsense 22.1.2_1-amd64
FreeBSD 13.0-STABLE
OpenSSL 1.1.1m 14 Dec 2021
Intel Atom Processor (SnowRidge) (2 cores, 2 threads)

***GOT REQUEST TO AUDIT HEALTH***
Currently running OPNsense 22.1.2_1 (amd64/OpenSSL) at Mon Mar  7 09:20:11 CET 2022
>>> Check installed kernel version
Version 22.1.2 is correct.
>>> Check for missing or altered kernel files
No problems detected.
>>> Check installed base version
Version 22.1.2 is correct.
>>> Check for missing or altered base files
No problems detected.
>>> Check installed repositories
OPNsense
>>> Check installed plugins
os-dyndns 1.27_3
>>> Check for missing package dependencies
Checking all packages: .......... done
>>> Check for missing or altered package files
Checking all packages: .......... done
>>> Check for core packages consistency
Core package "opnsense" has 65 dependencies to check.
Checking packages: ................................................................... done
***DONE***

**Comment by AdSchellevis** [comment]
If 22.1 is the last version without issues, can you try the following:

Revert core package to last known "good" version, using:
```
opnsense-revert -r 22.1 opnsense
```

Reboot after installation.

If that works without issues, try the next minor (22.1.1):
```
opnsense-revert -r 22.1.1 opnsense
```

 And reboot again

**Comment by arstom** [comment]
No, 21.1 was the last version without issues.

Shall I do a test installation on 21.1 again and afterwards a step by step upgrade to identify the "faulty" versions?

**Comment by AdSchellevis** [comment]
21.1 ? then you will have to go there first, upgrade until the issue appears. the number of versions in between are just too many. So, first 21.1, last version of 21.1.x, upgrade to 21.7. and last version of 21.7.x.

**Comment by arstom** [comment]
Upgrade to following version has been done and no performance issue has been occured. Now, I will go on with patching to the next version.

> OPNsense 21.1.9_1-amd64
FreeBSD 12.1-RELEASE-p19-HBSD
OpenSSL 1.1.1k 25 Mar 2021

**Comment by arstom** [comment]
All updates until OPNsense 21.7.8-amd64 are not showing the bad upload performance issue. Now, I will take a snapshot and do the upgrade to 22.1

**Comment by arstom** [comment]
After upgrading to 22.1 the issue is back. Using speed test like speedtest.net I suddently get a real bad upload performance again. Are there any information I can share to find out the root case? I'm surprised that I'm only facing this kind of issue.

> OPNsense 22.1-amd64
FreeBSD 13.0-STABLE
OpenSSL 1.1.1m 14 Dec 2021

**Comment by fichtner** [comment]
In that case I’m sure it’s either documented in the 22.1 release notes or discussed a number of times in the forum.


Cheers,
Franco

**Comment by arstom** [comment]
Okay

**Comment by fonz55** [comment]
You are not the only one. Last weekend upgraded to 22.1 and got stability issues with Webex. Doing a speedtest I was surprised to see the extreme slow upload. I will also revert to 21.7.8. @arstom: do you have any update or other insights?

**Comment by AdSchellevis** [comment]
https://github.com/opnsense/core/issues/5521

**Comment by fonz55** [comment]
Super, @AdSchellevis! Unfortunately creating parent interface(s) was something I already did. That didn't help. So I will be looking for some other root cause and solution. When found and reproduced I will add an issue. Probably reading the release notes will shine a light in the right direction. Other suggestions are also appreciated ;-)  Regards.

**Comment by fonz55** [comment]
@AdSchellevis: I ruled everything out and found it was my windows/browser and WIFI combination that gives the sluggish speed. With my other desktop and wired connection everything is fine.

**Comment by AdSchellevis** [comment]
@fonz55 maybe packetloss or the client assuming an mtu size that doesn't fit, but good to hear it's not a generic issue

**Comment by karlanke** [comment]
I'm also seeing this - fairly basic install running on proxmox, no VLANs, two proxmox bridges. I get 1000/1000 directly to the ONT, and 1000/4 going through proxmox. Hardware offload is disabled, I've rebooted, I've tested other VMs on the proxmox server and all see the same consistent 4mpbs. No CPU or memory issues. Any ideas before I try 21.7?

**Comment by evo11x** [comment]
I am also having slow upload speed running opnsense in proxmox, download speed 945mbps, upload speed 7mbps. If I change the network bridge from virtio to intel e1000 the download is 245mbps and upload 600mbps but it looses some packets. This problem appeared after the last opnsense update to 24.1.6.
The problem is that opnsense does not like the proxmox bridge, not the pci passthrough, as iperf running in opnsense on WAN has good download/upload speed.
