### ISSUE TITLE
[ui] vpn -> alternating icons looks messy

### ISSUE THREAD

**Issue by sjorge** [opnsense/core#562]
The alternating locked, unlocked icons give the sub menu a messy look.
Maybe just use the same (locked?) icon for all?

**Comment by 8191** [comment]
The idea behind that is to distinguish between "secure" and "insecure" VPNs, i.e. VPNs that use strong encryption and authenticity, and VPNs that don't. See also #807.

**Comment by fichtner** [comment]
Yes, fixing the alignment is probably all that's needed.

**Comment by fichtner** [comment]
Has been reordered (2x locked, 2x unlocked) by @fabianfrz . FontAwesome doesn't give a unified icon size so fixing properly will be hell. Closing. Thanks!

**Comment by 8191** [comment]
@fichtner @fabianfrz  Regaring unified icon size, I just stumbled upon [the fixed with icon class](http://fortawesome.github.io/Font-Awesome/examples/#fixed-width) of FontAwesome: `fa-fw`.

**Comment by fichtner** [comment]
Looks very good, this should be in all submenus :)

(not the top menu, it still has a glyphicon)

**Comment by fichtner** [comment]
Pushed, many thanks to @8191

**Comment by 8191** [comment]
nice... :)
