### ISSUE TITLE
Feature Request: multiple source / destination / service options per Firewall Rule

### ISSUE THREAD

**Issue by Ketanest** [opnsense/core#5621]
[x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
[x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

Important notices

Before you add a new report, we ask you kindly to acknowledge the following:

I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

Is your feature request related to a problem? Please describe.

In big environments you have nest much aliases. That could be very confusing.

Describe the solution you like

it would be nice if you could select multiple source or destination networks (or aliases) per firewall rule.
Also it would be suitable to select multiple port ranges or protocol versions per rule.

This would make the rules much more clearer in big environments.

Describe alternatives you considered

N/A

Additional context

N/A

**Comment by mimugmail** [comment]
Nested Aliases is not sufficient enough?

**Comment by Ketanest** [comment]
Unfortunately not. We have more than 100 firewall rules. When we scroll through the roles we always have to mouseover the networks if we don't know what networks hide behind the aliases. In addition it is very complex to administrate especially if you use nested aliases multiple times.
I think that feature could be suitable for many admins.
