### ISSUE TITLE
Default Route is replaced

### ISSUE THREAD

**Issue by cmaxwe** [opnsense/core#5624]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

I have a WAN interface and the corresponding gateway (WAN_DHCP). I also have a separate interface that connects to a single device that has a DHCP server which dynamically assigns an IP addresses to my Opnsense interface (MevoDevice / MevoDeviceGateway). This interface is setup as a gateway (with upstream gateway not checked). I turn the device that assigns the IP to the MevoDevice on and off periodically.

After a reboot with the mevo device off everything works as expected however if I turn the mevo device on; my opnsense gets an ip on the mevodevice and my default route (i.e. the WAN) is removed. All traffic on my LAN stops being routed via the WAN.

Once this happens I can disable and enable the WAN interface and the route will be recreated and in the future it doesn't get removed if I turn on/off the mevo and get a new DHCP ip on my MevoDevice interface.

**To Reproduce**

1. Setup explained above (WAN + LAN + OPT1)
2. WAN gets an ip via DHCP and is the default gateway
3. OPT1 gets an ip via DHCP and the default route from the WAN is removed
4. Fix the route issue manually (i.e. enable / disable the WAN interface or WAN gateway)
5. Future cases where the OPT1 interface gets an ip via DHCP work as expected (i.e. the WAN route is not removed)

**Expected behavior**

Getting a new DHCP lease on a different interface after a reboot shouldn't remove the default route.

**Describe alternatives you considered**

A clear and concise description of any alternative solutions or workaround you considered.

**Screenshots**

**Relevant log files**

If applicable, information from log files supporting your claim.

**Additional context**

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 21.1.2_1 (amd64, OpenSSL).
Broadcom SFTP w/VLAN for WAN (DHCP Client)
Intel igb for Mevo (DHCP Client)
Intel em0 for LAN

**Comment by mimugmail** [comment]
Did you set Default gateway switching in System : Settings : General?

**Comment by cmaxwe** [comment]
@mimugmail  "Allow default gateway switching" is unchecked.

**Comment by AdSchellevis** [comment]
Usually this is about gateway switching or overlapping priorities, if there's an obvious bug we should fix we definitely change the tag later on.  

Gateway selection can be confusing sometimes, backgrounds about selection and how to troubleshoot can be found in our documentation (https://docs.opnsense.org/manual/gateways.html#default-gateways)

**Comment by cmaxwe** [comment]
Thanks for the link @AdSchellevis

Few more details about my setup (which was kind of confirmed by the link):
1. I have "Allow default gateway switching" unchecked
2. I have the WAN gateway as the highest priority (1)
3. I have the WAN gateway set as "upstream"
4. My Mevo gateway is the lowest priority (255)
5. My Mevo gateway is not set as "upstream"
6. I have no gateway monitoring setup

Later today I will reproduce and post the logs.

**Comment by cmaxwe** [comment]
Some attachments...

1. My gateways for [WAN](https://filedrop.c-maxwell.net/github_attachments/wan_gateway.png) and [Mevo](https://filedrop.c-maxwell.net/github_attachments/mevo_gateway.png)
2. The routes after I restart and before I start the Mevo (i.e. when everything is working expected and the Mevo hasn't given me a DHCP ip on the non-WAN interface [Before - Routes](https://filedrop.c-maxwell.net/github_attachments/after_reboot.png)
3. The routes once the Mevo gives Opnsense an IP via DHCP [After - Routes](https://filedrop.c-maxwell.net/github_attachments/after_starting_mevo.png)
4. Then finally the routes after I disable and enable my WAN gateway (to fix the problem) [Fixed - Routes](https://filedrop.c-maxwell.net/github_attachments/after_disable_enable_wan_gw.png)
5. Then the log (not much help actually) during this period of time [system.log](https://filedrop.c-maxwell.net/github_attachments/system.log)

**Comment by AdSchellevis** [comment]
@cmaxwe can you find the initial gateway creation in the log, it looks a bit suspicious.

Here it thinks Mevo is the valid gateway, but since both are dhcp based the initial event is the relevant here.
```
2022-03-10T13:46:26-04:00	Error	opnsense	 /usr/local/etc/rc.newwanip: On (IP address: 192.168.2.5) (interface: Mevo[opt4]) (real interface: igb0).
````


When the Mevo is plugged in, can you check which `/tmp/*_router` files exist as well?

**Comment by cmaxwe** [comment]
Here is a log (I removed the Mevo gateway that I had manually created - it doesn't look like it recreated it in the UI but it appears to create the routes I need regardless).

https://filedrop.c-maxwell.net/github_attachments/system%2520%25281%2529.log

When the Mevo is connected there is no corresponding _router file in tmp. Just my normal /tmp/bxe0_vlan35_router.

**Comment by fichtner** [comment]
@cmaxwe Can you take a look at

# cat /var/db/dhclient.leases.igb0

I suspect it doesn't give you a default route (or any route for that matter) if the router file does not exist ("option routers").


Cheers,
Franco

**Comment by cmaxwe** [comment]
@fichtner:

You are right!

lease {
  interface "igb0";
  fixed-address 192.168.2.5;
  option subnet-mask 255.255.255.0;
  option broadcast-address 192.168.2.255;
  option dhcp-lease-time 600;
  option dhcp-message-type 5;
  option dhcp-server-identifier 192.168.2.1;
  renew 1 2022/3/14 17:19:57;
  rebind 1 2022/3/14 17:23:42;
  expire 1 2022/3/14 17:24:57;
}
lease {
  interface "igb0";
  fixed-address 192.168.2.5;
  option subnet-mask 255.255.255.0;
  option broadcast-address 192.168.2.255;
  option dhcp-lease-time 600;
  option dhcp-message-type 5;
  option dhcp-server-identifier 192.168.2.1;
  renew 1 2022/3/14 17:23:43;
  rebind 1 2022/3/14 17:27:28;
  expire 1 2022/3/14 17:28:43;
}
lease {
  interface "igb0";
  fixed-address 192.168.2.5;
  option subnet-mask 255.255.255.0;
  option broadcast-address 192.168.2.255;
  option dhcp-lease-time 600;
  option dhcp-message-type 5;
  option dhcp-server-identifier 192.168.2.1;
  renew 1 2022/3/14 17:28:43;
  rebind 1 2022/3/14 17:32:28;
  expire 1 2022/3/14 17:33:43;
}

**Comment by cmaxwe** [comment]
@fichtner If I add "default routers 192.168.2.1" to the Mevo interface Option Modifiers then it creates a gateway for the interface and sets the default route to the mevo interface and 192.168.2.1 when it gets a DHCP lease.

Desired functionality is for it to not just assume that any dhcp lease is the default route though.

**Comment by cmaxwe** [comment]
Gateways page looks like you would expect.

WAN = Active w/ Priority 1 Upstream
Mevo = Looks like a normal gateway with a priority of 255 (no active in brackets and no upstream tag)

Routes page with Franco's suggestion looks a bit different than before (where there was no default route when the Mevo stole it from WAN). Now the Mevo's gateway shows up as the default route. While this makes more sense it actually doesn't change the overall problem of the Mevo stealing the default gateway when it is activated after a reboot.

Once I fix it by disabling and enabling the WAN gateway then it works going forward without issue (i.e. I can turn the mevo on and off and it will not steal the WAN gateway).

It is like Opnsense isn't respecting either the "upstream gateway" flag or the "Allow default gateway switching" when it gets the first DHCP lease on an interface after a reboot.

**Comment by cmaxwe** [comment]
I just recreated the issue with fresh Virtual Machines - so it isn't an issue with my specific instance.

1. A VM on my "LAN" virtual network to access and config Opnsense1
2. A Opnsense1 VM that has a "WAN" bridge to my real LAN + an interface to my "LAN" virtual network + an interface to a "MEVO" virtual network
3. A Opnsense2 VM that just gives out DHCP leases on my "MEVO" virtual network

As with my real configuration - if I boot Opnsense1 it works as expected and my default gateway is the "WAN" bridge. Then when I boot Opnsense2 then my Opnsense1 VM gets a lease on the "MEVO" virtual network and it replaces the default gateway.

**Comment by AdSchellevis** [comment]
looking briefly at the `dhclient-script`, there might be an issue with removing the default route. could your try to disable this line:

https://github.com/opnsense/core/blob/c3a4b2346928c3bd4b9c1f6336296b28f0445bb1/src/opnsense/scripts/interfaces/dhclient-script#L134

just place a # in front of the line (`#route delete default >/dev/null 2>&1`)

If that doesn't change anything, try the same for:

https://github.com/opnsense/core/blob/c3a4b2346928c3bd4b9c1f6336296b28f0445bb1/src/opnsense/scripts/interfaces/dhclient-script#L181

If the gateway determination is doing the right thing, but the dhclient script is removing the default gateway, it might explain what's happening on your end.

Usually the `rc.newwanip` should enforce the correct gateway as well. 

https://github.com/opnsense/core/blob/c3a4b2346928c3bd4b9c1f6336296b28f0445bb1/src/opnsense/scripts/interfaces/dhclient-script#L344

https://github.com/opnsense/core/blob/c3a4b2346928c3bd4b9c1f6336296b28f0445bb1/src/etc/rc.newwanip#L148

https://github.com/opnsense/core/blob/d4f4b48b0692efbbbccbb79e3651b50227eb65c5/src/etc/inc/system.inc#L540-L555

**Comment by waveguerilla** [comment]
My opnsense installation, from november, with all upgrades that came since.

I have the same issue and I see it is resolved, I have the good script here : /usr/local/opnsense/scripts/interfaces/dhclient-script

But I think the one that is used by dhclient is here /sbin/dhclient-script and it is the old code with default route removal.

It is not the same code or a link, have you an explanation for this ?

Thanks
