### ISSUE TITLE
DHCP leases do not register with dnsmasq on-the-fly; requires restarting the service.

### ISSUE THREAD

**Issue by wrobelda** [opnsense/core#5627]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

I connected a new system to my LAN network and realized I cannot SSH/ping it from any other host. I checked DHCP4 status page and can see the hostname and its IP address listed there. dnsmasq is configured with `Register DHCP leases` option. Despite that, a `dig @127.0.0.1 hostname` on the firewall (or anywhere else in LAN) does not return a record. 

Restarting the service, however, immediately made it work again, so it seems that the registering doesn't work on-the-fly.

**Expected behavior**

dnsmasq should register new leases immediately without having to be restarted.

**Environment**

OPNsense 22.1.2_1-amd64

**Comment by AdSchellevis** [comment]
Best switch to unbound, we rebuild a watcher which uses unbound-control for live updates. dnsmasq is hardly used and still implements https://github.com/opnsense/ports/tree/master/opnsense/dhcpleases which is unmaintained.

https://github.com/opnsense/core/blob/dedb11793547e270aa65cab8778eda4fc6663ebe/src/etc/inc/plugins.inc.d/dnsmasq.inc#L272-L289

If do do want to debug this further I would start there, if there are structural issues with it, it does raise the question if it does make sense to fix it or better remove it due to the alternatives available and the resources it will take to remove `dhcpleases`. 

By the way, it might be a good idea to answer @mimugmail in the forum (https://forum.opnsense.org/index.php?topic=27158.msg132329#msg132329) when asking for support and complaining about feedback in https://github.com/opnsense/core/issues/5592

**Comment by wrobelda** [comment]
> Best switch to unbound, we rebuild a watcher which uses unbound-control for live updates. dnsmasq is hardly used and still implements https://github.com/opnsense/ports/tree/master/opnsense/dhcpleases which is unmaintained.

Thanks, I guess I'll have to make the switch eventually.

> By the way, it might be a good idea to answer @mimugmail in the forum (https://forum.opnsense.org/index.php?topic=27158.msg132329#msg132329) when asking for support and complaining about feedback in https://github.com/opnsense/core/issues/5592  

Very much aware of it, still have that problem, but it requires some more time to look into. This one, on the other hand, was a quick to report, so obviously I did it right away.

**Comment by AdSchellevis** [comment]
> Thanks, I guess I'll have to make the switch eventually.

Probably the best option indeed. I'm closing this issue now in favour of https://github.com/opnsense/core/issues/5628

**Comment by wrobelda** [comment]
> > Thanks, I guess I'll have to make the switch eventually.
> 
> Probably the best option indeed. I'm closing this issue now in favour of #5628

Well, I switched to unbound and have same exact issue. Lease is registered, per DHCP status, "Register DHCP leases" is on on Unbound settings page, but not getting a DNS response unless restarting the service.

**Comment by AdSchellevis** [comment]
Could have multiple reasons, best check the unbound logs (remember to change the level), current lease file `/var/dhcpd/var/db/dhcpd.leases` (also check validity of the record in question).  The active feed should be flushed into `/var/unbound/dhcpleases.conf` and the running `unbound`.

**Comment by AdSchellevis** [comment]
Closed https://github.com/opnsense/core/issues/5628 again as it does seem to work for others without issues. Most likely cause would be using Apple devices with privacy settings (which omits hostnames), if that's the case, we would really like to ask to spend a bit more time locally before opening issues.....

**Comment by wrobelda** [comment]
> Closed https://github.com/opnsense/core/issues/5628 again as it does seem to work for others without issues. Most likely cause would be using Apple devices with privacy settings (which omits hostnames)

This is not the case, the host is Parallels VM bridged to the network, the VM hostnames are passed over, as witnessed by the DHCP leases page. 

I restarted the server, though, a bunch of time, and testing it again now with different VMs seems to work flawlessly. If this issue comes back, I will report here.
