### ISSUE TITLE
Services: Dnsmasq DNS - remove "Register DHCP leases" option

### ISSUE THREAD

**Issue by AdSchellevis** [opnsense/core#5628]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

The option "Register DHCP leases" is a remnant of our predecessor and doesn't seem to work as it should, since it's highly unlikely the registrations did work properly the last years and we use Unbound nowadays as our standard, it makes sense to remove the option and point people to Unbound when migrating old configurations. 

**To Reproduce**

Explained in https://github.com/opnsense/core/issues/5627 

**Describe alternatives you considered**

Rewrite `dhcpleases` as we did for Unbound and fix the issue, but  providing the same option in two places in the same product is suboptimal anyway. Since there are some use-cases where it does make sense to have a separate dns forwarder available, removing DNSMasq in full doesn't seem to be needed either.

**Additional context**

https://github.com/opnsense/core/blob/dedb11793547e270aa65cab8778eda4fc6663ebe/src/etc/inc/plugins.inc.d/dnsmasq.inc#L272-L277

^^ now seem to be the time.

**Comment by fichtner** [comment]
#5119

**Comment by AdSchellevis** [comment]
@fichtner if you agree on removal, we can close https://github.com/opnsense/core/issues/5119 (which I missed to be honest, but given the usage of dnsmasq I don't think we should spend too much time trying to revive features that are hardly used)

**Comment by AdSchellevis** [comment]
Tested by @fichtner, tracking leases does seem to work without issues, which doesn't warrant feature removal for now as we can't assess how many people are actually using it. Which leaves https://github.com/opnsense/core/issues/5119 the valid ticket for now as we're not planning for full removal of dnsmasq just yet (maybe in the future, but only with an exit strategy).
