### ISSUE TITLE
DNS Resolver (Unbound) needs ACL before working - make more obvious/more sane defaults?

### ISSUE THREAD

**Issue by syserr0r** [opnsense/core#563]
The unbound DNS Resolver needs ACLs added before it will accept DNS requests for any networks. This is not very obvious.

Is there a circumstance where the ACLs can do something the firewall rules can't?
If so, then it would be good to put a notice on the 'General' page to prevent unneeded head-scratching.
If not, I would suggest white-listing all (local?) networks and using firewall rules to control access.

**Comment by AdSchellevis** [comment]
@syserr0r that sounds odd, it should add acls for the active interfaces if I'm reading the code right. I will look into this, although I can't guarantee that it will make 16.1.

**Comment by AdSchellevis** [comment]
@syserr0r what does your setup look like? when I enable the dns resolver with its defaults on the current development version it doesn't seem to need an acl from my local net. I tried to forward some requests and added a local override for a random host.

**Comment by syserr0r** [comment]
@AdSchellevis I am using the DNS Resolver primarily on OPT1 (Lunchroom) but also for some LAN hosts on both the primary and secondary subnets.
LAN Primary = 192.168.1.0/24 (Typically not used as Windows/AD server DNS Resolver looks after this)
LAN Secondary = 192.168.2.0/24 [IP Alias on LAN] (Some hosts use this as the Windows/AD server does not listen on this network)
LUNCHROOM = 192.168.6.0/24 (OPT1, different VLAN, primarily for staff WiFi, DNS relies entirely on OPNsense DNS Resolver)

The relevant pages of the config look like this:
## DNS Resolver Settings
![DNS Resolver Settings](http://i.imgur.com/tOyfdi3.png)
## DNS Resolver ACL Overview
![DNS Resolver ACL Overview](http://i.imgur.com/BY4jrQm.png)
## DNS Resolver ACL Entry
![DNS Resolver ACL Entry](http://i.imgur.com/TIi4C8s.png)

I hope that helps

**Comment by 8191** [comment]
Are there actually situations in which I cannot use a firewall rule instead of ACLs to restrict DNS access? Do we actually need that feature?

**Comment by AdSchellevis** [comment]
@8191 you mean the ACL feature at all? I didn't need it on my end to set it up but @syserr0r needed it to get the resolver to accept anything from his network (which I think shouldn't be necessary, but I still need to find out why it worked at my end and not at Anthony's machine).

**Comment by AdSchellevis** [comment]
@syserr0r In the current version I can't seem to reproduce the issue for the defined interfaces, only for the IP alias.

When the configuration of unbound is generated it (should) generate an acl for all defined networks in /var/unbound/access_lists.conf , but will only do that for "interface addresses". 
The ACLs need to be defined for other addresses then those, for example aliases and vpn clients.
Like @8191 suggested an option could be to remove the ACL completely and just accept all from everywhere, but I don't have a strong opinion what's better in this case, may @fichtner has some ideas on the subject.

If you have the time, can you confirm that your /var/unbound/access_lists.conf  do contain the network addresses of the defined interfaces on a current version? Just to be sure I'm not overlooking something else here...

**Comment by syserr0r** [comment]
@AdSchellevis I can confirm that `/var/unbound/access_lists.conf` contains ranges for the configured interfaces.

**Comment by syserr0r** [comment]
@AdSchellevis I would argue that generating hidden ACL's for the interfaces is a bit misleading -- from looking at the web UI one would expect there to be no rules at all. At the very least the auto-generated ACL's should be shown, no?

**Comment by AdSchellevis** [comment]
@syserr0r true, it is a bit misleading, question is... should we fix it optically (and only display a line with the autogenerated rules) or is there really no use to have ACLs in it.
If we can't think of a reason why there should be ACL's I would rather trash the functionality like @8191 suggested, but maybe we're overseeing something here.
Let leave this one open for debate and decide what to do depending the outcome.

**Comment by syserr0r** [comment]
@AdSchellevis It's what I suggested to begin with, but looking a bit further there is more than just allow/deny for the ACLs: _Allow, Deny, Refuse_ (All can be done with the firewall) and _Snoop_ (which I don't think can)

## DNS Resolver ACL Options
![DNS Resolver ACL Options](http://i.imgur.com/HH4F174.png)

**Comment by AdSchellevis** [comment]
@syserr0r that makes sense, lets do the optical fix then, I just needs to be clear what it does by default.

**Comment by syserr0r** [comment]
@AdSchellevis Sounds good :+1:
