### ISSUE TITLE
interfaces: Virtual IP Bind Issue

### ISSUE THREAD

**Issue by AryasDad** [opnsense/core#5632]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [ X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [ X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

A clear and concise description of what the bug is, including last known working version (if any).

HAProxy started automatically in previous version of Opnsense 22.1.1_3.  However, after update to OPNsense 22.1.3-amd64, it would no longer start the HAProxy plugin.  No error was reported and nothing was present in the logs. I logged into terminal and tried to start manually and it reported that it could not bind to my internal Virtual IP.

So, I went to the VirtualIP settings in the GUI and confirmed that I had Allow service binding turned on.  As a test I re-saved and applied the settings.  After that HAProxy started up just fine.

I rebooted to test and the same thing happened.  I had to manually re-save the Virtual IP and apply the settings and the HAPRoxy could be started.

*Tip*: to validate your setup was working with the previous version, use opnsense-revert (https://docs.opnsense.org/manual/opnsense_tools.html#opnsense-revert)

**To Reproduce**

1. Go to Dashboard or HAProxy plugin and try to enable.  It will not start with no error reported.

**Expected behavior**

HAProxy should start with no issue.

Software version used and hardware type if relevant, e.g.:

OPNsense 22.1.3-amd64
FreeBSD 13.0-STABLE
OpenSSL 1.1.1m 14 Dec 2021

Run in virtual machine of Proxmox Virtual Environment 7.1-10

**Comment by AdSchellevis** [comment]
> Assigning services to the virtual IP's interface will automatically include this address. Uncheck to prevent binding to this address instead.

^^ off is the right option if you don't want core services to bind to it.

**Comment by fichtner** [comment]
It's always better to try the forum first and avoid (unreferenced) cross-posting. The fact that a config.xml flag resets itself is a bit fishy so that needs to be figured out first. The rest is just assumption vs. configuration.

https://forum.opnsense.org/index.php?topic=27547.msg133668#msg133668

**Comment by AryasDad** [comment]
Config flag does not appear to be changing, I just re-saved the same exact VIP settings as before and then Haproxy is able to start. 

Apologies for the unreferenced cross post.  Will continue discussion in forum to see where my settings are amiss.

**Comment by fichtner** [comment]
Fixed in 9a618ba6 / 22.1.4.
