### ISSUE TITLE
VPN / IPsec - migrate ipsec.conf to swanctl.conf

### ISSUE THREAD

**Issue by AdSchellevis** [opnsense/core#5636]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**

In time Strongswan will remove support for `ipsec.conf` (could't find a clear path on their end, if there is, it might be good to add a dead line here), in which case the newer `swanctl.conf` should be used.

**Describe the solution you like**

Migrate current legacy code to output new style configuration data instead of the current ipsec.conf file.

Currently the ipsec.conf is written here:

https://github.com/opnsense/core/blob/c3bae88bf5195e3f54b6e7bfba8cafce633164c5/src/etc/inc/plugins.inc.d/ipsec.inc#L1754

A challenging part might be the current support for custom includes in :
https://github.com/opnsense/core/blob/c3bae88bf5195e3f54b6e7bfba8cafce633164c5/src/etc/inc/plugins.inc.d/ipsec.inc#L1752

**Describe alternatives you considered**

None

**Additional context**

- Migration note from Strongswan https://wiki.strongswan.org/projects/strongswan/wiki/Fromipsecconf

**Comment by AdSchellevis** [comment]
Rebased on master, apply https://github.com/opnsense/core/issues/4614 first on 22.7.4 to test
```
opnsense-patch 9448b0c
```

**Comment by AdSchellevis** [comment]
merged

**Comment by fichtner** [comment]
@AdSchellevis marked this "roadmap" as well :)

**Comment by fichtner** [comment]
FWIW, I still get these warnings on bootup:

```
[10-Oct-2022 20:37:13 Europe/Berlin] PHP Warning:  Undefined array key "ikeid" in /usr/local/etc/inc/plugins.inc.d/ipsec.inc on line 244
[10-Oct-2022 20:37:16 Europe/Berlin] PHP Warning:  Undefined array key "ikeid" in /usr/local/etc/inc/plugins.inc.d/ipsec.inc on line 844
[10-Oct-2022 20:37:16 Europe/Berlin] PHP Warning:  Undefined array key "ikeid" in /usr/local/etc/inc/plugins.inc.d/ipsec.inc on line 390
[10-Oct-2022 20:37:16 Europe/Berlin] PHP Warning:  Undefined array key "ikeid" in /usr/local/etc/inc/plugins.inc.d/ipsec.inc on line 772
```

**Comment by AdSchellevis** [comment]
@fichtner i'll take a look, probably missed a spot there.

**Comment by AdSchellevis** [comment]
@fichtner probably an empty `phase1` or `phase2` tag in your config, all these lines are loops comparing both phases. These are almost impossible to fix with legacy code.

**Comment by fichtner** [comment]
This one perhaps?

     <phase2>                                                                    
       <reqid>1</reqid>                                                          
     </phase2>

**Comment by AdSchellevis** [comment]
yep, invalid data, probably injected due to a bug in the past. the advantages of models, at least you always know which properties exists, legacy will always be prone to errors.

**Comment by fichtner** [comment]
neat, that did the trick :)
