### ISSUE TITLE
Activating Unbound DNS blocklist causes configd.py traceback (so do other "longish" configuration tasks)

### ISSUE THREAD

**Issue by c-s-1** [opnsense/core#5639]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

Enabling Unbound DNS blocklists causes a traceback in configd.py.

**To Reproduce**

1. Go to `https://<opnsense box>/ui/unbound/dnsbl/index`.
2. Select ~10-11 blocklists.
3. Enable blocklist feature.

**Expected behavior**

Blocklists are enabled, "Apply" button animation will end after a short time.

**Describe alternatives you considered**

There seems to be no workaround.

**Screenshots**

**Relevant log files**

The backend logs show the following error:

```
2022-03-21T18:03:21 | Error | configd.py | unable to sendback response [OK ] for [unbound][dnsbl][None] {1708df0e-915b-4b59-8fe0-4730adf6deb7}, message was Traceback (most recent call last): File "/usr/local/opnsense/service/modules/processhandler.py", line 202, in run self.connection.sendall(('%s\n' % result).encode()) BrokenPipeError: [Errno 32] Broken pipe
2022-03-21T18:02:42 | Error | configd.py | Timeout (120) executing : unbound dnsbl
```

**Additional context**

This issue also occurs in a similar fashion when doing the following:

- Download and apply Web Proxy "Remote Blacklist".
- Activate Intrusion Prevention.

**Environment**

OPNsense 22.1.3-amd64 on an Intel(R) Celeron(R) CPU J3455 @ 1.50GHz (4 cores, 4 threads) platform with 6 GB RAM

**Comment by AdSchellevis** [comment]
The machine isn't fast enough to wait for the action to complete (120 seconds), https://github.com/opnsense/core/commit/28e7d49380624e787319ca4ca8bb59b7d15e231f changes the log level to `notice` (which is more suitable).
