### ISSUE TITLE
Cron: can't delete "Update and reload intrusion detection rules" cronjob

### ISSUE THREAD

**Issue by c-s-1** [opnsense/core#5640]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

The "Update and reload intrusion detection rules" cronjob automatically created via the "Services: Intrusion Detection: Administration / Schedule Tab" can't be deleted in "System: Settings: Cron" after disabling all ruleset downloads. Other, manually added cronjobs can be deleted just fine. The cronjob can only be disabled.

**To Reproduce**

1. Go to "Services: Intrusion Detection: Administration" and on the "Settings" tab activate "Enabled" and "IPS mode".
2. Go to "Download" tab and enable a number of rulesets and click "Download & Update Rules".
3. Go to "Schedule" tab and save the proposed cronjob.
4. Disable all rulesets on the "Download" tab.
5. Disable Intrusion Detection on the "Settings" tab.
6. Go to "System: Settings: Cron" and click the trashcan symbol next to the "Update and reload intrusion detection rules" cronjob.

**Expected behavior**

The cronjob will disappear, clicking on "Apply" will update Cron.

**Describe alternatives you considered**

I don't see any workarounds.

**Screenshots**

N/A

**Relevant log files**

N/A

**Additional context**

N/A

**Environment**

OPNsense 22.1.3-amd64
FreeBSD 13.0-STABLE
OpenSSL 1.1.1m 14 Dec 2021
Intel(R) Celeron(R) CPU J3455 @ 1.50GHz (4 cores, 4 threads)
6 GB RAM

**Comment by AdSchellevis** [comment]
It's an internal cron job, you can disable it.

**Comment by c-s-1** [comment]
@AdSchellevis Thanks for the quick reply. Ok, that wasn't obvious to me that it's internal and can't be deleted. Would it make sense to include this fact in the docs or to remove the trashcan from internal cronjobs that can't be deleted? In other words: does it make sense to open a feature request for this?

**Comment by c-s-1** [comment]
Thanks, @AdSchellevis . I'll close this issue and open a feature request.
