### ISSUE TITLE
Suricata Alerts tab limit and pagination

### ISSUE THREAD

**Issue by Codelica** [opnsense/core#5643]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [ X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X ] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

The "Alerts" tab under Suricata Administration has two issues:

1) The first concerns pagination.  When the default limit of 7 (which is extremely low) is changed to something like 50,  both the pager UI at the bottom and the count are not updated to be correct: 

<img width="1164" alt="suricata-pager" src="https://user-images.githubusercontent.com/386101/159748102-de79f208-9251-4c33-b683-d8ab7faf0d0c.png">

2) Unlike the Rules tab pagination under Suricata Administration, the Alerts tab pagination doesn't retain it's last chosen limit setting.  It always reverts to 7 when returning to Suricata from another part of the OPNSense admin UI.

**To Reproduce**

1) Setup Suricata and add rules to create alerts.
2) Gather over 7 alerts
3) Change the Alerts limit on the Alerts tab and refresh it.

**Expected behavior**

Pagination and count should be correct, and last Alerts limit chosen should be retained like Rules pagination.

**Describe alternatives you considered**

N/A

**Screenshots**

Inline above.

**Relevant log files**

N/A

**Additional context**

N/A

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 22.1.3 (amd64, OpenSSL).

**Comment by AdSchellevis** [comment]
is https://github.com/opnsense/core/commit/8100e506bf582a384ad52572d88c0db870b38b15 which will be released in the next version.

**Comment by Codelica** [comment]
Just FYI, after updating to 22.1.4_1 with the fix, pagination and alert total seems to still be broken for me.  Basically the total seems to always be the count of the last alert displayed + 1.   So pagination just continues to expand when used.  

Item 2 on this issue is fixed, it does retain the last setting for alert count to display.

**Comment by AdSchellevis** [comment]
@Codelica which is as expected as https://github.com/opnsense/core/commit/8100e506bf582a384ad52572d88c0db870b38b15 only fixes the issue with the `Showing 1 to X` part of the count, the backend doesn't know the number of lines in these cases.

**Comment by Codelica** [comment]
@AdSchellevis not trying to be a pain, but I don't seem to be following. :) I currently see `Showing 1 to X of X+1` rather than `Showing 1 to X of TotalEntries`.    You're saying that's because the backend doesn't know `TotalEntries` or that's coming as part of another future fix?  Thanks!

**Comment by AdSchellevis** [comment]
You can't know the number of rows in a file without reading the whole file first (https://docs.opnsense.org/manual/gui.html#page-navigation), if we would do that during each request you would likely complain about the lack of responsiveness next. Ending this discussion now with removing the `TotalEntries` part in https://github.com/opnsense/core/commit/6e6a0a280cac7817399185b7c7c45fa0aeeb8fd6.
