### ISSUE TITLE
Update to 22.1 : Leftover Logs break Web Interface?

### ISSUE THREAD

**Issue by ste7677** [opnsense/core#5644]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

After **updating** to 22.1.3 from an older release, some shown logs in the web interface are wrong. They seem to be leftovers from the prior installation. 

For example the IPSec log: there are two log files:

/var/log/ipsec.log and
/var/log/ipsec/latest.log (symlink)

The web interface displays the content of the (old?) /var/log/ipsec.log

Pressing the "clear log" button also does nothing obvious to the user: It correctly clears the (new?) /var/log/ipsec/latest.log file, but still the content of the old file is shown.

**Additional context**

rm -rd /var/log/* followed by a reboot fixed it completely but of course deletes log history completely.

**reproduce**

Just a guess: This will only occur on updates due to changed log structure.

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 22.1.3-amd64
FreeBSD 13.0-STABLE
OpenSSL 1.1.1m 14 Dec 2021

**Comment by AdSchellevis** [comment]
The old log files are always shown last, clearing all log files in "System: Settings: Logging" should flush all (both new and old).

**Comment by ste7677** [comment]
yes, clearing all log files in "System: Settings: Logging" works

But that is not expected behavior. The "clear logs" button on the specific service page must clear the corresponding logs. Otherwise, it is very confusing to the user.

**Comment by AdSchellevis** [comment]
clear logs should also remove the legacy one, I'll take a look

**Comment by ste7677** [comment]
nope, does not. Verified by just copying a new ipsec log to /var/log/ipsec.log

Note: I just tested this with ipsec deeply. Web GUI logs are the same behavior. Maybe there are more.

**Comment by AdSchellevis** [comment]
@ste7677 https://github.com/opnsense/core/commit/fcbca642624c4a798f9919866172e8e5b16cd3b7 should fix it, thanks for reporting.

**Comment by ste7677** [comment]
Thank you 😀
