### ISSUE TITLE
PPPoE using incorrect IP Address

### ISSUE THREAD

**Issue by utahbmxer** [opnsense/core#5646]
- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

After major upgrade from 21.7 to 22.1, PPPoE connection ignores ISP assigned address (observed in packet capture) and uses the first Virtual IP (IP Alias).  The "WAN Address" is now the second usable IP in my /28 block.  Had to create manual NAT rules to force use of first address which some remote systems are set to allow.

*Tip*: to validate your setup was working with the previous version, use opnsense-revert (https://docs.opnsense.org/manual/opnsense_tools.html#opnsense-revert)

**To Reproduce**

1. Boot/Reboot firewall.
2. Start packet capture
3. Disconnect/Reconnect PPP connection
4. See ISP assigned address of x.x.x.161
5. Check public IP address, which is x.x.x.162

**Expected behavior**

"WAN Address" should be the IP assigned from ISP which has been working for almost 2 years

**Describe alternatives you considered**

Have tried adding VIP of .161, moving to the top, but it seems to be ignored.  This VIP works if used in a manual outbound NAT rule.  Have considered removing all VIPs and rebooting.  However I have many rules which are referencing these so it will require some more downtime to test.

**Screenshots**
![wan-overview](https://user-images.githubusercontent.com/10680366/159996370-044b275e-425b-441b-adab-3baaa7fa5436.png)
![vips](https://user-images.githubusercontent.com/10680366/159996398-e0566f57-82c0-4c01-9e93-424fe4be99df.png)

**Relevant log files**
[ppps.log](https://github.com/opnsense/core/files/8344838/ppps.log)

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 22.1.3-amd64 (FreeBSD 13.0-STABLE, OpenSSL 1.1.1m 14 Dec 2021)
Running on Sophos SG310
Intel(R) Core(TM) i3-4330 CPU @ 3.50GHz (2 cores, 4 threads)
Intel I210 Gigabit Network Connection x8
Intel I350 Gigabit Fiber Network Connection x2

**Comment by fichtner** [comment]
@utahbmxer do you have data points for 22.1, 22.1.1 and 22.1.2 ?

**Comment by utahbmxer** [comment]
I don't as I applied all updates back to back before noticing.  I am planning on reinstalling 21.7 and then stepping through each one to try and pinpoint which release this started in.  I'll try and do this later tonight (located in US) and report back.

**Comment by utahbmxer** [comment]
@fichtner I reinstalled 21.7 (used config importer), then upgraded to 21.7.8.  Confirmed everything was working as expected.  Upgraded to 22.1 and things still worked correctly.  I tried to use opnsense-update tool (opnsense-update -bkpr 22.1.1) to try and do minor updates, but it jumped to 22.1.3.  How can I target those other releases to get data around those?

**Comment by fichtner** [comment]
@utahbmxer in the firmware settings tab select flavour "(other)": 22.1/MINT/22.1.1/OpenSSL

this way you can step through each update. I think this one might have started in 22.1.3.

**Comment by utahbmxer** [comment]
Looks like you're correct, @fichtner.  Loaded my other SG310 (eventually wanting to setup CARP, pppoe?) up to 22.1 and started going through.
22.1.1 - No issue noticed, uses correct IP
22.1.2 - No issue noticed, uses correct IP
22.1.3 - Issue started, seems to use first VIP instead of provider assigned IP
22.1.4 - (for fun) Issue still present, however I noticed that in the GUI, it seems to display correctly.  Dashboard / Interfaces widget shows correct IP.  Interfaces > Overview > WAN seems correct as it shows the primary IP, followed by all the VIPs preceded with a +.  However when I do 'curl http://ifconfig.me' or check in a browser, it shows the first VIP.

Going to keep this firewall racked but plug my cables back into the other one on 21.7.8.  Let me know if you want me to check anything else.

**Comment by fichtner** [comment]
@utahbmxer I've added back a change that seems to make this order enforcement happen although in general it would be nicer if the kernel had some sort of understanding for a primary address other than "first found. [57097e2](https://github.com/opnsense/core/commit/57097e20acdcdd09818275f3f0bc0ca7bd855bc8)

Can you try it?

    # opnsense-patch 57097e2

**Comment by utahbmxer** [comment]
@fichtner sorry for the delay.  I just applied that patch against 22.1.4_1 and reconnected my pppoe connection without a reboot (wasn't sure if that was needed).  Initial tests show it using the correct IP now.
