### ISSUE TITLE
relayd not working

### ISSUE THREAD

**Issue by fraenki** [opnsense/core#565]
It fails to start:

```
# /usr/local/sbin/relayd -d -v -f /var/etc/relayd.conf
startup
fatal: init_filter: DIOCGETSTATUS: Operation not supported by device
```

The [code](https://github.com/mmatuska/relayd/blob/master/src/usr.sbin/relayd/pfe_filter.c#L66-L86) tries to [get the internal packet filter statistics](https://www.freebsd.org/cgi/man.cgi?pf%284%29), but fails to do so.

Any ideas? Wanted to migrate two more pf*** to OPNsense, but without a working relayd this is not possible.

**Comment by fraenki** [comment]
Weird. Manually reinstalling relay solved this issue:

```
# pkg install -f relayd
```

This machine was always running the stable release of OPNsense, so I have no idea what went wrong.

**Comment by fichtner** [comment]
Might be some ABI clash during a patch purge. Relayd wasn't updated in a long time, I guess this was an older installation that was upgraded regularly and not a new install?

**Comment by fraenki** [comment]
Yes, this installation was lurking around for quite some time and finally was brought into service.

**Comment by fichtner** [comment]
Makes sense then, ABI changes didn't happen in a long time now. :)
