### ISSUE TITLE
radvd fails to send advertisements on bridged interface

### ISSUE THREAD

**Issue by mangelajo** [opnsense/core#5652]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

My devices don't get router advertisements over lan. I have a bridge that connects 3 ethernet interfaces, while 1 is used for WAN.

I'm new to OPNSense, so I cannot share any previous working version.

**To Reproduce**

1. Create a bridge
2. Add interfaces
3. Setup IPV6 tracking WAN interface
4. Try to acquire IPv6 on the bridged interface

**Expected behavior**

radvd announces properly without log errors

**Describe alternatives you considered**

**Screenshots**

On my LAN interface I use the following interface config:

![image](https://user-images.githubusercontent.com/1176434/160457147-c08b0950-a231-4e60-8a38-1b8ed3d70f6e.png)

**Relevant log files**

If I look at the radvd logs:

```
root@OPNsense:/var/log # /usr/local/sbin/radvd -p /var/run/radvd.pid -C /var/etc/radvd.conf --debug=5 -n
[Mar 28 17:46:27] radvd (42676): version 2.19 started
[Mar 28 17:46:27] radvd (42676): bridge0 interface definition ok
[Mar 28 17:46:27] radvd (42676): config file, /var/etc/radvd.conf, syntax ok
[Mar 28 17:46:27] radvd (42676): checking ipv6 forwarding not supported
[Mar 28 17:46:27] radvd (42676): radvd startup PID is 42676
[Mar 28 17:46:27] radvd (42676): opened pid file /var/run/radvd.pid
[Mar 28 17:46:27] radvd (42676): locked pid file /var/run/radvd.pid
[Mar 28 17:46:27] radvd (42676): opened pid file /var/run/radvd.pid
[Mar 28 17:46:27] radvd (42676): radvd PID is 42676
[Mar 28 17:46:27] radvd (42676): wrote pid 42676 to pid file: /var/run/radvd.pid
[Mar 28 17:46:27] radvd (42676): validated pid file, /var/run/radvd.pid: 42676
[Mar 28 17:46:27] radvd (42676): bridge0 if_index changed from 0 to 9
[Mar 28 17:46:27] radvd (42676): ioctl(SIOCGIFFLAGS) succeeded on bridge0
[Mar 28 17:46:27] radvd (42676): bridge0 is up
[Mar 28 17:46:27] radvd (42676): bridge0 is running
[Mar 28 17:46:27] radvd (42676): bridge0 supports multicast or is point-to-point
[Mar 28 17:46:27] radvd (42676): mtu for bridge0 is 1500
[Mar 28 17:46:27] radvd (42676): link layer token length for bridge0 is 48
[Mar 28 17:46:27] radvd (42676): prefix length for bridge0 is 64
[Mar 28 17:46:27] radvd (42676): checking ipv6 forwarding of interface not supported
[Mar 28 17:46:27] radvd (42676): no linklocal address configured on bridge0
[Mar 28 17:46:27] radvd (42676): interface bridge0 does not exist or is not set up properly, ignoring the interface
[Mar 28 17:46:27] radvd (42676): polling for 0 second(s), next iface is bridge0
[Mar 28 17:46:27] radvd (42676): timer_handler called for bridge0
[Mar 28 17:46:27] radvd (42676): ioctl(SIOCGIFFLAGS) succeeded on bridge0
[Mar 28 17:46:27] radvd (42676): bridge0 is up
[Mar 28 17:46:27] radvd (42676): bridge0 is running
[Mar 28 17:46:27] radvd (42676): bridge0 supports multicast or is point-to-point
[Mar 28 17:46:27] radvd (42676): mtu for bridge0 is 1500
[Mar 28 17:46:27] radvd (42676): link layer token length for bridge0 is 48
[Mar 28 17:46:27] radvd (42676): prefix length for bridge0 is 64
[Mar 28 17:46:27] radvd (42676): checking ipv6 forwarding of interface not supported
[Mar 28 17:46:27] radvd (42676): no linklocal address configured on bridge0
[Mar 28 17:46:27] radvd (42676): not sending RA for bridge0, interface is not ready
[Mar 28 17:46:27] radvd (42676): send_ra_forall failed on interface bridge0
[Mar 28 17:46:27] radvd (42676): bridge0 next scheduled RA in 16 second(s)
[Mar 28 17:46:27] radvd (42676): polling for 16 second(s), next iface is bridge0
```
**Additional context**

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 22.1.4_1-amd64
FreeBSD 13.0-STABLE
OpenSSL 1.1.1n 15 Mar 2022

**Comment by mangelajo** [comment]
Please, sorry, ignore my bug report, I didn't follow the last two tuneables here:

https://docs.opnsense.org/manual/how-tos/lan_bridge.html#step-six

Is there any technical reason why this isn't done automatically when a bridge is created?

**Comment by fichtner** [comment]
@mangelajo it could create side effects on other setups with bridges that rely on the standard behaviour... it's a bit of a slippery slope there
