### ISSUE TITLE
Show device and VLAN information on interface assignments page for VLAN interfaces

### ISSUE THREAD

**Issue by Zepmann** [opnsense/core#5655]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**

For the purpose of using the interface assignments page to get an overview of which interface is connected to which network, I am missing a solution that will show this information when VLANs are involved.

This issue is based on #5649. VLAN support was given an overhaul in 22.1.4. One result of this overhaul was that generated deviceIds for VLAN's now are in the format vlanNN, where NN is a unique number. Older numbers identified both the network card and the VLAN (e.g. igb0_vlan123), but this is not possible anymore. The result on the interface assignment page is as follows:

![vlan](https://user-images.githubusercontent.com/4273943/160552102-e481cbfa-899b-4284-8e92-cc55399f67ab.png)

The IOT interface is assigned to a VLAN configuration that was created in 22.1.3. The GUEST interface concerns a VLAN configuration created in 22.1.4. The interface assignments page does not show which network device and VLAN the GUEST interface is assigned to.

**Describe the solution you like**

For VLAN assignments (and maybe other configuration types), I would like to know for each interface to which network device and which VLAN it refers. See the following mockup:

![vlan mockup](https://user-images.githubusercontent.com/4273943/160556806-e6096a57-5c6a-4509-ac0f-5b521aae771d.png)

The hyphen makes the distinction between the name of the interface and what follows more clear. After it, the network device name and relevant VLAN are shown. These can be pulled from the VLAN configuratio. Finally, it is appended with the interface description between parentheses (as it is now).

I am not entirely sure what the best way is to portray the VLAN. I used 'vlan123', but 'VLAN 123' might be more correct, to avoid confusing the describing part with the deviceId.

**Describe alternatives you considered**

Alternatives that are considered:

* Reversing the new naming scheme, [which is undesirable](https://github.com/opnsense/core/issues/5649#issuecomment-1079925724=).
* Doing nothing by leaving the situation as it is now. This means that the interface assignments page will provide less of an overview, and users will need to dig deeper for each VLAN interface to see what is connected with what. This is cumbersome when assigning interfaces.

**Comment by fichtner** [comment]
Did this yesterday via 64fb551caa35f83f2c8d47d43d5544cb7590ace6

**Comment by fichtner** [comment]
@Zepmann close then? :)

**Comment by derek-shnosh** [comment]
@fichtner wanted to say kudos for being open to implementing an improvement here, even if it is just a simple quality-of-life fix. 👍
