### ISSUE TITLE
DHCPD stops globally on subnet change for single interface.

### ISSUE THREAD

**Issue by stable-it** [opnsense/core#5656]
**Description**
When changing the configuration of [Interfaces] with enabled [Services] > [DHCPv4] to another subnet beyond the DHCP range, the DHCPD gets stopped for all interfaces without warning.

**Expected behaviour**
- disable DHCP server only for the affected interface
- or, at least, print a more robust warning on interface config changes before globally disabling DHCP instead of the _"Don't forget to adjust the DHCP Server range if needed after applying."_ message.

**Additional notes**
I also would have expected the DHCPD to be startable again after disabling it for the misconfigured interface, as it does not stop on subnet changes for interfaces with the DHCPD disabled in advance.

**Environment**
OPNsense 22.1.4_1-amd64
FreeBSD 13.0-STABLE

**Comment by fichtner** [comment]
I would say logically and practically this is expected. I'm not sure how to mitigate manual configuration on both ends correctly.

**Comment by stable-it** [comment]
Yes, of course is it logically expected, that the DHCPD can not run on a misconfigured network and that in this case some manual work is necessary. 

But, as stated before, I would have expected 
1. a) either a warning that the DHCPD will be **globally** disabled 
   b) or, even better, that the DHCPD gets disabled only for the misconfigured interface.
2. that I can start the DHCPD again, immediately after having disabled it for the misconfigured interface - without the need of correcting the configuration beforehand.

If you think that this is not a bug, I'll be happy to re-open the issue as a 'feature request'!

**Comment by fichtner** [comment]
I'm open for docs PR. I don't recall any complaints about this for the last decade and it's difficult to fix with complex setups.

**Comment by stable-it** [comment]
Thank's for your reply - not sure, where in the docs would be the best place to point this out, but I am going to have a closer look!
