### ISSUE TITLE
TLS validation does not work in Unbound DNS over TLS (DoT)

### ISSUE THREAD

**Issue by oittaa** [opnsense/core#5657]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

TLS validation in Unbound DNS over TLS (DoT) does not work. The server answers even if the hostname is wrong.

**To Reproduce**

1. I installed OPNsense on a virtual machine with 2 network interfaces and basically set everything to default.
2. After installation I enabled DNSSEC and DoT, but I typed wrong domain name in the DoT configuration to test it out.
3. To my surprise the server replied without errors.

**Expected behavior**

Reject invalid certificates.

**Describe alternatives you considered**

A clear and concise description of any alternative solutions or workaround you considered.

**Screenshots**

![image](https://user-images.githubusercontent.com/8972248/160715752-6f2e82af-188f-4c71-b4ef-5783abeefa20.png)
![image](https://user-images.githubusercontent.com/8972248/160715790-7bbb95b5-058f-4b69-9bae-a2770113dd9d.png)

**Relevant log files**

If applicable, information from log files supporting your claim.

**Additional context**

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 22.1.4 (amd64, OpenSSL).

**Comment by oittaa** [comment]
For comparison this is what Unbound on Debian would return if the DoT hostname didn't match. 
![debian](https://user-images.githubusercontent.com/8972248/160718515-072297ef-c913-4abf-92eb-5688d5a830b5.png)

**Comment by fichtner** [comment]
@oittaa we should first make sure unbound actually had the correct configuration and was restarted (apply button). Does the /var/unbound/etc/dot.conf file contain the correct information?

**Comment by swhite2** [comment]
Just tested this out: 

```
# drill @127.0.0.1 nos.nl
;; ->>HEADER<<- opcode: QUERY, rcode: SERVFAIL, id: 55847
;; flags: qr rd ra ; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0
;; QUESTION SECTION:
;; nos.nl.      IN      A

;; ANSWER SECTION:

;; AUTHORITY SECTION:

;; ADDITIONAL SECTION:

;; Query time: 255 msec
;; SERVER: 127.0.0.1
;; WHEN: Wed Mar 30 09:16:03 2022
;; MSG SIZE  rcvd: 24
```
with:

```
 server:
    tls-cert-bundle: /etc/ssl/cert.pem
 forward-zone:
   name: "."
   forward-tls-upstream: yes
   forward-addr: 45.90.30.65@853#wrong-hostname.io

```

and as expected:

```
<27>1 2022-03-30T09:16:03+02:00 OPNsense.localdomain unbound 58995 - [meta sequenceId="16"] [58995:1] error: ssl handshake failed crypto error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed
<29>1 2022-03-30T09:16:03+02:00 OPNsense.localdomain unbound 58995 - [meta sequenceId="17"] [58995:1] notice: ssl handshake failed 45.90.30.65 port 853
<27>1 2022-03-30T09:16:03+02:00 OPNsense.localdomain unbound 58995 - [meta sequenceId="18"] [58995:1] error: ssl handshake failed crypto error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed
<29>1 2022-03-30T09:16:03+02:00 OPNsense.localdomain unbound 58995 - [meta sequenceId="19"] [58995:1] notice: ssl handshake failed 45.90.30.65 port 853
<27>1 2022-03-30T09:16:03+02:00 OPNsense.localdomain unbound 58995 - [meta sequenceId="20"] [58995:1] error: ssl handshake failed crypto error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed
<29>1 2022-03-30T09:16:03+02:00 OPNsense.localdomain unbound 58995 - [meta sequenceId="21"] [58995:1] notice: ssl handshake failed 45.90.30.65 port 853
<27>1 2022-03-30T09:16:03+02:00 OPNsense.localdomain unbound 58995 - [meta sequenceId="22"] [58995:1] error: ssl handshake failed crypto error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed
<29>1 2022-03-30T09:16:03+02:00 OPNsense.localdomain unbound 58995 - [meta sequenceId="23"] [58995:1] notice: ssl handshake failed 45.90.30.65 port 853
<27>1 2022-03-30T09:16:03+02:00 OPNsense.localdomain unbound 58995 - [meta sequenceId="24"] [58995:1] error: ssl handshake failed crypto error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed
<29>1 2022-03-30T09:16:03+02:00 OPNsense.localdomain unbound 58995 - [meta sequenceId="25"] [58995:1] notice: ssl handshake failed 45.90.30.65 port 853
<27>1 2022-03-30T09:16:03+02:00 OPNsense.localdomain unbound 58995 - [meta sequenceId="26"] [58995:1] error: ssl handshake failed crypto error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed
<29>1 2022-03-30T09:16:03+02:00 OPNsense.localdomain unbound 58995 - [meta sequenceId="27"] [58995:1] notice: ssl handshake failed 45.90.30.65 port 853
<27>1 2022-03-30T09:16:03+02:00 OPNsense.localdomain unbound 58995 - [meta sequenceId="28"] [58995:1] error: ssl handshake failed crypto error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed
<29>1 2022-03-30T09:16:03+02:00 OPNsense.localdomain unbound 58995 - [meta sequenceId="29"] [58995:1] notice: ssl handshake failed 45.90.30.65 port 853
<27>1 2022-03-30T09:16:03+02:00 OPNsense.localdomain unbound 58995 - [meta sequenceId="30"] [58995:1] error: ssl handshake failed crypto error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed
<29>1 2022-03-30T09:16:03+02:00 OPNsense.localdomain unbound 58995 - [meta sequenceId="31"] [58995:1] notice: ssl handshake failed 45.90.30.65 port 853
<27>1 2022-03-30T09:16:03+02:00 OPNsense.localdomain unbound 58995 - [meta sequenceId="32"] [58995:1] error: ssl handshake failed crypto error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed
<29>1 2022-03-30T09:16:03+02:00 OPNsense.localdomain unbound 58995 - [meta sequenceId="33"] [58995:1] notice: ssl handshake failed 45.90.30.65 port 853
<27>1 2022-03-30T09:16:03+02:00 OPNsense.localdomain unbound 58995 - [meta sequenceId="34"] [58995:1] error: ssl handshake failed crypto error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed
<29>1 2022-03-30T09:16:03+02:00 OPNsense.localdomain unbound 58995 - [meta sequenceId="35"] [58995:1] notice: ssl handshake failed 45.90.30.65 port 853
```

**Comment by oittaa** [comment]
I think I had clicked that "apply" button many times. I just restarted the virtual machine, put logging to level 4, and tried to query `reddit.com` and the DNS server replied again with A records even though it should have rejected.

![image](https://user-images.githubusercontent.com/8972248/160790499-501364b4-02ba-43f5-b084-b4606606d5e6.png)
![image](https://user-images.githubusercontent.com/8972248/160790576-0301e60e-1825-46a1-97d2-9a5fb6f55ccf.png)

But now while writing this message I tested to query `nos.nl` like @[swhite2](https://github.com/swhite2)  had in his example and it got rejected properly. `gmail.com` and `google.com` are also rejected correctly even though they returned A records previously. `reddit.com` still returns A records, so maybe these are coming from some cache?

**Comment by swhite2** [comment]
Unless Unbound->General->DNS Cache Flush is checked, the system will reload an existing cache - this behaviour is not the default mode for Unbound. 

Most likely `reddit.com` reached a TTL timer so a new query was done, at this point it would adhere to the certificate check. This is assuming you already did a query at some point without pressing 'apply'. 

You can manually flush the cache by running `configctl unbound cache flush`.

**Comment by oittaa** [comment]
> Unless Unbound->General->DNS Cache Flush is checked, the system will reload an existing cache - this behaviour is not the default mode for Unbound.

This probably confused me, since for example the default config on Debian just flushes the cache if you restart the service. I think the issue can be closed. Thanks for the help.

**Comment by fichtner** [comment]
Context: a number of people complained about cache flush in Unbound restart over the years. Cache retain was introduced by default in 21.7, but can be disabled like described.
