### ISSUE TITLE
GitHub Actions and unit testing

### ISSUE THREAD

**Issue by oittaa** [opnsense/core#5667]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

Having unit tests and linter run on every pull request would be a helpful addition. Maybe it would even encourage people to write more unit tests under https://github.com/opnsense/core/tree/master/src/opnsense/mvc/tests

**Describe the solution you like**

Add some Actions under `.github/workflows`

**Describe alternatives you considered**

A clear and concise description of any alternative solutions or features you considered.

**Additional context**

Add any other context or screenshots about the feature request here or links to relevant forum thread or similar

**Comment by AdSchellevis** [comment]
it would be practical to offer some integration, not sure what's needed for this to happen to be honest.

**Comment by fichtner** [comment]
Everything is run via nightly.opnsense.org

**Comment by oittaa** [comment]
I've never used GitHub Actions in FreeBSD before, but there seems to be a way to run virtual machines with it. No idea how long the full build would take. https://github.com/vmactions/freebsd-vm

**Comment by oittaa** [comment]
Seems to be working. https://github.com/oittaa/core/runs/5805822964?check_suite_focus=true

I think it would make sense to first run linter and phpunit on Ubuntu to get faster results, if there's a simple typo or other errors.

**Comment by oittaa** [comment]
[Here](https://github.com/oittaa/core/runs/5809463371?check_suite_focus=true)'s an example of `phpunit` run on Ubuntu. I had to copy couple of files to /usr/local, but otherwise it seems to be working out of the box. The same tests are failing as on my real FeeBSD OPNsense installation.

**Comment by AdSchellevis** [comment]
> The same tests are failing as on my real FeeBSD OPNsense installation.

I noticed the same thing recently as well, we have to figure out why that is at some point in time.
