### ISSUE TITLE
 DHCPv6 client configuration - UI option for overriding config is totally ignored

### ISSUE THREAD

**Issue by PaulGWebster** [opnsense/core#5672]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

When you set a custom config path in the UI/Interface for DHCPv6 Client, it is totally ignored by opnsense.

To work around this, I cat'd my custom config into /vat/etc/dhcp6c.conf and set it system immutable with 'chflags schg'.

I have included an image of what the UI believes the path to the config presently is(this is after a reboot) and this is what the process believes it is: 

`root         38930   0.0  0.0  12792  2524  -  Is   23:34      0:00.03 /usr/local/sbin/dhcp6c -c /var/etc/dhcp6c.conf -p /var/run/dhcp6c.pid`

Presumable this is a bug with the UI not passing the value to the appropriate configuration broker, not to sure!

My setup is over PPPOE so ra0->pppoe0, I am not sure if this is related to the fault or not.

**To Reproduce**

1. Simlpy try to use a custom config line with DHCP-PD client

**Expected behavior**

To use the custom configuration file

**Describe alternatives you considered**

chflags schg

**Screenshots**

![image](https://user-images.githubusercontent.com/401142/161446355-d0e9eef8-b630-451e-823e-5625d6f2359b.png)

**Relevant log files**

None that are helpful or show anything related to the problem

**Additional context**

Custom configuration file was required to specify a custom up script as the supplied one was unable to correctly assign ip addresses based on the /56 prefix assigned by my isp

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 22.1.4_1-amd64
FreeBSD 13.0-STABLE
OpenSSL 1.1.1n 15 Mar 2022
CPU: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (2800.00-MHz K8-class CPU)
re0: <RealTek 8168/8111 B/C/CP/D/DP/E/F/G PCIe Gigabit Ethernet> port 0xd000-0xd0ff mem 0xdf314000-0xdf314fff,0xdf310000-0xdf313fff at device 0.1 on pci2
ure0: <Realtek USB 10/100/1000 LAN, class 0/0, rev 3.00/30.00, addr 5> on usbus0
miibus1: <MII bus> on ure0
ue0: <USB Ethernet> on ure0

**Comment by fichtner** [comment]
It worked for me on latest devel.

# cat /usr/local/dhcp6c.conf 
#foobar
# cat /var/etc/dhcp6c.conf
#foobar


Cheers,
Franco

**Comment by PaulGWebster** [comment]
> It worked for me on latest devel.
> 
> ```
> # cat /usr/local/dhcp6c.conf 
> #foobar
> # cat /var/etc/dhcp6c.conf
> #foobar
> ```
> 
> Cheers, Franco

root@gateway:~ # cat /var/etc/dhcp6c.conf
interface pppoe0 {
        send ia-pd      0;
        request         domain-name-servers,domain-name,ntp-servers,sip-server-address;
        # sip-domain-name,nis-server-address,nis-domain-name,nisp-server-address,nisp-domain-name,bcmcs-server-address,bcmcs-domain-namedomain-name-servers,domain-name,ntp-servers,sip-server-address,sip-domain-name,nis-server-address,nis-domain-name,nisp-server-address,nisp-domain-name;
        script          "/usr/local/opnsense_additions/dhcpv6-up";
};

id-assoc pd {
        prefix ::/56 infinity;
};

**Comment by fichtner** [comment]
I don’t understand.

**Comment by PaulGWebster** [comment]
I do not really understand what you do not understand.

**Comment by fichtner** [comment]
Ok, I'm not in the mood for this type of community support and feel bad for try to help. Unsubscribed.
