### ISSUE TITLE
system: CRL support on PHP 8

### ISSUE THREAD

**Issue by fichtner** [opnsense/core#5675]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

Since PHP 8 changed internals again and our old CRL patching had been on life support ever since we need to change the approach to something more portable inside code to deal with keeping CRL support in the project.

**To Reproduce**

Use functionality under System: Trust: Revocation

**Expected behavior**

CRL keeps working after PHP 8 migration.

**Describe alternatives you considered**

No.

**Additional context**

Old patch: https://github.com/opnsense/ports/blob/master/security/php74-openssl/files/patch-openssl.c

```
% git grep openssl_crl
src/etc/inc/certs.inc:$openssl_crl_status = array(
src/etc/inc/certs.inc:    $crl_res = openssl_crl_new($ca_str_crt, $crl['serial'], $crl['lifetime']);
src/etc/inc/certs.inc:            openssl_crl_revoke_cert($crl_res, base64_decode($cert["crt"]), $cert["revoke_time"], $cert["reason"]);
src/etc/inc/certs.inc:    openssl_crl_export($crl_res, $crl_text, $ca_str_key);
src/www/system_crlmanager.php:                  <td><?=$openssl_crl_status[$cert["reason"]]; ?></td>
src/www/system_crlmanager.php:                  foreach ($openssl_crl_status as $code => $reason) :?>
```

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 19.1.1 (amd64, OpenSSL).
Intel® Xeon™ E3-1225V5 3.3Ghz Quad Core
Network Intel® I210-AT

**Comment by oittaa** [comment]
I'm not familiar how the CRL system is used here, but would a pure PHP implementation like https://github.com/phpseclib/phpseclib work?

**Comment by fichtner** [comment]
In theory yes as version 2 of phpseclib is already included in core
