### ISSUE TITLE
Improve resilience by monitoring and restarting services, or the whole system

### ISSUE THREAD

**Issue by mvglasow** [opnsense/core#5680]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**

I am running OPNsense on a home router system. Among others, I use its VPN functionality to connect to my home network while I am away. Recently, OPNsense stopped responding to any requests from outside while I was away. Back home, I found the system still responded to ping requests, but offered no connectivity, no web GUI and no response on the serial console. After power cycling the system, it came up again and ran normally.

I would like OPNsense to include mechanisms to monitor its own availability and automatically recover from failures which are recoverable.

**Describe the solution you like**

The first step would be for OPNsense to monitor its services, e.g.:
* Is the process running?
* Is the system responding on the port associated with the service?

Monitoring WAN connectivity could also be an option, although we would need to rule out failures on the WAN line with no fault in OPNsense.

If a service is found to be unresponsive, OPNsense should initiate recovery measures. I would recommend an escalation approach, i.e. trying one step and, if that fails, try a more radical one:
* Restart the service(s) which failed
* Reboot (exact conditions TBD, especially if multiple services have failed)
* Run `opnsense-bootstrap` to ensure all system files are OK (possibly only following a system health check)
* Possibly other means of remediation, such as restoring a known good image

Different use cases might require different scenarios: if you have staff on-site or on-call 24/7 and are capable of conducting a forensic investigation, you might not want any of this to happen automatically, as it may destroy forensic evidence. On the other end of the scale, if you’re running a system as a one-(wo)man show and need access even if you’re away from the system for a couple of weeks, you might want to automate as much of the try-and-error recovery procedures as you can.

In conclusion, this feature should be configurable. Levels could be:
* No attempt to auto-recover from anything (behave like the current version does)
* Per service: Restart service if no longer reachable and/or process is no longer running
* Reboot if service restart does not provide remediation (possibly to be configured per service, or m-out-of-n for designated services)
* Run `opnsense-bootstrap` if a reboot does not provide remediation

**Describe alternatives you considered**

No real alternatives. If certain features are too complex/time-consuming to implement, a subset would already provide some relief. Focus should be on providing *some* kind of remediation, not on nailing everything on day one.

Providing “run a command” as a remediation option would make this somewhat user-definable. Bonus for monitoring the output of the user-defined command and proceeding to the next step on failure.

**Additional context**

I have just recently switched to OPNsense from pfSense (which I have used for some 7–8 years), and have experienced similar outages with pfSense. Most failures so far were on pfSense, Some of them attributable to hardware failures, though I did not keep track.

The one OPNsense outage I have experienced so far was not. I cannot tell if it was due to a malfunction or a DoS attack that might have brought down the system.

**Comment by itractus** [comment]
I will want to have a look at this, since I think it would improve the project a lot. Maybe as a plugin? After my workday I will see what could be used
