### ISSUE TITLE
openvpn - client export - download - filetype headers not set - file saves as filename.ovpn.txt

### ISSUE THREAD

**Issue by ITJamie** [opnsense/core#5687]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [ ] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [ ] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

Right now the ovpnfile type export option has an issue on IOS. The file comes down as `[filename].ovpn.txt` on ios/safari due to the headers. This means its not easy to import into openvpn apps on ios.

some quick searching appears that the headers need to be more specific to the filetype during the download. eg
```
    'Content-Type' => 'text/ovpn',
    'Content-Length' => filesize(storage_path('file.ovpn')),
    'Content-Disposition' => 'attachment; filename="file.ovpn"'
```
**To Reproduce**

Steps to reproduce the behavior on an iphone safari:
1. Go to 'VPN>OpenVPN>Client Export'
2. Choose "File Only" as Export Type
3. Scroll to bottom, Choose any of the download buttons beside a cert
4. file will download as `[filename].ovpn.txt`

**Expected behavior**

File to download without the .txt extension allowing it to be easily opened in an openvpn app

**Describe alternatives you considered**

It is possible. but quite painful to work around this.
Instead use chrome on IOS. When it try's to open the file you can then open the more menu, choose the save to files option, here you will be allowed to name the file yourself and can give it the ovpn extension.
Ive tried several other browsers on IOS (Opera, brave, dolphin). none of them have even offered a download screen due to fact the headers are not set

**Comment by AdSchellevis** [comment]
@ITJamie https://github.com/opnsense/core/commit/f91d7f44e63383aef93a17701400266149505a42 should do the trick
