### ISSUE TITLE
Unbound: creating an override alias shows list of domain names instead of fqdn

### ISSUE THREAD

**Issue by jdeluyck** [opnsense/core#5690]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

In the new UI for adding Unbound override aliases, it shows a list of domain names of the override you want to add an alias to, and not the fqdn. When you have multiple override entries with the same domain name it's not possible to distinguish between them.

![override-domain-bug](https://user-images.githubusercontent.com/5451787/162580117-8ef48803-9255-4c0f-9170-97361aa070ee.png)

**To Reproduce**

1. Add several unbound overrides with the same domain name entry
2. Try to add an alias to any of them
3. Useless list ;)

**Expected behavior**

Show the fqdn instead of just the domain name.

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 22.1.5-amd64

**Comment by AdSchellevis** [comment]
@jdeluyck https://github.com/opnsense/core/commit/714eca2b18ebc6846ef4bacb86d561d6eada8b88 should fix the visibility issue.  (also https://github.com/opnsense/core/issues/5694)
