### ISSUE TITLE
Unbound: modifying an override alias from just hostname to hostname+domain throws error

### ISSUE THREAD

**Issue by jdeluyck** [opnsense/core#5691]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

I added an alias to an existing unbound override. I realised then that I needed to also override the domain, so I edited the alias, added it and hit save. At this point I was greeted with the following error:

```
/usr/local/opnsense/mvc/app/controllers/OPNsense/Base/ApiMutableModelControllerBase.php:443: Too few arguments to function OPNsense\Base\ApiMutableModelControllerBase::setBase(), 2 passed in /usr/local/opnsense/mvc/app/controllers/OPNsense/Unbound/Api/SettingsController.php on line 213 and at least 3 expected
```

**To Reproduce**

1. Add an alias to an unbound override without domain
2. Edit the alias and add the domain
3. hit save

**Expected behavior**

Alias is edited without error

**Environment**

OPNsense 22.1.5-amd64

**Comment by AdSchellevis** [comment]
Maybe browser issue, the "add" button should be hidden when no domain is selected. couldn't reproduce this on my end.

**Comment by Starkstromkonsument** [comment]
I can reproduce this. Screenshot of the exception:

![grafik](https://user-images.githubusercontent.com/53019449/162620790-6408c494-1a48-40fe-b1a6-fe57936d408f.png)

**Comment by Starkstromkonsument** [comment]
Ah, I think this might be a misunderstanding. We are talking of leaving the field "Domain" empty, not "Host override".

**Comment by Starkstromkonsument** [comment]
Debugging data from the Reporter (PHP Error):
```

[10-Apr-2022 15:33:40 Europe/Berlin] ArgumentCountError: Too few arguments to function OPNsense\Base\ApiMutableModelControllerBase::setBase(), 2 passed in /usr/local/opnsense/mvc/app/controllers/OPNsense/Unbound/Api/SettingsController.php on line 213 and at least 3 expected in /usr/local/opnsense/mvc/app/controllers/OPNsense/Base/ApiMutableModelControllerBase.php:443
Stack trace:
#0 /usr/local/opnsense/mvc/app/controllers/OPNsense/Unbound/Api/SettingsController.php(213): OPNsense\Base\ApiMutableModelControllerBase->setBase('alias', 'aliases.alias')
#1 [internal function]: OPNsense\Unbound\Api\SettingsController->setHostAliasAction('581e5ab4-54ed-4...')
#2 [internal function]: Phalcon\Dispatcher\AbstractDispatcher->callActionMethod(Object(OPNsense\Unbound\Api\SettingsController), 'setHostAliasAct...', Array)
#3 [internal function]: Phalcon\Dispatcher\AbstractDispatcher->dispatch()
#4 /usr/local/opnsense/www/api.php(26): Phalcon\Mvc\Application->handle('/api/unbound/se...')
#5 {main}
[10-Apr-2022 15:44:15 Europe/Berlin] ArgumentCountError: Too few arguments to function OPNsense\Base\ApiMutableModelControllerBase::setBase(), 2 passed in /usr/local/opnsense/mvc/app/controllers/OPNsense/Unbound/Api/SettingsController.php on line 213 and at least 3 expected in /usr/local/opnsense/mvc/app/controllers/OPNsense/Base/ApiMutableModelControllerBase.php:443
Stack trace:
#0 /usr/local/opnsense/mvc/app/controllers/OPNsense/Unbound/Api/SettingsController.php(213): OPNsense\Base\ApiMutableModelControllerBase->setBase('alias', 'aliases.alias')
#1 [internal function]: OPNsense\Unbound\Api\SettingsController->setHostAliasAction('581e5ab4-54ed-4...')
#2 [internal function]: Phalcon\Dispatcher\AbstractDispatcher->callActionMethod(Object(OPNsense\Unbound\Api\SettingsController), 'setHostAliasAct...', Array)
#3 [internal function]: Phalcon\Dispatcher\AbstractDispatcher->dispatch()
#4 /usr/local/opnsense/www/api.php(26): Phalcon\Mvc\Application->handle('/api/unbound/se...')
#5 {main}
```

**Comment by AdSchellevis** [comment]
@jdeluyck @Starkstromkonsument thanks, https://github.com/opnsense/core/commit/44b669d8ffc3ad5e78f3526e7bb37dd0bdb95891 should fix it.

**Comment by AdSchellevis** [comment]
cc @swhite2

**Comment by Starkstromkonsument** [comment]
It works perfectly now, thank you.

**Comment by AdSchellevis** [comment]
@Starkstromkonsument Thanks for confirming, we'll make sure these changes hit a release version as soon as possible.
