### ISSUE TITLE
Unbound: Upgrade to opnsense 22.1.5 clears all overrides

### ISSUE THREAD

**Issue by Starkstromkonsument** [opnsense/core#5693]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**
My config contains a lot of overrides for internal hostnames (A, MX and Aliases). The upgrade to opnsense 22.1.5 has cleared all of them and leaves me with an empty page. I found a corresponding migration error in the general log.

**To Reproduce**

1. Install OPNsense 22.1.4
2. Create Overrides
3. Everything works ok
4. Upgrade to OPNsense 22.1.5
5. See error (empty page at overrides)

**Expected behavior**
Do not delete my existing overrides during upgrade.

**Screenshots**

Empty overrides page after upgrade:
![grafik](https://user-images.githubusercontent.com/53019449/162612828-1cb1d04d-da27-4da0-859f-bad8a2b35713.png)

**Relevant log files**
System --> Log Files --> General
![grafik](https://user-images.githubusercontent.com/53019449/162613058-8410d35c-fd4a-4c37-997c-709746ae924f.png)

**Additional context**

Probably related to: #5488

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 22.1.5-amd64
FreeBSD 13.0-STABLE
OpenSSL 1.1.1n  15 Mar 2022

**Comment by Starkstromkonsument** [comment]
In addition: I'm unable to manually reconfigure my setup to get host overrides and aliases working again. Please see #5694. This change breaks my setup!

**Comment by AdSchellevis** [comment]
@Starkstromkonsument can you try https://github.com/opnsense/core/commit/ff11cde38e8d16d8d51ddd01c19af282cebe3d8d and run a migration next.

```
opnsense-patch ff11cde
/usr/local/opnsense/mvc/script/run_migrations.php
```

**Comment by Starkstromkonsument** [comment]
@AdSchellevis Thank you for your very fast reply. I tried it, but got errors:

```
root@vm-proxy:/home/alex # opnsense-patch ff11cde
Fetched ff11cde via https://github.com/opnsense/core
Hmm...  Looks like a unified diff to me...
The text leading up to this was:
--------------------------
|From ff11cde38e8d16d8d51ddd01c19af282cebe3d8d Mon Sep 17 00:00:00 2001
|From: Ad Schellevis <ad@opnsense.org>
|Date: Sat, 9 Apr 2022 08:50:38 +0200
|Subject: [PATCH] Services / Unbound - fix domain override ip validation as it
| may contain a port number using the following format x.x.x.x@53  cc @swhite2
|
|When migration failed into 22.1.5, this patch in combination with `/usr/local/opnsense/mvc/script/run_migrations.php` should fix migration issues. No new model version is needed as
|the previous version wasn't able to migrate in this case. closes https://github.com/opnsense/core/issues/5693
|---
| .../Unbound/FieldTypes/UnboundServerField.php | 68 +++++++++++++++++++
| .../app/models/OPNsense/Unbound/Unbound.xml   |  2 +-
| 2 files changed, 69 insertions(+), 1 deletion(-)
| create mode 100644 src/opnsense/mvc/app/models/OPNsense/Unbound/FieldTypes/UnboundServerField.php
|
|diff --git a/src/opnsense/mvc/app/models/OPNsense/Unbound/FieldTypes/UnboundServerField.php b/src/opnsense/mvc/app/models/OPNsense/Unbound/FieldTypes/UnboundServerField.php
|new file mode 100644
|index 0000000000..84bb4d759e
|--- /dev/null
|+++ b/src/opnsense/mvc/app/models/OPNsense/Unbound/FieldTypes/UnboundServerField.php
--------------------------
(Creating file opnsense/mvc/app/models/OPNsense/Unbound/FieldTypes/UnboundServerField.php...)
Patching file opnsense/mvc/app/models/OPNsense/Unbound/FieldTypes/UnboundServerField.php using Plan A...
Empty context always matches.
Hunk #1 succeeded at 1.
Hmm...  The next patch looks like a unified diff to me...
The text leading up to this was:
--------------------------
|diff --git a/src/opnsense/mvc/app/models/OPNsense/Unbound/Unbound.xml b/src/opnsense/mvc/app/models/OPNsense/Unbound/Unbound.xml
|index 3f758b5645..26f9bd25f5 100644
|--- a/src/opnsense/mvc/app/models/OPNsense/Unbound/Unbound.xml
|+++ b/src/opnsense/mvc/app/models/OPNsense/Unbound/Unbound.xml
--------------------------
Patching file opnsense/mvc/app/models/OPNsense/Unbound/Unbound.xml using Plan A...
Hunk #1 succeeded at 225.
done
All patches have been applied successfully.  Have a nice day.
root@vm-proxy:/home/alex # /usr/local/opnsense/mvc/script/run_migrations.php
*** OPNsense\Unbound\Unbound Migration failed, check log for details
root@vm-proxy:/home/alex # 
```
Errors in the log:
![grafik](https://user-images.githubusercontent.com/53019449/162618557-c4e7d544-138f-4ebb-b2b9-e1e3a302ce6d.png)

Do you need any more debugging data?

**Comment by AdSchellevis** [comment]
> Do you need any more debugging data?

Yes please, install https://github.com/opnsense/core/commit/626c3dbf558efbeadb64c5f6837904db976c80c0 using the same procedure and dump the log output again. We don't seem to flush the actual data, which makes it impossible to see if there's broken data or a validation issue at this point.  When we know why it failed, we can assess next steps. Thanks!

**Comment by Starkstromkonsument** [comment]
Here you go, the "malicious" hostname is `vm-proxy-lan_intern`

![grafik](https://user-images.githubusercontent.com/53019449/162619808-1fae2144-989c-4e62-8b0e-88b51721bf41.png)

**Comment by AdSchellevis** [comment]
@Starkstromkonsument I would advise to change the hostname, as underscores  aren't valid characters for hostnames (https://en.wikipedia.org/wiki/Hostname https://www.rfc-editor.org/rfc/rfc952).  See also https://github.com/opnsense/core/issues/4679.

For some other record types underscores are valid, as this restriction has been lifted by rfc 1281 (https://datatracker.ietf.org/doc/html/rfc2181#section-11), this just isn't the case for hostnames.

The migration itself isn't necessarily wrong, but these issues can be quite annoying if the old module didn't validate data correctly. We could automatically replace underscores in the migration and change the label during the process to avoid further breakage.

**Comment by Starkstromkonsument** [comment]
Thank you for your hint. I changed the hostname by manually editing my config.xml an the migration was completed successfully now.
