### ISSUE TITLE
Unbound: usage of aliases with new MVC

### ISSUE THREAD

**Issue by Starkstromkonsument** [opnsense/core#5694]
**Important notices**

Our forum is located at https://forum.opnsense.org , please consider joining discussions there in stead of using GitHub for these matters.

Before you ask a new question, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

Related to: https://github.com/opnsense/core/pull/5488

I use many aliases for internal services running on internal hosts. I have questions:

### Question 1
How can different hosts within the same domain be distinguished? I created some host overrides to demonstrate my problem:

![grafik](https://user-images.githubusercontent.com/53019449/162613708-f550f600-8cb5-4599-8b9b-bb1e9cf442ad.png)

and now I try to create an alias for one of the hosts:

![grafik](https://user-images.githubusercontent.com/53019449/162613770-8910f059-713d-4595-88dc-4f5ef855be70.png)

The drop down menu only contains the domains, but not the hosts.

### Question 2
 How am I supposed to know to which host override an alias belongs?
![grafik](https://user-images.githubusercontent.com/53019449/162613869-c28db121-c8fd-49d7-bc4f-2ce104480e4b.png)

Thank you for working on the migration to MVC but IMHO this is WIP and not ready for release yet. It breaks my setup and I have to downgrade my opnsense now to get my network properly working again.

**Comment by AdSchellevis** [comment]
@Starkstromkonsument https://github.com/opnsense/core/commit/714eca2b18ebc6846ef4bacb86d561d6eada8b88 should fix the visibility issue. cc @swhite2

**Comment by Starkstromkonsument** [comment]
Thank you! It fixes my "Question 1". 

But it leaves "Question 2" unfixed. I meanwhile figured out, that only the aliases of the checked host override are shown. Is there a way to show all aliases? One might not always know to which host override an alias belongs, when searching for a host

**Comment by AdSchellevis** [comment]
@Starkstromkonsument it's a master/detail view indeed. You could always add a ticket to be able to multi (all) select the parent (which would require the parent's id in the grid as well). I don't think this is a priority at the moment, but if more people miss such a feature it might be worth looking into that.
