### ISSUE TITLE
Unbound: please readd the "description" field to aliases of host overrides in the new MVC

### ISSUE THREAD

**Issue by Starkstromkonsument** [opnsense/core#5695]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**
Before the migration of the overrides to the new MVC, aliases had a "Description" filed too. It is gone since OPNsense 22.1.5.

**Expected behavior**
Please readd the field "Description" for aliases in the new MVC. Thank you!

**Screenshots**
Before 22.1.5
![grafik](https://user-images.githubusercontent.com/53019449/162619665-1b4f58c2-d6a0-4f69-aae7-6e47e316db7b.png)

Since 22.1.5
![grafik](https://user-images.githubusercontent.com/53019449/162619683-db13475c-3cf7-4289-b53c-7f76136fef5e.png)
![grafik](https://user-images.githubusercontent.com/53019449/162619722-8df692a5-e732-47c0-965f-a4f344d716dd.png)

**Additional context**

Related to: #5488

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 22.1.5-amd64
FreeBSD 13.0-STABLE
OpenSSL 1.1.1n 15 Mar 2022

**Comment by AdSchellevis** [comment]
@Starkstromkonsument here you go https://github.com/opnsense/core/commit/3a9763d5273bbf65d2e13f3e017dad5b0980dae8, you will have to restart the migration to import these by the way. While here I also change the migration a bit to prevent stumbling over the underscores.

https://github.com/opnsense/core/commit/3a9763d5273bbf65d2e13f3e017dad5b0980dae8#diff-63775beace878e13e414328a42954867227c45227d440b6d97a0657e3cb84738R66

**Comment by AdSchellevis** [comment]
cc @swhite2
