### ISSUE TITLE
Unbound Domain Overrides with _

### ISSUE THREAD

**Issue by egi815** [opnsense/core#5697]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x ] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x ] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

A clear and concise description of what the bug is, including last known working version (if any).

In Unblund -> Domain overrides it is not possible to enter a _ in Domainname like
_msdcs.office.consoto.com

1. Services -> Unbound DNS -> Domains Override
2. Add Domain with _
3. Domaincheck: A valid domain must be specified.

**Expected behavior**

A _ is valid in Domains (at least in Microsoft domain controllers)

**Describe alternatives you considered**

A clear and concise description of any alternative solutions or workaround you considered.
Pleas allow _ in Domains.

Software version used and hardware type if relevant, e.g.:
OPNsense 22.1.5 (amd64, OpenSSL).
AMD EPYC 3251

**Comment by NOYB** [comment]
Hyphen is not a valid domain name character.  As an override perhaps hyphen should be allowed.  Or not.  I've used them in the past but don't really care either way.  Probably good idea to not use hyphen anyway just to avoid future problems with a system that doesn't support them.

**Comment by swhite2** [comment]
While in the general sense of a domain name the RFCs do not state any restrictions, the record types used by Unbound are of the type A and AAAA in the case of domain overrides. Therefore, the domain names must be further restricted to the rules of a hostname, which does not allow `_` underscores.

As @NOYB pointed out, it is not a good idea to start accepting it now as it might unearth other problems.

**Comment by egi815** [comment]
Well in fact microsoft domain controllers use underscore domains by default and it is neccesary to forward requests to them.
It is only a gui problem, because unbound certainly handles these domains correctly. (as tested by entering them in the config file)
please allow them again.. as before 22.1.5

**Comment by NOYB** [comment]
@egi815
If you really need to use underscore, and the powers that be decide against accepting them.  You can customize the mask to allow them.
/usr/local/opnsense/mvc/app/models/OPNsense/Unbound/Unbound.xml

**Comment by swhite2** [comment]
As an alternative you can also follow the guide specified here https://docs.opnsense.org/manual/unbound.html#advanced-configurations

**Comment by egi815** [comment]
hmm. 
I guess anybody with domain controller in his network will need these underscores...
and not only these,
Lets encrypt _acme-challenge also has an underscore...  it is an absolute normal digit in domains..

_acme-challenge.api IN TXT iAlqLW...
_autodiscover._tcp 3600 IN SRV 0 5 443 mail.......


This is not a special case, but absolutly standard... in almost every environment... exept home.. i guess.

and anyway it also does also not work in hosts... not only in domains.  
i cannot enter the _ anywhere there...

sorry this is simply a bug..

**Comment by egi815** [comment]
@NOYB i read this documentation for advanced configuration now.
but these Files will not be saved with configuration, or will they? and will they survive an release-Upgrade?

**Comment by NOYB** [comment]
The `/usr/local/opnsense/mvc/app/models/OPNsense/Unbound/Unbound.xml` file should survive a release-upgrade if there was not changes to it.  The advanced configuration docs was from swite2.

**Comment by NOYB** [comment]
Google: Microsoft Domain Controller Underscore
https://docs.microsoft.com/en-us/troubleshoot/windows-server/identity/naming-conventions-for-computer-domain-site-ou
https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-2000-server/cc959336(v=technet.10)
https://support.microsoft.com/en-us/topic/2dc5c4b9-0881-2e0a-48df-f120493a2d3e
https://social.technet.microsoft.com/Forums/windowsserver/en-US/e7b024ac-9b8d-4f5f-9ec1-65d473e6511b/ambiguity-with-underscores-in-internal-network-names?forum=winserverPN

**Comment by swhite2** [comment]
> @NOYB i read this documentation for advanced configuration now. but these Files will not be saved with configuration, or will they? and will they survive an release-Upgrade?

@egi815 These files will be saved with the configuration and will also survive a release upgrade. 

I'll investigate this further, at the very least we'll go back to the situation as it was prior to 22.1.5 by accepting `_msdcs` as a prefix, but I find it suspicious to say the least.

**Comment by egi815** [comment]
You are right, normal domains cannot have an _ .  But unfortunately There are A records  with _ . 
It is suspicious. 
I never thought about it before, But i have tons of such A-records in my systems.
Thanks a lot..
