### ISSUE TITLE
non-admin users can't see "Host Overrides" entries in Unbond DNS

### ISSUE THREAD

**Issue by teawithbrownsugar** [opnsense/core#5704]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

_Services: Unbound DNS: Overrides_ contains a tab _Host Overrides_, which allows management of optional entries to override regular DNS data. Managing those entries as admin user works as expected. Managing those entries as a non-admin user seems to be impossible, because the list of entries is always empty; there is there is only a message being displayed: "No results found!".

A non-admin user should only have access to this list, if the _Effective Privileges_ of that user contain the privilege `Services: Unbound DNS: Edit Host and Domain Override`. Adding this privilege does activate the menu entry, so the user can open _Services: Unbound DNS: Overrides_. This is correct and expected behavior.

The unexpected behavior here is, that the list is always empty for a non-admin user, even if he has the privilege. An admin user can be used to verify that there are entries stored somewhere, they are just invisible to the previleged non-admin user.

The current OPNsense version where the bug first appeared? 22.1.5
The last OPNsense version where the bug did not exist? Probably 22.1.3 or 22.1.4

**To Reproduce**

1. Log into admin account.
2. Go to the URL path `/ui/unbound/overrides/`. The tab _Host Overrides_ should be selected. If not, select it.
4. Make sure that there is at least one entry. If there isn't one, create one.
5. Go to the URL path `/system_usermanager.php` and edit the _Effective Privileges_ of a non-admin user. Activate the privilege `Services: Unbound DNS: Edit Host and Domain Override`. Save changes.
6. Switch user: log out the admin user, log in the previously edited non-admin user.
7. Go to the URL path `/ui/unbound/overrides/`. The tab _Host Overrides_ should be selected. If not, select it.
8. Notice that the list of _Host Overrides_ is empty, that there is only a message "No results found!".

**Expected behavior**

The expected behaviour is about which users are supposed to see the configured host override entries:
- **Normal** users **without** the privilege `Services: Unbound DNS: Edit Host and Domain Override` **should not** be able to see those entries.
- **Normal** users **with** the privilege `Services: Unbound DNS: Edit Host and Domain Override` **should** be able to see those entries.
- **Admin** users **should** be able to see those entries.

**Additional context**

This bug seems to be similar to #5692. The affected area is different, but the symptoms are similar. In both cases there seems to be a permission issue.

This bug is not a duplicate of #5693, the symptoms are different.

**Environment**

OPNsense 22.1.5-amd64

**Comment by fichtner** [comment]
One addition: both admin or users with the privilege will be able to edit contents. This is the way the ACL works. If you need read only access that's what the global read-only privilege is for.

**Comment by teawithbrownsugar** [comment]
That fix works, thank you!
