### ISSUE TITLE
Bug: Unbound cannot specify port in domain override

### ISSUE THREAD

**Issue by rovingclimber** [opnsense/core#5705]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

In the dialogue to add a domain override in unbound configuration, the help information specifies:

"IP address of the authoritative DNS server for this domain, e.g. '192.168.100.100'. To use a nondefault port for communication, append an '@' with the port number."

If you attempt to use the instructions for a non-default port as above, by appending @ with the port number, you get this error:

"Please specify a valid network segment or address (IPv4/IPv6)"

**To Reproduce**

Services > Unbound > Overrides > Domain Overrides > Add
Click "Enabled"
Enter a domain like "test.local"
Enter an IP address with non-standard port like: "192.168.127.1@5353"
Click Save
You will get the error as above.

Dialogue should accept IP/Port in the manner described.

**Describe alternatives you considered**

**Screenshots**

**Relevant log files**

**Additional context**

**Environment**

OPNsense 22.1.5-amd64
FreeBSD 13.0-STABLE
OpenSSL 1.1.1n 15 Mar 2022

**Comment by AdSchellevis** [comment]
fixed in https://github.com/opnsense/core/commit/ff11cde38e8d16d8d51ddd01c19af282cebe3d8d
