### ISSUE TITLE
DHCPv6 prefix delegation range prefix does not account for interface prefix mask length

### ISSUE THREAD

**Issue by rfc4711** [opnsense/core#5709]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [ X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [ X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

When configuring the v6 dhcp, an interface having a subnet mask of greater than 64bits cannot set a prefix delegation in the DHCPv6 configuration. Options on delegation range are only 64 bit to 48 bit prefix mask. 

V6 prefix delegation should be unique from the DHCP range and provide a list or free entry field for a value range between interface mask and 128. 

```
Interface v6: fda0:dead:beef:cafe:17::2/80
Range6: fda0:dead:beef:cafe:17:affe:: fda0:dead:beef:cafe:17:affe:ffff:ffff;
Delegation v6: fda0:dead:beef:cafe:17:face:: fda0:dead:beef:cafe:17:face:ffff:ffff/96;
```

DHCPv6 config:

```
subnet6 fda0:dead:beef:cafe:17::/80 {
  range6 fda0:dead:beef:cafe:17:affe:: fda0:dead:beef:cafe:17:affe:ffff:ffff;
  option dhcp6.domain-search "v6.buxhofer.net","buxhofer.net","dyn.buxhofer.net","wifi.buxhofer.net";
  ddns-domainname "v6.buxhofer.net";
  option dhcp6.name-servers fda0:dead:beef:cafe:17::44;
  prefix6 fda0:dead:beef:cafe:17:face:: fda0:dead:beef:cafe:17:face:ffff:ffff/96;  <---
  option dhcp6.sntp-servers fda0:dead:beef:cafe:17::5;
  
}
```

*Tip*: to validate your setup was working with the previous version, use opnsense-revert (https://docs.opnsense.org/manual/opnsense_tools.html#opnsense-revert)

1. Configure a v6 interface with a mask greater than 64 bit
2. Enable DHCP v6 prefix delegation.

```
2022-04-13T12:53:56-04:00 | Error | php-cgi | /services_dhcpv6.php: The command '/usr/local/sbin/dhcpd -6 -user dhcpd -group dhcpd -chroot /var/dhcpd -cf /etc/dhcpdv6.conf -pf /var/run/dhcpdv6.pid ix1' returned exit code '1', the output was 'Internet Systems Consortium DHCP Server 4.4.2-P1 Copyright 2004-2021 Internet Systems Consortium. All rights reserved. For info, please visit https://www.isc.org/software/dhcp/ /etc/dhcpdv6.conf line 17: network mask too short prefix6 fda0:dead:beef:cafe:17:face:: fda0:dead:beef:cafe:17:face:ffff:ffff/64 ^ Configuration file errors encountered -- exiting If you think you have received this message due to a bug rather than a configuration issue please read the section on submitting bugs on either our web page at www.isc.org or in the README file before submitting a bug. These pages explain the proper process and the information we find helpful for debugging. exiting.'
-- | -- | -- | --
```

**Environment**

OPNsense 22.1.5-amd64
FreeBSD 13.0-STABLE
OpenSSL 1.1.1n 15 Mar 2022

**Comment by fichtner** [comment]
/80 is not valid. I'm not sure why you think it could be. The smallest network to delegate remains /64.


Cheers,
Franco

**Comment by rfc4711** [comment]
From my initial research, I did believe that a private delegation of subnets smaller than a /64 should be possible. Since I thought of the /64 as a recommendation rather than a rule. 
However, after more research, to be compatible with SLAAC, I see that a minimum subnet of /64 is necessary. 

Suppose we can close this issue then.

**Comment by rfc4711** [comment]
SLAAC requires a /64 minimum subnet.

**Comment by rfc4711** [comment]
Hi Franco,

I did believe that a private delegation of subnets smaller than a /64
should be possible. As I saw the /64 as a recommendation rather than a
rule.
However, to remain compatible with SLAAC, I see that a minimum subnet of
/64 is necessary.

Suppose we can close this issue then.

Best regards,
Sascha

**Comment by fichtner** [comment]
Hi Sascha, I also think that dhcp6c will not allow smaller delegation than /64. The problem likely is that other software might rely on the fact that it is /64 when in reality it is not causing funky stuff to happen for client that are impossible to debug and easily avoided with the /64.


Cheers,
Franco
