### ISSUE TITLE
[RFE] Configuring CARP virtual IPs is extremely slow

### ISSUE THREAD

**Issue by fraenki** [opnsense/core#571]
When adding/editing CARP virtual IPs in a setup with master/slave nodes, it takes really long to save the configuration. After clicking on "save" it takes easily 30-60 seconds. I couldn't find any error in the logs though. So I guess it's not related to pfsync timeouts, but instead the actually required time to rsync the configuration. Still this seems too much time to me...

**Comment by fraenki** [comment]
I could find these messages on the secondary node, stating a successful sync:

```
Dec 27 15:36:43 fw kernel: carp: demoted by 240 to 240 (pfsync bulk start)
Dec 27 15:36:43 fw kernel: carp: demoted by -240 to 0 (pfsync bulk done)
Dec 27 15:36:43 fw opnsense: /xmlrpc.php: waiting for pfsync...
Dec 27 15:37:14 fw opnsense: /xmlrpc.php: pfsync done in 30 seconds.
Dec 27 15:37:14 fw opnsense: /xmlrpc.php: Configuring CARP settings finalize...
```

After clicking on "save" both nodes are idle, CPU usage at ~1%.

**Comment by AdSchellevis** [comment]
it's this part your waiting for https://github.com/opnsense/core/blob/master/src/etc/inc/interfaces.inc#L1940-L1947

**Comment by fraenki** [comment]
For future reference: https://github.com/opnsense/core/blob/b7fff8a7270c881fd1c4ef1099098a448a2649e5/src/etc/inc/interfaces.inc#L1940-L1947

The above code is a workaround to avoid issues. Maybe we can find a better solution in the future. I've changed this report to be a RFE instead of a bug report.

**Comment by AdSchellevis** [comment]
@fraenki just checked and tested https://github.com/opnsense/core/commit/2f8604874882a56c5a2bc0cea3588b09b9ef68a2 there's no need to wait as long as we implement the standards for carp/pfsync
