### ISSUE TITLE
Second openvpn server not routed correctly

### ISSUE THREAD

**Issue by mgiammarco** [opnsense/core#5717]
Hi,
I have a "licensed" OPNSense VM in Azure.
I configured an OpenVpn server on tcp port 443 with certificate only authentication.
Most clients have CSO.
Now I configure a second OpenVpn server with same CA and server certificate.
I expose it on udp on a different port because I finished first server ip space and because some clients cannot use tcp port 443.
But, no matter what I do, ip packets arrive at second openvpn interface but then they are blocked/not routed.
I have searched forums and tried:
- using pass all firewall rule
- disabling reply-to in firewall rules
- enabling openvpn interfaces
- then disabling dynamic openvpn gateway
- using firewall groups
No workaround worked.
Can you tell me if it is a bug or what should I try?
Thanks,
Mario

**Comment by mimugmail** [comment]
How do you find out that packets really arrive at the firewall? Did you allow the udp port in azure poliy?

**Comment by mgiammarco** [comment]
Close to conform to templates
