### ISSUE TITLE
Second openvpn server not routed correctly 

### ISSUE THREAD

**Issue by mgiammarco** [opnsense/core#5720]
**Important notices**

Our forum is located at https://forum.opnsense.org , please consider joining discussions there in stead of using GitHub for these matters.

Before you ask a new question, we ask you kindly to acknowledge the following:

- [ X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [ X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

Hi,
I have a "licensed" OPNSense VM in Azure.
I configured an OpenVpn server on tcp port 443 with certificate only authentication.
Most clients have CSO.
Now I configure a second OpenVpn server with same CA and server certificate.
I expose it on udp on a different port because I finished first server ip space and because some clients cannot use tcp port 443.
But, no matter what I do, ip packets arrive at second openvpn interface but then they are blocked/not routed.
I am pretty sure because I have tested with a packet capture and I see ping requests arrive in the opnsense interface but they stops there.

I have searched forums and tried:

- using pass all firewall rule
- disabling reply-to in firewall rules
- enabling openvpn interfaces
- then disabling dynamic openvpn gateway
- using firewall groups

No workaround worked.
Can you tell me if it is a bug or what should I try?
Thanks,
Mario

**Comment by AdSchellevis** [comment]
I've only seen similar behaviour when cso's aren't properly used and `iroute` is missing (in which case openvpn doesn't know where to send the traffic).

**Comment by mgiammarco** [comment]
Oh forgot to say that I disabled some cso for testing. Anyway I will check iroute now.
