### ISSUE TITLE
Accessibility improvment

### ISSUE THREAD

**Issue by jpcw** [opnsense/core#5721]
html pages don't respect accessibility.
This is not a functionnal bug, but an usability "bug".

Feel free to requalify this issue.

We are a French Linux User Group and we are very happy using opnsense. 
However one of our member is a blind man, and says us it's difficult for him to use opnsense correctly.

So we want to contribute to improve your work

Many input or others checkboxes doesn't have an associated label

To illustrate below 2 screenshots for page interfaces.php and checkbox enable interface

An easy way to see this 
![opnsense_interfaces_enable_if_not_accessible](https://user-images.githubusercontent.com/546715/164062134-ccfa30eb-c9df-4421-96e5-613e381debe6.png)
![opnsense_interfaces_enable_if_accessible](https://user-images.githubusercontent.com/546715/164062143-4ca5c322-0c94-46a3-a6a2-5fadecf419d2.png)

The difference between both is here https://github.com/paulla/core/commit/ecb2a3a4549971d94e0cd76c0e8f4d87aa717547#diff-8bda10faf6dc1b2eed1742ad25598b60e7f23d7934e9cc58802f517198bbed9aR1767

A simple tag "<label for="id_of_the_checkbox"> around the i18n gettext.

A sample merge request focused on interfaces.php file coming soon

Hoping this issue will encounter a favorable echo on your side, and you'll accept ours contributions

Regards

**Comment by AdSchellevis** [comment]
It's a known concern, but not very high on our todo list. Looking at your changes I don't expect there's an issue to merge them, but we will have to plan these. It's probably best to create separate pull-requests for topic and maybe a tracking ticket to monitor progress. 

I do expect the newer pages are easier to fix by the way.

**Comment by NOYB** [comment]
I have some commits aimed at accessibility improvements with checkbox labels and screen reader only content (SROC; a css class).  I'll open PR to submit them for review.

**Comment by AdSchellevis** [comment]
@NOYB small PR's are easier to review/test and more likely to be merged. Our time is limited, which is why I advised to start with a plan (tracking ticket) and start working on a per subject basis.

**Comment by jpcw** [comment]
@AdSchellevis thanks for your reply and @NOYB for your purpose.
@AdSchellevis is a ticket per file a good approach for you ? It was our first approach, but we'll adapt ours contributions on your plan.

I think interfaces.php is a biggest file, and we already have a pr for it (focused on attach labels)

**Comment by AdSchellevis** [comment]
> @AdSchellevis is a ticket per file a good approach for you ? It was our first approach, but we'll adapt ours contributions on your plan.

A ticket per file is not needed, but if you have a work list of planned changes, a checklist in this (or another) ticket might be a good idea, like:

- [x] interfaces.php
- [ ] other file or topic
