### ISSUE TITLE
Host Alias not working with a range in 22.1.6

### ISSUE THREAD

**Issue by zerwes** [opnsense/core#5723]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

Since 22.1.6 a host alias can not be created with a range as documented in https://docs.opnsense.org/manual/aliases.html#hosts
Error: `Entry "10.0.0.1-10.0.0.10" is not a valid hostname or IP address.`

More details: 
https://forum.opnsense.org/index.php?topic=28011.0

1. Go to 'Firewall: Aliases'
2. Click on '[+]'
3. Try to create a host alias with a range `10.0.0.1-10.0.0.10`
4. See error: `Entry "10.0.0.1-10.0.0.10" is not a valid hostname or IP address.`

**Expected behavior**

As documented and as in previous versions this should create a valid alias

**Environment**

OPNsense 22.1.6 (amd64, OpenSSL).

**Comment by zerwes** [comment]
Versions and test results:

version | test result
-- | --
22.1.2_1 | OK
22.1.3 | OK
22.1.4_1 | ERROR
22.1.5 | ERROR
22.1.6 | ERROR

**Comment by fichtner** [comment]
@zerwes thanks, could be 11b4c231a3 ... worth a try:

    # opnsense-patch 11b4c231a3


Cheers,
Franco

**Comment by zerwes** [comment]
+1 : you got it
```
# opnsense-patch 11b4c231a3
Fetched 11b4c231a3 via https://github.com/opnsense/core
Hmm...  Looks like a unified diff to me...
The text leading up to this was:
--------------------------
|From 11b4c231a392bd35b4c6ff65201feeffe156da70 Mon Sep 17 00:00:00 2001
|From: Ad Schellevis <ad@opnsense.org>
|Date: Fri, 18 Mar 2022 17:26:21 +0100
|Subject: [PATCH] Firewall - Aliases : tighten fqdn validation to avoid
| mistypes as 192.168.01.1 from being accepted as domain name.
|
|(cherry picked from commit 0ac674ceac95e51b2f5943aaa447ddd225540f60)
|(cherry picked from commit 57017c07f859a91ce5ba0d2c205c2b4a8ae8f170)
|---
| src/opnsense/mvc/app/library/OPNsense/Firewall/Util.php | 8 +++++++-
| 1 file changed, 7 insertions(+), 1 deletion(-)
|
|diff --git a/src/opnsense/mvc/app/library/OPNsense/Firewall/Util.php b/src/opnsense/mvc/app/library/OPNsense/Firewall/Util.php
|index 9190223b9e..8cb1919fb9 100644
|--- a/src/opnsense/mvc/app/library/OPNsense/Firewall/Util.php
|+++ b/src/opnsense/mvc/app/library/OPNsense/Firewall/Util.php
--------------------------
Patching file opnsense/mvc/app/library/OPNsense/Firewall/Util.php using Plan A...
Reversed (or previously applied) patch detected!  Assuming -R.Hunk #1 succeeded at 242.
done
All patches have been applied successfully.  Have a nice day.
```
resulting in a valid alias entry


Name | Type | Description | Content | Loaded# | Last updated
-- | -- | -- | -- | -- | --
test | Host(s) |   | 10.0.0.1-10.0.0.10 | 5 | 2022-04-20T11:12:19.012088

**Comment by fichtner** [comment]
@zerwes thanks  for confirming... looks like it was never really validated in the first place, @swhite2 will take care of it

**Comment by fichtner** [comment]
918ef316 should do the trick:

    # opnsense-patch 918ef316

**Comment by zerwes** [comment]
I can confirm this.
On a system freshly upgrade from 22.1.2 -> 22.1.6 the creation of a host alias with a range of IPs is working as expected after applying the patch.
```
# opnsense-version 
OPNsense 22.1.6 (amd64/OpenSSL)
# opnsense-patch 918ef316
Fetched 918ef316 via https://github.com/opnsense/core
Hmm...  Looks like a unified diff to me...
The text leading up to this was:
--------------------------
|From 918ef316df2ba646374c523f6f1805adbc402dfb Mon Sep 17 00:00:00 2001
|From: Franco Fichtner <franco@opnsense.org>
|Date: Wed, 20 Apr 2022 12:40:11 +0200
|Subject: [PATCH] firewall: add missing range validation to alias host type
| #5723
|
|---
| .../Firewall/FieldTypes/AliasContentField.php | 50 ++++++++++---------
| 1 file changed, 26 insertions(+), 24 deletions(-)
|
|diff --git a/src/opnsense/mvc/app/models/OPNsense/Firewall/FieldTypes/AliasContentField.php b/src/opnsense/mvc/app/models/OPNsense/Firewall/FieldTypes/AliasContentField.php
|index ac2e1b8afe..b71ceadd5d 100644
|--- a/src/opnsense/mvc/app/models/OPNsense/Firewall/FieldTypes/AliasContentField.php
|+++ b/src/opnsense/mvc/app/models/OPNsense/Firewall/FieldTypes/AliasContentField.php
--------------------------
Patching file opnsense/mvc/app/models/OPNsense/Firewall/FieldTypes/AliasContentField.php using Plan A...
Hunk #1 succeeded at 1.
Hunk #2 succeeded at 145.
done
All patches have been applied successfully.  Have a nice day.
```
=>


Name | Type | Description | Content | Loaded# | Last updated
-- | -- | -- | -- | -- | --
test | Host(s) |   | 10.0.0.1-10.0.0.10 | 5 | 2022-04-20T13:33:18.493335

**Comment by fichtner** [comment]
@zerwes thanks a lot of the help. we will review this internally but likely ship in 22.1.7 since it's a fix.


Cheers,
Franco
