### ISSUE TITLE
Traffic shaper should accept firewall aliases in dialog in order to shape IPv6 for dynamic prefixes

### ISSUE THREAD

**Issue by meyergru** [opnsense/core#5728]
Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**

When I want to use the traffic shaper selectively on a LAN target, I cannot reliably address a specific IPv6 if the assigned prefix changes. The source and destination fields only allow for specific network adresses or ranges.

**Describe the solution you like**

Much the same problem existed for firewall rules, but now, I can use firewall aliases for the source and destination in those rules by just using a "dynamic ipv6 alias" or maybe, a MAC based alias, which should even work when the IPv6 connection uses IPv6 privacy extensions.

**Describe alternatives you considered**

None.

**Additional context**

I do not really know if it is just the input validation, i.e. probably the resulting rule setting would have to be changed as well - maybe it only accepts network addresses?

**Comment by AdSchellevis** [comment]
asked for in multiple tickets (duplicate) https://github.com/opnsense/core/issues/2683, https://github.com/opnsense/core/issues/2373, https://github.com/opnsense/core/issues/865,  not really an option due to `ipfw` uses it's own less flexible alias option.

**Comment by meyergru** [comment]
Sorry for not having looked into closed issues as well... so I see it is not as easy as changing the input fields. However, despite that, it still would be a good idea as I can see no other way to shape traffic for dynamic IPv6 prefixes.
