### ISSUE TITLE
Netflow config page doesn't allow you to have no WAN interfaces selected

### ISSUE THREAD

**Issue by ngreatorex** [opnsense/core#5729]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

When you are configuring the Netflow collector in the OPNsense web GUI, if you leave the "WAN interfaces" box blank, you get a validation error: "WAN interfaces missing in listening interfaces: ".

**To Reproduce**

1. Go to 'Reporting' -> 'NetFlow' in the web GUI.
2. Add one or more interfaces to the 'Listening interfaces' field.
3. Make sure the 'WAN interfaces' field is blank (press clear all to ensure).
4. Click 'Apply'
5. See error as in screenshot below.

**Expected behavior**

I expected the Netflow collector to be configured to use all selected interfaces for both ingress and egress.

**Screenshots**

![image](https://user-images.githubusercontent.com/1928433/164303916-b2738770-f436-41b7-b0c0-9e68ccc945af.png)

**Additional context**

I've had a poke around in the code, and it seems to be a problem with: https://github.com/opnsense/core/blob/02781756f09644cd7f94a1f9319f8010e521d9f6/src/opnsense/mvc/app/models/OPNsense/Diagnostics/Netflow.php#L58
As noted in [this comment](https://www.php.net/manual/en/function.explode.php#126941), explode on an empty string will return an array with 1 element, not 0. Therefore the later in_array check fails and the empty string is added to the list of missing interfaces: https://github.com/opnsense/core/blob/02781756f09644cd7f94a1f9319f8010e521d9f6/src/opnsense/mvc/app/models/OPNsense/Diagnostics/Netflow.php#L63-L67

**Environment**

Only tested on OPNsense 22.1.4_1, but the buggy code is still in master.

**Comment by AdSchellevis** [comment]
thanks, fixed in https://github.com/opnsense/core/commit/26f72adaf691a2ebb07c189e77ebac967d1f53b0
