### ISSUE TITLE
Introduce a visual divider for the firewall rule list

### ISSUE THREAD

**Issue by smalchow** [opnsense/core#5732]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**

The feature request is not directly related to a problem - only the rules get very hard to read in a flat list

**Describe the solution you like**

I would like to be able to create divider in the filewall rules list, like so

![opnsense-divider](https://user-images.githubusercontent.com/8308427/164418768-edc7683c-edcd-420c-bbc8-d21d202b4d67.png)

to be able to group rules to have a better overview

**Comment by AdSchellevis** [comment]
no (duplicate), https://github.com/opnsense/core/issues/3795, https://github.com/opnsense/core/issues/3262 https://forum.opnsense.org/index.php?topic=2851.0

**Comment by smalchow** [comment]
sorry, i was searching for "divider" and not separator, then i would probably have found the other ones
