### ISSUE TITLE
Add Support for ISO 9660 Filesystem for Configuration Importer

### ISSUE THREAD

**Issue by utkonos** [opnsense/core#5733]
- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**

I am attempting to load a configuration file from a mounted ISO rather than a USB. The use case is for deployment on a VM inside of Proxmox, a virtualization environment. Generating an ISO and then uploading it to Proxmox's ISO storage is straightforward as is adding a second cd drive to the VM with that ISO attached. The result is `cd0` with the OPNsense ISO attached and `conf.iso` attached to `cd1`. The layout of the `conf.iso` is `/conf/config.xml`.

Both devices are recognized correctly during first boot. When I press any key to start the configuration importer, both are listed:

```
<QEMU QEMU DVD-ROM 2.5+> at scbus1 target 0 lun 0 (cd0,pass0)
<QEMU QEMU DVD-ROM 2.5+> at scbus1 target 1 lun 0 (cd1,pass1)
```

When I select `cd1` at the prompt as the device to import from, it doesn't find the configuration and the following is printed to console:

No known partition layout was found for 'cd1'.

The configuration importer, according to the following forum thread supports GPT, MBR, zfs pool, and msdosfs. I would be great if support were added for ISO 9660 to import from as well. If an ISO were supported, the entire deployment process can be automated via just the Proxmox API: generate OPNsense config.xml, generate ISO, upload ISO, attach ISO, done.

**Describe the solution you like**

I would like to be able to mount an ISO image with the layout of `/conf/config.xml` and then select that `cdN` device during the configuration importer step during install.

**Describe alternatives you considered**

I have an alternative for storing the configuration on a small disk image and then mounting that to the VM. This process works as expected. However, dynamically generating that config file and writing it to that image is more complex than generating the config, creating an ISO, uploading the new image, and attaching it to the VM. An ISO image on Proxmox can be shared one to many. A disk image needs to be connected to a VMID and can't be written to directly via API programmatically. A disk also needs to be copied and moved once per VM to deploy: it can't be attached one to many.

**Additional context**

https://forum.opnsense.org/index.php?topic=28020.0

**Comment by fichtner** [comment]
@utkonos Thanks for the ticket. Let me try to implement this tomorrow 😊

**Comment by utkonos** [comment]
That's aweome. Thanks!

**Comment by fichtner** [comment]
To be shipped in today's 22.1.7.

**Comment by thebeeric** [comment]
For future readers who may find this topic.. To create an iso image in Linux or WSL on Windows:
1. Install _genisoimage_
`sudo apt install genisoimage`
2. Make your a directory to convert to image:
`mkdir conf-image`
3. Make the conf directory:
`mkdir conf-image/conf`
4. Copy your config file here as config.xml:
`cp /path/to/my/config-old.hostname-202401010101.xml conf-image/conf/config.xml`
5. Build the iso file:
`genisoimage -o myOPNsenseconfig.iso conf-image/`
6. Upload the iso to Proxmox ISO storage
7. Create a new CD drive in the VM
8. Attach your myOPNsenseconfig.iso file to the VM
9. After installer starts, press a key to enter importer. The device is likely "cd1" assuming "cd0" is your OPNsense install media.

**Comment by HaMaMaHa** [comment]
thanks @thebeeric, the summary was very useful. Just one addition - you need to add -allow-lowercase, otherwise OPNsense can't read it:
genisoimage -allow-lowercase myOPNsenseconfig.iso conf-image/

KR
