### ISSUE TITLE
IPsec Create Phase2 failed - missing Buttons

### ISSUE THREAD

**Issue by skappich** [opnsense/core#5738]
It is not possible to add Phase2 entries to a given or new Phase1 entry of an IPsec-Connection.

1. Go to VPN -> IPsec -> create new Phase1 and then try to create Phase2 for this previsious created Phase1
2. Same on already created Phase1, you can't create new Phase2. But you can edit already existend Phase2 entries.

Software version used and hardware type if relevant, e.g.:

OPNsense 22.1.6 (amd64, OpenSSL).

**Comment by mimugmail** [comment]
Maybe you missed the new + sign in P1 row?

**Comment by skappich** [comment]
Yes you're right. I missed it. Sorry for that.
