### ISSUE TITLE
Jump to last page in log files doesn't work

### ISSUE THREAD

**Issue by Sopor** [opnsense/core#5744]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

Logs can have several pages and at the bottom it will show some arrows to jump back and forth.

The `<` and `>` will go one page and `<<` and `>>` will jump to the first and last page, but it is only the `<<` that works.

If i want to go to the last page and i click on the `>>` it will only go one page forward. The same as clicking on `>`.

*Tip*: to validate your setup was working with the previous version, use opnsense-revert (https://docs.opnsense.org/manual/opnsense_tools.html#opnsense-revert)

**To Reproduce**

Open any log files that have more than 3 pages.

**Expected behavior**

It should jump to the last page.

**Describe alternatives you considered**

A clear and concise description of any alternative solutions or workaround you considered.

**Screenshots**

![image](https://user-images.githubusercontent.com/5789283/165585159-87fd27b7-3e7f-40da-97c4-1df946e240e6.png)

**Relevant log files**

If applicable, information from log files supporting your claim.

**Additional context**

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 22.1.6-amd64
FreeBSD 13.0-STABLE
OpenSSL 1.1.1n 15 Mar 2022

**Comment by AdSchellevis** [comment]
https://docs.opnsense.org/manual/gui.html#page-navigation
