### ISSUE TITLE
Serial port access

### ISSUE THREAD

**Issue by gitterdoneplease** [opnsense/core#5751]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**

For the purpose of remote administration. Cannot access serial port remotely via BMC.

**Describe the solution you like**

Add serial port selection drop-down to System->Settings->Administration in the Console section from a list of serial ports provided by grep uart /var/run/dmesg.boot.

**Describe alternatives you considered**

Manually adding "comconsole_port=" to /boot/loader.conf.local is the only alternative.

**Additional context**

This feature would support serial port access for iDRAC, iLO and other whitebox BMCs to allow access via SSH, SMASH, Redfish, IPMI and various web-based GUIs. It would provide backend management of remote firewalls.

**Comment by fichtner** [comment]
There is a bug in tunables GUI that prevents the use of “environment” variables such as “comconsole_port” and that will be fixed in 22.1.7 so this is more or less possible without a feature request already.


Cheers,
Franco

**Comment by gitterdoneplease** [comment]
Thanks Franco! I look forward to trying that.

I'm not a UI/UX designer, but having the port in with the speed seems ideal. Once the tunables bug is fixed would it make sense to move the speed there as well?

Thanks,
David
