### ISSUE TITLE
Messages with wrong severity appear after editing Gateways.

### ISSUE THREAD

**Issue by jorglodita** [opnsense/core#5753]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [V] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [V] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

"Error" and "Warning" messages appear on logs each time a Gateway configuration is made.

**To Reproduce**
1. Go to System>Gateways>Single.
2. Choose any Gateway, click "edit".
3. No changes needed, just scroll down and click "save"
4. Click on "Apply changes".
5. Check "System>Log Files>General". Error messages appear (the more Gateways the more error messages appear).

**Optional steps to reproduce more related logs**
...
3. Enable monitoring on a Gateway unticking "Disable Gateway Monitoring".
4. Add a working Monitor IP.
5. Save and click on "Apply changes".
6. Check "System>Log Files>General" for new error messages and System>Gateways>Log File for new warning messages.

**Expected behavior**

Logs are showing OPNsense internal normal behavior as error or warning. Apparently the Severity of those messages is wrong.

**Describe alternatives you considered**

System is working as expected, apparently there is no error at all or nothing to be warned, just normal behavior. There aren't connection drops, there is not bad configuration, all is working as expected. 

Lower the severity of that messages. Informational maybe?

**Screenshots**

![generallog](https://user-images.githubusercontent.com/104060911/166642725-ef16f122-53e5-4db3-8894-75307e2c1096.png)

![gatewaylog](https://user-images.githubusercontent.com/104060911/166642747-81703e71-d6dc-4753-822f-f516d7c9ab52.png)

In the screenshots I did the optional steps to reproduce more error and warning messages. 

**Relevant log files**

Shown as screenshots

**Additional context**

To check it was not my ISP connection creating errors I created two more (working) Gateways using WireGuard. The error and warning messages appears in all of them.
The connection never dropped in any of the Gateways while having those errors. All is working perfectly, just getting those error and warning messages each time I edit or just save any Gateway setup.

**Environment**

OPNsense 22.1.6
1x ISP Gateway using ISP VLAN
2x Additional Gateways using WireGuard VPN connections

**Comment by AdSchellevis** [comment]
More or less a side affect of adding the level in 22.1, see also https://github.com/opnsense/core/pull/5541. we do need to change log levels for certain messages (these should be LOG_NOTICE)
