### ISSUE TITLE
Standard upgrade mechanism doesn't work

### ISSUE THREAD

**Issue by dylannevans** [opnsense/core#5755]
Hi folks.  When following the GUI prompts to apply an upgrade from 21.7.8 to 22.whatever, I consistently get the following error blocking progress:

`***GOT REQUEST TO UPGRADE***
Currently running OPNsense 21.7.8 (amd64/OpenSSL) at Thu May  5 07:37:05 CDT 2022
Fetching packages-22.1-OpenSSL-amd64.tar: .................................................. failed, signature invalid
***DONE***`

Other than adding kern.vty="sc" to /boot/loader.conf.local during install so it actually boots, I've done no meaningful customization.  
Potential associated factors: unbound fails every other week and I have to restart it.  I was hoping an upgrade would fix that issue.

**Comment by dylannevans** [comment]
How do I clean it? 

I got plenty of space: 

`Disk usage | 3% / [zfs] (2.8G/100G)0% /var/mail [zfs] (88K/97G)0% /zroot [zfs] (88K/97G)0% /var/crash [zfs] (88K/97G)0% /tmp [zfs] (1.4M/97G)0% /usr/home [zfs] (88K/97G)0% /usr/ports [zfs] (88K/97G)0% /var/audit [zfs] (88K/97G)0% /var/log [zfs] (236M/97G)0% /usr/src [zfs] (88K/97G)0% /var/tmp [zfs] (88K/97G)`

**Comment by fichtner** [comment]
First make sure via health audit that no vital files are missing.

**Comment by dylannevans** [comment]
Is this repairable?

***GOT REQUEST TO AUDIT HEALTH***
Currently running OPNsense 21.7.8 (amd64/OpenSSL) at Sat May  7 16:23:09 CDT 2022
>>> Check installed kernel version
Version 21.7.8 is correct.
>>> Check for missing or altered kernel files
No problems detected.
>>> Check installed base version
Version 21.7.8 is correct.
>>> Check for missing or altered base files
Error 2 ocurred.
usr/bin/clang: 
	sha256digest: clang: Input/output error
usr/bin/cc: 
	sha256digest: cc: Input/output error
usr/bin/cpp: 
	sha256digest: cpp: Input/output error
usr/bin/c++: 
	sha256digest: c++: Input/output error
usr/bin/clang-cpp: 
	sha256digest: clang-cpp: Input/output error
usr/bin/clang++: 
	sha256digest: clang++: Input/output error
>>> Check for missing package dependencies
Checking all packages: .......... done
>>> Check for missing or altered package files
Checking all packages: .........
sudo-1.9.8p2: checksum mismatch for /usr/local/libexec/sudo/sudoers.so
Checking all packages...
pkg: pkg_checksum_hash_sha256_file(read failed): Input/output error

**Comment by fichtner** [comment]
It could be your disk failing.


Cheers,
Franco
