### ISSUE TITLE
New option WebGUI enable/disable in "opnsense-shell"

### ISSUE THREAD

**Issue by lars18th** [opnsense/core#5758]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**

When configuring a new install of OPNsense in a virtual machine (or some cloud service) the LAN network is not accessible externally. However, the WAN interface is accessible. But the configuration by default has WAN webGUI access closed, and the shell doesn't have the option to enable it.

**Describe the solution you like**

The solution could be to add a simple new command to enable/disable (by default disabled) the WAN webGUI access from the "opnsense-shell" command.

**Describe alternatives you considered**

The alternative is a complex network changes to enable access to the internal LAN, configure (aka enable) the WAN webGUI access, then reconfigure with the final network configuration. However, this is a pain.

**Additional context**

Other people has commented this problem in other sites: https://www.reddit.com/r/OPNsenseFirewall/comments/odficf/edit_config_through_local_shell/

I feel it's time to address this problem to simplify the initial configuration in virtual environments.
Thank you.

**Comment by fichtner** [comment]
I'm not sure what sort of problem this really solves: if you can't access your LAN it's not a management network. If you can't run a WAN-only setup for initial configuration where GUI is unlocked by default it's pretty hard to solve this "problem" for "reasons".

I'm not sure what opnsense-shell should be doing here specifically. It sounds like trying to solve it from the wrong end.


Cheers,
Franco

**Comment by larencejg** [comment]
Add firewall rules for any interface that needs an IP address.  In the example above, with a routing solution, add a permissive "allow all TCP traffic" rule to the WAN port.  The "Can't access WebGUI on any port other than LAN" problem is due to default "deny all" Firewall rules on the other interfaces such as WAN.  Add a permit traffic rule (ACL) to the WAN interface that will allow WebGui (port 443 SSL) traffic if you need to manage OPNSense access from an external network reachable via WAN port.

**Comment by lars18th** [comment]
Hi @larencejg (and @fichtner),

Thank you for your suggestion. But it doesn't solve the problem. I try onother time to explain the problem:

- In a _cloud_ environment, when you're deploying an opnsense instance, your network has this configuration (and no other): WAN is connected to the public Internet or to a LAN network with Internet connectivity; and the opnsense's LAN network is connected no where. The objective is to provide the new opnsense LAN network to other services. And you can't connect it to the _real_ LAN because the opnsense has a DHCP server and provides other LAN services. Therefore in this case your WAN network is the management network. And you can't reach with your computer the opnsense LAN network.

So for this specific case (I feel very common at these days), and to not broke the security, the request is quite simple: provide a CLI command to enable (disabled by default) WEB GUI ACCESS FROM THE WAN INTERFACE.

This will simplifies a lot the management of this appliance. Please, re-think to support this _simple_ function.
Regards.

**Comment by SANCLA** [comment]
+1

**Comment by fichtner** [comment]
„pfctl -d“ is the best thing here, already mentioned.

**Comment by lars18th** [comment]
> „pfctl -d“ is the best thing here, already mentioned.

Do you really want to completely disable the firewall in a cloud environment with many unknown services on the WAN interface? Seriously?

IMHO I don't understand why a simple CLI command to enable/disable access to the WebGUI port from WAN is not considered as a musthave.

**Comment by fichtner** [comment]
Because the simple reason that 3 people failing to set up their cloud environment properly in 10 years of project history is not very sensible to ask for a feature that has larger security implications that hundreds of thousands of users could fall into because they think it fixes "something".


Cheers,
Franco
