### ISSUE TITLE
Style issues and missing translation

### ISSUE THREAD

**Issue by DokuKaefer** [opnsense/core#576]
system_advanced_network.php
Line 139
	"class="text-warning" is missing at Note

system_authservers.php
Line 285
	- missing translation
Line 483
	- nothing for "showhelp"-function

System -> Access Control -> Servers -> click on "Add Servers"
	- the Button for "Add Server" is still available
	- the Button for "full help" is missing
	- the table on the right side jumps to left when opening a help text at:
		- Hostname or IP address
		- Authentication containers

![without_help_text](https://cloud.githubusercontent.com/assets/11537653/12012488/62b28c6e-acf7-11e5-81e9-04fa601c9d25.png)

![show_help_text](https://cloud.githubusercontent.com/assets/11537653/12012489/6f9b5b36-acf7-11e5-8a2a-2951b9741670.png)

system_advanced_admin.php
Line 402
	"class="text-warning" is missing at Note

diag_logs_settings.php
Line 402 and 462
	"class="text-warning" is missing at Note

**Comment by AdSchellevis** [comment]
@DokuKaefer can you recheck the current master branch? I walked through the first few issues and they seemed to be solved already..

**Comment by AdSchellevis** [comment]
Looks fixed, if anything is missing feel free to open a new issue for that part.
