### ISSUE TITLE
Adding gateway fails with "Cannot add IPv6 Gateway Address because no IPv6 address could be found on the interface."

### ISSUE THREAD

**Issue by eimann** [opnsense/core#5766]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

On 22.1.5 and 22.1.7 adding an IPv6 gateway fails with the following message, if the gateway is on a GRE interface:

Cannot add IPv6 Gateway Address because no IPv6 address could be found on the interface.

**To Reproduce**

1. Create GRE tunnel with IPv4 transport
2. Add IPv4 and IPv6 IP alias to it
3. Add IPv4 and IPv6 gateway

While adding an IPv6 gateway, the "Cannot add IPv6 Gateway Address because no IPv6 address could be found on the interface." message appears. The network size is /126, the gateway is the first IP address, the OPNsense IP alias is the 2nd IP address out of this /126

**Expected behavior**

Add gateway, start dpinger

**Relevant log files**

<13>1 2022-05-12T07:27:57+00:00 hostname configctl 79601 - [meta sequenceId="15"] event @ 1652340477.31 msg: May 12 07:27:57 hostname config[71311]: [2022-05-12T07:27:57+00:00][info] config-event: new_config /conf/backup/config-1652340477.3115.xml
<13>1 2022-05-12T07:27:57+00:00 hostname configctl 79601 - [meta sequenceId="16"] event @ 1652340477.31 exec: system event config_changed
<11>1 2022-05-12T07:27:59+00:00 hostname opnsense 64052 - [meta sequenceId="17"] /system_gateways.php: ROUTING: entering configure using defaults
<11>1 2022-05-12T07:27:59+00:00 hostname opnsense 64052 - [meta sequenceId="18"] /system_gateways.php: ROUTING: IPv4 default gateway set to wan
<11>1 2022-05-12T07:27:59+00:00 hostname opnsense 64052 - [meta sequenceId="19"] /system_gateways.php: ROUTING: setting IPv4 default route to 1.2.3.4
<11>1 2022-05-12T07:27:59+00:00 hostname opnsense 64052 - [meta sequenceId="20"] /system_gateways.php: ROUTING: keeping current default gateway '1.2.3.4'
<11>1 2022-05-12T07:27:59+00:00 hostname opnsense 64052 - [meta sequenceId="21"] /system_gateways.php: ROUTING: IPv6 default gateway set to opt2
<11>1 2022-05-12T07:27:59+00:00 hostname opnsense 64052 - [meta sequenceId="22"] /system_gateways.php: ROUTING: setting IPv6 default route to 2001:db8:4000::ae9
<11>1 2022-05-12T07:27:59+00:00 hostname opnsense 64052 - [meta sequenceId="24"] /system_gateways.php: ROUTING: creating /tmp/gre0_defaultgwv6 using '2001:db8:4000::ae9'
<13>1 2022-05-12T07:27:59+00:00 hostname opnsense 64052 - [meta sequenceId="25"] plugins_configure monitor ()
<13>1 2022-05-12T07:27:59+00:00 hostname opnsense 64052 - [meta sequenceId="26"] plugins_configure monitor (execute task : dpinger_configure_do())
<11>1 2022-05-12T07:27:59+00:00 hostname opnsense 64052 - [meta sequenceId="27"] /system_gateways.php: The WANtunnel_GWv6 IPv6 interface address could not be found, skipping.

**Additional context**

I first saw this issue when restoring my config on a new OPNsense with 22.1.5, I updated to 22.1.7 but the issue stayed.
I then re-enabled the old OPNsense also running 22.1.5 but after powering it up it had the same issue.
I had working v6 connectivity until powering it down, so I'm not sure exactly when this issue was introduced.

**Environment**

OPNsense 22.1.5-amd64
FreeBSD 13.0-STABLE
OpenSSL 1.1.1n 15 Mar 2022

**Comment by fichtner** [comment]
https://github.com/opnsense/core/blob/4173fbca0e602f202aa1bdc626d5860f96265f79/src/www/system_gateways_edit.php#L108

From the looks of it the code never really intended to work correctly with VIPs when no "primary" address is found on the interface in question. A similar situation is 0e202bc062f where IP type is "none" as well but VIPs exist which taint the primary interface concept formerly (and carelessly so) ignored by find_interface_ip() function family.

While working on 0e202bc062f we discussed the possibility of tainting primary addresses with aliases if the respective IP configuration type was none but then opted for a simpler (and more compatible approach), but now that IPv6 is affected it might be better to align both cases.


Cheers,
Franco

**Comment by fichtner** [comment]
@eimann can you try d3ea41d?

    # opnsense-patch d3ea41d


Cheers,
Franco

**Comment by eimann** [comment]
Looks better now, at least it applies through the GUI without an error and gateway is correctly set.
But it seems dpinger isn't setup correctly, as the gateway stays "offline".
Is this another issue I should follow up separately?

Cheers,
Dominik

**Comment by fichtner** [comment]
#5777
