### ISSUE TITLE
Aliases not added to UNBOUND DNS

### ISSUE THREAD

**Issue by DRON4eg** [opnsense/core#5767]
**Important notices**

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

When you try to add an alias to DNS, it is not added, but a message pops up asking you to apply the new settings.
It helps to clone an existing alias and edit it.
Maybe I caught some bug :)

**Screenshots**

![image](https://user-images.githubusercontent.com/1354427/168126730-c7739961-aaae-4fa6-a4ce-799e71f26094.png)

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 22.1.7 (amd64, OpenSSL).
Intel(R) Core(TM) i3-3240 CPU @ 3.40GHz
Network Intel® I350-T4V2

**Comment by fichtner** [comment]
But if you’re on 22.1.7 the patch you say is removed?!

**Comment by DRON4eg** [comment]
> But if you’re on 22.1.7 the patch you say is removed?!

why removed?  everything is in place

https://forum.opnsense.org/index.php?topic=28043.msg136169#msg136169
https://github.com/opnsense/core/commit/4ec9ea3d1aad

**Comment by fichtner** [comment]
Because what I said is true.

**Comment by DRON4eg** [comment]
> Because what I said is true. ;)

hmm, it's strange, but without this patch, I didn't add aliases to Unbound DNS.
Maybe I need to provide some more information to find the true causes of the problem?

**Comment by fichtner** [comment]
I just tested adding aliases and it works from here on the latest development version. Haven't heard of any other report about what you describe yet.

**Comment by DRON4eg** [comment]
> I just tested adding aliases and it works from here on the latest development version. Haven't heard of any other report about what you describe yet.

Maybe I was lucky and I caught some bug :D
But then why did this patch fix my problem? I had a problem in 22.1.5, but I decided to wait for new patches because the problem was not critical at that time.
Now I'll try to roll back the patch and check again.

**Comment by fichtner** [comment]
I can only attest to what you wrote: 22.1.7 plus opnsense-patch equals pre-22.1.7 state, not the other way around.

**Comment by DRON4eg** [comment]
After rolling back the patch, all my test recordings came out, and with duplicates))))
Apparently I really have some kind of "my" bug.
![image](https://user-images.githubusercontent.com/1354427/168222084-a6836f1c-4758-4dd6-83c5-432675533902.png)
