### ISSUE TITLE
interfaces: plugins_interfaces() is not called by MVC code causing side effects in interface population

### ISSUE THREAD

**Issue by utkonos** [opnsense/core#5768]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

I am using the OPNsense importer on a config file from a previous install. This previous install has WireGuard installed, configured, and working. The resulting instance after running the importer and then running the install results in a working OPNsense with WireGuard also working. However, at one point between the importer and the end of the install process, the installer removes the WireGuard (Group) interface. This is created by the plugin when an interface is enabled.

According to the backup configs, the revision's metadata shows "(root): Created web GUI TLS certificate". I have included a screenshot below.

**To Reproduce**

1. Configure WireGuard
2. Export config.xml
3. Use OPNsense importer on said config.xml
4. Check the config history.

**Expected behavior**

At the end of the import process, the WireGuard interface group should exist.

**Describe alternatives you considered**

I have tried to trigger the creation of the interface by doing the following, but none worked.

1. Uninstalling and reinstalling the plugin.
2. Disabling and enabling the local server configuration.
3. Disabling and enabling WireGuard.
4. Creating a new local server configuration.
5. Creating a new local server configuration with all others disabled and WireGuard disabled.

**Screenshots**

<img width="2219" alt="image" src="https://user-images.githubusercontent.com/2775739/168193361-08c092b0-5976-43cd-9b34-3bea7cc2e051.png">

<img width="1146" alt="image" src="https://user-images.githubusercontent.com/2775739/168188251-324cf517-49f2-406f-bef9-07c81bee7699.png">

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 22.1.7_1 (amd64, OpenSSL)

**Comment by utkonos** [comment]
If anyone encounters this installer bug here is a workaround until the bug is fixed:

1. Login to the OPNsense web console.
2. Navigate to the `Interfaces` menu.
3. Select `Assignments`.
4. In the pane that appears on the right, click `Save`.

This will recreate the missing interface.

<img width="444" alt="image" src="https://user-images.githubusercontent.com/2775739/178157988-8f0288e1-a5e9-4cf8-887d-b70500ca3b18.png">

**Comment by fichtner** [comment]
Could it be the importer bug happened because wireguard plugin was not installed?

**Comment by utkonos** [comment]
The wireguard plugin is listed in the config.xml that the importer uses. However, I have noticed that the existence of that plugin in the XML does not cause the installer to install the wireguard `pkg` during install. That only happens after the first updates (or can be done manually).

**Comment by fichtner** [comment]
Yeah, which has the plugin code to create the group. The issue here, however, seems to be that from MVC code we do not create interfaces on config sace since that is only available in legacy code.

**Comment by utkonos** [comment]
Thanks @fichtner !

**Comment by fichtner** [comment]
@utkonos we are adding a slightly improved version for 22.7, but this needs more rework for 23.1 to integrate completely.

**Comment by fichtner** [comment]
note: mvc pluginctl -i mutable controller flag to call it since we need it for new ipsec vti api
