### ISSUE TITLE
Certificate Expired on Mirror

### ISSUE THREAD

**Issue by bigops** [opnsense/core#5772]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [ x ] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [ x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

The certificate of a Mirror in the US seems to have expired 

Certificate verification failed for /CN=mirrors.nycbug.org
34378686464:error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:/usr/src/crypto/openssl/ssl/statem/statem_clnt.c:1916:
Certificate verification failed for /CN=mirrors.nycbug.org
34378686464:error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:/usr/src/crypto/openssl/ssl/statem/statem_clnt.c:1916:
pkg: http://mirrors.nycbug.org/pub/opnsense/FreeBSD:13:amd64/22.1/latest/packagesite.txz: Authentication error

**Comment by AdSchellevis** [comment]
seems to be fixed now
