### ISSUE TITLE
Firmware API: $.product.product_latest is missing hotfix release number

### ISSUE THREAD

**Issue by Starkstromkonsument** [opnsense/core#5773]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

The 'product_latest' does not contain sub release numbers (e.g. for hotfixes). It only conteins 'x.y.z' and is missing the suffix '_a' if applicable.

**To Reproduce**

1. Go to 'https://[hostname of opnsense webui]:[port of opnsense webui]/api/core/firmware/info'
2. Navigate to '$.product'
3. Check 'product_latest' and 'product_version'
4. See them being different

**Expected behavior**

'product_latest' = 'product_version' = '22.1.7_1'

**Describe alternatives you considered**

None

**Screenshots**

None

**Relevant log files**

None

**Additional context**

RAW-Data for `$.product`

```
[
  {
    "product_abi": "22.1",
    "product_arch": "amd64",
    "product_check": {
      "api_version": "2",
      "connection": "ok",
      "downgrade_packages": [],
      "download_size": "",
      "last_check": "Sat May 14 20:54:34 CEST 2022",
      "needs_reboot": "0",
      "new_packages": [],
      "os_version": "FreeBSD 13.0-STABLE",
      "product_id": "opnsense",
      "product_target": "opnsense",
      "product_version": "22.1.7_1",
      "reinstall_packages": [],
      "remove_packages": [],
      "repository": "ok",
      "upgrade_major_message": "",
      "upgrade_major_version": "",
      "upgrade_needs_reboot": "0",
      "upgrade_packages": [],
      "upgrade_sets": []
    },
    "product_copyright_owner": "Deciso B.V.",
    "product_copyright_url": "https://www.deciso.com/",
    "product_copyright_years": "2014-2022",
    "product_crypto": "OpenSSL",
    "product_email": "project@opnsense.org",
    "product_flavour": "OpenSSL",
    "product_hash": "3cc3877c1",
    "product_id": "opnsense",
    "product_latest": "22.1.7",
    "product_mirror": "https://pkg.opnsense.org/FreeBSD:13:amd64/22.1",
    "product_name": "OPNsense",
    "product_nickname": "Observant Owl",
    "product_repos": "OPNsense",
    "product_series": "22.1",
    "product_time": "Thu May 12 05:12:53 CEST 2022",
    "product_version": "22.1.7_1",
    "product_website": "https://opnsense.org/"
  }
]
```

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 22.1.7_1-amd64
FreeBSD 13.0-STABLE
OpenSSL 1.1.1o 3 May 2022

**Comment by fichtner** [comment]
It’s intentional because hotfixes are not separated in changelogs.

**Comment by Starkstromkonsument** [comment]
Is there any other way to get the latest OPNsense firmware version (incl. hotfixes)?

**Comment by fichtner** [comment]
Yes, a normal check for updates. The “latest” trick avoids doing that by looking at changelog information instead of package information. It’s a lot lighter in terms of data exchanged.

**Comment by Starkstromkonsument** [comment]
Thx!
