### ISSUE TITLE
dpinger: works on gateways which support VIPs

### ISSUE THREAD

**Issue by fichtner** [opnsense/core#5777]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**

A few years ago we had issues with wrong "primary" address reading so we added reliable functions for it and concluded the replacement in 22.1. Now primaries are never VIPs by initial design, but some services wanting VIPs but not getting them from primary address fail for the right reasons.

**Describe the solution you like**

Add VIP listening support to dpinger.

**Describe alternatives you considered**

Not a real alternative as gateways already allow VIPs.

**Additional context**

#5766 
#4221
5509fabfa3c3d

**Comment by fichtner** [comment]
@eimann good morning, proposal is b37c1774a2 pending some discussion, but would be nice to know if it works for you:

    # opnsense-patch b37c1774a2


Cheers,
Franco

**Comment by fichtner** [comment]
Small issue during testing, it's cc6a80c164 now actually and it works from here in IPv4 and IPv6.

    # opnsense-patch cc6a80c164


Cheers,
Franco

**Comment by eimann** [comment]
I applied cc6a80c1649ce8d5d2d30ad74049a3d2bf8a72c8 saved the IPv6 gateway and applied this as well.
Unfortunately dpinger doesn't seem to start and I get:

```
[meta sequenceId="1"] /status_services.php: The required WANtest_GWv6 IPv6 interface address could not be found, skipping.
```

**Comment by fichtner** [comment]
@eimann sorry, screwed up the amendment, 34e47da should be the right one

    # opnsense-patch 34e47da


Cheers,
Franco

**Comment by eimann** [comment]
Yup, that works nicely. All green and pinging. Thank you for this fix :)

**Comment by fichtner** [comment]
Great, thanks!
