### ISSUE TITLE
wrong route for DNS server in multi-wan with duplicate gateway ips

### ISSUE THREAD

**Issue by Teruell** [opnsense/core#5779]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [Y] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [N] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

Multi-WAN set up with two system gateways which have the same gateway IP (same ISP), as follows:

Name: WAN4_Gateway (active), Interface: WAN4_igb4 Priority: 100 (upstream), Gateway: 100.64.0.1
Name: WAN5_Gateway, Interface: WAN5_igb5 Priority: 101 (upstream), Gateway: 100.64.0.1

Have configured DNS servers for each in System/Settings/General:

208.67.222.222 - WAN4_Gateway
208.67.220.220 - WAN5_Gateway

However, routes are configured as follows:

# route get default
route to: default
destination: default
gateway: 100.64.0.1
interface: igb4

# route get 208.67.220.220
gateway: 100.64.0.1
interface: igb4

# route get 208.67.222.222
gateway: 100.64.0.1
interface: igb4

So DNS for both gateways is actually going through only one of the interfaces.

**Expected behavior**

I would expect a route for 208.67.220.220 to be added for gateway 100.64.0.1 via interface igb5

**Describe alternatives you considered**

I have manually added the route and all seems to work as expected, but something seems to reset the route table periodically so this only works for a few seconds.

**Environment**

OPNsense 22.1.7_1-amd64

**Comment by fichtner** [comment]
Also more or less duplicates #5778
