### ISSUE TITLE
System privileges editor has incorrect URL prefix for Intrusion Detection log file browser

### ISSUE THREAD

**Issue by imyller** [opnsense/core#5781]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

System privileges editor has incorrect URL prefix for log file browser in `Services: Intrusion Detection`:

- `/ui/diagnostics/log/suricata/*`
- `/api/diagnostics/log/suricata/*`

Correct paths for Intrusion Detection (suricata) log viewer URL are:

- `/ui/diagnostics/log/core/suricata/*`
- `/api/diagnostics/log/core/suricata/*`

This causes Intrusion Detection -privileged  user account to have access to settings but not log file browser.

**To Reproduce**

1. Edit limited users or groups system privileges
2. Enable `Services: Intrusion Detection` access for the user
3. Login as limited user
4. `Services -> Intrusion detection -> Log File` menu item is not available

**Expected behavior**

User should have access to  `Services -> Intrusion detection -> Log File` and related `/ui/diagnostics/log/core/suricata` URL path.

**Environment**

OPNsense 22.1.7_1-amd64

**Comment by imyller** [comment]
Relevant privilege editor UI displaying the incorrect URL prefix for `Log File` menu item:
<img width="398" alt="opn_ids_logfile_privs" src="https://user-images.githubusercontent.com/1898870/169244615-afed4b00-a5a4-4037-b075-5a9ad5ad1b17.png">

**Comment by AdSchellevis** [comment]
@imyller nice catch, thanks! should be fixed in https://github.com/opnsense/core/commit/e810712f8b27068a4fec4b3ba0822e783851977a
