### ISSUE TITLE
netflow causes long boot and shutdown times, large /var/netflow/src_addr_details.sqlite files

### ISSUE THREAD

**Issue by benibilme** [opnsense/core#5787]
Hello, 

I am a casual home user, have been using opnsense for several years, and have NO  deep understanding of opnsense, underlying BSD system, just have read to documentation to be able to configure firewall rules etc. However I am long term linux user. 

After power outage,  my headless opnsense did not come back, I had to access via terminal console by hooking monitor, keyboard, etc. 

I have seen  bunch of invoking backup scripts that  take years specifically .20-netflow. I have seen that the firewall just taking too much time boot from backup scripts. I encounter similar issue, if I use reboot command from terminal console when accessed by ssh. 

Sometimes gui does not reboot the system and I have access it reboot manually. 

I have also seen gzip is failed error for /var/netflow/src_addr_details_XXX.sqlite  file which is currently 2.8gb 

The system boots but take years specifically the netflow parts. I do not  know the the use of netflow thing but it is possible to stop backup of this large file, how important to keep this file as it is or let it grow continously?  It is possible to reset the file. Is is possible to stop netflow altogether if it is not critical for firewall. I am not doing any traffic analyses and do not intent to export this file etc. 

I upgraded system to 22.1 and nothing has changed. 

Anyhelp or directions is greatly appreciated.

**Comment by Batnun** [comment]
I had the same problem... Just disable NetFlow:

Go to **Reporting** > **NetFlow**, and make the settings for all the interfaces is: **Nothing selected**
Then go to **Reporting** > **Settings**, and click on **Reset Netflow Data**

**Comment by AdSchellevis** [comment]
or disable periodic backups in "System: Settings: Miscellaneous"

**Comment by benibilme** [comment]
Thank you all for the answers. Both does the trick actually both seems to needed. RDD caches and any other files can be deleted safely via Report > Settings. Even if reporting is disabled, backup continues. So backup must be stopped as well.  I did both.
