### ISSUE TITLE
Network alias problem on 22.1.8

### ISSUE THREAD

**Issue by galibozek** [opnsense/core#5788]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

After upgrade from `22.1.7` to `22.1.8` i have problem with **network aliases type** with added **one entry**,
`pfctl -t $ALIAS_NAME -T show` returns **0** entries for this alias

**To Reproduce**

1. Add Alias type Network(s) with one entry (for example 10.10.0.0/24)
2. Reboot
3. Run `pfctl -t test_aliast_one_net -T show` to show entries

**Screenshots**
![Screenshot_20220525_211508](https://user-images.githubusercontent.com/70749001/170350562-223a6009-71e2-457c-adf6-9df3bdf995ec.png)

**Expected behavior**

`pfctl -t test_aliast_one_net -T show` return:
- 10.10.0.0/24

**Environment**

OPNsense 22.1.8 (amd64, OpenSSL).

**Comment by galibozek** [comment]
Updated

**Comment by vota** [comment]
can confirm this issue.
further discussion is already going on here: https://forum.opnsense.org/index.php?topic=28494

**Comment by c-vo** [comment]
I can confirm the problem. I work a lot with aliases and my whole network stopped after updating to version 22.1.8.

The problem can be solved temporarily with revert to the previous opnsense version, command:
opnsense-revert -r 22.1.7 opnsense

**Comment by AdSchellevis** [comment]
can you run the following command to populate the aliases manually and dump the output here?

```
/usr/local/opnsense/scripts/filter/update_tables.py 
```

**Comment by galibozek** [comment]
For me:
```sh
$ /usr/local/opnsense/scripts/filter/update_tables.py
{"status": "ok"}
```

**Comment by vota** [comment]
same for me - alias still broken
```
/usr/local/opnsense/scripts/filter/update_tables.py
{"status": "ok"}
```

**Comment by AdSchellevis** [comment]
these are all aliases with a single entry in them, right?

**Comment by galibozek** [comment]
I have one with one and many entries

**Comment by vota** [comment]
> these are all aliases with a single entry in them, right?

for me only network-aliases with one entry are affected

**Comment by AdSchellevis** [comment]
Can you try https://github.com/opnsense/core/commit/021786612cae12fe7557bf1627773f4f71cff50d ?

```
opnsense-patch 0217866
```

The loop seems to flush an empty value into the compare.

**Comment by galibozek** [comment]
it looks like it's ok now

**Comment by AdSchellevis** [comment]
@galibozek thanks for confirming!

**Comment by vota** [comment]
> opnsense-patch 0217866

can confirm. issues seems solved.

this wont be included in the 22.1.8-upgrade, right?
all my boxes will upgrade this WE automatically :)

**Comment by AdSchellevis** [comment]
@vota can't hotfix at the moment, it's an offday today. better stop the schedules if all of the machines use the same aliases for now.

**Comment by f45tb00t** [comment]
To fix the issue with the existing Outbound NAT and Firewall rules

1.    edit NAT rule and choose any other source with an alias
2.     edit FW rule which allows the flow for the NAT rule and change source to any other alias
3.    remove the alias which does not work
4.    add the same alias again. e.g LAN_192_xxx_xxx_xxx_24
5.   change the nat and the fw rules to the new created alias
6.    internet works again

**Comment by mannp** [comment]
> To fix the issue with the existing Outbound NAT and Firewall rules
> 
>     1. edit NAT rule and choose any other source with an alias
> 
>     2. edit FW rule which allows the flow for the NAT rule and change source to any other alias
> 
>     3. remove the alias which does not work
> 
>     4. add the same alias again. e.g LAN_192_xxx_xxx_xxx_24
> 
>     5. change the nat and the fw rules to the new created alias
> 
>     6. internet works again

Is this a remaining issue even with the patch applied on fresh systems, or ones on 22.1.8 still?

**Comment by Th4nat0s** [comment]
Thank's for having fix this quickly guys !...

**Comment by vota** [comment]
this issues seems to occure again after updating from 23.1.4 to 23.1.5

`pfctl -t $ALIAS_NAME -T show` 
returns nothing again when a networkalias only has one entry

steps to reproduce are the same:
1. Add Alias type Network(s) with one entry (for example 10.10.0.0/24)
2. Reboot
3. Run pfctl -t test_aliast_one_net -T show to show entries

also see: https://forum.opnsense.org/index.php?topic=33295

**Comment by Ketanest** [comment]
> this issues seems to occure again after updating from 23.1.4 to 23.1.5
> 
> `pfctl -t $ALIAS_NAME -T show` returns nothing again when a networkalias only has one entry
> 
> steps to reproduce are the same:
> 
>     1. Add Alias type Network(s) with one entry (for example 10.10.0.0/24)
> 
>     2. Reboot
> 
>     3. Run pfctl -t test_aliast_one_net -T show to show entries
> 
> 
> also see: https://forum.opnsense.org/index.php?topic=33295

Can confirm that.

**Comment by vota** [comment]
@AdSchellevis patch is already installed - can still reproduce the issue

**Comment by Ketanest** [comment]
@all switching the alias type to "Host" seems to solve this bug.

@AdSchellevis same at my firewall, patch does not solve it. Using on a amd64 hardware platform with Celeron J4125

**Comment by splooge** [comment]
Same issue.  Time seems to be fine.  NTP running.  HP-T620+.

This post from RSK fixed it for me: https://forum.opnsense.org/index.php?topic=33295.15

```
rm -f /var/db/aliastables/* && /usr/local/opnsense/scripts/filter/update_tables.py
```
I don't normally complain on the internet but this is a pretty serious screw up.  Perhaps you need to implement regression testing since this problem has happened before (22.1.8 and now 23.1.5)

**Comment by AdSchellevis** [comment]
@ALL highly annoying, it looks like I did reintroduce the same issue here https://github.com/opnsense/core/commit/e2dada5783e1fd86ec351f54897363c3b561390a . 

can you try `opnsense-patch e2dada5` to install this and reboot? on my end this seems to fix it.

**Comment by Ketanest** [comment]
> @ALL highly annoying, it looks like I did reintroduce the same issue here [e2dada5](https://github.com/opnsense/core/commit/e2dada5783e1fd86ec351f54897363c3b561390a) .
> 
> can you try `opnsense-patch e2dada5` to install this and reboot? on my end this seems to fix it.

Yes, seems so.

**Comment by fichtner** [comment]
> I don't normally complain on the internet but this is a pretty serious screw up. Perhaps you need to implement regression testing since this problem has happened before (22.1.8 and now 23.1.5)

If you want to throw wrenches either create a new ticket (this is off-topic) or open a PR with the work done.


Cheers,
Franco

**Comment by splooge** [comment]
Very well.

**Comment by vota** [comment]
> @ALL highly annoying, it looks like I did reintroduce the same issue here [e2dada5](https://github.com/opnsense/core/commit/e2dada5783e1fd86ec351f54897363c3b561390a) .
> 
> can you try `opnsense-patch e2dada5` to install this and reboot? on my end this seems to fix it.

yep  - working for me as well!
Thanks!

**Comment by AdSchellevis** [comment]
thanks for confirming! we restructured a lot for the aliases in this release, added unit tests for the various types (https://github.com/opnsense/core/tree/master/src/opnsense/scripts/filter/tests), but forgot to make a note about the empty value last time. Highly annoying, but not really preventable given the size of the operation under the hood. (this was needed to offer OpenVPN group aliases in a near future version and make aliases more pluggable).

**Comment by vota** [comment]
thanks for fixing it in that timely manner! I still love what you guys are doing.

another question: would this issue have occured earlier if i use the "development" release type? I've a few firewalls where no important infrastructure is running, which i patch automatically as soon as a release is available(hourly via cron).
These firewalls, never the less, are well monitoring. 
So a basic functionality issue (like an aliases- or firewall-rule-problem) would popup quickly after an upgrade. 
I could have reported it prior to release of the community-edition if the development-release is published earlier.
How often and when do you release the development-branch?

**Comment by AdSchellevis** [comment]
@vota thanks! and yes, we usually make sure patches are released for one or more cycles in the development branch. this one has been around since 23.1.2 if I'm not mistaken.

**Comment by fichtner** [comment]
The commit in question on master is:

```
commit 78b76cb5050d77ec27833ad018cee22e71550402
Author: Ad Schellevis <AdSchellevis@users.noreply.github.com>
Date:   Sun Feb 26 15:28:09 2023 +0100
```

It has been in the development version since 23.1.2 (March 07, 2023). The standard policy is to give it one round on the development release at least and here it was 3 rounds.

The development version is released in sync with the community version to at least batch a couple of changes  that make issues easier to pinpoint changes and avoid a daily flow of (incomplete) work chunks. But for most purposes the development version is relatively stable (I'm using it for the home office so the use cases that are covered there make catching regressions easy), but covering all scenarios all the time is difficult.

I think the user base of the development version is not very large for whatever reason and all users who want to help are encouraged to run development at home. What this ends up doing is making it also hard to catch all scenarios so that community releases can be affected as well.


Cheers,
Franco
