### ISSUE TITLE
Update to OPNsense 22.1.8 breaks Alias / Outbound NAT

### ISSUE THREAD

**Issue by f45tb00t** [opnsense/core#5789]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

After the update to OPNsense 22.1.8, my Internet did not work from LAN, DMZ, etc.... If checked the other setup but could not find any issues.  The FW itself still had internet access.
It seemed that the Outbound NAT did not work anymore.  I've disabled the NAT rules and created a new one at the top with a new alias for one of the hosts. This fixed the issue.

**To Reproduce**

1. Upgrade from 22.1.7 to 22.1.8
2. Outbound NAT did not work in my case

**Expected behavior**

Internet access for all hosts behind the FW

**Describe alternatives you considered**

To fix the issue with the existing Outbound NAT and Firewall rules

1. edit NAT rule and choose any other source with an alias
2. edit FW rule which allows the flow for the NAT rule and change source to any other alias
3. remove the alias which does not work
4. add the same alias again. e.g LAN_192_xxx_xxx_xxx_24
5. change the nat and the fw rules to the new created alias
6. internet works again

**Screenshots**

no screenshots

**Relevant log files**

no log files

**Additional context**

It tiik me quite some time to follow the procedure from above.
Can anyone else confirm this issue?

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 22.1.8 (amd64, OpenSSL).

**Comment by AdSchellevis** [comment]
duplicate https://github.com/opnsense/core/issues/5788
