### ISSUE TITLE
Interfaces: empty description + save removes the interface name from the title / menu

### ISSUE THREAD

**Issue by fichtner** [opnsense/core#579]

**Comment by AdSchellevis** [comment]
Technically it's not the interface page :) For some reason the check for an empty interface description failed, this https://github.com/opnsense/core/commit/df86acd7dba6c9b81f7ff3eebf8264d6b504f442 fixes it.

**Comment by fichtner** [comment]
Looks like it's not being saved as "null" anymore. Is that an intended change?

Also, isn't this also happening in the menu API as well?

**Comment by AdSchellevis** [comment]
I think it is still null in the config, but probably the old version removed the tag (<descr/>), doesn't really matter I guess. The item is pushed into the menu (it should move into the menu system at some point, but not now).

**Comment by fichtner** [comment]
I mean this :)

https://github.com/opnsense/core/blob/master/src/opnsense/mvc/app/controllers/OPNsense/Core/Api/MenuController.php#L133

**Comment by AdSchellevis** [comment]
oops, totally forgot about that one... in the end it should all move to that controller and the other two should be removed. thanks!
