### ISSUE TITLE
Unbound: Support Additional Serve Expired Settings

### ISSUE THREAD

**Issue by iamperson347** [opnsense/core#5795]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**

No

**Describe the solution you like**

Adjust the Unbound Advanced Settings page (/services_unbound_advanced.php) to support the following new Unbound settings:
- serve-expired-ttl
- serve-expired-client-timeout
- serve-expired-reply-ttl

**Describe alternatives you considered**

Setting these settings in `/usr/local/etc/unbound.opnsense.d/` (which does work)

**Additional context**

**Comment by dacioromero** [comment]
@swhite2 I'm admittedly new to OPNsense, but it doesn't seem like the additional serve expired settings were hooked up to `src/opnsense/service/templates/OPNsense/Unbound/core/advanced.conf` in #6053

**Comment by swhite2** [comment]
@dacioromero Must've slipped through, https://github.com/opnsense/core/commit/9966db9946b28b15b3df49c9be009c4641c93238
