### ISSUE TITLE
Traffic shaper to services?

### ISSUE THREAD

**Issue by fichtner** [opnsense/core#580]
The traffic shaper like captive portal runs on IPWF. If we disable the firewall (system settings), the traffic shaper can still be used. Can we move it to services?

**Comment by fichtner** [comment]
@jschellevis @AdSchellevis your thoughts please :)

**Comment by AdSchellevis** [comment]
@fichtner I vote for keeping it in the firewall section, it kind of seems more logical there then in the services section (and it uses a firewall to do it). We might however add an option to disable it with the firewall at some point (preferably not before 16.1).

**Comment by fichtner** [comment]
I agree, but would not net it undiscussed since @8191 was involved in discussing what is a firewall page and what is not. The idea of removing the firewall menu in case the firewall was disabled came up, which would inherently hide the traffic shaper in that case. It would look a bit funny if only the firewall pages disappear and the only firewall entry is the traffic shaper, but there's time to think and restructure on our way to 16.7. :D
