### ISSUE TITLE
aliases are completely broken in 22.1.8 and 22.1.8_1

### ISSUE THREAD

**Issue by Stifler6996** [opnsense/core#5805]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**
There are some other issues relating to aliases but not specifically this problem. However, there seems to be a bug causing the various  sub-problems related to aliases such as #5800, and the recent work in #5788 .

Aliases are not functioning in firewall rules. Aliases with "networks" fail to load as confirmed in Firewall->Diagnostics->Aliases.
Aliases are not functioning in firewall rules. Aliases with "ports" fail to load as confirmed in Firewall->Diagnostics->Aliases.

All functionality works in 22.1.7_1 however, changing aliases in 22.1.7_1 requires a reboot or a restart of all services from the console in order to populate them correctly. (Can be confirmed using Firewall->Diagnostics->Aliases).

I have rolled back to 22.1.7_1 so that the firewall functions as I need. However the last time it works completely correctly (no restarting services/reboot to fix it) was prior to 22.1.7_1, and I frequently skip minor updates, so I'm unable to pin point the exact revision that it last fully functioned.

**To Reproduce**

1. Upgrade 22.1.7_1 to 22.1.8(_1)
2. Firewall->Diagnostics->Aliases
3. All or some aliases will not be populated.
4. The other way I can confirm the alias is not working, is where I have "networks" aliases for network scanners like stretchoid, and I am still seeing them attempt to connect from networks in the alias that I have blocked. I would not normally see these attempts because the firewall rule using the alias is set to **not log** them therefore should not show up at all. but because the alias is broken, they are showing up as connection attempts.

**Expected behavior**

Aliases to work as intended.

**Describe alternatives you considered**

22.1.7_1 You can reset services from console (or reboot) to force the aliases to load.
22.1.8(_1) No such method seems to fix the aliases. They are either there or not, and nothing can reload the "empty" ones.

**Screenshots**

**Relevant log files**

**Additional context**

**Environment**

OPNsense 22.1.8_1 (amd64, OpenSSL).
ESXi 7.0.2 , VMXNET3 nics
Intel(R) Xeon(R) CPU E5-2620 v4 @ 2.10GHz

**Comment by Stifler6996** [comment]
Why did you flag this as support? This is a bug.
I've been using opnsense since v16, I don't need support, I need you to address a bug in the code.

**Comment by fichtner** [comment]
Fair enough, I can also close it if you don't need any help figuring out what is wrong before saying "a" "bug" "exists"? If it's a bug you probably know which line of code or which patch changed the behaviour. If not you probably want support for it.

**Comment by Stifler6996** [comment]
Well, I don't know what your tags mean. But a "support" tag certainly sounds like you are denying its a problem on your side.
No, I dont know your code, and no with what I have on my plate, I am not about to dive in to try to learn it.
I'm not a paid user so I don't expect a support service either. I'd respect a valid attempt to clarify the problem, or an attempt to look into it.
You will find Reddit is starting to find these problems in the aliases system, but I sought to use the proper channel and bring it up here.

**Comment by fichtner** [comment]
Please stop assuming and just try to be friendly which is the must have base for this level of interaction that you seek.


Cheers,
Franco

**Comment by fichtner** [comment]
Just as an FYI the tags are briefly explained here: https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

**Comment by Stifler6996** [comment]
As I expected: `support: community-based help figuring out setup issues or code problems`
This will go nowhere. I no longer wish to support this software. I will seek alternatives.

**Comment by fichtner** [comment]
Note to future readers: doing open source bug triage on a national holiday / Sunday. We're following standard protocol to allow time to verify a bug which can't always happen instantly :)
