### ISSUE TITLE
Aliases "Enable / Disable" checkbox no longer functions since update to 22.1.8_1

### ISSUE THREAD

**Issue by copperheadclgp** [opnsense/core#5808]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**
Since upgrading to 22.1.8_1-amd64, the ability to enable and disable Aliases using a combination of checkbox + Apply button no longer functions. There is a new column that appears next to the checkbox that shows either 1 (enabled) or 0 (disabled) but this value does not change.

**To Reproduce**

1. Go to 'Firewall > Aliases'
2. Click on the checkbox for an alias
3. Click 'Apply'
4. Observe that the alias does not enable or disable as expected.

**Expected behavior**

Should behave as in previous releases, wherein the administrator can select one or more aliases and enable / disable them en-mass. 

**Describe alternatives you considered**

Aliases can be enabled / disabled singularly as expected via the 'Edit' button.

**Screenshots**

[image](https://user-images.githubusercontent.com/51468137/172453374-254b98c0-c636-45fe-83e2-65abc9677efc.png)

**Environment**

OPNsense 22.1.8_1 (amd64, OpenSSL).
AMD GX-412TC SOC 
PCEngines APU2

**Comment by fichtner** [comment]
3dac44b77a maybe?

    # opnsense-patch 3dac44b77a


Cheers,
Franco
