### ISSUE TITLE
Feature Request - Netflow Exporter

### ISSUE THREAD

**Issue by willjones** [opnsense/core#581]
Feature Request:

Add netflow exporter (softflowd, or ng_netflow) with a basic GUI and support for v5 & v9 export.

**Comment by langerma** [comment]
+1 ipfix would be awesome as well

**Comment by fichtner** [comment]
I agree, this is a good roadmap item for 16.7 :)

**Comment by fichtner** [comment]
(This should probably be a plugin)

**Comment by pieton** [comment]
Looking forward getting Netflow.

**Comment by fichtner** [comment]
First bits of this are going to hit the development version soon. :)

**Comment by AdSchellevis** [comment]
The development version (github) contains a functional netflow collector, in case anybody wants to try it out, don't forget to install samplicator first. 

![schermafbeelding 2016-03-25 om 17 39 51](https://cloud.githubusercontent.com/assets/9783985/14048761/a18c5178-f2b0-11e5-98f1-264c5f7f87b4.png)
![schermafbeelding 2016-03-25 om 17 40 25](https://cloud.githubusercontent.com/assets/9783985/14048773/bad17582-f2b0-11e5-82c3-600542eff069.png)

**Comment by fichtner** [comment]
Already in the development version, closing in anticipation of a release in maybe 1-2 weeks from now.
