### ISSUE TITLE
DHCPv4 server assigns same IP to multiple clients (randomized MAC address)

### ISSUE THREAD

**Issue by Proper-Job** [opnsense/core#5810]
I have a static DHCPv4 mapping defined for one of the clients in my LAN net ([GUI page](https://192.168.1.1/services_dhcp.php?if=lan))
The static mapping uses the client's non-randomized MAC address to assign the local IP: 192.168.1.168
This works as expected until clients with randomized MAC addresses enter the network.
The attached screenshot illustrates that 2 clients with different MAC addresses are both assigned the local IP 192.168.1.168
The '7c' MAC address is non-randomized and the mapping is static. The '5e' address is randomized and the device erroneously receives the same IP address.

As soon as I disable MAC address randomization, the 2 clients receive different IPs.

**To Reproduce**

1. Go to Service > DHCPv4 > [Lan]
2. Create static mapping with non-randomized MAC address
3. Connect that client to the network
4. Connect a client with randomized MAC address to the same network

**Expected behavior**

Both clients have separate IP addresses

**Describe alternatives you considered**

I have disabled MAC address randomization for all clients which mitigates this issue.

**Environment**

OPNsense 22.1.8_1-amd64
FreeBSD 13.0-STABLE
OpenSSL 1.1.1o 3 May 2022

Intel(R) Core(TM) i7-4600U CPU @ 2.10GHz (2 cores, 4 threads)
<img width="1392" alt="opnsense_leases" src="https://user-images.githubusercontent.com/5182820/172843503-7b6a08e4-c948-4874-9d61-d6c9545c3baa.png">
<img width="1392" alt="static_mapping" src="https://user-images.githubusercontent.com/5182820/172843511-b835f08d-5263-4a29-9abf-61355e8ad227.png">

**Comment by fichtner** [comment]
@Proper-Job we recommend assigning static IPs outside of the dynamic pool(s) configured for safety reasons...

**Comment by Proper-Job** [comment]
@fichtner ok let me try that, thank you

**Comment by fichtner** [comment]
I think what makes this more prominent nowadays is f83a74d4961c2a0c0 which fills in the IP that shouldn't be used CC @AdSchellevis

**Comment by Proper-Job** [comment]
@fichtner I can confirm that moving the static mapping outside the dynamic DHCP pool mitigates this issue. Thank you for your fast reply.

**Comment by rosmo** [comment]
What if we added `infinite-is-reserved` for dhcpd as a configurable option and only then pass the ipaddr to the static lease creation page? If I'm understanding the option correctly, that should allow the IP address of be reserved out of the pool in perpetuity?

**Comment by fichtner** [comment]
@rosmo might be good to try it out locally first. I wouldn't mind a PR in this case
