### ISSUE TITLE
503 Service Unavailable

### ISSUE THREAD

**Issue by filmar25** [opnsense/core#5818]
**Describe the bug**

Cannot have Web UI of OpnSense

I upgrade my OpnSense last week at the last Community version available by the web interface and I was able to continue have access to the Firewall without problem. No configuration has been changed, just update.

Yesterday I was able to access OpnSense without problem, but today, I cannot access anymore the Web Interface. I didn't change nothing since the update. I reboot the firewall and the problem still there.

When I enter the URL to access it, I got 503 Service Unavailable. I have tried directly by IP address and I got the same message. I tried from my phone too and I got the same error.

I can connect to the firewall via SSH without problem. Just the Web Interface stop working. It seems that all the rest also working. I have HAProxy that continue working normally because external access to DMZ web app is working, we continue to have Internet access from LAN, etc.

**To Reproduce**

1. Open URL with DNS or IP from LAN network
4. Got Error 503 Service Unavailable

**Expected behavior**

Like yesterday, I must have Web UI interface working properly.

**Describe alternatives you considered**

I have tried opnsense-revert -r 22.1.7 but it is not working.

No workaround.

**Screenshots**

![image](https://user-images.githubusercontent.com/44647654/173901906-277b79e0-2db4-4d43-a206-387f3532cd45.png)

**Relevant log files**

Can get if needed

**Additional context**

```
Internet
==> OpnSense (HAProxy, ACME client, DynDNS, Intrusion Prevention, Antivirus)
     ==> DMZ
     ==> LAN
          ==> PC accessing OpnSense Web UI
```

**Environment**

OPNsense 22.1.8 (amd64, OpenSSL).
Intel Core i5-2400 3.1GHZ, 8GB DDR3 RAM
2 STARTECH ST1000BT32 PCI
120 GB SSD

**Comment by mimugmail** [comment]
If you disable HAproxy and restart the box, does it work again?

**Comment by filmar25** [comment]
Can you tell me how can I disable it with SSH ?

Thank you !

**Comment by filmar25** [comment]
Like my image, I have bird brain !!

There is my problem : My browser reset my url history. So I entered my url like before, but I forgot to specify the port !!
