### ISSUE TITLE
DEV - Captive Portal - Confusing help text

### ISSUE THREAD

**Issue by DokuKaefer** [opnsense/core#582]
The second sentence is a little bit confusing.

![captive_portal](https://cloud.githubusercontent.com/assets/11537653/12054884/9abd5d50-af27-11e5-9029-34c300f7087b.png)

**Comment by AdSchellevis** [comment]
@DokuKaefer Not sure what you mean there, the error message or the help text itself. Suggestions are welcome :)

**Comment by DokuKaefer** [comment]
Hey AD, the help text says "leave this field blank..." but you need a 0 (ZERO) for no hard timeout. ;)

**Comment by AdSchellevis** [comment]
I totally missed that one, but now I understand what you mean, this needs fixing :)
