### ISSUE TITLE
Dual PPOE WAN Load Balancing and gateway behaviour

### ISSUE THREAD

**Issue by SukMeWot** [opnsense/core#5821]
I have 2 WAN connections defined as WAN and OPT1, both connections are PPOE configured with independant accounts and settings. Both are fixed IP, one is an IP range, the other a single IP. 

Servers I operate need ingress and egress to be via specific gateways, this is due to the IP addresses and public domain records - they are NOT dynamic IP address's. 

In order to gain best value from both PPPOE connections a load balancing and failover binding of the two PPPOE connections is required. To ensure that traffic is 'shaped' according to total bytes transmitted and each connection receives half the outbound traffic.

The problem : Load Balancing following numerous 'internet' guides does not work. Also specified gateways are not being respected.

Steps to  create

1. Define WAN interface to connect to PPPOE account 1.
2. Define OPT1 interface to connect to PPPOE account 2.
3. Define Virtual IP's to represent the public facing IP addresses in use.
4. Define Aliases for the internal Web and Mail servers (2 of each)
5. Define NAT 1:1 for public IP's on PPPOE account 1 to relevant internal hosts.
6. Set PPPOE account 2 as default gateway.
7. Verify function of 1:1 connections using MX Toolbox. External incoming connections behave as expected.
8. Send an Email from inside the firewall and check it leaves the corrrect PPPOE account 1 gateway : It does NOT
9. Reboot both OPNSense and the mail server to ensure states are cleared
10. Send an Email from inside the firewall and check it leaves the corrrect PPPOE account 1 gateway : It does NOT
11. Create a failover gateway group comprising PPPOE account 1 (WAN) and PPPOE account 2 (OPT1), set both to tier 1, failover on packet loss / latency. IP's used for monitoring are 4.2.2.1 and 4.2.2.2 respectively (Level 3 root responders)
12. Set the failover gateway as the 'default' gateway on the LAN firewall outbound rule
13. Ensure that changing default gateway is permitted.
14. Observe that failover functions on disconnecting a PPPOE account - it does - note that internal performance for DNS resolving really doesn't like this so many sessions fail and cannot be re-established - seems like the states for the failed gateway are not cleared but I didn't verify.
15. Using Netflow identify traffic leaving is even between WAN and OPT1 : It is NOT - All traffic leaves via the default gateway regardless, this gateway never changes unless it fails and all traffic exits the default unless it fails.

DO NOT establish any kind of ubound or DNS resolving in the OPNsense configuration. All DNS and DHCP must be handled by a server in the LAN.

In the log you see things like this - these errors aren't - this is false reporting - this is the public facing IP, it is fixed - 'couldn't find a proper match' - proper match with what - same error on OPT1 it also is fixed IP but shows the same error.

<html><body>

2022-06-20T12:42:46 | Error | opnsense | /usr/local/etc/rc.newwanip: Choose to bind ZEN1_PPPOE on 82.68.70.254 since we could not find a proper match. |  
-- | -- | -- | -- | --

</body>
</html>

**Comment by fichtner** [comment]
Hi,

I'm not sure what the yard stick for "Send an Email from inside the firewall and check it leaves the corrrect PPPOE account 1 gateway : It does NOT". Do you use a rule with gateway set? I mean you literally set PPPOE 2 to default. 1:1 is for incoming, not outgoing if it was implied it should be enough.

The log message is diagnostic and was improved upon in https://github.com/opnsense/core/commit/99d16b7ea738 which is scheduled for 22.1.9.


Cheers,
Franco

**Comment by SukMeWot** [comment]
Sorry for misleading - I do actually have dedicated LAN outgoings with the appropriate gateway set.  Let me know what you need - I will keep things running a while longer although I've now purged the loadbalancing gateway it won't take much to put it back

**Comment by fichtner** [comment]
> Sorry for misleading - I do actually have dedicated LAN outgoings with the appropriate gateway set. Let me know what you need - I will keep things running a while longer although I've now purged the loadbalancing gateway it won't take much to put it back

I'm not sure what that means now. You need policy based firewall rules with gateway set, either single or group in a rule in order to route to specific gateway or load balance. In your mail server case it seems to be the first. Is the rule in place? Is it being evaluated and matched? (you can see that from the inspection).

Local tests on the firewall don't work for confirmation of correct routing since the LAN rules filter on inbound traffic setting gateway on outbound. You need to test from the mail server.


Cheers,
Franco

**Comment by SukMeWot** [comment]
I've had little choice but dump OpnSense, the same configuration used in PfSense works fine, in OpnSense it does not, I do not have the time to mess with this. It is interesting the world over that tech support is generally tech avoid, there is a problem, whether that is accepted or not is no longer my concern - pFSense works.

**Comment by fichtner** [comment]
Just as a comment: 1 month without a reply from @SukMeWot makes me shake my head what support void was even referenced. If you need business support instead of community support just get that from the shop as that likely fits your constraints better but also I can’t make you reply to progress this. 🤷‍♂️
