### ISSUE TITLE
HA stuck states after PKG update

### ISSUE THREAD

**Issue by ElXk6** [opnsense/core#5822]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

It seems like a package update could lead to an HA state change, which in turn leads to a stuck backup state (on Master Firewall).
The problem here was that the master firewall had multiple interfaces with backup state and the backup firewall had multiple interfaces with master. The solution was to restart the backup firewall. Restarting the Master Firewall didnt solve the Problem.

I have an autoupdate cron job that starts every Monday at 11pm:
`      0	23	*	*	1`
	  
A config change/reload can be seen in the logs:
```
   2022-06-20T23:24:33 Notice syslog-ng  Configuration reload finished;
   2022-06-20T23:24:33 Notice syslog-ng  Configuration reload request received, reloading
configuration;
```

In the history you can see a config.xml change from the script "/usr/local/opnsense/mvc/script/run_migrations.ph" at 23:24:41:
```
   -    <captiveportal version="1.0.0">
   +    <captiveportal version="1.0.1">
```

The first problems start at 23:25:38 (see attached File).

The same may have happened to other firewalls in the past month, but here it was multiple packets (unfortunately I don't have any more logs here. OPNsense Version 22.1.7):
```
   -    <Syslog version="1.0.0">
   +    <Syslog version="1.0.1">
   +      <vxlans version="1.0.1"/>
   +      <loopbacks version="1.0.0"/>
   -    <cron version="1.0.2">
   +    <cron version="1.0.3">
```
   
Is this an error that could just happen when updating and one should be careful, or is this a bug that shouldn't happen?
Is such a problem already known, or am I on the wrong track here?

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 22.1.8_1-amd64
FreeBSD 13.0-STABLE
OpenSSL 1.1.1o 3 May 2022
AMD GX-416RA SOC (4 cores, 4 threads)

**Comment by ElXk6** [comment]
Forgot the log file ..
[system.log](https://github.com/opnsense/core/files/8946672/system.log)
.

**Comment by fichtner** [comment]
Hi @ElXk6,

I'm not sure what the actual problem is being reported here. Yes, model versions change over time, but either the sync is carried out in full or the local migration fills config.xml contents to make it operational. However, it's very unlikely a running master node stops working (in full or partially) because of this.

So again, we need to know what the problem is: mixed master/backup states for interfaces in the HA pair?


Cheers,
Franco

**Comment by ElXk6** [comment]
Hey thanks for the reply,


> however, it's very unlikely a running master node stops working (in full or partially) because of this.

yes, I thought so too

> So again, we need to know what the problem is: mixed master/backup states for interfaces in the HA pair?

yes, the problem was mixed master/backup states for interfaces in the HA pair.
It already happend on to different HA pairs (but there is 1 month time in between). 

But for both the problems started seconds after a configuration reload and model version changes.
So I thought it might be related to that. Another problem is not visible for both Firewalls.

**Comment by ElXk6** [comment]
Sorry for the very late feedback.
Unfortunately, the problem is still not properly known.
The only noticeable thing was IPv6 errors on one Interface "Error dhcp6c transmit failed: Network is down".

Since I disabled IPv6 for this interface, everything works as usual again.
Maybe the problems with the update happened accidental at the same time, which is why I mistakenly assumed that was the error. 

Maybe a dying device at the interface causes the problems.

---

Issue can be closed.
