### ISSUE TITLE
Interface wireless settings get removed on first form submission with newly installed config

### ISSUE THREAD

**Issue by keyandthegate** [opnsense/core#5825]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

Wireless settings get cleared on WAN interface after first form submission in fresh install.

**To Reproduce**

1. Fresh install, with WAN assigned to a wireless interface. 
2. Go to https://192.168.1.1/interfaces.php?if=wan
3. Submit the form
4. The wireless settings disappear
5. The following error is reported:
```
PHP Warning:  Illegal string offset 'wep' in /usr/local/www/interfaces.php on line 523
PHP Warning:  Illegal string offset 'mode' in /usr/local/www/interfaces.php on line 909
```

**Expected behavior**

The wireless settings should not disappear.

**Describe alternatives you considered**

It looks like the config initially contains:
```
<interfaces>
...
  <wan>
    ...
      <wireless/>
```

In [interfaces.php:986](https://github.com/opnsense/core/blob/249afc5/src/www/interfaces.php#L986), that evaluates as "empty", and doesn't get copied:
```
            if (!empty($old_config['wireless'])) {
                $new_config['wireless'] = $old_config['wireless'];
            }
```

A workaround is editing the initial config to:
```
<interfaces>
...
  <wan>
    ...
      <wireless><mode></mode></wireless>
```

**Comment by fichtner** [comment]
@keyandthegate thanks, I assume this as created from the console port assignment. Patch is 91b840d and you can apply with:

    # opnsense-patch 91b840d


Cheers,
Franco

**Comment by fichtner** [comment]
No response so far but should be fine. Added to pre-RC test rotation in any case to give it one more look.
