### ISSUE TITLE
Reporting Insight - Wireguard and ZeroTier switched interface

### ISSUE THREAD

**Issue by jkumar2001** [opnsense/core#5827]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

Reporting Insight - Wireguard and ZeroTier switched interface

*Tip*: to validate your setup was working with the previous version, use opnsense-revert (https://docs.opnsense.org/manual/opnsense_tools.html#opnsense-revert)

**To Reproduce**

1. Created a Wireguard VPN interface, 
2. Created a Zerotier VPN interface,
3. Both work perfectly fine.
4. Reporting --> Insight switched the interface names (WG0 showing up as ZT0 and vice versa)
5. Packet capture on each interface shows up no anomaly 
6. Realtime traffic under Reporting --> Traffic (Graph and Top Talkers) show correct traffic for each of these interfaces.

**Expected behavior**

Each interface should show correct metrics in Reporting --> Insight 

**Describe alternatives you considered**

I have tried following

Stop Netflow, Delete Netflow data, Star Netflow

Reboot Firewall

**Screenshots**

**Relevant log files**

If applicable, information from log files supporting your claim.

**Additional context**

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 19.1.1 (amd64, OpenSSL).
Intel® Xeon™ E3-1225V5 3.3Ghz Quad Core
Network Intel® I210-AT

**Comment by craigsansam** [comment]
I am experiencing a similar issue - but my WAN and Wireguard interfaces have switched.

I have checked a packet capture on both interfaces and see the expected traffic.
