### ISSUE TITLE
Feature Request on Naming Interfaces

### ISSUE THREAD

**Issue by andreasvel** [opnsense/core#583]
Hi, referenced to https://forum.opnsense.org/index.php?topic=1924.0 (german) and 
https://forum.opnsense.org/index.php?topic=1452.0 (german)
i would like to request

Option to Rename the Interfaces from OPT to WAN/LAN/DMZ or something like that
Option to colorize the Interfaces in the Overview to get fast an overview

Referencing to https://github.com/opnsense/core/issues/534 to get this all in a redesign of the overview perhaps like Sophos

picture http://www.bilder-upload.eu/show.php?file=fe4e55-1451501044.jpg

**Comment by AdSchellevis** [comment]
We already have a description to identify interfaces, the internal names are used at more places in the code which aren't a very good idea to change.
I will make the interfaces collapsible to improve the overall overview a bit.
