### ISSUE TITLE
Firmware: flock-2.37.2 is repeatedly reinstalled on our Desktop Appliance running OPNsense 22.1.9 

### ISSUE THREAD

**Issue by lastzero** [opnsense/core#5832]
**Describe the bug**

The `flock-2.37.2` package is constantly getting reinstalled on our [Desktop Security Appliance](https://shop.opnsense.com/) since the last update.

**To Reproduce**

Upgrading to OPNsense 22.1.9-amd64 might reproduce the issue, but we only have one appliance available to connect to the internet. So I cannot reinstall it to verify this happens again.

**Expected behavior**

The package should only be installed / upgraded once.

**Describe alternatives you considered**

Complete reinstallation, which does not seem to be reasonable, since the appliance works without any other (known) problems.

**Screenshots**

![onsense-flock-reinstall](https://user-images.githubusercontent.com/301686/175937692-3e67a3ae-8204-4e7b-a7d8-ae199c9bffcc.png)

**Relevant log files**

```
***GOT REQUEST TO CHECK FOR UPDATES***
Currently running OPNsense 22.1.9 (amd64/OpenSSL) at Mon Jun 27 13:53:45 CEST 2022
Fetching changelog information, please wait... done
Updating OPNsense repository catalogue...
Fetching meta.conf: . done
Fetching packagesite.pkg: .......... done
Processing entries: .......... done
OPNsense repository update completed. 792 packages processed.
All repositories are up to date.
Checking integrity... done (0 conflicting)
Your packages are up to date.
Checking for upgrades (46 candidates): .......... done
Processing candidates (46 candidates): . done
The following 1 package(s) will be affected (of 0 checked):

Installed packages to be REINSTALLED:
	flock-2.37.2 (option added: NLS)

Number of packages to be reinstalled: 1

21 KiB to be downloaded.
***DONE***
```

**Environment**

Our appliance is currently running **OPNsense 22.1.9-amd64 on FreeBSD 13.0-STABLE with OpenSSL**.

Unfortunately, I don't know which version we upgraded from. However, if it is helpful, I can provide you with a complete list of installed packages.

**Comment by lastzero** [comment]
Looks like this "NLS option" is causing the behavior then. Why is the NLS option added? What is it needed for? Does it depend on other OPNsense packages we have installed, like IDS or VPN software?

@AdSchellevis Running "pkg install -f flock" in a terminal works without any problems, but flock is still reinstalled when I update in the user interface afterwards:

```
Updating OPNsense repository catalogue...
OPNsense repository is up to date.
All repositories are up to date.
Checking integrity... done (0 conflicting)
The following 1 package(s) will be affected (of 0 checked):

Installed packages to be REINSTALLED:
  flock-2.37.2

Number of packages to be reinstalled: 1

Proceed with this action? [y/N]: y
[1/1] Reinstalling flock-2.37.2...
[1/1] Extracting flock-2.37.2: 100%
```

Note:
- the NLS option is missing when running the command as you suggest
- this is the first time I use a terminal to avoid problems with incompatible packages or configurations

**Comment by lastzero** [comment]
I can't imagine ever using Cloudflare, so hopefully that's not installed 😂

The UI shows this, so 4 more or less essential packages in addition to the base packages that cannot be uninstalled:

![opnsense-plugins](https://user-images.githubusercontent.com/301686/176012679-9992859d-05e4-4292-b8d8-7af193d05aae.png)

If DynDNS or Wireguard are bad, maybe I can find alternatives, e.g. run the services on another device. If it's the theme, I can also cope with a light theme...

As I maintain a large FOSS project myself, I won't randomly install tons of packages and then complain that something doesn't work anymore. However, I hope this helps you or other users who see the same and don't know what it even means.

**Comment by AdSchellevis** [comment]
Which mirror are you using? (in the settings tab) The plugins don't look suspicious from my end to be honest.

**Comment by fichtner** [comment]
Note I said “cloud flare mirror” as @AdSchellevis tries to emphasise here.

flock is a standard tool bundled with core. I’m in doubt anybody else messes with this and the package progression is clear.

**Comment by lastzero** [comment]
Oh, now I understand. Thanks for the clarification! I thought it was a package that required NLS.

Changing the mirror actually fixed the problem and we'll be happy to switch back to the Business Edition once our own project generates some revenue. 🥳

**Comment by AdSchellevis** [comment]
@lastzero thanks for reporting back, good to know it's indeed the mirror setting.
