### ISSUE TITLE
Bug: Time Range Description not applied after clicking "Add Time"

### ISSUE THREAD

**Issue by 8191** [opnsense/core#585]
The _Time Range Description_ is ignored after clicking _Add Time_ in the "Firewall: Schedules" view.

**Comment by AdSchellevis** [comment]
At my end it isn't ignored, but the alignment is a bit strange. 
I've fixed the alignment in https://github.com/opnsense/core/commit/6b48c193870d78be40e7b749ece346db30b2b3de can we close this or am I overlooking something here?

(I probably should have rebuild the javascript code as well here, it's still quite messy)

**Comment by 8191** [comment]
You're right... I overlooked that the description was just left-aligned - not missing... :wink:
