### ISSUE TITLE
configd - BrokenPipeError on long running processes

### ISSUE THREAD

**Issue by agh1467** [opnsense/core#5850]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

`BrokenPipeError` occurs if Backend::configdRun() leaves the configd socket before execution is complete.

Logs:
```
<163>1 2022-07-04T08:52:19-04:00 OPNsense.localdomain configd.py 88361 - [meta sequenceId="1"] Timeout (20) executing : module_name command_name
<13>1 2022-07-04T08:52:20-04:00 OPNsense.localdomain configd.py 385 - [meta sequenceId="2"] unable to sendback response [{     "json_key": "json_value" }  ] for [module_name][command_name] {4313e30d-4420-4420-a64d-c67111e38449},
message was Traceback (most recent call last):
   File "/usr/local/opnsense/service/modules/processhandler.py", line 202, in run
     self.connection.sendall(('%s\n' % result).encode()) BrokenPipeError: [Errno 32] Broken pipe
```

This error is currently caught by:
https://github.com/opnsense/core/blob/1d769e6e6cec6594ca0409c2b8b2d7539b90c558/src/opnsense/service/modules/processhandler.py#L215-L219

Why the pipe breaks is unclear to me, as the process eventually completes execution without error, apparently unbroken. Maybe the broken pipe is referring to the connection to the socket by configdRun() and not anything to do with the process itself?

**To Reproduce**

This happened under these conditions:
1. Using Backend::configdRun() with timeout value lower the the time it takes to execute a command.
2. Executing a process which takes more time than the specified timeout value (in this case an API call to an external system which had a delayed response).

The message `Timeout (20) executing` comes from Backend::configdRun():
https://github.com/opnsense/core/blob/1d769e6e6cec6594ca0409c2b8b2d7539b90c558/src/opnsense/mvc/app/library/OPNsense/Core/Backend.php#L136

While `unable to sendback response` comes from processhandler.py:
https://github.com/opnsense/core/blob/1d769e6e6cec6594ca0409c2b8b2d7539b90c558/src/opnsense/service/modules/processhandler.py#L217

You can reproduce this with the following:
Test script: `/tmp/test.php:`
```php
<?php

require_once('/usr/local/opnsense/mvc/app/library/OPNsense/Core/Backend.php');
require_once('/usr/local/opnsense/mvc/app/library/OPNsense/Phalcon/Logger/Logger.php');

use OPNsense\Core\Backend;

var_dump((new Backend())->configdRun("noexist long", false, 5));
```
configd action file: `/usr/local/opnsense/service/conf/actions.d/actions_noexist.conf`
```ini
[long]
command: sleep 10 && echo Hello
type:script_output
```
After placing the files:
1. Restart configd `service configd restart`
2. Execute test script `php /tmp/test.php`
3. Wait 5 seconds for the php to terminate.
4. Wait 5 seconds for the configd command to finish
5. Review configd log: `tail /var/log/configd/latest.log`

**Expected behavior**

Maybe a clearer message about whatever it is that's happening.

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 22.7.a_431-amd64
FreeBSD 13.0-STABLE
OpenSSL 1.1.1o 3 May 2022

**Comment by agh1467** [comment]
Ok, so I think I understand then.

Doing some experimenting, I found that both of the last two sendall() calls will produce this error. Both could be try/excepted, and passing on the first, but that seems repetitive, like this:
https://github.com/agh1467/core/blob/c6f67e7651ac7f0467990fdd82e774de22fe2735/src/opnsense/service/modules/processhandler.py#L200-L219

I was thinking about this approach, and thought continuing through to the second call seems unnecessary. Here's an approach which re-raises with an additional exception which includes a message.

https://github.com/agh1467/core/blob/edfb8752fee144692a59d0e99a93c3a1a3c49982/src/opnsense/service/modules/processhandler.py#L200-L205

Looks like this in the logs:
`<13>1 2022-07-04T14:26:10-04:00 OPNsense.localdomain configd.py 82707 - [meta sequenceId="10"] unable to sendback response [Hello  ] for [noexist][long][None] {5a6f3a05-7c7d-4f7c-8504-85716b997164}, message was Traceback (most recent call last):   File "/usr/local/opnsense/service/modules/processhandler.py", line 203, in run     self.connection.sendall(('%s\n' % result).encode()) BrokenPipeError: [Errno 32] Broken pipe  The above exception was the direct cause of the following exception:  Traceback (most recent call last):   File "/usr/local/opnsense/service/modules/processhandler.py", line 205, in run     raise Exception('socket connection terminated before execution finished') from e Exception: socket connection terminated before execution finished
`

This at least provides some context as to what the broken pipe is about, but this makes the messaging verbose.

Another option would be to except on the whole try block alongside the SystemExit except, but that's not as precise as trying only a single command when it's understood why the BrokenPipeError might occur.

I looked for a way to break/continue out of the parent try block but I lack such knowledge if that's possible. I imagine that a good way to handle it would be to syslog_notice() the message, and then gracefully bail on the rest without raising an exception.

**Comment by AdSchellevis** [comment]
To be honest, I don't think this is super important and I'm not sure I want to spend a lot of time on this, but if we would like to  treat `BrokenPipeError`'s differently, we could likely add an except for it above :

https://github.com/opnsense/core/blob/6a69e524e09a4bf1e1c3e8fdb47f902f9eceaedc/src/opnsense/service/modules/processhandler.py#L215

And send it to log there, but in my opinion it wouldn't be that different as the log level is already pretty low and the message quite explicit due to the BrokenPipeError itself.

**Comment by agh1467** [comment]
I see your points. I'm going to close this as there isn't much value in changing it.
