### ISSUE TITLE
MVC - Empty value skips validators

### ISSUE THREAD

**Issue by agh1467** [opnsense/core#5853]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**
Referencing this occurrence:
https://github.com/opnsense/core/blob/1d769e6e6cec6594ca0409c2b8b2d7539b90c558/src/opnsense/mvc/app/models/OPNsense/Base/FieldTypes/TextField.php#L64-L78

The condition `$this->internalValue != null` will evaluate to false when internalValue is an empty string. This may be intended, but I found this to be unexpected as this results in an empty string performing no validations, so a configured regex pattern is not applied, and allows an empty string to be saved into the config, even when the pattern might require a non-empty value.

**To Reproduce**

I put together some tests for TextField which includes a test for this usage. I saw TextField didn't have any, so I made these PHPUnit tests:
https://github.com/agh1467/core/blob/pr-validator-null-check/src/opnsense/mvc/tests/app/models/OPNsense/Base/FieldTypes/TextFieldTest.php

Execute the tests like:
`cd /usr/local/opnsense/mvc/tests`
`phpunit -c PHPunit.xml --filter "TextFieldTest"`

`testEmptyStringWithNonEmptyMask` will fail.

To do it manually:

This isn't ideal since it edits the config out of band, however, it's a way to do it with just Core.

1. Services: Monit: Settings
2. See that defaults are provided for several settings including Start Delay, and Mail server.
3. Click Save
4. Edit /conf/config.xml
5. Delete the values in the <monit> node for `<startdelay>` and/or `<mailserver>`
6. Save the config file
7. Refresh the page
8. See that the values for Start Delay, and Mail server are empty.
9. Click save.
10. No error appears, and the empty values are saved to the config.

Both of the fields above are required (which is probably something else entirely but I'd guess similar reason), but mailserver has a mask assigned to it.

**Expected behavior**

Validators are performed even on an empty value.

The below seems to address the issue, but I'm not very familiar with the validators to fully understand. It negates `===` instead of `!=`.
https://github.com/agh1467/core/blob/f22833c5d1cd804fc9600060ee389ecfce92e269/src/opnsense/mvc/app/models/OPNsense/Base/FieldTypes/TextField.php#L64-L82

Plus this addresses it only in TextField, this evaluation is used throughout most of the FieldTypes.

**Additional context**

I noticed that `$this->internalValue != null` was checked for twice in a row, so I excluded the second check in the above. Also I'd guess that combining the null checks into a single if statement would be functionally equivalent.

I see CSVList Field does this:
```php
if ($this->internalValue != null && $this->internalMask != null) {
```
`!is_null()` also works but I hear that's slower than `===`, probably marginal.

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 22.7.a_431-amd64
FreeBSD 13.0-STABLE
OpenSSL 1.1.1o 3 May 2022

**Comment by AdSchellevis** [comment]
This might need some work to make the options more explicit as history teaches php is getting more strict on every release and this might eventually lead to unforeseen issues, although that's probably not the issue at hand here.

The php manual states `null` and `""` are evaluated  as equal (https://www.php.net/manual/en/types.comparisons.php), a quick check on my end seems to be doing the same:

```
echo null != "" ? "not equal" : "equal";
```

outputs `equal`

The `isEmptyAndRequired()` method on the base class uses a more explicit check it seems:

https://github.com/opnsense/core/blob/1d769e6e6cec6594ca0409c2b8b2d7539b90c558/src/opnsense/mvc/app/models/OPNsense/Base/FieldTypes/BaseField.php#L455

It might be an option to add a method `isEmpty`  to `BaseField` and use this for all instances where we're currently evaluating `internalValue` to make things more explicit. The `internalMask` is set to `null` when not provided by the config, which already should be more or less safe to be honest even if php would tighten validation. 

By the way, it's logical (and intended) that `testEmptyStringWithNonEmptyMask` would trigger, since the `Required` attribute is solely responsible for guarding if an attribute should be provided:

https://github.com/opnsense/core/blob/1d769e6e6cec6594ca0409c2b8b2d7539b90c558/src/opnsense/mvc/app/models/OPNsense/Base/FieldTypes/BaseField.php#L524-L526

(https://docs.opnsense.org/development/frontend/models_fieldtypes.html#creating-models-field-types)

If it wouldn't work like this, every new validation type would reimplement the "required" concept again, which is more or less hoe most other systems and databases implement this by the way.

**Comment by agh1467** [comment]
If I might try to summarize/rephrase to see if I'm following correctly:
* This evaluation is intentional, and working as designed.
* An empty value should only trigger the `BaseField` `isEmptyAndRequired()` validator.
* Only non-empty values should trigger all other validators (includes Regex masks, etc.)

So, seems like not a bug. However, if there is interest in implementing `isEmpty()` in BaseField using the same logic as is used individually in the fields today, I could do that, which would enable for the logic to be easily changed in the future if needed/desired. First, I'd prefer to author tests for, at minimum, the affected fields to validate that the new implementation works as expected.

I noticed that the following fields have no tests:
```
* ArrayField.php
* BaseField.php
* BaseListField.php
* CSVListField.php
* ConfigdActionsField.php
* ContainerField.php
* EmailField.php
* HostnameField.php
* JsonKeyValueStoreField.php
* LegacyLinkField.php
* NetworkField.php
* NumericField.php
* TextField.php
* UniqueIdField.php
* UpdateOnlyTextField.php
* UrlField.php
```
I'd plan to write the tests and do a PR per field, and then once all the tests are there, implement `isEmpty()` which I hope together with the tests would provide a level of confidence that it wouldn't break anything.

---
Below the line is just some musings I was thinking about as I was working through these concepts in my head. I think it would be an interesting approach (if it would even work), but I think it would be functionally equivalent, with some minor advantages which I noted at the end.

---
You mention the option to implement an `isEmpty()` method in `BaseField` which seems like a good idea and would centralize the logic into `BaseField`. Following up with what you're talking about with reimplementing the 'required' concept, that's basically what's happening here with each field reimplementing the the `internalValue != null` concept. So, taking those ideas a step further, I wonder if it would be practical to do something like what is done with `setActionHook()` in ApiMutableModelControllerBase.php. 

Implement a `getValidatorsHook()` which can be overridden by the inheriting fields:
```php
    protected function getValidatorsHook()
    {
    }

    public function getValidators()
    {
        $validators = $this->getConstraintValidators();
        if ($this->isEmptyAndRequired()) {
            $validators[] = new PresenceOf(array('message' => $this->internalValidationMessage));
        } else if (!$this->isEmpty()) {
            $hooks = $this->getValidatorsHook();
            if ($hooks) {
                $validators[] = $hooks;
            }
        }
        return $validators;
    }
```
Where the field's `getValidatorsHook()` would contain just the validator definitions (with per-field applicable conditions):
```php
    public function getValidatorsHook()
    {
            $validators = array();
            $validators[] = new IntegerValidator(array('message' => $this->internalValidationMessage));
            $validators[] = new MinMaxValidator(array('message' => $this->internalValidationMessage,
                "min" => $this->minimum_value,
                "max" => $this->maximum_value
                ));
            return validators;
    }
```

I think this would centralize the evaluation logic which should apply to all fields into the BaseField, and in each inheriting field require less code as there wouldn't be overriding `getValidators()` nor requiring a subsequent call to `parent::getValidators()`, nor the if condition evaluating the internalValue.

I noted that two fields override `getValidators()` but don't evaluate `internalValue != null`, [PortField](https://github.com/opnsense/core/blob/1d769e6e6cec6594ca0409c2b8b2d7539b90c558/src/opnsense/mvc/app/models/OPNsense/Base/FieldTypes/PortField.php#L183-L215), and [NetworkAliasField](https://github.com/opnsense/core/blob/1d769e6e6cec6594ca0409c2b8b2d7539b90c558/src/opnsense/mvc/app/models/OPNsense/Base/FieldTypes/NetworkAliasField.php#L113-L124). This would make the empty evaluation consistent across all of the fields. Though these fields are not building a validators array with their function, but doing other activities, which should still be possible with the hook approach by not having a return, or returning null.

**Comment by AdSchellevis** [comment]
Let's try to answer your questions one by one:

> This evaluation is intentional, and working as designed.

yes it is

> An empty value should only trigger the BaseField `isEmptyAndRequired()` validator.

The presence of validator, yes. Unless there's some dependency involved in which case there could be a specific overwrite or a [constraint](https://docs.opnsense.org/development/frontend/models_constraints.html) in place .

> Only non-empty values should trigger all other validators (includes Regex masks, etc.)

See previous notes, there's no hard rule it shouldn't be possible to overwrite the default behaviour, but I don't think I've ever witnessed a use-case where that made sense. (except perhaps [custom (app specific) field types](https://docs.opnsense.org/development/frontend/models_customfields.html))

> ...However, if there is interest in implementing isEmpty() in BaseField using the same logic as is used individually in the fields today, I could do that, which would enable for the logic to be easily changed in the future if needed/desired...

I'm not against it, also don't have strong feelings about it to be honest. I don't know if `php` ever plans to change their [comparison](https://www.php.net/manual/en/types.comparisons.php) for these cases, in which case strange regressions will occur, realistically if `null != ""`  a lot more will fail. So if we would wrap `isEmpty()` it's merely for people using our codebase but who are less experienced in `php`. 

 > ...I'd plan to write the tests and do a PR per field,...

That would be very welcome, so far we mainly focussed on the most important once, having tests for isolated core functionality is certainly helpful.

>You mention the option to implement an `isEmpty()` method in BaseField which seems like a good idea and would centralize the logic into BaseField....

Easy fix, as explained in my previous point. No strong feelings from my end.


>....Following up with what you're talking about with reimplementing the 'required' concept, that's basically what's happening here with each field reimplementing the the internalValue != null concept. So, taking those ideas a step further, I wonder if it would be practical to do something like what is done with setActionHook() in ApiMutableModelControllerBase.php....

Probably a misunderstanding, how required works (standard OO inheritance) is how it should work in my opinion, just noted that if we wrap `isEmpty()`, the `isEmptyAndRequired()` validator should make use of it as well for clarity.

> ....I noted that two fields override getValidators() but don't evaluate internalValue != null, [PortField](https://github.com/opnsense/core/blob/1d769e6e6cec6594ca0409c2b8b2d7539b90c558/src/opnsense/mvc/app/models/OPNsense/Base/FieldTypes/PortField.php#L183-L215), and [NetworkAliasField](https://github.com/opnsense/core/blob/1d769e6e6cec6594ca0409c2b8b2d7539b90c558/src/opnsense/mvc/app/models/OPNsense/Base/FieldTypes/NetworkAliasField.php#L113-L124)....

It's up to the field type to determine when to slip its own validations, these both derive from [BaseListField](https://github.com/opnsense/core/blob/1d769e6e6cec6594ca0409c2b8b2d7539b90c558/src/opnsense/mvc/app/models/OPNsense/Base/FieldTypes/BaseListField.php#L134) which follows the same pattern but are allowed to slip options of their own.

**Comment by agh1467** [comment]
Thanks for the detailed feedback and explanations. Closing this as it's working as intended. I'll be making some PRs for test coverage as described.
