### ISSUE TITLE
[Bug]Captive Portal, delete but active....

### ISSUE THREAD

**Issue by Chiller2019** [opnsense/core#5854]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

If Captive Portal is active, it is deleted, it is still active instead of being deactivated as usual. (For a VLAN, in my setting)

**To Reproduce**

1. Create a Portal, set it to a VLAN-interface
(2.5. Delete the VLAN from Interface and VLAN-Settings-Page) [idk if this step was before or after]
3. Delete and dont **deactivate** it!

**Expected behavior**

Like everything, when it's deleted, it's also disabled at the same time

**Describe alternatives you considered**

-

**Screenshots**

-

**Relevant log files**

-

**Additional context**

-

**Environment**

OPNsense 22.1.9 (amd64, OpenSSL).
AMD GX-415GA SOC with Radeon(tm) HD Graphics (4 cores, 4 threads)
Network Intel® PRO/1000 PT

**Comment by fichtner** [comment]
@Chiller2019 did you hit apply after delete?

**Comment by Chiller2019** [comment]
> @Chiller2019 did you hit apply after delete?

Sure, the entry was away.

**Comment by Chiller2019** [comment]
> I mean actually pressing the "apply" button below the empty table which takes care of reconfiguration?

Yeahr, ok, I know what you mean. Maybe this was my fault..... stupid... sry for opening ....
