### ISSUE TITLE
Upgrade from 22.1.9 to 22.1.10 fails because module Jinja2 is missing.

### ISSUE THREAD

**Issue by APz** [opnsense/core#5859]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

On upgrade from .9 to .10, error about missing module Jinja2 is displayed. Configd appears to fail on start.

**To Reproduce**

1. Upgrade 22.1.9 system to 22.1.10
2. Observe errors in the console while the upgrade is running

**Expected behavior**

Error free upgrade, no daemon failures.

**Additional context**

Except from the console while running update:

    Stopping configd...done
    Starting configd.
    Traceback (most recent call last):
    File "/usr/local/opnsense/service/configd.py", line 43, in <module>
    import modules.processhandler
    File "/usr/local/opnsense/service/modules/processhandler.py", line 43, in <module>
    from . import ph_inline_actions, syslog_error, syslog_info, syslog_notice, singleton
    File "/usr/local/opnsense/service/modules/ph_inline_actions.py", line 32, in <module>
    from . import template
    File "/usr/local/opnsense/service/modules/template.py", line 43, in <module>
    import jinja2
    ModuleNotFoundError: No module named 'jinja2'
    /usr/local/etc/rc.d/configd: WARNING: failed to start configd
    Reloading plugin configuration
    Configuring system logging...done.
    Reloading template OPNsense/Syslog: configd socket missing (@/var/run/configd.socket)
    Reloading template OPNsense/ddclient: configd socket missing (@/var/run/configd.socket)
    pkg-static: POST-INSTALL script failed
    [44/45] Upgrading opnsense from 22.1.9_1 to 22.1.10...
    [44/45] Extracting opnsense-22.1.10: .......... done
    configd not running? (check /var/run/configd.pid).

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 22.1.10 (amd64, OpenSSL).
Discovered on PC Engines APU4, reproduced in a Xen VM

**Comment by APz** [comment]
A reboot fixed it, this update probably needs to force a reboot after finishing.

**Comment by fichtner** [comment]
Not according to my testing. Things can always happen though.

**Comment by fichtner** [comment]
We've had multiple reports, none of those fatal so I don't think this has to be kept open...
