### ISSUE TITLE
Unbound DNS: DNS override + DHCP Registration causes conflict

### ISSUE THREAD

**Issue by sorano** [opnsense/core#5861]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**DNS override + DHCP Registration causes conflict which breaks the DNS override.**

When you are using DHCP registration in unbound and it registers a lease, then you cannot use the same IP as the lease for DNS override.

**To Reproduce**

1. Go to Unbound DNS - General and enable "DHCP Registration".
2. Renew lease for a device and verify the DHCP hostname gets registered in Unbound.
3. Go to Unbound DNS - Overrides and create a new hostname that resolves to the same IP as the DHCP lease for the device in step 2.
4. Try to resolve the A record for hostname created in step 3. Unbound will reply with NXDOMAIN.
5. Go to Unbound DNS - General and **disable** "DHCP Registration".
6. Try to resolve the A record for hostname created in step 3. Unbound will reply with correct IP.

**Expected behavior**

Unbound should resolve the override independent of DHCP Registration.

**Environment**
OPNsense 22.1.10-amd64
FreeBSD 13.0-STABLE
OpenSSL 1.1.1q 5 Jul 2022

**Comment by AdSchellevis** [comment]
duplicate https://github.com/opnsense/core/issues/5804 ?

**Comment by sorano** [comment]
Correct. My bad.
