### ISSUE TITLE
Squid Proxy leaking IP / Not Routing over OpenVPN 

### ISSUE THREAD

**Issue by sallgit** [opnsense/core#5868]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

Using Squid as Transparent Proxy with ICAP / ClamAV for filtering. Issue is when using OpenVpn Client connection with Squid Proxy, the Public WAN IP is leaked, and not the VPNs Public IP, as Squid use the WAN Connection as outgoing gateway.

The temporary workaround is to add the parameter “tcp_outgoing_address + (VPN Interface IP)” to the squid.conf via Templates File, and create a .sh script with the following content:

``
#!/bin/sh

# Variables
VPN_IFACE=ovpnc1
SQUID_CONFIG_FILE=/usr/local/etc/squid/squid.conf

# Get current IP address of VPN interface
VPN_IFACE_IP=$(ifconfig $VPN_IFACE | awk '{print $2}' | egrep -o '([0-9]+\.){3}[0-9]+')

# Check if VPN interface is up and exit if it isn't
if [ -z "$VPN_IFACE_IP" ]
then
        exit 0;
fi

# Check current IP for VPN interface in squid.conf file
VPN_CONFIG_IP=$(grep -m 1 "tcp_outgoing_address" $SQUID_CONFIG_FILE | awk '{print $2}' | egrep -o '([0-9]+\.){3}[0-9]+')

# Check if the config file matches the current VPN interface IP, and if so exit script
if [ "$VPN_IFACE_IP" == "$VPN_CONFIG_IP" ]
then
        exit 0;
fi

# Replace the previous IP address in the squid.conf file with the current VPN interface address
sed -ie 's/'"$VPN_CONFIG_IP"'/'"$VPN_IFACE_IP"'/' $SQUID_CONFIG_FILE

# Force reload of the new squid.conf file
/usr/local/sbin/squid -k reconfigure
``

After run a Cron Job to execute the created .sh script, if the VPN Ip Interface Address changes, to Update the tcp_outgoing_address in Squid.conf accordingly. 

**Expected behavior**

The above workaround is working, and should be implemented imho to opnsense / squid without the need to add / edit template files / create .sh file / cron job etc..

Or there is a better alternate approach to fix this issue. 

http://www.squid-cache.org/Doc/config/tcp_outgoing_address/

OPNsense 20.1.10 (amd64, OpenSSL).

**Comment by marshalleq** [comment]
Does anyone ever come back and revisit these tickets after the bot has closed them?  I mean I'd be pretty unhappy if I went to all this trouble to log a ticket then have it closed down and never looked at again.  Especially for a security issue like this.

**Comment by fichtner** [comment]
Sure, someone "only" has to open a PR to fix the issue or chime in what a possible (code-wise) fix this would entail.

However, I'm not even sure what you've reported here. Is this a setup question? A defect? A missing feature? I wonder why you say "the Public WAN IP is leaked" when Squid would normally not even bind to a WAN address in question since WAN-setups are only static addresses half of the time (which is are requirement for squid to run on OPNsense). So that would mean it's a routing table issue on your setup more than a squid configuration problem.


Cheers,
Franco
