### ISSUE TITLE
22.7r1: Dashboard breaks with PPPoE interfaces that are down

### ISSUE THREAD

**Issue by g-a-c** [opnsense/core#5870]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

After upgrading to 22.7-RC1, the Dashboard page no longer loads on my OPNsense appliance. The first time you load it, the Dashboard pane is blank, subsequent attempts show the "a problem was detected" message with a link to the Crash Reporter.

Last working on 22.1.10

**To Reproduce**

1. Configure a PPPoE WAN interface, which is enabled but does not come up (I am currently on a temporary Internet connection which is not PPPoE but I have retained the config)
2. Upgrade to 22.7r1
3. Load the Lobby/Dashboard page

**Expected behavior**

Dashboard is correctly displayed, as it was with 22.1.10

**Describe alternatives you considered**

n/a

**Screenshots**

n/a

**Relevant log files**
From the Crash Reporter:
```
[13-Jul-2022 22:16:48 Europe/London] PHP Fatal error:  Uncaught TypeError: Unsupported operand types: string / int in /usr/local/etc/inc/interfaces.inc:4054
Stack trace:
#0 /usr/local/etc/inc/interfaces.inc(3999): convert_seconds_to_hms('')
#1 /usr/local/www/widgets/api/plugins/interfaces.inc(34): get_interfaces_info()
#2 /usr/local/www/widgets/api/get.php(70): interfaces_api()
#3 {main}
  thrown in /usr/local/etc/inc/interfaces.inc on line 4054
```

**Additional context**

It _seems_ like my box is going through this series of events
- Dashboard is loaded
- interfaces.inc is finding the `/var/run/pppoe_wan.pid` file, meaning it hits the code on line 3998-3999
- L3998 executes `/usr/local/opnsense/scripts/interfaces/ppp-uptime.sh`
  - this looks for `/tmp/${1}_uptime` to compare the current system Unix timestamp, and the `mtime` Unix timestamp of that file
  - this file does _not_ exist, _presumably_ because the interface is currently down, so this command returns no output
- L3999 then tries to convert the number of seconds to `hh:mm:ss` format **but** there is no value in seconds because `ppp-uptime.sh` returned no output
- this causes `convert_seconds_to_hms()` to bail

Anecdotally, the [PHP 8 migration notes](https://www.php.net/manual/en/migration80.incompatible.php) give several circumstances where `TypeErrors` may be thrown which would not have been thrown in earlier versions, so this could potentially be a PHP migration issue?

**potential workaround**
I've changed my copy of `/usr/local/opnsense/scripts/interfaces/ppp-uptime.sh` to `echo 0` if the file it's looking for does not exist so that there is always a numeric output to convert, and this has solved the problem for me in a hacky way...

```sh
if [ -f /tmp/${1}_uptime ]; then
        echo $((`date -j +%s` - `/usr/bin/stat -f %m /tmp/${1}_uptime`))
else
        echo 0
fi
```

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 22.7r1 (amd64, OpenSSL).
Intel Atom C2558
Network Intel® I210-AT, I350

**Comment by fichtner** [comment]
@g-a-c thanks, looks like PHP 8 is a bit allergic to this now. Will fix in a bit.

**Comment by fichtner** [comment]
Historically it looks like empty value is expected for defunct connection:

https://github.com/opnsense/core/blob/ddb4af9040d430889c5b365cbce2c7f93eada872/src/opnsense/scripts/interfaces/ppp-linkdown.sh#L48

So I'll not touch ppp-uptime.sh and check its return value for empty instead.

**Comment by fichtner** [comment]
@g-a-c can you try fb892d24 ?

    # opnsense-patch fb892d24

**Comment by g-a-c** [comment]
> @g-a-c can you try [fb892d2](https://github.com/opnsense/core/commit/fb892d24a1ad94cf05e851cb9a0328e20dc08165) ?
> 
> ```
> # opnsense-patch fb892d24
> ```

Yep, I took out my quick hack and replaced it with this successfully (after a quick restart of the web GUI). Thanks for the speedy fix!

**Comment by fichtner** [comment]
@g-a-c terrific, thanks for the quick heads-up. I'll be issuing a small hotfix today for the issues reported since yesterday
