### ISSUE TITLE
DNS Rebind Check breaks spam blocklists

### ISSUE THREAD

**Issue by stoklund** [opnsense/core#5871]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

Email spam filtering often uses real-time blocklists published in DNS. They work like this:

    % host 2.0.0.127.zen.spamhaus.org
    2.0.0.127.zen.spamhaus.org has address 127.0.0.10
    2.0.0.127.zen.spamhaus.org has address 127.0.0.4
    2.0.0.127.zen.spamhaus.org has address 127.0.0.2

These DNS blocklists are described in [RFC5782](https://datatracker.ietf.org/doc/html/rfc5782), and they always return A records with IP addresses in the 127/8 range to indicate membership in the blocklist.

It took me a long time to figure out that OPNsense was silently dropping these A records from replies to my DNS queries because of the DNS Rebind Check feature. 

**To Reproduce**

1. Configure Unbound as a recursive DNS resolver for your network.
2. Enable (un-disable) DNS Rebind Checks under System: Settings: Administration.
3. Run `host 2.0.0.127.zen.spamhaus.org` from a machine on your network.

**Expected behavior**

I expected the host command to return a number of A records with 127/8 addresses for this spam blocklist test entry as shown above.

I got a DNS response with an empty answer section instead. (And spamassassin is badly crippled on my mail server because it can't use these blocklists)

**Describe alternatives you considered**

I was able to work around the problem by disabling DNS Rebind Check and instead adding my own config file to `/usr/local/etc/unbound.opnsense.d/` with just the RFC1918 networks and link-local stuff:

```
private-address: 10.0.0.0/8
private-address: 172.16.0.0/12
private-address: 192.168.0.0/16
private-address: 169.254.0.0/16
private-address: fd00::/8 
private-address: fe80::/10
```

**Additional context**

Please note that the [Unbound documentation]( https://unbound.docs.nlnetlabs.nl/en/latest/manpages/unbound.conf.html#term-private-address-IP-address-or-subnet) advises against adding 127/8 as a `private-address` precisely because it breaks spam blocklists.

There's a couple of changes you could make to improve the situation:

- Don't add 127/8 as a `private-address` as recommended by Unbound. I think the localhost network has a smaller attack surface for DNS Rebind attacks that the RFC1918 networks, and browsers can detect bogus 127/8 A records themselves. (Although I don't know if they do that).
- Alternatively, add an option to allow 127/8 A records when DNS Rebind Check is enabled for people running their own mail servers.
- I suppose I could also add all of my spam blocklist domains to "Private Domains" under Services: Unbound DNS: Blocklist. I am still confused abut this setting: It doesn't seem to have anything to do with the DNSBL lists you can configure in that pane. Should it go next to the "DNS Rebind Check" setting way over in  System: Settings: Administration? Unbound lists `private-address` and `private-domain` next to each other because they are related.

**Environment**

OPNsense 22.1.10-amd64

**Comment by AdSchellevis** [comment]
At a first glance I tend to agree, also for consistency reasons. For DNSmasq we seem to exempt localhost by default
https://github.com/opnsense/core/blob/dedb11793547e270aa65cab8778eda4fc6663ebe/src/etc/inc/plugins.inc.d/dnsmasq.inc#L109

For Unbound we don't 
https://github.com/opnsense/core/blob/ebdf49363e86267588a87f0bfc7a1b963f86ca8b/src/etc/inc/plugins.inc.d/unbound.inc#L156

Let's keep this open for a while to see if there are concerns about changing this behaviour. We might need to double check the rest of the static list as well.

**Comment by fichtner** [comment]
I don't mind removing localhost (IPv4 and IPv6) although it's strange that this went fine since 2016.

**Comment by AdSchellevis** [comment]
https://github.com/opnsense/core/commit/3edd472aaa007a9f080c3f9d863d4c774114f1b5 removes 127/8, but adds the network to the model in case someone wants to add them anyway (against Unbound's advice).
