### ISSUE TITLE
Downloadable ISO Files

### ISSUE THREAD

**Issue by mr2017x** [opnsense/core#5873]
Hi Guys,

thanks for your work, but may someone can explain why you offer only img.bz2 files for download and not simple iso/img files for direct work with (e.g. in proxmox environments)

May you can think about additive simplestupid iso releases. :-)

merci

**Comment by mr2017x** [comment]
> Too much bandwidth, no verification. External (cloud) services will just use it to provide VMs to users which is not good.
> 
> Cheers, Franco

Hi,

so are you and your mirros that poor of bandwith? i mean other tools also distribute as plain iso?

Thanks

**Comment by fichtner** [comment]
first of all bandwidth is not the issue. traffic volume on our main mirror is the issue for an open source project. also the traffic volume given by our mirror provides is not for others to benefit from.

if you want just host your own iso...
