### ISSUE TITLE
Problem in BaseField.php line 632 

### ISSUE THREAD

**Issue by bimbar** [opnsense/core#5874]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [ x ] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [ x ] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

In commit fc8890851a87d3041b820d801e6a386b88ee244b in BaseField.php line 632 was changed from

`if (!isset($this->__items[$dataKey])) {`

to

`if (!isset($this->$dataKey) && !$this->$dataKey->GetInternalIsVirtual()) {` .

Since then, a plugin I wrote errors out with:

`PHP Fatal error:  Uncaught Error: Call to a member function GetInternalIsVirtual() on null in /usr/local/opnsense/mvc/app/models/OPNsense/Base/FieldTypes/BaseField.php:632`

My plugin calls `$field->setNodes($data);` .

It seems to me that if `!isset($this->$dataKey)` is true, and so is not set, it will never be possible to call `->GetInternalIsVirtual()` on it.

**Expected behavior**

The data is loaded without error.

**Environment**

OPNsense 22.1.10-amd64
FreeBSD 13.0-STABLE
OpenSSL 1.1.1q  5 Jul 2022

and

OPNsense 22.4.2-amd64
FreeBSD 13.0-STABLE
OpenSSL 1.1.1q 5 Jul 2022

This error popped up with the update to 22.4.2.

**Comment by fichtner** [comment]
Looks like a typo?

```
% git grep GetInternalIsVirtual
src/opnsense/mvc/app/models/OPNsense/Base/FieldTypes/BaseField.php:                    if (isset($parentNode->$tagName) && !$parentNode->$tagName->GetInternalIsVirtual()) {
src/opnsense/mvc/app/models/OPNsense/Base/FieldTypes/BaseField.php:                if (!isset($this->$dataKey) && !$this->$dataKey->GetInternalIsVirtual()) {
```

```
% git grep -i GetInternalIsVirtual
src/opnsense/mvc/app/models/OPNsense/Base/FieldTypes/ArrayField.php:            if ($this->internalChildnodes[$firstKey]->getInternalIsVirtual()) {
src/opnsense/mvc/app/models/OPNsense/Base/FieldTypes/BaseField.php:                    if (isset($parentNode->$tagName) && !$parentNode->$tagName->GetInternalIsVirtual()) {
src/opnsense/mvc/app/models/OPNsense/Base/FieldTypes/BaseField.php:    public function getInternalIsVirtual()
src/opnsense/mvc/app/models/OPNsense/Base/FieldTypes/BaseField.php:                if (!isset($this->$dataKey) && !$this->$dataKey->GetInternalIsVirtual()) {
src/opnsense/mvc/app/models/OPNsense/Base/FieldTypes/BaseField.php:            if ($FieldNode->getInternalIsVirtual()) {
src/opnsense/mvc/app/models/OPNsense/Firewall/FieldTypes/AliasField.php:            if (!$node->getInternalIsVirtual()) {
```

**Comment by fichtner** [comment]
CC @swhite2

**Comment by bimbar** [comment]
I think it should be `if (!isset($this->$dataKey)) {`

**Comment by fichtner** [comment]
I don't know, fixing function name would be the obvious thing.

**Comment by AdSchellevis** [comment]
@bimbar can  you try https://github.com/opnsense/core/commit/9cc07ed4ac2efd4c8e04081fba2b98f513888cdd? It looks there are two small issues with the commit (function name and null dereference) if I'm not mistaken.

**Comment by bimbar** [comment]
@AdSchellevis I manually changed BaseField.php to what you referenced and it works.

**Comment by fichtner** [comment]
Thanks, we plan to add this to both 22.1.10 and 22.4.2, but it will take a while with 22.7 release preparations going on.


Cheers,
Franco
