### ISSUE TITLE
DNS lookup triggers local configuration backup

### ISSUE THREAD

**Issue by maurice-w** [opnsense/core#5881]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**
Performing a DNS lookup with the built-in diagnostics tool creates a local backup of the OPNsense configuration.

This didn't happen with the previous DNS lookup tool.

**To Reproduce**

1. Go to 'Interfaces: Diagnostics: DNS Lookup'
2. Enter a hostname and click on 'Apply'
3. Go to 'System: Configuration: History'
4. See error: A configuration backup was created ("/api/diagnostics/dns_diagnostics/set made changes")

**Expected behavior**

A DNS lookup should not trigger a configuration backup.

**Environment**

OPNsense 22.7.r1_8 (amd64, OpenSSL)

**Comment by fichtner** [comment]
Nice catch, related to #5843 as the new "memory" model defies the current config expectations. Handing it over to @AdSchellevis

**Comment by AdSchellevis** [comment]
fixed in https://github.com/opnsense/core/commit/40a64dc9f535254057d1c25778a7c6054f959b2e, @maurice-w thanks for reporting!
