### ISSUE TITLE
No host route for GIF remote address if gateway is IPv6 link-local

### ISSUE THREAD

**Issue by maurice-w** [opnsense/core#5884]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

When setting up a GIF tunnel, a host route for the remote address is supposed to be created (using the gateway of the selected parent interface):
https://github.com/opnsense/core/blob/40a64dc9f535254057d1c25778a7c6054f959b2e/src/etc/inc/interfaces.inc#L667
This works if the gateway has an IPv4 address or IPv6 GUA / ULA. But the route doesn't get created if the gateway address is IPv6 link-local (as is common for IPv6 gateways).

The root cause is probably here, where nothing seems to be returned if the gateway is IPv6 link-local:
https://github.com/opnsense/core/blob/40a64dc9f535254057d1c25778a7c6054f959b2e/src/etc/inc/interfaces.inc#L642

I don't know since when this issue exists, didn't have such a setup before.

**To Reproduce**

1. Go to 'Interfaces: Other Types: GIF' and add a new tunnel. 'Parent interface' must have a link-local IPv6 gateway, 'GIF remote address' must be IPv6.
2. Go to 'Interfaces: Assignments' and assign the new tunnel interface.
3. Go to 'System: Routes: Status'.
4. See error: No host route for GIF remote address.

**Expected behavior**

A host route for the GIF remote address should be created.

**Environment**

OPNsense 22.7.r1_8 (amd64, OpenSSL)

**Comment by fichtner** [comment]
@maurice-w for now I'm not sure what's wrong. I have a similar setup but I get a link local gateway and the route command fails:

    /interfaces_gif_edit.php: The command '/sbin/route add -host -'inet6' 'GUA' 'LL'' returned exit code '1', the output was 'route: writing to routing socket: Network is unreachable add host GUA: gateway LL fib 0: Network is unreachable'

Which might be true... do we have to force host routes to interface here because of LL/GUA mismatch?

**Comment by maurice-w** [comment]
It works when I add the route manually like this:
`route add -host -inet6 2001:db8::1 fe80::1%hn0`
Specifying the interface (%hn0) is indeed mandatory for link-local gateways.

**Comment by fichtner** [comment]
ok, thanks for the hint. will fix :)

**Comment by fichtner** [comment]
let me know if this works for you 575c8a5233d5867ca7, but it does look good here

**Comment by maurice-w** [comment]
This works indeed. Thanks for the quick fix!
