### ISSUE TITLE
Squid in SSL-Inspection Mode doesn't  display several Sites, there are CA- or Certificate Errors

### ISSUE THREAD

**Issue by egi815** [opnsense/core#5888]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [ x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [ x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

Squid in SSL-Inspection Mode doesn't  display several Sites, because there are issues with the CAs or Certificates.

No matter what i Enter into SSL no bump sites, the Sites will not show up:

eni-card2view.eni.as8677.net
www.ic-myron.com
fe3cr.delivery.mp.microsoft.com
fe2.update.microsoft.com

I have several such domains, some of them from godaddyCA

I build in an workaround:
acl no_ssl_interception ssl::server_name "/usr/local/etc/squid/no_ssl_interception.acl"
ssl_bump splice no_ssl_interception

    # configure bump
ssl_bump peek bump_step1 all
ssl_bump peek bump_step2 bump_nobumpsites
ssl_bump splice bump_step3 bump_nobumpsites
ssl_bump stare bump_step2
ssl_bump bump bump_step3

 but everytime i click on Apply in web-Proxy, My Workaround is gone again..

The Problem is now,
you cannot use SSL Inspection, if it is immpossible to reach site, which are needed by the Users.

So Maybe you could add another Textfield like "no bump sites"
for the  "SNI information only" Sites, 
Then Microsoft Update will also work again...

Describe alternatives you considered
Please invite an other list like 

acl no_ssl_interception ssl::server_name "/usr/local/etc/squid/no_ssl_interception.acl"
ssl_bump splice no_ssl_interception

above the 
    # configure bump
ssl_bump peek bump_step1 all
rules....

Software version used and hardware type if relevant, e.g.:

OPNsense 22.1.10 (amd64, OpenSSL).
AMD EPYC 3251

**Comment by egi815** [comment]
Hmm no answer at all?
is there nobody who uses web-proxy and windows?
It is not possible to get windows Updates when using web proxy  with ssl-inspection.

and why  does it have an support label? web-proxy is no community plugin.

**Comment by kulikov-a** [comment]
It would be nice if squid errors were given
imho looks like "squid4 vs TLS1.3 site not providing an intermediate certificate" issue
can you try with
`opnsense-patch -a kulikov-a a3420ac`
and adding domain to Forward Proxy - Access Control List -Allow broken server certificate?
(uses `sslproxy_cert_error` and `sslproxy_cert_sign` options)
