### ISSUE TITLE
system: remove last bits of clog (circular logging) support

### ISSUE THREAD

**Issue by fichtner** [opnsense/core#5892]
**Important notices**

Our forum is located at https://forum.opnsense.org , please consider joining discussions there in stead of using GitHub for these matters.

Before you ask a new question, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

Triggered by a spellcheck 22.7 receives the following patch to remove reading legacy logs for the log viewer UI: 48e5f9f2ab8e51

We still have a few leftovers from clog, mostly for parsing the format in Python that can be removed now.

**Comment by AdSchellevis** [comment]
@fichtner can go now indeed, removed in https://github.com/opnsense/core/commit/868c9531cdc95a0d4ceef1f7f8306df194f03d6f

**Comment by fichtner** [comment]
FreeRADIUS and possibly others "mock" clog files as file output logging causing logs to appear as empty on 22.7. This should be fixed in the plugins but maybe we should revert and retarget 23.1.

**Comment by AdSchellevis** [comment]
just log files like `/var/log/myservice.log`? as long as their not in clog format, we could keep support for those easily

**Comment by fichtner** [comment]
@AdSchellevis my only worry would be reading clog files as text files if we remove the clog reading

**Comment by AdSchellevis** [comment]
true, although likely not a huge issue. it's worth a shot I guess and see what happens,  clog files will likely be sorted at the end of the results anyway and mangled data will go out of visible range soon.

**Comment by fichtner** [comment]
that means revert 48e5f9f2ab as shown in forum thread and be done with it?

**Comment by AdSchellevis** [comment]
yep, that looks like it indeed, rather harmless, also in the long run if needed.

**Comment by fichtner** [comment]
super, thanks for the help ❤️
