### ISSUE TITLE
LDAP group style options are too limited / missing RFC 2307 support

### ISSUE THREAD

**Issue by ichihaifu** [opnsense/core#5899]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**

Configuring authentication server is missing LDAP group configuration settings.
I want use RFC 2307 based schema where memberOf is not the default group membership identifier.

**Describe the solution you like**

pfSense has integrated these options quite well in their interface.

**Describe alternatives you considered**

I could implement RFC 2307bis format but since [memberOf is being deprecated](https://github.com/openldap/openldap/blob/master/doc/man/man5/slapo-memberof.5) in future OpenLDAP versions, and the instructions to configure similar functionality using dynlist is yet very limited, Opnsense should provide support for the default OpenLDAP formats.

**Additional context**

pfSense configuration options
![image](https://user-images.githubusercontent.com/58817020/180618383-2250b75e-db4f-4927-b25c-e7ad217a6ba7.png)

**Comment by AdSchellevis** [comment]
Might be worth checking if changing OpenLDAP's configuration isn't the easier approach here, I don't think they deprecated rfc2307bis, but merely seem to change to a different implementation for it https://github.com/ltb-project/slapd-cli/issues/42 (`slapo-memberof` vs `slapo-dynlist`).

**Comment by Cosmicfour4** [comment]
I have recently also encountered this issue. I am using JumpCloud services and they use RFC 2307 in there LDAP implementation. I have seen other forum posts about support for RFC 2307. 

https://jumpcloud.com/support/configure-pfsense-vpn-to-use-cloud-ldap
