### ISSUE TITLE
Create User -> Create Certificate missing 'Digest Algorithm' options

### ISSUE THREAD

**Issue by sjorge** [opnsense/core#59]
http://i.imgur.com/IQJtgI1.png

Also option to add a few alt names would be nice.

**Comment by sjorge** [comment]
Creating a client certificate for a user (email as CN) using cert manager
http://i.imgur.com/5hRXnFq.png
Creating a user with selecting the option to create a certificate
http://i.imgur.com/QlKyCIC.png

As you can see 'Digest Algorithm' option is missing. (I'm also not sure if the certificates are generated properly with the 'Client Authentication' DN, but that's something to check out at a later time. I'll file a new report if that is not the case.

**Comment by AdSchellevis** [comment]
I have just re-factored all the cert manager pages, I'm going to solve the inconsistency issue by redirecting to the cert manager from the user manager instead of duplicating code there....
