### ISSUE TITLE
IPsec: Tunnel Settings - Phase 2 list all hides last entry

### ISSUE THREAD

**Issue by selbitschka** [opnsense/core#5903]
Hi,
I just discovered that if you set the length option to "All" in Phase 2 table of IPSec settings the it jumps to "-1". This results in a list where the last entry of the list is not displayed. If you switch back to "100" or something large enough to see all rules the last line is shown correctly.

This behavior shows using version 22.1.10

I didn't checked other list if this is a system wide problem or only related to IPSec settings.

regards
stefan

**Comment by fichtner** [comment]
could be https://github.com/opnsense/core/commit/59b076ba4ef21
