### ISSUE TITLE
stray error_reporting(E_ALL) calls

### ISSUE THREAD

**Issue by fichtner** [opnsense/core#5904]
**Important notices**

Our forum is located at https://forum.opnsense.org , please consider joining discussions there in stead of using GitHub for these matters.

Before you ask a new question, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

We do have 4 spots overriding the error level which can emit spurious things on production deployments triggered by more aggressive stance of PHP 8.

```
% git grep error_reporting\(E_ALL
src/opnsense/mvc/script/run_migrations.php:error_reporting(E_ALL);
src/opnsense/mvc/tests/setup.php:error_reporting(E_ALL);
src/opnsense/www/api.php:error_reporting(E_ALL);
src/opnsense/www/index.php:error_reporting(E_ALL);
```

Now that we have a development mode we could get rid of those most likely. Test run can be the exception here, but also a bit counter-intuitive.

Also see https://github.com/opnsense/plugins/pull/3043

**Comment by swhite2** [comment]
@fichtner Thank for the heads up :)
