### ISSUE TITLE
unbound: exception handling in watcher et al

### ISSUE THREAD

**Issue by fichtner** [opnsense/core#5905]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

There seems to be a race condition when starting unbound in a separate script in the background and then starting the DHCP watcher right away causing 31f3e82c6bb64e0

The actual trace is:

```
[1658262867] unbound-control[79947:0] fatal error: timeout: could not connect to server
Traceback (most recent call last):
  File "/usr/local/opnsense/scripts/dns/./unbound_dhcpd.py", line 222, in <module>
    run_watcher(
  File "/usr/local/opnsense/scripts/dns/./unbound_dhcpd.py", line 198, in run_watcher
    unbound_control(['local_datas_remove'], input=remove_rr)
  File "/usr/local/opnsense/scripts/dns/./unbound_dhcpd.py", line 57, in unbound_control
    subprocess.run(['/usr/sbin/chroot', '-u', 'unbound', '-g', 'unbound', '/',
  File "/usr/local/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/usr/sbin/chroot', '-u', 'unbound', '-g', 'unbound', '/', '/usr/local/sbin/unbound-control', '-c', '/var/unbound/unbound.conf', 'local_datas_remove']' returned non-zero exit status 1.
```

via https://www.reddit.com/r/opnsense/comments/w3h0v4/opnsense_dhcp_unbound_no_lease_registration/

**To Reproduce**

Restart unbound, see timeout with blocklist use for example.

**Expected behavior**

Gradual start of services, no timeouts on unbound-control. Possibly better error handling in DHCP watcher.

**Comment by swhite2** [comment]
Addressed in https://github.com/opnsense/core/commit/966e54011e29bf3c6a8a7bccc5afa11be7fc4ddb
