### ISSUE TITLE
IPv6 outbound NAT rule not created if source address is set to 'LAN net'

### ISSUE THREAD

**Issue by maurice-w** [opnsense/core#5907]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

When adding an IPv6 Outbound NAT rule and setting the source address to 'LAN net', no pf rule seems to get created.

This is a new issue in 22.7, it did work up to 22.1.10.

**To Reproduce**

1. Go to 'Interfaces: [LAN]', set 'IPv6 Configuration Type' to 'Static IPv6', enter IPv6 address 2001:db8::1/64, save & apply.
2. Go to 'Firewall: NAT: Outbound', set mode to manual, add a rule (TCP/IP Version 'IPv6', Source address 'LAN net', everything else default), save & apply.
3. Go to 'Firewall: Diagnostics: Statistics / rules / nat rules', see error: No NAT rule was created.
4. Go back to 'Firewall: NAT: Outbound', edit the previously created rule, set Source address to 'Single host or Network', enter 2001:db8::/64, save & apply.
5. Go back to 'Firewall: Diagnostics: Statistics / rules / nat rules'. NAT rule now exists.

**Expected behavior**

'LAN net' should get picked up correctly for outbound NAT rule creation.

**Describe alternatives you considered**

Enter source network manually as outlined above.

**Environment**

OPNsense 22.7.r1 / 22.7.r2 / 22.7 (amd64, OpenSSL)

**Comment by fichtner** [comment]
Hopefully this isn't a side effect of c7e67c6752ec79a. Tagging "support" for now until confirmed or pinned to a problem because I'm not sure. Kernel side change also is unlikely.


Cheers,
Franco

**Comment by fichtner** [comment]
It has been confirmed here:

https://forum.opnsense.org/index.php?topic=29517.0

`Error	firewall	There were error(s) loading the rules: /tmp/rules.debug:116: syntax error - The line in question reads [116]: nat log on ovpnc1 inet6 from (igb0:network),fe80::/10 to $vpn_XXX_targets -> (ovpnc1:0) port 1024:65535 # LAN to XXX IPv6 NAT`
