### ISSUE TITLE
get_interfaces_info() broken in various places

### ISSUE THREAD

**Issue by timota** [opnsense/core#5910]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

This issue similar to issue resolved in this ticket https://github.com/opnsense/core/issues/5870 but proposed solution doesnt work either.

After upgrading to 22.7, the Dashboard page no longer loads. The first time you load it, the Dashboard page is blank, subsequent attempts show the "a problem was detected" message with a link to the Crash Reporter. 
Also, when trying to check interfaces (Interfaces->Overview) got an error.

**To Reproduce**

1. Configure a PPPoE WAN interface
2. Upgrade to 22.7
3. Load the Lobby/Dashboard page OR
4. Interfaces -> Overview
5. See error

**Expected behavior**

Dashboard working. Interfaces tab working

**Describe alternatives you considered**

n/a

**Screenshots**

n/a

**Relevant log files**
Logs. from Crash report
```
[29-Jul-2022 00:11:48 Europe/London] PHP Fatal error:  Uncaught TypeError: Unsupported operand types: int + string in /usr/local/etc/inc/interfaces.inc:4196
Stack trace:
#0 /usr/local/etc/inc/interfaces.inc(3998): get_ppp_uptime('ppp0')
#1 /usr/local/www/widgets/widgets/interface_list.widget.php(117): get_interfaces_info()
#2 /usr/local/www/index.php(421): include('/usr/local/www/...')
#3 {main}
  thrown in /usr/local/etc/inc/interfaces.inc on line 4196
```

Logs from `Interfaces->Overview`
```
Fatal error: Uncaught TypeError: Unsupported operand types: int + string in /usr/local/etc/inc/interfaces.inc:4194 Stack trace: #0 /usr/local/etc/inc/interfaces.inc(3998): get_ppp_uptime('ppp0') #1 /usr/local/www/status_interfaces.php(77): get_interfaces_info(true) #2 {main} thrown in /usr/local/etc/inc/interfaces.inc on line 4194
```

**Additional context**

Similar to ticket  https://github.com/opnsense/core/issues/5870, but interfaces already loaded. 

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 2.7 (amd64, OpenSSL).

**Comment by AdSchellevis** [comment]
can you post the contents of `/conf/ppp0.log`?

**Comment by kalpik** [comment]
For me, it's a bit different. I can open the dashboard and interface overview screens, but I do not get any uptime information for the PPPoE interface. The entire uptime row is missing.

Discussed over Twitter here: https://twitter.com/kalpik/status/1552699964437970951

**Comment by fichtner** [comment]
@kalpik working on it now as promised :)

**Comment by fichtner** [comment]
This could be it for both issues reported here: 86ebdc291e8

# opnsense-patch 86ebdc291e8

**Comment by kalpik** [comment]
@fichtner yep! Uptime is back for me, and both Dashboard and Interface Overview pages open fine :)

Thanks for the super fast fix! Appreciate it :)

**Comment by fichtner** [comment]
@kalpik no problem, always happy about quick and precise reports

**Comment by timota** [comment]
@fichtner your patch does help. All back again. Many thanks

for any case `ppp0.log` below

```
cat /conf/ppp0.log
2021.06.08-10:02:31 978982
2021.06.08-11:47:45 -915
2021.06.13-16:17:59 448134
2021.06.29-22:50:44 1328512
2021.07.04-06:59:23 46342
2021.07.22-19:26:36 -2953
2021.07.30-23:03:47 704148
2021.08.05-22:49:56 -1668
2021.09.20-01:21:03 3896954
2021.09.26-18:01:59 -3121
2021.10.01-13:08:34 414315
2021.10.01-13:31:11 -3191
2021.10.11-10:40:07 853652
2021.11.12-00:07:03 2726731
2021.11.12-02:14:05 7265
2021.12.02-02:23:54 1355857
2021.12.07-12:25:19 468067
2021.12.07-12:26:36 70
2022.01.29-21:22:26 1237
2022.01.29-21:39:01 898
```

**Comment by fichtner** [comment]
> 2021.06.08-11:47:45 -915

WTF? :D

**Comment by timota** [comment]
have no idea. even if those numbers indicates latency, they doesn't make any sense.

**Comment by fichtner** [comment]
@timota looking at this with a fresh eye it looks like this happened in 2021, but not in 2022. Unfortunately 2022 stops due to a typo which has now been corrected with said patch and I'll close this in the hopes the negative values will not appear. Maybe you can check again if that is true for you now and let me know if it still happens and we could take a closer look. :)


Cheers,
Franco
