### ISSUE TITLE
Aliases URL Tables (IPs) does not work correctly

### ISSUE THREAD

**Issue by Anywake** [opnsense/core#5918]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [+] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [+] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

I have an alias URL Tables (IPs) - mail gmail

![image](https://user-images.githubusercontent.com/109514623/182304114-b7abfb3f-d86d-45f9-bdfa-b1c7426f8cfb.png)

Firewall>Diagnostics:

![image](https://user-images.githubusercontent.com/109514623/182304350-96a43352-afbb-418f-9224-b0bf184df702.png)

my PC

![image](https://user-images.githubusercontent.com/109514623/182304423-963bb4ac-42c4-424d-8bd4-c190f362801d.png)

URL Tables (IPs) does not contain real addresses 108.177.14.108 and 108.177.14.109.

Software version used and hardware type if relevant, e.g.:

OPNsense 22.7_4-amd64
FreeBSD 13.1-RELEASE
OpenSSL 1.1.1q 5 Jul 2022

**Comment by kulikov-a** [comment]
https://serverfault.com/questions/1008483/how-does-google-return-a-different-a-record-every-time

**Comment by Anywake** [comment]
OPNsense lookup IP *.gmail.com on other DNS? DNS server for computer is OPNsense (gateway). OPNsense use a different DNS? о_О   should return the same ip for computer and OPNsense

PC (mail client)  __ DNS request imap.gmail.com  __ -> from gateway opnsense -> gateway opnsense __ DNS request from 8.8.8.8___ ->  8.8.8.8 answer "imap.gmail.com -108.177.14.109

**Comment by kulikov-a** [comment]
For geo/load balancing google dns records have short TTLs and authoritative servers mixing returning addresses so any host that tries to resolve *.Gmail.com may receive different answer on each try. IMHO it's not the best idea to try to use google dns records to filter google mail traffic. I would try to use ports and "google subnets" alias (see link in first answer)
