### ISSUE TITLE
DNSSL set in radvd.conf although sending DNS is disabled in UI

### ISSUE THREAD

**Issue by pmhausen** [opnsense/core#5919]
- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

Even when sending DNS info via RA is explicitly disabled, radvd is configured with DNSSL. This leads to (at least) TrueNAS 13 dropping its static DNS configuration after each reboot.

**To Reproduce**

1. Manually configure router advertisements on LAN like in screenshot.
2. Check /var/etc/radvd.conf

```
interface igb0 {
	AdvSendAdvert on;
	MinRtrAdvInterval 200;
	MaxRtrAdvInterval 600;
	AdvLinkMTU 1500;
	AdvDefaultPreference medium;
	prefix 2003:a:827:2a00::/64 {
		DeprecatePrefix on;
		AdvOnLink on;
		AdvAutonomous on;
	};
	DNSSL punkt.de {
	};
```

**Expected behavior**

The DNSSL section should not be there.

**Screenshots**
![Bildschirmfoto 2022-08-02 um 09 19 01](https://user-images.githubusercontent.com/27051716/182316595-a5a0b52c-1ab2-4e47-a164-830292bbf17c.png)

**Environment**

OPNsense 22.1.10

**Comment by pmhausen** [comment]
This is what lead to this issue:

https://ixsystems.atlassian.net/browse/NAS-117458

**Comment by pmhausen** [comment]
Thanks for the quick reply. Does the milestone setting imply this is not going into 22.7.x as a bug fix?

**Comment by fichtner** [comment]
Means we can't retrofit 22.7 release but 22.7.x is a possibility :)

**Comment by maurice-w** [comment]
The current behaviour of 'Do not send DNS settings to clients' is consistent with the 'Use the DNS settings of the DHCPv6 server' feature. This only grabs the DNS servers from the DHCPv6 config, not the search list. The placement of these settings in the UI also implies this, although the wording doesn't.

I agree with extending 'Do not send DNS settings to clients' to also apply to DNSSL. But for consistency, 'Use the DNS settings of the DHCPv6 server' should then be modified accordingly. And a UI layout change might be required to reflect the new behaviour (both settings applying to RDNSS and DNSSL).

**Comment by fichtner** [comment]
Let's keep this open for now. Some opportunity to refactor as well. :)

**Comment by pmhausen** [comment]
@maurice-w Like this?

**Comment by fichtner** [comment]
@pmhausen I have a patch ready in a second

**Comment by fichtner** [comment]
@pmhausen b504bc8 should behave the same as your addition and also pull search list from DHCPv6 if the other setting is defined as spotted by @maurice-w

**Comment by pmhausen** [comment]
Whatever :) Thanks again for the quick response. That was really bothersome here in production. Looking forward to 22.7.1.

**Comment by fichtner** [comment]
@pmhausen let's add your patch for 22.7.1 and throw in the refactor/GUI stuff later. it feels a bit like (the good kind of) bike shedding

**Comment by pmhausen** [comment]
Bug is fixed. Let's open a new issue if necessary for the UI changes. Pull-request alone should suffice, though.

**Comment by fichtner** [comment]
Follow up is https://github.com/opnsense/core/commit/68894e989dc890954746507fe85cd4f5c087d94a

Can probably go into 22.7.2 as a batch change.
