### ISSUE TITLE
Logs lost on update to OPNsense 22.7 - Settings default to /var/log RAM disk enabled

### ISSUE THREAD

**Issue by AlexAndrascu** [opnsense/core#5924]
I was recently upgrading the system to OPNsense 22.7 and noticed that all the logs stored in /var/logs are gone. 
Upon investigation and some searching around I have found that  

`/var/log RAM disk | Use memory file system for /var/log` was enabled (by default) under `System -> Settings -> Miscellaneous`

I was wondering if this is an oversight or intentional and what would be the workaround to prevent this from happening on the next upgrade. To clarify this hasn't happened in the past with any other minor or major upgrades and I haven't enabled the memory file system.

**Comment by fichtner** [comment]
This is enabled if you had previously had /var MFS enabled on a version prior to 22.7. Same thing really, except that /var scope was a bit wider.


Cheers,
Franco

**Comment by AlexAndrascu** [comment]
Hi @fichtner and thanks for replying,

As I have said I don't remember turning this and also had done multiple minor and major upgrades to the system without this ever happening. So I guess it wouldn't be the same thing, more of a breaking change if anything?

**Comment by fichtner** [comment]
As you can see from https://github.com/opnsense/core/commit/dc33b3ab4e5 we don't change the read/write of config.xml values so I can only conclude it was indeed enabled manually at some point except this was a Nano image where the option is set by default.

**Comment by AlexAndrascu** [comment]
I was actually looking at that after I posted on the /src repo ( thanks for moving it here where it belongs) but I still need to read a bit more to get the gist. Perhaps it was enabled for /tmp only but definitely not for the /logs folder. Would that have the same results?

**Comment by fichtner** [comment]
No, /tmp and /var MFS have always been separate. Now there is /tmp and /var/log MFS but both operate on the same enable/disable as before. There were no similar reports in the past of this not working (if you don't count the many issue people have had with wanting /var contents to be persistent while also having /var MFS enabled). ;)

**Comment by AlexAndrascu** [comment]
I didn't had this problem in the past either, it's the first time I'm seeing it too :)

**Comment by fichtner** [comment]
Is there any specific log that you have in mind here. The subtlety of this is that prior to 22.7 some plugins had persistent log storage in the volatile location (as little sense as that makes).

**Comment by AlexAndrascu** [comment]
Yes, Mailtrail logs missing gave me the shivers before I found out what's happening

**Comment by fichtner** [comment]
Long story short I think you either want to disable /var/log MFS or send your logs to an external syslog server for storage.


Cheers,
Franco

**Comment by AlexAndrascu** [comment]
Yup, I did disable it as soon as I've found the little bugger, questions is, will it come back in the future or act normally as it should? 

External syslog is indeed a better approach but I kept delaying it indefinitely as this was working fine for my needs.

**Comment by fichtner** [comment]
It worked normally before, it will work normally now. The collateral damage here were 3 plugins trying to store persistent logs which was not originally intended (mailtrail, netdata and munin-node). No other components are affected.

**Comment by AlexAndrascu** [comment]
Understood. Shall I close this now, or maybe leave it for further reference?

**Comment by fichtner** [comment]
Can be closed if you agree. We do not embed extended plugin changes into our release notes and it was documented as:

https://github.com/opnsense/changelog/blob/a86d40e492aa892514d65e2640dbfc91cc9a11bc/community/22.7/22.7#L148

Maybe the working could have been a bit more explicit that we brutally enforce this now on 22.7 but the scope seemed too small for said 3 plugins alone.
