### ISSUE TITLE
[22.7] WebGUI broken after upgrade

### ISSUE THREAD

**Issue by mmaridev** [opnsense/core#5926]
Hi,

after upgrading to OPNSense 22.7 the WebGUI is broken meaning that I have nothing in the Dashboard and the menu won't show up.
In the console I get

```
Uncaught TypeError: $(...).tooltip is not a function
    <anonymous> https://10.190.30.254/index.php:96
    jQuery 13
[index.php:96:36](https://10.190.30.254/index.php)
    <anonima> https://10.190.30.254/index.php:96
```

**Comment by mmaridev** [comment]
Can confirm is related to the Italian translation, refs https://forum.opnsense.org/index.php?topic=29575.0

**Comment by spikeygg** [comment]
I just had this issue and found this ticket. The UI was completely unusable, the only page I could see was the license. Nothing else would load. I logged in remotely via ssh to try to issue an update and it also failed, I then restarted the system through the ssh connection and after the reboot everything came back to life. I'm on 22.7.6-amd64.

**Comment by merlink01** [comment]
Had this Error in 24.1.6, it was caused by the old dyndns plugin, that broke my ui.
A trick to get the ui working again was to go from the crashed dashboard to the license page.

After this i could use the Menu again and remove the plugin.
