### ISSUE TITLE
Nextcloud backup is executed twice every night

### ISSUE THREAD

**Issue by mzurhorst** [opnsense/core#5931]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**
First observed in 22.1, but issue is also available in the recently released version 22.7.

I have specified a cronjob at:   1:30am to backup my Opnsense to a Nextcloud account.
When I now look at Nextcloud, I see that all backups are executed twice:   at 1:00am, and also at 1:30am.

**To Reproduce**

1. Go to 'System --> Configuration --> Backups'
2. Scroll down to 'Nextcloud' section
3. Configure connection to Nextcloud instance (username, password, URL, ...).
4. Click 'Setup/Test Nextcloud'Go to 'System --> Settings --> Cron'
5. Click on '+' to add a new cron job
6. Scroll down to 'Command' and select 'Remote backup' from the LOV
7. Save.
8. Login to Nextcloud URL and observe backups created.

**Expected behavior**

Only a single backup exactly at the time where the cron job is specified in the GUI.

**Describe alternatives you considered**

Nothing

**Screenshots**

Screenshot 1:   Cron settings
![grafik](https://user-images.githubusercontent.com/575190/182893668-dfd0eabf-1780-4238-9797-3c013b646247.png)

Screenshot 2:   backup file results on Nextcloud
![grafik](https://user-images.githubusercontent.com/575190/182894140-d18827fa-980d-4250-9612-cb36e070a340.png)

Topic also raised in the forum, but no response so far:
https://forum.opnsense.org/index.php?topic=29621.0

**Relevant log files**

If applicable, information from log files supporting your claim.

**Additional context**

**Environment**

Software version used and hardware type if relevant, e.g.:

Virtualized OPNsense 22.7 (amd64, OpenSSL) in a KVM machine on Proxmox 7.2.7
Intel® Core i7-4900u,  8GB RAM

**Comment by fichtner** [comment]
There is an automatic nightly cron job as documented. If you need more cron jobs that is what the manual one is for. I don't think running two closely together and then adding a ticket brings much to the table?


Cheers,
Franco

**Comment by mzurhorst** [comment]
Hi Franco,
can you please point me to the documentation? -- Neither in the "Cloud Backup" section do I read something about 1:00am, nor in the "Cronjob" section of the documentation.

Apologies for raising this.  This was non-obvious to me.

What I now understand:   I will remove the Cronjob at 1:30am, and I will then magically get only a single cloud backup per day, at 1:00am.   

Thank you.

**Comment by mzurhorst** [comment]
![grafik](https://user-images.githubusercontent.com/575190/182904296-fd99f77b-1586-431b-884e-7d99e1b59f43.png)
Maybe such a hint should be added in the description of the plugin: "do not create a cronjob; OPNsense will take care for this already."

**Comment by fichtner** [comment]
It's in the git-backup documentation it mentions "nightly" keeping the the of the cron job adjustable. https://docs.opnsense.org/manual/git-backup.html?highlight=nightly

In the NextCloud/Google documentation it's mentioned "per day". https://docs.opnsense.org/manual/how-tos/cloud_backup.html?highlight=day

I don't mind improving those but documentation is often there when people say they can't find it. ;)

**Comment by mzurhorst** [comment]
Thanks, Franco.

To which extend is now the git-backup applicable for my reporting? -- I do not even have this installed.

So, I am gonna close this as issue since it is all working as designed, despite being hard-coded to 1:00am at the moment.

Another suggestion how to improve this:   display the hard-coded cronjobs in the cronjobs view, maybe greyed-out, such that users cannot modify those.  

Thanks for explaining.

**Comment by fichtner** [comment]
The git-backup is using the same component for remote backups. So you have two places where this is documented. If you need details I would always recommend the source code.

**Comment by mzurhorst** [comment]
Would something like this be reasonable?

![grafik](https://user-images.githubusercontent.com/575190/182908180-e190807b-16e8-435f-9a2a-06315e84f775.png)

**Comment by fichtner** [comment]
@mzurhorst I don't mind the docs change except that we don't want to put the 1:00 am internals in there because if we have to change them (the cron jobs have been rearranged before) it'll void the documentation and possibly will be wrong for a long time).

**Comment by mzurhorst** [comment]
Sure. I will update the CR accordingly.  Shall I leave the "early morning" in or is this too specific as well?

**Comment by fichtner** [comment]
"nightly" or "overnight" would be more precise... in any case thanks for doing this
