### ISSUE TITLE
firewall: extend pool options support

### ISSUE THREAD

**Issue by fichtner** [opnsense/core#5934]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**

Currently only port forward rules support pool options. But firewall rules (FilterRule.php), 1:1 ("nat" rules of DNatRule.php) and automatic rules (Plugin.php) could have their options extended, the first two knowing nothing and the latter knowing only "round-robin [sticky-address]".

**Describe the solution you like**

Consistent and complete support of pool options across the different rule types.

**Additional context**

```
POOL OPTIONS
     For nat and rdr rules, (as well as for the route-to, reply-to and dup-to
     rule options) for which there is a single redirection address which has a
     subnet mask smaller than 32 for IPv4 or 128 for IPv6 (more than one IP
     address), a variety of different methods for assigning this address can
     be used:

     bitmask
           The bitmask option applies the network portion of the redirection
           address to the address to be modified (source with nat, destination
           with rdr).

     random
           The random option selects an address at random within the defined
           block of addresses.

     source-hash
           The source-hash option uses a hash of the source address to
           determine the redirection address, ensuring that the redirection
           address is always the same for a given source.  An optional key can
           be specified after this keyword either in hex or as a string; by
           default pfctl(8) randomly generates a key for source-hash every
           time the ruleset is reloaded.

     round-robin
           The round-robin option loops through the redirection address(es).

           When more than one redirection address is specified, round-robin is
           the only permitted pool type.

     static-port
           With nat rules, the static-port option prevents pf(4) from
           modifying the source port on TCP and UDP packets.

     map-e-portset ⟨psid-offset⟩ / ⟨psid-len⟩ / ⟨psid⟩
           With nat rules, the map-e-portset option enables the source port
           translation of MAP-E (RFC 7597) Customer Edge.  In order to make
           the host act as a MAP-E Customer Edge, setting up a tunneling
           interface and pass rules for encapsulated packets are required in
           addition to the map-e-portset nat rule.

           For example:

                 nat on $gif_mape_if from $int_if:network to any \
                       -> $ipv4_mape_src map-e-portset 6/8/0x34

           sets PSID offset 6, PSID length 8, PSID 0x34.

     Additionally, the sticky-address option can be specified to help ensure
     that multiple connections from the same source are mapped to the same
     redirection address.  This option can be used with the random and
     round-robin pool options.  Note that by default these associations are
     destroyed as soon as there are no longer states which refer to them; in
     order to make the mappings last beyond the lifetime of the states,
     increase the global options with set timeout src.track.  See STATEFUL
     TRACKING OPTIONS for more ways to control the source tracking.
```

**Comment by AdSchellevis** [comment]
ok, this was a nice idea... add the pool opt selection to the gateway group, which would make the current selection explicit and offers some different choices when here, but pf doesn't seem to support it, it errors out with:

```
...r.rpool.opts must be PF_POOL_ROUNDROBIN - The line in question reads....
```


https://github.com/opnsense/src/blob/44291f7a44c41bb205196cd18ae53b428db7fcf5/sbin/pfctl/parse.y#L2457-L2464

**Comment by fichtner** [comment]
That’s strange, let me check why that is next week.

**Comment by kulikov-a** [comment]
Hi!
I thought pool type other than` round-robin` are limited to single subnet pool only: `for which there is a single redirection address which has a subnet mask smaller than 32 for IPv4 or 128 for IPv6`? and `when more than one redirection address is specified,	round-robin is the only permitted pool type`
unfortunately it doesn't seem to work for addresses groups

**Comment by fichtner** [comment]
Yep so these things only work for one network address given /31 or /127 or smaller, which is only true for NAT if you use it. I can even produce errors trying a table with non-rounnd-robin pool option in port forward. Looks like this restriction is consistent and never changed.
