### ISSUE TITLE
interfaces: PHP 8 doesn't like config.xml "<wireless/>" node

### ISSUE THREAD

**Issue by fichtner** [opnsense/core#5939]
https://github.com/opnsense/core/blob/47bff6840dfbda481665a19f7517a68bb57e4080/src/www/interfaces.php#L931

```
Fatal error: Uncaught TypeError: Cannot access offset of type string on string in /usr/local/www/interfaces.php:931
```

via https://forum.opnsense.org/index.php?topic=29559.0

**Comment by hxw** [comment]
I experienced this error on a fresh install in a bhyve VM using passthru to allow the VM access to the WIFI device

**Comment by fichtner** [comment]
@hxw thanks for chiming in. Would you mind to try the patch 475cb8e to confirm it improves things on your end?

    # opnsense-patch 475cb8e


Cheers,
Franco

**Comment by hxw** [comment]
After patching I was able to reset to factory defaults and reconfigure without getting the php error.
Thanks for this.

**Comment by hxw** [comment]
However NAT did not work, no rules were shown on NAT/Outbound in automatic mode. So no ping/https from LAN net.

I changed `<if>iwm0</if>` to `<if>iwmo_wlan0</if>` in the `<wan>` section of config.xml

After a reboot the outbound automatic rules appeared and `pfctl -s nat` output now has several nat referencing iwm0_wlan0 lines.I can now ping and browse from the lan side.

I think you need the full interface name (iwm0_wlan0) as shown by ifconfig in pfctl commands, not just the iwm0 prefix.

**Comment by fichtner** [comment]
That would be 47bff6840dfbda, reported in a related forum thread.

I think we tripped over something repairing defunct wireless code for 22.7 and now we have a couple more bugs to deal with that were always there. One thing that struck me as odd is that the assignments in the console are only done partially and then the rest of the code tries to "unbreak" whatever it needs to arrive to a state that doesn't have a wireless clone attached but emulated because that was what the original console code misses in the first place.

I'm still unsure how to proceed, but if you say 47bff6840dfbda makes sense and it ends up ok I'm happy to merge the current state into 22.7.x.


Cheers,
Franco

**Comment by hxw** [comment]
That patch works, I was able to go from reset to default to working NAT without any config.xml changes. Thanks.

**Comment by hxw** [comment]
Just noticed a minor point, on the interfaces/assignments, the network port only has one item: vtnet0.
So WAN and LAN both show attached to vtnet0. The WAN interface is showing correct value: iwm0_wlan0 though.
(i noticed while looking to see if there was a way to set multiple ssid/psk)

**Comment by fichtner** [comment]
Thanks, same side-effect here from interface name mismatch due to "automatic" interpretation. https://github.com/opnsense/core/commit/76a473d8ed4e707f90d622a8169c8d20cd48cb6c should help avoid this...

    # opnsense-patch 76a473d

If you see anything else let me know. I'm pondering moving all wireless settings to wireless clones and creating explicit devices for them. It's probably going to have bugs migrating this and other twilight states, but it could really help simplify the code without ditching wireless functionality completely to achieve a similar goal of simplification.

**Comment by hxw** [comment]
One question, is it possible to have multiple wireless WAN ssid/key pairs e.g., home/office/… I have not experimented with the wireless clones yet. (I will check 76a473d later)

**Comment by fichtner** [comment]
@hxw yes, that's possible, but only as the driver/hardware permits. The trouble starts again with multiple clones and the default console assignment practice because the initial wireless interface will not register a clone to begin with. It will cause other issues. Discussed this briefly a bit and only solution here would be to force a configuration migration and create explicit clones from all "implied" clones in order to make this less error-prone. At the moment, however, that's not in our mid-term interest.


Cheers,
Franco

**Comment by hxw** [comment]
the patch for interface assignments works for me

**Comment by fichtner** [comment]
Thanks, I'll move those patches to 22.7.3 then. :)
