### ISSUE TITLE
EFI Boot 

### ISSUE THREAD

**Issue by openzu** [opnsense/core#594]
Hi,

I bought a Zotac CI323nano to install OPNsense. It does boot in Legacy mode, but after reboots it just hangs for a very long time and the whole setup does not seem very stable. Ubuntu 14.04 on the same machine with EFI Boot was way more stable. Is there a way to EFI Boot OPNsense? I could not find an option at install.

kind regards,
openzu

**Comment by jschellevis** [comment]
As far as I can see UEFI support in freebsd is new as of 10.2 not sure how well stock freebsd works on your mainboard.. Can you test that first? 
See also: https://wiki.freebsd.org/UEFI

-------- Oorspronkelijk bericht --------
Van: openzu <notifications@github.com> 
Datum: 02-01-2016  14:07  (GMT+01:00) 
Aan: opnsense/core <core@noreply.github.com> 
Onderwerp: [core] EFI Boot  (#594) 

Hi,

I bought a Zotac CI323nano to install OPNsense It does boot in Legacy mode, but after reboots it just hangs for a very long time and the whole setup does not seem very stable Ubuntu 1404 on the same machine with EFI Boot was way more stable Is there a way to EFI Boot OPNsense? I could not find an option at install

kind regards,

openzu

**Comment by openzu** [comment]
I downloaded http://vesta.informatik.rwth-aachen.de/ftp/pub/mirror/FreeBSD/releases/ISO-IMAGES/10.2/FreeBSD-10.2-RELEASE-amd64-memstick.img put it on a usb stick and booted via uefi. I installed it and an efi boot partition was created automatically. Booting the installed OS from SSD worked as well. Some controller dumps showed up at boot and delayed it a bit, but I am not sure this is connected to EFI.

**Comment by fichtner** [comment]
@openzu  With version 16.1 you may be able to use opnsense-bootstrap(8) in your 10.2 EFI install to convert the system to OPNsense... https://github.com/opnsense/update#opnsense-bootstrap

We will be looking into a full EFI boot image for 16.7.

**Comment by fichtner** [comment]
done for amd64 "cdrom" and "vga" images. The installer will also offer a "gpt/uefi" mode for installation as the new default. "mbr" is still possible.
