### ISSUE TITLE
NAT reflection for port forward rules not created, manual rules don't work.

### ISSUE THREAD

**Issue by Stan-Tastic** [opnsense/core#5941]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

**Problem description:**

_NAT reflection with SNAT doesn't work, no rules are created, the rules I create won't work._

**Network setup:**

_WAN - OPNSense - LAN1 - Router - LAN2_

There's masquerade done by OPNsense (Outbound NAT for LAN2). 

Port 22 on LAN2_A machine is exposed on WAN IP, port 3322 (port forwarding).

In Advanced settings, I have enabled "Reflection for port forwards", "Automatic outbound NAT for Reflection" and "Reflection for 1:1" (just in case). I expected some new automatic NAT rules to be created in "Outbound NAT", but nothing appeared there.

**Troubleshooting steps:**

When I connect from outside, all is fine.

When I connect from **LAN2_B** to **WAN:3322**, OPNsense only translates destination IP and returns the packet to _LAN2_ - so the connection doesn't work, because **LAN2_A** now sees the packet came from **LAN2_B** and tries to send SYN ACK to **LAN2_B**, but **LAN2_B** rejects this packet, because it sent SYN to **WAN:3322**, not to **LAN2_A**.

What needs to be done is SNAT in addition to DNAT, so that **LAN2_A** gets packet with OPNsense _LAN1_ address as source, and noone is confused.

This is what I assumed "Automatic reflection for Port Forwards" does - I thought it's going to create a new automatic rule in Outbound NAT - but there's no rule like this to be found! And yes, _I know_ it will only create rule for _LAN1_, not for _LAN2_, but that would at least give me some basis for creating my own rule.

Anyway, automatic doesn't work, so I can do this manually, right? I switched Outbound NAT to Hybrid mode, and create rule:

On LAN interface, when traffic comes from _LAN2_ network and is destined to **WAN:3322**, translate to OPNsense _LAN1_ IP. Log it.

Nothing. Doesn't work, there's nothing in the logs.

So, new rule (I'm not sure if Outbound NAT rules are evaluated before or after DNAT, did not find this info in the documentation):

On LAN interface, when traffic comes from _LAN2_ network and is destined to **LAN2_A:22**, translate to OPNsense _LAN1_ IP. Log it.

Again, nothing. Doesn't work, there's nothing in the logs.

So, I have 2 questions:

-   **What is the rule that would/should be autogenerated? (and why it's not created?)**
-   **What rule should be created to perform SNAT in this scenario? (i.e. what am I missing?)**

**To Reproduce**

1. Setup single port forward.
2. Make sure "Reflection for port forwards", "Automatic outbound NAT for Reflection" and "Reflection for 1:1" is enabled.
3. No profit.

**Expected behavior**

SNAT in addition to DNAT, so that **LAN2_A** gets packet with OPNsense _LAN1_ address as source.

**Describe alternatives you considered**

I switched Outbound NAT to Hybrid mode, and create rule:

On LAN interface, when traffic comes from _LAN2_ network and is destined to **WAN:3322**, translate to OPNsense _LAN1_ IP. Log it.

Nothing. Doesn't work, there's nothing in the logs.

So, new rule (I'm not sure if Outbound NAT rules are evaluated before or after DNAT, did not find this info in the documentation):

On LAN interface, when traffic comes from _LAN2_ network and is destined to **LAN2_A:22**, translate to OPNsense _LAN1_ IP. Log it.

Again, nothing. Doesn't work, there's nothing in the logs.

**Relevant log files**

There are no logs, I'm happy to provide tcpdump if that helps any.

**Additional context**

Network setup:

_WAN - OPNSense - LAN1 - Router - LAN2_

**Environment**

Proxmox VM
OPNsense 21.1.10_4 (amd64, OpenSSL).
VM x64
Network virtnet

**Comment by marshalleq** [comment]
I believe I have the same problem.  I need to use nat reflection for my mail server so that clients set up externally don't get complaints about security certificates due to differing IP's etc.  Everything works externally, internally I'm left with having to use multi-homed DNS which doesn't work for security certificates being that those are on a web proxy, not the mail server.  The obvious answer is to use NAT reflection and redirect all internal traffic for these services to the external IP and associated certificates.  But enabling NAT reflection does not create any new rules.  Worse, enabling these options actually prevents internal traffic from getting to the internet for some reason.  If anyone needs an additional person to help test, I'm happy to do so.  Only other alternative it seems is to use another firewall (which I do not desire BTW).  Thanks.

**Comment by marshalleq** [comment]
Bugs shouldn't need to be planned to remain open for a fix.  Opnsense has NAT reflection, but it doesn't work.  Really this should be fixed.  There are lots of posts about this going back many years and no action by the Opnsense team.  For all the good work Opnsense do, I can't for the life of me understand why this basic feature is constantly ignored.  Please can there be a fix for this bug.

**Comment by Stan-Tastic** [comment]
Same here, this is basic functionality.

pon., 6 lut 2023, 21:13 użytkownik marshalleq ***@***.***>
napisał:

**Comment by fichtner** [comment]
> So, I have 2 questions:
> 
> What is the rule that would/should be autogenerated? (and why it's not created?)
> What rule should be created to perform SNAT in this scenario? (i.e. what am I missing?)

So is it a bug or two questions? Do you expect commercial grade response here in community scope?

Everybody is free here to put work into it or not. If nothing gets done there is no point to keep tickets open. This is our simple policy.


Cheers,
Franco

**Comment by mimugmail** [comment]
In this scenario its just a lack of documentation, reflection works with ALL networks directly connected, same as auto nat. In the Initial post its LAN2 behind a router of LAN, how should opnsense know about it? Just add a manual nat rule for LAN, and while at it, give something back to the community in form of an updated doc :)

**Comment by marshalleq** [comment]
> Everybody is free here to put work into it or not. If nothing gets done there is no point to keep tickets open. This is our simple policy.
> 
> Cheers, Franco

What on earth is a ticketing system for if not to track open tickets.  For goodness sake, just because there's no community person to work on something now, doesn't mean that we should just ignore active and real bugs.  This is basic service management 101.  Instead, placing the burden back on the customer to continuously log the same bug over and over because someone wants to artificially make the bug list look less than it actually is, is complete madness.

**Comment by marshalleq** [comment]
> In this scenario its just a lack of documentation, reflection works with ALL networks directly connected, same as auto nat. In the Initial post its LAN2 behind a router of LAN, how should opnsense know about it? Just add a manual nat rule for LAN, and while at it, give something back to the community in form of an updated doc :)

How would you know this isn't a problem, if active bugs are being closed prematurely, without being resolved?

**Comment by fichtner** [comment]
You are welcome to disagree with our policy, but I don’t think it helps. And thanks to @mimugmail for sharing free professional advice. 👍
