### ISSUE TITLE
Feature: Unbound: AAAA-only mode

### ISSUE THREAD

**Issue by maurice-w** [opnsense/core#5944]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**

Some poorly implemented devices (IoT) do have IPv6 support, but prefer IPv4 whenever possible. These devices do perform DNS queries for A + AAAA records. If both exist, they should use IPv6, but actually use IPv4. Some devices don't even "fall back" to IPv6 in case IPv4 connections fail. The solution to this is only sending AAAA records in DNS responses, which successfully forces these devices to use IPv6.

**Describe the solution you like**

I would like an option in the Unbound settings which removes all A records from responses. Since this only makes sense if all host names have AAAA records, this option should only apply if DNS64 is enabled.

**Additional context**

This is also useful for testing which devices / applications brake if there are no A records in DNS at all.

**Comment by fichtner** [comment]
@maurice-w can you check 4bc0871 for me on top? too many variables in the config and if/else bootstrap for my taste

**Comment by maurice-w** [comment]
@fichtner Thanks for the clean-up, works fine! We don't strictly need the `.=` and `\n` here, do we?
https://github.com/opnsense/core/blob/4bc0871c9922834f8513f76eec054d21885e06a7/src/etc/inc/plugins.inc.d/unbound.inc#L128
Same here for `.=`:
https://github.com/opnsense/core/blob/4bc0871c9922834f8513f76eec054d21885e06a7/src/etc/inc/plugins.inc.d/unbound.inc#L131

**Comment by maurice-w** [comment]
Makes sense, I'll keep that in mind. Thanks!

**Comment by KDGundermann** [comment]
sorry my dumb question but I'm new to OPNsense and Unbound
but is there also an A-only mode ?
(as we use only IPv4 in our network )

**Comment by maurice-w** [comment]
@KDGundermann There is no A-only mode. What problem would that solve?
