### ISSUE TITLE
Router Solicitation not working on IPv6-only WAN interface

### ISSUE THREAD

**Issue by maurice-w** [opnsense/core#5946]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

If a WAN interface is configured with DHCPv6 or SLAAC and no IPv4, rtsold doesn't send Router Solicitations from the interface and doesn't process Router Advertisements received on the interface.

Not sure if this ever worked.

**To Reproduce**

1. Go to 'Interfaces: [WAN]', set 'IPv4 Configuration Type' to 'None' and 'IPv6 Configuration Type' to 'DHCPv6' or 'SLAAC' (both are affected).
2. Save, apply and reboot(!).
3. See error: No Router Solicitations are being sent (confirmed by packet capture) and /tmp/$if_routerv6 file doesn't get created.
4. Go to 'Interfaces: [WAN]', set 'IPv4 Configuration Type' to 'Static IPv4' or 'DHCP' (either works).
5. Save, apply and reboot(!).
6. See result: Router Solicitations are being sent and /tmp/*_routerv6 file gets created.

**Expected behavior**

The IPv4 configuration should have no impact on rtsold behaviour.

**Describe alternatives you considered**

- Trigger link down / up event (unplug / plug cable on physical machine or disconnect / connect interface on VM).
- Save & apply WAN interface configuration (without changing anything).

Both workarounds result in rtsold working properly until the next reboot. A more permanent workaround is configuring a static /32 dummy IPv4 address on the affected interface.

**Additional context**

We might be skipping some initialization steps during startup if `<ipaddr>` doesn't exist in the config. Wasn't able to pin it down yet, ideas welcome.

**Environment**

OPNsense 23.1.a_59 (amd64, OpenSSL)
Hyper-V Gen2 Ver10.0

**Comment by fichtner** [comment]
This didn't work at some point in time since the thing was supposed to be "dual" stack where IPv4 would be the driving force, but for me it worked fine with DHCPv6 (except the part where GitHub isn't available on IPv6 so I can't tell about it).

One thing that affects this is "Use IPv4 connectivity" which then would wait for IPv4 to come up first. I have it unchecked.


Cheers,
Franco

**Comment by maurice-w** [comment]
@fichtner, thanks for your feedback. I tested this extensively and can say with certainty that as of 23.1.a_59, both DHCPv6 and SLAAC are affected. 'Use IPv4 connectivity' is disabled.

In case of DHCPv6, dhcp6c works - interface address, delegated prefix and DNS info do get assigned. But rtsold fails - the _routerv6 file doesn't get created. Could you double-check whether this actually works for you?

In case of SLAAC, the interface autoconfigures an address, but rtsold fails - the _routerv6 file doesn't get created and RDNSS / DNSSL info doesn't get processed.

Since it works fine after a link down / up event or interface reconfiguration and only breaks after a reboot, it might be one of these hard to track timing issues.

Cheers
Maurice

**Comment by maurice-w** [comment]
Making some progress. I dumped ifconfig output to a file just before rtsold gets invoked:
https://github.com/opnsense/core/blob/19a14cac7ea8ab8f949852a6e8d367646c9e4d85/src/etc/inc/interfaces.inc#L2693-L2695
Turns out the interface is not ready at this point. As a result, rtsold fails:
```
hn1: flags=8802<BROADCAST,SIMPLEX,MULTICAST> metric 0 mtu 1500
        description: WAN
        options=80018<VLAN_MTU,VLAN_HWTAGGING,LINKSTATE>
        ether 00:15:5d:d2:76:1c
        media: Ethernet autoselect (10Gbase-T <full-duplex>)
        status: active
        nd6 options=23<PERFORMNUD,ACCEPT_RTADV,AUTO_LINKLOCAL>
```

Now add a static IPv4 address, reboot, and the interface is up & running at the same point and rtsold works:
```
hn1: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500
        description: WAN
        options=80018<VLAN_MTU,VLAN_HWTAGGING,LINKSTATE>
        ether 00:15:5d:d2:76:1c
        inet 127.0.0.2 netmask 0xffffffff broadcast 127.0.0.2
        inet6 fe80::215:5dff:fed2:761c%hn1 prefixlen 64 tentative scopeid 0x6
        media: Ethernet autoselect (10Gbase-T <full-duplex>)
        status: active
        nd6 options=23<PERFORMNUD,ACCEPT_RTADV,AUTO_LINKLOCAL>
```

**Comment by maurice-w** [comment]
de2c088a8b55a29c1c9424c3ff54e0d168ddacbb fixes it. Note sure yet whether there could be any side effects if the interface is already up. Will check.

**Comment by fichtner** [comment]
Missing link-local causing this issue perhaps? I'm not sure why I'm not seeing this, but shouldn't be a problem specific to hn(4) interfaces. Let me try this :)

**Comment by fichtner** [comment]
BTW, it's stating "tentative" here. Same issue with missing delay? oO

**Comment by fichtner** [comment]
Might be hn(4) related after all:

https://github.com/opnsense/src/blob/c7fed157a7721092a3d364b14475254dd83ab0af/usr.sbin/rtsold/if.c#L205-L209

https://lists.freebsd.org/pipermail/freebsd-hackers/2004-August/007817.html

**Comment by fichtner** [comment]
I wonder why IPv4-only thinks that it's UP at this point and it starts to work?

**Comment by fichtner** [comment]
Let's play a bit of whack-a-mole here with c01ad5059f2a + ddb79243cc

**Comment by fichtner** [comment]
@maurice-w you are probably on a well-deserved holiday. I'm assuming this works (at least as good as before) so dcf9b2b is going into 22.7.4.
