### ISSUE TITLE
Feature: dhcpd6: allow Rapid Commit

### ISSUE THREAD

**Issue by maurice-w** [opnsense/core#5947]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**

Some DHCPv6 clients only support the two-message exchange (solicit - reply, a.k.a. Rapid Commit), but not the full four-message exchange (solicit - advertise - request - reply). ISC dhcpd supports this, but the configuration created by OPNsense currently doesn't include the option which allows it.

**Describe the solution you like**

Add `option dhcp6.rapid-commit;` to dhcpdv6.conf. This enables the Rapid Commit exchange if a client explicitly requests it in the initial solicit message.

**Comment by fichtner** [comment]
I don't mind trying this as the default, but if this turns out to cause issues we  need to revert and/or add a configuration option for it.

I couldn't find a lot info about this. This here seems only tangetially relevant https://telekomhilft.telekom.de/t5/Festnetz-Internet/Fehlerhafte-Implementierung-der-RFC3315-Abschnitt-22-14-im/td-p/1477491


Cheers,
Franco

**Comment by maurice-w** [comment]
Yeah, I initially thought about making this configurable. I can add a checkbox if you prefer. But probably the only situation where this might cause issues is a broken client requesting rapid commit but not actually being able to handle it. We might as well roll it out and wait for bug reports. ;-)

(This solved an actual problem for me with a client which can't do the four-message exchange at all.)

**Comment by fichtner** [comment]
@maurice-w yep, let's leave this as is and introduce this into 22.7.x, maybe .4 or .5
