### ISSUE TITLE
LDAP Errors with Upgrade to PHP 8

### ISSUE THREAD

**Issue by JamieOrlando-Engooden** [opnsense/core#5949]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

After the upgrade to 22.7, auth calls to my ldap server are failing with the following error.

`Fatal error: Uncaught TypeError: ldap_get_entries(): Argument #2 ($result) must be of type resource, bool given in /usr/local/opnsense/mvc/app/library/OPNsense/Auth/LDAP.php:596 Stack trace: #0 /usr/local/opnsense/mvc/app/library/OPNsense/Auth/LDAP.php(596): ldap_get_entries(Resource id #50, false) #1 /usr/local/www/diag_authentication.php(57): OPNsense\Auth\LDAP->authenticate('jo.test@engoode...', 'Password1$') #2 {main} thrown in /usr/local/opnsense/mvc/app/library/OPNsense/Auth/LDAP.php on line 596`

I suspect this has to do with the upgrade to PHP 8, but I am not familiar enough with PHP to know where to look next.

**To Reproduce**

1. Create an ldap connection using the Okta virtual ldap
2. Upgrade to 22.7
3. LDAP calls fail with the given error

**Expected behavior**

I would expect the ldap calls to authenticate successfully as worked in the same configuration for previous opnsense versions.

**Describe alternatives you considered**

Downgrading back to 22.1.10 fixes the issue

**Screenshots**

ldap server configuration
![image](https://user-images.githubusercontent.com/79408459/184362163-83097568-8114-4d70-b143-464d9e76fed8.png)

Testing the auth
![image](https://user-images.githubusercontent.com/79408459/184362305-7b7fb78b-308c-4bed-af20-4ee8c8830a7a.png)

Failure
![err](https://user-images.githubusercontent.com/79408459/184362805-c61ff780-aa97-4b54-87eb-6714f140890e.png)

**Relevant log files**

`
 | LDAP bind error [Authentication failed : (Refer to Okta error Code E0000004); Invalid credentials]
`

The following was noticed during the upgrade, not sure if relevant.

`
2022-08-11T20:28:01 | Error | opnsense | /usr/local/etc/rc.configure_firmware: warning: ignoring missing default tunable request: net.inet.ip.fastforwarding
`

**Additional context**

N/A

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 22.1.10_4-amd64
FreeBSD 13.0-STABLE
OpenSSL 1.1.1q 5 Jul 2022

**Comment by AdSchellevis** [comment]
@JamieOrlando-Engooden can you try https://github.com/opnsense/core/commit/bc392461da6e1fe79cd2aeb9c22214137f88906f? I haven't had time to check this locally yet, but it looks like a classic php 8 change. 

This should install the patch via a console:
```
opnsense-patch bc39246
```

**Comment by JamieOrlando-Engooden** [comment]
Thank you very much @AdSchellevis . I can confirm this fixed the issue I was running into.

**Comment by AdSchellevis** [comment]
@JamieOrlando-Engooden thanks for letting us know, we'll try to queue this one for 22.7.2
