### ISSUE TITLE
DHCP Client Confuses Unbound When Changing IP Addresses

### ISSUE THREAD

**Issue by jasonpcrowley** [opnsense/core#5952]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

When a DHCP client explicitly releases a lease and uses a discover request to get a new lease with a different IP address, the unbound_watcher.py script will see both the old lease and the new lease in the dhcpd.leases file and log numerous "dhcpd entry changed" events. Then, when the older of the two leases expires, a "dhcpd expired" event will be logged and the entry is removed from Unbound.

I am running OPNsense 22.1.8_1, but unbound_watcher.py hasn't changed, so I think the problem exists in current versions as well.

**To Reproduce**

1. On a DHCP client release and discover an IP address. I used the following to force this on a Ubiquiti wireless access point.
   ```
   kill -SIGUSR2 `pidof udhcpc`; kill -SIGUSR1 `pidof udhcpc`
   ```
2. Grab a copy of dhcpd.leases and dhcpdleases.conf on your OPNsense instance. You can analyze these files to see multiple entries for your client. 
   ```
   cp /var/dhcpd/var/db/dhcpd.leases ~ ; cp /var/unbound/dhcpleases.conf ~
   ```
3. Notice the copious log related to your client. 
   ```
   grep -i YourDHCPClientHostName /var/log/dhcpd/latest.log /var/log/resolver/latest.log
   ```
4. Try to resolve your client's IP address. Notice that you get two IP addresses. 
   ```
   nslookup YourDHCPClientHostName
   ```
5. Tail the resolver log until you see "dhcpd expired YourDHCPClientHostName". This may take a while if your lease time isn't fairly short. 
   ```
   tail -f /var/log/resolver/latest.log
   ```
6. When the "dhcp expired" line shows up, try to resolve your client's IP address again. You will get an NXDOMAIN response. 
   ```
   nslookup YourDHCPClientHostName
   ```

**Expected behavior**

Only the most recent lease matters. The unbound_watcher.py script should only use the last lease in the file for registering entries in the Unbound server. According to the man page for dhcpd.leases:
> The lease file is a log-structured file - whenever a lease changes, the contents of that lease are written to the end of the file. This means that it is entirely possible and quite reasonable for there to be two or more declarations of the same lease in the lease file at the same time. In that case, the instance of that particular lease that appears last in the file is the one that is in effect.

When changing a lease from one IP address to another, only the IP address from the current lease should be returned. 

**Describe alternatives you considered**

Killing and restarting the unbound_dhcpd.py (a.k.a. unbound_watcher.py) process fixes the problem temporarily. The only permanent solution I can find is to issue static leases for all devices that might behave in this way.

**Relevant log files**

/var/log/dhcpd/latest.log
```
2022-08-12T12:05:37-05:00 MyOPNsense.mydomain.org dhcpd 52501 - [meta sequenceId="2949"] DHCPRELEASE of 172.23.128.214 from 68:d7:9a:86:2c:f1 (MyDHCPClient) via ixl0 (found)
2022-08-12T12:05:37-05:00 MyOPNsense.mydomain.org dhcpd 52501 - [meta sequenceId="2950"] DHCPREQUEST for 172.23.128.214 from 68:d7:9a:86:2c:f1 (MyDHCPClient) via ixl0: lease in transition state released
2022-08-12T12:05:37-05:00 MyOPNsense.mydomain.org dhcpd 52501 - [meta sequenceId="2951"] DHCPDISCOVER from 68:d7:9a:86:2c:f1 (MyDHCPClient) via ixl0
2022-08-12T12:05:38-05:00 MyOPNsense.mydomain.org dhcpd 52501 - [meta sequenceId="2952"] DHCPOFFER on 172.23.128.209 to 68:d7:9a:86:2c:f1 (MyDHCPClient) via ixl0
2022-08-12T12:05:38-05:00 MyOPNsense.mydomain.org dhcpd 52501 - [meta sequenceId="2953"] DHCPREQUEST for 172.23.128.209 (172.23.128.3) from 68:d7:9a:86:2c:f1 (MyDHCPClient) via ixl0
2022-08-12T12:05:38-05:00 MyOPNsense.mydomain.org dhcpd 52501 - [meta sequenceId="2954"] DHCPACK on 172.23.128.209 to 68:d7:9a:86:2c:f1 (MyDHCPClient) via ixl0
```

/var/log/resolver/latest.log
```
2022-08-12T13:37:59-05:00 MyOPNsense.mydomain.org unbound 84950 - [meta sequenceId="1"] dhcpd entry changed MyDHCPClient.mydomain.org @ 172.23.128.214.
2022-08-12T13:38:01-05:00 MyOPNsense.mydomain.org unbound 84950 - [meta sequenceId="2"] dhcpd entry changed MyDHCPClient.mydomain.org @ 172.23.128.209.
2022-08-12T13:38:01-05:00 MyOPNsense.mydomain.org unbound 84950 - [meta sequenceId="3"] dhcpd entry changed MyDHCPClient.mydomain.org @ 172.23.128.214.
2022-08-12T13:38:04-05:00 MyOPNsense.mydomain.org unbound 84950 - [meta sequenceId="4"] dhcpd entry changed MyDHCPClient.mydomain.org @ 172.23.128.209.
** Repeats Hundreds of Times **
2022-08-12T13:38:04-05:00 MyOPNsense.mydomain.org unbound 84950 - [meta sequenceId="407"] dhcpd entry changed MyDHCPClient.mydomain.org @ 172.23.128.214.
2022-08-12T13:38:06-05:00 MyOPNsense.mydomain.org unbound 84950 - [meta sequenceId="408"] dhcpd entry changed MyDHCPClient.mydomain.org @ 172.23.128.209.
2022-08-12T13:38:06-05:00 MyOPNsense.mydomain.org unbound 84950 - [meta sequenceId="409"] dhcpd entry changed MyDHCPClient.mydomain.org @ 172.23.128.214.
2022-08-12T13:38:08-05:00 MyOPNsense.mydomain.org unbound 84950 - [meta sequenceId="410"] dhcpd entry changed MyDHCPClient.mydomain.org @ 172.23.128.209.
2022-08-12T13:38:08-05:00 MyOPNsense.mydomain.org unbound 84950 - [meta sequenceId="411"] dhcpd entry changed MyDHCPClient.mydomain.org @ 172.23.128.214.
2022-08-12T13:38:31-05:00 MyOPNsense.mydomain.org unbound 84950 - [meta sequenceId="412"] dhcpd expired MyDHCPClient @ 172.23.128.209
```

**Environment**

OPNsense 22.1.8_1-amd64
Intel(R) Core(TM) i9-9900KF CPU @ 3.60GHz (8 cores, 16 threads)
Network Intel X710-DA2

**Comment by sanxiago** [comment]
I am seeing this also on OPNsense 22.1.10_4-amd64

**Comment by sanxiago** [comment]
I may be speaking nonsense because I am not familiar with any of these scripts, and it's late here.

Looks like this is the watcher and it indexes by IP address
https://github.com/opnsense/core/blob/3ca57fae8b8f460eedb0a649e26ea7fac95bf9c9/src/opnsense/site-python/watchers/dhcpd.py#L62

I am using this to see if I can get it fixed:
https://github.com/opnsense/core/blob/af587e812a7b8d96cf3fd84869dc7e00bbfe09b3/src/opnsense/scripts/interfaces/list_arp.py

**Comment by AdSchellevis** [comment]
What does `/var/dhcpd/var/db/dhcpd.leases` contain for the host after the new  discovery?

**Comment by jasonpcrowley** [comment]
Here are the dhcpd.leases entries for the host in question. I had released the IP more than once in a couple of hours so it might be a little cluttered. 

Relevant log from `/var/log/dhcpd`:
```
<190>1 2022-08-12T12:01:17-05:00 IWNKGW01.nk.iwerx.org dhcpd 52501 - [meta sequenceId="2709"] DHCPRELEASE of 172.23.128.214 from 68:d7:9a:86:2c:f1 (IWNKD1WL01) via ixl0 (found)
<190>1 2022-08-12T12:05:37-05:00 IWNKGW01.nk.iwerx.org dhcpd 52501 - [meta sequenceId="2949"] DHCPRELEASE of 172.23.128.214 from 68:d7:9a:86:2c:f1 (IWNKD1WL01) via ixl0 (found)
<190>1 2022-08-12T13:17:29-05:00 IWNKGW01.nk.iwerx.org dhcpd 52501 - [meta sequenceId="4416"] DHCPRELEASE of 172.23.128.209 from 68:d7:9a:86:2c:f1 (IWNKD1WL01) via ixl0 (found)
```

Relevant leases from `/var/dhcpd/var/db/dhcpd.leases`:
```
lease 172.23.128.214 {
  starts 5 2022/08/12 17:02:58;
  ends 5 2022/08/12 17:05:37;
  tstp 5 2022/08/12 17:05:37;
  tsfp 5 2022/08/12 17:05:37;
  atsfp 5 2022/08/12 17:05:37;
  cltt 5 2022/08/12 17:02:58;
  binding state free;
  hardware ethernet 68:d7:9a:86:2c:f1;
  uid "\001h\327\232\206,\361";
}
lease 172.23.128.209 {
  starts 5 2022/08/12 17:38:08;
  ends 5 2022/08/12 18:08:08;
  tstp 5 2022/08/12 18:23:08;
  tsfp 5 2022/08/12 18:23:08;
  atsfp 5 2022/08/12 18:23:08;
  cltt 5 2022/08/12 17:38:08;
  binding state active;
  next binding state expired;
  hardware ethernet 68:d7:9a:86:2c:f1;
  uid "\001h\327\232\206,\361";
  set vendor-class-identifier = "ubnt";
  client-hostname "MyDHCPClient";
}
lease 172.23.128.209 {
  starts 5 2022/08/12 17:53:08;
  ends 5 2022/08/12 18:23:08;
  tstp 5 2022/08/12 18:38:08;
  tsfp 5 2022/08/12 18:23:08;
  cltt 5 2022/08/12 17:53:08;
  binding state active;
  next binding state expired;
  hardware ethernet 68:d7:9a:86:2c:f1;
  uid "\001h\327\232\206,\361";
  set vendor-class-identifier = "ubnt";
  client-hostname "MyDHCPClient";
}
lease 172.23.128.209 {
  starts 5 2022/08/12 17:53:08;
  ends 5 2022/08/12 18:23:08;
  tstp 5 2022/08/12 18:38:08;
  tsfp 5 2022/08/12 18:38:08;
  atsfp 5 2022/08/12 18:38:08;
  cltt 5 2022/08/12 17:53:08;
  binding state active;
  next binding state expired;
  hardware ethernet 68:d7:9a:86:2c:f1;
  uid "\001h\327\232\206,\361";
  set vendor-class-identifier = "ubnt";
  client-hostname "MyDHCPClient";
}
lease 172.23.128.209 {
  starts 5 2022/08/12 18:08:09;
  ends 5 2022/08/12 18:38:09;
  tstp 5 2022/08/12 18:53:09;
  tsfp 5 2022/08/12 18:38:08;
  cltt 5 2022/08/12 18:08:09;
  binding state active;
  next binding state expired;
  hardware ethernet 68:d7:9a:86:2c:f1;
  uid "\001h\327\232\206,\361";
  set vendor-class-identifier = "ubnt";
  client-hostname "MyDHCPClient";
}
lease 172.23.128.209 {
  starts 5 2022/08/12 18:08:09;
  ends 5 2022/08/12 18:38:09;
  tstp 5 2022/08/12 18:53:09;
  tsfp 5 2022/08/12 18:53:09;
  atsfp 5 2022/08/12 18:53:09;
  cltt 5 2022/08/12 18:08:09;
  binding state active;
  next binding state expired;
  hardware ethernet 68:d7:9a:86:2c:f1;
  uid "\001h\327\232\206,\361";
  set vendor-class-identifier = "ubnt";
  client-hostname "MyDHCPClient";
}
lease 172.23.128.209 {
  starts 5 2022/08/12 18:08:09;
  ends 5 2022/08/12 18:17:29;
  tstp 5 2022/08/12 18:17:29;
  tsfp 5 2022/08/12 18:53:09;
  cltt 5 2022/08/12 18:08:09;
  binding state released;
  next binding state free;
  hardware ethernet 68:d7:9a:86:2c:f1;
  uid "\001h\327\232\206,\361";
  client-hostname "MyDHCPClient";
}
lease 172.23.128.214 {
  starts 5 2022/08/12 18:17:31;
  ends 5 2022/08/12 18:27:31;
  tstp 5 2022/08/12 18:52:31;
  tsfp 5 2022/08/12 17:05:37;
  cltt 5 2022/08/12 18:17:31;
  binding state active;
  next binding state expired;
  rewind binding state free;
  hardware ethernet 68:d7:9a:86:2c:f1;
  uid "\001h\327\232\206,\361";
  set vendor-class-identifier = "ubnt";
  client-hostname "MyDHCPClient";
}
lease 172.23.128.214 {
  starts 5 2022/08/12 18:17:31;
  ends 5 2022/08/12 18:27:31;
  tstp 5 2022/08/12 18:52:31;
  tsfp 5 2022/08/12 17:05:37;
  cltt 5 2022/08/12 18:17:31;
  binding state active;
  next binding state expired;
  hardware ethernet 68:d7:9a:86:2c:f1;
  uid "\001h\327\232\206,\361";
  set vendor-class-identifier = "ubnt";
  client-hostname "MyDHCPClient";
}
lease 172.23.128.209 {
  starts 5 2022/08/12 18:08:09;
  ends 5 2022/08/12 18:17:29;
  tstp 5 2022/08/12 18:17:29;
  tsfp 5 2022/08/12 18:17:29;
  atsfp 5 2022/08/12 18:17:29;
  cltt 5 2022/08/12 18:08:09;
  binding state free;
  hardware ethernet 68:d7:9a:86:2c:f1;
  uid "\001h\327\232\206,\361";
}
lease 172.23.128.214 {
  starts 5 2022/08/12 18:17:31;
  ends 5 2022/08/12 18:27:31;
  tstp 5 2022/08/12 18:52:31;
  tsfp 5 2022/08/12 18:52:31;
  atsfp 5 2022/08/12 18:52:31;
  cltt 5 2022/08/12 18:17:31;
  binding state active;
  next binding state expired;
  hardware ethernet 68:d7:9a:86:2c:f1;
  uid "\001h\327\232\206,\361";
  set vendor-class-identifier = "ubnt";
  client-hostname "MyDHCPClient";
}
lease 172.23.128.214 {
  starts 5 2022/08/12 18:17:31;
  ends 5 2022/08/12 18:47:31;
  tstp 5 2022/08/12 18:52:31;
  tsfp 5 2022/08/12 19:02:31;
  atsfp 5 2022/08/12 19:02:31;
  cltt 5 2022/08/12 18:17:31;
  binding state active;
  next binding state expired;
  hardware ethernet 68:d7:9a:86:2c:f1;
  uid "\001h\327\232\206,\361";
  set vendor-class-identifier = "ubnt";
  client-hostname "MyDHCPClient";
}
```
[dhcpd.leases.txt](https://github.com/opnsense/core/files/9331366/dhcpd.leases.txt)

**Comment by AdSchellevis** [comment]
I'm not sure we can/should fix anything to be honest. It kind of depends if the old entry is indeed removed around the time it should according the latest received "end" timestamp. One hostname may have different leases at the same time, we can't really trust anything else then the lease (address) and the timestamp where it should be released, which is where the expired messages come into place:

https://github.com/opnsense/core/blob/e58d7de7d4090524aa7e6f09900b77c43dbd820f/src/opnsense/scripts/dhcp/unbound_watcher.py#L163

It might be possible to solve this from dhcpd's end, the unbound lease worker doesn't seem to be doing anything wrong at the moment.

**Comment by jasonpcrowley** [comment]
First, thanks for looking into this thoroughly!

There are two problems I see that I think should be addressed:

1. When there are two DHCP leases for the same IP, the watcher will wait for the first one to expire and then delete the A record  that contains both IPs altogether leaving no A record for either the new IP or the old one. It seems to me that the remaining active lease should maintain both an A and PTR record. Even though the DHCP client maintains a record in `dhcpd.leases` through several renewals, the watcher will never pick it up and put it back in Unbound. (If I restart the DHCP watcher, the A and PTR records return.)
2. This one is less important to me, but I think it's still relevant. The `dhcpd.leases` file is meant to be read in order with each successive record replacing the previous one for the same IP. In that case, when the following lines including `binding state free;` are appended to the `dhcpd.leases` file, the watcher should delete both the A and PTR records for 172.23.128.209. At least that's my opinion of how it should work. 
   ```
   lease 172.23.128.209 {
     starts 5 2022/08/12 18:08:09;
     ends 5 2022/08/12 18:17:29;
     tstp 5 2022/08/12 18:17:29;
     tsfp 5 2022/08/12 18:17:29;
     atsfp 5 2022/08/12 18:17:29;
     cltt 5 2022/08/12 18:08:09;
     binding state free;
     hardware ethernet 68:d7:9a:86:2c:f1;
     uid "\001h\327\232\206,\361";
   }
   ```

I realize that for the second problem, I'm asking for a substantial recoding of the DHCP watcher for a problem that doesn't seem to affect many people. I'm more concerned about the first part where DNS entries disappear never to return. 

Let me know what you think. Thanks.

**Comment by AdSchellevis** [comment]
@jasonpcrowley can you try https://github.com/opnsense/core/commit/fcbdc44f6384704f8873bf91308e9d10799d4e8c, it should fix point 1 (which is indeed unintended behaviour)

**Comment by jasonpcrowley** [comment]
@AdSchellevis, it worked great! 

When I released the first IP and discovered another, the A record switched from the first IP to the second one. Unbound still had PTR records for both IPs pointing back to the same hostname until the lease for the first IP expired. Then the associated PTR record was removed. 

Relevant log from `/var/log/dhcpd`:
```
<190>1 2022-08-15T13:57:56-05:00 MyOPNsense.mydomain.org dhcpd 52501 - [meta sequenceId="259"] DHCPRELEASE of 172.23.128.238 from e0:63:da:22:6b:12 (MyDHCPClient) via ixl0 (found)
<190>1 2022-08-15T13:57:56-05:00 MyOPNsense.mydomain.org dhcpd 52501 - [meta sequenceId="260"] DHCPDISCOVER from e0:63:da:22:6b:12 (MyDHCPClient) via ixl0
<190>1 2022-08-15T13:57:57-05:00 MyOPNsense.mydomain.org dhcpd 52501 - [meta sequenceId="261"] DHCPOFFER on 172.23.128.216 to e0:63:da:22:6b:12 (MyDHCPClient) via ixl0
<190>1 2022-08-15T13:57:57-05:00 MyOPNsense.mydomain.org dhcpd 52501 - [meta sequenceId="262"] DHCPREQUEST for 172.23.128.216 (172.23.128.3) from e0:63:da:22:6b:12 (MyDHCPClient) via ixl0
<190>1 2022-08-15T13:57:57-05:00 MyOPNsense.mydomain.org dhcpd 52501 - [meta sequenceId="263"] DHCPACK on 172.23.128.216 to e0:63:da:22:6b:12 (MyDHCPClient) via ixl0
```
Relevant log from `/var/log/resolver`:
```
<165>1 2022-08-15T13:57:58-05:00 MyOPNsense.mydomain.org unbound 65825 - [meta sequenceId="2"] dhcpd entry changed MyDHCPClient.mydomain.org @ 172.23.128.216.
<165>1 2022-08-15T14:27:07-05:00 IWNKGW01.nk.iwerx.org unbound 65825 - [meta sequenceId="1"] dhcpd expired MyDHCPClient @ 172.23.128.238
```
Thanks!

**Comment by AdSchellevis** [comment]
@jasonpcrowley thanks for testing! can we consider this issue closed?

**Comment by jasonpcrowley** [comment]
@AdSchellevis yes, please close it. I look forward to having it implemented in the next release. Thanks again for your quick work on this!

**Comment by fichtner** [comment]
Release engineering note: probably part of 22.7.3, not 22.7.2.

**Comment by jasonpcrowley** [comment]
22.7.3 will work for me. It's a single-file update if I need it before then. Thanks.

**Comment by fichtner** [comment]
Not sure if you know, but it's a always a single-**line** update using:

    # opnsense-patch fcbdc44

;)

**Comment by jasonpcrowley** [comment]
I was aware, but because the site where we're seeing the problem is on 22.1.8_1, and the path to the file in question has changed, I opted to just copy the file to the correct location. Would `opnsense-patch fcbdc44` have worked on such an old version?

**Comment by fichtner** [comment]
Should have looked closer. Yes, the file was moved for organizational reasons which makes opnsense-patch fail indeed.
