### ISSUE TITLE
Interfaces : tunnel types and assigments

### ISSUE THREAD

**Issue by AdSchellevis** [opnsense/core#5953]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

Not sure it's a bug, but more an inconvenience. When assigning tunnel interfaces such as openvpn, applying settings will remove the tunnel address as the frontend code thinks it's responsible for the interface (also when set to None) and removes the current addressing, due to.

https://github.com/opnsense/core/blob/475cb8ec7fcea310eea92eb4f1e75491b1253f87/src/www/interfaces.php#L580

Although in most cases it might make sense to remove all addresses, for just configured vpns it's a bit annoying to loose the configuration after first assignment (especially when connected over that same vpn ;) ).
Not sure what the best course of action is here, the most pragmatic option might be to prevent removal when the interface is a tunnel type (using `legacy_interfaces_details()` tunnel property).

**To Reproduce**

1. setup an openvpn server
2. assign new interface (ovpnsX), with none as ipvX settings and enable
3. hit apply

**Expected behavior**

Keeping an active tunnel after configuration.

**Describe alternatives you considered**

none

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 22.7_4(amd64, OpenSSL).

**Comment by mimugmail** [comment]
Same happens to Wireguard too

**Comment by AdSchellevis** [comment]
that was to be expected, I expect it's safe to prevent execution of `interface_bring_down()` for tunnel types, just wanted to push it in a ticket first to have feedback about possible concerns.

**Comment by fichtner** [comment]
Seems to be a very specific code case and mismatch on primary address removal. How about in bring_down we check if actually IPv4 or IPv6 is configured to other than none before we remove any address? I think nowadays configure does the same.

**Comment by AdSchellevis** [comment]
I think we're potentially left with addresses on previously used interfaces in that case, fixing the "primary" issue could be a simple change as well to `legacy_interfaces_details()`, copy the tunnel property on the top level so we can safely check if there's a tunnel configured (in which case it's quite unlikely we do need to flush addresses).

This would result in a structure similar to the following:

```
{
  "flags": [
    "up",
    "pointopoint",
    "running",
    "multicast"
  ],
  "capabilities": [
    "linkstate"
  ],
  "options": [
    "linkstate",
    "performnud",
    "auto_linklocal"
  ],
  "macaddr": "00:00:00:00:00:00",
  "ipv4": [
    {
      "ipaddr": "xxx.xxx.xxx.xxx",
      "subnetbits": 24,
      "tunnel": true,
      "endpoint": "xxx.xxx.xxx.xxx"
    }
  ],
  "ipv6": [
    {
      "deprecated": false,
      "ipaddr": "xxxx::xxxx:xxxx:xxxx:xxxxx",
      "link-local": true,
      "tentative": false,
      "tunnel": false,
      "subnetbits": 64
    }
  ],
  "supported_media": [],
  "mtu": "1500",
  "groups": [
    "tun",
    "openvpn"
  ],
  "is_tunnel": true   <---- one or more addresses are a tunnel (v4/v6)
}
```

Keeping the logic in `interfaces.php` would prevent performance issues due to `interface_bring_down()` not knowing status of the interface currently (and functionally it makes sense that down really de-configures the interface unconditionally).

**Comment by fichtner** [comment]
Apply’s bring down uses the old configuration flushed to disk before hitting save so it should be safe (and sane).

**Comment by AdSchellevis** [comment]
@fichtner I see your point, https://github.com/opnsense/core/commit/7bbfd981aca6e8abed55d93d6a636e4ee3f587a2 might be a better option then.

**Comment by fichtner** [comment]
I was thinking more along the lines of 74a4c1a which we need anyway for consistency.

If we want to avoid bring_down here this seems more appropriate:

https://github.com/opnsense/core/blob/7bbfd981aca6e8abed55d93d6a636e4ee3f587a2/src/www/interfaces.php#L666-L669

However, what exactly is the problem scope: initial assignment only or any case of reconfiguration? in the latter case we miss state clear and other things...

**Comment by AdSchellevis** [comment]
I think the issue is initial configuration (at least in my case), in which case it makes sense to prevent `interfaces.php` from removing addresses for "tunnel type" interfaces, which happens to be an overlapping set with previously un-configured. Both approaches do have downsides, but in edge-cases. 

For example when there is a manually configured interface on the console and one starts to use it from the gui, addresses might "stick", same is possibly the case when configuration and assignments are mixed (race between assignment page and interface configuration).

Looking for tunnel interfaces has the downside of being specific, although doesn't come with possible race conditions. 

Personally I don't have a strong preference, both methods will have some sort of side affects, but are better than what is being performed now.

When it comes to where the logic should live, I don't know, `interface_bring_down()` is pretty convoluted due to the passing of `$ifacecfg` for only the `interfaces.php` case.  In principle https://github.com/opnsense/core/commit/74a4c1a7f4b80c9e547ec70b169427f60c6a26cd would prevent removal of the address as well, at a first glance I don't think it matters a lot that this will also be the case when `interface_bring_down()` is being called from other areas, although it feels a bit odd to ask for removal and then just don't do it, which is why I moved it on top to the configuration page (also less likely to have other regressions).

**Comment by fichtner** [comment]
I don't know about and trade off between side effects. More context presents 61500f6790969 which isn't that old actually and fixes stripping of addresses where configuration is not set/required. So interface_configure() already does the proper job since 22.1.3 so the question is what the goal post is if we look at an "oddity" that was always the case prior and now is slowly being reworked in a better way.

interfaces.php seems to be the wrong page to fix "initial" configuration. it does the correct job it is required to do with 74a4c1a and assignment doesn't call "bring down" initially.

We might want to talk about enabling interfaces where bring_down isn't required, but I don't think low level logic as ipaddr/ipaddrv6 shouldn't be moved to this page to prevent interface_bring_down().

**Comment by fichtner** [comment]
Done in 22.7.3.
