### ISSUE TITLE
Web Proxy

### ISSUE THREAD

**Issue by mamik-1** [opnsense/core#5958]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x ] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x ] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**

I need to add some custom parameters to squid.
I tried to add a "squid.conf.local" file, inside the squid folder, with the required custom parameters, but the file is ignored by squid (the custom parameters don't appear in the squid log).
If I add the same custom parameters to "squid.conf", they are accepted by squid (they appear in the squid log). The problem with this approach is that, every time I make a change in "Web Proxy" UI, the custom parameters are erased from "squid.conf" file.

**Describe the solution you like**

Add a "Custom Parameters" field in "Web Proxy" UI.

**Describe alternatives you considered**

Having squid (Web Proxy) recognize the "squid.conf.local" file, inside squid folder. 

**Additional context**

I already posted this request on the OPNsense's official forum:

https://forum.opnsense.org/index.php?topic=29860.0

**Comment by mimugmail** [comment]
What about the include folders  in squid.conf. Not enough for this case?

**Comment by mamik-1** [comment]
> What about the include folders in squid.conf. Not enough for this case?

Hello and thank you for trying to help me.
I'm not sure if I understood correctly, but are you suggesting to make a modification to the "squid.conf" file?
Modifying the "squid.conf" file directly (through SSH) is undesirable, because every time you make a change in "Web Proxy" UI, all the custom parameters are erased automatically.
This is reason for my feature request.

**Comment by mimugmail** [comment]
Have a look at squid.conf file, there are 2 static forderst where you can Placebo2any static *.conf  :)

**Comment by AdSchellevis** [comment]
forum post where to place files https://forum.opnsense.org/index.php?topic=6516.msg28049#msg28049 and reasons why plain text input won't be included in the ui : https://docs.opnsense.org/development/guidelines/basics.html#safeguard-user-input

**Comment by mamik-1** [comment]
Thank you very much, to both of you @mimugmail @AdSchellevis.
I searched around about my issue, but didn't find that OPNsense's forum topic, during my search, so thank you @AdSchellevis 
@AdSchellevis @mimugmail Is there any preferable folder to put my custom .conf file? I come from PFsense, where almost everything is done in the UI, so I'm not sure what's the correct folder to put my file in.
As far as my feature request being denied, I understand @AdSchellevis , you (OPNsense team) want to avoid future headaches. But would be nice to have a "Custom Parameters" field in the Web Proxy UI :)

**Comment by mamik-1** [comment]
Sorry for the late reply.
As the inclusion of a "Custom Parameters" field in Web Proxy UI is not possible/desired and the workaround purposed on that OPNsense's forum post works, I will close this issue.
Thank you very much @mimugmail and @AdSchellevis , for your help.
I would also like to thank, again, to all OPNsense team, for providing and supporting such awesome software.
