### ISSUE TITLE
[RFE] XMLRPC: Special characters should be preserved

### ISSUE THREAD

**Issue by fraenki** [opnsense/core#596]
I've just noticed that special characters are removed everywhere when using XMLRPC to sync the OPNsense configuration to a secondary node. This is especially true for all sorts of descriptions (rules, aliases, virtual IPs).

Example:
- primary node rule description: `Test: This is a (test) description`
- secondary node rule description: `Test: This is a test description`

I would expect the XMLRPC sync to push a (almost) unmodified configuration instead.

This is by all means a low priority issue. This [bug report](https://redmine.pfsense.org/issues/960) was likely the reason to strip special characters, but maybe with recent technology this is no longer an issue.

**Comment by AdSchellevis** [comment]
remove_special_characters seems to be the root of all evil here, it should either leave if the xmlrpc lib is doing the escaping or do the normal escape sequence on all entries.
