### ISSUE TITLE
IPsec remote access clients (mobile) get no routes when vpn establishes

### ISSUE THREAD

**Issue by ee19** [opnsense/core#5960]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [ x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x ] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

IPsec remote access clients (mobile config, macOS IPsec-Client) get no routing information after the vpn is established. 
Even if "Provide a list of accessible networks to clients" in "Mobile Clients" is activated. 
In OPNsense 22.7 (and 22.7_4 or 22.7.1) the strongswan.conf has no "subnet" and "split-include" attributes in the plugins section.

In 19.1.10 (where i came from) the "subnet" and "split-include" attributes existed, and the IPsec client had routes for all phase-2 entries after activating the vpn. The upgrade was done via new installation and config restore.
I rolled back to 19.1.10 and configured it from scratch, to be sure it worked. 
I did not try 21.1.x, because someone in the forum mentioned it still worked there (see below).

Steps to reproduce:
1. Configure IPsec remote access vpn with one or more phase-2-entries and 
2. switch on "Provide a list of accessible networks to clients" in "Mobile Clients"
3. Control the routes before and after activating the vpn

After activating the vpn the IPsec-Client should have routes for the via vpn connected networks.

**Describe alternatives you considered**

A workaround is right now to copy the old strongswan.conf into /usr/local/etc/strongswan.opnsense.d/ and reboot.
It is mentioned in the forum:
https://forum.opnsense.org/index.php?topic=29798.0
https://forum.opnsense.org/index.php?topic=29872.0

**Screenshots**

**Relevant log files**

If applicable, information from log files supporting your claim.

**Additional context**

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 22.7.1-amd64
VMware-VM
vmx interfaces
ESXi-Version:
7.0.3

**Comment by fichtner** [comment]
Looks to be another side effect of 416687de49d8cf3a54 -- assigning @AdSchellevis

**Comment by AdSchellevis** [comment]
could be, best check if phase 1 is marked as mobile, which should be the case for this to work.
<img width="512" alt="image" src="https://user-images.githubusercontent.com/9783985/185052669-9a1c0ca3-63cb-4090-b189-42f027a49986.png">

The logic in https://github.com/opnsense/core/commit/416687de49d8cf3a54f9d34e748fea56d00b478b looks good to be honest, provided `$net_list` is missing here

https://github.com/opnsense/core/blob/e58d7de7d4090524aa7e6f09900b77c43dbd820f/src/etc/inc/plugins.inc.d/ipsec.inc#L1048

**Comment by AdSchellevis** [comment]
Missing feedback, nothing todo here at the moment. can reopen later if needed,

**Comment by sstaible** [comment]
> could be, best check if phase 1 is marked as mobile, which should be the case for this to work. <img alt="image" width="512" src="https://user-images.githubusercontent.com/9783985/185052669-9a1c0ca3-63cb-4090-b189-42f027a49986.png">
> 
> The logic in [416687d](https://github.com/opnsense/core/commit/416687de49d8cf3a54f9d34e748fea56d00b478b) looks good to be honest, provided `$net_list` is missing here
> 
> https://github.com/opnsense/core/blob/e58d7de7d4090524aa7e6f09900b77c43dbd820f/src/etc/inc/plugins.inc.d/ipsec.inc#L1048

The logic in the code looks wrong to me as $ph1ent is not set to the correct phase 1 entry at this point in the code. (It is set to the last phase 1 entry but not necessarily the one associated with the phase 2 entry)

I have the same issue as the person that opened the ticket and when I remove all but the first phase 1 (mobile client) entry in my config, the subnet information from phase 2 is correctly applied to strongswan.conf.

**Comment by AdSchellevis** [comment]
@sstaible you're right, I can only fix this for 23.1.x, https://github.com/opnsense/core/commit/296344f6f5afa7453fce79a5ac492e07b28b7d48 should do the trick here.
