### ISSUE TITLE
Inactive Items Time Zone and Language

### ISSUE THREAD

**Issue by ElitConcept** [opnsense/core#5961]
I upgraded from 2.1 to 2.7 and since :
Now the items : “Time Zone”, “Language” and “Theme” are inactive.
An update to version 2.7.1 did not change anything.
![Capture](https://user-images.githubusercontent.com/111413519/185048250-6e09a15d-07c9-490f-a41e-54512df42915.JPG)

**Comment by fichtner** [comment]
They are not inactive, they are gone. This cannot happen. Check your browsers and addons, antivirus and stuff...

**Comment by ElitConcept** [comment]
You're totally right !
Older versions of Firefox browser are no longer compatible with Opensense 2.7 while it worked with Opensense 2.1.
The systems on which we work are of course not connected to the Internet and as long as a tool meets the need, there is no reason to make it evolve at the risk of encountering problems on very sensitive systems.
Thanks for your intervention.

**Comment by fichtner** [comment]
It might be the removed IE support that is a “problem” here, probably the last thing still in support until the first half of this year, much longer than the firefox you are using (likely version 3 or so).

thanks for confirming.
