### ISSUE TITLE
Firewall / Diagnostics / Sessions - Rule Selection - Incorrect results

### ISSUE THREAD

**Issue by greggitter** [opnsense/core#5962]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x ] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x ] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

Using the diagnostics for the firewall to view what host sessions are active via firewall rules allowing egress from VLAN to LAN, the results with the rule selected are sometimes wrong.  In my situation, the first rule shows no results (probably correct).  The second rule shows incorrect results.  In fact, I can't find a rule that specifically applies to the data shown at all.

In this situation, I have one alias group on the VLAN (172.20.110.190-196) allowed access to one host on the primary LAN (172.20.100.202).  The results show completely unrelated hosts...see screenshots; note the rule selection in the first screenshot, and the rule definition in the second.

![Sessions](https://user-images.githubusercontent.com/68356047/185183379-21dcf44e-5b2e-440f-a3d0-370d0cddabe6.jpg)
![Rule](https://user-images.githubusercontent.com/68356047/185183413-4f00f8b6-763f-47ae-8ea5-6ac5d198fd93.jpg)

None of the destinations in the screenshot are local, the source IPs are all IP cams.  I don't see any reason these particular hosts would be displayed, they are not part of an alias group, nor are they part of any other firewall rule.  Also, some rule selections DO show proper host connections, while others (in addition to this one) are similarly wrong.

**To Reproduce**

1. I did clone a rule prior to seeing this problem (not sure if the problem was there prior).  The rule was cloned, renamed and host name changed.
2. Save/Apply the modified rule clone.
3. Use the Firewall / Diagnostics / Sessions to view sessions with that rule name

**Expected behavior**

I would expect sessions related to the rule in question, verified by IP addresses coinciding properly.

**Describe alternatives you considered**

N/A

**Screenshots**

Above.

**Relevant log files**

N/A

**Additional context**

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 22.7.1-amd64
FreeBSD 13.1-RELEASE
OpenSSL 1.1.1q 5 Jul 2022

**Comment by AdSchellevis** [comment]
easiest way to check if the gui is reporting anything wrong is to list the states and check the labels.

To dump the states via the console use:
```
/sbin/pfctl -vvPsr
```

The  label (serials) refer to the rule id's which can be shown using the question mark button in the header row:

<img width="239" alt="image" src="https://user-images.githubusercontent.com/9783985/185203518-3e278870-4c41-4c3d-bb54-1118b513395d.png">

**Comment by greggitter** [comment]
OK, so I was able to see the specific rule ID and outputs as follows:

```
root@opnsense:~ # /sbin/pfctl -vvPsr | grep '9525a2784f0babf6397b9480271e797b'
No ALTQ support in kernel
ALTQ related functions disabled
@123 pass in quick on igb0_vlan10 inet proto tcp from <Amazon_Echo_Group:3> to 172.20.100.214 port = 80 flags S/SA keep state label "9525a2784f0babf6397b9480271e797b"
@124 pass in quick on igb0_vlan10 inet proto udp from <Amazon_Echo_Group:3> to 172.20.100.214 port = 80 keep state label "9525a2784f0babf6397b9480271e797b"
```
So this confirms the GUI looks wrong for sessions/states WHEN this rule is selected in the filter drop-down...?  These labels do correspond to the rule as I described them and the screenshot above.  And as far as I can tell, the output on the sessions and states screens appears to be wrong information as displayed in the GUI.  Or am I missing something?  Thanks!

**Comment by AdSchellevis** [comment]
my mistake, now you have the numbers (@123, @124), the states link to those:
```
/sbin/pfctl -vvs state
```

look for lines ending with `, rule 123` or `, rule 124`

Please keep in mind that a filer reload changes the numbers, after which the references are "unstable"

**Comment by greggitter** [comment]
Searching for those rules, they do not exist.  That is expected.

```
root@opnsense:~ # /sbin/pfctl -vvs state | grep 'rule 123'
No ALTQ support in kernel
ALTQ related functions disabled
root@opnsense:~ # /sbin/pfctl -vvs state | grep 'rule 124'
No ALTQ support in kernel
ALTQ related functions disabled
```
Is there anything else I can verify?  Also, what is a "filer reload"?  And by unstable, you mean they change but aren't unstable...?  :)

**Comment by AdSchellevis** [comment]
filter reload I meant. rule numbers aren't guaranteed the same after reloads, which means the rule labels aren't guaranteed the same either. if these rule numbers aren't found, it's probably best to search for an item in the list and check what the whole section looks like for `/sbin/pfctl -vvs state`

**Comment by greggitter** [comment]
OK, I'm a bit confused what you want me to do.  Do you want me to verify some of the data is displaying correctly?

Back to the GUI (for clarification), some in the rules drop-down list are displaying proper states/sessions.  For example, the third entry I have allows VLAN DNS resolution to a resolver on the primary LAN...that data is correct.  But apparently rules 123/124 there are no active states which is expected, but there is "garbage" data showing up in the results (screenshot in first post).  I guess I see that as the bug...?  The incorrect lines shown in the screenshot are handled by a VLAN to ANY rule...I have no specific rule for those listed hosts...they shouldn't show up in that screen shot for that selected rule.

**Comment by greggitter** [comment]
Or is the problem that these particular connections are long-lived states and when the state is created, that's when the rule number is assigned?  And thus, the state table would need to be flushed for this to all work?  And then it works until a rule (filter) changes and then it's all "unstable"/potentially wrong again?  If that's the case then...yeah...that's a problem.

**Comment by AdSchellevis** [comment]
I was interested if you could find some of the problematic states in the gui and the matching output of pfctl. If there is an issue  merging the datasets, I would expect there's a parsing issue merging the rule numbers in some way.

Let me give an example of what I'm looking for with output (which matches) on my machine:

The gui states:

<img width="1453" alt="image" src="https://user-images.githubusercontent.com/9783985/185219943-1bdd4db7-7ac0-4fb9-9003-c24952bafdef.png">

Now I'm executing `/sbin/pfctl -vvs state | less`  to search for `10.37.132.1:49460`, this results in:

```
all tcp 10.37.132.100:22 <- 10.37.132.1:49460       ESTABLISHED:ESTABLISHED
   [1096929984 + 1878983168] wscale 7  [1640271468 + 256] wscale 6
   age 01:32:36, expires in 24:00:00, 755:820 pkts, 52857:205889 bytes, rule 113, source-track
   id: 6694fa6200000003 creatorid: a2e0f312 gateway: 0.0.0.0
   origif: le0
```

Now searching the rule again, seems to match on the expected rule (for me) (`/sbin/pfctl -vvPsr | grep '@113'`):

```
@113 pass log quick on **redacted** label "85d6857423b92d5835367845eaa8df38"
```


As long as the ruleset isn't reloaded (for some reason), the numbers remain the same, but on a reload (for example when using schedules), the link is less relevant (more likely wrong).

**Comment by greggitter** [comment]
Applied today's update, rebooted and as expected, no data is "misplaced" as described above.  So I guess this is "by design"?  I seem to remember labels aren't included in pf...so I guess that's the limitation?  Again, thanks!

**Comment by AdSchellevis** [comment]
sure, no problem, let's close this issue. not much currently can change here I guess.
