### ISSUE TITLE
where did the config syshook go

### ISSUE THREAD

**Issue by s0mm3rb** [opnsense/core#5968]
I am trying to run a script on config change event

but I am not sure how to accomplish this

either this guide is incomplete, or I am missing something obvious
[https://docs.opnsense.org/development/backend/autorun.html](https://docs.opnsense.org/development/backend/autorun.html)

it clearly states a `config` folder, to trigger `scripts used when a configuration change took place`
but that folder does not exist
I created it and put a script in there `50-user-changed.sh`
but it is not executed
to verify it is running I simply write a new line to the new log `/var/log/audit/user-change_$DATE.log`
no log is created

I see the trigger logs at ` /var/log/configd/latest.log`
```
... - [meta sequenceId="10"] [...] User test changed
... - [meta sequenceId="11"] [...] trigger config changed event
```

how can I trigger my script on this event
if I understand the guide correct, it should be as simple as putting the script in the folder and of it goes?
what am I missing?

`ll` output from that folder
```
# ll /usr/local/etc/rc.syshook.d/config/
total 4
-rwxr-xr-x  1 root  wheel  108 Aug 21 01:58 50-user-changed.sh*

```
thank you

**Environment** OPNsense 22.7.2-amd64

**Comment by fichtner** [comment]
"config" dir is not created by default, but can always be using a simple `mkdir`. So far the only hook exists in os-git-backup plugin, but the facility should work. Might want to compare your script to plugins.git/sysutils/git-backup/src/etc/rc.syshook.d/config/10-git-backup to see if maybe the handling is wrong.


Cheers,
Franco

**Comment by s0mm3rb** [comment]
not sure what changed since yesterday (other than a system reboot) but it works now

should not need a reboot imho but I guess the old "off and on again" did the trick
