### ISSUE TITLE
Feature request for Aliases UI

### ISSUE THREAD

**Issue by PanMat** [opnsense/core#5973]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [*] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [*] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**

A clear and concise description of what the problem is including your motivation for the request,
i.e. "For the purpose of [...] I am missing a solution that will [...]."

"Yes, the current UI for "Aliases" can be made more intuitive and user friendly. Especially with IoTs, it is hard to remember what 192.168.23.37 or Wans_camera means."

**Describe the solution you like**

(e.g. I would like an input field in the `/ui/firewall/alias` which would add .... to ....)

"If its possible to add some comment against aliases (like "front gate camera")  then it would helpful for ongoing maintenance and up keeping of the firewall."

**Describe alternatives you considered**

A clear and concise description of any alternative solutions or features you considered.

"None so far and this is more like a feature request"

**Additional context**

Add any other context or screenshots about the feature request here or links to relevant forum thread or similar
"None"

**Comment by maurice-w** [comment]
You can enter a description. Isn't that exactly what you're looking for?

**Comment by PanMat** [comment]
Here is a brief description of my dilemma and keep in mind that it could just be a bad design of topology at my end or my inability to remember things :-)

Lets say I've a VLAN of IoTs with about 100-150 gadgets of various form factors. Of these many are flashed with ESPHome so do not really need outside access for anything but there are many (like cameras, switches, OEM branded equipment) that needs access to WAN for various things like firmware updates or even core functionality.

So regardless of the default VLAN policy for IoTs (deny all or allow all), I find myself managing an alias of about 30-40 IP addresses to manage exception to the default rule.

So the description filed does not help much here as I constantly find myself looking over other tabs to see what a particular IP might represent in this context within the alias.

**Comment by kulikov-a** [comment]
@PanMat Hi! technically you could try using a "Network group" type alias: create separate "Host(s)" type aliases for each device with the desired description and then combine them into a "Network group" alias for use in rules

**Comment by PanMat** [comment]
I was not using Network Groups so had to read the documentation and few examples online. It is a great feature and rightly solves my problem at hand and in fact gives more flexibility than I originally envisioned!

Thanks for your patience and for pointing me in the right direction!
