### ISSUE TITLE
Interfaces Overview: DHCPv6 Reload / Release / Renew buttons missing

### ISSUE THREAD

**Issue by maurice-w** [opnsense/core#5974]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

When the IPv6 configuration type of an interface is set to DHCPv6, but the IPv4 configuration type is _not_ set to DHCP, no 'DHCP Reload / Release / Renew' buttons are shown in 'Interfaces: Overview'.

**To Reproduce**

1. Go to 'Interfaces: WAN', set 'IPv4 Configuration Type' to DHCP and 'IPv6 Configuration Type' to DHCPv6, save & apply.
2. Go to 'Interfaces: Overview', click on 'DHCP Release'.
3. See result: Both IPv4 and IPv6 addresses get released.
4. Go to 'Interfaces: WAN', set 'IPv4 Configuration Type' to 'Static IPv4' or 'None', save & apply.
5. Go to 'Interfaces: Overview', see error: 'DHCP Reload / Release / Renew' buttons are missing.

**Expected behavior**

DHCPv6 reload / release / renew feature should be available for interfaces without DHCPv4.

**Additional context**

There is code in `status_interfaces.php` to display dedicated buttons for DHCPv6:
https://github.com/opnsense/core/blob/f609a9cbb1a814023fc4d019a8abc65955a02d8e/src/www/status_interfaces.php#L141-L153
But there is no code in `get_interfaces_info()` which would actually return 'dhcp6link' information.

**Environment**

OPNsense 23.1.a_102 (amd64, OpenSSL)
Hyper-V Gen2 Ver10.0

**Comment by fichtner** [comment]
Caveat as per commit message 0592276. We could move the thing "up" to the status and just show a link type thing (dhclient and dhcp6c up indicator). SLAAC also missing. Maybe you want to give it a try.

**Comment by maurice-w** [comment]
Thanks @fichtner, mostly works. Except for the DHCPv6 "Release" button not switching to "Renew" after a release. We don't actually kill dhcp6c, so get_interfaces_info() always returns dhcp6link = up. Might have to find another way to determine DHCPv6 state.

Of course it would be nice if we could reload / release / renew DHCPv4 and DHCPv6 independently, but that's probably quite a bit of work.

**Comment by fichtner** [comment]
@maurice-w I can offer f3b51b3 for the status mismatch

In theory interface_bring_down() could split between IPv4 and IPv6 but might end up tearing the other one down as well as a side effect if one is connected over the other. For interface_configure() I think we should stay clear of partial reconfiguration so we would end up restarting the other one as well anyway even if it wasn't killed before.

According to the code here we could make the IPv4/IPv6 individual "up" stay but simply move the buttons to the "link" state in order to manage expectations about what would happen. I'll think about it some more.


Cheers,
Franco

**Comment by maurice-w** [comment]
@fichtner, may I suggest maurice-w/core@a57f179?

**Comment by fichtner** [comment]
@maurice-w LGTM, want to create a PR or shall I cherry-pick this directly?
