### ISSUE TITLE
unbound: move advanced settings page to MVC/API, log-reply option etc.

### ISSUE THREAD

**Issue by fichtner** [opnsense/core#5978]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**

Static pages should go away eventually. For Unbound to move further find smallest impact page(s).

**Describe the solution you like**

Advanced page migration is easy and gives opportunity to add more features.

**Describe alternatives you considered**

Moving all to MVC is too much work, too many side-effects.

**Additional context**

https://github.com/opnsense/core/issues/5795 https://github.com/opnsense/core/issues/5256

**Comment by swhite2** [comment]
While at it, let's move https://github.com/opnsense/core/issues/5256 to this page as well.

Include `log-reply` conf option as well.
