### ISSUE TITLE
Missing translation - services_ntpd.php

### ISSUE THREAD

**Issue by DokuKaefer** [opnsense/core#599]
Line 280 and 283 (preffer and noselect)

**Comment by fichtner** [comment]
Note that these two words are ntpd config file tags that do not translate and might cause confusion in a non-English translation.

**Comment by fabianfrz** [comment]
@fichtner @DokuKaefer replace the text? "prefer this server" and "do not use this server"

**Comment by fichtner** [comment]
@fabianfrz Hmm, the help text already says that, but I think that changing it according to your suggestion and zapping the help text for both items is better. Or we leave it as is, making sure the translation for the labels matches the help text underneath.
