### ISSUE TITLE
Loss of connectivity after rebooting cable modem (bridge mode/DHCP WAN)

### ISSUE THREAD

**Issue by Yoshimi82** [opnsense/core#5997]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

I am using OPNsense in combination with a cable modem that is configured in bridge mode and provisioning a public IP to the router using DHCP. Whenever the modem is rebooted, or the network cable on the WAN interface of OPNsense is unplugged/plugged, connectivity remains lost. Only a reboot of the firewall fixes it (at least the quick and dirty way, maybe there are alternatives). This occurs in version 22.7.2, and did not occur earlier.

**To Reproduce**

1. Reboot cable modem or unplug WAN cable from firewall
2. Allow the modem to come back online
3. Check gateway status (showing as online again)
4. Verify connectivity (fails)

**Expected behavior**

WAN must be re-established after reboot of modem or loss of connectivity on ISP side, without action on the firewall.

**Describe alternatives you considered**

Did a fresh install of 22.7 and restoring the backup configuration. It works fine on this version. Rebooting the modem and/or plugging the WAN cable nicely restores connectivity.

**Screenshots**

N/A

**Relevant log files**

Please let me know what logs you need to troubleshoot. I can provide them.

**Additional context**

N/A

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 22.7.2-amd64
FreeBSD 13.1-RELEASE-p1
OpenSSL 1.1.1q 5 Jul 2022
Network Intel® I210-AT
PCEngines APU2D4

**Comment by Yoshimi82** [comment]
Thanks Franco, they might indeed be related! This response https://github.com/opnsense/core/issues/2517#issuecomment-1226649147 is actually close to what I am experiencing. If you need me to test and/or log anything, please let me know.

**Comment by fichtner** [comment]
@Yoshimi82 can you try on 22.7.3 first? I intend to work on  #2517 for 23.1 but not fully sure how too pull it off yet.

**Comment by Yoshimi82** [comment]
@fichtner good news! I have upgraded to 22.7.3_2 an hour ago, and can confirm this fixed it. Tested by both disconnecting/connecting the WAN cable as well as rebooting the modem. Thanks so much for your hard work on OPNsense!

**Comment by fichtner** [comment]
Ok close then? It was either 2de4658ef0c or 7aadb0159e75 :)

**Comment by Yoshimi82** [comment]
Yep, I will close it. Thanks again :)
