### ISSUE TITLE
Incorrect validation check on aliasses

### ISSUE THREAD

**Issue by sjorge** [opnsense/core#60]
http://i.imgur.com/7qPuFH3.png

alias name is less than 32 chars, only has a-z + . so should be valid!

**Comment by StopTrain** [comment]
I may be wrong on this, but I don't think the 'alias' can contain a dot.  I believe the error message is just the '.' is the ending period for punctuation on the sentence.  Looks to me it has to be a-z, A-Z, or _ (underscore)

**Comment by jschellevis** [comment]
Indeed that is what it says.. the . at the end is the end of the sentence. You cannot use a dot in the alias name. You may use an underscore though.

**Comment by fichtner** [comment]
I'll reopen this to at least tweak the underscore markup a wee bit. I can see others run into this as well... Doesn't hurt to make the description more concise.

**Comment by sjorge** [comment]
Maybe also look into why . can't be used. At first glance there should be no technical reason why not.

**Comment by sjorge** [comment]
Because I like living on the edge, I edited my alias to include dots. Looks like it works fine.
I am using it in a NAT and Firewall rule.

**Comment by sjorge** [comment]
OK so using '.' in an alias does indeed not work, pf rules set errors on $test.alias
Worked fine before because the rule set was already loaded, modifying and saving failed but appeared to work because the rule set did not get updated. So disregard that.

**Comment by sjorge** [comment]
Closing issue because the message is fixed in 15.1.7-openssl
