### ISSUE TITLE
Empty CRL causes fatal error on OpenVPN server check

### ISSUE THREAD

**Issue by Niikoneko** [opnsense/core#6001]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

In Version 22.7.3_2, if an OpenVPN server declares an empty CRL, no user can connect anymore. I included the logs in the appropriate section bellow.

*Tip*: to validate your setup was working with the previous version, use opnsense-revert (https://docs.opnsense.org/manual/opnsense_tools.html#opnsense-revert)

**To Reproduce**

1. Have an active OpenVPN server with some authorised users configured in distant access mode (SSL/TLS)
2. Create a new CRL on the OpenVPN server's CA
3. Do not add any certificate to the CRL
4. No authorised users can connect anymore
Notice : If the CRL isn't empty, the users that are not in the CRL can connect.

**Expected behavior**

Having empty CRL is usefull for administration to anticipate user's leaves or certificate comprimise but it is not possible anymore. This problem is not present in version 22.7.0 (appeared with the update).

**Describe alternatives you considered**

A false user must be created and revoked in all CRL for a CRL to be declared in an OpenVPN server to ensure the CRL is not empty.

**Screenshots**

NA

**Relevant log files**

> 2022-09-02T15:13:37 | Error | openvpn | [WAN IP & PORT] Fatal TLS error (check_tls_errors_co), restarting |  -- | -- | -- | -- | --
> 2022-09-02T15:13:37 | Error | openvpn | [WAN IP & PORT] TLS Error: TLS handshake failed |  
> 2022-09-02T15:13:37 | Error | openvpn | [WAN IP & PORT] TLS Error: TLS object -> incoming plaintext read error |  
> 2022-09-02T15:13:37 | Error | openvpn | [WAN IP & PORT] TLS_ERROR: BIO read tls_read_plaintext error |  
> 2022-09-02T15:13:37 | Error | openvpn | [WAN IP & PORT] OpenSSL: error:1417C086:SSL routines:tls_process_client_certificate:certificate verify failed |  
> 2022-09-02T15:13:37 | Error | openvpn | [WAN IP & PORT] VERIFY ERROR: CRL not loaded

**Additional context**

NA

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 22.7.3_2-amd64
FreeBSD 13.1-RELEASE-p2
OpenSSL 1.1.1q 5 Jul 2022
Intel(R) Core(TM) i7-2600 CPU @ 3.40GHz (2 cores, 2 threads)
Network Unknown (VMWare Virtualized)

**Comment by bahnwaerter** [comment]
Your problem seems most likely related to the problem described in issue #6005.

To solve this problem you could try to update to OPNsense 22.7.5. Note that it is important to consider the [emergency instructions](https://twitter.com/opnsense/status/1577978745272557574) for existing OPNsense instances, otherwise you may not be able to access your instance via OpenVPN after the upgrade (as already [reported in a comment](https://github.com/opnsense/core/issues/6005#issuecomment-1272525186)):
> For those having trouble with OpenVPN CLRs on 22.7.5: Your CRL is empty and creation never rendered the binary format required for OpenVPN to accept the file. If OpenVPN is not working remove the empty CRL from the server configuration or add a mockup certificate to the CRL or add any certificate and remove it immediately after. All these things can instantly bring back your OpenVPN server. We will be sandboxing the CRL code further to avoid any of the issues seen on previous 22.7.x for good, but then also won't automatically fix currently broken CRLs.

**Comment by fichtner** [comment]
This has been addressed in 22.7.x
