### ISSUE TITLE
dhcpd.conf generated with wrong pool { } section

### ISSUE THREAD

**Issue by R000795** [opnsense/core#6006]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [ X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X ] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

I created a new vlan with a new pool for that interface. I got this in the log file:

`DHCPDISCOVER from xx:xx: via vlan01: network 172.16.119.0/24: no free leases`

Reason: incorrect generated dhcpd.conf

```
subnet 172.16.119.0 netmask 255.255.255.0 {
  pool {
    option domain-name-servers 172.16.100.30;
    range 172.16.119.100 172.16.119.200;
  }

  option routers 172.16.119.1;
  option domain-name-servers 172.16.100.30;
  default-lease-time 3600;
  max-lease-time 4000;

}

```
![image](https://user-images.githubusercontent.com/20793435/188464590-b82a11dd-d61c-4e52-85de-fc9a684e26b0.png)

**To Reproduce**

1. Go to https://opnsense.xxx.xx/services_dhcp.php?if=opt8
2. Enter a DNS server
3. Click on Save
4. Check /var/dhcpd/etc/dhcpd.conf

**Expected behavior**

A correct dhcpd.conf like this

```
subnet 172.16.119.0 netmask 255.255.255.0 {
  pool {
    range 172.16.119.100 172.16.119.200;
  }

  option routers 172.16.119.1;
  option domain-name-servers 172.16.119.1;
  default-lease-time 3600;
  max-lease-time 4000;

}
```

Software version:
OPNsense 22.7.3_2-amd64

**Comment by fichtner** [comment]
I don't know... adding "172.16.100.30" as a manual DNS server has you ending up with the DHCP configuration it is supposed to generate and not the one you want? As for the error I'm not sure how it's related to a bad DNS server hint.


Cheers,
Franco

**Comment by R000795** [comment]
Hi Franco,
I tried to reproduce this issue ("no free leases") and it's working as expected now ... I've no clue why it happened two days before, even after restarting the DHCPD service. So I'll close the issue and sorry!

Cheers, Lutz

**Comment by fichtner** [comment]
Hi Lutz,

It seems a strange error but happy it works now. I'll keep this in mind if somebody else reports this.


Cheers,
Franco
