### ISSUE TITLE
Responsive Design on Iphone

### ISSUE THREAD

**Issue by andreasvel** [opnsense/core#602]
Hi,
the Design doenst work right on a Iphone 6 (iOS 9.2)

Example: OPENVPN Client Export
neither to scroll / see all
neither to download the certificates to work on the iphone

**Comment by fichtner** [comment]
Can you be more specific about these with screen shots?

**Comment by fichtner** [comment]
Some tables just don't work very well yet. Some additions are coming with 16.1.16, but it will take help to get more fixes in for individual pages.

**Comment by L1ghtn1ng** [comment]
As we use bootstrap won't it be somewhat easier to use this?
<meta name="viewport" content="width=device-width, initial-scale=1">
