### ISSUE TITLE
Port forwards apply to all interfaces if destination=any

### ISSUE THREAD

**Issue by haarp** [opnsense/core#6021]
- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

Hello,

when a port forward is set with the destination field left at `any`, the forward will apply on unrelated interfaces. Observed thus:

- Port forward from WAN to internal:80 on LAN
- Unrelated machine on LAN net tries to reach foo:80 outside -> It either hits a timeout or hits the port forward target instead.

The port forward rule is as follows:

![jGC4efA](https://user-images.githubusercontent.com/781030/189962344-43d00709-b909-4af2-a6b6-f847318d0794.png)

If this rule is enabled, all LAN clients cannot reach their intended destination at dport 80 anymore. It's as if this rule also applied to the LAN interface, which is definitely not selected. The associated filter rule is correctly created on the WAN_DSL interface.

If the destination is set to the WAN_DSL address, everything works as it should.

**To Reproduce**

1. Appy port forward as shown above
2. Prepare for chaos :)

**Expected behavior**

A rule **must** only apply to the interface it was put on.

**Describe alternatives you considered**

I don't understand pf internals enough to figure out what's going on. If it can't be solved on the pf end, then the web interface should be smart about it. Disallow creation of such rules in the first place (e.g. by disallowing the destination field to be anything but the corresponding interface address). Or don't show the interface selector in the first place, when it is expected to be ignored.

**Screenshots**

See above

**Additional context**

The situation is made worse by the ability to select multiple interfaces in port forward rules. This will create floating rules, which will similarly affect more interfaces than were selected. Users with multi-WAN setups will select multiple WAN interfaces and leave destination=any, thinking they won't have to duplicate their port forwards anymore. Fatal mistake :)

I found #3718 which looks related. However, as I'm not using VLANs, I cannot say it's the same issue.

**Environment**

Software version used and hardware type if relevant, e.g.:
- OPNsense 22.7.4-amd64
- Intel(R) Celeron(R) J4125 CPU @ 2.00GHz (4 cores, 4 threads)
- A long evening spent debugging ;)

Thanks a lot!

**Comment by MarinBernard** [comment]
Hi,

> **Expected behavior**
> A rule must **only** apply to the interface it was put on.

Well, it's probably exactly what's happening there.

You write that when you enable the rule, _all LAN clients cannot reach their intended destination at dport 80 anymore_. I suppose their _intended destination_ is a public web server reachable via the `WAN_DSL` interface ?

If so, the firewall is acting as expected: client packets enter the firewall by the `LAN` interface, follow the default route to the Internet, and are about to leave by the `WAN_DSL` interface... except that your NAT rule rewrites their destination to an internal address. As a consequence all outgoing traffic on port 80 is redirected to the internal network, and never leaves your network.

**Comment by haarp** [comment]
I think I see. So basically NAT rules have the "Direction" flag implicitely set to "any"?

**Comment by marinbernard-pep06** [comment]
> I think I see. So basically NAT rules have the "Direction" flag implicitely set to "any"?

That was my hypothesis. However, after reading the man pages, it turns out it cannot be so. Port forwarding rules are rendered as `rdr` rules in the final pf config. According to the manual, `rdr` rules are always implicitly evaluated on inbound traffic, so my first idea was just wrong.

Hopefully, I got another: I noticed that your rule used system defaults for NAT reflection. Did you try to explicitly disable it and see what happens ? When NAT reflection is enabled, additional `rdr` rules are created to forward inbound traffic on internal interfaces. Since your forwarding criteria are so lax, NAT reflection may create additional catch-all `rdr` rules for any packet headed to `tcp/80` hitting internal interfaces.

**Comment by haarp** [comment]
@MarinBernard / @marinbernard-pep06 

Thanks for having a look at the docs. Very interesting. Especially

> rdr rules are always implicitly on inbound traffic

So I did some more testing and it turns out NAT reflection is indeed responsible for this behavior. Disabling ` Reflection for port forwards` fixes it. Comparing the rulesets reveals these rules being added with reflection:

```
nat on igc0 inet proto tcp from (igc0:network) to {192.168.137.54} port {80} -> (igc0) port 1024:65535
nat on lo0 inet proto tcp from (lo0:network) to {192.168.137.54} port {80} -> (lo0) port 1024:65535
rdr log on igc0 inet proto tcp from {any} to {any} port {80} -> 192.168.137.54 port 80
rdr log on lo0 inet proto tcp from {any} to {any} port {80} -> 192.168.137.54 port 80
```
