### ISSUE TITLE
Dual stack Routed IPsec (VTI) is not possible

### ISSUE THREAD

**Issue by trunet** [opnsense/core#6022]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [ ] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

This is follow up of https://github.com/opnsense/core/issues/4866 that was closed for some reason. Let me know if you want to reopen the other one and I can add related information there.

**Describe the bug**

I have 2 x phase2, one with ipv4 and the second with ipv6. ipv4 have reqid 1000, ipv6 have reqid 1.

if I enable ipv6 phase2, it removes ipsec1000 interface and create an ipsec1 only with ipv6 in it.

with ipv4 only enabled:
```
ipsec1000: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> metric 0 mtu 1400
	tunnel inet x.x.x.x --> y.y.y.y
	inet 172.16.0.130 --> 172.16.0.129 netmask 0xfffffffc
	groups: ipsec
	reqid: 1000
	nd6 options=29<PERFORMNUD,IFDISABLED,AUTO_LINKLOCAL>
```

with both ipv4 and ipv6 enabled:
```
ipsec1: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> metric 0 mtu 1400
	tunnel inet x.x.x.x --> y.y.y.y
	inet6 fd00::172:12a prefixlen 126
	inet6 fe80::6eb3:11ff:fe3c:3064%ipsec1 prefixlen 64 scopeid 0x12
	groups: ipsec
	reqid: 1
	nd6 options=21<PERFORMNUD,AUTO_LINKLOCAL>
```

as you can see with both enabled ipsec1000 vanishes.

Other side is a pfsense, and it works fine with other pfsense boxes. pfsense have both phase2 IPs set in a single interface as you can see here:
```
ipsec1: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> metric 0 mtu 1400
	tunnel inet y.y.y.y--> x.x.x.x
	inet6 fe80::f076:7b6d:b8e2:6a85%ipsec1 prefixlen 64 scopeid 0x9
	inet6 fd00::172:129 prefixlen 126
	inet 172.16.0.129 --> 172.16.0.130 netmask 0xfffffffc
	groups: ipsec
	reqid: 5001
	nd6 options=21<PERFORMNUD,AUTO_LINKLOCAL>
```

**To Reproduce**

1. Create a Phase 1 IPsec
2. Create 2 phase 2s, one IPv4 and one IPv6

**Expected behavior**

I should have one interface with both ipv4 and ipv6 IPs.

**Describe alternatives you considered**

Create 2 phase 1 with a phase 2 in each. Should work, not ideal.

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 22.7.4-amd64 OpenSSL 1.1.1q 5 Jul 2022
Intel(R) Atom(TM) CPU C2558 @ 2.40GHz (4 cores, 4 threads)

**Comment by AdSchellevis** [comment]
It should keep both interfaces, which is also the reason why every phase 2 has a unique reqid (visible in the gui), on my end it doesn't appear to remove one. If for some reason it can't find the tunnel as one of it's own it should log something

https://github.com/opnsense/core/blob/b9bdf760b883acbc24919abbdacf832cf90c820d/src/etc/inc/plugins.inc.d/ipsec.inc#L1829-L1834


Can you check if `System: Log Files: General` contains any useful messages after ipsec1000 has been removed?

**Comment by trunet** [comment]
As soon as I hit the apply after enabling the ipv6 phase2 (reqid 1) I get on the logs:

```
<13>1 2022-09-14T22:58:29+02:00 x.x.x.x configctl 30848 - [meta sequenceId="1"] event @ 1663189109.24 msg: Sep 14 22:58:29 x.x.x.x config[5201]: [2022-09-14T22:58:29+02:00][INFO] config-event: new_config /conf/backup/config-1663189109.199.xml
<13>1 2022-09-14T22:58:29+02:00 x.x.x.x configctl 30848 - [meta sequenceId="2"] event @ 1663189109.24 exec: system event config_changed
<13>1 2022-09-14T22:58:30+02:00 x.x.x.x opnsense 7442 - [meta sequenceId="3"] plugins_configure ipsec (1)
<13>1 2022-09-14T22:58:31+02:00 x.x.x.x opnsense 7442 - [meta sequenceId="4"] plugins_configure ipsec (execute task : ipsec_configure_do(1))
<11>1 2022-09-14T22:58:31+02:00 x.x.x.x opnsense 7442 - [meta sequenceId="5"] /usr/local/sbin/pluginctl: destroy interface ipsec1000
```

**Comment by trunet** [comment]
You gave me something to dig deeper here, I `var_dump($configured_intf);` from `ipsec_configure_vti()` and it only shows one interface even with both enabled.

**Comment by trunet** [comment]
I found the issue, it was because of the tunnel isolation on phase 1 being disabled. Now I have both interfaces up.

https://github.com/opnsense/core/blob/24aa099509abb34acebafeb2a061342c5496aa61/src/etc/inc/plugins.inc.d/ipsec.inc#L1734-L1744

Now, if tunnel is not isolated, why not imitate the behavior from pfsense and add both to the same interface?

**Comment by AdSchellevis** [comment]
> I think would be better for opnsense imitates the behaviour of pfsense and if not selected add additional phase2 as alias IPs on its single interface.

Either that or enforce a split for these cases, we'll take it under consideration.
