### ISSUE TITLE
94.247.141.0/24 range not bogon anymore

### ISSUE THREAD

**Issue by alejandroscf** [opnsense/core#6039]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

In the bogons file at https://pkg.opnsense.org/bogons/fullbogons-ipv4.txt still appears the range 94.247.136.0/21which is already at least partially [assigned.](https://apps.db.ripe.net/db-web-ui/lookup?source=RIPE&type=inetnum&key=94.247.141.0%20-%2094.247.141.255)

It would be great if it could be removed.

Thanks in advance.

**Comment by AdSchellevis** [comment]
Looks like ours need an update indeed, let's ask @fichtner to update with the next release.

**Comment by fichtner** [comment]
Not sure what to do: the authoritative file is https://www.team-cymru.org/Services/Bogons/fullbogons-ipv4.txt which doesn't have this range.

 https://pkg.opnsense.org/bogons/fullbogons-ipv4.txt wasn't updated since 2017 (the change indicates it's from 2021) which means that file can't have said change and also that file is not used by any modern release, maybe the last one was 17.x or 18.x.

The current URL is https://pkg.opnsense.org/FreeBSD:13:amd64/22.7/sets/bogons.txz which is now versioned...

**Comment by AdSchellevis** [comment]
@fichtner oops, my mistake, our active bogons doesn't contain this range indeed. @alejandroscf should likely update his OPNsense .

**Comment by alejandroscf** [comment]
I'm not using OPNsense. I report this in behalf of the owner of the IP range. Some servers or equipment are blocking traffic from our IPs and we are trying to remove the range from any block list. 
As some OPNsense with old versions sure are still running, if the old path (https://pkg.opnsense.org/bogons/fullbogons-ipv4.txt) could be updated it will help. Or if is not maintained any more and that versions have no support, maybe removing it from the repo would be possible, to avoid blocking legitimate traffic.

**Comment by AdSchellevis** [comment]
removing is problematic as some clients may end up in a "fetch loop", I've updated the both lists for now to avoid further issues.

**Comment by fichtner** [comment]
I don't think there is much relevancy in legacy installs still running this bogons file... It's been over 5 years here and even if this was a concern a much bigger concern is that some installs pre 2021 might have not updated their bogons file for different reasons and that's something we can't fix. Files go stale eventually to make upgrades more appealing.


Cheers,
Franco
