### ISSUE TITLE
Firewall/Log Files/Live View - missing data in gui when the amount of messages increases

### ISSUE THREAD

**Issue by AdSchellevis** [opnsense/core#6042]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

When a lot of rules are being logged on busy environments, live-log sometimes has issues keeping up.
Since we currently are not pushing filters to the backend, the browser has to take care of pulling and filtering, which will limit the capacity to what the browser is able to cope with.

Ideally we should increase the performance on the browser end or try to refactor the code to push filters to the backend, although the latter will be more difficult.

**To Reproduce**

Enable logging on all rules and filter for specific traffic, sometimes there are gaps in the results.

**Expected behavior**

-

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 22.7.4 (amd64, OpenSSL).

**Comment by AdSchellevis** [comment]
```
opnsense-patch 67d2233
```

**Comment by fichtner** [comment]
Will be in 22.7.6.
