### ISSUE TITLE
Add support to match Firewall rule on DSCP / DiffServ

### ISSUE THREAD

**Issue by rsipka** [opnsense/core#6045]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**

For better Policy routing, and overall firewall usability, please add feature to be able to match firewall rules on PF `tos` field (DSCP).

Similarly, `set-tos` (mark DSCP) PF option could be added as well. Marking for tos (DSCP) that is possible in BSD PF.

Opnsense at this moment supports only Priority matching/setting, which is L2. This is done by `priority` and `set prio` PF commands, and is possible to be controlled by "Match priority" and "Set priority" UI during firewall creation/edit.

L3 solution would be adding more flexibility.

**Describe the solution you like**

I would like to have an input field / select options in Firewall rule to both match and set DiffServ (DSCP) code, similar to an already existing options to match/set Priority (802.1p)

**Describe alternatives you considered**

No alternatives

**Additional context**

From manual of [FreeBSD PF](https://www.freebsd.org/cgi/man.cgi?pf.conf(5)):

Matching:
```
     tos <string> | <number>
	   This	rule applies to	packets	with the specified TOS bits set.  TOS
	   may be given	as one of critical, inetcontrol, lowdelay, netcontrol,
	   throughput, reliability, or one of the DiffServ Code	Points:	ef,
	   va, af11 ...	af43, cs0 ... cs7; or as either	hex or decimal.

	   For example,	the following rules are	identical:

		 pass all tos lowdelay
		 pass all tos 0x10
		 pass all tos 16
```

Setting:
```
     set-tos <string> |	<number>
	   Enforces a TOS for matching IP packets.  TOS	may be given as	one of
	   critical, inetcontrol, lowdelay, netcontrol,	throughput,
	   reliability,	or one of the DiffServ Code Points: ef,	va, af11 ...
	   af43, cs0 ... cs7; or as either hex or decimal.
```

Such solution would allow us to set Routing Policies on DiffServ code (L3), not only on Priority (L2)

**Comment by AdSchellevis** [comment]
@rsipka no promises, but I might take a look at this. Out of curiosity, could you explain a bit more about your use-case?

**Comment by fichtner** [comment]
I know this has been asked before. tos/set-tos are supported by normalization (scrub) rules already.


Cheers,
Franco

**Comment by rsipka** [comment]
@AdSchellevis My use case is, that I have 2 internet providers, having Multi-WAN and want to Policy Route based on DSCP flag. For example, one provider is via WiFi connection, that is faster, but latency and packet loss can occur quite regularly. On the other hand, second provider is via VDSL, which is slower, but much more stable.

In Windows environment, you can mark DSCP packets via powershell, for example: `New-NetQosPolicy -Name "SSH" -AppPathNameMatchCondition "ssh.exe" -DSCPAction 46`, so matching for DSCP value would allow routing packets from different applications via different WANs. 
> Note: there is also an `New-NetQosPolicy` parameter `-PriorityValue8021Action`, which is L2 Priority, and doesn't work as expected - thus, DSCP on Layer 3 is in the end my only viable option at this moment.

@fichtner yes, and I saw those questions & answers, but unfortunately, normalization doesn't do what I want to accomplish - it simply "normalizes" the traffic from source/destination, and you can add DSCP code there - to all traffic is then sharing the same code. However, this doesn't work when you want to send packets with various DSCP (either none or any other code) from single source.

I wanted to also notify that there is already an "option set" in Normalization PHP page for DSCP mark, which could be re-used for firewall match/set rules?

**Comment by fichtner** [comment]
Looks like we don't support `tos` at all, a bit unexpected. I would make sense to add it in firewall rules. Some of this is really fragmented though... `set-prio` is in firewall rules, `set-tos` in normalization rules, `prio` is in firewall rules and `tos` does not exist anywhere yet.


Cheers,
Franco

**Comment by AdSchellevis** [comment]
It looks a bit inconsistent indeed, adding (set) tos to the firewall rules would   make sense, I don't think we should try to make this more consistent the other way around (`set prio` is likely also available for `scrub`) as scrubbing is already a subset of filter properties. I don't expect many people will use `set prio` any way, as in our case it only seems to be relevant when the rule matches on a vlan:

> ...If the  packet is transmitted on a [vlan(4)](https://www.freebsd.org/cgi/man.cgi?query=vlan&sektion=4&apropos=0&manpath=FreeBSD+13.1-RELEASE+and+Ports) interface, the queueing priority will be written as the priority code point in the 802.1Q VLAN header....

On OpenBSD the priority field is likely more usable as they support both queueing and the `match` keyword.

Currently we only support tos/DiffServ matching on the shaper, it does make sense to add it to the firewall rules as well indeed.

**Comment by AdSchellevis** [comment]
https://github.com/opnsense/core/commit/a002251146709a34eebf294bff076a3329253698 adds the tos keyword to the rules, `set-tos` is only available for `scrub` rules, which already offer the capability indeed.

**Comment by rsipka** [comment]
Hello, 
Thanks **A LOT** for such a quick modification!

Testing it, however, it throws an error:
`Match TOS/DSCP value invalid.`

Testing more, it seems that `$pconfig['tos']` is **always** converted to lowercase where `get_tos_values()` return some fields as upper case - for example all the hexa codes and "EF" vs "ef" in `tos` field.

In `src/www/firewall_rules_edit.php`:
```php
    if (!empty($pconfig['tos']) && !in_array($pconfig['tos'], get_tos_values())) {
        $input_errors[] = gettext('Match TOS/DSCP value invalid.');
    }
```

I don't know the source code very well, but if my presumption is correct, it could be changed to something like that:
```php
    if (!empty($pconfig['tos']) && !in_array($pconfig['tos'], array_map('strtolower', get_tos_values()))) {
        $input_errors[] = gettext('Match TOS/DSCP value invalid.');
    }
```

I have tested this (=applied patches to temporary test it) on my home firewall and with the above change it works like a charm.

**Comment by AdSchellevis** [comment]
@rsipka can you try https://github.com/opnsense/core/commit/7c0db67577b5ccba64aa4ea20248b3a12f9571c6 ?

**Comment by rsipka** [comment]
@AdSchellevis works well! Thanks a lot!

**Comment by haarp** [comment]
@AdSchellevis This is great and allows for some cool use cases that have nothing to do with QoS itself. Thanks! I've written a short howto on using it for policy routing: https://www.reddit.com/r/OPNsenseFirewall/comments/y1jdlp/quick_howto_marking_packets_for_policy_routing/

Would it be possible to implement this for NAT rules aswell? Because NAT rules are evaluated before filter rules, there's no way to match DSCP in NAT cases. My specific use case is intercepting/redirecting DNS (port forward rule) based on the DSCP tag.
