### ISSUE TITLE
Unbound API - Query forwarding

### ISSUE THREAD

**Issue by ansibleguy** [opnsense/core#6047]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

The API management of 'Query Forwarding' is not working as expected/documented.

API References:
- https://docs.opnsense.org/development/api/core/unbound.html
- https://github.com/opnsense/core/blob/master/src/opnsense/mvc/app/models/OPNsense/Unbound/Unbound.xml

There is a 'type' switch that does nothing - it will always use 'dot' (_DNS-over-TLS_) as type.

```xml
<type type="OptionField">
  <Required>Y</Required>
  <default>dot</default>
  <OptionValues>
    <dot>DNS over TLS</dot>
    <forward>Forward</forward>
  </OptionValues>
</type>
```
Here is the type as seen in the 'get' response:

```json
{"type":{"dot":{"value":"DNS over TLS","selected":0},"forward":{"value":"Forward","selected":1}}
```

If one does try to set the 'type' to 'forward' - as seen in the documentation - it does create a 'dot' item.

```
REQUEST: POST | HEADERS: '{'Content-Type': 'application/json'}' | URL: https://FW/api/unbound/settings/addForward | DATA: {'dot': {'type': 'forward', 'enabled': 1, 'domain': 'tmp.at', 'server': '1.1.1.1', 'port': 53}}
RESPONSE: {'status_code': 200,... '_content': b'{"result":"saved","uuid":"..."}'}
```

The commit this behaviour changed seems to be the following one: https://github.com/opnsense/core/commit/6832fd75a0b41e376e80f287f8ad3cfe599ea3d1#diff-a3952cd78b5ddaabed637d6331fbd16ec8f4d04bba06f6689b991493156fb66e

Currently the 'type' can only be set using the '**Referer**' http-header.

**BUT** it does only work when targeting the undocumented '[add|set|del]Dot' API endpoint.

Per example:
```
# this request creates an item of type 'dot'
REQUEST: POST | HEADERS: '{'Referer': 'https://FW/ui/unbound/forward', 'Content-Type': 'application/json'}' | URL: https://FW/api/unbound/settings/addForward | DATA: {'dot': {'type': 'forward', 'enabled': 1, 'domain': 'tmp.at', 'server': '1.1.1.1', 'port': 53}}
# this one successfully creates an item of 'type' forward
REQUEST: POST | HEADERS: '{'Referer': 'https://FW/ui/unbound/forward', 'Content-Type': 'application/json'}' | URL: https://FW/api/unbound/settings/addDot | DATA: {'dot': {'type': 'forward', 'enabled': 1, 'domain': 'tmp.at', 'server': '1.1.1.1', 'port': 53}}
```

**To Reproduce**

1. Create an API key in 'System - Access - Users'
2. Replace 'API_KEY', 'API_SECRET' and 'FW' in the following commands
3. Try creating a query-forwarding using the documented way:
  The item will be created in 'Services - Unbound DNS - DNS over TLS'
  ```bash
  curl -u API_KEY:API_SECRET https://FW/api/unbound/settings/addForward -H "Content-Type: application/json" -d '{"dot": {"type": "forward", "enabled": 1, "domain": "tmp.at", "server": "1.1.1.1", "port": 53}}' --insecure
  ```

4. Try creating a query-forwarding when adding the 'Referer' header
  The item will be created in 'Services - Unbound DNS - DNS over TLS'
  ```bash
  curl -u API_KEY:API_SECRET https://FW/api/unbound/settings/addForward -H "Content-Type: application/json" -H "Referer: https://FW/ui/unbound/forward" -d '{"dot": {"type": "forward", "enabled": 1, "domain": "tmp.at", "server": "1.1.1.1", "port": 53}}' --insecure
  ```

5. Successfully create a query-forwarding adding the 'Referer' header and using the 'addDot' API endpoint (undocumented)
  The item will be created in 'Services - Unbound DNS - Query Forwarding'
  ```bash
  curl -u API_KEY:API_SECRET https://FW/api/unbound/settings/addDot -H "Content-Type: application/json" -H "Referer: https://FW/ui/unbound/forward" -d '{"dot": {"type": "forward", "enabled": 1, "domain": "tmp.at", "server": "1.1.1.1", "port": 53}}' --insecure
  ```
 

**Expected behavior**

I would expect the 'type' inside the json-data to be used for this dot/forward-switch as it would be the most streight-forward approach.

It make no sense that you would call a 'addDot' for a 'forwarding'-item if you call a 'addForwarding' for a 'dot'-item.

**Environment**
OPNsense 22.7.4-amd64
FreeBSD 13.1-RELEASE-p2
OpenSSL 1.1.1q 5 Jul 2022
Common KVM processor (4 cores, 4 threads)
Hypervisor: Proxmox PVE

**Comment by AdSchellevis** [comment]
The types are fixed intentionally per endpoint. Even though the endpoints do return the type, it's merely an internal property to prevent having to construct two different endpoints (one for Dot, one for Forward, both providing similar functionality). 

https://github.com/opnsense/core/blob/b5b7670b487ce5604a066781433faa8a0d7f361c/src/opnsense/mvc/app/controllers/OPNsense/Unbound/Api/SettingsController.php#L113

https://github.com/opnsense/core/blob/b5b7670b487ce5604a066781433faa8a0d7f361c/src/opnsense/mvc/app/controllers/OPNsense/Unbound/Api/SettingsController.php#L61-L72

Our automated api doc just can't handle this type of extractions (https://docs.opnsense.org/development/api/core/unbound.html).

**Comment by kulikov-a** [comment]
Hi!
@AdSchellevis although I agree that the functionality is similar, the template still creates different options (in particular `forward-tls-upstream: yes`). maybe it would be more correct to allow to explicitly specify the type through an api call? like https://github.com/kulikov-a/core/commit/390b8e2fa54259a846f5eeae43f925b6f55f6bca ?

**Comment by kulikov-a** [comment]
@AdSchellevis I think I understand you and I agree (although the current behavior also seems to me not quite correct). personally, the existing model\controller seem a little confusing for me: from my understanding of the unbound  (DoT is just a forwarder type), I would rather suggest a model like:
```
        <forwarders>
            <forwarder type="ArrayField">
                <enabled type="BooleanField">
                    <Required>Y</Required>
                    <default>1</default>
                </enabled>
                <is_dot type="BooleanField">
                    <Required>Y</Required>
                    <default>0</default>
                    <Constraints>
                        <check001>
                            <type>DependConstraint</type>
                            <addFields>
                                <field1>verify</field1>
                            </addFields>
                            <ValidationMessage>Forwaredr should be DoT for CN verify</ValidationMessage>
                        </check001>
                    </Constraints>
                </is_dot>
                <domain type="TextField">
                    <Required>N</Required>
                    <mask>/^(?:(?:[a-z0-9]|[a-z0-9][a-z0-9\-]*[a-z0-9])\.)*(?:[a-z0-9]|[a-z0-9][a-z0-9\-]*[a-z0-9])$/i</mask>
                    <ValidationMessage>A valid domain must be specified.</ValidationMessage>
                </domain>
                <server type="NetworkField">
                    <Required>Y</Required>
                </server>
                <port type="PortField">
                    <Required>N</Required>
                </port>
                <verify type="HostnameField">
                    <Required>N</Required>
                        <Constraints>
                            <check001>
                                <reference>is_dot.check001</reference>
                            </check001>
                        </Constraints>
                </verify>
            </forwarder>
        </forwarders>
```

and would use "Query Forwarding" only

**Comment by AdSchellevis** [comment]
@kulikov-a part of this is historical (adding functionality before design), I don't want to change the model, don't mind that much if you can overwrite the type in an api call either to be honest. If you open a PR, I'll discuss the  proposed change with @swhite2
