### ISSUE TITLE
Group Edit dialog allows assigning privileges, Group Add does not

### ISSUE THREAD

**Issue by haarp** [opnsense/core#6048]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

Hello,

this is a quick one.

Probably due to an oversight, The System->Access->Groups->Add dialog does not show the `Assigned Privileges` field, while the Modify dialog does. This leads users creating new goups to assume that no privileges can be assigned to them, leading to much confusion.

Thanks!

**To Reproduce**

1. Go to 'System->Access->Groups'
2. Click on 'Add'
3. No 'Assigned Privileges' field to be found

**Expected behavior**

'Assigned Privileges' field present

**Describe alternatives you considered**

--

**Screenshots**

--

**Relevant log files**

--

**Additional context**

--

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 22.7.4 (amd64, OpenSSL).

**Comment by AdSchellevis** [comment]
same as with users, you can only edit the privileges on edit (it's a different page needing an anchor to update)

**Comment by haarp** [comment]
Ooh, interesting, you *can* add privileges to individual users aswell! See, this is what I'm talking about ;) I assumed it wasn't possible because the field never showed up during creation.

Would you consider improving this? I'm aware of this now, but others might still get confused and make wrong assumptions.

**Comment by AdSchellevis** [comment]
The documentation is more suitable for that, you can always open a PR with suggestions on https://github.com/opnsense/docs/blob/master/source/manual/how-tos/user-local.rst
