### ISSUE TITLE
New certificate request: digest algorithm not correctly set after form error

### ISSUE THREAD

**Issue by 8191** [opnsense/core#605]
When submitting the "add or import certificate" form (`system_certmanager.php?act=new`) and an error is detected, the digest algorithm field is not set correctly to the already submitted value.

**Comment by AdSchellevis** [comment]
Thanks for reporting, it should be fixed with https://github.com/opnsense/core/commit/8f46be824bc41c995e5d04a87e6a1134d6ea485f

Digest Algorithm is used in both the certificate and the signing request, I think your issue is about the csr, the other one functioned without issues on my end.
