### ISSUE TITLE
security - wizard still active after install

### ISSUE THREAD

**Issue by foobarjo** [opnsense/core#6059]
**Affected versions**
Current OPNsense version where the bug first appeared : 22.7.x
Last OPNsense version where the bug did not exist : 22.1.x

**Describe the bug**
On any fresh install of 22.7, the "installer" wizard is not deactivated after install and therefore is accessible via console and, if activated, ssh.

note: the password remain 'opnsense' even after a root password change

**To Reproduce**
- Download the 22.7 media from the official download page (dvd and vga tested)
- Install OPNsense on any VM or hardware
- (optionnal) Configure your newly install OPNsense, change root password, activate ssh and reboot (to be sure you're not in a read only environment)
- try to login console or ssh with user:'installer' pass:'opnsense'

**Expected behavior**
login should be rejected

**Describe alternatives you considered**
none

**Screenshots**
na

**Relevant log files**
na

**Additional context**
none

**Environment**
any

**Comment by fichtner** [comment]
Looks to be a non-obvious side effect of https://github.com/opnsense/core/commit/ba2da34854a

thanks for the report!

**Comment by fichtner** [comment]
9d619ba wil lbe shipped in 22.7.5 next week
