### ISSUE TITLE
UX: change icon "add new based on this one"

### ISSUE THREAD

**Issue by 8191** [opnsense/core#606]
In the Firewall: Rules screen the button "add new rule based on this one" uses a :heavy_plus_sign: icon. In my opinion that's not really straightforward, since I'd expect something like "add new rule below/above this one" when seeing the :heavy_plus_sign: icon.

What about changing the icon to something more intuitive like a copy or clone icon (e.g. [something like this](http://fortawesome.github.io/Font-Awesome/icon/clone/))?

Similar functions use the same icon, e.g.: copy IPsec P1/P2 rules, copy gateways, etc...

**Comment by AdSchellevis** [comment]
Hi Manuel,

Those are probably quite some icons to replace, but it's a good idea to choose a different icon for the copy feature to make it a bit more intuitive.

Do you have time to do this replacement?

Regards,

Ad

**Comment by 8191** [comment]
Hi Ad, 
Yes, I can create a PR for that. Just wanted to clarify if it's also in your intention changing the icons. 

Manuel

**Comment by fichtner** [comment]
Colours may be counter-intuitive and create problems in other themes. It would be better to use a copy icon, namely fa-copy. :)

**Comment by 8191** [comment]
@fichtner I'm afraid there is [no such icon](http://fortawesome.github.io/Font-Awesome/icon/copy/) named `fa-copy` in Font Awesome... But there is [`fa-files-o`](http://fortawesome.github.io/Font-Awesome/icon/files-o/).

**Comment by fichtner** [comment]
Whoops, should have been fa-clone :)

**Comment by 8191** [comment]
Is it intended to migrate the glyphicons to font awesome, or can they co-exist at one page?

**Comment by fichtner** [comment]
font awesome took over the menu (except for the firewall icon, the font awesome one looks blunt), but glyphicons are widely used for action buttons. they must coexist anyway :)

**Comment by fichtner** [comment]
@8191 Will you close? Other smaller things we can merge without a specific PR now since you've established a great baseline now.

**Comment by 8191** [comment]
Yes, the initial request/report was merged.
