### ISSUE TITLE
Unbound DNSBL: Show filter list URL/support site in GUI

### ISSUE THREAD

**Issue by haarp** [opnsense/core#6060]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**

Hi!

When setting up DNSBL filter lists, You only see the list's name. You don't know what exactly you're getting, who's behind the list, where to preview or where to go for problems/improvements. Or maybe you want to find out which list is filtering a specific domain?

**Describe the solution you like**

I humbly request that the filter list URLs be shown somewhere in the web UI. Or some other information, like the relevant Github page.

Thank you very much!

**Describe alternatives you considered**

Searching for the name? Yields nothing useful. Try googling for e.g. "Simple Tracker List", endless results but no dice. Or maybe you think the "Blocklist.site' lists could be found on https://blocklist.site? Nope, they're on Github.

To get this information, I had to do the following:

- Get internal list name from `/usr/local/opnsense/mvc/app/models/OPNsense/Unbound/Unbound.xml`
- Look up internal name in ` /usr/local/opnsense/service/templates/OPNsense/Unbound/core/blocklists.conf`

Which is hardly user-friendly :)

**Additional context**

--

**Comment by AdSchellevis** [comment]
https://docs.opnsense.org/manual/unbound.html#predefined-sources

**Comment by haarp** [comment]
Oh, there it is. The docs are generally very good, but somehow didn't expect the lists to be there.

Feature request: link the relevant docs on all web UI pages (net to he `full  help` button) :D

**Comment by micfogas** [comment]
I found them by dropping to console and locating the file they are stored in XD I put them into AdGuardHome. I didn't think to check the docs either
