### ISSUE TITLE
IPSec: "Manual SPD entries" in conjunction with dynamic remotes may result in wrong endpoint adresses in the generated SPD entries

### ISSUE THREAD

**Issue by boomer41** [opnsense/core#6061]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

Consider the following scenario, where two sites wish to connect with each other using IPSec.
Each site has one router, say A1 and B1, and the IPSec-tunnel is working fine.
All routers shall run OPNsense. 

    Site A:
        IPSec-"Local"-IPs: 10.10.10.0/24
        Router A1 Public IP: 1.1.1.1
        Configured IPSec-Remote: 2.2.1.1 (B1)

    Site B:
        IPSec-"Local"-IPs: 20.20.20.0/24
        Configured IPSec-Remote: 1.1.1.1 (A1)
        Router B1 Public IP: 2.2.1.1

        Router B2 ("Test-Box") Public IP: 2.2.2.2

Each site is configured to "hide" it's local networks by SNAT to one of the IPSec-IPs.
Thus, only one Phase2, `10.10.10.0/24 <=> 20.20.20.0/24` needs to be established.

To actually get the packets from the LANs to IPsec, each side has a manual SPD entry `0.0.0.0/0` configured for that Phase2, so that a "catch all going to the other site"-SA is established.
For Site A, this may look like `0.0.0.0/0 <=> 20.20.20.0/24`.

This, so far, is working fine.

Now Site B wants to test changes to the router configuration with another Router called B2. B2 has a different public IP than B1.
Site A agrees that this connection can be used for that as it's only used occasionally, so they activate the **Dynamic Gateway**-Option in their Phase1.
Establishing the Phase1 and Phase2 between Site A and B2 works fine.

Now, every SA also contains the tunnel endpoints.
For the SA `10.10.10.0/24 <=> 20.20.20.0/24`, the tunnel endpoint on Site A correctly resembles the public IP of B2, `2.2.2.2`.
However, for the SA `0.0.0.0/0 <=> 20.20.20.0/24` caused by the manual SPD entry, the tunnel endpoint **does not** resemble the public IP of B2, but the public IP of the configured IPSec-Remote, `2.2.1.1`.
As a result, the packets originating from Site A's LAN will be wrapped in the Phase2, but the packet is sent to B1 instead of B2.
Thus, the packets will never arrive on the correct remote.

Correctly, the established manual SA entry needs to contain the "correct" tunnel endpoint of the remote, which originally established the Phase2.

**To Reproduce**

1. Set up a IPSec-connection between Box A and B.
2. On A (running OPNsense):
    1. Add a manual SPD entry "0.0.0.0/0"
    2. Change the Remote Gateway to something which is NOT the IP of B
    3. Activate dynamic gateway
    4. Apply
    5. Consider adding firewall rules to allow traffic from B. ISAKMP (500/udp), NAT-T (4500/udp), ESP and AH should be sufficient.
3. On B: Start the IPSec-Connection
4. Observe the established Phase1 and Phase2
6. Look in the Security Policy Database
7. Observe the correct entries which where *not* generated by the manual SPD entries
8. Observe the entries with the wrong remote endpoint generated by the manual SPD entries

**Expected behavior**

The generated SPD entries, which are a result of the manual SPD entries text field, must contain the remote tunnel endpoint which actually established the Phase1/2, and not the configured remote gateway in Phase1 (as they may differ by the Dynamic Gateway feature).

**Describe alternatives you considered**

- We are now running two separate IPSec tunnels with the same Networks.
- It works, but it's ugly and the dynamic gateway feature would be very handy for this.

**Screenshots**

Unfortunately due to corporate policy I may not leak corporate ips.

**Environment**

OPNsense 22.7.4-amd64
Intel(R) Xeon(R) CPU E3-1275 v6 @ 3.80GHz (2 cores, 2 threads)

**Comment by boomer41** [comment]
I looked through the code and I found the issue:

https://github.com/opnsense/core/blob/4f9e12c99959f37614521ed6e998dfbae417d955/src/etc/inc/plugins.inc.d/ipsec.inc#L804

Here, the tunnel destination is resolved using the statically configured remote, not the remote which actually started the Phase2

**Comment by AdSchellevis** [comment]
I believe it's a known limitation, in order to add a manual spd, the endpoints address should be known upfront, see the spdadd command in:

https://github.com/opnsense/core/blob/3c59ce3b6108a6e7015e72f5d3a80c820d0f3869/src/etc/inc/plugins.inc.d/ipsec.inc#L822-L832

**Comment by boomer41** [comment]
Yes, it seems like a limitation.
To be fair, this "bug" only happens in very specific scenarios. However it would be great to get this working in the future as the interface suggests that this should work. It's a very low priority bug/feature request IMHO.

Maybe the interface should show a notice that manual SPD entries won't work with dynamic gateways?

**Comment by AdSchellevis** [comment]
Documentation could be improved on this subject, contributions to https://github.com/opnsense/docs are certainly welcome.
