### ISSUE TITLE
Aliases don't take CIDR notation for networks anymore

### ISSUE THREAD

**Issue by martinroehder** [opnsense/core#6062]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

The add or edit dialog for aliases doesn't take the CIDR notation for networks anymore.

**To Reproduce**

1. Go to 'Firewall->Aliases'
2. Click on '+ for adding a new or edit an existing'
3. Add or change a network wird CIDR notation in the field content
4. See error Entry "192.168.0.0/24" is not a valid hostname

**Expected behavior**

The add or edit dialog accepts networks in CIDR notation as described here: https://docs.opnsense.org/manual/aliases.html.

**Describe alternatives you considered**

**Screenshots**

![Screenshot 2022-10-02 235140](https://user-images.githubusercontent.com/51159911/193478053-abcb6cdf-0c8b-4cdf-ac40-66733fe7d827.png)

**Relevant log files**

**Additional context**

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 22.7.4 (amd64, OpenSSL).

**Comment by AdSchellevis** [comment]
wrong type, choose network. a host is an address without a subnet (https://docs.opnsense.org/manual/aliases.html#hosts)

**Comment by martinroehder** [comment]
Thanks for not laughing at me.
