### ISSUE TITLE
GeoIP does not cater for results being located as just "Europe"

### ISSUE THREAD

**Issue by Taomyn** [opnsense/core#6063]
- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

The GeoIP service MaxMind will for its country tables, return a location value of just "Europe" - this cannot be set in the Firewall Alias/GeoIP section and therefore any IPs designated as "Europe" are not included in the checks.

**To Reproduce**

1. Subscribe to MaxMind GeoIP free service, the country database
2. Create a GeoIP list alias includes USA and some European countries
3. Use the alias in some way
4. Wait for Google Assistant services to connect to the firewall
5. The connection will not be tagged as belonging to the alias

I appreciate it's a vague set of steps, but it's the only example I have that is being caught by this issue

**Expected behavior**

The above connection should be deemed to coming from either the US or Europe

**Describe alternatives you considered**

Reversing the alias, but that created too many entries and explodes memory and probably performance

**Screenshots**

**Additional context**
This is the address block of the IP:

```
network,geoname_id,registered_country_geoname_id,represented_country_geoname_id,is_anonymous_proxy,is_satellite_provider
66.249.81.0/25,6255148,6252001,,0,0

```

According to the country lookup in the file from Maxmind that's:

```
6255148,en,EU,Europe,,,0
6252001,en,NA,"North America",US,"United States",0

```
My forum thread on the matter: https://forum.opnsense.org/index.php?topic=30460.0

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 22.7.4-amd64
FreeBSD 13.1-RELEASE-p2
OpenSSL 1.1.1q 5 Jul 2022

**Comment by AdSchellevis** [comment]
It seems like Maxmind classified a couple of netblocks as being 'somewhere in europe', we should probably add the selection as well, but I kind of expect this will lead to future tickets when not named correctly (unclassified is probably the best option here).
