### ISSUE TITLE
22.7 Users with limited access are not able to seen IPSEC VPN status

### ISSUE THREAD

**Issue by airdatec** [opnsense/core#6067]
Users with limited access are not able to seen IPSEC VPN status.
The Overview IPSEC Status ist shown but Connections.
On root login IPSEC Connections will bis visisble.

Rights defined as below :

   GUI   Status: IPsec
   GUI   Status: IPsec: Leasespage
   GUI   Status: IPsec: SAD
   GUI   Status: IPsec: SPD
   GUI   Status: System logs: IPsec VPN
   GUI   VPN: IPsec

it is also until 22.7.4 rebuildable

On 22.1.10  it was the last Version it works

**Comment by fichtner** [comment]
Perhaps this one

https://github.com/opnsense/core/blob/37fc19bfedb85b88ed9efb45396110d48f30cd47/src/opnsense/mvc/app/models/OPNsense/IPsec/ACL/ACL.xml#L51

Requires value `api/ipsec/sessions/*` instead?

**Comment by airdatec** [comment]
@fichtner,  sounds plausible but im not an developer

**Comment by fichtner** [comment]
@airdatec no problem can you try this patch?

    # opnsense-patch 6a21906
    # /usr/local/etc/rc.configure_plugins


Cheers,
Franco

**Comment by airdatec** [comment]
@fichtner  it Works,  Thx a lot.

**Comment by fichtner** [comment]
Ok, I'll add it to this week's 22.7.6 release :)

Cheers,
Franco
