### ISSUE TITLE
mvc: validation messages provided to UI may be a string or an array of strings

### ISSUE THREAD

**Issue by fichtner** [opnsense/core#6073]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

In some instances multiple validation messages are returned as an array as opposed to a string and JavaScript concatenates them with a default "," character, which ends up with a UI message like:

"This is an error.,This is another error."

https://github.com/opnsense/core/blob/6f83fd8effa94c610db098e7a5f3a22894d4e8ee/src/opnsense/www/js/opnsense.js#L184

**To Reproduce**

Steps to reproduce multiple validation messages:

1. Create a "vlan01" device.
2. Attempt to create a "vlan01" device on top of the "vlan01" device.

**Expected behavior**

A nicer way of displaying multiple validation messages, the easiest of which would be to add bullet points perhaps as we don't know if we deal with sentences or short error messages or a mix of them.

Furthermore it should be considered to always return an array in such instances even when only a single message is contained within.

**Comment by AdSchellevis** [comment]
@fichtner  as promised https://github.com/opnsense/core/commit/6f53ca0b22c900c9d7a1affa1a88a0a950e5d07a , results in the following:

<img width="872" alt="image" src="https://user-images.githubusercontent.com/9783985/194694037-71867281-24b7-4388-9e92-8a91decefb15.png">

<img width="885" alt="image" src="https://user-images.githubusercontent.com/9783985/194694052-05268850-a9b1-4c18-8f57-3f1cc2039199.png">

**Comment by fichtner** [comment]
@AdSchellevis splendid, thank you!
