### ISSUE TITLE
No console menu when connecting via USB console port on DEC3860 version 22.7.5

### ISSUE THREAD

**Issue by Skywalker-11** [opnsense/core#6075]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

No console menu when connecting via USB console port on DEC3860 version 22.7.5

**To Reproduce**

1. Connect computer via USB-A-to-Micro-USB to console port on DEC3860
2. Open serial port (eg. `screen /dev/ttyUSB0 115200`
3. Try to interact with the console
4. No response send back to the computer on the input (terminal stays empty)

**Expected behavior**

Display console config menu. 
In case of an error eg. with the network config which prevents access to the web gui it should be possible to check the current status or reason for an error via the console connection and fix possible config errors that way.

**Additional context**

When booting the output from the boot process is visible via the console connection. 
After the bootup process is finished the console menu which opens for example if you connect via SSH doesn't appear.

Changes to the interface status (connect/disconnect, carp change, etc.) are being displayed on the serial connection after the bootup process is finished or when connecting during normal operation. But otherwise the console screen doesn't respond to any input.

The console menu was available this way via the serial connection in a previous version of OPNsense while setting up the device (unsure which version exactly).

Settings of System>Settings>Administration>Console:
- Console Driver: [x] Use the virtual terminal driver (vt)
- Primary Console: Serial Console
- Secondary Console: None
- Serial Speed: 115200
- USB-based serial: doesn't work with either setting
- Console menu: [x] Password protect the console menu

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 22.7.4/22.7.5 (amd64, OpenSSL).
AMD EPYC 3201 8-Core Processor (8 cores, 8 threads)
DEC3860

**Comment by NielsPiersma** [comment]
@Skywalker-11, We had the same issue, serial console not being available. We resolved this by updating the bios of the dec3860 https://docs.opnsense.org/hardware/bios.html#dec800-and-dec3800-series
The console stopped working after a specific update of OPNSense, it was related to our batch of 3860's not having the latest/correct firmware installed.
Niels
