### ISSUE TITLE
Creating VLAN : GUI offers existing VLAN interfaces as parent interface

### ISSUE THREAD

**Issue by PacoTyson** [opnsense/core#6077]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**
Creating VLAN : GUI offers existing VLAN interfaces as parent interface

**To Reproduce**

1. Go to /ui/interfaces/vlan
2. Click the + icon to create a new vlan interface
3. Expand the "Parent" dropdown list : it contains parent interfaces but also all the existing vlan interfaces.

**Expected behavior**
Only VLAN capable interfaces will be shown, as the help text says.
I didn't try creating a new vlan interface with a vlan interface as parent.

**Screenshots**

![image](https://user-images.githubusercontent.com/10000103/194713617-c23fd0e3-d9bf-4a0a-9222-3cf211ff3aab.png)

**Environment**

OPNsense 22.7.5-amd64
FreeBSD 13.1-RELEASE-p2
OpenSSL 1.1.1q 5 Jul 2022

**Comment by AdSchellevis** [comment]
QinQ support (https://en.wikipedia.org/wiki/IEEE_802.1ad)

**Comment by PacoTyson** [comment]
Learned something today, sorry for trouble.

**Comment by AdSchellevis** [comment]
we all learn every day :) no problem at all.
