### ISSUE TITLE
VPN: IPsec: Status Overview doesn't show entries for non-admin users in 22.7.4

### ISSUE THREAD

**Issue by goodomens42** [opnsense/core#6079]
- [x ] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [ x I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Description**

In most of our OPNSense Installations we have a group "operators" with restricted rights and a restricted menu set.
Since upgrading to 22.7.4 "VPN: IPsec: Status Overview" (/ui/ipsec/sessions) shows only an empty list ("no results found").
The relevant right "GUI | Status: IPsec" is set for the group "operators".
For users in group "admins" everything works as it should.

**To Reproduce**

1. Create a group "operators"
2. Allow this Group to access the menu entry "GUI | Status: IPsec"
3. Create/assign a user to this group who is *not* member of the "admins" group
4. Login as this user
5. Goto /ui/ipsec/sessions
6. An empty list is displayed

**Expected behavior**

Should display a list of active IPSEC Connections
Did work with 21.7, the functionality must have been lost somewhere in between, unfortunately I cant tell with which release

**Environment**

OPNsense 22.7.1 (amd64, OpenSSL)

**Comment by fichtner** [comment]
https://github.com/opnsense/core/issues/6067 (patch inside)
