### ISSUE TITLE
Invisible text at load_balancer_monitor.php

### ISSUE THREAD

**Issue by DokuKaefer** [opnsense/core#608]
At all browsers the Description Text ist invisible.

![load_balancer_services](https://cloud.githubusercontent.com/assets/11537653/12150461/2c67c3da-b4aa-11e5-931c-1033a7fd43f6.png)

And at line 82 the "Add" is missing to translate.

**Comment by fabianfrz** [comment]
this is already fixed

**Comment by DokuKaefer** [comment]
Oh okay :)
I close the isssue.
