### ISSUE TITLE
22.7.5 OpenVPN Default DNS Default Domain - unable to remove

### ISSUE THREAD

**Issue by spaxxilein** [opnsense/core#6084]
**Describe the bug** / **To Reproduce**

When activating "DNS Default Domain" in the OpenVPN Server settings and hitting save - everything works. When trying to remove the setting by unticking the setting and hit "Save" the setting will not be removed. After reentering the OpenVPN Server settings, the previously deleted DNS Default domain is still there. 

**Expected behavior**

Setting will be removed and the OpenVPN Server will push options correctly to newly connected clients.

Workaround: The only way to delete this setting is by leaving the setting ticked and remove the domain from the list and hit save.

***Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 22.7.5 (amd64, OpenSSL).

**Comment by fichtner** [comment]
The configuration wants you to remove the domain entry and the checkbox is just clutter. It would probably be better to remove the checkbox and always show the field.

Since this is a bit of work to audit all fields relevant to this I'll queue this up for 23.1.
