### ISSUE TITLE
ARP Table: sorting problem (incorrect order)

### ISSUE THREAD

**Issue by HarburGER** [opnsense/core#6087]
Interfaces -> Diagnostics -> ARP Table:

Screenshot:
![OPNsense ARP Table sort issue](https://user-images.githubusercontent.com/11475297/195984491-9effddce-6730-4fe0-ad31-3e15f8faf2d9.png)

OPNsense 22.7.6-amd64
FreeBSD 13.1-RELEASE-p2

**Comment by AdSchellevis** [comment]
https://github.com/opnsense/core/issues/4185#issuecomment-755227043
