### ISSUE TITLE
Dynamic state reset is too overbearing

### ISSUE THREAD

**Issue by haarp** [opnsense/core#6088]
Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**

Hello!

The Firewall→Settings→Advanced→Dynamic state reset option is useful. However, it will reset *every* state. This includes innocent connections unrelated to the affected interface. e.g.:

- Connections to a remote server over primary WAN die when failover WAN hiccups.
- SSH sessions into the firewall itself die when WAN changes.

This poses an unnecessary danger to long-lived connections, and makes working with and testing/debugging things involving connection resets a lot harder and frustrating.

**Describe the solution you like**

**Idea 1:** The simple approach, previously proposed in #5367: Only reset the states going through the interface in question. This would cut down on unnecessary state killing.

*However*, this doesn't cover the failover scenario: If the primary WAN goes down and comes back, states on the backup WAN will not be killed. If backup WAN is metered or otherwise undesirable (e.g. cell networks), this is a problem. The *current* behavior of Dynamic state reset covers this case.

**Idea 2:** Whitelist LAN and loopback. This would keep e.g. SSH sessions into the firewall alive. But it would still unnecessarily kill primary WAN states if e.g. the backup WAN changes.

**Idea 3:** Per-interface configuration options. Thus you could set it so changes to Primary WAN1 would kill states on WAN1 and WAN2, But changes on backup WAN2 would only kill states on WAN2.

Nothing is ever easy :/ But I think idea 3 would give the best flexibility and cover all use cases.

**Describe alternatives you considered**

Someone might say "just disable State killing". That's not a solution.

**Additional context**

Failover scenario previously also discussed in #3516.

Thanks a lot!

**Comment by haarp** [comment]
It could be an idea to connect state killing to gateway groups. When the active gateway moves up a tier (tier number decreases), the previous tier's states may be killed, but not the other way around.

**Comment by AdSchellevis** [comment]
> Someone might say "just disable State killing". That's not a solution.

In most cases it probably is as our states aren't bound to interfaces by default and in most cases the client is unaware of the removal of the state (and hangs for that reason).

To be honest, the whole "Dynamic state reset" option is something of past which is disabled by default for valid reasons in my humble opinion. When disabled it kills only the states related to the old address anyway.

https://github.com/opnsense/core/blob/20a60050ee40a096ab2c86e13411b4485a89b7db/src/etc/rc.newwanip#L174-L178

**Comment by haarp** [comment]
> When disabled it kills only the states related to the old address anyway.

Interesting! Neither the web UI nor the manual mention this. This can mislead users (including myself :) ) to assume the checkbox had better be enabled on dynamic IP setups.

OK, this reduced the scope of this request to only the failover scenario: Primary WAN goes down, comes back, but connections on failover WAN remain and drive up the traffic meter. Disabled *Dynamic state reset* doesn't solve this, enabled *Dynamic state reset* kills too much. How to solve this?

**Comment by haarp** [comment]
Upon hearing in #6089 that Dynamic state reset is likely to be removed soon anyway, I hacked together an [alternative for failover recovery](https://github.com/opnsense/core/issues/3516#issuecomment-1280020496). I would love to see something like it properly implemented at some point :)

But as for this feature request, should I close it or keep it open until Dynamic state reset is actually removed?

**Comment by AdSchellevis** [comment]
I think it's better to close, further additions to the state reset in a sensible way are likely complicated as they seem to be missing a generic trigger. 

For example when a route change triggers a different path, but there's already a state binding an outbound address, you can't reliably know this is the case. I've seen similar behaviour with (IPsec) tunnels before, in which case simply assigning an interface as failover wouldn't really help. In most cases the client will restart communication, in some cases this unfortunately is problematic. Very often you are able to prevent issues like these with rules by the way (only nat on an interface if traffic doesn't originate from ...).

**Comment by haarp** [comment]
Closing. Still, thanks for your time!
