### ISSUE TITLE
FW/Aliases: Inconsistent sorting

### ISSUE THREAD

**Issue by devNan0** [opnsense/core#6090]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:
- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**
The name sorting at 'Firewall' -> 'Aliases' (`/ui/firewall/alias`) is different than at 'Firewall' -> 'Diagnostics' -> 'Aliases' (`/ui/firewall/alias_util`).
In my opinion the sorting on the Diagnostics page is better because the internal aliases (prefixed with `__`) are at the bottom.

**To Reproduce**
1. Go to 'Firewall' -> 'Aliases'
2. Click on 'Name'

**Expected behavior**
Sorting to be same as at the Diagnostics page.

**Describe alternatives you considered**
None

**Screenshots**
Sorting at 'Firewall' -> 'Aliases' (`/ui/firewall/alias`)
![image](https://user-images.githubusercontent.com/49376203/196010568-adbaf03a-ff97-4c56-bcb6-58dee83d7655.png)

Sorting at 'Firewall' -> 'Diagnostics' -> 'Aliases' (`/ui/firewall/alias_util`)
![image](https://user-images.githubusercontent.com/49376203/196010596-ba14f0d9-eead-475d-ad3a-32681370c66b.png)

**Relevant log files**
None

**Additional context**
None

**Environment**
OPNsense 22.7.6-amd64
FreeBSD 13.1-RELEASE-p2
OpenSSL 1.1.1q 5 Jul 2022
AMD GX-412TC SOC (4 cores, 4 threads)

**Comment by AdSchellevis** [comment]
grids use natural sorting (for all fields), you can always exclude the internal types if it clutters your view.

**Comment by devNan0** [comment]
This is a possible solution but would result in (up to) 12 additional clicks each time i load the page.

And i still find it inconsistent that `/api/firewall/alias/searchItem` (where the sorting happens) returns a different order than `/api/firewall/alias_util/aliases/` (Firewall: Diagnostics: Aliases)
