### ISSUE TITLE
OpenVPN: support bridged mode setup

### ISSUE THREAD

**Issue by sjorge** [opnsense/core#61]
Doesn't look like you can configure OpenVPN in bridge mode*

*OpenVPN in tap mode and dhcp/slaac requests get forwarded over the tunnel to LAN_X interface.
e.g. useful when non layer3 traffic is needed/desired over vpn.

**Comment by sjorge** [comment]
If anyone is interested in an example config, I can share mine (openbsd)

**Comment by fichtner** [comment]
that would be helpful, yeah. is it ok to paste here for reference?

**Comment by sjorge** [comment]
https://gist.github.com/sjorge/571794e54de3a50d957a, feel free to hit me op on twitter/irc/here for more info

**Comment by fichtner** [comment]
More friendly feedback via mail:

Site-to-site bridging. No network-related config, just a p2p connection à la OpenVPN 1.5 (using openvpn v. 2.3.4).
Sites share the same broadcast domain, have local gateways, DNS forwarder, DHCP server (filtered to avoid leases being granted across the bridge) etc.

== Server on site 1 (waits for connections, 3 tunnels: 2 site-to-site, 1 roadwarriors.) Site1<->Site 2 config shown here ==
# brctl show
bridge name	bridge id		STP enabled	interfaces
myorgbr		8000.001122334455	yes		eth0
							tap0
							tap1
							tap2

# cat /etc/openvpn/site2.myorg.conf
float
lport 1196
mode server
proto udp
dev tap0
...

== Client on site 2 (actively connects to site 1, floating IP) ==
# brctl show
bridge name	bridge id		STP enabled	interfaces
myorgbr		8000.00ffeeddccaa	yes		eth0.1234
							tap0
							wap0

# cat /etc/openvpn/site1.myorg.conf
remote X.X.X.X 1196
float
lport 1194
client
proto udp
dev tap0
…

**Comment by fichtner** [comment]
timeout
