### ISSUE TITLE
Stale lock file when using modem dialin connection

### ISSUE THREAD

**Issue by ahaase-c4u** [opnsense/core#6102]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

We have a little hardware, that has builtin Quectel EG25-G. After configuring the ppp device as WAN, all works well, until the hardware is shut down uncleanly. Doing so, leaves a lock file in /var/spool/lock and no more dialin connection is being done. Error message in log is "MODEM: Fail to open serial port /dev/cuaU0.2 on speed 115200".

When I delete the stale lock file manually, the dialin connection works after next reboot.

**To Reproduce**

1. Configure Quectel device /dev/cuaU0.2 to be used as device for dialin
2. Dialin connection works
3. Reboot device uncleanly, e.g. power cycle
4. Stale lock, no dialin possible

**Expected behavior**

Stale locks should be removed, if recognised. Alternatively clean all locks on boot of device.

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 22.7.6-amd64
FreeBSD 13.1-RELEASE-p2
OpenSSL 1.1.1q 5 Jul 2022

Quectel EG25-G as modem

**Comment by fichtner** [comment]
This should be handled by https://github.com/opnsense/core/blob/64635342a0e302753591cfee3274a445039d723c/src/etc/inc/interfaces.inc#L1242 or which lock file are you referring to?


Cheers,
Franco

**Comment by ahaase-c4u** [comment]
Yes, looks exactly like the lock, that isn't deleted correctly. So the unlink seems not to work in this case.

**Comment by fichtner** [comment]
could it be that $port is actually `/dev/cuaU0.2` ?

**Comment by fichtner** [comment]
I think that would then mean...

    @unlink('/var/spool/lock/LCK..' . basename($port));

**Comment by ahaase-c4u** [comment]
According to Interfaces -> Point-to-Point -> Devices port is /dev/cuaU0.2. So I could build in the basename fix?

**Comment by fichtner** [comment]
Yep, please try replacing that delete.

**Comment by fichtner** [comment]
@ahaase-c4u did you test this yet?

**Comment by ahaase-c4u** [comment]
Sorry for coming back to you this late. Your change fixes the problem for me. As I tried yesterday, a power-cycle does not prevent the mobile connection from coming up any more. Thank you very much.

**Comment by fichtner** [comment]
No problem, assuming e892a560ff8ce does the trick and will be shipped in 22.7.8. Thanks a lot!
