### ISSUE TITLE
DHCP server leases not using set default lease time

### ISSUE THREAD

**Issue by LeftyJohnson** [opnsense/core#6103]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X ] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [ X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

The DCHP daemon is issuing leases with the service default lease time of 7200 seconds instead of the set value at https://192.168.1.1/services_dhcp.php?if=lan : Default lease time (seconds)

**To Reproduce**

The behavior is visible in the DHCPD log file in messages.

**Expected behavior**

The DHCP leases should be issued with the set default lease time.

**Relevant log files**

From DHCP log file:
- address 2601:840:8681:739::1d46 to client with duid 00:01:00:01:28:8d:0c:13:38:14:28:4f:da:c2 iaid = 167005923 valid for 7200 seconds

Software version used and hardware type if relevant, e.g.:

OPNsense 22.7.6-amd64
FreeBSD 13.1-RELEASE-p2
LibreSSL 3.3.6
Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz (2 cores, 4 threads)
Network Intel® I211

**Comment by AdSchellevis** [comment]
7200 is the default ipv6 indeed, you probably need to adjust the settings there (services_dhcpv6.php)

**Comment by LeftyJohnson** [comment]
I would, but there there doesn't appear to be a separate configuration setting for DHCPv6 lease time.
When I try to navigate to https://<router>/services_dhcpv6.php I get redirected to https://<router>/index.php

**Comment by AdSchellevis** [comment]
Which is to be expected, it needs the interface as paramater too (Services -> DHCPv6 -> [LAN] for example), but with IPv6 there are more settings needed depending on the type of setup. probably best use our forum to discuss what you want to achieve, it's located at https://forum.opnsense.org

**Comment by LeftyJohnson** [comment]
Services -> DHCPv6 -> [LAN] is not an option in the GUI
