### ISSUE TITLE
Allow for advanced configuration of SYN Cookies

### ISSUE THREAD

**Issue by Zaddish** [opnsense/core#6106]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**

When enabling SynCookiesunder the firewall, there is no way to configure which interfaces we have it enabled on.
Having it used as a global option can be detrimental to features of some services. 

**Describe the solution you like**

We could instead make it more configurable for services that are not compatible with SynCookies. 
A way to be able to change the configuration of the SynCookie to allow for specific LAN's, VLANS and or IP addresses.
Disabling SynCookies for loopback connections.

**Additional context**

I am having the problem with specifically with CrowdSec's API & Bouncer, it requires the use of disabling SYN Cookies for it's service to run.

**Comment by fichtner** [comment]
Have you checked pf.conf syntax before you opened this request? How does the resulting pf.conf configuration look?

**Comment by Zaddish** [comment]
> Have you checked pf.conf syntax before you opened this request? How does the resulting pf.conf configuration look?

I have not looked at pf.conf. Is there ways to configure SynCookies to my needs with it?
If so, I believe a Web UI for that sort of configuration would be good.
