### ISSUE TITLE
Authentication / Radius - RADIUS_CLASS support 

### ISSUE THREAD

**Issue by AdSchellevis** [opnsense/core#6111]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**

Note to self, it might be practical to extract radius classes (RADIUS_CLASS) at some point to allow group synchronisation for some use-cases 

https://github.com/opnsense/core/blob/f68816a8c2f2f02852c4846c0b6806a0fdf42c2e/src/opnsense/mvc/app/library/OPNsense/Auth/Radius.php#L415-L437

https://www.php.net/manual/en/radius.constants.attributes.php

**Comment by NielsPiersma** [comment]
I support this feature request.

**Comment by AdSchellevis** [comment]
@NielsPiersma if you do want to test this at some time, just drop me an email. it needs the following commits:

https://github.com/opnsense/core/commit/5a6aaeda3329612ad538dc39325b902058d18d15
https://github.com/opnsense/core/commit/a8bd3379b1a8c922ba181648626431c543b378b3
https://github.com/opnsense/core/commit/ef0da3ea59ffaeaa70f7baef8245b347d3097589
