### ISSUE TITLE
PPP advanced options cleared when interface settings are saved

### ISSUE THREAD

**Issue by haarp** [opnsense/core#6121]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

Hi,

when a PPP interface is assigned it shows up as *Interfaces->foo*. When you open it, settings may be changed and saved.

If you do that, settings on the underlying interface in *Interfaces->Point-to-Point->Devices->pppX->Edit->Show advanced options* are cleared! They vanish from both the web interface and config.xml.

Thanks!

**To Reproduce**

1. Assign `pppX` to interface `foo`
2. Go to *Interfaces->Point-to-Point->Devices->pppX->Edit->Show advanced options*
3. Set some stuff, e.g. `SIM PIN` or `Init String`, Save
4. Go to *Interfaces->foo*, press Save, then Apply
5. Go back to *Interfaces->Point-to-Point->Devices->pppX->Edit->Show advanced options*
6. Observe `SIM PIN` and `Init String` having been cleared
7. Open config.xml, observe `<simpin>` and `<initstr>` also missing

**Expected behavior**

Not discarding settings

**Describe alternatives you considered**

-

**Screenshots**

-

**Relevant log files**

-

**Additional context**

-

**Environment**

OPNsense 22.7.7 (amd64, OpenSSL).
APU 2D4

**Comment by AdSchellevis** [comment]
should be fixed with https://github.com/opnsense/core/commit/0ae0c2fc9307d89c449a61605a1af50e35c54fdd

**Comment by haarp** [comment]
Speedy bugfixing on a weekend? You guys are something else :) Thanks!
