### ISSUE TITLE
Support CARP with IPv6 peer IP

### ISSUE THREAD

**Issue by telmich** [opnsense/core#6122]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**

In our IPv6 only networks, we don't have IPv4 anymore. Technically, carp can use IPv6 for synchronisation. However in the webinterface of opnsense it says: "    The synchronize peer IP must be an IPv4 address or left empty."

**Describe the solution you like**

Add support for using an IPv6 address for carp sync.

**Describe alternatives you considered**

-

**Additional context**

This is somewhat a "nasty" problem, as the whole network diagram of the networks are IPv6 only. At the moment we added "undocumented" IPv4 addresses, but this will lead to issues later, as conceptually our networks don't have IPv4 anymore and thus IPv4 traffic is something rare/special to be considered. 

Having support for carp via IPv6 in OpnSense would allow us to synchronise in the native IPv6 environment.

**Comment by fichtner** [comment]
I just found https://reviews.freebsd.org/D36277 and I was under the impression this is simply not supported by pfsync(4) at the moment.

**Comment by telmich** [comment]
@fichtner There are multiple angles here from my perspective:

* Supporting CARP (non-pfsync) for IPv6
* pfsync for state synchronisation

I agree that both would be good to have, but what I wanted to raise is that even using IPv6 as in input in opnsense does not work for carp.

From https://www.freebsd.org/cgi/man.cgi?query=carp&sektion=4
I think IPv6 should be supported: " The CARP allows multiple hosts on the same	local network to share a set
     of	IPv4 and/or IPv6 addresses."

However, trying to actually use that, I do get an error message from ifconfig, which I need to debug:

```
root@router:~ # ifconfig igb3 vhid 2 advskew 100 pass anypassword 2a0a:e5c0:10:b11::42/64
ifconfig: 2a0a:e5c0:10:b11::42/64: bad value (width too large)
```

**Comment by telmich** [comment]
NVM, if you use `inet6` correctly, the kernel & ifconfig are quite happy:

```
root@router:~ # ifconfig igb1 inet6 vhid 1 advskew 9 pass anypass fe80::44/64
root@router:~ # ifconfig igb1 inet6 vhid 1 advskew 9 pass anypass 2a0a:e5c0:10:bee::1042/64
root@router:~ # ifconfig igb1
igb1: flags=8963<UP,BROADCAST,RUNNING,PROMISC,SIMPLEX,MULTICAST> metric 0 mtu 1500
	description: WAN
	options=4800028<VLAN_MTU,JUMBO_MTU,NOMAP>
	ether f4:90:ea:00:88:3b
	inet 192.168.42.244 netmask 0xffffff00 broadcast 192.168.42.255
	inet6 2a0a:e5c0:10:bee::1003 prefixlen 64
	inet6 fe80::f690:eaff:fe00:883b%igb1 prefixlen 64 scopeid 0x2
	inet6 fe80::44%igb1 prefixlen 64 scopeid 0x2 vhid 1
	inet6 2a0a:e5c0:10:bee::1042 prefixlen 64 vhid 1
	carp: BACKUP vhid 1 advbase 1 advskew 9
	media: Ethernet autoselect (1000baseT <full-duplex>)
	status: active
	nd6 options=21<PERFORMNUD,AUTO_LINKLOCAL>
root@router:~ # 
```

**Comment by fichtner** [comment]
Yes, IPv6 CARP work even from the Virtual IP GUI, but keep in mind that it requires a link-local for failover to work correctly.

pfsync als syncs IPv6, but just not over IPv6 connection itself.


Cheers,
Franco

**Comment by fichtner** [comment]
@telmich

Funnily enough https://reviews.freebsd.org/D36277 was merged to FreeBSD yesterday so it's not that far away anymore and we will evaluate inclusion in 23.1.

But for the time being the scope of this ticket is covered, shall we close it?


Cheers,
Franco
