### ISSUE TITLE
New Packet Capture Interface doesn't parse characters correctly.

### ISSUE THREAD

**Issue by holysoles** [opnsense/core#6125]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x ] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x ] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

When reviewing a packet capture through the web interface, the OPNsense web frontend isn't parsing the `&gt;` HTML entity into a `>` symbol, resulting in a harder to read output value.

**To Reproduce**

1. Go Interfaces > Diagnostics > Packet Capture
2. Under the "Capture" tab, select rules to collect a packet capture that will result in packets.
3. Let the capture run until you're sure you've capture traffic, stop the capture on the "Jobs" tab with the stop button.
4. View the capture under "high detail", "medium detail" or "low detail"
5. Note that the "Output" column of the results shows the traffic flowing between IPs with the `&gt;` HTML special entity, which isn't parsed to `>`.

**Expected behavior**

During HTML rendering, `&gt;` should be parsed to a `>`.

**Describe alternatives you considered**

1. Just associate `&gt;` with `>` as you read the output column
2. Export pcap to another tool like Wireshark for review.

**Screenshots**

<img width="1211" alt="image" src="https://user-images.githubusercontent.com/31580846/200194355-9e34f02b-3060-4697-86e5-6705849cd7ac.png">

**Relevant log files**

N/A

**Additional context**

N/A

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 22.7.7_1-amd64
FreeBSD 13.1-RELEASE-p3
OpenSSL 1.1.1s 1 Nov 2022

**Comment by AdSchellevis** [comment]
@holysoles https://github.com/opnsense/core/commit/919b645262655d293ea824d729b1308167023c3b should do the trick.
