### ISSUE TITLE
Network-Interfaces not found after update to 22.7.6

### ISSUE THREAD

**Issue by Toby-BY** [opnsense/core#6126]
Hi,

after updating to version 22.7.6, OPNsense no longer finds the network interfaces.
The computer starts with two error messages:
error : interface re1 not found
error : interface re0 not found

This means I can't install another update (maybe to fix the problem).
Are there similar problems and/or does anyone have a solution?

My hardware:
Minisforum Kodlix GD41
Processor: Intel N4120
2 Ethernetports (Gigabit)

Before the update everything worked fine.
Probably a driver or kernel problem.

Thanks and greets
Toby

**Comment by fichtner** [comment]
Is this a 2.5G card? Possibly lost the plugin driver for it, but not enough info to go on.

**Comment by Toby-BY** [comment]
The PC has two networkports, each 1G. The network card is an onboard card. 
It's the following device with an Intel N4120.

http://www.kodlix.com/view/49.html

How can I install the driver manually?



> Is this a 2.5G card? Possibly lost the plugin driver for it, but not enough info to go on.
