### ISSUE TITLE
Network-Interfaces not found after update to 22.7.6

### ISSUE THREAD

**Issue by Toby-BY** [opnsense/core#6127]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

Hi,

after updating to version 22.7.6, OPNsense no longer finds the network interfaces. 
The computer starts with two error messages: 
error : interface re1 not found 
error : interface re0 not found

This means I can't install another update (maybe to fix the problem). 

My hardware: 
Minisforum Kodlix GD41
Processor: Intel N4120
The PC has two networkports, each 1G. The network card is an onboard card. It's the following device with an Intel N4120:
http://www.kodlix.com/view/49.html (http://www.kodlix.com/view/49.html)

Before the update everything worked fine.  Probably a driver or kernel problem.

How can I install the driver manually?
Are there similar problems and/or does anyone have a solution?

**To Reproduce**

**Expected behavior**

None

**Describe alternatives you considered**

None

**Screenshots**

None

**Relevant log files**

None

**Additional context**

None

**Environment**

OPNsense 22.7.6 (amd64).

Minisforum Kodlix GD41 Processor: Intel N4120
The PC has two networkports, each 1G. The network card is an onboard card.
 It's the following device with an Intel N4120:
http://www.kodlix.com/view/49.html (http://www.kodlix.com/view/49.html)

Thanks
Toby

**Comment by fichtner** [comment]
https://github.com/opnsense/core/issues/6126#event-7751653034

The re(4) driver is built in for 1G. When was this last working, which version? Maybe the network controller died?

**Comment by Toby-BY** [comment]
The firewall worked without problems until last weekend. Before that, in the evening I manually initiated an update to version 22.7.6 via the web interface and restarted it. The next day the problem appeared.

Unfortunately I can not say which version was last installed. Can I look that up somewhere?

Would be an odd coincidence that the network controller dies right after the update.

**Comment by fichtner** [comment]
I suppose the question was if it worked in 22.7 or 22.1 prior. There aren’t any changes to re(4).

the other question is if you installed os-realtek-re plugin or not…
