### ISSUE TITLE
Nothing to do response with command opnsense-update

### ISSUE THREAD

**Issue by ElXk6** [opnsense/core#6128]
**Important notices**

Our forum is located at https://forum.opnsense.org , please consider joining discussions there in stead of using GitHub for these matters.

Before you ask a new question, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Could be releated to**
https://github.com/opnsense/core/issues/6097 ?
https://forum.opnsense.org/index.php?topic=30836.0 ?

**The current OPNsense version where the bug first appeared**
Unfortunately I do not know since when the problem exists

**Describe the bug**
I have the problem that when I want to update the opnsense over cli with the help of the command `opnsense-update`,
I get a `Nothing to do.` response.

**To Reproduce**
Execude command `opnsense-update` on Version 21.7.7

**Expected behavior**
Update to newest Minor/Patch Version

**Describe alternatives you considered**
To work around the problem, I have to either log into the GUI and use the `Check for Updates`
button under `System: Firmware: Status` and then confirm the popup message.
Once I do that, i can execude `opnsense-update` without problems.

Second possibility is to execute the script `/usr/local/opnsense/scripts/firmware/update.sh` manually,
this also works without problems.

Third possibility is to run `pkg upgrade -y`, but here I don't know if this is bad practice and could cause conflicts?

**Environment**
OPNsense 21.7.7-amd64
FreeBSD 12.1-RELEASE-p21-HBSD
OpenSSL 1.1.1l 24 Aug 2021
CPU type AMD GX-412TC SOC (4 cores)

**Comment by fichtner** [comment]
It’s in the manual page. “-bkp” is no longer the default mode. That change is possibly over half a year ago or more.

**Comment by fichtner** [comment]
For reference the changes are https://github.com/opnsense/update/commit/1f2b05a684fdf0 -- maybe the working is not as clear as it could be?
