### ISSUE TITLE
[23.1.b_2-amd64] UNBOUND: module python failed to setup modules

### ISSUE THREAD

**Issue by Dustie** [opnsense/core#6129]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:
- [x ] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [ x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**
Unbound fails with Fatal Error after update: 
`Critical | unbound | [69215:0] fatal error: failed to setup modules`

**To Reproduce**
1. Start Firewall
2. Unbound fails

**Expected behavior**
Unbound should not fail.

**Screenshots**
![Screenshot 2022-11-09 080549](https://user-images.githubusercontent.com/21229918/200766538-681bb473-c475-4d36-b728-95f47b37d157.png)

**Relevant log files**
```
Critical | unbound | [69215:0] fatal error: failed to setup modules
Error | unbound | [69215:0] error: module init for module python failed
KeyError: 'dst_addr'
self.dst_addr = config['dst_addr']
File "dnsbl_module.py", line 26, in load_dnsbl
self.load_dnsbl()
File "dnsbl_module.py", line 52, in update_dnsbl
self.update_dnsbl()
File "dnsbl_module.py", line 15, in __init__
ctx = ModuleContext(env)
File "dnsbl_module.py", line 84, in init_standard
```

**Additional context**
Previous working version: `unbound upgraded: 1.16.3 -> 1.17.0`

*Steps tried to fix issue*
1. Tried disabling blocklist completely
2. Tried reinstalling package
3. Tried reverting to the previous version:

```
root@OPN:~ # opnsense-revert -r 1.16.3 unbound
Fetching unbound.pkg: ..[fetch: https://pkg.opnsense.org/FreeBSD:13:amd64/22.7/MINT/1.16.3/LibreSSL/Latest/unbound.pkg.sig: Not Found] failed
```

**Environment**

Version: 23.1.b_2-amd64
Flavour: LibreSSL

```
***GOT REQUEST TO AUDIT HEALTH***
Currently running OPNsense 23.1.b_2 (amd64/LibreSSL) at Wed Nov  9 07:25:23 UTC 2022
>>> Check installed kernel version
Version 22.7.7 is correct.
>>> Check for missing or altered kernel files
No problems detected.
>>> Check installed base version
Version 22.7.7 is correct.
>>> Check for missing or altered base files
No problems detected.
>>> Check installed repositories
OPNsense
>>> Check installed plugins
No plugins found.
>>> Check locked packages
No locks found.
>>> Check for missing package dependencies
Checking all packages: .......... done
>>> Check for missing or altered package files
Checking all packages: .......... done
>>> Check for core packages consistency
Core package "opnsense-devel" has 63 dependencies to check.
Checking packages: ................................................................. done
***DONE***
```

```
***GOT REQUEST TO CHECK FOR UPDATES***
Currently running OPNsense 23.1.b_2 (amd64/LibreSSL) at Wed Nov  9 07:39:15 UTC 2022
Fetching changelog information, please wait... done
Updating OPNsense repository catalogue...
Fetching meta.conf: . done
Fetching packagesite.pkg: .......... done
Processing entries: .......... done
OPNsense repository update completed. 782 packages processed.
All repositories are up to date.
Checking integrity... done (0 conflicting)
Your packages are up to date.
Checking for upgrades (0 candidates): . done
Processing candidates (0 candidates): . done
Checking integrity... done (0 conflicting)
Your packages are up to date.
***DONE***
```

**Comment by AdSchellevis** [comment]
@Dustie can you try to run the following on a console and start again?
```
configctl unbound dnsbl
```

**Comment by Dustie** [comment]
That was quick @AdSchellevis and that fixed it!

**Comment by fichtner** [comment]
BTW, `-r` takes the OPNsense release you want a package to revert to, so in this case 22.7.6.

**Comment by AdSchellevis** [comment]
lets keep this open, @swhite2 might want to safe-guard the startup a bit.

**Comment by swhite2** [comment]
@Dustie Thanks for the report. You can use `opnsense-patch fae02022c` to test.
