### ISSUE TITLE
openvpn: update p12 export algorithm

### ISSUE THREAD

**Issue by jo-krk** [opnsense/core#6130]
After upgrade to Ubuntu 22.10 my Openvpn Client doesn't connect anymore to Openvpn Server running on Opnsense.
Investigation showed that new openssl version, that is shipped with Ubuntu 22.10, doesn't support deprecated algorithm that is used by Opnsense when exporting Openvpn config.

```
$ openssl pkcs12 -info -in openvpn_OpenVPN_Server_Zertifikat.p12
Enter Import Password:
MAC: sha1, Iteration 1
MAC length: 20, salt length: 8
PKCS7 Encrypted data: pbeWithSHA1And40BitRC2-CBC, Iteration 2048
Error outputting keys and certificates
80FB35FD2D7F0000:error:0308010C:digital envelope routines:inner_evp_generic_fetch:unsupported:../crypto/evp/evp_fetch.c:373:Global default library context, Algorithm (RC2-40-CBC : 0), Properties ()

```

Same openssl command, from above, with `-legacy` flag provides expected output

Opnsense version: _OPNsense 22.7.7_1 (amd64/OpenSSL)_
Openvpn package version @ OPNsense: _2.5.8_

Client OS: _Ubuntu 22.10_
Client's openssl version: _OpenSSL 3.0.5 5 Jul 2022_
Client's openvpn version: _OpenVPN 2.6_git x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] [DCO]_

**Comment by fichtner** [comment]
We should update the default algorithm most likely, but the `-legacy` switch and deprecation is all on OpenSSL 3 and out of our reach

**Comment by fichtner** [comment]
If you want to have a laugh see https://www.openssl.org/docs/man1.1.1/man3/PKCS12_create.html

    These defaults are: 40 bit RC2 encryption for certificates

**Comment by fichtner** [comment]
Upstream issue fixed eventually by moving to OpenSSL 3. But that's definitely not this year. Removing milestone.

**Comment by luckylinux** [comment]
I made a small script based on @jo-krk suggestions.
This allows to quickly regenerate the updated .p12 file with the required modifications.

```
#!/bin/bash

# Abort on errors
set -e

# Source: https://github.com/opnsense/core/issues/6130#issuecomment-1310237598

# .p12 file to read
read -p "Enter .p12 filename to convert to new OpenSSL 3.x format: " p12file
echo -e "\n"

# Get folder name and p12 filename
fullpath=$(dirname $p12file)

# Generate timestamp
timestamp=$(date +%Y%m%d%H%M)

# Create backup
cp "${p12file}" "${p12file}_backup_${timestamp}"

# Filenames only
p12filename=$(basename $p12file)
certfilename=${p12filename/".p12"/".cert.pem"}
keyfilename=${p12filename/".p12"/".key.pem"}

# Filenames with path
certfile="${fullpath}/${certfilename}"
keyfile="${fullpath}/${keyfilename}"

# Decrypt p12 generated by OPNsense via:
# Manual Process
#openssl pkcs12 -info -in $oldp12 -legacy

# Automatic Process
# And place the respective contents in a .cert and .key file
openssl pkcs12 -in $p12file -legacy -out $keyfile -nodes
openssl pkcs12 -in $p12file -legacy -out $certfile -nokeys

# Generate new p12 file with current algorithm:
openssl pkcs12 -export -out $p12file -inkey $keyfile -in $certfile
```
