### ISSUE TITLE
Better UI notification when configd crashes

### ISSUE THREAD

**Issue by Keno** [opnsense/core#6132]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**

The `configd` daemon on my opnsense firewall crashed (appears to have been related to freeradius, deleting the `os-freeradius` package and restarting configd worked). The results were extremely confusing. The web UI appeared to work, but was extremely slow when adding new firewall rules (the "add new rule" windows would take about 30 seconds just to load). Applying new firewall rules appeared to succeed in the Web UI, but wasn't actually getting reflected in the firewall causing much confusion.

**Describe the solution you like**

I would have liked a big error banner at the top telling me that configd crashed and that adding firewall rules was not going to work, or at the very least some sort of warning when the firewall rules are being applied that they will not be reflected in the actual firewall.

**Describe alternatives you considered**
**Additional context**

**Comment by fichtner** [comment]
I suppose it did not crash, but the pre-deinstall script hung after stopping it for some reason? it's supposed to stop/start to re-register the backend commands without the freeradius hooks.

do you have the log of the deinstall phase? are you able to reproduce?

**Comment by Keno** [comment]
> I suppose it did not crash, but the pre-deinstall script hung after stopping it for some reason? it's supposed to stop/start to re-register the backend commands without the freeradius hooks.

Just to clarify. I installed os-freeradius (last week), which, without me noticing, appears to have stopped or crashed `configd`. Uninstalling os-freeradius made it work again. I can try re-installing os-freeradius to see if the configd issue reproduces, but I would also strongly suggest that there be some GUI indication that firewall rules aren't actually being applied if configd is not running.

**Comment by Keno** [comment]
> I can try re-installing os-freeradius to see if the configd issue reproduces

Indeed, re-installing os-freeradius causes the issue to re-appear. This may be because I already have a `radiusd` daemon running with a handwritten config (on a non-default port though). I had installed os-freeradius to try to see if I can move it over to be opnsense-managed instead. Are the any interesting logs here I should look at to figure out exactly what is going wrong with configd? The `/var/log/configd/latest.log` is filling up with messages like:
```
<163>1 2022-11-10T21:01:48+00:00 OPNsense.localdomain configd.py 56336 - [meta sequenceId="22"] Failed to connect to configd socket: Connection refused while executing firmware product
<163>1 2022-11-10T21:02:06+00:00 OPNsense.localdomain configd.py 47260 - [meta sequenceId="23"] Failed to connect to configd socket: Connection refused while executing firmware product
```

**Comment by fichtner** [comment]
ps: `service configd restart` should bring it back?

**Comment by Keno** [comment]
```
root@OPNsense:~ # service configd status
configd is running as pid 46498.
root@OPNsense:~ # pkg install -f os-freeradius
Updating OPNsense repository catalogue...
OPNsense repository is up to date.
All repositories are up to date.
Checking integrity... done (0 conflicting)
The following 1 package(s) will be affected (of 0 checked):

New packages to be INSTALLED:
	os-freeradius: 1.9.21_1

Number of packages to be installed: 1

Proceed with this action? [y/N]: y
[1/1] Installing os-freeradius-1.9.21_1...
[1/1] Extracting os-freeradius-1.9.21_1: 100%
Stopping configd...done
Starting configd.
Reloading plugin configuration
Configuring system logging...done.
Reloading template OPNsense/Freeradius: OK
root@OPNsense:~ # service configd status
configd is not running.
root@OPNsense:~ # service configd restart
configd not running? (check /var/run/configd.pid).
Starting configd.
root@OPNsense:~ # service configd status
configd is running as pid 16827.
```
