### ISSUE TITLE
Support for Importing Encrypted Configuration Files During OPNsense Installation

### ISSUE THREAD

**Issue by dlcasto** [opnsense/core#6133]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**

When installing a new instance of OPNsense, the configuration import step currently only supports unencrypted backup configuration files produced from the web UI. If an encrypted configuration file is used, the following message is displayed "The file /conf/config.xml is encrypted."

**Describe the solution you like**

A [discussion on Twitter](https://twitter.com/HomeNetworkGuy_/status/1590077161310150656) with the OPNsense team included a possible solution of requiring a separate file containing the password needed to decrypt the configuration file. This has the advantage of working for both automated deployments as well as an interactive installation where the user presses any key to start the configuration import process.

**Describe alternatives you considered**

One alternative is prompting the user for the password necessary to decrypt the configuration file, but there was concern this would interrupt automated deployments. If there is a way to allow this option to work for those interactively installing OPNsense without disrupting automated deployments, this could be a viable option.

**Additional context**

The code which rejects the encrypted configuration file was sent to me by the OPNsense team: [https://github.com/opnsense/core/blob/master/src/sbin/opnsense-importer#L337](https://github.com/opnsense/core/blob/master/src/sbin/opnsense-importer#L337)

**Comment by fichtner** [comment]
I'll try to come up with a solution for 23.7 :)

**Comment by dlcasto** [comment]
Thanks! I'll advertise it on my Twitter account and update my OPNsense hardware migration guide once this feature is complete!

**Comment by fichtner** [comment]
@dlcasto the change is still queued for testing with the final images for 23.7, but there is no apparent reason why it shouldn't work.


Cheers,
Franco

**Comment by dlcasto** [comment]
@fichtner Thanks for working this feature! I'm sure I'm not the only one who appreciates it!
