### ISSUE TITLE
FIREWALL: DIAGNOSTICS: ALIASES; select picker list not sorted

### ISSUE THREAD

**Issue by NOYB** [opnsense/core#6137]
FIREWALL: DIAGNOSTICS: ALIASES
The aliases select picker list is not sorted.

Cause:
The natcasesort($array) function maintains the key/value associations.  Thus returning the array to the ajax call with original index order.  Preventing effective sorting.

Suggested change:
AliasUtilController.php: 84
```
-	$result = array_values($result);
-	natcasesort($result);
+	sort($result, SORT_NATURAL | SORT_FLAG_CASE);
```
Related Locations:
ajax call: /usr/local/opnsense/mvc/app/views/OPNsense/Firewall/alias_util.volt: 5
natcasesort() function: /usr/local/opnsense/mvc/app/controllers/OPNsense/Firewall/Api/AliasUtilController.php: 84

**Comment by AdSchellevis** [comment]
https://github.com/opnsense/core/commit/c929c73a50de525e6b8a192b11b6b8ad169f2850
