### ISSUE TITLE
firewall: live log dns lookup checkbox 431 error

### ISSUE THREAD

**Issue by fichtner** [opnsense/core#6139]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

The API DNS request is being returned with `431 Request Header Fields Too Large`. This is the case after a4fcfdbd3edabe47 which fetches 1000 records minimum which breaks the GET size limitation.

**To Reproduce**

1. Update to at least 22.7.6
2. Open live log
3. Enable  DNS resolution checkbox
4. See error in developer tools for DNS API call and log GET request

**Expected behavior**

Possibly limit query to visible data and/or change to POST request and/or split into multiple calls if necessary.

**Describe alternatives you considered**

Limit total amount pushed somehow, but hard to correlate with filtered input if clamped directly after fetch.

**Additional context**

https://forum.opnsense.org/index.php?topic=30838.0

**Environment**

Since 22.7.6 / a4fcfdbd3edabe47

**Comment by AdSchellevis** [comment]
https://github.com/opnsense/core/commit/da9c21c550d915ef5edff8e013700e8d68371652 should do the trick
