### ISSUE TITLE
Wireguard will always use the default gateway

### ISSUE THREAD

**Issue by haarp** [opnsense/core#6140]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

When using wireguard (userspace variant) in a multi-WAN environment, one will encounter the problem that wg will always send replies using the default gateway. So incoming connections through the default gateway interface will work fine, incoming connections through any other interface will fail, as the client will see a different address than it sent its handshake to.

On the surface this looks similar to #5307, but is different. As no NAT/port forwards are involved, no amount of manual rules or fiddling with reply-to will make it work (as far as I tried).

There is a forum thread discussing this problem, but without a real solution: https://forum.opnsense.org/index.php?topic=16141.0

**To Reproduce**

1. Have mutliple WAN interfaces
2. Set up Wireguard "server"
3. Set Allow rules for WG port on all WANs
4. From the outside, try connecting to WG behind each of the WANs
5. WAN that is default gateway: Connection succeeds
6. WAN that is not default gateway: Connection fails

**Expected behavior**

Wireguard should egress using the same interface it received on.

**Describe alternatives you considered**

Tough call. The forum thread suggests stuffing WG behind NAT and routing using rules. That didn't work out either for me.

The kernel version of WG might behave differently. I did not test it, as its performance is sub-par here.

**Screenshots**

--

**Relevant log files**

--

**Additional context**

--

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 22.7.7 (amd64, OpenSSL).
APU 2D4

Thanks!

**Comment by mimugmail** [comment]
The Kernel version should work, user space variant is not actively developed by them

**Comment by haarp** [comment]
Indeed, the kernel version uses the correct gateway going out. Yay! Thanks @mimugmail 

What's the ultimate goal regarding Wireguard? Keep both version around forever? Slowly deprecate the userspace version?

**Comment by fichtner** [comment]
The kmod is base in 14.0 now. I suppose we can add a kmod variant, or keep the go and move it to a second plugin and make the main one the kmod one for 23.1
