### ISSUE TITLE
Is there any changes in ARP API?

### ISSUE THREAD

**Issue by budimanjojo** [opnsense/core#6144]
**Important notices**

Our forum is located at https://forum.opnsense.org , please consider joining discussions there in stead of using GitHub for these matters.

Before you ask a new question, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

I don't know how do I debug this because there's not really any useful information I can provide. But the [home assistant integration](https://www.home-assistant.io/integrations/opnsense/) is no longer working for me (and some people). More information about the problem can be look at here: https://github.com/home-assistant/core/issues/81815

**Comment by AdSchellevis** [comment]
I don't think so, the library [1] seems to call `https://xxx.xxx.xxx.xxx/api/diagnostics/interface/getArp`, which doesn't look changed in terms of output on our end.


1. https://github.com/mtreinish/pyopnsense/blob/529a49565f82733d2667ee7573da7029b1b96a3d/pyopnsense/diagnostics.py#L50-L52

**Comment by AdSchellevis** [comment]
I think it doesn't make sense to keep it open with the details known, somebody probably needs to analyse what's happening in home assistant, when that point to an issue on our end you can always reopen (or open a new ticket if its in another area).
