### ISSUE TITLE
Unbound crashes

### ISSUE THREAD

**Issue by q-wertz** [opnsense/core#6147]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

After a certain period DNS resolving is broken and I have to restart the firewall (sometimes unbound DNS is stopped and starting it again is enough. Restarting only unbound does not work).

**To Reproduce**

1. Have a working setup
2. Let it run for certain days
3. After some time DNS resolving is not working anymore
4. Sometimes unbound is shown as stopped in the interface and can be started
5. Sometimes it is shown as running but cannot be restarted

**Expected behavior**

Unbound does not crash

**Describe alternatives you considered**

I am not sure if it is related to my provider connection resets (also the stack trace says something about  'newwanip'…)

**Screenshots**

**Relevant log files**

```
[18-Nov-2022 10:49:55 Europe/Berlin] Error: Call to undefined function reopenlog() in /usr/local/etc/inc/plugins.inc.d/unbound.inc:551
Stack trace:
#0 /usr/local/etc/inc/plugins.inc.d/unbound.inc(198): unbound_add_host_entries(Array)
#1 /usr/local/etc/inc/plugins.inc.d/unbound.inc(339): unbound_generate_config()
#2 /usr/local/etc/inc/plugins.inc(288): unbound_configure_do(false, 'wan')
#3 /usr/local/etc/rc.newwanipv6(106): plugins_configure('newwanip', false, Array)
#4 {main}
```

In `LOg Files` -> `Backend`:
```
2022-11-19T10:52:09 | Error | configd.py | Timeout (120) executing : unbound cache dump
```

**Additional context**

I think it started with the 22.7 version of OPNsense

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 22.7.8-amd64
FreeBSD 13.1-RELEASE-p3
OpenSSL 1.1.1s  1 Nov 2022

AMD GX-412TC SOC

**Comment by fichtner** [comment]
Perhaps you want to do a health audit first. On 22.7.8 config.inc includes `reopenlog()` which is the first require of file rc.newwanipv6 so I don't see how this would be missing the function.

Unbound-control is problematic in general, you can try to turn on "Flush DNS cache during reload" in the Unbound settings if you continue to have issues with it.

**Comment by q-wertz** [comment]
Thanks. Sonce enabling `Flush DNS cache during reload` it never happened again.
