### ISSUE TITLE
UPNP issues with multiple systems playing same game

### ISSUE THREAD

**Issue by tiurs** [opnsense/core#6148]
This is pretty much the exact issue. 
https://forum.netgate.com/topic/169837/upnp-fix-for-multiple-clients-consoles-playing-the-same-game
Has fix for pfsense is there similar fix for OpnSense?
image below first system works fine then second system creates multiple entries and fails to connect to game servers. 

![image](https://user-images.githubusercontent.com/27645243/203452277-1b5bf3ee-2661-4c59-950d-1f606154622e.png)

**Comment by fichtner** [comment]
Duplicate.
