### ISSUE TITLE
UPnP Fails for multiple clients/consoles playing the same game

### ISSUE THREAD

**Issue by tiurs** [opnsense/core#6149]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**
UPnP Fails for multiple clients/consoles playing the same game

A clear and concise description of what the bug is, including last known working version (if any).

*Tip*: to validate your setup was working with the previous version, use opnsense-revert (https://docs.opnsense.org/manual/opnsense_tools.html#opnsense-revert)

**To Reproduce**

enabled upnp 
connect on first system 
connect on second system to the same server
multiple ports are created for upnp for second system but it fails to connect. 

**Expected behavior**

When using upnp for ports first system works fine second system can not connect.  multiple ports are created for the second system. 

Here is article about the issue in pfsense 
https://forum.netgate.com/topic/169837/upnp-fix-for-multiple-clients-consoles-playing-the-same-game 

A clear and concise description of any alternative solutions or workaround you considered.

![image](https://user-images.githubusercontent.com/27645243/203457186-4770418d-36fd-417a-9a94-9eedc2206ceb.png)

**Relevant log files**

If applicable, information from log files supporting your claim.

Two system on the same network using upnp to connect to same server. 

Software version used and hardware type if relevant, e.g.:
OPNsense 22.7.8-amd64

miniupnpd | 2.1.20200510,1 | 155KiB | OPNsense | BSD3CLAUSE | UPnP IGD implementation which uses pf/ipf

**Comment by hyperenergy** [comment]
Good news @tiurs, @Tawmu and @fichtner have been working on this!  I've been keeping an eye on the issues fichtner mentioned here, opnsense/plugins#3183, most recently opnsense/plugins#3096.

**Comment by fichtner** [comment]
And still a duplicate.
