### ISSUE TITLE
GUI VLAN broken if non root

### ISSUE THREAD

**Issue by Makss39** [opnsense/core#6151]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

VLAN creation and management is impossible for a non root user.

**To Reproduce**

1. Create a "supervisor" group
2. On the privileges assigment, untick only "GUI - All pages"
3. Assign an user to this group
4. Login with the new user
5. Go to Interfaces: Other Types: VLAN
6. Try to add a VLAN
7. Parent list is empty

 **Expected behavior**

We should be able to add a VLAN with a non root user.

**Describe alternatives you considered**
Nothing

**Screenshots**

With a supervisor account:
![image](https://user-images.githubusercontent.com/61969235/203511033-a5390d1d-0c7a-4f64-925b-b3059aed8d8a.png)

With a root account:
![image](https://user-images.githubusercontent.com/61969235/203511171-98d718aa-8f16-4fa5-87a8-3a598f67a34b.png)

**Relevant log files**
No logs.

**Additional context**
Nothing

**Environment**

OPNsense 22.7.8-amd64
FreeBSD 13.1-RELEASE-p3
OpenSSL 1.1.1s 1 Nov 2022
Intel(R) Core(TM) i5-4460 CPU @ 3.20GHz (4 cores, 4 threads)

**Comment by Makss39** [comment]
Thanks for fast answer, but sorry, error while patching.
![image](https://user-images.githubusercontent.com/61969235/203520199-c5063b9e-ac4c-4019-abb8-64d686293444.png)

**Comment by fichtner** [comment]
Too many changes then, you can adjust the file per hand extend api url with `_settings/*` and run second command

**Comment by Makss39** [comment]
I have replaced the concerned files by the updated one from github.
![image](https://user-images.githubusercontent.com/61969235/203566176-8b3ba3e6-37da-40d8-833d-31349b237b52.png)

It fix the VLAN issue, but now the VIP Status/Settings page are not accessible anymore.

Following, the PHP error :

> [23-Nov-2022 12:29:47 Europe/Paris] Phalcon\Mvc\Dispatcher\Exception: Action 'vip' was not found on handler 'interface' in /usr/local/opnsense/www/index.php:70
Stack trace:
#0 [internal function]: Phalcon\Mvc\Dispatcher->throwDispatchException('Action 'vip' wa...', 5)
#1 [internal function]: Phalcon\Dispatcher\AbstractDispatcher->dispatch()
#2 /usr/local/opnsense/www/index.php(70): Phalcon\Mvc\Application->handle('/ui/diagnostics...')
#3 {main}
[23-Nov-2022 12:29:59 Europe/Paris] Phalcon\Mvc\Dispatcher\Exception: Action 'vip' was not found on handler 'interface' in /usr/local/opnsense/www/index.php:70
Stack trace:
#0 [internal function]: Phalcon\Mvc\Dispatcher->throwDispatchException('Action 'vip' wa...', 5)
#1 [internal function]: Phalcon\Dispatcher\AbstractDispatcher->dispatch()
#2 /usr/local/opnsense/www/index.php(70): Phalcon\Mvc\Application->handle('/ui/diagnostics...')
#3 {main}
[23-Nov-2022 12:30:40 Europe/Paris] Phalcon\Mvc\Dispatcher\Exception: OPNsense\Interfaces\VipController handler class cannot be loaded in /usr/local/opnsense/www/index.php:70
Stack trace:
#0 [internal function]: Phalcon\Mvc\Dispatcher->throwDispatchException('OPNsense\\Interf...', 2)
#1 [internal function]: Phalcon\Dispatcher\AbstractDispatcher->dispatch()
#2 /usr/local/opnsense/www/index.php(70): Phalcon\Mvc\Application->handle('/ui/interfaces/...')
#3 {main}
[23-Nov-2022 15:01:38 Europe/Paris] Phalcon\Mvc\Dispatcher\Exception: OPNsense\Interfaces\VipController handler class cannot be loaded in /usr/local/opnsense/www/index.php:70
Stack trace:
#0 [internal function]: Phalcon\Mvc\Dispatcher->throwDispatchException('OPNsense\\Interf...', 2)
#1 [internal function]: Phalcon\Dispatcher\AbstractDispatcher->dispatch()
#2 /usr/local/opnsense/www/index.php(70): Phalcon\Mvc\Application->handle('/ui/interfaces/...')
#3 {main}

**Comment by Makss39** [comment]
No worries, it can wait for the next update !
I will revert to the original files.

Cheers

**Comment by fichtner** [comment]
@Makss39 made a proper backport for you to try

    # opnsense-patch cdbd1dc
    # /usr/local/etc/rc.configure_plugins


Cheers,
Franco

**Comment by Makss39** [comment]
@fichtner perfect, it works as expected ! Thx !
