### ISSUE TITLE
Can not set DNS domain root at namecheap with web interface for DDclient. 

### ISSUE THREAD

**Issue by DrekiDegga** [opnsense/core#6155]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

Namecheap uses an unusual naming convention for the Root DNS entry.

I am able to set subdomain.example.com using the web interface of DDclient with no problems but in order to set the IP address for example.com with namecheap, you must use @.example.com for the record name. The web interface will not allow the entry of '@' in the hostname field.

I was able to edit the file '/usr/local/etc/ddclient.conf' to include @.example.com and that works prefectly so I believe the problem is that the web interface simply wont allow '@' in the hostname field

A clear and concise description of what the bug is, including last known working version (if any).

I tried to report this issue two months ago but Apparently I didn't use a template to report the bug so the bot just buried my post as incomplete. I didn't see the point in filling out the template line by line because this is a simple bug and my explanation was thorough but here I am two months later wasting my time.  see  opnsense/core#6058

*Tip*: to validate your setup was working with the previous version, use opnsense-revert (https://docs.opnsense.org/manual/opnsense_tools.html#opnsense-revert) - no

**To Reproduce**

1. Go to 'open sense web admin panel'
2. Click on 'Services>Dynamic DNS (NOT legacy)>Settings'
3. Click add and try to add the root domain of a domain hosted from namecheap, just like I described in the description setion of this silly template.
4. It won't work, because the web interface will not allow you to add "@.example.com", as I described in the description section of this silly template.

**Expected behavior**
I expect to be able to add the root domain of my namecheap hosted domain to a dynamic DNS configuration.

**Describe alternatives you considered**

Just continuing to edit the file to make changes since I know how to do that and reporting the bug will take so much of my time it almost doesn't seem worth it.

**Screenshots**

If anyone really needs screenshots please ask.

**Relevant log files**

no

**Additional context**

Bananas

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 22.7.4-amd64
FreeBSD 13.1-RELEASE-p2
OpenSSL 1.1.1q  5 Jul 2022

**Comment by AdSchellevis** [comment]
Transferring back to core, looks like an interpretation issue in https://github.com/opnsense/core/commit/f110c988d4c5722308d0ec7a4ef5b86c0b3f767c, need to validate if we can fix this in core or we should add a custom validator in the plugin.
