### ISSUE TITLE
OpenVPN log instance id

### ISSUE THREAD

**Issue by Skywalker-11** [opnsense/core#6156]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**

When running multiple OpenVPN instances on the same system it is not possible to differentiate the instances in the vpn log

**Describe the solution you like**
The process name for syslog logging can be changed via the `daemon` config option. Changing this line 

https://github.com/opnsense/core/blob/1472df66fb36c93bd44c3b1857b92fd49cb2c979/src/etc/inc/plugins.inc.d/openvpn.inc#L525
to
```
    $conf .= "daemon openvpn{$mode_id}\n";
```
or similar lets OpenVPN write the logs with a  process name like `openvpnserver4`. 
To make it easier to identify the corresponding instance it could help to show the instance id also in the web gui or use a sanitized part of the description field.

**Additional context**

Add any other context or screenshots about the feature request here or links to relevant forum thread or similar

**Comment by AdSchellevis** [comment]
@Skywalker-11 thanks for the hint, https://github.com/opnsense/core/commit/5586e49d86cbf883d3a35e2741e5061bd89ee4ef adds the process name
