### ISSUE TITLE
[BUG] Interface routes not installed in FRR routing table (Zebra)

### ISSUE THREAD

**Issue by smyers119** [opnsense/core#6170]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X ] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

I have a interface gateway for a wireguard interface. ("dynamic" in opnsense terms). Static routes to that interface gateway do not get installed in FRR route table causing bgp invalid next-hop. This stops all bgp routes from getting installed as well.

**To Reproduce**

Install os-frr and os-wireguard

After wireguard is connected:
Create a dynamic gateway pointing to wireguard interface
Create a /32 route pointing towards created gateway
Check frr table under routing --> diagnostic --> general

Note No route in FRR table.

**Expected behavior**
Route installed in Zebra

**Describe alternatives you considered**
Current Workaround:
From shell start staticd
`staticd -d`
From vtysh add static interface route

```
vtysh
>config
>ip route 1.1.1.1/32 wg1
>exit
```

**Environment**
OPNsense 22.7.9-amd64
FreeBSD 13.1-RELEASE-p5
OpenSSL 1.1.1s  1 Nov 2022

**Comment by smyers119** [comment]
bump

**Comment by mimugmail** [comment]
Why do you need a static gateway set outside of the FRR scope when using BGP? 
Wireguard itself mangles the routing table. 

Gateways via System : Gateways : Single should not be used at all when it comes to dynamic routing

**Comment by smyers119** [comment]
my wireguard peer is a /32, so i need to create a static route to that /32 via interface wireguard to reach the address.

**Comment by smyers119** [comment]
> 

Zebra can not access the nexthop and that can be confirmed by checking "show bgp nexthop" in vtysh.  The /32 shows invalid until i add the static route

**Comment by smyers119** [comment]
and its a easily reproduicable bug report.  not a support ticket.

**Comment by mimugmail** [comment]
So its a feature request cause of missing staticd. I remember limitations with ospf and multicast but thought I got bgp running over it :/

**Comment by AdSchellevis** [comment]
I’m not using WireGuard, but from earlier support cases I expect the next hop should be accessible using standard “netmask” rules, in which case /32 just isn’t a valid option. We changed our tunnel calculations on IPsec (VTI) for the same reason as well a long time ago.

**Comment by bimbar** [comment]
Same problem here, I have a /24 on my wireguard interface, and I can set a static route with that gateway, but frr will not accept routes without an IP as the nexthop, it seems.
