### ISSUE TITLE
URL table aliases "Loaded#" can mislead

### ISSUE THREAD

**Issue by NOYB** [opnsense/core#6176]
FIREWALL: ALIASES

For URL table aliases, the "Loaded#" is the max of what is actually loaded in the packet filter, or the number of entries in the alias table file.
This value can be misleading by indicating that the table is loaded in the packet filter even if it is not.

Is there a use for showing the number of entries in the alias table file rather than what is actually loaded in the packet filter?

Appears to be intended behavior.  Though maybe not a good behavior.  Otherwise, it may be a bug.

**Comment by AdSchellevis** [comment]
it's intended https://github.com/opnsense/core/blob/c96e5f88b480a23753615297ccae6865d505c9d5/src/opnsense/scripts/filter/pftablecount.py#L56-L57

Explaining the columns in the documentation (https://docs.opnsense.org/manual/aliases.html) would be a nice addition, the current (active) aliases are always inspectable from the diagnostics page.

**Comment by NOYB** [comment]
Why does firewall aliases page need to display planned size?  What is the value in that?
Seems like it should display the actual active firewall packet filter table size.

**Comment by AdSchellevis** [comment]
size before optimization and a clear indication which alias isn't able to load when the reserved space is too small.
