### ISSUE TITLE
[Bug] [squid] Proxy no longer binds to vips

### ISSUE THREAD

**Issue by wolfspyre** [opnsense/core#6181]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X ] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X ] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**
Squid doesn't seem to bind to VIPs any longer.  

Not sure when this changed. 

I'm noticing it on `23.1b_87`

[core/src/opnsense/service/templates/OPNsense/Proxy/squid.conf](https://github.com/opnsense/core/blob/31b54c4b53cc2db05effb854c290be66585e03b5/src/opnsense/service/templates/OPNsense/Proxy/squid.conf#L44)
Line 44 in [31b54c4](https://github.com/opnsense/core/commit/31b54c4b53cc2db05effb854c290be66585e03b5)

 {%                 if intf_item.interface == interface and intf_item.type == 'single' %} 
it seems `intf_item.type` is no longer a thing?
 so this logic never fires, and listener entries aren't added to squid's config.

as a result, squid no longer listens on VIP addresses.

**To Reproduce**

I'd imagine creating a vip and trying to have proxy listen on it?

**Expected behavior**

I'd expect squid to bind on the VIPs for the selected listen addresses.

**Describe alternatives you considered**

running squid elsewhere? but this is likely more trouble than it's worth.

**Additional context**

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 23.1.b_87

**Comment by fichtner** [comment]
Thanks for running the development version! That's indeed an issue after MVC/API conversion. Apparently plugins also have this issue:

```
/usr/core # git grep intf_item.type
src/opnsense/service/templates/OPNsense/Proxy/squid.conf:{%                 if intf_item.interface == interface and intf_item.type == 'single' %}
/usr/plugins # git grep intf_item.type
databases/redis/src/opnsense/service/templates/OPNsense/Redis/redis.conf:{%         if intf_item.interface == listen_interface and intf_item.type == 'single' %}
security/tor/src/opnsense/service/templates/OPNsense/Tor/torrc:{%         if intf_item.interface == listen_interface and intf_item.type == 'single' %}
www/nginx/src/opnsense/service/templates/OPNsense/Nginx/webgui.conf:{%     if intf_item.type == 'single' %}
```

**Comment by fichtner** [comment]
I'm changing this to "cleanup" since not a production bug.
