### ISSUE TITLE
Unable to assign/save new interface

### ISSUE THREAD

**Issue by sfr0st** [opnsense/core#6183]
**The current OPNsense version where the bug first appeared**
OPNsense 22.7.9_3-amd64

**The last OPNsense version where the bug did not exist**
Unknown. All my interfaces/VLANs were created and assigned many versions of OPNsense ago and this issue did not exist then.

- The exact URL of the GUI page involved (if any)

https://XXX.XXX.XXX.XXX/interfaces_assign.php

**A list of steps to replicate the bug**
Unable to save/apply changes under "New interface:". This is problem exists when trying to assign a physical interface or assign a VLAN to a physical interface. Once you hit "Save" the page refreshes and no new interfaces are created. I am able to make changes to existing assignments. This problem exists with both the root and non-root admin user accounts.

**Comment by fichtner** [comment]
There is a separate button for adding ;)
