### ISSUE TITLE
.ssh/authorizedkeys gets deleted when I deactivate "allow user/pwd" in ssh web-ui dialog 

### ISSUE THREAD

**Issue by bachmarc** [opnsense/core#6185]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [ x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [ x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**
.ssh/autorized_keys file gets wiped by UI when "allow user/pwd" is toggled

**To Reproduce**
Logon to Opnsense (22.7.8) via ssh root/pwd
create a file .ssh/autorized_keys which contains a public key
deactivate "allow user/pwd" in web ui to restrict it to key only
try to logon ... it fails

To get it done you need to logon with user/pwd, toggle UI while logged on in ssh, add the key after password is switched off. 

**Expected behavior**

A written authorized_keys file should not be touched by Web UI or depend on the order of editing and toggling 

**Describe alternatives you considered**

A clear and concise description of any alternative solutions or workaround you considered.

**Screenshots**

**Relevant log files**

If applicable, information from log files supporting your claim.

**Additional context**

**Environment**
22.7.8

Software version used and hardware type if relevant, e.g.:

OPNsense 22.7.8 (amd64, OpenSSL).
Intel® Xeon™ E3

**Comment by AdSchellevis** [comment]
use the gui (System: Access: Users --> [select user] --> Authorized keys)
