### ISSUE TITLE
Feature Request User Site on WAN

### ISSUE THREAD

**Issue by andreasvel** [opnsense/core#619]
Hi,
Feature request for a site reachable via WAN with Personal account (ideal with OTP)
to be able to download OPNVPN Profiles. 

Like Sophos User Portal

**Comment by 8191** [comment]
Do you expect the OpenVPN Profiles being offered there automatically based on the current configuration, or are you looking for something like a tiny externally reachable web-server to offer custom files for download?

**Comment by fabianfrz** [comment]
I think @andreasvel wants a portal, where it is possible to log in and download the configuration files for the client as well as the certificates and the private keys.

**Comment by 8191** [comment]
Yes, but shall the configs and keys be put there automatically (according to the configured OpenVPN servers) or shall the admin put the files there?

**Comment by fichtner** [comment]
It's the administrator's responsibility to enable the GUI on the WAN. The users can already login if given rights, the part that is missing is a sanity improvement for the client export pages so that only a specific (non-admin user) can download his/her own certificates:  https://github.com/opnsense/core/issues/375

**Comment by andreasvel** [comment]
It was thought as an easy just one site to get the openvpn profile or informations to the IPSEC Tunnes without Passwords

i agree to fichtner - but if its simple enough?
also i would love to get this work with otp

**Comment by fichtner** [comment]
It's simple because if the User Profile was configured to only show the export page, it will be visible right after login. :)

**Comment by andreasvel** [comment]
yes, but - if you activate that the user can change the pw this is the first page which is shown... also he can see the other profiles not only his profile (vpn)

**Comment by fichtner** [comment]
#375 deals with the latter issue, the first one we can fix, too. I will add an issue.

**Comment by andreasvel** [comment]
what about the IPSEC Page Preshared key??? should it be possible to be configed by the user? is there a scenario

**Comment by fichtner** [comment]
PSKs should be shared out of band. It would be lots of management code to map a PSK to a user/group of users just for display.

**Comment by andreasvel** [comment]
i agree in this part that i would say it should just be able to edit from a LAN Site not from VPN/WAN Site

**Comment by andreasvel** [comment]
to hide the other profiles is more problematic? a milestone for 16.7???

**Comment by fichtner** [comment]
yes, but - if you activate that the user can change the pw this is the first page which is shown

This isn't true. A new user that is not an admin and that only has OpenVPN export page rights will not be allowed to change his password. A user with password change privileges will also be redirected to the export page, not the password page.

**Comment by fichtner** [comment]
Staff is short, any help is welcome...

**Comment by andreasvel** [comment]
i tested it. my user can just openvpn export and user
see my config http://www.bilder-upload.eu/show.php?file=2df1be-1452264684.png
the result is that first page that is shown is the user site to change pw

**Comment by fichtner** [comment]
Maybe the assignment order matters?

**Comment by andreasvel** [comment]
no i cant test it :( cant login as normal user any more :( i guess it could be a error at my config.xml?!

**Comment by andreasvel** [comment]
deleted the user, recreated now it works fine
