### ISSUE TITLE
Can't select more than one entry in lists

### ISSUE THREAD

**Issue by eBeyond** [opnsense/core#6192]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

On many sites in the configuration, where I can select multiple entries it's still not possible. I try to select multiple entries to delete but   if I select more than one entry the former entry was deselected (unchecked).

This is in the current and former version of opnsense

**Comment by AdSchellevis** [comment]
good point, that button shouldn't be there, fixed in https://github.com/opnsense/core/commit/8ca676e43bad6595d40954c08b2f0f556f9d429e
