### ISSUE TITLE
Feature: Firewall: also show floating rules on interface tabs

### ISSUE THREAD

**Issue by 8191** [opnsense/core#620]
Actually I thought that was already introduced some time ago, but never actually checked it. So it turns out, that currently this feature is already "implemented" as a bug in some cases (i.e. only one assigned interface).
But anyway, I think it would be handy to merge interface-only and floating rules at the interface tabs, since one might overlook a floating rule when creating new rules or investigating existing rules. The rules of cause should be tagged somehow as floating.

**Comment by oparoz** [comment]
I agree, maybe in a separate block, like in the outbound nat rule panel?

**Comment by AdSchellevis** [comment]
timeout
