### ISSUE TITLE
Firewall groups in the interface section

### ISSUE THREAD

**Issue by bdonauba** [opnsense/core#6201]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [ x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [ x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**

If one organizes the rules in groups, those groups apply to the interfaces as well.

While in the Firewall/Rules section all groups and interface are visible in the interfaces section interfaces that are member of a group do not appear. One has to search the groups to find the interfaces.

See this example the interface VLAN022_WLANDATA does not appear in the interfaces section because it is a member of a group:

![firewall](https://user-images.githubusercontent.com/101336450/208687505-16f9d9fb-955b-42bf-8f67-2b7b0febc088.png)

**Describe the solution you like**

I would prefer to see all interfaces in the interfaces section immediately. 
I even want to ask why are the groups displayed in the interfaces section at all?

**Describe alternatives you considered**

No groups but all interfaces in the interfaces section.

**Comment by AdSchellevis** [comment]
not really possible due to the number of levels the menu supports.

**Comment by AdSchellevis** [comment]
never mind, you want to remove the groups in the interfaces, not adding them in the rules. Not likely going to happen, the extra grouping was a feature introduced a long time ago not planning to revert it.

**Comment by fichtner** [comment]
The idea (which was discussed and explained before) was to reduce the number of entries in the interfaces submenu, which it still does.

We discussed preventing grouping in the menu as an additional group option, but I guess we've come a long way without it...


Cheers,
Franco

**Comment by fichtner** [comment]
PS: it was #4016

**Comment by bdonauba** [comment]
@fichtner wrote:
> We discussed preventing grouping in the menu as an additional group option, but I guess we've come a long way without it...

I would vote for this option because I find it rather tedious to search my interfaces in the groups.

So there's nothing left to but thank you for your immediate support and wish you nice holidays.

Regards,
Bernhard

**Comment by fichtner** [comment]
Hi Bernhard,

I'm not sure it will fit 23.1 timeline, but I’ll try.


Happy holidays!
Franco
