### ISSUE TITLE
API call ipsec / leases returns 'bad request'  (Resources (LeasesController.php))

### ISSUE THREAD

**Issue by msroedel** [opnsense/core#6209]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x ] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x ] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

Requesting ipsec/leases/pools or ipsec/leases/search returns 'bad request'. 

Version tested: 22.7.10_2

**To Reproduce**
1. Use Postman to connect via  api-key and secret
2. tested several api calls successfully
3. tried https://<hostname>/api/ipsec/leases/pools or  .../search
4. Both resulted in  "controller OPNsense\\IPsec\\Api\\LeasesController not found", "status": 400"

**Expected behavior**

Api should return list of ipsec leases

Software version used and hardware type if relevant, e.g.:

Version | 22.7.10_2 
Architecture | amd64 |  
Flavour | OpenSSL |  
 Commit | bdce9463f

**Comment by AdSchellevis** [comment]
Best use the inspect button from the browser to check what it's calling, in this case the most likely endpoint your looking for is a `POST` to `https://xxx.xxx.xxx.xxx/api/ipsec/leases/search`. As a general rule of thumb, if the gui works, its highly unlikely the api doesn't (same code path)

**Comment by msroedel** [comment]
https://<hostname>/api/ipsec/leases/search  in browser returns: 
{"message":"controller OPNsense\\IPsec\\Api\\LeasesController not found","status":400}

According to the documentation ist should be a GET, not a POST:
![image](https://user-images.githubusercontent.com/33430812/209093701-24e7b3f5-9030-4852-9578-e2f111cff902.png)

whereas e.g. https://<hostname>/api/ipsec/sessions/searchPhase1  delivers correct replies both in postman and Browser. The GUI also works correctly.

**Comment by fichtner** [comment]
Is this even on stable/22.7? I’m not sure. Docs could be from master.

**Comment by AdSchellevis** [comment]
can you please go the the gui, try the function your seeking from there, if that doesn't work, open a ticket with the issue reported there.

**Comment by fichtner** [comment]
Latest commit from stable/22.7, see version

**Comment by msroedel** [comment]
As mentionend above, the function works as expected in the GUI. (VPN - IPSEC - Lease status)

**Comment by AdSchellevis** [comment]
ok, then it's clear indeed. not using the development branch, endpoint won't be there. check the uri in the page, it likely ends with .php (all mvc pages show /ui/)

**Comment by AdSchellevis** [comment]
you can use the endpoint as of 23.1 when it's available in stable.

**Comment by msroedel** [comment]
Correct: https://hostname/diag_ipsec_leases.php
So the docs are ahead of the current stable version. Thanks!

**Comment by AdSchellevis** [comment]
not fully intentional in this case, but they are indeed. busy preparing for 23.1, sorry for  the noise

**Comment by msroedel** [comment]
That happens. :-)  You're welcome.
