### ISSUE TITLE
Feature Request on OpenVPN

### ISSUE THREAD

**Issue by andreasvel** [opnsense/core#621]
Hi,
should be possible to define from Administration how the  "Host Name Resolution" works.

Scenario:
I got 2 WANs - just one should be for the users - the other is rescue/spare for me should not be able to choice.

thx

**Comment by AdSchellevis** [comment]
I'm not sure what you want to accomplish here, but you could either push a (list of) dns server(s) from your OpenVPN to your clients using the list of dns servers or specify client specific overwrites.

Questions about how to use OPNsense in specific scenarios are best discussed in the forum.
