### ISSUE TITLE
Automatic floating rule "block all targeting port 0" displayed as blocking "*"

### ISSUE THREAD

**Issue by pinysuse** [opnsense/core#6215]
**Important notices**

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

~/firewall_rules.php?if=FloatingRules shows the automatically generated rule

![2022-12-26_fw-rules_floating-auto_block-all-targeting-port-0](https://user-images.githubusercontent.com/37483735/209573464-fb4033f4-3909-49fb-a148-4d774092a0ab.png)

This appears to block any TCP/UDP traffic!

**To Reproduce**

1. Go to ~/firewall_rules.php?if=FloatingRules
2. Expand the automatically generated rules
3. See issue

**Expected behavior**

The target port(s) should be depicted as `0` instead of `*`.

**Additional context**

Inspecting the source code in the browser it appears that
`<td class="view-info">` is used.

[Searching for "block all targeting port 0"]( https://github.com/opnsense/core/search?q=block+all+targeting+port+0)
shows that port number `0` [is set in the rule "src/etc/inc/filter.lib.inc" #266](https://github.com/opnsense/core/blob/ffd64bcfd5dfc3bd0a016739702e65511b74e4be/src/etc/inc/filter.lib.inc) itself.

[firewall_rules.php](https://github.com/opnsense/core/blob/81a355b5c011ca85840be90791a2a19a745662ba/src/www/firewall_rules.php)
has following code fragment (twice):

```
<td class="view-info hidden-xs hidden-sm">
                          <?=!empty($filterent['to_port']) ? $filterent['to_port'] : "*";?>
                      </td>
```

> It appears that the port value `0` is treated as `empty` by PHP.

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 22.7.9_3-amd64
AMD GX-412TC SOC (4 cores, 4 threads)
APU.4D4

**Comment by AdSchellevis** [comment]
@pinysuse nice catch, has been in there for quite some time probably. https://github.com/opnsense/core/commit/a9f4b4b5209eeed5270f43b35e75411eac26f4b1 should fix this.
