### ISSUE TITLE
VTI interface is not created

### ISSUE THREAD

**Issue by Trapulo** [opnsense/core#6217]
**Describe the bug**

Creating a Route based site2site IPSEC the virtual interface is not created and a gateway cannot be assigned.

**To Reproduce**

Using this guide:
https://docs.opnsense.org/manual/how-tos/ipsec-s2s-route.html

At step 5 the IPSEC interface does not exist

**Expected behavior**

I aspect to find the virtual interface to configure and use

**Additional context**

Tunnel configured as "ESP Route-based", up and running.

**Environment**

OPNsense 22.7.10_2-amd64
FreeBSD 13.1-RELEASE-p5
OpenSSL 1.1.1s 1 Nov 2022

A fresh installation

**Comment by slalabs** [comment]
Can confirm this behavior. Also a fresh installation.

**Comment by fichtner** [comment]
It’s a bit unlikely. But FWIW, there are two ipsec implementations now and the obvious question is have you tried the other? Couldn’t discern which one you tried but assuming the tunnel one as per documentation.

**Comment by slalabs** [comment]
We cannot implement and debug ~50 IPsec tunnels on a weekend. The "legacy" implementation should also work, like before.

**Comment by fichtner** [comment]
I’m not saying it doesn’t. See my first post.

Furthermore I’m not going to debug 50 tunnels on community support. 😉


Cheers,
Franco

**Comment by slalabs** [comment]
Thanks for your answer, switching to pfSense now. There strongswan implementation is not broken after every update 😉

**Comment by Trapulo** [comment]
pfsense has A LOT of problems with VTI. I moved from pfSense to OPNSense for that.

**Comment by fichtner** [comment]
> Thanks for your answer, switching to pfSense now. There strongswan implementation is not broken after every update 😉

May you live in interesting times!

FWIW, your report is really shallow. If you expect community support you need to provide more information.


Cheers,
Franco
