### ISSUE TITLE
Uncaught TypeError in NAT configuration

### ISSUE THREAD

**Issue by splix** [opnsense/core#6218]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

Tried to setup _Firewall: NAT: Port Forward_ but it seems I've entered an invalid option. I guess it's a destination port entered as `any`, though I'm not sure because I cannot open that page anymore.

Now when I open `/firewall_nat.php` page I see in the _Ports_ column: 

```
Fatal error: Uncaught TypeError: Unsupported operand types: int - string in /usr/local/www/firewall_nat.php:492 Stack trace: #0 {main} thrown in /usr/local/www/firewall_nat.php on line 492
```

Most importantly, it **broke the whole NAT config page**. I.e., opnSense doesn't allow to edit it, remove or add any new rule. In fact I cannot go to other pages from that page, unless I refresh it manually.

**Environment**

OPNsense 22.7-amd64

**Comment by AdSchellevis** [comment]
update? looks like https://github.com/opnsense/core/commit/77569c29fb686cc5deccadf4004a6d9be91d5599 fixed a couple of months ago

**Comment by splix** [comment]
Oh, I thought I have the latest version. Upgraded to the 22.7.10_2 and it works now. Thank you
