### ISSUE TITLE
Are alias table entry and rule statistics counters written to disk or kept only in RAM?

### ISSUE THREAD

**Issue by NOYB** [opnsense/core#6219]
Don't see anything in manual about the alias counters.
https://docs.opnsense.org/manual/aliases.html

Manual mentions the firewall rule statistics counters but not if written to disk.
https://docs.opnsense.org/manual/firewall.html

Interest is in minimizing USB flash drive write cycles.

22.7.10_2
VGA image install

**Comment by AdSchellevis** [comment]
traffic counters only in memory, see https://www.freebsd.org/cgi/man.cgi?pf.conf(5)
