### ISSUE TITLE
Bug Report on Dyndns and related to OpenVPN

### ISSUE THREAD

**Issue by andreasvel** [opnsense/core#622]
Hi,
if you choice custom as service no hostname can not be added to use it in OpenVPN

**Comment by 8191** [comment]
I'm not sure if I clearly understand the bug: the DynDNS service type "custom" is broken, correct? Is OpenVPN related to the bug, or are you just trying to use the DynDNS records for external VPN access?

**Comment by andreasvel** [comment]
Just trying to user the dyndns settings for the vpn access/hostname for for the vpn
the dyndns service itselfs works

the relation is that you cant use the dyndns entry/service for the openvpn

**Comment by fichtner** [comment]
(ist vielleicht einfacher kurz auf deutsch zu erklären, ich verstehe es auch nicht)

**Comment by andreasvel** [comment]
sorry
also ich will für die opnvpn den dyndns hostnamen nehmen
da ich das ding aber custom definiert habe fehlt der hostname für die openvpn tunnel

**Comment by fichtner** [comment]
Okay, bei custom und customv6 fehlt der Hostname, den könnte man hinzufügen in DynDNS. Wie aber kommt der Name zu OpenVPN? Im Client-Export Formular?

**Comment by fichtner** [comment]
Sollte erledigt sein, danke :)

Der Nutzer muss nun selbst im custom Eintrag von DynDNS den Hostnamen angeben, danach kann er auch übernommen werden.
