### ISSUE TITLE
OpenVPN IPv6 Redirect Gateway

### ISSUE THREAD

**Issue by tabacha** [opnsense/core#6220]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x ] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x ] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**

We want to get all IPv6 Traffic though OpenVPN. But there is only one Option in the GUI:
"Redirect Gateway" which will only work for IPv4. The option will add a 
`push "redirect-gateway def1"` to openvpn config file.

**Describe the solution you like**

Rename "Redirect Gateway"  to "Redirect IPv4 Gateway" 

Add a new GUI Option: "Redirect IPv6 Gateway" 
which will set `push "redirect-gateway ipv6"` to the openvpn config file.

**Describe alternatives you considered**

Alternative is to add the string: `push "redirect-gateway ipv6"`  to the advanced options. This works for us.

**Additional context**

no

**Comment by AdSchellevis** [comment]
For now the advanced options would do the trick indeed.

We are discussing a re-write of the openvpn legacy module at the moment to offer api support and more align it with the actual configuration logic (https://openvpn.net/community-resources/reference-manual-for-openvpn-2-5/). 

For 23.1 we rewrote the IPsec module, if a similar strategy works for OpenVPN we might consider that as well for a future version ( in which case it's practical to know which options are practical to offer).

**Comment by AdSchellevis** [comment]
https://github.com/opnsense/core/pull/6584
