### ISSUE TITLE
Feature Request :  Interface Status on Assignment Page

### ISSUE THREAD

**Issue by bigops** [opnsense/core#6222]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [ X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X ] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**

This is not related to a problem but improve usability 

A clear and concise description of what the problem is including your motivation for the request,

The interface assignments page shows all interfaces that are currently assigned and also what is not assigned.  But the interface icons are grey in color which does not show if the interface is physically connected (Assigned interfaces can be seen from the dashboard but having a green color here also would be more user friendly).  The pulldown when assigning interface shows either red or green which shows it is connected or not.  So I think the code and the logic to show status (green/red) is already there.  It would be good if  after assignment the color would also show up

**Describe the solution you like**

The carrier status of the interface can be shown in either green or Red

**Describe alternatives you considered**

**Additional context**

**Comment by fichtner** [comment]
You have to take into account that some drivers (pseudo devices) don’t have a carrier state and sometimes are always presented as „up“ as well. It’s a bit difficult to discern used vs. unused although the info in the details is useful (and should be there).

**Comment by fichtner** [comment]
works on my end in 23.1
