### ISSUE TITLE
OpenVPN Option: Deny if no Client Specific override is found

### ISSUE THREAD

**Issue by tabacha** [opnsense/core#6224]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**

In our Company we want to assign a fixed IP to every employee Notebook connecting through OpenVPN / OpnSense to the office. This allows us to track, who has logged in on a server just by looking at the ip addresse, and allows firewall rules like:
Holgers notebook is allowed to ssh to Holgers office-PC.

**Describe the solution you like**

I would like to speficy an IP Address for the Tunnel IP in the "Client Speficic Override" (this works). But also
deny is a client is connected but no "Client Speficic Override"  is found (for example a typo in the CN)

For this i would like a checkbox in the OpenVPN -> Servers Tab

[ ] Deny client if no client specific override is found.

I have read in https://github.com/opnsense/core/issues/6220 that there is a rework planed so this could be done in this rework.

**Describe alternatives you considered**

I do not know a alternative to this.

**Additional context**

In the current config there is a line like this:
```
client-connect "/usr/local/etc/inc/plugins.inc.d/openvpn/ovpn_setup_cso.php server1"
``` 

One soloution cloud be that the `/usr/local/etc/inc/plugins.inc.d/openvpn/ovpn_setup_cso.php` returns an non zerro exit code.  If the CN is not found in the CSO and the new option is checked. Then the connection will not established.

**Comment by AdSchellevis** [comment]
If I'm not mistaken a workaround for this is just to assign a larger pool for the server and offer only addresses from a subnet to the clients, in which case you can easily drop all un-provisioned traffic.

> I have read in https://github.com/opnsense/core/issues/6220 that there is a rework planed so this could be done in this rework.

Considered, not planned.

**Comment by tabacha** [comment]
> If I'm not mistaken a workaround for this is just to assign a larger pool for the server and offer only addresses from a subnet to the clients, in which case you can easily drop all un-provisioned traffic.
> 
> > I have read in #6220 that there is a rework planed so this could be done in this rework.
> 
> Considered, not planned.

Yes, but I am not sure if an attacker can reconnect "n times" and then gets a ip which is assigned to a CSO Client.

**Comment by AdSchellevis** [comment]
> Yes, but I am not sure if an attacker can reconnect "n times" and then gets a ip which is assigned to a CSO Client.

To be fairly honest, but if an attacker has the private certificate of the user and his password and optionally a one time password token, I guess you're lost anyway.  To me this feels like the wrong fix, it's always good to consider which problem you are trying to solve, the overwrites aren't really a security measurement, the address doesn't even have hard guarantees on openvpn's end.

**Comment by AdSchellevis** [comment]
the firewall aliases https://github.com/opnsense/core/issues/6312 are likely a better option to add more constraints if needed. closing this for now.
