### ISSUE TITLE
Created API key cannot be downloaded using Google Chrome

### ISSUE THREAD

**Issue by 8191** [opnsense/core#623]
At least Google Chrome blocks the ini file which gets downloaded when creating an API key for a user.

I don't know if there's actually a use-case for the API keys right know, but as soon as there is one we should address this one, I'd say, since the ini file contains the secret, which is not shown within the GUI.

**Comment by fabianfrz** [comment]
https://wiki.opnsense.org/index.php/Howto_use_the_API

**Comment by fichtner** [comment]
Maybe the best course of action is use .txt instead...

**Comment by fabianfrz** [comment]
@8191 I wrote a patch to use txt instead. Can you test it?

**Comment by fichtner** [comment]
Looking at the code, .csv for type csv is also good....

**Comment by fabianfrz** [comment]
it is not a csv ;)

**Comment by fichtner** [comment]
then something wasn't quite right all along ;)

**Comment by fabianfrz** [comment]
@fichtner I can change it so it will create a csv file but it does not have an advantage over now because the csv would not contain more than one api key

**Comment by fichtner** [comment]
nono, txt is fine, thanks for submitting :)

**Comment by AdSchellevis** [comment]
nice work, I've just updated the wiki page as well.

**Comment by fabianfrz** [comment]
@AdSchellevis , @fichtner @8191 confirmed that it works - you can merge the pull request now
