### ISSUE TITLE
System Health "States" report is incorrect -- possibly because of invalid regexp

### ISSUE THREAD

**Issue by darth-wader** [opnsense/core#6234]
Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

The UI page `/ui/diagnostics/systemhealth` shows all zeros for `pfstates`, `pfnat`, `srcip`, and `dstip`.

I believe this is because the file `/var/db/rrd/updaterrd.sh`, which is generated from the below code, contains the command `egrep -v \"<\\-.*?<\\-|\\->.*?\\->\"`.
https://github.com/opnsense/core/blob/1472df66fb36c93bd44c3b1857b92fd49cb2c979/src/etc/inc/rrd.inc#L329 

Executing this command in the shell results in:
```
$ /usr/bin/egrep '<\-.*?<\-|\->.*?\->' < /tmp/pfctl_ss_out
egrep: repetition-operator operand invalid
```

The problem appears to be the use of the lazy match (aka minimal match) operator `*?`, which doesn't seem to be supported in the FreeBSD grep.

This regular expression is supported in GNU grep, so I speculate that when the `updaterdd.sh` code was written, OPNSense used GNU Grep, but at some point it was changed to use FreeBSD grep.

**To Reproduce**

1. In the UI, navigate to **Reporting** -> **Health** -> **System** 
2. Click on "Show Tables"
3. See all the zeros under the `pfstates`, `pfnat`, `srcip`, and `dstip` columns.
4. In the shell, execute `grep pfctl_ss_out /var/db/rrd/updaterrd.sh`
5. See the commands that are used to populate those columns.
6. Run the command manually, `egrep -v "<\-.*?<\-|\->.*?\->"`
7. See the error message and no output.

**Expected behavior**

I expect the `pfstates`, `pfnat`, `srcip`, and `dstip` columns to have non-zero data.

**Describe alternatives you considered**

I considered installing GNU grep on my system, but I don't know the FreeBSD or OPNsense package infrastructure well enough to do this.

I briefly considered fixing the regular expressions, but I don't know exactly what you're looking for in the `pfctl` output, so I can't fix the expression to find it.

**Version**
OPNsense 22.7.10_2-amd64
FreeBSD 13.1-RELEASE-p5
OpenSSL 1.1.1s 1 Nov 2022

**Comment by fichtner** [comment]
FreeBSD 13 changed grep utilities from GNU to BSD... Can you try 49c7402?

    # opnsense-patch 49c7402

It does require giving RRD backend a full recycle, best to do a reboot at a convenient time.


Cheers,
Franco

**Comment by fichtner** [comment]
Will add this to 22.7.11 although final feedback from reporter is missing. Works on my end now anyway...
