### ISSUE TITLE
OpenVPN server DH length is not set when importing an old config

### ISSUE THREAD

**Issue by mvglasow** [opnsense/core#6235]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/docs/blob/master/CONTRIBUTING.md
- [X] I have searched the existing issues and I am convinced that mine is new.

**Describe the issue**

After importing a configuration exported in October 2022 (the system was set up in March 2022, using the then-current version), the OpenVPN server failed to start. I eventually determined that the DH length parameter was not set. Setting it to its default value using the GUI fixed the issue.

A look at the exported config, as well as the config history, showed that the `/opnsense/openvpn/openvpn-server/dh_length` was missing from the old config file, but setting it manually added it on the machine. When I then exported the config, the parameter was also there. Btw, the GUI defaulted to 1024 bits, whereas OpenVPN got called with an empty parameter, resulting in an auto-generated filename that pointed to a nonexisting file.

See also https://superuser.com/q/1761737/292907

**Suggestions**

I do not know the entire background: was the parameter introduced in a recent version? In any case, upgrading a system with an existing config somehow did not exhibit this issue. If installing an upgrade involves updates to the config, then the same procedures should run when importing a config file from an older version.

I see config files do not report the OPNsense version number. Maybe it would make sense to add this information. That way, whenever OPNsense boots up (because a config was restored from backup, or because the system was upgraded), it can verify the version of the config file, and if it is lower than the current version, check if any changes need to be made (because new mandatory parameters have been introduced etc.), do whatever is necessary and then store the current version number in the file. Such upgrade procedures would have to stay in the software (e.g. version 42.5 would still have the code to upgrade a config from 22.8 to 22.9). When a config upgrade is needed, they would run consecutively, in ascending order, starting with the version reported by the config file.

**Version affected**

```
OPNsense 22.1.10_4-amd64
FreeBSD 13.0-STABLE
OpenSSL 1.1.1q 5 Jul 2022
```

This is the version on which the config was imported. The export was on an older version (current as of March–October 2022).

**Describe alternatives you considered**

Workaround is to edit the configuration using the web GUI, setting the missing parameter manually, then saving. On the long run, imported config files should undergo a consistency check (or an upgrade procedure, see above) and any issues should either get fixed automatically or result in an error message.

**Additional context**

**Comment by mvglasow** [comment]
Indeed, I just noticed that 22.1.* is end-of-life and I got prompted to upgrade to 22.7. Didn’t notice that even after upgrading I was not on the latest version, and had possibly downgraded without knowing it.

**Comment by fichtner** [comment]
Ok, close this then?

**Comment by mvglasow** [comment]
As far as importing config goes, yes. That upgrading does not give me the latest version is kind of unexpected, but a different issue.

**Comment by fichtner** [comment]
I don’t think I understood the issue then.
