### ISSUE TITLE
Incorrect Help Description in Interfaces > Diagnostics > Packet Capture

### ISSUE THREAD

**Issue by put3r-r00t3r** [opnsense/core#6236]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

There is an incorrect description in the help for the "Description" field in Interfaces > Diagnostics > Packet Capture

URL: https://opnsense.domain.tld/ui/diagnostics/packet_capture

The description when selecting the info icon or full help is:
"Select the protocol to capture, or Any. "

Instead, it should read something like:
"Enter a description for the packet capture here."

**To Reproduce**

1. Go to 'Interfaces'
2. Click on 'Diagnostics'
3. Click on 'Packet Capture'
4. Click on the "i" icon on the left or "Full Help" on the top right.
5. Observe the incorrect description: "Select the protocol to capture, or Any. "

**Expected behavior**

It should say something like" "Enter a description for the packet capture here."

**Screenshots**

![Screenshot 2023-01-09 at 15-43-43 Packet Capture Diagnostics Interfaces](https://user-images.githubusercontent.com/75872475/211431074-6935ae95-0021-481b-b488-6b21ecb64de9.png)

**Relevant log files**

N/A

**Additional context**

N/A

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 22.7.10_2-amd64
FreeBSD 13.1-RELEASE-p5
OpenSSL 1.1.1s 1 Nov 2022

**Comment by AdSchellevis** [comment]
@put3r-r00t3r looks like a copy-paste issue, thanks. I’ll put it on my list to fix when I’m near a computer
