### ISSUE TITLE
IPsec VTI when tunnel goes down, reconnecting the tunnel doesn't bring back the static routes

### ISSUE THREAD

**Issue by FingerlessGlov3s** [opnsense/core#6238]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

I have routed IPsec tunnel between two OPNsense Firewalls. Both are using DHCP WAN where the IP address can change from time to time, they're not on static IPs.

If the tunnel goes down say the IP changes, tunnel connectivity is lost. Now DPD should kick in and restart the tunnel, but I'm not entirely sure it did but the tunnel was showing as down in "VPN: IPsec: Status Overview" and the static routes were now missing from the "System: Routes: Status", I then pressed connect button and the tunnel came back up and SA's were created. The static routes didn't come back. To get these back I have to go press Apply again on "System: Routes: Status", which then brought the routes back.

**To Reproduce**

Setup IPsec Route Based tunnel between two OPNsense Firewalls. Any settings not listed will default.
Phase1
  Key Exchange version: V2
  Internet Protocol: IPv4
  Interface: WAN
  Remote gateway: DDNS.domain2.com
  Dynamic gateway: Ticked
  
  Authentication method: Mutual PSK
  My identifier: Distinguished Name: DDNS.domain1.com
  Peer identifier: Distinguished Name: DDNS.domain2.com
  
  Install policy: Not Ticked
  Disable Rekey: Not Ticked
  Disable Reauth: Not Ticked
  Tunnel Isolation: Not Ticked
  SHA256 96 Bit Truncation: Not Ticked
  NAT Traversal: Disable
  Close Action: None
  Dead Peer Detection: Enabled, 10 seconds 5 retries action restart
Phase2
  Local Address: 169.254.0.2
  Remote Address: 169.254.0.1
  
Create a Gateway for the remote peer IP of the tunnel
Create a static route using the gateway for a remote network.

Tuneables:
Name | Description | Type | Value
-- | -- | -- | --
net.enc.in.ipsec_bpf_mask | IPsec input bpf mask | runtime | 0 |  
net.enc.in.ipsec_filter_mask | IPsec input firewall filter mask | runtime | 0 |  
net.enc.out.ipsec_bpf_mask | IPsec output bpf mask | runtime | 0 |  
net.enc.out.ipsec_filter_mask | IPsec output firewall filter mask | runtime | 0
net.inet.ipsec.filtertunnel | If set, filter packets from an IPsec tunnel. | runtime | 1
net.inet6.ipsec6.filtertunnel | If set, filter packets from an IPsec tunnel. | runtime | 1

Find a way to make the tunnel drop and see if the routes disappear when tunnel is restarted or recreated?

**Expected behavior**

When the tunnel comes backup the routes should come back as well.

**Describe alternatives you considered**

None other than changing over to WireGuard

**Additional context**

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 22.7.10_2 (amd64, OpenSSL).
Intel(R) Core(TM) i3-7100U CPU @ 2.40GHz (2 cores, 4 threads)
Network Intel® I211

**Comment by fichtner** [comment]
Additional info: IPsec Phase 1 on WAN interface

**Comment by AdSchellevis** [comment]
This probably doesn’t work reliably as the problem likely isn’t the tunnel, but the if_ipsec device which is bound to an address and has no knowledge about dns changes. (I tried to explain this recently in https://github.com/opnsense/docs/commit/4f625774883368f79bee138961b86b69be47e62e ).

**Comment by FingerlessGlov3s** [comment]
The ipsec1 `tunnel inet` makes sense as the address has changed but it wouldn't know the WAN interface IP has changed.
I'd would have thought DPD would kick in and restart tunnel? 
Or does the restarting via DPD just try soft restart the tunnel? as in it keeps the ipsec1 interface as is but tries reconnecting?

**Comment by Pr1mEzz** [comment]
> This probably doesn’t work reliably as the problem likely isn’t the tunnel, but the if_ipsec device which is bound to an address and has no knowledge about dns changes. (I tried to explain this recently in [opnsense/docs@4f62577](https://github.com/opnsense/docs/commit/4f625774883368f79bee138961b86b69be47e62e) ).

Hello togehter,

I updated my OPNsense to OPNsense Business Edition 22.10.1 but still have this Problem.
After a WAN-IP-Change (every Night) the Tunnel seems to be up, but theres no traffic possible. Only when I restart the IPsec Service.

My temporary solution is to restart the ipsec service every night at 4 am. (Cron) Before this happens, the tunnel is down a few minutes. :(

What can I do?

**Comment by AdSchellevis** [comment]
@Pr1mEzz if you use dynamic addresses and they change frequently, I expect it will be difficult to prevent this permanently. When the address on the host itself changes and there are events, a custom script to restart the service on renew might work, but hardly is a generic solution.

**Comment by Pr1mEzz** [comment]
I use DynDNS at the remote Peer (Fortigate) and the IP Changes every Night. 
 
The OPNsense has a static IP.

Im very sad thats isnt possible like commercial solutions.
