### ISSUE TITLE
opnsense-bootstrap fails on AWS EC2 instance

### ISSUE THREAD

**Issue by securityguy** [opnsense/core#6239]
Using opnsense-bootstrap on a fresh freeBSD 13 completes the install, reboots, and allows network interface configuration via the AWS serial console. However, the VM then hangs after displaying the HTTPS SHA256 fingerprint:

`Configuring firewall.......done.
Syncing OpenVPN settings...done.
Starting NTP service...done.
Starting Unbound DNS...done.
Generating RRD graphs...done.
>>> Invoking start script 'newwanip'
Reconfiguring IPv4 on ena0
>>> Invoking start script 'freebsd'
Starting rtsold.
>>> Invoking start script 'syslog'
>>> Invoking start script 'dnsbl'
>>> Invoking start script 'carp'
>>> Invoking start script 'cron'
Starting Cron: OK
>>> Invoking start script 'beep'
Root file system: /dev/gpt/rootfs
Thu Jan 12 01:03:30 UTC 2023

*** OPNsense.localdomain: OPNsense 22.7.10_2 (amd64/OpenSSL) ***

 LAN (ena0)      -> v4/DHCP4: 10.99.15.157/20

 HTTPS: SHA256 7D 63 A5 70 0E E0 03 2D 86 E9 C1 EE 62 C2 7C 0A
               43 13 0D 90 47 1D EC 08 98 FE A6 1C 80 0A 74 3D`
               
            
Multiple attempts failed using a VM with 2 interfaces (LAN and WAN), and a VM with one interface and configuring it as WAN or LAN.

The system can be booted into single-user mode, but normal reboots fail as above.

By rebooting in single-user mode, I was able to view logs. Perhaps this will help?

`<11>1 2023-01-12T01:03:25+00:00 OPNsense.localdomain opnsense 79869 - [meta sequenceId="45"] /usr/local/etc/rc.newwanip: IPv4 renewal is starting on 'ena0'
<11>1 2023-01-12T01:03:25+00:00 OPNsense.localdomain opnsense 79869 - [meta sequenceId="46"] /usr/local/etc/rc.newwanip: On (IP address: 10.99.15.157) (interface: LAN[lan]) (real interface: ena0).
<11>1 2023-01-12T01:03:25+00:00 OPNsense.localdomain opnsense 85046 - [meta sequenceId="47"] /usr/local/etc/rc.routing_configure: ROUTING: entering configure using defaults
<11>1 2023-01-12T01:03:25+00:00 OPNsense.localdomain opnsense 85046 - [meta sequenceId="48"] /usr/local/etc/rc.routing_configure: ROUTING: IPv4 default gateway set to lan
<11>1 2023-01-12T01:03:25+00:00 OPNsense.localdomain opnsense 85046 - [meta sequenceId="49"] /usr/local/etc/rc.routing_configure: ROUTING: setting IPv4 default route to 10.99.0.1
<11>1 2023-01-12T01:03:25+00:00 OPNsense.localdomain opnsense 79869 - [meta sequenceId="50"] /usr/local/etc/rc.newwanip: ROUTING: entering configure using 'lan'
<11>1 2023-01-12T01:03:25+00:00 OPNsense.localdomain opnsense 85046 - [meta sequenceId="51"] /usr/local/etc/rc.routing_configure: ROUTING: keeping current default gateway '10.99.0.1'
<13>1 2023-01-12T01:03:25+00:00 OPNsense.localdomain opnsense 85046 - [meta sequenceId="52"] /usr/local/etc/rc.routing_configure: plugins_configure monitor (1,)
<11>1 2023-01-12T01:03:25+00:00 OPNsense.localdomain opnsense 79869 - [meta sequenceId="53"] /usr/local/etc/rc.newwanip: ROUTING: IPv4 default gateway set to lan
<11>1 2023-01-12T01:03:25+00:00 OPNsense.localdomain opnsense 79869 - [meta sequenceId="54"] /usr/local/etc/rc.newwanip: ROUTING: setting IPv4 default route to 10.99.0.1
<13>1 2023-01-12T01:03:25+00:00 OPNsense.localdomain opnsense 85046 - [meta sequenceId="55"] /usr/local/etc/rc.routing_configure: plugins_configure monitor (execute task : dpinger_configure_do(1,))
<11>1 2023-01-12T01:03:25+00:00 OPNsense.localdomain opnsense 79869 - [meta sequenceId="56"] /usr/local/etc/rc.newwanip: ROUTING: keeping current default gateway '10.99.0.1'
<13>1 2023-01-12T01:03:25+00:00 OPNsense.localdomain opnsense 79869 - [meta sequenceId="57"] /usr/local/etc/rc.newwanip: plugins_configure monitor (,LAN_DHCP)
<11>1 2023-01-12T01:03:25+00:00 OPNsense.localdomain opnsense 85046 - [meta sequenceId="58"] /usr/local/etc/rc.routing_configure: The LAN_DHCP monitor address is empty, skipping.
<13>1 2023-01-12T01:03:25+00:00 OPNsense.localdomain opnsense 79869 - [meta sequenceId="59"] /usr/local/etc/rc.newwanip: plugins_configure monitor (execute task : dpinger_configure_do(,LAN_DHCP))
<11>1 2023-01-12T01:03:25+00:00 OPNsense.localdomain opnsense 79869 - [meta sequenceId="60"] /usr/local/etc/rc.newwanip: The LAN_DHCP monitor address is empty, skipping.
<13>1 2023-01-12T01:03:25+00:00 OPNsense.localdomain opnsense 85046 - [meta sequenceId="61"] /usr/local/etc/rc.routing_configure: plugins_run return_gateways_status ()
<13>1 2023-01-12T01:03:25+00:00 OPNsense.localdomain opnsense 85046 - [meta sequenceId="62"] /usr/local/etc/rc.routing_configure: plugins_run return_gateways_status (execute task : dpinger_status())
<13>1 2023-01-12T01:03:25+00:00 OPNsense.localdomain opnsense 79869 - [meta sequenceId="63"] /usr/local/etc/rc.newwanip: plugins_run return_gateways_status ()
<13>1 2023-01-12T01:03:25+00:00 OPNsense.localdomain opnsense 79869 - [meta sequenceId="64"] /usr/local/etc/rc.newwanip: plugins_run return_gateways_status (execute task : dpinger_status())
<13>1 2023-01-12T01:03:26+00:00 OPNsense.localdomain opnsense 79869 - [meta sequenceId="65"] /usr/local/etc/rc.newwanip: plugins_configure vpn (,lan)
<13>1 2023-01-12T01:03:26+00:00 OPNsense.localdomain opnsense 79869 - [meta sequenceId="66"] /usr/local/etc/rc.newwanip: plugins_configure vpn (execute task : ipsec_configure_do(,lan))
<13>1 2023-01-12T01:03:26+00:00 OPNsense.localdomain opnsense 79869 - [meta sequenceId="67"] /usr/local/etc/rc.newwanip: plugins_configure vpn (execute task : openvpn_configure_do(,lan))
<13>1 2023-01-12T01:03:26+00:00 OPNsense.localdomain opnsense 79869 - [meta sequenceId="68"] /usr/local/etc/rc.newwanip: plugins_configure newwanip (,lan)
<13>1 2023-01-12T01:03:26+00:00 OPNsense.localdomain opnsense 79869 - [meta sequenceId="69"] /usr/local/etc/rc.newwanip: plugins_configure newwanip (execute task : dnsmasq_configure_do())
<13>1 2023-01-12T01:03:26+00:00 OPNsense.localdomain opnsense 79869 - [meta sequenceId="70"] /usr/local/etc/rc.newwanip: plugins_configure newwanip (execute task : ntpd_configure_do())
<45>1 2023-01-12T01:03:28+00:00 OPNsense.localdomain syslog-ng 12078 - [meta sequenceId="1"] Configuration reload request received, reloading configuration;
<45>1 2023-01-12T01:03:28+00:00 OPNsense.localdomain syslog-ng 12078 - [meta sequenceId="2"] Configuration reload finished;
<13>1 2023-01-12T01:03:30+00:00 OPNsense.localdomain opnsense 79869 - [meta sequenceId="3"] /usr/local/etc/rc.newwanip: plugins_configure newwanip (execute task : opendns_configure_do())
<13>1 2023-01-12T01:03:30+00:00 OPNsense.localdomain opnsense 79869 - [meta sequenceId="4"] /usr/local/etc/rc.newwanip: plugins_configure newwanip (execute task : openssh_configure_do(,lan))
<13>1 2023-01-12T01:03:30+00:00 OPNsense.localdomain opnsense 79869 - [meta sequenceId="5"] /usr/local/etc/rc.newwanip: plugins_configure newwanip (execute task : unbound_configure_do(,lan))
<13>1 2023-01-12T01:03:30+00:00 OPNsense.localdomain opnsense 79869 - [meta sequenceId="6"] /usr/local/etc/rc.newwanip: plugins_configure newwanip (execute task : vxlan_configure_do())
<13>1 2023-01-12T01:03:30+00:00 OPNsense.localdomain opnsense 79869 - [meta sequenceId="7"] /usr/local/etc/rc.newwanip: plugins_configure newwanip (execute task : webgui_configure_do(,lan))
<45>1 2023-01-12T01:21:32+00:00 OPNsense.localdomain syslog-ng 12078 - [meta sequenceId="1"] syslog-ng shutting down; version='3.38.1'
root@:/var/log/system # `

**Comment by AdSchellevis** [comment]
Our authorized image is available in the marketplace
