### ISSUE TITLE
Bug: Registered DHCP leases in DNS have wrong domain name

### ISSUE THREAD

**Issue by 8191** [opnsense/core#624]
The feature "register DHCP leases in DNS" registers the DHCP leases with wrong domain name. The domain name of the OPNsense system is used instead of the configured domain name of the DHCP service.

**Comment by AdSchellevis** [comment]
@8191 I don't think we can fix this without glueing too many components together, with our latest changes we collect and monitor all the leases, but I'm not sure how we should determine the dhcp pool they belong too easily. Any suggestions?

**Comment by AdSchellevis** [comment]
timeout
