### ISSUE TITLE
DNS Issues on 22.7.10_2 

### ISSUE THREAD

**Issue by mejas** [opnsense/core#6241]
Hello,

I'm currently trying to troubleshoot an issue with how DNS is handled by the firewall. When using Unbound (forwarding or resolver modes) or DNS Lookup in the firewall, I always notice that there is a random interval when DNS Query Times would shoot up to 5 or even 10 seconds. This results in a poor user experience where pages load slowly or fail to load at all due to DNS_PROBE error.

Replication methodology:

- Use DNS Lookup tool to any site
- Use any DNS resolver (in my case 1.1.1.1)
- Keep looking up DNS records (can be the same site)

Using the AdGuardHome plugin does not have these worst case times (down to 200ms at worst), which makes me suspect there may be something off with an update or configuration.

I've attempted to capture a PCAP of my test with this issue and have attached it here. Any suggestions to solve the problem would be greatly appreciated.

[capture.zip](https://github.com/opnsense/core/files/10401482/capture.zip)

**Comment by swhite2** [comment]
Is this captured by a client behind OPNsense? If so, not much can be said about it. At the very least you'd need to see the timing of queries passing through the firewall (capture both LAN dst port 53 + WAN src port 53). The least noisiest way of doing this would be in forwarding mode.

**Comment by mejas** [comment]
The capture was done on the firewall itself via the Interfaces > Diagnostics > Packet Capture tool with the WAN as the target interface. I then ran  Interfaces > Diagnostics > DNS Lookup against 1.1.1.1 to complete the capture.
