### ISSUE TITLE
Ability to schedule NAT rules

### ISSUE THREAD

**Issue by digitalcohesion** [opnsense/core#6242]
I would like to be able to schedule a NAT rule to turn on and off at some time like firewall rules can be scheduled. 

I have multiple servers behind my public IP and I would like to be able to use Let's Encrypt without having to manually renew certs. Currently I have a NAT rule for port 80 that is disabled most of the time. This allows web traffic to hit my web server. This also prevents any other internal servers from auto renewing their certs.

So when I want to renew I have to manually turn on the NAT rule that points to the other internal server and force a renew operation and then disable the NAT rule again. 

Being able to schedule these usually disabled NAT rules would allow me to automate all my renewals.

I have not figured out how to do this using any other means with OPNsense.

**Comment by swhite2** [comment]
You could use relayd and schedule the filter rule accordingly, no NAT required.

**Comment by digitalcohesion** [comment]
> You could use relayd and schedule the filter rule accordingly, no NAT required.

I'm not sure I understand. I've never used relayd. It looks like relayd is a sort of proxy. Will it will allow multiple backend servers relaying off the same ip and port in it's config? If I set it up with multiple internal servers all coming from port 80 then what would I filter on? The internal servers should have connections allowed and available all the time through the firewall. The only change I would like to schedule is what internal server is connected to port 80 on my public IP. I'll have to think about this idea some more and see if there is a way I can setup a test network to try it out. Thanks for the idea.
