### ISSUE TITLE
Unclosed files in multiple Python processes

### ISSUE THREAD

**Issue by swhite2** [opnsense/core#6243]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

While analyzing a Python core dump, I built Python39 from the ports tree with debug symbols enabled. The regular workflow now contained some more verbose messages about Python. The most prominent was this one:

`sys:1: ResourceWarning: unclosed file <_io.TextIOWrapper name='/var/run/configd.pid' mode='w' encoding='UTF-8'>
ResourceWarning: Enable tracemalloc to get the object allocation traceback`.

In fact, `configd` is Daemonized, and it's pid file is not opened by configd itself, but rather the `Daemonize` process. A closer look at the source code shows: https://github.com/opnsense/core/blob/db2bcf716e0b7e8b1809de1d9a53322b208243cc/src/opnsense/site-python/daemonize.py#L84

and the corresponding SIGTERM handler:
https://github.com/opnsense/core/blob/db2bcf716e0b7e8b1809de1d9a53322b208243cc/src/opnsense/site-python/daemonize.py#L65-L71
Which doesn't close the file, only removes it.

I then noticed this wasn't the only one: 

`/usr/local/opnsense/scripts/syslog/queryLog.py:129: ResourceWarning: unclosed file <_io.TextIOWrapper name='/var/log/system/system_20230111.log' mode='r' encoding='UTF-8'>`

`usr/local/opnsense/scripts/filter/pftablecount.py:54: ResourceWarning: unclosed file <_io.TextIOWrapper name='/var/db/aliastables/spamhaus_drop.txt' mode='r' encoding='UTF-8'>\n  tmp = open(filename).read()`

As part of of the system backend log.

This isn't limited to code on our end: 

`/usr/local/opnsense/scripts/interfaces/list_macdb.py:41: ResourceWarning: unclosed file <_io.BufferedReader name='/usr/local/lib/python3.9/site-packages/netaddr/eui/oui.txt'>\n for line in open(oui_registry_file, 'rb'):`

Most of these are (I think) simple oversights and opening files without the use of a ContextManager. I don't think the impact is very high, but fixing these errors will at least provide some more protection against corrupted files in case of a crash.

**To Reproduce**

1. Clone the ports tree
2. run `make config` in /usr/ports/lang/python39
3. Enable debug symbols
4. run `make`
5. run `make deinstall` to remove the current python version
6. run `make install` to install the debug python version
7. The `libpython3.9.so*` objects in /usr/local/lib are now `libpython3.9d.so*`. This poses a problem for every module expecting `libpython3.9.so*`
8. copy every `libpython3.9d.so*` file to `lib.python3.9.so*` to mask the fact we're using debug symbols.
9. Do some development work, e.g. `make upgrade` in /usr/core, and observe that a restart of configd causes the error message.

**Expected behavior**

For file descriptors to be closed properly.

**Describe alternatives you considered**

None

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 23.1.b (amd64, OpenSSL).

**Comment by swhite2** [comment]
> If the file is only read, there wasn’t much that could go wrong either to be honest.

Agreed, so if we can agree this is a nonissue, I'll close the ticket. The workflow might still be useful to track down open() calls in write mode.

**Comment by AdSchellevis** [comment]
I don’t mind fixing some of them either as long as it’s in our own codebase. Strictness changes over time, code evolves.
