### ISSUE TITLE
Route Based VPN hangs on reboot - interface isn´t created on reboot for Gateway

### ISSUE THREAD

**Issue by jpmonzonr** [opnsense/core#6250]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

I have a route based vpn configured against a Forinet firewall, it is working fine. The issue I have is when I reboot the opnsense firewall several services fail to start including the vpn service at boot. If I try to enable the VPN Service the opnsense will hang and another reboot is necessary. I noticed that the problem is related to the Gateway I created for the vpn to route traffic to. Logging into the opnsense cli I notice the interface ipsec7 isn´t created automatically when I boot and therefore the Gateway realy doesnt have an interface and a chain reaction of problems happen.

A clear and concise description of what the bug is, including last known working version (if any).

*Tip*: to validate your setup was working with the previous version, use opnsense-revert (https://docs.opnsense.org/manual/opnsense_tools.html#opnsense-revert)

**To Reproduce**

1. Go to 'Power'
2. Click on 'Reboot'
3. See error → Opnsense fails to load several services including the VPN service. 

**Expected behavior**

I expect the interface to be created before the vpn and gateway load. And the vpn establishes flawlessly without any intervention. 

**Describe alternatives you considered**

The only way to get it working again without the opnsense hanging is to delete all of the routes associated with the Gateway, then delete the Gateway and then the VPN, and reconfigure everything again.

A clear and concise description of any alternative solutions or workaround you considered.

When the Firewall restarts this interface isn´t created automatically and the gateway fails and hangs the opnsense completely.
![image](https://user-images.githubusercontent.com/106492511/213349836-26d6a697-9e54-422d-9cd4-39a85afef7e5.png)

This is the gateway i configured:

![image](https://user-images.githubusercontent.com/106492511/212956285-9d44a9f8-e372-4e35-914b-86f00e95a180.png)

**Relevant log files**

If applicable, information from log files supporting your claim.

Didn´t really see anything relevant in the log.

Software version used and hardware type if relevant, e.g.:

OPNsense 22.7.10_2 (amd64/OpenSSL)
FreeBSD 13.1-RELEASE-p5 FreeBSD 13.1-RELEASE-p5 stable/22.7-n250270-9d1c26e8548 SMP amd64
hw.model: AMD EPYC Processor
hw.realmem: 4194304000

**Comment by AdSchellevis** [comment]
Best check the console first if a service or plug-in hangs during boot (in which case the next in line won’t start either).

**Comment by jpmonzonr** [comment]
Ok so I rebooted and checked the console via my cloud provider and I get the following:
![image](https://user-images.githubusercontent.com/106492511/213347708-6275f5ab-9228-475e-8cc3-37a73f9bcdef.png)

After I log in I get this:
![image](https://user-images.githubusercontent.com/106492511/213347750-a61643d1-48a7-42ce-b16f-8c238881d315.png)
![image](https://user-images.githubusercontent.com/106492511/213347763-2445681c-351f-4d20-b79c-85fe61f7094f.png)

So now I login via console and can see ther is no ipsec7 interface created:
![image](https://user-images.githubusercontent.com/106492511/213347886-a85c49f7-b51b-44a6-acc9-d3f7db5dc35a.png)

Now I go and check the Gateway for the VPN and the gateway still appears to be there but it has no interface (ipsec7). If I try to change anyhthing on the Gateway I get:
![image](https://user-images.githubusercontent.com/106492511/213348027-f8d8a8a0-52b0-4bd0-bae3-06e53b08920a.png)

The only way I can get it to work again is to delete all the routes associated with the Gateway, then delete the Gateway and then delete the Phase 2 of the vpn, after a reboot now all services are on and I proceed to reconfigure phase 2 for the VPN, the Gateway again and all of the routes again in order for it to work.

**Comment by AdSchellevis** [comment]
if "configure firewall" is indeed the last entry, the box is still booting. could be a plugin , custom script or misconfigured dns.

**Comment by jpmonzonr** [comment]
Ok, so I uninstalled all plugins, but still get the same problem when rebooting Opnsense vía console I can see it still stays at "Configuring Firewall....done". Then I log to the GUI and many services are not loaded. Again the only way to get this to work is to erase the routes, the gateway, the VPN (phase 1 and 2) and configure it from scratch again. The problem seems to be the Gateway and how it is associated to the interface when Opnsense is booted. Have you done any tests using Route Based VPN to mimick this issue?

**Comment by fichtner** [comment]
@jpmonzonr that looks like a PHP yield/idle issue I've been trying to get a hold off since PHP 8. Can you press CTRL+T a few times when this happens and make a screenshot of the output? FWIW, it's not the actual 0.0.0.0 issue described here...

**Comment by jpmonzonr** [comment]
Ok so I upgraded to 23.1, and getting the same issue. Where should I press Ctrl-t from the console you mean? If so, I can´t because its a virtual console from my cloud provider. Is there any log I can send you that I can access via CLI?
