### ISSUE TITLE
Multiple DHCPv6 instances send advertisements

### ISSUE THREAD

**Issue by JasMan78** [opnsense/core#6263]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

I've enabled IPv6 on some of my interface in OPNsense. Most of them are tracking the address from the WAN interface, and distribute the addresses to my LAN clients by DHCPv6. One interface has a static ULA address without DHCP.
After a prefix change I noticed that my clients still got the previous IPv6 prefix, although the OPNsense interface overview showed the new one.
I run a packet capture and noticed, that my clients received always four DHCPv6 advertisements in respone of their solicit. Three of them contained the previous IPv6 prefix. Only one contained the new one.

The clients requested the address of the first advertisement, which was always the old address. The request was denied by OPNsense, because of the wrong prefix (status code 13, NotOnLink).

I noticed also that the process list showed four "dhcp -6" processes, and only one for IPv4.

When I disabled one of the four IPv6 interfaces, one of the "dhcp -6" processes disappeared, and the capture showed only three DHCPv6 advertisements.

*Tip*: to validate your setup was working with the previous version, use opnsense-revert (https://docs.opnsense.org/manual/opnsense_tools.html#opnsense-revert)

**To Reproduce**

I'm not sure if the behaviour is reproduceable. I would guess that many others having the same setup as me, and I'm wondering why nobody else has noticed this before.

**Expected behavior**

The DHCPv6 service should send not more than one advertisement with the current prefix to a requesting client.

**Describe alternatives you considered**

When the prefix has changed, a reboot of OPNsense updates the IPv6 prefix for all DHCPv6 instances, and all four advertisements contain the correct prefix then. 

**Screenshots**

![image](https://user-images.githubusercontent.com/20991399/214609473-dc2e32e0-c441-4009-b9bd-15887a7e38dc.png)

**Additional context**

First I thought OPNsense started a DHCPv6 instance for each IPv6 enabled interface. But as you can see in the screenshot, there are currenlty just two instances for four interfaces.

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 22.7.11-amd64
Intel(R) Core(TM) i5-6200U

**Comment by fichtner** [comment]
Well, the issue is that there shouldn't be multiple DHCPv6 daemons as they possibly run on an older configuration, but in your case they have the same pid file (see your screenshot) so something during process exit doesn't work. As far as I know the kill signal is mandatory.

**Comment by JasMan78** [comment]
Thx, Franco. I will try this at the weekend.

Do you know similiar cases, or I'm the only known person who is having this? :)

**Comment by JasMan78** [comment]
I've deleted the line from the file, but no success. 
Still multiple instances of the DHCPv6 daemon when the prefix has changed, or Zenarmor starts after a reboot of OPNsense.

Any quick-and-dirty solution ideas (e.g. kill all dhcp -6 processes, when new WAN IP) ?

**Comment by fichtner** [comment]
Don’t know. You can try but as I said it’s a bit tricky.

**Comment by JasMan78** [comment]
Uhm, I don't know why, but after I updated to 23.1 today the issue has been solved. 
I've rebooted OPNsense several times, forced a prefix change, restarted Zenarmor, but nothing created a new DHCPv6 daemon.

So.....thank you :)

**Comment by fichtner** [comment]
I was under the impression that this would translate to 23.1 but some areas received changes, especially rc.newwanip(v6) so that might be it. But I wouldn’t be surprised if this comes back later also.

**Comment by JasMan78** [comment]
@fichtner You were right. After another outage of my ISP, I've two DHCPv6 instances again. One with the old prefix, the other with the new one. :-(

You flagged my report as "Support". Isn't it a bug?

**Comment by fichtner** [comment]
It’s a bug if we can reproduce or know what to do. Can you post the system log of the last occurrence at notice level?

**Comment by JasMan78** [comment]
Yep.
The outage happens yesterday at 23:00.
[system_20230204_ano.log](https://github.com/opnsense/core/files/10608784/system_20230204_ano.log)

**Comment by fichtner** [comment]
got any other entry from "dhcp6c" around these two days?

**Comment by JasMan78** [comment]
No, only the ones in the attached log file.
BTW: are the OpenVPN entries normal? Because I'm not using OpenVPN.

**Comment by fichtner** [comment]
Also anything under Services: DHCPv4: Log File under notice level?

OpenVPN may be a bit noisy, yes. But not an issue.


Cheers,
Franco

**Comment by fichtner** [comment]
Your WAN is using SLAAC? oO

**Comment by fichtner** [comment]
Historically we don't seem to be in need to restart radvd and dhcpd...

**Comment by JasMan78** [comment]
> Your WAN is using SLAAC? oO

No, the IPv6 WAN IF is configured as DHCPv6 client.
The DHCPv6 server is an AVM Fritz!Box, configured to distribute DNS servers and IPv6 prefixes only.

**Comment by fichtner** [comment]
Seems like a dead end to me. Did you try eb1367cc57 earlier?

**Comment by fichtner** [comment]
So there is only one single dispatch for dhcpd here but it seems to spawn a second process? It's strange..

**Comment by JasMan78** [comment]
> Seems like a dead end to me. Did you try [eb1367c](https://github.com/opnsense/core/commit/eb1367cc57564d1069077938d4cc6ac1e6030939) earlier?

No. Should I try?

**Comment by fichtner** [comment]
Yes please. Restart seems slightly slower but it keeps working. The old code claims that this could hang if file is not removed but if we delete the pid the service has no way to wait and it may have muted a different bug that originated somewhere else back then.

**Comment by JasMan78** [comment]
OK, I will install it and do some tests. Will let you know the results in a few days. 

Thank you for your help.

**Comment by JasMan78** [comment]
Works not as expected. 
Right after the reboot, I had two DHCPv6 daemons. The service overview at the dashboard says "DHCPv6 server stopped (red)"
Here's the current system log.
[system_20230204_ano.log](https://github.com/opnsense/core/files/10608966/system_20230204_ano.log)

**Comment by fichtner** [comment]
I wonder what’s different about your setup if it triggers this easily with no other report which is  less than 0.001% report rate. I’m baffled, but perhaps we can figure it out 😊

**Comment by JasMan78** [comment]
That would be great, and I'm happy to help to find out.
Just let me know what I can do to support you.

**Comment by fichtner** [comment]
I've tested eb1367c a bit more and on my end it's true that DHCPv6 seems to be slower to start (as said before) it still comes up eventually. It looks safer to me and I'd like to continue testing with it. On your end I don't see a reason why dhcpd -6 won't come up eventually if you let it boot and configre. Can you try again?


Thanks,
rFranco

**Comment by JasMan78** [comment]
It was just the dashboard that said "Service is not up and running".
When I checked the process list, I saw two DHCPv6 daemons right after the reboot. The packet capture showed me also two DHCPv6 advertisements when a client sent a solicit. 

Therefore I uninstalled the patch yesterday and rebooted OPNsense. Unfortunately it didn't came up anymore: 

![image](https://user-images.githubusercontent.com/20991399/216956321-2a25b263-b93a-49cb-8700-a205f25fb833.png)

I did a fresh install and importet the config backup to solve this issue.
Not sure if I would like to try the patch again. :)

**Comment by fichtner** [comment]
I can fix this, but likely a PHP 8.1 issue triggered in edge case unrelated to the issue at hand.

**Comment by fichtner** [comment]
Which version did you install running into an issue from 2021? https://github.com/opnsense/core/commit/b74b3799db80

**Comment by JasMan78** [comment]
> I can fix this, but likely a PHP 8.1 issue triggered in edge case unrelated to the issue at hand.

The dashboard issue is not the problem. But after I applied the patch eb1367c and rebooted OPNsense, I had immediately two DHCPv6 daemons running. So no improvement for my installation. 
When I clicked on the start button for "DHCPv6 Server" on the service dashboard, I saw three DHCPv6 daemons.


> Which version did you install running into an issue from 2021? [b74b3799db80](https://github.com/opnsense/core/commit/b74b3799db80)

This happend after I unsintall eb1367c under 23.1_6, not after the fresh installation (which was also the current image).
MAybe I did something wrong. I reapplied the patch to undo it, and after that I cleanded the local patch cache.

**Comment by fichtner** [comment]
This all makes me very suspicious... can you do a health audit on that system?

**Comment by JasMan78** [comment]
Sure

[OPNsense_HealthAudit.txt](https://github.com/opnsense/core/files/10663095/OPNsense_HealthAudit.txt)

**Comment by JasMan78** [comment]
It seems that the issue does not occures, when "Start On Boot" for Zenarmor packet engine is disabled. 

I did several reboots and OPNsense was always up much more faster. The process list showed me always only one DHCPv6 daemon right after the reboot.

When "Start On Boot" is enabled, the reboot process until the webgui is reachable takes a little bit longer. But sometimes the webgui is only reachable for about 10 seconds. Then it seems that the Zenarmor services starts delayed or again, and I've to wait up to 3 minutes until the webgui is reachable again.
And in this cases, I always saw more than one DHCPv6 daemon in the process list after the reboot.

**Comment by Xploder** [comment]
I have the same problem with an unmanageable second dhcpd -6 process that spawns each boot and therefore two DHCPV6 replies after every client request. All I can do is manually kill the PID.

**Comment by fichtner** [comment]
There is a patch to try actually. If this is Zenarmor related it might also be Suricata/IPS related.

**Comment by Xploder** [comment]
Also not using Suricata/IPS. It's a very vanilla install actually.
Could using Stateless RA have something to do with it?

**Comment by JasMan78** [comment]
I can confirm that the issue is related to Zenarmor.
When I disable the "Start at boot" switch for Zenarmor, OPNsense comes up with one DHCPD -6 process.
As soon as I start Zenarmor manually, the current DHCPD -6 process dissappears, and up to four new processes come up. 

When I enable the "Start at boot" switch and reboot OPNsense, the multiple DHCP -6 processes appear right after the boot has finished. 
But I had also some proper boots with "Start at boot" enabled, and only one DHCP -6 process after the boot finished.

The patch has no effect to this behaviour for me.

**Comment by JasMan78** [comment]
The issue seems to be solved when I enable the emulated netmap driver in Zenarmor. 
And OPNsense is reachable much more faster after a reboot now.

With the native driver Zenarmor causes an additional downtime for about 3-5 minutes right after OPNsense came up and was reachable. 
Now this timeout is completly gone.

Not sure if it is really a netmap driver issue, or if the driver change causes a timing change how the interfaces and services come up, which solves the issue.
