### ISSUE TITLE
Support other GeoIP sources

### ISSUE THREAD

**Issue by misery** [opnsense/core#6264]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**

I like to request a more flexible solution for GeoIP sources. I really like the stuff of MaxMind but it would be nice if it is possible to use other GeoIP sources without a special account.

**Describe the solution you like**

OPNSense documentation should define a format that needs a URL must provide like the ZIP-File and the content.
Since /usr/local/share/GEOIP/alias seems really simple it should be easy to say "those files as ZIP content".

Maybe it should be possible to define a "subdirectory" in the ZIP that should be extracted or something like this. Or a field for "regex replace" filenames for conversion.

**Describe alternatives you considered**

There is a autogenerated github repo that could be used as the files a provided as CIDR format.

https://github.com/herrbischoff/country-ip-blocks
https://codeload.github.com/herrbischoff/country-ip-blocks/zip/refs/heads/master

**Additional context**

Someone wrote a special tool to convert but it would be nice to use the URL directly.
https://github.com/cnbatch/GeoIP-Update-for-OPNsense/

**Comment by AdSchellevis** [comment]
> OPNSense documentation should define a format ..

The supported format is described in the docs (https://docs.opnsense.org/manual/aliases.html#geoip), we currently don't have plans to offer other services, we offer a GeoIP service as part of our business edition as well (included by default).

**Comment by misery** [comment]
Ah, thank you! I searched for it but didn't found that.
