### ISSUE TITLE
Reporting traffic without resolv.conf

### ISSUE THREAD

**Issue by cookiemonsteruk** [opnsense/core#6266]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X ] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [ X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

Hi.
I am unable to see top talkers in Reporting > Traffic . Neither in the Graph tab nor the Top Talkers tab.
The Graph section works fine with the interfaces I chose.
I suspected a hardware replacement I made for the whole system, using config backup & restore and changing interface names in the config caused the stats backends to get confused or corrupted.
However after going to Reporting > Settings and Reset RDD Data, Reset Netflow Data, the problem persists.

Looking for clues I see in the error logs for Backend the following:
`configd.py	[df54baa3-9972-4eb7-a381-eb4b7aa560de] Script action failed with Command '/usr/local/opnsense/scripts/interfaces/traffic_top.py --interfaces 'igc1,igc0'' returned non-zero exit status 1. at Traceback (most recent call last): File "/usr/local/opnsense/service/modules/processhandler.py", line 482, in execute subprocess.check_call(script_command, env=self.config_environment, shell=True, File "/usr/local/lib/python3.9/subprocess.py", line 373, in check_call raise CalledProcessError(retcode, cmd) subprocess.CalledProcessError: Command '/usr/local/opnsense/scripts/interfaces/traffic_top.py --interfaces 'igc1,igc0'' returned non-zero exit status 1.`
When I call the last exception from the shell I get this:
```
[penguin@OPNsense ~]$ /usr/local/opnsense/scripts/interfaces/traffic_top.py --interfaces 'igc1,igc0'
Traceback (most recent call last):
  File "/usr/local/opnsense/scripts/interfaces/traffic_top.py", line 183, in <module>
    reverse_lookup = AsyncLookup().collect([x['address'] for x in top_hosts])
  File "/usr/local/opnsense/scripts/interfaces/traffic_top.py", line 107, in collect
    asyncio.run(self.request_ittr(addresses))
  File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/usr/local/opnsense/scripts/interfaces/traffic_top.py", line 91, in request_ittr
    dnsResolver = Resolver()
  File "/usr/local/lib/python3.9/site-packages/dns/resolver.py", line 758, in __init__
    self.read_resolv_conf(filename)
  File "/usr/local/lib/python3.9/site-packages/dns/resolver.py", line 850, in read_resolv_conf
    raise NoResolverConfiguration('no nameservers')
dns.resolver.NoResolverConfiguration: no nameservers
```
Indeed I have no DNS servers set in /etc/resolv.conf . I am not using ISP dns servers from the isp. I am using Unbound on a non-standard port.
Allow DNS server list to be overridden by DHCP/PPP on WAN is unchecked.
Do not use the local DNS service as a nameserver for this system is checked.
Thinking a little, I enabled the second to populate /etc/resolv.conf and tried the script:
```
[penguin@OPNsense ~]$ /usr/local/opnsense/scripts/interfaces/traffic_top.py --interfaces 'igc1,igc0'
{"igc1":{"records":[],"status":"ok"},"igc0":{"records":[],"status":"ok"}}
```
So that suggests this graphing functionality won't work without a valid value in /etc/resolv.conf
Is this the expected behaviour?

System Info:
OPNsense 22.7.8-amd64
FreeBSD 13.1-RELEASE-p3
OpenSSL 1.1.1s  1 Nov 2022

**Comment by AdSchellevis** [comment]
@cookiemonsteruk it's not supposed to just crash out, https://github.com/opnsense/core/commit/bb623c6033db80c4b913494c5348a857de84182e should prevent this from happening.

**Comment by cookiemonsteruk** [comment]
Nice Ad. Thanks.

**Comment by cookiemonsteruk** [comment]
Commit  applied with opnsense-patch and I can confirm it solved the problem.
