### ISSUE TITLE
OPNSense server send default route to client even if it disabled 

### ISSUE THREAD

**Issue by jpVm5jYYRE1VIKL** [opnsense/core#6267]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [*] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [*] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

Configured opvenvpn server with redirect gateway disabled. 

*Tip*: to validate your setup was working with the previous version, use opnsense-revert (https://docs.opnsense.org/manual/opnsense_tools.html#opnsense-revert)

**To Reproduce**

1. Connect to opnsense using openvpn
2. ip route list
3. See that default route installed 

**Expected behavior**

Must be installed only routes which written in option : IPv4 Local Network

**Describe alternatives you considered**

Not exist

**Screenshots**

![ksnip_20230126-200617](https://user-images.githubusercontent.com/22169129/214927050-cfb76850-d66e-488f-9d38-f58e5a862320.png)
![ksnip_20230126-200711](https://user-images.githubusercontent.com/22169129/214927082-2abb7d79-cb23-4f33-802a-b6cf756fc6e7.png)

**Relevant log files**

If applicable, information from log files supporting your claim.

**Additional context**

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 23.1-amd64
FreeBSD 13.1-RELEASE-p5
OpenSSL 1.1.1s 1 Nov 2022

**Comment by mimugmail** [comment]
OpenVPN client logs please

**Comment by jpVm5jYYRE1VIKL** [comment]
After investigation i found that this issue inside linux openvpn networkmanager module. Original openvpn work normal.

**Comment by fichtner** [comment]
@jpVm5jYYRE1VIKL Close then?

**Comment by jpVm5jYYRE1VIKL** [comment]
Oh sorry.

**Comment by fichtner** [comment]
no problem, glad this could be resolved :)
