### ISSUE TITLE
unbound: aliases provide no additional benefit

### ISSUE THREAD

**Issue by 8191** [opnsense/core#627]
Is there any use-case where an alias of a host override provides any additional benefit than creating two distinct host override records? If not, I'd opt for removing the host override alias feature, since there are two bugs (one caused by myself):

* Override does not work for A or AAAA records (already present before PR #519)
* Override does not work for MX records (introduced with PR #519)

**Comment by fichtner** [comment]
Sure, let's kill it for 16.1

**Comment by fichtner** [comment]
@8191 still in for the kill? :)

**Comment by AdSchellevis** [comment]
closed by https://github.com/opnsense/core/commit/c3049819100c851a0493820437a40528ca83932a https://github.com/opnsense/core/commit/6f417404b312fafa56b92bd64c6a1f3fbb8f43d8
