### ISSUE TITLE
Reporting - Unbound DNS - Logarithmic scale save

### ISSUE THREAD

**Issue by T13nou** [opnsense/core#6271]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

Hi,

When I'm going to "Reporting > Unbound DNS" I can check the boxes "Logarythmic" but it doesn't save this setting.

If I navigate in other tabs and come back to "Reporting > Unbound DNS", the checkbox is empty.

**To Reproduce**

1. Go to "Reporting > Unbound DNS
2. Click on "Logarythmic" checkbox
3. It applies correctly
4. Go to another menu and come back to "Reporting > Unbound DNS
5. "Logarythmic" checkbox is empty

**Expected behavior**

I expect the checkbox to keep the "Logarythmic" checked and maybe a button save.

**Describe alternatives you considered**

Save button or equivalent

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 23.1
Intel NUC 11
Network Intel® I225

**Comment by swhite2** [comment]
The best course of action would be to set it in the browsers' local storage so it's implicitly saved.

Thanks for the suggestion, will add this when I get around to it :)

**Comment by T13nou** [comment]
Thanks :)

**Comment by swhite2** [comment]
Fixed in https://github.com/opnsense/core/commit/dd720b45b4bc4fcaea77e5e32ea356f886bee632
