### ISSUE TITLE
DHCP error when WAN interface is set to DHCP

### ISSUE THREAD

**Issue by T13nou** [opnsense/core#6272]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [ ] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [ ] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

When the WAN interface is set to DHCP, I constantly have this error "unknown dhcp option value 0x7d"

**To Reproduce**

1. Go to Interfaces: [WAN]
2. Click on IPv4 Configuration Type as DHCP
3. Click on Save
4. Wait few hours
5. See in the logs "System: Log Files: General" the error "unknown dhcp option value 0x7d"

**Expected behavior**

No error

**Describe alternatives you considered**

Going to static IP address

**Screenshots**

![opnsense-dhcp](https://user-images.githubusercontent.com/64090484/215042822-d859c773-30a8-4787-a134-55efe63fefd7.png)

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 23.1
Intel NUC 11
Network Intel® I225
LAN Client > Opnsense > ISP Router > Internet

**Comment by fichtner** [comment]
And this impacts operation how?

**Comment by T13nou** [comment]
@fichtner no visible impact on operations. 

Just a concern to see if it will trigger some disfunction in the future..

**Comment by fichtner** [comment]
I can move that to src.git but dhclient probably will never support it. So it's just a spurious message about unsupported option being offered by ISP (and not an error really).

I'd rather close this one than moving and closing it in a year.


Cheers,
Franco

**Comment by T13nou** [comment]
@fichtner  thanks Franco ! no worry you can close if there is no operation impact

**Comment by fichtner** [comment]
@T13nou thanks :)
