### ISSUE TITLE
Reporting - Unbound DNS - Blocklist button works but not update itself

### ISSUE THREAD

**Issue by T13nou** [opnsense/core#6273]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [ ] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [ ] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

From "Reporting: Unbound DNS", if you go into "Details" tab to block a site, the blocklist button (and maybe action) is not updated to whitelist button (and maybe action).

**To Reproduce**

1. Go to '"Reporting: Unbound DNS", "Details" tab
2. Click on "Block domain" icon on whatever the line is
3. The domain is well included into "Services: Unbound DNS: Blocklist" & "Blocklist Domains"
4. But if I go back to "Reporting: Unbound DNS", "Details" tab and search for the same entry, the icon and action is not changed to "Whitelist domain" with pencil icon

**Expected behavior**

When you click "Block domain"
The domain is added to Services: Unbound DNS: Blocklist" & "Blocklist Domains"
In "Reporting: Unbound DNS", "Details" tab the icon is changed to Pencil with "Whitelist domain"

**Screenshots**

![unbound_block](https://user-images.githubusercontent.com/64090484/215062600-e3800ca8-0d68-44b9-8eab-a902d1d373f5.jpg)

**Relevant log files**

If applicable, information from log files supporting your claim.

**Additional context**

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense  23.1
Intel NUC 11
Network Intel® I225

**Comment by T13nou** [comment]
Well it seems that there is no correlation between the Unbound DNS: Blocklist and the report view.

Blocklisted sites are marked as whitelisted in the report view.

**Comment by swhite2** [comment]
> Well it seems that there is no correlation between the Unbound DNS: Blocklist and the report view.

There is, it just needs to reflect the current state of a domain, which currently isn't the case, it's instead maintaining a snapshot in history. I'll get back to you with a patch to try out and see if it improves the situation.

**Comment by T13nou** [comment]
Sure thanks @swhite2 !

**Comment by swhite2** [comment]
Hi @T13nou, can you try `# opnsense-patch f239c6680 3b711a3a9`?

Reference commits:
- https://github.com/opnsense/core/commit/f239c6680ffdd57b5d47708ead5f3f98c253ac32
- https://github.com/opnsense/core/commit/3b711a3a9cc8cc8812ec6d2a93691cad29bb6699

You can revert it with `# opnsense-patch 3b711a3a9 f239c6680`

**Comment by T13nou** [comment]
Hi @swhite2 , works OK !

I've tried blocklist & whitelist again and status is correct in the logs :) should I keep the patch ?

**Comment by swhite2** [comment]
You can keep it running if it suits your needs, the fix will go into the next minor release.

**Comment by swhite2** [comment]
Fixed in https://github.com/opnsense/core/commit/3b711a3a9cc8cc8812ec6d2a93691cad29bb6699
