### ISSUE TITLE
Services: Unbound DNS: Blocklist - Add update lists feature (cron?)

### ISSUE THREAD

**Issue by T13nou** [opnsense/core#6275]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**

A clear and concise description of what the problem is including your motivation for the request,
i.e. "For the purpose of [...] I am missing a solution that will [...]."

**Describe the solution you like**

Hi

Would be interesting to have a "update blocklist" feature in Services: Unbound DNS: Blocklist.

I don't know if they are even updated regularly. 

Maybe a cron where user can choose the interval to update.

Thanks :)

T13nou

**Describe alternatives you considered**

None

**Comment by fichtner** [comment]
It should be "Update Unbound DNSBLs". Can you try?

**Comment by T13nou** [comment]
Yes sorry I was not clear : I can make the cron using the cron section.

But just as an idea, it would be good to have this option directly in the unbound section for User Experience easyness :)

**Comment by fichtner** [comment]
Ah ok. Web proxy remote access control lists has a "schedule with cron" button which works ok. Intrusion detection has a "Schedule" tab which works a bit wonky in my view. I don't think we have added any more of those for simplicity's sake. Not sure what @AdSchellevis and @swhite2 think about it.

**Comment by AdSchellevis** [comment]
leave it at cron, probably make sure the documentation explains how to use it. It adds quite some complexity for little gain

**Comment by T13nou** [comment]
yup ! I close this one :)

**Comment by logicito** [comment]
If I use a custom link for the blocklist (URLs of Blacklists) instead of the predefined Type of DNSBL, will the cron I had created for the automatic daily (Update Unbound DNSBLs) download will also pull the updates from  the custom URLs of Blocklists link? Thanks
