### ISSUE TITLE
IPSec new connection UI: email cannot be used as authentication ID

### ISSUE THREAD

**Issue by rmaffeo** [opnsense/core#6277]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

In 23.1, using the new IPSec Connections UI, when populating the "Remote Authentication" section with a new entry, I am unable to use an email as the Id string and receive a "text validation error" message when trying to save the page.  Although email IDs are deprecated, this should still be an allowable configuration. 

1. Go to 'VPN->IPSec->Connections [new]'
2. Click on '+' (add) to create a new connection.
3. Click on 'Save', defaults are fine for this example
4. Scroll down to 'Remote Authentication'
5. Click '+' (add)
6. Type an email address (foo@example.com) in the Id field 
7. See the "text validation error" message

**Expected behavior**

The field should be accepted and populated into swanctl.conf.

**Screenshots**
![image](https://user-images.githubusercontent.com/13106716/215225875-2ff1450e-88ae-4738-81cf-42a9596ac226.png)

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 23.1 (amd64, OpenSSL).

**Comment by AdSchellevis** [comment]
@rmaffeo https://github.com/opnsense/core/commit/9d33c518e6136aed40d6ea15be920a5ff7bbe023 should do the trick, thanks for reporting.

**Comment by MichaelKuch** [comment]
@AdSchellevis: In 23.1.1_2 the above fix allows to use an email address as authentication ID for the local authentication but not for the remote authentication. The fix in Swanctl.xml for line 142 and 146 must also be applied in the `<remotes>...</remotes>` section of Swanctl.xml in line 205 and 209 where there are also `<id>...</id>` and `<eap_id>...</eap_id>` elements.

**Comment by AdSchellevis** [comment]
@MichaelKuch right, missed a spot there indeed. fixed in https://github.com/opnsense/core/commit/652b35e87a5179dc17fb48534ba07104769f0514
