### ISSUE TITLE
CARP link from dashboard not valid in 23.1

### ISSUE THREAD

**Issue by stelb** [opnsense/core#6278]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

After upgrade to 23.1 the CARP link from the dahboard does not work anymore. I get a page not found for /carp_status.php

I used that link right before upgrading the opnsense master.

**To Reproduce**

1. Go to Lobby, Dashboard
2. Add CARP widget
3. Click on CARP link
4. Page not found

**Expected behavior**

I get to the CARP status page and enable/disable maintenance mode

**Describe alternatives you considered**

I can do what I want via interfaces/virtual ips/status

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 23.1 (amd64, OpenSSL).
AMD GX-412TC SOC (4 cores, 4 threads)
Network Intel® I210-AT

**Comment by fichtner** [comment]
Thanks! If @AdSchellevis doesn’t steal this I’ll do it on Monday.

**Comment by AdSchellevis** [comment]
I already did, yesterday :) https://github.com/opnsense/core/commit/ed12696f122a65241afb5f87d4f3dcc450eb10f7

**Comment by fichtner** [comment]
👍

**Comment by stelb** [comment]
Perfect, thanks! :)
