### ISSUE TITLE
IPsec: new connection UI: sha1 not a selectable integrity algorithm option

### ISSUE THREAD

**Issue by rmaffeo** [opnsense/core#6279]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

sha1 is mostly missing in the proposal options in the new IPsec connection UI; although deprecated due to security concerns, sha1 is still an allowable integrity algorithm and should be selectable.

**To Reproduce**

1. Go to 'VPN->IPSec->Connections [new]'
2. Click on '+' (add) to create a new connection.
3. Click on 'Save', defaults are fine for this example
4. Scroll down to 'Children'
5. Click '+' to add
6. Scroll down to 'ESP proposals' and select the drop down
7. There are very few choices for sha1.  For example, my configuration uses 'eas128-sha1-modp2048' but it is not a pickable option in the field list.

**Expected behavior**

Sha1 options should be available in the list.  More proposal options were configurable with the old UI.

**Additional context**

One possible solution is to add 'sha1' to line 72 of IPsecProposalField.php so that it reads:
`foreach (['sha1', 'sha256', 'sha384', 'sha512', 'aesxcbc'] as $intalg) {`
However, I have not validated that all resulting combinations are valid, and it also pollutes the pick list.

An alternative would be to add it as a one-off:
`self::$internalCacheOptionList['aes128-sha1-modp2048'] = 'aes128-sha1-modp2048';`

Or, instead of a pick list, allow the user to manually enter a proposal string.

**Environment**

Software version used and hardware type if relevant, e.g.:
OPNsense 23.1 (amd64, OpenSSL).

**Comment by AdSchellevis** [comment]
We left the weak options out on purpose (https://docs.strongswan.org/docs/5.9/howtos/securityRecommendations.html), if more people seem to be needing them, we may revisit the list, but as long as the legacy option (tunnels) is also available, I'm not sure we should start lowering security already.

**Comment by rmaffeo** [comment]
Thank you for the quick reply.  Understood, and seems reasonable.  While I would have liked to use the new UI, I'll continue to use the legacy tunnels interface for now until I can get my other endpoint upgraded to a different proposal scheme.

**Comment by mimugmail** [comment]
I think sha1 should stay. Couple of hospitals connected to plenty of sites depend on equipment of a third party. I know that also an old ASA supports sha256, but most of the time the admin of this device is afraid to Touch it. In the end opnsense is "guilty" since it doesnt work anymore after the update.

**Comment by AdSchellevis** [comment]
If we can agree on a single or a couple of unsafe ciphers, we may discuss. Keep in mind this only involves the new input way, the old one will likely remain for a couple of years.

In theory both can be combined as well (when the end date for old cruft is two years from now, I'm not sure we should try to aim for inclusion, upstream might deprecate them earlier then we do in that case).

So, open for discussion as far as I'm concerned. More feedback from more people helps.

**Comment by andrewhotlab** [comment]
I just had the same problem trying to port into the new configuration scheme an old one which is still using `3des-sha1-modp1024` in phase 1 encryption proposal... I completely agree with @AdSchellevis about the choice to left the weak options out.
However, with the only purpose to help who out there needs to support unfortunare real-world scenarios... maybe when the old input way will be phased out, it would be a nice idea to allow admins (at their own and sole risk) to manually enter any cipher combination that Strongswan will still allow (even if discouraged/deprecated).
I'm not a developer, so honestly I have only vague idea about it, but maybe such approach would break the MVC logic (there is the need to check user input before passing it to the controller, or is the controller which validate the input?).

**Comment by AdSchellevis** [comment]
> ...However, with the only purpose to help who out there needs to support unfortunare real-world scenarios... maybe when the old input way will be phased out,...

There's time to decide what todo, this is only the first version. But upstream (Strongswan/Freebsd) might change as well in the future, in which case both aren't possible. Collecting which ciphers you do need in this ticket will certainly help by the way, you seem to be needing `3des-sha1-modp1024` the reporter of this ticket `aes128-sha1-modp2048`. 

Adding them to the list with a note is relatively easy, we can do that at any time in the future when still relevant. 

You should be able to combine the old and new input methods in the gui, leaving only the old cruft on "tunnels" by the way.

**Comment by brandlit** [comment]
Hello all, 

i would need aes256-sha512-modp1024

**Comment by fichtner** [comment]
Here is a list if IANA-based deprecations: https://www.iana.org/assignments/ikev2-parameters/ikev2-parameters.xml

Which modp1024 / DH group is that? Group 2 doesn't seem to be deprecated, but 22 is as per that document.

**Comment by brandlit** [comment]
modp1024 - DH2

**Comment by Monviech** [comment]
Hello,
I would need one of the following proposals, most Fritzbox still use them (sadly) as defaults:

IKE:AES_CBC_256/HMAC_SHA2_512_256/PRF_HMAC_SHA2_512/MODP_1024
IKE:AES_CBC_256/HMAC_SHA1_96/PRF_HMAC_SHA1/MODP_1024
IKE:AES_CBC_192/HMAC_SHA1_96/PRF_HMAC_SHA1/MODP_1024
IKE:AES_CBC_128/HMAC_SHA1_96/PRF_HMAC_SHA1/MODP_1024
IKE:3DES_CBC/HMAC_SHA1_96/PRF_HMAC_SHA1/MODP_1024
IKE:DES_CBC/HMAC_SHA1_96/PRF_HMAC_SHA1/MODP_1024
IKE:AES_CBC_256/HMAC_MD5_96/PRF_HMAC_MD5/MODP_1024
IKE:AES_CBC_192/HMAC_MD5_96/PRF_HMAC_MD5/MODP_1024
IKE:AES_CBC_128/HMAC_MD5_96/PRF_HMAC_MD5/MODP_1024
IKE:3DES_CBC/HMAC_MD5_96/PRF_HMAC_MD5/MODP_1024
IKE:DES_CBC/HMAC_MD5_96/PRF_HMAC_MD5/MODP_1024

**Comment by Mirelt** [comment]
Would it be an option to add a button "Allow weak deprecated ciphers"? There are many old and new devices that only support weak ciphers. For example, our industry router supports only 3DES & AES 128-192-256 with MD5 & SHA-1.

**Comment by itkfm** [comment]
> In the end opnsense is "guilty"

Yeah. We don’t use IPsec to setup new tunnels. We didn’t in the past. And we don’t plan to use it for the time being.

But we use this feature to establish tunnels to all sort of misc servers that our clients’ partners run. We don’t get to choose or change what they might use. OpenVPN or Wireguard usually are no option either (although I’d prefer them over IPsec).

Recently had a client ask us to configure a connection to their brand new infrastructure (provided by a different company) with IKEv1. I expect those legacy technologies to be around for quite a while and much longer.

So what happens when OPNsense throws out all those old ciphers early on? We get to explain to mildly disinterested network admins why our fantastic open-source firewall doesn’t speak the same protocols that all the expensive tech from big name companies have been supporting for ages. “It works for everyone else smoothly”, will be the most sympathetic thing we’ll get to hear, unfortunately. While at the same time the customer expects a working solution…

If the IPsec implementation doesn’t work for the real-world applications we run into, then it doesn’t do the job for us.

**Comment by AdSchellevis** [comment]
> So what happens when OPNsense throws out all those old ciphers early on?

We're not, nor did we claim so at any point, there is just a risk of upstream projects (Strongswan, FreeBSD, ..) removing support for deprecated ciphers at some point in which case consumers might end up with issues impossible to fix, which to some degree has been warned about. The risk might be low, but it exists. As long as the (legacy) tunnel options is being shipped on our end, there's no rush in adding anything, as underneath we did refactor the tunnels to use the same `swanctl.conf`  as well. 

If it wasn't clear yet, let me make it more clear now, we are not planning to remove the old tunnel option soon, you may expect a reasonable amount of unsecure ciphers in the new connections ui before it vanishes.

This particular ticket exists so we can collect the current relevant ones for our new component and add them at some point, nothing more nothing less. We just need to find a way to explain you shouldn't use them, which in the initial versions was not yet possible. 

> If the IPsec implementation doesn’t work for the real-world applications we run into, then it doesn’t do the job for us.

Fair enough, personally I can't think of a reason why business don't want to adopt to newer safer standards at some point, adoption time is just all that counts in these cases. We just tend to make people aware of the issues with older standards, some other parties might find it less important to educate their customers about safer options...

**Comment by AdSchellevis** [comment]
moving discussion to https://github.com/opnsense/core/issues/6928#issuecomment-1763054247

**Comment by fichtner** [comment]
SHA-1 will be selectable via #6928, closing this ticket as support
