### ISSUE TITLE
Allowed memory size of 1073741824 bytes exhausted (tried to allocate 12288 bytes) in /usr/local/opnsense/mvc/app/models/OPNsense/Firewall/Alias.php on line 192

### ISSUE THREAD

**Issue by marrobHD** [opnsense/core#6281]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [ x ] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [ x ] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

I did some work on the opnsense firewall today. I noticed that it took a bit to save the firewall rules. At some point I noticed that some firewall rules weren't applying. So I did the reboot. 

It greet me with Fatal error:
> Allowed memory size of 1073741824 bytes exhausted (tried to allocate 12288 bytes) in /usr/local/opnsense/mvc/app/models/OPNsense/Firewall/Alias.php on line 192

**To Reproduce**

There is maybe something with the configuration which OPNSense generated. 

**Expected behavior**

The firewall (service) should start.

**Describe alternatives you considered**

**Screenshots**

![IMG_20230129_173639.jpg](https://user-images.githubusercontent.com/29308361/215343167-5615c0e2-6cda-4887-a595-a04e1c6c5b33.jpg)

**Relevant log files**

**Additional context**

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 23.1 (amd64, OpenSSL).
Intel N6005
Intel i226

**Comment by AdSchellevis** [comment]
I would first check the contents of the installed aliases, when trying to allocate over 1GB chances are quite high there's a configuration issue. context matters....

**Comment by kulikov-a** [comment]
hm..any chance that you made a port alias referring to itself?

**Comment by marrobHD** [comment]
First of all, thanks for the help. 
I found the last working config (`/conf/backup/config-1675003671.2281.xml`).
After changes in  `/conf/backup/config-1675003817.1049.xml`, it didn't came up.
Here the diff:

```diff
root@OPNsense:~ # diff -b -u -a /conf/backup/config-1675003817.1049.xml /conf/backup/config-1675003671.2281.xml
--- /conf/backup/config-1675003817.1049.xml	2023-01-29 15:50:17.117455000 +0100
+++ /conf/backup/config-1675003671.2281.xml	2023-01-29 15:47:51.239206000 +0100
@@ -2851,8 +2851,8 @@
   </widgets>
   <revision>
     <username>may@10.0.0.2</username>
-    <time>1675003817.1049</time>
-    <description>/api/firewall/alias/addItem/ made changes</description>
+    <time>1675003671.2281</time>
+    <description>/firewall_rules_edit.php made changes</description>
   </revision>
   <OPNsense>
     <captiveportal version="1.0.1">
@@ -3322,18 +3322,6 @@
 8080</content>
             <categories/>
             <description>Web Ports</description>
-          </alias>
-          <alias uuid="d6abfc48-1b5a-4a8c-8cf9-ad82e6fab2a5">
-            <enabled>1</enabled>
-            <name>8080</name>
-            <type>port</type>
-            <proto/>
-            <interface/>
-            <counters>0</counters>
-            <updatefreq/>
-            <content>8080</content>
-            <categories>dc6a6c16-6a08-47a4-8f26-e6b5006b6c98</categories>
-            <description>Port 8080 used for Wings API</description>
           </alias>
         </aliases>
       </Alias>
```

**Comment by kulikov-a** [comment]
yep, looks like infinite loop in `getPortAlias`
imho you can try to edit config.xml and change the content field to something like 8081 and reboot. then edit alias: change alias name so it not equal to content (and change back to 8080). im shure that this will be fixed very soon )

**Comment by marrobHD** [comment]
Since I rebooted and firewall didn't start, GUI was not an option. Thanks!

**Comment by AdSchellevis** [comment]
https://github.com/opnsense/core/commit/2ba91361a7e27f616fa8f1b46250267ffac34e74 should prevent this from happening in the future.
