### ISSUE TITLE
IPsec Mobile

### ISSUE THREAD

**Issue by at0msense** [opnsense/core#6294]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [ X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [ X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

After upgrading to 23.1, I noticed that the "Lease Status" does not show the complete DN and the "Remote ID" field is too short.
Is it possible to make "Version" a bit narrower and "Remote ID" a bit wider in the "Status Overview" ?

![status_overview](https://user-images.githubusercontent.com/124162279/216050815-71fc2018-9f05-4ce2-831c-a97b166fd56c.png)
![lease_status](https://user-images.githubusercontent.com/124162279/216050821-a8600534-8d97-4452-b31a-62d9e309ebfc.png)

**Comment by AdSchellevis** [comment]
We could hide local/remote auth by default and limit the almost fixed columns, which would result in https://github.com/opnsense/core/commit/484e89f8bd56b922f5bc9743f905ab07ae6eb6f9

Does that help?

To try locally:
```
opnsense-patch 484e89f
````

**Comment by at0msense** [comment]
"Status Overview" looks a bit better. Would it be possible to make "Local IP" narrower ?
![status_overview_first_fix](https://user-images.githubusercontent.com/124162279/216089285-fc388b68-3317-4e99-83cf-5f9482ac6d69.png)

**Comment by AdSchellevis** [comment]
not really to be honest as these scale with screen size now and local/remote ip can be quite large as well. You can always hide columns locally.

**Comment by at0msense** [comment]
I didn't know that I can hide columns. Sorry for that. That would be enough for one problem. 
Only that the user field is too short at the "Lease Status" can not be fixed.

**Comment by AdSchellevis** [comment]
ah, I was wondering why the lease status was also in the screenshots. I can push an update later for that as well

**Comment by at0msense** [comment]
That would be great.

**Comment by at0msense** [comment]
Unfortunately there is only "C=DE" in the User column and not the entire DN.

**Comment by at0msense** [comment]
I also just saw that the IPsec widget doesn't show mobile connections.

**Comment by at0msense** [comment]
I hope it is still usable despite all the blackening.
![swanctl_leases](https://user-images.githubusercontent.com/124162279/216108463-ba3fa81b-85bd-46a4-ad19-8792e9ed544f.png)

**Comment by AdSchellevis** [comment]
can you copy -> paste the text and change the sensitive data? I need the format in order to replicate something....

**Comment by at0msense** [comment]
Better ?

root@osrc:~ # /usr/local/sbin/swanctl --list-pools --leases
no files found matching '/usr/local/etc/strongswan.opnsense.d/*.conf'
defaultv4            111.111.111.64                       1 / 2 / 62
  111.111.111.65                 offline  'C=DE, O=Company, CN=Smith.L'
  111.111.111.66                 online   'C=DE, O=Company, CN=Wesson.O'
  111.111.111.67                 offline  'C=DE, O=Company, CN=Washington.D'
user1_v4             111.111.111.2                         0 / 1 / 1
  111.111.111.2                  offline  'C=DE, O=Company, CN=Gulf.T'
user2_v4             111.111.111.3                         1 / 0 / 1
  111.111.111.3                  online   'C=DE, O=Company, CN=Luna.F'
user3_v4             111.111.111.4                         1 / 0 / 1
  192.168.177.4                  online   'C=DE, O=Company, CN=Brandon.H'
group_v4             111.111.111.64                       0 / 0 / 62
group_v6             fd25:5555:6666:777::                0 / 0 / 254

**Comment by AdSchellevis** [comment]
@at0msense yes, https://github.com/opnsense/core/commit/3d6876ee1d0e068b9b20ba077d44792da94e46ed should fix it

**Comment by at0msense** [comment]
It works. Thanks a lot.
