### ISSUE TITLE
Router Advertisements provide "fe80" address as gateway to clients

### ISSUE THREAD

**Issue by thefiredragon** [opnsense/core#6295]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

OPNsense RA & DHCPv6 provide clients a "fe80" address of the firewall instead of using the the lan interface IPv6 address.

Same issue by another user on reddit:

https://www.reddit.com/r/OPNsenseFirewall/comments/ha2sy2/router_advertisement_default_gateway/

**To Reproduce**

Setup static private IPv6 on a lan interface.
Setup DHCPv6 for a a range you like.
Enable RA in managed mode.

Clients get an "fe80::441d:81ff:fe65:5b7a" as router address (example) which I can find under system - routes - status -> 

ipv6 | fe80::441d:81ff:fe65:5b7a%vtnet8 | link#9 | UHS | NaN | 16384 | lo0 | Loopback

**Expected behavior**

Clients should get the lan IPv6 of the firewall instead of the loopback IPv6 address:

Software version used and hardware type if relevant, e.g.:

OPNsense 23.1_6-amd64FreeBSD 13.1-RELEASE-p5OpenSSL 1.1.1s 1 Nov 2022
--

**Comment by fichtner** [comment]
Huh, fe80::441d:81ff:fe65:5b7a%vtnet8 is clearly scoped through vtnet8, which is probably the interface you want your RAs to be sent from?

**Comment by thefiredragon** [comment]
It's right, RAs should be sent from vtnet8 which is our internal network interface

The reason is, we're getting only a fixed public IPv6 with an /64 prefix so we can't create subnets for a routing.
So we like to setup internal a "fd" IPv6 range which we like to map with NPTv6 as a workaround. 
Clients can't ping "fe80::441d:81ff:fe65:5b7a" or ssh to the this firewall address.

**Comment by fichtner** [comment]
I don't see why a link-local attached client would not be able to ping the vtnet8 link-local unless it's blocked on the firewall, but that also would be pretty surprising given special link-local handling we do.

**Comment by thefiredragon** [comment]
output from my mac
I've tried to ping this local address, also I can't see in live view that this ip will be dropped, more my mac told me "no route to host"

```
➜  ~ ifconfig
lo0: flags=8049<UP,LOOPBACK,RUNNING,MULTICAST> mtu 16384
	options=1203<RXCSUM,TXCSUM,TXSTATUS,SW_TIMESTAMP>
	inet 127.0.0.1 netmask 0xff000000
	inet6 ::1 prefixlen 128
	inet6 fe80::1%lo0 prefixlen 64 scopeid 0x1
	nd6 options=201<PERFORMNUD,DAD>
gif0: flags=8010<POINTOPOINT,MULTICAST> mtu 1280
stf0: flags=0<> mtu 1280
en0: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	options=400<CHANNEL_IO>
	ether cc:f9:e4:9d:3a:23
	inet6 fe80::147e:873d:b222:8d70%en0 prefixlen 64 secured scopeid 0x4
	inet 10.60.1.50 netmask 0xfffffe00 broadcast 10.60.1.255
	inet6 fdf5:e60e:37b2:98cc:5428:e987:3ece:60a8 prefixlen 64 dynamic
	nd6 options=201<PERFORMNUD,DAD>
	media: autoselect
	status: active
awdl0: flags=8802<BROADCAST,SIMPLEX,MULTICAST> mtu 1484
	options=400<CHANNEL_IO>
	ether da:62:3b:cf:fb:a4
	media: autoselect
	status: inactive
utun0: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> mtu 1380
	inet6 fe80::b0eb:f8c2:2b65:7954%utun0 prefixlen 64 scopeid 0x6
	nd6 options=201<PERFORMNUD,DAD>
utun1: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> mtu 2000
	inet6 fe80::a092:624f:85f6:875b%utun1 prefixlen 64 scopeid 0x7
	nd6 options=201<PERFORMNUD,DAD>
utun2: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> mtu 1000
	inet6 fe80::ce81:b1c:bd2c:69e%utun2 prefixlen 64 scopeid 0x8
	nd6 options=201<PERFORMNUD,DAD>
awdl1: flags=8802<BROADCAST,SIMPLEX,MULTICAST> mtu 1484
	options=400<CHANNEL_IO>
	ether 8e:da:2e:dd:92:05
	media: autoselect
	status: inactive
awdl2: flags=8802<BROADCAST,SIMPLEX,MULTICAST> mtu 1484
	options=400<CHANNEL_IO>
	ether f2:8c:89:ea:d1:95
	media: autoselect
	status: active
awdl3: flags=8802<BROADCAST,SIMPLEX,MULTICAST> mtu 1484
	options=400<CHANNEL_IO>
	ether 0e:48:18:3e:3e:c3
	media: autoselect
	status: inactive
awdl4: flags=8802<BROADCAST,SIMPLEX,MULTICAST> mtu 1484
	options=400<CHANNEL_IO>
	ether be:9f:30:7b:89:62
	media: autoselect
	status: inactive
awdl5: flags=8802<BROADCAST,SIMPLEX,MULTICAST> mtu 1484
	options=400<CHANNEL_IO>
	ether ee:8b:19:9b:ab:ab
	media: autoselect
	status: inactive
awdl6: flags=8802<BROADCAST,SIMPLEX,MULTICAST> mtu 1484
	options=400<CHANNEL_IO>
	ether ca:43:d9:fc:bc:5c
	media: autoselect
	status: inactive
awdl7: flags=8802<BROADCAST,SIMPLEX,MULTICAST> mtu 1484
	options=400<CHANNEL_IO>
	ether b2:65:be:b2:ee:53
	media: autoselect
	status: inactive
awdl8: flags=8802<BROADCAST,SIMPLEX,MULTICAST> mtu 1484
	options=400<CHANNEL_IO>
	ether c2:cd:2d:72:89:91
	media: autoselect
	status: inactive
awdl9: flags=8802<BROADCAST,SIMPLEX,MULTICAST> mtu 1484
	options=400<CHANNEL_IO>
	ether 16:8c:bf:81:5d:c6
	media: autoselect
	status: inactive
awdl10: flags=8802<BROADCAST,SIMPLEX,MULTICAST> mtu 1484
	options=400<CHANNEL_IO>
	ether 52:a0:59:26:6a:3f
	media: autoselect
	status: active
➜  ~ ping6 fe80::147e:873d:b222:8d70
PING6(56=40+8+8 bytes) fe80::147e:873d:b222:8d70%en0 --> fe80::147e:873d:b222:8d70
16 bytes from fe80::147e:873d:b222:8d70%en0, icmp_seq=0 hlim=64 time=0.443 ms
16 bytes from fe80::147e:873d:b222:8d70%en0, icmp_seq=1 hlim=64 time=0.246 ms
^C
--- fe80::147e:873d:b222:8d70 ping6 statistics ---
2 packets transmitted, 2 packets received, 0.0% packet loss
round-trip min/avg/max/std-dev = 0.246/0.345/0.443/0.098 ms
➜  ~ ping6 fe80::441d:81ff:fe65:5b7a
PING6(56=40+8+8 bytes) fe80::147e:873d:b222:8d70%en0 --> fe80::441d:81ff:fe65:5b7a
ping6: sendmsg: No route to host
ping6: wrote fe80::441d:81ff:fe65:5b7a 16 chars, ret=-1
ping6: sendmsg: No route to host
ping6: wrote fe80::441d:81ff:fe65:5b7a 16 chars, ret=-1
ping6: sendmsg: No route to host
ping6: wrote fe80::441d:81ff:fe65:5b7a 16 chars, ret=-1
^C
--- fe80::441d:81ff:fe65:5b7a ping6 statistics ---
4 packets transmitted, 0 packets received, 100.0% packet loss
➜  ~ ssh root@fe80::441d:81ff:fe65:5b7a
ssh: connect to host fe80::441d:81ff:fe65:5b7a port 22: No route to host
```

<img width="504" alt="Bildschirm­foto 2023-02-01 um 15 57 51" src="https://user-images.githubusercontent.com/20144860/216078190-211e1fab-c1e6-4d60-a12f-de880037ee26.png">

<img width="1415" alt="Bildschirm­foto 2023-02-01 um 15 58 51" src="https://user-images.githubusercontent.com/20144860/216079067-978f3e73-e731-491c-95e3-ee6d41139311.png">
<img width="1424" alt="Bildschirm­foto 2023-02-01 um 15 59 04" src="https://user-images.githubusercontent.com/20144860/216079077-a4dc80ff-e650-4918-9ca5-371eab6bbde7.png">
<img width="1170" alt="Bildschirm­foto 2023-02-01 um 15 59 28" src="https://user-images.githubusercontent.com/20144860/216079081-eece4aa3-d934-4ecf-b663-ae812bd8e55e.png">
<img width="1582" alt="Bildschirm­foto 2023-02-01 um 16 00 32" src="https://user-images.githubusercontent.com/20144860/216079086-3adef0a7-6329-47f2-99ee-cc565b569009.png">

**Comment by fichtner** [comment]
It seems to take the correct scope in ping (%en0) but I have no clue why it wouldn't work. There is no good chance to cover this in community support scope as the issue is likely local and needs digging.

**Comment by thefiredragon** [comment]
It's strange under an Windows client it seem to work

```
C:\Users\administrator>ping -6 fe80::441d:81ff:fe65:5b7a

Ping wird ausgeführt für fe80::441d:81ff:fe65:5b7a mit 32 Bytes Daten:
Antwort von fe80::441d:81ff:fe65:5b7a: Zeit=1ms
Antwort von fe80::441d:81ff:fe65:5b7a: Zeit<1ms
Antwort von fe80::441d:81ff:fe65:5b7a: Zeit<1ms
Antwort von fe80::441d:81ff:fe65:5b7a: Zeit<1ms

Ping-Statistik für fe80::441d:81ff:fe65:5b7a:
    Pakete: Gesendet = 4, Empfangen = 4, Verloren = 0
    (0% Verlust),
Ca. Zeitangaben in Millisek.:
    Minimum = 0ms, Maximum = 1ms, Mittelwert = 0ms

C:\Users\administrator>
```
So it's look like macOS has a problem with this settings but why?

**Comment by thefiredragon** [comment]
When I specify the interface under mac and linux like : ping6 -I eth3 fe80::441d:81ff:fe65:5b7a  I can ping the link local address of the firewall.

On windows its working directly with ssh and ping, under mac and linux I need to specify the interface 

```
➜  root@dNextCloud  ~ ping6  fe80::441d:81ff:fe65:5b7a
PING fe80::441d:81ff:fe65:5b7a(fe80::441d:81ff:fe65:5b7a) 56 data bytes
From fe80::f425:c7ff:fec9:d626%eth0 icmp_seq=1 Destination unreachable: Address unreachable
From fe80::f425:c7ff:fec9:d626%eth0 icmp_seq=2 Destination unreachable: Address unreachable
From fe80::f425:c7ff:fec9:d626%eth0 icmp_seq=3 Destination unreachable: Address unreachable
^C
--- fe80::441d:81ff:fe65:5b7a ping statistics ---
5 packets transmitted, 0 received, +3 errors, 100% packet loss, time 4098ms

➜  root@dNextCloud  ~ cat /etc/network/interfaces
auto lo
iface lo inet loopback

auto eth0
iface eth0 inet static
	address 192.168.10.210/24

auto eth1
iface eth1 inet static
	address 37.24.63.251/20
	gateway 37.24.63.241

auto eth2
iface eth2 inet static
	address 10.70.0.26/23
	gateway 10.70.1.254

auto eth3
iface eth3 inet dhcp

iface eth3 inet6 dhcp

➜  root@dNextCloud  ~

```

My question is here, is this the expected behaviour?
Is there a way to set the interface IPv6 for RA?

**Comment by thefiredragon** [comment]
Till yet I didn't find a solution to reach the gateway address if a machine has multiple interfaces on linux or mac
A VM with a single interface setup can reach the gateway address.


Another question is HA with IPv6 possible/ resolved?
I had read I need to ensure to stop ra daemon on backup, but how would be the handling by a failure of the master firewall?

**Comment by fichtner** [comment]
#5185 has a wonderful discussion on the subject
