### ISSUE TITLE
IPsec Widget empty

### ISSUE THREAD

**Issue by at0msense** [opnsense/core#6297]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X ] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X ] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

After upgrade to 23.1 the IPsec widget for Mobile is empty.

![ipsec_widget_tunnels](https://user-images.githubusercontent.com/124162279/216116978-2a5fb481-5543-4c98-84bf-36b313cdc7b7.png)

![ipsec_widget_overview](https://user-images.githubusercontent.com/124162279/216116899-910c437d-c486-4875-a73f-c75504aff886.png)

![ipsec_widget_mobile](https://user-images.githubusercontent.com/124162279/216116346-6451ca16-8e7a-4c73-b9ce-a86b0f6e9d53.png)

**Comment by AdSchellevis** [comment]
@at0msense thanks for reporting, https://github.com/opnsense/core/commit/958ff5b7cab6874e224a2fc3f08c8c89564eed17 should fix the output.

**Comment by at0msense** [comment]
Great. This solves the problem.
