### ISSUE TITLE
Web interface slow after upgrade

### ISSUE THREAD

**Issue by remco770** [opnsense/core#6299]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

After upgrading, the webinterface is working but really slow. Even after disabeling https

**Environment**

Proxmox
Intel Atom c2750f
Onboard nics

Version 23.1.6

**Comment by Shogobg** [comment]
I am experiencing the same issue.

**Comment by remco770** [comment]
@Shogobg I think i'd managed to fix it by doing the following:

Interfaces > Settings
Check the boxes for:

Hardware CRC | Disable hardware checksum offload
Hardware TSO | Disable hardware TCP segmentation offload
Hardware LRO | Disable hardware large receive offload

So not sure why it wasn't an issue before this release. But this seems to be the fix for me.
Is it for you also the fix?

**Comment by fichtner** [comment]
> Hardware CRC | Disable hardware checksum offload
> Hardware TSO | Disable hardware TCP segmentation offload
> Hardware LRO | Disable hardware large receive offload

Those look like the recommended system defaults to me.


Cheers,
Franco

**Comment by Shogobg** [comment]
@remco770 thanks for the suggestion.
As @fichtner said, these were on by default.

It looks like the system didn't restart properly after the update.
I've force restarted it and now all is fine.

Thanks to everyone!

**Comment by fichtner** [comment]
Ah, nice. So close ticket?

**Comment by kamalteja** [comment]
> 

I encountered same problem and comment from remco770 solved in my case.
