### ISSUE TITLE
Typo in aa3a73bfe700ca4154fee044015fcdf1244957c7

### ISSUE THREAD

**Issue by trassl** [opnsense/core#63]
Dropping  cf_conf_path in aa3a73bfe700ca4154fee044015fcdf1244957c7 has a small typo in 127.

Should be `if (file_exists('/cf/conf/config.xml')) {`.

**Comment by AdSchellevis** [comment]
thanks, should be fixed with https://github.com/opnsense/core/commit/65ab157cd611a4c0e7082294227da7527e930369

**Comment by fichtner** [comment]
Oops, thanks for catching that so quickly. I love you guys <3
