### ISSUE TITLE
Unbound: Feature to add a way to the web UI to add IPs/Subnets the ability to bypass the DNSBL

### ISSUE THREAD

**Issue by slackadelic** [opnsense/core#6300]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**

With the move to the python module for DNSBL management this has definitely given a much better performance boost and the stats are amazing.  However, there are times where I need to exclude specific hosts or even whole subnets from being filtered with the DNSBL.

Before 23.1, it was easy enough to add in (for example):

server:
    access-control-view: 192.168.1.182/32 bypass
    access-control-view: 192.168.1.0/24 dnsbl
view:
    name: "bypass"
    view-first: yes
view:
    name: "dnsbl"
    view-first: yes
    include: /data/dnsbl.conf

Then specifying the IPs/subnets with access-control-view you can determine what gets to bypass the DNSBL

**Describe the solution you like**

I've read up on the python portion of Unbound and apparently this opens a whole plethora of possibilities that weren't possible before.  

It would be nice to have a way to exclude hosts or subnets from the DNSBL filtering right from the web interface.  
I was not able to find a way to apply this from the command line since the lists are now stored in .json format

**Describe alternatives you considered**

I've looked at possibly running a secondary DNS server and pointing any client I want to bypass the DNSBL at that, but that's just not long term manageable.   I've also looked at installing the Adguard plugin as it does add this ability, however, I started using unbound for DNSBL as I would really like to keep things with the 'core' functions of the software.

Thank you!

**Comment by AdSchellevis** [comment]
We're likely going to add fine grained control in a (near) future business edition of our product.

**Comment by slackadelic** [comment]
I see, so this feature will be available only in the business edition?

**Comment by AdSchellevis** [comment]
that's highly likely indeed, we do aim to offer as much as possible in the community edition, but for some business features we add them to the business edition. 

The investment to offer this features in terms of development time was quite high, which isn't a problem,  we just have to balance our efforts.

**Comment by slackadelic** [comment]
Completely understandable.  I'll look at alternatives for my situation.  Thank you!

**Comment by fichtner** [comment]
@bignick8t3 see https://docs.opnsense.org/vendor/deciso/extended_dnsbl.html
