### ISSUE TITLE
Is Realtek Plugin Still Needed?

### ISSUE THREAD

**Issue by NOYB** [opnsense/core#6301]
22.1 Release notes
"The Realtek vendor driver is no longer bundled with the updated FreeBSD kernel. If unsure whether FreeBSD 13 supports your Realtek NIC please install the os-realtek-re plugin prior to upgrading to retain operability of your NICs."

Had to install the os-realtek-re plugin to eliminate "watchdog timeouts".

Upgrade to 23.1 is a fresh install.  The os-realtek-re plugin is not installed and not getting "watchdog timeouts".

Was there a fix to the FreeBSD driver?
Is the realtek vendor driver bundled in FreeBSD 13.1-RELEASE-p5?
What's the story?

Update to include NIC info:
#pciconf -lv
re0@pci0:1:0:0: class=0x020000 rev=0x15 hdr=0x00 vendor=0x10ec device=0x8168 subvendor=0x103c subdevice=0x881d
    vendor     = 'Realtek Semiconductor Co., Ltd.'
    device     = 'RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller'
    class      = network
    subclass   = ethernet

**Comment by fichtner** [comment]
Still the case. I don’t follow driver updates on Realtek in the kernel and as such there weren’t any between 22.7 and 23.1 from our side. 22.1 vs. 22.7 might be different, but best to check yourself.

**Comment by malhal** [comment]
This helped me get the Realtek plugin driver installed:

https://www.thomas-krenn.com/de/wiki/Realtek_NICs_in_OPNsense

Would have been nice if it could have happened automatically or at least show an alert me to the fact the NIC was going down every 6mins for over a year.
