### ISSUE TITLE
VPN Multiple Phase 2 result in Same Reqid within Security Policy Database

### ISSUE THREAD

**Issue by grbd** [opnsense/core#6302]
When setting up a IPSec site to site VPN connection with a Single Phase 1 that has multiple Phase 2 Entries
and when the "Install policy" setting is enabled for Phase 1

It seems as if the Security Policy Database lists all the subnets that are setup across the different phase2's to be attached to a single ReqId, usually Id 1
This means traffic is sent down the wrong Phase 2 connection
When attached to a Cisco this results in something like the below

```
IPSEC: Received an ESP packet (SPI= 0xF0DBDF26, sequence number= 0x21) from x.x.x.x (user= x.x.x.x) to y.y.y.y. 
The decapsulated inner packet doesn't match the negotiated policy in the SA.
The packet specifies its destination as 192.168.31.21, its source as 10.31.11.90, and its protocol as udp.
The SA specifies its local proxy as 192.168.31.0/255.255.255.0/ip/0 and its remote_proxy as 10.31.12.0/255.255.255.0/ip/0.
```

I've tried a workaround of disabling the "Install policy" setting in the Phase 1
and manually added the entries into the Security Policy Database using the correct ReqId
But this doesn't seem to work ether
So far it looks as if it only works when using a single phase2 and disabling the others

![image](https://user-images.githubusercontent.com/8965579/216443810-bf9a7b25-33ce-4eeb-8f37-3e7037865921.png)

![image](https://user-images.githubusercontent.com/8965579/216444146-a6ad1901-cd2a-4d8e-8a1c-4778947685dc.png)

**Environment**

Latest OPNsense 23.1.6 - AWS
Although I think it's also an issue on 22.7.10_2

**Comment by mimugmail** [comment]
Maybe enabling tunnel Isolation will help, but please tick install policy and dont to things manually:)

**Comment by grbd** [comment]
Ok I  thought I'd already tried that
but I just tried it now and it worked doooh
