### ISSUE TITLE
Showing expiration date column in System:Access:User list view

### ISSUE THREAD

**Issue by MichaelSeelig** [opnsense/core#6307]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**
Whoever wants to limit and mantain user access with captive portal by expiration date, is interested to see the expiration date already in the users list, instead to edit the user, scroll down, just to confirm the expiration date and to cancel the edit.

**Describe the solution you like**
It would be very helpful, if this column expiration date would be visible (added) to the users list view already. So that it is not necessary to edit the user to see the setting.

Actually there user view shows username, fullname and group, the expiration date column should be added after group column.

**Describe alternatives you considered**
An even better alternative would be, if the columns to show in the user view could be customized, by selecting the existing user fields, so everyone would be free to define which columns should show up.

**Additional context**
Nothing more to say :-)

**Comment by fichtner** [comment]
I'm not against reviewing and merging a PR for this. It should be rather trivial to add and perhaps hide on small screens.


Cheers,
Franco

**Comment by MichaelSeelig** [comment]
Whatever solution that add's the expiration date is good for anyone using this field to limit user access on CP.

**Comment by fichtner** [comment]
I doubt it's of ample use without a bootgrid coversion and search/column reorder, but as I said I don't mind a PR.
