### ISSUE TITLE
some driver licenses need to be accepted by the end user before they can be used

### ISSUE THREAD

**Issue by fabianfrz** [opnsense/core#631]
some driver fails to load because the user has to accept a license.

The problem is that the user does not get a feedback why it does not work.
Pages where a driver may be loaded should show a message to the user why it could not be loaded.

**Comment by fichtner** [comment]
Problem description:

Some old drivers have tainted licenses. The end user must accept them manually, we can't do it for him. The dmesg output gives hints, but apart from that the driver simply doesn't load correctly. We need to be able to pick up on the dmesg output, notify the user, show the actual license and have him accept it, save the whole thing in the config and patch the system.

This is quite a bit of work...

**Comment by fichtner** [comment]
@fabianfrz you can fix this now with a very simple rc.loader.d and a plugin :) see https://github.com/opnsense/plugins/commit/7ccea3e5a2ae

```
ipw_bss: You need to read the LICENSE file in /usr/share/doc/legal/intel_ipw/.
ipw_bss: If you agree with the license, set legal.intel_ipw.license_ack=1 in /boot/loader.conf.
module_register_init: MOD_LOAD (ipw_bss_fw, 0xffffffff805fd2a0, 0) error 1
ipw_ibss: You need to read the LICENSE file in /usr/share/doc/legal/intel_ipw/.
ipw_ibss: If you agree with the license, set legal.intel_ipw.license_ack=1 in /boot/loader.conf.
module_register_init: MOD_LOAD (ipw_ibss_fw, 0xffffffff805fd350, 0) error 1
ipw_monitor: You need to read the LICENSE file in /usr/share/doc/legal/intel_ipw/.
ipw_monitor: If you agree with the license, set legal.intel_ipw.license_ack=1 in /boot/loader.conf.
module_register_init: MOD_LOAD (ipw_monitor_fw, 0xffffffff805fd400, 0) error 1
```
