### ISSUE TITLE
Separate 2FA OTP field on login page

### ISSUE THREAD

**Issue by mimizone** [opnsense/core#6310]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [ *] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [ *] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**

User Experience improvement, not a functional problem

**Describe the solution you like**

When OTP 2FA is enabled for the Web UI access, there should be a separate/dedicated input field for the OTP in order for password managers to autofill.

**Describe alternatives you considered**

The alternative now is to have a 2 step process in a password manager to retrieve the password and then the OTP and copy paste them one after another, which is cumbersome to do, and not automatic.

**Additional context**

.

**Comment by meyergru** [comment]
This has got to be the bazillionth time this has been requested. See https://github.com/opnsense/core/issues/4966 for an example.

**Comment by AdSchellevis** [comment]
https://github.com/opnsense/core/issues/6228#issuecomment-1423363905

**Comment by mimizone** [comment]
> 

I noticed now yes. That's good. Many people seem to need this for the good reason of using 2FA and be more secured.

All issues being closed, it  doesn't show up if you do a default search for issues, thinking the feature is not implemented yet. 
Is that something considered to be added to upcoming features already and/or it is stuck in looking for a contributor?

**Comment by meyergru** [comment]
In and of itself, it is not. However, if you also want to eat your cake (= more security) and still have it (= no less comfortable), then you probably use a password manager that can handle TOTP.

Most of which can handle 3 fields, but not 2 with one being split up, 2FAS being an example.

So the reason would be that more people might actually use TOTP if OpnSense's implementation would be more "normal" in that respect.

**Comment by meyergru** [comment]
Actually, I also do not quite understand @AdSchellevis to close this issue, pointing to another issue, having critized me for hijacking that very other issue with this topic. The other one is about a thirfd input for VPN, not for logging into the Web UI, which this any many other closed issues were about...

**Comment by AdSchellevis** [comment]
probably misread the topic, reopened.

**Comment by mimizone** [comment]
> 

Of course the point is not that a third field brings additional security technically speaking.
It is that without it, it's cumbersome to use when users are used to autofill from their password managers. So the user/admin will revert to not using 2FA, which is less secure.
Password managers could help by automatically concatenating the 2 values (for instance there is a feature request for 1password). But I haven't seen any doing it yet. (I use both 1password for work and Bitwarden for personal).

**Comment by meyergru** [comment]
I found that KeePass2 together with Kee browser plugin cannot do this either, but KeePassXC with its browser plugin actually can via a self-defined variable consisting of the concatenated password and TOTP, For the time being, that is what I use.

**Comment by shaul75** [comment]
> > 
> 
> [mimugmail](https://github.com/mimugmail) Of course the point is not that a third field brings additional security technically speaking. It is that without it, it's cumbersome to use when users are used to autofill from their password managers. So the user/admin will revert to not using 2FA, which is less secure. Password managers could help by automatically concatenating the 2 values (for instance there is a feature request for 1password). But I haven't seen any doing it yet. (I use both 1password for work and Bitwarden for personal).

I doubt password managers would implement that anytime soon, OPNsense is the only one I've seen that doesn't do the so-called "standard" 2FA login.

Is there a reason not to split it to a 3rd field? (the reason for it have obviously been stated already)

**Comment by mimugmail** [comment]
> > > 
> > 
> > 
> > [mimugmail](https://github.com/mimugmail) Of course the point is not that a third field brings additional security technically speaking. It is that without it, it's cumbersome to use when users are used to autofill from their password managers. So the user/admin will revert to not using 2FA, which is less secure. Password managers could help by automatically concatenating the 2 values (for instance there is a feature request for 1password). But I haven't seen any doing it yet. (I use both 1password for work and Bitwarden for personal).
> 
> I doubt password managers would implement that anytime soon, OPNsense is the only one I've seen that doesn't do the so-called "standard" 2FA login.
> 
> Is there a reason not to split it to a 3rd field? (the reason for it have obviously been stated already)

So, FortiGate seems to do it like OPN:
https://www.token2.com/site/page/hardware-tokens-for-two-factor-authentication-with-fortigate?totpradius

With Cisco ASA I also never saw a field in ASDM Manager, and Sophos UTM also doesn't support it.
With Sophos XG there is a captcha field, but I never used OTP there. 

Which Firewalls you have used and to support a separate field for login?

**Comment by fichtner** [comment]
One reason I still doubt separate OTP field, especially on a separate page after login is that user enumeration is easily carried out. Sure if you look at GitHub for example where they do this you have to keep in mind user names are already public. ;)

**Comment by meyergru** [comment]
It should not be on a separate page, as it may be dependent on whether 2FA is needed in case you specify multiple authentication mechanisms. You would leave the 3rd field empty when you use a password-only credential.

**Comment by fichtner** [comment]
Should we tell GitHub then they do it wrong? I'm really unsure here where the baseline is at.

**Comment by meyergru** [comment]
They definitely do it wrong, you are totally correct with the enumeration argument. Although in practice, the "independent factor" criteria is problematic for some use-cases: For PSD2 e.g., you should never give away which of the two factors were wrong when denying access, This get a bit complicated when the second factor can only be selected after the first has been verified. You would need to present fake selections in case the first factor was wrong.

For TOTP, this is no problem and the error message should not give away what exactly went wrong.

**Comment by shaul75** [comment]
> > > [mimugmail](https://github.com/mimugmail) Of course the point is not that a third field brings additional security technically speaking. It is that without it, it's cumbersome to use when users are used to autofill from their password managers. So the user/admin will revert to not using 2FA, which is less secure. Password managers could help by automatically concatenating the 2 values (for instance there is a feature request for 1password). But I haven't seen any doing it yet. (I use both 1password for work and Bitwarden for personal).
> > 
> > 
> > I doubt password managers would implement that anytime soon, OPNsense is the only one I've seen that doesn't do the so-called "standard" 2FA login.
> > Is there a reason not to split it to a 3rd field? (the reason for it have obviously been stated already)
> 
> So, FortiGate seems to do it like OPN: https://www.token2.com/site/page/hardware-tokens-for-two-factor-authentication-with-fortigate?totpradius
> 
> With Cisco ASA I also never saw a field in ASDM Manager, and Sophos UTM also doesn't support it. With Sophos XG there is a captcha field, but I never used OTP there.
> 
> Which Firewalls you have used and to support a separate field for login?

I wasn't referring to any specific firewall, but to 2FA authentications on web login pages, in general. Why should it be different?

**Comment by AnAnalogGuy** [comment]
Help wanted? Well, I offered help like half a year ago with one very simple little question to be answered by the lead of this project. Since i got no reply, i just changed the implementation on my side and did not contribute back. Someone a bit of a waste of time this board....

**Comment by JSuenram** [comment]
+1 from here. We have about 24 opnsense Boxes most of them reachable from the Internet to be remote mangaable. The missing extra field for the TOTP-Code makes our customers man usability problems. They simply forgot that they have to add it to the passoword field. A simple box for the code to be entered, can't be that hard?

**Comment by AnAnalogGuy** [comment]
It's still up to the project owners to tell me, if they would accept a change as i proposed and to provide a bit guideance, since the last thing I'm going to do is to waste my time providing a pull request finding out they don't care about it. Now it's more than a year and not one single reaction from the project and the ticket closed without any reply. Very very professional and repectful.

**Comment by AdSchellevis** [comment]
@AnAnalogGuy 

We responded on this and earlier tickets that it's not a priority, but we will review a clean (non hacky) solution in a PR. In the long run this page likely needs an overhaul to move it out of the legacy scheme. 

Some of the challenges of implementing this cleanly are:

* Determine if a token is requested (depends on the authenticator)
* Handle concatenation order (depends on the settings of the authenticator)
* Prevent breakage in themes as much as possible
* Try to keep the concat action in the browser, no need to send separate items to the backend as the authentication sequence itself doesn't change

To some degree I can understand people don't want to waste their time, but that's not really how this works (remember you are asking time from other people here). 
If there is a proposal to discuss in terms of code (or a step by step plan), it makes it more valuable from our end to spend (waste?) our time as well. 

So, if the question is, "is there room to implement a solution for the ui for this", the answer is yes. When the question is, "are you going to spend a lot of your time to make it happen", the current answer is no. 
A proper implementation this costs quite some time to build and test given the constraints that exists. 

A hacky solution is likely already implementable using a custom theme package by the way when adding a `theme.js` file to overlay the input box.

When reimplementing the legacy page into a new mvc one from our end, it makes sense to take this into account as well, but in the grant scheme of things, this, at the moment, is just not a priority.

**Comment by andrewpedzewick** [comment]
It's really unfortunate when community requests are not addressed. While I understand you may have different priorities, it does come across as inflexible when many users are requesting this feature. The goal of OPNSense is to provide robust security and control over our networks, and TOTP is a critical part of that security for many users.

Password managers are a key aspect of maintaining strong security practices. The current implementation makes it challenging to use TOTP effectively, which could reduce overall security for those relying on password managers. This isn't an issue with password managers but rather the non-traditional implementation of TOTP.

It's concerning that this feedback is being dismissed without consideration of its impact. I urge you to reconsider the prioritization of this feature, as it would greatly enhance security and usability for many users, including myself. Thank you for your attention to this matter

**Comment by fichtner** [comment]
With all due respect we try to steer a project and not all concerns can be addressed by the core team all the time. We’re trying to be realistic and productive (just check our road map). Try to be realistic and productive, too.


Merry Christmas!

**Comment by AnAnalogGuy** [comment]
From an outside perspective, it looks like this is an open source but rather closed dev project. So maybe it's just about different expections from ppl with different experiences from other open source projects.

**Comment by fichtner** [comment]
How about raise a PR and see what happens?

I think straw man arguments coupled with entitlement and subtle attacks towards an open source project are not a dependable strategy and will derail this issue request further.


Merry Christmas 😊

**Comment by Haulien** [comment]
> From an outside perspective, it looks like this is an open source but rather closed dev project. So maybe it's just about different expections from ppl with different experiences from other open source projects.

They seem open to a pull request for a clean solution, submit a PR.

**Comment by melmatsuoka** [comment]
If you're a macOS user that uses 1Password as your password manager, and you also happen to also use Keyboard Maestro, you can use the 1Password CLI tool to auto-concatenate the TOTP code and then auto-fill the password field on the OPNsense login page with a single click. I'm sure there are probably similar workarounds for Windows & Linux as well. But the 1Password CLI tool is a real lifesaver for things like this. 

I made a video walkthrough of how this works here (Github link to the KM macro is in the video description): 

https://www.youtube.com/watch?v=3uF7ZcEXCBY

There's a big thread on the 1Password community forum regarding this issue (it also affects sites like USAA.com). and despite well received suggestions on [how to implement auto-concatenation within 1Password,](https://1password.community/discussion/comment/665852/#Comment_665852) there doesn't seem like there's much interest on the part of 1PW developers to add this as a feature. So it really would be nice if OPNsense would implement a more standard way to enter TOTP codes.

**Comment by smitty-nieto** [comment]
I have added a PR (https://github.com/opnsense/core/pull/8241) which covers this.
Please give it a review.
