### ISSUE TITLE
Unbound is slow when IPv6 is allowed but a connection not present

### ISSUE THREAD

**Issue by dacioromero** [opnsense/core#6311]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

In the default configuration on my router, Unbound can take several seconds to resolve a domain. This seemed abnormal to me when an ARMv7 SBC I have running my DNS previously performed just fine. Turns out `do-ip6: true` was set which Unbound can struggle with when there is no IPv6 connection.

**To Reproduce**

1. Set up a router with a IPv6-less WAN
2. Make sure "Allow IPv6" is enabled under `/system_advanced_firewall.php`
3. Observe long query times with dig, drill, or the details menu under `/ui/unbound/overview`

**Expected behavior**

Unbound should perform normally in the default configuration with IPv6 allowed.

Perhaps `do-ip6` should be set to false if the WAN interface isn't configured for it or have `do-ip6` be a user-configured value specific to Unbound and not the firewall.

**Describe alternatives you considered**

Disallowing IPv6 when it isn't available fixes it.

**Screenshots**

| Before | After |
| -- | -- |
| ![image](https://user-images.githubusercontent.com/12436128/217734119-7c3e6f1a-c238-467f-87e4-d44561120ca8.png) | ![image](https://user-images.githubusercontent.com/12436128/217734280-9050faee-6b27-431a-ba0e-a07f7cf2d0d0.png) |

**Relevant log files**

N/A

**Additional context**

https://bugzilla.redhat.com/show_bug.cgi?id=646536
https://lists.fedoraproject.org/pipermail/scm-commits/2010-October/513340.html
https://web.archive.org/web/20150924100839/https://dnssec.surfnet.nl/?p=464
https://github.com/opnsense/core/issues/2913

**Environment**

OPNsense 23.1_6-amd64
FreeBSD 13.1-RELEASE-p5
OpenSSL 1.1.1s 1 Nov 2022
Intel i226-V

**Comment by fichtner** [comment]
Unless something changed this is why it was done in the way it was... 53024b5c159c7c476 prefer-ip6 is set to no by unbound so I'm not sure why you are seeing this / what you are seeing.

**Comment by fichtner** [comment]
PS: You might want to enable "Prefer IPv4" option under System: Settings: General and see if the issue goes away.

**Comment by dacioromero** [comment]
prefer-ip4 is also set to no by default according to the docs, so I wonder if Unbound will use either. I'm willing to do more testing and/or provide more info if wanted just let me know what you need.

It looks like pfSense folks are having similar issues, going to read over this thread: https://forum.netgate.com/topic/173148/slow-dns-after-22-05
Issue with Unbound someone linked in the thread: https://github.com/NLnetLabs/unbound/issues/670

**Comment by fichtner** [comment]
Franky we don't have a lot of issues with this as far as issues here and forum goes (that cannot be resolved in configuration). It could be an issue introduced by newer Unbound perhaps, but too early to tell. Thanks for looking into this in any case 👍 


Cheers,
Franco
