### ISSUE TITLE
Firewall / Aliases  - Allow to create firewall rules for logged in OpenVPN users 

### ISSUE THREAD

**Issue by AdSchellevis** [opnsense/core#6312]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**

It would be practical to support a pattern in which logged in (open)vpn users are able to have their own set of firewall rules. In which case we are able to allow certain traffic for groups of users

**Describe the solution you like**

As we already do have aliases for all sorts of types, the most logical option is to hook an alias type which is maintained in the firewall/aliases section and collects addresses for groups of openvpn users. 

**Describe alternatives you considered**

Pin the addresses using client specific overwrites, but this involves more maintenance and these are not 100% guaranteed to be applied.

**Additional context**

- https://openvpn.net/community-resources/reference-manual-for-openvpn-2-6/
- https://docs.opnsense.org/manual/vpnet.html#client-specific-overrides

**Comment by rene-bayer** [comment]
Please extend this to IPSEC Users (IKEv2 Mobile VPN)!

**Comment by jerryhze** [comment]
> Please extend this to IPSEC Users (IKEv2 Mobile VPN)!

amen!

**Comment by fichtner** [comment]
Let's try not to rush this ;) It was discussed but we have other priorities at the moment.
