### ISSUE TITLE
High cpu usage of scripts/unbound/logger.py

### ISSUE THREAD

**Issue by Sunsheep** [opnsense/core#6314]
- [x]  I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

*) May be related to [6191](https://github.com/opnsense/core/issues/6191)

### Describe the bug

Hello,

I've now seen this bug on my OPNsense box after upgrading to 23.1_6. The Unbound DNS Reporting is a very neat feature, but on my system it comes with the cost, that the script `/usr/local/opnsense/scripts/unbound/logger.py` (see Outputs) causes an average cpu load of 100% (mostly in range of 60% to 160%).

I've already rebooted the system. This does not help.
I have modified the `logger.py` script with a "timeout" in the main loop (0.1sec delay). This helps party -> cpu load in the range of 40% to 100%. Even with the delay, the statistics are popping up in the gui. 

Average DNS request per 10 minutes: 1000 to 2000.
 
### To Reproduce

Activate Unbound DNS reporting under `Reporting > Settings > Unbound DNS reporting > Statistics`.

### Expected behavior

Do not exhaust the CPU ;-)

### Screenshots / Outputs

I have executed the following command at different times. Average relative CPU load approx. 100% !

```root@fw01:~ # ps -p 15375 -o %cpu,%mem,command
%CPU %MEM COMMAND
63.7  1.8 /usr/local/bin/python3 /usr/local/opnsense/scripts/unbound/logger.py (python3.9)
176.1  1.8 /usr/local/bin/python3 /usr/local/opnsense/scripts/unbound/logger.py (python3.9)
183.8  1.8 /usr/local/bin/python3 /usr/local/opnsense/scripts/unbound/logger.py (python3.9)
164.6  1.8 /usr/local/bin/python3 /usr/local/opnsense/scripts/unbound/logger.py (python3.9)
163.1  1.8 /usr/local/bin/python3 /usr/local/opnsense/scripts/unbound/logger.py (python3.9)
73.4  1.8 /usr/local/bin/python3 /usr/local/opnsense/scripts/unbound/logger.py (python3.9)
```

### Relevant log files

I did not see anything unusual in any logfile during this time. However I am monitoring it and will post here once I can reproduce this again.

### Environment

```
OPNsense 23.1_6-amd64
FreeBSD 13.1-RELEASE-p5
OpenSSL 1.1.1s 1 Nov 2022
```

Thanks!

**Comment by AdSchellevis** [comment]
fixed with https://github.com/opnsense/core/commit/02f44d9024f0c9eb53ae2ade83f9ff522218014c

**Comment by Sunsheep** [comment]
Thanks!
