### ISSUE TITLE
Unable to add multiple IPsec PSK on 23.1

### ISSUE THREAD

**Issue by andrewhotlab** [opnsense/core#6316]
When reconfiguring IPsec site-to-site tunnels after upgraded to the 23.1_6 release, the web interface does not allow to save more than one pre-shared key, complaining that another local identifier already exists (we are using local and remote IP addresses to authenticate):

![2023-02-09_20-15](https://user-images.githubusercontent.com/26433166/217915939-96687376-1b87-41aa-bf6d-c2ae63bb4ac4.jpg)

But we have two tunnels between our public IP address and two different remote gateways, thus the tuple "local identifier / remote identifier" are not the same... it looks like to me as a bug in the checking logic of the web interface, isn't it?

**Comment by AdSchellevis** [comment]
@andrewhotlab https://github.com/opnsense/core/commit/c0a6d22e58d4f16ace73a893b594900f61f39b8c should fix the constraint issue.

**Comment by andrewhotlab** [comment]
Wonderful: now it works as expected.
Thank you so much @AdSchellevis !  If you solve a low-priority bug in 24 minutes, I'm curious to know how much time it takes you to solve a high priority one! :D

Needless to say that I will never thank enough anyone involved in OPNsense development... you are great!

**Comment by AdSchellevis** [comment]
@andrewhotlab you're welcome, thanks for reporting!
