### ISSUE TITLE
CARP issues after upgrade to 23.1

### ISSUE THREAD

**Issue by Skywalker-11** [opnsense/core#6318]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

After upgrade from Opnsense 22.7 to 23.1 the CARP ip network/address and VHID group ids are required to be globally unique when using the gui to create/edit them.

Before 23.1 it was possible to use the same CARP ip on different interfaces (eg. link local ip for services that exist in multiple networks). It was also possible to use the same VHID group id on different interfaces.

The error messages that are displayed when changing/creating a carp ip are these:

Previously created CARP ips that use per interface unique VHID group and ip/network addresses still work as expected but the issue is introduced when editing it.

**To Reproduce**

1. Go to Virtual IPs: Settings
2. Edit existing virtual ip of CARP type or click on plus sign to add new virtual ip and select mode CARP and an interface
3. Enter an ip/network address that does not yet exist for the selected network or enter VHID group id that is not yet assigned for the selected interface
4. Click save
5. Error messages are shown:
- `Address already assigned. ` or
- `VHID 4 is already in use on interface wan. Pick a unique number on this interface.`

**Expected behavior**

The ip/network address and VHID group should only be required to be unique per interface

**Describe alternatives you considered**

The VHID group could be required to be globally unique. But this only works if less then 255 CARP addresses are used on a system in total due to requirements of the 

**Additional context**

Issue is probably introduced by PR #6105 

**Environment**

OPNsense 23.1_6 (amd64, OpenSSL).

**Comment by AdSchellevis** [comment]
Overlapping IP's didn't appear to be allowed earlier either:
https://github.com/opnsense/core/blob/stable/22.7/src/www/firewall_virtual_ip_edit.php#L123

vhid's might be spawned over interfaces, although I'm not sure why one would want to broadcast the same id over multiple interfaces (attaching addresses can be done using aliases). It did seem to be possible earlier indeed

https://github.com/opnsense/core/blob/stable/22.7/src/www/firewall_virtual_ip_edit.php#L151

**Comment by Skywalker-11** [comment]
Previously it checked if the same IP is already assigned to the **same** interface:
https://github.com/opnsense/core/blob/1e28d5b352e3aeb9a4e94720595e5e82bf83503b/src/etc/inc/interfaces.inc#L4180

That vhid are required to be globally unique is only an inconvenience right now as we had an assignment template for CARP ips that provide the same link local service. Eg. for Router Advertisements we use a link local fe80::1 carp ip as source so that the client always use the active firewall as a gateway. Using ip aliases is not an option as we require the failover function of CARP ips for the service that uses it.
Still the restriction to global unique VHIDs could be an issue for larger organizations with more than >255 entries (does currently not apply for my use case). 
Also my understanding was that the carp traffic is only send on the interface that they are actually assigned to.

**Comment by AdSchellevis** [comment]
Well, the intend was not to change behavior, but `is_ipaddr_configured()` seems to return "unused" if the address is not found at all or bound to the requested interface. the vhid check is different indeed.

**Comment by AdSchellevis** [comment]
https://github.com/opnsense/core/commit/9a0bc2e79b30eb51f3b0d2a464b12039fd567c92 should fix the vhid issue, if you do want to discuss about the address further, can you install an older version and test locally first? 

If I'm misreading and there is a valid use-case to support 100% overlaps, I don't mind to discuss further, the code just seems to suggest otherwise.

**Comment by Skywalker-11** [comment]
I seem to have remembered it wrong. The previous behavior was was only working for link-local addresses (which also makes sense).
Here is is the corresponding code that triggered it as it appended an interface scope to the actual ip address: https://github.com/opnsense/core/blob/9ece6788df20e99f39d42b84013688620f0d4ded/src/etc/inc/util.inc#L856

We are currently defining fe80::1/64 as a carp address and use this in the router advertisements daemon as source address. We used to set a static carp address in the interfaces subnet range eg. `2001:a:b:c:d::1/64` but some change in 2021/2022 disabled this option and only allowed link local addresses and `automatic`.

The reason behind this is to prevent a backup opnsense to announce its own ip as default gateway to the clients via the router advertisements. This would result in the reply packet being send via the active master opnsense and then rejected as the master firewall weren't able to associate the traffic with an existing connection.
By using a carp ip for RA the traffic would always go through the currently active opnsense.

**Comment by Skywalker-11** [comment]
> [9a0bc2e](https://github.com/opnsense/core/commit/9a0bc2e79b30eb51f3b0d2a464b12039fd567c92) should fix the vhid issue, if you do want to discuss about the address further, can you install an older version and test locally first?
> 
> If I'm misreading and there is a valid use-case to support 100% overlaps, I don't mind to discuss further, the code just seems to suggest otherwise.

That commit seems to fix the vhid issue

**Comment by fichtner** [comment]
> Here is is the corresponding code that triggered it as it appended an interface scope to the actual ip address

Not sure what is wrong here appending the scope to link-local?

> We used to set a static carp address in the interfaces subnet range eg. 2001:a:b:c:d::1/64

RA always uses link-local, that's why you need a CARP link-local configured for RA to actually make use of it. This has been working for a while and I think a number of people working on this feature would complain loudly if it broke.


Cheers,
Franco
