### ISSUE TITLE
Virtual IPs UI: New VIP form lacks description field for IP Alias, Proxy ARP, and Other; CARP alone shows one.

### ISSUE THREAD

**Issue by cyberpuffin-digital** [opnsense/core#6320]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

When adding a new IP Alias in the Virtual IP UI (/ui/interfaces/vip) the form field for entering a description is not present.  The form field is shown when the Virtual IP mode is set to CARP.

**To Reproduce**

1. Go to Interfaces -> Virtual IPs -> Settings
2. Click the button to add a new virtual IP
3. Cycle through the different Modes to see a Description form field in the CARP mode and no other.

**Expected behavior**

It would be nice to be able to set a description on the Virtual IP regardless of the Mode.

**Describe alternatives you considered**

In this case the IP Alias was saved as a CARP VIP with the target description, then modified to be the expected IP Alias.  The description persisted and now shows in the list of VIPs.

**Screenshots**

![image](https://user-images.githubusercontent.com/91905896/218195117-1557deb7-a9e1-4e5d-9acd-edf23905fda2.png)

![image](https://user-images.githubusercontent.com/91905896/218195144-893a42f9-0f40-416b-9d81-28a1fb8703fd.png)

**Relevant log files**

n/a

**Additional context**

n/a

**Environment**

OPNsense 23.1_6 (amd64, openssl)
FreeBSD 13.1-RELEASE-p5

**Comment by AdSchellevis** [comment]
easy to have missed, but was fixed recently in https://github.com/opnsense/core/pull/6304. should be in the next version

**Comment by cyberpuffin-digital** [comment]
Thanks!  Sorry to have missed it.  I was looking through Issues and neglected to search through the existing PRs.

**Comment by AdSchellevis** [comment]
@cyberpuffin-digital no problem, easy to miss this one :)
