### ISSUE TITLE
`Fatal error` when retreiving large packet captures

### ISSUE THREAD

**Issue by kquinsland** [opnsense/core#6321]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

I use the Diagnostics/packet capture from time to time and - every once in a blue moon - the resulting capture is ... big.

When attempting to download a large packet capture, I hit this URL:

```
https://opnsense-host.tld/api/diagnostics/packet_capture/download/c00cd3fd-8560-4c35-b8a0-cb82c98eab70
```

When - after a few seconds - returns this error:

```
Fatal error: Allowed memory size of 1073741824 bytes exhausted (tried to allocate 2147483648 bytes) in /usr/local/opnsense/mvc/app/controllers/OPNsense/Diagnostics/Api/PacketCaptureController.php on line 159 
```

When setting up the diagnostic packet capture initially for this particular purpose, I didn't know the volume that I'd capture:

```shell
root@opnsense:/tmp/captures # ls -lah
total 4341919
drwxr-x---  2 root  wheel     5B Feb 10 16:41 .
drwxrwxrwt  8 root  wheel    45B Feb 10 19:22 ..
-rw-r-----  1 root  wheel   196B Feb 10 16:17 c00cd3fd-8560-4c35-b8a0-cb82c98eab70.json
-rw-r-----  1 root  wheel   2.1G Feb 10 16:43 c00cd3fd-8560-4c35-b8a0-cb82c98eab70.zip
-rw-r-----  1 root  wheel   2.1G Feb 10 16:41 c00cd3fd-8560-4c35-b8a0-cb82c98eab70_vlan02.pcap
```

**To Reproduce**

1. Use the packet capture functionality to capture more than `1073741824` bytes (just about 1 gig)
2. Stop, then attempt to download the capture
3. See error

**Expected behavior**

Ideally, the file would just download regardless of the size. I'm not sure of what the implications are for switching away from `readfile()` directly,[ but it does seem like there are alternative ways to stream large files over HTTP w/o consuming all the memory](https://stackoverflow.com/questions/31277672/allowed-memory-exhausted-when-using-readfile).

**Describe alternatives you considered**

Short of a refactor ^, is it is possible to detect that the file size is too large, present a warning telling the user to `scp` the capture to their local machine or let the http server handle the file directly?

**Screenshots**

N/A

**Relevant log files**

N/A

**Additional context**

N/A

**Environment**

Software version used and hardware type if relevant, e.g.:

```
OPNsense 23.1_6-amd64FreeBSD 13.1-RELEASE-p5OpenSSL 1.1.1s  1 Nov 2022
```

**Comment by AdSchellevis** [comment]
At the moment files that don't fit php's memory allocation won't fit indeed, there are options to improve this, but it unfortunately takes time. I'll put it on my list, but can't promise anything just yet.

**Comment by kquinsland** [comment]
> At the moment files that don't fit php's memory allocation won't fit indeed, there are options to improve this, but it unfortunately takes time. I'll put it on my list, but can't promise anything just yet.

No worries / I understand. I use the packet capture function often, but I think this is the first capture over 500 MB that i've had ... in at least a year or two.  This is for sure an edge case and there is a easy workaround: `scp`.

**Comment by AdSchellevis** [comment]
@kquinsland https://github.com/opnsense/core/commit/651edfe7c49dae231cc5d2fde198783066ddf3e7 should fix the problem `readfile()` shouldn't need a lot of memory, but output buffering is likely enabled at this point.
