### ISSUE TITLE
Issues with generation of swanctl.conf from new 'Connections' tab of IPsec

### ISSUE THREAD

**Issue by DennisBankmann** [opnsense/core#6324]
Hi,

on OPNsense 23.1_6-amd64, there is an issue with the new connections defined in the 'Connections' tab.

In the generated swanctl.conf, the reference to the pool generated under the 'connections' entry uses the 'name' of the pool that was entered in the UI. The description of the pool under 'pools' however uses a type of UUID. For this reason, the pool does not get associated with the connection and this IPsec connection does not work. 
See relevant parts of generated swanctl.conf below.

connections {
    ad158821-fb44-457a-bd27-7c837c8f797d {
        proposals = default
        unique = no
        aggressive = no
        version = 2
        mobike = yes
        local_addrs = [REDACTED]
        encap = no
        **pools = Roadwarriors**
        ...
}
pools {
    **ee5ef34a-da67-4407-b01d-169afe329c5c** {
        addrs = 10.56.2.0/24
    }
}

Many thanks for looking into this.

**Comment by AdSchellevis** [comment]
https://github.com/opnsense/core/commit/9d5e1edb9580432c2f650cae66bab55e533d2a3d should fix it, missed a mapping it seems.
