### ISSUE TITLE
IPsec: Creating mobile address pools in new UI can lead to syntax error in swanctl.conf

### ISSUE THREAD

**Issue by somova** [opnsense/core#6328]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

Using white space characters in the name of IPsec address pools ("VPN -> IPsec -> Connections [new] -> Pools") lead to syntax error in swanctl.conf. Maybe some other characters are also not allowed. Enclosing the name in quotation marks also lead to misconfigured IPsec connections.

This bug is related to #6324. 

**To Reproduce**

1. Update to Opnsense 23.1.1
2. Click on 'VPN -> IPsec -> Connections [new] -> Pools'
3. Create a new pool with a white space character in its name
4. Assign pool to a Roadwarrior IPsec connection profile

**Expected behavior**

Strongswan correctly parses IPsec connections from swanctl. conf and successfully starts. 

**Describe alternatives you considered**

I prefer to use a UUID in swanctl.conf to link address pools to IPsec connections

**Relevant log files**

From CLI:

> **root@opnsense-host:/usr/local/etc/swanctl #** swanctl --list-conns 
> no files found matching '/usr/local/etc/strongswan.opnsense.d/*.conf'
> **root@opnsense-host:/usr/local/etc/swanctl #** swanctl --load-conns
> no files found matching '/usr/local/etc/strongswan.opnsense.d/*.conf'
> /usr/local/etc/swanctl/swanctl.conf:182: syntax error, unexpected NAME, expecting : or '{' or '='
> invalid config file '/usr/local/etc/swanctl/swanctl.conf'
> no connections found, 0 unloaded
> **root@opnsense-host:/usr/local/etc/swanctl #**

**Environment**

OPNsense 23.1.1 (amd64, OpenSSL).

**Comment by AdSchellevis** [comment]
At the moment I tend to add a validation on the field, uuid's for the pools where considered, but also need changes in the diagnostics area and has the disadvantage of not being able to read swanctl's output easily.

**Comment by somova** [comment]
That's also a good solution.

BTW: The new IPsec WebUI interface is awesome. Thanks :1st_place_medal:

**Comment by AdSchellevis** [comment]
@somova thanks! I've added a basic validation in https://github.com/opnsense/core/commit/24111268124567ad28730dcf18d4af35ca866c28

**Comment by somova** [comment]
I've installed the patch. It successfully prevents the use of illegal characters like white spaces, brackets etc.
Thanks.

**Comment by AdSchellevis** [comment]
@somova thank for reporting back, much appreciated!
