### ISSUE TITLE
categories and filters in System: Access: Users

### ISSUE THREAD

**Issue by jpVm5jYYRE1VIKL** [opnsense/core#6329]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [* ] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [ *] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**

In case if OPNSense used as VPN gateway with quite a lot of different type of users it is quite hard to add them manually one by one and also quite hard to search and overview in System: Access: Users . Because not possible to do filtering.

**Describe the solution you like**

1) It will be good to make possible to add some kind of categories for **System: Access: Users** . and possibility to choose Category like it is done at **Firewall: Aliases**
2) It will be good have possibility to do clone of user or add bundle of users or at least possibility to do massive import from csv.
3) It will be good to have possibility to do mass edition of users . For example choose multiply users and assign to another group or category

**Describe alternatives you considered**

Not have in my mind

**Additional context**

Not needed

**Comment by fichtner** [comment]
User categories are called groups. And until MVC/API conversion is carried out the GUI will not change with regard to filtering.


Cheers,
Franco
