### ISSUE TITLE
Bug: configd action failed

### ISSUE THREAD

**Issue by fabianfrz** [opnsense/core#633]
configd.py: [f50e0018-dd65-4b75-9951-fe4f3acf18b1] Script action failed at Traceback (most recent call last): File "/usr/local/opnsense/service/modules/processhandler.py", line 462, in execute stdout=output_stream, stderr=error_stream) File "/usr/local/lib/python2.7/subprocess.py", line 540, in check_call raise CalledProcessError(retcode, cmd) CalledProcessError: Command '/usr/local/opnsense/scripts/suricata/listClasstypes.py' returned non-zero exit status 1

Version: Stable 15.7.23

**Comment by AdSchellevis** [comment]
can you try to run this on the console?
```
/usr/local/opnsense/scripts/suricata/listClasstypes.py
````
If your issue is reproducible, this should provide you with some additional feedback.

**Comment by fabianfrz** [comment]
it outputs a valid JSON object.

**Comment by AdSchellevis** [comment]
then it's probably a race condition somewhere, unless "configctl ids list classtypes" is always failing, which I don't expect.

**Comment by fabianfrz** [comment]
this usually happens when i click the download and update rules button.
When i reload the page it works.

**Comment by AdSchellevis** [comment]
ok, then I know what to do, the RuleCache create probably fails when 2 processes execute it at once.

**Comment by fabianfrz** [comment]
``` 
configctl ids list classtypes
```
works on the shell
