### ISSUE TITLE
23.1.1 - Captive Portal unfunctional

### ISSUE THREAD

**Issue by AndyX90** [opnsense/core#6332]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

Captive Portal does not work anymore.

It was working on 23.1_6.

Most likely it has to do with the LightHTTPD update 1.4.68.
Their [changelog](https://www.lighttpd.net/2023/1/3/1.4.68/) says there are deprecated modules (mod_evasive) which are used in https://github.com/opnsense/core/blob/24111268124567ad28730dcf18d4af35ca866c28/src/opnsense/service/templates/OPNsense/Captiveportal/lighttpd-zone.conf#L47.

**To Reproduce**

Upgrade to 23.1.1

**Expected behavior**

**Describe alternatives you considered**

A clear and concise description of any alternative solutions or workaround you considered.

**Screenshots**

**Relevant log files**

If applicable, information from log files supporting your claim.

**Additional context**

Replacement: https://wiki.lighttpd.net/ModMagnetExamples#lua-mod_evasive

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 23.1.1 (amd64, OpenSSL).
KVM
virtio network

**Comment by fichtner** [comment]
Thanks for the report! For now:

    # opnsense-revert -r 23.1 lighttpd

**Comment by AdSchellevis** [comment]
I think we can safely remove mod_evasive and it's usage from the file and point people to rate limiting using firewall rules, which is more flexible and needs less glue than trying to rewrite this to lua (https://redmine.lighttpd.net/projects/lighttpd/wiki/ModMagnetExamples#lua-mod_evasive).

**Comment by AdSchellevis** [comment]
if this https://github.com/opnsense/core/commit/8cb5ec0e38c7d1723387f541275bba3f768bd9cb is an acceptable fix, we can close the issue probably.
