### ISSUE TITLE
Allow adding custom input to configuration of Monit daemon

### ISSUE THREAD

**Issue by codiflow** [opnsense/core#6337]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**

The configuration regarding the Monit daemon using the OPNsense GUI is very limited. So one can't use / configure all features of the daemon.

**Describe the solution you like**

Instead of adding input and all the other additional stuff for every single feature it would be more sustainable to have a **text area** where you can add a **custom monit configuration** which automatically gets added to the **end** of the configuration file (and therefore overwrites / extends all the other options).

**Describe alternatives you considered**

As the configuration file gets overwritten with every configuration change it is not sufficient to add the changes manually to `/usr/local/etc/monitrc`. So currently adding custom stuff  to the Monit daemon in a sustainable way is not possible at all.

**Additional context**

An example use case would be to be able to increase the limits of the Monit daemon with this feature:

```
## Set limits for various tests. The following example shows the default values:
##
set limits {
     programOutput:     5120 B,      # check program's output truncate limit
#     sendExpectBuffer:  256 B,      # limit for send/expect protocol test
     fileContentBuffer: 5120 B,      # limit for file content test
#     httpContentBuffer: 1 MB,       # limit for HTTP content test
#     networkTimeout:    5 seconds   # timeout for network I/O
#     programTimeout:    300 seconds # timeout for check program
#     stopTimeout:       30 seconds  # timeout for service stop
     startTimeout:      120 seconds  # timeout for service start
#     restartTimeout:    30 seconds  # timeout for service restart
}
```

A missconfiguration in this field would not need additional checking as you can already "misconfigure" Monit with the service checks and the changes will not be applied then. The log will show whats wrong and the issue can easily be solved.

**Comment by AdSchellevis** [comment]
If monit support import hooks, that might be an option. Unvalidated user input is not going to happen as explained in https://docs.opnsense.org/development/guidelines/basics.html#safeguard-user-input

**Comment by codiflow** [comment]
Oh thats an interesting point thanks for that background information.

Of course monit supports those file hooks (I hope I understood that right):
https://mmonit.com/monit/documentation/monit.html#INCLUDE-FILES

So if you could add a multiple input field where one can add file paths which should be included (or just a single one – depends) this would absolutely be sufficient.

**Comment by AdSchellevis** [comment]
tagging this help-wanted, low priority for us at the moment and needs an update in our documentation as well to avoid future confusion.

**Comment by codiflow** [comment]
Can I provide and help with this feature?

**Comment by AdSchellevis** [comment]
you certainly can, just open a pull request for a conditional include preferably together with another PR in https://github.com/opnsense/docs (for the documentation part in https://github.com/opnsense/docs/blob/master/source/manual/monit.rst)

**Comment by codiflow** [comment]
OK great – will get into it 😎

Just for clarification: You talked about "avoiding future confusion" regaring the docs. What exactly did you mean with that?

**Comment by AdSchellevis** [comment]
If there is a directory or file included automatically, we should explain that to others to avoid someone else coming in next year seeking for the same :) (for example see https://docs.opnsense.org/manual/unbound.html#advanced-configurations )

Should be an easy fix 😎

**Comment by codiflow** [comment]
Ah ok so just the normal purpose of documentation. Got it 👍

**Comment by codiflow** [comment]
So the documentation part is already prepared.

Could you pls help me with a design decision?

## Solution 1
We add the **automatic** include command to `https://github.com/opnsense/core/blob/master/src/opnsense/service/templates/OPNsense/Monit/monitrc` at the end and it is always active.

Downside: The path needs to exist with a dummy file otherwise the Monit check will log a Warning (`Include failed -- No such file or directory '/usr/local/etc/monit.conf.d/*.conf'`) which is ugly.
So the dummy structure could look like this:

```
monit.conf.d/
  00-example.conf
```

With content like `# This is a placeholder file. You can add your custom and advanced monit configuration here.`

I don't know if we can provide this dummy structure easily (also regarding upgrade szenarios of older installations)

## Solution 2
We add a **checkbox** to the GUI which activates this feature. So the line in the configuration builder file will only be included if the user manually checked the box. If the path does not exist after activation the log would not be misleading because the option has been activated manually and the admin hopefully knows what he does / has to do then.

Downside: I don't know which files need to be adapted that this GUI flag is respected in the config too. So before I dig deeper into it we maybe agree on the general path :-)

**Comment by fichtner** [comment]
Solution 1 is preferable.

**Comment by codiflow** [comment]
OK great, PR incoming.

What about the dummy folder structure? How can I provide this in a PR and can you make sure it also updates existing installations?

**Comment by fichtner** [comment]
You create the dummy.conf file in the correct directory with your PR and this will be created at package install time
