### ISSUE TITLE
Bug: empty IPsec status overview

### ISSUE THREAD

**Issue by 8191** [opnsense/core#634]
I'm afraid that's a bug in vici and not in OPNsense itself:

The IPsec: Status Overview is empty, even there are several tunnels established (`ipsec status` shows several SAs). The error can be traced down to `/usr/local/opnsense/scripts/ipsec/list_status.py` not executing successfully:

```python-traceback
# /usr/local/opnsense/scripts/ipsec/list_status.py
Traceback (most recent call last):
  File "/usr/local/opnsense/scripts/ipsec/list_status.py", line 73, in <module>
    for sas in s.list_sas():
  File "/usr/local/opnsense/scripts/ipsec/vici/session.py", line 334, in streamed_request
    self._register_unregister(event_stream_type, False);
  File "/usr/local/opnsense/scripts/ipsec/vici/session.py", line 250, in _register_unregister
    confirm=Packet.EVENT_CONFIRM,
vici.exception.SessionException: Unexpected response type 53, expected '5' (EVENT_CONFIRM)
```

The response type is different after each execution. Even a very simplified vici call leads to the same exception, why I assume the bug lies somewhere in vici (or even strongSwan?):

```python-traceback
>>> import vici
>>> s = vici.Session()
>>> sas = s.list_sas()
>>> sas.next()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "vici/session.py", line 334, in streamed_request
    self._register_unregister(event_stream_type, False);
  File "vici/session.py", line 250, in _register_unregister
    confirm=Packet.EVENT_CONFIRM,
vici.exception.SessionException: Unexpected response type 46, expected '5' (EVENT_CONFIRM)
```

**Comment by fichtner** [comment]
Probably this? That wasn't pushed to FreeBSD ports... https://github.com/pfsense/FreeBSD-ports/commit/a7cec01e2171a8760c6183cba43e9ee99af09547

**Comment by 8191** [comment]
Cannot really confirm this... The [strongSwan issue](https://wiki.strongswan.org/issues/1185) does not really reveal much how the deadlock exposes to the user. Any indication why you assume the deadlock might be related to that problem?

Without looking too deep into the strongSwan code, wouldn't the error also show up when using `ipsec status`, if the referred deadlock was the issue?

**Comment by fichtner** [comment]
Similarities between *sense, timing and vici scope match and complexity not unlike your test setup: "I’m able to induce a deadlock condition in the charon daemon’s vici implementation with good repeatability using an eight-host full mesh test" vs. several tunnels.

**Comment by fichtner** [comment]
The deadlock may yield an error or timeout resulting in no data to be gathered. Check your system log for configd errors or timeouts?

**Comment by 8191** [comment]
Just found these errors in my ipsec logs while error was present; might be related?

```

Jan 13 13:50:59	charon: 10[CFG] vici connection 6 unknown
Jan 13 13:50:59	charon: 10[CFG] vici connection 6 unknown
Jan 13 13:50:59	charon: 07[CFG] vici write error: Broken pipe
Jan 13 13:50:59	charon: 10[KNL] unable to query SAD entry with SPI c74cb422: No such file or directory (2)
Jan 13 13:50:59	charon: 10[KNL] unable to query SAD entry with SPI c7104cdf: No such file or directory (2)
Jan 13 13:50:59	charon: 10[KNL] unable to query SAD entry with SPI c9874632: No such file or directory (2)
Jan 13 13:50:59	charon: 10[KNL] unable to query SAD entry with SPI ce4aff68: No such file or directory (2)
Jan 13 13:50:59	charon: 10[KNL] unable to query SAD entry with SPI cd6da6a8: No such file or directory (2)
Jan 13 13:50:59	charon: 10[KNL] unable to query SAD entry with SPI ccb4ab5d: No such file or directory (2)
Jan 13 13:50:59	charon: 10[KNL] unable to query SAD entry with SPI c3324b8c: No such file or directory (2)
Jan 13 13:50:59	charon: 10[KNL] unable to query SAD entry with SPI c9199e22: No such file or directory (2)
Jan 13 13:50:59	charon: 10[KNL] unable to query SAD entry with SPI c6fcbc3b: No such file or directory (2)
```

**Comment by fichtner** [comment]
There is a new patch available on a branch in the upstream repo... https://git.strongswan.org/?p=strongswan.git;a=shortlog;h=refs/heads/1185-vici-action-unlock

**Comment by andreasvel** [comment]
Its still there...
I got it in
OPNsense 16.1.4-amd64
FreeBSD 10.2-RELEASE-p12
OpenSSL 1.0.2f 28 Jan 2016

nothing special in my IPSEC log.

**Comment by fichtner** [comment]
Yes, there has been no strongswan release yet.

**Comment by jschellevis** [comment]
It seems the patch mentioned by Franco was just merged, so next release of Strongswan should fix it.

**Comment by fichtner** [comment]
16.1.9 will ship the new StrongSwan 5.4.0 with said patches... ports commit here:  https://github.com/opnsense/ports/commit/63de190349d36f90ac52248dfea5b1bbea04d8a7
