### ISSUE TITLE
`Disable Host Route` has no effect in 23.x

### ISSUE THREAD

**Issue by haarp** [opnsense/core#6342]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**
Hello,

since #6002 is completed, I wanted to check it out on OPNsense 23.1.1_2. For each of my gateways, I enabled `Disable Host Route` and pressed Apply.

Problem 1: I can still see the static routers to the monitor IPs in  System -> Routes -> Status. So that didn't work. If I manually delete the static route, monitoring breaks.

Problem 2: When trying to add the same monitor IP to a second gateway, I get the old `The monitor IP address foo is already in use. You must choose a different monitor IP.` (For testing, I commented that check in `system_gateways_edit.php` -> Monitoring breaks completely for the gateways sharing a monitor IP.)

So this option is still somewhat broken, it seems. Or am I misunderstanding what it's supposed to do?

Thanks a lot!

**To Reproduce**

1. Enable `Disable Host Route` for gateways
2. Observe problems described above

**Expected behavior**

No static routes, monitoring IPs may be re-used

**Describe alternatives you considered**

Not using that option? :D

**Screenshots**

--

**Relevant log files**

--

**Additional context**

See #6002

**Environment**

OPNsense 23.1.1_2-amd64

**Comment by haarp** [comment]
Ok, upon further experimentation:

a) Enabling `Disable Host Route` for a gw and pressing `Apply changes` will **not** remove a previously created static route -> Bug?
b) Disabling `Disable Host Route` and pressing Apply will recreate the rule as expected
c) A static route is still necessary for gw monitoring to work. This makes the Disable Host Route` a bit pointless IMO

**Comment by fichtner** [comment]
Let's slow down a bit... first of all "disable host route" is a user request introduced in 23.1 and I don't expect it to be perfect. In fact the host routes are pretty fragile considering that they have been known to break setups in subtle and not so subtle ways jus recently. We do not have any way of tracking existing host routes so they are unhandled when not required. Thus, a reboot is required to remove host routes reliably from the system.

They do certainly work, but are a fringe and poorly designed feature at the moment spreading over 5 or more individual system components competing for a single host route...

Perhaps the validation can be related in reusing the gateway, but it's a bit more complex than not checking it. It obviously still can't be used somewhere else requesting a host route also.


Cheers,
Franco

**Comment by haarp** [comment]
Yeah, I actually started #6002 after hearing about it being in pfSense :)

It doesn't have to be perfect. At this point I'm mostly wondering how it works. I thought the `Disable Host Route` option would:

a) Allow using a monitoring IP without a static route to it
b) Allow the monitoring IP to be re-used across several gateways

Is this incorrect?

**Comment by fichtner** [comment]
a) yes
b) it depends

;)
