### ISSUE TITLE
Prefix Delegation broken after update

### ISSUE THREAD

**Issue by Crazyachmed** [opnsense/core#6347]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

WAN-Interface is PPPoE dual-stack. IPv4 is negotiated via PPP, IPv6 via DHCPv6 with "Request only an IPv6 prefix" and "Use IPv4 connectivity". The WAN-Interface is assigend a /64 global address and a /56 prefix for delegation.

After upgrade from 23.1_6 to 23.1.1_2 there is no delegated prefix anymore. Fixed by roll back to VM snapshot for now.

Unfortunatly I did not find the logs for DHCPv6 on the WAN interface. Also I don't see something obvious in the changelog.

**Comment by Crazyachmed** [comment]
Seems to be fixed with newest update. Thanks :)

**Comment by fichtner** [comment]
23.1.2 most likely. Thanks for the feedback.
