### ISSUE TITLE
captive portal: MAC filter goes out of sync without service restart

### ISSUE THREAD

**Issue by fichtner** [opnsense/core#635]
via: https://forum.opnsense.org/index.php?topic=1970.0

**Comment by AdSchellevis** [comment]
@fichtner Do you have some additional information about the issue for me?

**Comment by fichtner** [comment]
I think that when the MACs are mapped to IP addresses they won't be refreshed. When then MACs get assigned new IP addresses the wrong hosts are enforced, because the CP still thinks it blocks the correct clients.

**Comment by AdSchellevis** [comment]
There will be some lag, but as far as I know I tested switching ip addresses of static mac addresses. I really need more information here. Does it always fail for example (simply test switching the ip address of a connected client and start pinging).

**Comment by fichtner** [comment]
Ok, closing :)
