### ISSUE TITLE
OPNsense 23.1.1_2  : multible IPSEC Road Warrior connections behind same NAT don't work

### ISSUE THREAD

**Issue by brunotl** [opnsense/core#6352]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

when 2 or more client open vpn from same local network, only the last opened work.

it's exactly the same as describe in issue #4757  

**To Reproduce**
`/usr/local/etc/swanctl/swanctl.conf`
```
# This file is automatically generated. Do not edit
connections {
    con1 {
        unique = never
        aggressive = no
        version = 2
        mobike = yes
        local_addrs = xx.xx.xxx.xxx
        local-0 {
            id = fqdn:xxxx.yyyyyy.zz
            auth = pubkey
            certs = cert-1.crt
        }
        remote-0 {
            id = %any
            auth = eap-radius
            eap_id = %any
        }
        remote_addrs = %any
        encap = no
        pools = defaultv4
        send_certreq = no
        send_cert = always
        proposals = aes256-sha256-modp2048,aes256-sha256-modp1024,aes256-sha1-modp2048,aes256-sha1-modp1024
        children {
            con1-000 {
                start_action = none
                policies = yes
                mode = tunnel
                sha256_96 = no
                local_ts = 192.168.0.0/16
                remote_ts =
                reqid = 1
                esp_proposals = aes256-sha1,aes256-sha256
                life_time = 3600 s
            }
        }
    }
}
pools {
    defaultv4 {
        addrs = 10.10.1.0/24
    }
}
secrets {
}
# Include config snippets
include conf.d/*.conf
```

**Expected behavior**

Should work 

**Describe alternatives you considered**

no workarround found

**Environment**

OPNsense 23.1.1_2-amd64
FreeBSD 13.1-RELEASE-p6
OpenSSL 1.1.1t 7 Feb 2023

Intel(R) Celeron(R) N5105 @ 2.00GHz (4 cores, 4 threads)

**Comment by AdSchellevis** [comment]
@brunotl can you check if "tunnel isolation" is enabled on phase1? looking at the code, I would expect https://github.com/opnsense/core/commit/9be878390a762f8d23c09789ef34696f53b0ab3e prevents `reqid` from appearing in the child section.

**Comment by brunotl** [comment]
yes, "tunnel isolation" was checked, if unchecked and with the https://github.com/opnsense/core/commit/9be878390a762f8d23c09789ef34696f53b0ab3e change, issues look solved !

**Comment by AdSchellevis** [comment]
ok, we can add the same fix to the "tunnel isolation mode" as it will generate the same config. @brunotl thans for reporting back.

**Comment by AdSchellevis** [comment]
@brunotl certainly not, but that would be the first major release with the fix. Minors do contain feature additions and bug fixes as well, I won't be surprised if @fichtner pushes this to 23.1.2 to be honest.

**Comment by brunotl** [comment]
Perfect, thanks.

**Comment by fichtner** [comment]
Backport was added for 23.1.2 half an hour ago or so.
