### ISSUE TITLE
Upgrade to 23.1 with NIC tunables

### ISSUE THREAD

**Issue by smithj33** [opnsense/core#6353]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x ] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x ] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

When upgrading from 22.7 to 23.1, I had tunables set for an I350 NIC on all 4 ports. With these in place, the ports do not initialize properly upon reboot after upgrade. After reverting the system to 22.7 and removing the tunables, the system upgraded without issue. I was able to add the flow control tunables back after upgrade, but adding the eee_control back and hitting apply will lock up the interface and ports will not initialize properly upon a reboot. I can log in directly to the box locally and use ifconfig to bring the ports down and up and they work until reboot. It's possible flow control did not need to be removed before upgrade, but I did not have time to test as it is a production system.

dev.igb.0.fc = 0
dev.igb.0.eee_control = 0

**To Reproduce**

Ensure the tunables above are added via the GUI and system is working normally on 22.7
Use the GUI to upgrade from 22.7 to 23.1
Upon reboot you will not have access to any network functionality

**Expected behavior**

The tunables above worked without issue in 22.7 and it would be expected that you could complete an upgrade to 23.1 without having to first remove those tunables. Until resolved, a warning should be added to the upgrade dialog or tunables should be removed by the upgrade process.

**Describe alternatives you considered**

Not using tunables

**Screenshots**

N/A

**Relevant log files**

N/A

**Additional context**

N/A

**Environment**

OPNsense 22.7.11 (amd64, OpenSSL).
Dell Wyse 5070 Extended - Intel J5005
Network Intel® I350 x4

**Comment by fichtner** [comment]
This is mainly a driver issue. Not using the tunables is recommended.

**Comment by fichtner** [comment]
You can still set them manually from /boot/loader.conf.local if you really need to.
