### ISSUE TITLE
IPsec/VTI - apply routes after [re]configuration

### ISSUE THREAD

**Issue by AdSchellevis** [opnsense/core#6354]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

In some cases the routes disappear when [re]configuring ipsec vti tunnels, for example when changing the tunnel endpoints. 

**To Reproduce**

Most easy scenario is probably to edit a tunnel, changing the endpoints and put the old ones back with an apply in between, but any change triggering an edit on `if_ipsec` would probably signal a removal of existing routes.

**Expected behavior**

It's probably better to force routes back at any time to prevent having to go back to routes or gateways. 

**Describe alternatives you considered**

none

**Comment by fichtner** [comment]
This might be related to #5263

**Comment by fichtner** [comment]
Back to the feature ;)
