### ISSUE TITLE
Alias name check logic broken in 23.1.1

### ISSUE THREAD

**Issue by andrewhotlab** [opnsense/core#6368]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

Editing or adding such a string, which is within the requirements, in the "name" field of an alias makes the GUI return this error in version 23.1.1:

![2023-03-01_16-03](https://user-images.githubusercontent.com/26433166/222181366-76eec64d-8a5d-4edb-8045-782d15b8fbae.jpg)

Previously versions (surely before 23.1) does not have this problem.

I suppose the problem lies in this line:
https://github.com/opnsense/core/blob/bc1a8778ab2140e46175ecf2546b634f87087f07/src/opnsense/mvc/app/models/OPNsense/Firewall/FieldTypes/AliasNameField.php#L88

Thanks!

**Comment by fichtner** [comment]
https://twitter.com/opnsense/status/1628843345626779655

**Comment by andrewhotlab** [comment]
Thanks. In fact I realized a few minutes ago that the issue has been already solved with commit 05b48c151547 ! :)
