### ISSUE TITLE
IPsec 23.1 in HA setup doesn't synchronizes Connections[new] entries

### ISSUE THREAD

**Issue by at0msense** [opnsense/core#6369]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

After upgrade a HA setup to 23.1 the synchronization of the IPsec configuration to the other HA host doesn't work for tunnels 
created with the Connections[new] interface. The swanctl.conf contains only the migrated tunnels.

**Comment by at0msense** [comment]
I applied the patch on both sides and then started the sync. 
The data for the "new" tunnels are then not yet there. Do I still have to do something ?

**Comment by at0msense** [comment]
maybe this helps

root@osgw1:/var/log/configd # cat latest.log | grep swa
<15>1 2023-03-01T18:26:13+01:00 host.example.com configd.py 261 - [meta sequenceId="70"]  * generated //usr/local/etc/swanctl/reqid_events.conf

**Comment by AdSchellevis** [comment]
I would expect it would just send the config to the other end when properly applies, it does so on my end at least.

**Comment by at0msense** [comment]
It doesn't work for me. Shouldn't there be an entry for OPNsense.Swanctl in the logfile ?

**Comment by AdSchellevis** [comment]
maybe wait for a next release on our end (I did validate the sync and checked history on the backup), this is costing too much community support time.
