### ISSUE TITLE
DHCPv6 prefix delegation not probed on boot

### ISSUE THREAD

**Issue by fichtner** [opnsense/core#637]
After a reboot it doesn't ask the providers DHCPv6 server for a prefix delegation, therefore my provider (Init7) doesn't route my static IPv6 /48 range to my box. Manually invoking

    # /var/etc/rtsold_[...].sh

fixes this until next reboot.

The issue https://github.com/opnsense/core/issues/47 and post https://forum.opnsense.org/index.php?topic=1533.0 seem related.

via: https://forum.opnsense.org/index.php?topic=1950.0

**Comment by fichtner** [comment]
interafce_dhcpv6_configure() isn't called as often as its IPv4 sibling. E.g. rc.linkup does not call newipv6 even though it checks for IPv6 a few lines earlier: https://github.com/opnsense/core/blob/master/src/etc/rc.linkup#L63 and interface_configure() doesn't call it either... https://github.com/opnsense/core/blob/master/src/etc/rc.linkup#L77

**Comment by fichtner** [comment]
timeout

**Comment by fichtner** [comment]
People have suggested that this may be due to an utter lack of RAs in their network.

**Comment by fichtner** [comment]
There seems to be a very similar issue here: https://redmine.pfsense.org/issues/5993

I've added an option that does what you initially suggested: direct run the dhcp6 client.

**Comment by fichtner** [comment]
I think we figured this out, all code in 16.7. Fixing bugs inline if needed. Thanks everyone!

**Comment by onitake** [comment]
Please reopen this bug, I'm running OPNsense 16.7.2 and I have exactly the same problem as described.

Your workaround (running /var/etc/rtsold_[...].sh directly) fixes it temporarily, but it's not possible to get persistent IPv6 PD.

I even tried to replicate the (working) configuration I had back in pfSense, but to no avail. No DHCPv6 client is started and no DHCPv6 packets are sent.

**Comment by fichtner** [comment]
@onitake have you tried the "Directly send SOLICIT" option in your WAN configuration?

**Comment by onitake** [comment]
Hmm. Interesting. This works. I was sure I tried this before though?
Looks like it just took some time to get that lease.
dhcp6c is being started now, and it propagates the configured prefix to the LAN.

Ok. That part is sorted out. Next up, I'm not getting any return traffic for the delegated network. I can see the packets being sent out through the WAN, but there is nothing in response. Doesn't seem like it's a firewall problem, and it's almost definitely not the ISPs fault, as I had IPv6 working before.

**Comment by fichtner** [comment]
@onitake so far so good :)

Can you open a new ticket? It's better to start fresh with some more info: When / how was it working, which versions specifically and whether or not there is any indication in the firewall logs for dropped traffic or packet captures on WAN (don't have to share, only look into for return traffic).

**Comment by onitake** [comment]
I can, however, the initial symptoms pointed to the same bug as described here. (and thus, the fix not doing what it should)
I'm still a bit suspicious if what I'm seeing now is not a stale lease that was stored and reused. That would explain the lack of incoming traffic. I will investigate further and open a new issue once I've collected some data.
