### ISSUE TITLE
IPsec 23.1 rekey_time always 14400s

### ISSUE THREAD

**Issue by at0msense** [opnsense/core#6370]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

All tunnels automatically migrated by the upgrade to 23.1 have a lifetime of 14400 instead of the configured one. 
Only the newly created tunnels with "Connections [new]" have the specified lifetime.

**Comment by AdSchellevis** [comment]
The question is, which lifetime are we talking about and is this different than proposed in the upstream migration guide (https://wiki.strongswan.org/projects/strongswan/wiki/Fromipsecconf).

**Comment by at0msense** [comment]
I've the text precise to phase 1 lifetime.

**Comment by AdSchellevis** [comment]
phase 1 lifetime was`ikelifetime` in our legacy code 

https://github.com/opnsense/core/blob/3bd5b046232def1530ebb2bfc94de9a72ebd3e9e/src/etc/inc/plugins.inc.d/ipsec.inc#L1430

Which should be translated according to https://wiki.strongswan.org/projects/strongswan/wiki/Fromipsecconf

**Comment by at0msense** [comment]
I just see that it is probably because the rekey_lifetime parameter is not set in swanctl.conf, but is correct in the GUI.

**Comment by at0msense** [comment]
swanctl --list-conns | grep reke | grep IKE

e73c3b2e-55e1-484e-8e9d-e76ee35d6f3a: IKEv2, no reauthentication, rekeying every 86400s
con1: IKEv2, no reauthentication, rekeying every 14400s, dpd delay 10s
con4: IKEv2, no reauthentication, rekeying every 14400s, dpd delay 10s
con5: IKEv2, no reauthentication, rekeying every 14400s, dpd delay 10s
con6: IKEv2, no reauthentication, rekeying every 14400s, dpd delay 10s
con8: IKEv2, no reauthentication, rekeying every 14400s, dpd delay 10s
con3: IKEv2, no reauthentication, rekeying every 14400s, dpd delay 10s
con13: IKEv2, no reauthentication, rekeying every 14400s, dpd delay 10s
con14: IKEv2, no reauthentication, rekeying every 14400s, dpd delay 10s
con16: IKEv2, no reauthentication, rekeying every 14400s, dpd delay 10s
con17: IKEv2, no reauthentication, rekeying every 14400s, dpd delay 10s

**Comment by AdSchellevis** [comment]
best create a sample config in ipsec.conf and a swanctl.conf style and point to where you expect the translation is wrong and we'll try to check the code on our end.

**Comment by at0msense** [comment]
![lifetime_phase1_86400_in_gui](https://user-images.githubusercontent.com/124162279/222217266-6c8e8784-fbe7-4e1b-9f85-3bff81a9ab8a.png)

But the there is no entry " rekey_time = 86400" in swanctl.conf for this tunnel.

**Comment by AdSchellevis** [comment]
https://github.com/opnsense/core/blob/4c84f442c86d28c506e1cbe4b92497850b4b0027/src/etc/inc/plugins.inc.d/ipsec.inc#L1353-L1357

^^  https://docs.strongswan.org/docs/5.9/config/rekeying.html

**Comment by at0msense** [comment]
Unfortunately I don't really know what you want to say with the screenshot. 
My expectation is that if I enter a lifetime of 86400s for phase 1, then the tunnel really has a lifetime of 86400s and not 14400s ( which is the default according to the strongswan documentation, because the parameter in the swanctl.conf

**Comment by AdSchellevis** [comment]
The problem is that according to the documentation this wors differently, which is why I'm referring to the upstream documentation and the implementation on our end. `rekey_time` and `ikelifetime` aren't the same

**Comment by at0msense** [comment]
Okay. Understood. According to the documentation, I'll say that the lifetime parameter for phase 1 ( IKE SA ) in the GUI, corresponds to the <conn>.rekey_time for the connection in swanctl.conf. The lifetime parameter for phase 2 ( IPsec SA )in the GUI  is incorrectly set here with <child>.life_time in swanctl.conf. The parameter should be <child>.rekey_time here.

**Comment by AdSchellevis** [comment]
Let's agree to disagree here. https://wiki.strongswan.org/projects/strongswan/wiki/Fromipsecconf and https://docs.strongswan.org/docs/5.9/config/rekeying.html suggest otherwise.

**Comment by at0msense** [comment]
Sure ? comparsion says:
old
ikelifetime=3h (default)
new
connections.<conn>.rekey_time=170m (default: 4h)

old
lifetime=1h (default)
new
connections.<conn>.children.<child>.life_time=1h (default: 110% * rekey_time)
**but configuring**
connections.<conn>.children.<child>.rekey_time (default: 1h, so setting life_time to 1h without changing this, will disable rekeying)
**instead is preferred,**

**Comment by AdSchellevis** [comment]
yes?
<img width="810" alt="image" src="https://user-images.githubusercontent.com/9783985/222394403-1fea851b-268e-4320-9621-d99a7b06ab9c.png">
<img width="1149" alt="image" src="https://user-images.githubusercontent.com/9783985/222394910-bcc420c0-f92b-4deb-946a-cb11ea5344a3.png">

if ikelifetime would be the same, I would expect a migration note would state "rekey_time = ikelifetime", which it doesn't. 
I'm bailing out of this for now, if valuable feedback for an improvement arrives we can always discuss further.

**Comment by at0msense** [comment]
I must have taken the only IKEv1 tunnel by mistake. The other tunnels are all IKEv2.
I've added the screenshot only to show that lifetime in the GUI is set to 86400s and not 14400s. 
But the 14400s is set incorrectly for both IKEv1 and IKEv2.
