### ISSUE TITLE
Interfaces: Diagnostics: Port Probe: migrate to MVC

### ISSUE THREAD

**Issue by fichtner** [opnsense/core#6379]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**

Static pages need to be removed eventually. Services page offers opportunity for it and enables API handling of the functionality.

**Describe the solution you like**

See DNS lookup for inspiration, parse results.

**Describe alternatives you considered**

N/A

**Additional context**

N/A

**Comment by AdSchellevis** [comment]
fixed in https://github.com/opnsense/core/commit/327334b0fb8de9e64ce98217eb6bf8ab6726c5b2
