### ISSUE TITLE
Services: DHCP: Leases (4+6): migrate to MVC

### ISSUE THREAD

**Issue by fichtner** [opnsense/core#6380]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**

Static pages need to be removed eventually. Services page offers opportunity for it and enables API handling of the functionality.

**Describe the solution you like**

Likely easy to migrate using the searchRecordsetBase() method.

**Describe alternatives you considered**

N/A

**Additional context**

N/A

**Comment by swhite2** [comment]
DHCPv4: https://github.com/opnsense/core/commit/4b7a1ce85bac391993fa106ce2fc1677331e8bdb
DHCPv6: https://github.com/opnsense/core/commit/f782be9cbf39ea99c9770458a78f2ece2d5031d7

**Comment by FSeidinger-XI** [comment]
In my opinion this is only half the work to be done. Sure it is good to search or delete leases, but how about adding leases? There seems to be currently no way to do that over the API.

**Comment by fichtner** [comment]
ISC DHCP is a legacy component and will remain that way which means no more API for it. Eventually it will become an optional plugin with a proper API-capable replacement in the core.
