### ISSUE TITLE
VPN: OpenVPN: Client Specific Overrides: Migrate to MVC

### ISSUE THREAD

**Issue by fichtner** [opnsense/core#6381]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**

Static pages need to be removed eventually. Services page offers opportunity for it and enables API handling of the functionality.

**Describe the solution you like**

Might be possible to migrate this inline (openvpn->openvpn-csc), question is what to do with the "advanced" input. 

**Describe alternatives you considered**

N/A

**Additional context**

N/A

**Comment by AdSchellevis** [comment]
The "advanced" input has been removed, couldn't find a lot of relevant tickets for options that we should add for the overwrites. 90% of the use-cases likely only involve network settings (tunnels, distributed nets)

**Comment by mimugmail** [comment]
> The "advanced" input has been removed, couldn't find a lot of relevant tickets for options that we should add for the overwrites. 90% of the use-cases likely only involve network settings (tunnels, distributed nets)

Maybe this will make a bit work after releasing it. 99% of the users don't read tickets here and quite sure couple of them use this field, especially static-user-auth or similar. And as the new MVC code gives users the option to mass roll-out configs it would make  things more complex.

**Comment by AdSchellevis** [comment]
@mimugmail might be the case, but I've honestly can't remember anyone using these for the overwrites, usually the "options" are generic in my experience (and set on the server)
