### ISSUE TITLE
Firewall: NPTv6: migrate to MVC

### ISSUE THREAD

**Issue by fichtner** [opnsense/core#6383]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**

Static pages need to be removed eventually. Services page offers opportunity for it and enables API handling of the functionality.

**Describe the solution you like**

Use bootgrid to list rules and also tackle #6158

**Describe alternatives you considered**

N/A

**Additional context**

N/A

**Comment by AdSchellevis** [comment]
needs a least a solution to offer a "network" selection like the legacy part
<img width="694" alt="image" src="https://github.com/opnsense/core/assets/9783985/ea09567f-868e-45ef-a04c-411e6600e284">

Same is the case for ports.

**Comment by fichtner** [comment]
The trackif validation is not tight enough (want to limit it to dhcp6c interface trackers).
