### ISSUE TITLE
Unbound: General: migrate to MVC

### ISSUE THREAD

**Issue by fichtner** [opnsense/core#6387]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**

Static pages need to be removed eventually. Services page offers opportunity for it and enables API handling of the functionality.

**Describe the solution you like**

Please move OPNsense.unboundplus to OPNsense.unbound while at it.

**Describe alternatives you considered**

N/A

**Additional context**

N/A

**Comment by swhite2** [comment]
Implemented in https://github.com/opnsense/core/commit/5492d4477ce775b05c2018cc2663c423891663d8

**Comment by fichtner** [comment]
The port can be empty but the model is set to `required` and a blank port will thus be filled out during migration. Also `BlankDesc` doesn't seem to do what it should.

**Comment by fichtner** [comment]
I fixed the `BlankDesc` via e42b8a301887c. However, it makes more sense to enforce the default since we migrate anyway. But I don't agree on enabling unbound on migration by default. Also we need to adjust src/etc/config.xml.sample accordingly. It still uses the old layout.

**Comment by swhite2** [comment]
@fichtner How about https://github.com/opnsense/core/commit/ffc1c438e02ae209b8ad690907d3fad8f74a6248? :)

**Comment by fichtner** [comment]
The help text for port also needs attention./

**Comment by fichtner** [comment]
All done 👍
