### ISSUE TITLE
PHP syntax errors on master

### ISSUE THREAD

**Issue by fabianfrz** [opnsense/core#639]
Used "php -l" to check the syntax. (using PHP 7)

PHP Parse error:  syntax error, unexpected '}', expecting end of file in diag_smart.php on line 267
PHP Parse error:  syntax error, unexpected end of file in vpn_openvpn_export.php on line 825
PHP Parse error:  syntax error, unexpected end of file in vpn_openvpn_export_shared.php on line 406

**Comment by 8191** [comment]
I could not reproduce your output with PHP 5 within ae3ffb284f204676bf1dda5c019c499b5e4c0fb4. Is there a specific reason you've validated with PHP 7? Anyway, I don't think that missing braces (error reported for `diag_smart.php`) are being validated differently within PHP 5 and PHP 7... Did you also run your validation within ae3ffb284f204676bf1dda5c019c499b5e4c0fb4?

**Comment by fabianfrz** [comment]
yes it is the same (ae3ffb2).

I use PHP 7 because it is installed on my host system and it will be used by OPNsense in the future.

**Comment by 8191** [comment]
I could not verify your findings with PHP 7.0.2, neither... Which version did you use?

**Comment by fabianfrz** [comment]
PHP 7.0.2 (cli)

**Comment by 8191** [comment]
Same here. Strange...

**Comment by fabianfrz** [comment]
Which operating system are you using?

**Comment by 8191** [comment]
Tested it on Windows 10.

**Comment by fabianfrz** [comment]
I sent you a mail

**Comment by fichtner** [comment]
PHP Parse error: syntax error, unexpected '}', expecting end of file in diag_smart.php on line 267

That file is twice as long, but PHP sees it as truncated most likely. sshfs? nfs mount? clobbered fs? git checkout -f may help or resyncing the code. I think we've had this before, @fabianfrz

**Comment by fabianfrz** [comment]
@fichtner no it is a file on my host system (local file system)
```
git checkout -f
Ihr Branch ist auf dem selben Stand wie 'origin/master'. 
```

last time I had issues was because of short open tags were disabled but this file does not these

**Comment by fabianfrz** [comment]
ok, looks like it is the PHP build I am using (older version 7.0.1 works)

**Comment by fichtner** [comment]
A regression in PHP? Whoopsie?!

**Comment by fabianfrz** [comment]
No - compiled PHP 7.0.2 right now  and this version works too.

**Comment by fichtner** [comment]
Arch package then? This is totally obscure. :)

**Comment by 8191** [comment]
After trying some PHP-OS combinations, I receive the same error using PHP 5.6.16 under Linux64, but not under Windows or FreeBSD. Same with PHP 7.0.2 (Windows no error, Linux64 error as above, FreeBSD not tested).
