### ISSUE TITLE
File permission on dhcp.leases seems to change after `rc.linkup: plugins_configure dhcp` runs

### ISSUE THREAD

**Issue by SwissGipfel** [opnsense/core#6393]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

We encounter an issue where the dhcp leases file is not readable by 'others' anymore. Normally a restart of dhcpd or a complete reboot fix this temporarily. We had this behavior for quite a while (can't say, when exactly it started) but with Version `OPNsense 23.1.1_2-amd64` and the previous stable version it seems to trigger frequently.

**To Reproduce**

We've observed this behavior on two occasions up until now:

1. The less frequent one: when adding ip reservations on a dhcp scope in the Web-UI. I can't supply logs for this one atm.
2. The more frequent one: restarting a connected - on a LAN port - gateway (in a double NAT setup) seems to trigger `/usr/local/etc/rc.linkup: plugins_configure dhcp (execute task: dhcpd_dhcp_configure())`. These are the moments we discovered the loss of the read permissions

**Expected behavior**

I expect the permissions to stay the same after a reconfiguration as they were set after a service restart.

**Describe alternatives you considered**

At first, we just restarted the dhcpd service or our whole appliance. This fixes the issue temporarily.
An even better alternative would be the usage of an API to get the leases (see section 'Additional context'). As far as I know, there's currently no such Api available.

**Screenshots**
![image](https://user-images.githubusercontent.com/15341063/222760253-31f6b07c-2826-4fda-9458-838278a6c35b.png)

```bash
-rw-r-----  1 dhcpd  dhcpd  2629794 Mar  2 17:09 /var/dhcpd/var/db/dhcpd.leases
```

**Relevant log files**

I'm not really an OPNSense pro. Can provide relevant logfiles, if you help me find it :)

**Additional context**

Currently we've automation in place, that fetches via scp and parses the dhcp.leases of every OPNSense we use in production, to find devices like printers and configure them automatically. The automation uses a specific user that has limited access. Basically, permission to access shell and read - with said 'others' read permission - /var/dhcpd/var/db/dhcpd.leases.

As already mentioned, we tried to implement this automation with an (REST) API but couldn't find one for dhcp out of the box. But to be fair, it's been some time since we looked.

**Environment**

```
OPNsense 23.1.1_2-amd64
FreeBSD 13.1-RELEASE-p6
OpenSSL 1.1.1t 7 Feb 2023
```

**Comment by fichtner** [comment]
Configd infamously mangles permissions for files created. I’m not sure about touching them though. Yet AFAIK dhcpd would be the only one to recreating these files (while switching to the strange copy they make on edits?) so we might not have further influence on this directly. Umask change might be the only option here.


Cheers,
Franco

**Comment by fichtner** [comment]
PS: An API for the IPv4 leases is on the roadmap for 23.7…

**Comment by SwissGipfel** [comment]
Thanks for the fast response!

Will a Umask change survive an OPNsense update? We automated them too with a canary deployment.
As far as I know, I can change the system default with a corresponding script in `/etc/profile.d/` - or overwrite it with ~/.bashrc.
But won't at least `/etc/profile.d/` be touched in an upgrade?

**Comment by fichtner** [comment]
/etc/profile.d should he left untouched. I can take a closer look on Monday. What user/group are you using for reading the file if I may ask?

**Comment by SwissGipfel** [comment]
We created a user with the OPNsense UI called 'dhcpreader' and a group 'lease_reader', allowed the user to connect to shell

```shell
# /etc/passwd
dhcpreader:*:2000:65534::/home/dhcpreader:/bin/sh

# /etc/group
lease_readers:*:2000:dhcpreader
```

Now that I think about it, 'lease_readers' is not needed anymore. This group has only the permission to access the ARP Table API - this was our first approach.

Essentially, the user 'dhcpreader' accesses the file `/var/dhcpd/var/db/dhcpd.leases` with its permission to access shell and the permission for 'others', which would be `read` normally.

**Comment by SwissGipfel** [comment]
We just added the user to the dhcpd group. This may be not the best solution in terms of permissions, but since we want to rework our solution after the release of the ipv4 API (hopefully in 23.7 :wink: ) anyway, I think we can live with this workaround.

Thanks for your time & help!

**Comment by fichtner** [comment]
Sorry, it was a bit busy getting 23.1.2 out the door. I was thinking the same about dhcpd group, but discarded it because a few versions back it wasn't possible to retain system users with system groups over a reboot, but we did change that last year I think so it should be a pretty good solution for the time being. 👍 

Close issue?


Cheers,
Franco
