### ISSUE TITLE
Alias name restriction (Firewall:Alias)

### ISSUE THREAD

**Issue by bongoo1** [opnsense/core#6394]
when trying to add a new device, i tried to do this according to the scheme i always did it so far.
unfortunately, this seems to be no longer accepted without obvious reason.

my scheme is:
<device type, 1 letter>_<device name>

as an example:
W_MyWifiDevice

this is not accepted and results in the message "The name must start with a letter or single underscore, be less than 32 characters and only consist of alphanumeric characters or underscores.". i think this is fulfilled.

but using
WW_MyWifiDevice
or
_W_MyWifiDevice

is accepted.

i'm running
    OPNsense 23.1.1_2-amd64
Intel(R) Celeron(R) CPU J3455 @ 1.50GHz (4 cores, 4 threads)

**Comment by fichtner** [comment]
https://github.com/opnsense/core/commit/158220ebd606a1a173f99b75c62f95737da6bd74
