### ISSUE TITLE
IPSec API - not working as expected

### ISSUE THREAD

**Issue by ansibleguy** [opnsense/core#6398]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

The new IPSec API does not work as [documented](https://docs.opnsense.org/development/api/core/ipsec.html) and/or expected.

**To Reproduce**

Try to add a connection/tunnel using the API as documented:

```bash
curl -u API_KEY:API_SECRET https://FW/api/ipsec/connections/addConnection --insecure -H "Content-Type: application/json" -d '{"Connection": {"description": "test1", "enabled": 1}}'

{"result":"failed"}
```

The actual working API-calls differ from the expected ones:

```bash
curl -u API_KEY:API_SECRET https://FW/api/ipsec/connections/add_connection --insecure -H "Content-Type: application/json" -d '{"connection": {"description": "test99", "enabled": 1}}'

{"result":"saved","uuid":"1494398a-4900-492d-9810-7f19279208f1"}
```

Also - as mentioned in [this ticket](https://github.com/opnsense/core/issues/6397) - the 'get' commands of other ipsec-controllers do not return useful data.
I think this is because of the auto-generated documentation.
One might still need to call the 'connections' controller for all those sub-categories.

**Expected behavior**

I would expect:
* the **documented** API commands and controllers to work
* the case-sensitivity of keys like 'Connections' to be consistent. In the [schema](https://github.com/opnsense/core/blob/master/src/opnsense/mvc/app/models/OPNsense/IPsec/Swanctl.xml) it is defined capitalized but the API uses it in lowercase form
  * In my opinion => lowercase is always better (;

**Environment**

OPNsense 23.1.1_2-amd64FreeBSD
13.1-RELEASE-p6
OpenSSL 1.1.1t 7 Feb 2023
Common KVM processor (4 cores, 4 threads)
Hypervisor: Proxmox PVE

**Comment by AdSchellevis** [comment]
`Connection` vs `connection` ? `addConnection` and `add_connection` are actually the same endpoints, phalcon advises to use `add_connection` in this case, but both are mapped. (always check our gui code, easy to find out what's being used and works in that case....)

**Comment by ansibleguy** [comment]
Sorry.
I re-checked it and the documented API commands seem to work.

\- AnsibleGuy
