### ISSUE TITLE
IPsec status page reports 'disconnected' for working tunnel

### ISSUE THREAD

**Issue by fichtner** [opnsense/core#64]
"the ipsec tunnel site to site is up and running, although the status page for ipsec states disconnected."

via https://forum.opnsense.org/index.php?topic=82.0 and https://forum.opnsense.org/index.php?topic=69.0

**Comment by fichtner** [comment]
Indeed @AdSchellevis thanks, this is fixed then :)

**Comment by AdSchellevis** [comment]
I suppose it is, I was just trying to solve this one an came to the conclusion that smp didn't work :-)  I will update that package on my test setup and do some final testing...

**Comment by YordanYordanov** [comment]
The connection state in Status --> IPsec is now indeed correct, however I noticed that the IPsec widget doesn't display them correctly. Currently I have 7 working tunnels and the widget shows 7 inactive. Sometimes it shows 3/7 or other combinations. I have tested this on two different machines.
![ipsec widget](https://cloud.githubusercontent.com/assets/11943712/7337728/e543f78e-ec3c-11e4-8276-f325eb635726.PNG)

**Comment by AdSchellevis** [comment]
It's probably something small, but at the moment I don't have an active setup to test it properly. I will open a new issue for this one.
