### ISSUE TITLE
Unbound reporting: stops when a static lease is modified/added/removed

### ISSUE THREAD

**Issue by Christophe999s** [opnsense/core#6402]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

Unbound reporting stops when a static dhcp lease is modified/added/removed

**To Reproduce**

Change static dhcp lease
Check unbound reporting

**Workaround**
Reporting starts again when going into Reporting > Settings and clicking the Save button on Unbound DNS reporting

**Screenshots**
<img width="1320" alt="General" src="https://user-images.githubusercontent.com/36367001/223349603-1013de8f-709f-4766-a8ec-fe9c0be5be23.png">
![Reporting](https://user-images.githubusercontent.com/36367001/223349592-89f1a69f-dc3f-4fff-aa49-978894a87c7c.png)

**Additional context**
Thread on OPNsense forum:
https://forum.opnsense.org/index.php?topic=32161.0

Software version used and hardware type if relevant, e.g.:

OPNsense 23.1.1_2-amd64
FreeBSD 13.1-RELEASE-p6
OpenSSL 1.1.1t 7 Feb 2023
Intel(R) Core(TM) i5-10400 CPU @ 2.90GHz (4 cores, 4 threads)
Running in Proxmox VM

**Comment by AdSchellevis** [comment]
Looks like the `HUP` command kills the pipe between both processes and isn't reopened:

https://github.com/opnsense/core/blob/35090ecee19e90c31233d0c52250de91fc1a9219/src/etc/inc/plugins.inc.d/unbound.inc#L46

https://github.com/opnsense/core/blob/35090ecee19e90c31233d0c52250de91fc1a9219/src/etc/inc/plugins.inc.d/unbound.inc#L661

**Comment by fichtner** [comment]
It might be better to replace the HUP, as it forces unbound to do a complete reload and possibly purging the cache as well (without being able to retain it).

**Comment by fichtner** [comment]
TBH, the whole 'hosts' logic can be removed and dns restart be issued instead:

```
% git grep unbound_hosts_generate
src/etc/inc/plugins.inc.d/unbound.inc:        'hosts' => array('unbound_hosts_generate:0'),
src/etc/inc/plugins.inc.d/unbound.inc:function unbound_hosts_generate()
% git grep 'plugin.*hosts'       
src/www/services_dhcp.php:    plugins_configure('hosts');
src/www/services_dhcpv6.php:    plugins_configure('hosts');
```

**Comment by fichtner** [comment]
(the same applies to dnsmasq where HUP works, but how often is are host overrides edited in batch anyway)

**Comment by fichtner** [comment]
Should be taken care of then. Not before 23.1.3.
