### ISSUE TITLE
Firewall: Rules "Group rules" section does not show actual Source/Destination/Port details

### ISSUE THREAD

**Issue by justinhorton** [opnsense/core#6403]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

Version 23.1.2
Related to: [Firewall/Rules - show all applicable rules when showing an interface](https://github.com/opnsense/core/commit/4376301607aedb79a272469f2339a113a546996c)

* The new per-interface display of group firewall rules doesn't seem to properly show the Source/Destination/Port/etc. information for the rule. In my case, Source, Destination, and Destination Port are _not_ wildcards, but show up as `*` in the _Group rules_ section.
* Additionally, the rule also shows up on the Group Interface page itself (again with wildcards instead of the correct details).

**To Reproduce**

1. Add firewall group (`interfaces_groups.php`) and include 1 or more interfaces as members. Mine is `all_lans`.
2. Add a rule for the group, using non-wildcard entries for Source, Destination, and/or their respective Port (`firewall_rules.php?if=all_lans`).
3. View the firewall page for a Group member and observe that the rule row is present under _Group rules_, but that the correct details are missing (`firewall_rules.php?if=lan`).
4. Return to the firewall page for the Group itself and observe that (3) applies here, too, and the correct rule is shown just below, outside the _Group rules_ (`firewall_rules.php?if=all_lans`).

**Expected behavior**

I expected:
* the _Group rules_ display for relevant interfaces to show the details as defined in the group rule (`Firewall: Rules: LAN`).
* there to be no _Group rules_ display on the Interface Group definition itself (`Firewall: Rules: all_lans`).

**Screenshots**

Interface rule display in _Group rules_ not showing correct details:
![image](https://user-images.githubusercontent.com/18197817/223597604-90a657ee-4706-40a4-9c5c-88b817ef965c.png)

Group rule definition and duplicate display in _Group rules_:
![image](https://user-images.githubusercontent.com/18197817/223597383-a429ebea-0a83-46f5-925d-c0e77c44384f.png)

**Comment by AdSchellevis** [comment]
should be better with https://github.com/opnsense/core/commit/48bdf53cda2d321c8d709055506793763a30353a

**Comment by justinhorton** [comment]
@AdSchellevis thanks for this feature and the quick fix! I tested the patch and it works exactly as expected for my rules.

**Comment by AdSchellevis** [comment]
@justinhorton thanks for confirming, we'll try to merge this into a minor release soon.

**Comment by fichtner** [comment]
I'll include this in a hotfix for 23.1.2 to avoid future reports. Although the hotfix is currently on hold as we try to figure out what happened to sqlite (different story).


Cheers,
Franco
