### ISSUE TITLE
firewall alias not updating in a timely manner

### ISSUE THREAD

**Issue by Bugz000** [opnsense/core#6404]
i have a locally hosted blocklist i wish to poll ideally every 5 seconds for new entries, i update this list live as people are scanning my network - the moment they go somewhere they shouldn't - they are added to the list
back when i ran openwrt i could use an api to invoke a job to tell openwrt to re-pull the list and apply it
opnsense support for this infrastructure is either _SEVERELY_ lacking, or i'm doing something wrong

i have set the alias refresh frequency to 0 days 0.10 hours - (where's the minutes?, this should have a seconds parameter ideally) 
i have system -> settings -> cron -> job set to */1 minutes to update lists 
i have floating firewall rule using the alias to drop all packets incoming and outgoing from these ip addresses
but it can still take upwards of 20 mins to ACTUALLY reflect changes

by this point, the bot has already completely scanned my network and moved on - it's completely useless
WHY is faster poll rates seemingly not allowed?
is there something i am doing wrong?
how would YOU do this system, because i'd imagine a simple ip list and using the alias system is the way to go no?
i just cannot fathom why this should not be working, in my mind */1 should be running every 60 seconds, right? but it does not

it should not be performance based, it is running on proxmox vm with 40 cores, 16gb ram and 180gb bootdisk it should not have any trouble

issue supposedly fixed here; [c5555b2](https://github.com/opnsense/core/commit/c5555b2ebc4c2285fb40d3a1a22c1966820bc64e)
but i cannot apply this patch; "1 out of 1 hunks failed while patching etc/inc/system.inc"

it is at this point i am at a complete loss

**Comment by williamdes** [comment]
Hi @Bugz000 
Any chance you for you to update your system ?

**Comment by Bugz000** [comment]
i updated my system, i now use API to add to api and refresh the rules, so instead of polling it's proactively updated when required, but the firewall is still not reacting fast re;

> i have floating firewall rule using the alias to drop all packets incoming and outgoing from these ip addresses
> but it can still take upwards of 20 mins to ACTUALLY reflect changes

cite;
https://www.reddit.com/r/OPNsenseFirewall/comments/13l6alq/opnsense_states/
https://forum.opnsense.org/index.php?topic=21074.0
https://forum.opnsense.org/index.php?topic=30962.0
https://forum.opnsense.org/index.php?topic=38305.0
https://forum.opnsense.org/index.php?topic=31706.0

similar issues
flush_states kill_states api endpoints may solve, but documentation on what they exactly do is totally non-existent

both seem to ultimately totally disconnect all active connections, not really a solution

is there no way to force a single state to refresh?

**Comment by Bugz000** [comment]
solved
https://forum.opnsense.org/index.php?topic=48670.msg245913#msg245913
