### ISSUE TITLE
setting a static dcphv4 ip address stops unbound reporting

### ISSUE THREAD

**Issue by roblatour** [opnsense/core#6405]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x ] I have read the contributing guidelines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x ] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

Unbound reporting stops as soon as I go into Services - DCHPv4 - Leases and click the '+' sign beside an active lease type and make it static.

The dashboard shows Unbound as green.  However, the reporting for unbound dns - overview no longer shows any activity being added.

To correct this, I go into the lobby dashboard and restart the unbound service.

Please see this post for more information:
https://forum.opnsense.org/index.php?topic=32810.0

**To Reproduce**

as described above.

**Expected behavior**

changing a lease type from active to static should not impact unbound reporting.

**Describe alternatives you considered**

**Screenshots**

available in post linked to above

**Relevant log files**

If applicable, information from log files supporting your claim.

**Additional context**

**Environment**

**Comment by AdSchellevis** [comment]
duplicate https://github.com/opnsense/core/issues/6402
