### ISSUE TITLE
Opensense 23.1.2 puts GW as default route even though it's marked as "Down" and " Upstream Gateway" is not checked

### ISSUE THREAD

**Issue by notyourcommy** [opnsense/core#6406]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**
Hello
Fresh install here 23.1.2-amd64
There is a single GW in the system which is configured like that :

 _Upstream Gateway []
 Disable Gateway Monitoring[x]
 Mark Gateway as Down[x]_

**To Reproduce**

1. Go to System > Gateways > Single > GW in question
2. Turn off "Upstream Gateway" and "Disable Gateway Monitoring"
3. Turn on "Mark gateway as Down"
4. See in System > Routes > Status that this GW is still default

**Expected behavior**
It was mine understanding that
1) Only Gateways with "Upstream Gateway" marked should be considered to be set as Default GW (ever)
2) Gateways that are marked as Down (Mark gateway as Down) should not be concidered as Default GW (ever)
Also this https://github.com/opnsense/core/issues/3597

**Screenshots**

![routes-opnsense](https://user-images.githubusercontent.com/56963978/223972796-d1e59e18-ec9f-4bc0-a782-3d5cfe4c2569.png)
![GW-opnsense](https://user-images.githubusercontent.com/56963978/223972818-382e801b-cc93-418a-a4b2-9d80d80bdfd7.png)

Software version used and hardware type if relevant, e.g.:

OPNsense 23.1.2-amd64

**Comment by fichtner** [comment]
I believe this is only true when you use default gateway switching option. Still you would need a separate default gateway. If it's the only gateway in your system there is nothing else to switch to. ;)


Cheers,
Franco

**Comment by notyourcommy** [comment]
> I believe this is only true when you use default gateway switching option. Still you would need a separate default gateway. If it's the only gateway in your system there is nothing else to switch to. ;)
> 
> Cheers, Franco

We have FRR installed on this Opnsense and BGP neighbours are sending default routes to Opnsense box so it will be installed as best route when this static default gw will be deleted (or missing)

Also same situation was (kinda?) solved via this issue - https://github.com/opnsense/core/issues/3597
+ https://github.com/opnsense/core/commit/64fd58da15c1979f3a461310ea3013a7ce26c9dd

**Comment by fichtner** [comment]
Not knowing the full setup I can't help very much. System default route is set in two places: once for default gateway switching and in any case also for standard routing. Also there a no logs attached.

**Comment by notyourcommy** [comment]
> Not knowing the full setup I can't help very much. System default route is set in two places: once for default gateway switching and in any case also for standard routing. Also there a no logs attached.

What is "standard routing" and what kind of logs should I attach?
Also can you please be more "transparent", by saying "Still you would need a separate default gateway" what do you mean exactly? That Opnsense will still put something in default GW?

**Comment by fichtner** [comment]
I'm not the one who lacks providing data. I can't support this in community scope otherwise.


Cheers,
Franco

**Comment by fichtner** [comment]
# opnsense-log | grep ROUTING

**Comment by notyourcommy** [comment]
<13>1 2023-03-09T11:43:23+03:00 opnsense.localdomain opnsense 46582 - [meta sequenceId="3"] /system_gateways.php: ROUTING: entering configure using defaults
<13>1 2023-03-09T11:43:23+03:00 opnsense.localdomain opnsense 46582 - [meta sequenceId="4"] /system_gateways.php: ROUTING: IPv4 default gateway set to wan
<13>1 2023-03-09T11:43:23+03:00 opnsense.localdomain opnsense 46582 - [meta sequenceId="5"] /system_gateways.php: ROUTING: setting IPv4 default route to 92.255.**.53
<13>1 2023-03-09T11:43:23+03:00 opnsense.localdomain opnsense 46582 - [meta sequenceId="6"] /system_gateways.php: ROUTING: keeping current default gateway '92.255.**.53'
<13>1 2023-03-09T11:46:25+03:00 opnsense.localdomain opnsense 46459 - [meta sequenceId="3"] /system_gateways.php: ROUTING: entering configure using defaults
<13>1 2023-03-09T11:46:26+03:00 opnsense.localdomain opnsense 46459 - [meta sequenceId="4"] /system_gateways.php: ROUTING: IPv4 default gateway set to wan
<13>1 2023-03-09T11:46:26+03:00 opnsense.localdomain opnsense 46459 - [meta sequenceId="5"] /system_gateways.php: ROUTING: setting IPv4 default route to 92.255.**.53
<13>1 2023-03-09T11:46:26+03:00 opnsense.localdomain opnsense 46459 - [meta sequenceId="6"] /system_gateways.php: ROUTING: keeping current default gateway '92.255.**.53'
<172>1 2023-03-09T11:47:50+03:00 opnsense.localdomain php-cgi 46582 - [meta sequenceId="1"] /system_general.php: ROUTING: not a valid host gateway address: ''
<172>1 2023-03-09T11:47:50+03:00 opnsense.localdomain php-cgi 46582 - [meta sequenceId="2"] /system_general.php: ROUTING: not a valid host gateway address: ''
<13>1 2023-03-09T11:47:51+03:00 opnsense.localdomain opnsense 44869 - [meta sequenceId="10"] /usr/local/etc/rc.filter_configure: ROUTING: keeping current default gateway '92.255.**.53'
<13>1 2023-03-09T12:00:01+03:00 opnsense.localdomain opnsense 47653 - [meta sequenceId="3"] /system_gateways.php: ROUTING: entering configure using defaults
<13>1 2023-03-09T12:00:01+03:00 opnsense.localdomain opnsense 47653 - [meta sequenceId="4"] /system_gateways.php: ROUTING: IPv4 default gateway set to wan
<13>1 2023-03-09T12:00:01+03:00 opnsense.localdomain opnsense 47653 - [meta sequenceId="5"] /system_gateways.php: ROUTING: setting IPv4 default route to 92.255.**.53
<13>1 2023-03-09T12:00:01+03:00 opnsense.localdomain opnsense 47653 - [meta sequenceId="6"] /system_gateways.php: ROUTING: keeping current default gateway '92.255.**.53'
<13>1 2023-03-09T12:00:01+03:00 opnsense.localdomain opnsense 69375 - [meta sequenceId="9"] /usr/local/etc/rc.filter_configure: ROUTING: keeping current default gateway '92.255.**.53'

**Comment by fichtner** [comment]
So for one that looks like default gateway switching to me. I'd recommend to disable this first and try a reboot and post the log again.

**Comment by notyourcommy** [comment]
<13>1 2023-03-09T13:41:00+03:00 opnsense.localdomain opnsense 65381 - [meta sequenceId="3"] /usr/local/etc/rc.routing_configure: ROUTING: entering configure using defaults
<13>1 2023-03-09T13:41:00+03:00 opnsense.localdomain opnsense 65381 - [meta sequenceId="4"] /usr/local/etc/rc.routing_configure: ROUTING: IPv4 default gateway set to wan
<13>1 2023-03-09T13:41:00+03:00 opnsense.localdomain opnsense 65381 - [meta sequenceId="5"] /usr/local/etc/rc.routing_configure: ROUTING: setting IPv4 default route to 92.255.111.53
<13>1 2023-03-09T13:41:00+03:00 opnsense.localdomain opnsense 65381 - [meta sequenceId="6"] /usr/local/etc/rc.routing_configure: ROUTING: keeping current default gateway '92.255.111.53'
<13>1 2023-03-09T13:41:00+03:00 opnsense.localdomain opnsense 65381 - [meta sequenceId="9"] /usr/local/etc/rc.routing_configure: ROUTING: keeping current default gateway '92.255.111.53'
![newroutesstatus-opn](https://user-images.githubusercontent.com/56963978/224000813-eb7679ac-17f6-4c6a-bced-972853921a61.png)
![newgw-opn](https://user-images.githubusercontent.com/56963978/224000825-c6ad2df2-7098-48e6-beba-deafd71ba09b.png)

![newroutes-opn](https://user-images.githubusercontent.com/56963978/224000841-9987d961-86a4-4ef7-9831-7b579e69c8d8.png)


Gw is disabled, logs after reboot

**Comment by AdSchellevis** [comment]
System->Settings->General / Gateway switching

**Comment by fichtner** [comment]
What does this return?

    # grep -c /gateway_item /conf/config.xml

**Comment by notyourcommy** [comment]
> System->Settings->General / Gateway switching

Turned off. Same results

**Comment by notyourcommy** [comment]
> 

grep -c /gateway_item /conf/config.xml
2

**Comment by fichtner** [comment]
Ok, you have a shadow entry in your config.xml -- delete the gateway and the other one with the wrong settings will appear in the GUI.

**Comment by notyourcommy** [comment]
> Ok, you have a shadow entry in your config.xml -- delete the gateway and the other one with the wrong settings will appear in the GUI.

Yes! It's working as it should now. Is there a clue what might create such shadow GW? 

"Mark Gateway as Down" now tells opnsense to not use this GW as default.

Thank you!

**Comment by fichtner** [comment]
I'm taking a look now, but no promises.

**Comment by notyourcommy** [comment]
I understand that my "clicking" did it and I almost remember exact moment when I first saw second GW option inside interface configuration. I'll update if I will be able to reproduce it.

**Comment by fichtner** [comment]
Thanks, that would help.

**Comment by fichtner** [comment]
I added a GUI fix for avoiding double-clicks in the form since 23.1.4. I'm closing this until new evidence on newer versions is available.
