### ISSUE TITLE
Invert destination rules are not showed correctly in the interface UI

### ISSUE THREAD

**Issue by ivlis** [opnsense/core#6409]
This is how the rule is shown in the rules table:

![image](https://user-images.githubusercontent.com/332942/224489193-ca267902-66ec-4864-a3a1-26707d7acdc9.png)

The rule config is:

![image](https://user-images.githubusercontent.com/332942/224489234-b1274b6f-9bdb-4910-a516-745d100cb8a4.png)

OPNsense 23.1.3-amd64
FreeBSD 13.1-RELEASE-p7
OpenSSL 1.1.1t  7 Feb 2023

**Comment by AdSchellevis** [comment]
fixed with https://github.com/opnsense/core/commit/3725d70732a49e6351465deedcb19d3b5c4acbf5
