### ISSUE TITLE
Feature: GUI login using certificate

### ISSUE THREAD

**Issue by 8191** [opnsense/core#641]
SSH can be restricted to prevent password login (default). Since the WebUI is considered the main entry point for configuration, what about implementating HTTP authentication using X.509 certificates?

**Comment by 8191** [comment]
Client certification authentication got really (unnecessary) complicated with current Chrome. The user need to manually reconfigure the certificate to be able to use it for authentication... :( Not really user friendly in my opinion.

Regarding the OPNsense implementation I have two basic designs in my head:

1. The certificate is stored with the other certificates in the certificate store and can be assigned to each user like IPsec certificates
2. A Base64 encoded string of a X.509 certificate can be paste into the user's configuration similar like SSH public key authentication

I think both solutions have advantages and disadvantages. I personally vote for 1, since then all certificates are in one place and also certificate creation can be implemented easily (or already exists partially).
Any Recommendations?

**Comment by fabianfrz** [comment]
@8191 I know how this works and you cannot use any certificate here.

**Comment by 8191** [comment]
Yes, typically you use a CA and let the webserver verify the certification path, but you also could realize it programmatically, e.g. let PHP verify the certificate. 

But yes, option 3 arises... ;-)

**Comment by fichtner** [comment]
cross-reference https://github.com/opnsense/core/issues/615

**Comment by fichtner** [comment]
timeout and lack of ressources, other construction sites have priority
