### ISSUE TITLE
Possible visual defect in firewall rule when "invert" and alias is used

### ISSUE THREAD

**Issue by MrClayPole** [opnsense/core#6413]
When running the OPNsense 23.1.3-amd64 and viewing with the Brave browser v1.49.120 (Mar 9, 2023) I can see a possible visual defect in the firewall rules when "invert" for an alias is selected for either the source or destination of a firewall rule.

When creating a firewall rule where an interface is selected for the destination or source with "invert" then it's rendered with a "!" in front of the interface the firewall rules list to indicate that inversion has been chosen.

If you do the same but select an alias for the source or destination with "invert" then the "!" is not rendered which I believe leads to a confusing render of the firewall rules list.

I believe it would be better if the "!" was rendered for aliases as well as interfaces in the firewall rules list when "invert" is selected.

**Comment by AdSchellevis** [comment]
duplicate https://github.com/opnsense/core/issues/6409
