### ISSUE TITLE
Use CSP frame-ancestors with GUI for whitelisted URLs

### ISSUE THREAD

**Issue by yordanov-alexandar** [opnsense/core#6416]
**Is your feature request related to a problem? Please describe.**

I would like to be able to embed Opnsense inside Home Assistant. 
Home Assistant supports adding custom URLs to it's sidebar(https://www.home-assistant.io/integrations/panel_iframe/). Pressing the new button in the sidebar(corresponding to the added URL) loads the URL on the right side inside an Iframe. Currently the browser prevents the loading of Opnsense because of the 'X-Frame-Options: SAMEORIGIN' header

**Describe the solution you like**

Please remove X-Frame-Options header and use frame-ancestors directive of CSP instead and also add a GUI for entering whitelist URLs that will be added to frame-ancestors

**Describe alternatives you considered**

Currently I have used SSH and edited guiconfig.inc manually to comment X-Frame-Options and add frame-ancestors to CSP and it's working, but that will probably be overwritten pretty often... I don't know if there are any other alternatives

**Comment by AdSchellevis** [comment]
It's a security measurement, I don't expect we will remove it to be honest.

**Comment by yordanov-alexandar** [comment]
From what I understood from the documentation frame-ancestors 'self' is doing the same thing as X-Frame-Options: SAMEORIGIN, but frame-ancestors also allows to add a list of other urls that are allowed like: frame-ancestors 'self' <url1> <url2> ...
