### ISSUE TITLE
Update translation template

### ISSUE THREAD

**Issue by fabianfrz** [opnsense/core#642]
@fichtner wait until #640 is merged

**Comment by fichtner** [comment]
Yes, this will be the last regeneration for 16.1. After that no more gettext changes so the translation doesn't go out of sync, ok?

Releasing 15.7.24 today, will merge and regenerate afterwards.

**Comment by fabianfrz** [comment]
@fichtner thanks - this is also the reason why I want the template to be regenerated. 
Many strings have been changed and I think we should have everything in the menu translated (if possible) when 16.1 is released.


Will the code in the "plugin" repository also be part of the translation in this repository?

**Comment by fichtner** [comment]
It's still unclear how the plugins tie into the translations, that's something for 16.7 to figure out as we add actual GUI plugins that need translations. All ideas welcome here. It would, however, not be productive to merge translations into core.git from plugins.git, they need to coexist independently.

Small note: I was hoping we could "finish" German and I will certainly help to contribute. We have set a milestone to complete a translation (let's say 90%, it's hard to get 100% anyway with strings being changed and corrected). What do you think, will this be doable or am I dreaming? :)

**Comment by fabianfrz** [comment]
it is around 30% which is a lot of work but it may be possible if we work really hard on it.
However we have to fix many strings because they cannot be translated without concatenating them (will give a useless result).
Other strings should not be in the template (I think many of them come from menu.xml - the XML tag when VisibleName is set e.g. https://translate.opnsense.org/de/gui/translate/de.po#filter=incomplete&unit=10652 )

**Comment by fichtner** [comment]
Done pending Pootle upload.
