### ISSUE TITLE
OpenVPN client cannot connect after update to 23.1.3_4

### ISSUE THREAD

**Issue by gallogabor** [opnsense/core#6420]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [*] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [*] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

After update to 23.1.3._4, OpenVPN client stopped connecting to remote OpenVPN server. Neither server or client config changed. The remote server logged that "the cipher and key size is unknown". I found similar problems reported in the forums, so I changed the "Encryption algorithm (fallback)" option to "None" (from "AES-256-CBC" used until now) and added "`--cipher AES-256-CBC`" to advanced. This solved the problem, client connected again.
I think the GUI creates an OpenVPN config file that is not 100% compatible with the currently installed OpenVPN package.

*Tip*: to validate your setup was working with the previous version, use opnsense-revert (https://docs.opnsense.org/manual/opnsense_tools.html#opnsense-revert)

**To Reproduce**

1. Upgrade to 23.1.3_4
2. Try to connect OpenVPN client with Encryption algo set in UI
4. See "connecting" in status and error in server log

**Expected behavior**

OpenVPN client connect to server without this hack inserted in advanced config.

**Describe alternatives you considered**

None.

**Screenshots**

Not applicable I think.

**Relevant log files**

On server (Mikrotik router):
`<aaa.bbb.ccc.ddd>: disconnected <unkown cipher alg or key size>`

On client (OPNsense):
```
2023-03-15T18:17:42	Notice	openvpn_client4	SIGUSR1[soft,connection-reset] received, process restarting	
2023-03-15T18:17:42	Error	openvpn_client4	Connection reset, restarting [0]	
2023-03-15T18:17:41	Notice	openvpn_client4	TCP_CLIENT link remote: [AF_INET]vvv.xxx.yyy.zzz:abcde	
2023-03-15T18:17:41	Notice	openvpn_client4	TCP_CLIENT link local: (not bound)	
2023-03-15T18:17:41	Notice	openvpn_client4	TCP connection established with [AF_INET]vvv.xxx.yyy.zzz:abcde
2023-03-15T18:17:41	Notice	openvpn_client4	Attempting to establish TCP connection with [AF_INET]vvv.xxx.yyy.zzz:abcde [nonblock]	
2023-03-15T18:17:41	Notice	openvpn_client4	TCP/UDP: Preserving recently used remote address: [AF_INET]213.181.201.26:58194	
2023-03-15T18:17:41	Warning	openvpn_client4	NOTE: the current --script-security setting may allow this configuration to call user-defined scripts	
```

**Additional context**

None.

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 23.1.3_4 (amd64, OpenSSL).
Intel® Xeon™ E5-2450L 4 vCPU
Virtio Ethernet
Proxmox VE 6.4 virtual machine

**Comment by fichtner** [comment]
Is this a OpenVPN 2.3 server?

**Comment by gallogabor** [comment]
The "server side" runs on a Mikrotik CCR1009 router with RouterOS 6.47.4 (which is dated 2020.09.21.)
Unfortunately I cannot find the RouterOS embedded OpenVPN version. Only this sencence can be found on Mikrotik forums about this (official documentation says nothing about compatibility levels):
"Mikrotik uses an OpenVpn implementation of it own. You will not find parity of capabilities between Mikrotik's version and the official one."

**Comment by fichtner** [comment]
Thanks. It increasingly looks like OpenVPN is breaking the wider ecosystem with that deprecation of --ciphers option. Not sure what to do. CC @AdSchellevis

Forum post with similar report: https://forum.opnsense.org/index.php?topic=27394.0

**Comment by AdSchellevis** [comment]
No clue either, we can move it back to "cipher" and hope it doesn't die on the next iteration, in my opinion OpenVPN is extremely vague about the cipher option and deprecation. Reading the source for 2.6 (https://github.com/OpenVPN/openvpn/blob/release/2.6/src/openvpn/options.c#L3550-L3553) it kind of assumes it will just offer the same noise as 2.5 did (telling you it's not being used for cipher negotiations). 

The manual suggest it still exists in 2.6, but shouldn't be used (https://openvpn.net/community-resources/reference-manual-for-openvpn-2-6/). Let's change defaults to not set cipher, add a note and put it back as it was?

**Comment by fichtner** [comment]
strange idea: maybe it works setting both at the same time? 🤷

**Comment by AdSchellevis** [comment]
well apparently  it does, but it will make all of this even more confusing, so I think it's better to only set cipher in this case, so we able to offer the other settings if needed
