### ISSUE TITLE
23.1 Virtual IP configuration MVC UI is broken for certain setups

### ISSUE THREAD

**Issue by Kishi85** [opnsense/core#6422]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

After migrating to the Virtual IP MVC-UI in 23.1 you can no longer assing additional IP aliases to CARP VIPs (as was possible before). Additionally if you upgrade from a (for configd valid) configuration with IP aliases on CARP VIPs the OPNsense\Interfaces\Vip Migration will fail (noted in the upgrade log) and the whole Virtual IP MVC Settings-UI will lock up and not do anything.  The existing Virtual IP configuration is still correctly applied by configd (even with IPalias on the CARP VIP).

**To Reproduce**

1. Migrate from a configuration that has a CARP VIP with an IP alias
2. Try to edit/clone an existing IP Alias that was previously on a CARP VIP or try to create an IP alias on a CARP VIP
3. Note that save does not work/you cannot select a CARP VIP for the Interface of the IPalias

**Expected behavior**

Being able to add an IP Alias to a CARP VIP as was possible before 23.1 and is still correctly applied from an existing configuration by configd.

**Describe alternatives you considered**

Editing the config.xml manually to add an IP alias to the CARP VIP works as expected.

**Relevant log files**

There are no addtional log messages (at all) except for the already noted migration failure.

**Additional context**
Having IP Aliases on CARP VIPs is very useful as those additional IPs do not require an additional VHID to be assigned, which would limit the amount of Virtual IPs on an interface significantly.

**Environment**
OPNsense 23.1.3_4 (amd64, OpenSSL)

**Comment by Kishi85** [comment]
Addendum: Just did a HAsync a configuration with IP aliases on CARP VIPs to secondary where I manually deleted those aliases from config.xml and rebooted before and even that works so it's just the new MVC-UI that is broken in regards to IP Aliases on CARP VIPs

**Comment by AdSchellevis** [comment]
euh, just add the correct vhid on the alias? I don't think this was different before 23.1 to be honest.

**Comment by Kishi85** [comment]
I've tried that on my upgraded system and it doesn't let me edit or save anything in the VIP Settings MVC UI.

After some digging in the Logs i'm seeing errors like this one for every IP alias on CARP VIP in the General log:
```
[OPNsense\Interfaces\Vip:vip.ecad7906-88a5-4fc0-a395-9639d5edc687.vhid] VHID 2 must be defined on interface opt3 as a CARP VIP first.{2}
in /usr/local/opnsense/mvc/app/models/OPNsense/Base/BaseModel.php:583
Stack trace:	
#0 /usr/local/opnsense/mvc/app/models/OPNsense/Base/BaseModel.php(706): OPNsense\Base\BaseModel->serializeToConfig()	
#1 /usr/local/opnsense/mvc/script/run_migrations.php(54): OPNsense\Base\BaseModel->runMigrations()	
#2 {main} )	
```

This is presumably causing the problems with the UI and from the stack trace seems to be stemming from the failed config migration which gets retried every reboot. Seems like some kind of ordering issue when running the migration but in the original config.xml the corresponding parts are defined in the proper order (CARP first, then IP aliases on the CARP)

The corresponding config.xml section looks like this (obfuscated since it is a production config):
```
  <virtualip>
    <vip>
      <type>single</type>
      <subnet_bits>32</subnet_bits>
      <mode>carp</mode>
      <interface>opt1</interface>
      <descr>IF_WAN1_FW4</descr>
      <subnet>x.x.x.4</subnet>
      <vhid>3</vhid>
      <advskew>0</advskew>
      <advbase>1</advbase>
      <password>.*</password>
    </vip>
    <vip>
      <type>single</type>
      <subnet_bits>32</subnet_bits>
      <mode>ipalias</mode>
      <interface>opt1</interface>
      <descr>IF_WAN1_MAIL4</descr>
      <subnet>x.x.x.3</subnet>
      <vhid>3</vhid>
    </vip>
    <vip>
      <type>single</type>
      <subnet_bits>32</subnet_bits>
      <mode>ipalias</mode>
      <interface>opt1</interface>
      <descr>IF_WAN1_WWW4</descr>
      <subnet>x.x.x.2</subnet>
      <vhid>3</vhid>
    </vip>
    <vip>
      <type>single</type>
      <subnet_bits>32</subnet_bits>
      <mode>ipalias</mode>
      <interface>opt1</interface>
      <descr>IF_WAN1_IPSEC4</descr>
      <subnet>x.x.x.10</subnet>
      <vhid>3</vhid>
    </vip>
    <vip>
      <type>single</type>
      <subnet_bits>32</subnet_bits>
      <mode>ipalias</mode>
      <interface>opt1</interface>
      <descr>IF_WAN1_NS4</descr>
      <subnet>x.x.x.11</subnet>
      <vhid>3</vhid>
    </vip>
    <vip>
      <type>single</type>
      <subnet_bits>32</subnet_bits>
      <mode>ipalias</mode>
      <interface>opt1</interface>
      <descr>IF_WAN1_VC14</descr>
      <subnet>x.x.x.12</subnet>
      <vhid>3</vhid>
    </vip>
    <vip>
      <type>single</type>
      <subnet_bits>32</subnet_bits>
      <mode>ipalias</mode>
      <interface>opt1</interface>
      <descr>IF_WAN1_TURN4</descr>
      <subnet>x.x.x.13</subnet>
      <vhid>3</vhid>
    </vip>
    <vip>
      <type>single</type>
      <subnet_bits>32</subnet_bits>
      <mode>ipalias</mode>
      <interface>opt1</interface>
      <descr>IF_WAN1_WA4</descr>
      <subnet>x.x.x.14</subnet>
      <vhid>3</vhid>
    </vip>
    <vip>
      <type>single</type>
      <subnet_bits>32</subnet_bits>
      <mode>ipalias</mode>
      <interface>opt1</interface>
      <descr>IF_WAN1_VC24</descr>
      <subnet>x.x.x.15</subnet>
      <vhid>3</vhid>
    </vip>
    <vip>
      <type>single</type>
      <subnet_bits>128</subnet_bits>
      <mode>carp</mode>
      <interface>opt1</interface>
      <descr>IF_WAN1_FW6</descr>
      <subnet>2001:638:a01:11::2</subnet>
      <vhid>4</vhid>
      <advskew>0</advskew>
      <advbase>1</advbase>
      <password>.*</password>
    </vip>
    <vip>
      <type>single</type>
      <subnet_bits>128</subnet_bits>
      <mode>ipalias</mode>
      <interface>opt1</interface>
      <descr>IF_WAN1_FW6-external</descr>
      <subnet>2001:638:a01:5030::10</subnet>
      <vhid>4</vhid>
    </vip>
    <vip>
      <type>single</type>
      <subnet_bits>32</subnet_bits>
      <mode>carp</mode>
      <interface>opt2</interface>
      <descr>IF_WAN2_FW4</descr>
      <subnet>x.x.x.124</subnet>
      <vhid>3</vhid>
      <advskew>0</advskew>
      <advbase>1</advbase>
      <password>.*</password>
    </vip>
    <vip>
      <type>single</type>
      <subnet_bits>32</subnet_bits>
      <mode>ipalias</mode>
      <interface>opt2</interface>
      <descr>IF_WAN2_MAIL4</descr>
      <subnet>x.x.x.123</subnet>
      <vhid>3</vhid>
    </vip>
    <vip>
      <type>single</type>
      <subnet_bits>32</subnet_bits>
      <mode>ipalias</mode>
      <interface>opt2</interface>
      <descr>IF_WAN2_WWW4</descr>
      <subnet>x.x.x.122</subnet>
      <vhid>3</vhid>
    </vip>
    <vip>
      <type>single</type>
      <subnet_bits>128</subnet_bits>
      <mode>carp</mode>
      <interface>opt2</interface>
      <descr>IF_WAN2_FW6</descr>
      <subnet>xxx:xxx:xxx:26::2</subnet>
      <vhid>4</vhid>
      <advskew>0</advskew>
      <advbase>1</advbase>
      <password>.*</password>
    </vip>
    <vip>
      <type>single</type>
      <subnet_bits>128</subnet_bits>
      <mode>ipalias</mode>
      <interface>opt2</interface>
      <descr>IF_WAN2_FW6-external</descr>
      <subnet>xxx:xxx:xxx:3030::10</subnet>
      <vhid>4</vhid>
    </vip>
  </virtualip>
```

Any hints on how to fix this issue  without having to manually modify config.xml to delete the broken aliases, reboot and then recreate every single IP alias (there's just too many of them) would be greatly appreciated.

**Comment by Kishi85** [comment]
I've tried that on my upgraded system and it doesn't let me edit or save anything in the VIP Settings MVC UI.

After some digging in the Logs i'm seeing errors like this one for every IP alias on CARP VIP in the General log:
```
[OPNsense\Interfaces\Vip:vip.ecad7906-88a5-4fc0-a395-9639d5edc687.vhid] VHID 2 must be defined on interface opt3 as a CARP VIP first.{2}
in /usr/local/opnsense/mvc/app/models/OPNsense/Base/BaseModel.php:583
Stack trace:	
#0 /usr/local/opnsense/mvc/app/models/OPNsense/Base/BaseModel.php(706): OPNsense\Base\BaseModel->serializeToConfig()	
#1 /usr/local/opnsense/mvc/script/run_migrations.php(54): OPNsense\Base\BaseModel->runMigrations()	
#2 {main} )	
```

This is presumably causing the problems with the UI and from the stack trace seems to be stemming from the failed config migration which gets retried every reboot. Seems like some kind of ordering issue when running the migration but in the original config.xml the corresponding parts are defined in the proper order (CARP first, then IP aliases on the CARP)

The corresponding config.xml section looks like this (obfuscated since it is a production config):
```
  <virtualip>
    <vip>
      <type>single</type>
      <subnet_bits>32</subnet_bits>
      <mode>carp</mode>
      <interface>opt1</interface>
      <descr>IF_WAN1_FW4</descr>
      <subnet>x.x.x.4</subnet>
      <vhid>3</vhid>
      <advskew>0</advskew>
      <advbase>1</advbase>
      <password>.*</password>
    </vip>
    <vip>
      <type>single</type>
      <subnet_bits>32</subnet_bits>
      <mode>ipalias</mode>
      <interface>opt1</interface>
      <descr>IF_WAN1_MAIL4</descr>
      <subnet>x.x.x.3</subnet>
      <vhid>3</vhid>
    </vip>
    <vip>
      <type>single</type>
      <subnet_bits>32</subnet_bits>
      <mode>ipalias</mode>
      <interface>opt1</interface>
      <descr>IF_WAN1_WWW4</descr>
      <subnet>x.x.x.2</subnet>
      <vhid>3</vhid>
    </vip>
    <vip>
      <type>single</type>
      <subnet_bits>32</subnet_bits>
      <mode>ipalias</mode>
      <interface>opt1</interface>
      <descr>IF_WAN1_IPSEC4</descr>
      <subnet>x.x.x.10</subnet>
      <vhid>3</vhid>
    </vip>
    <vip>
      <type>single</type>
      <subnet_bits>32</subnet_bits>
      <mode>ipalias</mode>
      <interface>opt1</interface>
      <descr>IF_WAN1_NS4</descr>
      <subnet>x.x.x.11</subnet>
      <vhid>3</vhid>
    </vip>
    <vip>
      <type>single</type>
      <subnet_bits>32</subnet_bits>
      <mode>ipalias</mode>
      <interface>opt1</interface>
      <descr>IF_WAN1_VC14</descr>
      <subnet>x.x.x.12</subnet>
      <vhid>3</vhid>
    </vip>
    <vip>
      <type>single</type>
      <subnet_bits>32</subnet_bits>
      <mode>ipalias</mode>
      <interface>opt1</interface>
      <descr>IF_WAN1_TURN4</descr>
      <subnet>x.x.x.13</subnet>
      <vhid>3</vhid>
    </vip>
    <vip>
      <type>single</type>
      <subnet_bits>32</subnet_bits>
      <mode>ipalias</mode>
      <interface>opt1</interface>
      <descr>IF_WAN1_WA4</descr>
      <subnet>x.x.x.14</subnet>
      <vhid>3</vhid>
    </vip>
    <vip>
      <type>single</type>
      <subnet_bits>32</subnet_bits>
      <mode>ipalias</mode>
      <interface>opt1</interface>
      <descr>IF_WAN1_VC24</descr>
      <subnet>x.x.x.15</subnet>
      <vhid>3</vhid>
    </vip>
    <vip>
      <type>single</type>
      <subnet_bits>128</subnet_bits>
      <mode>carp</mode>
      <interface>opt1</interface>
      <descr>IF_WAN1_FW6</descr>
      <subnet>xxx:xxx:xxx:11::2</subnet>
      <vhid>4</vhid>
      <advskew>0</advskew>
      <advbase>1</advbase>
      <password>.*</password>
    </vip>
    <vip>
      <type>single</type>
      <subnet_bits>128</subnet_bits>
      <mode>ipalias</mode>
      <interface>opt1</interface>
      <descr>IF_WAN1_FW6-external</descr>
      <subnet>xxx:xxx:xxx::10</subnet>
      <vhid>4</vhid>
    </vip>
    <vip>
      <type>single</type>
      <subnet_bits>32</subnet_bits>
      <mode>carp</mode>
      <interface>opt2</interface>
      <descr>IF_WAN2_FW4</descr>
      <subnet>x.x.x.124</subnet>
      <vhid>3</vhid>
      <advskew>0</advskew>
      <advbase>1</advbase>
      <password>.*</password>
    </vip>
    <vip>
      <type>single</type>
      <subnet_bits>32</subnet_bits>
      <mode>ipalias</mode>
      <interface>opt2</interface>
      <descr>IF_WAN2_MAIL4</descr>
      <subnet>x.x.x.123</subnet>
      <vhid>3</vhid>
    </vip>
    <vip>
      <type>single</type>
      <subnet_bits>32</subnet_bits>
      <mode>ipalias</mode>
      <interface>opt2</interface>
      <descr>IF_WAN2_WWW4</descr>
      <subnet>x.x.x.122</subnet>
      <vhid>3</vhid>
    </vip>
    <vip>
      <type>single</type>
      <subnet_bits>128</subnet_bits>
      <mode>carp</mode>
      <interface>opt2</interface>
      <descr>IF_WAN2_FW6</descr>
      <subnet>xxx:xxx:xxx:26::2</subnet>
      <vhid>4</vhid>
      <advskew>0</advskew>
      <advbase>1</advbase>
      <password>.*</password>
    </vip>
    <vip>
      <type>single</type>
      <subnet_bits>128</subnet_bits>
      <mode>ipalias</mode>
      <interface>opt2</interface>
      <descr>IF_WAN2_FW6-external</descr>
      <subnet>xxx:xxx:xxx:3030::10</subnet>
      <vhid>4</vhid>
    </vip>
  </virtualip>
```

Any hints on how to fix this issue  without having to manually modify config.xml to delete the broken aliases, reboot and then recreate every single IP alias (there's just too many of them) would be greatly appreciated.

**Comment by AdSchellevis** [comment]
a broken config needs to be modified manually unfortunately, the model can't know which items have changed when there's no uuid assigned yet. so, download, edit, upload without reboot and inspect.

**Comment by Kishi85** [comment]
Okay, so i'll just have to download the config.xml and add the uuid attribute to every single vip entry?

This config was created on 20.7 first from scratch and has been upgraded through every available version using the UI since then, how can it be that the UUIDs are now missing? Shouldn't they've been added during one of the upgrades? 

Anyway, thanks again for the information i need to fix this manually so i'll give it a try.

**Comment by AdSchellevis** [comment]
or maybe easier, make sure the vhid's are consistent (only assign an alias with vhid when there's also an address with type carp defined).

**Comment by Kishi85** [comment]
That is currently the case but the UI parser (or maybe the migration job as that fails consistently?) does not seem to resolve the CARP definitions before the IP Aliases, therefore the above mentioned error. 

In config.xml there is always a VIP/VHID with type carp defined before any ipaliases with the same VHID (as seen above).

**Comment by AdSchellevis** [comment]
maybe a duplicate section in the config? vhid 2 doesn't exist in the configuration above.....

**Comment by Kishi85** [comment]
I've just tried to add the missing uuid's as you suggested and that lead to the same errors upon saving an ip alias, when trying to edit a CARP VIP i could not save again so i suspect that it is the CARP VIP entry that is broken in the first place leading to subsequent errors during VIP-config migration when upgrading the opnsense package. 

I've reduced my VIP config to a single CARP VIP and tried to upgrade but the Virtual-IP config migration from package opnsense still fails with just that single entry. This is the entry used (obfuscated):
```
<vip>
    <type>single</type>
    <subnet_bits>32</subnet_bits>
    <mode>carp</mode>
    <interface>opt1</interface>
    <descr>IF_WAN1_FW4</descr>
    <subnet>xxx.xxx.xxx.4</subnet>
    <vhid>3</vhid>
    <advskew>100</advskew>
    <advbase>1</advbase>
    <password>.*</password>
</vip>
```


After manually created a VIP entry on a new VM for testing an it looks like this in config.xml, so at least now I know what I have to put there to make it work (and ip aliases subsequently as well), which is modifying CARP entries to the following and adding a UUID to all the vip tags:
```
<vip uuid="29f4f85a-b5bd-45d1-ae7b-511e219ff009">
    <interface>opt1</interface>
    <mode>carp</mode>
    <subnet>xxx.xxx.xxx.4</subnet>
    <subnet_bits>32</subnet_bits>
    <gateway/>
    <noexpand>0</noexpand>
    <nobind>0</nobind>
    <password>.*</password>
    <vhid>3</vhid>
    <advbase>1</advbase>
    <advskew>100</advskew>
    <descr>IF_WAN1_FW4</descr>
</vip>
```

For what it's worth is that I think that there are some issues with the configuration migration for VIPs in the opnsense Package (I still haven't found the logs as to why it fails) but it should be managable now that know how to manually edit the config to a sane state.

**Comment by michaelroland** [comment]
Same here. To me it seems that the Virtual IP configuration is not changed during the update although upgrades would be required.

Configuration before/after upgrade:
```
  <virtualip>
    <vip>
      <type>single</type>
      <subnet_bits>28</subnet_bits>
      <mode>carp</mode>
      <interface>wan</interface>
      <descr>WAN = 100.100.100.82/28</descr>
      <subnet>100.100.100.82</subnet>
      <vhid>4</vhid>
      <advskew>10</advskew>
      <advbase>1</advbase>
      <password>abc123</password>
    </vip>
    <vip>
      <type>single</type>
      <subnet_bits>28</subnet_bits>
      <mode>ipalias</mode>
      <interface>wan</interface>
      <descr>WAN = 100.100.100.83/28</descr>
      <subnet>100.100.100.83</subnet>
      <vhid>4</vhid>
    </vip>
    <vip>
      <type>single</type>
      <subnet_bits>64</subnet_bits>
      <mode>carp</mode>
      <interface>wan</interface>
      <descr>WAN = 2001:100:100:100::2/64</descr>
      <subnet>2001:100:100:100::2</subnet>
      <vhid>6</vhid>
      <advskew>10</advskew>
      <advbase>1</advbase>
      <password>abc123</password>
    </vip>
```

Configuration after manually recreating VIP config (by manually copying all elements from the config dump into the UI):
```
  <virtualip version="1.0.0">
    <vip uuid="39a655df-375e-471f-8df9-0dd3717eebc8">
      <interface>wan</interface>
      <mode>carp</mode>
      <subnet>100.100.100.82</subnet>
      <subnet_bits>28</subnet_bits>
      <gateway/>
      <noexpand>0</noexpand>
      <nobind>0</nobind>
      <password>abc123</password>
      <vhid>4</vhid>
      <advbase>1</advbase>
      <advskew>10</advskew>
      <descr>WAN = 100.100.100.82/28</descr>
    </vip>
    <vip uuid="3fb7c11f-77ce-460c-9fe4-f9c5bbd849fc">
      <interface>wan</interface>
      <mode>ipalias</mode>
      <subnet>100.100.100.83</subnet>
      <subnet_bits>28</subnet_bits>
      <gateway/>
      <noexpand>0</noexpand>
      <nobind>0</nobind>
      <password/>
      <vhid>4</vhid>
      <advbase>1</advbase>
      <advskew>0</advskew>
      <descr>WAN = 100.100.100.83/28</descr>
    </vip>
    <vip uuid="8a524bbc-b38e-4b89-a0d1-90438ae0623e">
      <interface>wan</interface>
      <mode>ipalias</mode>
      <subnet>100.100.100.84</subnet>
      <subnet_bits>28</subnet_bits>
      <gateway/>
      <noexpand>0</noexpand>
      <nobind>0</nobind>
      <password/>
      <vhid>4</vhid>
      <advbase>1</advbase>
      <advskew>0</advskew>
      <descr>WAN = 100.100.100.84/28</descr>
    </vip>
    <vip uuid="acac2af3-4d48-4ce3-8b45-6831ba37b28b">
      <interface>wan</interface>
      <mode>carp</mode>
      <subnet>2001:100:100:100::2</subnet>
      <subnet_bits>64</subnet_bits>
      <gateway/>
      <noexpand>0</noexpand>
      <nobind>0</nobind>
      <password>abc123</password>
      <vhid>6</vhid>
      <advbase>1</advbase>
      <advskew>10</advskew>
      <descr>WAN = 2001:100:100:100::2/64</descr>
    </vip>
```

For me it looks as if the (manually recreated) configuration is the same as the old one (exact same order; just a few new fields + the version attribute for the virtualip tag + the uuid attribute for each vip entry).

Note that without manual re-configuration, the existing configuration seemed to work just fine. The problems just appeared when editing/adding virtual IPs. Before deleting and manually re-creating the vvirtual IPs, it was not possible to edit any of the virtual IPs (the UI elements remain empty upon clicking the Edit button) or to add new IPAliases for the existing CARP entries.

**Comment by Kishi85** [comment]
After further testing i'm still encountering issues during testing on a new demo install of opnsense, when editing (newly created) CARP VIPs as soon as there is an IP alias on that or another CARP VIP is involved, e.g. Nothing happens when pressing the save button upon changing the value of advbase. 

There has to be some kind of bug in the parsing logic or the model of the new MVC UI that breaks upon certain changes and/or on upgrading existing configurations with certain preconditions that i cannot grasp.

**Comment by Kishi85** [comment]
> After further testing i'm still encountering issues during testing on a new demo install of opnsense, when editing (newly created) CARP VIPs as soon as there is an IP alias on that or another CARP VIP involved, e.g. Nothing happens when pressing the save button upon changing the value of advbase.
> 
> There has to be some kind of bug in the parsing logic or the model of the new MVC UI that breaks upon certain changes and/or on upgrading existing configurations with certain preconditions that i cannot grasp.
> 
> Definitely not just an existing (not even broken?) config issue.

Steps to reproduce:

1. Use newly installed opnsense
2. Create first CARP VIP
3. Create second CARP VIP
4. Create IP alias on second CARP VIP
5. Edit advbase on either of the CARP VIPs
6. Press save on the edit dialog -> Nothing happens, Dialog stays open

**Comment by michaelroland** [comment]
Changing advbase (or other parameters) on the CARP entries works just fine for me. Only changing the address of existing entries fails with "VHID 4 must be defined on interface [...] as a CARP VIP first."

**Comment by Kishi85** [comment]
> Changing advbase (or other parameters) on the CARP entries works just fine for me. Only changing the address of existing IPAlias entries fails with "VHID 4 must be defined on interface [...] as a CARP VIP first." (the same works for the corresponding CARP entry itself).

I've now also managed to reach this error as well after manually updating every single entry in my config.xml to the format 23.1 uses using this simple python script:
```python
import uuid
import xmltodict


def find_carpvip(data, iface, vhid):
    for cvip in data['vip']:
        if cvip['mode'] == 'carp' and cvip['interface'] == iface and cvip['vhid'] == vhid:
            return cvip


with open('config.xml', 'r', encoding='utf-8') as f:
    config = xmltodict.parse(f.read())
    virtualip = config['opnsense']['virtualip']
    if '@version' not in virtualip:
        virtualip['@version'] = "1.0.0"

    for vip in virtualip['vip']:
        if '@uuid' not in vip:
            vip['@uuid'] = uuid.uuid4()

        if 'type' in vip:
            del vip['type']
            vip['gateway'] = None
            vip['nobind'] = 0
            vip['noexpand'] = 0

        if vip['mode'] == 'ipalias' and 'vhid' in vip:
            carpvip = find_carpvip(virtualip, vip['interface'], vip['vhid'])
            vip['advbase'] = carpvip['advbase']
            vip['advskew'] = carpvip['advskew']

    print(xmltodict.unparse({'virtualip': virtualip}, pretty=True).replace('<gateway></gateway>', '<gateway/>'))
```

Editing an IP alias the same 'VHID must be defined' error is shown. 
Additionally upon creating a new IP alias on the 'opt1' Interface with a VHID pressing save again does nothing, instead of an IP alias a CARP VIP gets somehow created on the never selected 'wan' Interface in the background that upon trying to delete on the UI gives the following API exception (Listing all defined IP aliases on CARP VIPs):
```
/usr/local/opnsense/mvc/app/models/OPNsense/Base/BaseModel.php:583: [OPNsense\Interfaces\Vip:vip.0e27476d-039b-4e21-9ca9-50068f692f44.vhid] VHID 3 must be defined on interface opt1 as a CARP VIP first.{3}
[OPNsense\Interfaces\Vip:vip.7bf2ba0a-be77-4593-b977-cfd35d326d07.vhid] VHID 3 must be defined on interface opt1 as a CARP VIP first.{3}
[OPNsense\Interfaces\Vip:vip.e5648fa2-65b6-44b6-a1e3-4e2ac595e338.vhid] VHID 3 must be defined on interface opt1 as a CARP VIP first.{3}
[OPNsense\Interfaces\Vip:vip.366a5fd4-7d4c-45a2-9f35-4fa8fc6cc5e4.vhid] VHID 3 must be defined on interface opt1 as a CARP VIP first.{3}
[OPNsense\Interfaces\Vip:vip.5d800c97-6e34-4432-ac65-11bbed8c39ab.vhid] VHID 3 must be defined on interface opt1 as a CARP VIP first.{3}
[OPNsense\Interfaces\Vip:vip.d95a5ee9-1a85-4287-bcfb-54303e192e85.vhid] VHID 3 must be defined on interface opt1 as a CARP VIP first.{3}
[OPNsense\Interfaces\Vip:vip.12b580a6-e34d-4a5b-8358-534870a148c0.vhid] VHID 3 must be defined on interface opt1 as a CARP VIP first.{3}
[OPNsense\Interfaces\Vip:vip.5640b3db-55ac-4362-8437-ce0b00b34220.vhid] VHID 3 must be defined on interface opt1 as a CARP VIP first.{3}
[OPNsense\Interfaces\Vip:vip.bb43ad92-15b4-4071-8f2d-18709742364b.vhid] VHID 3 must be defined on interface opt1 as a CARP VIP first.{3}
[OPNsense\Interfaces\Vip:vip.573f7ca6-8c75-4bad-81eb-1bbb80662736.vhid] VHID 4 must be defined on interface opt1 as a CARP VIP first.{4}
[OPNsense\Interfaces\Vip:vip.7c30f090-d002-47e4-9a53-85c179b74627.vhid] VHID 3 must be defined on interface opt2 as a CARP VIP first.{3}
[OPNsense\Interfaces\Vip:vip.b1969568-dfe5-42eb-8557-687684d7834a.vhid] VHID 3 must be defined on interface opt2 as a CARP VIP first.{3}
[OPNsense\Interfaces\Vip:vip.2d1e64f3-4ab7-4e70-8800-bb8f77255762.vhid] VHID 4 must be defined on interface opt2 as a CARP VIP first.{4}
[OPNsense\Interfaces\Vip:vip.9088a4ec-0d2a-40a1-9213-d5e3e28334a2.vhid] VHID 1 must be defined on interface opt3 as a CARP VIP first.{1}
[OPNsense\Interfaces\Vip:vip.c146c8fe-a599-4e48-be43-3af03743cdc4.vhid] VHID 2 must be defined on interface opt3 as a CARP VIP first.{2}
```
Oddly enough all of those VHIDs have a proper CARP VIP defined in config.xml (and the UI) but the BaseModel again does not seem to resolve this properly. This is now the same problem as my initial issue but with the full config.xml virtualip Section in the Format that 23.1 generates using the MVC UI. This same config worked perfectly until 23.1 but is now somehow no longer editable using the MVC UI (even with the updated config.xml format), though still not broken as configd still happily accepts and processes it.

P.S.: Another thing that I don't understand why it is necessary to have advbase and advskew in the IPalias definition as well on 23.1 as that is really only needed for setting up the CARP VIP itself.

**Comment by AdSchellevis** [comment]
@Kishi85 can you try https://github.com/opnsense/core/commit/4ef3c1fbe850274ec5a01e03025cbdf75d0382c8? 
```
opnsense-patch 4ef3c1f
```

**Comment by fichtner** [comment]
Thanks, I'll add this to 23.1.4 for today.
