### ISSUE TITLE
IPSec: local DNS resolution on VPN mobile clients 

### ISSUE THREAD

**Issue by igolman** [opnsense/core#6423]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x ] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x ] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

---

Hello everyone,

on `23.1.3_4` as well as on `23.1.1_2` firmware versions following behaviour is observed:
the `DNS split` values from `VPN: IPsec: Mobile Clients` generated at end-clients are incorrect.

_Example:_
WebUI setting: `VPN: IPsec: Mobile Clients>Split DNS`: `domain.one,domain.two` 
![dns_split](https://user-images.githubusercontent.com/1389334/225922502-e17d037d-cc33-499d-aca8-c5684f625085.png)
generates following in the `/conf/config.xml` file:
```
# grep split /conf/config.xml
<dns_split>domain.one,domain.two</dns_split>
```

however upon creating IpSec connection from a Client, the local `/etc/resolv.conf` will be changed to:
```
cat /etc/resolv.conf | grep search
search domain.onep^C
```

as a result DNS resolution on IpSec Client ist not working as intended.

**Expected behavior**
```
cat /etc/resolv.conf | grep search
search domain.one
search domain.two
```

**Environment**
OPNsense `23.1.3_4`  _(amd64,512684e0b)_, `23.1.1_2`  _(amd64, OpenSSL,6f57e7d75)_
Mac OSX _(as IPsec Clients)_: Ventura _(13.2.1)_, Monterey _(12.6.3)_

**Comment by AdSchellevis** [comment]
could be a client issue as well, best check the contents of `/usr/local/etc/strongswan.conf` on OPNsense first, the upstream documentation should help identify if the issue is on our end or elsewhere (https://docs.strongswan.org/docs/5.9/plugins/attr.html)

**Comment by igolman** [comment]
> best check the contents of /usr/local/etc/strongswan.conf on OPNsense first

looks correct:
```
# cat /usr/local/etc/strongswan.conf
# Automatically generated, please do not modify
starter {
    load_warning = no
}
charon {
    threads = 16
    ikesa_table_size = 32
    ikesa_table_segments = 4
    init_limit_half_open = 1000
    ignore_acquire_ts = yes
    syslog {
        identifier = charon
        daemon {
            ike_name = yes
        }
    }
    i_dont_care_about_security_and_use_aggressive_mode_psk = yes
    install_routes = no
    cisco_unity = yes
    plugins {
        attr {
            dns = 1.2.3.4,1.1.1.1,8.8.8.8
            28675 = domain.one,domain.two
            25 = domain.one,domain.two
        }
        xauth-pam {
            pam_service = ipsec
            session = no
            trim_email = yes
        }
    }
}

include strongswan.opnsense.d/*.conf
```

**Comment by stumbaumr** [comment]
https://github.com/opnsense/core/issues/3325 is related...

**Comment by igolman** [comment]
Please re-open.

**Comment by AdSchellevis** [comment]
We can always reopen when someone is planning to work on it (as mentioned earlier it could still be client issue as well). If it’s clear what we should change on our end, I don’t mind discussing options.
