### ISSUE TITLE
Web Proxy: Add strip_query_terms option to the config UI

### ISSUE THREAD

**Issue by Cyb3r-Monk** [opnsense/core#6429]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**

**Describe the solution you like**

By default, Squid doesn't log full URLs when the URL contains query terms. Query term logging can be enabled by adding the `strip_query_terms off` to the config as explained in the documentation: http://www.squid-cache.org/Doc/config/strip_query_terms/. 

Would be nice to have the option in the GUI.  

**Describe alternatives you considered**

**Additional context**

**Comment by anthonyalayo** [comment]
I would also like this. Could the issue be reopened?
