### ISSUE TITLE
OpenVPN Wizard referes to non-existing configuration section

### ISSUE THREAD

**Issue by 8191** [opnsense/core#643]
The section _System->Packages_ referred to in `src/wizard/openvpn.xml:965` does not exist.

```xml
<opnsensewizard>
    <!-- ... -->
<step>
    <!-- ... -->
    <field>                                                                 
        <type>text</type>                                                   
        <description>To be able to export client configurations, browse to System->Packages and install the OpenVPN Client Export package.</description>
    </field>
</step>
</opnsensewizard>
```

~~I could not find the section anymore with different name, maybe it was removed?~~
The section moved to VPN: OpenVPN: Client Export.

**Comment by fichtner** [comment]
Client export is installed by default, so this text can be safely stripped.

**Comment by fichtner** [comment]
For reference: the old packages framework was removed in favour of a redesign, it's now found under System: Firmware (plugins tab).

**Comment by 8191** [comment]
I think the text describes how to configure VPN clients, i.e. should refer to _VPN: OpenVPN: Client Export_ ?

**Comment by fichtner** [comment]
No it refers to how to install the package, but it's not a package :)

**Comment by 8191** [comment]
Ah, I see. So we can change it so something like _Browse to VPN: OpenVPN: Client Export to generate configuration packages for your OpenVPN clients._ ?

**Comment by fichtner** [comment]
I would zap the text, because it didn't say that before, but I'll merge whatever you suggest, deal? :)

**Comment by fabianfrz** [comment]
I vote for zap the text
