### ISSUE TITLE
OpenVPN does not listen to UDP4 and UDP6 at same time

### ISSUE THREAD

**Issue by svenkatdsbe** [opnsense/core#6431]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [ X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [ X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**
When I configure an OpenVPN server on _interface localhost_, _local port 1194_ and ...

protocol UDP4 - the server is listening on **udp4/[127.0.0.1:1194-*:*]**
protocol UDP6 - the server is listening on **udp6/[::1:1193-*:*]**

That's fine. But with ...

protocol UDP - the server is also listening only on **udp4/[127.0.0.1:1193-*:*]**

Only in combination with _interface any_ and ...

protocol UDP - the server is also listening on both (UDP4 and UDP6) **udp46/[*:1193-*:*]**

I first seen this bug: 23.1.2 (I am new to OPNsense and have not used it before)

**Expected behavior**
I would expect that a server with protocol _UDP_ should listen to both _UDP4_ and _UDP6_ even on a single interface like _localhost_.

**Screenshots**

none

**Relevant log files**

none

**Additional context**

none

**Environment**
OPNsense  23.1.2 (amd64)

**Comment by svenkatdsbe** [comment]
Cool - a bot that marks all new bug reports as incomplete

**Comment by fichtner** [comment]
beep beep it's incomplete because you didn't use the template beep beep

beep beep the feature is a limitation of openvpn beep beep

**Comment by svenkatdsbe** [comment]
I understand. The available configuration options suggested to me that this was possible.

Perhaps the _UDP_ option can only be displayed when _any_ is selected as the interface.

**Comment by fichtner** [comment]
The help text in the GUI states:

> Select the protocol family to be used. Note that using both families with UDP/TCP does not work with an explicit interface as OpenVPN does not support listening to more than one specified IP address. In this case IPv4 is currently assumed.


Cheers,
Franco

**Comment by svenkatdsbe** [comment]
Thank you for your quick feedback

Regards
Sven
