### ISSUE TITLE
[FR] Sort interfaces under Reporting/Health in dropdpown lists

### ISSUE THREAD

**Issue by FrankWeis** [opnsense/core#6434]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**
If you have a lot of interfaces (in my case >100) the fact that interface names are not sorted makes the dropdown lists very hard to use in the Packets and Traffic tabs on the Reporting/Health page.

**Describe the solution you like**
Sort the entries alphabetically

**Additional context**

![image](https://user-images.githubusercontent.com/51480121/226913016-39a168cf-6d27-44fe-b561-16b15f1a55ea.png)

**Comment by AdSchellevis** [comment]
@FrankWeis https://github.com/opnsense/core/commit/9f2ad523b58e580c0fe90db03092d748e2ce23ec should do the trick.

```
opnsense-patch 9f2ad52
```
