### ISSUE TITLE
OpenVPN widget broken

### ISSUE THREAD

**Issue by Unit764** [opnsense/core#6437]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:
- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**
OpenVPN widget appears broken after latest update.  Server side it shows all connections down (when they are actually up).  Client side show no information (blank widget)

*Tip*: to validate your setup was working with the previous version, use opnsense-revert (https://docs.opnsense.org/manual/opnsense_tools.html#opnsense-revert)

**To Reproduce**
1. Go to 'Lobby > Dashboard'
2. Click on 'Add widget'
3. Scroll down to 'OpenVPN'
4. Server side shows all connections down.  Client side shows no information.

**Expected behavior**
Server Side: Widget should show green arrows for up and red arrows for down.
Client Side: Widget should show connection information.

**Describe alternatives you considered**
I need to manually connect to devices on the other side of the VPN to check if it is up and working.

**Screenshots**
SERVER WIDGET:
![OpenVPNWidget](https://user-images.githubusercontent.com/91616063/227231804-4c9f7d59-246f-4344-a86d-2f61feb5888e.png)
CLIENT WIDGET:
![OpenVpnWidgetClient](https://user-images.githubusercontent.com/91616063/227231819-f581e303-c2e4-4f05-ad30-bed6d2fed5a2.png)

**Relevant log files**
None

**Additional context**
None

**Environment**
OPNsense 23.1.4_1-amd64
FreeBSD 13.1-RELEASE-p7
OpenSSL 1.1.1t 7 Feb 2023
Intel i5

**Comment by Unit764** [comment]
**Environment**
OPNsense 23.1.5_2-amd64
FreeBSD 13.1-RELEASE-p7
OpenSSL 1.1.1t 7 Feb 2023

After update, Client widget is displaying the correct information.
![ClientWorking20230330](https://user-images.githubusercontent.com/91616063/228864125-dfcf5b4c-5281-47f2-b987-29c4c7f3759b.png)

Server widget still not displaying correct information.

**Comment by fichtner** [comment]
Probably https://github.com/opnsense/core/commit/a0c8016b2f0129d869f6eb8c4ffa0382ec3d19e7

**Comment by Unit764** [comment]
OPNsense 23.1.5_4-amd64
FreeBSD 13.1-RELEASE-p7
OpenSSL 1.1.1t 7 Feb 2023
Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (4 cores, 8 threads)

OpenVPN Server Widget still not showing connection status correctly, showing red arrows where tunnels are up (should be green arrows).  Real / Virtual IP information is correct.  There also seems to be an extra space between VPN Server information making the widget very long (longer than before).

![OpnVpnWidgit20230403](https://user-images.githubusercontent.com/91616063/229524909-7b1eb489-11e8-47b1-9625-0094bed7936e.png)

**Comment by Unit764** [comment]
OPNsense 23.1.6-amd64
FreeBSD 13.1-RELEASE-p7
OpenSSL 1.1.1t 7 Feb 2023
CPU type | Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (4 cores, 8 threads)

After update, same issue.  All arrows showing red instead of green when connected on OpenVPN server widget.

**Comment by Unit764** [comment]
OPNsense 23.1.7_2-amd64
FreeBSD 13.1-RELEASE-p7
OpenSSL 1.1.1t 7 Feb 2023
CPU type | Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (4 cores, 8 threads)

After update, issue is resolved.  All arrows are showing correct color status on OpenVPN server widget.  Spacing between servers listed in status could be shrunk for more minimal display.  But that should probably be raised as a separate feature request.

Happy day.
