### ISSUE TITLE
AutoUpdate important Security Updates

### ISSUE THREAD

**Issue by SilentGlasses** [opnsense/core#6441]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**

Not related to a problem.

**Describe the solution you like**

Looking at how much security concerns are running around, it would be nice to be able to set a flag to install security updates and restart those services as needed to ensure there are no long delays between a patch being released and it being installed.

**Describe alternatives you considered**

No alternatives.

**Additional context**

Nothing extra to add.

**Comment by dstr-wpd** [comment]
I have running those predefined cronjobs that are installing firmware updates automatically. It is not installing major releases, which is perfectly fine for me.
