### ISSUE TITLE
More favorable/natural handling of stale TCP connections

### ISSUE THREAD

**Issue by paul-palmer** [opnsense/core#6445]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**

More favorable/natural handling of stale TCP connections.

Today when a TCP connection ages out of the state table or the firewall is restarted, the packets from existing connections will no longer match a connection entry and will not be selected by any of the user-provided rules. The default behavior for such packets is to be dropped/blocked. This causes problems for some applications which are slow to discover that their packets are not arriving at their destination. To some extent this can be worked around by enabling keep-alive packets on the socket, but this adds complexity and still may not be fast enough. In many cases, we do not have the access to modify the application to enable keep-alive packets. So, the end experience is that applications will hang for long periods of time, the root cause is often difficult to diagnose, and may require a complete restart of the application to recover.

**Describe the solution you like**

A solution would be to change state violation behavior so that any such packet would not be immediately dropped, but would then be processed against the firewall rules and if the action would have been "pass" to then process the packet with a reject action instead of a block action. This behavior would be consistent with the expected network behavior if the firewall was not in the network path and the remote server was rebooted.

**Describe alternatives you considered**

The simplest alternative I have considered, would be to add a feature flag that changes the "Default deny / state violation rule" to reject packets instead of blocking them as it does today. This is not ideal as we personally would prefer rejects only for state violations and then only for connections between two networks that we control (that is, not from traffic originating from the Internet).

Another approach would add a selectable option to each firewall rule (maybe called "Reject state violations") for TCP rules. When enabled, a hidden rule could be generated using the same rule criteria, except the hidden rule would be stateless and have the reject action. (I think this could work, but have not tested it exhaustively by manually adding such rules myself. And to be honest, it feels kludgy).

**Additional context**

None at this time.

**Comment by fichtner** [comment]
Set state none on firewall rule? 😉

**Comment by paul-palmer** [comment]
A reasonable suggestion and simple enough for me to test...

> Set state none on firewall rule? 😉
