### ISSUE TITLE
proxy: enable/disable cache_store_log in GUI

### ISSUE THREAD

**Issue by fichtner** [opnsense/core#645]
If enabled, point to /var/log/squid/store.log

**Comment by AdSchellevis** [comment]
Its a bug :) the attribute is in there expecting squid.conf to default to /var/log/squid/store.log
Will fix this and close.

**Comment by fichtner** [comment]
I feel bad for not fixing this... I grep'ed for the config setting only, thought it was unconditionally and not available on the GUI. Sorry and thank you! :)

**Comment by AdSchellevis** [comment]
No problem, it wasn't a lot of work fixing it :)
