### ISSUE TITLE
More friendly filename for GDrive backups

### ISSUE THREAD

**Issue by vik-patel** [opnsense/core#6455]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**

Currently unix time is appended ... looking for a human readable time

**Describe the solution you like**

please can you update line in "/usr/local/opnsense/mvc/app/library/OPNsense/Backup/GDrive.php"

from:
`$target_filename = $fileprefix . time() . ".xml";`
to
`$target_filename = $fileprefix . date("c",time()) . ".xml";`

**Describe alternatives you considered**

None

**Additional context**

Thx

**Comment by williamdes** [comment]
I also think `2023-06-03T21:11:54+00:00` is more readable, is this a change other users want ?
