### ISSUE TITLE
How can I install GOST encryption algorithms on OpenSense?

### ISSUE THREAD

**Issue by Mirlitus** [opnsense/core#6457]
It is necessary that algorithms according to GOST (Russia) be added to the list of available encryption algorithms in OpenSense.

Maybe someone knows about this issue?

**Comment by fichtner** [comment]
To my knowledge GOST option is already supported by openssl package:

```
# pkg info openssl | grep GOST
	GOST           : on
```

**Comment by Mirlitus** [comment]
> To my knowledge GOST option is already supported by openssl package:

Fine. What needs to be done with the OpenSense repositories so that GOST support is added to the system?
Or do you not need to do anything with the repositories, and just install the correct OpenSSL with GOST support?

**Comment by fichtner** [comment]
You are not asking a specific question and/or do not know how GOST works in practice. I cannot help you with this.

**Comment by Mirlitus** [comment]
> You are not asking a specific question and/or do not know how GOST works in practice. I cannot help you with this.

It is necessary that 3 GOST algorithms be added to OpenVPN when adding a server and a client.
In the interface, this is VPN --> OpenVPN --> Servers/Clients.
I will be grateful for advice.

**Comment by fichtner** [comment]
https://techglimpse.com/solved-openssl-library-has-no-gost-support/

**Comment by fichtner** [comment]
Likely, yes.

**Comment by Mirlitus** [comment]
> Likely, yes.

Tell me please:
1) What commands and in what order should I enter to install the required version of OpenSSL with GOST support from this repository? Start from the moment I installed FreeBSD in the virtual machine.

I think so:

pkg update && pkg upgrade
pkg install git gmake pkgconf gettext-tools openssl
git clone https://github.com/gost-engine/engine.git
cd engine
git checkout openssl_1_1_1
make
make install
mkdir -p /usr/local/lib/engines-1.1
ln -s /usr/local/lib/libgost.so /usr/local/lib/engines-1.1/gost.so

Then open the file /usr/local/etc/ssl/openssl.cnf on the FreeBSD machine and add the following lines at the beginning of the file:

openssl_conf = openssl_def
[openssl_def]
engines = engine_section
[engine_section]
gost = gost_section
[gost_section]
engine_id = gost
dynamic_path = /usr/local/lib/engines-1.1/gost.so
default_algorithms = ALL
CRYPT_PARAMS = id-Gost28147-89-CryptoPro-A-ParamSet

2) Do I need to change something in the interface of the OpenSense itself (in particular, the core repository), or should the algorithms themselves be loaded into the interface after installing OpenSSL on FreeBSD?

I will be very grateful.

**Comment by kulikov-a** [comment]
@Mirlitus i think you can install gost-engine from ports (https://github.com/opnsense/ports/tree/master/security/gost-engine) (https://docs.opnsense.org/manual/software_included.html#the-ports-tree). keep in mind that it will be `dynamic_path = /usr/local/lib/engines-1.1/libgost.so` iirc. but.. i dont think that OPNSense uses a patched openvpn with the GOST algos support.
there is a commercial "FSTEC-certified" opnsene-based product (can be googled. will not name it here) that offers (don't no if\how it works) "os-gostvpn"

**Comment by hotmax22** [comment]
Will there be an os-gostvpn plugin?
