### ISSUE TITLE
firmware: report running CLI update in GUI

### ISSUE THREAD

**Issue by fabianfrz** [opnsense/core#646]

**Comment by fichtner** [comment]
This is intentional, because the console update runs no background wrapper. This acts as a fail safe for whe GUI upgrades may break. Adding the same wrappers for the console increases said risk unnecessarily?

**Comment by fabianfrz** [comment]
it can be written to a file while using standard output so the webinterface can see it too

**Comment by fabianfrz** [comment]
https://www.freebsd.org/cgi/man.cgi?query=tee&sektion=1

**Comment by fichtner** [comment]
The backend is easy, the additional JavaScript code in the firmware page I'm not liking.

Maybe this should be looked at differently: providing a persistent upgrade logs facility?

**Comment by fabianfrz** [comment]
I do not think this is a good idea because it will grow with every update and it does not provide any useful information worth to store them persistently - maybe just show the information, that something is working in the background.

**Comment by fichtner** [comment]
Sounds reasonable, let's pin this down for 16.7, thanks :)

**Comment by fichtner** [comment]
I've worked on this... it's a real pain to do. Even file locking using flock(1) subtly fails because when the webgui restarts it inherits the write-lock, FD_CLOEXEC is needed but not supported, so that either means patching flock or adding even more wrappers to the firmware subsystem...

**Comment by fichtner** [comment]
I've added more wrappers ;) see 7370fe2e1d07fc4ce213244d2a33be2744d6c83d a175a7457196b3c76549c486d10ca3c6bfc7f259 d111ea445835eb7914265f53d47e94226f4ba713

To be merged after 16.1.16 is released.

**Comment by fabianfrz** [comment]
:+1:

**Comment by fichtner** [comment]
Testing is better in master....
