### ISSUE TITLE
IPv6 Gateway is missing the checkbox for far gateways

### ISSUE THREAD

**Issue by pabe-github** [opnsense/core#6461]
**Describe the bug**

When adding or editing an IPv6 Gateway, the checkbox for Far Gateways is missing

**To Reproduce**

1. Go to 'System -> Gateways -> Single"
2. Click on '+' to add a new Gateway
3. Notice while the default settings are loaded (Address Family = IPv4), the "Far Gateway" checkbox is visible
4. Change the Address Family to IPv6
5. Notice the missing "Far Gateway" checkbox

**Expected behavior**

Have the checkbox visible and usable for IPv6

**Screenshots**

![image](https://user-images.githubusercontent.com/42635243/229123925-17d0f792-1705-47bf-8cd6-b6539dec9914.png)
![image](https://user-images.githubusercontent.com/42635243/229123985-2be8942a-22fb-4fa5-b1bc-3e9beae763a0.png)

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 23.1.5_4 (amd64, OpenSSL).

**Comment by fichtner** [comment]
This is not an acceptable configuration for IPv6.
