### ISSUE TITLE
Setup Wizard omits /31 netmask from dropdown list

### ISSUE THREAD

**Issue by thowe** [opnsense/core#6463]
**Setup Wizard Netmask Dropdowns omit /31**

When selecting IPv4 network address on interfaces in the setup Wizard,
the netmask selector omits the 31 option as a netmask.
There have been some /31 fixes in the past, but this appears to have been missed.

There may also be functional fixes that need to go with this, but I was unable to test this.

OPNsense 23.1.4_1-amd64
FreeBSD 13.1-RELEASE-p7
OpenSSL 1.1.1t  7 Feb 2023

**Comment by fichtner** [comment]
https://github.com/opnsense/core/commit/866b48028b87b32b0b3d9940a62e342f5d13ea0a should do the trick?


Cheers,
Franco
