### ISSUE TITLE
Allow unbound to use TCP for upstream DNS requests (Domain override) instead of UDP

### ISSUE THREAD

**Issue by somova** [opnsense/core#6465]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**

In my configuration unbound uses domain overrides through an IPsec tunnel. As described in the following forum discussion the IPsec tunnel has an issue with UDP communication. Telling unbound to use TCP for specific domain overrides solves the problem that DNS requests through the IPsec tunnel time out.

See link: https://forum.opnsense.org/index.php?topic=32997.0

**Describe the solution you like**

Allow users to configure to use TCP for communication per domain override in the WebUI. This can be done by adding the parameter "forward-tcp-upstream: yes" in the domain override configuration section (see example below).

```
root@opnsense:/var/unbound/etc # cat domainoverrides.conf 
forward-zone:
  name: "fritz.box"
  forward-addr: 192.168.1.1
  forward-tcp-upstream: yes
root@opnsense-host:/var/unbound/etc # 
```

**Describe alternatives you considered**

The only alternative will be to solve the IPsec issue as discussed in the forum (see link above)

**Comment by AdSchellevis** [comment]
https://github.com/opnsense/core/commit/a556df4a85df41db80b4b4ec22e9f9bfc79f2925 should do the trick

**Comment by somova** [comment]
Many thanks.
