### ISSUE TITLE
`netflow` get error "Invalid argument" when interface name has `.`

### ISSUE THREAD

**Issue by steelywing** [opnsense/core#6468]
I have a VLAN interface with name `vlan0.410`, when NetFlow start, it has error `ngctl: send msg: Invalid argument`

```
root@OPNsense:~ # /usr/local/etc/rc.d/netflow restart
setup vlan0.410
ngctl: send msg: Invalid argument
error vlan0.410: cannot create netflow node for vlan0.410
```

I found the `netflow` script call `mkpeer` like this

```
ngctl mkpeer vlan0.410: netflow lower iface5
```

but the VLAN interface name is `vlan0_410`

```
root@OPNsense:~ # ngctl list
...
  Name: vlan0_401       Type: ether           ID: 00000005   Num hooks: 0
```

Relate to #6359

**Comment by AdSchellevis** [comment]
not very useful to open a new ticket for the same issue (https://github.com/opnsense/core/issues/6359)
