### ISSUE TITLE
Bug: configd error

### ISSUE THREAD

**Issue by fabianfrz** [opnsense/core#647]
Having this in the log after reboot (i upgraded to the new dev)

```
configd.py: [1a23f4df-5346-4cfb-b90a-2642847ec32f] Inline action failed at Traceback (most recent call last):
File "/usr/local/opnsense/service/modules/processhandler.py", line 488, in execute return ph_inline_actions.execute(self, inline_act_parameters)
File "/usr/local/opnsense/service/modules/ph_inline_actions.py", line 52, in execute filenames = tmpl.generate(parameters)
File "/usr/local/opnsense/service/modules/template.py", line 300, in generate for filename in self._generate(template_name, create_directory):
File "/usr/local/opnsense/service/modules/template.py", line 248, in _generate content = j2_page.render(cnf_data) File "/usr/local/lib/python2.7/site-packages/jinja2/environment.py", line 989, in render return self.environment.handle_exception(exc_info, True)
File "/usr/local/lib/python2.7/site-packages/jinja2/environment.py", line 754, in handle_exception reraise(exc_type, exc_value, tb)
File "/usr/local/opnsense/service/modules/../template
```

via: https://forum.opnsense.org/index.php?topic=2016.0

**Comment by fichtner** [comment]
Does this repeat or is it a one-time thing?

**Comment by fabianfrz** [comment]
repeats at least after reboot

**Comment by fichtner** [comment]
There's probably more context that configd spits out, we recently fixed something similar:

```
Dec 26 23:32:27	configd.py: [1c5b9cf7-35f6-4141-a696-feb225082ab3] Inline action failed at Traceback (most recent call last):
File "/usr/local/opnsense/service/modules/processhandler.py", line 488, in execute return ph_inline_actions.execute(self, inline_act_parameters)
File "/usr/local/opnsense/service/modules/ph_inline_actions.py", line 52, in execute filenames = tmpl.generate(parameters)
File "/usr/local/opnsense/service/modules/template.py", line 296, in generate for filename in self._generate(template_name, create_directory):
File "/usr/local/opnsense/service/modules/template.py", line 226, in _generate new_filename = filename.replace('[%s]' % target_filter, target_filters[target_filter][key])
TypeError: expected a string or other character buffer object
Dec 26 23:32:27	configd.py: generate template container OPNsense.Captiveportal
Dec 26 23:32:27	configd.py: generate template container OPNsense
```

See: https://github.com/opnsense/core/commit/51724d293c3eaf9ee1de5ec8a3f7563bb936a141

**Comment by fichtner** [comment]
This looks suspicious... /usr/local/opnsense/service/modules/../template

Do you have any custom templates in there?

**Comment by fabianfrz** [comment]
no - i changed nothing in this directory but the line happens between this lines in the log
```
Jan 11 14:07:09 	configd.py: generate template container OPNsense.Sample
```
and 
```
Jan 11 14:07:09 	kernel: ipfw2 (+ipv6) initialized, divert loadable, nat loadable, default to accept, logging disabled
```

**Comment by fichtner** [comment]
Aha, do you have the os-helloworld plugin installed? Will this error go away when you remove it?

You can increase the amount of characters logged for the traceback here:

https://github.com/opnsense/core/blob/9fe4591d0897b66c3a92099b7b956f24cbcdae4b/src/opnsense/service/modules/processhandler.py#L469

**Comment by fichtner** [comment]
No, it's actually another sample set. It can probably be removed safely, but let's get the full traceback to be sure.

**Comment by fabianfrz** [comment]
no the plugin is not installed os-helloworld is not installed

**Comment by fabianfrz** [comment]
disabled some daemons - no success
restarted some daemons - no success

**Comment by fichtner** [comment]
I'll need the full python traceback :D it's just about those Sample templates I think.

**Comment by fichtner** [comment]
(and it can only ever happen on reboot as far as I can see)

**Comment by fabianfrz** [comment]
how to crate a full traceback as the log does not contain one - it does not even show wher the error comes from

**Comment by fichtner** [comment]
See my code link for where to increase the syslog dump size above :)

**Comment by fabianfrz** [comment]
ok found the configd call responsible for the error (can reproduce the error with this command)
```
configctl template reload "*"
```

**Comment by fabianfrz** [comment]
it really has to do with the template OPNsense.Sample

**Comment by fichtner** [comment]
So far I already figured, it's only triggered once on bootup, never again. It's supposed to recurse into every template, but something in the Sample package fails. Still need the traceback :D

**Comment by fabianfrz** [comment]
i increased it to 4096 but I do not get more output...

**Comment by fichtner** [comment]
After reboot or manually? If manually, you'd need

    # service configd restart

**Comment by fabianfrz** [comment]
I rebooted the VM

**Comment by fichtner** [comment]
Let's leave this for Ad, I don't know how to debug this further without a way to trigger it locally.

**Comment by fabianfrz** [comment]
I deleted "+TARGETS" and the error was gone ;)

**Comment by azdps** [comment]
Just wanted to add that I get the same error everytime I reboot opnsense. i'm using OPNsense 15.7.23-amd64. I'm attaching my entire log right after a reboot.

[Complete Bootup Log.txt](https://github.com/opnsense/core/files/87650/Complete.Bootup.Log.txt)

**Comment by fabianfrz** [comment]
@azdps I read in your log file that you also have issue #631

**Comment by azdps** [comment]
Just updated to OPNsense 15.7.24-amd64. I'm assuming you're still working on this issue since this bug isn't closed. I'm attaching my System --> Log file output. Has very similar error.

[System Log.txt](https://github.com/opnsense/core/files/89640/System.Log.txt)

**Comment by fichtner** [comment]
@azdps I think this has already been pinned down to a benign sample plugin. Will be fixed for 16.1, but it has no ill effects on the running system. :)

**Comment by fichtner** [comment]
@AdSchellevis this was fixed in eec35a3cf175299 right?

**Comment by AdSchellevis** [comment]
@fichtner yes, and the next commit moves the sample out of the way :)

**Comment by fichtner** [comment]
Alright, thanks. I'll close and let the forum know.
