### ISSUE TITLE
Firewall groups explicit ordering

### ISSUE THREAD

**Issue by erlendk** [opnsense/core#6471]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**

I would like to be able to set the internal priority between firewall groups in an explicit way, so that when an interface is a member of more than one group, the rules are applied in an order not determined by the name of the groups, but by their given priority.

Right now the priority between firewall groups seems to be based on the ascending alphabetical ordering between group names.

**Describe the solution you like**

In the "Firewall: Groups" page, I would like to be able to reorder groups. Possible solutions could be drag-and-drop or arrows to move groups up and down, or maybe a "Move selected groups after this group"-button, that would be more in line with the firewall rules page. The groups should (still) be listed in their applied order, and this should also be communicated on the page.

**Describe alternatives you considered**

N/A

**Additional context**

 The experienced alphabetical ordering is also backed by this [forum post](https://forum.opnsense.org/index.php?topic=21808.msg102919#msg102919).

**Comment by AdSchellevis** [comment]
It might be an idea to combine this with the MVC migration in https://github.com/opnsense/core/issues/6385 and add a priority field, explicit choices are certainly better than assumptions.

**Comment by fichtner** [comment]
In general this sounds sane, but I also think that this might be more work than worth it/prepending a priority to the name itself.

**Comment by AdSchellevis** [comment]
Let's keep it on the wishlist for now, we can remove it if the amount of work doesn't warrant the change later.

**Comment by AdSchellevis** [comment]
implemented in https://github.com/opnsense/core/commit/8e197ff73ee3412696110b3ff668598d9c10b2e9
