### ISSUE TITLE
IPsec widget shows "Note: There are no configured IPsec Tunnels"

### ISSUE THREAD

**Issue by ahaase-c4u** [opnsense/core#6472]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

When configuring an IPsec connection via the new MVC, tunnel comes up correctly, but widget doesn't show either configured connection or connection status.

**To Reproduce**

1. Go to VPN -> IPsec -> Connections [new]
2. Configure connection as stated in https://docs.opnsense.org/manual/how-tos/ipsec-s2s-conn.html
3. Check "Enable IPsec" and Apply
4. Check "Connection status" to see the connection up and running
5. Go to dashboard, IPsec widget shows "Note: There are no configured IPsec Tunnels"

**Expected behavior**

Widget should show the configured and running connection.

**Describe alternatives you considered**

Bug is similiar to #6297, but here it is no mobile connection and the fix mentioned there seems to not work here.

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 23.1.5_4 (amd64, OpenSSL).

**Comment by AdSchellevis** [comment]
can you try to change this to `if (true) {` ?

https://github.com/opnsense/core/blob/958ff5b7cab6874e224a2fc3f08c8c89564eed17/src/www/widgets/widgets/ipsec.widget.php#L77

If that's the only issue, the fix should be simple

**Comment by ahaase-c4u** [comment]
Doing so, let's the mentioned message disappear. But now I see 0 tunnels as active and 0 tunnels as inactive. So, it's a little better, but still not correct.
<img width="712" alt="Bildschirm­foto 2023-04-04 um 16 15 54" src="https://user-images.githubusercontent.com/42471048/229821201-1b0ed17e-3453-42d1-9497-a91731cb6b8c.png">

**Comment by AdSchellevis** [comment]
ah, same here https://github.com/opnsense/core/blob/958ff5b7cab6874e224a2fc3f08c8c89564eed17/src/www/widgets/widgets/ipsec.widget.php#L39

The widget isn't really build for the new code, but maybe we're lucky

**Comment by ahaase-c4u** [comment]
Now it looks good.

<img width="708" alt="Bildschirm­foto 2023-04-04 um 16 26 16" src="https://user-images.githubusercontent.com/42471048/229824158-6fb5b85a-e630-4b76-b67b-ea5359b9ae34.png">
