### ISSUE TITLE
IPSEC must stay on master node

### ISSUE THREAD

**Issue by ouafnico** [opnsense/core#6473]
Hi team,

**Description**

Actually I'm using a lot of clusters of Opnsense (master and backup), and IPSEC tunnels.

In all VLANS I'm using, the gateway for clients is a virtual address managed by opnsense, and hosted on the master node.

I have configured the IPSEC tunnel to use the "VIP" address of WAN interface, as interface in the IPSEC phase 1 configuration.

When the cluster is changing of master, sometimes, the ipsec stays on the previous master.

**Describe the solution you like**

There is no direct way actually to configure opnsense to start the IPSEC tunnel only on the master node.

There is no option for this on the IPSEC section, and very often, the phase 1 and 2 of IPSEC is started on the BACKUP node, and not on the MASTER.
Sometime, the phase 1 is connected on both nodes.

It result an asymetric routage and associated problems.

**Describe alternatives you considered**

- A simple option on the IPSEC configuration to start only when MASTER ?

- Any way to create automatisations when switching mode (BACKUP -> MASTER, or MASTER -> BACKUP) ?
  We would be able to tel :
  - MASTER -> BACKUP : Stop ipsec
  - BACKUP > MASTER : Start ipsec

Any help, ideas, are appreciated.

Thanks

**Comment by mimugmail** [comment]
Tick Disable MOBIKE in Phase 1

**Comment by ouafnico** [comment]
> Tick Disable MOBIKE in Phase 1

Already tried, but no changes

**Comment by stumbaumr** [comment]
This could be related here... https://github.com/opnsense/core/issues/3708
