### ISSUE TITLE
IPV6 Routing problem on LAN if re0

### ISSUE THREAD

**Issue by agh1701** [opnsense/core#6475]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [ x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x ] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

The simplest description is that i cannot pint the router using ipv6.  needless to say I cannot contact the internet via ipv6. 23.1.4 worked, other prior 23.1.v versions also had the same problem.  22.7.x versions worked.
Ping for client:
   to router LAN re0 2603:: address              No
   to router LAN re0 fe80:: address               Yes
   to any other client Lan 2603:: Address         Yes
   to any internet ipv6 address                        No
   
Ping from router:
   to router LAN re0 2603:: address             No
   to router LAN re0 fe80:: address              Yes
   to any client LAN 2603::                              No   ping: UDP connect: Network is unreachable
   to any internet ipv6 address                       Yes   with DNS name resolution

The router WAN re1 is fully functional.
The router LAN re0 ISP assigned address is not honored.

**To Reproduce**

1. Install opnsense v23.1.5_4
2. restore config
3. no ipv6 routing

**Expected behavior**

IPV6 should route.

**Describe alternatives you considered**

firewall rules look good and worked on 22.7.x

**Screenshots**
![Screenshot 2023-04-01 090148](https://user-images.githubusercontent.com/42355088/229943931-38b7bd67-6151-4c4a-8f50-f4da6dad45cc.jpg)

**Relevant log files**
[glog.txt](https://github.com/opnsense/core/files/11153916/glog.txt)

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 23.1.5_4 (amd64, OpenSSL).
Zotac n5105
Network realtek

**Comment by agh1701** [comment]
I notice this report [https://github.com/opnsense/core/issues/6435](url) in Wich the user is having the same trouble on the wan interface. in the other case the interface is vmn0 and my trouble is on the lan re(0).  Could there be and ipv6 initialization problem on any 0(zero) interface or the first interface.

**Comment by AdSchellevis** [comment]
If `23.1.4` did work, I would try to revert the base package to that version first and restart, the report doesn't contain a lot of relevant details, the amount of changes between `23.1.4` and  `23.1.5_4` are quite limited.

```
opnsense-revert -r  23.1.4 opnsense
```

(https://docs.opnsense.org/manual/opnsense_tools.html#opnsense-revert)

**Comment by agh1701** [comment]
Thanks, I reverted and ipv6 was fully function immediately.  I also rebooted and ipv6 is functional.  You mention lack of info.  is the attached general log(glog.txt) not helpful?  It contains I believe relevant errors.

**Comment by fichtner** [comment]
Immediately as in without reconfiguration right after revert. Usually it’s easy to find these things if reports are clear but here it isn’t.

The most likely change is https://github.com/opnsense/core/commit/eec08e055028674114b7d2e763b35d87fe7bd64e but I fail to see what could be going wrong unless radvd is *still* buggy.

**Comment by agh1701** [comment]
I am not sure how radvd affects the LAN port.  Ifconfig shows the 2006:: address assigned by my ISP on the LAN interface yet, a ping from the LAN has no response and a ping from the router shows “ping: UDP connect: Network is unreachable”.  Why is the LAN interface ignoring the address?  Could this be a kernel problem?

**Comment by fichtner** [comment]
I fear the questions here are not representative of the issue at hand. Debugging IPv6 starts with posting your WAN config and diagnosing if WAN is connected to the upstream router and if it has a GUA to talk to the Internet. After that we can switch to the LAN side. ;)

**Comment by agh1701** [comment]
You might want to reread my problem description.  My WAN functions correctly.  from the opnsense console I can ping any address on the internet by IPV6 address or by DNS name.  From the opnsense console a ping to the LAN address(or any LAN address) yields “ping: UDP connect: Network is unreachable”.  It seems like the LAN interface is ignoring its own address.

**Comment by fichtner** [comment]
Sure, WAN info is still completely missing. I’m writing this for you and anyone else later jumping into this with „I have the same problem“ and „why was this not fixed?“

**Comment by Sot3** [comment]
I've been having this same issue (router has IPv6 connectivity but LAN hosts don't) on and off for several of the last releases and posted about it in the community forums but got little interest.  I'm not entirely convinced that it's version-specific rather than just a sporadic issue.  But packet traces on the LAN interface clearly show that the local clients have valid IPv6 addresses but every SYN packet they deliver to the router goes unanswered.

I will be more than happy to share whatever "WAN info" you need to track this down and fix it.  Specifically what details do you need?

**Comment by lucaberta** [comment]
Thanks @agh1701 and @Sot3 for bringing this issue also here on the GitHub repo.

IPv6 has been quite unstable for me too, and this time an upgrade to 23.1.6 broke things for good.

I would normally be able to make IPv6 work again after a reboot by running:

/usr/local/etc/rc.configure_interface wan

from the FreeBSD shell as root, but this time it did not work out.

I reverted back to 23.1.4 as hinted by @AdSchellevis on this thread by using the command he suggested:

opnsense-revert -r  23.1.4 opnsense

and without rebooting, IPv6 came back to life after giving the reconfigure_interface wan command listed above.

I will NOT update my OPNsense box any further, as IPv6 is really unstable at this time, and I'd rather have it than not.

Many thanks,

Luca

**Comment by fichtner** [comment]
The only thing I see in 23.1.5/6 is the radvd SIGHUP change, which fixes intermittent connectivity issues during reconfiguration. There are no plans to change something there at the moment.

If that is indeed problematic I first need to know how it is problematic because I'm not seeing it (like most IPv6 instability issues reported) while having worked on IPv6 improvements since 2016 at least and running it here in production.


Thanks,
Franco

**Comment by lucaberta** [comment]
Hi Franco, appreciate you looking into this.

Thing is, I have IPv6 issues right on the OPNsense box after reboot, regardless of radvd or DHCPv6 having issues, I believe. In fact, when the box reboots, IPv6 does not work even by doing a ping6 from the OPNsense box CLI, so it's got nothing to do with radvd nor DHCPv6, which matter for machines on the local LAN, I believe.

After I force the WAN link reconfiguration from the CLI with:

/usr/local/etc/rc.configure_interface wan

then IPv6 comes up fine, and I can ping6 from the CLI too.

I have noticed that sometimes after boot the DHCPv6 daemon appears stopped on the dashboard, with the red stopped icon; after I force the WAN interface reconfiguration with the CLI command, it comes up fine and goes green.

All I can say is that moving back to 23.1.4 at least put me back in a situation where forcing a command from the CLI after a reboot makes IPv6 work fine. With the 23.1.6 update not even the CLI trick made things work.

Of course I would love to help by providing troubleshooting information and logs as required, as long as there is value in doing so. Let me know if you think I can help in any way.

Vielen Dank,

Luca

**Comment by agh1701** [comment]
I have tried both patches from https://github.com/opnsense/core/issues/6522 and this did not work.  can you tell me what info i need to provied?

**Comment by Neustradamus** [comment]
Dear all,

I would like to have a perfect radvd 2.20, it is possible to talk about your radvd problems upstream?
Several Issues/PRs are always opened:
- https://github.com/radvd-project/radvd/issues
- https://github.com/radvd-project/radvd/pulls

Thanks in advance.
