### ISSUE TITLE
AAAA DNS entry of pkg.opnsense.org not reachable

### ISSUE THREAD

**Issue by Sunsheep** [opnsense/core#6476]
**Important notices**

Our forum is located at https://forum.opnsense.org , please consider joining discussions there in stead of using GitHub for these matters.

Before you ask a new question, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

Hello,

the DNS AAAA entry for pkg.opnsense.org leads to non reachable address (have a look at the output below).
This leads to opnsense not being able to retrieve updates or the package list (also plugins) respectively a long time passes until a timeout.

Therefore my question: is this intended?

Here the links: 

- https://[2001:1af8:4f00:a005:5::]/
- https://89.149.211.205

```
$ dig pkg.opnsense.org AAAA @8.8.8.8

; <<>> DiG 9.18.13 <<>> pkg.opnsense.org AAAA @8.8.8.8
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 20410
;; flags: qr rd ra ad; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;pkg.opnsense.org.              IN      AAAA

;; ANSWER SECTION:
pkg.opnsense.org.       758     IN      AAAA    2001:1af8:4f00:a005:5::

;; Query time: 13 msec
;; SERVER: 8.8.8.8#53(8.8.8.8) (UDP)
;; WHEN: Wed Apr 05 14:58:17 CEST 2023
;; MSG SIZE  rcvd: 73
```

**Comment by fichtner** [comment]
Local issue?

**Comment by Sunsheep** [comment]
> Local issue?

Must be... Tested on mobile (over LTE instead of wifi) and the connection to the server over IPv6 works.

-- Will close this and investigate a little more.
