### ISSUE TITLE
Feature: Chose language at start of System Wizard

### ISSUE THREAD

**Issue by DokuKaefer** [opnsense/core#648]
It would be good if you can select the language before the System Wizard starts at a new installation and if possible change the language directly without press save or everything.

**Comment by fichtner** [comment]
Love this idea, will be in 16.1 for sure :)

**Comment by fabianfrz** [comment]
@fichtner Another idea: Choose the language on the log in page and use the system setting as default value

**Comment by DokuKaefer** [comment]
@fabianfrz thats also a nice idea
