### ISSUE TITLE
 New IPSec configuration interface: XAuth PAM (group) constraints

### ISSUE THREAD

**Issue by GottemHams** [opnsense/core#6481]
**Important notices**

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**

Using the new IPSec VPN configuration interface you can pretty much configure VPNs in any way you want, including support for mobile users. The only thing missing is a way to enforce group membership when using XAuth PAM. This option can still be found under `Mobile Client Settings`, but enabling that also means OPNsense will insert quite insecure phase configuration in `swanctl.conf` (probably a very conscious decision to remain compatible with many mobile clients). Also the way the new interface is set up might make people think everything should be configured there to begin with.

**Describe alternatives you considered**

See PR #6480.

**Comment by AdSchellevis** [comment]
@GottemHams https://github.com/opnsense/core/commit/621d1b015bc42f0e5e7fd0e1db30ed992d0ad143 should do the trick.

**Comment by GottemHams** [comment]
The now-separate `Extended Authentication (Xauth)` subsection doesn't have its own save/apply button. :D Other than that it seems to work fine, I also don't see additional phase config in `strongswan.conf` anymore.

How fast do things end up in an actual release, by the way?

**Comment by fichtner** [comment]
I think this will be in 23.1.6. if we have a ticket and user confirmation that does speed things up considerably.
