### ISSUE TITLE
Random reboot after connected to internet (NTP / set time issue)

### ISSUE THREAD

**Issue by steelywing** [opnsense/core#6482]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

After setup WAN and connect to internet, wait several minutes, OPNsense will crash and reboot, after reboot several minutes, it will reboot again.
- If I down the WAN interface, it doesn't have crash in several hours.
- I have done some memtest and disk check, there are no issue.
- I tried reinstall OPNsense and restore the config, same happen.
- It is fresh setup, no rule is added on WAN yet.

**To Reproduce**

1. Fresh install OPNsense
2. Setup VLAN for WAN / LAN
3. Connect to internet
4. Wait several minutes (< 20 minutes) it will reboot

**Environment**

OPNsense 23.1 / 23.1.5 / 22.7 (amd64, OpenSSL).
[HP stream mini desktop](https://support.hp.com/us-en/document/c04545960)

**Relevant log files**

[msgbuf.txt](https://github.com/opnsense/core/files/11184720/msgbuf.txt)
[config.txt](https://github.com/opnsense/core/files/11184724/config.txt)
[version.txt](https://github.com/opnsense/core/files/11184721/version.txt)
[info.0.txt](https://github.com/opnsense/core/files/11184722/info.0.txt)
[ddb.txt](https://github.com/opnsense/core/files/11184723/ddb.txt)

**Comment by steelywing** [comment]
I just try v22.7 fresh install, the problem exist too.

**Comment by steelywing** [comment]
Look like it is NTP issue.
I SSH and `tcpdump` the WAN interface, it sometimes reboot after NTP sync packet (but not reboot after every of NTP packet).

After I disable the NTP service, it run about ~1 hour with no reboot.

but now it don't have log in `/var/crash` after crash now, how can I help to debug?

**Comment by steelywing** [comment]
It is NTP issue.
I SSH and `tcpdump` the WAN interface, it often reboot after NTP sync packet.

When I set time manually in shell `date xxxxxx`, it crash too. 

but now it don't have log in `/var/crash` after crash now, how can I help to debug?

Should I close this and report to FreeBSD?

**Comment by fichtner** [comment]
I’ve looked briefly for similar issues via bugs.freebsd.org but couldn’t find something. Opening a ticket there would help clear things up perhaps. It sounds a bit like a BIOS issue with that device.

**Comment by steelywing** [comment]
> I’ve looked briefly for similar issues via bugs.freebsd.org but couldn’t find something. Opening a ticket there would help clear things up perhaps. It sounds a bit like a BIOS issue with that device.

I have search google and can't find relate issue, so lonely.
I have reported in https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=270752

**Comment by fichtner** [comment]
Thanks, I subscribed to that one and let's see what happens.
