### ISSUE TITLE
No "route-to" rule for gateway group will be created when using dynamic gateway members

### ISSUE THREAD

**Issue by spin-lock** [opnsense/core#6486]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

I have two Wireguard tunnels, both are using dynamic gateway. Individually they work, I can use each gateway for policy-based routings.
Wanting to load-balance those tunnels, I created a gateway group with both gateways as Tier 1 members.
Once the gateway group is created, when using it for policy-based routing I found no traffic passing through it.
Upon further checking I could not find any rule with "route-to" the gateway group in the /tmp/debug.rules.

So I had an idea to assign IP addresses to both gateways. Sure enough this time the rule is created: 
`pass in quick on igc2 route-to {( wg2 172.16.0.1 ) ( wg3 10.1.2.1)} round-robin inet from $H_VPN_HOSTv4 to !$N_HOME_PRIVATEv4 keep state label "fe985684557d47cfaf97760aacd2c499"`

I removed the IP addresses from both gateway to turn them into dynamic gateways again, found the rule was missing again.

So I manually inserted a rule in /tmp/debug.rules with this line:
`pass in quick on igc2 route-to { wg2, wg3 } round-robin inet from $H_VPN_HOSTv4 to !$N_HOME_PRIVATEv4 keep state`
Reloaded the rules with "pfctl -f", and voilaaa....found them working as intended and traffic is load-balanced properly.

So I concluded assigning dynamic gateways as members in Gateway group prevents the rule creation, which I think is a bug because it should be allowed.

**To Reproduce**

1. Create two WG tunnels.
2. Create two gateways for each tunnel and assign no IPv4 address (dynamic) on both.
3. Create a gateway group with both gateways as members on a same tier (Load-balance).
4. Create a firewall rule to route IPv4 traffic to the gateway group
Results : No "route-to" rule is created. 
PS : Same results for failover group.

**Expected behavior**

The "route-to"rule should be created.

**Describe alternatives you considered**

When validating a "route-to" rule for gateway group and encountering no IPv4 address on member gateway OPNsense should treat it as route by interface instead of dropping it.

**Screenshots**

**Relevant log files**

If applicable, information from log files supporting your claim.

**Additional context**

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 23.1.5_4-amd64 (amd64, OpenSSL).
Intel® N5105 @ 2GHz
Network Intel® I226

**Comment by AdSchellevis** [comment]
It might be better to document the constraint at the moment, validating if a combination of gateways is usable isn't very trivial it seems and you are more likely to run into issues which invalidate the full ruleset (`all pool addresses must be in the same address family`) if one of the options doesn't "fit".
