### ISSUE TITLE
mvc: deal with template generation failures on another level

### ISSUE THREAD

**Issue by fichtner** [opnsense/core#6487]
**Important notices**

Our forum is located at https://forum.opnsense.org , please consider joining discussions there in stead of using GitHub for these matters.

Before you ask a new question, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

When a template can't render the service is restarted but using the old configuration and that can lead to frustration and confusion even though a log message is emitted.

For one we don't need to restart and also we want to transport the template error to the GUI or the crash reporter pointing to the full issue.

**Comment by fichtner** [comment]
Or: generate an API user error on template generation issue

**Comment by fichtner** [comment]
@AdSchellevis 6af3ec2 should do the trick but I found a problem with wildcards: 7a8129a5d735 -- which now begs the question if we should leave the `Execute error` in there or would rather remove it from the template.reload command?

**Comment by AdSchellevis** [comment]
@fichtner https://github.com/opnsense/core/commit/7a8129a5d73573004ad337899a3910f64667e714 looks good, I don't mind that much removing the execute error as it doesn't seem to hold much additional value if we always send the message tot syslog (as in the wildcard variant). less code, better :)

**Comment by fichtner** [comment]
c9b8f41ce88 then, done :)
