### ISSUE TITLE
squid proxy: use SNI only

### ISSUE THREAD

**Issue by 74656** [opnsense/core#6488]
**Important notices**

Our forum is located at https://forum.opnsense.org , please consider joining discussions there in stead of using GitHub for these matters.

Before you ask a new question, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

Hello,
I am observing a strange behaviour regarding the web proxy in transparent mode.
I'm using OPNsense version 23.1.5_4-amd64.
HTTP is working just as expected.
For HTTPS, I do not want to decrypt traffic nor deploy own certificates, but only use domain based filtering via ACLs.
So I used the option "Log SNI information only".

**Expected behaviour:**
HTTPS traffic ist domain filtered according to web proxy ACL.
HTTPS traffic is not decrypted and if whitelisted, gets passed through to the client inlcuding the original certificate.
Therefore a self-signed CA/certifcate is not needed.
No actual SSL inspection is done.

**Actual behaviour:**
squid is unable to start without a self-signed CA.
If used, any HTTPS traffic causes errors on clients, because the certificate is replaced.
The checkbox "Log SNI information only" can only be used if "Enable SSL inspection" is also enabled.

It seems to me I either I am missing something or "Log SNI information only" is not working as intended.
Any help would be appreciated :)

**Comment by AdSchellevis** [comment]
If I'm not mistaken squid requires the certificate in order to handle error responses., the log might contain more details about the missing cert.

**Comment by AdSchellevis** [comment]
> I don't really care if one has to select a CA as long it doesn't replace the HTTPS traffic certificates when using "Log SNI information only".

It doesn't, only when errors are being served (in which case the client won't trust the answer anyway)

**Comment by AdSchellevis** [comment]
In order to regex match you have to inspect the traffic, which is highly likely the reason for this. 

https://github.com/opnsense/core/blob/f636f0c7b59ca25697e7eece827202e99dbd04df/src/opnsense/service/templates/OPNsense/Proxy/squid.conf#L179

In the business edition we offer a different acl option which uses a different type of matching (https://docs.opnsense.org/vendor/deciso/opnproxy.html), currently we are not planning to invest much more time in the proxy module ourselves.
