### ISSUE TITLE
Openvpn Connection Status Error 

### ISSUE THREAD

**Issue by brandlit** [opnsense/core#6498]
**Describe the bug**

The Openvpn connection status will not open. An error message appears.

**To Reproduce**

1. Go to "VPN"
2. Click on 'OpenVPN'
3. Click on 'Connection Status/Verbindungsstatus'

**Screenshots**

![image](https://user-images.githubusercontent.com/117906596/232403516-5a196a79-3b5b-49dc-bef7-8bf1c062d781.png)

**System Information Log**

User-Agent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36
FreeBSD 13.1-RELEASE-p7 stable/23.1-n250411-85724e9ce22 SMP amd64
OPNsense 23.1.5_4 5aae1b41e
Plugins os-ddclient-1.11_1 os-sensei-1.12.4 os-sensei-updater-1.12 os-sunnyvalley-1.2_3
Time Mon, 17 Apr 2023 08:35:29 +0200
OpenSSL 1.1.1t  7 Feb 2023
Python 3.9.16
PHP 8.1.17

**PHP Error Log**

[17-Apr-2023 08:26:28 Europe/Berlin] ValueError: Array sizes are inconsistent in /usr/local/opnsense/mvc/app/controllers/OPNsense/Base/ApiControllerBase.php:73
Stack trace:
#0 /usr/local/opnsense/mvc/app/controllers/OPNsense/Base/ApiControllerBase.php(73): array_multisort(Array, 4, 14, Array)
#1 /usr/local/opnsense/mvc/app/controllers/OPNsense/OpenVPN/Api/ServiceController.php(111): OPNsense\Base\ApiControllerBase->searchRecordsetBase(Array)
#2 [internal function]: OPNsense\OpenVPN\Api\ServiceController->searchSessionsAction()
#3 [internal function]: Phalcon\Dispatcher\AbstractDispatcher->callActionMethod(Object(OPNsense\OpenVPN\Api\ServiceController), 'searchSessionsA...', Array)
#4 [internal function]: Phalcon\Dispatcher\AbstractDispatcher->dispatch()
#5 /usr/local/opnsense/www/api.php(24): Phalcon\Mvc\Application->handle('/api/openvpn/se...')
#6 {main}
[17-Apr-2023 08:34:25 Europe/Berlin] ValueError: Array sizes are inconsistent in /usr/local/opnsense/mvc/app/controllers/OPNsense/Base/ApiControllerBase.php:73
Stack trace:
#0 /usr/local/opnsense/mvc/app/controllers/OPNsense/Base/ApiControllerBase.php(73): array_multisort(Array, 4, 14, Array)
#1 /usr/local/opnsense/mvc/app/controllers/OPNsense/OpenVPN/Api/ServiceController.php(111): OPNsense\Base\ApiControllerBase->searchRecordsetBase(Array)
#2 [internal function]: OPNsense\OpenVPN\Api\ServiceController->searchSessionsAction()
#3 [internal function]: Phalcon\Dispatcher\AbstractDispatcher->callActionMethod(Object(OPNsense\OpenVPN\Api\ServiceController), 'searchSessionsA...', Array)
#4 [internal function]: Phalcon\Dispatcher\AbstractDispatcher->dispatch()
#5 /usr/local/opnsense/www/api.php(24): Phalcon\Mvc\Application->handle('/api/openvpn/se...')
#6 {main}
[17-Apr-2023 08:35:14 Europe/Berlin] ValueError: Array sizes are inconsistent in /usr/local/opnsense/mvc/app/controllers/OPNsense/Base/ApiControllerBase.php:73
Stack trace:
#0 /usr/local/opnsense/mvc/app/controllers/OPNsense/Base/ApiControllerBase.php(73): array_multisort(Array, 4, 14, Array)
#1 /usr/local/opnsense/mvc/app/controllers/OPNsense/OpenVPN/Api/ServiceController.php(111): OPNsense\Base\ApiControllerBase->searchRecordsetBase(Array)
#2 [internal function]: OPNsense\OpenVPN\Api\ServiceController->searchSessionsAction()
#3 [internal function]: Phalcon\Dispatcher\AbstractDispatcher->callActionMethod(Object(OPNsense\OpenVPN\Api\ServiceController), 'searchSessionsA...', Array)
#4 [internal function]: Phalcon\Dispatcher\AbstractDispatcher->dispatch()
#5 /usr/local/opnsense/www/api.php(24): Phalcon\Mvc\Application->handle('/api/openvpn/se...')
#6 {main}

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 23.1.5_4-amd64
Intel(R) Celeron(R) J4125 CPU @ 2.00GHz (4 cores, 4 threads)

**Comment by fichtner** [comment]
I assume this could be fixed by 4978b067d5 which is already queued up for 23.1.6 this week.

**Comment by brandlit** [comment]
Thanks for the fast answer
