### ISSUE TITLE
Enhancement: change columns of IPsec tunnels

### ISSUE THREAD

**Issue by 8191** [opnsense/core#650]
https://forum.opnsense.org/index.php?topic=1799.0

Suggestion: change columns of IPsec tunnels as follows:

* _P1 Protocol, P1 Transforms_ :arrow_right:  _Phase 1 Proposal_ to show Enc. Alg. + Auth Alg. + DH Group (e.g. AES-128, SHA-256, Group 5)
* Add column _Authentication_ for P1 to show "RSA" or "PSK" (or Xauth for IPsec mobile)
* Move _P2 Protocol, Mode_ :arrow_right: _Type_ to show IP version + enc. + mode (e.g. IPv4 ESP tunnel, or AH transport)
* _P2 Transforms_ :arrow_right: _Encryption Algorithms_ (e.g. AES-128; AES-228; Blowfish-auto)
* _P2 Auth Methods_ :arrow_right: _Authenticity Algorithms_ (e.g. SHA-1; SHA-256)
* Add column _PFS_ for P2

A picture always says more than a 1000 words... ;-)
![Screenshot](https://cloud.githubusercontent.com/assets/5854959/12241793/9ea86852-b895-11e5-9f2e-8fa7ca97d35c.png)

**Comment by 8191** [comment]
I'd have some concrete coding questions:

Can we put the `$p1_authentication_methods` array of [vpn_ipsec_phase1.php:734-740](https://github.com/opnsense/core/blob/master/src/www/vpn_ipsec_phase1.php#L734-L740) to a central place? Maybe either `etc/inc/vpn.inc` or into a legacy function?

Same goes for [DH groups](https://github.com/opnsense/core/blob/master/src/www/vpn_ipsec_phase1.php#L941-L953)...

**Comment by AdSchellevis** [comment]
I kind of moved all variables which aren't used very often or once into the file where they are used, to make cleaning of the old code easier. The new mvc framework provides clear handles for shared definitions, the old code needs cleanups to make migrations easier.

The column changes sound good to me, they wheren't very logical to start with

**Comment by 8191** [comment]
@AdSchellevis I just saw that those variables where exactly in `etc/inc/ipsec.inc` before and you moved them away... :blush: 

What's your recommendation for the interim solution? Code duplication or moving the arrays to legacy functions?

**Comment by AdSchellevis** [comment]
I would vote for duplication here, because the impact is really low and it improves readability of the separate pages.
Although I'm very aware this isn't the final solution, at some point we will have to replace the legacy code.

Cleaning up the old code and making it easier to read really is a step by step process and the steps don't always look that logical in the first place. (sorry about that)

**Comment by 8191** [comment]
PR: #661
