### ISSUE TITLE
Allow custom Firewall rules before auto generated rules

### ISSUE THREAD

**Issue by agowa** [opnsense/core#6502]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

Allow creating rules that apply before the automatically generated rules apply to e.g. drop something specific without logging, or make exceptions to the bogon rule.

**To Reproduce**

1. Enable filtering bogons on WAN
2. Have WAN configured to get its IP using DHCP.
3. Look into Live View and see that the firewall logs all DHCP packages on WAN as bogon.
4. Try to create a block rule for it with disabled logging.
5. Look into Live View again and see that it does not apply, as it is listed after the bogon rule.

**Expected behavior**

Ability to create rules before the automatically generated rules.

**Describe alternatives you considered**

Disabling the generation of the auto rule (depending on case it may not be easy/possible). And recreate it manually.

**Screenshots**

![image](https://user-images.githubusercontent.com/2544867/232623903-8fdf0161-5f11-42fb-bbf3-580714f95505.png)

**Environment**

Software version used and hardware type, if relevant, e.g.:

OPNsense 23.1.5_4-amd64
FreeBSD 13.1-RELEASE-p7
OpenSSL 1.1.1t 7 Feb 2023
AMD Ryzen 7 3800X 8-Core Processor

**Comment by kulikov-a** [comment]
System: Settings: Logging -> `Log packets blocked by 'Block Bogon Networks' rules` checkbox?

> Disabling the generation of the auto rule

`Block bogon networks` checkbox on Interface settings?

**Comment by agowa338** [comment]
yes, in this case I could (and ended up doing for now) disable the block bogon networks checkbox. But I'd prefer to keep that one and just add "an overwrite" before it.

**Comment by AdSchellevis** [comment]
> yes, in this case I could (and ended up doing for now) disable the block bogon networks checkbox. But I'd prefer to keep that one and just add "an overwrite" before it.

Not going to happen, in most cases these rules belong to options set elsewhere (traceable with the "magnifier"), when rules need to be disabled for any reason, it should happen there. Preventing log spam is rather easy by not logging the default rules and adding your own on top.

**Comment by kulikov-a** [comment]
>  to keep that one and just add "an overwrite" before it

IMHO, allowing this (adding user rules with highest prio) in the GUI can(will) lead to users self-locking or other bad things.

**Comment by agowa338** [comment]
> lead to users self-locking or other bad things.

So does turning off the anti-lockout rule or configuring an incorrect IP, NAT, Firewall rule...

I'd also be fine with enabling this capability in the advanced section, similar to how disabling the anti-lockout rule works.

**Comment by agowa338** [comment]
Tbh, I'd also settle for only being able to create log/no-log rules before it. I mainly want to be able to fine-tweak the logging behavior without disabling it entirely.
