### ISSUE TITLE
Favicon isn't displayed when bookmark to the dashboard is saved in Safari favourites.

### ISSUE THREAD

**Issue by turbo-vision** [opnsense/core#6508]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [ X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [ X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**
Safari favourites bookmark of the dashboard doesn't show the favicon, it displays it in the tab only.

A clear and concise description of what the problem is including your motivation for the request,
i.e. "For the purpose of [...] I am missing a solution that will [...]."
Favicon not displayed in Safari when saved as a favourite. I like to keep my favourites neat and tidy and it's annoying. I realise that this is probably pretty low on your list of priorities but it would be nice to implement when someone had the time.

**Describe the solution you like**
Display favicon in favourites bookmark when saving a link to the dashboard.

(e.g. I would like an input field in the `/ui/firewall/alias` which would add .... to ....)
I would like the favicon to also display when a bookmark is saved to favourites in Safari

**Describe alternatives you considered**
None

A clear and concise description of any alternative solutions or features you considered.
None

**Additional context**

Add any other context or screenshots about the feature request here or links to relevant forum thread or similar
Image of the issue for context: https://imgur.com/a/LlmWqvu

**Comment by kulikov-a** [comment]
Hi
not sure if the game is worth the candle (this affects many places, not counting plugins) - for this to work on many types of devices\browsers it need to use various `rel` attr values imho. something like
```
<link rel="apple-touch-icon" sizes="180x180" href="/ui/themes/opnsense/build/images/apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="32x32" href="/ui/themes/opnsense/build/images/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="/ui/themes/opnsense/build/images/favicon-16x16.png">
<link rel="manifest" href="/ui/themes/opnsense/build/images/site.webmanifest">
<link rel="mask-icon" href="/ui/themes/opnsense/build/images/safari-pinned-tab.svg" color="#5bbad5">

```
https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/rel
