### ISSUE TITLE
Kernel panic and boot loop when setting a vlan's parent to itself

### ISSUE THREAD

**Issue by arnogramatke** [opnsense/core#6509]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [ x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x ] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

When setting the parent of a VLAN to the same VLAN, OPNsense crashes with a kernel panic and runs into a boot loop making it unusable.

**To Reproduce**

1. Go to "Interfaces" > "Other types" > "VLAN"
2. Create a new VLAN, for example VLAN ID 10, description "Audio" and parent "LAN".
3. Click "Apply"
4. Edit the VLAN and choose the VLAN that was just created as parent.
5. Click on "Apply"
6. The spinning activity indicator keeps spinning and the web interface doesn't update anymore.
7. Looking at the console, you see that OPNsense crashed with a kernel panic.
8. At some point the appliance reboots, but crashes again when it tries to create the VLAN interfaces.

**Expected behavior**

I am not sure, what the expected behavior should be. Probably OPNsense should not allow the user to set a VLAN as its own parent.

**Describe alternatives you considered**

-

**Screenshots**

-

**Relevant log files**

Can provide a log from the console.

**Additional context**

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 23.1.5_2-amd64
Deciso DEC2685

**Comment by AdSchellevis** [comment]
@arnogramatke thanks for reporting, I expect https://github.com/opnsense/core/commit/e9dc6875532f87bf8950d2f0deafca9ba6b86adf should prevent this from happening.
