### ISSUE TITLE
ICMP Firewall: NAT: Port Forward issue

### ISSUE THREAD

**Issue by azdps** [opnsense/core#651]
Under Firewall -> NAT-> Port Forward when I add ICMP to redirect to an internal ip address the webgui show the destination port as 80 (HTTP) and the redirect port as 80 (HTTP). Should probably just show * for both. Under Firewall -> Rules also shows port 80 (HTTP). I'm assuming this is just a webgui cosmetic issue. I'm using version opnsense v15.7.23-amd64.

![icmp](https://cloud.githubusercontent.com/assets/1825683/12250633/ba12043c-b885-11e5-9e79-46daf3b01e23.jpg)

![icmp2](https://cloud.githubusercontent.com/assets/1825683/12250883/b0648bf6-b887-11e5-969f-66de5e933b7c.jpg)

**Comment by azdps** [comment]
Was just testing out ICMP rules. Something else I noticed that is wrong with creating a NAT -> Port Forward ICMP rule. If you first select create a new rule using the button "add new rule based on this one" and then select protocol ICMP the destination port will be from the rule you based the ICMP rule from. You have no option to change the destination or redirect target ip port. I don't believe the webgui should be showing an option to even select a port let alone input a port for you.

**Comment by fichtner** [comment]
I agree with your analysis, there has been a similar patch that was added to 15.7.24 that does the same for the firewall rules. These are cosmetic issues that surfaced when we reworked the pages as we touched more than just the layout (because it needed housekeeping).
