### ISSUE TITLE
MVC: default value for non-required field

### ISSUE THREAD

**Issue by kulikov-a** [opnsense/core#6511]
**Important notices**

Our forum is located at https://forum.opnsense.org , please consider joining discussions there in stead of using GitHub for these matters.

Before you ask a new question, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

Hi!
In several PR discussions it sounded that in order to set the default value, the field must be set as required. And it seemed logical (In such a case, is a custom migration necessary to set the default value for an non-required field?)
However, when testing the standard migration (just a model ver. bump), I noticed that the default value for the non-required field is successfully set in config. like 
```
      <bots_ua type="CSVListField">
        <Required>N</Required>
        <default>Python-urllib,Nmap,python-requests</default>
      </bots_ua>
```
goes to
`<bots_ua>Python-urllib,Nmap,python-requests</bots_ua>`
in config after the migration
I think thanks to this part:
https://github.com/opnsense/core/blob/85116f7bc384be54af5cb68927899ac5fc09052b/src/opnsense/mvc/app/models/OPNsense/Base/BaseModel.php#L220-L228

So the question is still the same: what is the correct way to set the default value for a non-required field (is a custom migration necessary or will the current behavior be preserved and a simple model bumping is enough)?
Or am I missing something obvious?

Thanks!!

**Comment by fichtner** [comment]
@kulikov-a We will park this for a bit and discuss internally later. There are many possibilities to get to a more consistent state but need to figure out the actual requirements first before possibly doing undesirable work in a wrong direction.

**Comment by kulikov-a** [comment]
@fichtner 

> IMO the default value of a non-required field is a placeholder, not a configuration to render. 

hm, so the second question appears: the correctness of the non-required field prepopulation? (or only using an extra boolean field to disable a required field with a default)

> We will park this for a bit and discuss internally later.

sure, thanks!

**Comment by fichtner** [comment]
One idea could be to remove required setting and just decide based on default tag provided. But as I said we are unsure how much we want/need from this.

**Comment by AdSchellevis** [comment]
Discussed this internally, not really fixable from our model, we only use defaults when the actual value usually depends on the service being used, in which when storing these values in some way, we also need to track the upstream project for changed defaults in these cases. Closing now, but we should remove non required default values from models where set (as they hold no actual value).

**Comment by kulikov-a** [comment]
@AdSchellevis Hi! 
sorry, maybe I've been away for a while and lost the thread a bit: in the end, what's the correct way to set a field with a predefined value but allow a null value so as not to cause problems in the future? add this value with a migration? or is it possible to keep setting this values as in the initial question with something like:
https://github.com/kulikov-a/plugins/blob/4a0161a3bb46ee1b23f3cbfc9786c47471e5201b/www/nginx/src/opnsense/mvc/app/models/OPNsense/Nginx/Nginx.xml#L72-L75
 and your statement is about the default values for the upstream project's native parameters (so as not to constantly track changes in upstream)?
thanks

**Comment by fichtner** [comment]
No worries. Hope you are well.

the example at hand is a really elaborate default value that doesn’t fit a hint/placeholder or  doing a template bound default. In that case you want to set the value to Require=Y in order to be set and displayed visibly.

however, users can’t get back the default value easily. I think this problem may need a solution, but it’s low priority for me.


Cheers,
Franco

**Comment by kulikov-a** [comment]
@fichtner 
I'm not sure if Required=yes is the right choice here - what if the user wants no bot protection at all (I'm trying to move the current hard-coded list of bots into the model for https://github.com/opnsense/plugins/issues/2175 )? 
so I'll probably remove the default value from the model and set it in the migration without violating the idea of ​​a required field in this way)
Thanks!

**Comment by fichtner** [comment]
> what if the user wants no "UA"-bot protection at all

add a checkbox to enable/disable alongside. My point is the default is such an elaborate value that 99% of users cannot set themselves so it's better in there to be edited or removed.

**Comment by fichtner** [comment]
> what if the user wants no "UA"-bot protection at all

add a checkbox to enable/disable alongside. My point is the default is such an elaborate value that 99% of users cannot set themselves so it's better in there to be edited or removed.

**Comment by kulikov-a** [comment]
@fichtner perhaps you are right, it's probably better to make it Required and correctly describe the behavior in the help text (enable/disable selection is available for each server)
Thanks!!)
