### ISSUE TITLE
OpenVPN Widget missing Remote IP for client instances in 23.1.6

### ISSUE THREAD

**Issue by benyamin-codez** [opnsense/core#6516]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

The OpenVPN Widget on the Lobby Dashboard does not show the the "Remote" IP address, aka the "Real Address", of client connections.

Some of the MVC refactoring work @AdSchellevis [committed on April 2](https://github.com/opnsense/core/commit/3066c875a2f61bde48a230ebb3fc150f52cf3db1) - which is the last commit for the file - missed correcting a reference at line 123 to `remote_host`, which should now be `real_address` instead.

For reference: #6464 and [my comment](https://github.com/opnsense/core/issues/6464#issuecomment-1493327272).

Editing the file in-place resolves the problem.

**To Reproduce**

1. On 23.1.6
2. Go to 'Lobby: Dashboard'
3. Observe in the OpenVPN widget under Client Instance Statistics: the Remote IP address is missing.

**Expected behavior**

The OpenVPN widget to show the "Remote" IP address, aka the "Real Address", of client connections.

**Describe alternatives you considered**

N/A

**Screenshots**

N/A

**Relevant log files**

N/A

**Additional context**

No multi-client server instances are present in my environment.

**Environment**

OPNsense 23.1.6

**Comment by benyamin-codez** [comment]
@AdSchellevis, apologies for not catching it, I saw Line 91 and thought that was it... If I'm not mistaken, Line 91 is for servers.

Also just realised I deleted the reference to which file whilst drafting the above; it's `src/www/widgets/widgets/openvpn.widget.php`.

**Comment by AdSchellevis** [comment]
@benyamin-codez no problem, I missed it too. https://github.com/opnsense/core/commit/8a3040fecdd93bd9bf457c281b7994e92c166ede should be the final part then.

**Comment by benyamin-codez** [comment]
@AdSchellevis that did the trick..!

Thanks again, and for the prompt fix.
