### ISSUE TITLE
Prefill IP Address in Static DHCP Config 

### ISSUE THREAD

**Issue by Phiwatec** [opnsense/core#6521]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

Hi, 
when showing the current dhcp leases on  /status_dhcp_leases.php a button (Plus symbol) allows me to add this entry as a static DHCP entry. 
Doing this will automatically enter the MAC-Address and hostname of the device. (Transported as a query paramter: 

 ![photo](https://user-images.githubusercontent.com/52720981/233959271-62451f83-3f03-45ea-bfd2-bcb8dfbc5288.png)

However you still have to manually enter the IP-Address to be assigned to this device. It would be nice, if not only the hostname and mac but also the ip would be prefilled. (Adding &ip=xxx.xxx.xxx.xxx to the query string) 
Greetings 
Philipp

**Comment by fichtner** [comment]
No no no no no no no. This will assign a pool address to a static mapping and isc-dhcp will still hand out that IP address as a lease if it wants to. We've already had this and we don't want to go back.


Cheers,
Franco

**Comment by Phiwatec** [comment]
Oh sorry. Didn't see that. So will the same problem arise when I manually assign a pool address to a device? 
Will dhcpd ignore these static entries and potentially assign them to different devices?
Greetings

**Comment by fichtner** [comment]
Yes, that is precisely the problem with it. Learned that the hard way as forum posts with the "problem" started appearing. Took a while to pin point it to this improvement.
