### ISSUE TITLE
Accept root domain "." as valid DNSSL (in radvd, dhcp, ...)

### ISSUE THREAD

**Issue by agowa** [opnsense/core#6529]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**

A DNSSL entry of "." is commonly used to disable the search domain feature (Linux, windows, ...). Even though a valid DNSSL entry should not end with a dot (like "mydomain."), just a dot (the root domain) is still valid, but OPNsense currently does not accept it.

**Describe the solution you like**

Many public networks don't have a search domain, and explicitly advertising "." makes a lot of clients (esp. domain-joined corporate ones) not use fallbacks. And most of the time (in public networks), the search domains make the lookups take longer, as all entries are tried first before "google.de." is tried, and it also causes a lot of unnecessary NXDOMAIN responses from the DNS server.
And some people use "." as the first item in their search domain to query the domain without the search domain first (makes the DNS client ask for `google.de.` before it would try `google.de.mydomain.`)

**Describe alternatives you considered**

This is mainly a performance enhancement for search domain-related DNS lookups, and it has no alternative.

**Comment by fichtner** [comment]
Can you try [1ff709d](https://github.com/opnsense/core/commit/1ff709dc91ca27f2c70adcacd8ae7fde21d46de4) to see if that works for router advertisements?

    # opnsense-patch 1ff709d


Cheers,
Franco

**Comment by agowa338** [comment]
for some reason that crashed the whole webinterface until I reverted it.

**Comment by fichtner** [comment]
Tried this locally. It rendered the config and GUI was ok. Not sure what could be wrong. Little potential for breakage.

**Comment by agowa338** [comment]
I tried it again and this time it works. And while looking at the dashboard, I probably got the web if OOM killed 🤦

**Comment by fichtner** [comment]
Is this enough for radvd or do we want this in dhcpv6 (v4?) as well? Keep in mind this was never requested before so I'd like the scope small.


Cheers,
Franco

**Comment by agowa** [comment]
It would be meaningful for dhcpv6 too, but tbh, I don't know if the daemon supports it, I try to avoid dhcpv6 as much as possible...

The only thing I'd personally be interested in is opnsense itself using the domain "." or some other way to make it ignore any search domain it receives (e.g. from WAN).

**Comment by fichtner** [comment]
I think you can override the search domain list in system settings general. The validation won’t allow it but if adjusted it would inject it in resolv.conf which is what you are looking for?

**Comment by agowa** [comment]
That would work. My goal with this one is mainly to isolate OPNsense from potentially malicious or erroneous configurations on WAN, as otherwise there could be subtle redirect because of this, as an attacker on wan (e.g. when I have OPNsense running in a VM and I'm connected to a public network). could potentially redirect DNS requests by injecting a dnssearch domain he controls. It also would could help to bypass DNSSec by other domain being connected to then intended, as almost never the final "." is included in lookups by applications to make them complete FQDNs and bypass this "feature"...

**Comment by fichtner** [comment]
@agowa ok what you want is 603a6801f1d but there is a complication (or rather a failsafe):

https://github.com/opnsense/core/blob/603a6801f1deb216d80dee0e6d160c64e42fbb14/src/etc/inc/system.inc#L200-L203

I don't want to add another setting just to override. Perhaps we can change priority when "." is used as first entry. But open for ideas.


Cheers,
Franco

**Comment by agowa** [comment]
Changing the priority sounds good. But I don't know how to implement this in code best. I mainly want to get rid of this "feature" (being able to disable it) 😅
I'd also be fine with a single global option of "disable dnssearchdomain support". I'm not insisting on a single specific implementation.

**Comment by samip5** [comment]
@fichtner If I were to implement this, have I understood right that if `.` is used, the whole searchdomainlist would be ommitted from config entirely aka "commented out" from definition?

**Comment by fichtner** [comment]
@samip5 you can look at https://github.com/opnsense/core/commit/1ff709dc91ca2 which is for router advertisements... we agreed that dhcp is not needed but if you want to patch it you can try
