### ISSUE TITLE
Bug: OpenVPN Client Export only exports singing CA of server certificate without its chain

### ISSUE THREAD

**Issue by 8191** [opnsense/core#653]
The OpenVPN client export (VPN: OpenVPN: Client Export) only exports the direct CA singing the server certificate without the CA's chain. The client then fails to verify the exported CA, if it was not self-signed (i.e. it's an intermediate CA).

**Comment by fichtner** [comment]
@8191 I'm leaving this open for a week to collect more reports before closing. Worst case, we're reverting for 16.1, but I don't think we need to do that. :)

**Comment by fichtner** [comment]
All good, many thanks. :)
