### ISSUE TITLE
Outgoing IPv6 NAT uses wrong address after WAN gets new address from DHCPv6

### ISSUE THREAD

**Issue by jgoerzen** [opnsense/core#6530]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

I believe this is the same bug as described in #5325, though with newer OPNsense (I'm on 23.1.6, while that was reported on 21.7.3).  Everything in the #5325 description also applies to me.  I'm unclear why it was closed, and I am unable to reopen it, so submitting this.

My WAN is Starlink, and they give me a different IPv6 address via DHCPv6 every view days.  For various reasons, I am unable to use NPTv6.  After Starlink gives me a new IPv6 address, traffic originating on the Opnsense device itself works, but NATed traffic doesn't.  tcpdump on the WAN interface shows NAT traffic is egressing with the old (and now invalid) IPv6 source address, while traffic originating on the Opnsense device egresses with the new (and now correct) IPv6 source address.  ifconfig does not show any remnant of the old address.

**To Reproduce**

Use NATv6 and wait for WAN address to change.

**Expected behavior**

Packets should egress with the correct address.

**Describe alternatives you considered**

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 23.1.6-amd64
FreeBSD 13.1-RELEASE-p7
OpenSSL 1.1.1t 7 Feb 2023

**Comment by fichtner** [comment]
It's probably a kernel issue ignoring the deprecated flag or deprecated not being set properly. A bit out of scope from the core side here I'm afraid.


Cheers,
Franco

**Comment by fichtner** [comment]
(or it's actually a state issue for existing connections and you need a reset or stop tracking state for these connections)

**Comment by jgoerzen** [comment]
I can confirm this happens on new connections, so it's not (solely) an issue for existing connections.

**Comment by fichtner** [comment]
Does it fix when you run the following?

    # /usr/local/etc/rc.filter_configure

And if that doesn't fix does the following?

    # /usr/local/etc/rc.routing_configure


Cheers,
Franco

**Comment by jgoerzen** [comment]
Hi Franco,

I had disconnected my NAT due to this issue.  I reconfigured it, but will now have to wait for the next cycle of the IP address from the ISP.  I'll let you know when that happens.

**Comment by jgoerzen** [comment]
Hi Franco,

I experienced this issue again.  Running rc.filter_configure resolved it immediately.

- John

**Comment by fichtner** [comment]
John, I have some patches queued up for 23.1.8 which will improve the situation. Release is expected next week.
