### ISSUE TITLE
incorrect radvd config for /128 virtual IPs

### ISSUE THREAD

**Issue by agowa** [opnsense/core#6531]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

Because of a suggestion to workaround the issue in #6528 by using a virtual IP I discovered that having one with "/128" causes an invalid radvd config file to be generated and hosts on lan will receive SLAAC from that "/64".

**To Reproduce**

1. Add virtual IP `fd1b:b7c6:c499::1/128` to LAN.
2. Restart Router Advertisements service (to have opnSense rewrite the configuration file)
3. Hosts on lan get SLAAC addresses from `fd1b:b7c6:c499::/64` but as it is not a valid network some (I noticed NPTv6 related) traffic to always fail (Probably Happy Eyeballs prevents more from failing).

The radvd.conf file gets generated with:
```conf
        prefix fd1b:b7c6:c499::/64 {
                DeprecatePrefix on;
                AdvOnLink on;
                AdvAutonomous on;
        };
```

**Expected behavior**

Radvd not advertising the `/128` virtual IP from LAN esp. as it is too small for SLAAC. Further more the router advertisement advanced configuration probably should allow to set flags for each (virtual) IPs and to include/exclude them.

**Describe alternatives you considered**

none, was just a test for another bug/limitation.

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 23.1.6-amd64
FreeBSD 13.1-RELEASE-p7
OpenSSL 1.1.1t 7 Feb 2023
AMD Ryzen 7 3800X 8-Core Processor (4 cores, 8 threads)

**Comment by fichtner** [comment]
We can exclude /128 perhaps but I think only accepting /64 or bigger than /65 might break people's setup having set the wrong mask in the first place. Sounds ok?


Cheers,
Franco
