### ISSUE TITLE
DHCP: Dynamic leases with descriptions are forgotten when DHCP service is restarted allowing for IP conflicts

### ISSUE THREAD

**Issue by DarkStarSword** [opnsense/core#6532]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

When the DHCP server is restarted, the dynamically assigned IP addresses of any device with an entry in the static mappings table with a blank IP address field (i.e. "If no IPv4 address is given, one will be dynamically allocated from the pool.") are forgotten - i.e. the IP address in the current leases table is blanked out (presumably copied from the static mappings table), along with the lease start and end times, allowing the DHCP server to potentially assign those addresses to other devices before the old lease has been expired/renewed.

This does not happen for devices that are not in the static mappings table - the IP address in the leases table are not blanked for these when the DHCP service is restarted.

**To Reproduce**

1. Go to Services -> DHCPv4 -> Leases
2. Select a suitable device with a dynamic lease to test the issue. A simple device that doesn't remember its own IP address when unpowered will demonstrate the issue more clearly than a laptop or phone that may request its previous IP, though I don't believe that the issue is actually specific to such devices.
3. Click on the + button next to a the lease of the chosen device
4. Fill in the description field and save. Do not click 'apply changes' when prompted just yet (doing so will yield the same result, I just want to emphasise what is happening on the leases page)
5. Go back to the leases page
6. Note the IP address currently assigned to the chosen device along with the lease start and end times
7. Unplug the device from the network/power
8. Restart the DHCP service via the button at the top of the page (or the apply changes prompt)
9. Observe that the IP address, start and end times for the lease are now blank
10. Plug the device back into the network/power, wait a few seconds for it to connect to the network
11. Observe that the device is assigned a new IP address that may differ from the previous value.
12. Confirm that the current time is still before the lease end time previously noted in step 6.

The issue should already be apparent at this point. To observe the worst case scenario behaviour, continue:

13. Optional - reduce the lease time to the order of a few minutes so we can re-attempt the repro multiple times with minimal waiting, though keep in mind that the lease time needs to be long enough that the forgotten lease will still be valid when we see the address handed out to a different device.
14. Optional - reduce the pool size such that there are very few free addresses to maximise the chances to the DHCP server will issue a recently used but forgotten address rather than a never previously used address.
15. Optional - set up mappings for many more devices with a MAC and Description filled out, but the IP left blank. This will increase the likelihood that one of these devices will have their address assigned to a different device before the forgotten lease has expired.
16. Optional - have some new devices ready to go that do not currently have a lease on the network.
17. Wait for any existing leases to be renewed so that the result of steps 13-16 are in full effect.
18. Navigate to / refresh the DHCP leases page and save the page to disk
19. Restart the DHCP service via the button at the top of the page
20. Plug some new devices into the network that did not previously have an active lease, and/or wait for existing devices on the network to renew their leases, though do not wait too long - to see the issue some devices must still be using the IP from their lease prior to restarting the DHCP service. In my test I only waited a few seconds long enough for the new device I had plugged in to get an IP, though the conflicts I observed actually ended up being in other devices that were renewing their leases during this window.
21. Refresh the DHCP leases page and save to disk.
22. Compare the active leases saved in steps 18 and 21 and look for any devices that:
    - Changed to a new IP between those two moments
    - That the new IP by step 21 was in use by a different device at step 18
    - That the device that had that IP in step 18 has not yet been assigned a different IP by step 21 (i.e. is still using that IP)
    - That the lease end time in step 18 is some time after the lease start time in step 21 (i.e. the leases overlap)
23. If no conflicts are observed, wait a little longer for more devices to check in with the DHCP server, or start over from step 18

**Expected behavior**

The IP address should be remembered in the leases table when restarting the DHCP server (as it is for devices without an entry in the static mappings table) and it should not give out that IP to other devices while the lease is valid.

**Describe alternatives you considered**

I'll probably end up assigning static IP addresses to these devices to avoid the problem, though I would much rather they remain dynamically assigned (e.g. so I can retire a device and automatically reclaim the IP address without having to manually remove the mapping).

**Screenshots**

Leases prior to restarting server - take note that the Broadlink RM4 is currently on .138 and there is an ESP device on .146. The broadlink device's lease will be expiring shortly while the ESP only just obtained it's lease which should remain valid for the next few minutes until 5:25:39:
![image](https://user-images.githubusercontent.com/379749/235287588-f89db867-2cb8-4374-ad47-f287fdda8126.png)

Leases a few seconds after restarting the DHCP server - the Broadlink RM4 has attempted to renew it's lease, but was reassigned to the .146 IP address previously assigned to (and still in use by) the ESP. Note in particular that the lease start time 5:21:22 is quite a bit earlier then the lease end time for this IP in the previous screenshot:

![image](https://user-images.githubusercontent.com/379749/235287790-80134b2e-9277-40a0-8981-c5692d700eef.png)

From the same leases page as the previous screenshot, showing that the ESP device's lease has been forgotten when the server was restarted, and it has not yet checked into the DHCP server to renew:

![image](https://user-images.githubusercontent.com/379749/235287810-1988eac6-5391-4e29-815f-d5fd3d4d5d4d.png)

**Relevant log files**

If applicable, information from log files supporting your claim.

**Additional context**

In order to keep track of the various IoT devices on my network, I added entries in the DHCP Static Mappings table (via the plus button on the leases page) with only the MAC address and description fields filled out (and in some cases hostname if the device was already providing one), and specifically did not fill out the IP address field (i.e. "If no IPv4 address is given, one will be dynamically allocated from the pool.") as my use case does not require that for most of these devices.

To identify the last few devices that I didn't have a more direct way to find their MAC address I was pinging the addresses of every unidentified device, then unplugged one of them (a random ESP8266 relay running my own custom firmware, but I later observed the same happening on other IoT devices) to see which address stopped responding to pings. I then added an entry for that device, saved, clicked the apply changes prompt that appeared, then plugged it back in - and was surprised that it came back on a different IP address to before despite that the dynamic lease should not have timed out yet. Thinking maybe that was a one off just because I'd just added an entry for it, I unplugged the device again, clicked the restart service button (without editing any entries), plugged the device back in and observed that it was assigned yet another IP address again despite that it should have still had a valid lease, and worse was now conflicting with a different device that was already using that IP.

Further investigation showed that before restarting the DHCP server the leases show up on the leases page with their dynamically assigned IP addresses, but after restarting the DHCP service the IP address are blanked out on this page until the next time the device renews its lease, meaning there is a window where the DHCP server has forgotten that it has assigned a given IP and can assign it to a different newly connected device, potentially creating IP conflicts until the old leases start timing out.

**Environment**

OPNsense 23.1.6-amd64

**Comment by AdSchellevis** [comment]
could be https://github.com/opnsense/core/commit/2850c263c8ddd7516b84f563254be940a6fdf263, I think we now drop all static entries on startup, which shouldn't be needed when no address is provided.

**Comment by fichtner** [comment]
Was released in 23.1.7.
