### ISSUE TITLE
DEC840 USB console

### ISSUE THREAD

**Issue by feld** [opnsense/core#6536]
On the DEC840 the USB console is ttyu0 not ttyU0, so the default configuration in /etc/ttys doesn't work.

You can see the kernel messages at boot with console="efi", but you can't login or install from the USB serial console because of this limitation.

changing ttyU0 to ttyu0, off to on, and `kill -HUP 1` makes the console usable.

Can we get this supported out of the box?

**Comment by AdSchellevis** [comment]
@feld you shouldn't need anything (it should work out of the box), if this machine is a little bit older, you might need to change the bios settings as described at https://docs.opnsense.org/hardware/serial_connectivity.html#legacy-uart-vs-uefi-serial
