### ISSUE TITLE
Unbound API searchForwardAction has $this-type set to "dot" and doesn't search

### ISSUE THREAD

**Issue by btenison** [opnsense/core#6538]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

Attempting to use the API for Unbound to call the searchForward API endpoint. I noticed that it does not work, but searchDot does. When I added an 'echo $this->type;' to the function, I noticed that the type within that attribute is 'dot' when called by the searchForward API, but is 'forward' when searchDot is called (and the __call method is called).

In opnsense/mvc/app/controllers/OPNsense/Unbound/Api/SettingsController.php in public function searchForwardAction() approx line 129

*Tip*: to validate your setup was working with the previous version, use opnsense-revert (https://docs.opnsense.org/manual/opnsense_tools.html#opnsense-revert)

**To Reproduce**

- Open PostMan, create a standard call to the API using the key/secret for basic auth.
- Send a POST to: https://OPNSENSE_HOSTNAME/api/unbound/settings/searchDot
  - Include Headers:
    - Content-Type: application/json
    - Accept: application/json
    - Referer: https://OPNSENSE_HOSTNAME/ui/unbound/forward (Required for some reason?)
  - BODY:
    - {"current":1,"rowCount":7,"sort":{},"searchPhrase":""}

When sending the POST message, searchDot returns the information requested from:
https://OPNSENSE_HOSTNAME/ui/unbound/forward

Next, retry the post with this URL:
https://OPNSENSE_HOSTNAME/api/unbound/settings/searchForward

**Expected behavior**

Same POST body and headers should succeed, but it returns nothing.

**Describe alternatives you considered**

Editing the opnsense/mvc/app/controllers/OPNsense/Unbound/Api/SettingsController.php public function searchForwardAction() approx line 129 and adding the line:
- echo $this->type;
- Retrying the above Postman tests shows that the type attribute is 'forward' when using searchDot, but is 'dot' when using searchForward.  
- From the __call method directly above the searchForwardAction method, when the searchDotAction call is used, the call is translated to searchForwardAction and the type is set to 'forward'.
- Since the records do not have a type of 'dot' they are not returned by the succeeding calls.
- As a temporary workaround, I am changing my local copy to set the type to 'forward' within the searchForwardAction() method so I can continue development

**Screenshots**

![image](https://user-images.githubusercontent.com/9038440/235549081-17c038a4-92fa-43cb-9896-3bb237dd3270.png)

![image](https://user-images.githubusercontent.com/9038440/235548777-36adb41b-900e-43ae-93dd-305016418c67.png)

![image](https://user-images.githubusercontent.com/9038440/235548799-399d230d-ea8c-4141-9c91-fe6d9ef48db6.png)

**Relevant log files**

- No log files to upload for this

**Additional context**

- Do not have any prior experience with this API to tell if it ever worked in the past.

**Environment**
OPNsense 23.1.6-amd64
FreeBSD 13.1-RELEASE-p7
OpenSSL 1.1.1t 7 Feb 2023
Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz (4 cores, 4 threads)

**Comment by fichtner** [comment]
It's probably a7966cdd9f7 already in placefor upcoming 23.1.7.

    # opnsense-patch a7966cdd9f7


Cheers,
Franco

**Comment by btenison** [comment]
Thanks Franco! I searched (honest I did) and thought I found a new bug.  Thanks for the update!

**Comment by fichtner** [comment]
No worries 😊
