### ISSUE TITLE
Bug: Routing/Firewall is unstable dont work after editing/adding a vlan

### ISSUE THREAD

**Issue by andreasvel** [opnsense/core#654]
Hi,
assigning, editing, adding a VLAN brings the OPNSense System unstable
was cleared with 15.7.22 and now with OPNsense 15.7.99_2008-amd64 its again like that

**Comment by AdSchellevis** [comment]
Thanks for trying out the development version, it's probably a problem with reloading some settings. Do you have some more information available? 

Like the output of ifconfig when there are issues. And when exactly does issues occur, on edit, delete or create?

**Comment by andreasvel** [comment]
Management was / is on VLAN 1 on em0
In one case i moved a VLAN from one Interface to another (em0 -> em2) 
result - webgui doesnt reloaud - after 5-10 min it was accessible. No DNS Service - no connection via the firewall to the internet

other case i made a new vlan on em2 
result no dns service was reachable.

**Comment by 8191** [comment]
I had similar issues recently after creating VLANs, but after a reboot the issues were gone. Do you still face the problems after a reboot?

**Comment by andreasvel** [comment]
No after a reset it works
But like I wrote on 15.7.22 there it was no problem

I think it should be called a heavy bug because I think it's normal on system to make new vlan on a interface

I just can say that the webgui goes down, the dns system - perhaps the firewall itself goes down 
On one interface the routing and the rules showed a break every ten to 12 seconds

So I think it's should be investigated more - Franco told me that the problem was found but I think there seems more 
The question is if it will be done with the raise on 16.1?!

**Comment by AdSchellevis** [comment]
I don't think anything particular changed in that area, but changing interfaces you primary need sometimes gives hassles (a reboot is often advisable). 
commit https://github.com/opnsense/core/commit/bb223225d05b423e7d9032e698f67710064f21dd might solve some issues.

**Comment by oparoz** [comment]
I also had some issues and it could be because routing was not sending packets exclusively to the VLANs it's supposed to, but to the other ones as well. If I understand that commit properly, it should help.
