### ISSUE TITLE
API CaptivePortal: status property acc_session_timeout always null

### ISSUE THREAD

**Issue by lycano** [opnsense/core#6540]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

CaptivePortal api property `acc_session_timeout` seems not to be updating and is always null.

**To Reproduce**

1. Login to guest network having set `hard-timeout: 10080`, `idle-timeout: 0` under CaptivePortal->Administration before
2. Go to `http[s]://<your-guest-interface-ip>/api/captiveportal/access/status/<zone-id>/` and inspect json
3. See that `acc_session_timeout` is null

**Expected behavior**

When following the Tutorial [Setup Guest Network](https://docs.opnsense.org/manual/how-tos/guestnet.html) where it states "use session_popup.html to see the remaining session time" -> See [image](https://docs.opnsense.org/_images/captiveportal_popup.png) remaining time after logging in should be displayed. The tutorial does use the property `acc_session_timeout` here. Since there is an `idletimeout` property already defined i would expect that `acc_session_timeout` reflects hard-timeout in Captive portal Administration i.e. startTime + hard_timeout_minutes_in_seconds.

**Describe alternatives you considered**

I want to create a custom template displaying the remaining datetime (e.g. on 2023-06-10 13:00:00 Uhr) a guest has.

Alternative implementation idea: Since i plan to use vue and do some designing using vuetify system header bar i would like to count down a timer a user has before getting disconnected on a status/welcome page.

As a workaround i could use `startTime` property and calculate it based on hardcoded timeout - in this case 10080 minutes in seconds until this is fixed. Whenever i decide to update hard-timeout setting i would simply need to rebuild the app and deploy to hardware which is a minor issue for me right now as this can be a variable during build time.

**Environment**

OPNsense 23.4-amd64
FreeBSD 13.1-RELEASE-p7

**Comment by AdSchellevis** [comment]
`acc_session_timeout` is only available when using accounting, which currently is only supported on RADIUS. I'm not sure you currently are able to calculate the hard timeout from the data provided.

https://github.com/opnsense/core/blob/af587e812a7b8d96cf3fd84869dc7e00bbfe09b3/src/opnsense/scripts/OPNsense/CaptivePortal/cp-background-process.py#L128-L140

**Comment by lycano** [comment]
Hello @AdSchellevis,

must have missed the info box on the page. Then its not a bug and this can be closed. Will switch to RADIUS and see how it goes. Currently im using Local Database. Was assuming this should work too. Thanks!
