### ISSUE TITLE
IPv6 CARP MAC addresses are not sync'ed between nodes, and acting as "IP Aliases" instead

### ISSUE THREAD

**Issue by dracocephalum** [opnsense/core#6543]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

TL;DR
IPv4 CARP is working fine. IPv6 CARP MAC addresses are not sync'ed between nodes, and appeared as "Aliases" on UI.

After upgrading to the latest OPNSense, I am experiencing some strange issues.
On UI, both IPv4 CARP and IPv6 CARP are defined for each interface like below:
![image](https://user-images.githubusercontent.com/29667545/236118191-ae695792-99cf-4eac-84c3-ef5effef19ef.png)

But they are shown like this on "Status" page e.g. I have to include "IP Alias" from the filter to show IPv6 CARP addresses:
![image](https://user-images.githubusercontent.com/29667545/236116950-3d1a0ac3-4da6-4b0e-ba0f-bf61b9db043f.png)

Also when the interface has been put into BACKUP mode correctly:

![image](https://user-images.githubusercontent.com/29667545/236117366-7901bf7e-ce39-4f39-a82a-c2373b07d408.png)

The NDP is showing that the MAC address of the local interface is a permanent "neighbour", instead of the MAC address of the master CARP interface on the other machine. It is indeed acting a bit more like an "IP Alias" rather than CARP:

![image](https://user-images.githubusercontent.com/29667545/236117739-35fe3f80-2927-4a2f-adaa-256273391dbf.png)

**To Reproduce**

1. Setup 3 OPNSense instances (Hyper-V VMs, MAC address spoofing enabled, virtual switch without SR/IOV)
2. Setup both CARP IPv4 and IPv6 on an interface for each instance

**Expected behavior**

IPv6 CARP should work like IPv4 CARP e.g. BACKUP machine should have the MAC address updated for the CARPv6 address.

**Describe alternatives you considered**

n/a

**Screenshots**

See describe the bug section

**Relevant log files**

See describe the bug section

**Additional context**

n/a

**Environment**

OPNsense 23.1.6-amd64
FreeBSD 13.1-RELEASE-p7
OpenSSL 1.1.1t 7 Feb 2023

machine 1: Supermicro SYS-8049U-E1CR4T
machine 2: Supermicro SYS-110P-WTR
machine 3: Supermicro X10SDV

**Comment by AdSchellevis** [comment]
sounds like https://github.com/opnsense/core/commit/d5c6cc24d3964b152536f24198ec4d1377728d88
