### ISSUE TITLE
DHCP Static Mappings allows duplicate entries

### ISSUE THREAD

**Issue by feld** [opnsense/core#6546]
- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

I have a problem where if I'm testing two devices with the same hostname but only running one at a time on my network the Unbound server will end up registering two IP addresses for the same hostname from this DHCP Static Mapping feature which creates a big mess. Enabling randomized MAC addresses in some OSes also creates this same problem.

**To Reproduce**

1. Start a device with a hostname, get a lease, shut it down.
2. Start another device (or somehow change MAC address) but use same hostname, get a lease.
3. Try resolving that hostname and observe that two A records are returned when only one should exist.

**Expected behavior**

For DHCP static mapping entries it should only be possible to have one IP address registered for the hostname meaning only one active A and PTR record. Every time it tries to add a new DNS record from the DHCP lease data it should drop any existing records first.

**Describe alternatives you considered**

It appears the logic in `unbound_watcher.py` is too basic for this right now as it just keeps appending new entries to the `dhcpleases.conf` file.

Honestly, it might seem a little silly but I really think the better solution than this python script would be to fire up a BIND server on localhost:5353 or something and enable the ISC-DHCPD <> BIND integration using DDNS which does this properly, then have Unbound forward requests for the local forward and reverse zones to BIND. That's what I used to do before I used OpnSense and it worked perfectly. Unbound can still have its static records, but anything else is forwarded to BIND.

**Comment by AdSchellevis** [comment]
>Honestly, it might seem a little silly but I really think the better solution than this python script would be to fire up a BIND server on localhost:5353 or something and enable the ISC-DHCPD <> BIND integration using DDNS which does this properly, then have Unbound forward requests for the local forward and reverse zones to BIND. That's what I used to do before I used OpnSense and it worked perfectly. Unbound can still have its static records, but anything else is forwarded to BIND.


There are quite some reasons why this wouldn't be a very good idea, apart from adding a lot of complexity, there's also isc sunsetting the service (https://www.isc.org/dhcp/) which means everything added is a new problem someone has to solve at some point in time.....

I think this is a bit of an edge case, it bears some resemblance to  https://github.com/opnsense/core/issues/5952, but there might be use-cases where people actually expect the service to return both hosts (as still having an active lease) in this case.
