### ISSUE TITLE
Initial Wizard Changes DHCP Settings With No Way To Prevent

### ISSUE THREAD

**Issue by utkonos** [opnsense/core#6551]
**Important notices**

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

During the console install process, if the user selects option 2 to set the IP configuration for the LAN interface and chooses to enable DHCP, the next step is to set the lower and upper bounds for the DHCP range. No matter what the user chooses for these two bounds, if the user then goes through the initial wizard, that lower and upper bound are changed by the wizard with no input from the user and no way to prevent the change.

**To Reproduce**

1. Install from official 23.1 ISO
2. After install, login as root
3. Select option 2
4. Configure LAN to enable DHCP.
5. Set lower bound to 10.10.10.100
6. Set upper bound to 10.10.10.200
7. Connect to GUI over LAN network.
8. Go through the steps of the initial wizard.
9. Look at the config changes that are performed by the wizard and observe that the lower and upper bounds were changed and there was no setting in the wizard that controls this change. It just happens without the user's input and no warning.

**Expected behavior**

The DHCP boundaries that are chosen during the configuration should be kept with no change if the user goes through the initial wizard steps.

**Describe alternatives you considered**

It's ok if the initial wizard changes these boundaries, it just needs to offer an option to the user where these two values can be changed or kept the same.

**Screenshots**

<img width="1142" alt="Screenshot 2023-05-08 at 22 20 28" src="https://user-images.githubusercontent.com/2775739/236978634-69c54f5c-c274-4c6e-9879-bcfab8456329.png">

<img width="1576" alt="Screenshot 2023-05-08 at 22 20 15" src="https://user-images.githubusercontent.com/2775739/236978593-0ae021fc-6840-4a7e-bc35-2b3fcb6937f5.png">

**Environment**

OPNsense 23.1 (amd64, OpenSSL)

**Comment by fichtner** [comment]
I'm leaving this as support. Don't really feel that a wizard should not set defaults that look sane and if you want to use something else that sort of suggests you shouldn't rerun a setup wizard. Though I'm open for suggestions that DO NOT complicate the hard-to-maintain wizard glue.
