### ISSUE TITLE
DHCPv6 support for virtual IP range

### ISSUE THREAD

**Issue by Qhilm** [opnsense/core#6555]
**Important notices**

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**

I want to be able to control which device receives which IP in my network in a granular fashion, in order to be able to apply different policies to them:
* Route outbound via VPN or not
* Apply parental controls on local DNS server
* Prioritise or throttle

My ISP provides me a delegated IPv6 prefix but it changes. Hence I have configured a virtual IP to create ULAs on my local network.

When using Router Advertisement, I am at the mercy of the client, as it may decide at any time to change the IPv6 suffix of their ULA.

Obviously, when the client uses a random MAC, all of this does not work anyway, but in general this behavior can be turned off on the device (iPhones, Android devices).

**Describe the solution you like**

Being able to assign static DHCPv6 leases for multiple IPv6 ranges:
* Delegated IPv6 prefix acquired from a WAN interface (or a VPN interface)
* Virtual IPv6 range (used as ULA for example)

**Describe alternatives you considered**

* Router advertisements (drawbacks described above)

**Comment by fichtner** [comment]
This won't happen before we have a migration strategy for DHCP core service software itself as isc-dhcp is more or less end of life/unsupported.

**Comment by hobbes444** [comment]
ok, I'll be following progress on this migration with interest then. Thanks for the feedback.

**Comment by simonmicro** [comment]
I would like to extend the scope of this issue: As @Qhilm already mentioned, the support of multiple (dynamic) IPv6 prefixes would be needed. So, I would like to see that support to also include multiple WAN interfaces. This will also allow the use of _multi-homed_ IPv6 networks.

**Comment by BPplays** [comment]
@fichtner according to [this](https://forum.opnsense.org/index.php?topic=38503.msg214079#msg214079)  DNSmasq DHCP will be supported in the future, are there any plans for supporting this in DNSmasq?

**Comment by fichtner** [comment]
I guess yes if Dnsmasq doesn’t complain at run time. Kea DHCPv6 would support this too. Kea DHCPv4 already does…
