### ISSUE TITLE
Only add CARP FW Filter rules if VIP are configured

### ISSUE THREAD

**Issue by rudiservo** [opnsense/core#6556]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**

CARP filter rules are added in general even if CARP is not being used, granted this is probably negligible performance impact, nonetheless I do feel that every cycle counts and that hardening is really something to achieve specially in a router, it might avoid security issues, you never know, better safe then sorry IMO.

**Describe the solution you like**
As @AdSchellevis mention there was something that was removed in the commit 1b336f3cccd59d622e8f7f54b46f0d6fac763974 
My suggestion is to only add carp rules if carp Virtual Ip carp mode are configured

```
$a_vip = &config_read_array('virtualip', 'vip');
$has_vip_carp = false;
$i = 0;
$a_vip_length = sizeof($a_vip);
while ($i < $vips_length && false === $has_vip_carp) {
    $vip = $a_vip[$i];
    if ( false === empty($vip) && true === is_array($vip) && 'carp' === $vip['mode'] ) {
        $has_vip_carp = true;
    }
    $i++;
}
if ( true === $has_vip_carp ) {
    foreach ( ['ff02::12', '224.0.0.18'] as $to ) {
        $fw->registerFilterRule(
            1,
            [
                'protocol' => 'carp',
                'direction' => 'any',
                'to' => $to,
                'descr' => 'CARP defaults',
                '#ref' => 'firewall_virtual_ip.php'
            ],
            $defaults['pass']
        );
    }
}

```

**Describe alternatives you considered**

I have considered to add rule per VIP interface or pfsyncinterface

```
$a_vip = $config['virtualip']['vip'];
foreach ($a_vip as $vip) {
    if ( false === empty($vip) && true === is_array($vip) && 'carp' === $vip['mode'] ) {
        foreach ( ['ff02::12', '224.0.0.18'] as $to ) {
            $fw->registerFilterRule(
                1,
                [
                    'interface' => $vip['interface'],
                    'protocol' => 'carp',
                    'direction' => 'any',
                    'to' => $to,
                    'descr' => 'CARP defaults',
                    '#ref' => 'firewall_virtual_ip.php'
                ],
                $defaults['pass']
            );
        }
    }
}

```
Or Pfsync interface

```
$a_vip = &config_read_array('virtualip', 'vip');
$has_vip_carp = false;
$i = 0;
$a_vip_length = sizeof($a_vip);
while ($i < $vips_length && false === $has_vip_carp) {
    $vip = $a_vip[$i];
    if ( false === empty($vip) && true === is_array($vip) && 'carp' === $vip['mode'] ) {
        $has_vip_carp = true;
    }
    $i++;
}
if ( true === $has_vip_carp ) {
    $hasync = $config['hasync']
    if ( false === empty($hasync) && true === is_array($hasync) && true === array_key_exists('pfsyncinterface', $hasync) ) {
        foreach ( ['ff02::12', '224.0.0.18'] as $to ) {
            $fw->registerFilterRule(
                1,
                [
                    'interface' => $hasync['pfsyncinterface'],
                    'protocol' => 'carp',
                    'direction' => 'any',
                    'to' => $to,
                    'descr' => 'CARP defaults',
                    '#ref' => 'firewall_virtual_ip.php'
                ],
                $defaults['pass']
            );
        }
    }
} 
```

**Additional context**

I know this seems silly, I do have a lot of FW rules like DROP and EDROP that consume more cycles, but I don't think that having general rules added even if the service is not being used a good practice, today security is problematic at minimum, so a good hardened system should be a good practice and Opnsense could and should be the Gold Standard, at least in my opinion.

Thanks for all your effort, it's an amazing system and this suggestion is with the best intentions.

**Comment by pawlakm** [comment]
you forgot to link to #6539

**Comment by pawlakm** [comment]
Adding link to the forum as well: https://forum.opnsense.org/index.php?topic=36157.0

**Comment by rudiservo** [comment]
A similar conversation was added over FRR, it adds all generic firewall rules to all interfaces, the way opnsense maintainers will go about it is the ability to deactivate generating rules, but the administrator has to add them manually, not a huge ordeal,

https://github.com/opnsense/plugins/issues/3431

https://github.com/opnsense/plugins/pull/3432

**Comment by AdSchellevis** [comment]
same as https://github.com/opnsense/plugins/issues/3431#issuecomment-1735682366 , if more people would like to be able to omit these rules and add them manually, we can discuss where to place the option.  From a performance perspective the effects will be neglectable, the generic (current) rule is likely faster then one aimed at the interface where carp is enabled.

**Comment by rudiservo** [comment]
@AdSchellevis well I will admit that I do not understand how PF works, hopefully it would be faster depending on how much traffic needs to be validated on a certain interface, maybe on day I will go down that rabbit hole and check it.
However IMO it's not really a good practice to have things open where you do not need them, better safe than sorry, again, IMO.

**Comment by rudiservo** [comment]
@AdSchellevis sorry to bump this, but can we have the option to disable carp firewall rules, or at least not have them enabled if carp is not configured.
Appreciated, thanks!

**Comment by AdSchellevis** [comment]
@rudiservo I don't mind that much if someone wants to spend his/her time on adding a toggle to disable the rule, although realistically the value of the option is close to zero (as these packets are ignored when no vips are configured anyway).

**Comment by Apachez-** [comment]
@AdSchellevis its bad security practice to have rules enabled for services who currently isnt enabled on a firewall.

Same goes with dhcp-request (and dhcp-response) if you use static IP etc.

And even if they for whatever reason are enabled by default it should be possible to through the webgui disable unwanted services AND rules.

Forcing the admin to go behind the scenes and manually alter the /usr/local/etc/inc/filter.lib.inc file is just wrong.

Anyone who knows where on the roadmap ability to manually (through webgui) disable the carp default rules (and other default rules that might exist) currently is or prefered making this automagic the way @rudiservo initial post suggested?
