### ISSUE TITLE
Improve OpenVPN Compression Configuration to help mitigate VORACLE attack vector

### ISSUE THREAD

**Issue by benyamin-codez** [opnsense/core#6559]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**

OpenVPN from v2.5 added the `--no-compression` option defaulting to the `asym` mode.
OpenVPN from v2.6 changes the default to `--no-compression no`.

The use of compression leaves tunnels vulnerable to the VORACLE attack vector and is not recommended. OpenVPN v2.6 offers a solution to mitigate the risk of a successful VORACLE attacks whilst maximising backwards compatibility. However, these mitigations require Server and Client configurations with minor but important differences.

Related issue: #6265 (probably a bit stale since v2.6 is released)
Related forum post: https://forum.opnsense.org/index.php?topic=25205.msg164177#msg164177

**Describe the solution you like**

Please update the OpenVPN server and client configuration pages at _Tunnel Settings: Compression_ as follows:

1. Consider changing _No Preference_ ---> _No Preference - NOT recommended_ 
2. Consider changing _Partial - Packet framing for compression (--compress)_  --->  _Prepared - Set up packet framing for any compression type (--compress)_
3. Consider changing _Enabled - Stub algorithm (--compress stub)_  --->  _Prepared - Set up packet framing for stub compression (--compress stub)_
4. Change the **default** option on the **client** page to use `--compress stub-v2` and rename the option _Enabled - Stub v2 algorithm (--compress stub-v2)_ ---> _Prepared - Set up packet framing for stub v2 compression (--compress stub-v2) RECOMMENDED_
5. Add a new **default** option to the **server** page called _Conditional - Special migration mode (--compress migrate) RECOMMENDED_ 
6. Consider adding the following label to the drop-down list (or adding it to the Help text): 
> WARNING: Compression is DEPRECATED and NOT recommended.
> WARNING: VPN tunnels which use compression are susceptible to the VORALCE attack vector.
7. Consider changing the Help text to the following:
> OpenVPN v2.6 includes a default option of "--allow-compression no" which is recommended.
> Servers should use "--compress migrate" (added in v2.6).
> Clients should use "--compress stub-v2" (added in v2.5) which invisibly prepares a compression frame and from Community Client v2.6.2 prevents clients from negotiating an insecure compression algorithm.
> 
> The recommended settings mitigate the VORACLE attack vector. Please consider their use wherever possible. This configuration object does not include the insecure options for "--allow-compression asym" and "--allow-compression yes", neither of which is recommended. In cases where these options are required, the relevant advanced configuration item can be added to the Advanced list. To permit the use of insecure compression algorithms, such as lz0, lz4, lz4-v2 and stub, select "No Preference - NOT recommended" (which should only be used when you own both the server and client configurations).
>
> For more information, please refer to https://openvpn.net/community-resources/reference-manual-for-openvpn-2-6.

Also please consider changing the label on the OpenVPN server and client configuration pages at _Advanced configuration: Advanced_ to the following:
>ATTENTION: Only full administrators are allowed to change this setting.
>WARNING: This setting might become deprecated in the future. No validation is performed. Use with caution.

**Describe alternatives you considered**

Adding a GUI knob for `--allow-compression` options, but with the change in v2.6 defaults to use the `no` parameter, this would be unwise. The suggested Help text describes how these options can be enabled if doing so is unavoidable.

Adding the `--compress migrate` to both server and client pages, but this might introduce confusion when configuring clients.

Not adding recommendations (both positive and negative), but there is really only one configuration choice to mitigate VORACLE attack vectors, and this is not really clear without making recommendations.

**Additional context**

Valid from OPNsense 23.1 with the inclusion of OpenVPN 2.6.3.

**Comment by AdSchellevis** [comment]
We are likely going to add a new user interface (https://github.com/opnsense/core/tree/openvpn_mvc) in a similar way as we did for IPsec (stick to the upstream documentation). In the long run the legacy pages are not really maintainable and unfortunately full of assumptions.

**Comment by benyamin-codez** [comment]
All for new GUI MVC goodness...!

I guess the main issue is the defaults do not mitigate two VORACLE attack vectors and advanced options are required for servers (`--compress mitigate`). **Would this perhaps be better described as a bug or vuln?**

After **5 years** I think OpenVPN have finally come up with a set of configuration options that can fully disable compression and mitigate all VORACLE attack vectors. These too will become deprecated one day I guess (when v2.6.1 client support ends).

Whether implemented in the legacy pages or the new UI - or indeed both - could the above still be considered anyway..?
I note my suggestions are in agreement with upstream documentation.

**Comment by benyamin-codez** [comment]
> These too will become deprecated one day I guess (when v2.6.1 client support ends).

Actually, it is if and when a client with a default of `--compress stub-v2` goes EOL... 8^d

**Comment by benyamin-codez** [comment]
>I note my suggestions are in agreement with upstream documentation.

Except that the default is NOT to `--compress`.

The problem for clients is a server can still push a compression option the client may accept, e.g. a v2.6.3 client with no `--compress` directive will still accept a push of `--comp-lzo no`, enabling selective compression.
Servers with the default settings will refuse non-stub compression, but compression frame detection is still possible with `stub` (but not with `stub-v2`) due to the additional framing byte.
In theory, both scenarios could cause peers to be susceptible to attacks which could eventually make use of VORACLE.

> **Would this perhaps be better described as a bug or vuln?**

Should this be reported upstream? The upstream defaults only mitigate VORACLE attack vectors when using trusted server AND client configurations. It appears explicit intervention is required during configuration in any other scenario.

**Comment by AdSchellevis** [comment]
I'm not entirely sure what your referring to, but if their defaults are unsafe, better report there indeed, but from their documentation about this subject I don't expect they are (https://community.openvpn.net/openvpn/wiki/VORACLE)

**Comment by benyamin-codez** [comment]
Thanks Ad. The VORACLE wiki article you referenced - whilst useful - was last updated over 5 years ago.

Somewhere along the way to v2.6, all of the following statements in that article now prove to be FALSE (probably not an exhaustive list), at least in the OPNsense implementation (it's the only one I can readily test against):

> Configurations *NOT* using `--comp-lzo` or `--compress` are *NOT* affected by VORACLE.

The defaults permit these options to be pushed and / or negotiated, thus adding them to running configurations.

> It is important to know that compression has never been enabled by default. An OpenVPN configuration (implying both the local and remote side) must explicitly enable compression.

The defaults permit compression options to be pushed and / or negotiated, thus adding them to running configurations.

> It is important to remember that `--comp-lzo` or `--compress` must be used on both the local and the remote side. If only one side uses any of these options, it will not be a functional VPN tunnel.

Clients can be pushed these options using the default configuration. Servers will not refuse `stub` in the default configuration. The v2.5 default of `--allow-compression asym` would also render this statement false.

From the Reference Manual (https://openvpn.net/community-resources/reference-manual-for-openvpn-2-6/):

> `--allow-compression no`: (default) OpenVPN will refuse any non-stub compression.

i.e. it can still be enabled on a server by a client requesting `stub`, where packet framing for compression will then be enabled. Clients will also accept `--comp-lzo no` and `--compress` being pushed even with this default. This is likely due to the packet framing for compression being identical to `stub`.

In reference to proper mitigation:

> Especially `stub-v2` is essentially identical to no compression and no compression framing as its header indicates IP version 5 in a tun setup and can [be] (ab)used to complete[ly] disable compression to clients. (See the `migrate` option below)

> Using `migrate` as compression algorithm enables a special migration mode. It allows migration away from the `--compress`/`--comp-lzo` options to no compression. This option sets the server to no compression mode and the server behaves identical to a server without a compression option for all clients without a compression in their config. However, if a client is detected that indicates that compression is used (via OCC), the server will automatically add `--push compress stub-v2` to the client specific configuration if supported by the client and otherwise switch to `[--]comp-lzo no` and add `--push comp-lzo [no]` to the client specific configuration.

This wiki article was last updated 3 months ago): https://community.openvpn.net/openvpn/wiki/Compression

It alludes to the primary problem: For the defaults to be considered safe, you must control both server and client.

However, even that article is wrong in it's claim that using `--allow-compression no` completely disables compression.

The only way to mitigate VORACLE is to ensure servers use `--allow-compression no` (the new default) and `--compress migrate`, and clients to use `--compress stub-v2`. The current default for both clients and servers is to not specify any `--compress` or `--comp-lzo` options, which means one of these options can be pushed or negotiated.

It gets even worse again for clients, which really require `--pull-filter ignore comp` as well, in order to stop servers clobbering `--compress stub-v2` with the likes of `--comp-lzo no`, which would modify the IP header and the compression frame. Adding the filter when being clobbered results in a data channel set up for `stub-v2` but unable to transceive packets.

In the OpenVPN Changes (https://github.com/OpenVPN/openvpn/blob/master/Changes.rst#user-visible-changes), the following is mentioned:
> (OpenVPN 2.6.2) A client will now refuse a connection if pushed compression settings will contradict the setting of allow-compression as this almost always results in a non-working connection.

However, this does not appear to be the case as described above. Did OPNsense implement a different client version, or are we forcing a compatibility mode...? It could just be because `--comp-lzo no` and `--compress` have packet framing for compression identical to `stub`, so the connection is not refused for these. In the clobbering example I mention, the negotiated data channel is `stub-v2`, both of which are permitted by `--allow-compression no`.

`--allow-compression never` would be nice. 8^d

Before dropping an upstream report, are we sure the above behaviours aren't due to any oddities in the OPNsense implementation?

In any case, can we implement some of my suggestions above anyway?

**Comment by AdSchellevis** [comment]
The OPNsense configuration files can easily be inspected in the `/var/etc/openvpn/` directory. We only add compression when some option is selected (empty is the default).

https://github.com/opnsense/core/blob/c568629c01cb046d0905b26d3b3de1e3293b1b4b/src/etc/inc/plugins.inc.d/openvpn.inc#L837-L851


I'll happily review any pull request being opened, but certainly am not planning to change anything at the moment, time can better be spend elsewhere.

**Comment by benyamin-codez** [comment]
Thanks @AdSchellevis.
I appreciate you making the time to comment and for the pointer.
I also noticed:
https://github.com/opnsense/core/blob/c568629c01cb046d0905b26d3b3de1e3293b1b4b/src/etc/inc/plugins.inc.d/openvpn.inc#L164-L178 I might do a PR as time permits... 8^d

I'm just filtering through what might belong upstream and thought you might be able to share some insight into the client behaviour from v2.6.2 (24 March 2023). Arne Schwabe made four commits that day re compression per https://github.com/OpenVPN/openvpn/commits/master:

https://github.com/OpenVPN/openvpn/commit/bfc00a01c10bbdd9683aab5db2c2e7dcbb2f7378
https://github.com/OpenVPN/openvpn/commit/e86bc8b2967484afdb1e96efddb8d91185c4cc2c
https://github.com/OpenVPN/openvpn/commit/4117d950788eebfaf6c9b5dde278e3a81b9e805d <-- Notably this one
https://github.com/OpenVPN/openvpn/commit/a8170dd0e76a7440f3291ad26d78f8ca247a191b

I'm not convinced we are seeing that behaviour in our port-built v2.6.3 (15 April 2023). Was curious if it might be because we use `enable_comp_stub=no` at compile time (per `/usr/local/sbin/openvpn --version`). I didn't want to raise it upstream if that might be the cause...

**Comment by AdSchellevis** [comment]
I really think your questions are best aimed elsewhere, the version we ship can easily be found using ` openvpn --version`, the build recipe (port) is available at https://github.com/opnsense/ports/tree/master/security/openvpn

**Comment by benyamin-codez** [comment]
Thanks again @AdSchellevis.
As in I should aim upstream instead?
Perhaps /dev/null...? 8^D

Version doesn't appear to be an issue, as I said `openvpn --version` reports v2.6.3.

Looks like `--enable-comp-stub` might disable lzo and lz4 anyway, with description _"disable compression support but still allow limited interoperability with compression-enabled peers"_ ... so likely not desirable for OPNsense.

And our port Makefile:
```
.if ! ${PORT_OPTIONS:MLZ4} && ! ${PORT_OPTIONS:MLZO}
CONFIGURE_ARGS+=	--enable-comp-stub
.endif
```
I think the problem is that we are getting `--allow-compression stub` and not `--allow-compression no` and the new compression parsing and refusal logic fails. Anyway, it's looking like an upstream problem methinks, at least that part...

**Comment by pavelmatskevichiosifovich** [comment]
ㅤ

**Comment by nisutaro88** [comment]
No solution to disable compression only server side?
