### ISSUE TITLE
New aliases in Unbound DNS override are easy to get added to wrong host

### ISSUE THREAD

**Issue by haarp** [opnsense/core#6561]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

When a new alias is added with the `+` button to a selected host, a `Edit Host Override Alias` is opened. In this dialog, the `Host override` dropdown is always selected to the first entry, not the one which was visible when `+` was pressed. This is misleading and leads to incorrect aliases when the user is not paying close attention.

**To Reproduce**

1. Go to Unbound DNS Overrides
2. Select a host using its checkbox
3. Press the `+` button under the `Aliases` heading below
4. `Host override` box is not prepopulated with previously selected host

**Expected behavior**

Previously selected host should be preselected

**Describe alternatives you considered**

Paying a lot of attention and never making mistakes? :)

**Screenshots**

--

**Relevant log files**

--

**Additional context**

( I don't understand why the Hosts section above is using checkboxes instead of radio boxes. Only one can be selected. This was very confusing in the beginning. It's not immediately clear that this is used to select a single host, and that the Aliases section changes upon selecting one. )

**Environment**

OPNsense 23.1.7

Thanks a lot!

**Comment by haarp** [comment]
Hey Ad, it's a sunday :) Thanks for the swift fix!

**Comment by haarp** [comment]
confirmed fixed on my box with c568629

**Comment by AdSchellevis** [comment]
@haarp thanks for confirming! we'll try to add it to the next release.
