### ISSUE TITLE
Monit /usr/local/opnsense/scripts/OPNsense/Monit/gateway_alert returns exit=0 regardless of gateway status

### ISSUE THREAD

**Issue by kpiq** [opnsense/core#6562]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**OPNsense 23.1.7_3**
**/usr/local/opnsense/scripts/OPNsense/Monit/gateway_alert returns exit=0 regardless of gateway status**

A clear and concise description of what the bug is, including last known working version (if any).
**I noticed that OPNsense's Monit plugin has not been alerting me when there is a loss of internet connectivity, even though I have the following Monit Service alert set up and enabled:

Enabled=yes, Name=gateway_alert, Type=Custom, Path=/usr/local/opnsense/scripts/OPNsense/Monit/gateway_alert, Program Timeout=120, Start Timeout=30, Tests=NonZeroStatus, Depends=Nothing, Poll Time=0-59 * * * *

To make sure my settings in the Web GUI were not mistaken I proceeded to manually test the alert.  See below section "To reproduce" for detailed description of the steps to test manually.**

*Tip*: to validate your setup was working with the previous version, use opnsense-revert (https://docs.opnsense.org/manual/opnsense_tools.html#opnsense-revert)

**To Reproduce**

1. login to opnsense console (root).  Press 8 for the shell.
2. login to the Web GUI.  
3. Go to System: Gateways: Single, record the Monitor IP for the WAN_DHCP gateway.
4. Go to Lobby: Dashboard, find the Gateways widget.  Verify the WAN_DHCP gateway is online.
5. Switch back to the console login.  ping the WAN_DHCP's Monitor IP address.  Expected result: 0% packet loss.  Actual result: 0% packet loss.
6. Run /usr/local/opnsense/scripts/OPNsense/Monit/gateway_alert; echo RC=$?.  Record exit code.  Expected result: RC=0.    Actual result: RC=0.
7. Disconnect power of the cable modem.
8. ping the WAN_DHCP's Monitor IP address.  Expected result: 100% packet loss.    Actual result: 100% packet loss.
9. Run /usr/local/opnsense/scripts/OPNsense/Monit/gateway_alert; echo RC=$?;   Expected result: RC= something other than 0.    Actual result: RC=0.
10. Reconnect power to the cable modem.  Wait for full boot up and Internet Connectivity.
11. Run /usr/local/opnsense/scripts/OPNsense/Monit/gateway_alert; echo RC=$?.  Record exit code.  Expected result: RC=0.    Actual result: RC=0.
12. ping the WAN_DHCP's Monitor IP address.  Expected result: 0% packet loss.  Actual result: 0% packet loss.

**Expected behavior**

**Describe alternatives you considered**

A clear and concise description of any alternative solutions or workaround you considered.

**Screenshots**

**Relevant log files**

If applicable, information from log files supporting your claim.

**Additional context**

**Environment**

Software version used and hardware type if relevant, e.g.:

Versions | OPNsense 23.1.7_3-amd64FreeBSD 13.1-RELEASE-p7OpenSSL 1.1.1t  7 Feb 2023
-- | --
Updates | Click to check for updates.
CPU type | Intel(R) Core(TM) i7-8705G CPU @ 3.10GHz (4 cores, 8 threads)

Versions 	OPNsense 23.1.7_3-amd64
FreeBSD 13.1-RELEASE-p7
OpenSSL 1.1.1t 7 Feb 2023
Platform--
Manufacturer | QEMU
Product Name | Standard PC (i440FX + PIIX, 1996)
Version | pc-i440fx-jammy
Virtualized OPNsense on Ubuntu Jammy KVM/QEMU

CPU type 	Intel(R) Core(TM) i7-8705G CPU @ 3.10GHz (4 cores, 8 threads)
Network Intel® I210
igb0: flags=8863<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500
	description: WAN (wan)
	options=4900028<VLAN_MTU,JUMBO_MTU,NETMAP,NOMAP>
	ether 54:b2:03:98:26:c6
	inet 74.213.124.## netmask 0xffffff00 broadcast 255.255.255.255
	media: Ethernet autoselect (1000baseT <full-duplex>)
	status: active
	nd6 options=29<PERFORMNUD,IFDISABLED,AUTO_LINKLOCAL>

**Comment by AdSchellevis** [comment]
This check only monitors gateways which are part of a group (https://github.com/opnsense/core/blob/master/src/opnsense/scripts/OPNsense/Monit/gateway_alert).

**Comment by kpiq** [comment]
Thank you.  Never thought of creating a Gateway Group, just a single Gateway.

**Comment by lostcontrol** [comment]
> This check only monitors gateways which are part of a group (https://github.com/opnsense/core/blob/master/src/opnsense/scripts/OPNsense/Monit/gateway_alert).

This is super confusing. That script should be named `gateway_group_alert` and the corresponding Monit service setting should include "Group" somewhere to avoid confusion.

I have 2 gateways defined by OPNsense, one for IPv4 and one for IPv6. I would expect this script to send an alert whenever the status of one of the gateways is down. This is not the case.

![Image](https://github.com/user-attachments/assets/ca36818c-6c07-4411-ab11-717c6d54352a)
