### ISSUE TITLE
Schedule support in Traffic Shaper

### ISSUE THREAD

**Issue by patan32** [opnsense/core#6563]
Any chance we can finally have support for schedules in Traffic Shaper?

This is the number one feature I miss in OPNsense, there are so many situations where traffic shaping needs vary across the day but there's no simple way to setup in OPNsense. it's available in most other firewall products out there (and has been for many years) so quite frankly I find it astounding that this still hasn't been implemented in OPNsense (and demand seems to be there are I found a number of requests for this feature throughout the years).

Are there any plans to implement this?

**Comment by patan32** [comment]
@fichtner - Sorry to mention you like this but i saw a support request for traffic shaper. Can you please tag this as feature request. Can we please get this implemented in Opnsense?

**Comment by AdSchellevis** [comment]
@patan32 you could try to close this and open a proper ticket using our templates, I don't mind tagging it afterwards, for us it's not a priority (if someone wants to spend time on it and the amount of resources needed from our end are limited, that's obviously fine).

**Comment by patan32** [comment]
> @patan32 you could try to close this and open a proper ticket using our templates, I don't mind tagging it afterwards, for us it's not a priority (if someone wants to spend time on it and the amount of resources needed from our end are limited, that's obviously fine).

Hello, 

Thanks for the reply. I did create another ticket link: https://github.com/opnsense/core/issues/6564
Is this good? I understand it's low priority but would be nice feature to have. Thank you for all the help.

**Comment by AdSchellevis** [comment]
sure, closed this one in favor of https://github.com/opnsense/core/issues/6564
