### ISSUE TITLE
Service Name in PPPoE connection cannot be set as NULL after being changed

### ISSUE THREAD

**Issue by Matwolf08** [opnsense/core#6568]
When I set a service name for a PPPoE interface, I can't unset it.

Within the WAN interface configuration, the PPPoE section is missing the "set as NULL" checkbox, and if I delete the name after applying the changes the Service Name comes back as before, unchanged.

![image](https://github.com/opnsense/core/assets/1523458/e499ce31-b11f-4e2c-ba32-d5ef39436293)

But even if I edit the Point to point device directly, where the checkbox to set as NULL is present, it doesn't get set as NULL but as "1".

![image](https://github.com/opnsense/core/assets/1523458/0f2cdab1-b40e-4b39-a78e-c73ea8700af3)

The only way to clear that field (and get the connection to work again) is to delete and re-create the ppp device.

```
OPNsense 23.1.7_3-amd64
FreeBSD 13.1-RELEASE-p7
OpenSSL 1.1.1t 7 Feb 2023
```

Thanks in advance

**Comment by fichtner** [comment]
@Matwolf08 `null_service` aside I don't see a reason why leaving the service name empty doesn't work. I've also tried changing the service name from the interface settings and it works as intended.


Cheers,
Franco

**Comment by fichtner** [comment]
I'll just leave this here for educational purposes:

https://github.com/pfsense/pfsense/commit/c66673968c

vs.

https://github.com/pfsense/pfsense/commit/233e2af1f43

**Comment by Matwolf08** [comment]
Tested now on OPNsense 23.1.11-amd64 and the issue is still present.

@fichtner changing the the service name from the interface settings does work, but if you try setting it to an empty string it doesn't get changed. It comes back with the same name as before.

From the PPPoE interface edit page, instead, where you can see the "Set NULL service" chackbox, if you check the checkbox the service name get set at "1".

**Comment by fichtner** [comment]
Well, just try the patch then...

    # opnsense-patch c3db32722d48

**Comment by Matwolf08** [comment]
Ok, after applying your patch the behavior is the expected.

Thanks!

**Comment by fichtner** [comment]
Perfect, thanks for the report and testing!
