### ISSUE TITLE
Bug: Menu-Style problem on iPad Mini 4

### ISSUE THREAD

**Issue by DokuKaefer** [opnsense/core#657]
Look on the screenshot, the menu is not show complete on a iPad Mini 4.

![opnsense_ipad_mini4](https://cloud.githubusercontent.com/assets/11537653/12277457/a0a20398-b97b-11e5-93b6-5d96302e7276.png)

**Comment by 8191** [comment]
@DokuKaefer On which browser? The built-in one (Safari?) or a 3rd party browser? Do you think it's specific to the Mini or also with the non-mini?

**Comment by DokuKaefer** [comment]
The screenshot is from the Chrome browser. But the Safari browser has this problem also.
I have only the iPad Mini, so I can currently say anything about other tablets.

**Comment by DokuKaefer** [comment]
I tested again on iPad Mini
The heading line at Captive Portal (DEV Version) is not show.
On other pages the same but not at all pages.
Affected all browsers Chrome, Safari, Firefox

![cp_1](https://cloud.githubusercontent.com/assets/11537653/12300338/4998b308-ba1b-11e5-8ee7-b4c56151cae4.png)
![cp_2](https://cloud.githubusercontent.com/assets/11537653/12300339/49bbcfa0-ba1b-11e5-8de3-655ab5ff202c.png)

**Comment by DokuKaefer** [comment]
Landscape Mode and heading line is good.

![cp](https://cloud.githubusercontent.com/assets/11537653/12309533/884cbcc2-ba4b-11e5-8382-410b33c0be46.png)
