### ISSUE TITLE
OPNsense BGP Alias lists show empty [SSL: CERTIFICATE_VERIFY_FAILED]

### ISSUE THREAD

**Issue by newyork10023** [opnsense/core#6570]
**Important notices**

Our forum is located at https://forum.opnsense.org , please consider joining discussions there in stead of using GitHub for these matters.

Before you ask a new question, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

I currently have an issue when upgrading from OPNsense 23.1.5 series to later versions (including 23.1.6 and 21.1.7).

My rules rely heavily on BGP aliases (e.g., to limit SMTP and IMAP to locally valid addresses).  On upgrades, and possibly other configuration/setup change events (e.g., possibly restoring configuration backups?), the configured BGP alias lists are empty.  This has immediate consequences on email as well as push notifications (e.g., Apple, WhatsApp, etc.) among others.

Am I correct that BGP alias lists are flushed on these type of events?  How long does it take to refresh these aliases?  Can I manually force the BGP alias lists to be refreshed?  (Or, has the BGP alias system broke since 23.1.5?)

I asked this question in the community forums as per the guidelines for contributing, but I have received no reply.  I have not filed a bug report yet.

**Comment by AdSchellevis** [comment]
It downloads the content from https://rulesets.opnsense.org/alias/asn.gz on our end, usually the log (Firewall: Log Files: General) does offer some more clarity. On my end it works without issues.

**Comment by newyork10023** [comment]
Thanks @AdSchellevis .  The firewall logs at The Firewall -> Log Files -> General reveal:

2023-05-19T12:06:42-04:00	Error	firewall	alias resolve error BGP_Apple_v4 (HTTPSConnectionPool(host='rulesets.opnsense.org', port=443): Max retries exceeded with url: /alias/asn.gz (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get issuer certificate (_ssl.c:1134)'))))

The issue began to occur with 23.1.5_4.  I have upgraded to 23.1.7_3.  On a separate system, I do not have the issue.  I have now upgraded the system at issue, removed unnecessary plugins, performed a configuration reset to defaults (and reloaded the saved configuration).

Under Firewall -> Aliases, the BGP aliases show Loaded# with various numbers of loaded aliases.  However, under Firewall        -> Diagnostics -> Aliases, the BGP aliases are all empty.  The update dates are current regardless of the failure above.  This seems related to #6327 ( https://github.com/opnsense/core/issues/6327 ).

The firewall rules on which BGP aliases depend no longer function.

**Comment by AdSchellevis** [comment]
Likely installed certificate authorities breaking trust upstream. When visiting our website with https://rulesets.opnsense.org it does look normal (and works without issues on my OPNsense as well).

**Comment by fichtner** [comment]
If the health audit looks ok sometimes the following file get damaged beyond repair for the package tool `/usr/local/openssl/cert.pem` for reasons not to be debated here...

To fix:

   # cp /usr/local/openssl/cert.pem{.sample,}
   # /usr/local/etc/rc.configure_firmware
