### ISSUE TITLE
Strongswan curl fetcher 

### ISSUE THREAD

**Issue by belerovon** [opnsense/core#6572]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**
I have the following Situation:

Setting up an IPSec with X509 Certificate

IPSec working and is up but in logs I can see CRL and OCSP Check are failing due to "no capable fetcher found"

CURL to OCSP and CRL from my Opnsense working correctly

Risk: That means that I can not revoke Certificates what is in my point of view a security Issue.

What i also have seen from swanctl --stats or ipsec statusall I can see that following modules are loaded:

> loaded plugins: charon aes des blowfish rc2 sha2 sha1 md4 md5 random nonce x509 revocation constraints pubkey pkcs1 pkcs7 pkcs12 pgp dnskey sshkey pem openssl pkcs8 fips-prf curve25519 xcbc cmac hmac kdf gcm drbg attr kernel-pfkey kernel-pfroute resolve socket-default stroke vici updown eap-identity eap-md5 eap-mschapv2 eap-radius eap-tls eap-ttls eap-peap xauth-generic xauth-eap xauth-pam whitelist addrblock counters

For me, it seems the Opnsense Strongwan package isn't build with the strongswan-mod-curl.

Think this would be really easy for you and increase the security.

**To Reproduce**
 * Using a PKI (e.g. openssl) and sign  X509 Usercertificate with a CRL and/or OCSP
 * Import CA to Truststore of Opnsnse so the certificates can be checked and trusted
 * VPN > IPsec > Tunnel Settings : Add in IPSec VPN with Mutal RSA Authentication method and select imported CA
 * Add a Phase 2
 * Open in terminal a tail -f: tail -f /var/log/ipsec/latest.log | grep "con"
 * Connect to IPSec

in logs you will see the connection comes up but with hint:

> <30>1 2023-05-19T12:35:04+02:00 zh-fw.xxxxxx.tld charon 17843 - [meta sequenceId="293"] 05[LIB] <con4|52> unable to fetch from http://ocsp.xxxxxx.tld:8080, no capable fetcher found
> <30>1 2023-05-19T12:35:04+02:00 zh-fw.xxxxxx.tld charon 17843 - [meta sequenceId="294"] 05[CFG] <con4|52> ocsp request to http://ocsp.xxxxxx.tld:8080 failed
> <30>1 2023-05-19T12:35:04+02:00 zh-fw.xxxxxx.tld charon 17843 - [meta sequenceId="295"] 05[CFG] <con4|52> ocsp check failed, fallback to crl
> <30>1 2023-05-19T12:35:04+02:00 zh-fw.xxxxxx.tld charon 17843 - [meta sequenceId="296"] 05[CFG] <con4|52>   fetching crl from 'http://crl.xxxxxx.tld/intermediate.crl.pem' ...
> <30>1 2023-05-19T12:35:04+02:00 zh-fw.xxxxxx.tld charon 17843 - [meta sequenceId="297"] 05[LIB] <con4|52> unable to fetch from http://crl.xxxxxx.tld/intermediate.crl.pem, no capable fetcher found
> <30>1 2023-05-19T12:35:04+02:00 zh-fw.xxxxxx.tld charon 17843 - [meta sequenceId="298"] 05[CFG] <con4|52> crl fetching failed

**Expected behavior**
Strongswan should be able to use curl to fetch OCSP or CRL.
Strongswan on a Linux system have installed strongswan-mod-curl and with it seems to work correctly.

**Relevant log files**
> <30>1 2023-05-19T12:35:04+02:00 zh-fw.xxxxxx.tld charon 17843 - [meta sequenceId="293"] 05[LIB] <con4|52> unable to fetch from http://ocsp.xxxxxx.tld:8080, no capable fetcher found
> <30>1 2023-05-19T12:35:04+02:00 zh-fw.xxxxxx.tld charon 17843 - [meta sequenceId="294"] 05[CFG] <con4|52> ocsp request to http://ocsp.xxxxxx.tld:8080 failed
> <30>1 2023-05-19T12:35:04+02:00 zh-fw.xxxxxx.tld charon 17843 - [meta sequenceId="295"] 05[CFG] <con4|52> ocsp check failed, fallback to crl
> <30>1 2023-05-19T12:35:04+02:00 zh-fw.xxxxxx.tld charon 17843 - [meta sequenceId="296"] 05[CFG] <con4|52>   fetching crl from 'http://crl.xxxxxx.tld/intermediate.crl.pem' ...
> <30>1 2023-05-19T12:35:04+02:00 zh-fw.xxxxxx.tld charon 17843 - [meta sequenceId="297"] 05[LIB] <con4|52> unable to fetch from http://crl.xxxxxx.tld/intermediate.crl.pem, no capable fetcher found
> <30>1 2023-05-19T12:35:04+02:00 zh-fw.xxxxxx.tld charon 17843 - [meta sequenceId="298"] 05[CFG] <con4|52> crl fetching failed

**Environment**
* OPNsense 23.1.7_3 (amd64).
* strongswan | 5.9.10_1

**Comment by belerovon** [comment]
Hey would be nice to hear from you …

**Comment by doktornotor** [comment]
This does not depend on #6838 at all. strongswan simply needs to be compiled with CURL support enabled. It grabs the OCSP/CRL location from certificate just fine, but cannot download it.
