### ISSUE TITLE
Default DNS not returned in DHCP request when unbound set to a port other than 53

### ISSUE THREAD

**Issue by tommiyau** [opnsense/core#6575]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**
With blank Services->DHCPv4->[LAN]->DNS Servers field Opnsense is intended to return the default LAN Gateway address as the Option 6 to a client DHCP Ack request. On 23.1.7 this only happens if unbound is configured for port 53. If unbound is configured for any other port there is no Option 6 DNS Server list returned to successful LAN Client DHCP requests. In previous version unbound could run on any port and the default LAN Gateway address would be returned as Option 6 in the DHCP ack.

*Tip*: to validate your setup was working with the previous version, use opnsense-revert (https://docs.opnsense.org/manual/opnsense_tools.html#opnsense-revert)

**To Reproduce**
Set Services->DHCPv4->[LAN]->DNS servers field to be blank.
Change Services->Unbound DNS->General->Listen Port to a value other than 53

Perform the following on a windows 10 machine
ipconfig /flushdns
ipconfig /renew

Try to resolve any host name such as google.com in a browser or nslookup. These now fail.

to restore
Set Services->DHCPv4->[LAN]->DNS servers field to be blank.
Change Services->Unbound DNS->General->Listen Port to a value 53

Try to resolve any host name such as google.com in a browser or nslookup. These now work.

**Expected behavior**

The default LAN DNS ip address should be the default LAN gateway as stated in the opnsense GUI and documentation irrespective of the unbound dns port.

**Describe alternatives you considered**

Manually defining the default DNS setting to be the LAN gateway address resolves the issue.
Set Services->DHCPv4->[LAN]->DNS servers set the default LAN IP Gateway address

**Screenshots**
N/A

**Relevant log files**

Not included but can supply if you point me to which ones in particular would assist.

**Additional context**

Issue breaks the default opnsense forum configuration for use of adguard home.

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 23.1.7_3-amd64
FreeBSD 13.1-RELEASE-p7
OpenSSL 1.1.1t 7 Feb 2023
Intel J3160

**Comment by fichtner** [comment]
If port 53 isn't active, how is the client reaching Unbound on that port?


Cheers,
Franco

**Comment by tommiyau** [comment]
Following the configuration to add adguard home to opnsense requires
adguard essentially proxy ingress config between port 53 and the upstream
resolver. So my old configuration on 22.7 had unbound being upstream of
adguard home and listening on port 53530. Adguard was suitably configured
to use that port as upstream. The opnsense help pages on services, dhcpv4,
dns states if the fields are empty then the lan default gateway ip address
is sent in option 6 of the dhcp request. On 23.1.7 this does not occur and
the ip address of the dns server (the lan gateway address) is not returned.
Changing the port to listen upon I don't think should cause the ip address
to fail to be returned. That has not changed. That is why if you now
manually set the LAN DNS address the configuration with adguard works
again. However, you can take adguard out of the picture...simply changing
the port stops the ip address being returned in the dhcp request even
though the address is the same default.

**Comment by fichtner** [comment]
Missing AdGuard integration has been discussed at length already. We cannot assume someone installs something else on port 53 when no known DNS service is configured there.


Cheers,
Franco

**Comment by tommiyau** [comment]
Resolved by finding the thread below
https://github.com/opnsense/core/issues/6513
