### ISSUE TITLE
no "add phase 2 entry" button on /ui/ipsec/tunnels

### ISSUE THREAD

**Issue by EBG100** [opnsense/core#6577]
Important notices
Before you add a new report, we ask you kindly to acknowledge the following:
•	  I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
•	  I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

Version:
23.1.8  amd64
(Azure Virtual Server)

Describe the bug
There is no “add phase 2 entry” button on https://myserver/ui/ipsec/tunnels

1.	Go to https://myserver/ui/ipsec/tunnels
2.	Notice lack of “add phase 2 entry” button

Expected behavior
An “add phase 2 entry" button in the phase 2 section

Screenshots
 
![Picture1](https://github.com/opnsense/core/assets/134736954/b7dbfc44-099c-4b8e-aa0f-ae0865ab5f0c)

**Comment by fichtner** [comment]
In your screenshot orange button in the phase 1 row

**Comment by EBG100** [comment]
I see what you mean now.  That could be a bit clearer :)
Thanks, you can close this issue.

**Comment by fichtner** [comment]
It can be improved, but not sure how at the moment. We will continue to work on it.


Cheers,
Franco
