### ISSUE TITLE
Unable to access webui when upgrade to 23.1.8

### ISSUE THREAD

**Issue by CallMeR** [opnsense/core#6578]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

After updating to the latest version of OPNsense, I found that I can no longer access it through WebUI.  

SSH is disabled on the router so the web interface is the only way to manage it.

Everything is working normally before the update.

**To Reproduce**

1. Upgrade system
2. Reboot the system
4. See error "503 Service Unavailable"

OPNsense 23.1.8  (amd64, OpenSSL).

**Comment by fichtner** [comment]
https://docs.opnsense.org/manual/settingsmenu.html#listen-interfaces

**Comment by CallMeR** [comment]
> https://docs.opnsense.org/manual/settingsmenu.html#listen-interfaces

> If for whatever reason, you do need to listen only on specific interfaces, the following rules apply:
> The interface must always be available, so do not try to bind to vpn instances of any kind (OpenVPN, Wireguard, …)
> The addressing must be fully static, so no IPv6 tracking configured for example

It listen on specific interfaces `LAN` , and  which has a static IPv4 address ,

**Comment by fichtner** [comment]
And likely IPv6 tracking enabled

**Comment by CallMeR** [comment]
> And likely IPv6 tracking enabled

yes，track IPv6 interface is set to `WAN` .  

So is this a problem caused by IPv6 address changes ?  

However, I am using the IPv4 address of the LAN for webUI access, and I have been using it for months before this system update.

**Comment by CallMeR** [comment]
some logs :

![image](https://github.com/opnsense/core/assets/11908641/ebcfb17f-8654-4d41-b70e-b947c5523dfd)

**Comment by AdSchellevis** [comment]
> So is this a problem caused by IPv6 address changes ?

highly likely, https://docs.opnsense.org/manual/settingsmenu.html#listen-interfaces explains how to set this up properly....

**Comment by CallMeR** [comment]
In fact, I modified the listening interface of the service to improve the security of the device, and maybe I'm going against with the best practice. 

If the problem is caused by a dynamic IP address on the interface on which the WebUI or SSH service listens, is it possible to provide an additional configurable item when the user sets the listening interface?

For example, let the user select a static IP address that exists on the interface as the listening address of the service.

Or, when set to Default (your recommended settings) , provide additional ACLs to limit the accessibility of the service, like specify the accessible IP address ranges.

According to my observations, SSH services can specify the IP address to listen on, and likewise, in the first configuration of Adguard Home, you can also select the IP address that WebUI listens on.

**Comment by fichtner** [comment]
A LAN interface is not a management interface. You haven’t increased security. WAN is inaccessible by default anyway. Let’s please not drag security into misconfiguration issue here.
