### ISSUE TITLE
menu: VisibleName vs. underscore

### ISSUE THREAD

**Issue by fichtner** [opnsense/core#658]
I've recently thought about replacing "VisibleName" by a simpler approach, taking literal "Test_Entry" in the node name as a translated space as "Test Entry", "Test__Entry" as a translated underscore as "Test_Entry". The node names already generate strings and this is very simple to grasp for newbies. What do you think? :)

**Comment by AdSchellevis** [comment]
I rather keep an attribute for the visible name in stead of combining key and value, attributes may include literal phrases including entities like "&#x00040; home" for example :)
Although I see no issue in renaming the attribute or making it required for more transparency.

**Comment by fichtner** [comment]
No need, was just an idea. Thanks for answering. :)
