### ISSUE TITLE
Expose in GUI the CARP unicast options as an advanced setting

### ISSUE THREAD

**Issue by nzkiwi68** [opnsense/core#6581]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**

- Some switches do not work well with CARP multicast packets.
- ISP supplied modem/routers with small (often 4 port) switches don't support multicast packets at all
- I have seen many stacked switches that mess with multicast CARP on the switch to switch stacking backend and cause CARP issues

I'm not asking to "reinvent" CARP, rather, expose and enable the existing CARP over unicast features that exist today.
See [https://man.openbsd.org/carp](https://man.openbsd.org/carp)

**Describe the solution you like**

Add an "advanced option" into 
    Interfaces: Virtual IPs: Settings

So, these new advanced options would not be visible unless the user deliberately toggled and switched on the "advanced mode" slider.

Then offer three options:

1. CARP multicast (default)
2. CARP ip-unicast
3. CARP ip-stealth

**Describe alternatives you considered**

There isn't any, we just have CARP over multicast

**Additional context**

pfSense have recently added CARP over unicast, it we would great to have this available on OPNsense.
This will likely reduce broadcast traffic
The only negative I can see is the cluster is limited to two members, well, we never have more that primary and backup anyway

I am requesting and recommending this all be under an advanced option so the default will be CARP multicast and these extra options will not be immediately visible.

I expect CARP over unicast for all the HA sites I run will be more reliable.

**Comment by fichtner** [comment]
Pointing to OpenBSD page while we use FreeBSD is a bit counter productive. Also a request for these additions with out specifics such as which option it is in name and how it’s enabled is also problematic.

However, I’m aware of the setting but relatively sure FreeBSD 13 doesn’t offer it. Is it even in FreeBSD soon to be 14?

These are important questions and information to supply.


Cheers,
Franco

**Comment by JSuenram** [comment]
> Pointing to OpenBSD page while we use FreeBSD is a bit counter productive. Also a request for these additions with out specifics such as which option it is in name and how it’s enabled is also problematic.
> 
> However, I’m aware of the setting but relatively sure FreeBSD 13 doesn’t offer it. Is it even in FreeBSD soon to be 14?
> 
> These are important questions and information to supply.
> 
> Cheers, Franco

Bringing this up again as I think this is realy a good option in smaller setups.

Freebsd at least will bring CARP Unicast in 14.1
https://freebsdfoundation.org/blog/freebsd-14-1-whats-new-and-how-did-we-get-here/

CARP Unicast Address Support: Updated carp(4) to allow configuration of the address to which CARP messages are sent, supporting unicast addresses for certain virtual configurations.

**Comment by AdSchellevis** [comment]
euh, did you actually check our end??? including the documentation https://docs.opnsense.org/manual/firewall_vip.html#carp

**Comment by JSuenram** [comment]
> euh, did you actually check our end??? including the documentation https://docs.opnsense.org/manual/firewall_vip.html#carp

Yes sure... but was not aware that this is basically the same.... 
never mind...

**Comment by JSuenram** [comment]
Have to bring this up once again. I think what the T/O meant was unicast for CARP-Traffic, not only for Statesync....
Currently even when you enter peer IP, there is still Multicast-Traffic for every Interface which as a CARP-VIP. And this should be configurable to be unicast like the other sense-product can already do.... Should be considered when change to FreeBSD14 is done....

**Comment by AdSchellevis** [comment]
🤷‍♂️
<img width="621" alt="image" src="https://github.com/user-attachments/assets/6d17cc8e-f3d8-4d64-b586-e6fe96731b71">
<img width="887" alt="image" src="https://github.com/user-attachments/assets/b952ed5d-73e4-44f5-92f3-55bbb4438523">

**Comment by JSuenram** [comment]
> 🤷‍♂️ <img alt="image" width="621" src="https://private-user-images.githubusercontent.com/9783985/371777550-6d17cc8e-f3d8-4d64-b586-e6fe96731b71.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc1NDYwNTQsIm5iZiI6MTcyNzU0NTc1NCwicGF0aCI6Ii85NzgzOTg1LzM3MTc3NzU1MC02ZDE3Y2M4ZS1mM2Q4LTRkNjQtYjU4Ni1lNmZlOTY3MzFiNzEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MjhUMTc0OTE0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NGNmNTlkNWZhYTkzMWI4MTE0MzRmMDRlMDhlYjA0Y2Q3NTgzYzhlZDNiODVlY2JiNzdhYmFlZjViYzIyMTczMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.t2MkAtx3j5kzT90SQkaaNHCmN2XxIwqomO8_TDxw3DM"> <img alt="image" width="887" src="https://private-user-images.githubusercontent.com/9783985/371777561-b952ed5d-73e4-44f5-92f3-55bbb4438523.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc1NDYwNTQsIm5iZiI6MTcyNzU0NTc1NCwicGF0aCI6Ii85NzgzOTg1LzM3MTc3NzU2MS1iOTUyZWQ1ZC03M2U0LTQ0ZjUtOTJmMy01NWJiYjQ0Mzg1MjMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MjhUMTc0OTE0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTUxYTU0N2VkN2IzYjFmNGFiYTBjZDcyZjA1MzE5NGVlMTkwMzFlNjlkZTljNWYxNWJmNDI0NzE2Zjg5NmI5MSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.2dpQu-x4R5KY0YjQ3XIzIRHm23DFWLWGaBq_YsRjHEc">

Sorry bout that. My mistake is that we are using 100% Business Edition for our around 40 installations..... And there this still does not exist in current release....

**Comment by fichtner** [comment]
Because it's a feature of FreeBSD 14.1. You can have your cake and eat it too, but have to stick to a release plan here.

**Comment by JSuenram** [comment]
> Because it's a feature of FreeBSD 14.1. You can have your cake and eat it too, but we have to stick to a release plan here which is 24.10...

Absolutely! This should not be understood as “criticism”, I just wanted to point out that I missed it because we are working with the business versions. So the feature is actually already there and will reach us with the next release of BE..... absolutely ok for me....
