### ISSUE TITLE
23.1.7+ routing problem 

### ISSUE THREAD

**Issue by ELERON23** [opnsense/core#6585]
Hi Opnsense Teams!,

Iv'e got an issue here that I cant seem to get resolved. On 23.1.6 what you see in this screen capture works just fine but any higher that 23.1.7+ it does not. Got 5 Single gateways configured as "FAR GATEWAYS" that are rechable VIA 192.168.12.0/24 via STATIC ROUTES 192.168.12.1 witch corresponds to my Cisco Wan interface.  
![image](https://github.com/opnsense/core/assets/133873840/694c5f98-30cc-4380-985e-e0653cadbdab)

![image](https://github.com/opnsense/core/assets/133873840/087a0225-d6c7-4fd5-a0c3-897f23ea0074)

To make it somehow kind of working in 23.1.7+, I need to make my Opnsense Lan Interface the gateway of 192.168.12.0/24 witch make no sence to me since it should be 192.168.12.1 to make matther worse the single gateway witch correspond to my Opnsense Lan Interface need's to have it's IP correspond to "dynamic" for my setup to work. 

What's working in 23.1.6+

![image](https://github.com/opnsense/core/assets/133873840/60924506-12fc-44f5-8d1d-603e32f4a16c)

And for some reason in 23.1.7 inside of the overview Tab, my lan interface dosent seem to care at all about the auto-detection of it's own defaut-gateway, with always seem to want to go to 192.168.1.0/28 with correspond to VLAN 40 running on my Cisco Router. 

Lan interface in 23.1.6:

![image](https://github.com/opnsense/core/assets/133873840/185f9858-820d-41dc-84c8-04fd8d4bf207)

Here is an example of my Routing table between 23.1.6 VS 23.1.7+

23.1.6:
![image](https://github.com/opnsense/core/assets/133873840/3f6c173a-ac59-466f-874e-9bfa243848ba)

23.1.7+
![image](https://github.com/opnsense/core/assets/133873840/94b8c5e6-89c7-4715-a51e-472d40036383)

In 23.1.6 you can clearly see that my "FAR NETWORK" are correctly showing. But in 23.1.7 without me changing anything nothing is getting picked up correctly. But as previously stated if I set the default Gateway of 192.168.12.0/24 to my Opnsense Lan interface thing start to kind of working again. 

Please help 👍 

Nick

Software version used and hardware type if relevant, e.g.:

OPNsense 23.6.1 (amd64, OpenSSL).
Intel® Xeon™  E5-1620 v2 @ 3.70GHz (4 cores, 8 threads)

**Comment by fichtner** [comment]
I think that would be https://github.com/opnsense/core/commit/25e2c0a301

# opnsense-patch 25e2c0a301


Cheers,
Franco

**Comment by fichtner** [comment]
PS: To be released in 23.1.9 this week.

**Comment by ELERON23** [comment]
Hi to all!,

Just updated again to 23.1.8 with the proposed patch and it's all working as before. @ChristopherZender Thank's for your input!

@fichtner Thank you,

Nick
