### ISSUE TITLE
Simulateneous editing of firewall rules can lead to unexpected results

### ISSUE THREAD

**Issue by cmitasch** [opnsense/core#6586]
**Describe the bug**

When two admins are editing the same rule simultaneously, this can lead to unexpected results.

**To Reproduce**

1. Admin1 and Admin2 load the floating rules list at the same time.
2. Admin1 deletes rule number 20 and applies the change
3. Admin2 clicks on "disable" for rule number 23 and applies the change
4. Admin2 has now disabled rule number 22 because the index id has changed in the meantime.

**Expected behavior**

I would expect a warning that an editing conflict might occur and the rule-set should be reloaded first.

**Environment**

OPNsense Business 23.4 (amd64)

**Comment by AdSchellevis** [comment]
For legacy components we can't really fix this behavior, all new mvc components use `uuids` as identification which doesn't come with these issues.
