### ISSUE TITLE
Subsecond value in Squid Access Log timestamp is incorrect

### ISSUE THREAD

**Issue by PacoTyson** [opnsense/core#6588]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**
In Services>Web Proxy>Access Log, the displayed time in column Date displays an incorrect subsecond value. For example : 

2023-05-31T21:40:01.**550000**

when the value stored in the file /var/log/squid/access.log is 
1685562001.**553**

It should be 
2023-05-31T21:40:01.**553**

**To Reproduce**

1. Go to '.Services>Web Proxy>Access Log'
2. Look at the Date column, see the value.

**Expected behavior**

Correct time is displayed

**Describe alternatives you considered**

The issue is located in /usr/local/opnsense/scripts/syslog/logformats/syslog.py , as shown by the backend command queryLog.py :
```
/usr/local/opnsense/scripts/syslog # ./queryLog.py --filename access --module squid --limit 1
{"filters":"","rows":[{"timestamp":"2023-05-31T21:40:01.550000","parser":"SysLogFormatEpoch","facility":null,"severity":null,"process_name":"","pid":null,"rnum":2,"line":"1186 192.168.1.2 TCP_TUNNEL\/200 6181 CONNECT update.qnap.com:443 - HIER_DIRECT\/143.204.231.116 -"}],"total_rows":2,"origin":"access"}

/usr/local/opnsense/scripts/syslog # tail -n1 /var/log/squid/access.log
1685562001.553   1186 192.168.10.2 TCP_TUNNEL/200 6181 CONNECT update.qnap.com:443 - HIER_DIRECT/143.204.231.116 -
```

Line 90 should be 
`        return len(line) > 15 and line[0:10].isdigit() and line[10] == '.' and line[11:14].isdigit()`
and line 94 : 
`        return datetime.datetime.fromtimestamp(float(self._line[0:14])).isoformat(timespec='milliseconds')`

After this change,
```
/usr/local/opnsense/scripts/syslog # ./queryLog.py --filename access --module squid --limit 1
{"filters":"","rows":[{"timestamp":"2023-05-31T21:40:01.553","parser":"SysLogFormatEpoch","facility":null,"severity":null,"process_name":"","pid":null,"rnum":2,"line":"1186 192.168.1.2 TCP_TUNNEL\/200 6181 CONNECT update.qnap.com:443 - HIER_DIRECT\/143.204.231.116 -"}],"total_rows":2,"origin":"access"}
```

**Environment**
OPNsense 23.1.9 (amd64, OpenSSL).

**Comment by AdSchellevis** [comment]
@PacoTyson looks reasonable, thanks! fixed in https://github.com/opnsense/core/commit/038d5b9bcf78ca7b97ab80513d9780062ca68374
