### ISSUE TITLE
Adding PF Rule Number to UI Firewall Rules tables for external log analysis/correlation

### ISSUE THREAD

**Issue by mikebutash** [opnsense/core#6590]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**

Today exporting firewall logs with OPNsense and anything pf in general produces as one of the export fields as "rulenum" or "rule-number" to identify what actual rule took action to generate the log. Attempting to cross-reference what the rule was and why an action was took, there was no UI way to correlate that syslog rulenum field to an actual configured rule.

**Describe the solution you like**

The most basic solution and a quick win would be to expose the rule number pf uses to index the rules, and display these in OPNsense Firewall Rules list along side the existing protocol, source, port, etc columns. This would allow at least any user to see the configured rule by number that performed the action from the log/siem perspective in the basic UI without needing shell access.

There also should be always made available that pf-based rulenum index value to Rules correlation for potential upstream enterprise log systems (splunk, wazuh, etc) or even humans to enrich their data directly, exposing them both UI and API means in this respect for association.

**Describe alternatives you considered**

Ideally pflogd could log something more descriptive of the rule vs. just a number would be helpful, such as including the description string would help correlate at a log level externally, but doesn't seem an option with pflogd after having looking at the man pages. This could be to avoid string parsing or length issue, or not ideal anyways, but not done today or likely to be added there if not already

**Additional context**

Today for any investigation from log events (pass, block) externally through a central syslog collector or siem to determine which Rule generated said event requires ssh access via an admin/root shell to see the rule numbers using "pfctl -s rules -vv" and finding the rule within those what was actually configured.

As a SOC or Network Analyst doing routine firewall log analysis, that's far from ideal as most never log into the shell as admin or root user, which then generates a ticket to the firewall guy to find out, and he'd even be hard pressed unless they know freebsd and pf reasonably well to even search for a solution as it did me.

Within OPNsense UI, your filter log view enriches this with the description as "Label" there making easier to find in Rules per issue #2034, but external log systems are not privy to the firewall rules directly, and only receive an ambiguous rule number to match against the firewall to investigate with. This rule number not found in the main UI anywhere hampers this.

As the only method of correlation from the log event to a given Rule, the rule numbers should be visible even optionally to display in the UI as part of the Rules list per interface.

syslog output example:
```
firewall.local filterlog[1090]: 102,,,fae559338f65e11c53669fc3642c93c2,eth0,match,pass,out,4,0x0,,64,50840,0,none,17,udp,56,10.0.0.129,172.17.0.1,46282,53,36
```
Here, rule-number == 102

pfctl output example:
```
pfctl -s rules -vv | grep @102
@102 pass out log all flags S/SA keep state allow-opts label "fae559338f65e11c53669fc3642c93c2"
```
Nowhere is 102 referenced in the UI to be useful here outside of finding it in current logs, which is negated if outside the local retention window of OPNsense.

The label (==fae559338f65e11c53669fc3642c93c2) could be used too, but for columnar display, the rule number would be best at least to match against for brevity.

**Comment by fichtner** [comment]
Hi @mikebutash,

The rule number is suboptimal as it can change after each reload and makes later correlation impossible. The labels help but only present a hash of the rule content. If the rules were MVC the UUID would be a more prominent identification method but we are not there yet. The label can be seen from the rule listing using the Description "?" header toggle.


Cheers,
Franco

**Comment by fichtner** [comment]
PS: https://xx.xx.xx.xx/ui/diagnostics/firewall/statistics#rules has what you are looking for and is already API-enabled...

**Comment by mikebutash** [comment]
@fichtner, thank you for that explanation and pointer to the statistics there, I've not had occasion to look there and didn't know about that!  It's been killing me for a while moving stuff around in my network between vlans using graylog to analyze.

I didn't take into consideration those weren't a permanent numeric convention, opnsense is still somewhat new to me, but used to the enterprise world with the likes of pan, fortigates, even cisco for 20+ years where I guess this sort of thing is figured out already.  

Thinking about my most recent experiences with like solutions, fortigates do use include static 16bit integer ID's that do not change upon reordering, sometimes to my dismay, but in this context makes sense as that's how I identify them from the fortianalyzer log component end.  They do also apply a uuid dynamically to rules, but those are relative to the local system even if same rule is distributed across many firewalls (ie using their fortimanager product).

Moving to an MVC pattern like Forti does would be necessary I suppose as the true feature request ultimately, but seems that needs to begin with PF more directly.

The lack of persistence for that numbering related to log output would likely will be a barrier to entry for opnsense in the enterprise world to use if an org uses a central logging/siem solution, which is where I'm coming from.  I would ask to see this request considered long-term even if not directly from this request.

Thank you for the workaround and consideration!
