### ISSUE TITLE
Monit: getting error /usr/local/etc/monitrc:14: syntax error 'reminder' when using "Not on" with empty events

### ISSUE THREAD

**Issue by devaux** [opnsense/core#6591]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

If you don't set any "events" in the Events of Monit tab and using the "Not on" function, you will get the following error: /usr/local/etc/monitrc:14: syntax error 'reminder' 

**To Reproduce**

1. Go to 'Services' => 'Monit' => 'Settings' => 'Alert Settings'
2. Click on 'Recipient'
3. Enable alert with "Not on" and "Nothing selected"
4. You get the following error "/usr/local/etc/monitrc:14: syntax error 'reminder'" when starting the service

**Expected behavior**

Service starts with all Event alert messages enabled for notification.
Or get an error that you have to select at least one Event 

OPNsense 23.1.8-amd64
FreeBSD 13.1-RELEASE-p7
OpenSSL 1.1.1t 7 Feb 2023
AMD GX-412TC SOC (4 cores, 4 threads)

**Comment by AdSchellevis** [comment]
what does `/usr/local/etc/monitrc` look like? (you can remove personal data if any exists there)

**Comment by devaux** [comment]
```
# DO NOT EDIT THIS FILE -- OPNsense auto-generated file

set httpd unixsocket /var/run/monit.sock
    allow localhost

set daemon 120 with start delay 120

set logfile syslog facility log_daemon



set mailserver 192.168.14.12 port 25

set alert notifications@domain.tld not on   reminder on 10 cycles

check system $HOST
   if memory usage is greater than 75% then alert
   if cpu usage is greater than 75% then alert
   if loadavg (1min) is greater than 8 then alert
   if loadavg (5min) is greater than 6 then alert

check filesystem RootFs with path "/"
   if space usage is greater than 75% then alert




include /usr/local/etc/monit.opnsense.d/*.conf

**Comment by AdSchellevis** [comment]
add a validation in https://github.com/opnsense/core/commit/7273bba2c1b0b06bc07dbe4c44677b3381968318

**Comment by fichtner** [comment]
# opnsense-patch 7273bba

This is not an issue of a missing validation. It's an issue of an apparent misconfiguration missing a vital option when using it...
