### ISSUE TITLE
Useless I/O eating up disks

### ISSUE THREAD

**Issue by williamdes** [opnsense/core#6596]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

A clear and concise description of what the bug is, including last known working version (if any).

*Tip*: to validate your setup was working with the previous version, use opnsense-revert (https://docs.opnsense.org/manual/opnsense_tools.html#opnsense-revert)

**To Reproduce**

1. Setup a normal OPNsense on ZFS
2. Enable logs and stuff into tmpfs
3. Have firewall aliases

**Expected behavior**

Stop re-writing my tables when they did not change

**Describe alternatives you considered**

Fix/reduce the useless writes.

**Screenshots**

The writes are constant
![Sélection_2023060320:55:15001](https://github.com/opnsense/core/assets/7784660/a48d633f-a07f-485d-bcc1-a513f95fb0cb)

The reads are okay
![Sélection_2023060320:55:35001](https://github.com/opnsense/core/assets/7784660/9cba47fc-02c8-431e-b94d-3c1e566f79b0)

**Additional context**

```sh
   	18:32	zfs snapshot zroot/ROOT/default@06jun2023t20h32
   	18:40	zfs snapshot zroot/ROOT/default@06jun2023t20h40
   	18:46	zfs diff zroot/ROOT/default@06jun2023t20h32 zroot/ROOT/default@06jun2023t20h40
```

```text
M	/root
M	/var/db/aliastables/Emails.self.txt
M	/var/db/aliastables/Emails.md5.txt
M	/var/db/aliastables/Emails.txt
M	/var/db/entropy/saved-entropy.3
M	/var/db/aliastables/Bogus_destinations.self.txt
M	/var/db/aliastables/Bogus_destinations.md5.txt
M	/var/db/aliastables/Bogus_destinations.txt
M	/var/db/aliastables/SAFE_HOSTS.self.txt
M	/var/db/aliastables/SAFE_HOSTS.md5.txt
M	/var/db/aliastables/SAFE_HOSTS.txt
M	/var/db/aliastables/xxx_Ambrose.self.txt
M	/var/db/aliastables/xxx_Ambrose.md5.txt
M	/var/db/aliastables/xxx_Ambrose.txt
M	/var/db/currentipsecpinghosts
M	/var/db/aliastables/bogonsv6.self.txt
M	/var/db/aliastables/__lan_network.self.txt
M	/var/db/aliastables/virusprot.self.txt
M	/var/db/aliastables/__lo0_network.self.txt
M	/var/db/aliastables/__opt1_network.self.txt
M	/var/db/aliastables/bogons.self.txt
M	/var/db/aliastables/sshlockout.self.txt
M	/var/db/aliastables/__wan_network.self.txt
M	/var/db/aliastables/crowdsec_blacklists.self.txt
M	/var/db/aliastables/crowdsec6_blacklists.self.txt
M	/var/db/aliastables/OOB_HOSTS.self.txt
M	/var/db/aliastables/OOB_HOSTS.md5.txt
M	/var/db/aliastables/OOB_HOSTS.txt

# Out of OPNsense scope
M	/var/db/crowdsec/data
M	/var/db/crowdsec/data/crowdsec.db
```

**Environment**

OPNsense latest on Proxmox

**Comment by williamdes** [comment]
Seems like some of the code is in https://github.com/opnsense/core/blob/6b40db6c2a6a9a1f140904a5bc6a5dd7462c4aeb/src/opnsense/scripts/filter/lib/alias/__init__.py#L161-L200

**Comment by williamdes** [comment]
And that saved entropy could be due to https://github.com/opnsense/src/blob/stable/23.7/libexec/save-entropy/save-entropy.sh

Maybe someone can explain to me why this entropy file is needed. Some freeBSD content on the web seems to indicate that it's some security feature

Maybe we can say the entropy files are out of the scope of this issue

**Comment by AdSchellevis** [comment]
I don't think this is super important (bigger fish to fry), but you could try to compare the contents of 

https://github.com/opnsense/core/blob/6b40db6c2a6a9a1f140904a5bc6a5dd7462c4aeb/src/opnsense/scripts/filter/lib/alias/__init__.py#L170

With what's about to be saved in 

https://github.com/opnsense/core/blob/6b40db6c2a6a9a1f140904a5bc6a5dd7462c4aeb/src/opnsense/scripts/filter/lib/alias/__init__.py#L187

Before writing the contents

**Comment by williamdes** [comment]
yes, exactly, I can contribute this
I was thinking to compare md5 files
Such changes are for master branch and so the next release ?

**Comment by williamdes** [comment]
About `/var/run/booting` and `/var/db/currentipsecpinghosts` empty
I do not see why they are written, can you help me find the sources that update them ?

**Comment by AdSchellevis** [comment]
> I was thinking to compare md5 files

I expect you can just compare content

> Such changes are for master branch and so the next release ?

Either a next minor or major depending on the change.

> About /var/run/booting ....

Knowing the system hasn't been booted (fully) yet. 
https://github.com/opnsense/core/blob/6b40db6c2a6a9a1f140904a5bc6a5dd7462c4aeb/src/etc/rc#L232

> ... and /var/db/currentipsecpinghosts empty files

IPsec script https://github.com/opnsense/core/blob/master/src/sbin/ping_hosts.sh monitoring endpoints. 

To be honest, I can't really imagine this is important at all. Chances of changes being accepted on these files are likely not very high. Preventing some writes for local cache files would probably be fine when there are no other downsides, files that are hardly being written to at all need a strong motivation to accept changes.

**Comment by williamdes** [comment]
Thanks, I am cloning repos. I really enjoy this quick feedback, seems like an active and listening community !
Will see what I can do to help when I am done with this subject

> Knowing the system hasn't been booted (fully) yet.

So it's a bug ? to write contents to this file, the system is booted since many hours 😄

**Comment by AdSchellevis** [comment]
> So it's a bug ? to write contents to this file, the system is booted since many hours 😄

That's debatable, in theory it could have used a check for the file combined with a `touch`, this is just less code with little harm in reality:

https://github.com/opnsense/core/blob/6b40db6c2a6a9a1f140904a5bc6a5dd7462c4aeb/src/etc/inc/config.inc#L52

**Comment by shtirlic** [comment]
JFYI: In my case it was Unbound DNS reporting  so I disabled it
![image](https://github.com/opnsense/core/assets/74080/05a29d50-0e12-4ede-b0cf-c5e73d0e9046)

And writes dropped from alsmost 300kb per second to ~40 kb per second
![graf](https://github.com/opnsense/core/assets/74080/af1dd017-5953-448f-9163-a0a8ac4c383f)
![pve](https://github.com/opnsense/core/assets/74080/056c7a01-1c2e-4af9-87d0-92ecb63a8853)

**Comment by doktornotor** [comment]
There are some much bigger fish to fry... 

https://github.com/opnsense/core/issues/7101

**Comment by AdSchellevis** [comment]
some changes are made, if new relevant io issues turn up, better open a new ticket after 24.1 is released.
