### ISSUE TITLE
dashboard could also include actually usage in MB

### ISSUE THREAD

**Issue by sjorge** [opnsense/core#66]
Currently the memory and swap usage are reported as:
``` 9% of 2016 MB ```
Having it read
``` 9% used 182/2016 MB ```

Would a small but nice change.

**Comment by AdSchellevis** [comment]
Without changing too much of the code, commit https://github.com/opnsense/core/commit/e6bc4237c5ad0fdd41301b24db6352750f32f6f9 contains usage statistics as reported by the underlying shell commands.
