### ISSUE TITLE
GUI not working over WAN Interface 400 Bad Request 

### ISSUE THREAD

**Issue by strawberryfly** [opnsense/core#6603]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [ X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [ X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

After upgrading from Version 23.1.6 to 23.1.9 the Web GUI says "400 Bad Request". This happens only over the public IP addresse, the internal address still works. This happens on muliple systems.

**To Reproduce**

1. Update to the latest Version 23.1.9
2. Try to access the GUI over WAN
3. See error "400 Bad Request" 

**Expected behavior**

GUI loads as before.

**Describe alternatives you considered**

-

**Relevant log files**

unfortunately there is nothing to see in the logs ...

**Environment**

Software version used and hardware type if relevant, e.g.:

I used different systems. Hardware OPNsense as well as VMs 
OPNsense 23.1.9 (amd64, OpenSSL).

**Comment by fichtner** [comment]
No relevant info given here. It's impossible to help without any configuration description.


Cheers,
Franco

**Comment by strawberryfly** [comment]
Sorry, for the little information. We have found the error. We are doing SSL decryption and the OPNsense was responding with the error message in the newer versions. We made an exception for the IPs now and everything works again.

Maybe it will help someone else in the future :)

**Comment by fichtner** [comment]
Ok no worries. Happy the problem was found 😊
