### ISSUE TITLE
Permit adding arbitrary (virtual) interfaces (created by third-party software) to be added to the configuration

### ISSUE THREAD

**Issue by noseshimself** [opnsense/core#6609]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [*] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [*] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**

I would like adding a generic tunneling solution to OPNSense routers and have their (synthetic) interfaces show up like any other "supported" interface for assignment.

**Describe the solution you like**

Add a sub-menu below "Interfaces -> other types" where it is possible to add random interface names that are outside OPNSense's control to be brought into the configuration so they can be used for assignment.

**Describe alternatives you considered**

Just renaming the interface to something known (like gre or such) is obviously insufficient.

Creating an OpenVPN server that is not started and abuse its interface name. Would require changes to the code, too.

Putting it by hand into /conf/config.xml but this will probably break sooner or later and should not be considered a very bright idea.

**Additional context**

I would like to add third-party VPN mesh software to the firewall itself instead of having a collection of single-purpose Raspberries to maintain in addition to the designated router itself. It just does not make sense. At the same time I don't believe in asking the project to add the latest development in VPN technology. Nevertheless adding Nebula to our clients' setups is definitely the better choice over anything included in OPNSense right now.

Adding Nebula (at least as a mesh node) to the OPNSense supported VPN list would be the best idea but that will probably bind resources needed somewhere else.

**Comment by AdSchellevis** [comment]
Start the VPN or service which creates the device, go to assignments and link the interface. Don’t forget to lock the interface. I don’t expect anything else is needed.

**Comment by fichtner** [comment]
It might have issues with the device name presented, but a custom plugin file will allow the devices to be assignable.

**Comment by noseshimself** [comment]
I guess I will have to file a different bug or feature request now...

I already didn't understand the requirement for VLAN names to contain a digit.

It did not work for a simple reason: I called the interface "nebula". After renaming it to "nebula3.14159" it showed up in assignments. Isn't it time to drop the requirement for interface names ending in digits?

**Comment by AdSchellevis** [comment]
> After renaming it to "nebula3.14159" it showed up in assignments. Isn't it time to drop the requirement for interface names ending in digits?

probably not, a unique name isn’t very scalable, usually the same type can be created multiple times.

> What is the recommended minimum for integration? An rc.d for starting and stopping or adding it to configd?

best read the development documentation at https://docs.opnsense.org first and checkout similar plugins in our repo.

**Comment by fichtner** [comment]
There is a number if VPN plugins to see what is necessary for implementation. About interface names I’m not 100% sure, but in general only known ones are missing (including tap/tun) but all unknown ones are passed through to the GUI for assignment.

**Comment by noseshimself** [comment]
> > After renaming it to "nebula3.14159" it showed up in assignments. Isn't it time to drop the requirement for interface names ending in digits?
> 
> probably not, a unique name isn’t very scalable, usually the same type can be created multiple times.

If you are auto-generating the names from OPNSense scripts that might be the case. If third party software is creating interfaces it should be considered "other peoples' problem"...

In the case of overlay meshes you usually have only one of them (there are a few special cases where you want to isolate software that is doing a lot of broadcasting/multicasting in its own mesh or where you want to interconnect meshes under separate management) but usually you get only 

Nebula is a bit worse in that regard: You put a fixed(!) interface name into the configuration file; if it is colliding with an existing interface all hell breaks loose. So you will add a separate name for every single config file you create and keep track of them anyway. Things are getting worse if other programs are creating interface names the same way.

**Comment by noseshimself** [comment]
> There is a number if VPN plugins to see what is necessary for implementation.

That's the special case where you are generating interfaces by software.

> About interface names I’m not 100% sure, but in general only known ones are missing (including tap/tun) but all unknown ones are passed through to the GUI for assignment.

I remember defining VLANs a few weeks ago and having to name them with trailing numbers even though "office" "servers" and "printers" would have done just as easily. There is a reason why FreeBSD added the ability to rename interfaces after the optional description was used  to simulate this feature (see OPNSense itself...).

The interface numbering thing is a thing of early history and has been kept since BSD3 (you could configure global driver features that way as front end to obscure ioctl()s). Linux showed us that calling everything net(number) did not improve things either -- just see the interface renaming taking place these days (and I don't know what's worse -- having the MAC address that might change later as part of the interface name or the path in the driver tree).

**Comment by fichtner** [comment]
Most of this is off-topic. If you want to use arbitrary content for device names fine, but 15 characters limit and identifiable names that are unique at the same time are rather difficult to pull off if you think about it.

**Comment by noseshimself** [comment]
Succeeding opened so many more questions that I will move over to the forum with it.

**Comment by noseshimself** [comment]
Request doesn't make sense like this.
