### ISSUE TITLE
Unbound can´t start due to special characters in the hostname

### ISSUE THREAD

**Issue by Tharguard** [opnsense/core#6614]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

An IoT-device (Brother sewing machine Innovis NV880E) has special characters in it´s hostname: 56;2;1;1.53
I think its the ";" sign
If i switch on the device on it gets an IP-address from dhcp and then unbound service works until i restart the service, 
the restart fails then.

**To Reproduce**

Turn device on

**Expected behavior**

Unbound works flawless ;)

**Describe alternatives you considered**

Assigning a hostname via DHCP is not the solution.

**Screenshots**

**Relevant log files**

2023-06-11T13:19:11 Critical unbound [45340:0] fatal error: Could not set up local zones
2023-06-11T13:19:11 Error unbound [45340:0] error: Bad local-data RR 56;2;1;1.60.local IN A 10.10.10.74
2023-06-11T13:19:11 Error unbound [45340:0] error: error parsing local-data at 34 '56;2;1;1.60.local IN A 10.10.10.74': Syntax error, could not parse the RR's TTL

**Additional context**

If i delete in /var/unbound/dhcpleases.conf this two lines unbound service starts again:

local-data-ptr: "10.10.10.74 56;2;1;1.53.local"
local-data: "56;2;1;1.53.local IN A 10.10.10.74"

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 23.1.9-amd64
FreeBSD 13.1-RELEASE-p7
OpenSSL 1.1.1t 7 Feb 2023

**Comment by swhite2** [comment]
Nice catch, invalid hostnames exist out in the wild and we should ignore them.

Can you try `# opnsense-patch 02aae56f0 e43c23fce`?

**Comment by Tharguard** [comment]
> Nice catch, invalid hostnames exist out in the wild and we should ignore them.
> 
> Can you try `# opnsense-patch 02aae56f0 e43c23fce`?

Thanks, this patch works ;)

**Comment by fichtner** [comment]
@swhite2 neat... would you mind applying something similar to dnsmasq watcher too?

**Comment by swhite2** [comment]
@fichtner on it
