### ISSUE TITLE
Port forwarding adds wrong subnet mask for virtual IPv6 addresses

### ISSUE THREAD

**Issue by tuxnet** [opnsense/core#6617]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [ x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x ] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

Virtual IPv6 addresses are set up as /32 rule and not as single host respectively /128

**To Reproduce**

1. Setup a IPv6 CARP address (/64)
2. At "Firewall: NAT: Port Forward" create a new entry
3. Select the created CARP address in the Virtual IPs section as the destination.
4. TCP/IP Version: IPv6
5. fill in the remaining data
6. click save
7. Check the destination address in the overview (should wrongly be /32)

**Expected behavior**

it should be /128 respectively a single host

**Additional context**
CLI check:
```bash
grep 2001:xxxx:xxxx:xxxx::100 /tmp/rules.debug
rdr on ix1_vlan1010 inet6 proto tcp from {any} to {2a02:xxxx:xxxx:xxxx::190/32} port {443} -> 2001:xxxx:xxxx:xxxx::100 port 8443 # To Webserver 01
```

**Environment**

OPNsense 23.1.9-amd64 (Openssl)
Intel® Xeon™ CPU (bare metal)

**Comment by fichtner** [comment]
b779ab46d1cb might do the trick... this was pretty wild

**Comment by AdSchellevis** [comment]
@fichtner on my end it still stores the /32, I was thinking to keep the original construct, but hide and disable the mask field. The mask isn't really needed, but since we offer it for the "special nets" we are posting it for processing too. Yesterday I couldn't find the time to check which part should be changed here, but you're certainly right, these legacy pages are the worst.

**Comment by fichtner** [comment]
if it was stored it won't be cleared. Initial assignment is ok as far as I can tell. It's not possible to decide afterwards if this was manual input or not... and VIPs seem to be stored without /xx attached which is consistent with the patch.

**Comment by fichtner** [comment]
either way is fine really, not attached to a particular fix

**Comment by AdSchellevis** [comment]
@fichtner I was thinking about https://github.com/opnsense/core/commit/0c76a9134d5aa9226aeeebd05ad5d81ba40716fc. (in which case we can revert the other commit). The page still has warnings and deprecation notices, but I didn't want to fix those now to avoid cluttering the view. (I can take a look later at that)

**Comment by fichtner** [comment]
No need to revert. It was a separate branch.

**Comment by fichtner** [comment]
modifying pconfig_to_address() likely requires fixing all caller page's JS

**Comment by fichtner** [comment]
"fixing" may be a harsh word but here it just means "to make things consistent" across all callers

**Comment by AdSchellevis** [comment]
@fichtner this https://github.com/opnsense/core/commit/fc93cdb0b060b8434defb0b6f2bd47a5df11eeb4 should be the last bit then to make things consistent (firewall_nat_npt_edit.php doesn't use the select/related fields)

**Comment by fichtner** [comment]
Thanks! Will test and close next week :)

**Comment by fichtner** [comment]
Ok, misread, will test anyway 😊

**Comment by fichtner** [comment]
Looks ok to me, into 23.1.10 it goes. 👍
