### ISSUE TITLE
Feature request: proper administration of aliases

### ISSUE THREAD

**Issue by roykrikke** [opnsense/core#6619]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**

No it is not related to a problem or bug. It's really a new feature.

**Describe the solution you like**

For the purpose of proper administration of aliases, I am missing a solution that gives me the possibility to add a description per e.g. port. In the example below, the list is big with no description of the e.g. ports and therefor not providing a proper overview. If would be great if this feature could be added for proper administration/documentation of aliases. This feature could also be  implemented for all category types.
<img width="887" alt="alias" src="https://github.com/opnsense/core/assets/37672838/700fd25b-cd7d-4559-a9cd-064c4c09a9b1">

**Describe alternatives you considered**

I have not found an alternative.

**Additional context**https://docs.github.com/github/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax

N/A

**Comment by AdSchellevis** [comment]
nesting, one port (or other object type) per entry combined in a new alias. (see also https://github.com/opnsense/core/issues/4190 https://forum.opnsense.org/index.php?topic=9302.0 https://docs.opnsense.org/manual/aliases.html#nesting )

**Comment by roykrikke** [comment]
Interesting read, this might very well be a deal breaker for me. Nesting aliases gets extremely dirty very quickly. Not a good way to properly set up and manage your aliases in my world.

I may be missing a technique that other people use. Does anyone have any tips on how to do it in a neat and manageable way?

**Comment by michmoor0725** [comment]
Nesting aliases is pretty common with other vendors. Is there a particular one that does what you are asking?

**Comment by roykrikke** [comment]
For me it was about proper documenting/administration of aliases. Functionally nothing is missing. Only the documentation part is not working as I was expecting.

https://forum.opnsense.org/index.php?topic=24037.0 is an interesting read for me.

**Comment by seteq** [comment]
I migrated from pfsense shortly and I'm also missing the per-entry description fields for documentation purposes.
Nesting aliases may also do the job but that's getting really messy in larger setups in my opinion.

**Comment by I-G-1-1** [comment]
I'm trying to migrate from OPNsense 18 to 25, but the impossibility to document each port is a deal breaker also for me.

I find it a regression and really a poor design choise.

Here is a screenshot of OPNsense 18:

<img width="1669" height="786" alt="Image" src="https://github.com/user-attachments/assets/665e3951-52a8-433f-a4cc-11951faffbf2" />

The idea of nesting aliases is not usefull: I have these ports for these services on server 1, in server 2 I have different ports for the same services.
Not mentioning the time wasted in clicks to create all these aliases.
Do you expect that for each service I have to create an alias for each port for each server?

Please reconsider this bad design choise and revert to a human friendly interface. For now I'll stay on my outdated OPNsense 18.
Thanks
