### ISSUE TITLE
Authentication / Radius - Add MSCHAPv2 support

### ISSUE THREAD

**Issue by AdSchellevis** [opnsense/core#6623]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**

Currently our RADIUS authentication only offers PAP authentication, while some setups require challenge/response type authentication.  With some small modifications to CHAP.php (https://github.com/opnsense/ports/commit/818fa8e936b810df683afd1cf8d77cdf19d0ace3) we are able to implement challenge response support for our RADIUS authenticator within the existing framework. 

** Additional context **

Example implementation in https://github.com/LawnGnome/php-radius/blob/master/examples/radius-auth.php

**Comment by AdSchellevis** [comment]
fixed in https://github.com/opnsense/core/commit/58b1ec1ea67910cafb791a445d4935f3697c13df

**Comment by mimugmail** [comment]
Nice :)
