### ISSUE TITLE
Unbound DNS > Domain Overrides | Deleting multiple selected

### ISSUE THREAD

**Issue by arnocs** [opnsense/core#6630]
When deleting multiple entries from the "Unbound DNS: Domain Overrides" only (top) one gets the deleted.
Not noticed it in previous versions.

**To Reproduce**
1. Goto: OPNsense > Services > Unbound DNS > Overrides > [Domain Overrides]
2. Have a couple of entries added if there are none.
3. Select all entries en click the 'trashcan' at the bottom right of the list.
4. Accept for deleting all entries.

**Issue**
Only the entry at the top of the list gets deleted.

**Expected behavior**
All selected entries should be removed at once.

**Describe alternatives you considered**
Tried with two and three entries, both cases deleting is from top down one entry at a time.

**Environment**
OPNsense-Business (DEC750) 23.4.1-8a631aed2

**Comment by AdSchellevis** [comment]
https://github.com/opnsense/core/commit/4e1562af51a54e9d7d810bda00d46d3d84f711eb should fix this, to try locally: 
```
opnsense-patch 4e1562a
```

@arnocs Thanks for the report!

**Comment by AdSchellevis** [comment]
@arnocs thanks! we'll try to push it in the next release.

**Comment by FirstS0ul** [comment]
Same again!
i can't mark multiple entries.

Type | opnsense |  
Version | 25.7.8 |  
Architecture | amd64 |  
Commit | f070f179f |  
Mirror | https://pkg.opnsense.org/FreeBSD:14:amd64/25.7 |  
Repositories | OPNsense (Priority: 11), mimugmail (Priority: 5) |  
Updated on | Sun Nov 30 19:39:41 CET 2025 |  
Checked on | Sun Nov 30 19:47:36 CET 2025

**Comment by AdSchellevis** [comment]
@FirstS0ul probably this https://github.com/opnsense/core/commit/0f3daf70e4a5eaf848dace40eb2f5bdabb2ef296

**Comment by FirstS0ul** [comment]
No, doenst work
Did an opnsense-patch 0f3daf7

PS: the API with del:     /api/unbound/settings/delHostOverride/
doenst work either.
look here: https://forum.opnsense.org/index.php?topic=47604.0

**Comment by AdSchellevis** [comment]
the api is highly unlikely as the gui works, but if the issue is that you can't actually select multiple items to delete, best open a ticket for that. my fix only solves the concurrency issue
