### ISSUE TITLE
Feature Request Kill all states for a rule

### ISSUE THREAD

**Issue by michmoor0725** [opnsense/core#6635]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**
No

A clear and concise description of what the problem is including your motivation for the request,
When adding rules, specifically reject/block rules, there should be an easier way of killing all states that match a permit rule.
So for example, if i have a single rule that says "Permit ANY ANY" and then later on create a rule that says "Block 192.168.1.1/32 to Anywhere", the states for 192.168.1.1 still exists for the permit any any rule. 

**Describe the solution you like**

There is an option now in pfsense to kill all flows for a rule which is useful in situations as i described above. Or maybe there is additional filtering upstream that needs to see new flows so you still need a method of killing all sessions that match a rule.

**Describe alternatives you considered**

Either disable then reenable a rule. 
Either hunt through the sessions table and kill all states for a IP or network

**Additional context**

Add any other context or screenshots about the feature request here or links to relevant forum thread or similar
No

**Comment by AdSchellevis** [comment]
From the rules page you can use the inspect button to find all associated states, adding a button on the states page to drop all for this (selected) rule shouldn't be to hard and prevents having to select all in the grid below. The firewall rules page is already quite full, not sure we do want to add more there for a relative edge case.

**Comment by michmoor0725** [comment]
Ah i see what you mean. Is the States table updated dynamically? Right now i see 18 entries. If I kill everything here will that take into account a 19th or 20th entry that comes up?

**Comment by AdSchellevis** [comment]
not at the moment, but if we would add an action to kill all for the selected rule, it will.

**Comment by AdSchellevis** [comment]
<img width="458" alt="image" src="https://github.com/opnsense/core/assets/9783985/d40e656e-d354-463c-9e79-6ded06a1a7d0">

It should work with https://github.com/opnsense/core/commit/1fa623cfd9d1afc4104918644389e31f4da096ee now, looks like we missed a spot in the previous code (not showing the "kill" button for the selected states).
