### ISSUE TITLE
radvd doesn't advertise GUA after reboot or IPv6 change

### ISSUE THREAD

**Issue by smart7324** [opnsense/core#6637]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

After a reboot radvd doesn't advertise my GUA. It is only advertising my ULA and therefore all clients don't get a public IPv6. Here is output of /var/etc/radvd.conf directly after reboot:
<img width="421" alt="01" src="https://github.com/opnsense/core/assets/34960772/7896b167-5f27-4d2e-af26-7f50514a6d54">

Restarting radvd service through the UI does fix the problem. Here is the output of /var/etc/radvd.conf after restarting the service:
<img width="407" alt="02" src="https://github.com/opnsense/core/assets/34960772/41d74207-ccb6-4851-a06b-509b007d1aa8">

The same also happens after a network reconnection and release of IPv6. Then radvd only advertises the ULA and clients don't get public IPv6. The issue didn't occur in the past (end of may 2023), but I can't exactly determine the version of OPNsense that worked.

**To Reproduce**

1. Reboot OPNsense on 23.1.10_1
2. radvd doesn't advertise GUA, only ULA
3. restart radvd service through UI
4. everything's working again

**Expected behavior**

radvd should also advertise GUA after reboot.

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense OPNsense 23.1.10_1-amd64
FreeBSD 13.1-RELEASE-p7
OpenSSL 1.1.1u 30 May 2023
Intel(R) Celeron(R) J6412 @ 2.00GHz (4 cores, 4 threads)

**Comment by fichtner** [comment]
Perhaps since 23.1.9? https://github.com/opnsense/changelog/blob/06022edff310f0e305bae06aecf9ebc5b087f14f/community/23.1/23.1.9#L22

**Comment by fichtner** [comment]
I wonder if DAD is the problem here? 31368fb15

# opnsense-patch 31368fb15

**Comment by smart7324** [comment]
Hi, thanks for your fast reply!
It worked for 2 reboots now, but then it didn't work on the 3rd reboot... Also directly after applying the patch, radvd only advertised the ULA. 

And if I'm clicking the "reload"-Button under Interfaces -> Overview -> WAN Interface, I have the same problem every time and radvd is missing the GUA.

I'm having these in my logs, maybe that helps?
<img width="1124" alt="Bildschirmfoto 2023-06-28 um 07 58 18" src="https://github.com/opnsense/core/assets/34960772/bb7db458-e11b-46d9-9d7e-872b892f2256">

**Comment by fichtner** [comment]
Hmm the only reason it fails is because the address is either not on the interface when it happens or not in a usable state (tentative -- hence the DAD patch). Just to be sure this is a DHCPv6 WAN with a LAN tracking and "Allow manual adjustment of DHCPv6 and Router Advertisements" option unset?

**Comment by fichtner** [comment]
PS: not getting a WAN address is a more serious issue.. no WAN address no LAN IPv6 to bring to radvd in the first place.

**Comment by smart7324** [comment]
Yes, it's a DHCPv6 WAN with a LAN tracking interface. "Allow manual adjustment of DHCPv6 and Router Advertisements" is actually ticked. Is this a problem?

**Comment by fichtner** [comment]
PPPoE or normal?

**Comment by smart7324** [comment]
So do you think it could be a problem with my ISP? I didn't change anything and it was working fine for months. Yesterday, I had a short outage of my internet connection (1-2 minutes) but then everything recovered, except clients didn't get IPv6 addresses. And I then found out, that radvd isn't advertising it, even after reboots.

Normal, no PPPoE

<img width="1222" alt="Bildschirmfoto 2023-06-28 um 08 07 21" src="https://github.com/opnsense/core/assets/34960772/10d1bf4a-a80c-4fa5-9e5b-0936728b6dad">

<img width="777" alt="Bildschirmfoto 2023-06-28 um 08 07 52" src="https://github.com/opnsense/core/assets/34960772/8e970c3d-ee62-4185-bb4a-a3dcdc7317fd">

**Comment by fichtner** [comment]
I think 165327ba72d2 is a problem, but what it's doing is not a fix... it's just obscuring the situation. Can you revert this one?

    # opnsense-patch 165327ba72d2

**Comment by smart7324** [comment]
Ok, I did your command, did it actually revert the patch or did it apply it?
<img width="644" alt="Bildschirmfoto 2023-06-28 um 08 17 26" src="https://github.com/opnsense/core/assets/34960772/57d7c35d-c1c5-4bd4-9ab8-e5fb9ad05633">

I then did a reboot and still radvd only advertises ULA. After pressing the "reload" button on my WAN interface, it also doesn't work. Still have this in my logs, but I am getting a IPv6 on WAN side and a prefix. Also I can ping ipv6.google.com.

<img width="1185" alt="Bildschirmfoto 2023-06-28 um 08 21 39" src="https://github.com/opnsense/core/assets/34960772/5c676b73-8b2e-45f7-9840-d67a608e6053">

**Comment by fichtner** [comment]
It did revert because the patch was already in place... but that was expected. opnsense-patch does both... rerunning it brings it back to where it was.

I tried to reproduce this here but I cannot. I need a better log (general system log) from you with Interfaces: Settings:  Log level set to "Info" and reboot into problematic situation.

**Comment by fichtner** [comment]
"Failed to detect IP" is still suspicious...after having acquired an IP allegedly. 👀

**Comment by smart7324** [comment]
Hm okay, Im happy to provide more logs. How can I change the system log level?

Yes, I also find this looks suspicious, as I'm getting an IPv6 and it's working fine.

**Comment by fichtner** [comment]
> Interfaces: Settings: Log level set to "Info" and reboot into problematic situation.

A log text dump wold be better. It prints a lot of upstream DHCPv6 information.

**Comment by smart7324** [comment]
Ok, I captured the log, how can I sent it to you? (don't want to post it publicly)

**Comment by fichtner** [comment]
franco AT opnsense DOT org

**Comment by smart7324** [comment]
Ok, I sent it to you.

**Comment by CallMeR** [comment]
I think I ran into the same problem as in this thread. 

IPv4 PPPoE, DHCPv6 WAN with a LAN tracking    

"Allow manual adjustment of DHCPv6 and Router Advertisements" option is **set** .

This problem occurs frequently since automatic update to 23.1.10_1 (maybe 23.1.10 ) version.   

This problem was not perceived to occur in 23.1.9.

**Comment by fichtner** [comment]
There is no change in 23.1.10 that sticks out here. Some people have reported this on older 23.1.x in the forum as well.

I need to some time to look at @smart7324's log, but what is common is: "/usr/local/etc/rc.newwanipv6: Failed to detect IP for WAN[wan]" which doesn't make much sense after grabbing and IPv6 address from the provider...

**Comment by CallMeR** [comment]
![image](https://github.com/opnsense/core/assets/11908641/3dbc8869-da3b-4958-b421-bd510f79f630)

**Comment by CallMeR** [comment]
It can be confirmed that the WAN and LAN have obtained IPv6 addresses, but OPNsense have not advertised GUA Prefix to intranet devices.

**Comment by fichtner** [comment]
It's a little difficult to process... you say LAN has an IPv6 but the code complains about bridge0 having no IPv6 address.

**Comment by smart7324** [comment]
And I’m also 100% sure that I get an ipv6 but I get the „ Failed to detect IP“. Different text, but could this be related to @CallMeR‘s having no ipv6?

**Comment by CallMeR** [comment]
All my configuration details are documented in this document, but in Chinese.
[opnsense_configuration_notes](https://github.com/CallMeR/opnsense_configuration_notes)

This log shows that OPNsense's radvd could not find the IPv6 address on bridge0. This bridge0 is a pure bridge that operates according to the official wiki.

My ISP will provide dynamic IPv6 prefixes, OPNsense will automatically restart the WAN port every 3 days, and after each WAN port restart, it will get a new IPv6 prefix, and today I found that after the WAN port restarts, all my intranet devices (Linux servers and mobile phones) have lost IPv6 connectivity.  

So I checked OPNsense to see if it was because I didn't get the IPv6 prefix, and the result was that OPNsense's WAN and LAN had IPv6 addresses, but it didn't advertise the prefix to the intranet. 

I can only fix this at the moment by restarting OPNsense multiple times.

That log screenshot was generated today during multiple reboots.

It seems that radvd started first, but after it started, it found that there was no IPv6 address on the LAN (bridge0), and then the WAN correctly got the IPv6 prefix, so OPNsense's IPv6 returned to normal.

However, if OPNsense is not restarted, but simply redials PPPoE, radvd will no longer advertise new IPv6 prefixes to the intranet, and this situation can be stably reproduced.

**Comment by fichtner** [comment]
The PPPoE is a bit of a complication here... the bridge likely as well but first things first. It looks like @smart7324 may be seeing a driver issue due to VLAN configuration bringing the interface down when they should not be down. Might be specific to `igc(4)` driver.

**Comment by smart7324** [comment]
Good morning @fichtner 
Today I changed my ISP from Vodafone Cable to DTAG FTTH and I still have the same problem. After every reconnect or reboot radvd doesn't advertise my GUA. So I still need help :)

**Comment by fichtner** [comment]
Let’s figure this out. Likely a timing issue with the hardware then as previously considered. But needs to wait 2 weeks since I’m not in the office before that.


Cheers,
Franco

**Comment by smart7324** [comment]
Yes, thank you, Franco :)

Will a release (clicked at Interfaces -> wan) also lead to the same interface up and down like a reboot and can therefore cause the issue?

**Comment by meyergru** [comment]
I seem to have the same problem, not on reboot, but once after a while. It appears on one of three systems with DG as ISP (dhcp with tracking interface, no PPPoE). I do not know what causes the loss after a while, because the WAN connection seems stable and the prefix does not change at all. For now, I have a cron job to restart radvd every hour.

Is there a patch I can try already with 23.1.11?

**Comment by meyergru** [comment]
I now have found that when I reconfigure the WAN interface (which does not get an own IPv6, only prefixes are acquired), the same problem happens: /var/etc/radvd.conf does not contain the prefix.

The log shows:

```
<13>1 2023-07-02T13:23:58+02:00 OPNsense.jmg dhcp6c 66216 - [meta sequenceId="1"] RTSOLD script - Sending SIGHUP to dhcp6c
<13>1 2023-07-02T13:23:59+02:00 OPNsense.jmg dhcp6c 68748 - [meta sequenceId="2"] dhcp6c_script: REQUEST on igc3 executing
<13>1 2023-07-02T13:23:59+02:00 OPNsense.jmg dhcp6c 72872 - [meta sequenceId="3"] dhcp6c_script: REQUEST on igc3 renewal
<13>1 2023-07-02T13:24:00+02:00 OPNsense.jmg opnsense 75082 - [meta sequenceId="4"] /usr/local/etc/rc.newwanipv6: Failed to detect IP for WAN[wan]
```

Nothing valuable after that. It seems that sometimes, renewal of either DHCPv4 or DHCPv6 gets a renewal on WAN, the IPv6 assigment is too slow before radvd gets restarted. When I look afterwards, the LAN interface has an IPv6, but obviously not yet when radvd is triggered.

**Comment by smart7324** [comment]
Interesting observation! So you get the same "/usr/local/etc/rc.newwanipv6: Failed to detect IP for WAN[wan]" log message. I also thought it would help, if radvd would be triggered some seconds later. Now the question is: What script is triggering radvd and can we add timeout here?

**Comment by meyergru** [comment]
A short pause before radvd is restarted might even suffice. The script that creates radvd.conf and restarts it must wait until the IPV6 has settled. But how exactly and on what interfaces is certainly not easy to work out.

Also note that the log message does not give away that my assumption is correct: as I said, I actually do not get any global IPv6 on my WAN interface, so the message is to be expected in my case. It is the SLAAC prefix on LAN that **seems** missing.
But that I cannot prove and I cannot say which pause would suffice as I lack logging for the exact course of events (dhcpv4 renewal, dhcpv6 renewal, interface IPv6 tracking, radvd restart). And it does happen only for one of my three systems.

**Comment by fichtner** [comment]
https://github.com/opnsense/core/commit/31368fb15aae9a2764c10523f2b70c4b27578ca8 did add a sleep which was said to be ineffective ;)

**Comment by uholeschak** [comment]
I also have the problem, that /var/etc/radvd.conf is sometimes not correctly updated after pppoe0 ipv6 address change. Only manual restart of the service on the "Services: Router Advertisements:" page seems to fix it.
Also tried /usr/local/etc/rc.newwanipv6 pppoe0 -f
but there is no change.
What is the correct way to update /var/etc/radvd.conf from a script?

**Comment by meyergru** [comment]
See here for a band-aid: https://forum.opnsense.org/index.php?topic=19032.msg90983#msg90983

**Comment by uholeschak** [comment]
Thanks I have added a cron job now, hope that this fixes the problem.
I would prefer to use monit and restart radvd only if it fails. But I don't know what is a useful test condition for this.

**Comment by meyergru** [comment]
Actually, the real fix would be to solve the timing problem (only assuming here).

The condition is that the /var/etc/radvd.conf does not contain an IPv6 for the interface, but for the band-aid this does not matter: The prefix lifetimes are long enough that restarting radvd every hour is sufficient (at least for me it is),

**Comment by smart7324** [comment]
Thanks for the cronjob! 

I think this does not solve the problem after a reboot, where radvd doesn’t advertise the GUA, but only the ULA. So we still need a real fix for the timing problem.

**Comment by uholeschak** [comment]
The question is, how to formulate this in a monit condition, that /var/etc/radvd.conf is not containing the IPv6 oft the interface.

**Comment by gek64** [comment]
Same problem, after restarting radvd service, everything works fine.
I use this cron.d script to restart the radvd service after reboot

```shell
echo "@reboot root (sleep 60; /usr/local/sbin/pluginctl -s radvd restart)" > /etc/cron.d/radvd
/etc/rc.d/cron restart
```

**Comment by fichtner** [comment]
Ok, back at the office now... it's a bit mysterious this starts to become more common and nobody pinpointed this to a specific 23.1.x release yet. For now let's try this debugging patch [f77941f](https://github.com/opnsense/core/commit/f77941fc8d66428e3dcaade24647ba3bc02b435e) and see if it reveals something:

    # opnsense-patch f77941f

There should be a log in the system log when the renew mismatch happens... if the address is actually already there. If it isn't I'm unsure why not while running the post-address scripts... ;)


Cheers,
Franco

**Comment by fichtner** [comment]
That being said the master branch works a litte different now. It would be good if someone could compare against latest development release.

**Comment by meyergru** [comment]
Alas, I cannot reliably test this as it does not happen after a reboot for me, but mostly only after days of operation. I can only determine if a fix works after a longer period of time and even then, the result will not be 100% certain. Maybe someone who has the problem right after boot should try this patch.

**Comment by CallMeR** [comment]
Maybe this is a problem with radvd, after all, it seems that the version of radvd used by OPNsense is 2 years old, and there is no new release version of radvd recently

https://github.com/radvd-project/radvd/commits/master

**Comment by meyergru** [comment]
Even the most bug-free version of radvd cannot work correctly when its configuration file does not contain the neccessary information. I highly doubt that radvd is the culprit here.

**Comment by fichtner** [comment]
IMO it has been speculated too much around this area but too little investigation into the timing issue has taken place. The config file is definitely wrong which has been confirmed a few weeks ago but as I said it hasn't been pinpointed to a version 23.1.x or actual patch in that version plus nobody had the ability to debug this on their own. It might be the holiday season but in general the reliance on the core team is a bit too much or I have to assume IPv6 is not that integral after all.


Cheers,
Franco

**Comment by fichtner** [comment]
None of this is really true in the grand scheme of things. 23.1.11 has no interface changes and we do have a "force" mechanism to reload anyway if dhcp6c wants to.

https://github.com/opnsense/changelog/blob/master/community/23.1/23.1.11

**Comment by uholeschak** [comment]
At least in my case the radvd update has stopped working always when the IPV6 address changes and it never repairs.
I also tried:
/usr/local/etc/rc.newwanipv6 pppoe0 -f
but this also not updating the config file.
Only
/usr/local/sbin/pluginctl -s radvd restart
helps.

**Comment by uholeschak** [comment]
These are all extracted error messages when the update fails:
![grafik](https://github.com/opnsense/core/assets/7830051/87784be6-1781-42ec-9252-b14b57f85651)

**Comment by uholeschak** [comment]
Perhaps the `Network is unreachable` is the problem ...

**Comment by uholeschak** [comment]
I have seen the network is not reachable is at the beginning if the disconnect, this is not the problem.
I have added also the warning level to the output, otherwise there are too many lines.
Where is the log file stored? Then I could attach it.
The patch is not applied.
![grafik](https://github.com/opnsense/core/assets/7830051/0d5304e0-790c-4b05-8073-088aa1caf3ba)

**Comment by fichtner** [comment]
@uholeschak what I can see is that the disconnect forces a reconnect running multiple invocations of the script at the same time. The "force" ones are being run correctly but might be missing their target because of overlaps. For me personally it's difficult to trace this with PPPoE and a bridge involved. It (the bridge) might make the whole situation more unstable than necessary.

**Comment by uholeschak** [comment]
Is there a way to bridge multiple interfaces without using a bridge?

**Comment by smart7324** [comment]
Hi @fichtner, I have applied the patch and did a reboot, here are parts of the log (I sent you the full log via e-mail):
It seems that it can't get a IPv6& for WAN interface, but then 3 seconds later it detects the IPv6...


`<13>1 2023-07-17T19:58:40+02:00 opnsense.local opnsense 47813 - [meta sequenceId="48"] /usr/local/etc/rc.newwanipv6: Failed to detect IP for WAN[wan]
<13>1 2023-07-17T19:58:40+02:00 opnsense.local dhcp6c 83314 - [meta sequenceId="49"] RTSOLD script - Sending SIGHUP to dhcp6c
<13>1 2023-07-17T19:58:40+02:00 opnsense.local opnsense 38253 - [meta sequenceId="50"] /usr/local/etc/rc.newwanip: plugins_configure vpn (,wan)
<13>1 2023-07-17T19:58:40+02:00 opnsense.local opnsense 38253 - [meta sequenceId="51"] /usr/local/etc/rc.newwanip: plugins_configure vpn (execute task : ipsec_configure_do(,wan))
<13>1 2023-07-17T19:58:40+02:00 opnsense.local opnsense 38253 - [meta sequenceId="52"] /usr/local/etc/rc.newwanip: plugins_configure vpn (execute task : openvpn_configure_do(,wan))
<13>1 2023-07-17T19:58:40+02:00 opnsense.local opnsense 38253 - [meta sequenceId="53"] /usr/local/etc/rc.newwanip: plugins_configure newwanip (,wan)
<13>1 2023-07-17T19:58:40+02:00 opnsense.local opnsense 38253 - [meta sequenceId="54"] /usr/local/etc/rc.newwanip: plugins_configure newwanip (execute task : dnsmasq_configure_do())
<13>1 2023-07-17T19:58:40+02:00 opnsense.local opnsense 38253 - [meta sequenceId="55"] /usr/local/etc/rc.newwanip: plugins_configure newwanip (execute task : ntpd_configure_do())
<13>1 2023-07-17T19:58:42+02:00 opnsense.local opnsense 38253 - [meta sequenceId="56"] /usr/local/etc/rc.newwanip: plugins_configure newwanip (execute task : opendns_configure_do())
<13>1 2023-07-17T19:58:42+02:00 opnsense.local opnsense 38253 - [meta sequenceId="57"] /usr/local/etc/rc.newwanip: plugins_configure newwanip (execute task : openssh_configure_do(,wan))
<13>1 2023-07-17T19:58:42+02:00 opnsense.local opnsense 38253 - [meta sequenceId="58"] /usr/local/etc/rc.newwanip: plugins_configure newwanip (execute task : unbound_configure_do(,wan))
<13>1 2023-07-17T19:58:42+02:00 opnsense.local opnsense 38253 - [meta sequenceId="59"] /usr/local/etc/rc.newwanip: plugins_configure newwanip (execute task : vxlan_configure_do())
<13>1 2023-07-17T19:58:42+02:00 opnsense.local opnsense 38253 - [meta sequenceId="60"] /usr/local/etc/rc.newwanip: plugins_configure newwanip (execute task : webgui_configure_do(,wan))
<13>1 2023-07-17T19:58:42+02:00 opnsense.local dhcp6c 50010 - [meta sequenceId="61"] dhcp6c_script: REQUEST on pppoe0 executing
<13>1 2023-07-17T19:58:42+02:00 opnsense.local dhcp6c 55555 - [meta sequenceId="62"] dhcp6c_script: REQUEST on pppoe0 renewal
<12>1 2023-07-17T19:58:42+02:00 opnsense.local opnsense 56411 - [meta sequenceId="63"] /usr/local/etc/rc.newwanipv6: interfaces_primary_address6(): rejecting other address 192.*****CHANGED*****
<12>1 2023-07-17T19:58:42+02:00 opnsense.local opnsense 56411 - [meta sequenceId="64"] /usr/local/etc/rc.newwanipv6: interfaces_primary_address6(): rejecting other address fd12:*****CHANGED*****
<12>1 2023-07-17T19:58:42+02:00 opnsense.local opnsense 56411 - [meta sequenceId="65"] /usr/local/etc/rc.newwanipv6: interfaces_primary_address6(): rejecting tentative address 2003:*****CHANGED*****
<12>1 2023-07-17T19:58:42+02:00 opnsense.local opnsense 56411 - [meta sequenceId="66"] /usr/local/etc/rc.newwanipv6: interfaces_primary_address6(): rejecting other address fe80::*****CHANGED*****
<12>1 2023-07-17T19:58:43+02:00 opnsense.local opnsense 56411 - [meta sequenceId="67"] /usr/local/etc/rc.newwanipv6: interfaces_primary_address6(): rejecting other address 87.*****CHANGED*****
<13>1 2023-07-17T19:58:43+02:00 opnsense.local opnsense 56411 - [meta sequenceId="68"] /usr/local/etc/rc.newwanipv6: IP renewal starting (new: 2003:*****CHANGED*****, old: , interface: WAN[wan], device: pppoe0, force: no)`

**Comment by fichtner** [comment]
Thanks for everyone participating. 9e4463a may improve the situation after understanding it a bit better. It can be installed on 23.1.11:

    # opnsense-patch 9e4463a

Make sure to test a reboot scenario. I think I know why this cannot be reproduced here easily... FritzBox in front of the OPNsense answers DHCP requests quickly enough for the boot to serialise the dynamic reload of the IPv6 connectivity script.


Cheers,
Franco

**Comment by smart7324** [comment]
So I've applied the patch and did a reboot twice. It seems that the timing-problem is fixed now, no `Failed to detect IP for WAN[wan]` in syslog.

But the issue with radvd is still the same. No GUA advertised after reboot. A manual restart of radvd service through UI fixes the issue. 

I sent you the 2 syslogs of the reboots.

**Comment by sbellon** [comment]
Sadly `opnsense-patch 9e4463a` makes the situation worse for me:

- **without** the patch (i.e. plain vanilla 23.1.11), `dhcpd6` starts after a reboot and I only have to restart `radvd` manually.
- **with** the patch, `dhcpd6` does not start after a reboot, so I have to start that service manually and afterwards I also have to restart `radvd` manually.

I have rebooted several times with each configuration (23.1.11 with and without patch 9e4463a), and it is completely reproducible each time.

**Comment by fichtner** [comment]
@sbellon I'd appreciate the logs. The commonality is that during your bootup DHCPv6 doesn't have enough time to initialise but why it misses the mark here is pretty strange as the script is still running eventually.

@smart7324 so the radvd issue might be more with the configuration handling than anything else then. I do wonder if it even has the prefix in the file at some point and then it's being removed again? I will try to think about it while releasing 23.7-RC1 today and hopefully propose another patch tomorrow.


Cheers,
Franco

**Comment by smart7324** [comment]
@fichtner that sounds good, thanks for your effort!

@sbellon I am not using dhcpv6, so I cannot say if its working after the patch. Anyways in my opinion dhcpv6 is not necessary to get a stable IPv6 configuration. Clients can just use SLAAC and everything's working fine (if radvd is working of course ;)...)

**Comment by sbellon** [comment]
@fichtner What logs do you want? Those of a reboot *with* patch applied or those of a reboot *without* the patch applied (or both)? Where should I send them to?

@smart7324 I'm well aware that you can "use IPv6" with just SLAAC and without dhcpd6, but (for reasons) I need ULAs in my network and also make available the IPv6 DNS via ULA. My understanding is that I need a Virtual IPv6 ULA and dhcpd6 for this to work. At least, it didn't work with just radvd (I still have tagged configuration backups to look at the diffs what worked and what didn't and how I ended up with this setup). TLDR: I have an IPv6 setup with different VLANs (and their different configurations) that works with GNU/Linux, Windows, Android, iOS clients and all the various IoT devices very well and don't want to change that by turning off dhcpd6.

**Comment by fichtner** [comment]
@sbellon ideally both but one with the patch would help already

**Comment by smart7324** [comment]
@sbellon I can imagine of these reasons. I also need ULA and advertise a fd address as DNS server to make sure that all my clients are using my Adguard Home for DNS requests. This is working fine with just radvd and completely without DHCPv6. I also thought that I would need DHCPv6 for that, but I then gave it a try completely without it and it’s working perfectly fine for months now.

**Comment by sbellon** [comment]
> @sbellon ideally both but one with the patch would help already

Ok, I have both logs (boot with patch and without) available ... where can I send them?

**Comment by fichtner** [comment]
franco AT opnsense DOT org

**Comment by sbellon** [comment]
Just for the record (and in case something got lost): I sent them last Thursday.

**Comment by fichtner** [comment]
@sbellon yes I got a couple. RC2 is out now and I'll be going through all of them tomorrow and send individual responses back.

**Comment by fichtner** [comment]
As a side note the original radvd advertise bug was likely found in the FreeBSD kernel just a few days ago. For more details see https://github.com/opnsense/core/issues/4338#issuecomment-1648330954

**Comment by fichtner** [comment]
Can you guys try the improved version of the patch? 47775a0

    # opnsense-revert opnsense
    # opnsense-patch 47775a0


Thanks,
Franco

**Comment by fichtner** [comment]
Do you mean the DHCPv6 service from the service widget? I saw this not working earlier but it should restart these again now with that in place unless it didn’t run correctly. Logs would be good again.

**Comment by fichtner** [comment]
Okay, `flock() `doesn't work how I would expect at all. The proposed solution works if the exiting process would unlock the file automatically which it doesn't and the lock lingers after the process is gone, which is why the second reload does not come through. We should be having a working state by tomorrow. :)


Cheers,
Franco

**Comment by fichtner** [comment]
So @AdSchellevis and me had a little late night session to get to the bottom and basically 9184457 was missing which is only very obvious in hindsight. Now it should work as expected:

    # opnsense-revert opnsense
    # opnsense-patch d11029b

(the full backport is d11029b)


Cheers,
Franco

**Comment by smart7324** [comment]
It's working! Thanks a lot for your effort @fichtner ;) and also thanks to @AdSchellevis 

So my issue is solved!

**Comment by sbellon** [comment]
Yes, indeed. At least now, first reboot after applying latest patch: dhcpd6 runs and radvd also doesn't need a manual restart. Judging from one reboot only, but this looks good.

Also thanks for your continuous effort. :-)

**Comment by fichtner** [comment]
Sorry, this was harder than anticipated. Thanks for bearing with me 😊

**Comment by fichtner** [comment]
@meyergru did you have a chance to test this as well?

**Comment by meyergru** [comment]
With 23.7 right at the gates, no, at least not in a meaningful manner, because my problem was that only sometimes, maybe once in a month, the prefixes disappeared. Thus, a long-term test is needed in order to verify if it works in my scenario. But the code looks good now, it actually seems to have been a sequencing error, as I assumed from the symptoms.

**Comment by fichtner** [comment]
Ok, I'll close then and release 23.7-RC3 with it. Thanks all! ❤️
