### ISSUE TITLE
VPN/IPSEC/Key Pairs - RSA Keys are always generated 2048 Bit

### ISSUE THREAD

**Issue by Monviech** [opnsense/core#6638]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

Yes, I couldn't find any bug about RSA generation in open or closed issues.

**Describe the bug**

When using the "generate" Option in VPN/IPSEC/Key Pairs, it always generates 2048 Bit RSA keys, even if you select 4096 or 1024.

**To Reproduce**

1. Go to 'VPN/IPSEC/Key Pairs'
2. Click on 'Add'
3. Click on 'Key Type - RSA - 4096 BIT - "Generate new."'
4. See that the generated RSA Key is 2048 Bit

**Expected behavior**

The generated RSA Key should be 4096 Bit.

**Describe alternatives you considered**

Workaround is to use Openssl directly in the opnsense shell and then manually input the keys into the Public and Private Key Windows. Even though it says 2048 in Key Type, it will then actually be a 4096 Key. The Key has to be inputted in 1 Line with tags, or it fails to load into charon.

**Additional context**

**Environment**

Versions	OPNsense 23.4-amd64
FreeBSD 13.1-RELEASE-p7
OpenSSL 1.1.1t 7 Feb 2023
DEC2750 Security Appliance

**Comment by AdSchellevis** [comment]
the `ECDSA` types seem to work normally, but `openssl_pkey_new()` seems to ignore `private_key_bits` here 

https://github.com/opnsense/core/blob/54f2ed4fa703c7712d03318a91604f010544988a/src/opnsense/mvc/app/controllers/OPNsense/IPsec/Api/KeyPairsController.php#L127-L153

**Comment by Monviech** [comment]
> the `ECDSA` types seem to work normally, but `openssl_pkey_new()` seems to ignore `private_key_bits` here
> 
> https://github.com/opnsense/core/blob/54f2ed4fa703c7712d03318a91604f010544988a/src/opnsense/mvc/app/controllers/OPNsense/IPsec/Api/KeyPairsController.php#L127-L153

Ich habe folgendes zum Code hinzugefügt und jetzt funktioniert die Auswahl in der GUI mit allen RSA Schlüsselgrößen:

`$size = intval($size);`

`{
    $certtype = null;
    $keylength = null;
    $attrs = [];
    $size = intval($size); // Wandeln Sie $size in einen Integer um
    if ($type == 'rsa') {
        if (!empty($size) && !in_array($size, [1024, 2048, 3072, 4096, 8192])) {
            return ['status' => 'failed', 'message' => sprintf('invalid key size %s', $size)];
        }
        $attrs['private_key_type'] = OPENSSL_KEYTYPE_RSA;
        $attrs['private_key_bits'] = !empty($size) ? $size : 2048;`

**Comment by AdSchellevis** [comment]
@Monviech thanks! this https://github.com/opnsense/core/commit/c5580da6c96b53e934fc44c477bb02df9d131fd3 should do the trick then
