### ISSUE TITLE
pretty up ca_chain() output

### ISSUE THREAD

**Issue by fichtner** [opnsense/core#664]
For discussion see #662.

While there, invert the weirdness that is:

    $validconfig = openvpn_client_export_validate_config($srvid, $usrid, $crtid);
     	if ($validconfig) {

**Comment by 8191** [comment]
Actually I'm wondering why @AdSchellevis put the `str_replace("\r", "", ...)` to the [CaptivePortal/generate_certs.php](https://github.com/opnsense/core/blob/b83fed8cfcc655f07db931e3961e6a92b85318cc/src/opnsense/scripts/OPNsense/CaptivePortal/generate_certs.php#L59). I could not observe any `\r` in the output of `ca_chain()`.

**Comment by fichtner** [comment]
Don't think so, except maybe imported certificates?

**Comment by AdSchellevis** [comment]
Yes, imported certs from Windows hosts :-)

**Comment by 8191** [comment]
Hm... The imported certificate is directly written to the config? Maybe it's worth running it through the (Open/Libre)SSL engine to then store the sanitized output? 
Maybe we could also catch some other  potential encoding problems with that method, e.g. some other sanitations than removing `\r`...

**Comment by fichtner** [comment]
Generally true. However, that won't fix the certificates that have already been imported. I really don't like config.xml migrations. We've only ever done one in the entire history of OPNsense, and this would mean we'd have to do another one. ;)

**Comment by AdSchellevis** [comment]
And we don't have a decent migration method in place yet (other then the legacy script).... Minimizing config migrations is a really good idea at this moment :-)

**Comment by fichtner** [comment]
@8191 @AdSchellevis please review (and/or test) https://github.com/opnsense/core/commit/69a81ab13689191d48f7117a1ba810035edc8729
