### ISSUE TITLE
TOTP + High-Availability (HA) -> How that works together?

### ISSUE THREAD

**Issue by Ramalama2** [opnsense/core#6640]
**Important notices**

Our forum is located at https://forum.opnsense.org , please consider joining discussions there in stead of using GitHub for these matters.
--> Did that, but no one Answers/Reply to the Forums, seems a bit dead to me, sry.

Before you ask a new question, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue
--> I even checked forum and everything, and didn't found anything.

----------------------------

- Okay, i need TOTP, because in some cases i need to Access the Firewall from Outside. Means i opened the webgui Port in WAN.
- The Problem is, that wireguard is sometimes a bit unreliable, sometimes i need to restart the wireguard service after i booted opnsense, seems like a bug to me. However after i simply restarted the wireguard Service after the bootup of opnsense, wireguard runs stable and perfect.
- This leads to an issue here, because it can happen that we got a powerloss, everything boots up automatically afterwards and works, except that wireguard needs an Service restart xD
- Sometimes, rarely but happens i don't have the WG Access simply, while i need to access the FW, sometimes WG doesn't work simply.
- However, that are the reasons, "Why i need TOTP"

----

- Now i thought to Setup HA, because it's amazing and gives me the possibility to Maintaince my Main-Server without loosing the internet connection.
- But how to do that with TOTP?

---

- The problem is, when i create an User without TOTP, it will be easy to get Access to the GUI from WAN.
- I thought of an option to "Allow Bypass TOTP from IP:"

---

How do you guys do that?
The only idea that comes into my mind, is creating an user with Admin Priviliges and an very insanely hard password without TOTP like: "GJT#$xxM$oenmp!L7$YyX!G3LR7LXhLW5BdNYXcec3"

Cheers

**Comment by Ramalama2** [comment]
Oh man, i just found out, that i have to die one death.
If i activate Local TOTP and Local Database, then i can login without TOTP from outside, even while the root user has an OTP Seed.
I though at least there would be some cleverness, like if the user has an OTP seed, allow only totp auth... or sth like that.

However, seems like there is simply no solution for this, either we use TOTP or HA, but both is not Possible atm.
Would be grat if that would at least be mentioned somewhere, like:
https://docs.opnsense.org/manual/two_factor.html
https://docs.opnsense.org/manual/hacarp.html
as a small yellow box, that both at the same time is not supported atm.

Cheers

**Comment by Ramalama2** [comment]
So i deactivated here TOTP and use now an 60+ long password with all possible special characters, which makes me feel a bit more secure.

So thats the solution for now.
Thanks everyone, i leave the Topic open, because this is somewhat a Needed Feature at least. Feel free to discuss, maybe someone does a Pull Request at the end.

Thanks all!

**Comment by fichtner** [comment]
You can disable "integrated authentication" option under system: settings: administration and it lets you use the plain passwords on the console and SSH, or you unlock the console menu if you have secured physical access to it.

As for wireguard needing a kick it depends on the connectivity you are trying to achieve.. more complex setups can have these issues but it's easily fixed by dropping a script into rc.syshook "start" facility at the end of the boot sequence, see https://docs.opnsense.org/development/backend/autorun.html


Cheers,
Fraco

**Comment by fichtner** [comment]
PS: You can also sidestep with SSH by using a key instead of passwords.

**Comment by Ramalama2** [comment]
> PS: You can also sidestep with SSH by using a key instead of passwords.

Hey @fichtner thanks for taking your time!

~ i have passwordless console
~ ssh is diabled

But im wondering why you mention it, because im talking about the synchronisation from master to backup (ha)

As far i understood it has nothing todo with ssh/keys/etc, it does the sync via web api (i think)
Because the description says "web gui password/username"

Thanks again!
Cheers

**Comment by Ramalama2** [comment]
> I don't think you understand:
> 
> > The problem is, when i create an User without TOTP, it will be easy to get Access to the GUI from WAN.
> > I thought of an option to "Allow Bypass TOTP from IP:"
> 
> If you create a user without TOTP, you can't login when you set the system auth as TOTP. That's always going to be true for the web GUI. I've given you examples on how to access the box without TOTP in order to do recovery in case the TOTP is not working. Because if you use TOTP in the web GUI it should work for everyone, even admins unless it's broken (NTP not working, lost mobile phone with authenticator app/token).

Fichtner, that's off topic and it's not handy.
If you're away from home, you can't access the console, the only thing you can access is anything that you open or portforward.
I won't portforward the Proxmox gui for sure (console access)

Opening ssh doesn't help either, multiple reasons:
1. Managing firewall rules via the Cli is a pain in the butt. But restarting wireguard is at least easy via GUI, just not helpful if i need to change rules and don't have wg with me.
2. Ssh keys, as nice as they are, you can't save them in any password manager, just as note or something.

So i don't see the benefit of all that, it's the same as if I don't use TOTP, but set the password as a 60+ long string with special characters.
It's as same secure as an ssh key, but i can save it in the password manager and use it for accessing the opnsense GUI instead of ssh. Which is nicer.

But again I can't use TOTP, because of xmlrpc, and that's the main point of this topic.

Thanks Fichtner!

**Comment by fichtner** [comment]
It's not really off-topic if you try to cover such a broad scope in your "question". HA/XMLRPC has nothing to do with TOTP use. SSH allows for its own `port forwarding` so you can actually access the GUI from a remote location and don't have to deal with CLI. It's really not that difficult to get the system administration into a state that you want, but you need to be aware of all the tools available to you first.


Cheers,
Franco
