### ISSUE TITLE
add htop to pkg repository

### ISSUE THREAD

**Issue by aleczdr** [opnsense/core#6649]
**Is your feature request related to a problem? Please describe.**

There is no human-readable way to see real-time performance metrics from the command line.

**Describe the solution you like**
It would be nice if the htop utility (https://github.com/htop-dev/htop) was available in the package repository.

**Describe alternatives you considered**

The top utility is currently available, as well as the ability to git clone htop and compile it from source, but it would be nice to have the option of installing htop directly from the package repository.

**Additional context**

None

**Comment by cookiemonsteruk** [comment]
@aleczdr  as a suggestion, you can install htop from the mimugmail repository. It's as simple as adding the repository and then "pkg add htop".

**Comment by BeehiveSystems** [comment]
If anyone stumbles upon this, here's the repo that contains htop.

https://github.com/mimugmail/opn-repo

Repo install commands:

```
fetch -o /usr/local/etc/pkg/repos/mimugmail.conf https://www.routerperformance.net/mimugmail.conf
pkg update
```
