### ISSUE TITLE
Unbound DNS aliases do not appear in list in web GUI

### ISSUE THREAD

**Issue by danwilliams** [opnsense/core#6652]
- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

Using a fresh installation of OPNsense, I have added a range of hostnames to the list in Unbound DNS. These work fine.

I have then attempted to add aliases for some of these. **The aliases do not show up in the aliases list.**

I tried a few times, with a couple of different aliases, and then realised (by checking the configuration history) that they *are* getting added to the system, but are just not appearing in the list. This means I now have duplicated entries for some of the aliases I tried, but no way to view or delete them through the web GUI.

**To Reproduce**

1. Go to Services -> Unbound DNS -> Overrides
2. Add a "host override"
3. Add an alias for the host just added
4. Observe that the alias does not appear in the list
5. Go to System -> Configuration -> History and confirm that the alias was indeed added

**Expected behavior**

The alias should show in the "Aliases" list.

**Describe alternatives you considered**

There are no real alternatives, other than using the CLI interface via SSH, or exporting/editing/importing the config.

**Screenshots**

There are no screenshots relevant here, as the Aliases list is empty.

**Relevant log files**

I am not aware of any log files that would help here.

**Additional context**

This is a brand-new setup, created yesterday. I have entered host overrides for the first time, and aliases for the first time.

**Environment**

Host system:
- Ubuntu Server 23.04

VM configured for OPNsense:
- OPNsense 23.1 OpenSSL AMD64s (using the ISO)

**Comment by AdSchellevis** [comment]
best update to latest version first (23.1.11) before opening an issue which might already be fixed.

**Comment by danwilliams** [comment]
...ignore my initial confusion over version numbers; I've figured out that you use year.month for the major versions, and release every six months. So 23.7 will naturally be July.

**Comment by AdSchellevis** [comment]
https://docs.opnsense.org/manual/unbound.html#overrides 

>You have to select the host in the top list and it will the show you the assigned aliases in the bottom list.

**Comment by danwilliams** [comment]
That is truly bizarre UI. Thank you, as even though I had read that page in detail multiple times, I did not realise that you have to *click on the individual host row in question* to change the list below!

Elsewhere, it is possible to use the checkboxes on the left to select multiple entries. That does not appear to be possible for the hosts, even though it is for the aliases. In that case they should really be radio buttons, or, maybe changed to allow multi-select. Selecting all (as is possible in other tables) would then presumably show all aliases in the bottom table. At present that appears to be impossible, and so if I have a lot of hosts it will be time-consuming to manually click through each one to see which has aliases.

I'm not sure if it's just me that did not understand that UI implementation, but it might be worth considering changing it? If you would like some input into that then I can submit a PR when I have some time?

**Comment by danwilliams** [comment]
...just musing further on this: it's also lacking confirmatory feedback to the user about the action they just tried, because when you add aliases you don't see any result. Even if you don't want to change the behaviour of the hosts list, perhaps you should amend the aliases behaviour so that the host in question is automatically selected when adding? Although that may be tricky if it's not in the listed results in view at that point. Or, maybe restrict the addition process so that aliases can only be added for the host clicked on? I note that the host you click on is automatically selected, but as you can change it, the context can be missed.

**Comment by AdSchellevis** [comment]
> I'm not sure if it's just me that did not understand that UI implementation, but it might be worth considering changing it? If you would like some input into that then I can submit a PR when I have some time?

We're open for suggestions as long as it doesn't complicate the code too much, these are master/detail forms, a flatter structure might have been easier to understand (single grid). Allowing a multiselect and show all when none are selected shouldn't be too hard to add, if that's what you're looking for, just open a PR for discussion.

**Comment by stoklund** [comment]
I came here to file the exact same bug report. Thanks @danwilliams for doing the hard work. I've just added a couple of DNS aliases, and each time I add one it goes puff! and it's gone. I would not have figured out that the host and alias tables are linked without reading this bug.

Here's some suggesting for helping users like me figuring out what's going on.

If you stick with the single host selection:
- Replace the check boxes in the host table with radio buttons. They already behave like radio buttons.
- Replace the table title *"Aliases"* with *"Aliases for a.example.com"* and have it change dynamically when hosts are selected. This helps us learn that the tables are linked.
- Replace the empty table placeholder text *"No results found for selected host or none selected"* with *"No aliases for a.example.com"*.
- When no host is selected, display aliases for all hosts.

If you go with the multiple selection:
- Default to no hosts selected, and display all aliases in that case.
- Allow new aliases to be added when no hosts are selected.
- When a single host is selected, use the same text strings as above.
- When multiple hosts are selected, show something like *"Aliases for 3 selected hosts"*.

**Comment by perlun** [comment]
There's also another bug in this UI I discovered recently: if you open up an entry, you can indeed see its aliases. Now, if you search for a non-existent host in the top-right Search box, the upper list is cleared... but **the bottom list is not refreshed**. I.e. the "details" are not refreshed when the "master" list is updated. :thinking: 

@AdSchellevis - would you like me to create a separate issue for this or is it enough to keep it tracked in this issue?

**Comment by AdSchellevis** [comment]
@perlun maybe better to open a new ticket for that, it's probably a small cosmetic issue.

**Comment by perlun** [comment]
> @perlun maybe better to open a new ticket for that, it's probably a small cosmetic issue.

Alright, here we go: https://github.com/opnsense/core/issues/6920

**Comment by rudiservo** [comment]
Bug still exists in 23.7.7_3.

**Comment by rudiservo** [comment]
The issue seems to be in opnsense/mvc/app/controllers/OPNsense/Unbound/Api/SettingsController.php line 224.
So everytime you click on a host on unbound, now is selected by default, it does a query to this API to fetch aliases related to that override entry.

Issue is this part of the code.

```
public function searchHostAliasAction()
    {
        $host = $this->request->get('host');
        $filter_func = null;
        if (!empty($host)) {
            $filter_func = function ($record) use ($host) {
                return $record->host == $host;
            };
        }
        return $this->searchBase(
            'aliases.alias',
            ['enabled', 'host', 'hostname', 'domain', 'description'],
            "hostname",
            $filter_func,
            SORT_NATURAL | SORT_FLAG_CASE
        );
    }
```

So the host that the API receives is the host UUID, i.e.
`{"current":1,"rowCount":100,"sort":{},"searchPhrase":"","host":"5e88d281-f1d1-40dc-aa53-a0a9b81ba583"}`

The comparison is $record->host (something.example.com) with UUID (5e88d281-f1d1-40dc-aa53-a0a9b81ba583)

I did try to change the function to
`$result->uuid == $host`
but it did not work.

**Comment by AdSchellevis** [comment]
The host field does contain a uuid... 

https://github.com/opnsense/core/blob/89f880751536695217569a1965b24e60ce9a18da/src/opnsense/mvc/app/models/OPNsense/Unbound/Unbound.xml#L347-L357

you can always check the raw contents of the `config.xml` for validation by the way

**Comment by rudiservo** [comment]
@AdSchellevis somewhere something has it, because that is what is being sent by the javascript.
That UUID, that was the request sent by the GUI, not the response!
