### ISSUE TITLE
API issue with getFirmwareConfig (400: not found)

### ISSUE THREAD

**Issue by clementmoulin** [opnsense/core#6655]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

Since last versions (I would say 23.1.x cannot tell exactly which one), the route API `core/firmware/getfirmwareconfig` is not working anymore.

**To Reproduce**

```
curl -k -u '...':'...' http://localhost/api/core/firmware/getfirmwareconfig -v
[...]
> GET /api/core/firmware/getfirmwareconfig HTTP/1.1
> Host: localhost
[...]
< HTTP/1.1 400 Bad Request
[...]
< Server: OPNsense
<
* Connection #0 to host localhost left intact
{"message":"action getfirmwareconfig not found","status":400}
```

**Expected behavior**

Answer from API :)

**Describe alternatives you considered**

N/A

**Screenshots**

N/A

**Relevant log files**

N/A

**Additional context**

N/A

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 23.1.5 to 23.1.11 (amd64, OpenSSL).

**Comment by clementmoulin** [comment]
OK. I have made some investigations through GUI, and it seems that routes have been updated and now are named `api/firmware/set`, `api/firmware/get` and `api/firmware/get_options`.

Documentation should be updated : https://docs.opnsense.org/development/api/core/firmware.html

**Comment by AdSchellevis** [comment]
uniformed in https://github.com/opnsense/core/commit/4c65524322ce246cf3c0e182e6068f033323bd35, I'll make sure to update the api docs before the 23.7 release

**Comment by AdSchellevis** [comment]
I think we can close this with https://github.com/opnsense/docs/commit/8f5ea3663c670356e5ed61613357e74178593e91

**Comment by clementmoulin** [comment]
I don't see any update about core/firmware/rules in that commit.

**Comment by AdSchellevis** [comment]
it looks like this one is excluded from our automated procedures, let me check if we can fix this for future changes as well.

**Comment by AdSchellevis** [comment]
we do have to do this manually it seems, https://github.com/opnsense/docs/commit/e747ad1300164af927c5be3bc7933dd4956f2e23 should be it then.
