### ISSUE TITLE
SNMPv3 "password" and "enkey" are stored in plain text and should be hashed?

### ISSUE THREAD

**Issue by mgoerke76** [opnsense/core#6656]
<img width="1216" alt="SNMPv3clear" src="https://github.com/opnsense/core/assets/52465058/bd7d7ef0-6631-4861-8822-24d4bb706364">
*Question about SNMPv3 and password hashing*

The passwords and encryption keys are stored in plain text.
Is it a valid feature request to hash these values?

**Comment by fichtner** [comment]
Which plugin is this? If the service (assuming net-Ann’s) doesn’t use hashing we can’t store as hashes.

**Comment by mgoerke76** [comment]
Hello Franco, thanks, i think i got the point. 
Perhaps i check net-snmp docu.
Morris
