### ISSUE TITLE
Gateway monitoring IP not correctly setting gateway as online on boot

### ISSUE THREAD

**Issue by MaxXor** [opnsense/core#6660]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

I just upgraded two OPNsense instances from 22.7.11 to 23.1.11. Both have a gateway monitoring IP adress configured. On one OPNsense box I noticed that after the upgrade to 23.1.11 the internet connection was not working anymore. I checked the dashboard but the gateway was shown as online. Weird, so I went into the gateway settings and tried disabling gateway monitoring, which immediately worked.
![opnsense_gateway_dashboard](https://github.com/opnsense/core/assets/7271470/80695413-05d6-4e01-ac21-32d2c7fcc926)

I researched some more and found out that I could check if the routing table includes the monitoring IP after reboots, its indeed included:

![opnsense_default_route](https://github.com/opnsense/core/assets/7271470/98aacf00-ada9-45fa-a581-dca7f8a648be)

But if you look closely the default route is missing. Just to confirm at ALL times the gateway is shown with 0% packet loss and status "Online". I noticed that I can "fix" the WAN connection either by un/re-plugging the WAN cable or by simply editing the gateway configuration and clicking "Save" (without edits). Afterwards the default route is included which is seen below (20 entries vs 19 entries in the previous screenshot):

![opnsense_default_route2](https://github.com/opnsense/core/assets/7271470/18e7f5d4-d4fe-4f62-9282-26d084a61373)

Another fun thing I noticed is that when OPNsense is booted I can ping `8.8.8.8` because it's included in the routing table due to the monitoring IP, but no other IPs.

My other OPNsense box is working absolutely fine with gateway monitoring, I have no idea whats wrong. I've tried to include all necessary log files and also the log files of my 2nd working box. There are no special plugins installed, only `iperf3` and `acme` Maybe some kind of race condition which only happens at startup?

**To Reproduce**

1. Enable a gateway monitoring IP (either 8.8.8.8 or any other)
2. Reboot
3. No internet connection

**Expected behavior**

1. Enable a gateway monitoring IP (either 8.8.8.8 or any other)
2. Reboot
3. Internet connection :slightly_smiling_face: 

**Describe alternatives you considered**

I can "fix" the WAN connection either by un/re-plugging the WAN cable or by simply editing the gateway configuration and clicking "Save" (without edits).

**Screenshots**

***Gateway configuration***
![opnsense_gateway](https://github.com/opnsense/core/assets/7271470/ef1f55ad-d564-41b0-8315-70f1c562b1e9)

***Gateway log***
![opnsense_gateway_log](https://github.com/opnsense/core/assets/7271470/98d20c87-3255-4da6-9916-d70f4c6a4cf1)

**Relevant log files**

OPNsense 23.1.11 broken setup with gateway monitoring: [system_not_working.log](https://github.com/opnsense/core/files/12005082/system_not_working.log)
OPNsense 23.1.11 working setup with gateway monitoring: [system_working.log](https://github.com/opnsense/core/files/12005085/system_working.log)

**Environment**

```
OPNsense 23.1.11 (amd64, OpenSSL)
Intel(R) Atom(TM) CPU C2758
Intel(R) I354
```

**Comment by MaxXor** [comment]
Latest update 27.3.5 fixes this bug. Thank you @fichtner

**Comment by fichtner** [comment]
😊
