### ISSUE TITLE
Captiveportal crash on firewall reboot [OPNsense 23.1.11]

### ISSUE THREAD

**Issue by Algie37** [opnsense/core#6661]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [ x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [ x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

Captive portal does not accept logons after firewall has rebooted.

*Tip*: to validate your setup was working with the previous version, use opnsense-revert (https://docs.opnsense.org/manual/opnsense_tools.html#opnsense-revert)

**To Reproduce**

1. Reboot firewall.
2. Attempt Captiveportal logon.

**Expected behavior**

Correct credentials will be accepted and the user will logon.

I have been executing the below commands manually to resolve this issue.

1. Stop captiveportal service.
2. cd /var/captiveportal/
3. mv captiveportal.sqlite captiveportal.sqlite.bak
4. Start captiveportal service

**Screenshots**

**Relevant log files**

The below log lines populates every 1 minute prior to above mitigation

1. 

2023-07-11T05:11:13 | Error | captiveportal | Forcefully repair database (Traceback (most recent call last): File "/usr/local/opnsense/scripts/OPNsense/CaptivePortal/cp-background-process.py", line 208, in main bgprocess.db.cleanup_sessions() File "/usr/local/opnsense/scripts/OPNsense/CaptivePortal/lib/db.py", line 375, in cleanup_sessions cur.execute(""" delete sqlite3.OperationalError: no such table: cp_clients )
-- | -- | -- | --

2.
2023-07-11T05:11:13 | Error | captiveportal | sqlite3 repair /var/captiveportal/captiveportal.sqlite
-- | -- | -- | --

3.  
2023-07-11T05:11:13 | Error | captiveportal | sqlite3 repair /var/captiveportal/captiveportal.sqlite [done]
-- | -- | -- | --

**Additional context**

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 23.1.11-amd64
FreeBSD 13.1-RELEASE-p8
OpenSSL 1.1.1u 30 May 2023
Intel Core i7 6700 CPU @ 3.4GHz (4 cores, 8 threads)

**Comment by AdSchellevis** [comment]
might be this https://github.com/opnsense/core/commit/8fbf2dd7f9d83a29cfe9029d24e290e2be2e38d5 

to try locally (and restart captive portal): 
```
opnsense-patch 8fbf2dd
```

**Comment by Algie37** [comment]
Hello @AdSchellevis . Unfortunately, captive portal restart does not solve the issue even after several retries. 
Firewall restart also does not solve the issue.
You have to manually clear the SQLite file as described above for everything to work again.
