### ISSUE TITLE
Sanity check: NAT "Add associated filter rule" - multiple entries in dropdown field

### ISSUE THREAD

**Issue by levelad** [opnsense/core#6664]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

When I messed around with NAT rules I found out that there are multiple entries in the dropdown field for "Filter rule association".

To replicate just create the same NAT rule with identical name 4 times with "Add associated filter rule".

The first NAT rule will have all 4 rules, the 2nd 3 rules, the 3rd 2 rules and the 4th one rule (IIRC).

It's not wrong as every NAT rule is associated to the right rule but either it shows only one FW rule in the corresponding NAT rule or all FW rules in the corresponding NAT rule.

I guess the source is already aware of the problem because it says:

`<!-- maybe we should remove this in the future, multi purpose id field might not be the best thing in the world -->`

OPNsense 23.4.1

**Comment by vpx23** [comment]
Writing from my work account. Original post I wrote from home off the top of my head so it might not be 100% accurate.

If the replication above does not work try the following, I wrote down exactly how I created the NAT rules:

Rule 1 created with:

NAT reflection: Use system default
Filter rule association: Add associated filter rule
Firewall->Settings->Advanced->Network Address Translation: Reflection for port forwards: off | Reflection for 1:1: off | Automatic outbound NAT for Reflection: off

Changed to Pass -> The rule on the WAN disappeared, dropdown menu in Port Forward no more shows "Rule", only "Pass" and "None".

Rule 2 created with:

NAT reflection: Enable
Filter rule association: Add associated filter rule
Firewall->Settings->Advanced->Network Address Translation: All off

No NAT relection rule is visible anywhere. If you now edit Port Forward rule 1 then there is again the "Rule", so the rule in the WAN interface is now linked with both Port Forward rules.

Rule 3 created with:

NAT reflection: Enable
Filter rule association: Add associated filter rule
Firewall->Settings->Advanced->Network Address Translation: Reflection for port forwards: off | Reflection for 1:1: off | Automatic outbound NAT for Reflection: on

No NAT outbound rule is visible anywhere.

Rule 4 created with:

NAT reflection: Use system default
Filter rule association: Add associated filter rule
Firewall->Settings->Advanced->Network Address Translation: Reflection for port forwards: on | Reflection for 1:1: off | Automatic outbound NAT for Reflection: on

No NAT relection rule is visible anywhere. Only the WAN rule. Drodown menu in "Filter rule association" now shows 3x "Rule".
![Assoc_filter_rule](https://github.com/opnsense/core/assets/134484700/c902b4bd-44f4-4306-a81d-5213a8bdddb3)
![automatic_rules](https://github.com/opnsense/core/assets/134484700/d2b97763-6be8-4257-a88e-0b490b294dcd)
![PF_2](https://github.com/opnsense/core/assets/134484700/a2bacbaf-8af3-456c-8a8d-a93dcdecb4d0)
![PF_3](https://github.com/opnsense/core/assets/134484700/bca4fa15-8c2a-443e-b418-bf26a9814325)
![PF4](https://github.com/opnsense/core/assets/134484700/49c4a2cb-cd72-4d99-8557-c085b0be5e92)
![Rule1](https://github.com/opnsense/core/assets/134484700/2d9ac334-be67-4e90-8b43-528988d90aca)
![Rule1_2_settings](https://github.com/opnsense/core/assets/134484700/489079ed-9f59-4111-ae66-8abb275ed2f2)
![Rule2](https://github.com/opnsense/core/assets/134484700/d63deac3-0727-4e64-9a2d-c6b7b1cd1528)
![Rule3](https://github.com/opnsense/core/assets/134484700/40892028-2ded-4931-bd64-e935f682bffb)
![Rule3_settings](https://github.com/opnsense/core/assets/134484700/8412a760-442e-4e4a-9fa7-59d089d8379b)
![Rule4](https://github.com/opnsense/core/assets/134484700/9480bf43-937e-49a6-a65b-1de8cfc02941)
![Rule4_settings](https://github.com/opnsense/core/assets/134484700/b1aefa47-9ecb-416a-a8fd-707fb00ab8bc)

**Comment by AdSchellevis** [comment]
It always shows all "linked" rules, not the brightest concept in the world, but if we would have designed it we might not offered to add a rule at all to be honest (there are more downsides to this).

https://github.com/opnsense/core/blob/0c76a9134d5aa9226aeeebd05ad5d81ba40716fc/src/www/firewall_nat_edit.php#L1067

In this case it might be better to just show the linked rule (1) or offer to add one if none is linked yet. I'll take a look

**Comment by AdSchellevis** [comment]
https://github.com/opnsense/core/commit/e5c2ac59097152fa1d981b0c82744236ebd9afb0 should clean things up a bit and only show the linked rule when it exists.
