### ISSUE TITLE
Unbound and DNS records for DHCP leases with underscores

### ISSUE THREAD

**Issue by cookiemonsteruk** [opnsense/core#6666]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**
DHCP clients that use hostnames with underscores now unbound logs the error "dhcpd leases: XXX_XXX not a valid hostname, ignoring" I believe since version 23.1 with the new regex validation.
src/opnsense/scripts/dhcp/dnsmasq_watcher.py
and 
src/opnsense/scripts/dhcp/unbound_watcher.py
hostname_pattern = re.compile("(?!-)[A-Z0-9-]*(?<!-)$", re.IGNORECASE)

https://forum.opnsense.org/index.php?action=post;topic=34842.0;last_msg=168755

I am led to believe  it as not a bug, if previous behaviour was against RFCs, therefore if you forgive logging this question as a bug, the question is: Can have the non-compliant behaviour back?.
If the answer is no, we'll need to rename hosts but I wonder if it is worth considering if the old behaviour is innocuous enough to allow again.

Version:
OPNsense 23.1.11-amd64
FreeBSD 13.1-RELEASE-p8
OpenSSL 1.1.1u  30 May 2023

**Comment by AdSchellevis** [comment]
let's reference the open PR here as well https://github.com/opnsense/core/pull/6665, it might not be an issue to bring it back, we should check for both unbound and dnsmasq if this would lead to issues in my opinion.

**Comment by cookiemonsteruk** [comment]
ok that is indeed better. I failed to see that PR at the time I opened this. Happy to have this closed if preferred @AdSchellevis

**Comment by AdSchellevis** [comment]
fixed in https://github.com/opnsense/core/pull/6665
