### ISSUE TITLE
Stuck ISP DNS Servers in WAN DHCP

### ISSUE THREAD

**Issue by spark1313** [opnsense/core#6668]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

I am on version 23.1.11 and did not check or notice it prior. I am using Unbound DNS and have DNS over TLS configured.
At one point during troubleshooting, I ticked the box for "Allow DNS server list to be overridden by DHCP/PPP on WAN" in System > Settings > General. This pulled in ISP provided DNS servers in addition to my intended DNS servers.

Later I unticked that box, intending to go back to my two intentional DNS servers, but when I viewed the status of the WAN interface in Interfaces > Overview, the two ISP provided DNS remain. However, when I check the contents of /etc/resolv.conf, the ISP provided DNS are not listed in there. I checked to confirm and the ISP network gets added to /etc/resolv.conf when I go back and tick the referenced box again.
However, when I tick the box AND exclude the WAN interface, the ISP provided DNS servers no longer show up under the list of DNS servers for the WAN interface in the Overview page mentioned. When I checked /etc/resolv.conf the ISP network was still in there although it no longer showed up in the Overview page.
This seems to be a bug. My goal is to remove all traces of the ISP provided DNS servers and since not existing in /etc/resolv.conf either, I would not expect them to show up under the interface. I did not find a way to manually remove DNS Servers for the WAN DHCP within the UI. I ran a grep on the entire OS for the ISP provided IPs in case they were in a config file elsewhere but it ran for an hour and didn't find anything so I canceled it.

**To Reproduce**

1. Tick the box for "Allow DNS server list to be overridden by DHCP/PPP on WAN" in System > Settings > General
2. Reload
3. Untick the box
4. Reload
5. View WAN interface DNS server list in Interfaces > Overview

**Expected behavior**
ISP provided DNS servers go away in the Interfaces > Overview page WAN interface after the "Allow DNS server list to be overridden by DHCP/PPP on WAN" is ticked. Also expecting the DNS servers to show up on that Interfaces > Overview page when the box is ticket but WAN excluded since they are still present in /etc/resolv.conf but do not show up on that page.

**Additional context**

Note that my setup is fairly vanilla. I'm fairly new to OPNSense coming from pfSense land. I have it set so the OPNSense router does all DNS resolution locally and any clients go through it for DNS. I have firewall rules configured to make that happen.
I have one LAN and one WAN interface set up with the router connected to an ONT box with WAN DHCP. I'm using intel NICs.

**Comment by fichtner** [comment]
DHCP provided DNS servers are always recorded (overview page) regardless of your choice but the system will stop using them if not preferred. DNS host routes may stick due to flaky implementation and design constraints (routes cannot be annotated so we don’t know who owns them) and host routes overlaps can always happen for other reasons as well.

A best practice is rebooting and sticking to the appropriate ISP server setting.

If you plan to work on improving the current situation please be my guest. Otherwise let’s close as support issue.

**Comment by spark1313** [comment]
Understood, thanks for the insight @fichtner.

However, I am implementing DNS over TLS (DoT) from Cloudflare DNS and others and intentionally do not want to use the ISP provided WAN DHCP provided DNS servers so rebooting and sticking to the appropriate ISP server setting would not be a resolution.

I manually removed the DNS host routes in the route list status page, and they did not repopulate after reboot, which is great. But the associated WAN DHCP provided DNS servers are still listed on the Overview page.
Do you know what config file sources the DNS server entries listed on the Overview page? I did not see them in /conf/config.xml or /etc/resolv.conf and was looking for their location so that I could scrub them out and see if they auto-repopulate stuck when the interface refreshes/after reboot or if they remain unstuck.

Also would the DNS server entries disappearing in Overview page but still listed in /etc/resolv.conf when "Allow DNS server list to be overridden by DHCP/PPP on WAN" is ticked but WAN interface excluded not be counted as a bug?
It appears to me that the expected behavior is reversed. I would think that when the box is ticked and WAN excluded, the behavior when the setting is unticked should be identical. Instead, /etc/resolv.conf becomes misconfigured when checked but WAN excluded but the Overview listing is correct and when the box unchecked, /etc/resolv.conf becomes correctly configured but the Overview listing becomes incorrect.

**Comment by fichtner** [comment]
> But the associated WAN DHCP provided DNS servers are still listed on the Overview page.

This is for diagnostics purposes nowadays, but they are not being used by the system. It just lists what DHCP offered to give more insights into what the ISP is doing.
