### ISSUE TITLE
Alternate Hostnames to bypass the DNS Rebinding Attack checks not working

### ISSUE THREAD

**Issue by vpx23** [opnsense/core#6673]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

I'm getting a lot of warnings in the dnsmasq log about the Microsoft NCSI DNS server:

`2023-07-19T09:58:33	Warning	dnsmasq	possible DNS-rebind attack detected: dns.msftncsi.com`

That's why I added an exception in: "System->Settings->Administration->Alternate Hostnames". I guess this should equal "rebind-domain-ok" in dnsmasq.

But even after setting the hostname I get the warning in the dnsmasq log. I the tried the domain with and without the subdomain.

I also set a sinkhole in "Services->Dnsmasq DNS->Host Overrides", that could be the cause. When I modify the host override to have an invalid host the warning still appears, so this doesn't seem to be the cause.

OPNsense 23.4.1
![NCSI_sinkhole](https://github.com/opnsense/core/assets/134484700/d1c52eab-9b84-4828-8768-804fc0a1d722)
![Rebind_Domain_OK](https://github.com/opnsense/core/assets/134484700/c115c698-dd9d-44ae-8128-1b24981a34fe)
![Rebind_Domain_OK_no_subdomain](https://github.com/opnsense/core/assets/134484700/28b1cf79-a920-4207-afb2-fdd108dd2fdc)

**Comment by vpx23** [comment]
Isn't there a dot missing after the first slash?

See these examples:

https://serverfault.com/questions/939775/whitelist-all-sub-domains-with-rebind-domain-ok
https://superuser.com/questions/1722785/dnsmasq-domain-whitelisting-breaks-dns

I cannot manually add a leading dot to the hostname in the GUI, it will show the error: "Alternate hostname .dns.msftncsi.com is not a valid hostname."

**Comment by AdSchellevis** [comment]
by my knowledge the statement only belongs to the webgui check

https://github.com/opnsense/core/blob/4c6e3a1e081bd543af434231b2da5803b6359550/src/etc/inc/authgui.inc#L65

**Comment by vpx23** [comment]
@AdSchellevis In this case I would like to convert this into a feature request.

There should be a text field in the dnsmasq settings, maybe call it "Rebind domains" with the help description of the dnsmasq man page "Do not detect and block dns-rebind on queries to these domains.  Separate hostnames with spaces."

Then you would have to append these domains with some conversion of the spaces to slashes to the existing "--rebind-domain-ok=" parameter.

**Comment by fichtner** [comment]
I would rather recommend using the advanced settings for your use case: https://docs.opnsense.org/manual/dnsmasq.html#advanced-settings
