### ISSUE TITLE
Allow VoucherController.php API access from guest/captive network like AccessController.php

### ISSUE THREAD

**Issue by oscarsmx** [opnsense/core#6675]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**

_**For a purpose of creating the voucher within the same captive network (the one with the captive portal) would be awesome to create forms in a local environment (local network) in same vlan as the portal. Currently you can access with the API to AccessController.php to validate if the token is right but you can't create tokens (there is no access to VoucherController.php with the API in the same guest network).**_

A clear and concise description of what the problem is including your motivation for the request,

**_For the purpose of this feature we are missing the option to create forms to self serving tokens to the users (IE. click here to generate your voucher)_**

**_Allow access to VoucherController from the guest network like the AccessController.php_**

A clear and concise description of any alternative solutions or features you considered.

**_I did tried to edit this manually with the lighttpd config and the php but I did lack of knowledge for this and end up with a broken voucher system that didn't work afterwards (the access to the endpoint and payload was ok but vouchercontroller.php was broken and didn't generate anything). However I do think this it's easy if there is already something like this within the same files._**

**Comment by oscarsmx** [comment]
That's what I was thinking... (Intentional indeed)

Is there is a way to access the vouchercontroller.php from the captive portal to the API endpoint?

I did managed to edit the lighttpd config file

https://github.com/opnsense/core/blob/fc7e1ddddf9c487304c8962cd4eddda9a22c5f15/src/opnsense/service/templates/OPNsense/Captiveportal/lighttpd-zone.conf#L107-L111

and get access from the captive portal to the whole API removing /access but the vouchercrontller.php doesnt have access-control I did managed to copy the funcion from AccessContoller

`    public function beforeExecuteRoute($dispatcher)
    {
        // disable standard authentication in CaptivePortal Access API calls.
        // set CORS headers
        $this->response->setHeader("Access-Control-Allow-Origin", "*");
        $this->response->setHeader("Access-Control-Allow-Methods", "OPTIONS, GET, POST");
    }`

but this broke the vouchersystem

> that's intentional, the web portal should have a low attack surface, you can expose the regular web gui to any network, feeding other endpoints via the portal webserver isn't supported (for good reasons).
> 
> https://github.com/opnsense/core/blob/fc7e1ddddf9c487304c8962cd4eddda9a22c5f15/src/opnsense/service/templates/OPNsense/Captiveportal/lighttpd-zone.conf#L107-L111
> 
> https://github.com/opnsense/core/blob/fc7e1ddddf9c487304c8962cd4eddda9a22c5f15/src/opnsense/service/templates/OPNsense/Captiveportal/lighttpd-api-dispatcher.conf#L39-L41

**Comment by AdSchellevis** [comment]
I'm afraid this goes a little beyond community support scope. The api calls should probably "just work" when not being executed from a browser (and using api keys), the CORS headers are only there to protect the browser (https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS)

**Comment by oscarsmx** [comment]
Oh that's a little sad.

As the web portal (Captive) it's only allowed to run html/css/js (browser) there is no way to gerate this from the portal because of the CORS (using JS we get the CORS issue)

My thinking was instead of print/generate from a CRM the voucher (on the network wihtout captive) just generating one withing the portal itself (self service) to the user that is connected to the guest network but like you said I can't consume the api using browser because of CORS either run another language over the template of the portal.
