### ISSUE TITLE
WAN address does not mean a singular address

### ISSUE THREAD

**Issue by gitterdoneplease** [opnsense/core#6676]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

When using Virtual IPs on a WAN interface the "WAN address" drop-down item does not mean the WAN address. It instead means all addresses on the WAN interface. 

**To Reproduce**

1. Set Virtual IP
2. Set Port Forward to Destination of "WAN address"
3. Apply changes
4. connect to WAN address with port set in Port Forward rule and it will work
5. connecting to any other Virtual IP will also work on that port

**Expected behavior**

The "WAN address" should only be the IP address of the WAN interface, not additional Virtual IPs. Or the terminology should change to "WAN Interface IPs."

**Describe alternatives you considered**

Using just the IP address as a the destination works, but that is not a drop-down menu by default. Maybe add the actual address as a default? Something to alert the user of the UI that "WAN address" has the potential to mean many addresses and is not, in fact, a singular "address."

**Screenshots**

N/A

**Relevant log files**

N/A

**Additional context**

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense OPNsense 23.1.11-amd64

**Comment by fichtner** [comment]
Well, how does the resulting rule look in /tmp/rules.debug ?

**Comment by gitterdoneplease** [comment]
Hello!

With a port forward set to "WAN address" I see:

`rdr on vtnet0 inet proto tcp from {any} to {(vtnet1)} port {4190} -> 192.168.1.20 port 4190 # mail Sieve`

If I specify the IP (68.70.22.206) I see:

`rdr on vtnet0 inet proto tcp from {any} to {68.70.22.206} port {4190} -> 192.168.1.20 port 4190 # mail Sieve`

**Comment by fichtner** [comment]
Ok, `(vtnet1)` is a kernel-side expansion. It should really mean "WAN address**es**" here but we've never changed the label due to side effects between different (NAT) rule types.

**Comment by gitterdoneplease** [comment]
Hrmmm. Be nice to have the label reflect reality. I noticed when I put "WAN network" I get:

`rdr on lo0 inet proto tcp from {any} to {(vtnet1:network)} port {4190} -> 192.168.1.20 port 4190 # mail Sieve`

Is there a further kernel-side expansion that could be leveraged for just the WAN address?

**Comment by fichtner** [comment]
There is `:0` but we can't change this without breaking rules for other people why rely on the current behaviour.

**Comment by AdSchellevis** [comment]
We might consider renaming address to addresses in https://github.com/opnsense/core/blob/67addc6577939aab2bfde3e75b4ea1fd0713c41d/src/www/guiconfig.inc#L313

Assuming these are replaced similar in all areas where this is used.

**Comment by fichtner** [comment]
The exception is probably outbound NAT.

**Comment by levelad** [comment]
Could you put a tooltip over these system aliases listing all IPs/networks as you do for user aliases?

That would be very helpful, I also noticed "OpenVPN net" not  working in firewall rules but maybe this is another issue. ^^

**Comment by AdSchellevis** [comment]
> Could you put a tooltip over these system aliases listing all IPs/networks as you do for user aliases?

Unfortunately not, as the gui doesn't know which addresses are there.


Could you put a tooltip over these system aliases listing all IPs/networks as you do for user aliases?

> That would be very helpful, I also noticed "OpenVPN net" not working in firewall rules but maybe this is another issue. ^^

It likely is working, but different then you expect, the net usually is the tunnel (point to point), these nets can be inspected in the diagnostics by the way.

**Comment by fichtner** [comment]
In point to point mode a network cannot be inferred by the packet filter since the kernel doesn’t have that information.

**Comment by levelad** [comment]
> It likely is working, but different then you expect, the net usually is the tunnel (point to point), these nets can be inspected in the diagnostics by the way.

I expected "OpenVPN net" to be the VPN address pool, good to know that it is not.
