### ISSUE TITLE
bug (23.7r1): Call to undefined function legacy_interfaces_details() 

### ISSUE THREAD

**Issue by g-a-c** [opnsense/core#6677]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

Since upgrading to 23.7-RC1 I have a reported crash once per minute which appears to be triggered by the default `gateway_alert` check in Monit:

```
[21-Jul-2023 08:40:28 Europe/London] Error: Call to undefined function legacy_interfaces_details() in /usr/local/etc/inc/plugins.inc.d/dpinger.inc:142
Stack trace:
#0 /usr/local/etc/inc/plugins.inc.d/dpinger.inc(353): dpinger_instances()
#1 /usr/local/etc/inc/plugins.inc(330): dpinger_status()
#2 /usr/local/etc/inc/legacy_bindings.inc(172): plugins_run('return_gateways...')
#3 /usr/local/opnsense/scripts/OPNsense/Monit/gateway_alert(52): return_gateways_status()
#4 {main}
```

To my PHP-naive mind it looks like `dpinger.inc` is missing a `require_once 'interfaces.lib.inc;` as this file is where the `legacy_interfaces_details()` function is actually defined. I did this on my appliance in an attempt to get rid of the errors and it did, but I'll leave it to the experts to decide whether that's the right solution or not.

*Tip*: to validate your setup was working with the previous version, use opnsense-revert (https://docs.opnsense.org/manual/opnsense_tools.html#opnsense-revert)

**To Reproduce**

1. Install OPNsense 23.7r1
2. Configure gateways with monitoring
3. Install the `os-monit` plugin

**Expected behavior**

Errors do not happen

**Describe alternatives you considered**

A clear and concise description of any alternative solutions or workaround you considered.

**Screenshots**

**Relevant log files**

If applicable, information from log files supporting your claim.

**Additional context**

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 23.7r1 (amd64, OpenSSL).
Atom C2558
Network Intel® I210

**Comment by fichtner** [comment]
@g-a-c thanks! to avoid gluing all includes together the include/require should be in the top script, see https://github.com/opnsense/core/commit/24f8eb66329b289cb09d6331904b43f62defb6f7

    # opnsense-patch 24f8eb6


Cheers,
Franco
