### ISSUE TITLE
Aliases not working as expected in Firewall rules

### ISSUE THREAD

**Issue by roblatour** [opnsense/core#6678]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

I have a program (which I wrote) that basically casts sound/video files to chromecast devices.

I also have aliases and firewall rules set up in OPNSense as follows:

[screenshot](https://ibb.co/tsMxV2w)

Thing is, if I enable the rule with the aliases and disable the rule right below it, the casting does not work. 

However, if I enable the rule below the one with the aliases the casting does work.

I am using the most up to date version of OPNSense:
OPNsense 23.1.11-amd64
FreeBSD 13.1-RELEASE-p8
OpenSSL 1.1.1u 30 May 2023

**To Reproduce**

Require a Google Nest Home, Mini or some such chromecast device

1. Setup OPNsense with two interfaces: LAN (192.168.1.xxx) and LAN_IOT (192.168.200.xxx)
2. LAN should have access to LAN_IOT, LAN_IOT should not have access to LAN
3. Setup your Google devices on LAN_IOT
4. Set up an aliase referencing the IP addresses of all your Google devices
5. For the LAN_IOT interface, set up a pair of rules as shown in the last two lines of [screenshot](https://ibb.co/tsMxV2w)
6. **Disable** the last rule as shown in the screenshot above
6. download and install cast from [https://rlatour.com/cast](https://rlatour.com/cast) 
7. from the Windows command prompt of a Windows machine running in the LAN interface, enter the command:
    **cast -inventory**
    you should see a list of all your google devices, their ip address should match what you have set up in your aliase
8. note the address of one of your google devices, lets say it is 192.168.200.132 (as in the screenshot above)
9. from the command prompt enter the command
    cast -ip 198.168.200.132 -text Hello world
10. the message will **not** play on your google home device
11. **Enable** the last rule as shown in the screenshot above
12. issue the same command as in step 9 above
13. the message **will** play on your google home device

Note, if you have a Google nest Hub (with a screen) you will see the file being sent to it, but it will not play with the the last rule as shown in the screenshot above disabled, but will play with the last rule as shown in the screenshot above enabled.

**Expected behavior**

The cast command should work with the 2nd from the bottom rule in the screen shot enabled only

**Screenshots**

shown above

**Relevant log files**

 

**Additional context**

 

**Environment**

 Cast runs on Windows 11

OPNsense 23.1.11-amd64
FreeBSD 13.1-RELEASE-p8
OpenSSL 1.1.1u 30 May 2023

**Comment by AdSchellevis** [comment]
non routable multicast traffic? at least it sounds like it. usually multicast is not intended to leave the subnet it's bound to, in which case you would need a repeater of some sort (has nothing todo with firewall rules or aliases in that case)

**Comment by roblatour** [comment]
Well, it **does work** as (I) intended without a repeater or anything else like that when I specifically include the IP address of the target google device in the IOT_LAN firewall rules (as show in the bottom line of the screenshot in the original post).   

However, it **doesn't work** when I include that same ip address, along with other IP addresses, in an Aliase.

So I'm thinking its a bug one way or the other.

Regardless, you have said '**usually ... not intended**', but I do intend it to work that way, and also with an Aliase.

So I would like to leave this issue open please.

**Comment by AdSchellevis** [comment]
if it's not multicast traffic being targeted, I would inspect the contents of the alias first in diagnostics. 
Nobody said anything about closing an issue, just pointing you in a direction, but if help isn't appreciated, no problem, we'll just wait for someone else to chime in. The chance an alias with the correct content (according to diagnostics) is not properly applied on a source or destination selector is likely close to zero.

**Comment by roblatour** [comment]
help is appreciated

**Comment by roblatour** [comment]
I've recorded a short (3 minute 12 second) video of the issue here to help illustrate it:
[video](https://6ec1f0a2f74d4d0c2019-591364a760543a57f40bab2c37672676.ssl.cf5.rackcdn.com/OPNSense%20issue.mp4)

**Comment by bsiege** [comment]
That is the point where packet dumps could reveal the "real issue"

**Comment by roblatour** [comment]
@bsiege

For my part, I am just posting what appears to be a bug with OPNSense, including taking the time to create a video showing it happening and also writing it up with hopefully clear enough instructions on how to recreate it.  

I'm really not familiar enough about OPNSense to interpret package dumps or delve into to the code to figure it out.  

Perhaps use of the alias is not the 'real' issue, all I know is I'm turning the key and the car isn't starting :-)

**Comment by barbacoder** [comment]
Your detailed description still leaves room for questions ;-)

- We have to assume both rules are identical, except for the source.
- We have to assume the alias being used is not disabled

Since the second rule is probably working as you expected, I would take the following steps:
 > enable logging on both rules
 > give both a distinctive description instead of the same
 > under firewall > logfiles > live view do a selection on address contains 192.168.200.132.
 
You would probably see the last of these two rules being hit. If some of the traffic is allowed by the first rule, we can assume the alias must be active and other options in the first rule may play a role in your mystery.
If that's the case: what traffic is being handled by the second rule?

That being said: you have created a rule on the IOT interface which opens the IOT lan (at least for the devices in the alias list) to the LAN which is not desired according to your nr 2.  I would dig further into the required traffic and see what could be done to eliminate a rule of this kind. But that all depends on the type of traffic.

**Comment by roblatour** [comment]
Regarding:

```
Your detailed description still leaves room for questions ;-)

We have to assume both rules are identical, except for the source.
We have to assume the alias being used is not disabled
```

Yes, both assumptions are correct.

As for the other points, time permitting I may get to that.  However, as I have a work around I doubt that will be any time soon, if at all.

**Comment by roblatour** [comment]
As an update, I am working on another project right now that touches on my firewall and as part of it I did some renumbering of my interfaces and ports.  As part of this I also came back and retested this issue.  Sadly, it still remains.  However, I did pick up another clue based on my revised numbering ...

Here are my revised aliases:
[url=https://ibb.co/JdK6T9y][img]https://i.ibb.co/3s76bnM/ss1.jpg[/img][/url]

Here are my revised rules for which I have turned logging on:
[url=https://ibb.co/ZVvS318][img]https://i.ibb.co/t4nzSPs/ss2.jpg[/img][/url]

Here are my logged results:
[url=https://ibb.co/x22V8mZ][img]https://i.ibb.co/kGGY63Z/ss3.jpg[/img][/url]

What is interesting is the rule that specifies the alias is NOT logged, which I assume means was NOT considered.  Rather the rule below it, with a specific IP address was logged.

Although this in no way resolves the issue with the use of the aliases, it may perhaps help in further pin pointing the issue.

**Comment by AdSchellevis** [comment]
Use proper alias type and, please, check the actual content using diagnostics before expecting any type of bug in this area…… these tools are there for a reason.

**Comment by roblatour** [comment]
You are right.  For the Alias type I had 'URLs (IPs)' - I had seen the IPs as part of the description and thought it was ok if I used the IPs of my Google devices.  What I should have used was 'Hosts'.  When I made that change it worked.  Thank you for your guidance.
