### ISSUE TITLE
Stacked VLANS (Q-in-Q) but not 802.1ad

### ISSUE THREAD

**Issue by wizdude** [opnsense/core#6679]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**

My ISP provides a service to me with VLANS stacked inside a VLAN. Specifically these are 802.1q inside 802.1q. Both packets are tagged with 0x8100.

Traditionally the standard for this would be to use Q-in-Q with an outer 802.1ad VLAN and 802.1q VLANS inside. I can see that changes were made in OPNsense to meet this "standard" behaviour and to become more compliant last year.

However, my carriage service provider will drop packets tagged with 0x88a8 (802.1ad), so my ISP uses 802.1q inside 802.1q to work around this issue.

Currently I have to manually edit two files (src/opnsense/scripts/interfaces/reconfigure_vlans.php and src/etc/inc/interfaces.inc) and change the logic which sets the parent to 802.1ad if it has children. I simply change the conditional to hard set $vlan['proto'] to '802.1q'. This obviously won't survive an OPNsense patch update.

**Describe the solution you like**

I would like a override for this, located perhaps in Interfaces > Settings >Network Interfaces, perhaps with a name like "Q-in-Q 802.1q Override" or "Stacked VLAN Override" with a tick box for "Force Q-in-Q Parent to use 802.1q". The full help could advise something such as "Checking this option will force all parent VLANs which contain child VLANS (Q-in-Q) to be tagged as 802.1q (0x8100) instead of the default 802.1ad (0x88A8)".

**Describe alternatives you considered**

I discussed this in the forums and someone suggested that this should be a per-VLAN setting rather than global, and that sounds ambitious but potentially over-engineered for this specific use case. I'd be happy with a global setting to start with, and if someone wants to further enhance this afterwards that would be fine.

**Additional context**

Original forum thread:
https://forum.opnsense.org/index.php?topic=34617.msg167760

I'm keen to get this implemented so I won't have to manually patch files each time an update comes out. At this point in time I also can't update anything remotely as I would lose connectivity and would not be able to fix remotely.

**Comment by AdSchellevis** [comment]
I'm not against making this configurable, but it should indeed be set per vlan to avoid future issues.

Dumping the relevant spots (also in the forum) here for reference:

https://github.com/opnsense/core/blob/c3db32722d48335f7a9f396d729df2d2847669b1/src/etc/inc/interfaces.inc#L164
https://github.com/opnsense/core/blob/24dbe30cadd83fa5a1fcea8ed6b38357794a4d6a/src/opnsense/scripts/interfaces/reconfigure_vlans.php#L77

**Comment by AdSchellevis** [comment]
@wizdude this https://github.com/opnsense/core/commit/6487a9b62e31c253392f5fe2985da11b8225f99e should do the trick, it adds an advanced option for manual proto selection in the dialog. 

To install, I expect the following should to the trick (revert with `opnsense-revert  opnsense`)

```
opnsense-patch 6487a9b
```

**Comment by wizdude** [comment]
this is awesome. thanks. i've tested it on my lab box and it works well. i'll put it into production as soon as I can organise a suitable maintenance window.

does this mean that this new feature will automatically be part of future updates?

**Comment by fichtner** [comment]
I think this will be in 23.7.
