### ISSUE TITLE
dhcp: csv file import for static leases

### ISSUE THREAD

**Issue by fichtner** [opnsense/core#668]

**Comment by 8191** [comment]
Maybe we can solve this within #471?

**Comment by fichtner** [comment]
I don't think so, it should be on DHCP page... we already have drag and drop support for input boxes cvs in the proxy server pages. :)

**Comment by 8191** [comment]
Sorry, I misunderstood: I thought this was intended as a backup-and-restore scenario, but I guess it is more intended as a 3rd party migration path?

**Comment by fichtner** [comment]
Exactly, bootstrapping a config for a larger network, or maybe a batch addition of hosts in the target network(s).

**Comment by fabianfrz** [comment]
@fichtner Would not that be easier when the api could be used for that?
