### ISSUE TITLE
Firewall log download returns an empty file of 0Kb

### ISSUE THREAD

**Issue by eduardodextil** [opnsense/core#6680]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

Describe the bug
OPNsense Version: 23.1.11
RAM 16GB
Disk size: 115GB
CPU size: Intel(R) Core(TM) i7-3612QE CPU @ 2.10GHz (4 cores, 8 threads)

Description:
In situations where the OPNsense box is in high traffic network generating many logs (Approx. 300MB daily; while trying to download firewall log files via the web GUI, an empty file of size 0kb is returned. Since the circular log files were replaced by the number of preservation days for logs to be stored, it becomes difficult to retrieve log files via the web GUI because of the size of the individual daily logs.
After editing different parameters in the backend and this issue not being resolved, there might be a hardcoded limit on the file size of logs that can be downloaded or retrieved via the web interface.

Steps to reproduce:
1.	Go to Firewall.
2.	Click on “Log Files.”
3.	Then click on “Plain view.”
4.	Scroll down to the end of the page and click the cloud download widget and the bottom right.
5.	The download process takes a while to complete, but an empty file is returned once completed.

Expected behavior:
The expected behavior is that the log files are downloaded successfully via the web GUI.

Alternative considered / Remediation.
Edited php.ini file in the (root/usr/local/opnsense/service/templates/OPNsense/WebGui) directory. Increasing the memory limit to 4GB & 8GB, respectively, increasing the upload_max_filesize to 2GB, increasing the post_max_size to 2GB, and changing the execution time and the max_input _time as “indefinite.” However, the same behavior was noticed despite changes to those php download parameters.

**Comment by AdSchellevis** [comment]
If I'm not mistaken, the filter applies on the download too. I'm not sure we can change this easily to stream the data to the browser, which would prevent memory exhaustion.

**Comment by eduardodextil** [comment]
Provided you have the memory resources. What are the options to prevent this behavior. Is there a hard coded limit in the source that can handle this exception ?

**Comment by AdSchellevis** [comment]
I would expect it crashes on a php memory limit, but it could also be crashing due to insufficient memory in the python script being passed through configd. You likely have to investigate more in order to know where it stops. Short term there's not much I can offer, I can label this ticket "feature request" and put it on the stack for future improvements. There is a way to offer this type of functionality, but it will easily cost a couple of working days to mature and develop.

For us it's currently not a super high priority, there are other means to export large sets as well.

**Comment by AdSchellevis** [comment]
requires https://github.com/opnsense/core/commit/cee33f5393154bb459150fd4639a6a8cd77456ee in combination with https://github.com/opnsense/core/commit/42fd27df777ee85a0e42767a814bed5e93659f0c and https://github.com/opnsense/core/commit/28b99101d45779c7f8e75e9c6817c942e2d0dfee
