### ISSUE TITLE
Wizard: LAN IP address is empty after entering invalid address and reloading

### ISSUE THREAD

**Issue by subnetspider** [opnsense/core#6681]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

After entering an invalid LAN IP address in the OPNsense wizard (e.g. an IPv6 address) and reloading at the end of the wizard, the LAN interface is left without an IPv4 interface. This practically breaks all connectivity of the LAN interface, including the GUI.

**To Reproduce**

1. Go to "System: Wizard"
2. Click "Next" until "System: Wizard: Configure LAN Interface".
3. Enter something invalid (e.g. "fd00:10::1") into the field "LAN IP Address:".
4. Click "OK" on the Pop-up "LAN IP Address field is invalid".
5. Click "Next" until "System: Wizard: Reload Configuration".
6. Click "Reload". 

**Expected behavior**

The Wizard should prevent the user from proceeding after entering an invalid IP address, instead of only displaying the "LAN IP Address field is invalid" popup, like by graying out the "Next" button. While it is the user's fault for proceeding after the warning, the LAN interface on OPNsense is rendered completely unusable (no DNS, DHCP, routing, GUI, etc.) until the setting is corrected at the command line.  

**Describe alternatives you considered**

Alternatively, if invalid data is entered in the LAN IP Address: field, the wizard could exit to the dashboard to prevent the user from locking themselves out.

**Screenshots**

Warning popup:

![grafik](https://github.com/opnsense/core/assets/111726680/811f8e1e-1f4f-4711-90bc-ddcd8f0ce34e)

After the reload, the "IPv4 Configuration Type" is changed to "None".

![grafik](https://github.com/opnsense/core/assets/111726680/57cff099-7b53-4cc0-a8d8-f5772a42fb2e)

**Relevant log files**

Configuration diff:

```
--- /conf/backup/config-1689971662.7157.xml	2023-07-21 22:34:22.716674000 +0200
+++ /conf/backup/config-1689971680.5847.xml	2023-07-21 22:34:40.585632000 +0200
@@ -277,7 +277,7 @@
       <descr/>
       <enable>1</enable>
       <spoofmac/>
-      <ipaddr>192.168.1.1</ipaddr>
+      <ipaddr>fd00:10::1</ipaddr>
       <subnet>24</subnet>
       <ipaddrv6>track6</ipaddrv6>
       <track6-interface>wan</track6-interface>
@@ -399,7 +399,7 @@
   </widgets>
   <revision>
     <username>root@192.168.1.2</username>
-    <time>1689971662.7157</time>
+    <time>1689971680.5847</time>
     <description>/wizard.php made changes</description>
   </revision>
   <OPNsense>
```

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 23.1.11-amd64
FreeBSD 13.1-RELEASE-p8
OpenSSL 1.1.1u 30 May 2023
Intel® Core™ i5-6500 3.2Ghz Quad Core
Network Intel® I350-T4

**Comment by subnetspider** [comment]
**Update**

It seems that there is already a check for invalid IP addresses, but it is not triggered with valid IPv6 addresses:

![grafik](https://github.com/opnsense/core/assets/111726680/8f4ffee0-f621-490c-b666-9555bb826010)

**Comment by fichtner** [comment]
@subnetspider thanks, c9bd89752 should fix this :)
