### ISSUE TITLE
[Feature Request] Captive Portal Additional Radius Attribute

### ISSUE THREAD

**Issue by filterfilter** [opnsense/core#6682]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

I am using OPNsense 23.1 with an external freeradius server (I am not using freeradius plugin), and I am trying to utilize the radius accounting.

I tested group-check with freeradius using attribute 'max-daily-session', and user will be automatically disconnected once it reach the configured value, for example below is 60.

(1) rest: Auth-Type := Accept <<<< user auth accepted
(1) rest: Parsing attribute "Session-Timeout"
(1) rest: EXPAND 60
(1) rest:    --> 60
(1) rest: Session-Timeout := 60 <<<< freeradius relpy the attribute Max-Daily-Session/Session-Timeout to captive portal during user auth

(14)   User-Name = "testvpn3"
(14)   Acct-Status-Type = Stop
(14)   Acct-Authentic = Local
(14)   Acct-Session-Time = 60 <<<<
(14)   Acct-Input-Octets = 52045
(14)   Acct-Output-Octets = 204323
(14)   Framed-IP-Address = 10.1.1.2
(14)   Acct-Terminate-Cause = User-Request <<<< I assume captive portal is sending the disconnect request, hence the cause is user-request.

Is it possible to add another attribute, it is something like 'Bandwidth-Usage' that is used to count the total bandwidth usage of the user, so if it reach the configured value, captive portal will send a disconnect request similar to Max-Daily-Session.

I notice there is a bytes_in and bytes_out in captive portal sqlite db or Acct-Input-Octets and Acct-Output-Octets that is being sent out as accounting update (I guess that is something that captive portal already track locally)

,     bytes_in integer default (0)
,     bytes_out integer default (0)

Is this something that is possible to be added into captive portal functionality?
from https://docs.opnsense.org/manual/how-tos/accounting.html, it seems to support 'Daily-Session-Time' and 'Max-Daily-Session'

Thanks!

**Comment by AdSchellevis** [comment]
We currently do not have plans to invest in that direction, we had some requests from prospects in the past which didn't lead to anything. Usually when this type of functionality is needed, there's a clear commercial business case involved as well (charging customers per megabyte).

**Comment by filterfilter** [comment]
Understand and thank you for your response, if in the future OPNsense are planning to have some feature enablement that are locked behind a license/commercial, it is definitely something that I would consider (esp. if it is AWS/Azure BYOL or PAYG type of thing)

I am closing this issues as I have gotten the response for my query.
