### ISSUE TITLE
ANY route required otherwise PBR not working

### ISSUE THREAD

**Issue by kub3let** [opnsense/core#6684]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

I wanted to get this out here since it took me over 2 hours to figure this out, maybe it will save someone else.

If you route IPv6 over a VPN tunnel, e.g. the Firewall is IPv4 only and want to setup PBR the routing will not work unless **any** IPv6 route is added in the system routing table.

So let's say you add a PBR:
``Firewall -> Rules -> lan -> add``
``action: pass, direction: out, ip version: ipv6, source: lan net, gateway: ipv6-gateway``

**Ping to global IPv6 lan address does not work...**

Now adding any random IPv6 route to the system table, e.g.
``System -> Routes -> Configuration -> add``
``network: ::/0, gateway: Null6 ::1, description: dummy route``

**Ping to global IPv6 lan address works...**

So here I am wondering why I need to add a route to the system table ? 

Seems to me like OPNsense automatically disables IPv6 routing if there is no route ?

**Expected behavior**

I would expect routing to work even if only PBR is used.

To be fair this only  affects you if you have no IPv6 on WAN since otherwise there will be a default route.

**Environment**

OPNsense 23.1.11 (amd64, OpenSSL).

**Comment by fichtner** [comment]
It sounds like a FreeBSD kernel issue to me. I’m not sure if it’s useful to add generic null routes to work around this. First time this has come up.

**Comment by kub3let** [comment]
I mainly wanted to have this documented, implementing a null route if no other route is defined in OPNsense sounds like a bad workaround.

It's unlikely there are any people behind a IPv4 only ISP which try to setup IPv6 via VPN like me.

**Comment by fichtner** [comment]
Well, we were discussing after all :) It's the weekend... Perhaps https://bugs.freebsd.org has a report for this already where we could gather more info. Perhaps there is also a patch already somewhere in FreeBSD.
