### ISSUE TITLE
interfaces: RXCSUM and netmap speedup

### ISSUE THREAD

**Issue by fichtner** [opnsense/core#6687]
**Important notices**

Our forum is located at https://forum.opnsense.org , please consider joining discussions there in stead of using GitHub for these matters.

Before you ask a new question, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

Discuss impact of RXCSUM on Netmap and how to expose it to the user. There seems to be an improvement possible in terms of processing speed as recently discovered around https://github.com/opnsense/src/commit/72ffa92d649779c8ab9d7dd6990fd32f7a849068

**Comment by fichtner** [comment]
I'm not entirely sure but since it's zero-copy it's likely going to be passed along just fine.

**Comment by swhite2** [comment]
Yep, you're right: https://github.com/opnsense/src/blob/stable/23.1/sys/dev/netmap/netmap.c#L1326

**Comment by AdSchellevis** [comment]
We should measure the difference before making changes to core.

**Comment by fichtner** [comment]
Abandoned this due to lack of need.
