### ISSUE TITLE
unbound not working after upgrade to 23.7

### ISSUE THREAD

**Issue by drinn** [opnsense/core#6690]
Unbound was working prior to upgrade to 23.7. After the upgrade, I found that unbound did not start up as it did prior to the upgrade.

I am using the Adguardhome which runs on the default port of 53. I am running unbound on a different port and adguardhome points to unbound to assist with lookups for static DHCP entries.

I am unable to unable the unbound service. Going to Services -> Unbound DNS -> General, I try and "Enable Unbound" and apply the changes but I'm receiving the following error:

![unbound](https://github.com/opnsense/core/assets/12588455/198f8881-1e05-4e4c-9f78-3980a61085e6)

**Comment by AdSchellevis** [comment]
sounds like a bug elsewhere (Adguardhome?), but our model should check type before usage

**Comment by crt333** [comment]
I had this same error and the one line edit also fixed unbound for me. I am running AG querying unbound on 5353.

Also, it seems that for some others as well, the update to 23.7 turned unbound off and wiped out a bunch of general settings (enabled, port number, DNSSEC, etc). Not sure if this is also related to AG usage. Some said that after resetting all the values unbound would start, others reported the error above.

**Comment by fichtner** [comment]
> Also, it seems that for some others as well, the update to 23.7 turned unbound off and wiped out a bunch of general settings (enabled, port number, DNSSEC, etc).

This sounds like the Unbound data migration fails, but we need the details on why that is. It's likely easy to reproduce with the right data, although this has been on the development version for several months without such a problem reported so far.


Cheers,
Franco

**Comment by fichtner** [comment]
@crt333 What happens when you run this?

    # /usr/local/opnsense/mvc/script/run_migrations.php

**Comment by crt333** [comment]
I have it working (reset all unbound parameters and manually edited the php file indicated in https://github.com/opnsense/core/commit/c61ef7a2876880222e09831bdf90f6a137a4f67c) so I'm not sure what running the script now will do.

Also, after the upgrade I changed unbound from DOT to recursive after figuring out a way for recursive to run through a wireguard tunnel (which wasn't easy). 

So, I'm afraid to run a script that might change something. Is it safe? What can be learned after all the changes I made?

**Comment by drinn** [comment]
> What happens when you run this?
> 
> `# /usr/local/opnsense/mvc/script/run_migrations.php`

I just ran this from my server and got the following output:

```
opnsense [~] # /usr/local/opnsense/mvc/script/run_migrations.php
Migrated OPNsense\Firewall\Group from 0.0.0 to 1.0.0
Migrated OPNsense\Unbound\Unbound from 1.0.4 to 1.0.6
Migrated OPNsense\OpenVPN\OpenVPN from 0.0.0 to 1.0.0
Migrated OPNsense\Interfaces\Lagg from <unversioned> to 1.0.0

```

Trying to run it again, it produces no output:

```
opnsense [~] # /usr/local/opnsense/mvc/script/run_migrations.php
opnsense [~] #
```

**Comment by mimugmail** [comment]
Updated the plugin, sorry for searching in the haystack

**Comment by drinn** [comment]
I updated my instance to include the updated plugin and the commit from 4c6d66e. I rebooted my instance and can confirm that everything started properly after a reboot. Thank you to everyone involved to help fix this issue!
