### ISSUE TITLE
VXLAN: Remote address change in the GUI does not change the actual remote address used

### ISSUE THREAD

**Issue by c-vo** [opnsense/core#6693]
- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

A clear and concise description of what the bug is:
After creating a VXLAN and adding it as an interface, the remote IP address cannot be effectively changed. While changes can be made in the GUI at any time, they do not take effect on the IP address actually being used.
Last known working version (if any): No version known

**To Reproduce**

0. Initial situation: Correctly configured VXLAN point to point interface according to https://docs.opnsense.org/manual/other-interfaces.html

1. Access the OPNsense Web GUI:
Open web browser and enter the IP address of your OPNsense firewall. Log in with appropriate credentials to access the web GUI.

2. Navigate to Interfaces:
Once logged in, click on "Interfaces" in the menu to access the network interface settings.

3. Change existing VXLAN Interface:

3a) Go to "Other Types" and „VXLAN“
3b) Choose the existing VXLAN Device and Click the edit-Button
3c) Change the Remote-Address in the „Remote address“-Field
3d) Click the „Save“-Button
3e) Click the „Apply“-Button
Optional: 3f) Reboot OPNsense
A clear and concise description of what you expected to happen:
Primarily, changing the remote address in the GUI should also change the remote address effectively used for VXLAN. Alternatively, changing the remote address in the GUI should be prevented.

A clear and concise description of any alternative solutions or workaround you considered:
The only known solution is to completely remove the VXLAN interface and VXLAN device and to create a new one.
I am not aware of any log files. However, the behavior can be observed in the live view of the firewall log by setting the filter to the VXLAN port, __port__=4789.

**Environment**
OPNsense 23.7-amd64
FreeBSD 13.2-RELEASE-p1
OpenSSL 1.1.1u 30 May 2023
Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (2 cores, 4 threads)

**Comment by AdSchellevis** [comment]
it might be locked while busy, trying the same sequence on my end doesn't seem to cause issues. You could try to change it manually, if only the address has changed, something like this should work:

```
ifconfig vxlan1 vxlanremote 127.0.0.4
```

**Comment by c-vo** [comment]
Thank you for the feedback. Unfortunately, I haven't found the cause yet. Even a reboot doesn't help in most cases. Now, after many reboots, the correct new remote address was suddenly used. Disabling the interface and re-enabling it didn't help either. It may also have something to do with the fact that a DHCP server is running on the VXLAN and that the VXLAN is running via Wireguard. I'll take a closer look towards the weekend and give feedback here.

**Comment by c-vo** [comment]
Unfortunately I could not find the cause clearly. It seems like the problem only occurs sometimes and only under certain circumstances. Unfortunately, it was not possible to narrow it down further at the moment, so I am closing the issue.

**Comment by c-vo** [comment]
Unfortunately I could not find the cause clearly. It seems like the problem only occurs sometimes and only under certain circumstances. Unfortunately, it was not possible to narrow it down further at the moment, so I am closing the issue.
