### ISSUE TITLE
Error when deleting static key on new OpenVPN interface

### ISSUE THREAD

**Issue by Skywalker-11** [opnsense/core#6697]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

Error when deleting static key on new OpenVPN interface (23.7 release) 

**To Reproduce**

1. Go to VPN>OpenVPN>Instances[new]>Static Keys
2. Create new Static Key
3. Click on Trash icon to delete the static key and confirm
5. Error occures
"An API exception occured": `/usr/local/opnsense/mvc/app/controllers/OPNsense/OpenVPN/Api/InstancesController.php:99: Call to undefined method OPNsense\OpenVPN\Api\InstancesController::delStaticKeyBase()`

**Expected behavior**

Static key should be deleted

**Describe alternatives you considered**

A clear and concise description of any alternative solutions or workaround you considered.

**Environment**

OPNsense 23.7(amd64, OpenSSL)

**Comment by fichtner** [comment]
https://github.com/opnsense/core/commit/da64b4f9443b9845635f4e8e9ed1f1e6b27fc431
