### ISSUE TITLE
OpenVPN: Add missing option for server certificate verification for MVC

### ISSUE THREAD

**Issue by ruifung** [opnsense/core#6698]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**

In the old OpenVPN/Clients setting page, you can specify an option to select a CA certificate to use to verify the server's certificate. But in the new OpenVPN Instances page, there is no such option.

OpenVPN even logs a warning with regards to this:
```
WARNING: No server certificate verification method has been enabled. See http://openvpn.net/howto.html#mitm for more info.
```

**Describe the solution you like**

For the option to select a CA certificate to use to verify the server certificate to be added to the new pages.

**Describe alternatives you considered**

No other alternatives have been considered.

**Additional context**

OPNsense 23.7-amd64
FreeBSD 13.2-RELEASE-p1
OpenSSL 1.1.1u 30 May 2023

**Comment by ruifung** [comment]
Nevermind, Just checked with the older clients. The warning is still printed.
I might re-open this at a later date with an updated details. Closing for now.

**Comment by Skywalker-11** [comment]
I would also like the option to specify a CA to validate the remote certificates to be reintroduced. 
The CA for the server certificate should instead be specified via the extra-certs option.
