### ISSUE TITLE
Certificate Depth not saved in new OpenVPN interface

### ISSUE THREAD

**Issue by Skywalker-11** [opnsense/core#6701]
**Important notices**

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

When setting `Certificate Depth` in the new OpenVPN interface the setting is not saved

**To Reproduce**

1. Open settings for OpenVPN instance in 23.7 interface
2. Set a value for `Certificate Depth` and save the settings
3. Open the settings again
4. Setting is not saved

**Expected behavior**

Setting should be saved
**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 23.7(amd64, OpenSSL).

**Comment by fichtner** [comment]
This was https://github.com/opnsense/core/issues/6692
