### ISSUE TITLE
IPv6 router advertisement from one vlan is distributed to all other vlans

### ISSUE THREAD

**Issue by denny123305** [opnsense/core#6713]
**Bug Description**

IPv6 router advertisement from one vlan is distributed to all other vlans on the physical interface and to the interface itself.
If I activate the ipv6 track interface option on an interface (e.g. vlan10), then router advertisements are also sent outside of this network to all networks that are on the same physical interface (i.e. vlan11, lan).

The problem is then, if I activate the track interface option on two interfaces, that my end devices in the corresponding networks then have all 4 ipv6 addresses (2 addresses each from each existing network), but that shouldn't be the case and I'm also nonsense because otherwise I would not segment my networks.

**To Reproduce**

Enable track interface option on two interfaces (e.g. vlan10, vlan11) .
Have a look to ipconfig on your end devices in the corresponding network.

**Expected behavior**

normally only one router advertisement should pass through per interface, so that each end device only receives one ipv6 address from your network

**Screenshots**

![grafik](https://github.com/opnsense/core/assets/141491179/c5d7de17-0403-4384-886c-2b3f892d969e)

![grafik](https://github.com/opnsense/core/assets/141491179/af13d75a-c638-47d9-8939-9c97abcb1626)

activate the same on another interface

![grafik](https://github.com/opnsense/core/assets/141491179/dfbee513-edd8-48e5-82c0-ca2bbb40a56d)
ipconfig snippet from end device

**Environment**

OPNsense 23.1.11_1-amd64
FreeBSD 13.1-RELEASE-p8
OpenSSL 1.1.1u 30 May 2023

AMD GX-420CA SOC with Radeon(tm) HD Graphics (4 cores, 4 threads)

**Comment by fichtner** [comment]
Not sure how this would work. Perhaps a faulty switch with multicast forwarding. Or the result of bridging VLANs together. But that would also be a security issue of your network setup at hand.

**Comment by denny123305** [comment]
> Not sure how this would work. Perhaps a faulty switch with multicast forwarding. Or the result of bridging VLANs together. But that would also be a security issue of your network setup at hand.

There is no switch with faulty multicast forwarding (igmp snooping is only act on vlan11, because of iptv in that network) and no bridged layer 2 networks. 

Here is a visio sheet of my network structure:
[network.pdf](https://github.com/opnsense/core/files/12272624/network.pdf)
