### ISSUE TITLE
Add ICMP6 Support to Shaper

### ISSUE THREAD

**Issue by aque** [opnsense/core#6714]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**

I investigated an issue where my IPv6 gateway experienced packet loss and goes offline whenever I saturate my uplink. IPv4 dpinger (under 23.1) showed no issues. I have a shaper catchall rule that sends all upload IP packets to an FQ_CoDel queue. Under a higher priority, I send ICMP packets to a separate FIFO pipe so it does not fall into the catchall.

    60001 pipe 10004 icmp from any to any via lagg0 // 1b5cdc2d-f045-4c2a-a085-1eab471e4125 wan: PipeFIFO-1M

Apparently `icmp` does not include IPv6 ICMP packets. These packets were falling through this ICMP rule and hitting the FQ_CoDel catchall, resulting in “packet loss” when the algorithm properly discards packets to shape uplink traffic.

**Describe the solution you like**

Add ‘icmp6’ to shaper protocols that creates `ipv6-icmp` rules in order to handle IPv6 ICMP packets.  I was able to test by adding the rule below with `ipfw`.

    60002 pipe 10004 ipv6-icmp from any to any out via lagg0 // c7ac91ad-ec86-47db-b835-25b78a82332c wan: PipeFIFO-1M

The existing `icmp` protocol should be renamed into `icmp4` to remove ambiguity.

**Describe alternatives you considered**

I put a workaround by breaking up my catchall into 4 separate rules. I send the following protocols to FQ_CoDel: ipv4, udp, and tcp. Then, my last rule sends ip protocol packets to the FIFO pipe.

**Comment by AdSchellevis** [comment]
adding ipv6-icmp to the list isn't an issue, done in https://github.com/opnsense/core/commit/fd6c824a5b0a070a939a7d2cfc7ca59623bb3af6. We're not going to rename `icmp` though as this is the original protocol name (https://www.iana.org/assignments/protocol-numbers/protocol-numbers.xhtml)

**Comment by aque** [comment]
Thank you for your consideration @AdSchellevis.
