### ISSUE TITLE
DHCPD: DHCPv6 Leases do not display since upgrade to 27.1

### ISSUE THREAD

**Issue by billgertz** [opnsense/core#6715]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

No leases are being shown in the **Services**, **DHCPv6**, then the **Leases** tab. This was working under the previous version just before 27.1

**To Reproduce**

1. Configure DHCPv6 to give leases for an interface. For example:

<img width="1795" alt="Screenshot 2023-08-06 at 19 16 05" src="https://github.com/opnsense/core/assets/3613249/3107b6f3-dbb2-4bb8-9882-b131f4d8b163">

2. Go to **Services**, **DHCPv6**, then the **Leases** tab
3. Notice there ar no leases shown:

<img width="1833" alt="Screenshot 2023-08-06 at 19 14 50" src="https://github.com/opnsense/core/assets/3613249/c4c104bc-cf96-44f3-ba0a-a971a4e04a72">

4. Login into the OPNsense host as root and then select 8) Shell
5. Change to the /var/dhcpd/var/db directory.
6. Display the dhcp6.leases file and notice there are leases:

```
root@opnsense:/var/dhcpd/var/db # cat dhcpd6.leases
# The format of this file is documented in the dhcpd.leases(5) manual page.
# This lease file was written by isc-dhcp-4.4.3-P1

# authoring-byte-order entry is generated, DO NOT DELETE
authoring-byte-order little-endian;

server-duid "\000\001\000\001,Lw\003\246\321Qa\376\037";

ia-na "xm\336\365\000\001\000\001,L\264_\000\012\365\336mx" {
  cltt 0 2023/08/06 17:15:58;
  iaaddr 2001:470:786f:2:ffff:0:8ca:ea95 {
    binding state active;
    preferred-life 4500;
    max-life 7200;
    ends 0 2023/08/06 18:47:47;
  }
}

ia-na "\013\245F\032\000\002\000\000\253\021f\201y\231%{\327\262" {
  cltt 1 2023/07/31 16:32:32;
}

ia-na "\000\000\000\000\000\001\000\001,L\005\237\254\207\243\022\034," {
  cltt 0 2023/08/06 16:52:41;
  iaaddr 2001:470:786f:2:ffff:0:8f6a:9733 {
    binding state active;
    preferred-life 4500;
    max-life 7200;
    ends 0 2023/08/06 18:52:41;
  }
}

ia-na "\323M&\012\000\001\000\001+\011j/\212\030\377\206\270*" {
  cltt 0 2023/08/06 16:52:44;
  iaaddr 2001:470:786f:2:ffff:0:f7df:87b8 {
    binding state active;
    preferred-life 4500;
    max-life 7200;
    ends 0 2023/08/06 18:52:44;
  }
}

ia-na "\366d\232\356\000\002\000\000\253\021\374\201m\254\343\177\020`" {
  cltt 0 2023/08/06 17:12:38;
  iaaddr 2001:470:786f:3:ffff:0:4589:7109 {
    binding state active;
    preferred-life 4500;
    max-life 7200;
```

**Expected behavior**

Display the leases in the **Services**, **DHCPv6**,  **Leases** tab.

**Describe alternatives you considered**

See steps 4. through 6. above but not ideal. I would expect most system admins not to know where to dig.

**Relevant log files**

See above.

**Environment**

OPNsense Versions:

   OPNsense 23.7-amd64
   FreeBSD 13.2-RELEASE-p1
   OpenSSL 1.1.1u 30 May 2023

Host:

   xcp-ng 8.2

**Comment by AdSchellevis** [comment]
might be https://github.com/opnsense/core/commit/23318015b2abc075a3bf506533da07ea740d2250 + https://github.com/opnsense/core/commit/4ec97df4c475223b31df31cb61e78f1bdb71d789

**Comment by fichtner** [comment]
Yep

**Comment by fichtner** [comment]
> Next release?

Yes.

**Comment by billgertz** [comment]
@fichtner @AdSchellevis Can confirm DHCPv6 leases are again being displayed in Services -> DHCPv6 -> Leases in release 23.7.1. Thanks!
