### ISSUE TITLE
Openvpn client export error

### ISSUE THREAD

**Issue by skyeci-draytek** [opnsense/core#6717]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**
Following upgrade to 23.7 if you try an export user profile from openvpn client export the user name and password credentials are missing . Tried both openvpn client on pc and android but when importing the file the credentials details are missing. 
A workaround is to manually add "auth-user-pass"
in the "custom-config" box.
Worked without the custom config before 23.7
**To Reproduce**

1. Go to vpn,openvpn, client export then go to the user accounts below. Export the file.
Try importing file and no user account or password fields will be carried over. 

**Expected behavior**

username and password details should be exported.

**Describe alternatives you considered**

work around is to add "auth-user-pass" to the custom config box, was not required pre 23.7 release

OPNsense 23.7-amd64
FreeBSD 13.2-RELEASE-p1
OpenSSL 1.1.1u 30 May 2023

**Comment by AdSchellevis** [comment]
thanks for the ticket, fixed it yesterday in https://github.com/opnsense/core/commit/48462b4dfd12c4ba8c14f29557a54fc73e363c01
