### ISSUE TITLE
DHCP server distributes IPv6 address of interface as DNS server

### ISSUE THREAD

**Issue by thomasglauser** [opnsense/core#6718]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

I am using OPNsense 23.7-amd64 with multiple VLANS. On VLAN 21 I have 2 DNS servers running for my whole network.
The clients are on VLAN 30. In the DHCPv4 settings I have configured the 2 IPv4 DNS servers of VLAN 21 as the DNS servers:

![image](https://github.com/opnsense/core/assets/36607394/fd5cfc7a-e627-4c9e-9b35-d04e749131ca)

Unfortunately, all clients receive a different DNS server list via DHCP. The IPv6 address of the VLAN 30 interface is also distributed:

![image](https://github.com/opnsense/core/assets/36607394/c4095217-cce5-47a7-95f1-b1e7299d85ce)

I have Unbound DNS running as an upstream server for my 2 DNS servers, but only listening on VLAN 21:

![image](https://github.com/opnsense/core/assets/36607394/58c0bb7a-6f0e-469b-ad7f-6107663549a0)

The general system settings are configured without IPv6 address:
![image](https://github.com/opnsense/core/assets/36607394/761287a6-4227-4537-9cb2-c1faedae2c14)

**To Reproduce**

1. Set up 2 VLANs with IPv4 and IPv6 track interface. One client VLAN (30) and one server VLAN (21).
2. Run Unbound DNS on the Server VLAN 21
3. Run a DHCPv4 server on the client VLAN with two IPv4 DNS servers in the list.
4. In addition to the two IPv4 addresses, the clients also receive an IPv6 DNS server. The IPv6 address is that of the interface.

**Expected behavior**

The IPv6 address should not be distributed to the clients via DHCP because it is not configured anywhere.

**Describe alternatives you considered**

Once I disable IPv6 on the Client interface, the DNS server list is correct.

**Screenshots**

See above

**Relevant log files**

Not applicable.

**Additional context**

Not applicable.

**Environment**

OPNsense 23.7-amd64
FreeBSD 13.2-RELEASE-p1
FreeBSD 13.2-RELEASE-p1
OPNsense DEC840 appliance

**Comment by fichtner** [comment]
Hi,

I don’t understand this report.


Cheers,
Franco

**Comment by thomasglauser** [comment]
Ok I will try to simplify the report.

I have a VLAN (30) 10.30.0.1/24 with several Windows clients that get their IP from OPNsense via DHCP.
In the DHCPv4 configuration of the interface VLAN 30, I have configured 2 DNS servers (10.21.0.10 and 10.21.0.11) which are in a separate VLAN 21.

Somehow the Windows clients get assigned 3 DNS servers via DHCP:
XXXX:XXX:XXXX:7730:f690:eaff:fe00:627e -> This is the IPv6 address of interface VLAN 30 which should not be here.
10.21.0.10 -> This address is specified in the DHCPv4 configuration.
10.21.0.11 -> This is configured in the DHCPv4 configuration.

I don't understand why the IPv6 interface address is distributed as a DNS server.
The address is not configured as DNS server anywhere. This causes issues with DNS resolution on the clients.

**Comment by fichtner** [comment]
I think I get it now: selecting specific interfaces for Unbound (which is discouraged) will not stop the DHCP server from selecting Unbound as a DNS server for all interfaces. Chances are you need to set one instead or use NAT to provide one for this network, or use the override “none” to prevent that from happening.

Cheers,
Franco

**Comment by maurice-w** [comment]
Works as designed. If Unbound is globally enabled, LAN interface addresses are advertised as a DNS server via DHCPv4, DHCPv6 and Router Advertisements - unless explicitly configured otherwise.

> On VLAN 21 I have 2 DNS servers running for my whole network.
The clients are on VLAN 30. In the DHCPv4 settings I have configured the 2 IPv4 DNS servers of VLAN 21 as the DNS servers.

You need to do exactly the same for DHCPv6 and Router Advertisements: Configure the 2 IPv6 DNS servers of VLAN 21 as the DNS servers.

**Comment by thomasglauser** [comment]
I have not enabled Unbound globally. Under "Network Interfaces" I have selected only VLAN21. Unbound still registers itself as IPv4 DNS on each interface. But yes, I think this is the solution. I have configured the 2 DNS servers in DHCPv6 and Router Advertisement.

**Comment by maurice-w** [comment]
@thomasglauser Misunderstanding. By "globally enabled" I simply meant "enabled", not necessarily "binding to all interfaces". The DHCP servers and radvd only check whether Unbound is enabled, not whether it's actually listening on a specific interface. That might seem counterintuitive, but it is how it is.

**Comment by thomasglauser** [comment]
Alright thanks. I'll close this issue.
