### ISSUE TITLE
is impossible install or bootstrap freebsd (aws marketplace) to opnsense on EC2?

### ISSUE THREAD

**Issue by fiantyogalihp** [opnsense/core#6721]
i have install .raw file from opnsense and "instance status check" is failed,

i try another solution, it's bootstrap freebsd (aws marketplace) to opnsense, and still "instance status check" is failed,

NO ONE is successfully, anyone has a documentation, article or anything is help me alot :)

thanks!
~tyo

**Comment by AdSchellevis** [comment]
duplicate https://github.com/opnsense/core/issues/6239#issuecomment-1380037316
