### ISSUE TITLE
Port forward clone keeps the same/updates the original filter rule association

### ISSUE THREAD

**Issue by Lennie** [opnsense/core#6723]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

Port forward clone keeps the same/updates the original filter rule association, but also can't choose to create a filter rule new association.

Tested with OPNsense 23.7-amd64

This issue didn't exist in OPNsense 21.1.5-amd64

**To Reproduce**

1. go to NAT ->  port forward and create a new rule for WAN to LAN, don't change the setting for filter rule association
2. check go to Rules -> WAN you'll see the filter rule association is created
3. go to NAT -> port forward, clone the original port forward rule
4. make the needed changes, can only choose rule, pass, none, leave it on the default 'rule'

**Expected behavior**

A clone would create a new filter rule association. At step 4, expected: 'add filter rule association'

**Describe alternatives you considered**

A workaround exists, which also supports the theory of the issue.

1. go to Rules -> WAN
2. delete the filter rule
3. save
4. go to NAT -> port forward
5. edit both NAT port forward entries and choose 'add filter rule association' 
6. go to Rules -> WAN 
7. you now have 2 filter rules for the 2 NAT port forwards

**Comment by AdSchellevis** [comment]
looks like a slip of the pen in https://github.com/opnsense/core/commit/e5c2ac59097152fa1d981b0c82744236ebd9afb0 , will fix in the next commit.
