### ISSUE TITLE
Trying to Delete a DHCP lease returns a 400 Bad Request Error

### ISSUE THREAD

**Issue by eneerge** [opnsense/core#6725]
I just updated to 23.7.1-amd64.

When you go to Services -> DHCPv4 -> Leases and then you click on the Recycle Bin/Delete button for a lease, the entry is not deleted and there is an error in the browser console showing 400 Bad Request when requesting /api/dhcp/leases/delLease/<ip.address>

**Comment by eneerge** [comment]
controller OPNsense\\Core\\Api\\IndexController not found

**Comment by fichtner** [comment]
Likely https://github.com/opnsense/core/commit/b842980bb4

**Comment by eneerge** [comment]
I just tried manually navigating to /api/dhcpv4/leases/delLease/<ip.address> and it just returned "result: failed"

**Comment by eneerge** [comment]
Nevermind, it required a JSON body. Using v4 url worked.

**Comment by fichtner** [comment]
Thanks, I'll hotfix this since the patch is available and we need to address a NTP problem as well.


Cheers,
Franco
