### ISSUE TITLE
VPN: IPsec: Pre-Shared Keys - IPV6 Address not Permitted - The identifier contains invalid characters

### ISSUE THREAD

**Issue by firestormo** [opnsense/core#6727]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

Unable to Add IPV6 Addr for PSK

**To Reproduce**

1. Go to 'VPN'
2. Click on 'IPSEC'
3. Click on 'Pre-Shared Keys'
4.  Add a new Pre-Shared Key
5.  In Local or Remote Identifier Enter an IPV6 Address
6. See error 'The identifier contains invalid characters'

**Expected behavior**

I expect it to allow IPV6 addresses like it does with Names or IPV4 Addresses

![ipv6](https://github.com/opnsense/core/assets/42076498/60d74969-88a0-4d9d-891d-4354bd963ec5)

**Screenshots**
see attached

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 23.7.1_3-amd64
Intel(R) Xeon(R) D-1718T CPU @ 2.60GHz (4 cores, 8 threads)
Network Intel® I210-AT

**Comment by AdSchellevis** [comment]
@firestormo  https://github.com/opnsense/core/commit/0ab0bf309537df7e779fc02032f28a3d33cc8e18 should fix this.
