### ISSUE TITLE
Gateway Selection Problems

### ISSUE THREAD

**Issue by Daggolin** [opnsense/core#6728]
# Gateway Selection Problems

**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

As of 23.7 the gateway configuration of OPNsense does not seem to work correctly anymore. The default route of the system is not properly set on system boot and gateway switching does no longer work reliable when an interface looses or gains connectivity. We believe this to mostly be a regression due to the changes made for issue #6231. We have been experiencing two variations of the issue. Details follow below.

**What happened**

NOTE: connecting/disconnecting an interface in the texts below refers to plugging ethernet cables in/out, not removing or adding interfaces to a the system. The instance is running on a physical system, not a virtual machine.

In preparation for the update to 23.7 on our main instance we recently updated a test instance of OPNsense from 23.1.10 to 23.7.1_3. As soon as the system booted with 23.7.x the internet connectivity appeared to be lost and no external systems could be reached anymore. The connected interface seemed to be configured correctly, but the default route was pointing to the gateway with the highest priority (lowest value) despite that gateway being down, because the interface for that gateway was disconnected. Upon disconnecting and reconnecting the interface that the system was supposed to be using the default route was updated to match the available gateway and connectivity was restored. The same behaviour occurred after every reboot of the system - connectivity was lost every time. We proceeded upgrading to 23.7.1_3, but the issue still persisted.

Our system usually has 4 Uplinks configured:
 - igb5: static public IP 
 - igb4_vlan7: PPPoE via VLAN (gets assigned a public IP)
 - igb3: static private IP (acts as exposed host behind another system; indirectly reachable via public IP)
 - igb2: DHCP private IP (not publicly reachable)

The upstream gateways are usually configured like this (for ipv4 only, ignoring ipv6 here; different monitoring IPs are set for each gateway):
 - priority: 190 - GW_1: fixed public gateway IP (igb5)
 - priority: 200 - GW_2: dynamic gateway IP (igb4_vlan7)
 - priority: 230 - GW_3: fixed private gateway IP (igb3)
 - priority: 254 - GW_4: dynamic gateway IP (igb2)

When updating the system only igb2 was plugged in and GW_4 should have been used. This used to work on all previous versions of OPNsense that we used. However, after updating to 23.7 the gateway page `System > Gateways > Single` correctly showed GW_4 as the only online gateway, but the default route was set to the IP of GW_1 instead.

As the issue persisted after several reboots and upgrading to 23.7.1_3 we performed a few tests to get a better feeling for the issue:
 - in addition to igb2 we also connected igb3 and rebooted to confirm that the system would still use the gateway of the disconnected igb5 interface (and it did)
 - with igb2 and igb3 connected we increased the priority of GW_4 (reduced the value from 254 to 160) and rebooted to see if GW_4 would be picked now (and it was)
 - a few other combinations, but I don’t have sufficient notes on those

Additionally, during our tests we would disconnect and connect interfaces at runtime. When doing this the default gateway switching sometimes worked and other times it left us without a default route. Looking for GitHub issues and commits possibly related to the problems we encountered #6231 and looked into `src/opnsense/scripts/routes/gateway_watcher.php` (https://github.com/opnsense/core/blob/605042ada8eeb60ba9dd339f9ebfd246fa95633a/src/opnsense/scripts/routes/gateway_watcher.php). We have identified two possible issues within the script:
 1. when removing unknown interfaces no alarm is triggered unless another interface changed
 2. when a gateway is seen for the first time no alarm is triggered unless another interface changed

The first issue occurs when an interface that is configured to use DHCP gets disconnected. The corresponding gateway is no longer returned by `return_gateways_status`, leading to it silently getting discarded from the cached states in `gateway_monitor.php` without triggering the interface alarm. Thus, gateway switching doesn’t work reliable when DHCP interfaces loose connectivity at runtime.

The second issue occurs if `gateway_watcher.php` get executed when the currently used gateway is already down. As the gateway issue on boot persisted after we added a workaround for the first issue this is probably something that happens if you reboot the system while the gateway with the highest priority is unreachable. Considering unknown gateways get removed in the `gateway_monitor.php` loop and gateways on DHCP interfaces can disappear/reappear at runtime this is probably something that can cause issues at runtime, too.

To solve the issues on our system we simply ended up setting the `$alarm` variable in `gateway_monitor.php` to `true` if a gateway gets removed or a new one is first seen. I assume you may want to handle this slightly different than we did or add some log messages when this happens. Thus I am not making a PR for 2 lines, but this is the diff for reference:
```
diff --git a/src/opnsense/scripts/routes/gateway_watcher.php b/src/opnsense/scripts/routes/gateway_watcher.php
index 44c72ec36..1d265a1c5 100755
--- a/src/opnsense/scripts/routes/gateway_watcher.php
+++ b/src/opnsense/scripts/routes/gateway_watcher.php
@@ -57,6 +57,7 @@ while (1) {
     }
     foreach (array_keys($cleanup) as $stale) {
         unset($mode[$stale]);
+        $alarm = true;
     }
 
     /* run main watcher pass */
@@ -71,6 +72,7 @@ while (1) {
         if (empty($mode[$report['name']])) {
             /* skip one round for baseline */
             $mode[$report['name']] = $report['status'];
+            $alarm = true;
             continue;
         }
```

**Expected behavior**

We expected the system would automatically pick an available upstream gateway on boot after updating to 23.7, like it used to do on older versions. We also expected that the system would automatically switch to another upstream gateway if the current one became unavailable.

**To Reproduce**

We only reproduced the issues in our test environment with existing configs, thus we don’t know if this works on a fresh install or not.

Variant 1 (Boot issue):
 - Requirements:
   1. Setup with multiple WAN interfaces
 - Steps to reproduce:
   1. Make sure only one of the WAN interfaces is connected
   2. Go to `System > Gateways > Single`
   3. Assign highest priority (lowest value) to the gateway of the disconnected interface
   4. Reboot the system

Variant 2 (DHCP interface issue):
 - Requirements:
   1. Setup with multiple WAN interfaces
   2. At least one of the WAN interfaces needs a dynamic gateway (DHCP, might also work for PPPoE)
 - Steps to reproduce:
   1. Make sure both of the WAN interfaces are connected
   2. Go to `System > Gateways > Single`
   3. Assign highest priority (lowest value) to the dynamic gateway
   4. Disconnect the interface with the dynamic gateway that has higher priority (lower value)

**Describe alternatives you considered**

Running own scripts/services on the system to take care of interfaces and routes. Not really something we would want to do.

**Environment**

Versions:
 - OPNsense 23.7.1_3-amd64
 - FreeBSD 13.2-RELEASE-p2
 - OpenSSL 1.1.1v 1 Aug 2023

CPU type:
 - Intel(R) Xeon(R) CPU D-1518 @ 2.20GHz (4 cores, 8 threads)

**Comment by fichtner** [comment]
@Daggolin thanks for the detailed report. I agree with most of this keeping in mind that we wanted to bring down the reload attempts to a minimum from previously triggering on any alarm even if it had no impact on the system. The transition from an up to down interface likely works fine, but not the other way around as it requires either to trigger spurious reloads or introspection in order to know that a trigger point has been reached. I'll look into it in more detail now.

One question though: you said your highest priority gateway is selected after boot... that means you are not using "default gateway switching" option? Are the gateways instead added to a gateway group?


Cheers,
Franco

**Comment by fichtner** [comment]
Note: much of the observed issues are by design: initial down->none transitions are avoided in the status code, which makes it pretty much impossible to watch for. Also "down" gateways are treated as "disabled" which disappears their current gateway monitoring status.

Just adding alarms brings us back to the old trigger-happy behaviour which is discouraged...

**Comment by Daggolin** [comment]
@fichtner, thanks for the quick response.

> The transition from an up to down interface likely works fine

The problem with gateways on DHCP interfaces (referred to as variant 2 above) is that the gateway is no longer part of the data returned by the function `return_gateways_status`. The dynamic gateways don’t actually switch to `down` when their interface gets disconnected, they just disappear (IF they actually get into the down state it is probably too short and happens between two polls of the script). This causes the cleanup code to remove the cached interface status stored in `mode[$report['name']` (https://github.com/opnsense/core/blob/605042ada8eeb60ba9dd339f9ebfd246fa95633a/src/opnsense/scripts/routes/gateway_watcher.php#L53-L60). For that reason transitions from up to down do NOT work fine. In that cleanup loop there should at least be handling for interfaces disappearing that were not down before disappearing like `if ( $mode[$report['name']] != 'down') $alarm = true;`. I would also recommend to perform the same check when new gateways appear (https://github.com/opnsense/core/blob/605042ada8eeb60ba9dd339f9ebfd246fa95633a/src/opnsense/scripts/routes/gateway_watcher.php#L71-L75), otherwise a gateway may already be up when it is first handled by the gateway monitor (the script is polling after all and it might miss a new gateway that quickly gets added and becomes up).

> One question though: you said your highest priority gateway is selected after boot... that means you are not using "default gateway switching" option? Are the gateways instead added to a gateway group?

Sorry, forgot to mention this in the initial post: the option “default gateway switching” is enabled and all the gateways described above are set as upstream gateways. It should automatically pick an online one as default gateway, just like it did for the last few years. Additionally some of the gateways are part of gateway groups used in firewall rules for specific networks. So far OPNsense has always used the upstream gateways for update checks, Unbound, etc. and ignored the gateway groups. According to the description on `System > Gateways > Group` that is how is should be: gateway groups require firewall rules in order to take effect, implying they should not affect the choice of default gateway OPNsense makes for itself when “default gateway switching” is enabled. So far I have no reason to believe this has changed.


> Note: much of the observed issues are by design: initial down->none transitions are avoided in the status code, which makes it pretty much impossible to watch for. Also "down" gateways are treated as "disabled" which disappears their current gateway monitoring status.
> 
> Just adding alarms brings us back to the old trigger-happy behaviour which is discouraged...

The current implementation seems to be very unreliable according to our tests, making 23.7 in its current state pretty unusable for multi WAN setups that tend to have some uplinks go down for a while. That kind of defeats the purpose of having multiple uplinks for redundancy. Especially if gateway selection doesn’t properly pick an available gateway on boot and completely disregards whole interfaces going down, still clinging to a gateway that is clearly offline.

**Comment by fichtner** [comment]
d1d255a24 fixes the down gateway visibility -- also for the dashboard so it's easier to observe. I'm still shying away from triggering alerts without having a proper syslog entries associated with it so that's why the solution looks different than your proposal.

    # opnsense-patch d1d255a24

> It should automatically pick an online one as default gateway, just like it did for the last few years.

It still does unless the state of the interface cannot be quickly monitored and appears "down" when the boot process (as always) tries to set a default route. It's pretty much impossible to make any guess on the boot sequence without a log attached and you already established the watcher script can fix this which means the previous alert behaviour of dpinger likely fixed this at some point for some reason... it was likely doing multiple reloads in a row until it settled with a default gateway.

That's easy to test by removing the `/usr/local/etc/rc.syshook.d/monitor/10-dpinger` script on 23.1.11, rebooting and seeing if the default route is up after boot which I suspect is not the case as witnessed here.


Cheers,
Franco

**Comment by aque** [comment]
@fichtner let me know if I should file a different issue. When I check Disable Gateway Monitoring, that gateway shows up as Pending under Gateways > Groups instead of Online. I was able to determine `empty($gateways_status[$gwname])` returns `true` for that `$gwname`.

**Comment by fichtner** [comment]
@aque Is that with or without the patch above? Because I can't reproduce this on the latest development state.


Cheers,
Franco

**Comment by Daggolin** [comment]
> ```
> # opnsense-patch d1d255a24
> ```
We reverted our own changes, confirmed that the issues resurfaced and then applied your patch using the `opnsense-patch` tool. The issues seem to be resolved as of [d1d255a](https://github.com/opnsense/core/commit/d1d255a24d4824ab5e3e97e49fa51a888431df4d). The tests described in the initial post and various other combinations now work as expected - just a bit slow sometimes, but usually within less than half a minute.

I consider the reported issues resolved now, thank you.
Leaving the issue open, because of the latest 2 comments. Feel free to close this as resolved.

**Comment by aque** [comment]
@fichtner it is without the patch. I just installed the patch and it seems to have fixed it.

**Comment by ashceryth** [comment]
@fichtner

Hi Franco! So, am I understanding this correctly, there is currently no way to automatically switch back the default route when the primary WAN interface gets back online?

I am running a dual WAN setup with Fiber on the primary link and LTE on the secondary. As my LTE package is very limited (just a few GB each month) I want to switch back the default route to the primary interface as soon as it is back online. I'm just using priority settings for the gateways and  "Default gateway switching" without any firewall rules or gateway groups. This worked fine up to 23.7.

PS: Also tested with patch d1d255a24.
