### ISSUE TITLE
Monit: program stuck on "Initializing"

### ISSUE THREAD

**Issue by giggio** [opnsense/core#6730]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

When you create a monit service of type custom the status page does not display the status right away, even if timeout is set low.

**To Reproduce**

1. Go to Services > Monit > Settings
2. Create a service of type custom
3. Select advanced options
4. Set the timeout field to a low number, like 5
5. Set as path a program that can run fast and not fail, like `/bin/echo 1`
6. Save and apply
7. Go to the monit status page, notice that this test will show as initializing, even after you wait for several minutes, like so:

```
Program 'myprogram'
  status                       Initializing
  monitoring status            Initializing
  monitoring mode              active
  on reboot                    start
  data collected               Thu, 10 Aug 2023 02:22:48
```

**Expected behavior**

The status show within the specified timeout.

**Describe alternatives you considered**

N/A.

**Screenshots**

N/A.

**Relevant log files**

N/A.

**Additional context**

The problem is consistent, all `check program` tests show the same behavior.

Other services of different types show status right away, when Monit is started.

There are no logs showing this progressing, or that seem to explain the delay.

This is the snippet from `/usr/local/etc/monitrc` with relevant parts included:

````
set httpd unixsocket /var/run/monit.sock
    allow localhost

set daemon 360 with start delay 300

set logfile syslog facility log_daemon

set mailserver <REDACTED>

set alert <REDACTED>

check program myprogram with path "/bin/echo 1" timeout 5 seconds
   if status != 0 then alert
````

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 23.7.1_3-amd64
FreeBSD 13.2-RELEASE-p2
OpenSSL 1.1.1v 1 Aug 2023
Intel(R) Celeron(R) CPU J1900 @ 1.99GHz (4 cores, 4 threads)

**Comment by mimugmail** [comment]
Did you wait 5 minutes after starting to recheck the status?

**Comment by giggio** [comment]
Yes, it then shows the correct status.

**Comment by mimugmail** [comment]
Then you have to reduce start delay :)
Close then?

**Comment by giggio** [comment]
Start delay only applies to custom/program tests? I thought it applied to all of them.
And the UI says it only applies on OpnSense boot, is it Monit start or boot? If it is Monit start it would be a good idea to change the help text in the UI.

**Comment by giggio** [comment]
I have checked in the terminal with `monit status` that the web ui only shows what is already defined by Monit. So, the discussion about showing the initializing message is not to be had here, but at the [Monit repo](https://bitbucket.org/tildeslash/monit/).

Just to add more information: lowering the start delay to 2 minutes did not make the `initializing` message to go away in 2 minutes.
It seems that the first check por `program` is at the first daemon run, which, in my case, is 6 minutes. Those are not checked when Monit starts.

Also, there is no start delay whatsoever when restarting the service. All services are checked immediately. It would be nice to confirm this behavior, because if this is the case, then either the start delay is useless, or it really only applies to a reboot (I have not checked that).

I'll close the issue, but maybe these insights demand some exploration.

Thanks for the help.

**Comment by giggio** [comment]
More insight from the [Monit manual](https://mmonit.com/monit/documentation/monit.html#PROGRAM-STATUS-TEST), that confirms that the behavior for `program` is different:

> Program checks are asynchronous. Meaning that Monit will not wait for the program to exit, but instead, Monit will start the program in the background and immediately continue checking the next service entry in monitrc. At the next cycle, Monit will check if the program has finished and if so, collect the program's exit status. If the status indicate a failure, Monit will raise an alert message containing the program's error (stderr) output, if any. If the program has not exited after the first cycle, Monit will wait another cycle and so on. If the program is still running after 5 minutes, Monit will kill it and generate a program timeout event. It is possible to override the default timeout (see the syntax below).

There is an issue opened at the Monit repo, and they plan to fix it, but they said they would fix it 2 years ago.

https://bitbucket.org/tildeslash/monit/issues/1019/check-program-status-shows-initializing

**Comment by giggio** [comment]
More insight regarding startup delay: yes, it only applies after a reboot.

See closed issue: https://bitbucket.org/tildeslash/monit/issues/829/monit-startup-delay-on-boot
