### ISSUE TITLE
OpenVPN: Instances [new] - Setting Enforce local group causes auth failure

### ISSUE THREAD

**Issue by ack100** [opnsense/core#6732]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [ X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [ X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

Using OpenVPN: Instances [new]
When Setting a group in Enforce local group the client authentication fails.
With the group set to None it works correctly.

The new Instances stores the group ID number in the config but the code that checks group membership on client login uses the group name and does not check group ID so auth fails

**To Reproduce**

1. Go to 'OpenVPN: Instances'
2. Edit a server
3. Set a group in 'Enforce local group'
4. client authentication fails

**Expected behavior**

Client can connect if member of selected Enforce local group

**Describe alternatives you considered**

Tweaking `AuthGroupField.php` But that's a bad idea that will break something else.
change `self::$internalStaticOptionList[(string)$group->gid] = (string)$group->name;`
to `self::$internalStaticOptionList[(string)$group->name] = (string)$group->name;`

Alternative could be to change the functions used by `user_pass_verify.php` to support group ID or create a different script for  Instances to use. 

**Screenshots**

N/A

**Relevant log files**

Warning	openvpn	OpenVPN '3' requires the local group 2002. Denying authentication for user USERNAME

**Additional context**

N/A

**Environment**

OPNsense 23.7.1_3-amd64 (OpenSSL)

**Comment by AdSchellevis** [comment]
@ack100 https://github.com/opnsense/core/commit/8f51311423e2f5a3991eb1c3394391b03dfd8f50 should do the trick, thanks for reporting!
