### ISSUE TITLE
OpenVPN: Instances [new] - Redirect gateway not working

### ISSUE THREAD

**Issue by ack100** [opnsense/core#6733]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

In OpenVPN: Instances [new] when setting Redirect gateway to default no traffic is routed to the internet from the client.
Using the old Server config with redirect gateway works correctly.

The client using either server gets the same routes pushed and the server configs show the same push directives.

When using the old server config with gateway redirect enabled these 2 NAT rules are created.
`nat on em0 inet from [Tunnel Network]/24 to any port = isakmp -> (em0:0) static-port`
`nat on em0 inet from [Tunnel Network]/24 to any -> (em0:0) port 1024:65535`

Those rules do not exist when using Instances [new].

Manually creating those rules when using Instances [new] makes Redirect gateway work.

**To Reproduce**

1. Go to 'OpenVPN: Instances [new]'
2. Enable Redirect gateway default on a server
3. Attempt to access internet with client
4. Nothing loads from the internet

**Expected behavior**

All internet traffic from the client passes thru the firewall's gateway.

**Describe alternatives you considered**

Manually creating the 2 NAT rules
`nat on em0 inet from [Tunnel Network]/24 to any port = isakmp -> (em0:0) static-port`
`nat on em0 inet from [Tunnel Network]/24 to any -> (em0:0) port 1024:65535`

**Screenshots**

**Relevant log files**

`Notice	openvpn_server6	[Common Name]/[clients connection IP]:6403 MULTI: bad source address from client [client IP], packet dropped`

**Additional context**

**Environment**

OPNsense 23.7.1_3-amd64 (OpenSSL).

**Comment by fichtner** [comment]
Our rewrites like IPsec and OpenVPN in MVC try to avoid adding "general purpose" rules which can be useful, but not always desired.


Cheers,
Franco
