### ISSUE TITLE
PPPoE 'Baby Jumbos' - RFC 4638 - not applied on boot

### ISSUE THREAD

**Issue by iMiMx** [opnsense/core#6738]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

PPPoE 'Baby Jumbos' is not applied at boot, without editing the WAN/PPPoE interface and clicking 'Save'

My ISP requires a VLAN to be set for PPPoE, so I set:

- Physical, MTU 1512
- VLAN/WAN MTU 1508
- Which should then allow 1500 on the PPPoE interface

**To Reproduce**

- Physical interface, MTU 1512

![WAN_PHYS](https://github.com/opnsense/core/assets/17220013/93dc0feb-6e54-4e26-a21d-c5627eb85c9a)

```
em0: flags=8863<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1512
	description: WAN_PHYS (opt3)
	options=4802008<VLAN_MTU,WOL_MAGIC,NOMAP>
	ether xx:xx:xx:xx:xx:xx
	media: Ethernet autoselect (1000baseT <full-duplex>)
	status: active
	nd6 options=29<PERFORMNUD,IFDISABLED,AUTO_LINKLOCAL>
```

- WAN/VLAN interface, MTU 1508 (assigning this interface was not previously required, however another user on the forum reported that this fixed the issue for them)

![WAN_VLAN](https://github.com/opnsense/core/assets/17220013/6db94f16-5fe0-4c2c-81fd-2c25bfa87a43)

```
vlan01: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1508
	description: WAN_VLAN911 (opt4)
	options=4000000<NOMAP>
	ether yy:yy:yy:yy:yy:yy
	groups: vlan
	vlan: 911 vlanproto: 802.1q vlanpcp: 0 parent interface: em0
	media: Ethernet autoselect (1000baseT <full-duplex>)
	status: active
	nd6 options=29<PERFORMNUD,IFDISABLED,AUTO_LINKLOCAL>
```

- PPPoE interface at boot stil MTU 1492

```
pppoe0: flags=88d1<UP,POINTOPOINT,RUNNING,NOARP,SIMPLEX,MULTICAST> metric 0 mtu 1492
	description: WAN (wan)
	inet a.a.a.a --> gw.gw.gw.gw netmask 0xffffffff
	nd6 options=29<PERFORMNUD,IFDISABLED,AUTO_LINKLOCAL>
```

Even though the UI for the WAN/PPPoE interface shows 1508 and calculated 1500:

![WAN](https://github.com/opnsense/core/assets/17220013/4cb4cdff-cf3e-4ede-884e-1e0f4a21c5c1)

To fix: Edit the WAN interface, click Save, MTU is then set correctly:

```
pppoe0: flags=88d1<UP,POINTOPOINT,RUNNING,NOARP,SIMPLEX,MULTICAST> metric 0 mtu 1500
	description: WAN (wan)
	inet b.b.b.b --> gw.gw.gw.gw netmask 0xffffffff
	nd6 options=29<PERFORMNUD,IFDISABLED,AUTO_LINKLOCAL>	
```

**Expected behavior**

MTU of 1500 should be set on the PPPoE interface at boot - without requiring an 'Edit' and 'Save' of the WAN interface.

Previously the VLAN did not need to be assigned to an interface in the UI, another forum member mentioned that this seemed to fix the issue for them - however even after assigning the VLAN interface and rebooting, the PPPoE MTU came up at 1492.  

Previously (the below) setting the physical interface MTU to 1512, then setting 1508 on the WAN/PPPoE interface (showing 1500 calculated) was all that was required.

![WAN](https://github.com/opnsense/core/assets/17220013/98a265b9-3388-406f-92f5-49a49aba0dc6)

**Environment**

Software version used and hardware type if relevant, e.g.:

Versions	OPNsense 23.7.1_3-amd64
FreeBSD 13.2-RELEASE-p2
OpenSSL 1.1.1v 1 Aug 2023

**Comment by iMiMx** [comment]
Tagging forum posts:

https://forum.opnsense.org/index.php?topic=35282.0

https://forum.opnsense.org/index.php?topic=35350.0

**Comment by fichtner** [comment]
Sounds like something resetting it or a command being ignored. Not sure but FreeBSD 13.2 is the key difference here.


Cheers,
Franco

**Comment by iMiMx** [comment]
Is there any possibility this could be related to the 'no default route on PPPoE' issue?  Being reset/bounced by any of the gateway monitoring?

**Comment by pallebone** [comment]
I also have this issue but I was wondering if I can just add a script to resolve it? For example add script:
nano /usr/local/etc/rc.syshook.d/start/96-MTU
contains:
#!/bin/sh

ifconfig pppoe0 mtu 1500 up

Then after a reboot will the MTU be set as I want?

**Comment by fichtner** [comment]
These reports seem to pile up but lack of technical implementation make these difficult to follow. The thing I can see is that VLANs cannot set MTU because the parent is not updated, but as far as I can tell that was the case on 23.1.11 as well at least. Needs more investigation.

**Comment by fichtner** [comment]
This is fixed on the development version. I'm slipping in bits for 23.7.2, 23.7.3. The hardware MTU bit will be in 23.7.3/4 not sure which.
