### ISSUE TITLE
OpnSense Secure Shell does not Connect on reboot untill 'Save' is pressed on the configuration page.

### ISSUE THREAD

**Issue by gb-123-git** [opnsense/core#6739]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [ Yes ] I have read the contributing guide lines at  https://github.com/opnsense/src/blob/master/CONTRIBUTING.md
- [ Yes ] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/src/issues?q=is%3Aissue

**Describe the bug**

OpnSense Secure Shell does not connect on reboot untill 'Save' is pressed on the configuration page (System: Settings: Administration) after rebooting

**To Reproduce**

1. Reboot OpnSense Router

Workaround :
1. Go To > System: Settings: Administration
2. Click Save (Even without touching any settings)

**Expected behavior**

If Secure Shell is enabled, it should automatically connect on rebooting the router (power-off and power -on).

**Describe alternatives you considered**

Workaround :
1. Go To > System: Settings: Administration
2. Click Save (Even without touching any settings)

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 23.7.1 (amd64, OpenSSL).
AMD 5950X
Network Intel® I210-AT

**Comment by fichtner** [comment]
Set to listen to all interfaces (recommended). 😉

**Comment by gb-123-git** [comment]
@fichtner @AdSchellevis 

Well I am not talking about GUI which is set to All Interfaces.

I dont want the Secure Shell to be accessible with WAN. I have set it to be LAN + OPT1.
When I press Save with the same config, it works. After restart, it stops working till I press save again (without changing anything)
This is definitely a a bug and not something I missed because I tested this multiple times.

**Comment by fichtner** [comment]
No it is not.

https://docs.opnsense.org/manual/settingsmenu.html#listen-interfaces

**Comment by gb-123-git** [comment]
@fichtner 

Well guess its my bad. Sorry for bothering you guys.

However, I would like to point out that I am only trying LAN and its Static IP so both the conditions on the referenced document is met.

Thank you so much @fichtner !

**Comment by fichtner** [comment]
Not sure because the original report is incomplete. You may try to connect via host name resolved in IPv6 which LAN tracks from WAN (dynamic).


Cheers,
Franco
