### ISSUE TITLE
rc.newwanipv6 Monitors Link-Local Address Instead of GUA

### ISSUE THREAD

**Issue by aque** [opnsense/core#6740]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

`/usr/local/etc/rc.newwanipv6` is monitoring the link-local fe80::/10 address instead of GUA. I confirmed in an old system_*.log file that 23.1.11 logged the GUA, and the change happened after I upgraded to 23.7.

My WAN interface is set to use DHCPv6 with PD but no NA assignment. GUA is monitored if I switch the interface to use SLAAC instead.

The following is in my log:
`<13>1 2023-08-12T13:15:28-05:00 gw.net opnsense 7424 - [meta sequenceId="1774"] /usr/local/etc/rc.newwanipv6: No IP change detected (current: fe80::4262:31ff:fe14:9006%igb0, interface: WAN[wan])`

Output of `ifconfig`
```
root@gw:~ # ifconfig igb0
igb0: flags=8863<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500
	description: WAN (wan)
	options=4802028<VLAN_MTU,JUMBO_MTU,WOL_MAGIC,NOMAP>
	ether 40:62:31:14:90:06
	inet x.x.x.x netmask 0xfffffffc broadcast x.x.x.x
	inet6 fe80::4262:31ff:fe14:9006%igb0 prefixlen 64 scopeid 0x1
	inet6 2603:3018:xxxx:xxxx:4262:31ff:fe14:9006 prefixlen 64 autoconf
	media: Ethernet autoselect (1000baseT <full-duplex>)
	status: active
	nd6 options=23<PERFORMNUD,ACCEPT_RTADV,AUTO_LINKLOCAL>
```

**To Reproduce**

I have the following DHCPv6 client configuration in case it is relevant.
1. Configuration Mode: Advanced
2. Use IPv4 connectivity - UNCHECK
3. VLAN Priority - Disabled
4. Interface Statement
   * Information Only - UNCHECK
   * Send Options - “ia-pd 0”
5. Identity Association
   * Non-Temporary Address Allocation - UNCHECK
   * Prefix delegation - CHECK
   * idassoc pd id - 0
   * Prefix - 2603:3018:xxxx:xxxx::/59
   * Preferred Lifetime - infinity
6. Prefix Interface Site-Level Aggregation Length - 5

All other fields are empty.

**Expected behavior**

Monitor WAN GUA for changes as it may require updates to tracked interfaces and VIPs.

**Relevant log files**
Contents of the various `/tmp/igb*` files.

```
root@gw:~ # foreach f ( /tmp/igb* )
foreach? echo -n "$f -> "
foreach? cat $f
foreach? end

/tmp/igb0:slaac_nameserverv6 -> 2603:3018:xxxx:xxxx:fad2:acff:febf:695b
2001:558:feed::1
2001:558:feed::2
/tmp/igb0:slaac_routerv6 -> fe80::fad2:acff:febf:695b
/tmp/igb0_oldipv6 -> fe80::4262:31ff:fe14:9006%igb0
/tmp/igb0_prefixv6 -> 2603:3018:xxxx:xxxx::/59
/tmp/igb0_routerv6 -> fe80::fad2:acff:febf:695b
```

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 23.7.1_3-amd64
FreeBSD 13.2-RELEASE-p2
OpenSSL 1.1.1v 1 Aug 2023

**Comment by fichtner** [comment]
We learned that monitoring for an address in IPv6 is futile for a number of reasons. Today it uses “force” flag when a reloads is deemed necessary. Eventually it goes away but for now the symmetry with IPv4 is kept.


Cheers,
Franco

**Comment by aque** [comment]
Thanks @fichtner. I was not sure if this was an issue for my setup, and wanted to report it. You can close this at your convenience since this is a non-issue. I really appreciate your response.

**Comment by fichtner** [comment]
@aque ok, I looked at the scripts again but there is nothing to do here except a little log message cleanup for the time being. Appreciate the report :)
