### ISSUE TITLE
Fix RFC 5424 syslog message

### ISSUE THREAD

**Issue by a3ilson** [opnsense/core#6741]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**
Remote logging of OPNsense firewalls are problematic (annoying) when the message contains square brackets and quotes.

A clear and concise description of what the problem is including your motivation for the request,
i.e. "For the purpose of [...] I am missing a solution that will [...]."
RFC5424 output contains the following: - [meta sequenceId=\"726\"]

**Describe the solution you like**
Remove the square brackets, remove the equals sign, remove the slashes, remove the quotes

(e.g. I would like an input field in the `/ui/firewall/alias` which would add .... to ....)
Remove the square brackets, remove the equals sign, remove the slashes, remove the quotes

**Describe alternatives you considered**
no alternatives...

A clear and concise description of any alternative solutions or features you considered.
none

**Additional context**
If the meta sequence ID is absolute needed in the message consider remove special characters. Ideally, adding a suffix to the procid number would be preferred. 

Add any other context or screenshots about the feature request here or links to relevant forum thread or similar

**Comment by AdSchellevis** [comment]
Better fix the parser reading the stream, the brackets are part of RFC5424 (
https://datatracker.ietf.org/doc/html/rfc5424#section-6.5 https://datatracker.ietf.org/doc/html/rfc5424#section-7.3 ,  https://datatracker.ietf.org/doc/html/rfc5424#section-7.3.1)

**Comment by a3ilson** [comment]
:(
