### ISSUE TITLE
Virtual IP status filtering issue LAN IPv6 CARP VIP is missing

### ISSUE THREAD

**Issue by Lennie** [opnsense/core#6742]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug** / **To Reproduce**

I had created multiple IPv6 CARP VIPs under Virtual IP in Interfaces -> Virtual IPs -> Settings.

At least 1 on WAN and 1 on LAN (ULA)

When I go to Interfaces -> Virtual IPs -> Status

The 1 or more on the WAN side are shown when I have only CARP selected in the drop down.

But the one the LAN side is missing.

Might be related to #6543

**Describe alternatives you considered**

Also select IP Alias from the drop down and then we see it.

OPNsense 23.7.1-amd64

**Comment by AdSchellevis** [comment]
When the virtual ip type is alias, that's logical. The filter matches the type selected at the vip configured in `Interfaces: Virtual IPs: Settings`.

**Comment by Lennie** [comment]
The odd thing is, it's a CARP, it also creates a CARP on the interface if you check on the console.

As a test I added some IP-aliasses and things got more 'intriguing'.

![Screenshot from 2023-08-13 22-18-48](https://github.com/opnsense/core/assets/330102/f276d9aa-3d90-45f8-a352-8473c82959dd)

![Screenshot from 2023-08-13 22-19-18](https://github.com/opnsense/core/assets/330102/9051fc9f-1246-4c1d-9145-e8f5abc7906c)

As you can see it shows the CARP on the IP-alias selection and does NOT show the IP-aliasses.

**Comment by AdSchellevis** [comment]
IPv6 compressed format, it helps to be specific when opening tickets, this only happens when ifconfig's output doesn't equal the one provided in the vip (`::` vs `:0:`).
