### ISSUE TITLE
Monit: E-mail server password with special chars ! and " won't work 

### ISSUE THREAD

**Issue by TheNightmanX** [opnsense/core#6748]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**
Monit alert e-mail password with special chars ! (exclamation mark) and " (double quotes) won't work 

**To Reproduce**
1. Go to opnsense Web: Services - Monit - Settings
2. Click on page 'General Settings'
3. enter the data and an email server password containing a special characters ! (exclamation mark) and " (double quotes)
6. save and apply
7. service does not start
8. see error in monit log: Error monit  /usr/local/etc/monitrc:12: syntax error '!'

**Expected behavior**
Service should accept the email password with special characters ! and " to succesfully start the service

**Describe alternatives you considered**
none possible, I am not able to change the password of the email service account

**Screenshots**

**Relevant log files**

If applicable, information from log files supporting your claim.

**Additional context**

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 23.7.1_3-amd64
FreeBSD 13.2-RELEASE-p2
OpenSSL 1.1.1v 1 Aug 2023
Intel(R) Celeron(R) J4125 CPU @ 2.00GHz (4 cores, 4 threads)

**Comment by fbrendel** [comment]
Hi @TheNightmanX,
monit already accepts special characters except double quotes.

This is not an OPNsense limitation but from Monit.
See [THE MONIT CONTROL FILE](https://www.mmonit.com/monit/documentation/monit.html#THE-MONIT-CONTROL-FILE)  

> Strings can be either quoted or unquoted. A quoted string is bounded by **double quotes** ...

Escaping the double quote is also not possible.

**Comment by MAkcanca** [comment]
Here is the related part.
https://github.com/opnsense/core/blob/4d383db1d2a5f91eb3b5b8d521d58d731a269f92/src/opnsense/service/templates/OPNsense/Monit/monitrc#L57


If user inputs a password that contains `"` rc file will fail with syntax error '}'
We can't blame a 15 year old monitoring tool since they probably won't accept new MRs. https://github.com/arnaudsj/monit

But since OPNsense generates the rc file using jinja, we can add a small line like 
`{% set escaped_password = password|replace('\\', '\\\\')|replace('"', '\\"') %}`
and use escaped password instead.
I can create the MR if requested.

**Comment by fbrendel** [comment]
No, you can't escape double quotes. 
E.g.
`set mailserver 127.0.0.1 port 25 username test password "123\"456"`

```
# monit -t
/usr/local/etc/monitrc:12: syntax error '456'
```

**Comment by MAkcanca** [comment]
@fbrendel Actually true, I stand corrected. Monit uses yyparse lexical parser and they implemented a function to find first and last quote accordingly.

What about something like:
```
{% if '"' in OPNsense.monit.general.password %}
    {% set password = "password '" ~ OPNsense.monit.general.password ~ "'" %}
{% else %}
    {% set password = 'password "' ~ OPNsense.monit.general.password ~ '"' %}
{% endif %}
```
Or handle it somewhere else?
I saw that you tackled this problem years ago, and honestly if you think it's not worth the effort, that's quite alright. 
What's stopping us from validating on form submit?

**Comment by fbrendel** [comment]
@MAkcanca got it now!
Quotes in passwords are possible if you use single quotes for passwords with double quotes and vice versa.

`set mailserver 127.0.0.1 port 25 username test password '123"456'`
or
`set mailserver 127.0.0.1 port 25 username test password "123'456"`

 Thanks for pointing me to the right direction. :smiley:
