### ISSUE TITLE
DHCP - DynamicDNS - update-optimization

### ISSUE THREAD

**Issue by MisterBlueBear** [opnsense/core#6750]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**

The DHCP service is configured to send Dynamic DNS updates to an external BIND/named server. The configuration works initially as expected and the forward and reverse zones on the DNS server are updated with the correct information.

> 2023-07-26T04:30:54-04:00	Informational	dhcpd	Added new forward map from vanadium.xxx.xxx.xx to 10.2.73.23	 
> 2023-07-26T04:30:54-04:00	Informational	dhcpd	DHCPACK on 10.2.73.23 to xx:xx:xx:xx:xx:xx (vanadium) via lagg1_vlan6	 
> 2023-07-26T04:30:54-04:00	Informational	dhcpd	DHCPREQUEST for 10.2.73.23 (10.2.72.2) from xx:xx:xx:xx:xx:xx (vanadium) via lagg1_vlan6	 
> 2023-07-26T04:30:54-04:00	Informational	dhcpd	DHCPOFFER on 10.2.73.23 to xx:xx:xx:xx:xx:xx (vanadium) via lagg1_vlan6

At some point, the DNS entry gets removed from the DNS and even if the client is still correctly renewing its lease within the default time (every 2 hours), the DHCP server never attempts to send an update to the DNS server (i.e. Added new forward map ...) to have the mapping added once again.

> 2023-07-27T03:30:55-04:00	Informational	dhcpd	DHCPACK on 10.2.73.23 to xx:xx:xx:xx:xx:xx (vanadium) via lagg1_vlan6	
> 2023-07-27T03:30:55-04:00	Informational	dhcpd	DHCPREQUEST for 10.2.73.23 from xx:xx:xx:xx:xx:xx (vanadium) via lagg1_vlan6

By default, the "update-optimization" is set to true and will only attempt an update when it appears to be necessary (i.e. when the lease changes in some way).
In a case where the DNS and DHCP have inconsistencies, having this parameter set to true prevents the DHCP service from fixing the DNS errors or adding missing entries by sending an update to the DNS.
There doesn't seem to be any other way of performing such actions via the DHCP UI.

**Describe the solution you like**

Adding the "update-optimization" option as a configurable parameter in the DHCP UI would be a solution.

> update-optimization flag;
> 
> If the update-optimization parameter is false for a given client, the server will attempt a DNS update for that client each time the client renews its lease, rather than only attempting an update when it appears to be necessary. This will allow the DNS to heal from database inconsistencies more easily, but the cost is that the DHCP server must do many more DNS updates. We recommend leaving this option enabled, which is the default. If this parameter is not specified, or is true, the DHCP server will only update when the client information changes, the client gets a different lease, or the client’s lease expires.

**Describe alternatives you considered**

**Additional context**

**Comment by fichtner** [comment]
I'd encourage you to try the advanced config override https://docs.opnsense.org/manual/dhcp.html#advanced-settings as we are trying to keep a feature freeze over isc-dhcp due to it being EoL.

I don't mind changing defaults also, but only if it fixes a bug and doesn't have negative impact on everyone else.


Cheers,
Franco

**Comment by MisterBlueBear** [comment]
Since you have the "update-static-leases on;" by default in the code already (/usr/local/etc/inc/plugins.inc.d/dhcpd.inc) which sends an update to the DNS regarless if the client's static lease information has changed or not, I would assume that having the "update-optimization off;" too would make the update DNS behavior uniform between Static and Dynamic leases.

As for being a negative impact, this will definitely vary between environments as the impact (i.e. the number of times the DHCP service communicates with the DNS server) is based on the quantity of leases and the configured lease time. So I can't tell you how this will impact everyone else as everyone's configuration can be vastly different.

However, since you have a freeze, the https://docs.opnsense.org/manual/dhcp.html#advanced-settings workaround is acceptable.
And I can confirm this solution works for me.
