### ISSUE TITLE
OpenVPN: Instances [new] - unable to set /30 tunnel subnet

### ISSUE THREAD

**Issue by andrewhotlab** [opnsense/core#6753]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

Just upgraded to 23.7 branch, and trying to port OpenVPN peer-to-peer configuration to the MVC framework. But se server role does not allow to set a /30 subnet for the tunnel, logging this error:
```
Options error: --server directive when used with --dev tun must define a subnet of 255.255.255.248 (/29) or lower
```
OT: Moreover, from [this example](https://docs.opnsense.org/manual/how-tos/sslvpn_instance_s2s.html) in the manual, it looks like now is mandatory to setup a CA and create (and periodically renew!) a server certificate to authenticate both peers, while in the previous "peer-to-peer" mode it wasn't necessary at all... can I ask why?

**To Reproduce**

Try to configure a new server instance and put in the " Server (IPv4)" field something like "x.x.x.x/30"

**Environment**
||
|---|
|OPNsense 23.7.1_3-amd64|
|FreeBSD 13.2-RELEASE-p2|
|OpenSSL 1.1.1v  1 Aug 2023|

**Comment by AdSchellevis** [comment]
> OT: Moreover, from [this example](https://docs.opnsense.org/manual/how-tos/sslvpn_instance_s2s.html) in the manual, it looks like now is mandatory to setup a CA and create (and periodically renew!) a server certificate to authenticate both peers, while in the previous "peer-to-peer" mode it wasn't necessary at all... can I ask why?

The answer can be found in the upstream documentation, search for `--secret` in https://openvpn.net/community-resources/reference-manual-for-openvpn-2-6/ , which states:

> DEPRECATED Enable Static Key encryption mode (non-TLS). Use pre-shared secret file which was generated with --genkey. ....

The new instances module will not support deprecated options, when they still work and are available in the legacy configuration, you can keep using them there for now (we plan to support both options for quite some time).

**Comment by andrewhotlab** [comment]
Thank you for the clarification about deprecated options. Thus we'll prepare our brains to reconfig all p2p tunnels... :S

What about the usage of /30 subnet in tunnels?

**Comment by iqt4** [comment]
Sorry for jumping in. A comment regarding:
> DEPRECATED Enable Static Key encryption mode (non-TLS)

I understand that static key with TLS is not deprecated - only non-TLS a.k.a. "Shared Key". So it should still be possible to setup a client without client certificate (like in ProtonVPN). This is not the case in VPN: OpenVPN: Instances [new] yet.

**Comment by iqt4** [comment]
Thanks for pointing me to this page. My point is that in the Trust section of VPN: OpenVPN: Instances [new] for clients a certificate must be selected. This should be optional for the client. On the server side we have respective option --client-cert-not-required <none|optional|require>. The CA is of course mandatory.

**Comment by AdSchellevis** [comment]
Well, nothing “should”, but if you’re looking for a specific configuration that is currently not possible and not going to be deprecated, just open a ticket with relevant information included to request the missing feature.
