### ISSUE TITLE
IPV6 VTI Interfaces - Missing IPV6 address on interface

### ISSUE THREAD

**Issue by firestormo** [opnsense/core#6754]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

When creating new VTI interfaces with IPV6 Tunnel Local and Tunnel Remote Addresses, it does not apply the IPV6 address to the ipsec interface. When doing the same VTI config via Tunnel Settings [Legacy} it auto creates the VTI interface and adds the IPV6 address and mask to the interface correctly. 

This works fine for IPV4, only V6 doesn't get its inet6 addresses it only gets the tunnel inet6 address. See text output below. 

**To Reproduce**

1. Go to 'VPN'
2. Click on 'IPSEC'
3. Click on 'Virtual Tunnel Interfaces'
4. Create a new VTI with IPV6 addr for Local / Remote and Tunnel Local/Remote
5.On console run ifconifg to check interfaces

**Describe alternatives you considered**
Used Legacy Tunnel Settings for now, works fine

A clear and concise description of any alternative solutions or workaround you considered.

Via VPN > IPSEC > Virtual Tunnel Interfaces
Its missing the description and the inet6 addresses (desc not important, but IP is)

ipsec34: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> metric 0 mtu 1400
        tunnel inet6 2001:XXXX:XXXX::XXXX -->  2604:XXXX:XXXX:XXXX::X
        groups: ipsec
        reqid: 34
        nd6 options=29<PERFORMNUD,IFDISABLED,AUTO_LINKLOCAL>

Via Legacy Tunnel Settings
ipsec1: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> metric 0 mtu 1400
        description: (ipsec1)
        tunnel inet6 2001:XXXX:XXXX::XXXX --> 2604:XXXX:XXXX:XXXX::X
        inet6 fe80::3eec:efff:feda:db32%ipsec1 prefixlen 64 scopeid 0x10
        inet6 fd93:XXXX:XXXX::1 prefixlen 126
        groups: ipsec
        reqid: 1
        nd6 options=21<PERFORMNUD,AUTO_LINKLOCAL>

**Environment**

Software version used and hardware type if relevant, e.g.:
OPNsense 23.7.1_3-amd64
FreeBSD 13.2-RELEASE-p2
Intel(R) Xeon(R) D-1718T CPU @ 2.60GHz (4 cores, 8 threads)
Network Intel® I210-AT

**Comment by firestormo** [comment]
@AdSchellevis I realize it says IFDISABLED, but its not, and I have the same req id set for the phase 2 as well.

**Comment by firestormo** [comment]
<ipsec34>
      <internal_dynamic>1</internal_dynamic>
      <enable>1</enable>
      <descr>TESTLAS</descr>
      <if>ipsec34</if>
      <type>none</type>
    </ipsec34>

**Comment by AdSchellevis** [comment]
https://github.com/opnsense/core/issues/6777
