### ISSUE TITLE
DHCP: add "allow unknown-clients" option

### ISSUE THREAD

**Issue by Bomorav** [opnsense/core#6755]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**

I'm facing the same problem as described in this older forum post
https://forum.opnsense.org/index.php?topic=26081.msg125837#msg125837

Opnsense DHCP does not allow setting the "allow unknown-clients" option in pool declaration. This option is necessary for proper functioning if we want to separate known and unknown clients into different IP ranges as described in dhcpd.conf man page in section "Address Pools" (https://linux.die.net/man/5/dhcpd.conf)

Adding this option inside the pool by using advanced settings .conf file is not possible.

**Describe the solution you like**

I think it might not be necessary to add this option to the gui. It would be enough to set this option as the default for the pool if the option "deny unknown-clients" is not checked.

Something like this
```
--- dhcpd.inc.bak       2023-08-15 10:38:13.899592000 +0200
+++ dhcpd.inc   2023-08-15 10:39:16.130877000 +0200
@@ -840,6 +840,8 @@

             if (isset($poolconf['denyunknown'])) {
                 $dhcpdconf .= "    deny unknown-clients;\n";
+            } else {
+                $dhcpdconf .= "    allow unknown-clients;\n";
             }

             if (isset($poolconf['ignoreuids'])) {
```

**Comment by fichtner** [comment]
Shouldn't isc-dhcp default to this if omitted? oO

**Comment by Bomorav** [comment]
Dynamic address assignment to unknown clients works by default and there is no need to specify the option except the case of assigning different parameters for known and unknown clients.
 
This is only an idea of simple solution which is working for me.

A cleaner solution would be to add an option to the gui, but that would probably require more work.

**Comment by AdSchellevis** [comment]
https://kb.isc.org/docs/isc-dhcp-41-manual-pages-dhcpdconf

> The unknown-clients flag is used to tell dhcpd whether or not to dynamically assign addresses to unknown clients. Dynamic address assignment to unknown clients is allowed by default. An unknown client is simply a client that has no host declaration.

> The use of this option is now deprecated. If you are trying to restrict access on your network to known clients, you should use deny unknown-clients; inside of your address pool, as described under the heading ALLOW AND DENY WITHIN POOL DECLARATIONS.

**Comment by Bomorav** [comment]
So any other advice how to achieve this in opnsense?

https://kb.isc.org/docs/isc-dhcp-41-manual-pages-dhcpdconf

> ADDRESS POOLS

> The pool declaration can be used to specify a pool of addresses that will be treated differently than another pool of addresses, even on the same network segment or subnet. For example, you may want to provide a large set of addresses that can be assigned to DHCP clients that are registered to your DHCP server, while providing a smaller set of addresses, possibly with short lease times, that are available for unknown clients. If you have a firewall, you may be able to arrange for addresses from one pool to be allowed access to the Internet, while addresses in another pool are not, thus encouraging users to register their DHCP clients. To do this, you would set up a pair of pool declarations:

```

subnet 10.0.0.0 netmask 255.255.255.0 {
option routers 10.0.0.254;

# Unknown clients get this pool.
pool {
option domain-name-servers bogus.example.com;
max-lease-time 300;
range 10.0.0.200 10.0.0.253;
allow unknown-clients;
}

# Known clients get this pool.
pool {
option domain-name-servers ns1.example.com, ns2.example.com;
max-lease-time 28800;
range 10.0.0.5 10.0.0.199;
deny unknown-clients;
}
}
```
If "allow unknown-clients" option is missing, then the behavior is as follows:
1. We connect an unknown client - it gets an IP address from pool range for unknown clients - correct
2. We add a static MAC mapping for this client so now it becomes a known client
3. We renew the IP address on the client
4. The client still gets an IP address from the first pool for unknown clients - wrong

If the first pool for unknown clients contains "allow unknown-clients" then in step 4
4. The client gets an IP address from the second pool for known clients - correct

**Comment by fichtner** [comment]
Well, "renew" is not really a "bind" since it asks for the previous address...

But does this work if you flush the lease after adding the static mapping?

I'm only trying to locate the bug / look for possible alternatives.


Cheers,
Franco

**Comment by Bomorav** [comment]
I tried several different cases after adding the static mapping using windows 10 client.

A. default - without "allow unknown-clients" in the first pool
1. ipconfig /release + ipconfig /renew - client gets the same IP address from uknown clients pool
2. ipconfig /release + disconnect and reconnect network cable - client gets the same IP address from uknown clients pool
3. ipconfig /release + disconnect cable + wait longer than lease time + reconnect cable - client gets the same IP address from uknown clients pool
4. ipconfig /release + delete the lease on dhcpd + ipconfig /renew - client gets the same IP address from uknown clients pool
5. ipconfig /release + delete the lease on dhcpd + disconnect and reconnect network cable - **client gets the IP address from known clients pool**

So the only working alternative without "allow unknown-clients" option is to delete the lease from the leases and force client to ask for a new address and not "renew".

B. "allow unknown-clients" in the first pool
The client gets the IP address from known clients pool in all cases regardless of what address it had before and whether it is renew or new request.

Option B is more comfortable, just add a static mapping and the client will get a new IP address when renewing or reconnecting.
