### ISSUE TITLE
Routes not being created with the new OpenVPN server instance

### ISSUE THREAD

**Issue by kuya1284** [opnsense/core#6757]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

**OPNsense 23.7** introduced the new **Instances** improvement with **OpenVPN**; however, it appears that after migrating the configuration from the old **Servers** section to the **Instances** section, the routes aren't getting initialized properly with a [site-to-site](https://docs.opnsense.org/manual/how-tos/sslvpn_instance_s2s.html) setup. The handshake and connection between two sites does get established, but the routes don't get added at all.

I may be missing something and it's possible that this may be caused by a misconfiguration; however, everything does seem to be in order.

The following steps assume that an existing [site-to-site](https://docs.opnsense.org/manual/how-tos/sslvpn_instance_s2s.html) setup already exists and describe the process for migrating to the new **Instances** section. This also assumes that the `Client Settings > Topology` setting is **checked** with the old setup.

**To Reproduce**

1. In a browser tab, which we'll refer to as **Tab 1**, go to `VPN > OpenVPN > Connection Status > Sessions` and confirm that a connection has been established
2. Go to `VPN > OpenVPN > Connection Status > Routes` and take note of the routes that currently exist
3. Go to `VPN > OpenVPN > Servers` and click the **Edit** button for the server that's going to be migrated
4. Copy the contents of the **TLS Shared Key** field in the **Cryptographic Settings** section
5. In a new browser tab, which we'll refer to as **Tab 2**, go to `VPN > OpenVPN > Instances [new] > Static Keys`
6. Click the **Add** button
7. Paste the **shared key** into the **Static Key** field, set the **Mode** to `auth`, fill in the **Description** field, then click **Save**
8. While still on **Tab 2**, go to `VPN > OpenVPN > Instances [new] > Instances`
9. Click the **Add** button
10. Fill in the following fields, copying the information from **Tab 1** to **Tab 2** using the following mapping, leaving anything not mentioned at their defaults:

| Old Field (Tab 1) | New Field (Tab 2) | Notes |
| --- | --- | --- |
| General Information > Description | General Settings > Description | |
| General Information > Local Port | General Settings > Port Number | |
| Tunnel Settings > IPv4 Tunnel Network | General Settings > Server (IPv4) | |
| Cryptographic Settings > Server Certificate | Trust > Certificate | |
| Cryptographic Settings > Certificate Depth | Trust > Certificate Depth | |
|  | Trust > TLS static key | Set to the static key that was added at **Step 4** above |
|  | Authentication > Authentication | Click **Clear All** |
| Tunnel Settings > IPv4 Local Network | Routing > Local Network | Copy and paste the comma-delimited list; each item will automatically render as individual tokens |
| Tunnel Settings > IPv4 Remote Network | Routing > Remote Network | Same note as above |

11. Close **Tab 1**, then click **Save** on **Tab 2**
12. Go to `VPN > OpenVPN > Servers` and **disable** the old server
13. At the other site, disconnect then reconnect the client
14. Back at the server, go to `VPN > OpenVPN > Connection Status > Sessions` and confirm a successful connection
15. Go to `VPN > OpenVPN > Connection Status > Routes` and confirm that the list doesn't match what was seen in **Step 2** above

**Expected behavior**

A connection must be established between the two sites with the appropriate routes being added to the routing table. Without the routes, it won't be possible to communicate from one site to the other.

**Describe alternatives you considered**

_N/A_

**Screenshots**

**OLD SETUP > SESSIONS**
![image](https://github.com/opnsense/core/assets/121985/687614f0-5562-4b18-85e7-38102c53d2d1)

**OLD SETUP > ROUTES**
![image](https://github.com/opnsense/core/assets/121985/0c86c9e6-4a2f-4f9c-80f4-9f4d8ea37694)

**NEW SETUP > SESSIONS**
![image](https://github.com/opnsense/core/assets/121985/525e75c0-d8fd-46bc-a5f9-d9ca5d570336)

**NEW SETUP > ROUTES**
![image](https://github.com/opnsense/core/assets/121985/d39275c4-7eea-4168-83a9-2f01785908ef)

**OPENVPN LOG**
![image](https://github.com/opnsense/core/assets/121985/fdacc56f-4b56-4a6b-b3f6-84835b0c1a71)

**Relevant log files**

See **OPENVPN LOG** screenshot above.

**Additional context**

I've also tried manually adding each route one by one instead of using the copy-and-paste approach, but that made no difference. I wanted to see if maybe there was some white-space or the comma somehow saving on the back-end since what's seen on the front-end doesn't always necessarily reflect what's actually saved on the back-end.

I also tried deleting the old server and establishing a connection after, but end up with the same results.

I left the **Client Specific Overrides** as-is and **enabled**, which appeared to be needed still.

![image](https://github.com/opnsense/core/assets/121985/bd58a41f-46d9-41d6-9266-1862aabe3f62)

**Environment**

OPNsense 23.7.1_3 (amd64, OpenSSL).
Intel Celeron J4125 2.00GHz Quad Core

**Comment by AdSchellevis** [comment]
best compare the contents of the generated instances configuration and the one generate by the legacy module, both are being written to `/var/etc/openvpn/`

**Comment by kuya1284** [comment]
@AdSchellevis, will do. Thanks for the tip. That lead helps. I'll perform a diff and report back.

**Comment by AdSchellevis** [comment]
Most of these are changes for valid reasons (https://openvpn.net/community-resources/reference-manual-for-openvpn-2-6/), please stick to the problem in question, the aim of instances isn't to deliver the exact same config, but if you do miss something, checking under the hood might help identify the related difference.

**Comment by kuya1284** [comment]
I get that the changes are necessary; however, don't you find it odd that when attempting to have the client connect while having the new **Instance** version _enabled_ and the old **Server** version _disabled_, the **Server** config is what gets processed? Well, that's what it seems like. 

I am trying to stick to the problem in question. There just seems to be some type of conflict or overlap between the two configs (or the processing of thereof) that could be contributing to the problem in question.

I'd tried to do my own troubleshooting earlier in attempt to help out with this potential bug, but I kept running into a brick wall with "socket bind" failures, which forced me to have to reboot OPNsense a few times. Regardless, I've pointed out discrepancies with the old config and the new config. Two keys that seem to stand out and that are missing from the new config are `tls-server` and `ifconfig`. When reading the document you linked to, it appears that the topology that should be used with my setup should be **p2p** instead of **subnet**. That doesn't seem to make a difference, nor doesn't change the topology to **p2p** cause the `ifconfig` key to show up in the config.

So have I checked under the hood? Yes, I've tried to no avail. I couldn't even find documentation or a migration guide anywhere to help transition to the new **Instance** setup. If there is one written up, I'd appreciate a link to that.

**Comment by AdSchellevis** [comment]
> I get that the changes are necessary; however, don't you find it odd that when attempting to have the client connect while having the new Instance version enabled and the old Server version disabled, the Server config is what gets processed? Well, that's what it seems like.

I don't think that's possible as they both use a different execution path, but `ps -afx` will show you what's running.

> I am trying to stick to the problem in question. There just seems to be some type of conflict or overlap between the two configs (or the processing of thereof) that could be contributing to the problem in question.

Maybe trying to bind to the same port, after which one fails, but hard to assess from here.

> I'd tried to do my own troubleshooting earlier in attempt to help out with this potential bug, but I kept running into a brick wall with "socket bind" failures, which forced me to have to reboot OPNsense a few times. 

hmm, sounds like the problem I've just described. My advice would be to bind both servers to a different port so in theory you could start both at the same time.

> Regardless, I've pointed out discrepancies with the old config and the new config. Two keys that seem to stand out and that are missing from the new config are tls-server and ifconfig. When reading the document you linked to, it appears that the topology that should be used with my setup should be p2p instead of subnet. That doesn't seem to make a difference, nor doesn't change the topology to p2p cause the ifconfig key to show up in the config.

Debugging specific setups doesn't fit community support scope, if there is a clear pointer of a setting that is missing which could be related to any issue you might have, I don't mind having a quick look.

> So have I checked under the hood? Yes, I've tried to no avail. I couldn't even find documentation or a migration guide anywhere to help transition to the new Instance setup. If there is one written up, I'd appreciate a link to that.

The examples we offer are available for both (https://docs.opnsense.org/manual/vpnet.html#id3), other (special) uses cases are way easier to investigate in term of migration by reading the config file from the old file and checking the options in the new as these match the upstream documentation (https://openvpn.net/community-resources/reference-manual-for-openvpn-2-6/).

Our goal with the new instances module is to lean as close as we can towards the terminology used by the application in question (openvpn), the same we done in 23.1 for IPsec by the way. Upstream documentation is often better in explain all options that are available. It is likely that some scenario's that were supported earlier, are not possible to configure now, in which case if it's a safe to use option (according to upstream documentation), we will likely aim for inclusion at some point.

> EDIT: I'm just trying to provide as much details as possible. Most people who report bugs generally don't do that because they aren't developers or testers. I know how things go and know that it's often better to over communicate than to under communicate. I was trying to provide as much information as possible that I thought was relevant to help troubleshoot the "problem in question".

This is always difficult, you're really trying to be thorough on your reports, which is a good thing, but is also quite a read and if one would try to reproduce your issue quite time consuming. I'm merely trying to skim through the highlights to identify what would be needed to explain any differences. Please remember I'm spending my limited free time here.

**Comment by kuya1284** [comment]
I figured out the problem. The issue had to do with the **Client Specific Override**. The **Servers** dropdown doesn't list the servers created in **Instances**, only in **Servers**:

![image](https://github.com/opnsense/core/assets/121985/2191d71a-0ff3-49d7-98bb-0d62f575fe6e)

Per the docs, I should be able to select the **Instance** server:

![image](https://github.com/opnsense/core/assets/121985/2c990239-e20d-4f73-9504-7fdda1131389)

However, I just learned that I could have nothing selected at all. So once I realized that selecting nothing would cause the overrides to apply to all servers, I figured I'd give that a try.

Sure enough, my routes got built as expected.

So the bug in this case wasn't the configurations all along. The issue has to do with the **CSO** not allowing users to select the server created from the **Instances** screen.

I'm going to leave the **Servers** option empty since I'm only planning on running one server. However, this bug could impact others who are running multiple OpenVPN servers and require CSO on a per-server basis.

**Comment by kuya1284** [comment]
Also, if you prefer I create a separate issue specific to the **CSO** screen, I can do that and close this one to keep the issue more targeted and focused. Just let me know how you'd like me to proceed.

**Comment by AdSchellevis** [comment]
It's fine to close this one, @fichtner already fixed the issue you found last week https://github.com/opnsense/core/commit/ee4496702d0dd2ec312d45d459f16d90cf4ba2d4 https://github.com/opnsense/core/commit/42e06c5daf1689fe6ff9e91fdb6511d138989507 , it should be in the next release.

**Comment by kuya1284** [comment]
Thanks, @AdSchellevis. Closing...
