### ISSUE TITLE
Hostsname on Aliases not updated

### ISSUE THREAD

**Issue by newtoptan** [opnsense/core#6762]
hello
i have a problem
Hostsname on Aliases not updated

OPNsense 23.7.1_3-amd64
FreeBSD 13.2-RELEASE-p2
OpenSSL 1.1.1v 1 Aug 2023

![Screenshot 2023-08-20 223155](https://github.com/opnsense/core/assets/21101279/e5f130ea-9097-4f21-b0be-202ecec4496b)
![Screenshot 2023-08-20 222821](https://github.com/opnsense/core/assets/21101279/b408b27c-56a4-4559-9175-55db2d74ee3e)
![Screenshot 2023-08-20 222935](https://github.com/opnsense/core/assets/21101279/6e664b36-a149-4cf9-be1e-a6d3c1d58e6f)

**Comment by Axsgranted** [comment]
You're using the wrong format for host types.  You'd need an IP address, not a domain name.

**Comment by newtoptan** [comment]
https://docs.opnsense.org/manual/aliases.html#hosts

You try to see this
