### ISSUE TITLE
Running plugins on routing_configure

### ISSUE THREAD

**Issue by ashceryth** [opnsense/core#6763]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**

It would be great to run scripts every time the default route changes. This would be handy to send notifications or update configurations.

**Describe the solution you like**

Currently it is possible to create configure plugins to catch some events as described here: https://docs.opnsense.org/development/backend/legacy.html#configure. For example, I created a plugin to run a script on `newwanip` events which updates some configurations. Similarily, I would like to create a plugin to run a script on `routing_configure` events. Alternatively, a syshook for this would be even better!

This is related to [5956](https://github.com/opnsense/core/issues/5956), which is already a bit dated. The issue came up again because it seems the `monitoring` syshook isn't triggered anymore, when the gateway switches back to the primary WAN interface. At least my script isn't triggered anymore.

**Describe alternatives you considered**

For testing, I adapted the rc.routing_configure file to run my script and it works as desired.

**Additional context**

None

**Comment by AdSchellevis** [comment]
Maybe in the long run it makes sense to offer structured registration mechanism to add static routes in `get_staticroutes()` so services can request what they need, another event currently doesn't look very useful. I don't think we made intentional changes to the `monitoring` syshook facility, the event seems to be where it should be: 

https://github.com/opnsense/core/blob/7f1d8c66d3a5c0f8ee34c82b7319e76ea5c0ebc4/src/opnsense/scripts/routes/gateway_watcher.php#L105

**Comment by fichtner** [comment]
The down->none transition might be fixed in 23.7.2 so that monitor facility works again as expected. The gateway monitors are already some sort of extension of the routing reconfiguration. I don't mind making them pluggable in the long run, but for now I agree with @AdSchellevis in trying to keep the system as is.

Perhaps that would be a good opportunity to remove the monitor script if we can hook directly into the actual handler (rc.routing_configure) which is now more reliable and less noisy as opposed to the monitor facility (it will trigger spuriously to emulate the previous behaviour).


Cheers,
Franco

**Comment by fichtner** [comment]
> Are you referring to the changes in https://github.com/opnsense/core/commit/d1d255a24d4824ab5e3e97e49fa51a888431df4d? I already applied the patch.

So it's not working? Did you reboot? The patch is not effective otherwise.


Cheers,
Franco

**Comment by ashceryth** [comment]
No, I did not reboot. My bad. I will try it later today, Thanks!

**Comment by ashceryth** [comment]
@fichtner Did a reboot yesterday and checked the behavior. The default route switches back perfectly fine. However, it seems the monitor syshook is not triggered, when this happens. So, is this expected behaviour or am I missing something?

Thanks!

**Comment by fichtner** [comment]
@ashceryth It looks ok from here... can you grep for the log message? Example below

```
# opnsense-log gateways | grep ALERT
ALERT: WAN_DHCP (Addr: 8.8.8.8 Alarm: down -> none RTT: 15.1 ms RTTd: 3.6 ms Loss: 0.0 %)
```

**Comment by ashceryth** [comment]
I can see the alerts in the log. I also enabled some logging in my script and it runs on the alerts. The issue seems to be, that the alerts are sent before the default default route has been changed (I guess via rc.routing_configure). So, I guess the command in my script `route -n show default | grep interface | awk '{print $2}'` still shows the backup WAN interface at this point. 

Could it be the old behaviour generated a lot more alerts and one of the alerts was sent after the route has already been changed?

**Comment by fichtner** [comment]
> Could it be the old behaviour generated a lot more alerts and one of the alerts was sent after the route has already been changed?

Yes and no. The alert was triggered at 10-dpinger,if you have scripts before it it shows the pre-switch and if you have scripts behind it (like 20-log) shown here it would have seen the post-switch most likely. But it's certainly true that it would trigger a lot more in the past.

Perhaps we can switch the order. Let me see.

**Comment by ashceryth** [comment]
My hook is named 50-myscript, so it's behind 10-dpinger. 

Wouldn't it be possible to also trigger the monitor syshook on rc.routing_configure? Or do you consider this as undesired?

**Comment by fichtner** [comment]
We can move it. But it loses the ability to send the monitoring data which this was written for... It's giving me too much of a headache to bend this. I'l inclined to say that reading the new gateway from the monitoring facility was a fortunate side effect before, but it's not feasible to emulate it now without making a step backwards.

**Comment by fichtner** [comment]
Actually I think what you are looking for is the monitor plugin facility...

https://github.com/opnsense/core/blob/6487512a8ed72d6f8edce2c5206a6934cde98416/src/etc/inc/system.inc#L724

... but it is being disabled for the monitoring invoke to not loop the alert handling.

**Comment by fichtner** [comment]
FWIW, you could run `configctl interface routes alarm` from your script and it reverts back to the old behaviour. Maybe that is acceptable to you.

**Comment by ashceryth** [comment]
Thanks for the clarification and I do fully understand the implications you brought up.

> FWIW, you could run `configctl interface routes alarm` from your script and it reverts back to the old behaviour.

Do you mean I have to run it everytime? May I ask you for a short description what the command does?

**Comment by fichtner** [comment]
That's exactly what 10-dpinger did until 23.1.11. For 23.7 I moved it to the watcher script which is why what you see is happening.

**Comment by fichtner** [comment]
For reference:

https://github.com/opnsense/core/blob/da466781965bdb89470f81b70280021d920fdcbd/src/etc/rc.syshook.d/monitor/10-dpinger#L38

(I moved the necessary locking to the configd action too)

**Comment by ashceryth** [comment]
Including `configctl interface routes alarm` im my hook file before running the script actually did the trick! Working as expected now!

Many thanks!

**Comment by fichtner** [comment]
@ashceryth happy to hear. shall we close this? I expect more substantial improvements here in the future but likely not before 24.1 is out and we definitely do have this on my wish list anyway.

**Comment by ashceryth** [comment]
Sure! Thank you very much for the support!
