### ISSUE TITLE
Aliases column width to small for buttons, resulting it to '...'

### ISSUE THREAD

**Issue by arnocs** [opnsense/core#6769]
**Important notices**
- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at 

**Describe the bug**

In [ Firewall - Aliases ] the collumn 'Commands' is too small,
resulting the last button (delete) to be replaced by [...].

**To Reproduce**

1. Go to [OPNsense] > [Firewall] > [Aliases]
2. Have some aliases in the list.
3. Look at column 'Commands', the last button on the richt. (see attachment)

**Expected behavior**

To see a button with a 'bin-icon' instead of '...'

**Describe alternatives you considered**

none

**Screenshots**
![Screenshot 2023-08-23 at 10 41 36](https://github.com/opnsense/core/assets/10909218/439e43c0-785d-40e3-94e5-12360420d781)

**Relevant log files** 

n/a

**Additional context**

Changing the <thead><th style...>  title-row column width from "width:7em;" to "width:8em;" for 'commands' resolves the issue.

**Environment**

OPNsense-Business (DEC750) 23.4.2-amd64 (OpenSSL 1.1.1v 1 Aug 2023)
It is a long standing at least from OPNsense-Business version 23.4.1

Desktop system MacOS ventura 13.5.1 (22G90)
Used browsers Safari, Firefox, Chrome

**Comment by AdSchellevis** [comment]
Doesn't seem to be doing that on my end, let's see if more people have the same issue and if there's a pattern to detect

**Comment by arnocs** [comment]
Ah forgot to add * Using theme 'rebellion'
_might be theme-name related, lol_

Tested with default theme 'opnsense' and other themes 'cicada', 'tukan', 'vicuna', do not have the issue.

**Comment by AdSchellevis** [comment]
then I think it would be better to open a ticket in plugins for that theme as it's likely better handled there.

**Comment by arnocs** [comment]
Done, [opnsense-plugins #3559](https://github.com/opnsense/plugins/issues/3559)
