### ISSUE TITLE
[FR] Search engine in the GUI

### ISSUE THREAD

**Issue by oparoz** [opnsense/core#677]
I'm really missing a search bar in the GUI, kind of like the one in KDE or Windows settings. It makes it so much easier to quickly find what we're looking for.
In those systems, the results are dynamic. In KDE, the top level menu items are coloured while the rest is greyed out. In Windows, you get the "pages" directly as results.

**Comment by fichtner** [comment]
first version as quick navigation feature implemented as previously advertised in the roadmap :)
