### ISSUE TITLE
OpenVPN Instances: Peer Certificate Authority

### ISSUE THREAD

**Issue by rac-HH** [opnsense/core#6771]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

Using external certificate management may result in different CAs for server and client certificates. The old "Servers" configuration has an option "Peer Certificate Authority" to explicitly select the client CA.
The [forum](https://forum.opnsense.org/index.php?topic=35225.msg170817#msg170817) mentions that it is derived form the server certificate, which prevents migration of some existing rollouts.

**To Reproduce**

1. Create Instance with same parameters as existing server
2. Take server down, start instance
3. Connect with existing client configuration
4. See error:  VERIFY ERROR: depth=0, error=unable to get local issuer certificate: CN=XXXX

**Expected behavior**

The migrated instance should accept the clients as the server before.

**Environment**

OPNsense 23.7.1_3-amd64

**Comment by pfoo** [comment]
Similar option has disappeared with new ipsec connection UI.

Legacy IPSec ui allowed to select/enforce the remote certification authority to check when validating remote certs in pubkey authentication. This was materialized by `rightca=<issuer dn>` in ipsec.conf.
In swanctl.conf it is now `connections.<conn>.remote<suffix>.cacerts=<ca certificates>` (certificate should be placed in cacerts directory), but for now the new ipsec UI don't allows to define it.

Same reasoning as discussed in #6709 can apply, is it worth a separate issue ?

**Comment by AdSchellevis** [comment]
@pfoo just open a new ticket, by default it should allow all configured CA's, but if you want to constraint, a selection might be possible.

https://github.com/opnsense/core/blob/27e723a00ed8e89c55d060c4be72ecf88780061b/src/etc/inc/plugins.inc.d/ipsec.inc#L1110-L1131
