### ISSUE TITLE
Firewall: Rules: Group Pulldown has gotten merged into the Automatically generated Rules Pull down.

### ISSUE THREAD

**Issue by IsaacFL** [opnsense/core#6772]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

See
https://forum.opnsense.org/index.php?topic=35389.0

The Group Rules Pull Down, that used to display when viewing a Group member interface has been broken, I think after 23.7.
**To Reproduce**

Create a group. Add interfaces to the Group. Add rules to the group. 
Then go to one of the member interface rules, and instead of the Group Rules having its own pull down, it is combined into the Automatically Generated Rules.

If there are too many combined, the pull down doesn't even work.

Also if you look at the Group rules, you will see the Group rules there also under the automatically generated rules pull-down.

If you look at the actual website source being generated, it looks like the header section for the group rules pull down is a copy/paste of the Auto generated pull-down, which seems to try to combine them.

**Screenshots**

I attached a screenshot of the Group Rules with Pull Open. You can see that the group rules are also being displayed in the Auto Pull down. Hence the magnifying glass icon on the right.

**Relevant log files**

NA

**Additional context**

NA

Software version used and hardware type if relevant, e.g.:

I am currently on:
OPNsense 23.7.2-amd64
FreeBSD 13.2-RELEASE-p2
OpenSSL 1.1.1v 1 Aug 2023

But I saw it after 23.7

<img width="1898" alt="Firewall-Rules-Group Screenshot 2023-08-23 080002" src="https://github.com/opnsense/core/assets/9387311/045b1efa-d41f-49a3-8998-f0f8b43f5d57">

**Comment by IsaacFL** [comment]
I have attached the Console log. I don't see anything there.
[console-export-2023-8-23_8-55-0.txt](https://github.com/opnsense/core/files/12421138/console-export-2023-8-23_8-55-0.txt)

**Comment by IsaacFL** [comment]
Here is the actual source file for the LAN interface rules.  You will see starting at line 2639:

`<tr id="expand-internal-rules" class="expand_type is_collapsed" data-type="internal" style="display: none;">
                        <td><i class="fa fa-folder-o text-muted"></i></td>
                        <td></td>
                        <td class="view-info" colspan="2"> </td>
                        <td class="view-info hidden-xs hidden-sm" colspan="5"> </td>
                        <td colspan="2" class="view-stats hidden-xs hidden-sm"></td>
                        <td colspan="2" class="view-stats"></td>
                        <td class="view-info"></td>
                        <td>Automatically generated rules</td>
                        <td>
                            <button class="btn btn-default btn-xs" id="expand-internal">
                              <i class="fa fa-chevron-circle-down" aria-hidden="true"></i>
                              <span class="badge">
                                <span id="internal-rule-count"><span>
                              </span>
                            </button>
                        </td>
                    </tr>`

This is where the pulldown for the group rules starts, but you can see it is an exact copy of the Autogenerated rules section. The browser refuses to open the pull down in this case since it is 45 rules after being combined.




[firewall_rules-if-lan.txt](https://github.com/opnsense/core/files/12421189/firewall_rules-if-lan.txt)

**Comment by IsaacFL** [comment]
Here is a screenshot of the LAN interface, which is a member of the group.  The pulldown (45) will not even open, and the group pulldown doesn't even show at all.

I will note, as part of my debug, I reinstall 23.7 using my config.xml and even reformatted the drive.  After the 23.7 updated it had the same problem.

<img width="1327" alt="Firewall-Rules-LAN Screenshot 2023-08-23 080002" src="https://github.com/opnsense/core/assets/9387311/75b0abe4-dad0-4ce4-a93d-a26e6f32721a">

**Comment by IsaacFL** [comment]
I have a firewall group called IGLOCAL.  Here is the source code for the IGLOCAL Rules. You can see that it actually duplicates the rules from the same interface twice.  Once for the group itself and then another copy in the auto gen pull down group.
[firewall_rules-if-IGLOCAL.txt](https://github.com/opnsense/core/files/12422504/firewall_rules-if-IGLOCAL.txt)

**Comment by AdSchellevis** [comment]
Which interfaces are in `IGLOCAL` ? your html code doesn't show a group heading, which does seem to suggest it "thinks" the rule is not part of the group

**Comment by IsaacFL** [comment]
IGLOCAL is all of my local LANs.  For me that is 10LAN,30WIFI,40SRV,20WKS,50IOT,60GST,70UBI.

10LAN is an em0 interface, the others are vlans on top of an ix1 interface if it makes a difference.

**Comment by AdSchellevis** [comment]
@IsaacFL it took some time, but found the culprit. this https://github.com/opnsense/core/commit/1dbcf112e6b5a1cf9bba928e3aff0483aba478fd should fix it. Thanks for reporting!

**Comment by IsaacFL** [comment]
It was the new sequence #s on the groups.  Funny, how little changes.

**Comment by AdSchellevis** [comment]
yep, totally overlooked that one.
