### ISSUE TITLE
Config Import RRD data handling

### ISSUE THREAD

**Issue by Daggolin** [opnsense/core#6774]
# Config Import RRD data handling

**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

When importing a config that has been exported with `Do not backup RRD data.` unchecked the rrddata part of the export does not get stripped on import unless `Exclude console settings from import.` is checked.

**What happened**

In preparation for the update to 23.7 on our main instance we recently updated a test instance of OPNsense from 23.1.10 to 23.7.1_3 (see https://github.com/opnsense/core/issues/6728 for details; unrelated to the current issue). With the release of 23.7.2 the blockers we encountered before seemed to have been resolved and we decided to update the test instance, export the lastest config from the production environment (still on the latest 23.1 release due to the previous blockers) and import the config on the test instance. Right after a successful import the config history (`System > Configuration > History`) showed that our config supposedly grew from around 600 KB to around 10 MB and the diff showed that an `rrddata` block was now considered part of the config. Comparing the Health graphs (`Reporting > Health`) on both systems indicated that the data was correctly imported. As everything seemed to be working, except for the supposedly grown config, we exported the config of test system (23.7.2) once without RRD data and once with it to see the results. The export without RRD data still contained the `rrddata` block from the old export and the export with RRD contained two `rrddata` blocks (the old and a new one). As a workaround we removed the `rrddata` block from the new export that should not have contained any block to begin with and imported the modified config. This brought our config size back down to its original value. Exporting without RRD data gave us a clean config file, exporting with RRD data gave us a config file with RRD data. Importing the new export with RRD data (this time exported from 23.7.2) brought the config size to 10 MB again and the issue resurfaced. Importing an export with two `rrddata` blocks resulted in a 20 MB config and repeating the process added almost 10 MB each time, because another `rrddata` block got added to the config.

Looking at the source of `src/www/diag_backup.php` we quickly found the code at fault:
https://github.com/opnsense/core/blob/587a50cb7c8c04af71f36ccc74a1464383916607/src/www/diag_backup.php#L258-L267
 
If `rrddata` is set on a full restore the if in line 259 evaluates as true: the rdd data gets imported (line 261) and the `rrddata` is removed from the config (262).  As a consequence of this the first part of the if in line 264 can never be true, because it‘s the same condition as line 259, which means the `rrddata` has already been stripped from the config (line 262). This means the check to determine if the config has to be written to file effectively only checks if `keepconsole` is part of the POST parameters.

Based on the code we tried importing our config with `Exclude console settings from import.` checked. With this checkbox active the import properly writes the config without `rrddata` to disk, no matter how many `rrddata` blocks the used config contains.

I don’t know if this matches your preferred style, but this is the diff of a fix I tested on our system:
```diff
diff --git a/src/www/diag_backup.php b/src/www/diag_backup.php
index 8f67583f6..21442ac91 100644
--- a/src/www/diag_backup.php
+++ b/src/www/diag_backup.php
@@ -245,7 +245,9 @@ if ($_SERVER['REQUEST_METHOD'] === 'GET') {
                         $do_reboot = true;
                     }
                     $config = parse_config();
-                    if (!empty($pconfig['keepconsole'])) {
+                    $keepconsole = !empty($pconfig['keepconsole']);
+                    $got_rrddata = !empty($config['rrddata']);
+                    if ($keepconsole) {
                         // restore existing console settings
                         foreach ($csettings as $fieldname => $fieldcontent) {
                             if ($fieldcontent === null && isset($config[$fieldname])) {
@@ -256,12 +258,12 @@ if ($_SERVER['REQUEST_METHOD'] === 'GET') {
                         }
                     }
                     /* extract out rrd items, unset from $config when done */
-                    if (!empty($config['rrddata'])) {
+                    if ($got_rrddata) {
                         /* XXX we should point to the data... */
                         rrd_import();
                         unset($config['rrddata']);
                     }
-                    if (!empty($config['rrddata']) || !empty($pconfig['keepconsole'])){
+                    if ($got_rrddata || $keepconsole){
                         write_config();
                         convert_config();
                     }
```

**Expected behavior**

We expected the system would strip the `rrddata` block from the config when importing it, just like old versions of OPNsense used to.

**To Reproduce**

Steps to reproduce:
 1. Go to `System > Configuration > Backups`
 2. Uncheck `Do not backup RRD data.`
 3. Click on `Download configuration`
 4. Choose the just downloaded file as input for the restore option
 5. Uncheck `Exclude console settings from import.`
 6. Click on `Restore configuration`

Optionally you can also uncheck `Reboot after a successful restore.` when restoring the config.

**Describe alternatives you considered**

Importing with `Exclude console settings from import.` checked to avoid the issue, but that defeats the purpose of a restore on identical hardware.

**Environment**

Versions:
 - OPNsense 23.7.2-amd64
 - FreeBSD 13.2-RELEASE-p2
 - OpenSSL 1.1.1v 1 Aug 2023

CPU type:
 - Intel(R) Xeon(R) CPU D-1518 @ 2.20GHz (4 cores, 8 threads)

**Comment by AdSchellevis** [comment]
@Daggolin https://github.com/opnsense/core/commit/318be6ab60e7fc50c3a75ae7de37047d415d8ba3 should fix the issue. thanks for reporting.
