### ISSUE TITLE
DHCP: '+' button on lease table not working

### ISSUE THREAD

**Issue by OscaAlb** [opnsense/core#6779]
**Description of the bug**

With the latest update to OPNsense 23.7.2, when in Services -> DHCPv4 -> Leases and hitting the '+' button on the lease table to add a new static mapping for a specific MAC address OPNsense just goes back to the Lobby -> Dashboard without opening the section with the DHCP static mappings.

**To Reproduce**

1. Go to 'Services -> DHCPv4 -> Leases'
2. Click on '+' for any lease to add a static mapping for a MAC address

**Expected behavior**

I expect the menu for adding a static mapping to open. (Services -> DHCPv4 -> [yournetwork] -> static DHCP mapping)

**Describe alternatives you considered**

Navigating manually to Services -> DHCPv4 -> [yournetwork] -> static DHCP mapping works.

**Screenshots**

None

**Relevant log files**

None

**Additional context**

None

**Environment**

OPNsense 23.7.2-amd64
FreeBSD 13.2-RELEASE-p2
OpenSSL 1.1.1v 1 Aug 2023
AMD EPYC 3201 8-Core Processor

**Comment by fichtner** [comment]
https://github.com/opnsense/core/commit/6b909723

**Comment by mietzen** [comment]
@fichtner thanks for the quick fix, I saw you added this fix to 24.1. Is there a workaround for the meantime? I'm new to OPNsense, can I edit the leases via terminal?

**Comment by fichtner** [comment]
You can install this on top of 23.7.2 with the following console command:

    # opnsense-patch 6b909723

And it will be shipped in 23.7.3 tomorrow.
