### ISSUE TITLE
Cannot create PPTP interface

### ISSUE THREAD

**Issue by oparoz** [opnsense/core#678]
### Env

15.7.99

### Steps to reproduce

1. create p2p device, assign to *WAN*
1. create interface in *Assignements*
1. edit interface -> enable

### Expected result

A new interface using  pptp0

### Actual result

* The device is deleted
* In *Assignements*, the interface is assigned to re0
* In *Overview* the interface is shown as `interface (opt2, wan)`

### Logs

```
Jan 18 14:34:20	opnsense: /status_interfaces.php: The command `/usr/local/sbin/ifinfo 'wan'' failed to execute
Jan 18 14:34:08	opnsense: /interfaces.php: Creating rrd update script
Jan 18 14:34:08	inetd[30656]: 19000/tcp: unknown service
Jan 18 14:34:08	configd.py: [34ef9f24-4740-47fb-ab68-8d8b84a6150b] Reloading filter
Jan 18 14:34:06	opnsense: /interfaces.php: The command '/usr/sbin/arp -d -i 'wan' -a > /dev/null 2>&1' returned exit code '1', the output was ''
Jan 18 14:34:06	opnsense: /interfaces.php: The command '/sbin/ifconfig 'wan' -staticarp' returned exit code '1', the output was 'ifconfig: interface wan does not exist'
Jan 18 14:34:05	configd.py: [97f234fd-6bb3-4839-bcc6-2e18bbe520a2] updating dyndns opt2
Jan 18 14:34:00	opnsense: /interfaces.php: The command '/sbin/ifconfig 'wan' inet6 -accept_rtadv' returned exit code '1', the output was 'ifconfig: interface wan does not exist'
```

**Comment by oparoz** [comment]
I've added more details to the OP. Maybe I'm selecting the wrong interface when configuring the device, but for an OpenVPN client per example, I do select *WAN*. If that's the problem, then maybe only add the physical interfaces (re1) in the dialogue?

**Comment by AdSchellevis** [comment]
It looks like p2p interface assignment from the interface section does function, but when assigned using the "interface assignment" it should copy some properties to the interface to glue all together which it doesn't do. 
The next commit will fix the assignment issue, if the issue remains feel free to reopen it again.
