### ISSUE TITLE
DHCPv4 - Hostname and vendor indentifier does not replicate to failover peer.

### ISSUE THREAD

**Issue by Blip9575** [opnsense/core#6782]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

When two instances are configured as failover peers, DHCP information is replicated from primary peer to failover peer without the client's hostname and vendor information.

With DHCP leases registered in Unbound, the dns records for DHCP clients are inconsistent between the firewalls and client lookups fail on the failover peer.

**To Reproduce**

DHCP lease information is displayed on peer which responded to client's DHCP request. (https://fw/ui/dhcpv4/leases)
![image](https://github.com/opnsense/core/assets/2066320/f62752c6-35db-44d5-bff6-9870e9958fd1)

Database located in '/var/dhcpd/var/db/dhcpd.leases' contains information displayed within web GUI.
`lease 192.168.0.54 {`
`  starts 6 2023/08/26 14:19:56;`
`  ends 6 2023/08/26 15:19:56;`
`  tstp 6 2023/08/26 15:49:56;`
`  tsfp 6 2023/08/26 15:49:56;`
`  atsfp 6 2023/08/26 15:49:56;`
`  cltt 6 2023/08/26 14:19:56;`
`  binding state active;`
`  next binding state expired;`
`  hardware ethernet 4a:b1:0f:a8:43:c0;`
`  uid "\001J\261\017\250C\300";`
`  set vendor-class-identifier = "android-dhcp-13";`
`  client-hostname "OnePlus-7T";`
`}`

On the failover peer, the clients lease is visibile without the client's hostname and vender identifier.
![image](https://github.com/opnsense/core/assets/2066320/58a2f1bf-c267-4de7-a3d2-12107d443bb2)

Database located in '/var/dhcpd/var/db/dhcpd.leases' is also missing the clients hostname and vendor identifier.
`lease 192.168.0.54 {`
`  starts 6 2023/08/26 14:19:56;`
`  ends 6 2023/08/26 15:19:56;`
`  tsfp 6 2023/08/26 15:49:56;`
`  atsfp 6 2023/08/26 15:49:56;`
`  binding state active;`
`  next binding state expired;`
`  hardware ethernet 4a:b1:0f:a8:43:c0;`
`  uid "\001J\261\017\250C\300";`
`}`

**Expected behavior**

Expected to see complete client lease information on both peers to maintain consistent DNS records on both firewalls.

**Relevant log files**

Logs on primary peer responded to DHCP request and allocated client an address from the DHCP scope. (https://fw/ui/diagnostics/log/core/dhcpd)
![image](https://github.com/opnsense/core/assets/2066320/32584a74-ae45-46cf-92ae-317ebbb815d8)

Logs on failover peer confirms lease owned by primary peer.
![image](https://github.com/opnsense/core/assets/2066320/ad7c9687-0c04-4964-bbea-b9639d0fefbb)

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 23.7.2-amd64
FreeBSD 13.2-RELEASE-p2
OpenSSL 1.1.1v 1 Aug 2023

**Comment by Blip9575** [comment]
@AdSchellevis If this is a bug within DHCPD, may I ask why Opnsense still uses isc-dhcp44-server (4.4.3P1) which was marked as 'end of life' in October 2022 and the plans to upgrade to Kea DHCP server?

https://www.isc.org/blogs/isc-dhcp-eol/

**Comment by fichtner** [comment]
'If your headlight is broken why haven't you bought a new car' is what comes to mind. EoL is nice, but we can't replace a car just because the vendor decided to not sell it anymore.

**Comment by Blip9575** [comment]
> 'If your headlight is broken why haven't you bought a new car' is what comes to mind. EoL is nice, but we can't replace a car just because the vendor decided to not sell it anymore.

As stated in the opening post in great detail, I have identified a bug within DHCP which maybe related to an unresolved bug in DHCPD which now EOL.

Therefore, my question has merit and constructive feedback would be appreciated.

**Comment by fichtner** [comment]
Feel free to propose a patch to dhcpd. I'm happy to review and integrate. So the EoL argument doesn't apply.

We are planning to migrate, but are still in the early design phase. It could 1-2 years easily to have a replacement ready with the limited resources and funding that we have.

Is that better?

**Comment by Blip9575** [comment]
> Feel free to propose a patch to dhcpd. I'm happy to review and integrate. So the EoL argument doesn't apply.

This is not possible since the code is no longer being maintained.

https://www.isc.org/blogs/isc-dhcp-eol/

The 4.4.3-P1 and 4.1-ESV-R16-P2 versions of ISC DHCP, released on October 5, 2022, are the last maintenance versions of this software that ISC plans to publish. If we become aware of a significant security vulnerability, we might make an exception to this, but it is **our intention to cease actively maintaining this codebase**.
 
> We are planning to migrate, but are still in the early design phase. It could 1-2 years easily to have a replacement ready with the limited resources and funding that we have.

Thank you, shame this information wasn't included in the initial response.

> Is that better?

Concidering the feedback and Reddit attitude, my clients will no longer purchase Opnsense appliances and will begin migrating to pfSense.

**Comment by fichtner** [comment]
> This is not possible since the code is no longer being maintained.

The code does not magically appear in OPNsense...

> Concidering the feedback and Reddit attitude

Maybe you should make a survey over on Reddit about community satisfaction. I think you're just being pushy and want something we cannot give you mid-term.

**Comment by Blip9575** [comment]
Code for DHCPD is EOL and not maintained by OpnSense.

Will migrate to pfSense.

**Comment by AdSchellevis** [comment]
The reason why this is, is also explained here 
https://serverfault.com/questions/842621/isc-dhcp-server-doesnt-share-hostnames-with-failover-peer , it's a limitation of how a peer is implemented (a reservation, not a two way sync). 

Just for reference in case you are considering opening an issue "elsewhere" for the same https://docs.netgate.com/pfsense/en/latest/troubleshooting/ha-dhcp-failover.html#inconsistent-client-hostnames

And our previous ticket for the same https://github.com/opnsense/core/issues/5029 .
