### ISSUE TITLE
DHCP - Opnsense Ver. 23.7.2 - unable to add a static mapping for a MAC address from the "Leases" menu. 

### ISSUE THREAD

**Issue by phlo2009** [opnsense/core#6783]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [ ] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [ ] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

A clear and concise description of what the bug is, including last known working version (if any).

*Tip*: to validate your setup was working with the previous version, use opnsense-revert (https://docs.opnsense.org/manual/opnsense_tools.html#opnsense-revert)

**To Reproduce**

1. Go to 'services -> DHCPv4 -> Leases'
2. Click on '.+' to add a ststic mapping of a specific mac address. Error: It jumps to the wrong page, the dashboard.

**Expected behavior**

**Describe alternatives you considered**

A clear and concise description of any alternative solutions or workaround you considered.

**Screenshots**

**Relevant log files**

If applicable, information from log files supporting your claim.

**Additional context**

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 23.7.2 (amd64, OpenSSL).
KVM64 Quad Core
Network Linux VirtIO

**Comment by AdSchellevis** [comment]
duplicate https://github.com/opnsense/core/issues/6780
