### ISSUE TITLE
OpenVPN Instance : Client Specific Overrides not applied

### ISSUE THREAD

**Issue by pfoo** [opnsense/core#6784]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

On OPNsense 23.7.2 Client Specific Overrides are not applied with an OpenVPN (new) instance (no mention to CSC in log, and /var/etc/openvpn-csc/3/ stays empty) despite checking the instance in the CSO  "Servers" field.

After applying commit d3af50a and manually creating directory /var/etc/openvpn-csc/961988-0461-4-8933-779744/ CSO are now created in /var/etc/openvpn-csc/961988-0461-4-8933-779744/ but instance configuration file still mention `client-config-dir /var/etc/openvpn-csc/3` instead of `/var/etc/openvpn-csc/961988-0461-4-8933-779744/`

Followup forum thread : https://forum.opnsense.org/index.php?topic=35447.0

**To Reproduce**

Steps to reproduce the behavior: Try to use CSO in 23.7.2 with or without patch d3af50a

**Environment**

OPNsense 23.7.2 + patch d3af50a

**Comment by AdSchellevis** [comment]
In my attempt to server both new (mvc) id's and legacy id's (which are used for the device naming), I missed a spot it seems. Can you try https://github.com/opnsense/core/commit/78d49d85fea6141191e8382496b44766fe262480 on top? It should preserve the usual numbering in the `/var/etc/openvpn-csc/` path.

**Comment by pfoo** [comment]
It is working for both d3af50a and 78d49d8 ! Thanks !

**Comment by AdSchellevis** [comment]
@pfoo thanks for confirming, we'll aim to include this in our next minor release.
