### ISSUE TITLE
OpenVPN Instance - does not register Network Interfaces in Unbound settings

### ISSUE THREAD

**Issue by TimmiORG** [opnsense/core#6787]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

The new OpenVPN Instance does not register a Network Interface in the general Unbound settings.
Currently you need to configure to listen on all interfaces to get DNS working on the new OpenVPN Instances

**To Reproduce**

1. Create OpenVPN instance
2. Go to General Settings of Unbound
3. OpenVPN instance is not visible in the Network Interface list (OpenVPN server (old) are visible.

**Expected behavior**

OpenVPN Instance is to be expected to be selectable on the Network Interface List in the Unbound setting.

**Describe alternatives you considered**

Workaround would be that Unbound is listing on all interfaces (selected none)

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 23.7.2

**Comment by AdSchellevis** [comment]
Only assigned ones (Interfaces: Assignments) end up there, but for stability reasons we wouldn't advise to bind to specific interfaces anyway. For compatibility reasons we added the old OpenVPN's as well, but given this is usually a bad idea anyway, I don't expect we will add hooks like that for new components.

https://github.com/opnsense/core/blob/78d49d85fea6141191e8382496b44766fe262480/src/opnsense/mvc/app/models/OPNsense/Unbound/FieldTypes/UnboundInterfaceField.php#L54-L61

**Comment by TimmiORG** [comment]
Hi @AdSchellevis 
thank you for the feedback and clarification.

Best regards
Christoph
