### ISSUE TITLE
[RFE] Move services "overview" page

### ISSUE THREAD

**Issue by fraenki** [opnsense/core#679]
Currently the "overview" page to control all services can be found under `System->Diagnostics->Services`.

Personally, I find this somewhat odd and it took me some time to find this page when I first required to manually control a service. I was expecting to find this page under `Services`.

I'm suggesting to move this page to `Services->Diagnostics` for 16.1, because this would align well with other pages like Firewall and Interfaces. They have their own Diagnostics space, but oddly Services does not.

**Comment by AdSchellevis** [comment]
Agreed, let's move it.
