### ISSUE TITLE
Unbound doesn't resolve static ip mappings

### ISSUE THREAD

**Issue by markus-seidl** [opnsense/core#6796]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

There are static ip mappings configured for DHCP, but they do not resolve via unbound even with the appropriate settings turned on.

**To Reproduce**

1. Add a static IP mapping
2. Set the domain in the System:General Setup
3. Set "Register DHCP Leases" and "Register DHCP Static Mappings" in Unbound
4. Domain does not resolve

**Expected behavior**

Domain should resolve

**Describe alternatives you considered**

I have tried:

```
root@opnsense:~ # cat /var/unbound/dhcpleases.conf
local-data-ptr: "192.168.20.40 XXX"
local-data: "XXX IN A 192.168.20.40"
local-data-ptr: "192.168.20.41 ZZZ"
local-data: "ZZZ IN A 192.168.20.41"
// all dynamic leases showing, but NO static at all.
```

**Screenshots**

**Relevant log files**

**Additional context**

I do believe this is new with the 23.7 branch.

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 23.7.2-amd64
FreeBSD 13.2-RELEASE-p2
OpenSSL 1.1.1v 1 Aug 2023
Intel(R) Celeron(R) J4125 CPU @ 2.00GHz (4 cores, 4 threads)

**Comment by AdSchellevis** [comment]
checking wrong file?

https://github.com/opnsense/core/blob/f782be9cbf39ea99c9770458a78f2ece2d5031d7/src/etc/inc/plugins.inc.d/unbound.inc#L546-L567

**Comment by markus-seidl** [comment]
True, the other file (host_entries.conf) contains the entries.

I will monitor this further, currently it does resolve after various restarts.

**Comment by markus-seidl** [comment]
It seems to be fixed with restarts.
