### ISSUE TITLE
web interface also listens on all VIP ip added!

### ISSUE THREAD

**Issue by sjorge** [opnsense/core#68]
It should only listen on the LAN IP, or if there are multiple LAN's on all the LAN IP's.

**Comment by sjorge** [comment]
Same for SSHd so probably many more daemons too.

**Comment by sjorge** [comment]
OK, so for every VIP added the sshd, web interface,... listens on that also.
Personally inclined to mark this as a security issue, since you could unsuspected end up service exposure you were not planning on.

**Comment by StopTrain** [comment]
I personally don't see an issue with this since the default for the firewall is to block anything from the outside coming in, unless of course you explicitly open those ports/rules/etc.

**Comment by sjorge** [comment]
I was using a default config (no rules added), I added a VIP x.x.x.123 in my LAN interface range. To use this to redirect some traffic to a different server. Without doing anything else than adding the VIP, ssh, web interface,... is now available on x.x.x.123 on the LAN interface.

No rules were added,

**Comment by StopTrain** [comment]
Correct, that makes sense. Is the VIP on your LAN or part of a subnet on your LAN etc?

to me, the default for not allowing access from the OUTSIDE world is fine, but you need access from the internal networks etc by default or you risk locking yourself out.

**Comment by sjorge** [comment]
I just checked, the default rule does indeed seem to allow 'any' lan traffic to the entire lan range.
So it does match with traffic hitting the VIP, still think It's a bug that web interface listens on all VIP's added to the LAN interface though.

**Comment by StopTrain** [comment]
If it's part of the LAN subnet, it would make sense.  I'm sure they'll look into it though!

**Comment by jschellevis** [comment]
As far as I know this is intended to work this way. You can change the default by disabling the anti-lockout rule and add rules manually.

**Comment by StopTrain** [comment]
Yeah, that's what my next suggestion was.  Beat me to it!

**Comment by jschellevis** [comment]
:-)

**Comment by sjorge** [comment]
But that still does not fix the problem of all the daemons also binding their ports on the VIPs also.

**Comment by jschellevis** [comment]
But that is mandatory as the system uses the interface name.. not the ip address assignment as it can't know what ip it should listen to. If you disable the anti-lockout rule you can block traffic reaching the gui or other services by blocking all traffic and allowing only the ones with the correct destination ip.
Be sure that you add an alow rule first or you won't be able to reach the gui anymore..
