### ISSUE TITLE
Display/table error on DHCPv6 leases page

### ISSUE THREAD

**Issue by syserr0r** [opnsense/core#680]
MAC address on DHCPv6 leases page is faulty/incorrect, see image below:

![Display/table error](http://i.imgur.com/L7bdbPd.png)

**Comment by fichtner** [comment]
Lease pages are going to be refactored by @AdSchellevis

**Comment by AdSchellevis** [comment]
@syserr0r I saw this too when refactoring this page, all should work now. In case you still experience the issue feel free to reopen.

Related commits: https://github.com/opnsense/core/commit/b9f53deea2a4c7a54d5e8641e60e179515e2db94
https://github.com/opnsense/core/commit/e81728ba672e84e71ebae9ce0c1366c34f7cc3ca
https://github.com/opnsense/core/commit/835a66bde7af99a2ef6c40a5564626a0223d91a3
https://github.com/opnsense/core/commit/525a4ed7fc1ee1be5c903d9162da005a83859a9e
