### ISSUE TITLE
OpenVPN - route-gateway CSO option

### ISSUE THREAD

**Issue by smeretech** [opnsense/core#6801]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [ ] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**

In an OpenVPN Topology (subnet) configuration I set the Tunnel network to be a class B.
Within the CSO section I subsequently created individual directives for each common name that connects by assigning them smaller subnets and dedicated IP so as to divide the different users into groups and consequently creating special firewall rules.
Within the same CSO I set the directive "**route-gateway <gateway>**" in the Advanced section to assign an IP from that subnet as gateway.
Everything works correctly with OPNSense version 23.1.x but in the new version 23.7 I can't find how to speficate this directive in the CSO section.

**Describe the solution you like**

Being that the lack of the Advanced section where the route-gateway directive can be set also impacts a Legacy OpenVPN instance, we request the possibility to have a dedicated section in the CSO page to reconfigure this option.

**Describe alternatives you considered**

no alternative identified

**Comment by smeretech** [comment]
ok. since this is my first time reporting/requesting, should I put a comment on 6703 and close this one?

**Comment by fichtner** [comment]
Yes, sounds like a plan.

**Comment by smeretech** [comment]
ok thanks
