### ISSUE TITLE
Adding DHCP opt interface removes upstream gateway on static WAN interface

### ISSUE THREAD

**Issue by andreas-p** [opnsense/core#681]
On a system with 3 static-ip interfaces, I added a fourth DHCP interface. as soon as changes are applied, WAN connectivity is disrupted (LAN seems ok). Rules still seem ok (pfctl -s rules), the new interface gets all DHCP data. I tried ifconfig up/down and pfctl -d on the wan interface, but it didn't restore connectivity until I rebooted the firewall.
Version: 15.7.25

**Comment by andreas-p** [comment]
A further check shows that the default gateway via the wan interface is lost. As soon as I re-add it manually connectivity is restored.

**Comment by syserr0r** [comment]
I'm having a similar problem, except the default gateway is OK for some unspecified amount of time after an (initial/re-)boot.

My set-up is as follows:
![Current set-up](http://i.imgur.com/wtD3R8r.png)
Note that the DHCP gateway is **disabled**

When external connectivity fails, checking the System > Routes > Status shows the default gateway is missing. I suspect when the DHCP client renews it clobbers the default route.

I presume this is the same problem? If not I'll make a separate issue.

**Comment by syserr0r** [comment]
I've added two static routes (as setting a static route with a network mask of /0 isn't allowed) of
`0.0.0.0/1` and `128.0.0.0/1`, both with WANGW as the default gateway, which seems to have worked around the issue for now until this is fixed.

**Comment by fichtner** [comment]
timeout

**Comment by syserr0r** [comment]
Is this actually fixed as I used a workaround (and we still are using it)?

**Comment by fichtner** [comment]
@syserr0r different, can we start fresh from the current code state? the reported version was 15.7.25
