### ISSUE TITLE
Let us select the interface in "Interfaces: Diagnostics: DNS Lookup"

### ISSUE THREAD

**Issue by vpx23** [opnsense/core#6810]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

Please let us select the interface in a dropdown list in "Interfaces: Diagnostics: DNS Lookup" from which the request is sent.

Why?

Because it makes a difference over which line you make a DNS request.

For example you can only ping or resolve "tel.t-online.de" from a Telekom line.

This would also be useful for the ping and traceroute tools.

OPNsense version: OPNsense 23.4.2-amd64

**Comment by AdSchellevis** [comment]
ping and traceroute support a source address, interface isn't distinct enough. If I'm not mistaken the `host` command doesn't support a source address, which is probably why we left it out here. 

https://github.com/opnsense/core/blob/5121b8a6d458fa728c5d83f71e0b1e0802ac2b84/src/opnsense/scripts/dns/query_dns.py#L48
