### ISSUE TITLE
PPPoE Connection Issues

### ISSUE THREAD

**Issue by mejas** [opnsense/core#6811]
**Important notices**

Our forum is located at https://forum.opnsense.org , please consider joining discussions there in stead of using GitHub for these matters.

Before you ask a new question, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

I'm currently having issues with a PPPoE connection in 23.7.2 and above (last working version was 23.7.1, the initial release). I've verified that the connection works when using the following:

- MacOS
- Windows
- OpenWRT
- ISP default config

For some reason, only OPN has trouble with the connection handshake. I've done a packet capture of the interface and have noticed that the ISP does give a PADO but the firewall seems to not recognize it at all. Said capture has been attached [here (in zip)](https://github.com/opnsense/core/files/12488422/34671261-6e5f-4fa5-a1c2-ce85e6c9bfac.zip) for your perusal.

Additional details:

- No change was made to config when upgrading from 23.7.1
- An attempt to downgrade from 23.7.2 went awry and I had to reinstall latest: PPPoE config still does not work from scratch
- Majority of the log shows `PPPoE connection timeout after 9 seconds`
- Tested with 23.7.3 and the issue still persists

**Comment by klinkeye** [comment]
I am starting to see issues since upgrading to 23.7.x - unfortunately I have little to back up my claim as far as logs and details. I'm monitoring the situation a little closer from this point forward and will hopefully add some value to this discussion soon.

**Comment by mejas** [comment]
Thanks for responding @klinkeye. Just to ask: did your PPPoE setup also work on an older version? It might be interesting if you can also capture the PPPoE handshake log to see if we're having the same issue.

**Comment by brandonsturgeon** [comment]
I've been having extremely flaky PPPoE connections since 22.7 (yes, 22.7) - I upgraded to 23.1 and still saw flakiness.

This could be an issue with my specific setup or even an ISP issue - how can I gather useful logs/details to see if my problem is related?

**Comment by brandonsturgeon** [comment]
I believe my issue was ISP related. It started after a day of ISP maintenance and magically resolved itself a couple of weeks later.
