### ISSUE TITLE
No RFC5424 format for Syslog-TLS targets with "rfc5424" enabled

### ISSUE THREAD

**Issue by cs-1** [opnsense/core#6813]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

When using a logging target with Syslog-TLS (TCP/6514) and enable RFC5424 messages, no RFC5424 formatting (incl. timestamps with timezone etc.) is used.

**To Reproduce**

1. Go to 'System: Settings: Logging / targets'
2. Add new target.
3. Enable 'TLS(4)' transport.
4. Configure hostname and port 6514.
5. Enable 'rfc5424' option.
6. Save the target.
7. Apply new configuration.
8. Produce log messages that are logged to remote target.

**Expected behavior**

All messages are RFC5424 formatted:

```
<29>1 2023-09-01T11:27:23+02:00 xxxxxxxxxxx openvpn_server1 85466 - [meta sequenceId="28"] xxxx/x.x.x.x:33774 SIGUSR1[soft,remote-exit] received, client-instance restarting
```

Instead, legacy syslog formatting is used:

```
<29>Sep  1 09:14:05 xxxxxxxxx openvpn_server1[85466]: xxxx/x.x.x.x:54238 MULTI_sva: pool returned IPv4=x.x.x.x, IPv6=x:x::x
```

**Describe alternatives you considered**

I used UDP transport over UDP/514 and enabled the 'rfc5424' option. In this scenarios everything works as expected and RFC5424 formatting is used.

**Relevant log files**

N/A

**Additional context**

N/A

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 23.7.3-amd64
FreeBSD 13.2-RELEASE-p2
OpenSSL 1.1.1v 1 Aug 2023

**Comment by cs-1** [comment]
Quick note: there seems to be an easy fix for the problem:

Adding `flags(syslog-protocol)` to the `destination xxxxx { }` section in `/usr/local/etc/syslog-ng.conf.d/syslog-ng-destinations.conf` resolves the issue (tested by manually adding the option and doing a `kill -HUP ...` with the syslog-ng process id).

**Comment by einhirn** [comment]
This jinja template should do the job: https://github.com/opnsense/core/blob/0ab708fb72248761336178b1ba280501b1513888/src/opnsense/service/templates/OPNsense/Syslog/syslog-ng-destinations.conf#L31-L32
but somehow it obviously didn't in this case.

**Comment by AdSchellevis** [comment]
forgot to apply the change? The model, form and template look normal rfc5424 and on my end it saves the following content when set into `/usr/local/etc/syslog-ng.conf.d/syslog-ng-destinations.conf`:
```
destination d_a3631f45fb0e4393895a505fbce9ed15 {
    network(
        "xxxxx"
        transport("udp")
        port(514)
        ip-protocol(4)
        flags(syslog-protocol)
        persist-name("a3631f45fb0e4393895a505fbce9ed15")
    );
};
```

**Comment by cs-1** [comment]
For `transport(udp)` (the transport you're using in the example) it works as expected (see my original post). But when using `transport("tls")` with `port(6514)` it doesn't work, `flags(syslog-protocol)` is not set in `/usr/local/etc/syslog-ng.conf.d/syslog-ng-destinations.conf`. I made sure to apply the config. Changing the transport to UDP and back to TLS (always applying the config) consistently shows the same issue.

**Comment by AdSchellevis** [comment]
ok, then this https://github.com/opnsense/core/commit/8a8b6ff2d67099f590fb4887c4d427690b56f723 seems to be your issue.

**Comment by cs-1** [comment]
Yes, that seems to be the case. Thanks, Ad!

**Comment by AdSchellevis** [comment]
You're welcome, I missed the udp part in your ticket 🙃

**Comment by AdSchellevis** [comment]
I'll ask @fichtner to include it in the next one

**Comment by cs-1** [comment]
That'd be brilliant. Thanks, Ad!
