### ISSUE TITLE
Suricata stopped working after upgrade to 23.7(.2)

### ISSUE THREAD

**Issue by tsense1337** [opnsense/core#6814]
- [v] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [v] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

after upgrading from 22.1.11 to 23.7 suricata fails to launch. returning to 22.1.11 everything was fine again. Seems that the 10Gbit interfaces could not be handled correctly. Suricata is configured to run in inline mode (IPS).

**To Reproduce**

1. Upgrade from 22.1.11 to 23.7

**Expected behavior**

We see this error messages:
Error   suricata   [104583] <Error> -- [ERRCODE: SC_ERR_FATAL(171)] - opening devname netmap:ix1^3/T failed: Cannot allocate memory   
Error   suricata   [102114] <Error> -- [ERRCODE: SC_ERR_FATAL(171)] - opening devname netmap:ix1^3/T failed: Cannot allocate memory

**Describe alternatives you considered**
N/A

**Screenshots**
N/A

**Relevant log files**

Error   suricata   [104583] <Error> -- [ERRCODE: SC_ERR_FATAL(171)] - opening devname netmap:ix1^3/T failed: Cannot allocate memory   
Error   suricata   [102114] <Error> -- [ERRCODE: SC_ERR_FATAL(171)] - opening devname netmap:ix1^3/T failed: Cannot allocate memory

**Additional context**

N/A

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 23.7 (amd64, OpenSSL).
nic ='NetXtreme BCM5719 Gigabit Ethernet PCIe'
nic = 'Ethernet Controller 10-Gigabit X540-AT2'

**Comment by fredouil66** [comment]
Hello i have the same issue since 23.7

**Comment by fredouil66** [comment]
Have you found a solution ?

**Comment by fredouil66** [comment]
Changelog 23.7 :
ports: suricata now enables Netmap V14 API

**Comment by fichtner** [comment]
> Cannot allocate memory

That doesn't seem like a driver problem. FreeBSD 13.2 changed as well, maybe the driver has changed too. Or a manual adjustment somewhere for buffer size / slot count behaving differently now. But not a general problem.

Obvious question: do you have enough RAM?

**Comment by fichtner** [comment]
I'm assuming each ring now takes its own device and hits a driver limit. Not sure where that limit is.

**Comment by fredouil66** [comment]
yes and as there are several queues per interface... the limit arrives quickly, I am not found either.

dev.netmap.admode=2 seems to have circumvented the problem, I will see over several days..

**Comment by tsense1337** [comment]
works again!

thx

**Comment by AdSchellevis** [comment]
Maybe someone can open a ticket in our docs repo or open a pull-request to explain the netmap mode setting. I don’t think this documented somewhere yet and some (virtual) adapters don’t play nice with netmap in our experience

**Comment by AdSchellevis** [comment]
Well, the buf_num could be the cause of your issue as the default is much lower if I’m not mistaken. When the defaults don’t work, the emulated mode is nowadays a good alternative as the performance drop seems to be low and upstream there’s not much interest in fixing netmap support in various drivers in our experience.
This was one of the mean reasons our friends of Zenarmor worked with us to improve the emulated mode together with people from Klara.

I would certainly try if you use-case works with all defaults set, if not, it’s good to know the limitations.

**Comment by Samega7Cattac** [comment]
Having the same issue since I installed opnsense.
