### ISSUE TITLE
Don't restart OpenVPN connections etc when DHCP WAN IP address is the same

### ISSUE THREAD

**Issue by jonpmyatt** [opnsense/core#6816]
- [x ] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [ x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**

When the DHCP WAN IP address is renewed but is the same IP address, rc.newwanip restarts everything including OpenVPN connections, which can result in a new IP address for OpenVPN, which clients don't like.

Why does anything have to happen at all if the WAN IP address doesn't change?

It would be better if the renewal of the WAN IP address was less disruptive in the case of the IP address not changing.

**Additional context**

Add any other context or screenshots about the feature request here or links to relevant forum thread or similar

Example: 

opnsense | /usr/local/etc/rc.newwanip: IP renewal starting (new: 88.102.221.199, old: 88.102.221.199, interface: WAN[wan], device: igb0, force: yes)
Creating resolv.conf |  
2023-09-01T11:57:28 | Notice | dhclient | New Routers (igb0): 88.102.221.1 |  
2023-09-01T11:57:28 | Notice | dhclient | New Broadcast Address (igb0): 88.102.221.255 |  
2023-09-01T11:57:28 | Notice | dhclient | New Subnet Mask (igb0): 255.255.254.0 |  
2023-09-01T11:57:28 | Notice | dhclient | New IP Address (igb0): 88.102.221.199 

...but the IP address has not changed.

**Comment by fichtner** [comment]
Unfortunately dhclient might reset the interface address to the same value, which kills the attached routes due to "undesired intentional behaviour" in the kernel which requires a full recycle for the scripting. But I don't think that applies to the new OpenVPN instances.
