### ISSUE TITLE
generated radvd.conf contains a syntax error on RDNSS setting

### ISSUE THREAD

**Issue by Rikiki87** [opnsense/core#6819]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

radvd is failing to start with a syntax error. Clients relying on it fail to get an IP

**To Reproduce**

Unsure, this happens even if I uncheck the "Allow manual adjustment of DHCPv6 and Router Advertisements" setting on my LAN interface

**Expected behavior**

OPNSense should generate working syntax for radvd

**Describe alternatives you considered**

Removing the %<interface_name> to the RDNSS statement allows radvd to start and clients are able to get an IP

**Screenshots**

**Relevant log files**
```
root@OPNsense:~ # /usr/local/sbin/radvd -p /var/run/radvd.pid -C /var/etc/radvd.conf -m syslog
/var/etc/radvd.conf:14 error: syntax error
```

```
root@OPNsense:~ # cat -b /var/etc/radvd.conf
     1  # Automatically generated, do not edit
     2  # Generated for DHCPv6 server wan
     3  interface igc0_vlan100 {
     4          AdvSendAdvert on;
     5          MinRtrAdvInterval 200;
     6          MaxRtrAdvInterval 600;
     7          AdvLinkMTU 1500;
     8          AdvDefaultPreference medium;
     9          prefix fe80::/64 {
    10                  DeprecatePrefix on;
    11                  AdvOnLink off;
    12                  AdvAutonomous off;
    13          };
    14          RDNSS fe80::62be:b4ff:fe05:4774%igc0_vlan100 {  ## the '%' is causing a syntax error
    15          };
    16          DNSSL localdomain {
    17          };
    18  }; 
[...]
```

**Environment**

OPNsense 23.7.3-amd64
OpenSSL 1.1.1v 1 Aug 2023
Intel(R) Celeron(R) N5105 @ 2.00GHz 
Network Intel® I225-V

**Comment by fichtner** [comment]
Seems to be another one here https://forum.opnsense.org/index.php?topic=35848.0

**Comment by fichtner** [comment]
What sort of interface is this? `igc0_vlan100` the code thinks it is a WAN interface, which seems odd given that you want to run RADVD on it.

**Comment by Rikiki87** [comment]
Yes that's my WAN interface, from what I understand, this radvd conf is generated because my WAN IPV6 is set to "Request only an IPv6 prefix" and my LAN interface is set to track WAN.

**Comment by fichtner** [comment]
RADVD should run on LAN. That's the odd part.

**Comment by Rikiki87** [comment]
It runs on both, I just truncated the config in my original post, here is the full config:

```root@OPNsense:~ # cat -b /var/etc/radvd.conf
     1  # Automatically generated, do not edit
     2  # Generated for DHCPv6 server wan
     3  interface igc0_vlan100 { ## WAN interface
     4          AdvSendAdvert on;
     5          MinRtrAdvInterval 200;
     6          MaxRtrAdvInterval 600;
     7          AdvLinkMTU 1500;
     8          AdvDefaultPreference medium;
     9          prefix fe80::/64 {
    10                  DeprecatePrefix on;
    11                  AdvOnLink off;
    12                  AdvAutonomous off;
    13          };
    14          RDNSS fe80::62be:b4ff:fe05:4774%igc0_vlan100 {
    15          };
    16          DNSSL localdomain {
    17          };
    18  };
    19  # Generated for DHCPv6 server lan
    20  interface igc1 { ## LAN interface
    21          AdvSendAdvert on;
    22          MinRtrAdvInterval 200;
    23          MaxRtrAdvInterval 600;
    24          AdvLinkMTU 1500;
    25          AdvDefaultPreference high;
    26          AdvManagedFlag on;
    27          AdvOtherConfigFlag on;
    28          prefix 2001:xxxx::/64 {
    29                  DeprecatePrefix on;
    30                  AdvOnLink on;
    31                  AdvAutonomous on;
    32          };
    33          route 2001:xxxx::/72 {
    34                  RemoveRoute on;
    35          };
    36          RDNSS 2001:xxxx:xxxx {
    37          };
    38          DNSSL localdomain {
    39          };
    40  };
```

**Comment by fichtner** [comment]
For some reason the DHCPv6 server was enabled on WAN, which it shouldn't. I could add a safeguard but I'm not sure where this comes from (previous static assignment on WAN misconfiguring router advertisements there?)

You can see the config using:

     # pluginctl -g dhcpd.wan

In the /conf/config.xml you can drop the <wan/> element and all its contents under <dhcpd/> and that should make it work again.


Cheers,
Franco

**Comment by maurice-w** [comment]
Hm, WAN uses a VLAN in both cases. Coincidence?

**Comment by fichtner** [comment]
I think it is. Somehow the install was coerced into running a DHCPv6 server on WAN at one point in time and it never got disabled. 23.7's interfaces_primary_address6() had a little chance that causes the link-local to appear now where it didn't before but the problematic configuration was already in place and worst case interfered with the setup.


Cheers,
Franco

**Comment by Rikiki87** [comment]
The output of pluginctl is empty, is this expected?
```
root@OPNsense:~ # pluginctl -g dhcpd.wan

root@OPNsense:~ #
```

**Comment by fichtner** [comment]
Good point, let's try searching for the right one ;)

    # pluginctl -g dhcpdv6.wan


Cheers,
Franco

**Comment by Rikiki87** [comment]
Hi,

Yep, here is the output:
```
root@OPNsense:~ # pluginctl -g dhcpdv6.wan
{"ramode":"router","rapriority":"medium","ramininterval":"200","ramaxinterval":"600","radomainsearchlist":"","radnsserver":[]}
```

I removed the <wan> block under the dhcpdv6 block in config.xml, restarted the router and now the radvd conf looks correct (only LAN is mentionned).

I did try to hit save on both my WAN and LAN interface to see if that made the entries reappear but it does not look like it.

Everything seems to work on my end. Thanks a lot!

What's strange is that I have never touched that config.xml manually in the past, I'm not sure what created that WAN block for dhcpdv6...

**Comment by fichtner** [comment]
Unsure too but I'm treating this as a support case now. The behaviour for 23.7 did change causing this to break, but I don't see a reason for this entry in the first place... maybe some sort of test configuration or early configuration try. FWIW, I added a feature to `pluginctl` to be able to drop these garbage entries easily in #6834 

Cheers,
Franco

**Comment by fichtner** [comment]
For future reference the configuration can only have been written by services_router_advertisements.php at one point in time. Nothing else ever sets "ramode".
