### ISSUE TITLE
illegal alias names error message

### ISSUE THREAD

**Issue by andreas-p** [opnsense/core#682]
Apparently, the name "monitor" is illegal as ip host alias name. The error message says "The alias name must be less than 32 characters long and may only consist of the characters a-z, A-Z, 0-9, _." which is obviously misleading. Looking at util.inc, is_validaliasname checks some reserved words, and returns NULL instead of false, so it should be easy to change the error message. Maybe a hint, what kind of words may conflict, would be nice.

**Comment by fichtner** [comment]
it looks into a long list of protocol names in /etc/services

the whole thing seems counter-intuitive, I'll ditch the checks and prefix the alias to void (potential) namespace conflicts

**Comment by fichtner** [comment]
Changing scope to original proposal: return a list of reserved keywords on an error.

**Comment by fichtner** [comment]
This code will change drastically in the future and reports have been very low. Closing this.
