### ISSUE TITLE
System-Access-Tester: Encoding issue from Microsoft NPS server

### ISSUE THREAD

**Issue by stumbaumr** [opnsense/core#6820]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

Executing the tester with "Synchronize groups" ticked on shows the groups coming from the authenticating server.
Umlauts are displayed incorrectly...

**To Reproduce**

1. Add Microsoft NPS service as Radius server and tick "Synchronize groups" in System-Access-Servers
2. Execute System-Access-Tester and log on
3. Check for Umlauts
4. See [Mojibake](https://en.wikipedia.org/wiki/Mojibake)

**Expected behavior**

Umlauts should be displayed properly...

**Screenshots**

![grafik](https://github.com/opnsense/core/assets/12425441/eb7b98a6-f818-4bc2-b728-9bb9109a753d)

**Relevant log files**

None.

**Additional context**

None.

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 23.7.3-amd64
FreeBSD 13.2-RELEASE-p2
OpenSSL 1.1.1v 1 Aug 2023

**Comment by fichtner** [comment]
It would help to paste it here. Likely because MS doesn't return UTF-8... it's difficult to guess the encoding because it's tied to a localization.

**Comment by stumbaumr** [comment]
Probably related...
https://github.com/dapphp/radius/issues/5

**Comment by stumbaumr** [comment]
Äääääh, something seems really borked here on my test system...
![grafik](https://github.com/opnsense/core/assets/12425441/e8f0810f-0158-4c32-8ff9-4eaedea43ee2)
