### ISSUE TITLE
VPN: IPsec: Log File : Output is unusable due to usage of UUIDs

### ISSUE THREAD

**Issue by stumbaumr** [opnsense/core#6821]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

The log file out put is unusable if you do can not link the used UUIDs in the swanctl.conf to the Connections in the WebGUI.

**To Reproduce**

1. Create some Connections
2. Go to the Log files section
3. Try to figure out what happens without looking into the swanctl.con file

**Expected behavior**

Either add the UUIDs in the WebGUI or do not use UUIDs in the config at all... 

**Describe alternatives you considered**

Staying on 22.7 forever ;-)

**Screenshots**

![grafik](https://github.com/opnsense/core/assets/12425441/d4ef1129-e7e2-4516-867c-fb956466fe1b)

**Relevant log files**

**Additional context**

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 23.7.3-amd64
FreeBSD 13.2-RELEASE-p2
OpenSSL 1.1.1v 1 Aug 2023

**Comment by AdSchellevis** [comment]
like this ?
<img width="484" alt="image" src="https://github.com/opnsense/core/assets/9783985/2ca276a8-e66d-4c67-b765-eed953988f19">

**Comment by stumbaumr** [comment]
No, rather like this...
![grafik](https://github.com/opnsense/core/assets/12425441/13c48e4b-8262-44c1-b299-f72a26fde8f7)

**Comment by stumbaumr** [comment]
Uuuups - sorry, just found that missing checkbox...

**Comment by miken32** [comment]
> Uuuups - sorry, just found that missing checkbox...

What does this mean? I would also like to have more helpful output in log files, this seems like a good request?

**Comment by AdSchellevis** [comment]
@miken32 check the id field:
<img width="178" alt="image" src="https://github.com/opnsense/core/assets/9783985/84c93829-7b4d-49e0-9839-b78aba5bbcee">

**Comment by miken32** [comment]
Ah ok I was hoping for something to show a friendly name in the log files. All our routers have 4 site-to-site tunnels as well as possible mobile clients. It gets busy!
