### ISSUE TITLE
Firewall - live view does not use description information from rule instead of "nat rule" as label

### ISSUE THREAD

**Issue by Brownys** [opnsense/core#6839]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

if a create a "outbound-rule" the "live view" always shows "nat rule" as label for the log entry and not the description of the triggered rule

**To Reproduce**

1. Go to 'firewall.' and create a nat outbound rule for p.e. a specific lan ip.
2. activate logging for that firewall rule
3. go to "firewall" -> "live view" and wait until the rule is triggered by the specific lan device
4. check the log entries
5. See error, that the description is "nat rule" instead of "description of triggered rule"

**Expected behavior**

If i create a firewall rule (outbound) the live view will show the description information from dedicated firewall rule as information in the column "label"

**Describe alternatives you considered**

if the rule has not an description it shows maybe furthermore the Label "nat rule"

**Screenshots**

![image](https://github.com/opnsense/core/assets/53260366/8540229d-2812-4612-81cd-660f8d908d1a)

![image](https://github.com/opnsense/core/assets/53260366/fcc0342c-5ac3-43f0-888d-b37aa0115311)

**Relevant log files**

-

**Additional context**

-

**Environment**
OPNsense 23.7.3-amd64

**Comment by fichtner** [comment]
NAT rules in pf(4) do not support labels.


Cheers,
Franco

**Comment by RangerXP** [comment]
We are in 25.1 and this appears to still be an issue.  Is this planning to be addressed?

**Comment by fichtner** [comment]
NAT rules do not support labels in the OS layer. There is nothing to fix, but I mentioned that before.

**Comment by RangerXP** [comment]
Thank you for the reply.  I though that might be a transient issue from
23.x but sounds like OPNSense will never make that feature available.  Is
there another way to capture the NAT rule description detail at the
application layer?  I tried using Tags as well.. perhaps tagging is a
better way to go, especially if I plan to filter on them?

Cheers
