### ISSUE TITLE
ui: selectpicker issue with ipv4v6net after version update

### ISSUE THREAD

**Issue by fichtner** [opnsense/core#6849]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

IPv4 subnet selector in legacy doesn't work anymore (no options visible). Strangely IPv6 works. May be due to disabled options in the select element?

Also reminder to rename files in plugins.

**To Reproduce**

Use e.g. Interfaces: Other Types: GIF: GIF tunnel remote address and enter an IPv4 and try to select a subnet other than 32

**Expected behavior**

selectpicker works for IPv4 too.

**Describe alternatives you considered**

N/A

**Screenshots**

N/A

**Relevant log files**

N/A

**Additional context**

N/A

**Environment**

24.1 development

**Comment by AdSchellevis** [comment]
https://github.com/opnsense/core/commit/445a81d73ba1026b2e445c87183afdd34f271ca9 should do the trick (more or less)

**Comment by fichtner** [comment]
I'm seeing it jump between 32 and 128 now on changing the subnet selector. I'll take a closer look tomorrow.

**Comment by fichtner** [comment]
@AdSchellevis I forgot to ask: should I simply rename the files used in the plugins? we've already had a few reports regarding this on the latest devel version.

**Comment by AdSchellevis** [comment]
@fichtner I expect a rename would work indeed.

**Comment by fichtner** [comment]
shipped in 23.7.9 today
