### ISSUE TITLE
menu: favourites menu

### ISSUE THREAD

**Issue by andreas-p** [opnsense/core#685]
I'm frequently navigating to the same couple of menu entries, e.g. dhcp leases or firewall/rules/LAN. Instead of having to click several times, a favourite menu with my preferred 5-10 topics would be nice.

OTOH, I'll certainly never use PPTP in my life again (nobody should...), so I propose an option to slim down the menu by hiding unwanted menu entries.

**Comment by fichtner** [comment]
Wouldn't a favourites widget be suitable for the dashboard instead?

FWIW, you can create a new user and only assign privileges to the pages you need, the others will be removed from the menu automatically.

PPTP will be moved to a plugin mid-term so it's not on the default install anymore (maybe 16.7)

**Comment by andreas-p** [comment]
IMHO the dashboard is for status stuff only; navigation elements should be limited to the menu, so my proposal is a top-level "favourites" menu entry.

**Comment by fichtner** [comment]
please open a separate ticket for the ACL selection

**Comment by fichtner** [comment]
Upon further discussion, this doesn't fit our project direction of a no-frills firewall. There are some things we'll do to enhance the individual user experience (e.g. widgets and themes per user), but the favourites menu would just build on top of the ACL, which doesn't mean that this can't be a plugin if contributed. :)

**Comment by AdSchellevis** [comment]
Some additional information on how to create your own menus can be found in this issue https://github.com/opnsense/core/issues/832 
As of 16.1.8 the "delete" option for existing menu's will be available in the standard version of OPNsense.
