### ISSUE TITLE
OpenVPN: Instances [new] - Client Certificate is mandatory

### ISSUE THREAD

**Issue by iqt4** [opnsense/core#6856]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

In the Trust section of VPN: OpenVPN: Instances [new] for clients a certificate must always be selected. I expect this to be optional for the client. On the server side we can set respective option --client-cert-not-required <none|optional|require>. 

**To Reproduce**

1. Go to 'VPN: OpenVPN: Instances [new]'
2. Click on 'Add'
3. Change Role to 'Client'
4. Scroll down to 'Certificate'
5. Option 'None' is not available

**Expected behavior**

Option 'None' is available for Certificate

**Describe alternatives you considered**

The option 'None' is available for Client Certificate in VPN: OpenVPN: Clients

**Screenshots**

n/a

**Relevant log files**

n/a

**Additional context**

See discussion https://github.com/opnsense/core/issues/6753#issuecomment-1722250101

ProtonVPN uses TLS and username/password for trust - not certificates.

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 23.7.4 (amd64).

**Comment by iqt4** [comment]
@AdSchellevis: Two observations regarding the generated /var/etc/openvpn/instance...conf file:

- Certificate Authority is missing
- 'verify-client-cert none' leads to log entry "Options error: --verify-client-cert requires --mode server"

Do you want me to open a new issue or can we reopen this one?

**Comment by AdSchellevis** [comment]
My advise would be to try which options you need first, then explain the difference between what is generated now, after which we can assess if we should reopen or need an extra ticket. Please keep the deprecation notes into account, as anything in there won't be in included in the new instances. (e.g. https://community.openvpn.net/openvpn/wiki/DeprecatedOptions#Option:--client-cert-not-requiredStatus:RemovedinOpenVPNv2.5)

It's not very complicated to start the instance created (you can find the files in `/var/etc/openvpn/instance-*.conf`)
