### ISSUE TITLE
mass edit in firewall rules

### ISSUE THREAD

**Issue by jpVm5jYYRE1VIKL** [opnsense/core#6858]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**

Yes my issue related to the problem. I have several thousands firewall rules and sometimes i need to do changes for multiply rules(In most cases hundreds). In current moment exist only one way to do it in opnsense - manual edit one by one. Due to it normally for simple change(  for example gateway item ) for hundred firewall rules need to spend 2 -3 hours doing stupid task . 
( Select rule , press edit , do change , press save and repeat again.)

**Describe the solution you like**

it is very simple . You already have possibility to select rules . Only what needed to add button "edit selected" and implement edition of field which was changed for all selected rules.

**Describe alternatives you considered**

such way mass edit quite good implemented in Netbox Gui. It is not alternative but can be used as a concept. 

**Additional context**

Add any other context or screenshots about the feature request here or links to relevant forum thread or similar

**Comment by mlazzarotto** [comment]
Wow, this could be a MASSIVE improvements in OPNsense usability!!!
As a Network Engineer used to work with Cisco ASA through CLI, I often find quite slow to work with multiple rules on OPNsense.
