### ISSUE TITLE
VPN: IPsec: Connections: Pools add IP4_DNS and IP6_DNS Configuration Payloads

### ISSUE THREAD

**Issue by Monviech** [opnsense/core#6860]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**

With the current implementation of pools in the OPNsense GUI it's not possible to define  DNS Servers as "Configuration Payload" (rfc4306 and rfc7296 3.15).

The DNS Server Configuration Payloads are defined as:
```
                                                        
Attribute Type           Value     Multi-Valued   Length

INTERNAL_IP4_DNS         3     YES                    0 or 4 octets
INTERNAL_IP6_DNS        10    YES                    0 or 16 octets
```
https://docs.strongswan.org/docs/5.9/swanctl/swanctlConf.html#_pools
The strongswan docs defines all additional attributes that are accepted in pools. ``<name>.<attr>`` allows the use of the ``Value`` as numeric number.

The Values 3 and 10 are mapped in ``vici`` as ``dns`` and allow multiple values seperated by a comma as delimiter.

An example configuration ``swanctl.conf`` ``pools{}`` section would look like this:
```
pools {
    pool-roadwarrior-ipv4 {
        addrs = 172.16.203.0/24
        dns = 192.168.1.1,192.168.1.2
    }
    pool-roadwarrior-ipv6 {
        addrs = 2001:db8:1234:ec::/120
        dns = 2001:db8:1234:1::1,2001:db8:1234:1::2
    }
}
```
It looks like there is no limit to 2 dns servers. You can input several with comma as delmiter and they're all pushed.
```
dns = 192.168.1.1,192.168.1.2,192.168.1.3,2001:db8:1234:1::1,2001:db8:1234:1::2,2001:db8:1234:1::3
```

**Describe the solution you like**

I would like additional configuration fields in VPN: IPsec: Connections Pools tab that allow to set DNS IPv4 (Value 3) and DNS IPv6 (Value 10) Servers. That way clients will be autoconfigured with the Virtual IP and DNS Servers.

**Describe alternatives you considered**

Configuring DNS manually in all roadwarrior configurations.

**Additional context**

I have already tested this with 2 pools as seen above, to create a dual stack IPv6 Roadwarrior tunnel to an android Strongswan client. Both virtual IPs and both DNS Servers are pushed and imported into the client configuration on connect.

I stumbled upon this missing functionality while writing a tutorial for IKEv2 Roadwarriors
with the new Connections Interface.

Additional Note: iOS ignores DNS Configuration Payloads, this only works for Android, Windows, Linux.

I don't know if I'm confident enough to implement it, if desired I could try it though. I'm not sure how to tokenize an input field that allows multi values.

**Comment by AdSchellevis** [comment]
@Monviech Just open a PR in draft mode and comment on the items you're not sure about, I'll take a look when I do have the time. 

By the way, I think you can also just use `dns`, these seemed to be mapped in vici :

https://github.com/strongswan/strongswan/blob/190d8cbe1931ec57484d9bb451824a7fc57979bd/src/libcharon/plugins/vici/vici_attribute.c#L418

**Comment by Monviech** [comment]
@AdSchellevis Sounds good, thank you. The mapping looks better than using values. Is the scope with just DNS sufficent? Im not sure if there's real use cases for the other values, but if somebody requests them in the future, should the input field allow for them?

**Comment by AdSchellevis** [comment]
just dns should be fine, we can always add more when needed.
