### ISSUE TITLE
Gateway behind OpenVPN client instance does not get monitored (dpinger does not start)

### ISSUE THREAD

**Issue by Daggolin** [opnsense/core#6868]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

When starting an OpenVPN client instance (`VPN > OpenVPN > Instances [new]`) OPNsense 23.7.x does not start a `dpinger` instance to monitor the corresponding gateway.

The client instance is connecting to a remote server on the default OpenVPN port using a certificate and a TLS static key. No settings were provided for the section `Authentication`. For `Routing` only `Remote Network` was provided as `10.9.0.0/24`. For `Miscellaneous` the option `route-nopull` is enabled.

The VPN Client is assigned as interface (`Interfaces > Assignments`) and a gateway is configured for the interface (`System > Gateways > Single`). The gateway has `10.9.0.1` specified as `Monitor IP`.

When starting the VPN Client instance the connection is established, but the gateway remains `Offline`. Checking for running `dpinger` instances using `ps auxww | grep dpinger` there is no instance monitoring the gateway of the VPN client. Manually disabling and re-enabling the gateway causes an instance of `dpinger` for the gateway to spawn and the gateway gets a valid status.

This used to be no problem back on 23.1: when using a VPN Client on OPNsense 23.1 the `dpinger` instance gets started automatically and the gateway get monitored. Disabling the VPN client keeps the `dpinger` instance around and upon reconnecting the `dpinger` instance gets removed and a new one gets started to replace it.

On a side note: back on 23.1 it was not even required to specify a `Monitor IP` for the gateway, the gateway IP would automatically be used if left blank (as the help text implies it should still do), but trying to disable / enable the gateway does not spawn an instance of `dpinger` if no explicit `Monitor IP` is specified on 23.7.4 - this might be another bug.

**Additional context**

This issue might be related to https://github.com/opnsense/core/issues/6862, considering that issue seems to be related to `dpinger` not properly getting restarted/reloaded when it should be, leading to `dpinger` delivering incorrect data. So there might be a few places (like VPN connections) missing a restart/reload. I stumbled upon this VPN issue during tests related to the other issue, but I had already noticed the gateway monitoring not working during a quick test on 23.7.1, but assumed it was related to https://github.com/opnsense/core/issues/6728 at the time.

**Expected behavior**

A gateway that is associated with a VPN instance should automatically be monitored when the VPN instance establishes a connection.

**Environment**

Software version used and hardware type if relevant, e.g.:

Versions:
 - OPNsense 23.7.4-amd64
 - FreeBSD 13.2-RELEASE-p3
 - OpenSSL 1.1.1v 1 Aug 2023

CPU type:
 - Intel(R) Xeon(R) CPU D-1518 @ 2.20GHz (4 cores, 8 threads)

**Comment by Daggolin** [comment]
I have noticed that the old OpenVPN instances call the `ovpn-linkup` and `ovpn-linkdown` scripts. The generated configs for legacy instances have `up` and `down` instructions to call those scripts. The new instances do not.

The `ovpn-linkup` script calls `/usr/local/sbin/configctl -d interface new ${1} force`, which I assume triggers the `newip` action, thus executing the `rc.newwanip` script which then starts the `dpinger` instance to monitor the gateway.

I have not looked into the exact differences between the legacy and new instances, so I am not sure if the `ovpn-linkup` script was intentionally left out for new instances, because some things are supposed to be handled differently, or not. However, adding it to the new instances solves the issue:
```diff
diff --git a/src/opnsense/mvc/app/models/OPNsense/OpenVPN/OpenVPN.php b/src/opnsense/mvc/app/models/OPNsense/OpenVPN/OpenVPN.php
index de54eb42a..4f89ca174 100644
--- a/src/opnsense/mvc/app/models/OPNsense/OpenVPN/OpenVPN.php
+++ b/src/opnsense/mvc/app/models/OPNsense/OpenVPN/OpenVPN.php
@@ -499,6 +499,8 @@ class OpenVPN extends BaseModel
                 $options['proto'] = (string)$node->proto;
                 $options['verb'] = (string)$node->verb;
                 $options['verify-client-cert'] = (string)$node->verify_client_cert;
+                $options['up'] = '/usr/local/etc/inc/plugins.inc.d/openvpn/ovpn-linkup';
+                $options['down'] = '/usr/local/etc/inc/plugins.inc.d/openvpn/ovpn-linkdown';
 
                 foreach (
                     [
```

**Comment by fichtner** [comment]
@Daggolin nice catch, can you make a PR?

**Comment by fichtner** [comment]
@Daggolin thanks again for your work on both of the reported issues <3
