### ISSUE TITLE
Firewall: Shaper [tcp (ACK packets only)] not working

### ISSUE THREAD

**Issue by dMopp** [opnsense/core#6873]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**
When iam creating a flow rule for TCP-ACK packets, i can see every traffic is matched as an ACK packet instead of ACK only, Settings see screenshot. So it looks the, the protocol matching for TCP-ACK is not working

**To Reproduce**

- Create a Flow rule like i did
- Open the status Dashboard
- Start a speedtest (speedtest.net as an example)
- Watch that ALL traffic goes into the rule instead of the ACKs only

**Expected behavior**

Only acks reaching that flow.,

**Describe alternatives you considered**

Currently i disabled the rule, so not all traffic is high traffic now.

**Screenshots**

![grafik](https://github.com/opnsense/core/assets/5166587/d7020edc-03c1-49a0-84b9-0d134edc0fe4)

**Relevant log files**

n.a.

**Additional context**

n.a.

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 23.7.4-amd64 OpenSSL 1.1.1v 1 Aug 2023
KVM Virtualized
VirtIO

**Comment by fichtner** [comment]
The problem is described here but a solution was never contributed https://github.com/opnsense/core/issues/4132

It's matching ALL packets with ACK but you probably want only the ones with the shorter IP length. Modern TCP stacks add ACKS everywhere they can to save an extra packet.

**Comment by maxfield-allison** [comment]
Hey! I actually did contribute the IPlen option. i think the value we settled on to match strictly ACK packets was something like 72.

**Comment by fichtner** [comment]
True, the option is hidden under advanced: 5c3791ef8bef2 and needs to be set manually then. Sorry about missing it.

**Comment by fichtner** [comment]
@dMopp close then?

**Comment by dMopp** [comment]
Yep, sorry
