### ISSUE TITLE
captive portal: voucher login simplification

### ISSUE THREAD

**Issue by fichtner** [opnsense/core#688]
@DokuKaefer asks whether there will be simpler login types that only use the voucher code like in the old CP or at least a way to have multiple vouchers to activate the same user.

I'm guessing in this case vouchers should be temporary users, that's a bit against the way the authentication is set up currently, right?

**Comment by AdSchellevis** [comment]
No, not planned. 
I'm not saying it's impossible to authenticate with only a username (and an empty/pre-defined password), but either the voucher code needs to generate empty (or default) passwords or a new plugin is required and the template needs to be adjusted to support this.

**Comment by fichtner** [comment]
Closing, thanks :)

**Comment by jstrebel** [comment]
Ad, in many CP applications it is much more convenient to enter only a voucher code. What are the reasons to eliminate this feature wich first appeared in monowall?

**Comment by AdSchellevis** [comment]
@jstrebel, we just choose a direction here (we had to build all from scratch). It is rather easy to build plugins for different types of use, and there are quite some possibilities with the new template system (including concatenation of the user/pass combination for the voucher as one with a separator in between).

**Comment by jstrebel** [comment]
Thank you Ad, this is a very positive response. (fyi we have developed the voucher system almost then years ago for monowall.)
