### ISSUE TITLE
Can't load rules with A/N protocol

### ISSUE THREAD

**Issue by NOYB** [opnsense/core#6880]
There were error(s) loading the rules: /tmp/rules.debug:409: unknown protocol a - The line in question reads [409]: block in quick on re0_vlan99 reply-to ( re0_vlan99 50.38.40.1 ) inet proto a/n from {any} to {any} label "9fb69f05dcc290de9015939ac2bf4d2d"

Probably doesn't like the slash in 'a/n'

OPNsense 23.7.4
FreeBSD 13.2-RELEASE-p3
OpenSSL 1.1.1v 1 Aug 2023
11th Gen Intel(R) Core(TM) i3-1115G4 @ 3.00GHz
Some Realtek NIC

**Comment by fichtner** [comment]
Quoting the string probably works. But please don’t quote the protocol numbers if they are passed to the config.

**Comment by NOYB** [comment]
Don't see a mechanism in the GUI for quoting rule protocol.

**Comment by fichtner** [comment]
That’s good, because I never said “GUI”.

**Comment by NOYB** [comment]
Never said not GUI either.  ;)  But GUI has the A/N protocol available for rules and it fails to load when applying.  Seems that if it's going to be available for specifying in the GUI that it should be made to work or be removed.

**Comment by fichtner** [comment]
> Never said not[sic] GUI either. ;)

> Don't see a mechanism in the GUI for quoting rule protocol.

**Comment by NOYB** [comment]
Talking about what you said/didn't say.  Not what I said.  But that's just pettiness that can go around in circles off the rails indefinitely.

Meanwhile back on the rails...
Setting the A/N protocol in the GUI is broken.
Will it be fixed?  Guess time will tell.

**Comment by Monviech** [comment]
I just tested it too in the GUI with a protocol A/N rule and it resulted in the same error:

``
2023-09-25T08:54:00	Error	firewall	There were error(s) loading the rules: /tmp/rules.debug:472: unknown protocol a - The line in question reads [472]: pass in quick on hn5 inet proto a/n from {any} to {any} keep state label "c3154db8bf416dc89514303dc66ec964"
``

Looking at the IANA protocol numbers, it looks like it's the only protocol with "/" in its keyword.

I'm not even sure who uses this protocol though, if it would be a decently popular one it might have been found earlier. Just giving my two cents here.

**Comment by fichtner** [comment]
Go to /tmp/rules.debug and try to quote the value like "a/n" and try to reload:

    # pfctl -f /tmp/rules.debug

If this works a fix is pretty trivial. I've already outlined the required changes but they seem to get lost in "pettiness". ;)

**Comment by fichtner** [comment]
@NOYB I'm going to ban you now because working with you is too tedious. You've had too many screwups.
