### ISSUE TITLE
OpnSense 23.7 - OpenVPN Client export Bug no auth-user-pass will added

### ISSUE THREAD

**Issue by Bacaloni** [opnsense/core#6881]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X ] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [ X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

OpnSense 23.7 - OpenVPN Client export Bug no auth-user-pass will added

A clear and concise description of what the bug is, including last known working version (if any).

VPN: OpenVPN: Client Export
Issue: "auth-user-pass" will not added in the config file.

**Expected behavior**

"auth-user-pass" should be added to the config file.

**Describe alternatives you considered**

Test with an older Version is successful

Software version used and hardware type if relevant, e.g.:

OPNsense 23.7.4-amd64
FreeBSD 13.2-RELEASE-p3
OpenSSL 1.1.1v 1 Aug 2023

**Comment by AdSchellevis** [comment]
for the legacy openvpn servers this sounds like https://github.com/opnsense/core/issues/6717, which was fixed earlier. As this property depends on the mode settings of the server, server details matter....

https://github.com/opnsense/core/blob/d971257fd9c1973066486019afb84c3d8a953a3d/src/opnsense/mvc/app/library/OPNsense/OpenVPN/PlainOpenVPN.php#L136-L141
