### ISSUE TITLE
OpenVPN Instances. Add client, no certificate.

### ISSUE THREAD

**Issue by Plutoaurus** [opnsense/core#6886]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [ ] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [ ] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

Setting up a new connection to a VPN service (Nord,Express etc) using the new Instances as a Client role has a mandatory certificate field.
Public VPN providers that i have do not prove a certificate with a private key so unable to add this.
The certificate field only shows the self signed Opensense web gui certificate and None is not a option

Using the old client menu does not force this certificate option.

**To Reproduce**

Goto VPN, OpenVPN,, Instances (New)
+ to create
Change role to client
Check certificate dropdown.
Filling in all details inc the VPN CA and verify client certificate to none and trying to save still requires a certificate

**Expected behavior**

Client certificate, like in the original method of adding clients should have a "None (Username and password required) option

**Describe alternatives you considered**

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 23.7.5-amd64
openvpn | 2.6.6

**Comment by AdSchellevis** [comment]
https://github.com/opnsense/core/issues/6856#issuecomment-1728089616

**Comment by Plutoaurus** [comment]
> https://github.com/opnsense/core/issues/6856#issuecomment-1728089616

Thanks but I'm unable to get it to create any instance as the Opnsense Gui certificate says it cannot be validated and does not allow to save.

It would be this option
--verify-client-cert none
That if set either needs to ignore the certificate field or none needs to be a certificate option

**Comment by AdSchellevis** [comment]
according to https://community.openvpn.net/openvpn/wiki/DeprecatedOptions#Option:--client-cert-not-requiredStatus:RemovedinOpenVPNv2.5 `--verify-client-cert ` has been deprecated. I don't mind offering options in the gui (as mentioned in the ticket as well), but only when they're not up for deprecation.

**Comment by Plutoaurus** [comment]
> according to https://community.openvpn.net/openvpn/wiki/DeprecatedOptions#Option:--client-cert-not-requiredStatus:RemovedinOpenVPNv2.5 `--verify-client-cert ` has been deprecated. I don't mind offering options in the gui (as mentioned in the ticket as well), but only when they're not up for deprecation.

Hi.

Think that may be misread.
The old
--client-cert-not-required
Is being depreciated and replaced with the new
--verify-client-cert

Not having a no certificate option means all paid for VPNs won't work.
![Screenshot_20230927_182417_Chrome.jpg](https://github.com/opnsense/core/assets/108938674/5ce7231e-37d9-48d9-a606-c56d38fb11d9)

**Comment by Plutoaurus** [comment]
https://openvpn.net/community-resources/reference-manual-for-openvpn-2-6/
![Screenshot_20230927_183021_Chrome.jpg](https://github.com/opnsense/core/assets/108938674/837dd392-41f3-41ee-ae36-e7dc22269e75)

**Comment by AdSchellevis** [comment]
`--verify-client-cert` is a server setting (https://github.com/opnsense/core/issues/6856#issuecomment-1727678968), if someone wants movement on this topic, he or she should really spend some time building a functional setup with openvpn and explain which combination of settings he or she needs for a specific scenario. I'm not planning to spend more time on this guessing what people want.

**Comment by Plutoaurus** [comment]
> `--verify-client-cert` is a server setting (https://github.com/opnsense/core/issues/6856#issuecomment-1727678968), if someone wants movement on this topic, he or she should really spend some time building a functional setup with openvpn and explain which combination of settings he or she needs for a specific scenario. I'm not planning to spend more time on this guessing what people want. 

Sorry, you are correct on that setting. This is what services such as NordVPN must have enabled on their servers.

I have a working client openvpn config
 It doesn't really help as there isn't a certificate option, or certificate file because services like NordVPN do not provide one, hence no certificate file.


This
![20230927_201449.jpg](https://github.com/opnsense/core/assets/108938674/f7797eca-7f86-46ba-a454-d129fe0e36db)

And this section of code requires a certificate but there is not one. It is assumed that a client must have a certificate that is linked to a CA in the current instances settings but there isn't one.
This code if statement does not account for the 
"Verify Client Certificate" 
Setting if it is set to none

~~if (!empty((string)$instance->cert)) {
                if ($instance->cert->isFieldChanged() || $validateFullModel) {
                    $tmp = Store::getCertificate((string)$instance->cert);
                    if (empty($tmp) || !isset($tmp['ca'])) {
                        $messages->appendMessage(new Message(
                            gettext("Unable to locate a Certificate Authority for this certificate"),
                            $key . ".cert"
                        ));
                    }
                }~~

**Comment by AdSchellevis** [comment]
if you try to modify the openvpn file created into one that works for you, it shouldn't be an issue to fix it on our end. 

To start a file generated from the gui, use:

```
/usr/local/sbin/openvpn --config /var/etc/openvpn/instance-xxxxx-xxxx-xxx-xxx-xxxx.conf
```

(xxxxx-xxxx-xxx-xxx-xxxx equals the uuid of the instance)

https://github.com/opnsense/core/commit/6d5ca5da1ae23a9a47f300ea253f5c6868a85064 removed the requirement for a certificate.

**Comment by Plutoaurus** [comment]
> if you try to modify the openvpn file created into one that works for you, it shouldn't be an issue to fix it on our end. 
> 
> To start a file generated from the gui, use:
> 
> ```
> /usr/local/sbin/openvpn --config /var/etc/openvpn/instance-xxxxx-xxxx-xxx-xxx-xxxx.conf
> ```
> 
> (xxxxx-xxxx-xxx-xxx-xxxx equals the uuid of the instance)
> 
> https://github.com/opnsense/core/commit/6d5ca5da1ae23a9a47f300ea253f5c6868a85064 removed the requirement for a certificate.
> 

Ah Brill.
Doesn't seem to have made it to the master branch yet so wasn't seeing it.
Will try manually adding to my server to see if that let's me save the instance with no certificate.

New to actually browsing github so trying to get my head around the processes 

Ta

**Comment by fichtner** [comment]
This slipped through when doing 23.7.5 since the whole model file was being edited. I've cherry-picked this now for 23.7.6 via 98a7e04954. It may apply to 23.7.5 cleanly but not entirely sure (but the change is trivial by hand anyway).


Cheers,
Franco

**Comment by Plutoaurus** [comment]
Changed on 23.7.5 and it does indeed fix the certificate issue and allow to save.

One thing to note is that the verify client certificate option on 23.7.5 seems to be classed as a "client" option and does not get removed when changing instance from server to client in the drop down.

I've tried for about an hour to see how it determines what is client and what's server setting, but my coding skills aren't good enough to determine if it's been fixed in 23.7.6.

This causes the connection to not start and error with.
![20230928_203654.jpg](https://github.com/opnsense/core/assets/108938674/1011c5c8-8019-44df-b67e-a9ecce1b13bc)

**Comment by AdSchellevis** [comment]
if you remove the optional manually from the configuration file and start the openvpn instance, does that offer the expected results? Fixing the dependency issue should be a minor thing.

**Comment by Plutoaurus** [comment]
> if you remove the optional manually from the configuration file and start the openvpn instance, does that offer the expected results? Fixing the dependency issue should be a minor thing. 

Have tried removing and commenting out.
Each time I press the start button on the opnsense gui it adds it back in again.

**Comment by AdSchellevis** [comment]
you need to start openvpn from the console in that case. 
```
/usr/local/sbin/openvpn --config /var/etc/openvpn/instance-xxx.conf
```
