### ISSUE TITLE
IPsec Widget on Dashboard counts users per unique IP address

### ISSUE THREAD

**Issue by Monviech** [opnsense/core#6889]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

I'm not sure if it's a bug or if it's intended to be that way. It's just something I noticed. It doesn't have any real impact other than a wrong number of mobile users in the widget.

When you create a roadwarrior setup in VPN: IPsec: Connections and add more than one pool, any user that connects to this VPN connection will receive more than 1 IP. For example in a dual stack setup, they will receive one ipv4 and one ipv6 address.

The widget counts this as 2 individual mobile users, and not 1 mobile user, even if the eap local identifier is the same.

**To Reproduce**

Create a connection like this:

![image](https://github.com/opnsense/core/assets/79600909/56d86c27-5dc3-4e0a-89c6-f3cdde1c4b9f)

Connect to it and observe the ipsec widget:

![image](https://github.com/opnsense/core/assets/79600909/535443f4-cd8f-4048-87a8-70cb28f37efd)
![image](https://github.com/opnsense/core/assets/79600909/f835ce97-5992-4572-bc6b-c72ecdcf4e67)
(Screenshot has the name and ipv6 address ommited due to privacy reasons.)

Output in the shell:

```
root@opn01:~ # swanctl --list-pools --leases
pool-roadwarrior-ipv4 172.16.203.0                        1 / 0 / 254
  172.16.203.1                   online   'a@vpn1.org'
pool-roadwarrior-ipv6 2003:a:xxxx:xxxx::                  1 / 0 / 254
  2003:a:xxxx:xxxx::1            online   'a@vpn1.org'
```

**Expected behavior**

I don't know if the expected behavior should be 1 mobile user, or 2 mobile users. It depends on the design choice that was made with parsing the output `swanctl --list-pools --leases` provides.

I think it might look better if it would be like this in the IPsec Widget, and only count as 1 user:
`a@vpn1.org  172.16.203.1, 2003:a:xxxx:xxxx::1`

**Describe alternatives you considered**

Not changing any of this because it's too much work and it work's as it was designed. As I said, it's just something I noticed.

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 23.7.4-amd64
FreeBSD 13.2-RELEASE-p3
OpenSSL 1.1.1v 1 Aug 2023

**Comment by AdSchellevis** [comment]
It might be better to count the unique users indeed, currently it's not really a user count, but more of a number of leases count (same user two ipv4 addresses likely counts as more than one to). 

In the long run we probably should refactor the dashboard (and it's widgets) to something easier understandable as well, but it's currently just not high enough on the prio list.  

If you do want to try to change this to the number of unique users, be my guest, I'm not very attached to the current count. You likely only need to change this area:

https://github.com/opnsense/core/blob/8030df31caf431cbc44627aced5a3a912cae7694/src/www/widgets/widgets/ipsec.widget.php#L138-L143

**Comment by Monviech** [comment]
Thank you for the hint, I will look into it when I have time. And I kinda like the current dashboard, though it might be because I'm used to it over the years. :)

**Comment by Monviech** [comment]
@AdSchellevis 

I have changed some code, debugged whats inside $ipsec_leases (found out its 'user' that defines the identity)

I have faked some array data into `$ipsec_leases = [];` to test what I did
`$ipsec_leases = array(
    array(
        'pool' => 'pool-roadwarrior-ipv4',
        'address' => '172.16.203.1',
        'online' => true,
        'user' => 'user1@vpn1'
    ) .... etc...
);`

That's how it looks in the widget now. If that's the way you like it too, I will open a pull request once I cleaned up the code a little.

![grafik](https://github.com/opnsense/core/assets/79600909/174c0895-143d-4cbe-b3d5-e16f9a4bde7f)
![grafik](https://github.com/opnsense/core/assets/79600909/d7fb330d-d796-4840-8dda-a0d446a0d15d)

**Comment by Monviech** [comment]
@AdSchellevis 
The version above only counts online leases because I restricted it to that, and it assumes all leases are always online. If a user isn't connected, the GUI entry vanishes. 

I have one additional version that also shows the online and offline status. But I don't know if it would get too convoluted with it. 

![grafik](https://github.com/opnsense/core/assets/79600909/b0ccaa87-d4b6-49e8-8f89-9f56386f1514)

**Comment by AdSchellevis** [comment]
@Monviech I think I can live with most options, the line wrap in your examples does make it more readable by the way.
