### ISSUE TITLE
Cron for geoip DB update

### ISSUE THREAD

**Issue by 0nnyx** [opnsense/core#6892]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**

Geoip DB is apparently never updated unless downloaded manually through ui/firewall/alias#geoip

_I didn't see any geoip auto update in opnsense github code but correct me if I'm wrong_

**Describe the solution you like**

Add a cron entry at ui/cron to allow geoip DB automated updates

**Describe alternatives you considered**

Manual download

**Additional context**

From Maxmind site, the DBs are updated twice weekly, every Tuesday and Friday. 
https://dev.maxmind.com/geoip/geolite2-free-geolocation-data

When using geoip blocking, it's good practice to schedule at least a monthly geoip update.

**Comment by AdSchellevis** [comment]
it's updated every day, has a lifetime (TTL) of a bit under `86400` seconds.

https://github.com/opnsense/core/blob/78b76cb5050d77ec27833ad018cee22e71550402/src/opnsense/scripts/filter/lib/alias/geoip.py#L138

If you want to add a note or tip to the docs, you can find the source of our documentation here https://github.com/opnsense/docs/blob/master/source/manual/aliases.rst#L53 (just open a pull-request)

**Comment by 0nnyx** [comment]
I missed that obvious part... Thanks for pointing it out. Closing this request.
