### ISSUE TITLE
firewall rule with alias / MAC does not work reliable

### ISSUE THREAD

**Issue by Lutzion** [opnsense/core#6894]
I use a 

- Sophos SG 115Wr1 
- with OPNsense 23.7.5-amd64.

For my "smart" home i have installed several IOT devices of Type ESP8266. 
I want to restrict access of these devices, thus i defined an alias `ESPs` based on MAC addresses.

![AliasESP](https://github.com/opnsense/core/assets/46639828/8d646c88-4186-40f6-9194-80a3e032ce49)

As in my setup access is forbidden in general, i make one rule `ESP_an_MQTT` to allow traffic for ESP
![FirewallRules](https://github.com/opnsense/core/assets/46639828/937fd9a5-6f4a-4fe0-a35d-db9f07578a53)

Unfortunatelly in some cases traffic was blocked.
So i made a second rule that is not based on alias with mac address but with the netmask. That rule is called `ESP_an_MQTT_NetMask`

See the resulting firewall actions:
![FirewallActions](https://github.com/opnsense/core/assets/46639828/a9968ee9-5686-45a2-802b-ddab329252ed)

Although the ip-adress and mac-adress do not change, the same device sometimes triggers the rule `ESP_an_MQTT` and sometimes the rule `ESP_an_MQTT_NetMask`.

If i would not have the additional rule `ESP_an_MQTT_NetMask` at that time the IOT device would not work and be blocked.

Why is the firewall rule `ESP_an_MQTT` not working reliable?

**Comment by mimugmail** [comment]
I'd guess the problem is that you can't use wildcards in MAC address.
The logic behind is, that it looks in the arp table for current pairs and replaces the mac with the IP :)

**Comment by Lutzion** [comment]
As you see in screenshot of the firewall action, sometimes the rule with aliases of mac does not work but 40 minutes later it works.
So it can not be a generell problem with wildcards in MAC addresses.

But perhaps you give a hint:
When does a device disappear from arp table?
How often are the mac addresses replaced with ips?

**Comment by Lutzion** [comment]
I made some further testings and it seems that checking `arp static table entry`  for the dhcp reservation solves the problem.
