### ISSUE TITLE
Routing Problem - OpenVPN Local Site

### ISSUE THREAD

**Issue by Zenutrix** [opnsense/core#6897]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [YES ] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [YES ] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**
When using the OpenVPN Site2Site network, I encounter a one-sided connection configuration. Specifically: A ping from my Mikrotik router with the IP address 10.255.255.254 to the address 192.168.45.10 is successful. However, attempting the reverse - i.e., pinging from 192.168.45.10 to the address 10.255.255.254 - fails.

It seems there might be a bug related to routing. Interestingly, the connection works as expected when I implement the same setup with version OPNsense 23.1.4_1-amd64.

A traceroute attempt from 192.168.45.10 indicates that the request stops at the associated gateway and doesn't get forwarded. It appears as if Opnsense isn't correctly forwarding the OpenVPN routes.

For your information: My firewall settings are currently set to "AnyAny".

I'm available for further information if needed.
A clear and concise description of what the bug is, including last known working version (OPNsense 23.1.4_1-amd64).

*Tip*: to validate your setup was working with the previous version, use opnsense-revert (https://docs.opnsense.org/manual/opnsense_tools.html#opnsense-revert)

**To Reproduce**

1. Setup OpenVPN Site2Site
2. Setup Local & Remote Subnet (Local 192.168.45.0/24, Remote 10.255.255.0/24)
3. Set Firewall Roules to AnyAny
4. Try to Ping from the Remote Network (It works fine)
5. Try to Ping from the Local Network (Out of Time Range)

**Expected behavior**

I Ping form the Local Network and the remote Network Reply my Icmp request.

**Describe alternatives you considered**

I try the "new OpenVPN" same Problem.

**Screenshots**
![image](https://github.com/opnsense/core/assets/31670241/240ad87f-720e-4b2b-9bf5-b89d516910b8)
![image](https://github.com/opnsense/core/assets/31670241/fc5e60fa-09e9-4577-ac88-f004220027be)
![image](https://github.com/opnsense/core/assets/31670241/75ed456b-fb8c-466f-af44-35ee8e3b10cb)
![image](https://github.com/opnsense/core/assets/31670241/e2245e70-5956-42b9-846a-8c0f5a1c4254)
![image](https://github.com/opnsense/core/assets/31670241/09230043-7cd3-44d5-8a97-f91c8350b24c)

**Relevant log files**

No Log

**Additional context**

Nope

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 23.7.5-amd64
FreeBSD 13.2-RELEASE-p3
OpenSSL 1.1.1w 11 Sep 2023

Intel(R) Xeon(R) Silver 4114 CPU @ 2.20GHz (8 cores, 8 threads)

**Comment by Zenutrix** [comment]
@AdSchellevis Dont think its a Support thing

**Comment by AdSchellevis** [comment]
It likely is (OpenVPN is used quite regularly in similar setups without issues), but if proof of a bug comes in, we just relabel it as always.
