### ISSUE TITLE
system: improve backup restore area selection

### ISSUE THREAD

**Issue by dimitrijp** [opnsense/core#6901]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [ x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x ] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

I wanted to restore only IPSec configuration from my backup to new HW. If I go to System - Configuration - Backups - Restore, select restore area IPSEC, select backup file. After reboot IPSec configuration is empty.

Its working if I dont select area, but use ALL instead. OPNSense is the same version on both machines 23.7.5

A clear and concise description of what the bug is, including last known working version (if any).

*Tip*: to validate your setup was working with the previous version, use opnsense-revert (https://docs.opnsense.org/manual/opnsense_tools.html#opnsense-revert)

**To Reproduce**

**Expected behavior**

Working partial restores from backup.

**Describe alternatives you considered**

Full restore, but the partial restore feature is there to use so it should work.

**Screenshots**

**Relevant log files**

If applicable, information from log files supporting your claim.

**Additional context**

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 19.1.1 (amd64, OpenSSL).
Intel® Xeon™ E3-1225V5 3.3Ghz Quad Core
Network Intel® I210-AT

**Comment by fichtner** [comment]
Given the new components IPsec configuration is scattered over a few config keys nowadays. @AdSchellevis and me have been discussing a good way forward for this page and it’s functionality, but I’m not sure this will happen mid-term. So the question is what to do with this short-term?

**Comment by AdSchellevis** [comment]
It might be an option to hook it to the xmlrpc sync sections to make this more consistent short term, long term I'm not a huge fan of partial restores as these lack referential integrity and are not guaranteed to work

**Comment by dimitrijp** [comment]
Personally I don’t need the feature, I was just opening the issue in case it was a unknown bug, since I ran into it while I was playing with IPSEC migration to connections.

**Comment by fichtner** [comment]
Hooking into XMLRPC sounds like a good plan even though it might add sections to the configuration not formerly seen/intended. But then we could also ditch the „OPNsense additions“ option which is a mashup of all sorts of things (and also only partial IPsec in this case).

I’d be happy to pick this up for 24.1 if ok.


Cheers,
Franco

**Comment by fichtner** [comment]
@dimitrijp Discussion is good, thanks for raising the issue 😊

**Comment by AdSchellevis** [comment]
> I’d be happy to pick this up for 24.1 if ok.

Sure, it's indeed at least more consistent and likely less code in the legacy page.

**Comment by fichtner** [comment]
@AdSchellevis it's so nice we should put it on the roadmap as a milestone ;)

**Comment by AdSchellevis** [comment]
@fichtner will do :)
