### ISSUE TITLE
Allow Us to Specify the Outgoing and Incoming Interface in Rules

### ISSUE THREAD

**Issue by skirmess** [opnsense/core#6902]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**

In the following example we will have the following interfaces:
 - WAN
 - LAN
 - GUEST
 - DMZ

We want the LAN, DMZ, and GUEST to be able to access the Internet. But neither must be able to access the LAN nor the DMZ, nor GUEST. This situation requires us to create some arcane rules that, as far as I can tell, aren't explained nor directly supported in the WUI.

For IPv4 we will create a rule on the GUEST Interface (and on DMZ) like so:

```
Action: Pass
Quick: checked
Interface: GUEST (or DMZ)
Direction: in
Source: Any
Destination / Invert: checked
Destination: RFC1918 (an alias with the RFC1918 networks)
```

For IPv6 this gets even worse because the Interfaces can contain a random network assigned by PD. And, depending on your provider, this can change from time to time. The solution I found on the forum is to (ab)use the route-to keyword of pf - but I'm unsure if that's a secure solution or just a hack that seems to work. Again, the WUI doesn't guide me to the right solution to create an "allow Internet access" rule.

**Describe the solution you like**

The suggested solution to this problem would be to allow us to specify not only the (incoming) Interface but also the outgoing Interface. The defined rule would look like this.

```
Action: Pass
Quick: checked
Interface: GUEST (or DMZ)
Direction: in
Outgoing Interface: WAN
Source: Any
Destination: Any
```

which would generate the following two rules:

```
# pppoe0 is the WAN interface. This rule blocks everything tagged with
# abcdef01234567890abcdef012345678 if it tries to exit the system on an
# interface that isn't the WAN interface
block drop out log quick on ! pppoe0 tagged "abcdef01234567890abcdef012345678"

# vlan0.10 is the guest interface. It allows everything and adds the tag
# abcdef01234567890abcdef012345678
pass in log quick on vlan0.10 inet from any to any flags S/SA keep state tag "abcdef01234567890abcdef012345678" label "f1cfa12fd466e923172927c2557b172f"
```

If we want to support multiple outgoing interfaces the rule could like like so:

```
pass out log quick on igb0 tagged "abcdef01234567890abcdef012345678"
pass out log quick on igb1 tagged "abcdef01234567890abcdef012345678"
block drop out log quick tagged "abcdef01234567890abcdef012345678"
pass in log quick on vlan0.10 inet from any to any flags S/SA keep state tag "abcdef01234567890abcdef012345678" label "f1cfa12fd466e923172927c2557b172f"
```
**Describe alternatives you considered**

I can't see any real alternative as "accessing the Internet" can't really be described in the form of IP addresses, especially if you start to consider things like multicast or other "special" IP addresses that might or might not have been defined.

What I want to express with the rule "Allow clients in the GUEST network to do whatever they want as long as they don't access my LAN or DMZ network. I don't care about addresses - I care that nothing from them leaves the Interface connected to my LAN or DMZ.

**Comment by AdSchellevis** [comment]
As far as I know you can already use `tag`, `tagged` and `direction` in our web gui (`Set local tag` / `Match local tag` under advanced).

**Comment by fichtner** [comment]
BTW, only being able to select the incoming or outgoing interface is a limitation of how the pf.conf syntax/network stack integration works.

**Comment by skirmess** [comment]
> you can already use `tag`, `tagged` and `direction` in our web gui (`Set local tag` / `Match local tag` under advanced).

You can, but you can't add a negate for the interface. Which means I would have to add a rule for every interface that isn't WAN. 

And if I add another Interface later (e.g. DMZ2) I must remember to add another block rule for that interface too. Otherwise, GUEST and DMZ have full access to DMZ2. I would prefer a solution where that is blocked, and therefore secure, by default. Also, if you mistype the tag you allow more traffic than you would like.

The "allow Internet for an interface" should be a common rule - I think it would make sense to be able to create a secure allow Internet rule with just a single rule. The end user shouldn't have to mess around with tags, in my opinion.

**Comment by skirmess** [comment]
> BTW, only being able to select the incoming or outgoing interface is a limitation of how the pf.conf syntax/network stack integration works.

You can achieve that with 2 rules using a tag. The "pass in" rule checks the incoming interface and tags the package, then a "block out" checks the outgoing interface for all packages with that tag and drops them if they would leave the firewall through the wrong interface.

```
block drop out log quick on ! pppoe0 tagged "abcdef01234567890abcdef012345678"
pass in log quick on vlan0.10 inet from any to any flags S/SA keep state tag "abcdef01234567890abcdef012345678" label "f1cfa12fd466e923172927c2557b172f"
```

**Comment by fichtner** [comment]
> You can achieve that with 2 rules using a tag. 

Huh? I Never said you couldn’t.

**Comment by AdSchellevis** [comment]
If the question is to add a negate on the floating rules, that's probably an option.

**Comment by skirmess** [comment]
> If the question is to add a negate on the floating rules, that's probably an option.

That would be really cool.

> Huh? I Never said you couldn’t.

Ah, sorry, I didn't want to imply that you said that. My feature request is that a single rule in the WUI would create a "pass in" and a corresponding "block out" rule. I think that could be quite useful and the less knobs the end user (e.g. me) has to turn, the less he can break.

**Comment by AdSchellevis** [comment]
@skirmess this https://github.com/opnsense/core/commit/be0b18930f36f9ec198c688fd0bcbdb646f7a593 should add the option to match "all but" one interface. I think we can close this issue with that addition.

**Comment by skirmess** [comment]
That makes it easy enough to home-brew Policy Filtering.

**Thank you very much!**

@AdSchellevis I assume that will first show up in 24.1?

**Comment by fichtner** [comment]
Looks ok to backport to 23.7.6 or use opnsense-patch on the commit now ;)

**Comment by AdSchellevis** [comment]
ok, let's close this then and schedule for inclusion in the next community (minor) release. This should be rather risk free.

**Comment by skirmess** [comment]
For everybody finding this ticket - this is how I intend to use this.

Create a floating rule that blocks all outgoing traffic with the tag to_WAN if the outgoing interface is not WAN.

![image](https://github.com/opnsense/core/assets/8441536/665c9f04-05ad-4203-81bb-5b2b47388bc0)

Then, for every interface that should get Internet access, create a rule like this that adds the to_WAN tag:

- The destination must be _not the firewall_, not _any_, because with _any_ you would also allow to access to the firewall. (And accessing the firewall itself does not use the out rules.)
- In pf tags are sticky, and because this rule matches all traffic from this Interface, every packet processed by this rule will get the to_WAN tag. Therefore this rule must be the last rule on this interface and every other pass rule on this interface must be quick.

![image](https://github.com/opnsense/core/assets/8441536/6faa9b3f-f569-4900-bd54-21919d6d2989)

Thank you again for this incredible fast change, @AdSchellevis !

**Comment by printerderby** [comment]
I think this solution still lacks serveral problems.
@skirmess gave a nice example, of how to use tags. This is already a hack and only works, if you have one uplink, only. But what happens, if you have a second uplink/backup interface? You can't specify a second Interface in a negated rule. 
It is quite complicated and prone to misconfiguration. The more complex your setup gets, the more you need to take care of this solution and ensure, all colleagues are on the same page/level of skill. Just forget to set a simple tag and your security drops out of the window - without knowing or realizing, as the "pass"-Part of the rule is still working and therefore nobody complains, his internet would not be working. 

TBH: Creating rules with multiple negated objects is already forbidden because of possible mis-interpretations. But all the solutions I found for the simple problem "Allow LAN-X to INTERNET", are way more complicated or too limited (e.g. not working with IPv6). 
Anything that requires separate blocking-rules, for a "pass" rule to work properly, should be seen as problem in the long run. The more VLANs/Interfaces you have, the more you need to take care and think about all the tags and what could happen in the background - you might be better of, writing the filter rules directly. I would love OpnSense to take care of this. 

Therefore I would still prefer/suggest one of two solutions:
- Allow the specification of the incoming AND outgoing interface at the same time. At least with iptables this should be possible - don't know about the BSD filter capabilities. 
- Add a "via" option that allows traffic to be selected by the gateway(s) (multiple should be working) to be used
