### ISSUE TITLE
OpenVPN: Instances [new] - proto tcp is ambiguous

### ISSUE THREAD

**Issue by rbrouwer** [opnsense/core#6904]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

When creating a TCP-OpenVPN server the following message will be logged and the OpenVPN instance will fail to start.

`Options error: --proto tcp is ambiguous in this context. Please specify --proto tcp-server or --proto tcp-client`

**To Reproduce**

1. Go to 'VPN', 'OpenVPN', 'Instances [new]'
2. Click on '+'/Add
3. Select 'Role':  'Server'
4. Select 'Protocol':  'TCP'
5. Click on 'Save'
6. See error in 'VPN', 'OpenVPN', 'Log File'

**Expected behavior**

I expect the OpenVPN server to start.

**Describe alternatives you considered**

I've search the source code find any way to set the proto tcp-server, but was unable to find any way.

**Additional context**

I believe the following line(s) should be adjusted to handle this case:
https://github.com/opnsense/core/blob/21bd623835e9dfa437a61f77a4f1531e17581e25/src/opnsense/mvc/app/models/OPNsense/OpenVPN/OpenVPN.php#L499C58-L499C58

The old instances handled it in the following section:
https://github.com/opnsense/core/blob/21bd623835e9dfa437a61f77a4f1531e17581e25/src/etc/inc/plugins.inc.d/openvpn.inc#L495C12-L495C12

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 23.7.5-amd64
FreeBSD 13.2-RELEASE-p3
OpenSSL 1.1.1w 11 Sep 2023

**Comment by AdSchellevis** [comment]
@rbrouwer what did you configure for the server (IPv4/IPv6]) option (and possibly type)? I'm not 100% sure if this is a configuration issue about a missing validation and/or a scenario we have missed. 

Looking at this, I would expect it is clear for openvpn we intend to run a server when any "server" clause is provided (which offered the tunnel), for `tap` it might still result in the same issue as no tunnel network would be provided there.

**Comment by rbrouwer** [comment]
In my case I did try to migrate my existing OpenVPN server instances to the Instances [new] section. I ran into this case when I was attempting to migrate the TAP TCP server instance, so I provided no Server IPv4/IPv6.

**Comment by AdSchellevis** [comment]
@rbrouwer thanks, just wanted to check, I'll put this on my list to fix. As I see it we need an extra validation for tun and the `-client` / `-server` option for tap.

**Comment by AdSchellevis** [comment]
@rbrouwer https://github.com/opnsense/core/commit/163a0796f72c73f5c174c183d12138c733bf19fc + https://github.com/opnsense/core/commit/997b4d6e001492ae2157057e483cfc7c4fb0f0df should fix the issue. Out of curiosity, what made you decide to use the new instances module already? I noticed the popularity, but always a bit curious about why that is.

**Comment by rbrouwer** [comment]
To be honest I was setting up OpenWrt 23.05.0-rc4 on one of my travel routers and therefore needed to be in that section and figured I could attempt get my 4 OpenVPN instances into there. I prefer to try it out earlier and rather find out issues before the server section becomes deprecated/gets removed.

That gives me time to find issues like this one I mentioned or like that one the config appears to be missing "tls-server" like the old version is doing on this line:
https://github.com/opnsense/core/blob/21bd623835e9dfa437a61f77a4f1531e17581e25/src/etc/inc/plugins.inc.d/openvpn.inc#L583

Select 'Role': 'Server'
Select 'Protocol': 'TCP'
Select 'Type': 'Tap'
Select 'Authentication': 'Local Database'
Select a 'Certificate Authority'.

I believe that gets OpenVPN to rage-quit with:
Options error: Parameter ca_file can only be specified in TLS-mode, i.e. where --tls-server or --tls-client is also specified.

But I cannot find that issue yet and you cannot reproduce that issue yet, because OpenVPN currently will rage-quit for proto being  "ambiguous in this context".
