### ISSUE TITLE
New Firewall Alias - "Categories" help text not displaying

### ISSUE THREAD

**Issue by jkoch22** [opnsense/core#6906]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [ x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [ x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

When creating a new alias in the Firewall section of the web GUI, "Categories" has an orange exclamation mark to expand the help text. The help text does not display by clicking nor by using the "Full Help" toggle.

**To Reproduce**

1. From the web interface, click on Firewall
2. Click on Aliases
3. Click on the + sign to add a new alias
4. Click on the exclamation mark next to "Categories"

**Expected behavior**

Help text should display the string from line 764 of src/opnsense/mvc/app/views/OPNsense/Firewall/alias.volt

**Describe alternatives you considered**

N/A

**Screenshots**

![image](https://github.com/opnsense/core/assets/98610758/c2c6fa12-eed9-4d36-8a6b-5544f5560c19)

**Relevant log files**

N/A

**Additional context**

N/A

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 23.7.5 (amd64, OpenSSL).

**Comment by AdSchellevis** [comment]
@jkoch22 thanks for the report, should be fixed in https://github.com/opnsense/core/commit/33e497f808ea356e0fbd39a1ac50b9ed4b401d11
