### ISSUE TITLE
Unbound DNS-Access Lists: Default Action only applies internally

### ISSUE THREAD

**Issue by Kinerg** [opnsense/core#6910]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [*] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [*] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

`Unbound DNS-Access Lists: Default Action` help states: "By default, Unbound will allow queries from all networks. Use this setting to change this behaviour."

If the option is set to "Deny", Unbound continues to allow queries from interfaces and only blocks queries from OPNsense itself.

**To Reproduce**

1. Try to resolve DNS from an allowed interface - works
2. Try to resolve DNS from OPNsense - works
3. Go to Unbound DNS: Access Lists
4. Set Default Action to Deny
5. Try to resolve DNS from any previously allowed interface - still works
6. Try to resolve DNS from OPNsense - doesn't work

**Expected behavior**

Per option description, Unbound should Deny all queries except manual exceptions entered below.

**Describe alternatives you considered**

This seems to either be a bug in the implementation or a wrong description of the option.

**Environment**

OPNsense 23.7.5-amd64
FreeBSD 13.2-RELEASE-p3
OpenSSL 1.1.1w 11 Sep 2023

**Comment by AdSchellevis** [comment]
Can you check the contents of `/var/unbound/etc/access_lists.conf` when changing the mode to deny? It is rather logical that the OPNsense machine itself can't resolve, in which case the policy would have been applied. Maybe the local machine did cache earlier results, how did you test the resolve from the client (`nslookup`)?

**Comment by Kinerg** [comment]
`access-control: 0.0.0.0/0 allow`
`access-control: ::/0 allow`
`access-control: 127.0.0.1/8 allow`
`access-control: ::1/128 allow`

vs

`access-control: 0.0.0.0/0 deny`
`access-control: ::/0 deny`
`access-control: 127.0.0.1/8 deny`
`access-control: ::1/128 deny`


Yes, I've used nslookup.

**Comment by AdSchellevis** [comment]
And the specific rules do work? you could grep for other `access-control` rules not being supplied by us in `/var/unbound/etc/`, the rules generated on our end look normal.

**Comment by Kinerg** [comment]
They seem to work. (they are to block Unifi AP requests spamming and I haven't noticed them in the log immediately) 

Hmm, checking the `/var/unbound/etc/` as you've instructed reminded me I have `access-control-view` set for some networks (that I have also been testing from) with a few
```
view-first
local-data
local-data-ptr
```
rules.

Commenting the `access-control-view` out for the specific network indeed makes the `Default Action` option apply as expected. But I thought this only affects the behavior once allowed to being queried, not if access itself is allowed or denied?

**Comment by AdSchellevis** [comment]
You probably have to read in on the upstream (unbound) documentation for that, Unbound can be complicated.

**Comment by Kinerg** [comment]
I have spent some time reading the Unbound documentation and haven't been able to determine the definite intended behavior in this scenario. It is somewhat ambiguous when it comes to `access-control-view`. Either way, intended or not, at least now I know why it behaves the way it does. Thank you for your help.
