### ISSUE TITLE
dpinger does not come up for IPv6 after interface DOWN / UP cycle

### ISSUE THREAD

**Issue by Saarbremer** [opnsense/core#6913]
**Describe the bug**

When WAN interface is disconnected and reconnected after a time (tested with > 15 secs every time) the following happens:
- dpinger for standard gateway on IPv4 goes back from stopped to running state and reports gateway's status correctly
- dpinger for standard gateway on IPv6 stays in stopped state and reports gateway down

**To Reproduce**

1. Disconnect WAN cable from OPNsense
2. Wait until both gateways go down
3. Connect WAN cable to OPNsense again

**Expected behavior**

Dpinger for IPv6 should also restore into running state automatically after an interface down condition.

**Describe alternatives you considered**

1. Situation can be solved by manually starting dpinger or perform a full reboot of the OPNsense machine. Problem occurs again after interface down. 
2. Switching off the gateway monitor could also be a possible workaorund, I guess. 

Problem for me is that WAN is connected to the ISP's router which is not under my control. It periodically reboots during the night and after that IPv6 is broken when no manual intervention is done.

**Screenshots**

**Relevant log files**

See gateways.log for dpinger 
See system.log for IF events and config

link DOWN happens at 10:28:43. The machine was rebooted just before that. 

**Additional context**

Configuration of WAN is 
for IPv4: static public IP
for IPv6: static public /64 address, a public /56 is delegated to LAN/OPT accordingly in /64 pieces
RA, DHCPv6 and DHCPv4 are not activated for WAN

WAN is a physical interface (re0) while LAN (re1) is the parent for all active interfaces implemented as VLANs on a common line. The system is a zotac zbox with Intel(R) Celeron(R) CPU N3450 @ 1.10GHz (4 cores, 4 threads) and two realtek nics. 

**Environment**

OPNsense 23.7.5-amd64
FreeBSD 13.2-RELEASE-p3
OpenSSL 1.1.1w  
11 Sep 2023

Health check: 

Currently running OPNsense 23.7.5 at Thu Oct  5 10:52:05 CEST 2023
>>> Check installed kernel version
Version 23.7.4 is correct.
>>> Check for missing or altered kernel files
No problems detected.
>>> Check installed base version
Version 23.7.4 is correct.
>>> Check for missing or altered base files
No problems detected.
>>> Check installed repositories
OPNsense
>>> Check installed plugins
os-igmp-proxy 1.5_2
os-net-snmp 1.5_2
os-ntopng 1.2_2
os-realtek-re 1.0
os-redis 1.1_2
os-theme-rebellion 1.8.8
os-theme-tukan 1.27
>>> Check locked packages
No locks found.
>>> Check for missing package dependencies
Checking all packages: .......... done
py37-markupsafe has a missing dependency: python37
py37-markupsafe has a missing dependency: py37-setuptools
py37-markupsafe is missing a required shared library: libpython3.7m.so.1.0
>>> Check for missing or altered package files
Checking all packages: .......... done
>>> Check for core packages consistency
Core package "opnsense" has 68 dependencies to check.
Checking packages: ..................................................................... done
***DONE***

[gateways.log](https://github.com/opnsense/core/files/12814562/gateways.log)
[system.log](https://github.com/opnsense/core/files/12814795/system.log)

**Comment by MCterra10** [comment]
+1 for this issue. I have noticed the same problem, in addition this also occurs after initial power up as well when the interfaces go up (though not as much of a problem at that point as I just start it after boot)
No issues with the IPv4 pinger

**Comment by fichtner** [comment]
I‘m not seeing much besides rc.linkup failing to start the monitor because the IPv6 address is missing, which is normal for dynamic IP addressing since IP addresses are stripped by rc.linkup and only put back  by dhcp6c and then picked up by rc.newwanipv6. I don’t see that in the system log snippet. Gateways log is not relevant for debugging this issue.

**Comment by fichtner** [comment]
Static seems strange to me, rc.linkup should trigger this

https://github.com/opnsense/core/blob/972a7d60bf4e16c6ed95fba40db09d0240e526e5/src/etc/inc/interfaces.inc#L2342

but maybe this is another case of DAD not being finished when the monitor is supposed to reload?

could you try adding a tunable „net.inet6.ip6.dad_count“ with value „0“ to see if that problem goes away?

**Comment by Saarbremer** [comment]
> could you try adding a tunable „net.inet6.ip6.dad_count“ with value „0“ to see if that problem goes away?

I set up a test case in virtualbox 7.0.10 with a fresh install of OPNsense and could confirm similar behaviour. 
LAN, WAN both configured statically for IPv4 + IPv6, 
LAN has Radvd sending "Assisted" while DHCPv6 serves IP Adresses

version
23.7 vanilla install (dvd version): dpinger stopped after IF down/up cycle for IPv6 GW;
with tunable dad_count = 0: dpinger came up for IPv6 GW

23.7.5 vanilla install (dvd): dpinger stopped after IF down/up cycle for IPv6 GW;
with tunable dad_count = 0: dpinger came up for IPv6 GW

Other observation - unsure if related: In 23.7 fresh install I could observe a restart of DHCPv6 in the dashboard (toggling to STOPPED and RUNNING again within seconds). In 23.7.5. I couldn't. 

So the tunable seems to work. 
Will test it in production setup tomorrow.

Thanks.

**Comment by fichtner** [comment]
Perfect. I know what to do tomorrow. You can wait for the right fix to test again. 😊

Cheers,
Franco

**Comment by fichtner** [comment]
It should work with fb336e3 without modifying the DAD counter... to test:

    # opnsense-patch fb336e3

**Comment by Saarbremer** [comment]
I tested this on the virtualbox environment. Applying the patch made dpinger for IPv6 to return as expected after IF down/up cycle; dad_count was not set as tunable. Tested also with setting dad_count to zero, same expected behaviour observed. 

After that I applied the patch with a similar result. FTR: In both cases I did a full reboot of OPNsense.

The gateway.log shows the success:
> 2023-10-09T12:16:23	Notice	dpinger	 MONITOR: ISP_WAN_GWv6 (Addr: 2a00:xxxx:xxxx:xx::1 Alarm: down -> none RTT: 0.2 ms RTTd: 0.0 ms Loss: 0.0 %)
> 2023-10-09T12:16:23	Notice	dpinger	 MONITOR: ISP_WAN_GWv4 (Addr: xx.xx.148.97 Alarm: down -> none RTT: 0.2 ms RTTd: 0.1 ms Loss: 0.0 %)
> 2023-10-09T12:16:22	Notice	dpinger	 Reloaded gateway watcher configuration on SIGHUP

Thanks. I will stick to the patch until it appears in a production version

**Comment by fichtner** [comment]
Thanks for confirming and the report 👍 I'll get this into 23.7.6 this week.

**Comment by fichtner** [comment]
We did a review of this one and the workaround is not a good solutions for when e.g. multiple VLANs are underneath. We're discussing better options, but they take a lot more time so it's not going to be in 23.7.6. I'm reusing this ticket for further work.


Cheers,
Franco
