### ISSUE TITLE
OpenVPN client overrides not updating in 23.7.5

### ISSUE THREAD

**Issue by Support-Zylon** [opnsense/core#6914]
Using the OpenVPN client overrides does not add / update the files in /var/etc/openvpn-css/1 directory.

Older entries still work but new items are not added (routes) on existing "common names" and new ones are not added.
items like:

ifocnfig-push  192.268.255.38 192.168.255.37
push "route 192.168.200.0 255.255.255.0" 

And maybe others.

New entries common name entries are not created.

**Comment by Support-Zylon** [comment]
Hi. 

I seem to have issue to locate a bug template. 

But  see issue report info needed:

Current Version: OPNsense 23.7.5-amd64
Last known version to work: OPNsens 22.x exact version unknown 

Url of gui page with issue: https://OPENSENSE/ui/openvpn/client_overwrites

Add user / common name with overrides

**Comment by Support-Zylon** [comment]
I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue 

There are maybe some relevant issues like #6870  but they have also incomplete label

**Comment by AdSchellevis** [comment]
https://github.com/opnsense/core/issues/6915
