### ISSUE TITLE
Unbound DNS aliases list not refreshed when searching for non-existent host

### ISSUE THREAD

**Issue by perlun** [opnsense/core#6920]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

Searching for non-existent Unbound DNS alias does not refresh detail list on bottom

**To Reproduce**

1. Go to https://host/ui/unbound/overrides
2. In the top-right search field, search for a DNS entry with existing aliases. The top-list shows the entry in question, and the bottom list displays the aliases
3. In the same search field, search for a bogus entry like adding `zzz` to the previous query (`foo` -> `foozzz`).
4. The top-list is cleared, but the bottom list retains the list of the aliases for the previous host you searched for.

**Expected behavior**

The top-list **and** the bottom list would be cleared in this case.

**Describe alternatives you considered**

N/A

**Screenshots**

N/A

**Relevant log files**

N/A

**Additional context**

N/A

**Environment**

OPNsense 23.7.5-amd64.
AMD EPYC 3201 8-Core Processor (8 cores, 8 threads)

**Comment by AdSchellevis** [comment]
https://github.com/opnsense/core/commit/8d71ea0f647a44eaf35f4aa442b84606e677ca75 should do the trick

**Comment by perlun** [comment]
Thanks, appreciated! :bow:
