### ISSUE TITLE
Manually set Captive Portal a limit for "Concurrent User Logins"

### ISSUE THREAD

**Issue by gomesOseias** [opnsense/core#6921]
**Important Notices**

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

- [x]  I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**

My feature request is related to the issue of concurrent user logins in the Captive Portal. While OPNsense currently allows checking the "Concurrent user logins" box to allow more than one login per user, I would like to suggest the ability to set a specific limit, such as 2 logins per user. This would enable users to log in on multiple devices (e.g., PC and cell phone) while automatically disconnecting one of the previous connections upon reaching the specified limit.

**Describe the solution you'd like**

I propose adding a feature to the Captive Portal settings that allows administrators to specify a maximum concurrent login limit per user. For example, if this limit is set to 2, a user could log in on two devices simultaneously, and any additional logins beyond this limit would automatically disconnect one of the earlier sessions.

**Describe alternatives you've considered**

Currently, the only alternative is to enable "Concurrent user logins" without a specific limit. This feature request aims to provide more fine-grained control over concurrent logins.

**Additional Context**

This feature enhancement would improve user experience and security in scenarios where multiple device logins need to be managed effectively within the Captive Portal. It would offer users greater flexibility while maintaining control over concurrent logins.

Thank you for considering this feature request.

**Comment by RemcoLeonard** [comment]
This would be a very usefull feature indeed.
