### ISSUE TITLE
UI: Virtual IP Sort by Address broken

### ISSUE THREAD

**Issue by spacerunner5** [opnsense/core#6926]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

UI: When setting up / editing virtual IPs, the address (first) column does not sort by address properly. I cannot tell if it works without IPv6 virtual IPs (aliases). But at least with IPv6 and IPv4 virtual IPs mixed, sorting results in quite a mess (looks random / unsorted).

My guess: I looks like sorting on **ID** instead of address when clicking on "address"

The error is cosmetic, but with many virtual IPs in place one can get lost pretty quickly.

**To Reproduce**

1. Go to Interfaces -> Virtual IPs -> settings
2. Click on 'Address' column to sort
3. See error described above

**Expected behavior**

Sort on IP numbers

Software version used and hardware type if relevant, e.g.:

OPNsense 23.4.2_1-amd64

tested in Browsers on MacOS:
- Safari
- Chrome

**Comment by AdSchellevis** [comment]
It's a known omission, but https://github.com/opnsense/core/commit/68139689ae51803a08db8118d1bac06fcd590f6b should fix it for a future release.

**Comment by spacerunner5** [comment]
Thank you :)
