### ISSUE TITLE
list_arp.py does not display manufacturer

### ISSUE THREAD

**Issue by gitdevmod** [opnsense/core#693]
list_arp.py does not display manufacturer because nmap is not installed by default

**Comment by fichtner** [comment]
this is intended, we don't want nmap in the default install just for a single file. we could import it, but then we need to sync regularly. I don't know what the best approach is. Any help in getting this properly addresses is helpful.

PS: this is a very history piece of code and it has always been this way

**Comment by gitdevmod** [comment]
Ok, I was browsing all menus to check translation and found this empty column.
http://www.macvendorlookup.com/api provide an api to lookup mac address

**Comment by fabianfrz** [comment]
@fichtner install nmap as a plugin?

**Comment by gitdevmod** [comment]
I submited PR #696
