### ISSUE TITLE
Cleanup: "Group Rules" display on interface rules page does not respect interface group sequence order.

### ISSUE THREAD

**Issue by bbrauchl** [opnsense/core#6933]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

When 2+ interface groups are defined containing a physical interface, "Sequence" parameter in the interface groups (ui/firewall/group) is not respected in the UI. (firewall_rules.php?if=\<ifname\>), causing UI to display a different sequence than the generated ruleset (/tmp/rules.debug)

As far as I can tell, this is related to the fact that `$this->filterRules` is sorted by priority via `public function outputFilterRules()` when the ruleset is generated, but not when iterated for the UI via `public function iterateFilterRules()`

https://github.com/opnsense/core/blob/9206823d60f90430f26415082ba8a7b52931c294/src/opnsense/mvc/app/library/OPNsense/Firewall/Plugin.php#L341C1-L352C6

However the iterate function does not sort this table:
https://github.com/opnsense/core/blob/9206823d60f90430f26415082ba8a7b52931c294/src/opnsense/mvc/app/library/OPNsense/Firewall/Plugin.php#L358C1-L365C6

As far as I can tell, the ruleset is generated in the correct order, so this issue only affects the UI

**To Reproduce**

1. Go to Firewall: groups (/ui/firewall/group)
3. Create multiple groups containing a given interface. Assign different sequence configuration to each
4. Apply changes
5. Create firewall rules in each group
6. Go to Firewall: Rules: \<ifname\> (firewall_rules.php?if=\<ifname\>)
7. Observe firewall rules are not properly ordered by group sequence UI

**Expected behavior**

Firewall "group rules" are correctly ordered in UI by group sequence

**Suggested Fix**
modification to `public function iterateFilterRules()`:
```PHP
    public function iterateFilterRules()
    {
        ksort($this->filterRules); // sort rules in the same way as outputFilterRules so ordering in UI is reflective of the generated ruleset
        foreach ($this->filterRules as $prio => $ruleset) {
            foreach ($ruleset as $rule) {
                 yield $rule;
            }
        }
    }
```

**Screenshots**

I have 2 groups defined with different sequences: g3_all_blocking and g4_ex_access
![image](https://github.com/opnsense/core/assets/10524506/92368099-e435-4bb4-af9a-b73ae22b18f9)

g3_all_blocking has the following rules:
![image](https://github.com/opnsense/core/assets/10524506/04ebfe33-00c2-498a-aace-caec1c0b04ce)

g4_ex_access has the following rule:
![image](https://github.com/opnsense/core/assets/10524506/002dba47-1cef-4299-9a68-14d1c555e45d)

However on the interface page that is stared between the two groups,
g3_all_blocking is shown _after_ g4_ex_access rules and others
![image](https://github.com/opnsense/core/assets/10524506/e7dd345e-65b5-4222-a26e-7665b284f53a)

adding `ksort` as suggested above corrects the output order:
![image](https://github.com/opnsense/core/assets/10524506/4ee8260b-beee-49b5-b213-764dc887f7c4)

**Relevant log files**

N/A

**Additional context**

N/A

**Environment**

N/A

**Comment by AdSchellevis** [comment]
@bbrauchl thanks for the report,  a key sort should indeed to the trick here (implemented in https://github.com/opnsense/core/commit/6d79f3c44dcc01be7a24f7ca6eb66ec33243f927).
