### ISSUE TITLE
User synchronization from LDAP server

### ISSUE THREAD

**Issue by nc67** [opnsense/core#6935]
Good morning,
I hope it's the right place. If it isn't, I apologize

I installed OPNsense ver. 23.7.6 and on this I configured an LDAP server (AD microsoft) and imported some users. The problem I find is that when I add a new user on the LDAP server, it does not appear in the list of users that can be imported. There seems to be no synchronization between the OPN server and the LDAP server. How could I solve the problem? Is there a command that allows me to reload the LDAP server users?
Thank you all.
Good work.
Nicholas

**Comment by matsimon** [comment]
@nc67 I guess it could be helpful to provide (anonymized) settings of the LDAP server settings. Maybe you've set the filters "to tight" so they are not found?
