### ISSUE TITLE
Can't paste list of domains to blacklist in squid

### ISSUE THREAD

**Issue by oparoz** [opnsense/core#694]
## Env

OPNsense 16.1 (15.7.99_2050)
Chrome

## Steps to reproduce

1. Go to Proxy Server -> ACL
2. Paste these domains in *Blacklist*
```
(^|\.)101com\.com$
(^|\.)101order\.com$
(^|\.)123found\.com$
(^|\.)180hits\.de$
(^|\.)180searchassistant\.com$
(^|\.)1x1rank\.com$
(^|\.)207\.net$
(^|\.)247media\.com$
```

## Expected results

The same list, with the same formatting should appear in the *Blacklist* field

## Actual result

All the domains are pasted on one line, making it unusable

I've tried different line ending formats, but it didn't work.

**Comment by oparoz** [comment]
Also, "Clear All" doesn't work

**Comment by AdSchellevis** [comment]
have you tried this :
(^|\.)101com\.com$,(^|\.)101order\.com$,(^|\.)123found\.com$,,(^|\.)180hits\.de$,(^|\.)180searchassistant\.com$,(^|\.)1x1rank\.com$,(^|\.)207\.net$,(^|\.)247media\.com$

(comma separated)

**Comment by AdSchellevis** [comment]
I tried the clear all on  15.7.25 and the current development version as well, both seem to work on my end. when you click "Clear All" is there a dialog?

**Comment by oparoz** [comment]
I've modified the list so that each item ends with a comma and that works. The form processes the input and I after a while end up with 1500 entries.
It would be great if that could work with "end of line" characters as well.

Regarding clear all, it doesn't work if the items haven't been "tokenized" (blue). So in my case, I had that one line which wasn't processed and when I clicked "yes" in the dialogue, nothing happened.

**Comment by AdSchellevis** [comment]
we choose the comma here to split the input and try to minimize changes to javascript components from others... so I'm afraid this is what it is, you can always use notepad++ to convert all \n or \n\r to commas :)

**Comment by oparoz** [comment]
OK, so maybe the related help paragraph could be slightly improved to indicate that line feed separated entries won't work? I made the assumption that because "Enter" works and because most lists simply have no delimiters, then it would be a simple copy and paste job.

**Comment by AdSchellevis** [comment]
but the help message already states this:
"TIP: You can also paste a comma separated list into this field."

**Comment by oparoz** [comment]
I missed the "Tip" section, because above the examples you have: "use a comma or press Enter for new item".
So to me it seems like both options are available.
