### ISSUE TITLE
Request windows for new items in UI to be non-modal

### ISSUE THREAD

**Issue by cookiemonsteruk** [opnsense/core#6947]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**
I would like to be able to see details of current configuration items whilst I create a new one.

**Describe the solution you like**
Please make window to create new instances of a configuration non-modal. That is a configuration box can be moved around the screen.

**Describe alternatives you considered**

No alternative currently found.

**Additional context**
For instance if I have an existing VLAN in Interfaces > Other Types > VLAN and I start creating a new one by using the + button, I am unable to move the box to see the details of the existing VLAN. I have to cancel, see, make a note physical or mental and then start again. It is the same for Virtual IPs, New ACME clients, etc. It appears all new windows are modal.
I am using version 23.1 of OPNSense.

**Comment by AdSchellevis** [comment]
I don't think you're looking for non-modal, but draggable, in which case this https://github.com/opnsense/core/commit/2f1996cc053abf844827e5e6f3c8982af2c0fb30 should do the trick.

**Comment by cookiemonsteruk** [comment]
patch applied and is perfect. Thanks @AdSchellevis

**Comment by AdSchellevis** [comment]
@cookiemonsteruk you're welcome, it is practical to have these draggable indeed, I was thinking about this recently as well, but kind of forgot about it. Thanks for the ticket. Not sure when we're going to merge it into a release, although I don't expect regressions, it might be good to keep this on the master branch for a while.
