### ISSUE TITLE
Host routes break connectivity to far gateways after upgrading from 23.7.3 to 23.7.6

### ISSUE THREAD

**Issue by baseomat** [opnsense/core#6948]
**Describe the bug**

After upgrading my secondary firewall host routes to far gateways got added:

before:
```
root@gate2:~ # netstat -rn | grep ^172.23.43
172.23.43.0/24     172.23.43.17       UGS        ixl0
172.23.43.16/29    link#3             U          ixl0
172.23.43.22       link#3             UHS         lo0
```

after:
```
root@gate2:~ # netstat -rn | grep ^172.23.43
172.23.43.0/24     172.23.43.17       UGS        ixl0
172.23.43.2        link#3             UHS        ixl0
172.23.43.6        link#3             UHS        ixl0
172.23.43.10       link#3             UHS        ixl0
172.23.43.16/29    link#3             U          ixl0
172.23.43.22       link#3             UHS         lo0
172.23.43.26       link#3             UHS        ixl0

```
Since 172.23.43.2, 172.23.43.6, 172.23.43.10 and 172.23.43.26 are far gateways, they cant be reached anymore because the host tries to reach them directly on the interface ilx0 and not via the gateway (172.23.43.17) configured for 172.23.43.0/24.

I used opnsense-revert to go back to version 23.7.3 and the host routes disappeared again.

**Expected behavior**

The host should use the configured gateway (172.23.43.17) for 172.23.43.0/24 to connect to the far gateways.
No host routes should be added for far gateways.

**Describe alternatives you considered**

I entered "Monitor IP" with ips behind the far gateway, which gets the gateway online again.
However the far gateway itself remains unreachable.

**Environment**

Software version used and hardware type:

Manufacturer: Supermicro
Product Name: X11SRM-F
Intel(R) Xeon(R) W-2245 CPU @ 3.90GHz (8 cores, 16 threads)
32G Ram
OPNsense 23.7.6-amd64
FreeBSD 13.2-RELEASE-p3
OpenSSL 1.1.1w 11 Sep 2023

**Comment by fichtner** [comment]
The far gateway settings pins the gateway to the interface and this is now consistent. Before it would only do it when a default route was added (probably those gateways are not marked default). But this is exactly what it's supposed to do.

A far gateway is not a far gateway if you have a route for it...


Cheers,
Franco

**Comment by baseomat** [comment]
Hi Franco,

thanks for the quick reply and yes the gateways are not marked default.
However if I try to uncheck "Far Gateway" i cannot save the gateway anymore:

```
The following input errors were detected:

The gateway address "172.23.43.2" does not lie within one of the chosen interface's IPv4 subnets.
```

**Comment by fichtner** [comment]
Why can’t you add a VIP to the interface in the target range? Then it works.

**Comment by baseomat** [comment]
Hi Franco,

I think that will not work in my setup. I realized that I added the four remote gateways only for monitoring the performance of the private WAN connecting them. All routing to them is done by 172.23.43.17.

I will remove them now and will setup telegraf to collect the data.

Thanks again for your quick replies!

Cheers,
André

**Comment by fichtner** [comment]
Hi André,

ok, sounds like a plan. Close this issue?


Cheers,
Franco

**Comment by baseomat** [comment]
Hi Franco,

yes please, and thank you for your support!

Cheers,
André
