### ISSUE TITLE
DHCRelay: Allow selecting interfaces without IP, differentiate between upstream and downstream interfaces

### ISSUE THREAD

**Issue by nwinkelstraeter** [opnsense/core#6949]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**

https://forum.opnsense.org/index.php?topic=36514.0

Interfaces without IPs, like tunnel interfaces, are not selectable in the DHCRelay configuration.
Therefore the dhcrelay does not listen on those interfaces and DHCP answer are on those interfaces are discarded.

Starting dhcrelay manually and adding the interface with e.g `-i ovpnc1` works fine.
I think previously there was a problem with "unsupported interface" errors, but this does not occur anymore. (https://forum.opnsense.org/index.php?topic=27814)

**Describe the solution you like**

Allow selecting all available interfaces in the dhcrelay configuration page.

Additionaly it would be nice to have two selection for upstream (-iu) and downstream (-id) (or lower and upper for v6) interfaces to make sure the relay does not accidentally send DHCP offser to the wrong interface. ( See dhcrelay man page: https://man.freebsd.org/cgi/man.cgi?query=dhcrelay&sektion=8&format=html)

**Describe alternatives you considered**

* Starting dhcrelay manually with additional options

**Comment by nwinkelstraeter** [comment]
Hi @fichtner 
I created the ticket for the dhcrelay topic here.

**Comment by fichtner** [comment]
Thanks ❤️

**Comment by fichtner** [comment]
Dumping a bit of debug info here for later.

IPv6 version supports upstream/downstream and requires an IPv6 address which the GUI enforces partially, but also not fully. Even a "none" configuration could have an alias that makes this work, same for VPN interfaces. The -u .. % if syntax is actually not link local scope.. that's part of the daemon parsing and I think it would be beneficial to allow for selection of the upstream interfaces from the GUI and they can even be omitted in IPv6...

```
# /usr/local/sbin/dhcrelay -6 -pf /var/run/dhcrelay6.pid -l igb0 -l igb2_vlan42 -l igb1 -l igb3 -u fe80::f000%igb1
parse_upstream: Interface 'igb1' is both down and up.
Internet Systems Consortium DHCP Relay Agent 4.4.3-P1
Copyright 2004-2022 Internet Systems Consortium.
All rights reserved.
For info, please visit https://www.isc.org/software/dhcp/
Bound to *:547
Listening on Socket/igb3
Sending on   Socket/igb3
Listening on Socket/igb1
Sending on   Socket/igb1
Listening on Socket/igb2_vlan42
Sending on   Socket/igb2_vlan42
Listening on Socket/igb0
Sending on   Socket/igb0
Interface 'igb3' has no IPv6 addresses.

If you think you have received this message due to a bug rather
than a configuration issue please read the section on submitting
bugs on either our web page at www.isc.org or in the README file
before submitting a bug.  These pages explain the proper
process and the information we find helpful for debugging.

exiting.
```

**Comment by fichtner** [comment]
Since we move to OpenBSD's dhcrelay I'm closing this. While interfaces without an IP address can work it's switching from layer 3 to 2 which ISC dhcrelay doesn't support this from what I understand (and it ends up with a hard error during command invoke).

**Comment by fichtner** [comment]
> Starting dhcrelay manually and adding the interface with e.g -i ovpnc1 works fine.

This may be a TAP interface which has an ethernet address?! ;)
