### ISSUE TITLE
firewall: transparent proxy rule leaks into rules page

### ISSUE THREAD

**Issue by oparoz** [opnsense/core#695]
## Env

15.7.99_2050

## Steps to reproduce

1. Go to Services -> Proxy Server
1. Click on the *Forward Proxy* tab
1. Click on *advanced mode*
1. Click on the (i) for *Enable Transparent HTTP proxy*
1. Click on *add a new firewall rule*
1. Pick an interface and save the rule
1. Go to Firewall: Rules
1. Click on the tab matching the interface chosen above
1. Edit the rule called *NAT redirect traffic to proxy*
1. Change the gateway (it's not greyed out)
1. Save

## Expected result

I should be able to save the rule

## Actual result

The Javascript validation rules get in the way, thinking that all greyed out fields are fields which have not been filled.

**Comment by fichtner** [comment]
Can you please refine the terminology and exact page names for steps 1., 2. and 3., I am unable to reproduce this with the current description.

**Comment by oparoz** [comment]
OK, I've updated the OP.

**Comment by fichtner** [comment]
Is this the error you're seeing?

    The following input errors were detected:
    The field Protocol is required.
    The field Source is required.
    The field Destination is required.
    The field Source bit count is required.
    The field Destination bit count is required.
    is not a valid source IP address or alias.
    A valid source bit count must be specified.
    is not a valid destination IP address or alias.
    A valid destination bit count must be specified.

**Comment by oparoz** [comment]
Exactly and all of these fields are filled up, but greyed out to prevent bad things to happen.

**Comment by fichtner** [comment]
Ok, it's a NAT rule and it shouldn't show up in the rules screen.

**Comment by oparoz** [comment]
OK, so it's the same rule as the Port Forward rule, but presented differently?

**Comment by fichtner** [comment]
exactly, and since it's a NAT rule it fails to save properly in the rules screen

**Comment by oparoz** [comment]
OK, thanks :+1:
