### ISSUE TITLE
URL aliases do not fetch IP addresses

### ISSUE THREAD

**Issue by ruslanbay** [opnsense/core#6952]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**To Reproduce**

1. Go to `Firewall > Aliases`
2. Create a new `URL (IPs)` alias
3. In the Content field enter: `https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/firewall/spy.txt`
4. Click `Save`
5. Click `Apply`

**Expected behavior**
On the `Firewall: Aliases` page I can see a new rule with non-zero value in the `Loaded#` column.

**Actual behavior**
No IP addresses loaded

6. Go to `Firewall: Diagnostics: Aliases`
7. Select the rule created on step 4

**Expected behavior**
The list shows fetched IP addresses

**Actual behavior**
The list is empty

8. Go to `Firewall: Rules: LAN`
9. Create a new rule
10. Action = Block; Destination = the alias we created on step 4
11. Click `Save`
12. Click `Apply`

**Actual behavior**
It doesn't fetch the IP addresses even if I have a rule that utilize the alias we created on step 4

13. Create a new rule with type `URL Table (IPs)`
14. Content: `https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/firewall/spy.txt`
15. Refresh Frequency: 0 days, 0.5 hours

**Actual behavior**
No IP addresses fetched

**Screenshots**

![image](https://github.com/opnsense/core/assets/67730802/d0ba48fa-e502-4299-a20b-b0b1961cb3d2)
![image](https://github.com/opnsense/core/assets/67730802/6e55c399-c991-4514-a7aa-f0a985ee0971)
![image](https://github.com/opnsense/core/assets/67730802/48e64623-f600-4859-ba76-b9edc7531571)
![image](https://github.com/opnsense/core/assets/67730802/909600c1-29e6-4c81-bed9-198a89ef3f1e)

**Environment**
OPNsense 23.7.6

**Comment by fichtner** [comment]
Did you apply the aliases?

**Comment by ruslanbay** [comment]
> Did you apply the aliases?

Yes, I did

**Comment by AdSchellevis** [comment]
screenshot states 30 days..... In most cases the log "Firewall: Log Files: General" helps find local configuration issues (usual dns in these cases)

**Comment by ruslanbay** [comment]
> screenshot states 30 days....

I've experimented with different intervals and with different IP lists. It can't fetch the list even when I'm using alias with type ["URL (IPs)" (not URL Table (IPs))](https://docs.opnsense.org/manual/aliases.html#alias-types).

**Comment by ruslanbay** [comment]
> In most cases the log "Firewall: Log Files: General" helps find local configuration issues (usual dns in these cases)
![image](https://github.com/opnsense/core/assets/67730802/d87b9e56-a3ca-4bcb-a10a-5157b8c31e6b)

Thanks, I'll check my DNS settings
