### ISSUE TITLE
Can't block Yandex urls using BGP ASN

### ISSUE THREAD

**Issue by ruslanbay** [opnsense/core#6953]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**To Reproduce**

1. Go to `Firewall: Aliases`
2. Create a new alias
Name: Yandex
Type: BGP ASN, IPv4+IPv6
Content: `13238` `44534` `210560`
3. Click Save
4. Click Apply
5. Go to `Firewall: Rules: LAN`
6. Create a new rule
Action: Block
Quick: checked
Interface: LAN
Direction: IN
TCP/IP Version: IPv4+IPv6
Protocol: Any
Source: Any
Destination: Yandex (the alias we created on step 4)
7. Click Save
8. Click Apply
9. Navigate to https://ya.ru or https://passport.yandex.ru/

**Expected behavior**
Web pages are not available

**Actual behavior**
The web page is accessible even though the IP address belongs to ASN13238.

I have the same exact rule for several other ASNs, but for some reason the rule doesn't work for Yandex.

https://host.io/ya.ru 
https://ipinfo.io/213.180.204.24
https://ipinfo.io/77.88.55.242
https://ipinfo.io/2a02:6b8::24

**Screenshots**
![image](https://github.com/opnsense/core/assets/67730802/7192ca2f-0273-4385-a773-3daf2c78f631)
![image](https://github.com/opnsense/core/assets/67730802/2af308b8-bd03-47f5-88e9-82f22d2f8da5)

**Environment**

OPNsense 23.7.6

**Comment by AdSchellevis** [comment]
same comment as the other ticket, to fetch ASN's, the firewall needs to be able to fetch a remote file. Often these issues relate to DNS and/or misconfigured ipv6 routing. The log files help debug your issues in these cases.

**Comment by ruslanbay** [comment]
The thing is, I have several rules for different ASNs and they all work except the rule for Yandex

**Comment by ruslanbay** [comment]
It seems like ASNs have been fetched
Date | Severity | Process | Line |  
-- | -- | -- | -- | --
2023-10-20T15:09:30 | Notice | firewall | dowloaded ASN list (1114566 entries) |  
2023-10-19T14:34:34 | Notice | firewall | dowloaded ASN list (1114803 entries) |

**Comment by AdSchellevis** [comment]
does the alias contain anything for Yandex? if not I can easily try the same on my end as well.

**Comment by ruslanbay** [comment]
Thank you Ad, I appreciate that level of support. The alias only contains three ASNs: [13238](https://ipinfo.io/13238), [44534](https://ipinfo.io/44534) and [210560](https://ipinfo.io/210560). They are all related to Yandex.

**Comment by AdSchellevis** [comment]
https://passport.yandex.ru/ resolves to `213.180.204.24` at my end, which doesn't seem to match the provided ASN's 

<img width="910" alt="image" src="https://github.com/opnsense/core/assets/9783985/7ab10e90-07c5-4158-a20c-7fbe62df18bf">


our (ipv4) source is https://thyme.apnic.net/current/data-raw-table

**Comment by ruslanbay** [comment]
> our (ipv4) source is https://thyme.apnic.net/current/data-raw-table
Thanks, It seems like there are some IP addresses missing in this list.

Is it possible to use offline packages as a ASN/GeoIP database? I can see some MaxMind packages for FreeBSD:
https://freebsd.pkgs.org/13/freebsd-amd64/libmaxminddb-1.7.1_1.pkg.html
https://freebsd.pkgs.org/13/freebsd-amd64/p5-MaxMind-DB-Reader-1.000014.pkg.html
https://freebsd.pkgs.org/13/freebsd-amd64/p5-MaxMind-DB-Reader-XS-1.000009.pkg.html

**Comment by AdSchellevis** [comment]
This is likely the entry you're looking for, not sure why it moved to `208398`
```
213.180.192.0/19        208398
```

Other packages are not supported on our end, but you can always create your own list and fetch it from there.
