### ISSUE TITLE
Adding Loopback interface dialog: Return-key does "Apply" instead of "Save"

### ISSUE THREAD

**Issue by pabe-github** [opnsense/core#6958]
**Describe the bug**

When adding a new loopback interface, pressing the return key while focusing on the dialog/textfield does not add (save) the new interface, instead it seems to trigger the Apply-Function without saving/adding the new interface

**To Reproduce**

1. Go to interfaces
2. Go to other types
3. Go to Loopback
4. Click on the +-Sign
5. Add some text to the Description-Field
6. Press the return key while the cursor is in the Decription-Field

**Expected behavior**

Pressing return should trigger the "Save" button when focusing on something in this dialog

**Screenshots**

![image](https://github.com/opnsense/core/assets/42635243/5efd225c-6622-4f01-9ebb-cb25aad8aad9)

**Environment**

OPNsense 23.7.6-amd64

**Comment by AdSchellevis** [comment]
browser problem? On my end it executes `https://x.x.x.x/api/interfaces/loopback_settings/addItem/` when you hit save, which is the proper endpint.

**Comment by pabe-github** [comment]
> browser problem? On my end it executes `https://x.x.x.x/api/interfaces/loopback_settings/addItem/` when you hit save, which is the proper endpint.

I am not clicking save. I am pressing the return key while the cursor is in the descriptionfield. This closes the dialog instead of saving

**Comment by AdSchellevis** [comment]
Ah, sounds like tab-index or something similar.

**Comment by fichtner** [comment]
Enter submits the first submit button that is declared, either in the form or worst case in the whole document.

**Comment by AdSchellevis** [comment]
It seems to be a coincidence it's doing the form submit here, other pages might do the same, but it's not very common it seems. https://github.com/opnsense/core/commit/1452683b655adcc65d43cd79859b1876619aad24 removes the submit in full (for mvc pages), I don't think any of our mvc pages should ever do a `submit`. Hooking this specifically to the input forms isn't enough as the `navbar-form` is also a form type.
