### ISSUE TITLE
IPSec ESP not decrypted via IPv6 transport

### ISSUE THREAD

**Issue by nova-2nd** [opnsense/core#6964]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

A dual stack IPSec road-warrior setup will work via IPv4 transport but not IPv6.
I verified that ESP packets arrive at the ingress interface (WAN in my case) but do not drop out of the IPSec interface.
Everything works fine for IPv4 transport...

**To Reproduce**

- Set up a road warrior IPSec (non Legacy) config
- Establish tunnel via IPv4 -> OK
- Establish tunnel via IPv6 -> ESP arrives at ingress interface but does not drop out of IPSec interface 

**Expected behavior**

Traffic flows via both protocol stacks

**Additional context**

Verified on Android (StrongSwan client) and Windows 11 (native client)
Verified for ESP and ESP in UDP
I am happy to share logs/pcap's, if it helps the cause

**Environment**

OPNSense 23.7.7_3 on KVM 
Virtio NIC's
PPPoE dial-up - Deutsche Telekom (Germany) - true dual-stack - fixed IP/Prefix

**Comment by nova-2nd** [comment]
Support?

**Comment by AdSchellevis** [comment]
can always be relabeled at a later moment in time if it appears to be a bug on our end. Most logical reason at the moment is a configuration issue, like a missing firewall rule.

**Comment by nova-2nd** [comment]
I see

**Comment by Monviech** [comment]
I will test this with my Android StrongSwan Client over IPv6.

Whats the testing baseline, did you create the RoadWarrior tunnel with the docs here? https://docs.opnsense.org/manual/how-tos/ipsec-swanctl-rw-ikev2-eap-mschapv2.html

**Comment by Monviech** [comment]
Short summary:

- It has never worked before to create an IPv6 Transport tunnel when NAT-T 4500 and UDP Encapsulation is used.
- IPv6 Transport only works directly on UDP 500 to UDP 500 as of now
- The StrongSwan IPsec Client forces the use of UDP Encapsulation, since it doesn't have the privileges to work with raw packets. 
- Strongswan doesn't allow NAT-T to be disabled. https://docs.strongswan.org/docs/5.9/features/natTraversal.html

Result:

- Android Strongswan Client + FreeBSD Strongswan implementation + IPv6 Transport with NAT-T and UDP encapsulaton = Currently not working

**Comment by Monviech** [comment]
https://forums.freebsd.org/threads/error-when-starting-up-strongswan.90468/
Freebsd-13.2 seems not to support UDP Encapsulation for IPv6.

**Comment by nova-2nd** [comment]
>     * Android Strongswan Client + FreeBSD Strongswan implementation + IPv6 Transport with NAT-T and UDP encapsulaton = Currently not working

Thank you very much for the confirmation of this.
Next time I promise to dig even deeper, to not waste the time of others

You have my respect *salute*

**Comment by fichtner** [comment]
Close for now? I'll screen the FreeBSD source code for changes in that area.

**Comment by doktornotor** [comment]
> https://forums.freebsd.org/threads/error-when-starting-up-strongswan.90468/ Freebsd-13.2 seems not to support UDP Encapsulation/Decapsulation for IPv6.

Also: https://github.com/strongswan/strongswan/issues/1759

**Comment by Monviech** [comment]
That's very interesting thanks for sharing.

**Comment by nova-2nd** [comment]
Wireguard could be an alternative on greenfield, but out in the wild there is a lot of IPSec and that won't change anytime soon...

**Comment by pfoo** [comment]
It seems like there are now patches for NAT-T / ESP-in-UDP for IPv6 in Freebsd :
https://cgit.freebsd.org/src/commit/?id=80044c785cb040a2cf73779d23f9e1e81a00c6c3
https://cgit.freebsd.org/src/commit/?id=dc02374f54455e354495870c24f86bb2966a7960

**Comment by Monviech** [comment]
@fichtner I just tested it on the testkernel and it works:

```
09:03:44.904086 IP6 2a02:XXXX:XXXX:3cfb:1410:827d:332a:8.42662 > 2003:a:XXXX:XXXX:5054:ff:fec1:44ca.4500: UDP-encap: ESP(spi=0xc0b7e393,seq=0x970), length 12
```

VPN client connects, udp encap with ipv6 is working, everything looks neat here imo.

**Comment by fichtner** [comment]
Ok let's keep the commit for the RC and see what happens 👍
