### ISSUE TITLE
Automatic rules should not include IPsec related rules when it's not enabled

### ISSUE THREAD

**Issue by oparoz** [opnsense/core#697]
In `Firewall: NAT: Outbound `, there is an automatic rule on the WAN interface for IPsec with the destination port 500. It should not exist when IPsec has not been enabled.

**Comment by AdSchellevis** [comment]
It should exist, it's not for ipsec running on the firewall itself but keeps the source port on outgoing packages using UDP port 500 on a host somewhere else.
ISAKMP is known not to handle source port changes very well.
