### ISSUE TITLE
Bug: cron page does not work and is not linked in menu

### ISSUE THREAD

**Issue by fabianfrz** [opnsense/core#698]
the page /ui/cron/ is not shown in the menu and clicking the delete button does not work (cannot remove ids update entry).

**Comment by fichtner** [comment]
It's disabled for a reason. ;) We will make it public some time during the 16.1.x series.

**Comment by AdSchellevis** [comment]
Items from other application components are locked, but can be disabled. The other component, in this case ids, still has a reference to this object.
