### ISSUE TITLE
User is not created using LDAP and Automatic user creation when User naming attribute is set to UserPrincipalName (eMail-Address)

### ISSUE THREAD

**Issue by haebi5** [opnsense/core#6980]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

I have created an LDAP access server configuration with the option "Automatic user creation" and "UserPrincipalName" which is the eMail address of the user as the "User naming attribute. The user is not being created / importe in the local user database. If I use "SAMAccountName" in the "User naming attribute", the user is created as expected.

*Tip*: to validate your setup was working with the previous version, use opnsense-revert (https://docs.opnsense.org/manual/opnsense_tools.html#opnsense-revert)

**To Reproduce**

1. Go to 'System\Access\Servers'
2. Click on 'Plus symbol to add a new server'
3. Fill out 'type (LDAP), hostname, port value, transport, protocol (3), bind credentials, search scope, base DN, Authentication containers, Extended Query, User naming attribute (UserPrincipalName), Read properties (true), Synchronize gourps (true), Automatic user creation'
4. Login to the web GUI. User will be logged in but no user object is being imported in the user database.

**Expected behavior**

A user object should be created after the first login.

**Describe alternatives you considered**

Alternatively, the user object is being created, when the "User naming attribute" is SAMAccountname instead of UserPrincipalName .

**Screenshots**

**Relevant log files**

If applicable, information from log files supporting your claim.

**Additional context**

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 23.10_2 (amd64, OpenSSL).

**Comment by AdSchellevis** [comment]
email addresses aren't supported as local usernames

**Comment by haebi5** [comment]
is it a real local user or just a proxy object referring to ldap? We do not have real local user, all users are in active directory.

**Comment by haebi5** [comment]
> email addresses aren't supported as local usernames

so, why did it fell off the fork? in pfsense it is working.

**Comment by AdSchellevis** [comment]
it didn't, we never supported email addresses for local usernames, nor does FreeBSD for that matter.

**Comment by haebi5** [comment]
It is not a local user. It is an LDAP user from active directory. And the exact same config is working on pfsense

**Comment by fichtner** [comment]
If in doubt just ask for a feature with the necessary technical background attached.

**Comment by haebi5** [comment]
> it didn't, we never supported email addresses for local usernames, nor does FreeBSD for that matter.

It's not a local user. The user is from the LDAP backend.

**Comment by haebi5** [comment]
So, no updates on this?

**Comment by haebi5** [comment]
User cannot login, when the user naming attribut in the access server is set to userprincipalname:

![image](https://github.com/opnsense/core/assets/82973352/3dd4e7f3-0769-42be-ac10-b595cb067f0a)
