### ISSUE TITLE
IPv6 route added to the wrong gateway/interface

### ISSUE THREAD

**Issue by kedare** [opnsense/core#6988]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

I am have a setup when I have PPPOE with my ISP to get dynamic a IPv4, then I connect via L2TP to another provider that gives me a fixed IPv4 and a fixed IPv6 range.

When trying to add a static route `::/0` to my IPv6 provider (Hivane), I see that it's actually added on the wrong interface `WAN` that doesn't have any IPv6 connectivity (the pppoe one)

**To Reproduce**

1. Setup an IPv4 only provider via tunnel (PPPOE here)
2. Setup a dual stack provider that depends on this tunnel (L2TP here)
3. Setup a static `::/0` using this L2TP access
4. Check the route in the route status page

**Expected behavior**

IPv6 routing should be done as expected on the L2TP tunnel (l2tp1 interface)

**Describe alternatives you considered**

Setting the static route manually via `route` works fine but is not a permanent option

```
root@ESMLG1-OPN1:~ # route -6 show ::/0
   route to: default
destination: default
       mask: default
        fib: 0
  interface: pppoe0
      flags: <UP,DONE,STATIC>
 recvpipe  sendpipe  ssthresh  rtt,msec    mtu        weight    expire
       0         0         0         0      1492         1         0
root@ESMLG1-OPN1:~ # route -6 add ::/0 -interface l2tp1
add net ::/0: gateway l2tp1 fib 0: route already in table
root@ESMLG1-OPN1:~ # route -6 delete ::/0
delete net ::/0
root@ESMLG1-OPN1:~ # route -6 add ::/0 -interface l2tp1
add net ::/0: gateway l2tp1

// Now it's working 
```

**Screenshots**

Gateways

![Screenshot 2023-11-05 at 14 45 06](https://github.com/opnsense/core/assets/359877/d2c56a53-bcde-4790-a36f-45779fd345f0)

The route configuration

![Screenshot 2023-11-05 at 14 34 16](https://github.com/opnsense/core/assets/359877/eaa82bc7-c3d6-4ef1-a3be-38b15a8dd7e1)

The effective (wrong route)
![Screenshot 2023-11-05 at 14 34 27](https://github.com/opnsense/core/assets/359877/eea51b97-cf81-4e91-b318-bf927346c3e3)

Interface assignments

![Screenshot 2023-11-05 at 14 46 46](https://github.com/opnsense/core/assets/359877/86ebeae2-a8b9-402c-bf1d-0d2e7edc5d4e)

**Relevant log files**

**Additional context**

**Environment**

Software version used and hardware type if relevant, e.g.:
OPNsense 23.7.7_3

**Comment by fichtner** [comment]
Hi @kedare,

I'm trying to reproduce but the L2TP on PPPoE is not something I can mock easily so let's try to test something together:

```
# cat test.php
<?php

require_once 'config.inc';
require_once 'interfaces.inc';
require_once 'util.inc';

var_dump(get_real_interface($argv[1]));
var_dump(get_real_interface($argv[1], 'inet6'));
```

The test script will tell us of the interface lookup is wrong. Put the script on the firewall, then execute with:

    # php -f test.php opt7


Thanks,
Franco

**Comment by kedare** [comment]
Hello @fichtner 

Thank you for your fast answer.

This is the result I get

```
kedare@ESMLG1-OPN1:~ $ php test-nic.php opt7
string(5) "l2tp1"
string(6) "pppoe0"
```

**Comment by kedare** [comment]
Also something strange, on the ifconfig, both have the `HIVANE (opt7)` description

```
l2tp1: flags=88d1<UP,POINTOPOINT,RUNNING,NOARP,SIMPLEX,MULTICAST> metric 0 mtu 1460
        description: HIVANE (opt7)
        inet6 fe80::a236:9fff:fe0f:d06c%l2tp1 prefixlen 64 scopeid 0x10
        inet6 fe80::a236:9fff:fe0f:d06d%l2tp1 prefixlen 64 scopeid 0x10
        inet 193.17.192.236 --> 193.17.192.134 netmask 0xffffffff
        nd6 options=21<PERFORMNUD,AUTO_LINKLOCAL>
kedare@ESMLG1-OPN1:~ $ ifconfig pppoe0
pppoe0: flags=88d1<UP,POINTOPOINT,RUNNING,NOARP,SIMPLEX,MULTICAST> metric 0 mtu 1492
        description: HIVANE (opt7)
        inet6 fe80::a236:9fff:fe0f:d06c%pppoe0 prefixlen 64 scopeid 0xf
        inet xx.xx.xx.xx --> xx.xx.xx.xx netmask 0xffffffff
        nd6 options=23<PERFORMNUD,ACCEPT_RTADV,AUTO_LINKLOCAL>
```

**Comment by fichtner** [comment]
I think that's the same bug. Probably able to figure this out. Give me a day to report back.

Problem here on the IPv6 device lookup:

kedare@ESMLG1-OPN1:~ $ php test-nic.php opt7
string(5) "l2tp1"
string(6) "**pppoe0**"


Thanks,
Franco

**Comment by kedare** [comment]
Great, thank you.

Let me know if you would need any more tests from me.

**Comment by fichtner** [comment]
@kedare If you go on the interface assignments at the bottom for SLAAC you will find "Use IPv4 connectivity" unchecked?. If you check that it will work most likely... I'm not entirely sure if that is the actual fix or a workaround, but I'm somewhat leaning towards "fix" at the moment. Need more coffee to process this.

**Comment by kedare** [comment]
Thank you, I confirm you it is working fine when configured this way :)

Thank you very much

**Comment by fichtner** [comment]
Ok, good. Looks like we can keep it as is. Stacking PPP devices on top of each other isn't ideal, but we also have trouble changing defaults now for whether "use IPv4" should be enabled by default or not.
