### ISSUE TITLE
IPSec EAP Radius  not working  due to incorrect strongswan.conf config file generated

### ISSUE THREAD

**Issue by scramatte** [opnsense/core#6990]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

When you pick authentication backends from  VPN > Mobile Clients > Extended Authentication (Xauth) > Backend for Authentication and save config,  the resulting  "strongswan.conf" generated file doesn't have  
"charon > plugins > eap-radius > servers  config"  details.  So IKEv2 + EAP-RADIUS stop to works 

*Tip*: to validate your setup was working with the previous version, use opnsense-revert (https://docs.opnsense.org/manual/opnsense_tools.html#opnsense-revert)

**To Reproduce**

1. Go to 'VPN > Mobile Clients > Extended Authentication (Xauth) > Backend for Authentication field'
2. Pick a backend authentication server
3. Save
4. Connect to OpnSense using SSH or console
5. cat /usr/local/etc/strongswan.conf
6. See error,  the section 'charon > plugins > eap-radius > servers' is empty 

**Expected behavior**

The strongswan.conf should be generated including the backends details 

``` 
charon {
  plugins {  
    eap-radius {
      servers {
        server-a {
          address = 127.0.0.1
          secret = R4diu5-shared-$ecreŧ
        }
      }
    }
  }
}
```

**Describe alternatives you considered**

To solve temporary the issue I've added manually a file  '/usr/local/etc/strongswan.opnsense.d/eap.conf'

```
charon {
  plugins {
    eap-radius {
      servers {
        server1 {
          address = 127.0.0.1
          secret = R4diu5-shared-$ecreŧ
        }
      }
    }
  }
}
```

**Screenshots**
![image](https://github.com/opnsense/core/assets/188766/b04ed7e7-b955-4d41-81c5-1a62c799d505)
![image](https://github.com/opnsense/core/assets/188766/9ac56781-7139-446a-b1ff-a1847576115f)
![image](https://github.com/opnsense/core/assets/188766/5f9139bf-71d5-4c23-af28-efc33491d679)

**Relevant log files**

```
<30>1 2023-11-05T19:56:27+01:00 vpn.xxx.xx charon 29297 - [meta sequenceId="61"] 14[ENC] <con1|1> parsed IKE_AUTH request 2 [ EAP/RES/ID ]
<30>1 2023-11-05T19:56:27+01:00 vpn.xxx.xx charon 29297 - [meta sequenceId="62"] 14[IKE] <con1|1> received EAP identity 'scramatte'
<30>1 2023-11-05T19:56:27+01:00 vpn.xxx.xx charon 29297 - [meta sequenceId="63"] 14[IKE] <con1|1> loading EAP_RADIUS method failed
<30>1 2023-11-05T19:56:27+01:00 vpn.xxx.xx charon 29297 - [meta sequenceId="64"] 14[ENC] <con1|1> generating IKE_AUTH response 2 [ EAP/FAIL ]
```

**Additional context**

Nothing

**Environment**

OPNsense 23.7.7_3-amd64
FreeBSD 13.2-RELEASE-p3
OpenSSL 1.1.1w 11 Sep 2023

**Comment by AdSchellevis** [comment]
looking at the ports, it does seem to find a radius server (otherwise there would be no radius section):

https://github.com/opnsense/core/blob/42256caacb61f62c681a8f20277de011b0c206a6/src/etc/inc/plugins.inc.d/ipsec.inc#L1064-L1066

but it does seem to be able to find it in the list of valid options:

https://github.com/opnsense/core/blob/42256caacb61f62c681a8f20277de011b0c206a6/src/etc/inc/plugins.inc.d/ipsec.inc#L1071-L1072


The relevant parts of the config.xml would help here (auth section without usernames/passwords) and `radius_source` value in ipsec.
