### ISSUE TITLE
Better VIP implementation (feature request)

### ISSUE THREAD

**Issue by sjorge** [opnsense/core#70]
After some back on forth with fitch on IRC, opening a feature request.

So as mentioned in a bug before, VIP's get added as an ip alias on the parent interface.
This has the side effect of having a lot of services listening on this. Although this can be prevented by using firewall rules to block traffic. This is not ideal.

Implementing VIP using vether (Not sure freebsd has this) and preventing sshd, web server, unbound,... from grabbing IP's from those would be a cleaner implementation. (This also leaves them free for other stuff to bind things on those IP's)

**Comment by fichtner** [comment]
Don't believe FreeBSD has this, sorry.
