### ISSUE TITLE
Proxy: Same filename is allowed in remote blacklist

### ISSUE THREAD

**Issue by gitdevmod** [opnsense/core#700]
We can add remote blacklist with the same filename in Proxy

**Comment by AdSchellevis** [comment]
We need some additional logic in our model system to support some more advanced constraints, we should definitely solve this, but we should fix this after https://github.com/opnsense/core/issues/272

**Comment by fichtner** [comment]
@AdSchellevis something to fix now or drop or move to 17.1?

**Comment by AdSchellevis** [comment]
@fichtner move to 17.1, model changes are still going to happen.... made a start with the unit tests, when the most scenarios are in, we can extend the model behaviour.
