### ISSUE TITLE
interfaces: regression in ULA handling on 23.7.8

### ISSUE THREAD

**Issue by galaksian** [opnsense/core#7006]
Hi all,
After upgrade to 23.7.8 from 23.7.7_3 :

radvd.conf is not generated with the info in the config.xml.
Then the radvd daemon is not starting because of the missing infos.
Seems that the same issue for dhcpdv6.conf.
It is not generated with the infos in config.xml.

Using backup file and lauching in cli works, but as soon as I try to restart via web interface all is lost...
Thanks for your support.

**Comment by fichtner** [comment]
Likely https://forum.opnsense.org/index.php?topic=36893 but no relevant information given to say for sure.

**Comment by johnnykang** [comment]
i had the same issue so i have to revert and patch the core to have the ipv6 and radad working again. Refer to the above link for info.

**Comment by fichtner** [comment]
Yep. Commit is https://github.com/opnsense/core/commit/cd808e3152 -- we are considering a hotfix but need to wait a little longer for testing to conclude.

**Comment by fichtner** [comment]
Was hotfixed in 23.7.8_1.
