### ISSUE TITLE
support Google Shared Drives for backups

### ISSUE THREAD

**Issue by mimizone** [opnsense/core#7008]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**

Using a Google Shared Drive (such as a Google Workspace Shared Drive in a company) for the System Configuration backup doesn't work.

**Describe the solution you like**

The Google API requires to add the `supportsAllDrives=true` to the API calls.
https://developers.google.com/drive/api/guides/enable-shareddrives 

Which is not set in the current OPNsense code.
See here for instance: https://github.com/opnsense/core/blob/22f939bb8df2d116a5a709a5f952cb59e5c7a778/src/opnsense/mvc/app/library/Google/API/Drive.php#L100

maybe something along those lines? (similar on each call)
```
return $this->service->files->listFiles(array('q' => $query, 'supportsAllDrives' => true ));
```

**Comment by mimizone** [comment]
https://github.com/opnsense/core/pull/7009

**Comment by AdSchellevis** [comment]
@mimizone can you try https://github.com/opnsense/core/commit/29215763026b7a1f4fa33a6d2cdd9c3fade8bed2 ? your commit had a typo, fixed some small styling issues while there as well. As far as I could find there are no downsides to always supplying `supportsAllDrives`, my gdrive still works after this patch.

**Comment by mimizone** [comment]
works for me on `23.7.7_1-amd64`
