### ISSUE TITLE
Support for Unbound RPZs

### ISSUE THREAD

**Issue by RomanHargrave** [opnsense/core#7010]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**

I would like to configure RPZs in Unbound; however, there is no means by which I may do so, because it is not possible to enable `respip` (which is required) without also enabling "AAAA-only mode" _and_ DNS64 simultaneously. I would not like to enable AAAA-only mode. Placing a configuration file with a differing `module-config` into `unbound.opnsense.d` has no apparent effect.

**Describe the solution you like**

I would simply like to be able to prepend the `respip` module to `server.module-config` ***without*** [enabling `noarecords`](https://github.com/opnsense/core/blob/22f939bb8df2d116a5a709a5f952cb59e5c7a778/src/etc/inc/plugins.inc.d/unbound.inc#L156-L159), so that I may place my RPZ configuration in to `unbound.opnsense.d` and have it work. This could be as simple as adding an "Enable RPZs" option to the advanced unbound configuration.

A more general audience might like to be able [configure RPZs](https://unbound.docs.nlnetlabs.nl/en/latest/topics/filtering/rpz.html) from the user interface.

**Comment by RomanHargrave** [comment]
Disregard, I had initially tested this improperly and it does work.

**Comment by UnderEu** [comment]
@RomanHargrave How did you manage to fix your issue? I'm trying to add a RPZ policy in my own box and it's giving me the exact error you reported.
