### ISSUE TITLE
Wireguard CARP awareness

### ISSUE THREAD

**Issue by raspitoaster** [opnsense/core#7013]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

OPNsense docs claim that _"both High Availability firewalls will send handshakes and fight against each other for the remote Wireguard peer. This behavior was mitigated in 23.7.6 with Wireguard CARP vhid tracking that disables the Wireguard Instance with CARP VIPs in Backup state."_
I tried all "Master with wireguard service enabled and wireguard instance enabled" with all combinations of starting points on the backup node: wireguard service enabled, wireguard instance enabled, wireguard service disabled, wireguard instance disabled.
The result is always the same: when clicking on "Enter Persistent CARP Maintenance Mode", then wireguard does not change.

**To Reproduce**
On MASTER and BACKUP node:
goto VPN - WIREGUARD - SETTINGS
edit WIREGUARD INSTANCE to Depend on (CARP) => select one of the CARP entries from the pulldown

On MASTER node:
goto INTERFACES - VIRTUAL IPs - STATUS => click on "Enter Persistent CARP Maintenance Mode"

On MASTER and BACKUP node:
Check CARP and wireguard status
=> On MASTER node : CARP will switch from Master to Backup, **wireguard service and instance is still up**.
=> On BACKUP node : CARP will switch from Backup to Master, **"No WireGuard instance defined or enabled"**.

**Expected behavior**

On MASTER node:
goto INTERFACES - VIRTUAL IPs - STATUS => click on "Enter Persistent CARP Maintenance Mode"

On MASTER and BACKUP node:
Check CARP and wireguard status
=> On MASTER node : CARP should switch from Master to Backup, **wireguard instance should be disabled**
=> On BACKUP node : CARP should switch from Backup to Master, **wireguard instance should be enabled**.

**Comment by AdSchellevis** [comment]
VPN: WireGuard: Diagnostics --> status ??

**Comment by raspitoaster** [comment]
**Master node=Master, Backup node=Backup:**
on Master node:
![image](https://github.com/opnsense/core/assets/4280150/fe2a33b7-e6f1-4d24-bfd3-6104b6057f04)

on Backup node:
![image](https://github.com/opnsense/core/assets/4280150/bf793b61-2dd9-4079-9844-db7bb5f759fc)

now clicking "Enter Persistent CARP Maintenance Mode"
**Master node=Backup, Backup node=Master:**
on Master node:
![image](https://github.com/opnsense/core/assets/4280150/3a556734-0474-488b-a114-7dfa4f9dfa2c)

on Backup node:
![image](https://github.com/opnsense/core/assets/4280150/fd39189a-28ac-4819-9d40-39f9c9eb939b)

Lobby looks like this:

On Master node (in CARP backup mode)
![image](https://github.com/opnsense/core/assets/4280150/31779080-77bd-4d5c-9c4c-5b2fd5fd2520)

On Backup node (in CARP master mode)
![image](https://github.com/opnsense/core/assets/4280150/ee67f3c6-b406-4de3-b0e2-ae6b39a08018)

**Comment by AdSchellevis** [comment]
widget broken? I'm not sure what we're looking at there, the status looks proper so a functional issue is likely not the case here.

**Comment by raspitoaster** [comment]
The status does **not** look proper because there is no interface and no status for wireguard (in VPN - WIREGUARD - DIAGNOSTICS and in the LOBBY) on the backup node after switching CARPs from master node to backup node.
The status on the master node is shown as "down" and although the connections (peers) are still shown in the lists (in VPN - WIREGUARD - DIAGNOSTICS and in the LOBBY), there is no more traffic and the "last connected" times are frozen.

Switching CARPs back from backup node to master node, the master node is shown as up and the "last connected" times start updating.
 So on master everything is ok, but on backup node wireguard is never active.

**Comment by raspitoaster** [comment]
Both nodes have been updated yesterday to OPNsense 23.7.8_1-amd64 (this is why I noticed that the wireguard integration got improved).

Stupid me - not looked into the logfiles.
Logfiles on both systems show errors:

/usr/local/opnsense/scripts/Wireguard/wg-service-control.php: The command '/usr/bin/wg setconf 'wg1' '/usr/local/etc/wireguard/wg1.conf'' returned exit code '1', the output was 'fopen: No such file or directory'

BUT:
'/usr/bin/wg' exists
'/usr/local/etc/wireguard/wg1.conf' exists
running the command /usr/bin/wg setconf 'wg1' '/usr/local/etc/wireguard/wg1.conf' in a shell also does not return any error.

**Comment by raspitoaster** [comment]
Both nodes have been updated yesterday to OPNsense 23.7.8_1-amd64 (this is why I noticed that the wireguard integration got improved).

Logfiles on both systems show no recent entries or even errors - but there are several lines on both systems some days old with:

/usr/local/opnsense/scripts/Wireguard/wg-service-control.php: The command '/usr/bin/wg setconf 'wg1' '/usr/local/etc/wireguard/wg1.conf'' returned exit code '1', the output was 'fopen: No such file or directory'

BUT:
'/usr/bin/wg' exists
'/usr/local/etc/wireguard/wg1.conf' exists
running the command /usr/bin/wg setconf 'wg1' '/usr/local/etc/wireguard/wg1.conf' in a shell also does not return any error.

**Comment by fichtner** [comment]
"setconf" is no longer used on 23.7.8 as far as I'm aware.

**Comment by nzkiwi68** [comment]
Confirm:

1. You are running the latest firmware for OPNsense 23.7.8_1


2. Under:
VPN > WireGuard > Settings 
each and every instance, you have enabled "Depend on (CARP)"  and have used the dropdown box to follow a CARP interface.
![Depend of CARP](https://github.com/opnsense/core/assets/67399588/ff2d53af-2b73-4353-858c-4192ed83c2d8)

**Comment by raspitoaster** [comment]
I confirm this.

when entering CARP maintenance mode I get the error messages in log:

master node:
2023-11-21T21:39:57 | Notice | wireguard | Wireguard configure event instance XXXXXX (wg1) vhid: 116 carp: BACKUP interface: up

backup node:
2023-11-21T21:39:54	Notice	wireguard	/usr/local/opnsense/scripts/Wireguard/wg-service-control.php: ROUTING: entering configure using 'opt4'	
2023-11-21T21:39:54	Notice	wireguard	wireguard instance XXXXXX (wg1) started	
2023-11-21T21:39:54	Error	wireguard	/usr/local/opnsense/scripts/Wireguard/wg-service-control.php: The command '/usr/bin/wg syncconf 'wg1' '/usr/local/etc/wireguard/wg1.conf'' returned exit code '1', the output was 'fopen: No such file or directory'	
2023-11-21T21:39:54	Notice	wireguard	wireguard instance XXXXXX (wg1) stopped	
2023-11-21T21:39:54	Notice	wireguard	wireguard instance XXXXXX (wg1) can not reconfigure without stopping it first.	
2023-11-21T21:39:54	Notice	wireguard	Wireguard configure event instance XXXXXX (wg1) vhid: 116 carp: MASTER interface: -

leaving CARP maintenance mode I get the error messages in log:

Master node:
2023-11-21T21:47:34 | Notice | wireguard | Wireguard configure event instance XXXXXX (wg1) vhid: 116 carp: MASTER interface: down

Backup node:
2023-11-21T21:47:33	Notice	wireguard	Wireguard configure event instance XXXXXX (wg1) vhid: 116 carp: BACKUP interface: up

**Comment by AdSchellevis** [comment]
```
2023-11-21T21:39:54 Error wireguard /usr/local/opnsense/scripts/Wireguard/wg-service-control.php: The command '/usr/bin/wg syncconf 'wg1' '/usr/local/etc/wireguard/wg1.conf'' returned exit code '1', the output was 'fopen: No such file or directory'
```

suggests there is no configuration for the tunnel in question in `/usr/local/etc/wireguard/*.conf`, forgot to apply settings on the backup?

**Comment by raspitoaster** [comment]
Strange! 

Web interface on master and backup node show the wireguard service as active and the wireguard instance as active.
There is a configuration visible on both nodes, but:
looking in the directory you suggested, there was indeed the config file for the wireguard instance missing on the backup node.
I checked the already checked checkboxes for the wireguard service and the wireguard instance and then the file was there.

Now when I enter CARP maintenance mode, everything looks fine.
(lastest handshake stall on master node and update every cycle on backup node)
Switch back also works (despite a little problem that CARP throws an error and I need to click again to enter CARP maintenance mode and then I can click leave CARP maintenance mode).

Thank you!


before:
root@fw-002:~ # cd /usr/local/etc/wireguard/
root@fw-002:/usr/local/etc/wireguard # ls -la
total 12
drwx------   2 root  wheel   512 Nov 21 21:39 .
drwxr-xr-x  40 root  wheel  4096 Nov 15 22:00 ..
-rw-r-----   1 root  wheel    33 Nov 21 21:39 wg1.stat


after:
root@fw-002:/usr/local/etc/wireguard # ls -la
total 16
drwx------   2 root  wheel   512 Nov 22 09:39 .
drwxr-xr-x  40 root  wheel  4096 Nov 15 22:00 ..
-rw-------   1 root  wheel  2256 Nov 22 09:39 wg1.conf
-rw-r-----   1 root  wheel    65 Nov 22 09:39 wg1.stat
root@fw-002:/usr/local/etc/wireguard #

**Comment by raspitoaster** [comment]
Summary: issue was caused by missing config file on the backup node
