### ISSUE TITLE
API - TrafficShaping: flushreload

### ISSUE THREAD

**Issue by gravitytechau** [opnsense/core#7014]
G'day,

As detailed here: https://forum.opnsense.org/index.php?topic=36472.msg178089 I'm trying to use the OPNSense API to enable/disable Traffic Shaping rules. Before I make a bug about this not working, I thought I'd bring the question here to ensure I haven't got the wrong end of the functionality stick on `flushreload` (/api/trafficshaper/service/flushreload) as the forum post has gone a month with no response.

Both the reading & toggling of the rule's active state is successful via the API, but `flushreload` doesn't apply them to the functioning rules. (What I really need amounts to the "Apply" button in the GUI.)

So, questions! 

1. As implied above - is `flushreload` intended to give me the functionality I'm hoping for. 
2. If not, what should I be using to enact the change?
3. Is there some other API call that will suffice if this one isn't functional?

As far as testing goes, I haven't rebooted the system to see if that also applies the change, but as noted in the forum post, pressing Apply on the GUI page does.

Thanks in advance for your help/clarification.

**Comment by AdSchellevis** [comment]
The trick to find the correct endpoint usually is to check the browser network inspector, hitting apply calls : `/api/trafficshaper/service/reconfigure`

**Comment by gravitytechau** [comment]
Ah! The data-endpoint attribute on the Apply button! I had looked for forms and the JS event, but I didn't notice that. 

... how didn't I notice that? \*cleans glasses furiously\*

I will test.

**Comment by gravitytechau** [comment]
Ok, Good News Everybody (.jpg), that has achieved my goal. So it wasn't a bug, it was a lack of understanding (documentation?) of the ServiceController commands.

Was there a section in the documentation I missed detailing what we've found here?

Will update the Forum post to reflect the solution.

**Comment by AdSchellevis** [comment]
We don't detail endpoints as this means a lot of "double documenting" with the risk of getting out of sync, since usage is easy to find, that's usually the fastest anyway. The number of unused endpoints on our end is very low.

**Comment by gravitytechau** [comment]
That's totally understandable. Given the nature of the project and the number of people involved.

Is there anywhere in the preamble to the API that notes how to find endpoints as you noted above for this case? (if not, then that'd probably be helpful.)

**Comment by AdSchellevis** [comment]
I've checked the docs, but I don't think the simple trick is explained somewhere at the moment, we might consider adding it to https://docs.opnsense.org/development/api.html as that's likely the first place people will look for it.

**Comment by gravitytechau** [comment]
Good idea. 

Hopefully people will actually _read_ that section in full ;)

**Comment by AdSchellevis** [comment]
well, at least we can point them to there 🙃 this https://github.com/opnsense/docs/commit/ea8d486124f912d4f1e6637145a6dce00bf63197 should help.
