### ISSUE TITLE
firewall: empty "proto" selection on GeoIP alias

### ISSUE THREAD

**Issue by fichtner** [opnsense/core#7016]
**Important notices**

Our forum is located at https://forum.opnsense.org , please consider joining discussions there in stead of using GitHub for these matters.

Before you ask a new question, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

Not sure how it should be handled, but looking at the way the GUI is set up I'd say prevent storing an empty value via validation?

**Comment by AdSchellevis** [comment]
Empty is treated as both as it emits it from the `filter_tables.conf`, adding a validation would be ok, but as it depends on type, is a bit annoying.

**Comment by fichtner** [comment]
In that case I can just mock "IPv4, IPv6" as the empty selection title then :)
