### ISSUE TITLE
OpenVPN: Please add Data Channel Offload (DCO) support w/ FreeBSD 14

### ISSUE THREAD

**Issue by cs-1** [opnsense/core#7020]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**

OpenVPN is known for its mediocre throughput performance even on high end hardware.

**Describe the solution you like**

Current OpenVPN server versions starting with 2.6 support a feature called "Data Channel Offload" (DCO) which significantly increases the throughput by offloading data processing from user to kernel space. To make this work, a kernel module is need which is included in FreeBSD 14. We found that the throughput performance can be increased by as much as 2-3x compared to non-DCO OpenVPN. My request is to please include DCO support in OpenVPN and to use the DCO FreeBSD kernel module when moving OPNsense to the FreeBSD 14 base.

**Describe alternatives you considered**

There're no alternative solutions to increase performance as much as DCO does.

**Additional context**

https://community.openvpn.net/openvpn/wiki/DataChannelOffload/NonLinuxPlatforms
https://reviews.freebsd.org/D34340

**Comment by cs-1** [comment]
@fichtner Quick question so that I understand the "upstream" label: does OPNsense use FreeBSD's openvpn package and therefore the FreeBSD maintainers need to compile it with DCO support?

**Comment by fichtner** [comment]
This depends on FreeBSD 14, which we will be targeting as 14.1. I haven't seen the DCO parts being backported to 13.x.

**Comment by cs-1** [comment]
Makes sense. I just wanted to raise "DCO awareness" because the speed gain is significant. :) Thanks for the clarification.

**Comment by fichtner** [comment]
#7474
