### ISSUE TITLE
Nat reflection not working as it should

### ISSUE THREAD

**Issue by oculos** [opnsense/core#7022]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

Obs: My issue is similar to this one: https://github.com/opnsense/core/issues/6650, but not quite the same.

**Describe the bug**

I have a setup where I have port forwarding setup for port 443 to my reverse proxy on one of my vlans. I use NAT reflection, and I never noticed this problem until today.

The thing is that when my host send a request to the port 443 my WAN address, half of the time I get the request, half of the time I get connection refused.

It goes like this:

✘ francis@nginx $ curl https://auth.mydomain.com/realms/mydomain/account #works
 francis@nginx $ curl https://auth.mydomain.com/realms/mydomain/account
curl: (7) Failed to connect to auth.mydomain.com port 443: Connection refused
 ✘ francis@nginx $ curl https://auth.mydomain.com/realms/mydomain/account # works
 francis@nginx $ curl https://auth.mydomain.com/realms/mydomain/account
curl: (7) Failed to connect to auth.mydomain.com port 443: Connection refused
 ✘ francis@nginx $ curl https://auth.mydomain.com/realms/mydomain/account #works
 francis@nginx $ curl https://auth.mydomain.com/realms/mydomain/account
curl: (7) Failed to connect to auth.mydomain.com port 443: Connection refused
 ✘ francis@nginx $ curl https://auth.mydomain.com/realms/mydomain/account # works

Basically, every other request goes through.
When the connection is refused, I see a blue line log on firewall where the label says "rdr rule".

I have:

- deleted and recreated the port forwarding rule;
 access from another host on the same vlan: same problem
- use another server instead of nginx, on another port: same problem
- disable nat reflector on the 443 port forwarding: no traffic from my vlan goes through, only external traffic.

1. enable Nat reflection
2. create a port forward rule to a host on a vlan - use port 5000 for example
3. install a little server or use `python -m http.server 5000
4. on the same or another host on that vlan, try `curl http://wanaddress:5000 multiple times

**Expected behavior**

All traffic should go through. Pings do go through.

**Describe alternatives you considered**

I tried to locally add the host I tried to reach on my `/etc/hosts` file, and it worked, as traffic no longer leaves the vlan. But this is not ideal.

Software version used and hardware type if relevant, e.g.:

OPNsense 23.7.8 (amd64), though the bug was consistent accross 23.1 to 23.7.8. I know because I upgraded three times today to get up to the latest version. Between every upgrade, I tested.

**Comment by AdSchellevis** [comment]
https://docs.opnsense.org/manual/how-tos/nat_reflection.html

**Comment by doktornotor** [comment]
OK, let's have a look.

`igb0 `= WAN (IP: `1.2.3.4`, GW: `1.2.3.5`)
`igb1` = LAN (IP: `10.0.0.1`, LAN subnet: `10.0.0.0/24`)
`ManagementAccess` = an alias (allowed IPs, subnets)
`10.0.0.101`: RDP server on LAN

### **OPNsense:** (NAT reflection broken)

Relevant part of `/tmp/rules.debug`
```
rdr on igb0 inet proto {tcp udp} from $ManagementAccess to {(igb0)} port {3389} -> 10.0.0.101 port 3389
nat on igb0 inet proto {tcp udp} from (igb0:network) to {10.0.0.101} port {3389} -> (igb0) port 1024:65535
rdr on lo0 inet proto {tcp udp} from $ManagementAccess to {(igb0)} port {3389} -> 10.0.0.101 port 3389 # RDP Access
nat on lo0 inet proto {tcp udp} from (lo0:network) to {10.0.0.101} port {3389} -> (lo0) port 1024:65535 # RDP Access
rdr on igb1 inet proto {tcp udp} from $ManagementAccess to {(igb0)} port {3389} -> 10.0.0.101 port 3389 # RDP Access
nat on igb1 inet proto {tcp udp} from (igb1:network) to {10.0.0.101} port {3389} -> (igb1) port 1024:65535 # RDP Access
pass in quick on igb0 reply-to ( igb0 1.2.3.5 ) inet proto {tcp udp} from $ManagementAccess to {10.0.0.101} port {3389} keep state label "b57873a2d1d45a6119a0850bdadd4468" # RDP Access
```

**Resulting ruleset** 
- the NAT part, checked with `# pfctl -vv -s nat | grep ms-wbt-server`
```
@39 nat on igb0 inet proto tcp from (igb0:network:1) to 10.0.0.101 port = ms-wbt-server -> (igb0) port 1024:65535 round-robin
@40 nat on igb0 inet proto udp from (igb0:network:1) to 10.0.0.101 port = ms-wbt-server -> (igb0) port 1024:65535 round-robin
@41 nat on lo0 inet proto tcp from (lo0:network:1) to 10.0.0.101 port = ms-wbt-server -> (lo0) port 1024:65535 round-robin
@42 nat on lo0 inet proto udp from (lo0:network:1) to 10.0.0.101 port = ms-wbt-server -> (lo0) port 1024:65535 round-robin
@43 nat on igb1 inet proto tcp from (igb1:network:1) to 10.0.0.101 port = ms-wbt-server -> (igb1) port 1024:65535 round-robin
@44 nat on igb1 inet proto udp from (igb1:network:1) to 10.0.0.101 port = ms-wbt-server -> (igb1) port 1024:65535 round-robin
@45 rdr on igb0 inet proto tcp from <ManagementAccess:3> to (igb0:1) port = ms-wbt-server -> 10.0.0.101 port 3389
@46 rdr on igb0 inet proto udp from <ManagementAccess:3> to (igb0:1) port = ms-wbt-server -> 10.0.0.101 port 3389
@47 rdr on lo0 inet proto tcp from <ManagementAccess:3> to (igb0:1) port = ms-wbt-server -> 10.0.0.101 port 3389
@48 rdr on lo0 inet proto udp from <ManagementAccess:3> to (igb0:1) port = ms-wbt-server -> 10.0.0.101 port 3389
@49 rdr on igb1 inet proto tcp from <ManagementAccess:3> to (igb0:1) port = ms-wbt-server -> 10.0.0.101 port 3389
@50 rdr on igb1 inet proto udp from <ManagementAccess:3> to (igb0:1) port = ms-wbt-server -> 10.0.0.101 port 3389

```

The 39+40 rules makes no sense whatsoever. Why's the loopback interface there, also no idea. 

- the rules part, checked with `# pfctl -vv -sr | grep ms-wbt-server`
```
@213 pass in quick on igb0 reply-to (igb0 1.2.3.5) inet proto tcp from <ManagementAccess:3> to 10.0.0.101 port = ms-wbt-server flags S/SA keep state label "b57873a2d1d45a6119a0850bdadd4468"
@214 pass in quick on igb0 reply-to (igb0 1.2.3.5) inet proto udp from <ManagementAccess:3> to 10.0.0.101 port = ms-wbt-server keep state label "b57873a2d1d45a6119a0850bdadd4468"

```

### **The _other_ project:** (NAT reflection working)

Relevant part of `/tmp/rules.debug`
```
rdr on igb0 inet proto { tcp udp } from $ManagementAccess to 1.2.3.4 port 3389 -> 10.0.0.101
# Reflection redirect
rdr on { igb1 openvpn WireGuard } inet proto { tcp udp } from $ManagementAccess to 1.2.3.4 port 3389 -> 10.0.0.101
nat on igb1 proto { tcp udp } from 10.0.0.0/24 to 10.0.0.101 port 3389 -> 10.0.0.254 port 1024:65535
pass  in  quick  on $WAN reply-to ( igb0 1.2.3.5 ) inet proto { tcp udp }  from $ManagementAccess to 10.0.0.101 port 3389 ridentifier 1418935306 keep state label "USER_RULE: NAT RDP Access" label "id:1418935306"
```

**Resulting ruleset** 

- the NAT part, checked with `# pfctl -vv -s nat | grep ms-wbt-server`
```
@25 nat on igb1 inet proto tcp from 10.0.0.0/24 to 10.0.0.101 port = ms-wbt-server -> 10.0.0.1 port 1024:65535
@26 nat on igb1 inet proto udp from 10.0.0.0/24 to 10.0.0.101 port = ms-wbt-server -> 10.0.0.1 port 1024:65535
@116 rdr on igb0 inet proto tcp from <ManagementAccess:3> to 1.2.3.4 port = ms-wbt-server -> 10.0.0.101
@117 rdr on igb0 inet proto udp from <ManagementAccess:3> to 1.2.3.4 port = ms-wbt-server -> 10.0.0.101
@118 rdr on igb1 inet proto tcp from <ManagementAccess:3> to 1.2.3.4 port = ms-wbt-server -> 10.0.0.101
@119 rdr on igb1 inet proto udp from <ManagementAccess:3> to 1.2.3.4 port = ms-wbt-server -> 10.0.0.101
@120 rdr on openvpn inet proto tcp from <ManagementAccess:3> to 1.2.3.4 port = ms-wbt-server -> 10.0.0.101
@121 rdr on openvpn inet proto udp from <ManagementAccess:3> to 1.2.3.4 port = ms-wbt-server -> 10.0.0.101
@122 rdr on WireGuard inet proto tcp from <ManagementAccess:3> to 1.2.3.4 port = ms-wbt-server -> 10.0.0.101
@123 rdr on WireGuard inet proto udp from <ManagementAccess:3> to 1.2.3.4 port = ms-wbt-server -> 10.0.0.101
```

- the rules part, checked with `# pfctl -vv -sr | grep ms-wbt-server`
```
@253 pass in quick on igb0 reply-to (igb0 1.2.3.5) inet proto tcp from <ManagementAccess:3> to 10.0.0.101 port = ms-wbt-server flags S/SA keep state label "USER_RULE: NAT RDP Access" label "id:1418935306" ridentifier 1418935306
@254 pass in quick on igb0 reply-to (igb0 1.2.3.5) inet proto udp from <ManagementAccess:3> to 10.0.0.101 port = ms-wbt-server keep state label "USER_RULE: RDP Access" label "id:1418935306" ridentifier 1418935306
```

I'd say the very obvious differences between broken and working are:
- first apply **all** `nat`, do `rdr` later
- do **not** NAT on WAN (and on loopback, for completeness sake]

Other notable differences:
- the NAT reflection is being done on OpenVPN and Wireguard groups as well on the *other* project.
