### ISSUE TITLE
Infiniband lagg type support

### ISSUE THREAD

**Issue by Gouster4** [opnsense/core#7025]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [ x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [ x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**

Infiniband (ipoib) isnt supported by default. But after installing required kernel modules, infiniband and ipoib are working as per-port standalone interface.

But i cannot create infiniband lagg type.
Once i put infiniband interfaces inside lagg, it is not working.

LAGG Statistics active ports:0
flapping:0

I installed infiniband modules by temporary enabling freebsd repo, then installed auto-admin package,
and then used this command:
"auto-install-infiniband-modules datagram"
Which installed infiniband and ipoib modules with datagram mode.
I tried also connected mode, but mtu was limited to 2044 exactly like datagram mode limitation, so i think it installed modules with datagram mode anyways. But to be sure, i removed modules and installed them rather in datagram mode, just to be sure which mode is used, as i dont know how to check it.

**Describe the solution you like**

I dont know how OPNSense handles interfaces, but if freebsd network management is used, then "infiniband" checkbox in lagg settings can use this:
"ifconfig lagg0 create laggtype infiniband"
instead of just this:
"ifconfig lagg0 create"

This way, lagg would be set to infiniband type, when user uses checkbox (maybe hidden inside advanced settings)

Afaik, infiniband doesnt support some lagg types, but roundrobin and failover should be possible, so it would be nice if non-possible modes would be hidden since infiniband checkbox is checked in lagg settings.

Also, bundlung infiniband support (kernel modules) with opnsense would be great, but its not preventing ipoib from working, as those can be compiled by user, and loaded.

**Describe alternatives you considered**

Currently idont use failover, and have just one port active, because i cannot get lagg working with ipoib.

**Comment by AdSchellevis** [comment]
Took a brief look, but unfortunately it's not very easy to implement on our end as it needs quite some additional validations and only works when `laggtype` is specified on initial creation (all other attributes are changeable without removing the device node).
