### ISSUE TITLE
VPN: OpenVPN: Instances Client config doesn't contain "nobind"

### ISSUE THREAD

**Issue by werty1st** [opnsense/core#7028]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

A client instance doesn't start because it tries to bind to Port 1194 which in my case is used by a legacy server config.

The Help Text describes:

> Portnumber to use, defaults to 1194 when in server role, nobind for clients

The generated config lacks the "nobind" option. thus tries to bind to 1194 and fails.

*Tip*: to validate your setup was working with the previous version, use opnsense-revert (https://docs.opnsense.org/manual/opnsense_tools.html#opnsense-revert)

**To Reproduce**

1. occupy port 1194 on the selected interface (wan).
2. create a new client instance. leave port setting empty
3. start the client instace and watch it fail.

**Expected behavior**

the config should contain the nobind option to make the client allocate a random, available port.

**Describe alternatives you considered**

add nobind manually. but the instance interface doesn't allow that. i switched back to the "legacy" setup.

**Environment**

Software version used and hardware type if relevant, e.g.:

latest version from 2023-11-21

**Comment by werty1st** [comment]
Yes it's my fault. I just read the openvpn manual again and this time a saw that it doesn't bind to interface and port. sorry maybe i was to tried yesterday.😅

**Comment by AdSchellevis** [comment]
no problem, it might make sense to change the label anyway
