### ISSUE TITLE
Missing 0 and 1

### ISSUE THREAD

**Issue by IAmAStealer** [opnsense/core#7029]
https://github.com/opnsense/core/blob/99fcbaf93345b8c08bd60a67c9aa9014c3fbf89c/src/opnsense/mvc/app/library/OPNsense/Auth/Voucher.php#L199C6-L199C6

Hello, is it me or there is a problem regarding the character map excluding 0 and 1 ?
Also, I'm not a PHP professional but isn't a const ALPHA_NUM that exists for there cases ?

Regards,

**Comment by fichtner** [comment]
Becase O0 and 1l may look the same depending on the font used to print/display the code.

**Comment by IAmAStealer** [comment]
Hello, I understand but also want to point that regarding security removing 2 characters from the pool of possible characters is not harmless.
You can close if it is not critical concern about this generation.

**Comment by fichtner** [comment]
To be frank it says so in the GUI: "Use simple passwords (less secure)". There is really no point to be made about it other than that. It is a compromise of readability for security. If you are a hotel you probably care more about readability than someone being able to use your hotel WiFi by brute-forcing vouchers. ;)
