### ISSUE TITLE
Can the widgets api be accessed programmatically? 

### ISSUE THREAD

**Issue by ihatemodels** [opnsense/core#7031]
**Important notices**

Before you ask a new question, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

Dear OPNsense Team, 

### Description
I'm developing a Prometheus exporter that leverages the OPNsense API to gather data. Specifically, I'm targeting the endpoint `https://opnsense.mydomain.com/widgets/api/get.php?load=system,interfaces,temperature` to collect system, interfaces, and temperature data. 

### Issue
When I invoke the API using basic authentication with API/secret keys, it consistently returns an HTML page prompting for login, rather than the expected JSON data. This behavior persists despite the fact that my user account has full permissions on all endpoints.

### Steps to Reproduce
1. Call the endpoint `https://opnsense.mydomain.com/widgets/api/get.php?load=system,interfaces,temperature` using basic auth with valid API/secret keys.
2. Observe the response.

### Expected Behavior
I would expect the API to return JSON-formatted data corresponding to the specified parameters (`system`, `interfaces`, `temperature`).

### Actual Behavior
The API call returns an HTML page with a login prompt.

### Questions 
- Is the widgets endpoint (/widgets/api/get.php) intended for use outside of browser-based calls? Can it be accessed programmatically? 
- If the /widgets/api/get.php endpoint is not designed for external calls, is there an alternative API endpoint available for retrieving data on temperatures, system versions, and CPU load, similar to what is displayed in the system and temperature widgets? 

### Additional Context
- I have verified that my user account possesses full permissions for all endpoints.
- I attempted to analyze the source code to determine if this URL is exclusively accessible via a web browser, but I couldn't find any conclusive information.
- I tried to search the endpoints, but could not find any other that can get me the data I need. 

Any insights or suggestions regarding this issue would be greatly appreciated. Thank you!

**Comment by AdSchellevis** [comment]
nope, eventually we should try to rebuild the dashboard as well, but all legacy pages only work in the browser.

**Comment by ihatemodels** [comment]
Thank you for your response! 

Maybe I can start to work on the API implementation of the mentioned components as initial step for the dashboard rebuild. 

Should we make different endpoints under `/api/diagnostics/system/getXXX` for every component (system, temperatures, etc ...) or mby the information should be under single endpoint, let's say `/api/diagnostics/system/getInfo` From my perspective now as Prometheus Exporter developer it makes more sense that information to be available on single endpoint. From the dashboard perspective it's ok too I guess. The less http calls, the better . 

What will you suggest?

**Comment by AdSchellevis** [comment]
it might be better to put this in the prometheus plugin, a new dashboard needs a design first, which will need quite some time from our end.

**Comment by ihatemodels** [comment]
I believe the Prometheus plugin may not be the best solution, and I'd like to elaborate on why.

My current project involves developing 'opnsense-exporter', a standalone software. This software is designed to operate externally, accessing the OPNsense API from a remote location, and then converting the data into Prometheus-compatible metrics. This approach differs significantly from the existing 'node_exporter' package. Unlike 'node_exporter', which requires installation directly on the OPNsense system and needs a dedicated port for metric exportation (a constraint that may not be feasible in every environment), 'opnsense-exporter' is intended to be more flexible. Also it sounds for me that it will be best if the new exporter works without the need of any plugin installation. 

Furthermore, 'node_exporter' does not capture the full spectrum of metrics available through the OPNsense API, such as firewall data, service information, etc ... and other plugins data. 

Considering these factors, I propose the creation of a dedicated endpoint within the `/api/diagnostics` subsystem of OPNsense. This endpoint would provide comprehensive system information, similar to what is displayed on the dashboard, and would be invaluable not just for my project, but broadly for ITSM and monitoring purposes.

**Comment by AdSchellevis** [comment]
I don't expect we will implement a single endpoint which collects a lot of data in core, but you can build a plugin that offers that functionality on its own endpoints. 

When some statistic would be practical to add into the existing endpoints, we can always discuss, but when adding core endpoints, we aim to offer frontend components as well for people to use (which also eases testing).

**Comment by ihatemodels** [comment]
Understood. I will probably jump for the development of another plugin. Should we close this one ?

**Comment by AdSchellevis** [comment]
let's do that, a plugin is likely a better place for this indeed.
