### ISSUE TITLE
Persist serial console everywhere, not just USB serial ports

### ISSUE THREAD

**Issue by no-usernames-left** [opnsense/core#7037]
- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

Even if boot console is set to "dual, serial primary" the physical serial console is not persisted across reboot; this was fixed for USB serial in #4849 but physical UARTs are still affected. This prevents access to OPNsense shell from either physical serial port or IPMI serial in the event the network is down and out-of-band recovery is needed.

To put this issue to bed once and for all, this should probably be done for `xc0` (Xen virtual console) and `rcons` (HTIF console) as well.

AFAIK, this cannot be fixed with a tunable, and manual changes to `/etc/ttys` are lost at reboot.

**To Reproduce**

1. Connect to serial port
2. Press enter
3. There is no step 3
4. ???
5. Profit!

**Expected behavior**

1. Connect to serial port
2. Press enter
3. Login prompt

**Relevant extract from /etc/ttys as shipped**

```
# Serial terminals
# The 'dialup' keyword identifies dialin lines to login, fingerd etc.
ttyu0   "/usr/libexec/getty 3wire.115200"       vt100   onifconsole secure
ttyu1   "/usr/libexec/getty 3wire.115200"       vt100   onifconsole secure
ttyu2   "/usr/libexec/getty 3wire.115200"       vt100   onifconsole secure
ttyu3   "/usr/libexec/getty 3wire.115200"       vt100   onifconsole secure
# Dumb console
dcons   "/usr/libexec/getty std.9600"   vt100   off secure
# Xen Virtual console
xc0     "/usr/libexec/getty Pc"         xterm   onifconsole secure
# RISC-V HTIF console
rcons   "/usr/libexec/getty std.9600"   vt100   onifconsole secure

```

**Fix**

*s/onifconsole/on/g*

**Environment**

Software version used and hardware type if relevant, e.g.:
OPNsense 23.7.9-amd64 on enterprise-grade dual-Xeon rack-mount server

**Comment by fichtner** [comment]
> is not persisted across reboot

What does this mean? It's copied from the other ticket but it doesn't make the same sense in serial console, because it talked about pluggin in USB after the fact.

Changing "onifconsole" to "on" will likely start spamming messages for those who don't have consoles activated and I'm not even sure what "This prevents access to OPNsense shell from either physical serial port or IPMI serial in the event the network is down and out-of-band recovery is needed." means either.

**Comment by fichtner** [comment]
I've never seen this since 2016 where it was introduced 845b96d41fbb764 except when people use "home made unshielded serial cables". I don't think sending Wikipedia entries helps here. It makes it look more like AI generated content. ;)

**Comment by fichtner** [comment]
Yep, you are missing why that is on your end and jump to conclusions on how to not fix it for everyone. This is not the fix you are looking for and doing strange working like "not persisted across reboot" which didn't make sense as "be persistent over reboots". It's the same wording. And it's still wrong.

**Comment by fichtner** [comment]
Because it doesn't initate as a console? https://man.freebsd.org/cgi/man.cgi?ttys(5)

```
As flag values, the strings ``on'' and  ``off''	specify	 that  init(8)
should  (should	not)  execute  the  command given in the second	field.
``onifconsole'' will cause this line to be enabled if and only if it is
an active kernel	console	device (it is equivalent  to  ``on''  in  this
case).	The  flag ``onifexists'' will cause this line to be enabled if
and only	if the name exists.  If	the name starts	with a ``/'', it  will
be  considered  an  absolute  path.  Otherwise, it is considered	a path
relative	to /dev.  The flag ``secure'' (if the console is enabled)  al-
lows  users with	a uid of 0 to login on this line.  The flag ``dialup''
indicates that a	tty entry describes a dialin line, and ``network''  is
obsolete	 and does nothing.  Either of these strings may	also be	speci-
fied in the terminal type field.	 The string ``window=''	 may  be  fol-
lowed  by  a  quoted  command  string which init(8) will	execute	before
starting	the command specified by the second field.
```

This has been the case since 2016 when "on" was moved to "onifconsole" and I've never seen what you describe and I have hears as many bug reports from others regarding this. So I'm very sceptical of the conclusion.

**Comment by fichtner** [comment]
If you don't believe me, see https://github.com/opnsense/core/issues?q=is%3Aissue+onifconsole

There's only your issue and the one you are referencing (for a different type of problem).

**Comment by fichtner** [comment]
If FreeBSD is considering changing their default, yes.

**Comment by fichtner** [comment]
My community support time ends here.

**Comment by fichtner** [comment]
FWIW, you could try to save the system: settings: administration page to see if a simple SIGHUP to init actually solves the connectivity issue. If not for one reason or another the connected line is not properly detected. That could be a mismatch in serial settings or other (vendor) quirks. I don't doubt that it doesn't work, maybe even a fix in FreeBSD is available, but I have no way to confirm or test.

**Comment by fichtner** [comment]
Confirmation bias? ;) There is really no difference between OPNsense 23.7 and FreeBSD 13.2. if 14.0 works then either 13.2 works too or it doesn’t. The educated guess would be it doesn’t and there is a patch somewhere that needs to be located.

**Comment by fichtner** [comment]
FreeBSD 14.1/OPNsense 25.1 is much more likely unfortunately.
