### ISSUE TITLE
Dashboard : Reporting health don't shows VpnUsers stats with new OpenVPN instance

### ISSUE THREAD

**Issue by droumanet** [opnsense/core#7038]
**Describe the bug**
It can't display user's information in 
Reporting -> Health -> VpnUsers
Reporting -> Health -> Packets -> Ovpns1
Reporting -> Health -> Traffic -> Ovpns1

**To Reproduce**
I've configured the new way to create OpenVPN instance.

**Screenshots**
![image](https://github.com/opnsense/core/assets/24438463/64e13b27-49e7-4d73-ad15-639c2cb1a824)

**Relevant log files**
![image](https://github.com/opnsense/core/assets/24438463/8d680b99-8066-4b18-9c34-2c2edca49b18)

**Environment**
OPNsense 23.7.9 (amd64).

**Comment by AdSchellevis** [comment]
@droumanet I haven't tested it yet, but the configuration looks good on my end when applying https://github.com/opnsense/core/commit/d662097d1d2ea4ce35e4d165f1f60cea6e32d2e4

The following commands should install and restart the rrd service.

```
opnsense-patch d662097
configctl webgui restart
```
