### ISSUE TITLE
File /var/log/squid/store.log doesn't exist

### ISSUE THREAD

**Issue by oparoz** [opnsense/core#704]
In *Proxy Server: Administration*, the "Enable store logging" box is ticked by default, but the log files stays empty.

**Comment by AdSchellevis** [comment]
Please check the closed issues first before opening new ones: https://github.com/opnsense/core/issues/645

**Comment by fichtner** [comment]
Fixed via #645

**Comment by oparoz** [comment]
> Please check the closed issues first

My bad
