### ISSUE TITLE
Vip.xml subnet/network

### ISSUE THREAD

**Issue by ansibleguy** [opnsense/core#7041]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

When creating a VIP from the WebUI in Version **23.7.7** the following call is seen:

```
{
  "mode": "ipalias",
  "interface": "lan",
  "network": "192.168.0.1",  # <= NOT 'subnet'
  "gateway": "",
  "noexpand": "0",
  "nobind": "0",
  "password": "",
  "vhid": "",
  "advbase": "1",
  "advskew": "0",
  "descr": ""
}
```

But the `network` attribute is not listed in the [Vip.xml](https://github.com/opnsense/core/blame/master/src/opnsense/mvc/app/models/OPNsense/Interfaces/Vip.xml)

This working in previous versions (not sure exactly when it stopped working).

**To Reproduce**

1. Try to add a VIP using the information see in Vip.xml

   ```
   {"vip": {"subnet": "192.168.1.1", "mode": "ipalias", "subnet_bits": 32, "noexpand": 0, "nobind": 0, "gateway": "", "password": "", "vhid": "", "advbase": 1, "advskew": 0, "descr": "", "interface": "lan"}}
   ```

2. Get the follwing error

    ```
    {\"result\":\"failed\",\"validations\":{\"vip.network\":[\"A network address is required.\"]}}'}
    ```

**Expected behavior**

The API definition being correct.
**Environment**

OPNsense 23.7.7-amd64
FreeBSD 13.2-RELEASE-p3
OpenSSL 1.1.1w 11 Sep 2023

**Comment by fichtner** [comment]
This is an oddity in the VIP model as it comes from the legacy side where address and mask are split, but the controller has a single field input and since 23.7.9 that requires the xxx/yy input. A user complained that adding /32 without the user noticing wasn't the best approach.


Cheers,
Franco

**Comment by ansibleguy** [comment]
Greetings!

I totally understand why one would use a single network instead of address + cidr.
But how should I handle it using the API?

I'm currently debugging it and it seems the response from the 'get' command is (still) returning the `subnet` and `subnet_bits` instead of the new `network`:
```
{'expand': True, 'bind': True, 'advertising_base': 1, 'advertising_skew': 0, 'description': '', 'interface': 'lan', 'mode': 'ipalias', 'subnet': '192.168.1.1', 'subnet_bits': 30, 'gateway': '', 'password': '', 'vhid': '', 'uuid': 'be055b3f-8cbc-4313-8053-67ec526fbc01'}
```

But if I try to create one using the `add` command I need to supply it as `network` - else the server-side validation fails :(

**Comment by fichtner** [comment]
The only change here is that "/32" (and "/128" in IPv4) is not added to the network automatically anymore if submitted. If the user wanted that it needs to be added manually now.

**Comment by ansibleguy** [comment]
Ok.
So the `cidr` simply became required instead of optional? Do I understand it correctly?
In that case this requests should work, yes? 
```
DATA: '{"vip": {"subnet": "192.168.1.1", "mode": "ipalias", "subnet_bits": 32, "noexpand": 0, "nobind": 0,
"gateway": "", "password": "", "vhid": "", "advbase": 1, "advskew": 0, "descr": "", "interface": "lan"}}'
```

But it doesn't:
```
{\"vip.network\":[\"A network address is required.\"]}
```

The field `network` seems to be required now (as used by the WebUI.

**Comment by fichtner** [comment]
Hmm, I don't know how to make myself more clear:

```
{
  "mode": "ipalias",
  "interface": "lan",
  "network": "192.168.0.1",  # <= NOT 'subnet'
  "gateway": "",
  "noexpand": "0",
  "nobind": "0",
  "password": "",
  "vhid": "",
  "advbase": "1",
  "advskew": "0",
  "descr": ""
}
```

You need to do:

```
{
  "mode": "ipalias",
  "interface": "lan",
  "network": "192.168.0.1/32",  # <= NOT 'subnet'
  "gateway": "",
  "noexpand": "0",
  "nobind": "0",
  "password": "",
  "vhid": "",
  "advbase": "1",
  "advskew": "0",
  "descr": ""
}
```

That's all there is to it.

**Comment by ansibleguy** [comment]
Ok.
So I'll 'only' need to add a special case for handling add/set and get differently.

As add/set need `network`
And get only returns `subnet` and `subnet_bits`

**Comment by fichtner** [comment]
yes but that was the case before 23.7.9 as well :)

and in most cases you can't run into the new validation if you made sure to send "network" with the proper subnet mask attached already. This is really just an undefined  edge case with the value handling you are seeing.

**Comment by ansibleguy** [comment]
Alright - then I'll figure it out (;
I would think it would be cleaner if the `get` also returned the `network`

**Comment by fichtner** [comment]
It was done to avoid breaking the legacy backend code handling of VIPs when the API was introduced. If you create a ticket to consolidate it to "network" you will be the first to know when it's done. Deal? :)

**Comment by ansibleguy** [comment]
@fichtner Yeah - that sounds great :D
Anyways - thanks for the quick help.

**Comment by AdSchellevis** [comment]
We discussed this briefly internally, but it's not practical that the model definition can't be used as separate fields (and a bit unintentional) since we don't have a way to documented these situations better than pointing to the model. https://github.com/opnsense/core/commit/78c0e681caaf8c0dda01d4071b413e61456c2712 should allow `network` and `subnet` + `subnet_bits` where `network` is preferred when offered, being a concatenated field of both.  Obviously `subnet_bits` is still required in all cases.
