### ISSUE TITLE
Timed config change

### ISSUE THREAD

**Issue by lfirewall1243** [opnsense/core#7043]
Idea for a feature.

In some situations a "timed config" would be nice to have. When you change some Firewall rules for testing new setting, it would be nice to set a timer for like "5 Minutes".

For these 5 minutes the new Firewall settings will be active if you not submit them.
For risky rule settings you wouldn't have the risk to log out after a config change.

Thanks

**Comment by mimugmail** [comment]
Just for the record, this was added here https://github.com/mimugmail/opn-repo/tree/main/sysutils/auto-recovery
