### ISSUE TITLE
Toggling Multiselect removes all other options from the dropdown menu

### ISSUE THREAD

**Issue by Unspec7** [opnsense/core#7045]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

When viewing log files, selecting "Multiselect" removes all other options from the dropdown menu besides multiselect. Even if it is unselected, the list stays empty except for multiselect. Refreshing the page brings back all the dropdown menus with the multiselect option still correctly toggled.

**To Reproduce**

1. Go to System > Log Files > Web GUI (any log page is fine, the behavior is not observed on just Web GUI page)
2. Click on dropdown menu to select type of log to view
3. Toggle Multiselect
4. All other options disappear

**Expected behavior**

Expected behavior is that other dropdown menu items do not disappear

**Describe alternatives you considered**

A clear and concise description of any alternative solutions or workaround you considered.

**Screenshots**

![image](https://github.com/opnsense/core/assets/11931584/3fc2dc2f-1d12-4652-9a18-d9b3b1588b30)

**Environment**

OPNsense 23.7.9 (amd64).
Intel® Core™ i5-8500 3.0Ghz Hex Core
Network Intel® I350-T4

**Comment by AdSchellevis** [comment]
https://github.com/opnsense/core/commit/f2427d6173539cbc0da557f0a75aaf665f733dcc should do the trick, looks like a glitch in the bootstrap select component we use.
