### ISSUE TITLE
Wrong "help" in DHCPv6 for Prefix Delegation Range

### ISSUE THREAD

**Issue by rderensy** [opnsense/core#7046]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

The help in DHCPv6 "Prefix Delegation Range" says:

> When using a tracked interface then please only enter the range itself, i.e. ::xxxx:0:0:0:0. For example, for a /56 delegation from ::100;0:0:0:0 to ::f00:0:0:0:0.

But this is wrong.

My LAN interface is set to "track interface" and I chose to delegate /60, so I set the range as ::10:0:0:0:0 to ::f0:0:0:0:0, because it says to only enter the range. But this was not working. OPNsense RA is Unmanaged and my subrouter was only requesting a prefix and not an address. It got the prefix (`f` was the first assigned) but its LAN addresses were `::f0:xxxx:xxxx:xxxx:xxxx/128` instead of `2001:(...)f0:xxxx:xxxx:xxxx:xxxx/128`. I had to set the range with the public routing prefix too for it to work.

This also caused the route to be created with `0:0:0:f0/60` instead of `2001:(...)f0:xxxx:xxxx:xxxx:xxxx/60`.

So either the help is wrong, or the prefix delegation doesn't work as expected.

**To Reproduce**

1. Add a subrouter (another OPNsense if you want) behind the main OPNsense.
2. Enable DHCPv6 and set the Prefix Delegation Size to 60 and delegate from ::10:0:0:0:0 to ::f0:0:0:0:0
3. Set the subrouter WAN interface to DHCPv6 and its LAN to "track interface"
4. Check the LAN address

**Expected behavior**

The prefix delegation should delegate the public routing prefix as well as the prefix itself.

**Describe alternatives you considered**

Add the public routing prefix in the range.

**Screenshots**

![Untitled](https://github.com/opnsense/core/assets/29119296/0200a132-cf24-48b2-96d2-7ee84502909c)

**Relevant log files**

If applicable, information from log files supporting your claim.

**Additional context**

**Environment**

OPNsense 23.7.9-amd64 (virtualized)
Ryzen 5 3600
Linux bridge

**Comment by fichtner** [comment]
> Enable DHCPv6 and set the Prefix Delegation Size to 60 and delegate from ::10:0:0:0:0 to ::f0:0:0:0:0

Well, you need a matching WAN DHCPv6 client config first and LAN tracking it. Otherwise you can't use the WAN prefix with the "::" prefix trick and it will be treated as a normal IPv6.

**Comment by fichtner** [comment]
Well, does Interface: Overview list your correct WAN prefix? The merge is pretty straight forward if there is a delegated prefix acquired.

**Comment by fichtner** [comment]
Yeah, but it only does that if your prefix failed to acquire. These "dynamic" approaches to static things like DHCP are not really great, but ISPs tend to be on the side of only giving out dynamic IPv6 prefixes so it is what it is.

**Comment by rderensy** [comment]
On my ISP's side, I do get 2001:xxxx:yyyy:zz00::/56 from them.

**Comment by fichtner** [comment]
/128 .. it should be /64?

**Comment by rderensy** [comment]
It is, my bad

**Comment by fichtner** [comment]
Well it's easy to check the DHCPv6 config file to see if subnet6 and range6 have the expected value:

    # cat /var/dhcpd/etc/dhcpdv6.conf

**Comment by rderensy** [comment]
Well now that I set the public routing prefix manually, subnet6 looks good, but range6 doesn't exist. Probably because I didn't set a DHCP address range?

But when I set only the prefix, subnet6 is

```
subnet6 2001:xxxx:yyyy:zz00::/64 {
  option dhcp6.name-servers 2001:xxxx:yyyy:zz00:vvvv:vvff:fevv:vvvv;
  prefix6 0:0:0:10:: 0:0:0:f0::/60;

}
```

**Comment by fichtner** [comment]
I'm very very sure this is a configuration problem because a number of people would immediately say that this doesn't work (anymore). Does your entered prefix range start exactly with "::" ? You can also try the range to see if it merged. I'd still be surprised if it wouldn't.

**Comment by fichtner** [comment]
Also your steps don't mention setting "Allow manual adjustment of DHCPv6 and Router Advertisements" which is a prerequisite for even configuring the DHCPv6 on that interface configuration.

**Comment by rderensy** [comment]
> Does your entered prefix range start exactly with "::" ?

Yes

> You can also try the range to see if it merged.

I'm not sure I understand this 

> Also your steps don't mention setting "Allow manual adjustment of DHCPv6 and Router Advertisements" which is a prerequisite for even configuring the DHCPv6 on that interface configuration.

This is enabled, otherwise the daemon wouldn't start, and it wouldn't work when writing the public routing prefix manually.

**Comment by fichtner** [comment]
Just put a range from `::2000` to `::ffff` to see if range6 is merged correctly or not.

**Comment by rderensy** [comment]
Now this looks like what I would expect
![image](https://github.com/opnsense/core/assets/29119296/d5bc749f-72b5-4e4a-8f33-56bcfc11c27e)

```
subnet6 2001:xxxx:yyyy:zz00::/64 {
  range6 2001:xxxx:yyyy:zz00::2000 2001:xxxx:yyyy:zz00::ffff;
  option dhcp6.name-servers 2001:xxxx:yyyy:zz00:vvvv:vvff:fevv:vvvv;
  prefix6 0:0:0:10:: 0:0:0:f0::/60;

}
```

shouldn't the prefix6 be like range6?

**Comment by fichtner** [comment]
Yes... but... what's your `Available prefix delegation size`?

**Comment by rderensy** [comment]
57 bits

**Comment by fichtner** [comment]
Do you see any log message for this?

    # opnsense-log | grep "not a valid prefix"

**Comment by fichtner** [comment]
Well, I'm a bit lost. The code issue is somewhere here https://github.com/opnsense/core/blob/master/src/etc/inc/plugins.inc.d/dhcpd.inc#L1368-L1388

Just to be sure you have set prefix hint on WAN to /56 ?

**Comment by rderensy** [comment]
The size is set to 56 (I asked my ISP and it is the right size) but "Send IPv6 prefix hint" is unchecked.

**Comment by rderensy** [comment]
[merge_ipv6_address](https://github.com/opnsense/core/blob/master/src/etc/inc/plugins.inc.d/dhcpd.inc#L1372) seems to be the problem. It converts `::10:0:0:0:0` into `10:0:0:0::`.

So when you [merge at the end](https://github.com/opnsense/core/blob/master/src/etc/inc/plugins.inc.d/dhcpd.inc#L1386), it tries to merge `2001:xxxx:yyyy:zz00:0:0:0:0` with `0:0:0:10::`

Shouldn't it be `$range_from = merge_ipv6_address('::', $dhcpdv6cfg[$ifname]['prefixrange']['from']);`?

**Comment by PacoTyson** [comment]
Hi,

If it helps by bringing more examples, I’m facing the same issue, see https://forum.opnsense.org/index.php?topic=37348.0

opnsense-log | grep "not a valid prefix" returns nothing either.

**Comment by rderensy** [comment]
@fichtner if my LAN IPv6 Prefix ID is `0x1`, what should the PD range be? It shouldn't overlap so it is my understanding that `::10:0:0:0:0` and `::f0:0:0:0:0` do not overlap with `::1:0:0:0:0/64`, but should it be from `::12:0:0:0:0` to `::f2:0:0:0:0` or something?

**Comment by maurice-w** [comment]
The help text is indeed incorrect, you need to omit the trailing zeroes. For 15x /60, simply enter `from ::10 to ::f0`.

**Comment by rderensy** [comment]
Writing without the trailing zeroes works indeed.

`cat /var/dhcpd/etc/dhcpdv6.conf ` does merge the address with the prefix correctly with `::10` to `::f0`.

**Comment by maurice-w** [comment]
I've always used it that way, probably never paid attention to the help text. Not sure if it ever worked with trailing zeroes.

**Comment by fichtner** [comment]
This doesn't make sense to me... trailing zeroes are not optional. It would indicate it's lower /64 bit side. The examples are derived from https://tldp.org/HOWTO/Linux+IPv6-HOWTO/ch22s06.html and you can see they have all the trailing zeroes in the config format. Something about leading and trailing zeroes is weird, maybe an intermediate compress destroys the correct ordering making prefix merge fail.

I've been away the past two weeks so I haven't looked closer yet.

**Comment by fichtner** [comment]
The relevant from 5fa042b68 almost 18 months ago... it must have broken somewhere else in the meantime.

**Comment by rderensy** [comment]
This seems to have broken it for me https://github.com/opnsense/core/commit/7fcbb22094392f6ea9f9f67dfbc00a4488d4cf32#diff-e8a8d358a47a0aaf09fb3b160a32f5dd7625b3c1c82210d7f2412e182d0fcd66R545

**Comment by maurice-w** [comment]
Well, all I can say is that I've never entered trailing zeroes for the PD range values. It seemed the logical syntax to me and always worked as expected. I just checked some of my config backups from as long as four years ago to confirm.

dhcpdv6.conf needs the prefix6 values to end with :: of course, but this has always been handled by the OPNsense prefix merge code.

Note: This only applies to track6 LAN interfaces. For static LAN interfaces, you have to enter the PD range values "correctly" of course (ending with :: or trailing zeroes).

**Comment by fichtner** [comment]
dd92fe4 is worth a try... keep in mind this is only a problem due to allowing people to use the wrong legacy format...

    # opnsense-patch dd92fe4


Cheers,
Franco

**Comment by rderensy** [comment]
The patch works with trailing zeroes

**Comment by fichtner** [comment]
Thanks, I'll add this to 23.7.11 and close.


Cheers,
Franco

**Comment by PacoTyson** [comment]
> The patch works with trailing zeroes

Not for me, I provided details in the forum post.
Franco, should I open an issue here instead of a forum post ?

**Comment by fichtner** [comment]
@PacoTyson yeah a separate issue with all the details would be good. Already knowing this is not your issue goes back to square one: 50% change for configuration mistake, 50% chance of another bug. Let's start from the top.


Cheers,
Franco
