### ISSUE TITLE
[VXLAN] Option to customize local and remote ports 

### ISSUE THREAD

**Issue by spin-lock** [opnsense/core#7047]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**

Currently, when creating VXLAN interfaces through OPNsense GUI there's no option to customize local and remote ports. As a result, all VXLAN ifaces are created with default values (4789) for both local and remote ports.

**Describe the solution you like**

I would like to ask a feature to customize local and remote ports on VXLAN for various reasons - avoiding censorships, better entropy for ECMP balancing, etc. - so OPNsense can pass the _vxlanlocalport_ and _vxlanremoteport_ params to [ifconfig](https://man.freebsd.org/cgi/man.cgi?query=ifconfig&sektion=8&apropos=0&manpath=FreeBSD+14.0-RELEASE+and+Ports#:~:text=vxlanlocalport) when creating a VXLAN interface. 

**Describe alternatives you considered**

**Additional context**

**Comment by AdSchellevis** [comment]
@Monviech sure, be my guest. Thanks in advance

**Comment by Monviech** [comment]
https://github.com/opnsense/core/pull/7048
