### ISSUE TITLE
unbound/logger.py crash

### ISSUE THREAD

**Issue by zt-luo** [opnsense/core#7049]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

A clear and concise description of what the bug is, including last known working version (if any).

*Tip*: to validate your setup was working with the previous version, use opnsense-revert (https://docs.opnsense.org/manual/opnsense_tools.html#opnsense-revert)

**To Reproduce**

1. stop Unbound DNS service
2. start Unbound DNS service
3. about 4 hours after, unbound/logger.py start crash

**Expected behavior**

no crash

**Describe alternatives you considered**

no

**Screenshots**

no

**Relevant log files**

System log:
2023-12-03T16:47:46 | Notice | kernel | <6>pid 82433 (python3.9), jid 0, uid 0: exited on signal 6

Services: Unbound DNS: Log File

2023-12-03T16:48:12	Informational	unbound	[78837:0] info: dnsbl_module: no logging backend found.	
2023-12-03T16:48:12	Informational	unbound	[78837:0] info: dnsbl_module: attempting to open pipe	
2023-12-03T16:48:01	Informational	unbound	[78837:1] info: dnsbl_module: no logging backend found.	
2023-12-03T16:48:01	Informational	unbound	[78837:1] info: dnsbl_module: attempting to open pipe	
2023-12-03T16:47:46	Informational	unbound	[78837:6] info: dnsbl_module: no logging backend found.	
2023-12-03T16:47:46	Informational	unbound	[78837:6] info: dnsbl_module: attempting to open pipe	
2023-12-03T16:47:46	Informational	unbound	[78837:5] info: dnsbl_module: Logging backend closed connection. Closing pipe and continuing.

then i found unbound/logger.py crashing...
root@opn:~ # ps -A | grep "/usr/local/opnsense/scripts/unbound/logger.py"
 8192  0  S+        0:00.00 grep /usr/local/opnsense/scripts/unbound/logger.py
root@opn:~ # ps -A | grep "/usr/local/opnsense/scripts/unbound/logger.py"
 9754  0  S+        0:00.00 grep /usr/local/opnsense/scripts/unbound/logger.py
root@opn:~ # ps -A | grep "/usr/local/opnsense/scripts/unbound/logger.py"
11230  0  S+        0:00.00 grep /usr/local/opnsense/scripts/unbound/logger.py
root@opn:~ # ps -A | grep "/usr/local/opnsense/scripts/unbound/logger.py"
12236  0  S+        0:00.00 grep /usr/local/opnsense/scripts/unbound/logger.py
root@opn:~ # ps -A | grep "/usr/local/opnsense/scripts/unbound/logger.py"
14652  0  S+        0:00.00 grep /usr/local/opnsense/scripts/unbound/logger.py
root@opn:~ # ps -A | grep "/usr/local/opnsense/scripts/unbound/logger.py"
16047  0  S+        0:00.00 grep /usr/local/opnsense/scripts/unbound/logger.py
root@opn:~ # ps -A | grep "/usr/local/opnsense/scripts/unbound/logger.py"
17997  0  S+        0:00.00 grep /usr/local/opnsense/scripts/unbound/logger.py
root@opn:~ # ps -A | grep "/usr/local/opnsense/scripts/unbound/logger.py"
18315  0  S+        0:00.01 grep /usr/local/opnsense/scripts/unbound/logger.py
root@opn:~ # ps -A | grep "/usr/local/opnsense/scripts/unbound/logger.py"
20902  0  S+        0:00.00 grep /usr/local/opnsense/scripts/unbound/logger.py
root@opn:~ # ps -A | grep "/usr/local/opnsense/scripts/unbound/logger.py"
21931  0  S+        0:00.00 grep /usr/local/opnsense/scripts/unbound/logger.py
root@opn:~ # ps -A | grep "/usr/local/opnsense/scripts/unbound/logger.py"
22734  0  S+        0:00.01 grep /usr/local/opnsense/scripts/unbound/logger.py
root@opn:~ # ps -A | grep "/usr/local/opnsense/scripts/unbound/logger.py"
23895  0  S+        0:00.00 grep /usr/local/opnsense/scripts/unbound/logger.py
root@opn:~ # ps -A | grep "/usr/local/opnsense/scripts/unbound/logger.py"
25625  0  S+        0:00.00 grep /usr/local/opnsense/scripts/unbound/logger.py
root@opn:~ # ps -A | grep "/usr/local/opnsense/scripts/unbound/logger.py"
25998  0  S+        0:00.00 grep /usr/local/opnsense/scripts/unbound/logger.py
root@opn:~ # ps -A | grep "/usr/local/opnsense/scripts/unbound/logger.py"
27812  0  S+        0:00.00 grep /usr/local/opnsense/scripts/unbound/logger.py
root@opn:~ # ps -A | grep "/usr/local/opnsense/scripts/unbound/logger.py"
28992  0  S+        0:00.00 grep /usr/local/opnsense/scripts/unbound/logger.py

**Additional context**

no

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 23.7.9 (amd64).
Intel(R) Core(TM) i3-N305 (8 cores, 8 threads)

**Comment by AdSchellevis** [comment]
intel microcode issues? the N families seem to be famous for strange behavior

**Comment by AdSchellevis** [comment]
any idea when the issue started?

If logger.py is not running and crashes quite rapidly, you could try to run the logger in a shell to see if it produces any readable errors using the following command:

```
/usr/local/opnsense/scripts/unbound/logger.py
```

**Comment by zt-luo** [comment]
![Screenshot_2023-12-12-12-50-28-506_com termux-edit](https://github.com/opnsense/core/assets/9106745/3fcd6603-3c2b-4e8e-909e-e7d060622732)

just abort

**Comment by zt-luo** [comment]
more information:
unbound/logger.py will never crash until click Reporting->unbound dns

**Comment by AdSchellevis** [comment]
no clue what happened there, could be an issue with duckdb, it doesn't seem to produce a python exception which points to something more low level

**Comment by AdSchellevis** [comment]
This might be caused by a broken database file, can you try to install https://github.com/opnsense/core/commit/29377cecc4db6b073567ab8abdb62e158a92bdce and export/import the database using the commands below?

```
opnsense-patch 29377cecc4db6b073567ab8abdb62e158a92bdce
/usr/local/etc/rc.syshook.d/upgrade/20-unbound-duckdb.py && /usr/local/opnsense/scripts/unbound/restore_db.py && pluginctl -s unbound restart
```

This likely also shrinks the db file (/var/unbound/data/unbound.duckdb ) significantly as well.

**Comment by zt-luo** [comment]
> This might be caused by a broken database file, can you try to install [29377ce](https://github.com/opnsense/core/commit/29377cecc4db6b073567ab8abdb62e158a92bdce) and export/import the database using the commands below?
> 
> ```
> opnsense-patch 29377cecc4db6b073567ab8abdb62e158a92bdce
> /usr/local/etc/rc.syshook.d/upgrade/20-unbound-duckdb.py && /usr/local/opnsense/scripts/unbound/restore_db.py && pluginctl -s unbound restart
> ```
> 
> This likely also shrinks the db file (/var/unbound/data/unbound.duckdb ) significantly as well.

caused by a broken database file.
restore_db.py won't work.
after delete unbound.duckdb, unbound works back to normal.

**Comment by AdSchellevis** [comment]
close issue then?

**Comment by Kornelius777** [comment]
Thank you very much!
I just ran into the same issue. (OPNsense 23.7.10_1-amd64 with unbound 1.19.0)
Deleting /var/unbound/data/unbound.duckdb solved it for me.
Kind regards!

**Comment by tvr256** [comment]
I've also been seeing this since December. Deleting the database is a workaround, but ideally we should solve the root cause of the database corruption. It seems strange that everyone has started seeing it recently, has anything changed in the logging code?

**Comment by AdSchellevis** [comment]
Instead of dropping the database, one could try to repair it as suggested earlier (https://github.com/opnsense/core/issues/7049#issuecomment-1851751168). If a repair helps, that's something we might be able to automate at some point in time. Otherwise we can wait for the next duckdb version and see if that improves the situation..... Unfortunately we can only do that on major upgrades at the moment due to duckdb files not being binary compatible....
