### ISSUE TITLE
Unused dyndns service keeps restarting the OpenVPN connection

### ISSUE THREAD

**Issue by oparoz** [opnsense/core#705]
This is using Suricata in IPS mode and squid as a transparent proxy with ACLs.

Here is what I see in the logs

```
Jan 25 13:00:11	inetd[68786]: 19000/tcp: unknown service
Jan 25 13:00:10	configd.py: [u-u-i-d] Reloading filter
Jan 25 13:00:10	opnsense: /usr/local/etc/rc.openvpn: OpenVPN: One or more OpenVPN tunnel endpoints may have changed its IP. Reloading endpoints that may use VPN_TCP_VPNV4.
Jan 25 13:00:09	configd.py: [u-u-i-d] Restarting OpenVPN tunnels/interfaces VPN_TCP_VPNV4
Jan 25 13:00:09	configd.py: [u-u-i-d] Restarting ipsec tunnels
Jan 25 13:00:09	configd.py: [u-u-i-d] updating dyndns VPN_TCP_VPNV4
```

I'm not using dyndns, nor am I using IPsec.

**Comment by AdSchellevis** [comment]
did you only enable ips (netmap) on the physical device?

**Comment by oparoz** [comment]
I didn't do anything else than ticking the box in Intrusion Detection and rebooting (since it was unstable)

**Comment by oparoz** [comment]
If I don't monitor the VPN gateway, then everything is fine, but then I don't know when it goes down.

**Comment by fichtner** [comment]
@oparoz You're not providing your configuration, which defeats the point of getting help. Is DynDNS disabled (or what do you mean by "unused") and which devices do you use for IPS mode...

**Comment by oparoz** [comment]
* Unused as in "I did not add any DynDNS service"
* There is no DynDNS service listed under *System: Diagnostics: Services*
* Suricata is set to filter both WAN and VPN_WAN
* The Suricata command line ` /usr/local/bin/suricata -D --netmap --pidfile /var/run/suricata.pid -c /usr/local/etc/suricata/suricata.yaml`

**Comment by oparoz** [comment]
netmap is enabled on WAN
```
re1: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500
        options=182098<VLAN_MTU,VLAN_HWTAGGING,VLAN_HWCSUM,WOL_MAGIC,LINKSTATE,NETMAP>
```

And monitoring the WAN_VPN changed nothing in the end, I get the same messages in the logs.

**Comment by AdSchellevis** [comment]
@oparoz again, you **can not** enable IPS on a non physical interface "VPN_WAN"

**Comment by oparoz** [comment]
@AdSchellevis OK, I've opened this then, so that users are not allowed to add any other interface.
