### ISSUE TITLE
ddclient sends updates every 5 minutes even though the IP address has not changed

### ISSUE THREAD

**Issue by mvglasow** [opnsense/core#7050]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

After upgrading to OPNsense 23.7.9-amd64, ddclient keeps attempting to update the IP address with the DynDNS provider although the address did not change. Not sure what the previous version was (something pre-23.7), however my DynDNS provider blocked me for abuse within two days of updating.

A clear and concise description of what the bug is, including last known working version (if any).

*Tip*: to validate your setup was working with the previous version, use opnsense-revert (https://docs.opnsense.org/manual/opnsense_tools.html#opnsense-revert)

**To Reproduce**

1. Configure DynDNS with the following settings:
```
    <DynDNS version="1.5.1">
      <general>
        <enabled>1</enabled>
        <verbose>0</verbose>
        <allowipv6>0</allowipv6>
        <daemon_delay>300</daemon_delay>
        <backend>ddclient</backend>
      </general>
      <accounts>
        <account uuid="REDACTED">
          <enabled>1</enabled>
          <service>nsupdatev4</service>
          <protocol/>
          <server/>
          <username>REDACTED</username>
          <password>REDACTED</password>
          <resourceId/>
          <hostnames>REDACTED</hostnames>
          <wildcard>0</wildcard>
          <zone/>
          <checkip>web_nsupdate.info-ipv4</checkip>
          <checkip_timeout>10</checkip_timeout>
          <force_ssl>1</force_ssl>
          <interface/>
          <description/>
        </account>
      </accounts>
    </DynDNS>
```
2. Make sure it is enabled and watch the log for a few minutes (more than 5).

**Expected behavior**

The ddns client updates once at most, then no more updates unless the address has changed.

** Actual behavior **

After the first update, I get the following log entry every 5 minutes (or whatever the update interval is):

    WARNING: updating HOST-NAME-REDACTED: nochg: No update required; unnecessary attempts to change to the current address are considered abusive

**Describe alternatives you considered**

As a workaround, I have disabled ddns as my IP address is de facto static (though this is not guaranteed and I won’t be able to find my server, should the address change unexpectedly). Alternatively, increase the update interval to the interval at which your IP address changes (if this is predictable), though this may cause updates to be delayed and your DynDNS entry will be out of date in the meantime.

**Screenshots**

**Relevant log files**

If applicable, information from log files supporting your claim.

**Additional context**

DynDNS updates may ban systems for sending unnecessary updates, and this bug basically causes the service to be hammered with such updates. If your DynDNS provider is doing their job, this is a recipe for getting banned. It seems the IP address change detection broke, at least for nsupdate.info.

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 23.7.8 (amd64).
Intel® Xeon™ E3-1225V5 3.3Ghz Quad Core
Network Intel® I210-AT

**Comment by mvglasow** [comment]
I’m a bit surprised that this is getting closed, after first being labeled as support. For all I know, this is a legitimate bug. I have used the configuration in question for about 2 years, and it wasn’t until December 2023 that suddenly nsupdate.info informed me that they’re getting updates for the same IP address over and over again, which they consider abusive.

For one, why is this getting labeled as support? If there is something I can change (or try) on my end, please let me know. So far I have no indication of anything being wrong with my config (which, after all, has worked for 2 years before).

Has anyone even looked at the issue? For folks relying on nsupdate.info with an IP address which changes only infrequently (maybe not at all, even though the ISP reserves the right to change the IP at any time), this essentially makes ddclient useless.

I have worked around this by disabling DNS updates through ddclient, but as soon as my ISP decides to assign me a different IP address (it’s remained static for years but no guarantee), my system is going to be unreachable from the outside until I intervene manually. That leaves me, and probably other users, in a precarious situation.

**Comment by AdSchellevis** [comment]
best try our native backend. See our contribution guidelines for more information about ticket handling https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

**Comment by mvglasow** [comment]
Where/how would I configure that? Any pointers? I haven’t been able to find any documentation, but I don’t really know what to look for...

**Comment by AdSchellevis** [comment]
https://docs.opnsense.org/manual/dynamic_dns.html#general-settings
