### ISSUE TITLE
Make Google shared drive an optional plugin, like NextCloud, update Cloud Backup documentation

### ISSUE THREAD

**Issue by MagicFab** [opnsense/core#7052]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guidelines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**

When reviewing 23.7.9 release notes, I noticed this note : 
"system: add support for Google Shared drives backup (contributed by Jeremy Huylebroeck)"

Looking at the [Cloud Backup documentation](https://docs.opnsense.org/manual/how-tos/cloud_backup.html) I see detailed instructions for Google Drive and Nextcloud with the following problems : 

* There is no mention of NextCloud backup functionality requiring the **os-nextcloud-backup ** to be installed.
* The documentation mixes both NextCloud and Google drive information, giving the impression both are installed by default when Nextcloud is not.

Google drive's inclusion as a core feature is also incoherent with several [OPNsense mission statement elements](https://opnsense.org/about/about-opnsense/) such as being open source, transparent and friendly.

**Describe the solution you like**

- It would be useful to mention **os-nextcloud-backup ** needs to be installed and add a mention to it in core features.
- Google drive backup should not be enabled by default, it should be available as an optional plugin, like Nextcloud.
- When either of them is available, their parameters should only be visible/expanded when enabled.
- Documentation should also be separate for both backup options, and updated. Having encryption for the Nextcloud backup was missing from the included screenshot. 

**Describe alternatives you considered**

- After installing **os-nextcloud-backup ** Nextcloud backup became available.
- I searched for a dedicated Google shared drive backup package to remove but there was none.
 
**Additional context**

I didn't check in detail what was missing or outdated.

**Comment by fichtner** [comment]
If this a docs problem might be worth contributing there instead.


Cheers,
Franco

**Comment by MagicFab** [comment]
I'd like to step up and work in improving the documentation.

Am I correct in this specific case the document to update is at :
https://github.com/opnsense/docs/blob/master/source/manual/how-tos/cloud_backup.rst 

?

If so I'd like to request permission to do so, or just confirmation I can make a pull request etc.

Thanks in advance for considering this request.

**Comment by fichtner** [comment]
@MagicFab yep, feel free to open a PR. Thanks in advance!
