### ISSUE TITLE
unbound stats page leads to memory leak -> OOM kill

### ISSUE THREAD

**Issue by xschlef** [opnsense/core#7053]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**
We are running DEC3850 with opnsense community 23.7.7_3.
Our unbound or more likely the unbound logger, has a memory leak when we click on Reporting -> Unbound DNS.
It takes about 3-4 minutes for the logger and unbound processes to crash.

We have a guess that this happend as we enabled the unbound blocklist and blocked two domains that are queried 10+ times / second (badly configured CPEs). Bascially 98% of all DNS queries were blocked. We even removed the blocklist (still present in the logs below) and disabled it, but the stats page still fails to load.

Also unbound has about 1k locally configured overrides for DNS. But I guess that should not impact anything.

**To Reproduce**

1. Click on Webinterface -> Reporting -> Unbound DNS
2. Page fails to render, webinterface becomes unresponsive

**Expected behavior**
No memory leak and instead show the unbound stats.

**Describe alternatives you considered**

**Relevant log files**
system log show:
```
<13>1 2023-11-30T11:44:08+01:00 fw-1 kernel - - [meta sequenceId="1"] swap_pager: out of swap space
<13>1 2023-11-30T11:44:08+01:00 fw-1 kernel - - [meta sequenceId="2"] swp_pager_getswapspace(16): failed
<13>1 2023-11-30T11:44:15+01:00 fw-1 kernel - - [meta sequenceId="3"] <3>pid 26576 (python3.9), jid 0, uid 0, was killed: failed to reclaim memory
<13>1 2023-11-30T11:44:17+01:00 fw-1 kernel - - [meta sequenceId="4"] <3>pid 25333 (python3.9), jid 0, uid 0, was killed: failed to reclaim memory
<13>1 2023-11-30T11:44:18+01:00 fw-1 kernel - - [meta sequenceId="5"] <3>pid 99583 (unbound), jid 0, uid 59, was killed: failed to reclaim memory
<13>1 2023-11-30T11:44:19+01:00 fw-1kernel - - [meta sequenceId="6"] <3>pid 3444 (python3.9), jid 0, uid 0, was killed: failed to reclaim memory

```

resolver log:
```
<29>1 2023-11-30T12:53:41+01:00 fw-1 unbound 14574 - [meta sequenceId="1"] [14574:0] notice: init module 0: python
<29>1 2023-11-30T12:53:41+01:00 fw-1 unbound 14574 - [meta sequenceId="2"] [14574:0] notice: init module 1: iterator
<30>1 2023-11-30T12:53:41+01:00 fw-1 unbound 14574 - [meta sequenceId="3"] [14574:0] info: start of service (unbound 1.18.0).
<30>1 2023-11-30T12:53:41+01:00 fw-1 unbound 14574 - [meta sequenceId="4"] [14574:2] info: dnsbl_module: attempting to open pipe
<30>1 2023-11-30T12:53:41+01:00 fw-1 unbound 14574 - [meta sequenceId="5"] [14574:2] info: dnsbl_module: no logging backend found.
<165>1 2023-11-30T12:53:43+01:00 fw-1 unbound 18591 - [meta sequenceId="6"] Backgrounding unbound logging backend.
<30>1 2023-11-30T12:53:51+01:00 fw-1 unbound 14574 - [meta sequenceId="7"] [14574:1] info: dnsbl_module: attempting to open pipe
<30>1 2023-11-30T12:53:51+01:00 fw-1 unbound 14574 - [meta sequenceId="8"] [14574:1] info: dnsbl_module: successfully opened pipe
```

**Environment**

Software version used and hardware type if relevant, e.g.:
DEC3850
opnsense community 23.7.7_3.

**Comment by AdSchellevis** [comment]
Via "System: Diagnostics: Activity" you can track the processes needing a lot of memory, sort by "RES" shows the current allocation per process id.

**Comment by xschlef** [comment]
Hi,

thanks for the fast response. Without clicking the reporting I can see the following top processes:
```
        62538	unbound	21	0	1475M	249M	kqread	2	11:31	1.86%	/usr/local/sbin/unbound -c /var/unbound/unbound.conf{unbound}
	62538	unbound	20	0	1475M	249M	kqread	0	11:20	1.78%	/usr/local/sbin/unbound -c /var/unbound/unbound.conf{unbound}
	62538	unbound	20	0	1475M	249M	kqread	4	11:52	1.71%	/usr/local/sbin/unbound -c /var/unbound/unbound.conf{unbound}
	62538	unbound	20	0	1475M	249M	CPU1	1	11:23	1.61%	/usr/local/sbin/unbound -c /var/unbound/unbound.conf{unbound}
	62538	unbound	20	0	1475M	249M	kqread	3	11:30	1.57%	/usr/local/sbin/unbound -c /var/unbound/unbound.conf{unbound}
	62538	unbound	20	0	1475M	249M	kqread	0	11:15	1.50%	/usr/local/sbin/unbound -c /var/unbound/unbound.conf{unbound}
	62538	unbound	20	0	1475M	249M	kqread	1	11:19	1.41%	/usr/local/sbin/unbound -c /var/unbound/unbound.conf{unbound}
	62538	unbound	20	0	1475M	249M	kqread	6	11:16	1.36%	/usr/local/sbin/unbound -c /var/unbound/unbound.conf{unbound}
	66763	root	24	0	330M	218M	kqread	5	48:08	2.29%	/usr/local/bin/python3 /usr/local/opnsense/scripts/unbound/logger.py (python3.9){python3.9}
	66763	root	52	0	330M	218M	usem	5	0:00	0.00%	/usr/local/bin/python3 /usr/local/opnsense/scripts/unbound/logger.py (python3.9){python3.9}
	66763	root	52	0	330M	218M	usem	3	0:00	0.00%	/usr/local/bin/python3 /usr/local/opnsense/scripts/unbound/logger.py (python3.9){python3.9}
	66763	root	52	0	330M	218M	usem	4	0:00	0.00%	/usr/local/bin/python3 /usr/local/opnsense/scripts/unbound/logger.py (python3.9){python3.9}
	66763	root	52	0	330M	218M	usem	6	0:00	0.00%	/usr/local/bin/python3 /usr/local/opnsense/scripts/unbound/logger.py (python3.9){python3.9}
	66763	root	52	0	330M	218M	usem	7	0:00	0.00%	/usr/local/bin/python3 /usr/local/opnsense/scripts/unbound/logger.py (python3.9){python3.9}
	66763	root	52	0	330M	218M	usem	4	0:00	0.00%	/usr/local/bin/python3 /usr/local/opnsense/scripts/unbound/logger.py (python3.9){python3.9}
	66763	root	52	0	330M	218M	usem	4	0:00	0.00%	/usr/local/bin/python3 /usr/local/opnsense/scripts/unbound/logger.py (python3.9){python3.9}
	66763	root	52	0	330M	218M	uwait	6	0:00	0.00%	/usr/local/bin/python3 /usr/local/opnsense/scripts/unbound/logger.py (python3.9){python3.9}
	66763	root	52	0	330M	218M	uwait	5	0:00	0.00%	/usr/local/bin/python3 /usr/local/opnsense/scripts/unbound/logger.py (python3.9){python3.9}
	66763	root	52	0	330M	218M	uwait	7	0:00	0.00%	/usr/local/bin/python3 /usr/local/opnsense/scripts/unbound/logger.py (python3.9){python3.9}
	66763	root	52	0	330M	218M	uwait	4	0:00	0.00%	/usr/local/bin/python3 /usr/local/opnsense/scripts/unbound/logger.py (python3.9){python3.9}
	66763	root	52	0	330M	218M	uwait	5	0:00	0.00%	/usr/local/bin/python3 /usr/local/opnsense/scripts/unbound/logger.py (python3.9){python3.9}
	66763	root	52	0	330M	218M	uwait	4	0:00	0.00%	/usr/local/bin/python3 /usr/local/opnsense/scripts/unbound/logger.py (python3.9){python3.9}
	66763	root	52	0	330M	218M	uwait	5	0:00	0.00%	/usr/local/bin/python3 /usr/local/opnsense/scripts/unbound/logger.py (python3.9){python3.9}
	66763	root	52	0	330M	218M	uwait	6	0:00	0.00%	/usr/local/bin/python3 /usr/local/opnsense/scripts/unbound/logger.py (python3.9){python3.9}
	98336	root	52	0	84M	45M	accept	4	0:03	0.00%	/usr/local/bin/php-cgi
```

this looks pretty normal to me and we have no problem during normal operation. I do not want to trigger the memleak as it will create a service disruption...

**Comment by AdSchellevis** [comment]
looks rather normal indeed. If this machine is very busy serving questions, the size of the duckdb database underneath might be problematic. If it crashes out on reading the database, the logger might be a mere victim of not having enough memory available.

**Comment by xschlef** [comment]
```
root@fw-1:/var/unbound/data # ls -alh /var/unbound/data/unbound.duckdb
-rw-r-----  1 unbound  unbound   1.0G Dec  5 13:38 /var/unbound/data/unbound.duckdb
```
the database looks pretty sane to me

**Comment by AdSchellevis** [comment]
could be, you probably have to inspect top while causing the issue. as duckdb can't be accessed simultaneously, the logger needs to "stash" while being used by the viewer (not something we can solve, it's a limitation of duckdb).

**Comment by xschlef** [comment]
`72791	root	22	0	15G	7G	RUN	5	0:05	12.90%	/usr/local/bin/python3 /usr/local/opnsense/scripts/unbound/stats.py rolling --interval 600 --timeperiod 24 --clients (python3.9){python3.9}`

stats.py is eating all available memory and crashing. I have no idea why as the blocklist is disabled for over a week now. duckdb grew to 8,6G.

**Comment by AdSchellevis** [comment]
you could try to cleanup the database using https://github.com/opnsense/core/issues/7049#issuecomment-1851751168 , but realistically I wouldn't be surprised if your traffic might need more resources than available.

**Comment by xschlef** [comment]
the fix just fryed my opnsense as nearly everything got oomkilled. Had to reboot for it to recover
