### ISSUE TITLE
Feature: Firewall rules based on domain name instead IP

### ISSUE THREAD

**Issue by Starbase12** [opnsense/core#7056]
I didn't found any information about how to configure firewall rules based on their domain names. Some Cloud based applicates are using dynamic IP-addresses and it's not that easy to handle the respective IPs for a belonging firewall rule. 
Therefore my request is about to add this section into the official documentation or/and implement a solution for this.

I'm not an networking expert. I hope this feature isn't already available and I just don't know the right naming for such feature.

**Comment by fichtner** [comment]
You can use host aliases for this purpose. 😊

**Comment by Starbase12** [comment]
> You can use host aliases for this purpose. 😊

Really? So easy and I didn't tested it? Thank you. Will give it a try :-)
