### ISSUE TITLE
Suricata: only list physical interfaces

### ISSUE THREAD

**Issue by oparoz** [opnsense/core#706]
On the settings tab in *Intrusion Detection*, there is a *interfaces* field.
As soon as we click on it, we're presented with all our interfaces as opposed to just the list of physical interfaces.
The logic should be modified to only present physical interfaces as virtual ones are not supported.

**Comment by fichtner** [comment]
Something slightly different went in with #935

**Comment by oparoz** [comment]
Well, you've added something to the help file, but people who don't read it may still end up with a non-working config. Isn't there a way to detect physical interfaces?

**Comment by fichtner** [comment]
We certainly can't fix people who don't read help files. :)

**Comment by oparoz** [comment]
True, but in terms of usability, you can hide options which a user should never see because they don't work. It's not always a good idea when there isn't a clear distinction since users could feel there is something wrong, but in this case, showing something like WAN (em1), LAN1 (em0), LAN2 (em2) could be useful.
I'm just wondering is there is already an easy way to query for the real interfaces used in OPNsense.
