### ISSUE TITLE
Speed up boot process during certificate scanning

### ISSUE THREAD

**Issue by levelad** [opnsense/core#7063]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at  https://github.com/opnsense/src/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/src/issues?q=is%3Aissue

**Describe the bug**

After installing OPNsense I noticed the system takes very long in the boot process for these two lines:

```
Scanning /usr/share/certs/blacklisted for certificates...
Scanning /usr/share/certs/trusted for certificates...
```

The other lines just take some seconds, but the mentioned ones take about 20-30 seconds.

Is it possible to speed this part up?

Software version used and hardware type if relevant, e.g.:

OPNsense 23.7.9 (amd64)
AMD E1-6010 APU dual-core 1.35 GHz, 4 GB RAM

**Comment by fichtner** [comment]
@doktornotor already raised concerns in the forum. I raised concerns in FreeBSD but so far they haven’t come up with a plan or so much responded to questions and code review. We have a few options to work around, but it would be nice to know where they are going after having forced curl package down the path of certctl use.

**Comment by doktornotor** [comment]
> @doktornotor already raised concerns in the forum. I raised concerns in FreeBSD but so far they haven’t come up with a plan or so much responded to questions and code review. We have a few options to work around, but it would be nice to know where they are going after having forced curl package down the path of certctl use.

@fichtner, do you have the mailing list / bugzilla link handy, or was that a private email discussion? The thing is seriously driving me nuts. 🤬 Posted on the forum thread about the CA import a day or two ago. Incredible waste of time.

**Comment by fichtner** [comment]
Last elaborate message was https://lists.freebsd.org/archives/freebsd-ports/2023-October/004739.html

I only got one private reply. No reply from any of the authors, however, neither private nor public.

I’ll be back on Monday.

**Comment by doktornotor** [comment]
Thanks for the link. The issue with "special" untrusted CAs by FreeBSD you mentioned - is that about Certum CA root or something else? I still cannot make sense of whether it's gonna be trusted or not or how to override it.

**Comment by fichtner** [comment]
@doktornotor the certificates in `/usr/share/certs/blacklisted` act as a global untrusted list which causes user-based CAs to be ovewritten by FreeBSD mandated CAs in that directory. This could also happen on an update since these are supposed to be managed by FreeBSD updates... In my case it was the SwissSign Platinum G2 which I happened to have in my default install for other reasons, which was annoying because when we were still writing a full bundle file it was the first one in the file and ignored all the subsequent ones as well.

So @AdSchellevis wrote a short `certctl.py` to emulate what FreeBSD is doing. If anyone wants to try the backport: 13a1a52565a72

    # opnsense-patch 13a1a52565a72

Feedback welcome.


Cheers,
Franco

**Comment by doktornotor** [comment]
Thanks, applied and switched the "Store intermediate" toggle a couple of times. This appear to be ~5 times faster than before. 👍

**Comment by fichtner** [comment]
Just for reference: on my end it changed from 30 seconds to 1 second.

**Comment by doktornotor** [comment]
Indeed the webgui test is not very good. A testbox with APU4:

```
# time /usr/local/opnsense/scripts/system/certctl.py rehash
Scanning /usr/share/certs/blacklisted for certificates...
Scanning /usr/share/certs/trusted for certificates...
Scanning /usr/local/share/certs for certificates...
1.511u 0.314s 0:02.16 84.2%     5+168k 0+0io 0pf+0w

```

😍

**Comment by levelad** [comment]
Thank you, boot time should be much faster now.

```
root@OPNsense:~ # time /usr/local/opnsense/scripts/system/certctl.py rehash
Scanning /usr/share/certs/blacklisted for certificates...
Scanning /usr/share/certs/trusted for certificates...
Scanning /usr/local/share/certs for certificates...
0.751u 0.134s 0:00.88 100.0%    5+168k 0+0io 0pf+0w
```
