### ISSUE TITLE
How to set unbound as ONLY resolver on OPNSense?

### ISSUE THREAD

**Issue by djusHa** [opnsense/core#7066]
Hi,

i want configure Unbound as ONLY DNS resolver on OPNSense, but
have no Idea how to achieve this.

Have a fresh install on Sophos SG-105 and latest OPNSense.
WAN with PPPoE.

My Settings are:
- "System: Settings: General"
      No DNS Servers
      Allow DNS server list to be overridden by DHCP/PPP on WAN - Off
      other Settings are default

- "Services: Unbound DNS: General"
    all default

No Forward DNS Server are configured.

The Problem, DNS not working.

Calling drill from OPNSense with different DNS Server set, DNS working.
Calling drill from OPNSense without different DNS Server set or with 127.0.0.1 -> Servfail

Unbound needs always a forward DNS Server under
"Services: Unbound DNS: Query Forwarding"
or "Services: Unbound DNS: DNS over TLS"
or "System: Settings: General" with "Use System Nameservers" set.

Any Idea?

**Important notices**

Our forum is located at https://forum.opnsense.org , please consider joining discussions there in stead of using GitHub for these matters.

Before you ask a new question, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Comment by fichtner** [comment]
While the configuration is perfectly viable, it’s only possible if the ISP doesn’t block it for whatever the reason might be. M


Cheers,
Franco

**Comment by djusHa** [comment]
Thanks for Reply.

But how to proof Root DNS Server are accessible, for sure?

Have "drilled" some of the Servers from "root.hints". It seems to be ok so far, as i can judge.

Do you need some Logs?

**Comment by fichtner** [comment]
As long as your ISP is possibly meddling with this you don't have a choice anyway. Either change the ISP or use something like DoT to avoid the immediate meddling.


Cheers,
Franco

**Comment by djusHa** [comment]
Oh boy, got it now :-)

Unfortunately, changed too many factors as same Time, so i can't say what caused this behaviour.

Changes are:
- Replaced Fritzbox against Draytek Vigor 165 as Modem
- Disabled IPv6 on Lan and Wan Interfaces
- Disabled IPv6 Firewall Rule under "Firewall: Rules: LAN"
- Set "Prefer to use IPv4 even if IPv6 is available" under "System: Settings: General"

IMHO it was the Firewall Rule.

Thanks for Support.

**Comment by djusHa** [comment]
Closed.

**Comment by fichtner** [comment]
Ok, most likely thing would be defunct IPv6 then. Glad you could solve it.


Cheers,
Franco
