### ISSUE TITLE
OpenVPN username mixed case

### ISSUE THREAD

**Issue by fabiocastagnino-horsa** [opnsense/core#7067]
**Describe the bug**

Firewall rules using Group (OpenVPN) alias don't match if there are mixed case in username
OpenVPN don't match certificate if there are mixed case in username

**To Reproduce**

I use external LDAP as authenticating system with username in mixed case (Name.Surname or name.surname), and it's configured to ignore the case
I use OpenVPN Instances with Certificate+Username/password and user/cn matching
I use group alias in firewall

If I respect the original case in LDAP, everything works, but if I normalize (all lower) OPNsense don't match the group in firewall rules.

**Expected behavior**

OPNsense should ignore case for username in OpenVPN certificate match and in OpenVPN/Firewall group matching.

**Environment**

OPNsense 23.7.9-amd64
Azure VM

**Comment by AdSchellevis** [comment]
The "Strict User/CN Matching" might be solvable, but the users (common_names) stored in the config should match case with those being reported by openvpn (these do not know their origin). Simple test is to disable the matching and see if the group rules do work.

**Comment by fabiocastagnino-horsa** [comment]
This issue are caused by #7140. Closing.
