### ISSUE TITLE
WAN does not initialize correctly after hard reboot due to power loss while behind ISP modem.

### ISSUE THREAD

**Issue by MaxMacNeill-UNB** [opnsense/core#7068]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

Apologies in advance if this is a duplicate, but I couldn't find anything that addressed my issue.

**Describe the bug**

I recently observed that after a hard reset of the router (read - power loss) If opnsense comes up before the ISP modem does (it always does) the system will provide full Internet for about 40 seconds, then refuse to talk to anything on WAN afterwards. Lan works fine, and rebooting opnsense fixes it. There's no difference in wan IP. As of right now, I can find no reason for this behavior, but it persists in the current version. No knowledge of previous versions, as I have not experienced power loss like this before.

**To Reproduce**

1. Connect OPNSense behind an ISP modem (I have a Bell Aliant Gigahub) in DMZ.
2. Put them both on the same breaker
3. Flip the breaker off and back on, observe as both boot correctly but opnsense does not provide Internet to clients.
4. Reboot opnsense and observe it suddenly work.

**Expected behavior**

Power loss should be handled cleanly without manual intervention.

**Describe alternatives you considered**

I have looked into setting up a script to delay boot, but this would cause issues with efficiency in non power loss reboots, and even then would be a hacky workaround at best.

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 23.7.9 (amd64).
Intel® Core I5-10500
Network SuperMicro AOC-SG-i2

**Comment by fichtner** [comment]
When that happens you are likely getting a WAN IP from another range. In those cases it is advisable to configure WAN DHCP to reject leases from the server in that problematic range and then DHCP waits for the modem to properly initialise.


Cheers,
Franco

**Comment by MaxMacNeill-UNB** [comment]
I only wish this were the solution, but this is not the case - My *correct* WAN IP is 192.168.2.11 - as I have confirmed that when the network is not working it has the proper IP. My ISP modem is setup in DMZ but has the capabilities of a router - it's a static DHCP lease with all traffic forwarded, and it loads correctly. The issue is elsewhere.

**Comment by MaxMacNeill-UNB** [comment]
To clarify, this is a double nat, not a CG-Nat. There is no way to bypass the ISP router without dropping a few hundred dollars on specialty hardware, as the (Serialized and containing authentication hardware) SFP is soldered to the mainboard.

**Comment by mimugmail** [comment]
Can you set up a ping from internal to outside, watch system latest.log and post the message when ping stops?

**Comment by MaxMacNeill-UNB** [comment]
It will be difficult to time, as in order to trigger the bug I'd have to hard reset opnsense, then login, configure a ping, and open logs all before the error is triggered, but I will try come morning (it's about 10 minutes to midnight here.)

**Comment by mimugmail** [comment]
You can ping on your local machine and have an eye on your clock, then compare afterwards

**Comment by MaxMacNeill-UNB** [comment]
I see nothing of issue in the logs, but maybe you'll do better than I did - here's the relevant timestamps.

**_Power on - 11:44:16
OPNSense beep script - 11:45:33
Network up on client, ping starts working - 11:45:50
Ping goes to Destination unreachable - 11:46:30_**

[latest.log](https://github.com/opnsense/core/files/13650299/latest.log)

**Comment by MaxMacNeill-UNB** [comment]
Hey - just wanted to check in if there's any other information you folks need other than that log? I pulled it from the system folder, I assume it's the right one.

**Comment by Maxwelldoug** [comment]
Hey, just following up (from my main account rather than school, didn't even realize that was logged in, oops) - that issue still persists as of the latest version of Opnsense.

**Comment by MaxMacNeill-UNB** [comment]
Updating mid-March to prevent stale issue closure. this persists.
