### ISSUE TITLE
Hide ZFS datasets in Lobby: Dashboard: System Information: Disk usage

### ISSUE THREAD

**Issue by levelad** [opnsense/core#7069]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**

When using the ZFS file system the "Disk usage" is overloaded, you got 12 entries instead of 2 with UFS. It would be nice if these additional datasets could be hidden.

![ZFS_datasets](https://github.com/opnsense/core/assets/47079419/89a3d840-10b4-4f43-8049-d00fbf25e76c)

**Describe the solution you like**

Hide the additional ZFS datasets behind a [+] which can be expanded.

**Comment by fichtner** [comment]
The sets are what they are. I’m unsure which one anyone considers less important and if that belief overlaps between multiple people. First time I heard this is too much in a very long time to be honest. 


Cheers,
Franco

**Comment by levelad** [comment]
Hiding the datasets with a [+] button is probably more complicated because of dynamic elements when expanding. Maybe we can make a compromise and add a pencil menu entry with a checkbox "Hide datasets in ZFS file system" (which is greyed out when there's no ZFS). It's just that it takes up space that could be used by other widgets.
