### ISSUE TITLE
Broken hardware crypto info on dashboard

### ISSUE THREAD

**Issue by oparoz** [opnsense/core#707]
I get something like this:

`Hardware crypto	<AES-CBC`

**Comment by oparoz** [comment]
Also, that row doesn't always appear on the dashboard.

**Comment by gonzopancho** [comment]
I've created a pull request https://github.com/opnsense/core/pull/732 that should close this issue.  (We fixed it months ago in pfSense.)

I predict that @fichtner won't take it, and someone else will clone the work.  You'll still get a fix that way.

**Comment by oparoz** [comment]
>The code in question was removed after a bit of tinkering with the direction to take.

Care to briefly elaborate? I think it's quite useful to have some info on the dashboard about the hardware and available features. Maybe in a separate widget?

**Comment by fichtner** [comment]
The output this code parsed is enclosed in dmesg (visible via crash reporter) or available in the system logs. The real setting under System: Settings: Misc: Cryptographic Hardware Acceleration is authoritative and works fine.
