### ISSUE TITLE
OpenVPN: Client Specific Overrides - IP Error in generate file with use Topology P2P  

### ISSUE THREAD

**Issue by hvalencia89** [opnsense/core#7071]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

Error in file with use OpenVPN: Client Specific Overrides by use Topology P2P

*Tip*: to validate your setup was working with the previous version, use opnsense-revert (https://docs.opnsense.org/manual/opnsense_tools.html#opnsense-revert)

**To Reproduce**

in menu VPN: OpenVPN: Client Specific Overrides

<img width="816" alt="imagen" src="https://github.com/opnsense/core/assets/46072913/d229cd45-d252-4855-8d60-2f7817db5758">

Generate file 

<img width="367" alt="imagen" src="https://github.com/opnsense/core/assets/46072913/83e03984-5c7f-49c9-b1b0-0b8e23b14019">

In documentation OpenVPN for Topology p2p

<img width="1203" alt="imagen" src="https://github.com/opnsense/core/assets/46072913/315aefca-c739-468d-bff4-74b2a23cc60e">

**Expected behavior**

<img width="883" alt="imagen" src="https://github.com/opnsense/core/assets/46072913/1eabd51f-cd0f-458e-954a-5209efe63507">

**Describe alternatives you considered**

A clear and concise description of any alternative solutions or workaround you considered.

**Screenshots**

<img width="1162" alt="imagen" src="https://github.com/opnsense/core/assets/46072913/8c5caa1a-7eb3-4daa-b41f-b278f6b5ebed">

**Relevant log files**

<img width="1162" alt="imagen" src="https://github.com/opnsense/core/assets/46072913/ce7bb645-140c-4d19-9583-3e734e8ec0e2">

**Additional context**

**Environment**

OPNsense 23.7.10_1-amd64
FreeBSD 13.2-RELEASE-p7
OpenSSL 1.1.1w

**Comment by AdSchellevis** [comment]
choose a valid subnet? /32 is a single address, you need at least two to calculate both ends. 

https://github.com/opnsense/core/blob/549c180e92d6a56f19f9b6a8d29286c5e5d86956/src/etc/inc/plugins.inc.d/openvpn.inc#L985-L989

**Comment by hvalencia89** [comment]
Documentacion OpenVPN 

https://community.openvpn.net/openvpn/wiki/Concepts-Addressing

Examples for p2p topology

<img width="1207" alt="imagen" src="https://github.com/opnsense/core/assets/46072913/c4d76e17-b9b1-4c4b-90a7-f08ffcf22c9d">

<img width="1198" alt="imagen" src="https://github.com/opnsense/core/assets/46072913/9a90a919-79a2-4bce-a29c-9687407b7845">


Logs OPNsense

<img width="1054" alt="imagen" src="https://github.com/opnsense/core/assets/46072913/36fb7355-f1ef-40aa-bad9-d5f3c0c59869">

<img width="1039" alt="imagen" src="https://github.com/opnsense/core/assets/46072913/93ed1436-84dc-4e46-9d01-0961fa722b13">

<img width="1364" alt="imagen" src="https://github.com/opnsense/core/assets/46072913/a1ef469b-dd49-4e81-9621-6c5088b88e42">


And what is the correct format ip for this case Topology P2P ?

**Comment by AdSchellevis** [comment]
.. I know what the documentation looks like, merely explaining here topology subnet expects two addresses (server, client) which in our case is specified by a network. /32 is a host, anything smaller than that is a net....  (https://docs.opnsense.org/manual/vpnet.html#client-specific-overrides)

**Comment by hvalencia89** [comment]
What is the correct format  to place the ips so that p2p works properly in the menu 
VPN: OpenVPN: Client Specific Overrides

**Comment by htoxqui89** [comment]
Hello Guys,

Where do you store the Topology variables "subnet", "net 30" and "p2p" to be able to make some adjustments or do I have to design the moto to obtain them from the file?

Greetings

**Comment by htoxqui89** [comment]
I cat not view value "subnet", "net 30" and "p2p" for this server running in my lab 

Array $server 

<img width="376" alt="imagen" src="https://github.com/opnsense/core/assets/165633564/2e66520b-82ec-429a-9e43-186a9c3d6b6d">

Array settings

<img width="366" alt="imagen" src="https://github.com/opnsense/core/assets/165633564/aff1abc2-8a91-4a04-bf84-a229aeb2edae">
