### ISSUE TITLE
Automatic synchronization with Active Directory not work

### ISSUE THREAD

**Issue by hotmax22** [opnsense/core#7074]
We bought a business subscription. Automatic synchronization does not work.

**As of version business edition 21.10, the system will automatically query the LDAP servers and remove non-existing users. (not available in the community version of OPNsense)**

**Comment by AdSchellevis** [comment]
The cleanup is only in the business edition, the sync on login is standard (https://docs.opnsense.org/manual/how-tos/user-ldap.html#step-1-1-optional-synchronize-groups)

**Comment by hotmax22** [comment]
What didn't you like about the phrase : We bought the business version and auto-synchronization with LDAP does not work for us"

**Comment by AdSchellevis** [comment]
not sure what you are referring too, I'm merely stating that the removal part is automatic, creation is on login when properly configured.

**Comment by hotmax22** [comment]
We have to manually import and delete users from AD, regardless of payment. Neither automatic user creation nor automatic deletion works. Actually, nothing changes from buying a business subscription. Or maybe we're doing something wrong? 
We would like to see at least an automatic deletion of the user if he was deleted from AD

**Comment by AdSchellevis** [comment]
you can manually run the automatic cleanup using `/usr/local/opnsense/scripts/OPNBEcore
/ldap_sync_cleanup` , any issues are reported to the audit log
