### ISSUE TITLE
NDProxy support in OPNsense

### ISSUE THREAD

**Issue by andromaks** [opnsense/core#7079]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

My mobile ISP provides /64 for me. This is the only internet connection at my place. Speed and latency is good.
I would like to connect my homelab to IPv6. OPNsense is my router.
My ISP is not willing to provide Prefix Delegation for mobile internet. At same time mobile internet becomes more and more popular as the main internet connectivity.

A clear and concise description of what the problem is including your motivation for the request,
i.e. "For the purpose of [...] I am missing a solution that will [...]."

I checked that FreeBSD supports NDProxy. It would be interesting that OPNsense would support it also.
This will allow me to use /64 from my mobile ISP for LAN devices.

(e.g. I would like an input field in the `/ui/firewall/alias` which would add .... to ....)

I have 2 alternatives:
- configure NDProxy kernel module by myself and pray that it will not break anything in OPNsense
- change OPNsense to something else.

A clear and concise description of any alternative solutions or features you considered.

Thank you very much for support.

**Comment by doktornotor** [comment]
See https://github.com/opnsense/plugins/issues/3609

**Comment by andromaks** [comment]
Thanks. 

More and more people are interested in this.

**Comment by fichtner** [comment]
That’s good. Is somebody interested enough that a FreeBSD port exists yet? 😊

**Comment by MCterra10** [comment]
> That’s good. Is somebody interested enough that a FreeBSD port exists yet? 😊

Yes
https://www.freshports.org/net/ndproxy/

**Comment by MCterra10** [comment]
Glad to see there's some other people interested since my original issue (now on the plugins repo)

**Comment by HyperEr00** [comment]
> Glad to see there's some other people interested since my original issue (now on the plugins repo)
> 
> @andromaks fyi I have built ndproxy myself and use it with opnsense with no problems. You will need to clone the OPNsense kernel sources and ports tree for FreeBSD yourself though. And you need to rebuild it each kernel update.

Noob here, can you provide instructions how to do it?

**Comment by MCterra10** [comment]
> > Glad to see there's some other people interested since my original issue (now on the plugins repo)
> > @andromaks fyi I have built ndproxy myself and use it with opnsense with no problems. You will need to clone the OPNsense kernel sources and ports tree for FreeBSD yourself though. And you need to rebuild it each kernel update.
> 
> Noob here, please can you provide instructions how to do it?

https://gist.github.com/MCterra10/7e3930e54db0be10f42dd999e3263560

See this script, I'd try executing line by line and check over things, as I haven't tested it.
Basically you need to clone the OPNsense kernel source code, then the FreeBSD ports repository, and build it from source code for the OPNsense kernel.

You need to rebuild with every OPNsense kernel update btw. You don't have to clone the repos all over again though. Update the script and use git pull instead of the rm -r and git clones

**Comment by HyperEr00** [comment]
Thank you very much for the plugin. I will test it over the weekend and upload some feedback.

**Comment by Monviech** [comment]
@HyperEr00 Hey thanks that you will test it. You can also wait for the release in the next OPNsense version, its not urgent.

Im curious about your infrastructure. How do you plan to use it?

Or are you already using it from CLI with the freebsd pkg and custom rc script?

If yes, how does your `sysctl -a | grep -i ndproxy` look like?

How does your OPNsense configuration look like, especially WAN/LAN interface, Router Advertisement, SLAAC/DHCPv6?

Thanks :)

**Comment by Monviech** [comment]
For reference, my working test setup configuration. Added since there is literally nothing online about how to configure it properly:

https://forum.opnsense.org/index.php?topic=44071

**Comment by HyperEr00** [comment]
i followed the settings you posted in forum but clients can't get ipv6, only local. 
in the logs i saw this 
2024-11-20T14:29:35	Notice	kernel	<7>cannot forward src fe80:2::8106:cc5c:3857:a616, dst 2a00:1450:4001:61::a, nxt 17, rcvif vtnet0, outif re0	
2024-11-20T14:29:33	Notice	kernel	<7>cannot forward src fe80:2::8106:cc5c:3857:a616, dst 2a00:1450:4001:61::a, nxt 17, rcvif vtnet0, outif re0	
2024-11-20T14:29:32	Notice	kernel	<7>cannot forward src fe80:2::8106:cc5c:3857:a616, dst 2a00:1450:4001:61::a, nxt 17, rcvif vtnet0, outif re0	
2024-11-20T14:29:31	Notice	kernel	<7>cannot forward src fe80:2::8106:cc5c:3857:a616, dst 2a00:1450:4001:61::a, nxt 17, rcvif vtnet0, outif re0	
2024-11-20T14:29:31	Notice	kernel	<7>cannot forward src fe80:2::8106:cc5c:3857:a616, dst 2a00:1450:4001:61::a, nxt 17, rcvif vtnet0, outif re0	
2024-11-20T14:29:31	Notice	kernel	<7>cannot forward src fe80:2::8106:cc5c:3857:a616, dst 2a00:1450:4001:61::a, nxt 17, rcvif vtnet0, outif re0	
2024-11-20T14:29:18	Notice	kernel	<7>cannot forward src fe80:2::8106:cc5c:3857:a616, dst 2a00:1450:4001:81c::2002, nxt 6, rcvif vtnet0, outif re0

**Comment by fichtner** [comment]
that's normal for SLAAC devices (infamously Android phones) using a link-local address to try and talk to GUA. They didn't see any RAs.

**Comment by HyperEr00** [comment]
when i change wan to slaac then i get ipv6 on lan clients with no connectivity to ipv6

**Comment by Monviech** [comment]
In my test setup the upstream router delegated a /64 prefix to the downstream router that ran ndproxy. Im not sure what setup you have, but it sound different and might need different settings.
