### ISSUE TITLE
core integration of telegram notifications like pf*

### ISSUE THREAD

**Issue by oscarsmx** [opnsense/core#7080]
Like you may know, our big brother pf has telegram notifications integrated by default. So why opnsense doesn't add this and stay like the up to day modern sense that it is?

PF method to enable notifications to telegram (and others)

System>Advance>Notifcations>Insert apikey, channelid or @channelname done.

**Comment by chiragkrishna** [comment]
Definitely a +1 from my side. Moved from pfsense to opnsense missing telegram notification..

**Comment by Monviech** [comment]
I remember this one for Monit: https://github.com/kulikov-a/opn-monit2t

**Comment by hellcry37** [comment]
up on this
