### ISSUE TITLE
Improve Firewall - Log Files - Live View filtering (multiselect, missing OpenVPN/Wireguard interfaces/groups, direct input)

### ISSUE THREAD

**Issue by doktornotor** [opnsense/core#7081]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**

Using the Firewall - Log Files - Live View, filtering the view to only show OpenVPN/Wireguard interfaces (groups) is not possible.

**Describe the solution you like**

- Ability to select the VPN interfaces / groups (WG, OpenVPN)
- Ability to select multiple interfaces at the same time.
- And/or just let me input something directly, like with ports, e.g.

**Describe alternatives you considered**

Use 'interface' - 'does not contain' ... to filter out all other interfaces. Annoying waste of time, even more so since there is no multiselect available. Even with this workaround, you will get all the VPN firewall hits shown, not possible to separate WG from OpenVPN, or just show specific WG/OpenVPN interfaces.

**Comment by doktornotor** [comment]
While here, showing the TCP flags would really help to find out why "allowed" traffic is blocked.. E,g. [this forum thread](https://forum.opnsense.org/index.php?topic=20219.0)

**Comment by kulikov-a** [comment]
doesn't the interface appear in the list if you assign it?
aren't the tcp flags visible by pressing the 'i'-button?

**Comment by doktornotor** [comment]
Uhm, yes. I'd say assigning those various VPN interfaces (with all its consequences and side-effects, including the "famous" _Default interfaces not found_ message on boot ) is not even a temporary workaround. 

Note e.g. [this](https://docs.opnsense.org/troubleshooting/openvpn.html):

> While not strictly necessary, it is possible to assign individual interfaces for OpenVPN servers and clients alike. However doing so may yield unexpected behaviour of firewall rules. _Most notably, rules created on an assigned interface of an OpenVPN Roadwarrior server are created with the reply-to directive by default, which breaks client connectivity._


And yes, the `i` button works. Again, it's about getting in information in a one second glance at the screen vs. clicking `i` per each log entry line.
