### ISSUE TITLE
Static /31 address is force to use DHCP server

### ISSUE THREAD

**Issue by kabaga** [opnsense/core#7085]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [ x ] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [ x ] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

I have another interface opt15 and this is a point-to-point link to another router. The subnet is /31. The issue now is the DHCP server was complaining that the range was wrong. I could not disable the DHCP server. The DHCP services has stopped at this point. I could not start it due to the problematic force DHCP service to the interface that does not need it.

*Tip*: to validate your setup was working with the previous version, use opnsense-revert (https://docs.opnsense.org/manual/opnsense_tools.html#opnsense-revert)

**To Reproduce**

1. Add a new VLAN interface
2. Enabled the VLAN interface
3. Give the VLAN interface a static IP with a /31 mask
4. Go to DHCP server and disable the DHCP server

**Expected behavior**

I should be able to disable the DHCP server for this interface. 

**Describe alternatives you considered**

The DHCP server should be optional. Not all interface need to be a DHCP server for every subnets.

**Screenshots**

N/A

**Relevant log files**

N/A

**Additional context**

N/A

**Environment**

N/A

OPNsense 23.7.10_1-amd64
FreeBSD 13.2-RELEASE-p7
OpenSSL 1.1.1w

**Comment by fichtner** [comment]
I’m wondering why it would be enabled in the first place unless it’s a leftover from another interface. I mean you clearly did not want it or it even makes sense. 😉

I need to double check if unassign deletes the DHCP server but I would think it does which only leaves switching interfaces which leaves DHCP running on purpose?


Cheers,
Franco

**Comment by fichtner** [comment]
The assignment part is as I mentioned, but I've added c2f7998 to be able to disable a server with an invalid range.

    # opnsense-patch c2f7998


Cheers,
Franco
