### ISSUE TITLE
System - Trust: Do not delete certificates when removing a CA

### ISSUE THREAD

**Issue by doktornotor** [opnsense/core#7088]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

So I was doing some Xmas cleaning and removed a couple of external CAs from System - Trust - Authorities. Unfortunately, it nuked my webgui certificate which was in use. Needless to say, this is completely unexpected and causes severe breakage.

**To Reproduce**

1. Add an external CA.
2. Add a certificate issued by that CA.
3. Configure WebGUI to use that certificate.
4. Delete the previously added CA.
5. WebGUI certificate gone.

I assume this happens with any CA, not just external, and any certificates, not just webgui. Not willing to test ATM, need another VM test setup where these experiments do no wreak havoc.

**Expected behavior**

When deleting a CA, do not delete certificates which are in use. Ideally, do not ever delete any certificates when deleting a CA. Removing certificates in use is already disabled in System - Trust - Certificates, but this apparently is not the case with System - Trust - Authorities.

Software version used and hardware type if relevant, e.g.:

OPNsense 23.7.10_1 (amd64).

**Comment by AdSchellevis** [comment]
luckily you can easily revert using the history, but I agree we shouldn't drop these.

**Comment by AdSchellevis** [comment]
@doktornotor I was working on some cleanups and changes in the trust section, https://github.com/opnsense/core/commit/5cf738f6e7a3cd481c8c009d9e3108f96f318228 should fix your issue as well, but does require https://github.com/opnsense/core/commit/52fe119e0c82cd4b9613dd80263d6290c3d62358 too.

**Comment by doktornotor** [comment]
That's a big one. Only did a quick test for now:
- create an internal CA
- issue a couple of certs using that CA
- delete the CA

Certificates are still there. 👍

**Comment by doktornotor** [comment]
@AdSchellevis - will play with it more today (the OCSP AIA part works nicely, also the info button). 

Just to be clear, to fix the actual bug here, [this one line](https://github.com/opnsense/core/commit/5cf738f6e7a3cd481c8c009d9e3108f96f318228#diff-e81998824891dd279171e1a66f6897d3c5f198f7b66dd7b06385a9f8fe1e77c8R257) is the only part I need, correct?

**Comment by AdSchellevis** [comment]
@doktornotor yep, that's the one liner, but since I was already working on that file I couldn't stash that separately for you.

**Comment by doktornotor** [comment]
Great, thanks. I just need something way less intrusive ATM for production boxes that got migrated with all the cruft.
