### ISSUE TITLE
Multiple selection for user privilege removal

### ISSUE THREAD

**Issue by andreas-p** [opnsense/core#709]
Currently, each single user privilege must be deleted + acknowleged individually. This should be a column of checkboxes to delete a selection.
Alternatively, a solution using two listboxes (left: available privilege, right: assigned privilege) could be implemented. This would enable some privilege hierarchy, i.e. groups of privileges that are assigned or removed with a single selection.

**Comment by AdSchellevis** [comment]
changed privilege edit in https://github.com/opnsense/core/commit/e74f0c2a42a2c27ef4a39a912d897bfc9030bb9b
