### ISSUE TITLE
set skew in CARP manually

### ISSUE THREAD

**Issue by magiclu** [opnsense/core#7093]
**Is your feature request related to a problem? Please describe.**

I want to transfer from pfsense to opnsense. I used 2 vitural machine in 2 different computers to do CARP . I have 2 internet service, one for each machine .I use two CARP IPs as load balancing . 
OPNSENSE lan IPs:
192.168.99.3
192.168.99.4

CARP IPs:
192.168.99.13 means 192.168.99.3 as master
192.168.99.14 means 192.168.99.4 as master

My use case:  one computer is using 192.168.99.13 as gateway. Downloading at max speed.  other computers is using 192.168.99.14 as gateway. And they are not affected by that computer's downloading. 

<img width="670" alt="image" src="https://github.com/opnsense/core/assets/3338197/724c801d-e4bd-4d03-bc96-7ade4e5c6c9b">

If I understand it correctly 
advbase:
Specifies the base of the advertisement interval in seconds. The acceptable values are 1 to 255.

is only set the Advertising frequency not how important the firewall is
Somehow I can set the value higher. And it seems to be working as I wanted .But it is wrong 

If i do a HIGH AVAILABILITY sync the backup's skew will become 100. So skew is an important number but currently not allow user to set it manually
<img width="921" alt="image" src="https://github.com/opnsense/core/assets/3338197/ba3f0287-f4c8-4286-8cb2-2490bcb1db92">

**Describe the solution you like**

add this option as in pfsense.And after some rearch it was possible to do this in opnsense before .But it is removed in the latest version

![image](https://github.com/opnsense/core/assets/3338197/5730906e-bbae-4926-8ad4-b9998b22a33a)
https://youtu.be/-fR3ULmaM-c?si=dhEUugcCosPJTI_s

**Additional context**

Add any other context or screenshots about the feature request here or links to relevant forum thread or similar
<img width="461" alt="image" src="https://github.com/opnsense/core/assets/3338197/6018816e-3bc2-46e4-97d6-aa1cbc3cf78e">

<img width="864" alt="image" src="https://github.com/opnsense/core/assets/3338197/86ae8295-5b96-4411-8c9b-672825ba5c5e">

<img width="890" alt="image" src="https://github.com/opnsense/core/assets/3338197/ea29cf7b-2575-47e3-8f13-8962ee92e5bd">

**Comment by AdSchellevis** [comment]
advanced mode?

**Comment by magiclu** [comment]
> advanced mode?

I did not see that .thanks.

**Comment by AdSchellevis** [comment]
close?

**Comment by magiclu** [comment]
> close?

yes
