### ISSUE TITLE
Shaper Template Exception

### ISSUE THREAD

**Issue by aque** [opnsense/core#7096]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**
I converted my install to use LAGG and VLAN tags, and I am updating my rules to use the new interfaces. I ran into an issue with the traffic shaper refusing to update. Logs show the following error under 23.7.10_1.

```
error generating template OPNsense/IPFW : Traceback (most recent call last):
   File "/usr/local/opnsense/service/modules/template.py", line 262, in _generate
     content = j2_page.render(cnf_data)
   File "/usr/local/lib/python3.9/site-packages/jinja2/environment.py", line 1301, in render
     self.environment.handle_exception()
   File "/usr/local/lib/python3.9/site-packages/jinja2/environment.py", line 936, in handle_exception
     raise rewrite_traceback_stack(source=source)
   File "/usr/local/opnsense/service/templates/OPNsense/IPFW/ipfw.conf", line 185, in top-level template code
     physical_interface(rule.interface) }} {%
   File "/usr/local/lib/python3.9/site-packages/jinja2/utils.py", line 83, in from_obj
     if hasattr(obj, "jinja_pass_arg"):
 jinja2.exceptions.UndefinedError: 'physical_interface' is undefined
  During handling of the above exception, another exception occurred:
  Traceback (most recent call last):
   File "/usr/local/opnsense/service/modules/template.py", line 328, in generate
     for filename in self._generate(template_name, create_directory):
   File "/usr/local/opnsense/service/modules/template.py", line 265, in _generate
     raise Exception("%s %s %s" % (module_name, template_filename, render_exception))
 Exception: OPNsense/IPFW OPNsense/IPFW/ipfw.conf 'physical_interface' is undefined
```

I have an older lab VM running 23.7.3 and it does not have this problem.

**To Reproduce**

1. Create a pipe - values are not relevant
2. Create a rule with the following parameters:
Sequence: 1
Interface: Loopback
Interface 2: Loopback
_[Other values are set to their defaults]_
Direction: both or out - error does not occur with "in"
Target: pipe created on step 1

The issue is tied to "Interface 2"; no error if it is set to None.

**Expected behavior**

configd generates the ipfw file without errors.

**Environment**
OPNsense 23.7.10_1-amd64
FreeBSD 13.2-RELEASE-p7
OpenSSL 1.1.1w

**Comment by AdSchellevis** [comment]
https://github.com/opnsense/core/commit/c9d191f10d4e2a7a1e7dc14c670b3d8fbac6402d should do the trick, it looks like we missed a spot in our refactor.

**Comment by fichtner** [comment]
will consider a hotfix, but currently waiting for openssh update to hit FreeBSD ports

**Comment by aque** [comment]
Thanks @AdSchellevis! I confirm the patch resolved it.
