### ISSUE TITLE
Allow overriding ipxe boot filename on DHCP static mappings

### ISSUE THREAD

**Issue by ruifung** [opnsense/core#7097]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**

So, the netboot filename can be overridden in a static mapping in DHCP settings, but this means if you want to set a specific IPXE script for that host, you would need to compile ipxe with the embedded script.

**Describe the solution you like**

The main netboot section in DHCP settings has an option to set the ipxe boot filename, this option should be added to the static mapping configuration as an override option too.

**Describe alternatives you considered**

The existing features already sort of allow this, but requires recompiling ipxe with a new embedded script every single change. Being able to just pass a new URL in the dhcp static mapping would be great.

**Additional context**

Add any other context or screenshots about the feature request here or links to relevant forum thread or similar

**Comment by AdSchellevis** [comment]
it might be better to check what would be needed in Kea (upcoming for ipv4 in 24.1), isc-dhcp is EOL and we should aim for at least a feature freeze.
