### ISSUE TITLE
OpenVPN: cannot redirect all traffic in new "instance" version.

### ISSUE THREAD

**Issue by Stifler6996** [opnsense/core#7098]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**
Old version:
![image](https://github.com/opnsense/core/assets/12870096/951fc496-97c0-465d-9d1e-a894b1898f23)

New version does not have this support.

**To Reproduce**

Go and look, its not there. There is no documentation identifying this option in the new "instances" setup either.

**Expected behavior**

Tell the client that all traffic should be redirected to the VPN tunnel.

**Comment by AdSchellevis** [comment]
Miscellaneous --> Redirect gateway ?

**Comment by Stifler6996** [comment]
None of the options includes the "block-outside-dns" modifier which is included in the old version.

**Comment by AdSchellevis** [comment]
didn't say it did nor did you ask (it's a different option in the same area), but in that case we can close this ticket as a question for block-outside-dns is already in the ticket system (https://github.com/opnsense/core/issues/6770). 

Opening a PR for discussion isn't very difficult and helps progressing wishes.
