### ISSUE TITLE
Addition of a "moveCommand" in the UI Bootgrid Plugin

### ISSUE THREAD

**Issue by Monviech** [opnsense/core#7100]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**

When using the UI Bootgrid Plugin, all saved data is written into the config.xml file in the order it was saved. The user can't decide a new order without deleting and re-adding the entries in a different order.

https://github.com/opnsense/core/blob/master/src/opnsense/www/js/opnsense_bootgrid_plugin.js

**Describe the solution you like**

I would like a command button that could trigger a "moveCommand", kinda like the "legacy_move_config_list_items" and "move selected rule before this rule" button that the firewall rules use. So the user can mark a checkbox and click the move button. The currently selected entry will be moved in front of the selected line. That would then change the spot in the config.xml where the data is saved.

When the "data-column-id="commands" is imported into the UI-Bootgrid in a view, the move button would appear and work in the same way as in the firewall rules.

**Describe alternatives you considered**

I don't really have an alternative idea for this, except telling the user to delete and re-add their configuration if the order should be changed.

**Additional context**

This kind of button would be essential for all plugins that use the UI Bootgrid Plugin, and have position sensitive configuration data, where the order of data influences the functionality of a generated configuration template. Also sorry if this already exists and I just didn't find it. ^^

**Comment by AdSchellevis** [comment]
when items are position sensitive, add a sequence number so you can sort them when extracting from the config. Item order isn't guaranteed nor should it (only legacy modules use these non explicit arrangements).

**Comment by Monviech** [comment]
Thanks for your answer. :)

It makes sense to add a https://docs.opnsense.org/development/frontend/models_fieldtypes.html#autonumberfield for position sensitive items. Though the bootgrid would lack functionality to "swap" the autonumberfield between two entries if a user would like to switch the position of an item.

Maybe there could be an additional moveCommand that checks for a standard "position" "autonumberfield", almost like the toggleCommand checks for an "enabled" "booleanfield".

Then when a user marks a checkbox in the UI Bootgrid, and presses the respective "move" button, the function "gets" both UUIDs, and extracts the "position", and swaps them while "set".

**Comment by AdSchellevis** [comment]
adding this as a generic feature likely isn't very useful as over 80% of the array typed items are not position sensitive at all (I think we only have a couple where a priority/sequence is being used).

**Comment by kulikov-a** [comment]
I think the plugin maintainer could add 'up' and 'down' buttons to the grid and corresponding functions to the controller? (perhaps the 'autonumbering shrink ' function will be needed on model save?)

**Comment by Monviech** [comment]
@AdSchellevis Okay. I thought I would suggest it because I thought in the future the pf firewall/nat rules might need it too when they're moved out of legacy.

@kulikov-a Your suggestion sounds nice, I think I will try an own solution for that. I was mainly suggesting it because I thought it could maybe become a shared functionality.

I'm closing this for now. Thank you all for your feedback. :+1:
