### ISSUE TITLE
voucher generation freeze

### ISSUE THREAD

**Issue by VirusEcks** [opnsense/core#7105]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

Voucher generation freeze and causes any call to the voucher api and voucher ui web to timeout as well.

> Fatal error: Maximum execution time of 900 seconds exceeded in
> /usr/local/opnsense/mvc/app/library/OPNsense/Auth/Voucher.php on line 212

**To Reproduce**

1. Go to 'System > Access > Servers'
2. Create a New Voucher Server
3. Set "less secure passwords" and "username length: 0"'
4. Goto 'Services > Captive Portal > Voucher'
5. Generate Vouchers
6. Now every generation will cause Firewall to freeze and any call to voucers will timeoout

**Describe alternatives you considered**

there should be a smart choice when generating passwords or using voucher system that will not consider the susername if it's 0 and hide the username field on the captive portal

**Additional context**

that same problem exists on 23.1 up to 23.7.10_1 

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 23.7.10_1 (amd64).
Intel(R) Xeon(R) CPU E5-2680 v4 @ 2.40GHz x 28

**Comment by AdSchellevis** [comment]
validation added in https://github.com/opnsense/core/commit/d7a858de3449ae3aecf60e7d074d3adb0142308d ,  if you want a single token you can concat user+pass in the template.
