### ISSUE TITLE
DHCPv6 lease display chokes on DUIDs containing 0x20

### ISSUE THREAD

**Issue by eamaclean** [opnsense/core#7107]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

When any IAID+DUID contains the byte 0x20, this gets stored as a space character in the lease file. Line 112 in get_leases6.py will then split the string on this character resulting in an incorrectly parsed DUID. 

For example, the IAID+DUID for this machine is "D{\020\011\000\001\000\001$\377L \020{D{\322\017", or 44:7b:10:09:00:01:00:01:24:ff:4c:20:10:7b:44:7b:d2:0f in hex. This will get split after 4c, and this results in the DUID being displayed as 00:01:00:01:24:ff in the web UI, which in this case it also coincidentally believes is a valid MAC address and displays this until the NDP table corrects it.

In some cases this also causes a more significant parsing error which will break display of all leases, an example string: " : \314\000\001\000\001- \203j\252\317\314 : " - 20:3a:20:cc:00:01:00:01:2d:20:83:6a:aa:cf:cc:20:3a:20 in a more readable form.

[fb2d2f6 ](https://github.com/opnsense/core/commit/fb2d2f63d111ce2c49e090e0f127c9b127479e71) seems to have been an attempt to fix this by stripping leading and trailing whitespace, however this whitespace is valid data, and cases where it's not trailing or leading will still break the parser.

**To Reproduce**

Have any DUID containing 0x20 with a DHCPv6 lease and visit the lease page.

**Expected behavior**

Correct display of all leases. Perhaps substitute whitespace within the string with the octal representation?

**Environment**

OPNsense 23.7.10

**Comment by AdSchellevis** [comment]
@eamaclean can you try https://github.com/opnsense/core/commit/5b0b4139b60dbd7834601c7e42fb2f17b4a5c71e ? it should fix the parsing issue and includes some cleanups for the rest of the script.

```
opnsense-patch 5b0b413
```

**Comment by eamaclean** [comment]
That does seem to do the trick, thanks! One note, it no longer appears to display MAC addresses for clients not currently marked as online (ie. in the NDP table), is that expected behaviour or unintentional?

**Comment by AdSchellevis** [comment]
@eamaclean thanks for confirming, I'm not aware of changes in the ndp table handling, but I'll double check to be sure.

**Comment by AdSchellevis** [comment]
these mac addresses might have been side affects of the parsing issue caused by the strip()

https://github.com/opnsense/core/blob/a59e936389cbdab847460200c3e604053a11eacd/src/opnsense/mvc/app/controllers/OPNsense/DHCPv6/Api/LeasesController.php#L175-L193

if `duid` starts with `00:01` or `00:03` it should calculate one according to the code above.

**Comment by AdSchellevis** [comment]
@eamaclean thanks, https://github.com/opnsense/core/commit/2ef916de0cd387b887498b8197e623e91509699e should fix the off by one issue here.
