### ISSUE TITLE
DHCP: API for Static leases

### ISSUE THREAD

**Issue by ansibleguy** [opnsense/core#7108]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**

Greetings!

Is it planned that there will be an API for managing the DHCP leases?
It is pretty much the most asked-for feature for my [Ansible collection](https://github.com/ansibleguy/collection_opnsense).
I understand the users, as some networks have hundreds of leases that should be dynamically extendable.

Currently it seems to call `/services_dhcp.php?if=<IFNAME>` - that cannot easily be integrated into external tools.

I've seen that [there is already a documentation](https://docs.opnsense.org/development/api/core/dhcpv4.html) for deleting them - but without a link to a XML.

**Comment by AdSchellevis** [comment]
should be superseded by https://github.com/opnsense/core/issues/6971, for ipv4 it should be in the 24.1 release.

**Comment by ansibleguy** [comment]
Good to know! Thank you for the information.

**Comment by AdSchellevis** [comment]
@AdSchellevis you're welcome, I'll see if we can add ipv6 in 24.7. Eventually we need to get rid of isc-dhcp
