### ISSUE TITLE
Firewall - Log Files - Overview "self-DOS" with search as you type

### ISSUE THREAD

**Issue by doktornotor** [opnsense/core#7109]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

Trying to search will launch a separate `queryLog.py` process for each subsequent letter, as you type. E.g., typing _crowdsec_ there will launch 8 of these processes, eat all CPU and freezing the GUI. See **Relevant log files** below.

**To Reproduce**

1. Go to 'Firewall - Log Files - Overview'.
2. Start typing into the search box.
3. Run some process monitor (`top`, `htop`) on console.
4. Watch growing number of `queryLog.py` python processes launched as you type, chewing huge amounts of your CPU for lunch.

**Expected behavior**

Stop launching processes as you type. It may be funky, but it's an absolute CPU killer.

**Screenshots**
Ugh...

![image](https://github.com/opnsense/core/assets/1075960/ff9c9370-e43f-4d58-af9e-b7ae01243d2a)

**Relevant log files**

```
/usr/local/bin/python3 /usr/local/opnsense/scripts/syslog/queryLog.py --limit 20 --offset 0 --filter crowdsec --module core --filename filter --severity Emergency,Alert,...
/usr/local/bin/python3 /usr/local/opnsense/scripts/syslog/queryLog.py --limit 20 --offset 0 --filter crowdse --module core --filename filter --severity Emergency,Alert,...
/usr/local/bin/python3 /usr/local/opnsense/scripts/syslog/queryLog.py --limit 20 --offset 0 --filter crowds --module core --filename filter --severity Emergency,Alert,...
/usr/local/bin/python3 /usr/local/opnsense/scripts/syslog/queryLog.py --limit 20 --offset 0 --filter crowd --module core --filename filter --severity Emergency,Alert,...
/usr/local/bin/python3 /usr/local/opnsense/scripts/syslog/queryLog.py --limit 20 --offset 0 --filter crow --module core --filename filter --severity Emergency,Alert,...
/usr/local/bin/python3 /usr/local/opnsense/scripts/syslog/queryLog.py --limit 20 --offset 0 --filter cro --module core --filename filter --severity Emergency,Alert,...
/usr/local/bin/python3 /usr/local/opnsense/scripts/syslog/queryLog.py --limit 20 --offset 0 --filter cr --module core --filename filter --severity Emergency,Alert,...
/usr/local/bin/python3 /usr/local/opnsense/scripts/syslog/queryLog.py --limit 20 --offset 0 --filter c --module core --filename filter --severity Emergency,Alert,...


```

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 23.7.10_1 (amd64).

**Comment by AdSchellevis** [comment]
by default it is a bit jumpy indeed, let's increase the auto search timer to 1 second to make this a bit more fluent (https://github.com/opnsense/core/commit/2ab6a8f188d735061fb98168a490cee840e3f280)

**Comment by doktornotor** [comment]
Ok, so that launched only 2 processes until I finished typing - after one minute the search finally finished the "loading" stage and spit out "No results found!"

However, no matter whether I clear the search box or leave the filter there, the processes still keep running for another about 90 seconds, doing I don't know what? I mean, this cannot be by design?

**Comment by fichtner** [comment]
90 seconds is the configd timeout?

**Comment by AdSchellevis** [comment]
commands execute until they are finished (by design, configd has a timeout., also by design)...  Did you test development as well? I'm not sure if https://github.com/opnsense/core/commit/42fd27df777ee85a0e42767a814bed5e93659f0c is available in production versions, but that might help closing the command a bit earlier when there's no receiver for data being send.

**Comment by doktornotor** [comment]
Will try and post feedback here. Sticking to console tools like (e)grep meanwhile 😉. 

I guess python is not the tool of choice for these tasks. I have an extensive regex whitelist for Unbound (about 150 entries) and it takes 4+ minutes to apply for the bunch of configured blacklists), that's python at work as well IIRC. 🤐

**Comment by kulikov-a** [comment]
Sorry for breaking into a closed request, but it’s possible to disable input until response received. should help with possible race?


https://github.com/opnsense/core/assets/36099472/6761923d-01fc-4430-b523-f301060f564b

**Comment by doktornotor** [comment]
Well, yes... That, plus a lot more than 1 second delay, TBH, I'd love to see the "realtime" search go to `/dev/null`. Not fixable. Wait for enter and move on. E.g., I still cannot make sense of what's gonna be returned in the GUI while two or more search processes are spawned while typing.

**Comment by AdSchellevis** [comment]
disabling input will lead to a lot more reports than this single one. if you're seeking grep... use grep on the console and don't ask for a gui that mimics the console.  There might be ways to better detect if someone is still waiting for an answer (or bail if not) without forcing the rest of the world to press buttons all the time (haven't looked into it, not a priority for 24.1 either).

The one second delay is trivial, although it does raise the question how slow people actually type......

**Comment by doktornotor** [comment]
Well, I think there is something **extremely** wrong with the script itself. 

`02f4bab031b57d1e30553ce08e0ec131` is the label for _"Default deny / state violation rule"_

```
# /usr/bin/time -l -h -p /usr/local/bin/python3 /usr/local/opnsense/scripts/syslog/queryLog.py --limit 20 --offset 0 --filter 02f4bab031b57d1e30553ce08e0ec131 --module core --filename filter
...
real 0.58
user 0.50
sys 0.07
     14864  maximum resident set size
         4  average shared memory size
         4  average unshared data size
       129  average unshared stack size
      1751  page reclaims
         0  page faults
         0  swaps
         0  block input operations
         0  block output operations
         0  messages sent
         0  messages received
         0  signals received
         4  voluntary context switches
        21  involuntary context switches
```

```
# /usr/bin/time -l -h -p /usr/local/bin/python3 /usr/local/opnsense/scripts/syslog/queryLog.py --limit 20 --offset 0 --filter "Default deny" --module core --filename filter
{"filters":"Default deny","rows":[],"total_rows":0,"origin":"filter"}
real 150.96
user 142.55
sys 4.31
     15376  maximum resident set size
         3  average shared memory size
         3  average unshared data size
       127  average unshared stack size
      1882  page reclaims
         0  page faults
         0  swaps
         0  block input operations
         0  block output operations
         0  messages sent
         0  messages received
         0  signals received
       765  voluntary context switches
     23638  involuntary context switches

```

Huh???

**Comment by doktornotor** [comment]
Note that when the label does **not** match anything in the logs, it takes exactly same ages as with a random word that does **not** match. I.e, the script keeps running until timeout.

**Comment by kulikov-a** [comment]
@doktornotor i don't think there is a rule name string in plain filter log. so queryLog will work harder, search longer (the whole log) and will find nothing )
don't understand what bothered you, sorry

**Comment by doktornotor** [comment]
Yes, it is not there (missing feature, can live with that). Script keeps running for no good reason until timeout when nothing matches and pegs CPU => bug.

**Comment by kulikov-a** [comment]
> keeps running for no good reason

hm. Isn't this what you demanded of it: i suspect that when "default deny" rules logging is enabled the logs are **huge**. you gave the command to search for a non-existent string in them (so limits do not work). I think the result is expected.

**Comment by doktornotor** [comment]
Well, not really sure what to say here.

```
# ls -lah `readlink /var/log/filter/latest.log`
-rw-------  1 root  wheel   6.2M Jan  2 22:04 /var/log/filter/filter_20240102.log
```
```
# /usr/bin/time -l -h -p grep "02f4bab031b57d1e30553ce08e0ec131" `readlink /var/log/filter/latest.log` | wc -l
real 1.49
user 1.39
sys 0.09
      2624  maximum resident set size
        20  average shared memory size
         8  average unshared data size
       128  average unshared stack size
       146  page reclaims
         0  page faults
         0  swaps
         0  block input operations
         0  block output operations
      1515  messages sent
         0  messages received
         0  signals received
         9  voluntary context switches
        36  involuntary context switches
   24687
```
```
# /usr/bin/time -l -h -p grep "Default deny" `readlink /var/log/filter/latest.log` | wc -l
real 0.07
user 0.00
sys 0.06
      2608  maximum resident set size
        20  average shared memory size
         8  average unshared data size
       128  average unshared stack size
       140  page reclaims
         0  page faults
         0  swaps
         0  block input operations
         0  block output operations
         0  messages sent
         0  messages received
         0  signals received
         2  voluntary context switches
         4  involuntary context switches
       0
```

**Comment by kulikov-a** [comment]
why latest only?

**Comment by doktornotor** [comment]
Dunno, guys, probably because I assumed some sane default behaviour. Being able to search / filter firewall logs in an efficient and usable way is kind of a big deal on a firewall appliance. 

Anyway, to find nothing, it takes <8s with `grep`, and 150+s (never finishes) with the python script.

```
# du -sh /var/log/filter/
107M    /var/log/filter/
```

```
# /usr/bin/time -l -h -p grep "Default deny" /var/log/filter/*.log > /dev/null
real 7.55
user 4.09
sys 3.42
      2616  maximum resident set size
        20  average shared memory size
         8  average unshared data size
       128  average unshared stack size
       144  page reclaims
         0  page faults
         0  swaps
         0  block input operations
         0  block output operations
         0  messages sent
         0  messages received
         0  signals received
        41  voluntary context switches
       725  involuntary context switches
```

Takes about 90s to spit out all the matches with grep.

```
# /usr/bin/time -l -h -p grep "02f4bab031b57d1e30553ce08e0ec131" /var/log/filter/*.log >/dev/null
real 96.88
user 91.89
sys 4.55
      2636  maximum resident set size
        20  average shared memory size
         8  average unshared data size
       128  average unshared stack size
       148  page reclaims
         0  page faults
         0  swaps
         0  block input operations
         0  block output operations
         0  messages sent
         0  messages received
         0  signals received
       507  voluntary context switches
      7088  involuntary context switches
```

If I may suggest anything, limit the search to the `latest.log` by default and add a tickbox in the GUI to search all logs. The defaults are anything but sane, seriously.

P.S. Have a great new year. 😉
