### ISSUE TITLE
net/wireguard duplicate public keys in different peers causes connection failure

### ISSUE THREAD

**Issue by KellenRenshaw** [opnsense/core#7110]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [ x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [x ] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [x ] The title contains the plugin to which this issue belongs

**Describe the bug**
Adding two peers with identical public keys to an instance doesn't throw an error.

Made a mistake transferring from a pfSense setup, accidentally used the same public key for two "different" peers. Instead of throwing a warning, the wireguard config just fails to work as expected.

It would be nice to check that the public key is unique to at least the instance and warn/error for the user if peers have duplicate public keys.

*Tip*: to validate your setup was working with the previous version, use opnsense-revert (https://docs.opnsense.org/manual/opnsense_tools.html#opnsense-revert)

**To Reproduce**
1) Configure a Wireguard instance.
2) Add two peers with the same public key, but different allowed IPs.
3) Connect and attempt to use the connection.

**Expected behavior**
It would be nice to warn or error on duplicated public keys between peers.

**Environment**
OPNsense 	23.7.10_1 (amd64)
net/wireguard version 2.5_2

**Comment by adamcstorm** [comment]
It seems that this change prevents configuring a peer with the same public key on two different interfaces though. Some privacy VPNs use the same public keys for peers when connecting to different endpoints. Is it possible to implement this check in a different way? Perhaps just a warning about duplicate keys if the interface is selected that includes a conflicting peer?
