### ISSUE TITLE
The unbound root.min.hints is outdated

### ISSUE THREAD

**Issue by doktornotor** [opnsense/core#7115]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

root.hints file (not sure why it is shipped with core) needs updating. 
- https://gitlab.isc.org/isc-projects/bind9/-/issues/4101
- https://www.lacnic.net/6868/1/lacnic/lacnic-asigna-recursos-de-numeracion-al-servidor-raiz-de-usc_isi

**Comment by fichtner** [comment]
Forgive me for refetching the file to check the validity of the submission... I've committed https://github.com/opnsense/core/commit/f1ae49b803a since the diff is smaller than what you have here and the upstream file checksum then matches
