### ISSUE TITLE
Having a lot of blacklisted domains in the proxy ACL slows down the remote ACL feature

### ISSUE THREAD

**Issue by oparoz** [opnsense/core#712]
### Env

* 16.1
* Chrome browser
* Large list of domains in the standard ACL

### Steps to reproduce

1. Open the *Remote Access Control Lists* tab in *Proxy Server: Administration*
2. Click on the [+] to add a list.

### Expected result

A modal window should open instantaneously.

### Actual result

It takes more than a minute to get the dialogue.
Sometimes the windows ends up blank and the tab has to be killed.

**Comment by oparoz** [comment]
Still happening on 16.1 release.

**Comment by oparoz** [comment]
Just wondering if it's related to the long time it takes for the *Administration* page to load, due to the large blacklist.

**Comment by fichtner** [comment]
How large is "large"?

**Comment by oparoz** [comment]
This list: http://pgl.yoyo.org/adservers/

**Comment by oparoz** [comment]
If I remove the domains from the ACL field, then things go back to normal, so it would be good to figure out why this is slowing down the whole interface.

**Comment by AdSchellevis** [comment]
timeout, no other reports with similar issues. tested with large blocklists from different providers.
