### ISSUE TITLE
Show suricata rules description in user defined policy

### ISSUE THREAD

**Issue by deajan** [opnsense/core#7121]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**

I am adjusting some suricata rules depending on my networks.
In order to do so, I have to add rule SIDs which I want to drop / accept in rule adjustements.

![image](https://github.com/opnsense/core/assets/4681318/dcf92cc0-458a-482d-aa63-b6d3610ffcff)

The problem is that once this list grows a bit or time passes, I don't know what the rules I added actually do. I have to lookup the SIDs manually.

**Describe the solution you like**

It would be nice to have the rule description, as present in the alert window. See the (badly) edited screenshot below:

![image](https://github.com/opnsense/core/assets/4681318/88b83c55-43df-4de6-bd32-82db33e68d88)

**Describe alternatives you considered**

As of today, I lookup each rule manually, which is really time consuming.

**Additional context**

Piggybacking this feature request with two more related options I'd love to see in the suricata configuration:
1. Having a bulk import / export interface for rule adjustments, to transfer from one OPNSense to another
2. Have a button on alerts allowing to create a rule adjustement from an existing alert

Thank you for considering this.

**Comment by AdSchellevis** [comment]
The rule message and source we can offer (https://github.com/opnsense/core/commit/3daff54655730332240b95b497eebbd453ffb4f1). Should probably be in time for 24.1

Originally we tried to get rid of the rule modifications as the policies can match patterns in a single rule, but as metadata in the rules doesn't appear to be very simple and consistent, it does seem like a good idea to make sure people can find descriptions for the separate rules.

**Comment by deajan** [comment]
Makes sense ^^
You just removed one of my biggest thorns in this module. Again, thank you alot.
