### ISSUE TITLE
 Issue Report - FreeOTP Unknown Issuer in Issuer Field

### ISSUE THREAD

**Issue by Gaitonde007** [opnsense/core#7126]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [Yes] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [Yes] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

I have encountered an issue with FreeOTP on OPNsense where the issuer field displays as "unknown." This occurs when attempting to use FreeOTP for two-factor authentication within the OPNsense environment.

**To Reproduce**

Steps to reproduce the behaviour:

1. Install FreeOTP on a device.
2. Set up two-factor authentication in OPNsense using FreeOTP.
3. Generate a token and observe the issuer field.

**Expected behaviour**

I expected the issuer field in FreeOTP on OPNsense to display the correct and expected issuer information.  Unfortunately i don't see an option to set the issuer field.

**Screenshots**

![1b60104c-4254-4f42-ad0f-614876abda95](https://github.com/opnsense/core/assets/52353158/26ba52c4-4290-4d05-a344-780fc6fe4cee)

**Additional context**
I do not get this error on Google Authenticator, it displays the hostname given to the OPNsense correctly. 
Kindly provide steps to resolve this issue.

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 24.1 (amd64).

**Comment by AdSchellevis** [comment]
probably better ask them what they need to display an issuer... you can find their GitHub repo's at https://github.com/freeotp

**Comment by Gaitonde007** [comment]
> probably better ask them what they need to display an issuer... you can find their GitHub repo's at https://github.com/freeotp

Hi, sure will do. 
FYI: with pfSense it displays as FreeRadius Server since external authentication is built into that package.

Thanks.

**Comment by joggee-fr** [comment]
Hi @AdSchellevis,
I get here following https://github.com/freeotp/freeotp-android/issues/387 and analyze URI returned by OPNsense in this comment https://github.com/freeotp/freeotp-android/issues/387#issuecomment-1926668075.
Just to know, did you except `$config['system']['hostname']` to be viewed as the issuer here?

**Comment by AdSchellevis** [comment]
@joggee-fr yes, usually it shows `user@domain` in these type of apps.

**Comment by joggee-fr** [comment]
@AdSchellevis 
As I understand the docs on OTP URI format, in the case `otpauth://totp/User1@Mail_VPN?secret=`, `User1@Mail_VPN` is the account name. FreeOTP seems to choose to display the issuer but none is precised here.
`OPNsense:User1@Mail_VPN` would certainly display `OPNsense` as issuer for example. Or it seems it can also be added as URI parameters `OPNsense:User1@Mail_VPN?secret=&issuer=OPNsense`.

**Comment by AdSchellevis** [comment]
I don't mind adding an issuer, but I don't expect them to have a logo on their end....

**Comment by AdSchellevis** [comment]
@joggee-fr can you try https://github.com/opnsense/core/commit/12001a32f2605c7356c82f6ac26803d80a686fcd ? install via:
```
opnsense-patch 12001a3
```

**Comment by joggee-fr** [comment]
@Gaitonde007, as you are the initial reporter could you give this patch a test?

**Comment by Gaitonde007** [comment]
> @Gaitonde007, as you are the initial reporter could you give this patch a test?

Hi @joggee-fr , I have tested on Android and it works as expected. Issue on IOS still persists.

Thanks

**Comment by joggee-fr** [comment]
@Gaitonde007, I am not aware of the iOS version of the FreeOTP application. However, did you open an issue there?
