### ISSUE TITLE
Allow custom Firewall rules before auto generated rule / allow auto generated rules to be configured/deleted

### ISSUE THREAD

**Issue by c33s** [opnsense/core#7127]
voting for a reopen of https://github.com/opnsense/core/issues/6502

not being able to remove/disable autogenerated rules is not helpful. in my case i want to access the webgui via the wan interface. it is because i already have a pfsense firewall and want tryout/migrate to opnsense while opnsense (via wan interface -> dhcp) is in the same network as the desktop.

i know that "you should not make the webgui accessible via wan" but currently i know what i am doing and the current behavior of opnsense is just a blocker and no help at all.

creating a rule on the wan interface which would allow it, does not work. the traffic gets blocked by "Default deny / state violation rule"

additionally i don't have ipv6, so i would like to remove all the pregenerated ipv6 rules (dhcpv6,...)

not being able to click on a auto generated rule also does not help. the rule overview is not as detailied as the detail view, so being able to view the details of auto generated rules would help (same for aliases, i really prefer to be able to click on an external/automatic/internal alias to see the content of the alias.

searching for solutions only led to "works as intended", "not going to happen", ... which feels like the wrong approach as i often read things like "switching back to pfsense" because of that. for me it feels similar. i wanted to go with opnsense instead of pfsense but no easy way to let the firewall do what i want is a real blocker. 

please reconsider you position.

**Comment by fichtner** [comment]
To be frank, what automatic rules are you not able to disable?


Cheers,
Franco

**Comment by c33s** [comment]
![image](https://github.com/opnsense/core/assets/649209/e6b20ff4-6c87-4a43-bad5-d226bc62d66f)

everything with ipv6
and i would like to have a rule which allows https access to the webgui from the wan but even if i create a rule for it is getting blocked by the default deny rule, which is strange because it is a "last match" rule and as far as i understand a "first match" rule which was defined by the user should be higher in priority shouldn't it?

**Comment by fichtner** [comment]
So you want to remove those rules that allow you to use DHCPv6 client on WAN... which effectively disables your IPv6 unless you add all the rules manually? The safest option is to disable IPv6 on WAN in this case?

**Comment by c33s** [comment]
@fichtner i want to disable ipv6 rules because my provider doesn't support ipv6 and i also don't use ipv6 in my lan. so all the predefined ipv6 rules only pollute my interface for nothing. it is not about allowing dhcpv6 on wan.

for the WAN i want to create a rule which allow access to the webgui (it is just for a lab setup) but as i wrote above, even if i create a rule which allows webgui access over the lan interface , access gets blocked by the default rules.

**Comment by bugoff** [comment]
I have the same issue as @c33s. 

My opnsense boxes have their http / ssh interface open on wan for certain static ip's, and this isn't possible anymore. Is there an option to disable this behaviour as i use this on all my remote firewalls? This was possible on older versions.

**Comment by AdSchellevis** [comment]
@bugoff rules haven't changed recently, you can use the "Automatically generated rules" button on the interface to see which automatic rules apply on an interface (and usually how to disable them as well).

**Comment by bugoff** [comment]
@AdSchellevis it has been a while since i installed a new device, so i haven't noticed it before. 
The sshlockout rules don't have any info on them, and  i can't find a way to disable them. If i read them correctly they reject traffic on the wan interface on port 22 and 443.

![Screenshot 2024-05-31 at 14 33 35](https://github.com/opnsense/core/assets/1258672/5025869c-ee08-46b7-903d-d529518f9ee4)

I added 2 new rules to enable ssh / https traffic to the firewall on port 22 and 443, but they aren't allowed.

**Comment by AdSchellevis** [comment]
ssh lockout means X faulty logins dropping your connection, that can't be an issue, but if it is, you can inspect the alias mentioned in the rule.

**Comment by bugoff** [comment]
@AdSchellevis Then i'm not really sure what i'm doing wrong here.

I'm currently testing this in my office, so it's a private range. I tested it with a floating firewall rule and a firewall rule on wan, the most basic rule i can think of. 

The rule doesn't match and it always loads the default block rule. 
On the wan interface i disabled "block private networks and block bogon networks" (just in case)

![Screenshot 2024-05-31 at 15 28 01](https://github.com/opnsense/core/assets/1258672/f47bb220-fd2f-4009-b503-3e97ff5c81cb)

![Screenshot 2024-05-31 at 15 29 13](https://github.com/opnsense/core/assets/1258672/7b9761a5-c9db-4b32-9679-ca6c0d469d5f)

**Comment by AdSchellevis** [comment]
best make sure to disable reply-to in the rule or in the advanced settings to prevent packets being send to the gateway address. I'm very sure you can allow access, our forum (https://forum.opnsense.org) might be a better place to discuss setup scenario's.

**Comment by bugoff** [comment]
For anyone having the same problem, this fixed it for me:
https://forum.opnsense.org/index.php?topic=27983.msg141843#msg141843

**Comment by willagc** [comment]
I'm encountering the same problem. It's quite inconvenient and poor user experience to restrict users from modifying these autogenerated rules.

I often resort to using `pfctl -d` frequently just to access the web UI. In my setup, Opnsense acts as a virtual firewall managing VMs within Proxmox. There's another firewall upstream, making the additional WAN rules a hassle.

**Comment by fichtner** [comment]
Can you be specific on what rules can’t be turned off?

**Comment by willagc** [comment]
> Can you be specific on what rules can’t be turned off?

Any of the auto generated wan rules. More specifically the implicit deny all rule at the top of the list.

**Comment by mrfreezer** [comment]
having the same issue and spent ~10 hours on this so far. using the newest (24.7_9)

**Comment by psflachglas** [comment]
Hello

I installed OpenSense for the first time today.
These automatically generated rules were also a problem for me.

My intended use of OpenSense was as a simple router with GUI.
I want to connect two local networks. The GUI is very helpful for entering DHCP reservations.
But I gave up after I read that the automatically generated WAN rules can neither be edited nor deleted.

I would appreciate it very much if this would be possible in the future.

**Comment by c33s** [comment]
a colegue told me that i can manually edit th rules in the following files (haven't verified it yet but maybe it helps someone):
```
/usr/local/etc/inc/filter.lib.inc
/usr/local/etc/inc/filter.inc 
```

**Comment by AdSchellevis** [comment]
if you need to edit these files, you're likely doing something wrong....

**Comment by c33s** [comment]
if there is no possibility to prevent creation of default rules i a doing it right. still voting for allowing to prevent automatic rule creation.

**Comment by AdSchellevis** [comment]
Almost all rules can be disabled from the ui (the block private networks a couple of postings back is a good example), but I think we're circling back to the beginning here. If some rule can't be disabled and there are good reasons why it should be possible to disable, open a ticket for the case. All non-quick rules are useless to disable as your own will always go first anyway.

**Comment by willagc** [comment]
@AdSchellevis I was able to workaround this by using PFSense. They allow these rules to be managed. It's pretty poor UX to not allow us to do so.

**Comment by c33s** [comment]
@AdSchellevis i opened the ticket here but it was closed. what does it help if i open the ticket again? 

as i stated above: i have no ipv6 in my network. all predefined ipv6 rules are just polluting the interface. also listing so many rules which are not relevant without a simple option to edit them is just a bad UX/DX. why do i have to search through settings like 

> WAN -> Block private networks = Disabled

or

> Navigate to Firewall > Settings > Advanced/li
> Go to Miscellaneous > Firewall Optimization
> switch from "normal" to "conservative"

https://forum.opnsense.org/index.php?topic=27983.msg141843#msg141843

just to cleanup rules i don't want? simply allow to delete them in the interface. hide it behind an advanced mode or whatever.

why is it such a no go to allow to delete autogenerated rules? what is the argument here as my workaround is bad practice?

@willagc it is the only reason i still use pfsense.

**Comment by AdSchellevis** [comment]
let's agree to disagree and all use the product we prefer, we chose to show the rules that exist (visibility), another project adds the rules without showing them, different choices but in the shown cases likely similar rulesets (`/tmp/rules.debug`).

**Comment by willagc** [comment]
> let's agree to disagree and all use the product we prefer, we chose to show the rules that exist (visibility), another project adds the rules without showing them, different choices but in the shown cases likely similar rulesets (`/tmp/rules.debug`). 

I think it's a little more than agreeing to disagree. 

What is the purpose of using a firewall if I don't have full autonomy over what rules I want to create/delete?

**Comment by c33s** [comment]
@AdSchellevis don't get me wrong i would really prefer to use opnsense. i stand for opensource and tend to choose the software with fairer license (mariadb over mysql, libreoffice over openoffice, opentofu over terraform, ...).

normally closedsource products try to think for me and prevent me of doing stuff. i prefer the straight way of linux and its `rm -rf /`. if i want to do that i can. it is really sad that you/the opnsense team is blocking such an important functionality which, as this ticket shows, costs developer a lot of time and blocks them from using your awesome software. i would love to stand with opnsense instead of pfsense. so i would really prefer to use opnsense.

i think i can speak for the people who commented here that it is not about removing a default setting, which you say make the firewall more secure, but the option for an advanced user to do so. 

what is the security benefit of having preset rules which block me from using the software at all (ssh on wan in my lab setup was my problem then). can you explain what is the benefit of hiding the rules behind a setting called firewall optimization? everybody who worked with firewalls (shorewall, ufw, checkpoint, pfsense) knows their way around in a basic ui firewall and will be able to edit or delete a rule. with opnsense specific settings which are uncommon you make the software harder to use with no gain at all. why is it more secure to create new terms and make the live of firewall admins harder? what is the exact benefit of having ipv6 rules in place in a ipv4-only setting? in my point of view, it is doing the oposite, in a rules listing there are extra rules which are doing nothing but confuse the admins eye. have a look at my screenshot https://github.com/opnsense/core/issues/7127#issuecomment-1881845686 all yellow rules are useless to me (and everybody without ipv6), as far as i can remember it is not even possible to add notes to the predefined rules. 
why do you think not being able to delete rules help anyone? in my providers webgui (vps) i can also simply delete a server, this can do much more harm. they added a "lock" which i can toggle but i am able to create an delete my server. why don't you take your users for full? why do you think you know better about which rules i need and which i don't need? so it is really a little bit more than agree to disagree, i would really love to hear your arguments. more arguments than it is more secure (if i disconnect my computer from the internet/network it is much more secure than having it connected but it doesn't help me at all)

so please rethink your point and let the users of your firewall software decide if they want to delete such rules without hacking around in custom rule files. such hacks make the software really unsecure because of unknown sideffects on updates, ...

**Comment by korgano** [comment]
Just want to add that my current issue (#8012) would literally be solved by the ability to individually turn of the automatically generated rules to figure out which one(s) prevents DHCP assignment/renewal on WiFi interfaces.

I suspect that the automatically generated rules might explain a **lot** of issues people have with setting up certain OPNsense configurations.

**Comment by yevgen-lasman** [comment]
> Almost all rules can be disabled from the ui (the block private networks a couple of postings back is a good example), but I think we're circling back to the beginning here. If some rule can't be disabled and there are good reasons why it should be possible to disable, open a ticket for the case. All non-quick rules are useless to disable as your own will always go first anyway.

@AdSchellevis so what's the good reason to prevent me from using opnsense as a router in my homelab, where my "WAN" is private network? These automatically generated rules (#6 in particular) preventing me from accessing my router from the "outside"? And, no, they can't be disabled or bypassed by any settings.

**Comment by yevgen-lasman** [comment]
What if I want to emulate the real case scenario when I a firewall is needed? Man, this is an absurd, really. A firewall which makes its own rules? Well, I'll had to fallback to pfSense or other alternatives **only** because of this… weird architecture decision. And it is absolutely not a user friendly decision to enforce **some** firewall rules(!) which cannot be disabled no matter what.

**Comment by AdSchellevis** [comment]
That's a bit odd as most of them have similar defaults.... but hey, it's a free country. As stated in multiple tickets, we're open for any discussion as long as it actual contains substance.

**Comment by bugoff** [comment]
> That's a bit odd as most of them have similar defaults.... but hey, it's a free country. As stated in multiple tickets, we're open for any discussion as long as it actual contains substance.

So multiple people complaining about the same feature is not a real issue?
How is it that every firewall allows this, except opnsense?

**Comment by AdSchellevis** [comment]
May point is (and always has been) you can overwrite almost every rule there is, if specific rules need optional exclusions, we're open for a discussion. 

Most vendors don't allow you to show the rules in question, which hides all these automatic choices, being an enterprise product we aim for visibility in these cases.

**Comment by yevgen-lasman** [comment]
@AdSchellevis since we're on this topic, then how to read "System -> Settings -> Administration -> Web GUI (section) -> Listen Interfaces" option? I've it in its default "All (recommended)" value and still have a rule which blocks all traffic to Web GUI from WAN. Looks like a bug to me then.

**Comment by yevgen-lasman** [comment]
Also,
> Most vendors don't allow you to show the rules in question, which hides all these automatic choices, being an enterprise product we aim for visibility in these cases.

just is not true. Most of vendors will not hideously inject non-removable rules into firewall chains, especially for enterprise usage.

**Comment by fichtner** [comment]
Since the language (calling documented and visible standard requirements behaviour "hideously inject" was not on my bingo card) and arguments (namely getting more specific and talking OPNsense scope instead of some vague "all vendor" scope)  are not improving I'm locking this thread. Thanks!
