### ISSUE TITLE
Button Save not pressable in   VPN: OpenVPN: Client Specific Overrides

### ISSUE THREAD

**Issue by jpVm5jYYRE1VIKL** [opnsense/core#7131]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

After upgrade to  	OPNsense 23.7.11-amd64 it is not possible anymore to press button Save in UI at 
VPN: OpenVPN: Client Specific Overrides.
Critical functionality broken.

*Tip*: to validate your setup was working with the previous version, use opnsense-revert (https://docs.opnsense.org/manual/opnsense_tools.html#opnsense-revert)

**To Reproduce**

1. upgrade to OPNsense 23.7.11
2. Goto "VPN: OpenVPN: Client Specific Overrides"
3. Create new record and press button Save.
4. Button Save dont work.

**Expected behavior**

Must work button save

**Describe alternatives you considered**

A clear and concise description of any alternative solutions or workaround you considered.

**Screenshots**

**Relevant log files**

If applicable, information from log files supporting your claim.

**Additional context**

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 23.7.11-amd64
FreeBSD 13.2-RELEASE-p7
OpenSSL 1.1.1w

**Comment by fichtner** [comment]
I can't reproduce. Maybe validation error? ;)

**Comment by jpVm5jYYRE1VIKL** [comment]
I not have any highlight of validation . I just press Save and nothing happens . Tried different browsers. I Also tried clone persistent records with same result

**Comment by fichtner** [comment]
Can you run this from the shell? Your report is probably missing the relevant bits to reproduce.

    # /usr/local/opnsense/mvc/script/run_validations.php

**Comment by jpVm5jYYRE1VIKL** [comment]
```
OPNsense\OpenVPN\OpenVPN.Instances.Instance.d94b762a-e06a-44ae-ad30-95d4f88bafb1.server => At least one IPv4 or IPv6 tunnel network is required.
OPNsense\OpenVPN\OpenVPN.Instances.Instance.d94b762a-e06a-44ae-ad30-95d4f88bafb1.server_ipv6 => At least one IPv4 or IPv6 tunnel network is required.
PHP Fatal error:  Uncaught TypeError: flock(): Argument #1 ($stream) must be of type resource, bool given in /usr/local/opnsense/mvc/app/models/OPNsense/Base/FieldTypes/JsonKeyValueStoreField.php:132
Stack trace:
#0 /usr/local/opnsense/mvc/app/models/OPNsense/Base/FieldTypes/JsonKeyValueStoreField.php(132): flock(false, 2)
#1 /usr/local/opnsense/mvc/app/models/OPNsense/Base/FieldTypes/BaseField.php(193): OPNsense\Base\FieldTypes\JsonKeyValueStoreField->actionPostLoadingEvent()
#2 /usr/local/opnsense/mvc/app/models/OPNsense/Base/FieldTypes/BaseField.php(191): OPNsense\Base\FieldTypes\BaseField->eventPostLoading()
#3 /usr/local/opnsense/mvc/app/models/OPNsense/Base/FieldTypes/BaseField.php(191): OPNsense\Base\FieldTypes\BaseField->eventPostLoading()
#4 /usr/local/opnsense/mvc/app/models/OPNsense/Base/FieldTypes/BaseField.php(191): OPNsense\Base\FieldTypes\BaseField->eventPostLoading()
#5 /usr/local/opnsense/mvc/app/models/OPNsense/Base/FieldTypes/BaseField.php(191): OPNsense\Base\FieldTypes\BaseField->eventPostLoading()
#6 /usr/local/opnsense/mvc/app/models/OPNsense/Base/BaseModel.php(365): OPNsense\Base\FieldTypes\BaseField->eventPostLoading()
#7 [internal function]: OPNsense\Base\BaseModel->__construct()
#8 /usr/local/opnsense/mvc/script/run_validations.php(51): ReflectionClass->newInstance()
#9 {main}
  thrown in /usr/local/opnsense/mvc/app/models/OPNsense/Base/FieldTypes/JsonKeyValueStoreField.php on line 132

Fatal error: Uncaught TypeError: flock(): Argument #1 ($stream) must be of type resource, bool given in /usr/local/opnsense/mvc/app/models/OPNsense/Base/FieldTypes/JsonKeyValueStoreField.php:132
Stack trace:
#0 /usr/local/opnsense/mvc/app/models/OPNsense/Base/FieldTypes/JsonKeyValueStoreField.php(132): flock(false, 2)
#1 /usr/local/opnsense/mvc/app/models/OPNsense/Base/FieldTypes/BaseField.php(193): OPNsense\Base\FieldTypes\JsonKeyValueStoreField->actionPostLoadingEvent()
#2 /usr/local/opnsense/mvc/app/models/OPNsense/Base/FieldTypes/BaseField.php(191): OPNsense\Base\FieldTypes\BaseField->eventPostLoading()
#3 /usr/local/opnsense/mvc/app/models/OPNsense/Base/FieldTypes/BaseField.php(191): OPNsense\Base\FieldTypes\BaseField->eventPostLoading()
#4 /usr/local/opnsense/mvc/app/models/OPNsense/Base/FieldTypes/BaseField.php(191): OPNsense\Base\FieldTypes\BaseField->eventPostLoading()
#5 /usr/local/opnsense/mvc/app/models/OPNsense/Base/FieldTypes/BaseField.php(191): OPNsense\Base\FieldTypes\BaseField->eventPostLoading()
#6 /usr/local/opnsense/mvc/app/models/OPNsense/Base/BaseModel.php(365): OPNsense\Base\FieldTypes\BaseField->eventPostLoading()
#7 [internal function]: OPNsense\Base\BaseModel->__construct()
#8 /usr/local/opnsense/mvc/script/run_validations.php(51): ReflectionClass->newInstance()
#9 {main}
  thrown in /usr/local/opnsense/mvc/app/models/OPNsense/Base/FieldTypes/JsonKeyValueStoreField.php on line 132
ktoto@OPNsense:~ $ 
```

I am also did a review of all records in client_overrrides and all records have filled in Tunnel Network .

**Comment by fichtner** [comment]
About the flock failure I'm not sure, but you need to go to your Istance that doesn't save correctly and add at least one tunnel network to it. It could be that this blocks adding overrides as well...

**Comment by jpVm5jYYRE1VIKL** [comment]
> About the flock failure I'm not sure, but you need to go to your instance that doesn't save correctly and add at least one tunnel network to it. It could be that this blocks adding overrides as well...

Yes i do it . This is basically main reason why i do override every record contain its own Tunnel Network.

**Comment by fichtner** [comment]
Not sure what to do then. The validation was added so leaving it in a broken format could have unintended consequences like the one you reported.

**Comment by jpVm5jYYRE1VIKL** [comment]
For me it is strange why i get that error if absolutely all records contain Tunnel Network.

**Comment by fichtner** [comment]
I don't think your server instance with UUID d94b762a-e06a-44ae-ad30-95d4f88bafb1 does, because that's what it complains about.

**Comment by jpVm5jYYRE1VIKL** [comment]
Sorry may be strange question. How i can find in UI server instance by UUID ? Because in UI i have only instance names  . And not have any place where i can find UUID.

**Comment by fichtner** [comment]
You can enable die ID column here:

<img width="676" alt="Screenshot 2024-01-09 at 12 51 10" src="https://github.com/opnsense/core/assets/1915288/580bb828-9d2e-4f03-a81f-63ab0cbb8d23">

**Comment by jpVm5jYYRE1VIKL** [comment]
Thanks. Ok . I found what was wrong and most probably it is really bug. On Opensense i had openvpn Server configuration(old style config) and i started to prepare migration to Instance based config and created Ovpn Instance (not activated it yet but prepared for migration). Now. After i deleted Instance  and left only Server all started to work.

**Comment by fichtner** [comment]
Ok close then? :)

**Comment by jpVm5jYYRE1VIKL** [comment]
Yes.Thanks.

**Comment by fichtner** [comment]
PS: It's possible to have both new and old. I know that we added the tunnel validation later and you probably created the instance earlier so it didn't require the tunnel network, but it would have made OpenVPN fail to start anyway.

**Comment by jpVm5jYYRE1VIKL** [comment]
Yes . You right. I created Instance quite long time ago but not had time to migrate yet. Thanks for your help.
