### ISSUE TITLE
Kea - special characters in hostname for reservations

### ISSUE THREAD

**Issue by ronin3510** [opnsense/core#7137]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

IoT - water leak monitoring device - cannot be renamed from its control interface and includes _ in the name  

**To Reproduce**

Screenshot attached

**Expected behavior**

Discovered the issue when copying existing DHCP reservations from the legacy client, so I assume it's just a matter of adjusting the regex for Kia to include _ as well

**Describe alternatives you considered**

N/A

**Screenshots**
![ESP](https://github.com/opnsense/core/assets/145736760/976b3f63-adba-4a51-905c-0af5c5bfe7e7)

**Relevant log files**

N/A

**Additional context**

N/A

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 24.1.r_3 (amd64).

**Comment by AdSchellevis** [comment]
https://github.com/opnsense/core/commit/fdc72727a8390c6c1a0d1b230fd94b387bfdcc7a + https://github.com/opnsense/core/commit/68d5b81cb302a2cb2a6ee1149421dfc67d324298 should do the trick here.
