### ISSUE TITLE
Interface 'Block bogon networks' Blocking Legitimate ipv6 ICMP Traffic

### ISSUE THREAD

**Issue by gregtwallace** [opnsense/core#7139]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

I recently enabled ipv6 support and noticed some weird firewall traffic logs. A lot of traffic from my ISPs default gateway link local address was being blocked by the WAN block bogons rule. I reviewed the logs and realized the traffic is being blocked because it appears to be using the ICMPv4 protocol number even though the network is IPv6 (it shows as 'icmp' instead of 'ipv6-icmp').

At first I assumed it was an ISP configuration issue (sending the wrong protocol number). However, when I turn off bogon blocking the traffic disappears. My assumption was after passing the initial bogus packets the ISP router started using the correct protocol. However, there are no entries showing that traffic was ever passed (or even dropped after disabling Bogon blocking) for the bad protocol number, the traffic simply disappears.

Image bottom is with bogon blocking on and top is after disabling it. Since the traffic disappears as opposed to getting passed and then the gateway behaving differently, this makes me wonder if it might be an opnsense bug.

https://ibb.co/txqS6cw

Additionally, disabling block bogons on the WAN interface and then manually recreating the block bogon rules at the top of my fireawall rule list using the built in bogon aliases (both a v4 and v6 rule) also makes all of the "icmp" (wrong protocol number) traffic disappear too and all of the traffic in the logs shows as ipv6-icmp and is passed.

I did not use ipv6 on opnsense in a prior version.

**To Reproduce**

Enable WAN block bogons and watch the firewall logs. Unsurue if this might be ISP/gateway hardware specific though.

**Expected behavior**

ICMPv6 traffic should show up with the correct protocol name and be passed.

**Describe alternatives you considered**

Manually creating block bogons rules in the Firewall makes the issue go away.

**Screenshots**

Image bottom is with bogon blocking on and top is after disabling it. Since the traffic disappears as opposed to getting passed and then the gateway behaving differently, this makes me wonder if it might be an opnsense bug.

https://ibb.co/txqS6cw

<img width="1058" alt="Screenshot-2024-01-13-122105" src="https://github.com/opnsense/core/assets/63136063/9fc29409-c6db-4a7b-96b5-9fb84c6878a1">

**Relevant log files**

**Additional context**

**Environment**

Running virtualized on xcp-ng.

Versions	OPNsense 23.7.11-amd64
FreeBSD 13.2-RELEASE-p7
OpenSSL 1.1.1w

CPU type	Intel(R) Xeon(R) CPU E3-1231 v3 @ 3.40GHz (6 cores, 6 threads)

**Comment by fichtner** [comment]
What sort of IPv6-based traffic is passed over the old ICMP protocol with IPv6 addressing? That the bogons catch this traffic is not unusual because they catch all traffic not required (which also depends on your IPv6 connectivity type).


Cheers,
Franco

**Comment by fichtner** [comment]
Without capturing the traffic we don't really know what's going on. pflog artefacts have made the rounds before, but not for traffic suddenly disappearing and capturing that traffic pattern (ipv6 with icmp proto) should be relatively quick with the packet capture GUI. The bigger question, however, is whether the icmp traffic being processed by some automated rule actually reaches the host or of it drops it as invalid anyway.


Cheers,
Franco

**Comment by gregtwallace** [comment]
Not a single ICMP (wrong version) packet is appearing in the packet capture with the block bogon rule on or off.

![image](https://github.com/opnsense/core/assets/63136063/6510131b-326f-4618-8ad8-fc90f53c924e)

**Comment by fichtner** [comment]
Ok next step is using tcpdump on the pflog0 interface (from the command line). This is what filterlog/live log does.

**Comment by AdSchellevis** [comment]
Isn’t fe80::/10 just part of the bogon list?

**Comment by gregtwallace** [comment]
No ICMP traffic seen when using `tcpdump -i pflog0 icmp -v`

@AdSchellevis - It is not in https://pkg.opnsense.org/bogons/fullbogons-ipv6.txt  Even if it was, the autogenerated "IPv6 RFC4890 requirements (ICMP)" rules appear before the autogenerated block bogons rule.

**Comment by AdSchellevis** [comment]
Well, I would double check (you can use the alias diagnostics for that as well, to find which alias matches an address). It’s highly unlikely the block is not on the list and matching… 

The RFC4890 rule is very strict and could easily be unmatched with your test case. 

https://github.com/opnsense/core/blob/5b5cf45846c679b6c90d4447b4493bf63c5d68cf/src/etc/inc/filter.lib.inc#L227-L233

**Comment by gregtwallace** [comment]
Ah yes, it would be included in the last network, 8000::/1. 

The behavior/mislabeling is still bizarre and unexplainable though.
