### ISSUE TITLE
LDAP Authentication case insensitive, not binding proper groups

### ISSUE THREAD

**Issue by fabiocastagnino-horsa** [opnsense/core#7140]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**
We have an authentication Server LDAP with the "Match case insensitive": true
![image](https://github.com/opnsense/core/assets/116292883/0423fa51-4bee-4ad6-bda5-a2eee819b8bc)

when the username typed match the username stored in configuration, the user is member of the assigned groups.
when the username typed don't match the username stored in configuration, the user has no group assigned.

*Tip*: to validate your setup was working with the previous version, use opnsense-revert (https://docs.opnsense.org/manual/opnsense_tools.html#opnsense-revert)

**To Reproduce**

1. Go to System -> Access -> Servers and add a new LDAP server with property "Match case insensitive" = true
2. Go to System -> Access -> User and Import user from LDAP server and assign a group
3. Try to login with username non matching the original case 
4. See wrong group membership

**Expected behavior**

Opnsense should bind the group the user, ignoring the case, if the Server is configured to ignore the case.

**Screenshots**

![image](https://github.com/opnsense/core/assets/116292883/a7fe976f-a326-4684-800f-d121737513b7)
![image](https://github.com/opnsense/core/assets/116292883/b4789137-256d-4019-bc31-faa0671c4194)
![image](https://github.com/opnsense/core/assets/116292883/e9df4173-76b7-45d4-b577-a2ca3d8ddea7)

**Environment**

OPNsense 23.7.9-amd64
FreeBSD 13.2-RELEASE-p5
OpenSSL 1.1.1w

**Comment by AdSchellevis** [comment]
looks like an omission in the tester page, https://github.com/opnsense/core/commit/e1139109c8a16fb85860e5b4e94acdcf40df56fe should fix it.
