### ISSUE TITLE
Fatal error: Uncaught TypeError: stream_get_contents(): Argument #1 ($stream) must be of type resource, null given in 

### ISSUE THREAD

**Issue by tkrn** [opnsense/core#7142]
**Describe the bug**

Fatal error when installing various plugins. I believe this was functional in the previous minor version 23.7.11 from my observations. 

**To Reproduce**

Upgrade to 23.7.12. Click on Plugins. Install either the "os-acme-client" or "os-haproxy" packages.

**Expected behavior**

I would expect the plugin to install without error. 

**Describe alternatives you considered**

I've attempted in a new in-private browser session to prevent any old session data. It's not a client issue.

**Screenshots**

![2024-01-16_10-23-40](https://github.com/opnsense/core/assets/4492419/9d22773e-c0a3-4646-90a1-bb4f62974d7f)

**Relevant log files**

Upon request

**Additional context**

Output:
```
[19/20] Extracting py39-dns-lexicon-3.17.0: .......... done
[20/20] Installing os-acme-client-3.20...
[20/20] Extracting os-acme-client-3.20: .......... done
Stopping configd...done
Starting configd.
Reloading plugin configuration
Configuring system logging...
Fatal error: Uncaught TypeError: stream_get_contents(): Argument #1 ($stream) must be of type resource, null given in /usr/local/opnsense/mvc/app/library/OPNsense/Core/Backend.php:169
Stack trace:
#0 /usr/local/opnsense/mvc/app/library/OPNsense/Core/Backend.php(169): stream_get_contents(NULL)
#1 /usr/local/etc/inc/legacy_bindings.inc(41): OPNsense\Core\Backend->configdRun('template reload...', false)
#2 /usr/local/etc/inc/system.inc(794): configd_run('template reload...')
#3 /usr/local/etc/rc.configure_plugins(49): system_syslog_start(true)
#4 {main}
```

**Environment**

OPNsense 23.7.12 (amd64).
SuperMicro X10SDV-4C-TLN2F
64GB Memory, ZFS Mirror installation
Intel i350 Quad Port PCIe Adapter
Intel X552 Series (integrated) 10GBe Copper

**Comment by fichtner** [comment]
System: Log Files: Backend page should be logging errors now in 23.7.12.

**Comment by fichtner** [comment]
Two more from Twitter: https://twitter.com/allmightywiener/status/1747354311225491837 https://twitter.com/Johnnyluke228/status/1747322697007378684

I think the code may have made the problem more obvious now but problem could have always been there.
