### ISSUE TITLE
Password used for external backup in Google drive is in plain text

### ISSUE THREAD

**Issue by milapointe** [opnsense/core#7143]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

When using the function to export configuration to external storage (e.g. Google Drive), we can see clearly in the logs our password used for encrypting the file. I would assume that no password should be in cleartext...

**To Reproduce**

1. Save a new google drive backup configuration
2. Go to 'System: Configuration: History'
3. See the diff revision and look at that value : '\<GDrivePassword>**easy123**\</GDrivePassword>'

**Expected behavior**

\<GDrivePassword>**encryptedvalue**\</GDrivePassword>

**Describe alternatives you considered**

Not using this feature ?

On another note, could the password be encrypted with the self-signed certificate key or something else?

Could the password be hidden in that panel (and else where if found too?)

**Screenshots**

![ssopnsense](https://github.com/opnsense/core/assets/77821029/a44c97e1-1391-4143-805c-f49dbdd17497)

**Relevant log files**

N/A

**Additional context**

N/A

**Environment**

OPNsense 23.7.12-amd64 
FreeBSD 13.2-RELEASE-p7 
OpenSSL 1.1.1w

First issue here, I looked at past issues but didnt find anything on this.... 

Thanks !

**Comment by fichtner** [comment]
I don't think there is a way to verify a password hash to GDrive remotely. You could encrypt it but if you want it automated you'd need to store the key alongside which has the same "issue".

I think you are stuck between a rock and a hard place if you want to automate something but don't want to use the password preinstalled. ;)


Cheers,
Franco

**Comment by fichtner** [comment]
Keep in mind the config history is more or less an administrator page and you are very likely logged in as one.

**Comment by milapointe** [comment]
> PS: Keep in mind the config history is more or less an administrator page and you are very likely logged in as one.

I know but since it's exported on a remote drive, I would expected the data being encrypted.
