### ISSUE TITLE
firmware: duckdb migration script no longer prints what it does (all the time?)

### ISSUE THREAD

**Issue by fichtner** [opnsense/core#7147]
**Important notices**

Our forum is located at https://forum.opnsense.org , please consider joining discussions there in stead of using GitHub for these matters.

Before you ask a new question, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

<img width="1168" alt="Screenshot 2024-01-19 at 13 21 11" src="https://github.com/opnsense/core/assets/1915288/9f7dc897-8278-4ffd-8fa2-c50397697b35">

**Comment by AdSchellevis** [comment]
@fichtner https://github.com/opnsense/core/commit/4530da743c85187a188d3861794881672b7aab1b is likely what you're looking for.

**Comment by fichtner** [comment]
yep, thanks!
