### ISSUE TITLE
24.1.r1 - traceback on squid and duckdb

### ISSUE THREAD

**Issue by ronin3510** [opnsense/core#7149]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

This FW has been living on snapshots/openssl since the branch was created and was fully up to date as of Thursday. The issue didn't come up on the other 3 FWs that have been similarly upgraded

Once 24.1.r1 was published I switched to stable again and ran 12 in the console with 24.1.r1 to get the packages, and saw this 

>Fetching packages-24.1.r1-amd64.tar: .................................................................................................................................................................................................................. done
Extracting packages-24.1.r1-amd64.tar... done
Please reboot.
>>> Invoking upgrade script 'squid-plugin.php'
Squid web proxy is not active. Not installing replacement plugin.
>>> Invoking upgrade script 'unbound-duckdb.py'
Traceback (most recent call last):
  File "/usr/local/opnsense/site-python/duckdb_helper.py", line 65, in __enter__
    self.connection = duckdb.connect(database=self._path, read_only=self._read_only)
duckdb.duckdb.IOException: IO Error: Trying to read a database file with version number 39, but we can only read version 64.
The database file was created with DuckDB version v0.6.0 or v0.6.1.

>The storage of DuckDB is not yet stable; newer versions of DuckDB cannot read old database files and vice versa.
>The storage will be stabilized when version 1.0 releases.
>
>For now, we recommend that you load the database file in a supported version of DuckDB, and use the EXPORT DATABASE command followed by IMPORT DATABASE on the current version of DuckDB.
>
>See the storage page for more information: https://duckdb.org/internals/storage
>
>During handling of the above exception, another exception occurred:
>
>Traceback (most recent call last):
  File "/usr/local/etc/rc.syshook.d/upgrade/20-unbound-duckdb.py", line 41, in <module>
    if export_database('/var/unbound/data/unbound.duckdb', '/var/cache/unbound.duckdb', 'unbound', 'unbound'):
  File "/usr/local/opnsense/site-python/duckdb_helper.py", line 147, in export_database
    with DbConnection(source, read_only=True) as db:
  File "/usr/local/opnsense/site-python/duckdb_helper.py", line 75, in __enter__
    raise StorageVersionException(str(e))
duckdb_helper.StorageVersionException: IO Error: Trying to read a database file with version number 39, but we can only read version 64.
>The database file was created with DuckDB version v0.6.0 or v0.6.1.

>The storage of DuckDB is not yet stable; newer versions of DuckDB cannot read old database files and vice versa.
>The storage will be stabilized when version 1.0 releases.

>For now, we recommend that you load the database file in a supported version of DuckDB, and use the EXPORT DATABASE command followed by IMPORT DATABASE on the current version of DuckDB.

>See the storage page for more information: https://duckdb.org/internals/storage
>>> Error in upgrade script '20-unbound-duckdb.py'

**Describe alternatives you considered**
**Screenshots**
**Relevant log files**
**Additional context**

Unsure if this is a known issue, found it odd it only came up on one FW so I thought it was best to report it
Squid is not used and while unbound still runs on port 53 clients have a port forward to AGH.

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 24.1.r1 (amd64).

**Comment by fichtner** [comment]
Well the incompatibility is somewhat expected as this is how duckdb works, although I’m not sure what the initial situation was. You get this error when the duckdb version is updated before the export is done and it’s not recoverable.

**Comment by ronin3510** [comment]
Hi Franco,

Unsure what "not recoverable" means here and how to proceed. 

The duckdb was mostly empty so there's no data loss to worry about. I'm just wondering if there's anything else to do before rebooting.

**Comment by Giel538** [comment]
Hi, i have this problem as well. I only run regular updates but i am stuck now when updating to 24.1 

This is my error log:

`Fetching packages-24.1-amd64.tar: ............... done
Fetching base-24.1-amd64.txz: ...... done
Fetching kernel-24.1-amd64.txz: ... done
Extracting packages-24.1-amd64.tar... done
Extracting base-24.1-amd64.txz... done
Extracting kernel-24.1-amd64.txz... done
Please reboot.
>>> Invoking upgrade script 'squid-plugin.php'
Squid web proxy is not active. Not installing replacement plugin.
>>> Invoking upgrade script 'unbound-duckdb.py'
Traceback (most recent call last):
  File "/usr/local/opnsense/site-python/duckdb_helper.py", line 65, in __enter__
    self.connection = duckdb.connect(database=self._path, read_only=self._read_only)
duckdb.IOException: IO Error: Trying to read a database file with version number 39, but we can only read version 51.
The database file was created with DuckDB version v0.6.0 or v0.6.1.

The storage of DuckDB is not yet stable; newer versions of DuckDB cannot read old database files and vice versa.
The storage will be stabilized when version 1.0 releases.

For now, we recommend that you load the database file in a supported version of DuckDB, and use the EXPORT DATABASE command followed by IMPORT DATABASE on the current version of DuckDB.

See the storage page for more information: https://duckdb.org/internals/storage

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/etc/rc.syshook.d/upgrade/20-unbound-duckdb.py", line 41, in <module>
    if export_database('/var/unbound/data/unbound.duckdb', '/var/cache/unbound.duckdb', 'unbound', 'unbound'):
  File "/usr/local/opnsense/site-python/duckdb_helper.py", line 147, in export_database
    with DbConnection(source, read_only=True) as db:
  File "/usr/local/opnsense/site-python/duckdb_helper.py", line 75, in __enter__
    raise StorageVersionException(str(e))
duckdb_helper.StorageVersionException: IO Error: Trying to read a database file with version number 39, but we can only read version 51.
The database file was created with DuckDB version v0.6.0 or v0.6.1.

The storage of DuckDB is not yet stable; newer versions of DuckDB cannot read old database files and vice versa.
The storage will be stabilized when version 1.0 releases.

For now, we recommend that you load the database file in a supported version of DuckDB, and use the EXPORT DATABASE command followed by IMPORT DATABASE on the current version of DuckDB.

See the storage page for more information: https://duckdb.org/internals/storage
>>> Error in upgrade script '20-unbound-duckdb.py'
`

**Comment by fichtner** [comment]
See https://forum.opnsense.org/index.php?topic=38430 for a solution.
