### ISSUE TITLE
24.1.rc1 Suricata 7.0.2 IPS netmap issues with ix nic driver

### ISSUE THREAD

**Issue by L1ghtn1ng** [opnsense/core#7151]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

A clear and concise description of what the bug is, including last known working version (if any).

*Tip*: to validate your setup was working with the previous version, use opnsense-revert (https://docs.opnsense.org/manual/opnsense_tools.html#opnsense-revert)

**To Reproduce**

Go from 23.7.12 to 24.rc1 with Suricata set in IPS mode (I also have it in promiscuous mode due to having vlans) using a ix nic
and then watch you lose internet etc.
**Expected behavior**
Everything works as normal

**Describe alternatives you considered**
None

**Screenshots**

**Relevant log files**

If applicable, information from log files supporting your claim.

**Additional context**

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 24.1.r_8-amd64
FreeBSD 13.2-RELEASE-p9
OpenSSL 3.0.12
Intel(R) Core(TM) i9-10850K CPU
Intel Corporation Ethernet Controller X550T2

**Comment by AdSchellevis** [comment]
dmesg output, relevant system logs and try with software mode please (https://docs.opnsense.org/manual/ips.html)

**Comment by L1ghtn1ng** [comment]
![image0](https://github.com/opnsense/core/assets/3628354/458334f0-a4db-44ab-a978-389f9505cdf1)
[for_ad.zip](https://github.com/opnsense/core/files/13998700/for_ad.zip)

![image](https://github.com/opnsense/core/assets/3628354/3c99ab6d-d042-451f-ad09-5a91b65d3f71)

I think I set the software mode correctly, if so that did not work and killed all traffic as well but everything you requested is attached

**Comment by mib43** [comment]
@L1ghtn1ng , any chances you can also try Zenarmor (in bypass mode) with emulated netmap , on the same interface? ZA in bypass mode does nothing more than basically switching packets back and forth. This should tell if this is a netmap issue or an application problem.

**Comment by L1ghtn1ng** [comment]
Has it been built to handle OpenSSL 3?

On 20 Jan 2024, at 23:04, Murat ***@***.***> wrote:

﻿

@L1ghtn1ng<https://github.com/L1ghtn1ng> , any chances you can also try Zenarmor (in bypass mode) with emulated netmap , on the same interface? ZA in bypass mode does nothing more than basically switching packets back and forth. This should tell if this is a netmap issue or an application problem.

**Comment by TwoSoulz** [comment]
@AdSchellevis i have the same issue, my output is following: 

root@opntry:~ # dmesg
Copyright (c) 1992-2021 The FreeBSD Project.
Copyright (c) 1979, 1980, 1983, 1986, 1988, 1989, 1991, 1992, 1993, 1994
        The Regents of the University of California. All rights reserved.
FreeBSD is a registered trademark of The FreeBSD Foundation.
FreeBSD 13.2-RELEASE-p9 stable/24.1-n254969-8659880248c SMP amd64
FreeBSD clang version 14.0.5 (https://github.com/llvm/llvm-project.git llvmorg-14.0.5-0-gc12386ae247c)
VT(vga): resolution 640x480
CPU: Intel(R) Atom(TM) CPU C3558R @ 2.40GHz (2400.21-MHz K8-class CPU)
  Origin="GenuineIntel"  Id=0x506f1  Family=0x6  Model=0x5f  Stepping=1
  Features=0xbfebfbff<FPU,VME,DE,PSE,TSC,MSR,PAE,MCE,CX8,APIC,SEP,MTRR,PGE,MCA,CMOV,PAT,PSE36,CLFLUSH,DTS,ACPI,MMX,FXSR,SSE,SSE2,SS,HTT,TM,PBE>
  Features2=0x4ff8ebbf<SSE3,PCLMULQDQ,DTES64,MON,DS_CPL,VMX,EST,TM2,SSSE3,SDBG,CX16,xTPR,PDCM,SSE4.1,SSE4.2,x2APIC,MOVBE,POPCNT,TSCDLT,AESNI,XSAVE,OSXSAVE,RDRAND>
  AMD Features=0x2c100800<SYSCALL,NX,Page1GB,RDTSCP,LM>
  AMD Features2=0x101<LAHF,Prefetch>
  Structured Extended Features=0x2294e283<FSGSBASE,TSCADJ,SMEP,ERMS,NFPUSG,MPX,PQE,RDSEED,SMAP,CLFLUSHOPT,PROCTRACE,SHA>
  Structured Extended Features3=0xac000000<IBPB,STIBP,ARCH_CAP,SSBD>
  XSAVE Features=0xf<XSAVEOPT,XSAVEC,XINUSE,XSAVES>
  IA32_ARCH_CAPS=0x9<RDCL_NO,SKIP_L1DFL_VME>
  VT-x: PAT,HLT,MTF,PAUSE,EPT,UG,VPID,VID,PostIntr
  TSC: P-state invariant, performance statistics
real memory  = 17179869184 (16384 MB)
avail memory = 16563720192 (15796 MB)
Event timer "LAPIC" quality 600
ACPI APIC Table: <INTEL  TIANO   >
WARNING: L1 data cache covers fewer APIC IDs than a core (0 < 1)
FreeBSD/SMP: Multiprocessor System Detected: 4 CPUs
FreeBSD/SMP: 1 package(s) x 4 core(s)
random: registering fast source Intel Secure Key RNG
random: fast provider: "Intel Secure Key RNG"
random: unblocking device.
ioapic0 <Version 2.0> irqs 0-119
Launching APs: 1 2 3
wlan: mac acl policy registered
random: entropy device external interface
kbd0 at kbdmux0
WARNING: Device "spkr" is Giant locked and may be deleted before FreeBSD 14.0.
vtvga0: <VT VGA driver>
smbios0: <System Management BIOS> at iomem 0xf05e0-0xf05fe
smbios0: Version: 3.0, BCD Revision: 3.0
aesni0: <AES-CBC,AES-CCM,AES-GCM,AES-ICM,AES-XTS,SHA1,SHA256>
acpi0: <ALASKA A M I >
acpi0: Power Button (fixed)
cpu0: <ACPI CPU> on acpi0
hpet0: <High Precision Event Timer> iomem 0xfed00000-0xfed003ff on acpi0
Timecounter "HPET" frequency 24000000 Hz quality 950
Event timer "HPET" frequency 24000000 Hz quality 550
Event timer "HPET1" frequency 24000000 Hz quality 440
Event timer "HPET2" frequency 24000000 Hz quality 440
Event timer "HPET3" frequency 24000000 Hz quality 440
Event timer "HPET4" frequency 24000000 Hz quality 440
atrtc0: <AT realtime clock> port 0x70-0x77 irq 8 on acpi0
atrtc0: Warning: Couldn't map I/O.
atrtc0: registered as a time-of-day clock, resolution 1.000000s
Event timer "RTC" frequency 32768 Hz quality 0
attimer0: <AT timer> port 0x40-0x43,0x50-0x53 irq 0 on acpi0
Timecounter "i8254" frequency 1193182 Hz quality 0
Event timer "i8254" frequency 1193182 Hz quality 100
Timecounter "ACPI-fast" frequency 3579545 Hz quality 900
acpi_timer0: <24-bit timer at 3.579545MHz> port 0x1808-0x180b on acpi0
pcib0: <ACPI Host-PCI bridge> port 0xcf8-0xcff on acpi0
pci0: <ACPI PCI bus> on pcib0
pcib1: <ACPI PCI-PCI bridge> at device 6.0 on pci0
pci1: <ACPI PCI bus> on pcib1
pci1: <processor> at device 0.0 (no driver attached)
pcib2: <ACPI PCI-PCI bridge> mem 0x7b7ffc0000-0x7b7ffdffff irq 16 at device 9.0 on pci0
pci2: <ACPI PCI bus> on pcib2
igb0: <Intel(R) I211 (Copper)> port 0xd000-0xd01f mem 0xdfd00000-0xdfd1ffff,0xdfd20000-0xdfd23fff irq 16 at device 0.0 on pci2
igb0: NVM V0.6 imgtype2
igb0: Using 1024 TX descriptors and 1024 RX descriptors
igb0: Using 2 RX queues 2 TX queues
igb0: Using MSI-X interrupts with 3 vectors
igb0: Ethernet address: 00:a0:57:72:b3:89
igb0: netmap queues/slots: TX 2/1024, RX 2/1024
pcib3: <ACPI PCI-PCI bridge> mem 0x7b7ffa0000-0x7b7ffbffff irq 17 at device 10.0 on pci0
pci3: <ACPI PCI bus> on pcib3
igb1: <Intel(R) I211 (Copper)> port 0xc000-0xc01f mem 0xdfc00000-0xdfc1ffff,0xdfc20000-0xdfc23fff irq 17 at device 0.0 on pci3
igb1: NVM V0.6 imgtype2
igb1: Using 1024 TX descriptors and 1024 RX descriptors
igb1: Using 2 RX queues 2 TX queues
igb1: Using MSI-X interrupts with 3 vectors
igb1: Ethernet address: 00:a0:57:72:b3:8a
igb1: netmap queues/slots: TX 2/1024, RX 2/1024
pcib4: <ACPI PCI-PCI bridge> mem 0x7b7ff80000-0x7b7ff9ffff irq 18 at device 11.0 on pci0
pci4: <ACPI PCI bus> on pcib4
igb2: <Intel(R) I211 (Copper)> port 0xb000-0xb01f mem 0xdfb00000-0xdfb1ffff,0xdfb20000-0xdfb23fff irq 18 at device 0.0 on pci4
igb2: NVM V0.6 imgtype2
igb2: Using 1024 TX descriptors and 1024 RX descriptors
igb2: Using 2 RX queues 2 TX queues
igb2: Using MSI-X interrupts with 3 vectors
igb2: Ethernet address: 00:a0:57:72:b3:8b
igb2: netmap queues/slots: TX 2/1024, RX 2/1024
pcib5: <ACPI PCI-PCI bridge> mem 0x7b7ff60000-0x7b7ff7ffff irq 19 at device 12.0 on pci0
pci5: <ACPI PCI bus> on pcib5
igb3: <Intel(R) I211 (Copper)> port 0xa000-0xa01f mem 0xdfa00000-0xdfa1ffff,0xdfa20000-0xdfa23fff irq 19 at device 0.0 on pci5
igb3: NVM V0.6 imgtype2
igb3: Using 1024 TX descriptors and 1024 RX descriptors
igb3: Using 2 RX queues 2 TX queues
igb3: Using MSI-X interrupts with 3 vectors
igb3: Ethernet address: 00:a0:57:72:b3:8c
igb3: netmap queues/slots: TX 2/1024, RX 2/1024
pcib6: <ACPI PCI-PCI bridge> mem 0x7b7ff40000-0x7b7ff5ffff irq 20 at device 14.0 on pci0
pci6: <ACPI PCI bus> on pcib6
pcib7: <ACPI PCI-PCI bridge> mem 0x7b7ff20000-0x7b7ff3ffff irq 22 at device 16.0 on pci0
pci7: <ACPI PCI bus> on pcib7
pcib8: <ACPI PCI-PCI bridge> mem 0x7b7ff00000-0x7b7ff1ffff irq 23 at device 17.0 on pci0
pci8: <ACPI PCI bus> on pcib8
ahci0: <Intel Denverton AHCI SATA controller> port 0xe050-0xe057,0xe040-0xe043,0xe020-0xe03f mem 0xdff04000-0xdff05fff,0xdff07000-0xdff070ff,0xdff06000-0xdff067ff irq 20 at device 19.0 on pci0
ahci0: AHCI v1.31 with 2 6Gbps ports, Port Multiplier not supported
ahcich1: <AHCI channel> at channel 1 on ahci0
ahcich3: <AHCI channel> at channel 3 on ahci0
ahciem0: <AHCI enclosure management bridge> on ahci0
xhci0: <Intel Denverton USB 3.0 controller> mem 0x7b7ffe0000-0x7b7ffeffff irq 19 at device 21.0 on pci0
xhci0: 32 bytes context size, 64-bit DMA
usbus0 on xhci0
usbus0: 5.0Gbps Super Speed USB v3.0
pcib9: <ACPI PCI-PCI bridge> irq 16 at device 22.0 on pci0
pci9: <ACPI PCI bus> on pcib9
ix0: <Intel(R) X553 N (SFP+)> mem 0x7b7fc00000-0x7b7fdfffff,0x7b7fe04000-0x7b7fe07fff irq 16 at device 0.0 on pci9
ix0: Using 2048 TX descriptors and 2048 RX descriptors
ix0: Using 4 RX queues 4 TX queues
ix0: Using MSI-X interrupts with 5 vectors
ix0: allocated for 4 queues
ix0: allocated for 4 rx queues
ix0: Ethernet address: 00:a0:57:72:b3:8d
ix0: eTrack 0x80000bd7 PHY FW V65535
ix0: netmap queues/slots: TX 4/2048, RX 4/2048
ix1: <Intel(R) X553 N (SFP+)> mem 0x7b7fa00000-0x7b7fbfffff,0x7b7fe00000-0x7b7fe03fff irq 17 at device 0.1 on pci9
ix1: Using 2048 TX descriptors and 2048 RX descriptors
ix1: Using 4 RX queues 4 TX queues
ix1: Using MSI-X interrupts with 5 vectors
ix1: allocated for 4 queues
ix1: allocated for 4 rx queues
ix1: Ethernet address: 00:a0:57:72:b3:8e
ix1: eTrack 0x80000bd7 PHY FW V65535
ix1: netmap queues/slots: TX 4/2048, RX 4/2048
pcib10: <ACPI PCI-PCI bridge> at device 23.0 on pci0
pci10: <ACPI PCI bus> on pcib10
ix2: <Intel(R) X553 L (1GbE)> mem 0x7b7f600000-0x7b7f7fffff,0x7b7f804000-0x7b7f807fff irq 16 at device 0.0 on pci10
ix2: Using 2048 TX descriptors and 2048 RX descriptors
ix2: Using 4 RX queues 4 TX queues
ix2: Using MSI-X interrupts with 5 vectors
ix2: allocated for 4 queues
ix2: allocated for 4 rx queues
ix2: Ethernet address: 00:a0:57:72:b3:8f
ix2: eTrack 0x80000b3e
ix2: netmap queues/slots: TX 4/2048, RX 4/2048
ix3: <Intel(R) X553 L (1GbE)> mem 0x7b7f400000-0x7b7f5fffff,0x7b7f800000-0x7b7f803fff irq 17 at device 0.1 on pci10
ix3: Using 2048 TX descriptors and 2048 RX descriptors
ix3: Using 4 RX queues 4 TX queues
ix3: Using MSI-X interrupts with 5 vectors
ix3: allocated for 4 queues
ix3: allocated for 4 rx queues
ix3: Ethernet address: 00:a0:57:72:b3:90
ix3: eTrack 0x80000b3e
ix3: netmap queues/slots: TX 4/2048, RX 4/2048
pci0: <simple comms> at device 24.0 (no driver attached)
sdhci_pci0: <Intel Denverton eMMC 5.0 Controller> mem 0x7b7fff2000-0x7b7fff2fff,0x7b7fff1000-0x7b7fff1fff irq 16 at device 28.0 on pci0
sdhci_pci0: 1 slot(s) allocated
mmc0: <MMC/SD bus> on sdhci_pci0
isab0: <PCI-ISA bridge> at device 31.0 on pci0
isa0: <ISA bus> on isab0
pci0: <memory> at device 31.2 (no driver attached)
pci0: <serial bus> at device 31.5 (no driver attached)
apei0: <ACPI Platform Error Interface> on acpi0
acpi_tz0: <Thermal Zone> on acpi0
ppc1: <Parallel port> port 0x378-0x37f irq 5 on acpi0
ppc1: Generic chipset (NIBBLE-only) in COMPATIBLE mode
ppbus0: <Parallel port bus> on ppc1
lpt0: <Printer> on ppbus0
lpt0: Interrupt-driven port
ppi0: <Parallel I/O> on ppbus0
uart0: <16550 or compatible> port 0x3f8-0x3ff irq 4 flags 0x10 on acpi0
uart0: console (115200,n,8,1)
uart1: <16550 or compatible> port 0x2f8-0x2ff irq 3 on acpi0
est0: <Enhanced SpeedStep Frequency Control> on cpu0
Timecounter "TSC-low" frequency 1200000237 Hz quality 1000
Timecounters tick every 1.000 msec
ugen0.1: <Intel XHCI root HUB> at usbus0
uhub0 on usbus0
uhub0: <Intel XHCI root HUB, class 9/0, rev 3.00/1.00, addr 1> on usbus0
mmc0: No compatible cards found on bus
ses0 at ahciem0 bus 0 scbus2 target 0 lun 0
ses0: <AHCI SGPIO Enclosure 2.00 0001> SEMB S-E-S 2.00 device
ses0: SEMB SES Device
ada0 at ahcich3 bus 0 scbus1 target 0 lun 0
ada0: <ADATA ISSS332-064GM Q0303B> ACS-2 ATA SATA 3.x device
ada0: Serial Number 2L29291ABBLT
ada0: 600.000MB/s transfers (SATA 3.x, UDMA6, PIO 1024bytes)
ada0: Command Queueing enabled
ada0: 61057MB (125045424 512 byte sectors)
ses0: pass0,ada0 in 'Slot 03', SATA Slot: scbus1 target 0
Trying to mount root from ufs:/dev/gpt/rootfs [rw]...
WARNING: / was not properly dismounted
uhub0: 8 ports with 8 removable, self powered
igb1: link state changed to UP
ichsmb0: <Intel Denverton SMBus controller> port 0xe000-0xe01f mem 0x7b7fff0000-0x7b7fff00ff irq 23 at device 31.4 on pci0
smbus0: <System Management Bus> on ichsmb0
lo0: link state changed to UP
pflog0: permanently promiscuous mode enabled
vlan0: changing name to 'vlan0.1147'
vlan1: changing name to 'vlan0.1148'
vlan2: changing name to 'vlan0.1149'
vlan3: changing name to 'vlan0.1150'
ix1: link state changed to UP
vlan0.1147: link state changed to UP
vlan0.1150: link state changed to UP
vlan0.1149: link state changed to UP
vlan0.1148: link state changed to UP
[fib_algo] inet.0 (bsearch4#16) rebuild_fd_flm: switching algo to radix4_lockless
igb1: link state changed to DOWN
igb1: link state changed to UP
404.406320 [ 850] iflib_netmap_config       txr 2 rxr 2 txd 1024 rxd 1024 rbufsz 2048
404.414403 [ 850] iflib_netmap_config       txr 2 rxr 2 txd 1024 rxd 1024 rbufsz 2048
404.422479 [ 850] iflib_netmap_config       txr 2 rxr 2 txd 1024 rxd 1024 rbufsz 2048
404.704807 [ 850] iflib_netmap_config       txr 2 rxr 2 txd 1024 rxd 1024 rbufsz 2048
igb1: link state changed to DOWN
405.291259 [ 850] iflib_netmap_config       txr 2 rxr 2 txd 1024 rxd 1024 rbufsz 2048
405.299257 [ 850] iflib_netmap_config       txr 2 rxr 2 txd 1024 rxd 1024 rbufsz 2048
405.307245 [ 850] iflib_netmap_config       txr 2 rxr 2 txd 1024 rxd 1024 rbufsz 2048
igb1: link state changed to UP

**Comment by AdSchellevis** [comment]
@TwoSoulz if you upgrade, suricata should be downgraded to version 6 again. We're investigating the issue  before opening an upstream ticket.

**Comment by L1ghtn1ng** [comment]
I have upgraded but will enable suricata a bit later when I am free and see what happens

On 31 Jan 2024, at 16:57, Ad Schellevis ***@***.***> wrote:

﻿

@TwoSoulz<https://github.com/TwoSoulz> if you upgrade, suricata should be downgraded to version 6 again. We're investigating the issue before opening an upstream ticket.

**Comment by mdrichardson** [comment]
> @TwoSoulz if you upgrade, suricata should be downgraded to version 6 again. We're investigating the issue before opening an upstream ticket.

I didn't see an open issue for this, but the same thing appears to be happening with crowdsec. Is this being investigated already, as well?

**Comment by fichtner** [comment]
Crowdsec is not a core component, but you can raise a plugin issue to reach the maintainers.

**Comment by fichtner** [comment]
So @swhite2 found two issues in the new 7 default settings which prevent the netmap mode from working in our case. I think this is solved.
