### ISSUE TITLE
host alias resolve doesnt work for a specific host with CNAME response

### ISSUE THREAD

**Issue by elschman** [opnsense/core#7157]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

    [ x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
    [ x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug:**

The name is resolved fine (Interfaces: Diagnostics: DNS Lookup) A and AAAA record returned with an in CNAME ..
But the ping (Interfaces: Diagnostics: Ping) returns cannot resolve artifactory.<removed>.com: No address associated with name

As result the hosts alias is not resolved correctly and the firewall blocks the traffic.

BTW. This is only valid for a few addresses not all I guess the reason is the cname...

In the firewall:
x.mycomp.com ... is ok
y.mycomp.com ... is not ok

A host behind the firewall can resolve BOTH addresses and starts pinging. Both FW and Host using the same dns

digging deeper per ssh interface:

root@OPNsense:/usr/bin # drill heise.de
;; ->>HEADER<<- opcode: QUERY, rcode: NOERROR, id: 26134
;; flags: qr rd ra ; QUERY: 1, ANSWER: 1, AUTHORITY: 13, ADDITIONAL: 14
;; QUESTION SECTION:
;; heise.de.    IN      A

;; ANSWER SECTION:
heise.de.       86400   IN      A       193.99.144.80

;; AUTHORITY SECTION:
.       90643   IN      NS      h.root-servers.net.
.       90643   IN      NS      m.root-servers.net.
.       90643   IN      NS      l.root-servers.net.
.       90643   IN      NS      b.root-servers.net.
.       90643   IN      NS      d.root-servers.net.
.       90643   IN      NS      a.root-servers.net.
.       90643   IN      NS      g.root-servers.net.
.       90643   IN      NS      f.root-servers.net.
.       90643   IN      NS      i.root-servers.net.
.       90643   IN      NS      e.root-servers.net.
.       90643   IN      NS      k.root-servers.net.
.       90643   IN      NS      j.root-servers.net.
.       90643   IN      NS      c.root-servers.net.

;; ADDITIONAL SECTION:
m.root-servers.net.     324886  IN      A       202.12.27.33
h.root-servers.net.     76865   IN      A       198.97.190.53
a.root-servers.net.     263107  IN      A       198.41.0.4
c.root-servers.net.     138868  IN      A       192.33.4.12
e.root-servers.net.     260655  IN      A       192.203.230.10
i.root-servers.net.     264776  IN      A       192.36.148.17
k.root-servers.net.     324975  IN      A       193.0.14.129
j.root-servers.net.     325372  IN      A       192.58.128.30
f.root-servers.net.     325953  IN      A       192.5.5.241
l.root-servers.net.     325451  IN      A       199.7.83.42
g.root-servers.net.     260656  IN      A       192.112.36.4
d.root-servers.net.     326171  IN      A       199.7.91.13
b.root-servers.net.     326860  IN      A       170.247.170.2
m.root-servers.net.     264777  IN      AAAA    2001:dc3::35

;; Query time: 260 msec
;; SERVER: 10.255.1.50
;; WHEN: Mon Jan 15 16:56:08 2024
;; MSG SIZE  rcvd: 489
root@OPNsense:/usr/bin # drill artifactory.my-comp.com
;; ->>HEADER<<- opcode: QUERY, rcode: NOERROR, id: 7072
;; flags: qr rd ra ; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 0
;; QUESTION SECTION:
;; artifactory.my-comp.com.      IN      A

;; ANSWER SECTION:
artifactory.my-comp.com. 1471    IN      CNAME   artifactory.global.my-comp.com.
artifactory.global.my-comp.com.  3643    IN      A       172.22.51.78

;; AUTHORITY SECTION:

;; ADDITIONAL SECTION:

;; Query time: 0 msec
;; SERVER: 10.160.5.6
;; WHEN: Mon Jan 15 16:56:17 2024
;; MSG SIZE  rcvd: 89
root@OPNsense:/usr/bin # drill artifactory-berlin1.my-comp.com
;; ->>HEADER<<- opcode: QUERY, rcode: NOERROR, id: 15703
;; flags: qr rd ra ; QUERY: 1, ANSWER: 1, AUTHORITY: 13, ADDITIONAL: 14
;; QUESTION SECTION:
;; artifactory-berlin1.my-comp.com.      IN      A

;; ANSWER SECTION:
artifactory-berlin1.my-comp.com. 1781    IN      A       172.20.48.164

;; AUTHORITY SECTION:
.       90621   IN      NS      e.root-servers.net.
.       90621   IN      NS      h.root-servers.net.
.       90621   IN      NS      a.root-servers.net.
.       90621   IN      NS      d.root-servers.net.
.       90621   IN      NS      c.root-servers.net.
.       90621   IN      NS      k.root-servers.net.
.       90621   IN      NS      l.root-servers.net.
.       90621   IN      NS      b.root-servers.net.
.       90621   IN      NS      j.root-servers.net.
.       90621   IN      NS      i.root-servers.net.
.       90621   IN      NS      g.root-servers.net.
.       90621   IN      NS      m.root-servers.net.
.       90621   IN      NS      f.root-servers.net.

;; ADDITIONAL SECTION:
m.root-servers.net.     324864  IN      A       202.12.27.33
h.root-servers.net.     76843   IN      A       198.97.190.53
a.root-servers.net.     263085  IN      A       198.41.0.4
c.root-servers.net.     138846  IN      A       192.33.4.12
e.root-servers.net.     260633  IN      A       192.203.230.10
i.root-servers.net.     264754  IN      A       192.36.148.17
k.root-servers.net.     324953  IN      A       193.0.14.129
j.root-servers.net.     325350  IN      A       192.58.128.30
f.root-servers.net.     325931  IN      A       192.5.5.241
l.root-servers.net.     325429  IN      A       199.7.83.42
g.root-servers.net.     260634  IN      A       192.112.36.4
d.root-servers.net.     326149  IN      A       199.7.91.13
b.root-servers.net.     326838  IN      A       170.247.170.2
m.root-servers.net.     264755  IN      AAAA    2001:dc3::35

;; Query time: 134 msec
;; SERVER: 10.255.1.50
;; WHEN: Mon Jan 15 16:56:31 2024
;; MSG SIZE  rcvd: 511
root@OPNsense:/usr/bin # ping artifactory-berlin1.my-comp.com
ping: Unknown host
root@OPNsense:/usr/bin # ping heise.de
PING heise.de (193.99.144.80): 56 data bytes
64 bytes from 193.99.144.80: icmp_seq=0 ttl=243 time=13.168 ms
^C
--- heise.de ping statistics ---
1 packets transmitted, 1 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 13.168/13.168/13.168/0.000 ms
root@OPNsense:/usr/bin # ping artifactory.my-comp.com
ping: Unknown host
root@OPNsense:/usr/bin #

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 23.7.11 (amd64).
Intel(R) Xeon(R) E-2378 CPU @ 2.60GHz (8 cores, 16 threads)

**Comment by fichtner** [comment]
As far as I’m aware it uses A/AAAA only.


Cheers,
Franco

**Comment by elschman** [comment]
Does it mean the answer as following is just not supported? even if all other OS HW boxes etc supporting that ? How to overcome this blocking situation ?

 ;; ANSWER SECTION:
artifactory.my-comp.com. 1471 IN CNAME artifactory.global.my-comp.com.
artifactory.global.my-comp.com. 3643 IN A 172.22.51.78

**Comment by fichtner** [comment]
I'm merely stating the obvious:

https://github.com/opnsense/core/blob/98878a9eb90c1150b232bfbc7e9a012a3e3462a0/src/opnsense/scripts/filter/lib/alias/base.py#L123

"OS HW boxes etc supporting that" is too unspecific for me personally.

**Comment by fichtner** [comment]
Fair enough. Alias tables, however, are not a ping utility.

**Comment by elschman** [comment]
even the opnsense ping utility cant ping ! But the hosts behind the Firewall.

**Comment by AdSchellevis** [comment]
> even the opnsense ping utility cant resolve the host and therefore ping but the dns lookup tool works fine!

probably because it doesn't exist....

https://mxtoolbox.com/SuperTool.aspx?action=a%3aartifactory-berlin1.my-comp.com&run=toolpage

(sounds like you're querying an external dns for something only available internally)

**Comment by elschman** [comment]
The host name is faked (original name ->my-comp )  its an company internal only host available only on internal dns servers.
btw 172.22. ... is even just only private ip range .. inside our company

in the above comments you can see:
drill works fine for this host

```

drill artifactory.my-comp.com
;; ->>HEADER<<- opcode: QUERY, rcode: NOERROR, id: 7072
;; flags: qr rd ra ; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 0
;; QUESTION SECTION:
;; artifactory.my-comp.com. IN A

;; ANSWER SECTION:
artifactory.my-comp.com. 1471 IN CNAME artifactory.global.my-comp.com.
artifactory.global.my-comp.com. 3643 IN A 172.22.51.78
```

but ping not
 
```
ping artifactory.my-comp.com
ping: Unknown host
root@OPNsense:/usr/bin #
```

**Comment by AdSchellevis** [comment]
`/etc/resolv.conf` as always....  one tip for community support cases, make sure someone can actually reproduce your issue.

**Comment by elschman** [comment]
ok to reproduce it use www.tri-hgwaii.de as  target
