### ISSUE TITLE
"Disable hardware checksum offload" is missing vlanhwcsum

### ISSUE THREAD

**Issue by oparoz** [opnsense/core#716]
### Before

`options=8209b<RXCSUM,TXCSUM,VLAN_MTU,VLAN_HWTAGGING,VLAN_HWCSUM,WOL_MAGIC,LINKSTATE>`

### After

`options=82098<VLAN_MTU,VLAN_HWTAGGING,VLAN_HWCSUM,WOL_MAGIC,LINKSTATE>`

**Comment by AdSchellevis** [comment]
that one is part of "VLAN Hardware Filtering" https://github.com/opnsense/core/blob/master/src/etc/inc/interfaces.inc#L288-L294

**Comment by oparoz** [comment]
That doesn't remove it either
`options=82088<VLAN_MTU,VLAN_HWCSUM,WOL_MAGIC,LINKSTATE>`

**Comment by fichtner** [comment]
Did you reconfigure the interface or did a reboot? It may need that in order to apply.

**Comment by oparoz** [comment]
Looking at [ifconfig](https://www.freebsd.org/cgi/man.cgi?ifconfig), this cannot be disabled...

**Comment by oparoz** [comment]
And yes, I did reboot, as it was necessary to disable the vlan offloading
