### ISSUE TITLE
Add option to set route-metric in OpenVPN

### ISSUE THREAD

**Issue by wytchmaster** [opnsense/core#7160]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [ X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [ X ] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**

It should be possible to set a route metric for the routes set by OpenVPN. There's a client side option called "route-metric" which sets the route metric to a user defined value. In earlier versions of the OpenVPN-configuration, it was possible to set this via the user defined options in the "client specific overrides" menu. This not possible anymore.

**Describe the solution you like**

There should be an option for setting the client route metric (both per server and per client)

**Describe alternatives you considered**

--

**Additional context**

I have many mobile clients which have a permanent OpenVPN-connection to our main location. They should use this as long they are not physically at this location. If they are on-site, they should use a direct connection. So the route metric of the routes provided by OpenVPN must be higher. This is not the case. And it's no good solution to manually edit all client config files.

**Comment by AdSchellevis** [comment]
@wytchmaster you're sure this actually works on FreeBSD? FreeBSD's route command doesn't support the metric clause (https://man.freebsd.org/cgi/man.cgi?route), in which case I would expect OpenVPN ignores it, but I can be wrong.

**Comment by wytchmaster** [comment]
It an option the server can push to the clients. This works with Linux and Windows clients. I don't want to change the route metric on the server.

**Comment by AdSchellevis** [comment]
well, technically, it's an option for both the server and the client.... so, you're looking for "push  route-metric X"

**Comment by wytchmaster** [comment]
That would be great. The other option may be to have "route-metric" in the openvpn config file to be exported for the clients.

**Comment by AdSchellevis** [comment]
> ....The other option may be to have "route-metric" in the openvpn config file to be exported for the clients.

You can already do that.

**Comment by wytchmaster** [comment]
I only found the free text option field at the client export. But you have to add the option before every export. You can't set this option for all clients belonging to one server, right?

**Comment by AdSchellevis** [comment]
the export only creates a profile for the client indeed.
