### ISSUE TITLE
Multiple monitor IPs for gateway monitoring

### ISSUE THREAD

**Issue by deajan** [opnsense/core#7163]
- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**

So this one quite bugs me since I use OPNsense, and probably goes even back to the time I used m0n0wall ^^

Monitoring a gateway and switching to an alternative gateway depending on a single condition isn't always reliable.
Example:
I use the change the monitor IP of the gateways  to a "far IP", ie outside of the ISP adresses, which allows to really make sure internet is reachable, more far than next just next hop. Example: Monitor cloudflare DNS, OpenDNS, or a cloud provider IP or whatever service that usually responds 24h/24 to pings.

The problem is that those services can stop responding to ping for a couple of minutes from time to time for various reasons, like maintenance, BGP routing, peering changes...
When this happens, OPNsense will mark the gateway as down and execute rules accordingly, even if internet still works but it's just the monitored IP that stopped responding.

So of course I could just monitor the remote gateway IP, but this would not be a good enough guarantee for internet to work.
Some cases where "one can reach the remote gateway but not internet" happened, happen and will happen again.
This could be even more true for home users where OPNSense is behind a non bridged router, but that's not my scope for this FR.

**Describe the solution you like**

It would be really really nice if there could be more than one monitor IP.
In that case, one could monitor IP 1 and IP 2 and if one of them responds, then the gateway is supposed to work.

Ideal solution would be:
- Monitor as many IPs as wanted
- Have 'OR' & 'AND' conditions so we can say thinks like
> GW is okay if IP1 responds and (IP2 responds or IP3 responds) where IP1 would be the next hop, and IP2 and IP3 would be "far" IPs

**Describe alternatives you considered**

A set of external scripts that could hook to the gateway monitoring could also be used.
Eg, instead of monitoring IP 1.1.1.1, we'll execute a script which results would determine whether gateway is up or not.
Since we're talking scripts, a user has full freedom of choice of what conditions he wants to be met for a gateway to be considered up.
Downside: No nice gateway quality graphs, even if we could normalize the script output to be dpinger compatible to workaround that downside.

**Additional context**

Another (super dream) wish would be to allow adding TCP pings, ie mark gateway down if IP:PORT is unreachable, which would make OPNSense suitable for gateway changes when SaaS software / cloud provider / whatever http service isn't available via a gateway.

I know that OPNSense uses dpinger which only does ICMP pings, but it would be so nice to have added TCP support, with tools like nmap for example (or even nping which is part of nmap).

**Comment by rmundel** [comment]
Would be nice something like Fortigate does for SD-WAN monitoring.

They call Performance SLA:
![image](https://github.com/opnsense/core/assets/13142574/cd42c40f-1a41-4d53-b777-feb7da9ef904)
![image](https://github.com/opnsense/core/assets/13142574/a46431b9-47ef-4af4-8930-56f01066cde3)

I think dpinger limits what could be done it this regard but the ability to use multiple dpinger instances with different parameters for each gateway would improve things a lot.

The issue we have with the current approach is to detect gateway failures when the ISP throttles the internet due to payment issues. Usually they keep allowing icmp and domain resolution and blocks all tcp/udp traffic outside they're own network.

When this happens to the secondary link, which usually is kept on Tier 2, we only find out when it's needed. Then is too late.

Maybe use monit with some scripts to achieve this? Maybe it's already possible even?

**Comment by Wireheadbe** [comment]
Multiple IP's to monitor on a single gateway would be a welcome feature indeed.. 👍🏻

**Comment by djatwork** [comment]
+1

**Comment by deajan** [comment]
AFAIK, dpinger only has ICMP support.
Priror to dpinger, arpinger was used, but it seemed buggy at the time, hence the replacement.

It seems that dpinger has multiple target support, see [this](https://github.com/dennypage/dpinger/issues/24), although I didn't see anything in the release notes.
There have been only a few bugfix releases in the last 7 years, so probably no new features.
arpinger's page is even worse, project has been put in archive mode 9 years ago.

So there's plenty room for improvement for gateway monitoring in OPNSense.
I've made an FR [here](https://github.com/dennypage/dpinger/issues/39) for dpinger.

**Comment by deajan** [comment]
Wow !

**Comment by deajan** [comment]
So, I've got a response from the dpinger developper, who doesn't want to add TCP monitoring.
Anyway, could the OPNSense team at least consider multiple ICMP targets, so routing decisions won't be taken when a single target isn't available, but multiple ones ?

**Comment by AdSchellevis** [comment]
multiple targets is also not a feature of dpinger as far as I know (and we're currently not planning to build a different monitor), but feel free to open a pull-request to explain how this should be implemented...

**Comment by deajan** [comment]
@AdSchellevis Not feeling fine doing PR's in opnsense, but would enjoy sponsoring this feature.

**Comment by AdSchellevis** [comment]
@deajan I’m not sure what it needs, best contact our sales in that case (sales@opnsense.com)

**Comment by t1mothy666** [comment]
I'm quite surprised that this is not requested by more. 
Having an uplink depending on a single host ICMP response seems unreliable for a productive environment, no?
@deajan you got any workaround?

**Comment by SEKCobra** [comment]
Would also like this feature, is there any way just manually mark a gateway as down from a script? Feels like it would be easy to run a periodic script checking on some internet destinations which can then set an interface down as needed.

**Comment by victorvs0uz4** [comment]
The ability to monitor multiple IPs on a single gateway would be an extremely valuable feature!

**Comment by fichtner** [comment]
It also requires someone rewriting/replacing dpinger. It’s a bit of an extreme request in that sense too.


Cheers,
Franco

**Comment by deajan** [comment]
Well I do understand that rewrting dpinger is out of scope.

But one could add an optional other pinger like `fping` or even `tcpping` which support both ICMP and TCP pings.
With that, add multiple optional IP targets per gateway and you get a full new implementation while keeping the current behaviour.

Is there any remote chance to see this discussed ?

**Comment by fichtner** [comment]
To be frank it would be easier to write a generic framework and add pluggable scripts for one time pings which could implement multiple addresses or other types than ping, but it's certainly not planned any time soon.

Multiple addresses also has the downside of populating more host routes and inducing unwanted overlap, which is already a challenge for newcomers.


Cheers,
Franco

**Comment by deajan** [comment]
Thanks for the fast.
You're totally right for the routes.
I know the github bot just closes issues after 6 months of inactivity, so this feature request will very likely end the same way since nothing is planned any time soon.
Is there some backlog where a FR could be opened ?

**Comment by eduardosantanna** [comment]
+1 This would be a very valuable resource.

**Comment by almightiest** [comment]
+1 i don't want a single monitor ip going down to cause my failover scenarios
