### ISSUE TITLE
event_config_changed.json is not updated or newly created

### ISSUE THREAD

**Issue by ElXk6** [opnsense/core#7164]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

I have the following problem.
We have two FWs in HA setup here.
So that I do not forget that I have not pushed changes from master to the backup, I have created a monitoring with the help of /conf/event_config_changed.json.

Since 1-2 days I have the problem that the config does not change on the backup anymore.
Deleting the config does not create a new file.
Rebooting did not help either.
A config change on the master + trigger sync does not change anything either.

Maybe the problem was caused because I accidentally created a rule on the backup?
Maybe this is also desired here for reasons?
I don't know whether this is considered as a correct issue here.

**To Reproduce**

Unfortunately, I don't know.
It could be triggered by a rule change on the backup FW, would fit in terms of timing.

Software version used and hardware type if relevant, e.g.:

OPNsense 23.7.12-amd64
FreeBSD 13.2-RELEASE-p7
OpenSSL 1.1.1w
Intel(R) Atom(TM) CPU C3558 @ 2.20GHz (4 cores, 4 threads)

**Comment by AdSchellevis** [comment]
checked again on my end, it does look like something is off here

**Comment by AdSchellevis** [comment]
this https://github.com/opnsense/core/commit/042f71db129f848306449fbb538a892d03f6b777 should fix the issue, does need a syslog-ng restart afterwards. 
```
service syslog-ng restart
```

**Comment by ElXk6** [comment]
Many thanks for the quick fix.
As you said, I ran the following on the backup FW:
opnsense-patch 042f71d 
service syslog-ng restart

Then started a new sync from the master, the file was created and contains a new timestamp.

**Comment by AdSchellevis** [comment]
@ElXk6 thanks for confirming
