### ISSUE TITLE
OpenVPN needs a gateway parameter

### ISSUE THREAD

**Issue by felixtech-msp** [opnsense/core#7167]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X ] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X ] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

When setting up a OpenVPN Site-to-Site VPN and configuring all required settings, the VPN fails to start up because there seems to be some tunnel configuration missing to the OpenVPN daemon which is not properly populated by the GUI, even though it's configured. The error is: `OpenVPN ROUTE: OpenVPN needs a gateway parameter for a --route option and no default was specified by either --route-gateway or --ifconfig options`

In my view the `IPv4 Local Network` and/or `IPv4 Remote Network` settings are half way ignored and the daemon looks for them but doesn't properly find them. I was unable to find any actually useful information on that error.

**To Reproduce**

Set up the OPNsense part of the VPN like described here: https://forum.opnsense.org/index.php?topic=38350.0
The client part is not required to be set up as the OPNsense part of it already doesn't work at all.

**Expected behavior**

The VPN adapter starts and can be used.

**Describe alternatives you considered**

None.

**Relevant log files**

See the mentioned forum post.

**Environment**

OPNsense 23.7.12 (amd64) (commit f62681301)

**Comment by felixtech-msp** [comment]
The bug can be reproduced on a fresh install. When you are configuring OpenVPN Peer-to-Peer, the adapter will not start as there is a fundamental bug in OPNsense.

**Comment by AdSchellevis** [comment]
Better try to implement your use case with `VPN: OpenVPN: Instances`, if that fails, be more elaborate about the settings configured. It's highly likely a misconfiguration, in which case our forum (https://forum.opnsense.org) might be  a better place to look for help.

**Comment by felixtech-msp** [comment]
Just test it yourself. It is very clearly a bug. Also I have in detail described the issue in a forum post.
I don't want to use a workaround Client-Server connection to interconnect two locations. There is a Peer-to-Peer function (or Site-to-Site called by Ubiquiti) for this case. Not starting to trick around with a workaround would result in many hours of work and doesn't solve the actual issue.
Also the bug occurs totally independent of what the other side would be. The OPNsense part fails to even get to a point where it would be ready to accept any connection.
It cannot be a misconfiguration as a very minimal configuration already fails to start.
As I said, just test it yourself. Set up one side of a "Peer to Peer (Shared Key)" VPN according to the documentation and observe it crash.

**Comment by AdSchellevis** [comment]
suit yourself, there's nothing in your ticket that would allow someone to reproduce your issue. Merely explaining you the process and wishing you a pleasant day.

**Comment by felixtech-msp** [comment]
I have posted the forum link into the ticket where you can find a very detailed description. I will attach a screenshot of the relevant text of the forum post, which lets you reprocude the bug:
![grafik](https://github.com/opnsense/core/assets/89098885/159d9212-0f94-4c2d-ab3c-97b1b15576ca)

If there would be only one instead of two remote networks, the issue is still there. It is also independent of if I set the tunnel network to "10.255.0.1/30" or "10.255.0.0/30".

The bug occurs when having anything entered into "IPv4 Remote Network" and Topology is checked.

Meanwhile I found another bug that changing the configuration of this running or stopped VPN interface is not possible due to "the local port already being used" which yes it is used by this very interface. There is no way I could figure out where this bug came from. It just suddently appeared.

**Comment by AdSchellevis** [comment]
the relevant line in the log is the failing `ifconfig` here, but I'm not going on a further fishing expedition, your answer likely lies in the details of the log. the failing route is merely a symptom of a missing interface configuration.

**Comment by felixtech-msp** [comment]
The interfaces are configured and they work with IPsec and OpenVPN Server mode and traffic which is connected with local interfaces. The log is (even though max log level) totally useless. The identical configuration works on other firewall operating systems. And I absolutely hate your "blame the customer and refuse to check the bug" attitude. You can close the ticket if you don't care about providing assistance or checking bugs.

**Comment by AdSchellevis** [comment]
You're seeking commercial level support on a community platform.... I'm not blaming anyone for not being able to read the logs, just offering some pointers on how to fix these kind of issues in my free time here, sorry about that, won't happen again, I too have better ways so spend my weekend.

**Comment by felixtech-msp** [comment]
I'm not asking anyone to spend time with work on weekends. It's totally enough when this is investigated during your regular working hours. Just because we work on weekends and therefore respond to incoming communication, we don't expect anyone else to do so. But just responding "read the logs" when the logs are useless doesn't help anyone.

The log is useless. It's nice to know that ifconfig failed, but nothing could be more generic and useless than a status code 1 snd "something failed" without any explanation of what exactly has failed, even though debug logs are enabled.

I wouldn't consider a core feature of a product that is bugged to be commercial grade support. I don't expect this to be fixed tomorrow.

The log also says that routing configuration is missing. When I enter routing configuration into the GUI this has to be then handed over to the daemon and not that I have to manually enter that additionally into the advanced operations. Other firewall products offer the same functionality with basically the same GUI (even though some things may be called slightly differently) and it just works without having to enter mysterious things into advanced options.

I have already pointed out multiple times where I suspect the issue happens in the transformation from the configuration input into the OpenVPN command which is run then in the background.

I could maybe figure something more out if the debug log would tell me more than "status 1" and "something is wrong". But unfortunately there is no log level "tell me your secrets beyond your highest log level".

**Comment by AdSchellevis** [comment]
For me this discussion ends, but feel free to discuss with the next person who has the spirit to continue. 

As I tried to explain multiple times this (highly) likely is a misconfiguration (during support we offer, we have seen quite some variants), the routing issues are most likely caused by the fact that the interface configuration is not possible, but since you "know" it's in the configuration, you should also be able to debug this further (configuration files are stored in `/var/etc/openvpn/`, usually openvpn is quite elaborate about the command that failed in their log).

In case you are only seeing the messages reported earlier, you might want to change the log level in your view.

I do regret suggesting alternatives and areas to inspect to help you debug your issue, won't happen again, wish you a nice weekend.

**Comment by felixtech-msp** [comment]
Mentioning where the config files are stored was very helpful. I was able to isolate the exact cause of the bug.

When "Topology" is checked, according to the help text this means subnet-topology. When reading the OpenVPN Reference Manual the "ifconfig" command then needs a subnet and a subnetmask in subnet mode (e.g. `ifconfig 10.255.0.0 255.255.255.0`).

When "Topology" is unchecked, this would then mean net30-topology and the "ifconfig" command wants the local and the remote tunnel adapter IP address as mentioned in the manual (e.g. `ifconfig 10.255.0.1 10.255.0.2`).

But in the configuration file in both cases the local and remote IP are present. So when "Topology" is checked, there is a incorrect use of the "ifconfig" command in the configuration file. This causes ifconfig to fail as the command in used incorrectly.

I have also attached a screenshot of the OpenVPN Reference Manual below where this is described.

![grafik](https://github.com/opnsense/core/assets/89098885/c3a81d03-c89b-4516-bb61-e01360d37657)

![grafik](https://github.com/opnsense/core/assets/89098885/15a4f380-9c58-46fd-b308-588bc10048de)

--------------------

Bug number two I found in the PHP-CGI log. When creating the VPN adapter, there needs to be a route added for the tunnel network. But instead the route is trying to be deleted, which obviously fails.

`/vpn_openvpn_server.php: The command '/sbin/route -q delete 10.255.0.1' returned exit code '1', the output was 'route: route has not been found'`

As the route doesn't exist yet (as the interface is to be created), this is expected to fail. I get why this command is run (to get rid of any route which may already be there), but in case it fails, this should not abort the interface startup, as it just means the precondition of this route not already being there is met.

--------------------

Knowing now that the subnet topology is broken I could switch over to net30-topology and I got it to work very easily.

So the solutions for the bugs would be to use the correct command syntax for ifconfig when using subnet topology and to ignore a failed route deletion when adding the route. But the second bug could as well be one which just happens because of the first one. A simple test after fixing the first will tell.

**Comment by AdSchellevis** [comment]
Validations are likely incomplete, so incompatible choices may be possible. Which is one of the main reasons I've asked to try the new code first, eventually legacy modules will go end of live, adding more validations doesn't make much sense at this stage. 

You're obviously free to call it a bug, from my perspective it's a misconfiguration, it would be nice if the gui would prevent some of these choices, but that's not a goal we're trying to reach with components that more or less outlived their live-time. 

Let's close the ticket. 

One word of advice for future tickets, with any community project, I would suggest to work on your communication skills, if you read the thread again, envision this is one of your projects you offered to someone for free you might understand why....
