### ISSUE TITLE
system: let opnsense-shell continue if CMD_BANNER fails

### ISSUE THREAD

**Issue by skunkworker** [opnsense/core#7171]
```
OPNsense 23.7.12-amd64
FreeBSD 13.2-RELEASE-p1
OpenSSL 1.1.1w
```

Device: Protectli VP2420

I was trying to install tailscale from the guide https://tailscale.com/kb/1097/install-opnsense, tonight Jan 25, 2024. I ran `opnsense-code ports` and after this I was unable to ssh into the machine, it would throw an error on `ld-elf.so.1`. And on Lobby->Dashboard, the list of Services and Gateways stopped working (probably due to php)

```
Last login: Fri Jan 26 03:15:30 2024 from ....
----------------------------------------------
|      Hello, this is OPNsense 23.7          |         @@@@@@@@@@@@@@@
|                                            |        @@@@         @@@@
| Website:	https://opnsense.org/        |         @@@\\\   ///@@@
| Handbook:	https://docs.opnsense.org/   |       ))))))))   ((((((((
| Forums:	https://forum.opnsense.org/  |         @@@///   \\\@@@
| Code:		https://github.com/opnsense  |        @@@@         @@@@
| Twitter:	https://twitter.com/opnsense |         @@@@@@@@@@@@@@@
----------------------------------------------
ld-elf.so.1: /usr/local/lib/php/20220829/mbstring.so: Undefined symbol "php_pcre2_compile"
Connection to .... closed.
```

I had an active SSH connection and was able to live restore using `opnsense-bootstrap` after which the web UI started working again and new ssh connections worked.

If this is not the right repository, I'll close this, but also for anyone else who runs into this problem in the future.

**Comment by fichtner** [comment]
The moral of the story is 54d98085c2 which should allow you to access the shell menu under such unfortunate circumstances for recovery's sake.


Cheers,
Franco
