### ISSUE TITLE
24.1.r1 - XMLRPC syncs disabled FRR configuration, missing flag to disable sync for Prometheus Exporter

### ISSUE THREAD

**Issue by Kariton** [opnsense/core#7173]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

I have a HA pair with node specific FRR BGP deployed.

- XMLRPC sync is disabled for FRR settings.

The Settings for FRR are synced regardless.
(tried enabling and disabling; still synced)
This changes peer passwords, routerID and initiator IPs etc. on the other node.
obviously breaking the BGP deployment.

- Prometheus Exporter

The settings for Prometheus Exporter cant be excluded from sync.
Because each node has its own dedicated IP the "Listen Address" is not valid on node 2.

disabling FRR sync was correctly working with 23.7.12.
IIRC Prometheus Exporter wasnt even synced at all. (at least not overwritten)

**To Reproduce**

- HA Pair with dedicated FRR BGP settings per node (local side only; not over VPN etc.)
- XMLRPC FRR disabled
-> run XMLRPC sync

**Expected behavior**

Working XMLRPC. :)
- additional setting for Prometheus Exporter XMLRPC sync

**Describe alternatives you considered**
-

**Screenshots**
-

**Relevant log files**
-

**Additional context**
-

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 24.1.b_105-amd64
FreeBSD 13.2-RELEASE-p7
OpenSSL 1.1.1w

P.S.: the new GW monitor looks GREAT! :)

**Comment by AdSchellevis** [comment]
doubting if this is a question about a plugin or core, relevant information in these cases would be options checked in xmlrpc, committed changes according the configuration history page right after a sync.  By my knowledge no changes where made to either the sender of the receiver side in core on this subject.

**Comment by Kariton** [comment]
hey,
i was unsure if this is some kind of "core" or plugin issue. i assumed xmlrpc is more core then plugin.

anyways,
after retesting and looking into some other packages and version stuff i apparently somehow managed to have an absolutely broken versions mix of 23.7.12 and 24.1.rc1 on my second node.

while the update on the first node was successfully applied the second node update was not.
after fixing (reinstall 23.7.12, restore old config and upgrade again) it seems to work correctly.

i have absolutely no clue what gone wrong.

for me this issue is resolved.

**Comment by AdSchellevis** [comment]
was a type it seems, fixed in https://github.com/opnsense/core/commit/7e994cab29cc75e08be1c2433bdb41d7477da656
