### ISSUE TITLE
Wrong condition when parsing GeoIP ranges file

### ISSUE THREAD

**Issue by drakosha** [opnsense/core#7174]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

* [x]  I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
* [x]  I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Wrong condition when parsing GeoIP ranges file**

In [Documentation](https://docs.opnsense.org/manual/aliases.html#geoip) geoip networks file format is described as "2.21.241.0/28,1",
but [parser code](https://github.com/opnsense/core/blob/78b76cb5050d77ec27833ad018cee22e71550402/src/opnsense/scripts/filter/lib/alias/geoip.py#L106C79-L106C92) checks that record contains at least 4 columns. So, then i try to import files generated by my own according to documentstion it's not working.

**Describe the solution you like**

Condition should be changed to:
`if len(parts) > **1** and parts[1] in country_codes:`

**Comment by AdSchellevis** [comment]
Maxmind's dataset contains more fields (which we don't use) (`network,geoname_id,registered_country_geoname_id,represented_country_geoname_id,is_anonymous_proxy,is_satellite_provider,is_anycast`), which is why these sets work without issues.
