### ISSUE TITLE
Logging Target UDP still use UDP when changed to TCP

### ISSUE THREAD

**Issue by Digitum** [opnsense/core#7175]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X ] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [ X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

When log target is first set to UDP and later changed to TCP, it still logs to UDP.

**To Reproduce**

1. Go to https://<admin_ui>/ui/syslog/)
2. Click on 'System'->'Settings-'>'Logging/Targets'.
3. Add new target: 'UDP(4)' and <log_target_ip>
4. Apply settings.
5. Go to OpnSense console, run shell
6. Run command 'tcpdump -i eth0 dst host <log_target_ip>'
7. In 'System'->'Settings-'>'Logging/Targets', change target from UDP(4) to TCP(4)
8. Apply settings.
9. TCPDump still shows UDP traffic only. Expected change to TCP.

**Describe alternatives you considered**

Remove the target and create a new target.

**Screenshots**

![image](https://github.com/opnsense/core/assets/9963291/b6c6e609-d203-4e93-adee-ddebb09f49d9)

**Relevant log files**

No logfiles.

**Additional context**

No additional context

**Environment**

OPNsense 23.7.12-amd64
FreeBSD 13.2-RELEASE-p7
OpenSSL 1.1.1w
Intel(R) Xeon(R) CPU E5-2650L v4 @ 1.70GHz (8 cores, 8 threads)
Esxi 6.7

**Comment by AdSchellevis** [comment]
you could try to restart the service, if `/usr/local/etc/syslog-ng.conf.d/syslog-ng-destinations.conf` contains the proper settings, it might be a reload issue in `syslog-ng` after a change in some cases.

**Comment by Digitum** [comment]
Reload works, but only "Apply" does not work.
Is this a bug or by design?

**Comment by AdSchellevis** [comment]
might be a limitation of `syslog-ng` (reload vs restart behavior), in which case it is what it is I'm afraid.
