### ISSUE TITLE
Restore to other hardware could handle VLAN mappings better

### ISSUE THREAD

**Issue by systeemkabouter** [opnsense/core#7180]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**

When restoring the OPNsense configuration on another hardware platform then where the config backup is created, OPNsense detects and warns that logical interfaces cannot be automaticly mapped to physical interfaces and drops you in the screen to fix that. But when VLAN's are also used, you cannot change the assignments of the physical interface the VLAN maps to. But given the invalid physical ports, you also cannot save any changes. 

**Describe the solution you like**

* the config restore fuction should drop me in the VLAN mapping screen when VLANS are detected in use OR 
* the interface assignment screen should allow me to alter the physical mapping of interfaces too from the logical -> physical ports mapping screen. 

**Describe alternatives you considered**

A clear and concise description of any alternative solutions or features you considered.

**Additional context**

This issue was detected when migrating a config with VLAN mappings from a pcengines apu device to a DEC740 device.

**Comment by AdSchellevis** [comment]
I'm afraid that's not really fixable, same is more or less the case for other virtual types (laggs, bridges, ..). In theory you should be able to first change the vlans, then apply and go back to the assignments, but if you're connected to the machine using the same interface, it will be a bit fragile. 

complex setups are often easier to migrate manually (edit the config.xml and upload with proper interface mappings).
