### ISSUE TITLE
KEA not respecting DNS changes in subnet

### ISSUE THREAD

**Issue by Foowy** [opnsense/core#7181]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

When setting custom dns servers in dns field, kea is set to gateway address when "Auto collect option data" is enabled. Un-setting "Auto collect option data" and reloading custom DNS servers corrects the GUI to show custom dns server addresses, but leases are still being handed out original gateway address for dns.

**To Reproduce**

1. Go to Services > Kea DHCP [new] > Kea DHCPv4
2. Click on Subnets
3. Create subnet with option Auto collect option data enabled
4. Enter custom DNS servers that firewall is not using
5. From device refresh interface/reconnect/renew IP
6. Assigned DNS from DHCP will be that of the firewall
7. Disable Auto collect option data
8. Correct DNS server ip's in subnet
9. From device refresh interface/reconnect/renew IP
10. Assigned DNS from DHCP will still be that of the gateway and not of manually set dns addresses

**Expected behavior**

Disabling Auto collect option data should cause kea to use custom values entered into dns field

**Describe alternatives you considered**

Deleting and re-creating subnet at this time without "Auto collect option data" being enabled properly respects manually entered DNS addresses for client DHCP

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 24.1-amd64
Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (2 cores, 4 threads)
Using Unbound for gateway/firewall dns

*Edit

Words are hard and proper sentence structure is harder

**Comment by AdSchellevis** [comment]
Missed apply? the running config can be found in `/usr/local/etc/kea/kea-dhcp4.conf`, apply restarts the service, which means you can check the `pid` in top as well (should change after apply).

**Comment by AdSchellevis** [comment]
this one https://github.com/opnsense/core/issues/7183 should be fixed, when option data is configured as expected, it might be the client giving you a hard time, that's not something we can fix from our end unfortunately.

**Comment by KaiKimera** [comment]
I confirm the error. DNS is not installed on clients with the "Auto collect option data" option enabled.

![Screenshot 2024-02-01 at 01-40-21 Log File Kea DHCP new Services gw01 home lan](https://github.com/opnsense/core/assets/157225891/4d34d1bb-2040-44cd-9835-2d9eff8077f1)

**Comment by AdSchellevis** [comment]
@KaiKimera best read the ticket and responses to help you debug your issue, the warning is harmless and is already fixed in the master branch as communicated earlier and your claim is the exact opposite as reported in this ticket. If the configuration file is correct, there's not much to look at from our perspective.
