### ISSUE TITLE
Kea DHCP UI generates an invalid JSON config file

### ISSUE THREAD

**Issue by ronin3510** [opnsense/core#7183]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

Initially reported here by another user [https://forum.opnsense.org/index.php?topic=38451.0](url)

I can confirm the issue on multiple FWs

**Screenshots**

![Kea comma](https://github.com/opnsense/core/assets/145736760/99224dcf-eded-4374-bfae-f18ee2a5d9e0)

**Relevant log files**

WARN [kea-dhcp4.dhcp4.0x834648000] DHCP4_CONFIG_SYNTAX_WARNING configuration syntax warning: /usr/local/etc/kea/kea-dhcp4.conf:193.10: Extraneous comma. A piece of configuration may have been omitted.

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 24.1

**Comment by AdSchellevis** [comment]
need data to reproduce...

**Comment by ronin3510** [comment]
This the most bare-bones config I have on a FW, I have maybe a couple more reservations to add.

Please let me know if there anything else needed.

[kea-conf.txt](https://github.com/opnsense/core/files/14108851/kea-conf.txt)

**Comment by AdSchellevis** [comment]
@ronin3510 this config fails?

**Comment by ronin3510** [comment]
Hi Ad,

Kea runs fine with it, just complains about the extra comma in the logs.

 On this particular FW running with that config file uploaded earlier this appears in the log:

`	Warning	kea-dhcp4	WARN [kea-dhcp4.dhcp4.0x834ee5000] DHCP4_CONFIG_SYNTAX_WARNING configuration syntax warning: /usr/local/etc/kea/kea-dhcp4.conf:55.10: Extraneous comma. A piece of configuration may have been omitted.`


Nothing urgent or critical. Can wait for 24.1.x, I just reported it here once I've confirmed it on my FWs

**Comment by AdSchellevis** [comment]
got it, thanks! missed the fact that it was working fine :)

**Comment by AdSchellevis** [comment]
@ronin3510 can you try https://github.com/opnsense/core/commit/4a5193900c0cee8bd67dd2d13907e2cd2979d749 ? kea is pretty picky when it comes to formatting of its config, couldn't easily reproduce it on my end, but I expect it's complaining about this comma.

**Comment by ronin3510** [comment]
Confirmed, with a caveat :)

The patch doesn't trigger the conf file to be regenerated so stop/starting the daemon will continue to use the old file.

Once I added a fake reservation and applied it the file comes up cleanly, the extra comma is gone. 

So with the patch the issue is self resolving pending user interaction. Whether it's worth triggering the .conf regeneration when the patch lands I'll leave it with you -- I don't think there are too many users yet to justify it


Thanks again :) 


[4a51939.txt](https://github.com/opnsense/core/files/14110174/4a51939.txt)

**Comment by AdSchellevis** [comment]
an apply should be enough after installation, patch doesn't do anything indeed.

**Comment by ronin3510** [comment]
Negative :)

Clicked apply in all three tabs - without making a change - verified after each with tail -- comma still present.

Restarted Kea, went through the same steps once more - no change.


So it's picky enough to not touch the file, even if restarted in the meantime, unless a config change needs to be committed.


Found another cosmetic bug tinkering with it: the Trash Can in Reservations is not visible on 1366x768 laptop screens, it's replaced with ... and non clickable. It only appears if I remove all columns except Commands (I'll try to open an issue later, mentioning it here in case I forget)

![Kea Commands](https://github.com/opnsense/core/assets/145736760/57bea710-6c98-4f15-b1d1-143e275d95fa)

**Comment by KaiKimera** [comment]
I confirm the error.

![Screenshot 2024-02-01 at 01-40-21 Log File Kea DHCP new Services gw01 home lan](https://github.com/opnsense/core/assets/157225891/3bb1e5d9-5c30-43c1-b6f6-67c139f73909)

**Comment by tirsojrp** [comment]
Just migrated from ISC, same error.

**Comment by fichtner** [comment]
Lucky you this issue was fixed and closed? 😊
