### ISSUE TITLE
Google Drive backup no longer functional in 24.1

### ISSUE THREAD

**Issue by bucker00** [opnsense/core#7184]
The bug:
Google Drive backups are no longer working after upgrade to 24.1.  It previously worked daily up until yesterday on version 23.7.12.
The setup configuration is still in place but attempting a backup produces the message "Invalid P12 key, openssl_pkcs12_read() failed".
Configuring a new valid p12 file and supplying that in the configuration instead also produces the same message.

**To Reproduce**

1. Go to ~/diag_backup.php and then the Google Drive section on that page.
2. Set up Google Drive backups as per https://docs.opnsense.org/manual/how-tos/cloud_backup.html
3. When the configuration is complete upload the p12 file using the Browse button.
4. Click the 'Setup/Test Google Drive' button.
5. The following error is displayed:
"The following input errors were detected:
    Invalid P12 key, openssl_pkcs12_read() failed
    Saved settings, but remote backup failed."

Expected behavior
Usually and up until today, a backup is saved to the configured Google Drive and a list of the backups currently stored there already is displayed.

Alternatives:
Manual backups seem to be the only option currently without finding and installing plugins.

Software version used and hardware type:
OPNsense 24.1-amd64
CPU type | 12th Gen Intel(R) Core(TM) i3-1215U (6 cores, 8 threads)

<img width="377" alt="Screenshot 2024-01-31 212838" src="https://github.com/opnsense/core/assets/5030293/69e6dcf7-a43f-4ba4-baf9-29d7e44776be">

**Comment by bucker00** [comment]
I should also have mentioned that this has also been encountered by several other users in the 24.1 thread in the forums.

**Comment by fichtner** [comment]
Could be an incompatibility with OpenSSL 3.
