### ISSUE TITLE
24.1_1 - XMLRPC Sync is synchronizing settings that are not selected to sync

### ISSUE THREAD

**Issue by CMcNichol-GBSTP** [opnsense/core#7187]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

I have updated a HA pair of OpnSense firewalls to version 24.1_1.
Since the upgrade the HA XMLRPC sync is syncing items to the backup node which are de-selected in the HA settings page.

Previously I was running version 23.7 and the sync worked perfectly. Due to some issues upgrading from 23.7 to 24.1, I had a config backup, so reinstalled the firewalls from the new ISO, imported my config and upgraded from 24.1 to 24.1_1.

HA works as expected for failover etc. but the HA XMLRPC sync is syncing items that aren't selected.
I have tried selecting, saving, de-selecting and saving again, but this still syncs them.
The non-selected items which are syncing when they shouldn't include core packages (cron is included) as well as plugins (zabbix agent).

**To Reproduce**

- Configure backup node with different settings in cron and Zabbix Agent than the primary node.
- On primary node, go to System > High Availability > Status
  - Click on the Cloud button to sync settings
- Backup node now has cron and Zabbix Agent settings copied from primary node.

**Expected behavior**

Unselected items in High Availability XMLRPC sync not to sync.

**Describe alternatives you considered**
---

**Screenshots**

Cron not selected:
![image](https://github.com/opnsense/core/assets/95704161/927b0d21-63d3-4cd6-bc78-f5130ba5c80d)

Zabbix Agent not selected:
![image](https://github.com/opnsense/core/assets/95704161/e9ac9db8-05fe-4b94-900c-fd8c1ba77649)

**Relevant log files**
---

**Additional context**
---

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 24.1_1-amd64
FreeBSD 13.2-RELEASE-p9
OpenSSL 3.0.12

**Comment by AdSchellevis** [comment]
same as https://github.com/opnsense/core/issues/7173 , https://github.com/opnsense/core/commit/7e994cab29cc75e08be1c2433bdb41d7477da656 should fix it.
