### ISSUE TITLE
KEA DHCP-leases not working on interfaces with active Captive Portal

### ISSUE THREAD

**Issue by mayerthomas** [opnsense/core#7188]
**Important notices**

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Bug description**

I have an interface with a working Captive-Portal-Setup. After switching from ISC-DHCP to KEA-DHCP clients do not longer get an IP-address assigned. Without activated Captive Portal KEA-DHCP will assign IP-addresses correctly.

**Environment**

OPNsense 24.1_1 (amd64)

**Comment by mayerthomas** [comment]
Thank you for the hint!

Would it be a good solution to let KEA also auto-add the required rules, or should there be a hint in the documentation?

**Comment by AdSchellevis** [comment]
I'm not a huge fan of these autogenerated rules, but for dhcp services it might be better to consider it anyway. Maybe with a toggle to disable these rules.  I'm marking this ticket feature request.

**Comment by mayerthomas** [comment]
That sounds like a very sensible solution. Thank you for your tireless commitment to the OPNSense project.
