### ISSUE TITLE
VXLan-Interfaces getting overwritten by NAT-Sync

### ISSUE THREAD

**Issue by fzenger7** [opnsense/core#7190]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

The HA-Sync for NAT overrides the configuration of my VXLAN-Interfaces on the Backupnode with the configuration of the Masternode.

**To Reproduce**

1. Create a VXLAN-Interface on both OpnSenses with different SourceIPs
2. Trigger the HA-Sync with the NAT-Sync checked
3. Now, both OpnSenses have the same SourceIP

**Expected behavior**

Interfaces should not be synced by HA. 
If they should, I think it should be a separate Checkbox.

**Describe alternatives you considered**

Deactivate the NAT-Sync and create Rules on both Opnsenses

OPNsense 24.1_1-amd64
Intel(R) Celeron(R) CPU N3450

**Comment by fichtner** [comment]
https://github.com/opnsense/core/commit/7e994cab29

# opnsense-patch 7e994cab29
