### ISSUE TITLE
Wireguard instance ID is invalid going from 23.7 to 24.1_1

### ISSUE THREAD

**Issue by Zerophase** [opnsense/core#7192]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x ] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [ x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

Attempting to switch the endpoint, on an instance created in the previous version, used by an instance leads to an error about invalid integer value. There's no means of manually correcting the integer value.

**To Reproduce**

1. setup wireguard with version 23.7
2. Upgrade to 24.1_1
3. Attempt to change endpoint used by wireguard in 24.1_1
4. Can't save change because instance ID is invalid.

**Expected behavior**

Able to save change to wireguard instance.

**Describe alternatives you considered**

Thought creating a new instance with all of the same values, and letting OPNSense update the ID to 1, and assigning the new wireguard instance to the interface I have for Wireguard would work. But, that does not seem to work. Looking at the overview doing that leads to the driver and device ID mismatching with wg0 and wg1 respectively. 

**Screenshots**

I'd like to add screenshots, but I'm worried about leaking unique identifiers. There's not really anything that needs a screenshot.

**Additional context**

When I run resolve plugin conflicts from the gui it does show os-wireguard (missing), and I cannot delete os-wireguard through the gui. No idea if crud is still left behind.

The instance ID is also 0, which the updated version claims is invalid when I try to change the endpoint.

If I do add a new Wireguard instance with ID wg1, under Interfaces -> overview  the Wireguard interface shows up with driver wg0 and device wg1.

**Environment**

DEC850, and OPNSense 24.1_1

**Comment by AdSchellevis** [comment]
Likely an instance that hasn't been touched for quite a while as the lower bound for autonumber fields was changed in https://github.com/opnsense/core/commit/09d782f8f53e169a71b4d800c3325f98de3b2834. Changing the config.xml manually might be the easiest fix, not sure if changing the fieldtype makes sense at the moment.

**Comment by fichtner** [comment]
@AdSchellevis migrate these automatically at some point? But the affected user base is likely pretty small.

**Comment by AdSchellevis** [comment]
@fichtner it changes interface names, so migrating is also not very easy. we can change the input type so people can fix the data manually if we can not really change the field type.

**Comment by fichtner** [comment]
Fair enough. As far as I remember the "0" was omitted from the field type because the unit test for it was failing.

**Comment by AdSchellevis** [comment]
@fichtner thanks, that was exactly what I was looking for, reason missed in the commit :)

**Comment by AdSchellevis** [comment]
https://github.com/opnsense/core/commit/46e0bc67bb43ad442501bac49a567bf9746c0472 should allow 0 as valid id again.

**Comment by Zerophase** [comment]
Changing `wg0` to `wg1` in config.xml seems to work with creating a new instance with the same values. I'm pretty sure everything is going out over the VPN again. 

The only odd behavior I've noticed currently is when the firewall first boots up the Gateways widget on the Dashboard lists the Wireguard gateway as being down for about a minute, before showing it as up. However, I can successfully load a page during this time period with the IP address I should have from the VPN. Logs do show Wireguard going down and being restarted just before I access a website.
