### ISSUE TITLE
Change default domain from OPNsense.local to OPNsense.internal

### ISSUE THREAD

**Issue by vpx23** [opnsense/core#7193]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

Please consider changing the default domain for new installations to OPNsense.internal following the IANA proposition.

https://itp.cdn.icann.org/en/files/root-system/identification-tld-private-use-24-01-2024-en.pdf

I know the decision for the domain is not final by the IANA but maybe you can already do preparations or identify possible problems with this change.

**Comment by fichtner** [comment]
For future reference this should be a single line pull request:

https://github.com/opnsense/core/blob/5220c4a1a684adbf8b6b74431a3a8693f685478a/src/etc/config.xml.sample#L207

But I suggest waiting for this to be actually a standard or at least gain a wider recognition first.


Cheers,
Franco
