### ISSUE TITLE
Replaced plugins stay in config after upgrade to 24.1

### ISSUE THREAD

**Issue by ohartl** [opnsense/core#7195]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

After the upgrade to 24.1, the plugins replaced by a core implementation are marked as missing. 
(This might be true of other version upgrades, that replace a plugin with a core implementation, too.?)

To fix this manually, I had to edit the config.xml manually, removing the false "missing" plugins, and restore with that config.

**To Reproduce**

1. Install 'os-firewall' and 'os-wireguard' on 23.7.12
2. Upgrade from 23.7.12 to 24.1
3. (Restart)
4. Go to 'System > Firmware > Plugins'
5. See that both 'os-firewall' and 'os-wireguard' are marked as missing and cannot be uninstalled or installed.

**Expected behavior**

After the upgrade (which integrates those plugins into the core), it should automatically remove (migration) them from the config.

**Describe alternatives you considered**

Or the missing plugins can also be removed manually in the Plugins tab.

**Environment**

before:
 - OPNsense 23.7.12 (amd64).
 - plugins: os-firewall, os-wireguard

after:
 - OPNsense 24.1_1 (amd64).

**Comment by fichtner** [comment]
Yes, I’ll find a way to make this more bearable.

**Comment by fichtner** [comment]
> Or the missing plugins can also be removed manually in the Plugins tab.

FWIW, the GUI way to do it is to use the plugin conflict action with the "reset conflict" option under System: Firmware: Status.

**Comment by ohartl** [comment]
> > Or the missing plugins can also be removed manually in the Plugins tab.
> 
> FWIW, the GUI way to do it is to use the plugin conflict action with the "reset conflict" option under System: Firmware: Status.

Ok, but "Reset all conflicts" doesn't really seem intuitive to click for that.

**Comment by spuky** [comment]
At least a description on the release notes would have helped for that.. ;-)
Searched the forum for how to remove missing Plugins. 
Checked the Plugin Documentation... next step was looking for Github issue around that... 

a simple Sentense...like

If you see missing plugins that moved into core ('os-firewall' and 'os-wireguard' ) and you don't need to roll back to 23.7 you can get rid of the missing Plugin lines by clicking the reset local conflicts option on the Firmware Status page.

In the Release notes would have solved it for me... ( I know there are People not reading those... )

But thanks for the solution...

**Comment by fichtner** [comment]
To be fair I don't think most people read the release notes so adding a hint that gets ignored is suboptimal.

I understand that people get hung up about this "missing" thing, yet you also have to see the luxury of reporting a really annoying cosmetic bug in a major upgrade instead of any real world operational issue.

You see a long time ago people asked for the config.xml to register plugins and I was very sure it would cause these silly issues in the following years so only reluctantly I went ahead and implemented it.


Cheers,
Franco
