### ISSUE TITLE
Wireguard port assignment breaks randomly

### ISSUE THREAD

**Issue by LOENS2** [opnsense/core#7201]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

The bug only occurs randomly which makes it incredibly hard to reproduce. When the bug occurs, any TLS traffic from the tunnel to the internal network is dropped. This doesn't seem to be done by the firewall, as all failing transmission are allowed by the firewall and are shown green in the firewall live log and the issue still occurs when allowing all traffic through the firewall. I was able to do some packet captures of that and I was able to find out that all TCP ACK frames are missing in the tunnel which lead to the TCP steam being reset. The TCP ACK frames are however send by the web server and make it to the OPNsense box after that they are lost. I can provide those packet captures if needed, but I'd prefer not to share them on GitHub. However, all of the other traffic is passing fine through the tunnel and the OPNsense box. This error first occured to me when the kernel wireguard implementation was added (should be OPNsense 23.1).

**To Reproduce**

1. Create a wireguard tunnel
2. Assign an interface to the tunnel in order to be able to set up firewall rules
3. Try to request any https webserver through the tunnel that is inside the local network of the OPNsense box.

**Expected behavior**

 TLS traffic is passed through the tunnel and the OPNsense box without missing any TCP frames. Only traffic blocked by the firewall should be dropped.

**Describe alternatives you considered**

Switching the interface assignment to any dummy port and switching it back to the wireguard tunnel interface fixed the problem and everything is back to normal.

**Screenshots**

**Relevant log files**

If applicable, information from log files supporting your claim.

**Additional context**

My support post on the German sysadmin forum Administrator.de describing the series of events of me figuring out the problem with a wrong conclusion: https://administrator.de/forum/opnsense-blockiert-https-traffic-zwischen-2-netzwerken-8725532251.html#comment-24552568284261491 

https://github.com/opnsense/core/issues/7148 might be related to this problem, but I don't have issues with the firewall.

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 23.10.2 (amd64).
Deciso DEC2750 Rack Security Appliance

**Comment by mimugmail** [comment]
Sounds you didnt set the MTU on both Firewalls to the same value? Assign and unsassign may fix it for the time beeing, but you better set those values.

**Comment by LOENS2** [comment]
@mimugmail Thank you very much for pointing me in the right direction. Nobody was able to do so yet. I just set the MTU on the Wireguard clients (which was unconfigured) to match the MTU in the interface configuration.

**Comment by AdSchellevis** [comment]
@LOENS2 if you would care for a secondary test with the same setup, can you try to add a normalization rule in `Firewall: Settings: Normalization` targeting the wireguard group? e.g. 
<img width="851" alt="image" src="https://github.com/opnsense/core/assets/9783985/12b3a378-82a6-4bf3-bbd6-abe3d0f620aa">

and leave the rest default
