### ISSUE TITLE
VPN-IPsec-Connections - Add check for installing kernel routes policies with 0.0.0.0/0 in traffic selector

### ISSUE THREAD

**Issue by nikolyabb** [opnsense/core#7205]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**

Installing new site-to-site IPSEC connection or modifying an existing one could lead to unobvious connectivity issue (losing external and internal access while IPSEC connection is active). In VPN -> IPsec-> Connections -> Children there are "Policies" flag, that enabled by default. And if you forget to disable it and put value "0.0.0.0/0" to "Local" field for traffic selector, that would cause a 0.0.0.0/0 IPsec Kernel policy being installed and all network traffic will just stop as soon as tunnel is up.

**Describe the solution you like**

I would like to have a UI config check that track having 0.0.0.0/0 in Local Traffic selector and "Policies" flag enabled that notifies user of potential connectivity loss and/or request for additional explicit confirmation.

**Describe alternatives you considered**

Set "Policies flag" disabled by default add modifying docs to reflect that in "road warrior" setup.
https://github.com/opnsense/core/blob/c7d6f53797722678f64a754c8a4da2be7cf11eb9/src/opnsense/mvc/app/models/OPNsense/IPsec/Swanctl.xml#L294-L297

**Additional context**

Additional context: https://forum.opnsense.org/index.php?topic=36381

**Comment by AdSchellevis** [comment]
Warnings are difficult, but adding a validation to prevent saving a record when `Policies` is checked and local network is `0.0.0.0/0` shouldn't be too difficult.
