### ISSUE TITLE
Upgrade from 23.x to 24.1 breaks the GUI when `os-dyndns` plugin is installed and previously added as a dashboard widget.

### ISSUE THREAD

**Issue by Flightkick** [opnsense/core#7206]
**Describe the bug**

As the title describes, having the `os-dyndns` plugin installed and added as a dashboard widget breaks the GUI (/index.php) after upgrading to the 24.1 version. The main sections in the menu become unresponsive and the dashboard is empty.

**Workaround/remediation**

I managed to fix the issue on my setup through the following steps.

The navigation entries under the 'Lobby' section do work, so the easiest* way to fix this through the GUI is to go to `License`, which unborks the GUI navigation. Then go to `System` > `Firmware` > `Plugins` and remove the `os-dyndns` plugin.

 \* _(or directly visit `/ui/core/firmware#plugins`)_

**Expected behavior**

In an ideal situation I would have expected that this incompatibility would have been reported during the upgrade process or at least that the rest of the GUI/navigation remained functional. But I understand that this may not be trivial at the moment. Hopefully, documenting this here may help others who bump into the same issue. Feel free to close this issue in case this does not require any additional action.

**Comment by fichtner** [comment]
Or

# pkg remove os-dyndns

As we haven't had the plugin since 23.1.x we can't fix code that we no longer ship.


Cheers,
Franco

**Comment by v1ckxy** [comment]
Perfect, so the idea is that we are forced to remove the plugin that was working perfectly until 24.x for the one that no God can understand how it works (it works terribly, let's be realistic).

Nice.
