### ISSUE TITLE
Bug reports can't be dismissed

### ISSUE THREAD

**Issue by oparoz** [opnsense/core#721]
I don't know if it's because I have a huge backlog of reports or if it's a bug which doesn't remove the report when told to.

### Env

16.1
10.2-p11

### Steps to reproduce
1. Create a crash report (not sure how)
1. Go to the *Crash Reporter*
1. Dismiss the report
1. Click on *Crash Reporter* again

### Expected result

The page should be empty

### Actual result

The page contains the same report

**Comment by AdSchellevis** [comment]
Doesn't reproduce on my end, creating a report is quite simple, 

echo "test" > /tmp/PHP_errors.log

But that's probably not the issue here, you can check the contents of
ls -lah /var/crash

If something is stuck in that directory, that might be your issue.

We would really like to encourage you to do more investigation on your end before submitting an issue.

**Comment by oparoz** [comment]
>ls -lah /var/crash

Unfortunately, I've found a way to reset it, by asking to create a new report right away. So that folder only contains `minfree` now.
I'm going to close it until it happens again.

>We would really like to encourage you to do more investigation on your end before submitting an issue.

Of course, but for that to happen, one has to get to know how the system works. How do I figure out where reports are stored? Most config files, per example, are in non-standard locations, `locate` is not available, etc.
So, in time, it will be easier for me (and others) to figure out what is going on, but it takes reading a lot of issues and forum threads to understand how this special flavour of FreeBSD works.

**Comment by oparoz** [comment]
I was looking at the wrong server...

`/tmp/PHP_errors.log` is getting hammered with errors and that's probably why the crash reporter always wants to submit a new report, so this report is bogus. It's just the logs which are being flooded.
