### ISSUE TITLE
Not able to add two WireGuard peers with same public key

### ISSUE THREAD

**Issue by adamcstorm** [opnsense/core#7213]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x ] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x ] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

The WireGuard new peer interface requires that the public key be unique for each peer.  This check was implemented with https://github.com/opnsense/core/issues/7110. This behavior makes sense to prevent duplicate peer public keys on the same WireGuard instance, but breaks functionality when using the same key on two peers belonging to separate instances.

The use case for adding multiple peers with the same public key on different WireGuard instances is connecting to two privacy VPN endpoints for the purposes of load balancing/failover. 

**To Reproduce**

1. Configure a Wireguard instance.
2. Add two peers with the same public key, but select a different instance.
3. Attempt to save, a warning will appear that public keys need to be unique and the save will not complete

**Expected behavior**

I agree that duplicate public keys on peers of the same instance is problematic. However, this is not a requirement when using separate instances. I don't know the best way to handle this, but can make a couple suggestions:
- Allow the save to happen but present a warning about duplicate public keys
- Only prevent the save if a selected instance has a peer with a duplicate public key
- Don't allow an instance to be selected if a peer with the same public key is configured for that instance

I'm sure there are other/more graceful ways of mitigating the issue. 

Software version used and hardware type if relevant, e.g.:

OPNsense 24.1.1 (amd64).

**Comment by AdSchellevis** [comment]
isn't that just one peer belonging to two instances? or am I missing something

**Comment by AdSchellevis** [comment]
@adamcstorm ah, so your problem is peers should be unique per pubkey+instance, right?

**Comment by adamcstorm** [comment]
Correct, if there's a need to put a limitation in at all. When I connect to my privacyVPN, they give the same public key for multiple endpoints, which I have to put in the peer public key. Since each peer can only connect to a single endpoint, I have to set up a different peer for each privacyVPN endpoint I wish to connect to. Since each of these peers are configured to use a different wireguard instance, there is no conflict. I don't know that a limitation as implemented in the linked change is strictly required by the wireguard architecture.

**Comment by AdSchellevis** [comment]
I'm not sure I can make everybody happy here. We can add constraints, warnings are not a feature. More complex constraint scenario's are possible, but also add logic (and cost time to develop). 

Leaving this ticket open for now to figure out if this is a rare issue or more common.

**Comment by adamcstorm** [comment]
@AdSchellevis I'm fully supportive of a more sensible solution. I don't think overcomplicating this is necessary. I do believe that the current restriction breaks compatibility with the wireguard architecture by implementing a superfluous restriction. May I suggest the limitation be removed until a better solution is available? Duplicating a public key on an instance is an administrative problem, after all. Restricting the re-use of a public key to mitigate the problem is noble, but has resulted in a breaking restriction for a valid use case.

**Comment by AdSchellevis** [comment]
@adamcstorm wait a second, I might be wrong here. you have two identical keys used by two different remote hosts?

**Comment by adamcstorm** [comment]
Correct

**Comment by AdSchellevis** [comment]
@adamcstorm this https://github.com/opnsense/core/commit/ce8b3c878f5b5411b3562b6c47ef417b1546aec1 should fix your issue and the original one

**Comment by adamcstorm** [comment]
@AdSchellevis Can confirm this change works for the issue I reported and my specific use case. Thanks for being so responsive!
If there is any future effort put in this area, I might suggest the second requirement be tied to the instance selected and not the server/port. Not sure how feasible that is though. From my understanding the issue really is duplicate public keys per instance and not necessarily per server/port combination. Can't say how likely it is to need to have the same server/port on different instances but I suppose it's possible. Most likely scenario is when the fields are left blank for a dynamic endpoint. Current change is great, this is just food for thought. 

Cheers!

**Comment by AdSchellevis** [comment]
@adamcstorm let's see if this is enough, adding instance to the mix is a bit more complicated as the same peer can be connected to multiple instances (in which case you probably also don't need a copy by the way).

**Comment by gitthangbaby** [comment]
> @adamcstorm wait a second, I might be wrong here. you have two identical keys used by two different remote hosts?

i confirm i also connect to different hosts with the same public and preshared key from Opnsense at the same time and balance. it's unavoidable for thousands of customers. i edit multiple peers and instances in config.xml, changes are reflected immediately. the change looks good, thanks.

**Comment by 0xShkk** [comment]
Hi,

I am having the same issue. I want to add a second peer with the same public key as an existing one. The endpoint address is the same but the port is different. It maps to two different wg servers on different ports with same public key. 

My workaround currently is to add the second peer via a config import after manually editing the backup config xml.

This works but would be nice to be able to do the same via the gui.

**Comment by 0xShkk** [comment]
Just updated to 24.1.2 and my problem was solved :)

**Comment by gitthangbaby** [comment]
It's solved and there's a little related glitch. In the Diagnostics tab, the "Name" column will show duplicit peer name, probably based on public key.

Settings - Peer:
Name Endpoint (key)
VPN1 endpoint1.tld key XXXXXXXXXX
**VPN2** endpont2.tld key XXXXXXXXXX
Diagnostics:
Public Key Name Endpoint
key XXXXXXXXXX VPN1 endpoint1.tld
key XXXXXXXXXX **VPN1** endpont2.tld

**Comment by AdSchellevis** [comment]
@gitthangbaby better open a separate ticket for this

**Comment by AdSchellevis** [comment]
@CaptchaHuman  https://github.com/opnsense/core/commit/25072fae65cea8615800ea4e23b419e7e5fbed04 released in 24.1.3?

**Comment by CaptchaHuman** [comment]
@AdSchellevis I'm on opnsense 24.1.5_3

**Comment by AdSchellevis** [comment]
@CaptchaHuman then these changes are in and you should be able to add a peer with a duplicate pubkey as long as endpoint and/or port differ... works on my end

**Comment by CaptchaHuman** [comment]
@AdSchellevis I updated and hadn't tried it again. Works now, thanks!

**Comment by AdSchellevis** [comment]
🤷‍♂️
