### ISSUE TITLE
Captive Portal generate Voucher

### ISSUE THREAD

**Issue by DokuKaefer** [opnsense/core#722]
I can generate in one Voucher Role more than 250 Vouchers.
Clicking rapidly on the "generate button".
Is this good? :)

![vouchers](https://cloud.githubusercontent.com/assets/11537653/12661471/0ca3e08e-c61a-11e5-8b99-e3e88ba8339b.png)

**Comment by AdSchellevis** [comment]
Its not really a problem if more are generated, but may be its smart to limit the max amount a bit.
Will fix this in the next commit.
