### ISSUE TITLE
WireGuard endpoints don't have Internet access unless service manually restarted

### ISSUE THREAD

**Issue by Kinerg** [opnsense/core#7222]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [+] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [-] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

After OPNsense boot, WireGuard endpoints don't have Internet access. Restarting WireGuard service fixes the issue.

**To Reproduce**

1. Restart OPNsense
2. Connect WireGuard endpoint
3. Try to access Internet or ping any domain/IP, no answer
4. Restart WireGuard service
5. Everything works

**Expected behavior**

WireGuard clients should have Internet access after OPNsense boot.

**Relevant log files**

This gets added to WireGuard log after every boot:

```
/usr/local/opnsense/scripts/Wireguard/wg-service-control.php: The command '/sbin/route -q -n add -'inet' '10.101.1.2/30' -interface 'wg2'' returned exit code '1', the output was ''
```

**Additional context**

This is a reopen of the issue #6909 which was set to be resolved in 24.1

**Environment**

OPNsense 24.1.1-amd64
FreeBSD 13.2-RELEASE-p9
OpenSSL 3.0.13

**Comment by fichtner** [comment]
We have enough tickets as is ;) #7148

**Comment by Kinerg** [comment]
Sorry, missed that one.
