### ISSUE TITLE
Kea DHCP: DNS server addresses disappear in subnet settings

### ISSUE THREAD

**Issue by KaiKimera** [opnsense/core#7225]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

DNS server addresses disappear in Subnet settings.

**To Reproduce**

1. Add several DNS servers (10.0.0.1, 1.1.1.1, 8.8.8.8) to Subnet.
2. Click the Save button.
3. Open Subnet settings.
4. See only 10.0.0.1.

**Environment**

Software version used and hardware type if relevant, e.g.:

- OPNsense 24.1.1-amd64
- FreeBSD 13.2-RELEASE-p9
- OpenSSL 3.0.13

**Comment by AdSchellevis** [comment]
looks like using "Auto collect option data" 
<img width="619" alt="image" src="https://github.com/opnsense/core/assets/9783985/e3ec8da8-127e-48e2-a906-fc14ac3614e6">

**Comment by KaiKimera** [comment]
> looks like using "Auto collect option data" <img alt="image" width="619" src="https://private-user-images.githubusercontent.com/9783985/303824606-e3ec8da8-127e-48e2-a906-fc14ac3614e6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc1NTQ2MTAsIm5iZiI6MTcwNzU1NDMxMCwicGF0aCI6Ii85NzgzOTg1LzMwMzgyNDYwNi1lM2VjOGRhOC0xMjdlLTQ4ZTItYTkwNi1mYzE0YWMzNjE0ZTYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIxMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMTBUMDgzODMwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDNkMWYxOWJjZGU2OWVhNDk4MzU5MmEzNjk2OTNmMjY5M2NhYmZjNjNhYmI4MWNlYmIzNDEzZjFiM2VhMmYzYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.teJD5fiHsXWWYXGPoRM4oCEYx81mdbx2z6TjejP3qjs">

The issue is resolved. I forgot about this checkbox. My mistake.

**Comment by AdSchellevis** [comment]
@KaiKimera no problem, I've added https://github.com/opnsense/core/commit/bf9996989ee653ce1cc4c0df03f2405d78c30721 to make it more explicit from the users perspective. (hide when automatically collected on save)
