### ISSUE TITLE
"enabled" always true in dhcpd.inc

### ISSUE THREAD

**Issue by nt1** [opnsense/core#7226]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

It appears as if the dhcp configuration enabled flag is misinterpreted as true throughout [dhcpd.inc](https://github.com/opnsense/core/blob/25d06fd8129a1d6733dc6ce0ed38073b0917e25b/src/etc/inc/plugins.inc.d/dhcpd.inc).  As seen [here](https://github.com/opnsense/core/blob/25d06fd8129a1d6733dc6ce0ed38073b0917e25b/src/etc/inc/plugins.inc.d/dhcpd.inc#L715), the value of enabled is interpreted with `isset`, which only returns false if the variable has been declared and is not null.  However, the value of enabled will always be set as a boolean according to [this code](https://github.com/opnsense/core/blob/25d06fd8129a1d6733dc6ce0ed38073b0917e25b/src/www/services_dhcp.php#L364), which uses `empty` to ensure falsey variables (eg unset, null, or false) are set to false prior to persisting the configuration.   When enabled is read back in dhcpd.inc, if its value is false, isset(enabled) evaluates to true.

**To Reproduce**

n/a

**Expected behavior**

dhcpd.inc uses `empty` instead of `isset` when evaluating variables.

**Environment**

```
 % opnsense-version
OPNsense 24.1.1
```

**Comment by fichtner** [comment]
Just open a PR, easier to discuss. Due to PHP internals nowadays we rather use empty() instead of isset() but it has these side effects with a legacy code base since there is no unified model to access the settings.

**Comment by fichtner** [comment]
I tested this and disabling the server does the following:

```
--- /conf/backup/config-1718086462.5496.xml	2024-06-11 08:14:22.579710000 +0200
--
+++ /conf/backup/config-1718171701.5105.xml	2024-06-12 07:55:01.539178000 +0200
@@ -603,7 +603,6 @@
</staticmap>
</lan>
<opt3>
-      <enable>1</enable>
<ddnsdomainalgorithm>hmac-md5</ddnsdomainalgorithm>
<numberoptions>
<item/>
@@ -627,7 +626,6 @@
<dnsserver>10.1.2.3</dnsserver>
<ntpserver/>
</pool>
-      <staticmap/>
</opt3>
</dhcpd>
```

I'm not sure why but it warrants the use of isset() if the `enable` node disappears. If this was a larger issue someone would surely have reported it by now.
