### ISSUE TITLE
Web GUI failed to start on 24.1.1

### ISSUE THREAD

**Issue by codegain** [opnsense/core#7227]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

After upgrading from 23.7 to 24.1 the web GUI fails to start on reboot. Using the console and "11) Reload all services" reveals: `Starting web GUI...failed` but no further information. It also seems that the command never finishes (see screenshot).
All other things (f.e. connectivity) seem to work fine.

**To Reproduce**

1. Be on 23.7
2. Upgrade to the latest 24.1 from the web GUI
3. Wait for the update to finish
4. Web GUI not starting on reboot

**Expected behavior**

Web GUI is starting normally

**Describe alternatives you considered**

The upgrade from 23.7 to 24.1 did finish without any errors and I was able to get the web GUI to work after running `11) Reload all services`. Then the web GUI prompted me to update some further packages (this was the hotifx for suricata 7 -> 6). After the install I rebooted and now  `11) Reload all services` fails to start the web GUI.

**Screenshots**

![image](https://github.com/opnsense/core/assets/11192306/542fd06a-8ab3-449c-8144-91deba4d6f82)

**Relevant log files**

(Not really sure how to get them, please point me to a cmd/file via console if you need any)

**Additional context**

**Environment**

Software version used and hardware type if relevant, e.g.:

Running as VM on Proxmox 8.1.4
OPNsense 24.1.1 (amd64).

**Comment by codegain** [comment]
FYI: `configctl webgui restart` on the shell did the trick for me, but the web GUI still does not start successfully on reboot.

**Comment by codegain** [comment]
Found this in the log file relating to lighttpd, only appears in the log after 24.1 upgrade:

```
/usr/local/etc/rc.bootup: The command '/usr/local/bin/flock -ne /var/run/lighty-webConfigurator.pid /usr/local/sbin/lighttpd -f /var/etc/lighty-webConfigurator.conf' returned exit code '255', the output was '2024-02-11 14:17:10: (/usr/obj/usr/ports/www/lighttpd/work/lighttpd-1.4.73/src/mod_openssl.c.1356) SSL: inactive/expired X509 certificate '/var/etc/cert.pem' 2024-02-11 14:17:10: (/usr/obj/usr/ports/www/lighttpd/work/lighttpd-1.4.73/src/network.c.588) bind() [XXXX::XXXX:XXXX:XXXX:XXXX]:443: Can't assign requested address'
```

I'm not using any certificate, only self-signed.

**Comment by AdSchellevis** [comment]
Most likely binding to an interface, keep settings default or select a loopback for most consistent results.

**Comment by knumsi** [comment]
Same Problem for me.
System -> Settings -> Administration 
-> Listen Interfaces: LAN
-> HTTP Redirect: Checked "Disable web GUI redirect rule"
Port is not used in any other context on the firewall. 

Same Firmware:
Running as VM on Proxmox 8.1.4
OPNsense 24.1.1 (amd64).

Plugins & Tests:
Export config - import & reboot - no difference
HAProxy - Disable Plugin, reboot - no difference
os-ddclient - Uninstall
ACME - Disable Plugin, reboot - no difference
qemu-guest-agent - Uninstall, reboot - no difference

**Comment by fichtner** [comment]
https://docs.opnsense.org/manual/settingsmenu.html#listen-interfaces

**Comment by knumsi** [comment]
Interesting. This link was posted in another context as well, but that time it had the default settings. Because of this link I changed the settings to the following settings AFTER the webinterface did not come up. 
System -> Settings -> Administration
-> Listen Interfaces: LAN
-> HTTP Redirect: Checked "Disable web GUI redirect rule"

Changed back again, because you posted that link.
System -> Settings -> Administration
-> Listen Interfaces: None selected = All
-> HTTP Redirect: Unhecked "Disable web GUI redirect rule"

Now it comes back up again. Well - something inbetween did resolve this issue. Thank you.

**Comment by codegain** [comment]
Seems like on the 24.1 upgrade the configuration for Interfaces -> LAN "IPv6 configuration type" was set to "Track interface". I don't use IPv6 on WAN or LAN and can't remember to have set it myself.

Setting it to "None" and rebooting did fix this for me.

**Comment by fichtner** [comment]
> Seems like on the 24.1 upgrade the configuration for Interfaces -> LAN "IPv6 configuration type" was set to "Track interface". I don't use IPv6 on WAN or LAN and can't remember to have set it myself.

It was set to the factory default actually.

> HTTP Redirect: Unhecked "Disable web GUI redirect rule"

If you have haproxy or nginx running make sure to not overlap your port 80 by disabling this because otherwise the other service will complain about it and sometimes the GUI loses that race


Cheers,
Franco

**Comment by SilentGlasses** [comment]
Having this issue but only when using the hostname, I can load in fine using the IP . Nothing changed on my system other then the recent update.

**Comment by realslacker** [comment]
Turning off Track Interface for IPv6 fixed it for me as well
