### ISSUE TITLE
Adding a duplicate mac reservation causes kea to fail to start

### ISSUE THREAD

**Issue by fastalan** [opnsense/core#7230]
**Description**
By mistake when you add the same MAC address as a reservation the OPNSense UX accepted it, but when the firewall restarted kea failed to start taking down the entire bootp network. System should log an error/warning and disregard the duplicate.

**To Reproduce**

1. Go to DHCP reservations
2. Add a reservation by MAC
3. Save config, observe reservation is valid
4. Go to DHCP reservations and add another reservation for a different IP for the same MAC
5. The reservation is accepted
6. Restart the firewall
7. Note KEA does not start
8. Note log message: 
  | ERROR [kea-dhcp4.dhcp4.0x834b8d000] DHCP4_INIT_FAIL failed to  initialize Kea server: configuration error using file  '/usr/local/etc/kea/kea-dhcp4.conf': failed to add new host using the HW  address 'xx:xx:xx:xx:xx:xx' to the IPv4 subnet id '1' as this host has  already been added

**Expected behavior**
Log a warning disregard the duplicate or all reservations with the same MAC.

**Describe alternatives you considered**

Workaround is you remove the duplicate and start KEA

**Screenshots**

N/A

**Relevant log files**

Indicated in steps to reproduce

**Additional context**

**Environment**

Version | 24.1.1 |  
Architecture | amd64 |  
Commit | 516bda3fc

**Comment by fastalan** [comment]
I used the template and modified it as I made the report, if you guys are going to ignore the defect, not my problem, I already know the workaround.

**Comment by AdSchellevis** [comment]
not going to argue with botty (template is missing elements), but we should indeed add a constraint there (https://github.com/opnsense/core/commit/27e27f25c5bdfb1a6eff74073ec2ab452af2cff7)
