### ISSUE TITLE
Kea TFTP server name validation is too restrictive

### ISSUE THREAD

**Issue by miken32** [opnsense/core#7235]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

Validation of DHCP option 66 is too restrictive; it is defined in standards (and [Kea documents](https://kea.readthedocs.io/en/latest/arm/dhcp4-srv.html#standard-dhcpv4-options)) as a field that can contain any text, but currently is being validated with regex `/^([0-9a-zA-Z.\:\-,_]){0,1024}$/u`. 

**Additional context**

Hardware vendors often use this field for rich provisioning info. For example, Polycom allows full URIs pointing to provisioning servers.

**Comment by AdSchellevis** [comment]
@miken32 https://github.com/opnsense/core/commit/098a89b9652f68c038ee39147dd8ee7fb4ba99ad only excludes newlines and double quotes to prevent config breakage.

**Comment by miken32** [comment]
Perfect, thanks. (FWIW, I tested with double quotes and the templating engine does properly escape them.)
