### ISSUE TITLE
interfaces: convert GRE configuration to MVC/API

### ISSUE THREAD

**Issue by fichtner** [opnsense/core#7242]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**

GRE interfaces can not be operated by API.

**Describe the solution you like**

Time to migrate!

**Describe alternatives you considered**

N/A

**Additional context**

N/A

**Comment by SilentGlasses** [comment]
You have two exact issues open, please close one out to keep the devs from having to look over two identical things and avoid having others from adding different comments across both.  

Thanks.

Duplicate: https://github.com/opnsense/core/issues/7242
