### ISSUE TITLE
src: FreeBSD 14.1

### ISSUE THREAD

**Issue by fichtner** [opnsense/core#7245]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**

_ticket updated, original plan was 13.3_

13.2 will be outdated pretty quickly as 13.3 is scheduled for March 2024.
14.1 seems to align with our timeline (https://www.freebsd.org/releases/14.1R/schedule/), which makes it an interesting option.

**Additional context**

N/A

**Comment by ronin3510** [comment]
Colin seems to want to wrap it up by end of February according to his comments on Twitter when announcing RC3.

Will we have a snapshots/13.3 branch then to test 13.3 + php8.3 + python 3.11 before pushing it to 24.1.x ?

Unsure about the rest, but python 3.11 should bring in a noticeable performance bump overall.

**Comment by joaquinvacas** [comment]
https://freebsdfoundation.org/blog/a-sneak-peek-simd-enhanced-string-functions-for-amd64/

Is there any possibility of backporting this to 13.3?

As I've seen it's being backported to 14.1
