### ISSUE TITLE
Firewall log contains IGMP for rules that do not have logging on

### ISSUE THREAD

**Issue by sh3llc0de** [opnsense/core#725]
Can we get this fixed?

https://redmine.pfsense.org/issues/4383

**Comment by ikenigma** [comment]
Confirming I can replicate this too.

Long story short: some networks with noisy IGMP traffic will spam the firewall logs mercilessly.

There appears to be no way to get this noise out of the logs
    - not from any of the default frewall log items
    - disabling all the default logged things, (rfc1918 and bogons) still lets these get logged
    - creting floating firewall to block IGMP (and not log) does not work
    - creating firewall on interface itself to block IGMP (and not log) does not work

**Comment by fichtner** [comment]
I found the FreeBSD patch on the stable/10 branch while reviewing code changes for pf(4). I will merge it into our stable/16.1 branch, but it will be shipped in 16.1.2, not 16.1.1 (tomorrow already).

**Comment by fichtner** [comment]
FYI https://github.com/opnsense/src/commit/bbff73ecb564a941bef5718ac7495c01d2e424cb
