### ISSUE TITLE
GUI: 7 rows

### ISSUE THREAD

**Issue by gitthangbaby** [opnsense/core#7252]
When browsing windows, the tables are only 7 rows.
It can drive a person crazy to keep setting the value to a reasonable value, e.g. 20 for a standard screen.
The setting is forgotten over and over.

Is your feature request related to a problem? Please describe.
#3560 (not fixed), #3550 (not fixed)

Describe the solution you'd like
WebUI settings page, with settings like this to set default rows per page.
and/or
Remember the table setting (e.g. on server side, per user).

Describe alternatives you've considered
Hardcoded value (e.g. mobile view:7, desktop view:20).

Additional context
Note some pages offer different different set of choices (e.g. 25 instead of 20).

**Comment by Gauss23** [comment]
+1 on this one!

**Comment by fichtner** [comment]
The dashboard will be replaced. It’s currently being worked on but realistically that’s not before 25.1.
