### ISSUE TITLE
log entries are missing a space between script name and log payload

### ISSUE THREAD

**Issue by dominikborkowski** [opnsense/core#7258]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

While working with the AWS AMI, we noticed that log entries related to password changes had the name of the php script smooshed with the payload it produced, eg:

```
latest.log:<37>1 2024-02-20T04:35:42+00:00 OPNsense.localdomain audit 58523 - [meta sequenceId="23"] user (root) changed configuration to /conf/backup/config-1708403742.8139.xml in /usr/local/opnsense/scripts/aws/set_password.phpec2-user password chang
ed from console
latest.log:<37>1 2024-02-20T04:35:43+00:00 OPNsense.localdomain audit 62068 - [meta sequenceId="27"] user (root) changed configuration to /conf/backup/config-1708403743.0899.xml in /usr/local/opnsense/scripts/aws/set_password.phproot password changed f
rom console
```

*Tip*: to validate your setup was working with the previous version, use opnsense-revert (https://docs.opnsense.org/manual/opnsense_tools.html#opnsense-revert)

**To Reproduce**

1. Boot AWS AMI image
2. Inspect logs in /var/log/audit/

**Expected behavior**

A space between `set_password.php` and `usernamehere`

**Additional context**

@AdSchellevis pointed out that this issue may be caused by  https://github.com/opnsense/core/blob/e7d18bfedc185b362ca849d39fa0ebc23e2bf4cf/src/opnsense/mvc/app/library/OPNsense/Core/Config.php#L554 

Thank you!

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 23.7.12
AWS AMI

**Comment by AdSchellevis** [comment]
@dominikborkowski thanks for the ticket, should be fixed with https://github.com/opnsense/core/commit/efb9162e6978b414f8afe31f419142b174f96464
