### ISSUE TITLE
GUI of services->dhcp-> server: Change static mapping configuration 

### ISSUE THREAD

**Issue by bringha1** [opnsense/core#726]
When static mapping configurations are changed or added in Services->dhcp->server, the light blue bar 'Änderungen übernehmen' does not disappear again. The bar remains until next reboot. 

<img width="1385" alt="bildschirmfoto 2016-01-31 um 09 19 08" src="https://cloud.githubusercontent.com/assets/15860903/12701044/bcc593f8-c7fb-11e5-93f5-11d2cbfc85ed.png">

The topic has been described for 15.7. in [https://forum.opnsense.org/index.php?topic=1802.0](url) and has been reported as fixed in 16.1 but is still in 16.1

**Comment by fichtner** [comment]
@bringha1 I'm still not able to reproduce this, we'll have to look at internals. I'll need the following output after editing a static map entry and after pressing "Änderungen übernehmen". thanks in advance :)

    # ls /tm/*.dirty

**Comment by bringha1** [comment]
Hallo Franko,

Ich nehme an Du meinst /tmp/*.dirty - da gibt es bei mir nur ein staticmaps.dirty und das ist leer (nach beiden Schritten)

Aus meiner Sicht ist das Thema FUNKTIONAL nicht kritisch, aber störend auf der GUI Ebene. Ich bin mir nicht sicher ob wir nicht aneinander vorbeireden: es geht um diese Bildsequenz:

Nach einer inhaltlichen Änderung und Drücken von ‚Speichern‘ nach Änderungen in den Staticmaps sieht das Bild so aus:



Das ist OK, die Änderungen sollen bestätigt werden; nach drücken des 'Änderungen übernehmen' Buttons sieht das Bild dann so aus:




Das heisst, es  erscheint unter  der (erwarteten) blauen Box ‚die Änderungen wurden erfolgreich übernommen‘ AUCH NOCHMAL die ‚The static mapping configuration  has been changed … Änderungen übernehmen' Box. Und die ist dann nicht mehr wegzubekommen. Beim ersten mal drücken verschwindet dann die obere blaue Box, drückst Du immer weiter Änderungen übernehmen, passiert nix mehr,  die Box bleibt einfach stehen. Gehst du aus der dhcp Server Seite raus, machst was anderes, gehst dann wieder auf die dhcp server seite, ist die Box immer noch/wieder da. Ich kann das dann nur durch Neustart  von opnsense wieder verschwinden lassen.

Erwarten würde ich wie bei allen ‚Änderung übernehmen‘ Button Presses auf anderen Seiten  auch, dass die blaue Box ‚The mapping configuration ….‘ nach drücken von Änderungen übernehmen ERSETZT WIRD durch 'Die Änderungen wurden erfolgreich angewandt'. …. und gut ist

Vielleicht habe ich mich ungeschickt ausgedrückt, dann nichts für ungut


Br br

**Comment by fichtner** [comment]
Moin, ja, hatte mich initial vertippt. :) Die Datei müsste gelöscht werden, dann verschwindet auch die Meldung. Kannst du das versuchen?

Ich hab verstanden, du hattest es schon bestens beschrieben. Hatte vorher leider angenommen, dass es mit einem anderen Fehler zusammenhängt.

Große Preisfrage ist ob beim nächsten Editieren das gleiche passiert. Wenn ja, dann beendet sich der Code vor dem korrekten Löschen. Zumindest hätten wir es dann schon gut eingegrenzt.

**Comment by bringha1** [comment]
Ich habe gerade ausprobiert, es passiert im Prinzip das gleiche, allerdings mit einer kleinen Änderung: Drückt du Änderungen übernehmen bleiben BEIDE blauen Blöcke dauerhaft stehen. Lösche ich dann /tmp/staticmaps.dirty dann bleibt der ‚Änderungen wurden erfolgreich‘ Block stehen

Br br

**Comment by fichtner** [comment]
Moin, benutzt du den DNS Resolver?

**Comment by bringha1** [comment]
yep - und der soll auch DHCP Leases registrieren (tut er auch artig ….)

**Comment by fichtner** [comment]
gut, das wars, besten dank :)

**Comment by bringha1** [comment]
Thx!!
