### ISSUE TITLE
Local nameserver still used for DNS even if advised not to do

### ISSUE THREAD

**Issue by 0xShkk** [opnsense/core#7272]
**Describe the bug**

I am using the dnscrypt-proxy plugin for the local system DNS. Dnscrypt is configured to act as the local system DNS by listening on `0.0.0.0:53` as described in the documentation. However, the OPNsense setting `Do not use the local DNS service as a nameserver for this system` is checked but still DNScrypt proxy is used for resolving DNS queries originating from the local OPNsense system. OPNsense version is 24.1.2

**To Reproduce**

- Install dnscrypt-proxy plugin
- Configure dnscrypt proxy to listen on `0.0.0.0:53`
- Check the OPNsense setting `Do not use the local DNS service as a nameserver for this system` in `System` -> `Settings` -> `General`
- Do not set any other system DNS servers
- Try to ping a name via th OPNsense CLI
- See names resolved by dnscrypt-proxy

**Expected behavior**

By setting `Do not use the local DNS service as a nameserver for this system` in combination with no other DNS servers set for system, no DNS lookups should be possible for the OPNsense host system.

**Comment by fichtner** [comment]
You may just want to check /etc/resolv.conf beforehand.

**Comment by kulikov-a** [comment]
> By setting Do not use the local DNS service as a nameserver for this system in combination with no other DNS servers set for system, no DNS lookups should be possible for the OPNsense host system.

https://man.freebsd.org/cgi/man.cgi?resolv.conf
_If no nameserver entries are present, the default is to use the name server on the local machine_

**Comment by fichtner** [comment]
Yeah sounds like it, but in any case `/etc/resolv.conf` contents would be helpful to pinpoint.

**Comment by 0xShkk** [comment]
Contents in my `/etc/resolv.conf` is only the following 

```
domain local
search local
```

**Comment by 0xShkk** [comment]
Yea actually it works as designed...

However I was confused by the gui settings. Maybe you could add a floating message or similar when the checkbox is checked and no nameservers are set to make aware of FreeBSD name resolution logic.

In my scenario, I think I will reconfigure dnscrypt proxy to not be the system DNS by let it listen on something different than 53 and then Port fwd the clients to it in the nets where they need access.

Thanks for your kind support. This can be closed from my side.
