### ISSUE TITLE
Update issues from 23.7.12 to 24.1.1

### ISSUE THREAD

**Issue by ElXk6** [opnsense/core#7275]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

We started the updates to 24.1.1 at the beginning of last week.
The first ~10 FWs went through without any problems.
After that, however, three FWs were affected at the same time. All with the same problem.

The FWs could only be pinged, after a restart they were no longer accessible.

Unfortunately, I've only just got around to looking at the three cases.
In all three cases, the following error occurs when booting (over serial interface), which means that the services no longer start:
SSH: ld-elf.so.1: Shared object "libcrypto.so.11" not found, required by "ssh-keygen"

See also the logs below.

Is the problem already known and I just haven't found it here?

**Relevant log files**

Boot:
```
SSH:   ld-elf.so.1: Shared object "libcrypto.so.11" not found, required by "ssh-keygen"
SSH:   ld-elf.so.1: Shared object "libcrypto.so.11" not found, required by "ssh-keygen"
SSH:   ld-elf.so.1: Shared object "libcrypto.so.11" not found, required by "ssh-keygen"
```

root@example.com:~ # sockstat -4 -l
```
USER     COMMAND    PID   FD PROTO  LOCAL ADDRESS         FOREIGN ADDRESS
root     lighttpd   55578 4  tcp4   127.0.0.1:43580       *:*
nobody   dnsmasq    37000 4  udp4   *:53                  *:*
nobody   dnsmasq    37000 5  tcp4   *:53                  *:*
dhcpd    dhcpd      33366 13 udp4   *:67                  *:*
```
root@example.com:~ # sockstat -6 -l
```
USER     COMMAND    PID   FD PROTO  LOCAL ADDRESS         FOREIGN ADDRESS
nobody   dnsmasq    37000 6  udp6   *:53                  *:*
nobody   dnsmasq    37000 7  tcp6   *:53                  *:*
```

root@example.com:~ # service openssh onestart
```
ld-elf.so.1: Shared object "libcrypto.so.11" not found, required by "ssh-keygen"
ld-elf.so.1: Shared object "libcrypto.so.11" not found, required by "ssh-keygen"
ld-elf.so.1: Shared object "libcrypto.so.11" not found, required by "ssh-keygen"
ld-elf.so.1: Shared object "libcrypto.so.11" not found, required by "ssh-keygen"
Performing sanity check on openssh configuration.
ld-elf.so.1: Shared object "libcrypto.so.11" not found, required by "sshd"
/usr/local/etc/rc.d/openssh: WARNING: failed precmd routine for openssh
```

root@example.com:~ # /usr/local/sbin/lighttpd -f /var/etc/lighty-webConfigurator.conf
```
2024-02-23 14:07:58: (/usr/obj/usr/ports/www/lighttpd/work/lighttpd-1.4.73/src/plugin.c.221) dlopen() failed for: /usr/local/lib/lighttpd/mod_openssl.so Shared object "libssl.so.11" not found, required by "mod_openssl.so"
2024-02-23 14:07:58: (/usr/obj/usr/ports/www/lighttpd/work/lighttpd-1.4.73/src/server.c.1643) loading plugins finally failed
```

ps ax:
```
  PID TT  STAT     TIME COMMAND
    0  -  DLs   0:01.19 [kernel]
    1  -  ILs   0:00.05 /sbin/init
    2  -  DL    0:00.00 [KTLS]
    3  -  DL    0:00.00 [crypto]
    4  -  DL    0:00.00 [cam]
    5  -  DL    0:00.53 [pf purge]
    6  -  DL    0:00.10 [rand_harvestq]
    7  -  DL    0:00.52 [mmcsd0: mmc/sd card]
    8  -  DL    0:00.12 [pagedaemon]
    9  -  DL    0:00.00 [vmdaemon]
   10  -  DL    0:00.00 [audit]
   11  -  RNL  59:46.58 [idle]
   12  -  WL    0:01.03 [intr]
   13  -  DL    0:00.48 [geom]
   14  -  DL    0:00.00 [sequencer 00]
   15  -  DL    0:00.09 [usb]
   16  -  DL    0:00.06 [bufdaemon]
   17  -  DL    0:00.01 [vnlru]
   18  -  DL    0:00.13 [syncer]
  219  -  Is    0:03.11 /usr/local/bin/python3 /usr/local/opnsense/service/configd.py (python3.9)
  224  -  I     0:19.01 /usr/local/bin/python3 /usr/local/opnsense/service/configd.py console (python3.9)
  444  -  Is    0:00.02 /sbin/devd
33366  -  Is    0:00.06 /usr/local/sbin/dhcpd -user dhcpd -group dhcpd -chroot /var/dhcpd -cf /etc/dhcpd.conf -pf /var/run/dhcpd.pid igb1 igb2 igb2_vlan2 igb2_vlan3 igb2_vlan4
37000  -  I     0:00.00 /usr/local/sbin/dnsmasq -H /var/etc/dnsmasq-hosts -H /var/etc/dnsmasq-leases --all-servers --dns-forward-max=5000 --cache-size=10000 --local-ttl=1 --conf-dir=/usr/local/etc/dnsmasq.conf.d,*.conf
39896  -  Ss    0:00.02 /usr/sbin/cron -s
50743  -  Ss    0:00.03 /usr/local/sbin/filterlog -i pflog0 -p /var/run/filterlog.pid
55578  -  S     0:00.04 /usr/local/sbin/lighttpd -f /var/etc/lighttpd-acme-challenge.conf
63547  -  SC    0:00.00 sleep 1
69060  -  Ss    0:00.61 /usr/local/sbin/mpd5 -b -d /var/etc -f mpd_wan.conf -p /var/run/pppoe_wan.pid -s ppp pppoeclient
73989  -  DL    0:00.00 [ng_queue]
81637  -  Is    0:00.00 daemon: /var/db/rrd/updaterrd.sh[81801] (daemon)
81801  -  S     0:00.03 /bin/sh /var/db/rrd/updaterrd.sh
61393 u0  I     0:00.01 /bin/sh /usr/local/sbin/opnsense-shell
63567 u0  R+    0:00.00 ps ax
73786 u0  S     0:00.16 /bin/csh
76693 u0  Is    0:00.03 login [pam] (login)
73710 v0  Is+   0:00.01 /usr/libexec/getty Pc ttyv0
74372 v1  Is+   0:00.01 /usr/libexec/getty Pc ttyv1
75134 v2  Is+   0:00.01 /usr/libexec/getty Pc ttyv2
75407 v3  Is+   0:00.01 /usr/libexec/getty Pc ttyv3
75692 v4  Is+   0:00.01 /usr/libexec/getty Pc ttyv4
75942 v5  Is+   0:00.01 /usr/libexec/getty Pc ttyv5
76434 v6  Is+   0:00.01 /usr/libexec/getty Pc ttyv6
76447 v7  Is+   0:00.01 /usr/libexec/getty Pc ttyv7
```

Restart all Services:
```
Enter an option: 11

Writing firmware settings: FreeBSDcp: /usr/local/etc/pkg/repos/OPNsense.conf.sample: No such file or directory
 OPNsense
Writing trust files...done.
Scanning /usr/share/certs/blacklisted for certificates...
Scanning /usr/share/certs/trusted for certificates...
Scanning /usr/local/share/certs for certificates...
Writing trust bundles...done.
Configuring login behaviour...done.
Configuring CRON...done.
Setting timezone: Europe/Berlin
Setting hostname: example.com
Generating /etc/resolv.conf...done.
Generating /etc/hosts...done.
Configuring loopback interface...done.
Configuring LAGG interfaces...done.
Configuring VLAN interfaces...vlan0: changing name to 'igb2_vlan2'
vlan1: changing name to 'igb2_vlan3'
vlan2: changing name to 'igb2_vlan4'
done.
Configuring PPPoE interface...ng0: changing name to 'pppoe0'
done.
Configuring VLAN2 interface...done.
Configuring VLAN3 interface...done.
Configuring VLAN4 interface...done.
Configuring WLAN interface...done.
Configuring LAN interface...done.
Setting up routes...done.
Setting up gateway monitors...done.
Configuring firewall.......done.
Starting DHCPv4 service...done.
Starting Dnsmasq DNS...done.
Starting NTP service...done.
Configuring OpenSSH...failed.
Starting web GUI...failed.
Syncing OpenVPN settings...done.
Generating RRD graphs...done.
Stopping acme_http_challenge.
Waiting for PIDS: 149112024-02-23T14:59:03.187726+01:00 example.com lighttpd 14911 - - (/usr/obj/usr/ports/www/lighttpd/work/lighttpd-1.4.73/src/server.c.2332) server stopped by UID = 0 PID = 44909
.
Starting acme_http_challenge.
2024-02-23T14:59:04.500934+01:00 example.com lighttpd 3905 - - (/usr/obj/usr/ports/www/lighttpd/work/lighttpd-1.4.73/src/server.c.1933) server started (lighttpd/1.4.73)
```

**Additional context**

All three FWs are still old, slow SD card devices.
Could this have something to do with it?
Coincidentally, all the others are running with SSDs and had no problems.

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 23.7.12-amd64
FreeBSD 13.2-RELEASE-p7
OpenSSL 1.1.1w
AMD GX-412TC SOC (4 cores, 4 threads)

**Comment by michalsladek** [comment]
I have exactly the same problem. HW [APU1D4](https://www.pcengines.ch/apu1d4.htm). Services (SSH, WebGUI, Network UPS Tools) complain about missing libraries libcrypto.so.11 or libssl.so.11. Firewall is accessible only via serial console.

**Comment by michalsladek** [comment]
root@gw:~ # opnsense-update
ld-elf.so.1: Shared object "libssl.so.11" not found, required by "opnsense-verify"

**Comment by fichtner** [comment]
Did you forget the arguments? Specifically -i should avoid calling opnsense-verify ;)

**Comment by michalsladek** [comment]
No I didn't. It complains all the time, regardless of arguments you use. I tried your command first.

**Comment by fichtner** [comment]
Then just use OPNsense-bootstrap as described in the documentation.

**Comment by michalsladek** [comment]
Thanks for your tip Franco! Opnsense-bootstrap worked! You saved my day!

**Comment by ElXk6** [comment]
Should you always avoid opnsense-verify, or is this only necessary for this update?

opnsense-bootstrap, would not be a good solution for me, as the devices are no longer accessible externally once the update has been performed incorrectly. The only way to perform a rollback would be with the help of the serial interface.

**Comment by fichtner** [comment]
> Should you always avoid opnsense-verify, or is this only necessary for this update?

Only if it was broken by a partial upgrade, which can be the case when adding third party packages or manual ports builds.

> opnsense-bootstrap, would not be a good solution for me, as the devices are no longer accessible externally once the update has been performed incorrectly.

Can't solve accessibility issues for you. We recommend not doing upgrades without access to machines.

> The only way to perform a rollback would be with the help of the serial interface.

If you can roll back you can reinplace install ;)

As I said this was caused by a partial upgrade for whatever reason and it's out of support scope.


Cheers,
Franco
