### ISSUE TITLE
dhcp menu does not display network card settings

### ISSUE THREAD

**Issue by matiasduartee** [opnsense/core#7278]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

With version 24.1.2_1, the buttons for configuring the DHCP server [LAN] stopped displaying, as shown in the image.

![Painel  Lobby  NGFW rondomoveis corp e mais 6 páginas - Pessoal — Microsoft Edge](https://github.com/opnsense/core/assets/81826268/fd73a643-dd2f-4f46-9196-b6506c7e006e)

*Tip*: to validate your setup was working with the previous version, use opnsense-revert (https://docs.opnsense.org/manual/opnsense_tools.html#opnsense-revert)

**To Reproduce**

Perform a clean installation of the system in version 24, I installed the following plugins, os-ddclient, os-nginx, os-realtek-re, os-sensei, os-sensei-agent, os-sensei-updater, os-squid, os -sunnyvalley, os-theme-vicuna

**Expected behavior**

That the configuration options were displayed correctly, as in an installation I have here in version 23.7.12_5 as shown in the image.

![image](https://github.com/opnsense/core/assets/81826268/69288c0a-0235-4378-9c44-ee4eb43e431b)

Software version used and hardware type if relevant, e.g.:

OPNsense 24.1.2_1-amd64
Intel(R) Pentium(R) CPU G870 @ 3.10GHz (2 cores, 2 threads)

**Comment by fichtner** [comment]
A bit unexpected. Did you change your configuration from static IPv4 to something else? Because that's required...

**Comment by matiasduartee** [comment]
The only thing I change is the LAN IP from the default to my internal IP 192.168.0.254, simply after I run all the system updates this DHCP menu disappeared.

If I install from scratch and don't run the update, the menu continues to appear, after running all the updates and restarting it disappeared.

![image](https://github.com/opnsense/core/assets/81826268/196ef5b3-2126-4049-a6ab-2eb0ffd0837e)

**Comment by fichtner** [comment]
The fun part is on 24.1 the menu name is "ISC DHCPv4" so I'm not sure what's up with your screenshot there.

**Comment by matiasduartee** [comment]
See the logs

![image](https://github.com/opnsense/core/assets/81826268/d5f1b59a-89a5-49dd-a35b-39c275b46a30)

![image](https://github.com/opnsense/core/assets/81826268/9561bdbf-4852-4db5-8cf0-35a143314ff1)

![image](https://github.com/opnsense/core/assets/81826268/d03904f0-0e91-4256-b5d2-bdafd5f66047)

**Comment by fichtner** [comment]
The logs are not helpful. If you are on 24.1.2 and don't have "ISC DHCPv4" in the menu where your configurations are something is out of order for sure.

**Comment by matiasduartee** [comment]
see my friend

![image](https://github.com/opnsense/core/assets/81826268/4bced043-d05e-488b-a3c8-df5191946891)

![image](https://github.com/opnsense/core/assets/81826268/f293e89c-3637-4a1f-8167-0d52e8bebe6b)

**Comment by fichtner** [comment]
Can you clear your browser cache or use a different one to test again?

**Comment by matiasduartee** [comment]
Yes, I've tried accessing it from another browser, another device, even my smart phone and it doesn't display the full DHCP menu.

If I put the end /services_dhcp.php?if=lan in the browser link, I can access the LAN interface settings, however the [LAN] menu is not displayed as shown in the image.

**Comment by fichtner** [comment]
Can you do a health check from the firmware settings? There is just something off with your install.

**Comment by matiasduartee** [comment]
Would it be the Health option?

![image](https://github.com/opnsense/core/assets/81826268/d3797ae3-ba0a-485c-a514-3e2a3b15da0c)

**Comment by fichtner** [comment]
Yes

**Comment by matiasduartee** [comment]
Result!

`***GOT REQUEST TO AUDIT HEALTH***
Currently running OPNsense 24.1.2_1 at Tue Feb 27 11:49:22 -03 2024
>>> Root file system: /dev/gpt/rootfs
>>> Check installed kernel version
Version 24.1.2 is correct.
>>> Check for missing or altered kernel files
No problems detected.
>>> Check installed base version
Version 24.1.2 is correct.
>>> Check for missing or altered base files
Error 2 occurred.
etc/sysctl.conf: 
	size (299, 633)
	sha256digest (0x45f469e7a9b4eef887bab7b55397305043fe101e1d6ce6f7e23d758e72f56dc6, 0x4d6d289eb94b2d3fa79ea58e528447aebbefd254e408fef2f23c3011876aed78)
>>> Check installed repositories
OPNsense
SunnyValley
>>> Check installed plugins
os-ddclient 1.21
os-nginx 1.32.2
os-realtek-re 1.0
os-sensei 1.16.3
os-sensei-agent 1.16.5
os-sensei-updater 1.16
os-squid 1.0
os-sunnyvalley 1.4_3
os-theme-vicuna 1.45_1
>>> Check locked packages
No locks found.
>>> Check for missing package dependencies
Checking all packages: .......... done
>>> Check for missing or altered package files
Checking all packages: ...
opnsense-24.1.2_1: checksum mismatch for /boot/lua/brand-opnsense.lua
opnsense-24.1.2_1: checksum mismatch for /boot/lua/logo-hourglass.lua
opnsense-24.1.2_1: checksum mismatch for /usr/local/opnsense/mvc/app/models/OPNsense/Core/Menu/Menu.xml
opnsense-24.1.2_1: checksum mismatch for /usr/local/opnsense/mvc/app/views/OPNsense/Core/license.volt
Checking all packages....
os-theme-vicuna-1.45_1: checksum mismatch for /usr/local/opnsense/www/themes/vicuna/assets/stylesheets/bootstrap-dialog.less
os-theme-vicuna-1.45_1: checksum mismatch for /usr/local/opnsense/www/themes/vicuna/assets/stylesheets/main.scss
os-theme-vicuna-1.45_1: checksum mismatch for /usr/local/opnsense/www/themes/vicuna/assets/stylesheets/tokenizer2.scss
os-theme-vicuna-1.45_1: checksum mismatch for /usr/local/opnsense/www/themes/vicuna/build/css/bootstrap-dialog.css
os-theme-vicuna-1.45_1: checksum mismatch for /usr/local/opnsense/www/themes/vicuna/build/css/jquery.bootgrid.css
os-theme-vicuna-1.45_1: checksum mismatch for /usr/local/opnsense/www/themes/vicuna/build/css/main.css
os-theme-vicuna-1.45_1: checksum mismatch for /usr/local/opnsense/www/themes/vicuna/build/css/tokenize2.css
os-theme-vicuna-1.45_1: checksum mismatch for /usr/local/opnsense/www/themes/vicuna/build/images/default-logo.png
os-theme-vicuna-1.45_1: checksum mismatch for /usr/local/opnsense/www/themes/vicuna/build/images/favicon.png
os-theme-vicuna-1.45_1: checksum mismatch for /usr/local/opnsense/www/themes/vicuna/build/images/icon-logo.png
Checking all packages......... done
>>> Check for core packages consistency
Core package "opnsense" has 68 dependencies to check.
Checking packages: ..................................................................... done
***DONE***`

**Comment by fichtner** [comment]
Well that's your issue:

> opnsense-24.1.2_1: checksum mismatch for /usr/local/opnsense/mvc/app/models/OPNsense/Core/Menu/Menu.xml

You can just try to reinstall the "opnsense" package from the firmware packages tab.


Cheers,
Franco

**Comment by fichtner** [comment]
You're welcome. Small glich on the disk apparently.


Cheers,
Franco
