### ISSUE TITLE
Bug in the voucher generation of CSV File

### ISSUE THREAD

**Issue by DokuKaefer** [opnsense/core#728]
I test currently the voucher generation and found a bug in gerneration of Voucher-CSV File.

My steps:
1. Create Voucher DB
2. Create Voucher Role like "4 Hours"
3. Save the CSV File with name "4 Hours"
4. Create another Voucher Role like 1 Day
5. Save the CSV File with another name

But every CSV File after Step 3 is the same as the first Voucher Role.

Test with Chrome and Firefox.

**Comment by AdSchellevis** [comment]
Can you check what happens if you load the page again and create new vouchers? I expect it's a bug in the jQuery/javascript part which prevents the new data to be loaded.

**Comment by DokuKaefer** [comment]
Ok when i reload the page after create a voucher role the problem is gone!

**Comment by AdSchellevis** [comment]
ok, found the issue, forgot to remove the previous object.
