### ISSUE TITLE
Missing SSH host key algorithms in configuration dropdown

### ISSUE THREAD

**Issue by pjht** [opnsense/core#7282]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

The `rsa-sha2-256` and `rsa-sha2-512` host key algorithms are missing in the configuration dropdown, along with their certificate counterparts (`rsa-sha2-256-cert-v01@openssh.com` and `rsa-sha2-512-cert-v01@openssh.com`).

**To Reproduce**

1. Go to `System -> Administration`
2. Scroll to the `Secure Shell` section
3. Click on the `Host key algorithms` dropdown
4. Note the lack of the SHA2 RSA host key algorithms.

**Expected behavior**

The SHA2 RSA host key algorithms would be present.

**Describe alternatives you considered**

Manually putting the key algorithms in the generated file located at /usr/local/etc/ssh/sshd_config,
though this did not seem to work and even if it did would often be overwritten.

**Screenshots**

![screenshot_2024-02-26T10:02:45](https://github.com/opnsense/core/assets/4466438/6c40cc15-8cc6-43a6-944c-9aa6a6404a2b)

**Comment by fichtner** [comment]
Weren’t these removed for security reasons by OpenSSH?

**Comment by pjht** [comment]
That was the ssh-rsa key type, though it's still there, you can even see it in the screenshot I gave. It uses the insecure SHA1 instead of the missing ones that use the newer SHA2. The missing ones are actually default unless you change from the listed types, so definitely not removed.

**Comment by fichtner** [comment]
Appears to be related to https://security.stackexchange.com/questions/255074/why-are-rsa-sha2-512-and-rsa-sha2-256-supported-but-not-reported-by-ssh-q-key then

**Comment by fichtner** [comment]
Ok so you made me look and I'm here to tell  you rsa-sha2-256 / rsa-sha2-512 are signatures, not keys.

**Comment by pjht** [comment]
True, but let me quote the `sshd_config(5)` man page to explain things:
```
HostKeyAlgorithms
Specifies the host key signature algorithms that the client wants to use in order of preference. Alternately if the specified list begins with a ‘+’ character, then the specified signature algorithms will be appended to the default set instead of replacing them. If the specified list begins with a ‘-’ character, then the specified signature algorithms (including wildcards) will be removed from the default set instead of replacing them. If the specified list begins with a ‘^’ character, then the specified signature algorithms will be placed at the head of the default set. 

The default for this option is:
ssh-ed25519-cert-v01@openssh.com,
ecdsa-sha2-nistp256-cert-v01@openssh.com,
ecdsa-sha2-nistp384-cert-v01@openssh.com,
ecdsa-sha2-nistp521-cert-v01@openssh.com,
sk-ssh-ed25519-cert-v01@openssh.com,
sk-ecdsa-sha2-nistp256-cert-v01@openssh.com,
rsa-sha2-512-cert-v01@openssh.com,
rsa-sha2-256-cert-v01@openssh.com,
ssh-ed25519,
ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,
sk-ecdsa-sha2-nistp256@openssh.com,
sk-ssh-ed25519@openssh.com,
rsa-sha2-512,rsa-sha2-256
If hostkeys are known for the destination host then this default is modified to prefer their algorithms.

The list of available signature algorithms may also be obtained using "ssh -Q HostKeyAlgorithms".
```
As the first sentence says, the option isn't about the underlying keys, but instead, the signatures, as you said above. You can also see the sha2 signature types in the default list, so they're definitely valid. Think the issue is that you're using `ssh -Q key` to get the items for `Host key algorithms`, where you should be using what the man page says, `ssh -Q HostKeyAlgorithms`. It's just a mildly misleading field name, as it does at first glance appear to have nothing to do with signature algorithms.
