### ISSUE TITLE
Inaccurate activation of firewall schedule when date range spans month end

### ISSUE THREAD

**Issue by DeltaTangoLima** [opnsense/core#7291]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

I use a pair of firewall rules to manage my daughter's internet curfew:

1. A `pass immediate` rule that matches based on IP address and schedule
2. A `reject immediate` rule that matches based on IP address

The intent is that the schedule defines the days, dates and times that internet is active (rule 1) and rejects all traffic at other times (rule 2).

Until I upgraded to **OPNsense 24.1.2_1** this morning, this was working as intended.

Tonight, my daughter's internet was active past the expected time. Turning on logging and trying different things, I found that a particular date range that spanned the end of the month (for school term holidays later this month) was causing the firewall schedule to be active at the wrong time.

Upon further testing I found that if a single date range spans the end of month, and into the next month, but covering the same *date of month* as the current one, the schedule still matches.

For example, today is March 3rd. If I have a date range that spans from later in March into April, including the 3rd of April, the schedule is incorrectly activated.

If I create two separate date ranges, for the relevant dates in each month, the rule is correctly inactive.

**To Reproduce**

1. Go to `Firewall | Settings | Schedules`
2. Create a schedule that spans end/start of month, and covers the same date in next month as today's date (but **DOES NOT** include today's actual date/month)
3. Observe on Schedules screen that schedule is active
4. Edit schedule and remove today's date from next month's range
5. Observe on Schedules screen that schedule is inactive

**Expected behavior**

Schedules should respect contiguous date ranges that span end of month, and not confuse date of month in the wrong month itself.

**Screenshots**

1. Incorrectly active
2. Correctly inactive
3. Inactive when using two separate ranges
4. Current date/times of testing

<img width="920" alt="active" src="https://github.com/opnsense/core/assets/53992354/37955441-9c45-49e4-b764-55f6ab11d6d3">

<img width="921" alt="inactive" src="https://github.com/opnsense/core/assets/53992354/aa4b0ef1-9f95-469f-8b09-9f385012219d">

<img width="866" alt="separate_date_ranges" src="https://github.com/opnsense/core/assets/53992354/961c25ab-e443-4f8c-8938-7002bb77e760">

<img width="579" alt="dashboard" src="https://github.com/opnsense/core/assets/53992354/b8a0c013-2cd5-4406-9de6-37ec41ea870f">

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 24.1.2_1-amd64
Intel(R) Xeon(R) CPU E5540 @ 2.53GHz (4 cores, 4 threads)

**Comment by AdSchellevis** [comment]
I was hoping to never touch this code again (ancient cruft), but since you made the effort to create the ticket, I've fixed this in https://github.com/opnsense/core/commit/8623a2d4aea671a97891fe7582381d0dd96cd5ce and simplified the code underneath for better readability.

**Comment by DeltaTangoLima** [comment]
Thanks for this - glad I could help you clean up ancient code :)

What's the best way for me to test this? I can see it's been added to the plan for 24.7 - should I just wait for that? Running under Proxmox, so rollback using snapshots is easily achieved if required.

**Comment by fichtner** [comment]
As simple as running:

    # opnsense-patch 8623a2d


Cheers,
Franco

**Comment by DeltaTangoLima** [comment]
Fantastic - thanks. Will try it out tonight. Cheers.
