### ISSUE TITLE
Fix setting pipe type in shaper settings.

### ISSUE THREAD

**Issue by chrcoluk** [opnsense/core#7296]
Currently OPNsense has the scheduler type on the pipe configuration line, with no way of setting a type for the pipe itself.  Instead it is always set to droptail.

There is CodeL and Pie tickboxes in the pipe configuration screen but these do nothing, likely because OPNsense is appending scheduler settings to the end of the pipe line instead of its own sched line in /usr/local/etc/ipfw.rules.

OPNsense 24.1.2_1 (amd64).

**Comment by chrcoluk** [comment]
UI url is https://88.198.64.155:444/ui/trafficshaper#pipes, to repeat simply make a pipe, and can verify with 'ipfw pipe show' also examine incorrect syntax in /usr/local/etc/ipfw.rules.

**Comment by bryanwieg** [comment]
After a bit of rabbit hole, chatgpt found this bug impacting my implementation, and even sourced this github issue.

So, yes, FIFO is the only working pipe right now.
