### ISSUE TITLE
Bug: Special characters in Voucher Groupname, cannot delete role

### ISSUE THREAD

**Issue by DokuKaefer** [opnsense/core#730]
When i generate voucher role with special characters i cannot delete the role group.
Only the codes are deleted.

![voucher_groupname](https://cloud.githubusercontent.com/assets/11537653/12704311/8934af76-c858-11e5-9924-e7ff1fe0feed.png)

**Comment by AdSchellevis** [comment]
The voucher group name is used in the URL, so some characters may not be used. I will include some cleansing on the input data when generating the vouchers.
