### ISSUE TITLE
OpenVPN: non working TAP server mode, using wrong configuration directives

### ISSUE THREAD

**Issue by muchachagrande** [opnsense/core#7302]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [ x ] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [ x ] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

Using the new OpenVPN instances I'm not being able to get a working bridged VPN (TAP).
I'm moving OpenVPN servers from the legacy configs to the new instances approach on several routers I manage.
As of now I could successfully migrate some routed VPNs with client overrides, but when I define a bridged VPN I found a problem in the generated configuration.
The problem is that the configuration key "server-bridge" is not being used and it is needed for a bridged VPN to function. The configuration fields for defining the bridge are also missing on the web page. If you take a look at the legacy configuration page you can see the the "bridge interface" option and the DHCP range for the IP assignments of the clients.
Instead of the "server-bridge" directive, the "server" directive is being used as in the routed VPNs and it is also adding the "topology" configuration that is useless on bridged type VPNs. Additionally, if I don't set the Server network field the daemon will not even start because it generates an invalid configuration.
In the OpenVPN manual https://openvpn.net/community-resources/reference-manual-for-openvpn-2-6/ it says that "server" key is used for configuring a routed VPN and "server-bridge" for an ethernet bridged one.
Another directive that is missing, is the "tls-server" key.

**To Reproduce**

1. Go to 'OpenVPN Instances'
2. Click on '+' sign to add a new Instance
3. Select the 'advanced mode'
4. Change type to 'tap'
5. Configure the rest of the parameters

**Expected behavior**

The bridged VPN daemon should start and wait for connections.

**Describe alternatives you considered**

No alternatives

**Screenshots**

I've rearranged a legacy configuration to compare it side-by-side with a new instance config of a TAP VPN.
In the new instance (right) I had to fill the Server (IPv4) only for the purpose of getting a full configuration.
The left pane shows the old working TAP VPN and the right pane the new non-working instance:

![Captura desde 2024-03-06 12-49-36](https://github.com/opnsense/core/assets/20299175/82b9fa85-c764-4794-815e-80eae5cc79f7)

Left pane: Working old TAP config
Right pane: Incorrect "topology" and "server" directives used and missing "server-bridge" and "tls-server" directives

**Relevant log files**

When you create a TAP VPN without the server directive you get this log:

> 2024-03-06T14:07:47-03:00	Error	openvpn	/usr/local/opnsense/scripts/openvpn/ovpn_service_control.php: The command '/usr/local/sbin/openvpn --config '/var/etc/openvpn/instance-d3b43d35-7f44-43a9-b186-b29743414c61.conf'' returned exit code '1', the output was ''	 
> 2024-03-06T14:07:47-03:00	Warning	openvpn_server2	Use --help for more information.	 
> 2024-03-06T14:07:47-03:00	Error	openvpn_server2	Options error: --verify-client-cert requires --mode server	 
> 2024-03-06T14:07:47-03:00	Warning	openvpn_server2	WARNING: Ignoring option 'dh' in tls-client mode, please only include this in your server configuration

**Additional context**

None

**Environment**

OPNsense 24.1.3 (amd64). (Virtualized with ESXi 7)
Intel® Core™ I7-10700 2.9Ghz (4 vCores)
2 x Network Intel® E1000 (virtualized)

**Comment by AdSchellevis** [comment]
I'm not sure about the bridge helper with dhcp to be honest as in theory you should also be able to start a dhcp server already available on the machine (isc-dhcp or kea). We do seem to miss `mode server` and `tls-server` when selecting `tap` mode, which is what https://github.com/opnsense/core/commit/3d09a2cb609a2ec234877f42f6dd293c5314f5c0 should solve.

**Comment by muchachagrande** [comment]
Hi, @AdSchellevis.

I've tested the path and the daemon fails to start.

> 2024-03-06T17:38:01-03:00	Error	openvpn	/usr/local/opnsense/scripts/openvpn/ovpn_service_control.php: The command '/usr/local/sbin/openvpn --config '/var/etc/openvpn/instance-d3b43d35-7f44-43a9-b186-b29743414c61.conf'' returned exit code '1', the output was ''	 
> 2024-03-06T17:38:01-03:00	Warning	openvpn_server2	Use --help for more information.	 
> 2024-03-06T17:38:01-03:00	Error	openvpn_server2	Options error: --verify-client-cert none|optional must be used with --management-client-auth, an --auth-user-pass-verify script, or plugin	 
> 2024-03-06T17:38:01-03:00	Notice	openvpn_server2	Note: --cipher is not set. OpenVPN versions before 2.5 defaulted to BF-CBC as fallback when cipher negotiation failed in this case. If you need this fallback please add '--data-ciphers-fallback BF-CBC' to your configuration and/or add BF-CBC to --data-ciphers.

Now I can see the the "mode server" and "tls-server" directives and the "server" directive is absent, but I think it is still missing the "server-bridge" directive. If you use "server-bridge" without parameters, it is supposed to use the DHCP server of the bridged LAN as you stated before.

Also I see that some other directives are gone: "auth-user-pass-verify", "learn-address", "client-disconnect" and "tls-verify". I don't think this is right.

Left pane; config before patch
Right pane: config after patch

![Captura desde 2024-03-06 17-43-33](https://github.com/opnsense/core/assets/20299175/303b351a-6f0d-44d8-94fa-2492c3314ef3)

And "topology" directive is still there, may be it is not a problem if it is not used anyway.

**Comment by AdSchellevis** [comment]
it shouldn't need the `server-bridge`, this is your problem:

> error openvpn_server2 Options error: --verify-client-cert none|optional must be used with --management-client-auth, an --auth-user-pass-verify script, or plugin

according to the documentation, `server-bridge` on non windows platforms only make sense when adding a pool, but running a dhcp server should do the same in my opinion (server did start on my end, but with slightly different settings).

**Comment by muchachagrande** [comment]
Well, I corrected the problem with "verify-client-cert" and now I can connect. But I've fallen into another problem:

> 2024-03-06 19:30:22 OpenVPN 2.5.3 x86_64-w64-mingw32 [SSL (OpenSSL)] [LZO] [LZ4] [PKCS11] [AEAD] built on Jun 17 2021
> 2024-03-06 19:30:22 Windows version 6.1 (Windows 7) 64bit
> 2024-03-06 19:30:22 library versions: OpenSSL 1.1.1k  25 Mar 2021, LZO 2.10
> 2024-03-06 19:30:27 WARNING: No server certificate verification method has been enabled.  See http://openvpn.net/howto.html#mitm for more info.
> 2024-03-06 19:30:27 TCP/UDP: Preserving recently used remote address: [AF_INET]w.x.y.z:1196
> 2024-03-06 19:30:27 UDP link local (bound): [AF_INET][undef]:0
> 2024-03-06 19:30:27 UDP link remote: [AF_INET]w.x.y.z:1196
> 2024-03-06 19:30:28 WARNING: 'tun-mtu' is used inconsistently, local='tun-mtu 1532', remote='tun-mtu 1500'
> 2024-03-06 19:30:28 [router.svrcom.com.ar] Peer Connection Initiated with [AF_INET]w.x.y.z:1196
> 2024-03-06 19:30:28 OpenVPN ROUTE: OpenVPN needs a gateway parameter for a --route option and no default was specified by either --route-gateway or --ifconfig options
> 2024-03-06 19:30:28 OpenVPN ROUTE: failed to parse/resolve route for host/network: 192.168.99.0
> 2024-03-06 19:30:28 OpenVPN ROUTE: OpenVPN needs a gateway parameter for a --route option and no default was specified by either --route-gateway or --ifconfig options
> 2024-03-06 19:30:28 OpenVPN ROUTE: failed to parse/resolve route for host/network: 192.168.2.0
> 2024-03-06 19:30:28 OpenVPN ROUTE: OpenVPN needs a gateway parameter for a --route option and no default was specified by either --route-gateway or --ifconfig options
> 2024-03-06 19:30:28 OpenVPN ROUTE: failed to parse/resolve route for host/network: 192.168.1.0
> 2024-03-06 19:30:28 open_tun
> 2024-03-06 19:30:28 tap-windows6 device [OpenVPN TAP-Windows6] opened
> 2024-03-06 19:30:28 Successful ARP Flush on interface [13] {2CDCC32D-356B-4B07-8CAA-8C7239C5947F}
> 2024-03-06 19:30:33 Initialization Sequence Completed

The pushed routes do not have a gateway. I think that a is needed a push "route-gateway <ip address>" or push "route-gateway dhcp" in the server configuration.

**Comment by AdSchellevis** [comment]
If I'm not mistaken, you either need a client specific overwrite to push the gateway to the client or add it to the client configuration in this case.

I would like to prevent adding a bridge dhcp pool to the mix, but if there's anything missing to offer a functional tap, I don't mind taking a look. Trying a legacy config without a pool might help to explain the differences by the way.

**Comment by muchachagrande** [comment]
Hi @AdSchellevis. Thank you for taking the time on this issue.

I made various tests with the TAP Instance and this is what I've got:

It is not necessary to add a bridge pool to de configuration, it is working with the DHCP of the bridged interface, in my case the vlan 2 at IP 192.168.2.1. So the "server-bridge" directive is not necessary at all.

If I push routes via Routing->Local Networks option, the client complains at start because it doesn't have a gateway for those routes so I tested with "route-gateway" directive in the client configuration with the vlan2 IP (route-gateway 192.168.2.1) and it connected without complains. Then the routing table showed the accessible network and I could ping them.

Then I manage to test pushing the "route-gatway 192.168.2.1" from the server modifying the Instance configuration and initiating it from the shell and it worked fine, so using route-gateway on the client or pushing it from the server produces the same result.

Then I tested pushing the routes but from a client override, and it didn't work. The Local Networks must be on the Instance config. This is estrange because I should be capable of setting different routes for different users. May be related to the missing "client-config-dir" directive on the Instance configuration when using TAP ??

So, from I could see on the tests, the "route-gateway" directive is needed somewhere, pushing it from the instance or directly in the client or presumably pushing it from the client override.

May be a "Route Gateway" input box could be added to the instance configuration under Routing or Miscellaneous only visible when you select server-TAP mode to enter the IP of the bridged interface that will play as gateway for the pushed routes.

**Comment by AdSchellevis** [comment]
> Then I tested pushing the routes but from a client override, and it didn't work. The Local Networks must be on the Instance config. This is estrange because I should be capable of setting different routes for different users. May be related to the missing "client-config-dir" directive on the Instance configuration when using TAP ??

That's something I can check, if that works, that would be my preferred solution.

>May be a "Route Gateway" input box could be added to the instance configuration under Routing or Miscellaneous only visible when you select server-TAP mode to enter the IP of the bridged interface that will play as gateway for the pushed routes.

When we can't get option 1 to function as expected, that will probably be the alternative.

**Comment by AdSchellevis** [comment]
@muchachagrande https://github.com/opnsense/core/commit/46354f486ccc882593eb20351ba82ab280f5b3ad should add the `client-config-dir` for tap

**Comment by muchachagrande** [comment]
I found another problem. All previous tests were made on Windows client but I'm testing on Linux client and it doen't work.

> sudo openvpn --config TAP_VPN_fjm.ovpn

> 2024-03-07 14:27:17 --cipher is not set. Previous OpenVPN version defaulted to BF-CBC as fallback when cipher negotiation failed in this case. If you need this fallback please add '--data-ciphers-fallback BF-CBC' to your configuration and/or add BF-CBC to --data-ciphers.
> 2024-03-07 14:27:17 OpenVPN 2.5.9 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Sep 29 2023
> 2024-03-07 14:27:17 library versions: OpenSSL 3.0.2 15 Mar 2022, LZO 2.10

> Enter Auth Username: fjm
> Enter Auth Password: ********                

> 2024-03-07 14:27:24 WARNING: No server certificate verification method has been enabled.  See http://openvpn.net/howto.html#mitm for more info.
> 2024-03-07 14:27:24 TCP/UDP: Preserving recently used remote address: [AF_INET]192.168.100.221:1196
> 2024-03-07 14:27:24 UDP link local (bound): [AF_INET][undef]:0
> 2024-03-07 14:27:24 UDP link remote: [AF_INET]192.168.100.221:1196
> 2024-03-07 14:27:24 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
> 2024-03-07 14:27:24 WARNING: 'tun-mtu' is used inconsistently, local='tun-mtu 1532', remote='tun-mtu 1500'
> 2024-03-07 14:27:24 [router.svrcom.com.ar] Peer Connection Initiated with [AF_INET]192.168.100.221:1196
> 2024-03-07 14:27:24 TUN/TAP device tap0 opened
> 2024-03-07 14:27:24 WARNING: OpenVPN was configured to add an IPv4 route. However, no IPv4 has been configured for tap0, therefore the route installation may fail or may not work as expected.
> 2024-03-07 14:27:24 sitnl_send: rtnl: generic error (-101): Network is unreachable
> 2024-03-07 14:27:24 ERROR: Linux route add command failed
> 2024-03-07 14:27:24 sitnl_send: rtnl: generic error (-101): Network is unreachable
> 2024-03-07 14:27:24 ERROR: Linux route add command failed
> 2024-03-07 14:27:24 sitnl_send: rtnl: generic error (-101): Network is unreachable
> 2024-03-07 14:27:24 ERROR: Linux route add command failed
> 2024-03-07 14:27:24 Initialization Sequence Completed

I'm testing what's wrong here.

**Comment by muchachagrande** [comment]
@AdSchellevis, I will test the patch to use the client overrides but the successful tests I made using Windows client don't work on Linux client. Quoting the manual:

> If --server-bridge is used without any parameters, it will enable a DHCP-proxy mode, where connecting OpenVPN clients will receive an IP address for their TAP adapter from the DHCP server running on the OpenVPN server-side LAN. Note that only clients that support the binding of a DHCP client with the TAP adapter (such as Windows) can support this mode.

Only the Windows TAP adapter support the DHCP proxy mode. I'm afraid that the "server-bridge" directive must be used to assign an IP address to Linux TAP adapter.

I made a test modifying the TAP instance to use "server-bridge" directive and Linux connected fine.

**Comment by muchachagrande** [comment]
> @muchachagrande [46354f4](https://github.com/opnsense/core/commit/46354f486ccc882593eb20351ba82ab280f5b3ad) should add the `client-config-dir` for tap

I've tested the client overrides patch and now I can use the "Local Network" option on a per client basis but it didn't fix the route-gateway problem. If I don't add "route-gateway 192.168.2.1" in the client config the routes will not work, just as it happened before pushing the routes from the instance. So in that regard, the issue remains.

**Comment by AdSchellevis** [comment]
@muchachagrande thanks for testing, I'll see if I can add the `server-bridge` option in that case.

**Comment by AdSchellevis** [comment]
@muchachagrande this https://github.com/opnsense/core/commit/ac4bbb359f72ce4523fc4b516ebad89a002a5042 should be the last parts to allow the optional gateway+pool setting as well.

**Comment by muchachagrande** [comment]
Hi @AdSchellevis. Tried to patch with the following result:

> Fetched ac4bbb3 via https://github.com/opnsense/core
3 out of 4 hunks failed while patching opnsense/mvc/app/models/OPNsense/OpenVPN/OpenVPN.php

Do I have to undo some of the previous patches?

**Comment by AdSchellevis** [comment]
@muchachagrande the list has grown a bit with all the modifications, I expect this will work better:
```
opnsense-revert opnsense
opnsense-patch 3d09a2c 59ce2706 46354f48 ac4bbb
```

**Comment by muchachagrande** [comment]
@AdSchellevis, thank you for your time. I've tested the VPN with Windows and Ubuntu clients and is working fine. With this I can migrate all my VPNs to new instances.

**Comment by AdSchellevis** [comment]
@muchachagrande thanks for testing, we'll try to add this to a minor release.

**Comment by muchachagrande** [comment]
It would be great as I've already erased my old VPN :smile:

**Comment by phloggu** [comment]
I had perfectly working OpenVPN connections set up with OPNSense 24.1 all using TAP interfaces. With the Upgrade to 24.1.5 all these connections ceased to work. The error displayed  (on Linux OpenVPN client 2.5.1) is:
`2024-04-21 16:30:30 OpenVPN ROUTE: failed to parse/resolve route for host/network: 10.70.0.0`
The connection gets established, but there is no IP given to the client. I do not see anything special in the server log.

When I check the WebGUI of OPNSense under OpenVPN/Instances the server address and subnet I defined for VPN  clients connecting to that instance disappeared. Switching to TUN mode those addresses resp. subnet definition appear again.

Meanwhile on 24.1.6, I am not able to reconfigure the VPN instances in a way the clients can do TAP connections. One reason is, I can't figure out, what to enter in the field "Bridge DHCP pool".  The help text says it should contain an ip range, but neither <ip>-<ip> (or using colon, semicolon or space instead of a dash as a separator) is accepted. The WebGUI corrects entries in this field to 

Additional information:
I can't remember from what version I updated to 24.1.5, it must have been 24.1.2, I guess. The VPN stopped working just after the upgrade, I was connected by VPN doing the upgrade and tried to reconnect after the reboot, which did not work.

Summary:
- I would like to give a hint that TAP mode connections were working and for me stopped doing so.
- I would like to know how I have to enter the IP range in the field "Bridge DHCP pool".

**Comment by muchachagrande** [comment]
Hi @phloggu, in response to your second question in the summary, the "Bridge DHCP pool" field should have an IP range in the form [from IP]-[to IP]. Just that.
Regarding your first statement, you have not provided the configuration you had working so that someone can help you.
Right now the OpenVPN TAP new instances are working just as the legacy ones. The generated configurations are almost identical on new and legacy definitions. I have various working fine.

This kind of questions can be better answered in the forum https://forum.opnsense.org/index.php?board=45.0
Please create an issue report there providing your configuration, wether you are using the legacy or the new instance config and so on.
