### ISSUE TITLE
WireGuard Peers Page - Add commands for downloading the config and generate a QR code

### ISSUE THREAD

**Issue by mhlas7** [opnsense/core#7308]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**

The most annoying part about creating new WireGuard peers is having to manually populate a config file for each peer and then generate a QR code to transfer the config to a mobile device.

**Describe the solution you like**

I would like a button under the `Commands` column to download a WireGuard config file for each peer with all of the config fields populated.

Additionally, another button should be added in the `Commands` column which would generate a QR code of the config file. QR codes are used to transfer WireGuard configs to a mobile device. The QR code could be displayed in a popup window.

**Additional context**

`wg-easy` is a great example of how this user interface could be implemented: https://github.com/wg-easy/wg-easy

**Comment by AdSchellevis** [comment]
https://github.com/opnsense/core/commit/13b685a0a792e686116e92a0bd5cb0429a9bf838 adds a config builder to generate peers, as we do not store private keys (not should we), we can not generate these from existing entries. Below a screenshot from the feature in this commit:

<img width="1413" alt="image" src="https://github.com/opnsense/core/assets/9783985/3960b9d9-5c66-4662-bbea-a6ad83601001">

**Comment by mimugmail** [comment]
This looks nice :)

**Comment by mhlas7** [comment]
This looks great! This will make building configs for a lot of users much easier!

I made one small comment on your commit with what looks like a typo.

**Comment by AdSchellevis** [comment]
@mhlas7 I just noticed the typo, fixed in https://github.com/opnsense/core/commit/550dacfe929d4f0f51b484ff30f9c9b1667133d6. The server/client comment isn't entirely true, both of these parameters are for the client (peer), the instance (peer) ships the public key stored in the config under peer (remote peer, this instance)
