### ISSUE TITLE
Prevent last interface assignment from being removed

### ISSUE THREAD

**Issue by Monviech** [opnsense/core#7317]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**

Right now it is possible to delete all interface assigments in the GUI. Since its applied instantly during each delete, you can totally lock yourself out if you are playing around.

Rebooting doesn't help, since FreeBSD will refuse to boot with the error message that there are currently no assigned interfaces, leaving you with a soft bricked firewall. (Reinstall can fix that though).

**Describe the solution you like**

Refusing to delete the last assigned interface with a clear error message could mitigate this user error.

**Describe alternatives you considered**

Not being as stupid as me and try to find out what happens if you delete all interface assigments. xD I was especially surprised not even a reboot can fix this, since I wasnt able to even get to the interface wizard via serial.

**Additional context**

This happened on 23.7.12

**Comment by fichtner** [comment]
This is more or less a feature. You can and should lock your interfaces from the settings to prevent this (no delete button then). Technically there is nothing wrong with a no-interface boot.

Also we don’t know what the user intends… could want to start from scratch too and this would be the next bug report.

**Comment by Monviech** [comment]
Hehe understood, I just came across this and thought I would write it here. I understand why to lock interfaces down. Thanks for your quick reply and hope you have a nice weekend. ^^
