### ISSUE TITLE
OpenVPN: Instances [new] - Redirect gateway (still) broken - Outbound NAT issue

### ISSUE THREAD

**Issue by cektom** [opnsense/core#7318]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

In the new OpenVPN Instances section, redirect-gateway doesn't work. Neither via the Instances config - Miscellaneous - Redirect gateway - default nor directly via OpenVPN config file `redirect-gateway def1`
This means that ping is only possible to other internal Nets (e.g. LAN) but not to the internet.

This did work with the legacy config. It would be nice if the manual outbound NAT rule could be generated automatically again.

**To Reproduce**

1. Go to 'OpenVPN: Instances [new]'
2. Edit your server and set Redirect gateway to default or edit the OpenVPN config file and add the line `redirect-gateway def1`
3. Connect to your server with the OpenVPN client
4. Ping to internet (e.g. 8.8.8.8)

**Expected behavior**

Successful ping via WAN to internet

**Describe alternatives you considered**

According to this issue [https://github.com/opnsense/core/issues/6733](https://github.com/opnsense/core/issues/6733) and this forum post [https://forum.opnsense.org/index.php?topic=36045.0](https://forum.opnsense.org/index.php?topic=36045.0) you have to manually create an NAT outbound rule. (You have to set NAT Mode to at least Hybrid outbound NAT rule generation)

**Screenshots**
![image](https://github.com/opnsense/core/assets/96428856/330671c1-e8dc-473c-8527-9311d67442a2)

**Environment**

OPNsense 24.1.2_1-amd64
FreeBSD 13.2-RELEASE-p10
OpenSSL 3.0.13

**Comment by cektom** [comment]
@AdSchellevis Hi Ad, if this isn't going to be fixed [https://github.com/opnsense/core/issues/6733#issuecomment-1674260625](https://github.com/opnsense/core/issues/6733#issuecomment-1674260625), it would be nice to add this to the documentation.

**Comment by AdSchellevis** [comment]
@cektom not sure what you want to add, but feel free to open a pull request at https://github.com/opnsense/docs

**Comment by allanonmage** [comment]
I am running into this issue, and the workaround does not seem to be working for me, although I'm only 90% sure I implemented it correctly.
