### ISSUE TITLE
I can no longer create vouchers without a password.

### ISSUE THREAD

**Issue by Loughty** [opnsense/core#7319]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

I can no longer create vouchers without a password, I haven't created vouchers for a while, but I'm sure that at least in 23.1 it let me do it.

Is it safe to revert? even if it's to a previous major update? If this has to do with a recent minor update, could you tell me which one to revert to a version before that?

**To Reproduce**

1. Go to '/ui/captiveportal/voucher'
2. Click on 'Create vouchers'
3. Click on 'Generate'
4. Open the CSV to see that your vouchers now are create with a random one letter password.

Also:
1. Go to '/system_authservers.php?act=new'
2. Select type 'Vouchers'
3. Put on Password length '0'
4. Now gives you the error "Password length must be a number or empty for default".

**Expected behavior**

Create vouchers without a password.

**Describe alternatives you considered**

I would like to use an external voucher server to prevent more problems in the future, because once it happened to me that when I restored a configuration after a fresh install, all the vouchers that I create were not restored. Having an external server that takes care of this would save me headaches, I think that with RADIUS you can create vouchers, but I'm not sure if it lets you create them without a password, if someone can confirm that would be great, can use FreeRADIUS for that?

**Screenshots**

Error when I want to create a new voucher server without password.
![Captura desde 2024-03-11 12-36-48](https://github.com/opnsense/core/assets/52808915/31564849-ed52-4f46-bd30-9774b61f2159)

The vouchers that are create now when I try to use my old voucher server that don't have password.
![Captura desde 2024-03-11 12-52-25](https://github.com/opnsense/core/assets/52808915/28022d19-d669-4f71-acd9-4d59de3b4997)

**Additional context**

All the old vouchers are (still) working.

**Environment**

OPNsense 24.1.3_1-amd64

**Comment by AdSchellevis** [comment]
this was introduced with https://github.com/opnsense/core/issues/7105 , but for some reason I have the feeling reverting the patch will cause an endless loop.

**Comment by AdSchellevis** [comment]
https://github.com/opnsense/core/commit/5b92fef5942352b00ca2f93e219e2c61d9ebd16c should do the trick

**Comment by Loughty** [comment]
Wow, that was fast! Thank you so much!

I guess I have to wait for the next update to see and try =D

**Comment by AdSchellevis** [comment]
`opnsense-patch 5b92fef`  should do the trick
