### ISSUE TITLE
Gateway weight "Invalid integer value."

### ISSUE THREAD

**Issue by FloMiau** [opnsense/core#7321]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**
I'm setting up multi WAN with load balancing. I want to give my fiber connection about 90% of the traffic and the other 10% should go to the other connection.

**To Reproduce**

1. Go to System -> Gateways -> Configuration (ui/routing/configuration)
2. Edit gateway
3. Set weight on the main connection to 9
4. Saving is not possible with the text "Invalid integer value." - see screenshot below

**Expected behavior**

No error on 4.

**Screenshots**

![grafik](https://github.com/opnsense/core/assets/37121807/bf19de0c-dbb8-4f26-9c72-6b6cb654af9e)

**Additional context**

I think this is about this lines of code https://github.com/opnsense/core/blob/master/src/opnsense/mvc/app/models/OPNsense/Routing/Gateways.xml#L74-L79

There should be a better text than "invalid integer value" when setting this option. Also I'm wondering why this is limited 5.

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 24.1.3_1

**Comment by AdSchellevis** [comment]
help text seems to be incomplete, the max is set to 5 https://github.com/opnsense/core/blob/8010030d10b269bd123d0ad8fc399e41fe807ff3/src/opnsense/mvc/app/models/OPNsense/Routing/Gateways.xml#L78

in the old version it was a select box, which had its max set to 5 as well

https://github.com/opnsense/core/blob/847d88416f58b80c31d112a39112520f3d3c28a0/src/www/system_gateways_edit.php#L624-L640

Increasing the number to a higher value usually doesn't hold much value and increases the risk of issues as these are expanded to additional `route-to` clauses.
