### ISSUE TITLE
Attempting to change the web GUI TCP port results in the following text on a white screen upon clicking "Save"

### ISSUE THREAD

**Issue by sshanky** [opnsense/core#7323]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [ ] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [ ] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

Attempting to change the web GUI TCP port results in the following text on a white screen upon clicking "Save":

`Fatal error: Uncaught TypeError: Cannot access offset of type string on string in /usr/local/www/system_advanced_admin.php:175 Stack trace: #0 {main} thrown in /usr/local/www/system_advanced_admin.php on line 175
`
*Tip*: to validate your setup was working with the previous version, use opnsense-revert (https://docs.opnsense.org/manual/opnsense_tools.html#opnsense-revert)

**To Reproduce**

**Expected behavior**

Wanted to change the GUI TCP port

**Describe alternatives you considered**

A clear and concise description of any alternative solutions or workaround you considered.

**Screenshots**

**Relevant log files**

If applicable, information from log files supporting your claim.

**Additional context**

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 24.7.a_184-amd64
FreeBSD 13.2-RELEASE-p10
OpenSSL 3.0.13
QEMU Virtual CPU version 2.5+ (4 cores, 4 threads)

**Comment by sshanky** [comment]
```
root@OPNsense:~ # awk 'NR < 170{next}1;NR==180{exit}' /usr/local/www/system_advanced_admin.php
        $config['system']['webgui']['port'] = $pconfig['webguiport'];
        $config['system']['webgui']['ssl-certref'] = $pconfig['ssl-certref'];
        $config['system']['webgui']['ssl-ciphers'] = $newciphers;
        $config['system']['webgui']['interfaces'] = $newinterfaces;
        $config['system']['webgui']['compression'] = $pconfig['compression'];
        $config['syslog']['nologlighttpd'] = empty($pconfig['loglighttpd']);

        if (!empty($pconfig['deployment'])) {
            $config['system']['deployment'] = $pconfig['deployment'];
        } elseif (isset($config['system']['deployment'])) {
            unset($config['system']['deployment']);
```

**Comment by AdSchellevis** [comment]
It's a wild guess, but can you try?

```
opnsense-patch 3111a05
```

**Comment by sshanky** [comment]
Nice guess! That fixed it.

```
root@OPNsense:~ # opnsense-patch 022ab7a
Fetched 022ab7a via https://github.com/opnsense/core
Hmm...  Looks like a unified diff to me...
The text leading up to this was:
--------------------------
|From 022ab7ad75a994eb92d8e923ba904e033c593392 Mon Sep 17 00:00:00 2001
|From: Ad Schellevis <ad@opnsense.org>
|Date: Wed, 13 Mar 2024 08:42:45 +0100
|Subject: [PATCH] System: Settings: Administration - possible issue when syslog
| container doesn't exist in the config. closes
| https://github.com/opnsense/core/issues/7323
|
|---
| src/www/system_advanced_admin.php | 7 ++++---
| 1 file changed, 4 insertions(+), 3 deletions(-)
|
|diff --git a/src/www/system_advanced_admin.php b/src/www/system_advanced_admin.php
|index b12eb8f6c4..ae14a3c286 100644
|--- a/src/www/system_advanced_admin.php
|+++ b/src/www/system_advanced_admin.php
--------------------------
Patching file www/system_advanced_admin.php using Plan A...
Hunk #1 succeeded at 79.
Hunk #2 succeeded at 152.
Hunk #3 succeeded at 165.
Hunk #4 succeeded at 173.
done
All patches have been applied successfully.  Have a nice day.
```
