### ISSUE TITLE
Unbound not resolving some keystonecollects.com subdomains until restart

### ISSUE THREAD

**Issue by HarlemSquirrel** [opnsense/core#7329]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [ x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [ x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

So far I've only noticed this issue with the following subdomains:

- www.keystonecollects.com
- newmy.keystonecollects.com

*Tip*: to validate your setup was working with the previous version, use opnsense-revert (https://docs.opnsense.org/manual/opnsense_tools.html#opnsense-revert)

**To Reproduce**

1. Run `nslookup www.keystonecollects.com`
2. See `** server can't find www.keystonecollects.com: NXDOMAIN`
3. Run `nslookup www.keystonecollects.com 1.1.1.1`
4. See resolution
```
Non-authoritative answer:
Name:	www.keystonecollects.com
Address: 162.159.135.42
** server can't find www.keystonecollects.com: SERVFAIL
```

Sometimes restarting fixes the issue and sometimes it does not.

Adding query forwarding entries for these two domains to forward to 1.1.1.1 allows these domains to resolve correctly.

**Expected behavior**

No restart should be required

**Describe alternatives you considered**

A clear and concise description of any alternative solutions or workaround you considered.

**Screenshots**

**Relevant log files**

If applicable, information from log files supporting your claim.

**Additional context**

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 23.7.8 (amd64).
Intel® Xeon™ E3-1225V5 3.3Ghz Quad Core
Network Intel® I210-AT

**Comment by HarlemSquirrel** [comment]
I also found that `efile.keystonecollects.com` is having this issue, too.

@kulikov-a well I just turned off dnssec support and my query forwarding rules, restarted unbound, and two of the three resolved but `www.` did not.

**Comment by kulikov-a** [comment]
> but www. did not

just a negative cache maybe? is it working now?
it looks like another effect of aggressive nsec (https://forum.opnsense.org/index.php?topic=38888.msg191480#msg191480)

**Comment by HarlemSquirrel** [comment]
Haven't noticed any more issues so I guess we can close this.
