### ISSUE TITLE
locking packages not working

### ISSUE THREAD

**Issue by andreas-p** [opnsense/core#733]
I suspected a problem with suricata 3.0, so I locked the package prior to upgrading from 15.7 to 16.1. Unfortunately, after the upgrade I found suricata upgraded as well so I can't pinpoint my problem.

**Comment by fichtner** [comment]
Is the package still displayed as locked?

**Comment by andreas-p** [comment]
No.

**Comment by fichtner** [comment]
Ok, see this for reference :( https://github.com/freebsd/pkg/issues/1344

I'm marking this won't fix but leave the ticket open...

**Comment by fichtner** [comment]
https://github.com/freebsd/pkg/issues/1344

upstream will apparently fix this in the next pkg release

**Comment by fichtner** [comment]
pkg 1.7.2 is coming to 16.1.12 :)
