### ISSUE TITLE
Incorrect firewall statistics

### ISSUE THREAD

**Issue by nt1** [opnsense/core#7332]
The IPv4 packet pass and block statistics are incorrect.  Each is set to the corresponding byte count.  This is also noticeable in the RRD graphs. 

**To Reproduce**

1. Go to Firewall: Diagnostics: Statistics page.
2. Click on the Interfaces tab.
3. Expand the interface that corresponds to your WAN connection (or any other interface that has active rules).  Note that the values of in4_pass_bytes and in4_pass_packets are the same.  This should also be the case for in4_block_bytes and in4_block_packets.
4. ssh in to your device.
5. Get interface statistics for the interface that was inspected in step (3): `sudo pfctl -s Interfaces -vv | grep $INTERFACE -A 10`
6. Packet stats reported by pfctl for in4 pass and block differ form what is in the ui, while byte stats are roughly equivalent to what is in the ui.

**Expected behavior**

Packet stats are correct.

The bug is [here](https://github.com/opnsense/core/blob/15e477393f92767efc19d2d66ca65b953b56ee05/src/opnsense/scripts/filter/pfstatistics.py#L94).  Packet stats are in `parts[2]`.  `parts[4]` contains byte stats.

**Comment by AdSchellevis** [comment]
@nt1 thanks, corrected in https://github.com/opnsense/core/commit/8faa33eebaa4ea1b3ab0b4259e995bc0f858604d
