### ISSUE TITLE
ipv6 track mode's radvd running with incorrect config path

### ISSUE THREAD

**Issue by nergdron** [opnsense/core#7341]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

When setting ipv6 to "track" mode, a correct config is generated for radvd under `/var/etc/radvd.conf`, but the process is run referencing the dummy example `/usr/local/etc/radvd.conf` file, so it never works. switching to static IPv6 mode on my LAN interface instead of track fixes this issue, and it correctly restarts radvd to point at `/var/etc/radvd.conf`, and switching it back correctly keeps the service pointed at the right config, allowing track mode to work.

**To Reproduce**

1. do a fresh opnsense install in an environment with dhcpv6 working on the WAN side.
2. set LAN ipv6 mode to `track`
3. log in to server with ssh, run `ps axf | rg radvd`, and notice it is using the incorrect config file `/usr/local/etc/radvd.conf`
5. switch LAN ipv6 mode to `static` with a valid config, save and apply. then switch it back to `track`, save and apply.
6. log into server with ssh, run `ps axf| rg radvd`, notice it's now using the correct config file `/var/etc/radvd.conf`

**Expected behavior**

I expected radvd to run using the correct config path out of the box.

This is on a fresh install of opnsense as of last week, all updates have been performed. this probably explains why so many people have been having ipv6 issues out of the box, since you have to go through a weird song and dance to get it running with the correct config.

**Describe alternatives you considered**

not sure what workarounds should be needed on a fresh install.

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 24.1.4-amd64
Protectli VP2420
https://ca.protectli.com/product/vp2420/

**Comment by fichtner** [comment]
It’s not our code referencing the wrong file?

**Comment by nergdron** [comment]
not sure what you mean. if I do a fresh install of the OS, tell it to set up ipv6 tracking on my lan interface, and hit apply, then your code should point radvd at the right config file, no? what else should be managing this behaviour?

**Comment by fichtner** [comment]
You’re asking the wrong question. The question is where is the wrong file referenced in our code?

**Comment by nergdron** [comment]
I'm still not sure what you mean. it's your distro, you management interface. if your code isn't setting up radvd to use the correct config file on a fresh install, it's likely your code isn't fully setting up radvd properly. it may not be referencing the wrong config file, but rather leaving it incorrectly as the default value. so it's your code's fault, if it creates a config file at a different place than radvd is expecting, and doesn't tell radvd to look for it there, no?

**Comment by fichtner** [comment]
I think I’m unable to help you at this point. We do not use that wrong config file so it’s likely something you did like a manual rc.conf entry or running the wrong command somewhere in custom scripting.

**Comment by nergdron** [comment]
I literally just did a fresh install on a fresh piece of hardware, so... way to gaslight me a guess. very weird responses all around to a pretty straightforward bug report.

**Comment by fichtner** [comment]
i admire your passion, but you miss my point:

    % git checkout 24.1.4 
    % git grep "/usr/local/etc/radvd.conf"
    % git grep "/var/etc/radvd.conf"      
    src/etc/inc/plugins.inc.d/dhcpd.inc:    $radvd_conf_file = '/var/etc/radvd.conf';
    src/etc/inc/plugins.inc.d/dhcpd.inc:            mwexec('/usr/local/sbin/radvd -p /var/run/radvd.pid -C /var/etc/radvd.conf -m syslog');

As you can see we're not configuring the wrong path from our code. I've tried to tell you that. If you want to call it gaslighting that's fine but at the end of the day it's just a community support effort not being appreciated.

And now instead of gaslighting let me "mansplain" the issue.. There is another file /usr/local/etc/rc.d/radvd which does reference the wrong file, but the only way to load the wrong configuration is by doing:

    # service radvd onerestart
    Stopping radvd.
    Waiting for PIDS: 61104.
    Starting radvd.
    # ps aux | grep radvd
    root    24361   0.0  0.0  12696   2452  -  Ss   08:59       0:00.00 /usr/local/sbin/radvd -p /var/run/radvd.pid -C /usr/local/etc/radvd.conf

But again, our code IS NOT doing this. Our code restarts as follows:

    # pluginctl -s radvd stop
    Service `radvd' has been stopped.
    # pluginctl -s radvd start 
    Service `radvd' has been started.
    # ps aux | grep radvd
    root    61611   3.2  0.0  12696   2448  -  Ss   09:03       0:00.00 /usr/local/sbin/radvd -p /var/run/radvd.pid -C /var/etc/radvd.conf -m syslog

I'm going to lock this ticket now. Feel free to start a new ticket with a way to reproduce the issue as your steps are incomplete and the "rg" utility doesn't even exist.


Cheers,
Franco
