### ISSUE TITLE
dhcp: Kea not allowing to specify pools per interface

### ISSUE THREAD

**Issue by rossigee** [opnsense/core#7347]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**

Trying to migrate from ISC DHCP, where I have a LAN interface which dishes out addresses from it's own pool (say, 172.16.10.100-199) and a WIFI interface which dishes out addresses from it's pool (say, 192.168.20.100-199), and various other ranges which should only apply to certain interfaces.

This allows me to then trust/treat connections from each range differently from a security standpoint.

I can't see how the current approach of having one set of pools which apply to all configured interfaces would allow me to accomplish this arrangement. It seems to make some awkwardly simplistic topology/routing assumptions.

**Describe the solution you like**

I guess a field per pool definition which could be used to apply it to one or more interfaces, if that's even possible with Kea.

**Describe alternatives you considered**

N/A

**Additional context**

N/A

**Comment by AdSchellevis** [comment]
You did try to add both subnets and inspect the leases? I would expect that kea prefers an address that fits the interface subnet. Their documentation is available at https://kea.readthedocs.io/en/latest/arm/intro.html when you would like to deep dive into the options it offers.

**Comment by rossigee** [comment]
@AdSchellevis - no, I didn't try that, but it makes sense now. I'll give that a try later and re-open this if it's still an issue. Thanks!
