### ISSUE TITLE
tx checksum offload broken with Xen netfront

### ISSUE THREAD

**Issue by andreas-p** [opnsense/core#735]
See https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=197344; still present with 10.3 from opnsense-update -bkr 791bdab10f3cfbed0b6a62d89d9168fb66d3eafe

When routing traffic between two (non-FreeBSD) VMs over opnsense that are located on the same Xen host tx checksumming must be switched off (suffering a heavy speed penalty). With TX offloading enabled, packets leaving the router contain an invalid checksum and won't be accepted by the target. This happens regardless whether pf is enabled or disabled.

A recent patch for a similar pf specific issue (https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=154428) didn't fix this.

**Comment by fichtner** [comment]
Sorry, no movement in FreeBSD as it seems.
