### ISSUE TITLE
Firewall Multi-Month Schedule Bug

### ISSUE THREAD

**Issue by smithj33** [opnsense/core#7350]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x ] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x ] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

If you create a schedule for say 2 months, February_24 and March_24, once February is over, you can no longer remove February as February_24 is no longer an option. Oddly when you go to edit the schedule, the days you chose for February_24 now show up under February_25, but you can't actually edit them.

A clear and concise description of what the bug is, including last known working version (if any).

*Tip*: to validate your setup was working with the previous version, use opnsense-revert (https://docs.opnsense.org/manual/opnsense_tools.html#opnsense-revert)

**To Reproduce**

1. Go to Firewall | Settings | Schedules
2. Create a schedule that spans multiple months
3. Once a month passes, attempt to edit the schedule and remove the prior months dates

**Expected behavior**

You should be able to remove the past months dates versus recreating a new schedule every month. Also, the past months selected dates should not show up in the same month for the next year.

**Describe alternatives you considered**

**Bug possibly similar to #7291?**

**Screenshots**

**Relevant log files**

If applicable, information from log files supporting your claim.

**Additional context**

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 23.7.8 (amd64).
Intel® Xeon™ E3-1225V5 3.3Ghz Quad Core
Network Intel® I210-AT

**Comment by AdSchellevis** [comment]
upgrade to a version that does include https://github.com/opnsense/core/issues/7291 ?

**Comment by smithj33** [comment]
I just upgraded to the latest version and the issues above still exist. I guess the main issue is the prior month get removed from the selection menu at the start of a new month since it's a rolling 12 month menu. A 13 month menu, which keeps the prior month, could be a solution, but not sure if that is possible.
