### ISSUE TITLE
Named / Bind invalid secondary zone configuration written from opnsense

### ISSUE THREAD

**Issue by Bassbauer** [opnsense/core#7351]
**To Reproduce**

1. install os-bind package
2. configure a normal config with zone slaves
3. add any kind of slave zone

you will see that bind wont start anymore due to an invalid configuration:

vi /usr/local/etc/namedb/named.conf

zone "test.zone" {
        type secondary;
        primaries { 10.99.8.11; 10.99.8.10; };
        file "/usr/local/etc/namedb/secondary/test.zone.db";
        allow-query {
                internal;
        };
        update-policy {
                grant rndc-key zonesub ANY;
        };
};

the reason is simple, secondary zones cannot have an update-policy, remove the statement and bind will start fine.

**Expected behavior**

OpnSense does not write an invalid configuration statement "update-policy" for secondary zones

**Environment**

Type	opnsense	
Version	24.1.4	
Architecture	amd64	
Commit	31cd002eb	
Mirror	https://pkg.opnsense.org/FreeBSD:13:amd64/24.1	
Repositories	OPNsense

**Comment by fichtner** [comment]
Fixed in master branch.
