### ISSUE TITLE
Suricata shows no logs and alerts

### ISSUE THREAD

**Issue by jh-devv** [opnsense/core#7353]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

Hey!
After recently reinstalling my OPNSense instance, Suricata is not working?

It does not make any alerts and when IPS is enabled, the log is filled with:
```
2024-04-01T19:01:40	Error	suricata	[101954] <Error> -- re0^: error reading netmap data via polling: No error: 0	
2024-04-01T19:01:40	Error	suricata	[101403] <Error> -- re0^: error reading netmap data via polling: No buffer space available
```
*Note: Before the reinstall, the instance was on 23.1*

This leads to the system becoming unusable and drive being filled with logs.

**To Reproduce**

1. Configure Suricata
2. Start Suricata

**Expected behavior**

This should not happen and it should work

**Environment**

Software version used and hardware type if relevant, e.g.:

##### Software:
OPNsense 24.1.4-amd64
FreeBSD 13.2-RELEASE-p10
OpenSSL 3.0.13

##### Hardware
Intel(R) Core(TM) i5-9600K CPU @ 3.70GHz (6 cores, 6 threads)

Onboard 1GB Network Port (re0)
Mellanox Connect-X3 (mlxen0, mlxen1) (driver: mlx4en)

**Comment by AdSchellevis** [comment]
most likely a driver issue, realtek is a bit notorious when it comes to driver support. Switching to software mode (see the note in https://docs.opnsense.org/manual/ips.html#choosing-an-interface), might help in these cases.

**Comment by jh-devv** [comment]
> most likely a driver issue, realtek is a bit notorious when it comes to driver support. Switching to software mode (see the note in https://docs.opnsense.org/manual/ips.html#choosing-an-interface), might help in these cases.

Thanks! I'll try
