### ISSUE TITLE
WireGuard peer configuration generator does not save instance

### ISSUE THREAD

**Issue by Ch-Fr** [opnsense/core#7356]
**Bug**

The WireGuard peer configuration generator lets you select an instance. But if you press "Store and generate next" the entry in the peer list does not have an instance configured.

**To Reproduce**

1. Go to VPN / WireGuard / Peer generator
2. Generate a peer
3. Click "Store and generate next"
4. Check the respective entry in the peer list for the instance

**Expected behavior**

The peer entry should have the selected WireGuard instance configured. For reference and in case it matters: In my case only one instance was configured.

**Environment**

OPNsense 24.1.5 (amd64).

**Comment by AdSchellevis** [comment]
Peer was adde, but not assigned?

**Comment by Ch-Fr** [comment]
Exactly. The peer was added like expected, but the instance field was blank.

**Comment by Ch-Fr** [comment]
It does.

Thank you for that patch and for your great work on OPNsense in general. Much appreciated!
