### ISSUE TITLE
WireGuard Peer Generator - Instance not being assigned to the new peer

### ISSUE THREAD

**Issue by mhlas7** [opnsense/core#7358]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**To Reproduce**

On the Peer Generator page, I have an Instance selected. When I click `Store and generate next` and then check the Peers page, the Instance has not been assigned to the new peer. All other values appear to be correctly input to the new peer.

**Expected behavior**

The instance from the peer generator should be assigned to the newly generated peer.

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense OPNsense 24.1.5_1-amd64

**Comment by AdSchellevis** [comment]
duplicate https://github.com/opnsense/core/issues/7356
