### ISSUE TITLE
Wireguard Peer Generator - Allowed IPs is correctly added to the peer config however it should not be added to the server side config when saved

### ISSUE THREAD

**Issue by mhlas7** [opnsense/core#7359]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Issue Description - Updated**

On the Peer Generator page, this is generating the config for the peer client where `Allowed IP's` refers to which IP addresses should be routed from the client and through the VPN server. The most common value for this is `AllowedIPs = 0.0.0.0/0, ::/0` which routes all traffic through from the client through the VPN. 

However when you create a new peer through the peer generator and click `Store and generate next` the `AllowedIPs = 0.0.0.0/0, ::/0` gets saved as `AllowedIPs` on the server side config which is **incorrect**. On the server side config, `AllowedIPs` should be the IP address which gets assigned to the client, which on the client config is the `Address` field.

**What changes should be made:**
1. On the Peer Generator page, add an `Address` field. This field will get added to the `[Interface]` section of the generated config and when the user clicks `Store and generate next`, this value is saved to the new peer in the `AllowedIPs` field on the Peers page
2. On the Peer Generator page, `AllowedIPs` should be added to the generated config (as it does in version 24.1.5_1) however, this should NOT be saved to `AllowedIPs` on the server side (the `Peers` page). This value is only valuable to the client side peer config.

**Original Description**
_See the comments below, I originally didn't understand WireGuard well enough_

I love the new WireGuard Peer Generator page!!! It is going to make generating VPN configs so much easier! However I did notice a few bugs that could make things better.

**On the Peers page, change `Allowed IP's` to `Address`** - `Allowed IP's` appears to be correctly labeled in the Peer Generator page however on the Peers page `Allowed IP's` is being used as the `Address` which is assigned to the peer when it connects to the VPN.

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense OPNsense 24.1.5_1-amd64

**Comment by AdSchellevis** [comment]
both are labeled the same (and stored at the exact same place)...
<img width="587" alt="image" src="https://github.com/opnsense/core/assets/9783985/39aa9608-65ce-463b-8bfe-c52dc3c92337">
<img width="855" alt="image" src="https://github.com/opnsense/core/assets/9783985/0740ffe7-eedc-4f8f-9a3c-17a2241c2c64">

**Comment by mhlas7** [comment]
Ahh you are correct! I got things mixed up. Resolving

**Comment by mhlas7** [comment]
Actually, @AdSchellevis I wanted to follow up on this. Looking at the documentation for the road warrior setup, it indicates that the `Allowed IP's` field on the Peers page is the `Address` field.

https://docs.opnsense.org/manual/how-tos/wireguard-client.html#step-2-configure-the-client-peer
```
Allowed IPs - Unique tunnel IP address (IPv4 and/or IPv6) of client - it should be a /32 or /128 (as applicable) within the subnet configured on the WireGuard Instance. For example, 10.10.10.2/32
```

Or maybe its just the documentation that needs to be updated?

I am a newbie when it comes to WireGuard so I could be misinterpreting things here.

**Comment by mhlas7** [comment]
Lower down on the same road warrior setup page I found another reference where `Allowed IPs` is being used as the peer client `Address` field.

https://docs.opnsense.org/manual/how-tos/wireguard-client.html#step-6-configure-the-wireguard-client

```
Address - Refers to the IP(s) specified as Allowed IPs in the Peer configuration on OPNsense. For example, 10.10.10.2/32
```

Overall I'm getting the impression that the documentation needs to be updated.

**Comment by mhlas7** [comment]
Ahh I learned something about WireGuard today! I was thinking of `Allowed IP's` from the perspective of the client and the peer config, whereas the peers page is looking at `Allowed IP's` from the perspective of the WireGuard host server. I've written plenty of client configs but I've always setup WireGuard servers through some sort of GUI and I have never directly managed the server side config.

There is still an issue here though. On the Peer Generator page, this is generating the config for the peer client where `Allowed IP's` refers to which IP addresses should be routed from the client and through the VPN server. The most common value for this is `AllowedIPs = 0.0.0.0/0, ::/0` which routes all traffic through from the client through the VPN. 

However when you create a new peer through the peer generator and click `Store and generate next` the `AllowedIPs = 0.0.0.0/0, ::/0` gets saved as `AllowedIPs` on the server side config which is incorrect. On the server side config, `AllowedIPs` should be the IP address which gets assigned to the client, which on the client config is the `Address` field.

**What changes should be made:**
1. On the Peer Generator page, add an additional `Address` field. This field will get added to the `[Interface]` section of the generated config and when the user clicks `Store and generate next`, this value is saved to the new peer in the `AllowedIPs` field on the Peers page
2. On the Peer Generator page, `AllowedIPs` should be added to the generated config (as it does today) however, this should NOT be saved to `AllowedIPs` on the server side (the `Peers` page)

I'll update the description of this ticket

**Comment by raphpa** [comment]
Would also be nice if the `Address` field then gets saved to use it for the next peer and is checked against the already available peers for overlap. `AllowedIPs` should also be saved.

I think the most confusion around Wireguard configs comes from the fact that Wireguard does not know the concept of server and client. All are just peers and the `AllowedIPs` setting defines which networks should be routed to that particular peer. Further blocking and routing is not part of Wireguard but the router and/or firewall.

**Comment by AdSchellevis** [comment]
> Would also be nice if the Address field then gets saved to use it for the next peer and is checked against the already available peers for overlap

On my mobile app (ios) it doesn't ask for an address (other than addresses, which appears to be the allowed range), which makes you wonder what the default is, terminology and documentation with Wireguard is challenging at best to be honest, which also explains most of the noise. 

Probably best open a ticket to discuss what this should do, I'm open for discussing some sort of address generation, but would like to see more datapoints before spending time on the subject.

> AllowedIPs should also be saved.
Feature request will do, I don't have strong opinions on not storing these per instance.

> I think the most confusion around Wireguard configs comes from the fact that Wireguard does not know the concept of server and client. All are just peers and the AllowedIPs setting defines which networks should be routed to that particular peer.

Well, from a technical perspective that's not even true, these are the networks that are routable, which doesn't mean traffic should go there, it's simply just allowed. Wireguard is just a tunnel, quite similar to the others. (but with a strong tendency of feeling special if I might add)

**Comment by maederm** [comment]
> Well, from a technical perspective that's not even true, these are the networks that are routable, which doesn't mean traffic should go there, it's simply just allowed. Wireguard is just a tunnel, quite similar to the others. (but with a strong tendency of feeling special if I might add)

When I set Allowed IPs of a peer to ::/0 and 0.0.0.0/0 I faced routing issues on opnsense. I had to undo this configuration and reboot. (I use configuration 4a, assigning an interface to WireGuard)

I'd be in favor of opnsense managing client IPv4 and IPv6 addresses for the road warrior scenario. If these addresses are then shown as aliases it would be easier to create firewall rules per client.

**Comment by AdSchellevis** [comment]
> When I set Allowed IPs of a peer to ::/0 and 0.0.0.0/0 I faced routing issues on opnsense. I had to undo this configuration and reboot. (I use configuration 4a, assigning an interface to WireGuard)

On the instance, check "Disable routes". for road-warriors you really don't want to automatically install routes (on OPNsense). This is more or less a leftover from how wg-quick operated, which in quite some cases likely isn't a good idea anyway.

**Comment by mhlas7** [comment]
> On the instance, check "Disable routes". for road-warriors you really don't want to automatically install routes (on OPNsense). This is more or less a leftover from how wg-quick operated, which in quite some cases likely isn't a good idea anyway.

@AdSchellevis I think the [Road Warrior documentation](https://docs.opnsense.org/manual/how-tos/wireguard-client.html#step-1-configure-the-wireguard-instance) needs to be updated here as it specifically says that `Disable Routes` should be unchecked. It may even be a good idea to include some help text under disable routes in the OPNsense interface. I think Road Warrior is a common setup that many installers are setting up.

**Comment by AdSchellevis** [comment]
@mhlas7 I think most concerns should be fixed with https://github.com/opnsense/core/commit/231a4d48de82ac963338c7b14954434a57d93bb5 , by generating addresses and storing these as allowed, the automatically generated routes are also less problematic (routes are skipped, because the interface has the net).

https://github.com/opnsense/core/blob/a86c0de2032925271e3243cca466d4f305f398d0/src/opnsense/scripts/Wireguard/wg-service-control.php#L96-L103

**Comment by mhlas7** [comment]
Things are working well in the new release! Thank you so much for all of your work on WireGuard and especially for all of the quality of life improvements that have been added in the past month!
