### ISSUE TITLE
unbound: msg-cache-slabs, ... in error on 6-core hosts

### ISSUE THREAD

**Issue by zommarin** [opnsense/core#736]
When running the DNS resolver (unbound) on 6-core hyperthreaded hosts (that shows up as 12-core in the OS) the performance tuning configuration entries end up in error as they are set to 12, and unbound wants these values to be a power of two (or else it won't start): _"Set *-slabs to a power of 2 close to the num-threads value."_

See: https://www.unbound.net/documentation/howto_optimise.html

pfsense have a fix for this as shown in this code:

	/*
	 * Set the number of threads equal to number of CPUs.
	 * Use 1 to disable threading, if for some reason this sysctl fails.
	 */
	$numprocs = intval(get_single_sysctl('kern.smp.cpus'));
	if ($numprocs > 1) {
		$optimization['number_threads'] = "num-threads: {$numprocs}";
		$optimize_num = pow(2, floor(log($numprocs, 2)));
	} else {
		$optimization['number_threads'] = "num-threads: 1";
		$optimize_num = 4;
	}
	// Slabs to help reduce lock contention.
	$optimization['msg_cache_slabs'] = "msg-cache-slabs: {$optimize_num}";
	$optimization['rrset_cache_slabs'] = "rrset-cache-slabs: {$optimize_num}";
	$optimization['infra_cache_slabs'] = "infra-cache-slabs: {$optimize_num}";
	$optimization['key_cache_slabs'] = "key-cache-slabs: {$optimize_num}";

opnsense should have a fix here: `core/src/etc/inc/unbound.inc`

**Comment by AdSchellevis** [comment]
Thanks for reporting, will fix this in the following commit.

**Comment by zommarin** [comment]
Looks great! Thanks for fixing this!
