### ISSUE TITLE
Automation rules don't appear anymore in Interface rules

### ISSUE THREAD

**Issue by adripa45** [opnsense/core#7367]
Hi,
We noticed on new versions of opnsense (24.1.*) that rules from Automation don't appear anymore in the list of rules of an Interface.
We don't have this problem on firewalls on 23.7.12 version.
Is this actually wanted ? Is there a way around to display all the rules in one place ?
Best regards,
Adrien

**Comment by AdSchellevis** [comment]
@adripa45 it's unintended, https://github.com/opnsense/core/commit/ceb51410ba86155908d28a35b801ab7a950f15ce should fix this
