### ISSUE TITLE
24.1.5 - ISC DHCPv4 does not register new leases in Unbound

### ISSUE THREAD

**Issue by TimmiORG** [opnsense/core#7376]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

New registered DHCP names are not registered inside the DNS (Unbound) even though so "Register ISC DHCP4 Leases" is enabled.

I think the issue is there since 24.1 but not 100%.
At least I can say it since 24.1.3.

**To Reproduce**

1. Register new hostname through DHCP
2. Request the IP via hostname from DNS -> no response
3. Reload Unbound server
4. Request the IP via hostname from DNS -> working

**Expected behavior**

Hostname should be registered automatically in the Unbound DNS.

**Describe alternatives you considered**

Restart of Unbound.

**Screenshots**

not needed

**Relevant log files**

Please let me know which logs are required

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 24.1.5_3 (amd64).
Intel(R) Xeon(R) Silver 4214R CPU @ 2.40GHz (12 cores, 24 threads)

**Comment by fob2024** [comment]
Exact same behaviour here for OPNsense 24.7.1.
Additionally, we have observed that entering DHCP leases still works shortly after restarting unbound.

**Comment by gyrex** [comment]
I'm also experiencing this issue and I created a forum post about this issue here: https://forum.opnsense.org/index.php?topic=43814.0
