### ISSUE TITLE
Domain search list wrong, when using dhcp ipv6 caused by `dhcp6.domain-search`.

### ISSUE THREAD

**Issue by dagobert** [opnsense/core#7377]
- The global `domain-name` option (set to the system domain) should be renamed to `dhcp6.domain-search`.
- Same for static mappings.
- The interface-specific `domain-name` option should be removed.

I created another pull request, please double check.

_Originally posted by @maurice-w in https://github.com/opnsense/core/issues/2336#issuecomment-556377778_

**Comment by AdSchellevis** [comment]
copying sections from other tickets without further context is considered spam.

**Comment by dagobert** [comment]
> copying sections from other tickets without further context is considered spam.

I was just elaborating my issue in a second comment since the interface options when referencing on copy is very bad!

**Comment by AdSchellevis** [comment]
please don't use the comments to explain any issue, use our templates which are there for a reason.
