### ISSUE TITLE
Domain search list wrong, when using isc dhcp6, caused by global dhcp6.domain-search entry in configuration file

### ISSUE THREAD

**Issue by dagobert** [opnsense/core#7379]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

When using ISC DHCPv6 with `domain search list` set to a different domain than the domain set in System->Settings->General: Domain, both the "opnsense domain" and the domain in the domain search list of the DHCPv6 interface are handed over to the clients.

In the pull request #3824 by @maurice-w (commit 122bf965b0a01991076769168d0dce1fcad3f696) the global option `domain-name` was replaced by `dhcp6.domain-search`.

**To Reproduce**

My setup is the following:

- opnsense domain in settings: example.com
- isc-dhcpv4 domain search list for interface lan: lan.example.com
- isc-dhcpv6 domain search list for interface lan: lan.example.com
- router advertisement domain search list for interface lan: lan.example.com

Clients with only ipv4 enable receive the correct domain search list via dhcp (lan.example.com).
Clients configured with ipv4 and ipv6 receive wrong domain search list via dhcp (example.com and lan.example.com).

**Expected behavior**

The OPNsense domain should not be included in the domain search list, at least not as soon as there is an entry in the domain search list of an interface.

**Describe alternatives you considered**

This problem is caused by the global option `dhcp6.domain-search` being the domain set for OPNsense host in system settings. This global option causes the additional search list for all subnets/interfaces.

**Screenshots**

none

**Relevant log files**

none

**Additional context**

This is not only an inconvenient effect but also a major problem with Windows network shares. Clients that have domain A.B.C configured but a search domain list of B.C will not connect/allow network sharing.

**Environment**

OPNsense 24.1.5_2-amd64
FreeBSD 13.2-RELEASE-p11
OpenSSL 3.0.13

**Comment by maurice-w** [comment]
If specified, a subnet-specific `dhcp6.domain-search` option is supposed to override the global option.

`/var/dhcpd/etc/dhcpdv6.conf` should have your system domain in the first line:
```
option dhcp6.domain-search "example.com";
```

The subnet6 declaration for your LAN subnet should include the LAN domain:
```
subnet6 2001:db8:0:1::/64 {
  option dhcp6.domain-search "lan.example.com";
  [...]
}
```

_lan.example.com_ is expected to replace _example.com_, not augment it. Did you perform a packet capture to confirm that DHCPv6 replies actually contain both domains?

**Comment by dagobert** [comment]
I did a tcpdump (`tcpdump -i enp0s3 -n -vv '(udp port 546 or 547) or icmp6'`) on ubuntu when requesting dhcp6 address (`dhclient -6 -i enp0s3`).

This is the ?relevant part? of the dump:

```
11:29:06.300165 IP6 (flowlabel 0xeaaee, hlim 1, next-header UDP (17) payload length: 64) fe80::a56e:2c6b:c4fd:438.546 > ff02::1:2.547: [bad udp cksum 0x98e7 -> 0xd6ca!] dhcp6 solicit (xid=33c818 (client-ID hwaddr/time type 1 time 766402145 08002726de25) (option-request DNS-server DNS-search-list Client-FQDN SNTP-servers) (elapsed-time 0) (IA_NA IAID:656858661 T1:3600 T2:5400))
11:29:06.301332 IP6 (hlim 64, next-header UDP (17) payload length: 143) fe80::be24:11ff:fe7d:fcac.547 > fe80::a56e:2c6b:c4fd:438.546: [udp sum ok] dhcp6 advertise (xid=33c818 (IA_NA IAID:656858661 T1:0 T2:0 (IA_ADDR 2a00:6020:5092:2c05::29e3 pltime:4500 vltime:7200)) (client-ID hwaddr/time type 1 time 766402145 08002726de25) (server-ID hwaddr/time type 1 time 764417234 bc2411c42b1e) (DNS-server 2a00:6020:5092:2c05:be24:11ff:fe7d:fcac) (DNS-search-list lan.example.com.))
11:29:07.341055 IP6 (flowlabel 0xeaaee, hlim 1, next-header UDP (17) payload length: 110) fe80::a56e:2c6b:c4fd:438.546 > ff02::1:2.547: [bad udp cksum 0x9915 -> 0x96c4!] dhcp6 request (xid=b05f8a (client-ID hwaddr/time type 1 time 766402145 08002726de25) (server-ID hwaddr/time type 1 time 764417234 bc2411c42b1e) (option-request DNS-server DNS-search-list Client-FQDN SNTP-servers) (elapsed-time 0) (IA_NA IAID:656858661 T1:3600 T2:5400 (IA_ADDR 2a00:6020:5092:2c05::29e3 pltime:7200 vltime:7500)))
11:29:07.342123 IP6 (hlim 64, next-header UDP (17) payload length: 143) fe80::be24:11ff:fe7d:fcac.547 > fe80::a56e:2c6b:c4fd:438.546: [udp sum ok] dhcp6 reply (xid=b05f8a (IA_NA IAID:656858661 T1:0 T2:0 (IA_ADDR 2a00:6020:5092:2c05::29e3 pltime:4500 vltime:7200)) (client-ID hwaddr/time type 1 time 766402145 08002726de25) (server-ID hwaddr/time type 1 time 764417234 bc2411c42b1e) (DNS-server 2a00:6020:5092:2c05:be24:11ff:fe7d:fcac) (DNS-search-list lan.example.com.))

```

But I was also getting the following message.

```
11:36:48.254993 IP6 (hlim 255, next-header ICMPv6 (58) payload length: 64) fe80::20d:b9ff:fe55:7573 > ff02::1: [icmp6 sum ok] ICMP6, router advertisement, length 64
	hop limit 64, Flags [none], pref high, router lifetime 1800s, reachable time 0ms, retrans timer 0ms
	  dnssl option (31), length 32 (4):  lifetime 600s, domain(s): example.com.
	    0x0000:  0000 0000 0258 0863 6f6a 6968 6f6d 6506
	    0x0010:  342d 7765 726b 0264 6500 0000 0000
	  mtu option (5), length 8 (1):  1500
	    0x0000:  0000 0000 05dc
	  source link-address option (1), length 8 (1): 00:0d:b9:55:75:73
	    0x0000:  000d b955 7573
```

I also noticed that the search list was wrong again even after removing the global option. I guess it was just an coincidence. I was running wireshark for a long time on one of the windows clients since they had the problems. I was looking for this latter packet.
Finally I found the problem. The MAC helped in the end. It was my old opnsense that still advertised its configuration. It was left running for a later HA setup and not purged properly.

I am very sorry to have bothered and thank plenty for the tcpdump tip. I should have thought of it earlier.

Regards
