### ISSUE TITLE
unbound: Bind to VIP interface breaks the config file

### ISSUE THREAD

**Issue by zommarin** [opnsense/core#738]
I have a CARP setup of OPNsense and the DNS Resolver is enabled. I need to bind the service so that replies are made using the VIP address. If this is selected (done in `Services: DNS Resolver: General`, Section `Outgoing Network Interfaces`) and I set it to `1.2.3.4 (VIP LAN)` (assuming 1.2.3.4 is my VIP LAN address), then the config file will contain this broken line:

```
# Outgoing interfaces to be used
outgoing-interface: 10.1.47.1
outgoing-interface: Array
```

The `Array` does not really seem right... Kind of looks like the helpful `(VIP LAN)` breaks things.

I am using `OPNsense 16.1-amd64`

**Comment by AdSchellevis** [comment]
Thanks for reporting, apparently the check for ipv6 addresses returns an empty array which gets rendered to the output. I will fix this in the next commit.

**Comment by zommarin** [comment]
Great! I like the turnaround time - less then two hours, impressive!

**Comment by AdSchellevis** [comment]
Thanks! but to be honest, your problem description was very clear and helpful.

**Comment by fichtner** [comment]
I agree with the both of you... awesome team play! :)
