### ISSUE TITLE
DHCP log file permission - /ui/diagnostics/log/core/dhcpd

### ISSUE THREAD

**Issue by matiasduartee** [opnsense/core#7382]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

With the change of the DHCP service to the new ISC DHCPv4 name, the endpoint of the loh file is wrong, the correct one would be /ui/diagnostics/log/core/dhcpd and in the permissions interface it is /ui/diagnostics/log/core/dhcp, as the image shows.

OPNsense 24.1.5_3-amd64
FreeBSD 13.2-RELEASE-p11
OpenSSL 3.0.13

![image](https://github.com/opnsense/core/assets/81826268/ecc789e5-cfef-44d9-8c83-2dd58d12f06c)

**Comment by AdSchellevis** [comment]
I think it's an older regression (rename didn't move anything), but the ACL does indeed seem to point to the wrong item.

**Comment by AdSchellevis** [comment]
@matiasduartee thanks for reporting by the way
