### ISSUE TITLE
[Feature Request]: trust: certificate renew functionality

### ISSUE THREAD

**Issue by teodorescuserban** [opnsense/core#7385]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**

For the purpose of running an OpenVPN server with internal certificates, I am missing a solution in the WebGUI that would renew the expired certificates that are generated by an internal CA.

**Describe the solution you like**

I would like an action icon next to the "info" icon for each certificate that would allow me to renew that certificate.
This is the exact functionality present in pfSense for as long as I remember. I didn't even imagined that it wouldn't be present in OPNSense. :( 

**Describe alternatives you considered**

Export the expired certificate and its key, ran `openssl x509 -x509toreq -in old.crt -signkey private.key` to get a new csr and signed that CSR with my internal CA.

The problem is I can see both certificates (the old one and he new one) in the list and the new one has no key associated with it.

After all this I do have to also go and edit the user to link the new certificate and unlink the old one.

Even then, openvpn client export will not work properly as it keeps attaching the old certificate to the config. I would remove it, but then the key is not accessible anymore.

**Additional context**

**Comment by AdSchellevis** [comment]
tried the latest development release?

**Comment by teodorescuserban** [comment]
> tried the latest development release?

No, but I will and provide feedback. 
Thank you, @AdSchellevis!

**Comment by teodorescuserban** [comment]
Alright, I tested the development, this looks really nice!
I am providing feedback below, as promised.
When can we expect this to be rolled out to production? I see 24.7 is scheduled for July 2024, but there is no mention about the Trust related enhancements in the road map.

Expected functionality that now works:
- I am able to reissue/renew the certificate in place, which means the private key stays linked with the new certificate 
![Screenshot 2024-04-17 at 03 14 33](https://github.com/opnsense/core/assets/1542984/0f63d402-53a4-4ede-9fa3-1c47cc3089cc)

- It looks like OpenVPN's "Client Export" is able to pick the certificate changes immediately

Issues I've found:
- cannot link / create a user certificate from the user page: I get redirected to `/system_certmanager.php?act=new&userid=1` which doesn't seem to be working, but I am able to create a certificate with the same common name as the username and OpenVPN will happily use it 
![Screenshot 2024-04-17 at 03 06 13](https://github.com/opnsense/core/assets/1542984/cf4e426e-8fef-4676-94a5-b0098a388cde)
![Screenshot 2024-04-17 at 03 06 23](https://github.com/opnsense/core/assets/1542984/d8c943aa-f036-4030-8dc9-c2c28bcf81b2)

- when I reissued the certificate I did not go through all the fields, assuming there will be no change, however, the CN changed to `internal-ca`, which I noticed when checking the connection status on OpenVPN after re-exporting the certificate; I'd argue that the CN field should be readonly for a certificate reissue, but I think at least it should be pre-populated with the previous certificate CN. 
![Screenshot 2024-04-17 at 03 20 07](https://github.com/opnsense/core/assets/1542984/80466f44-db04-4b1c-8e06-b6ec486451b9)

- OpenVPN's "Connection Status" throws an error about not being able to read the description when a connection is active, but it looks like it does show the description anyway.
![Screenshot 2024-04-17 at 03 17 17](https://github.com/opnsense/core/assets/1542984/07e4ca54-edca-4e8f-9812-4e0e4d9553ad)
![Screenshot 2024-04-17 at 03 32 54](https://github.com/opnsense/core/assets/1542984/4f82782e-77ea-41d7-abe3-2aae6c4b6a6e)

**Comment by AdSchellevis** [comment]
>Alright, I tested the development, this looks really nice!

Thanks, it was quite some work

> When can we expect this to be rolled out to production? I see 24.7 is scheduled for July 2024, but there is no mention about the Trust related enhancements in the road map.

There is, see (base system) https://opnsense.org/about/road-map/

> cannot link / create a user certificate from the user page: I get redirected to /system_certmanager.php?act=new&userid=1 which doesn't seem to be working, but I am able to create a certificate with the same common name as the username and OpenVPN will happily use it

Can you open a ticket for this? I'll take a look when I can. It might miss some glue to be able to support linking to it.

> when I reissued the certificate I did not go through all the fields, assuming there will be no change, however, the CN changed to internal-ca, which I noticed when checking the connection status on OpenVPN after re-exporting the certificate; I'd argue that the CN field should be readonly for a certificate reissue, but I think at least it should be pre-populated with the previous certificate CN.

Also a ticket please.

> OpenVPN's "Connection Status" throws an error about not being able to read the description when a connection is active, but it looks like it does show the description anyway.

Weird, but a separate ticket would be helpful to track this down.

**Comment by teodorescuserban** [comment]
> There is, see (base system) https://opnsense.org/about/road-map/

Oh, indeed it is! I was looking for `Trust` but missed `System Trust`

I created 3 bug reports as requested. 

Thank you for support, I'll wait for 24.7.
