### ISSUE TITLE
[Bug] Wrong "internal-ca" default for CN field when renewing a certificate on development

### ISSUE THREAD

**Issue by teodorescuserban** [opnsense/core#7389]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

This is related to https://github.com/opnsense/core/issues/7385.
I am using the development environment to test the renew certificate feature.
When I reissued the certificate I did not go through all the fields, assuming there will be no change, however, the CN changed from the user name to `internal-ca`, which I noticed only when checking the connection status on OpenVPN after re-exporting the certificate; I'd argue that the CN field should be readonly for a certificate reissue, but I think at least it should be pre-populated with the previous certificate CN

**To Reproduce**

1. Install the development env
2. Create an internal certificate authority; give it the common name `internal-ca`
3. Create a new certificate signed by your new CA (pick any common name beside `internal-ca`)
4. Click the new `Edit` icon for it
5. Observe how on the new form the common name is now `internal-ca` (this seems to match whatever common name you chose fot your *CA* not for your certificate).

**Expected behavior**

The common name should be pre-populated with the old certificate common name, not with the signing CA common name.
Or even better, just have it read-only?

**Describe alternatives you considered**

N/A

**Screenshots**

![Screenshot 2024-04-17 at 03 20 07](https://github.com/opnsense/core/assets/1542984/7e12707c-a8b9-4949-8406-9985b8d02c47)

**Relevant log files**

N/A

**Additional context**

N/A

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 24.7.a_341-amd64
FreeBSD 13.2-RELEASE-p11
OpenSSL 3.0.13

**Comment by AdSchellevis** [comment]
I can't reproduce this, below screenshots made on creation and reissue
<img width="926" alt="image" src="https://github.com/opnsense/core/assets/9783985/51dd5dbe-ca22-4e6d-a877-0d6187b544a1">

<img width="905" alt="image" src="https://github.com/opnsense/core/assets/9783985/41255240-ac10-4096-a837-d3ab2f77c4fd">

**Comment by teodorescuserban** [comment]
I think I missed a step in the bug report, sorry about that, @AdSchellevis .
If you create a self-signed certificate you cannot reploduce this.
The issue comes up if you create an internal CA (mine had `internal-ca` as common name) and the create a new certificate signed by this internal CA.

**Comment by AdSchellevis** [comment]
@teodorescuserban best update the steps in the ticket then with the ones we need to replicate to reproduce the issue. The origin of the cert shouldn't matter for the cn it fetches, maybe only when no CN exists.

**Comment by teodorescuserban** [comment]
Sure, @AdSchellevis, I updated the ticket description.

**Comment by teodorescuserban** [comment]
@AdSchellevis do you need anything else on this ticket? 
Thank you.

**Comment by AdSchellevis** [comment]
@teodorescuserban it looks like I can reproduce your issue, so nothing more needed

**Comment by AdSchellevis** [comment]
@teodorescuserban can you retest with https://github.com/opnsense/core/commit/50bd3dc48cb5222482cd04ee860543cc9c69cc88 in place? it would be helpful to also retest the other functions if you can spare the time, I don't expect impact, but it's good to know for sure.

**Comment by teodorescuserban** [comment]
@AdSchellevis, https://github.com/opnsense/core/commit/50bd3dc48cb5222482cd04ee860543cc9c69cc88 seems to fix the issue. I found no other issues while testing.
Thank you for fixing this!

**Comment by AdSchellevis** [comment]
@teodorescuserban thanks for testing!
