### ISSUE TITLE
Automatically disable all hardware offloading when IPS mode is enabled

### ISSUE THREAD

**Issue by lattera** [opnsense/core#739]
I forgot to disable all hardware offloading this prior to enabling IPS mode and bad things happened. I'm wondering if it'd be a good idea to automatically disable hardware offloading if the user decides to enable IPS mode. That way, the user doesn't have to remember to do that.

**Comment by AdSchellevis** [comment]
We will add a validation at some point in time, but it needs additions to the model system.... It will be there, but might take some time.
(for ids, hw offloading is fine, for ips not)

**Comment by gonzopancho** [comment]
There is code in netmap-fwd that does this.  I'd do the work to extract it and provide a pull request, but @fichtner would just reject it.

https://github.com/Netgate/netmap-fwd/blob/master/if.c#L543

So at least you know where to look.

**Comment by gonzopancho** [comment]
There is code to do this in netmap-fwd.

https://github.com/Netgate/netmap-fwd/blob/master/if.c#L67-L78
https://github.com/Netgate/netmap-fwd/blob/master/if.c#L543-L561

I would prepare a patch and a pull request for opnsense, but @fichtner would just have someone else implement it.  At a minimum @lattera, @AdSchellevis or @fichtner could look at that code for a solution.

I wrote a comment on this issue to this effect last night, but it seems to have been deleted.

**Comment by AdSchellevis** [comment]
We're swapping the defaults, there are too many situations where hardware offloading causes issues. https://github.com/opnsense/core/issues/1092

**Comment by L1ghtn1ng** [comment]
Is this going to be back ported to the 16.7 branch? Also if hardware offloading has been disabled already, I am guessing that it will not need to change anything? if it has not been then it will disable it for you?

**Comment by AdSchellevis** [comment]
@L1ghtn1ng as soon as we release a new installer, we will use the new defaults. The current images obviously contain the previous defaults.
