### ISSUE TITLE
Wireguard GUI KeyGen Pair Issue

### ISSUE THREAD

**Issue by rudiservo** [opnsense/core#7396]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

I have been trying for the past 8 hours to create a site to site WG vpn, I followed the official tutorial to the T without any success
In a last attempt I searched for any issues in the forums and reddit, in a comment someone tried to generate the pairs manually instead of the generated by the GUI.
So I generated the keys via SSH and extracted the pub key for both sites (it was much larger than the original one), and it immediately connected.

I had to create new keys via CLI for both sites.

I do not know how this came to be, I checked and triple check the key pairs and generated a few more in the GUI without success.

**To Reproduce**
Try and use a connection with generated keypairs in the GUI vs CLI

**Environment**

OPNsense 24.1.6-amd64
FreeBSD 13.2-RELEASE-p11
OpenSSL 3.0.13

**Comment by Beachviolence** [comment]
Did you use the peer generator for this, or is this issue related to another keygen in the GUI? I have noticed a bug where the pubkey doesn't update in the textbox next to the QR-code, so the saved config is another than the one showing. I need to know if i should open another issue or not.

**Comment by rudiservo** [comment]
@Beachviolence I think I might have used both situations, the issue might be in the updating the key itself rather than a newly generated one.

Because I added new key for mobile devices generated once and first time only and it was ok.

Can you check, I am going to try and get to it when I can.
