### ISSUE TITLE
Update bogons

### ISSUE THREAD

**Issue by cbuechler** [opnsense/core#74]
Suggested patch to rc.update_bogons:

**Comment by jschellevis** [comment]
Thanks for sharing your thoughts.

**Comment by fichtner** [comment]
Viable source: https://www.team-cymru.org/bogon-reference-http.html

**Comment by AdSchellevis** [comment]
fixed  https://github.com/opnsense/core/commit/66a9c2703dacba1179fcdcd58f4903f9bad4900d

**Comment by fichtner** [comment]
Switched to https://pkg.opnsense.org/bogons to ease the bandwidth for others. Sorry for the trouble!
