### ISSUE TITLE
System/Trust: (Dev) Selecting multiple certificates for deletion, only deletes 1 certificate

### ISSUE THREAD

**Issue by Monviech** [opnsense/core#7402]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

When selecting multiple certificates for deletion in "System - Trust - Certificates", only one certificate will be deleted.

**To Reproduce**

1. Go to 'System - Trust - Certificates'
2. Mark multiple certificates with the checkbox
3. Click on the "delete" icon
4. Only one certificate from the selected certificates will be deleted.

**Expected behavior**

All selected certificates will be deleted.

**Screenshots**

![screen001](https://github.com/opnsense/core/assets/79600909/c5f19a99-c505-4353-9f0e-8547b9629ed8)
![screen002](https://github.com/opnsense/core/assets/79600909/ad026dee-0331-4720-9735-390372634e5e)
![screen003](https://github.com/opnsense/core/assets/79600909/70d582b7-ea0c-4eab-bf24-af96aa09bef7)

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 24.7.a_372-amd64
FreeBSD 13.2-RELEASE-p11
OpenSSL 3.0.13

**Comment by AdSchellevis** [comment]
@Monviech this https://github.com/opnsense/core/commit/885aba5944119536b8ff32c3bebc2477835ba681 ?

**Comment by Monviech** [comment]
@AdSchellevis Solved it, thanks.
