### ISSUE TITLE
Multi-Wan: Not sure if bug or feature - Lately I have to restart the multi-wan service (or re-save the settings) to see the IP address ever switch

### ISSUE THREAD

**Issue by ilikenwf** [opnsense/core#7407]
I have two WAN connections right now, both about equally as "good" and they don't usually ping out or anything. I have them with equal priority, both Tier 1 for my "humans" WAN group that the LAN uses for internet connections.

Ever since 1-3 updates ago (am on current stable), I notice that sometimes the load balance configuration does not switch clients' exit IP address at all in many cases. I have it configured for non-sticky round robin to maximize throughput.

After re-saving the settings it works for a time, but eventually goes back to having the LAN users exit from just one of the two WAN connections. I feel like there could be an issue here but I'm not 100% sure.

Happy to do what I can to assist.

**Comment by ilikenwf** [comment]
After investigating it appears this happens after the nightly reboot of the starlink dish. I've disabled it, however shouldn't the firewall, once it realizes that the WAN is back up, start routing it as normal again? I have to pull the interface down and put it back up in order to alleviate the situation.

**Comment by fichtner** [comment]
@ilikenwf the states may still reference the working starlink connection so it won't switch everything over as that would also mean disrupting established connections

**Comment by ilikenwf** [comment]
I don't think so since the default wan connection routes via starlink and works fine even after I restart...

**Comment by ilikenwf** [comment]
I added an interface refresh after the reboot and the issue persists...

**Comment by ilikenwf** [comment]
Yet if I manually restart it now it goes back to working...

**Comment by jbdu12** [comment]
Hello,
I have same problem. 
If i have my WAN  become down, and back up. The monitoring of this gateway ( dpinger) stay down.
The solution is re saving the setting of gateway

**Comment by nerzhei** [comment]
Hello,

I'm facing the same issue and was wondering if you have found a workaround?

Here is my setup:

- Multi-WAN with one static and one PPPoE connection (dynamic, renewed every 12 hours).
- Both gateways are set to tier 1 (load balancing) and have the same priority.
- The dynamic connection is set as the upstream.
- Gateway monitoring is enabled and "Allow default gateway switching" is active.

When the PPPoE connection is renewed, traffic starts flowing only through the static WAN. This issue resolves itself after saving any changes related to the gateway or firewall.

**Comment by ilikenwf** [comment]
I added interface restarts that trigger after I reboot starlink and tmo, and this seems to have fixed my issue in particular. The current version of OPNSense works for me just fine now, with my config at least.
