### ISSUE TITLE
Host traffic report data ~1/2 expected rate

### ISSUE THREAD

**Issue by Codelica** [opnsense/core#7421]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

Traffic report host data seems to be ~ 1/2 the expected rate.  In this example I have a VPN interface (VPN_eC_IOT - purple) which just has a 6Mbps inbound video stream to a client on the LAN.   As you can see the purple inbound VPN rate graph at the top does show the 6Mbps stream, however the hosts graphs show 3Mbps streams from the VPN and to the LAN client which seem incorrect unless I'm missing something(?).

**To Reproduce**

Setup a substantial data stream between hosts on two networks (with negligible other activity) and compare the network graph for the networks and the hosts. 

**Expected behavior**

Without other host network activity, the host network stats should roughly equal the network stats. 

**Describe alternatives you considered**

That I'm overlooking something very simple -- sorry if that's the case!

**Screenshots**

<img width="1137" alt="traffic-graph" src="https://github.com/opnsense/core/assets/386101/ab1d917a-1fc5-4f06-b554-c0784238c9b2">

**Relevant log files**

Can pull some if needed.

**Additional context**

N/A. 

**Environment**

OPNsense 24.1.6-amd64
Intel(R) Celeron(R) J4125 CPU @ 2.00GHz (4 cores, 4 threads)
4 x Intel 2.5GbE I226-V

**Comment by Codelica** [comment]
I decided to setup a controlled example you can replicate.  Over a quiet network connection I setup a listener on one side via:

`nc -lk 8000 > /dev/null`

And a source to feed it random data at ~2Mbps (244 kibibytes/s for pv):

`dd if=/dev/urandom bs=1000 count=100000000 | pv -L 244k | nc my-test-host 8000`

As you can see the network graph correctly shows ~2Mbps, while the host graph shows the corresponding host at only ~1Mbps:

<img width="1242" alt="openvpn-traffic" src="https://github.com/opnsense/core/assets/386101/6ddcff6e-3fdc-4db1-a745-c4ea397819b5">

**Comment by AdSchellevis** [comment]
The top hosts are sampled (each 2 seconds) using iftop and only the top 10 is collected if I'm not mistaken, which might explain differences here.

https://github.com/opnsense/core/blob/030ed198a7b24fcd3a671c7726a9f9163018e295/src/opnsense/scripts/interfaces/traffic_top.py#L45-L48

**Comment by Codelica** [comment]
The bug here is actually with `iftop` which is being used to gather the stats.  Basically `iftop` when called in non-curses mode (`-t`) is returning output rates that are exactly 1/2 the normal (correct) curses mode output . 

For example, startup a controlled stream from host A to B on interface XXX then check the statistics for that connection via both:

Curses:

`iftop -nNb -i XXX -s 2`

Non-curses:

`iftop -nNb -i XXX -s 2 -t`

And you'll see it's always ~ 1/2 the rate.

Also FWIW `iftop` doesn't seem to have a `-s` param which OPNsense uses, at least not one discussed in the current man page.

**Comment by AdSchellevis** [comment]
```
# iftop -h
iftop: display bandwidth usage on an interface by host

Synopsis: iftop -h | [-npblNBP] [-i interface] [-f filter code]
                               [-F net/mask] [-G net6/mask6]

   -h                  display this message
   -n                  don't do hostname lookups
   -N                  don't convert port numbers to services
   -p                  run in promiscuous mode (show traffic between other
                       hosts on the same network segment)
   -b                  don't display a bar graph of traffic
   -B                  Display bandwidth in bytes
   -i interface        listen on named interface
   -f filter code      use filter code to select packets to count
                       (default: none, but only IP packets are counted)
   -F net/mask         show traffic flows in/out of IPv4 network
   -G net6/mask6       show traffic flows in/out of IPv6 network
   -l                  display and count link-local IPv6 traffic (default: off)
   -P                  show ports as well as hosts
   -m limit            sets the upper limit for the bandwidth scale
   -c config file      specifies an alternative configuration file
   -t                  use text interface without ncurses

   Sorting orders:
   -o 2s                Sort by first column (2s traffic average)
   -o 10s               Sort by second column (10s traffic average) [default]
   -o 40s               Sort by third column (40s traffic average)
   -o source            Sort by source address
   -o destination       Sort by destination address

   The following options are only available in combination with -t
   -s num              print one single text output afer num seconds, then quit
   -L num              number of lines to print

```

-s averages over 2 secondes

There's not a lot in the upstream git repo (https://code.blinkace.com/pdw/iftop), in the long run we might look into switching to an alternative if the reporting is more suitable, but I haven't found one yet (haven't seen a difference on my end either yet to be honest).

**Comment by Codelica** [comment]
Yes, it seems that first 2 second sample period just isn't accurate.  You can actually see it in the normal curses output as well where the initial values literally double when that first sample is replaced.  For me `-s 4` seems to work pretty well though.
