### ISSUE TITLE
More than 1200 php processes - 99 % memory and swap usage

### ISSUE THREAD

**Issue by smart7324** [opnsense/core#7423]
**Important notices**

Our forum is located at https://forum.opnsense.org , please consider joining discussions there in stead of using GitHub for these matters.

Before you ask a new question, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

## Problem

Today I logged into my OPNsense dashboard and saw 99% memory and swap usage. I found out that there were **1231 php processes running**, each using more than 60 MB of RAM.

A reboot of course fixed the issue, as **after reboot only 8 php processes are running**, but this can happen again I guess?

How can there be so many processes? Isn't there any limit set how many php processes can be spawned? I kind of know the configuration of php-fpm, there you can provide a maximum number of processes to fork. But it seems OPNsense core is not using php-fpm, but php-cgi.

I would be very happy about any help!
 
OPNsense 24.1.6-amd64
FreeBSD 13.2-RELEASE-p11
OpenSSL 3.0.13

Never experienced these problems before...

**Comment by AdSchellevis** [comment]
`ps faxd | grep php` ?

**Comment by smart7324** [comment]
Yeah now it's only the 8 processes. Will keep an eye on it and reply if it rises again...

```
root@opnsense:~ # ps faxd | grep php
 2996  0  S+     0:00.00 |       `-- grep php
19370  -  Is     0:00.03 | |-- /usr/local/bin/php-cgi
20452  -  S      0:01.49 | | |-- /usr/local/bin/php-cgi
22164  -  I      0:00.15 | | |-- /usr/local/bin/php-cgi
23878  -  I      0:00.76 | | `-- /usr/local/bin/php-cgi
20027  -  Is     0:00.03 | `-- /usr/local/bin/php-cgi
16663  -  S      0:00.75 |   |-- /usr/local/bin/php-cgi
46318  -  S      0:00.42 |   |-- /usr/local/bin/php-cgi
73876  -  S      0:00.45 |   `-- /usr/local/bin/php-cgi
```

**Comment by smart7324** [comment]
So as it never happened again, I think we can close this issue now.

**Comment by frivascl** [comment]
it happened to me. This is the output:

root@casa:/var/log/system # ps faxd | grep php
77485  0  S+       0:00.00 |         `-- grep php
54141  -  IWs      0:00.00 |-- daemon: /usr/local/opnsense/scripts/routes/gateway_watcher.php[54627] (daemon)
54627  -  S       27:38.82 | `-- /usr/local/bin/php /usr/local/opnsense/scripts/routes/gateway_watcher.php interface routes alarm
58894  -  Is       0:00.04 | |-- /usr/local/bin/php-cgi
20996  -  I        0:00.07 | | |-- /usr/local/bin/php-cgi
30826  -  I        0:00.00 | | |-- /usr/local/bin/php-cgi
45149  -  I        0:00.02 | | |-- /usr/local/bin/php-cgi
61890  -  IW       0:00.00 | | |-- /usr/local/bin/php-cgi
63656  -  IW       0:00.00 | | |-- /usr/local/bin/php-cgi
64533  -  IW       0:00.00 | | |-- /usr/local/bin/php-cgi
65741  -  I        0:00.00 | | |-- /usr/local/bin/php-cgi
67006  -  IW       0:00.00 | | |-- /usr/local/bin/php-cgi
67787  -  IW       0:00.00 | | |-- /usr/local/bin/php-cgi
68707  -  IW       0:00.00 | | |-- /usr/local/bin/php-cgi
69514  -  IW       0:00.00 | | |-- /usr/local/bin/php-cgi
70251  -  IW       0:00.00 | | |-- /usr/local/bin/php-cgi
71372  -  IW       0:00.00 | | |-- /usr/local/bin/php-cgi
71994  -  IW       0:00.00 | | |-- /usr/local/bin/php-cgi
73849  -  IW       0:00.00 | | |-- /usr/local/bin/php-cgi
75003  -  IW       0:00.00 | | |-- /usr/local/bin/php-cgi
76108  -  IW       0:00.00 | | |-- /usr/local/bin/php-cgi
77211  -  IW       0:00.00 | | |-- /usr/local/bin/php-cgi
77948  -  I        0:00.08 | | |-- /usr/local/bin/php-cgi
78602  -  IW       0:00.00 | | `-- /usr/local/bin/php-cgi
58995  -  IWs      0:00.00 | `-- /usr/local/bin/php-cgi
41526  -  I        0:01.08 |   |-- /usr/local/bin/php-cgi
61971  -  IW       0:00.00 |   |-- /usr/local/bin/php-cgi
62633  -  I        0:00.82 |   |-- /usr/local/bin/php-cgi
63348  -  IW       0:00.00 |   |-- /usr/local/bin/php-cgi
64227  -  I        0:00.84 |   |-- /usr/local/bin/php-cgi
66393  -  IW       0:00.00 |   |-- /usr/local/bin/php-cgi
67542  -  I        0:00.85 |   |-- /usr/local/bin/php-cgi
67851  -  IW       0:00.00 |   |-- /usr/local/bin/php-cgi
69121  -  I        0:00.05 |   |-- /usr/local/bin/php-cgi
69628  -  IW       0:00.00 |   |-- /usr/local/bin/php-cgi
71020  -  IW       0:00.00 |   |-- /usr/local/bin/php-cgi
71625  -  IW       0:00.00 |   |-- /usr/local/bin/php-cgi
72742  -  IW       0:00.00 |   |-- /usr/local/bin/php-cgi
73963  -  IW       0:00.00 |   |-- /usr/local/bin/php-cgi
74396  -  IW       0:00.00 |   |-- /usr/local/bin/php-cgi
75545  -  IW       0:00.00 |   |-- /usr/local/bin/php-cgi
75857  -  IW       0:00.00 |   |-- /usr/local/bin/php-cgi
76497  -  IW       0:00.00 |   |-- /usr/local/bin/php-cgi
78028  -  IW       0:00.00 |   |-- /usr/local/bin/php-cgi
78145  -  IW       0:00.00 |   `-- /usr/local/bin/php-cgi
root@casa:/var/log/system # 


I have 3 internet links (1 PPPoE, 2 gigabit ethernet) and one local link (to another office).

**Comment by AdSchellevis** [comment]
without the grep might be better in this case, the number of php processes isn't really out of the ordinary.
