### ISSUE TITLE
Logging Severity incorrect - Google Drive backup.

### ISSUE THREAD

**Issue by bucker00** [opnsense/core#7427]
- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

Each night when Google Drive backup runs, or I back it up manually to Google Drive the backup completes successfully.
In System/Logfiles/General this gets logged each time:
backup configuration as <hostname>-1714404135.xml which is great, but it has a severity of ERROR when no error occurred.

**To Reproduce**

Backup the system configuration to Google Drive. 
Go to System/Logfiles/General and the action will be logged as an error even when a successful backup has happened.

**Expected behavior**

I would have expected the Severity of this event to be Notice rather than Error.

Software &  hardware:

OPNsense 24.1.6 (amd64).
Intel(R) Core(TM) i3-10110U CPU @ 2.10GHz (2 cores, 4 threads)
Protectli VP4630.

**Comment by fichtner** [comment]
@bucker00 thanks I found two that would be better to send as notice: eea9c5c58e
