### ISSUE TITLE
Create Alias function not working on DNS Lookup page.

### ISSUE THREAD

**Issue by alisamar** [opnsense/core#743]
Create Alias is a handy feature but it does not quite work on v15.7.25

![opnsense-dnslookup](https://cloud.githubusercontent.com/assets/4459630/12807305/f3b8e6b2-cb16-11e5-8583-9e6835bb234c.gif)

**Comment by AdSchellevis** [comment]
In 16.1 we dropped that feature, it just wasn't worth the effort of fixing it decently.

**Comment by alisamar** [comment]
Oh I get it, but this is a handy feature... Obviously I'd like to use it.

**Comment by AdSchellevis** [comment]
Just to be sure, you know you can use hostnames in aliases using the host(s) type which will also be periodical updated?
