### ISSUE TITLE
Captive Portal not redirected to login page since using KEA-DHCP

### ISSUE THREAD

**Issue by migro3466** [opnsense/core#7430]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

Problem:
When using new KEA-DHCP insted of ISC-DHCP together with Captive Portal I'm not redirected to the login page of CP to authenticate user. IP adresses are correctly assigned.

Software version used:
OPNsense 24.1.6-amd64

**Comment by AdSchellevis** [comment]
The question is what did you send to the cient when using ISC (`/var/dhcpd/etc/dhcpd.conf`), if option 114 was set (https://kea.readthedocs.io/en/latest/arm/dhcp4-srv.html#id3), we can change this to a feature request to add `v4-captive-portal`.

**Comment by migro3466** [comment]
It's been a while since I configured Captive Portal. I use the standard settings in Captive Portal, I only entered the IP address of the dhcp server under hostname, otherwise I will not be redirected to the login page even with ISC. The dhp.conf file was not changed manually, so I assume that option 144 was not set.

**Comment by AdSchellevis** [comment]
it might be worth the effort to try isc first then, looking at configs, I don't think the defaults are very different.
