### ISSUE TITLE
Changing an interface assignment does less than is expected

### ISSUE THREAD

**Issue by meyergru** [opnsense/core#7432]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

I wanted to use another physical interface for a certain VLAN and used the "assign interfaces" dialog to do this.
Later, I found out that the logical interface was assigned to the new pyhsical interface, but since the old static IP assignment was not removed from the old interface, the interface had no IP assigned at all.

Because of this, I lost connection to the VLAN/subnet and could not complete the task.

**To Reproduce**

1. For example, if you have ixl1_vlan6 as "MGMT" interface with IP assignment 192.168.6.2/24.
2. You reassign MGMT to use ixl1 instead of ixl1_vlan6.
3. What you get is that the old ixl1_vlan6 is still using 192.168.6.2/24, thus MGMT/ixl1 has no IP at all.
4. You would need to reboot to have the correct assignments made.

**Expected behavior**

When an assigment takes place, it should transfer all the IP assignments with it.

**Describe alternatives you considered**

One could reboot, however, I did not expect this to happen since the UI shows the wanted target configuration.

**Screenshots**

-

**Relevant log files**

-

**Additional context**

I needed to reassign the management VLAN and this bug rendered me without network connectivity (the Unifi controller could not communicate with the switches and APs any more). Took me hours to get it fixed.
**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 24.1.6 (amd64)

**Comment by AdSchellevis** [comment]
Probably best to inspect the system log after such an event, just reassigning a single interface doesn't seem to cause issues on my end, it could also be something driver related (in which case failed ifconfig commands might be logged). 

I have seen some issues in the past, we did change quite a bit in this area, but there might still be hard to catch edge-cases, following the steps in the ticket doesn't automatically seem to cause the same issue.

**Comment by meyergru** [comment]
I tried this on a VM instance and could not reproduce it, either. I tried to model the circumstances, i.e. there were multiple VLANs on the physical interface present and I moved just one to the parent. However, alas, I could not trigger the problem again.

During the test, I suspected that the real name could have been the culprit, since I had "old" VLAN names. To model this, I edited a saved config.xml to replace vlan01 by vtnet2_vlan8. I then restored that config - without reboot. Interestingly enough, the VLAN interface name stayed at vlan01. Only a reboot would show a working rename.

**Comment by AdSchellevis** [comment]
renaming vlan0.xx to igb1_vlanxx (no need to edit the config, both are allowed) and switching a couple times in the assignments page on my end works like a charm. my suspicion remains a hard lock somewhere (driver/kernel), but without a way to reproduce it's near to impossible to improve anything here.

**Comment by meyergru** [comment]
I know, you are right. Let's close this for now, may someone else stumbles upon it and can reproduce.
