### ISSUE TITLE
Wireguard Peer Generator - Improvements for better user experience

### ISSUE THREAD

**Issue by stavros-k** [opnsense/core#7439]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

---

**Is your feature request related to a problem? Please describe.**

A clear and concise description of what the problem is including your motivation for the request,
i.e. "For the purpose of [...] I am missing a solution that will [...]."

Bellow I'm summing some ideas I have. Browsing other issues to see if mine was duplicates. I found couple others scattered, and I thought it would be nice to sum them up here.

---

**Describe the solution you like**

- [x] Validate the `Endpoint` that it has a port (otherwise wireguard app says invalid QR) https://github.com/opnsense/core/commit/3f6b9ec4f970a1f038f6fb7a26303af22ec181fc
- [ ] Allow the usage of alias (networks) in the `Allowed IPs` field
- [ ] `Allowed IPs` should be "chip" (see image) entries and then joined by comma on the config  
  ![image](https://github.com/opnsense/core/assets/47820033/7f9ebe04-c905-4da3-9b64-c2806d2313ac)
- [ ] Besides the QR, it would be nice to have a `Download config` button (https://github.com/opnsense/core/issues/7360)
- [ ] `Allowed IPs` should be "saved" when clicking `Store and generate next` (https://github.com/opnsense/core/issues/7359#issuecomment-2039107632)
- [ ] `Keepalive` should be "saved" when clicking `Store and generate next` 

---

**Describe alternatives you considered**

A clear and concise description of any alternative solutions or features you considered.

**Additional context**

Add any other context or screenshots about the feature request here or links to relevant forum thread or similar

**Comment by Ramalama2** [comment]
The peer generator is amazing!

I miss actually only any way to set "Defaults".
-> Like "Start from IP" -> I usually leave the first 5 or 10 Peer IP's free, for any Case when i need an S2S Tunnel. So the users start from .11
-> "Allowed IP's" -> To set default "allowed IP's"
-> "Preshared" -> True/False, so you don't need to clieck the generate button
-> "Endpoint" -> To allow a hostname
-> "DNS Servers" -> If you want to use different ones.

No matter if this yould be realized through a Config Template File, or through the GUI, but this would be awesome, so i would need to put in just the Username :-)
And Surely a Config Download Button either :-)

Thanks :-)
