### ISSUE TITLE
CaptivePortal doesn't log anything

### ISSUE THREAD

**Issue by Mad-Onion** [opnsense/core#744]
Hi everyone,

I'm testing the captive portal of version OPNsense 16.1.1 but I'm not receiving cp-log-entries at all - neither via syslog nor as local logfile ("File /var/log/portalauth.log yielded no results.").

Best regards
Tobias

**Comment by AdSchellevis** [comment]
Hi Tobias,

The portalauth log file is a bit of a left over from the old code, it logs all local4 messages from syslog (which isn't only from captive portal).
All service related actions are logged into system.log at the moment, may we should filter the captive portal ones out of there and use portalauth exclusively for captiveportal.

User logins aren't logged at the moment, I will look into that.

Regards,

Ad

**Comment by AdSchellevis** [comment]
Added logging and changed syslog in commits https://github.com/opnsense/core/commit/9b6dc9535ccb1d8ea1d01fac6cc4e61b6f71b823 https://github.com/opnsense/core/commit/181215b2677e3ad77c5f00fc53b086da1b1db97e https://github.com/opnsense/core/commit/e1d6a690e78014a1e0db97ef5ae970a043d72391

 I've asked @fichtner to add this into tomorrows release

**Comment by fichtner** [comment]
Backported into 16.1.2 as d49d6b0e28fc652604
