### ISSUE TITLE
SNMP-Support for OpenVPN instances

### ISSUE THREAD

**Issue by cs-1** [opnsense/core#7441]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**

Right now there's no method to monitor OpenVPN instance usage (users, tx/rx volume etc.) via SNMP. This would be very helpful in bigger installations to manage resources.

**Describe the solution you like**

It would be great to either implement AgentX support for OpenVPN (there's a repo which implements this: https://github.com/Phhere/openvpn-snmp) or to integrate it as a UCD configuration into Net-SNMP. The latter would allow to simply parse an OpenVPN status file which can be enabled via the "status" directive in the OpenVPN configuration. Since this issue is more OpenVPN centric (enabling AgentX support or enabling the status file) I opened the issue here in the core repo.

**Describe alternatives you considered**

There're no better alternatives that I'm aware of.

**Additional context**

N/N

**Comment by fichtner** [comment]
The code you reference was last updated 9 years ago. I don’t want to get any hopes up here. It neither looks fitting for core scope nor is there a maintainable way forward. Net-snmp has been superseded by an array of modern monitoring tools which all are actively maintained and might even offer openvpn support already.
