### ISSUE TITLE
IP-over-Infiniband Initial Support in MVC - team preferences

### ISSUE THREAD

**Issue by rileyg98** [opnsense/core#7442]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**

As per some earlier discussions on the tools repo, I've been looking into getting Infiniband support into better shape. I'd like to ideally have it supported on the GUI and that requires support in the MVC. Even things as simple as MAC addresses are not correctly processed by the current interfaces code in configd. 

I wanted to get the opinion of the core team on how best to approach these fixes, as it seems even my MAC address example - where IPoIB MAC addresses are 20 bytes, with 12 bytes of config data before an 8 byte GUID, which is used as the MAC address in the Ethernet-over-Infiniband mode - the failure to show a MAC address is due to netstat's address for the link being capped at 40 characters, even in the JSON format. 

I am quite happy to work on adding support myself but don't want to do the work only to find it may be done in an inappropriate fashion for the code standards.

**Describe the solution you like**

There are multiple approaches to fixing these issues and I wanted to know if the core team preferred that I look at fixing the underlying tools in the src and ports trees, or if an appropriate solution would be to, for the MAC example, add a Python script to replace the [show.interfaces] command and inject the correct GUID for any IPoIB interfaces. 

The issue with modifying the underlying tools is, well, for netstat(1) at least, it's old. A lot of the code hasn't changed in 20 years and that was either when FreeBSD initially forked, or when they added IPv6 support.

**Comment by AdSchellevis** [comment]
I don't have any Infiniband equipment on my end, but last time I looked at the kernel/base support for https://github.com/opnsense/core/issues/7025 I wasn't very hopeful this could be easily implemented to be honest.

The best way to get some progress is likely with baby steps, one issue at a time, explain what the current omission is and how you would (like to) solve that. For us this isn't a core priority and community time is limited (these large topics usually need funding), but having a look at small snippets from time to time might be doable.

**Comment by fichtner** [comment]
Variable MAC address length is a bit of an issue as it is pinned to Ethernet length for the most part, but since we mostly store and handle strings in PHP that could be eased into. The aim is to minimise code required to handle this.

I agree with @AdSchellevis on the baby steps. Maybe set up a first goal for diagnostics and getting hard errors out of the way that prevent using the hardware and then it's relatively clear what the next steps will be.

Keep in mind we can help review and improve the PR submissions, but since this is undeniably only solved core but not a core mission we only have limited time available and no relevant hardware to double check (or even the time for double-checking in community scope).


Cheers,
Franco

**Comment by rileyg98** [comment]
Surprisingly now I've configured the subnet manager, there's no hard errors
preventing usage. It's really just enabling the right port types with a
kernel tunable, the rest auto configures itself.

I do understand you guys have no targets to do this on your end, of course.
I'm honestly only a random guy who wants IB support in a small cluster I'm
using for ML model training at home.

As it is, IPoIB works (and there's not really a need to show the full 20
byte MAC, only the 8 byte GUID is sufficient). That's honestly enough for
me at this point.

Feel free to close this. Anything beyond it working is very optional.


Riley
