### ISSUE TITLE
Hyperscan Now Proprietary

### ISSUE THREAD

**Issue by tomatotoast** [opnsense/core#7453]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [ x ] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [ x ] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**
Intel made hyperscan proprietary. So its unlikely that it will receive any updates in the future.

**Describe the solution you like**
Use the fork "vectorscan" instead:
https://github.com/VectorCamp/vectorscan

**Comment by AdSchellevis** [comment]
I don't expect we use hyperscan anywhere, except when being pulled in from other (upstream) projects (such as Suricata), this might not be the right place to ask for changes in these cases....

**Comment by fichtner** [comment]
Don’t mind leaving this open. The strange Redis project shift also hasn’t reached FreeBSD ports tree yet. So it will take a while. 😉
