### ISSUE TITLE
Unable to paste in to text input without replacing current value

### ISSUE THREAD

**Issue by victorhaggqvist** [opnsense/core#7456]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

Unable to paste value in to text input without replacing current value. Discovered trying to paste an addition to a Wiregurad peer name, but the form would not let me do so, only replacing the current name. Same behavior with both `ctrl+v` and `ctrl+shift+v`.

I'm fairly sure this used to work, and some investigation suggests that there is indeed something hijacking the paste now.

Some searching lead me to this probably being introduced in https://github.com/opnsense/core/issues/2217 and https://github.com/opnsense/core/commit/388d99cf6f4ab8387fb463e2e18584c7c2fce982.

**To Reproduce**

1. Go to Wiregurad
2. Click edit a current peer
3. Attempt to paste an _addition_ to any text input field
4. See error: observe current value being replaced by clipborad, even when no text was selected

**Expected behavior**

Clipborad value pasted at cursor in text input

**Describe alternatives you considered**

As mentioned in the commit that adds this, but maybe not in the way it was considered;
 
> There is a small risk the current selector is actuall too wide

This is probably one kind of "too wide", not as in html-selector necessarily, but maybe being a bit too trigger-happy all over the place.

Consider not interfering with `ctrl+shift+v` and/or consider only applying this essentially force-replace behavior on inputs where which has been more vetted to "makes sense" (however that may be defined). Currently, while well-intentioned, it overdoes it a bit when there appears to be no way to escape hatch it to "make it just paste".

**Screenshots**
Screenshot of paste-hijacking listener
![screen-2024-05-12_21:40:47](https://github.com/opnsense/core/assets/1887628/b99238d3-6767-4878-81b0-a5c787eb8de1)

**Environment**

Software version used and hardware type if relevant, e.g.:
OPNsense 24.1.6-amd64
FreeBSD 13.2-RELEASE-p11
OpenSSL 3.0.13

**Comment by AdSchellevis** [comment]
@victorhaggqvist I agree the previous commit is too aggressive,  https://github.com/opnsense/core/commit/2e010a77deef8a8decfb559660e892e702426be7 is probably better as it trims the clipboard data and re-injects it into the insert. Can you test and confirm? Thanks

**Comment by victorhaggqvist** [comment]
Tested, can confirm, that should resolve/unbreak basic paste and resolve the immediate issue.

**Comment by AdSchellevis** [comment]
@victorhaggqvist thanks for confirming!
