### ISSUE TITLE
allow use of aliases in `system > settings > general > dns servers` and other dns server input locations

### ISSUE THREAD

**Issue by BPplays** [opnsense/core#7464]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**

i use local dns servers that aren't opnsense and i would like to be able to point to those over ipv6 with an alias using type Dynamic IPv6 Host

**Describe the solution you like**

the ability to chose aliases instead of just ip addresses in cases where you can add dns servers

**Comment by fichtner** [comment]
Unless the alias system is extended to force all kinds of restrictions on downstream users of individual aliases the alias system will be no fun at all. For example here we'd have to restrict alias use to a specific type and up to 8 entries? I'm not convinced this is a significant ease of use and will yield further complaints down the road.

**Comment by BPplays** [comment]
@fichtner if aliases won't work that's fine but it would still be nice to have some way to have an ipv6 address with a dynamic prefix as a dns server, this would also be nice for Unbound DNS Overrides
