### ISSUE TITLE
WireGuard Peer generator Endpoint field does not accept valid hostname

### ISSUE THREAD

**Issue by Captain-Chaos** [opnsense/core#7472]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

The WireGuard Peer generator Endpoint field does not accept the value `24-109-132-185.internet.netrebel.net:58832`. It says: ""24-109-132-185.internet.netrebel.net:58832" is invalid. Please specify a valid host:port combination.", even though that value _is_ a valid such combination.

My suspicion is that it does not like the minus signs, even though those are allowed in hostnames. It does accept `185.132.109.24:58832`.

Version information:

OPNsense 24.1.7-amd64
FreeBSD 13.2-RELEASE-p11
OpenSSL 3.0.13

This is the first version of OPNsense I have tried, so I don't know if it worked in previous versions and if so which.

**To Reproduce**

1. Go to https://\<hostname>/ui/wireguard/general#configbuilder
2. Enter the value `24-109-132-185.internet.netrebel.net:58832` in the Endpoint field (fill the other fields with valid values as needed)
3. Hit the store button

**Expected behavior**

A new peer should be created with the specified configuration.

**Describe alternatives you considered**

Specifying the IP address instead of the hostname does work.

**Environment**

Software version used and hardware type if relevant, e.g.:

This is on a Protectli Vault. CPU: Intel(R) Celeron(R) CPU J3160 @ 1.60GHz (4 cores, 4 threads)

**Comment by AdSchellevis** [comment]
it looks like I forgot a spot there, https://github.com/opnsense/core/commit/b1b5971b7967d547db63ab469b1de4d3d1871a45 adds hostnames as valid options as well.

**Comment by Captain-Chaos** [comment]
That was quick! Thanks. 👍
