### ISSUE TITLE
OPNsense 24.7 - OpenVPN breakage due to DCO being enabled by default

### ISSUE THREAD

**Issue by AdSchellevis** [opnsense/core#7474]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

When using FreeBSD 14.1, our OpenVPN seems to misbehave as DCO is enabled by default. To lower the risk at upgrades, we likely should disable DCO by default and try to figure out why it breaks next. 

**Suggested workaround**

Toggle `--disable-dco` by default on our end. (https://openvpn.net/community-resources/reference-manual-for-openvpn-2-6/)

**Comment by NielsPiersma** [comment]
Please disable DCO. DCO is not supported for /30 networks.

**Comment by AdSchellevis** [comment]
@NielsPiersma for 24.7 it will be optional, we're certainly not automatically going to migrate tun setups to dco ones knowing the constraints that apply (https://community.openvpn.net/openvpn/wiki/DataChannelOffload/Features , https://github.com/OpenVPN/openvpn/blob/master/README.dco.md )
