### ISSUE TITLE
Ports alias saves but doesn't load: Unavailable for firewall rule creation

### ISSUE THREAD

**Issue by Oinkweil** [opnsense/core#7476]
**Describe the bug**

I created an alias containing individual ports. After saving the alias, no number appears under "Loaded#" and the new alias isn't available in source/destination when creating firewall rules. 

To test further I created a second alias with one port only, which also fails to load as above.

**Expected behavior**

Alias is created with entries enumerated on Aliases page. The alias is available under source/destination when creating firewall rules.

Software version used and hardware type if relevant, e.g.:

OPNsense 24.1.7-amd64

**Comment by AdSchellevis** [comment]
documentation doesn't seem to be clear on the subject, added it in https://github.com/opnsense/docs/commit/7d0a7e45d430aa8ab4088584391c48f3e91300ff
