### ISSUE TITLE
[Feature Request] Allow custom Cron commands

### ISSUE THREAD

**Issue by browne-net** [opnsense/core#7482]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**

Not a problem in particular but it would surely be beneficial having this possibility.

**Describe the solution you like**

It would be good if we could add custom cron commands in the Cron GUI (System: Settings: Cron) instead of only using the preconfigured / plugin generated ones.

This can be useful for a number of things
- workaround bugs until a fix arrives
- restarting services that are otherwise not available
- issuing other commands
- ...

**Describe alternatives you considered**

Not possible.

**Additional context**

As an example right now the DHCP relay is broken (https://github.com/opnsense/core/issues/7471) which could be worked around by restarting `dhcrelay` every minute or so. Surely this is not perfect by any means regarding this specific issue but it seems to help recover the functionality at least for a short period of time.

**Comment by fichtner** [comment]
https://docs.opnsense.org/development/backend/configd.html

See "description" property of the commands.

The command to invoke is `pluginctl dhcrelay`

**Comment by browne-net** [comment]
Sure I understand and know that we can do this by adding files to the system environment. However, direct GUI support for this would probably be a lot easier for most people.

So my "Feature Request" is more of an usability idea than a request.

**Comment by feld** [comment]
If we add custom cron jobs via this configd method will they be properly backed up and restored?

**Comment by fichtner** [comment]
@feld can you specify "this configd method"? File based drop ins are not handled by configuration, they are supposed to be local or done by plugins.
