### ISSUE TITLE
System: Gateways: Configuration - non "far" route creating a host route

### ISSUE THREAD

**Issue by AdSchellevis** [opnsense/core#7483]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

When a gateway is added, but the interface is either not initialized or the supplied address is out of range, a host route will always be created (even when far is not selected).

**To Reproduce**

1. Go to System: Gateways: Configuration
2. Add a new gateway on "lan" with all default settings (no upstream) and gateway address 1.2.3.4
3. hit apply
4. check routes via `System: Routes: Status` and witness `1.2.3.4` at the link

**Expected behavior**

Only a host route when "far" is selected.

**Describe alternatives you considered**

none

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 24.1.7 (amd64).

**Comment by fichtner** [comment]
Ok nice catch 👍
