### ISSUE TITLE
OPNsense 24.7 - support unicast CARP announcements

### ISSUE THREAD

**Issue by AdSchellevis** [opnsense/core#7486]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**

FreeBSD 14.x support unicast carp announcements, which would be practical to offer in our gui as well.  

**Describe the solution you like**

Add optional `peer` and `peer6` values in `Interfaces: Virtual IPs: Settings` for carp type interfaces. 

**Describe alternatives you considered**

none

**Additional context**

https://man.freebsd.org/cgi/man.cgi?carp

* add a note in the docs about source selection (https://github.com/opnsense/src/blob/dc96e48a8d362b6db096560cf93cce98fa7fc25c/sys/netinet/ip_carp.c#L923-L924), `ifa_preferred()` seems just to select the first address which might be problematic when using unicast

**Comment by Monviech** [comment]
Nice, this saves a lot of headache when switches use igmp snooping or multicast storm protection.
