### ISSUE TITLE
Automatically populate IP address field when creating an IP reservation in the DHCP leases

### ISSUE THREAD

**Issue by lennon101** [opnsense/core#7489]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**

When I click on the plus symbol on a DHCP lease to reserve it, the IP address (that has already been assigned to it by DHCP) isn't being populated in the next page. I have to either copy it or remember it before clicking the ➕ button. Is that a bug or some sort of strange design decision?

**Describe the solution you like**

Automatically populate IP address field when creating an IP reservation in the DHCP leases

**Describe alternatives you considered**

N/A

**Additional context**

I don't see an issue with reserving an IP inside the DHCP pool range. Especially if the IP has already been assigned by the DHCP, I can be sure there isn't going to be an IP address conflict. I know there is potential for other issues like network performance and configuration errors particularly in large networks, but in this context (my home network with only a few devices) I don't see an issue

**Comment by fichtner** [comment]
> I don't see an issue with reserving an IP inside the DHCP pool range.

Nice try but you are wrong. We did follow this suggestion in the past and it caused a lot of users annoying problems because this assumption is wrong.


Cheers,
Franco
