### ISSUE TITLE
Newer generated core package can't be installed

### ISSUE THREAD

**Issue by oparoz** [opnsense/core#749]
I've created an updated core package using the tools provided, but it can't be installed.
```
# pkg add 16.1.2/All/opnsense-16.1.2.txz
Installing opnsense-16.1.2...
the most recent version of opnsense-16.1.1 is already installed
```

I've checked the manifest and it seems OK

`{"name":"opnsense","origin":"opnsense/opnsense","version":"16.1.2","comment":"OPNsense release package",...`

**Comment by fichtner** [comment]
Use the force: pkg add -f

**Comment by oparoz** [comment]
That worked. There must be something in the package which says it's 16.1.1 patch xxx instead of 16.1.2 though, but I couldn't grep it.

**Comment by fichtner** [comment]
Pkg-add as well as pkg-install have no notion of upgrade, this is working as intended

**Comment by oparoz** [comment]
Ah, would pkg upgrade have worked then?

**Comment by fichtner** [comment]
No, add works on files, install on repos and upgrades on repos (files can't know where updates are)
