### ISSUE TITLE
openvpn error in log after reboot

### ISSUE THREAD

**Issue by StopTrain** [opnsense/core#75]
Found this tonight after working with fitch on IRC on the 15.1.7 stuff.

openvpn[49220]: ERROR: FreeBSD route add command failed: external program exited with error status: 1

fitch believes this is a failed route add because the route being added already exists.

**Comment by fichtner** [comment]
This coming from OpenVPN itself makes me think we can't do anything here. Ok to close? Any side effects?

**Comment by AdSchellevis** [comment]
Let's close it.
