### ISSUE TITLE
[FR] Apply selected action in Intrusion Detection without having to restart Suricata

### ISSUE THREAD

**Issue by oparoz** [opnsense/core#750]
I have set one rule to drop packets and in the Action column, I see it's set to "drop", but in my *Alerts* logs, I keep seeing alerts related to that rule and the action is shown as "allowed".

**Comment by AdSchellevis** [comment]
Have you applied your changes? 
If so, can you check the generated rule in /usr/local/etc/suricata/rules/?
It should state drop for the sid you changed.

**Comment by oparoz** [comment]
I had not restarted (and I hope "apply" only does a reload), but it didn't change anything.
I've checked the rule and it's set to *alert* even though the GUI says it's set to *Drop*

**Comment by oparoz** [comment]
I've manually updated the rule and the request is now blocked, so that's a relief that Suricata doesn't need to be restarted.
The problem remains though.

I have /tmp and /var in RAM if that makes any difference.

**Comment by AdSchellevis** [comment]
The temp filesystem could be the difference here, the ids package really needs access to /usr/local/etc/suricata  in order to generate its ruleset... maybe more of your recent logged issues are related to the same thing.

**Comment by oparoz** [comment]
Well, `/usr/local/etc/suricata` is not on tmpfs, so it shouldn't be a problem.

Here is what's strange.

There are 2 almost identical folders:
* `/usr/local/etc/suricata/opnsense.rules/`. Making modifications to these rule take effect
* `/usr/local/etc/suricata/rules/` contains a rules.sqlite files which is probably used for the GUI. When changing the action a locked version is created, but never deleted. It just remains there at 0 bytes

**Comment by AdSchellevis** [comment]
The lock is supposed to be there, generating the sqlite db may only be executed from one worker at the same time, its using the lock to guarantee that.
```
/usr/local/etc/suricata/opnsense.rules/ 
```
contains the running ruleset (possibly changed by the user)

details from the suricata config:
```
/usr/local/etc/suricata/suricata.yaml:default-rule-path: /usr/local/etc/suricata/opnsense.rules
```

The downloaded (original, possibly only changed by import filter) ruleset:
```
/usr/local/etc/suricata/rules/ 
```

**Comment by oparoz** [comment]
Thanks. 
Why is the sqlite db in `rules` and not in `opnsense.rules` since that's where the running rules are?

Every time I make a change, the DB is updated, but rules are not touched.

**Comment by AdSchellevis** [comment]
Because the sqlite file is only for internal use, and we try to avoid suricata to read its contents.

**Comment by oparoz** [comment]
OK, so the main problem remains. The DB is updated, but rules aren't. Maybe a permission issue if it's a different process modifying the rules.

**Comment by AdSchellevis** [comment]
This installs the rules into the correct location (from the command line):
```
configctl ids install rules
```

Which is triggered upon reconfigure https://github.com/opnsense/core/blob/master/src/opnsense/mvc/app/controllers/OPNsense/IDS/Api/ServiceController.php#L121-L172
specifically:
https://github.com/opnsense/core/blob/master/src/opnsense/mvc/app/controllers/OPNsense/IDS/Api/ServiceController.php#L153

**Comment by oparoz** [comment]
I don't understand how the ServiceController gets involved and on top of that Suricata doesn't need to be restarted, so reconfigureAction() should not be called when simply changing the action in rules.

When changing an action, the request lands in the SettingsController
https://github.com/opnsense/core/blob/master/src/opnsense/mvc/app/controllers/OPNsense/IDS/Api/SettingsController.php#L419-L447

The rule is retrieved, a call to setAction is made, but I think this only modifies the cache (sqlite DB). I don't see where the change is actually committed to the filesystem.

**Comment by AdSchellevis** [comment]
changing a rule **only** updates the config.xml, you need to apply before anything will be changed in suricata.

The process is very simple:

setAction updates the model -> validates -> saves to config.xml
"Apply" (in the form) calls the setter for the general settings and performs reconfigureAction, which generates your ruleset.

**Comment by oparoz** [comment]
OK, so just tested with *Apply* and it does work, the opnsense.rules are updated (I must have checked the rules folder in my previous attempts), but it's a really bad UX. Restarting Suricata kills all connections for a long time. This can't happen every time rules need to be modified, especially since it seems to be unnecessary. My `eve.json` contains the log and I can see packets being dropped after I've manually edited the rule, without a restart.

**Comment by AdSchellevis** [comment]
We could move the buttons for apply and download into the general tab and add an apply button to the rules tab, which does approx the same trick as download/update.

**Comment by oparoz** [comment]
That sounds good, especially if you can re-use that update method. I'm not yet familiar with the system, but it looks like it would require a new configd action as "ids update" would also download the rules.

**Comment by AdSchellevis** [comment]
This should to the trick:
https://github.com/opnsense/core/commit/54f0787c23101dd5dbeb0e6fe5773836ca943836
https://github.com/opnsense/core/commit/492a75184f569c2cd5ea0bedde26ba92764d27bd
https://github.com/opnsense/core/commit/1e1aae8b575b4a6be390d16a06608e0e3d56f312

Close this issue?

**Comment by oparoz** [comment]
Many thanks. I'll give it a go tonight to see if it works as expected.

**Comment by oparoz** [comment]
OK, so I think it works. The reason I'm not sure is that if I do
`# configctl ids query rules 1 0 sid/2000006`
then it says `"action":"alert"`, but if I look at the opnsense.rules, then it's set to drop.

I would also change the submit text on the button from *Update* to *Apply changes* or just *Apply* and maybe the help text next to the action dropdown in the modal window could include some information, letting users know they have to apply the changes for them to take effect.

**Comment by AdSchellevis** [comment]
The configctl command returns the rule from the original source (after pre filtering), without additions of your config.xml. The mvc/middleware framework handles the config interaction, so the UI should display the corect value.
So it looks good.
Will rename the button and close the issue.
