### ISSUE TITLE
IPsec logs always blank

### ISSUE THREAD

**Issue by zyphlar** [opnsense/core#7504]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

Despite finding IPsec log settings under VPN > IPsec > Advanced Settings (which was non-obvious, some of these menus could use reordering/renaming/cleanup and some features more prominently cross-linked to each other) the VPN > IPsec > Log File entry is totally blank.

Interestingly, the Firewall > Log Files > General view is similarly blank even though the Live, Overview, and Plain Views have data. I wonder if this logging facility is broken somehow. A firefox network inspector shows a POST being received just fine, it just produces `rows: []` (empty response) for both `api/diagnostics/log/core/ipsec` and `api/diagnostics/log/core/firewall`

**To Reproduce**

- Enable normal IPsec and Firewall things, including IPsec debug settings.
- Restart the IPsec service even though that shouldn't be necessary (should be part of changing debug settings)
- Try to view IPsec logs, notice they are blank

**Expected behavior**

IPsec logs should not be blank, especially with debug log levels turned on.

**Describe alternatives you considered**

Screaming into the void, etc

**Environment**

OPNsense 24.1.8-amd64
FreeBSD 13.2-RELEASE-p11
OpenSSL 3.0.13

AMD GX-412TC SOC (4 cores, 4 threads)

PCEngines APU2

**Comment by AdSchellevis** [comment]
right top corner, log level selector

**Comment by zyphlar** [comment]
Ahh, that did it. So I've been managing IPsec VPNs with PFsense/etc since ~2010, I think it's safe to say that most people who haven't figured out not only the log level controls but also the log level filters is going to just give up rather than make a Github ticket (I'm a feisty one, and also happen to also live on Github all day in my new job as a web dev)

Some suggestions to prevent future dismay:

- Link to or hint at IPsec log level settings inside the Connections, Legacy IPSec Tunnel, and other control panels
- Rename or hint at "Advanced Settings" containing log details
- If a restart is necessary for debug settings (idk if it is) specify that, prompt for a restart, or just automatically restart
- If a table in the GUI (like these log tables) returns no data, modify the message to say "No results found! If you expect data here, <a href="#">adjust the displayed log levels</a>"
- I was battling a failing IPsec tunnel with mismatched ciphers and peer identifiers, that's not a warning or higher?
- The IPsec Status Overview consistently said ":arrow_forward: Connected" even when it wasn't due to the aforementioned mismatches, making that more accurate or perhaps linking to a more detailed status would be helpful (I personally know better than to trust IPsec when it says everything's fine, but that's because it was my hellish job for a long time, most people expect things to only be green when phase 1+2 are up *and passing traffic.*)

**Comment by AdSchellevis** [comment]
Sounds like case closed, there's always room for improvement, but how we handle logging in all parts of the system is pretty consistent, explaining the use better is more a documentation issue (maybe adding a paragraph in https://docs.opnsense.org/manual/gui.html).

**Comment by zyphlar** [comment]
I've gotten this far without reading the manual, not gonna start now ;)

Consider this a feature request, maybe I'll make a PR sometime in the future if I have time. The rest of the UI is mostly intuitive, minus this
