### ISSUE TITLE
Static IPv6 over PPPoE not working anymore

### ISSUE THREAD

**Issue by RoelVB** [opnsense/core#7508]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

I have a WAN interface that connects over PPPoE. My interface is configured to use PPPoE for IPv4 and a static address for IPv6.
At some point this stopped working and the PtP log started showing "[wan_link0] rec'd unexpected protocol IPV6CP, rejecting" whenever the interface connects.

After a lot of digging I'm sure [this commit](https://github.com/opnsense/core/commit/54cd32c49d1e38376438604e45ab3cfc065e5b65) by @fichtner introduced my issue.

**More info**
When I set my IPv6 type for my interface to `PPPoEv6` the before mentioned error in the PtP log disappears, but I wont have an IPv6 address because I have to assign it statically.

Would it be possible to work-around this in some way? For example:
1. Force `set bundle enable ipv6cp` into the mpd config?
2. Somehow set a static IPv6 address in PPPoEv6 mode?

**Comment by RoelVB** [comment]
I've manually reverted the mentioned commit by editing the `/usr/local/etc/inc/interfaces.inc` and that does solve my issue!

**Comment by fichtner** [comment]
Ok I see, Static IPv6 is not really suitable for PPPoE when ipv6p is required. That's exactly why PPPoEv6 was added. :)

**Comment by RoelVB** [comment]
Hi @fichtner 

Thank you very much for your prompt reply. You are right... I got it to work using PPPoEv6.
My ISP said I had to statically configure the IPv6 address, but now I'm thinking about this I don't see why. This put me on the wrong track.

Thanks again, and enjoy your evening.

**Comment by fichtner** [comment]
Well they are not wrong in requiring you to do a static setup but typically you do the static setup on the LAN side and the WAN address via PPPoEv6 is routable so it all works out ok.


Cheers,
Franco

**Comment by RoelVB** [comment]
Exactly, but they told me to setup an IP on both WAN and LAN

**Comment by fichtner** [comment]
Yes, fair enough. Let's give them some slack for delivering working IPv6. Static setups are a bit rare but great. 👍
