### ISSUE TITLE
Let users set the action mode from the Alerts tab

### ISSUE THREAD

**Issue by oparoz** [opnsense/core#752]
If an alert is identified as a threat, it should be possible for users to quickly change its state from "Alert" to "Drop". Instead, they currently have to
* make the window wide so that they can copy the full alert as there can be several rules starting the same
* copy the rule
* go to the *Rules* tab
* paste the rule in the search field
* open the rule

It could just be:
* open the rule from the *Alerts* tab

**Comment by AdSchellevis** [comment]
Ideally you should be able to open the same dialog as in the rules tab, maybe from a separate button in the same grid or some kind of link in the info dialog using the same service calls we already have. 
Let me think about this.
