### ISSUE TITLE
interfaces: DHCPv6 incoming requirements for random server origin port

### ISSUE THREAD

**Issue by antipiot** [opnsense/core#7527]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

My opnsense installation does not seems to use / apply the prefix delegated by my internet service provider router

**To Reproduce**

Setup IPV6 with DHCP on the router side: i have a/48 delegated
On Opnsense, enable DHCPv6 -  / Send IPv6 prefix hint / Prefix delegation size /57 (or whatever does the same) / Request only an IPv6 prefix
Check what is the delegated network using else:
 cat `ifctl -6 -l -p` or the system - route - status - and look for loopback addresses that match your ipv6 ip range.
- Nothing shows up.

**Expected behavior**

A network with the delegated subnet is applied / used by opnsense
The command and routes status show's and address that looks like 1:1:1:1000/52

**Describe alternatives you considered**

Tested on 2 similar installations (same provider / different bare metla hardware for opnsense) with opnsense v23 and v24 with the same behavior

**Relevant log files**

I've wiresharked the thing and it looks like the delagation is correctly sendt to opnsense:
![image](https://github.com/opnsense/core/assets/26579988/0f57a7d0-3fcb-4d28-bf20-0619ba2b054c)

**Other informations**
I've already deployed IPv6 with success with another internet provider.

**Environment**

opnsense bare metal 24.1.8

Thanks for any hint!

Regards

**Comment by fichtner** [comment]
Hi @antipiot,

I see your point, but no configuration or system output we can trace this by. There's also the ability to set debug log level for dhcp6c but for some reason I expect this to be configuration related.


Cheers,
Franco

**Comment by antipiot** [comment]
Hi @fichtner !

Thanks for your help. For sure it can be configuration related, but... where...

If i'm not mistaken the only needed configuration to get the delegation is on the interface settings. Thoses are my settings.
![image](https://github.com/opnsense/core/assets/26579988/de976816-83c1-4367-9575-6e8d954ef45d)

I've indeed played around here to try to find a sweet spot without luck. Is there anything elses i can try?

I will try to enable debug log level for DHCPv6

**Comment by antipiot** [comment]
it seems to want to use some vlan for a reason i dont understand...
I have no vlan on wan at all.

![image](https://github.com/opnsense/core/assets/26579988/9b8d7c80-adab-4a52-a94f-9240129af12a)

**Comment by antipiot** [comment]
In the logs for my interface i have this message:

2024-06-14T08:44:33 | Notice | dhcp6c | dhcp6c_script:  on igc1 ignored

**Comment by fichtner** [comment]
An empty `$REASON`? Looks like a good thing to ignore ;)

Your capture says Prefix length: 52, why do you try to set 55?

**Comment by antipiot** [comment]
@fichtner When requesting a 55 i have a /52 delegated, already tried to set to 52 without success.

**Comment by antipiot** [comment]
i do have the feeling it's ISP related, but how to prove / debug that

**Comment by antipiot** [comment]
> All of this rounds rather strange.
> 
> It's best to enable DHCPv6 debugging and reboot and then look for all the `dhcp6c` lines in System: Log Files: General to avoid speculation.

How to enable DHCPv6 debugging?

**Comment by antipiot** [comment]
@fichtner here's a part of what i have in logs

[dhcp.log](https://github.com/user-attachments/files/15837579/dhcp.log)

**Comment by fichtner** [comment]
That snippet already shows that nobody answers to the SOLICIT of dhcp6c.

**Comment by antipiot** [comment]
> That snippet already shows that nobody answers to the SOLICIT of dhcp6c.

Yes. does not looks like opnsense related.

**Comment by antipiot** [comment]
> That snippet already shows that nobody answers to the SOLICIT of dhcp6c.

But why is there a Advertise answer showing up there?

![image](https://github.com/opnsense/core/assets/26579988/2f85b54d-9955-4ca9-963c-b8a689da64f9)

**Comment by fichtner** [comment]
I have no idea where you capture or which machine replies. Relevant things are edited out, logs are partial and so far not a single ifconfig output to help get this some structure.

**Comment by antipiot** [comment]
> I have no idea where you capture or which machine replies. Relevant things are edited out, logs are partial and so far not a single ifconfig output to help get this some structure.

Thanks for your time @fichtner, really appreciate.

This was captures using "capture" of opnsense.

I'm sorry but you can perfectly identify the interfaces in thoses captures.
Logs are partiel because i was trying not to submerge with not relevent informations :)
The fact that the request was "timeouting" sounded sufficient to me, but if you telle me that you need the full log, i can surely provide it to you!

**Comment by antipiot** [comment]
In case one wants to manually trigger DHCP and get a bit of verbosity:

/usr/local/sbin/dhcp6c -dDfi igc1
```
Jun/18/2024 08:23:25: reset a timer on igc1, state=INIT, timeo=0, retrans=891
Jun/18/2024 08:23:26: Sending Information Request
Jun/18/2024 08:23:26: a new XID (7803ed) is generated
Jun/18/2024 08:23:26: set client ID (len 14)
Jun/18/2024 08:23:26: set elapsed time (len 2)
Jun/18/2024 08:23:26: send information request to ff02::1:2%igc1
Jun/18/2024 08:23:26: reset a timer on igc1, state=INFOREQ, timeo=0, retrans=991
Jun/18/2024 08:23:27: Sending Information Request
Jun/18/2024 08:23:27: set client ID (len 14)
Jun/18/2024 08:23:27: set elapsed time (len 2)
Jun/18/2024 08:23:27: send information request to ff02::1:2%igc1
Jun/18/2024 08:23:27: reset a timer on igc1, state=INFOREQ, timeo=1, retrans=1892
Jun/18/2024 08:23:29: Sending Information Request
Jun/18/2024 08:23:29: set client ID (len 14)
Jun/18/2024 08:23:29: set elapsed time (len 2)
Jun/18/2024 08:23:29: send information request to ff02::1:2%igc1
Jun/18/2024 08:23:29: reset a timer on igc1, state=INFOREQ, timeo=2, retrans=3617
Jun/18/2024 08:23:33: Sending Information Request
Jun/18/2024 08:23:33: set client ID (len 14)
Jun/18/2024 08:23:33: set elapsed time (len 2)
Jun/18/2024 08:23:33: send information request to ff02::1:2%igc1
Jun/18/2024 08:23:33: reset a timer on igc1, state=INFOREQ, timeo=3, retrans=7326
Jun/18/2024 08:23:40: Sending Information Request
Jun/18/2024 08:23:40: set client ID (len 14)
Jun/18/2024 08:23:40: set elapsed time (len 2)
Jun/18/2024 08:23:40: send information request to ff02::1:2%igc1
Jun/18/2024 08:23:40: reset a timer on igc1, state=INFOREQ, timeo=4, retrans=14830
Jun/18/2024 08:23:55: Sending Information Request
Jun/18/2024 08:23:55: set client ID (len 14)
Jun/18/2024 08:23:55: set elapsed time (len 2)
Jun/18/2024 08:23:55: send information request to ff02::1:2%igc1
Jun/18/2024 08:23:55: reset a timer on igc1, state=INFOREQ, timeo=5, retrans=29003
^CJun/18/2024 08:23:57: removing an event on igc1, state=INFOREQ
Jun/18/2024 08:23:57: exiting
```

**Comment by antipiot** [comment]
> I have no idea where you capture or which machine replies. Relevant things are edited out, logs are partial and so far not a single ifconfig output to help get this some structure.

Sorry i forgot the Ifconfig :) Here it is:

igc1: flags=8863<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500
        description: WAN (opt1)
        options=4e0232b<RXCSUM,TXCSUM,VLAN_MTU,JUMBO_MTU,TSO4,TSO6,WOL_MAGIC,RXCSUM_IPV6,TXCSUM_IPV6,NOMAP>
        ether MAC:c7:90
        inet6 fe80::227c:14ff:fef0:c790%igc1 prefixlen 64 scopeid 0x2
        inet MYIP4PUBLICIP netmask 0xfffffffc broadcast MYIP4PUBLICIPBroadcast
        media: Ethernet autoselect (1000baseT <full-duplex>)
        status: active
        nd6 options=23<PERFORMNUD,ACCEPT_RTADV,AUTO_LINKLOCAL>

**Comment by antipiot** [comment]
@fichtner 
Ok. i think i'm starting to understand Packets were blocked by firewall because they weren't send by port 546 
WAN |   | 2024-06-18T08:49:41 | [fe80:::79f3]:48457 | [fe80::c790]:546 | udp | Default deny / state violation rule

The router does not send the packet from the expected port

IPv6 UDP | fe80::/10 | 546 | fe80::/10 | 546 | * | * |   | allow dhcpv6 client in SwisscomWAN

I added a rule to allow this but i still get no confirmation. 

Is it possible that Opnsense wont use a dhcp message that is issued by another port than 546?

Regards

**Comment by fichtner** [comment]
@antipiot https://en.wikipedia.org/wiki/DHCPv6#Port_numbers

> Clients listen for DHCP messages on UDP port 546. Servers and relay agents listen for DHCP messages on UDP port 547.

If your ISP behaviour differs you need manual rules for sure.


Cheers,
Franco

**Comment by fichtner** [comment]
Then again, maybe we can loosen that requirement, but it's quite unusual.

**Comment by antipiot** [comment]
> @antipiot https://en.wikipedia.org/wiki/DHCPv6#Port_numbers
> 
> > Clients listen for DHCP messages on UDP port 546. Servers and relay agents listen for DHCP messages on UDP port 547.
> 
> If your ISP behaviour differs you need manual rules for sure.
> 
> Cheers, Franco

Yes, i do think that aswell. I'm trying to find the RFC for this.

I've tried to add a manual rule but it does not looks to be enough: can i try something else?

**Comment by fichtner** [comment]
You can edit the following, just remove the `from_port` specification

https://github.com/opnsense/core/blob/34cafe3e9835cb48c41ad063d2aba2700e7f701a/src/etc/inc/filter.lib.inc#L352

It's really odd this pins the port from 546 to 546, because you either have a server to client 547 -> 546 or client to server 546 yo 547.

**Comment by antipiot** [comment]
> You can edit the following, just remove the `from_port` specification
> 
> https://github.com/opnsense/core/blob/34cafe3e9835cb48c41ad063d2aba2700e7f701a/src/etc/inc/filter.lib.inc#L352
> 
> It's really odd this pins the port from 546 to 546, because you either have a server to client 547 -> 546 or client to server 546 -> 547.

Do you find, by any chances, the RFC that request the messages to be sent using either port 546 or 547? couldnt find this on the RFC 8415 -> https://datatracker.ietf.org/doc/html/rfc8415#page-24

That one specify the messages needs to be received on thoses ports as they are "listen" requirements

**Comment by fichtner** [comment]
I know the BPF filter in dhclient (IPv4) enforces the strict sending port, but the dhcp6c client may or may not.

The origin of this rule is https://github.com/pfsense/pfsense/commit/dbcddabcdf7e which gives no reference to what it tried to achieve. It has never been changed since.

**Comment by fichtner** [comment]
It would possibly make sense to condense this back into a single rule and relax the incoming server port. I'm not sure if everything is done over link-local but I kind of expect it is.

**Comment by fichtner** [comment]
(historically speaking that IPv6 stuff was probably just copied over from IPv4 filtering requirements)

**Comment by antipiot** [comment]
> It would possibly make sense to condense this back into a single rule and relax the incoming server port. I'm not sure if everything is done over link-local but I kind of expect it is.

It was from all my testings at least.

**Comment by antipiot** [comment]
> You can edit the following, just remove the `from_port` specification
> 
> https://github.com/opnsense/core/blob/34cafe3e9835cb48c41ad063d2aba2700e7f701a/src/etc/inc/filter.lib.inc#L352
> 
> It's really odd this pins the port from 546 to 546, because you either have a server to client 547 -> 546 or client to server 546 -> 547.

This edit does not seems to be sufficient, i'm still getting a "sollicit / advertise" loop.

**Comment by fichtner** [comment]
capture from the WAN port would help then... it's doing something right ;)

**Comment by fichtner** [comment]
This is what I have in mind, but I can't test before 24.1.9 is out in a bit... https://github.com/opnsense/core/commit/a3a5e7832

**Comment by antipiot** [comment]
> capture from the WAN port would help then... it's doing something right ;)

Rebooted everything aaaand -> 
![image](https://github.com/opnsense/core/assets/26579988/5f7389dd-d7dd-44fd-aa5c-227fd9a396e8)
 Hourrah

**Comment by fichtner** [comment]
Thanks for debugging. I'll test the patch, ask you to try it too (with a clean reboot) and then we will likely add it for 24.7 :)

**Comment by antipiot** [comment]
> Thanks for debugging. I'll test the patch, ask you to try it too (with a clean reboot) and then we will likely add it for 24.7 :)

Will do with pleasure. Thanks for the fix.

**Comment by fichtner** [comment]
Ok patch works fine on my end... to try from your end make sure you are on 23.1.9 (just came out) and apply the patch cleanly with the following commands:

    # opnsense-revert opnsense && opnsense-patch a3a5e78323


Cheers,
Franco

**Comment by antipiot** [comment]
> Ok patch works fine on my end... to try from your end make sure you are on 23.1.9 (just came out) and apply the patch cleanly with the following commands:
> 
> ```
> # opnsense-revert opnsense && opnsense-patch a3a5e78323
> ```
> 
> Cheers, Franco

Will do!
DId you thinked about adjusting the automatic firewall rule aswell?


> @fichtner Ok. i think i'm starting to understand Packets were blocked by firewall because they weren't send by port 546 WAN |   | 2024-06-18T08:49:41 | [fe80:::79f3]:48457 | [fe80::c790]:546 | udp | Default deny / state violation rule
> 
> The router does not send the packet from the expected port
> 
> IPv6 UDP | fe80::/10 | 546 | fe80::/10 | 546 | * | * |   | allow dhcpv6 client in WAN
> 
> I added a rule to allow this but i still get no confirmation.
> 
> Is it possible that Opnsense wont use a dhcp message that is issued by another port than 546?
> 
> Regards

**Comment by fichtner** [comment]
> DId you thinked about adjusting the automatic firewall rule aswell?

Wasn't that what we did with the patch? Not sure which other automatic rule you could mean.

**Comment by antipiot** [comment]
> > DId you thinked about adjusting the automatic firewall rule aswell?
> 
> Wasn't that what we did with the patch? Not sure which other automatic rule you could mean
Sorry i was mixing things up! 

Patched and had to restart all services - Looks OK
