### ISSUE TITLE
Unbound:  Make it easier to enable or disable blocklists

### ISSUE THREAD

**Issue by robled** [opnsense/core#7532]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**

With DNS adblocking it's common to want to temporarily disable all blocklists to access a website.  Other DNS adblocking solutions allow you to toggle the setting via the UI or API, or even just disable it for some time interval (e.g. 5 minutes to allow you to access a specific site for a quick task).

Currently it's cumbersome to have to log into the web UI and drill into the Unbound configuration to disable the blocklists.  It is possible to use the API to do this ([example](https://github.com/hibby50/opnsense-unbound-dnsbl-toggle/blob/main/webapp.py#L31)), but the API call not only requires the enable/disable boolean, but also the rest of the blocklist config, which means that you cannot easily use the API to do this without the risk of nuking the rest of your blocklist config.  

**Describe the solution you like**

An API call with a boolean enable/disable value which doesn't affect other blocklist configuration would be helpful.  Additionally, an option to disable the adblocking for some amount of time and then turn it back on again would be further useful.

Finally, the UI could support this as well via a quick dashboard button.  For example:

![PiHoleDisable_1](https://github.com/opnsense/core/assets/3211560/836d3537-e563-4de0-acf4-1ddd00c39db2)

**Describe alternatives you considered**

A clear and concise description of any alternative solutions or features you considered.

**Additional context**

Add any other context or screenshots about the feature request here or links to relevant forum thread or similar

**Comment by OrionPaxNL** [comment]
Please add this :)
