### ISSUE TITLE
Virtual IPv6 alias stop working on version 24.1.9

### ISSUE THREAD

**Issue by BeePerNet** [opnsense/core#7545]
I used an fd*/64 virtual ip alias on a LAN network interface. I cannot ping it anymore from lan computers when upgrading to version 24.1.9. The local network diagnostic ping works, but any ping from other computer to opnsense got destination unreachable error and I can't ping any other computer with that range from opnsense. I got weird firewall log showing that ::1 is trying to contact some other fd* network computers (my dns servers) and was block by the firewall. Why the server is using ::1, knowing that the destination range is using by one of is virtual ip, containing a mask of 64? I created a temporary rules to accept all everywhere and was unable to ping that ip or the opnsense server to contact my dns servers. I had to revert to 24.1.8 version. Note that all other ipv6 functionalities is working fine with IPv6 Prefix delegation from ISP and 2000::/3 addresses and all other stuff. Seems that the virtual ip is not added to the routing table anymore, but I'm no expert of your back-end. What I'm sure: some commit for 24.1.9 broke that functionality. I did not check/test virtual ipv4.

**Comment by fichtner** [comment]
> What I'm sure: some commit for 24.1.9 broke that functionality.

Or it was a fix and you relied on the broken behaviour. At first glance nothing stops an IPv6 from communicating to another IPv6.


Cheers,
Franco

**Comment by BeePerNet** [comment]
I'm not using some special stuff, just added an ipv6 address to an lan card with the virtual ip alias opnsense functionnality. I just saw another hotfix. So I upgraded to test it and I found that it was fixed by the _3 version.

**Comment by fichtner** [comment]
The hotfixes only pertain to one-to-one NAT.
