### ISSUE TITLE
Emtpy system.log

### ISSUE THREAD

**Issue by oparoz** [opnsense/core#755]
I'm not sure which change broke it, but I'm using the RAM disk and I've updated to 16.1.2 and system.log is always empty.
AFAICT the other logs get populated properly.

**Comment by AdSchellevis** [comment]
Just checked it on my end, this change seems to have caused it https://github.com/opnsense/core/commit/e1d6a690e78014a1e0db97ef5ae970a043d72391#diff-460dfc2bc3262765b55473c6f9b38003

If you revert this you will have a log again, not sure what the proper change is yet.

**Comment by oparoz** [comment]
Confirmed as fixed.
