### ISSUE TITLE
Feature:  Custom DHCP/BOOTP options for Kea DHCP

### ISSUE THREAD

**Issue by Codelica** [opnsense/core#7550]
- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**

In migrating from ISC DHCP to Kea DCHP one feature is still missing for me -- the ability to add custom DHCP/BOOTP options. (As defined [here](https://www.iana.org/assignments/bootp-dhcp-parameters/bootp-dhcp-parameters.xhtml)). For example I'm using option 43 (Vendor Specific Information) to assist in adoption of new Ubiquiti network equipment.  Kea seems to have the ability documented [here](https://kea.readthedocs.io/en/kea-2.2.0/arm/dhcp4-srv.html#custom-dhcpv4-options).

**Describe the solution you like**

The ability to add custom DHCP/BOOTP option similar to the current ISC DHCP interface. 

**Describe alternatives you considered**

Giving up and staying with ISC DHCP until it no longer is offered. :) 

**Additional context**

That's it, thanks for considering!

**Comment by AdSchellevis** [comment]
same as https://github.com/opnsense/core/pull/7361#issuecomment-2112933052 ?

**Comment by Codelica** [comment]
Wow, sorry I didn't think to search the PRs.   That would definitely take care of my need, and looks more elaborate than the current ISC DHCP/BOOTP options implementation -- where you just add raw number, type, value combinations.   I'll just follow that issue.  Thanks!

**Comment by AdSchellevis** [comment]
@Codelica no problem, on our end we just were not able to reach a functional state, we kept the code in a separate branch. When we know what the [kea] configuration should look like and there are people confirming it actually works, it shouldn't be a huge deal to finish the work.

**Comment by fichtner** [comment]
There is Kea 1.6.0 in the pipeline, but I'm a bit reluctant to pull this in for 24.1.x. It might change things, but it might also bring new issues.
