### ISSUE TITLE
LAN interface tracking with manual adjustment and SLAAC-only WAN interface

### ISSUE THREAD

**Issue by kevinchalet** [opnsense/core#7552]
Hey everyone 👋🏻 

**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

I have a scenario where my ISP (a mobile carrier) doesn't delegate a prefix via DHCPv6 (no IA-NA or IA-PD is returned even if you ask politely 🤣 ):

![image](https://github.com/opnsense/core/assets/6998306/ad12348d-e091-47c1-b830-15b36fef497c)

It does, however, announce a prefix in its RAs (well, two actually: one global and one local):

![image](https://github.com/opnsense/core/assets/6998306/b527f745-fd98-4fe4-a979-f1bb3db0b7e3)

Configuring the WAN interface to use SLAAC (or DHCPv6) works fine and an address is correctly attached:

![image](https://github.com/opnsense/core/assets/6998306/f0b18a96-20cb-40a2-a519-cee10d278bb8)

Unfortunately, using interface tracking on my LAN interface doesn't work correctly as no address is assigned:

![image](https://github.com/opnsense/core/assets/6998306/48c025e9-d3d9-4852-95ad-4f1b14d6c9f6)

![image](https://github.com/opnsense/core/assets/6998306/e3d26c39-7328-419d-869c-5dc4d74e7575)

(and since no address is attached to the LAN interface, the radvd configuration doesn't include the prefix announced in the RA:)

```
# Automatically generated, do not edit
# Generated RADVD config for manual assignment on lan
interface hn0 {
        AdvSendAdvert on;
        MinRtrAdvInterval 200;
        MaxRtrAdvInterval 600;
        AdvLinkMTU 1500;
        AdvDefaultPreference low;
        AdvManagedFlag off;
        AdvOtherConfigFlag on;
        DNSSL localdomain {
        };
};
```

While it's likely not a widespread scenario (I'd expect most ISPs to use IA-PD), it is my understanding after reading https://github.com/opnsense/core/issues/2394 that it should be supported by OPNsense. That said, that thread was opened 6 years ago and the related code has since changed quite a lot, so it's hard to determine whether something has regressed or if I'm just being stupid 😄 

**To Reproduce**

1. Configure a WAN interface to use SLAAC.
2. Configure a LAN interface to use WAN interface tracking.

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 24.1.9_4-amd64
FreeBSD 13.2-RELEASE-p11
OpenSSL 3.0.14

Important note: it's a test machine that uses the vanilla 24.1.9_4 bits so it's unrelated to the (fantastic) changes made by @fichtner for https://github.com/opnsense/core/issues/5630.

**Comment by kevinchalet** [comment]
Interestingly, it works if I leave the `Allow manual adjustment of DHCPv6 and Router Advertisements` box unchecked (both the global and the local prefixes announced via ICMPv6 are attached and are added to radvd's config).

I'll update the title to reflect that.

**Comment by fichtner** [comment]
The SLAAC tracking was devised for a fringe use case with an Israeli ISP if I remember correctly. It’s possible to work on this again, but not before 24.7 is out.


Cheers,
Franco

**Comment by kevinchalet** [comment]
> Interestingly, it works if I leave the `Allow manual adjustment of DHCPv6 and Router Advertisements` box unchecked (both the global and the local prefixes announced via ICMPv6 are attached and are added to radvd's config).

I was a bit optimistic when I said it was working: an IPv6 address was indeed correctly assigned to the LAN interface and the machines on the LAN subnet were able to assign themselves an IPv6 GUA via SLAAC... but no communication using that prefix was possible: trying to ping an IPv6 server on Internet from a machine located in the LAN subnet would simply result in a timeout error.

Unfortunately, there's a "small" (🤣) detail I forgot: this scenario requires proxying neighbor advertisements for IPv6 packets to be correctly routed back to the sender... and it's not something OPNsense supports (as confirmed by https://forum.opnsense.org/index.php?topic=21795.msg105213#msg105213).

> While it's likely not a widespread scenario (I'd expect most ISPs to use IA-PD), it is my understanding after reading https://github.com/opnsense/core/issues/2394 that it should be supported by OPNsense.

Amusingly, this is actually more common than I originally thought as it's the magic sauce used to make all tethering/mobile phone connection sharing scenarios work. And it's a standard thing: [Extending an IPv6 /64 Prefix from a Third Generation Partnership Project (3GPP) Mobile Interface to a LAN Link](https://datatracker.ietf.org/doc/html/rfc7278) (aka RFC7278).

> The SLAAC tracking was devised for a fringe use case with an Israeli ISP if I remember correctly. It’s possible to work on this again, but not before 24.7 is out.

I don't want to discourage you from working on that post-24.7, but it seems much less trivial to implement than I anticipated, since fixing the address assignment would only be a tiny part of the story: it still wouldn't work without an NDP proxy/relay.

For completeness, RFC7278 doesn't seem to be supported by `systemd-networkd` - at least I wasn't able to make it work - but it works flawlessly on OpenWrt (I tested on both a VM and an ASUS TUF AX6000). For those interested, you only need to configure two things:

<details>
You need to update your WAN interface to set extendprefix to 1 (which basically treats the IPv6 prefix returned via ICMPv6 as a classical DHCPv6-delegated prefix you can assign to your LAN interfaces):

```
config interface 'lan'
        option device 'br-lan'
        option proto 'static'
        option ipaddr '10.1.150.5'
        option netmask '255.0.0.0'
        option ip6assign '64'
        option ip6ifaceid 'random'

config interface 'wan'
        option proto 'dhcpv6'
        option device 'eth1'
        option extendprefix '1'
        option reqaddress 'try'
        option reqprefix 'auto'
```

You need to update your DHCP configuration to enable the NDP relay between the WAN and the LAN interfaces:

```
config dhcp 'lan'
        option interface 'lan'
        option start '100'
        option limit '150'
        option leasetime '12h'
        option dhcpv4 'server'
        option ra 'server'
        option ndp 'relay'
        option ndproxy_slave 1
        option dhcpv6 'server'

config dhcp 'wan'
        option interface 'wan'
        option ignore '1'
        option ndp 'relay'
        option master '1'
```
</details>

@fichtner since it's a mobile-first feature, maybe it's not a great fit for OPNsense. If you think so, please don't hesitate to close this ticket 😃

**Comment by Skywalker-11** [comment]
Please correct me if I'm wrong but the `Prefix Information` (ICMPv6 Code 3) in your screenshot should only be used for on link traffic. That means devices that are directly connected to each other without a router in between. So your OPNsense should not be able to use that prefix on the LAN side. 

If your ISP only provides a single public /64 prefix  the `2a04....` prefix in your case the only viable solution might be to do IPv6-natting

**Comment by Monviech** [comment]
@kevinchalet
https://forum.opnsense.org/index.php?topic=44071.0
https://github.com/opnsense/plugins/pull/4348

Your issue is most likely fixed with this plugin. :)

**Comment by kevinchalet** [comment]
Woooo, very nice @Monviech, thanks for letting me know! 👏🏻 

Your post says that `it is best not to use "Allow manual adjustement of DHCPv6 and Router Advertisements"` but did you have a chance to test the manual mode? That's the part that didn't work correctly during my testing: https://github.com/opnsense/core/issues/7552#issuecomment-2184112905

(I'll certainly give it a try soon 😄)

**Comment by Monviech** [comment]
I just tested it quickly with manual adjustement.

Services: Router Advertisements: [igc0_LAN]
Router Advertisements: Stateless
Router Priority: Low
DNS servers: fe80::f690:eaff:fe01:3dc6 (link local of that firewall)

No DHCPv6 is enabled, its just SLAAC.

Rebooted my box and it still worked right away. So I think its okay.
