### ISSUE TITLE
Services: Captive Portal: Administration - remove Transparent proxy settings

### ISSUE THREAD

**Issue by AdSchellevis** [opnsense/core#7557]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**

A long time ago we added "Transparent proxy" options in the captive portal to be able to use captive portal combined with the squid proxy. Last time we did some internal tests, the feature introduced in https://github.com/opnsense/core/commit/0fb1cb1d68f9582b1108ac273f9d786fbadd0253 seemed to be broken and likely has been for a very long time. 

My assumption is nobody has been using this for a very long time, in which case we better remove the toggles for clarity.

**Describe the solution you like**

Remove the toggles before 24.7 is released.

**Describe alternatives you considered**

none

**Additional context**

* https://github.com/opnsense/core/issues/1189
* https://forum.opnsense.org/index.php?topic=3670.msg12576#msg12576

**Comment by vknecht** [comment]
Hello !
Can this change be reconsidered, and tests be re-run ?
Since this removal and updating to 244.7, our captive-portal-with-transparent-proxy is broken
and adding ipfw rules manually "fixes it".
Did I miss something ?

Thanks
