### ISSUE TITLE
Installer ignores LAN domain setting

### ISSUE THREAD

**Issue by TechGeek01** [opnsense/core#7558]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

When running through the setup wizard after first install, the setting for the LAN domain is ignored, instead using the default `localdomain` regardless of what is entered.

**To Reproduce**

1. Install OPNsense
2. Reboot
3. Run through the setup wizard
    3a. Enter your LAN domain of choice while using the wizard
4. When checking the dashboard, the domain will still be using the default `localdomain`

**Expected behavior**

The domain that was set in the wizard should be used instead of the default.

**Describe alternatives you considered**

Setting the domain in Settings > General works after the wizard completes.

**Environment**

I've seen this in every version of the 24.1 installer image I've ever used, including the latest downloaded from the website as of 2024-06-25.

When testing, the 24.7 beta doesn't seem to have this issue, just 24.1.

**Comment by fichtner** [comment]
Yes, it was fixed, but the 24.1 images can’t be reissued.
