### ISSUE TITLE
Web-Portal blog needs update

### ISSUE THREAD

**Issue by Zweihorn** [opnsense/core#7566]
IMHO **NOT an un-important question**

_Why did the blog stop in 2023 and no advertising of 24.1 and more?_

Yes there may be other sources of information but the OPNsense blog could be easily continued as an instrument of marketing and information on the home page.  Furthermore, the "Blog" button sits quite prominent besides the "Download" button on the web top menu of your most beloved project home page.  Did I miss something or am I wrong?

ref
  * https://opnsense.org/blog/
  * https://opnsense.org/about/road-map/
  * https://forum.opnsense.org/

Just curios and just asking.

Keep on the good work and prosper.

🌻 

**Important notices**

Our forum is located at https://forum.opnsense.org , please consider joining discussions there in stead of using GitHub for these matters.

Before you ask a new question, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Comment by AdSchellevis** [comment]
@Zweihorn the blog was merely a copy of the messages posted on the forum, manually copied periodically, it didn't add very much. We changed the widget on our end to use the feed via https://forum.opnsense.org/index.php?board=11.0&action=.xml;limit=20;type=rss2

When we're upgrading the project website, we have to see what we will do with it, currently we don't actively write blog postings, but in the future you never know.

**Comment by Zweihorn** [comment]
@AdSchellevis  THX - However, the core web problem and IMHO quite _misleading first impression to interested newcomers_ still remains apparently.

Why not just **making a last and only blog post** reading: 

> Please find more current information at
>  * https://opnsense.org/about/road-map/
>  * https://forum.opnsense.org/

Supposedly an easy and simple task.  Hope this helps.

🌻

**Comment by AdSchellevis** [comment]
@Zweihorn good point, I'll see what we can do.

**Comment by melroy89** [comment]
> However, the core web problem and IMHO quite _misleading first impression to interested newcomers_ still remains apparently.

I can't agree more here. The blog menu item is quite prominent in the top menu, if the last blog item is from Juli 2023, the project seems kinda dead. Which isn't the case.

You really want to update those blogs if you are serious about the business IMO.

**Comment by fichtner** [comment]
> You really want to update those blogs if you are serious about the business IMO.

The rebranding of both the company and project has been going on for at least a year now and requires a lot of work so the modification of the old pages are just where strictly necessary and the blog just isn't one of them. We're on it. It would be nicer to not read such blanket statements.

**Comment by fichtner** [comment]
To be fair the messenger has been dead for a couple of years. Random blanket statements are a waste of time and motivation.

**Comment by AdSchellevis** [comment]
feeds from forum now https://opnsense.org/blog/

**Comment by melroy89** [comment]
Thank you so much!!
