### ISSUE TITLE
OpenVPN: working Static IP addresses for VPN clients

### ISSUE THREAD

**Issue by Reiner030** [opnsense/core#7567]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**OpenVPN pool can't assign dedicated IP addresses even override fields are implemented.**

As already twice commented on other issues the implementation of manual pool range is missing for OpenVPN:
```
server 10.30.7.0 255.255.255.0 nopool
ifconfig-pool 10.30.7.20 10.30.7.200
```

**Setup of these configuration parameters**

because in actual implementation the client gets only the assigned IP address when address is not already dynamically in use by other client.

patch attached

**Comment by Reiner030** [comment]
PR again not referenced... => https://github.com/opnsense/core/pull/7568

Suggestion in https://github.com/opnsense/core/issues/7316#issuecomment-2191126783 would be also nice but because an additional file and optional TTL are needed this needs another PR
> --ifconfig-pool-persist args
> Persist/unpersist ifconfig-pool data to file, at seconds intervals (default 600), as well as on program startup and shutdown.
> Valid syntax: `ifconfig-pool-persist file [seconds]`

**Comment by jpVm5jYYRE1VIKL** [comment]
Hey developers . It is really needed feature. You even got PR why just not to add it ?
