### ISSUE TITLE
OpenVPN - variable implementation fix

### ISSUE THREAD

**Issue by Reiner030** [opnsense/core#7569]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x ] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x ] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

Since in all other files OTP tokens are used as otp_token it's a weird behavior to use a "pin" on OTP token itself in OpenVPN ... 
So small variable fix done.

**Comment by Reiner030** [comment]
Implemented in PR https://github.com/opnsense/core/pull/7570

**Comment by AdSchellevis** [comment]
https://github.com/OpenVPN/openvpn/blob/v2.4.7/doc/management-notes.txt << PIN
