### ISSUE TITLE
cdrom-iso too large to burn

### ISSUE THREAD

**Issue by majorsl** [opnsense/core#757]
Hi all, I downloaded OPNsense-16.1-OpenSSL-cdrom-amd64.iso from one of the mirrors.  The iso size is 760.1MB which is too large to burn to a physical CD-ROM disc. I did not check any of the other iso images for this issue.

**Comment by jschellevis** [comment]
Dont know what current image size is, but with what you say it will fit on 90min cdr (800MB) or use a DVD.

**Comment by majorsl** [comment]
I must be getting old. I didn't know 90min existed. I only have a stack of 80min cdr and remember when 70min was standard. I did end up using a DVD. It wasn't a problem with the 15 series and was just thinking someone accidentally set the wrong size of the iso. Feel free to close this.

**Comment by jschellevis** [comment]
No problem. I did not know image size had become a problem for standard 80min cdr's. Don't think we can do anything about it but before closing it I'll look into that first. Thank you for your feedback... and ofcourse for using OPNsense :)

**Comment by fichtner** [comment]
CD-ROMs have sizes varying from 650 to 879 MB according to Wikipedia. We try to land in the middle, but not wanting to offer strip down customisations to our eco-system to stay compatible with FreeBSD has increased image size bit by bit. A DVD works as well for physical access. (And VMs don't have this problem at all.)

We are looking into trimming the base system for 16.7, splitting off a few services into plugins, making the ISO slightly slimmer in the process. There is no definitive timetable as to what and when, but it'll happen. :)
