### ISSUE TITLE
BUG: OpenVPN offers unused Keepalive_interval and KeepAlive_timout parameters

### ISSUE THREAD

**Issue by Reiner030** [opnsense/core#7571]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

GUI holds parameters but configuration has setup only static values

**To Reproduce**

set / change the parameters and find out that there is no change ;-)

patch attached in PR

**Comment by Reiner030** [comment]
Interesting, wasn't setup in my master trunk till i wrote the issue/created the PR for months ... 

```
$ grep -n keepalive opnsense/mvc/app/models/OPNsense/OpenVPN/OpenVPN.php
146:            if ((int)(string)$instance->keepalive_timeout < (int)(string)$instance->keepalive_interval) {
149:                    $key . ".keepalive_timeout"
188:                'keepalive_interval',
189:                'keepalive_timeout',
601:                if (!empty((string)$node->keepalive_interval) && !empty((string)$node->keepalive_timeout)) {
602:                    $options['keepalive'] = "{$node->keepalive_interval} {$node->keepalive_timeout}";
```

so feel free to check against https://github.com/opnsense/core/pull/7572 if  there are additonal changes needed.

**Comment by AdSchellevis** [comment]
I'm not going to spend more time on this, don't worry. Tried to explain a couple of times now we're not hosting a dumpster here. The PR taints legacy frozen legacy code and will affect other peoples setups for various reasons.
