### ISSUE TITLE
ipv6 tagged VLAN is "leaking" router advertisement messages to parent untagged lan interface

### ISSUE THREAD

**Issue by antipiot** [opnsense/core#7577]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

VLANs are leaking ipv6 router avertisement on the wrong (other) interfaces (parent interface ). 

**I'm not sure it's opnsense related** as i tried to exclude the VLAN on the switch where my computer is connected and it seems to prevent this behavior.

**To Reproduce**
Create an ipv6 activated subnet on an interface
Create an ipv6 enabled vlan using the same interface as parent
**Tag** the vlan every where on a switch
Restart the router advertisement service in order to force the message
You now have 2 subnets on an interface, one belonging to the other tagged VLAN interface 
![image](https://github.com/opnsense/core/assets/26579988/cf00af5c-d635-4eb5-874b-203479c1fd4b)

**To Prevent this**
Exclude VLAN on switch
or
Set RA to disabled

**Expected behavior**
You only get the ip subnet that belongs to the interface you're connected to.

**Describe alternatives you considered**
Tried this on others vlans and i was able to kind of reproduce this aswell

**Screenshots**
![image](https://github.com/opnsense/core/assets/26579988/b50ccf7b-ff5a-4c39-8bde-529d6e9a1d88)

**Additional context**
Switch is a Zyxel GS1900-24HP - up to date firmware

Regards

JS

**Comment by Monviech** [comment]
I think using a trunk with only Tagged VLANs between the OPNsense and the Core Switch will solve this behavior.

There's no reason to use the untagged VLAN on the trunk in my opinion.

**Comment by antipiot** [comment]
> I think using a trunk with only Tagged VLANs between the OPNsense and the Core Switch will solve this behavior.
> 
> There's no reason to use the untagged VLAN on the trunk in my opinion.

Interesting Idea! thanks.
Will try this for sure.

Anyway this is still kind of strange...

**Comment by antipiot** [comment]
> Yeah, but this can happen for dhcp too:
> 
> https://forum.opnsense.org/index.php?topic=39073

Thanks you very much for this.
