### ISSUE TITLE
Can't scroll with scrollbar

### ISSUE THREAD

**Issue by DokuKaefer** [opnsense/core#759]
There is no scrollbar on smaller display like laptops.
I can only scroll with arrow keys or mouse wheel.
Here a screenshot of my Test-VM, the scrollbar is in the background.

![scrollbar](https://cloud.githubusercontent.com/assets/11537653/12874852/f9f8f7f6-cddc-11e5-8c50-48a7d01335c6.png)

**Comment by fichtner** [comment]
I think that's how the bootstrap modals are designed... they overlay and scroll on top of the locked page, they are not supposed to scroll in themselves. Can we close this?

**Comment by DokuKaefer** [comment]
Ja kann nach meiner Meinung geschlossen werden, so oft kommt das ja nicht vor das man keine Maus hat. Anonsten muss man halt mit den Pfeiltasten scrollen.

**Comment by fichtner** [comment]
Oki :)
