### ISSUE TITLE
dhcp6: WAN address seems to vanish after a renew is tried (24.1.9_4)

### ISSUE THREAD

**Issue by samip5** [opnsense/core#7595]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

My WAN configuration is set to DHCPv6 and DHCPv4, with /56 prefix. I get the /56 IPv6 prefix, but the WAN's DHCPv6 address vanishes on renew seemingly.

This used to work on 24.1.9_1.

**To Reproduce**

1. Setup WAN with DHCPv6 and send IPv6 prefix hint checked
2. See that it's successful in getting the address and prefix after applying
3. Wait 5m-1h
4. See that IPv6 WAN address vanished.
5. See that the logs for it are indeed missing IA_NA address.

**Expected behavior**

I would have expected the WAN interface to keep it's global address, and not rely on link-local only for WAN.

**Describe alternatives you considered**

N/A

**Relevant log files**

syslog.txt: https://gist.github.com/samip5/b5ef592b639ab4ec997288bd76a0167e

**Additional context**

This is very frustrating problem to have when you're relying on the WAN address for port forwarding purposes.

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 24.1.9_4 (amd64).
Intel® Atom™ C3758 @ 2.20Ghz 8C/8T
Network Intel® X553 & Intel® I225-V

**Comment by fichtner** [comment]
As the forum suggested…

    # opnsense-revert -r 24.1.8 dhcp6c

reboot and it should be ok.

if not feel free to debug this further.

**Comment by samip5** [comment]
> As the forum suggested…
> 
> ```
> # opnsense-revert -r 24.1.8 dhcp6c
> ```
> 
> reboot and it should be ok.
> 
> if not feel free to debug this further.

I don't know but that just says fetching without actually showing any signs of an error or progress...?

**Comment by samip5** [comment]
Okay, so `24.1.8` did not fix it. 🤔

**Comment by samip5** [comment]
Fixed by `pkg add -f https://pkg.opnsense.org/FreeBSD:13:amd64/snapshots/misc/dhcp6c-20240607_1.pkg`
