### ISSUE TITLE
opnsense /usr/local/etc/rc.bootup error in log

### ISSUE THREAD

**Issue by StopTrain** [opnsense/core#76]
Found this after some testing tonight.  Not sure if this was in other releases or not:

opnsense: /usr/local/etc/rc.bootup: The command '/usr/sbin/pw groupadd -g -M 2001 2>&1' returned exit code '65', the output was 'pw: group name required'

**Comment by fichtner** [comment]
Matt, I could not track this down. Does the problem persist? It is likely a custom user that you added to the system through the config.xml...

**Comment by AdSchellevis** [comment]
It seems related to https://github.com/opnsense/core/commit/49c891985fc733ec647094bec7c315e2af265fdf , when adding users sometimes an empty group item was put in to local_user_set_groups and then weirdness happened. I will close this issue.

**Comment by fichtner** [comment]
Cool! :)
