### ISSUE TITLE
CaptivePortal: Allowed MAC - Uppercase and lowercase don't mix 

### ISSUE THREAD

**Issue by DokuKaefer** [opnsense/core#760]
Uppercase and lowercase don't mix 
Example:

08:**bb**:27:12:68:**ac** = internet free (all letters small)
08:**BB**:27:12:68:**AC** = internet free (all letters large)

08:**BB**:27:12:68:**ac** = no internet (mixed letters)
08:**bb**:27:12:68:**Ac** = no internet (mixed letters)

**Comment by AdSchellevis** [comment]
You will have to save your data again before this fix will work, I've chosen to lowercase automatically here to prevent this from happening.
To test if the correct config is created, you can inspect /usr/local/etc/captiveportal.conf
