### ISSUE TITLE
Netflow Export does not support IPv6 destination

### ISSUE THREAD

**Issue by apalrd** [opnsense/core#7600]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

Netflow exporter (Reporting -> Netflow -> Destinations field) does not accept a valid IPv6 address:port combination.

**To Reproduce**

1. Go to 'Reporting -> Netflow'
2. Enter a [valid IPv6 address] : port number (i.e. `[2001:db8::1]:2055]`) in the Destinations field
3. Click Apply
4. See error ('Invalid IP-port combination')

**Expected behavior**

IPv6 address+port is accepted in the Destinations list

**Describe alternatives you considered**

I also tried to use a DNS name:port, however, accepting an IPv6 address would be sufficient.

**Screenshots**

N/A

**Relevant log files**

N/A

**Additional context**

It looks like https://github.com/opnsense/core/pull/7134 improved input validation of this field, but is set to only validate ipv4. Samplicate appears to support mixed v4/v6 outgoing packets if they are properly formatted, however, the netflow/samplicate service file will rewrite :'s in IPv6 addresses into /'s improperly (https://github.com/opnsense/core/blob/d82d17044e09705c8c39ae77c03f0cd9ba2a999d/src/etc/rc.d/netflow#L167). 

Reading Samplicate's code it looks like they use getaddrinfo() so a DNS name : port should also be valid.

**Environment**

Software version used and hardware type if relevant, e.g.:
OPNsense 24.1.6 (amd64)
Intel(R) Celeron(R) CPU J3160
Network Intel® I210

**Comment by AdSchellevis** [comment]
@apalrd can you try https://github.com/opnsense/core/commit/f587c307e3b5472880f4d7d2290dedacc459394c ? I haven't checked if it fully works, but it accepts ipv6 input and starts samplicate with proper arguments on my end (`/usr/local/bin/samplicate -s 127.0.0.1 -p 2055 [2001:db8::1]/2055`)

**Comment by apalrd** [comment]
Tested with `opnsense-patch` and it's working correctly with a v6 destination. I also tried a mix of v4/v6 destinations and packet capture shows the packets to all destinations are going out successfully.

**Comment by AdSchellevis** [comment]
@apalrd thanks for confirming, the update should be in time for our 24.7 release later this month
