### ISSUE TITLE
OPNSense checksum does not match

### ISSUE THREAD

**Issue by Heracles31** [opnsense/core#7602]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X ] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [ X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

OPNSense can be downloaded from https://opnsense.org/download/  where the page mentions that the appropriate checksum is ec08755245017cd449a8d174b6ea7c4e2038c454a8abecfad0d0378729d8b331

On this page https://docs.opnsense.org/manual/install.html#download-and-verification
there is a mention that from now on, the checksum is processed BEFORE zipping, so you need to unzip the archive before verifying the checksum.

The thing is, the checksum given by the download site is the one of the zipped file, not the one of the img file contained in it, which is a5e7e1c72b72a4e43d51da81706bae0205e340793219692e6f9ec4c03542d585

**To Reproduce**

1. Go to 'https://opnsense.org/download/'
2. See the advertised checksum value of ec08755245017cd449a8d174b6ea7c4e2038c454a8abecfad0d0378729d8b331
3. Go to 'https://docs.opnsense.org/manual/install.html#download-and-verification'
4. See the big orange warning saying to "Make sure to unpack the image using bunzip2 before verifying. Our signatures are generated before compressing them (as of OPNsense version 24.1)"
5. unzip the downloaded image
6. compute the SHA256 of the .img file
7. see the mismatch

**Expected behavior**

The advertised checksum should be the proper one.

**Describe alternatives you considered**

Easy enough to work around that and validate that the archive is still authentic but a proper documentation would be important.

**Screenshots**

**Relevant log files**

**Additional context**

Running proxmox here and it includes a built-in checksum validation for ISO files. It rejected the OPNSense image because of the bad checksum.

**Environment**

OPNsense 24.1 (amd64).

**Comment by fichtner** [comment]
Checksum check is before unzip, signature verification after unzip. It’s pretty clear so maybe you’re just confusing the two methods.


Cheers,
Franco

**Comment by Heracles31** [comment]
Indeed...

**Comment by Heracles31** [comment]
indeed
