### ISSUE TITLE
Issue with AD User Deactivation: 'Disable' Button Not Functioning as Expected

### ISSUE THREAD

**Issue by ElXk6** [opnsense/core#7604]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

I found out earlier that users who were added with an AD are not deactivated via the "disable" button.

Neither for access in the GUI, nor via VPN etc.

Is this a "works as expected", or is this a bug?
I am actually of the opinion that this has worked before, but I am not sure.

If it is supposed to work like this, can it be submitted as a feature request? 

The background is, for example, to block users only for access to the GUI or VPN, but not immediately to all other AD dependencies.

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 24.1.9_4-amd64
FreeBSD 13.2-RELEASE-p11
OpenSSL 3.0.14
Intel(R) Atom(TM) CPU C3558

**Comment by AdSchellevis** [comment]
I'm not 100% sure what you mean, but if you check the `disabled`  checkbox and save the user, doesn't the value stick? or is disabled just ignored when trying to authenticate? I don't expect anything has changed here by the way.

**Comment by ElXk6** [comment]
The deactivation is ignored when you log in.
The check itself for disabled is saved.

It works as expected for locally created users.
Disabled checked => you cannot log in.
Disabled unchecked => you can log in

The Disabled button does not work for users that are imported via an LDAP:
Disabled checked => you can log in.
Disabled unchecked => you can log in

**Comment by AdSchellevis** [comment]
That kind of makes sense, but has (highly likely) always been the case. For ldap (AD) users the server is responsible for accounting, groups are synched when chosen, but when the remote server authenticates properly we can assume the user itself is not disabled. 

Theoretically when user creation is enabled we could remove the disable flag when set, but that is likely not really worth the effort. Choosing to user the disable flag as some sort of overwrite might also be possible, but might lead to new tickets for people not expecting a "local" user blocking "non-local" access.

**Comment by ElXk6** [comment]
I would be on your side if you simply connected the ad-sync and had nothing else to do with it.
Then I would assume that everything is managed on the AD side.

But you have to import the users individually using the import button.
I have always thought that all the settings I make there are first checked against the opnsense and only the user credentials are authenticated against the AD.

In my opinion it is definitely confusing, I never expected that the button would not work.

In any case, it would be a good option to be able to block users independently of other services.
Then you also know that all linked opnsense services, such as openvpn, no longer work. 

But whether you want to do that is up to you :)

**Comment by AdSchellevis** [comment]
the import is the old method, it works, but automatic syncs are easier to manage (see also the note in https://docs.opnsense.org/manual/how-tos/user-ldap.html#step-4-import-users)

**Comment by AdSchellevis** [comment]
I can see where the confusion comes from, but I think we better add a help text to explain this is only relevant for local logins (same as the password, which is likely more obvious). Even when not using a group sync option, it's still better to use groups for access control anyway.
