### ISSUE TITLE
16.1.2 + old config -> RRD API request authentication failed

### ISSUE THREAD

**Issue by hobi82** [opnsense/core#761]
I upgraded today to 16.1.2 and played back an older config from 15.7.17. When I select "System" -> "Health" I get an error message: "Error while fetching RRD list : error". After checking a bit futher I noticed that the background request towards the API fails with an authentication error:

https://opnsense-box/api/diagnostics/systemhealth/getRRDlist/

{"status":401,"message":"Authentication Failed"}

Resetting RRD data etc. didn't help at all. Re-login didn't work either. Maybe there's a different old user set on the API?

Cheers

**Comment by AdSchellevis** [comment]
For some reason I can't seem to reproduce this one on my end, only small thing I noticed is that we didn't supply an acl for this part, but for root this shouldn't be necessary.

I've added the acl just to be sure, it's in https://github.com/opnsense/core/commit/8b12976fc4bbbc8d69a6cf47971970d78c96ff59

If you would like to test if this solves anything, just run:
```
curl -o /usr/local/opnsense/mvc/app/models/OPNsense/Diagnostics/ACL/ACL.xml https://raw.githubusercontent.com/opnsense/core/master/src/opnsense/mvc/app/models/OPNsense/Diagnostics/ACL/ACL.xml
```

**Comment by hobi82** [comment]
Seems to be solved now on my end (after re-login ~24 hours later). Maybe a browser/session related issue?! I think you can close that one too for now. Thanks, keep up the good work you do!

**Comment by AdSchellevis** [comment]
Your welcome, thank you for testing.

**Comment by rcursaru** [comment]
I have installed 16.1 in vmware and then upgraded to 16.1.8. When I try to open system -> Health I get the same error with the same json as reply. I have experienced this in Firefox. Opening the Health page in Chrome works properly.

**Comment by AdSchellevis** [comment]
@rcursaru is this repeatable when you login to the machine again and try to access the system health? if your session did reach a time-out and the health was still open, you probably receive the same feedback.

**Comment by rcursaru** [comment]
Logging out and in again did not fixed it. Neither logging in with a different admin user.

**Comment by AdSchellevis** [comment]
@rcursaru really odd, I'm using Firefox at my location and don't seem to have the same issue. are you using the root user? or a configured admin user?

**Comment by rcursaru** [comment]
@AdSchellevis I was using the root user at the moment of the update, only later I created a pair of admin users.
I've switched from HTTP to HTTPS and the error was gone. Switching back to HTTP brought the error back. What other tests should I do?

**Comment by AdSchellevis** [comment]
@rcursaru so, it only happens when using http?

**Comment by rcursaru** [comment]
@AdSchellevis yes, only on HTTP, only on the browser I was using from install up until after the update (Firefox 45.0.1 on Windows 10), on all users (root and configured admins).
It doesn't happen in:
* Firefox with HTTPS
* Chrome with HTTP or HTTPS
* Firefox with HTTP in new private window
Cookie or some weird browser caching?

**Comment by AdSchellevis** [comment]
@rcursaru its probably a weird browser issue, but I will test this one on my box and to see what its trying to do when using https.

**Comment by AdSchellevis** [comment]
@rcursaru its very likely is a browser issue, when I switch to http on my end all still works as expected, probably some weird caching like you suggested.
