### ISSUE TITLE
Geoip aliases cannot be created or changed

### ISSUE THREAD

**Issue by meyergru** [opnsense/core#7614]
- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

With 24.1.10_2 (probably 24.1.10), it is impossible to edit geoip aliases. There is an error message:

`Entry "[object HTMLOptionElement]" is not a valid country code.
`

**To Reproduce**

Try to create a geoip alias and select any country. Save.

**Expected behavior**

Normal save and edit window disappears.

**Describe alternatives you considered**

Existing entries are not affected, but they cannot be changed.

**Screenshots**

![grafik](https://github.com/user-attachments/assets/26ee97fc-77cf-4871-b91a-cf1352f39d96)

**Relevant log files**

None.

**Additional context**

None.

**Environment**

OPNsense 24.1.10_2 (amd64).
Intel® Pentium Silver N6005
Network Intel® I225-V

**Comment by bensmithurst** [comment]
[geoip.patch](https://github.com/user-attachments/files/16199638/geoip.patch)

I came up with the attached patch which fixes the problem for me, but I don't know if it's the best way.

**Comment by AdSchellevis** [comment]
https://github.com/opnsense/core/commit/4569d045ccd42de08a792ca7f606e047ae84234d should fix the issue

**Comment by meyergru** [comment]
It does, as verified by 'opnsense-patch 4569d04'

Thanks!

**Comment by AdSchellevis** [comment]
@meyergru you're welcome and thanks for reporting.

**Comment by meyergru** [comment]
I forgot to mention: it was not me finding this... https://forum.opnsense.org/index.php?topic=41531
