### ISSUE TITLE
After update to OPNsense 24.1.10_3-amd64 openssh was inaccible

### ISSUE THREAD

**Issue by chimmmpie** [opnsense/core#7624]
I have 4 systems running opnsense (3 VM's and one hardware appliance. 

After doing the updates in the webui this morning the openssh service did not work despite the system stating that is was running on the web UI. Hitting restart (system -> Diagnostics -> services -> openssh -> restart) resolved the issue.

**Comment by fichtner** [comment]
This was the "intended" behaviour of the OpenSSH upgrade. https://gitlab.archlinux.org/archlinux/packaging/packages/openssh/-/issues/5

**Comment by chimmmpie** [comment]
It would have been nice if this was in the change log. Now i got all kind of alarms :D

**Comment by fichtner** [comment]
It was in the annoucements, but not the changelog. Let me fix that today.

https://forum.opnsense.org/index.php?topic=41505.msg203633#msg203633

**Comment by fichtner** [comment]
https://github.com/opnsense/changelog/commit/208f60a9
