### ISSUE TITLE
select a specific widget from that dropdown doesn´t work in the alternative opnsense themes

### ISSUE THREAD

**Issue by opnsenseuser** [opnsense/core#7627]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [ x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x ] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**netnut wrote in the forum:**

Playing around with 24.7-RC1 and the new dashboard, I noticed I couldn't add a new widget to the dashboard. Adding a new widget shows a dropdown which is slightly hidden behind the rest of the UI which results in not able to select a specific widget from that dropdown. Switching back to the "default" opnsense theme fixes it, so I guess it's a small glitch in the Cicada theme (Firefox 128 / MacOS).

see description of the user: netnut

 @swhite2 Is there any file missing from the new dashboard or any addition that I haven't added yet for the alternative themes?

see forum: https://forum.opnsense.org/index.php?topic=41370.15

Cicada theme (Firefox 128 / MacOS).

OPNsense 24.7-RC1

Regards René

**Comment by fichtner** [comment]
Missing this? https://github.com/opnsense/core/commit/c6f9ce504e

**Comment by swhite2** [comment]
Full commit is https://github.com/opnsense/core/commit/818b0412f5536884f3a5d23d381612af0aeff62c, which is in RC1.

**Comment by opnsenseuser** [comment]
@swhite2 It will probably be due to the bootstrap-select.css file that I have not yet modified. Because the opnsense_widget_manager.js is cross-themed. Should be enough to just add or modify the bootstrap-select.css, right? What do you think?

**Comment by fichtner** [comment]
If you carry the file yourself you will need to update it when changes are made, yes.

**Comment by opnsenseuser** [comment]
i will modify the bootstrap-select.css files for all themes and make a new request as soon as possible.

**Comment by swhite2** [comment]
@opnsenseuser FWIW, the `dashboard.css` file hasn't changed much since you started work on it, but both https://github.com/opnsense/core/commit/34cafe3e9835cb48c41ad063d2aba2700e7f701a#diff-cdc8da5965a4bc43e113a4a237eae3a8efc31ef50bfa344b97262ed16c06ba89 and https://github.com/opnsense/core/commit/c9182e23dc18419e2c9eef6470ca566f45d16398#diff-cdc8da5965a4bc43e113a4a237eae3a8efc31ef50bfa344b97262ed16c06ba89 contains some color information you might want to be aware of.

Many thanks for your work on the themes :)

**Comment by fichtner** [comment]
More or less fixed. I think Tukan is still open, but closing core ticket.
