### ISSUE TITLE
More granular firewall schedule

### ISSUE THREAD

**Issue by giggio** [opnsense/core#7629]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**

I'd like to allow some of my IoT devices to connect to the internet for only a few minutes, but the current schedule minimum interval is 15 minutes, as it forces you to choose one minute of `00`, `15`, `30`, `45` or `59`.

**Describe the solution you like**

Remove the 2 dropdowns for minutes and let use type a number from `0` to `59`.

**Describe alternatives you considered**

I can't find any.

**Additional context**

See:
https://github.com/opnsense/core/blob/684ee270f181397655ca105871db5ede126de6d8/src/www/firewall_schedule_edit.php#L889-L895

**Comment by fichtner** [comment]
The way this was implemented a along time ago was to only offer schedule-based reloads at these checkpoints 15 minutes apart. Everything smaller being selected will just end up being ignored until the next 15 minute checkpoint is reached.

And before you ask there are no plans to rewrite this functionality at the moment although it is on the eternal wish list.


Cheers,
Franco

**Comment by giggio** [comment]
Thanks for the explanation, Franco. Do you think this should be closed or should we keep it open so this can be tracked?

**Comment by fichtner** [comment]
I‘d rather close this. The work to replace this is at least a year away (the last firewall static page to go).

**Comment by fichtner** [comment]
@derek-shnosh you'd have to change the config.xml entry and the hook for the cron to restart the firewall (or roll your own)

```
src/opnsense/service/conf/actions.d/actions_filter.conf-[reload]
src/opnsense/service/conf/actions.d/actions_filter.conf:command:/usr/local/etc/rc.filter_configure
src/opnsense/service/conf/actions.d/actions_filter.conf-parameters: %s
src/opnsense/service/conf/actions.d/actions_filter.conf-type:script
src/opnsense/service/conf/actions.d/actions_filter.conf-message:Reloading filter
```

This would need a `description:` tag to be eligible for cron GUI selection.


Cheers,
Franco

**Comment by derek-shnosh** [comment]
Thanks @fichtner!

I edited **/conf/config.xml** to add a time range.

```xml
  <schedules>
    <schedule>
      <name>KIDS_OFFLINE</name>
      <descr/>
      <timerange>
        <position>1,2,3,4,7</position>
        <hour>7:55-15:00</hour>
        <rangedescr>2-SCHOOL</rangedescr>
      </timerange>
    </schedule>
  </schedules>
```

Then I gave a description to `rc.filter_configure` in **/usr/local/opnsense/service/conf/actions.d/actions_filter.conf**.

```conf
[reload]
command:/usr/local/etc/rc.filter_configure
parameters: %s
type:script
description:Update and reload firewall rules and schedules
Message:Reloading filter
```

Then was able to select it for a job in the UI.

![Image](https://github.com/user-attachments/assets/6dc6e784-9b57-4992-9824-ffb9ce178dc7)

After creating the job and clicking apply, should it show up in shell with `crontab -l`? I see the original rule for every 15 min, but not the new one. Is there a limitation that would prevent `1-59/1` in the minutes field?

```bash
# crontab -l
# or /usr/local/etc/cron.d and follow the same format as
# /etc/crontab, see the crontab(5) manual page.
SHELL=/bin/sh
PATH=/etc:/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin
REQUESTS_CA_BUNDLE=/usr/local/etc/ssl/cert.pem
#minute hour    mday    month   wday    command
1       *       *       *       *       (/usr/local/sbin/configctl -d syslog archive) > /dev/null
2       *       *       *       *       (/usr/local/sbin/expiretable -v -t 3600 sshlockout) > /dev/null
3       *       *       *       *       (/usr/local/sbin/expiretable -v -t 3600 virusprot) > /dev/null
4       *       *       *       *       (/usr/local/etc/rc.expireaccounts) > /dev/null
*/4     *       *       *       *       (/usr/local/sbin/ping_hosts.sh) > /dev/null
0       22      *       *       *       (/usr/local/sbin/configctl -d firmware changelog cron) > /dev/null
*       *       *       *       *       (/usr/local/bin/flock -n -E 0 -o /tmp/updaterrd.lock /usr/local/opnsense/scripts/health/updaterrd.php) > /dev/null
1,16,31,46      *       *       *       *       (/usr/bin/logger "reload filter for configured schedules" ; /usr/local/etc/rc.filter_configure) > /dev/null
1       3       1       *       *       (/usr/local/sbin/configctl -d filter schedule bogons) > /dev/null
*       *       *       *       *       (/usr/local/bin/flock -n -E 0 -o /tmp/filter_update_tables.lock /usr/local/opnsense/scripts/filter/update_tables.py) > /dev/null
```

**Comment by cracklingice** [comment]
I recognize this is a closed issue, but I just wanted to suggest that if there was a page in the UI where we could configure the trigger times, the default could be to include only 00 on fresh installs with the 1 minute prior auto populating and the end user could decide when if any additional minutes they wanted to reload the filter at.  This would reduce filter refreshes on future fresh installs to only the bare minimum required by the individual user while allowing for granularity.  I stumbled upon this because I want to block connections for just 4 minutes so I would only need the filter to reload twice an hour, but with the current setup, it happens 4 times an hour a minimum of 15 mins apart.

**Comment by korgano** [comment]
Just adding my voice to the calls for an option to have sub-15 minute schedule periods.

Currently have a rule for allowing DHCP traffic from a potentially sus IP, and I would **love** to have it only be for 5 minutes, instead of 15.

**Comment by fichtner** [comment]
Some day this component will be rewritten from scratch, but definitely not this year.
