### ISSUE TITLE
[FR] Please don't always redirect to the service status page on service restart

### ISSUE THREAD

**Issue by oparoz** [opnsense/core#763]
I'm generally not a fan of this redirect. Per example, if I restart the VPN service, the next thing I'm going to do is to check the logs, so redirecting me away from the VPN section is a distraction.
But maybe that's just a corner case.

Where the redirect really doesn't work though is on the dashboard widget. It should be possible to restart a service and stay on the dashboard.

**Comment by AdSchellevis** [comment]
Agreed, staying on the page also matches the behaviour of the new components better, for some reason this dropped of the list of things to do earlier.

**Comment by fichtner** [comment]
Wow, thanks, this has been bugging me for years. :)
