### ISSUE TITLE
Add a confirm dialog for the  "Restore default layout" buttom on Lobby: Dashboard

### ISSUE THREAD

**Issue by raydoom** [opnsense/core#7638]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**

**Describe the solution you like**
Add a confirm dialog for the  "Restore default layout" buttom on Lobby: Dashboard，for prevent misclick.

**Describe alternatives you considered**

**Additional context**
![image](https://github.com/user-attachments/assets/83e0b832-b751-4366-b146-26f083f65e9a)

**Comment by Monviech** [comment]
For me it seems to show one, I'm on the 24.7 R2:

![screen123](https://github.com/user-attachments/assets/fcb52523-16c0-448c-ad27-784887997c28)

**Comment by raydoom** [comment]
I am on OPNsense 24.7.b_215-amd64

**Comment by raydoom** [comment]
Only a beta version bug.
