### ISSUE TITLE
interfaces: LAGG ifconfig advertise their actual hwaddr as all zeroes when a member is attached

### ISSUE THREAD

**Issue by fichtner** [opnsense/core#7641]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

A change to retain the original MAC in an assigned interface when not otherwise set was made but backed out for 24.7 since a regression with LAGG was observed.

https://github.com/opnsense/core/commit/afe9c107665

```
ether f4:90:ea:00:d3:0e
hwaddr 00:00:00:00:00:00
```

That makes the implementation think the hwaddr is worth restoring but that's different for LAGG which uses the primary member's MAC address in this "transparent" fashion.

To retain the functionality improvement for a future stable release the idea is to avoid dealing with setting a MAC address that is all zeroes, see https://github.com/opnsense/core/commit/76695679

Just needs testing hopefully.

**To Reproduce**

Create a LAGG with at least a member and assign it as an interface.

ether is reverting to 00:00:00:00:00:00 after configuring the interface

**Expected behavior**

Keep the automatic address / ignore the zeroed one.

**Describe alternatives you considered**

N/A

**Screenshots**

N/A

**Relevant log files**

N/A

**Additional context**

N/A

**Environment**

https://github.com/opnsense/core/commit/a2ac1999f37

**Comment by AdSchellevis** [comment]
fixed in https://github.com/opnsense/core/commit/7baff2c1fc97062d145ae77e2bca0d53d06efa3a
