### ISSUE TITLE
API calls never succeed since 24.7

### ISSUE THREAD

**Issue by svenso** [opnsense/core#7645]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [ X ] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [ X ] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

The last release (24.7) introduced a bug, where API calls using an API token almost never work for POST requests.
The issue is most probably caused by this commit:
https://github.com/opnsense/core/commit/d7d016f400fbcc30c29973b1315db12055cce0f7
It deletes the call to `$this->parseJsonBodyData()` which causes, that JSON data is never read to the $_POST variable.

for example, $this->request->hasPost($post_field) will always be false.
Sample from: ApiMutableModelControllerBase.php
```
 public function setBase($post_field, $path, $uuid, $overlay = null)
    {
        if ($this->request->isPost() && $this->request->hasPost($post_field) && $uuid != null) {
            $mdl = $this->getModel();
```

**To Reproduce**

```
POST http://172.17.128.2/api/wireguard/server/setServer/f74b989b-a885-4600-9c55-a688bba87f69 HTTP/1.1
Host: 172.17.128.2
Content-Type: application/json
Authorization: Basic XXX
Accept: */*
Content-Length: 337

{
	"server": {
		"enabled": "1",
		"name": "wg0",
		"pubkey": "8mmkypKcr9mOgpA1/Lhj0Xk54WXrIj4eynwD43XL1H4=",
		"privkey": "CM6fAXgN1Th7jz5m9vxNq0jT+Akzlfm4VVr+20AQC3k=",
		"port": "443",
		"mtu": "",
		"dns": "",
		"tunneladdress": "10.0.0.1,10.0.0.3",
		"carp_depend_on": "",
		"peers": "",
		"disableroutes": "0",
		"gateway": ""
	}
}
```
which always responds with 
````
{
	"result": "failed"
}
````

The exact same request using interactive authentication succeeds.

**Expected behavior**

The API call should work regardless of the used authentication method.

**Describe alternatives you considered**

Doing an "interactive" login for services when API Keys exists is not a very good way to go.

**Screenshots**
Not applicable

**Relevant log files**
Not applicable

**Additional context**
Not applicable

**Environment**

OPNsense 24.7-amd64
HyperV

**Comment by AdSchellevis** [comment]
looks like I cleaned up a bit too much here, will post a patch asap

**Comment by AdSchellevis** [comment]
https://github.com/opnsense/core/commit/9024abe3f8f2cec10c037f8a7d84bf20fa13b2d1 should fix this, easy to apply using:
```
 opnsense-patch 9024abe
```
