### ISSUE TITLE
BackupController fails due to incorrect call to setContentType

### ISSUE THREAD

**Issue by dharrigan** [opnsense/core#7654]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

```
[26-Jul-2024 09:02:38 Europe/London] ArgumentCountError: Too few arguments to function OPNsense\Mvc\Response::setContentType(), 1 passed in /usr/local/opnsense/mvc/app/controllers/OPNsense/Core/Api/BackupController.php on line 200 and exactly 2 expected in /usr/local/opnsense/mvc/app/library/OPNsense/Mvc/Response.php:64
Stack trace:
#0 /usr/local/opnsense/mvc/app/controllers/OPNsense/Core/Api/BackupController.php(200): OPNsense\Mvc\Response->setContentType('application/oct...')
#1 /usr/local/opnsense/mvc/app/library/OPNsense/Mvc/Dispatcher.php(165): OPNsense\Core\Api\BackupController->downloadAction('this')
```

**To Reproduce**

Invoke a backup.

**Environment**
User-Agent Mozilla/5.0 (Windows NT 10.0; rv:128.0) Gecko/20100101 Firefox/128.0
FreeBSD 14.1-RELEASE-p2 stable/24.7-n267758-4ad7ad40bc77 SMP amd64
OPNsense 24.7 f29196d01
Time Fri, 26 Jul 2024 09:02:48 +0100
OpenSSL 3.0.14
Python 3.11.9
PHP 8.2.20

**Comment by AdSchellevis** [comment]
@dharrigan ah, it looks like I forgot a default there, should be fixed with https://github.com/opnsense/core/commit/810ecdc52fe21c5bbf02c0e079125872820f7bdf. Thanks for reporting and opening a PR
