### ISSUE TITLE
OpenVPN instance: TLS Shared Key

### ISSUE THREAD

**Issue by Green2Matter** [opnsense/core#7656]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

-  I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
-  I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**

In order to fully migrate from legacy servers I would like to use same options for TLS Authentication: TLS Shared Key.

**Describe the solution you like**

Implement TLS Shared Key option in Openvpn instances config.

**Describe alternatives you considered**

None

**Additional context**

It will also further secure TLS control channel.

**Comment by AdSchellevis** [comment]
you're probably seeking the `TLS static key` option (`tls-crypt` / `tls-auth`). A full set of existing features can be found at https://openvpn.net/community-resources/reference-manual-for-openvpn-2-6/ in case something misses,

**Comment by Green2Matter** [comment]
> you're probably seeking the `TLS static key` option (`tls-crypt` / `tls-auth`). A full set of existing features can be found at https://openvpn.net/community-resources/reference-manual-for-openvpn-2-6/ in case something misses,

Yes you are right. I had my mind hard fixed on "TLS Shared Key" that I had missed "TLS static key" config option in instances. Thanks!
