### ISSUE TITLE
VoucherDB with special character like ü ä ö ends with reload error at CP

### ISSUE THREAD

**Issue by DokuKaefer** [opnsense/core#766]
Can create VoucherDB with ä ö ü, choose the DB in the Administration settings of Captive Portal, press Save and then apply. It comes a error.

![settings](https://cloud.githubusercontent.com/assets/11537653/12931511/95b94e00-cf7e-11e5-8679-ffcb44ca45ed.png)

![error](https://cloud.githubusercontent.com/assets/11537653/12931514/983b31a2-cf7e-11e5-8dcc-4c98a09c0094.png)

**Comment by AdSchellevis** [comment]
@DokuKaefer Thanks for reporting.

It looks like a unicode issue in template generation, this commit  https://github.com/opnsense/core/commit/1363689dc7092d64bfc35475f29b7f2fb644e5d6 solves that issue. Did a quick test on my end including authentication and all seem to work fine now.
