### ISSUE TITLE
Add picture widget to new dashboard

### ISSUE THREAD

**Issue by ethanroy14** [opnsense/core#7665]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**

Picture widget is no longer present on dashboard options after update from 24.1.10 to 24.7

**Describe the solution you like**

Add picture widget to new dashboard

**Describe alternatives you considered**

n/a

**Additional context**

the picture was of my cat. :3

Thank you all for all your hard work!

**Comment by smitty-nieto** [comment]
I'd like to see this added back in as well. As an MSP, we add the logo of our client to the dashboard.
When you are juggling lots of clients, its nice to get a clear indication of which window we are in :)

**Comment by Hunduster** [comment]
+1

**Comment by wesrl** [comment]
I agree I put a meme on mine to remind me why I do stuff on the internet also the MSP thing but PFsense still has this so it didnt effect them

**Comment by fichtner** [comment]
We are aware and something will be added, but we don't want the picture stored in the config.xml where other dashboard settings are stored. This is why it hasn't been done yet.

**Comment by toz2020** [comment]
I totally agree with everyon. The picture or logo was to me very important and i do miss it.

**Comment by nallak** [comment]
Glad i'm not alone kinda found it handy ;)
Good to see that there is a future plan for it !!

**Comment by fichtner** [comment]
Actually it’s done and scheduled for 24.7.5.

**Comment by toz2020** [comment]
> Actually it’s done and scheduled for 24.7.5.



> Actually it’s done and scheduled for 24.7.5.

Fantastic news.

**Comment by nallak** [comment]
> Actually it’s done and scheduled for 24.7.5.

perfect !!!
