### ISSUE TITLE
Graphical glitch when adding widget to new dashboard

### ISSUE THREAD

**Issue by ethanroy14** [opnsense/core#7666]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

graphical glitch with dashboard "add widget." dropdown shows up behind popup box and does not respond to mouse

*Tip*: to validate your setup was working with the previous version, use opnsense-revert (https://docs.opnsense.org/manual/opnsense_tools.html#opnsense-revert)

**To Reproduce**

1. click "add widget" in dashboard
2. attempt to open dropdown

**Expected behavior**

window presents in front of popup box and is clickable

**Describe alternatives you considered**

currently i am able to tab through and select entries with Enter, so there is not too critical of a function issue

**Screenshots**

![image_2024-07-26_181314939](https://github.com/user-attachments/assets/f644365a-9b60-4198-a4de-dfec4c79d7c5)

**Relevant log files**

n/a

**Additional context**

all other functions in new update went off without a hitch. this is the only glitch i have encountered so far

**Environment**

OPNsense 24.7-amd64
Intel® Core i5-6500 @3.2 GHz

**Comment by AdSchellevis** [comment]
this looks like a theme thing, can you retest with the default theme?

**Comment by ethanroy14** [comment]
Seems you are right! I can redirect this to a new issue with rebellion.

![image_2024-07-27_140457660](https://github.com/user-attachments/assets/94704e88-713d-43f9-bf37-2123e2d3372a)
