### ISSUE TITLE
Monit status widget does not update properly on new dashboard

### ISSUE THREAD

**Issue by mgittelman** [opnsense/core#7669]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x ] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [ ] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

The green circles on the left next to each item do not update if an alert has failed. 

**To Reproduce**

1.  Add the monit widget
2.  Add a monit test service that works such as ping external site
3.  Check dashboard to make sure the monit widget item is green
4.  Create condition where test service fails, such as changing ping IP to one that is un=pingable
5.  Check monit dashboard again to see if the status has changed.

**Expected behavior**

The green circles next to each item being monitored by monit on the dashboard should turn red in the case of a failure in the service being monitored. Additionally, when I hover my mouse over the green circles, if an alert has failed it just says "undefined" instead of "ok." The hover over text should say "failed"

**Screenshots**
In the screenshot, the item "Test_Ping_Check" has failed and you can see the mouseover is showing "undefined"

![image](https://github.com/user-attachments/assets/7260a4b7-8f6c-41b7-a02d-aa275afe220b)

**Relevant log files**

N/A

**Additional context**

N/A

**Environment**

OPNsense 24.7_5-amd64 (amd64).
Intel i3-9100f
Supermicro X11SCL-IF

**Comment by Monviech** [comment]
When the ping does not work, its status in the API shows as ``"status":"16384"``

Since this is not mapped in the widget, it goes to undefined.
