### ISSUE TITLE
Feature Request: Configurable Widgets for Gateways and CPU in Dashboard

### ISSUE THREAD

**Issue by kozistan** [opnsense/core#7672]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

Is your feature request related to a problem? Please describe.

Currently, the dashboard does not allow users to configure which Gateways or CPU details they want to display. For better customization and usability, it would be beneficial to select which Gateways are visible and to choose whether to display total CPU usage only.

Describe the solution you like

I would like to have configurable widgets for Gateways and CPU on the dashboard. Specifically, users should be able to:

Select which Gateways to display on the dashboard.
Choose to display only the total CPU usage instead of detailed per-core usage.
Have the ability to collapse and expand widgets, similar to the functionality available in version 24.1.
Describe alternatives you considered

An alternative solution could be implementing a custom view setting where users can save their preferred widget configurations and apply them as needed.

Additional context

Implementing these features would greatly improve the user experience by providing more control over dashboard customization.

**Comment by tismofied** [comment]
I vote for this feature as well because I thought the option to display total CPU usage was under cpu widget options somewhere and I just didn't see it.

**Comment by swhite2** [comment]
@kozistan Thank you for the feedback! I've included the CPU and gateways configurability as per the title, however, because of the customization of widget dimensions I don't see an immediate benefit to collapsing/expanding widgets. It also runs the risk of cluttering the UI further, especially with other pending UX changes.

If more people want to see that happen we can always reconsider.
