### ISSUE TITLE
crash_reporter.php: Fatal error: Allowed memory exhausted 

### ISSUE THREAD

**Issue by oparoz** [opnsense/core#768]
The PHP error log got quite large
```
-rw-r-----   1 squid  wheel   152M Feb  9 22:58 PHP_errors.log
```

and so when opening the crash reporter, I get this:

```
Fatal error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 158880042 bytes) in /usr/local/www/crash_reporter.php on line 137 Call Stack: 0.0009 271272 1. {main}() /usr/local/www/crash_reporter.php:0 3.0008 164537528 2. trim() /usr/local/www/crash_reporter.php:137
```

Maybe only collect the last 300 lines?

**Comment by AdSchellevis** [comment]
Good point, when errors stack very rapidly this file can get quite huge.
I will limit the presentation and upload size to 1MB. (to avoid sending data the user doesn't know about its probably better to keep both aligned).
