### ISSUE TITLE
Cannot restart webGUI from command line

### ISSUE THREAD

**Issue by deajan** [opnsense/core#7680]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

I've hit a 100% disk space usage scenario, which in return prevented WebGUI access because of a CSRF token error.
Once I've cleaned the log files, I've tried to reload the WebGUI using
```
/usr/local/etc/rc.restart_webgui
```

The command failed the the following error message:
```
Warning: require_once(config.inc): Failed to open stream: No such file or directory
```

I've checked `/usr/local/etc/inc/config.inc`, the file exists, and it contains php code so it seems legit.
If I chdir into `/usr/local/etc/inc`, the `rc.restart_webgui` script complains about another missing file, so I think the environment PATH isn't loaded.

Is there any env path to load before executing the script ?

**To Reproduce**

1. Login to SSH
2. Launch `/usr/local/etc/rc.restart_webgui`

**Screenshots**

![image](https://github.com/user-attachments/assets/ade345e4-f8ae-422b-8508-caf2907bc988)

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 24.1.8 (amd64).
KVM VM Intel 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
Network Intel® I211-AT via PCI passthrough

**Comment by deajan** [comment]
Can confirm that v 24.7_5 isn't impacted.

**Comment by WRKT** [comment]
Just asking, did you try to run the command with configctl instead ? 

`configctl webgui restart`

**Comment by fichtner** [comment]
Hint: broken install

    # opnsense-bootstrap

**Comment by deajan** [comment]
@fichtner Don't think so.
A reboot later:
```
/usr/local/etc/rc.restart_webgui
Starting web GUI...done.
Generating RRD graphs...done.
```
I guess it's just the 100% disk space usage that did prevent (somehow ?) to load env variables.
Anyway, I'm closing this since there's no real issue.

Thanks.

**Comment by fichtner** [comment]
ok then the include path was wrong, so maybe it didn't write the php.ini file. if this is disk space related then maybe, but how php.ini got lost in the first place is strange.

**Comment by deajan** [comment]
I have no idea, that was just my wild guess, especially because chdir to the inc dir made the php script complain about other files missing that the initial one.
But apart from a reboot after cleaning disk space, I did nothing more.

Anyway, there's not much more data to analyse. Sorry for the noise.
