### ISSUE TITLE
distribute inslation image with more than just bz2

### ISSUE THREAD

**Issue by tomtom13** [opnsense/core#7682]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**

Issue is that BZ2 compression is not broadly supported out of the box on all platforms.

**Describe the solution you like**

It would be good to see image being compressed and hosted NOT ONLY with bz2. I understand that you guys have your reasons for not hosting plain ISO, but providing GZ, or ZIP would be great for people that have been strapped with windows / mac machines and need to jump through hoops to get BZ2 decompressed. 

**Describe alternatives you considered**

tar.gz
gz
zip

**Additional context**

I honestly think that it's similar to shooting your self in the foot by making people jump through hoops on step 1, if the goal is to make more people use your solution.

**Comment by fichtner** [comment]
bz2 mainly chosen for best cross-compat and size reduction. Adding more compressed images to the mirrors is quite counter-productive as is switching to a algo that compresses this less than bz2.

**Comment by tomtom13** [comment]
Cross compatibility ? with who ? if you're talking linux / bsd distros than yes. But I was talking about sys admins which sometimes are unfortunate to be forced to use windows / mac machines and then jump through hoops to get bz2 decompressed. 

if we're sticking with just thinking about making life easy for linux / bsd, why not take it a notch higher and take LRZIP ?

`ls -la OP*
-rw-r--r-- 1 root root 2182705152 Jul 23 12:52 OPNsense-24.7-dvd-amd64.iso
-rw-r--r-- 1 root root  511969259 Jul 23 12:52 OPNsense-24.7-dvd-amd64.iso.bz2
-rw-r--r-- 1 root root  604875248 Jul 23 12:52 OPNsense-24.7-dvd-amd64.iso.gz
-rw-r--r-- 1 root root  330695696 Jul 23 12:52 OPNsense-24.7-dvd-amd64.iso.lrz
`

?! I don't see that much of a difference between gzip and bz2 :/

**Comment by doktornotor** [comment]
1/ W11 22H2 and later has [had native support for .bz2 (among others) via libarchive for a while](https://www.techspot.com/news/100663-windows-11-extends-support-archive-formats-thanks-open.html) for all those those handicapped sysadmins who cannot install 7zip to handle "obscure compression". 

https://www.techspot.com/news/100663-windows-11-extends-support-archive-formats-thanks-open.html

2/ Or perhaps use a tool that handles decompression on its own. E.g. [USBImager's ](https://gitlab.com/bztsrc/usbimager)

**Comment by tomtom13** [comment]
wow that comment tells me you never worked in paranoid mega corp like pharma where people are forced to be stuck on w10 or cyber where belena etcher is only allowed due to signed support contract. 
Personally I don't give a F, however I want my department to stop supporting stuff that we can offload on IT ... and they are useless and handicapped by their own policies. 
If you buys want to cary on with something that is stupid (putting barriers to entry) then go for it, but denial about it is just stupid squared.

**Comment by fichtner** [comment]
Don't these companies have a budget to buy commercial vendors to deflect blame when something happens? Custom images are in the realm of business opportunity with or without that side note, just contact sales AT deciso DOT com -- talking about community certain restrictions to the process have to be made for the bulk of users.
