### ISSUE TITLE
Widget sizing fails in GridStack.resizeToContent()

### ISSUE THREAD

**Issue by jamtur01** [opnsense/core#7686]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

I have a custom widget that returns the Nut UPS information (https://gist.github.com/jamtur01/a8c2f7cdb26a858da03056458e2ec2ff). Prior to 24.7 it worked. Now I see:

```
Error: GridStack.resizeToContent() widget id:nut '.grid-stack-item-content'.firstElementChild is null, make sure to have a div like container. Skipping sizing.
```

**To Reproduce**

1. Add widget.
2. Refresh dashboard.

**Expected behavior**

**Describe alternatives you considered**

I've tried a few different things like forcing the resize:

```
this.resizeToContent();
```

but no joy.

**Screenshots**

Empty widget:

<img width="502" alt="Screenshot 2024-07-30 at 11 08 57 AM" src="https://github.com/user-attachments/assets/6b620c2b-744c-44e7-be4b-abecbced719c">

Errors:

<img width="732" alt="Screenshot 2024-07-30 at 11 05 09 AM" src="https://github.com/user-attachments/assets/08cab016-b56d-48ea-ae20-0ab357e70cce">

**Environment**

Opnsense 24.7_9-amd64

**Comment by fichtner** [comment]
Noticing that this widget is not in the plugins would you mind raising a PR in plugins for adding it and we can then work on the bug? Might be something small, but I want to avoid working on code that is not in our code base :)


Cheers,
Franco

**Comment by jamtur01** [comment]
I am happy to add it but the issue isn't in my code - it's upstream - so even I am sure someone else is going to stumble onto it.

**Comment by jamtur01** [comment]
Also, where do I put widgets in plugins?

**Comment by fichtner** [comment]
What do you mean "it's upstream"? We're upstream and the widget is not here ;)

https://github.com/opnsense/plugins/tree/master/sysutils/nut <- put in here create a PR

But you need to rename Core.xml to Nut.xml because that file already exists and would prevent the plugin from being installed.

**Comment by jamtur01** [comment]
Upstream: The widget worked fine in the last release. I haven't changed the widget. Hence something upstream that was changed as a result of the upgrade broke the widget.

**Comment by fichtner** [comment]
Fair enough, but that will simply emphasise my point that if it were in the plugins it would have been fixed by upstream.

**Comment by jamtur01** [comment]
The last release seems to have fixed the issue. I added the widget to the plugin also: https://github.com/opnsense/plugins/pull/4166.
