### ISSUE TITLE
Cannot declare class Opnsense\Routing\Gateways upgrading from 24.1.10 -> 24.7

### ISSUE THREAD

**Issue by amnnku** [opnsense/core#7687]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [ x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [ x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

Unable to boot my opnsense after an upgrade due to the error in the title.

Name already in use /use/local/opnsense/MVC/app/library/opnsense/routing/gateways.php line 38

*Tip*: to validate your setup was working with the previous version, use opnsense-revert (https://docs.opnsense.org/manual/opnsense_tools.html#opnsense-revert)

Unable to revert as no internet on that machine. Cannot find docs to revert manually or offline,

Upgrade

**Expected behavior**

Bootup so I am able to debug any other errors from a major upgrade,

**Describe alternatives you considered**

opnsense-revert but do not know how to revert when downloading files from another machine

OPNsense 24.7 (amd64).

**Comment by fichtner** [comment]
Just move this file to /root and it should start working. It seems to be a leftover of when the package manager database crashed so it never managed to clear stale files?
