### ISSUE TITLE
Cron validation issue on hour field

### ISSUE THREAD

**Issue by alisamar** [opnsense/core#769]
Following regular expression does not validate the hour after 14! (https://github.com/opnsense/core/blob/master/src/opnsense/mvc/app/models/OPNsense/Cron/Cron.xml#L27)

`/^((?:\*|[1-2][0-3]|0[0-9]|[0-9])(,{1}|-{1}|$))+$/`

see: https://regex101.com/r/rK8oD4/2

**Comment by alisamar** [comment]
following regex can solve the issue

`/^((?:\*|([1][0-9]|[2][0-3])|0[0-9]|[0-9])(,{1}|-{1}|$))+$/`

see: https://regex101.com/r/rK8oD4/3

**Comment by AdSchellevis** [comment]
@alisamar looks good, thanks for working this out!
