### ISSUE TITLE
kerberos or kerberos-sec

### ISSUE THREAD

**Issue by Stricken1670** [opnsense/core#7694]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guidelines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

In the interface, I have a port alias which allows various ports on our authentication server, including kerberos. Which is also suggested when I try to edit the alias and type `kerb`. But... kerberos does nothing since a recent change. See how there is no rule for port 88?

```
pass in quick on igb0_vlan110 inet proto tcp from any to <sec_server> port = 80 flags S/SA keep state label "680cbba83e76ecabd1c297847c9e57a5"
pass in quick on igb0_vlan110 inet proto tcp from any to <sec_server> port = 443 flags S/SA keep state label "680cbba83e76ecabd1c297847c9e57a5"
pass in quick on igb0_vlan110 inet proto tcp from any to <sec_server> port = 464 flags S/SA keep state label "680cbba83e76ecabd1c297847c9e57a5"
pass in quick on igb0_vlan110 inet proto tcp from any to <sec_server> port = 53 flags S/SA keep state label "680cbba83e76ecabd1c297847c9e57a5"
pass in quick on igb0_vlan110 inet proto tcp from any to <sec_server> port = 389 flags S/SA keep state label "680cbba83e76ecabd1c297847c9e57a5"
pass in quick on igb0_vlan110 inet proto tcp from any to <sec_server> port = 636 flags S/SA keep state label "680cbba83e76ecabd1c297847c9e57a5"
pass in quick on igb0_vlan110 inet proto udp from any to <sec_server> port = 464 keep state label "aa502882ecbcd51b2f45949070959ec1"
pass in quick on igb0_vlan110 inet proto udp from any to <sec_server> port = 123 keep state label "aa502882ecbcd51b2f45949070959ec1"
pass in quick on igb0_vlan110 inet proto udp from any to <sec_server> port = 53 keep state label "aa502882ecbcd51b2f45949070959ec1"
```

So I checked /etc/services and... kerberos is now called kerberos-sec

```
# grep kerberos /etc/services
kerberos-sec	 88/tcp	   kerberos	# krb5	# Kerberos (v5)
kerberos-sec	 88/udp	   kerberos	# krb5	# Kerberos (v5)
kerberos-adm	749/tcp	   #Kerberos administration (v5)
kerberos-adm	749/udp	   #Kerberos administration (v5)
kerberos-iv	750/udp	   kdc		# Kerberos (v4)
krb_prop	754/tcp	   krb5_prop	# kerberos/v5 server propagation
```

Whilst on Linux hosts, it's called kerberos:
```
%  grep kerberos /etc/services
kerberos        88/tcp          kerberos5 krb5  # Kerberos v5
kerberos        88/udp          kerberos5 krb5  # Kerberos v5
```

And since this used to work for ages, I'm positive this is a recent change.
Please harmonize the name for this port.

**Comment by AdSchellevis** [comment]
`kerberos-sec` since at least 20 years https://github.com/freebsd/freebsd-src/commit/39280ed3845f971f0d2a7682bf41fb3ccbe4b35f

**Comment by Stricken1670** [comment]
Try creating a port alias with kerberos and some other port, and a rule using that port. I'm positive it will create a rule only for the other port. I had to specify port 88 in the port alias.

And with older opnsense versions this worked fine.

**Comment by AdSchellevis** [comment]
<img width="1129" alt="image" src="https://github.com/user-attachments/assets/2e4d6f40-3510-4f3d-9584-0a7c2296e769">

expected output on my end, kerberos not being in the list (unless already specified elsewhere)

**Comment by Stricken1670** [comment]
And what happens with an older version of opnsense? 24.1 for example

**Comment by abbra** [comment]
Official IANA port service name for Kerberos is `kerberos` (see https://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.txt). This does not really matter because `/etc/services` format includes `kerberos` as an alias in FreeBSD version. 

It looks to me that OPNSense is not working properly with services' aliases, so may be the actual problem here is to fix alias usage?

**Comment by AdSchellevis** [comment]
likely this then https://github.com/opnsense/core/commit/2d8aff2fe5b7c5029a98abbcac2981b13b0d65b3, probably a regression of https://github.com/opnsense/core/commit/edd7a00a3986ffb86eecf2d0a74bd13ed0b93957

**Comment by Stricken1670** [comment]
Thanks, much appreciated.
