### ISSUE TITLE
Problem to manage certificates after upgrade to 24.7_9

### ISSUE THREAD

**Issue by ByLsXD** [opnsense/core#7696]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

After updating from version 24.1.10_8 to 24.7_9, the certificate management/creation part is not fully functional as it was before; it seems something has broken.

Previously, in version 24.1.10_8, it was possible to "unlink" a certificate from a user in System > Access > Users after creating it for a specific user. Now, the "unlink" button for the certificate no longer exists, and consequently, it's also not possible to remove the certificate in System > Trust > Certificates.

Another issue I've noticed is that when creating a user certificate in version 24.7_9, in the VPN > OpenVPN > Client Export screen, the certificate appears but is not associated with any user.

Software version used and hardware type if relevant, e.g.:

OPNsense 24.7_9 (amd64).
Intel® Xeon™ E5-2650v4 2.2Ghz 
Intel® 82575GB Gigabit Network Connection

**Comment by AdSchellevis** [comment]
> Previously, in version 24.1.10_8, it was possible to "unlink" a certificate from a user in System > Access > Users after creating it for a specific user. Now, the "unlink" button for the certificate no longer exists, and consequently, it's also not possible to remove the certificate in System > Trust > Certificates.

This is intentional behavior, the "link" in the user manager is merely a common name match, see also https://forum.opnsense.org/index.php?topic=41760.msg205243#msg205243

> Another issue I've noticed is that when creating a user certificate in version 24.7_9, in the VPN > OpenVPN > Client Export screen, the certificate appears but is not associated with any user.

It should match when the common name equals the username, if it doesn't, we should double check as we might have missed a spot there.

**Comment by AdSchellevis** [comment]
@ByLsXD if you try to delete it, where does it think it's in use (it should popup an error)

**Comment by AdSchellevis** [comment]
@ByLsXD https://github.com/opnsense/core/commit/2ad84c1932644f7e9a76c32ae6599bcbd842247f should fix the name matching in the export, if there's another issue with the "link" status, can you open a new ticket for that item? 

`opnsense-patch 2ad84c1` should install this fix.
