### ISSUE TITLE
Config backups via API failing after 24.7 update

### ISSUE THREAD

**Issue by USBAkimbo** [opnsense/core#7697]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**
- After updating to 24.7, my backup script using the API is no longer working

**To Reproduce**
- Create a new user
- Grant the user effective privileges `GUI - Diagnostics: Configuration History`
- Create an API key and download it
- Take the key and secret from the file and use it in the below command
```
curl -k -u "mykey":"mysecret" https://opnsense_ip_here/api/core/backup/download -o "backup.xml"
```
- Edit the `backup.xml` file and you should see content like this
```
{"errorMessage":"Endpoint not found"}
```

**Expected behavior**
- A plain text XML file is created containing the backup

**Describe alternatives you considered**
- Manual backups (pls no)
- Google Drive (no thanks)
- Nextcloud (I don't run it in my stack)

**Relevant log files**
- I submitted a crash report as it showed up in the UI
- I included the below unique string as a reference
```
HVXlVji19cIuE9uz6fhZ
```
**Environment**
- VM running in Proxmox

**Comment by AdSchellevis** [comment]
upgraded to the latest version?

**Comment by fichtner** [comment]
Yes, should be fixed in 24.7_9 already.

**Comment by USBAkimbo** [comment]
Hey, yeah I'm on the latest version - I upgraded the firewall before I
posted this thread

Has there been a new release in the hours since?

**Comment by fichtner** [comment]
BTW https://github.com/opnsense/plugins/blob/stable/23.7/sysutils/api-backup/Makefile#L3

**Comment by USBAkimbo** [comment]
Ah, must be something I've missed - I see a scheduled backup ran and
completed

I'll do another update check and reboot and try again

You're right on the endpoint too and I have a typo above - my actual script
has "/this" at the end

**Comment by USBAkimbo** [comment]
Final update - latest update fixed it

I then had a problem with doing the backup as a cron job, but it was because a variable had been cut in half so the password was wrong
