### ISSUE TITLE
Inconsistancy: NAT page -> resovles aliasses, Rules page -> shows aliases

### ISSUE THREAD

**Issue by sjorge** [opnsense/core#77]
I noticed that when adding a port forwarding and using aliasses for port and/or redirect destination they get 'resolved' to there value e.g. 8080 or 172.12.30.1, the rules pages lists the associated rules with there alias names.

This should be consistent (preferably listing aliases in both cases).

**Comment by AdSchellevis** [comment]
Your correct, the old code tried to resolve the names but that differs from the rules page. The version that's checked in now displays names, my suggestion would be to remove the unused code for resolving the names to keep it a little cleaner.
