### ISSUE TITLE
Certificate is marked as not in use

### ISSUE THREAD

**Issue by Krustak** [opnsense/core#7702]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [ ] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [ ] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

Hello,

opening new bug report to continue this one
https://github.com/opnsense/core/issues/7696

patch applied, it seems like part of the problem is fixed

when I try to add new certificate to user (another certificate) in System: Access: Users Im forwarded to System: Trust: Certificates where I can create new certificate

Once I do, new certificate is visible under user account in System: Access: Users but is marked as NOT IN USE in System: Trust: Certificates 

OPNsense 24.7_9

thank you

**Comment by AdSchellevis** [comment]
that's technically correct, a certificate exists (which has the same common name), which is not needed for the system to function.

**Comment by Krustak** [comment]
OK, thats fine, thus it would be better to remove that column?

Now i have most of the certificates generated in previous version marked as "IN USE" and new certificates generated in 24.7_9 not marked as "IN USE"

**Comment by AdSchellevis** [comment]
ah, the old ones are "in use" because of the old unused link. We can ignore these indeed.
