### ISSUE TITLE
Download of pkcs12 / pfx not recognized by Windows with MVC rewrite

### ISSUE THREAD

**Issue by mimugmail** [opnsense/core#7703]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

Hi, I have a Firewall here with 24.7_9 and when I download a certificate as pfx with a password and double click in Windows, I get an error like enclosed (before even typing a password):

![image](https://github.com/user-attachments/assets/d248c9e4-6583-4ebd-955c-49b8a0b1c4c1)

Seems it's marked as wrong type somewhere

**To Reproduce**

see above

**Expected behavior**

**Describe alternatives you considered**

A clear and concise description of any alternative solutions or workaround you considered.

**Screenshots**

Se above

**Relevant log files**

If applicable, information from log files supporting your claim.

**Additional context**

**Environment**

Software version used and hardware type if relevant, e.g.:

Versions
OPNsense 24.7_9-amd64
FreeBSD 14.1-RELEASE-p2
OpenSSL 3.0.14

**Comment by AdSchellevis** [comment]
same as https://github.com/opnsense/core/issues/7251 ?

**Comment by Weltherrscher** [comment]
No, not the same, i have a similar issue:
An exported p12 from WebUI cant be read with openssl 1.1.1w and 3.3.1 under windows.
(Didn't try Linux by now.)

Steps to reproduce:
1. Export the internally used certificate (generated on the OPNsense) as PKCS12 in the WebUI
2. Import the file into the Keystore Explorer under Windows, actually doesn't matter, as it's a Java application
3. Error message: file corrupt or password incorrect (it WAS correct, tried 4 times)

Tried a workaround:
1. Exported the certificate and key in PEM format from the OPNsense
2. Using openssl (under Windows) created a PKCS12 with the cert.pem, key.pem and the same password as above
3. Imported the file into the Keystore Explorer
4. Works.

Also, example output from openssl -info for three different generated p12 files:
cert.p12 -> Export from WebUI
bundle_v1.1.p12 -> exported PEMs combined with openssl 1.1.1w
bundle_v3.p12 -> exported PEMs combined with openssl 3.3.1

openssl -info:
` e:\Progs\Security\openssl-3\x64\bin>openssl pkcs12 -info -in cert.p12
B47E0000:error:0680007B:asn1 encoding routines:ASN1_get_object:header too long:..\crypto\asn1\asn1_lib.c:105:

e:\Progs\Security\openssl-3\x64\bin>openssl pkcs12 -info -in bundle_v1.1.p12
Enter Import Password:

MAC: sha1, Iteration 2048
MAC length: 20, salt length: 8
PKCS7 Encrypted data: pbeWithSHA1And40BitRC2-CBC, Iteration 2048
Error outputting keys and certificates
E4680000:error:0308010C:digital envelope routines:inner_evp_generic_fetch:unsupported:..\crypto\evp\evp_fetch.c:355:Global default library context, Algorithm (RC2-40-CBC : 0), Properties ()

e:\Progs\Security\openssl-3\x64\bin>openssl pkcs12 -info -in bundle_v3.p12
Enter Import Password:

MAC: sha256, Iteration 2048
MAC length: 32, salt length: 8
PKCS7 Encrypted data: PBES2, PBKDF2, AES-256-CBC, Iteration 2048, PRF hmacWithSHA256
Certificate bag
Bag Attributes
    localKeyID: 57 3C ... 60 87
subject=C=DE, blah blubb server-rsa
issuer=C=DE, blah blubb -ca
-----BEGIN CERTIFICATE-----
MIIHaDkBFg9pdEBhbHRlbmhlaW0uaXQxHjAc... `

**Comment by AdSchellevis** [comment]
I don't see anything weird in our code, but there seems to be something off here, we're using the standard functions offered by php to create these.

https://github.com/opnsense/core/blob/809e3be395a5681480fc5dcb5c67a692613546c1/src/opnsense/mvc/app/library/OPNsense/Trust/Store.php#L504

**Comment by AdSchellevis** [comment]
Ok, this was quite unexpected. the endpoint offers the right data, but then the browser seems to return something "random" . https://github.com/opnsense/core/commit/b3aa9104380851d5c5ab49e96d72737c5f440837 should prevent this from happening.

```
opnsense-patch b3aa910
```

**Comment by Weltherrscher** [comment]
That was quick! =)

Confirmed working:
cert_new.p12 -> new export from OPNsense (base64)
cert_new_d.p12 -> decoded base64 cert

**e:\Progs\Security\openssl-3\x64\bin>openssl pkcs12 -info -in cert_new.p12**
702E0000:error:068000A8:asn1 encoding routines:asn1_check_tlen:wrong tag:..\crypto\asn1\tasn_dec.c:1194:
702E0000:error:0688010A:asn1 encoding routines:asn1_item_embed_d2i:nested asn1 error:..\crypto\asn1\tasn_dec.c:349:Type=PKCS12

**e:\Progs\Security\openssl-3\x64\bin>openssl pkcs12 -info -in cert_new_d.p12**
Enter Import Password:

MAC: sha256, Iteration 2048
MAC length: 32, salt length: 8
PKCS7 Encrypted data: PBES2, PBKDF2, AES-256-CBC, Iteration 2048, PRF hmacWithSHA256
Certificate bag
Bag Attributes
    localKeyID: 57 3C ... 60 87
    friendlyName: blah (RSA)
subject=C=DE, blahblubb-server-rsa
issuer=C=DE, blahblubb-ca
-----BEGIN CERTIFICATE-----
MIIHaDCCBw+gAwIBAgIBAjAKBggqhkjOPQQ...

**Comment by AdSchellevis** [comment]
@Weltherrscher thanks for confirming, will likely be released in the next minor

**Comment by fichtner** [comment]
It was fixed in 24.7.1 already.

**Comment by fichtner** [comment]
Some of this incompatibility is because of OpenSSL 1.1 vs. 3.0 defaults. Can't do much more in community scope than mention this.
