### ISSUE TITLE
interfaces: interfacesInfoAction() and actual IP addresses on the GUI-based interface do not match extended reality of the underlying ifconfig output

### ISSUE THREAD

**Issue by fichtner** [opnsense/core#7707]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

There are multiple issues in the way the information is being collected. There is no distinction between IPv4 and IPv6 devices (like STF or PPPOE) as well as no concept of a primary IP. Listing the first address is a problem, especially for IPv6 where SLAAC can get in the way.

**To Reproduce**

Dashboard "Interfaces" widget or interfaces overview page.

**Expected behavior**

Work like before. The old widget was pretty straightforward and is now mostly overwhelmed with irrelevant API return data. But the overview page needs fixing too.

TODO

- [x] Adjust backend to allow returning primary addresses for easy consumption
- [x] Use new backend data to fill the correct interfaces widget data
- [ ] Check SLAAC vs. manual tracking ID in WAN, primary behaviour seems wrong now
- [ ] Check overview page just to be sure and adjust accordingly

**Describe alternatives you considered**

As reality is complicated there is no alternative to going back to our best practices that have been refined with users for many years.

**Screenshots**

N/A

**Relevant log files**

N/A

**Additional context**

https://forum.opnsense.org/index.php?topic=41825.0

**Environment**

For dashboard since 24.7 but for overview page a bit earlier.

**Comment by AdSchellevis** [comment]
It might be best to collect some examples first before aiming for fixes. In most cases ifconfig does contain the right information, but sorting is wrong when it comes to the concept of "primary". 

stf is likely the only real edge case as it should be an interface like `gif`/`gre` but isn't if I'm not mistaken.

**Comment by fichtner** [comment]
There's no way around emulating this the way the old widget did, which is why I extended the backend call a bit 67dbbfb30d0a to do the same as:

https://github.com/opnsense/core/blob/stable/24.1/src/www/widgets/widgets/interface_list.widget.php#L157-L158

**Comment by fichtner** [comment]
overview page is fine, works differently showing all addresses anyway
