### ISSUE TITLE
dashboard: ipsectunnels widget: Show children of connections

### ISSUE THREAD

**Issue by Monviech** [opnsense/core#7708]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**

Something small I want to work on. Showing the children of ipsec connections in the same widget.

**Describe the solution you like**

Maybe adding a second column next to the first, and then adding the children into the same rows as their connection parent.

**Comment by Monviech** [comment]
Integrating Phase2 creates a "one to many" relationship between phase1 and phase2, which makes the layout and code really complicated. I have tried it out and its just not that nice, especially the layout is troublesome.

- It might be the best choice to either create a separate widget that only shows phase2 entries with data like: phase2desc, status, local-ts, remote-ts, life-time, bytes-in, bytes-out
- Another idea that @AdSchellevis had was to integrate aggregated stats into the API of Phase1. That would also make things easier.

**Comment by AdSchellevis** [comment]
@Monviech this https://github.com/opnsense/core/commit/809e3be395a5681480fc5dcb5c67a692613546c1 is what I thought might be practical. For the dashboard we should then be able to use the same stats. 

In most cases you only want to know a tunnel is active and passing traffic, when more children exist, the detailed view is available in the normal status overview anyway.

**Comment by Monviech** [comment]
@AdSchellevis Nice, thank you for addint that to the API. Now it's easy to enhance the widget. :)
