### ISSUE TITLE
mvc: normalize multiple slashes into single slashes for URLs

### ISSUE THREAD

**Issue by fichtner** [opnsense/core#7709]
**Important notices**

Our forum is located at https://forum.opnsense.org , please consider joining discussions there in stead of using GitHub for these matters.

Before you ask a new question, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

For consistent behaviour and error handling it would be beneficial to normalize slashes in URLs such as "//api///this/that" into "/api/this/that" which helps with consistent API error handling.

**Comment by fichtner** [comment]
There is still a bit of funky behaviour:

/ui/core/firmware#status -> works
//ui/core/firmware#status-> page not found
///ui/core/firmware#status -> PHP error:

`Warning: Trying to access array offset on value of type bool in /usr/local/opnsense/mvc/app/library/OPNsense/Mvc/Router.php on line 118 Deprecated: str_starts_with(): Passing null to parameter #1 ($haystack) of type string is deprecated in /usr/local/opnsense/mvc/app/library/OPNsense/Mvc/Router.php on line 120 Warning: session_set_cookie_params(): Session cookie parameters cannot be changed after headers have already been sent in /usr/local/opnsense/mvc/app/library/OPNsense/Mvc/Session.php on line 54 Warning: session_set_cookie_params(): Session cookie parameters cannot be changed after headers have already been sent in /usr/local/opnsense/mvc/app/library/OPNsense/Mvc/Session.php on line 61 Warning: session_start(): Session cannot be started after headers have already been sent in /usr/local/opnsense/mvc/app/library/OPNsense/Mvc/Session.php on line 62 Warning: Undefined global variable $_SESSION in /usr/local/opnsense/mvc/app/library/OPNsense/Mvc/Session.php on line 65 Warning: Cannot modify header information - headers already sent by (output started at /usr/local/opnsense/mvc/app/library/OPNsense/Mvc/Router.php:118) in /usr/local/opnsense/www/index.php on line 81`

Also, when using "." or ".." components between slashes it normalises (that's nice) and also redirects which is what I think we should do with multiple slashes as well (making them disappear on the redirect). It might fix the spot you patched automatically?

**Comment by AdSchellevis** [comment]
I probably missed a spot there,  I thought about redirecting as well, but it adds more glue which doesn't really bring a lot. The behavior is more or less the same as a page not found now, always render, so you know what you've offered.
