### ISSUE TITLE
24.7_5 and 24.7_9 Upgraded from 24.1.10, packet capture does not download.  Link is to pcap displayed in browser.

### ISSUE THREAD

**Issue by upended** [opnsense/core#7714]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

As this is a new error not present in the previous version used prior to upgrade, there is no existing issues / reports.

**Describe the bug**

Select a packet capture, then stop. Clicking on the link to save the file to your computer will open a page to https:/firewall_IP_address/api/diagnostics/packet_capture/download/xxxxxx-xxxxx-xxxxx-xxxxx-xxxxxxx and display the zip file in the browser as an html page.

This fuction was working correctly in 24.1.10 as I was using extensively for the past several days, then decided to upgrade.

*Tip*: to validate your setup was working with the previous version, use opnsense-revert (https://docs.opnsense.org/manual/opnsense_tools.html#opnsense-revert)

**To Reproduce**

Go to  Interfaces: Diagnostics: Packet Capture

Use the following settings
       Interface : WAN
        All other settings default
   
Or these settings
       Second test
      Interface VLAN 10
      Promiscuous : On
      Packet count : 10000

Or these settings
     Third test
     Interface LAN
     Promiscuous : on
     Address family : IPv4
    Description : LAN capture IPv4 

Let the capture run for any period, stop the capture and click on the download icon.  

**Expected behavior**

The zip file produced by the firewall should start to download.

**Describe alternatives you considered**

A clear and concise description of any alternative solutions or workaround you considered.

None available.  When on the /api/diagnostics/packet_capture/download/xxxxxx-xxxxx-xxxxx-xxxxx-xxxxxxx page, attempting to save file will result in saving an html page.  Attempting to change the file extension from html to zip when saving results in an error.

**Screenshots**

Version with issue 24.7_5 and 24.7_9

**Comment by upended** [comment]
Screen snapshot is not saving to post.  Not receiving error message or confirmation.

**Comment by AdSchellevis** [comment]
could be a browser thing, the headers offered to the client look ok on my end.
<img width="808" alt="image" src="https://github.com/user-attachments/assets/b56fc302-3a90-4f41-bc78-01202f79437a">

**Comment by ivulit** [comment]
Hi. The same issue here, 24.7_9. I've checked in different browsers and different devices.
The headers:
![headers](https://github.com/user-attachments/assets/005e51d2-80e4-4228-959b-b3d724bf65f5)

**Comment by AdSchellevis** [comment]
Although it does seem to work on my end, this https://github.com/opnsense/core/commit/790a32c916d3f63ee07fe025f88e028d28bcbdd6 is likely the issue. Timing differences could result in headers being send anyway, but this doesn't seem to be a guarantee.

To test, just run the following on the console (and try to download the file again):

```
opnsense-patch 790a32c
```

**Comment by upended** [comment]
Thank you, corrected issue.

**Comment by AdSchellevis** [comment]
@upended thanks for confirming
