### ISSUE TITLE
monit: widget code cleanup

### ISSUE THREAD

**Issue by fichtner** [opnsense/core#7719]
**Important notices**

Our forum is located at https://forum.opnsense.org , please consider joining discussions there in stead of using GitHub for these matters.

Before you ask a new question, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

As witnessed by #7705 the status return from monit API is a bit inconsistent / hard to handle from the consumer side. Maybe this could be simplified to a few defined errors and one good status code (mapped to 0),

**Comment by Monviech** [comment]
As discussed with @fichtner and @swhite2, changing the widget to only evaluate if the status is either 0 (ok) or =! 0 (not ok) is the best choice. The API does not have to be changed for that, only the widget.
