### ISSUE TITLE
Chrome: No Scrollbar at System: Access: Users -> System Privileges selection

### ISSUE THREAD

**Issue by DokuKaefer** [opnsense/core#772]
There is no Scrollbar in Google Chrome at the System Privileges selection.
Firefox and Internet Explorer is good.

left Chrome - right Firefox

![scrollbar](https://cloud.githubusercontent.com/assets/11537653/12962957/463c22c4-d048-11e5-9e4f-dd62accea9ce.png)

**Comment by fichtner** [comment]
will be fixed in #709 soon
