### ISSUE TITLE
Captive portal Issues 

### ISSUE THREAD

**Issue by Vivekmauli14** [opnsense/core#7722]
Hi,

While I upgraded my system from 24.1 to 24.7, I faced some issues in the user login of captive portal.

1. While we are able to login to the portal at :8000, we are required to refresh the page manually. Then only I am seeing the logout button.

2. Even when clicking on logout, a user is not getting logged out, I tried updating the firewall but the issue persisted. 

I noticed the API logoffAction() in [here ](https://github.com/opnsense/core/blob/master/src/opnsense/mvc/app/controllers/OPNsense/CaptivePortal/Api/AccessController.php)

That it is returning always {"clientState":"UNKNOWN","ipAddress":"192.168.1.1"}

This is why the whole login mechanism is getting failed. Am I the only one facing this issue ?

Looking forward for a resolution

Thanks,
VivekSP

**Comment by fichtner** [comment]
Suppose that was #7740
