### ISSUE TITLE
Thermal sensors elevated highly fluctuating core temperatures

### ISSUE THREAD

**Issue by NOYB** [opnsense/core#7727]
Thermal sensors widget reporting elevated and highly fluctuating Core temperatures by about 10 to 20 degrees Celsius.

Typically reporting mid 50's to mid 60's Celsius with a high amount of fluctuation.

Shell sysctl typically reports low to mid 40's Celsius and much more stable.

**Comment by NOYB** [comment]
From this:
![Snap1](https://github.com/user-attachments/assets/e9454c75-b7f8-4996-883b-7bd85c2852b0)

To this:
![Snap2](https://github.com/user-attachments/assets/10591cf8-cb76-4b33-99d0-e7b8e3a7b86a)

**Comment by fichtner** [comment]
#7730
