### ISSUE TITLE
"Import CRL" removes externally created, signed and revoked Certificates from CRL

### ISSUE THREAD

**Issue by NadeoWolf** [opnsense/core#7748]
**Important Notices**

Before you add a new report, we kindly ask you to acknowledge the following:

- [X] I have read the contributing guidelines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the Bug**

After importing an externally created CRL, the info shows no revoked certificates.

**To Reproduce**

1. Create internal Root CA and Sub-CA.
2. Download Sub-CA key and certificate.
3. Create external certificates and corresponding CRL.
4. Go to System -> Trust -> Revocation.
5. Press Edit on the Sub-CA entry RL.
6. Change Method to Import existing.
7. Add Description.
8. Insert externally created CRL data.
9. Click on 'Apply'.
10. Now check 'Show Certificate Info' on the same Sub-CA RL.
11. It will show "No Revoked Certificates."

**Expected Behavior**

A list of the externally added revoked certificates.

In the provided CRL, they are present (checked with `openssl crl -in crl.pem -text`).

**Describe Alternatives You Considered**

- Removing the private key from the Sub-CA to prevent internal issuance of a new CRL by OPNsense.
- Overriding the CRL file in the OpenVPN config after each save (working but not practical).
- Using OCSP: not an option.
- Creating certificates through OPNsense: not an option for 100+ certificates each semester.
- Using the `crl-verify` custom option in a non-legacy OpenVPN instance is not possible due to the missing "Custom Options" field.
- Using the `crl-verify` custom option in a legacy OpenVPN server works as expected, but the custom option is marked as "deprecated."

**Screenshots**

N/A

**Relevant Log Files**

No errors or other relevant logs are present.

**Additional Context**

We want to use OpenVPN with about 160 clients (teachers, students, and servers) changing every Semester for a specific project. After creating a Sub-CA for the teacher, we want to issue certificates to each student so they can join their group (firewall rules isolate groups). By using this approach, the teacher does not need access to OPNsense, and the management of the short-lived certificates can be automated.

**Environment**

OPNsense 24.7.1 (amd64)  
OpenSSL 3.0.14  

Intel(R) Xeon(R) Silver 4208 CPU @ 2.10GHz (8 cores, 8 threads)  
8 GB RAM

**Comment by AdSchellevis** [comment]
@NadeoWolf this https://github.com/opnsense/core/commit/fd516e8c9972cee6f5b92dd46ed549f62013858c should fix the import part, it looks like the input was ignored on save.
