### ISSUE TITLE
Surprising redirection when hitting page with no permission

### ISSUE THREAD

**Issue by andreas-p** [opnsense/core#776]
I'm acting as a user with some permissions removed (one too much, obviously).

When hitting the 'Schedule' tab on the Intrusion Detection page, I'm getting redirected to an arbitrary page (in my case /getstats.php) instead of being notified of an illegal access.
- When navigating to a non-permitted page, this shouldn't redirect somewhere but display "access denied" or so. A hint, which privilege is missing, might be helpful.
- The Schedule tab shouldn't be there or be disabled, when not permitted to press.

**Comment by AdSchellevis** [comment]
The specific case could easily be fixed, by adding cron to the intrusion detection acl, which probably is for the moment the most sensible thing to do (the module depends on it).
Although the generic pattern is a different story, some things are fixable within the current product, some things just break user experience for others.

If someone wants to change the generic redirect behaviour, they have to make very sure the first page after login always bounces to something the user can access (not being an error page).
Telling the user what he/she is missing is probably not a very good idea from a security perspective (your teaching the attacker), but making things more explicit in changing user/group acl's is probably worth the effort.

I like to make the next proposal:
1)  Change issue https://github.com/opnsense/core/issues/709 to "improve ACL selection", which could include multi select, show contents, and possibly order to prevent some of the redirect issues.
2) Add an issue for the Intrusion detection, to extend the ACL to include the cron part
3) Keep this issue, with my remarks about login redirection and leave it open for a couple of months. If after that period nobody worked on it, and there doesn't seem to be a big demand. Close it.

**Comment by AdSchellevis** [comment]
timeout, no feedback.
