### ISSUE TITLE
system: interfaces statistics widget table view on expansion

### ISSUE THREAD

**Issue by PanMat** [opnsense/core#7766]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**

I just upgraded to 24.7.1 and love the new dashboard UI, the pie charts and graph visualizations are quiet pleasant...well done team!!

But there is one part i.e. "Interface Statistics" where I liked the old theme table because it was easier to read the stats on "Errors In" and "Errors Out" across all interfaces at a glance but now have to hover mouse on each interface manually.

**Describe the solution you like**

If there is option to show "Interface Statistics" in tabular format for easier readability.

**Describe alternatives you considered**

none

**Additional context**

Filing this request as per Franco's direction - https://forum.opnsense.org/index.php?topic=42145.0

**Comment by dstr-wpd** [comment]
Also services widget is now double the size and wont fit to a fullhd monitor without scrolling.

**Comment by bagobones** [comment]
> Also services widget is now double the size and wont fit to a fullhd monitor without scrolling.

The MIN hight for the Traffic and CPU graphs is HUGE on a 1080p res screen. The little gauge graphs also jump from small / unreadable to big very quickly.

Minor issues but this could use a lot more fine tuning.

**Comment by fichtner** [comment]
@dstr-wpd @bagobones if still not fix please open separate tickets. This one is done and shipped.
