### ISSUE TITLE
OpenVPN DCO mode: no fields for Server IPv4 / IPv6

### ISSUE THREAD

**Issue by cs-1** [opnsense/core#7772]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

When configuring an OpenVPN instance it's necessary to configure Server IPv4 (and IPv6) addresses with prefix for "TUN" and "DCO (experimental)" mode. Despite the fields being present for "TUN", they disappear as soon as "DCO (experimental)" is selected.

**To Reproduce**

1. Go to VPN>OpenVPN>Instances
2. Click on "+" to add an instance.
3. Select "DCO (experimental)" as "Type".
4. The fields "Server (IPv4)" and "Server (IPv6)" disappear.

**Expected behavior**

The fields "Server (IPv4)" and "Server (IPv6)" should be present and editable.

**Describe alternatives you considered**

There're no alternatives since "--disable-dco" is configured if the type "DCO (experimental)" is not selected, hence disabling DCO globally.

**Screenshots**

!["TUN" mode selected](https://github.com/user-attachments/assets/25c42baf-151d-4aab-9b44-c4d4ed5dff38)

vs.

!["DCO (experimental)" selected](https://github.com/user-attachments/assets/59df6ea5-f6ce-42ae-83a1-3e865ab6deba)

**Relevant log files**

N/N

**Additional context**

N/N

**Environment**

OPNsense 24.7.1-amd64
FreeBSD 14.1-RELEASE-p3
OpenSSL 3.0.14

**Comment by doktornotor** [comment]
If you need a quick workaround, just click Save, those fields will appear, conveniently highlighted with an error message.

**Comment by cs-1** [comment]
@AdSchellevis thanks for the quick fix, I'll cherry pick it tomorrow morning and try DCO.

@fichtner If it's not too much trouble, could you add this fix to the next 24.7.x release? Pretty please. :)

**Comment by fichtner** [comment]
Queued up for 24.7.2 2 hours ago. ;)
