### ISSUE TITLE
Search in the log breaks when using capital letters or combinations of numbers with special characters

### ISSUE THREAD

**Issue by imarlan** [opnsense/core#7778]
After upgrading OPNsense to version 24.7, I have found a problem with the log search. When I enter some combinations of numbers with special characters or capital letters into the search, I get an empty response.
![Screenshot 2024-08-16 111756](https://github.com/user-attachments/assets/ac83da0b-790b-4c77-8614-efe15557c6ae)
![Screenshot 2024-08-16 111822](https://github.com/user-attachments/assets/9b5d3bc0-803a-4e3d-b56a-76949ed111c6)
![Screenshot 2024-08-16 111920](https://github.com/user-attachments/assets/07646c60-a31c-435d-8ff3-636beacbfe8e)
![Screenshot 2024-08-16 112042](https://github.com/user-attachments/assets/79d956e9-e772-4b42-9b7e-b1414fe828c8)

**Comment by swhite2** [comment]
@imarlan https://github.com/opnsense/core/commit/44a1ea309622f08decaf447c508b131b9c937725 should be it:

```
# opnsense-patch 44a1ea3
```

**Comment by imarlan** [comment]
> @imarlan [44a1ea3](https://github.com/opnsense/core/commit/44a1ea309622f08decaf447c508b131b9c937725) should be it:
> 
> ```
> # opnsense-patch 44a1ea3
> ```

Installed an update. The case in the search no longer causes a problem. However, combinations of symbols with numbers still lead to an empty response.
![Screenshot 2024-08-22 095758](https://github.com/user-attachments/assets/190d45a8-2641-4fe3-9898-8909a0e2b922)
![Screenshot 2024-08-22 095814](https://github.com/user-attachments/assets/c60d626d-20d3-4f33-a881-90a6e8b91d04)
![Screenshot 2024-08-22 095917](https://github.com/user-attachments/assets/4eb40457-2e57-4614-a064-d1ffa63c1ce0)
![Screenshot 2024-08-22 095935](https://github.com/user-attachments/assets/37ec21d3-be2d-4627-8423-0e595182297b)

**Comment by fichtner** [comment]
Some characters get stripped in the controller so they end up not being searched for in the resulting string. We are aware and discussing a solution at the moment.
