### ISSUE TITLE
dhcpv6 server parge: Issue  fixed in 15.7.23 (partly) back in 16.1.2

### ISSUE THREAD

**Issue by bringha1** [opnsense/core#778]
dhcpv6 server page throws

` 57 Warning: Illegal string offset 'lan' in /usr/local/www/services_dhcpv6.php on line 58 Warning: Illegal string offset 'opt1' in /usr/local/www/services_dhcpv6.php on line 57 Warning: Illegal string offset 'opt1' in /usr/local/www/services_dhcpv6.php on line 58 Warning: Illegal string offset 'opt2' in /usr/local/www/services_dhcpv6.php on line 57 Warning: Illegal string offset 'opt2' in /usr/local/www/services_dhcpv6.php on line 58`

which is shown on the very top of the page, partly hidden by the dark bar on top (therefore here the message is cut off at the beginning as not being cut&paste-able. Issue is also creating entry in the Absturzreporter (crash reporter)

**Comment by AdSchellevis** [comment]
This page will probably be re-factored completely within a couple of weeks, I will close this issue when its done.
(ipv4 dhcp is currently being re-factored)

**Comment by fichtner** [comment]
This seems to be a different issue and is already addressed with 4f0a083e9f36dd823316 so I'm going to push this to 16.1.3 and close now. :)
