### ISSUE TITLE
Unbound: Info text for field ""Register DHCP Static Mappings" is outdated (due to UI changes)

### ISSUE THREAD

**Issue by bernhardkohlhaas** [opnsense/core#7781]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

In the OPNsense admin UI (in 24.7.1) the info text for the input field "Register DHCP Static Mappings" under "Services: Unbound DNS: General" is outdated. The domain is no longer set in "System:General Setup", but in "System: Settings: General". (Luckily the link still works, so this is essentially a cosmetic isssue.)

**To Reproduce**

1. In the OPNsense admin UI go to 'Services: Unbound DNS: General'
2. Click on the "info" icon next to field 'Register DHCP Static Mappings' to show the info text for that field.
4. See outdated text

**Expected behavior**

Replace "System:General Setup" with "System: Settings: General" in the info text.

**Describe alternatives you considered**

n/a

**Screenshots**
![image](https://github.com/user-attachments/assets/1dd0666e-0ad2-47ac-ad0c-32edecb49d71)

**Relevant log files**

n/a

**Additional context**

n/a

**Environment**

OPNsense 24.7.1-amd64

**Comment by AdSchellevis** [comment]
@bernhardkohlhaas thanks, found a couple of others too, renamed in https://github.com/opnsense/core/commit/e37e67ebcde65abd35b9e33c2256168ce838ce38
