### ISSUE TITLE
IPV6 missing under firewall setting

### ISSUE THREAD

**Issue by aznablegs** [opnsense/core#7782]
**To Reproduce**

Firewall > Settings > Advanced > IPv6 Options > Allow IPv6

**Describe alternatives you considered**

this option for Allow IPv6 is missing from the recent 1-2 months of version upgrade. sorry didn't track when exactly it disappeared. 

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 24.7.1 (amd64).

**Comment by doktornotor** [comment]
Go to Interfaces - Settings. https://github.com/opnsense/core/commit/f5b298ec6cbfea7ee526d3eef2ebe12b49abc803

**Comment by fichtner** [comment]
I'm pretty sure this was updated in the documentation as well so I'm closing this.
