### ISSUE TITLE
More Backup options

### ISSUE THREAD

**Issue by CrazyWolf13** [opnsense/core#7786]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**

Currently it's possible to backup the configuration of opnsense to google drive, that solution is awesome, however most homelabbers/selfhosters try to do the exact opposite, get rid of google / cloud services. 

**Describe the solution you like**

I'd love to see some more Backup options, for example the following:

- Proton Drive
- Nextcloud (Not sure about this, as I could find an FR: https://github.com/opnsense/core/issues/3988, but can not find it anywhere in the Opnsense UI)
- Supporting other general means of backing up.

**Describe alternatives you considered**

A manual script exporter, however that is really a Pre-Alpha experience.

**Additional context**

Thanks for anyone that is working on opnsense <3

**Comment by doktornotor** [comment]
[Backup to Nextcloud](https://docs.opnsense.org/manual/how-tos/cloud_backup.html) works perfectly fine here, there's also bult-in backup to Google Drive, as you have noticed, there's [backup to Git](https://docs.opnsense.org/manual/git-backup.html), not to mention the [backup API](https://docs.opnsense.org/development/api/plugins/backup.html) which is about as general as it gets. 

OPNsense has pretty much the best choice of backup means I've seen on similar projects. Wouldn't call it exactly _pre-alpha experience_.... 🤔

**Comment by CrazyWolf13** [comment]
Apologies for that!

Yeah you are right, the api is awesome, how could I not find this beforehand, I really searched the web.
And the nextcloud/git options were just not there due to me not installing them.

I think with those many ptions it's really not needed, again apologies for the oversight!

**Comment by doktornotor** [comment]
Of course everything is extensible with plugins, if you want Proton Drive the main trouble in coding something seems like that they do not have any official API. There's some third-party effort going on at https://github.com/henrybear327/Proton-API-Bridge

**Comment by CrazyWolf13** [comment]
Yeah I just dug into this topic a little bit deeper and found integration into proxmox-backup-client would be best, but as opnsense is freebsd, and pve backup client is debian, I guess I'll need a jump host, which fetches the config from opnsense and sends it to the backup server.

**Comment by doktornotor** [comment]
Currently have many OPNsense boxes set up to back up the config to a Nextcloud server. If you are fine with a single set of backup credentials, It's really just one directory with subdirs per each OPNsense box, one backup per day each, You can do whatever you want with those backups there, we are rsync-ing them offsite.

**Comment by CrazyWolf13** [comment]
Oh yeah that's also a neat way, I currently don't heavily use nextcloud(just as a web-gateway to interact with my nas) so sending them to my proxmox backup server ensures all my backups are in one place and can easily be cloned to offsite backup.
