### ISSUE TITLE
I think the traffic widget is reporting MB/s and not Mb/s incorrectly.

### ISSUE THREAD

**Issue by jaxjexjox** [opnsense/core#7789]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X ] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X ] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

I noticed a post on reddit by someone also outlining this, it seems that the traffic monitor tool on the dashboard is incorrectly reporting MB/s not Mbit/s  

https://i.imgur.com/KAx4shT.png

No further information probably needed for this (sorry to skim it!) but this is very straightforward, Mb for Megabit and MB for MegaByte.

**Comment by swhite2** [comment]
It seems this was lost in translation as a side effect of https://github.com/opnsense/core/commit/b76b69aacde3f548471c8caae5bc8f402b094bfd. Should be fixed in https://github.com/opnsense/core/commit/70f1270123ce6326f141fb4223f7bd7bfc457c27
