### ISSUE TITLE
relayd: applying configuration changes disrupts firewall traffic

### ISSUE THREAD

**Issue by fraenki** [opnsense/core#780]
When applying Loadbalancer settings, most network traffic stops working and seems to be filtered.

It can easily be fixed by manually reloading the filter rules (Firewall->Diagnostics->Filter Reload), but there seems to be something wrong around the reload of the Loadbalancer.

I've seen this already on 15.7.x and can confirm that this is still an issue on 16.1.3.

**Comment by fraenki** [comment]
The loadbalancer configuration is really simple (two web servers, TCP monitor), but I'm using a CARP IP address as listen address for my _LB Virtual Server_.

FWIW, the traffic is not disrupted when stopping/starting the relayd service. It seems to be related to the filter reload that happens when applying loadbalancer configuration changes:

```
Feb 18 15:04:22 fw01 configd.py: [db02118c-1717-48ca-8673-f622928ba5ef] Reloading filter
```

**Comment by fraenki** [comment]
I'm not sure how to debug this further. Any advise is welcome. :)

**Comment by fichtner** [comment]
All the load balancer pages apply the filter config, is it actually needed?

    src/www/load_balancer_monitor.php:		$retval |= filter_configure();
    src/www/load_balancer_pool.php:		$retval |= filter_configure();
    src/www/load_balancer_setting.php:                $retval |= filter_configure();
    src/www/load_balancer_virtual_server.php:		$retval |= filter_configure();

**Comment by fichtner** [comment]
Does this also happen when you manually reload the filter via the firewall diagnostics?

**Comment by fraenki** [comment]
No, the manual filter reload is my rescue actually :)
It's like this:

1. I make changes to the LB configuration
1. I click on "apply settings"
1. network traffic stops (mostly)
1. I manually reload filter
1. network traffic is working again

Really odd.

**Comment by fichtner** [comment]
Try flipping the order of the configure calls, it looks like the order is reversed ATM:

   $ git grep -A1 filter_configure src/www/load_balancer_*
    src/www/load_balancer_monitor.php:              $retval |= filter_configure();
    src/www/load_balancer_monitor.php-              $retval |= relayd_configure();
    --
    src/www/load_balancer_pool.php:         $retval |= filter_configure();
    src/www/load_balancer_pool.php-         $retval |= relayd_configure();
    --
    src/www/load_balancer_setting.php:                $retval |= filter_configure();
    src/www/load_balancer_setting.php-                $retval |= relayd_configure();
    --
    src/www/load_balancer_virtual_server.php:               $retval |= filter_configure();
    src/www/load_balancer_virtual_server.php-               $retval |= relayd_configure();

**Comment by fraenki** [comment]
I've found a way to reliable reproduce this issue:

1. make sure that the relayd service is NOT running
1. add an invalid configuration (i.e. timeout: 20000, interval: 5)
1. apply this configuration (relayd will exit with an error: global timeout exceeds interval)
1. (most) network traffic will be disrupted

Interesting edge case. I'll try to flip the order of the configure calls...

**Comment by fraenki** [comment]
@fichtner Great, flipping the order fixes this issue, see my PR.
