### ISSUE TITLE
core/mvc: `<hint>` could display in multiple selection `OptionField` when nothing is selected

### ISSUE THREAD

**Issue by Monviech** [opnsense/core#7800]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**

Create a model like this:

```
            <Selectpicker type="OptionField">
                <Multiple>Y</Multiple>
                <OptionValues>
                    <A1>Value1</A1>
                    <A2>Value2</A2>
                    <A3>Value3</A3>
                </OptionValues>
            </Selectpicker>
```

Create a form like this:

```
        <field>
            <id>general.Selectpicker</id>
            <label>Selectpicker</label>
            <type>select_multiple</type>
            <hint>This should display when nothing is selected.</hint>
            <help>Some Help</help>
        </field>
```

Since `BlankDesc` can not be used here, a multiple selection OptionField will always display `Nothing Selected`.

**Describe the solution you like**

In some cases you would want the default to be empty, and display a hint to the user inside the OptionField that this is indeed correct.

**Describe alternatives you considered**

Using the help text to explain what the default setting is when nothing is selected.

**Additional context**

BlankDesc not applicable: https://github.com/opnsense/core/blob/master/Makefile#L374-L375

**Comment by fichtner** [comment]
Wasn't there a proper mechanism for this? There was something about BlankDesc being removed... let me check.

**Comment by fichtner** [comment]
Ok something wrong with `data-hint` vs. `data-title` or `title` use :)
