### ISSUE TITLE
Traceroute ICMP doesn't work through opnsense

### ISSUE THREAD

**Issue by vgdh** [opnsense/core#7803]
**Describe the bug**
When I run `traceroute github.com -I`, it doesn't work correctly when using OPNsense as the router. 
However, it works fine with any other hardware router. 
The UDP version, though, works fine."

**To Reproduce**
Use NAT and do  `traceroute github.com -I` on machine in lan and see the results are empty

**Expected behavior**
Shows intermediate servers as expected

**Screenshots**
With OPNsense as router
![2](https://github.com/user-attachments/assets/c809ca90-b267-4ca9-a83a-17ef5be0d43d)
With any HW router
![1](https://github.com/user-attachments/assets/14f24178-a77c-4d8f-bd7a-e7539098c540)

**Comment by fichtner** [comment]
A bit late to the party. Install 24.7.2. :)
