### ISSUE TITLE
"SSL certificate manager" link in System > Settings > Administration points to nothing.

### ISSUE THREAD

**Issue by tanpro260196** [opnsense/core#7811]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

This link: 
![image](https://github.com/user-attachments/assets/a233e3d3-4954-4df5-a3fc-7f092a601303)
Points to a 404
![image](https://github.com/user-attachments/assets/d3f3a05c-246a-4836-b1a4-c409550cc9e1)
When it should points to
![image](https://github.com/user-attachments/assets/ab35edce-418a-402b-a2e4-89b3470b481f)

**To Reproduce**

1. Go to System > Settings > Administration
2. Click on SSL certificate manager

**Expected behavior**

Should take user to Trust >Certificates instead

**Environment**

OPNsense 24.7.2 (amd64).

**Comment by AdSchellevis** [comment]
@tanpro260196 thanks, fixed in https://github.com/opnsense/core/commit/f2603ca7101f8fb02dba37b3b14ff561964fcbc3
