### ISSUE TITLE
Disabled interface with PPP assisgnment can not enabled again - "The field Modem Port is required"

### ISSUE THREAD

**Issue by itn3rd77** [opnsense/core#7823]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**
I have disabled my "LTE" interface with an assigned PPP device /dev/cuaU0.2  for testing purposes. Now I am unable to enable the interface again. After hitting the save button the "Modem Port" field is empty and I just get the error message "The field Modem Port is required". I tried chaning the the PPP device e.g. /dev/cuaU0.1 but got the same result. 

*Tip*: to validate your setup was working with the previous version, use opnsense-revert (https://docs.opnsense.org/manual/opnsense_tools.html#opnsense-revert)

**To Reproduce**

1. Go to 'Interfaces'
2. Click on a Interface with an PPP device assigned and disabled the interface
3. Go to 'Interfaces' again
4. Click on a Interface with an PPP device assigned again and enable the interface
5. See error

**Expected behavior**

Interface should be enabled gain without an error

**Describe alternatives you considered**

none

**Screenshots**

![29-08-2024_07-40-40](https://github.com/user-attachments/assets/d63145a9-3daf-4c95-b9df-41adfed1c7e6)
![29-08-2024_07-41-22](https://github.com/user-attachments/assets/41626ddb-97da-4e0a-95d0-a8ccbacc1879)
![29-08-2024_07-42-16](https://github.com/user-attachments/assets/01bd65f3-fd70-4d68-97ee-66910ed1c11e)

**Relevant log files**

If applicable, information from log files supporting your claim.

**Additional context**

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 24.7.2-amd64
FreeBSD 14.1-RELEASE-p3
OpenSSL 3.0.14

**Comment by fichtner** [comment]
Nono I think it's a bug I introduced. I will fix it in time for 24.7.3 today.

**Comment by fichtner** [comment]
@itn3rd77 can you try 090c651:

    # opnsense-patch 090c651


Cheers,
Franco

**Comment by itn3rd77** [comment]
@fichtner That worked. Thanks a lot 👍

**Comment by fichtner** [comment]
Great, appreciate your time :)
