### ISSUE TITLE
Failed to disable ISC DHCPv6 while no available address range for configured interface is available

### ISSUE THREAD

**Issue by itn3rd77** [opnsense/core#7828]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

I struggle to get an IPv6 address from my ISP for days so I do currently not have any IPv6 address and hence track IPv6 on my LAN interface is not working (no available address range).

For some testing I wanted to disable ISC DHCPv6 on the LAN interface but that fails while there is no available address range. Obviously disable should not be a problem regardless if the is an available address range.

*Tip*: to validate your setup was working with the previous version, use opnsense-revert (https://docs.opnsense.org/manual/opnsense_tools.html#opnsense-revert)

**To Reproduce**

1. Ensure you have no IPv6 delegated from your WAN
2. Go to 'Services: ISC DHCPv6 '
3. Click on '[LAN]'
4. Unselect "Enable DHCP server on the LAN interface"
5. Click on 'Save'
6. See error

**Expected behavior**

Even if  no available address range is available it should be posible to disable ISC DHCPv6 for that interface

**Describe alternatives you considered**
none

**Screenshots**

![30-08-2024_14-46-54](https://github.com/user-attachments/assets/e26af0e9-161a-4fac-ae29-f7876af05272)

**Relevant log files**

If applicable, information from log files supporting your claim.

**Additional context**

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 24.7.3_1-amd64
FreeBSD 14.1-RELEASE-p3
OpenSSL 3.0.14

**Comment by fichtner** [comment]
Can you try 296399a?

    # opnsense-patch 296399a


Cheers,
Franco

**Comment by itn3rd77** [comment]
Yep that did the job👍Thanks Franco.

Cheers,
Ingo

**Comment by fichtner** [comment]
Sure thing, enjoy your weekend :)

**Comment by itn3rd77** [comment]
Btw. after disabling "Allow manual adjustment of DHCPv6 and Router Advertisements" on all internal Interfaces I instantly got an IPv6 again from Deutsche Glasfaser. Is that a know problem with some ISPs?

**Comment by fichtner** [comment]
DG is a bit whacky at the moment but given the whole FreeBSD IMCPv6 SA situation I don't know if that was from our end or theirs. Need a bit of time to find out during 24.7.x iterations.
