### ISSUE TITLE
Dashboard sluggish if logging to disk is enabled

### ISSUE THREAD

**Issue by neelchauhan** [opnsense/core#7829]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

When I visit the OPNsense 24.7 dashboard, it is very slow and sluggish even on an Intel i9-13900F, unless I disable logging to disk when it's very snappy.

This happens on a connection running six Tor relays where 100K states is normal.

**To Reproduce**

Take a connection running Tor relays, use a commercial or fiber ISP, and have up to eight Tor relays behind your OPNsense box. Then access the Web UI via a browser on the same connection.

**Expected behavior**

The dashboard UI should not be sluggish even under heavy load, such as that from Tor relays.

**Describe alternatives you considered**

I've considered going back to my old MikroTik box, I don't remember older OPNsense versions having a sluggish dashboard.

**Additional context**

I am using the [MonkWho pfatt bypass](https://github.com/MonkWho/pfatt/) on Frontier FiberOptic because of an 802.1X requirement in my state. This way I am not bound to the Frontier Arris NVG468MQ state table. I am not using the supplicant bypass since I'm not sure if Frontier routers have a known root like AT&T gateways so I can't extract certificates.

However, this increases CPU usage considerably as it effectively bridges 802.1X and reroutes IP traffic via VLAN 0.

**Environment**

Software version used and hardware type if relevant, e.g.:

Router:
* OPNsense 24.7.3 (amd64)
* Minisforum MS-01 (i9-13900H, disabled E-cores, 32GB RAM, 1TB SDD)
* Broadcom BCM5720 for WAN/bypass
* Onboard Intel X710 NIC for LAN
* [MonkWho pfatt bypass](https://github.com/MonkWho/pfatt/) on a Arris NVG468MQ and an unknown white 4-port Nokia ONT

PCs used to access include Lenovo ThinkPad X1 Yoga 3rd Gen (work laptop) running Windows 11, Dell XPS 14 9440 (personal laptop) running Fedora 40, and a homebuilt i9-13900F desktop PC running Fedora 40. Firefox (both), Chrome/Opera (Linux), and Edge (Windows) were tested.

**Comment by doktornotor** [comment]
Perhaps you should remove widgets that try to read logs? 🤔

**Comment by fichtner** [comment]
Yes, my first thought was try to only use the system information widget and see if that is better. Basically find the widget that makes it sluggish first. Then we can talk specifics.

**Comment by doktornotor** [comment]
From the issue description, I'd say disk I/O is simply not capable. Would be hardly surprising, considering you are trying to display latest `N` entries from huge logs that keep scrolling by so fast that the `N` is obsolete at the moment it's been read. Then again, just a quick guess. 

Something like [iostat(8)](https://man.freebsd.org/cgi/man.cgi?iostat) could help as well. Probably will be the same problem with any "live" logs there.

**Comment by miovo** [comment]
I appear to be facing the same issue. Before the new UI, my dashboard worked perfectly fine with no issues what so ever.
Directly after the update, my dashboard become completely unusable and caused browser crashes whenever I loaded the dashboard.

**Comment by doktornotor** [comment]
The original - very specific - issue mentions absolutely nothing about browser crashes or completely unusable. Let me quote the core of it for your convenience: _"very slow and sluggish ... unless I disable logging to disk when it's very snappy. **This happens on a connection running six Tor relays where 100K states is normal.**_

Please, don't post unrelated unspecific rants,

**Comment by miovo** [comment]
Not sure if hostility was the right moved on your part. Wouldn’t quite consider what I said a “rant”. 
Comment has been removed, Hope you have a better day,

**Comment by fichtner** [comment]
This was fixed in 24.7.7.
