### ISSUE TITLE
Missing documentation about rules for description of proxy blacklist

### ISSUE THREAD

**Issue by oparoz** [opnsense/core#784]
When adding a squid blacklist, there is a field for a description.
I've tried to add a URL, but it didn't work.
I removed the protocol, but it still didn't work.

I think it would be good to give a bit more information about what is allowed in this field, just like for the filename or drop the restrictions since it's a description field. It could also be converted from an input to a textarea.

**Comment by AdSchellevis** [comment]
https://docs.opnsense.org/manual/how-tos/proxywebfilter.html
