### ISSUE TITLE
Minor alias webgui issue

### ISSUE THREAD

**Issue by azdps** [opnsense/core#785]
How to reproduce in Chrome.

1. Navigate to Firewall -> Aliases and select any one of the Aliases sub-menu's that has a an option button to Add a new alias.
2. Select the Add a new alias button.
3. Zoom in to the point where the save and cancel buttons don't show.
4. If you attempt to scroll down, the save and cancel button won't show. You have to zoom back out to see the buttons.

This is obviously a minor webui issue with the latest version of OPNsense (16.1.3).

**Comment by AdSchellevis** [comment]
@azdps Thanks for reporting, found the issue.

In case you want to try it out for yourself, run this in a console:

```
curl -o /usr/local/www/firewall_aliases_edit.php https://raw.githubusercontent.com/opnsense/core/master/src/www/firewall_aliases_edit.php
```

**Comment by AdSchellevis** [comment]
https://github.com/opnsense/core/commit/bcaaf64cf939d790f831736c5f2fa085d0935a7c
