### ISSUE TITLE
Unable to Import Third Party Certificates

### ISSUE THREAD

**Issue by driver099** [opnsense/core#7856]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [* ] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [ *] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

TLDR: Adding a third party certificate generates an error or crashes the Webgui or is not able to be imported. Last time a cert was installed was 2 years ago.

When replacing an expired third party certificate that is used for Webgui https access, generating a CSR that is then passed to the third party CA (Digicert in this instance) results in the issuance of a new certificate. The contents of the certificate are then pasted into the certificate data box when returning to OPNsense to complete the process by 'signing' the original request. Assigning the certificate then crashes the webgui.

**To Reproduce**

1. Go to System>Trust>Certificates
2. Click on +
3. Enter details of certificate - fqdn as common name, RSA2048, SHA256
4. Save
5. Edit the request, observe the CSR text
6. Send CSR to Digicert, Obtain issued Cert
7. Edit the request from the list
8. Find the output (PEM)>Certificate Data box
9. Paste cert text into the box, hit Save
10. Observe error: missing CA key

Alternative: Manually add the cert details, minus the private key (as you do not have one from a third party). Assigning this cert to the webgui then crashes the gui and you cannot access it unless you restart the webgui and reset it from the shell.

**Expected behavior**

Certificate is imported without error and is assigned without causing a crash.

Software version used and hardware type if relevant, e.g.:
Versions
OPNsense 24.7.3_1-amd64
FreeBSD 14.1-RELEASE-p3
OpenSSL 3.0.14

**Comment by AdSchellevis** [comment]
Looks like we missed a spot there, the following command should store the private key as planned :
```
opnsense-patch fb9cb1e
```

**Comment by driver099** [comment]
Tried the patch, still getting the error. Just to confirm, when creating the CSR, the issuer is set to self-signed and there are no other options.

**Comment by driver099** [comment]
Thanks, that did resolve it.

**Comment by AdSchellevis** [comment]
@driver099 thanks for confirming

**Comment by driver099** [comment]
Just came to do the renewal of the cert, and getting 'missing CA key' again. Has the fix that was implemented been reversed again in the latest major build perhaps?
Versions
OPNsense 25.7.1_1-amd64
FreeBSD 14.3-RELEASE-p1
OpenSSL 3.0.17
