### ISSUE TITLE
onWidgetResize is called only on initial draw

### ISSUE THREAD

**Issue by m3e-g** [opnsense/core#7863]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [ x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [ x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

I'm writing a new dashboard widget (not associated with any plugin) and I've noticed that onWidgetResize is called only on a initial draw of the widget. I've reduced the code to this stub below and it stil does not call this method more than once. I've added similar console message to the WOL widget and it's being printed normally on each resize, and both widgets have similar structure.

I've tried to debug it on my own but I've hit a wall, so any help would be appreciated. 

```
export default class IfClientsWidget extends BaseTableWidget {
    constructor() {
        super();
        this.test_cnt = 0;
    }

    getMarkup() {
        let $container = $('<div id="if-clients-container"></div>');
        let $if_cli_table = this.createTable('if-clients-table', {
            headerPosition: 'none'
        });

        $container.append($if_cli_table);
        return $container;
    }

    async onWidgetTick() {
        this.test_cnt += 1;
        let rows = [];
        rows.push([`${this.test_cnt}`,`${this.test_cnt}`]);
        super.updateTable('if-clients-table', rows);
    }
 
    onWidgetResize(elem, width, height) {
        console.log('resize-widget');
        return super.onWidgetResize(elem, width, height);
    }
} 
```

**To Reproduce**

1. Create a widget from template above
2. install it and add to dashboard
3. resize window
4. No 'resize-widget' messages printed
5. Reload window
6. Single 'resize-widget' message printed

**Expected behavior**

onWidgetResize method is called each time window size changes

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 24.7.4-amd64

**Comment by swhite2** [comment]
I cannot reproduce this:

Firefox:
![image](https://github.com/user-attachments/assets/15376053-ab65-40e7-8e66-13987ee9e1a4)

Chrome:
![image](https://github.com/user-attachments/assets/80b97d43-450f-45ae-9382-55a4e8817cf4)

Metadata file formatted as documented? e.g.

```
    <ifclientswidget>
        <filename>IfClientsWidget.js</filename>
        <translations>
            <title>Test</title>
        </translations>
    </ifclientswidget>
```

**Comment by m3e-g** [comment]
Thank you!

I had dashes in the metadata main field name:

```
    <if-clients-widget>
        <filename>IfClientsWidget.js</filename>
        <translations>
            <title>Test</title>
        </translations>
    </if-clients-widget>
```

This file had been used to some extent (translations had been used and I could do API calls), but I couldn't resize. 
Once I've removed the dashes it works as intended.

Thanks again! I wouldn't have found it otherwise :)

**Comment by swhite2** [comment]
@m3e-g Glad you found it :)
