### ISSUE TITLE
New version 24.7.4 error VPN Client

### ISSUE THREAD

**Issue by matiasduartee** [opnsense/core#7866]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

New version 24.7.4 error VPN Client where the OpenSSL package was updated to version 3.0.15, is causing an error when closing the point-to-point tunnel. 

Example 1: two OPNsense in version OPNsense 24.7.4_1-amd64, FreeBSD 14.1-RELEASE-p4, OpenSSL 3.0.15 when using the point-to-point VPN service using a shared key gives the following error on the client.
![image](https://github.com/user-attachments/assets/1a57739a-be3b-4c23-b27e-fdd3147494b5)

Example 2: Company1 with OPNsense version OPNsense 24.7.4_1-amd64, FreeBSD 14.1-RELEASE-p4, OpenSSL 3.0.15 and Company2 with OPNsense version 24.7.3_1-amd64, FreeBSD 14.1-RELEASE-p3, OpenSSL 3.0.14 when using the point-to-point VPN service using shared key works correctly.
![image](https://github.com/user-attachments/assets/fdc65806-8f3a-4327-b6ac-c1872ce98419)

**Comment by matiasduartee** [comment]
Hello everyone, I apologize for opening this issue, but I discovered that there is nothing wrong with the new version or with the OpenSSL 3.0.15 package.

The problem is that the OpenVPN client already had a server running on port 1195 and when trying to connect to company A via port 1195, the error `FreeBSD ifconfig failed: external program exited with error status: 1` was displayed.

Please forgive me!

**Comment by fichtner** [comment]
Hey @matiasduartee, no worries. Can we close this then? :)

**Comment by matiasduartee** [comment]
@fichtner how are you, friend? You can finish, thank you.
