### ISSUE TITLE
Squid: Add option maximum_object_size_in_memory

### ISSUE THREAD

**Issue by uKev** [opnsense/core#787]
It would be great to be able to set the option _maximum_object_size_in_memory_ for squid. 
The default maximum object size is 4MiB. Every object that's bigger than that isn't cached inside the proxy.

One usecase for caching of bigger files would be a local cache for linux distribution updates without much effort. The update files for multiple computers/vms done over http would only be downloaded once. That is more important as lower the internet connection is, of course.

The option must be set before cache_dir in the configuration file.
See http://superuser.com/questions/972665/squid3-caching-websites-works-but-not-for-large-files-despite-max-size-6gb for more about this.

Thanks and keep up the good work!

**Comment by AdSchellevis** [comment]
Good idea, I will try to add this to the "advanced options" for one of the upcoming releases.

**Comment by AdSchellevis** [comment]
@uKev I've added the maximum_object_size for you, in case you want to test this new feature, you can download the 3 files manually using:
```
curl -o /usr/local/opnsense/mvc/app/controllers/OPNsense/Proxy/forms/main.xml https://raw.githubusercontent.com/opnsense/core/master/src/opnsense/mvc/app/controllers/OPNsense/Proxy/forms/main.xml
curl -o /usr/local/opnsense/mvc/app/models/OPNsense/Proxy/Proxy.xml https://raw.githubusercontent.com/opnsense/core/master/src/opnsense/mvc/app/models/OPNsense/Proxy/Proxy.xml
curl -o /usr/local/opnsense/service/templates/OPNsense/Proxy/squid.conf https://raw.githubusercontent.com/opnsense/core/master/src/opnsense/service/templates/OPNsense/Proxy/squid.conf
```

It will probably go in to the next release.

**Comment by uKev** [comment]
I've tested this with the new release and it works as expected.
Thanks for implementing and releasing this feature in such a short time!
