### ISSUE TITLE
openvpn: client export misses --data-ciphers

### ISSUE THREAD

**Issue by emammadov** [opnsense/core#7893]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

We are using the latest version of OPNsense. I have setup OpenVPN instance.
If I use Openvpn Connect, I see that it uses AES256-GCM. No errors.

But if use OpenVPN client v2.6.12 (Community edition), it gives the following error, but it connects successfully.

`Note: --cipher is not set. OpenVPN versions before 2.5 defaulted to BF-CBC as fallback when cipher negotiation failed in this case. If you need this fallback please add '--data-ciphers-fallback BF-CBC' to your configuration and/or add BF-CBC to --data-ciphers.
`

In the server logs, when the client is connected, it shows that the client uses AES-256-GCM.

`openvpn_server1	xxx.xxx.xxx.xxx:55396 Data Channel: cipher 'AES-256-GCM', peer-id: 0`

**Comment by fichtner** [comment]
Forum discussion for reference: https://forum.opnsense.org/index.php?topic=42914.0

**Comment by AdSchellevis** [comment]
I don't mind pushing `data-ciphers-fallback` in a similar way as the legacy version would do,  but it's likely not very useful (https://github.com/opnsense/core/commit/a3fd07bd4e60727024a1daf829d10ce95f9ec0d3)

**Comment by iMiMx** [comment]
The 'note' (not really an error) generated at the client end, is about 'cipher' - to silence the note, 'cipher' should be set in the client export config.

... even though not technically required, with 2.6 OpenVPN anyway (client and server).

data-ciphers-fallback is used when an old OpenVPN client, for example 2.3, connects to a current OpenVPN server - where the client does not support cipher negotiation.

data-ciphers is used to restrict the ciphers that can be select during cipher negotiation.

If the clients/servers are all 2.6.x, 'cipher' is not required - the 'note' will be shown on the client end, however - but might be required with older clients and to silence the 'note' even in a 2.6 client.  But it is just a note, not a terminal error/fault.

Given that there are still quite a lot of 'other' routers around that still have OpenVPN 2.4, or 2.5, it probably makes sense to include 'cipher' in the opnsense OpenVPN client export - to ensure compatability with older clients, one which won't cause problems for 2.6 anyway.

**Comment by emammadov** [comment]
I've read that the latest OpenVPN server no longer needs to export Data Ciphers, as OpenVPN now supports cipher negotiation between the server and client. That's great news.

I also checked the OpenVPN server logs and confirmed that it uses AES-256-GCM when a client is connected, which is fine.

When I use OpenVPN Connect, there are no errors. However, when I use the OpenVPN client, it complains about missing Data Ciphers, even though the OPNsense OpenVPN log shows that AES-256-GCM is being used.

I have used the latest patch of OPNsense patch (**opnsense-patch a3fd07bd4e**), but the output of Openvpn client is the same. 

`Note: --cipher is not set. OpenVPN versions before 2.5 defaulted to BF-CBC as fallback when cipher negotiation failed in this case. If you need this fallback please add '--data-ciphers-fallback BF-CBC' to your configuration and/or add BF-CBC to --data-ciphers.`

If this message is purely informational and doesn't involve any security issues, I will leave it as it is.

**Comment by AdSchellevis** [comment]
@iMiMx hehe, this was wat I expected as well, client mismatches. pushing `data-ciphers-fallback` when offered on our end is harmless, but is also likely pretty useless for reasons you mentioned.

**Comment by iMiMx** [comment]
> it complains about missing Data Ciphers, even though the OPNsense OpenVPN log shows that AES-256-GCM is being used.

I'm not sure it complains as such - it's just a polite 'note' :)

.... WARNING in the logs would be OpenVPN complaining!

**Comment by emammadov** [comment]
After patch, I have just exported the vpn config. That's why it gave the same message.

In the **Openvpn Instance**, I selected:
Data Ciphers - AES-256-GCM 
Data Ciphers Fallback - AES-256-GCM 

<img width="425" alt="2024-09-25 09_15_03-Instances _ OpenVPN _ VPN _ WS-OPENVPN-1-80 localdomain" src="https://github.com/user-attachments/assets/9a331e34-b578-4bf3-a2b4-4b7253557a4b">

then exported the config and connected the vpn, the message is gone.

I am attaching the log of Openvpn client:

`2024-09-25T09:16:47	Notice	openvpn_server1	username/xxx.xxx.xxx.xxx:49195 Protocol options: protocol-flags cc-exit tls-ekm dyn-tls-crypt	 
2024-09-25T09:16:47	Notice	openvpn_server1	username/xxx.xxx.xxx.xxx:49195 Data Channel: cipher 'AES-256-GCM', peer-id: 0	 
2024-09-25T09:16:46	Notice	openvpn_server1	username/xxx.xxx.xxx.xxx:49195 SENT CONTROL [username]: 'PUSH_REPLY,dhcp-option DNS 213.133.100.98,dhcp-option DNS 88.198.229.192,dhcp-option DNS 193.47.99.5,route-gateway 10.249.1.81,topology subnet,redirect-gateway def1,redirect-gateway def1,ifconfig 10.200.1.10 255.255.255.240,peer-id 0,cipher AES-256-GCM,protocol-flags cc-exit tls-ekm dyn-tls-crypt,tun-mtu 1500' (status=1)	 
2024-09-25T09:16:46	Notice	openvpn_server1	username/xxx.xxx.xxx.xxx:49195 MULTI: primary virtual IP for username/xxx.xxx.xxx.xxx:49195: 10.200.1.10	 
2024-09-25T09:16:46	Notice	openvpn_server1	username/xxx.xxx.xxx.xxx:49195 MULTI: Learn: 10.200.1.10 -> username/xxx.xxx.xxx.xxx:49195	 
2024-09-25T09:16:46	Notice	openvpn_server1	username/xxx.xxx.xxx.xxx:49195 OPTIONS IMPORT: reading client specific options from: /tmp/openvpn_cc_69842ea2870cbcac784320a2bb1e6b46.tmp	 
2024-09-25T09:16:46	Notice	openvpn	client config created @ /tmp/openvpn_cc_69842ea2870cbcac784320a2bb1e6b46.tmp	 
2024-09-25T09:16:46	Notice	openvpn_server1	username/xxx.xxx.xxx.xxx:49195 OPTIONS IMPORT: reading client specific options from: /var/etc/openvpn-csc/1/username	 
2024-09-25T09:16:46	Notice	openvpn_server1	username/xxx.xxx.xxx.xxx:49195 MULTI_sva: pool returned IPv4=10.200.1.10, IPv6=(Not enabled)	 
2024-09-25T09:16:46	Notice	openvpn_server1	xxx.xxx.xxx.xxx:49195 [username] Peer Connection Initiated with [AF_INET]xxx.xxx.xxx.xxx:49195	 
2024-09-25T09:16:46	Notice	openvpn_server1	xxx.xxx.xxx.xxx:49195 Control Channel: TLSv1.3, cipher TLSv1.3 TLS_AES_256_GCM_SHA384, peer certificate: 2048 bits RSA, signature: RSA-SHA256, peer temporary key: 253 bits X25519	 
2024-09-25T09:16:46	Notice	openvpn_server1	xxx.xxx.xxx.xxx:49195 TLS: tls_multi_process: initial untrusted session promoted to trusted	 
2024-09-25T09:16:46	Notice	openvpn_server1	xxx.xxx.xxx.xxx:49195 TLS: move_session: dest=TM_ACTIVE src=TM_INITIAL reinit_src=1	 
2024-09-25T09:16:46	Notice	openvpn_server1	xxx.xxx.xxx.xxx:49195 peer info: IV_PROTO=990	 
2024-09-25T09:16:46	Notice	openvpn_server1	xxx.xxx.xxx.xxx:49195 peer info: IV_CIPHERS=AES-256-GCM:AES-128-GCM	 
2024-09-25T09:16:46	Notice	openvpn_server1	xxx.xxx.xxx.xxx:49195 peer info: IV_NCP=2	 
2024-09-25T09:16:46	Notice	openvpn_server1	xxx.xxx.xxx.xxx:49195 peer info: IV_MTU=1600	 
2024-09-25T09:16:46	Notice	openvpn_server1	xxx.xxx.xxx.xxx:49195 peer info: IV_TCPNL=1	 
2024-09-25T09:16:46	Notice	openvpn_server1	xxx.xxx.xxx.xxx:49195 peer info: IV_PLAT=win	 
2024-09-25T09:16:46	Notice	openvpn_server1	xxx.xxx.xxx.xxx:49195 peer info: IV_VER=2.6.8
`

**Comment by emammadov** [comment]
Is it okay now to leave it so or should it be developed?

**Comment by iMiMx** [comment]
Based on your screenshot - if 'ciphers' is selected/set in the export options, then really it should show in the resulting file?

... or it shouldn't be there at all, as it makes no sense.

Perhaps the best logic would be:

- If ciphers is set, it should appear in the exported file
- If ciphers is not set, perhaps the default is not set, as it's not required, then it's not in the exported file

**Comment by iMiMx** [comment]
Ooof - I misunderstood that cipher is set on the server, I thought it was on the export UI.

You could fix it on the Export UI - under custom config add:

cipher AES-256-GCM

... then the 'problem' goes away.

**Comment by emammadov** [comment]
Then should I revert the latest Opnsense patch? 

Because only Openvpn Client complains about the data ciphers, Openvpn Connect doesn't give any warning.

If the Data Cipher is not set in the vpn config file, the Openvpn server shows the following log that AES-256-GCM is used.

Notice	openvpn_server1	username/xxx.xxx.xxx.xxx:58955 Protocol options: protocol-flags cc-exit tls-ekm dyn-tls-crypt	 
Notice	openvpn_server1	username/xxx.xxx.xxx.xxx:58955 **Data Channel: cipher 'AES-256-GCM'**, peer-id: 0	 
Notice	openvpn_server1	username/xxx.xxx.xxx.xxx:58955 SENT CONTROL [username]: 'PUSH_REPLY,dhcp-option DNS 213.133.100.98,dhcp-option DNS 88.198.229.192,dhcp-option DNS 193.47.99.5,route-gateway 10.200.1.xx,topology subnet,redirect-gateway def1,redirect-gateway def1,ifconfig 10.200.1.xx 255.255.255.240,peer-id 0,cipher AES-256-GCM,protocol-flags cc-exit tls-ekm dyn-tls-crypt,tun-mtu 1500' (status=1)	 
Notice	openvpn_server1	username/xxx.xxx.xxx.xxx:58955 MULTI: primary virtual IP for username/xxx.xxx.xxx.xxx:58955: 10.249.1.82	 
Notice	openvpn_server1	username/xxx.xxx.xxx.xxx:58955 MULTI: Learn: 10.249.1.82 -> username/xxx.xxx.xxx.xxx:58955	 
Notice	openvpn_server1	username/xxx.xxx.xxx.xxx:58955 OPTIONS IMPORT: reading client specific options from: /tmp/openvpn_cc_605e7a19c88c2c3a420aef8349e1cdf1.tmp	 
Notice	openvpn	client config created @ /tmp/openvpn_cc_605e7a19c88c2c3a420aef8349e1cdf1.tmp	 
Notice	openvpn_server1	username/xxx.xxx.xxx.xxx:58955 OPTIONS IMPORT: reading client specific options from: /var/etc/openvpn-csc/1/username

**Comment by fichtner** [comment]
> Ooof - I misunderstood that cipher is set on the server in your screenshot, I thought it was on the export UI.
> 
> You could fix it on the Export UI - under custom config add:
> 
> cipher AES-256-GCM
> 
> ... then the 'problem' goes away.

I thought that was the original point of the bug report? :)

**Comment by iMiMx** [comment]
I think you're right....

If clients are 2.5 or above (i.e current) the current implementation is a non-issue - there's just a polite 'Note' on the client end.

But having the option to set 'data-ciphers-fallback' to support older clients, is probably a nice to have.

**Comment by emammadov** [comment]
I reverted the latest patch. We are using OpenVPN Client 2.6, and OPNsense shows that AES-256-GCM is being used when the client is connected. 
The client only provides a note, which I understand is just an informational message.

**Comment by Skyfly2021** [comment]
> > Ooof - I misunderstood that cipher is set on the server in your screenshot, I thought it was on the export UI.
> > You could fix it on the Export UI - under custom config add:
> > cipher AES-256-GCM
> > ... then the 'problem' goes away.
> 
> I thought that was the original point of the bug report? :)

After using the AES-256-GCM cipher, the network speed decreased during speed tests.
