### ISSUE TITLE
dashboard: which plugins may require inline edit functionality for their data?

### ISSUE THREAD

**Issue by fichtner** [opnsense/core#7895]
**Important notices**

Our forum is located at https://forum.opnsense.org , please consider joining discussions there in stead of using GitHub for these matters.

Before you ask a new question, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

This would extend the idea of a general edit page link being able to make changes in a modal directly on the dashboard.  Also collect the widgets from the plugins if applicable.

**Comment by Monviech** [comment]
@fichtner

I gave this a quick look and it does not seem to provide much benefit anymore, now that every widget has the quick link button to its respective page.

I also couldn't find widgets that would clearly benefit from this. Some widgets already have more selective behavior:
- e.g. Interfaces goes to the correct interfaces page
- e.g. Firewall opens Livelog with correct rid selected

For other widgets, it is much easier to find and edit data in the respective core or plugin pages after clicking the referral link. I would rather give this functionality a pass.

**Comment by Monviech** [comment]
Since I found a working simple solution for this I gonna reopen it and add it to some other widgets, e.g. the VPN widgets.
