### ISSUE TITLE
system: add a certificate widget to allow visibility for upcoming expiries

### ISSUE THREAD

**Issue by fichtner** [opnsense/core#7898]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**

People have always asked for certificate expiration notifications, but these are not very reliable if ignored and when they should notify which leaves a lot of configuration glue. But expiry is a problem that needs to be dealt with.

**Describe the solution you like**

Build a dashboard widget to list the certificates to be expired soon with delete and renew functions.

**Describe alternatives you considered**

N/A

**Additional context**

N/A

**Comment by Monviech** [comment]
The delete and renew functions are out of scope for the widget, they should be handled in their respective UI pages.
