### ISSUE TITLE
System: High Availability: Status MVC/API conversion

### ISSUE THREAD

**Issue by fichtner** [opnsense/core#7899]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**

We want an API for everything.

**Describe the solution you like**

Port the HA Status page to MVC.

**Describe alternatives you considered**

N/A

**Additional context**

N/A

**Comment by fichtner** [comment]
Almost ;)

```
% git grep status_habackup
src/opnsense/mvc/app/controllers/OPNsense/Core/forms/hasyncSettings.xml:        <label><![CDATA[Configuration Synchronization Settings (XMLRPC Sync) <a href="/status_habackup.php">Perform synchronization </a>]]></label>
src/opnsense/mvc/app/models/OPNsense/Core/ACL/ACL.xml:            <pattern>status_habackup.php</pattern>
src/www/guiconfig.inc:            $lnk_start = '<a href="status_habackup.php">';
```

**Comment by AdSchellevis** [comment]
@fichtner got it (https://github.com/opnsense/core/commit/24485709f3be16348927a3c7ce07d872c946cf66), thanks!

**Comment by lug-gh** [comment]
Hi @fichtner 
I noticed in the API documentation that the command is “restartAll”. However, “restart_all” is called in the OPNsense web GUI. Both seem to work. The question now is, which is correct, or which of the two commands will remain in the future? This may also affect other commands.

**Comment by fichtner** [comment]
as per calling convention "restart_all" is the correct one. mileage may vary on the other for obscure reasons :)
