### ISSUE TITLE
system: setup wizard should also cover IPv6, add help texts

### ISSUE THREAD

**Issue by sjorge** [opnsense/core#79]
The setup wizard shows no mention of ipv6.
It should ask how to configure wan/lan for those too.

**Comment by box293** [comment]
Throwing my 2c in, you should be able to complete the wizard using only IPv6 parameters, IPv4 should not be a requirement (in the scenarios where you want to run a dedicated IPv6 firewall that has no IPv4 responsibilities).

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository, 
please read https://github.com/opnsense/core/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue, 
just let us know, so we can reopen the issue and assign an owner to it.
