### ISSUE TITLE
"X-Forwarded for header handling" setting in Proxy Server has no effect

### ISSUE THREAD

**Issue by oparoz** [opnsense/core#790]
### Env

16.1.3
LAN->Proxy Server->OpenVPN GW

### Steps to reproduce

1. Got to *Proxy server*
1. Turn on *Advanced mode*
1. Set *X-Forwarded for header handling* to *none*
1. Click on the *Apply* button
1. Make a request to a web server you control
1. Check the value of *HTTP_X_FORWARDED_FOR*

### Expected result

`X-Forwarded-For: unknown`

### Actual result

`X-Forwarded-For: <random public IP>, <LAN IP>`

**Comment by oparoz** [comment]
I've checked the config at `/usr/local/etc/squid/squid.conf` and there is no sign of `forwarded_for`

**Comment by AdSchellevis** [comment]
your using the wrong option, you need to set "Set forward header to unknown (off)". 
The field is optional, so "none" is default.

**Comment by oparoz** [comment]
Got it, thanks.
