### ISSUE TITLE
system: trust: global settings page

### ISSUE THREAD

**Issue by fichtner** [opnsense/core#7901]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**

First and foremost for compliance reasons we need a settings page for global trust behaviour.

**Describe the solution you like**

Introduce the page and move settings related to it that already exist to it. Add more settings as required, e.g. the disabling of OpenSSL legacy ciphers.

**Describe alternatives you considered**

Adding settings to system settings general, but not very flexible in the future.

**Additional context**

N/A

**Comment by AdSchellevis** [comment]
https://github.com/opnsense/core/pull/7854
