### ISSUE TITLE
DHPC Bug: ISC DHCP ipv4 and ipv6 Can't work on LAN Bridge

### ISSUE THREAD

**Issue by Handsome1080P** [opnsense/core#7902]
DHPC Bug: ISC DHCP v4 and v6 Can't work on LAN Bridge.
But new KEA DHCP Works.How?

**Comment by fichtner** [comment]
My professional opinion: https://www.youtube.com/watch?v=k6KfhOpq2n8

As far as ISC goes it's EoL and nobody will fix it. And given the fact that Kea works I'd say you have all you need to implement it.


Cheers,
Franco

**Comment by Handsome1080P** [comment]
> My professional opinion: https://www.youtube.com/watch?v=k6KfhOpq2n8
> 
> As far as ISC goes it's EoL and nobody will fix it. And given the fact that Kea works I'd say you have all you need to implement it.
> 
> Cheers, Franco

I saw it in documents.But IPv6 DHCP working or not?

**Comment by fichtner** [comment]
Can you clarify your question? DHCPv6 for ISC or Kea?

**Comment by Handsome1080P** [comment]
> Can you clarify your question? DHCPv6 for ISC or Kea?

ISC.I didn't see kea support ipv6.

**Comment by fichtner** [comment]
Yes, ISC DHCPv6 is integrated and works fine.

**Comment by Handsome1080P** [comment]
> Yes, ISC DHCPv6 is integrated and works fine.

good.thx.

**Comment by Handsome1080P** [comment]
> Yes, ISC DHCPv6 is integrated and works fine.

fk,If ISC DHCP v6 enabled,KEA DHCPv4 will stop work.

**Comment by fichtner** [comment]
Maybe it’s missing the link local setting on the bridge?

**Comment by Handsome1080P** [comment]
> Maybe it’s missing the link local setting on the bridge?

LL set on bridge.Using Radvd working now.
