### ISSUE TITLE
reporting: restructure RRD handling for health graphs

### ISSUE THREAD

**Issue by fichtner** [opnsense/core#7903]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**

rrd.inc is an ancient integration and should likely  be removed (and for the most part it already was on the development version).

**Describe the solution you like**

Replace with flexible drop-in scripts and common boilerplate handling magic.

**Describe alternatives you considered**

N/A.

**Additional context**

N/A

**Comment by AdSchellevis** [comment]
implemented in https://github.com/opnsense/core/pull/7836
