### ISSUE TITLE
unbound startup problem

### ISSUE THREAD

**Issue by fichtner** [opnsense/core#791]
```
# rm -rf /var/unbound
# mkdir -p /var/unbound
# chown -R unbound:unbound /var/unbound
# chroot -u unbound -g unbound / /usr/local/sbin/unbound-control-setup -d /var/unbound
```

Produces the following error since updating unbound to 1.5.7:

```
34379175320:error:0E079065:configuration file routines:DEF_LOAD_BIO:missing equal sign:/usr/src/secure/lib/libcrypto/../../../crypto/openssl/crypto/conf/conf_def.c:346:line 6
/usr/local/sbin/unbound-control-setup fatal error: could not create unbound_server.pem
```

**Comment by mircsicz** [comment]
I've just upgraded a fresh installed 16.1 and now face the same issue. How do I solve the Prob?

**Comment by fichtner** [comment]
@mircsicz run this once on the console:

    # unbound-control-setup -d /var/unbound

**Comment by mircsicz** [comment]
THX a ton! ;-)

**Comment by fichtner** [comment]
Lookie, it's an upstream bug... https://www.nlnetlabs.nl/bugs-script/show_bug.cgi?id=729

**Comment by fichtner** [comment]
Fixed via patching unbound port https://github.com/opnsense/ports/commit/aa4cf2dd91ef4a1ce87efc6fbe558ebba6ea09e8
