### ISSUE TITLE
Linked certificates are not shown as used

### ISSUE THREAD

**Issue by jl-stellar** [opnsense/core#7920]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

We have recently upgraded to 24.7.
Our users are synced via LDAP.
Up until now, certificates that are linked to users had no "trash can icon" because they were in use.
Now, the same certificates are shown as "unused" and therefore also have a "trash can icon".
This was noticed with already existing users and certificates, but is reproducible with new ones.

**To Reproduce**

Requirement: CA set up for issuing OpenVPN certificates

1. Create new user with new OpenVPN certificate
2. Go to System --> Trust --> Certificates
3. Inspect first and last columns for the entry of the new user

**Expected behavior**

The first column icon should be a "checkmark icon" and there should be no "trash can icon" in the last one because the certificate is in use

**Describe alternatives you considered**

not applicable

**Screenshots**

![certs](https://github.com/user-attachments/assets/8c25fa39-9627-4002-9dad-b85905b26b10)
Excerpt from the certificate list. All visible certificates are linked to users.

**Relevant log files**

not applicable

**Additional context**

The users are synced from LDAP

**Environment**

OPNsense 24.7.4 (amd64).
CPU: Intel® Xeon™ D-1518, 4-core 2.20 GHz
Network: 6*1G onboard (supermicro) + Intel® I350-T2

**Comment by AdSchellevis** [comment]
Just to be sure, username equals common name?

**Comment by jl-stellar** [comment]
Yes, checked it twice.
Also maybe of note: Two other certificates (the OpenVPN server cert and the web UI's TLS cert) are shown correctly as "in use".

**Comment by AdSchellevis** [comment]
We can mark a certificate as `in_use` or show it likely belongs to a user when the username exists, but it does need another check somewhere around:

https://github.com/opnsense/core/blob/b5ca261e18915f5c5962e7f5b1d625d44dd28f64/src/opnsense/mvc/app/models/OPNsense/Trust/FieldTypes/CertificatesField.php#L148-L156


I'll put it on the list, although the priority isn't very high, it's mostly a cosmetic thing (preventing removal is not an option for obvious reasons)

**Comment by cpalv** [comment]
testing in a vm I got the check marks to appear by removing '!'
https://github.com/opnsense/core/blob/b5ca261e18915f5c5962e7f5b1d625d44dd28f64/src/opnsense/mvc/app/models/OPNsense/Trust/FieldTypes/CertificatesField.php#L155

to if `$tmp` is not empty and `$path` is in the array `['system.user', 'cert']`

`if (!empty($tmp) && in_array($path, ['system.user', 'cert'])) {`

**Comment by AdSchellevis** [comment]
That only works on old entries

**Comment by AdSchellevis** [comment]
(https://github.com/opnsense/core/commit/9ce4add4dbb3683f483f30977176110b8222f585) When a certificate isn't used (referenced) but the common name matches a local username, show a different icon, example content below:
<img width="113" alt="image" src="https://github.com/user-attachments/assets/46ff0d69-d02d-4568-810f-f2b96a05442f">
