### ISSUE TITLE
No automatic reboot after upgrade?

### ISSUE THREAD

**Issue by kumy** [opnsense/core#7927]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

That is the second time I see that. First time was on my development VM so I thought it was my fault, but it just happen on a second "prod-ready" machine.
After the new packages are installed, the page stay a bit on the "your device is rebooting" popup then it redirect me to the dashboard without rebooting the host.
If I click again on the link "Click to check for updates", the same popup appear again - still no reboot, and was redirected again to the dashboard.

Maybe worth reporting :shrug: 

**To Reproduce**

1. Host was installed and up to date with last week version (was probably 24.7.4 ?)
2. Click on "Click to check for updates" from the dashboard
3. Validate the upgrade

**Expected behavior**

The server should reboot itself

**Describe alternatives you considered**

- Click again on check updates.
- On the dev vm, I remember having used the reboot feature from the portal and got delay and was a bit confused of what happening, but also as I was also connected via ssh I may have issued `reboot` from there.
- I did nothing on the 2nd machine in case you need something from it

**Screenshots**

![image](https://github.com/user-attachments/assets/a2f0388a-c7d2-44b3-aac3-10ae79a719d7)

**Relevant log files**

Please ask if you need some

**Comment by fichtner** [comment]
crowdsec plugin?

**Comment by kumy** [comment]
yes it is installed

**Comment by fichtner** [comment]
ok I'll close and point you to https://github.com/opnsense/plugins/issues/4262

**Comment by kumy** [comment]
Thanks :bow: and sorry for the noise
(To be noted, I doubt I had  that plugin on the dev VM - but it has been reinstalled since, so cannot check for sure.)

**Comment by fichtner** [comment]
For now let's go with the verifiable problem and hope crowdsec will bring a solution soon. IMO it looks like FreeBSD in general is affected at least. You can always raise another ticket once this particular problem is solved but it's still happening. :)

**Comment by kumy** [comment]
100% agree (I didn't expected this ticket to be reopened - just putting note)
