### ISSUE TITLE
reset to factory 

### ISSUE THREAD

**Issue by ali-reza-zareian** [opnsense/core#793]
if ids was enable and we have done **reset factory **,
now ids is still running because  /etc/rc.conf.d file is still remain.so it must be delete in reset factory process.

**Comment by AdSchellevis** [comment]
After a factory reset (and reboot), the file should be there, but with suricata_enable="NO" set in it.
Did you see the contents of this file before deleting it?

**Comment by ali-reza-zareian** [comment]
yes i saw it but suricata_enable="Yes" and  I have forgotten to tell that IPS was enabled too.
I used iso of 16.1 release.

**Comment by fichtner** [comment]
@ali-reza-zareian Can you try to reproduce this on 16.1.4?

**Comment by ali-reza-zareian** [comment]
I will try to and replay ...

**Comment by fichtner** [comment]
timeout
