### ISSUE TITLE
Unbound does not start if OpenVPN failed to start

### ISSUE THREAD

**Issue by paul8046** [opnsense/core#7936]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

If OpenVPN fails to start on boot (in my case because of an invalid server certificate), Unbound does not start either. This is not fixed by re-booting. As soon as the OpenVPN errors have been resolved and OpenVPN starts correctly, Unbound starts. 

**To Reproduce**

1. Deselect a certificate in OpenVPN so that the service will not start
2. Reboot

**Expected behavior**

Unbound starts

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 24.1.10_8-amd64
FreeBSD 13.2-RELEASE-p11
OpenSSL 3.0.14

**Comment by AdSchellevis** [comment]
remove explicit binds on interfaces and you should be fine....

**Comment by paul8046** [comment]
Ah, yes - I was binding Unbound to the OpenVPN interface along with others. Good spot.

That would make this not a bug. However, it would be nice if Unbound didn't fall over in such a scenario. Perhaps this is an area for improvement?

**Comment by AdSchellevis** [comment]
it's not, the fix would be to not offer manual binds (or only on loopbacks).... which would cause other tickets for people insisting they need them.

**Comment by AdSchellevis** [comment]
added a clear warning in the documentation (https://github.com/opnsense/docs/commit/dae34b40e34ba53e0dab7f0653ed960db5bb4a71).
