### ISSUE TITLE
System picture deleted by saving again

### ISSUE THREAD

**Issue by itkfm** [opnsense/core#7940]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

After setting a *Picture* in *System › Settings › General* and saving the picture is set as expected.
But saving that page again (with no change to the picture) deletes the picture.

**To Reproduce**

1. Goto *System › Settings › General*.
2. Click on the picture selector and upload a picture by pressing [Save].
3. The settings page confirms the changes and shows the uploaded picture.
4. Press [Save] again.
5. The settings page confirms the changes and the previously uploaded picture is gone.

**Expected behavior**

The uploaded picture stays in place.

**Describe alternatives you considered**

Not using the new Picture widget.

**Screenshots**

- ![image](https://github.com/user-attachments/assets/787e84b7-7c08-4d0e-b55a-006ebe0531c3)
- ![image](https://github.com/user-attachments/assets/4136a6b7-75c7-4ea6-b9f5-bd547d630d7a)

**Relevant log files**

*n/a*

**Additional context**

*n/a*

**Environment**

- OPNsense 24.7.5_3-amd64
- Firefox 131.0 on GNU/Linux
- Chromium 129.0.6668.70
- Picture is a PNG-8 file.

**Comment by itkfm** [comment]
> Picture is a PNG-8 file.

Also tested it with JPEG – The one in the screenshots is a JPG file.

**Comment by swhite2** [comment]
Should be fixed with https://github.com/opnsense/core/commit/b49b935bb9f80e34358f13dc380e63e0a54eff27

`#opnsense-patch b49b935`
