### ISSUE TITLE
Wireguard is not accessable after reboot

### ISSUE THREAD

**Issue by Northguy** [opnsense/core#7942]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

Wireguard cannot be accessed anymore after a reboot. The service states it is 'up', but no valid connection is shown in the connection overview. 

![image](https://github.com/user-attachments/assets/03e8300a-0679-40ec-b463-b971399f895f)

When Wireguard is manually disabled and re-anabled after a reboot, the tunnel becomes accessible again.
From log file it seems that using Dynamic DNS cannot resolve at boot time, which causes the malfunction.

**To Reproduce**

* Configure wireguard according to https://docs.opnsense.org/manual/how-tos/wireguard-client.html
* Instead of fixed IP, make use of dyndns service and use dyndns url as endpoint address
* connect and test working configuration
* reboot opnsense
* find out that wireguard is not accessible anymore. See screenshot above

Configuration parsing error visible in Wireguard log and system log

**2024-10-03T22:38:42	Error	opnsense	/usr/local/etc/rc.newwanip: The command '/usr/bin/wg syncconf 'wg0' '/usr/local/etc/wireguard/wg0.conf'' returned exit code '1', the output was 'Name does not resolve: `url.redacted.byme:55879' Configuration parsing error'**	

* Disable Wireguard - Apply
* Enable Wireguard - Apply
* Wireguard is accessible again and tunnel is functional

Working tunnel, just by disable/enable action after reboot
![image](https://github.com/user-attachments/assets/5fae6b21-99e3-4cd1-9778-181c099d1663)

**Expected behavior**

Wireguard should be accessible after reboot without manual intervention regardless of use of dyndns.

**Describe alternatives you considered**

N/A

**Screenshots**

See above.

**Relevant log files**

[logfile.txt](https://github.com/user-attachments/files/17250205/logfile.txt)

note the error at **2024-10-03T22:38:42	Error	opnsense	/usr/local/etc/rc.newwanip: The command '/usr/bin/wg syncconf 'wg0' '/usr/local/etc/wireguard/wg0.conf'' returned exit code '1', the output was 'Name does not resolve: `url.redacted.byme:55879' Configuration parsing error'**	

**Additional context**

Note that Wireguard is configured to use DynDns service url.

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 24.7.5_3-amd64
FreeBSD 14.1-RELEASE-p5
OpenSSL 3.0.15

**Comment by Northguy** [comment]
Had a more thorough look in the plugins directory and am 99% sure that the phenomenon described here is the root cause for the issue I described: https://github.com/opnsense/plugins/issues/3186#issuecomment-1907087032

I have adguard set up as DNS resolver and I suspect that wireguard fails due to adguard not being 'up' and not due to the dyndns URL used.

Is there any way to influence the startup order of adguard and wireguard in order in such a way that DNS resolver is present prior to wireguard configuration attempt?

**Comment by fichtner** [comment]
Without a proper Adguard integration this isn't happening. And with Adguard not being in our plugins (for other good reasons) there is no way this will be fixed unless someone takes the time to see how DNS services are integrated into OPNsense and improves the Adguard code in that regard. Most prominently the "dns" configuration plugin hook is likely not populated by Adguard.

What you can do is use the cron job "Renew DNS for WireGuard on stale connections" or execute the script `/usr/local/opnsense/scripts/Wireguard/reresolve-dns.py` with a rc.syshook script after Adguard has started.


Cheers,
Franco

**Comment by Northguy** [comment]
@fichtner clear.

Do you want me to close this issue then, or leave it open in hope of someone picking this up? 

It is a minor issue anyway.  That one time last summer when I was away and a short powergrid failure at home rebooted the router was a bit of a nuisance. Most of the time I am managing a reboot from within the network and am able to login and restart the service.

**Comment by fichtner** [comment]
@Northguy if you are willing to do a follow up on how to solve this with one of the workarounds suggested that would be great. This would help others in the future coming across this issue.


Thanks,
Franco

**Comment by Northguy** [comment]
Hi @fichtner 

Used the firmware upgrade for 24.7.6 as an opportunity to test the cron solution you suggested. This works fine for me. Thanks for pointing that out.

**Comment by Vercety87** [comment]
Hi, I have the same problem. I'm on a fresh new install since 22.7, using unbound. Even with the cron job the problem is still there until I manually restart WG service. Any thoughts about it ?
