### ISSUE TITLE
Kea does not check for already reserved ip adress on new reservation - failed to start up

### ISSUE THREAD

**Issue by firefart** [opnsense/core#7944]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

When adding a new reservation in KEA DHCP there is no check if the reserved ip adress is already taken. I accidently added a second entry with the same ip adress and after some time my whole network went down, because KEA refused to start because of the double entry and thus the DHCP server was unavailable.

The error message during bootup:

```
2024-10-04T11:43:33	Error	kea-dhcp4	ERROR [kea-dhcp4.dhcp4.0xa0026212000] DHCP4_INIT_FAIL failed to initialize Kea server: configuration error using file '/usr/local/etc/kea/kea-dhcp4.conf': failed to add new host using the HW address 'aa:aa:aa:aa:aa:aa and DUID '(null)' to the IPv4 subnet id '4' for the address 10.0.0.22: There's already a reservation for this address
```

(mac adress redacted)

**To Reproduce**

Add 2 reservations with the same ip and restart the server

**Expected behavior**

A check in the GUI in save that prevents this error

**Describe alternatives you considered**

A clear and concise description of any alternative solutions or workaround you considered.

**Screenshots**

**Relevant log files**

If applicable, information from log files supporting your claim.

**Additional context**

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 24.7.5_3-amd64
FreeBSD 14.1-RELEASE-p5
OpenSSL 3.0.15
kea 2.6.1

**Comment by AdSchellevis** [comment]
@firefart thanks for reporting, should be fixed with https://github.com/opnsense/core/commit/415b280959b816e755c25e8b1df58462e737c8e1

**Comment by firefart** [comment]
Awesome thanks for the quick fix!
