### ISSUE TITLE
NAT redirect rules don't respect interface selection and instead rely solely on source address

### ISSUE THREAD

**Issue by Unspec7** [opnsense/core#7952]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

I have a couple of internet NAT redirect rules, specifically to enforce my pihole DNS for my IOT devices, since Google Homes hardcode google DNS. I noticed that despite only wanting to enforce it on the IOT network, it was being enforced on all networks, despite selecting interface as "IOT".

Turns out, this was due to the fact that source was set to "ANY". So it appears that NAT redirects, if source is ANY, completely ignore the set interface and matches all traffic with that rule. This has firewall implications because it can inadvertently allow certain devices on an interface to bypass a firewall rule on that interface due to the unintended redirect. It also makes it impossible to create a single redirect rule that applies to multiple interfaces without creating an interface group.

*Tip*: to validate your setup was working with the previous version, use opnsense-revert (https://docs.opnsense.org/manual/opnsense_tools.html#opnsense-revert)

**To Reproduce**

Steps to reproduce the behavior (note: using DNS redirect for ease of testing):
1. Create NAT redirect rule targeting interface A, with source any, port any, destination NOT your local DNS, and target your local DNS.
2. Create a firewall block rule on interface B that blocks DNS requests to 9.9.9.9
3. On a device on interface B, run dig [something.com] @9.9.9.9
3a. Result: DNS still goes though
4. Set NAT redirect rule in step 1 to have source "Interface A net"
5. On a device on interface B, run dig [something.com] @9.9.9.9
5a. Result: DNS blocked properly

**Expected behavior**

1. Create NAT redirect rule targeting interface A, with source any, port any, destination NOT your local DNS, and target your local DNS.
2. Create a firewall block rule on interface B that blocks DNS requests to 9.9.9.9
3. On a device on interface B, run dig [something.com] @9.9.9.9
3a. **_Result: DNS blocked properly due to NAT redirect rule only applying to interface A_**
4. Set NAT redirect rule in step 1 to have source "Interface A net"
5. On a device on interface B, run dig [something.com] @9.9.9.9
5a. Result: DNS blocked properly.

**Describe alternatives you considered**

Using interface net as the source, but as mentioned before, this is not ideal since it forces you to create interface groups.

**Screenshots**

NAT redirect rule for pihole:
![image](https://github.com/user-attachments/assets/6143fd62-2a05-4d5d-91c9-fddde736ab4a)

Log live view RDR:
![image](https://github.com/user-attachments/assets/2a7b6e28-5e65-4020-81cb-0bc6e01b9b41)

DMZ firewall rules. Second rule doesn't apply even though it should since the redirect shouldn't be redirecting DMZ network traffic:
![image](https://github.com/user-attachments/assets/197c68b6-f6f7-4956-9b72-dbde3944beb0)

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 24.7.5_3-amd64

**Comment by ollioddi** [comment]
Have the exact same issue. It completely grabs anything.

**Comment by Unspec7** [comment]
The current more elegant workaround, other than to make a bunch of firewall interface groups, is to create firewall network aliases with the relevant networks placed in them.

Still not great, but working as a temporary workaround.

**Comment by Unspec7** [comment]
No updates?

**Comment by AleD219** [comment]
Can confirm this on latest version of OPNsense.

**Comment by Unspec7** [comment]
Disabling "Reflection for port forwards" does indeed fix the issue. Are there any considerations we need to take into account when disabling reflection for port forwards?

**Comment by AdSchellevis** [comment]
pros and cons of using reflection can be found in our excellent documentation here https://docs.opnsense.org/manual/how-tos/nat_reflection.html . A default configuration has all reflection options disabled.

**Comment by Unspec7** [comment]
Thanks!!

**Comment by Unspec7** [comment]
Out of curiosity, why does the documentation not provide a Method 4: Creating manual Port-Forward NAT (DNAT), automatic Outbound NAT (SNAT), and automatic firewall rules? That seems like a relatively middle-ground method by disabling reflection but having outbound NAT rules handled automatically. Is there some security risk to doing this hypothetical method 4?

**Comment by AdSchellevis** [comment]
not sure, but it's always possible to open a PR for review. Personally, I'm not a fan of the automatic rules at all, but also understand translations can be difficult for people.

**Comment by Monviech** [comment]
The automatic source nat rules are the most disruptive in my opinion since only a very edge case needs them (traffic reflected by the firewall in the same broadcast domain to preven assymetric traffic).

Just enabling it for everything is like a sledgehammer approach.

**Comment by Unspec7** [comment]
> The automatic source nat rules are the most disruptive in my opinion since only a very edge case needs them (traffic reflected by the firewall in the same broadcast domain to preven assymetric traffic).
> 
> Just enabling it for everything is like a sledgehammer approach.
> 
> EDIT: (I mean the automatic source nat reflection rules, not automatic masquerading for traffic destined to the internet)

Gotcha. So to be clear, the edge case that usually requires outbound NAT rules are cases where client 1 on subnet 1 needs to talk to client 2 on the same subnet but via the *WAN* IP address, correct?

**Comment by Monviech** [comment]
Yeah. Otherwise after the DNAT happens on the firewall (translation of WAN IP to internal IP), the client would take its local direct route in the same subnet to the other client after the first request, because it has the client in its aro table.

It will not communicate symmetrically with the firewall. For that it would need to think that the firewall is the client and thats what Source NAT fakes for this edge case.
