### ISSUE TITLE
mvc: dashboard: Logging a lot of firewall rules impacts dashboard performance on default layout

### ISSUE THREAD

**Issue by Monviech** [opnsense/core#7975]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

Using the default dashboard and triggering the logging of many firewall rules can impact dashboard performance up to the point of freezing the client side browser window.

It is only a client side browser issue. Restarting the browser fixes this.

**To Reproduce**

1. Create a firewall rule that has logging enabled
2. The Firewall widget has to be present on the dashboard
3. Use `hping` to send lots of packets that trigger the prior created rule: ``hping3 -S -p "$TARGET_PORT" --flood "$TARGET_IP"``
4. Have the dashboard open at the same time, the dashboard will slow down and freeze and the RAM the browser uses will steadily increase

**Expected behavior**

The firewall live-log widget and the dashboard continues to work even though a lot of rules are logged.

**Environment**

OPNsense 24.7.6 (amd64)

**Comment by swhite2** [comment]
https://github.com/opnsense/core/commit/2e50dc12de082624844aff65932a994ed458d39f should be enough to address the issue on the short term, longer term a solution is needed to increase accuracy of the event count without introducing a lot of complexity

**Comment by Monviech** [comment]
I have tested this and it indeed prevents the dashboard from freezing up.

**Comment by tribalRu** [comment]
> I have tested this and it indeed prevents the dashboard from freezing up.

I jealous of you, I have the same issue, it hangs after a couple dozen seconds.

**Comment by swhite2** [comment]
> I jealous of you, I have the same issue, it hangs after a couple dozen seconds.

@tribalRu Is this still the case for you on the latest community (24.7.7)? Otherwise I'll close this ticket.

**Comment by fichtner** [comment]
Looks like it's working. ;)
