### ISSUE TITLE
Package request: maradns

### ISSUE THREAD

**Issue by djGrrr** [opnsense/core#798]
Would it be possible to add the dns/maradns port pkg to the opnsense repository?

It has a useful feature for rejecting AAAA records, which can be used in combination with the domain overrides in DNS Forwarder / DNS Resolver, for blocking AAAA records for specific domains.

This can be used to resolve performance issues with specific websites when using an ipv6 tunnel

**Comment by fichtner** [comment]
Ok, added to packages, will be available in 16.1.5. :)
