### ISSUE TITLE
Feature: custom dns port for domain overrides in DNS Forwarder

### ISSUE THREAD

**Issue by djGrrr** [opnsense/core#799]
I would like to see support added to the DNS Forwarder domain overrides section for custom DNS server ports. This support exist in the DNS Resolver by using 1.2.3.4@5353 format for the server, but such support is lacking in the DNS Forwarder.

dnsmasq itself supports this with the format:
1.2.3.4#5353
as in:
server=/test-ipv6.com/1.2.3.4#5353

**Comment by fichtner** [comment]
Ok, I'll take this, but will take till 16.1.6 to materialise as we have some larger DNS improvements in the pipe that need testing.
