### ISSUE TITLE
system: CRL/cert subject hash mismatch in certctl.py

### ISSUE THREAD

**Issue by fichtner** [opnsense/core#7993]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

Some subjects were producing a different hash in certctl.py after refactor, fixed by https://github.com/opnsense/core/commit/d172f15cebb

**To Reproduce**

Revert commit ;)

**Expected behavior**

Correct hashing for CRL and certificates

**Describe alternatives you considered**

N/A

**Screenshots**

N/A

**Relevant log files**

N/A

**Additional context**

N/A

**Environment**

24.7.6

**Comment by AdSchellevis** [comment]
seems to be caused by https://github.com/pyca/pyopenssl/issues/165, fix on its way
