### ISSUE TITLE
error if uncheck 'disable password login'

### ISSUE THREAD

**Issue by unixland** [opnsense/core#8]
Every time I uncheck 'Disable password login for Secure Shell' on the advanced admin config page and click on the save button the next time (after more than 20 seconds) I change an option on this site and press save the following message appears: 

Fatal error: Cannot unset string offsets in /usr/local/www/system_advanced_admin.php on line 189 

If I reselect this SSH-option again the site works as expected.

Everyone should always prefer ssh-keys so I think this is a bug and a feature at the same time ;)

**Comment by jschellevis** [comment]
Confirmed in firefox and chrome. Seems to work in safari though.

**Comment by fichtner** [comment]
@unixland thanks! just to let you know that we are going to flip the wording of that setting sooner or later to fully correspond with the initial configuration of sshd: disabled daemon, disabled password login, disabled root login.
