### ISSUE TITLE
crash reporting not working

### ISSUE THREAD

**Issue by sjorge** [opnsense/core#80]
http://i.imgur.com/sUNk14H.png

**Comment by fichtner** [comment]
Send button was disabled until the server is set up. Several other tweaks went in to make it and the PHP error reporting more useful in the future. Stay tuned. :)

**Comment by fichtner** [comment]
@AdSchellevis the code is now ready to be used again with the send report feature. will you take over and finish this up? :)

**Comment by AdSchellevis** [comment]
@fichtner No  problem, I will put this one on my list

**Comment by fichtner** [comment]
Backend is up. :)
