### ISSUE TITLE
Firewall Staates and SIP

### ISSUE THREAD

**Issue by lieblinger** [opnsense/core#800]
Hi all,

thanks for your great firewall, we really enjoy to use it in our company.

But we have one problem. Scince we update opnsense to the newest Version we have to reset daily the states to make SIP calls possible.

We would be really thankful if you could have an idea.

Hope to hearing Form you inthe near future.

Regards Yannik

**Comment by AdSchellevis** [comment]
@lieblinger What version where you using and what version did you upgrade to?

**Comment by AdSchellevis** [comment]
timeout.
