### ISSUE TITLE
OPNcentral - gateway status not working

### ISSUE THREAD

**Issue by pmhausen** [opnsense/core#8004]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

In the Management > Status > Resources overview the gateways are not shown.

**To Reproduce**

1. OPNsense business edition
2. Install OPNcentral, add host
3. Navigate to Management > Status > Resources

**Expected behavior**

Gateway status should be shown.

**Describe alternatives you considered**

None.

**Screenshots**

![Bildschirmfoto 2024-10-23 um 12 22 29](https://github.com/user-attachments/assets/5f32dc72-1c6d-45aa-8bf0-119fafd2603d)

**Additional context**

Additionally the link in the Resources overview leads to `https://managed.fire.wall/system_gateways.php` which generates a "Page not found" error message.

I suspect the gateway setup was MVC'ified more or less recently and OPNcentral has not yet caught up?

**Environment**

OPNsense 24.10_7
OPNcentral

**Comment by Monviech** [comment]
@pmhausen Thanks for reporting I fixed this one.

**Comment by pmhausen** [comment]
Awesome! Thanks.
