### ISSUE TITLE
Cannot enable DNS Resolver on different port while DNS Forwarder is enabled

### ISSUE THREAD

**Issue by djGrrr** [opnsense/core#801]
When trying to enable the DNS Resolver on a different port than the DNS Forwarder (default or otherwise), you get an error:
The following input errors were detected:
    The DNS Forwarder is still active. Disable it before enabling the DNS Resolver.

If you enable DNS Resolver first, then enable DNS Forwarder, you get no such error, but also has the effect that you can't make changes on the General page of DNS Resolver settings.

We should be able to enable both servers at the same time on different ports, it can be very useful for testing one or the other before switching it to be the main (port 53) dns server.

Perhaps a warning about running both at the same time may make sense, but it should not be an error.

**Comment by AdSchellevis** [comment]
In the current development version, you can't enable both because the resolver performs the opposite check now. But you may change the configuration when it's disabled (fields aren't disabled out any more).
To be honest, I don't know if we really would want two services running on the same box doing approximately the same.

**Comment by djGrrr** [comment]
Isn't that something we should be leaving up to the user to decide? Not put arbitrary restrictions on?
In my opinion, that is a step backwards. Like I mentioned in the original post, if we want to discourage people from running both DNS servers at the same time, we can simply add a warning message when you enable the 2nd one. I see no reason we should be making it impossible to run both.

My use case is to have one of the dns server's run on a different port so that it's configuration can be tested by tools like dig. I have personally had issue with domain overrides in the DNS Resolver that caused overridden domains to time out, while they work perfectly fine in the DNS Forwarder.

I would prefer not to have to break DNS for all LAN clients in order to test if the other dns server is working properly or not.

**Comment by AdSchellevis** [comment]
Don't understand me wrong, I'm not against a solution which provides the possibility to enable both at the same time on different ports, I just expect most organisations use a different machine to do the testing. Pull requests containing a good solution would certainly be evaluated.

I'm willing to change the validation to allow unbound !53, but anything more fancy then that will have to be donated by others.

**Comment by djGrrr** [comment]
You may be right about the most organizations using a different machine for testing, but also keep in mind that it is not only organizations using opnsense. I use it as my home router as it gives me much more control than any retail home router ever could.

Such a simple validation is all it really needs, basically, when enabling either the forwarder or the resolver and the other is already enabled, check that the other is not configured to use the same port (defaulting no setting to 53 of course).

**Comment by fichtner** [comment]
Unfortunately, it does not work so easily for the reverse case with the DNS forwarder on non-standard ports while unbound is running on 53: some code paths will do either-or and this will break DNS connectivity without proper care taken. We agree to keep the status quo, but can't do much more from our side for 16.7. All help is welcome though. :)
