### ISSUE TITLE
Squid : add custom fields

### ISSUE THREAD

**Issue by thelinuxfr** [opnsense/core#802]
Hi,

It is that it would be possible to have a field to enter additional settings proxy ?

_For example, to add the directive: "tcp_outgoing_address 127.0.0.1;"_

Thx

**Comment by AdSchellevis** [comment]
@thelinuxfr I rather not add plain text fields to the configuration for validation reasons, but we probably could extend the template to support custom hooks by placing a template on the filesystem. Would that work for you?

**Comment by thelinuxfr** [comment]
@AdSchellevis yes that's fine. An example of other parameters may be of interest

https://doc.pfsense.org/index.php/Squid_Package_Tuning#Random_Tips.2FTricks

**Comment by AdSchellevis** [comment]
@thelinuxfr the last commit adds the possibility to append custom options before and after the http_access section.

When available, these files will be included:
/usr/local/opnsense/service/templates/OPNsense/Proxy/squid.user.pre_auth.conf
/usr/local/opnsense/service/templates/OPNsense/Proxy/squid.user.post_auth.conf
