### ISSUE TITLE
Minor webgui issue System -> Settings -> General

### ISSUE THREAD

**Issue by azdps** [opnsense/core#803]
Looking at the System -> Settings -> General webui page there seems to be an issue with the way the Use gateway drop down fields are positioned within the page.

**Reproduce under chrome browser:**
Zoom in and zoom out on the General webui page. You will notice unusual positioning of the Use gateway drop down fields.

Also take a look at the System -> Settings -> Firewall/Nat page. There is a similar effect with the start and end edit boxes for the Firewall Adaptive Timeouts. The start edit box isn't aligned with the other edit boxes on the page as well.

**Comment by AdSchellevis** [comment]
@azdps can you post some screenshots of the issue? and what version of OPNsense are you using? I tried some zooming in Chrome on my end but can't seem to trigger the event on our latest version.

**Comment by azdps** [comment]
Have to go to  work right now. Will do it later on when I get home around 5pm  MST.

azdps

**Comment by azdps** [comment]
Does the screenshots show the expected behavior? I didn't seem right that the use gateway drop down lists shift over the the right. I figured they should have remained to the left.

**Comment by AdSchellevis** [comment]
@azdps thanks for the screenshots, I see what you mean. it would indeed be better if they stick together.
