### ISSUE TITLE
Static IPv6 not working has expected.

### ISSUE THREAD

**Issue by rudiservo** [opnsense/core#8041]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at 

**Describe the bug**

Adding a static IPv6 to the Lan does not seem to work has expectedwork, no errors on log, shows in the overview and netstat, but not on the dashboard.
Also setting a new ipv6 does not clear previous ipv6 on overview and netstat.

add from any fe80::/10 a /64 static address. i.e. fe88::1/64

**Expected behavior**

Static IPv6 address should show in overview and DHCPv6 should be able to view that ip-

**Describe alternatives you considered**

adding all the zeros to the IPv6 in the event it was a bug on checking ::, i.e. fe88:0:0:0:0:0:0:1

**Relevant log files**

DHCPv6 show this is the log

```
/usr/local/sbin/pluginctl: dhcpd_dhcp6_configure() found no suitable IPv6 address on lan(em1)
```

Opnsense 24.7.7

**Comment by rudiservo** [comment]
Upon further investigation I came to a problem, the static ipv6 address is not being properly set.

So I tested and tried to add this IPv6 fe90:1:1:1:1:1:1:1/64
![image](https://github.com/user-attachments/assets/8a5e8365-db05-4219-8c9e-2dbcc150bb55)


but in ipconfig I get 
```
inet6 fe90:0:1:1:1:1:1:1%em1 prefixlen 64 scopeid 0x3
```

plus all the tests I did on this interface with IPv6 it just added a new IPv6, it did not substitute.

![image](https://github.com/user-attachments/assets/6ccd586f-0a59-4134-ac2f-26d1183ce102)

Please notive that the second part is always 0 no matter what value I set.

**Comment by fichtner** [comment]
Im unsure what your issue is in general but specifically: the second bit in the link-local is used for scoping in the kernel so you can’t use it. There is a reason why everyone uses the fe80::/64 prefix and only the suffix for addresses.

**Comment by jfieber** [comment]
If you want a locally administered address space, you will want to generate a ULA prefix and assign address out of that. Link local address are for the kernel, not the user.

https://www.unique-local-ipv6.com

**Comment by rudiservo** [comment]
@jfieber got it, thanks.
Now the other issue is DHCPv6 does not work properly until I restarted the whole machine.
I will close this and put up a new issue if one is not up yet-
