### ISSUE TITLE
OPNsense becomes unreachable when new interface is enabled or disabled

### ISSUE THREAD

**Issue by w00000dy** [opnsense/core#8044]
**Describe the bug**

Enabling or disabling an interface and then clicking "_Apply changes_" results in a very long load time. The OPNsense Web UI is also unreachable during this time. I would estimate that it is down for about 5 minutes.

**To Reproduce**

1. Go to Interfaces -> Assignments (URL : .../interfaces_assign.php)
2. Assign a new interface. (e.g. Device: igb3, Description: "test")
3. Click on the "_Add_" button
4. Go to Interfaces -> [test] (URL : .../interfaces.php?if=opt2)
5. Select the "_Enable Interface_" check box
6. Click on "_Save_"
7. Click on "_Apply changes_".

**Expected behavior**

It should take no more than 5 seconds to load after I click "_Apply changes_".

**Screenshots**

![grafik](https://github.com/user-attachments/assets/2830f09b-d287-4e63-98b5-2a2039506ff8)

**Video**

https://github.com/user-attachments/assets/f3feb2a0-1f1c-4e4a-92cd-5bc527aaa400

**Additional context**

Even after a complete factory reset, the problem still exists.

**Environment**

OPNsense 24.7.8-amd64
Intel® Core i7-7500U CPU @ 2.70GHz (2 cores, 4 threads)
Network Intel® I211 Gigabit Network Connection

**Comment by marius137** [comment]
I have the same issue on several DEC3852 Appliances

**Comment by fichtner** [comment]
I think that's the same as https://github.com/opnsense/core/commit/988dbae92 shipping in 24.7.11 tomorrow.
