### ISSUE TITLE
VLAN interfaces no longer working

### ISSUE THREAD

**Issue by djGrrr** [opnsense/core#806]
With the latest stable version installed, vlan interfaces are no longer working properly when adding or after rebooting.

vmx2_vlan234: flags=8003&lt;UP,BROADCAST,MULTICAST&gt; metric 0 mtu 1500
        ether 00:00:00:00:00:00
        inet6 fe80::ec4:7aff:fe69:fef8%vmx2_vlan234 prefixlen 64 scopeid 0xc
        nd6 options=21&lt;PERFORMNUD,AUTO_LINKLOCAL&gt;
        vlan: 0 parent interface: &lt;none&gt;

For some reason the vlan and vlandev are no longer being set correctly

After running the following from the shell everything works correctly:
ifconfig vmx2_vlan234 vlan 234 vlandev vmx2

vmx2_vlan234: flags=8843&lt;UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST&gt; metric 0 mtu 1500
        ether 00:0c:29:2a:17:cd
        inet6 fe80::ec4:7aff:fe69:fef8%vmx2_vlan234 prefixlen 64 scopeid 0xc
        nd6 options=21&lt;PERFORMNUD,AUTO_LINKLOCAL&gt;
        media: Ethernet autoselect
        status: active
        vlan: 234 parent interface: vmx2

I am experiencing this on multiple OPNsense installs. It is a recent issue as it was working fine all long.

**Comment by fichtner** [comment]
Confirmed, will issue a hotfix within the hour.

**Comment by fichtner** [comment]
Hotfixes in the form of OPNsense 16.1.5_1 are now syncing to the mirror and will be available any minute. Thanks again for the report.
