### ISSUE TITLE
Add dhcp-socket-type option to kea

### ISSUE THREAD

**Issue by pieewiee** [opnsense/core#8068]
# Add dhcp-socket-type option to Kea DHCP server

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after checking both open and closed issues

## Problem Description
For the purpose of running DHCP server on specific network setups that require udp socket access, the current Kea implementation in OPNsense lacks the ability to configure the socket type. This option is available in Kea's configuration but not exposed in the OPNsense UI.

## Proposed Solution
Add a dropdown option in the Kea DHCP server settings to allow users to choose between 'udp' and 'raw' socket types. I have implemented this by modifying the following files:

1. [Added](https://github.com/opnsense/core/blob/master/src/opnsense/mvc/app/models/OPNsense/Kea/KeaDhcpv4.xml) socket type field to model definition in `/usr/local/opnsense/mvc/app/models/OPNsense/Kea/KeaDhcpv4.xml`:
```xml
<dhcp_socket_type type="OptionField">
    <Default>udp</Default>
    <Required>Y</Required>
    <OptionValues>
        <udp>udp</udp>
        <raw>raw</raw>
    </OptionValues>
</dhcp_socket_type>
```

2. [Added](https://github.com/opnsense/core/blob/master/src/opnsense/mvc/app/controllers/OPNsense/Kea/forms/generalSettings4.xml) UI form field in `/usr/local/opnsense/mvc/app/controllers/OPNsense/Kea/forms/generalSettings4.xml`:
```xml
<field>
    <id>dhcpv4.general.dhcp_socket_type</id>
    <label>Socket Type</label>
    <type>dropdown</type>
    <help>Socket type used for DHCP communication</help>
</field>
```

3. [Updated](https://github.com/opnsense/core/blob/master/src/opnsense/mvc/app/models/OPNsense/Kea/KeaDhcpv4.php) config generation in `/usr/local/opnsense/mvc/app/models/OPNsense/Kea/KeaDhcpv4.php` to include the socket type:
```php
'interfaces-config' => [
    'interfaces' => $this->getConfigPhysicalInterfaces(),
    'dhcp-socket-type' => (string)$this->general->dhcp_socket_type
]
```

## Alternatives Considered
1. Manual editing of kea-dhcp4.conf file - not persistent across updates
2. Using udp sockets by default - would break compatibility with some setups

## Additional Context
This implementation follows the existing pattern used for other Kea DHCP options and maintains consistency with the current UI design. The change is minimally invasive and maintains backward compatibility by defaulting to 'raw' socket type.

**Comment by AdSchellevis** [comment]
@pieewiee just open a pull-request and we'll try to merge it, as far as I can see, there's no reason to not offer the option from our end.

**Comment by pieewiee** [comment]
This option is particularly valuable when Kea needs to serve DHCP requests for subnets that are not directly connected to the OPNsense router. When using UDP sockets, DHCP packets may not be properly routed through relay agents. Using raw sockets allows Kea to handle DHCP traffic more reliably in complex network setups where DHCP requests need to be relayed across different subnets or VLANs. This is a common requirement in enterprise environments with centralized DHCP management. 


I will create a pull request for you :-)

**Comment by pieewiee** [comment]
Pull request created. 

[feat(dhcp): add dhcp-socket-type option to Kea DHCP server #8069](https://github.com/opnsense/core/pull/8069)

**Comment by pieewiee** [comment]
forgot to close with comment

**Comment by AdSchellevis** [comment]
@pieewiee we usually close after merge :)
