### ISSUE TITLE
How to use configd.py or the backend registry/database to add elements using a python script and without writing xml 

### ISSUE THREAD

**Issue by ji-podhead** [opnsense/core#8072]
Hi,
so i wanted to recreate the module prototypes using python classes and the provided *models* in `/src/opnsense/mvc/app/models/OPNsense/`. so i wrote myself a parser that creates classes from the prototypes.
But then i notices that elements dont get placed in the same field in /conf/config.xml
For example i cant add Firewall lan rules like i add snat rules, but the prototypes are both in the same xml file.
Then i thought: ok never mind, i just can search the parent element, but this wont work either cause the structure of the containers also differs. 

## Example Filter.xml
this is the model  file
```xml
<model>
    <mount>//OPNsense/Firewall/Filter</mount>
    <version>1.0.4</version>
    <migration_prefix>MFP</migration_prefix>
    <description>OPNsense firewall filter rules</description>
    <items>
        <rules>
            <rule type=".\FilterRuleField">
 ...
 ```
 > - theres rules, snatrules and a bunch of others

 - in the config.xml the filter rules are defined as this:
 ```xml
   <filter>
    <rule>
      <type>pass</type>
      <ipprotocol>inet</ipprotocol>
      ...
```
but snatrules are under:
```xml
 <OPNsense>
    <Firewall>
      <Filter version="1.0.4">
        <rules />
        <snatrules /> 
 ``` 
 in the config.xml i can only apply snat rules via OPNsense.Firewall.Filter and rules only under filter.rules.
 ***Is there any other way i can find all the attributes for the wrapper-classes i want to create, other than scanning the php-files, or adding every module-elemt at least a single time via the web gui?***

---

I am not really sure i f i should use the php scripts rather than the daemon or something else. 
I just dont know if configd is having  a in memory representation of the config.xml.

so it wouldbe cool if i could add the objects directly to the registry, rather than dumping xmls. for example like this:
```python
daemon= configd_daemoin
config=daemon.get_config()
config["Fiter"].append(New Filter_Rule())
daemon.apply(config)
daemon.verify()
daemon.save()
```

**Comment by fichtner** [comment]
Mhh, I don't think we should support writing confg.xml directly from configd -- it has read access for templating, but the rest is better done via PHP as it always has been.


Cheers,
Franco

**Comment by ji-podhead** [comment]
> Mhh, I don't think we should support writing confg.xml directly from configd -- it has read access for templating, but the rest is better done via PHP as it always has been.
> 
> Cheers, Franco

hey Franco, 
so i think i know now how to approach this.
So i guess i can create a new Filter like this:
```php
$loader->register();
use OPNsense\Firewall\Filter;

$filter = new Filter();
$filter->rules = new Rules();
$filter->snatrules = new SnatRules();
$filter->npt = new Npt();
$filter->onetoone = new OneToOne();
```
and then maybe use `ApiMutableModelControllerBase.php` to to validate and save.

Will see if that works.

Thanks for your reply and greetings:

ji

**Comment by fichtner** [comment]
Can you start from the top: what do you want do do besides saving firewall rules that the API can already handle?

**Comment by ji-podhead** [comment]
> Can you start from the top: what do you want do do besides saving firewall rules that the API can already handle?

sure, i want to do some stuff that i could not do with the api, like setting physical interfaces.
I already managed to do this using the  config.xml and the script that reconfigures interfaces.
The reason why i needed this was that i wrote a ansible collection that creates ovs-bridges, configures libvirt and sets up docker networks  to isolate vm and container traffic.
Next i wanted to automate the firewall and routing for those networks using ansible.
I created wrapper classes for all the opnsense scripts you can call and provided  autodoc api docs for them. i recreated the argParse objects for those scripts to fetch all the defaults and options, etc.
Next i thought: *why dont i just look for a way to create those python wrapper classes generically*.
And thats where i am now. I created a parser for the xmls in  opnsense/mvc/app/models, to create python classes for this using the defaults and datatypes. 
Now i just need a way to pass the data from the python objects to the php data store.
The cool thing is that i can create autodocs for all the required arguments and methods and you have the descriptions directly in the ide .

**Comment by fichtner** [comment]
Do you mean you need an API to interface settings and assignments? That's one large chunk of work that still needs to be done eventually, but it's not in the current roadmap scope. You are better off templating XML snippets for your needs.

**Comment by AdSchellevis** [comment]
If you need to update legacy sections, you can use the config object, for example to update an existing interface:

```
require_once("script/load_phalcon.php");
$cfg = OPNsense\Core\Config::getInstance()->object();
$cfg->interfaces->wan->if = 'vnet0';
OPNsense\Core\Config::getInstance()->save(
        [
            'username' => 'root',
            'time' => microtime(true),
            'description' => 'my custom update'
        ]
    );
```

`object()` returns a SimpleXML object (https://www.php.net/manual/en/book.simplexml.php)

**Comment by ji-podhead** [comment]
ok thank you both for your feedback!!

Ill close this now and check out the provided snippet!

Love from germany!
