### ISSUE TITLE
Bug in hostapd setup script

### ISSUE THREAD

**Issue by uvNikita** [opnsense/core#8079]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**
I had an issue that my configured WLAN was disappearing as soon as I would enable WPA2/AES on it.
After a lot of debugging, I found that the reason was this code in hostapd setup:

https://github.com/opnsense/core/blob/f8e8969a96eb0887908789967b437c219e64de88/src/etc/inc/interfaces.inc#L2093-L2103

The generated script looks like that:

```sh
#!/bin/sh
# wireless configuration script.

/sbin/ifconfig 'run0_wlan1' link '<mac>'
/usr/local/sbin/hostapd -B -P /var/run/hostapd_run0_wlan1.pid /var/etc/hostapd_run0_wlan1.conf
/sbin/ifconfig 'run0_wlan1' link '<mac>'
```

What I think is happening is because of `-B` flag, `hostapd` goes into background mode as soon as it starts, and the third line gets executed attempting to change mac address right away. Due to this interface gets into a non-functional state.

Note that this is happening even if I don't touch mac spoofing configuration at all and both macs from the script above are identical.

As soon as I comment out the code that generates ifconfig command and re-run the interface configuration, everything is working as expected.

**To Reproduce**

1. Create WLAN with no authentication
2. Confirm it's working as expected
3. Add WPA2/AES configuration (doesn't matter which options)
4. SSID disappears
5. Comment out the code generating the second ifconfig mac change
6. Save, apply config, reboot firewall
7. SSID appears as expected with WPA2 auth

**Expected behavior**

WLAN working with WPA2/AES enabled.

**Describe alternatives you considered**

- Commenting out the part of the code that generates the second mac change fixes the problem.
- I wonder if just removing the -B flag would also help since then the second mac change wouldn't happen right after hostapd is started but rather would ran after it's finished as intended. I haven't tested this solution.
- Alternatively, I would be fine if those mac changing lines wouldn't generate at all if mac spoofing is not in use since it's just trying to change to the mac address it already has.

**Additional context**

WiFi module used: AW-NU706H / RT3070

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 24.7.9 (amd64).

**Comment by AdSchellevis** [comment]
This stuff is really old, maybe we should try to remove both mac address switches and see if it works on your end, let me push a commit to try for you

**Comment by AdSchellevis** [comment]
@uvNikita can you try https://github.com/opnsense/core/commit/cb6ec88a16f63afbcc82268213d104fc87bb9abe?

```
opnsense-patch cb6ec88
```

**Comment by uvNikita** [comment]
Yes, this fixes the issue, thanks a lot!

**Comment by AdSchellevis** [comment]
@uvNikita thanks for confirming, let's close this one then.
