### ISSUE TITLE
Rule Loading Errors Not Displayed

### ISSUE THREAD

**Issue by landonix** [opnsense/core#808]
The end user does not receive an error message if an alias is not accepted and the rules fail to load.

The UI continues showing new rules/modifications, but 'pfctl -sr' does not show the modifications. The issue can be uncovered further by seeing the modifications in /tmp/rules.debug and manually attempting to load the rules with `pfctl -f /tmp/rules.debug' which uncovers which line of the config has an issue.

**Comment by AdSchellevis** [comment]
no need to open 3 issues for the same case, duplicate https://github.com/opnsense/core/issues/810 https://github.com/opnsense/core/issues/809
