### ISSUE TITLE
No IPv6 Adress from Telekom Germany 

### ISSUE THREAD

**Issue by Tagor12** [opnsense/core#8083]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**
Hello,
I hope you can help me.
I can get an IPv4 address without any problems, but unfortunately I cannot get a v6 address.
I have already searched some tutorials and unfortunately I can't find my configuration error.
i also tried to get help from the Forum, where they sayed, that i have to make an Bug report.
(https://forum.opnsense.org/index.php?topic=44191.msg220388#msg220388)

i have an Telekom fiber ONT and an x86 (Intel N100) Pc with the newest OPnsense.

my config for IPv6 is the following:

**To Reproduce**

IPv6 is enabled.
IPv6 config:
  IPv6 Configuration Type: DHCPv6
  Use VLAN priority: 0 but I have also tried it with disabled.
  Use IPv4 connectivity: activated
  Prefix delegation size: 56
  Request prefix only: activated
 

Unfortunately, my IPv6 address always starts with FE80:.

**Expected behavior**
I should get an IPv5 Adress

**Describe alternatives you considered**
I have testet an OPNWRT router after my Telekom ONT and it gets the IPv6 Adress without any Problems.

**Relevant log files**

Sorry this is my first time using opnsense so i don't know how i can get a log, wich would help you.

**Additional context**
I have this opnsense box running for 4 Month and never had an IPv6 Adress with any version.

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 24.7.9  (amd64).
Intel® N™ 100
Network Intel® I226-V

**Comment by Optic00** [comment]
isn't it SLAAC on PPPoE and Telekom and not DHCPV6 on WAN?

**Comment by fichtner** [comment]
SLAAC is a prerequisite for DHCPv6 in general, because DHCPv6 has no concept of a default route. ;)

**Comment by fichtner** [comment]
> Unfortunately, my IPv6 address always starts with FE80:.

Which is correct for WAN when:

> Request prefix only: activated

**Comment by fichtner** [comment]
@Tagor12 ok feel free to circle back here, but I will close for now if that's ok.
