### ISSUE TITLE
OCSP stapling support is missing for lighttpd

### ISSUE THREAD

**Issue by meyergru** [opnsense/core#8084]
- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**

When I want to make use of ACME certificates for dual-use, like for HAproxy sites and OpnSense itself, I want to be able to use OCSP stapling. Currently, OpnSense does not support it.

**Describe the solution you like**

Lighttpd supports OCSP stapling since 1.4.56:

https://redmine.lighttpd.net/projects/lighttpd/wiki/Docs_SSL#OCSP-Stapling

Once could use "ssl.stapling-file" in the configuration and have a cron job that fetches its content regularly, like described in the docs.

**Describe alternatives you considered**

Having another non-OCSP-stapling certificate, just for OpnSense.

**Comment by Monviech** [comment]
https://github.com/opnsense/core/pull/5567

Just for reference.

**Comment by fichtner** [comment]
IMO the whole discussion was derailed so nothing came of it. A prime example of what discouragement does to open source contributions. 🤷‍♂️

**Comment by meyergru** [comment]
Sorry, did not find it in open issues... should I close this?

**Comment by Monviech** [comment]
I guess the TLDR of the whole discussion in that PR was that upstream has a script for it.

**Comment by meyergru** [comment]
I rest my case, since Let's Encrypt will stop supporting this anyway: https://letsencrypt.org/2024/12/05/ending-ocsp/
