### ISSUE TITLE
OPNSense Theme CSS Issue

### ISSUE THREAD

**Issue by jkoch2** [opnsense/core#8088]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

Borders are transparent on last nav tab or page selector.

*Tip*: to validate your setup was working with the previous version, use opnsense-revert (https://docs.opnsense.org/manual/opnsense_tools.html#opnsense-revert)

**To Reproduce**

1. Go to 'System>Settings>Cron'

**Expected behavior**

Border on right side is colored black.

**Describe alternatives you considered**

Using a different theme.

**Screenshots**

![Borders](https://github.com/user-attachments/assets/0d9b0ac8-e86c-4568-83aa-50c36e581722)

**Relevant log files**

N/A

**Additional context**

This is overwriting the color. Can this line be removed or moved to inside of the `@media`?
https://github.com/opnsense/core/blob/669a602e3f7abf82549a5ff4d813b745f8da7e2a/src/opnsense/www/themes/opnsense/assets/stylesheets/main.scss#L598

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 24.7.9_1 (amd64).

**Comment by AdSchellevis** [comment]
looks like a minor, rather old, glitch indeed. As far as I could find this style has been in there since the beginning. At a first glance it looks  like we remove it
