### ISSUE TITLE
URI Allowed in Aliases via WebUI

### ISSUE THREAD

**Issue by landonix** [opnsense/core#809]
The webUI allows the entry of a URI, however pf will not process a URI which causes an error when loading a firewall rule policy. This was identified via troubleshooting issue [808](https://github.com/opnsense/core/issues/808).

**Comment by AdSchellevis** [comment]
no need to open 3 issues for the same case, duplicate https://github.com/opnsense/core/issues/810 https://github.com/opnsense/core/issues/809
