### ISSUE TITLE
Cert Manager Issues

### ISSUE THREAD

**Issue by sjorge** [opnsense/core#81]
Leaving aside the issue whether CA's are good or evil...

# description
The current Cert Manager is still pretty broken. I guess over the years pfsense never fixed any of the issues. (EasyRSA does it properly for example)

The mean issues with the current implementation is that it more or less ignores 'Key Usage' and 'Basic Constraints'. If you don't know what they are, ... They restrict what can be done with the certificate. They are like keys to a house, you usually only want one key to do one thing (or a few).

OPNsense should deal with 3 types of certificates:
  * Certificate Authorities (Use to sign other certificates, should never be used for client/server communications)
  * Server Certificates (Can be used by web interface, OpenVPN server,...)
  * Client Certificates (OpenVPN Client)

Currently the Cert Manager does not know the difference between Client and Server certificates. Nor is the CA's it create restrained properly. (Also things like subjectAltName are missing)

## Certificate Authority
http://i.imgur.com/ApvvGLX.png
  * Basic Constraints are set correctly (yay) 
  * Key Usage is not set, it should be set to ```Certificate Signing, Off-line CRL Signing, CRL Signing```

This is to make the CA only usable to sign other certificates and manage the revocation list (to blacklist bad/compromised certificates)

## Server Certificates
http://i.imgur.com/boRAHz1.png
http://i.imgur.com/Nam9VS9.png
  * Key Usage and Enhanced Key Usage missing :( should be ```Server Authantication -> Digital Signature, Key Encipherment```
  * CN is usually a fqd
  * can have additional DNS/IP entries can be added -> subjectAttName to allow SNI on webservers

This will restrict the certificate to be used by a server, e.g. web server, openvpn server,... it will be usable for signing (e.g. a download) and encryption and provide authentication of the server side.

## Client Certificates
http://i.imgur.com/85bIBCD.png
Currently not supported at all.
  * Key Usage and Enhanced Key Usage  should be ```Client Authentication -> Digital Signature```
  * CN is usually fqdn of the client machine or name of a person
  * often has email field set
  * can have additional DNS/IP entries can be added

Issue #59 is related to this, certificates generated from the user dialog should be of this type

# propose solution
## (a) drop the entire cert manager
  * Drop the entire Cert Manager as we know it
  * Provide Certificate and Key fields for: web interface certificate, OpenVPN server/client, ...
  * offer a generate icon next to the fields to generate a self signed one (make sure it is of the proper type though)

Why would you choose a?
  * Certificate Management is not the responsibility of a firewall (comment thread on 53b031e8cb9c6a1522c3ea1481bd30261a5a4b8b)
  * Less code = less attack surface, less bugs

## (b) fix the cert manager
  * Properly implement Basic Constraints, Key Usage and Enhanced Key Usage
  * Add additional checks to prevent wrong type to be used in the wrong place (e.g. client cert for web interface or OpenVPN server, server cert for OpenVPN client,...
  * ...

Why would you choose b?
  * VPN functionality is present, by extend certificate management is needed
  * Currently aside from EasyRSA (awesome but command line only) and the Certificate Authority rules on windows server I know of no (proper) Certificate Manager that is easy to use and free
  * Lots of work needed to fix it, will be needed anyway (e.g. to provide the self-sign options for OpenVPN, Web Interfaces...)
  * We can one up pfsense and brag about it ;)

*braces for endless discussion about this*

**Comment by sjorge** [comment]
pfsense dev have done a change like what is described here.
https://github.com/pfsense/pfsense/commit/ed2265217acc84b6c83e307de01d25d0688cb603

**Comment by AdSchellevis** [comment]
@sjorge commits https://github.com/opnsense/core/commit/9b432e836fed920538bc7b5cf80ce3fcd2374e24 https://github.com/opnsense/core/commit/45a82edb9700d70df1b238208b40bb7f014472de https://github.com/opnsense/core/commit/44a02f94f619b824ba15b931ab34cac644caf5bc should fix this one including an info dialog (displays openssl x509 -in cert.pem -text) and a fix for the Subject Alternative Names.

**Comment by sjorge** [comment]
Will this show up in opnsense-devel? If so I can upgrade my test box to check it out.

**Comment by AdSchellevis** [comment]
yes, this will be in the next devel build @fichtner probably knows when this one will be released.

**Comment by fichtner** [comment]
Wow, great! 15.7.23 planned for December 21, or I'll refresh the devel version in-place, not sure yet.

**Comment by fichtner** [comment]
@sjorge please check back when you can, closing this to continue bugs or hiccups in other tickets. :)

**Comment by sjorge** [comment]
I think I already checked this, a I remember telling Ad job job on fixing it.

**Comment by fichtner** [comment]
purrrrfect, thanks! :)
