### ISSUE TITLE
Host Aliases Allow URLs, Filter Reload Lacks Error Message

### ISSUE THREAD

**Issue by landonix** [opnsense/core#810]
From my reading on pf lists/macros, URLs are not allowed. However, names are allowed. The webUI for alias should be updated from URLs to names, to avoid confusing users who may actually enter URLs.

**Comment by AdSchellevis** [comment]
@landonix URL's can be used to download lists from, so they are in OPNsense actually an option.
some additional info can be found in our docs https://docs.opnsense.org/manual/aliases.html?highlight=alias 

Are do you mean something else?

**Comment by landonix** [comment]
My apologies. The issue exists when a URL is entered into the host aliases as shown [here] (https://usercontent.irccloud-cdn.com/file/p2cWaiAV/image.png). No error is provided thereafter showing that rule mods are failing to load.

**Comment by fichtner** [comment]
Thanks, issue(s) have been identified and error reporting will be back better than ever. Will fix this in time for 16.1.6 tomorrow :)

**Comment by fichtner** [comment]
Handing this over to @AdSchellevis for GUI parts if needed.
