### ISSUE TITLE
TOTP Authentication

### ISSUE THREAD

**Issue by Technopass53** [opnsense/core#8100]
Hello,
I have a pairs of Opnsense server in high avaibility 24.7.9, I can use OTP on one server but not in the other. The configuration is exactly the same (replication is done correctly between them) and NTP server is the same and it is OK.
What I saw, it's a problem with the password build (I saw that by doing "tcpdump port 389 -X" on both). For example, If I try a LDAP+OTP on both servers :
       On the server where it's OK the ldap resquest  has the password and NOT the OTP ticket (password)
       On the server where it's not OK the ldap resquest  has the password and the OTP ticket (password123456 or 123456password)
So there's a problem in the build of the request.
Note :
If I try with a local account+otp it's not working.
If I try only LDAP, it's working
If I try only local account it's working
If I try only local Account, it's working.
Thank you in advance for answers.
Software version used and hardware type if relevant, e.g.:

Best regards

**Comment by fichtner** [comment]
Did you update both to 24.7.9_1? _1 contains the hotfix for a TOTP issue.

**Comment by Technopass53** [comment]
Hello,
Thank you for your answer. No, I didn't, I've just do it and now it's OK.
Thank you very much.
Best regards

**Comment by fichtner** [comment]
forum link for reference https://forum.opnsense.org/index.php?topic=44347.0
