### ISSUE TITLE
Lighttpd PHP_FCGI_CHILDREN cap limits usability

### ISSUE THREAD

**Issue by heeeck** [opnsense/core#8103]
**Important notices**

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

In newer versions, the widgets seem to consume to many PHP_FCGI_CHILDREN. Open the dashboard for more than a couple of seconds the widgets wont load anymore and any `Apply changes` needs 20 seconds or more.

**To Reproduce**

Install a current version (in my case 24.7.9) and let the dashboard open for a couple of seconds.

**Expected behavior**

A working system which wont change its behavior, if u let it half a minute in idle.

**Describe alternatives you considered**

Changing the `"PHP_FCGI_CHILDREN" => "3"` in `/usr/local/etc/inc/plugins.inc.d/webgui.inc` to any value 30 or above gives a fluent experience.

**Environment**

OPNsense 24.7.9.(amd64).

**Comment by AdSchellevis** [comment]
has been > 3 for months now (https://github.com/opnsense/core/commit/724f8494d64074e0384b9f593e699daf2d84d604)

**Comment by AdSchellevis** [comment]
I'm not sure what your issue is, but as mentioned, the PHP_FCGI_CHILDREN is higher in current releases than reported in your ticket.

**Comment by heeeck** [comment]
Thank you i will check further
