### ISSUE TITLE
System: Snapshots permission has wrong target

### ISSUE THREAD

**Issue by novaclark** [opnsense/core#8111]
**Important notices**

- [ x ] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [ x ] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

The permissions page at https://opnsense.local/system_usermanager_addprivs.php has a permission for System: Snapshots that appears to use the wrong endpoint of /ui/snapshots/*, which should be /ui/core/snapshots/*.

**To Reproduce**

1. Go to System: Access: Users or System: Access: Groups
2. Edit the effective privileges of a non-admin user and check the box for System: Snapshots and Save
3. Log out of OPNsense and back in as the user that was granted the permission
4. Note that Snapshots does not appear under the System menu
5. Paste https://opnsense.local/ui/core/snapshots into the browser's location bar and hit enter
6. The browser redirects to the OPNsense Dashboard
7. Paste https://opnsense.local/ui/snapshots into the browser's location bar and hit enter
8. You see the error Page not found

**Expected behavior**

I expected to see Snapshots under the System menu when logged in as a user with the System: Snapshots permission

OPNsense 24.7.10_2-amd64
Intel(R) Xeon(R) CPU E5-2450 v2 @ 2.50GHz

**Comment by fichtner** [comment]
This should do the trick? :) 918ba63

    # opnsense-patch 918ba63


Cheers,
Franco
