### ISSUE TITLE
Reboot not Possible- not from GUI or Shell command

### ISSUE THREAD

**Issue by andreasvel** [opnsense/core#812]
OPNsense 16.1.5_1-amd64 
cant reboot with Webgui command or on SHell command 

reference: https://forum.opnsense.org/index.php?topic=2353.0 (german)

**Comment by fichtner** [comment]
Hallo Andreas,

Ich hab ehrlich gesagt keine Ahnung was man hier tun für core.git tun kann. Das liegt am System, nicht am Code.

Wenn du kein /var und /tmp MFS Mount hast kannst du mit FreeBSD's "reboot" (über Option (8) aus der Konsole) rebooten. Wenn das auch hängt geht nur ein Power-Cycle... Falls es /var und /tmp MFS Mount gibt, dann sind die DHCP Leases und RRD Graphen weg.


Gruss
Franco

**Comment by andreasvel** [comment]
MIr gings drum hier abzuklären ob das ein evtl grösseres Problem bzgl. der Funktion der Kommandos das dieses evtl. nicht funktioniert in Kombination mit PPPOE über VLAN
Reboot über Feebsd ging. PPPOE geht jetzt auch...
evtl ist der GUI Befehl zu erweitern um einen "force" befehl?

dank dir

**Comment by fichtner** [comment]
@AdSchellevis do we still need this? does it need to open the file as "w+" even? https://github.com/opnsense/core/blob/master/src/etc/rc.halt.common#L16-L23

@andreasvel alles in der Datei oben könnte blockieren von unserem System, also eigentlich nur das Datei-Lock, DHCP Lease Backup, RRD Backup, Ein RC Skript (Squid Proxy z.B.), eigene "Syshook" Stop Skripte

Force wäre direkt einen FreeBSD reboot auszuführen wie du es gemacht hast. Ich überlege mal ob/wie man das einbauen könnte.

**Comment by AdSchellevis** [comment]
@fichtner its safer to wait here, if there is another process writing to the config you don't want to shut-down immediately. The mode however should have been a+, I will correct this in the following commit.

**Comment by fichtner** [comment]
thanks :)
