### ISSUE TITLE
[CARP] Unicast Mode and HA-Sync

### ISSUE THREAD

**Issue by Ramalama2** [opnsense/core#8120]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**
The issue is, that if you Sync "Virtual IPs" between both Firewalls, the peer IP in Carp Interfaces will set to the same ip on both firewalls.

In other settings like isc-dhcp for example, there is somewhat an "Intelligence" behind, so the peer is there always the other side if you sync.
I seen that in some other configs either, that sync and use the right name or ip.

Sure i can disable the Sync for "Virtual IPs", but it somehow doesn't feel like fully thought out.
Instead there should be some script ot something behind:
If a user sets a unicast peer IP in carp settings, the xmlrpc-sync should send the config to backup with the Interface IP-Address from actual firewall set as Carp-Peer for the backup-firewall.

Probably not easy to do but would make more sense as at the moment.
(Or at least in worst case, ignore the Carp Peer-IP and dont set it at all?)

Cheers

**Comment by AdSchellevis** [comment]
likely not going to make the bar as it's prone to "assumptions". An option where both are set at the primary firewall might work, but given this stuff hardly changes, manual configuration is likely the better option here (when auto configured multicast isn't an option).

**Comment by Ramalama2** [comment]
Yeah thats true either.
