### ISSUE TITLE
Max. 125 traffic shaper rules in GUI supported

### ISSUE THREAD

**Issue by Abraham1220** [opnsense/core#8123]
Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

I detected in version 24.7 and also in version 24.1 the issue, that when you have more than 125 items maintained in the Trafficshaper rules section, it's not possible anymore to change existing entries. After pressing the "Save" button, the popup windows is not closing and also the update is not done in the config file.

This also applies to pipe changesl when you have more then 125 rules defined.

When I reduce the number of rules back to 125 or below, the saving is working well again.

Please check this bug.

Thanks.

**Comment by AdSchellevis** [comment]
best check browser console, network traffic via the browser and the crash reporter, there's no hard limit set in the rules, so you will have to collect more useful data to increase chances of progressing your issue.

**Comment by Abraham1220** [comment]
Here you have a config file from a fresh installation, where I included 126 traffic shaper rules. Import just the "Shaper" section into your test system. You will see that you cannot modify any entry in pipes or rules. Data is not saved. Delete one rule and then try again. ;-)

I am wondering what is causing this issue.
[test-126-rules.zip](https://github.com/user-attachments/files/18098550/test-126-rules.zip)

**Comment by AdSchellevis** [comment]
no problem at my end, imported the trafficshaper section and added/copied some rules:

<img width="1390" alt="image" src="https://github.com/user-attachments/assets/6e86ecfd-96f2-4eac-91fd-9b122bb8757c" />

**Comment by Abraham1220** [comment]
Adding and copying is working. It's about changing an existing entry when you have more than 125 rules!

**Comment by AdSchellevis** [comment]
which yields a crash report:
```
[11-Dec-2024 20:48:27 Europe/Amsterdam] PHP Fatal error:  Allowed memory size of 1073741824 bytes exhausted (tried to allocate 1052672 bytes) in /usr/local/opnsense/mvc/app/models/OPNsense/Base/FieldTypes/BaseListField.php on line 156
```

Hence the earlier question...

**Comment by AdSchellevis** [comment]
https://github.com/opnsense/core/commit/70e7695b3dbb464545063bd16c65b136ffe2865d should fix the issue.

**Comment by Abraham1220** [comment]
I applied manually to my 24.1 version and it works. Thanks a lot.
