### ISSUE TITLE
Kea - should not support underscore in hostnames

### ISSUE THREAD

**Issue by firefart** [opnsense/core#8128]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

KEA should not allow underscores in hostnames as it's not allowed: https://en.wikipedia.org/wiki/Hostname#cite_note-8
unbound for example errors out on such a hostname with `KEA: refusing to register non standard hostname [example_test]`

**To Reproduce**

Add a static mapping in KEA and put a `_` in the hostname

**Expected behavior**

Only `-` but not `_` are allowed

**Describe alternatives you considered**

**Screenshots**

**Relevant log files**

**Additional context**

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 24.7.10_2-amd64

**Comment by AdSchellevis** [comment]
don't you love standards.... https://github.com/opnsense/core/issues/7492 https://github.com/opnsense/core/issues/7976

I couldn't find the error in KEA, your ticket states unbound, but I assume you mean KEA here. Are there other messages in the log? It might be practical to note the reference as well to prevent the next person complaining it doesn't support rfc2181.... removing the support is easy by the way (ditch `IsDNSName`)

**Comment by firefart** [comment]
No the error appears in unbound as it registers KEA leases, but it fails when a hostname contains a `_`. KEA itself is behaving fine

**Comment by AdSchellevis** [comment]
@firefart ok, got it, it's one of our own constraints being a bit to tight (https://github.com/opnsense/core/commit/ee269a1991eebdb7cce38488fe20ec3682bb5788)

**Comment by xconverge** [comment]
I had a single hostname entry in my KEA mappings that had a space in the name.  Today when I upgraded to 24.7.12 this caused unbound to fail to start (when register static mappings was selected).

My question is should there be some sort of validation/error happening on the KEA Reservations tab for the hostname?

**Comment by firefart** [comment]
@xconverge as far as I understand the validation is only happening in PHP code on save and not on startup, so I think you need to remove the faulty entry manually.

**Comment by xconverge** [comment]
> [@xconverge](https://github.com/xconverge) as far as I understand the validation is only happening in PHP code on save and not on startup, so I think you need to remove the faulty entry manually.

Sounds good, in 24.7.12 I can save a hostname with a space in it and apply those changes in KEA without it ever validating or complaining, maybe this is a different issue?

**Comment by firefart** [comment]
I guess so. I would suggest to open a new ticket so someone from the team can have a look at this
