### ISSUE TITLE
Routing API toggleGatewayAction() bug

### ISSUE THREAD

**Issue by Abraham1220** [opnsense/core#8130]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

Applies to:
/opnsense/mvc/app/controllers/OPNsense/Routing/Api/SettingsController.php

In method toggleGatewayAction() is a soure-code error in line 267.

Currently (wrong):
`$result['changed'] = (string)$node->disabled === $disabled;`

Correct (tobe):
`$result['changed'] = (string)$node->disabled !== $disabled;`

kr/m

**Comment by AdSchellevis** [comment]
@Abraham1220 nice catch, thanks
