### ISSUE TITLE
Delegated DHCPv6 Static Reservations Convert Decimal to Hexidecimal in Lease

### ISSUE THREAD

**Issue by Ryushin** [opnsense/core#8139]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [ X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X ] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

Running version: 24.7.11

When setting a reserved IP address in a delegated prefix, input is received is as a decimal, but the outputted reserved lease is in hexadecimal.

![DHCPv6_Static_Mappings](https://github.com/user-attachments/assets/0b355fbf-d3cd-4408-ad39-955a803686de)

![DHCPV6_Leases](https://github.com/user-attachments/assets/d1e3ef15-d7d6-418c-9636-6c888b27d943)

Both should be the same.  If ::0.0.0.10 is entered for the static lease the output should also be .10 and not .a.

**Comment by fichtner** [comment]
In practice that’s impossible as a general rule. An IPv6 is just a 128 bit number and this information gets los somewhere, especially with compression in play.

**Comment by Ryushin** [comment]
I agree the IPv6 addresses are in hex.  I'm saying that when you create the reserved IP address, the input is in decimal and the actual lease is converted to hex.

**Comment by fichtner** [comment]
No, they are not `::0.0.0.28` or `::0.0.0.a` because the leases page does **not** show IPv4-mapped IPv6 address format.

To reiterate: you are using IPv4-mapped IPv6 address format. It has colons AND dots at the end which mimics an IPv4 address (mapped in IPv6). This is a convenience way of setting an IPv6, but the actual adress displayed as a normal IPv6 is what you see...

**Comment by Ryushin** [comment]
This is under the ISC DHCPv6 Leases.  I'm not using any IPv4-mapped to IPv6.  The IPv6 /64 prefix is handed to the LAN from the WAN /56 prefix requested from my ISP.

Since the LAN has a /64 delegated prefix, the first four sets of numbers are already specified and I just specify the last four sets of numbers, so ::0.0.0.28 or whatever.

I've worked around this by converting the hexadecimal number I want as a static mapping to decimal number in the mappings.  So I wanted ::0.0.0.10 as the lease I entered ::0.0.0.16 in the static mapping.

I think this is a bug since this is related just to to DHCPv6 and is not related to DHCPv4.

**Comment by fichtner** [comment]
Also see https://serverfault.com/questions/1102241/purpose-of-ipv4-mapped-ipv6-address

**Comment by Ryushin** [comment]
I've attached the full GUI of what I'm seeing.  Unless I'm just dain bramaged, these are not IPv4-mapped IPv6 addresses:

![WAN_DHCPv6_client_config](https://github.com/user-attachments/assets/e3f5a567-0a0e-4363-be4d-d4896a75332f)
![LAN_Track_IPv6_Interface](https://github.com/user-attachments/assets/17819a3a-24cc-4b3b-ba73-7591d6a85f15)
![ISC_DHCPv6_LAN_Page1](https://github.com/user-attachments/assets/bdec3529-f814-4e03-8916-38c23b8a06ad)
![ISC_DHCPv6_LAN_Page2](https://github.com/user-attachments/assets/0bf160ee-9f6b-43e1-8f5f-c663b3a02729)
![DHCPV6_Leases_2](https://github.com/user-attachments/assets/06c0d7c8-fb22-40d7-a39d-07ee801bcaa5)

**Comment by fichtner** [comment]
In the third screenshot under "DHCPv6 Static Mappings for this interface" you are using the IPv4 mapped notation for the IPv6 address. It works fine within the bounds that it was designed for...

"0.0.0.10" translates to "00.00.00.0a" (0xa) which is also "::a" in the compressed IPv6 format :)

What I don't understand is why you don't use "::10" in the static mappings and be done with it. You can ignore all the hex chars if you want.

**Comment by Ryushin** [comment]
The help showed 1:2:3:4.  I originally tried ::10 and that didn't work so I thought the syntax needed ::1:2:3:4.  I just tried entering ::10 again and I must not have hit "save" the first time as it worked this time when I tried it.

So I still think that this is a bug.  If I enter ::10.10.10.10 the address, the lease should be ::10.10.10.10 and not ::a.a.a.a.

Since it's working for me using the compressed IPv6 format then I'm happy.  I'll let you decide if this is a bug or not and if not, I'll let you close the ticket.

![IPv6_Address](https://github.com/user-attachments/assets/06103c64-8503-4f8f-b881-3923a18f0776)

**Comment by fichtner** [comment]
I don’t want to decide. I tried to explain. 😊

**Comment by Ryushin** [comment]
> I don’t want to decide. I tried to explain. 😊

LOL.  Then lets keep this opened as this does not pertain to using IPv4 mapped notation.  If assigning a IPv6 static lease with ::10.10.10.10 the assigned lease should be <prefix>:10.10.10.10 and not <prefix>:a.a.a.a.  There should be no decimal to hexadecimal hanky panky going on.

**Comment by Ryushin** [comment]
> Ok, how about https://www.internex.at/de/toolbox/ipv6/ip6=::10.10.10.10/prefix=64
> 
> The IP address is `::a0a:a0a` and note the absence of dots, because `::a.a.a.a` is not a valid IPv6, but you already know this so I don't know what we are arguing about.

Oh my word, @fichtner you are so right.  Must be end of the year tiredness and pushing myself too hard to get things done.  I was using dots (.) instead of colons (:) so I was using IPv4 notation.  Bloody hell, I apologize for wasting your time.  Can't believe I did such a noob mistake.

**Comment by fichtner** [comment]
No worries, this stuff isn't easy. :)
