### ISSUE TITLE
Trust: How to import certificates programmatically via a plugin?

### ISSUE THREAD

**Issue by fraenki** [opnsense/core#8141]
**Important notices**

Our forum is located at https://forum.opnsense.org , please consider joining discussions there in stead of using GitHub for these matters.

Before you ask a new question, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

The Acme Client Plugin plugin frequently imports new certificates to the OPNsense Trust Storage. However, it still uses the legacy method of importing certificates, which has severe drawbacks.

So I'm wondering: is there a new method available? I couldn't find one. Please point me to the right direction (no in-depth example necessary). Thanks! :blush:

**Comment by AdSchellevis** [comment]
Hi Frank, from code on the machine, you can implement the model. Do you have a code snippet you're currently using to import certificates? maybe I can offer you a small example on how to do that using the model.

**Comment by fraenki** [comment]
Sure, but it's not pretty. :smile: 

https://github.com/opnsense/plugins/blob/fc5629d810ac8b447f9aca1f6fac1f6c646b3739/security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/LeCertificate.php#L271-L290

This is the part where the certificated is added to the config "the legacy way". In the lines before this the cert entry is crafted using the legacy `cert_import()` function.

**Comment by AdSchellevis** [comment]
ok, so seek and update by `refid`, I'll try to glue an example today, no problem.

**Comment by fraenki** [comment]
Converting my code to use the new cert uuid may also be an option, in case this matters.

**Comment by fraenki** [comment]
Thank you very much! I'll give it a try.

**Comment by fraenki** [comment]
@AdSchellevis, I've got it working (https://github.com/opnsense/plugins/pull/4449), thanks again!

I've noticed that the `parseX509()` function does not provide the serial and issuer of the cert. Would it be possible to add this information too the output of this function? This would allow me to drop more legacy code.

I may also submit a PR, if you don't mind.

**Comment by AdSchellevis** [comment]
@fraenki I don't mind pull-requests at all, but this is a quick an easy addition, so I've done it for you in https://github.com/opnsense/core/commit/f72e066e4d57558e972379cc61dd6d35625f4834

There's no reason not to add this information, just don't want to pull in everything without a reason.
