### ISSUE TITLE
Enhance Proxy Server Log File

### ISSUE THREAD

**Issue by thelinuxfr** [opnsense/core#815]
Have the same interface as the one in the FireWall section in order to seek prondeur and appreciate more detailed statements for the proxy access:
- normal view
- dynamic view
- summary view
- plain view

So you can find / easily filter visits and user actions. Very useful for example for the French [HADOPI](https://en.wikipedia.org/wiki/HADOPI_law) law :)

**Comment by fichtner** [comment]
I'm not strictly against that, but I'll have to park this under "future" as it's not a priority, but contributions on this would be nice to have, thanks! :)

**Comment by fichtner** [comment]
We should opt for a lightsquid integration or similar. Nothing for the core anymore.
