### ISSUE TITLE
system: shells are now static in the model, but must be read from /etc/shells

### ISSUE THREAD

**Issue by fichtner** [opnsense/core#8155]
**Important notices**

Our forum is located at https://forum.opnsense.org , please consider joining discussions there in stead of using GitHub for these matters.

Before you ask a new question, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

The new model makes shells static but that is not correct:

> Even though bash is installed (via pkg install bash) and appears in /etc/shells, it doesn't appear as a shell choice in the UI.

As a side quest the user says:

> If I choose another valid shell it still gets written as nologin in /etc/passwd and so I can't log in as that user via SSH.

https://forum.opnsense.org/index.php?topic=44771.0

**Comment by AdSchellevis** [comment]
I know, but realistically there are not a lot of valid choices, I think I rather add some static options with a note (bash, when installed) than more glue for options hardly anyone uses.

**Comment by bensmithurst** [comment]
I have created https://github.com/opnsense/core/pull/8156 which solves both problems for me, I will let you decide how to proceed.

Thanks

**Comment by fichtner** [comment]
I am a bit in doubt that deviating from the previous, OS aligned, unproblematic behaviour gains much other than future reports.

Also, not having opnsense-shell as an explicit choice anymore seems strange. Another side effect from removing auth_get_shells().

**Comment by AdSchellevis** [comment]
> Also, not having opnsense-shell as an explicit choice anymore seems strange.

I also expected opnsense-shell in the option list, but while looking at the code again, it is only offered for root... 

https://github.com/opnsense/core/blob/908f3ee73edc10ba147c8dddd6c6b946b1d01229/src/etc/inc/auth.inc#L221-L223

In which case the default choice will be non explicit the same:

https://github.com/opnsense/core/blob/908f3ee73edc10ba147c8dddd6c6b946b1d01229/src/etc/inc/auth.inc#L348-L349

In which case I don't think it's much of a loss here, unless we would like to offer it to non root admins as well (which is something we can do without issues).

I can live with something that plugs shells, although given `bash` is likely the only relevant non default available choice, a static list might even be better in terms of maintenance. The last commit @bensmithurst added (https://github.com/bensmithurst/opnsense-core/commit/0bb18c5badd39b05eed54c8e8edd6bbe7fad2d52) is more or less ok (although we would often wire these via `configd`), question just is if in the long run we are seeking this type of extensibility (if it wasn't there before, I wouldn't add it now, but there are arguments for keeping it).

**Comment by fichtner** [comment]
> I also expected opnsense-shell in the option list, but while looking at the code again, it is only offered for root...

Which is quirkily correct since it needs root privileges to run the scripts successfully and used to be the implicit standard shell for admin/root long before it was called opnsense-shell.

> In which case I don't think it's much of a loss here, unless we would like to offer it to non root admins as well (which is something we can do without issues).

It would be nicer to make it explicit, because otherwise nologin and empty login default cause confusion. Again, most of this is old code, which we could migrate now and switch to explicit defaults / values.

I like the shell field, maybe with a backend script to gather all shells and cache the value for a few seconds or so.

**Comment by AdSchellevis** [comment]
it's not really worth the discussion, although static fields are slightly faster, I also don't mind having it pluggable that much. https://github.com/opnsense/core/commit/96a1145c3e453af7ac5cfdf6d035667b5b58bc9c contains the dynamic shell field implementation which can cope with other shells.
