### ISSUE TITLE
Disk widget not working

### ISSUE THREAD

**Issue by TheCeet** [opnsense/core#8168]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**
Installed 25.1 on new nvme.
The disk widget on dashboard isn't working. It shows 'Free: 100%'.

**To Reproduce**
1. Go to 'dashboard'
2. Hover on 'disk'
3. See result

**Expected behavior**
Working disk widget

**Screenshots**
![image](https://github.com/user-attachments/assets/6c062f2f-e5ff-48b8-b659-6b7393f944ed)
![image](https://github.com/user-attachments/assets/60f05b22-8237-4995-a692-2945f2b88c9c)

**Additional context**
![image](https://github.com/user-attachments/assets/8edf0840-6734-4801-ba2f-853ca879e6e2)

**Environment**
Software version used and hardware type if relevant, e.g.:
OPNsense 25.1.b_20-amd64
FreeBSD 14.2-RELEASE
OpenSSL 3.0.15

Lenovo M720Q 
Intel(R) Core(TM) i5-8400T CPU @ 1.70GHz

**Comment by AdSchellevis** [comment]
your df shows the same as the graphs, doesn't it? (100% free, roughly 0% used)

**Comment by TheCeet** [comment]
I get it now.

Total size: 453G
Used: 1.2G
To get 1% used, I need 4.5G used status.

My bad!
