### ISSUE TITLE
KEA DHCP reservations import ignores encoding and imports incorrectly

### ISSUE THREAD

**Issue by giggio** [opnsense/core#8169]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

Accented imported values show incorrect characters.

**To Reproduce**

1. Create a file with an accented character (example bellow)
2. Go to KEA DHCP reservation import
3. Import the file

**Expected behavior**

Accented characters are correctly imported and show as expected.

**Describe alternatives you considered**

Import and fix manually. Very impractical if you have too many values (I do).

**Screenshots**

![image](https://github.com/user-attachments/assets/98438ac1-805a-49fa-9caf-a37a63189973)

**Relevant log files**

N/A.

**Additional context**

I have tried several different encodings, like UTF-8, UTF-16, Western etc. None works.

Sample CSV:

```csv
ip_address,hw_address,hostname,description
10.0.0.100,60:60:60:60:60:60,escritorio,Escritório
```

**Environment**

Software version used and hardware type if relevant, e.g.:
OPNsense 24.7.11_2-amd64
FreeBSD 14.1-RELEASE-p6
OpenSSL 3.0.15

**Comment by fichtner** [comment]
Looks like faulty double-encoding to me, which can happen when the original file encoding did not properly detect or when the encoding was present but the preamble was not.

This can be especially problematic with Windows bound ASCII encodings, but not strictly limited to.


Cheers,
Franco
