### ISSUE TITLE
Feature: configurable IPv6 Link-Local address

### ISSUE THREAD

**Issue by djGrrr** [opnsense/core#817]
Link-Local addresses should be configurable for interfaces when using Static IPv6.

It can be very useful to be able to set link-local ips for a router,  fe80::1 is commonly used for the "internal side" of a router so that no matter what range an IPv6 network might be using on various interfaces, you can always use a gateway address of fe80::1

For the implementation, if an interface does not yet have any IPv6 configured, ie, not inet6 addresses, it is as simple as:
ifconfig ixv0 inet6 fe80::1/64 -auto_linklocal

If IPv6 is already configured, you must first remove all inet6 addresses; first standard ipv6, followed by link-local, then you can run the above command to configure the static link-local.

On the UI side, there would simply need to be an additional optional field for setting the link-local ip when configuring Static IPv6 that only allows you to set the ip, not the bits, which should be /64. For validation, the ip only need's to be within fe80::/64

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/core/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
