### ISSUE TITLE
Missing certificate SANs field

### ISSUE THREAD

**Issue by mlofjard** [opnsense/core#8171]
When I edit a previoously issued certificate with SANs (Subject Alternative Name), the DNS names are not filled. I think this is due to the mapping at the following line:
https://github.com/opnsense/core/blob/752795a22996eddbe8dcef88298555d83f12ce9b/src/opnsense/mvc/app/library/OPNsense/Trust/Store.php#L410

I think it should be "DNS Name" instead of "DNS"

**Comment by AdSchellevis** [comment]
more likely this https://github.com/opnsense/core/issues/8116

**Comment by mlofjard** [comment]
> more likely this #8116

Thanks, I missed that one. =)
