### ISSUE TITLE
Blacklist categories are not sorted and incomplet

### ISSUE THREAD

**Issue by gitdevmod** [opnsense/core#819]
Using blacklist from UT1, categories available are not sorted and incomplet. After selecting categories new ones are added
![blacklist](https://cloud.githubusercontent.com/assets/2040775/13780458/da73d39c-eabf-11e5-8f06-a4117ab3c369.PNG)

**Comment by gitdevmod** [comment]
I updated to 16.1.7 categories are sorted but still truncated (only 10 in the drop list)

**Comment by fichtner** [comment]
@gitdevmod It's either the browser cache or the remote list not being updated afterwards... worst case, try downloading again / readding the list

**Comment by gitdevmod** [comment]
After cleaning the browser cache, it works as expected thanks :+1:

**Comment by fichtner** [comment]
Whew, cool. Thank you for testing. :)
