### ISSUE TITLE
Widgets: Can't move them (16.1.6)

### ISSUE THREAD

**Issue by b2000699** [opnsense/core#820]
It is not possible for me to move widgets across the dashboard, using Firefox.
Other than making it difficult for me to sort widgets as I please, when I delete widgets, this produces great white spaces between the remaining widgets.

**Comment by fichtner** [comment]
This is the default ;) We have a ticket that will take care of dashboard widget customisation. It will likely be in 16.7 the very latest. https://github.com/opnsense/core/issues/597

**Comment by b2000699** [comment]
OK!
