### ISSUE TITLE
Dashboard: Autorefresh loses scrolling position

### ISSUE THREAD

**Issue by b2000699** [opnsense/core#821]
16.1.6 with Firefox 44.0.2:

Every few seconds the dashboard scrolls up to the first line. I guess that the cause for this is that the dashboard is getting refreshed by some widget.

This feels broken, since it is highly annoying when having scrolled down and monitored some widget. It would be good, if the dashboard would remember the scrolling position after refreshing itself and thus not change its scrolling position so not to annoy the user.

**Comment by fichtner** [comment]
Agreed. I would like to move this to #597 as well as I suspect fixing this now will double the amount of work in this area for something that has been the default behaviour (even though iffy even for me) for a long time  -- could you add a note there and close this? :)

**Comment by b2000699** [comment]
Ok, I just did that!

**Comment by fichtner** [comment]
Thank you :)
