### ISSUE TITLE
Feature: Remember "Full help" setting of menus

### ISSUE THREAD

**Issue by b2000699** [opnsense/core#822]
It would be beneficial if the "Full help" choice of the menus would be remembered so that a new user is not forced to re-select it every time he changes from one menu to another.

BTW: Great feature!

P.S.: Maybe an even greater option might be if the "Full help" setting would be remembered for each menu separately?!

**Comment by fichtner** [comment]
This is generally nice to have but I am not sure somebody will pick up the work. We don't want to clutter the GUI so this should be stored as a cookie. Hm, cookies.
