### ISSUE TITLE
WebUI sluggish when accessed via HTTPS on a 250+ vlan host

### ISSUE THREAD

**Issue by isrc** [opnsense/core#826]
Hi,
Thanks for your hard work on the opnsense project ! 

For the cloud lab i'm trying to setup, i would like to configure a opnsense-on-a-stick router with a trunk link (with more that 500 vlans) between my compute node and the opnsense (physical) server/router so that a vlan could be dedicated ot each of my users.
OPNSense is running bare metal on a host with an Intel® Xeon® Processor E5420 cpu , 8G RAM and 6 NIC

The configuration, which is was partially generated via a mini-script and is attached to  this report (NB:password attribute has been deleted), seems to be correctly imported and the CLI shows that all of the vlan subinterfaces have been created
But, the WebUI is so slow when accessed via https  that it is barely useable :-/ It took me 15 min for example to show the configuration of a single interface. In the meantime, ssh access works just fine. 

After trying several options, It appears that disabling the https (and the redirect to https) access  solves the issue !?

Any hint on what could be the bottleneck please :-) ? 
[config-OPNsense.gw_opennebula.orig.xml.250.txt](https://github.com/opnsense/core/files/175881/config-OPNsense.gw_opennebula.orig.xml.250.txt)

Thanks
PS:I tried to copy/paste some Dtrace one-liner to help me find the issue but it seems that Dtrace doesn't work at all even if the modules are loaded :-/ Is that a known issue please ?

**Comment by fichtner** [comment]
@isrc hi there, is this still an issue? we suspect it's the old config system coupled with static php pages (end in ".php" in the address bar). pages will slowly change to MVC, but this takes us all the way into 2018 due to the sheer amount of work necessary.
