### ISSUE TITLE
Feature: Dashboard - Colors: More contrast for widgets

### ISSUE THREAD

**Issue by b2000699** [opnsense/core#827]
Hi all,

I am currently comparing the dashboards of pfSense and OPNsense side-by-side and have noticed that the strong color contrast of the pfSense dashboard (white background / dark gray widgets / red headline of widgets) helps me a lot to quickly grasp visually the dashboard and thus quickly "understand" what I am seeing

This is opposed to OPNsense, where the colors are all quite similar with low contrast to each other (everything consists of variations of very light gray and white), what - when browsed quickly - does make it harder for me to visually grasp what I am seeing.

Thus, I would recommend to change the color theme to something with more contrast, especially having a contrast between background and the widgets, as well as highlighting the headline of each widget.

A super bonus feature would be of course, if those colors would be settable by the user in an options menu, so that everyone could set it as he pleases, or maybe even a theme/skin-layer.

Thank you very much for your great work!

**Comment by fichtner** [comment]
Hi there,

Please double-check 16.1.7 (out in an hour), we've made the widget status bars darker and smaller. All of this is just the tip of the iceberg as we've had some internal discussion on dashboard revamp, e.g. a lot of the widgets have inconsistent style to begin with. I know, I've said this before... more is planned in the next weeks, be sure to watch the progress and help guide the restyle.

(This can also include running opnsense-devel or opnsense-stable and upgrading the packages from core.git manually. I'll have a tutorial up soon.)

And thank you too, please let these reports keep coming. I really like the explanations, they help a lot. :)


Cheers,
Franco

**Comment by b2000699** [comment]
Hi Franco,
I just checked the update and indeed the title bars of the widgets are darker and have a smaller hight. I like both changes, the (unfortunately only a little bit) darker color increases the contrast, thus I can grasp the different sections better and the decreased height helps saving screen real estate.
For my taste, the contrast could even be further increased (i.e. widget title bar even darker, whole widget contrasting better from background, lines inside a widget alternate with lines of higher contrast, etc.). And I would love it if all widgets would not be as generous in spending screen real estate, i.e. by reducing line height.

But as I had written already: I guess all this is a matter of individual taste - and as we know, there are as many different opinions about taste as there are different users.
So my preferred option would be to have those settings not hard coded, but settable by the user in some menu (e.g. widget title color, widget title font size, widget content color 1, widget content color 2 (for alternating lines), widget content font size, dashboard background color). Maybe this thought could even be extendable to a full fledged theme/skin-plugin logic for the whole interface some day.

Thank you!

**Comment by AdSchellevis** [comment]
custom theme's are possible using css (theme selection in system_general.php).
