### ISSUE TITLE
collapsible menu bar

### ISSUE THREAD

**Issue by sjorge** [opnsense/core#83]
Option to have the menu bar auto collaps (force on small screens) into a small row with icons only unless hovered over. To maximize screen realestate

**Comment by fichtner** [comment]
Hover I don't personally like because it diverges from a mobile workflow: only clicky-clicky there. Collapse the menu on page load sounds like something to discuss/consider.

**Comment by fichtner** [comment]
16.1.15 will have improvements here, no collapse needed.
