### ISSUE TITLE
Tool tips at /System/Firmware not working

### ISSUE THREAD

**Issue by b2000699** [opnsense/core#830]
Hi there,

the tool tips at the right side of /System/Firmware are not working (i.e. of the recycle and unlock icons)

Cheers

**Comment by fichtner** [comment]
Interesting, works in Chrome + Safari but not in Firefox doing a quick check. What browser are you using?

**Comment by fichtner** [comment]
The tooltip placement is off, it's only on the icon so it might not "work" although it does what it is programmed to do. This needs fixing for sure. There is, however, a larger issue that renders the tooltips differently and adds a delay that is not present in other pages. Will need to investigate a bit more...

**Comment by b2000699** [comment]
Hi fichtner, 
I am using Firefox 45.0
Cheers
