### ISSUE TITLE
Suricata: Impossible to set a default action for a ruleset without downloading and updating all rules

### ISSUE THREAD

**Issue by oparoz** [opnsense/core#831]
1. Go to /ui/ids/#settings
1. Press (i) for one of the rulesets
1. In the modal window,  set the input filter to "Drop"
1. Hit "save changes"

At this stage, the filter column shows "drop" but nothing has happened as far as rules are concerned...

1. Click on the rules tab
1. Click on Apply

Action for those rules still hasn't changed.

The only solution is to go back to settings and to click on "download and apply". It shouldn't be necessary to update all rules to apply this change.

Best solution would be to: Apply the changes when the user clicks "Save changes" in the modal window
Next best thing would be to: Update all those rules when the user clicks on apply in the rules section

**Comment by AdSchellevis** [comment]
@oparoz our "filter" option is a download filter option (applied on download, the original file doesn't exist in this case), so yes, you need to download the file again to get the latest version using your settings. 
Maybe we could add a comment somewhere to make the current behaviour more obvious, but then again, the docs describe it quite clearly too (https://docs.opnsense.org/manual/how-tos/ips-feodo.html)

**Comment by oparoz** [comment]
> our "filter" option is a download filter option (applied on download, the original file doesn't exist in this case)

@AdSchellevis Hmmm. I don't follow. That ruleset was installed and logging alerts, so it shouldn't even need to be downloaded again.
And my main problem still stands. If there is no way around downloading the ruleset again, not all rulesets need to be updated when only one of them was affected by a change.
I've tried to tick only the one, but all rules were updated nonetheless.

**Comment by AdSchellevis** [comment]
@oparoz yes, its installed using your selection. so if you don't add a filter, its the original file, when you added a filter, its not... there's no way for the system to know what it should do, other then downloading again (it streams the data through the filter before saving to disc).

If you only want to download the changed files, you could do that in theory, although you probably will need quite some extra logic for that, and but to be honest, I don't see the big gain here (for an operation that's most of the time only done during initial setup). 

In case you want to build this feature, feel free to create a pull request.

**Comment by oparoz** [comment]
>(it streams the data through the filter before saving to disc)

Ah, now I understand the technical reason for the behaviour.
The main reason I don't like downloads is that a Suricata reload used to cut-off connections, but doing some tests now didn't seem to disrupt the VPN connections, so maybe that point isn't valid any more.

>I don't see the big gain here (for an operation that's most of the time only done during initial setup).

I was concerned about hitting the mirrors repeatedly when trying out things, but in retrospect it's far from being the same as ddosing a server since there will need to be a time period during which the change has to be monitored

Let's close this and if I encounter problems again with Suricata, I'll see if I can improve this area.
Thanks for the insightful replies.

**Comment by AdSchellevis** [comment]
@oparoz your welcome, glad that I could be of help here.
