### ISSUE TITLE
Proposal: Move "Settings/Admin Access" to /Access

### ISSUE THREAD

**Issue by b2000699** [opnsense/core#832]
Hi,

I would like to propose to move "Settings/Admin Access" to "/Access" since it seems to fit and since the current arrangement confuses me with access management in 2 different menus.

Cheers

**Comment by fichtner** [comment]
Indeed, been meaning to move the firewall settings page to the firewall section for clarity for a while. General setup also seems to be a bit lost in all of this. If we do this a plan needs to be devised for the whole menu, here's a collection for further discussion:

General -> ???
Admin Access -> System / Access / Admin
Networking -> Interfaces / Settings
Firewall / NAT -> Firewall / Settings
Notifications -> ???
Logs / Reports -> ???
Miscellaneous -> ???
Tunables -> ???

**Comment by fichtner** [comment]
As a side note, moving the pages is done by moving the entries around in /usr/local/opnsense/mvc/app/models/OPNsense/Base/Menu/Menu.xml

https://github.com/opnsense/core/blob/master/src/opnsense/mvc/app/models/OPNsense/Base/Menu/Menu.xml

No page modifications necessary anymore. Maybe you want to give it a try on your box. Seeing is usually better than anything else.

**Comment by AdSchellevis** [comment]
Another side note, you can also easily plugin your own menu, the current version doesn't support removing of existing items yet, but as of this commit https://github.com/opnsense/core/commit/d53780856a58f6ad4d4c090cce42ddacd7e0dbee you can really build your own menu if you like.

If you create a Menu.xml in the models directory it will be automatically loaded by the system.

For example, create this file:
```
/usr/local/opnsense/mvc/app/models/MyCompany/Sample/Menu/Menu.xml
```

using the following content:
```
<menu>
	<System>
        	<Access order="90" visibility="delete"  cssClass="fa fa-users fa-fw">
        	</Access>		
	</System>
        <Access order="10" cssClass="fa fa-users fa-fw">
            <Users order="10" url="/system_usermanager.php">
                <All url="/system_usermanager.php*" visibility="hidden"/>
                <Privileges url="/system_usermanager_addprivs.php*" visibility="hidden"/>
            </Users>
            <Groups order="20" url="/system_groupmanager.php">
                <All url="/system_groupmanager.php*" visibility="hidden"/>
                <Privileges url="/system_groupmanager_addprivs.php*" visibility="hidden"/>
            </Groups>
            <Settings order="30" url="/system_usermanager_settings.php"/>
            <Servers order="40" url="/system_authservers.php">
                <Edit url="/system_authservers.php*" visibility="hidden"/>
            </Servers>
            <Tester order="50" url="/diag_authentication.php"/>
        </Access>	
</menu>
```

Would place all Access items at the bottom of the menu.

**Comment by b2000699** [comment]
Hi!

My propositions / feedback on your propositions would be:

General -> ???
I would tear that apart and place the topics into the other menus. E.g.:
DNS: /Networking (currently "Interfaces")/DNS
hostname & domain /Networking/Identity,
Language & Theme: /System/Settings/Web interface
Time zone: /System/Settings/Hardware (together with additional features for system time, e.g. system date & Time, hardware clock set to UTC?, etc. as not every system has the ability to run NTP).
Firmware stuff /System/Firmware

Admin Access -> System / Access / Admin: +1

Networking -> Interfaces / Settings: +1
Additionally I would:
- Rename /Interfaces to /Networking
- Put all interfaces into /Networking/Interfaces (I have almost 20 NICs, so it would be good to have them in a sub menu)
- Move /System/Gateways & /System/Routes to /Networking

Firewall / NAT -> Firewall / Settings: +1

Notifications -> ???
Logs / Reports -> ???
I would place it together with /System/Log file to /System/Logging & Reporting

Miscellaneous -> ???
I would cram the proxy and load balancing stuff to /Networking(currently "Interfaces")/Proxy and /Networking/Load Balancing, the Schedules and Gateway monitoring to /Firewall and the remaining stuff (PowerD, Crypto accel, Thermal Sensors, RAM disk, etc. into /System/Hardware, then delete "Miscellaneous"

Tunables -> ???
I would tear this menu apart and place those settings as "Advanced tuning" in the menus of the respective topics, e.g. networking stuff to the /Networking menu, firewall to /Firewall, etc.

Cheers

**Comment by fichtner** [comment]
Progress on the easy targets although it's clear that further refinement is necessary for all pages to avoid new clashes in navigation and underlying features. This will take some time to finish. Please bear with us. :)
