### ISSUE TITLE
Bind WebConfigurator to Specific IP/Interface(s)

### ISSUE THREAD

**Issue by landonix** [opnsense/core#833]
I'd like to make a feature request to allow binding the WebConfigurator to a specific IP/interface(s) for simplified access control.

**Comment by fraenki** [comment]
+1 because the bind to `*` is annoying when using the (Web) Load Balancer in OPNsense: If all web servers of the load balancer are down the OPNsense webConfigurator is shown (instead of the usual error page of the browser).

**Comment by mschilt** [comment]
+1 is also a source for misconfiguration should someone apply too lax ACL.

**Comment by fichtner** [comment]
duplicates #1347
