### ISSUE TITLE
Proposal: Move /System/Settings/General/Firmware Mirror & Flavour to /System/Firmware

### ISSUE THREAD

**Issue by b2000699** [opnsense/core#834]
Hi,

I would like to propose this move since it seems to fit better and since the current arrangement confuses me with options concerning the same topic in 2 different menus.

Cheers

**Comment by fichtner** [comment]
You must be reading my private TODO list :) This will happen soon, I've asked Ad to take care of this for me as the firmware page is MVC, but the firmware settings are in the old parts of the GUI so there is a config path mismatch.... reassigning, thanks!

**Comment by b2000699** [comment]
Glad about your feedback, fichtner!

What I am currently doing is: I am a brand new, pure virgin user, who has never seen your interface before and who goes through it step by step.
I am recording every discrepancy/inconsistency that I might encounter/feel, since as soon as I will get used to the interface, I will not notice them anymore myself!

Hope that helps!
Cheers

**Comment by AdSchellevis** [comment]
@fichtner this one will have to wait, the best solution would be to move the properties into a new style model, but we can only do that if the data can either be migrated or moves with it automatically.

My current idea is to extent the model system to be able to reference a "previous location" for a property which will fetch the data from there if its not available in the new location and deletes the old location on save (kind of an inline migration). 
This will need some additional thinking, and I first like to have unit tests in place before changing any thing major here.
