### ISSUE TITLE
Proposal: Default settings shown as "(default)" > Better to display what the default setting is!

### ISSUE THREAD

**Issue by b2000699** [opnsense/core#835]
Hi all,

I just saw some settings, such as /System/Settings/General/Firmware Flavour, where the default setting is "(default)". I think that it would be beneficial in those cases to indicate to the user what the default is, since I have e.g. no clue if the default is LibreSSL or OpenSSL in this case, etc.

Cheers

**Comment by fichtner** [comment]
Hi there,

This is tricky without tainting the config / reading back the defaults from a write only template location. "default" defaults to nothing, meaning the actual package default of the GUI package. This was also done for compatibility with custom builds that override this default. The changes in #834 will be coupled with a rework of those two settings, so let's merge this issue into the other one (should already show up as referenced).


Thanks,
Franco
