### ISSUE TITLE
Proposal: Firewall/Rules: Change icons for "log" & "reject (disabled)"

### ISSUE THREAD

**Issue by b2000699** [opnsense/core#838]
I really like the icons and find them much nicer than they are in pfSense, but I have 2 proposals:

1. The icon for "log" and for "log (disabled)" are too similar, so it is error prone for confusion. How about just coloring the "log" icon blue, as it is in pfSense but as it is also the standard for "Information" signs?

2. The icon for "block (disabled)" and "reject (disabled)" are absolutely similar, so that there is a lot of information lost in the overview table. I would suggest to change the icon of "reject" and "reject (disabled)" to a different icon, e.g. to a "thumbs down" icon as shown here: [https://cdn2.iconfinder.com/data/icons/toolbar-signs-4/512/fail_delete_agt_action_usb-512.png](https://cdn2.iconfinder.com/data/icons/toolbar-signs-4/512/fail_delete_agt_action_usb-512.png) or something like that, so that block and reject are easy and unmistakably distinguishable from each other!

Cheers

**Comment by fichtner** [comment]
1. adding "text-info" to match and log
2. using remove-sign for now for reject, changing colour to "text-danger"

I would like to migrate to font awesome as we've done for the menu, but that's going to take a lot longer selecting the "right" icons... I'm happy the menu is in a good state now. :)

**Comment by b2000699** [comment]
Wow, great response time!! I really like this project, it feels really nice to be here!

I would have gone for glyphicon-thumbs-down for deny, instead of remove-sign, though. I think it fits better to the "denial" character and it cannot be confused with reject (glyphicon-remove)... :-)

**Comment by fichtner** [comment]
The small things matter most, no? :)

The notion of reject is to send a disruptive packet instead of just dropping and none of the glyphicons can do that very well, so for now I wanted to stick with the similar pattern that is easier to distinguish and kind of matches the design of the log icon.

Let's just find better icons with font awesome and focus on fixing it for good with that next iteration, ok?

**Comment by b2000699** [comment]
Sure, I am a detail fetishist ;-)

I thought that that "X" fits perfectly to "dropping", since it resembles just a dry "no trespassing here" while "rejecting" includes some active form of communication, which I thought that this thumbs-down icon resembles quite good, as showing someone a thumbs-down is an active act of nonverbal communication saying "I reject you" :-)

Out of interest: Why do you want to change to font awesome? I am new to both glyphicon and font awesome as well to bootstrap in general, etc. so I am eager to learn.

BTW: Will those small instant fixes/changes be available through weekly updates or only in the final 16.7 release?

**Comment by fichtner** [comment]
Small scope fixes go directly to the next stable release 16.1.x, the development version for 16.7 is always a bit ahead, but sometimes not by much. It's gotten more of a staging area for testing than a "new next major stepping stone".

Gylphicons looks a bit edgy and mechanic, plus they also only have about 250 icons:

http://getbootstrap.com/components/

Font-awesome (as used in the menu) is more playful, round and thus easier on the eyes. Plus they have over 600 icons which makes it easier to find appropriate symbols:

https://fortawesome.github.io/Font-Awesome/icons/

Getting a bit into the psychology of a thumbs down would imply a manual fiddling or a sort of displeasing statement in terms of the traffic being rejected. Gylphicons do not have an icon such as the following:

http://fortawesome.github.io/Font-Awesome/icon/ban/

The transition through the temporary reject should be kept minimal, as the new reject builds on the old one and addresses your original problem with it. The next transition will make the icon a lot clearer, in a natural progression, not going "hands" and then going back to "sign".

This also takes us to the point of whether "X" should be used for drop at all. Feel free to skim through font-awesome and see if there is anything that fits better. :)
