### ISSUE TITLE
feature: dashboard interface widget could use relase/renew icon for dhcp interfaces

### ISSUE THREAD

**Issue by sjorge** [opnsense/core#84]
See title

**Comment by fichtner** [comment]
I like this.

**Comment by fichtner** [comment]
I was trying to work on this, thinking:

(1) Where would be possibly put this in the confined space of the widget.
(2) We only release, not renew. This may lead to fatal clicking in the dashboard section. Ideally the dashboard would be read-only. Don't know if there is anything that works against this rule that's in there?

**Comment by sjorge** [comment]
Having one icon that pops up a menu with both choises? That solved both tie space and the accidental click issues

**Comment by fichtner** [comment]
The confirm does work indeed. I also like the simplicity of splitting release / renew so we really can't offer both choices at the same time.

Lastly, there's the issue of redirecting. This might need an API call to work seamlessly, right now the release button redirects to the actual status page that does this. Needs more tinkering in my head.

Thanks for the feedback. :)

**Comment by sjorge** [comment]
Out of scope: split of all common actions like add firewall rule, set interface properties,... Into a rest/json api ;)

**Comment by fichtner** [comment]
That's a huge rework that needs proper sponsoring. We do what we can keeping the balance of "doesn't help to build it now on top of old code" and "it's new let's build this flexible from the start". We could end up reworking the code for a year practically get nowhere. :/

I'll keep you posted on this.

**Comment by sjorge** [comment]
I said it was out of scope ;)

**Comment by fichtner** [comment]
I tried to do this but it doesn't work very well on the dashboard as you could release your lease and end up with a disconnect by accident. I'm closing this.
