### ISSUE TITLE
Feature: Remember scrolling position when toggling action of rules

### ISSUE THREAD

**Issue by b2000699** [opnsense/core#840]
It would be great if the scrolling position of /Firewall/Rules would be remembered after toggling the action-status of a rule (e.g. changing "pass" to "pass (disabled)")

Cheers

**Comment by AdSchellevis** [comment]
The provided commits fix the scrolling position after reload for firewall_rules.php by keeping track of the position in a session cookie.

We still need to fix the other pages which contain a toggle, so I'm leaving this issue open.

**Comment by fabianfrz** [comment]
I do not think a cookie is the best place to store this value.

**Comment by AdSchellevis** [comment]
@fabianfrz any better suggestion? I agree it's suboptimal, but I don't think there are a lot of other simple options here.

**Comment by fabianfrz** [comment]
Web Storage

**Comment by AdSchellevis** [comment]
@fabianfrz your right, that's a better solution. Just changed it to use sessionStorage.

**Comment by AdSchellevis** [comment]
I've just committed a batch of "scroll" fixes for pages with toggle/move operations. In case there are pages left with a similar issue which should better be fixed in a similar way, feel free to open new issues for those pages (if possible per page/subject).
