### ISSUE TITLE
Designing new features Like a Webgui to manage more than one instance of opnsense

### ISSUE THREAD

**Issue by sensei-splinter** [opnsense/core#845]
Hello,

I am new to opnsense, but old using pfsense, and I have a idea to create a webgui interface to manage more than one opnsene. And I would like to know how to procceed? If it is possible, what to read, where to start, etc. 

Reasons:
I think that feature would help a lot of admins out there, because you can have lots of networks in a company and each one of them with its own firewall/router, and to manage it is a headache. 

Thanks in advance and sorry for any mistakes.

**Comment by AdSchellevis** [comment]
Hi sensei-splinter,

Welcome to OPNsense, this is certainly an interesting feature which from time to time also crosses our minds and feeds some discussion at our office as well.
Reality is that using our new style components, such a feature wouldn't be to hard to build, but a lot of the system is still old (although highly refactored) style code.

If you want to start your own development, I would certainly recommend looking at our documentation here: https://docs.opnsense.org/develop.html
And especially our step-by-step manual here https://docs.opnsense.org/development/examples/helloworld.html 

Happy coding,

Best regards.

Ad
