### ISSUE TITLE
Proxy sslbump no restart after changing the CA

### ISSUE THREAD

**Issue by thelinuxfr** [opnsense/core#847]
Hi,

@AdSchellevis Good job for SSL support. 

I just met a little problem with the proxy restart, after changing the CA

 Page faults with 	physical i/o: 0
Maximum Resident Size: 	301984 KB
CPU Usage: 1.650 	seconds = 1.545 user + 0.106 sys
Squid Cache (Version 	3.5.15): Terminated abnormally.
	
FATAL: Ipc::Mem::Segment::open failed 	to shm_open(/var/run/squid/ssl_session_cache.shm): (2) No such file or directory
2016/03/21 23:21:30 kid1| 	helperOpenServers: Starting 5/5 'ssl_crtd' processes

I use VirtualBox
`FreeBSD 10.2-RELEASE-p13 #0 c7e4a12(stable/16.1): Mon Mar  7 22:07:31 CET 2016     root@sensey64:/usr/obj/usr/src/sys/SMP
OPNsense 16.7.a_633-cf1a41023 [16.7.a_456-01b168c51] OpenSSL 1.0.2g  1 Mar 2016 (amd64)
UUID b4eab648-b0f9-42a3-b932-0161fa90e35a
Time Mon, 21 Mar 2016 23:33:06 +0100
User Agent Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0`

**Comment by AdSchellevis** [comment]
@thelinuxfr I saw the same issue when squid was started right after /usr/local/sbin/squid -z was run, that's why I added a small sleep in there (I don't know exactly why this happens).
Does your setup work when you stop/start squid manually?

**Comment by thelinuxfr** [comment]
@AdSchellevis stop/start squid manually works

**Comment by AdSchellevis** [comment]
@thelinuxfr can you try moving the sleep in /usr/local/opnsense/scripts/proxy/setup.sh to the bottom of the file and retest the CA change again?

**Comment by thelinuxfr** [comment]
@AdSchellevis works with a sleep 5 - but it can be a problem depending on the equipment used, the cache generation time will vary ... no ?

**Comment by thelinuxfr** [comment]
@AdSchellevis with `/usr/local/sbin/squid -z -N` and removing the sleep it not?

**Comment by thelinuxfr** [comment]
@AdSchellevis Work for me : 
```
/usr/sbin/pw groupmod proxy -m squid
/usr/local/sbin/squid -z -N                  

# wait a moment before exit, running squid -z and squid start without time between them sometimes results in
# some vague errors.
#sleep 10
```

**Comment by fichtner** [comment]
sleeps are never safe, -N is a great idea :)

**Comment by AdSchellevis** [comment]
I totally missed the -N, will push that in and remove the sleep.

**Comment by AdSchellevis** [comment]
@thelinuxfr thanks for testing!
