### ISSUE TITLE
Bug: Firewall/Schedules/Days: Date ranges are not sorted properly

### ISSUE THREAD

**Issue by b2000699** [opnsense/core#849]
Hi,

I just noticed that the date ranges are not sorted properly in SOME cases when adding schedules in Firewall/Schedules/.

I am not sure about it, but I think there seems to be a pattern when the error occurs: Everything seems fine as long no date from the first line has been selected (i.e. for March: 1-6)

Here are my test results:

March 10-11, March 18, March 1, March 4				
March 8, March 15-16, March 23-24, March 1				
March 8, March 15, March 22, March 29, March 1				
March 8, March 15, March 22, March 29, March 1				
March 9-10, March 17-18, March 25-26, March 1-2				
March 14-19, March 23-26				
March 8-10, March 23-25				
March 28-29, March 1-2				
March 7-8, March 14-15, March 21-22, March 28-29, March 1				
March 26, March 2, March 4, March 6				
March 8, March 10-11, March 16-18, March 20, March 24, March 29-30				
March 8, March 11, March 15, March 17-19, March 23, March 27, March 31, March 2				
March 8, March 11, March 15, March 17-19, March 23, March 27, March 29, March 31

Cheers

P.S.: pfSense seems to have the same bug, so I guess the bug is not living somewhere in the interface but in a lower layer of that.

**Comment by fichtner** [comment]
I know I tagged this but it's just not worth the effort.
