### ISSUE TITLE
smaller number of bugs in the ntp configuration page

### ISSUE THREAD

**Issue by sjorge** [opnsense/core#85]
A small text mistake:
http://i.imgur.com/1Ztbsld.png

Change default to 'Generic' we are not pfsense :p
http://i.imgur.com/7fQNOge.png

Defaults don't match actual defaults
http://i.imgur.com/9zuZAh6.png

**Comment by sjorge** [comment]
Update for 'Defaults don't match actual defaults'

Checkboxes and list changed based on selection of type.
All fields aside from baud rate and serial device should be set to readonly unless 'Custom' is selected.

**Comment by weust1979** [comment]
Small addition: On the NTP tab under Timeservers, the "Add another Time Server" picture/button does not load because it does not exist.

http://opnsense.local/themes/opnsense/images/icons/icon_plus.gif

**Comment by AdSchellevis** [comment]
Fixed in https://github.com/opnsense/core/commit/95ba411113a63f0bb4c597c83e686a5f67cd3ed0 except locking baud rate and serial device (the current code is not very nicely written, extending it with more javascript will probably make things worse).

**Comment by sjorge** [comment]
toggling the field to readonly is not an option?

**Comment by AdSchellevis** [comment]
There's quite some messy javascript in that file, fixing event handlers for the checkbox probably costs some extra hours and there's still a lot of other work to do. 
If you send in a pull request, I will be happy to merge it in :-)
