### ISSUE TITLE
WAN over PPPOE - default Route is not set

### ISSUE THREAD

**Issue by andreasvel** [opnsense/core#850]
Hi,
im using PPPOE for my WAN - if its the default gateway the IPv4 default is not set.
The Default IPv6 is set corect

**Comment by fichtner** [comment]
Andreas, the problem with your reports is that they miss vitual informations. Please read the following and report back:

https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

It's simply not possible to help with no information about your setup, logs, etc.

**Comment by fichtner** [comment]
I'll still need version info and additionally a dump of the following file(s), but careful with embedded credentials...

    # ls /var/etc/mpd_*.conf

**Comment by andreasvel** [comment]
i will sent you an email

**Comment by andreasvel** [comment]
any news with the infos from my email?

**Comment by fichtner** [comment]
Experimental patch at b349470, it looks like a missing Multi-WAN awareness issue.

**Comment by fichtner** [comment]
This is on the 17.1 development track for now (opnsense-devel package under 16.7)

**Comment by fichtner** [comment]
I haven't heard of further problems from @andreasvel and it's currently queued up for inclusion in 16.7.1. Thanks!

**Comment by andreasvel** [comment]
Its there again.. :-1: 
on OPNsense 16.7.3-amd64

**Comment by tadaog** [comment]
The bug is back now too in OPNsense 16.7.13-amd64
If I set:

route add -net default -interface pppoe0 

everythings works but any change in config (such as in Web Proxy removes the IPv4 default route manually added previously.

**Comment by fichtner** [comment]
It looks like "the" bug never went away completely, looking like a narrow race condition, which makes this hard to trace with the amount of additional info provided.

17.1 is almost out, featuring a new FreeBSD version. If anything we need to see how it performs there and think about what can be done?

**Comment by JoseJimeniz** [comment]
I had this today. I couldn't figure out why it could not ping, traceroute, or connect to anything on the Internet. If i forced the use of **WAN** interface it would work fine.

Finally i found the routes screen. The **default** route is set to go the physical WAN port, rather than the PPPoE virtual port:

![image](https://cloud.githubusercontent.com/assets/4681474/26136618/23e85946-3a8b-11e7-90c2-cdc9a234f22b.png)


![image](https://cloud.githubusercontent.com/assets/4681474/26136649/4947b498-3a8b-11e7-9653-b23b4f05f63b.png)

Now could i find anything in the UI to repair, reset, change, or fix it. So i had to yank the live USB stick and revert to pfSense.

**Comment by fichtner** [comment]
> I couldn't find anything in the UI to repair, reset, change, or fix it.

How about release/renew the PPP lease from the Interfaces: Overview page? Or saving/reapplying the WAN configuration? Or console option 11 or reboot... ;)

**Comment by JoseJimeniz** [comment]
- I did **disconnect** the PPPoE connection, so the WAN interface was **down**; and then connected it again
- I did re-save the WAN configuration; thinking (hoping) that it simply would fix itself

Strictly speaking i did reboot; but without the Live USB stick in. I'll try again tonight. I had to get the Internet back up before people started complaining too much.

**Comment by JoseJimeniz** [comment]
Well i tried it again; live booting off a USB stick. The wizard ran on first use because it was, by definition, a fresh install.

Same thing. The **default** route is set to go out the physical WAN port:

![image](https://cloud.githubusercontent.com/assets/4681474/26182778/5961b1d6-3b48-11e7-87a4-00af6d61c51e.png)

Unpluged the USB stick to revert to pfSense in order to wait for a fix.

**Comment by fichtner** [comment]
@JackTrapper, can you walk me through your setup sequence? You use the wizard to configure PPPoE?

**Comment by fichtner** [comment]
(in the context of this older bug, we have found some caching files that were never cleared, so that might have something to do this this no default gateway behaviour previously reported for when this was referencing 16.7)

**Comment by JackTrapper** [comment]
So i plugged in the USB stick and booted it up again. 

OPNSense 17.1.4
---------------

Welcome to OPNSense! Starting wizard. 

- <kbd>Next</kbd>

General information. 

- <kbd>Next</kbd>

Time Server Information. 

- **Timezone:** America/Toronto
- <kbd>Next</kbd>

Configure WAN Interface

- **Selected Type:** PPPoE
- **PPPoE Username:** [redacted]
- **PPPoE Password:** [redacted]
- <kbd>Next</kbd>

Configure LAN Interface

- <kbd>Next</kbd>

Set Admin Web GUI Password

- **Admin Password:** [redacted]
- **Admin Password AGAIN:** [redacted]
- <kbd>Next</kbd>

Reload Configuration

- <kbd>Reload</kbd>

Finished initial configuration!

- Congratulations! OPNsense is now configured.
- Click to continue to the dashboard.

> You are currently running in LiveCD mode. A reboot will reset the configuration. SSH remote login is disabled.

How are the routes
--------------

So now it is setup. Lets check the routes

System -> Routes -> Status

| Proto | Destination | Gateway | Flags | Use | MTU | Netif | Netif (name) |
|-------|---------------|----------|-------|------|------|-------|---------------|
| ipv4  | Default         | link#2     | U      | 5083 | 1500 | re0   |                     |
| ipv4  | *[ISP gateway IP redacted]* | link#7     | UH      | 0 | 1492| pppoe  | wan     |	

So it's using the wrong gateway as the default route. Lets try pinging.

Interfaces -> Diagnostics -> Ping

- **Host:** 8.8.8.8
- **IP Protocol:** IPv4
- **Source Address:** **`Default`**
- **Count:** 3

      PING 8.8.8.8 (8.8.8.8): 56 data bytes

       --- 8.8.8.8 ping statistics ---
       3 packets transmitted, 0 packets received, 100.0% packet loss
       ping: sendto: Host is down
       ping: sendto: Host is down
       ping: sendto: Host is down

Fails. Lets *force* use of the WAN (i.e. pppoe0) interface:

- **Host:** 8.8.8.8
- **IP Protocol:** IPv4
- **Source Address:** **WAN**
- Count: 3

      PING 8.8.8.8 (8.8.8.8) from 216.8.135.131: 56 data bytes
      64 bytes from 8.8.8.8: icmp_seq=0 ttl=51 time=24.503 ms
      64 bytes from 8.8.8.8: icmp_seq=1 ttl=51 time=24.306 ms
      64 bytes from 8.8.8.8: icmp_seq=2 ttl=51 time=28.037 ms
 
      --- 8.8.8.8 ping statistics ---
      3 packets transmitted, 3 packets received, 0.0% packet loss
      round-trip min/avg/max/stddev = 24.306/25.615/28.037/1.714 ms

So if i **force** the use of the interface, the packets will go. It just doesn't realize the default route.

Disconnect and reconnect PPPoE
------------------

Lets try forcing a disconnect and reconnect of the PPPoE interface
	
Interfaces -> Overview -> WAN Interface (wan, pppoe0)

- **Status:** up
- **PPPOE:** up
- <kbd>Disconnect</kbd>

- **Status:** down
- **PPPoE:** down
- <kbd>Connect</kbd>

- **Status:** up
- **PPPoE:** up

And check the routes again	

| Proto | Destination | Gateway | Flags | Use | MTU | Netif | Netif (name) |
|-------|---------------|----------|-------|------|------|-------|---------------|
| ipv4  | Default         | link#2     | U      | 10400 | 1500 | re0   |                     |
| ipv4  | *[ISP gateway IP redacted]* | link#7     | UH      | 0 | 1492| pppoe  | wan     |	

Still the wrong route. What about pinging again

Interface -> Diagnostics -> Ping

- **Host:** 8.8.8.8
- **IP Protocol:** IPv4
- **Source Address:** **Default**
- **Count: 3**

      PING 8.8.8.8 (8.8.8.8): 56 data bytes
      
      --- 8.8.8.8 ping statistics ---
      3 packets transmitted, 0 packets received, 100.0% packet loss
      ping: sendto: Host is down
      ping: sendto: Host is down
      ping: sendto: Host is down

Nope, still cannot ping using the default gateway. 

Disable and re-enable the WAN interface
---------------

Lets disable the interface:
 
Interfaces -> [WAN]

- **Enable:** `[x]` Enable Interface
- <kbd>Uncheck</kbd>
- <kbd>Save</kbd>
- <kbd>Apply changes</kbd>

And re-enable it:

- **Enable:** `[ ]` Enable Interface
- <kbd>Check</kbd>
- <kbd>Save</kbd>
- <kbd>Apply changes</kbd>

And check the routes again:

System -> Routes -> Status

| Proto | Destination | Gateway | Flags | Use | MTU | Netif | Netif (name) |
|-------|---------------|----------|-------|------|------|-------|---------------|
| ipv4  | Default         | link#2     | U      | 12152 | 1500 | re0   |                     |
| ipv4  | *[ISP gateway IP redacted]* | link#7     | UH      | 0 | 1492| pppoe  | wan     |	

Still the wrong route. And ping still fails:

Interfaces -> Diagnostics -> Ping

- **Host:** 8.8.8.8
- **IP Protocol:** IPv4
- **Source Address:** **Default**
- **Count:** 3

      PING 8.8.8.8 (8.8.8.8): 56 data bytes
      
      --- 8.8.8.8 ping statistics ---
      3 packets transmitted, 0 packets received, 100.0% packet loss
      ping: sendto: Host is down
      ping: sendto: Host is down
      ping: sendto: Host is down
 
And again if i force the use of PPPoE interface directly, it works:

- **Host:** 8.8.8.8
- **IP Protocol:** IPv4
- **Source Address:** WAN
- **Count:** 3

      PING 8.8.8.8 (8.8.8.8) from 216.8.135.131: 56 data bytes
      64 bytes from 8.8.8.8: icmp_seq=0 ttl=51 time=24.503 ms
      64 bytes from 8.8.8.8: icmp_seq=1 ttl=51 time=24.306 ms
      64 bytes from 8.8.8.8: icmp_seq=2 ttl=51 time=28.037 ms
      
      --- 8.8.8.8 ping statistics ---
      3 packets transmitted, 3 packets received, 0.0% packet loss
      round-trip min/avg/max/stddev = 24.306/25.615/28.037/1.714 ms
      
Now to go back downstairs, pull the USB stick, let pfSense boot up, and put my nicely formatted, long, verbose, findings into Github markdown. Should be posted in about an hour. 

- 7:43pm EDT

- Current time: 8:03pm EDT *(quicker than i thought)*

**Comment by fichtner** [comment]
Lots of progress here in the backgrounds, eventually cleaning up the IP renewal facilities for 17.7. 17.7-RC1 is out soon, please retest then.

**Comment by JackTrapper** [comment]
So i finally tried 17.7 and it still happens: Even though the PPPoE interface is up, the default interface is out the physical WAN port - with traffic going nowhere.


**System -> Routes -> Status**

| Proto | Destination | Gateway | Flags | Use | MTU | Netif | Netif (name) | Expire |
|-------|-------------|---------|-------|-----|-----|-------|--------------|--------|
| ipv4 |default | link#2 | U | 81208 | 1500 | re0 |   |  
|ipv4 | 98.143.64.200 | link#7 | UHS | 0 | 16384 | lo0 |   |  |
|ipv4 | 216.8.136.169 | link#7 | UH | 0 | 1492 | pppoe0 | wan |  |
**System -> Gateways -> Status

| Name      | Gateway       | Monitor | RTT    | Loss  | Status | Description                 |
|-----------|---------------|---------|--------|-------|--------|-----------------------------|
| WAN_PPPOE | 216.8.136.169 | none    | 0.0 ms | 0.0 % | Online | Interface WAN_PPPOE Gateway |

**Comment by JackTrapper** [comment]
So what's needed to help get this fixed?

By definition i'm starting a fresh install - Live USB stick.

Somebody on the planet must understand why the operating system refuses to use the correct default route. Is there a logfile that opnSense needs to log to?
