### ISSUE TITLE
configd not starting up correctly

### ISSUE THREAD

**Issue by L1ghtn1ng** [opnsense/core#853]
so after upgrading to 16.1.8 today it needed a reboot. So I let it do its automatic reboot that it says in the web UI. I decided to halt the system when logged in via SSH and option 6 if I recall correctly. So I went downstairs and still noticed it was on even after at least 5 minutes had past. I disconnected the powersupply, upon plugging it in and it booting up and logging in and checking for updates again I got an error saying response unknown and could not SSH in to the firewall. It turns out that configd and sshd did not startup on boot. so I did this and this is the output I got.

```
root@OPNsense:~ # service configd status
configd is running as pid 57577.
root@OPNsense:~ # service configd enable
/usr/local/etc/rc.d/configd: unknown directive 'enable'.
Usage: /usr/local/etc/rc.d/configd [fast|force|one|quiet](start|stop|restart|rcvar|enabled|status|poll)
root@OPNsense:~ # service configd enabled
/usr/local/etc/rc.d/configd: WARNING: $ is not set properly - see rc.conf(5).
```

I have had this issue before but not realised why it was happening so I would normally just do a restore to factory defaults which fixes it till the next time I have to turn the firewall off.

**Comment by AdSchellevis** [comment]
@L1ghtn1ng it looks like configd is enabled, if you want to restart you need start|stop|restart in stead of enable as an argument.
Can you start the following sequence (to restart both configd and ssh):

```
service configd restart
configctl sshd restart
```

**Comment by fichtner** [comment]
Configd starts up correctly, you can see the pid (it's "service configd restart"), but it can clash with sshd startup as we found out just a couple of days ago. We're still narrowing the problem down, but it's a known issue. See e.g.: https://forum.opnsense.org/index.php?topic=2432

**Comment by L1ghtn1ng** [comment]
Configd started as I started it via the web ui manually, it did not start on its own from boot after the firewall was completely powered down

**Comment by fichtner** [comment]
That's new, ok, thanks for clarifying. Is this a relatively new server with amd64 or older embedded hardware with i386?

**Comment by L1ghtn1ng** [comment]
I got this last week https://www.applianceshop.eu/security-appliances/security-appliances-desktop-and-wallmountable/pfsense-based-desktop/opnsense-a10-quad-core-ssd-desktop.html

**Comment by AdSchellevis** [comment]
It must be a race condition in the bootup sequence (syslog not active, configd trying to connect to it). I will make sure configd starts when syslog has issues to prevent this from happening again. 
Expect a fix in 16.1.9

**Comment by L1ghtn1ng** [comment]
Awesome that you fixed it. When will the fix get pushed out?

**Comment by AdSchellevis** [comment]
@L1ghtn1ng your issue helped us narrowing things down further, thanks for that. We plan to include this one in the release next week.

**Comment by L1ghtn1ng** [comment]
Awesome glad I could help. I thought that would be the case that you would release it next week. I hope it can be as soon as possible after being tested extensively. Would like to get this fix in before I have to power it down so I can install the UPS in

**Comment by AdSchellevis** [comment]
@L1ghtn1ng in case we won't do a release next week, you can easily fix your machine by executing the following command:

```
curl -o /usr/local/opnsense/service/configd.py  https://raw.githubusercontent.com/opnsense/core/master/src/opnsense/service/configd.py
```

**Comment by L1ghtn1ng** [comment]
Won't it conflict when you do, do a release?

**Comment by fichtner** [comment]
Only when the change isn't shipped with the next release, but in this case it'll be in 16.1.9 for sure. Sneak preview. :)

**Comment by L1ghtn1ng** [comment]
Okay cool I think I can hold off for now though as I can wait
