### ISSUE TITLE
Description issue with Interfaces --> LAN --> Block private networks

### ISSUE THREAD

**Issue by azdps** [opnsense/core#854]
The description for Block private networks in the webui for Interfaces --> LAN is wrong. It's an obvious wording error and should be changed..

**Comment by fichtner** [comment]
Hi Shane,

Does this refer to the fact that it explains things about WAN that should not be used in a LAN context? If so I can tweak the wording a bit, otherwise I'm not yet sure what you mean. In any case, please clarify. :)


Cheers,
Franco

**Comment by azdps** [comment]
Exactly :). Also it says "You should generally leave this option turned on" which conflicts with OPNsense's default setting of off for this. Am I wrong by thinking this?

**Comment by fichtner** [comment]
Tricky to get the wording right... what do you think about the change?

**Comment by azdps** [comment]
Looks good to me. Keep up the good work :).
