### ISSUE TITLE
Bug in pfSense: Brainstructure of community member heavily damaged!

### ISSUE THREAD

**Issue by b2000699** [opnsense/core#856]
Hi everyone,

look what I just stumbled upon: https://twitter.com/htilonom/status/711215161118494720

:-D

Today I stumbled upon what is going on here https://twitter.com/htilonom and here http://www.opnsense.com/ and I must say: What sicko stuff is going on over there at pfSense?

I left pfSense long ago because of the arrogant attitude - and even aggressiveness -  of some of their members in their mailing list, which I disliked, so I walked away.

But this mud-slinging propaganda hate campaigns against your project, which they pull off with a great deal of investment in time and money... leaves me speechless.. What childish morons live over there at pfSense!? Amazing!! :-)

**Comment by fichtner** [comment]
This has been going on for the better part of a year and, well, it likely WONTFIX :/

**Comment by b2000699** [comment]
:-D
