### ISSUE TITLE
Firewall: Editing an associated NAT rule does not warn the user that changes are not allowed

### ISSUE THREAD

**Issue by thelinuxfr** [opnsense/core#858]
referenced problem and corrected on [pfsense](https://redmine.pfsense.org/issues/5790), also present in OPNsense

> Editing an associated NAT rule does not warn the user that changes are not allowed. The end result is OK -- the rule should not allow changes -- but the user is given no indication that the edit (correctly) was denied or failed.
> 
> 1. Create a NAT port forward with an associated firewall rule (the default)
> 2. Edit the resulting firewall rule, make a change (to anything other than descr), click save
> 3. The change is not saved but it appears to have succeeded, Apply is offered, etc.

The following input errors were detected:

-     The field Protocol is required.
-     The field Source is required.
-     The field Destination is required.
-     The field Source bit count is required.
-     The field Destination bit count is required.
-     is not a valid source IP address or alias.
-     A valid source bit count must be specified.
-     is not a valid destination IP address or alias.
-     A valid destination bit count must be specified.

**Comment by azdps** [comment]
I'm using version 16.1.8 and I can confirm this issue exists. Following the same procedure above and clicking save without making any changes to an associated NAT rule yields the same results.

**Comment by AdSchellevis** [comment]
Strange, it should not show an edit button for the associated rules. We had a discussion last year about those, which let to first hide the rule and later we choose to only hide the edit button for those.
 
https://forum.opnsense.org/index.php?topic=2097.msg6879#msg6879
https://github.com/opnsense/core/commit/e1dd1839931ca804970a2f9b9b4c1237160adcca

Am I missing something here?

**Comment by azdps** [comment]
Yes I just spotted the culprit. From a NAT port forward rule click on edit to edit the NAT rule. From there scroll to the bottom and select "View the filter rule". This will take you to the rule as well as allow you to select save at the bottom. Clicking save will yield the results posted above.

**Comment by AdSchellevis** [comment]
that explains, I think we should remove this link then to make it consistent. Thanks for testing this.

**Comment by azdps** [comment]
No problem. Glad I could help.

**Comment by thelinuxfr** [comment]
@AdSchellevis It might have been better to leave the option and correct errors when validating the rule. For now, the rule automatically generated can be changed (eg the category, or the gateway ...)

**Comment by azdps** [comment]
thelinuxfr how do you access the automatically generated rule? Unless there is another way to access the generated rule the change has prevented access to even view the rule. Changes won't be possible if you can't view it (edit it).

**Comment by thelinuxfr** [comment]
@azdps sorry my mistake ;)

**Comment by azdps** [comment]
thelinuxfr no problem. I'm glad you reported the issue in the first place. Just want OPNsense to be rock solid and bug free just like I'm sure you do =).
