### ISSUE TITLE
Add interface column in the list of DHCP IPv4/IPv6 clients

### ISSUE THREAD

**Issue by thelinuxfr** [opnsense/core#860]
Add interface column in the list of DHCP IPv4/IPv6 clients

**Comment by AdSchellevis** [comment]
Hi Frédéric, can you provide a bit more information for this request (which page to look at for example)? Thanks in advance. Regards, Ad

**Comment by thelinuxfr** [comment]
@AdSchellevis hi here's a nice mockup :p 

![issue-860](https://cloud.githubusercontent.com/assets/43656/14062144/d5129d88-f394-11e5-8eef-05559943741f.png)

**Comment by AdSchellevis** [comment]
@thelinuxfr thank you for clarifying this.
