### ISSUE TITLE
Feature: How to correctly enable wireless interface?

### ISSUE THREAD

**Issue by ylli2000** [opnsense/core#863]
My system can actually detect "ath0_wlan0" interface, but when I try to enable it via "Interface->wireless->devices" it throws this message:

- console - "ath0: only 1 sta vap supported" 
- web UI - "Error creating interface with mode infrastructure (BSS) The ath0 interface may not support creating more clones with the selected mode"

I cannot understand why it knows the wireless interface but doesn't allow me to use it. and, I am not trying to clone, I am trying to use the one-and-only WLAN device.

**Comment by fichtner** [comment]
How is ath0_wlan0 created? It may not be a wireless clone at all. Ifconfig dump would be helpful too.

**Comment by ylli2000** [comment]
Thanks for trying to help me fichtner. I am new to PF & OPNSense and I am trying to pick up. I manage to skip the error now. Here is how I did it:

1. from OPN server, I assigned interface to ath0 for OPT1. then I have "OPT1 (ath0_wlan0) ->" with no IP address yet.
2. now I go to web UI I can assign interfaces-> wireless -> device ->Add ath0. Important thing for me is NOT to go "Interfaces->OPT1->Enable" first, or I will not be able to Add ath0 as wireless device.

Now that is done, could you please tell me, where I can go and setup the wireless related configurations, such as SSID, WPA/PSK keys all that? Please forgive my ignorance,I can't seem to find it anywhere on the Web UI or FreeBSD command menu. Being a newbie to the system, not sure what to do next. Please help.

**Comment by fichtner** [comment]
I think you ran into the problem that I fixed earlier today thanks to your reminder. :)

When you have ath0_wlan1 assigned, you go to "OPT1" in the menu and enable it, hit save. On the bottom the wireless options will appear.

**Comment by fichtner** [comment]
Is there anything still to do here or can we close this?
