### ISSUE TITLE
Feature Request - support for aliases in traffic shaper rules

### ISSUE THREAD

**Issue by k666mac** [opnsense/core#865]
Add ability to use aliases in the traffic shaper rules to allow for easier management of rules when needing to set priority by groups of hosts rather than protocol.

**Comment by tapsystem** [comment]
It will be a great idea ... ip by ip rules make my keyboard burning out ! Tks

**Comment by AdSchellevis** [comment]
@tapsystem do you know you can add multiple addresses / ranges at once? https://github.com/opnsense/core/issues/1226

**Comment by AdSchellevis** [comment]
timeout due to inactivity
