### ISSUE TITLE
Need guidance to wireless adapter configuration 

### ISSUE THREAD

**Issue by ylli2000** [opnsense/core#867]
Please take a look at my configurations and guide me if I have done anything wrong? I assume the hardware is working fine, my OPNSense box can see surrounding WIFI networks from "Interfaces->Wireless->Status", and my laptop can detect the surrounding WIFI networks, but my laptop can't see my OPNSense box. Here are my settings.

**OPNSense UI Wireless Settings ---------------------------------------------------**
**(left blank or default where not mentioned)**
Enable Interface yes
Static IPv4
Speed and duplex Default (no preference, typically autoselect)
IPv4 address 20.1.1.1
IPv4 Upstream Gateway None

Standard 802.11g
Protection mode off
Transmit power 18
Antenna Settings Default Auto Auto
Distance Setting 100
Regulatory domain ROW
Country Australia -- (AU ROW)
Location Indoor

Mode Infrastructure (BSS)
SSID OPNTest
Enable WME yes
Enable WPA
WPA pre-shared key *********
Authentication Open System Authentication
WPA Pairwise AES Recommended
Key Rotation 60
Master Key Regen 3600

APPLY CHANGES

**Hardware Factory Specs----------------------------------------------------------------**
TP-Link TL-WN651G 108Mbps Super G Wireless PCI Adapter
http://www.mondoplast.net/datasheets/TL-WN651G.html
Protocol and Standards: IEEE 802.11g; IEEE 802.11b; CSMA/CA with ACK
Interface: 32-bit PCI 2.2
Frequency: 2.4~2.4835GHz
Radio Data Rate: 108/54/48/36/24/18/12/9/6/11/5.5/3/2/1Mbps (Auto Rate Sensing)
Spread Spectrum: DSSS
Modulation:1M DBPSK; 2M DQPSK; 5.5M, 11M CCK; 6M, 9M, 12M, 18M, 24M, 36M, 48M, 54M, 108M OFDM;
Transmission Distance:Indoor up to 100m, outdoor up to 300m
Transmit Power: 18dBm(Typical)
Data Security: WPA; 64/128/152 BIT WEP; TKIP/AES 
Power Consumption: Typically 685mA in full Transmit (TX), 515mA in full Receive (RX) 

**Side Note:** 
Am I supposed to raise this kind of question here in Github Issues? Or do we post them in other channels, such as Stackoverflow? Where is the best place to ask questions? Thank you :)

**Comment by fichtner** [comment]
Is the SSID public or did you check the hide option?

The forum would be better for support issues as other people will help you there as well. We use GitHub for code improvements mostly.

**Comment by ylli2000** [comment]
Thanks fichtner. I will ask future questions in the forum. 

"Hide SSID" option is unchecked. As I want it to broadcast. So, other settings look okay to you?

Thanks.

**Comment by fichtner** [comment]
Morning, can you try another standard like 802.11b?

**Comment by fichtner** [comment]
This moved to the forum: https://forum.opnsense.org/index.php?topic=2695
