### ISSUE TITLE
[framework] support n-m relation in ModelRelationField

### ISSUE THREAD

**Issue by fraenki** [opnsense/core#868]
Currently it is limited to 1-n relation, but I'd require n-m relation. :)
As discussed with @AdSchellevis on IRC...

**Comment by AdSchellevis** [comment]
details https://github.com/opnsense/core/pull/869#issuecomment-203821570

**Comment by fraenki** [comment]
@AdSchellevis I was wrong in https://github.com/opnsense/core/pull/869#issuecomment-203821570. My test failed because I forgot to add the tag `Multiple>Y</Multiple>`. D'oh! I did a new test and now it's working as expected.

**Comment by AdSchellevis** [comment]
@fraenki thanks for testing again! this indeed explains all :)
