### ISSUE TITLE
IDS: SURICATA UDPv4 invalid checksum

### ISSUE THREAD

**Issue by thelinuxfr** [opnsense/core#871]
Hi,

I followed the howto on documentation and is off all Hardware Offloading Under and restart the firewall. But I get an error in alerts suricata : SURICATA UDPv4 invalid checksum

I did a test by following the FAQ and Suricata is disabled and there stream.checksum_valdation his work, I have no error and the flow is blocked when I want ...

So es it a validation issue in the general settings or a problem in Suricata?

Thx

**Comment by AdSchellevis** [comment]
@thelinuxfr The default install for Suricata contains a ruleset "decoder-events.rules" if you remove that file, your alerts will be gone. We should probably make this one selectable, now you can only remove them manually.

**Comment by AdSchellevis** [comment]
@thelinuxfr you should be able to either disable the rule (sid 2200075) or the ruleset (decoder-events.rules). This rule is quite trigger friendly from time to time (bad checksums).

(at first I though it was missing in our ruleset and there for more difficult to remove, but it looks like its easy to disable)

**Comment by thelinuxfr** [comment]
@AdSchellevis Well done, indeed my problem was there ;)

**Comment by tuwid** [comment]
Can we get to the reason why is this happening in the first place instead of just disabling rules ?

**Comment by fichtner** [comment]
It depends on individual setup hardware, VM technology used, network drivers, IDS mode, hardware offloading feature state, etc. An assessment in an individual case costs time.

**Comment by tuwid** [comment]
@tifredfr I've actually bought the appliance

**Comment by fichtner** [comment]
I'm sorry, I don't know what you mean by that.

**Comment by L1ghtn1ng** [comment]
He probably means the A10 which is what I have and I get that problem as well
________________________________
