### ISSUE TITLE
[framework] ArrayField: relax the child node validation

### ISSUE THREAD

**Issue by fraenki** [opnsense/core#879]
The `ArrayField` FieldType validates child nodes very strictly (see https://github.com/opnsense/core/blob/708a1d017f568f3e7bcbba3f696be9ae89397d1f/src/opnsense/mvc/app/models/OPNsense/Base/FieldTypes/ArrayField.php#L80-L83). As discussed with @AdSchellevis this validation should be relaxed to support sub-tags in models.

Example:

```
        <myitems>
            <myitem type="ArrayField">
                <name type="TextField">
                    <Required>Y</Required>
                </name>
                <subitem>
                    <enabled type="BooleanField">
                        <default>0</default>
                        <Required>Y</Required>
                    </enabled>
                </subitem>
                <subitem2>
                    <enforce type="BooleanField">
                        <default>1</default>
                        <Required>N</Required>
                    </enforce>
                </subitem2>
            </myitem>
        </myitems>
```

This would be very useful for complex configurations with A LOT options and parameters.

**Comment by fraenki** [comment]
Hm. The BasField would need adjustements too (https://github.com/opnsense/core/blob/708a1d017f568f3e7bcbba3f696be9ae89397d1f/src/opnsense/mvc/app/models/OPNsense/Base/FieldTypes/BaseField.php#L392-L396).

**Comment by AdSchellevis** [comment]
@fraenki why?

**Comment by fraenki** [comment]
As it turns out this isn't that easy, it'd require more structural changes. This will be possible once #870 is done.
