### ISSUE TITLE
Wishlist: Collection of feature ideas & proposals

### ISSUE THREAD

**Issue by klausneil** [opnsense/core#882]
Greetings, not if this is the way but I wanted to express my humble but collaborative idea and my whishlist is basicly for the proxy module:

* Create group by ip or users for apply filter rules of the proxy by each one.
* Create time of access by groups by  the proxy.
* Cutomize the page of deny proxy
* The log displays information such as time of access, domain, url and / or MIME type.
* A button to clear the cache proxy.

Thanks for your consideration and time.

**Comment by AdSchellevis** [comment]
@klausneil It's a perfect place for feature requests, but maybe it's a good idea to change the title to better explain the issue and split it into 3 or 4 separate issues for easier handling (a collection of issues is very hard to close :) ).

**Comment by fichtner** [comment]
Yes, please split this up. We already have a ticket for the proxy page customisation. 😊

**Comment by AdSchellevis** [comment]
timeout, no feedback.
