### ISSUE TITLE
IPS: add easy setup test ruleset

### ISSUE THREAD

**Issue by L1ghtn1ng** [opnsense/core#884]
It could be me just doing something wrong. I did follow the guide to block facebook from https://docs.opnsense.org/manual/how-tos/ips-sslfingerprint.html

I then cleared the cache and everything in firefox using CTRL+SHIFT+DEL and then when to facebook. It did not generate an alert.

I am doing this to test to make sure the rules that I have enabled that come with OPNsense are working correctly.

**Comment by AdSchellevis** [comment]
@L1ghtn1ng I've seen the same behaviour before when using firefox, it looks like flushing the cache doesn't always forget the state of the ssl session.
I just tried the same for our website (www.deciso.com) using the corresponding fingerprint (AA:C4:99:2B:A0:23:E8:3D:61:DB:E4:21:C1:07:4E:FB:F3:1A:98:C1) same issue when using firefox, internet explorer did trigger an alert, firefox didn't (only after a full reset, https://support.mozilla.org/en-US/kb/refresh-firefox-reset-add-ons-and-settings).

**Comment by L1ghtn1ng** [comment]
Does chrome/chromium work correctly?

**Comment by L1ghtn1ng** [comment]
I am also trying to work out as well if the rules that are in  Opnsense by default without me creating a rule are working correctly as I have not seen any blocked alerts at all and I would of thought I would have

**Comment by AdSchellevis** [comment]
@L1ghtn1ng Maybe we should add an easy to test ruleset to our set, I've heard other people as well having issues with testing their setup, most rules in there are meant for specific (real) threads.
Can we change the issue to something like "IPS: add easy setup test ruleset"?

**Comment by L1ghtn1ng** [comment]
Yeah go for it

**Comment by AdSchellevis** [comment]
added a simple test using the eicar test virus (http://www.eicar.org/download/eicar.com.txt)
just apply the test ruleset and try to download the virus, it should block and log the event.

Maybe we should add additional tests at some point, but I don't have better ideas at the moment for them.

**Comment by L1ghtn1ng** [comment]
How about a simple website that could be setup to also test SSL
blocking as well?
