### ISSUE TITLE
getty errors

### ISSUE THREAD

**Issue by L1ghtn1ng** [opnsense/core#890]
getty[43849]: open /dev/ttyv6: No such file or directory
 	getty[43849]: open /dev/ttyv6: No such file or directory
 	getty[43404]: open /dev/ttyv3: No such file or directory
 	getty[43404]: open /dev/ttyv3: No such file or directory
 	getty[43577]: open /dev/ttyv4: No such file or directory
 	getty[43577]: open /dev/ttyv4: No such file or directory
 	getty[43354]: open /dev/ttyv2: No such file or directory
 	getty[43354]: open /dev/ttyv2: No such file or directory
 	getty[44164]: open /dev/ttyv7: No such file or directory
 	getty[44164]: open /dev/ttyv7: No such file or directory
 	getty[43670]: open /dev/ttyv5: No such file or directory
 	getty[43670]: open /dev/ttyv5: No such file or directory
 	getty[43178]: open /dev/ttyv0: No such file or directory
 	getty[43178]: open /dev/ttyv0: No such file or directory
 	getty[43199]: open /dev/ttyv1: No such file or directory
 	getty[43199]: open /dev/ttyv1: No such file or directory

**Comment by AdSchellevis** [comment]
@L1ghtn1ng are you using a serial version? then this is normal, the defaults ttys (/etc/ttys) contain these.
I don't expect we will change this, its harmless.

**Comment by L1ghtn1ng** [comment]
@AdSchellevis im using what ever version comes on this. I would assume it is that version as that is the connector it has on it https://www.applianceshop.eu/security-appliances/security-appliances-desktop-and-wallmountable/pfsense-based-desktop/opnsense-a10-quad-core-ssd-desktop.html

**Comment by AdSchellevis** [comment]
@L1ghtn1ng yes, this is a serial version without video output. Because this won't cause any issues, I would rather close this issue. what do you think?

**Comment by L1ghtn1ng** [comment]
I would say if it is serial version, then don't have those errors get reported. Only report those errors if it is the video version. Reason for this is to basically remove errors from the log that do not apply to the version. This is so we do not get people like me thinking this is a problem when it's not

**Comment by fichtner** [comment]
The serial image (as well as nano) is a hybrid serial/vga image. As such, we cannot remove those "errors" as they would break other people's use cases. Closing.

**Comment by L1ghtn1ng** [comment]
Fair enough

**Comment by fichtner** [comment]
The rules for this changed a bit in 16.7, even more in 17.1: the code will then switch off virtual terminals if only serial is selected (which will be true for serial images): https://github.com/opnsense/core/commit/d28b79a90d61216bac4ae364d3f550ac26419317
