### ISSUE TITLE
Escaping of HTML special characters in input fields

### ISSUE THREAD

**Issue by fraenki** [opnsense/core#898]
Currently HTML special characters in input fields are encoded on **every** edit. This leads to scrambled data. See below. (As discussed with @fichtner and @AdSchellevis on IRC.)

Adding an item with HTML special characters (**watch the "content" field**):
![bug1](https://cloud.githubusercontent.com/assets/909706/14609652/1c07bafe-058b-11e6-9ba2-6d8ef1396562.png)
After "Save changes", the JSON output from the API get() method looks like this:
`{"uuid":"76d249a3-c368-4100-ac89-66dbce2e151f","enabled":"1","name":"test_bug","description":"test HTML special characters in input fields","content":"this is\n&lt;html&gt;\nbla bla"}`

This is the _expected result_, because the HTML special characters must be encoded before storing the data in `config.xml`.

But on the second edit, the data is **encoded again** by the Web GUI:
![bug2](https://cloud.githubusercontent.com/assets/909706/14609758/7a4c7668-058b-11e6-8067-7d655cfecae0.png)
After "Save changes", the JSON output from the API get() method is broken:
`{"uuid":"76d249a3-c368-4100-ac89-66dbce2e151f","enabled":"1","name":"test_bug","description":"test HTML special characters in input fields","content":"this is\n&amp;lt;html&amp;gt;\nbla bla"}`

This gets worse with every edit:
![bug3](https://cloud.githubusercontent.com/assets/909706/14609793/9e84d854-058b-11e6-908c-e76c5f260fd2.png)
After "Save changes", the JSON output from the API get() method looks like this:
`{"uuid":"76d249a3-c368-4100-ac89-66dbce2e151f","enabled":"1","name":"test_bug","description":"test HTML special characters in input fields","content":"this is\n&amp;amp;lt;html&amp;amp;gt;\nbla bla"}`

In my opinion there are two problems:
* The Web GUI should **not encode** the data which was _received from the API_. It can be expected that this data was properly encoded while saving it to config.xml.
* All Input Fields should show the **decoded** data, thus replacing all HTML entities (i.e. `&gt;`) with the HTML special characters (i.e. `>`) for user-convenience. (Otherwise input fields with such data are a pain and almost impossible to maintain from a user-perspective.)

Side note: I was using the new HAProxy plugin to demonstrate this, but this issue applies to basically _all_ input fields.

**Comment by fraenki** [comment]
Yes, I'm aware of the `disableOutputCleansing()`method, but this looks more like a general issue to me. I think it is not desirable to have this duplicate encoding of HTML special characters as it literally destroys the data in the input field.

**Comment by fraenki** [comment]
@fichtner tested another input field to demonstrate the faulty behaviour also affects existing applications:

<img width="577" alt="9mdhouq - imgur" src="https://cloud.githubusercontent.com/assets/909706/14610506/80d673d2-058e-11e6-9212-f35ab15e3357.png">

**Comment by AdSchellevis** [comment]
@fraenki I was a bit too busy yesterday, but it should indeed be possible to push html content back to the client as long as it is guaranteed not executed. 
My last commit should fix it, just download this file:
```
curl -o /usr/local/opnsense/www/js/opnsense.js https://raw.githubusercontent.com/opnsense/core/master/src/opnsense/www/js/opnsense.js
```

On a side node, I think we should remove disableOutputCleansing from the base class, it looked like a good idea at the time, but it isn't :)

**Comment by fraenki** [comment]
@AdSchellevis Great job, thank you! :+1:
