### ISSUE TITLE
CaptivePortal: Option to set voucher codes manually invalid

### ISSUE THREAD

**Issue by DokuKaefer** [opnsense/core#899]
It's possible to add an option like in the old CP to set vouchercodes manually invalid?

**Comment by DokuKaefer** [comment]
hey @AdSchellevis nice! But can you add this option also to the "Captive Portal Sessions" Overview page? 
So it's easier to cancel an active session.

**Comment by AdSchellevis** [comment]
@DokuKaefer sorry, can't do that. glueing sessions back to the authenticator they belong to and fixing the UI involves quite some work which I don't have the time for.
