### ISSUE TITLE
Chrome Firewall Rules Edit Lockup

### ISSUE THREAD

**Issue by fichtner** [opnsense/core#90]
Another strange issue is trying to edit a firewall rule with Chrome (using it on Windows 7 oder 8.1).
    Clicking on the pencil works only once. After that, clicking on any pencil in any rule makes the rule
    flicker shortly and then it says I should press the update button because my ruleset has changed.
    IE and Firefox seem to work fine.

via: https://forum.opnsense.org/index.php?topic=78.msg453#msg453

**Comment by jschellevis** [comment]
Tested it with Chrome on Mac OSX and Windows, works just fine on version 15.1.7.

The only thing I can think of is that the rule was moved by dragging the button, it still works in that case but it behaves different. If that is the case you'll also see and Undo button.

Anyway, I will close this issue as it cannot be reproduced and there are no styling or obvious coding errors on this page.
