### ISSUE TITLE
system: change halt to power off

### ISSUE THREAD

**Issue by L1ghtn1ng** [opnsense/core#907]
Under the system -> firmware section change halt to shutdown the system completely. This will run the poweroff command

**Comment by fichtner** [comment]
It's been like this forever, but I agree. :)

**Comment by L1ghtn1ng** [comment]
You have addressed the webui issues but looking at the RC.halt file it will still only halt the system. This is not desired. If I have gotten this wrong please correct me, but looking at this www.freebsd.org/cgi/man.cgi?query=shutdown&sektion=8&manpath=freebsd-release-ports it says we need to remove the "o" parameter

**Comment by fichtner** [comment]
While the file is named "rc.halt", the system has always powered down for as long as I can remember. The command invoke is:

    # /sbin/shutdown -op now

Which skips killing init (which would run FreeBSD's rc shutdown which interferes with our rc system), but then powers down correctly.

**Comment by L1ghtn1ng** [comment]
Interesting as I have not seen it shutdown correctly I.e completely turned off, even when I have asked it to. The only way I got it to do what I wanted was to SSH in to it and run poweroff

**Comment by fichtner** [comment]
VM, Hardware, special configs? Can you run the above command and provide the output of the console? It could also be SD/CF card writes/backup that stalls.

**Comment by L1ghtn1ng** [comment]
It is hardware, VM it works fine but will double check that. I have in my other issues that I have reported is what I am using

**Comment by L1ghtn1ng** [comment]
@fichtner this is what I have for hardware https://www.applianceshop.eu/security-appliances/security-appliances-desktop-and-wallmountable/pfsense-based-desktop/opnsense-a10-quad-core-ssd-desktop.html

**Comment by L1ghtn1ng** [comment]
running the above command works from the ssh into it, but if you try and do it from the web interface it does not work

**Comment by L1ghtn1ng** [comment]
as I get this output to the terminal, and I went and checked it and it was completley turned off. So the issue is that the webui is not talking correctley to the backend when you select that option.

```
                 
*** FINAL System shutdown message from root@OPNsense.lightning.local ***     

System going down IMMEDIATELY                                                  

                                                                               

System shutdown time has arrived
Connection to 10.0.0.1 closed by remote host.
Connection to 10.0.0.1 closed
```

**Comment by fichtner** [comment]
I've seen the shutdown not go through on occasion, but I can't say for sure what's going on. E.g. reboot always seems to go through with the A10 I have. I can play a little with it, but I suspect this may come as a side effect of having heavy services running that are slow to stop, e.g. squid or suricata. Do you have those services running?

**Comment by L1ghtn1ng** [comment]
suricata I do

**Comment by L1ghtn1ng** [comment]
Any update on this?##SELECTION_END##
