### ISSUE TITLE
configd: dashboard hangs with ipsec status widget when configd is down

### ISSUE THREAD

**Issue by fichtner** [opnsense/core#913]
I have widgets for services and ipsec. I wanted to stop/start configd, but the stop command hangs. Configd stop works fine on the services diagnostics page.

Can we lower the "configd not there" timeout?

**Comment by AdSchellevis** [comment]
@fichtner Maybe we should lower the default in https://github.com/opnsense/core/blob/73f353c9c27e68de57c82593ce633bc3461e39bc/src/opnsense/mvc/app/library/OPNsense/Core/Backend.php#L76 to something like 20 seconds and pass the parameter with a higher value when needed. Most calls won't take that long or run in the background.

**Comment by fichtner** [comment]
How about a response timeout (120 secs as defined) and a separate connect timeout (5-10 secs)?

Is connect instant or will it have to wait for the last configd command to finish?

**Comment by AdSchellevis** [comment]
I guess your right, adding another parameter for connect timeout would be better. If we can avoid configd calls during boot it might even be better to set it to a fixed default.

**Comment by fichtner** [comment]
fixed sounds good to me

**Comment by fichtner** [comment]
works as expected, thanks!
