### ISSUE TITLE
php database modules: pdo, pdo_sqlite, sqlite3

### ISSUE THREAD

**Issue by fichtner** [opnsense/core#915]
Which do we actually need? E.g. "pdo" is supposed to be an automatic dependency.

**Comment by AdSchellevis** [comment]
@fichtner SQLite3 is by my knowledge the only module we use and should be installed by default (http://php.net/manual/en/sqlite3.installation.php), it is very easy to test just build without and try the vouchers.

**Comment by fichtner** [comment]
Thanks! Does 1d0ae14 look sane?

**Comment by AdSchellevis** [comment]
yes:) I see you also removed the unused mysql config directive, good.

**Comment by fichtner** [comment]
indeed, got sucked into the vortex because of "pdo" ;)
