### ISSUE TITLE
Please add mtr package!!

### ISSUE THREAD

**Issue by aes512** [opnsense/core#919]
This tool is absolutely needed, it is the Swiss army knife of all things trace route..

https://www.bitwizard.nl/mtr/

**Comment by AdSchellevis** [comment]
@aes512 it will be in the next release (https://github.com/opnsense/tools/commit/87ff2f30a328fae444a79b3b87192fcbf035fa63), if you can't wait for it and are using amd64 you can install using:
```
pkg add -f https://pkg.opnsense.org/snapshots/mtr-0.86.txz
```
