### ISSUE TITLE
 dhcp: lease file read/write when too big

### ISSUE THREAD

**Issue by fichtner** [opnsense/core#922]
```
Fatal error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 22 bytes) in /usr/local/www/services_dhcp.php on line 62
```

**Comment by AdSchellevis** [comment]
for reference, it needs something like https://github.com/opnsense/core/blob/master/src/www/status_dhcp_leases.php#L252-L284 in stead if file_get_contents()

**Comment by fichtner** [comment]
Respective report logs, this was on 16.1.12

PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 72 bytes) in /usr/local/www/status_dhcp_leases.php on line 111
PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 22 bytes) in /usr/local/www/services_dhcp.php on line 62

**Comment by fichtner** [comment]
haven't seen these in a long time
