### ISSUE TITLE
16.7.b_78 save or reset RRD data in Reporting: Settings redirect to diag_log_settings.php

### ISSUE THREAD

**Issue by gitdevmod** [opnsense/core#925]
Running 16.7.b_78
when I try to save or reset RRD data in "Reporting: settings" page it redirects to dia_log_settings.php and fails

![rrd - copie](https://cloud.githubusercontent.com/assets/2040775/15026021/78af135c-123c-11e6-8a4c-ee346a65de66.png)

**Comment by fichtner** [comment]
Yay, thanks to you both!

**Comment by AdSchellevis** [comment]
@fichtner I think we should remove most of the action="" tags, only some dashboard widgets have a valid reason to point to another location then the current page. what do you think?

**Comment by fichtner** [comment]
yes please, I did not anticipate this problem and this will solve it in the future :)
