### ISSUE TITLE
firmware: progress polling would stop while upgrade was running

### ISSUE THREAD

**Issue by fichtner** [opnsense/core#927]
/api/core/firmware/upgradestatus
    Failed to load resource: the server responded with a status of 404 (Not Found)

via: https://forum.opnsense.org/index.php?topic=2993.0

**Comment by fichtner** [comment]
@AdSchellevis you can have this if you want ;)

**Comment by AdSchellevis** [comment]
@fichtner sure, it misses a try/catch block
