### ISSUE TITLE
Adding a file .editorconfig in the repository

### ISSUE THREAD

**Issue by thelinuxfr** [opnsense/core#932]
Hi,

Why not add a file .editorconfig in repositories to standardize for example tabs, end line ... For more information http://editorconfig.org/

### Example file
```
root = true

[*]
indent_style = space
indent_size = 4
end_of_line = lf
charset = utf-8
trim_trailing_whitespace = true # doesn't work yet
insert_final_newline = true # doesn't work yet
```

**Comment by AdSchellevis** [comment]
@thelinuxfr sounds like a fine plan, I will add one for the most used file types.
