### ISSUE TITLE
Disabled Gateways Show In Gateway Widget

### ISSUE THREAD

**Issue by vectr0n** [opnsense/core#933]
I noticed the other day when I disabled a gateway it still appears in the gateway widget.  It will show 0.0ms 0.0% and as online.

**Comment by fichtner** [comment]
more info: gif + dynamic, this doesn't happen with "normal" gateways

**Comment by fichtner** [comment]
![6c5f04ff1a0b3f88a62d0526b971b39d](https://cloud.githubusercontent.com/assets/1915288/15099323/8444a0e2-1552-11e6-8f68-9813b7448602.png)
![4d5da1b14ddcd817c135d66838212805](https://cloud.githubusercontent.com/assets/1915288/15099324/85f79052-1552-11e6-9886-048b3aeaf38f.png)

**Comment by AdSchellevis** [comment]
@fichtner I think this happens with all "dynamic" types, the very obscure return_gateways_array() looks responsible.

Take a look here for example https://github.com/opnsense/core/blob/master/src/etc/inc/gwlb.inc#L634-L667 this seem to add the just disabled gateway again. We should probably refactor this into something readable..... there doesn't seem to be an easy fix.

**Comment by AdSchellevis** [comment]
related to https://github.com/opnsense/core/issues/957

**Comment by fichtner** [comment]
125808e addresses the remaining problems described in this ticket. I'm not entirely sure that this will backported to 16.1 with 16.7 just around the corner, but it is worth mentioning. :)
