### ISSUE TITLE
Interface netmask /31

### ISSUE THREAD

**Issue by natux54** [opnsense/core#934]
Hello, 
my ISP provides me a Public IP / 31 corresponding to the RFC 3021, but opnsense directly from 30 to 32.

**Comment by fichtner** [comment]
I will have to ask again which page / config setting are you referring to :)

**Comment by natux54** [comment]
sorry,

https://172.29.19.254/interfaces.php?if=wan

you can see => https://cloud.couanouz.net/index.php/s/z1xIHawlo9a7gcD

**Comment by AdSchellevis** [comment]
@natux54 can you try this fix?

```
curl -o /usr/local/www/interfaces.php https://raw.githubusercontent.com/opnsense/core/master/src/www/interfaces.php
```

**Comment by natux54** [comment]
yes at first seen it works
thank you

**Comment by AdSchellevis** [comment]
your welcome
