### ISSUE TITLE
bsnmpd crashes if $(location) contains a "ß"

### ISSUE THREAD

**Issue by mircsicz** [opnsense/core#939]
I had an Address in that field containing a german "Straße", so i got:

```
May 13 23:06:13	snmpd[97871]: in file /var/etc/snmpd.conf line 17
May 13 23:06:13	snmpd[97871]: in macro location pos 11
May 13 23:06:13	snmpd[97871]: unexpected character 0xffffffc3
```

not sure if it's a known bug, just wanted to report as it's late and I might forget about till tomorow...

**Comment by AdSchellevis** [comment]
I haven't seen it before, but snmpd doesn't seem to be unicode aware or uses a different character set,  there doesn't seem to be a lot of documentation about this subject.

When Using "Straße" in a location string it generates something like this:

```
location := "test location Straße"
sysLocation     = $(location)
```

Which raises the error you are receiving.

We could validate the input for unicode and warn the user, or maybe somebody else knows what directive or charset snmpd needs to make it accept this type of input.
