### ISSUE TITLE
Bug: Eicar test IPS rule

### ISSUE THREAD

**Issue by L1ghtn1ng** [opnsense/core#940]
I have the rule enabled and set to drop but when I download it does not generate an alert. This is with Firefox and chromium. I did try it in firefox first though

**Comment by AdSchellevis** [comment]
@L1ghtn1ng did you download eicar over http? (not https)

**Comment by L1ghtn1ng** [comment]
Did it both and still nothing

**Comment by fabianfrz** [comment]
Do you have it in your cache (browser or proxy) and run the IPS on the WAN interface?

**Comment by fabianfrz** [comment]
I have enabled the IPS without changing the mode just now and I get a log entry.

**Comment by L1ghtn1ng** [comment]
It is on the wan and I have not got a cache or proxy. Well not that I am aware of. Also I installed chromium and then did the same thing I did in Firefox. I have not seen any alerts generated since I set the IPS up which I would of thought I would of by now.

**Comment by L1ghtn1ng** [comment]
Also I have it set as an IPS not an IDS

**Comment by AdSchellevis** [comment]
is your wan interface connected to a physical device (em0, em1, ..)? if so, can you try to stop/start suricata.

**Comment by L1ghtn1ng** [comment]
Yeah it's connected to the modem and I will have to do that when I get home later

**Comment by fabianfrz** [comment]
Is the data link protocol supported by suricata?
https://suricata-ids.org/features/all-features/

**Comment by fichtner** [comment]
I remember it was added somewhere in the 3.0 development series, existed as a backport in FreeBSD ports for 2.x. I don't remember that it needs to be explicitly stated, but better double-check that...

**Comment by L1ghtn1ng** [comment]
@AdSchellevis sorry for taking so long to get back to you on this. I have just tried it again in chromuim in a incognito session, it still has not worked and the service has been restarted as it has been rebooted as this happened on the upgrade to 16.1.14

**Comment by L1ghtn1ng** [comment]
@AdSchellevis @fabianfrz Hopefully this also helps you out

[http://imgur.com/a/oe6qZ](url)

**Comment by L1ghtn1ng** [comment]
@AdSchellevis @fichtner  Seeing this in the log as well

```
May 21 08:00:21 	configd.py: [f82ee898-83ae-400b-a6eb-1729c72a9cb3] returned exit status 1
May 21 08:00:00 	configd.py: [f82ee898-83ae-400b-a6eb-1729c72a9cb3] update and reload suricata rules
May 21 04:00:00 	configd.py: [5b27128a-f716-42f8-845d-0519401018bd] update and reload suricata rules
May 21 00:00:00 	configd.py: [3da28c7e-66f2-4ca0-9e75-ee3d3d6f499e] update and reload suricata rules
May 20 20:00:12 	configd.py: [b3f80eb4-17c9-4d37-93f5-3e4cbb57c00c] returned exit status 1
May 20 20:00:00 	configd.py: [b3f80eb4-17c9-4d37-93f5-3e4cbb57c00c] update and reload suricata rules
May 20 16:00:00 	configd.py: [af5b38d4-2ec3-4e06-aecd-b91304778889] update and reload suricata rules
```

**Comment by L1ghtn1ng** [comment]
@AdSchellevis Maybe this helps as well

[dns setup](http://imgur.com/gbI1Sc7)

**Comment by AdSchellevis** [comment]
@L1ghtn1ng you have an issue with your setup, can you try to run the following commands one by one and output the results here?

```
ps fax | grep suri

/usr/local/opnsense/scripts/suricata/rule-updater.py

/usr/local/opnsense/scripts/suricata/installRules.py

/usr/local/bin/geoipupdate.sh

pkill -USR2 suricata
```

**Comment by L1ghtn1ng** [comment]
@AdSchellevis 
```
root@OPNsense:~ # /usr/local/opnsense/scripts/suricata/rule-updater.py
root@OPNsense:~ # 
```
Returned no output

```
root@OPNsense:~ # /usr/local/opnsense/scripts/suricata/installRules.py
root@OPNsense:~ # 
```
same as before

```
root@OPNsense:~ # /usr/local/bin/geoipupdate.sh
Fetching GeoIP.dat and GeoIPv6.dat...
/usr/local/share/GeoIP/GeoIPupdate.O8bSt3/GeoI100% of  491 kB 4047 kBps 00m00s
/usr/local/share/GeoIP/GeoIPupdate.6arZjp/GeoI100% of  792 kB 2100 kBps 00m00s
root@OPNsense:~ # 
```

```
root@OPNsense:~ # pkill -USR2 suricata
root@OPNsense:~ # ps fax | grep suri
42052  -  Ss      66:54.39 /usr/local/bin/suricata -D --netmap --pidfile /var/run/suricata.pid -c /usr/local/etc/suricata/suricata.yaml
28522  0  S+       0:00.00 grep suri
root@OPNsense:~ # 
```

**Comment by AdSchellevis** [comment]
@L1ghtn1ng odd, the output looks good, you could debug the rules that it actually installed by looking into the /usr/local/etc/suricata/opnsense.rules/ directory or the configuration file that was created ( /usr/local/etc/suricata/suricata.yaml). 

If you switch from ips to ids, is there still nothing reported then? netmap only functions on physical interfaces where it can capture traffic from.

I guess you have to do some more digging here to known why it doesn't appear to be working in your setup, I really doubt it's the eicar test rule.

**Comment by L1ghtn1ng** [comment]
@AdSchellevis Finally got an alert. This is when it is set to IDS mode and not IPS. But I want it to work when in IPS mode

**Comment by L1ghtn1ng** [comment]
@AdSchellevis I even get an alert in firefox as well when its in IDS mode

**Comment by AdSchellevis** [comment]
@L1ghtn1ng you could switch your interface to you lan instead of your wan, if your wan uses a pppoe layer it will probably not work with netmap.

**Comment by L1ghtn1ng** [comment]
@AdSchellevis in IPS mode in firefox when the interface is set to lan I get a blocked alert. This is using firefox, so it is now working but as my wan is pppoe why does this not work when in IPS mode and the interface is set to wan instead of lan?

**Comment by AdSchellevis** [comment]
@L1ghtn1ng ips uses netmap, which captures traffic before it enters normal kernel operation. In case traffic is encapsulated, rules very likely won't match any more.

**Comment by L1ghtn1ng** [comment]
Ah okay thanks for that. Might be an idea to have some documentation
about it or have it as part of the full help menu in the UI?

This would be handy for people not to get confused to why its not
working when it should.

**Comment by fichtner** [comment]
it could also be Suricata not decapsulating PPPoE... There was a bug last year where PPPoE would not work on pfSense/FreeBSD at all which was fixed for 3.0.

https://redmine.openinfosecfoundation.org/issues/1445

**Comment by L1ghtn1ng** [comment]
That is probably the issue then and why the lan interface only works
correctly

**Comment by fichtner** [comment]
Commit in question... it works for PCAP (IDS), but not Netmap. I'll ask the author to see if there is something to be done here.

https://github.com/inliniac/suricata/commit/04ccfda6398

**Comment by L1ghtn1ng** [comment]
@fichtner thanks and we will want to re-open this ticket?

**Comment by fichtner** [comment]
Won't do much good other than reporting upstream, which I've done now:

https://twitter.com/fitchitis/status/734443657982582784

I can follow up as soon as something is available through Suricata though.
