### ISSUE TITLE
When adding a new "Allow List" in DNS REsolver backspace in the wrong field destroy's the work

### ISSUE THREAD

**Issue by mircsicz** [opnsense/core#942]
when I create a new List backspace should not be linked to go-back!

Did it three times now, is fu..ing annoying...

**Comment by AdSchellevis** [comment]
its probably not OPNsense, but your browser using backspace as back
For firefox see:
http://kb.mozillazine.org/Browser.backspace_action

(using about:config)

**Comment by fichtner** [comment]
I had this "backspace problem" virtually everywhere with Chrome. I use "BackStop" extension for that reason.

**Comment by mircsicz** [comment]
THX, went with "BackStay"...
