### ISSUE TITLE
Cloning an firewall schedule doesn't do anything

### ISSUE THREAD

**Issue by module0x90** [opnsense/core#943]
Hi,

I just realized that when you clone a "firewall schedule" the webinterface is just reset, the menu on left is folded close (the firewall section was previously open, as I have clicked on "Schedules") and nothing else happens, ie no duplicate schedule is created.
It doesn't matter whether you clone schedules which are in use or not.

I am on

OPNsense 16.1.13-amd64 
Intel(R) Atom(TM) CPU D425 @ 1.80GHz
2 CPUs: 1 package(s) x 1 core(s) x 2 HTT threads

and it says no updates are outstanding.

Cheers

Tom

**Comment by fichtner** [comment]
Hi Tom,

Nice catch, will be fixed in 16.1.14, thank you :)


Cheers,
Franco
