### ISSUE TITLE
trust: ask to remove passwords from certs

### ISSUE THREAD

**Issue by fichtner** [opnsense/core#944]
via: https://forum.opnsense.org/index.php?topic=3021

**Comment by AdSchellevis** [comment]
@fichtner I rather won't add this in the gui, it assumes extra safety which isn't really the case.

**Comment by fichtner** [comment]
Can/should we prevent import of protected certs then?

**Comment by AdSchellevis** [comment]
From a user perspective, it would be best if you could remove the pass from the gui.... but honestly, this is hardly used and all clients containing openssl can do it with one command.

```
openssl rsa -in privateKey.pem -out newPrivateKey.pem
```

I would close this issue and leave it for what it is, but if you want to spend time on it... feel free :)

**Comment by fichtner** [comment]
Sounds like a plan. There is some pkcs#12 magic pending for our trust stuff too, maybe some fine day :)

**Comment by AdSchellevis** [comment]
timeout due to inactivity
