### ISSUE TITLE
Interface mismatch after restoring config.xml from gui

### ISSUE THREAD

**Issue by gitmod** [opnsense/core#95]
Step to reproduce
* install opnsense 15.1.7-78bdb9aef (amd64) FreeBSD 10.1-RELEASE-p6
* backup configuration
* change network interface name in config.xml
* restore configuration
* interface mismatch is detected, select correct network interface from the list
* reboot

opnsense detects a network interface mismatch

**Comment by fichtner** [comment]
Thanks, I will check this out.

**Comment by AdSchellevis** [comment]
The config handling will be replaced in release 15.1.8 (next week), the new code is currently available in branch config_replace and doesn't include this issue.
