### ISSUE TITLE
configd: script_output does not output on execute error (ret != 0)

### ISSUE THREAD

**Issue by fichtner** [opnsense/core#951]
Hi Ad,

I found this, not entirely sure if intended?

    # configctl firmware hotfix hello
    Execute error
    # opnsense-patch hello
    fetch: https://github.com/opnsense/core/commit/hello.patch: Not Found

For script error it seems important to still push the output, although I don't know what to do with the extra failure info. Do we even use this in the API?

**Comment by fichtner** [comment]
Log entry for reference:

configd.py: [538a19a0-1f31-43da-a830-2c531fece34a] Script action failed with Command '/usr/local/sbin/opnsense-patch "hello"' returned non-zero exit status 1 at Traceback (most recent call last): File "/usr/local/opnsense/service/modules/processhandler.py", line 477, in execute stdout=output_stream, stderr=error_stream) File "/usr/local/lib/python2.7/subprocess.py", line 540, in check_call raise CalledProcessError(retcode, cmd) CalledProcessError: Command '/usr/local/sbin/opnsense-patch "hello"' returned non-zero exit status 1

**Comment by AdSchellevis** [comment]
You don't know for sure that the script came to a point of returning output, it should log failure, but it might shout out the output if it did receive if any. 
The code in question is this https://github.com/opnsense/core/blob/master/src/opnsense/service/modules/processhandler.py#L473-L492

The error message "Execute error" isn't used in the api.

Replace with output and keep the logging?

**Comment by fichtner** [comment]
@AdSchellevis  Ok, you are right, should have done it like we've always done, pushed a commit for that. :)

Last small question: can we support multiple parameters on demand or will it just be one by one? For hotfixing it may be necessary to push more than one patch, which could be done in a single run.

**Comment by AdSchellevis** [comment]
@fichtner you can add more parameters, but the list is fixed... all missing will be left empty. 

I'm not sure how you want to push more then one, if it should rollback all on failure, you could pass the list comma separated. If you want the api to support more at once, you can call the configd action multiple times when needed from within the same api call or use the client part to execute one by one (which has the advantage of knowing progress).

**Comment by fichtner** [comment]
Thanks so far! Yet subprocess.check_call raises CalledProcessError, so it never tries to read from the stream. End result: empty output from the command and a log entry for the exception.
