### ISSUE TITLE
configd: IDS template error on 16.1.14-devel

### ISSUE THREAD

**Issue by fichtner** [opnsense/core#956]
May 22 11:01:12	configd.py: [198922af-668f-4d40-ad66-e971a4a696ca] Inline action failed with OPNsense.IDS OPNsense/IDS/suricata.yaml 'collections.OrderedDict object' has no attribute 'IDS' at Traceback (most recent call last): File "/usr/local/opnsense/service/modules/processhandler.py", line 505, in execute return ph_inline_actions.execute(self, inline_act_parameters) File "/usr/local/opnsense/service/modules/ph_inline_actions.py", line 52, in execute filenames = tmpl.generate(parameters) File "/usr/local/opnsense/service/modules/template.py", line 312, in generate for filename in self._generate(template_name, create_directory): File "/usr/local/opnsense/service/modules/template.py", line 260, in _generate raise Exception("%s %s %s" % (module_name, template_filename, render_exception)) Exception: OPNsense.IDS OPNsense/IDS/suricata.yaml 'collections.OrderedDict object' has no attribute 'IDS'
May 22 11:01:12	configd.py: generate template container OPNsense.IDS
May 22 11:01:12	configd.py: generate template container OPNsense.Cron
May 22 11:01:12	configd.py: generate template container OPNsense.Captiveportal
May 22 11:01:12	configd.py: generate template container OPNsense
May 22 11:01:12	configd.py: [198922af-668f-4d40-ad66-e971a4a696ca] generate template *

**Comment by AdSchellevis** [comment]
@fichtner are you very sure you tested the latests after a configd restart? When I wreck the IDS template on my end, it results in :

```
May 22 11:47:27 OPNsense configd.py: [c227a419-998d-46de-b127-8b38bb6ae49f] generate template *
May 22 11:47:28 OPNsense configd.py: generate template container OPNsense
May 22 11:47:28 OPNsense configd.py: generate template container OPNsense.Captiveportal
May 22 11:47:28 OPNsense configd.py: generate template container OPNsense.Cron
May 22 11:47:28 OPNsense configd.py: generate template container OPNsense.HelloWorld
May 22 11:47:28 OPNsense configd.py: generate template container OPNsense.IDS
May 22 11:47:28 OPNsense configd.py: error generating template OPNsense.IDS
May 22 11:47:28 OPNsense configd.py: generate template container OPNsense.IPFW
May 22 11:47:28 OPNsense configd.py: generate template container OPNsense.Macros
May 22 11:47:28 OPNsense configd.py: generate template container OPNsense.Netflow
May 22 11:47:29 OPNsense configd.py: generate template container OPNsense.Proxy
May 22 11:47:29 OPNsense configd.py: generate template container OPNsense.Sample
May 22 11:47:29 OPNsense configd.py: generate template container OPNsense.Sample.sub1
May 22 11:47:29 OPNsense configd.py: generate template container OPNsense.Sample.sub2
May 22 11:47:30 OPNsense configd.py: generate template container OPNsense.Syslog
```

hitting this error block https://github.com/opnsense/core/blob/master/src/opnsense/service/modules/template.py#L316-L318

**Comment by fichtner** [comment]
@AdSchellevis right, sorry,  I was testing -devel but it did not have the fix. The fix works, but the IDS error is there by default. Any idea?

**Comment by fichtner** [comment]
ps: the exception is not pushed to syslog anymore, should it be displayed still?

**Comment by AdSchellevis** [comment]
@fichtner the exception is pushed when generating the single package... when using a wildcard it silences. this was intended.

about the ids error, are you sure you tested with the latest template : https://github.com/opnsense/core/commit/8b4b5bbb864ecb3c0bf22c94663d08e545aee603#diff-e3b4444e0086ef9597f4d5f3ec39410b

**Comment by fichtner** [comment]
Oh ok, this is also not on -devel, a bit bumpier than usual. I guess that might have been also my problem with Squid not coming up un boot we talked about. Thanks for clearing that up.

Hmm, if we silence the error there it will make bug reports much harder in that area. What was your intention for silencing?

The downside is that we can't catch these errors for people that don't use a particular subsystem, especially like it happened with the IDS template because the error only appears when it is not configured so we never see the exception in the first place leaving the user with an unidentifiable error on bootup only that disappears when he starts to use the service.

**Comment by AdSchellevis** [comment]
The intention is quite simple, if a user spots "OPNsense configd.py: error generating template" he can get details be generating that specific subsystem. Most of the times it doesn't really matter if the system was unconfigured.

In case you rather log the traceback, I have no real objections against it.... other then its not very important to know the details there..

**Comment by fichtner** [comment]
It takes yourself to explain it to me, which doesn't sound like users will understand without dedicating support time to them each time someone picks up on the silent error. I'd rather have it back to get the error pasted directly in a report when someone stumbles across it. :)

**Comment by AdSchellevis** [comment]
sure, no problem...
