### ISSUE TITLE
gateways: defaultgw is enforced on last gateway even if disabled

### ISSUE THREAD

**Issue by fichtner** [opnsense/core#957]
Interesting code block, the question still stands: should this really be done??

https://github.com/opnsense/core/blob/master/src/etc/inc/gwlb.inc#L767-L786

Furthermore, dynamic entries can lose their monitor IP as reported on IRC.

**Comment by fichtner** [comment]
FWIW, deleting the block and rebooting brings up WAN as expected with DHCP autoconfiguration as it would with no gateway in the list.

**Comment by fichtner** [comment]
@AdSchellevis hi Ad, can you look at this for me for a second opinion? thanks :)

**Comment by AdSchellevis** [comment]
for reference, we'll keep it this way for now until there's time for a larger refactor  of this code. There's more odd code in it which needs a proper cleanup.

**Comment by fichtner** [comment]
FWIW, the default route is still added even on reboot when the gateway was disabled, at least for IPv4 DHCP. I suspect IPv6 auto-config modes to do the same...
