### ISSUE TITLE
[FR] Reset interface when it stops processing packets.

### ISSUE THREAD

**Issue by oparoz** [opnsense/core#961]
Under certain conditions (16.1.14 kernel using netmap), some interfaces (realtek) stop processing packets. A simple "down && up" restores connectivity, but it would be much better if opnsense could automatically detect that the interface has stopped processing packets and restart it.

1. How to detect that the interface has stopped working properly? Apparently the gateway monitoring mechanism doesn't work for this case. Is there another mechanism in place which could be used

2. Add a script to restart the interface when failure is detected

**Comment by AdSchellevis** [comment]
@oparoz you probably best create a script for your specific situation yourself (look for dmesg messages for example, or try to ping a local machine).

Restarting interfaces automatically is usually not a very good idea and leads to all kinds of unexpected behaviour, which we try to avoid. Broken or not very well supported hardware often reacts very differently, so my advice would be to either search for better supported hardware or script your way out of your specific issue ;)

**Comment by oparoz** [comment]
Pinging seems to be the only solution since there is no error in any logs, but I was hoping to find a way which is more integrated into opnsense than using a cronjob since the interface can become unavailable under normal circumstances such as enabling Suricata.

@AdSchellevis - Are there flags in opnsense which indicate when a reconfiguration is happening? Kind of like the maintenance mode used in web apps.

**Comment by AdSchellevis** [comment]
@oparoz you could search you log for interface up/down events if they are emitted in your fault situation, something like this:

clog -f /var/log/system.log

May 25 14:42:36 OPNsense kernel: em0: link state changed to DOWN
May 25 14:42:39 OPNsense kernel: em0: link state changed to UP

This happens when you pull the plug, but if the driver hangs, you might not see anything... (or maybe other kernel messages concerning failure)

You could also create a script that runs in the background and start it using the plugins hook.

**Comment by oparoz** [comment]
@AdSchellevis - The interface doesn't go down. Everything looks normal, except for the kernel trying to send packets to a non-responsive interface. The only difference is the number of missed frames, but it's going to severely pollute dmesg if stats are being printed every minute.

After having lookedat the doc, I don't think a plugin will add anything to the script for now, but I guess I could monitor suricata.pid for changes and add other PIDs when noticing problems.

**Comment by AdSchellevis** [comment]
timeout
