### ISSUE TITLE
[FR] Keep IDS/IPS logs

### ISSUE THREAD

**Issue by oparoz** [opnsense/core#962]
IPS logs are wiped after a restart when using tmpfs. It would be good if they could be kept, just like some of the other logs since those are pretty important.

**Comment by fichtner** [comment]
No, don't use it. This has been the standard behaviour for years. Going to split /tmp and /var MFS setting eventually, but that won't change the underlying behaviour of a memory file system.

**Comment by oparoz** [comment]
As long as you keep /var out of tmpfs, then it's all good :+1:

**Comment by fichtner** [comment]
I will try to make this happen for 16.1.x :)
