### ISSUE TITLE
nonexisting configd call

### ISSUE THREAD

**Issue by fichtner** [opnsense/core#968]
Hi Ad,

I found these...

$ git grep interface.reconfigure
src/etc/inc/interfaces.inc:                            configd_run("interface reconfigure {$interface}");
src/etc/rc.newwanip:            configd_run("interface reconfigure {$interface}");
src/etc/rc.newwanipv6:  // configd_run("interface reconfigure {$interface}");
src/www/system_gateways_edit.php:            configd_run("interface reconfigure {$reloadif}");

Do you know what they were supposed to call exactly? They don't do anything now :(

Cheers,
Franco

**Comment by AdSchellevis** [comment]
@fichtner are you sure? 
https://github.com/opnsense/core/blob/master/src/opnsense/service/conf/actions.d/actions_interface.conf#L1-L5

(calls : /usr/local/etc/rc.interfaces_wan_configure)

or am I missing something here?

**Comment by fichtner** [comment]
Oopsie, right... was looking for "interface reconfigure" in that file, but it's appended. Thanks. :)

**Comment by AdSchellevis** [comment]
your welcome :)
