### ISSUE TITLE
BUG PPPOE Disconnects after Time - Routing Problems

### ISSUE THREAD

**Issue by andreasvel** [opnsense/core#974]
Reference to (german)
https://forum.opnsense.org/index.php?topic=3066.0

my PPPOE Uplink disconnects after a time without a cause.
restarting makes the PPPOE Running again but its unstable after a time

the problems continues and makes the routing instable/not functional.

**Comment by L1ghtn1ng** [comment]
I have noticed that as well

**Comment by fichtner** [comment]
Have you tried the periodic PPPoE reset option(s)? That's there to address this problem without manual intervention...

**Comment by L1ghtn1ng** [comment]
Which option is that?

**Comment by fichtner** [comment]
Either under Point To Point Advanced Edit oder under Interface config... It's pretty hidden and complex, but it should help to periodically reset the interface.

There is a Cron rework going on at the moment, it will remove the feature in favour of a simple and flexible approach where you can pick the actual Cron settings.

**Comment by L1ghtn1ng** [comment]
Will wait to 16.1.16 if that will be in this week's release?

**Comment by andreasvel** [comment]
still the same problems with 24h reconnect
the routing is going down.. no default route to pppoe. normal uplink is stable.. just in case the pppoe is the default route the system is not routing right and loosing the connection

**Comment by andreasvel** [comment]
any new infos here? the problem is still alive :(

**Comment by fichtner** [comment]
Why do we have two tickets for this? https://github.com/opnsense/core/issues/850
