### ISSUE TITLE
[Enhancement] Add possibility to use IPv6 on multiple interfaces

### ISSUE THREAD

**Issue by enoch85** [opnsense/core#975]
My ISP provides a 6to4 tunnel via Teredo and I have multiple interfaces set up behind the OPNsense firewall. The problem for me is that I can only use IPv6 on 1 of the interfaces (seems like it anyway), and I would want to use IPv6 on multiple interfaces e.g. LAN | VLAN | WIFI_AP. Right now I have to choose which one I want to use IPv6 on.

- OPNsense 16.1.15-amd64	
- FreeBSD 10.2-RELEASE-p17	
- OpenSSL 1.0.2h 3 May 2016

**Comment by lattera** [comment]
I need to do a blog article, but I have IPv6 on multiple interfaces. I'm using Hurricane Electric's TunnelBroker service to provide me with a /48. I dish out different /64 prefixes on each of the different interfaces. The article I'll write will apply to you if you have a /48.

**Comment by lattera** [comment]
[Here](https://gist.github.com/lattera/304b8fe02144db4f8253324550655a2d) is a work-in-progress article.

**Comment by enoch85** [comment]
@lattera Thanks but I'm not based in US, and with 6to4 I have the issue posted on the first post.

**Comment by lattera** [comment]
Ah. Well, the instructions I wrote will work for peeps outside of the US. The only real requirement is getting assigned a /48 instead of just a /64. I'm not entirely sure about using Teredo, though, since I have no experience with it.

**Comment by fichtner** [comment]
@enoch85 Daniel, is this still a problem or was just a setup quirk?

**Comment by enoch85** [comment]
> just a setup quirk?

Yes.

**Comment by enoch85** [comment]
Or no, I think this is still valid btw.

**Comment by enoch85** [comment]
But this can be closed as I have it setup now how I want :)
