### ISSUE TITLE
Cloning a firewall schedule doesn't let you change the name

### ISSUE THREAD

**Issue by module0x90** [opnsense/core#976]
Hi,

just trying to clone firewall schedules, but unfortunately it keeps saying

 NOTE: This schedule is in use so the name may not be modified!

*after* having clicked on "Clone". This should be a new entry and cannot be in use.

 OPNsense 16.1.15-amd64 

Cheers

Thomas

**Comment by fichtner** [comment]
Hi Thomas,

Odd thing, should be fixed. Will be in 16.1.16.


Thanks,
Franco
