### ISSUE TITLE
Suggestion: Better overview of valid and expired vouchers in a role

### ISSUE THREAD

**Issue by DokuKaefer** [opnsense/core#977]
This would be easier to manage the voucher role.

**Comment by AdSchellevis** [comment]
@DokuKaefer have you tried sorting the grid on "state"?

**Comment by DokuKaefer** [comment]
Yes I have. But for me, this is confusing, at more than 100 vouchers.
A small counter per roll with valid and expired vouchers would be better to see if there are enough valid vouchers are available.

Or it is possible to let delete expired voucher codes automatically?

**Comment by AdSchellevis** [comment]
We could add a button to drop the expired vouchers

**Comment by DokuKaefer** [comment]
That sounds good!

**Comment by fichtner** [comment]
#899 is also useful while at it :)
