### ISSUE TITLE
SNMP OID List - OPNsense 16.1.x

### ISSUE THREAD

**Issue by overcore456** [opnsense/core#978]
Hi everybody,
I'm trying to monitoring (cpu, ram, traffic etc.) OPNsense with SNMP via a third party tool (PRTG) and already tried a list of OID from pfsense but nothing worked. Is there a list of OID that I can use for custom SNMP sensors?
Best regards,
Marco

**Comment by fabianfrz** [comment]
Is SNMP enabled and the port open?

**Comment by overcore456** [comment]
Yes, SNMP is enabled and port 161 is configured. I used SNMP Tester from PRTG to try out different OIDs but always got "Value: No such object (SNMP error # 222)".

**Comment by fabianfrz** [comment]
Can you try to fetch the data on the command line with snmpwalk?

**Comment by overcore456** [comment]
Hi Fabian,

this is the output that i get from snmpwalk (./snmpwalk -v 2c -c public 192.168.0.X):

iso.3.6.1.2.1.1.1.0 = STRING: "OPNsense wangw1 16.1.15-cfbcc72ad OPNsense FreeBSD 10.2-RELEASE-p17 amd64"
iso.3.6.1.2.1.1.2.0 = OID: iso.3.6.1.4.1.12325.1.1.2.1.1
iso.3.6.1.2.1.1.3.0 = Timeticks: (9197197) 1 day, 1:32:51.97
iso.3.6.1.2.1.1.4.0 = STRING: "Admin"
iso.3.6.1.2.1.1.5.0 = STRING: "wangw1"
iso.3.6.1.2.1.1.6.0 = STRING: "X1"
iso.3.6.1.2.1.1.7.0 = INTEGER: 76
iso.3.6.1.2.1.1.8.0 = Timeticks: (0) 0:00:00.00
iso.3.6.1.2.1.1.9.1.2.1 = OID: iso.3.6.1.4.1.12325.1.1.1.10.2
iso.3.6.1.2.1.1.9.1.2.2 = OID: iso.3.6.1.4.1.12325.1.1.1.10.3
iso.3.6.1.2.1.1.9.1.2.3 = OID: iso.3.6.1.6.3.1
iso.3.6.1.2.1.1.9.1.2.4 = OID: iso.3.6.1.4.1.12325.1.1
iso.3.6.1.2.1.1.9.1.3.1 = STRING: "udp transport mapping"
iso.3.6.1.2.1.1.9.1.3.2 = STRING: "lsock transport mapping"
iso.3.6.1.2.1.1.9.1.3.3 = STRING: "The MIB module for SNMPv2 entities."
iso.3.6.1.2.1.1.9.1.3.4 = STRING: "The MIB module for the Begemot SNMPd."
iso.3.6.1.2.1.1.9.1.4.1 = Timeticks: (0) 0:00:00.00
iso.3.6.1.2.1.1.9.1.4.2 = Timeticks: (0) 0:00:00.00
iso.3.6.1.2.1.1.9.1.4.3 = Timeticks: (0) 0:00:00.00
iso.3.6.1.2.1.1.9.1.4.4 = Timeticks: (0) 0:00:00.00
iso.3.6.1.2.1.11.1.0 = Counter32: 1525
iso.3.6.1.2.1.11.3.0 = Counter32: 0
iso.3.6.1.2.1.11.4.0 = Counter32: 0
iso.3.6.1.2.1.11.5.0 = Counter32: 0
iso.3.6.1.2.1.11.6.0 = Counter32: 0
iso.3.6.1.2.1.11.30.0 = INTEGER: 2
iso.3.6.1.2.1.11.31.0 = Counter32: 0
iso.3.6.1.2.1.11.32.0 = Counter32: 0

Not much. :-(

(Grüsse nach Leipzig :-) )

**Comment by fabianfrz** [comment]
Hi @overcore456, I ran the same command and got much more entries. Which modules did you select?

I selected all of them.

**Comment by overcore456** [comment]
Arggg. Because of the theme we use I couldnt see the boxes for module selection. After selecting them all I get the full list of OIDs. Do you know which OIDs are for CPU load and Traffic data?

**Comment by fabianfrz** [comment]
I am sorry, no I don't.

**Comment by fichtner** [comment]
Hi Marco,

Is this still valid? I can point you to the OID descriptions on the hard disk if you need.


Jetzt aber Grüße aus Leipzig ;)
Franco

**Comment by overcore456** [comment]
Can be closed :-) All solved.

**Comment by fichtner** [comment]
ok, thanks!
