### ISSUE TITLE
Feature Request - Social Proxy

### ISSUE THREAD

**Issue by neurospeech** [opnsense/core#987]
I know this is quite big, but here is problem in Software Development company, we often have to open Social Media websites for developers to develop and test OAuth and API integration, which almost every company needs. All firewalls support only banning Social Media completely or make it open.

Here is a suggestion, as of course we can intercept HTTPS, and we can intercept all HTTP URI/HEADERS/Content, if we can setup rules like `account.google.com` with path `/login` can only work for `a@gmail.com` and `b@gmail.com`, same for `account.facebook.com` with path `/login` can only work for `a` and `b`, this way we can control how can login to Social Media in which account.

This will eventually block all personal social media accounts.

I know you guys are using squid internally, but if you can provide a way to use some other proxy server on different ip, it will be helpful.

**Comment by fabianfrz** [comment]
hi @neurospeech, is ICAP an options for you?

**Comment by neurospeech** [comment]
@fabianfrz I will try, but how do I configure SQUID from OPNSense? It would be nice if there is direct configuration.

**Comment by neurospeech** [comment]
I will try ICAP, but I feel it is mostly for downloaded content, I don't know if it will work for HTTPS POST requests. If there is a way to bypass SQUID and simply use some different PROXY SERVER, I am windows and .NET user, writing simple proxy in c# is way too easy then trying to plugin ICAP which is little new.

**Comment by fabianfrz** [comment]
You can use your own proxy server as well - you will need a different firewall rule but it would work.
Be careful with this rule when the proxy is in the same network.

**Comment by neurospeech** [comment]
@fabianfrz can you give me an example of how to setup custom http proxy server?

**Comment by fabianfrz** [comment]
just use the docs: https://docs.opnsense.org/manual/how-tos/proxytransparent.html#step-3-nat-firewall-rule

you will have to use another ip address (the one of your proxy server) and this proxy server must not be redirected to itself (loop) if you want to use it as a transparent proxy.

If you want to use a "normal" proxy, you can drop HTTP(S) traffic from all IP addresses except the one of the proxy (Filter rule).

**Comment by fichtner** [comment]
out of scope for core development
