### ISSUE TITLE
Feature Reuqest - Support for Cisco AnyConnect

### ISSUE THREAD

**Issue by bkolbe** [opnsense/core#989]
It would be a nice Feature if Cisco AnyConnect could be used for VPN.

**Comment by fraenki** [comment]
For investigation: the `security/openconnect` port and [this hack](http://blog.dhampir.no/content/pfsense-as-a-cisco-anyconnect-vpn-client-using-openconnect)...

**Comment by fichtner** [comment]
I'll look at this for 16.7, no promises :)

**Comment by fichtner** [comment]
Er, I mean 17.1

**Comment by fichtner** [comment]
I'm adding this to the packages repository, but plugin will be have to built by the community :)

https://github.com/opnsense/plugins
