### ISSUE TITLE
Layer7 Filter does not function

### ISSUE THREAD

**Issue by jschellevis** [opnsense/core#99]
After configuring Layer7 filter rules, I get this error in system.log:

ipfw-classifyd: packet dropped: output queue full

And ipfw-classifyd runs at very high cpu load when doing nothing at all (100%+).

To test use latest git sources as some related issue have been solved.. setup Layer7 group and add a firewall rule.. apply and see log.

**Comment by AdSchellevis** [comment]
Functionality temporary removed in https://github.com/opnsense/core/commit/1ad20825d4aa0c2b2867c6c313be10a13a85bd53

**Comment by fichtner** [comment]
Put this on the long-term roadmap soon, remove from tracker now.
