### ISSUE TITLE
[Intrusion Detection] Remove all Rules when the main rule set to be disabled

### ISSUE THREAD

**Issue by enoch85** [opnsense/core#991]
So, I played around with Intrusion Detection and enabled rules that I thought would be nice to have (DOS, Trojan, Scan Fedo Tracker), hit apply and now I can't browse until I turn Intrusion Detection off. Just removing "Enabled" in the "main menu" didn't help as the rules are still enabled when I go to "Rules".

This shouldn't be the case imho. When I disable a rule the rules associated to that rule should also be disabled or removed.

Also It would be nice to be able to uninstall rules and/or enable default rules (is any).

Forum post is here: https://forum.opnsense.org/index.php?topic=3154.0

**Comment by AdSchellevis** [comment]
@enoch85 did you apply your changes? (download & apply when changing complete rulesets, apply when changing specific rules)
Download / Apply should also remove the uninstalled sets.

**Comment by enoch85** [comment]
Oh yeah, that solved it. Thanks :)
