### ISSUE TITLE
[plugins] inject new firewall rules

### ISSUE THREAD

**Issue by AdSchellevis** [opnsense/core#993]
Just an idea, probably won't make it for 16.7. But we could extend the plugin system to propagate its needed firewall rules, which will be automatically installed into the config.xml.
(like new interfaces do in current master)

Advantage of doing this is that the firewall config shows the actual settings its using and would simplify the fiter.inc a lot.

Ideas, no concrete plan yet.....

**Comment by fichtner** [comment]
Note to self: For now it seems we only have to insert anchors and the utilities will be able to inject their rules at will. This also includes relayd and miniupnpd, which could be split off as plugins in the future.

**Comment by AdSchellevis** [comment]
@fichtner that's only part of the story here... let's keep this for Friday.

**Comment by fichtner** [comment]
of course, only keeping some notes for consistency

**Comment by fichtner** [comment]
the framework works, no need to keep this ticket anymore

great work by @AdSchellevis
