### ISSUE TITLE
OpenVPN windows client export

### ISSUE THREAD

**Issue by natux54** [opnsense/core#994]
Hello,

it is impossible to install the windows of the export OpenVPN client, windows returns the following error: Unsupported Method.

opnsense version: 16.1.15 and 16.7.b_276-amd54
windows version : windows 10

**Comment by fraenki** [comment]
@natux54: I'm using the "Archive" export option in OPNsense. My OpenVPN-compatible [SecurePoint VPN client](https://sourceforge.net/projects/securepoint/) works like a charm with the included files.

What export option do you use to download the configuration from OPNsense? What's the version of your OpenVPN client? Do you use the official OpenVPN client or anything else?

**Comment by fichtner** [comment]
This? https://redmine.pfsense.org/issues/5763

**Comment by AdSchellevis** [comment]
wouldn't it be better to remove the windows executables from our system and only export profiles? our versions aren't the latests available (and we're not trying to distribute other clients either)

**Comment by natux54** [comment]
hello,
yes is this  https://redmine.pfsense.org/issues/5763

**Comment by fabianfrz** [comment]
@AdSchellevis I cannot say if it would be better or not to remove them but at least they should not be included in core as they increase the size of the updates and do not change often. They should be moved into a separate package at least to create smaller updates.

**Comment by fichtner** [comment]
zap as long as the overall export ability stays the same, nobody will update the binary files anyway...

**Comment by AdSchellevis** [comment]
as discussed with @fichtner, windows installers have been removed. Viscosity visz format has been added to the selection for hassle free windows installation.
