### ISSUE TITLE
dns forwarder: import page for overrides

### ISSUE THREAD

**Issue by module0x90** [opnsense/core#995]
Hi,

I am on OPNsense 16.1.15-amd64 and I have noticed the following 'strange' behaviour.

I have in my advanced section of DNS Forwarder the following:
conf-dir=/root/dnsmasq-domains,*.conf
There are some .conf files in there, what for redirecting maldomains/addomains to a specific IP, and another file just contains "log-queries".

So I noticed that everyday (I believe) "log-queries" for example doesn't work. Checking the machine then shows me that dnsmasq is running with /usr/local/etc/dnsmasq.conf as its config. That config looks like the default config and there is nothing exciting in there.
(I have just restarted DNS Forwarder, so I cannot provide the "default" ps auxwwww entry unfortunately.)

Then when I restart DNS Forwarder via the web interface, then it all comes to live. My config is working.

When it's working the ps auxwwww entry looks like

nobody 16482   0.1  0.2  23756   7892  -  S     8:34PM     0:01.33 /usr/local/sbin/dnsmasq --all-servers --rebind-localhost-ok --stop-dns-rebind --listen-address=A.B.C.D --listen-address=A.B.E.D --listen-address=A.B.F.D --bind-interfaces --server=/10.in-addr.arpa/ --server=/168.192.in-addr.arpa/ --server=/16.172.in-addr.arpa/ --server=/17.172.in-addr.arpa/ --server=/18.172.in-addr.arpa/ --server=/19.172.in-addr.arpa/ --server=/20.172.in-addr.arpa/ --server=/21.172.in-addr.arpa/ --server=/22.172.in-addr.arpa/ --server=/23.172.in-addr.arpa/ --server=/24.172.in-addr.arpa/ --server=/25.172.in-addr.arpa/ --server=/26.172.in-addr.arpa/ --server=/27.172.in-addr.arpa/ --server=/28.172.in-addr.arpa/ --server=/29.172.in-addr.arpa/ --server=/30.172.in-addr.arpa/ --server=/31.172.in-addr.arpa/ --conf-dir=/root/dnsmasq-domains,*.conf --dns-forward-max=5000 --cache-size=10000 --local-ttl=1

So it seems that dnsmasq is restarted at some point automatically - but with its default config.

Cheers

Thomas

**Comment by AdSchellevis** [comment]
Hi Thomas,

When it happens again, can you provide some more information? 
The only occurrence in the code I could find which starts dnsmasq is this one https://github.com/opnsense/core/blob/master/src/etc/inc/services.inc#L1977 which doesn't really explain what's happening here.

When it happens, can you inspect your syslog?
```
clog /var/log/system.log
```

And the ps output like you suggested.

Finally, do you have any custom scripts or hooks installed on your version?

Best regards,

Ad

**Comment by module0x90** [comment]
Oh yeah.
While I was eating breakfast in the morning I kept reading your email over and over again, then I realized.

As part of my malware-domainlist and ads-domainlist a remote script is executing

ssh root@firewall service dnsmasq onerestart >/dev/null

and I suspect that's the culprit here. Looking at dnsmasq's current "ps aux" entry, this is it:

nobody 62589   0.0  0.1  19660   2944  -  S     3:00AM     0:01.84 /usr/local/sbin/dnsmasq -x /var/run/dnsmasq.pid -C /usr/local/etc/dnsmasq.conf

and my script also runs at 3am.

What's the proper way to restart dnsmasq in the OPNSense way?


Cheers

Thomas

**Comment by fichtner** [comment]
If you only want to reload dnsmasq config files you should get away with: pkill -HUP dnsmasq

The "service" utility uses the FreeBSD config, not the OPNsense config. For newer services that's already changing though :)

**Comment by module0x90** [comment]
That works for me... :-)

Awesome, thanks guys.

**Comment by fichtner** [comment]
Sure thing, cheers

**Comment by module0x90** [comment]
I noticed pkill -HUP dnsmasq doesn't reload it's config really. Which other way is there to restart dnsmasq as my own provided config (repointing adservers and malwaredomains) is not loaded?

**Comment by fichtner** [comment]
Get a proper feature in that's maintained via GUI? Let's start from the top... :)

**Comment by module0x90** [comment]
Oh. A feature where you can feed it a list of domain names pointing to an IP you choose, you mean? Something similar what's in a way done on the Proxy service section. I have tried that initially to download the lists... but then got stuck again.
