### ISSUE TITLE
intrusion detection: reset alert logs

### ISSUE THREAD

**Issue by fichtner** [opnsense/core#997]
@lattera reports that there is no way of removing past alerts and I vaguely remember that there may be issues with the log rotation eating up disk space. How should we handle this?

**Comment by lattera** [comment]
From IRC:
```
01:51 < lattera> there's a script that runs that ends up taking 100% CPU and never seems to terminate when I search for all blocked alerts
01:52 < lattera> /usr/local/bin/python2.7 /usr/local/opnsense/scripts/suricata/queryAlertLog.py /limit 7 /offset 0 /filter alert,alert_action,src_ip/"*blocked*" /fileid
01:52 < lattera> I end up having to manually kill the script
01:55 < lattera> ah, it's because the python script starts eating up all RAM
01:55 < lattera> so the system starts swapping memory
01:56 < lattera> when the system only has 4GB of memory, but 11GB of Suricata alerts... :)
```

**Comment by AdSchellevis** [comment]
@lattera I can't reproduce the excessive memory usage.

Created a 7.2 GB  eve.json, and queried for something which is not in the dataset (to parse all record), during the time this is what my top looked like:
```
  PID USERNAME     THR PRI NICE   SIZE    RES STATE   C   TIME    WCPU COMMAND
59521 root           1  94    0 48004K  8276K CPU1    1   0:50  70.75% python2.7
```

I will try to add the "reset" option in time for the 16.7 release.

**Comment by AdSchellevis** [comment]
https://github.com/opnsense/core/commit/8de70201a70e07d0929ae1cb6fa8954dde482c5e adds configuration options for syslog, to manage the rotation and number of logs to keep. (default is once a week, which is not very practical when a lot of alerts are spawned)

**Comment by fichtner** [comment]
The following will probably create problems with the default config.xml that doesn't have IDS?

https://github.com/opnsense/core/commit/8de70201a70e07d0929ae1cb6fa8954dde482c5e#diff-c3e3ad31baa27142eb0f05dd663e59d7R5

**Comment by AdSchellevis** [comment]
I don't expect issues here, the outer if checks for the existence of the config section.

**Comment by fichtner** [comment]
Ah, sorry, only looked at the diff. My bad :)
