### ISSUE TITLE
Authentication: add pam module for console access using our standard authentication system

### ISSUE THREAD

**Issue by AdSchellevis** [opnsense/core#998]
It would be better to support PAM, so all configurable authentication options are also available for shell access. This would also remove the need for the ipsec user auth patch, strongswan supports pam by default.

**Comment by AdSchellevis** [comment]
ok, sshd pam ruleset is in, we probably should switch the default system console as well...
Normal operation is to use our helper, enabling all our auth helpers for console(ssh) access (like ldap, radius, totp), the user may switch to unix standard.

**Comment by fichtner** [comment]
I'm ok to switch login as well :)

**Comment by AdSchellevis** [comment]
ok, will fix that one too and close the issue when done.

**Comment by fichtner** [comment]
@AdSchellevis thinking about the default of using the PAM.... how about this:

flip "disableintegratedauth" to "integratedpamauth", so the default for existing installations is off, and put it onto config.xml.sample to be used only on factory reset and new installs?

**Comment by AdSchellevis** [comment]
@fichtner I'm not sure that's a good idea, if people want to use another authentication type you keep explaining that for their config the setting is probably disabled.... I would rather switch the default.
Unfortunately a lot of people still try to import old configs, although that's another topic, it would be good to warn people that importing other configs is generally not a good idea.

**Comment by fichtner** [comment]
@AdSchellevis ok, I'm fine with that. It just means I will have to postpone the switch to 16.7.10 or so just to make sure everything keeps working as expected.

I've set up TOTP now, will play with this for a while. :)

**Comment by AdSchellevis** [comment]
no rush ;)

**Comment by fichtner** [comment]
TOTP works great on SSH so far!!

What I could see was that there is a question about whether we want to switch other binaries as well: su, sudo, login. How much sense does it make to make them configurable one by one? What would be the best batch from your point of view if we keep it simple?

**Comment by AdSchellevis** [comment]
Nice :)
I'm not sure, the easiest thing to start with is to change all at once. When our pam module is used it's rather easy to add another config section to register the different services and preferred authentication methods (change or replace /system_usermanager_settings.php) 
Our module passes the type of service, which we can easily use to steer the behaviour. (this is what we need for ipsec at some point anyway)

**Comment by fichtner** [comment]
ok, interested to see how that pans out. then I'll shut up about this now. after login is added we shall be done for this iteration/ticket and figure out the rest later. :)

**Comment by fichtner** [comment]
@AdSchellevis the only blocker here is the login template, otherwise it could be on 16.7.11?

**Comment by AdSchellevis** [comment]
@fichtner login template, you mean normal gui? that's an optional switch.

**Comment by fichtner** [comment]
console pam.d file "login".. that's the one, right?

**Comment by AdSchellevis** [comment]
for normal serial/tty authentication, I expect so, yes. Eventually we can switch the gui to use pam too, but that's more 17.7 material.

**Comment by fichtner** [comment]
yup, for 17.1 ssd/login is all we need. We could add su and sudo, but this complicates privilege escalation too much IMO without having a knob for each service as discussed previously.

TLDR: on/off for sshd/login is all we need :)

**Comment by AdSchellevis** [comment]
https://github.com/opnsense/core/commit/ff8632c2c8d7ba43ec66751ea2adad7fae3f2de6
https://github.com/opnsense/core/commit/68de8c0225c552f8ec944da563b60ae1f085cbc3
https://github.com/opnsense/core/commit/643d2eef83397376bf7da792e04fbc1f6c3827f5
https://github.com/opnsense/core/commit/cc05a97726c615c73f5ea8f0cefb69c238158a76
https://github.com/opnsense/core/commit/cc05a97726c615c73f5ea8f0cefb69c238158a76

**Comment by fichtner** [comment]
@AdSchellevis 4ac59b3485631998eef6b0ebe25939076f4efdc3 23cf4fe10f74336fd7c8600e0d8f84f70f2708ea I think now we're good :)

**Comment by fichtner** [comment]
Ok, this one too https://github.com/opnsense/core/commit/7792d8ad7fa0a93a4827ec287ee688d371bd5709

**Comment by AdSchellevis** [comment]
:)

**Comment by fichtner** [comment]
Now I'm 94% sure it works :D
