### ISSUE TITLE
Corrupt netflow database

### ISSUE THREAD

**Issue by oparoz** [opnsense/core#999]
This is what I get after a restart on 16.1.16

```
Jun  8 12:13:59 Empyrion flowd_aggregate.py: flowd aggregate died with message Traceback (most recent call last):   File "/usr/local/opnsense/scripts/netflow/flowd_aggregate.py", line 145, in run     aggregate_flowd(do_vacuum)   File "/usr/local/opnsense/scripts/netflow/flowd_aggregate.py", line 85, in aggregate_flowd     stream_agg_object.cleanup(do_vacuum)   File "/usr/local/opnsense/scripts/netflow/lib/aggregate.py", line 281, in cleanup     self._update_cur.execute('vacuum') DatabaseError: database disk image is malformed
```

**Comment by AdSchellevis** [comment]
just to be sure, your not using a memory disk? and did the machine restart normally or was there a crash?

**Comment by oparoz** [comment]
1. I'm not using a memory disk, but I'm using the RAM disk feature which puts /var and /tmp in RAM
1. The machine has restarted normally

**Comment by AdSchellevis** [comment]
We should add some additional help text, ram disk is usually not a very good idea to store large amounts of data. I will add it to the help text for "Capture local".

**Comment by oparoz** [comment]
OK. I'll disable it and re-enable it once /var is moved out of the RAM disk then.

**Comment by oparoz** [comment]
But there may still be a bug in the script which makes a backup of the netflow DB every hour.
